Geant4: Track Class Reference
Track Class Reference
#include <Track.hh>
Public Member Functions
Track ()
~Track ()
const Step * GetStep () const
const Step * GetStep1 () const
const Step * GetStep2 () const
const Step * GetStep3 () const
const Step * GetStep4 () const
Private Attributes
Step * step
Detailed Description
Definition at line 42 of file Track.hh.
Constructor & Destructor Documentation
Track()
Track::Track ()
Definition at line 42 of file Track.cc.
~Track()
Track::~Track ()
Definition at line 51 of file Track.cc.
Member Function Documentation
GetStep()
const Step * Track::GetStep () const
Definition at line 61 of file Track.cc.
Referenced by GetStep1(), GetStep2(), GetStep3(), and GetStep4().
GetStep1()
const Step * Track::GetStep1 () const
Definition at line 69 of file Track.cc.
Referenced by BOOST_PYTHON_MODULE().
GetStep2()
const Step * Track::GetStep2 () const
Definition at line 76 of file Track.cc.
Referenced by BOOST_PYTHON_MODULE().
GetStep3()
const Step * Track::GetStep3 () const
Definition at line 83 of file Track.cc.
Referenced by BOOST_PYTHON_MODULE().
GetStep4()
const Step * Track::GetStep4 () const
Definition at line 90 of file Track.cc.
Field Documentation
step
Step* Track::step private
Definition at line 44 of file Track.hh.
Referenced by GetStep(), Track(), and ~Track().
The documentation for this class was generated from the following files:
environments/g4py/tests/test04/module/Track.hh
environments/g4py/tests/test04/module/Track.cc