Geant4: pyG4UImanager Namespace Reference
pyG4UImanager Namespace Reference
Functions
G4int ApplyUICommand_1 (const G4String &cmdstr)
G4int ApplyUICommand_2 (const std::string &cmdstr)
Variables
G4int(G4UImanager::* f1_ApplyCommand)(const char *) = &G4UImanager::ApplyCommand
G4int(G4UImanager::* f2_ApplyCommand)(const G4String &)
Function Documentation
ApplyUICommand_1()
G4int pyG4UImanager::ApplyUICommand_1 (const G4String & cmdstr)
Definition at line 55 of file pyG4UImanager.cc.
Referenced by ApplyUICommand_2(), and export_G4UImanager().
ApplyUICommand_2()
G4int pyG4UImanager::ApplyUICommand_2 (const std::string & cmdstr)
Definition at line 105 of file pyG4UImanager.cc.
Referenced by export_G4UImanager().
Variable Documentation
f1_ApplyCommand
G4int(G4UImanager::* pyG4UImanager::f1_ApplyCommand) (const char *) = &G4UImanager::ApplyCommand
Definition at line 46 of file pyG4UImanager.cc.
Referenced by export_G4UImanager().
f2_ApplyCommand
G4int(G4UImanager::* pyG4UImanager::f2_ApplyCommand) (const G4String &)
Initial value:
=
  &G4UImanager::ApplyCommand
Definition at line 47 of file pyG4UImanager.cc.
Referenced by export_G4UImanager().