Geant4: G4LogicalVolumeStore Class Reference
G4LogicalVolumeStore Class Reference
#include <G4LogicalVolumeStore.hh>
Public Member Functions
G4LogicalVolume * GetVolume (const G4String &name, G4bool verbose=true) const
virtual ~G4LogicalVolumeStore ()
Static Public Member Functions
static void Register (G4LogicalVolume *pVolume)
static void DeRegister (G4LogicalVolume *pVolume)
static G4LogicalVolumeStore * GetInstance ()
static void SetNotifier (G4VStoreNotifier *pNotifier)
static void Clean ()
Protected Member Functions
G4LogicalVolumeStore ()
Static Private Attributes
static G4LogicalVolumeStore * fgInstance = 0
static G4ThreadLocal G4VStoreNotifier * fgNotifier = 0
static G4ThreadLocal G4bool locked = false
Detailed Description
Definition at line 61 of file G4LogicalVolumeStore.hh.
Constructor & Destructor Documentation
~G4LogicalVolumeStore()
G4LogicalVolumeStore::~G4LogicalVolumeStore () virtual
Definition at line 63 of file G4LogicalVolumeStore.cc.
G4LogicalVolumeStore()
G4LogicalVolumeStore::G4LogicalVolumeStore () protected
Definition at line 53 of file G4LogicalVolumeStore.cc.
Member Function Documentation
Clean()
void G4LogicalVolumeStore::Clean () static
Definition at line 73 of file G4LogicalVolumeStore.cc.
Referenced by F04DetectorConstruction::Construct(), WLSDetectorConstruction::Construct(), DetectorConstruction::ConstructCalorimeter(), F02DetectorConstruction::ConstructCalorimeter(), F01DetectorConstruction::ConstructCalorimeter(), ExN03DetectorConstruction::ConstructCalorimeter(), F03DetectorConstruction::ConstructCalorimeter(), RMC01DetectorConstruction::ConstructSimpleGeometry(), DetectorConstruction::ConstructVolumes(), ElectronBenchmarkDetector::CreateGeometry(), DetectorConstruction::DefineVolumes(), G4RunManager::ReinitializeGeometry(), XrayFluoPlaneDetectorConstruction::UpdateGeometry(), XrayFluoMercuryDetectorConstruction::UpdateGeometry(), XrayFluoDetectorConstruction::UpdateGeometry(), and ~G4LogicalVolumeStore().
DeRegister()
void G4LogicalVolumeStore::DeRegister (G4LogicalVolume * pVolume) static
Definition at line 138 of file G4LogicalVolumeStore.cc.
Referenced by G4LogicalVolume::~G4LogicalVolume().
GetInstance()
G4LogicalVolumeStore * G4LogicalVolumeStore::GetInstance (void) static
Definition at line 181 of file G4LogicalVolumeStore.cc.
Referenced by G4GeometryManager::BuildOptimisations(), G4RunManagerKernel::CheckRegularGeometry(), checkVol(), Clean(), G4VUserDetectorConstruction::CloneF(), G4VUserDetectorConstruction::CloneSD(), GB06ParallelWorldForSlices::Construct(), F04DetectorConstruction::Construct(), WLSDetectorConstruction::Construct(), DetectorConstruction::ConstructCalorimeter(), F02DetectorConstruction::ConstructCalorimeter(), F01DetectorConstruction::ConstructCalorimeter(), ExN03DetectorConstruction::ConstructCalorimeter(), F03DetectorConstruction::ConstructCalorimeter(), GB06ParallelWorldForSlices::ConstructSD(), GB05DetectorConstruction::ConstructSDandField(), GB01DetectorConstruction::ConstructSDandField(), GB02DetectorConstruction::ConstructSDandField(), GB06DetectorConstruction::ConstructSDandField(), GB04DetectorConstruction::ConstructSDandField(), RMC01DetectorConstruction::ConstructSimpleGeometry(), DetectorConstruction::ConstructVolumes(), ElectronBenchmarkDetector::CreateGeometry(), DetectorConstruction::DefineVolumes(), G4GeometryManager::DeleteOptimisations(), DeRegister(), G4RadioactiveDecayBase::DeselectAVolume(), G4RadioactiveDecay::DeselectAVolume(), B2PrimaryGeneratorAction::GeneratePrimaries(), B4PrimaryGeneratorAction::GeneratePrimaries(), B1PrimaryGeneratorAction::GeneratePrimaries(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), DetectorConstruction::GetAbsorberMaterial(), DicomIntersectVolume::GetLogicalVolumes(), FFPrimaryGeneratorAction::GetNeutronSourceCenter(), G4Region::GetParentRegion(), G4GDMLReadStructure::GetVolume(), GetVolume(), G4GDMLParser::ImportRegions(), main(), Register(), G4RunManager::ReinitializeGeometry(), G4BlineTracer::ResetChordFinders(), G4RadioactiveDecayBase::SelectAllVolumes(), G4RadioactiveDecay::SelectAllVolumes(), G4RadioactiveDecayBase::SelectAVolume(), G4RadioactiveDecay::SelectAVolume(), G4VVisCommandGeometrySet::Set(), G4VisCommandGeometryList::SetNewValue(), G4GDMLMessenger::SetNewValue(), G4VisCommandGeometryRestore::SetNewValue(), G4VisCommandSceneAddLogicalVolume::SetNewValue(), SetNotifier(), G4VUserParallelWorld::SetSensitiveDetector(), G4VUserDetectorConstruction::SetSensitiveDetector(), CexmcSetup::SetupSpecialVolumes(), G4GDMLRead::StripNames(), G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster(), and F04SteppingAction::UserSteppingAction().
GetVolume()
G4LogicalVolume * G4LogicalVolumeStore::GetVolume (const G4String & name, G4bool verbose = true) const
Definition at line 159 of file G4LogicalVolumeStore.cc.
Referenced by GB06ParallelWorldForSlices::Construct(), GB06ParallelWorldForSlices::ConstructSD(), GB05DetectorConstruction::ConstructSDandField(), GB06DetectorConstruction::ConstructSDandField(), GB01DetectorConstruction::ConstructSDandField(), GB02DetectorConstruction::ConstructSDandField(), GB04DetectorConstruction::ConstructSDandField(), B2PrimaryGeneratorAction::GeneratePrimaries(), B4PrimaryGeneratorAction::GeneratePrimaries(), B1PrimaryGeneratorAction::GeneratePrimaries(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), DetectorConstruction::GetAbsorberMaterial(), FFPrimaryGeneratorAction::GetNeutronSourceCenter(), G4GDMLReadStructure::GetVolume(), G4GDMLParser::ImportRegions(), G4GDMLMessenger::SetNewValue(), and F04SteppingAction::UserSteppingAction().
Register()
void G4LogicalVolumeStore::Register (G4LogicalVolume * pVolume) static
Definition at line 128 of file G4LogicalVolumeStore.cc.
Referenced by G4LogicalVolume::G4LogicalVolume().
SetNotifier()
void G4LogicalVolumeStore::SetNotifier (G4VStoreNotifier * pNotifier) static
Definition at line 118 of file G4LogicalVolumeStore.cc.
Field Documentation
fgInstance
G4LogicalVolumeStore * G4LogicalVolumeStore::fgInstance = 0 static private
Definition at line 89 of file G4LogicalVolumeStore.hh.
Referenced by GetInstance().
fgNotifier
G4ThreadLocal G4VStoreNotifier * G4LogicalVolumeStore::fgNotifier = 0 static private
Definition at line 90 of file G4LogicalVolumeStore.hh.
Referenced by Clean(), DeRegister(), Register(), and SetNotifier().
locked
G4ThreadLocal G4bool G4LogicalVolumeStore::locked = false static private
Definition at line 91 of file G4LogicalVolumeStore.hh.
Referenced by Clean(), and DeRegister().
The documentation for this class was generated from the following files:
source/geometry/management/include/G4LogicalVolumeStore.hh
source/geometry/management/src/G4LogicalVolumeStore.cc