Geant4: source/processes/hadronic/models/lend/src/MCGIDI_LLNLAngular_angularEnergy.cc File Reference
MCGIDI_LLNLAngular_angularEnergy.cc File Reference
#include <string.h>
#include "MCGIDI.h"
#include "MCGIDI_fromTOM.h"
#include "MCGIDI_misc.h"
#include "MCGIDI_private.h"
Functions
static int MCGIDI_LLNL_angularEnergy_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_distribution *distribution)
static int MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM (statusMessageReporting *smr, xDataTOM_element *pointwise, MCGIDI_distribution *distribution)
int MCGIDI_LLNLAngular_angularEnergy_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_distribution *distribution)
Function Documentation
MCGIDI_LLNL_angularEnergy_parseFromTOM()
static int MCGIDI_LLNL_angularEnergy_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_distribution * distribution) static
Definition at line 40 of file MCGIDI_LLNLAngular_angularEnergy.cc.
Referenced by MCGIDI_LLNLAngular_angularEnergy_parseFromTOM().
MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM()
static int MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM (statusMessageReporting * smr, xDataTOM_element * pointwise, MCGIDI_distribution * distribution) static
Definition at line 66 of file MCGIDI_LLNLAngular_angularEnergy.cc.
Referenced by MCGIDI_LLNL_angularEnergy_parseFromTOM().
MCGIDI_LLNLAngular_angularEnergy_parseFromTOM()
int MCGIDI_LLNLAngular_angularEnergy_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_distribution * distribution)
Definition at line 22 of file MCGIDI_LLNLAngular_angularEnergy.cc.
Referenced by MCGIDI_distribution_parseFromTOM().