Geant4: G4RDAtomicShell Class Reference
G4RDAtomicShell Class Reference
#include <G4RDAtomicShell.hh>
Public Member Functions
G4RDAtomicShell (G4int, G4double)
~G4RDAtomicShell ()
G4double BindingEnergy () const
G4int ShellId () const
Private Attributes
G4int identifier
G4double bindingEnergy
Detailed Description
Definition at line 50 of file G4RDAtomicShell.hh.
Constructor & Destructor Documentation
G4RDAtomicShell()
G4RDAtomicShell::G4RDAtomicShell (G4int id, G4double energy)
Definition at line 40 of file G4RDAtomicShell.cc.
~G4RDAtomicShell()
G4RDAtomicShell::~G4RDAtomicShell ()
Definition at line 46 of file G4RDAtomicShell.cc.
Member Function Documentation
BindingEnergy()
G4double G4RDAtomicShell::BindingEnergy () const
Definition at line 49 of file G4RDAtomicShell.cc.
Referenced by G4LowEnergyIonisation::DeexciteAtom(), G4LowEnergyPhotoElectric::PostStepDoIt(), and G4LowEnergyIonisation::PostStepDoIt().
ShellId()
G4int G4RDAtomicShell::ShellId () const
Definition at line 55 of file G4RDAtomicShell.cc.
Referenced by G4LowEnergyIonisation::DeexciteAtom(), G4LowEnergyPhotoElectric::PostStepDoIt(), and G4LowEnergyIonisation::PostStepDoIt().
Field Documentation
bindingEnergy
G4double G4RDAtomicShell::bindingEnergy private
Definition at line 70 of file G4RDAtomicShell.hh.
Referenced by BindingEnergy(), and G4RDAtomicShell().
identifier
G4int G4RDAtomicShell::identifier private
Definition at line 69 of file G4RDAtomicShell.hh.
Referenced by G4RDAtomicShell(), and ShellId().
The documentation for this class was generated from the following files:
examples/advanced/eRosita/physics/include/G4RDAtomicShell.hh
examples/advanced/eRosita/physics/src/G4RDAtomicShell.cc