Geant4: G4RootMpiPNtupleManager Class Reference
G4RootMpiPNtupleManager Class Reference
#include <G4RootMpiPNtupleManager.hh>
Public Member Functions
G4RootMpiPNtupleManager (const G4AnalysisManagerState &state, G4bool rowWise, tools::impi *impi, G4int mpiRank, G4int destinationRank)
~G4RootMpiPNtupleManager ()
Public Member Functions inherited from G4BaseNtupleManager
G4BaseNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4BaseNtupleManager ()
G4BaseNtupleManager (const G4BaseNtupleManager &rhs)=delete
G4BaseNtupleManager & operator= (const G4BaseNtupleManager &rhs)=delete
Public Member Functions inherited from G4VNtupleManager
G4VNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4VNtupleManager ()
G4VNtupleManager (const G4VNtupleManager &rhs)=delete
G4VNtupleManager & operator= (const G4VNtupleManager &rhs)=delete
Public Member Functions inherited from G4BaseAnalysisManager
G4BaseAnalysisManager (const G4AnalysisManagerState &state)
virtual ~G4BaseAnalysisManager ()
G4bool SetFirstId (G4int firstId)
void SetLockFirstId (G4bool lockFirstId)
G4int GetFirstId () const
Private Types
enum G4PNtupleCreateMode { G4PNtupleCreateMode::kSlaveBeforeOpen, G4PNtupleCreateMode::kSlaveAfterOpen, G4PNtupleCreateMode::kUndefined }
Private Member Functions
void SetNtupleDirectory (tools::wroot::directory *directory)
void SetFileManager (std::shared_ptr< G4RootFileManager > fileManager)
void CreateNtuple (G4RootMpiPNtupleDescription *ntupleDescription)
void CreateNtuplesFromBooking ()
virtual G4int CreateNtuple (const G4String &name, const G4String &title) final
virtual G4int CreateNtupleIColumn (G4int ntupleId, const G4String &name, std::vector< int > *vector) final
virtual G4int CreateNtupleFColumn (G4int ntupleId, const G4String &name, std::vector< float > *vector) final
virtual G4int CreateNtupleDColumn (G4int ntupleId, const G4String &name, std::vector< double > *vector) final
virtual G4int CreateNtupleSColumn (G4int ntupleId, const G4String &name) final
virtual void FinishNtuple (G4int ntupleId) final
virtual G4bool FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value) final
virtual G4bool FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value) final
virtual G4bool FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value) final
virtual G4bool FillNtupleSColumn (G4int ntupleId, G4int columnId, const G4String &value) final
virtual G4bool AddNtupleRow (G4int ntupleId) final
virtual G4bool Merge () final
virtual G4bool Reset (G4bool deleteNtuple) final
virtual void SetActivation (G4bool activation) final
virtual void SetActivation (G4int ntupleId, G4bool activation) final
virtual G4bool GetActivation (G4int ntupleId) const final
virtual G4bool IsEmpty () const final
virtual G4int GetNofNtuples () const final
virtual G4int GetNofNtupleBookings () const final
const std::vector< G4RootMpiPNtupleDescription * > & GetNtupleDescriptionVector () const
unsigned int GetBasketSize () const
G4RootMpiPNtupleDescription * GetNtupleDescriptionInFunction (G4int id, G4String function, G4bool warn=true) const
tools::wroot::base_pntuple * GetNtupleInFunction (G4int id, G4String function, G4bool warn=true) const
template<typename T >
G4int CreateNtupleTColumn (G4int ntupleId, const G4String &name, std::vector< T > *vector)
template<typename T >
G4int CreateNtupleTColumn (const G4String &name, std::vector< T > *vector)
template<typename T >
G4bool FillNtupleTColumn (G4int ntupleId, G4int columnId, const T &value)
template<>
G4bool FillNtupleTColumn (G4int ntupleId, G4int columnId, const std::string &value)
Private Attributes
std::shared_ptr< G4RootFileManager > fFileManager
tools::wroot::directory * fNtupleDirectory
std::vector< G4RootMpiPNtupleDescription * > fNtupleDescriptionVector
std::vector< tools::wroot::impi_ntuple * > fNtupleVector
G4bool fRowWise
tools::impi * fImpi
G4int fMpiRank
G4int fDestinationRank
Friends
class G4RootMpiAnalysisManager
class G4RootAnalysisManager
class G4RootNtupleManager
Additional Inherited Members
Protected Member Functions inherited from G4BaseNtupleManager
virtual G4int CreateNtupleIColumn (const G4String &name, std::vector< int > *vector) final
virtual G4int CreateNtupleFColumn (const G4String &name, std::vector< float > *vector) final
virtual G4int CreateNtupleDColumn (const G4String &name, std::vector< double > *vector) final
virtual G4int CreateNtupleSColumn (const G4String &name)
virtual void FinishNtuple () final
virtual G4bool SetFirstNtupleColumnId (G4int firstId) final
G4int GetFirstNtupleColumnId () const final
virtual G4bool FillNtupleIColumn (G4int id, G4int value) final
virtual G4bool FillNtupleFColumn (G4int id, G4float value) final
virtual G4bool FillNtupleDColumn (G4int id, G4double value) final
virtual G4bool FillNtupleSColumn (G4int id, const G4String &value) final
virtual G4bool AddNtupleRow () final
Protected Attributes inherited from G4BaseNtupleManager
G4int fFirstNtupleColumnId
G4bool fLockFirstNtupleColumnId
Protected Attributes inherited from G4BaseAnalysisManager
const G4AnalysisManagerState & fState
G4int fFirstId
G4bool fLockFirstId
Detailed Description
Definition at line 58 of file G4RootMpiPNtupleManager.hh.
Member Enumeration Documentation
G4PNtupleCreateMode
enum G4RootMpiPNtupleManager::G4PNtupleCreateMode strong private
Enumerator
kSlaveBeforeOpen
kSlaveAfterOpen
kUndefined
Definition at line 70 of file G4RootMpiPNtupleManager.hh.
Constructor & Destructor Documentation
G4RootMpiPNtupleManager()
G4RootMpiPNtupleManager::G4RootMpiPNtupleManager (const G4AnalysisManagerState & state, G4bool rowWise, tools::impi * impi, G4int mpiRank, G4int destinationRank) explicit
Definition at line 41 of file G4RootMpiPNtupleManager.cc.
~G4RootMpiPNtupleManager()
G4RootMpiPNtupleManager::~G4RootMpiPNtupleManager ()
Definition at line 54 of file G4RootMpiPNtupleManager.cc.
Member Function Documentation
AddNtupleRow()
G4bool G4RootMpiPNtupleManager::AddNtupleRow (G4int ntupleId) final private virtual
Implements G4BaseNtupleManager.
Definition at line 352 of file G4RootMpiPNtupleManager.cc.
CreateNtuple() [1/2]
G4int G4RootMpiPNtupleManager::CreateNtuple (const G4String & name, const G4String & title) final private virtual
Implements G4BaseNtupleManager.
Definition at line 257 of file G4RootMpiPNtupleManager.cc.
CreateNtuple() [2/2]
void G4RootMpiPNtupleManager::CreateNtuple (G4RootMpiPNtupleDescription * ntupleDescription) private
Definition at line 110 of file G4RootMpiPNtupleManager.cc.
Referenced by CreateNtuplesFromBooking().
CreateNtupleDColumn()
G4int G4RootMpiPNtupleManager::CreateNtupleDColumn (G4int ntupleId, const G4String & name, std::vector< double > * vector) final private virtual
Implements G4BaseNtupleManager.
Definition at line 306 of file G4RootMpiPNtupleManager.cc.
CreateNtupleFColumn()
G4int G4RootMpiPNtupleManager::CreateNtupleFColumn (G4int ntupleId, const G4String & name, std::vector< float > * vector) final private virtual
Implements G4BaseNtupleManager.
Definition at line 299 of file G4RootMpiPNtupleManager.cc.
CreateNtupleIColumn()
G4int G4RootMpiPNtupleManager::CreateNtupleIColumn (G4int ntupleId, const G4String & name, std::vector< int > * vector) final private virtual
Implements G4BaseNtupleManager.
Definition at line 292 of file G4RootMpiPNtupleManager.cc.
CreateNtupleSColumn()
G4int G4RootMpiPNtupleManager::CreateNtupleSColumn (G4int ntupleId, const G4String & name) final private virtual
Implements G4BaseNtupleManager.
Definition at line 313 of file G4RootMpiPNtupleManager.cc.
CreateNtuplesFromBooking()
void G4RootMpiPNtupleManager::CreateNtuplesFromBooking () private
Definition at line 215 of file G4RootMpiPNtupleManager.cc.
Referenced by G4RootMpiAnalysisManager::OpenFileImpl().
CreateNtupleTColumn() [1/2]
template<typename T > G4int G4RootMpiPNtupleManager::CreateNtupleTColumn (const G4String & name, std::vector< T > * vector) private
CreateNtupleTColumn() [2/2]
template<typename T > G4int G4RootMpiPNtupleManager::CreateNtupleTColumn (G4int ntupleId, const G4String & name, std::vector< T > * vector) private
Definition at line 169 of file G4RootMpiPNtupleManager.hh.
FillNtupleDColumn()
G4bool G4RootMpiPNtupleManager::FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value) final private virtual
Implements G4BaseNtupleManager.
Definition at line 338 of file G4RootMpiPNtupleManager.cc.
FillNtupleFColumn()
G4bool G4RootMpiPNtupleManager::FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value) final private virtual
Implements G4BaseNtupleManager.
Definition at line 331 of file G4RootMpiPNtupleManager.cc.
FillNtupleIColumn()
G4bool G4RootMpiPNtupleManager::FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value) final private virtual
Implements G4BaseNtupleManager.
Definition at line 324 of file G4RootMpiPNtupleManager.cc.
FillNtupleSColumn()
G4bool G4RootMpiPNtupleManager::FillNtupleSColumn (G4int ntupleId, G4int columnId, const G4String & value) final private virtual
Implements G4BaseNtupleManager.
Definition at line 345 of file G4RootMpiPNtupleManager.cc.
FillNtupleTColumn() [1/2]
template<> G4bool G4RootMpiPNtupleManager::FillNtupleTColumn (G4int ntupleId, G4int columnId, const std::string & value) inline private
Definition at line 207 of file G4RootMpiPNtupleManager.hh.
FillNtupleTColumn() [2/2]
template<typename T > G4bool G4RootMpiPNtupleManager::FillNtupleTColumn (G4int ntupleId, G4int columnId, const T & value) private
Definition at line 264 of file G4RootMpiPNtupleManager.hh.
FinishNtuple()
void G4RootMpiPNtupleManager::FinishNtuple (G4int ntupleId) final private virtual
Implements G4BaseNtupleManager.
Definition at line 320 of file G4RootMpiPNtupleManager.cc.
GetActivation()
G4bool G4RootMpiPNtupleManager::GetActivation (G4int ntupleId) const final private virtual
Implements G4VNtupleManager.
Definition at line 485 of file G4RootMpiPNtupleManager.cc.
Referenced by AddNtupleRow(), and FillNtupleTColumn().
GetBasketSize()
unsigned int G4RootMpiPNtupleManager::GetBasketSize () const private
Definition at line 513 of file G4RootMpiPNtupleManager.cc.
GetNofNtupleBookings()
G4int G4RootMpiPNtupleManager::GetNofNtupleBookings () const final private virtual
Implements G4VNtupleManager.
Definition at line 501 of file G4RootMpiPNtupleManager.cc.
GetNofNtuples()
G4int G4RootMpiPNtupleManager::GetNofNtuples () const final private virtual
Implements G4VNtupleManager.
Definition at line 495 of file G4RootMpiPNtupleManager.cc.
GetNtupleDescriptionInFunction()
G4RootMpiPNtupleDescription * G4RootMpiPNtupleManager::GetNtupleDescriptionInFunction (G4int id, G4String function, G4bool warn = true) const private
Definition at line 67 of file G4RootMpiPNtupleManager.cc.
Referenced by AddNtupleRow(), CreateNtupleTColumn(), GetActivation(), GetNtupleInFunction(), and SetActivation().
GetNtupleDescriptionVector()
const std::vector< G4RootMpiPNtupleDescription * > & G4RootMpiPNtupleManager::GetNtupleDescriptionVector () const inline private
Definition at line 163 of file G4RootMpiPNtupleManager.hh.
GetNtupleInFunction()
tools::wroot::base_pntuple * G4RootMpiPNtupleManager::GetNtupleInFunction (G4int id, G4String function, G4bool warn = true) const private
Definition at line 86 of file G4RootMpiPNtupleManager.cc.
Referenced by FillNtupleTColumn().
IsEmpty()
G4bool G4RootMpiPNtupleManager::IsEmpty () const final private virtual
Definition at line 507 of file G4RootMpiPNtupleManager.cc.
Merge()
G4bool G4RootMpiPNtupleManager::Merge () final private virtual
Definition at line 395 of file G4RootMpiPNtupleManager.cc.
Referenced by G4RootMpiAnalysisManager::WriteNtuple().
Reset()
G4bool G4RootMpiPNtupleManager::Reset (G4bool deleteNtuple) final private virtual
Definition at line 449 of file G4RootMpiPNtupleManager.cc.
Referenced by G4RootMpiAnalysisManager::Reset().
SetActivation() [1/2]
void G4RootMpiPNtupleManager::SetActivation (G4bool activation) final private virtual
Implements G4VNtupleManager.
Definition at line 465 of file G4RootMpiPNtupleManager.cc.
SetActivation() [2/2]
void G4RootMpiPNtupleManager::SetActivation (G4int ntupleId, G4bool activation) final private virtual
Implements G4VNtupleManager.
Definition at line 475 of file G4RootMpiPNtupleManager.cc.
SetFileManager()
void G4RootMpiPNtupleManager::SetFileManager (std::shared_ptr< G4RootFileManager > fileManager) inline private
Definition at line 159 of file G4RootMpiPNtupleManager.hh.
SetNtupleDirectory()
void G4RootMpiPNtupleManager::SetNtupleDirectory (tools::wroot::directory * directory) inline private
Definition at line 155 of file G4RootMpiPNtupleManager.hh.
Friends And Related Function Documentation
G4RootAnalysisManager
friend class G4RootAnalysisManager friend
Definition at line 61 of file G4RootMpiPNtupleManager.hh.
G4RootMpiAnalysisManager
friend class G4RootMpiAnalysisManager friend
Definition at line 60 of file G4RootMpiPNtupleManager.hh.
G4RootNtupleManager
friend class G4RootNtupleManager friend
Definition at line 62 of file G4RootMpiPNtupleManager.hh.
Field Documentation
fDestinationRank
G4int G4RootMpiPNtupleManager::fDestinationRank private
Definition at line 149 of file G4RootMpiPNtupleManager.hh.
Referenced by CreateNtuple().
fFileManager
std::shared_ptr<G4RootFileManager> G4RootMpiPNtupleManager::fFileManager private
Definition at line 142 of file G4RootMpiPNtupleManager.hh.
Referenced by GetBasketSize(), and SetFileManager().
fImpi
tools::impi* G4RootMpiPNtupleManager::fImpi private
Definition at line 147 of file G4RootMpiPNtupleManager.hh.
Referenced by AddNtupleRow(), CreateNtuple(), and Merge().
fMpiRank
G4int G4RootMpiPNtupleManager::fMpiRank private
Definition at line 148 of file G4RootMpiPNtupleManager.hh.
Referenced by CreateNtuple().
fNtupleDescriptionVector
std::vector<G4RootMpiPNtupleDescription*> G4RootMpiPNtupleManager::fNtupleDescriptionVector private
Definition at line 144 of file G4RootMpiPNtupleManager.hh.
Referenced by CreateNtuple(), CreateNtuplesFromBooking(), GetNofNtupleBookings(), GetNtupleDescriptionInFunction(), GetNtupleDescriptionVector(), IsEmpty(), Merge(), Reset(), SetActivation(), and ~G4RootMpiPNtupleManager().
fNtupleDirectory
tools::wroot::directory* G4RootMpiPNtupleManager::fNtupleDirectory private
Definition at line 143 of file G4RootMpiPNtupleManager.hh.
Referenced by SetNtupleDirectory().
fNtupleVector
std::vector<tools::wroot::impi_ntuple*> G4RootMpiPNtupleManager::fNtupleVector private
Definition at line 145 of file G4RootMpiPNtupleManager.hh.
Referenced by CreateNtuple(), CreateNtuplesFromBooking(), GetNofNtuples(), and Reset().
fRowWise
G4bool G4RootMpiPNtupleManager::fRowWise private
Definition at line 146 of file G4RootMpiPNtupleManager.hh.
Referenced by CreateNtuple().
The documentation for this class was generated from the following files:
examples/extended/parallel/MPI/source/analysis/include/G4RootMpiPNtupleManager.hh
examples/extended/parallel/MPI/source/analysis/src/G4RootMpiPNtupleManager.cc