Geant4: G4FileUtilities Class Reference
G4FileUtilities Class Reference
#include <G4FileUtilities.hh>
Public Member Functions
G4FileUtilities ()
~G4FileUtilities ()
G4bool FileExists (const std::string file)
std::string StrErrNo () const
G4int Shell (std::string str)
G4int CopyFile (const std::string srcFile, const std::string dstFile)
G4int DeleteFile (const std::string file, const std::string option)
std::string GetEnv (const std::string env)
Detailed Description
Definition at line 49 of file G4FileUtilities.hh.
Constructor & Destructor Documentation
G4FileUtilities()
G4FileUtilities::G4FileUtilities ()
Definition at line 36 of file G4FileUtilities.cc.
~G4FileUtilities()
G4FileUtilities::~G4FileUtilities ()
Definition at line 41 of file G4FileUtilities.cc.
Member Function Documentation
CopyFile()
G4int G4FileUtilities::CopyFile (const std::string srcFile, const std::string dstFile)
Definition at line 61 of file G4FileUtilities.cc.
DeleteFile()
G4int G4FileUtilities::DeleteFile (const std::string file, const std::string option)
Definition at line 68 of file G4FileUtilities.cc.
FileExists()
G4bool G4FileUtilities::FileExists (const std::string file)
Definition at line 46 of file G4FileUtilities.cc.
Referenced by G4PersistencyCenter::SetReadFile().
GetEnv()
std::string G4FileUtilities::GetEnv (const std::string env) inline
Definition at line 74 of file G4FileUtilities.hh.
Shell()
G4int G4FileUtilities::Shell (std::string str) inline
Definition at line 65 of file G4FileUtilities.hh.
Referenced by CopyFile(), and DeleteFile().
StrErrNo()
std::string G4FileUtilities::StrErrNo () const inline
Definition at line 62 of file G4FileUtilities.hh.
The documentation for this class was generated from the following files:
source/persistency/mctruth/include/G4FileUtilities.hh
source/persistency/mctruth/src/G4FileUtilities.cc