Geant4: G4tgbVolume Class Reference
G4tgbVolume Class Reference
#include <G4tgbVolume.hh>
Public Member Functions
G4tgbVolume ()
~G4tgbVolume ()
G4tgbVolume (G4tgrVolume *vol)
void ConstructG4Volumes (const G4tgrPlace *place, const G4LogicalVolume *parentLV)
G4VSolid * FindOrConstructG4Solid (const G4tgrSolid *vol)
G4LogicalVolume * ConstructG4LogVol (const G4VSolid *solid)
G4VPhysicalVolume * ConstructG4PhysVol (const G4tgrPlace *place, const G4LogicalVolume *currentLV, const G4LogicalVolume *parentLV)
void SetCutsInRange (G4LogicalVolume *logvol, std::map< G4String, G4double > cuts)
void SetCutsInEnergy (G4LogicalVolume *logvol, std::map< G4String, G4double > cuts)
void CheckNoSolidParams (const G4String &solidType, const unsigned int NoParamExpected, const unsigned int NoParam)
G4VSolid * BuildSolidForDivision (G4VSolid *parentSolid, EAxis axis)
const G4String & GetName () const
G4bool GetVisibility () const
const G4double * GetColour () const
Private Attributes
G4tgrVolume * theTgrVolume
G4AssemblyVolume * theG4AssemblyVolume
Detailed Description
Definition at line 65 of file G4tgbVolume.hh.
Constructor & Destructor Documentation
G4tgbVolume() [1/2]
G4tgbVolume::G4tgbVolume ()
Definition at line 109 of file G4tgbVolume.cc.
~G4tgbVolume()
G4tgbVolume::~G4tgbVolume ()
Definition at line 116 of file G4tgbVolume.cc.
G4tgbVolume() [2/2]
G4tgbVolume::G4tgbVolume (G4tgrVolume * vol)
Definition at line 122 of file G4tgbVolume.cc.
Member Function Documentation
BuildSolidForDivision()
G4VSolid * G4tgbVolume::BuildSolidForDivision (G4VSolid * parentSolid, EAxis axis)
Definition at line 1183 of file G4tgbVolume.cc.
Referenced by ConstructG4PhysVol().
CheckNoSolidParams()
void G4tgbVolume::CheckNoSolidParams (const G4String & solidType, const unsigned int NoParamExpected, const unsigned int NoParam)
Definition at line 705 of file G4tgbVolume.cc.
Referenced by FindOrConstructG4Solid().
ConstructG4LogVol()
G4LogicalVolume * G4tgbVolume::ConstructG4LogVol (const G4VSolid * solid)
Definition at line 724 of file G4tgbVolume.cc.
Referenced by ConstructG4Volumes().
ConstructG4PhysVol()
G4VPhysicalVolume * G4tgbVolume::ConstructG4PhysVol (const G4tgrPlace * place, const G4LogicalVolume * currentLV, const G4LogicalVolume * parentLV)
Definition at line 815 of file G4tgbVolume.cc.
Referenced by ConstructG4Volumes().
ConstructG4Volumes()
void G4tgbVolume::ConstructG4Volumes (const G4tgrPlace * place, const G4LogicalVolume * parentLV)
Definition at line 130 of file G4tgbVolume.cc.
Referenced by G4tgbDetectorConstruction::Construct(), G4tgbDetectorBuilder::ConstructDetector(), ConstructG4PhysVol(), and ConstructG4Volumes().
FindOrConstructG4Solid()
G4VSolid * G4tgbVolume::FindOrConstructG4Solid (const G4tgrSolid * vol)
Definition at line 208 of file G4tgbVolume.cc.
Referenced by DicomIntersectVolume::BuildUserSolid(), and ConstructG4Volumes().
GetColour()
const G4double* G4tgbVolume::GetColour () const inline
Definition at line 109 of file G4tgbVolume.hh.
Referenced by ConstructG4LogVol().
GetName()
const G4String& G4tgbVolume::GetName (void) const inline
Definition at line 107 of file G4tgbVolume.hh.
Referenced by BuildSolidForDivision(), ConstructG4LogVol(), ConstructG4PhysVol(), ConstructG4Volumes(), and G4tgbVolumeMgr::RegisterMe().
GetVisibility()
G4bool G4tgbVolume::GetVisibility () const inline
Definition at line 108 of file G4tgbVolume.hh.
Referenced by ConstructG4LogVol().
SetCutsInEnergy()
void G4tgbVolume::SetCutsInEnergy (G4LogicalVolume * logvol, std::map< G4String, G4double > cuts)
SetCutsInRange()
void G4tgbVolume::SetCutsInRange (G4LogicalVolume * logvol, std::map< G4String, G4double > cuts)
Field Documentation
theG4AssemblyVolume
G4AssemblyVolume* G4tgbVolume::theG4AssemblyVolume private
Definition at line 116 of file G4tgbVolume.hh.
Referenced by ConstructG4PhysVol(), and G4tgbVolume().
theTgrVolume
G4tgrVolume* G4tgbVolume::theTgrVolume private
Definition at line 113 of file G4tgbVolume.hh.
Referenced by ConstructG4LogVol(), ConstructG4PhysVol(), ConstructG4Volumes(), G4tgbVolume(), GetColour(), GetName(), and GetVisibility().
The documentation for this class was generated from the following files:
source/persistency/ascii/include/G4tgbVolume.hh
source/persistency/ascii/src/G4tgbVolume.cc