Geant4: G4VisExtent Class Reference
G4VisExtent Class Reference
#include <G4VisExtent.hh>
Public Member Functions
G4VisExtent (G4double xmin=0., G4double xmax=0., G4double ymin=0., G4double ymax=0., G4double zmin=0., G4double zmax=0.)
G4VisExtent (const G4Point3D &centre, G4double radius)
~G4VisExtent ()
G4bool operator!= (const G4VisExtent &e) const
G4bool operator== (const G4VisExtent &e) const
G4double GetXmin () const
G4double GetXmax () const
G4double GetYmin () const
G4double GetYmax () const
G4double GetZmin () const
G4double GetZmax () const
const G4Point3D & GetExtentCentre () const
const G4Point3D & GetExtentCenter () const
G4double GetExtentRadius () const
void SetXmin (G4double xmin)
void SetXmax (G4double xmax)
void SetYmin (G4double ymin)
void SetYmax (G4double ymax)
void SetZmin (G4double zmin)
void SetZmax (G4double zmax)
Static Public Member Functions
static const G4VisExtent & GetNullExtent ()
Private Attributes
G4double fXmin
G4double fXmax
G4double fYmin
G4double fYmax
G4double fZmin
G4double fZmax
G4bool fRadiusCached
G4bool fCentreCached
G4double fRadius
G4Point3D fCentre
Friends
std::ostream & operator<< (std::ostream &os, const G4VisExtent &e)
Detailed Description
Definition at line 53 of file G4VisExtent.hh.
Constructor & Destructor Documentation
G4VisExtent() [1/2]
G4VisExtent::G4VisExtent (G4double xmin = 0., G4double xmax = 0., G4double ymin = 0., G4double ymax = 0., G4double zmin = 0., G4double zmax = 0.)
Definition at line 37 of file G4VisExtent.cc.
Referenced by GetNullExtent().
G4VisExtent() [2/2]
G4VisExtent::G4VisExtent (const G4Point3D & centre, G4double radius)
Definition at line 44 of file G4VisExtent.cc.
~G4VisExtent()
G4VisExtent::~G4VisExtent ()
Definition at line 58 of file G4VisExtent.cc.
Member Function Documentation
GetExtentCenter()
const G4Point3D & G4VisExtent::GetExtentCenter () const inline
Definition at line 96 of file G4VisExtent.hh.
GetExtentCentre()
const G4Point3D & G4VisExtent::GetExtentCentre () const
Definition at line 65 of file G4VisExtent.cc.
Referenced by G4Scene::CalculateExtent(), G4VSceneHandler::CreateSectionSolid(), GetExtentCenter(), and G4BoundingSphereScene::ProcessVolume().
GetExtentRadius()
G4double G4VisExtent::GetExtentRadius () const
Definition at line 75 of file G4VisExtent.cc.
Referenced by G4VisCommandSceneAddUserAction::AddVisAction(), G4Scene::CalculateExtent(), G4VSceneHandler::CreateSectionSolid(), G4BoundingSphereScene::ProcessVolume(), G4VisManager::RegisterEndOfEventUserVisAction(), G4VisManager::RegisterEndOfRunUserVisAction(), G4VisManager::RegisterRunDurationUserVisAction(), G4VRML2FileViewer::SendViewParameters(), G4DAWNFILEViewer::SendViewParameters(), G4VisCommandSceneAddArrow::SetNewValue(), G4VisCommandSceneAddAxes::SetNewValue(), G4VisCommandSceneAddLogicalVolume::SetNewValue(), G4VisCommandSceneAddLogo::SetNewValue(), G4VisCommandSceneAddScale::SetNewValue(), and G4RayTracerViewer::SetView().
GetNullExtent()
const G4VisExtent & G4VisExtent::GetNullExtent () static
Definition at line 60 of file G4VisExtent.cc.
Referenced by G4VSceneHandler::ProcessScene().
GetXmax()
G4double G4VisExtent::GetXmax () const inline
Definition at line 90 of file G4VisExtent.hh.
Referenced by G4VSceneHandler::AddPrimitive(), G4tgbVolume::BuildSolidForDivision(), G4MagneticFieldModel::DescribeYourselfTo(), G4VisCommandSceneAddLogo::SetNewValue(), and G4VisCommandSceneAddScale::SetNewValue().
GetXmin()
G4double G4VisExtent::GetXmin () const inline
Definition at line 89 of file G4VisExtent.hh.
Referenced by G4VSceneHandler::AddPrimitive(), G4tgbVolume::BuildSolidForDivision(), G4MagneticFieldModel::DescribeYourselfTo(), G4VisCommandSceneAddLogo::SetNewValue(), and G4VisCommandSceneAddScale::SetNewValue().
GetYmax()
G4double G4VisExtent::GetYmax () const inline
Definition at line 92 of file G4VisExtent.hh.
Referenced by G4VSceneHandler::AddPrimitive(), G4tgbVolume::BuildSolidForDivision(), G4MagneticFieldModel::DescribeYourselfTo(), G4VisCommandSceneAddLogo::SetNewValue(), and G4VisCommandSceneAddScale::SetNewValue().
GetYmin()
G4double G4VisExtent::GetYmin () const inline
Definition at line 91 of file G4VisExtent.hh.
Referenced by G4VSceneHandler::AddPrimitive(), G4tgbVolume::BuildSolidForDivision(), G4MagneticFieldModel::DescribeYourselfTo(), G4VisCommandSceneAddLogo::SetNewValue(), and G4VisCommandSceneAddScale::SetNewValue().
GetZmax()
G4double G4VisExtent::GetZmax () const inline
Definition at line 94 of file G4VisExtent.hh.
Referenced by G4VSceneHandler::AddPrimitive(), G4tgbVolume::BuildSolidForDivision(), G4MagneticFieldModel::DescribeYourselfTo(), G4VisCommandSceneAddLogo::SetNewValue(), and G4VisCommandSceneAddScale::SetNewValue().
GetZmin()
G4double G4VisExtent::GetZmin () const inline
Definition at line 93 of file G4VisExtent.hh.
Referenced by G4VSceneHandler::AddPrimitive(), G4tgbVolume::BuildSolidForDivision(), G4MagneticFieldModel::DescribeYourselfTo(), G4VisCommandSceneAddLogo::SetNewValue(), and G4VisCommandSceneAddScale::SetNewValue().
operator!=()
G4bool G4VisExtent::operator!= (const G4VisExtent & e) const
Definition at line 93 of file G4VisExtent.cc.
Referenced by operator==().
operator==()
G4bool G4VisExtent::operator== (const G4VisExtent & e) const inline
Definition at line 64 of file G4VisExtent.hh.
SetXmax()
void G4VisExtent::SetXmax (G4double xmax) inline
Definition at line 102 of file G4VisExtent.hh.
Referenced by G4VSolid::GetExtent().
SetXmin()
void G4VisExtent::SetXmin (G4double xmin) inline
Definition at line 100 of file G4VisExtent.hh.
Referenced by G4VSolid::GetExtent().
SetYmax()
void G4VisExtent::SetYmax (G4double ymax) inline
Definition at line 106 of file G4VisExtent.hh.
Referenced by G4VSolid::GetExtent().
SetYmin()
void G4VisExtent::SetYmin (G4double ymin) inline
Definition at line 104 of file G4VisExtent.hh.
Referenced by G4VSolid::GetExtent().
SetZmax()
void G4VisExtent::SetZmax (G4double zmax) inline
Definition at line 110 of file G4VisExtent.hh.
Referenced by G4VSolid::GetExtent().
SetZmin()
void G4VisExtent::SetZmin (G4double zmin) inline
Definition at line 108 of file G4VisExtent.hh.
Referenced by G4VSolid::GetExtent().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const G4VisExtent & e) friend
Definition at line 85 of file G4VisExtent.cc.
Field Documentation
fCentre
G4Point3D G4VisExtent::fCentre mutable private
Definition at line 86 of file G4VisExtent.hh.
Referenced by GetExtentCentre().
fCentreCached
G4bool G4VisExtent::fCentreCached mutable private
Definition at line 84 of file G4VisExtent.hh.
Referenced by GetExtentCentre(), SetXmax(), SetXmin(), SetYmax(), SetYmin(), SetZmax(), and SetZmin().
fRadius
G4double G4VisExtent::fRadius mutable private
Definition at line 85 of file G4VisExtent.hh.
Referenced by GetExtentRadius().
fRadiusCached
G4bool G4VisExtent::fRadiusCached mutable private
Definition at line 84 of file G4VisExtent.hh.
Referenced by GetExtentRadius(), SetXmax(), SetXmin(), SetYmax(), SetYmin(), SetZmax(), and SetZmin().
fXmax
G4double G4VisExtent::fXmax private
Definition at line 83 of file G4VisExtent.hh.
Referenced by G4VisExtent(), GetExtentCentre(), GetExtentRadius(), GetXmax(), operator!=(), operator<<(), and SetXmax().
fXmin
G4double G4VisExtent::fXmin private
Definition at line 83 of file G4VisExtent.hh.
Referenced by G4VisExtent(), GetExtentCentre(), GetExtentRadius(), GetXmin(), operator!=(), operator<<(), and SetXmin().
fYmax
G4double G4VisExtent::fYmax private
Definition at line 83 of file G4VisExtent.hh.
Referenced by G4VisExtent(), GetExtentCentre(), GetExtentRadius(), GetYmax(), operator!=(), operator<<(), and SetYmax().
fYmin
G4double G4VisExtent::fYmin private
Definition at line 83 of file G4VisExtent.hh.
Referenced by G4VisExtent(), GetExtentCentre(), GetExtentRadius(), GetYmin(), operator!=(), operator<<(), and SetYmin().
fZmax
G4double G4VisExtent::fZmax private
Definition at line 83 of file G4VisExtent.hh.
Referenced by G4VisExtent(), GetExtentCentre(), GetExtentRadius(), GetZmax(), operator!=(), operator<<(), and SetZmax().
fZmin
G4double G4VisExtent::fZmin private
Definition at line 83 of file G4VisExtent.hh.
Referenced by G4VisExtent(), GetExtentCentre(), GetExtentRadius(), GetZmin(), operator!=(), operator<<(), and SetZmin().
The documentation for this class was generated from the following files:
source/graphics_reps/include/G4VisExtent.hh
source/graphics_reps/src/G4VisExtent.cc