Geant4: G4UserLimits Class Reference
G4UserLimits Class Reference
#include <G4UserLimits.hh>
Public Member Functions
G4UserLimits (G4double ustepMax=DBL_MAX, G4double utrakMax=DBL_MAX, G4double utimeMax=DBL_MAX, G4double uekinMin=0., G4double urangMin=0.)
G4UserLimits (const G4String &type, G4double ustepMax=DBL_MAX, G4double utrakMax=DBL_MAX, G4double utimeMax=DBL_MAX, G4double uekinMin=0., G4double urangMin=0.)
virtual ~G4UserLimits ()
virtual G4double GetMaxAllowedStep (const G4Track &)
virtual G4double GetUserMaxTrackLength (const G4Track &)
virtual G4double GetUserMaxTime (const G4Track &)
virtual G4double GetUserMinEkine (const G4Track &)
virtual G4double GetUserMinRange (const G4Track &)
virtual void SetMaxAllowedStep (G4double ustepMax)
virtual void SetUserMaxTrackLength (G4double utrakMax)
virtual void SetUserMaxTime (G4double utimeMax)
virtual void SetUserMinEkine (G4double uekinMin)
virtual void SetUserMinRange (G4double urangMin)
const G4String & GetType () const
void SetType (const G4String &type)
Protected Attributes
G4double fMaxStep
G4double fMaxTrack
G4double fMaxTime
G4double fMinEkine
G4double fMinRange
G4String fType
Detailed Description
Definition at line 56 of file G4UserLimits.hh.
Constructor & Destructor Documentation
G4UserLimits() [1/2]
G4UserLimits::G4UserLimits (G4double ustepMax = DBL_MAX, G4double utrakMax = DBL_MAX, G4double utimeMax = DBL_MAX, G4double uekinMin = 0., G4double urangMin = 0.)
G4UserLimits() [2/2]
G4UserLimits::G4UserLimits (const G4String & type, G4double ustepMax = DBL_MAX, G4double utrakMax = DBL_MAX, G4double utimeMax = DBL_MAX, G4double uekinMin = 0., G4double urangMin = 0.)
~G4UserLimits()
virtual G4UserLimits::~G4UserLimits () virtual
Member Function Documentation
GetMaxAllowedStep()
virtual G4double G4UserLimits::GetMaxAllowedStep (const G4Track &) virtual
Referenced by G4StepLimiter::PostStepGetPhysicalInteractionLength().
GetType()
const G4String& G4UserLimits::GetType () const
Referenced by export_G4UserLimits().
GetUserMaxTime()
virtual G4double G4UserLimits::GetUserMaxTime (const G4Track &) virtual
Referenced by export_G4UserLimits(), G4UserSpecialCuts::PostStepGetPhysicalInteractionLength(), G4MaxTimeCuts::PostStepGetPhysicalInteractionLength(), and DMXMaxTimeCuts::PostStepGetPhysicalInteractionLength().
GetUserMaxTrackLength()
virtual G4double G4UserLimits::GetUserMaxTrackLength (const G4Track &) virtual
Referenced by export_G4UserLimits(), and G4UserSpecialCuts::PostStepGetPhysicalInteractionLength().
GetUserMinEkine()
virtual G4double G4UserLimits::GetUserMinEkine (const G4Track &) virtual
Referenced by export_G4UserLimits(), G4MinEkineCuts::PostStepGetPhysicalInteractionLength(), and DMXMinEkineCuts::PostStepGetPhysicalInteractionLength().
GetUserMinRange()
virtual G4double G4UserLimits::GetUserMinRange (const G4Track &) virtual
Referenced by export_G4UserLimits(), and G4UserSpecialCuts::PostStepGetPhysicalInteractionLength().
SetMaxAllowedStep()
virtual void G4UserLimits::SetMaxAllowedStep (G4double ustepMax) virtual
Referenced by export_G4UserLimits(), F04ElementField::F04ElementField(), G4gstmed(), B2bDetectorConstruction::SetMaxStep(), B2aDetectorConstruction::SetMaxStep(), ExN02DetectorConstruction::SetMaxStep(), F04ElementField::SetMaxStep(), and DetectorConstruction::SetMaxStepSize().
SetType()
void G4UserLimits::SetType (const G4String & type)
Referenced by export_G4UserLimits().
SetUserMaxTime()
virtual void G4UserLimits::SetUserMaxTime (G4double utimeMax) virtual
Referenced by export_G4UserLimits(), F04ElementField::F04ElementField(), DMXDetectorConstruction::SetRoomTimeCut(), and DMXDetectorConstruction::SetTimeCut().
SetUserMaxTrackLength()
virtual void G4UserLimits::SetUserMaxTrackLength (G4double utrakMax) virtual
Referenced by export_G4UserLimits(), and F04ElementField::F04ElementField().
SetUserMinEkine()
virtual void G4UserLimits::SetUserMinEkine (G4double uekinMin) virtual
Referenced by export_G4UserLimits(), F04ElementField::F04ElementField(), DMXDetectorConstruction::SetEnergyCut(), and DMXDetectorConstruction::SetRoomEnergyCut().
SetUserMinRange()
virtual void G4UserLimits::SetUserMinRange (G4double urangMin) virtual
Referenced by export_G4UserLimits().
Field Documentation
fMaxStep
G4double G4UserLimits::fMaxStep protected
Definition at line 101 of file G4UserLimits.hh.
fMaxTime
G4double G4UserLimits::fMaxTime protected
Definition at line 103 of file G4UserLimits.hh.
fMaxTrack
G4double G4UserLimits::fMaxTrack protected
Definition at line 102 of file G4UserLimits.hh.
fMinEkine
G4double G4UserLimits::fMinEkine protected
Definition at line 104 of file G4UserLimits.hh.
fMinRange
G4double G4UserLimits::fMinRange protected
Definition at line 105 of file G4UserLimits.hh.
fType
G4String G4UserLimits::fType protected
Definition at line 107 of file G4UserLimits.hh.
The documentation for this class was generated from the following file:
source/global/management/include/G4UserLimits.hh