Geant4: G4HadProjectile Class Reference
G4HadProjectile Class Reference
#include <G4HadProjectile.hh>
Public Member Functions
G4HadProjectile ()
G4HadProjectile (const G4Track &aT)
G4HadProjectile (const G4DynamicParticle &aT)
~G4HadProjectile ()
void Initialise (const G4Track &aT)
const G4Material * GetMaterial () const
const G4ParticleDefinition * GetDefinition () const
const G4LorentzVector & Get4Momentum () const
G4LorentzRotation & GetTrafoToLab ()
G4double GetKineticEnergy () const
G4double GetTotalEnergy () const
G4double GetTotalMomentum () const
G4double GetGlobalTime () const
G4double GetBoundEnergy () const
void SetGlobalTime (G4double t)
void SetBoundEnergy (G4double e)
Private Member Functions
G4HadProjectile & operator= (const G4HadProjectile &right)
G4HadProjectile (const G4HadProjectile &)
Private Attributes
const G4Material * theMat
G4LorentzVector theOrgMom
G4LorentzVector theMom
const G4ParticleDefinition * theDef
G4LorentzRotation toLabFrame
G4double theTime
G4double theBoundEnergy
Detailed Description
Definition at line 39 of file G4HadProjectile.hh.
Constructor & Destructor Documentation
G4HadProjectile() [1/4]
G4HadProjectile::G4HadProjectile ()
Definition at line 30 of file G4HadProjectile.cc.
G4HadProjectile() [2/4]
G4HadProjectile::G4HadProjectile (const G4Track & aT)
Definition at line 38 of file G4HadProjectile.cc.
G4HadProjectile() [3/4]
G4HadProjectile::G4HadProjectile (const G4DynamicParticle & aT)
Definition at line 43 of file G4HadProjectile.cc.
~G4HadProjectile()
G4HadProjectile::~G4HadProjectile ()
Definition at line 57 of file G4HadProjectile.cc.
G4HadProjectile() [4/4]
G4HadProjectile::G4HadProjectile (const G4HadProjectile &) private
Member Function Documentation
Get4Momentum()
const G4LorentzVector & G4HadProjectile::Get4Momentum () const inline
Definition at line 86 of file G4HadProjectile.hh.
Referenced by G4BinaryLightIonReaction::ApplyYourself(), G4RPGPiMinusInelastic::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4ParticleHPFissionFS::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4ElectroVDNuclearModel::ApplyYourself(), G4MuonVDNuclearModel::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4ParaFissionModel::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4NeutrinoElectronNcModel::ApplyYourself(), G4NeutrinoElectronCcModel::ApplyYourself(), G4ParticleHPChannelList::ApplyYourself(), G4LENDModel::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4LEpp::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4NeutronElectronElModel::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4QMDReaction::ApplyYourself(), CexmcChargeExchangeProductionModel< OutputParticle >::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4LEnp::ApplyYourself(), G4PreCompoundModel::ApplyYourself(), G4LFission::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4ParticleHPThermalScattering::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4BinaryCascade::BuildLateParticleCollisions(), G4MuonVDNuclearModel::CalculateEMVertex(), G4ElectroVDNuclearModel::CalculateEMVertex(), G4RPGInelastic::CalculateMomenta(), G4RPGAntiKZeroInelastic::Cascade(), G4HadronicProcess::CheckResult(), G4ParticleHPInelasticCompFS::CompositeApply(), G4CascadeInterface::createBullet(), G4BinaryCascade::DebugFinalEpConservation(), G4ParticleHPThermalBoost::GetThermalEnergy(), GetTotalEnergy(), GetTotalMomentum(), G4GeneratorPrecompoundInterface::Propagate(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4LENDModel::returnUnchanged(), G4NuclNuclDiffuseElastic::SampleThetaLab(), G4DiffuseElastic::SampleThetaLab(), and G4RPGNeutronInelastic::SlowNeutron().
GetBoundEnergy()
G4double G4HadProjectile::GetBoundEnergy () const inline
Definition at line 118 of file G4HadProjectile.hh.
Referenced by G4MuMinusCapturePrecompound::ApplyYourself(), and G4MuonMinusBoundDecay::ApplyYourself().
GetDefinition()
const G4ParticleDefinition * G4HadProjectile::GetDefinition () const inline
Definition at line 81 of file G4HadProjectile.hh.
Referenced by G4INCLXXInterface::AccurateProjectile(), G4BinaryLightIonReaction::ApplyYourself(), G4RPGPiMinusInelastic::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGNeutronInelastic::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4ParticleHPFissionFS::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4LENDorBERTModel::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4ElectroVDNuclearModel::ApplyYourself(), G4ParaFissionModel::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4LENDModel::ApplyYourself(), G4NeutrinoElectronCcModel::ApplyYourself(), G4NeutrinoElectronNcModel::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4LEpp::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4NeutronElectronElModel::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4QMDReaction::ApplyYourself(), CexmcChargeExchangeProductionModel< OutputParticle >::ApplyYourself(), G4LEnp::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4LFission::ApplyYourself(), G4PreCompoundModel::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4ParticleHPThermalScattering::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4CascadeInterface::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4BinaryCascade::BuildLateParticleCollisions(), G4ElectroVDNuclearModel::CalculateEMVertex(), G4RPGInelastic::CalculateMomenta(), G4RPGKMinusInelastic::Cascade(), G4RPGAntiProtonInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGXiMinusInelastic::Cascade(), G4RPGSigmaPlusInelastic::Cascade(), G4RPGAntiLambdaInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4RPGAntiOmegaMinusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGOmegaMinusInelastic::Cascade(), G4RPGKZeroInelastic::Cascade(), G4RPGKPlusInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGSigmaMinusInelastic::Cascade(), G4RPGLambdaInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), G4RPGAntiKZeroInelastic::Cascade(), G4HadronicProcess::CheckResult(), G4ParticleHPInelasticCompFS::CompositeApply(), G4CascadeInterface::createBullet(), G4FissionFragmentGenerator::G4GenerateFission(), G4EnergyRangeManager::GetHadronicInteraction(), GetKineticEnergy(), G4ParticleHPThermalBoost::GetThermalEnergy(), G4NeutrinoElectronNcModel::IsApplicable(), G4NeutrinoElectronCcModel::IsApplicable(), G4NeutronElectronElModel::IsApplicable(), G4DiffuseElasticV2::IsApplicable(), G4DiffuseElastic::IsApplicable(), G4hhElastic::IsApplicable(), G4LMsdGenerator::IsApplicable(), G4CascadeInterface::IsApplicable(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4NeutrinoElectronCcModel::SampleCosCMS(), G4NeutrinoElectronNcModel::SampleElectronTkin(), G4LMsdGenerator::SampleMx(), G4NuclNuclDiffuseElastic::SampleThetaLab(), G4DiffuseElastic::SampleThetaLab(), and G4INCLXXInterface::toINCLParticleSpecies().
GetGlobalTime()
G4double G4HadProjectile::GetGlobalTime () const inline
Definition at line 113 of file G4HadProjectile.hh.
Referenced by G4BinaryLightIonReaction::ApplyYourself(), G4ParticleHPFissionFS::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4LENDFission::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4PreCompoundModel::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4EmCaptureCascade::ApplyYourself(), G4MuonMinusBoundDecay::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4HadronStoppingProcess::AtRestDoIt(), and G4FissionLibrary::SampleMult().
GetKineticEnergy()
G4double G4HadProjectile::GetKineticEnergy () const inline
Definition at line 106 of file G4HadProjectile.hh.
Referenced by G4BinaryLightIonReaction::ApplyYourself(), G4RPGPiMinusInelastic::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGNeutronInelastic::ApplyYourself(), G4ParticleHPFissionFS::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4LENDorBERTModel::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4ElectroVDNuclearModel::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4MuonVDNuclearModel::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4LENDCombinedModel::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4NeutrinoElectronNcModel::ApplyYourself(), G4ParticleHPChannelList::ApplyYourself(), G4LENDModel::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4LEpp::ApplyYourself(), G4LENDFission::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4NeutronElectronElModel::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4QMDReaction::ApplyYourself(), CexmcChargeExchangeProductionModel< OutputParticle >::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4LEnp::ApplyYourself(), G4LFission::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4ParticleHPThermalScattering::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4CascadeInterface::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4MuonVDNuclearModel::CalculateEMVertex(), G4RPGInelastic::CalculateMomenta(), G4HadronicProcess::CheckResult(), G4ParticleHPInelasticCompFS::CompositeApply(), G4EnergyRangeManager::GetHadronicInteraction(), G4ParticleHPThermalBoost::GetThermalEnergy(), G4LMsdGenerator::IsApplicable(), G4CascadeInterface::NoInteraction(), G4LENDModel::returnUnchanged(), G4RPGReaction::Rotate(), G4LMsdGenerator::SampleT(), and G4INCLXXInterface::toINCLKineticEnergy().
GetMaterial()
const G4Material * G4HadProjectile::GetMaterial () const inline
Definition at line 76 of file G4HadProjectile.hh.
Referenced by G4RPGKMinusInelastic::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4ParticleHPFissionFS::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4LENDorBERTModel::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4ParticleHPElastic::ApplyYourself(), G4ParticleHPCapture::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4LENDCombinedModel::ApplyYourself(), G4LENDModel::ApplyYourself(), G4ParticleHPFission::ApplyYourself(), G4ParticleHPChannelList::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4LENDFission::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4ParticleHPThermalScattering::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4FissLib::ApplyYourself(), G4ParticleHPChannel::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), and G4ParticleHPInelasticCompFS::CompositeApply().
GetTotalEnergy()
G4double G4HadProjectile::GetTotalEnergy (void) const inline
Definition at line 96 of file G4HadProjectile.hh.
Referenced by G4MuonVDNuclearModel::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4NeutrinoElectronCcModel::ApplyYourself(), G4LEpp::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4LEnp::ApplyYourself(), G4LFission::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4MuonVDNuclearModel::CalculateEMVertex(), G4RPGKMinusInelastic::Cascade(), G4RPGXiMinusInelastic::Cascade(), G4RPGAntiLambdaInelastic::Cascade(), G4RPGAntiProtonInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGSigmaPlusInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4RPGAntiOmegaMinusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGOmegaMinusInelastic::Cascade(), G4RPGLambdaInelastic::Cascade(), G4RPGKPlusInelastic::Cascade(), G4RPGKZeroInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGSigmaMinusInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), G4HadronicProcess::CheckResult(), GetKineticEnergy(), G4NeutrinoElectronCcModel::IsApplicable(), G4NeutrinoElectronNcModel::IsApplicable(), G4NeutronElectronElModel::IsApplicable(), G4NeutrinoElectronCcModel::SampleCosCMS(), and G4NeutrinoElectronNcModel::SampleElectronTkin().
GetTotalMomentum()
G4double G4HadProjectile::GetTotalMomentum () const inline
Definition at line 101 of file G4HadProjectile.hh.
Referenced by G4LightMedia::AntiLambdaExchange(), G4LightMedia::AntiNeutronExchange(), G4LightMedia::AntiOmegaMinusExchange(), G4LightMedia::AntiProtonExchange(), G4LightMedia::AntiSigmaMinusExchange(), G4LightMedia::AntiSigmaPlusExchange(), G4LightMedia::AntiXiMinusExchange(), G4LightMedia::AntiXiZeroExchange(), G4RPGAntiProtonInelastic::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4LEpp::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4LEnp::ApplyYourself(), G4LFission::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4RPGKMinusInelastic::Cascade(), G4RPGAntiLambdaInelastic::Cascade(), G4RPGAntiProtonInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4LightMedia::KaonPlusExchange(), G4LightMedia::KaonZeroShortExchange(), G4LightMedia::LambdaExchange(), G4LightMedia::NeutronExchange(), G4LightMedia::OmegaMinusExchange(), G4LightMedia::PionPlusExchange(), G4LightMedia::ProtonExchange(), G4NuclNuclDiffuseElastic::SampleThetaLab(), G4DiffuseElastic::SampleThetaLab(), G4LightMedia::SigmaMinusExchange(), G4LightMedia::SigmaPlusExchange(), G4LightMedia::XiMinusExchange(), and G4LightMedia::XiZeroExchange().
GetTrafoToLab()
G4LorentzRotation & G4HadProjectile::GetTrafoToLab () inline
Definition at line 91 of file G4HadProjectile.hh.
Referenced by G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), and G4HadronicProcess::PostStepDoIt().
Initialise()
void G4HadProjectile::Initialise (const G4Track & aT)
Definition at line 60 of file G4HadProjectile.cc.
Referenced by G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4HadProjectile(), G4NeutrinoElectronProcess::PostStepDoIt(), and G4HadronicProcess::PostStepDoIt().
operator=()
G4HadProjectile& G4HadProjectile::operator= (const G4HadProjectile & right) private
SetBoundEnergy()
void G4HadProjectile::SetBoundEnergy (G4double e) inline
Definition at line 128 of file G4HadProjectile.hh.
Referenced by G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), and G4MuonicAtomDecay::DecayIt().
SetGlobalTime()
void G4HadProjectile::SetGlobalTime (G4double t) inline
Definition at line 123 of file G4HadProjectile.hh.
Referenced by G4MuonMinusBoundDecay::ApplyYourself(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), and G4MuonicAtomDecay::DecayIt().
Field Documentation
theBoundEnergy
G4double G4HadProjectile::theBoundEnergy private
Definition at line 73 of file G4HadProjectile.hh.
Referenced by G4HadProjectile(), GetBoundEnergy(), Initialise(), and SetBoundEnergy().
theDef
const G4ParticleDefinition* G4HadProjectile::theDef private
Definition at line 70 of file G4HadProjectile.hh.
Referenced by G4HadProjectile(), GetDefinition(), and Initialise().
theMat
const G4Material* G4HadProjectile::theMat private
Definition at line 67 of file G4HadProjectile.hh.
Referenced by G4HadProjectile(), GetMaterial(), and Initialise().
theMom
G4LorentzVector G4HadProjectile::theMom private
Definition at line 69 of file G4HadProjectile.hh.
Referenced by G4HadProjectile(), Get4Momentum(), and Initialise().
theOrgMom
G4LorentzVector G4HadProjectile::theOrgMom private
Definition at line 68 of file G4HadProjectile.hh.
Referenced by G4HadProjectile(), and Initialise().
theTime
G4double G4HadProjectile::theTime private
Definition at line 72 of file G4HadProjectile.hh.
Referenced by G4HadProjectile(), GetGlobalTime(), Initialise(), and SetGlobalTime().
toLabFrame
G4LorentzRotation G4HadProjectile::toLabFrame private
Definition at line 71 of file G4HadProjectile.hh.
Referenced by G4HadProjectile(), GetTrafoToLab(), and Initialise().
The documentation for this class was generated from the following files:
source/processes/hadronic/util/include/G4HadProjectile.hh
source/processes/hadronic/util/src/G4HadProjectile.cc