Geant4: G4INCL::KinematicsUtils Namespace Reference
G4INCL::KinematicsUtils Namespace Reference
Functions
void transformToLocalEnergyFrame (Nucleus const *const n, Particle *const p)
G4double getLocalEnergy (Nucleus const *const n, Particle *const p)
ThreeVector makeBoostVector (Particle const *const p1, Particle const *const p2)
G4double totalEnergyInCM (Particle const *const p1, Particle const *const p2)
G4double squareTotalEnergyInCM (Particle const *const p1, Particle const *const p2)
G4double momentumInCM (Particle const *const p1, Particle const *const p2)
gives the momentum in the CM frame of two particles.
G4double momentumInCM (const G4double E, const G4double M1, const G4double M2)
G4double momentumInLab (Particle const *const p1, Particle const *const p2)
gives the momentum in the lab frame of two particles.
G4double momentumInLab (const G4double s, const G4double m1, const G4double m2)
G4double sumTotalEnergies (const ParticleList &)
ThreeVector sumMomenta (const ParticleList &)
G4double energy (const ThreeVector &p, const G4double m)
G4double invariantMass (const G4double E, const ThreeVector &p)
G4double squareInvariantMass (const G4double E, const ThreeVector &p)
G4double gammaFromKineticEnergy (const ParticleSpecies &p, const G4double EKin)
Function Documentation
energy()
G4double G4INCL::KinematicsUtils::energy (const ThreeVector & p, const G4double m)
Definition at line 158 of file G4INCLKinematicsUtils.cc.
Referenced by G4PenelopeCrossSection::AddCrossSectionPoint(), G4WaterStopping::AddData(), G4PenelopeCrossSection::AddShellCrossSectionPoint(), XrayFluoAnalysisManager::analysePrimaryGenerator(), G4ForwardXrayTR::AngleDensity(), G4ForwardXrayTR::AngleInterval(), G4VXTRenergyLoss::AngleSpectralXTRdEdx(), G4NeutrinoElectronCcModel::ApplyYourself(), G4RDAugerTransition::AugerTransitionEnergy(), G4AugerTransition::AugerTransitionEnergy(), G4RDeIonisationSpectrum::AverageEnergy(), G4eIonisationSpectrum::AverageEnergy(), G4RDShellVacancy::AverageNOfIonisations(), G4ShellVacancy::AverageNOfIonisations(), RunAction::BeginOfRunAction(), G4DecayProducts::Boost(), G4VXTRenergyLoss::BuildAngleTable(), G4PolarizedCompton::BuildAsymmetryTable(), G4KokoulinMuonNuclearXS::BuildCrossSectionTable(), G4PenelopeIonisationXSHandler::BuildDeltaTable(), G4LowEnergyIonisation::BuildLossTable(), G4RDVCrossSectionHandler::BuildMeanFreePathForMaterials(), G4VCrossSectionHandler::BuildMeanFreePathForMaterials(), G4LossTableBuilder::BuildRangeTable(), G4RDVeLowEnergyLoss::BuildRangeVector(), G4hRDEnergyLoss::BuildRangeVector(), G4IonParametrisedLossModel::BuildRangeVector(), G4PenelopeIonisationXSHandler::BuildXSTable(), G4PenelopeBremsstrahlungModel::BuildXSTable(), G4GDecay3::CalculateMomentumMagnitudes(), G4OpRayleigh::CalculateRayleighMeanFreePaths(), G4BinaryCascade::Capture(), G4Fancy3DNucleus::ChooseFermiMomenta(), G4IonChuFluctuationModel::ChuFluctuationModel(), StackingAction::ClassifyNewTrack(), G4eplusPolarizedAnnihilation::ComputeAsymmetry(), G4ePolarizedIonisation::ComputeAsymmetry(), G4PolarizedCompton::ComputeAsymmetry(), G4LivermorePolarizedPhotoElectricModel::ComputeCrossSectionPerAtom(), G4LivermorePhotoElectricModel::ComputeCrossSectionPerAtom(), G4PenelopeAnnihilationModel::ComputeCrossSectionPerAtom(), G4PenelopeGammaConversionModel::ComputeCrossSectionPerAtom(), G4PenelopeRayleighModel::ComputeCrossSectionPerAtom(), G4PEEffectFluoModel::ComputeCrossSectionPerAtom(), G4LivermoreIonisationModel::ComputeCrossSectionPerAtom(), G4PenelopePhotoElectricModel::ComputeCrossSectionPerAtom(), G4IonParametrisedLossModel::ComputeCrossSectionPerAtom(), G4ICRU73QOModel::ComputeCrossSectionPerElectron(), G4eeToHadronsModel::ComputeCrossSectionPerElectron(), G4BraggIonModel::ComputeCrossSectionPerElectron(), G4BraggModel::ComputeCrossSectionPerElectron(), G4PenelopeAnnihilationModel::ComputeCrossSectionPerElectron(), G4eeToHadronsMultiModel::ComputeCrossSectionPerElectron(), G4IonParametrisedLossModel::ComputeLossForStep(), G4ePolarizedIonisation::ComputeSaturationFactor(), G4PenelopeIonisationXSHandler::ComputeShellCrossSectionsElectron(), G4PenelopeIonisationXSHandler::ComputeShellCrossSectionsPositron(), UltraDetectorConstruction::ConstructTableMaterials(), G4IonParametrisedLossModel::CorrectionsAlongStep(), G4ParticleHPThermalScattering::create_E_isoAng_from_energy(), G4VPhononProcess::CreateSecondary(), G4PhysChemIO::FormattedText::CreateWaterMolecule(), G4PhysChemIO::G4Analysis::CreateWaterMolecule(), G4DNAChemistryManager::CreateWaterMolecule(), G4LivermorePhotoElectricModel::CrossSectionPerVolume(), G4LivermorePolarizedPhotoElectricModel::CrossSectionPerVolume(), G4PenelopeComptonModel::CrossSectionPerVolume(), G4PEEffectFluoModel::CrossSectionPerVolume(), G4PenelopeBremsstrahlungModel::CrossSectionPerVolume(), G4PenelopeIonisationModel::CrossSectionPerVolume(), G4XDeltaNstarTable::CrossSectionTable(), G4XDeltaDeltaTable::CrossSectionTable(), G4XNNstarTable::CrossSectionTable(), G4XDeltaDeltastarTable::CrossSectionTable(), G4XNDeltaTable::CrossSectionTable(), G4XNDeltastarTable::CrossSectionTable(), G4VEmProcess::CurrentSetup(), G4MuonDecayChannelWithSpin::DecayIt(), G4ScreenedNuclearRecoil::DepositEnergy(), Run::DetailedLeakage(), G4AdjointeIonisationModel::DiffCrossSectionMoller(), G4PenelopeComptonModel::DifferentialCrossSection(), GammaRayTelDigitizer::Digitize(), Run::EndOfRun(), RunAction::EnergyBalance(), RunAction::EnergySpectrumOfSecondaries(), RunAction::EnergyTransfered(), RunAction::EnergyTransferedByProcess(), G4RDRangeTest::Escape(), G4IonFluctuations::Factor(), AnalysisManager::FillSecondaries(), XrayFluoDataSet::FindBinLocation(), G4CompositeDataSet::FindValue(), G4RDShellEMDataSet::FindValue(), G4ShellEMDataSet::FindValue(), G4PixeShellDataSet::FindValue(), G4DataSet::FindValue(), G4RDEMDataSet::FindValue(), G4EMDataSet::FindValue(), G4RDVCrossSectionHandler::FindValue(), G4PixeCrossSectionHandler::FindValue(), G4VCrossSectionHandler::FindValue(), G4RDAtomicShell::G4RDAtomicShell(), G4RPGReaction::GenerateNBodyEvent(), G4RPGReaction::GenerateNBodyEventT(), BrachyPrimaryGeneratorAction::GeneratePrimaries(), PrimaryGeneratorAction2::GeneratePrimaries(), UltraPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPrimaryGeneratorAction::GeneratePrimaries(), G4BlinePrimaryGeneratorAction::GeneratePrimaries(), DMXParticleSource::GeneratePrimaryVertex(), DNA::Penetration::Terrisol1990::Get3DStdDeviation(), G4ParticleHPFFFissionFS::GetAFissionFragment(), G4VXTRenergyLoss::GetAngleVector(), G4MuNeutrinoNucleusTotXsc::GetANuMuTotCsXsc(), RE01TrackerHit::GetAttDefs(), RE01CalorimeterHit::GetAttDefs(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4BremsstrahlungCrossSectionHandler::GetCrossSectionAboveThresholdForElement(), G4eIonisationCrossSectionHandler::GetCrossSectionAboveThresholdForElement(), G4HadronicProcessStore::GetCrossSectionPerAtom(), G4HadronicProcessStore::GetCrossSectionPerVolume(), G4PenelopeIonisationXSHandler::GetDensityCorrection(), G4WaterStopping::GetElectronicDEDX(), G4ESTARStopping::GetElectronicDEDX(), G4ASTARStopping::GetElectronicDEDX(), G4PSTARStopping::GetElectronicDEDX(), G4PAIxSection::GetElectronRange(), G4NeutrinoElectronNcXsc::GetElementCrossSection(), G4NeutrinoElectronCcXsc::GetElementCrossSection(), XrayFluoAnalysisManager::GetEmittedParticleEnergyAndType(), G4MuNeutrinoNucleusTotXsc::GetEnergyIndex(), G4VEvaporationChannel::GetFinalLevelEnergy(), G4PhotonEvaporation::GetFinalLevelEnergy(), G4ParticleHPChannel::GetFSCrossSection(), GIDI_settings_group::getGroupIndexFromEnergy(), G4PenelopeCrossSection::GetHardCrossSection(), XrayFluoHPGeDetectorType::GetInfData(), G4MuNeutrinoNucleusTotXsc::GetIsoCrossSection(), G4NuclearLevelData::GetLevelEnergy(), G4NuclearLevelData::GetLowEdgeLevelEnergy(), G4LowEnergyRayleigh::GetMeanFreePath(), G4LowEnergyCompton::GetMeanFreePath(), G4LowEnergyGammaConversion::GetMeanFreePath(), G4LowEnergyPolarizedCompton::GetMeanFreePath(), G4LowEnergyPhotoElectric::GetMeanFreePath(), G4ScreenedNuclearRecoil::GetMeanFreePath(), G4VEvaporationChannel::GetNearestLevelEnergy(), G4RPGInelastic::GetNormalizationConstant(), G4PenelopeCrossSection::GetNormalizedShellCrossSection(), G4MuNeutrinoNucleusTotXsc::GetNuMuTotCsXsc(), DNA::Penetration::Terrisol1990::GetPenetration(), G4PenelopeBremsstrahlungModel::GetPositronXSCorrection(), G4ParticleHPFissionERelease::GetPromptNeutronKinetic(), DNA::Penetration::Terrisol1990::GetRmean(), G4SandiaTable::GetSandiaCofForMaterial(), G4SandiaTable::GetSandiaCofPerAtom(), G4SandiaTable::GetSandiaCofWater(), G4PenelopeCrossSection::GetShellCrossSection(), G4PenelopePhotoElectricModel::GetShellCrossSection(), G4PenelopeCrossSection::GetSoftStoppingPower(), G4XTRRegularRadModel::GetStackFactor(), G4RegularXTRadiator::GetStackFactor(), G4XTRTransparentRegRadModel::GetStackFactor(), G4TransparentRegXTRadiator::GetStackFactor(), XTRTransparentRegRadModel::GetStackFactor(), G4GammaXTRadiator::GetStackFactor(), G4StrawTubeXTRadiator::GetStackFactor(), G4XTRGammaRadModel::GetStackFactor(), G4VXTRenergyLoss::GetStackFactor(), XrayFluoHPGeDetectorType::GetSupData(), G4AtomicShells_XDB_EADL::GetTotalBindingEnergy(), G4AtomicShells::GetTotalBindingEnergy(), G4PenelopeCrossSection::GetTotalCrossSection(), G4ParticleHPFissionERelease::GetTotalEnergy(), G4VarNtp::getTotalEnergy(), G4ParticleHPChannel::GetWeightedXsec(), G4ParticleHPIsoData::GetXsec(), G4ParticleHPChannel::GetXsec(), GunPrimaryGeneratorAction::GunPrimaryGeneratorAction(), G4ParticleHPDiscreteTwoBody::Init(), G4ParticleHPElasticFS::Init(), G4ParticleHPAngular::Init(), G4DNABornExcitationModel2::Initialise(), G4PhysicsOrderedFreeVector::InsertValues(), G4TransitionRadiation::IntegralOverAngle(), G4NeutrinoElectronCcModel::IsApplicable(), G4NeutrinoElectronNcModel::IsApplicable(), G4NeutronElectronElModel::IsApplicable(), G4DecayProducts::IsChecked(), G4NeutrinoElectronNcXsc::IsElementApplicable(), G4NeutrinoElectronCcXsc::IsElementApplicable(), G4PenelopeComptonModel::KleinNishinaCrossSection(), G4eIonisationParameters::LoadData(), G4RDeIonisationParameters::LoadData(), XrayFluoAnalysisManager::LoadGunData(), G4ParticleHPMadlandNixSpectrum::Madland(), G4BaryonWidth::MassDependentWidth(), G4BaryonPartialWidth::MassDependentWidth(), MCGIDI_energy_free(), MCGIDI_energy_initialize(), MCGIDI_energy_new(), MCGIDI_energy_parseEvaporationFromTOM(), MCGIDI_energy_parseFromTOM(), MCGIDI_energy_parseGeneralEvaporationFromTOM(), MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_energy_parseNBodyPhaseSpaceFromTOM(), MCGIDI_energy_parseSimpleMaxwellianFissionFromTOM(), MCGIDI_energy_parseWattFromTOM(), MCGIDI_energy_parseWeightedFunctionalsFromTOM(), MCGIDI_energy_parseWeightFromTOM(), MCGIDI_energy_release(), MCGIDI_energy_sampleEnergy(), MCGIDI_energy_sampleWeightedFunctional(), G4PixeCrossSectionHandler::MicroscopicCrossSection(), G4hImpactIonisation::MicroscopicCrossSection(), G4LevelManager::NearestLevel(), G4LevelManager::NearestLevelEnergy(), G4LevelManager::NearestLevelIndex(), G4LevelManager::NearestLowEdgeLevelEnergy(), G4LevelManager::NearestLowEdgeLevelIndex(), G4hICRU49Nuclear::NuclearStoppingPower(), G4hZiegler1985Nuclear::NuclearStoppingPower(), G4ICRU49NuclearStoppingModel::NuclearStoppingPower(), G4VXTRenergyLoss::OneBoundaryXTRNdensity(), G4VXTRenergyLoss::OneInterfaceXTRdEdx(), G4PenelopeComptonModel::OscillatorTotalCrossSection(), G4RDBremsstrahlungParameters::Parameter(), G4BremsstrahlungParameters::Parameter(), G4INCL::Particle::Particle(), G4LindhardRobinsonPartition::PartitionNIEL(), G4KL3DecayChannel::PhaseSpace(), G4GammaGeneralProcess::PostStepGetPhysicalInteractionLength(), G4IonDEDXHandler::PrintDEDXTable(), G4IonParametrisedLossModel::PrintDEDXTable(), G4eIonisationSpectrum::Probability(), G4RDeIonisationSpectrum::Probability(), G4INCL::ProjectileRemnant::ProjectileRemnant(), G4INCL::Cluster::putParticlesOffShell(), XrayFluoEventAction::RandomCut(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4ParticleHPThermalScattering::readAnE_isoAng(), G4ParticleHPThermalScattering::readAnE_P_E_isoAng(), G4PenelopePhotoElectricModel::ReadDataFile(), XrayFluoHPGeDetectorType::ResponseFunction(), XrayFluoSiLiDetectorType::ResponseFunction(), G4ParticleHPNBodyPhaseSpace::Sample(), G4ParticleHPLegendreStore::Sample(), G4NeutrinoElectronCcModel::SampleCosCMS(), G4SauterGavrilaAngularDistribution::SampleDirection(), G4Generator2BS::SampleDirection(), G4PenelopePhotoElectricModel::SampleElectronDirection(), G4NeutrinoElectronNcModel::SampleElectronTkin(), G4RDeIonisationSpectrum::SampleEnergy(), G4eIonisationSpectrum::SampleEnergy(), G4PenelopeBremsstrahlungFS::SampleGammaEnergy(), G4AntiNuclElastic::SampleInvariantT(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4PEEffectFluoModel::SampleSecondaries(), G4eeToHadronsMultiModel::SampleSecondaries(), G4MollerBhabhaModel::SampleSecondaries(), G4ICRU73QOModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4IonParametrisedLossModel::SampleSecondaries(), G4GammaTransition::SampleTransition(), G4INCL::InteractionAvatar::ViolationEMomentumFunctor::scaleParticleMomenta(), G4PenelopePhotoElectricModel::SelectRandomShell(), G4ContinuousGainOfEnergy::SetDynamicMassCharge(), G4ParticleHPLegendreStore::SetEnergy(), G4ParticleHPAngularP::SetEnergy(), G4ParticleHPLegendreTable::SetEnergy(), G4VXTRenergyLoss::SetEnergy(), G4INCL::Particle::setEnergy(), PrimaryKiller::SetEnergyThreshold(), G4INCL::Particle::setFrozenEnergy(), G4hImpactIonisation::SetHighEnergyForAntiProtonParametrisation(), G4hImpactIonisation::SetHighEnergyForProtonParametrisation(), G4hImpactIonisation::SetLowEnergyForAntiProtonParametrisation(), G4hImpactIonisation::SetLowEnergyForProtonParametrisation(), G4ScreenedNuclearRecoil::SetMaxEnergyForScattering(), PrimaryKiller::SetMaxLossEnergyLimit(), PrimaryKiller::SetMinLossEnergyLimit(), G4ScreenedNuclearRecoil::SetPhysicsCutoff(), G4hImpactIonisation::SetPixeProjectileMaxEnergy(), G4hImpactIonisation::SetPixeProjectileMinEnergy(), Run::SetPrimary(), AnalysisManager::SetPrimaryEnergy(), G4ParticleChangeForGamma::SetProposedKineticEnergy(), G4ParticleChangeForLoss::SetProposedKineticEnergy(), G4ScreenedNuclearRecoil::SetRecoilCutoff(), G4AtimaEnergyLossModel::sezi_p_se(), G4INCL::StandardPropagationModel::shootParticle(), G4ForwardXrayTR::SpectralAngleTRdensity(), G4ForwardXrayTR::SpectralDensity(), G4XTRRegularRadModel::SpectralXTRdEdx(), G4RegularXTRadiator::SpectralXTRdEdx(), G4XTRTransparentRegRadModel::SpectralXTRdEdx(), G4TransparentRegXTRadiator::SpectralXTRdEdx(), XTRTransparentRegRadModel::SpectralXTRdEdx(), G4VXTRenergyLoss::SpectralXTRdEdx(), G4RDAugerData::StartShellEnergy(), G4AugerData::StartShellEnergy(), EventAction::SumEnergyTransfered(), Run::SumeTransf(), G4IonYangFluctuationModel::TheValue(), G4IonChuFluctuationModel::TheValue(), G4hBetheBlochModel::TheValue(), G4hNuclearStoppingModel::TheValue(), G4hIonEffChargeSquare::TheValue(), G4QAOLowEnergyLoss::TheValue(), G4PhaseSpaceDecayChannel::ThreeBodyDecayIt(), G4GeneralPhaseSpaceDecay::ThreeBodyDecayIt(), G4AblaInterface::toG4Particle(), G4INCLXXInterface::toG4Particle(), G4GammaGeneralProcess::TotalCrossSectionPerVolume(), RunAction::TotalEnergyDeposit(), RunAction::TotalEnergyLost(), XrayTelAnalysis::Update(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), BrachySteppingAction::UserSteppingAction(), G4RDVCrossSectionHandler::ValueForMaterial(), G4PixeCrossSectionHandler::ValueForMaterial(), G4VCrossSectionHandler::ValueForMaterial(), G4ParticleHPWattSpectrum::Watt(), G4VXTRenergyLoss::XTRNAngleSpectralDensity(), G4VXTRenergyLoss::XTRNSpectralDensity(), and G4IonYangFluctuationModel::YangFluctuationModel().
gammaFromKineticEnergy()
G4double G4INCL::KinematicsUtils::gammaFromKineticEnergy (const ParticleSpecies & p, const G4double EKin)
Definition at line 170 of file G4INCLKinematicsUtils.cc.
getLocalEnergy()
G4double G4INCL::KinematicsUtils::getLocalEnergy (Nucleus const *const n, Particle *const p)
Definition at line 53 of file G4INCLKinematicsUtils.cc.
Referenced by G4INCL::InteractionAvatar::ViolationEMomentumFunctor::scaleParticleMomenta(), G4INCL::InteractionAvatar::ViolationEEnergyFunctor::setParticleEnergy(), and transformToLocalEnergyFrame().
invariantMass()
G4double G4INCL::KinematicsUtils::invariantMass (const G4double E, const ThreeVector & p)
Definition at line 162 of file G4INCLKinematicsUtils.cc.
Referenced by G4INCL::ClusteringModelIntercomparison::findClusterStartingFrom().
makeBoostVector()
ThreeVector G4INCL::KinematicsUtils::makeBoostVector (Particle const *const p1, Particle const *const p2)
Definition at line 89 of file G4INCLKinematicsUtils.cc.
Referenced by G4INCL::InteractionAvatar::preInteraction(), and squareTotalEnergyInCM().
momentumInCM() [1/2]
G4double G4INCL::KinematicsUtils::momentumInCM (const G4double E, const G4double M1, const G4double M2)
Definition at line 119 of file G4INCLKinematicsUtils.cc.
momentumInCM() [2/2]
G4double G4INCL::KinematicsUtils::momentumInCM (Particle const *const p1, Particle const *const p2)
gives the momentum in the CM frame of two particles.
The formula is the following:
where is the scalar product of the momentum four-vectors:
Parameters
p1 pointer to particle 1
p2 pointer to particle 2
Returns
the absolute value of the momentum of any of the two particles in the CM frame, in MeV/c.
Definition at line 107 of file G4INCLKinematicsUtils.cc.
Referenced by G4INCL::DeltaDecayChannel::computeDecayTime(), G4INCL::PhaseSpaceRauboldLynch::computeMaximumWeightNaive(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::PhaseSpaceRauboldLynch::computeWeight(), G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), G4INCL::CrossSectionsMultiPionsAndResonances::etaNToPiN(), G4INCL::NKbToNKbChannel::fillFinalState(), G4INCL::NKbToSpiChannel::fillFinalState(), G4INCL::NYElasticChannel::fillFinalState(), G4INCL::NKElasticChannel::fillFinalState(), G4INCL::NKToNKChannel::fillFinalState(), G4INCL::NpiToLKChannel::fillFinalState(), G4INCL::NpiToSKChannel::fillFinalState(), G4INCL::NKbToLpiChannel::fillFinalState(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::StrangeAbsorbtionChannel::fillFinalState(), G4INCL::DeltaDecayChannel::fillFinalState(), G4INCL::SigmaZeroDecayChannel::fillFinalState(), G4INCL::PionResonanceDecayChannel::fillFinalState(), G4INCL::RecombinationChannel::fillFinalState(), G4INCL::PhaseSpaceKopylov::generate(), G4INCL::NKbElasticChannel::KaonMomentum(), and G4INCL::CrossSectionsMultiPionsAndResonances::omegaNToPiN().
momentumInLab() [1/2]
G4double G4INCL::KinematicsUtils::momentumInLab (const G4double s, const G4double m1, const G4double m2)
Definition at line 124 of file G4INCLKinematicsUtils.cc.
momentumInLab() [2/2]
G4double G4INCL::KinematicsUtils::momentumInLab (Particle const *const p1, Particle const *const p2)
gives the momentum in the lab frame of two particles.
Assumes particle 1 carries all the momentum and particle 2 is at rest.
The formula is the following:
Parameters
p1 pointer to particle 1
p2 pointer to particle 2
Returns
the absolute value of the momentum of particle 1 in the lab frame, in MeV/c
Definition at line 135 of file G4INCLKinematicsUtils.cc.
Referenced by G4INCL::CrossSectionsINCL46::elasticNNLegacy(), G4INCL::CrossSectionsMultiPionsAndResonances::etaNElastic(), G4INCL::CrossSectionsMultiPionsAndResonances::etaNToPiN(), G4INCL::CrossSectionsMultiPionsAndResonances::etaNToPiPiN(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::EtaNElasticChannel::fillFinalState(), G4INCL::EtaNToPiNChannel::fillFinalState(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::ElasticChannel::fillFinalState(), G4INCL::NKbToSpiChannel::KaonMomentum(), G4INCL::NpiToLKChannel::KaonMomentum(), G4INCL::NKbToNKbChannel::KaonMomentum(), G4INCL::NpiToSKChannel::KaonMomentum(), G4INCL::NKbToLpiChannel::KaonMomentum(), G4INCL::NKbElasticChannel::KaonMomentum(), G4INCL::CrossSectionsINCL46::NDeltaToNN(), G4INCL::CrossSectionsStrangeness::NKbelastic(), G4INCL::CrossSectionsStrangeness::NKbToNKb(), G4INCL::CrossSectionsStrangeness::NKbToNKb2pi(), G4INCL::CrossSectionsStrangeness::NKbToNKbpi(), G4INCL::CrossSectionsStrangeness::NKbToS2pi(), G4INCL::CrossSectionsStrangeness::NKbToSpi(), G4INCL::CrossSectionsStrangeness::NKelastic(), G4INCL::CrossSectionsStrangeness::NKToNK(), G4INCL::CrossSectionsStrangeness::NKToNK2pi(), G4INCL::CrossSectionsStrangeness::NKToNKpi(), G4INCL::CrossSectionsStrangeness::NLToNS(), G4INCL::CrossSectionsMultiPions::NNElastic(), G4INCL::CrossSectionsMultiPions::NNElasticFixed(), G4INCL::CrossSectionsMultiPions::NNOnePiOrDelta(), G4INCL::CrossSectionsMultiPions::NNThreePi(), G4INCL::CrossSectionsStrangeness::NNToMissingStrangeness(), G4INCL::CrossSectionsINCL46::NNToNDelta(), G4INCL::CrossSectionsStrangeness::NNToNLK(), G4INCL::CrossSectionsStrangeness::NNToNSK(), G4INCL::CrossSectionsMultiPions::NNTotFixed(), G4INCL::CrossSectionsMultiPions::NNTwoPi(), G4INCL::CrossSectionsStrangeness::NpiToLK2pi(), G4INCL::CrossSectionsStrangeness::NpiToLKpi(), G4INCL::CrossSectionsStrangeness::NpiToMissingStrangeness(), G4INCL::CrossSectionsStrangeness::NpiToNKKb(), G4INCL::CrossSectionsStrangeness::NpiToSK2pi(), G4INCL::CrossSectionsStrangeness::NpiToSKpi(), G4INCL::CrossSectionsStrangeness::NSToNL(), G4INCL::CrossSectionsStrangeness::NSToNS(), G4INCL::CrossSectionsStrangeness::NYelastic(), G4INCL::CrossSectionsMultiPionsAndResonances::omegaNElastic(), G4INCL::CrossSectionsMultiPionsAndResonances::omegaNInelastic(), G4INCL::CrossSectionsMultiPionsAndResonances::omegaNToPiN(), G4INCL::CrossSectionsStrangeness::p_kmToL_pp_pm(), G4INCL::CrossSectionsStrangeness::p_kmToL_pz(), G4INCL::CrossSectionsStrangeness::p_pimToLK0(), G4INCL::CrossSectionsStrangeness::p_pimToSmKp(), G4INCL::CrossSectionsStrangeness::p_pimToSzKz(), G4INCL::CrossSectionsStrangeness::p_pipToSpKp(), G4INCL::CrossSectionsStrangeness::p_pizToSzKp(), G4INCL::CrossSectionsMultiPions::piMinuspIne(), G4INCL::CrossSectionsMultiPions::piMinuspOnePi(), G4INCL::CrossSectionsMultiPionsAndResonances::piMinuspToEtaN(), G4INCL::CrossSectionsMultiPionsAndResonances::piMinuspToOmegaN(), G4INCL::CrossSectionsMultiPions::piMinuspTwoPi(), G4INCL::CrossSectionsMultiPions::piNIne(), G4INCL::CrossSectionsMultiPions::piNOnePi(), G4INCL::CrossSectionsMultiPions::piNToxPiN(), G4INCL::CrossSectionsMultiPions::piNTwoPi(), G4INCL::CrossSectionsMultiPions::piPluspIne(), G4INCL::CrossSectionsMultiPions::piPluspOnePi(), and G4INCL::CrossSectionsMultiPions::piPluspTwoPi().
squareInvariantMass()
G4double G4INCL::KinematicsUtils::squareInvariantMass (const G4double E, const ThreeVector & p)
Definition at line 166 of file G4INCLKinematicsUtils.cc.
Referenced by invariantMass().
squareTotalEnergyInCM()
G4double G4INCL::KinematicsUtils::squareTotalEnergyInCM (Particle const *const p1, Particle const *const p2)
Definition at line 98 of file G4INCLKinematicsUtils.cc.
Referenced by G4INCL::CrossSectionsINCL46::elasticNNLegacy(), G4INCL::ElasticChannel::fillFinalState(), G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar(), G4INCL::BinaryCollisionAvatar::getChannel(), momentumInLab(), G4INCL::CrossSectionsStrangeness::NDeltaToDeltaLK(), G4INCL::CrossSectionsStrangeness::NDeltaToDeltaSK(), G4INCL::CrossSectionsStrangeness::NDeltaToNLK(), G4INCL::CrossSectionsINCL46::NDeltaToNN(), G4INCL::CrossSectionsMultiPions::NDeltaToNN(), G4INCL::CrossSectionsStrangeness::NDeltaToNSK(), G4INCL::CrossSectionsMultiPions::NNElastic(), G4INCL::CrossSectionsMultiPions::NNFourPi(), G4INCL::CrossSectionsMultiPions::NNTot(), and totalEnergyInCM().
sumMomenta()
ThreeVector G4INCL::KinematicsUtils::sumMomenta (const ParticleList & pl)
Definition at line 150 of file G4INCLKinematicsUtils.cc.
sumTotalEnergies()
G4double G4INCL::KinematicsUtils::sumTotalEnergies (const ParticleList & pl)
Definition at line 142 of file G4INCLKinematicsUtils.cc.
totalEnergyInCM()
G4double G4INCL::KinematicsUtils::totalEnergyInCM (Particle const *const p1, Particle const *const p2)
Definition at line 94 of file G4INCLKinematicsUtils.cc.
Referenced by G4INCL::CrossSectionsMultiPionsAndResonances::etaNToPiN(), G4INCL::EtaNToPiPiNChannel::fillFinalState(), G4INCL::NNToNSKChannel::fillFinalState(), G4INCL::NNToNSKpiChannel::fillFinalState(), G4INCL::PiNToEtaChannel::fillFinalState(), G4INCL::NpiToLK2piChannel::fillFinalState(), G4INCL::NpiToLKpiChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::NpiToNKKbChannel::fillFinalState(), G4INCL::NpiToSK2piChannel::fillFinalState(), G4INCL::NpiToSKpiChannel::fillFinalState(), G4INCL::NSToNLChannel::fillFinalState(), G4INCL::NSToNSChannel::fillFinalState(), G4INCL::OmegaNToPiPiNChannel::fillFinalState(), G4INCL::PiNToMultiPionsChannel::fillFinalState(), G4INCL::NDeltaToDeltaLKChannel::fillFinalState(), G4INCL::NNToNSK2piChannel::fillFinalState(), G4INCL::NDeltaToDeltaSKChannel::fillFinalState(), G4INCL::NDeltaToNLKChannel::fillFinalState(), G4INCL::NDeltaToNNKKbChannel::fillFinalState(), G4INCL::NNToNLKpiChannel::fillFinalState(), G4INCL::NDeltaToNSKChannel::fillFinalState(), G4INCL::NKbToL2piChannel::fillFinalState(), G4INCL::NKbToNKb2piChannel::fillFinalState(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NKbToNKbpiChannel::fillFinalState(), G4INCL::NKbToS2piChannel::fillFinalState(), G4INCL::NKToNK2piChannel::fillFinalState(), G4INCL::NKToNKpiChannel::fillFinalState(), G4INCL::NLToNSChannel::fillFinalState(), G4INCL::NNEtaToMultiPionsChannel::fillFinalState(), G4INCL::NNOmegaToMultiPionsChannel::fillFinalState(), G4INCL::NNToMultiPionsChannel::fillFinalState(), G4INCL::NNToNLK2piChannel::fillFinalState(), G4INCL::NNToNLKChannel::fillFinalState(), G4INCL::NNToNNEtaChannel::fillFinalState(), G4INCL::NNToNNKKbChannel::fillFinalState(), G4INCL::NNToNNOmegaChannel::fillFinalState(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::NDeltaEtaProductionChannel::fillFinalState(), G4INCL::StrangeAbsorbtionChannel::fillFinalState(), G4INCL::NDeltaOmegaProductionChannel::fillFinalState(), G4INCL::RecombinationChannel::fillFinalState(), G4INCL::CrossSectionsStrangeness::NDeltaToNNKKb(), G4INCL::CrossSectionsMultiPions::NNOnePi(), G4INCL::CrossSectionsMultiPions::NNOnePiOrDelta(), G4INCL::CrossSectionsMultiPions::NNThreePi(), G4INCL::CrossSectionsINCL46::NNToNDelta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNDeltaEta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNDeltaOmega(), G4INCL::CrossSectionsStrangeness::NNToNLK2pi(), G4INCL::CrossSectionsStrangeness::NNToNLKpi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaExclu(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaFourPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaOnePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaOnePiOrDelta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaThreePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaTwoPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaxPi(), G4INCL::CrossSectionsStrangeness::NNToNNKKb(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmega(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaExclu(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaFourPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaOnePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaOnePiOrDelta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaThreePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaTwoPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaxPi(), G4INCL::CrossSectionsStrangeness::NNToNSK2pi(), G4INCL::CrossSectionsStrangeness::NNToNSKpi(), G4INCL::CrossSectionsMultiPions::NNTwoPi(), G4INCL::CrossSectionsMultiPionsAndResonances::omegaNToPiN(), G4INCL::CrossSectionsMultiPionsAndResonances::piMinuspToEtaN(), G4INCL::CrossSectionsMultiPionsAndResonances::piMinuspToOmegaN(), G4INCL::CrossSectionsINCL46::piNToDelta(), G4INCL::CrossSectionsMultiPions::piNToDelta(), and G4INCL::CrossSectionsMultiPions::piNTot().
transformToLocalEnergyFrame()
void G4INCL::KinematicsUtils::transformToLocalEnergyFrame (Nucleus const *const n, Particle *const p)
Definition at line 45 of file G4INCLKinematicsUtils.cc.
Referenced by G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar(), and G4INCL::InteractionAvatar::preInteractionLocalEnergy().