Geant4: G4QGSMFragmentation Class Reference
G4QGSMFragmentation Class Reference
#include <G4QGSMFragmentation.hh>
Public Member Functions
G4QGSMFragmentation ()
~G4QGSMFragmentation ()
virtual G4KineticTrackVector * FragmentString (const G4ExcitedString &theString)
Public Member Functions inherited from G4VLongitudinalStringDecay
G4VLongitudinalStringDecay ()
virtual ~G4VLongitudinalStringDecay ()
G4int SampleQuarkFlavor (void)
G4ThreeVector SampleQuarkPt (G4double ptMax=-1.)
G4KineticTrackVector * DecayResonans (G4KineticTrackVector *aHadrons)
void SetSigmaTransverseMomentum (G4double aQT)
void SetStrangenessSuppression (G4double aValue)
void SetDiquarkSuppression (G4double aValue)
void SetDiquarkBreakProbability (G4double aValue)
void SetVectorMesonProbability (G4double aValue)
void SetSpinThreeHalfBarionProbability (G4double aValue)
void SetScalarMesonMixings (std::vector< G4double > aVector)
void SetVectorMesonMixings (std::vector< G4double > aVector)
void SetStringTensionParameter (G4double aValue)
Private Member Functions
G4QGSMFragmentation (const G4QGSMFragmentation &right)
const G4QGSMFragmentation & operator= (const G4QGSMFragmentation &right)
int operator== (const G4QGSMFragmentation &right) const
int operator!= (const G4QGSMFragmentation &right) const
void SetMinMasses ()
void SetMinimalStringMass (const G4FragmentingString *const string)
void SetMinimalStringMass2 (const G4double aValue)
virtual G4bool StopFragmenting (const G4FragmentingString *const string)
virtual G4bool IsFragmentable (const G4FragmentingString *const string)
virtual G4bool SplitLast (G4FragmentingString *string, G4KineticTrackVector *LeftVector, G4KineticTrackVector *RightVector)
virtual void Sample4Momentum (G4LorentzVector *Mom, G4double Mass, G4LorentzVector *AntiMom, G4double AntiMass, G4double InitialMass)
virtual G4KineticTrack * Splitup (G4FragmentingString *string, G4FragmentingString *&newString)
virtual G4LorentzVector * SplitEandP (G4ParticleDefinition *pHadron, G4FragmentingString *string, G4FragmentingString *newString)
virtual G4double GetLightConeZ (G4double zmin, G4double zmax, G4int PartonEncoding, G4ParticleDefinition *pHadron, G4double Px, G4double Py)
virtual G4ParticleDefinition * DiQuarkSplitup (G4ParticleDefinition *decay, G4ParticleDefinition *&created)
Private Attributes
G4double Mass_of_light_quark
G4double Mass_of_heavy_quark
G4double Mass_of_string_junction
G4double minMassQQbarStr [3][3]
G4double minMassQDiQStr [3][3][3]
G4double MinimalStringMass
G4double MinimalStringMass2
const G4double arho
const G4double aphi
const G4double an
const G4double ala
const G4double aksi
const G4double alft
Additional Inherited Members
Protected Types inherited from G4VLongitudinalStringDecay
typedef std::pair< G4ParticleDefinition *, G4ParticleDefinition * > pDefPair
typedef G4ParticleDefinition *(G4HadronBuilder::* Pcreate) (G4ParticleDefinition *, G4ParticleDefinition *)
Protected Member Functions inherited from G4VLongitudinalStringDecay
virtual void SetMassCut (G4double aValue)
G4double GetMassCut ()
G4KineticTrackVector * LightFragmentationTest (const G4ExcitedString *const theString)
G4double FragmentationMass (const G4FragmentingString *const string, Pcreate build=0, pDefPair *pdefs=0)
G4ParticleDefinition * FindParticle (G4int Encoding)
G4ExcitedString * CopyExcited (const G4ExcitedString &string)
G4ParticleDefinition * QuarkSplitup (G4ParticleDefinition *decay, G4ParticleDefinition *&created)
pDefPair CreatePartonPair (G4int NeedParticle, G4bool AllowDiquarks=true)
void CalculateHadronTimePosition (G4double theInitialStringMass, G4KineticTrackVector *)
void ConstructParticle ()
G4ParticleDefinition * CreateHadron (G4int id1, G4int id2, G4bool theGivenSpin, G4int theSpin)
G4double GetDiquarkSuppress ()
G4double GetDiquarkBreakProb ()
G4double GetStrangeSuppress ()
G4double GetClusterMass ()
G4int GetClusterLoopInterrupt ()
G4double GetStringTensionParameter ()
Protected Attributes inherited from G4VLongitudinalStringDecay
G4double MassCut
G4double ClusterMass
G4double SigmaQT
G4double DiquarkSuppress
G4double DiquarkBreakProb
G4double SmoothParam
G4double StrangeSuppress
G4int StringLoopInterrupt
G4int ClusterLoopInterrupt
G4HadronBuilder * hadronizer
G4double pspin_meson
G4double pspin_barion
std::vector< G4double > vectorMesonMix
std::vector< G4double > scalarMesonMix
G4bool PastInitPhase
G4double Kappa
Detailed Description
Definition at line 39 of file G4QGSMFragmentation.hh.
Constructor & Destructor Documentation
G4QGSMFragmentation() [1/2]
G4QGSMFragmentation::G4QGSMFragmentation ()
Definition at line 49 of file G4QGSMFragmentation.cc.
~G4QGSMFragmentation()
G4QGSMFragmentation::~G4QGSMFragmentation ()
Definition at line 74 of file G4QGSMFragmentation.cc.
G4QGSMFragmentation() [2/2]
G4QGSMFragmentation::G4QGSMFragmentation (const G4QGSMFragmentation & right) private
Member Function Documentation
DiQuarkSplitup()
G4ParticleDefinition * G4QGSMFragmentation::DiQuarkSplitup (G4ParticleDefinition * decay, G4ParticleDefinition *& created) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 615 of file G4QGSMFragmentation.cc.
Referenced by Splitup().
FragmentString()
G4KineticTrackVector * G4QGSMFragmentation::FragmentString (const G4ExcitedString & theString) virtual
Implements G4VLongitudinalStringDecay.
Definition at line 79 of file G4QGSMFragmentation.cc.
GetLightConeZ()
G4double G4QGSMFragmentation::GetLightConeZ (G4double zmin, G4double zmax, G4int PartonEncoding, G4ParticleDefinition * pHadron, G4double Px, G4double Py) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 228 of file G4QGSMFragmentation.cc.
Referenced by SplitEandP().
IsFragmentable()
G4bool G4QGSMFragmentation::IsFragmentable (const G4FragmentingString *const string) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 563 of file G4QGSMFragmentation.cc.
operator!=()
int G4QGSMFragmentation::operator!= (const G4QGSMFragmentation & right) const private
operator=()
const G4QGSMFragmentation& G4QGSMFragmentation::operator= (const G4QGSMFragmentation & right) private
operator==()
int G4QGSMFragmentation::operator== (const G4QGSMFragmentation & right) const private
Sample4Momentum()
void G4QGSMFragmentation::Sample4Momentum (G4LorentzVector * Mom, G4double Mass, G4LorentzVector * AntiMom, G4double AntiMass, G4double InitialMass) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 592 of file G4QGSMFragmentation.cc.
Referenced by SplitLast().
SetMinimalStringMass()
void G4QGSMFragmentation::SetMinimalStringMass (const G4FragmentingString *const string) private
Definition at line 781 of file G4QGSMFragmentation.cc.
Referenced by SplitEandP(), and StopFragmenting().
SetMinimalStringMass2()
void G4QGSMFragmentation::SetMinimalStringMass2 (const G4double aValue) private
Definition at line 885 of file G4QGSMFragmentation.cc.
Referenced by SetMinimalStringMass().
SetMinMasses()
void G4QGSMFragmentation::SetMinMasses () private
Definition at line 757 of file G4QGSMFragmentation.cc.
Referenced by G4QGSMFragmentation().
SplitEandP()
G4LorentzVector * G4QGSMFragmentation::SplitEandP (G4ParticleDefinition * pHadron, G4FragmentingString * string, G4FragmentingString * newString) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 379 of file G4QGSMFragmentation.cc.
Referenced by Splitup().
SplitLast()
G4bool G4QGSMFragmentation::SplitLast (G4FragmentingString * string, G4KineticTrackVector * LeftVector, G4KineticTrackVector * RightVector) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 472 of file G4QGSMFragmentation.cc.
Referenced by FragmentString().
Splitup()
G4KineticTrack * G4QGSMFragmentation::Splitup (G4FragmentingString * string, G4FragmentingString *& newString) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 667 of file G4QGSMFragmentation.cc.
Referenced by FragmentString().
StopFragmenting()
G4bool G4QGSMFragmentation::StopFragmenting (const G4FragmentingString *const string) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 570 of file G4QGSMFragmentation.cc.
Referenced by FragmentString().
Field Documentation
aksi
const G4double G4QGSMFragmentation::aksi private
Definition at line 99 of file G4QGSMFragmentation.hh.
Referenced by GetLightConeZ().
ala
const G4double G4QGSMFragmentation::ala private
Definition at line 98 of file G4QGSMFragmentation.hh.
Referenced by GetLightConeZ().
alft
const G4double G4QGSMFragmentation::alft private
Definition at line 100 of file G4QGSMFragmentation.hh.
Referenced by GetLightConeZ().
an
const G4double G4QGSMFragmentation::an private
Definition at line 97 of file G4QGSMFragmentation.hh.
Referenced by GetLightConeZ().
aphi
const G4double G4QGSMFragmentation::aphi private
Definition at line 96 of file G4QGSMFragmentation.hh.
Referenced by GetLightConeZ().
arho
const G4double G4QGSMFragmentation::arho private
Definition at line 95 of file G4QGSMFragmentation.hh.
Referenced by GetLightConeZ().
Mass_of_heavy_quark
G4double G4QGSMFragmentation::Mass_of_heavy_quark private
Definition at line 84 of file G4QGSMFragmentation.hh.
Referenced by SetMinimalStringMass(), and SetMinMasses().
Mass_of_light_quark
G4double G4QGSMFragmentation::Mass_of_light_quark private
Definition at line 83 of file G4QGSMFragmentation.hh.
Referenced by SetMinimalStringMass(), and SetMinMasses().
Mass_of_string_junction
G4double G4QGSMFragmentation::Mass_of_string_junction private
Definition at line 85 of file G4QGSMFragmentation.hh.
Referenced by SetMinMasses().
MinimalStringMass
G4double G4QGSMFragmentation::MinimalStringMass private
Definition at line 91 of file G4QGSMFragmentation.hh.
Referenced by SetMinimalStringMass(), SetMinMasses(), SplitEandP(), and StopFragmenting().
MinimalStringMass2
G4double G4QGSMFragmentation::MinimalStringMass2 private
Definition at line 92 of file G4QGSMFragmentation.hh.
Referenced by SetMinimalStringMass2(), and SetMinMasses().
minMassQDiQStr
G4double G4QGSMFragmentation::minMassQDiQStr[3][3][3] private
Definition at line 88 of file G4QGSMFragmentation.hh.
Referenced by SetMinimalStringMass(), and SetMinMasses().
minMassQQbarStr
G4double G4QGSMFragmentation::minMassQQbarStr[3][3] private
Definition at line 87 of file G4QGSMFragmentation.hh.
Referenced by SetMinimalStringMass(), and SetMinMasses().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/parton_string/hadronization/include/G4QGSMFragmentation.hh
source/processes/hadronic/models/parton_string/hadronization/src/G4QGSMFragmentation.cc