Geant4: G4VITRestDiscreteProcess Class Reference
G4VITRestDiscreteProcess Class Reference abstract
Identical to G4VRestDiscreteProcess with dependency from G4VITProcess.
#include <G4VITRestDiscreteProcess.hh>
Public Member Functions
G4VITRestDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VITRestDiscreteProcess (const G4VITRestDiscreteProcess &)
virtual ~G4VITRestDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VITProcess
G4VITProcess (const G4String &name, G4ProcessType type=fNotDefined)
virtual ~G4VITProcess ()
G4VITProcess (const G4VITProcess &other)
G4VITProcess & operator= (const G4VITProcess &other)
G4int operator== (const G4VITProcess &right) const
G4int operator!= (const G4VITProcess &right) const
size_t GetProcessID () const
G4shared_ptr< G4ProcessState_Lock > GetProcessState ()
void SetProcessState (G4shared_ptr< G4ProcessState_Lock > aProcInfo)
void ResetProcessState ()
virtual void StartTracking (G4Track *)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
G4double GetInteractionTimeLeft ()
virtual void ResetNumberOfInteractionLengthLeft ()
WARNING : Redefine the method of G4VProcess reset (determine the value of)NumberOfInteractionLengthLeft.
G4bool ProposesTimeStep () const
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
virtual G4double GetMeanFreePath (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition)=0
virtual G4double GetMeanLifeTime (const G4Track &aTrack, G4ForceCondition *condition)=0
G4VITRestDiscreteProcess ()
G4VITRestDiscreteProcess & operator= (const G4VITRestDiscreteProcess &right)
Protected Member Functions inherited from G4VITProcess
void RetrieveProcessInfo ()
void CreateInfo ()
template<typename T >
T * GetState ()
virtual void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
virtual void ClearInteractionTimeLeft ()
virtual void ClearNumberOfInteractionLengthLeft ()
void SetInstantiateProcessState (G4bool flag)
G4bool InstantiateProcessState ()
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Additional Inherited Members
Static Public Member Functions inherited from G4VITProcess
static const size_t & GetMaxProcessIndex ()
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Attributes inherited from G4VITProcess
G4shared_ptr< G4ProcessState > fpState
G4bool fProposesTimeStep
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Identical to G4VRestDiscreteProcess with dependency from G4VITProcess.
Identical to G4VRestDiscreteProcess with dependency from G4VITProcess
Definition at line 62 of file G4VITRestDiscreteProcess.hh.
Constructor & Destructor Documentation
G4VITRestDiscreteProcess() [1/3]
G4VITRestDiscreteProcess::G4VITRestDiscreteProcess (const G4String & aName, G4ProcessType aType = fNotDefined)
Definition at line 44 of file G4VITRestDiscreteProcess.cc.
G4VITRestDiscreteProcess() [2/3]
G4VITRestDiscreteProcess::G4VITRestDiscreteProcess (const G4VITRestDiscreteProcess & right)
Definition at line 54 of file G4VITRestDiscreteProcess.cc.
~G4VITRestDiscreteProcess()
G4VITRestDiscreteProcess::~G4VITRestDiscreteProcess () virtual
Definition at line 50 of file G4VITRestDiscreteProcess.cc.
G4VITRestDiscreteProcess() [3/3]
G4VITRestDiscreteProcess::G4VITRestDiscreteProcess () protected
Definition at line 37 of file G4VITRestDiscreteProcess.cc.
Member Function Documentation
AlongStepDoIt()
virtual G4VParticleChange* G4VITRestDiscreteProcess::AlongStepDoIt (const G4Track & , const G4Step &) inline virtual
Implements G4VProcess.
Definition at line 98 of file G4VITRestDiscreteProcess.hh.
AlongStepGetPhysicalInteractionLength()
virtual G4double G4VITRestDiscreteProcess::AlongStepGetPhysicalInteractionLength (const G4Track & , G4double , G4double , G4double & , G4GPILSelection *) inline virtual
Implements G4VProcess.
Definition at line 88 of file G4VITRestDiscreteProcess.hh.
AtRestDoIt()
G4VParticleChange * G4VITRestDiscreteProcess::AtRestDoIt (const G4Track & , const G4Step &) inline virtual
Implements G4VProcess.
Reimplemented in G4DNAMolecularDissociation, and G4DNAElectronHoleRecombination.
Definition at line 217 of file G4VITRestDiscreteProcess.hh.
AtRestGetPhysicalInteractionLength()
G4double G4VITRestDiscreteProcess::AtRestGetPhysicalInteractionLength (const G4Track & track, G4ForceCondition * condition) inline virtual
Implements G4VProcess.
Reimplemented in G4DNAMolecularDissociation.
Definition at line 189 of file G4VITRestDiscreteProcess.hh.
Referenced by G4DNAMolecularDissociation::AtRestGetPhysicalInteractionLength().
GetMeanFreePath()
virtual G4double G4VITRestDiscreteProcess::GetMeanFreePath (const G4Track & aTrack, G4double previousStepSize, G4ForceCondition * condition) protected pure virtual
Implemented in G4DNAElectronHoleRecombination, and G4DNAMolecularDissociation.
Referenced by PostStepGetPhysicalInteractionLength().
GetMeanLifeTime()
virtual G4double G4VITRestDiscreteProcess::GetMeanLifeTime (const G4Track & aTrack, G4ForceCondition * condition) protected pure virtual
Implemented in G4DNAElectronHoleRecombination, and G4DNAMolecularDissociation.
Referenced by AtRestGetPhysicalInteractionLength().
operator=()
G4VITRestDiscreteProcess& G4VITRestDiscreteProcess::operator= (const G4VITRestDiscreteProcess & right) protected
PostStepDoIt()
G4VParticleChange * G4VITRestDiscreteProcess::PostStepDoIt (const G4Track & , const G4Step &) inline virtual
Implements G4VProcess.
Reimplemented in G4DNAMolecularDissociation, and G4DNAElectronHoleRecombination.
Definition at line 180 of file G4VITRestDiscreteProcess.hh.
PostStepGetPhysicalInteractionLength()
G4double G4VITRestDiscreteProcess::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) inline virtual
Implements G4VProcess.
Reimplemented in G4DNAMolecularDissociation.
Definition at line 129 of file G4VITRestDiscreteProcess.hh.
The documentation for this class was generated from the following files:
source/processes/electromagnetic/dna/management/include/G4VITRestDiscreteProcess.hh
source/processes/electromagnetic/dna/management/src/G4VITRestDiscreteProcess.cc