Geant4: G4FermiChannels Class Reference
G4FermiChannels Class Reference
#include <G4FermiChannels.hh>
Public Member Functions
G4FermiChannels (size_t nmax, G4double ex, G4double gmass)
size_t GetNumberOfChannels () const
const std::vector< const G4FermiPair * > & GetChannels () const
const G4FermiPair * GetPair (size_t idx) const
const G4FermiPair * SamplePair (G4double rand) const
void AddChannel (const G4FermiPair *)
std::vector< G4double > & GetProbabilities ()
G4double GetExcitation () const
G4double GetMass () const
Private Member Functions
const G4FermiChannels & operator= (const G4FermiChannels &)=delete
G4FermiChannels (const G4FermiChannels &)=delete
G4bool operator== (const G4FermiChannels &) const =delete
G4bool operator!= (const G4FermiChannels &) const =delete
Private Attributes
size_t nch
G4double excitation
G4double ground_mass
std::vector< const G4FermiPair * > fvect
std::vector< G4double > cum_prob
Detailed Description
Definition at line 39 of file G4FermiChannels.hh.
Constructor & Destructor Documentation
G4FermiChannels() [1/2]
G4FermiChannels::G4FermiChannels (size_t nmax, G4double ex, G4double gmass) inline explicit
Definition at line 43 of file G4FermiChannels.hh.
G4FermiChannels() [2/2]
G4FermiChannels::G4FermiChannels (const G4FermiChannels &) inline private delete
Member Function Documentation
AddChannel()
void G4FermiChannels::AddChannel (const G4FermiPair * ptr) inline
Definition at line 97 of file G4FermiChannels.hh.
GetChannels()
const std::vector< const G4FermiPair * > & G4FermiChannels::GetChannels () const inline
Definition at line 78 of file G4FermiChannels.hh.
Referenced by G4FermiFragmentsPoolVI::Initialise(), and G4FermiBreakUpVI::SampleDecay().
GetExcitation()
G4double G4FermiChannels::GetExcitation () const inline
Definition at line 109 of file G4FermiChannels.hh.
Referenced by G4FermiBreakUpVI::SampleDecay().
GetMass()
G4double G4FermiChannels::GetMass () const inline
Definition at line 114 of file G4FermiChannels.hh.
GetNumberOfChannels()
size_t G4FermiChannels::GetNumberOfChannels () const inline
Definition at line 73 of file G4FermiChannels.hh.
Referenced by G4FermiFragmentsPoolVI::Initialise(), and G4FermiBreakUpVI::SampleDecay().
GetPair()
const G4FermiPair * G4FermiChannels::GetPair (size_t idx) const inline
Definition at line 83 of file G4FermiChannels.hh.
Referenced by G4FermiBreakUpVI::SampleDecay().
GetProbabilities()
std::vector< G4double > & G4FermiChannels::GetProbabilities () inline
Definition at line 104 of file G4FermiChannels.hh.
Referenced by G4FermiFragmentsPoolVI::Initialise().
operator!=()
G4bool G4FermiChannels::operator!= (const G4FermiChannels &) const inline private delete
operator=()
const G4FermiChannels& G4FermiChannels::operator= (const G4FermiChannels &) inline private delete
operator==()
G4bool G4FermiChannels::operator== (const G4FermiChannels &) const inline private delete
SamplePair()
const G4FermiPair * G4FermiChannels::SamplePair (G4double rand) const inline
Definition at line 88 of file G4FermiChannels.hh.
Referenced by G4FermiBreakUpVI::SampleDecay().
Field Documentation
cum_prob
std::vector<G4double> G4FermiChannels::cum_prob private
Definition at line 69 of file G4FermiChannels.hh.
Referenced by AddChannel(), G4FermiChannels(), GetProbabilities(), and SamplePair().
excitation
G4double G4FermiChannels::excitation private
Definition at line 66 of file G4FermiChannels.hh.
Referenced by GetExcitation(), and GetMass().
fvect
std::vector<const G4FermiPair*> G4FermiChannels::fvect private
Definition at line 68 of file G4FermiChannels.hh.
Referenced by AddChannel(), G4FermiChannels(), GetChannels(), GetPair(), and SamplePair().
ground_mass
G4double G4FermiChannels::ground_mass private
Definition at line 67 of file G4FermiChannels.hh.
Referenced by GetMass().
nch
size_t G4FermiChannels::nch private
Definition at line 65 of file G4FermiChannels.hh.
Referenced by AddChannel(), GetNumberOfChannels(), GetPair(), and SamplePair().
The documentation for this class was generated from the following file:
source/processes/hadronic/models/de_excitation/fermi_breakup/include/G4FermiChannels.hh