Geant4: G4PAIPhotData Class Reference
G4PAIPhotData Class Reference
#include <G4PAIPhotData.hh>
Public Member Functions
G4PAIPhotData (G4double tmin, G4double tmax, G4int verbose)
~G4PAIPhotData ()
void Initialise (const G4MaterialCutsCouple *, G4double cut, G4PAIPhotModel *)
G4double DEDXPerVolume (G4int coupleIndex, G4double scaledTkin, G4double cut) const
G4double CrossSectionPerVolume (G4int coupleIndex, G4double scaledTkin, G4double tcut, G4double tmax) const
G4double GetPlasmonRatio (G4int coupleIndex, G4double scaledTkin) const
G4double SampleAlongStepTransfer (G4int coupleIndex, G4double kinEnergy, G4double scaledTkin, G4double stepFactor) const
G4double SampleAlongStepPhotonTransfer (G4int coupleIndex, G4double kinEnergy, G4double scaledTkin, G4double stepFactor) const
G4double SampleAlongStepPlasmonTransfer (G4int coupleIndex, G4double kinEnergy, G4double scaledTkin, G4double stepFactor) const
G4double SamplePostStepTransfer (G4int coupleIndex, G4double scaledTkin) const
G4double SamplePostStepPhotonTransfer (G4int coupleIndex, G4double scaledTkin) const
G4double SamplePostStepPlasmonTransfer (G4int coupleIndex, G4double scaledTkin) const
Private Member Functions
G4double GetEnergyTransfer (G4int coupleIndex, size_t iPlace, G4double position) const
G4double GetEnergyPhotonTransfer (G4int coupleIndex, size_t iPlace, G4double position) const
G4double GetEnergyPlasmonTransfer (G4int coupleIndex, size_t iPlace, G4double position) const
G4PAIPhotData & operator= (const G4PAIPhotData &right)=delete
G4PAIPhotData (const G4PAIPhotData &)=delete
Private Attributes
G4int fTotBin
G4double fLowestKineticEnergy
G4double fHighestKineticEnergy
G4PhysicsLogVector * fParticleEnergyVector
G4PAIxSection fPAIxSection
G4SandiaTable fSandia
std::vector< G4PhysicsTable * > fPAIxscBank
std::vector< G4PhysicsTable * > fPAIphotonBank
std::vector< G4PhysicsTable * > fPAIplasmonBank
std::vector< G4PhysicsTable * > fPAIdEdxBank
std::vector< G4PhysicsLogVector * > fdEdxTable
std::vector< G4PhysicsLogVector * > fdNdxCutTable
std::vector< G4PhysicsLogVector * > fdNdxCutPhotonTable
std::vector< G4PhysicsLogVector * > fdNdxCutPlasmonTable
std::vector< G4PhysicsLogVector * > fdEdxCutTable
Detailed Description
Definition at line 65 of file G4PAIPhotData.hh.
Constructor & Destructor Documentation
G4PAIPhotData() [1/2]
G4PAIPhotData::G4PAIPhotData (G4double tmin, G4double tmax, G4int verbose) explicit
Definition at line 58 of file G4PAIPhotData.cc.
~G4PAIPhotData()
G4PAIPhotData::~G4PAIPhotData ()
Definition at line 93 of file G4PAIPhotData.cc.
G4PAIPhotData() [2/2]
G4PAIPhotData::G4PAIPhotData (const G4PAIPhotData &) private delete
Member Function Documentation
CrossSectionPerVolume()
G4double G4PAIPhotData::CrossSectionPerVolume (G4int coupleIndex, G4double scaledTkin, G4double tcut, G4double tmax) const
Definition at line 307 of file G4PAIPhotData.cc.
Referenced by G4PAIPhotModel::CrossSectionPerVolume().
DEDXPerVolume()
G4double G4PAIPhotData::DEDXPerVolume (G4int coupleIndex, G4double scaledTkin, G4double cut) const
Definition at line 271 of file G4PAIPhotData.cc.
Referenced by G4PAIPhotModel::ComputeDEDXPerVolume().
GetEnergyPhotonTransfer()
G4double G4PAIPhotData::GetEnergyPhotonTransfer (G4int coupleIndex, size_t iPlace, G4double position) const private
Definition at line 940 of file G4PAIPhotData.cc.
GetEnergyPlasmonTransfer()
G4double G4PAIPhotData::GetEnergyPlasmonTransfer (G4int coupleIndex, size_t iPlace, G4double position) const private
Definition at line 1001 of file G4PAIPhotData.cc.
GetEnergyTransfer()
G4double G4PAIPhotData::GetEnergyTransfer (G4int coupleIndex, size_t iPlace, G4double position) const private
Definition at line 889 of file G4PAIPhotData.cc.
GetPlasmonRatio()
G4double G4PAIPhotData::GetPlasmonRatio (G4int coupleIndex, G4double scaledTkin) const
Definition at line 370 of file G4PAIPhotData.cc.
Referenced by G4PAIPhotModel::SampleSecondaries().
Initialise()
void G4PAIPhotData::Initialise (const G4MaterialCutsCouple * couple, G4double cut, G4PAIPhotModel * model)
Definition at line 126 of file G4PAIPhotData.cc.
Referenced by G4PAIPhotModel::Initialise().
operator=()
G4PAIPhotData& G4PAIPhotData::operator= (const G4PAIPhotData & right) private delete
SampleAlongStepPhotonTransfer()
G4double G4PAIPhotData::SampleAlongStepPhotonTransfer (G4int coupleIndex, G4double kinEnergy, G4double scaledTkin, G4double stepFactor) const
Definition at line 527 of file G4PAIPhotData.cc.
Referenced by G4PAIPhotModel::SampleFluctuations().
SampleAlongStepPlasmonTransfer()
G4double G4PAIPhotData::SampleAlongStepPlasmonTransfer (G4int coupleIndex, G4double kinEnergy, G4double scaledTkin, G4double stepFactor) const
Definition at line 619 of file G4PAIPhotData.cc.
Referenced by G4PAIPhotModel::SampleFluctuations().
SampleAlongStepTransfer()
G4double G4PAIPhotData::SampleAlongStepTransfer (G4int coupleIndex, G4double kinEnergy, G4double scaledTkin, G4double stepFactor) const
Definition at line 435 of file G4PAIPhotData.cc.
SamplePostStepPhotonTransfer()
G4double G4PAIPhotData::SamplePostStepPhotonTransfer (G4int coupleIndex, G4double scaledTkin) const
Definition at line 770 of file G4PAIPhotData.cc.
Referenced by G4PAIPhotModel::SampleSecondaries().
SamplePostStepPlasmonTransfer()
G4double G4PAIPhotData::SamplePostStepPlasmonTransfer (G4int coupleIndex, G4double scaledTkin) const
Definition at line 828 of file G4PAIPhotData.cc.
Referenced by G4PAIPhotModel::SampleSecondaries().
SamplePostStepTransfer()
G4double G4PAIPhotData::SamplePostStepTransfer (G4int coupleIndex, G4double scaledTkin) const
Definition at line 714 of file G4PAIPhotData.cc.
Field Documentation
fdEdxCutTable
std::vector<G4PhysicsLogVector*> G4PAIPhotData::fdEdxCutTable private
Definition at line 134 of file G4PAIPhotData.hh.
fdEdxTable
std::vector<G4PhysicsLogVector*> G4PAIPhotData::fdEdxTable private
Definition at line 128 of file G4PAIPhotData.hh.
fdNdxCutPhotonTable
std::vector<G4PhysicsLogVector*> G4PAIPhotData::fdNdxCutPhotonTable private
Definition at line 131 of file G4PAIPhotData.hh.
fdNdxCutPlasmonTable
std::vector<G4PhysicsLogVector*> G4PAIPhotData::fdNdxCutPlasmonTable private
Definition at line 132 of file G4PAIPhotData.hh.
fdNdxCutTable
std::vector<G4PhysicsLogVector*> G4PAIPhotData::fdNdxCutTable private
Definition at line 130 of file G4PAIPhotData.hh.
fHighestKineticEnergy
G4double G4PAIPhotData::fHighestKineticEnergy private
Definition at line 116 of file G4PAIPhotData.hh.
fLowestKineticEnergy
G4double G4PAIPhotData::fLowestKineticEnergy private
Definition at line 115 of file G4PAIPhotData.hh.
fPAIdEdxBank
std::vector<G4PhysicsTable*> G4PAIPhotData::fPAIdEdxBank private
Definition at line 127 of file G4PAIPhotData.hh.
fPAIphotonBank
std::vector<G4PhysicsTable*> G4PAIPhotData::fPAIphotonBank private
Definition at line 124 of file G4PAIPhotData.hh.
fPAIplasmonBank
std::vector<G4PhysicsTable*> G4PAIPhotData::fPAIplasmonBank private
Definition at line 125 of file G4PAIPhotData.hh.
fPAIxscBank
std::vector<G4PhysicsTable*> G4PAIPhotData::fPAIxscBank private
Definition at line 123 of file G4PAIPhotData.hh.
fPAIxSection
G4PAIxSection G4PAIPhotData::fPAIxSection private
Definition at line 120 of file G4PAIPhotData.hh.
fParticleEnergyVector
G4PhysicsLogVector* G4PAIPhotData::fParticleEnergyVector private
Definition at line 118 of file G4PAIPhotData.hh.
fSandia
G4SandiaTable G4PAIPhotData::fSandia private
Definition at line 121 of file G4PAIPhotData.hh.
fTotBin
G4int G4PAIPhotData::fTotBin private
Definition at line 114 of file G4PAIPhotData.hh.
The documentation for this class was generated from the following files:
source/processes/electromagnetic/standard/include/G4PAIPhotData.hh
source/processes/electromagnetic/standard/src/G4PAIPhotData.cc