Geant4: G4PhysListRegistry Class Reference
G4PhysListRegistry Class Reference
#include <G4PhysListRegistry.hh>
Public Member Functions
~G4PhysListRegistry ()
void AddFactory (G4String name, G4VBasePhysListStamper *)
void AddPhysicsExtension (G4String name, G4String procname)
G4VModularPhysicsList * GetModularPhysicsList (const G4String &name)
G4VModularPhysicsList * GetModularPhysicsListFromEnv ()
G4bool IsReferencePhysList (G4String nam) const
const std::vector< G4String > & AvailablePhysLists () const
const std::vector< G4String > & AvailablePhysicsExtensions () const
const std::vector< G4String > & AvailablePhysListsEM () const
void PrintAvailablePhysLists () const
G4bool DeconstructPhysListName (const G4String &name, G4String &plBase, std::vector< G4String > &physExt, std::vector< G4int > &replace, G4int verbose=0) const
G4bool FindLongestMatch (const G4String &workName, const G4String &searchName, const std::vector< G4String > &validNames, G4String &bestMatch, G4int verbose=0) const
void SetVerbose (G4int val)
G4int GetVerbose () const
void SetUnknownFatal (G4int val)
G4int GetUnknownFatal () const
void SetUserDefaultPhysList (const G4String &name="")
G4String GetUserDefaultPhysList () const
G4String GetSystemDefaultPhysList () const
Static Public Member Functions
static G4PhysListRegistry * Instance ()
Private Member Functions
G4PhysListRegistry ()
Private Attributes
std::map< G4String, G4VBasePhysListStamper * > factories
std::map< G4String, G4String > physicsExtensions
G4int verbose
G4int unknownFatal
G4String userDefault
throw an exception if unsatisfiable?
G4String systemDefault
use this if $PHYSLIST isn't set
std::vector< G4String > availBasePhysLists
use this if user hasn't set userDefault or attempts to set the userDefault=""
std::vector< G4String > availExtensions
Static Private Attributes
static G4ThreadLocal G4PhysListRegistry * theInstance = 0
Detailed Description
Definition at line 56 of file G4PhysListRegistry.hh.
Constructor & Destructor Documentation
~G4PhysListRegistry()
G4PhysListRegistry::~G4PhysListRegistry ()
Definition at line 100 of file G4PhysListRegistry.cc.
G4PhysListRegistry()
G4PhysListRegistry::G4PhysListRegistry () private
Definition at line 92 of file G4PhysListRegistry.cc.
Referenced by Instance().
Member Function Documentation
AddFactory()
void G4PhysListRegistry::AddFactory (G4String name, G4VBasePhysListStamper * factory)
Definition at line 110 of file G4PhysListRegistry.cc.
Referenced by G4PhysListStamper< T >::G4PhysListStamper().
AddPhysicsExtension()
void G4PhysListRegistry::AddPhysicsExtension (G4String name, G4String procname)
Definition at line 115 of file G4PhysListRegistry.cc.
Referenced by Instance(), and main().
AvailablePhysicsExtensions()
const std::vector< G4String > & G4PhysListRegistry::AvailablePhysicsExtensions () const
Definition at line 389 of file G4PhysListRegistry.cc.
Referenced by AvailablePhysListsEM(), and DeconstructPhysListName().
AvailablePhysLists()
const std::vector< G4String > & G4PhysListRegistry::AvailablePhysLists () const
Definition at line 378 of file G4PhysListRegistry.cc.
Referenced by g4alt::G4PhysListFactory::AvailablePhysLists(), DeconstructPhysListName(), and PrintAvailablePhysLists().
AvailablePhysListsEM()
const std::vector< G4String > & G4PhysListRegistry::AvailablePhysListsEM () const
Definition at line 400 of file G4PhysListRegistry.cc.
Referenced by g4alt::G4PhysListFactory::AvailablePhysListsEM().
DeconstructPhysListName()
G4bool G4PhysListRegistry::DeconstructPhysListName (const G4String & name, G4String & plBase, std::vector< G4String > & physExt, std::vector< G4int > & replace, G4int verbose = 0) const
Definition at line 231 of file G4PhysListRegistry.cc.
Referenced by GetModularPhysicsList(), and IsReferencePhysList().
FindLongestMatch()
G4bool G4PhysListRegistry::FindLongestMatch (const G4String & workName, const G4String & searchName, const std::vector< G4String > & validNames, G4String & bestMatch, G4int verbose = 0) const
Definition at line 341 of file G4PhysListRegistry.cc.
Referenced by DeconstructPhysListName().
GetModularPhysicsList()
G4VModularPhysicsList * G4PhysListRegistry::GetModularPhysicsList (const G4String & name)
Definition at line 122 of file G4PhysListRegistry.cc.
Referenced by GetModularPhysicsListFromEnv(), and g4alt::G4PhysListFactory::GetReferencePhysList().
GetModularPhysicsListFromEnv()
G4VModularPhysicsList * G4PhysListRegistry::GetModularPhysicsListFromEnv ()
Definition at line 201 of file G4PhysListRegistry.cc.
Referenced by g4alt::G4PhysListFactory::ReferencePhysList().
GetSystemDefaultPhysList()
G4String G4PhysListRegistry::GetSystemDefaultPhysList () const inline
Definition at line 102 of file G4PhysListRegistry.hh.
GetUnknownFatal()
G4int G4PhysListRegistry::GetUnknownFatal () const inline
Definition at line 95 of file G4PhysListRegistry.hh.
Referenced by g4alt::G4PhysListFactory::GetUnknownFatal().
GetUserDefaultPhysList()
G4String G4PhysListRegistry::GetUserDefaultPhysList () const inline
Definition at line 98 of file G4PhysListRegistry.hh.
GetVerbose()
G4int G4PhysListRegistry::GetVerbose () const inline
Definition at line 92 of file G4PhysListRegistry.hh.
Referenced by g4alt::G4PhysListFactory::GetVerbose().
Instance()
G4PhysListRegistry * G4PhysListRegistry::Instance (void) static
Definition at line 64 of file G4PhysListRegistry.cc.
Referenced by g4alt::G4PhysListFactory::AvailablePhysLists(), g4alt::G4PhysListFactory::AvailablePhysListsEM(), G4PhysListStamper< T >::G4PhysListStamper(), g4alt::G4PhysListFactory::GetReferencePhysList(), g4alt::G4PhysListFactory::GetUnknownFatal(), g4alt::G4PhysListFactory::GetVerbose(), g4alt::G4PhysListFactory::IsReferencePhysList(), main(), g4alt::G4PhysListFactory::PrintAvailablePhysLists(), g4alt::G4PhysListFactory::ReferencePhysList(), g4alt::G4PhysListFactory::SetDefaultReferencePhysList(), g4alt::G4PhysListFactory::SetUnknownFatal(), and g4alt::G4PhysListFactory::SetVerbose().
IsReferencePhysList()
G4bool G4PhysListRegistry::IsReferencePhysList (G4String nam) const
Definition at line 222 of file G4PhysListRegistry.cc.
Referenced by g4alt::G4PhysListFactory::IsReferencePhysList().
PrintAvailablePhysLists()
void G4PhysListRegistry::PrintAvailablePhysLists () const
Definition at line 408 of file G4PhysListRegistry.cc.
Referenced by g4alt::G4PhysListFactory::PrintAvailablePhysLists().
SetUnknownFatal()
void G4PhysListRegistry::SetUnknownFatal (G4int val) inline
Definition at line 94 of file G4PhysListRegistry.hh.
Referenced by g4alt::G4PhysListFactory::SetUnknownFatal().
SetUserDefaultPhysList()
void G4PhysListRegistry::SetUserDefaultPhysList (const G4String & name = "")
Definition at line 104 of file G4PhysListRegistry.cc.
Referenced by G4PhysListRegistry(), and g4alt::G4PhysListFactory::SetDefaultReferencePhysList().
SetVerbose()
void G4PhysListRegistry::SetVerbose (G4int val) inline
Definition at line 91 of file G4PhysListRegistry.hh.
Referenced by g4alt::G4PhysListFactory::SetVerbose().
Field Documentation
availBasePhysLists
std::vector<G4String> G4PhysListRegistry::availBasePhysLists mutable private
use this if user hasn't set userDefault or attempts to set the userDefault=""
Definition at line 124 of file G4PhysListRegistry.hh.
Referenced by AvailablePhysLists().
availExtensions
std::vector<G4String> G4PhysListRegistry::availExtensions mutable private
Definition at line 125 of file G4PhysListRegistry.hh.
Referenced by AvailablePhysicsExtensions().
factories
std::map<G4String, G4VBasePhysListStamper*> G4PhysListRegistry::factories private
Definition at line 110 of file G4PhysListRegistry.hh.
Referenced by AddFactory(), AvailablePhysLists(), and GetModularPhysicsList().
physicsExtensions
std::map<G4String, G4String> G4PhysListRegistry::physicsExtensions private
Definition at line 111 of file G4PhysListRegistry.hh.
Referenced by AddPhysicsExtension(), AvailablePhysicsExtensions(), DeconstructPhysListName(), GetModularPhysicsList(), and PrintAvailablePhysLists().
systemDefault
G4String G4PhysListRegistry::systemDefault private
use this if $PHYSLIST isn't set
Definition at line 116 of file G4PhysListRegistry.hh.
Referenced by GetSystemDefaultPhysList(), and SetUserDefaultPhysList().
theInstance
G4ThreadLocal G4PhysListRegistry * G4PhysListRegistry::theInstance = 0 static private
Definition at line 108 of file G4PhysListRegistry.hh.
Referenced by Instance().
unknownFatal
G4int G4PhysListRegistry::unknownFatal private
Definition at line 114 of file G4PhysListRegistry.hh.
Referenced by GetModularPhysicsList(), GetUnknownFatal(), and SetUnknownFatal().
userDefault
G4String G4PhysListRegistry::userDefault private
throw an exception if unsatisfiable?
Definition at line 115 of file G4PhysListRegistry.hh.
Referenced by GetModularPhysicsListFromEnv(), GetUserDefaultPhysList(), and SetUserDefaultPhysList().
verbose
G4int G4PhysListRegistry::verbose private
Definition at line 113 of file G4PhysListRegistry.hh.
Referenced by GetModularPhysicsList(), GetVerbose(), and SetVerbose().
The documentation for this class was generated from the following files:
source/physics_lists/lists/include/G4PhysListRegistry.hh
source/physics_lists/lists/src/G4PhysListRegistry.cc