Geant4: G4HadronicParameters Class Reference
G4HadronicParameters Class Reference
#include <G4HadronicParameters.hh>
Public Member Functions
~G4HadronicParameters ()
G4double GetMaxEnergy () const
Static Public Member Functions
static G4HadronicParameters * Instance ()
Private Member Functions
G4HadronicParameters ()
Private Attributes
G4double fMaxEnergy
Static Private Attributes
static G4HadronicParameters * sInstance = nullptr
Detailed Description
Definition at line 49 of file G4HadronicParameters.hh.
Constructor & Destructor Documentation
~G4HadronicParameters()
G4HadronicParameters::~G4HadronicParameters ()
Definition at line 59 of file G4HadronicParameters.cc.
G4HadronicParameters()
G4HadronicParameters::G4HadronicParameters () private
Definition at line 62 of file G4HadronicParameters.cc.
Member Function Documentation
GetMaxEnergy()
G4double G4HadronicParameters::GetMaxEnergy () const inline
Definition at line 70 of file G4HadronicParameters.hh.
Referenced by DMXPhysicsList::ConstructHad(), G4IonPhysics::ConstructProcess(), G4HadronInelasticQBBC::ConstructProcess(), G4IonPhysicsPHP::ConstructProcess(), G4IonINCLXXPhysics::ConstructProcess(), G4IonQMDPhysics::ConstructProcess(), GammaRayTelIonPhysics::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), G4FTFBinaryKaonBuilder::G4FTFBinaryKaonBuilder(), G4FTFBinaryNeutronBuilder::G4FTFBinaryNeutronBuilder(), G4FTFBinaryPionBuilder::G4FTFBinaryPionBuilder(), G4FTFBinaryProtonBuilder::G4FTFBinaryProtonBuilder(), G4FTFPAntiBarionBuilder::G4FTFPAntiBarionBuilder(), G4FTFPKaonBuilder::G4FTFPKaonBuilder(), G4FTFPNeutronBuilder::G4FTFPNeutronBuilder(), G4FTFPPiKBuilder::G4FTFPPiKBuilder(), G4FTFPPionBuilder::G4FTFPPionBuilder(), G4FTFPProtonBuilder::G4FTFPProtonBuilder(), G4HadronicAbsorptionFritiof::G4HadronicAbsorptionFritiof(), and G4QGSPKaonBuilder::G4QGSPKaonBuilder().
Instance()
G4HadronicParameters * G4HadronicParameters::Instance (void) static
Definition at line 50 of file G4HadronicParameters.cc.
Referenced by G4BertiniElectroNuclearBuilder::Build(), G4QGSBinaryProtonBuilder::Build(), G4QGSBinaryKaonBuilder::Build(), G4QGSBinaryPionBuilder::Build(), G4QGSPLundStrFragmProtonBuilder::Build(), G4QGSBinaryPiKBuilder::Build(), G4QGSPPionBuilder::Build(), G4QGSPProtonBuilder::Build(), G4QGSPPiKBuilder::Build(), G4QGSBinaryNeutronBuilder::Build(), G4QGSPNeutronBuilder::Build(), G4CrossSectionElastic::BuildPhysicsTable(), G4CrossSectionInelastic::BuildPhysicsTable(), B03PhysicsList::ConstructHad(), DMXPhysicsList::ConstructHad(), G4IonPhysics::ConstructProcess(), G4HadronInelasticQBBC::ConstructProcess(), G4IonPhysicsPHP::ConstructProcess(), G4IonINCLXXPhysics::ConstructProcess(), G4IonQMDPhysics::ConstructProcess(), G4HadronPhysicsQGSP_BIC_AllHP::ConstructProcess(), G4HadronPhysicsQGSP_BIC_HP::ConstructProcess(), GammaRayTelIonPhysics::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), G4HadronPhysicsFTFQGSP_BERT::CreateModels(), G4HadronPhysicsFTFP_BERT_HP::ExtraConfiguration(), G4HadronPhysicsShieldingLEND::ExtraConfiguration(), G4HadronPhysicsShielding::ExtraConfiguration(), G4HadronPhysicsQGSP_BERT_HP::ExtraConfiguration(), G4HadronPhysicsINCLXX::ExtraConfiguration(), G4BGGPionElasticXS::G4BGGPionElasticXS(), G4BGGPionInelasticXS::G4BGGPionInelasticXS(), G4ChargeExchange::G4ChargeExchange(), G4DiffuseElastic::G4DiffuseElastic(), G4DiffuseElasticV2::G4DiffuseElasticV2(), G4FTFBinaryKaonBuilder::G4FTFBinaryKaonBuilder(), G4FTFBinaryNeutronBuilder::G4FTFBinaryNeutronBuilder(), G4FTFBinaryPiKBuilder::G4FTFBinaryPiKBuilder(), G4FTFBinaryPionBuilder::G4FTFBinaryPionBuilder(), G4FTFBinaryProtonBuilder::G4FTFBinaryProtonBuilder(), G4FTFPAntiBarionBuilder::G4FTFPAntiBarionBuilder(), G4FTFPKaonBuilder::G4FTFPKaonBuilder(), G4FTFPNeutronBuilder::G4FTFPNeutronBuilder(), G4FTFPPiKBuilder::G4FTFPPiKBuilder(), G4FTFPPionBuilder::G4FTFPPionBuilder(), G4FTFPProtonBuilder::G4FTFPProtonBuilder(), G4HadronElastic::G4HadronElastic(), G4HadronicAbsorptionFritiof::G4HadronicAbsorptionFritiof(), G4hhElastic::G4hhElastic(), G4HyperonFTFPBuilder::G4HyperonFTFPBuilder(), G4NeutrinoElectronCcModel::G4NeutrinoElectronCcModel(), G4NeutrinoElectronNcModel::G4NeutrinoElectronNcModel(), G4NeutronRadCapture::G4NeutronRadCapture(), G4NuclNuclDiffuseElastic::G4NuclNuclDiffuseElastic(), and G4QGSPKaonBuilder::G4QGSPKaonBuilder().
Field Documentation
fMaxEnergy
G4double G4HadronicParameters::fMaxEnergy private
Definition at line 66 of file G4HadronicParameters.hh.
Referenced by G4HadronicParameters(), and GetMaxEnergy().
sInstance
G4HadronicParameters * G4HadronicParameters::sInstance = nullptr static private
Definition at line 64 of file G4HadronicParameters.hh.
Referenced by Instance().
The documentation for this class was generated from the following files:
source/processes/hadronic/util/include/G4HadronicParameters.hh
source/processes/hadronic/util/src/G4HadronicParameters.cc