Geant4: source/global/management/src/G4Exception.cc File Reference
G4Exception.cc File Reference
#include "G4Exception.hh"
#include "G4StateManager.hh"
Functions
void G4Exception (const char *originOfException, const char *exceptionCode, G4ExceptionSeverity severity, const char *description)
void G4Exception (const char *originOfException, const char *exceptionCode, G4ExceptionSeverity severity, G4ExceptionDescription &description)
void G4Exception (const char *originOfException, const char *exceptionCode, G4ExceptionSeverity severity, G4ExceptionDescription &description, const char *comments)
Function Documentation
G4Exception() [1/3]
void G4Exception (const char * originOfException, const char * exceptionCode, G4ExceptionSeverity severity, const char * description)
Definition at line 36 of file G4Exception.cc.
Referenced by G4ITTrackHolder::_PushTrack(), HadrontherapyRBEAccumulable::Accumulate(), G4MagInt_Driver::AccurateAdvance(), G4ITTransportationManager::ActivateNavigator(), G4TransportationManager::ActivateNavigator(), G4BiasingHelper::ActivatePhysicsBiasing(), G4ProcessManager::ActivateProcess(), G4RDVCrossSectionHandler::ActiveElements(), G4VCrossSectionHandler::ActiveElements(), G4PixeCrossSectionHandler::ActiveElements(), G4ITStepProcessor::ActiveOnlyITProcess(), G4SimpleIntegration::AdaptGauss(), G4TrajectoryChargeFilter::Add(), G4SDParticleFilter::add(), G4MoleculeCounter::AddAMoleculeAtTime(), G4ElementData::AddComponent(), G4HepRepFileSceneHandler::AddCompound(), G4GMocrenFileSceneHandler::AddCompound(), G4VSceneHandler::AddCompound(), G4ESTARStopping::AddData(), G4LogicalVolume::AddDaughter(), G4ElectronOccupancy::AddElectron(), G4Material::AddElement(), G4MaterialPropertiesTable::AddEntry(), G4TessellatedSolid::AddFacet(), DicomFileMgr::AddFile(), G4ExtrudedSolid::AddGeneralPolygonFacets(), G4AttributeFilterT< T >::AddInterval(), G4TrajectoryDrawByAttribute::AddIntervalContext(), G4Element::AddIsotope(), G4BiasingHelper::AddLimiterProcess(), DicomFileMgr::AddMaterial(), G4Material::AddMaterial(), DicomFileMgr::AddMaterialDensity(), G4GDMLWrite::AddModule(), G4SDStructure::AddNewDetector(), G4RootMpiPNtupleManager::AddNtupleRow(), G4RootPNtupleManager::AddNtupleRow(), G4ParallelGeometriesLimiterProcess::AddParallelWorld(), GB02BOptrMultiParticleForceCollision::AddParticle(), G4ChannelingOptrMultiParticleChangeCrossSection::AddParticle(), GB01BOptrMultiParticleChangeCrossSection::AddParticle(), G4ExtDEDXTable::AddPhysicsVector(), G4IonStoppingData::AddPhysicsVector(), G4tgrVolume::AddPlace(), G4tgrVolume::AddPlaceReplica(), G4GMocrenFileSceneHandler::AddPrimitive(), G4HepRepSceneHandler::AddPrimitive(), G4NuclearLevelData::AddPrivateData(), G4ProcessManager::AddProcess(), G4ProcessPlacer::AddProcessAs(), G4IonTable::AddProcessManager(), G4VUserPhysicsList::AddProcessManager(), ExTGRCRegionCutsMgr::AddRegionCuts(), ExTGRCRegionCutsMgr::AddRegionData(), G4tgrRotationMatrixFactory::AddRotMatrix(), G4ParticleChangeForRadDecay::AddSecondary(), G4VParticleChange::AddSecondary(), G4GMocrenFileSceneHandler::AddSolid(), G4GDMLWriteSolids::AddSolid(), G4Colour::AddToMap(), G4PhysicsListHelper::AddTransportation(), G4MolecularConfiguration::G4MolecularConfigurationManager::AddUserID(), G4AttributeFilterT< T >::AddValue(), G4TrajectoryDrawByAttribute::AddValueContext(), G4ParticleHPFinalState::adjust_final_state(), G4VIntersectionLocator::AdjustmentOfFoundIntersection(), G4NavigationLogger::AlongComputeStepLog(), G4BiasingProcessInterface::AlongStepDoIt(), G4Transportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4ITTransportation::AlongStepGetPhysicalInteractionLength(), G4ModelCmdSetStepPtsType< M >::Apply(), G4ModelCmdSetAuxPtsType< M >::Apply(), G4ModelCmdSetStepPtsSizeType< M >::Apply(), G4ModelCmdSetAuxPtsSizeType< M >::Apply(), G4ModelCmdSetStepPtsFillStyle< M >::Apply(), G4ModelCmdSetAuxPtsFillStyle< M >::Apply(), G4UImanager::ApplyCommand(), G4BOptnForceFreeFlight::ApplyFinalStateBiasing(), G4BinaryLightIonReaction::ApplyYourself(), G4ParticleHPFissionFS::ApplyYourself(), G4PreCompoundModel::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4ChordFinder::ApproxCurvePointV(), G4CutTubs::ApproxSurfaceNormal(), G4Torus::ApproxSurfaceNormal(), G4Tubs::ApproxSurfaceNormal(), G4Cons::ApproxSurfaceNormal(), G4Sphere::ApproxSurfaceNormal(), G4SPSEneDistribution::ArbEnergyHistoFile(), G4SPSEneDistribution::ArbInterpolate(), G4tgrUtils::AreWordsEquivalent(), G4GDMLReadStructure::AssemblyRead(), G4GDMLReadMaterials::AtomRead(), G4HadronStoppingProcess::AtRestDoIt(), G4VBiasingOperator::AttachTo(), G4RDAugerData::AugerShellId(), G4AugerData::AugerShellId(), G4AugerTransition::AugerTransitionEnergies(), G4AugerTransition::AugerTransitionProbabilities(), G4GDMLRead::AuxiliaryRead(), G4GDMLReadStructure::AxisRead(), B2bChamberParameterisation::B2bChamberParameterisation(), G4ReplicaNavigation::BackLocate(), G4VisManager::BeginDraw(), G4VisManager::BeginDraw2D(), G4VSceneHandler::BeginPrimitives(), G4VSceneHandler::BeginPrimitives2D(), G4HadPhaseSpaceKopylov::BetaKopylov(), G4HadronicProcess::BiasCrossSectionByFactor(), G4GDMLReadSolids::BooleanRead(), G4GDMLWriteSolids::BooleanWrite(), G4GDMLWriteStructure::BorderSurfaceCache(), G4GDMLReadStructure::BorderSurfaceRead(), G4ScaledSolid::BoundingLimits(), G4ReflectedSolid::BoundingLimits(), G4Box::BoundingLimits(), G4DisplacedSolid::BoundingLimits(), G4Tet::BoundingLimits(), G4Orb::BoundingLimits(), G4UnionSolid::BoundingLimits(), G4IntersectionSolid::BoundingLimits(), G4SubtractionSolid::BoundingLimits(), G4Ellipsoid::BoundingLimits(), G4GenericPolycone::BoundingLimits(), G4Hype::BoundingLimits(), G4CutTubs::BoundingLimits(), G4Paraboloid::BoundingLimits(), G4TwistedTubs::BoundingLimits(), G4Polycone::BoundingLimits(), G4VSolid::BoundingLimits(), G4Polyhedra::BoundingLimits(), G4EllipticalCone::BoundingLimits(), G4Trd::BoundingLimits(), G4GenericTrap::BoundingLimits(), G4Para::BoundingLimits(), G4Tubs::BoundingLimits(), G4Cons::BoundingLimits(), G4Torus::BoundingLimits(), G4ExtrudedSolid::BoundingLimits(), G4Sphere::BoundingLimits(), G4TessellatedSolid::BoundingLimits(), G4Trap::BoundingLimits(), G4GDMLReadParamvol::Box_dimensionsRead(), G4GDMLReadSolids::BoxRead(), G4ExcitationHandler::BreakItUp(), G4PhysicsBuilderInterface::Build(), G4LENDBertiniGammaElectroNuclearBuilder::Build(), DicomFilePET::BuildActivities(), G4tgrPlaceDivRep::BuildAxis(), G4PhantomHeadBuilder::BuildBrain(), G4PhantomBuilder::BuildBrain(), G4ErrorTrajState::BuildCharge(), G4mpi::buildCommunicationMap(), G4SmartVoxelHeader::BuildConsumedNodes(), G4PixeCrossSectionHandler::BuildCrossSectionsForMaterials(), G4PenelopeIonisationXSHandler::BuildDeltaTable(), G4PixeCrossSectionHandler::BuildForMaterials(), G4PenelopeRayleighModel::BuildFormFactorTable(), G4tgbElement::BuildG4ElementFromIsotopes(), G4tgbMaterialMixtureByVolume::BuildG4Material(), G4tgbMaterialMixtureByWeight::BuildG4Material(), G4tgbMaterialMixtureByNoAtoms::BuildG4Material(), G4tgbRotationMatrix::BuildG4RotMatrix(), G4PhantomHeadBuilder::BuildHead(), G4PhantomBuilder::BuildHead(), G4PhantomBuilder::BuildHeart(), G4PhantomBuilder::BuildLeftAdrenal(), G4PhantomBuilder::BuildLeftArmBone(), G4FemaleBuilder::BuildLeftBreast(), G4PhantomBuilder::BuildLeftClavicle(), G4PhantomBuilder::BuildLeftKidney(), G4PhantomBuilder::BuildLeftLeg(), G4PhantomBuilder::BuildLeftLegBone(), G4PhantomBuilder::BuildLeftLung(), G4CustomFemaleBuilder::BuildLeftOvary(), G4FemaleBuilder::BuildLeftOvary(), G4PhantomBuilder::BuildLeftScapula(), G4MaleBuilder::BuildLeftTeste(), G4PhantomBuilder::BuildLiver(), G4PhantomBuilder::BuildLowerLargeIntestine(), G4MaleBuilder::BuildMaleGenitalia(), G4NistMaterialBuilder::BuildMaterial(), DicomFileCT::BuildMaterials(), G4NistManager::BuildMaterialWithNewDensity(), G4RDVCrossSectionHandler::BuildMeanFreePathForMaterials(), G4VCrossSectionHandler::BuildMeanFreePathForMaterials(), G4PhantomBuilder::BuildMiddleLowerSpine(), G4SmartVoxelHeader::BuildNodes(), G4GeometryManager::BuildOptimisations(), G4PenelopeOscillatorManager::BuildOscillatorTable(), G4PhantomBuilder::BuildPancreas(), G4PhantomBuilder::BuildPelvis(), G4VLEPTSModel::BuildPhysicsTable(), G4NeutronElasticXS::BuildPhysicsTable(), G4NeutronCaptureXS::BuildPhysicsTable(), G4NeutronInelasticXS::BuildPhysicsTable(), G4ParticleInelasticXS::BuildPhysicsTable(), G4VUserChemistryList::BuildPhysicsTable(), G4VXTRenergyLoss::BuildPhysicsTable(), G4HadronicProcess::BuildPhysicsTable(), G4VUserPhysicsList::BuildPhysicsTable(), G4IonStoppingData::BuildPhysicsVector(), ExTGRCRegionCutsMgr::BuildProductionCuts(), G4SmartVoxelHeader::BuildReplicaVoxels(), G4PhantomBuilder::BuildRibCage(), G4PhantomBuilder::BuildRightAdrenal(), G4PhantomBuilder::BuildRightArmBone(), G4FemaleBuilder::BuildRightBreast(), G4PhantomBuilder::BuildRightClavicle(), G4PhantomBuilder::BuildRightKidney(), G4PhantomBuilder::BuildRightLeg(), G4PhantomBuilder::BuildRightLegBone(), G4PhantomBuilder::BuildRightLung(), G4CustomFemaleBuilder::BuildRightOvary(), G4FemaleBuilder::BuildRightOvary(), G4PhantomBuilder::BuildRightScapula(), G4MaleBuilder::BuildRightTeste(), G4PenelopeBremsstrahlungFS::BuildScaledXSTable(), G4PhantomHeadBuilder::BuildSkull(), G4PhantomBuilder::BuildSkull(), G4PhantomBuilder::BuildSmallIntestine(), G4tgbVolume::BuildSolidForDivision(), G4PhantomBuilder::BuildSpleen(), G4PhantomBuilder::BuildStomach(), DicomFileCT::BuildStructureIDs(), BuildTarget(), G4PhantomBuilder::BuildThymus(), G4PhantomBuilder::BuildThyroid(), G4Molecule::BuildTrack(), G4PhantomBuilder::BuildTrunk(), G4PhantomBuilder::BuildUpperLargeIntestine(), G4PhantomBuilder::BuildUpperSpine(), G4PhantomBuilder::BuildUrinaryBladder(), G4CustomFemaleBuilder::BuildUterus(), G4FemaleBuilder::BuildUterus(), G4CustomFemaleBuilder::BuildVoxelLeftBreast(), G4CustomFemaleBuilder::BuildVoxelRightBreast(), G4SmartVoxelHeader::BuildVoxelsWithinLimits(), G4PenelopeIonisationXSHandler::BuildXSTable(), G4PenelopeBremsstrahlungModel::BuildXSTable(), G4QuasiElRatios::CalcElTot(), G4HadronCrossSections::CalcScatteringCrossSections(), G4ParticleDefinition::CalculateAnomaly(), G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), G4MuonVDNuclearModel::CalculateEMVertex(), G4GenericPolycone::CalculateExtent(), G4Polycone::CalculateExtent(), G4Polyhedra::CalculateExtent(), G4ExtrudedSolid::CalculateExtent(), G4Scene::CalculateExtent(), G4MaterialPropertiesTable::CalculateGROUPVEL(), G4ITModelProcessor::CalculateMinTimeStep(), G4SmartVoxelHeader::CalculateQuality(), G4ITModelProcessor::CalculateTimeStep(), G4PAIySection::CallError(), G4PAIxSection::CallError(), G4DNAMolecularReactionTable::CanReactWith(), G4RPGAntiProtonInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4ViewParameters::CatmullRomCubicSplineInterpolation(), CCalDetector::CCalDetector(), CCalGeometryConfiguration::CCalGeometryConfiguration(), CCalRotationMatrixFactory::CCalRotationMatrixFactory(), CCalSensitiveConfiguration::CCalSensitiveConfiguration(), G4ChebyshevApproximation::ChebyshevEvaluation(), G4DNAMoleculeEncounterStepper::CheckAndRecordResults(), G4VIntersectionLocator::CheckAndReEstimateEndpoint(), G4NavigationLogger::CheckAndReportBadNormal(), G4PVDivision::CheckAndSetParameters(), G4ReplicatedSlice::CheckAndSetParameters(), G4PVReplica::CheckAndSetParameters(), G4VPrimitiveScorer::CheckAndSetUnit(), G4BoundingEnvelope::CheckBoundingBox(), G4BoundingEnvelope::CheckBoundingPolygons(), DicomVFileImage::CheckConsistency(), DicomFileCT_NOdcmrt::CheckConsistency(), DicomPhantomZSliceHeader::CheckConsistency(), G4PartialPhantomParameterisation::CheckCopyNo(), G4PhantomParameterisation::CheckCopyNo(), DicomFilePlan::CheckData0(), G4MolecularDissociationTable::CheckDataConsistency(), G4NavigationLogger::CheckDaughterEntryPoint(), G4PrimaryTransformer::CheckDynamicParticle(), G4Analysis::CheckEdges(), G4MolecularConfiguration::CheckElectronOccupancy(), DicomHandler::CheckFileFormat(), G4PenelopeOscillatorManager::CheckForTablesCreated(), G4ErrorPropagator::CheckIfLastStep(), G4tgrParameterMgr::CheckIfNewParameter(), G4ParticleChangeForGamma::CheckIt(), G4ParticleChangeForMSC::CheckIt(), G4ParticleChangeForLoss::CheckIt(), G4ParticleChangeForDecay::CheckIt(), G4ParticleChange::CheckIt(), G4VParticleChange::CheckIt(), G4FastStep::CheckIt(), G4MultiNavigator::CheckMassWorld(), G4ITMultiNavigator::CheckMassWorld(), G4ProductionCutsTable::CheckMaterialCutsCoupleInfo(), G4ProductionCutsTable::CheckMaterialInfo(), DetectorConstruction::CheckMaterials(), G4Analysis::CheckMinMax(), G4AccumulableManager::CheckName(), G4Analysis::CheckName(), G4ITNavigator2::CheckNavigatorState(), G4Analysis::CheckNbins(), DicomFileMgr::CheckNColumns(), G4VDivisionParameterisation::CheckNDivAndWidth(), G4tgbPlaceParameterisation::CheckNExtraData(), G4tgbVolume::CheckNoSolidParams(), G4VDivisionParameterisation::CheckOffset(), G4GenericTrap::CheckOrder(), G4ProcessManager::CheckOrderingParameters(), G4PVParameterised::CheckOverlaps(), G4PVPlacement::CheckOverlaps(), G4EllipticalTube::CheckParameters(), G4Trd::CheckParameters(), G4Para::CheckParameters(), G4Trap::CheckParameters(), G4ParameterisationPolyconeRho::CheckParametersValidity(), G4ParameterisationPolyhedraRho::CheckParametersValidity(), G4ParameterisationTrdY::CheckParametersValidity(), G4ParameterisationPolyhedraPhi::CheckParametersValidity(), G4ParameterisationPolyconeZ::CheckParametersValidity(), G4ParameterisationPolyhedraZ::CheckParametersValidity(), G4PhysicsListHelper::CheckParticleList(), G4ParticleTable::CheckReadiness(), G4HadronicProcess::CheckResult(), G4ReflectionFactory::CheckScale(), G4VParticleChange::CheckSecondary(), G4PhantomParameterisation::CheckVoxelsFillContainer(), G4tgrUtils::CheckWLsize(), G4QuasiElRatios::ChExer(), G4Fancy3DNucleus::ChooseFermiMomenta(), G4Fancy3DNucleus::ChoosePositions(), G4IonTable::clear(), G4Region::ClearFastSimulationManager(), G4PenelopeBremsstrahlungFS::ClearTables(), G4PenelopeBremsstrahlungModel::ClearTables(), G4Clebsch::ClebschGordanCoeff(), G4Field::Clone(), G4VSensitiveDetector::Clone(), G4VSolid::Clone(), G4VUserDetectorConstruction::CloneF(), G4GeometryWorkspace::CloneParameterisedSolids(), G4GeometryWorkspace::CloneReplicaSolid(), G4VUserDetectorConstruction::CloneSD(), G4PlotManager::CloseFile(), G4RootMpiAnalysisManager::CloseFileImpl(), G4Hdf5AnalysisManager::CloseFileImpl(), G4XmlAnalysisManager::CloseFileImpl(), G4CsvAnalysisManager::CloseFileImpl(), G4RootAnalysisManager::CloseFileImpl(), G4GDMLReadMaterials::CompositeRead(), G4PenelopeGammaConversionModel::ComputeCrossSectionPerAtom(), G4LivermoreIonisationModel::ComputeCrossSectionPerAtom(), G4PenelopeRayleighModel::ComputeCrossSectionPerAtom(), G4PenelopePhotoElectricModel::ComputeCrossSectionPerAtom(), G4WentzelVIRelModel::ComputeCrossSectionPerAtom(), G4WentzelVIModel::ComputeCrossSectionPerAtom(), G4PenelopeIonisationModel::ComputeDEDXPerVolume(), G4VTwistedFaceted::ComputeDimensions(), UltraFresnelLensParameterisation::ComputeDimensions(), G4ScaledSolid::ComputeDimensions(), G4ReflectedSolid::ComputeDimensions(), G4DisplacedSolid::ComputeDimensions(), G4TwistedTubs::ComputeDimensions(), G4VSolid::ComputeDimensions(), G4Analysis::ComputeEdges(), G4ILawTruncatedExp::ComputeEffectiveCrossSectionAt(), G4InteractionLawPhysical::ComputeEffectiveCrossSectionAt(), G4GenericTrap::ComputeIsTwisted(), G4ILawTruncatedExp::ComputeNonInteractionProbabilityAt(), G4InteractionLawPhysical::ComputeNonInteractionProbabilityAt(), G4ILawCommonTruncatedExp::ComputeNonInteractionProbabilityAt(), G4VoxelSafety::ComputeSafety(), G4VoxelNavigation::ComputeSafety(), G4Navigator::ComputeSafety(), G4ITNavigator1::ComputeSafety(), G4ITNavigator2::ComputeSafety(), G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), G4ePolarizedIonisation::ComputeSaturationFactor(), G4PolarizedCompton::ComputeSaturationFactor(), G4PathFinder::ComputeStep(), G4PropagatorInField::ComputeStep(), G4ParameterisedNavigation::ComputeStep(), G4Navigator::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4ITNavigator1::ComputeStep(), G4DNABrownianTransportation::ComputeStep(), G4ITNavigator2::ComputeStep(), G4ITPathFinder::ComputeStep(), G4Navigator::ComputeStepLog(), G4ITNavigator1::ComputeStepLog(), G4ITNavigator2::ComputeStepLog(), G4ITModelProcessor::ComputeTrackReaction(), UltraFresnelLensParameterisation::ComputeTransformation(), G4ParameterisationBoxX::ComputeTransformation(), G4ParameterisationTrdX::ComputeTransformation(), G4ParameterisationBoxY::ComputeTransformation(), G4ParameterisationTrdY::ComputeTransformation(), G4ParameterisationBoxZ::ComputeTransformation(), G4ParameterisationTrdZ::ComputeTransformation(), G4PSDoseDeposit::ComputeVolume(), G4PSPassageCellFlux::ComputeVolume(), G4PSCellFlux::ComputeVolume(), G4GDMLReadParamvol::Cone_dimensionsRead(), G4GDMLReadSolids::ConeRead(), G4ImportanceConfigurator::Configure(), G4GDMLReadDefine::ConstantRead(), HadrontherapyDetectorROGeometry::Construct(), WLSDetectorConstruction::ConstructFiber(), G4tgbVolume::ConstructG4LogVol(), G4tgbVolume::ConstructG4PhysVol(), DicomPartialDetectorConstruction::ConstructPhantom(), ExUCNExtraPhysics::ConstructProcess(), WLSExtraPhysics::ConstructProcess(), WLSOpticalPhysics::ConstructProcess(), G4ErrorPhysicsList::ConstructProcess(), G4OpticalPhysics::ConstructProcess(), ExTGDetectorConstructionWithSD::ConstructSDandField(), ExUCNExtraPhysics::ConstructUCN(), DetectorConstruction::ConstructWorld(), DicomFileMgr::Convert(), G4SPSEneDistribution::ConvertEPNToEnergy(), G4Radioactivation::ConvolveSourceTimeProfile(), G4RadioactiveDecay::ConvolveSourceTimeProfile(), G4AngularDistributionNP::CosTheta(), G4AngularDistributionPP::CosTheta(), G4CreatorFactoryT< T, Identifier, Creator >::Create(), G4ReduciblePolygon::Create(), G4GenericPolycone::Create(), G4Polycone::Create(), G4Polyhedra::Create(), G4DNASolvationModelFactory::Create(), G4ParticleHPThermalScattering::create_E_isoAng_from_energy(), create_pool_align(), G4PhysicalVolumeModel::CreateCurrentAttValues(), G4Hdf5FileManager::CreateDirectory(), G4RootFileManager::CreateHistoDirectory(), G4XmlFileManager::CreateHnFile(), B01DetectorConstruction::CreateImportanceStore(), B02ImportanceDetectorConstruction::CreateImportanceStore(), G4IonTable::CreateIon(), G4MolecularConfiguration::CreateMolecularConfiguration(), G4RootMainNtupleManager::CreateNtuple(), G4RootFileManager::CreateNtupleDirectory(), G4CsvFileManager::CreateNtupleFile(), G4XmlFileManager::CreateNtupleFile(), G4RootMainNtupleManager::CreateNtuplesFromBooking(), G4GenericPolycone::CreatePolyhedron(), G4ScaledSolid::CreatePolyhedron(), G4ReflectedSolid::CreatePolyhedron(), G4Polyhedra::CreatePolyhedron(), G4DisplacedSolid::CreatePolyhedron(), G4PVDivisionFactory::CreatePVDivision(), G4ReflectionFactory::CreateReflectedLV(), G4tgrVolumeMgr::CreateSolid(), G3Division::CreateSolid(), G4GeomSplitter< T >::CreateSubInstance(), G4Hdf5NtupleManager::CreateTNtuple(), G4RootNtupleManager::CreateTNtuple(), G4ScoreSplittingProcess::CreateTouchableForSubStep(), G4MultiNavigator::CreateTouchableHistoryHandle(), G4ITMultiNavigator::CreateTouchableHistoryHandle(), B01DetectorConstruction::CreateWeightWindowStore(), B02ImportanceDetectorConstruction::CreateWeightWindowStore(), G4TWorkspacePool< T >::CreateWorkspace(), G4PenelopeIonisationCrossSection::CrossSection(), G4DNARuddIonisationExtendedModel::CrossSectionPerVolume(), G4DNARuddIonisationModel::CrossSectionPerVolume(), G4DNABornIonisationModel1::CrossSectionPerVolume(), G4DNAIonElasticModel::CrossSectionPerVolume(), G4MicroElecElasticModel::CrossSectionPerVolume(), G4MuElecElasticModel::CrossSectionPerVolume(), G4DNAEmfietzoglouExcitationModel::CrossSectionPerVolume(), G4DNACPA100ElasticModel::CrossSectionPerVolume(), G4DNAEmfietzoglouIonisationModel::CrossSectionPerVolume(), G4DNACPA100ExcitationModel::CrossSectionPerVolume(), G4DNACPA100IonisationModel::CrossSectionPerVolume(), G4MicroElecInelasticModel::CrossSectionPerVolume(), G4MuElecInelasticModel::CrossSectionPerVolume(), G4PenelopeIonisationModel::CrossSectionPerVolume(), G4DataInterpolation::CubicSplineInterpolation(), G4GDMLReadSolids::CutTubeRead(), G4MuPairProductionModel::DataCorrupted(), G4ITTransportationManager::DeActivateNavigator(), G4TransportationManager::DeActivateNavigator(), G4KineticTrack::Decay(), G4ECDecay::DecayIt(), G4Decay::DecayIt(), G4DNAMolecularDissociation::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4GenericMessenger::DeclareMethodWithUnit(), G4PreCompoundModel::DeExcite(), G4GDMLEvaluator::DefineConstant(), G4GDMLEvaluator::DefineMatrix(), G4SteppingManager::DefinePhysicalStepLength(), G4GDMLReadDefine::DefineRead(), G4GDMLEvaluator::DefineVariable(), B2aDetectorConstruction::DefineVolumes(), B4cDetectorConstruction::DefineVolumes(), B4dDetectorConstruction::DefineVolumes(), B4DetectorConstruction::DefineVolumes(), G4RunManagerKernel::DefineWorldVolume(), G4OpticalPhysicsMessenger::Deprecated(), G4ITTransportationManager::DeRegisterNavigator(), G4TransportationManager::DeRegisterNavigator(), G4ITTransportationManager::DeRegisterWorld(), G4TransportationManager::DeRegisterWorld(), G4PhysicalVolumeModel::DescribeAndDescend(), G4LogicalVolumeModel::DescribeSolid(), G4NullModel::DescribeYourselfTo(), G4PhysicalVolumeModel::DescribeYourselfTo(), G4CacheReference< value_type >::Destroy(), G4QGSParticipants::DeterminePartonMomenta(), G4PolyPhiFace::Diagnose(), DicomPhantomZSliceHeader::DicomPhantomZSliceHeader(), G4OpBoundaryProcess::DielectricDichroic(), G4LundStringFragmentation::Diquark_AntiDiquark_aboveThreshold_lastSplitting(), G4VTwistSurface::DistanceToBoundary(), G4VTwistedFaceted::DistanceToIn(), G4IntersectionSolid::DistanceToIn(), G4SubtractionSolid::DistanceToIn(), G4Paraboloid::DistanceToIn(), G4TwistedTubs::DistanceToIn(), G4TessellatedSolid::DistanceToIn(), G4TessellatedSolid::DistanceToInNoVoxels(), G4EllipticalTube::DistanceToOut(), G4Ellipsoid::DistanceToOut(), G4Tet::DistanceToOut(), G4VTwistedFaceted::DistanceToOut(), G4Box::DistanceToOut(), G4Orb::DistanceToOut(), G4GenericTrap::DistanceToOut(), G4Paraboloid::DistanceToOut(), G4CutTubs::DistanceToOut(), G4TwistedTubs::DistanceToOut(), G4EllipticalCone::DistanceToOut(), G4ReplicaNavigation::DistanceToOut(), G4Trd::DistanceToOut(), G4Tubs::DistanceToOut(), G4Torus::DistanceToOut(), G4Cons::DistanceToOut(), G4Para::DistanceToOut(), G4Sphere::DistanceToOut(), G4TessellatedSolid::DistanceToOut(), G4Trap::DistanceToOut(), G4TessellatedSolid::DistanceToOutNoVoxels(), G4TwistTubsSide::DistanceToPlane(), G4TwistBoxSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), G4GDMLReadStructure::DivisionvolRead(), G4RadioactiveDecayBase::DoDecay(), G4RadioactiveDecay::DoDecay(), G4ITStepProcessor::DoDefinePhysicalStepLength(), G4WorkerRunManager::DoEventLoop(), G4SamplingPostStepAction::DoIt(), G4ITStepProcessor::DoIt(), G4PathFinder::DoNextCurvedStep(), G4ITPathFinder::DoNextCurvedStep(), G4EventManager::DoProcessing(), G4ITStepProcessor::DoStepping(), G4WorkerRunManager::DoWork(), G4TrajectoryDrawByAttribute::Draw(), G4TrajectoryDrawByEncounteredVolume::Draw(), G4BlineEventAction::DrawFieldLines(), G4VisManager::DrawT(), G4VisManager::DrawT2D(), G4DrawVoxels::DrawVoxels(), G4GDMLReadMaterials::DRead(), G4ExactHelixStepper::DumbStepper(), G4tgrFileIn::DumpException(), G4tgbGeometryDumper::DumpPVReplica(), G4tgbGeometryDumper::DumpSolid(), G4MaterialPropertiesTable::DumpTable(), DicomPhantomZSliceHeader::DumpToFile(), G4GDMLReadSolids::ElconeRead(), G4GDMLReadMaterials::ElementRead(), G4GDMLReadParamvol::Ellipsoid_dimensionsRead(), G4GDMLReadSolids::EllipsoidRead(), G4GDMLReadSolids::EltubeRead(), ScoreSpecies::EndOfEvent(), GammaRayTelEventAction::EndOfEventAction(), DicomRunAction::EndOfRunAction(), Dicom2RunAction::EndOfRunAction(), TSRunAction::EndOfRunAction(), G4VSceneHandler::EndPrimitives(), G4VSceneHandler::EndPrimitives2D(), G4BOptrForceCollision::EndTracking(), G4Scheduler::EndTracking(), G4ImportanceAlgorithm::Error(), G4WeightWindowStore::Error(), G4IStore::Error(), G4ErrorMatrix::error(), G4tgrMaterialFactory::ErrorAlreadyExists(), G4PVDivision::ErrorInAxis(), G4ReplicatedSlice::ErrorInAxis(), G4BrentLocator::EstimateIntersectionPoint(), G4MultiLevelLocator::EstimateIntersectionPoint(), G4SimpleLocator::EstimateIntersectionPoint(), G4CellScoreComposer::EstimatorCalculation(), G4TrajectoryEncounteredVolumeFilter::Evaluate(), G4AttributeFilterT< T >::Evaluate(), G4GDMLEvaluator::Evaluate(), G4GDMLEvaluator::EvaluateInteger(), G4FPYSamplingOps::EvaluateWattConstants(), G3Division::Exception(), G4MPImanager::ExecuteBeamOnThread(), ExN02ChamberParameterisation::ExN02ChamberParameterisation(), ExP01ChamberParameterisation::ExP01ChamberParameterisation(), G4SPSEneDistribution::ExpInterpolation(), G4GDMLReadDefine::ExpressionRead(), G4DNASancheExcitationModel::ExtendLowEnergyLimit(), G03ColorReader::ExtensionRead(), G4GDMLRead::ExtensionRead(), ExTGRCRegionData::ExTGRCRegionData(), F04PhysicsList::F04PhysicsList(), G4STRead::FacetRead(), G4DataInterpolation::FastCubicSpline(), G4QuasiElRatios::FetchElTot(), G4GDMLReadStructure::FileRead(), G4VDecayChannel::FillDaughters(), G4RootMpiPNtupleManager::FillNtupleTColumn(), G4RootPNtupleManager::FillNtupleTColumn(), G4VDecayChannel::FillParent(), G4ParticleDefinition::FillQuarkContents(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), G4EmCalculator::FindCouple(), G4tgbVolumeMgr::FindG4LogVol(), G4tgbVolumeMgr::FindG4PhysVol(), G4tgbMaterialMgr::FindG4tgbElement(), G4tgbMaterialMgr::FindG4tgbIsotope(), G4tgbMaterialMgr::FindG4tgbMaterial(), G4IonTable::FindIon(), CCalMaterialFactory::findMaterial(), G4tgbMaterialMgr::FindOrBuildG4Element(), G4tgbMaterialMgr::FindOrBuildG4Material(), G4tgbRotationMatrixMgr::FindOrBuildTgbRotMatrix(), G4tgbVolume::FindOrConstructG4Solid(), G4tgrParameterMgr::FindParameter(), G4DNASmoluchowskiReactionModel::FindReaction(), G4ITModelProcessor::FindReaction(), G4PenelopeIonisationCrossSection::FindShellIDIndex(), G4tgrVolumeMgr::FindSolid(), G4tgbGeometryDumper::FindSolidName(), G4ITStepProcessor::FindTransportationStep(), G4Scheduler::FindUserPreDefinedTimeStep(), G4CompositeDataSet::FindValue(), G4RDCompositeEMDataSet::FindValue(), G4CompositeEMDataSet::FindValue(), G4DataSet::FindValue(), G4RDEMDataSet::FindValue(), G4tgrLineProcessor::FindVolume(), G4tgrVolumeMgr::FindVolume(), G4tgbVolumeMgr::FindVolume(), G4tgrVolumeMgr::FindVolumes(), G4CsvNtupleManager::FinishTNtuple(), G4GDMLReadMaterials::FractionRead(), G4FastTrack::FRecordsAffineTransformation(), G4MicroElecCrossSectionDataSet::FullFileName(), G4MuElecCrossSectionDataSet::FullFileName(), G4RDShellEMDataSet::FullFileName(), G4DataSet::FullFileName(), G4RDEMDataSet::FullFileName(), G4ShellEMDataSet::FullFileName(), G4PixeShellDataSet::FullFileName(), G4DNACrossSectionDataSet::FullFileName(), G4CrossSectionDataSet::FullFileName(), G4EMDataSet::FullFileName(), G02ChamberParameterisation::G02ChamberParameterisation(), G3toG4BuildLVTree(), G3toG4BuildPVTree(), G3toG4MANY(), G4AccumulableManager::G4AccumulableManager(), G4alphaIonisation::G4alphaIonisation(), G4AssemblyVolume::G4AssemblyVolume(), G4AxesModel::G4AxesModel(), G4BestUnit::G4BestUnit(), G4BOptrForceCollision::G4BOptrForceCollision(), G4Box::G4Box(), G4ChannelingOptrChangeCrossSection::G4ChannelingOptrChangeCrossSection(), G4ChebyshevApproximation::G4ChebyshevApproximation(), G4ChordFinder::G4ChordFinder(), G4CompositeDataSet::G4CompositeDataSet(), G4CompositeEMDataSet::G4CompositeEMDataSet(), G4Cons::G4Cons(), G4ConstRK4::G4ConstRK4(), G4CrossSectionFactoryRegistry::G4CrossSectionFactoryRegistry(), G4CsvAnalysisManager::G4CsvAnalysisManager(), G4CsvAnalysisReader::G4CsvAnalysisReader(), G4CutTubs::G4CutTubs(), G4DataQuestionaire::G4DataQuestionaire(), G4DataSet::G4DataSet(), G4ecpssrBaseKxsModel::G4ecpssrBaseKxsModel(), G4ecpssrBaseLixsModel::G4ecpssrBaseLixsModel(), G4Element::G4Element(), G4Ellipsoid::G4Ellipsoid(), G4EllipticalCone::G4EllipticalCone(), G4EMDataSet::G4EMDataSet(), G4ErrorRunManagerHelper::G4ErrorRunManagerHelper(), G4ErrorTrackLengthTarget::G4ErrorTrackLengthTarget(), G4EventManager::G4EventManager(), G4Exception(), G4ExtrudedSolid::G4ExtrudedSolid(), G4fissionEvent::G4fissionerr(), G4ForwardXrayTR::G4ForwardXrayTR(), G4FTFParticipants::G4FTFParticipants(), G4GaussHermiteQ::G4GaussHermiteQ(), G4GaussJacobiQ::G4GaussJacobiQ(), G4GaussLaguerreQ::G4GaussLaguerreQ(), G4GaussLegendreQ::G4GaussLegendreQ(), G4GDMLMatrix::G4GDMLMatrix(), G4GenericTrap::G4GenericTrap(), G4GetDataEnv(), G4FissionProductYieldDist::G4GetFission(), G4GMocrenFileSceneHandler::G4GMocrenFileSceneHandler(), G4GMocrenFileViewer::G4GMocrenFileViewer(), G4gsbool(), G4gsdvn(), G4gsdvn2(), G4gsdvt(), G4gsdvt2(), G4gsmixt(), G4gspos(), G4gsposp(), G4gsrotm(), G4gsvolu(), G4HadronicException::G4HadronicException(), G4Hdf5AnalysisManager::G4Hdf5AnalysisManager(), G4Hdf5AnalysisReader::G4Hdf5AnalysisReader(), G4HEPEvtInterface::G4HEPEvtInterface(), G4Hype::G4Hype(), G4ImportanceProcess::G4ImportanceProcess(), G4IonisParamElm::G4IonisParamElm(), G4Isotope::G4Isotope(), G4IsotopeMagneticMomentTable::G4IsotopeMagneticMomentTable(), G4LevelReader::G4LevelReader(), G4LowEnergyCompton::G4LowEnergyCompton(), G4LowEnergyGammaConversion::G4LowEnergyGammaConversion(), G4LowEnergyPhotoElectric::G4LowEnergyPhotoElectric(), G4LowEnergyPolarizedCompton::G4LowEnergyPolarizedCompton(), G4LowEnergyRayleigh::G4LowEnergyRayleigh(), G4ModifiedMidpoint::G4ModifiedMidpoint(), G4Molecule::G4Molecule(), G4MTRunManager::G4MTRunManager(), G4MTRunManagerKernel::G4MTRunManagerKernel(), G4OpticalSurface::G4OpticalSurface(), G4Para::G4Para(), G4Paraboloid::G4Paraboloid(), G4ParameterisationConsRho::G4ParameterisationConsRho(), G4ParticleDefinition::G4ParticleDefinition(), G4ParticleInelasticXS::G4ParticleInelasticXS(), G4ParticleTable::G4ParticleTable(), G4PenelopeCrossSection::G4PenelopeCrossSection(), G4PhotoElectricAngularGeneratorPolarized::G4PhotoElectricAngularGeneratorPolarized(), G4PixeShellDataSet::G4PixeShellDataSet(), G4Polycone::G4Polycone(), G4Polyhedra::G4Polyhedra(), G4Pow::G4Pow(), G4ProcessDaughters(), G4ProcessManager::G4ProcessManager(), G4PVDivision::G4PVDivision(), G4PVParameterised::G4PVParameterised(), G4PVPlacement::G4PVPlacement(), G4PVReplica::G4PVReplica(), G4QuadrangularFacet::G4QuadrangularFacet(), G4RadioactiveDecay::G4RadioactiveDecay(), G4RadioactiveDecayBase::G4RadioactiveDecayBase(), G4RDCompositeEMDataSet::G4RDCompositeEMDataSet(), G4RDEMDataSet::G4RDEMDataSet(), G4RDPhotoElectricAngularGeneratorPolarized::G4RDPhotoElectricAngularGeneratorPolarized(), G4RDShellEMDataSet::G4RDShellEMDataSet(), G4RDVeLowEnergyLoss::G4RDVeLowEnergyLoss(), G4Region::G4Region(), G4RootAnalysisManager::G4RootAnalysisManager(), G4RootAnalysisReader::G4RootAnalysisReader(), G4RunManager::G4RunManager(), G4RunManagerKernel::G4RunManagerKernel(), G4FPYSamplingOps::G4SampleGaussian(), G4SandiaTable::G4SandiaTable(), G4SDParticleFilter::G4SDParticleFilter(), G4ShellEMDataSet::G4ShellEMDataSet(), G4Sphere::G4Sphere(), G4Tet::G4Tet(), G4tgbPlaceParamCircle::G4tgbPlaceParamCircle(), G4tgbPlaceParamLinear::G4tgbPlaceParamLinear(), G4tgbPlaceParamSquare::G4tgbPlaceParamSquare(), G4tgrRotationMatrix::G4tgrRotationMatrix(), G4tgrSolidBoolean::G4tgrSolidBoolean(), G4tgrVolumeDivision::G4tgrVolumeDivision(), G4TheMTRayTracer::G4TheMTRayTracer(), G4TransportationManager::G4TransportationManager(), G4Trap::G4Trap(), G4TriangularFacet::G4TriangularFacet(), G4Tubs::G4Tubs(), G4TwistBoxSide::G4TwistBoxSide(), G4TwistedTubs::G4TwistedTubs(), G4TwistTubsFlatSide::G4TwistTubsFlatSide(), G4TwistTubsHypeSide::G4TwistTubsHypeSide(), G4TwistTubsSide::G4TwistTubsSide(), G4UIbridge::G4UIbridge(), G4UIExecutive::G4UIExecutive(), G4UniformElectricField::G4UniformElectricField(), G4UniformMagField::G4UniformMagField(), G4UnitDefinition::G4UnitDefinition(), G4UserEventAction::G4UserEventAction(), G4UserRunAction::G4UserRunAction(), G4UserStackingAction::G4UserStackingAction(), G4UserSteppingAction::G4UserSteppingAction(), G4UserTrackingAction::G4UserTrackingAction(), G4VContinuousDiscreteProcess::G4VContinuousDiscreteProcess(), G4VContinuousProcess::G4VContinuousProcess(), G4VDiscreteProcess::G4VDiscreteProcess(), G4VisManager::G4VisManager(), G4VITDiscreteProcess::G4VITDiscreteProcess(), G4VITRestDiscreteProcess::G4VITRestDiscreteProcess(), G4VITRestProcess::G4VITRestProcess(), G4VParameterisationPolycone::G4VParameterisationPolycone(), G4VParameterisationPolyhedra::G4VParameterisationPolyhedra(), G4VReadOutGeometry::G4VReadOutGeometry(), G4VRestContinuousDiscreteProcess::G4VRestContinuousDiscreteProcess(), G4VRestContinuousProcess::G4VRestContinuousProcess(), G4VRestDiscreteProcess::G4VRestDiscreteProcess(), G4VRestProcess::G4VRestProcess(), G4VScoreNtupleWriter::G4VScoreNtupleWriter(), G4VSteppingVerbose::G4VSteppingVerbose(), G4VTwistedFaceted::G4VTwistedFaceted(), G4VUserPrimaryGeneratorAction::G4VUserPrimaryGeneratorAction(), G4VXTRenergyLoss::G4VXTRenergyLoss(), G4WeightCutOffConfigurator::G4WeightCutOffConfigurator(), G4WeightCutOffProcess::G4WeightCutOffProcess(), G4WeightWindowProcess::G4WeightWindowProcess(), G4WorkerRunManager::G4WorkerRunManager(), G4WorkerRunManagerKernel::G4WorkerRunManagerKernel(), G4XmlAnalysisManager::G4XmlAnalysisManager(), G4XmlAnalysisReader::G4XmlAnalysisReader(), G4BetaDecayCorrections::Gamma(), GB01BOptrChangeCrossSection::GB01BOptrChangeCrossSection(), GB05BOptrSplitAndKillByCrossSection::GB05BOptrSplitAndKillByCrossSection(), GB06BOptrSplitAndKillByImportance::GB06BOptrSplitAndKillByImportance(), G4SPSEneDistribution::GenArbPointEnergies(), G4AtomicDeexcitation::GenerateAuger(), G4RDAtomicDeexcitation::GenerateAuger(), G4SPSEneDistribution::GenerateBremEnergies(), G4RunManager::GenerateEvent(), G4Clebsch::GenerateIso3(), GFlashHomoShowerParameterisation::GenerateLongitudinalProfile(), GFlashSamplingShowerParameterisation::GenerateLongitudinalProfile(), G4HadPhaseSpaceGenbod::GenerateMultiBody(), G4NuclideTable::GenerateNuclide(), G4SPSPosDistribution::GenerateOne(), G4RDAtomicDeexcitation::GenerateParticles(), G4AtomicDeexcitation::GenerateParticles(), ExN04PrimaryGeneratorAction::GeneratePrimaries(), RE01PrimaryGeneratorAction::GeneratePrimaries(), H02PrimaryGeneratorAction::GeneratePrimaries(), HadrontherapyPrimaryGeneratorAction::GeneratePrimaries(), B4PrimaryGeneratorAction::GeneratePrimaries(), B1PrimaryGeneratorAction::GeneratePrimaries(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), UltraPrimaryGeneratorAction::GeneratePrimaries(), G4BlinePrimaryGeneratorAction::GeneratePrimaries(), G4ParticleGun::GeneratePrimaryVertex(), G4HEPEvtInterface::GeneratePrimaryVertex(), G4MultiRunAction::GenerateRun(), G4PrimaryTransformer::GenerateSingleTrack(), G4GDMLReadSolids::GenericPolyconeRead(), G4GDMLReadSolids::GenericPolyhedraRead(), G4GDMLReadSolids::GenTrapRead(), G4SPSEneDistribution::GenUserHistEnergies(), G4GDMLMatrix::Get(), DNA::Penetration::Terrisol1990::Get3DStdDeviation(), G4Material::GetA(), G4AccumulableManager::GetAccumulable(), G4VDecayChannel::GetAngularMomentum(), G4TwistBoxSide::GetAreaCode(), G4TwistTrapParallelSide::GetAreaCode(), G4TwistTrapAlphaSide::GetAreaCode(), G4TwistTrapFlatSide::GetAreaCode(), G4TwistTubsFlatSide::GetAreaCode(), G4TwistTubsHypeSide::GetAreaCode(), G4TwistTubsSide::GetAreaCode(), G4AssemblyStore::GetAssembly(), G4CrystalExtension::GetAtomBase(), TSRun::GetAtomicHitsMap(), G4Element::GetAtomicShell(), G4ProcessManager::GetAttribute(), G4Analysis::GetAxisTitle(), G4RootNtupleManager::GetBasketSize(), G4RootMpiPNtupleManager::GetBasketSize(), G4Nucleus::GetBiasedThermalNucleus(), G4Analysis::GetBinScheme(), G4tgrUtils::GetBool(), G4VTwistSurface::GetBoundaryAtPZ(), G4VTwistSurface::GetBoundaryAxis(), G4VTwistSurface::GetBoundaryLimit(), G4VTwistSurface::GetBoundaryParameters(), G4VTwistSurface::Boundary::GetBoundaryParameters(), G4RootAnalysisReader::GetBuffer(), G4UnitDefinition::GetCategory(), G4ChebyshevApproximation::GetChebyshevCof(), G4MultiSensitiveDetector::GetCollectionID(), G4DNAPARSER::CommandLineParser::GetCommandIfActive(), G4tgrMaterialSimple::GetComponent(), G4MoleculeTable::GetConfiguration(), G4GDMLEvaluator::GetConstant(), G4BooleanSolid::GetConstituentSolid(), G4MaterialPropertiesTable::GetConstProperty(), G4MaterialPropertiesTable::GetConstPropertyIndex(), TSRun::GetConvMap(), G4PenelopeIonisationXSHandler::GetCrossSectionTableForCouple(), G4PenelopeBremsstrahlungModel::GetCrossSectionTableForCouple(), G4EmCalculator::GetCSDARange(), G4VUserPhysicsList::GetCutValue(), G4MoleculeDefinition::GetDecayChannels(), G4Radioactivation::GetDecayTime(), G4RadioactiveDecay::GetDecayTime(), G4Radioactivation::GetDecayTimeBin(), G4RadioactiveDecay::GetDecayTimeBin(), G4Step::GetDeltaEnergy(), G4Step::GetDeltaMomentum(), G4PenelopeIonisationXSHandler::GetDensityCorrection(), G4DNAMolecularMaterial::GetDensityTableFor(), G4GMocrenIO::getDetector(), G4ErrorCylSurfaceTarget::GetDistanceFromPoint(), G4ErrorPlaneSurfaceTarget::GetDistanceFromPoint(), G4tgrUtils::GetDouble(), G4VTwistSurface::GetEdgeVisibility(), G4PenelopeBremsstrahlungFS::GetEffectiveZSquared(), G4DynamicParticle::GetElectronMass(), G4GDMLReadMaterials::GetElement(), G4HadronicProcess::GetElementCrossSection(), G4QuasiElRatios::GetElTotXS(), G4VTwistSurface::GetFace(), G4CrossSectionFactoryRegistry::GetFactory(), G4MolecularConfiguration::GetFakeParticleID(), G4ErrorPropagator::GetFinalTrajState(), G4tgrMaterialSimple::GetFraction(), G4PenelopeRayleighModel::GetFSquared(), G4Analysis::GetFunction(), G4ErrorPropagationNavigator::GetGlobalExitNormal(), G4MultiNavigator::GetGlobalExitNormal(), G4ITMultiNavigator::GetGlobalExitNormal(), G4Navigator::GetGlobalExitNormal(), G4ITNavigator1::GetGlobalExitNormal(), G4ITNavigator2::GetGlobalExitNormal(), G4VIntersectionLocator::GetGlobalSurfaceNormal(), G4XmlAnalysisReader::GetHandler(), G4VTouchable::GetHistory(), G4VTouchable::GetHistoryDepth(), HadrontherapyRBE::GetHitAlphaAndBeta(), B4dEventAction::GetHitsCollection(), B4cEventAction::GetHitsCollection(), DicomRun::GetHitsMap(), TSRun::GetHitsMap(), Dicom2Run::GetHitsVector(), G4HnManager::GetHnInformation(), G4PSEnergyDeposit3D::GetIndex(), G4PSDoseDeposit3D::GetIndex(), G4NucleiPropertiesTheoreticalTable::GetIndex(), G4NucleiPropertiesTableAME12::GetIndex(), G4VisManager::GetInstance(), G4tgrFileIn::GetInstanceOpened(), G4tgrUtils::GetInt(), G4IonTable::GetIon(), G4LENDCrossSection::GetIsoCrossSection(), G4GDMLReadMaterials::GetIsotope(), G4DNAUeharaScreenedRutherfordElasticModel::GetKillBelowThreshold(), G4DNAChampionElasticModel::GetKillBelowThreshold(), G4IonTable::GetLifeTime(), G4MultiNavigator::GetLocalExitNormal(), G4ITMultiNavigator::GetLocalExitNormal(), G4Navigator::GetLocalExitNormal(), G4ITNavigator1::GetLocalExitNormal(), G4ITNavigator2::GetLocalExitNormal(), DicomIntersectVolume::GetLogicalVolumes(), G4DNASolvationModelFactory::GetMacroDefinedModel(), G4RootFileManager::GetMainNtupleDirectory(), G4RootPNtupleManager::GetMainNtupleInFunction(), G4RootNtupleManager::GetMainNtupleManager(), G4MPImanager::GetManager(), G4ScoreLogColorMap::GetMapColor(), G4LogicalVolume::GetMass(), WLSMaterials::GetMaterial(), G4GDMLReadMaterials::GetMaterial(), DicomFileMgr::GetMaterialIndex(), DicomFileMgr::GetMaterialIndexByDensity(), G4GDMLReadDefine::GetMatrix(), G4ClippablePolygon::GetMaxPoint(), G4NeutrinoElectronProcess::GetMeanFreePath(), G4HadronicProcess::GetMeanFreePath(), G4RadioactiveDecayBase::GetMeanFreePath(), G4RadioactiveDecay::GetMeanFreePath(), G4Accumulables::GetMergeMode(), G4ClippablePolygon::GetMinPoint(), G4ITModelManager::GetModel(), G4PhysListRegistry::GetModularPhysicsList(), G4MoleculeTable::GetMoleculeDefinition(), G4PenelopeBremsstrahlungFS::GetMomentumIntegral(), G4Navigator::GetMotherToDaughterTransform(), G4ITNavigator1::GetMotherToDaughterTransform(), G4ITNavigator2::GetMotherToDaughterTransform(), G4IonTable::GetMuonicAtom(), TSRun::GetMutexHitsMap(), G4ITTransportationManager::GetNavigator(), G4TransportationManager::GetNavigator(), G4Element::GetNbOfShellElectrons(), FFPrimaryGeneratorAction::GetNeutronSourceCenter(), G4VTwistSurface::GetNode(), G4VAnalysisReader::GetNtuple(), G4RootMpiPNtupleManager::GetNtupleDescriptionInFunction(), G4RootPNtupleManager::GetNtupleDescriptionInFunction(), G4RootFileManager::GetNtupleFile(), G4RootMpiPNtupleManager::GetNtupleInFunction(), G4RootPNtupleManager::GetNtupleInFunction(), G4IonTable::GetNucleusMass(), G4PenelopePhotoElectricModel::GetNumberOfShellXS(), G4PenelopeSamplingData::GetNumberOfStoredPoints(), G4DNAMolecularMaterial::GetNumMoleculePerVolumeUnitForMaterial(), G4DNAMolecularMaterial::GetNumMolPerVolForComponentInComposite(), G4DNAMolecularMaterial::GetNumMolPerVolTableFor(), G4Analysis::GetOutput(), G4Analysis::GetOutputName(), G4DNABornExcitationModel1::GetPartialCrossSection(), G4DNABornExcitationModel2::GetPartialCrossSection(), DicomIntersectVolume::GetPhantomParam(), G4EnergySplitter::GetPhantomParam(), DicomIntersectVolume::GetPhysicalVolumes(), G4PhysicsConstructorRegistry::GetPhysicsConstructor(), G4GDMLReadStructure::GetPhysvol(), G4BooleanSolid::GetPointOnSurface(), G4VSolid::GetPointOnSurface(), G4GDMLReadDefine::GetPosition(), G4ITStepProcessor::GetProcessInfo(), G4ProcessPlacer::GetProcessManager(), G4SteppingManager::GetProcessNumber(), G4TrackingInformation::GetProcessState(), G4VHighEnergyGenerator::GetProjectileNucleus(), G4MaterialPropertiesTable::GetPropertiesCMap(), G4MaterialPropertiesTable::GetPropertiesMap(), G4MaterialPropertiesTable::GetProperty(), G4MaterialPropertiesTable::GetPropertyIndex(), G4ChipsHyperonElasticXS::GetPTables(), G4ChipsProtonElasticXS::GetPTables(), G4ChipsKaonPlusElasticXS::GetPTables(), G4ChipsPionPlusElasticXS::GetPTables(), G4ChipsAntiBaryonElasticXS::GetPTables(), G4ChipsKaonMinusElasticXS::GetPTables(), G4ChipsPionMinusElasticXS::GetPTables(), G4ChipsNeutronElasticXS::GetPTables(), G4ReflectionFactory::GetPVDivisionFactory(), G4ChipsProtonElasticXS::GetQ2max(), G4ChipsHyperonElasticXS::GetQ2max(), G4ChipsKaonPlusElasticXS::GetQ2max(), G4ChipsPionPlusElasticXS::GetQ2max(), G4ChipsKaonMinusElasticXS::GetQ2max(), G4ChipsAntiBaryonElasticXS::GetQ2max(), G4ChipsPionMinusElasticXS::GetQ2max(), G4ChipsNeutronElasticXS::GetQ2max(), G4GDMLReadDefine::GetQuantity(), G4Event::GetRandomNumberStatus(), G4Event::GetRandomNumberStatusForProcessing(), G4RunManager::GetRandomNumberStatusForThisEvent(), G4DNAMolecularReactionTable::GetReactionData(), G4Timer::GetRealElapsed(), G4DNAMolecularReactionTable::GetReativesNData(), G4RegionStore::GetRegion(), G4PartialPhantomParameterisation::GetReplicaNo(), G4PhantomParameterisation::GetReplicaNo(), G4GMocrenTouchable::GetReplicaNumber(), G4VTouchable::GetReplicaNumber(), G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable::GetReplicaNumber(), G4GDMLReadDefine::GetRotation(), G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable::GetRotation(), G4tgrUtils::GetRotationFromDirection(), UltraFresnelLens::GetSagita(), G4GDMLReadDefine::GetScale(), G4PenelopeBremsstrahlungFS::GetScaledXSTable(), G4Scintillation::GetScintillationYieldByParticleType(), G4TemplateRNGHelper< T >::GetSeed(), G4GDMLReadSetup::GetSetup(), G4PenelopePhotoElectricModel::GetShellCrossSection(), G4GMocrenIO::getShortDoseDist(), G4ChipsHyperonElasticXS::GetSlope(), G4ChipsKaonPlusElasticXS::GetSlope(), G4ChipsPionPlusElasticXS::GetSlope(), G4ChipsProtonElasticXS::GetSlope(), G4ChipsPionMinusElasticXS::GetSlope(), G4ChipsAntiBaryonElasticXS::GetSlope(), G4ChipsNeutronElasticXS::GetSlope(), G4GDMLReadSolids::GetSolid(), G4tgrSolidBoolean::GetSolid(), G4SolidStore::GetSolid(), G4VTouchable::GetSolid(), G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable::GetSolid(), G4tgbGeometryDumper::GetSolidParams(), TSRun::GetStatMap(), G4VIntersectionLocator::GetSurfaceNormal(), G4GDMLReadSolids::GetSurfaceProperty(), G4Timer::GetSystemElapsed(), G4ErrorCylSurfaceTarget::GetTangentPlane(), G4CsvRNtupleManager::GetTNtupleRow(), G4Hdf5RNtupleManager::GetTNtupleRow(), G4RootRNtupleManager::GetTNtupleRow(), G4XmlRNtupleManager::GetTNtupleRow(), G4tgbVolumeMgr::GetTopLogVol(), G4tgrVolumeMgr::GetTopVolume(), G4GMocrenIO::getTrack(), G4ITReactionChange::GetTrackA(), G4ITReactionChange::GetTrackB(), G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable::GetTranslation(), G4Timer::GetUserElapsed(), G4UnitDefinition::GetValueOf(), G4GDMLEvaluator::GetVariable(), G03ColorReader::GetVisAttribute(), G4GDMLReadStructure::GetVolume(), G4LogicalVolumeStore::GetVolume(), G4PhysicalVolumeStore::GetVolume(), G4tgrVolume::GetVolume(), G4VTouchable::GetVolume(), G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable::GetVolume(), G4EnergySplitter::GetVoxelID(), G4Analysis::GetWidth(), G4tgrFileIn::GetWordsInLine(), DicomIntersectVolume::GetWordsInString(), DicomROIContour::GetZ(), G4Material::GetZ(), HadrontherapyLet::HadrontherapyLet(), HadrontherapyMatrix::HadrontherapyMatrix(), G4VGFlashSensitiveDetector::Hit(), DicomFileMgr::Hounsfield2density(), G4GDMLReadParamvol::Hype_dimensionsRead(), G4GDMLReadSolids::HypeRead(), G4GDMLParser::ImportRegions(), G4ProcessManager::InActivateProcess(), G4ErrorPropagator::InitFreeTrajState(), G4ErrorPropagator::InitG4Track(), G4ErrorPropagatorManager::InitGeant4e(), G4DNAUeharaScreenedRutherfordElasticModel::Initialise(), G4DNAScreenedRutherfordElasticModel::Initialise(), G4DNABornExcitationModel1::Initialise(), G4DNAChampionElasticModel::Initialise(), G4DNAMeltonAttachmentModel::Initialise(), G4DNASancheExcitationModel::Initialise(), G4DNABornExcitationModel2::Initialise(), G4DNABornIonisationModel1::Initialise(), G4DNABornIonisationModel2::Initialise(), G4DNAIonElasticModel::Initialise(), G4MicroElecElasticModel::Initialise(), G4MuElecElasticModel::Initialise(), G4DNAEmfietzoglouIonisationModel::Initialise(), G4DNACPA100ElasticModel::Initialise(), G4DNATransformElectronModel::Initialise(), G4LivermoreIonisationModel::Initialise(), G4DNACPA100IonisationModel::Initialise(), G4PenelopeComptonModel::Initialise(), G4PAIPhotModel::Initialise(), G4MuElecInelasticModel::Initialise(), G4MicroElecInelasticModel::Initialise(), G4ESTARStopping::Initialise(), G4PAIModel::Initialise(), G4NeutronElasticXS::Initialise(), G4NeutronCaptureXS::Initialise(), G4NeutronInelasticXS::Initialise(), G4ParticleInelasticXS::Initialise(), G4ComponentSAIDTotalXS::Initialise(), G4EmModelManager::Initialise(), G4EmSaturation::InitialiseBirksCoefficient(), G4ElementData::InitialiseForComponent(), G4ElementData::InitialiseForElement(), G4ITSafetyHelper::InitialiseNavigator(), G4SafetyHelper::InitialiseNavigator(), G4GeometryWorkspace::InitialisePhysicalVolumes(), G4PVReplica::InitialiseWorker(), G4ITReactionChange::Initialize(), G4INCL::HFB::initialize(), Initialize(), G4Scheduler::Initialize(), G4MPImanager::Initialize(), G4Orb::Initialize(), G4FastStep::Initialize(), G4DNAMolecularMaterial::InitializeDensity(), G4PenelopeBremsstrahlungFS::InitializeEnergySampling(), G4MTRunManager::InitializeEventLoop(), G4WorkerRunManager::InitializeGeometry(), G4ErrorRunManagerHelper::InitializeGeometry(), G4RunManager::InitializeGeometry(), G4DNAChemistryManager::InitializeMaster(), G4DNAMolecularMaterial::InitializeNumMolPerVol(), G4ErrorRunManagerHelper::InitializePhysics(), G4RunManagerKernel::InitializePhysics(), G4RunManager::InitializePhysics(), G4PenelopeRayleighModel::InitializeSamplingAlgorithm(), G4ITModelProcessor::InitializeStepper(), G4DNAChemistryManager::InitializeThread(), RunAction::InitializeWorker(), G4MoleculeTable::Insert(), G4ParticleTable::Insert(), G4MolecularConfiguration::G4MolecularConfigurationManager::Insert(), G4DNAModelInterface::InsertModelInTable(), G4ReplicaNavigation::Inside(), G4TessellatedSolid::InsideNoVoxels(), G4TessellatedSolid::InsideVoxels(), G4CrossSectionFactory< T, mode >::Instantiate(), G4BogackiShampine45::InterpolateHigh(), G4ErrorCylSurfaceTarget::IntersectLocal(), G4ErrorSymMatrix::invertBunchKaufman(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePSDIP(), G4DNAPTBIonisationStructure::IonisationEnergy(), G4MolecularConfiguration::IonizeMolecule(), G4GDMLReadMaterials::IsotopeRead(), G4HadronicDeveloperParameters::issue_has_changed(), G4HadronicDeveloperParameters::issue_is_already_defined(), G4HadronicDeveloperParameters::issue_is_modified(), G4HadronicDeveloperParameters::issue_no_param(), G4HadronicDeveloperParameters::issue_non_eligible_value(), G4LevelReader::LevelManager(), G4SPSEneDistribution::LinearInterpolation(), G4FastSimulationManager::ListModels(), PDBlib::Load(), G4RDDopplerProfile::LoadBiggsP(), G4DopplerProfile::LoadBiggsP(), G4VDNAModel::LoadCrossSectionData(), G4ShellData::LoadData(), G4RDShellData::LoadData(), G4RDShellEMDataSet::LoadData(), G4MicroElecCrossSectionDataSet::LoadData(), G4MuElecCrossSectionDataSet::LoadData(), G4RDBremsstrahlungParameters::LoadData(), G4BremsstrahlungParameters::LoadData(), G4RDeIonisationParameters::LoadData(), G4eIonisationParameters::LoadData(), G4FluoData::LoadData(), G4RDFluoData::LoadData(), G4DataSet::LoadData(), G4RDEMDataSet::LoadData(), G4ShellEMDataSet::LoadData(), G4RDAugerData::LoadData(), G4AugerData::LoadData(), G4DNACrossSectionDataSet::LoadData(), G4RDVCrossSectionHandler::LoadData(), G4CrossSectionDataSet::LoadData(), G4VCrossSectionHandler::LoadData(), XrayFluoDataSet::LoadData(), G4EMDataSet::LoadData(), G4NativeScreenedCoulombCrossSection::LoadData(), G4GSPWACorrections::LoadDataElement(), G4RadioactiveDecayBase::LoadDecayTable(), G4RadioactiveDecay::LoadDecayTable(), HadrontherapyRBE::LoadLEMTable(), G4GSMottCorrection::LoadMCDataElement(), G4GoudsmitSaundersonTable::LoadMSCData(), G4MicroElecCrossSectionDataSet::LoadNonLogData(), G4MuElecCrossSectionDataSet::LoadNonLogData(), G4ShellEMDataSet::LoadNonLogData(), G4DNACrossSectionDataSet::LoadNonLogData(), G4CrossSectionDataSet::LoadNonLogData(), G4VCrossSectionHandler::LoadNonLogData(), G4EMDataSet::LoadNonLogData(), G4DopplerProfile::LoadProfile(), G4RDDopplerProfile::LoadProfile(), XrayFluoHPGeDetectorType::LoadResponseData(), XrayFluoSiLiDetectorType::LoadResponseData(), G4SBBremTable::LoadSamplingTables(), G4RDVCrossSectionHandler::LoadShellData(), G4SBBremTable::LoadSTGrid(), G4Navigator::LocateGlobalPointWithinVolume(), G4ITNavigator1::LocateGlobalPointWithinVolume(), G4ITNavigator2::LocateGlobalPointWithinVolume(), G4VIntersectionLocator::LocateGlobalPointWithinVolumeAndCheck(), G4VIntersectionLocator::LocateGlobalPointWithinVolumeCheckAndReport(), G4SPSEneDistribution::LogInterpolation(), G4GDMLRead::LoopRead(), main(), GFlashHitMaker::make(), G4GenericTrap::MakeDownFacet(), G4MolecularConfiguration::MakeExceptionIfFinalized(), G4AssemblyVolume::MakeImprint(), G4LatticeReader::MakeLattice(), G4LevelReader::MakeLevelManager(), G4ErrorPropagator::MakeOneStep(), G4Trap::MakePlanes(), G4GenericTrap::MakeUpFacet(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), G4PhysicalVolumesSearchScene::Matcher::Matcher(), G4GDMLReadMaterials::MaterialRead(), G4GDMLReadMaterials::MaterialsRead(), G4GDMLReadDefine::MatrixRead(), G4GDMLReadMaterials::MEERead(), G4MPIToolsManager::Merge(), G4AccumulableManager::Merge(), G4RootMpiPNtupleManager::Merge(), G4RootPNtupleManager::Merge(), G4ScoringMessenger::MeshBinCommand(), G4GDMLReadMaterials::MixtureRead(), G4VIntraNuclearTransportModel::ModelDescription(), HadrontherapyModulator::ModulatorPropertiesFromFile(), G4MolecularConfiguration::MoveOneElectron(), G4VTouchable::MoveUpHistory(), G4GDMLReadSolids::MultiUnionNodeRead(), G4GDMLReadSolids::MultiUnionRead(), G4ITNavigator2::NewNavigatorState(), G4ITNavigator2::NewNavigatorStateAndLocate(), G4PDefManager::NewSubInstances(), G4VUPLSplitter< T >::NewSubInstances(), G4TessellatedSolid::Normal(), G4AugerData::NumberOfAuger(), G4RDAugerData::NumberOfAuger(), G4DNAPTBIonisationStructure::NumberOfLevels(), G4AtomicTransitionManager::NumberOfReachableShells(), G4AtomicTransitionManager::NumberOfShells(), G4RDFluoData::NumberOfTransitions(), G4FluoData::NumberOfTransitions(), G4AugerData::NumberOfTransitions(), G4RDAugerData::NumberOfTransitions(), G4MultiNavigator::ObtainFinalStep(), G4ITMultiNavigator::ObtainFinalStep(), G4MagInt_Driver::OneGoodStep(), G4Hdf5RFileManager::OpenDirectory(), G4RootFileManager::OpenFile(), G4PlotManager::OpenFile(), G4Hdf5FileManager::OpenFile(), G4VAnalysisManager::OpenFile(), G4tgrFileIn::OpenNewFile(), G4RootFileManager::OpenNtupleFiles(), G4CsvRFileManager::OpenRFile(), G4XmlRFileManager::OpenRFile(), G4RootRFileManager::OpenRFile(), G4Hdf5RFileManager::OpenRFile(), G4BOptrForceCollision::OperationApplied(), DicomVFileImage::operator+(), DicomPhantomZSliceHeader::operator+(), G4WrapperProcess::operator=(), G4CrossSectionFactoryRegistry::operator=(), G4VProcess::operator=(), G4ParticleTable::operator=(), G4DNAMolecularStepByStepModel::operator=(), G4ProcessManager::operator=(), G4IT::operator=(), G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >::operator[](), G4GDMLReadSolids::OpticalSurfaceRead(), G4GDMLReadParamvol::Orb_dimensionsRead(), G4GDMLReadSolids::OrbRead(), G4MPIscorerMerger::Pack(), G4GDMLReadParamvol::Para_dimensionsRead(), G4GDMLReadSolids::ParaboloidRead(), G4RDBremsstrahlungParameters::ParameterC(), G4BremsstrahlungParameters::ParameterC(), G4GDMLReadParamvol::ParameterisedRead(), IORTDetectorConstruction::ParametersCheck(), HadrontherapyDetectorConstruction::ParametersCheck(), G4GDMLReadParamvol::ParametersRead(), G4GDMLWriteParamvol::ParametersWrite(), G4GDMLReadParamvol::Paramvol_contentRead(), G4GDMLReadParamvol::ParamvolRead(), G4GDMLReadSolids::ParaRead(), G4DNARuddIonisationModel::PartialCrossSection(), G4DNARuddIonisationExtendedModel::PartialCrossSection(), G4LossTableManager::ParticleHaveNoLoss(), G4STRead::PhysvolRead(), G4GDMLReadStructure::PhysvolRead(), G4PenelopeBremsstrahlungAngular::PolarAngle(), G4GDMLReadParamvol::Polycone_dimensionsRead(), G4GDMLReadSolids::PolyconeRead(), G4GDMLReadParamvol::Polyhedra_dimensionsRead(), G4GDMLReadSolids::PolyhedraRead(), G4DataInterpolation::PolynomInterpolation(), G4GDMLReadDefine::PositionRead(), G4NavigationLogger::PostComputeStepLog(), G4Event::PostProcessingFinished(), G4PhononReflection::PostStepDoIt(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4HadronicProcess::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4ITTransportation::PostStepDoIt(), G4BiasingProcessInterface::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4BiasingProcessInterface::PostStepGetPhysicalInteractionLength(), G4GDMLReadMaterials::PRead(), G4NavigationLogger::PreComputeStepLog(), G4GeometrySampler::PrepareImportanceSampling(), G4MultiNavigator::PrepareNavigators(), G4ITMultiNavigator::PrepareNavigators(), G4StackManager::PrepareNewEvent(), G4PathFinder::PrepareNewTrack(), G4ITPathFinder::PrepareNewTrack(), G4PhysicsTableHelper::PreparePhysicsTable(), G4VUserPhysicsList::PreparePhysicsTable(), G4PenelopeBremsstrahlungAngular::PrepareTables(), G4GeometrySampler::PrepareWeightRoulett(), G4LossTableManager::PrintEWarning(), G4DNAMolecularMaterial::PrintNotAMolecularMaterial(), G4ProcessPlacer::PrintProcVec(), G4PhysicsVector::PrintPutValueError(), G4ASTARStopping::PrintWarning(), G4PSTARStopping::PrintWarning(), G4PolarizedComptonModel::PrintWarning(), G4PreCompoundModel::PrintWarning(), G4VEmProcess::PrintWarning(), G4EmParameters::PrintWarning(), G4VEnergyLossProcess::PrintWarning(), G4VScheduler::Process(), DicomFileMgr::ProcessFiles(), B4cCalorimeterSD::ProcessHits(), G4tgrLineProcessor::ProcessLine(), G4VSceneHandler::ProcessScene(), G4DopplerProfile::Profiles(), G4RDDopplerProfile::Profiles(), G4ErrorPropagator::Propagate(), G4ErrorTrajState::PropagateError(), G4VIntraNuclearTransportModel::PropagateNuclNucl(), G4ErrorPropagator::PropagateOneStep(), G4GDMLReadMaterials::PropertyRead(), G4GDMLReadSolids::PropertyRead(), G4GDMLWriteMaterials::PropertyWrite(), G4GDMLWriteSolids::PropertyWrite(), GB01BOptrChangeCrossSection::ProposeOccurenceBiasingOperation(), G4ChannelingOptrChangeCrossSection::ProposeOccurenceBiasingOperation(), PurgMagTabulatedField3D::PurgMagTabulatedField3D(), G4StackManager::PushOneTrack(), G4QGSParticipants::PutOnMassShell(), G4GDMLReadSolids::QuadrangularRead(), G4GDMLReadStructure::QuantityRead(), G4GDMLReadDefine::QuantityRead(), G4LundStringFragmentation::Quark_AntiQuark_lastSplitting(), G4LundStringFragmentation::Quark_Diquark_lastSplitting(), G4MagInt_Driver::QuickAdvance(), G4DataSet::RandomSelect(), G4RDEMDataSet::RandomSelect(), G4DNAEmfietzoglouExcitationModel::RandomSelect(), G4DNACPA100ExcitationModel::RandomSelect(), G4EMDataSet::RandomSelect(), G4DNARuddIonisationModel::RandomSelect(), G4MuElecInelasticModel::RandomSelect(), G4DNARuddIonisationExtendedModel::RandomSelect(), G4DNABornIonisationModel1::RandomSelect(), G4MicroElecInelasticModel::RandomSelect(), G4DNACPA100IonisationModel::RandomSelect(), G4DNAEmfietzoglouIonisationModel::RandomSelect(), G4VDNAModel::RandomSelectShell(), G4DataInterpolation::RationalPolInterpolation(), G4RDAtomicTransitionManager::ReachableShell(), G4AtomicTransitionManager::ReachableShell(), G4RPGStrangeProduction::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4STRead::Read(), G4GDMLRead::Read(), DicomVFile::Read1Data(), DicomVFile::Read1DataStr(), DicomHandler::ReadCalibration(), G4MPIbatch::ReadCommand(), G4UIbatch::ReadCommand(), G4SBBremTable::ReadCompressedFile(), G4GSMottCorrection::ReadCompressedFile(), DicomVFileImage::ReadData(), DicomFileStructure::ReadData(), DicomFilePlan::ReadData(), G4AblaDataFile::readData(), G4LivermoreRayleighModel::ReadData(), G4BoldyshevTripletModel::ReadData(), G4LivermoreComptonModel::ReadData(), G4LivermoreNuclearGammaConversionModel::ReadData(), G4LivermorePolarizedPhotoElectricGDModel::ReadData(), G4LivermoreGammaConversionModel::ReadData(), G4LivermoreGammaConversionModelRC::ReadData(), G4LivermorePolarizedGammaConversionModel::ReadData(), G4LivermoreBremsstrahlungModel::ReadData(), G4JAEAElasticScatteringModel::ReadData(), G4LivermorePolarizedPhotoElectricModel::ReadData(), G4LivermorePolarizedRayleighModel::ReadData(), G4LivermorePhotoElectricModel::ReadData(), G4SeltzerBergerModel::ReadData(), XrayFluoRunAction::ReadData(), G4LivermorePolarizedComptonModel::ReadData(), G4LowEPComptonModel::ReadData(), G4LowEPPolarizedComptonModel::ReadData(), G4ComponentSAIDTotalXS::ReadData(), G4PenelopeBremsstrahlungAngular::ReadDataFile(), G4PenelopeGammaConversionModel::ReadDataFile(), G4PenelopeBremsstrahlungFS::ReadDataFile(), G4PenelopePhotoElectricModel::ReadDataFile(), G4PenelopeRayleighModel::ReadDataFile(), DicomPhantomZSliceHeader::ReadDataFromFile(), G4OpticalSurface::ReadDichroicFile(), G4DNAPTBElasticModel::ReadDiffCSFile(), G4DNAPTBIonisationModel::ReadDiffCSFile(), G4VDNAModel::ReadDiffCSFile(), G4PenelopeOscillatorManager::ReadElementData(), G4LEPTSElossDistr::ReadFile(), DicomHandler::ReadFile(), G4tgrFileReader::ReadFiles(), G4ChannelingECHARM::ReadFromECHARM(), G4STRead::ReadGeom(), G4VAnalysisReader::ReadH1(), G4RootAnalysisReader::ReadH1Impl(), G4CsvAnalysisReader::ReadH1Impl(), G4VAnalysisReader::ReadH2(), G4RootAnalysisReader::ReadH2Impl(), G4CsvAnalysisReader::ReadH2Impl(), G4VAnalysisReader::ReadH3(), G4RootAnalysisReader::ReadH3Impl(), G4CsvAnalysisReader::ReadH3Impl(), G4ENDFTapeRead::ReadInData(), G4VLEPTSModel::ReadIXS(), G4OpticalSurface::ReadLUTDAVISFile(), G4OpticalSurface::ReadLUTFile(), G4RootAnalysisReader::ReadNtupleImpl(), G4PhysicsListHelper::ReadOrdingParameterTable(), G4VAnalysisReader::ReadP1(), G4CsvAnalysisReader::ReadP1Impl(), G4RootAnalysisReader::ReadP1Impl(), G4VAnalysisReader::ReadP2(), G4CsvAnalysisReader::ReadP2Impl(), G4RootAnalysisReader::ReadP2Impl(), G4VLEPTSModel::ReadParam(), DicomPartialDetectorConstruction::ReadPhantomData(), DicomDetectorConstruction::ReadPhantomData(), DicomPartialDetectorConstruction::ReadPhantomDataFile(), DicomDetectorConstruction::ReadPhantomDataFile(), DicomDetectorConstruction::ReadPhantomDataNew(), DicomVFileImage::ReadPixelData(), G4OpticalSurface::ReadReflectivityLUTFile(), G4STRead::ReadTree(), G4MPIToolsManager::Receive(), G4Navigator::RecheckDistanceToCurrentBoundary(), G4ITNavigator2::RecheckDistanceToCurrentBoundary(), G4StackManager::ReClassify(), G4MolecularConfiguration::G4MolecularConfigurationManager::RecordNewlyLabeledConfiguration(), G4VIntersectionLocator::ReEstimateEndpoint(), G4SmartVoxelHeader::RefineNodes(), G4GDMLReadSolids::ReflectedSolidRead(), G4ReflectionFactory::ReflectPVParameterised(), G4GDMLReadDefine::RefRead(), G4CreatorFactoryT< T, Identifier, Creator >::Register(), G4CrossSectionFactoryRegistry::Register(), G4UImanager::RegisterBridge(), G4ExtendedMaterial::RegisterExtension(), G4PhysicsBuilderInterface::RegisterMe(), G4HadronicProcess::RegisterMe(), G4tgrVolumeMgr::RegisterMe(), G4coutFormatters::RegisterNewStyle(), G4VUserDetectorConstruction::RegisterParallelWorld(), G4VModularPhysicsList::RegisterPhysics(), G4MultiFunctionalDetector::RegisterPrimitive(), G4PhysicsListHelper::RegisterProcess(), field_utils::relativeError2(), G4PathFinder::ReLocate(), G4ITPathFinder::ReLocate(), G4SafetyHelper::ReLocateWithinVolume(), G4ITSafetyHelper::ReLocateWithinVolume(), G4ParticleTable::Remove(), G4IonTable::Remove(), G4ParticleTable::RemoveAllParticles(), G4MoleculeCounter::RemoveAMoleculeAtTime(), G4ElectronOccupancy::RemoveElectron(), G4MolecularConfiguration::RemoveElectron(), WLSPhysicsList::RemoveFromPhysicsList(), G4ParallelGeometriesLimiterProcess::RemoveParallelWorld(), G4VModularPhysicsList::RemovePhysics(), G4ExtDEDXTable::RemovePhysicsVector(), G4IonStoppingData::RemovePhysicsVector(), G4ProcessManager::RemoveProcess(), G4VIntegrationDriver::RenewStepperAndAdjust(), G3VolTableEntry::ReplaceDaughter(), G3VolTableEntry::ReplaceMother(), G4VModularPhysicsList::ReplacePhysics(), G4GDMLReadStructure::ReplicaRead(), G4GDMLReadStructure::ReplicavolRead(), G4ConversionFatalError::ReportError(), G4CoupledTransportation::ReportInexactEnergy(), G4PropagatorInField::ReportLoopingParticle(), G4TransportationLogger::ReportLoopingTrack(), G4Transportation::ReportMissingLogger(), G4CoupledTransportation::ReportMissingLogger(), G4PathFinder::ReportMove(), G4ITPathFinder::ReportMove(), G4VBiasingOperator::ReportOperationApplied(), G4NavigationLogger::ReportOutsideMother(), G4PropagatorInField::ReportStuckParticle(), G4VIntersectionLocator::ReportTrialStep(), G4ASCIITreeSceneHandler::RequestPrimitives(), G4GenericPolycone::Reset(), G4Polyhedra::Reset(), G4MultiNavigator::ResetHierarchyAndLocate(), G4ITMultiNavigator::ResetHierarchyAndLocate(), G4MultiNavigator::ResetState(), G4ITMultiNavigator::ResetState(), G4ProductionCutsTable::RetrieveCutsInfo(), G4GMocrenIO::retrieveData(), G4ExtendedMaterial::RetrieveExtension(), G4PhysicsTableHelper::RetrievePhysicsTable(), G4ExtDEDXTable::RetrievePhysicsTable(), G4NeutronCaptureXS::RetrieveVector(), G4NeutronInelasticXS::RetrieveVector(), G4ParticleInelasticXS::RetrieveVector(), G4LENDModel::returnUnchanged(), G4GDMLReadDefine::RotationRead(), G4DNAChemistryManager::Run(), G4RunManagerKernel::RunInitialization(), G4GDMLReadSolids::RZPointRead(), G4VoxelSafety::SafetyForVoxelHeader(), G4TessellatedSolid::SafetyFromInside(), G4TessellatedSolid::SafetyFromOutside(), G4ParticleHPEnAngCorrelation::Sample(), G4PenelopeBremsstrahlungAngular::SampleDirection(), G4SBBremTable::SampleEnergyTransfer(), G4SeltzerBergerModel::SampleEnergyTransfer(), G4PenelopeBremsstrahlungFS::SampleGammaEnergy(), G4ILawTruncatedExp::SampleInteractionLength(), G4InteractionLawPhysical::SampleInteractionLength(), G4DNADingfelderChargeDecreaseModel::SampleSecondaries(), G4DNADingfelderChargeIncreaseModel::SampleSecondaries(), G4DNARuddIonisationModel::SampleSecondaries(), G4DNARuddIonisationExtendedModel::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4DNABornIonisationModel1::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4PenelopeGammaConversionModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4PenelopeRayleighModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4PenelopeIonisationModel::SampleSecondaries(), G4DNAModelInterface::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), G4LowEPPolarizedComptonModel::SampleSecondaries(), G4LundStringFragmentation::SampleState(), Histo::Save(), G4RDCompositeEMDataSet::SaveData(), G4RDShellEMDataSet::SaveData(), G4MicroElecCrossSectionDataSet::SaveData(), G4MuElecCrossSectionDataSet::SaveData(), G4DataSet::SaveData(), G4CompositeDataSet::SaveData(), G4RDEMDataSet::SaveData(), G4ShellEMDataSet::SaveData(), G4CompositeEMDataSet::SaveData(), G4CrossSectionDataSet::SaveData(), G4DNACrossSectionDataSet::SaveData(), G4EMDataSet::SaveData(), G4GDMLReadSolids::ScaledSolidRead(), G4GDMLReadDefine::ScaleRead(), G4Region::ScanVolumeTree(), G4Scatterer::Scatter(), G4VPartonStringModel::Scatter(), G4QuasiElRatios::Scatter(), G4GDMLReadSolids::SectionRead(), G4DNAUeharaScreenedRutherfordElasticModel::SelectHighEnergyLimit(), G4RDShellData::SelectRandomShell(), G4ShellData::SelectRandomShell(), G4VCrossSectionHandler::SelectRandomShell(), G4PenelopePhotoElectricModel::SelectRandomShell(), G4AtomicDeexcitation::SelectTypeOfTransition(), G4RDAtomicDeexcitation::SelectTypeOfTransition(), G4MPIToolsManager::Send(), G4ModelColourMap< G4String >::Set(), G4GDMLMatrix::Set(), G4TrajectoryDrawByCharge::Set(), G4Torus::SetAllParameters(), G4LowEnergyPhotoElectric::SetAngularGenerator(), G4LowEnergyBremsstrahlung::SetAngularGenerator(), G4Track::SetAuxiliaryTrackInformation(), G4TwistTrapParallelSide::SetBoundaries(), G4TwistBoxSide::SetBoundaries(), G4TwistTrapAlphaSide::SetBoundaries(), G4TwistTrapFlatSide::SetBoundaries(), G4TwistTubsFlatSide::SetBoundaries(), G4TwistTubsHypeSide::SetBoundaries(), G4TwistTubsSide::SetBoundaries(), G4VTwistSurface::SetBoundary(), HadrontherapyRBE::SetCellLine(), G4VTwistSurface::SetCorner(), G4TwistBoxSide::SetCorners(), G4TwistTrapParallelSide::SetCorners(), G4TwistTrapAlphaSide::SetCorners(), G4TwistTrapFlatSide::SetCorners(), G4TwistTubsFlatSide::SetCorners(), G4TwistTubsHypeSide::SetCorners(), G4TwistTubsSide::SetCorners(), G4VisListManager< T >::SetCurrent(), G4GeneralParticleSource::SetCurrentSourceto(), G4VTwistSurface::CurrentStatus::SetCurrentStatus(), ExTGRCRegionData::SetCutsData(), G4VDecayChannel::SetDaughter(), G4Radioactivation::SetDecayBias(), G4RadioactiveDecay::SetDecayBias(), G4TrajectoryDrawByOriginVolume::SetDefault(), G4TrajectoryDrawByEncounteredVolume::SetDefault(), G4TrajectoryDrawByParticleID::SetDefault(), G4UIparameter::SetDefaultUnit(), G4FieldManager::SetDetectorField(), XrayFluoPlaneDetectorConstruction::SetDetectorType(), XrayFluoMercuryDetectorConstruction::SetDetectorType(), XrayFluoDetectorConstruction::SetDetectorType(), G4NystromRK4::SetDistanceForConstantField(), G4MonopolePhysics::SetElectricCharge(), G4MicroElecCrossSectionDataSet::SetEnergiesData(), G4MuElecCrossSectionDataSet::SetEnergiesData(), G4RDCompositeEMDataSet::SetEnergiesData(), G4RDShellEMDataSet::SetEnergiesData(), G4ShellEMDataSet::SetEnergiesData(), G4CompositeEMDataSet::SetEnergiesData(), G4CompositeDataSet::SetEnergiesData(), G4DataSet::SetEnergiesData(), G4RDEMDataSet::SetEnergiesData(), G4DNACrossSectionDataSet::SetEnergiesData(), G4CrossSectionDataSet::SetEnergiesData(), G4PixeShellDataSet::SetEnergiesData(), G4EMDataSet::SetEnergiesData(), G4VRangeToEnergyConverter::SetEnergyRange(), G4MPImanager::SetExtraWorker(), G4VFileManager::SetFileName(), G4BaseAnalysisManager::SetFirstId(), G4BaseNtupleManager::SetFirstNtupleColumnId(), G4ILawTruncatedExp::SetForceCrossSection(), G4MaterialPropertiesTable::SetGROUPVEL(), GammaKnifeDetectorConstruction::SetHelmetSize(), G4VFileManager::SetHistoDirectoryName(), G4INCLXXInterfaceStore::SetINCLPhysics(), G4SteppingManager::SetInitialStep(), G4ITStepProcessor::SetInitialStep(), G4VMoleculeCounter::SetInstance(), G4DNAScreenedRutherfordElasticModel::SetKillBelowThreshold(), G4DNAUeharaScreenedRutherfordElasticModel::SetKillBelowThreshold(), G4DNAChampionElasticModel::SetKillBelowThreshold(), G4MicroElecElasticModel::SetKillBelowThreshold(), G4MuElecElasticModel::SetKillBelowThreshold(), G4DNACPA100ElasticModel::SetKillBelowThreshold(), G4PlotParameters::SetLayout(), G4MicroElecCrossSectionDataSet::SetLogEnergiesData(), G4MuElecCrossSectionDataSet::SetLogEnergiesData(), G4ShellEMDataSet::SetLogEnergiesData(), G4CompositeEMDataSet::SetLogEnergiesData(), G4CrossSectionDataSet::SetLogEnergiesData(), G4DNACrossSectionDataSet::SetLogEnergiesData(), G4EMDataSet::SetLogEnergiesData(), G4MonopolePhysics::SetMagneticCharge(), G4PhysicsBuilderInterface::SetMaxEnergy(), G4GDMLWriteStructure::SetMaxExportLevel(), G4PhysicsBuilderInterface::SetMinEnergy(), G4VisFilterManager< G4VTrajectory >::SetMode(), G4ITModelManager::SetModel(), G4ITModelProcessor::SetModelHandler(), G4MonopolePhysics::SetMonopoleMass(), G4RootMpiAnalysisManager::SetMpiNtupleMergingMode(), G4NtupleMessenger::SetNewValue(), DicomIntersectVolume::SetNewValue(), G4ModelCmdApplyStringColour< M >::SetNewValue(), G4ParticleGunMessenger::SetNewValue(), G4OpticalPhysicsMessenger::SetNewValue(), G4EmParametersMessenger::SetNewValue(), G4RunMessenger::SetNewValue(), G4GeneralParticleSourceMessenger::SetNewValue(), G4ModelCmdApplyColour< M >::SetNewValue(), G4VFileManager::SetNtupleDirectoryName(), G4RootAnalysisManager::SetNtupleMergingMode(), G4ProcessTableMessenger::SetNumberOfProcessType(), G4VScoringMesh::SetNumberOfSegments(), G4MTRunManager::SetNumberOfThreads(), G4Polycone::SetOriginalParameters(), G4Polyhedra::SetOriginalParameters(), G4ScoreNtupleWriter::SetOutputType(), G4ParallelWorldProcessStore::SetParallelWorld(), G4PVDivision::SetParameterisation(), G4ReplicatedSlice::SetParameterisation(), G4PSNofSecondary::SetParticle(), G4VUserPhysicsList::SetParticleCuts(), G4ParticleGun::SetParticleDefinition(), G4ParticleDefinition::SetParticleDefinitionID(), CCalVisualisable::setPath(), G4InteractionLawPhysical::SetPhysicalCrossSection(), G4PhysicsTableHelper::SetPhysicsVector(), G4WorkerThread::SetPinAffinity(), G4MTRunManager::SetPinAffinity(), PurgMagPhysicsList::SetPositronLowLimit(), G4ParallelGeometriesLimiterProcess::SetProcessManager(), G4ParticleDefinition::SetProcessManager(), G4ProcessManager::SetProcessOrderingToFirst(), G4ProcessManager::SetProcessOrderingToLast(), G4ProductionCuts::SetProductionCuts(), PurgMagPhysicsList::SetProtonLowLimit(), G4RunManager::SetRandomNumberStoreDir(), G3Division::SetRangeAndAxis(), G4DNASecondOrderReaction::SetReaction(), G4Scintillation::SetScintillationByParticleType(), G4VUserParallelWorld::SetSensitiveDetector(), G4VUserDetectorConstruction::SetSensitiveDetector(), G4VScoringMesh::SetSize(), G4MagInt_Driver::SetSmallestFraction(), G4Radioactivation::SetSourceTimeProfile(), G4RadioactiveDecay::SetSourceTimeProfile(), G4tgrMaterial::SetState(), G4PlotParameters::SetStyle(), G4GeometryTolerance::SetSurfaceTolerance(), G4ITStepProcessor::SetTrack(), G4TrackingManager::SetTrajectory(), G4PSNofStep::SetUnit(), G4PSNofCollision::SetUnit(), G4PSTermination::SetUnit(), G4GenericMessenger::Command::SetUnit(), G4PSTrackCounter::SetUnit(), G4PSPassageCellCurrent::SetUnit(), G4PSPopulation::SetUnit(), G4PSNofSecondary::SetUnit(), G4PSSphereSurfaceCurrent::SetUnit(), G4PSCylinderSurfaceFlux::SetUnit(), G4PSCylinderSurfaceCurrent::SetUnit(), G4PSSphereSurfaceFlux::SetUnit(), G4PSFlatSurfaceCurrent::SetUnit(), G4PSFlatSurfaceFlux::SetUnit(), G4RTPrimaryGeneratorAction::SetUp(), G4RunManagerKernel::SetupDefaultRegion(), G4ITStepProcessor::SetupGeneralProcessInfo(), G4MultiNavigator::SetupHierarchy(), G4ITMultiNavigator::SetupHierarchy(), G4GDMLReadSetup::SetupRead(), G4UserWorkerThreadInitialization::SetupRNGEngine(), G4WorkerRunManagerKernel::SetupShadowProcess(), G4MTRunManager::SetUserAction(), G4EventManager::SetUserInformation(), G4WorkerRunManager::SetUserInitialization(), G4RunManager::SetUserInitialization(), G4GDMLEvaluator::SetVariable(), G4VelocityTable::SetVelocityTableProperties(), G4GeometryManager::SetWorldMaximumExtent(), G4FastSimulationManagerProcess::SetWorldVolume(), G4Box::SetXHalfLength(), G4Box::SetYHalfLength(), G4Box::SetZHalfLength(), G4BetaDecayCorrections::ShapeFactor(), G4RDAtomicTransitionManager::Shell(), G4AtomicTransitionManager::Shell(), G4RDShellData::ShellIdVector(), G4ShellData::ShellIdVector(), G4ShellData::ShellVector(), G4RDShellData::ShellVector(), G4RayShooter::Shoot(), G4GMocrenFileViewer::ShowView(), SignalHandler(), G4GDMLWriteStructure::SkinSurfaceCache(), G4GDMLReadStructure::SkinSurfaceRead(), G4GeomSplitter< T >::SlaveCopySubInstanceArray(), G4IonTable::SlaveG4IonTable(), G4ParticleTable::SlaveG4ParticleTable(), G4GeomSplitter< T >::SlaveInitializeSubInstance(), G4GeomSplitter< T >::SlaveReCopySubInstanceArray(), G4GDMLReadSolids::SolidsRead(), G4GDMLEvaluator::SolveBrackets(), G4GDMLReadParamvol::Sphere_dimensionsRead(), G4GDMLReadSolids::SphereRead(), G4SPSEneDistribution::SplineInterpolation(), G4SamplingPostStepAction::Split(), G4BooleanSolid::StackPolyhedron(), GB05BOptrSplitAndKillByCrossSection::StartRun(), G4FluoData::StartShellEnergy(), G4RDFluoData::StartShellEnergy(), G4AugerData::StartShellEnergy(), G4RDAugerData::StartShellEnergy(), G4FluoData::StartShellId(), G4RDFluoData::StartShellId(), G4RDAugerData::StartShellId(), G4AugerData::StartShellId(), G4FluoData::StartShellProb(), G4RDFluoData::StartShellProb(), G4RDAugerData::StartShellProb(), G4AugerData::StartShellProb(), G4WeightCutOffProcess::StartTracking(), G4ImportanceProcess::StartTracking(), G4WeightWindowProcess::StartTracking(), G4ParallelWorldScoringProcess::StartTracking(), G4ParallelWorldProcess::StartTracking(), G4Scheduler::Stepping(), G4CashKarpRKF45::StepWithEst(), G4ClassicalRK4::StepWithEst(), G4RKG3_Stepper::StepWithEst(), G4ProductionCutsTable::StoreCutsInfo(), G4ProductionCutsTable::StoreMaterialCutsCoupleInfo(), G4ProductionCutsTable::StoreMaterialInfo(), G4ExtDEDXTable::StorePhysicsTable(), G4VUserPhysicsList::StorePhysicsTable(), G4NuclideTable::StripFloatLevelBase(), G4GDMLReadStructure::StructureRead(), G4tgrUtils::SubColon(), SubstractSolids(), G4VITProcess::SubtractNumberOfInteractionLengthLeft(), G4VProcess::SubtractNumberOfInteractionLengthLeft(), G4EllipticalTube::SurfaceNormal(), G4UnionSolid::SurfaceNormal(), G4Box::SurfaceNormal(), G4GenericTrap::SurfaceNormal(), G4Paraboloid::SurfaceNormal(), G4CutTubs::SurfaceNormal(), G4EllipticalCone::SurfaceNormal(), G4Trd::SurfaceNormal(), G4ExtrudedSolid::SurfaceNormal(), G4Para::SurfaceNormal(), G4Tubs::SurfaceNormal(), G4Cons::SurfaceNormal(), G4Torus::SurfaceNormal(), G4Sphere::SurfaceNormal(), G4Trap::SurfaceNormal(), TCRMC_FTFP_BERT< T >::TCRMC_FTFP_BERT(), G4GDMLReadSolids::TessellatedRead(), G4GDMLWriteSolids::TessellatedWrite(), G4DNAMolecularReaction::TestReactibility(), G4GDMLReadSolids::TetRead(), THIJING< T >::THIJING(), G4PhaseSpaceDecayChannel::ThreeBodyDecayIt(), G4GeneralPhaseSpaceDecay::ThreeBodyDecayIt(), G4GDMLReadParamvol::Torus_dimensionsRead(), G4GDMLReadSolids::TorusRead(), G4RDAtomicTransitionManager::TotalNonRadiativeTransitionProbability(), G4AtomicTransitionManager::TotalNonRadiativeTransitionProbability(), G4RDAtomicTransitionManager::TotalRadiativeTransitionProbability(), G4AtomicTransitionManager::TotalRadiativeTransitionProbability(), G4tgbMaterialMixtureByVolume::TransformToFractionsByWeight(), G4GDMLReadParamvol::Trap_dimensionsRead(), G4GDMLReadSolids::TrapRead(), G4GDMLWriteStructure::TraverseVolumeTree(), G4GDMLReadParamvol::Trd_dimensionsRead(), G4GDMLReadSolids::TrdRead(), G4GDMLReadMaterials::TRead(), G4GDMLReadSolids::TriangularRead(), G4PolyPhiFace::Triangulate(), G4GDMLReadParamvol::Tube_dimensionsRead(), G4GDMLReadSolids::TubeRead(), TUrQMD< T >::TUrQMD(), G4GDMLReadSolids::TwistedboxRead(), G4GDMLReadSolids::TwistedtrapRead(), G4GDMLReadSolids::TwistedtrdRead(), G4GDMLReadSolids::TwistedtubsRead(), G4PhaseSpaceDecayChannel::TwoBodyDecayIt(), G4GDMLReadSolids::TwoDimVertexRead(), UltraFresnelLens::UltraFresnelLens(), G4MPIscorerMerger::UnPackAndMerge(), G4tgrVolumeMgr::UnRegisterMe(), G4ILawTruncatedExp::UpdateInteractionLengthForStep(), G4InteractionLawPhysical::UpdateInteractionLengthForStep(), G4RunManagerKernel::UpdateRegion(), G4VTouchable::UpdateYourself(), G4ParticleHPInelasticCompFS::use_nresp71_model(), G4GDMLRead::UserinfoRead(), LXeSteppingAction::UserSteppingAction(), F05SteppingAction::UserSteppingAction(), G4OpWLS::UseTimeProfile(), G4PDefManager::UseWorkArea(), G4VUPLSplitter< T >::UseWorkArea(), G4GeomSplitter< T >::UseWorkArea(), G4RDFluoData::VacancyId(), G4FluoData::VacancyId(), G4RDAugerData::VacancyId(), G4AugerData::VacancyId(), G4GDMLReadDefine::VariableRead(), G4GDMLReadDefine::VectorRead(), G4GDMLReadStructure::Volume_contentRead(), G4GDMLReadStructure::VolumeRead(), G4UIGainServer::WaitingConnection(), G4AnalysisMessengerHelper::WarnAboutParameters(), G4AnalysisMessengerHelper::WarnAboutSetCommands(), G4MagInt_Driver::WarnEndPointTooFar(), G4ImportanceAlgorithm::Warning(), G4MagInt_Driver::WarnSmallStepSize(), G4MagInt_Driver::WarnTooManyStep(), G4Clebsch::Wigner6J(), G4VUPLSplitter< T >::WorkerCopySubInstanceArray(), G4RunManagerKernel::WorkerDefineWorldVolume(), G4GDMLWrite::Write(), G4VAnalysisManager::WriteAscii(), G4Hdf5FileManager::WriteDirectory(), G4XmlAnalysisManager::WriteImpl(), G4CsvAnalysisManager::WriteImpl(), G4RootAnalysisManager::WriteImpl(), G4PlotManager::WritePage(), G4GDMLReadSolids::XtruRead(), G4GDMLReadSolids::ZplaneRead(), G4BOptrForceCollisionTrackData::~G4BOptrForceCollisionTrackData(), G4MTRunManagerKernel::~G4MTRunManagerKernel(), and G4ParticleDefinition::~G4ParticleDefinition().
G4Exception() [2/3]
void G4Exception (const char * originOfException, const char * exceptionCode, G4ExceptionSeverity severity, G4ExceptionDescription & description)
Definition at line 101 of file G4Exception.cc.
G4Exception() [3/3]
void G4Exception (const char * originOfException, const char * exceptionCode, G4ExceptionSeverity severity, G4ExceptionDescription & description, const char * comments)
Definition at line 110 of file G4Exception.cc.