Geant4: G4VInteractiveSession Class Reference
G4VInteractiveSession Class Reference
#include <G4VInteractiveSession.hh>
Public Member Functions
G4VInteractiveSession ()
virtual ~G4VInteractiveSession ()
virtual void AddMenu (const char *, const char *)
virtual void AddButton (const char *, const char *, const char *)
virtual void AddIcon (const char *, const char *, const char *, const char *)
virtual void DefaultIcons (bool)
void AddInteractor (G4String, G4Interactor)
G4Interactor GetInteractor (G4String)
Private Types
typedef std::map< G4String, G4Interactor, std::less< G4String > > G4interactor_map
Private Attributes
G4UImessenger * messenger
G4interactor_map interactors
Detailed Description
Definition at line 44 of file G4VInteractiveSession.hh.
Member Typedef Documentation
G4interactor_map
typedef std::map<G4String,G4Interactor, std::less<G4String> > G4VInteractiveSession::G4interactor_map private
Definition at line 60 of file G4VInteractiveSession.hh.
Constructor & Destructor Documentation
G4VInteractiveSession()
G4VInteractiveSession::G4VInteractiveSession ()
Definition at line 33 of file G4VInteractiveSession.cc.
~G4VInteractiveSession()
G4VInteractiveSession::~G4VInteractiveSession () virtual
Definition at line 39 of file G4VInteractiveSession.cc.
Member Function Documentation
AddButton()
void G4VInteractiveSession::AddButton (const char * , const char * , const char *) virtual
Definition at line 50 of file G4VInteractiveSession.cc.
Referenced by G4InteractorMessenger::SetNewValue().
AddIcon()
void G4VInteractiveSession::AddIcon (const char * , const char * , const char * , const char *) virtual
Definition at line 60 of file G4VInteractiveSession.cc.
Referenced by G4InteractorMessenger::SetNewValue().
AddInteractor()
void G4VInteractiveSession::AddInteractor (G4String a_name, G4Interactor a_interactor)
Definition at line 65 of file G4VInteractiveSession.cc.
AddMenu()
void G4VInteractiveSession::AddMenu (const char * , const char *) virtual
Definition at line 45 of file G4VInteractiveSession.cc.
Referenced by G4InteractorMessenger::SetNewValue().
DefaultIcons()
void G4VInteractiveSession::DefaultIcons (bool) virtual
Definition at line 55 of file G4VInteractiveSession.cc.
Referenced by G4InteractorMessenger::SetNewValue().
GetInteractor()
G4Interactor G4VInteractiveSession::GetInteractor (G4String a_name)
Definition at line 72 of file G4VInteractiveSession.cc.
Field Documentation
interactors
G4interactor_map G4VInteractiveSession::interactors private
Definition at line 61 of file G4VInteractiveSession.hh.
Referenced by AddInteractor(), and GetInteractor().
messenger
G4UImessenger* G4VInteractiveSession::messenger private
Definition at line 59 of file G4VInteractiveSession.hh.
Referenced by G4VInteractiveSession(), and ~G4VInteractiveSession().
The documentation for this class was generated from the following files:
source/interfaces/common/include/G4VInteractiveSession.hh
source/interfaces/common/src/G4VInteractiveSession.cc