Geant4: G4Vee2hadrons Class Reference
G4Vee2hadrons Class Reference abstract
#include <G4Vee2hadrons.hh>
Public Member Functions
G4Vee2hadrons (G4eeCrossSections *cr, G4double vlowEnergy, G4double vhighEnergy, G4double vdelta)
virtual ~G4Vee2hadrons ()
virtual G4double PeakEnergy () const =0
virtual G4double ComputeCrossSection (G4double) const =0
G4PhysicsVector * PhysicsVector () const
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, G4double, const G4ThreeVector &)=0
G4double LowEnergy () const
G4double HighEnergy () const
Protected Attributes
G4eeCrossSections * cross
Private Member Functions
G4Vee2hadrons & operator= (const G4Vee2hadrons &right)=delete
G4Vee2hadrons (const G4Vee2hadrons &)=delete
Private Attributes
G4double lowEnergy
G4double highEnergy
G4double delta
Detailed Description
Definition at line 62 of file G4Vee2hadrons.hh.
Constructor & Destructor Documentation
G4Vee2hadrons() [1/2]
G4Vee2hadrons::G4Vee2hadrons (G4eeCrossSections * cr, G4double vlowEnergy, G4double vhighEnergy, G4double vdelta) inline explicit
Definition at line 67 of file G4Vee2hadrons.hh.
~G4Vee2hadrons()
virtual G4Vee2hadrons::~G4Vee2hadrons () inline virtual
Definition at line 77 of file G4Vee2hadrons.hh.
G4Vee2hadrons() [2/2]
G4Vee2hadrons::G4Vee2hadrons (const G4Vee2hadrons &) private delete
Member Function Documentation
ComputeCrossSection()
virtual G4double G4Vee2hadrons::ComputeCrossSection (G4double) const pure virtual
Implemented in G4eeToPGammaModel, G4ee2KChargedModel, G4ee2KNeutralModel, G4eeTo3PiModel, and G4eeToTwoPiModel.
Referenced by G4eeToHadronsModel::Initialise().
HighEnergy()
G4double G4Vee2hadrons::HighEnergy () const inline
Definition at line 95 of file G4Vee2hadrons.hh.
Referenced by G4eeToHadronsMultiModel::AddEEModel(), G4eeToHadronsModel::Initialise(), and G4eeTo3PiModel::PeakEnergy().
LowEnergy()
G4double G4Vee2hadrons::LowEnergy () const inline
Definition at line 93 of file G4Vee2hadrons.hh.
Referenced by G4eeToHadronsMultiModel::AddEEModel(), and G4eeToHadronsModel::Initialise().
operator=()
G4Vee2hadrons& G4Vee2hadrons::operator= (const G4Vee2hadrons & right) private delete
PeakEnergy()
virtual G4double G4Vee2hadrons::PeakEnergy () const pure virtual
Implemented in G4eeToPGammaModel, G4ee2KChargedModel, G4ee2KNeutralModel, G4eeTo3PiModel, and G4eeToTwoPiModel.
Referenced by G4eeToHadronsMultiModel::AddEEModel(), and G4eeToHadronsModel::Initialise().
PhysicsVector()
G4PhysicsVector* G4Vee2hadrons::PhysicsVector () const inline
Definition at line 83 of file G4Vee2hadrons.hh.
Referenced by G4eeToHadronsModel::Initialise().
SampleSecondaries()
virtual void G4Vee2hadrons::SampleSecondaries (std::vector< G4DynamicParticle * > * , G4double , const G4ThreeVector &) pure virtual
Implemented in G4eeToPGammaModel, G4ee2KChargedModel, G4ee2KNeutralModel, G4eeTo3PiModel, and G4eeToTwoPiModel.
Referenced by G4eeToHadronsModel::SampleSecondaries().
Field Documentation
cross
G4eeCrossSections* G4Vee2hadrons::cross protected
Definition at line 110 of file G4Vee2hadrons.hh.
Referenced by G4ee2KChargedModel::ComputeCrossSection(), G4eeToTwoPiModel::ComputeCrossSection(), G4ee2KNeutralModel::ComputeCrossSection(), G4eeTo3PiModel::ComputeCrossSection(), G4eeToPGammaModel::ComputeCrossSection(), and G4eeTo3PiModel::SampleSecondaries().
delta
G4double G4Vee2hadrons::delta private
Definition at line 106 of file G4Vee2hadrons.hh.
Referenced by G4Vee2hadrons(), and PhysicsVector().
highEnergy
G4double G4Vee2hadrons::highEnergy private
Definition at line 105 of file G4Vee2hadrons.hh.
Referenced by G4Vee2hadrons(), HighEnergy(), and PhysicsVector().
lowEnergy
G4double G4Vee2hadrons::lowEnergy private
Definition at line 104 of file G4Vee2hadrons.hh.
Referenced by G4Vee2hadrons(), LowEnergy(), and PhysicsVector().
The documentation for this class was generated from the following file:
source/processes/electromagnetic/highenergy/include/G4Vee2hadrons.hh