Geant4: G4VPVParameterisation Class Reference
G4VPVParameterisation Class Reference abstract
#include <G4VPVParameterisation.hh>
Public Member Functions
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual void ComputeTransformation (const G4int, G4VPhysicalVolume *) const =0
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=0)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
virtual void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
Detailed Description
Definition at line 71 of file G4VPVParameterisation.hh.
Constructor & Destructor Documentation
G4VPVParameterisation()
G4VPVParameterisation::G4VPVParameterisation ()
Definition at line 37 of file G4VPVParameterisation.cc.
~G4VPVParameterisation()
G4VPVParameterisation::~G4VPVParameterisation () virtual
Definition at line 41 of file G4VPVParameterisation.cc.
Member Function Documentation
ComputeDimensions() [1/13]
virtual void G4VPVParameterisation::ComputeDimensions (G4Box & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented in G02ChamberParameterisation, ExP01ChamberParameterisation, ExN02ChamberParameterisation, VoxelParam, VoxelParam, VoxelParam, G4ParameterisationBoxZ, G4ParameterisationBoxY, G4ParameterisationBoxX, G4EzVoxelParameterization, G4ParameterisationPolyhedraZ, G4ParameterisationPolyconeZ, G4ParameterisationTrdZ, G4ParameterisationParaZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationPolyhedraPhi, G4ParameterisationTrdY, G4ParameterisationPolyconePhi, G4ParameterisationConsPhi, G4ParameterisationParaY, G4ParameterisationTubsPhi, RE02NestedPhantomParameterisation, G4VNestedParameterisation, G4ParameterisationPolyhedraRho, G4ParameterisationTrdX, G4ParameterisationPolyconeRho, DicomNestedPhantomParameterisation, G4ParameterisationConsRho, G4ParameterisationParaX, G4ParameterisationTubsRho, ChromosomeParameterisation, G4PhantomParameterisation, UltraFresnelLensParameterisation, RE05CalorimeterParametrisation, RE04ParallelWorldParam, RE01TrackerParametrisation, G4GDMLParameterisation, RE01CalorimeterParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, B2bChamberParameterisation, B2bChamberParameterisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, and CellParameterisation.
Definition at line 94 of file G4VPVParameterisation.hh.
Referenced by G4Box::ComputeDimensions(), G4Orb::ComputeDimensions(), G4Ellipsoid::ComputeDimensions(), G4Hype::ComputeDimensions(), G4Trd::ComputeDimensions(), G4Polyhedra::ComputeDimensions(), G4Polycone::ComputeDimensions(), G4Para::ComputeDimensions(), G4Tubs::ComputeDimensions(), G4Cons::ComputeDimensions(), G4Sphere::ComputeDimensions(), G4Torus::ComputeDimensions(), G4Trap::ComputeDimensions(), G4tgbGeometryDumper::DumpPVParameterised(), and G4GDMLWriteParamvol::ParametersWrite().
ComputeDimensions() [2/13]
virtual void G4VPVParameterisation::ComputeDimensions (G4Cons & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationConsZ, G4ParameterisationConsPhi, G4ParameterisationConsRho, UltraFresnelLensParameterisation, G4ParameterisationPolyhedraZ, G4ParameterisationPolyconeZ, G4ParameterisationTrdZ, G4ParameterisationTubsZ, G4ParameterisationParaZ, G4ParameterisationBoxZ, G4ParameterisationPolyhedraPhi, G4ParameterisationPolyconePhi, G4ParameterisationTrdY, G4ParameterisationTubsPhi, G4ParameterisationParaY, G4ParameterisationBoxY, RE02NestedPhantomParameterisation, G4VNestedParameterisation, G4ParameterisationPolyhedraRho, G4ParameterisationPolyconeRho, DicomNestedPhantomParameterisation, G4ParameterisationTubsRho, G4ParameterisationTrdX, ChromosomeParameterisation, G4PhantomParameterisation, RE04ParallelWorldParam, G4ParameterisationParaX, G4ParameterisationBoxX, G02ChamberParameterisation, ExP01ChamberParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, CellParameterisation, RE01TrackerParametrisation, RE05CalorimeterParametrisation, RE01CalorimeterParametrisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, VoxelParam, VoxelParam, and VoxelParam.
Definition at line 110 of file G4VPVParameterisation.hh.
ComputeDimensions() [3/13]
virtual void G4VPVParameterisation::ComputeDimensions (G4Ellipsoid & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationPolyhedraZ, G4ParameterisationPolyconeZ, G4ParameterisationTrdZ, G4ParameterisationParaZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationBoxZ, G4ParameterisationPolyhedraPhi, G4ParameterisationTrdY, G4ParameterisationPolyconePhi, G4ParameterisationConsPhi, G4ParameterisationParaY, G4ParameterisationTubsPhi, G4ParameterisationBoxY, RE02NestedPhantomParameterisation, G4VNestedParameterisation, ChromosomeParameterisation, DicomNestedPhantomParameterisation, G4ParameterisationPolyhedraRho, G4ParameterisationTrdX, G4ParameterisationPolyconeRho, G4ParameterisationConsRho, G4ParameterisationParaX, G4ParameterisationTubsRho, G4PhantomParameterisation, RE04ParallelWorldParam, G4ParameterisationBoxX, UltraFresnelLensParameterisation, G02ChamberParameterisation, ExP01ChamberParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, CellParameterisation, RE05CalorimeterParametrisation, RE01TrackerParametrisation, RE01CalorimeterParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, VoxelParam, VoxelParam, and VoxelParam.
Definition at line 122 of file G4VPVParameterisation.hh.
ComputeDimensions() [4/13]
virtual void G4VPVParameterisation::ComputeDimensions (G4Hype & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationPolyhedraZ, G4ParameterisationPolyconeZ, G4ParameterisationTrdZ, G4ParameterisationParaZ, G4ParameterisationBoxZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationPolyhedraPhi, G4ParameterisationTrdY, G4ParameterisationPolyconePhi, G4VNestedParameterisation, G4ParameterisationParaY, G4ParameterisationBoxY, G4ParameterisationConsPhi, G4ParameterisationTubsPhi, RE02NestedPhantomParameterisation, DicomNestedPhantomParameterisation, ChromosomeParameterisation, G4ParameterisationPolyhedraRho, G4ParameterisationTrdX, G4ParameterisationPolyconeRho, G4ParameterisationConsRho, G4ParameterisationParaX, G4ParameterisationBoxX, G4ParameterisationTubsRho, G4PhantomParameterisation, RE04ParallelWorldParam, CellParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, UltraFresnelLensParameterisation, G02ChamberParameterisation, ExP01ChamberParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, RE05CalorimeterParametrisation, RE01TrackerParametrisation, RE01CalorimeterParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, VoxelParam, VoxelParam, and VoxelParam.
Definition at line 142 of file G4VPVParameterisation.hh.
ComputeDimensions() [5/13]
virtual void G4VPVParameterisation::ComputeDimensions (G4Orb & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationPolyhedraZ, G4ParameterisationPolyconeZ, G4ParameterisationTrdZ, G4ParameterisationParaZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationBoxZ, G4ParameterisationPolyhedraPhi, G4ParameterisationTrdY, G4ParameterisationPolyconePhi, G4ParameterisationConsPhi, G4ParameterisationParaY, G4ParameterisationTubsPhi, G4ParameterisationBoxY, RE02NestedPhantomParameterisation, G4VNestedParameterisation, DicomNestedPhantomParameterisation, G4ParameterisationPolyhedraRho, G4ParameterisationTrdX, ChromosomeParameterisation, G4ParameterisationPolyconeRho, G4ParameterisationConsRho, G4ParameterisationParaX, G4ParameterisationTubsRho, G4ParameterisationBoxX, G4PhantomParameterisation, RE04ParallelWorldParam, G02ChamberParameterisation, UltraFresnelLensParameterisation, ExP01ChamberParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, RE01TrackerParametrisation, RE01CalorimeterParametrisation, CellParameterisation, RE05CalorimeterParametrisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, VoxelParam, VoxelParam, and VoxelParam.
Definition at line 118 of file G4VPVParameterisation.hh.
ComputeDimensions() [6/13]
virtual void G4VPVParameterisation::ComputeDimensions (G4Para & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationParaZ, G4ParameterisationParaY, G4ParameterisationParaX, G4ParameterisationPolyhedraZ, G4ParameterisationPolyconeZ, G4ParameterisationTrdZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationBoxZ, G4ParameterisationPolyhedraPhi, G4ParameterisationTrdY, G4ParameterisationPolyconePhi, G4ParameterisationConsPhi, G4ParameterisationTubsPhi, G4ParameterisationBoxY, G4VNestedParameterisation, RE02NestedPhantomParameterisation, DicomNestedPhantomParameterisation, ChromosomeParameterisation, G4ParameterisationPolyhedraRho, G4ParameterisationTrdX, G4ParameterisationPolyconeRho, G4ParameterisationConsRho, G4ParameterisationTubsRho, G4PhantomParameterisation, RE04ParallelWorldParam, G4ParameterisationBoxX, UltraFresnelLensParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, G02ChamberParameterisation, ExP01ChamberParameterisation, CellParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, RE05CalorimeterParametrisation, RE01TrackerParametrisation, RE01CalorimeterParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, VoxelParam, VoxelParam, and VoxelParam.
Definition at line 130 of file G4VPVParameterisation.hh.
ComputeDimensions() [7/13]
virtual void G4VPVParameterisation::ComputeDimensions (G4Polycone & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationPolyconeZ, G4ParameterisationPolyconePhi, G4ParameterisationPolyconeRho, G4ParameterisationPolyhedraZ, G4ParameterisationTrdZ, G4ParameterisationParaZ, G4ParameterisationBoxZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationPolyhedraPhi, G4ParameterisationTrdY, G4ParameterisationParaY, G4ParameterisationBoxY, G4ParameterisationConsPhi, G4ParameterisationTubsPhi, G4VNestedParameterisation, RE02NestedPhantomParameterisation, DicomNestedPhantomParameterisation, ChromosomeParameterisation, G4ParameterisationPolyhedraRho, G4ParameterisationTrdX, G4ParameterisationConsRho, G4ParameterisationParaX, G4ParameterisationBoxX, G4ParameterisationTubsRho, RE04ParallelWorldParam, G4PhantomParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, G02ChamberParameterisation, UltraFresnelLensParameterisation, CellParameterisation, ExP01ChamberParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, RE01TrackerParametrisation, RE05CalorimeterParametrisation, RE01CalorimeterParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, VoxelParam, VoxelParam, and VoxelParam.
Definition at line 134 of file G4VPVParameterisation.hh.
ComputeDimensions() [8/13]
virtual void G4VPVParameterisation::ComputeDimensions (G4Polyhedra & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationPolyhedraZ, G4ParameterisationPolyhedraPhi, G4ParameterisationPolyhedraRho, G4ParameterisationPolyconeZ, G4ParameterisationTrdZ, G4ParameterisationParaZ, G4ParameterisationBoxZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationTrdY, G4ParameterisationPolyconePhi, G4ParameterisationParaY, G4ParameterisationBoxY, G4ParameterisationConsPhi, G4ParameterisationTubsPhi, G4VNestedParameterisation, RE02NestedPhantomParameterisation, ChromosomeParameterisation, DicomNestedPhantomParameterisation, G4ParameterisationTrdX, G4ParameterisationPolyconeRho, G4ParameterisationConsRho, G4ParameterisationParaX, G4ParameterisationBoxX, G4ParameterisationTubsRho, RE04ParallelWorldParam, G4PhantomParameterisation, CellParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, G02ChamberParameterisation, UltraFresnelLensParameterisation, ExP01ChamberParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, RE01TrackerParametrisation, RE05CalorimeterParametrisation, RE01CalorimeterParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, RE05TrackerParametrisation, VoxelParam, VoxelParam, VoxelParam, ExN04CalorimeterParametrisation, and ExN04TrackerParametrisation.
Definition at line 138 of file G4VPVParameterisation.hh.
ComputeDimensions() [9/13]
virtual void G4VPVParameterisation::ComputeDimensions (G4Sphere & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationPolyhedraZ, G4ParameterisationPolyconeZ, G4ParameterisationTrdZ, G4ParameterisationParaZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationBoxZ, G4ParameterisationPolyhedraPhi, G4ParameterisationTrdY, G4ParameterisationPolyconePhi, G4ParameterisationConsPhi, G4ParameterisationParaY, G4ParameterisationTubsPhi, G4ParameterisationBoxY, RE02NestedPhantomParameterisation, G4VNestedParameterisation, DicomNestedPhantomParameterisation, G4ParameterisationPolyhedraRho, G4ParameterisationTrdX, G4ParameterisationPolyconeRho, ChromosomeParameterisation, G4ParameterisationConsRho, G4PhantomParameterisation, RE04ParallelWorldParam, G4ParameterisationParaX, G4ParameterisationTubsRho, G4ParameterisationBoxX, UltraFresnelLensParameterisation, G02ChamberParameterisation, ExP01ChamberParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, CellParameterisation, RE05CalorimeterParametrisation, RE01TrackerParametrisation, RE01CalorimeterParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, VoxelParam, VoxelParam, and VoxelParam.
Definition at line 114 of file G4VPVParameterisation.hh.
ComputeDimensions() [10/13]
virtual void G4VPVParameterisation::ComputeDimensions (G4Torus & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationPolyhedraZ, G4ParameterisationPolyconeZ, G4ParameterisationTrdZ, G4ParameterisationParaZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationBoxZ, G4ParameterisationPolyhedraPhi, G4ParameterisationTrdY, G4ParameterisationPolyconePhi, G4ParameterisationConsPhi, G4ParameterisationParaY, G4ParameterisationTubsPhi, G4ParameterisationBoxY, G4VNestedParameterisation, RE02NestedPhantomParameterisation, DicomNestedPhantomParameterisation, G4ParameterisationPolyhedraRho, G4ParameterisationTrdX, ChromosomeParameterisation, G4ParameterisationPolyconeRho, G4ParameterisationConsRho, G4ParameterisationParaX, G4ParameterisationTubsRho, G4PhantomParameterisation, RE04ParallelWorldParam, G4ParameterisationBoxX, UltraFresnelLensParameterisation, G02ChamberParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, ExP01ChamberParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, CellParameterisation, RE05CalorimeterParametrisation, RE01TrackerParametrisation, RE01CalorimeterParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, VoxelParam, VoxelParam, and VoxelParam.
Definition at line 126 of file G4VPVParameterisation.hh.
ComputeDimensions() [11/13]
virtual void G4VPVParameterisation::ComputeDimensions (G4Trap & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationTrdX, G4ParameterisationPolyhedraZ, G4ParameterisationTrdZ, G4ParameterisationPolyconeZ, G4ParameterisationParaZ, G4ParameterisationBoxZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationTrdY, G4ParameterisationPolyhedraPhi, G4ParameterisationParaY, G4ParameterisationBoxY, G4ParameterisationPolyconePhi, G4ParameterisationConsPhi, G4ParameterisationTubsPhi, RE02NestedPhantomParameterisation, G4VNestedParameterisation, DicomNestedPhantomParameterisation, G4ParameterisationParaX, G4ParameterisationPolyhedraRho, G4ParameterisationBoxX, G4ParameterisationPolyconeRho, ChromosomeParameterisation, G4ParameterisationConsRho, G4ParameterisationTubsRho, G4PhantomParameterisation, RE04ParallelWorldParam, UltraFresnelLensParameterisation, G02ChamberParameterisation, ExP01ChamberParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, RE01TrackerParametrisation, RE05CalorimeterParametrisation, RE01CalorimeterParametrisation, RE05TrackerParametrisation, CellParameterisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, VoxelParam, VoxelParam, and VoxelParam.
Definition at line 106 of file G4VPVParameterisation.hh.
ComputeDimensions() [12/13]
virtual void G4VPVParameterisation::ComputeDimensions (G4Trd & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationTrdZ, G4ParameterisationTrdY, G4ParameterisationTrdX, G4ParameterisationPolyhedraZ, G4ParameterisationPolyconeZ, G4ParameterisationParaZ, G4ParameterisationBoxZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationPolyhedraPhi, G4ParameterisationParaY, G4ParameterisationPolyconePhi, G4ParameterisationBoxY, G4ParameterisationConsPhi, G4ParameterisationTubsPhi, RE02NestedPhantomParameterisation, G4VNestedParameterisation, DicomNestedPhantomParameterisation, G4ParameterisationParaX, G4ParameterisationPolyhedraRho, G4ParameterisationPolyconeRho, ChromosomeParameterisation, G4ParameterisationBoxX, G4ParameterisationConsRho, G4ParameterisationTubsRho, G4PhantomParameterisation, RE04ParallelWorldParam, UltraFresnelLensParameterisation, G02ChamberParameterisation, ExP01ChamberParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, RE01TrackerParametrisation, RE05CalorimeterParametrisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, RE01CalorimeterParametrisation, CellParameterisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, VoxelParam, VoxelParam, and VoxelParam.
Definition at line 102 of file G4VPVParameterisation.hh.
ComputeDimensions() [13/13]
virtual void G4VPVParameterisation::ComputeDimensions (G4Tubs & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationTubsZ, G4ParameterisationTubsPhi, G4ParameterisationTubsRho, B2bChamberParameterisation, B2bChamberParameterisation, RE01TrackerParametrisation, RE05TrackerParametrisation, ExN04TrackerParametrisation, ExN04TrackerParametrisation, ChromosomeParameterisation, RE01CalorimeterParametrisation, RE05CalorimeterParametrisation, ExN04CalorimeterParametrisation, ExN04CalorimeterParametrisation, G4ParameterisationPolyhedraZ, G4ParameterisationPolyconeZ, G4ParameterisationTrdZ, G4ParameterisationParaZ, G4ParameterisationBoxZ, G4ParameterisationConsZ, G4ParameterisationPolyhedraPhi, G4ParameterisationTrdY, G4ParameterisationPolyconePhi, G4ParameterisationParaY, G4ParameterisationBoxY, G4ParameterisationConsPhi, RE02NestedPhantomParameterisation, DicomNestedPhantomParameterisation, G4ParameterisationPolyhedraRho, G4ParameterisationTrdX, G4ParameterisationPolyconeRho, G4VNestedParameterisation, G4ParameterisationConsRho, G4ParameterisationParaX, G4ParameterisationBoxX, RE04ParallelWorldParam, G02ChamberParameterisation, ExP01ChamberParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, G4PhantomParameterisation, UltraFresnelLensParameterisation, VoxelParam, VoxelParam, VoxelParam, and CellParameterisation.
Definition at line 98 of file G4VPVParameterisation.hh.
ComputeMaterial()
G4Material * G4VPVParameterisation::ComputeMaterial (const G4int repNo, G4VPhysicalVolume * currentVol, const G4VTouchable * parentTouch = 0) virtual
Reimplemented in G4VNestedParameterisation, G4PhantomParameterisation, G4PartialPhantomParameterisation, DicomPhantomParameterisationColour, CellParameterisation, and RE04ParallelWorldParam.
Definition at line 53 of file G4VPVParameterisation.cc.
Referenced by G4tgbGeometryDumper::DumpPVParameterised(), G4LogicalVolume::GetMass(), G4ParameterisedNavigation::LevelLocate(), and G4Region::ScanVolumeTree().
ComputeSolid()
G4VSolid * G4VPVParameterisation::ComputeSolid (const G4int, G4VPhysicalVolume * pPhysicalVol) virtual
Reimplemented in G4ParameterisationTrdX, G4PhantomParameterisation, G4VDivisionParameterisation, and G4VNestedParameterisation.
Definition at line 46 of file G4VPVParameterisation.cc.
Referenced by G4SmartVoxelHeader::BuildNodes(), G4PVParameterised::CheckOverlaps(), G4VDivisionParameterisation::ComputeSolid(), G4PSDoseDeposit::ComputeVolume(), G4PSPassageCellFlux::ComputeVolume(), G4PSCellFlux::ComputeVolume(), G4ScoreSplittingProcess::CreateTouchableForSubStep(), G4tgbGeometryDumper::DumpPVParameterised(), G4LogicalVolume::GetMass(), G4Navigator::GetMotherToDaughterTransform(), G4ITNavigator1::GetMotherToDaughterTransform(), G4ITNavigator2::GetMotherToDaughterTransform(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITNavigator2::LocateGlobalPointAndSetup(), G4PSSphereSurfaceCurrent::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSFlatSurfaceCurrent::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), G4Navigator::SetupHierarchy(), G4ITNavigator1::SetupHierarchy(), and G4ITNavigator2::SetupHierarchy().
ComputeTransformation()
virtual void G4VPVParameterisation::ComputeTransformation (const G4int, G4VPhysicalVolume *) const pure virtual
Implemented in G4GDMLParameterisation, G4PhantomParameterisation, G4PartialPhantomParameterisation, G4tgbPlaceParameterisation, G4VNestedParameterisation, RE02NestedPhantomParameterisation, DicomNestedPhantomParameterisation, VoxelParam, VoxelParam, VoxelParam, UltraFresnelLensParameterisation, G4VDivisionParameterisation, G4ParameterisationPolyhedraZ, G4ParameterisationTrdZ, G4ParameterisationPolyconeZ, G4ParameterisationParaZ, G4ParameterisationBoxZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationPolyhedraPhi, G4ParameterisationTrdY, G4ParameterisationPolyconePhi, G4ParameterisationParaY, G4ParameterisationConsPhi, G4ParameterisationBoxY, G4ParameterisationTubsPhi, G4ParameterisationPolyhedraRho, G4ParameterisationTrdX, G4ParameterisationPolyconeRho, G4ParameterisationConsRho, G4ParameterisationBoxX, G4ParameterisationParaX, G4ParameterisationTubsRho, ChromosomeParameterisation, G02ChamberParameterisation, ExP01ChamberParameterisation, RE04ParallelWorldParam, ExN02ChamberParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, RE01CalorimeterParametrisation, RE01TrackerParametrisation, RE05CalorimeterParametrisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, G4tgbPlaceParamCircle, G4tgbPlaceParamLinear, G4EzVoxelParameterization, CellParameterisation, G4tgbPlaceParamSquare, and B5CellParameterisation.
Referenced by G4SmartVoxelHeader::BuildNodes(), G4PVParameterised::CheckOverlaps(), G4ScoreSplittingProcess::CreateTouchableForSubStep(), G4tgbGeometryDumper::DumpPVParameterised(), G4Navigator::GetMotherToDaughterTransform(), G4ITNavigator1::GetMotherToDaughterTransform(), G4ITNavigator2::GetMotherToDaughterTransform(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITNavigator2::LocateGlobalPointAndSetup(), G4GDMLWriteParamvol::ParametersWrite(), G4Navigator::SetupHierarchy(), G4ITNavigator1::SetupHierarchy(), and G4ITNavigator2::SetupHierarchy().
GetMaterialScanner()
G4VVolumeMaterialScanner * G4VPVParameterisation::GetMaterialScanner () virtual
Reimplemented in G4VNestedParameterisation.
Definition at line 67 of file G4VPVParameterisation.cc.
Referenced by G4Region::ScanVolumeTree().
IsNested()
G4bool G4VPVParameterisation::IsNested () const virtual
Reimplemented in G4VNestedParameterisation.
Definition at line 61 of file G4VPVParameterisation.cc.
Referenced by G4GMocrenFileSceneHandler::AddSolid(), G4Navigator::SetupHierarchy(), and G4ITNavigator2::SetupHierarchy().
The documentation for this class was generated from the following files:
source/geometry/management/include/G4VPVParameterisation.hh
source/geometry/management/src/G4VPVParameterisation.cc