Geant4: CCalEcal Class Reference
CCalEcal Class Reference
#include <CCalEcal.hh>
Public Member Functions
CCalEcal (const G4String &name)
virtual ~CCalEcal ()
G4String getGenMat () const
double getWidBox () const
double getLengBox () const
double getXpos () const
double getYpos () const
double getZpos () const
double getThetaX () const
double getPhiX () const
double getThetaY () const
double getPhiY () const
double getThetaZ () const
double getPhiZ () const
G4String getLayMat () const
int getLayNum () const
double getLayRadius () const
double getLayAngle () const
double getLengFront () const
double getLayPar (unsigned int i) const
G4String getCrystMat () const
int getCrystNum () const
double getCrystLength () const
double getCrystTol () const
double getCrystPar (unsigned int i) const
G4String getSuppMat () const
double getDxSupp () const
double getDySupp () const
double getDzSupp () const
double getDistSupp () const
Public Member Functions inherited from CCalDetector
CCalDetector (const G4String &name)
virtual ~CCalDetector ()
void constructHierarchy ()
void construct ()
void addDetector (CCalDetector *)
G4String Name () const
G4String baseFileName () const
G4String File () const
CCalDetector * getDaughter (int i) const
int getNDaughters () const
G4bool operator== (const CCalDetector &left) const
G4bool operator!= (const CCalDetector &left) const
Protected Member Functions
virtual int readFile ()
virtual void constructDaughters ()
Protected Member Functions inherited from CCalDetector
int buildFromFile ()
Private Attributes
G4String genMat
double widBox
double lengBox
double xpos
double ypos
double zpos
double thetaX
double phiX
double thetaY
double phiY
double thetaZ
double phiZ
G4String layMat
int layNum
double layRadius
double layAngle
double lengFront
double layPar [5]
G4String crystMat
int crystNum
double crystLength
double crystTol
double crystPar [5]
G4String suppMat
double dxSupp
double dySupp
double dzSupp
double distSupp
Additional Inherited Members
Protected Attributes inherited from CCalDetector
G4String detectorName
G4String fileName
G4String pathName
CCalDetectorTable theDetectorsInside
int constructFlag
Detailed Description
Definition at line 35 of file CCalEcal.hh.
Constructor & Destructor Documentation
CCalEcal()
CCalEcal::CCalEcal (const G4String & name) inline
Definition at line 38 of file CCalEcal.hh.
~CCalEcal()
CCalEcal::~CCalEcal () virtual
Definition at line 37 of file CCalEcal.cc.
Member Function Documentation
constructDaughters()
void CCalEcal::constructDaughters () protected virtual
Implements CCalDetector.
Definition at line 111 of file CCalEcal.cc.
getCrystLength()
double CCalEcal::getCrystLength () const inline
Definition at line 63 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructGlobal().
getCrystMat()
G4String CCalEcal::getCrystMat () const inline
Definition at line 61 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructGlobal().
getCrystNum()
int CCalEcal::getCrystNum () const inline
Definition at line 62 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructGlobal().
getCrystPar()
double CCalEcal::getCrystPar (unsigned int i) const inline
Definition at line 65 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructGlobal().
getCrystTol()
double CCalEcal::getCrystTol () const inline
Definition at line 64 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructGlobal().
getDistSupp()
double CCalEcal::getDistSupp () const inline
Definition at line 70 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructGlobal().
getDxSupp()
double CCalEcal::getDxSupp () const inline
Definition at line 67 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructGlobal().
getDySupp()
double CCalEcal::getDySupp () const inline
Definition at line 68 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructGlobal().
getDzSupp()
double CCalEcal::getDzSupp () const inline
Definition at line 69 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructGlobal().
getGenMat()
G4String CCalEcal::getGenMat () const inline
Definition at line 43 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructGlobal().
getLayAngle()
double CCalEcal::getLayAngle () const inline
Definition at line 58 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructGlobal().
getLayMat()
G4String CCalEcal::getLayMat () const inline
Definition at line 55 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructGlobal().
getLayNum()
int CCalEcal::getLayNum () const inline
Definition at line 56 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructGlobal().
getLayPar()
double CCalEcal::getLayPar (unsigned int i) const inline
Definition at line 60 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructGlobal().
getLayRadius()
double CCalEcal::getLayRadius () const inline
Definition at line 57 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructGlobal().
getLengBox()
double CCalEcal::getLengBox () const inline
Definition at line 45 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructGlobal().
getLengFront()
double CCalEcal::getLengFront () const inline
Definition at line 59 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructGlobal().
getPhiX()
double CCalEcal::getPhiX () const inline
Definition at line 50 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructIn().
getPhiY()
double CCalEcal::getPhiY () const inline
Definition at line 52 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructIn().
getPhiZ()
double CCalEcal::getPhiZ () const inline
Definition at line 54 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructIn().
getSuppMat()
G4String CCalEcal::getSuppMat () const inline
Definition at line 66 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructGlobal().
getThetaX()
double CCalEcal::getThetaX () const inline
Definition at line 49 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructIn().
getThetaY()
double CCalEcal::getThetaY () const inline
Definition at line 51 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructIn().
getThetaZ()
double CCalEcal::getThetaZ () const inline
Definition at line 53 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructIn().
getWidBox()
double CCalEcal::getWidBox () const inline
Definition at line 44 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructGlobal().
getXpos()
double CCalEcal::getXpos () const inline
Definition at line 46 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructIn().
getYpos()
double CCalEcal::getYpos () const inline
Definition at line 47 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructIn().
getZpos()
double CCalEcal::getZpos () const inline
Definition at line 48 of file CCalEcal.hh.
Referenced by CCalG4Ecal::constructIn().
readFile()
int CCalEcal::readFile () protected virtual
Implements CCalDetector.
Definition at line 39 of file CCalEcal.cc.
Field Documentation
crystLength
double CCalEcal::crystLength private
Definition at line 89 of file CCalEcal.hh.
Referenced by getCrystLength(), and readFile().
crystMat
G4String CCalEcal::crystMat private
Definition at line 87 of file CCalEcal.hh.
Referenced by getCrystMat(), and readFile().
crystNum
int CCalEcal::crystNum private
Definition at line 88 of file CCalEcal.hh.
Referenced by getCrystNum(), and readFile().
crystPar
double CCalEcal::crystPar[5] private
Definition at line 91 of file CCalEcal.hh.
Referenced by getCrystPar(), and readFile().
crystTol
double CCalEcal::crystTol private
Definition at line 90 of file CCalEcal.hh.
Referenced by getCrystTol(), and readFile().
distSupp
double CCalEcal::distSupp private
Definition at line 94 of file CCalEcal.hh.
Referenced by getDistSupp(), and readFile().
dxSupp
double CCalEcal::dxSupp private
Definition at line 93 of file CCalEcal.hh.
Referenced by getDxSupp(), and readFile().
dySupp
double CCalEcal::dySupp private
Definition at line 93 of file CCalEcal.hh.
Referenced by getDySupp(), and readFile().
dzSupp
double CCalEcal::dzSupp private
Definition at line 93 of file CCalEcal.hh.
Referenced by getDzSupp(), and readFile().
genMat
G4String CCalEcal::genMat private
Definition at line 78 of file CCalEcal.hh.
Referenced by getGenMat(), and readFile().
layAngle
double CCalEcal::layAngle private
Definition at line 84 of file CCalEcal.hh.
Referenced by getLayAngle(), and readFile().
layMat
G4String CCalEcal::layMat private
Definition at line 82 of file CCalEcal.hh.
Referenced by getLayMat(), and readFile().
layNum
int CCalEcal::layNum private
Definition at line 83 of file CCalEcal.hh.
Referenced by getLayNum(), and readFile().
layPar
double CCalEcal::layPar[5] private
Definition at line 86 of file CCalEcal.hh.
Referenced by getLayPar(), and readFile().
layRadius
double CCalEcal::layRadius private
Definition at line 84 of file CCalEcal.hh.
Referenced by getLayRadius(), and readFile().
lengBox
double CCalEcal::lengBox private
Definition at line 79 of file CCalEcal.hh.
Referenced by getLengBox(), and readFile().
lengFront
double CCalEcal::lengFront private
Definition at line 85 of file CCalEcal.hh.
Referenced by getLengFront(), and readFile().
phiX
double CCalEcal::phiX private
Definition at line 81 of file CCalEcal.hh.
Referenced by getPhiX(), and readFile().
phiY
double CCalEcal::phiY private
Definition at line 81 of file CCalEcal.hh.
Referenced by getPhiY(), and readFile().
phiZ
double CCalEcal::phiZ private
Definition at line 81 of file CCalEcal.hh.
Referenced by getPhiZ(), and readFile().
suppMat
G4String CCalEcal::suppMat private
Definition at line 92 of file CCalEcal.hh.
Referenced by getSuppMat(), and readFile().
thetaX
double CCalEcal::thetaX private
Definition at line 81 of file CCalEcal.hh.
Referenced by getThetaX(), and readFile().
thetaY
double CCalEcal::thetaY private
Definition at line 81 of file CCalEcal.hh.
Referenced by getThetaY(), and readFile().
thetaZ
double CCalEcal::thetaZ private
Definition at line 81 of file CCalEcal.hh.
Referenced by getThetaZ(), and readFile().
widBox
double CCalEcal::widBox private
Definition at line 79 of file CCalEcal.hh.
Referenced by getWidBox(), and readFile().
xpos
double CCalEcal::xpos private
Definition at line 80 of file CCalEcal.hh.
Referenced by getXpos(), and readFile().
ypos
double CCalEcal::ypos private
Definition at line 80 of file CCalEcal.hh.
Referenced by getYpos(), and readFile().
zpos
double CCalEcal::zpos private
Definition at line 80 of file CCalEcal.hh.
Referenced by getZpos(), and readFile().
The documentation for this class was generated from the following files:
examples/advanced/composite_calorimeter/include/CCalEcal.hh
examples/advanced/composite_calorimeter/src/CCalEcal.cc