Geant4: G4H2 Class Reference
G4H2 Class Reference
#include <G4H2.hh>
Static Public Member Functions
static G4H2 * Definition ()
Static Public Member Functions inherited from G4MoleculeDefinition
static G4MoleculeDefinition * Load (std::istream &)
Static Public Member Functions inherited from G4ParticleDefinition
static const G4PDefManager & GetSubInstanceManager ()
static void Clean ()
Private Member Functions
G4H2 ()
virtual ~G4H2 ()
Static Private Attributes
static G4H2 * theInstance = 0
Additional Inherited Members
Public Member Functions inherited from G4MoleculeDefinition
G4MoleculeDefinition (const G4String &name, G4double mass, G4double diffCoeff, G4int charge=0, G4int electronicLevels=0, G4double radius=-1, G4int atomsNumber=-1, G4double lifetime=-1, G4String aType="", G4FakeParticleID ID=G4FakeParticleID::Create())
virtual ~G4MoleculeDefinition ()
void SetLevelOccupation (G4int, G4int eNb=2)
void SetDiffusionCoefficient (G4double)
G4double GetDiffusionCoefficient () const
void SetAtomsNumber (G4int)
G4int GetAtomsNumber () const
void SetVanDerVaalsRadius (G4double)
G4double GetVanDerVaalsRadius () const
G4MolecularConfiguration * NewConfiguration (const G4String &excitedStateLabel)
G4MolecularConfiguration * NewConfigurationWithElectronOccupancy (const G4String &excitedStateLabel, const G4ElectronOccupancy &, double decayTime=0.)
G4MolecularConfiguration * GetConfigurationWithLabel (const G4String &molecularConfLabel)
void AddDecayChannel (const G4MolecularConfiguration *molConf, const G4MolecularDissociationChannel *channel)
void AddDecayChannel (const G4String &molecularConfLabel, const G4MolecularDissociationChannel *channel)
const std::vector< const G4MolecularDissociationChannel * > * GetDecayChannels (const G4MolecularConfiguration *) const
const std::vector< const G4MolecularDissociationChannel * > * GetDecayChannels (const G4String &) const
const G4MolecularDissociationTable * GetDecayTable () const
G4MolecularDissociationTable * GetDecayTable ()
G4double GetDecayTime () const
const G4ElectronOccupancy * GetGroundStateElectronOccupancy () const
G4int GetCharge () const
const G4String & GetName () const
G4double GetMass () const
const G4String & GetType () const
G4int GetNbElectrons () const
G4int GetNbMolecularShells () const
const G4String & GetFormatedName () const
void SetFormatedName (const G4String &name)
void Finalize ()
void Serialize (std::ostream &)
Public Member Functions inherited from G4ParticleDefinition
G4ParticleDefinition (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospinZ, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable, G4bool shortlived=false, const G4String &subType="", G4int anti_encoding=0, G4double magneticMoment=0.0)
virtual ~G4ParticleDefinition ()
const G4String & GetParticleName () const
G4double GetPDGMass () const
G4double GetPDGWidth () const
G4double GetPDGCharge () const
G4double GetPDGSpin () const
G4int GetPDGiSpin () const
G4int GetPDGiParity () const
G4int GetPDGiConjugation () const
G4double GetPDGIsospin () const
G4double GetPDGIsospin3 () const
G4int GetPDGiIsospin () const
G4int GetPDGiIsospin3 () const
G4int GetPDGiGParity () const
G4double GetPDGMagneticMoment () const
void SetPDGMagneticMoment (G4double mageticMoment)
G4double CalculateAnomaly () const
const G4String & GetParticleType () const
const G4String & GetParticleSubType () const
G4int GetLeptonNumber () const
G4int GetBaryonNumber () const
G4int GetPDGEncoding () const
G4int GetAntiPDGEncoding () const
void SetAntiPDGEncoding (G4int aEncoding)
G4int GetQuarkContent (G4int flavor) const
G4int GetAntiQuarkContent (G4int flavor) const
G4bool IsShortLived () const
G4bool GetPDGStable () const
void SetPDGStable (const G4bool aFlag)
G4double GetPDGLifeTime () const
void SetPDGLifeTime (G4double aLifeTime)
G4double GetIonLifeTime () const
G4DecayTable * GetDecayTable () const
void SetDecayTable (G4DecayTable *aDecayTable)
G4ProcessManager * GetProcessManager () const
void SetProcessManager (G4ProcessManager *aProcessManager)
G4ParticleTable * GetParticleTable () const
G4int GetAtomicNumber () const
G4int GetAtomicMass () const
void DumpTable () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetApplyCutsFlag (G4bool)
G4bool GetApplyCutsFlag () const
G4bool IsGeneralIon () const
G4bool IsMuonicAtom () const
G4bool operator== (const G4ParticleDefinition &right) const
G4bool operator!= (const G4ParticleDefinition &right) const
G4ProcessManager * GetMasterProcessManager () const
void SetMasterProcessManager (G4ProcessManager *aNewPM)
G4int GetInstanceID () const
void SetParticleDefinitionID (G4int id=-1)
G4int GetParticleDefinitionID () const
Protected Types inherited from G4ParticleDefinition
enum { NumberOfQuarkFlavor = 6 }
Protected Member Functions inherited from G4MoleculeDefinition
G4MoleculeDefinition ()
G4MoleculeDefinition (const G4MoleculeDefinition &)
Protected Member Functions inherited from G4ParticleDefinition
G4int FillQuarkContents ()
void SetParticleSubType (const G4String &subtype)
void SetAtomicNumber (G4int)
void SetAtomicMass (G4int)
G4ParticleDefinition (const G4ParticleDefinition &right)
G4ParticleDefinition ()
Protected Attributes inherited from G4ParticleDefinition
G4int theQuarkContent [NumberOfQuarkFlavor]
G4int theAntiQuarkContent [NumberOfQuarkFlavor]
G4bool isGeneralIon
G4bool isMuonicAtom
Detailed Description
Definition at line 59 of file G4H2.hh.
Constructor & Destructor Documentation
G4H2()
G4H2::G4H2 () inline private
Definition at line 63 of file G4H2.hh.
Member Function Documentation
Definition()
G4H2 * G4H2::Definition () static
Definition at line 45 of file G4H2.cc.
Referenced by G4EmDNAChemistry::ConstructMolecule(), G4EmDNAChemistry_option1::ConstructMolecule(), and G4DNAWaterDissociationDisplacer::GetProductsDisplacement().
~G4H2()
virtual G4H2::~G4H2 () inline private virtual
Definition at line 64 of file G4H2.hh.
Field Documentation
theInstance
G4H2 * G4H2::theInstance = 0 static private
Definition at line 62 of file G4H2.hh.
Referenced by Definition().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/dna/molecules/types/include/G4H2.hh
source/processes/electromagnetic/dna/molecules/types/src/G4H2.cc