Geant4: G4VisModelManager< Model > Class Template Reference
G4VisModelManager< Model > Class Template Reference
#include <G4VisManager.hh>
Public Types
typedef G4VisListManager< Model > List
typedef G4VModelFactory< Model > Factory
Public Member Functions
G4VisModelManager (const G4String &)
virtual ~G4VisModelManager ()
void Register (Model *)
void Register (Factory *)
void SetCurrent (const G4String &)
const Model * Current () const
G4String Placement () const
void Print (std::ostream &ostr, const G4String &name="") const
const List * ListManager () const
const std::vector< Factory * > & FactoryList () const
Private Member Functions
G4VisModelManager (const G4VisModelManager &)
G4VisModelManager & operator= (const G4VisModelManager &)
Private Attributes
G4String fPlacement
List * fpModelList
std::vector< Factory * > fFactoryList
std::vector< G4UImessenger * > fMessengerList
Detailed Description
template<typename Model>
class G4VisModelManager< Model >
Definition at line 113 of file G4VisManager.hh.
Member Typedef Documentation
Factory
template<typename Model> typedef G4VModelFactory<Model> G4VisModelManager< Model >::Factory
Definition at line 48 of file G4VisModelManager.hh.
List
template<typename Model> typedef G4VisListManager<Model> G4VisModelManager< Model >::List
Definition at line 47 of file G4VisModelManager.hh.
Constructor & Destructor Documentation
G4VisModelManager() [1/2]
template<typename Model > G4VisModelManager< Model >::G4VisModelManager (const G4String & placement)
Definition at line 87 of file G4VisModelManager.hh.
~G4VisModelManager()
template<typename Model > G4VisModelManager< Model >::~G4VisModelManager () virtual
Definition at line 93 of file G4VisModelManager.hh.
G4VisModelManager() [2/2]
template<typename Model> G4VisModelManager< Model >::G4VisModelManager (const G4VisModelManager< Model > &) private
Member Function Documentation
Current()
template<typename Model > const Model * G4VisModelManager< Model >::Current () const
Definition at line 140 of file G4VisModelManager.hh.
Referenced by G4VisManager::CurrentTrajDrawModel().
FactoryList()
template<typename Model > const std::vector< G4VModelFactory< Model > * > & G4VisModelManager< Model >::FactoryList () const
Definition at line 182 of file G4VisModelManager.hh.
Referenced by G4VisManager::PrintAvailableModels().
ListManager()
template<typename Model > const G4VisListManager< Model > * G4VisModelManager< Model >::ListManager () const
Definition at line 175 of file G4VisModelManager.hh.
Referenced by G4VisManager::PrintAvailableModels().
operator=()
template<typename Model> G4VisModelManager& G4VisModelManager< Model >::operator= (const G4VisModelManager< Model > &) private
Placement()
template<typename Model > G4String G4VisModelManager< Model >::Placement () const
Definition at line 147 of file G4VisModelManager.hh.
Referenced by G4VisManager::RegisterMessengers().
Print()
template<typename Model > void G4VisModelManager< Model >::Print (std::ostream & ostr, const G4String & name = "") const
Definition at line 154 of file G4VisModelManager.hh.
Register() [1/2]
template<typename Model> void G4VisModelManager< Model >::Register (Factory * factory)
Definition at line 122 of file G4VisModelManager.hh.
Register() [2/2]
template<typename Model> void G4VisModelManager< Model >::Register (Model * model)
Definition at line 115 of file G4VisModelManager.hh.
Referenced by G4VisManager::CurrentTrajDrawModel(), G4VisManager::RegisterModel(), and G4VisManager::RegisterModelFactory().
SetCurrent()
template<typename Model > void G4VisModelManager< Model >::SetCurrent (const G4String & model)
Definition at line 133 of file G4VisModelManager.hh.
Referenced by G4VisManager::SelectTrajectoryModel().
Field Documentation
fFactoryList
template<typename Model> std::vector<Factory*> G4VisModelManager< Model >::fFactoryList private
Definition at line 81 of file G4VisModelManager.hh.
fMessengerList
template<typename Model> std::vector<G4UImessenger*> G4VisModelManager< Model >::fMessengerList private
Definition at line 82 of file G4VisModelManager.hh.
fPlacement
template<typename Model> G4String G4VisModelManager< Model >::fPlacement private
Definition at line 79 of file G4VisModelManager.hh.
fpModelList
template<typename Model> List* G4VisModelManager< Model >::fpModelList private
Definition at line 80 of file G4VisModelManager.hh.
The documentation for this class was generated from the following files:
source/visualization/management/include/G4VisManager.hh
source/visualization/management/include/G4VisModelManager.hh