Geant4: G4VPHitsCollectionIO Class Reference
G4VPHitsCollectionIO Class Reference abstract
#include <G4VPHitsCollectionIO.hh>
Public Member Functions
G4VPHitsCollectionIO (std::string detName, std::string colName)
virtual ~G4VPHitsCollectionIO ()
virtual G4bool Store (const G4VHitsCollection *)=0
virtual G4bool Retrieve (G4VHitsCollection *&)=0
G4bool operator== (const G4VPHitsCollectionIO &right) const
std::string SDname ()
std::string CollectionName ()
void SetVerboseLevel (int v)
Protected Attributes
G4int m_verbose
std::string f_detName
std::string f_colName
Detailed Description
Definition at line 39 of file G4VPHitsCollectionIO.hh.
Constructor & Destructor Documentation
G4VPHitsCollectionIO()
G4VPHitsCollectionIO::G4VPHitsCollectionIO (std::string detName, std::string colName)
Definition at line 34 of file G4VPHitsCollectionIO.cc.
~G4VPHitsCollectionIO()
virtual G4VPHitsCollectionIO::~G4VPHitsCollectionIO () inline virtual
Definition at line 45 of file G4VPHitsCollectionIO.hh.
Member Function Documentation
CollectionName()
std::string G4VPHitsCollectionIO::CollectionName () inline
Definition at line 65 of file G4VPHitsCollectionIO.hh.
operator==()
G4bool G4VPHitsCollectionIO::operator== (const G4VPHitsCollectionIO & right) const
Definition at line 40 of file G4VPHitsCollectionIO.cc.
Retrieve()
virtual G4bool G4VPHitsCollectionIO::Retrieve (G4VHitsCollection *&) pure virtual
SDname()
std::string G4VPHitsCollectionIO::SDname () inline
Definition at line 62 of file G4VPHitsCollectionIO.hh.
Referenced by G4HCIOcatalog::RegisterHCIOmanager().
SetVerboseLevel()
void G4VPHitsCollectionIO::SetVerboseLevel (int v) inline
Definition at line 68 of file G4VPHitsCollectionIO.hh.
Referenced by G4VPHitIO::SetVerboseLevel(), and G4PersistencyManager::SetVerboseLevel().
Store()
virtual G4bool G4VPHitsCollectionIO::Store (const G4VHitsCollection *) pure virtual
Field Documentation
f_colName
std::string G4VPHitsCollectionIO::f_colName protected
Definition at line 74 of file G4VPHitsCollectionIO.hh.
Referenced by CollectionName(), and operator==().
f_detName
std::string G4VPHitsCollectionIO::f_detName protected
Definition at line 73 of file G4VPHitsCollectionIO.hh.
Referenced by operator==(), and SDname().
m_verbose
G4int G4VPHitsCollectionIO::m_verbose protected
Definition at line 68 of file G4VPHitsCollectionIO.hh.
Referenced by SetVerboseLevel().
The documentation for this class was generated from the following files:
source/persistency/mctruth/include/G4VPHitsCollectionIO.hh
source/persistency/mctruth/src/G4VPHitsCollectionIO.cc