Geant4: G4ModelCommandUtils Namespace Reference
G4ModelCommandUtils Namespace Reference
Functions
void AddContextMsgrs (G4VisTrajContext *context, std::vector< G4UImessenger * > &messengers, const G4String &placement)
Function Documentation
AddContextMsgrs()
void G4ModelCommandUtils::AddContextMsgrs (G4VisTrajContext * context, std::vector< G4UImessenger * > & messengers, const G4String & placement)
Definition at line 41 of file G4ModelCommandUtils.hh.
Referenced by G4ModelCmdAddIntervalContext< M >::Apply(), G4ModelCmdAddValueContext< M >::Apply(), G4TrajectoryDrawByAttributeFactory::Create(), G4TrajectoryDrawByChargeFactory::Create(), G4TrajectoryGenericDrawerFactory::Create(), G4TrajectoryDrawByParticleIDFactory::Create(), G4TrajectoryDrawByOriginVolumeFactory::Create(), and G4TrajectoryDrawByEncounteredVolumeFactory::Create().