Geant4: G4SDStructure Class Reference
G4SDStructure Class Reference
#include <G4SDStructure.hh>
Public Member Functions
G4SDStructure (G4String aPath)
~G4SDStructure ()
G4bool operator== (const G4SDStructure &right) const
void AddNewDetector (G4VSensitiveDetector *aSD, G4String treeStructure)
void Activate (G4String aName, G4bool sensitiveFlag)
void Initialize (G4HCofThisEvent *HCE)
void Terminate (G4HCofThisEvent *HCE)
G4VSensitiveDetector * FindSensitiveDetector (G4String aName, G4bool warning=true)
G4VSensitiveDetector * GetSD (G4String aName)
void ListTree ()
void SetVerboseLevel (G4int vl)
Private Member Functions
G4SDStructure * FindSubDirectory (G4String subD)
G4String ExtractDirName (G4String aPath)
void RemoveSD (G4VSensitiveDetector *)
Private Attributes
std::vector< G4SDStructure * > structure
std::vector< G4VSensitiveDetector * > detector
G4String pathName
G4String dirName
G4int verboseLevel
Detailed Description
Definition at line 46 of file G4SDStructure.hh.
Constructor & Destructor Documentation
G4SDStructure()
G4SDStructure::G4SDStructure (G4String aPath)
Definition at line 33 of file G4SDStructure.cc.
Referenced by AddNewDetector().
~G4SDStructure()
G4SDStructure::~G4SDStructure ()
Definition at line 47 of file G4SDStructure.cc.
Member Function Documentation
Activate()
void G4SDStructure::Activate (G4String aName, G4bool sensitiveFlag)
Definition at line 126 of file G4SDStructure.cc.
Referenced by Activate(), and G4SDManager::Activate().
AddNewDetector()
void G4SDStructure::AddNewDetector (G4VSensitiveDetector * aSD, G4String treeStructure)
Definition at line 60 of file G4SDStructure.cc.
Referenced by AddNewDetector(), and G4SDManager::AddNewDetector().
ExtractDirName()
G4String G4SDStructure::ExtractDirName (G4String aPath) private
Definition at line 118 of file G4SDStructure.cc.
Referenced by Activate(), AddNewDetector(), and FindSensitiveDetector().
FindSensitiveDetector()
G4VSensitiveDetector * G4SDStructure::FindSensitiveDetector (G4String aName, G4bool warning = true)
Definition at line 162 of file G4SDStructure.cc.
Referenced by FindSensitiveDetector(), and G4SDManager::FindSensitiveDetector().
FindSubDirectory()
G4SDStructure * G4SDStructure::FindSubDirectory (G4String subD) private
Definition at line 98 of file G4SDStructure.cc.
Referenced by Activate(), AddNewDetector(), and FindSensitiveDetector().
GetSD()
G4VSensitiveDetector * G4SDStructure::GetSD (G4String aName)
Definition at line 105 of file G4SDStructure.cc.
Referenced by Activate(), AddNewDetector(), and FindSensitiveDetector().
Initialize()
void G4SDStructure::Initialize (G4HCofThisEvent * HCE)
Definition at line 193 of file G4SDStructure.cc.
Referenced by G4SDManager::PrepareNewEvent().
ListTree()
void G4SDStructure::ListTree ()
Definition at line 213 of file G4SDStructure.cc.
Referenced by G4SDManager::ListTree().
operator==()
G4bool G4SDStructure::operator== (const G4SDStructure & right) const
Definition at line 55 of file G4SDStructure.cc.
RemoveSD()
void G4SDStructure::RemoveSD (G4VSensitiveDetector * sd) private
Definition at line 112 of file G4SDStructure.cc.
Referenced by AddNewDetector().
SetVerboseLevel()
void G4SDStructure::SetVerboseLevel (G4int vl) inline
Definition at line 75 of file G4SDStructure.hh.
Referenced by G4SDManager::SetVerboseLevel().
Terminate()
void G4SDStructure::Terminate (G4HCofThisEvent * HCE)
Definition at line 203 of file G4SDStructure.cc.
Referenced by G4SDManager::TerminateCurrentEvent().
Field Documentation
detector
std::vector<G4VSensitiveDetector*> G4SDStructure::detector private
Definition at line 69 of file G4SDStructure.hh.
Referenced by Activate(), AddNewDetector(), GetSD(), Initialize(), ListTree(), RemoveSD(), SetVerboseLevel(), Terminate(), and ~G4SDStructure().
dirName
G4String G4SDStructure::dirName private
Definition at line 71 of file G4SDStructure.hh.
Referenced by G4SDStructure().
pathName
G4String G4SDStructure::pathName private
Definition at line 70 of file G4SDStructure.hh.
Referenced by Activate(), AddNewDetector(), FindSensitiveDetector(), G4SDStructure(), and ListTree().
structure
std::vector<G4SDStructure*> G4SDStructure::structure private
Definition at line 68 of file G4SDStructure.hh.
Referenced by Activate(), AddNewDetector(), FindSubDirectory(), Initialize(), ListTree(), SetVerboseLevel(), Terminate(), and ~G4SDStructure().
verboseLevel
G4int G4SDStructure::verboseLevel private
Definition at line 72 of file G4SDStructure.hh.
Referenced by SetVerboseLevel().
The documentation for this class was generated from the following files:
source/digits_hits/detector/include/G4SDStructure.hh
source/digits_hits/detector/src/G4SDStructure.cc