Geant4: G4VRTScanner Class Reference
G4VRTScanner Class Reference abstract
#include <G4VRTScanner.hh>
Public Member Functions
G4VRTScanner ()
virtual ~G4VRTScanner ()
virtual const G4String & GetGSName () const =0
virtual const G4String & GetGSNickname () const =0
virtual void Initialize (G4int nRow, G4int nColumn)=0
virtual G4bool Coords (G4int &iRow, G4int &iColumn)=0
virtual void Draw (unsigned char red, unsigned char green, unsigned char blue)
Detailed Description
Definition at line 40 of file G4VRTScanner.hh.
Constructor & Destructor Documentation
G4VRTScanner()
G4VRTScanner::G4VRTScanner ()
Definition at line 32 of file G4VRTScanner.cc.
~G4VRTScanner()
G4VRTScanner::~G4VRTScanner () virtual
Definition at line 33 of file G4VRTScanner.cc.
Member Function Documentation
Coords()
virtual G4bool G4VRTScanner::Coords (G4int & iRow, G4int & iColumn) pure virtual
Implemented in G4RTSimpleScanner.
Referenced by G4TheRayTracer::CreateBitMap(), and G4TheMTRayTracer::CreateBitMap().
Draw()
void G4VRTScanner::Draw (unsigned char red, unsigned char green, unsigned char blue) inline virtual
Definition at line 70 of file G4VRTScanner.hh.
Referenced by G4TheRayTracer::CreateBitMap(), and G4TheMTRayTracer::CreateBitMap().
GetGSName()
virtual const G4String& G4VRTScanner::GetGSName () const pure virtual
Implemented in G4RTSimpleScanner.
GetGSNickname()
virtual const G4String& G4VRTScanner::GetGSNickname () const pure virtual
Implemented in G4RTSimpleScanner.
Initialize()
virtual void G4VRTScanner::Initialize (G4int nRow, G4int nColumn) pure virtual
Implemented in G4RTSimpleScanner.
Referenced by G4TheRayTracer::CreateBitMap(), and G4TheMTRayTracer::CreateBitMap().
The documentation for this class was generated from the following files:
source/visualization/RayTracer/include/G4VRTScanner.hh
source/visualization/RayTracer/src/G4VRTScanner.cc