Geant4: source/processes/electromagnetic/dna/processes/src/G4DNAElectronHoleRecombination.cc File Reference
G4DNAElectronHoleRecombination.cc File Reference
#include <G4DNAElectronHoleRecombination.hh>
#include <G4MoleculeFinder.hh>
#include "G4PhysicalConstants.hh"
#include "G4Electron_aq.hh"
#include "G4MoleculeTable.hh"
#include "G4MolecularDissociationChannel.hh"
#include "G4H2.hh"
#include "G4H2O.hh"
#include "G4MolecularConfiguration.hh"
#include "G4DNAWaterDissociationDisplacer.hh"
#include "G4DNAMolecularMaterial.hh"
#include "G4SystemOfUnits.hh"
#include "G4VMoleculeCounter.hh"
#include "G4Exp.hh"
Functions
double Y (double density)
double A (double temperature)
double B (double temperature)
double S (double temp)
double C (double temp)
double D (double temp)
double epsilon (double density, double temperature)
Variables
static double onsager_constant = e_squared / (4. * pi * epsilon0 * k_Boltzmann)
Function Documentation
A()
double A (double temperature)
Definition at line 60 of file G4DNAElectronHoleRecombination.cc.
Referenced by G4Pow::A13(), G4Pow::A23(), G4INCL::NuclearDensityFactory::addDensityToCache(), CCalMaterialFactory::addElement(), G4NistElementBuilder::AddElement(), G4SDParticleFilter::addIon(), G4RadioactivityTable::AddIsotope(), G4VarNtp::addParticle(), G4NuclearLevelData::AddPrivateData(), G4INCL::NuclearDensityFactory::addRPCorrelationToCache(), G4ionIonisation::AddStoppingData(), G4EmCorrections::AddStoppingData(), G4RadioactiveDecayBase::AddUserDecayDataFile(), G4RadioactiveDecay::AddUserDecayDataFile(), G4WendtFissionFragmentGenerator::ApplyYourself(), G4ParaFissionModel::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4LEpp::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4LEnp::ApplyYourself(), G4PreCompoundModel::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4EmCaptureCascade::ApplyYourself(), G4MuonMinusBoundDecay::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4ParticleHPChannel::ApplyYourself(), G4CompetitiveFission::AsymmetricRatio(), G4LFission::Atomas(), G4NucleiProperties::AtomicMass(), G4Nucleus::AtomicMass(), G4FissionBarrier::BarashenkovFissionBarrier(), RunAction::BeginOfRunAction(), G4InuclSpecialFunctions::bindingEnergy(), G4NucleiProperties::BindingEnergy(), G4InuclSpecialFunctions::bindingEnergyAsymptotic(), G4Evaporation::BreakFragment(), G4InuclEvaporation::BreakItUp(), G4ExcitationHandler::BreakItUp(), G4WilsonAblationModel::BreakItUp(), G4UnstableFragmentBreakUp::BreakUpChain(), G4DNAScreenedRutherfordElasticModel::BrennerZaiderRandomizeCosTheta(), G4DNAUeharaScreenedRutherfordElasticModel::BrennerZaiderRandomizeCosTheta(), G4Abla::bsbkbc(), G4EmCorrections::BuildCorrectionVector(), G4AdjointCSManager::BuildCrossSectionMatrices(), G4AdjointCSManager::BuildCrossSectionsMatricesForAGivenModelAndElement(), G4KokoulinMuonNuclearXS::BuildCrossSectionTable(), G4ParticleHPJENDLHEData::BuildPhysicsTable(), G4BGGNucleonInelasticXS::BuildPhysicsTable(), G4BGGPionElasticXS::BuildPhysicsTable(), G4BGGNucleonElasticXS::BuildPhysicsTable(), G4BGGPionInelasticXS::BuildPhysicsTable(), C(), G4GEMCoulombBarrier::CalcCompoundRadius(), G4StatMF::CalcEnergy(), G4StatMFMicroCanonical::CalcEntropyOfCompoundNucleus(), G4StatMFMicroCanonical::CalcFreeInternalEnergy(), G4GEMProbability::CalcProbability(), G4QuasiElRatios::CalcQF2IN_Ratio(), G4hhElastic::CalculateBQ(), G4hhElastic::CalculateBqQ123(), G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), G4ChipsKaonPlusInelasticXS::CalculateCrossSection(), G4RDGenerator2BN::CalculateFkt(), G4Generator2BN::CalculateFkt(), G4DiffuseElasticV2::CalculateNuclearRad(), G4NuclNuclDiffuseElastic::CalculateNuclearRad(), G4DiffuseElastic::CalculateNuclearRad(), G4GNASHTransitions::CalculateProbability(), G4PreCompoundTransitions::CalculateProbability(), G4StatMFMacroCanonical::CalculateTemperature(), G4PDGCodeChecker::CheckForNuclei(), G4StatMFChannel::CheckFragments(), G4ScreenedNuclearRecoil::CheckNuclearCollision(), G4BinaryCascade::CheckPauliPrinciple(), G4QuasiElRatios::ChExElCoef(), G4StatMFMacroCanonical::ChooseA(), G4StatMFMacroCanonical::ChooseAandZ(), G4StatMFMacroCanonical::ChooseZ(), G4FermiFragmentsPoolVI::ClosestChannels(), G4GeomTools::ClosestPointOnSegment(), G4GeomTools::ClosestPointOnTriangle(), G4INCL::Cluster::Cluster(), G4INCL::ClusteringModelIntercomparison::ClusteringModelIntercomparison(), G4PreCompoundHe3::CoalescenceFactor(), G4PreCompoundAlpha::CoalescenceFactor(), G4PreCompoundDeuteron::CoalescenceFactor(), G4PreCompoundTriton::CoalescenceFactor(), G4VEmAdjointModel::ComputeAdjointCrossSectionVectorPerAtomForScatProj(), G4VEmAdjointModel::ComputeAdjointCrossSectionVectorPerAtomForSecond(), G4ComponentGGNuclNuclXsc::ComputeCoulombBarier(), G4KalbachCrossSection::ComputeCrossSection(), G4VCrossSectionDataSet::ComputeCrossSection(), G4PolarizedComptonModel::ComputeCrossSectionPerAtom(), G4EmMultiModel::ComputeCrossSectionPerAtom(), G4VEmProcess::ComputeCrossSectionPerAtom(), G4EmCalculator::ComputeCrossSectionPerAtom(), G4ComponentGGHadronNucleusXsc::ComputeCrossSections(), G4ComponentGGNuclNuclXsc::ComputeCrossSections(), G4KokoulinMuonNuclearXS::ComputeDDMicroscopicCrossSection(), G4Fragment::ComputeGroundStateMass(), G4KokoulinMuonNuclearXS::ComputeMicroscopicCrossSection(), G4HadronElastic::ComputeMomentumCMS(), G4Material::ComputeNuclearInterLength(), G4FermiDecayProbability::ComputeProbability(), G4ComponentGGHadronNucleusXsc::ComputeQuasiElasticRatio(), G4ComponentGGNuclNuclXsc::ComputeQuasiElasticRatio(), G4DiffElasticRatio::ComputeRatio(), Construct(), Materials::Construct(), QMaterials::Construct(), MyMaterials::Construct(), B03DetectorConstruction::Construct(), B01DetectorConstruction::Construct(), B02DetectorConstruction::Construct(), CML2Ph_BoxInBox::Construct(), G4RDGenerator2BN::ConstructMajorantSurface(), G4Generator2BN::ConstructMajorantSurface(), G4MuonicAtomHelper::ConstructMuonicAtom(), G4IonTable::Contains(), G4BGGPionInelasticXS::CoulombFactor(), G4INCL::NuclearDensityFactory::createDensity(), G4StatMFChannel::CreateFragment(), G4IonTable::CreateIon(), G4LevelReader::CreateLevelManager(), G4INCL::NuclearDensityFactory::createPCDFTable(), G4GenericPolycone::CreatePolyhedron(), G4Polyhedra::CreatePolyhedron(), G4INCL::NuclearDensityFactory::createRCDFTable(), G4INCL::NuclearDensityFactory::createRPCorrelationTable(), G4CascadeInterface::createTarget(), G4DNABornIonisationModel1::CrossSectionPerVolume(), G4DNABornIonisationModel2::CrossSectionPerVolume(), G4VTwistSurface::DebugPrint(), G4MuonicAtomDecay::DecayIt(), G4Fissioner::deExcite(), G4PreCompoundModel::DeExcite(), G4HumanPhantomMaterial::DefineMaterials(), BrachyMaterial::DefineMaterials(), G4ElasticData::DefineNucleusParameters(), G4FissionParameters::DefineParameters(), G4VEmAdjointModel::DiffCrossSectionPerAtomPrimToScatPrim(), G4AdjointComptonModel::DiffCrossSectionPerAtomPrimToSecond(), G4AdjointIonIonisationModel::DiffCrossSectionPerAtomPrimToSecond(), G4AdjointhIonisationModel::DiffCrossSectionPerAtomPrimToSecond(), G4VEmAdjointModel::DiffCrossSectionPerAtomPrimToSecond(), G4GeomTools::DistancePointSegment(), G4EllipticalTube::DistanceToIn(), G4Ellipsoid::DistanceToIn(), G4Paraboloid::DistanceToIn(), G4EllipticalCone::DistanceToIn(), G4EllipticalTube::DistanceToOut(), G4Ellipsoid::DistanceToOut(), G4Paraboloid::DistanceToOut(), G4EllipticalCone::DistanceToOut(), G4TwistTubsSide::DistanceToPlane(), G4TwistTubsSide::DistanceToSurface(), G4ScreenedCoulombClassicalKinematics::DoCollisionStep(), G4ProjectileFragmentCrossSection::doit(), G4ScreenedCoulombClassicalKinematics::DoScreeningComputation(), G4FermiFragmentsPoolVI::Dump(), G4VIsotopeTable::DumpTable(), G4FissionProbability::EmissionProbability(), G4CompetitiveFission::EmittedFragment(), G4FPYSamplingOps::EvaluateWattConstants(), G4Abla::evap_postsaddle(), G4Pow::expA(), G4AdjointInterpolator::ExponentialInterpolation(), PerspectiveVisAction::ExtendedDraw(), G4LivermorePolarizedGammaConversionModel::Fdlor(), G4InuclSpecialFunctions::FermiEnergy(), HadrontherapyMatrix::Fill(), HadrontherapyLet::FillEnergySpectrum(), G4IonTable::FindIon(), G4EmCalculator::FindIon(), G4IonTable::FindIonInMaster(), G4IonTable::FindIsotope(), G4NuclearLevelData::FindLevel(), G4NuclearPolarizationStore::FindOrBuild(), G4StatMF::FindTemperatureOfBreakingChannel(), G4LivermorePolarizedGammaConversionModel::Fintlor(), G4Abla::fission_width(), G4CompetitiveFission::FissionAtomicNumber(), G4FissionBarrier::FissionBarrier(), G4CompetitiveFission::FissionCharge(), G4Abla::fissionDistri(), G4CompetitiveFission::FissionKineticEnergy(), G4CoulombBarrier::G4CoulombBarrier(), G4Isotope::G4Isotope(), G4LevelManager::G4LevelManager(), G4FissionFragmentGenerator::G4MakeIsotopeCode(), G4NistManager::G4NistManager(), G4Nucleus::G4Nucleus(), G4RandomPointOnEllipse(), G4RandomPointOnEllipsoid(), G4fissionEvent::G4SmpNugDist(), G4RDGenerator2BN::Generate2BN(), B3PrimaryGeneratorAction::GeneratePrimaries(), G4AdjointPrimaryGeneratorAction::GeneratePrimaries(), G4WilsonAbrasionModel::GetAbradedNucleons(), G4InuclSpecialFunctions::getAL(), G4AblaVirtualData::getAlpha(), G4HyperNucleiProperties::GetAtomicMass(), G4NucleiPropertiesTheoreticalTable::GetAtomicMass(), G4NucleiProperties::GetAtomicMass(), G4NucleiPropertiesTableAME12::GetAtomicMass(), G4SigmaPlusField::GetBarrier(), G4SigmaMinusField::GetBarrier(), G4AntiProtonField::GetBarrier(), G4KaonMinusField::GetBarrier(), G4KaonPlusField::GetBarrier(), G4PionPlusField::GetBarrier(), G4PionMinusField::GetBarrier(), G4AblaVirtualData::getBeta2(), G4AblaVirtualData::getBeta4(), G4NucleiPropertiesTableAME12::GetBetaDecayEnergy(), G4NucleiProperties::GetBindingEnergy(), G4NucleiPropertiesTheoreticalTable::GetBindingEnergy(), G4NucleiPropertiesTableAME12::GetBindingEnergy(), G4QuasiElRatios::GetChExFactor(), G4AntiNuclElastic::GetcosTeta1(), G4ComponentGGNuclNuclXsc::GetCoulombBarier(), G4NeutronInelasticCrossSection::GetCrossSection(), G4ParticleHPJENDLHEData::GetCrossSection(), G4CrossSectionDataStore::GetCrossSection(), G4StatMFMicroPartition::GetDegeneracyFactor(), G4Abla::getdeltabinding(), G4NuclNuclDiffuseElastic::GetDiffuseElasticSumXsc(), G4DiffuseElastic::GetDiffuseElasticSumXsc(), G4NuclNuclDiffuseElastic::GetDiffuseElasticXsc(), G4DiffuseElastic::GetDiffuseElasticXsc(), G4AblaVirtualData::getEcnz(), G4UPiNuclearCrossSection::GetElasticCrossSection(), G4ComponentGGHadronNucleusXsc::GetElasticElementCrossSection(), G4ComponentGGNuclNuclXsc::GetElasticElementCrossSection(), G4ComponentAntiNuclNuclearXS::GetElasticElementCrossSection(), G4ComponentGGHadronNucleusXsc::GetElasticGlauberGribov(), G4ComponentGGNuclNuclXsc::GetElasticGlauberGribov(), G4ComponentGGHadronNucleusXsc::GetElasticIsotopeCrossSection(), G4ComponentGGNuclNuclXsc::GetElasticIsotopeCrossSection(), G4ComponentAntiNuclNuclearXS::GetElasticIsotopeCrossSection(), G4ChipsComponentXS::GetElasticIsotopeCrossSection(), G3EleTable::GetEle(), G4NeutronInelasticCrossSection::GetElementCrossSection(), G4HadronInelasticDataSet::GetElementCrossSection(), G4HadronElasticDataSet::GetElementCrossSection(), G4IonsShenCrossSection::GetElementCrossSection(), G4ChargeExchangeProcess::GetElementCrossSection(), G4IonProtonCrossSection::GetElementCrossSection(), G4ComponentGGNuclNuclXsc::GetElementCrossSection(), G4QuasiElRatios::GetElTot(), G4PhotonEvaporation::GetEmissionProbability(), G4BinaryCascade::GetExcitationEnergy(), G4INCL::ParticleTable::getFermiMomentumConstantLight(), G4INCL::ParticleTable::getFermiMomentumMassDependent(), G4SigmaPlusField::GetField(), G4SigmaMinusField::GetField(), G4KaonZeroField::GetField(), G4SigmaZeroField::GetField(), G4KaonMinusField::GetField(), G4KaonPlusField::GetField(), G4PionPlusField::GetField(), G4PionZeroField::GetField(), G4AntiProtonField::GetField(), G4PionMinusField::GetField(), G4PhotonEvaporation::GetFinalLevelEnergy(), G4PairingCorrection::GetFissionPairingCorrection(), G4Abla::gethyperbinding(), G4Abla::gethyperseparation(), G4INCL::ParticleTable::getINCLMass(), G4NucleiPropertiesTheoreticalTable::GetIndex(), G4NucleiPropertiesTableAME12::GetIndex(), G4UPiNuclearCrossSection::GetInelasticCrossSection(), G4ComponentGGHadronNucleusXsc::GetInelasticElementCrossSection(), G4ComponentGGNuclNuclXsc::GetInelasticElementCrossSection(), G4ComponentAntiNuclNuclearXS::GetInelasticElementCrossSection(), G4ComponentGGHadronNucleusXsc::GetInelasticGlauberGribov(), G4ComponentGGNuclNuclXsc::GetInelasticGlauberGribov(), G4ComponentGGHadronNucleusXsc::GetInelasticIsotopeCrossSection(), G4ComponentGGNuclNuclXsc::GetInelasticIsotopeCrossSection(), G4ComponentAntiNuclNuclearXS::GetInelasticIsotopeCrossSection(), G4ChipsComponentXS::GetInelasticIsotopeCrossSection(), G4NuclNuclDiffuseElastic::GetInvCoulombElasticXsc(), G4DiffuseElastic::GetInvCoulombElasticXsc(), G4NuclNuclDiffuseElastic::GetInvElasticSumXsc(), G4DiffuseElastic::GetInvElasticSumXsc(), G4NuclNuclDiffuseElastic::GetInvElasticXsc(), G4DiffuseElastic::GetInvElasticXsc(), G4IonTable::GetIon(), G4BinaryCascade::GetIonMass(), G4IonTable::GetIonMass(), G4IonTable::GetIonName(), G4MuNeutrinoNucleusTotXsc::GetIsoCrossSection(), G4ChipsAntiBaryonInelasticXS::GetIsoCrossSection(), G4PhotoNuclearCrossSection::GetIsoCrossSection(), G4ChipsProtonElasticXS::GetIsoCrossSection(), G4ChipsProtonInelasticXS::GetIsoCrossSection(), G4ChipsHyperonElasticXS::GetIsoCrossSection(), G4ChipsHyperonInelasticXS::GetIsoCrossSection(), G4ChipsKaonMinusInelasticXS::GetIsoCrossSection(), G4ChipsKaonPlusElasticXS::GetIsoCrossSection(), G4ChipsPionPlusElasticXS::GetIsoCrossSection(), G4ChipsAntiBaryonElasticXS::GetIsoCrossSection(), G4ChipsKaonMinusElasticXS::GetIsoCrossSection(), G4ChipsNeutronElasticXS::GetIsoCrossSection(), G4ChipsPionMinusElasticXS::GetIsoCrossSection(), G4ChipsPionMinusInelasticXS::GetIsoCrossSection(), G4ChipsKaonPlusInelasticXS::GetIsoCrossSection(), G4ChipsNeutronInelasticXS::GetIsoCrossSection(), G4ChipsPionPlusInelasticXS::GetIsoCrossSection(), G4ChipsKaonZeroElasticXS::GetIsoCrossSection(), G4ChipsKaonZeroInelasticXS::GetIsoCrossSection(), G4NeutronCaptureXS::GetIsoCrossSection(), G4BGGNucleonInelasticXS::GetIsoCrossSection(), G4BGGPionElasticXS::GetIsoCrossSection(), G4BGGNucleonElasticXS::GetIsoCrossSection(), G4NeutronInelasticXS::GetIsoCrossSection(), G4ParticleInelasticXS::GetIsoCrossSection(), G4BGGPionInelasticXS::GetIsoCrossSection(), G4CrossSectionDataStore::GetIsoCrossSection(), G4VCrossSectionDataSet::GetIsoCrossSection(), G4ComponentGGHadronNucleusXsc::GetIsoCrossSection(), G4IonTable::GetIsomerMass(), G4IsotopeMagneticMomentTable::GetIsotope(), G4NuclideTable::GetIsotope(), G4VIsotopeTable::GetIsotopeByIsoLvl(), G4IsotopeMagneticMomentTable::GetIsotopeByIsoLvl(), G4NuclideTable::GetIsotopeByIsoLvl(), G4INCL::ParticleTable::getLargestNuclearRadius(), G4NuclearLevelData::GetLevelDensity(), G4NuclearLevelData::GetLevelEnergy(), G4NuclearLevelData::GetLevelManager(), G4IonTable::GetLifeTime(), G4IonTable::GetLightAntiIon(), G4IonTable::GetLightIon(), G4NuclearLevelData::GetLowEdgeLevelEnergy(), G4NucleiPropertiesTheoreticalTable::GetMassExcess(), G4NucleiProperties::GetMassExcess(), G4NucleiPropertiesTableAME12::GetMassExcess(), G4QMDNucleus::GetMassNumber(), G4StatMFParameters::GetMaxAverageMultiplicity(), G4INCL::ParticleTable::getMaximumNuclearRadius(), G4NuclearLevelData::GetMaxLevelEnergy(), G4VEvaporationChannel::GetMaxLevelEnergy(), G4PhononDownconversion::GetMeanFreePath(), G4AblaVirtualData::getMexp(), G4AblaVirtualData::getMexpID(), G4INCL::ParticleTable::getMomentumRMS(), G4MuonicAtomHelper::GetMuonCaptureRate(), G4MuonMinusBoundDecay::GetMuonCaptureRate(), G4MuonMinusBoundDecay::GetMuonDecayRate(), G4IonTable::GetMuonicAtom(), G4ParticleHPNames::GetName(), G4ParticleHPIsoData::GetName(), G4INCL::ParticleTable::getName(), G4VEvaporationChannel::GetNearestLevelEnergy(), G4QMDNucleus::GetNuclearMass(), G4NucleiProperties::GetNuclearMass(), G4HyperNucleiProperties::GetNuclearMass(), G4NucleiPropertiesTheoreticalTable::GetNuclearMass(), G4NucleiPropertiesTableAME12::GetNuclearMass(), G4INCL::ParticleTable::getNuclearRadius(), G4IonTable::GetNucleusByEncoding(), G4IonTable::GetNucleusEncoding(), G4IonTable::GetNucleusMass(), G4ComponentGGNuclNuclXsc::GetNucleusRadiusDE(), G4ComponentGGNuclNuclXsc::GetNucleusRadiusRMS(), G4AblaVirtualData::getPace2(), G4PairingCorrection::GetPairingCorrection(), G4NuclearLevelData::GetPairingCorrection(), G4FissionProductYieldDist::GetParticleDefinition(), G4Paraboloid::GetPointOnSurface(), G4ComponentGGHadronNucleusXsc::GetProductionElementCrossSection(), G4ComponentGGHadronNucleusXsc::GetProductionIsotopeCrossSection(), G4QuasiElRatios::GetQF2IN_Ratio(), G4INCL::ParticleTable::getRadiusParameter(), G4INCL::HFB::getRadiusParameterHFB(), G4RadioactivityTable::GetRate(), G4ComponentGGHadronNucleusXsc::GetRatioQE(), G4ComponentGGHadronNucleusXsc::GetRatioSD(), G4INCL::ParticleTable::getRealMass(), G4AblaVirtualData::getRms(), G4INCL::ParticleTable::getSeparationEnergyReal(), G4INCL::ParticleTable::getSeparationEnergyRealForLight(), G4ShellCorrection::GetShellCorrection(), G4INCL::ParticleTable::getShortName(), G4INCL::ParticleTable::getSurfaceDiffuseness(), G4INCL::HFB::getSurfaceDiffusenessHFB(), G4ComponentGGHadronNucleusXsc::GetTotalElementCrossSection(), G4ComponentGGNuclNuclXsc::GetTotalElementCrossSection(), G4ComponentAntiNuclNuclearXS::GetTotalElementCrossSection(), G4ComponentGGHadronNucleusXsc::GetTotalIsotopeCrossSection(), G4ComponentAntiNuclNuclearXS::GetTotalIsotopeCrossSection(), G4ComponentGGNuclNuclXsc::GetTotalIsotopeCrossSection(), G4ChipsComponentXS::GetTotalIsotopeCrossSection(), G4PhononDownconversion::GetTTDecayProb(), G4PhotonEvaporation::GetUpperLevelEnergy(), G4AblaVirtualData::getVgsld(), G4EMDissociationCrossSection::GetWilsonProbabilityForProtonDissociation(), G4WilsonRadius::GetWilsonRadius(), G4WilsonRadius::GetWilsonRMSRadius(), G4ParticleHPJENDLHEData::getXSfromThisIsotope(), G4NistManager::GetZ13(), G4ComponentGGNuclNuclXsc::GetZandACrossSection(), G4ParticleHPMadlandNixSpectrum::GIntegral(), G4LivermorePolarizedGammaConversionModel::Glor(), G4ParticleHPD2AInelasticFS::Init(), G4ParticleHPFCFissionFS::Init(), G4ParticleHPLCFissionFS::Init(), G4ParticleHPSCFissionFS::Init(), G4ParticleHPTCFissionFS::Init(), G4ParticleHPT2AInelasticFS::Init(), G4ParticleHPFFFissionFS::Init(), G4ParticleHP2NPInelasticFS::Init(), G4ParticleHPNDInelasticFS::Init(), G4ParticleHP2N2AInelasticFS::Init(), G4ParticleHP2NDInelasticFS::Init(), G4ParticleHP3AInelasticFS::Init(), G4ParticleHPDAInelasticFS::Init(), G4ParticleHPNAInelasticFS::Init(), G4ParticleHPN2PInelasticFS::Init(), G4ParticleHPN3AInelasticFS::Init(), G4ParticleHPND2AInelasticFS::Init(), G4ParticleHPNPAInelasticFS::Init(), G4ParticleHPNPInelasticFS::Init(), G4ParticleHPNXInelasticFS::Init(), G4ParticleHPHe3InelasticFS::Init(), G4ParticleHPNTInelasticFS::Init(), G4ParticleHPNInelasticFS::Init(), G4ParticleHPTInelasticFS::Init(), G4ParticleHPPInelasticFS::Init(), G4ParticleHPPAInelasticFS::Init(), G4ParticleHPDInelasticFS::Init(), G4ParticleHPN2AInelasticFS::Init(), G4ParticleHP2PInelasticFS::Init(), G4ParticleHPNHe3InelasticFS::Init(), G4ParticleHPPDInelasticFS::Init(), G4ParticleHPNT2AInelasticFS::Init(), G4ParticleHP2NInelasticFS::Init(), G4ParticleHP2NAInelasticFS::Init(), G4ParticleHPPTInelasticFS::Init(), G4ParticleHP3NPInelasticFS::Init(), G4ParticleHP4NInelasticFS::Init(), G4ParticleHPAInelasticFS::Init(), G4ParticleHP3NInelasticFS::Init(), G4ParticleHP3NAInelasticFS::Init(), G4ParticleHP2AInelasticFS::Init(), G4ParticleHPFissionFS::Init(), G4ParticleHPCaptureFS::Init(), G4ParticleHPFSFissionFS::Init(), G4ParticleHPFissionBaseFS::Init(), G4ParticleHPElementData::Init(), G4ParticleHPElasticFS::Init(), G4ParticleHPIsoData::Init(), G4ParticleHPInelasticBaseFS::Init(), G4ParticleHPFinalState::Init(), G4ParticleHPInelasticCompFS::Init(), G4FissionLibrary::Init(), G4FermiFragmentsPoolVI::Initialise(), G4NeutronCaptureXS::Initialise(), G4NeutronInelasticXS::Initialise(), G4ParticleInelasticXS::Initialise(), G4NuclearLevelData::InitialiseForIsotope(), G4PhotonEvaporation::InitialiseGRData(), G4PhotonEvaporation::InitialiseLevelManager(), G4NuclNuclDiffuseElastic::InitialiseOnFly(), G4DiffuseElasticV2::InitialiseOnFly(), G4DiffuseElastic::InitialiseOnFly(), G4StatMFMicroCanonical::Initialize(), G4StatMFMacroCanonical::Initialize(), G4StatMFMicroManager::Initialize(), G4WendtFissionFragmentGenerator::InitializeANucleus(), G4PenelopeBremsstrahlungFS::InitializeEnergySampling(), G4INCL::INCL::initializeTarget(), G4NuclNuclDiffuseElastic::InitParameters(), G4NuclNuclDiffuseElastic::InitParametersGla(), G4GoudsmitSaundersonTable::InitSCPCorrection(), G4INCL::INCL::initUniverseRadius(), G4IonTable::Insert(), G4IonTable::InsertWorker(), G4Paraboloid::Inside(), G4NuclNuclDiffuseElastic::IntegralElasticProb(), G4DiffuseElastic::IntegralElasticProb(), G4HETCFragment::IntegrateEmissionProbability(), G4PiNuclearCrossSection::Interpolate(), G4UPiNuclearCrossSection::Interpolate(), G4RDVeLowEnergyLoss::InvertRangeVector(), G4hRDEnergyLoss::InvertRangeVector(), G4FermiFragmentsPoolVI::IsApplicable(), G4RadioactiveDecayBase::IsApplicable(), G4RadioactiveDecay::IsApplicable(), G4FermiFragmentsPoolVI::IsInPhysPairs(), G4NucleiProperties::IsInStableTable(), G4NucleiPropertiesTheoreticalTable::IsInTable(), G4NucleiPropertiesTableAME12::IsInTable(), G4FermiFragmentsPoolVI::IsInThePool(), G4FermiFragmentsPoolVI::IsInUnphysPairs(), G4PhotoNuclearCrossSection::IsIsoApplicable(), G4ParticleHPBGGNucleonInelasticXS::IsIsoApplicable(), G4ParticleInelasticXS::IsoCrossSection(), G4NeutronCaptureXS::IsoCrossSection(), G4NeutronInelasticXS::IsoCrossSection(), G4FermiFragmentsPoolVI::IsPhysical(), G4INCL::ClusterDecay::isStable(), G4INCL::NKbToLpiChannel::KaonMomentum(), G4INCL::NKbElasticChannel::KaonMomentum(), G4INCL::NKbToNKbChannel::KaonMomentum(), G4INCL::NpiToLKChannel::KaonMomentum(), G4INCL::NpiToSKChannel::KaonMomentum(), G4INCL::NKbToSpiChannel::KaonMomentum(), G4ConstantLevelDensityParameter::LevelDensityParameter(), G4FissionLevelDensityParameter::LevelDensityParameter(), G4EvaporationLevelDensityParameter::LevelDensityParameter(), G4FissionLevelDensityParameterINCLXX::LevelDensityParameter(), G4LevelReader::LevelManager(), G4RadioactiveDecayBase::LoadDecayTable(), G4RadioactiveDecay::LoadDecayTable(), G4INCL::Store::loadParticles(), G4Pow::log10A(), G4Pow::logA(), G4AdjointInterpolator::LogarithmicInterpolation(), lPoPs_addParticleIfNeeded(), main(), G4FissionProductYieldDist::MakeIsotopeName(), G4LevelReader::MakeLevelManager(), G4CascadeCoalescence::makeLightIon(), G4CompetitiveFission::MassDistribution(), G4NucleiProperties::MassExcess(), DetectorConstruction::MaterialWithSingleIsotope(), G4NuclearLevelData::MaxLevelEnergy(), G4NucleiPropertiesTableAME12::MaxZ(), MCGIDI_miscNameToZAm(), MCGIDI_particle_getInternalID(), MCGIDI_POP_new(), G4hCoulombScatteringModel::MinPrimaryEnergy(), G4eCoulombScatteringModel::MinPrimaryEnergy(), G4NucleiPropertiesTableAME12::MinZ(), G4NucleiProperties::NuclearMass(), G4RPGReaction::NuclearReaction(), G3EleTable::parse(), G4Abla::pen(), G4PreCompoundTransitions::PerformTransition(), G4GeomTools::PointInTriangle(), PoP_setZ_A_l(), PoPs_getZ_A_l(), PoPs_getZ_A_l_atIndex(), G4Pow::powA(), G4IonTable::PreloadNuclide(), G4INCL::INCL::prepareReaction(), G4INCL::Store::printParticleConfiguration(), G4PreCompoundIon::ProbabilityDistributionFunction(), HadrontherapyDetectorSD::ProcessHits(), G4GeomTools::QuadArea(), G4GeomTools::QuadAreaNormal(), G4CompetitiveFission::Ratio(), G4AblaDataFile::readData(), G4LEPTSDiffXS::readDXS(), CCalMaterialFactory::readElements(), G4ParticleHPJENDLHEData::registAPhysicsVector(), G4ParticleHPChannel::Register(), G4IonTable::Remove(), PerspectiveVisAction::RoomAndChair(), G4ParticleHPIsotropic::Sample(), G4ParticleHPNBodyPhaseSpace::Sample(), G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContAngularPar::Sample(), G4NeutrinoElectronCcModel::SampleCosCMS(), G4Generator2BN::SampleDirection(), G4NeutrinoElectronNcModel::SampleElectronTkin(), G4PenelopeIonisationModel::SampleFinalStateElectron(), G4PenelopeBremsstrahlungFS::SampleGammaEnergy(), G4AntiNuclElastic::SampleInvariantT(), G4ChipsElasticModel::SampleInvariantT(), G4HadronElastic::SampleInvariantT(), G4NuclNuclDiffuseElastic::SampleInvariantT(), G4DiffuseElasticV2::SampleInvariantT(), G4DiffuseElastic::SampleInvariantT(), G4BetheHeitler5DModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4ChargeExchange::SampleT(), G4NuclNuclDiffuseElastic::SampleT(), G4DiffuseElastic::SampleT(), G4NuclNuclDiffuseElastic::SampleTableT(), G4DiffuseElasticV2::SampleTableT(), G4DiffuseElastic::SampleTableT(), G4DiffuseElasticV2::SampleTableThetaCMS(), G4NuclNuclDiffuseElastic::SampleTableThetaCMS(), G4DiffuseElastic::SampleTableThetaCMS(), G4AntiNuclElastic::SampleThetaCMS(), G4NuclNuclDiffuseElastic::SampleThetaCMS(), G4DiffuseElastic::SampleThetaCMS(), G4AntiNuclElastic::SampleThetaLab(), G4NuclNuclDiffuseElastic::SampleThetaLab(), G4DiffuseElastic::SampleThetaLab(), G4QuasiElasticChannel::Scatter(), G4WilsonAblationModel::SelectSecondariesByDefault(), G4ElementSelector::SelectZandA(), G4INCL::Cluster::setA(), G4AblaVirtualData::setAlpha(), G4IsotopeProperty::SetAtomicMass(), G4AblaVirtualData::setBeta2(), G4AblaVirtualData::setBeta4(), G4AblaVirtualData::setEcnz(), G4KM_OpticalEqRhs::SetFactor(), G4VPolarizedCrossSection::SetMaterial(), G4AblaVirtualData::setMexp(), G4AblaVirtualData::setMexpID(), G4RadioactiveDecayBaseMessenger::SetNewValue(), G4RadioactiveDecaymessenger::SetNewValue(), G4AblaVirtualData::setPace2(), G4Nucleus::SetParameters(), G4AblaVirtualData::setRms(), G4ParticleHPReactionWhiteBoard::SetTargA(), G4INCL::Config::setTargetA(), G4ScreeningMottCrossSection::SetupKinematic(), G4AblaVirtualData::setVgsld(), G4RPGNeutronInelastic::SlowNeutron(), G4RPGProtonInelastic::SlowProton(), HadrontherapyLet::StoreLetAscii(), G4NuclearLevelData::StreamLevels(), G4Paraboloid::SurfaceNormal(), G4CompetitiveFission::SymmetricRatio(), G4NuclNuclDiffuseElastic::TestAngleTable(), G4DiffuseElastic::TestAngleTable(), G4PhotoNuclearCrossSection::ThresholdEnergy(), G4Abla::tke_bu(), G4AblaInterface::toG4Particle(), G4INCLXXInterface::toG4Particle(), G4AblaInterface::toG4ParticleDefinition(), G4INCLXXInterface::toG4ParticleDefinition(), G4GeomTools::TriangleArea(), G4GeomTools::TriangleAreaNormal(), G4Abla::tunnelling(), G4ParticleHPInelasticCompFS::two_body_reaction(), G4ParticleHPElementData::UpdateData(), and G4ParticleHPChannel::UpdateData().
B()
double B (double temperature)
Definition at line 69 of file G4DNAElectronHoleRecombination.cc.
Referenced by F04FocusSolenoid::AddFieldValue(), F04SimpleSolenoid::AddFieldValue(), G4LMsdGenerator::ApplyYourself(), G4DecayWithSpin::AtRestDoIt(), G4WilsonAblationModel::BreakItUp(), G4DNAScreenedRutherfordElasticModel::BrennerZaiderRandomizeCosTheta(), G4DNAUeharaScreenedRutherfordElasticModel::BrennerZaiderRandomizeCosTheta(), C(), G4hhElastic::CalculateBQ(), G4hhElastic::CalculateBqQ123(), G4Reggeons::CalculateXs(), G4RPGInelastic::CheckQnums(), G4Reggeons::Chi_pomeron(), G4Reggeons::Chi_reggeon(), G4GeomTools::ClosestPointOnSegment(), G4GeomTools::ClosestPointOnTriangle(), G4GammaConversionToMuons::ComputeCrossSectionPerAtom(), G4mplIonisationModel::ComputeDEDXAhlen(), G4mplIonisationWithDeltaModel::ComputeDEDXAhlen(), F04GlobalField::ConstructField(), G4GenericPolycone::CreatePolyhedron(), G4Polyhedra::CreatePolyhedron(), G4DNABornIonisationModel2::CrossSectionPerVolume(), G4DNABornIonisationModel1::CrossSectionPerVolume(), D(), G4VTwistSurface::DebugPrint(), G4NonEquilibriumEvaporator::deExcite(), G4MagneticFieldModel::DescribeYourselfTo(), G4GeomTools::DistancePointSegment(), G4EllipticalTube::DistanceToIn(), G4Ellipsoid::DistanceToIn(), G4Paraboloid::DistanceToIn(), G4EllipticalCone::DistanceToIn(), G4EllipticalTube::DistanceToOut(), G4Ellipsoid::DistanceToOut(), G4Paraboloid::DistanceToOut(), G4EllipticalCone::DistanceToOut(), G4TwistTubsSide::DistanceToPlane(), G4TwistTubsSide::DistanceToSurface(), G4ErrorMag_UsualEqRhs::EvaluateRhsGivenB(), G4Mag_UsualEqRhs::EvaluateRhsGivenB(), G4BlineEquation::EvaluateRhsGivenB(), G4Mag_SpinEqRhs::EvaluateRhsGivenB(), G4AdjointInterpolator::ExponentialInterpolation(), G4RandomPointOnEllipse(), G4RandomPointOnEllipsoid(), G4ComponentAntiNuclNuclearXS::GetAntiHadronNucleonTotCrSc(), G4UniformMagField::GetConstantFieldValue(), G4ConstRK4::GetConstField(), G4TripathiCrossSection::GetElementCrossSection(), G4TripathiLightCrossSection::GetElementCrossSection(), CCalMagneticField::GetFieldValue(), G4LineCurrentMagField::GetFieldValue(), G4HarmonicPolMagField::GetFieldValue(), G4DELPHIMagField::GetFieldValue(), G4QuadrupoleMagField::GetFieldValue(), G4UniformMagField::GetFieldValue(), G4IonsShenCrossSection::GetIsoCrossSection(), G4PhononScattering::GetMeanFreePath(), G4Reggeons::GetProbabilities(), G4PenelopeGammaConversionModel::GetScreeningFunctions(), G4PhononDownconversion::GetTTDecayProb(), G4ParticleHPMadlandNixSpectrum::GIntegral(), G4HadronNucleonXsc::HadronNucleonXscPDG2005(), G4PenelopeBremsstrahlungFS::InitializeEnergySampling(), G4RDVeLowEnergyLoss::InvertRangeVector(), G4hRDEnergyLoss::InvertRangeVector(), G4AdjointInterpolator::LogarithmicInterpolation(), CCalMagneticField::MagneticField(), G4GeomTools::PointInTriangle(), G4GammaConversionToMuons::PostStepDoIt(), G4Fissioner::potentialMinimization(), G4GeomTools::QuadArea(), G4GeomTools::QuadAreaNormal(), PerspectiveVisAction::RoomAndChair(), G4NeutrinoElectronCcModel::SampleCosCMS(), G4NeutrinoElectronNcModel::SampleElectronTkin(), G4PenelopeBremsstrahlungFS::SampleGammaEnergy(), G4PenelopeGammaConversionModel::SampleSecondaries(), G4DecayWithSpin::Spin_Precession(), G4RKG3_Stepper::StepNoErr(), G4RKG3_Stepper::Stepper(), G4GeomTools::TriangleArea(), G4GeomTools::TriangleAreaNormal(), and G4Abla::width().
C()
double C (double temp)
Definition at line 86 of file G4DNAElectronHoleRecombination.cc.
Referenced by RE06DetectorConstruction::AddMaterial(), G4DNAScreenedRutherfordElasticModel::BrennerZaiderRandomizeCosTheta(), G4DNAUeharaScreenedRutherfordElasticModel::BrennerZaiderRandomizeCosTheta(), G4AlphaEvaporationProbability::CalcAlphaParam(), G4He3EvaporationProbability::CalcAlphaParam(), G4ProtonEvaporationProbability::CalcAlphaParam(), G4DeuteronEvaporationProbability::CalcAlphaParam(), G4TritonEvaporationProbability::CalcAlphaParam(), G4QuasiElRatios::CalcQF2IN_Ratio(), G4hhElastic::CalculateBqQ123(), G4GEMProbability::CCoeficient(), G4GeomTools::ClosestPointOnTriangle(), XrayTelDetectorConstruction::ConstructTelescope(), G4GenericPolycone::CreatePolyhedron(), G4Polyhedra::CreatePolyhedron(), G4VTwistSurface::DebugPrint(), G4Abla::DeexcitationAblaxx(), RE05DetectorConstruction::DefineMaterials(), ElectronBenchmarkDetector::DefineMaterials(), GB03DetectorConstruction::DefineMaterials(), RE06DetectorConstruction::DefineMaterials(), ExN03DetectorConstruction::DefineMaterials(), GammaRayTelDetectorConstruction::DefineMaterials(), G4EllipticalTube::DistanceToIn(), G4Ellipsoid::DistanceToIn(), G4EllipticalCone::DistanceToIn(), G4EllipticalTube::DistanceToOut(), G4Ellipsoid::DistanceToOut(), G4EllipticalCone::DistanceToOut(), G4TwistTubsSide::DistanceToPlane(), G4TwistTubsSide::DistanceToSurface(), G4hImpactIonisation::ElectronicLossFluctuation(), epsilon(), Par01EMShowerModel::Explode(), G4InuclSpecialFunctions::FermiEnergy(), G4Abla::fomega_gs(), G4RandomPointOnEllipsoid(), G4HETCTriton::GetAlpha(), G4HETCHe3::GetAlpha(), G4HETCAlpha::GetAlpha(), G4HETCProton::GetAlpha(), G4PreCompoundProton::GetAlpha(), G4HETCDeuteron::GetAlpha(), G4PreCompoundDeuteron::GetAlpha(), G4PreCompoundAlpha::GetAlpha(), G4PreCompoundHe3::GetAlpha(), G4PreCompoundTriton::GetAlpha(), G4ComponentAntiNuclNuclearXS::GetAntiHadronNucleonElCrSc(), G4ComponentAntiNuclNuclearXS::GetAntiHadronNucleonTotCrSc(), G4GEMChannelVI::GetEmissionProbability(), G4RDVeLowEnergyLoss::GetLossWithFluct(), G4InuclParamMomDst::GetMomentum(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), G4PhononDownconversion::GetTTDecayProb(), G4RDVeLowEnergyLoss::InvertRangeVector(), G4hRDEnergyLoss::InvertRangeVector(), G4Abla::lorentz_boost(), G4INCL::ThreeVector::operator*(), G4INCL::ThreeVector::operator/(), G4Bessel::pK0(), G4GeomTools::PointInTriangle(), G4Fissioner::potentialMinimization(), G4GeomTools::QuadArea(), G4GeomTools::QuadAreaNormal(), G4InuclSpecialFunctions::randomInuclPowers(), PerspectiveVisAction::RoomAndChair(), G4UniversalFluctuation::SampleFluctuations(), G4GeomTools::TriangleArea(), G4GeomTools::TriangleAreaNormal(), G4Abla::unstable_tke(), and G4Abla::width().
D()
double D (double temp)
Definition at line 91 of file G4DNAElectronHoleRecombination.cc.
Referenced by G4FissionBarrier::BarashenkovFissionBarrier(), G4hhElastic::CalculateBQ(), G4DNASmoluchowskiDiffusion::ComputeDistance(), G4DNASmoluchowskiDiffusion::ComputeS(), G4DNASmoluchowskiDiffusion::ComputeTime(), G4VTwistSurface::DebugPrint(), G4NonEquilibriumEvaporator::deExcite(), G4TriangularFacet::Distance(), G4EllipticalTube::DistanceToIn(), G4Orb::DistanceToIn(), G4EllipticalTube::DistanceToOut(), G4Orb::DistanceToOut(), G4TwistTubsSide::DistanceToPlane(), G4TwistTubsSide::DistanceToSurface(), G4TwistTubsHypeSide::DistanceToSurface(), epsilon(), G4DNASmoluchowskiDiffusion::EstimateCrossingTime(), G4UIcommand::Eval2(), G3DetTableEntry::G3DetTableEntry(), G4DNASmoluchowskiDiffusion::GetDensityProbability(), G4TripathiCrossSection::GetElementCrossSection(), G4IonsKoxCrossSection::GetElementCrossSection(), G4TripathiLightCrossSection::GetElementCrossSection(), EMField::GetFieldValue(), G4Abla::gethyperbinding(), G4DNASmoluchowskiDiffusion::GetRandomDistance(), G4DNASmoluchowskiDiffusion::GetRandomTime(), G4XTRTransparentRegRadModel::GetStackFactor(), G4TransparentRegXTRadiator::GetStackFactor(), XTRTransparentRegRadModel::GetStackFactor(), G4PhononDownconversion::GetTTDecayProb(), G4TriangularFacet::Intersect(), G4GDMLReadMaterials::MaterialRead(), G4Fissioner::potentialMinimization(), G3DetTable::Put(), G4GeomTools::QuadArea(), G4GeomTools::QuadAreaNormal(), G4AnalyticalPolSolver::QuarticRoots(), PerspectiveVisAction::RoomAndChair(), G4NeutrinoElectronCcModel::SampleCosCMS(), and G4NeutrinoElectronNcModel::SampleElectronTkin().
epsilon()
double epsilon (double density, double temperature)
Definition at line 96 of file G4DNAElectronHoleRecombination.cc.
Referenced by G4RDGenerator2BN::Calculatedsdkdt(), G4Generator2BN::Calculatedsdkdt(), G4KokoulinMuonNuclearXS::ComputeDDMicroscopicCrossSection(), G4eBremsstrahlungRelModel::ComputeDXSectionPerAtom(), G4PropagatorInField::ComputeStep(), G4VRangeToEnergyConverter::ConvertCutToKineticEnergy(), G4XPDGTotal::CrossSection(), G4AtimaEnergyLossModel::dedx_n(), G4ErrorMatrix::dfact_matrix(), G4AdjointComptonModel::DiffCrossSectionPerAtomPrimToScatPrim(), TrackerSD::EndOfEvent(), G4VSolid::EstimateCubicVolume(), G4DNAElectronHoleRecombination::FindReactant(), G4QuadrangularFacet::G4QuadrangularFacet(), G4NuclNuclDiffuseElastic::GetLegendrePol(), GetNormalizedAngularRange(), G4NeutronElectronElModel::GetTransfer(), G4hhElastic::GetTransfer(), G4ParticleHPDeExGammas::Init(), G4ErrorSymMatrix::invertBunchKaufman(), G4LowEnergyCompton::PostStepDoIt(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), ptwX_close(), ptwXY_mergeClosePoints(), ptwXY_tweakDomainsToMutualify(), XrayFluoEventAction::RandomCut(), MyKleinNishinaCompton::SampleSecondaries(), G4BoldyshevTripletModel::SampleSecondaries(), G4LivermoreGammaConversionModelRC::SampleSecondaries(), G4HeatedKleinNishinaCompton::SampleSecondaries(), G4LivermoreComptonModifiedModel::SampleSecondaries(), G4LivermoreNuclearGammaConversionModel::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4PenelopeAnnihilationModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4KleinNishinaCompton::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SetNewPolarization(), G4LowEnergyPolarizedCompton::SetNewPolarization(), G4LivermorePolarizedPhotoElectricGDModel::SetPhi(), G4Solver< Function >::SetTolerance(), G4NuclNuclDiffuseElastic::TestAngleTable(), G4DiffuseElastic::TestAngleTable(), G4NucleiModel::zoneIntegralGaussian(), and G4NucleiModel::zoneIntegralWoodsSaxon().
S()
double S (double temp)
Definition at line 77 of file G4DNAElectronHoleRecombination.cc.
Referenced by G4DNAScreenedRutherfordElasticModel::BrennerZaiderRandomizeCosTheta(), G4DNAUeharaScreenedRutherfordElasticModel::BrennerZaiderRandomizeCosTheta(), G4RPGInelastic::CheckQnums(), G4INCL::Cluster::Cluster(), G4GeomTools::comp_ellint_2(), G4INCL::Nucleus::computeSeparationEnergyBalance(), G4AngularDistribution::CosTheta(), G4AngularDistributionNP::CosTheta(), G4AngularDistributionPP::CosTheta(), G4INCL::NuclearDensityFactory::createDensity(), G4XAnnihilationChannel::CrossSection(), G4XPDGTotal::CrossSection(), G4EquilibriumEvaporator::deExcite(), G4VXResonance::DetailedBalance(), G4QGSParticipants::DeterminePartonMomenta(), G4AngularDistribution::DifferentialCrossSection(), G4DNARuddIonisationModel::DifferentialCrossSection(), G4ProjectileFragmentCrossSection::doit(), G4ElasticHNScattering::ElasticScattering(), epsilon(), G4QuarkExchange::ExciteParticipants(), G4SingleDiffractiveExcitation::ExciteParticipants(), G4QGSDiffractiveExcitation::ExciteParticipants(), G4VElasticCollision::FinalState(), G4VScatteringCollision::FinalState(), G4GIDI_Misc_Z_A_m_ToName(), G4ComponentAntiNuclNuclearXS::GetAntiHadronNucleonTotCrSc(), G4AnnihilationCrossSection::GetCrossSection(), G4TripathiCrossSection::GetElementCrossSection(), G4TripathiLightCrossSection::GetElementCrossSection(), G4INCL::ParticleTable::getINCLMass(), G4INCL::ParticleTable::getRealMass(), G4GammaAnnCrossSection::GetXsec(), G4ASCCrossSection::GetXsec(), G4GEMChannelVI::I2(), G4GEMProbability::I2(), G4GEMChannelVI::I3(), G4GEMProbability::I3(), G4FTFParameters::InitForInteraction(), G4INCL::INCL::initializeTarget(), G4INCL::CDPP::isBlocked(), G4LundStringFragmentation::lambda(), MCGIDI_KalbachMann_S_a_or_b(), MCGIDI_reaction_getENDL_CSNumbers(), G4PenelopeComptonModel::OscillatorTotalCrossSection(), G4Fissioner::potentialMinimization(), G4INCL::INCL::prepareReaction(), G4CrossSectionBuffer::push_back(), G4QGSParticipants::PutOnMassShell(), G4FTFModel::PutOnMassShell(), G4InuclSpecialFunctions::randomInuclPowers(), G4AntiNuclElastic::SampleInvariantT(), G4BoldyshevTripletModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4GammaParticipants::SelectInteractions(), G4QGSParticipants::SelectInteractions(), G4FTFParameters::SethNcmsEnergy(), G4Reggeons::SetS(), G4INCL::Cluster::setS(), G4INCL::Config::setTargetS(), G4AblaInterface::toG4Particle(), and G4AblaInterface::toG4ParticleDefinition().
Y()
double Y (double density)
Definition at line 55 of file G4DNAElectronHoleRecombination.cc.
Referenced by G4DNAPTBAugerModel::CalculAugerEnergyFor(), G4DiffractiveExcitation::CreateStrings(), epsilon(), G4ChipsAntiBaryonInelasticXS::EquLinearFit(), G4PhotoNuclearCrossSection::EquLinearFit(), G4ChipsKaonMinusInelasticXS::EquLinearFit(), G4ChipsProtonInelasticXS::EquLinearFit(), G4ChipsHyperonInelasticXS::EquLinearFit(), G4ChipsNeutronInelasticXS::EquLinearFit(), G4ChipsPionMinusInelasticXS::EquLinearFit(), G4ChipsKaonPlusInelasticXS::EquLinearFit(), G4ChipsPionPlusInelasticXS::EquLinearFit(), G4RKFieldIntegrator::Erf(), PerspectiveVisAction::ExtendedDraw(), G4Abla::fission_width(), G4Abla::fomega_sp(), G4Abla::func_trans(), G4FPYSamplingOps::G4SampleWatt(), G4ElectroNuclearCrossSection::GetEquivalentPhotonEnergy(), G4MuonicAtomHelper::GetLinApprox(), G4ParticleHPFFFissionFS::Init(), G4HETCFragment::IntegrateEmissionProbability(), LXeWLSSlab::LXeWLSSlab(), G4Abla::part_fiss(), and G4Abla::tunnelling().
Variable Documentation
onsager_constant
double onsager_constant = e_squared / (4. * pi * epsilon0 * k_Boltzmann) static
Definition at line 49 of file G4DNAElectronHoleRecombination.cc.
Referenced by G4DNAElectronHoleRecombination::FindReactant().