Geant4: G4CollisionOutput Class Reference
G4CollisionOutput Class Reference
#include <G4CollisionOutput.hh>
Public Member Functions
G4CollisionOutput ()
G4CollisionOutput & operator= (const G4CollisionOutput &right)
void setVerboseLevel (G4int verbose)
void reset ()
void add (const G4CollisionOutput &right)
void addOutgoingParticle (const G4InuclElementaryParticle &particle)
void addOutgoingParticles (const std::vector< G4InuclElementaryParticle > &particles)
void addOutgoingNucleus (const G4InuclNuclei &nuclei)
void addOutgoingNuclei (const std::vector< G4InuclNuclei > &nuclea)
void addOutgoingParticle (const G4CascadParticle &cparticle)
void addOutgoingParticles (const std::vector< G4CascadParticle > &cparticles)
void addOutgoingParticles (const G4ReactionProductVector *rproducts)
void addRecoilFragment (const G4Fragment *aFragment)
void addRecoilFragment (const G4Fragment &aFragment)
void removeOutgoingParticle (G4int index)
void removeOutgoingParticle (const G4InuclElementaryParticle &particle)
void removeOutgoingParticle (const G4InuclElementaryParticle *particle)
void removeOutgoingNucleus (G4int index)
void removeOutgoingNucleus (const G4InuclNuclei &nuclei)
void removeOutgoingNucleus (const G4InuclNuclei *nuclei)
void removeRecoilFragment (G4int index=-1)
G4int numberOfOutgoingParticles () const
const std::vector< G4InuclElementaryParticle > & getOutgoingParticles () const
std::vector< G4InuclElementaryParticle > & getOutgoingParticles ()
G4int numberOfOutgoingNuclei () const
const std::vector< G4InuclNuclei > & getOutgoingNuclei () const
std::vector< G4InuclNuclei > & getOutgoingNuclei ()
G4int numberOfFragments () const
const G4Fragment & getRecoilFragment (G4int index=0) const
const std::vector< G4Fragment > & getRecoilFragments () const
std::vector< G4Fragment > & getRecoilFragments ()
G4LorentzVector getTotalOutputMomentum () const
G4int getTotalCharge () const
G4int getTotalBaryonNumber () const
G4int getTotalStrangeness () const
void printCollisionOutput (std::ostream &os=G4cout) const
void boostToLabFrame (const G4LorentzConvertor &convertor)
G4LorentzVector boostToLabFrame (G4LorentzVector mom, const G4LorentzConvertor &convertor) const
void rotateEvent (const G4LorentzRotation &rotate)
void trivialise (G4InuclParticle *bullet, G4InuclParticle *target)
void setOnShell (G4InuclParticle *bullet, G4InuclParticle *target)
void setRemainingExitationEnergy ()
double getRemainingExitationEnergy () const
G4bool acceptable () const
Private Member Functions
std::pair< std::pair< G4int, G4int >, G4int > selectPairToTune (G4double de) const
G4bool tuneSelectedPair (G4LorentzVector &mom1, G4LorentzVector &mom2, G4int mom_index) const
Private Attributes
G4int verboseLevel
std::vector< G4InuclElementaryParticle > outgoingParticles
std::vector< G4InuclNuclei > outgoingNuclei
std::vector< G4Fragment > recoilFragments
G4double eex_rest
G4LorentzVector mom_non_cons
G4bool on_shell
Static Private Attributes
static const G4Fragment emptyFragment
Detailed Description
Definition at line 66 of file G4CollisionOutput.hh.
Constructor & Destructor Documentation
G4CollisionOutput()
G4CollisionOutput::G4CollisionOutput ()
Definition at line 83 of file G4CollisionOutput.cc.
Member Function Documentation
acceptable()
G4bool G4CollisionOutput::acceptable () const inline
Definition at line 173 of file G4CollisionOutput.hh.
Referenced by G4InuclCollider::collide(), and G4IntraNucleiCascader::finishCascade().
add()
void G4CollisionOutput::add (const G4CollisionOutput & right)
Definition at line 122 of file G4CollisionOutput.cc.
Referenced by G4InuclCollider::collide(), G4CascadeCheckBalance::collide(), G4CascadeDeexcitation::deExcite(), G4InuclCollider::deexcite(), G4IntraNucleiCascader::finalize(), and G4InuclCollider::rescatter().
addOutgoingNuclei()
void G4CollisionOutput::addOutgoingNuclei (const std::vector< G4InuclNuclei > & nuclea)
Definition at line 138 of file G4CollisionOutput.cc.
Referenced by add(), and G4CascadeCheckBalance::collide().
addOutgoingNucleus()
void G4CollisionOutput::addOutgoingNucleus (const G4InuclNuclei & nuclei) inline
Definition at line 85 of file G4CollisionOutput.hh.
Referenced by G4CascadeCoalescence::createNuclei(), and G4EquilibriumEvaporator::deExcite().
addOutgoingParticle() [1/2]
void G4CollisionOutput::addOutgoingParticle (const G4CascadParticle & cparticle)
Definition at line 144 of file G4CollisionOutput.cc.
addOutgoingParticle() [2/2]
void G4CollisionOutput::addOutgoingParticle (const G4InuclElementaryParticle & particle) inline
Definition at line 79 of file G4CollisionOutput.hh.
Referenced by addOutgoingParticle(), addOutgoingParticles(), G4IntraNucleiCascader::decayTrappedParticle(), G4NonEquilibriumEvaporator::deExcite(), G4EquilibriumEvaporator::deExcite(), G4IntraNucleiCascader::finishCascade(), G4IntraNucleiCascader::generateCascade(), and G4IntraNucleiCascader::processTrappedParticle().
addOutgoingParticles() [1/3]
void G4CollisionOutput::addOutgoingParticles (const G4ReactionProductVector * rproducts)
Definition at line 155 of file G4CollisionOutput.cc.
addOutgoingParticles() [2/3]
void G4CollisionOutput::addOutgoingParticles (const std::vector< G4CascadParticle > & cparticles)
Definition at line 148 of file G4CollisionOutput.cc.
addOutgoingParticles() [3/3]
void G4CollisionOutput::addOutgoingParticles (const std::vector< G4InuclElementaryParticle > & particles)
Definition at line 133 of file G4CollisionOutput.cc.
Referenced by add(), G4ElementaryParticleCollider::collide(), G4CascadeCheckBalance::collide(), G4BigBanger::deExcite(), G4CascadeDeexcitation::deExcite(), G4PreCompoundDeexcitation::deExcite(), G4IntraNucleiCascader::finishCascade(), and G4IntraNucleiCascader::setupCascade().
addRecoilFragment() [1/2]
void G4CollisionOutput::addRecoilFragment (const G4Fragment & aFragment) inline
Definition at line 102 of file G4CollisionOutput.hh.
addRecoilFragment() [2/2]
void G4CollisionOutput::addRecoilFragment (const G4Fragment * aFragment) inline
Definition at line 98 of file G4CollisionOutput.hh.
Referenced by G4NonEquilibriumEvaporator::deExcite(), G4Fissioner::deExcite(), G4EquilibriumEvaporator::deExcite(), and G4IntraNucleiCascader::finishCascade().
boostToLabFrame() [1/2]
void G4CollisionOutput::boostToLabFrame (const G4LorentzConvertor & convertor)
Definition at line 328 of file G4CollisionOutput.cc.
Referenced by G4InuclCollider::collide(), and G4EquilibriumEvaporator::deExcite().
boostToLabFrame() [2/2]
G4LorentzVector G4CollisionOutput::boostToLabFrame (G4LorentzVector mom, const G4LorentzConvertor & convertor) const
Definition at line 356 of file G4CollisionOutput.cc.
getOutgoingNuclei() [1/2]
std::vector<G4InuclNuclei>& G4CollisionOutput::getOutgoingNuclei () inline
Definition at line 140 of file G4CollisionOutput.hh.
getOutgoingNuclei() [2/2]
const std::vector<G4InuclNuclei>& G4CollisionOutput::getOutgoingNuclei () const inline
Definition at line 136 of file G4CollisionOutput.hh.
Referenced by G4Analyser::analyse(), G4InuclEvaporation::BreakItUp(), G4CascadeInterface::copyOutputToHadronicResult(), G4CascadeInterface::copyOutputToReactionProducts(), G4EquilibriumEvaporator::deExcite(), G4InuclCollider::photonuclearOkay(), and G4IntraNucleiCascader::releaseSecondary().
getOutgoingParticles() [1/2]
std::vector<G4InuclElementaryParticle>& G4CollisionOutput::getOutgoingParticles () inline
Definition at line 130 of file G4CollisionOutput.hh.
getOutgoingParticles() [2/2]
const std::vector<G4InuclElementaryParticle>& G4CollisionOutput::getOutgoingParticles () const inline
Definition at line 126 of file G4CollisionOutput.hh.
Referenced by G4Analyser::analyse(), G4InuclEvaporation::BreakItUp(), G4CascadeCheckBalance::collide(), G4CascadeInterface::copyOutputToHadronicResult(), G4CascadeInterface::copyOutputToReactionProducts(), G4CascadeInterface::coulombBarrierViolation(), G4CascadeDeexcitation::deExcite(), G4EquilibriumEvaporator::deExcite(), G4CascadeCoalescence::FindClusters(), G4IntraNucleiCascader::finishCascade(), G4IntraNucleiCascader::generateCascade(), G4NucleiModel::generateParticleFate(), G4IntraNucleiCascader::releaseSecondary(), G4CascadeInterface::retryInelasticNucleus(), and G4CascadeInterface::retryInelasticProton().
getRecoilFragment()
const G4Fragment & G4CollisionOutput::getRecoilFragment (G4int index = 0) const
Definition at line 114 of file G4CollisionOutput.cc.
Referenced by G4InuclCollider::collide(), G4NonEquilibriumEvaporator::deExcite(), G4CascadeDeexcitation::deExcite(), G4EquilibriumEvaporator::deExcite(), and G4InuclCollider::rescatter().
getRecoilFragments() [1/2]
std::vector<G4Fragment>& G4CollisionOutput::getRecoilFragments () inline
Definition at line 150 of file G4CollisionOutput.hh.
getRecoilFragments() [2/2]
const std::vector<G4Fragment>& G4CollisionOutput::getRecoilFragments () const inline
Definition at line 146 of file G4CollisionOutput.hh.
getRemainingExitationEnergy()
double G4CollisionOutput::getRemainingExitationEnergy () const inline
Definition at line 172 of file G4CollisionOutput.hh.
getTotalBaryonNumber()
G4int G4CollisionOutput::getTotalBaryonNumber () const
Definition at line 277 of file G4CollisionOutput.cc.
Referenced by G4CascadeCheckBalance::collide().
getTotalCharge()
G4int G4CollisionOutput::getTotalCharge () const
Definition at line 250 of file G4CollisionOutput.cc.
Referenced by G4CascadeCheckBalance::collide().
getTotalOutputMomentum()
G4LorentzVector G4CollisionOutput::getTotalOutputMomentum () const
Definition at line 231 of file G4CollisionOutput.cc.
Referenced by G4CascadeCheckBalance::collide(), and setOnShell().
getTotalStrangeness()
G4int G4CollisionOutput::getTotalStrangeness () const
Definition at line 296 of file G4CollisionOutput.cc.
Referenced by G4CascadeCheckBalance::collide().
numberOfFragments()
G4int G4CollisionOutput::numberOfFragments () const inline
Definition at line 142 of file G4CollisionOutput.hh.
Referenced by G4EquilibriumEvaporator::deExcite(), getRecoilFragment(), getTotalBaryonNumber(), getTotalCharge(), getTotalOutputMomentum(), printCollisionOutput(), removeRecoilFragment(), setOnShell(), and setRemainingExitationEnergy().
numberOfOutgoingNuclei()
G4int G4CollisionOutput::numberOfOutgoingNuclei () const inline
Definition at line 134 of file G4CollisionOutput.hh.
Referenced by addOutgoingParticles(), G4IntraNucleiCascader::copySecondaries(), getTotalBaryonNumber(), getTotalCharge(), getTotalOutputMomentum(), G4InuclCollider::photonuclearOkay(), printCollisionOutput(), G4IntraNucleiCascader::releaseSecondary(), removeOutgoingNucleus(), G4CascadeInterface::retryInelasticNucleus(), setOnShell(), and setRemainingExitationEnergy().
numberOfOutgoingParticles()
G4int G4CollisionOutput::numberOfOutgoingParticles () const inline
Definition at line 124 of file G4CollisionOutput.hh.
Referenced by addOutgoingParticles(), G4CascadeCheckBalance::collide(), G4IntraNucleiCascader::copySecondaries(), G4NonEquilibriumEvaporator::deExcite(), G4IntraNucleiCascader::finishCascade(), G4NucleiModel::generateParticleFate(), getTotalBaryonNumber(), getTotalCharge(), getTotalOutputMomentum(), getTotalStrangeness(), printCollisionOutput(), G4IntraNucleiCascader::releaseSecondary(), removeOutgoingParticle(), G4CascadeInterface::retryInelasticNucleus(), and setOnShell().
operator=()
G4CollisionOutput & G4CollisionOutput::operator= (const G4CollisionOutput & right)
Definition at line 90 of file G4CollisionOutput.cc.
printCollisionOutput()
void G4CollisionOutput::printCollisionOutput (std::ostream & os = G4cout) const
Definition at line 310 of file G4CollisionOutput.cc.
Referenced by G4CascadeInterface::ApplyYourself(), G4EvaporationInuclCollider::deExcite(), G4CascadeDeexcitation::deExcite(), G4CascadeCoalescence::FindClusters(), G4IntraNucleiCascader::finishCascade(), G4NucleiModel::generateParticleFate(), G4CascadeInterface::Propagate(), setOnShell(), G4CascadeInterface::throwNonConservationFailure(), and G4CascadeColliderBase::validateOutput().
removeOutgoingNucleus() [1/3]
void G4CollisionOutput::removeOutgoingNucleus (const G4InuclNuclei & nuclei)
Definition at line 214 of file G4CollisionOutput.cc.
removeOutgoingNucleus() [2/3]
void G4CollisionOutput::removeOutgoingNucleus (const G4InuclNuclei * nuclei) inline
Definition at line 116 of file G4CollisionOutput.hh.
removeOutgoingNucleus() [3/3]
void G4CollisionOutput::removeOutgoingNucleus (G4int index)
Definition at line 201 of file G4CollisionOutput.cc.
Referenced by removeOutgoingNucleus().
removeOutgoingParticle() [1/3]
void G4CollisionOutput::removeOutgoingParticle (const G4InuclElementaryParticle & particle)
Definition at line 208 of file G4CollisionOutput.cc.
removeOutgoingParticle() [2/3]
void G4CollisionOutput::removeOutgoingParticle (const G4InuclElementaryParticle * particle) inline
Definition at line 110 of file G4CollisionOutput.hh.
removeOutgoingParticle() [3/3]
void G4CollisionOutput::removeOutgoingParticle (G4int index)
Definition at line 196 of file G4CollisionOutput.cc.
Referenced by G4CascadeCoalescence::removeNucleons(), and removeOutgoingParticle().
removeRecoilFragment()
void G4CollisionOutput::removeRecoilFragment (G4int index = -1)
Definition at line 222 of file G4CollisionOutput.cc.
Referenced by G4InuclCollider::collide(), and G4InuclCollider::rescatter().
reset()
void G4CollisionOutput::reset ()
Definition at line 103 of file G4CollisionOutput.cc.
Referenced by G4CascadeInterface::ApplyYourself(), G4InuclCollider::collide(), G4CascadeCheckBalance::collide(), G4CascadeDeexcitation::deExcite(), G4EquilibriumEvaporator::deExcite(), G4InuclCollider::deexcite(), G4NucleiModel::generateParticleFate(), G4IntraNucleiCascader::newCascade(), G4CascadeInterface::Propagate(), G4InuclCollider::rescatter(), and trivialise().
rotateEvent()
void G4CollisionOutput::rotateEvent (const G4LorentzRotation & rotate)
Definition at line 367 of file G4CollisionOutput.cc.
selectPairToTune()
std::pair< std::pair< G4int, G4int >, G4int > G4CollisionOutput::selectPairToTune (G4double de) const private
Definition at line 629 of file G4CollisionOutput.cc.
Referenced by setOnShell().
setOnShell()
void G4CollisionOutput::setOnShell (G4InuclParticle * bullet, G4InuclParticle * target)
Definition at line 412 of file G4CollisionOutput.cc.
Referenced by G4InuclCollider::collide(), and G4IntraNucleiCascader::finishCascade().
setRemainingExitationEnergy()
void G4CollisionOutput::setRemainingExitationEnergy ()
Definition at line 618 of file G4CollisionOutput.cc.
Referenced by setOnShell().
setVerboseLevel()
void G4CollisionOutput::setVerboseLevel (G4int verbose) inline
Definition at line 71 of file G4CollisionOutput.hh.
Referenced by G4PreCompoundDeexcitation::deExcite(), G4IntraNucleiCascader::finishCascade(), G4InuclCollider::setVerboseLevel(), and G4CascadeInterface::SetVerboseLevel().
trivialise()
void G4CollisionOutput::trivialise (G4InuclParticle * bullet, G4InuclParticle * target)
Definition at line 387 of file G4CollisionOutput.cc.
Referenced by G4InuclCollider::collide(), and G4IntraNucleiCascader::finalize().
tuneSelectedPair()
G4bool G4CollisionOutput::tuneSelectedPair (G4LorentzVector & mom1, G4LorentzVector & mom2, G4int mom_index) const private
Definition at line 686 of file G4CollisionOutput.cc.
Referenced by setOnShell().
Field Documentation
eex_rest
G4double G4CollisionOutput::eex_rest private
Definition at line 187 of file G4CollisionOutput.hh.
Referenced by add(), getRemainingExitationEnergy(), operator=(), reset(), setOnShell(), and setRemainingExitationEnergy().
emptyFragment
const G4Fragment G4CollisionOutput::emptyFragment static private
Definition at line 181 of file G4CollisionOutput.hh.
Referenced by getRecoilFragment().
mom_non_cons
G4LorentzVector G4CollisionOutput::mom_non_cons private
Definition at line 188 of file G4CollisionOutput.hh.
Referenced by setOnShell(), and tuneSelectedPair().
on_shell
G4bool G4CollisionOutput::on_shell private
Definition at line 189 of file G4CollisionOutput.hh.
Referenced by add(), operator=(), reset(), and setOnShell().
outgoingNuclei
std::vector<G4InuclNuclei> G4CollisionOutput::outgoingNuclei private
Definition at line 179 of file G4CollisionOutput.hh.
Referenced by addOutgoingNuclei(), addOutgoingNucleus(), addOutgoingParticles(), boostToLabFrame(), getOutgoingNuclei(), getTotalBaryonNumber(), getTotalCharge(), getTotalOutputMomentum(), numberOfOutgoingNuclei(), operator=(), printCollisionOutput(), removeOutgoingNucleus(), reset(), rotateEvent(), setOnShell(), setRemainingExitationEnergy(), and trivialise().
outgoingParticles
std::vector<G4InuclElementaryParticle> G4CollisionOutput::outgoingParticles private
Definition at line 178 of file G4CollisionOutput.hh.
Referenced by addOutgoingParticle(), addOutgoingParticles(), boostToLabFrame(), getOutgoingParticles(), getTotalBaryonNumber(), getTotalCharge(), getTotalOutputMomentum(), getTotalStrangeness(), numberOfOutgoingParticles(), operator=(), printCollisionOutput(), removeOutgoingParticle(), reset(), rotateEvent(), selectPairToTune(), setOnShell(), and trivialise().
recoilFragments
std::vector<G4Fragment> G4CollisionOutput::recoilFragments private
Definition at line 180 of file G4CollisionOutput.hh.
Referenced by add(), addRecoilFragment(), boostToLabFrame(), getRecoilFragment(), getRecoilFragments(), getTotalBaryonNumber(), getTotalCharge(), getTotalOutputMomentum(), numberOfFragments(), operator=(), printCollisionOutput(), removeRecoilFragment(), reset(), rotateEvent(), setOnShell(), and setRemainingExitationEnergy().
verboseLevel
G4int G4CollisionOutput::verboseLevel private
Definition at line 173 of file G4CollisionOutput.hh.
Referenced by addOutgoingParticles(), boostToLabFrame(), G4CollisionOutput(), getTotalBaryonNumber(), getTotalCharge(), getTotalOutputMomentum(), getTotalStrangeness(), operator=(), rotateEvent(), selectPairToTune(), setOnShell(), setVerboseLevel(), trivialise(), and tuneSelectedPair().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/cascade/cascade/include/G4CollisionOutput.hh
source/processes/hadronic/models/cascade/cascade/src/G4CollisionOutput.cc