Geant4: G4Step Class Reference
G4Step Class Reference
#include <G4Step.hh>
Public Member Functions
G4Step ()
~G4Step ()
G4Step (const G4Step &)
G4Step & operator= (const G4Step &)
G4Track * GetTrack () const
void SetTrack (G4Track *value)
G4StepPoint * GetPreStepPoint () const
void SetPreStepPoint (G4StepPoint *value)
G4StepPoint * GetPostStepPoint () const
void SetPostStepPoint (G4StepPoint *value)
G4double GetStepLength () const
void SetStepLength (G4double value)
G4double GetTotalEnergyDeposit () const
void SetTotalEnergyDeposit (G4double value)
G4double GetNonIonizingEnergyDeposit () const
void SetNonIonizingEnergyDeposit (G4double value)
G4SteppingControl GetControlFlag () const
void SetControlFlag (G4SteppingControl StepControlFlag)
void AddTotalEnergyDeposit (G4double value)
void ResetTotalEnergyDeposit ()
void AddNonIonizingEnergyDeposit (G4double value)
void ResetNonIonizingEnergyDeposit ()
G4bool IsFirstStepInVolume () const
G4bool IsLastStepInVolume () const
void SetFirstStepFlag ()
void ClearFirstStepFlag ()
void SetLastStepFlag ()
void ClearLastStepFlag ()
G4ThreeVector GetDeltaPosition () const
G4double GetDeltaTime () const
G4ThreeVector GetDeltaMomentum () const
G4double GetDeltaEnergy () const
void InitializeStep (G4Track *aValue)
void UpdateTrack ()
void CopyPostToPreStepPoint ()
G4Polyline * CreatePolyline () const
G4int GetNumberOfSecondariesInCurrentStep () const
const std::vector< const G4Track * > * GetSecondaryInCurrentStep () const
const G4TrackVector * GetSecondary () const
G4TrackVector * GetfSecondary ()
G4TrackVector * NewSecondaryVector ()
void DeleteSecondaryVector ()
void SetSecondary (G4TrackVector *value)
void SetPointerToVectorOfAuxiliaryPoints (std::vector< G4ThreeVector > *theNewVectorPointer)
std::vector< G4ThreeVector > * GetPointerToVectorOfAuxiliaryPoints () const
Protected Attributes
G4double fTotalEnergyDeposit
G4double fNonIonizingEnergyDeposit
Private Attributes
const typedef G4Track * CT
G4StepPoint * fpPreStepPoint
G4StepPoint * fpPostStepPoint
G4double fStepLength
G4Track * fpTrack
G4SteppingControl fpSteppingControlFlag
G4bool fFirstStepInVolume
G4bool fLastStepInVolume
G4TrackVector * fSecondary
G4int nSecondaryByLastStep
std::vector< CT > * secondaryInCurrentStep
std::vector< G4ThreeVector > * fpVectorOfAuxiliaryPointsPointer
Detailed Description
Definition at line 75 of file G4Step.hh.
Constructor & Destructor Documentation
G4Step() [1/2]
G4Step::G4Step ()
Definition at line 52 of file G4Step.cc.
~G4Step()
G4Step::~G4Step ()
Definition at line 70 of file G4Step.cc.
G4Step() [2/2]
G4Step::G4Step (const G4Step & right)
Definition at line 92 of file G4Step.cc.
Member Function Documentation
AddNonIonizingEnergyDeposit()
void G4Step::AddNonIonizingEnergyDeposit (G4double value)
Referenced by G4ParticleChangeForLoss::UpdateStepForAlongStep(), G4ParticleChangeForGamma::UpdateStepForPostStep(), G4ParticleChangeForLoss::UpdateStepForPostStep(), and G4VParticleChange::UpdateStepInfo().
AddTotalEnergyDeposit()
void G4Step::AddTotalEnergyDeposit (G4double value)
Referenced by G4SteppingManager::ApplyProductionCut(), G4UCNBoundaryProcess::InvokeSD(), G4OpBoundaryProcess::InvokeSD(), G4ParticleChangeForLoss::UpdateStepForAlongStep(), G4ParticleChangeForGamma::UpdateStepForAtRest(), G4ParticleChangeForGamma::UpdateStepForPostStep(), G4ParticleChangeForLoss::UpdateStepForPostStep(), and G4VParticleChange::UpdateStepInfo().
ClearFirstStepFlag()
void G4Step::ClearFirstStepFlag ()
Referenced by G4ParticleChangeForTransport::UpdateStepForPostStep(), and G4VParticleChange::UpdateStepInfo().
ClearLastStepFlag()
void G4Step::ClearLastStepFlag ()
Referenced by G4ParticleChangeForTransport::UpdateStepForPostStep(), and G4VParticleChange::UpdateStepInfo().
CopyPostToPreStepPoint()
void G4Step::CopyPostToPreStepPoint ()
Referenced by G4ITStepProcessor::InitDefineStep(), and G4SteppingManager::Stepping().
CreatePolyline()
G4Polyline* G4Step::CreatePolyline () const
DeleteSecondaryVector()
void G4Step::DeleteSecondaryVector ()
Referenced by G4ITStepProcessor::~G4ITStepProcessor(), and G4SteppingManager::~G4SteppingManager().
GetControlFlag()
G4SteppingControl G4Step::GetControlFlag () const
Referenced by G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), and G4SteppingManager::Stepping().
GetDeltaEnergy()
G4double G4Step::GetDeltaEnergy () const
Definition at line 193 of file G4Step.cc.
Referenced by export_G4Step().
GetDeltaMomentum()
G4ThreeVector G4Step::GetDeltaMomentum () const
Definition at line 176 of file G4Step.cc.
Referenced by export_G4Step().
GetDeltaPosition()
G4ThreeVector G4Step::GetDeltaPosition () const
Referenced by export_G4Step(), G4Cerenkov::PostStepDoIt(), and G4Scintillation::PostStepDoIt().
GetDeltaTime()
G4double G4Step::GetDeltaTime () const
Referenced by export_G4Step(), G4DNASmoluchowskiReactionModel::FindReaction(), and G4DNABrownianTransportation::PostStepDoIt().
GetfSecondary()
G4TrackVector* G4Step::GetfSecondary ()
Referenced by G4SteppingManager::GetfSecondary(), and G4ITStepProcessor::SetupMembers().
GetNonIonizingEnergyDeposit()
G4double G4Step::GetNonIonizingEnergyDeposit () const
Referenced by G4ParallelWorldProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), G4ElectronIonPair::MeanNumberOfIonsAlongStep(), G4ScoreSplittingProcess::PostStepDoIt(), XAluminumElectrodeSensitivity::ProcessHits(), and G4EmSaturation::VisibleEnergyDepositionAtAStep().
GetNumberOfSecondariesInCurrentStep()
G4int G4Step::GetNumberOfSecondariesInCurrentStep () const
GetPointerToVectorOfAuxiliaryPoints()
std::vector<G4ThreeVector>* G4Step::GetPointerToVectorOfAuxiliaryPoints () const inline
Definition at line 241 of file G4Step.hh.
Referenced by G4SmoothTrajectory::AppendStep().
GetPostStepPoint()
G4StepPoint* G4Step::GetPostStepPoint () const
Referenced by HistoManager::AddTargetStep(), G4VAtomDeexcitation::AlongStepDeexcitation(), G4NuclearStopping::AlongStepDoIt(), G4AdjointForcedInteractionForGamma::AlongStepDoIt(), G4AdjointAlongStepWeightCorrection::AlongStepDoIt(), G4ContinuousGainOfEnergy::AlongStepDoIt(), G4eLowEnergyLoss::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepDoIt(), G4VMultipleScattering::AlongStepDoIt(), XrayFluoAnalysisManager::analyseStepping(), RE01Trajectory::AppendStep(), G4RichTrajectory::AppendStep(), G4SmoothTrajectory::AppendStep(), G4Trajectory::AppendStep(), RE04Trajectory::AppendStep(), G4BOptnForceFreeFlight::ApplyFinalStateBiasing(), G4DecayWithSpin::AtRestDoIt(), G4eplusAnnihilation::AtRestDoIt(), G4DNABrownianTransportation::ComputeStep(), G4VITSteppingVerbose::CopyState(), G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), G4AdjointCrossSurfChecker::CrossingAGivenRegisteredSurface(), G4AdjointCrossSurfChecker::CrossingAnInterfaceBetweenTwoVolumes(), G4AdjointCrossSurfChecker::CrossingASphere(), G4SteppingManager::DefinePhysicalStepLength(), G4ITStepProcessor::DoDefinePhysicalStepLength(), G4ExceptionHandler::DumpTrackInfo(), export_G4Step(), F04TrajectoryPoint::F04TrajectoryPoint(), G4ImportanceProcess::G4ImportanceProcess(), G4ParallelWorldProcess::G4ParallelWorldProcess(), G4ParallelWorldScoringProcess::G4ParallelWorldScoringProcess(), G4RichTrajectoryPoint::G4RichTrajectoryPoint(), G4ScoreSplittingProcess::G4ScoreSplittingProcess(), G4SteppingManager::G4SteppingManager(), G4WeightCutOffProcess::G4WeightCutOffProcess(), G4WeightWindowProcess::G4WeightWindowProcess(), GB03BOptnSplitOrKillOnBoundary::GenerateBiasingFinalState(), G4Channeling::GetPost(), G4Scintillation::GetScintillationYieldByParticleType(), CCaloSD::getStepInfo(), G4AdjointCrossSurfChecker::GoingInOrOutOfaVolume(), G4AdjointCrossSurfChecker::GoingInOrOutOfaVolumeByExtSurface(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePostStepDoItProcs(), G4SteppingManager::InvokePSDIP(), G4UCNBoundaryProcess::InvokeSD(), G4OpBoundaryProcess::InvokeSD(), G4PSPassageTrackLength::IsPassed(), G4PSPassageCellCurrent::IsPassed(), G4PSPassageCellFlux::IsPassed(), G4PSSphereSurfaceCurrent::IsSelectedSurface(), G4PSCylinderSurfaceFlux::IsSelectedSurface(), G4PSFlatSurfaceCurrent::IsSelectedSurface(), G4PSSphereSurfaceFlux::IsSelectedSurface(), G4PSCylinderSurfaceCurrent::IsSelectedSurface(), G4PSFlatSurfaceFlux::IsSelectedSurface(), G4ErrorPropagator::MakeOneStep(), Par01EMShowerModel::Par01EMShowerModel(), Par01PionShowerModel::Par01PionShowerModel(), G4PhononScattering::PostStepDoIt(), G4PhononReflection::PostStepDoIt(), G4Channeling::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4LowEnergyCompton::PostStepDoIt(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4WeightCutOffProcess::PostStepDoIt(), G4ImportanceProcess::PostStepDoIt(), G4WeightWindowProcess::PostStepDoIt(), G4UCNAbsorption::PostStepDoIt(), G4UCNMultiScattering::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4ScoreSplittingProcess::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4ITSteppingVerbose::PostStepVerbose(), eRositaTrackerSD::ProcessHits(), LXeScintSD::ProcessHits(), ExTGTrackerSD::ProcessHits(), XAluminumElectrodeSensitivity::ProcessHits(), ExN02TrackerSD::ProcessHits(), G4PSNofCollision::ProcessHits(), G4PSTrackCounter::ProcessHits(), G4PSCellCharge::ProcessHits(), ExP01TrackerSD::ProcessHits(), B2TrackerSD::ProcessHits(), TrackerSD::ProcessHits(), DMXScintSD::ProcessHits(), PhantomSD::ProcessHits(), DMXPmtSD::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), PrimaryKiller::ProcessHits(), LXePMTSD::ProcessHits_constStep(), WLSPhotonDetSD::ProcessHits_constStep(), G4ElectronIonPair::ResidualeChargePostStep(), G4ElectronIonPair::SampleIonsAlongStep(), G4VEnergyLossProcess::SampleSubCutSecondaries(), G4ITStepProcessor::SetupMembers(), G4SteppingVerbose::ShowStep(), G4ScoreSplittingProcess::StartTracking(), G4ParallelWorldProcess::StartTracking(), F04SteppingVerbose::StepInfo(), WLSSteppingVerbose::StepInfo(), ExN04SteppingVerbose::StepInfo(), SteppingVerbose::StepInfo(), eRositaSteppingVerbose::StepInfo(), FCALSteppingVerbose::StepInfo(), OpNoviceSteppingVerbose::StepInfo(), XrayFluoSteppingVerbose::StepInfo(), PurgMagSteppingVerbose::StepInfo(), ExN02SteppingVerbose::StepInfo(), RE05SteppingVerbose::StepInfo(), ExP01SteppingVerbose::StepInfo(), F05SteppingVerbose::StepInfo(), G4SteppingVerbose::StepInfo(), F03SteppingVerbose::StepInfo(), F02SteppingVerbose::StepInfo(), F01SteppingVerbose::StepInfo(), G4SteppingManager::Stepping(), G4ParallelWorldProcess::SwitchMaterial(), G4Channeling::UpdateParameters(), G4ParticleChangeForOccurenceBiasing::UpdateStepForAlongStep(), G4ParticleChangeForLoss::UpdateStepForAlongStep(), G4ParticleChangeForMSC::UpdateStepForAlongStep(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), G4ParticleChangeForGamma::UpdateStepForAtRest(), G4ParticleChangeForDecay::UpdateStepForAtRest(), G4ParticleChange::UpdateStepForAtRest(), G4FastStep::UpdateStepForAtRest(), G4ParticleChangeForOccurenceBiasing::UpdateStepForPostStep(), G4ParticleChangeForGamma::UpdateStepForPostStep(), G4ParticleChangeForLoss::UpdateStepForPostStep(), G4ParticleChangeForMSC::UpdateStepForPostStep(), G4ParticleChangeForTransport::UpdateStepForPostStep(), G4ParticleChangeForDecay::UpdateStepForPostStep(), G4ParticleChange::UpdateStepForPostStep(), G4FastStep::UpdateStepForPostStep(), ExN04SteppingAction::UserSteppingAction(), RE01SteppingAction::UserSteppingAction(), RE05SteppingAction::UserSteppingAction(), CCalSteppingAction::UserSteppingAction(), RE04SteppingAction::UserSteppingAction(), LXeSteppingAction::UserSteppingAction(), F05SteppingAction::UserSteppingAction(), F04SteppingAction::UserSteppingAction(), XrayFluoSteppingAction::UserSteppingAction(), HadrontherapySteppingAction::UserSteppingAction(), doiPETSteppingAction::UserSteppingAction(), WLSSteppingAction::UserSteppingAction(), PurgMagSteppingAction::UserSteppingAction(), CexmcSteppingAction::UserSteppingAction(), DMXSteppingAction::UserSteppingAction(), G4AdjointSteppingAction::UserSteppingAction(), G4ScoreSplittingProcess::Verbose(), G4ParallelWorldScoringProcess::Verbose(), and WLSTrajectoryPoint::WLSTrajectoryPoint().
GetPreStepPoint()
G4StepPoint* G4Step::GetPreStepPoint () const
Referenced by G4SDChargedFilter::Accept(), G4SDNeutralFilter::Accept(), G4SDKineticEnergyFilter::Accept(), CML2ExpVoxels::add(), HistoManager::AddTargetStep(), G4VAtomDeexcitation::AlongStepDeexcitation(), G4Transportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), G4NuclearStopping::AlongStepDoIt(), G4eLowEnergyLoss::AlongStepDoIt(), G4ITTransportation::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepDoIt(), XrayFluoAnalysisManager::analyseStepping(), G4RichTrajectory::AppendStep(), RE04Trajectory::AppendStep(), Par01PionShowerModel::AssignSpotAndCallHit(), Par01EMShowerModel::AssignSpotAndCallHit(), G4VReadOutGeometry::CheckROVolume(), G4VMscModel::ComputeGeomLimit(), G4DNABrownianTransportation::ComputeGeomLimit(), G4DNABrownianTransportation::ComputeStep(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTruePathLengthLimit(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), G4PSDoseDeposit::ComputeVolume(), G4PSPassageCellFlux::ComputeVolume(), G4PSCellFlux::ComputeVolume(), G4VITSteppingVerbose::CopyState(), G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), G4AdjointCrossSurfChecker::CrossingAnInterfaceBetweenTwoVolumes(), G4AdjointCrossSurfChecker::CrossingASphere(), CCalVOrganization::DetectorLevel(), G4ExceptionHandler::DumpTrackInfo(), G4CellScoreComposer::EstimatorCalculation(), export_G4Step(), G4DNASmoluchowskiReactionModel::FindReaction(), G4VReadOutGeometry::FindROTouchable(), G4ImportanceProcess::G4ImportanceProcess(), G4ParallelWorldProcess::G4ParallelWorldProcess(), G4ParallelWorldScoringProcess::G4ParallelWorldScoringProcess(), G4RichTrajectoryPoint::G4RichTrajectoryPoint(), G4ScoreSplittingProcess::G4ScoreSplittingProcess(), G4SteppingManager::G4SteppingManager(), G4WeightCutOffProcess::G4WeightCutOffProcess(), G4WeightWindowProcess::G4WeightWindowProcess(), RE02PSEnergyDeposit::GetIndex(), G4PSNofSecondary3D::GetIndex(), RE02PSNofStep::GetIndex(), G4PSNofStep3D::GetIndex(), G4PSTermination3D::GetIndex(), G4PSPopulation3D::GetIndex(), G4PSStepChecker3D::GetIndex(), G4PSEnergyDeposit3D::GetIndex(), G4PSNofCollision3D::GetIndex(), G4PSPassageCellCurrent3D::GetIndex(), G4PSTrackCounter3D::GetIndex(), RE02PSPassageCellFlux::GetIndex(), G4PSDoseDeposit3D::GetIndex(), G4PSCellCharge3D::GetIndex(), G4PSMinKinEAtGeneration3D::GetIndex(), G4PSTrackLength3D::GetIndex(), G4PSPassageTrackLength3D::GetIndex(), G4PSPassageCellFlux3D::GetIndex(), RE02PSCellFlux::GetIndex(), G4VPrimitiveScorer::GetIndex(), CexmcTrackPointsInCalorimeter::GetIndex(), CexmcEnergyDepositInCalorimeter::GetIndex(), RE02PSFlatSurfaceCurrent::GetIndex(), G4PSCellFlux3D::GetIndex(), CexmcTrackPointsInLeftRightSet::GetIndex(), CexmcEnergyDepositInLeftRightSet::GetIndex(), RE02PSFlatSurfaceFlux::GetIndex(), G4PSCylinderSurfaceCurrent3D::GetIndex(), G4PSCylinderSurfaceFlux3D::GetIndex(), G4PSFlatSurfaceCurrent3D::GetIndex(), G4PSSphereSurfaceCurrent3D::GetIndex(), G4PSSphereSurfaceFlux3D::GetIndex(), G4PSFlatSurfaceFlux3D::GetIndex(), G4NeutrinoElectronProcess::GetMeanFreePath(), G4Channeling::GetPre(), G4Scintillation::GetScintillationYieldByParticleType(), CCaloSD::getStepInfo(), CCalEcalOrganization::GetUnitID(), CCalHcalOrganization::GetUnitID(), G4AdjointCrossSurfChecker::GoingInOrOutOfaVolume(), G4AdjointCrossSurfChecker::GoingInOrOutOfaVolumeByExtSurface(), G4VGFlashSensitiveDetector::Hit(), G4ITStepProcessor::InitDefineStep(), G4PSPassageTrackLength::IsPassed(), G4PSPassageCellCurrent::IsPassed(), G4PSPassageCellFlux::IsPassed(), G4PSSphereSurfaceCurrent::IsSelectedSurface(), G4PSCylinderSurfaceFlux::IsSelectedSurface(), G4PSSphereSurfaceFlux::IsSelectedSurface(), G4PSCylinderSurfaceCurrent::IsSelectedSurface(), G4PSFlatSurfaceCurrent::IsSelectedSurface(), G4PSFlatSurfaceFlux::IsSelectedSurface(), CCalVOrganization::Levels(), G4ElectronIonPair::MeanNumberOfIonsAlongStep(), RE06SteppingVerbose::NewStep(), Par01EMShowerModel::Par01EMShowerModel(), Par01PionShowerModel::Par01PionShowerModel(), SplitProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VTransitionRadiation::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4ImportanceProcess::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4ScoreSplittingProcess::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4AdjointForcedInteractionForGamma::PostStepGetPhysicalInteractionLength(), G4BiasingProcessInterface::PostStepGetPhysicalInteractionLength(), GB05SD::ProcessHits(), GB06SD::ProcessHits(), G4HumanPhantomSD::ProcessHits(), ScreenSD::ProcessHits(), ExN04TrackerSD::ProcessHits(), RE05CalorimeterSD::ProcessHits(), RE05TrackerSD::ProcessHits(), ExN04MuonSD::ProcessHits(), Par01CalorimeterSD::ProcessHits(), RE05MuonSD::ProcessHits(), HadrontherapyDetectorSD::ProcessHits(), ExTGTrackerSD::ProcessHits(), eRositaTrackerSD::ProcessHits(), B5HodoscopeSD::ProcessHits(), LXeScintSD::ProcessHits(), B5HadCalorimeterSD::ProcessHits(), RE01TrackerSD::ProcessHits(), B5DriftChamberSD::ProcessHits(), B5EmCalorimeterSD::ProcessHits(), XAluminumElectrodeSensitivity::ProcessHits(), RE01CalorimeterSD::ProcessHits(), ExN02TrackerSD::ProcessHits(), ExGflashSensitiveDetector::ProcessHits(), G4PSDoseDeposit::ProcessHits(), G4PSEnergyDeposit::ProcessHits(), G4PSTermination::ProcessHits(), G4PSTrackCounter::ProcessHits(), G4PSCellCharge::ProcessHits(), F02CalorimeterSD::ProcessHits(), G4PSNofCollision::ProcessHits(), ExP01TrackerSD::ProcessHits(), G4PSPopulation::ProcessHits(), F01CalorimeterSD::ProcessHits(), FCALHadModuleSD::ProcessHits(), F03CalorimeterSD::ProcessHits(), G4PSMinKinEAtGeneration::ProcessHits(), FCALEMModuleSD::ProcessHits(), FCALTestbeamSetupSD::ProcessHits(), GammaRayTelCalorimeterSD::ProcessHits(), GammaRayTelTrackerSD::ProcessHits(), GammaRayTelAnticoincidenceSD::ProcessHits(), B2TrackerSD::ProcessHits(), G4PSPassageCellCurrent::ProcessHits(), B4cCalorimeterSD::ProcessHits(), PhantomSD::ProcessHits(), DMXScintSD::ProcessHits(), UltraPMTSD::ProcessHits(), XrayFluoHPGeSD::ProcessHits(), G4PSPassageCellFlux::ProcessHits(), G4PSNofSecondary::ProcessHits(), G4PSTrackLength::ProcessHits(), G4PSCellFlux::ProcessHits(), RMC01SD::ProcessHits(), XrayFluoSD::ProcessHits(), G4PSSphereSurfaceCurrent::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), CexmcTrackPoints::ProcessHits(), PrimaryKiller::ProcessHits(), ScoreSpecies::ProcessHits(), G4ErrorFreeTrajState::PropagateError(), G4ErrorFreeTrajState::PropagateErrorIoni(), G4BOptrForceCollision::ProposeNonPhysicsBiasingOperation(), G4TransportationLogger::ReportLoopingTrack(), G4ElectronIonPair::SampleIonsAlongStep(), G4VEnergyLossProcess::SampleSubCutSecondaries(), G4ITStepProcessor::SetupMembers(), G4SteppingVerbose::ShowStep(), G4EnergySplitter::SplitEnergyInVolumes(), G4ScoreSplittingProcess::StartTracking(), G4ParallelWorldProcess::StartTracking(), G4SteppingManager::Stepping(), G4Channeling::UpdateParameters(), G4ParticleChangeForLoss::UpdateStepForAlongStep(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), ExN04SteppingAction::UserSteppingAction(), RE05SteppingAction::UserSteppingAction(), RE01SteppingAction::UserSteppingAction(), CCalSteppingAction::UserSteppingAction(), RE04SteppingAction::UserSteppingAction(), LXeSteppingAction::UserSteppingAction(), F04SteppingAction::UserSteppingAction(), SteppingAction::UserSteppingAction(), B4bSteppingAction::UserSteppingAction(), B1SteppingAction::UserSteppingAction(), B4aSteppingAction::UserSteppingAction(), doiPETSteppingAction::UserSteppingAction(), HadrontherapySteppingAction::UserSteppingAction(), G4MSSteppingAction::UserSteppingAction(), WLSSteppingAction::UserSteppingAction(), PurgMagSteppingAction::UserSteppingAction(), CexmcSteppingAction::UserSteppingAction(), DMXSteppingAction::UserSteppingAction(), G4ScoreSplittingProcess::Verbose(), and G4ParallelWorldScoringProcess::Verbose().
GetSecondary()
const G4TrackVector* G4Step::GetSecondary () const
Referenced by G4SteppingManager::GetSecondary(), G4ITSteppingVerbose::PostStepVerbose(), and G4ElectronIonPair::ResidualeChargePostStep().
GetSecondaryInCurrentStep()
const std::vector< const G4Track * > * G4Step::GetSecondaryInCurrentStep () const
Definition at line 210 of file G4Step.cc.
Referenced by HadrontherapyDetectorSD::ProcessHits(), SteppingVerbose::StepInfo(), and OpNoviceSteppingAction::UserSteppingAction().
GetStepLength()
G4double G4Step::GetStepLength () const
Referenced by HistoManager::AddTargetStep(), G4VAtomDeexcitation::AlongStepDeexcitation(), G4ErrorEnergyLoss::AlongStepDoIt(), G4NuclearStopping::AlongStepDoIt(), G4AdjointForcedInteractionForGamma::AlongStepDoIt(), G4AdjointAlongStepWeightCorrection::AlongStepDoIt(), G4ContinuousGainOfEnergy::AlongStepDoIt(), G4eLowEnergyLoss::AlongStepDoIt(), G4hImpactIonisation::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepDoIt(), G4VMultipleScattering::AlongStepDoIt(), G4BiasingProcessInterface::AlongStepDoIt(), G4RayTrajectory::AppendStep(), SteppingAction::BirksAttenuation(), G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), G4ExceptionHandler::DumpTrackInfo(), G4CellScoreComposer::EstimatorCalculation(), export_G4Step(), G4PSPassageTrackLength::IsPassed(), G4PSPassageCellFlux::IsPassed(), G4VTransitionRadiation::PostStepDoIt(), G4ImportanceProcess::PostStepDoIt(), G4WeightWindowProcess::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4DNABrownianTransportation::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4BiasingProcessInterface::PostStepDoIt(), G4PSNofStep::ProcessHits(), F02CalorimeterSD::ProcessHits(), G4MultiFunctionalDetector::ProcessHits(), F01CalorimeterSD::ProcessHits(), F03CalorimeterSD::ProcessHits(), B4cCalorimeterSD::ProcessHits(), DMXScintSD::ProcessHits(), G4PSCellFlux::ProcessHits(), G4PSTrackLength::ProcessHits(), G4ErrorFreeTrajState::PropagateError(), G4ErrorFreeTrajState::PropagateErrorIoni(), G4ErrorFreeTrajState::PropagateErrorMSC(), G4TransportationLogger::ReportLoopingTrack(), G4VEnergyLossProcess::SampleSubCutSecondaries(), G4EnergySplitter::SplitEnergyInVolumes(), F04SteppingVerbose::StepInfo(), WLSSteppingVerbose::StepInfo(), ExN04SteppingVerbose::StepInfo(), SteppingVerbose::StepInfo(), OpNoviceSteppingVerbose::StepInfo(), FCALSteppingVerbose::StepInfo(), eRositaSteppingVerbose::StepInfo(), XrayFluoSteppingVerbose::StepInfo(), PurgMagSteppingVerbose::StepInfo(), RE05SteppingVerbose::StepInfo(), ExN02SteppingVerbose::StepInfo(), ExP01SteppingVerbose::StepInfo(), F05SteppingVerbose::StepInfo(), G4SteppingVerbose::StepInfo(), F01SteppingVerbose::StepInfo(), F02SteppingVerbose::StepInfo(), F03SteppingVerbose::StepInfo(), G4SteppingManager::Stepping(), F04SteppingVerbose::TrackingStarted(), WLSSteppingVerbose::TrackingStarted(), ExN04SteppingVerbose::TrackingStarted(), SteppingVerbose::TrackingStarted(), FCALSteppingVerbose::TrackingStarted(), OpNoviceSteppingVerbose::TrackingStarted(), eRositaSteppingVerbose::TrackingStarted(), XrayFluoSteppingVerbose::TrackingStarted(), PurgMagSteppingVerbose::TrackingStarted(), ExN02SteppingVerbose::TrackingStarted(), RE05SteppingVerbose::TrackingStarted(), ExP01SteppingVerbose::TrackingStarted(), F05SteppingVerbose::TrackingStarted(), G4SteppingVerbose::TrackingStarted(), F01SteppingVerbose::TrackingStarted(), F03SteppingVerbose::TrackingStarted(), F02SteppingVerbose::TrackingStarted(), G4BOptnForceCommonTruncatedExp::UpdateForStep(), B4bSteppingAction::UserSteppingAction(), B4aSteppingAction::UserSteppingAction(), G4MSSteppingAction::UserSteppingAction(), CexmcSteppingAction::UserSteppingAction(), G4ScoreSplittingProcess::Verbose(), G4ParallelWorldScoringProcess::Verbose(), and G4EmSaturation::VisibleEnergyDepositionAtAStep().
GetTotalEnergyDeposit()
G4double G4Step::GetTotalEnergyDeposit () const
Referenced by CML2ExpVoxels::add(), CML2Convergence::add(), HistoManager::AddTargetStep(), G4RichTrajectory::AppendStep(), SteppingAction::BirksAttenuation(), G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), G4ExceptionHandler::DumpTrackInfo(), export_G4Step(), G4Scintillation::GetScintillationYieldByParticleType(), CCaloSD::getStepInfo(), G4ElectronIonPair::MeanNumberOfIonsAlongStep(), G4ScoreSplittingProcess::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4HumanPhantomSD::ProcessHits(), RE05CalorimeterSD::ProcessHits(), ExN04MuonSD::ProcessHits(), RE05TrackerSD::ProcessHits(), ExN04TrackerSD::ProcessHits(), Par01CalorimeterSD::ProcessHits(), RE05MuonSD::ProcessHits(), ExTGTrackerSD::ProcessHits(), B5HodoscopeSD::ProcessHits(), LXeScintSD::ProcessHits(), B5EmCalorimeterSD::ProcessHits(), RE01TrackerSD::ProcessHits(), B5HadCalorimeterSD::ProcessHits(), RE01CalorimeterSD::ProcessHits(), ExGflashSensitiveDetector::ProcessHits(), ExN02TrackerSD::ProcessHits(), G4PSDoseDeposit::ProcessHits(), SensitiveDetector::ProcessHits(), G4PSEnergyDeposit::ProcessHits(), F02CalorimeterSD::ProcessHits(), ExP01TrackerSD::ProcessHits(), G4MultiFunctionalDetector::ProcessHits(), FCALHadModuleSD::ProcessHits(), F01CalorimeterSD::ProcessHits(), F03CalorimeterSD::ProcessHits(), FCALEMModuleSD::ProcessHits(), FCALTestbeamSetupSD::ProcessHits(), GammaRayTelTrackerSD::ProcessHits(), GammaRayTelAnticoincidenceSD::ProcessHits(), GammaRayTelCalorimeterSD::ProcessHits(), B2TrackerSD::ProcessHits(), B4cCalorimeterSD::ProcessHits(), TrackerSD::ProcessHits(), TargetSD::ProcessHits(), DMXScintSD::ProcessHits(), PhantomSD::ProcessHits(), G4MultiSensitiveDetector::ProcessHits(), XrayFluoHPGeSD::ProcessHits(), CCaloSD::ProcessHits(), RMC01SD::ProcessHits(), XrayFluoSD::ProcessHits(), CexmcSimpleEnergyDeposit::ProcessHits(), ScoreSpecies::ProcessHits(), G4SteppingVerbose::ShowStep(), G4EnergySplitter::SplitEnergyInVolumes(), ExN04SteppingVerbose::StepInfo(), SteppingVerbose::StepInfo(), OpNoviceSteppingVerbose::StepInfo(), FCALSteppingVerbose::StepInfo(), eRositaSteppingVerbose::StepInfo(), XrayFluoSteppingVerbose::StepInfo(), PurgMagSteppingVerbose::StepInfo(), ExN02SteppingVerbose::StepInfo(), RE05SteppingVerbose::StepInfo(), ExP01SteppingVerbose::StepInfo(), F05SteppingVerbose::StepInfo(), G4SteppingVerbose::StepInfo(), F01SteppingVerbose::StepInfo(), F02SteppingVerbose::StepInfo(), F03SteppingVerbose::StepInfo(), F04SteppingVerbose::TrackingStarted(), SteppingVerbose::TrackingStarted(), ExN04SteppingVerbose::TrackingStarted(), OpNoviceSteppingVerbose::TrackingStarted(), FCALSteppingVerbose::TrackingStarted(), eRositaSteppingVerbose::TrackingStarted(), XrayFluoSteppingVerbose::TrackingStarted(), PurgMagSteppingVerbose::TrackingStarted(), RE05SteppingVerbose::TrackingStarted(), ExN02SteppingVerbose::TrackingStarted(), ExP01SteppingVerbose::TrackingStarted(), F05SteppingVerbose::TrackingStarted(), G4SteppingVerbose::TrackingStarted(), F01SteppingVerbose::TrackingStarted(), F03SteppingVerbose::TrackingStarted(), F02SteppingVerbose::TrackingStarted(), CCalSteppingAction::UserSteppingAction(), FCALSteppingAction::UserSteppingAction(), B4bSteppingAction::UserSteppingAction(), SteppingAction::UserSteppingAction(), B1SteppingAction::UserSteppingAction(), B4aSteppingAction::UserSteppingAction(), doiPETSteppingAction::UserSteppingAction(), G4ScoreSplittingProcess::Verbose(), G4ParallelWorldScoringProcess::Verbose(), and G4EmSaturation::VisibleEnergyDepositionAtAStep().
GetTrack()
G4Track* G4Step::GetTrack () const
Referenced by CexmcTrackPointsFilter::Accept(), G4SDParticleFilter::Accept(), Run::AddEnergy(), HistoManager::AddTargetStep(), G4VAtomDeexcitation::AlongStepDeexcitation(), XrayFluoAnalysisManager::analyseStepping(), G4RichTrajectory::AppendStep(), G4DecayWithSpin::AtRestDoIt(), SteppingAction::BirksAttenuation(), G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), export_G4Step(), G4RichTrajectoryPoint::G4RichTrajectoryPoint(), CCaloSD::getStepInfo(), CexmcTrackPoints::GetTrackId(), G4UCNBoundaryProcess::InvokeSD(), G4PSPassageTrackLength::IsPassed(), G4PSPassageCellCurrent::IsPassed(), G4PSPassageCellFlux::IsPassed(), G4ElectronIonPair::MeanNumberOfIonsAlongStep(), SplitProcess::PostStepDoIt(), GB05SD::ProcessHits(), GB06SD::ProcessHits(), ScreenSD::ProcessHits(), ExTGTrackerSD::ProcessHits(), eRositaTrackerSD::ProcessHits(), RE01TrackerSD::ProcessHits(), B5DriftChamberSD::ProcessHits(), RE01CalorimeterSD::ProcessHits(), ExN02TrackerSD::ProcessHits(), G4PSDoseDeposit::ProcessHits(), G4PSCellCharge::ProcessHits(), G4PSTermination::ProcessHits(), ExP01TrackerSD::ProcessHits(), G4PSPopulation::ProcessHits(), G4PSMinKinEAtGeneration::ProcessHits(), B2TrackerSD::ProcessHits(), TrackerSD::ProcessHits(), B4cCalorimeterSD::ProcessHits(), DMXScintSD::ProcessHits(), UltraPMTSD::ProcessHits(), CheckVolumeSD::ProcessHits(), G4PSNofSecondary::ProcessHits(), RMC01SD::ProcessHits(), CexmcTrackPoints::ProcessHits(), PrimaryKiller::ProcessHits(), LXePMTSD::ProcessHits_constStep(), WLSPhotonDetSD::ProcessHits_constStep(), G4ElectronIonPair::ResidualeChargePostStep(), G4VEnergyLossProcess::SampleSubCutSecondaries(), G4SteppingVerbose::ShowStep(), G4DecayWithSpin::Spin_Precession(), G4EnergySplitter::SplitEnergyInVolumes(), G4ErrorGeomVolumeTarget::TargetReached(), G4ParticleChangeForLoss::UpdateStepForAlongStep(), G4ParticleChangeForMSC::UpdateStepForAlongStep(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), G4ParticleChangeForDecay::UpdateStepForAtRest(), G4ParticleChange::UpdateStepForAtRest(), G4FastStep::UpdateStepForAtRest(), G4ParticleChangeForGamma::UpdateStepForPostStep(), G4ParticleChangeForLoss::UpdateStepForPostStep(), G4ParticleChange::UpdateStepForPostStep(), G4FastStep::UpdateStepForPostStep(), G4ITReactionChange::UpdateStepInfo(), ExN04SteppingAction::UserSteppingAction(), RE01SteppingAction::UserSteppingAction(), RE05SteppingAction::UserSteppingAction(), OpNoviceSteppingAction::UserSteppingAction(), RE04SteppingAction::UserSteppingAction(), FCALSteppingAction::UserSteppingAction(), LXeSteppingAction::UserSteppingAction(), F04SteppingAction::UserSteppingAction(), F05SteppingAction::UserSteppingAction(), B4bSteppingAction::UserSteppingAction(), B4aSteppingAction::UserSteppingAction(), XrayFluoSteppingAction::UserSteppingAction(), doiPETSteppingAction::UserSteppingAction(), HadrontherapySteppingAction::UserSteppingAction(), WLSSteppingAction::UserSteppingAction(), PurgMagSteppingAction::UserSteppingAction(), CexmcSteppingAction::UserSteppingAction(), DMXSteppingAction::UserSteppingAction(), XrayTelSteppingAction::UserSteppingAction(), G4AdjointSteppingAction::UserSteppingAction(), G4ScoreSplittingProcess::Verbose(), G4ParallelWorldScoringProcess::Verbose(), and G4EmSaturation::VisibleEnergyDepositionAtAStep().
InitializeStep()
void G4Step::InitializeStep (G4Track * aValue)
Referenced by G4SteppingManager::SetInitialStep(), and G4ITStepProcessor::SetInitialStep().
IsFirstStepInVolume()
G4bool G4Step::IsFirstStepInVolume () const
IsLastStepInVolume()
G4bool G4Step::IsLastStepInVolume () const
NewSecondaryVector()
G4TrackVector* G4Step::NewSecondaryVector ()
Referenced by G4SteppingManager::G4SteppingManager(), and G4ITStepProcessor::InitDefineStep().
operator=()
G4Step & G4Step::operator= (const G4Step & right)
Definition at line 127 of file G4Step.cc.
ResetNonIonizingEnergyDeposit()
void G4Step::ResetNonIonizingEnergyDeposit ()
ResetTotalEnergyDeposit()
void G4Step::ResetTotalEnergyDeposit ()
Referenced by G4ITStepProcessor::InitDefineStep(), and G4SteppingManager::Stepping().
SetControlFlag()
void G4Step::SetControlFlag (G4SteppingControl StepControlFlag)
Referenced by G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), and G4VParticleChange::UpdateStepInfo().
SetFirstStepFlag()
void G4Step::SetFirstStepFlag ()
Referenced by G4ParticleChangeForTransport::UpdateStepForPostStep(), and G4VParticleChange::UpdateStepInfo().
SetLastStepFlag()
void G4Step::SetLastStepFlag ()
Referenced by G4ParticleChangeForTransport::UpdateStepForPostStep(), and G4VParticleChange::UpdateStepInfo().
SetNonIonizingEnergyDeposit()
void G4Step::SetNonIonizingEnergyDeposit (G4double value)
Referenced by G4ParallelWorldProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), and G4ScoreSplittingProcess::PostStepDoIt().
SetPointerToVectorOfAuxiliaryPoints()
void G4Step::SetPointerToVectorOfAuxiliaryPoints (std::vector< G4ThreeVector > * theNewVectorPointer) inline
Definition at line 238 of file G4Step.hh.
Referenced by G4ITStepProcessor::InitDefineStep(), G4SteppingManager::Stepping(), and G4ParticleChangeForTransport::UpdateStepForAlongStep().
SetPostStepPoint()
void G4Step::SetPostStepPoint (G4StepPoint * value)
SetPreStepPoint()
void G4Step::SetPreStepPoint (G4StepPoint * value)
SetSecondary()
void G4Step::SetSecondary (G4TrackVector * value)
Referenced by G4ParallelWorldProcess::CopyStep().
SetStepLength()
void G4Step::SetStepLength (G4double value)
Referenced by G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), G4SteppingManager::InvokeAtRestDoItProcs(), G4ScoreSplittingProcess::PostStepDoIt(), G4SteppingManager::Stepping(), G4ParticleChangeForMSC::UpdateStepForAlongStep(), G4ParticleChangeForGamma::UpdateStepForAtRest(), and G4VParticleChange::UpdateStepInfo().
SetTotalEnergyDeposit()
void G4Step::SetTotalEnergyDeposit (G4double value)
Referenced by G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), Par01PionShowerModel::FillFakeStep(), Par01EMShowerModel::FillFakeStep(), and G4ScoreSplittingProcess::PostStepDoIt().
SetTrack()
void G4Step::SetTrack (G4Track * value)
Referenced by G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), and G4SteppingManager::Stepping().
UpdateTrack()
void G4Step::UpdateTrack ()
Referenced by G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePSDIP(), and G4SteppingManager::Stepping().
Field Documentation
CT
const typedef G4Track* G4Step::CT private
Definition at line 230 of file G4Step.hh.
fFirstStepInVolume
G4bool G4Step::fFirstStepInVolume private
Definition at line 197 of file G4Step.hh.
Referenced by operator=().
fLastStepInVolume
G4bool G4Step::fLastStepInVolume private
Definition at line 198 of file G4Step.hh.
Referenced by operator=().
fNonIonizingEnergyDeposit
G4double G4Step::fNonIonizingEnergyDeposit protected
Definition at line 178 of file G4Step.hh.
Referenced by operator=().
fpPostStepPoint
G4StepPoint* G4Step::fpPostStepPoint private
Definition at line 187 of file G4Step.hh.
Referenced by G4Step(), GetDeltaEnergy(), GetDeltaMomentum(), operator=(), and ~G4Step().
fpPreStepPoint
G4StepPoint* G4Step::fpPreStepPoint private
Definition at line 186 of file G4Step.hh.
Referenced by G4Step(), GetDeltaEnergy(), GetDeltaMomentum(), operator=(), and ~G4Step().
fpSteppingControlFlag
G4SteppingControl G4Step::fpSteppingControlFlag private
Definition at line 193 of file G4Step.hh.
Referenced by operator=().
fpTrack
G4Track* G4Step::fpTrack private
Definition at line 191 of file G4Step.hh.
Referenced by operator=().
fpVectorOfAuxiliaryPointsPointer
std::vector<G4ThreeVector>* G4Step::fpVectorOfAuxiliaryPointsPointer private
Definition at line 247 of file G4Step.hh.
Referenced by GetPointerToVectorOfAuxiliaryPoints(), operator=(), and SetPointerToVectorOfAuxiliaryPoints().
fSecondary
G4TrackVector* G4Step::fSecondary private
Definition at line 225 of file G4Step.hh.
Referenced by G4Step(), GetSecondaryInCurrentStep(), operator=(), and ~G4Step().
fStepLength
G4double G4Step::fStepLength private
Definition at line 188 of file G4Step.hh.
Referenced by operator=().
fTotalEnergyDeposit
G4double G4Step::fTotalEnergyDeposit protected
Definition at line 175 of file G4Step.hh.
Referenced by operator=().
nSecondaryByLastStep
G4int G4Step::nSecondaryByLastStep private
Definition at line 228 of file G4Step.hh.
Referenced by GetSecondaryInCurrentStep(), and operator=().
secondaryInCurrentStep
std::vector<CT>* G4Step::secondaryInCurrentStep private
Definition at line 231 of file G4Step.hh.
Referenced by G4Step(), GetSecondaryInCurrentStep(), operator=(), and ~G4Step().
The documentation for this class was generated from the following files:
source/track/include/G4Step.hh
source/track/src/G4Step.cc