Geant4: source/global/management/include/G4Threading.hh File Reference
G4Threading.hh File Reference
#include "globals.hh"
#include "G4Types.hh"
#include <chrono>
#include <thread>
#include <mutex>
#include <condition_variable>
#include <future>
#include <vector>
Data Structures
class G4DummyThread
Namespaces
G4ThisThread
G4Threading
Macros
#define G4THREADSLEEP(tick) std::this_thread::sleep_for(std::chrono::seconds(tick))
#define G4MUTEX_INITIALIZER {}
#define G4MUTEXINIT(mutex) ;;
#define G4MUTEXDESTROY(mutex) ;;
#define G4MUTEXLOCK(mutex) ;;
#define G4MUTEXUNLOCK(mutex) ;;
#define G4THREADJOIN(worker) ;;
#define G4CONDITION_INITIALIZER 1
#define G4CONDITIONWAIT(cond, mutex) G4ConsumeParameters(cond, mutex);
#define G4CONDITIONWAITLAMBDA(cond, mutex, lambda) G4ConsumeParameters(cond, mutex, lambda);
#define G4CONDITIONNOTIFY(cond) G4ConsumeParameters(cond);
#define G4CONDITIONBROADCAST(cond) G4ConsumeParameters(cond);
Typedefs
template<typename _Tp >
using G4Future = std::future< _Tp >
template<typename _Tp >
using G4SharedFuture = std::shared_future< _Tp >
template<typename _Tp >
using G4Promise = std::promise< _Tp >
using G4Mutex = std::mutex
using G4RecursiveMutex = std::recursive_mutex
using G4ThreadFunReturnType = void *
using G4ThreadFunArgType = void *
using thread_lock = G4int(*)(G4Mutex *)
using thread_unlock = G4int(*)(G4Mutex *)
using G4Thread = G4DummyThread
using G4NativeThread = G4DummyThread::native_handle_type
using G4Pid_t = G4int
using G4Condition = G4int
using G4ThreadId = G4Thread::id
Enumerations
enum { G4Threading::SEQUENTIAL_ID = -2, G4Threading::MASTER_ID = -1, G4Threading::WORKER_ID = 0, G4Threading::GENERICTHREAD_ID = -1000 }
Functions
template<typename _Tp >
G4Mutex & G4TypeMutex (const unsigned int &_n=0)
template<typename _Tp >
G4RecursiveMutex & G4TypeRecursiveMutex (const unsigned int &_n=0)
template<typename _Worker , typename _Func , typename... _Args>
void G4THREADCREATE (_Worker *&worker, _Func func, _Args... args)
G4Pid_t G4Threading::G4GetPidId ()
G4int G4Threading::G4GetNumberOfCores ()
G4int G4Threading::G4GetThreadId ()
G4bool G4Threading::IsWorkerThread ()
G4bool G4Threading::IsMasterThread ()
void G4Threading::G4SetThreadId (G4int aNewValue)
G4bool G4Threading::G4SetPinAffinity (G4int idx, G4NativeThread &at)
void G4Threading::SetMultithreadedApplication (G4bool value)
G4bool G4Threading::IsMultithreadedApplication ()
int G4Threading::WorkerThreadLeavesPool ()
int G4Threading::WorkerThreadJoinsPool ()
G4int G4Threading::GetNumberOfRunningWorkerThreads ()
Macro Definition Documentation
G4CONDITION_INITIALIZER
#define G4CONDITION_INITIALIZER 1
Definition at line 251 of file G4Threading.hh.
G4CONDITIONBROADCAST
#define G4CONDITIONBROADCAST (cond) G4ConsumeParameters(cond);
Definition at line 255 of file G4Threading.hh.
G4CONDITIONNOTIFY
#define G4CONDITIONNOTIFY (cond) G4ConsumeParameters(cond);
Definition at line 254 of file G4Threading.hh.
G4CONDITIONWAIT
#define G4CONDITIONWAIT (cond, mutex) G4ConsumeParameters(cond, mutex);
Definition at line 252 of file G4Threading.hh.
G4CONDITIONWAITLAMBDA
#define G4CONDITIONWAITLAMBDA (cond, mutex, lambda) G4ConsumeParameters(cond, mutex, lambda);
Definition at line 253 of file G4Threading.hh.
G4MUTEX_INITIALIZER
#define G4MUTEX_INITIALIZER {}
Definition at line 88 of file G4Threading.hh.
G4MUTEXDESTROY
#define G4MUTEXDESTROY (mutex) ;;
Definition at line 90 of file G4Threading.hh.
G4MUTEXINIT
#define G4MUTEXINIT (mutex) ;;
Definition at line 89 of file G4Threading.hh.
G4MUTEXLOCK
#define G4MUTEXLOCK (mutex) ;;
Definition at line 234 of file G4Threading.hh.
G4MUTEXUNLOCK
#define G4MUTEXUNLOCK (mutex) ;;
Definition at line 235 of file G4Threading.hh.
G4THREADJOIN
#define G4THREADJOIN (worker) ;;
Definition at line 238 of file G4Threading.hh.
G4THREADSLEEP
#define G4THREADSLEEP (tick) std::this_thread::sleep_for(std::chrono::seconds(tick))
Definition at line 52 of file G4Threading.hh.
Typedef Documentation
G4Condition
using G4Condition = G4int
Definition at line 250 of file G4Threading.hh.
G4Future
template<typename _Tp > using G4Future = std::future<_Tp>
Definition at line 56 of file G4Threading.hh.
G4Mutex
using G4Mutex = std::mutex
Definition at line 84 of file G4Threading.hh.
G4NativeThread
using G4NativeThread = G4DummyThread::native_handle_type
Definition at line 231 of file G4Threading.hh.
G4Pid_t
using G4Pid_t = G4int
Definition at line 240 of file G4Threading.hh.
G4Promise
template<typename _Tp > using G4Promise = std::promise<_Tp>
Definition at line 58 of file G4Threading.hh.
G4RecursiveMutex
using G4RecursiveMutex = std::recursive_mutex
Definition at line 85 of file G4Threading.hh.
G4SharedFuture
template<typename _Tp > using G4SharedFuture = std::shared_future<_Tp>
Definition at line 57 of file G4Threading.hh.
G4Thread
using G4Thread = G4DummyThread
Definition at line 230 of file G4Threading.hh.
G4ThreadFunArgType
using G4ThreadFunArgType = void*
Definition at line 103 of file G4Threading.hh.
G4ThreadFunReturnType
using G4ThreadFunReturnType = void*
Definition at line 102 of file G4Threading.hh.
G4ThreadId
using G4ThreadId = G4Thread::id
Definition at line 262 of file G4Threading.hh.
thread_lock
using thread_lock = G4int(*)(G4Mutex*)
Definition at line 104 of file G4Threading.hh.
thread_unlock
using thread_unlock = G4int(*)(G4Mutex*)
Definition at line 105 of file G4Threading.hh.
Function Documentation
G4THREADCREATE()
template<typename _Worker , typename _Func , typename... _Args> void G4THREADCREATE (_Worker *& worker, _Func func, _Args... args)
Definition at line 245 of file G4Threading.hh.
Referenced by G4VisManager::BeginOfRun(), and main().
G4TypeMutex()
template<typename _Tp > G4Mutex& G4TypeMutex (const unsigned int & _n = 0)
Definition at line 114 of file G4Threading.hh.
Referenced by G4Cache< F02ElectricFieldSetup * >::G4Cache(), and G4Cache< F02ElectricFieldSetup * >::~G4Cache().
G4TypeRecursiveMutex()
template<typename _Tp > G4RecursiveMutex& G4TypeRecursiveMutex (const unsigned int & _n = 0)
Definition at line 135 of file G4Threading.hh.