Geant4: RE01RegionInformation Class Reference
RE01RegionInformation Class Reference
#include <RE01RegionInformation.hh>
Public Member Functions
RE01RegionInformation ()
virtual ~RE01RegionInformation ()
virtual void Print () const
void SetWorld (G4bool v=true)
void SetTracker (G4bool v=true)
void SetCalorimeter (G4bool v=true)
G4bool IsCalorimeter () const
Public Member Functions inherited from G4VUserRegionInformation
G4VUserRegionInformation ()
virtual ~G4VUserRegionInformation ()
Private Attributes
G4bool fIsWorld
G4bool fIsTracker
G4bool fIsCalorimeter
Detailed Description
Definition at line 38 of file RE01RegionInformation.hh.
Constructor & Destructor Documentation
RE01RegionInformation()
RE01RegionInformation::RE01RegionInformation ()
Definition at line 36 of file RE01RegionInformation.cc.
~RE01RegionInformation()
RE01RegionInformation::~RE01RegionInformation () virtual
Definition at line 42 of file RE01RegionInformation.cc.
Member Function Documentation
IsCalorimeter()
G4bool RE01RegionInformation::IsCalorimeter () const inline
Definition at line 48 of file RE01RegionInformation.hh.
Referenced by RE01SteppingAction::UserSteppingAction().
Print()
void RE01RegionInformation::Print (void) const virtual
Implements G4VUserRegionInformation.
Definition at line 46 of file RE01RegionInformation.cc.
Referenced by RE01DetectorConstruction::Construct().
SetCalorimeter()
void RE01RegionInformation::SetCalorimeter (G4bool v = true) inline
Definition at line 47 of file RE01RegionInformation.hh.
Referenced by RE01DetectorConstruction::Construct().
SetTracker()
void RE01RegionInformation::SetTracker (G4bool v = true) inline
Definition at line 46 of file RE01RegionInformation.hh.
Referenced by RE01DetectorConstruction::Construct().
SetWorld()
void RE01RegionInformation::SetWorld (G4bool v = true) inline
Definition at line 45 of file RE01RegionInformation.hh.
Referenced by RE01DetectorConstruction::Construct().
Field Documentation
fIsCalorimeter
G4bool RE01RegionInformation::fIsCalorimeter private
Definition at line 53 of file RE01RegionInformation.hh.
Referenced by IsCalorimeter(), Print(), and SetCalorimeter().
fIsTracker
G4bool RE01RegionInformation::fIsTracker private
Definition at line 52 of file RE01RegionInformation.hh.
Referenced by Print(), and SetTracker().
fIsWorld
G4bool RE01RegionInformation::fIsWorld private
Definition at line 51 of file RE01RegionInformation.hh.
Referenced by Print(), and SetWorld().
The documentation for this class was generated from the following files:
examples/extended/runAndEvent/RE01/include/RE01RegionInformation.hh
examples/extended/runAndEvent/RE01/src/RE01RegionInformation.cc