Geant4: G4VNtupleManager Class Reference
G4VNtupleManager Class Reference abstract
#include <G4VNtupleManager.hh>
Public Member Functions
G4VNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4VNtupleManager ()
G4VNtupleManager (const G4VNtupleManager &rhs)=delete
G4VNtupleManager & operator= (const G4VNtupleManager &rhs)=delete
Public Member Functions inherited from G4BaseAnalysisManager
G4BaseAnalysisManager (const G4AnalysisManagerState &state)
virtual ~G4BaseAnalysisManager ()
G4bool SetFirstId (G4int firstId)
void SetLockFirstId (G4bool lockFirstId)
G4int GetFirstId () const
Protected Member Functions
virtual G4int CreateNtuple (const G4String &name, const G4String &title)=0
virtual G4int CreateNtupleIColumn (const G4String &name, std::vector< int > *vector)=0
virtual G4int CreateNtupleFColumn (const G4String &name, std::vector< float > *vector)=0
virtual G4int CreateNtupleDColumn (const G4String &name, std::vector< double > *vector)=0
virtual G4int CreateNtupleSColumn (const G4String &name)=0
virtual void FinishNtuple ()=0
virtual G4int CreateNtupleIColumn (G4int ntupleId, const G4String &name, std::vector< int > *vector)=0
virtual G4int CreateNtupleFColumn (G4int ntupleId, const G4String &name, std::vector< float > *vector)=0
virtual G4int CreateNtupleDColumn (G4int ntupleId, const G4String &name, std::vector< double > *vector)=0
virtual G4int CreateNtupleSColumn (G4int ntupleId, const G4String &name)=0
virtual void FinishNtuple (G4int ntupleId)=0
virtual G4bool SetFirstNtupleColumnId (G4int firstId)=0
virtual G4int GetFirstNtupleColumnId () const =0
virtual G4bool FillNtupleIColumn (G4int id, G4int value)=0
virtual G4bool FillNtupleFColumn (G4int id, G4float value)=0
virtual G4bool FillNtupleDColumn (G4int id, G4double value)=0
virtual G4bool FillNtupleSColumn (G4int id, const G4String &value)=0
virtual G4bool AddNtupleRow ()=0
virtual G4bool FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value)=0
virtual G4bool FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value)=0
virtual G4bool FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value)=0
virtual G4bool FillNtupleSColumn (G4int ntupleId, G4int columnId, const G4String &value)=0
virtual G4bool AddNtupleRow (G4int ntupleId)=0
virtual void SetActivation (G4bool activation)=0
virtual void SetActivation (G4int id, G4bool activation)=0
virtual G4bool GetActivation (G4int id) const =0
virtual G4int GetNofNtuples () const =0
virtual G4int GetNofNtupleBookings () const =0
Friends
class G4VAnalysisManager
Additional Inherited Members
Protected Attributes inherited from G4BaseAnalysisManager
const G4AnalysisManagerState & fState
G4int fFirstId
G4bool fLockFirstId
Detailed Description
Definition at line 40 of file G4VNtupleManager.hh.
Constructor & Destructor Documentation
G4VNtupleManager() [1/2]
G4VNtupleManager::G4VNtupleManager (const G4AnalysisManagerState & state) inline explicit
Definition at line 47 of file G4VNtupleManager.hh.
~G4VNtupleManager()
virtual G4VNtupleManager::~G4VNtupleManager () inline virtual
Definition at line 49 of file G4VNtupleManager.hh.
G4VNtupleManager() [2/2]
G4VNtupleManager::G4VNtupleManager (const G4VNtupleManager & rhs) delete
Member Function Documentation
AddNtupleRow() [1/2]
virtual G4bool G4VNtupleManager::AddNtupleRow () protected pure virtual
Implemented in G4BaseNtupleManager.
AddNtupleRow() [2/2]
virtual G4bool G4VNtupleManager::AddNtupleRow (G4int ntupleId) protected pure virtual
Implemented in G4BaseNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, G4TNtupleManager< tools::hdf5::ntuple >, G4RootPNtupleManager, and G4RootMpiPNtupleManager.
CreateNtuple()
virtual G4int G4VNtupleManager::CreateNtuple (const G4String & name, const G4String & title) protected pure virtual
Implemented in G4BaseNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, G4TNtupleManager< tools::hdf5::ntuple >, G4RootPNtupleManager, and G4RootMpiPNtupleManager.
Referenced by G4VAnalysisManager::CreateNtuple().
CreateNtupleDColumn() [1/2]
virtual G4int G4VNtupleManager::CreateNtupleDColumn (const G4String & name, std::vector< double > * vector) protected pure virtual
Implemented in G4BaseNtupleManager.
Referenced by G4VAnalysisManager::CreateNtupleDColumn().
CreateNtupleDColumn() [2/2]
virtual G4int G4VNtupleManager::CreateNtupleDColumn (G4int ntupleId, const G4String & name, std::vector< double > * vector) protected pure virtual
Implemented in G4BaseNtupleManager, G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
CreateNtupleFColumn() [1/2]
virtual G4int G4VNtupleManager::CreateNtupleFColumn (const G4String & name, std::vector< float > * vector) protected pure virtual
Implemented in G4BaseNtupleManager.
Referenced by G4VAnalysisManager::CreateNtupleFColumn().
CreateNtupleFColumn() [2/2]
virtual G4int G4VNtupleManager::CreateNtupleFColumn (G4int ntupleId, const G4String & name, std::vector< float > * vector) protected pure virtual
Implemented in G4BaseNtupleManager, G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
CreateNtupleIColumn() [1/2]
virtual G4int G4VNtupleManager::CreateNtupleIColumn (const G4String & name, std::vector< int > * vector) protected pure virtual
Implemented in G4BaseNtupleManager.
Referenced by G4VAnalysisManager::CreateNtupleIColumn().
CreateNtupleIColumn() [2/2]
virtual G4int G4VNtupleManager::CreateNtupleIColumn (G4int ntupleId, const G4String & name, std::vector< int > * vector) protected pure virtual
Implemented in G4BaseNtupleManager, G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
CreateNtupleSColumn() [1/2]
virtual G4int G4VNtupleManager::CreateNtupleSColumn (const G4String & name) protected pure virtual
Implemented in G4BaseNtupleManager.
Referenced by G4VAnalysisManager::CreateNtupleSColumn().
CreateNtupleSColumn() [2/2]
virtual G4int G4VNtupleManager::CreateNtupleSColumn (G4int ntupleId, const G4String & name) protected pure virtual
Implemented in G4BaseNtupleManager, G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
FillNtupleDColumn() [1/2]
virtual G4bool G4VNtupleManager::FillNtupleDColumn (G4int id, G4double value) protected pure virtual
Implemented in G4BaseNtupleManager.
FillNtupleDColumn() [2/2]
virtual G4bool G4VNtupleManager::FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value) protected pure virtual
Implemented in G4BaseNtupleManager, G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
FillNtupleFColumn() [1/2]
virtual G4bool G4VNtupleManager::FillNtupleFColumn (G4int id, G4float value) protected pure virtual
Implemented in G4BaseNtupleManager.
FillNtupleFColumn() [2/2]
virtual G4bool G4VNtupleManager::FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value) protected pure virtual
Implemented in G4BaseNtupleManager, G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
FillNtupleIColumn() [1/2]
virtual G4bool G4VNtupleManager::FillNtupleIColumn (G4int id, G4int value) protected pure virtual
Implemented in G4BaseNtupleManager.
FillNtupleIColumn() [2/2]
virtual G4bool G4VNtupleManager::FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value) protected pure virtual
Implemented in G4BaseNtupleManager, G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
FillNtupleSColumn() [1/2]
virtual G4bool G4VNtupleManager::FillNtupleSColumn (G4int id, const G4String & value) protected pure virtual
Implemented in G4BaseNtupleManager.
FillNtupleSColumn() [2/2]
virtual G4bool G4VNtupleManager::FillNtupleSColumn (G4int ntupleId, G4int columnId, const G4String & value) protected pure virtual
Implemented in G4BaseNtupleManager, G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
FinishNtuple() [1/2]
virtual void G4VNtupleManager::FinishNtuple () protected pure virtual
Implemented in G4BaseNtupleManager.
Referenced by G4VAnalysisManager::FinishNtuple().
FinishNtuple() [2/2]
virtual void G4VNtupleManager::FinishNtuple (G4int ntupleId) protected pure virtual
Implemented in G4BaseNtupleManager, G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
GetActivation()
virtual G4bool G4VNtupleManager::GetActivation (G4int id) const protected pure virtual
Implemented in G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
GetFirstNtupleColumnId()
virtual G4int G4VNtupleManager::GetFirstNtupleColumnId () const protected pure virtual
Implemented in G4BaseNtupleManager.
Referenced by G4VAnalysisManager::GetFirstNtupleColumnId().
GetNofNtupleBookings()
virtual G4int G4VNtupleManager::GetNofNtupleBookings () const protected pure virtual
Implemented in G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, G4TNtupleManager< tools::hdf5::ntuple >, G4RootPNtupleManager, and G4RootMpiPNtupleManager.
Referenced by G4BaseNtupleManager::GetCurrentNtupleId().
GetNofNtuples()
virtual G4int G4VNtupleManager::GetNofNtuples () const protected pure virtual
Implemented in G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
Referenced by G4VAnalysisManager::GetNofNtuples().
operator=()
G4VNtupleManager& G4VNtupleManager::operator= (const G4VNtupleManager & rhs) delete
SetActivation() [1/2]
virtual void G4VNtupleManager::SetActivation (G4bool activation) protected pure virtual
Implemented in G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
Referenced by G4VAnalysisManager::SetNtupleActivation().
SetActivation() [2/2]
virtual void G4VNtupleManager::SetActivation (G4int id, G4bool activation) protected pure virtual
Implemented in G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
SetFirstNtupleColumnId()
virtual G4bool G4VNtupleManager::SetFirstNtupleColumnId (G4int firstId) protected pure virtual
Implemented in G4BaseNtupleManager.
Referenced by G4VAnalysisManager::SetFirstNtupleColumnId().
Friends And Related Function Documentation
G4VAnalysisManager
friend class G4VAnalysisManager friend
Definition at line 44 of file G4VNtupleManager.hh.
The documentation for this class was generated from the following file:
source/analysis/management/include/G4VNtupleManager.hh