Geant4: G4FastTrack Class Reference
G4FastTrack Class Reference
#include <G4FastTrack.hh>
Public Member Functions
G4FastTrack (G4Envelope *anEnvelope, G4bool IsUnique)
~G4FastTrack ()
void SetCurrentTrack (const G4Track &, const G4Navigator *a=0)
G4bool OnTheBoundaryButExiting () const
const G4Track * GetPrimaryTrack () const
G4Envelope * GetEnvelope () const
G4LogicalVolume * GetEnvelopeLogicalVolume () const
G4VPhysicalVolume * GetEnvelopePhysicalVolume () const
G4VSolid * GetEnvelopeSolid () const
G4ThreeVector GetPrimaryTrackLocalPosition () const
G4ThreeVector GetPrimaryTrackLocalMomentum () const
G4ThreeVector GetPrimaryTrackLocalDirection () const
G4ThreeVector GetPrimaryTrackLocalPolarization () const
const G4AffineTransform * GetAffineTransformation () const
const G4AffineTransform * GetInverseAffineTransformation () const
Private Member Functions
void FRecordsAffineTransformation (const G4Navigator *)
Private Attributes
const G4Track * fTrack
G4bool fAffineTransformationDefined
G4Envelope * fEnvelope
G4bool fIsUnique
G4LogicalVolume * fEnvelopeLogicalVolume
G4VPhysicalVolume * fEnvelopePhysicalVolume
G4VSolid * fEnvelopeSolid
G4ThreeVector fLocalTrackPosition
G4ThreeVector fLocalTrackMomentum
G4ThreeVector fLocalTrackDirection
G4ThreeVector fLocalTrackPolarization
G4AffineTransform fAffineTransformation
G4AffineTransform fInverseAffineTransformation
Detailed Description
Definition at line 76 of file G4FastTrack.hh.
Constructor & Destructor Documentation
G4FastTrack()
G4FastTrack::G4FastTrack (G4Envelope * anEnvelope, G4bool IsUnique)
Definition at line 50 of file G4FastTrack.cc.
~G4FastTrack()
G4FastTrack::~G4FastTrack ()
Definition at line 63 of file G4FastTrack.cc.
Member Function Documentation
FRecordsAffineTransformation()
void G4FastTrack::FRecordsAffineTransformation (const G4Navigator * theNavigator) private
Definition at line 111 of file G4FastTrack.cc.
Referenced by SetCurrentTrack().
GetAffineTransformation()
const G4AffineTransform * G4FastTrack::GetAffineTransformation () const inline
Definition at line 231 of file G4FastTrack.hh.
GetEnvelope()
G4Envelope * G4FastTrack::GetEnvelope () const inline
Definition at line 186 of file G4FastTrack.hh.
Referenced by G4FastSimulationManager::GetEnvelope(), G4FastSimulationManager::ListTitle(), and G4FastSimulationManager::~G4FastSimulationManager().
GetEnvelopeLogicalVolume()
G4LogicalVolume * G4FastTrack::GetEnvelopeLogicalVolume () const inline
Definition at line 191 of file G4FastTrack.hh.
GetEnvelopePhysicalVolume()
G4VPhysicalVolume * G4FastTrack::GetEnvelopePhysicalVolume () const inline
Definition at line 196 of file G4FastTrack.hh.
GetEnvelopeSolid()
G4VSolid * G4FastTrack::GetEnvelopeSolid () const inline
Definition at line 201 of file G4FastTrack.hh.
Referenced by GFlashShowerModel::CheckContainment(), Par01PiModel::DoIt(), GFlashShowerModel::ElectronDoIt(), Par01PionShowerModel::Explode(), and OnTheBoundaryButExiting().
GetInverseAffineTransformation()
const G4AffineTransform * G4FastTrack::GetInverseAffineTransformation () const inline
Definition at line 236 of file G4FastTrack.hh.
Referenced by G4FastStep::CreateSecondaryTrack(), Par01PionShowerModel::Explode(), G4FastStep::ProposePrimaryTrackFinalKineticEnergyAndDirection(), G4FastStep::ProposePrimaryTrackFinalMomentumDirection(), G4FastStep::ProposePrimaryTrackFinalPolarization(), and G4FastStep::ProposePrimaryTrackFinalPosition().
GetPrimaryTrack()
const G4Track * G4FastTrack::GetPrimaryTrack () const inline
Definition at line 206 of file G4FastTrack.hh.
Referenced by GFlashShowerModel::CheckParticleDefAndContainment(), Par01PiModel::DoIt(), Par01PionShowerModel::DoIt(), Par01EMShowerModel::DoIt(), GFlashShowerModel::DoIt(), Par02FastSimModelEMCal::DoIt(), Par02FastSimModelHCal::DoIt(), Par02FastSimModelTracker::DoIt(), GFlashShowerModel::ElectronDoIt(), Par01PionShowerModel::Explode(), Par01EMShowerModel::Explode(), G4GFlashSpot::GetPosition(), G4VGFlashSensitiveDetector::Hit(), G4FastStep::Initialize(), Par01PiModel::ModelTrigger(), Par01EMShowerModel::ModelTrigger(), and GFlashShowerModel::ModelTrigger().
GetPrimaryTrackLocalDirection()
G4ThreeVector G4FastTrack::GetPrimaryTrackLocalDirection () const inline
Definition at line 221 of file G4FastTrack.hh.
Referenced by GFlashShowerModel::CheckContainment(), Par01PiModel::DoIt(), GFlashShowerModel::ElectronDoIt(), Par01PionShowerModel::Explode(), Par01PiModel::ModelTrigger(), and OnTheBoundaryButExiting().
GetPrimaryTrackLocalMomentum()
G4ThreeVector G4FastTrack::GetPrimaryTrackLocalMomentum () const inline
Definition at line 216 of file G4FastTrack.hh.
GetPrimaryTrackLocalPolarization()
G4ThreeVector G4FastTrack::GetPrimaryTrackLocalPolarization () const inline
Definition at line 226 of file G4FastTrack.hh.
GetPrimaryTrackLocalPosition()
G4ThreeVector G4FastTrack::GetPrimaryTrackLocalPosition () const inline
Definition at line 211 of file G4FastTrack.hh.
Referenced by GFlashShowerModel::CheckContainment(), Par01PiModel::DoIt(), GFlashShowerModel::ElectronDoIt(), Par01PionShowerModel::Explode(), Par01PiModel::ModelTrigger(), and OnTheBoundaryButExiting().
OnTheBoundaryButExiting()
G4bool G4FastTrack::OnTheBoundaryButExiting () const inline
Definition at line 241 of file G4FastTrack.hh.
Referenced by G4FastSimulationManager::PostStepGetFastSimulationManagerTrigger().
SetCurrentTrack()
void G4FastTrack::SetCurrentTrack (const G4Track & track, const G4Navigator * a = 0)
Definition at line 70 of file G4FastTrack.cc.
Referenced by G4FastSimulationManager::AtRestGetFastSimulationManagerTrigger(), and G4FastSimulationManager::PostStepGetFastSimulationManagerTrigger().
Field Documentation
fAffineTransformation
G4AffineTransform G4FastTrack::fAffineTransformation private
Definition at line 177 of file G4FastTrack.hh.
Referenced by FRecordsAffineTransformation(), GetAffineTransformation(), and SetCurrentTrack().
fAffineTransformationDefined
G4bool G4FastTrack::fAffineTransformationDefined private
Definition at line 167 of file G4FastTrack.hh.
Referenced by FRecordsAffineTransformation(), and SetCurrentTrack().
fEnvelope
G4Envelope* G4FastTrack::fEnvelope private
Definition at line 168 of file G4FastTrack.hh.
Referenced by FRecordsAffineTransformation(), and GetEnvelope().
fEnvelopeLogicalVolume
G4LogicalVolume* G4FastTrack::fEnvelopeLogicalVolume private
Definition at line 170 of file G4FastTrack.hh.
Referenced by FRecordsAffineTransformation(), and GetEnvelopeLogicalVolume().
fEnvelopePhysicalVolume
G4VPhysicalVolume* G4FastTrack::fEnvelopePhysicalVolume private
Definition at line 171 of file G4FastTrack.hh.
Referenced by FRecordsAffineTransformation(), and GetEnvelopePhysicalVolume().
fEnvelopeSolid
G4VSolid* G4FastTrack::fEnvelopeSolid private
Definition at line 172 of file G4FastTrack.hh.
Referenced by FRecordsAffineTransformation(), and GetEnvelopeSolid().
fInverseAffineTransformation
G4AffineTransform G4FastTrack::fInverseAffineTransformation private
Definition at line 177 of file G4FastTrack.hh.
Referenced by FRecordsAffineTransformation(), and GetInverseAffineTransformation().
fIsUnique
G4bool G4FastTrack::fIsUnique private
Definition at line 169 of file G4FastTrack.hh.
Referenced by SetCurrentTrack().
fLocalTrackDirection
G4ThreeVector G4FastTrack::fLocalTrackDirection private
Definition at line 173 of file G4FastTrack.hh.
Referenced by GetPrimaryTrackLocalDirection(), and SetCurrentTrack().
fLocalTrackMomentum
G4ThreeVector G4FastTrack::fLocalTrackMomentum private
Definition at line 173 of file G4FastTrack.hh.
Referenced by GetPrimaryTrackLocalMomentum(), and SetCurrentTrack().
fLocalTrackPolarization
G4ThreeVector G4FastTrack::fLocalTrackPolarization private
Definition at line 173 of file G4FastTrack.hh.
Referenced by GetPrimaryTrackLocalPolarization(), and SetCurrentTrack().
fLocalTrackPosition
G4ThreeVector G4FastTrack::fLocalTrackPosition private
Definition at line 173 of file G4FastTrack.hh.
Referenced by GetPrimaryTrackLocalPosition(), and SetCurrentTrack().
fTrack
const G4Track* G4FastTrack::fTrack private
Definition at line 160 of file G4FastTrack.hh.
Referenced by GetPrimaryTrack(), and SetCurrentTrack().
The documentation for this class was generated from the following files:
source/processes/parameterisation/include/G4FastTrack.hh
source/processes/parameterisation/src/G4FastTrack.cc