Geant4: G4Molecule Class Reference
G4Molecule Class Reference
Class Description The dynamic molecule holds all the data that change for a molecule It has a pointer to G4MoleculeDefinition object, which holds all the "ground level" information.
#include <G4Molecule.hh>
Public Member Functions
ITDef (G4Molecule) void Print() const
void * operator new (size_t)
void operator delete (void *)
G4Molecule (const G4Molecule &)
G4Molecule & operator= (const G4Molecule &right)
G4bool operator== (const G4Molecule &right) const
G4bool operator!= (const G4Molecule &right) const
G4bool operator< (const G4Molecule &right) const
The two methods below are the most called of the simulation : compare molecules in the MoleculeStackManager or in the InteractionTable.
operator int () const
virtual G4ITType GetITSubType () const
G4Molecule (G4MoleculeDefinition *molecule)
To build a molecule at ground state according to a given G4MoleculeDefinition that can be obtained from G4GenericMoleculeManager.
G4Molecule (G4MoleculeDefinition *molDef, int charge)
G4Molecule (G4MoleculeDefinition *molecule, G4int, G4int)
To build a molecule at a specific excitation/ionisation state according to a ground state that can be obtained from G4GenericMoleculeManager.
G4Molecule (G4MoleculeDefinition *molecule, G4int, G4bool)
Specific builder for water molecules to be used in Geant4-DNA, the last option Excitation is true if the molecule is excited, is false is the molecule is ionized.
G4Molecule (G4MolecularConfiguration *)
virtual ~G4Molecule ()
const G4String & GetName () const
Returns the name of the molecule.
const G4String & GetFormatedName () const
Returns the formated name of the molecule.
G4int GetAtomsNumber () const
Returns the nomber of atoms compouning the molecule.
void SetElectronOccupancy (const G4ElectronOccupancy *)
Will set up the correct molecularConfiguration given an electron configuration.
void ExciteMolecule (G4int)
Method used in Geant4-DNA to excite water molecules.
void IonizeMolecule (G4int)
Method used in Geant4-DNA to ionize water molecules.
void AddElectron (G4int orbit, G4int n=1)
Add n electrons to a given orbit.
void RemoveElectron (G4int, G4int number=1)
Remove n electrons to a given orbit.
void MoveOneElectron (G4int, G4int)
Move one electron from an orbit to another.
G4double GetNbElectrons () const
Returns the number of electron.
void PrintState () const
Show the electronic state of the molecule.
G4Track * BuildTrack (G4double globalTime, const G4ThreeVector &Position)
G4double GetKineticEnergy () const
G4double GetDiffusionVelocity () const
const std::vector< const G4MolecularDissociationChannel * > * GetDecayChannel () const
G4int GetFakeParticleID () const
G4int GetMoleculeID () const
const G4MoleculeDefinition * GetDefinition () const
Get molecule definition.
void SetDiffusionCoefficient (G4double)
Sets the diffusion coefficient D of the molecule used in diffusion processes to calculate the mean square jump distance between two changes of direction.
G4double GetDiffusionCoefficient () const
Returns the diffusion coefficient D.
G4double GetDiffusionCoefficient (const G4Material *, double temperature) const
Returns the diffusion coefficient D.
void SetDecayTime (G4double)
Set the decay time of the molecule.
G4double GetDecayTime () const
Returns the decay time of the molecule.
void SetVanDerVaalsRadius (G4double)
The Van Der Valls Radius of the molecule.
G4double GetVanDerVaalsRadius () const
const G4ElectronOccupancy * GetElectronOccupancy () const
Returns the object ElectronOccupancy describing the electronic configuration of the molecule.
G4int GetCharge () const
Returns the charge of molecule.
void SetMass (G4double)
Set the total mass of the molecule.
G4double GetMass () const
Returns the total mass of the molecule.
const G4String & GetLabel () const
Returns the label of the molecule configuration.
void SetLabel (const G4String &label)
void ChangeConfigurationToLabel (const G4String &label)
G4MolecularConfiguration * GetMolecularConfiguration () const
Public Member Functions inherited from G4IT
G4IT ()
G4IT (G4Track *)
virtual ~G4IT ()
virtual void Print () const
virtual G4bool diff (const G4IT &right) const =0
virtual G4bool equal (const G4IT &right) const =0
G4bool operator< (const G4IT &right) const
G4bool operator== (const G4IT &right) const
G4bool operator!= (const G4IT &right) const
void SetTrack (G4Track *)
G4Track * GetTrack ()
const G4Track * GetTrack () const
void RecordCurrentPositionNTime ()
const G4ThreeVector & GetPosition () const
double operator[] (int i) const
const G4ThreeVector & GetPreStepPosition () const
G4double GetPreStepLocalTime () const
G4double GetPreStepGlobalTime () const
void SetPrevious (G4IT *)
void SetNext (G4IT *)
G4IT * GetPrevious ()
G4IT * GetNext ()
const G4IT * GetPrevious () const
const G4IT * GetNext () const
void SetITBox (G4ITBox *)
const G4ITBox * GetITBox () const
void TakeOutBox ()
void SetNode (G4KDNode_Base *)
G4KDNode_Base * GetNode () const
void SetParentID (int, int)
void GetParentID (int &, int &)
G4TrackingInformation * GetTrackingInfo ()
G4TrackListNode * GetListNode ()
void SetListNode (G4TrackListNode *node)
virtual const G4ITType GetITType () const =0
Public Member Functions inherited from G4VUserTrackInformation
G4VUserTrackInformation ()
G4VUserTrackInformation (const G4String &infoType)
G4VUserTrackInformation (const G4VUserTrackInformation &)
G4VUserTrackInformation & operator= (const G4VUserTrackInformation &)
virtual ~G4VUserTrackInformation ()
const G4String & GetType () const
Static Public Member Functions
static G4Molecule * GetMolecule (const G4Track *)
Private Member Functions
G4Molecule ()
Default molecule builder.
Private Attributes
G4MolecularConfiguration * fpMolecularConfiguration
Additional Inherited Members
Protected Member Functions inherited from G4IT
G4IT (const G4IT &)
G4IT & operator= (const G4IT &)
Protected Attributes inherited from G4IT
G4Track * fpTrack
Protected Attributes inherited from G4VUserTrackInformation
G4String * pType
Detailed Description
Class Description The dynamic molecule holds all the data that change for a molecule It has a pointer to G4MoleculeDefinition object, which holds all the "ground level" information.
Definition at line 98 of file G4Molecule.hh.
Constructor & Destructor Documentation
G4Molecule() [1/7]
G4Molecule::G4Molecule (const G4Molecule & right)
Definition at line 107 of file G4Molecule.cc.
G4Molecule() [2/7]
G4Molecule::G4Molecule (G4MoleculeDefinition * molecule)
To build a molecule at ground state according to a given G4MoleculeDefinition that can be obtained from G4GenericMoleculeManager.
Build a molecule at ground state according to a given G4MoleculeDefinition that can be obtained from G4GenericMoleculeManager.
Definition at line 184 of file G4Molecule.cc.
G4Molecule() [3/7]
G4Molecule::G4Molecule (G4MoleculeDefinition * molDef, int charge)
Definition at line 195 of file G4Molecule.cc.
G4Molecule() [4/7]
G4Molecule::G4Molecule (G4MoleculeDefinition * moleculeDefinition, G4int OrbitalToFree, G4int OrbitalToFill)
To build a molecule at a specific excitation/ionisation state according to a ground state that can be obtained from G4GenericMoleculeManager.
Build a molecule at a specific excitation/ionisation state according to a ground state that can be obtained from G4GenericMoleculeManager.
Put 0 in the second option if this is a ionisation.
Definition at line 209 of file G4Molecule.cc.
G4Molecule() [5/7]
G4Molecule::G4Molecule (G4MoleculeDefinition * molecule, G4int Level, G4bool Excitation)
Specific builder for water molecules to be used in Geant4-DNA, the last option Excitation is true if the molecule is excited, is false is the molecule is ionized.
Definition at line 256 of file G4Molecule.cc.
G4Molecule() [6/7]
G4Molecule::G4Molecule (G4MolecularConfiguration * molConf)
Definition at line 299 of file G4Molecule.cc.
~G4Molecule()
G4Molecule::~G4Molecule () virtual
Definition at line 163 of file G4Molecule.cc.
G4Molecule() [7/7]
G4Molecule::G4Molecule () private
Default molecule builder.
Definition at line 154 of file G4Molecule.cc.
Member Function Documentation
AddElectron()
void G4Molecule::AddElectron (G4int orbit, G4int n = 1)
Add n electrons to a given orbit.
Note : You can add as many electrons to a given orbit, the result may be unrealist.
Definition at line 335 of file G4Molecule.cc.
BuildTrack()
G4Track * G4Molecule::BuildTrack (G4double globalTime, const G4ThreeVector & Position)
Definition at line 394 of file G4Molecule.cc.
Referenced by G4MoleculeGun::BuildAndPushTrack(), G4DNAChemistryManager::CreateSolvatedElectron(), G4DNAChemistryManager::CreateWaterMolecule(), G4DNAMolecularDissociation::DecayIt(), G4DNAMolecularReaction::MakeReaction(), G4DNAChemistryManager::PushMolecule(), and G4DNAChemistryManager::PushMoleculeAtParentTimeAndPlace().
ChangeConfigurationToLabel()
void G4Molecule::ChangeConfigurationToLabel (const G4String & label)
Definition at line 614 of file G4Molecule.cc.
Referenced by G4DNAElectronHoleRecombination::MakeReaction().
ExciteMolecule()
void G4Molecule::ExciteMolecule (G4int ExcitedLevel)
Method used in Geant4-DNA to excite water molecules.
Definition at line 317 of file G4Molecule.cc.
GetAtomsNumber()
G4int G4Molecule::GetAtomsNumber () const
Returns the nomber of atoms compouning the molecule.
Definition at line 373 of file G4Molecule.cc.
GetCharge()
G4int G4Molecule::GetCharge () const
Returns the charge of molecule.
Definition at line 521 of file G4Molecule.cc.
GetDecayChannel()
const vector< const G4MolecularDissociationChannel * > * G4Molecule::GetDecayChannel () const
Definition at line 472 of file G4Molecule.cc.
Referenced by G4DNAMolecularDissociation::DecayIt().
GetDecayTime()
G4double G4Molecule::GetDecayTime () const
Returns the decay time of the molecule.
Definition at line 500 of file G4Molecule.cc.
Referenced by G4DNAMolecularDissociation::GetMeanLifeTime().
GetDefinition()
const G4MoleculeDefinition * G4Molecule::GetDefinition () const
Get molecule definition.
This G4MoleculeDefinition has the ground electronic state of the molecule.
Definition at line 549 of file G4Molecule.cc.
Referenced by G4DNAMolecularDissociation::DecayIt().
GetDiffusionCoefficient() [1/2]
G4double G4Molecule::GetDiffusionCoefficient () const
Returns the diffusion coefficient D.
Definition at line 563 of file G4Molecule.cc.
Referenced by G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength(), G4DNABrownianTransportation::ComputeStep(), G4DNASmoluchowskiReactionModel::FindReaction(), and G4DNAMoleculeEncounterStepper::Utils::Utils().
GetDiffusionCoefficient() [2/2]
G4double G4Molecule::GetDiffusionCoefficient (const G4Material * mat, double temperature) const
Returns the diffusion coefficient D.
Definition at line 570 of file G4Molecule.cc.
GetDiffusionVelocity()
G4double G4Molecule::GetDiffusionVelocity () const
Definition at line 447 of file G4Molecule.cc.
Referenced by GetKineticEnergy().
GetElectronOccupancy()
const G4ElectronOccupancy * G4Molecule::GetElectronOccupancy () const
Returns the object ElectronOccupancy describing the electronic configuration of the molecule.
Definition at line 542 of file G4Molecule.cc.
GetFakeParticleID()
G4int G4Molecule::GetFakeParticleID () const
Definition at line 479 of file G4Molecule.cc.
GetFormatedName()
const G4String & G4Molecule::GetFormatedName () const
Returns the formated name of the molecule.
Definition at line 366 of file G4Molecule.cc.
GetITSubType()
virtual G4ITType G4Molecule::GetITSubType () const inline virtual
Reimplemented from G4IT.
Definition at line 128 of file G4Molecule.hh.
GetKineticEnergy()
G4double G4Molecule::GetKineticEnergy () const
Definition at line 435 of file G4Molecule.cc.
Referenced by BuildTrack().
GetLabel()
const G4String & G4Molecule::GetLabel () const
Returns the label of the molecule configuration.
Definition at line 600 of file G4Molecule.cc.
GetMass()
G4double G4Molecule::GetMass () const
Returns the total mass of the molecule.
Definition at line 535 of file G4Molecule.cc.
GetMolecularConfiguration()
G4MolecularConfiguration * G4Molecule::GetMolecularConfiguration () const
Definition at line 579 of file G4Molecule.cc.
Referenced by G4MolecularDissociationChannel::AddProduct(), G4DNAMoleculeEncounterStepper::CalculateStep(), G4MolecularDissociationChannel::GetRMSRadialDisplacementOfProduct(), G4DNAMolecularReaction::MakeReaction(), G4DNASecondOrderReaction::PostStepGetPhysicalInteractionLength(), and G4DNAMolecularReaction::TestReactibility().
GetMolecule()
G4Molecule * G4Molecule::GetMolecule (const G4Track * track) static
Definition at line 93 of file G4Molecule.cc.
GetMoleculeID()
G4int G4Molecule::GetMoleculeID () const
Definition at line 486 of file G4Molecule.cc.
Referenced by G4DNAElectronHoleRecombination::FindReactant(), GetITSubType(), and operator int().
GetName()
const G4String & G4Molecule::GetName (void) const virtual
Returns the name of the molecule.
Implements G4IT.
Definition at line 359 of file G4Molecule.cc.
Referenced by G4DNAMoleculeEncounterStepper::CalculateStep(), G4DNAMoleculeEncounterStepper::CheckAndRecordResults(), G4DNABrownianTransportation::ComputeStep(), G4DNAMolecularDissociation::DecayIt(), G4DNABrownianTransportation::Diffusion(), G4DNASmoluchowskiReactionModel::FindReaction(), Run::MoleculeCountNeuron(), G4DNASecondOrderReaction::PostStepDoIt(), G4DNABrownianTransportation::PostStepDoIt(), and G4DNAIndirectHit::Print().
GetNbElectrons()
G4double G4Molecule::GetNbElectrons () const
Returns the number of electron.
Definition at line 380 of file G4Molecule.cc.
GetVanDerVaalsRadius()
G4double G4Molecule::GetVanDerVaalsRadius () const
Definition at line 514 of file G4Molecule.cc.
IonizeMolecule()
void G4Molecule::IonizeMolecule (G4int IonizedLevel)
Method used in Geant4-DNA to ionize water molecules.
Definition at line 327 of file G4Molecule.cc.
ITDef()
G4Molecule::ITDef (G4Molecule) const
MoveOneElectron()
void G4Molecule::MoveOneElectron (G4int orbitToFree, G4int orbitToFill)
Move one electron from an orbit to another.
Definition at line 351 of file G4Molecule.cc.
operator delete()
void G4Molecule::operator delete (void * aMolecule) inline
Definition at line 316 of file G4Molecule.hh.
operator int()
G4Molecule::operator int () const inline
Definition at line 123 of file G4Molecule.hh.
operator new()
void * G4Molecule::operator new (size_t) inline
Definition at line 308 of file G4Molecule.hh.
operator!=()
G4bool G4Molecule::operator!= (const G4Molecule & right) const
Definition at line 135 of file G4Molecule.cc.
operator<()
G4bool G4Molecule::operator< (const G4Molecule & right) const
The two methods below are the most called of the simulation : compare molecules in the MoleculeStackManager or in the InteractionTable.
Definition at line 146 of file G4Molecule.cc.
operator=()
G4Molecule & G4Molecule::operator= (const G4Molecule & right)
Definition at line 115 of file G4Molecule.cc.
operator==()
G4bool G4Molecule::operator== (const G4Molecule & right) const
Definition at line 124 of file G4Molecule.cc.
PrintState()
void G4Molecule::PrintState () const
Show the electronic state of the molecule.
Definition at line 387 of file G4Molecule.cc.
Referenced by G4DNAMolecularDissociation::DecayIt().
RemoveElectron()
void G4Molecule::RemoveElectron (G4int orbit, G4int number = 1)
Remove n electrons to a given orbit.
Definition at line 343 of file G4Molecule.cc.
SetDecayTime()
void G4Molecule::SetDecayTime (G4double dynDecayTime)
Set the decay time of the molecule.
Definition at line 493 of file G4Molecule.cc.
SetDiffusionCoefficient()
void G4Molecule::SetDiffusionCoefficient (G4double dynDiffusionCoefficient)
Sets the diffusion coefficient D of the molecule used in diffusion processes to calculate the mean square jump distance between two changes of direction.
In three dimension : <x^2> = 6 D t where t is the mean jump time between two changes of direction.
Definition at line 556 of file G4Molecule.cc.
SetElectronOccupancy()
void G4Molecule::SetElectronOccupancy (const G4ElectronOccupancy * occ)
Will set up the correct molecularConfiguration given an electron configuration.
Definition at line 306 of file G4Molecule.cc.
SetLabel()
void G4Molecule::SetLabel (const G4String & label)
Definition at line 607 of file G4Molecule.cc.
SetMass()
void G4Molecule::SetMass (G4double aMass)
Set the total mass of the molecule.
Definition at line 528 of file G4Molecule.cc.
SetVanDerVaalsRadius()
void G4Molecule::SetVanDerVaalsRadius (G4double dynVanDerVaalsRadius)
The Van Der Valls Radius of the molecule.
Definition at line 507 of file G4Molecule.cc.
Field Documentation
fpMolecularConfiguration
G4MolecularConfiguration* G4Molecule::fpMolecularConfiguration private
Definition at line 294 of file G4Molecule.hh.
Referenced by AddElectron(), BuildTrack(), ChangeConfigurationToLabel(), ExciteMolecule(), G4Molecule(), GetAtomsNumber(), GetCharge(), GetDecayChannel(), GetDecayTime(), GetDefinition(), GetDiffusionCoefficient(), GetDiffusionVelocity(), GetElectronOccupancy(), GetFakeParticleID(), GetFormatedName(), GetKineticEnergy(), GetLabel(), GetMass(), GetMolecularConfiguration(), GetMoleculeID(), GetName(), GetNbElectrons(), GetVanDerVaalsRadius(), IonizeMolecule(), MoveOneElectron(), operator<(), operator=(), operator==(), PrintState(), RemoveElectron(), SetDecayTime(), SetDiffusionCoefficient(), SetElectronOccupancy(), SetLabel(), SetMass(), SetVanDerVaalsRadius(), and ~G4Molecule().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/dna/molecules/management/include/G4Molecule.hh
source/processes/electromagnetic/dna/molecules/management/src/G4Molecule.cc