Geant4: G4MultiUnion Class Reference
G4MultiUnion Class Reference
#include <G4MultiUnion.hh>
Data Structures
struct G4MultiUnionSurface
Public Member Functions
G4MultiUnion ()
G4MultiUnion (const G4String &name)
~G4MultiUnion ()
void AddNode (G4VSolid &solid, G4Transform3D &trans)
G4MultiUnion (const G4MultiUnion &rhs)
G4MultiUnion & operator= (const G4MultiUnion &rhs)
const G4Transform3D & GetTransformation (G4int index) const
G4VSolid * GetSolid (G4int index) const
G4int GetNumberOfSolids () const
EInside Inside (const G4ThreeVector &aPoint) const
EInside InsideIterator (const G4ThreeVector &aPoint) const
G4double DistanceToIn (const G4ThreeVector &aPoint) const
G4double DistanceToOut (const G4ThreeVector &aPoint) const
void SetAccurateSafety (G4bool flag)
G4double DistanceToIn (const G4ThreeVector &aPoint, const G4ThreeVector &aDirection) const
G4double DistanceToOut (const G4ThreeVector &aPoint, const G4ThreeVector &aDirection, const G4bool calcNorm=false, G4bool *validNorm=0, G4ThreeVector *aNormalVector=0) const
G4double DistanceToInNoVoxels (const G4ThreeVector &aPoint, const G4ThreeVector &aDirection) const
G4double DistanceToOutVoxels (const G4ThreeVector &aPoint, const G4ThreeVector &aDirection, G4ThreeVector *aNormalVector) const
G4double DistanceToOutVoxelsCore (const G4ThreeVector &aPoint, const G4ThreeVector &aDirection, G4ThreeVector *aNormalVector, G4bool &aConvex, std::vector< G4int > &candidates) const
G4double DistanceToOutNoVoxels (const G4ThreeVector &aPoint, const G4ThreeVector &aDirection, G4ThreeVector *aNormalVector) const
G4ThreeVector SurfaceNormal (const G4ThreeVector &aPoint) const
void Extent (EAxis aAxis, G4double &aMin, G4double &aMax) const
void BoundingLimits (G4ThreeVector &aMin, G4ThreeVector &aMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pMin, G4double &pMax) const
G4double GetCubicVolume ()
G4double GetSurfaceArea ()
G4VSolid * Clone () const
G4GeometryType GetEntityType () const
void Voxelize ()
EInside InsideNoVoxels (const G4ThreeVector &aPoint) const
G4Voxelizer & GetVoxels () const
std::ostream & StreamInfo (std::ostream &os) const
G4ThreeVector GetPointOnSurface () const
void DescribeYourselfTo (G4VGraphicsScene &scene) const
G4Polyhedron * CreatePolyhedron () const
G4Polyhedron * GetPolyhedron () const
G4MultiUnion (__void__ &)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
virtual void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
void DumpInfo () const
virtual G4VisExtent GetExtent () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Private Member Functions
EInside InsideWithExclusion (const G4ThreeVector &aPoint, G4SurfBits *bits=0) const
G4int SafetyFromOutsideNumberNode (const G4ThreeVector &aPoint, G4double &safety) const
G4double DistanceToInCandidates (const G4ThreeVector &aPoint, const G4ThreeVector &aDirection, std::vector< G4int > &candidates, G4SurfBits &bits) const
G4ThreeVector GetLocalPoint (const G4Transform3D &trans, const G4ThreeVector &gpoint) const
G4ThreeVector GetLocalVector (const G4Transform3D &trans, const G4ThreeVector &gvec) const
G4ThreeVector GetGlobalPoint (const G4Transform3D &trans, const G4ThreeVector &lpoint) const
G4ThreeVector GetGlobalVector (const G4Transform3D &trans, const G4ThreeVector &lvec) const
void TransformLimits (G4ThreeVector &min, G4ThreeVector &max, const G4Transform3D &transformation) const
Private Attributes
std::vector< G4VSolid * > fSolids
std::vector< G4Transform3D > fTransformObjs
G4Voxelizer fVoxels
G4double fCubicVolume
G4double fSurfaceArea
G4double kRadTolerance
G4bool fAccurate
G4bool fRebuildPolyhedron
G4Polyhedron * fpPolyhedron
Friends
class G4Voxelizer
Additional Inherited Members
Protected Member Functions inherited from G4VSolid
void CalculateClippedPolygonExtent (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipCrossSection (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipBetweenSections (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipPolygon (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis) const
Protected Attributes inherited from G4VSolid
G4double kCarTolerance
Detailed Description
Definition at line 60 of file G4MultiUnion.hh.
Constructor & Destructor Documentation
G4MultiUnion() [1/4]
G4MultiUnion::G4MultiUnion () inline
Definition at line 66 of file G4MultiUnion.hh.
Referenced by Clone().
G4MultiUnion() [2/4]
G4MultiUnion::G4MultiUnion (const G4String & name)
Definition at line 58 of file G4MultiUnion.cc.
~G4MultiUnion()
G4MultiUnion::~G4MultiUnion ()
Definition at line 71 of file G4MultiUnion.cc.
G4MultiUnion() [3/4]
G4MultiUnion::G4MultiUnion (const G4MultiUnion & rhs)
Definition at line 90 of file G4MultiUnion.cc.
G4MultiUnion() [4/4]
G4MultiUnion::G4MultiUnion (__void__ & a)
Definition at line 100 of file G4MultiUnion.cc.
Member Function Documentation
AddNode()
void G4MultiUnion::AddNode (G4VSolid & solid, G4Transform3D & trans)
Definition at line 76 of file G4MultiUnion.cc.
Referenced by G4GDMLReadSolids::MultiUnionNodeRead().
BoundingLimits()
void G4MultiUnion::BoundingLimits (G4ThreeVector & aMin, G4ThreeVector & aMax) const virtual
Reimplemented from G4VSolid.
Definition at line 618 of file G4MultiUnion.cc.
Referenced by CalculateExtent(), and GetCubicVolume().
CalculateExtent()
G4bool G4MultiUnion::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pMin, G4double & pMax) const virtual
Implements G4VSolid.
Definition at line 628 of file G4MultiUnion.cc.
Clone()
G4VSolid * G4MultiUnion::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 83 of file G4MultiUnion.cc.
CreatePolyhedron()
G4Polyhedron * G4MultiUnion::CreatePolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 970 of file G4MultiUnion.cc.
Referenced by GetPolyhedron().
DescribeYourselfTo()
void G4MultiUnion::DescribeYourselfTo (G4VGraphicsScene & scene) const virtual
Implements G4VSolid.
Definition at line 964 of file G4MultiUnion.cc.
DistanceToIn() [1/2]
G4double G4MultiUnion::DistanceToIn (const G4ThreeVector & aPoint) const virtual
Implements G4VSolid.
Definition at line 762 of file G4MultiUnion.cc.
DistanceToIn() [2/2]
G4double G4MultiUnion::DistanceToIn (const G4ThreeVector & aPoint, const G4ThreeVector & aDirection) const virtual
Implements G4VSolid.
Definition at line 214 of file G4MultiUnion.cc.
DistanceToInCandidates()
G4double G4MultiUnion::DistanceToInCandidates (const G4ThreeVector & aPoint, const G4ThreeVector & aDirection, std::vector< G4int > & candidates, G4SurfBits & bits) const private
Definition at line 178 of file G4MultiUnion.cc.
Referenced by DistanceToIn().
DistanceToInNoVoxels()
G4double G4MultiUnion::DistanceToInNoVoxels (const G4ThreeVector & aPoint, const G4ThreeVector & aDirection) const
Definition at line 155 of file G4MultiUnion.cc.
DistanceToOut() [1/2]
G4double G4MultiUnion::DistanceToOut (const G4ThreeVector & aPoint) const virtual
Implements G4VSolid.
Definition at line 725 of file G4MultiUnion.cc.
DistanceToOut() [2/2]
G4double G4MultiUnion::DistanceToOut (const G4ThreeVector & aPoint, const G4ThreeVector & aDirection, const G4bool calcNorm = false, G4bool * validNorm = 0, G4ThreeVector * aNormalVector = 0) const virtual
Implements G4VSolid.
Definition at line 299 of file G4MultiUnion.cc.
DistanceToOutNoVoxels()
G4double G4MultiUnion::DistanceToOutNoVoxels (const G4ThreeVector & aPoint, const G4ThreeVector & aDirection, G4ThreeVector * aNormalVector) const
Definition at line 248 of file G4MultiUnion.cc.
DistanceToOutVoxels()
G4double G4MultiUnion::DistanceToOutVoxels (const G4ThreeVector & aPoint, const G4ThreeVector & aDirection, G4ThreeVector * aNormalVector) const
Definition at line 309 of file G4MultiUnion.cc.
Referenced by DistanceToOut().
DistanceToOutVoxelsCore()
G4double G4MultiUnion::DistanceToOutVoxelsCore (const G4ThreeVector & aPoint, const G4ThreeVector & aDirection, G4ThreeVector * aNormalVector, G4bool & aConvex, std::vector< G4int > & candidates) const
Extent()
void G4MultiUnion::Extent (EAxis aAxis, G4double & aMin, G4double & aMax) const
Definition at line 553 of file G4MultiUnion.cc.
Referenced by BoundingLimits().
GetCubicVolume()
G4double G4MultiUnion::GetCubicVolume () virtual
Reimplemented from G4VSolid.
Definition at line 125 of file G4MultiUnion.cc.
GetEntityType()
G4GeometryType G4MultiUnion::GetEntityType () const inline virtual
Implements G4VSolid.
Definition at line 127 of file G4MultiUnion.hh.
GetGlobalPoint()
G4ThreeVector G4MultiUnion::GetGlobalPoint (const G4Transform3D & trans, const G4ThreeVector & lpoint) const inline private
Definition at line 252 of file G4MultiUnion.hh.
Referenced by DistanceToOutNoVoxels(), GetPointOnSurface(), and TransformLimits().
GetGlobalVector()
G4ThreeVector G4MultiUnion::GetGlobalVector (const G4Transform3D & trans, const G4ThreeVector & lvec) const inline private
Definition at line 264 of file G4MultiUnion.hh.
Referenced by DistanceToOutVoxels(), and SurfaceNormal().
GetLocalPoint()
G4ThreeVector G4MultiUnion::GetLocalPoint (const G4Transform3D & trans, const G4ThreeVector & gpoint) const inline private
Definition at line 223 of file G4MultiUnion.hh.
Referenced by DistanceToIn(), DistanceToInCandidates(), DistanceToInNoVoxels(), DistanceToOut(), DistanceToOutNoVoxels(), DistanceToOutVoxels(), InsideNoVoxels(), InsideWithExclusion(), SafetyFromOutsideNumberNode(), and SurfaceNormal().
GetLocalVector()
G4ThreeVector G4MultiUnion::GetLocalVector (const G4Transform3D & trans, const G4ThreeVector & gvec) const inline private
Definition at line 235 of file G4MultiUnion.hh.
Referenced by DistanceToInCandidates(), DistanceToInNoVoxels(), DistanceToOutNoVoxels(), and DistanceToOutVoxels().
GetNumberOfSolids()
G4int G4MultiUnion::GetNumberOfSolids () const inline
Definition at line 210 of file G4MultiUnion.hh.
Referenced by CreatePolyhedron(), and G4GDMLWriteSolids::MultiUnionWrite().
GetPointOnSurface()
G4ThreeVector G4MultiUnion::GetPointOnSurface () const virtual
Reimplemented from G4VSolid.
Definition at line 943 of file G4MultiUnion.cc.
GetPolyhedron()
G4Polyhedron * G4MultiUnion::GetPolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 995 of file G4MultiUnion.cc.
GetSolid()
G4VSolid * G4MultiUnion::GetSolid (G4int index) const inline
Definition at line 204 of file G4MultiUnion.hh.
Referenced by CreatePolyhedron(), and G4GDMLWriteSolids::MultiUnionWrite().
GetSurfaceArea()
G4double G4MultiUnion::GetSurfaceArea () virtual
Reimplemented from G4VSolid.
Definition at line 813 of file G4MultiUnion.cc.
GetTransformation()
const G4Transform3D & G4MultiUnion::GetTransformation (G4int index) const inline
Definition at line 198 of file G4MultiUnion.hh.
Referenced by CreatePolyhedron(), Extent(), InsideNoVoxels(), and G4GDMLWriteSolids::MultiUnionWrite().
GetVoxels()
G4Voxelizer & G4MultiUnion::GetVoxels () const inline
Definition at line 192 of file G4MultiUnion.hh.
Inside()
EInside G4MultiUnion::Inside (const G4ThreeVector & aPoint) const virtual
Implements G4VSolid.
Definition at line 505 of file G4MultiUnion.cc.
Referenced by GetCubicVolume(), and GetPointOnSurface().
InsideIterator()
EInside G4MultiUnion::InsideIterator (const G4ThreeVector & aPoint) const
InsideNoVoxels()
EInside G4MultiUnion::InsideNoVoxels (const G4ThreeVector & aPoint) const
Definition at line 525 of file G4MultiUnion.cc.
InsideWithExclusion()
EInside G4MultiUnion::InsideWithExclusion (const G4ThreeVector & aPoint, G4SurfBits * bits = 0) const private
Definition at line 431 of file G4MultiUnion.cc.
Referenced by DistanceToOutVoxels(), and Inside().
operator=()
G4MultiUnion & G4MultiUnion::operator= (const G4MultiUnion & rhs)
Definition at line 108 of file G4MultiUnion.cc.
SafetyFromOutsideNumberNode()
G4int G4MultiUnion::SafetyFromOutsideNumberNode (const G4ThreeVector & aPoint, G4double & safety) const private
Definition at line 829 of file G4MultiUnion.cc.
Referenced by SurfaceNormal().
SetAccurateSafety()
void G4MultiUnion::SetAccurateSafety (G4bool flag) inline
Definition at line 216 of file G4MultiUnion.hh.
StreamInfo()
std::ostream & G4MultiUnion::StreamInfo (std::ostream & os) const virtual
Implements G4VSolid.
Definition at line 917 of file G4MultiUnion.cc.
SurfaceNormal()
G4ThreeVector G4MultiUnion::SurfaceNormal (const G4ThreeVector & aPoint) const virtual
Implements G4VSolid.
Definition at line 644 of file G4MultiUnion.cc.
TransformLimits()
void G4MultiUnion::TransformLimits (G4ThreeVector & min, G4ThreeVector & max, const G4Transform3D & transformation) const private
Definition at line 873 of file G4MultiUnion.cc.
Referenced by Extent().
Voxelize()
void G4MultiUnion::Voxelize ()
Definition at line 823 of file G4MultiUnion.cc.
Referenced by G4GDMLReadSolids::MultiUnionRead().
Friends And Related Function Documentation
G4Voxelizer
friend class G4Voxelizer friend
Definition at line 62 of file G4MultiUnion.hh.
Field Documentation
fAccurate
G4bool G4MultiUnion::fAccurate mutable private
Definition at line 185 of file G4MultiUnion.hh.
Referenced by DistanceToIn(), SafetyFromOutsideNumberNode(), and SetAccurateSafety().
fCubicVolume
G4double G4MultiUnion::fCubicVolume private
Definition at line 182 of file G4MultiUnion.hh.
Referenced by G4MultiUnion(), and GetCubicVolume().
fpPolyhedron
G4Polyhedron* G4MultiUnion::fpPolyhedron mutable private
Definition at line 188 of file G4MultiUnion.hh.
Referenced by GetPolyhedron().
fRebuildPolyhedron
G4bool G4MultiUnion::fRebuildPolyhedron mutable private
Definition at line 187 of file G4MultiUnion.hh.
Referenced by GetPolyhedron().
fSolids
std::vector<G4VSolid*> G4MultiUnion::fSolids private
Definition at line 179 of file G4MultiUnion.hh.
Referenced by AddNode(), DistanceToIn(), DistanceToInCandidates(), DistanceToInNoVoxels(), DistanceToOut(), DistanceToOutNoVoxels(), DistanceToOutVoxels(), Extent(), G4MultiUnion(), GetNumberOfSolids(), GetPointOnSurface(), GetSolid(), InsideNoVoxels(), InsideWithExclusion(), SafetyFromOutsideNumberNode(), StreamInfo(), SurfaceNormal(), and Voxelize().
fSurfaceArea
G4double G4MultiUnion::fSurfaceArea private
Definition at line 183 of file G4MultiUnion.hh.
Referenced by G4MultiUnion(), and GetSurfaceArea().
fTransformObjs
std::vector<G4Transform3D> G4MultiUnion::fTransformObjs private
Definition at line 180 of file G4MultiUnion.hh.
Referenced by AddNode(), DistanceToIn(), DistanceToInCandidates(), DistanceToInNoVoxels(), DistanceToOut(), DistanceToOutNoVoxels(), DistanceToOutVoxels(), G4MultiUnion(), GetPointOnSurface(), GetTransformation(), InsideWithExclusion(), SafetyFromOutsideNumberNode(), StreamInfo(), SurfaceNormal(), and Voxelize().
fVoxels
G4Voxelizer G4MultiUnion::fVoxels private
Definition at line 181 of file G4MultiUnion.hh.
Referenced by DistanceToIn(), DistanceToOut(), DistanceToOutVoxels(), GetVoxels(), InsideWithExclusion(), SafetyFromOutsideNumberNode(), SurfaceNormal(), and Voxelize().
kRadTolerance
G4double G4MultiUnion::kRadTolerance private
Definition at line 184 of file G4MultiUnion.hh.
Referenced by G4MultiUnion(), and InsideWithExclusion().
The documentation for this class was generated from the following files:
source/geometry/solids/Boolean/include/G4MultiUnion.hh
source/geometry/solids/Boolean/src/G4MultiUnion.cc