Geant4: G4PairingCorrection Class Reference
G4PairingCorrection Class Reference
#include <G4PairingCorrection.hh>
Public Member Functions
G4PairingCorrection ()
~G4PairingCorrection ()
G4double GetPairingCorrection (G4int A, G4int Z) const
G4double GetFissionPairingCorrection (G4int A, G4int Z) const
Private Attributes
G4CookPairingCorrections theCookPairingCorrections
G4CameronGilbertPairingCorrections theCameronGilbertPairingCorrections
Detailed Description
Definition at line 41 of file G4PairingCorrection.hh.
Constructor & Destructor Documentation
G4PairingCorrection()
G4PairingCorrection::G4PairingCorrection () explicit
Definition at line 38 of file G4PairingCorrection.cc.
~G4PairingCorrection()
G4PairingCorrection::~G4PairingCorrection ()
Definition at line 41 of file G4PairingCorrection.cc.
Member Function Documentation
GetFissionPairingCorrection()
G4double G4PairingCorrection::GetFissionPairingCorrection (G4int A, G4int Z) const
Definition at line 59 of file G4PairingCorrection.cc.
Referenced by G4FissionProbability::EmissionProbability(), G4CompetitiveFission::EmittedFragment(), and G4CompetitiveFission::GetEmissionProbability().
GetPairingCorrection()
G4double G4PairingCorrection::GetPairingCorrection (G4int A, G4int Z) const
Definition at line 44 of file G4PairingCorrection.cc.
Referenced by G4GEMProbability::CalcProbability(), G4FissionProbability::EmissionProbability(), G4GEMProbability::GetCoulombBarrier(), G4GEMChannel::GetEmissionProbability(), G4GEMChannelVI::GetEmissionProbability(), G4EvaporationChannel::GetEmissionProbability(), G4NuclearLevelData::GetPairingCorrection(), G4GEMChannel::SampleKineticEnergy(), and G4EvaporationProbability::TotalProbability().
Field Documentation
theCameronGilbertPairingCorrections
G4CameronGilbertPairingCorrections G4PairingCorrection::theCameronGilbertPairingCorrections private
Definition at line 56 of file G4PairingCorrection.hh.
Referenced by GetPairingCorrection().
theCookPairingCorrections
G4CookPairingCorrections G4PairingCorrection::theCookPairingCorrections private
Definition at line 55 of file G4PairingCorrection.hh.
The documentation for this class was generated from the following files:
source/processes/hadronic/models/de_excitation/util/include/G4PairingCorrection.hh
source/processes/hadronic/models/de_excitation/util/src/G4PairingCorrection.cc