Geant4: G4ExcitedLambdaConstructor Class Reference
G4ExcitedLambdaConstructor Class Reference
#include <G4ExcitedLambdaConstructor.hh>
Public Types
enum { NStates = 12 }
enum { NumberOfDecayModes = 7 }
Public Member Functions
G4ExcitedLambdaConstructor ()
virtual ~G4ExcitedLambdaConstructor ()
Public Member Functions inherited from G4ExcitedBaryonConstructor
G4ExcitedBaryonConstructor (G4int nStates=0, G4int isoSpin=0)
virtual ~G4ExcitedBaryonConstructor ()
virtual void Construct (G4int indexOfState=-1)
Protected Member Functions
virtual G4bool Exist (G4int)
virtual G4int GetQuarkContents (G4int, G4int)
virtual G4String GetName (G4int iIso3, G4int iState)
virtual G4String GetMultipletName (G4int iState)
virtual G4double GetMass (G4int state, G4int iso)
virtual G4double GetWidth (G4int state, G4int iso)
virtual G4int GetiSpin (G4int iState)
virtual G4int GetiParity (G4int iState)
virtual G4int GetEncodingOffset (G4int iState)
virtual G4DecayTable * CreateDecayTable (const G4String &name, G4int iIso3, G4int iState, G4bool fAnti=false)
Protected Member Functions inherited from G4ExcitedBaryonConstructor
virtual void ConstructParticle (G4int indexOfState)
virtual void ConstructAntiParticle (G4int indexOfState)
virtual G4double GetCharge (G4int iIsoSpin3)
virtual G4int GetEncoding (G4int iIsoSpin3, G4int idxState)
Private Types
enum { LambdaIsoSpin = 0 }
enum {
NK =0, NKStar =1, SigmaPi =2, SigmaStarPi =3,
LambdaGamma =4, LambdaEta =5, LambdaOmega =6
}
Private Member Functions
G4DecayTable * AddNKMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddNKStarMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddSigmaPiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddSigmaStarPiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddLambdaGammaMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddLambdaEtaMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddLambdaOmegaMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
Static Private Attributes
static const char * name [NStates]
static const G4double mass [NStates]
static const G4double width [NStates]
static const G4int iSpin [NStates]
static const G4int iParity [NStates]
static const G4int encodingOffset [NStates]
static const G4double bRatio [NStates][NumberOfDecayModes]
Additional Inherited Members
Protected Attributes inherited from G4ExcitedBaryonConstructor
G4int NumberOfStates
G4int iIsoSpin
const G4String type
const G4int iConjugation
const G4int iGParity
const G4int leptonNumber
const G4int baryonNumber
Detailed Description
Definition at line 42 of file G4ExcitedLambdaConstructor.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
NStates
Definition at line 83 of file G4ExcitedLambdaConstructor.hh.
anonymous enum
anonymous enum private
Enumerator
LambdaIsoSpin
Definition at line 85 of file G4ExcitedLambdaConstructor.hh.
anonymous enum
anonymous enum
Enumerator
NumberOfDecayModes
Definition at line 96 of file G4ExcitedLambdaConstructor.hh.
anonymous enum
anonymous enum private
Enumerator
NK
NKStar
SigmaPi
SigmaStarPi
LambdaGamma
LambdaEta
LambdaOmega
Definition at line 98 of file G4ExcitedLambdaConstructor.hh.
Constructor & Destructor Documentation
G4ExcitedLambdaConstructor()
G4ExcitedLambdaConstructor::G4ExcitedLambdaConstructor ()
Definition at line 46 of file G4ExcitedLambdaConstructor.cc.
~G4ExcitedLambdaConstructor()
G4ExcitedLambdaConstructor::~G4ExcitedLambdaConstructor () virtual
Definition at line 52 of file G4ExcitedLambdaConstructor.cc.
Member Function Documentation
AddLambdaEtaMode()
G4DecayTable * G4ExcitedLambdaConstructor::AddLambdaEtaMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 115 of file G4ExcitedLambdaConstructor.cc.
Referenced by CreateDecayTable().
AddLambdaGammaMode()
G4DecayTable * G4ExcitedLambdaConstructor::AddLambdaGammaMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 97 of file G4ExcitedLambdaConstructor.cc.
Referenced by CreateDecayTable().
AddLambdaOmegaMode()
G4DecayTable * G4ExcitedLambdaConstructor::AddLambdaOmegaMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 134 of file G4ExcitedLambdaConstructor.cc.
Referenced by CreateDecayTable().
AddNKMode()
G4DecayTable * G4ExcitedLambdaConstructor::AddNKMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 153 of file G4ExcitedLambdaConstructor.cc.
Referenced by CreateDecayTable().
AddNKStarMode()
G4DecayTable * G4ExcitedLambdaConstructor::AddNKStarMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 196 of file G4ExcitedLambdaConstructor.cc.
Referenced by CreateDecayTable().
AddSigmaPiMode()
G4DecayTable * G4ExcitedLambdaConstructor::AddSigmaPiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 239 of file G4ExcitedLambdaConstructor.cc.
Referenced by CreateDecayTable().
AddSigmaStarPiMode()
G4DecayTable * G4ExcitedLambdaConstructor::AddSigmaStarPiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 295 of file G4ExcitedLambdaConstructor.cc.
Referenced by CreateDecayTable().
CreateDecayTable()
G4DecayTable * G4ExcitedLambdaConstructor::CreateDecayTable (const G4String & name, G4int iIso3, G4int iState, G4bool fAnti = false) protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 56 of file G4ExcitedLambdaConstructor.cc.
Exist()
virtual G4bool G4ExcitedLambdaConstructor::Exist (G4int) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 52 of file G4ExcitedLambdaConstructor.hh.
GetEncodingOffset()
G4int G4ExcitedLambdaConstructor::GetEncodingOffset (G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 129 of file G4ExcitedLambdaConstructor.hh.
GetiParity()
G4int G4ExcitedLambdaConstructor::GetiParity (G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 123 of file G4ExcitedLambdaConstructor.hh.
GetiSpin()
G4int G4ExcitedLambdaConstructor::GetiSpin (G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 117 of file G4ExcitedLambdaConstructor.hh.
GetMass()
G4double G4ExcitedLambdaConstructor::GetMass (G4int state, G4int iso) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 105 of file G4ExcitedLambdaConstructor.hh.
GetMultipletName()
G4String G4ExcitedLambdaConstructor::GetMultipletName (G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 152 of file G4ExcitedLambdaConstructor.hh.
GetName()
G4String G4ExcitedLambdaConstructor::GetName (G4int iIso3, G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 158 of file G4ExcitedLambdaConstructor.hh.
GetQuarkContents()
G4int G4ExcitedLambdaConstructor::GetQuarkContents (G4int iQ, G4int) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 135 of file G4ExcitedLambdaConstructor.hh.
GetWidth()
G4double G4ExcitedLambdaConstructor::GetWidth (G4int state, G4int iso) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 111 of file G4ExcitedLambdaConstructor.hh.
Field Documentation
bRatio
const G4double G4ExcitedLambdaConstructor::bRatio static private
Initial value:
=
{
   {   0.0,  0.0,  1.0,  0.0,  0.0,   0.0,   0.0},
   {  0.45,  0.0, 0.43, 0.11, 0.01,   0.0,   0.0},
   {  0.35,  0.0, 0.65,  0.0,  0.0,   0.0,   0.0},
   {  0.20,  0.0, 0.50,  0.0,  0.0,  0.30,   0.0},
   {  0.25,  0.0, 0.45, 0.30,  0.0,   0.0,   0.0},
   {  0.40, 0.20, 0.20, 0.20,  0.0,   0.0,   0.0},
   {  0.35, 0.45, 0.15, 0.05,  0.0,   0.0,   0.0},
   {  0.73,  0.0, 0.16, 0.11,  0.0,   0.0,   0.0},
   {  0.10,  0.0, 0.70, 0.20,  0.0,   0.0,   0.0},
   {  0.37, 0.21, 0.11, 0.31,  0.0,   0.0,   0.0},
   {  0.35, 0.20, 0.05, 0.30,  0.0,  0.02,  0.08},
   {  0.25, 0.45, 0.30,  0.0,  0.0,   0.0,   0.0}
}
Definition at line 101 of file G4ExcitedLambdaConstructor.hh.
Referenced by CreateDecayTable().
encodingOffset
const G4int G4ExcitedLambdaConstructor::encodingOffset static private
Initial value:
= {
  10000,     0, 20000, 30000, 10000,
  40000, 50000,     0, 10000, 20000,
      0, 20000
}
Definition at line 93 of file G4ExcitedLambdaConstructor.hh.
Referenced by GetEncodingOffset().
iParity
const G4int G4ExcitedLambdaConstructor::iParity static private
Initial value:
= {
  -1,  -1,   +1,  -1,  -1,
  -1,  +1,   +1,  -1,  +1,
  -1,  +1
}
Definition at line 92 of file G4ExcitedLambdaConstructor.hh.
Referenced by GetiParity().
iSpin
const G4int G4ExcitedLambdaConstructor::iSpin static private
Initial value:
= {
    1,   3,   1,   1,   3,
    1,   1,   5,   5,   3,
    7,   5
}
Definition at line 91 of file G4ExcitedLambdaConstructor.hh.
Referenced by GetiSpin().
mass
const G4double G4ExcitedLambdaConstructor::mass static private
Initial value:
= {
  1.4051*GeV,1.5195*GeV, 1.600*GeV, 1.670*GeV,  1.690*GeV,
   1.800*GeV, 1.810*GeV, 1.820*GeV, 1.830*GeV,  1.890*GeV,
   2.100*GeV, 2.110*GeV
}
Definition at line 89 of file G4ExcitedLambdaConstructor.hh.
Referenced by GetMass().
name
const char * G4ExcitedLambdaConstructor::name static private
Initial value:
= {
  "lambda(1405)","lambda(1520)","lambda(1600)","lambda(1670)","lambda(1690)",
  "lambda(1800)","lambda(1810)","lambda(1820)","lambda(1830)","lambda(1890)",
  "lambda(2100)","lambda(2110)"
}
Definition at line 88 of file G4ExcitedLambdaConstructor.hh.
Referenced by GetMultipletName(), and GetName().
width
const G4double G4ExcitedLambdaConstructor::width static private
Initial value:
= {
   50.5*MeV,  15.6*MeV, 150.0*MeV,  35.0*MeV,  60.0*MeV,
  300.0*MeV, 150.0*MeV,  80.0*MeV,  95.0*MeV, 100.0*MeV,
  200.0*MeV, 200.0*MeV
}
Definition at line 90 of file G4ExcitedLambdaConstructor.hh.
Referenced by GetWidth().
The documentation for this class was generated from the following files:
source/particles/shortlived/include/G4ExcitedLambdaConstructor.hh
source/particles/shortlived/src/G4ExcitedLambdaConstructor.cc