Geant4: G4ErrorMatrix Class Reference
G4ErrorMatrix Class Reference
#include <G4ErrorMatrix.hh>
Data Structures
class G4ErrorMatrix_row
class G4ErrorMatrix_row_const
Public Member Functions
G4ErrorMatrix ()
G4ErrorMatrix (G4int p, G4int q)
G4ErrorMatrix (G4int p, G4int q, G4int i)
G4ErrorMatrix (const G4ErrorMatrix &m1)
G4ErrorMatrix (const G4ErrorSymMatrix &m1)
virtual ~G4ErrorMatrix ()
virtual G4int num_row () const
virtual G4int num_col () const
virtual const G4double & operator() (G4int row, G4int col) const
virtual G4double & operator() (G4int row, G4int col)
G4ErrorMatrix & operator*= (G4double t)
G4ErrorMatrix & operator/= (G4double t)
G4ErrorMatrix & operator+= (const G4ErrorMatrix &m2)
G4ErrorMatrix & operator+= (const G4ErrorSymMatrix &m2)
G4ErrorMatrix & operator-= (const G4ErrorMatrix &m2)
G4ErrorMatrix & operator-= (const G4ErrorSymMatrix &m2)
G4ErrorMatrix & operator= (const G4ErrorMatrix &m2)
G4ErrorMatrix & operator= (const G4ErrorSymMatrix &m2)
G4ErrorMatrix operator- () const
G4ErrorMatrix apply (G4double(*f)(G4double, G4int, G4int)) const
G4ErrorMatrix T () const
G4ErrorMatrix sub (G4int min_row, G4int max_row, G4int min_col, G4int max_col) const
void sub (G4int row, G4int col, const G4ErrorMatrix &m1)
G4ErrorMatrix inverse (G4int &ierr) const
virtual void invert (G4int &ierr)
G4double determinant () const
G4double trace () const
G4ErrorMatrix_row operator[] (G4int)
const G4ErrorMatrix_row_const operator[] (G4int) const
Static Public Member Functions
static void error (const char *s)
Protected Member Functions
virtual G4int num_size () const
virtual void invertHaywood4 (G4int &ierr)
virtual void invertHaywood5 (G4int &ierr)
virtual void invertHaywood6 (G4int &ierr)
Private Member Functions
G4int dfact_matrix (G4double &det, G4int *ir)
G4int dfinv_matrix (G4int *ir)
Private Attributes
std::vector< G4double > m
G4int nrow
G4int ncol
G4int size
Friends
class G4ErrorMatrix_row
class G4ErrorMatrix_row_const
class G4ErrorSymMatrix
G4ErrorMatrix operator+ (const G4ErrorMatrix &m1, const G4ErrorMatrix &m2)
G4ErrorMatrix operator- (const G4ErrorMatrix &m1, const G4ErrorMatrix &m2)
G4ErrorMatrix operator* (const G4ErrorMatrix &m1, const G4ErrorMatrix &m2)
G4ErrorMatrix operator* (const G4ErrorMatrix &m1, const G4ErrorSymMatrix &m2)
G4ErrorMatrix operator* (const G4ErrorSymMatrix &m1, const G4ErrorMatrix &m2)
G4ErrorMatrix operator* (const G4ErrorSymMatrix &m1, const G4ErrorSymMatrix &m2)
G4ErrorMatrix qr_solve (G4ErrorMatrix *, const G4ErrorMatrix &b)
void tridiagonal (G4ErrorSymMatrix *a, G4ErrorMatrix *hsm)
void row_house (G4ErrorMatrix *, const G4ErrorMatrix &, G4double, G4int, G4int, G4int, G4int)
void back_solve (const G4ErrorMatrix &R, G4ErrorMatrix *b)
void col_givens (G4ErrorMatrix *A, G4double c, G4double s, G4int k1, G4int k2, G4int rowmin, G4int rowmax)
void row_givens (G4ErrorMatrix *A, G4double c, G4double s, G4int k1, G4int k2, G4int colmin, G4int colmax)
void col_house (G4ErrorMatrix *, const G4ErrorMatrix &, G4double, G4int, G4int, G4int, G4int)
void house_with_update (G4ErrorMatrix *a, G4int row, G4int col)
void house_with_update (G4ErrorMatrix *a, G4ErrorMatrix *v, G4int row, G4int col)
void house_with_update2 (G4ErrorSymMatrix *a, G4ErrorMatrix *v, G4int row, G4int col)
Detailed Description
Definition at line 46 of file G4ErrorMatrix.hh.
Constructor & Destructor Documentation
G4ErrorMatrix() [1/5]
G4ErrorMatrix::G4ErrorMatrix ()
G4ErrorMatrix() [2/5]
G4ErrorMatrix::G4ErrorMatrix (G4int p, G4int q)
Definition at line 73 of file G4ErrorMatrix.cc.
G4ErrorMatrix() [3/5]
G4ErrorMatrix::G4ErrorMatrix (G4int p, G4int q, G4int i)
Definition at line 79 of file G4ErrorMatrix.cc.
G4ErrorMatrix() [4/5]
G4ErrorMatrix::G4ErrorMatrix (const G4ErrorMatrix & m1)
Definition at line 116 of file G4ErrorMatrix.cc.
G4ErrorMatrix() [5/5]
G4ErrorMatrix::G4ErrorMatrix (const G4ErrorSymMatrix & m1)
Definition at line 122 of file G4ErrorMatrix.cc.
~G4ErrorMatrix()
G4ErrorMatrix::~G4ErrorMatrix () virtual
Definition at line 112 of file G4ErrorMatrix.cc.
Member Function Documentation
apply()
G4ErrorMatrix G4ErrorMatrix::apply (G4double(*)(G4double, G4int, G4int) f) const
Definition at line 389 of file G4ErrorMatrix.cc.
determinant()
G4double G4ErrorMatrix::determinant () const
Definition at line 775 of file G4ErrorMatrix.cc.
dfact_matrix()
G4int G4ErrorMatrix::dfact_matrix (G4double & det, G4int * ir) private
Definition at line 517 of file G4ErrorMatrix.cc.
Referenced by determinant(), G4ErrorSymMatrix::determinant(), and invert().
dfinv_matrix()
G4int G4ErrorMatrix::dfinv_matrix (G4int * ir) private
Definition at line 404 of file G4ErrorMatrix.cc.
Referenced by invert().
error()
void G4ErrorMatrix::error (const char * s) static
Definition at line 804 of file G4ErrorMatrix.cc.
Referenced by determinant(), dfact_matrix(), dfinv_matrix(), G4ErrorMatrix(), G4ErrorSymMatrix::G4ErrorSymMatrix(), invert(), sub(), and G4ErrorSymMatrix::sub().
inverse()
G4ErrorMatrix G4ErrorMatrix::inverse (G4int & ierr) const inline
invert()
void G4ErrorMatrix::invert (G4int & ierr) virtual
Definition at line 644 of file G4ErrorMatrix.cc.
invertHaywood4()
void G4ErrorMatrix::invertHaywood4 (G4int & ierr) protected virtual
Definition at line 910 of file G4ErrorMatrix.cc.
Referenced by invert().
invertHaywood5()
void G4ErrorMatrix::invertHaywood5 (G4int & ierr) protected virtual
Definition at line 1009 of file G4ErrorMatrix.cc.
Referenced by invert().
invertHaywood6()
void G4ErrorMatrix::invertHaywood6 (G4int & ierr) protected virtual
Definition at line 1232 of file G4ErrorMatrix.cc.
Referenced by invert().
num_col()
virtual G4int G4ErrorMatrix::num_col () const inline virtual
Referenced by apply(), dfinv_matrix(), dsum(), operator*(), operator+(), operator+=(), operator-(), operator-=(), operator<<(), G4ErrorSymMatrix::similarity(), G4ErrorSymMatrix::similarityT(), and sub().
num_row()
virtual G4int G4ErrorMatrix::num_row () const inline virtual
Referenced by apply(), dfinv_matrix(), dsum(), operator*(), operator+(), operator+=(), operator-(), operator-=(), operator<<(), operator=(), G4ErrorSymMatrix::similarity(), and sub().
num_size()
virtual G4int G4ErrorMatrix::num_size () const inline protected virtual
operator()() [1/2]
virtual G4double& G4ErrorMatrix::operator() (G4int row, G4int col) inline virtual
operator()() [2/2]
virtual const G4double& G4ErrorMatrix::operator() (G4int row, G4int col) const inline virtual
operator*=()
G4ErrorMatrix & G4ErrorMatrix::operator*= (G4double t)
Definition at line 325 of file G4ErrorMatrix.cc.
operator+=() [1/2]
G4ErrorMatrix & G4ErrorMatrix::operator+= (const G4ErrorMatrix & m2)
Definition at line 305 of file G4ErrorMatrix.cc.
operator+=() [2/2]
G4ErrorMatrix & G4ErrorMatrix::operator+= (const G4ErrorSymMatrix & m2)
Definition at line 401 of file G4ErrorSymMatrix.cc.
operator-()
G4ErrorMatrix G4ErrorMatrix::operator- () const
Definition at line 214 of file G4ErrorMatrix.cc.
operator-=() [1/2]
G4ErrorMatrix & G4ErrorMatrix::operator-= (const G4ErrorMatrix & m2)
Definition at line 312 of file G4ErrorMatrix.cc.
operator-=() [2/2]
G4ErrorMatrix & G4ErrorMatrix::operator-= (const G4ErrorSymMatrix & m2)
Definition at line 433 of file G4ErrorSymMatrix.cc.
operator/=()
G4ErrorMatrix & G4ErrorMatrix::operator/= (G4double t)
Definition at line 319 of file G4ErrorMatrix.cc.
operator=() [1/2]
G4ErrorMatrix & G4ErrorMatrix::operator= (const G4ErrorMatrix & m2)
Definition at line 331 of file G4ErrorMatrix.cc.
operator=() [2/2]
G4ErrorMatrix & G4ErrorMatrix::operator= (const G4ErrorSymMatrix & m2)
Definition at line 477 of file G4ErrorSymMatrix.cc.
operator[]() [1/2]
G4ErrorMatrix_row G4ErrorMatrix::operator[] (G4int) inline
operator[]() [2/2]
const G4ErrorMatrix_row_const G4ErrorMatrix::operator[] (G4int) const inline
sub() [1/2]
G4ErrorMatrix G4ErrorMatrix::sub (G4int min_row, G4int max_row, G4int min_col, G4int max_col) const
Definition at line 154 of file G4ErrorMatrix.cc.
Referenced by dsum().
sub() [2/2]
void G4ErrorMatrix::sub (G4int row, G4int col, const G4ErrorMatrix & m1)
Definition at line 176 of file G4ErrorMatrix.cc.
T()
G4ErrorMatrix G4ErrorMatrix::T () const
Definition at line 373 of file G4ErrorMatrix.cc.
Referenced by G4ErrorFreeTrajState::PropagateError().
trace()
G4double G4ErrorMatrix::trace () const
Definition at line 794 of file G4ErrorMatrix.cc.
Friends And Related Function Documentation
back_solve
void back_solve (const G4ErrorMatrix & R, G4ErrorMatrix * b) friend
col_givens
void col_givens (G4ErrorMatrix * A, G4double c, G4double s, G4int k1, G4int k2, G4int rowmin, G4int rowmax) friend
col_house
void col_house (G4ErrorMatrix * , const G4ErrorMatrix & , G4double , G4int , G4int , G4int , G4int) friend
G4ErrorMatrix_row
friend class G4ErrorMatrix_row friend
Definition at line 174 of file G4ErrorMatrix.hh.
G4ErrorMatrix_row_const
friend class G4ErrorMatrix_row_const friend
Definition at line 175 of file G4ErrorMatrix.hh.
G4ErrorSymMatrix
friend class G4ErrorSymMatrix friend
Definition at line 176 of file G4ErrorMatrix.hh.
house_with_update [1/2]
void house_with_update (G4ErrorMatrix * a, G4ErrorMatrix * v, G4int row, G4int col) friend
house_with_update [2/2]
void house_with_update (G4ErrorMatrix * a, G4int row, G4int col) friend
house_with_update2
void house_with_update2 (G4ErrorSymMatrix * a, G4ErrorMatrix * v, G4int row, G4int col) friend
operator* [1/4]
G4ErrorMatrix operator* (const G4ErrorMatrix & m1, const G4ErrorMatrix & m2) friend
Definition at line 271 of file G4ErrorMatrix.cc.
operator* [2/4]
G4ErrorMatrix operator* (const G4ErrorMatrix & m1, const G4ErrorSymMatrix & m2) friend
Definition at line 286 of file G4ErrorSymMatrix.cc.
operator* [3/4]
G4ErrorMatrix operator* (const G4ErrorSymMatrix & m1, const G4ErrorMatrix & m2) friend
Definition at line 320 of file G4ErrorSymMatrix.cc.
operator* [4/4]
G4ErrorMatrix operator* (const G4ErrorSymMatrix & m1, const G4ErrorSymMatrix & m2) friend
Definition at line 353 of file G4ErrorSymMatrix.cc.
operator+
G4ErrorMatrix operator+ (const G4ErrorMatrix & m1, const G4ErrorMatrix & m2) friend
Definition at line 224 of file G4ErrorMatrix.cc.
operator-
G4ErrorMatrix operator- (const G4ErrorMatrix & m1, const G4ErrorMatrix & m2) friend
Definition at line 236 of file G4ErrorMatrix.cc.
qr_solve
G4ErrorMatrix qr_solve (G4ErrorMatrix * , const G4ErrorMatrix & b) friend
row_givens
void row_givens (G4ErrorMatrix * A, G4double c, G4double s, G4int k1, G4int k2, G4int colmin, G4int colmax) friend
row_house
void row_house (G4ErrorMatrix * , const G4ErrorMatrix & , G4double , G4int , G4int , G4int , G4int) friend
tridiagonal
void tridiagonal (G4ErrorSymMatrix * a, G4ErrorMatrix * hsm) friend
Field Documentation
m
std::vector<G4double > G4ErrorMatrix::m private
Definition at line 224 of file G4ErrorMatrix.hh.
Referenced by apply(), G4ErrorSymMatrix::assign(), dfact_matrix(), dfinv_matrix(), G4ErrorMatrix(), invert(), invertHaywood4(), invertHaywood5(), invertHaywood6(), operator*(), operator+=(), operator-(), operator-=(), operator=(), G4ErrorSymMatrix::similarity(), sub(), T(), and trace().
ncol
G4int G4ErrorMatrix::ncol private
Definition at line 226 of file G4ErrorMatrix.hh.
Referenced by determinant(), dfact_matrix(), G4ErrorMatrix(), invert(), operator*(), operator+(), operator-(), operator=(), T(), and trace().
nrow
G4int G4ErrorMatrix::nrow private
Definition at line 226 of file G4ErrorMatrix.hh.
Referenced by G4ErrorSymMatrix::assign(), determinant(), dfact_matrix(), G4ErrorMatrix(), invert(), operator*(), operator+(), operator-(), operator=(), and T().
size
G4int G4ErrorMatrix::size private
Definition at line 227 of file G4ErrorMatrix.hh.
Referenced by G4ErrorMatrix(), operator=(), and T().
The documentation for this class was generated from the following files:
source/error_propagation/include/G4ErrorMatrix.hh
source/error_propagation/src/G4ErrorMatrix.cc
source/error_propagation/src/G4ErrorSymMatrix.cc