Geant4: G4tgrPlace Class Reference
G4tgrPlace Class Reference
#include <G4tgrPlace.hh>
Public Member Functions
G4tgrPlace ()
virtual ~G4tgrPlace ()
const G4String & GetParentName () const
G4tgrVolume * GetVolume () const
unsigned int GetCopyNo () const
const G4String & GetType () const
void SetVolume (G4tgrVolume *vol)
void SetType (const G4String &typ)
virtual G4ThreeVector GetPlacement () const
Protected Attributes
G4tgrVolume * theVolume
G4String theParentName
unsigned int theCopyNo
G4String theType
Detailed Description
Definition at line 48 of file G4tgrPlace.hh.
Constructor & Destructor Documentation
G4tgrPlace()
G4tgrPlace::G4tgrPlace ()
Definition at line 38 of file G4tgrPlace.cc.
~G4tgrPlace()
G4tgrPlace::~G4tgrPlace () virtual
Definition at line 45 of file G4tgrPlace.cc.
Member Function Documentation
GetCopyNo()
unsigned int G4tgrPlace::GetCopyNo () const inline
Definition at line 59 of file G4tgrPlace.hh.
Referenced by G4tgrVolume::AddPlace(), G4tgbVolume::ConstructG4PhysVol(), G4tgbVolume::ConstructG4Volumes(), and G4tgrVolumeMgr::DumpVolumeLeaf().
GetParentName()
const G4String& G4tgrPlace::GetParentName () const inline
Definition at line 57 of file G4tgrPlace.hh.
Referenced by G4tgrVolumeAssembly::AddPlace(), G4tgrVolume::AddPlace(), G4tgrVolume::AddPlaceParam(), and G4tgrVolume::AddPlaceReplica().
GetPlacement()
G4ThreeVector G4tgrPlace::GetPlacement () const virtual
Reimplemented in G4tgrPlaceSimple.
Definition at line 51 of file G4tgrPlace.cc.
Referenced by G4tgbVolume::ConstructG4PhysVol().
GetType()
const G4String& G4tgrPlace::GetType () const inline
Definition at line 60 of file G4tgrPlace.hh.
Referenced by G4tgrVolumeAssembly::AddPlace(), G4tgrVolume::AddPlace(), G4tgbPlaceParameterisation::CheckNExtraData(), and G4tgbVolume::ConstructG4PhysVol().
GetVolume()
G4tgrVolume* G4tgrPlace::GetVolume () const inline
Definition at line 58 of file G4tgrPlace.hh.
Referenced by G4tgbVolume::ConstructG4Volumes(), and G4tgrVolumeMgr::DumpVolumeLeaf().
SetType()
void G4tgrPlace::SetType (const G4String & typ) inline
Definition at line 62 of file G4tgrPlace.hh.
Referenced by G4tgrVolume::AddPlaceReplica(), and G4tgrVolumeDivision::G4tgrVolumeDivision().
SetVolume()
void G4tgrPlace::SetVolume (G4tgrVolume * vol) inline
Definition at line 61 of file G4tgrPlace.hh.
Referenced by G4tgrVolumeAssembly::AddPlace(), G4tgrVolume::AddPlace(), G4tgrVolume::AddPlaceParam(), G4tgrVolume::AddPlaceReplica(), and G4tgrVolumeDivision::G4tgrVolumeDivision().
Field Documentation
theCopyNo
unsigned int G4tgrPlace::theCopyNo protected
Definition at line 75 of file G4tgrPlace.hh.
Referenced by G4tgrPlaceParameterisation::G4tgrPlaceParameterisation(), G4tgrPlaceSimple::G4tgrPlaceSimple(), and GetCopyNo().
theParentName
G4String G4tgrPlace::theParentName protected
Definition at line 71 of file G4tgrPlace.hh.
Referenced by G4tgrPlaceDivRep::G4tgrPlaceDivRep(), G4tgrPlaceParameterisation::G4tgrPlaceParameterisation(), G4tgrPlaceSimple::G4tgrPlaceSimple(), GetParentName(), operator<<(), and G4tgrPlaceDivRep::SetParentName().
theType
G4String G4tgrPlace::theType protected
Definition at line 78 of file G4tgrPlace.hh.
Referenced by G4tgrPlaceParameterisation::G4tgrPlaceParameterisation(), G4tgrPlaceSimple::G4tgrPlaceSimple(), GetType(), and SetType().
theVolume
G4tgrVolume* G4tgrPlace::theVolume protected
Definition at line 68 of file G4tgrPlace.hh.
Referenced by GetVolume(), and SetVolume().
The documentation for this class was generated from the following files:
source/persistency/ascii/include/G4tgrPlace.hh
source/persistency/ascii/src/G4tgrPlace.cc