Geant4: examples/advanced/ChargeExchangeMC/src/CexmcException.cc File Reference
CexmcException.cc File Reference
#include "CexmcException.hh"
#include "CexmcRunManager.hh"
#include "CexmcCommon.hh"
Functions
void ThrowExceptionIfProjectIsRead (CexmcExceptionType type, G4bool extraCond)
Function Documentation
ThrowExceptionIfProjectIsRead()
void ThrowExceptionIfProjectIsRead (CexmcExceptionType type, G4bool extraCond)
Definition at line 179 of file CexmcException.cc.
Referenced by CexmcEnergyDepositDigitizer::AddCrystalResolutionRange(), CexmcProductionModel::ApplyFermiMotion(), CexmcEnergyDepositDigitizer::ApplyFiniteCrystalResolution(), CexmcEnergyDepositDigitizer::ClearCrystalResolutionData(), CexmcParticleGun::SetBeamParticle(), CexmcEnergyDepositDigitizer::SetCalorimeterLeftThreshold(), CexmcEnergyDepositDigitizer::SetCalorimeterRightThreshold(), CexmcEnergyDepositDigitizer::SetCalorimetersThreshold(), CexmcEnergyDepositDigitizer::SetCalorimeterTriggerAlgorithm(), CexmcPrimaryGeneratorAction::SetFwhmDirX(), CexmcPrimaryGeneratorAction::SetFwhmDirY(), CexmcPrimaryGeneratorAction::SetFwhmMomentumAmp(), CexmcPrimaryGeneratorAction::SetFwhmPosX(), CexmcPrimaryGeneratorAction::SetFwhmPosY(), CexmcEnergyDepositDigitizer::SetMonitorThreshold(), CexmcParticleGun::SetOrigDirection(), CexmcParticleGun::SetOrigMomentumAmp(), CexmcParticleGun::SetOrigPosition(), CexmcEnergyDepositDigitizer::SetOuterCrystalsVetoAlgorithm(), CexmcEnergyDepositDigitizer::SetOuterCrystalsVetoFraction(), CexmcEnergyDepositDigitizer::SetVetoCounterLeftThreshold(), CexmcEnergyDepositDigitizer::SetVetoCounterRightThreshold(), and CexmcEnergyDepositDigitizer::SetVetoCountersThreshold().