Geant4: G4PionPlus Class Reference
G4PionPlus Class Reference
#include <G4PionPlus.hh>
Static Public Member Functions
static G4PionPlus * Definition ()
static G4PionPlus * PionPlusDefinition ()
static G4PionPlus * PionPlus ()
Static Public Member Functions inherited from G4ParticleDefinition
static const G4PDefManager & GetSubInstanceManager ()
static void Clean ()
Private Member Functions
G4PionPlus ()
~G4PionPlus ()
Static Private Attributes
static G4PionPlus * theInstance = 0
Additional Inherited Members
Public Member Functions inherited from G4ParticleDefinition
G4ParticleDefinition (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospinZ, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable, G4bool shortlived=false, const G4String &subType="", G4int anti_encoding=0, G4double magneticMoment=0.0)
virtual ~G4ParticleDefinition ()
const G4String & GetParticleName () const
G4double GetPDGMass () const
G4double GetPDGWidth () const
G4double GetPDGCharge () const
G4double GetPDGSpin () const
G4int GetPDGiSpin () const
G4int GetPDGiParity () const
G4int GetPDGiConjugation () const
G4double GetPDGIsospin () const
G4double GetPDGIsospin3 () const
G4int GetPDGiIsospin () const
G4int GetPDGiIsospin3 () const
G4int GetPDGiGParity () const
G4double GetPDGMagneticMoment () const
void SetPDGMagneticMoment (G4double mageticMoment)
G4double CalculateAnomaly () const
const G4String & GetParticleType () const
const G4String & GetParticleSubType () const
G4int GetLeptonNumber () const
G4int GetBaryonNumber () const
G4int GetPDGEncoding () const
G4int GetAntiPDGEncoding () const
void SetAntiPDGEncoding (G4int aEncoding)
G4int GetQuarkContent (G4int flavor) const
G4int GetAntiQuarkContent (G4int flavor) const
G4bool IsShortLived () const
G4bool GetPDGStable () const
void SetPDGStable (const G4bool aFlag)
G4double GetPDGLifeTime () const
void SetPDGLifeTime (G4double aLifeTime)
G4double GetIonLifeTime () const
G4DecayTable * GetDecayTable () const
void SetDecayTable (G4DecayTable *aDecayTable)
G4ProcessManager * GetProcessManager () const
void SetProcessManager (G4ProcessManager *aProcessManager)
G4ParticleTable * GetParticleTable () const
G4int GetAtomicNumber () const
G4int GetAtomicMass () const
void DumpTable () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetApplyCutsFlag (G4bool)
G4bool GetApplyCutsFlag () const
G4bool IsGeneralIon () const
G4bool IsMuonicAtom () const
G4bool operator== (const G4ParticleDefinition &right) const
G4bool operator!= (const G4ParticleDefinition &right) const
G4ProcessManager * GetMasterProcessManager () const
void SetMasterProcessManager (G4ProcessManager *aNewPM)
G4int GetInstanceID () const
void SetParticleDefinitionID (G4int id=-1)
G4int GetParticleDefinitionID () const
Protected Types inherited from G4ParticleDefinition
enum { NumberOfQuarkFlavor = 6 }
Protected Member Functions inherited from G4ParticleDefinition
G4int FillQuarkContents ()
void SetParticleSubType (const G4String &subtype)
void SetAtomicNumber (G4int)
void SetAtomicMass (G4int)
G4ParticleDefinition (const G4ParticleDefinition &right)
G4ParticleDefinition ()
Protected Attributes inherited from G4ParticleDefinition
G4int theQuarkContent [NumberOfQuarkFlavor]
G4int theAntiQuarkContent [NumberOfQuarkFlavor]
G4bool isGeneralIon
G4bool isMuonicAtom
Detailed Description
Definition at line 49 of file G4PionPlus.hh.
Constructor & Destructor Documentation
G4PionPlus()
G4PionPlus::G4PionPlus () inline private
Definition at line 53 of file G4PionPlus.hh.
~G4PionPlus()
G4PionPlus::~G4PionPlus () inline private
Definition at line 54 of file G4PionPlus.hh.
Member Function Documentation
Definition()
G4PionPlus * G4PionPlus::Definition () static
Definition at line 51 of file G4PionPlus.cc.
Referenced by G4BertiniPiKBuilder::Build(), G4BinaryPiKBuilder::Build(), G4BinaryPionBuilder::Build(), G4BertiniPionBuilder::Build(), G4INCLXXPionBuilder::Build(), G4FTFBinaryPionBuilder::Build(), G4FTFPPionBuilder::Build(), G4QGSBinaryPionBuilder::Build(), G4FTFBinaryPiKBuilder::Build(), G4QGSPPionBuilder::Build(), G4FTFPPiKBuilder::Build(), G4QGSPPiKBuilder::Build(), G4QGSBinaryPiKBuilder::Build(), G4InuclElementaryParticle::makeDefinition(), PionPlus(), PionPlusDefinition(), G4ChipsPionPlusInelasticXS::ThresholdMomentum(), and G4InuclElementaryParticle::type().
PionPlus()
G4PionPlus * G4PionPlus::PionPlus () static
Definition at line 97 of file G4PionPlus.cc.
Referenced by HistoManager::AddLeakingParticle(), HistoManager::AddTargetStep(), G4PionBuilder::Build(), G4PiKBuilder::Build(), G4PiNuclearCrossSection::BuildPhysicsTable(), G4BGGPionElasticXS::BuildPhysicsTable(), G4BGGPionInelasticXS::BuildPhysicsTable(), G4RPGKMinusInelastic::Cascade(), G4RPGSigmaPlusInelastic::Cascade(), G4RPGXiMinusInelastic::Cascade(), G4RPGAntiLambdaInelastic::Cascade(), G4RPGAntiProtonInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGOmegaMinusInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4RPGAntiOmegaMinusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGLambdaInelastic::Cascade(), G4RPGSigmaMinusInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGKPlusInelastic::Cascade(), G4RPGKZeroInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), G4RPGAntiKZeroInelastic::Cascade(), G4SpinDecayPhysics::ConstructParticle(), F04PhysicsList::ConstructProcess(), G4SpinDecayPhysics::ConstructProcess(), WLSPhysicsList::ConstructProcess(), G4HadronPhysicsFTFQGSP_BERT::ConstructProcess(), G4HadronicProcessStore::DumpHtml(), G4VScatteringCollision::FinalState(), G4BGGPionElasticXS::G4BGGPionElasticXS(), G4BGGPionInelasticXS::G4BGGPionInelasticXS(), G4ChargeExchange::G4ChargeExchange(), G4ChargeExchangeProcess::G4ChargeExchangeProcess(), G4ChipsKaonPlusInelasticXS::G4ChipsKaonPlusInelasticXS(), G4ComponentGGHadronNucleusXsc::G4ComponentGGHadronNucleusXsc(), G4DiffuseElastic::G4DiffuseElastic(), G4eeTo3PiModel::G4eeTo3PiModel(), G4eeToTwoPiModel::G4eeToTwoPiModel(), G4HadronNucleonXsc::G4HadronNucleonXsc(), G4hhElastic::G4hhElastic(), G4NuclNuclDiffuseElastic::G4NuclNuclDiffuseElastic(), G4RPGInelastic::G4RPGInelastic(), G4UPiNuclearCrossSection::G4UPiNuclearCrossSection(), G4PionPlusField::GetField(), G4ChipsPionPlusElasticXS::GetQ2max(), G4RKPropagation::Init(), G4FTFParameters::InitForInteraction(), G4hhElastic::Initialise(), G4eeCrossSections::Initialise(), G4DiffuseElasticV2::IsApplicable(), G4DiffuseElastic::IsApplicable(), G4hhElastic::IsApplicable(), G4LMsdGenerator::IsApplicable(), G4RPGPionSuppression::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4RPGReaction::Rotate(), G4hhElastic::SampleBisectionalT(), G4hhElastic::SampleInvariantT(), G4LMsdGenerator::SampleMx(), G4VScatteringCollision::SampleResonanceMass(), G4eeToTwoPiModel::SampleSecondaries(), G4eeTo3PiModel::SampleSecondaries(), G4RPGInelastic::SetUpPions(), G4ChipsPionPlusInelasticXS::ThresholdMomentum(), G4AblaInterface::toG4ParticleDefinition(), G4INCLXXInterface::toG4ParticleDefinition(), G4INCLXXInterface::toINCLParticleType(), and G4Absorber::WillBeAbsorbed().
PionPlusDefinition()
G4PionPlus * G4PionPlus::PionPlusDefinition () static
Definition at line 92 of file G4PionPlus.cc.
Referenced by G4MesonAbsorption::AbsorptionCrossSection(), G4BinaryCascade::ApplyYourself(), F04StackingAction::ClassifyNewTrack(), G4MesonConstructor::ConstructLightMesons(), ExN02PhysicsList::ConstructMesons(), G4AdjointPhysicsList::ConstructMesons(), GammaKnifeParticles::ConstructParticle(), G4EmLivermorePolarizedPhysics::ConstructParticle(), G4EmLowEPPhysics::ConstructParticle(), G4EmPenelopePhysics::ConstructParticle(), G4EmLivermorePhysics::ConstructParticle(), PhysicsList::ConstructParticle(), G4ErrorPhysicsList::ConstructParticle(), PhysListEm5DStandard::ConstructParticle(), G4EmStandardPhysicsSS::ConstructParticle(), PhysListEm19DStandard::ConstructParticle(), G4EmStandardPhysics::ConstructParticle(), G4EmStandardPhysics_option3::ConstructParticle(), G4EmStandardPhysicsGS::ConstructParticle(), G4EmStandardPhysics_option4_channeling::ConstructParticle(), G4EmStandardPhysics_option4::ConstructParticle(), G4EmStandardPhysicsWVI::ConstructParticle(), G4EmStandardPhysics_option1::ConstructParticle(), G4EmStandardPhysics_option2::ConstructParticle(), GammaRayTelHadronPhysics::ConstructProcess(), G4XMesonBaryonElastic::CrossSection(), G4QGSParticipants::DeterminePartonMomenta(), G4CollisionMesonBaryonToResonance::G4CollisionMesonBaryonToResonance(), G4ParticleTypeConverter::G4ParticleTypeConverter(), G4XPDGElastic::G4XPDGElastic(), G4XPDGTotal::G4XPDGTotal(), G4MesonAbsorption::GetTimeToAbsorption(), Par01PiModel::IsApplicable(), Par01PionShowerModel::IsApplicable(), G4ResonanceNames::MinMass(), and F04TrackingAction::PostUserTrackingAction().
Field Documentation
theInstance
G4PionPlus * G4PionPlus::theInstance = 0 static private
Definition at line 52 of file G4PionPlus.hh.
Referenced by Definition().
The documentation for this class was generated from the following files:
source/particles/hadrons/mesons/include/G4PionPlus.hh
source/particles/hadrons/mesons/src/G4PionPlus.cc