Geant4: G4RegularNavigation Class Reference
G4RegularNavigation Class Reference
#include <G4RegularNavigation.hh>
Public Member Functions
G4RegularNavigation ()
~G4RegularNavigation ()
G4bool LevelLocate (G4NavigationHistory &history, const G4VPhysicalVolume *blockedVol, const G4int blockedNum, const G4ThreeVector &globalPoint, const G4ThreeVector *globalDirection, const G4bool pLocatedOnEdge, G4ThreeVector &localPoint)
G4double ComputeStep (const G4ThreeVector &globalPoint, const G4ThreeVector &globalDirection, const G4double currentProposedStepLength, G4double &newSafety, G4NavigationHistory &history, G4bool &validExitNormal, G4ThreeVector &exitNormal, G4bool &exiting, G4bool &entering, G4VPhysicalVolume *(*pBlockedPhysical), G4int &blockedReplicaNo)
G4double ComputeStepSkippingEqualMaterials (G4ThreeVector &localPoint, const G4ThreeVector &globalDirection, const G4double currentProposedStepLength, G4double &newSafety, G4NavigationHistory &history, G4bool &validExitNormal, G4ThreeVector &exitNormal, G4bool &exiting, G4bool &entering, G4VPhysicalVolume *(*pBlockedPhysical), G4int &blockedReplicaNo, G4VPhysicalVolume *pCurrentPhysical)
G4double ComputeSafety (const G4ThreeVector &localPoint, const G4NavigationHistory &history, const G4double pProposedMaxLength=DBL_MAX)
void SetVerboseLevel (G4int level)
void CheckMode (G4bool mode)
void SetNormalNavigation (G4NormalNavigation *fnormnav)
Private Attributes
G4int fverbose
G4bool fcheck
G4NormalNavigation * fnormalNav
G4double kCarTolerance
Detailed Description
Definition at line 53 of file G4RegularNavigation.hh.
Constructor & Destructor Documentation
G4RegularNavigation()
G4RegularNavigation::G4RegularNavigation ()
Definition at line 45 of file G4RegularNavigation.cc.
~G4RegularNavigation()
G4RegularNavigation::~G4RegularNavigation ()
Definition at line 53 of file G4RegularNavigation.cc.
Member Function Documentation
CheckMode()
void G4RegularNavigation::CheckMode (G4bool mode) inline
Definition at line 117 of file G4RegularNavigation.hh.
ComputeSafety()
G4double G4RegularNavigation::ComputeSafety (const G4ThreeVector & localPoint, const G4NavigationHistory & history, const G4double pProposedMaxLength = DBL_MAX)
Definition at line 265 of file G4RegularNavigation.cc.
Referenced by G4Navigator::ComputeSafety(), G4ITNavigator1::ComputeSafety(), and G4ITNavigator2::ComputeSafety().
ComputeStep()
G4double G4RegularNavigation::ComputeStep (const G4ThreeVector & globalPoint, const G4ThreeVector & globalDirection, const G4double currentProposedStepLength, G4double & newSafety, G4NavigationHistory & history, G4bool & validExitNormal, G4ThreeVector & exitNormal, G4bool & exiting, G4bool & entering, G4VPhysicalVolume ** pBlockedPhysical, G4int & blockedReplicaNo)
Definition at line 60 of file G4RegularNavigation.cc.
Referenced by G4Navigator::ComputeStep(), G4ITNavigator1::ComputeStep(), and G4ITNavigator2::ComputeStep().
ComputeStepSkippingEqualMaterials()
G4double G4RegularNavigation::ComputeStepSkippingEqualMaterials (G4ThreeVector & localPoint, const G4ThreeVector & globalDirection, const G4double currentProposedStepLength, G4double & newSafety, G4NavigationHistory & history, G4bool & validExitNormal, G4ThreeVector & exitNormal, G4bool & exiting, G4bool & entering, G4VPhysicalVolume ** pBlockedPhysical, G4int & blockedReplicaNo, G4VPhysicalVolume * pCurrentPhysical)
Definition at line 122 of file G4RegularNavigation.cc.
LevelLocate()
G4bool G4RegularNavigation::LevelLocate (G4NavigationHistory & history, const G4VPhysicalVolume * blockedVol, const G4int blockedNum, const G4ThreeVector & globalPoint, const G4ThreeVector * globalDirection, const G4bool pLocatedOnEdge, G4ThreeVector & localPoint)
Definition at line 285 of file G4RegularNavigation.cc.
Referenced by ComputeStep(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), and G4ITNavigator2::LocateGlobalPointAndSetup().
SetNormalNavigation()
void G4RegularNavigation::SetNormalNavigation (G4NormalNavigation * fnormnav) inline
Definition at line 118 of file G4RegularNavigation.hh.
Referenced by G4ITNavigator1::G4ITNavigator1(), G4ITNavigator2::G4ITNavigator2(), and G4Navigator::G4Navigator().
SetVerboseLevel()
void G4RegularNavigation::SetVerboseLevel (G4int level) inline
Definition at line 116 of file G4RegularNavigation.hh.
Field Documentation
fcheck
G4bool G4RegularNavigation::fcheck private
Definition at line 124 of file G4RegularNavigation.hh.
Referenced by CheckMode().
fnormalNav
G4NormalNavigation* G4RegularNavigation::fnormalNav private
Definition at line 126 of file G4RegularNavigation.hh.
Referenced by ComputeSafety(), ComputeStep(), ComputeStepSkippingEqualMaterials(), and SetNormalNavigation().
fverbose
G4int G4RegularNavigation::fverbose private
Definition at line 123 of file G4RegularNavigation.hh.
Referenced by SetVerboseLevel().
kCarTolerance
G4double G4RegularNavigation::kCarTolerance private
Definition at line 127 of file G4RegularNavigation.hh.
Referenced by ComputeStepSkippingEqualMaterials(), and G4RegularNavigation().
The documentation for this class was generated from the following files:
source/geometry/navigation/include/G4RegularNavigation.hh
source/geometry/navigation/src/G4RegularNavigation.cc