Geant4: G4PhononPolarization Namespace Reference
G4PhononPolarization Namespace Reference
Enumerations
enum { Long =0, TransSlow =1, TransFast =2, UNKNOWN =-1 }
Functions
G4int Get (const G4ParticleDefinition *aPD)
G4ParticleDefinition * Get (G4int pol)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
Long
TransSlow
TransFast
UNKNOWN
Definition at line 39 of file G4PhononPolarization.hh.
Function Documentation
Get() [1/2]
G4int G4PhononPolarization::Get (const G4ParticleDefinition * aPD)
Definition at line 38 of file G4PhononPolarization.cc.
Referenced by XPhononStackingAction::ClassifyNewTrack(), G4VPhononProcess::CreateSecondary(), and G4VPhononProcess::GetPolarization().
Get() [2/2]
G4ParticleDefinition * G4PhononPolarization::Get (G4int pol)
Definition at line 45 of file G4PhononPolarization.cc.