Geant4: pyMedicalBeam Namespace Reference
pyMedicalBeam Namespace Reference
Functions
MedicalBeam * Construct ()
void SetParticleByName (MedicalBeam *beam, const std::string &pname)
std::string GetParticleByName (MedicalBeam *beam)
void f_SetFieldXY (MedicalBeam *beam, const list &listXY)
list f_GetFieldXY (MedicalBeam *beam)
Function Documentation
Construct()
MedicalBeam* pyMedicalBeam::Construct ()
Definition at line 48 of file pyMedicalBeam.cc.
Referenced by BOOST_PYTHON_MODULE().
f_GetFieldXY()
list pyMedicalBeam::f_GetFieldXY (MedicalBeam * beam)
Definition at line 94 of file pyMedicalBeam.cc.
Referenced by BOOST_PYTHON_MODULE().
f_SetFieldXY()
void pyMedicalBeam::f_SetFieldXY (MedicalBeam * beam, const list & listXY)
Definition at line 84 of file pyMedicalBeam.cc.
Referenced by BOOST_PYTHON_MODULE().
GetParticleByName()
std::string pyMedicalBeam::GetParticleByName (MedicalBeam * beam)
Definition at line 74 of file pyMedicalBeam.cc.
Referenced by BOOST_PYTHON_MODULE().
SetParticleByName()
void pyMedicalBeam::SetParticleByName (MedicalBeam * beam, const std::string & pname)
Definition at line 60 of file pyMedicalBeam.cc.
Referenced by BOOST_PYTHON_MODULE().