Geant4: G4MCCIndexConversionTable Class Reference
G4MCCIndexConversionTable Class Reference
#include <G4MCCIndexConversionTable.hh>
Public Member Functions
G4MCCIndexConversionTable ()
virtual ~G4MCCIndexConversionTable ()
void Reset (size_t size)
G4bool IsUsed (size_t index) const
void SetNewIndex (size_t index, size_t new_value)
G4int GetIndex (size_t index) const
size_t size () const
Protected Types
typedef std::vector< G4int > G4IntVector
Protected Attributes
G4IntVector vecNewIndex
Detailed Description
Definition at line 53 of file G4MCCIndexConversionTable.hh.
Member Typedef Documentation
G4IntVector
typedef std::vector<G4int> G4MCCIndexConversionTable::G4IntVector protected
Definition at line 81 of file G4MCCIndexConversionTable.hh.
Constructor & Destructor Documentation
G4MCCIndexConversionTable()
G4MCCIndexConversionTable::G4MCCIndexConversionTable ()
Definition at line 40 of file G4MCCIndexConversionTable.cc.
~G4MCCIndexConversionTable()
G4MCCIndexConversionTable::~G4MCCIndexConversionTable () virtual
Definition at line 45 of file G4MCCIndexConversionTable.cc.
Member Function Documentation
GetIndex()
G4int G4MCCIndexConversionTable::GetIndex (size_t index) const inline
Definition at line 105 of file G4MCCIndexConversionTable.hh.
Referenced by G4ProductionCutsTable::RetrieveCutsInfo(), and G4PhysicsTableHelper::RetrievePhysicsTable().
IsUsed()
G4bool G4MCCIndexConversionTable::IsUsed (size_t index) const inline
Definition at line 86 of file G4MCCIndexConversionTable.hh.
Referenced by G4ProductionCutsTable::RetrieveCutsInfo(), and G4PhysicsTableHelper::RetrievePhysicsTable().
Reset()
void G4MCCIndexConversionTable::Reset (size_t size)
Definition at line 50 of file G4MCCIndexConversionTable.cc.
Referenced by G4ProductionCutsTable::CheckMaterialCutsCoupleInfo().
SetNewIndex()
void G4MCCIndexConversionTable::SetNewIndex (size_t index, size_t new_value) inline
Definition at line 96 of file G4MCCIndexConversionTable.hh.
Referenced by G4ProductionCutsTable::CheckMaterialCutsCoupleInfo().
size()
size_t G4MCCIndexConversionTable::size () const inline
Definition at line 114 of file G4MCCIndexConversionTable.hh.
Referenced by G4ProductionCutsTable::RetrieveCutsInfo(), and G4PhysicsTableHelper::RetrievePhysicsTable().
Field Documentation
vecNewIndex
G4IntVector G4MCCIndexConversionTable::vecNewIndex protected
Definition at line 82 of file G4MCCIndexConversionTable.hh.
Referenced by GetIndex(), IsUsed(), Reset(), SetNewIndex(), size(), and ~G4MCCIndexConversionTable().
The documentation for this class was generated from the following files:
source/processes/cuts/include/G4MCCIndexConversionTable.hh
source/processes/cuts/src/G4MCCIndexConversionTable.cc