Geant4: G4HadronicException Class Reference
G4HadronicException Class Reference
#include <G4HadronicException.hh>
Public Member Functions
G4HadronicException (G4String in, G4int at, G4String mess)
virtual ~G4HadronicException () throw ()
void Report (std::ostream &aS)
Private Attributes
G4String theMessage
G4String theName
G4int theLine
Detailed Description
Definition at line 33 of file G4HadronicException.hh.
Constructor & Destructor Documentation
G4HadronicException()
G4HadronicException::G4HadronicException (G4String in, G4int at, G4String mess) inline
Definition at line 36 of file G4HadronicException.hh.
~G4HadronicException()
virtual G4HadronicException::~G4HadronicException () throw () inline virtual
Definition at line 51 of file G4HadronicException.hh.
Member Function Documentation
Report()
void G4HadronicException::Report (std::ostream & aS) inline
Definition at line 53 of file G4HadronicException.hh.
Referenced by G4HadronicProcess::BuildPhysicsTable(), G4HadronicException(), G4NeutrinoElectronProcess::GetMeanFreePath(), G4HadronicProcess::GetMeanFreePath(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4HadronicProcess::PostStepDoIt(), G4HadronicProcess::RegisterMe(), and G4HadReentrentException::Report().
Field Documentation
theLine
G4int G4HadronicException::theLine private
Definition at line 62 of file G4HadronicException.hh.
Referenced by G4HadronicException(), and Report().
theMessage
G4String G4HadronicException::theMessage private
Definition at line 60 of file G4HadronicException.hh.
Referenced by G4HadronicException(), and Report().
theName
G4String G4HadronicException::theName private
Definition at line 61 of file G4HadronicException.hh.
Referenced by G4HadronicException(), and Report().
The documentation for this class was generated from the following file:
source/processes/hadronic/util/include/G4HadronicException.hh