Geant4: G4UIparameter Class Reference
G4UIparameter Class Reference
#include <G4UIparameter.hh>
Public Member Functions
G4UIparameter ()
G4UIparameter (char theType)
G4UIparameter (const char *theName, char theType, G4bool theOmittable)
~G4UIparameter ()
G4bool operator== (const G4UIparameter &right) const
G4bool operator!= (const G4UIparameter &right) const
G4int CheckNewValue (const char *newValue)
void List ()
void SetDefaultValue (const char *theDefaultValue)
void SetDefaultValue (G4int theDefaultValue)
void SetDefaultValue (G4double theDefaultValue)
void SetDefaultUnit (const char *theDefaultUnit)
G4String GetDefaultValue () const
char GetParameterType () const
void SetParameterRange (const char *theRange)
G4String GetParameterRange () const
void SetParameterName (const char *theName)
G4String GetParameterName () const
void SetParameterCandidates (const char *theString)
G4String GetParameterCandidates () const
void SetOmittable (G4bool om)
G4bool IsOmittable () const
void SetCurrentAsDefault (G4bool val)
G4bool GetCurrentAsDefault () const
void SetWidget (G4int theWidget)
const G4String GetParameterGuidance () const
void SetGuidance (const char *theGuidance)
Private Member Functions
G4int TypeCheck (const char *newValue)
G4int RangeCheck (const char *newValue)
G4int CandidateCheck (const char *newValue)
G4int IsInt (const char *str, short maxDigit)
G4int IsDouble (const char *str)
G4int ExpectExponent (const char *str)
yystype Expression (void)
yystype LogicalORExpression (void)
yystype LogicalANDExpression (void)
yystype EqualityExpression (void)
yystype RelationalExpression (void)
yystype AdditiveExpression (void)
yystype MultiplicativeExpression (void)
yystype UnaryExpression (void)
yystype PrimaryExpression (void)
G4int Eval2 (yystype arg1, G4int op, yystype arg2)
G4int CompareInt (G4int arg1, G4int op, G4int arg2)
G4int CompareDouble (double arg1, G4int op, double arg2)
tokenNum Yylex (void)
G4int G4UIpGetc (void)
G4int G4UIpUngetc (G4int c)
G4int Backslash (G4int c)
G4int Follow (G4int expect, G4int ifyes, G4int ifno)
G4String TokenToStr (G4int token)
Private Attributes
G4String parameterName
G4String parameterGuidance
G4String defaultValue
G4String parameterRange
G4String parameterCandidate
char parameterType
G4bool omittable
G4bool currentAsDefaultFlag
G4int widget
G4String rangeBuf
G4int bp
tokenNum token
yystype yylval
yystype newVal
G4int paramERR
Detailed Description
Definition at line 46 of file G4UIparameter.hh.
Constructor & Destructor Documentation
G4UIparameter() [1/3]
G4UIparameter::G4UIparameter ()
Definition at line 36 of file G4UIparameter.cc.
G4UIparameter() [2/3]
G4UIparameter::G4UIparameter (char theType)
Definition at line 52 of file G4UIparameter.cc.
G4UIparameter() [3/3]
G4UIparameter::G4UIparameter (const char * theName, char theType, G4bool theOmittable)
Definition at line 68 of file G4UIparameter.cc.
~G4UIparameter()
G4UIparameter::~G4UIparameter ()
Definition at line 84 of file G4UIparameter.cc.
Member Function Documentation
AdditiveExpression()
yystype G4UIparameter::AdditiveExpression (void) private
Definition at line 480 of file G4UIparameter.cc.
Referenced by RelationalExpression().
Backslash()
G4int G4UIparameter::Backslash (G4int c) private
CandidateCheck()
G4int G4UIparameter::CandidateCheck (const char * newValue) private
Definition at line 170 of file G4UIparameter.cc.
Referenced by CheckNewValue().
CheckNewValue()
G4int G4UIparameter::CheckNewValue (const char * newValue)
Definition at line 160 of file G4UIparameter.cc.
CompareDouble()
G4int G4UIparameter::CompareDouble (double arg1, G4int op, double arg2) private
Definition at line 659 of file G4UIparameter.cc.
Referenced by Eval2().
CompareInt()
G4int G4UIparameter::CompareInt (G4int arg1, G4int op, G4int arg2) private
Definition at line 634 of file G4UIparameter.cc.
Referenced by Eval2().
EqualityExpression()
yystype G4UIparameter::EqualityExpression (void) private
Definition at line 420 of file G4UIparameter.cc.
Referenced by LogicalANDExpression().
Eval2()
G4int G4UIparameter::Eval2 (yystype arg1, G4int op, yystype arg2) private
Definition at line 578 of file G4UIparameter.cc.
Referenced by EqualityExpression(), and RelationalExpression().
ExpectExponent()
G4int G4UIparameter::ExpectExponent (const char * str) private
Definition at line 271 of file G4UIparameter.cc.
Referenced by IsDouble().
Expression()
yystype G4UIparameter::Expression (void) private
Definition at line 338 of file G4UIparameter.cc.
Referenced by PrimaryExpression(), and RangeCheck().
Follow()
G4int G4UIparameter::Follow (G4int expect, G4int ifyes, G4int ifno) private
Definition at line 744 of file G4UIparameter.cc.
Referenced by Yylex().
G4UIpGetc()
G4int G4UIparameter::G4UIpGetc (void) private
Definition at line 755 of file G4UIparameter.cc.
Referenced by Follow(), and Yylex().
G4UIpUngetc()
G4int G4UIparameter::G4UIpUngetc (G4int c) private
Definition at line 763 of file G4UIparameter.cc.
Referenced by Follow(), and Yylex().
GetCurrentAsDefault()
G4bool G4UIparameter::GetCurrentAsDefault () const inline
Definition at line 135 of file G4UIparameter.hh.
Referenced by G4UIcommandTree::CreateHTML(), and export_G4UIparameter().
GetDefaultValue()
G4String G4UIparameter::GetDefaultValue () const inline
Definition at line 94 of file G4UIparameter.hh.
Referenced by G4UIcmdWithADoubleAndUnit::ConvertToStringWithDefaultUnit(), G4UIcmdWith3VectorAndUnit::ConvertToStringWithDefaultUnit(), G4UIcommandTree::CreateHTML(), export_G4UIparameter(), G4UIGainServer::GetNewTreeValues(), G4UIGAG::GetNewTreeValues(), G4UIGAG::SendAParamProperty(), G4UIGainServer::SendAParamProperty(), and G4UIGAG::SendATclParamProperty().
GetParameterCandidates()
G4String G4UIparameter::GetParameterCandidates () const inline
Definition at line 123 of file G4UIparameter.hh.
Referenced by G4UIcmdWithADoubleAndUnit::ConvertToStringWithBestUnit(), G4UIcmdWith3VectorAndUnit::ConvertToStringWithBestUnit(), G4UIcommandTree::CreateHTML(), G4UIterminal::ExecuteCommand(), export_G4UIparameter(), G4UIGainServer::GetNewTreeValues(), G4UIGAG::GetNewTreeValues(), G4UIGAG::SendAParamProperty(), G4UIGainServer::SendAParamProperty(), and G4UIGAG::SendATclParamProperty().
GetParameterGuidance()
const G4String G4UIparameter::GetParameterGuidance () const inline
Definition at line 141 of file G4UIparameter.hh.
Referenced by export_G4UIparameter(), G4UIGAG::SendAParamProperty(), G4UIGainServer::SendAParamProperty(), and G4UIGAG::SendATclParamProperty().
GetParameterName()
G4String G4UIparameter::GetParameterName () const inline
Definition at line 114 of file G4UIparameter.hh.
Referenced by G4UIcommandTree::CreateHTML(), export_G4UIparameter(), G4UImanager::GetCurrentStringValue(), G4UIGainServer::GetNewTreeValues(), G4UIGAG::GetNewTreeValues(), G4UIGAG::SendAParamProperty(), G4UIGainServer::SendAParamProperty(), G4UIGAG::SendATclParamProperty(), and G4GenericMessenger::Command::SetUnit().
GetParameterRange()
G4String G4UIparameter::GetParameterRange () const inline
Definition at line 108 of file G4UIparameter.hh.
Referenced by G4UIcommandTree::CreateHTML(), export_G4UIparameter(), G4UIGainServer::GetNewTreeValues(), G4UIGAG::GetNewTreeValues(), G4UIGAG::SendAParamProperty(), G4UIGainServer::SendAParamProperty(), and G4UIGAG::SendATclParamProperty().
GetParameterType()
char G4UIparameter::GetParameterType () const inline
Definition at line 96 of file G4UIparameter.hh.
Referenced by G4UIcommandTree::CreateHTML(), export_G4UIparameter(), G4UIGainServer::GetNewTreeValues(), G4UIGAG::GetNewTreeValues(), G4UIGAG::SendAParamProperty(), G4UIGainServer::SendAParamProperty(), and G4UIGAG::SendATclParamProperty().
IsDouble()
G4int G4UIparameter::IsDouble (const char * str) private
Definition at line 279 of file G4UIparameter.cc.
Referenced by TypeCheck(), and Yylex().
IsInt()
G4int G4UIparameter::IsInt (const char * str, short maxDigit) private
Definition at line 247 of file G4UIparameter.cc.
Referenced by ExpectExponent(), TypeCheck(), and Yylex().
IsOmittable()
G4bool G4UIparameter::IsOmittable () const inline
Definition at line 129 of file G4UIparameter.hh.
Referenced by G4UIcmdWithADoubleAndUnit::ConvertToStringWithDefaultUnit(), G4UIcmdWith3VectorAndUnit::ConvertToStringWithDefaultUnit(), G4UIcommandTree::CreateHTML(), export_G4UIparameter(), G4UIGAG::SendAParamProperty(), G4UIGainServer::SendAParamProperty(), G4UIGAG::SendATclParamProperty(), and G4GenericMessenger::Command::SetUnit().
List()
void G4UIparameter::List ()
Definition at line 97 of file G4UIparameter.cc.
Referenced by export_G4UIparameter().
LogicalANDExpression()
yystype G4UIparameter::LogicalANDExpression (void) private
Definition at line 384 of file G4UIparameter.cc.
Referenced by LogicalORExpression().
LogicalORExpression()
yystype G4UIparameter::LogicalORExpression (void) private
Definition at line 349 of file G4UIparameter.cc.
Referenced by Expression().
MultiplicativeExpression()
yystype G4UIparameter::MultiplicativeExpression (void) private
Definition at line 492 of file G4UIparameter.cc.
Referenced by AdditiveExpression().
operator!=()
G4bool G4UIparameter::operator!= (const G4UIparameter & right) const
Definition at line 92 of file G4UIparameter.cc.
operator==()
G4bool G4UIparameter::operator== (const G4UIparameter & right) const
Definition at line 87 of file G4UIparameter.cc.
PrimaryExpression()
yystype G4UIparameter::PrimaryExpression (void) private
Definition at line 541 of file G4UIparameter.cc.
Referenced by UnaryExpression().
RangeCheck()
G4int G4UIparameter::RangeCheck (const char * newValue) private
Definition at line 185 of file G4UIparameter.cc.
Referenced by CheckNewValue().
RelationalExpression()
yystype G4UIparameter::RelationalExpression (void) private
Definition at line 451 of file G4UIparameter.cc.
Referenced by EqualityExpression().
SetCurrentAsDefault()
void G4UIparameter::SetCurrentAsDefault (G4bool val) inline
Definition at line 133 of file G4UIparameter.hh.
Referenced by G4UIcmdWithAString::SetParameterName(), G4UIcmdWithADouble::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWith3Vector::SetParameterName(), G4UIcmdWithABool::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcmdWith3VectorAndUnit::SetParameterName(), G4GenericMessenger::Command::SetParameterName(), and G4UIcmdWithNucleusLimits::SetParameterName().
SetDefaultUnit()
void G4UIparameter::SetDefaultUnit (const char * theDefaultUnit)
Definition at line 132 of file G4UIparameter.cc.
Referenced by G4ScoreQuantityMessenger::FilterCommands(), G4EmParametersMessenger::G4EmParametersMessenger(), G4ScoringMessenger::G4ScoringMessenger(), G4UserPhysicsListMessenger::G4UserPhysicsListMessenger(), and G4ScoreQuantityMessenger::QuantityCommands().
SetDefaultValue() [1/3]
void G4UIparameter::SetDefaultValue (const char * theDefaultValue) inline
Definition at line 82 of file G4UIparameter.hh.
Referenced by CexmcScenePrimitivesMessenger::CexmcScenePrimitivesMessenger(), DMXParticleSourceMessenger::DMXParticleSourceMessenger(), G4ScoreQuantityMessenger::FilterCommands(), G4AdjointSimMessenger::G4AdjointSimMessenger(), G4EmParametersMessenger::G4EmParametersMessenger(), G4GeneralParticleSourceMessenger::G4GeneralParticleSourceMessenger(), G4GMocrenMessenger::G4GMocrenMessenger(), G4InteractorMessenger::G4InteractorMessenger(), G4MatScanMessenger::G4MatScanMessenger(), G4MonopolePhysicsMessenger::G4MonopolePhysicsMessenger(), G4OpticalPhysicsMessenger::G4OpticalPhysicsMessenger(), G4ParticleGunMessenger::G4ParticleGunMessenger(), G4PolarizationMessenger::G4PolarizationMessenger(), G4ProcessManagerMessenger::G4ProcessManagerMessenger(), G4ProcessTableMessenger::G4ProcessTableMessenger(), G4RunMessenger::G4RunMessenger(), G4ScoringMessenger::G4ScoringMessenger(), G4UIcontrolMessenger::G4UIcontrolMessenger(), G4UserPhysicsListMessenger::G4UserPhysicsListMessenger(), G4VisCommandGeometrySetColour::G4VisCommandGeometrySetColour(), G4VisCommandGeometrySetDaughtersInvisible::G4VisCommandGeometrySetDaughtersInvisible(), G4VisCommandGeometrySetForceAuxEdgeVisible::G4VisCommandGeometrySetForceAuxEdgeVisible(), G4VisCommandGeometrySetForceLineSegmentsPerCircle::G4VisCommandGeometrySetForceLineSegmentsPerCircle(), G4VisCommandGeometrySetForceSolid::G4VisCommandGeometrySetForceSolid(), G4VisCommandGeometrySetForceWireframe::G4VisCommandGeometrySetForceWireframe(), G4VisCommandGeometrySetLineStyle::G4VisCommandGeometrySetLineStyle(), G4VisCommandGeometrySetLineWidth::G4VisCommandGeometrySetLineWidth(), G4VisCommandGeometrySetVisibility::G4VisCommandGeometrySetVisibility(), G4VisCommandOpen::G4VisCommandOpen(), G4VisCommandSceneAddArrow::G4VisCommandSceneAddArrow(), G4VisCommandSceneAddAxes::G4VisCommandSceneAddAxes(), G4VisCommandSceneAddLine::G4VisCommandSceneAddLine(), G4VisCommandSceneAddLogicalVolume::G4VisCommandSceneAddLogicalVolume(), G4VisCommandSceneAddLogo::G4VisCommandSceneAddLogo(), G4VisCommandSceneAddScale::G4VisCommandSceneAddScale(), G4VisCommandSceneAddText::G4VisCommandSceneAddText(), G4VisCommandSceneAddText2D::G4VisCommandSceneAddText2D(), G4VisCommandSetColour::G4VisCommandSetColour(), G4VisCommandSetTextColour::G4VisCommandSetTextColour(), G4VisCommandSpecify::G4VisCommandSpecify(), G4VisCommandsTouchableSet::G4VisCommandsTouchableSet(), G4VisCommandsViewerSet::G4VisCommandsViewerSet(), G4VisCommandViewerCreate::G4VisCommandViewerCreate(), HistoMessenger::HistoMessenger(), G4ScoreQuantityMessenger::QuantityCommands(), G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWith3VectorAndUnit::SetDefaultUnit(), SetDefaultUnit(), G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcmdWithADouble::SetDefaultValue(), G4UIcmdWithAString::SetDefaultValue(), G4UIcmdWith3Vector::SetDefaultValue(), G4UIcmdWithABool::SetDefaultValue(), G4GenericMessenger::Command::SetDefaultValue(), G4UIcmdWithADoubleAndUnit::SetDefaultValue(), G4UIcmdWith3VectorAndUnit::SetDefaultValue(), and G4UIcmdWithNucleusLimits::SetDefaultValue().
SetDefaultValue() [2/3]
void G4UIparameter::SetDefaultValue (G4double theDefaultValue)
Definition at line 124 of file G4UIparameter.cc.
SetDefaultValue() [3/3]
void G4UIparameter::SetDefaultValue (G4int theDefaultValue)
Definition at line 117 of file G4UIparameter.cc.
SetGuidance()
void G4UIparameter::SetGuidance (const char * theGuidance) inline
Definition at line 143 of file G4UIparameter.hh.
Referenced by CexmcScenePrimitivesMessenger::CexmcScenePrimitivesMessenger(), G4MonopolePhysicsMessenger::G4MonopolePhysicsMessenger(), G4OpticalPhysicsMessenger::G4OpticalPhysicsMessenger(), G4RadioactiveDecayBaseMessenger::G4RadioactiveDecayBaseMessenger(), G4RadioactiveDecaymessenger::G4RadioactiveDecaymessenger(), G4VisCommandGeometrySetColour::G4VisCommandGeometrySetColour(), G4VisCommandGeometrySetDaughtersInvisible::G4VisCommandGeometrySetDaughtersInvisible(), G4VisCommandGeometrySetForceAuxEdgeVisible::G4VisCommandGeometrySetForceAuxEdgeVisible(), G4VisCommandGeometrySetForceLineSegmentsPerCircle::G4VisCommandGeometrySetForceLineSegmentsPerCircle(), G4VisCommandGeometrySetForceSolid::G4VisCommandGeometrySetForceSolid(), G4VisCommandGeometrySetForceWireframe::G4VisCommandGeometrySetForceWireframe(), G4VisCommandGeometrySetLineStyle::G4VisCommandGeometrySetLineStyle(), G4VisCommandGeometrySetLineWidth::G4VisCommandGeometrySetLineWidth(), G4VisCommandGeometrySetVisibility::G4VisCommandGeometrySetVisibility(), G4VisCommandOpen::G4VisCommandOpen(), G4VisCommandSceneAddLogo::G4VisCommandSceneAddLogo(), G4VisCommandSceneAddScale::G4VisCommandSceneAddScale(), G4VisCommandSceneAddText::G4VisCommandSceneAddText(), G4VisCommandSceneAddText2D::G4VisCommandSceneAddText2D(), G4VisCommandSetColour::G4VisCommandSetColour(), G4VisCommandSetTextColour::G4VisCommandSetTextColour(), G4VisCommandSetTouchable::G4VisCommandSetTouchable(), G4VisCommandsViewerSet::G4VisCommandsViewerSet(), G4VisCommandViewerCreate::G4VisCommandViewerCreate(), HistoMessenger::HistoMessenger(), RMC01AnalysisManagerMessenger::RMC01AnalysisManagerMessenger(), and TrackingMessenger::TrackingMessenger().
SetOmittable()
void G4UIparameter::SetOmittable (G4bool om) inline
Definition at line 127 of file G4UIparameter.hh.
Referenced by G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWith3VectorAndUnit::SetDefaultUnit(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithADouble::SetParameterName(), G4UIcmdWith3Vector::SetParameterName(), G4UIcmdWithABool::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcmdWith3VectorAndUnit::SetParameterName(), G4GenericMessenger::Command::SetParameterName(), and G4UIcmdWithNucleusLimits::SetParameterName().
SetParameterCandidates()
void G4UIparameter::SetParameterCandidates (const char * theString) inline
Definition at line 118 of file G4UIparameter.hh.
Referenced by CexmcScenePrimitivesMessenger::CexmcScenePrimitivesMessenger(), G4EmParametersMessenger::G4EmParametersMessenger(), G4InteractorMessenger::G4InteractorMessenger(), G4MatScanMessenger::G4MatScanMessenger(), G4OpticalPhysicsMessenger::G4OpticalPhysicsMessenger(), G4ParticleGunMessenger::G4ParticleGunMessenger(), G4UIcontrolMessenger::G4UIcontrolMessenger(), G4UserPhysicsListMessenger::G4UserPhysicsListMessenger(), G4VisCommandGeometrySetLineStyle::G4VisCommandGeometrySetLineStyle(), G4VisCommandsViewerSet::G4VisCommandsViewerSet(), RMC01AnalysisManagerMessenger::RMC01AnalysisManagerMessenger(), G4UIcmdWithAString::SetCandidates(), G4GenericMessenger::Command::SetCandidates(), SetDefaultUnit(), G4UIcmdWithADoubleAndUnit::SetUnitCandidates(), G4UIcmdWith3VectorAndUnit::SetUnitCandidates(), and TrackingMessenger::TrackingMessenger().
SetParameterName()
void G4UIparameter::SetParameterName (const char * theName) inline
Definition at line 112 of file G4UIparameter.hh.
Referenced by G4UIcmdWith3VectorAndUnit::G4UIcmdWith3VectorAndUnit(), G4UIcmdWithADoubleAndUnit::G4UIcmdWithADoubleAndUnit(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithADouble::SetParameterName(), G4UIcmdWith3Vector::SetParameterName(), G4UIcmdWithABool::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcmdWith3VectorAndUnit::SetParameterName(), G4GenericMessenger::Command::SetParameterName(), and G4UIcmdWithNucleusLimits::SetParameterName().
SetParameterRange()
void G4UIparameter::SetParameterRange (const char * theRange) inline
Definition at line 100 of file G4UIparameter.hh.
Referenced by G4AdjointSimMessenger::G4AdjointSimMessenger(), G4EmParametersMessenger::G4EmParametersMessenger(), G4GMocrenMessenger::G4GMocrenMessenger(), G4MatScanMessenger::G4MatScanMessenger(), G4MonopolePhysicsMessenger::G4MonopolePhysicsMessenger(), G4RadioactiveDecayBaseMessenger::G4RadioactiveDecayBaseMessenger(), G4RadioactiveDecaymessenger::G4RadioactiveDecaymessenger(), G4RunMessenger::G4RunMessenger(), G4ScoringMessenger::G4ScoringMessenger(), G4UIcontrolMessenger::G4UIcontrolMessenger(), G4UserPhysicsListMessenger::G4UserPhysicsListMessenger(), G4VisCommandsViewerSet::G4VisCommandsViewerSet(), HistoMessenger::HistoMessenger(), RMC01AnalysisManagerMessenger::RMC01AnalysisManagerMessenger(), and TrackingMessenger::TrackingMessenger().
SetWidget()
void G4UIparameter::SetWidget (G4int theWidget) inline
Definition at line 139 of file G4UIparameter.hh.
TokenToStr()
G4String G4UIparameter::TokenToStr (G4int token) private
TypeCheck()
G4int G4UIparameter::TypeCheck (const char * newValue) private
Definition at line 210 of file G4UIparameter.cc.
Referenced by CheckNewValue().
UnaryExpression()
yystype G4UIparameter::UnaryExpression (void) private
Definition at line 504 of file G4UIparameter.cc.
Referenced by MultiplicativeExpression().
Yylex()
tokenNum G4UIparameter::Yylex (void) private
Definition at line 686 of file G4UIparameter.cc.
Referenced by EqualityExpression(), LogicalANDExpression(), LogicalORExpression(), PrimaryExpression(), RangeCheck(), RelationalExpression(), and UnaryExpression().
Field Documentation
bp
G4int G4UIparameter::bp private
Definition at line 178 of file G4UIparameter.hh.
Referenced by G4UIparameter(), G4UIpGetc(), G4UIpUngetc(), and RangeCheck().
currentAsDefaultFlag
G4bool G4UIparameter::currentAsDefaultFlag private
Definition at line 78 of file G4UIparameter.hh.
Referenced by G4UIparameter(), GetCurrentAsDefault(), List(), and SetCurrentAsDefault().
defaultValue
G4String G4UIparameter::defaultValue private
Definition at line 73 of file G4UIparameter.hh.
Referenced by G4UIparameter(), GetDefaultValue(), List(), and SetDefaultValue().
newVal
yystype G4UIparameter::newVal private
Definition at line 181 of file G4UIparameter.hh.
Referenced by Eval2(), and RangeCheck().
omittable
G4bool G4UIparameter::omittable private
Definition at line 77 of file G4UIparameter.hh.
Referenced by G4UIparameter(), IsOmittable(), List(), and SetOmittable().
paramERR
G4int G4UIparameter::paramERR private
Definition at line 182 of file G4UIparameter.hh.
Referenced by AdditiveExpression(), CompareDouble(), CompareInt(), EqualityExpression(), Eval2(), G4UIpUngetc(), LogicalANDExpression(), LogicalORExpression(), MultiplicativeExpression(), PrimaryExpression(), RangeCheck(), UnaryExpression(), and Yylex().
parameterCandidate
G4String G4UIparameter::parameterCandidate private
Definition at line 75 of file G4UIparameter.hh.
Referenced by CandidateCheck(), CheckNewValue(), G4UIparameter(), GetParameterCandidates(), List(), and SetParameterCandidates().
parameterGuidance
G4String G4UIparameter::parameterGuidance private
Definition at line 72 of file G4UIparameter.hh.
Referenced by G4UIparameter(), GetParameterGuidance(), List(), and SetGuidance().
parameterName
G4String G4UIparameter::parameterName private
Definition at line 71 of file G4UIparameter.hh.
Referenced by Eval2(), G4UIparameter(), GetParameterName(), List(), SetDefaultUnit(), SetParameterName(), and Yylex().
parameterRange
G4String G4UIparameter::parameterRange private
Definition at line 74 of file G4UIparameter.hh.
Referenced by CheckNewValue(), Eval2(), G4UIparameter(), G4UIpGetc(), G4UIpUngetc(), GetParameterRange(), List(), RangeCheck(), and SetParameterRange().
parameterType
char G4UIparameter::parameterType private
Definition at line 76 of file G4UIparameter.hh.
Referenced by Eval2(), G4UIparameter(), GetParameterType(), List(), RangeCheck(), SetDefaultUnit(), and TypeCheck().
rangeBuf
G4String G4UIparameter::rangeBuf private
Definition at line 177 of file G4UIparameter.hh.
token
tokenNum G4UIparameter::token private
Definition at line 179 of file G4UIparameter.hh.
Referenced by AdditiveExpression(), EqualityExpression(), G4UIparameter(), LogicalANDExpression(), LogicalORExpression(), MultiplicativeExpression(), PrimaryExpression(), RangeCheck(), RelationalExpression(), and UnaryExpression().
widget
G4int G4UIparameter::widget private
Definition at line 79 of file G4UIparameter.hh.
Referenced by G4UIparameter(), and SetWidget().
yylval
yystype G4UIparameter::yylval private
Definition at line 180 of file G4UIparameter.hh.
Referenced by PrimaryExpression(), and Yylex().
The documentation for this class was generated from the following files:
source/intercoms/include/G4UIparameter.hh
source/intercoms/src/G4UIparameter.cc