Geant4: G4VITTrackHolder Class Reference
G4VITTrackHolder Class Reference
G4ITTrackHolder is an empty interface that permits to push tracks to the IT system without actually depending on the IT tracking system.
#include <G4VITTrackHolder.hh>
Public Member Functions
virtual void Push (G4Track *)
virtual size_t GetNTracks ()
Static Public Member Functions
static G4VITTrackHolder * Instance ()
Protected Member Functions
G4VITTrackHolder ()
virtual ~G4VITTrackHolder ()
Static Protected Attributes
static G4ThreadLocal G4VITTrackHolder * fInstance
Detailed Description
G4ITTrackHolder is an empty interface that permits to push tracks to the IT system without actually depending on the IT tracking system.
However, G4ITTrackHolder does not permit to retrieve any track.
Definition at line 60 of file G4VITTrackHolder.hh.
Constructor & Destructor Documentation
G4VITTrackHolder()
G4VITTrackHolder::G4VITTrackHolder () protected
Definition at line 44 of file G4VITTrackHolder.cc.
~G4VITTrackHolder()
G4VITTrackHolder::~G4VITTrackHolder () protected virtual
Definition at line 49 of file G4VITTrackHolder.cc.
Member Function Documentation
GetNTracks()
virtual size_t G4VITTrackHolder::GetNTracks () inline virtual
Reimplemented in G4ITTrackHolder.
Definition at line 70 of file G4VITTrackHolder.hh.
Instance()
G4VITTrackHolder * G4VITTrackHolder::Instance (void) static
Definition at line 54 of file G4VITTrackHolder.cc.
Referenced by G4DNAChemistryManager::CreateSolvatedElectron(), G4DNAChemistryManager::CreateWaterMolecule(), G4DNAChemistryManager::PushMolecule(), G4DNAChemistryManager::PushMoleculeAtParentTimeAndPlace(), and G4ITGun::PushTrack().
Push()
void G4VITTrackHolder::Push (G4Track * track) virtual
Reimplemented in G4ITTrackHolder.
Definition at line 60 of file G4VITTrackHolder.cc.
Referenced by G4DNAChemistryManager::CreateSolvatedElectron(), G4DNAChemistryManager::CreateWaterMolecule(), G4DNAChemistryManager::PushMolecule(), G4DNAChemistryManager::PushMoleculeAtParentTimeAndPlace(), and G4ITGun::PushTrack().
Field Documentation
fInstance
G4ThreadLocal G4VITTrackHolder * G4VITTrackHolder::fInstance static protected
Definition at line 65 of file G4VITTrackHolder.hh.
Referenced by G4VITTrackHolder(), Instance(), and ~G4VITTrackHolder().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/dna/management/include/G4VITTrackHolder.hh
source/processes/electromagnetic/dna/management/src/G4VITTrackHolder.cc