Geant4: G4PVPlacement Class Reference
G4PVPlacement Class Reference
#include <G4PVPlacement.hh>
Public Member Functions
G4PVPlacement (G4RotationMatrix *pRot, const G4ThreeVector &tlate, G4LogicalVolume *pCurrentLogical, const G4String &pName, G4LogicalVolume *pMotherLogical, G4bool pMany, G4int pCopyNo, G4bool pSurfChk=false)
G4PVPlacement (const G4Transform3D &Transform3D, G4LogicalVolume *pCurrentLogical, const G4String &pName, G4LogicalVolume *pMotherLogical, G4bool pMany, G4int pCopyNo, G4bool pSurfChk=false)
G4PVPlacement (G4RotationMatrix *pRot, const G4ThreeVector &tlate, const G4String &pName, G4LogicalVolume *pLogical, G4VPhysicalVolume *pMother, G4bool pMany, G4int pCopyNo, G4bool pSurfChk=false)
G4PVPlacement (const G4Transform3D &Transform3D, const G4String &pName, G4LogicalVolume *pLogical, G4VPhysicalVolume *pMother, G4bool pMany, G4int pCopyNo, G4bool pSurfChk=false)
virtual ~G4PVPlacement ()
G4int GetCopyNo () const
void SetCopyNo (G4int CopyNo)
G4bool CheckOverlaps (G4int res=1000, G4double tol=0., G4bool verbose=true, G4int maxErr=1)
G4PVPlacement (__void__ &)
G4bool IsMany () const
G4bool IsReplicated () const
G4bool IsParameterised () const
G4VPVParameterisation * GetParameterisation () const
void GetReplicationData (EAxis &axis, G4int &nReplicas, G4double &width, G4double &offset, G4bool &consuming) const
G4bool IsRegularStructure () const
G4int GetRegularStructureId () const
Public Member Functions inherited from G4VPhysicalVolume
G4VPhysicalVolume (G4RotationMatrix *pRot, const G4ThreeVector &tlate, const G4String &pName, G4LogicalVolume *pLogical, G4VPhysicalVolume *pMother)
virtual ~G4VPhysicalVolume ()
G4bool operator== (const G4VPhysicalVolume &p) const
G4RotationMatrix * GetObjectRotation () const
G4RotationMatrix GetObjectRotationValue () const
G4ThreeVector GetObjectTranslation () const
const G4RotationMatrix * GetFrameRotation () const
G4ThreeVector GetFrameTranslation () const
const G4ThreeVector & GetTranslation () const
const G4RotationMatrix * GetRotation () const
void SetTranslation (const G4ThreeVector &v)
G4RotationMatrix * GetRotation ()
void SetRotation (G4RotationMatrix *)
G4LogicalVolume * GetLogicalVolume () const
void SetLogicalVolume (G4LogicalVolume *pLogical)
G4LogicalVolume * GetMotherLogical () const
void SetMotherLogical (G4LogicalVolume *pMother)
const G4String & GetName () const
void SetName (const G4String &pName)
EVolume VolumeType () const
virtual G4int GetMultiplicity () const
G4VPhysicalVolume (__void__ &)
G4int GetInstanceID () const
Private Member Functions
G4PVPlacement (const G4PVPlacement &)
G4PVPlacement & operator= (const G4PVPlacement &)
Static Private Member Functions
static G4RotationMatrix * NewPtrRotMatrix (const G4RotationMatrix &RotMat)
Private Attributes
G4bool fmany
G4bool fallocatedRotM
G4int fcopyNo
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicalVolume
static const G4PVManager & GetSubInstanceManager ()
static void Clean ()
Protected Member Functions inherited from G4VPhysicalVolume
void InitialiseWorker (G4VPhysicalVolume *pMasterObject, G4RotationMatrix *pRot, const G4ThreeVector &tlate)
void TerminateWorker (G4VPhysicalVolume *pMasterObject)
Protected Attributes inherited from G4VPhysicalVolume
G4int instanceID
Static Protected Attributes inherited from G4VPhysicalVolume
static G4GEOM_DLL G4PVManager subInstanceManager
Detailed Description
Definition at line 50 of file G4PVPlacement.hh.
Constructor & Destructor Documentation
G4PVPlacement() [1/6]
G4PVPlacement::G4PVPlacement (G4RotationMatrix * pRot, const G4ThreeVector & tlate, G4LogicalVolume * pCurrentLogical, const G4String & pName, G4LogicalVolume * pMotherLogical, G4bool pMany, G4int pCopyNo, G4bool pSurfChk = false)
Definition at line 99 of file G4PVPlacement.cc.
Referenced by LXeMainVolume::LXeMainVolume(), LXeWLSFiber::LXeWLSFiber(), and LXeMainVolume::PlacePMTs().
G4PVPlacement() [2/6]
G4PVPlacement::G4PVPlacement (const G4Transform3D & Transform3D, G4LogicalVolume * pCurrentLogical, const G4String & pName, G4LogicalVolume * pMotherLogical, G4bool pMany, G4int pCopyNo, G4bool pSurfChk = false)
Definition at line 124 of file G4PVPlacement.cc.
G4PVPlacement() [3/6]
G4PVPlacement::G4PVPlacement (G4RotationMatrix * pRot, const G4ThreeVector & tlate, const G4String & pName, G4LogicalVolume * pLogical, G4VPhysicalVolume * pMother, G4bool pMany, G4int pCopyNo, G4bool pSurfChk = false)
Definition at line 42 of file G4PVPlacement.cc.
G4PVPlacement() [4/6]
G4PVPlacement::G4PVPlacement (const G4Transform3D & Transform3D, const G4String & pName, G4LogicalVolume * pLogical, G4VPhysicalVolume * pMother, G4bool pMany, G4int pCopyNo, G4bool pSurfChk = false)
Definition at line 70 of file G4PVPlacement.cc.
~G4PVPlacement()
G4PVPlacement::~G4PVPlacement () virtual
Definition at line 158 of file G4PVPlacement.cc.
G4PVPlacement() [5/6]
G4PVPlacement::G4PVPlacement (__void__ & a)
Definition at line 150 of file G4PVPlacement.cc.
G4PVPlacement() [6/6]
G4PVPlacement::G4PVPlacement (const G4PVPlacement &) private
Member Function Documentation
CheckOverlaps()
G4bool G4PVPlacement::CheckOverlaps (G4int res = 1000, G4double tol = 0., G4bool verbose = true, G4int maxErr = 1) virtual
Reimplemented from G4VPhysicalVolume.
Definition at line 235 of file G4PVPlacement.cc.
Referenced by export_G4PVPlacement(), and G4PVPlacement().
GetCopyNo()
G4int G4PVPlacement::GetCopyNo () const inline virtual
Implements G4VPhysicalVolume.
Definition at line 124 of file G4PVPlacement.hh.
Referenced by CheckOverlaps().
GetParameterisation()
G4VPVParameterisation * G4PVPlacement::GetParameterisation () const virtual
Implements G4VPhysicalVolume.
Definition at line 198 of file G4PVPlacement.cc.
GetRegularStructureId()
G4int G4PVPlacement::GetRegularStructureId () const virtual
Implements G4VPhysicalVolume.
Definition at line 227 of file G4PVPlacement.cc.
GetReplicationData()
void G4PVPlacement::GetReplicationData (EAxis & axis, G4int & nReplicas, G4double & width, G4double & offset, G4bool & consuming) const virtual
Implements G4VPhysicalVolume.
Definition at line 207 of file G4PVPlacement.cc.
IsMany()
G4bool G4PVPlacement::IsMany () const virtual
Implements G4VPhysicalVolume.
Definition at line 166 of file G4PVPlacement.cc.
IsParameterised()
G4bool G4PVPlacement::IsParameterised () const virtual
Implements G4VPhysicalVolume.
Definition at line 190 of file G4PVPlacement.cc.
IsRegularStructure()
G4bool G4PVPlacement::IsRegularStructure () const virtual
Implements G4VPhysicalVolume.
Definition at line 217 of file G4PVPlacement.cc.
IsReplicated()
G4bool G4PVPlacement::IsReplicated () const virtual
Implements G4VPhysicalVolume.
Definition at line 182 of file G4PVPlacement.cc.
NewPtrRotMatrix()
G4RotationMatrix * G4PVPlacement::NewPtrRotMatrix (const G4RotationMatrix & RotMat) static private
Definition at line 393 of file G4PVPlacement.cc.
Referenced by G4PVPlacement().
operator=()
G4PVPlacement& G4PVPlacement::operator= (const G4PVPlacement &) private
SetCopyNo()
void G4PVPlacement::SetCopyNo (G4int CopyNo) virtual
Implements G4VPhysicalVolume.
Definition at line 174 of file G4PVPlacement.cc.
Field Documentation
fallocatedRotM
G4bool G4PVPlacement::fallocatedRotM private
Definition at line 172 of file G4PVPlacement.hh.
Referenced by G4PVPlacement(), and ~G4PVPlacement().
fcopyNo
G4int G4PVPlacement::fcopyNo private
Definition at line 173 of file G4PVPlacement.hh.
Referenced by GetCopyNo(), and SetCopyNo().
fmany
G4bool G4PVPlacement::fmany private
Definition at line 171 of file G4PVPlacement.hh.
Referenced by IsMany().
The documentation for this class was generated from the following files:
source/geometry/volumes/include/G4PVPlacement.hh
source/geometry/volumes/src/G4PVPlacement.cc