Geant4: G4BosonConstructor Class Reference
G4BosonConstructor Class Reference
#include <G4BosonConstructor.hh>
Public Member Functions
G4BosonConstructor ()
~G4BosonConstructor ()
Static Public Member Functions
static void ConstructParticle ()
Detailed Description
Definition at line 38 of file G4BosonConstructor.hh.
Constructor & Destructor Documentation
G4BosonConstructor()
G4BosonConstructor::G4BosonConstructor ()
Definition at line 43 of file G4BosonConstructor.cc.
~G4BosonConstructor()
G4BosonConstructor::~G4BosonConstructor ()
Definition at line 47 of file G4BosonConstructor.cc.
Member Function Documentation
ConstructParticle()
void G4BosonConstructor::ConstructParticle (void) static
Definition at line 52 of file G4BosonConstructor.cc.
Referenced by B03PhysicsList::ConstructAllBosons(), GammaKnifeParticles::ConstructParticle(), HadrontherapyParticles::ConstructParticle(), G4ChannelingPhysics::ConstructParticle(), Particles::ConstructParticle(), GammaRayTelParticles::ConstructParticle(), G4DecayPhysics::ConstructParticle(), and OpNovicePhysicsList::ConstructParticle().
The documentation for this class was generated from the following files:
source/particles/bosons/include/G4BosonConstructor.hh
source/particles/bosons/src/G4BosonConstructor.cc