Geant4: G4ErrorRunManagerHelper Class Reference
G4ErrorRunManagerHelper Class Reference
#include <G4ErrorRunManagerHelper.hh>
Public Member Functions
G4ErrorRunManagerHelper ()
virtual ~G4ErrorRunManagerHelper ()
void SetUserInitialization (G4VUserDetectorConstruction *userInit)
void SetUserInitialization (G4VPhysicalVolume *userInit)
void SetUserInitialization (G4VUserPhysicsList *userInit)
void SetUserAction (G4UserTrackingAction *userAction)
void SetUserAction (G4UserSteppingAction *userAction)
void RunInitialization ()
void InitializeGeometry ()
void InitializePhysics ()
void RunTermination ()
G4VUserPhysicsList * GetUserPhysicsList () const
Static Public Member Functions
static G4ErrorRunManagerHelper * GetRunManagerKernel ()
Private Attributes
G4VUserPhysicsList * theUserPhysicsList
G4VPhysicalVolume * theUserWorld
G4RunManagerKernel * theG4RunManagerKernel
Static Private Attributes
static G4ThreadLocal G4ErrorRunManagerHelper * fRunManagerKernel = 0
Detailed Description
Definition at line 52 of file G4ErrorRunManagerHelper.hh.
Constructor & Destructor Documentation
G4ErrorRunManagerHelper()
G4ErrorRunManagerHelper::G4ErrorRunManagerHelper ()
Definition at line 55 of file G4ErrorRunManagerHelper.cc.
~G4ErrorRunManagerHelper()
G4ErrorRunManagerHelper::~G4ErrorRunManagerHelper () virtual
Definition at line 80 of file G4ErrorRunManagerHelper.cc.
Member Function Documentation
GetRunManagerKernel()
G4ErrorRunManagerHelper * G4ErrorRunManagerHelper::GetRunManagerKernel () static
Definition at line 50 of file G4ErrorRunManagerHelper.cc.
Referenced by G4ErrorPropagatorManager::StartG4ErrorRunManagerHelper().
GetUserPhysicsList()
G4VUserPhysicsList* G4ErrorRunManagerHelper::GetUserPhysicsList () const inline
Definition at line 88 of file G4ErrorRunManagerHelper.hh.
Referenced by InitializePhysics().
InitializeGeometry()
void G4ErrorRunManagerHelper::InitializeGeometry ()
Definition at line 107 of file G4ErrorRunManagerHelper.cc.
Referenced by G4ErrorPropagatorManager::InitGeant4e().
InitializePhysics()
void G4ErrorRunManagerHelper::InitializePhysics ()
Definition at line 129 of file G4ErrorRunManagerHelper.cc.
Referenced by G4ErrorPropagatorManager::InitGeant4e().
RunInitialization()
void G4ErrorRunManagerHelper::RunInitialization ()
Definition at line 160 of file G4ErrorRunManagerHelper.cc.
Referenced by G4ErrorPropagatorManager::InitGeant4e().
RunTermination()
void G4ErrorRunManagerHelper::RunTermination ()
Definition at line 182 of file G4ErrorRunManagerHelper.cc.
Referenced by G4ErrorPropagatorManager::RunTermination().
SetUserAction() [1/2]
void G4ErrorRunManagerHelper::SetUserAction (G4UserSteppingAction * userAction)
Definition at line 175 of file G4ErrorRunManagerHelper.cc.
SetUserAction() [2/2]
void G4ErrorRunManagerHelper::SetUserAction (G4UserTrackingAction * userAction)
Definition at line 167 of file G4ErrorRunManagerHelper.cc.
SetUserInitialization() [1/3]
void G4ErrorRunManagerHelper::SetUserInitialization (G4VPhysicalVolume * userInit)
Definition at line 93 of file G4ErrorRunManagerHelper.cc.
SetUserInitialization() [2/3]
void G4ErrorRunManagerHelper::SetUserInitialization (G4VUserDetectorConstruction * userInit)
Definition at line 86 of file G4ErrorRunManagerHelper.cc.
Referenced by G4ErrorPropagatorManager::SetUserInitialization().
SetUserInitialization() [3/3]
void G4ErrorRunManagerHelper::SetUserInitialization (G4VUserPhysicsList * userInit)
Definition at line 100 of file G4ErrorRunManagerHelper.cc.
Field Documentation
fRunManagerKernel
G4ThreadLocal G4ErrorRunManagerHelper * G4ErrorRunManagerHelper::fRunManagerKernel = 0 static private
Definition at line 93 of file G4ErrorRunManagerHelper.hh.
Referenced by G4ErrorRunManagerHelper(), and GetRunManagerKernel().
theG4RunManagerKernel
G4RunManagerKernel* G4ErrorRunManagerHelper::theG4RunManagerKernel private
Definition at line 98 of file G4ErrorRunManagerHelper.hh.
Referenced by G4ErrorRunManagerHelper(), InitializeGeometry(), InitializePhysics(), RunInitialization(), and RunTermination().
theUserPhysicsList
G4VUserPhysicsList* G4ErrorRunManagerHelper::theUserPhysicsList private
Definition at line 95 of file G4ErrorRunManagerHelper.hh.
Referenced by G4ErrorRunManagerHelper(), GetUserPhysicsList(), InitializePhysics(), and SetUserInitialization().
theUserWorld
G4VPhysicalVolume* G4ErrorRunManagerHelper::theUserWorld private
Definition at line 96 of file G4ErrorRunManagerHelper.hh.
Referenced by G4ErrorRunManagerHelper(), InitializeGeometry(), and SetUserInitialization().
The documentation for this class was generated from the following files:
source/error_propagation/include/G4ErrorRunManagerHelper.hh
source/error_propagation/src/G4ErrorRunManagerHelper.cc