Geant4: G4ParameterisationPolyhedraZ Class Reference
G4ParameterisationPolyhedraZ Class Reference
#include <G4ParameterisationPolyhedra.hh>
Public Member Functions
G4ParameterisationPolyhedraZ (EAxis axis, G4int nCopies, G4double offset, G4double step, G4VSolid *motherSolid, DivisionType divType)
~G4ParameterisationPolyhedraZ ()
void CheckParametersValidity ()
G4double GetMaxParameter () const
void ComputeTransformation (const G4int copyNo, G4VPhysicalVolume *physVol) const
void ComputeDimensions (G4Polyhedra &phedra, const G4int copyNo, const G4VPhysicalVolume *physVol) const
Public Member Functions inherited from G4VParameterisationPolyhedra
G4VParameterisationPolyhedra (EAxis axis, G4int nCopies, G4double offset, G4double step, G4VSolid *msolid, DivisionType divType)
virtual ~G4VParameterisationPolyhedra ()
Public Member Functions inherited from G4VDivisionParameterisation
G4VDivisionParameterisation (EAxis axis, G4int nDiv, G4double width, G4double offset, DivisionType divType, G4VSolid *motherSolid=0)
virtual ~G4VDivisionParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
const G4String & GetType () const
EAxis GetAxis () const
G4int GetNoDiv () const
G4double GetWidth () const
G4double GetOffset () const
G4VSolid * GetMotherSolid () const
void SetType (const G4String &type)
G4int VolumeFirstCopyNo () const
void SetHalfGap (G4double hg)
G4double GetHalfGap () const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=0)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Private Member Functions
G4double GetR (G4double z, G4double z1, G4double r1, G4double z2, G4double r2) const
G4double GetRmin (G4double z, G4int nsegment) const
G4double GetRmax (G4double z, G4int nsegment) const
void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
Private Attributes
G4int fNSegment
G4PolyhedraHistorical * fOrigParamMother
Additional Inherited Members
Protected Member Functions inherited from G4VDivisionParameterisation
void ChangeRotMatrix (G4VPhysicalVolume *physVol, G4double rotZ=0.) const
G4int CalculateNDiv (G4double motherDim, G4double width, G4double offset) const
G4double CalculateWidth (G4double motherDim, G4int nDiv, G4double offset) const
void CheckOffset (G4double maxPar)
void CheckNDivAndWidth (G4double maxPar)
G4double OffsetZ () const
Protected Attributes inherited from G4VDivisionParameterisation
G4String ftype
EAxis faxis
G4int fnDiv
G4double fwidth
G4double foffset
DivisionType fDivisionType
G4VSolid * fmotherSolid
G4bool fReflectedSolid
G4bool fDeleteSolid
G4int theVoluFirstCopyNo
G4double kCarTolerance
G4double fhgap
Static Protected Attributes inherited from G4VDivisionParameterisation
static G4ThreadLocal G4RotationMatrix * fRot = 0
static const G4int verbose = 5
Detailed Description
Definition at line 187 of file G4ParameterisationPolyhedra.hh.
Constructor & Destructor Documentation
G4ParameterisationPolyhedraZ()
G4ParameterisationPolyhedraZ::G4ParameterisationPolyhedraZ (EAxis axis, G4int nCopies, G4double offset, G4double step, G4VSolid * motherSolid, DivisionType divType)
Definition at line 433 of file G4ParameterisationPolyhedra.cc.
~G4ParameterisationPolyhedraZ()
G4ParameterisationPolyhedraZ::~G4ParameterisationPolyhedraZ ()
Definition at line 468 of file G4ParameterisationPolyhedra.cc.
Member Function Documentation
CheckParametersValidity()
void G4ParameterisationPolyhedraZ::CheckParametersValidity () virtual
Reimplemented from G4VDivisionParameterisation.
Definition at line 517 of file G4ParameterisationPolyhedra.cc.
Referenced by G4ParameterisationPolyhedraZ().
ComputeDimensions() [1/13]
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Box & , const G4int, const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 218 of file G4ParameterisationPolyhedra.hh.
ComputeDimensions() [2/13]
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Cons & , const G4int, const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 234 of file G4ParameterisationPolyhedra.hh.
ComputeDimensions() [3/13]
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Ellipsoid & , const G4int, const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 224 of file G4ParameterisationPolyhedra.hh.
ComputeDimensions() [4/13]
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Hype & , const G4int, const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 230 of file G4ParameterisationPolyhedra.hh.
ComputeDimensions() [5/13]
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Orb & , const G4int, const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 222 of file G4ParameterisationPolyhedra.hh.
ComputeDimensions() [6/13]
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Para & , const G4int, const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 228 of file G4ParameterisationPolyhedra.hh.
ComputeDimensions() [7/13]
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Polycone & , const G4int, const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 236 of file G4ParameterisationPolyhedra.hh.
ComputeDimensions() [8/13]
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Polyhedra & phedra, const G4int copyNo, const G4VPhysicalVolume * physVol) const virtual
Reimplemented from G4VPVParameterisation.
Definition at line 656 of file G4ParameterisationPolyhedra.cc.
ComputeDimensions() [9/13]
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Sphere & , const G4int, const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 220 of file G4ParameterisationPolyhedra.hh.
ComputeDimensions() [10/13]
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Torus & , const G4int, const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 226 of file G4ParameterisationPolyhedra.hh.
ComputeDimensions() [11/13]
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Trap & , const G4int, const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 216 of file G4ParameterisationPolyhedra.hh.
ComputeDimensions() [12/13]
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Trd & , const G4int, const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 214 of file G4ParameterisationPolyhedra.hh.
ComputeDimensions() [13/13]
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Tubs & , const G4int, const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 232 of file G4ParameterisationPolyhedra.hh.
ComputeTransformation()
void G4ParameterisationPolyhedraZ::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const virtual
Implements G4VDivisionParameterisation.
Definition at line 607 of file G4ParameterisationPolyhedra.cc.
GetMaxParameter()
G4double G4ParameterisationPolyhedraZ::GetMaxParameter () const virtual
Implements G4VDivisionParameterisation.
Definition at line 510 of file G4ParameterisationPolyhedra.cc.
GetR()
G4double G4ParameterisationPolyhedraZ::GetR (G4double z, G4double z1, G4double r1, G4double z2, G4double r2) const private
Definition at line 473 of file G4ParameterisationPolyhedra.cc.
Referenced by GetRmax(), and GetRmin().
GetRmax()
G4double G4ParameterisationPolyhedraZ::GetRmax (G4double z, G4int nsegment) const private
Definition at line 498 of file G4ParameterisationPolyhedra.cc.
Referenced by ComputeDimensions().
GetRmin()
G4double G4ParameterisationPolyhedraZ::GetRmin (G4double z, G4int nsegment) const private
Definition at line 486 of file G4ParameterisationPolyhedra.cc.
Referenced by ComputeDimensions().
Field Documentation
fNSegment
G4int G4ParameterisationPolyhedraZ::fNSegment private
Definition at line 240 of file G4ParameterisationPolyhedra.hh.
Referenced by CheckParametersValidity(), and ComputeDimensions().
fOrigParamMother
G4PolyhedraHistorical* G4ParameterisationPolyhedraZ::fOrigParamMother private
Definition at line 241 of file G4ParameterisationPolyhedra.hh.
Referenced by CheckParametersValidity(), ComputeDimensions(), ComputeTransformation(), G4ParameterisationPolyhedraZ(), GetMaxParameter(), GetRmax(), and GetRmin().
The documentation for this class was generated from the following files:
source/geometry/divisions/include/G4ParameterisationPolyhedra.hh
source/geometry/divisions/src/G4ParameterisationPolyhedra.cc