Geant4: G4ProcessVector Class Reference
G4ProcessVector Class Reference
#include <G4ProcessVector.hh>
Public Member Functions
G4ProcessVector ()
G4ProcessVector (size_t)
G4ProcessVector (const G4ProcessVector &)
virtual ~G4ProcessVector ()
G4ProcessVector & operator= (const G4ProcessVector &right)
G4bool operator== (const G4ProcessVector &right) const
G4int entries () const
G4int length () const
G4int size () const
G4int index (G4VProcess *aProcess) const
G4bool contains (G4VProcess *aProcess) const
G4bool insert (G4VProcess *aProcess)
G4bool insertAt (G4int i, G4VProcess *aProcess)
G4VProcess * removeAt (G4int i)
G4VProcess * removeLast ()
void clear ()
G4VProcess *const & operator[] (G4int i) const
G4VProcess *const & operator() (G4int i) const
G4VProcess *& operator[] (G4int i)
G4VProcess *& operator() (G4int i)
Protected Types
typedef std::vector< G4VProcess * > G4ProcVector
Protected Attributes
G4ProcVector * pProcVector
Detailed Description
Definition at line 45 of file G4ProcessVector.hh.
Member Typedef Documentation
G4ProcVector
typedef std::vector<G4VProcess*> G4ProcessVector::G4ProcVector protected
Definition at line 99 of file G4ProcessVector.hh.
Constructor & Destructor Documentation
G4ProcessVector() [1/3]
G4ProcessVector::G4ProcessVector ()
Definition at line 40 of file G4ProcessVector.cc.
G4ProcessVector() [2/3]
G4ProcessVector::G4ProcessVector (size_t siz) explicit
Definition at line 45 of file G4ProcessVector.cc.
G4ProcessVector() [3/3]
G4ProcessVector::G4ProcessVector (const G4ProcessVector & right)
Definition at line 50 of file G4ProcessVector.cc.
~G4ProcessVector()
G4ProcessVector::~G4ProcessVector () virtual
Definition at line 65 of file G4ProcessVector.cc.
Member Function Documentation
clear()
void G4ProcessVector::clear ()
Referenced by G4ProcessManager::CreateGPILvectors(), and G4ProcessManager::~G4ProcessManager().
contains()
G4bool G4ProcessVector::contains (G4VProcess * aProcess) const
Referenced by G4GlobalFastSimulationManager::ShowSetup().
entries()
G4int G4ProcessVector::entries () const
Referenced by G4ProcessManager::AddProcess(), G4ProcessManager::CreateGPILvectors(), G4ITStepProcessor::DealWithSecondaries(), G4ProcessManager::DumpInfo(), G4ProcessManager::EndTracking(), G4ProcessManager::FindInsertPosition(), G4ProcessManager::G4ProcessManager(), G4SteppingManager::GetProcessNumber(), G4ProcessManager::InsertAt(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePSDIP(), G4ProcessManager::RemoveAt(), G4ProcessManager::SetProcessOrderingToSecond(), G4ITStepProcessor::SetupGeneralProcessInfo(), G4ProcessManager::StartTracking(), and WLSSteppingAction::UserSteppingAction().
index()
G4int G4ProcessVector::index (G4VProcess * aProcess) const
insert()
G4bool G4ProcessVector::insert (G4VProcess * aProcess)
Referenced by G4ProcessManager::AddProcess(), G4ProcessManager::CreateGPILvectors(), G4ProcessTable::ExtractProcesses(), and G4ProcessManager::G4ProcessManager().
insertAt()
G4bool G4ProcessVector::insertAt (G4int i, G4VProcess * aProcess)
Referenced by G4ProcessManager::InsertAt().
length()
G4int G4ProcessVector::length () const
Referenced by P6DExtDecayerPhysics::ConstructProcess(), G4ProcessPlacer::PrintProcVec(), G4ProcessTableMessenger::SetNewValue(), and G4ProcessTable::SetProcessActivation().
operator()() [1/2]
G4VProcess* & G4ProcessVector::operator() (G4int i)
operator()() [2/2]
G4VProcess* const& G4ProcessVector::operator() (G4int i) const
operator=()
G4ProcessVector & G4ProcessVector::operator= (const G4ProcessVector & right)
Definition at line 77 of file G4ProcessVector.cc.
operator==()
G4bool G4ProcessVector::operator== (const G4ProcessVector & right) const
operator[]() [1/2]
G4VProcess* & G4ProcessVector::operator[] (G4int i)
operator[]() [2/2]
G4VProcess* const& G4ProcessVector::operator[] (G4int i) const
removeAt()
G4VProcess* G4ProcessVector::removeAt (G4int i)
Referenced by G4ProcessManager::RemoveAt(), and G4ProcessManager::RemoveProcess().
removeLast()
G4VProcess* G4ProcessVector::removeLast ()
Referenced by G4ProcessManager::AddProcess().
size()
G4int G4ProcessVector::size () const
Referenced by G4BiasingHelper::ActivatePhysicsBiasing(), G4EmCalculator::ActiveForParticle(), G4ITStepProcessor::ActiveOnlyITProcess(), G4BiasingHelper::AddLimiterProcess(), G4hImpactIonisation::AlongStepDoIt(), RunAction::BeginOfRunAction(), G4VUserChemistryList::BuildPhysicsTable(), G4VUserPhysicsList::BuildPhysicsTable(), G4LossTableManager::BuildTables(), G4PhysicsListHelper::CheckParticleList(), G4NeutronCrossSectionXS::ConstructProcess(), G4FastSimulationPhysics::ConstructProcess(), G4GenericBiasingPhysics::ConstructProcess(), G4TheRayTracer::CreateBitMap(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), G4PhysListUtil::FindCaptureProcess(), G4VHadronPhysics::FindCaptureProcess(), G4VHadronPhysics::FindElasticProcess(), G4PhysListUtil::FindFissionProcess(), G4VHadronPhysics::FindFissionProcess(), G4PhysListUtil::FindInelasticProcess(), G4VHadronPhysics::FindInelasticProcess(), G4EmCalculator::FindProcess(), G4ErrorTrackLengthTarget::G4ErrorTrackLengthTarget(), G4HadronElasticPhysics::GetElasticProcess(), G4BiasingProcessInterface::IsFirstPostStepDoItInterface(), G4BiasingProcessInterface::IsFirstPostStepGPILInterface(), G4BiasingProcessInterface::IsLastPostStepDoItInterface(), G4BiasingProcessInterface::IsLastPostStepGPILInterface(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4VUserPhysicsList::PreparePhysicsTable(), G4PhysicsListHelper::RegisterProcess(), G4BiasingProcessInterface::ReorderBiasingVectorAsGPIL(), G4VUserPhysicsList::RetrievePhysicsTable(), G4WorkerRunManagerKernel::SetupShadowProcess(), G4RunManagerKernel::SetupShadowProcess(), and G4VUserPhysicsList::StorePhysicsTable().
Field Documentation
pProcVector
G4ProcVector* G4ProcessVector::pProcVector protected
Definition at line 101 of file G4ProcessVector.hh.
Referenced by G4ProcessVector(), operator=(), and ~G4ProcessVector().
The documentation for this class was generated from the following files:
source/processes/management/include/G4ProcessVector.hh
source/processes/management/src/G4ProcessVector.cc