Geant4: source/g3tog4/src/G3NegVolPars.cc File Reference
G3NegVolPars.cc File Reference
#include "globals.hh"
#include "G3VolTable.hh"
#include "G4VSolid.hh"
#include "G3toG4.hh"
#include <cmath>
Functions
G4bool G3CalcParamsFn (G4double *rpar, G4int npar, G4double *rparm, G4String shape, G4String shapem)
G4bool G3NegVolPars (G4double pars[], G4int *nparpt, G3VolTableEntry *vte, G3VolTableEntry *mvte, const char routine[])
Function Documentation
G3CalcParamsFn()
G4bool G3CalcParamsFn (G4double * rpar, G4int npar, G4double * rparm, G4String shape, G4String shapem)
Definition at line 36 of file G3NegVolPars.cc.
Referenced by G3NegVolPars().
G3NegVolPars()
G4bool G3NegVolPars (G4double pars[], G4int * nparpt, G3VolTableEntry * vte, G3VolTableEntry * mvte, const char routine[])
Definition at line 180 of file G3NegVolPars.cc.
Referenced by G4CreateCloneVTE(), and G4ProcessDaughters().