Geant4: G4VAttValueFilter Class Reference
G4VAttValueFilter Class Reference abstract
#include <G4VAttValueFilter.hh>
Public Member Functions
G4VAttValueFilter (const G4String &name="G4AttValueFilter")
virtual ~G4VAttValueFilter ()
virtual G4bool Accept (const G4AttValue &) const =0
virtual G4bool GetValidElement (const G4AttValue &, G4String &) const =0
virtual void PrintAll (std::ostream &ostr) const =0
virtual void Reset ()=0
virtual void LoadIntervalElement (const G4String &)=0
virtual void LoadSingleValueElement (const G4String &)=0
Public Member Functions inherited from G4VFilter< G4AttValue >
G4VFilter (const G4String &name)
virtual ~G4VFilter ()
G4String Name () const
G4String GetName () const
Additional Inherited Members
Public Types inherited from G4VFilter< G4AttValue >
typedef G4AttValue Type
Detailed Description
Definition at line 40 of file G4VAttValueFilter.hh.
Constructor & Destructor Documentation
G4VAttValueFilter()
G4VAttValueFilter::G4VAttValueFilter (const G4String & name = "G4AttValueFilter") inline
Definition at line 45 of file G4VAttValueFilter.hh.
~G4VAttValueFilter()
virtual G4VAttValueFilter::~G4VAttValueFilter () inline virtual
Definition at line 49 of file G4VAttValueFilter.hh.
Member Function Documentation
Accept()
virtual G4bool G4VAttValueFilter::Accept (const G4AttValue &) const pure virtual
Implements G4VFilter< G4AttValue >.
Implemented in G4AttValueFilterT< T, ConversionErrorPolicy >.
GetValidElement()
virtual G4bool G4VAttValueFilter::GetValidElement (const G4AttValue & , G4String &) const pure virtual
Implemented in G4AttValueFilterT< T, ConversionErrorPolicy >.
Referenced by G4TrajectoryDrawByAttribute::Draw().
LoadIntervalElement()
virtual void G4VAttValueFilter::LoadIntervalElement (const G4String &) pure virtual
Implemented in G4AttValueFilterT< T, ConversionErrorPolicy >.
Referenced by G4TrajectoryDrawByAttribute::Draw().
LoadSingleValueElement()
virtual void G4VAttValueFilter::LoadSingleValueElement (const G4String &) pure virtual
Implemented in G4AttValueFilterT< T, ConversionErrorPolicy >.
Referenced by G4TrajectoryDrawByAttribute::Draw().
PrintAll()
virtual void G4VAttValueFilter::PrintAll (std::ostream & ostr) const pure virtual
Implements G4VFilter< G4AttValue >.
Implemented in G4AttValueFilterT< T, ConversionErrorPolicy >.
Reset()
virtual void G4VAttValueFilter::Reset () pure virtual
Implements G4VFilter< G4AttValue >.
Implemented in G4AttValueFilterT< T, ConversionErrorPolicy >.
The documentation for this class was generated from the following file:
source/visualization/modeling/include/G4VAttValueFilter.hh