Geant4: G4GDMLReadParamvol Class Reference
G4GDMLReadParamvol Class Reference
#include <G4GDMLReadParamvol.hh>
Public Member Functions
virtual void ParamvolRead (const xercesc::DOMElement *const, G4LogicalVolume *)
virtual void Paramvol_contentRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLReadSetup
G4String GetSetup (const G4String &)
virtual void SetupRead (const xercesc::DOMElement *const element)
Public Member Functions inherited from G4GDMLReadSolids
G4VSolid * GetSolid (const G4String &) const
G4SurfaceProperty * GetSurfaceProperty (const G4String &) const
virtual void SolidsRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLReadMaterials
G4Element * GetElement (const G4String &, G4bool verbose=true) const
G4Isotope * GetIsotope (const G4String &, G4bool verbose=true) const
G4Material * GetMaterial (const G4String &, G4bool verbose=true) const
virtual void MaterialsRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLReadDefine
G4bool IsValidID (const G4String &) const
G4double GetConstant (const G4String &)
G4double GetVariable (const G4String &)
G4double GetQuantity (const G4String &)
G4ThreeVector GetPosition (const G4String &)
G4ThreeVector GetRotation (const G4String &)
G4ThreeVector GetScale (const G4String &)
G4GDMLMatrix GetMatrix (const G4String &)
virtual void DefineRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLRead
virtual void Volume_contentRead (const xercesc::DOMElement *const)=0
virtual void StructureRead (const xercesc::DOMElement *const)=0
virtual void ExtensionRead (const xercesc::DOMElement *const)
virtual void UserinfoRead (const xercesc::DOMElement *const)
virtual G4LogicalVolume * GetVolume (const G4String &) const =0
void Read (const G4String &, G4bool validation, G4bool isModule, G4bool strip=true)
void StripNames () const
void StripName (G4String &) const
void OverlapCheck (G4bool)
const G4GDMLAuxListType * GetAuxList () const
Protected Member Functions
G4GDMLReadParamvol ()
virtual ~G4GDMLReadParamvol ()
void Box_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Trd_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Trap_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Tube_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Cone_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Sphere_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Orb_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Torus_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Ellipsoid_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Para_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Hype_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Polycone_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Polyhedra_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void ParameterisedRead (const xercesc::DOMElement *const)
void ParametersRead (const xercesc::DOMElement *const)
Protected Member Functions inherited from G4GDMLReadSetup
G4GDMLReadSetup ()
virtual ~G4GDMLReadSetup ()
Protected Member Functions inherited from G4GDMLReadSolids
G4GDMLReadSolids ()
virtual ~G4GDMLReadSolids ()
void BooleanRead (const xercesc::DOMElement *const, const BooleanOp)
void BoxRead (const xercesc::DOMElement *const)
void ConeRead (const xercesc::DOMElement *const)
void ElconeRead (const xercesc::DOMElement *const)
void EllipsoidRead (const xercesc::DOMElement *const)
void EltubeRead (const xercesc::DOMElement *const)
void XtruRead (const xercesc::DOMElement *const)
void HypeRead (const xercesc::DOMElement *const)
void MultiUnionNodeRead (const xercesc::DOMElement *const, G4MultiUnion *const)
void MultiUnionRead (const xercesc::DOMElement *const)
void OrbRead (const xercesc::DOMElement *const)
void ParaRead (const xercesc::DOMElement *const)
void ParaboloidRead (const xercesc::DOMElement *const)
void PolyconeRead (const xercesc::DOMElement *const)
void GenericPolyconeRead (const xercesc::DOMElement *const)
void PolyhedraRead (const xercesc::DOMElement *const)
void GenericPolyhedraRead (const xercesc::DOMElement *const)
G4QuadrangularFacet * QuadrangularRead (const xercesc::DOMElement *const)
void ReflectedSolidRead (const xercesc::DOMElement *const)
void ScaledSolidRead (const xercesc::DOMElement *const)
G4ExtrudedSolid::ZSection SectionRead (const xercesc::DOMElement *const, G4double)
void SphereRead (const xercesc::DOMElement *const)
void TessellatedRead (const xercesc::DOMElement *const)
void TetRead (const xercesc::DOMElement *const)
void TorusRead (const xercesc::DOMElement *const)
void GenTrapRead (const xercesc::DOMElement *const)
void TrapRead (const xercesc::DOMElement *const)
void TrdRead (const xercesc::DOMElement *const)
void TubeRead (const xercesc::DOMElement *const)
void CutTubeRead (const xercesc::DOMElement *const)
void TwistedboxRead (const xercesc::DOMElement *const)
void TwistedtrapRead (const xercesc::DOMElement *const)
void TwistedtrdRead (const xercesc::DOMElement *const)
void TwistedtubsRead (const xercesc::DOMElement *const)
G4TriangularFacet * TriangularRead (const xercesc::DOMElement *const)
G4TwoVector TwoDimVertexRead (const xercesc::DOMElement *const, G4double)
zplaneType ZplaneRead (const xercesc::DOMElement *const)
rzPointType RZPointRead (const xercesc::DOMElement *const)
void OpticalSurfaceRead (const xercesc::DOMElement *const)
void PropertyRead (const xercesc::DOMElement *const, G4OpticalSurface *)
Protected Member Functions inherited from G4GDMLReadMaterials
G4GDMLReadMaterials ()
virtual ~G4GDMLReadMaterials ()
G4double AtomRead (const xercesc::DOMElement *const)
G4int CompositeRead (const xercesc::DOMElement *const, G4String &)
G4double DRead (const xercesc::DOMElement *const)
G4double PRead (const xercesc::DOMElement *const)
G4double TRead (const xercesc::DOMElement *const)
G4double MEERead (const xercesc::DOMElement *const)
void ElementRead (const xercesc::DOMElement *const)
G4double FractionRead (const xercesc::DOMElement *const, G4String &)
void IsotopeRead (const xercesc::DOMElement *const)
void MaterialRead (const xercesc::DOMElement *const)
void MixtureRead (const xercesc::DOMElement *const, G4Element *)
void MixtureRead (const xercesc::DOMElement *const, G4Material *)
void PropertyRead (const xercesc::DOMElement *const, G4Material *)
Protected Member Functions inherited from G4GDMLReadDefine
G4GDMLReadDefine ()
virtual ~G4GDMLReadDefine ()
G4RotationMatrix GetRotationMatrix (const G4ThreeVector &)
void VectorRead (const xercesc::DOMElement *const, G4ThreeVector &)
G4String RefRead (const xercesc::DOMElement *const)
void ConstantRead (const xercesc::DOMElement *const)
void MatrixRead (const xercesc::DOMElement *const)
void PositionRead (const xercesc::DOMElement *const)
void RotationRead (const xercesc::DOMElement *const)
void ScaleRead (const xercesc::DOMElement *const)
void VariableRead (const xercesc::DOMElement *const)
void QuantityRead (const xercesc::DOMElement *const)
void ExpressionRead (const xercesc::DOMElement *const)
Protected Member Functions inherited from G4GDMLRead
G4GDMLRead ()
virtual ~G4GDMLRead ()
G4String Transcode (const XMLCh *const)
G4String GenerateName (const G4String &name, G4bool strip=false)
G4String Strip (const G4String &) const
void GeneratePhysvolName (const G4String &, G4VPhysicalVolume *)
void LoopRead (const xercesc::DOMElement *const, void(G4GDMLRead::*)(const xercesc::DOMElement *const))
G4GDMLAuxStructType AuxiliaryRead (const xercesc::DOMElement *const auxElem)
Protected Attributes
G4GDMLParameterisation * parameterisation
Protected Attributes inherited from G4GDMLReadSetup
std::map< G4String, G4String > setupMap
Protected Attributes inherited from G4GDMLReadDefine
std::map< G4String, G4double > quantityMap
std::map< G4String, G4ThreeVector > positionMap
std::map< G4String, G4ThreeVector > rotationMap
std::map< G4String, G4ThreeVector > scaleMap
std::map< G4String, G4GDMLMatrix > matrixMap
Protected Attributes inherited from G4GDMLRead
G4GDMLEvaluator eval
G4bool validate
G4bool check
G4bool dostrip
Detailed Description
Definition at line 47 of file G4GDMLReadParamvol.hh.
Constructor & Destructor Documentation
G4GDMLReadParamvol()
G4GDMLReadParamvol::G4GDMLReadParamvol () protected
Definition at line 41 of file G4GDMLReadParamvol.cc.
~G4GDMLReadParamvol()
G4GDMLReadParamvol::~G4GDMLReadParamvol () protected virtual
Definition at line 46 of file G4GDMLReadParamvol.cc.
Member Function Documentation
Box_dimensionsRead()
void G4GDMLReadParamvol::Box_dimensionsRead (const xercesc::DOMElement * const element, G4GDMLParameterisation::PARAMETER & parameter) protected
Definition at line 51 of file G4GDMLReadParamvol.cc.
Referenced by ParametersRead().
Cone_dimensionsRead()
void G4GDMLReadParamvol::Cone_dimensionsRead (const xercesc::DOMElement * const element, G4GDMLParameterisation::PARAMETER & parameter) protected
Definition at line 279 of file G4GDMLReadParamvol.cc.
Referenced by ParametersRead().
Ellipsoid_dimensionsRead()
void G4GDMLReadParamvol::Ellipsoid_dimensionsRead (const xercesc::DOMElement * const element, G4GDMLParameterisation::PARAMETER & parameter) protected
Definition at line 507 of file G4GDMLReadParamvol.cc.
Referenced by ParametersRead().
Hype_dimensionsRead()
void G4GDMLReadParamvol::Hype_dimensionsRead (const xercesc::DOMElement * const element, G4GDMLParameterisation::PARAMETER & parameter) protected
Definition at line 622 of file G4GDMLReadParamvol.cc.
Referenced by ParametersRead().
Orb_dimensionsRead()
void G4GDMLReadParamvol::Orb_dimensionsRead (const xercesc::DOMElement * const element, G4GDMLParameterisation::PARAMETER & parameter) protected
Definition at line 408 of file G4GDMLReadParamvol.cc.
Referenced by ParametersRead().
Para_dimensionsRead()
void G4GDMLReadParamvol::Para_dimensionsRead (const xercesc::DOMElement * const element, G4GDMLParameterisation::PARAMETER & parameter) protected
Definition at line 559 of file G4GDMLReadParamvol.cc.
Referenced by ParametersRead().
ParameterisedRead()
void G4GDMLReadParamvol::ParameterisedRead (const xercesc::DOMElement * const element) protected
Definition at line 906 of file G4GDMLReadParamvol.cc.
Referenced by Paramvol_contentRead().
ParametersRead()
void G4GDMLReadParamvol::ParametersRead (const xercesc::DOMElement * const element) protected
Definition at line 846 of file G4GDMLReadParamvol.cc.
Referenced by ParameterisedRead().
Paramvol_contentRead()
void G4GDMLReadParamvol::Paramvol_contentRead (const xercesc::DOMElement * const element) virtual
Implements G4GDMLRead.
Definition at line 959 of file G4GDMLReadParamvol.cc.
Referenced by ParamvolRead().
ParamvolRead()
void G4GDMLReadParamvol::ParamvolRead (const xercesc::DOMElement * const element, G4LogicalVolume * mother) virtual
Definition at line 981 of file G4GDMLReadParamvol.cc.
Referenced by G4GDMLReadStructure::Volume_contentRead().
Polycone_dimensionsRead()
void G4GDMLReadParamvol::Polycone_dimensionsRead (const xercesc::DOMElement * const element, G4GDMLParameterisation::PARAMETER & parameter) protected
Definition at line 682 of file G4GDMLReadParamvol.cc.
Referenced by ParametersRead().
Polyhedra_dimensionsRead()
void G4GDMLReadParamvol::Polyhedra_dimensionsRead (const xercesc::DOMElement * const element, G4GDMLParameterisation::PARAMETER & parameter) protected
Definition at line 763 of file G4GDMLReadParamvol.cc.
Referenced by ParametersRead().
Sphere_dimensionsRead()
void G4GDMLReadParamvol::Sphere_dimensionsRead (const xercesc::DOMElement * const element, G4GDMLParameterisation::PARAMETER & parameter) protected
Definition at line 345 of file G4GDMLReadParamvol.cc.
Referenced by ParametersRead().
Torus_dimensionsRead()
void G4GDMLReadParamvol::Torus_dimensionsRead (const xercesc::DOMElement * const element, G4GDMLParameterisation::PARAMETER & parameter) protected
Definition at line 447 of file G4GDMLReadParamvol.cc.
Referenced by ParametersRead().
Trap_dimensionsRead()
void G4GDMLReadParamvol::Trap_dimensionsRead (const xercesc::DOMElement * const element, G4GDMLParameterisation::PARAMETER & parameter) protected
Definition at line 141 of file G4GDMLReadParamvol.cc.
Referenced by ParametersRead().
Trd_dimensionsRead()
void G4GDMLReadParamvol::Trd_dimensionsRead (const xercesc::DOMElement * const element, G4GDMLParameterisation::PARAMETER & parameter) protected
Definition at line 94 of file G4GDMLReadParamvol.cc.
Referenced by ParametersRead().
Tube_dimensionsRead()
void G4GDMLReadParamvol::Tube_dimensionsRead (const xercesc::DOMElement * const element, G4GDMLParameterisation::PARAMETER & parameter) protected
Definition at line 219 of file G4GDMLReadParamvol.cc.
Referenced by ParametersRead().
Field Documentation
parameterisation
G4GDMLParameterisation* G4GDMLReadParamvol::parameterisation protected
Definition at line 93 of file G4GDMLReadParamvol.hh.
Referenced by ParametersRead(), and ParamvolRead().
The documentation for this class was generated from the following files:
source/persistency/gdml/include/G4GDMLReadParamvol.hh
source/persistency/gdml/src/G4GDMLReadParamvol.cc