Geant4: G4Tubs Class Reference
G4Tubs Class Reference
#include <G4Tubs.hh>
Public Member Functions
G4Tubs (const G4String &pName, G4double pRMin, G4double pRMax, G4double pDz, G4double pSPhi, G4double pDPhi)
virtual ~G4Tubs ()
G4double GetInnerRadius () const
G4double GetOuterRadius () const
G4double GetZHalfLength () const
G4double GetStartPhiAngle () const
G4double GetDeltaPhiAngle () const
G4double GetSinStartPhi () const
G4double GetCosStartPhi () const
G4double GetSinEndPhi () const
G4double GetCosEndPhi () const
void SetInnerRadius (G4double newRMin)
void SetOuterRadius (G4double newRMax)
void SetZHalfLength (G4double newDz)
void SetStartPhiAngle (G4double newSPhi, G4bool trig=true)
void SetDeltaPhiAngle (G4double newDPhi)
G4double GetCubicVolume ()
G4double GetSurfaceArea ()
void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pmin, G4double &pmax) const
EInside Inside (const G4ThreeVector &p) const
G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=G4bool(false), G4bool *validNorm=0, G4ThreeVector *n=0) const
G4double DistanceToOut (const G4ThreeVector &p) const
G4GeometryType GetEntityType () const
G4ThreeVector GetPointOnSurface () const
G4VSolid * Clone () const
std::ostream & StreamInfo (std::ostream &os) const
void DescribeYourselfTo (G4VGraphicsScene &scene) const
G4Polyhedron * CreatePolyhedron () const
G4Tubs (__void__ &)
G4Tubs (const G4Tubs &rhs)
G4Tubs & operator= (const G4Tubs &rhs)
G4double GetRMin () const
G4double GetRMax () const
G4double GetDz () const
G4double GetSPhi () const
G4double GetDPhi () const
Public Member Functions inherited from G4CSGSolid
G4CSGSolid (const G4String &pName)
virtual ~G4CSGSolid ()
virtual G4Polyhedron * GetPolyhedron () const
G4CSGSolid (__void__ &)
G4CSGSolid (const G4CSGSolid &rhs)
G4CSGSolid & operator= (const G4CSGSolid &rhs)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
void DumpInfo () const
virtual G4VisExtent GetExtent () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Protected Types
enum ESide {
kNull, kRMin, kRMax, kSPhi,
kEPhi, kPZ, kMZ
}
enum ENorm {
kNRMin, kNRMax, kNSPhi, kNEPhi,
kNZ
}
Protected Member Functions
void Initialize ()
void CheckSPhiAngle (G4double sPhi)
void CheckDPhiAngle (G4double dPhi)
void CheckPhiAngles (G4double sPhi, G4double dPhi)
void InitializeTrigonometry ()
virtual G4ThreeVector ApproxSurfaceNormal (const G4ThreeVector &p) const
Protected Member Functions inherited from G4CSGSolid
G4double GetRadiusInRing (G4double rmin, G4double rmax) const
Protected Member Functions inherited from G4VSolid
void CalculateClippedPolygonExtent (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipCrossSection (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipBetweenSections (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipPolygon (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis) const
Protected Attributes
G4double kRadTolerance
G4double kAngTolerance
G4double fRMin
G4double fRMax
G4double fDz
G4double fSPhi
G4double fDPhi
G4double sinCPhi
G4double cosCPhi
G4double cosHDPhiOT
G4double cosHDPhiIT
G4double sinSPhi
G4double cosSPhi
G4double sinEPhi
G4double cosEPhi
G4bool fPhiFullTube
G4double halfCarTolerance
G4double halfRadTolerance
G4double halfAngTolerance
Protected Attributes inherited from G4CSGSolid
G4double fCubicVolume
G4double fSurfaceArea
G4bool fRebuildPolyhedron
G4Polyhedron * fpPolyhedron
Protected Attributes inherited from G4VSolid
G4double kCarTolerance
Detailed Description
Definition at line 84 of file G4Tubs.hh.
Member Enumeration Documentation
ENorm
enum G4Tubs::ENorm protected
Enumerator
kNRMin
kNRMax
kNSPhi
kNEPhi
kNZ
Definition at line 210 of file G4Tubs.hh.
ESide
enum G4Tubs::ESide protected
Enumerator
kNull
kRMin
kRMax
kSPhi
kEPhi
kPZ
kMZ
Definition at line 206 of file G4Tubs.hh.
Constructor & Destructor Documentation
G4Tubs() [1/3]
G4Tubs::G4Tubs (const G4String & pName, G4double pRMin, G4double pRMax, G4double pDz, G4double pSPhi, G4double pDPhi)
Definition at line 88 of file G4Tubs.cc.
Referenced by Clone().
~G4Tubs()
G4Tubs::~G4Tubs () virtual
Definition at line 141 of file G4Tubs.cc.
G4Tubs() [2/3]
G4Tubs::G4Tubs (__void__ & a)
Definition at line 127 of file G4Tubs.cc.
G4Tubs() [3/3]
G4Tubs::G4Tubs (const G4Tubs & rhs)
Definition at line 149 of file G4Tubs.cc.
Member Function Documentation
ApproxSurfaceNormal()
G4ThreeVector G4Tubs::ApproxSurfaceNormal (const G4ThreeVector & p) const protected virtual
Definition at line 622 of file G4Tubs.cc.
Referenced by SurfaceNormal().
BoundingLimits()
void G4Tubs::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 211 of file G4Tubs.cc.
Referenced by CalculateExtent().
CalculateExtent()
G4bool G4Tubs::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pmin, G4double & pmax) const virtual
Implements G4VSolid.
Definition at line 254 of file G4Tubs.cc.
CheckDPhiAngle()
void G4Tubs::CheckDPhiAngle (G4double dPhi) inline protected
CheckPhiAngles()
void G4Tubs::CheckPhiAngles (G4double sPhi, G4double dPhi) inline protected
Referenced by G4Tubs().
CheckSPhiAngle()
void G4Tubs::CheckSPhiAngle (G4double sPhi) inline protected
Clone()
G4VSolid * G4Tubs::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 1660 of file G4Tubs.cc.
ComputeDimensions()
void G4Tubs::ComputeDimensions (G4VPVParameterisation * p, const G4int n, const G4VPhysicalVolume * pRep) virtual
Reimplemented from G4VSolid.
Definition at line 200 of file G4Tubs.cc.
CreatePolyhedron()
G4Polyhedron * G4Tubs::CreatePolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 1767 of file G4Tubs.cc.
Referenced by G4GMocrenFileSceneHandler::AddSolid(), and G4ArrowModel::G4ArrowModel().
DescribeYourselfTo()
void G4Tubs::DescribeYourselfTo (G4VGraphicsScene & scene) const virtual
Implements G4VSolid.
Definition at line 1762 of file G4Tubs.cc.
DistanceToIn() [1/2]
G4double G4Tubs::DistanceToIn (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 1130 of file G4Tubs.cc.
DistanceToIn() [2/2]
G4double G4Tubs::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Implements G4VSolid.
Definition at line 754 of file G4Tubs.cc.
DistanceToOut() [1/2]
G4double G4Tubs::DistanceToOut (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 1591 of file G4Tubs.cc.
DistanceToOut() [2/2]
G4double G4Tubs::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcNorm = G4bool(false), G4bool * validNorm = 0, G4ThreeVector * n = 0) const virtual
Implements G4VSolid.
Definition at line 1174 of file G4Tubs.cc.
GetCosEndPhi()
G4double G4Tubs::GetCosEndPhi () const inline
Referenced by BoundingLimits(), and CalculateExtent().
GetCosStartPhi()
G4double G4Tubs::GetCosStartPhi () const inline
Referenced by BoundingLimits(), and CalculateExtent().
GetCubicVolume()
G4double G4Tubs::GetCubicVolume () inline virtual
Reimplemented from G4VSolid.
GetDeltaPhiAngle()
G4double G4Tubs::GetDeltaPhiAngle () const inline
Referenced by G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationTubsRho::ComputeDimensions(), G4ParameterisationTubsZ::ComputeDimensions(), export_G4Tubs(), G4ParameterisationTubsPhi::G4ParameterisationTubsPhi(), G4ParameterisationTubsPhi::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), G4GDMLWriteParamvol::Tube_dimensionsWrite(), and G4GDMLWriteSolids::TubeWrite().
GetDPhi()
G4double G4Tubs::GetDPhi () const inline
Referenced by export_G4Tubs().
GetDz()
G4double G4Tubs::GetDz () const inline
Referenced by export_G4Tubs().
GetEntityType()
G4GeometryType G4Tubs::GetEntityType () const virtual
Implements G4VSolid.
Definition at line 1651 of file G4Tubs.cc.
GetInnerRadius()
G4double G4Tubs::GetInnerRadius () const inline
Referenced by G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationTubsRho::ComputeDimensions(), G4ParameterisationTubsPhi::ComputeDimensions(), G4ParameterisationTubsZ::ComputeDimensions(), export_G4Tubs(), G4ParameterisationTubsRho::G4ParameterisationTubsRho(), G4ParameterisationTubsRho::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4PSCylinderSurfaceFlux::IsSelectedSurface(), G4PSCylinderSurfaceCurrent::IsSelectedSurface(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), G4GDMLWriteParamvol::Tube_dimensionsWrite(), and G4GDMLWriteSolids::TubeWrite().
GetOuterRadius()
G4double G4Tubs::GetOuterRadius () const inline
Referenced by G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationTubsPhi::ComputeDimensions(), G4ParameterisationTubsZ::ComputeDimensions(), export_G4Tubs(), G4ParameterisationTubsRho::G4ParameterisationTubsRho(), FFPrimaryGeneratorAction::GeneratePrimaries(), G4ParameterisationTubsRho::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Tube_dimensionsWrite(), and G4GDMLWriteSolids::TubeWrite().
GetPointOnSurface()
G4ThreeVector G4Tubs::GetPointOnSurface () const virtual
Reimplemented from G4VSolid.
Definition at line 1692 of file G4Tubs.cc.
GetRMax()
G4double G4Tubs::GetRMax () const inline
Referenced by export_G4Tubs().
GetRMin()
G4double G4Tubs::GetRMin () const inline
Referenced by export_G4Tubs().
GetSinEndPhi()
G4double G4Tubs::GetSinEndPhi () const inline
Referenced by BoundingLimits(), and CalculateExtent().
GetSinStartPhi()
G4double G4Tubs::GetSinStartPhi () const inline
Referenced by BoundingLimits(), and CalculateExtent().
GetSPhi()
G4double G4Tubs::GetSPhi () const inline
Referenced by export_G4Tubs().
GetStartPhiAngle()
G4double G4Tubs::GetStartPhiAngle () const inline
Referenced by G4tgbVolume::BuildSolidForDivision(), G4ParameterisationTubsRho::ComputeDimensions(), G4ParameterisationTubsPhi::ComputeDimensions(), G4ParameterisationTubsZ::ComputeDimensions(), export_G4Tubs(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Tube_dimensionsWrite(), and G4GDMLWriteSolids::TubeWrite().
GetSurfaceArea()
G4double G4Tubs::GetSurfaceArea () inline virtual
Reimplemented from G4VSolid.
GetZHalfLength()
G4double G4Tubs::GetZHalfLength () const inline
Referenced by G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationTubsRho::ComputeDimensions(), G4ParameterisationTubsPhi::ComputeDimensions(), G4ParameterisationTubsZ::ComputeTransformation(), UltraDetectorConstruction::ConstructUVscope(), export_G4Tubs(), G4ParameterisationTubsZ::G4ParameterisationTubsZ(), FFPrimaryGeneratorAction::GeneratePrimaries(), G4ParameterisationTubsZ::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4PSCylinderSurfaceFlux::IsSelectedSurface(), G4PSCylinderSurfaceCurrent::IsSelectedSurface(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), G4GDMLWriteParamvol::Tube_dimensionsWrite(), and G4GDMLWriteSolids::TubeWrite().
Initialize()
void G4Tubs::Initialize () inline protected
InitializeTrigonometry()
void G4Tubs::InitializeTrigonometry () inline protected
Inside()
EInside G4Tubs::Inside (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 364 of file G4Tubs.cc.
Referenced by DistanceToOut().
operator=()
G4Tubs & G4Tubs::operator= (const G4Tubs & rhs)
Definition at line 168 of file G4Tubs.cc.
SetDeltaPhiAngle()
void G4Tubs::SetDeltaPhiAngle (G4double newDPhi) inline
Referenced by ExN04CalorimeterParametrisation::ComputeDimensions(), ExN04TrackerParametrisation::ComputeDimensions(), RE05CalorimeterParametrisation::ComputeDimensions(), RE05TrackerParametrisation::ComputeDimensions(), RE01CalorimeterParametrisation::ComputeDimensions(), RE01TrackerParametrisation::ComputeDimensions(), B2bChamberParameterisation::ComputeDimensions(), G4ParameterisationTubsRho::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), NeuronLoadDataFile::ComputeDimensions(), G4ParameterisationTubsPhi::ComputeDimensions(), G4ParameterisationTubsZ::ComputeDimensions(), and export_G4Tubs().
SetInnerRadius()
void G4Tubs::SetInnerRadius (G4double newRMin) inline
Referenced by ExN04CalorimeterParametrisation::ComputeDimensions(), ExN04TrackerParametrisation::ComputeDimensions(), RE05CalorimeterParametrisation::ComputeDimensions(), RE05TrackerParametrisation::ComputeDimensions(), RE01CalorimeterParametrisation::ComputeDimensions(), RE01TrackerParametrisation::ComputeDimensions(), B2bChamberParameterisation::ComputeDimensions(), G4ParameterisationTubsRho::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), NeuronLoadDataFile::ComputeDimensions(), G4ParameterisationTubsPhi::ComputeDimensions(), G4ParameterisationTubsZ::ComputeDimensions(), and export_G4Tubs().
SetOuterRadius()
void G4Tubs::SetOuterRadius (G4double newRMax) inline
Referenced by ExN04CalorimeterParametrisation::ComputeDimensions(), ExN04TrackerParametrisation::ComputeDimensions(), RE01TrackerParametrisation::ComputeDimensions(), RE05CalorimeterParametrisation::ComputeDimensions(), RE05TrackerParametrisation::ComputeDimensions(), RE01CalorimeterParametrisation::ComputeDimensions(), B2bChamberParameterisation::ComputeDimensions(), G4ParameterisationTubsRho::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), NeuronLoadDataFile::ComputeDimensions(), G4ParameterisationTubsPhi::ComputeDimensions(), G4ParameterisationTubsZ::ComputeDimensions(), export_G4Tubs(), and DetectorConstruction::UpdateParameters().
SetStartPhiAngle()
void G4Tubs::SetStartPhiAngle (G4double newSPhi, G4bool trig = true) inline
Referenced by ExN04CalorimeterParametrisation::ComputeDimensions(), ExN04TrackerParametrisation::ComputeDimensions(), RE05CalorimeterParametrisation::ComputeDimensions(), RE05TrackerParametrisation::ComputeDimensions(), RE01CalorimeterParametrisation::ComputeDimensions(), RE01TrackerParametrisation::ComputeDimensions(), B2bChamberParameterisation::ComputeDimensions(), G4ParameterisationTubsRho::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), NeuronLoadDataFile::ComputeDimensions(), G4ParameterisationTubsPhi::ComputeDimensions(), G4ParameterisationTubsZ::ComputeDimensions(), and export_G4Tubs().
SetZHalfLength()
void G4Tubs::SetZHalfLength (G4double newDz) inline
Referenced by ExN04CalorimeterParametrisation::ComputeDimensions(), ExN04TrackerParametrisation::ComputeDimensions(), RE01CalorimeterParametrisation::ComputeDimensions(), RE01TrackerParametrisation::ComputeDimensions(), RE05CalorimeterParametrisation::ComputeDimensions(), RE05TrackerParametrisation::ComputeDimensions(), B2bChamberParameterisation::ComputeDimensions(), G4ParameterisationTubsRho::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), NeuronLoadDataFile::ComputeDimensions(), G4ParameterisationTubsPhi::ComputeDimensions(), G4ParameterisationTubsZ::ComputeDimensions(), export_G4Tubs(), ElectronBenchmarkDetector::SetPrimFoilThickness(), and DetectorConstruction::UpdateParameters().
StreamInfo()
std::ostream & G4Tubs::StreamInfo (std::ostream & os) const virtual
Reimplemented from G4CSGSolid.
Definition at line 1669 of file G4Tubs.cc.
SurfaceNormal()
G4ThreeVector G4Tubs::SurfaceNormal (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 531 of file G4Tubs.cc.
Field Documentation
cosCPhi
G4double G4Tubs::cosCPhi protected
Definition at line 220 of file G4Tubs.hh.
Referenced by DistanceToIn(), DistanceToOut(), and operator=().
cosEPhi
G4double G4Tubs::cosEPhi protected
Definition at line 220 of file G4Tubs.hh.
Referenced by DistanceToIn(), DistanceToOut(), and operator=().
cosHDPhiIT
G4double G4Tubs::cosHDPhiIT protected
Definition at line 220 of file G4Tubs.hh.
Referenced by DistanceToIn(), and operator=().
cosHDPhiOT
G4double G4Tubs::cosHDPhiOT protected
Definition at line 220 of file G4Tubs.hh.
Referenced by operator=().
cosSPhi
G4double G4Tubs::cosSPhi protected
Definition at line 220 of file G4Tubs.hh.
Referenced by DistanceToIn(), DistanceToOut(), and operator=().
fDPhi
G4double G4Tubs::fDPhi protected
Definition at line 216 of file G4Tubs.hh.
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
fDz
G4double G4Tubs::fDz protected
Definition at line 216 of file G4Tubs.hh.
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
fPhiFullTube
G4bool G4Tubs::fPhiFullTube protected
Definition at line 225 of file G4Tubs.hh.
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), Inside(), operator=(), and SurfaceNormal().
fRMax
G4double G4Tubs::fRMax protected
Definition at line 216 of file G4Tubs.hh.
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
fRMin
G4double G4Tubs::fRMin protected
Definition at line 216 of file G4Tubs.hh.
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
fSPhi
G4double G4Tubs::fSPhi protected
Definition at line 216 of file G4Tubs.hh.
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToOut(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
halfAngTolerance
G4double G4Tubs::halfAngTolerance protected
Definition at line 229 of file G4Tubs.hh.
Referenced by DistanceToOut(), G4Tubs(), Inside(), operator=(), and SurfaceNormal().
halfCarTolerance
G4double G4Tubs::halfCarTolerance protected
Definition at line 229 of file G4Tubs.hh.
Referenced by DistanceToIn(), DistanceToOut(), G4Tubs(), Inside(), operator=(), and SurfaceNormal().
halfRadTolerance
G4double G4Tubs::halfRadTolerance protected
Definition at line 229 of file G4Tubs.hh.
Referenced by DistanceToIn(), G4Tubs(), Inside(), and operator=().
kAngTolerance
G4double G4Tubs::kAngTolerance protected
Definition at line 212 of file G4Tubs.hh.
Referenced by G4Tubs(), and operator=().
kRadTolerance
G4double G4Tubs::kRadTolerance protected
Definition at line 212 of file G4Tubs.hh.
Referenced by DistanceToIn(), DistanceToOut(), G4Tubs(), and operator=().
sinCPhi
G4double G4Tubs::sinCPhi protected
Definition at line 220 of file G4Tubs.hh.
Referenced by DistanceToIn(), DistanceToOut(), and operator=().
sinEPhi
G4double G4Tubs::sinEPhi protected
Definition at line 220 of file G4Tubs.hh.
Referenced by DistanceToIn(), DistanceToOut(), and operator=().
sinSPhi
G4double G4Tubs::sinSPhi protected
Definition at line 220 of file G4Tubs.hh.
Referenced by DistanceToIn(), DistanceToOut(), and operator=().
The documentation for this class was generated from the following files:
source/geometry/solids/CSG/include/G4Tubs.hh
source/geometry/solids/CSG/src/G4Tubs.cc