Geant4: G4CacheReference< VALTYPE > Class Template Reference
G4CacheReference< VALTYPE > Class Template Reference
#include <G4CacheDetails.hh>
Public Member Functions
void Initialize (unsigned int id)
void Destroy (unsigned int id, G4bool last)
VALTYPE & GetCache (unsigned int id) const
Private Types
typedef std::vector< VALTYPE * > cache_container
Static Private Member Functions
static cache_container *& cache ()
Detailed Description
template<class VALTYPE>
class G4CacheReference< VALTYPE >
Definition at line 73 of file G4CacheDetails.hh.
Member Typedef Documentation
cache_container
template<class VALTYPE> typedef std::vector<VALTYPE*> G4CacheReference< VALTYPE >::cache_container private
Definition at line 89 of file G4CacheDetails.hh.
Member Function Documentation
cache()
template<class V > G4CacheReference< V * >::cache_container *& G4CacheReference< V >::cache () static private
Definition at line 208 of file G4CacheDetails.hh.
Referenced by G4CacheReference< G4double >::Destroy(), G4CacheReference< G4double >::GetCache(), and G4CacheReference< G4double >::Initialize().
Destroy()
template<class V > void G4CacheReference< V >::Destroy (unsigned int id, G4bool last) inline
Definition at line 161 of file G4CacheDetails.hh.
GetCache()
template<class V > V *& G4CacheReference< V >::GetCache (unsigned int id) const inline
Definition at line 201 of file G4CacheDetails.hh.
Referenced by G4Cache< F02ElectricFieldSetup * >::GetCache().
Initialize()
template<class V > void G4CacheReference< V >::Initialize (unsigned int id) inline
Definition at line 140 of file G4CacheDetails.hh.
Referenced by G4Cache< F02ElectricFieldSetup * >::GetCache().
The documentation for this class was generated from the following file:
source/global/management/include/G4CacheDetails.hh