Geant4: G4Polymarker Class Reference
G4Polymarker Class Reference
#include <G4Polymarker.hh>
Public Types
enum MarkerType { dots, circles, squares }
Public Types inherited from G4VMarker
enum FillStyle { noFill, hashed, filled }
enum SizeType { none, world, screen }
Public Types inherited from G4Point3DList
typedef std::vector< G4Point3D >::iterator iterator
Public Member Functions
G4Polymarker ()
G4Polymarker (const G4VMarker &)
virtual ~G4Polymarker ()
MarkerType GetMarkerType () const
void SetMarkerType (MarkerType)
Public Member Functions inherited from G4VMarker
G4VMarker ()
G4VMarker (const G4VMarker &)
G4VMarker (const G4Point3D &position)
virtual ~G4VMarker ()
G4VMarker & operator= (const G4VMarker &)
G4bool operator!= (const G4VMarker &) const
G4Point3D GetPosition () const
SizeType GetSizeType () const
G4double GetWorldSize () const
G4double GetWorldDiameter () const
G4double GetWorldRadius () const
G4double GetScreenSize () const
G4double GetScreenDiameter () const
G4double GetScreenRadius () const
FillStyle GetFillStyle () const
void SetPosition (const G4Point3D &)
void SetSize (SizeType, G4double)
void SetDiameter (SizeType, G4double)
void SetRadius (SizeType, G4double)
void SetWorldSize (G4double)
void SetWorldDiameter (G4double)
void SetWorldRadius (G4double)
void SetScreenSize (G4double)
void SetScreenDiameter (G4double)
void SetScreenRadius (G4double)
void SetFillStyle (FillStyle)
virtual const G4String & GetInfo () const
virtual void SetInfo (const G4String &info)
Public Member Functions inherited from G4Visible
G4Visible ()
G4Visible (const G4Visible &)
G4Visible (const G4VisAttributes *)
virtual ~G4Visible ()
G4Visible & operator= (const G4Visible &)
G4bool operator!= (const G4Visible &right) const
const G4VisAttributes * GetVisAttributes () const
void SetVisAttributes (const G4VisAttributes *)
void SetVisAttributes (const G4VisAttributes &)
Public Member Functions inherited from G4Point3DList
virtual ~G4Point3DList ()
Private Attributes
MarkerType fMarkerType
Friends
std::ostream & operator<< (std::ostream &os, const G4Polymarker &marker)
Additional Inherited Members
Protected Attributes inherited from G4Visible
const G4VisAttributes * fpVisAttributes
G4bool fAllocatedVisAttributes
Detailed Description
Definition at line 42 of file G4Polymarker.hh.
Member Enumeration Documentation
MarkerType
enum G4Polymarker::MarkerType
Enumerator
dots
circles
squares
Definition at line 47 of file G4Polymarker.hh.
Constructor & Destructor Documentation
G4Polymarker() [1/2]
G4Polymarker::G4Polymarker ()
Definition at line 33 of file G4Polymarker.cc.
G4Polymarker() [2/2]
G4Polymarker::G4Polymarker (const G4VMarker & marker)
Definition at line 37 of file G4Polymarker.cc.
~G4Polymarker()
G4Polymarker::~G4Polymarker () virtual
Definition at line 42 of file G4Polymarker.cc.
Member Function Documentation
GetMarkerType()
MarkerType G4Polymarker::GetMarkerType () const
Referenced by G4HepRepSceneHandler::AddPrimitive(), and G4VSceneHandler::AddPrimitive().
SetMarkerType()
void G4Polymarker::SetMarkerType (MarkerType)
Referenced by LXeTrajectory::DrawTrajectory(), G4TrajectoryDrawerUtils::DrawWithoutTime(), G4TrajectoryDrawerUtils::DrawWithTime(), and G4BlineEventAction::EndOfEventAction().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const G4Polymarker & marker) friend
Definition at line 44 of file G4Polymarker.cc.
Field Documentation
fMarkerType
MarkerType G4Polymarker::fMarkerType private
Definition at line 54 of file G4Polymarker.hh.
Referenced by operator<<().
The documentation for this class was generated from the following files:
source/graphics_reps/include/G4Polymarker.hh
source/graphics_reps/src/G4Polymarker.cc