Geant4: G4ConcreteMesonBaryonToResonance Class Reference
G4ConcreteMesonBaryonToResonance Class Reference
#include <G4ConcreteMesonBaryonToResonance.hh>
Public Member Functions
G4ConcreteMesonBaryonToResonance (const G4ParticleDefinition *aPrimary, const G4ParticleDefinition *bPriamry, const G4ParticleDefinition *aSecondary, const G4String &partWidthLabel)
virtual ~G4ConcreteMesonBaryonToResonance ()
virtual G4bool IsInCharge (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const std::vector< G4String > & GetListOfColliders (G4int) const
virtual G4String GetName () const
G4bool operator== (const G4ConcreteMesonBaryonToResonance &right) const
G4bool operator!= (const G4ConcreteMesonBaryonToResonance &right) const
Public Member Functions inherited from G4VAnnihilationCollision
G4VAnnihilationCollision ()
virtual ~G4VAnnihilationCollision ()
G4bool operator== (const G4VAnnihilationCollision &right) const
G4bool operator!= (const G4VAnnihilationCollision &right) const
virtual G4KineticTrackVector * FinalState (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const G4VAngularDistribution * GetAngularDistribution () const
Public Member Functions inherited from G4VCollision
G4VCollision ()
void establish_G4MT_TLS_G4VCollision ()
G4VCollision (void *s1, void *s2, void *s3, void *s4, void *s5, void *s6, void *s7)
virtual ~G4VCollision ()
G4bool operator== (const G4VCollision &right) const
G4bool operator!= (const G4VCollision &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual void Print () const
virtual void Print (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Protected Member Functions
virtual const G4VCrossSectionSource * GetCrossSectionSource () const
virtual const G4ParticleDefinition * GetOutgoingParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Protected Member Functions inherited from G4VCollision
G4int GetNumberOfPartons (const G4ParticleDefinition *aP) const
virtual const G4CollisionVector * GetComponents () const
Private Member Functions
G4ConcreteMesonBaryonToResonance (const G4ConcreteMesonBaryonToResonance &)
G4ConcreteMesonBaryonToResonance & operator= (const G4ConcreteMesonBaryonToResonance &)
Static Private Member Functions
static void InitialisePointers ()
static G4BaryonWidth & theBaryonWidth ()
static G4BaryonPartialWidth & theBaryonPartialWidth ()
static G4ParticleTypeConverter & myConv ()
Private Attributes
G4VCrossSectionSource * crossSectionSource
const G4ParticleDefinition * thePrimary1
const G4ParticleDefinition * thePrimary2
const G4ParticleDefinition * theSecondary
Static Private Attributes
static G4BaryonWidth * baryonWidth = nullptr
static G4BaryonPartialWidth * baryonPartialWidth = nullptr
static G4ParticleTypeConverter * particleTypeConverter = nullptr
Detailed Description
Definition at line 45 of file G4ConcreteMesonBaryonToResonance.hh.
Constructor & Destructor Documentation
G4ConcreteMesonBaryonToResonance() [1/2]
G4ConcreteMesonBaryonToResonance::G4ConcreteMesonBaryonToResonance (const G4ParticleDefinition * aPrimary, const G4ParticleDefinition * bPriamry, const G4ParticleDefinition * aSecondary, const G4String & partWidthLabel)
Definition at line 57 of file G4ConcreteMesonBaryonToResonance.cc.
~G4ConcreteMesonBaryonToResonance()
G4ConcreteMesonBaryonToResonance::~G4ConcreteMesonBaryonToResonance () virtual
Definition at line 70 of file G4ConcreteMesonBaryonToResonance.cc.
G4ConcreteMesonBaryonToResonance() [2/2]
G4ConcreteMesonBaryonToResonance::G4ConcreteMesonBaryonToResonance (const G4ConcreteMesonBaryonToResonance &) private
Member Function Documentation
GetCrossSectionSource()
virtual const G4VCrossSectionSource* G4ConcreteMesonBaryonToResonance::GetCrossSectionSource () const inline protected virtual
Implements G4VCollision.
Definition at line 81 of file G4ConcreteMesonBaryonToResonance.hh.
GetListOfColliders()
virtual const std::vector<G4String>& G4ConcreteMesonBaryonToResonance::GetListOfColliders (G4int) const inline virtual
Implements G4VCollision.
Definition at line 60 of file G4ConcreteMesonBaryonToResonance.hh.
GetName()
virtual G4String G4ConcreteMesonBaryonToResonance::GetName (void) const inline virtual
Implements G4VCollision.
Definition at line 67 of file G4ConcreteMesonBaryonToResonance.hh.
GetOutgoingParticle()
const G4ParticleDefinition * G4ConcreteMesonBaryonToResonance::GetOutgoingParticle (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const protected virtual
Implements G4VAnnihilationCollision.
Definition at line 102 of file G4ConcreteMesonBaryonToResonance.cc.
InitialisePointers()
void G4ConcreteMesonBaryonToResonance::InitialisePointers () static private
Definition at line 75 of file G4ConcreteMesonBaryonToResonance.cc.
Referenced by G4ConcreteMesonBaryonToResonance(), myConv(), theBaryonPartialWidth(), and theBaryonWidth().
IsInCharge()
G4bool G4ConcreteMesonBaryonToResonance::IsInCharge (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VCollision.
Definition at line 92 of file G4ConcreteMesonBaryonToResonance.cc.
myConv()
G4ParticleTypeConverter & G4ConcreteMesonBaryonToResonance::myConv () static private
Definition at line 51 of file G4ConcreteMesonBaryonToResonance.cc.
Referenced by GetOutgoingParticle(), and IsInCharge().
operator!=()
G4bool G4ConcreteMesonBaryonToResonance::operator!= (const G4ConcreteMesonBaryonToResonance & right) const
operator=()
G4ConcreteMesonBaryonToResonance& G4ConcreteMesonBaryonToResonance::operator= (const G4ConcreteMesonBaryonToResonance &) private
operator==()
G4bool G4ConcreteMesonBaryonToResonance::operator== (const G4ConcreteMesonBaryonToResonance & right) const
theBaryonPartialWidth()
G4BaryonPartialWidth & G4ConcreteMesonBaryonToResonance::theBaryonPartialWidth () static private
Definition at line 45 of file G4ConcreteMesonBaryonToResonance.cc.
Referenced by G4ConcreteMesonBaryonToResonance().
theBaryonWidth()
G4BaryonWidth & G4ConcreteMesonBaryonToResonance::theBaryonWidth () static private
Definition at line 39 of file G4ConcreteMesonBaryonToResonance.cc.
Referenced by G4ConcreteMesonBaryonToResonance().
Field Documentation
baryonPartialWidth
G4BaryonPartialWidth * G4ConcreteMesonBaryonToResonance::baryonPartialWidth = nullptr static private
Definition at line 101 of file G4ConcreteMesonBaryonToResonance.hh.
Referenced by InitialisePointers(), and theBaryonPartialWidth().
baryonWidth
G4BaryonWidth * G4ConcreteMesonBaryonToResonance::baryonWidth = nullptr static private
Definition at line 100 of file G4ConcreteMesonBaryonToResonance.hh.
Referenced by InitialisePointers(), and theBaryonWidth().
crossSectionSource
G4VCrossSectionSource* G4ConcreteMesonBaryonToResonance::crossSectionSource private
Definition at line 91 of file G4ConcreteMesonBaryonToResonance.hh.
Referenced by G4ConcreteMesonBaryonToResonance(), GetCrossSectionSource(), and ~G4ConcreteMesonBaryonToResonance().
particleTypeConverter
G4ParticleTypeConverter * G4ConcreteMesonBaryonToResonance::particleTypeConverter = nullptr static private
Definition at line 102 of file G4ConcreteMesonBaryonToResonance.hh.
Referenced by InitialisePointers(), and myConv().
thePrimary1
const G4ParticleDefinition* G4ConcreteMesonBaryonToResonance::thePrimary1 private
Definition at line 92 of file G4ConcreteMesonBaryonToResonance.hh.
Referenced by IsInCharge().
thePrimary2
const G4ParticleDefinition* G4ConcreteMesonBaryonToResonance::thePrimary2 private
Definition at line 93 of file G4ConcreteMesonBaryonToResonance.hh.
Referenced by IsInCharge().
theSecondary
const G4ParticleDefinition* G4ConcreteMesonBaryonToResonance::theSecondary private
Definition at line 94 of file G4ConcreteMesonBaryonToResonance.hh.
Referenced by GetOutgoingParticle().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/im_r_matrix/include/G4ConcreteMesonBaryonToResonance.hh
source/processes/hadronic/models/im_r_matrix/src/G4ConcreteMesonBaryonToResonance.cc