Geant4: G4EmDNAPhysicsActivator Class Reference
G4EmDNAPhysicsActivator Class Reference
#include <G4EmDNAPhysicsActivator.hh>
Public Member Functions
G4EmDNAPhysicsActivator (G4int ver=1)
virtual ~G4EmDNAPhysicsActivator ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Private Member Functions
void AddElectronModels0 (const G4String &region, G4LowECapture *ecap, G4bool emsc, G4double elowest, G4double elimel)
void AddProtonModels0 (const G4String &region, G4bool pmsc, G4double elimel, G4double pminbb, G4double pmax)
void AddHeliumModels0 (const G4String &region, G4bool a1msc, G4bool a2msc, G4double elimel, G4double pminbb, G4double pmax)
void AddGenericIonModels0 (const G4String &region, G4double pminbb)
void DeactivateNuclearStopping (G4ProcessManager *, G4double elimel)
G4bool HasMsc (G4ProcessManager *) const
G4bool IsVerbose () const
Private Attributes
G4int verbose
G4EmParameters * theParameters
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 40 of file G4EmDNAPhysicsActivator.hh.
Constructor & Destructor Documentation
G4EmDNAPhysicsActivator()
G4EmDNAPhysicsActivator::G4EmDNAPhysicsActivator (G4int ver = 1)
Definition at line 96 of file G4EmDNAPhysicsActivator.cc.
~G4EmDNAPhysicsActivator()
G4EmDNAPhysicsActivator::~G4EmDNAPhysicsActivator () virtual
Definition at line 104 of file G4EmDNAPhysicsActivator.cc.
Member Function Documentation
AddElectronModels0()
void G4EmDNAPhysicsActivator::AddElectronModels0 (const G4String & region, G4LowECapture * ecap, G4bool emsc, G4double elowest, G4double elimel) private
Definition at line 401 of file G4EmDNAPhysicsActivator.cc.
Referenced by ConstructProcess().
AddGenericIonModels0()
void G4EmDNAPhysicsActivator::AddGenericIonModels0 (const G4String & region, G4double pminbb) private
Definition at line 563 of file G4EmDNAPhysicsActivator.cc.
Referenced by ConstructProcess().
AddHeliumModels0()
void G4EmDNAPhysicsActivator::AddHeliumModels0 (const G4String & region, G4bool a1msc, G4bool a2msc, G4double elimel, G4double pminbb, G4double pmax) private
Definition at line 594 of file G4EmDNAPhysicsActivator.cc.
Referenced by ConstructProcess().
AddProtonModels0()
void G4EmDNAPhysicsActivator::AddProtonModels0 (const G4String & region, G4bool pmsc, G4double elimel, G4double pminbb, G4double pmax) private
Definition at line 481 of file G4EmDNAPhysicsActivator.cc.
Referenced by ConstructProcess().
ConstructParticle()
void G4EmDNAPhysicsActivator::ConstructParticle (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 114 of file G4EmDNAPhysicsActivator.cc.
ConstructProcess()
void G4EmDNAPhysicsActivator::ConstructProcess (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 143 of file G4EmDNAPhysicsActivator.cc.
DeactivateNuclearStopping()
void G4EmDNAPhysicsActivator::DeactivateNuclearStopping (G4ProcessManager * pman, G4double elimel) private
Definition at line 720 of file G4EmDNAPhysicsActivator.cc.
Referenced by ConstructProcess().
HasMsc()
G4bool G4EmDNAPhysicsActivator::HasMsc (G4ProcessManager * pman) const private
Definition at line 740 of file G4EmDNAPhysicsActivator.cc.
Referenced by ConstructProcess().
IsVerbose()
G4bool G4EmDNAPhysicsActivator::IsVerbose () const private
Definition at line 107 of file G4EmDNAPhysicsActivator.cc.
Referenced by AddHeliumModels0(), and ConstructProcess().
Field Documentation
theParameters
G4EmParameters* G4EmDNAPhysicsActivator::theParameters private
Definition at line 71 of file G4EmDNAPhysicsActivator.hh.
Referenced by AddElectronModels0(), AddGenericIonModels0(), AddHeliumModels0(), AddProtonModels0(), ConstructProcess(), and G4EmDNAPhysicsActivator().
verbose
G4int G4EmDNAPhysicsActivator::verbose private
Definition at line 70 of file G4EmDNAPhysicsActivator.hh.
Referenced by IsVerbose().
The documentation for this class was generated from the following files:
source/physics_lists/constructors/electromagnetic/include/G4EmDNAPhysicsActivator.hh
source/physics_lists/constructors/electromagnetic/src/G4EmDNAPhysicsActivator.cc