Geant4: G4VEvaporationChannel Class Reference
G4VEvaporationChannel Class Reference abstract
#include <G4VEvaporationChannel.hh>
Public Member Functions
G4VEvaporationChannel (const G4String &aName="")
virtual ~G4VEvaporationChannel ()
virtual G4double GetEmissionProbability (G4Fragment *theNucleus)=0
virtual void Initialise ()
virtual G4double GetLifeTime (G4Fragment *theNucleus)
virtual G4Fragment * EmittedFragment (G4Fragment *theNucleus)
virtual G4bool BreakUpChain (G4FragmentVector *theResult, G4Fragment *theNucleus)
G4FragmentVector * BreakUpFragment (G4Fragment *theNucleus)
virtual void Dump () const
virtual void SetICM (G4bool)
virtual void RDMForced (G4bool)
virtual G4double GetFinalLevelEnergy (G4int Z, G4int A, G4double energy)
virtual G4double GetUpperLevelEnergy (G4int Z, G4int A)
G4double GetMaxLevelEnergy (G4int Z, G4int A)
G4double GetNearestLevelEnergy (G4int Z, G4int A, G4double energy)
void SetPhotonEvaporation (G4VEvaporationChannel *p)
void SetOPTxs (G4int opt)
void UseSICB (G4bool use)
Protected Attributes
G4int OPTxs
G4bool useSICB
Private Member Functions
G4VEvaporationChannel (const G4VEvaporationChannel &right)=delete
const G4VEvaporationChannel & operator= (const G4VEvaporationChannel &right)=delete
G4bool operator== (const G4VEvaporationChannel &right) const =delete
G4bool operator!= (const G4VEvaporationChannel &right) const =delete
Private Attributes
G4VEvaporationChannel * photonEvaporation
Detailed Description
Definition at line 49 of file G4VEvaporationChannel.hh.
Constructor & Destructor Documentation
G4VEvaporationChannel() [1/2]
G4VEvaporationChannel::G4VEvaporationChannel (const G4String & aName = "") explicit
Definition at line 38 of file G4VEvaporationChannel.cc.
~G4VEvaporationChannel()
G4VEvaporationChannel::~G4VEvaporationChannel () virtual
Definition at line 42 of file G4VEvaporationChannel.cc.
G4VEvaporationChannel() [2/2]
G4VEvaporationChannel::G4VEvaporationChannel (const G4VEvaporationChannel & right) private delete
Member Function Documentation
BreakUpChain()
G4bool G4VEvaporationChannel::BreakUpChain (G4FragmentVector * theResult, G4Fragment * theNucleus) virtual
Reimplemented in G4PhotonEvaporation, and G4UnstableFragmentBreakUp.
Definition at line 75 of file G4VEvaporationChannel.cc.
Referenced by G4ExcitationHandler::BreakItUp(), and BreakUpFragment().
BreakUpFragment()
G4FragmentVector * G4VEvaporationChannel::BreakUpFragment (G4Fragment * theNucleus) inline
Definition at line 123 of file G4VEvaporationChannel.hh.
Referenced by G4NeutronRadCapture::ApplyYourself().
Dump()
void G4VEvaporationChannel::Dump () const virtual
Reimplemented in G4GEMChannelVI, and G4GEMChannel.
Definition at line 80 of file G4VEvaporationChannel.cc.
EmittedFragment()
G4Fragment * G4VEvaporationChannel::EmittedFragment (G4Fragment * theNucleus) virtual
Reimplemented in G4PhotonEvaporation, G4GEMChannelVI, G4EvaporationChannel, G4GEMChannel, and G4CompetitiveFission.
Definition at line 70 of file G4VEvaporationChannel.cc.
GetEmissionProbability()
virtual G4double G4VEvaporationChannel::GetEmissionProbability (G4Fragment * theNucleus) pure virtual
Implemented in G4PhotonEvaporation, G4GEMChannelVI, G4GEMChannel, G4CompetitiveFission, G4UnstableFragmentBreakUp, and G4EvaporationChannel.
GetFinalLevelEnergy()
G4double G4VEvaporationChannel::GetFinalLevelEnergy (G4int Z, G4int A, G4double energy) virtual
Reimplemented in G4PhotonEvaporation.
Definition at line 60 of file G4VEvaporationChannel.cc.
Referenced by GetNearestLevelEnergy().
GetLifeTime()
G4double G4VEvaporationChannel::GetLifeTime (G4Fragment * theNucleus) virtual
Definition at line 48 of file G4VEvaporationChannel.cc.
GetMaxLevelEnergy()
G4double G4VEvaporationChannel::GetMaxLevelEnergy (G4int Z, G4int A) inline
Definition at line 139 of file G4VEvaporationChannel.hh.
GetNearestLevelEnergy()
G4double G4VEvaporationChannel::GetNearestLevelEnergy (G4int Z, G4int A, G4double energy) inline
Definition at line 132 of file G4VEvaporationChannel.hh.
GetUpperLevelEnergy()
G4double G4VEvaporationChannel::GetUpperLevelEnergy (G4int Z, G4int A) virtual
Reimplemented in G4PhotonEvaporation.
Definition at line 65 of file G4VEvaporationChannel.cc.
Referenced by GetMaxLevelEnergy().
Initialise()
void G4VEvaporationChannel::Initialise () virtual
Reimplemented in G4PhotonEvaporation, G4GEMChannelVI, and G4EvaporationChannel.
Definition at line 45 of file G4VEvaporationChannel.cc.
Referenced by G4EvaporationChannel::Initialise(), and G4NeutronRadCapture::InitialiseModel().
operator!=()
G4bool G4VEvaporationChannel::operator!= (const G4VEvaporationChannel & right) const private delete
operator=()
const G4VEvaporationChannel& G4VEvaporationChannel::operator= (const G4VEvaporationChannel & right) private delete
operator==()
G4bool G4VEvaporationChannel::operator== (const G4VEvaporationChannel & right) const private delete
RDMForced()
void G4VEvaporationChannel::RDMForced (G4bool) virtual
Reimplemented in G4PhotonEvaporation.
Definition at line 56 of file G4VEvaporationChannel.cc.
SetICM()
void G4VEvaporationChannel::SetICM (G4bool) virtual
Reimplemented in G4PhotonEvaporation.
Definition at line 53 of file G4VEvaporationChannel.cc.
Referenced by G4NeutronRadCapture::InitialiseModel().
SetOPTxs()
void G4VEvaporationChannel::SetOPTxs (G4int opt) inline
Definition at line 151 of file G4VEvaporationChannel.hh.
SetPhotonEvaporation()
void G4VEvaporationChannel::SetPhotonEvaporation (G4VEvaporationChannel * p) inline
Definition at line 146 of file G4VEvaporationChannel.hh.
UseSICB()
void G4VEvaporationChannel::UseSICB (G4bool use) inline
Definition at line 154 of file G4VEvaporationChannel.hh.
Field Documentation
OPTxs
G4int G4VEvaporationChannel::OPTxs protected
Definition at line 108 of file G4VEvaporationChannel.hh.
Referenced by G4EvaporationChannel::GetEmissionProbability().
photonEvaporation
G4VEvaporationChannel* G4VEvaporationChannel::photonEvaporation private
Definition at line 119 of file G4VEvaporationChannel.hh.
Referenced by GetMaxLevelEnergy(), GetNearestLevelEnergy(), and SetPhotonEvaporation().
useSICB
G4bool G4VEvaporationChannel::useSICB protected
Definition at line 109 of file G4VEvaporationChannel.hh.
The documentation for this class was generated from the following files:
source/processes/hadronic/models/de_excitation/management/include/G4VEvaporationChannel.hh
source/processes/hadronic/models/de_excitation/management/src/G4VEvaporationChannel.cc