Geant4: G4NistMaterialBuilder Class Reference
G4NistMaterialBuilder Class Reference
#include <G4NistMaterialBuilder.hh>
Public Member Functions
G4NistMaterialBuilder (G4NistElementBuilder *, G4int verb=0)
~G4NistMaterialBuilder ()
G4Material * FindMaterial (const G4String &name) const
G4Material * FindOrBuildMaterial (const G4String &name, G4bool isotopes=true, G4bool warning=true)
G4Material * FindSimpleMaterial (G4int Z) const
G4Material * FindOrBuildSimpleMaterial (G4int Z, G4bool warning)
G4Material * ConstructNewMaterial (const G4String &name, const std::vector< G4String > &elm, const std::vector< G4int > &nbAtoms, G4double dens, G4bool isotopes=true, G4State state=kStateSolid, G4double temp=NTP_Temperature, G4double pressure=CLHEP::STP_Pressure)
G4Material * ConstructNewMaterial (const G4String &name, const std::vector< G4String > &elm, const std::vector< G4double > &weight, G4double dens, G4bool isotopes=true, G4State state=kStateSolid, G4double temp=NTP_Temperature, G4double pressure=CLHEP::STP_Pressure)
G4Material * ConstructNewGasMaterial (const G4String &name, const G4String &nameDB, G4double temp, G4double pres, G4bool isotopes=true)
G4Material * ConstructNewIdealGasMaterial (const G4String &name, const std::vector< G4String > &elm, const std::vector< G4int > &nbAtoms, G4bool isotopes=true, G4double temp=NTP_Temperature, G4double pressure=CLHEP::STP_Pressure)
void SetVerbose (G4int val)
void ListMaterials (const G4String &) const
void ListNistSimpleMaterials () const
void ListNistCompoundMaterials () const
void ListHepMaterials () const
void ListSpaceMaterials () const
void ListBioChemicalMaterials () const
const std::vector< G4String > & GetMaterialNames () const
G4double GetMeanIonisationEnergy (G4int index) const
G4double GetNominalDensity (G4int index) const
Private Member Functions
void Initialise ()
void NistSimpleMaterials ()
void NistCompoundMaterials ()
void NistCompoundMaterials2 ()
void HepAndNuclearMaterials ()
void SpaceMaterials ()
void BioChemicalMaterials ()
Build biochemical materials used in G4DNA Applications.
void AddMaterial (const G4String &nameMat, G4double dens, G4int Z=0, G4double pot=0.0, G4int ncomp=1, G4State=kStateSolid, G4bool stp=true)
void AddGas (const G4String &nameMat, G4double T, G4double P)
void AddElementByWeightFraction (G4int Z, G4double)
void AddElementByAtomCount (G4int Z, G4int)
void AddElementByWeightFraction (const G4String &name, G4double)
void AddElementByAtomCount (const G4String &name, G4int)
G4Material * BuildNistMaterial (const G4String &matname, G4bool warning)
G4Material * BuildMaterial (G4int idx)
void DumpElm (G4int) const
void DumpMix (G4int) const
Private Attributes
G4NistElementBuilder * elmBuilder
G4int verbose
G4int nMaterials
G4int nComponents
G4int nCurrent
G4int nElementary
G4int nNIST
G4int nHEP
G4int nSpace
std::vector< G4String > names
std::vector< G4String > chFormulas
std::vector< G4double > densities
std::vector< G4double > ionPotentials
std::vector< G4State > states
std::vector< G4double > fractions
std::vector< G4bool > atomCount
std::vector< G4int > components
std::vector< G4int > indexes
std::vector< G4int > elements
std::vector< G4int > matIndex
std::vector< G4bool > STP
std::vector< G4int > idxGas
std::vector< G4double > gasTemperature
std::vector< G4double > gasPressure
Detailed Description
Definition at line 69 of file G4NistMaterialBuilder.hh.
Constructor & Destructor Documentation
G4NistMaterialBuilder()
G4NistMaterialBuilder::G4NistMaterialBuilder (G4NistElementBuilder * eb, G4int verb = 0)
Definition at line 85 of file G4NistMaterialBuilder.cc.
~G4NistMaterialBuilder()
G4NistMaterialBuilder::~G4NistMaterialBuilder ()
Definition at line 97 of file G4NistMaterialBuilder.cc.
Member Function Documentation
AddElementByAtomCount() [1/2]
void G4NistMaterialBuilder::AddElementByAtomCount (const G4String & name, G4int nb) private
Definition at line 696 of file G4NistMaterialBuilder.cc.
AddElementByAtomCount() [2/2]
void G4NistMaterialBuilder::AddElementByAtomCount (G4int Z, G4int nb) private
Definition at line 687 of file G4NistMaterialBuilder.cc.
Referenced by BioChemicalMaterials(), ConstructNewIdealGasMaterial(), ConstructNewMaterial(), HepAndNuclearMaterials(), NistCompoundMaterials(), NistCompoundMaterials2(), NistSimpleMaterials(), and SpaceMaterials().
AddElementByWeightFraction() [1/2]
void G4NistMaterialBuilder::AddElementByWeightFraction (const G4String & name, G4double w) private
Definition at line 678 of file G4NistMaterialBuilder.cc.
AddElementByWeightFraction() [2/2]
void G4NistMaterialBuilder::AddElementByWeightFraction (G4int Z, G4double w) private
Definition at line 657 of file G4NistMaterialBuilder.cc.
Referenced by AddElementByAtomCount(), AddElementByWeightFraction(), ConstructNewMaterial(), HepAndNuclearMaterials(), NistCompoundMaterials(), and NistCompoundMaterials2().
AddGas()
void G4NistMaterialBuilder::AddGas (const G4String & nameMat, G4double T, G4double P) private
Definition at line 640 of file G4NistMaterialBuilder.cc.
Referenced by ConstructNewIdealGasMaterial(), ConstructNewMaterial(), and HepAndNuclearMaterials().
AddMaterial()
void G4NistMaterialBuilder::AddMaterial (const G4String & nameMat, G4double dens, G4int Z = 0, G4double pot = 0.0, G4int ncomp = 1, G4State state = kStateSolid, G4bool stp = true) private
Definition at line 457 of file G4NistMaterialBuilder.cc.
Referenced by BioChemicalMaterials(), ConstructNewIdealGasMaterial(), ConstructNewMaterial(), HepAndNuclearMaterials(), NistCompoundMaterials(), NistCompoundMaterials2(), NistSimpleMaterials(), and SpaceMaterials().
BioChemicalMaterials()
void G4NistMaterialBuilder::BioChemicalMaterials () private
Build biochemical materials used in G4DNA Applications.
Materials are defined in bonded and unbonded forms according to the following schema: G4_MATERIAL: Molecule in its free state G4_DNA_MATERIAL: Molecule, considering atoms lost in bonding
Definition at line 1939 of file G4NistMaterialBuilder.cc.
Referenced by Initialise().
BuildMaterial()
G4Material * G4NistMaterialBuilder::BuildMaterial (G4int idx) private
Definition at line 171 of file G4NistMaterialBuilder.cc.
Referenced by BuildNistMaterial(), ConstructNewIdealGasMaterial(), and ConstructNewMaterial().
BuildNistMaterial()
G4Material * G4NistMaterialBuilder::BuildNistMaterial (const G4String & matname, G4bool warning) private
Definition at line 122 of file G4NistMaterialBuilder.cc.
Referenced by FindOrBuildMaterial(), and FindOrBuildSimpleMaterial().
ConstructNewGasMaterial()
G4Material * G4NistMaterialBuilder::ConstructNewGasMaterial (const G4String & name, const G4String & nameDB, G4double temp, G4double pres, G4bool isotopes = true)
Definition at line 347 of file G4NistMaterialBuilder.cc.
Referenced by G4NistManager::ConstructNewGasMaterial().
ConstructNewIdealGasMaterial()
G4Material * G4NistMaterialBuilder::ConstructNewIdealGasMaterial (const G4String & name, const std::vector< G4String > & elm, const std::vector< G4int > & nbAtoms, G4bool isotopes = true, G4double temp = NTP_Temperature, G4double pressure = CLHEP::STP_Pressure)
Definition at line 394 of file G4NistMaterialBuilder.cc.
Referenced by G4NistManager::ConstructNewIdealGasMaterial().
ConstructNewMaterial() [1/2]
G4Material * G4NistMaterialBuilder::ConstructNewMaterial (const G4String & name, const std::vector< G4String > & elm, const std::vector< G4double > & weight, G4double dens, G4bool isotopes = true, G4State state = kStateSolid, G4double temp = NTP_Temperature, G4double pressure = CLHEP::STP_Pressure)
Definition at line 297 of file G4NistMaterialBuilder.cc.
ConstructNewMaterial() [2/2]
G4Material * G4NistMaterialBuilder::ConstructNewMaterial (const G4String & name, const std::vector< G4String > & elm, const std::vector< G4int > & nbAtoms, G4double dens, G4bool isotopes = true, G4State state = kStateSolid, G4double temp = NTP_Temperature, G4double pressure = CLHEP::STP_Pressure)
Definition at line 246 of file G4NistMaterialBuilder.cc.
Referenced by G4NistManager::ConstructNewMaterial().
DumpElm()
void G4NistMaterialBuilder::DumpElm (G4int i) const private
Definition at line 607 of file G4NistMaterialBuilder.cc.
Referenced by ListNistSimpleMaterials().
DumpMix()
void G4NistMaterialBuilder::DumpMix (G4int i) const private
Definition at line 618 of file G4NistMaterialBuilder.cc.
Referenced by ListBioChemicalMaterials(), ListHepMaterials(), ListNistCompoundMaterials(), and ListSpaceMaterials().
FindMaterial()
G4Material * G4NistMaterialBuilder::FindMaterial (const G4String & name) const inline
Definition at line 247 of file G4NistMaterialBuilder.hh.
Referenced by G4NistManager::FindMaterial(), FindOrBuildMaterial(), and FindSimpleMaterial().
FindOrBuildMaterial()
G4Material * G4NistMaterialBuilder::FindOrBuildMaterial (const G4String & name, G4bool isotopes = true, G4bool warning = true)
Definition at line 102 of file G4NistMaterialBuilder.cc.
Referenced by ConstructNewGasMaterial(), ConstructNewIdealGasMaterial(), ConstructNewMaterial(), and G4NistManager::FindOrBuildMaterial().
FindOrBuildSimpleMaterial()
G4Material * G4NistMaterialBuilder::FindOrBuildSimpleMaterial (G4int Z, G4bool warning)
Definition at line 160 of file G4NistMaterialBuilder.cc.
Referenced by G4NistManager::FindOrBuildSimpleMaterial().
FindSimpleMaterial()
G4Material * G4NistMaterialBuilder::FindSimpleMaterial (G4int Z) const inline
Definition at line 262 of file G4NistMaterialBuilder.hh.
Referenced by FindOrBuildSimpleMaterial(), and G4NistManager::FindSimpleMaterial().
GetMaterialNames()
const std::vector< G4String > & G4NistMaterialBuilder::GetMaterialNames () const inline
Definition at line 229 of file G4NistMaterialBuilder.hh.
Referenced by G4NistManager::GetNistMaterialNames().
GetMeanIonisationEnergy()
G4double G4NistMaterialBuilder::GetMeanIonisationEnergy (G4int index) const inline
Definition at line 235 of file G4NistMaterialBuilder.hh.
Referenced by G4NistManager::GetMeanIonisationEnergy().
GetNominalDensity()
G4double G4NistMaterialBuilder::GetNominalDensity (G4int index) const inline
Definition at line 241 of file G4NistMaterialBuilder.hh.
Referenced by G4NistManager::GetNominalDensity().
HepAndNuclearMaterials()
void G4NistMaterialBuilder::HepAndNuclearMaterials () private
Definition at line 1846 of file G4NistMaterialBuilder.cc.
Referenced by Initialise().
Initialise()
void G4NistMaterialBuilder::Initialise () private
Definition at line 708 of file G4NistMaterialBuilder.cc.
Referenced by G4NistMaterialBuilder().
ListBioChemicalMaterials()
void G4NistMaterialBuilder::ListBioChemicalMaterials () const
Definition at line 594 of file G4NistMaterialBuilder.cc.
Referenced by ListMaterials().
ListHepMaterials()
void G4NistMaterialBuilder::ListHepMaterials () const
Definition at line 570 of file G4NistMaterialBuilder.cc.
Referenced by ListMaterials().
ListMaterials()
void G4NistMaterialBuilder::ListMaterials (const G4String & mnam) const
Definition at line 522 of file G4NistMaterialBuilder.cc.
Referenced by Initialise(), and G4NistManager::ListMaterials().
ListNistCompoundMaterials()
void G4NistMaterialBuilder::ListNistCompoundMaterials () const
Definition at line 557 of file G4NistMaterialBuilder.cc.
Referenced by ListMaterials().
ListNistSimpleMaterials()
void G4NistMaterialBuilder::ListNistSimpleMaterials () const
Definition at line 545 of file G4NistMaterialBuilder.cc.
Referenced by ListMaterials().
ListSpaceMaterials()
void G4NistMaterialBuilder::ListSpaceMaterials () const
Definition at line 582 of file G4NistMaterialBuilder.cc.
Referenced by ListMaterials().
NistCompoundMaterials()
void G4NistMaterialBuilder::NistCompoundMaterials () private
Definition at line 838 of file G4NistMaterialBuilder.cc.
Referenced by Initialise().
NistCompoundMaterials2()
void G4NistMaterialBuilder::NistCompoundMaterials2 () private
Definition at line 1343 of file G4NistMaterialBuilder.cc.
Referenced by Initialise().
NistSimpleMaterials()
void G4NistMaterialBuilder::NistSimpleMaterials () private
Definition at line 725 of file G4NistMaterialBuilder.cc.
Referenced by Initialise().
SetVerbose()
void G4NistMaterialBuilder::SetVerbose (G4int val)
Definition at line 514 of file G4NistMaterialBuilder.cc.
Referenced by G4NistManager::SetVerbose().
SpaceMaterials()
void G4NistMaterialBuilder::SpaceMaterials () private
Definition at line 1907 of file G4NistMaterialBuilder.cc.
Referenced by Initialise().
Field Documentation
atomCount
std::vector<G4bool> G4NistMaterialBuilder::atomCount private
Definition at line 211 of file G4NistMaterialBuilder.hh.
Referenced by AddElementByAtomCount(), AddElementByWeightFraction(), AddMaterial(), and BuildMaterial().
chFormulas
std::vector<G4String> G4NistMaterialBuilder::chFormulas private
Definition at line 205 of file G4NistMaterialBuilder.hh.
Referenced by AddMaterial(), BuildMaterial(), DumpMix(), HepAndNuclearMaterials(), NistCompoundMaterials(), NistCompoundMaterials2(), and NistSimpleMaterials().
components
std::vector<G4int> G4NistMaterialBuilder::components private
Definition at line 212 of file G4NistMaterialBuilder.hh.
Referenced by AddElementByWeightFraction(), AddMaterial(), BuildMaterial(), and DumpMix().
densities
std::vector<G4double> G4NistMaterialBuilder::densities private
Definition at line 207 of file G4NistMaterialBuilder.hh.
Referenced by AddMaterial(), BuildMaterial(), DumpElm(), DumpMix(), and GetNominalDensity().
elements
std::vector<G4int> G4NistMaterialBuilder::elements private
Definition at line 214 of file G4NistMaterialBuilder.hh.
Referenced by AddElementByWeightFraction(), AddMaterial(), BuildMaterial(), and DumpMix().
elmBuilder
G4NistElementBuilder* G4NistMaterialBuilder::elmBuilder private
Definition at line 193 of file G4NistMaterialBuilder.hh.
Referenced by AddElementByAtomCount(), AddElementByWeightFraction(), BuildMaterial(), ConstructNewIdealGasMaterial(), ConstructNewMaterial(), and SetVerbose().
fractions
std::vector<G4double> G4NistMaterialBuilder::fractions private
Definition at line 210 of file G4NistMaterialBuilder.hh.
Referenced by AddElementByWeightFraction(), AddMaterial(), BuildMaterial(), and DumpMix().
gasPressure
std::vector<G4double> G4NistMaterialBuilder::gasPressure private
Definition at line 220 of file G4NistMaterialBuilder.hh.
Referenced by AddGas(), and BuildMaterial().
gasTemperature
std::vector<G4double> G4NistMaterialBuilder::gasTemperature private
Definition at line 219 of file G4NistMaterialBuilder.hh.
Referenced by AddGas(), and BuildMaterial().
idxGas
std::vector<G4int> G4NistMaterialBuilder::idxGas private
Definition at line 218 of file G4NistMaterialBuilder.hh.
Referenced by AddGas(), and BuildMaterial().
indexes
std::vector<G4int> G4NistMaterialBuilder::indexes private
Definition at line 213 of file G4NistMaterialBuilder.hh.
Referenced by AddElementByWeightFraction(), AddMaterial(), BuildMaterial(), and DumpMix().
ionPotentials
std::vector<G4double> G4NistMaterialBuilder::ionPotentials private
Definition at line 208 of file G4NistMaterialBuilder.hh.
Referenced by AddMaterial(), BuildMaterial(), DumpElm(), DumpMix(), and GetMeanIonisationEnergy().
matIndex
std::vector<G4int> G4NistMaterialBuilder::matIndex private
Definition at line 215 of file G4NistMaterialBuilder.hh.
Referenced by AddMaterial(), BuildMaterial(), and BuildNistMaterial().
names
std::vector<G4String> G4NistMaterialBuilder::names private
Definition at line 204 of file G4NistMaterialBuilder.hh.
Referenced by AddGas(), AddMaterial(), BuildMaterial(), BuildNistMaterial(), DumpElm(), DumpMix(), FindOrBuildSimpleMaterial(), FindSimpleMaterial(), and GetMaterialNames().
nComponents
G4int G4NistMaterialBuilder::nComponents private
Definition at line 197 of file G4NistMaterialBuilder.hh.
Referenced by AddElementByWeightFraction(), and AddMaterial().
nCurrent
G4int G4NistMaterialBuilder::nCurrent private
Definition at line 198 of file G4NistMaterialBuilder.hh.
Referenced by AddElementByWeightFraction(), and AddMaterial().
nElementary
G4int G4NistMaterialBuilder::nElementary private
Definition at line 199 of file G4NistMaterialBuilder.hh.
Referenced by FindSimpleMaterial(), ListNistCompoundMaterials(), ListNistSimpleMaterials(), and NistSimpleMaterials().
nHEP
G4int G4NistMaterialBuilder::nHEP private
Definition at line 201 of file G4NistMaterialBuilder.hh.
Referenced by HepAndNuclearMaterials(), ListHepMaterials(), and ListSpaceMaterials().
nMaterials
G4int G4NistMaterialBuilder::nMaterials private
Definition at line 196 of file G4NistMaterialBuilder.hh.
Referenced by AddElementByAtomCount(), AddElementByWeightFraction(), AddGas(), AddMaterial(), BuildMaterial(), BuildNistMaterial(), ConstructNewIdealGasMaterial(), ConstructNewMaterial(), GetMeanIonisationEnergy(), GetNominalDensity(), HepAndNuclearMaterials(), ListBioChemicalMaterials(), NistCompoundMaterials(), NistCompoundMaterials2(), NistSimpleMaterials(), and SpaceMaterials().
nNIST
G4int G4NistMaterialBuilder::nNIST private
Definition at line 200 of file G4NistMaterialBuilder.hh.
Referenced by ListHepMaterials(), ListNistCompoundMaterials(), and NistCompoundMaterials2().
nSpace
G4int G4NistMaterialBuilder::nSpace private
Definition at line 202 of file G4NistMaterialBuilder.hh.
Referenced by ListBioChemicalMaterials(), ListSpaceMaterials(), and SpaceMaterials().
states
std::vector<G4State> G4NistMaterialBuilder::states private
Definition at line 209 of file G4NistMaterialBuilder.hh.
Referenced by AddMaterial(), and BuildMaterial().
STP
std::vector<G4bool> G4NistMaterialBuilder::STP private
Definition at line 216 of file G4NistMaterialBuilder.hh.
Referenced by AddMaterial().
verbose
G4int G4NistMaterialBuilder::verbose private
Definition at line 195 of file G4NistMaterialBuilder.hh.
Referenced by AddMaterial(), BuildMaterial(), BuildNistMaterial(), ConstructNewGasMaterial(), FindOrBuildMaterial(), Initialise(), and SetVerbose().
The documentation for this class was generated from the following files:
source/materials/include/G4NistMaterialBuilder.hh
source/materials/src/G4NistMaterialBuilder.cc