Geant4: G4VDNAReactionModel Class Reference
G4VDNAReactionModel Class Reference abstract
G4VDNAReactionModel is an interface used by the G4DNAMolecularReaction process.
#include <G4VDNAReactionModel.hh>
Public Member Functions
G4VDNAReactionModel ()
G4VDNAReactionModel (const G4VDNAReactionModel &)
virtual ~G4VDNAReactionModel ()
virtual void Initialise (G4MolecularConfiguration *, const G4Track &)
This macro is defined in AddClone_def.
virtual void InitialiseToPrint (G4MolecularConfiguration *)=0
virtual G4double GetReactionRadius (G4MolecularConfiguration *, G4MolecularConfiguration *)=0
virtual G4double GetReactionRadius (const int)=0
virtual G4bool FindReaction (const G4Track &, const G4Track &, const G4double, G4double &, const G4bool)=0
void SetReactionTable (const G4DNAMolecularReactionTable *)
const G4DNAMolecularReactionTable * GetReactionTable ()
Protected Member Functions
G4VDNAReactionModel & operator= (const G4VDNAReactionModel &)
Protected Attributes
const G4DNAMolecularReactionTable * fReactionTable
Detailed Description
G4VDNAReactionModel is an interface used by the G4DNAMolecularReaction process.
It defines how the reaction radius should be calculated and whether two molecules can indeed react.
Definition at line 63 of file G4VDNAReactionModel.hh.
Constructor & Destructor Documentation
G4VDNAReactionModel() [1/2]
G4VDNAReactionModel::G4VDNAReactionModel ()
Definition at line 29 of file G4VDNAReactionModel.cc.
G4VDNAReactionModel() [2/2]
G4VDNAReactionModel::G4VDNAReactionModel (const G4VDNAReactionModel & right)
Definition at line 34 of file G4VDNAReactionModel.cc.
~G4VDNAReactionModel()
G4VDNAReactionModel::~G4VDNAReactionModel () virtual
Definition at line 39 of file G4VDNAReactionModel.cc.
Member Function Documentation
FindReaction()
virtual G4bool G4VDNAReactionModel::FindReaction (const G4Track & , const G4Track & , const G4double, G4double & , const G4bool) pure virtual
Implemented in G4DNASmoluchowskiReactionModel.
Referenced by G4DNAMolecularReaction::TestReactibility().
GetReactionRadius() [1/2]
virtual G4double G4VDNAReactionModel::GetReactionRadius (const int) pure virtual
Implemented in G4DNASmoluchowskiReactionModel.
GetReactionRadius() [2/2]
virtual G4double G4VDNAReactionModel::GetReactionRadius (G4MolecularConfiguration * , G4MolecularConfiguration *) pure virtual
Implemented in G4DNASmoluchowskiReactionModel.
Referenced by G4DNAMoleculeEncounterStepper::CalculateStep(), G4DNAMolecularReactionTable::PrintTable(), and G4DNAMolecularReaction::TestReactibility().
GetReactionTable()
const G4DNAMolecularReactionTable * G4VDNAReactionModel::GetReactionTable () inline
Definition at line 96 of file G4VDNAReactionModel.hh.
Referenced by G4DNAMolecularReactionTable::PrintTable().
Initialise()
virtual void G4VDNAReactionModel::Initialise (G4MolecularConfiguration * , const G4Track &) inline virtual
This macro is defined in AddClone_def.
Reimplemented in G4DNASmoluchowskiReactionModel.
Definition at line 73 of file G4VDNAReactionModel.hh.
Referenced by G4DNAMoleculeEncounterStepper::CalculateStep().
InitialiseToPrint()
virtual void G4VDNAReactionModel::InitialiseToPrint (G4MolecularConfiguration *) pure virtual
Implemented in G4DNASmoluchowskiReactionModel.
Referenced by G4DNAMolecularReactionTable::PrintTable().
operator=()
G4VDNAReactionModel & G4VDNAReactionModel::operator= (const G4VDNAReactionModel & right) protected
Definition at line 44 of file G4VDNAReactionModel.cc.
SetReactionTable()
void G4VDNAReactionModel::SetReactionTable (const G4DNAMolecularReactionTable * table) inline
Definition at line 91 of file G4VDNAReactionModel.hh.
Referenced by G4DNAMolecularStepByStepModel::Initialize(), and G4DNAMolecularReactionTable::PrintTable().
Field Documentation
fReactionTable
const G4DNAMolecularReactionTable* G4VDNAReactionModel::fReactionTable protected
Definition at line 88 of file G4VDNAReactionModel.hh.
Referenced by G4VDNAReactionModel(), G4DNASmoluchowskiReactionModel::GetReactionRadius(), GetReactionTable(), G4DNASmoluchowskiReactionModel::Initialise(), G4DNASmoluchowskiReactionModel::InitialiseToPrint(), operator=(), SetReactionTable(), and ~G4VDNAReactionModel().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/dna/utils/include/G4VDNAReactionModel.hh
source/processes/electromagnetic/dna/utils/src/G4VDNAReactionModel.cc