Geant4: G4VCurvedTrajectoryFilter Class Reference
G4VCurvedTrajectoryFilter Class Reference abstract
#include <G4VCurvedTrajectoryFilter.hh>
Public Member Functions
G4VCurvedTrajectoryFilter ()
virtual ~G4VCurvedTrajectoryFilter ()
void CreateNewTrajectorySegment ()
virtual void TakeIntermediatePoint (G4ThreeVector newPoint)=0
std::vector< G4ThreeVector > * GimmeThePointsAndForgetThem ()
Protected Attributes
std::vector< G4ThreeVector > * fpFilteredPoints
Detailed Description
Definition at line 55 of file G4VCurvedTrajectoryFilter.hh.
Constructor & Destructor Documentation
G4VCurvedTrajectoryFilter()
G4VCurvedTrajectoryFilter::G4VCurvedTrajectoryFilter ()
Definition at line 31 of file G4VCurvedTrajectoryFilter.cc.
~G4VCurvedTrajectoryFilter()
G4VCurvedTrajectoryFilter::~G4VCurvedTrajectoryFilter () virtual
Definition at line 36 of file G4VCurvedTrajectoryFilter.cc.
Member Function Documentation
CreateNewTrajectorySegment()
void G4VCurvedTrajectoryFilter::CreateNewTrajectorySegment ()
Definition at line 57 of file G4VCurvedTrajectoryFilter.cc.
Referenced by G4PropagatorInField::ComputeStep().
GimmeThePointsAndForgetThem()
std::vector< G4ThreeVector > * G4VCurvedTrajectoryFilter::GimmeThePointsAndForgetThem ()
Definition at line 41 of file G4VCurvedTrajectoryFilter.cc.
Referenced by G4PropagatorInField::GimmeTrajectoryVectorAndForgetIt().
TakeIntermediatePoint()
virtual void G4VCurvedTrajectoryFilter::TakeIntermediatePoint (G4ThreeVector newPoint) pure virtual
Implemented in G4IdentityTrajectoryFilter.
Referenced by G4PropagatorInField::ComputeStep().
Field Documentation
fpFilteredPoints
std::vector<G4ThreeVector>* G4VCurvedTrajectoryFilter::fpFilteredPoints protected
Definition at line 78 of file G4VCurvedTrajectoryFilter.hh.
Referenced by CreateNewTrajectorySegment(), GimmeThePointsAndForgetThem(), and G4IdentityTrajectoryFilter::TakeIntermediatePoint().
The documentation for this class was generated from the following files:
source/geometry/management/include/G4VCurvedTrajectoryFilter.hh
source/geometry/management/src/G4VCurvedTrajectoryFilter.cc