Geant4: G4VisAttributes Class Reference
G4VisAttributes Class Reference
#include <G4VisAttributes.hh>
Public Types
enum LineStyle { unbroken, dashed, dotted }
enum ForcedDrawingStyle { wireframe, solid }
Public Member Functions
G4VisAttributes ()
G4VisAttributes (G4bool visibility)
G4VisAttributes (const G4Colour &colour)
G4VisAttributes (G4bool visibility, const G4Colour &colour)
G4VisAttributes (const G4VisAttributes &)
~G4VisAttributes ()
G4VisAttributes & operator= (const G4VisAttributes &)
G4bool operator!= (const G4VisAttributes &a) const
G4bool operator== (const G4VisAttributes &a) const
void SetVisibility (G4bool=true)
void SetDaughtersInvisible (G4bool=true)
void SetColour (const G4Colour &)
void SetColor (const G4Color &)
void SetColour (G4double red, G4double green, G4double blue, G4double alpha=1.)
void SetColor (G4double red, G4double green, G4double blue, G4double alpha=1.)
void SetLineStyle (LineStyle)
void SetLineWidth (G4double)
void SetForceWireframe (G4bool=true)
void SetForceSolid (G4bool=true)
void SetForceAuxEdgeVisible (G4bool=true)
void SetForceLineSegmentsPerCircle (G4int nSegments)
void SetStartTime (G4double)
void SetEndTime (G4double)
void SetAttValues (const std::vector< G4AttValue > *)
void SetAttDefs (const std::map< G4String, G4AttDef > *)
G4bool IsVisible () const
G4bool IsDaughtersInvisible () const
const G4Colour & GetColour () const
const G4Color & GetColor () const
LineStyle GetLineStyle () const
G4double GetLineWidth () const
G4bool IsForceDrawingStyle () const
ForcedDrawingStyle GetForcedDrawingStyle () const
G4bool IsForceAuxEdgeVisible () const
G4bool IsForcedAuxEdgeVisible () const
G4bool IsForceLineSegmentsPerCircle () const
G4int GetForcedLineSegmentsPerCircle () const
G4double GetStartTime () const
G4double GetEndTime () const
const std::vector< G4AttValue > * CreateAttValues () const
const std::map< G4String, G4AttDef > * GetAttDefs () const
Static Public Member Functions
static const G4VisAttributes & GetInvisible ()
static G4int GetMinLineSegmentsPerCircle ()
Static Public Attributes
static const G4VisAttributes Invisible = G4VisAttributes (false)
static constexpr G4int fMinLineSegmentsPerCircle = 3
static constexpr G4double fVeryLongTime = 1.e100 * CLHEP::ns
Private Attributes
G4bool fVisible
G4bool fDaughtersInvisible
G4Colour fColour
LineStyle fLineStyle
G4double fLineWidth
G4bool fForceDrawingStyle
ForcedDrawingStyle fForcedStyle
G4bool fForceAuxEdgeVisible
G4bool fForcedAuxEdgeVisible
G4int fForcedLineSegmentsPerCircle
G4double fStartTime
G4double fEndTime
const std::vector< G4AttValue > * fAttValues
const std::map< G4String, G4AttDef > * fAttDefs
Friends
std::ostream & operator<< (std::ostream &os, const G4VisAttributes &a)
Detailed Description
Definition at line 68 of file G4VisAttributes.hh.
Member Enumeration Documentation
ForcedDrawingStyle
enum G4VisAttributes::ForcedDrawingStyle
Enumerator
wireframe
solid
Definition at line 75 of file G4VisAttributes.hh.
LineStyle
enum G4VisAttributes::LineStyle
Enumerator
unbroken
dashed
dotted
Definition at line 74 of file G4VisAttributes.hh.
Constructor & Destructor Documentation
G4VisAttributes() [1/5]
G4VisAttributes::G4VisAttributes ()
Definition at line 36 of file G4VisAttributes.cc.
Referenced by GetInvisible().
G4VisAttributes() [2/5]
G4VisAttributes::G4VisAttributes (G4bool visibility)
Definition at line 53 of file G4VisAttributes.cc.
G4VisAttributes() [3/5]
G4VisAttributes::G4VisAttributes (const G4Colour & colour)
Definition at line 70 of file G4VisAttributes.cc.
G4VisAttributes() [4/5]
G4VisAttributes::G4VisAttributes (G4bool visibility, const G4Colour & colour)
Definition at line 87 of file G4VisAttributes.cc.
G4VisAttributes() [5/5]
G4VisAttributes::G4VisAttributes (const G4VisAttributes & va)
Definition at line 105 of file G4VisAttributes.cc.
~G4VisAttributes()
G4VisAttributes::~G4VisAttributes ()
Definition at line 127 of file G4VisAttributes.cc.
Member Function Documentation
CreateAttValues()
const std::vector< G4AttValue > * G4VisAttributes::CreateAttValues () const
Definition at line 199 of file G4VisAttributes.cc.
Referenced by G4VSceneHandler::LoadAtts(), and G4XXXStoredSceneHandler::PreAddSolid().
GetAttDefs()
const std::map<G4String,G4AttDef>* G4VisAttributes::GetAttDefs () const
Referenced by G4VSceneHandler::LoadAtts(), and G4XXXStoredSceneHandler::PreAddSolid().
GetColor()
const G4Color& G4VisAttributes::GetColor () const
Referenced by G4GMocrenFileSceneHandler::AddDetector(), G4GMocrenFileSceneHandler::AddPrimitive(), G03ColorWriter::ColorWrite(), and export_G4VisAttributes().
GetColour()
const G4Colour& G4VisAttributes::GetColour () const
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4RTRun::Attenuate(), G4TheRayTracer::Attenuate(), G4XXXSGViewer::CompareForKernelVisit(), G4XXXStoredViewer::CompareForKernelVisit(), G4PhysicalVolumeModel::DescribeAndDescend(), export_G4VisAttributes(), G4RTRun::GetSurfaceColour(), G4TheRayTracer::GetSurfaceColour(), operator<<(), G4VisCommandsViewerSet::SetNewValue(), G4ViewParameters::TouchableCommands(), and G4RTSteppingAction::UserSteppingAction().
GetEndTime()
G4double G4VisAttributes::GetEndTime () const
GetForcedDrawingStyle()
G4VisAttributes::ForcedDrawingStyle G4VisAttributes::GetForcedDrawingStyle () const
Definition at line 189 of file G4VisAttributes.cc.
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), export_G4VisAttributes(), operator<<(), G4ViewParameters::TouchableCommands(), G4RTSteppingAction::UserSteppingAction(), G4RTRun::ValidColour(), and G4TheRayTracer::ValidColour().
GetForcedLineSegmentsPerCircle()
G4int G4VisAttributes::GetForcedLineSegmentsPerCircle () const
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), G4PhysicalVolumeModel::DescribeSolid(), G4VSceneHandler::GetNoOfSides(), operator<<(), and G4ViewParameters::TouchableCommands().
GetInvisible()
const G4VisAttributes & G4VisAttributes::GetInvisible () static
Definition at line 160 of file G4VisAttributes.cc.
Referenced by UltraFresnelLens::BuildLens(), HadrontherapyModulator::BuildSteps(), G4MIRDRibCage::Construct(), Par01DetectorConstruction::Construct(), RE05DetectorConstruction::Construct(), GeometryConstruction::Construct(), B3DetectorConstruction::Construct(), ExGflashDetectorConstruction::Construct(), FCALCryostatVolumes::Construct(), FCALEMModule::Construct(), ExUCNDetectorConstruction::Construct(), LXeDetectorConstruction::Construct(), FCALTestbeamSetup::Construct(), XrayTelDetectorConstruction::Construct(), DMXDetectorConstruction::Construct(), UltraDetectorConstruction::Construct(), RE02DetectorConstruction::Construct(), XrayFluoMercuryDetectorConstruction::ConstructApparate(), XrayFluoPlaneDetectorConstruction::ConstructApparate(), XrayFluoDetectorConstruction::ConstructApparate(), GammaKnifeDetectorConstruction::ConstructBeamLine(), DetectorConstruction::ConstructCalorimeter(), ExN03DetectorConstruction::ConstructCalorimeter(), Collimator100BeamLine::ConstructCollimator100BeamLine(), Collimator40BeamLine::ConstructCollimator40BeamLine(), Collimator50BeamLine::ConstructCollimator50BeamLine(), Collimator60BeamLine::ConstructCollimator60BeamLine(), Collimator70BeamLine::ConstructCollimator70BeamLine(), Collimator80BeamLine::ConstructCollimator80BeamLine(), LaserDrivenBeamLine::ConstructLaserDrivenBeamLine(), PassiveCarbonBeamLine::ConstructPassiveCarbonBeamLine(), GammaRayTelDetectorConstruction::ConstructPayload(), DicomNestedParamDetectorConstruction::ConstructPhantom(), DicomRegularDetectorConstruction::ConstructPhantom(), BrachyDetectorConstruction::ConstructPhantom(), XrayTelDetectorConstruction::ConstructTelescope(), TrentoPassiveProtonBeamLine::ConstructTrentoPassiveProtonBeamLine(), G4HumanPhantomConstruction::ConstructWorld(), B4cDetectorConstruction::DefineVolumes(), B4dDetectorConstruction::DefineVolumes(), B4DetectorConstruction::DefineVolumes(), export_G4VisAttributes(), LaserDrivenBeamLine::FaradayCup(), G4BuildGeom(), F04ElementField::GetVisAttribute(), G4GDMLReadStructure::GetWorldVolume(), PassiveCarbonBeamLine::HadrontherapyRippleFilter(), XDetectorConstruction::SetupGeometry(), RE04DetectorConstruction::SetupGeometry(), GB03DetectorConstruction::SetupGeometry(), RE06DetectorConstruction::SetupGeometry(), and G3toG4DetectorConstruction::SimpleConstruct().
GetLineStyle()
LineStyle G4VisAttributes::GetLineStyle () const
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), export_G4VisAttributes(), operator<<(), and G4ViewParameters::TouchableCommands().
GetLineWidth()
G4double G4VisAttributes::GetLineWidth () const
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), export_G4VisAttributes(), G4VSceneHandler::GetLineWidth(), operator<<(), and G4ViewParameters::TouchableCommands().
GetMinLineSegmentsPerCircle()
static G4int G4VisAttributes::GetMinLineSegmentsPerCircle () static
Referenced by G4VSceneHandler::GetNoOfSides(), G4ModelingParameters::SetNoOfSides(), and G4ViewParameters::SetNoOfSides().
GetStartTime()
G4double G4VisAttributes::GetStartTime () const
IsDaughtersInvisible()
G4bool G4VisAttributes::IsDaughtersInvisible () const
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), export_G4VisAttributes(), operator<<(), and G4ViewParameters::TouchableCommands().
IsForceAuxEdgeVisible()
G4bool G4VisAttributes::IsForceAuxEdgeVisible () const
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), export_G4VisAttributes(), operator<<(), and G4ViewParameters::TouchableCommands().
IsForcedAuxEdgeVisible()
G4bool G4VisAttributes::IsForcedAuxEdgeVisible () const
Definition at line 194 of file G4VisAttributes.cc.
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), G4VSceneHandler::GetAuxEdgeVisible(), operator<<(), and G4ViewParameters::TouchableCommands().
IsForceDrawingStyle()
G4bool G4VisAttributes::IsForceDrawingStyle () const
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), export_G4VisAttributes(), operator<<(), G4ViewParameters::TouchableCommands(), G4RTSteppingAction::UserSteppingAction(), G4RTRun::ValidColour(), and G4TheRayTracer::ValidColour().
IsForceLineSegmentsPerCircle()
G4bool G4VisAttributes::IsForceLineSegmentsPerCircle () const
Referenced by G4PhysicalVolumeModel::DescribeSolid(), and G4VSceneHandler::GetNoOfSides().
IsVisible()
G4bool G4VisAttributes::IsVisible () const
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4HepRepFileSceneHandler::AddPrimitive(), G4HepRepFileSceneHandler::AddSolid(), G4PhysicalVolumeModel::DescribeAndDescend(), G4HepRepSceneHandler::dontWrite(), export_G4VisAttributes(), G4GMocrenFileSceneHandler::IsVisible(), operator<<(), G4ViewParameters::TouchableCommands(), G4RTSteppingAction::UserSteppingAction(), G4RTRun::ValidColour(), and G4TheRayTracer::ValidColour().
operator!=()
G4bool G4VisAttributes::operator!= (const G4VisAttributes & a) const
Definition at line 278 of file G4VisAttributes.cc.
Referenced by operator==().
operator=()
G4VisAttributes & G4VisAttributes::operator= (const G4VisAttributes & rhs)
Definition at line 130 of file G4VisAttributes.cc.
operator==()
G4bool G4VisAttributes::operator== (const G4VisAttributes & a) const
Definition at line 307 of file G4VisAttributes.cc.
SetAttDefs()
void G4VisAttributes::SetAttDefs (const std::map< G4String, G4AttDef > *)
Referenced by export_G4VisAttributes().
SetAttValues()
void G4VisAttributes::SetAttValues (const std::vector< G4AttValue > *)
Referenced by export_G4VisAttributes().
SetColor() [1/2]
void G4VisAttributes::SetColor (const G4Color &)
Referenced by eRositaDetectorConstruction::Construct().
SetColor() [2/2]
void G4VisAttributes::SetColor (G4double red, G4double green, G4double blue, G4double alpha = 1.)
SetColour() [1/2]
void G4VisAttributes::SetColour (const G4Colour &)
Referenced by G4VisCommandSceneAddArrow2D::Arrow2D::Arrow2D(), G4ViewParameters::CatmullRomCubicSplineInterpolation(), CellParameterisation::CellParameterisation(), G4tgbVolume::ConstructG4LogVol(), G4PhysicalVolumeModel::DescribeAndDescend(), G4PhysicalVolumeModel::DescribeSolid(), G4GPSModel::DescribeYourselfTo(), G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), ExN04CalorimeterHit::Draw(), RE01CalorimeterHit::Draw(), ExGflashHit::Draw(), RE05CalorimeterHit::Draw(), Par01CalorimeterHit::Draw(), G4ScoringCylinder::DrawColumn(), G4ScoringBox::DrawColumn(), G4ArrowModel::G4ArrowModel(), G4DrawVoxels::G4DrawVoxels(), G4VisCommandSceneAddLine::Line::Line(), G4VisCommandSceneAddLine2D::Line2D::Line2D(), G4VisCommandSceneAddFrame::Frame::operator()(), G4VisCommandsTouchableSet::SetNewValue(), G4VisCommandsViewerSet::SetNewValue(), NeuronLoadDataFile::SingleNeuronSWCfile(), and G4VViewer::TouchableSetColour().
SetColour() [2/2]
void G4VisAttributes::SetColour (G4double red, G4double green, G4double blue, G4double alpha = 1.)
SetDaughtersInvisible()
void G4VisAttributes::SetDaughtersInvisible (G4bool = true)
Referenced by DetectorConstruction::ConstructLine(), G4PhysicalVolumeModel::DescribeAndDescend(), export_G4VisAttributes(), F04ElementField::GetVisAttribute(), and G4VisCommandsTouchableSet::SetNewValue().
SetEndTime()
void G4VisAttributes::SetEndTime (G4double)
Referenced by XAluminumElectrodeHit::Draw().
SetForceAuxEdgeVisible()
void G4VisAttributes::SetForceAuxEdgeVisible (G4bool visibility = true)
Definition at line 183 of file G4VisAttributes.cc.
Referenced by G4VSceneHandler::AddSolidWithAuxiliaryEdges(), G4PhysicalVolumeModel::DescribeAndDescend(), G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), G4ScoringCylinder::DrawColumn(), G4ScoringBox::DrawColumn(), export_G4VisAttributes(), and G4VisCommandsTouchableSet::SetNewValue().
SetForceLineSegmentsPerCircle()
void G4VisAttributes::SetForceLineSegmentsPerCircle (G4int nSegments)
Definition at line 204 of file G4VisAttributes.cc.
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), and G4VisCommandsTouchableSet::SetNewValue().
SetForceSolid()
void G4VisAttributes::SetForceSolid (G4bool force = true)
Definition at line 174 of file G4VisAttributes.cc.
Referenced by DetectorConstruction::AtomisticView(), DetectorConstruction::BarycenterView(), G4MIRDLeftLegBone::Construct(), G4MIRDRightKidney::Construct(), G4MIRDRightScapula::Construct(), G4MIRDLiver::Construct(), G4MIRDBrain::Construct(), G4MIRDLeftLeg::Construct(), G4MIRDRightClavicle::Construct(), G4MIRDRightLeg::Construct(), G4MIRDRightLegBone::Construct(), G4MIRDLeftLung::Construct(), G4MIRDLeftOvary::Construct(), G4MIRDLeftScapula::Construct(), G4MIRDSkull::Construct(), G4MIRDSmallIntestine::Construct(), G4MIRDLeftTeste::Construct(), G4MIRDHeart::Construct(), G4MIRDLeftAdrenal::Construct(), G4MIRDThyroid::Construct(), G4MIRDLowerLargeIntestine::Construct(), G4MIRDUpperLargeIntestine::Construct(), G4MIRDMaleGenitalia::Construct(), G4MIRDPelvis::Construct(), G4MIRDLeftClavicle::Construct(), G4MIRDRightAdrenal::Construct(), G4MIRDLeftKidney::Construct(), G4MIRDHead::Construct(), G4MIRDRightLung::Construct(), G4MIRDRightOvary::Construct(), G4MIRDRightTeste::Construct(), G4MIRDSpleen::Construct(), G4MIRDStomach::Construct(), G4MIRDThymus::Construct(), G4MIRDTrunk::Construct(), G4MIRDLeftArmBone::Construct(), G4MIRDUpperSpine::Construct(), G4MIRDMiddleLowerSpine::Construct(), G4MIRDUterus::Construct(), G4MIRDPancreas::Construct(), G4MIRDLeftBreast::Construct(), G4MIRDRibCage::Construct(), G4MIRDRightBreast::Construct(), B03DetectorConstruction::Construct(), G4MIRDUrinaryBladder::Construct(), G4MIRDRightArmBone::Construct(), B02DetectorConstruction::Construct(), B01DetectorConstruction::Construct(), ExUCNDetectorConstruction::Construct(), DMXDetectorConstruction::Construct(), XrayFluoMercuryDetectorConstruction::ConstructApparate(), XrayFluoPlaneDetectorConstruction::ConstructApparate(), XrayFluoDetectorConstruction::ConstructApparate(), PurgMagDetectorConstruction::ConstructCalorimeter(), DetectorConstruction::ConstructLine(), GammaRayTelDetectorConstruction::ConstructPayload(), G4HumanPhantomConstruction::ConstructWorld(), TSDetectorConstruction::ConstructWorld(), G4PhysicalVolumeModel::DescribeAndDescend(), G4GPSModel::DescribeYourselfTo(), UVA_VisAction::Draw(), G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), ExN04CalorimeterHit::Draw(), RE01CalorimeterHit::Draw(), RE05CalorimeterHit::Draw(), ExGflashHit::Draw(), LXePMTHit::Draw(), Par01CalorimeterHit::Draw(), G4ScoringCylinder::DrawColumn(), G4ScoringBox::DrawColumn(), export_G4VisAttributes(), CML2AccSaturn::flatteningFilter(), G4ArrowModel::G4ArrowModel(), CML2AccSaturn::Jaw1X(), CML2AccSaturn::Jaw1Y(), CML2Acc2::primaryCollimator(), DetectorConstruction::ResiduesView(), G4VisCommandsTouchableSet::SetNewValue(), G4VisCommandSceneAddLogo::SetNewValue(), and LXeMainVolume::VisAttributes().
SetForceWireframe()
void G4VisAttributes::SetForceWireframe (G4bool force = true)
Definition at line 165 of file G4VisAttributes.cc.
Referenced by ExN04DetectorConstruction::Construct(), RE01DetectorConstruction::Construct(), Par01DetectorConstruction::Construct(), RE05DetectorConstruction::Construct(), ExUCNDetectorConstruction::Construct(), doiPETDetectorConstruction::Construct(), UltraDetectorConstruction::Construct(), GammaRayTelDetectorConstruction::ConstructPayload(), doiPETDetectorConstruction::ConstructPhantom(), UltraDetectorConstruction::ConstructReflector(), TSDetectorConstruction::ConstructWorld(), G4PhysicalVolumeModel::DescribeAndDescend(), G4LogicalVolumeModel::DescribeSolid(), ExN04CalorimeterHit::Draw(), RE01CalorimeterHit::Draw(), ExGflashHit::Draw(), Par01CalorimeterHit::Draw(), export_G4VisAttributes(), PerspectiveVisAction::RoomAndChair(), G4VisCommandsTouchableSet::SetNewValue(), and CCalG4Able::setVisType().
SetLineStyle()
void G4VisAttributes::SetLineStyle (LineStyle)
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), export_G4VisAttributes(), and G4VisCommandsTouchableSet::SetNewValue().
SetLineWidth()
void G4VisAttributes::SetLineWidth (G4double)
Referenced by G4VisCommandSceneAddArrow2D::Arrow2D::Arrow2D(), G4MIRDSkull::Construct(), G4MIRDBrain::Construct(), CML2Ph_BoxInBox::Construct(), G4PhysicalVolumeModel::DescribeAndDescend(), CexmcScenePrimitives::DrawRadialLine(), G4TrajectoryDrawerUtils::DrawWithoutTime(), G4TrajectoryDrawerUtils::DrawWithTime(), export_G4VisAttributes(), CexmcScenePrimitives::HighlightInnerCrystals(), G4VisCommandSceneAddLine::Line::Line(), G4VisCommandSceneAddLine2D::Line2D::Line2D(), G4VisCommandSceneAddFrame::Frame::operator()(), and G4VisCommandsTouchableSet::SetNewValue().
SetStartTime()
void G4VisAttributes::SetStartTime (G4double)
Referenced by XAluminumElectrodeHit::Draw().
SetVisibility()
void G4VisAttributes::SetVisibility (G4bool = true)
Referenced by eRositaDetectorConstruction::Construct(), ExUCNDetectorConstruction::Construct(), CML2Ph_BoxInBox::Construct(), CML2PhantomConstruction::Construct(), doiPETDetectorConstruction::Construct(), CML2Ph_FullWater::Construct(), DMXDetectorConstruction::Construct(), UltraDetectorConstruction::Construct(), XrayFluoMercuryDetectorConstruction::ConstructApparate(), XrayFluoPlaneDetectorConstruction::ConstructApparate(), XrayFluoDetectorConstruction::ConstructApparate(), ExN03DetectorConstruction::ConstructCalorimeter(), PurgMagDetectorConstruction::ConstructCalorimeter(), DetectorConstruction::ConstructDetector(), G4tgbVolume::ConstructG4LogVol(), DetectorConstruction::ConstructLine(), GammaRayTelDetectorConstruction::ConstructPayload(), doiPETDetectorConstruction::ConstructPhantom(), UltraDetectorConstruction::ConstructReflector(), UltraDetectorConstruction::ConstructUVscope(), DetectorConstruction::ConstructWorld(), TSDetectorConstruction::ConstructWorld(), G4PhysicalVolumeModel::DescribeAndDescend(), G4TrajectoryDrawerUtils::DrawWithoutTime(), G4TrajectoryDrawerUtils::DrawWithTime(), export_G4VisAttributes(), CML2Acc1::flatteningFilter(), CML2Acc2::flatteningFilter(), CML2AccSaturn::flatteningFilter(), CML2Acc1::ionizationChamber(), CML2Acc2::ionizationChamber(), CML2Acc2::Jaw1X(), CML2AccSaturn::Jaw1X(), CML2Acc2::Jaw1Y(), CML2AccSaturn::Jaw1Y(), CML2Acc2::Jaw2X(), CML2Acc2::MLC(), CML2Acc1::primaryCollimator(), CML2Acc2::primaryCollimator(), DicomPhantomParameterisationColour::ReadColourData(), DicomNestedPhantomParameterisation::ReadColourData(), G4VisCommandsTouchableSet::SetNewValue(), G4ScoringCylinder::SetupGeometry(), G4ScoringBox::SetupGeometry(), XDetectorConstruction::SetupGeometry(), RE03DetectorConstruction::SetupGeometry(), RE04DetectorConstruction::SetupGeometry(), GB03DetectorConstruction::SetupGeometry(), RE06DetectorConstruction::SetupGeometry(), CCalG4Able::setVisType(), G3toG4DetectorConstruction::SimpleConstruct(), CML2Acc2::target(), G4VViewer::TouchableSetVisibility(), and CML2Acc2::vacuumWindow().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const G4VisAttributes & a) friend
Definition at line 216 of file G4VisAttributes.cc.
Field Documentation
fAttDefs
const std::map<G4String,G4AttDef>* G4VisAttributes::fAttDefs private
Definition at line 164 of file G4VisAttributes.hh.
Referenced by operator!=(), and operator=().
fAttValues
const std::vector<G4AttValue>* G4VisAttributes::fAttValues private
Definition at line 163 of file G4VisAttributes.hh.
Referenced by CreateAttValues(), operator!=(), and operator=().
fColour
G4Colour G4VisAttributes::fColour private
Definition at line 152 of file G4VisAttributes.hh.
Referenced by operator!=(), and operator=().
fDaughtersInvisible
G4bool G4VisAttributes::fDaughtersInvisible private
Definition at line 151 of file G4VisAttributes.hh.
Referenced by operator!=(), and operator=().
fEndTime
G4double G4VisAttributes::fEndTime private
Definition at line 162 of file G4VisAttributes.hh.
Referenced by operator!=(), and operator=().
fForceAuxEdgeVisible
G4bool G4VisAttributes::fForceAuxEdgeVisible private
Definition at line 158 of file G4VisAttributes.hh.
Referenced by IsForcedAuxEdgeVisible(), operator!=(), operator=(), and SetForceAuxEdgeVisible().
fForcedAuxEdgeVisible
G4bool G4VisAttributes::fForcedAuxEdgeVisible private
Definition at line 159 of file G4VisAttributes.hh.
Referenced by IsForcedAuxEdgeVisible(), operator!=(), operator=(), and SetForceAuxEdgeVisible().
fForcedLineSegmentsPerCircle
G4int G4VisAttributes::fForcedLineSegmentsPerCircle private
Definition at line 160 of file G4VisAttributes.hh.
Referenced by operator!=(), operator=(), and SetForceLineSegmentsPerCircle().
fForceDrawingStyle
G4bool G4VisAttributes::fForceDrawingStyle private
Definition at line 156 of file G4VisAttributes.hh.
Referenced by GetForcedDrawingStyle(), operator!=(), operator=(), SetForceSolid(), and SetForceWireframe().
fForcedStyle
ForcedDrawingStyle G4VisAttributes::fForcedStyle private
Definition at line 157 of file G4VisAttributes.hh.
Referenced by GetForcedDrawingStyle(), operator!=(), operator=(), SetForceSolid(), and SetForceWireframe().
fLineStyle
LineStyle G4VisAttributes::fLineStyle private
Definition at line 153 of file G4VisAttributes.hh.
Referenced by operator!=(), and operator=().
fLineWidth
G4double G4VisAttributes::fLineWidth private
Definition at line 154 of file G4VisAttributes.hh.
Referenced by operator!=(), and operator=().
fMinLineSegmentsPerCircle
constexpr G4int G4VisAttributes::fMinLineSegmentsPerCircle = 3 static constexpr
Definition at line 142 of file G4VisAttributes.hh.
Referenced by SetForceLineSegmentsPerCircle().
fStartTime
G4double G4VisAttributes::fStartTime private
Definition at line 162 of file G4VisAttributes.hh.
Referenced by operator!=(), and operator=().
fVeryLongTime
constexpr G4double G4VisAttributes::fVeryLongTime = 1.e100 * CLHEP::ns static constexpr
Definition at line 145 of file G4VisAttributes.hh.
Referenced by G4VisCommandsViewerSet::G4VisCommandsViewerSet().
fVisible
G4bool G4VisAttributes::fVisible private
Definition at line 150 of file G4VisAttributes.hh.
Referenced by operator!=(), and operator=().
Invisible
const G4VisAttributes G4VisAttributes::Invisible = G4VisAttributes (false) static
Definition at line 91 of file G4VisAttributes.hh.
Referenced by doiPETDetectorConstruction::Construct().
The documentation for this class was generated from the following files:
source/graphics_reps/include/G4VisAttributes.hh
source/graphics_reps/src/G4VisAttributes.cc