Geant4: G4ModelingParameters::VisAttributesModifier Class Reference
G4ModelingParameters::VisAttributesModifier Class Reference
#include <G4ModelingParameters.hh>
Public Member Functions
VisAttributesModifier (const G4VisAttributes &visAtts, VisAttributesSignifier signifier, const PVNameCopyNoPath &path)
const G4VisAttributes & GetVisAttributes () const
VisAttributesSignifier GetVisAttributesSignifier () const
const PVNameCopyNoPath & GetPVNameCopyNoPath () const
void SetVisAttributes (const G4VisAttributes &visAtts)
void SetVisAttributesSignifier (VisAttributesSignifier signifier)
void SetPVNameCopyNoPath (const PVNameCopyNoPath &PVNameCopyNoPath)
G4bool operator!= (const VisAttributesModifier &) const
G4bool operator== (const VisAttributesModifier &rhs) const
Private Attributes
G4VisAttributes fVisAtts
VisAttributesSignifier fSignifier
PVNameCopyNoPath fPVNameCopyNoPath
Detailed Description
Definition at line 110 of file G4ModelingParameters.hh.
Constructor & Destructor Documentation
VisAttributesModifier()
G4ModelingParameters::VisAttributesModifier::VisAttributesModifier (const G4VisAttributes & visAtts, VisAttributesSignifier signifier, const PVNameCopyNoPath & path) inline
Definition at line 113 of file G4ModelingParameters.hh.
Member Function Documentation
GetPVNameCopyNoPath()
const PVNameCopyNoPath& G4ModelingParameters::VisAttributesModifier::GetPVNameCopyNoPath () const inline
Definition at line 121 of file G4ModelingParameters.hh.
Referenced by G4ViewParameters::AddVisAttributesModifier().
GetVisAttributes()
const G4VisAttributes& G4ModelingParameters::VisAttributesModifier::GetVisAttributes () const inline
Definition at line 117 of file G4ModelingParameters.hh.
Referenced by G4ViewParameters::AddVisAttributesModifier().
GetVisAttributesSignifier()
VisAttributesSignifier G4ModelingParameters::VisAttributesModifier::GetVisAttributesSignifier () const inline
Definition at line 119 of file G4ModelingParameters.hh.
Referenced by G4ViewParameters::AddVisAttributesModifier().
operator!=()
G4bool G4ModelingParameters::VisAttributesModifier::operator!= (const VisAttributesModifier & rhs) const
Definition at line 271 of file G4ModelingParameters.cc.
Referenced by operator==().
operator==()
G4bool G4ModelingParameters::VisAttributesModifier::operator== (const VisAttributesModifier & rhs) const inline
Definition at line 130 of file G4ModelingParameters.hh.
SetPVNameCopyNoPath()
void G4ModelingParameters::VisAttributesModifier::SetPVNameCopyNoPath (const PVNameCopyNoPath & PVNameCopyNoPath) inline
Definition at line 127 of file G4ModelingParameters.hh.
SetVisAttributes()
void G4ModelingParameters::VisAttributesModifier::SetVisAttributes (const G4VisAttributes & visAtts) inline
Definition at line 123 of file G4ModelingParameters.hh.
SetVisAttributesSignifier()
void G4ModelingParameters::VisAttributesModifier::SetVisAttributesSignifier (VisAttributesSignifier signifier) inline
Definition at line 125 of file G4ModelingParameters.hh.
Field Documentation
fPVNameCopyNoPath
PVNameCopyNoPath G4ModelingParameters::VisAttributesModifier::fPVNameCopyNoPath private
Definition at line 135 of file G4ModelingParameters.hh.
Referenced by GetPVNameCopyNoPath(), and SetPVNameCopyNoPath().
fSignifier
VisAttributesSignifier G4ModelingParameters::VisAttributesModifier::fSignifier private
Definition at line 134 of file G4ModelingParameters.hh.
Referenced by GetVisAttributesSignifier(), and SetVisAttributesSignifier().
fVisAtts
G4VisAttributes G4ModelingParameters::VisAttributesModifier::fVisAtts private
Definition at line 133 of file G4ModelingParameters.hh.
Referenced by GetVisAttributes(), and SetVisAttributes().
The documentation for this class was generated from the following files:
source/visualization/modeling/include/G4ModelingParameters.hh
source/visualization/modeling/src/G4ModelingParameters.cc