Geant4: G4DNAEmfietzoglouWaterIonisationStructure Class Reference
G4DNAEmfietzoglouWaterIonisationStructure Class Reference
#include <G4DNAEmfietzoglouWaterIonisationStructure.hh>
Public Member Functions
G4DNAEmfietzoglouWaterIonisationStructure ()
virtual ~G4DNAEmfietzoglouWaterIonisationStructure ()
G4double IonisationEnergy (G4int level)
G4int NumberOfLevels ()
Private Attributes
G4int nLevels
std::vector< G4double > energyConstant
Detailed Description
Definition at line 42 of file G4DNAEmfietzoglouWaterIonisationStructure.hh.
Constructor & Destructor Documentation
G4DNAEmfietzoglouWaterIonisationStructure()
G4DNAEmfietzoglouWaterIonisationStructure::G4DNAEmfietzoglouWaterIonisationStructure ()
Definition at line 41 of file G4DNAEmfietzoglouWaterIonisationStructure.cc.
~G4DNAEmfietzoglouWaterIonisationStructure()
G4DNAEmfietzoglouWaterIonisationStructure::~G4DNAEmfietzoglouWaterIonisationStructure () virtual
Definition at line 54 of file G4DNAEmfietzoglouWaterIonisationStructure.cc.
Member Function Documentation
IonisationEnergy()
G4double G4DNAEmfietzoglouWaterIonisationStructure::IonisationEnergy (G4int level)
Definition at line 59 of file G4DNAEmfietzoglouWaterIonisationStructure.cc.
Referenced by G4DNAEmfietzoglouIonisationModel::DifferentialCrossSection(), G4DNAEmfietzoglouIonisationModel::RandomizeEjectedElectronEnergy(), G4DNAEmfietzoglouIonisationModel::RandomizeEjectedElectronEnergyFromCumulatedDcs(), and G4DNAEmfietzoglouIonisationModel::SampleSecondaries().
NumberOfLevels()
G4int G4DNAEmfietzoglouWaterIonisationStructure::NumberOfLevels () inline
Definition at line 52 of file G4DNAEmfietzoglouWaterIonisationStructure.hh.
Field Documentation
energyConstant
std::vector<G4double> G4DNAEmfietzoglouWaterIonisationStructure::energyConstant private
Definition at line 58 of file G4DNAEmfietzoglouWaterIonisationStructure.hh.
Referenced by G4DNAEmfietzoglouWaterIonisationStructure(), and IonisationEnergy().
nLevels
G4int G4DNAEmfietzoglouWaterIonisationStructure::nLevels private
Definition at line 56 of file G4DNAEmfietzoglouWaterIonisationStructure.hh.
Referenced by G4DNAEmfietzoglouWaterIonisationStructure(), IonisationEnergy(), and NumberOfLevels().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/dna/utils/include/G4DNAEmfietzoglouWaterIonisationStructure.hh
source/processes/electromagnetic/dna/utils/src/G4DNAEmfietzoglouWaterIonisationStructure.cc