Geant4: G4VSensitiveDetector Class Reference
G4VSensitiveDetector Class Reference abstract
#include <G4VSensitiveDetector.hh>
Public Member Functions
G4VSensitiveDetector (G4String name)
G4VSensitiveDetector (const G4VSensitiveDetector &right)
virtual ~G4VSensitiveDetector ()
G4VSensitiveDetector & operator= (const G4VSensitiveDetector &right)
G4bool operator== (const G4VSensitiveDetector &right) const
G4bool operator!= (const G4VSensitiveDetector &right) const
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
G4bool Hit (G4Step *aStep)
void SetROgeometry (G4VReadOutGeometry *value)
void SetFilter (G4VSDFilter *value)
G4int GetNumberOfCollections () const
G4String GetCollectionName (G4int id) const
void SetVerboseLevel (G4int vl)
void Activate (G4bool activeFlag)
G4bool isActive () const
G4String GetName () const
G4String GetPathName () const
G4String GetFullPathName () const
G4VReadOutGeometry * GetROgeometry () const
G4VSDFilter * GetFilter () const
virtual G4VSensitiveDetector * Clone () const
Protected Member Functions
virtual G4bool ProcessHits (G4Step *aStep, G4TouchableHistory *ROhist)=0
virtual G4int GetCollectionID (G4int i)
Protected Attributes
G4CollectionNameVector collectionName
G4String SensitiveDetectorName
G4String thePathName
G4String fullPathName
G4int verboseLevel
G4bool active
G4VReadOutGeometry * ROgeometry
G4VSDFilter * filter
Detailed Description
Definition at line 49 of file G4VSensitiveDetector.hh.
Constructor & Destructor Documentation
G4VSensitiveDetector() [1/2]
G4VSensitiveDetector::G4VSensitiveDetector (G4String name)
Definition at line 32 of file G4VSensitiveDetector.cc.
G4VSensitiveDetector() [2/2]
G4VSensitiveDetector::G4VSensitiveDetector (const G4VSensitiveDetector & right)
Definition at line 53 of file G4VSensitiveDetector.cc.
~G4VSensitiveDetector()
G4VSensitiveDetector::~G4VSensitiveDetector () virtual
Definition at line 64 of file G4VSensitiveDetector.cc.
Member Function Documentation
Activate()
void G4VSensitiveDetector::Activate (G4bool activeFlag) inline
Definition at line 141 of file G4VSensitiveDetector.hh.
Referenced by G4SDStructure::Activate(), and export_G4VSensitiveDetector().
clear()
void G4VSensitiveDetector::clear (void) virtual
Reimplemented in G4MultiFunctionalDetector, CCaloSD, UltraPMTSD, XrayFluoSD, CheckVolumeSD, DMXPmtSD, TargetSD, DMXScintSD, TargetSD, TargetSD, PhantomSD, TargetSD, CheckVolumeSD, GammaRayTelAnticoincidenceSD, GammaRayTelCalorimeterSD, GammaRayTelTrackerSD, GammaRayTelDummySD, FCALEMModuleSD, FCALTestbeamSetupSD, XrayFluoHPGeSD, LXePMTSD, G4HumanDummyLeftBreastSD, G4HumanDummyRightBreastSD, FCALHadModuleSD, G4MultiSensitiveDetector, LXeScintSD, ExN04CalorimeterSD, ExN04DummySD, ExN04MuonSD, ExN04TrackerSD, Par01CalorimeterSD, RE05DummySD, RE05MuonSD, ExN04DummySD, ExN04MuonSD, ExN04TrackerSD, RE05CalorimeterSD, RE05TrackerSD, ExN04CalorimeterSD, H02MuonSD, and HadrontherapyDummySD.
Definition at line 117 of file G4VSensitiveDetector.cc.
Referenced by export_G4VSensitiveDetector().
Clone()
G4VSensitiveDetector * G4VSensitiveDetector::Clone () const virtual
Reimplemented in G4MultiSensitiveDetector.
Definition at line 68 of file G4VSensitiveDetector.cc.
Referenced by G4VUserDetectorConstruction::CloneSD().
DrawAll()
void G4VSensitiveDetector::DrawAll (void) virtual
Reimplemented in G4MultiFunctionalDetector, RMC01SD, CCaloSD, UltraPMTSD, XrayFluoSD, DMXPmtSD, DMXScintSD, GammaRayTelAnticoincidenceSD, GammaRayTelCalorimeterSD, GammaRayTelTrackerSD, GammaRayTelDummySD, FCALEMModuleSD, FCALTestbeamSetupSD, XrayFluoHPGeSD, LXePMTSD, G4HumanDummyLeftBreastSD, G4HumanDummyRightBreastSD, FCALHadModuleSD, G4MultiSensitiveDetector, LXeScintSD, ExN04CalorimeterSD, ExN04DummySD, ExN04MuonSD, ExN04TrackerSD, Par01CalorimeterSD, RE05DummySD, RE05MuonSD, ExN04DummySD, ExN04MuonSD, ExN04TrackerSD, RE05CalorimeterSD, RE05TrackerSD, ExN04CalorimeterSD, H02MuonSD, and HadrontherapyDummySD.
Definition at line 121 of file G4VSensitiveDetector.cc.
Referenced by export_G4VSensitiveDetector().
EndOfEvent()
void G4VSensitiveDetector::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented in B4cCalorimeterSD, TrackerSD, B2TrackerSD, B2TrackerSD, B2TrackerSD, SensitiveDetector, VoxelSD, VoxelSD, VoxelSD, RMC01SD, CCaloSD, HadrontherapyDetectorSD, ExN04CalorimeterSD, ExN04MuonSD, ExN04TrackerSD, Par01CalorimeterSD, RE05MuonSD, ExN04MuonSD, ExN04TrackerSD, ScreenSD, ScreenSD, ScreenSD, ScreenSD, RE05CalorimeterSD, RE05TrackerSD, ExN04CalorimeterSD, H02MuonSD, RE01TrackerSD, SensitiveDetector, G4MultiFunctionalDetector, XrayFluoSD, CheckVolumeSD, UltraPMTSD, DMXPmtSD, TargetSD, TargetSD, DMXScintSD, TargetSD, TargetSD, PhantomSD, TargetSD, CheckVolumeSD, GammaRayTelAnticoincidenceSD, GammaRayTelCalorimeterSD, GammaRayTelTrackerSD, SensitiveDetector, GammaRayTelDummySD, FCALEMModuleSD, FCALTestbeamSetupSD, XrayFluoHPGeSD, LXePMTSD, G4HumanDummyLeftBreastSD, G4HumanDummyRightBreastSD, FCALHadModuleSD, F01CalorimeterSD, F03CalorimeterSD, G4MultiSensitiveDetector, ExP01TrackerSD, F02CalorimeterSD, ExGflashSensitiveDetector, ExN02TrackerSD, XAluminumElectrodeSensitivity, eRositaTrackerSD, LXeScintSD, ExTGTrackerSD, ExN04DummySD, G04SensitiveDetector, RE05DummySD, ExN04DummySD, G4HumanPhantomSD, and HadrontherapyDummySD.
Definition at line 113 of file G4VSensitiveDetector.cc.
Referenced by export_G4VSensitiveDetector().
GetCollectionID()
G4int G4VSensitiveDetector::GetCollectionID (G4int i) protected virtual
Reimplemented in G4MultiSensitiveDetector.
Definition at line 101 of file G4VSensitiveDetector.cc.
Referenced by ExN04CalorimeterSD::EndOfEvent(), RE05CalorimeterSD::EndOfEvent(), HadrontherapyDetectorSD::EndOfEvent(), H02MuonSD::Initialize(), RE05TrackerSD::Initialize(), ExN04MuonSD::Initialize(), RE01TrackerSD::Initialize(), ExN04TrackerSD::Initialize(), RE05MuonSD::Initialize(), LXeScintSD::Initialize(), RE01CalorimeterSD::Initialize(), LXePMTSD::Initialize(), WLSPhotonDetSD::Initialize(), ExGflashSensitiveDetector::Initialize(), UltraPMTSD::Initialize(), and RMC01SD::Initialize().
GetCollectionName()
G4String G4VSensitiveDetector::GetCollectionName (G4int id) const inline
Definition at line 137 of file G4VSensitiveDetector.hh.
Referenced by G4SDManager::AddNewDetector(), export_G4VSensitiveDetector(), and G4HCtable::GetCollectionID().
GetFilter()
G4VSDFilter* G4VSensitiveDetector::GetFilter () const inline
Definition at line 153 of file G4VSensitiveDetector.hh.
GetFullPathName()
G4String G4VSensitiveDetector::GetFullPathName () const inline
Definition at line 149 of file G4VSensitiveDetector.hh.
Referenced by G4VUserDetectorConstruction::CloneSD(), and export_G4VSensitiveDetector().
GetName()
G4String G4VSensitiveDetector::GetName (void) const inline
Definition at line 145 of file G4VSensitiveDetector.hh.
Referenced by G4SDStructure::AddNewDetector(), G4SDManager::AddNewDetector(), CCalSensAssign::assign(), G4MultiSensitiveDetector::Clone(), G4VUserDetectorConstruction::CloneSD(), export_G4VSensitiveDetector(), G4GDMLWriteStructure::ExportSD(), G4MultiSensitiveDetector::G4MultiSensitiveDetector(), G4HCtable::GetCollectionID(), G4MultiSensitiveDetector::GetCollectionID(), G4VPrimitiveScorer::GetCollectionID(), G4PSCellCharge::Initialize(), G4PSNofStep::Initialize(), G4PSMinKinEAtGeneration::Initialize(), G4PSNofCollision::Initialize(), G4PSTermination::Initialize(), G4PSTrackCounter::Initialize(), G4PSPassageTrackLength::Initialize(), G4PSPassageCellCurrent::Initialize(), G4PSPopulation::Initialize(), CexmcSimpleEnergyDeposit::Initialize(), CexmcTrackPoints::Initialize(), G4PSPassageCellFlux::Initialize(), G4PSTrackLength::Initialize(), G4PSNofSecondary::Initialize(), G4PSCellFlux::Initialize(), G4PSSphereSurfaceCurrent::Initialize(), G4PSSphereSurfaceFlux::Initialize(), G4PSCylinderSurfaceCurrent::Initialize(), G4PSFlatSurfaceCurrent::Initialize(), G3DetTable::PrintAll(), G4PSCellCharge::PrintAll(), G4PSEnergyDeposit::PrintAll(), G4PSDoseDeposit::PrintAll(), G4PSNofStep::PrintAll(), G4PSPassageTrackLength::PrintAll(), G4PSTermination::PrintAll(), G4PSNofCollision::PrintAll(), G4PSTrackCounter::PrintAll(), G4PSPopulation::PrintAll(), G4PSPassageCellCurrent::PrintAll(), G4PSPassageCellFlux::PrintAll(), G4PSTrackLength::PrintAll(), G4PSCellFlux::PrintAll(), G4PSSphereSurfaceCurrent::PrintAll(), G4PSCylinderSurfaceFlux::PrintAll(), G4PSSphereSurfaceFlux::PrintAll(), G4PSCylinderSurfaceCurrent::PrintAll(), G4PSFlatSurfaceCurrent::PrintAll(), G4PSFlatSurfaceFlux::PrintAll(), ScoreSpecies::PrintAll(), CexmcPrimitiveScorer::PrintHeader(), H02MuonSD::ProcessHits(), HadrontherapyDetectorSD::ProcessHits(), SensitiveDetector::ProcessHits(), G4MultiSensitiveDetector::ProcessHits(), G4ASCIITreeSceneHandler::RequestPrimitives(), CCalSensitiveDetectors::setSensitive(), G4VUserParallelWorld::SetSensitiveDetector(), G4VUserDetectorConstruction::SetSensitiveDetector(), and G4MultiSensitiveDetector::~G4MultiSensitiveDetector().
GetNumberOfCollections()
G4int G4VSensitiveDetector::GetNumberOfCollections () const inline
Definition at line 135 of file G4VSensitiveDetector.hh.
Referenced by G4SDManager::AddNewDetector(), export_G4VSensitiveDetector(), and G4HCtable::GetCollectionID().
GetPathName()
G4String G4VSensitiveDetector::GetPathName () const inline
Definition at line 147 of file G4VSensitiveDetector.hh.
Referenced by G4SDManager::AddNewDetector(), and export_G4VSensitiveDetector().
GetROgeometry()
G4VReadOutGeometry* G4VSensitiveDetector::GetROgeometry () const inline
Definition at line 151 of file G4VSensitiveDetector.hh.
Referenced by G4LogicalVolumeModel::DescribeYourselfTo(), export_G4VSensitiveDetector(), G4VGFlashSensitiveDetector::Hit(), and G4ASCIITreeSceneHandler::RequestPrimitives().
Hit()
G4bool G4VSensitiveDetector::Hit (G4Step * aStep) inline
Definition at line 113 of file G4VSensitiveDetector.hh.
Referenced by Par01PionShowerModel::AssignSpotAndCallHit(), Par01EMShowerModel::AssignSpotAndCallHit(), G4ParallelWorldProcess::AtRestDoIt(), G4ParallelWorldScoringProcess::AtRestDoIt(), export_G4VSensitiveDetector(), G4UCNBoundaryProcess::InvokeSD(), G4OpBoundaryProcess::InvokeSD(), G4ParallelWorldProcess::PostStepDoIt(), G4ScoreSplittingProcess::PostStepDoIt(), G4ParallelWorldScoringProcess::PostStepDoIt(), and G4SteppingManager::Stepping().
Initialize()
void G4VSensitiveDetector::Initialize (G4HCofThisEvent *) virtual
Reimplemented in B4cCalorimeterSD, TrackerSD, B2TrackerSD, B2TrackerSD, B2TrackerSD, SensitiveDetector, VoxelSD, VoxelSD, VoxelSD, RMC01SD, CCaloSD, B5DriftChamberSD, B5EmCalorimeterSD, B5HadCalorimeterSD, B5HodoscopeSD, RE01CalorimeterSD, ExN04CalorimeterSD, ExN04MuonSD, ExN04TrackerSD, Par01CalorimeterSD, RE05MuonSD, ExN04MuonSD, ExN04TrackerSD, ScreenSD, ScreenSD, ScreenSD, ScreenSD, RE01TrackerSD, RE05CalorimeterSD, RE05TrackerSD, ExN04CalorimeterSD, H02MuonSD, SensitiveDetector, G4MultiFunctionalDetector, XrayFluoSD, CheckVolumeSD, UltraPMTSD, DMXPmtSD, TargetSD, TargetSD, DMXScintSD, TargetSD, TargetSD, PhantomSD, TargetSD, CheckVolumeSD, GammaRayTelAnticoincidenceSD, GammaRayTelCalorimeterSD, GammaRayTelTrackerSD, SensitiveDetector, GammaRayTelDummySD, FCALEMModuleSD, FCALTestbeamSetupSD, XrayFluoHPGeSD, G4MultiSensitiveDetector, G4HumanDummyLeftBreastSD, G4HumanDummyRightBreastSD, FCALHadModuleSD, F01CalorimeterSD, F03CalorimeterSD, ExP01TrackerSD, F02CalorimeterSD, LXePMTSD, WLSPhotonDetSD, ExN02TrackerSD, ExGflashSensitiveDetector, XAluminumElectrodeSensitivity, eRositaTrackerSD, LXeScintSD, ExTGTrackerSD, ExN04DummySD, G04SensitiveDetector, RE05DummySD, HadrontherapyDetectorSD, ExN04DummySD, G4HumanPhantomSD, GB06SD, HadrontherapyDummySD, and GB05SD.
Definition at line 109 of file G4VSensitiveDetector.cc.
Referenced by export_G4VSensitiveDetector().
isActive()
G4bool G4VSensitiveDetector::isActive () const inline
Definition at line 143 of file G4VSensitiveDetector.hh.
Referenced by export_G4VSensitiveDetector(), G4VGFlashSensitiveDetector::Hit(), and Hit().
operator!=()
G4bool G4VSensitiveDetector::operator!= (const G4VSensitiveDetector & right) const
Definition at line 96 of file G4VSensitiveDetector.cc.
operator=()
G4VSensitiveDetector & G4VSensitiveDetector::operator= (const G4VSensitiveDetector & right)
Definition at line 78 of file G4VSensitiveDetector.cc.
Referenced by G4MultiSensitiveDetector::operator=().
operator==()
G4bool G4VSensitiveDetector::operator== (const G4VSensitiveDetector & right) const
Definition at line 91 of file G4VSensitiveDetector.cc.
PrintAll()
void G4VSensitiveDetector::PrintAll (void) virtual
Reimplemented in G4MultiFunctionalDetector, RMC01SD, CCaloSD, UltraPMTSD, XrayFluoSD, DMXPmtSD, CheckVolumeSD, DMXScintSD, TargetSD, TargetSD, TargetSD, PhantomSD, TargetSD, GammaRayTelAnticoincidenceSD, GammaRayTelCalorimeterSD, GammaRayTelTrackerSD, CheckVolumeSD, GammaRayTelDummySD, FCALEMModuleSD, FCALTestbeamSetupSD, XrayFluoHPGeSD, LXePMTSD, G4HumanDummyLeftBreastSD, G4HumanDummyRightBreastSD, FCALHadModuleSD, G4MultiSensitiveDetector, LXeScintSD, ExN04CalorimeterSD, ExN04DummySD, ExN04MuonSD, ExN04TrackerSD, Par01CalorimeterSD, RE05DummySD, RE05MuonSD, ExN04DummySD, ExN04MuonSD, ExN04TrackerSD, RE05CalorimeterSD, RE05TrackerSD, ExN04CalorimeterSD, H02MuonSD, and HadrontherapyDummySD.
Definition at line 125 of file G4VSensitiveDetector.cc.
Referenced by export_G4VSensitiveDetector().
ProcessHits()
virtual G4bool G4VSensitiveDetector::ProcessHits (G4Step * aStep, G4TouchableHistory * ROhist) protected pure virtual
Implemented in B4cCalorimeterSD, TrackerSD, B2TrackerSD, B2TrackerSD, B2TrackerSD, SensitiveDetector, ScreenSD, ScreenSD, ScreenSD, ScreenSD, RMC01SD, CCaloSD, G4MultiSensitiveDetector, UltraPMTSD, GammaRayTelCalorimeterSD, GammaRayTelTrackerSD, pyG4VSensitiveDetector::CB_G4VSensitiveDetector, RE01CalorimeterSD, B5DriftChamberSD, B5EmCalorimeterSD, B5HadCalorimeterSD, RE01TrackerSD, B5HodoscopeSD, HadrontherapyDetectorSD, ExN04CalorimeterSD, ExN04MuonSD, ExN04TrackerSD, Par01CalorimeterSD, RE05MuonSD, ExN04MuonSD, ExN04TrackerSD, RE05CalorimeterSD, RE05TrackerSD, ExN04CalorimeterSD, H02MuonSD, SensitiveDetector, GB06SD, GB05SD, VoxelSD, VoxelSD, VoxelSD, GammaRayTelAnticoincidenceSD, LXePMTSD, LXeScintSD, XrayFluoSD, XrayFluoHPGeSD, CheckVolumeSD, DMXPmtSD, TargetSD, TargetSD, DMXScintSD, TargetSD, TargetSD, PhantomSD, TargetSD, CheckVolumeSD, SensitiveDetector, GammaRayTelDummySD, FCALEMModuleSD, FCALTestbeamSetupSD, G4HumanDummyLeftBreastSD, G4HumanDummyRightBreastSD, FCALHadModuleSD, F01CalorimeterSD, F03CalorimeterSD, ExP01TrackerSD, G4MultiFunctionalDetector, F02CalorimeterSD, WLSPhotonDetSD, ExN02TrackerSD, ExGflashSensitiveDetector, XAluminumElectrodeSensitivity, eRositaTrackerSD, ExTGTrackerSD, ExN04DummySD, G04SensitiveDetector, RE05DummySD, ExN04DummySD, G4HumanPhantomSD, and HadrontherapyDummySD.
Referenced by Hit().
SetFilter()
void G4VSensitiveDetector::SetFilter (G4VSDFilter * value) inline
Definition at line 130 of file G4VSensitiveDetector.hh.
Referenced by B03ImportanceDetectorConstruction::ConstructSD(), B02ImportanceDetectorConstruction::ConstructSD(), and B01DetectorConstruction::ConstructSDandField().
SetROgeometry()
void G4VSensitiveDetector::SetROgeometry (G4VReadOutGeometry * value) inline
Definition at line 127 of file G4VSensitiveDetector.hh.
Referenced by ExN04DetectorConstruction::Construct(), and export_G4VSensitiveDetector().
SetVerboseLevel()
void G4VSensitiveDetector::SetVerboseLevel (G4int vl) inline
Definition at line 139 of file G4VSensitiveDetector.hh.
Referenced by export_G4VSensitiveDetector().
Field Documentation
active
G4bool G4VSensitiveDetector::active protected
Definition at line 108 of file G4VSensitiveDetector.hh.
Referenced by Activate(), G4VSensitiveDetector(), isActive(), and operator=().
collectionName
G4CollectionNameVector G4VSensitiveDetector::collectionName protected
Definition at line 98 of file G4VSensitiveDetector.hh.
Referenced by B2TrackerSD::B2TrackerSD(), B4cCalorimeterSD::B4cCalorimeterSD(), B5DriftChamberSD::B5DriftChamberSD(), B5EmCalorimeterSD::B5EmCalorimeterSD(), B5HadCalorimeterSD::B5HadCalorimeterSD(), B5HodoscopeSD::B5HodoscopeSD(), CCaloSD::CCaloSD(), DMXPmtSD::DMXPmtSD(), DMXScintSD::DMXScintSD(), Par01CalorimeterSD::EndOfEvent(), F02CalorimeterSD::EndOfEvent(), F03CalorimeterSD::EndOfEvent(), F01CalorimeterSD::EndOfEvent(), XrayFluoHPGeSD::EndOfEvent(), GammaRayTelTrackerSD::EndOfEvent(), GammaRayTelAnticoincidenceSD::EndOfEvent(), GammaRayTelCalorimeterSD::EndOfEvent(), DMXScintSD::EndOfEvent(), UltraPMTSD::EndOfEvent(), DMXPmtSD::EndOfEvent(), XrayFluoSD::EndOfEvent(), eRositaTrackerSD::eRositaTrackerSD(), ExGflashSensitiveDetector::ExGflashSensitiveDetector(), ExN02TrackerSD::ExN02TrackerSD(), ExN04CalorimeterSD::ExN04CalorimeterSD(), ExN04MuonSD::ExN04MuonSD(), ExN04TrackerSD::ExN04TrackerSD(), ExP01TrackerSD::ExP01TrackerSD(), ExTGTrackerSD::ExTGTrackerSD(), F01CalorimeterSD::F01CalorimeterSD(), F02CalorimeterSD::F02CalorimeterSD(), F03CalorimeterSD::F03CalorimeterSD(), G4HumanPhantomSD::G4HumanPhantomSD(), GammaRayTelAnticoincidenceSD::GammaRayTelAnticoincidenceSD(), GammaRayTelCalorimeterSD::GammaRayTelCalorimeterSD(), GammaRayTelTrackerSD::GammaRayTelTrackerSD(), GetCollectionID(), GetCollectionName(), GetNumberOfCollections(), H02MuonSD::H02MuonSD(), HadrontherapyDetectorSD::HadrontherapyDetectorSD(), G4HumanPhantomSD::Initialize(), ExN04CalorimeterSD::Initialize(), H02MuonSD::Initialize(), HadrontherapyDetectorSD::Initialize(), RE05TrackerSD::Initialize(), RE01TrackerSD::Initialize(), RE05CalorimeterSD::Initialize(), ExN04MuonSD::Initialize(), ExN04TrackerSD::Initialize(), Par01CalorimeterSD::Initialize(), RE05MuonSD::Initialize(), B5HodoscopeSD::Initialize(), LXeScintSD::Initialize(), ExTGTrackerSD::Initialize(), RE01CalorimeterSD::Initialize(), eRositaTrackerSD::Initialize(), B5DriftChamberSD::Initialize(), B5EmCalorimeterSD::Initialize(), B5HadCalorimeterSD::Initialize(), XAluminumElectrodeSensitivity::Initialize(), LXePMTSD::Initialize(), WLSPhotonDetSD::Initialize(), ExN02TrackerSD::Initialize(), ExGflashSensitiveDetector::Initialize(), SensitiveDetector::Initialize(), F02CalorimeterSD::Initialize(), ExP01TrackerSD::Initialize(), F03CalorimeterSD::Initialize(), F01CalorimeterSD::Initialize(), XrayFluoHPGeSD::Initialize(), GammaRayTelTrackerSD::Initialize(), GammaRayTelCalorimeterSD::Initialize(), GammaRayTelAnticoincidenceSD::Initialize(), B2TrackerSD::Initialize(), TrackerSD::Initialize(), B4cCalorimeterSD::Initialize(), DMXScintSD::Initialize(), DMXPmtSD::Initialize(), UltraPMTSD::Initialize(), XrayFluoSD::Initialize(), CCaloSD::Initialize(), RMC01SD::Initialize(), LXePMTSD::LXePMTSD(), LXeScintSD::LXeScintSD(), Par01CalorimeterSD::Par01CalorimeterSD(), RE01CalorimeterSD::RE01CalorimeterSD(), RE01TrackerSD::RE01TrackerSD(), RE05CalorimeterSD::RE05CalorimeterSD(), RE05MuonSD::RE05MuonSD(), RE05TrackerSD::RE05TrackerSD(), G4MultiFunctionalDetector::RegisterPrimitive(), RMC01SD::RMC01SD(), SensitiveDetector::SensitiveDetector(), TrackerSD::TrackerSD(), UltraPMTSD::UltraPMTSD(), WLSPhotonDetSD::WLSPhotonDetSD(), XAluminumElectrodeSensitivity::XAluminumElectrodeSensitivity(), XrayFluoHPGeSD::XrayFluoHPGeSD(), and XrayFluoSD::XrayFluoSD().
filter
G4VSDFilter* G4VSensitiveDetector::filter protected
Definition at line 110 of file G4VSensitiveDetector.hh.
Referenced by G4VSensitiveDetector(), GetFilter(), Hit(), operator=(), and SetFilter().
fullPathName
G4String G4VSensitiveDetector::fullPathName protected
Definition at line 106 of file G4VSensitiveDetector.hh.
Referenced by G4VSensitiveDetector(), GetFullPathName(), and operator=().
ROgeometry
G4VReadOutGeometry* G4VSensitiveDetector::ROgeometry protected
Definition at line 109 of file G4VSensitiveDetector.hh.
Referenced by G4VSensitiveDetector(), GetROgeometry(), Hit(), operator=(), and SetROgeometry().
SensitiveDetectorName
G4String G4VSensitiveDetector::SensitiveDetectorName protected
Definition at line 104 of file G4VSensitiveDetector.hh.
Referenced by G4VSensitiveDetector(), GetCollectionID(), GetName(), H02MuonSD::Initialize(), G4HumanPhantomSD::Initialize(), ExN04CalorimeterSD::Initialize(), RE01TrackerSD::Initialize(), RE05CalorimeterSD::Initialize(), ExN04TrackerSD::Initialize(), RE05TrackerSD::Initialize(), ExN04MuonSD::Initialize(), Par01CalorimeterSD::Initialize(), RE05MuonSD::Initialize(), B5HodoscopeSD::Initialize(), ExTGTrackerSD::Initialize(), RE01CalorimeterSD::Initialize(), eRositaTrackerSD::Initialize(), LXeScintSD::Initialize(), B5HadCalorimeterSD::Initialize(), XAluminumElectrodeSensitivity::Initialize(), B5DriftChamberSD::Initialize(), B5EmCalorimeterSD::Initialize(), LXePMTSD::Initialize(), ExGflashSensitiveDetector::Initialize(), SensitiveDetector::Initialize(), ExN02TrackerSD::Initialize(), WLSPhotonDetSD::Initialize(), F02CalorimeterSD::Initialize(), ExP01TrackerSD::Initialize(), F01CalorimeterSD::Initialize(), F03CalorimeterSD::Initialize(), XrayFluoHPGeSD::Initialize(), GammaRayTelAnticoincidenceSD::Initialize(), GammaRayTelTrackerSD::Initialize(), GammaRayTelCalorimeterSD::Initialize(), B2TrackerSD::Initialize(), B4cCalorimeterSD::Initialize(), TrackerSD::Initialize(), DMXScintSD::Initialize(), UltraPMTSD::Initialize(), DMXPmtSD::Initialize(), XrayFluoSD::Initialize(), RMC01SD::Initialize(), operator=(), G4MultiFunctionalDetector::RegisterPrimitive(), and G4MultiFunctionalDetector::RemovePrimitive().
thePathName
G4String G4VSensitiveDetector::thePathName protected
Definition at line 105 of file G4VSensitiveDetector.hh.
Referenced by G4VSensitiveDetector(), GetPathName(), and operator=().
verboseLevel
G4int G4VSensitiveDetector::verboseLevel protected
Definition at line 107 of file G4VSensitiveDetector.hh.
Referenced by eRositaTrackerSD::EndOfEvent(), ExN02TrackerSD::EndOfEvent(), B2TrackerSD::EndOfEvent(), B4cCalorimeterSD::EndOfEvent(), DMXScintSD::EndOfEvent(), DMXPmtSD::EndOfEvent(), G4MultiSensitiveDetector::G4MultiSensitiveDetector(), G4VSensitiveDetector(), ExN04CalorimeterSD::Initialize(), RE05CalorimeterSD::Initialize(), operator=(), ExN04CalorimeterSD::ProcessHits(), RE05CalorimeterSD::ProcessHits(), Par01CalorimeterSD::ProcessHits(), RE01CalorimeterSD::ProcessHits(), F02CalorimeterSD::ProcessHits(), F03CalorimeterSD::ProcessHits(), F01CalorimeterSD::ProcessHits(), XrayFluoHPGeSD::ProcessHits(), XrayFluoSD::ProcessHits(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
source/digits_hits/detector/include/G4VSensitiveDetector.hh
source/digits_hits/detector/src/G4VSensitiveDetector.cc