Geant4: G4Region Class Reference
G4Region Class Reference
#include <G4Region.hh>
Public Member Functions
G4Region (const G4String &name)
virtual ~G4Region ()
G4bool operator== (const G4Region &rg) const
void AddRootLogicalVolume (G4LogicalVolume *lv, G4bool search=true)
void RemoveRootLogicalVolume (G4LogicalVolume *lv, G4bool scan=true)
void SetName (const G4String &name)
const G4String & GetName () const
void RegionModified (G4bool flag)
G4bool IsModified () const
void SetProductionCuts (G4ProductionCuts *cut)
G4ProductionCuts * GetProductionCuts () const
std::vector< G4LogicalVolume * >::iterator GetRootLogicalVolumeIterator ()
std::vector< G4Material * >::const_iterator GetMaterialIterator () const
size_t GetNumberOfMaterials () const
size_t GetNumberOfRootVolumes () const
void UpdateMaterialList ()
void ClearMaterialList ()
void ScanVolumeTree (G4LogicalVolume *lv, G4bool region)
void SetUserInformation (G4VUserRegionInformation *ui)
G4VUserRegionInformation * GetUserInformation () const
void SetUserLimits (G4UserLimits *ul)
G4UserLimits * GetUserLimits () const
void ClearMap ()
void RegisterMaterialCouplePair (G4Material *mat, G4MaterialCutsCouple *couple)
G4MaterialCutsCouple * FindCouple (G4Material *mat)
void SetFastSimulationManager (G4FastSimulationManager *fsm)
G4FastSimulationManager * GetFastSimulationManager () const
void ClearFastSimulationManager ()
void SetFieldManager (G4FieldManager *fm)
G4FieldManager * GetFieldManager () const
G4VPhysicalVolume * GetWorldPhysical () const
void SetWorld (G4VPhysicalVolume *wp)
G4bool BelongsTo (G4VPhysicalVolume *thePhys) const
G4Region * GetParentRegion (G4bool &unique) const
void SetRegionalSteppingAction (G4UserSteppingAction *rusa)
G4UserSteppingAction * GetRegionalSteppingAction () const
G4Region (__void__ &)
G4int GetInstanceID () const
void UsedInMassGeometry (G4bool val=true)
void UsedInParallelGeometry (G4bool val=true)
G4bool IsInMassGeometry () const
G4bool IsInParallelGeometry () const
Static Public Member Functions
static const G4RegionManager & GetSubInstanceManager ()
static void Clean ()
Private Types
typedef std::vector< G4LogicalVolume * > G4RootLVList
typedef std::vector< G4Material * > G4MaterialList
typedef std::pair< G4Material *, G4MaterialCutsCouple * > G4MaterialCouplePair
typedef std::map< G4Material *, G4MaterialCutsCouple * > G4MaterialCoupleMap
Private Member Functions
G4Region (const G4Region &)
G4Region & operator= (const G4Region &)
void AddMaterial (G4Material *aMaterial)
Private Attributes
G4String fName
G4RootLVList fRootVolumes
G4MaterialList fMaterials
G4MaterialCoupleMap fMaterialCoupleMap
G4bool fRegionMod
G4ProductionCuts * fCut
G4VUserRegionInformation * fUserInfo
G4UserLimits * fUserLimits
G4FieldManager * fFieldManager
G4VPhysicalVolume * fWorldPhys
G4bool fInMassGeometry
G4bool fInParallelGeometry
G4int instanceID
Static Private Attributes
static G4GEOM_DLL G4RegionManager subInstanceManager
Detailed Description
Definition at line 98 of file G4Region.hh.
Member Typedef Documentation
G4MaterialCoupleMap
typedef std::map<G4Material*,G4MaterialCutsCouple*> G4Region::G4MaterialCoupleMap private
Definition at line 103 of file G4Region.hh.
G4MaterialCouplePair
typedef std::pair<G4Material*,G4MaterialCutsCouple*> G4Region::G4MaterialCouplePair private
Definition at line 102 of file G4Region.hh.
G4MaterialList
typedef std::vector<G4Material*> G4Region::G4MaterialList private
Definition at line 101 of file G4Region.hh.
G4RootLVList
typedef std::vector<G4LogicalVolume*> G4Region::G4RootLVList private
Definition at line 100 of file G4Region.hh.
Constructor & Destructor Documentation
G4Region() [1/3]
G4Region::G4Region (const G4String & name)
Definition at line 67 of file G4Region.cc.
~G4Region()
G4Region::~G4Region () virtual
Definition at line 117 of file G4Region.cc.
G4Region() [2/3]
G4Region::G4Region (__void__ &)
Definition at line 98 of file G4Region.cc.
G4Region() [3/3]
G4Region::G4Region (const G4Region &) private
Member Function Documentation
AddMaterial()
void G4Region::AddMaterial (G4Material * aMaterial) inline private
Referenced by ScanVolumeTree().
AddRootLogicalVolume()
void G4Region::AddRootLogicalVolume (G4LogicalVolume * lv, G4bool search = true)
Definition at line 289 of file G4Region.cc.
Referenced by G4RunManagerKernel::CheckRegions(), Par01ParallelWorldForPion::Construct(), Par01DetectorConstruction::Construct(), RE01DetectorConstruction::Construct(), DetectorBarr90::Construct(), DetectorHarris73::Construct(), DetectorWatase86::Construct(), DetectorSimpleALICE::Construct(), DetectorALICE06::Construct(), DetectorBari05::Construct(), ExGflashDetectorConstruction::Construct(), CML2Ph_BoxInBox::Construct(), CML2Ph_FullWater::Construct(), HadrontherapyDetectorConstruction::ConstructDetector(), DetectorConstruction::ConstructDetector(), G4RunManagerKernel::DefineWorldVolume(), export_G4Region(), CML2Acc1::flatteningFilter(), CML2Acc2::flatteningFilter(), CML2AccSaturn::flatteningFilter(), G4GDMLParser::ImportRegions(), CML2Acc1::ionizationChamber(), CML2Acc2::ionizationChamber(), CML2Acc1::Jaw1X(), CML2Acc2::Jaw1X(), CML2AccSaturn::Jaw1X(), CML2Acc2::Jaw1Y(), CML2AccSaturn::Jaw1Y(), CML2Acc2::Jaw2X(), CML2Acc2::Jaw2Y(), CML2Acc2::MLC(), CML2Acc1::primaryCollimator(), CML2Acc2::primaryCollimator(), G4ReflectionFactory::ReflectLV(), RE06DetectorConstruction::SetupGeometry(), CexmcSetup::SetupSpecialVolumes(), CML2Acc2::target(), and CML2Acc2::vacuumWindow().
BelongsTo()
G4bool G4Region::BelongsTo (G4VPhysicalVolume * thePhys) const
Definition at line 413 of file G4Region.cc.
Referenced by G4RunManagerKernel::CheckRegions(), export_G4Region(), and SetWorld().
Clean()
void G4Region::Clean () static
Definition at line 354 of file G4Region.cc.
Referenced by G4RegionStore::~G4RegionStore().
ClearFastSimulationManager()
void G4Region::ClearFastSimulationManager ()
Definition at line 433 of file G4Region.cc.
Referenced by export_G4Region(), and G4FastSimulationManager::~G4FastSimulationManager().
ClearMap()
void G4Region::ClearMap () inline
Referenced by export_G4Region().
ClearMaterialList()
void G4Region::ClearMaterialList ()
Definition at line 364 of file G4Region.cc.
Referenced by export_G4Region(), and UpdateMaterialList().
FindCouple()
G4MaterialCutsCouple* G4Region::FindCouple (G4Material * mat) inline
Referenced by export_G4Region(), and G4LogicalVolume::UpdateMaterial().
GetFastSimulationManager()
G4FastSimulationManager * G4Region::GetFastSimulationManager () const
Definition at line 136 of file G4Region.cc.
Referenced by ClearFastSimulationManager(), G4GlobalFastSimulationManager::DisplayRegion(), G4RunManagerKernel::DumpRegion(), export_G4Region(), G4VFastSimulationModel::G4VFastSimulationModel(), and G4FastSimulationManager::~G4FastSimulationManager().
GetFieldManager()
G4FieldManager* G4Region::GetFieldManager () const inline
Referenced by G4MagneticFieldModel::DescribeYourselfTo(), and G4PropagatorInField::FindAndSetFieldManager().
GetInstanceID()
G4int G4Region::GetInstanceID () const inline
GetMaterialIterator()
std::vector<G4Material*>::const_iterator G4Region::GetMaterialIterator () const inline
Referenced by G4RunManagerKernel::DumpRegion(), and G4ProductionCutsTable::IsCoupleUsedInTheRegion().
GetName()
const G4String& G4Region::GetName () const inline
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4RunManagerKernel::CheckRegions(), G4PhysicalVolumeModel::CreateCurrentAttValues(), G4RunManagerKernel::DefineWorldVolume(), G4GlobalFastSimulationManager::DisplayRegion(), G4RunManagerKernel::DumpRegion(), RE06RunAction::EndOfRunAction(), export_G4Region(), G4EmCalculator::FindCouple(), G4NeutrinoElectronProcess::GetMeanFreePath(), G4PAIPhotModel::Initialise(), G4EmBiasingManager::Initialise(), G4PAIModel::Initialise(), G4EmModelManager::Initialise(), G4FastSimulationManager::ListTitle(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VEnergyLossProcess::PreparePhysicsTable(), and G4GlobalFastSimulationManager::ShowSetup().
GetNumberOfMaterials()
size_t G4Region::GetNumberOfMaterials () const inline
Referenced by G4RunManagerKernel::DumpRegion(), export_G4Region(), and G4ProductionCutsTable::IsCoupleUsedInTheRegion().
GetNumberOfRootVolumes()
size_t G4Region::GetNumberOfRootVolumes () const inline
Referenced by G4RunManagerKernel::DumpRegion(), export_G4Region(), and G4RunManagerKernel::SetupDefaultRegion().
GetParentRegion()
G4Region * G4Region::GetParentRegion (G4bool & unique) const
Definition at line 468 of file G4Region.cc.
Referenced by ClearFastSimulationManager(), and export_G4Region().
GetProductionCuts()
G4ProductionCuts* G4Region::GetProductionCuts () const inline
Referenced by G4RunManagerKernel::CheckRegions(), Par01DetectorConstruction::Construct(), G4RunManagerKernel::DumpRegion(), RE06RunAction::EndOfRunAction(), export_G4Region(), G4GDMLWriteStructure::ExportEnergyCuts(), G4EmCalculator::FindCouple(), G4VUserPhysicsList::GetCutValue(), G4ProductionCutsTable::IsCoupleUsedInTheRegion(), G4VUserPhysicsList::SetParticleCuts(), and G4ParallelWorldProcess::SwitchMaterial().
GetRegionalSteppingAction()
G4UserSteppingAction * G4Region::GetRegionalSteppingAction () const
Definition at line 154 of file G4Region.cc.
Referenced by G4RunManagerKernel::DumpRegion(), and G4SteppingManager::Stepping().
GetRootLogicalVolumeIterator()
std::vector<G4LogicalVolume*>::iterator G4Region::GetRootLogicalVolumeIterator () inline
Referenced by G4RunManagerKernel::DumpRegion(), and G4RunManagerKernel::SetupDefaultRegion().
GetSubInstanceManager()
const G4RegionManager & G4Region::GetSubInstanceManager () static
Definition at line 57 of file G4Region.cc.
Referenced by G4GeometryWorkspace::G4GeometryWorkspace().
GetUserInformation()
G4VUserRegionInformation* G4Region::GetUserInformation () const inline
Referenced by G4RunManagerKernel::DumpRegion(), export_G4Region(), and RE01SteppingAction::UserSteppingAction().
GetUserLimits()
G4UserLimits* G4Region::GetUserLimits () const inline
Referenced by G4RunManagerKernel::DumpRegion(), and export_G4Region().
GetWorldPhysical()
G4VPhysicalVolume* G4Region::GetWorldPhysical () const inline
Referenced by G4RunManagerKernel::DumpRegion(), export_G4Region(), and G4FastSimulationManager::ListTitle().
IsInMassGeometry()
G4bool G4Region::IsInMassGeometry () const inline
Referenced by G4RunManagerKernel::CheckRegions(), and G4RunManagerKernel::DumpRegion().
IsInParallelGeometry()
G4bool G4Region::IsInParallelGeometry () const inline
Referenced by G4RunManagerKernel::CheckRegions(), and G4RunManagerKernel::DumpRegion().
IsModified()
G4bool G4Region::IsModified () const inline
Referenced by export_G4Region().
operator=()
G4Region& G4Region::operator= (const G4Region &) private
operator==()
G4bool G4Region::operator== (const G4Region & rg) const inline
RegionModified()
void G4Region::RegionModified (G4bool flag) inline
Referenced by G4LogicalVolume::AddDaughter(), G4LogicalVolume::ClearDaughters(), export_G4Region(), and G4LogicalVolume::RemoveDaughter().
RegisterMaterialCouplePair()
void G4Region::RegisterMaterialCouplePair (G4Material * mat, G4MaterialCutsCouple * couple) inline
Referenced by export_G4Region().
RemoveRootLogicalVolume()
void G4Region::RemoveRootLogicalVolume (G4LogicalVolume * lv, G4bool scan = true)
Definition at line 325 of file G4Region.cc.
Referenced by export_G4Region(), G4RunManagerKernel::SetupDefaultRegion(), XrayFluoDetectorConstruction::UpdateGeometry(), and G4LogicalVolume::~G4LogicalVolume().
ScanVolumeTree()
void G4Region::ScanVolumeTree (G4LogicalVolume * lv, G4bool region)
Definition at line 168 of file G4Region.cc.
Referenced by AddRootLogicalVolume(), export_G4Region(), and UpdateMaterialList().
SetFastSimulationManager()
void G4Region::SetFastSimulationManager (G4FastSimulationManager * fsm)
Definition at line 127 of file G4Region.cc.
Referenced by export_G4Region(), and G4FastSimulationManager::G4FastSimulationManager().
SetFieldManager()
void G4Region::SetFieldManager (G4FieldManager * fm) inline
SetName()
void G4Region::SetName (const G4String & name) inline
Referenced by export_G4Region().
SetProductionCuts()
void G4Region::SetProductionCuts (G4ProductionCuts * cut) inline
Referenced by G4RunManagerKernel::CheckRegions(), Par01DetectorConstruction::Construct(), CML2Ph_BoxInBox::Construct(), CML2Ph_FullWater::Construct(), DetectorConstruction::ConstructDetector(), G4RunManagerKernel::DumpRegion(), export_G4Region(), CML2Acc1::flatteningFilter(), CML2Acc2::flatteningFilter(), CML2AccSaturn::flatteningFilter(), G4RunManagerKernel::G4RunManagerKernel(), G4GDMLParser::ImportRegions(), CML2Acc1::ionizationChamber(), CML2Acc1::Jaw1X(), CML2Acc2::Jaw1X(), CML2Acc2::Jaw1Y(), CML2AccSaturn::Jaw1Y(), CML2Acc2::Jaw2X(), CML2AccSaturn::Jaw2X(), CML2Acc2::Jaw2Y(), CML2Acc2::MLC(), CML2Acc1::primaryCollimator(), CML2Acc2::primaryCollimator(), CML2AccSaturn::primaryCollimator(), G4VUserPhysicsList::SetParticleCuts(), CexmcSetup::SetupSpecialVolumes(), CML2Acc1::target(), CML2Acc2::target(), CML2Acc1::vacuumWindow(), CML2Acc2::vacuumWindow(), and CML2AccSaturn::vacuumWindow().
SetRegionalSteppingAction()
void G4Region::SetRegionalSteppingAction (G4UserSteppingAction * rusa)
Definition at line 145 of file G4Region.cc.
SetUserInformation()
void G4Region::SetUserInformation (G4VUserRegionInformation * ui) inline
Referenced by RE01DetectorConstruction::Construct(), and export_G4Region().
SetUserLimits()
void G4Region::SetUserLimits (G4UserLimits * ul) inline
Referenced by export_G4Region(), and G4GDMLParser::ImportRegions().
SetWorld()
void G4Region::SetWorld (G4VPhysicalVolume * wp)
Definition at line 397 of file G4Region.cc.
Referenced by G4RunManagerKernel::CheckRegions(), and export_G4Region().
UpdateMaterialList()
void G4Region::UpdateMaterialList ()
Definition at line 375 of file G4Region.cc.
Referenced by export_G4Region(), and RemoveRootLogicalVolume().
UsedInMassGeometry()
void G4Region::UsedInMassGeometry (G4bool val = true) inline
Referenced by G4RunManagerKernel::CheckRegions().
UsedInParallelGeometry()
void G4Region::UsedInParallelGeometry (G4bool val = true) inline
Referenced by G4RunManagerKernel::CheckRegions().
Field Documentation
fCut
G4ProductionCuts* G4Region::fCut private
Definition at line 261 of file G4Region.hh.
fFieldManager
G4FieldManager* G4Region::fFieldManager private
Definition at line 265 of file G4Region.hh.
fInMassGeometry
G4bool G4Region::fInMassGeometry private
Definition at line 269 of file G4Region.hh.
Referenced by ScanVolumeTree().
fInParallelGeometry
G4bool G4Region::fInParallelGeometry private
Definition at line 270 of file G4Region.hh.
fMaterialCoupleMap
G4MaterialCoupleMap G4Region::fMaterialCoupleMap private
Definition at line 258 of file G4Region.hh.
fMaterials
G4MaterialList G4Region::fMaterials private
Definition at line 257 of file G4Region.hh.
Referenced by ClearMaterialList().
fName
G4String G4Region::fName private
Definition at line 254 of file G4Region.hh.
Referenced by ClearFastSimulationManager().
fRegionMod
G4bool G4Region::fRegionMod private
Definition at line 260 of file G4Region.hh.
Referenced by AddRootLogicalVolume(), and RemoveRootLogicalVolume().
fRootVolumes
G4RootLVList G4Region::fRootVolumes private
Definition at line 256 of file G4Region.hh.
Referenced by AddRootLogicalVolume(), RemoveRootLogicalVolume(), and UpdateMaterialList().
fUserInfo
G4VUserRegionInformation* G4Region::fUserInfo private
Definition at line 263 of file G4Region.hh.
Referenced by ~G4Region().
fUserLimits
G4UserLimits* G4Region::fUserLimits private
Definition at line 264 of file G4Region.hh.
fWorldPhys
G4VPhysicalVolume* G4Region::fWorldPhys private
Definition at line 267 of file G4Region.hh.
Referenced by SetWorld().
instanceID
G4int G4Region::instanceID private
Definition at line 272 of file G4Region.hh.
Referenced by G4Region().
subInstanceManager
G4RegionManager G4Region::subInstanceManager static private
Definition at line 274 of file G4Region.hh.
Referenced by Clean(), G4Region(), and GetSubInstanceManager().
The documentation for this class was generated from the following files:
source/geometry/management/include/G4Region.hh
source/geometry/management/src/G4Region.cc