Geant4: G4PhysicalVolumeModel Class Reference
G4PhysicalVolumeModel Class Reference
#include <G4PhysicalVolumeModel.hh>
Data Structures
class G4PhysicalVolumeModelTouchable
class G4PhysicalVolumeNodeID
struct TouchableProperties
Public Types
enum { UNLIMITED = -1 }
enum ClippingMode { subtraction, intersection }
Public Member Functions
G4PhysicalVolumeModel (G4VPhysicalVolume *=0, G4int requestedDepth=UNLIMITED, const G4Transform3D &modelTransformation=G4Transform3D(), const G4ModelingParameters *=0, G4bool useFullExtent=false, const std::vector< G4PhysicalVolumeNodeID > &baseFullPVPath=std::vector< G4PhysicalVolumeNodeID >())
virtual ~G4PhysicalVolumeModel ()
void DescribeYourselfTo (G4VGraphicsScene &)
G4String GetCurrentDescription () const
G4String GetCurrentTag () const
G4VPhysicalVolume * GetTopPhysicalVolume () const
G4int GetRequestedDepth () const
const G4VSolid * GetClippingSolid () const
G4int GetCurrentDepth () const
G4VPhysicalVolume * GetCurrentPV () const
G4int GetCurrentPVCopyNo () const
G4LogicalVolume * GetCurrentLV () const
G4Material * GetCurrentMaterial () const
G4Transform3D * GetCurrentTransform () const
const std::vector< G4PhysicalVolumeNodeID > & GetBaseFullPVPath () const
const std::vector< G4PhysicalVolumeNodeID > & GetFullPVPath () const
const std::vector< G4PhysicalVolumeNodeID > & GetDrawnPVPath () const
const std::map< G4String, G4AttDef > * GetAttDefs () const
std::vector< G4AttValue > * CreateCurrentAttValues () const
void SetRequestedDepth (G4int requestedDepth)
void SetClippingSolid (G4VSolid *pClippingSolid)
void SetClippingMode (ClippingMode mode)
G4bool Validate (G4bool warn)
void Abort () const
void CurtailDescent () const
Public Member Functions inherited from G4VModel
G4VModel (const G4Transform3D &modelTransformation=G4Transform3D(), const G4ModelingParameters *=0)
virtual ~G4VModel ()
const G4ModelingParameters * GetModelingParameters () const
const G4String & GetType () const
const G4VisExtent & GetExtent () const
const G4String & GetGlobalDescription () const
const G4String & GetGlobalTag () const
const G4Transform3D & GetTransformation () const
void SetModelingParameters (const G4ModelingParameters *)
void SetExtent (const G4VisExtent &)
void SetType (const G4String &)
void SetGlobalDescription (const G4String &)
void SetGlobalTag (const G4String &)
void SetTransformation (const G4Transform3D &)
Static Public Member Functions
static G4ModelingParameters::PVNameCopyNoPath GetPVNameCopyNoPath (const std::vector< G4PhysicalVolumeNodeID > &)
Protected Member Functions
void VisitGeometryAndGetVisReps (G4VPhysicalVolume *, G4int requestedDepth, const G4Transform3D &, G4VGraphicsScene &)
void DescribeAndDescend (G4VPhysicalVolume *, G4int requestedDepth, G4LogicalVolume *, G4VSolid *, G4Material *, const G4Transform3D &, G4VGraphicsScene &)
virtual void DescribeSolid (const G4Transform3D &theAT, G4VSolid *pSol, const G4VisAttributes *pVisAttribs, G4VGraphicsScene &sceneHandler)
void CalculateExtent ()
Protected Attributes
G4VPhysicalVolume * fpTopPV
G4String fTopPVName
G4int fTopPVCopyNo
G4int fRequestedDepth
G4bool fUseFullExtent
G4int fCurrentDepth
G4VPhysicalVolume * fpCurrentPV
G4int fCurrentPVCopyNo
G4LogicalVolume * fpCurrentLV
G4Material * fpCurrentMaterial
G4Transform3D * fpCurrentTransform
std::vector< G4PhysicalVolumeNodeID > fBaseFullPVPath
std::vector< G4PhysicalVolumeNodeID > fFullPVPath
std::vector< G4PhysicalVolumeNodeID > fDrawnPVPath
G4bool fAbort
G4bool fCurtailDescent
G4VSolid * fpClippingSolid
ClippingMode fClippingMode
Protected Attributes inherited from G4VModel
G4String fType
G4String fGlobalTag
G4String fGlobalDescription
G4VisExtent fExtent
G4Transform3D fTransform
const G4ModelingParameters * fpMP
Private Member Functions
G4PhysicalVolumeModel (const G4PhysicalVolumeModel &)
G4PhysicalVolumeModel & operator= (const G4PhysicalVolumeModel &)
Detailed Description
Definition at line 82 of file G4PhysicalVolumeModel.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
UNLIMITED
Definition at line 86 of file G4PhysicalVolumeModel.hh.
ClippingMode
enum G4PhysicalVolumeModel::ClippingMode
Enumerator
subtraction
intersection
Definition at line 88 of file G4PhysicalVolumeModel.hh.
Constructor & Destructor Documentation
G4PhysicalVolumeModel() [1/2]
G4PhysicalVolumeModel::G4PhysicalVolumeModel (G4VPhysicalVolume * pVPV = 0, G4int requestedDepth = UNLIMITED, const G4Transform3D & modelTransformation = G4Transform3D(), const G4ModelingParameters * pMP = 0, G4bool useFullExtent = false, const std::vector< G4PhysicalVolumeNodeID > & baseFullPVPath = std::vector<G4PhysicalVolumeNodeID>())
Definition at line 58 of file G4PhysicalVolumeModel.cc.
~G4PhysicalVolumeModel()
G4PhysicalVolumeModel::~G4PhysicalVolumeModel () virtual
Definition at line 110 of file G4PhysicalVolumeModel.cc.
G4PhysicalVolumeModel() [2/2]
G4PhysicalVolumeModel::G4PhysicalVolumeModel (const G4PhysicalVolumeModel &) private
Member Function Documentation
Abort()
void G4PhysicalVolumeModel::Abort () const inline
Definition at line 243 of file G4PhysicalVolumeModel.hh.
Referenced by G4TouchablePropertiesScene::ProcessVolume().
CalculateExtent()
void G4PhysicalVolumeModel::CalculateExtent () protected
Definition at line 127 of file G4PhysicalVolumeModel.cc.
Referenced by Validate().
CreateCurrentAttValues()
std::vector< G4AttValue > * G4PhysicalVolumeModel::CreateCurrentAttValues () const
Definition at line 875 of file G4PhysicalVolumeModel.cc.
Referenced by G4VSceneHandler::LoadAtts(), G4XXXStoredSceneHandler::PreAddSolid(), G4ASCIITreeSceneHandler::RequestPrimitives(), and G4VisCommandsTouchable::SetNewValue().
CurtailDescent()
void G4PhysicalVolumeModel::CurtailDescent () const inline
Definition at line 246 of file G4PhysicalVolumeModel.hh.
Referenced by G4BoundingSphereScene::ProcessVolume(), and G4ASCIITreeSceneHandler::RequestPrimitives().
DescribeAndDescend()
void G4PhysicalVolumeModel::DescribeAndDescend (G4VPhysicalVolume * pVPV, G4int requestedDepth, G4LogicalVolume * pLV, G4VSolid * pSol, G4Material * pMaterial, const G4Transform3D & theAT, G4VGraphicsScene & sceneHandler) protected
Definition at line 358 of file G4PhysicalVolumeModel.cc.
DescribeSolid()
void G4PhysicalVolumeModel::DescribeSolid (const G4Transform3D & theAT, G4VSolid * pSol, const G4VisAttributes * pVisAttribs, G4VGraphicsScene & sceneHandler) protected virtual
Reimplemented in G4LogicalVolumeModel.
Definition at line 651 of file G4PhysicalVolumeModel.cc.
DescribeYourselfTo()
void G4PhysicalVolumeModel::DescribeYourselfTo (G4VGraphicsScene & sceneHandler) virtual
Implements G4VModel.
Definition at line 167 of file G4PhysicalVolumeModel.cc.
Referenced by CalculateExtent(), G4LogicalVolumeModel::DescribeYourselfTo(), G4ASCIITreeSceneHandler::EndModeling(), G4TouchableUtils::FindTouchableProperties(), G4VisCommandsTouchable::SetNewValue(), G4VisCommandSetTouchable::SetNewValue(), G4VisCommandSceneAddVolume::SetNewValue(), and Validate().
GetAttDefs()
const std::map< G4String, G4AttDef > * G4PhysicalVolumeModel::GetAttDefs () const
Definition at line 798 of file G4PhysicalVolumeModel.cc.
Referenced by G4VSceneHandler::LoadAtts(), G4XXXStoredSceneHandler::PreAddSolid(), G4ASCIITreeSceneHandler::RequestPrimitives(), G4VisCommandsTouchable::SetNewValue(), and G4VisCommandList::SetNewValue().
GetBaseFullPVPath()
const std::vector<G4PhysicalVolumeNodeID>& G4PhysicalVolumeModel::GetBaseFullPVPath () const inline
Definition at line 190 of file G4PhysicalVolumeModel.hh.
GetClippingSolid()
const G4VSolid* G4PhysicalVolumeModel::GetClippingSolid () const inline
Definition at line 169 of file G4PhysicalVolumeModel.hh.
GetCurrentDepth()
G4int G4PhysicalVolumeModel::GetCurrentDepth () const inline
Definition at line 172 of file G4PhysicalVolumeModel.hh.
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4HepRepSceneHandler::AddPrimitive(), G4HepRepSceneHandler::AddSolid(), G4GMocrenFileSceneHandler::AddSolid(), G4HepRepSceneHandler::getGeometryOrEventInstance(), G4PhysicalVolumeSearchScene::ProcessVolume(), G4PhysicalVolumeMassScene::ProcessVolume(), and G4PhysicalVolumesSearchScene::ProcessVolume().
GetCurrentDescription()
G4String G4PhysicalVolumeModel::GetCurrentDescription () const virtual
Reimplemented from G4VModel.
Definition at line 209 of file G4PhysicalVolumeModel.cc.
GetCurrentLV()
G4LogicalVolume* G4PhysicalVolumeModel::GetCurrentLV () const inline
Definition at line 181 of file G4PhysicalVolumeModel.hh.
Referenced by G4GMocrenFileSceneHandler::AddDetector(), G4HepRepFileSceneHandler::AddHepRepInstance(), G4GMocrenFileSceneHandler::AddPrimitive(), G4HepRepSceneHandler::AddSolid(), G4HepRepSceneHandler::getGeometryOrEventInstance(), and G4ASCIITreeSceneHandler::RequestPrimitives().
GetCurrentMaterial()
G4Material* G4PhysicalVolumeModel::GetCurrentMaterial () const inline
Definition at line 184 of file G4PhysicalVolumeModel.hh.
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4HepRepSceneHandler::AddSolid(), G4GMocrenFileSceneHandler::AddSolid(), G4HepRepSceneHandler::getGeometryOrEventInstance(), G4PhysicalVolumeMassScene::ProcessVolume(), and G4ASCIITreeSceneHandler::RequestPrimitives().
GetCurrentPV()
G4VPhysicalVolume* G4PhysicalVolumeModel::GetCurrentPV () const inline
Definition at line 175 of file G4PhysicalVolumeModel.hh.
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4GMocrenFileSceneHandler::AddPrimitive(), G4GMocrenFileSceneHandler::AddSolid(), G4TouchablePropertiesScene::ProcessVolume(), G4PhysicalVolumeSearchScene::ProcessVolume(), G4PhysicalVolumeMassScene::ProcessVolume(), G4PhysicalVolumesSearchScene::ProcessVolume(), and G4ASCIITreeSceneHandler::RequestPrimitives().
GetCurrentPVCopyNo()
G4int G4PhysicalVolumeModel::GetCurrentPVCopyNo () const inline
Definition at line 178 of file G4PhysicalVolumeModel.hh.
Referenced by G4PhysicalVolumesSearchScene::ProcessVolume().
GetCurrentTag()
G4String G4PhysicalVolumeModel::GetCurrentTag () const virtual
Reimplemented from G4VModel.
Definition at line 197 of file G4PhysicalVolumeModel.cc.
Referenced by GetCurrentDescription().
GetCurrentTransform()
G4Transform3D* G4PhysicalVolumeModel::GetCurrentTransform () const inline
Definition at line 187 of file G4PhysicalVolumeModel.hh.
Referenced by G4TouchablePropertiesScene::ProcessVolume(), G4ASCIITreeSceneHandler::RequestPrimitives(), and G4VisCommandsTouchable::SetNewValue().
GetDrawnPVPath()
const std::vector<G4PhysicalVolumeNodeID>& G4PhysicalVolumeModel::GetDrawnPVPath () const inline
Definition at line 204 of file G4PhysicalVolumeModel.hh.
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4GMocrenFileSceneHandler::AddSolid(), G4XXXSGSceneHandler::CreateCurrentItem(), G4VTreeSceneHandler::PreAddSolid(), and G4ASCIITreeSceneHandler::RequestPrimitives().
GetFullPVPath()
const std::vector<G4PhysicalVolumeNodeID>& G4PhysicalVolumeModel::GetFullPVPath () const inline
Definition at line 197 of file G4PhysicalVolumeModel.hh.
Referenced by G4RayTracerSceneHandler::BuildVisAttsMap(), G4TouchablePropertiesScene::ProcessVolume(), G4PhysicalVolumeSearchScene::ProcessVolume(), G4PhysicalVolumesSearchScene::ProcessVolume(), and G4VSceneHandler::RequestPrimitives().
GetPVNameCopyNoPath()
G4ModelingParameters::PVNameCopyNoPath G4PhysicalVolumeModel::GetPVNameCopyNoPath (const std::vector< G4PhysicalVolumeNodeID > & path) static
Definition at line 116 of file G4PhysicalVolumeModel.cc.
Referenced by G4VViewer::TouchableSetColour(), and G4VViewer::TouchableSetVisibility().
GetRequestedDepth()
G4int G4PhysicalVolumeModel::GetRequestedDepth () const inline
Definition at line 167 of file G4PhysicalVolumeModel.hh.
Referenced by G4ASCIITreeSceneHandler::EndModeling().
GetTopPhysicalVolume()
G4VPhysicalVolume* G4PhysicalVolumeModel::GetTopPhysicalVolume () const inline
Definition at line 165 of file G4PhysicalVolumeModel.hh.
Referenced by G4GMocrenFileSceneHandler::AddSolid(), G4ASCIITreeSceneHandler::EndModeling(), and G4PhysicalVolumesSearchScene::ProcessVolume().
operator=()
G4PhysicalVolumeModel& G4PhysicalVolumeModel::operator= (const G4PhysicalVolumeModel &) private
SetClippingMode()
void G4PhysicalVolumeModel::SetClippingMode (ClippingMode mode) inline
Definition at line 236 of file G4PhysicalVolumeModel.hh.
Referenced by G4VisCommandSceneAddVolume::SetNewValue().
SetClippingSolid()
void G4PhysicalVolumeModel::SetClippingSolid (G4VSolid * pClippingSolid) inline
Definition at line 232 of file G4PhysicalVolumeModel.hh.
Referenced by G4VisCommandSceneAddVolume::SetNewValue().
SetRequestedDepth()
void G4PhysicalVolumeModel::SetRequestedDepth (G4int requestedDepth) inline
Definition at line 228 of file G4PhysicalVolumeModel.hh.
Validate()
G4bool G4PhysicalVolumeModel::Validate (G4bool warn) virtual
Reimplemented from G4VModel.
Definition at line 743 of file G4PhysicalVolumeModel.cc.
VisitGeometryAndGetVisReps()
void G4PhysicalVolumeModel::VisitGeometryAndGetVisReps (G4VPhysicalVolume * pVPV, G4int requestedDepth, const G4Transform3D & theAT, G4VGraphicsScene & sceneHandler) protected
Definition at line 215 of file G4PhysicalVolumeModel.cc.
Field Documentation
fAbort
G4bool G4PhysicalVolumeModel::fAbort mutable protected
Definition at line 289 of file G4PhysicalVolumeModel.hh.
Referenced by Abort().
fBaseFullPVPath
std::vector<G4PhysicalVolumeNodeID> G4PhysicalVolumeModel::fBaseFullPVPath protected
Definition at line 286 of file G4PhysicalVolumeModel.hh.
Referenced by CreateCurrentAttValues(), and GetBaseFullPVPath().
fClippingMode
ClippingMode G4PhysicalVolumeModel::fClippingMode protected
Definition at line 292 of file G4PhysicalVolumeModel.hh.
Referenced by SetClippingMode().
fCurrentDepth
G4int G4PhysicalVolumeModel::fCurrentDepth protected
Definition at line 280 of file G4PhysicalVolumeModel.hh.
Referenced by GetCurrentDepth().
fCurrentPVCopyNo
G4int G4PhysicalVolumeModel::fCurrentPVCopyNo protected
Definition at line 282 of file G4PhysicalVolumeModel.hh.
Referenced by GetCurrentPVCopyNo().
fCurtailDescent
G4bool G4PhysicalVolumeModel::fCurtailDescent mutable protected
Definition at line 290 of file G4PhysicalVolumeModel.hh.
Referenced by CurtailDescent().
fDrawnPVPath
std::vector<G4PhysicalVolumeNodeID> G4PhysicalVolumeModel::fDrawnPVPath protected
Definition at line 288 of file G4PhysicalVolumeModel.hh.
Referenced by GetDrawnPVPath().
fFullPVPath
std::vector<G4PhysicalVolumeNodeID> G4PhysicalVolumeModel::fFullPVPath protected
Definition at line 287 of file G4PhysicalVolumeModel.hh.
Referenced by CreateCurrentAttValues(), GetFullPVPath(), G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable::GetReplicaNumber(), G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable::GetRotation(), G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable::GetSolid(), and G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable::GetVolume().
fpClippingSolid
G4VSolid* G4PhysicalVolumeModel::fpClippingSolid protected
Definition at line 291 of file G4PhysicalVolumeModel.hh.
Referenced by GetClippingSolid(), SetClippingSolid(), and ~G4PhysicalVolumeModel().
fpCurrentLV
G4LogicalVolume* G4PhysicalVolumeModel::fpCurrentLV protected
Definition at line 283 of file G4PhysicalVolumeModel.hh.
Referenced by CreateCurrentAttValues(), and GetCurrentLV().
fpCurrentMaterial
G4Material* G4PhysicalVolumeModel::fpCurrentMaterial protected
Definition at line 284 of file G4PhysicalVolumeModel.hh.
Referenced by CreateCurrentAttValues(), and GetCurrentMaterial().
fpCurrentPV
G4VPhysicalVolume* G4PhysicalVolumeModel::fpCurrentPV protected
Definition at line 281 of file G4PhysicalVolumeModel.hh.
Referenced by CreateCurrentAttValues(), GetCurrentPV(), and GetCurrentTag().
fpCurrentTransform
G4Transform3D* G4PhysicalVolumeModel::fpCurrentTransform protected
Definition at line 285 of file G4PhysicalVolumeModel.hh.
Referenced by CreateCurrentAttValues(), and GetCurrentTransform().
fpTopPV
G4VPhysicalVolume* G4PhysicalVolumeModel::fpTopPV protected
Definition at line 274 of file G4PhysicalVolumeModel.hh.
Referenced by CalculateExtent(), GetTopPhysicalVolume(), and Validate().
fRequestedDepth
G4int G4PhysicalVolumeModel::fRequestedDepth protected
Definition at line 277 of file G4PhysicalVolumeModel.hh.
Referenced by CalculateExtent(), GetRequestedDepth(), and SetRequestedDepth().
fTopPVCopyNo
G4int G4PhysicalVolumeModel::fTopPVCopyNo protected
Definition at line 276 of file G4PhysicalVolumeModel.hh.
Referenced by Validate().
fTopPVName
G4String G4PhysicalVolumeModel::fTopPVName protected
Definition at line 275 of file G4PhysicalVolumeModel.hh.
Referenced by Validate().
fUseFullExtent
G4bool G4PhysicalVolumeModel::fUseFullExtent protected
Definition at line 279 of file G4PhysicalVolumeModel.hh.
Referenced by CalculateExtent().
The documentation for this class was generated from the following files:
source/visualization/modeling/include/G4PhysicalVolumeModel.hh
source/visualization/modeling/src/G4PhysicalVolumeModel.cc