Geant4: G4XmlNtupleManager Class Reference
G4XmlNtupleManager Class Reference
#include <G4XmlNtupleManager.hh>
Public Member Functions
G4XmlNtupleManager (const G4AnalysisManagerState &state)
~G4XmlNtupleManager ()
Public Member Functions inherited from G4TNtupleManager< tools::waxml::ntuple >
G4TNtupleManager (const G4AnalysisManagerState &state)
~G4TNtupleManager ()
Public Member Functions inherited from G4BaseNtupleManager
G4BaseNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4BaseNtupleManager ()
G4BaseNtupleManager (const G4BaseNtupleManager &rhs)=delete
G4BaseNtupleManager & operator= (const G4BaseNtupleManager &rhs)=delete
Public Member Functions inherited from G4VNtupleManager
G4VNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4VNtupleManager ()
G4VNtupleManager (const G4VNtupleManager &rhs)=delete
G4VNtupleManager & operator= (const G4VNtupleManager &rhs)=delete
Public Member Functions inherited from G4BaseAnalysisManager
G4BaseAnalysisManager (const G4AnalysisManagerState &state)
virtual ~G4BaseAnalysisManager ()
G4bool SetFirstId (G4int firstId)
void SetLockFirstId (G4bool lockFirstId)
G4int GetFirstId () const
Private Types
using NtupleType = tools::waxml::ntuple
using NtupleDescriptionType = G4TNtupleDescription< NtupleType >
Private Member Functions
void SetFileManager (std::shared_ptr< G4XmlFileManager > fileManager)
const std::vector< NtupleDescriptionType * > & GetNtupleDescriptionVector () const
virtual void CreateTNtuple (NtupleDescriptionType *ntupleDescription, const G4String &name, const G4String &title) final
virtual void CreateTNtupleFromBooking (NtupleDescriptionType *ntupleDescription) final
virtual void FinishTNtuple (NtupleDescriptionType *ntupleDescription, G4bool fromBooking) final
Private Attributes
std::shared_ptr< G4XmlFileManager > fFileManager
Friends
class G4XmlAnalysisManager
Additional Inherited Members
Protected Member Functions inherited from G4TNtupleManager< tools::waxml::ntuple >
virtual void CreateNtuplesFromBooking ()
G4bool IsEmpty () const
virtual G4bool Reset (G4bool deleteNtuple)
virtual G4int CreateNtuple (const G4String &name, const G4String &title) override
virtual G4int CreateNtupleIColumn (G4int ntupleId, const G4String &name, std::vector< int > *vector) final
virtual G4int CreateNtupleIColumn (const G4String &name, std::vector< int > *vector) final
virtual G4int CreateNtupleIColumn (G4int ntupleId, const G4String &name, std::vector< int > *vector)=0
virtual G4int CreateNtupleFColumn (G4int ntupleId, const G4String &name, std::vector< float > *vector) final
virtual G4int CreateNtupleFColumn (const G4String &name, std::vector< float > *vector) final
virtual G4int CreateNtupleFColumn (G4int ntupleId, const G4String &name, std::vector< float > *vector)=0
virtual G4int CreateNtupleDColumn (G4int ntupleId, const G4String &name, std::vector< double > *vector) final
virtual G4int CreateNtupleDColumn (const G4String &name, std::vector< double > *vector) final
virtual G4int CreateNtupleDColumn (G4int ntupleId, const G4String &name, std::vector< double > *vector)=0
virtual G4int CreateNtupleSColumn (G4int ntupleId, const G4String &name) final
virtual G4int CreateNtupleSColumn (const G4String &name)
virtual G4int CreateNtupleSColumn (G4int ntupleId, const G4String &name)=0
virtual void FinishNtuple (G4int ntupleId) final
virtual void FinishNtuple () final
virtual void FinishNtuple (G4int ntupleId)=0
virtual G4bool FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value) final
virtual G4bool FillNtupleIColumn (G4int id, G4int value) final
virtual G4bool FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value)=0
virtual G4bool FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value) final
virtual G4bool FillNtupleFColumn (G4int id, G4float value) final
virtual G4bool FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value)=0
virtual G4bool FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value) final
virtual G4bool FillNtupleDColumn (G4int id, G4double value) final
virtual G4bool FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value)=0
virtual G4bool FillNtupleSColumn (G4int ntupleId, G4int columnId, const G4String &value) final
virtual G4bool FillNtupleSColumn (G4int id, const G4String &value) final
virtual G4bool FillNtupleSColumn (G4int ntupleId, G4int columnId, const G4String &value)=0
virtual G4bool AddNtupleRow (G4int ntupleId) override
virtual G4bool AddNtupleRow () final
virtual G4bool AddNtupleRow (G4int ntupleId)=0
virtual void SetActivation (G4bool activation) final
virtual void SetActivation (G4int ntupleId, G4bool activation) final
virtual G4bool GetActivation (G4int ntupleId) const final
tools::waxml::ntuple * GetNtuple () const
tools::waxml::ntuple * GetNtuple (G4int ntupleId) const
virtual G4int GetNofNtuples () const final
virtual G4int GetNofNtupleBookings () const override
std::vector< tools::waxml::ntuple * >::iterator BeginNtuple ()
std::vector< tools::waxml::ntuple * >::iterator EndNtuple ()
std::vector< tools::waxml::ntuple * >::const_iterator BeginConstNtuple () const
std::vector< tools::waxml::ntuple * >::const_iterator EndConstNtuple () const
Protected Member Functions inherited from G4BaseNtupleManager
virtual G4int CreateNtupleIColumn (const G4String &name, std::vector< int > *vector) final
virtual G4int CreateNtupleFColumn (const G4String &name, std::vector< float > *vector) final
virtual G4int CreateNtupleDColumn (const G4String &name, std::vector< double > *vector) final
virtual G4int CreateNtupleSColumn (const G4String &name)
virtual void FinishNtuple () final
virtual G4bool SetFirstNtupleColumnId (G4int firstId) final
G4int GetFirstNtupleColumnId () const final
virtual G4bool FillNtupleIColumn (G4int id, G4int value) final
virtual G4bool FillNtupleFColumn (G4int id, G4float value) final
virtual G4bool FillNtupleDColumn (G4int id, G4double value) final
virtual G4bool FillNtupleSColumn (G4int id, const G4String &value) final
virtual G4bool AddNtupleRow () final
Protected Attributes inherited from G4TNtupleManager< tools::waxml::ntuple >
std::vector< G4TNtupleDescription< tools::waxml::ntuple > * > fNtupleDescriptionVector
std::vector< tools::waxml::ntuple * > fNtupleVector
Protected Attributes inherited from G4BaseNtupleManager
G4int fFirstNtupleColumnId
G4bool fLockFirstNtupleColumnId
Protected Attributes inherited from G4BaseAnalysisManager
const G4AnalysisManagerState & fState
G4int fFirstId
G4bool fLockFirstId
Detailed Description
Definition at line 44 of file G4XmlNtupleManager.hh.
Member Typedef Documentation
NtupleDescriptionType
using G4XmlNtupleManager::NtupleDescriptionType = G4TNtupleDescription<NtupleType> private
Definition at line 55 of file G4XmlNtupleManager.hh.
NtupleType
using G4XmlNtupleManager::NtupleType = tools::waxml::ntuple private
Definition at line 54 of file G4XmlNtupleManager.hh.
Constructor & Destructor Documentation
G4XmlNtupleManager()
G4XmlNtupleManager::G4XmlNtupleManager (const G4AnalysisManagerState & state) explicit
Definition at line 44 of file G4XmlNtupleManager.cc.
~G4XmlNtupleManager()
G4XmlNtupleManager::~G4XmlNtupleManager ()
Definition at line 50 of file G4XmlNtupleManager.cc.
Member Function Documentation
CreateTNtuple()
void G4XmlNtupleManager::CreateTNtuple (NtupleDescriptionType * ntupleDescription, const G4String & name, const G4String & title) final private virtual
Definition at line 58 of file G4XmlNtupleManager.cc.
CreateTNtupleFromBooking()
void G4XmlNtupleManager::CreateTNtupleFromBooking (NtupleDescriptionType * ntupleDescription) final private virtual
Definition at line 75 of file G4XmlNtupleManager.cc.
Referenced by FinishTNtuple().
FinishTNtuple()
void G4XmlNtupleManager::FinishTNtuple (NtupleDescriptionType * ntupleDescription, G4bool fromBooking) final private virtual
Definition at line 89 of file G4XmlNtupleManager.cc.
GetNtupleDescriptionVector()
const std::vector< G4TNtupleDescription< tools::waxml::ntuple > * > & G4XmlNtupleManager::GetNtupleDescriptionVector () const inline private
Definition at line 90 of file G4XmlNtupleManager.hh.
Referenced by G4XmlAnalysisManager::CloseNtupleFiles(), and G4XmlAnalysisManager::WriteNtuple().
SetFileManager()
void G4XmlNtupleManager::SetFileManager (std::shared_ptr< G4XmlFileManager > fileManager) inline private
Definition at line 86 of file G4XmlNtupleManager.hh.
Referenced by G4XmlAnalysisManager::G4XmlAnalysisManager().
Friends And Related Function Documentation
G4XmlAnalysisManager
friend class G4XmlAnalysisManager friend
Definition at line 46 of file G4XmlNtupleManager.hh.
Field Documentation
fFileManager
std::shared_ptr<G4XmlFileManager> G4XmlNtupleManager::fFileManager private
Definition at line 80 of file G4XmlNtupleManager.hh.
Referenced by CreateTNtuple(), CreateTNtupleFromBooking(), FinishTNtuple(), and SetFileManager().
The documentation for this class was generated from the following files:
source/analysis/xml/include/G4XmlNtupleManager.hh
source/analysis/xml/src/G4XmlNtupleManager.cc