Geant4: G4AssemblyVolume Class Reference
G4AssemblyVolume Class Reference
#include <G4AssemblyVolume.hh>
Public Member Functions
G4AssemblyVolume ()
G4AssemblyVolume (G4LogicalVolume *volume, G4ThreeVector &translation, G4RotationMatrix *rotation)
~G4AssemblyVolume ()
void AddPlacedVolume (G4LogicalVolume *pPlacedVolume, G4ThreeVector &translation, G4RotationMatrix *rotation)
void AddPlacedVolume (G4LogicalVolume *pPlacedVolume, G4Transform3D &transformation)
void AddPlacedAssembly (G4AssemblyVolume *pAssembly, G4Transform3D &transformation)
void AddPlacedAssembly (G4AssemblyVolume *pAssembly, G4ThreeVector &translation, G4RotationMatrix *rotation)
void MakeImprint (G4LogicalVolume *pMotherLV, G4ThreeVector &translationInMother, G4RotationMatrix *pRotationInMother, G4int copyNumBase=0, G4bool surfCheck=false)
void MakeImprint (G4LogicalVolume *pMotherLV, G4Transform3D &transformation, G4int copyNumBase=0, G4bool surfCheck=false)
std::vector< G4VPhysicalVolume * >::iterator GetVolumesIterator ()
unsigned int TotalImprintedVolumes () const
unsigned int GetImprintsCount () const
unsigned int GetInstanceCount () const
unsigned int GetAssemblyID () const
Protected Member Functions
void SetInstanceCount (unsigned int value)
void SetAssemblyID (unsigned int value)
void InstanceCountPlus ()
void InstanceCountMinus ()
void SetImprintsCount (unsigned int value)
void ImprintsCountPlus ()
void ImprintsCountMinus ()
Private Member Functions
void MakeImprint (G4AssemblyVolume *pAssembly, G4LogicalVolume *pMotherLV, G4Transform3D &transformation, G4int copyNumBase=0, G4bool surfCheck=false)
Private Attributes
std::vector< G4AssemblyTriplet > fTriplets
std::vector< G4VPhysicalVolume * > fPVStore
unsigned int fImprintsCounter
unsigned int fAssemblyID
Static Private Attributes
static G4ThreadLocal unsigned int fsInstanceCounter = 0
Detailed Description
Definition at line 59 of file G4AssemblyVolume.hh.
Constructor & Destructor Documentation
G4AssemblyVolume() [1/2]
G4AssemblyVolume::G4AssemblyVolume ()
Definition at line 48 of file G4AssemblyVolume.cc.
G4AssemblyVolume() [2/2]
G4AssemblyVolume::G4AssemblyVolume (G4LogicalVolume * volume, G4ThreeVector & translation, G4RotationMatrix * rotation)
Definition at line 72 of file G4AssemblyVolume.cc.
~G4AssemblyVolume()
G4AssemblyVolume::~G4AssemblyVolume ()
Definition at line 99 of file G4AssemblyVolume.cc.
Member Function Documentation
AddPlacedAssembly() [1/2]
void G4AssemblyVolume::AddPlacedAssembly (G4AssemblyVolume * pAssembly, G4ThreeVector & translation, G4RotationMatrix * rotation)
Definition at line 170 of file G4AssemblyVolume.cc.
AddPlacedAssembly() [2/2]
void G4AssemblyVolume::AddPlacedAssembly (G4AssemblyVolume * pAssembly, G4Transform3D & transformation)
Definition at line 185 of file G4AssemblyVolume.cc.
Referenced by G4GDMLReadStructure::PhysvolRead().
AddPlacedVolume() [1/2]
void G4AssemblyVolume::AddPlacedVolume (G4LogicalVolume * pPlacedVolume, G4ThreeVector & translation, G4RotationMatrix * rotation)
Definition at line 133 of file G4AssemblyVolume.cc.
Referenced by G02DetectorConstruction::ConstructAssembly(), G4tgbVolume::ConstructG4PhysVol(), G4AssemblyVolume(), TrentoPassiveProtonBeamLine::HadrontherapyBeamMonitoring(), and G4GDMLReadStructure::PhysvolRead().
AddPlacedVolume() [2/2]
void G4AssemblyVolume::AddPlacedVolume (G4LogicalVolume * pPlacedVolume, G4Transform3D & transformation)
Definition at line 147 of file G4AssemblyVolume.cc.
GetAssemblyID()
unsigned int G4AssemblyVolume::GetAssemblyID () const
Referenced by MakeImprint().
GetImprintsCount()
unsigned int G4AssemblyVolume::GetImprintsCount () const
Referenced by MakeImprint().
GetInstanceCount()
unsigned int G4AssemblyVolume::GetInstanceCount () const
Definition at line 375 of file G4AssemblyVolume.cc.
Referenced by G4AssemblyVolume().
GetVolumesIterator()
std::vector<G4VPhysicalVolume*>::iterator G4AssemblyVolume::GetVolumesIterator () inline
ImprintsCountMinus()
void G4AssemblyVolume::ImprintsCountMinus () protected
ImprintsCountPlus()
void G4AssemblyVolume::ImprintsCountPlus () protected
Referenced by MakeImprint().
InstanceCountMinus()
void G4AssemblyVolume::InstanceCountMinus () protected
Definition at line 390 of file G4AssemblyVolume.cc.
Referenced by ~G4AssemblyVolume().
InstanceCountPlus()
void G4AssemblyVolume::InstanceCountPlus () protected
Definition at line 385 of file G4AssemblyVolume.cc.
Referenced by G4AssemblyVolume().
MakeImprint() [1/3]
void G4AssemblyVolume::MakeImprint (G4AssemblyVolume * pAssembly, G4LogicalVolume * pMotherLV, G4Transform3D & transformation, G4int copyNumBase = 0, G4bool surfCheck = false) private
Definition at line 244 of file G4AssemblyVolume.cc.
MakeImprint() [2/3]
void G4AssemblyVolume::MakeImprint (G4LogicalVolume * pMotherLV, G4ThreeVector & translationInMother, G4RotationMatrix * pRotationInMother, G4int copyNumBase = 0, G4bool surfCheck = false)
Definition at line 334 of file G4AssemblyVolume.cc.
Referenced by G02DetectorConstruction::ConstructAssembly(), G4tgbVolume::ConstructG4PhysVol(), MakeImprint(), and G4GDMLReadStructure::PhysvolRead().
MakeImprint() [3/3]
void G4AssemblyVolume::MakeImprint (G4LogicalVolume * pMotherLV, G4Transform3D & transformation, G4int copyNumBase = 0, G4bool surfCheck = false)
Definition at line 361 of file G4AssemblyVolume.cc.
SetAssemblyID()
void G4AssemblyVolume::SetAssemblyID (unsigned int value) protected
Referenced by G4AssemblyVolume().
SetImprintsCount()
void G4AssemblyVolume::SetImprintsCount (unsigned int value) protected
Referenced by G4AssemblyVolume().
SetInstanceCount()
void G4AssemblyVolume::SetInstanceCount (unsigned int value) protected
Definition at line 380 of file G4AssemblyVolume.cc.
TotalImprintedVolumes()
unsigned int G4AssemblyVolume::TotalImprintedVolumes () const inline
Field Documentation
fAssemblyID
unsigned int G4AssemblyVolume::fAssemblyID private
Definition at line 216 of file G4AssemblyVolume.hh.
Referenced by G4AssemblyVolume().
fImprintsCounter
unsigned int G4AssemblyVolume::fImprintsCounter private
Definition at line 208 of file G4AssemblyVolume.hh.
fPVStore
std::vector<G4VPhysicalVolume*> G4AssemblyVolume::fPVStore private
Definition at line 197 of file G4AssemblyVolume.hh.
Referenced by MakeImprint(), and ~G4AssemblyVolume().
fsInstanceCounter
G4ThreadLocal unsigned int G4AssemblyVolume::fsInstanceCounter = 0 static private
Definition at line 212 of file G4AssemblyVolume.hh.
Referenced by GetInstanceCount(), InstanceCountMinus(), InstanceCountPlus(), and SetInstanceCount().
fTriplets
std::vector<G4AssemblyTriplet> G4AssemblyVolume::fTriplets private
Definition at line 192 of file G4AssemblyVolume.hh.
Referenced by AddPlacedAssembly(), AddPlacedVolume(), MakeImprint(), and ~G4AssemblyVolume().
The documentation for this class was generated from the following files:
source/geometry/volumes/include/G4AssemblyVolume.hh
source/geometry/volumes/src/G4AssemblyVolume.cc