Geant4: examples/extended/medical/dna/pdb4dna/pdb4dna.cc File Reference
pdb4dna.cc File Reference
Main program of the pdb4dna example.
#include "DetectorConstruction.hh"
#include "PhysicsList.hh"
#include "ActionInitialization.hh"
#include "G4RunManager.hh"
#include "G4UImanager.hh"
#include "Randomize.hh"
#include "G4VisExecutive.hh"
#include "G4UIExecutive.hh"
#include "CommandLineParser.hh"
Functions
CommandLineParser * parser (0)
void Parse (int &argc, char **argv)
int main (int argc, char **argv)
Detailed Description
Main program of the pdb4dna example.
Definition in file pdb4dna.cc.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 67 of file pdb4dna.cc.
Parse()
void Parse (int & argc, char ** argv)
Definition at line 189 of file pdb4dna.cc.
Referenced by main().
parser()
CommandLineParser* parser (0)
Referenced by main(), and Parse().