Geant4: G4VEmAdjointModel Class Reference
G4VEmAdjointModel Class Reference abstract
#include <G4VEmAdjointModel.hh>
Public Member Functions
G4VEmAdjointModel (const G4String &nam)
virtual ~G4VEmAdjointModel ()
virtual void SampleSecondaries (const G4Track &aTrack, G4bool IsScatProjToProjCase, G4ParticleChange *fParticleChange)=0
virtual G4double AdjointCrossSection (const G4MaterialCutsCouple *aCouple, G4double primEnergy, G4bool IsScatProjToProjCase)
virtual G4double GetAdjointCrossSection (const G4MaterialCutsCouple *aCouple, G4double primEnergy, G4bool IsScatProjToProjCase)
virtual G4double DiffCrossSectionPerAtomPrimToSecond (G4double kinEnergyProj, G4double kinEnergyProd, G4double Z, G4double A=0.)
virtual G4double DiffCrossSectionPerAtomPrimToScatPrim (G4double kinEnergyProj, G4double kinEnergyScatProj, G4double Z, G4double A=0.)
virtual G4double DiffCrossSectionPerVolumePrimToSecond (const G4Material *aMaterial, G4double kinEnergyProj, G4double kinEnergyProd)
virtual G4double DiffCrossSectionPerVolumePrimToScatPrim (const G4Material *aMaterial, G4double kinEnergyProj, G4double kinEnergyScatProj)
virtual G4double GetSecondAdjEnergyMaxForScatProjToProjCase (G4double PrimAdjEnergy)
virtual G4double GetSecondAdjEnergyMinForScatProjToProjCase (G4double PrimAdjEnergy, G4double Tcut=0)
virtual G4double GetSecondAdjEnergyMaxForProdToProjCase (G4double PrimAdjEnergy)
virtual G4double GetSecondAdjEnergyMinForProdToProjCase (G4double PrimAdjEnergy)
void DefineCurrentMaterial (const G4MaterialCutsCouple *couple)
std::vector< std::vector< double > * > ComputeAdjointCrossSectionVectorPerAtomForSecond (G4double kinEnergyProd, G4double Z, G4double A=0., G4int nbin_pro_decade=10)
std::vector< std::vector< double > * > ComputeAdjointCrossSectionVectorPerAtomForScatProj (G4double kinEnergyProd, G4double Z, G4double A=0., G4int nbin_pro_decade=10)
std::vector< std::vector< double > * > ComputeAdjointCrossSectionVectorPerVolumeForSecond (G4Material *aMaterial, G4double kinEnergyProd, G4int nbin_pro_decade=10)
std::vector< std::vector< double > * > ComputeAdjointCrossSectionVectorPerVolumeForScatProj (G4Material *aMaterial, G4double kinEnergyProd, G4int nbin_pro_decade=10)
void SetCSMatrices (std::vector< G4AdjointCSMatrix * > *Vec1CSMatrix, std::vector< G4AdjointCSMatrix * > *Vec2CSMatrix)
G4ParticleDefinition * GetAdjointEquivalentOfDirectPrimaryParticleDefinition ()
G4ParticleDefinition * GetAdjointEquivalentOfDirectSecondaryParticleDefinition ()
G4double GetHighEnergyLimit ()
G4double GetLowEnergyLimit ()
void SetHighEnergyLimit (G4double aVal)
void SetLowEnergyLimit (G4double aVal)
void DefineDirectEMModel (G4VEmModel *aModel)
void SetAdjointEquivalentOfDirectPrimaryParticleDefinition (G4ParticleDefinition *aPart)
void SetAdjointEquivalentOfDirectSecondaryParticleDefinition (G4ParticleDefinition *aPart)
void SetSecondPartOfSameType (G4bool aBool)
G4bool GetSecondPartOfSameType ()
void SetUseMatrix (G4bool aBool)
void SetUseMatrixPerElement (G4bool aBool)
void SetUseOnlyOneMatrixForAllElements (G4bool aBool)
void SetApplyCutInRange (G4bool aBool)
G4bool GetUseMatrix ()
G4bool GetUseMatrixPerElement ()
G4bool GetUseOnlyOneMatrixForAllElements ()
G4bool GetApplyCutInRange ()
G4String GetName ()
virtual void SetCSBiasingFactor (G4double aVal)
void SetCorrectWeightForPostStepInModel (G4bool aBool)
void SetAdditionalWeightCorrectionFactorForPostStepOutsideModel (G4double factor)
Protected Member Functions
G4double DiffCrossSectionFunction1 (G4double kinEnergyProj)
G4double DiffCrossSectionFunction2 (G4double kinEnergyProj)
G4double DiffCrossSectionPerVolumeFunctionForIntegrationOverEkinProj (G4double EkinProd)
G4double SampleAdjSecEnergyFromCSMatrix (size_t MatrixIndex, G4double prim_energy, G4bool IsScatProjToProjCase)
G4double SampleAdjSecEnergyFromCSMatrix (G4double prim_energy, G4bool IsScatProjToProjCase)
void SelectCSMatrix (G4bool IsScatProjToProjCase)
virtual G4double SampleAdjSecEnergyFromDiffCrossSectionPerAtom (G4double prim_energy, G4bool IsScatProjToProjCase)
virtual void CorrectPostStepWeight (G4ParticleChange *fParticleChange, G4double old_weight, G4double adjointPrimKinEnergy, G4double projectileKinEnergy, G4bool IsScatProjToProjCase)
Protected Attributes
G4VEmModel * theDirectEMModel
G4VParticleChange * pParticleChange
const G4String name
G4int ASelectedNucleus
G4int ZSelectedNucleus
G4Material * SelectedMaterial
G4double kinEnergyProdForIntegration
G4double kinEnergyScatProjForIntegration
G4double kinEnergyProjForIntegration
std::vector< G4AdjointCSMatrix * > * pOnCSMatrixForProdToProjBackwardScattering
std::vector< G4AdjointCSMatrix * > * pOnCSMatrixForScatProjToProjBackwardScattering
std::vector< G4double > CS_Vs_ElementForScatProjToProjCase
std::vector< G4double > CS_Vs_ElementForProdToProjCase
G4double lastCS
G4double lastAdjointCSForScatProjToProjCase
G4double lastAdjointCSForProdToProjCase
G4ParticleDefinition * theAdjEquivOfDirectPrimPartDef
G4ParticleDefinition * theAdjEquivOfDirectSecondPartDef
G4ParticleDefinition * theDirectPrimaryPartDef
G4bool second_part_of_same_type
G4double preStepEnergy
G4Material * currentMaterial
G4MaterialCutsCouple * currentCouple
size_t currentMaterialIndex
size_t currentCoupleIndex
G4double currentTcutForDirectPrim
G4double currentTcutForDirectSecond
G4bool ApplyCutInRange
G4double mass_ratio_product
G4double mass_ratio_projectile
G4double HighEnergyLimit
G4double LowEnergyLimit
G4double CS_biasing_factor
G4bool UseMatrix
G4bool UseMatrixPerElement
G4bool UseOnlyOneMatrixForAllElements
size_t indexOfUsedCrossSectionMatrix
size_t model_index
G4bool correct_weight_for_post_step_in_model
G4double additional_weight_correction_factor_for_post_step_outside_model
Detailed Description
Definition at line 71 of file G4VEmAdjointModel.hh.
Constructor & Destructor Documentation
G4VEmAdjointModel()
G4VEmAdjointModel::G4VEmAdjointModel (const G4String & nam)
Definition at line 40 of file G4VEmAdjointModel.cc.
Referenced by ComputeAdjointCrossSectionVectorPerAtomForScatProj(), ComputeAdjointCrossSectionVectorPerAtomForSecond(), ComputeAdjointCrossSectionVectorPerVolumeForScatProj(), and ComputeAdjointCrossSectionVectorPerVolumeForSecond().
~G4VEmAdjointModel()
G4VEmAdjointModel::~G4VEmAdjointModel () virtual
Definition at line 54 of file G4VEmAdjointModel.cc.
Member Function Documentation
AdjointCrossSection()
G4double G4VEmAdjointModel::AdjointCrossSection (const G4MaterialCutsCouple * aCouple, G4double primEnergy, G4bool IsScatProjToProjCase) virtual
Reimplemented in G4AdjointhIonisationModel, G4AdjointBremsstrahlungModel, G4AdjointComptonModel, and G4AdjointPhotoElectricModel.
Definition at line 58 of file G4VEmAdjointModel.cc.
Referenced by G4AdjointComptonModel::AdjointCrossSection(), G4AdjointBremsstrahlungModel::AdjointCrossSection(), G4AdjointhIonisationModel::AdjointCrossSection(), G4AdjointCSManager::ComputeAdjointCS(), CorrectPostStepWeight(), GetAdjointCrossSection(), and G4AdjointForcedInteractionForGamma::PostStepDoIt().
ComputeAdjointCrossSectionVectorPerAtomForScatProj()
std::vector< std::vector< G4double > * > G4VEmAdjointModel::ComputeAdjointCrossSectionVectorPerAtomForScatProj (G4double kinEnergyProd, G4double Z, G4double A = 0., G4int nbin_pro_decade = 10)
Definition at line 292 of file G4VEmAdjointModel.cc.
Referenced by G4AdjointCSManager::BuildCrossSectionsMatricesForAGivenModelAndElement().
ComputeAdjointCrossSectionVectorPerAtomForSecond()
std::vector< std::vector< G4double > * > G4VEmAdjointModel::ComputeAdjointCrossSectionVectorPerAtomForSecond (G4double kinEnergyProd, G4double Z, G4double A = 0., G4int nbin_pro_decade = 10)
Definition at line 238 of file G4VEmAdjointModel.cc.
Referenced by G4AdjointCSManager::BuildCrossSectionsMatricesForAGivenModelAndElement().
ComputeAdjointCrossSectionVectorPerVolumeForScatProj()
std::vector< std::vector< G4double > * > G4VEmAdjointModel::ComputeAdjointCrossSectionVectorPerVolumeForScatProj (G4Material * aMaterial, G4double kinEnergyProd, G4int nbin_pro_decade = 10)
Definition at line 402 of file G4VEmAdjointModel.cc.
Referenced by G4AdjointCSManager::BuildCrossSectionsMatricesForAGivenModelAndMaterial().
ComputeAdjointCrossSectionVectorPerVolumeForSecond()
std::vector< std::vector< G4double > * > G4VEmAdjointModel::ComputeAdjointCrossSectionVectorPerVolumeForSecond (G4Material * aMaterial, G4double kinEnergyProd, G4int nbin_pro_decade = 10)
Definition at line 350 of file G4VEmAdjointModel.cc.
Referenced by G4AdjointCSManager::BuildCrossSectionsMatricesForAGivenModelAndMaterial().
CorrectPostStepWeight()
void G4VEmAdjointModel::CorrectPostStepWeight (G4ParticleChange * fParticleChange, G4double old_weight, G4double adjointPrimKinEnergy, G4double projectileKinEnergy, G4bool IsScatProjToProjCase) protected virtual
Reimplemented in G4AdjointIonIonisationModel, and G4AdjointPhotoElectricModel.
Definition at line 633 of file G4VEmAdjointModel.cc.
Referenced by G4AdjointComptonModel::SampleSecondaries(), G4AdjointeIonisationModel::SampleSecondaries(), G4AdjointBremsstrahlungModel::SampleSecondaries(), and G4AdjointhIonisationModel::SampleSecondaries().
DefineCurrentMaterial()
void G4VEmAdjointModel::DefineCurrentMaterial (const G4MaterialCutsCouple * couple)
Definition at line 692 of file G4VEmAdjointModel.cc.
Referenced by G4AdjointComptonModel::AdjointCrossSection(), G4AdjointBremsstrahlungModel::AdjointCrossSection(), G4AdjointhIonisationModel::AdjointCrossSection(), AdjointCrossSection(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), and G4AdjointBremsstrahlungModel::SampleSecondaries().
DefineDirectEMModel()
void G4VEmAdjointModel::DefineDirectEMModel (G4VEmModel * aModel) inline
Definition at line 192 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointPhotoElectricModel::SetTheDirectPEEffectModel().
DiffCrossSectionFunction1()
G4double G4VEmAdjointModel::DiffCrossSectionFunction1 (G4double kinEnergyProj) protected
Definition at line 201 of file G4VEmAdjointModel.cc.
Referenced by ComputeAdjointCrossSectionVectorPerAtomForSecond(), and ComputeAdjointCrossSectionVectorPerVolumeForSecond().
DiffCrossSectionFunction2()
G4double G4VEmAdjointModel::DiffCrossSectionFunction2 (G4double kinEnergyProj) protected
Definition at line 217 of file G4VEmAdjointModel.cc.
Referenced by ComputeAdjointCrossSectionVectorPerAtomForScatProj(), and ComputeAdjointCrossSectionVectorPerVolumeForScatProj().
DiffCrossSectionPerAtomPrimToScatPrim()
G4double G4VEmAdjointModel::DiffCrossSectionPerAtomPrimToScatPrim (G4double kinEnergyProj, G4double kinEnergyScatProj, G4double Z, G4double A = 0.) virtual
Reimplemented in G4AdjointComptonModel.
Definition at line 144 of file G4VEmAdjointModel.cc.
Referenced by DiffCrossSectionFunction2(), and SampleAdjSecEnergyFromDiffCrossSectionPerAtom().
DiffCrossSectionPerAtomPrimToSecond()
G4double G4VEmAdjointModel::DiffCrossSectionPerAtomPrimToSecond (G4double kinEnergyProj, G4double kinEnergyProd, G4double Z, G4double A = 0.) virtual
Reimplemented in G4AdjointhIonisationModel, G4AdjointIonIonisationModel, G4AdjointComptonModel, and G4AdjointeIonisationModel.
Definition at line 112 of file G4VEmAdjointModel.cc.
Referenced by DiffCrossSectionFunction1(), DiffCrossSectionPerAtomPrimToScatPrim(), and SampleAdjSecEnergyFromDiffCrossSectionPerAtom().
DiffCrossSectionPerVolumeFunctionForIntegrationOverEkinProj()
G4double G4VEmAdjointModel::DiffCrossSectionPerVolumeFunctionForIntegrationOverEkinProj (G4double EkinProd) protected
Definition at line 232 of file G4VEmAdjointModel.cc.
DiffCrossSectionPerVolumePrimToScatPrim()
G4double G4VEmAdjointModel::DiffCrossSectionPerVolumePrimToScatPrim (const G4Material * aMaterial, G4double kinEnergyProj, G4double kinEnergyScatProj) virtual
Definition at line 188 of file G4VEmAdjointModel.cc.
Referenced by DiffCrossSectionFunction2(), and G4AdjointeIonisationModel::SampleSecondaries().
DiffCrossSectionPerVolumePrimToSecond()
G4double G4VEmAdjointModel::DiffCrossSectionPerVolumePrimToSecond (const G4Material * aMaterial, G4double kinEnergyProj, G4double kinEnergyProd) virtual
Reimplemented in G4AdjointBremsstrahlungModel.
Definition at line 160 of file G4VEmAdjointModel.cc.
Referenced by DiffCrossSectionFunction1(), DiffCrossSectionPerVolumeFunctionForIntegrationOverEkinProj(), DiffCrossSectionPerVolumePrimToScatPrim(), G4AdjointBremsstrahlungModel::DiffCrossSectionPerVolumePrimToSecond(), and G4AdjointeIonisationModel::SampleSecondaries().
GetAdjointCrossSection()
G4double G4VEmAdjointModel::GetAdjointCrossSection (const G4MaterialCutsCouple * aCouple, G4double primEnergy, G4bool IsScatProjToProjCase) virtual
Reimplemented in G4AdjointBremsstrahlungModel, G4AdjointComptonModel, and G4AdjointPhotoElectricModel.
Definition at line 83 of file G4VEmAdjointModel.cc.
Referenced by G4AdjointBremsstrahlungModel::GetAdjointCrossSection(), and G4VAdjointReverseReaction::GetMeanFreePath().
GetAdjointEquivalentOfDirectPrimaryParticleDefinition()
G4ParticleDefinition* G4VEmAdjointModel::GetAdjointEquivalentOfDirectPrimaryParticleDefinition () inline
Definition at line 180 of file G4VEmAdjointModel.hh.
GetAdjointEquivalentOfDirectSecondaryParticleDefinition()
G4ParticleDefinition* G4VEmAdjointModel::GetAdjointEquivalentOfDirectSecondaryParticleDefinition () inline
Definition at line 182 of file G4VEmAdjointModel.hh.
GetApplyCutInRange()
G4bool G4VEmAdjointModel::GetApplyCutInRange () inline
Definition at line 213 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointCSManager::ComputeAdjointCS().
GetHighEnergyLimit()
G4double G4VEmAdjointModel::GetHighEnergyLimit () inline
Definition at line 184 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointCSManager::BuildCrossSectionsMatricesForAGivenModelAndElement(), and G4AdjointCSManager::BuildCrossSectionsMatricesForAGivenModelAndMaterial().
GetLowEnergyLimit()
G4double G4VEmAdjointModel::GetLowEnergyLimit () inline
Definition at line 186 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointCSManager::BuildCrossSectionsMatricesForAGivenModelAndElement(), G4AdjointCSManager::BuildCrossSectionsMatricesForAGivenModelAndMaterial(), ComputeAdjointCrossSectionVectorPerAtomForScatProj(), and ComputeAdjointCrossSectionVectorPerVolumeForScatProj().
GetName()
G4String G4VEmAdjointModel::GetName (void) inline
Definition at line 215 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointCSManager::BuildCrossSectionMatrices().
GetSecondAdjEnergyMaxForProdToProjCase()
G4double G4VEmAdjointModel::GetSecondAdjEnergyMaxForProdToProjCase (G4double PrimAdjEnergy) virtual
Reimplemented in G4AdjointIonIonisationModel, and G4AdjointhIonisationModel.
Definition at line 680 of file G4VEmAdjointModel.cc.
Referenced by G4AdjointComptonModel::AdjointCrossSection(), G4AdjointBremsstrahlungModel::AdjointCrossSection(), ComputeAdjointCrossSectionVectorPerAtomForSecond(), ComputeAdjointCrossSectionVectorPerVolumeForSecond(), G4AdjointCSManager::ComputeAdjointCS(), G4AdjointeIonisationModel::DiffCrossSectionPerAtomPrimToSecond(), DiffCrossSectionPerAtomPrimToSecond(), DiffCrossSectionPerVolumePrimToSecond(), G4AdjointBremsstrahlungModel::DiffCrossSectionPerVolumePrimToSecondApproximated1(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), SampleAdjSecEnergyFromCSMatrix(), SampleAdjSecEnergyFromDiffCrossSectionPerAtom(), and G4AdjointeIonisationModel::SampleSecondaries().
GetSecondAdjEnergyMaxForScatProjToProjCase()
G4double G4VEmAdjointModel::GetSecondAdjEnergyMaxForScatProjToProjCase (G4double PrimAdjEnergy) virtual
Reimplemented in G4AdjointIonIonisationModel, G4AdjointhIonisationModel, and G4AdjointComptonModel.
Definition at line 666 of file G4VEmAdjointModel.cc.
Referenced by G4AdjointBremsstrahlungModel::AdjointCrossSection(), ComputeAdjointCrossSectionVectorPerAtomForScatProj(), ComputeAdjointCrossSectionVectorPerVolumeForScatProj(), G4AdjointCSManager::ComputeAdjointCS(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), SampleAdjSecEnergyFromCSMatrix(), SampleAdjSecEnergyFromDiffCrossSectionPerAtom(), and G4AdjointeIonisationModel::SampleSecondaries().
GetSecondAdjEnergyMinForProdToProjCase()
G4double G4VEmAdjointModel::GetSecondAdjEnergyMinForProdToProjCase (G4double PrimAdjEnergy) virtual
Reimplemented in G4AdjointIonIonisationModel, G4AdjointhIonisationModel, and G4AdjointComptonModel.
Definition at line 685 of file G4VEmAdjointModel.cc.
Referenced by G4AdjointBremsstrahlungModel::AdjointCrossSection(), ComputeAdjointCrossSectionVectorPerAtomForSecond(), ComputeAdjointCrossSectionVectorPerVolumeForSecond(), G4AdjointCSManager::ComputeAdjointCS(), G4AdjointeIonisationModel::DiffCrossSectionPerAtomPrimToSecond(), DiffCrossSectionPerAtomPrimToSecond(), DiffCrossSectionPerVolumePrimToSecond(), G4AdjointBremsstrahlungModel::DiffCrossSectionPerVolumePrimToSecondApproximated1(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), SampleAdjSecEnergyFromCSMatrix(), SampleAdjSecEnergyFromDiffCrossSectionPerAtom(), and G4AdjointeIonisationModel::SampleSecondaries().
GetSecondAdjEnergyMinForScatProjToProjCase()
G4double G4VEmAdjointModel::GetSecondAdjEnergyMinForScatProjToProjCase (G4double PrimAdjEnergy, G4double Tcut = 0) virtual
Reimplemented in G4AdjointIonIonisationModel, and G4AdjointhIonisationModel.
Definition at line 673 of file G4VEmAdjointModel.cc.
Referenced by G4AdjointComptonModel::AdjointCrossSection(), G4AdjointBremsstrahlungModel::AdjointCrossSection(), ComputeAdjointCrossSectionVectorPerAtomForScatProj(), ComputeAdjointCrossSectionVectorPerVolumeForScatProj(), G4AdjointCSManager::ComputeAdjointCS(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), SampleAdjSecEnergyFromCSMatrix(), and G4AdjointeIonisationModel::SampleSecondaries().
GetSecondPartOfSameType()
G4bool G4VEmAdjointModel::GetSecondPartOfSameType () inline
Definition at line 202 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointCSManager::BuildCrossSectionsMatricesForAGivenModelAndElement(), and G4AdjointCSManager::BuildCrossSectionsMatricesForAGivenModelAndMaterial().
GetUseMatrix()
G4bool G4VEmAdjointModel::GetUseMatrix () inline
Definition at line 210 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointCSManager::BuildCrossSectionMatrices(), and G4AdjointCSManager::ComputeAdjointCS().
GetUseMatrixPerElement()
G4bool G4VEmAdjointModel::GetUseMatrixPerElement () inline
Definition at line 211 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointCSManager::BuildCrossSectionMatrices(), and G4AdjointCSManager::ComputeAdjointCS().
GetUseOnlyOneMatrixForAllElements()
G4bool G4VEmAdjointModel::GetUseOnlyOneMatrixForAllElements () inline
Definition at line 212 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointCSManager::BuildCrossSectionMatrices(), and G4AdjointCSManager::ComputeAdjointCS().
SampleAdjSecEnergyFromCSMatrix() [1/2]
G4double G4VEmAdjointModel::SampleAdjSecEnergyFromCSMatrix (G4double prim_energy, G4bool IsScatProjToProjCase) protected
Definition at line 548 of file G4VEmAdjointModel.cc.
SampleAdjSecEnergyFromCSMatrix() [2/2]
G4double G4VEmAdjointModel::SampleAdjSecEnergyFromCSMatrix (size_t MatrixIndex, G4double prim_energy, G4bool IsScatProjToProjCase) protected
Definition at line 458 of file G4VEmAdjointModel.cc.
Referenced by SampleAdjSecEnergyFromCSMatrix(), G4AdjointComptonModel::SampleSecondaries(), G4AdjointeIonisationModel::SampleSecondaries(), G4AdjointBremsstrahlungModel::SampleSecondaries(), G4AdjointIonIonisationModel::SampleSecondaries(), and G4AdjointhIonisationModel::SampleSecondaries().
SampleAdjSecEnergyFromDiffCrossSectionPerAtom()
G4double G4VEmAdjointModel::SampleAdjSecEnergyFromDiffCrossSectionPerAtom (G4double prim_energy, G4bool IsScatProjToProjCase) protected virtual
Definition at line 580 of file G4VEmAdjointModel.cc.
SampleSecondaries()
virtual void G4VEmAdjointModel::SampleSecondaries (const G4Track & aTrack, G4bool IsScatProjToProjCase, G4ParticleChange * fParticleChange) pure virtual
Implemented in G4AdjointhIonisationModel, G4AdjointIonIonisationModel, G4AdjointPhotoElectricModel, G4AdjointBremsstrahlungModel, G4AdjointeIonisationModel, and G4AdjointComptonModel.
Referenced by G4VAdjointReverseReaction::PostStepDoIt(), and G4AdjointForcedInteractionForGamma::PostStepDoIt().
SelectCSMatrix()
void G4VEmAdjointModel::SelectCSMatrix (G4bool IsScatProjToProjCase) protected
Definition at line 554 of file G4VEmAdjointModel.cc.
Referenced by SampleAdjSecEnergyFromCSMatrix().
SetAdditionalWeightCorrectionFactorForPostStepOutsideModel()
void G4VEmAdjointModel::SetAdditionalWeightCorrectionFactorForPostStepOutsideModel (G4double factor) inline
Definition at line 219 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointForcedInteractionForGamma::PostStepDoIt().
SetAdjointEquivalentOfDirectPrimaryParticleDefinition()
void G4VEmAdjointModel::SetAdjointEquivalentOfDirectPrimaryParticleDefinition (G4ParticleDefinition * aPart)
Definition at line 728 of file G4VEmAdjointModel.cc.
SetAdjointEquivalentOfDirectSecondaryParticleDefinition()
void G4VEmAdjointModel::SetAdjointEquivalentOfDirectSecondaryParticleDefinition (G4ParticleDefinition * aPart) inline
Definition at line 196 of file G4VEmAdjointModel.hh.
SetApplyCutInRange()
void G4VEmAdjointModel::SetApplyCutInRange (G4bool aBool) inline
Definition at line 209 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointBremsstrahlungModel::G4AdjointBremsstrahlungModel(), G4AdjointComptonModel::G4AdjointComptonModel(), and G4AdjointPhotoElectricModel::G4AdjointPhotoElectricModel().
SetCorrectWeightForPostStepInModel()
void G4VEmAdjointModel::SetCorrectWeightForPostStepInModel (G4bool aBool) inline
Definition at line 218 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointForcedInteractionForGamma::PostStepDoIt().
SetCSBiasingFactor()
virtual void G4VEmAdjointModel::SetCSBiasingFactor (G4double aVal) inline virtual
Definition at line 216 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointPhysicsList::ConstructEM().
SetCSMatrices()
void G4VEmAdjointModel::SetCSMatrices (std::vector< G4AdjointCSMatrix * > * Vec1CSMatrix, std::vector< G4AdjointCSMatrix * > * Vec2CSMatrix) inline
Definition at line 173 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointCSManager::BuildCrossSectionMatrices().
SetHighEnergyLimit()
void G4VEmAdjointModel::SetHighEnergyLimit (G4double aVal)
Definition at line 715 of file G4VEmAdjointModel.cc.
Referenced by G4AdjointPhysicsList::ConstructEM().
SetLowEnergyLimit()
void G4VEmAdjointModel::SetLowEnergyLimit (G4double aVal)
Definition at line 721 of file G4VEmAdjointModel.cc.
Referenced by G4AdjointPhysicsList::ConstructEM().
SetSecondPartOfSameType()
void G4VEmAdjointModel::SetSecondPartOfSameType (G4bool aBool) inline
Definition at line 200 of file G4VEmAdjointModel.hh.
Referenced by G4eInverseBremsstrahlung::G4eInverseBremsstrahlung(), G4eInverseCompton::G4eInverseCompton(), G4eInverseIonisation::G4eInverseIonisation(), G4hInverseIonisation::G4hInverseIonisation(), G4InversePEEffect::G4InversePEEffect(), and G4IonInverseIonisation::G4IonInverseIonisation().
SetUseMatrix()
void G4VEmAdjointModel::SetUseMatrix (G4bool aBool) inline
Definition at line 204 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointPhysicsList::ConstructEM(), G4AdjointBremsstrahlungModel::G4AdjointBremsstrahlungModel(), G4AdjointComptonModel::G4AdjointComptonModel(), and G4AdjointPhotoElectricModel::G4AdjointPhotoElectricModel().
SetUseMatrixPerElement()
void G4VEmAdjointModel::SetUseMatrixPerElement (G4bool aBool) inline
Definition at line 206 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointBremsstrahlungModel::G4AdjointBremsstrahlungModel(), and G4AdjointComptonModel::G4AdjointComptonModel().
SetUseOnlyOneMatrixForAllElements()
void G4VEmAdjointModel::SetUseOnlyOneMatrixForAllElements (G4bool aBool) inline
Definition at line 207 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointComptonModel::G4AdjointComptonModel().
Field Documentation
additional_weight_correction_factor_for_post_step_outside_model
G4double G4VEmAdjointModel::additional_weight_correction_factor_for_post_step_outside_model protected
Definition at line 344 of file G4VEmAdjointModel.hh.
Referenced by G4VEmAdjointModel(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), and SetAdditionalWeightCorrectionFactorForPostStepOutsideModel().
ApplyCutInRange
G4bool G4VEmAdjointModel::ApplyCutInRange protected
Definition at line 311 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointeIonisationModel::G4AdjointeIonisationModel(), G4AdjointhIonisationModel::G4AdjointhIonisationModel(), G4AdjointIonIonisationModel::G4AdjointIonIonisationModel(), GetApplyCutInRange(), GetSecondAdjEnergyMinForScatProjToProjCase(), SampleAdjSecEnergyFromCSMatrix(), and SetApplyCutInRange().
ASelectedNucleus
G4int G4VEmAdjointModel::ASelectedNucleus protected
Definition at line 271 of file G4VEmAdjointModel.hh.
Referenced by ComputeAdjointCrossSectionVectorPerAtomForScatProj(), ComputeAdjointCrossSectionVectorPerAtomForSecond(), DiffCrossSectionFunction1(), and DiffCrossSectionFunction2().
correct_weight_for_post_step_in_model
G4bool G4VEmAdjointModel::correct_weight_for_post_step_in_model protected
Definition at line 343 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), and SetCorrectWeightForPostStepInModel().
CS_biasing_factor
G4double G4VEmAdjointModel::CS_biasing_factor protected
Definition at line 326 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointBremsstrahlungModel::AdjointCrossSection(), G4AdjointIonIonisationModel::CorrectPostStepWeight(), CorrectPostStepWeight(), DiffCrossSectionFunction1(), DiffCrossSectionFunction2(), G4AdjointBremsstrahlungModel::G4AdjointBremsstrahlungModel(), G4AdjointeIonisationModel::G4AdjointeIonisationModel(), G4AdjointhIonisationModel::G4AdjointhIonisationModel(), G4AdjointIonIonisationModel::G4AdjointIonIonisationModel(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), and SetCSBiasingFactor().
CS_Vs_ElementForProdToProjCase
std::vector<G4double> G4VEmAdjointModel::CS_Vs_ElementForProdToProjCase protected
Definition at line 285 of file G4VEmAdjointModel.hh.
Referenced by AdjointCrossSection(), and SelectCSMatrix().
CS_Vs_ElementForScatProjToProjCase
std::vector<G4double> G4VEmAdjointModel::CS_Vs_ElementForScatProjToProjCase protected
Definition at line 284 of file G4VEmAdjointModel.hh.
Referenced by AdjointCrossSection(), and SelectCSMatrix().
currentCouple
G4MaterialCutsCouple* G4VEmAdjointModel::currentCouple protected
Definition at line 306 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointPhotoElectricModel::AdjointCrossSection(), CorrectPostStepWeight(), DefineCurrentMaterial(), G4AdjointPhotoElectricModel::DefineCurrentMaterialAndElectronEnergy(), G4VEmAdjointModel(), G4AdjointComptonModel::RapidSampleSecondaries(), and G4AdjointBremsstrahlungModel::RapidSampleSecondaries().
currentCoupleIndex
size_t G4VEmAdjointModel::currentCoupleIndex protected
Definition at line 308 of file G4VEmAdjointModel.hh.
Referenced by DefineCurrentMaterial(), and G4AdjointPhotoElectricModel::DefineCurrentMaterialAndElectronEnergy().
currentMaterial
G4Material* G4VEmAdjointModel::currentMaterial protected
Definition at line 305 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointPhotoElectricModel::AdjointCrossSection(), G4AdjointComptonModel::AdjointCrossSection(), G4AdjointhIonisationModel::AdjointCrossSection(), AdjointCrossSection(), G4AdjointIonIonisationModel::CorrectPostStepWeight(), DefineCurrentMaterial(), G4AdjointPhotoElectricModel::DefineCurrentMaterialAndElectronEnergy(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), G4AdjointeIonisationModel::SampleSecondaries(), G4AdjointPhotoElectricModel::SampleSecondaries(), and SelectCSMatrix().
currentMaterialIndex
size_t G4VEmAdjointModel::currentMaterialIndex protected
Definition at line 307 of file G4VEmAdjointModel.hh.
Referenced by DefineCurrentMaterial(), G4AdjointPhotoElectricModel::DefineCurrentMaterialAndElectronEnergy(), and SelectCSMatrix().
currentTcutForDirectPrim
G4double G4VEmAdjointModel::currentTcutForDirectPrim protected
Definition at line 309 of file G4VEmAdjointModel.hh.
currentTcutForDirectSecond
G4double G4VEmAdjointModel::currentTcutForDirectSecond protected
Definition at line 310 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointBremsstrahlungModel::AdjointCrossSection(), G4AdjointhIonisationModel::AdjointCrossSection(), AdjointCrossSection(), G4AdjointIonIonisationModel::CorrectPostStepWeight(), DefineCurrentMaterial(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), SampleAdjSecEnergyFromCSMatrix(), SampleAdjSecEnergyFromDiffCrossSectionPerAtom(), and G4AdjointeIonisationModel::SampleSecondaries().
HighEnergyLimit
G4double G4VEmAdjointModel::HighEnergyLimit protected
Definition at line 321 of file G4VEmAdjointModel.hh.
Referenced by GetHighEnergyLimit(), G4AdjointhIonisationModel::GetSecondAdjEnergyMaxForProdToProjCase(), G4AdjointIonIonisationModel::GetSecondAdjEnergyMaxForProdToProjCase(), GetSecondAdjEnergyMaxForProdToProjCase(), G4AdjointComptonModel::GetSecondAdjEnergyMaxForScatProjToProjCase(), GetSecondAdjEnergyMaxForScatProjToProjCase(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), G4AdjointComptonModel::SampleSecondaries(), G4AdjointeIonisationModel::SampleSecondaries(), G4AdjointBremsstrahlungModel::SampleSecondaries(), G4AdjointhIonisationModel::SampleSecondaries(), G4AdjointIonIonisationModel::SampleSecondaries(), and SetHighEnergyLimit().
indexOfUsedCrossSectionMatrix
size_t G4VEmAdjointModel::indexOfUsedCrossSectionMatrix protected
Definition at line 336 of file G4VEmAdjointModel.hh.
Referenced by SampleAdjSecEnergyFromCSMatrix(), and SelectCSMatrix().
kinEnergyProdForIntegration
G4double G4VEmAdjointModel::kinEnergyProdForIntegration protected
Definition at line 274 of file G4VEmAdjointModel.hh.
Referenced by ComputeAdjointCrossSectionVectorPerAtomForSecond(), ComputeAdjointCrossSectionVectorPerVolumeForSecond(), and DiffCrossSectionFunction1().
kinEnergyProjForIntegration
G4double G4VEmAdjointModel::kinEnergyProjForIntegration protected
Definition at line 276 of file G4VEmAdjointModel.hh.
Referenced by DiffCrossSectionPerVolumeFunctionForIntegrationOverEkinProj().
kinEnergyScatProjForIntegration
G4double G4VEmAdjointModel::kinEnergyScatProjForIntegration protected
Definition at line 275 of file G4VEmAdjointModel.hh.
Referenced by ComputeAdjointCrossSectionVectorPerAtomForScatProj(), ComputeAdjointCrossSectionVectorPerVolumeForScatProj(), and DiffCrossSectionFunction2().
lastAdjointCSForProdToProjCase
G4double G4VEmAdjointModel::lastAdjointCSForProdToProjCase protected
Definition at line 289 of file G4VEmAdjointModel.hh.
Referenced by AdjointCrossSection(), CorrectPostStepWeight(), G4AdjointeIonisationModel::SampleSecondaries(), and SelectCSMatrix().
lastAdjointCSForScatProjToProjCase
G4double G4VEmAdjointModel::lastAdjointCSForScatProjToProjCase protected
Definition at line 288 of file G4VEmAdjointModel.hh.
Referenced by AdjointCrossSection(), CorrectPostStepWeight(), G4AdjointeIonisationModel::SampleSecondaries(), and SelectCSMatrix().
lastCS
G4double G4VEmAdjointModel::lastCS protected
Definition at line 287 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointPhotoElectricModel::AdjointCrossSection(), G4AdjointComptonModel::AdjointCrossSection(), G4AdjointhIonisationModel::AdjointCrossSection(), AdjointCrossSection(), CorrectPostStepWeight(), G4AdjointhIonisationModel::RapidSampleSecondaries(), G4AdjointeIonisationModel::SampleSecondaries(), and SelectCSMatrix().
LowEnergyLimit
G4double G4VEmAdjointModel::LowEnergyLimit protected
Definition at line 322 of file G4VEmAdjointModel.hh.
Referenced by GetLowEnergyLimit(), and SetLowEnergyLimit().
mass_ratio_product
G4double G4VEmAdjointModel::mass_ratio_product protected
Definition at line 315 of file G4VEmAdjointModel.hh.
Referenced by G4VEmAdjointModel().
mass_ratio_projectile
G4double G4VEmAdjointModel::mass_ratio_projectile protected
Definition at line 316 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointhIonisationModel::DefineProjectileProperty(), G4AdjointIonIonisationModel::DefineProjectileProperty(), and G4VEmAdjointModel().
model_index
size_t G4VEmAdjointModel::model_index protected
Definition at line 338 of file G4VEmAdjointModel.hh.
Referenced by G4VEmAdjointModel().
name
const G4String G4VEmAdjointModel::name protected
Definition at line 266 of file G4VEmAdjointModel.hh.
Referenced by GetName().
pOnCSMatrixForProdToProjBackwardScattering
std::vector< G4AdjointCSMatrix* >* G4VEmAdjointModel::pOnCSMatrixForProdToProjBackwardScattering protected
Definition at line 282 of file G4VEmAdjointModel.hh.
Referenced by SetCSMatrices().
pOnCSMatrixForScatProjToProjBackwardScattering
std::vector< G4AdjointCSMatrix* >* G4VEmAdjointModel::pOnCSMatrixForScatProjToProjBackwardScattering protected
Definition at line 283 of file G4VEmAdjointModel.hh.
Referenced by SetCSMatrices().
pParticleChange
G4VParticleChange* G4VEmAdjointModel::pParticleChange protected
Definition at line 258 of file G4VEmAdjointModel.hh.
preStepEnergy
G4double G4VEmAdjointModel::preStepEnergy protected
Definition at line 301 of file G4VEmAdjointModel.hh.
Referenced by AdjointCrossSection(), and CorrectPostStepWeight().
second_part_of_same_type
G4bool G4VEmAdjointModel::second_part_of_same_type protected
Definition at line 297 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointBremsstrahlungModel::G4AdjointBremsstrahlungModel(), G4AdjointComptonModel::G4AdjointComptonModel(), G4AdjointeIonisationModel::G4AdjointeIonisationModel(), G4AdjointhIonisationModel::G4AdjointhIonisationModel(), G4AdjointIonIonisationModel::G4AdjointIonIonisationModel(), G4AdjointPhotoElectricModel::G4AdjointPhotoElectricModel(), G4VEmAdjointModel(), GetSecondAdjEnergyMaxForScatProjToProjCase(), GetSecondAdjEnergyMinForProdToProjCase(), GetSecondPartOfSameType(), SampleAdjSecEnergyFromCSMatrix(), and SetSecondPartOfSameType().
SelectedMaterial
G4Material* G4VEmAdjointModel::SelectedMaterial protected
Definition at line 273 of file G4VEmAdjointModel.hh.
Referenced by ComputeAdjointCrossSectionVectorPerVolumeForScatProj(), ComputeAdjointCrossSectionVectorPerVolumeForSecond(), DiffCrossSectionFunction1(), DiffCrossSectionFunction2(), and DiffCrossSectionPerVolumeFunctionForIntegrationOverEkinProj().
theAdjEquivOfDirectPrimPartDef
G4ParticleDefinition* G4VEmAdjointModel::theAdjEquivOfDirectPrimPartDef protected
Definition at line 294 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointBremsstrahlungModel::G4AdjointBremsstrahlungModel(), G4AdjointComptonModel::G4AdjointComptonModel(), G4AdjointeIonisationModel::G4AdjointeIonisationModel(), G4AdjointhIonisationModel::G4AdjointhIonisationModel(), G4AdjointIonIonisationModel::G4AdjointIonIonisationModel(), G4AdjointPhotoElectricModel::G4AdjointPhotoElectricModel(), GetAdjointEquivalentOfDirectPrimaryParticleDefinition(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), G4AdjointComptonModel::SampleSecondaries(), G4AdjointeIonisationModel::SampleSecondaries(), G4AdjointBremsstrahlungModel::SampleSecondaries(), G4AdjointIonIonisationModel::SampleSecondaries(), G4AdjointhIonisationModel::SampleSecondaries(), SetAdjointEquivalentOfDirectPrimaryParticleDefinition(), and G4AdjointIonIonisationModel::SetIon().
theAdjEquivOfDirectSecondPartDef
G4ParticleDefinition* G4VEmAdjointModel::theAdjEquivOfDirectSecondPartDef protected
Definition at line 295 of file G4VEmAdjointModel.hh.
Referenced by DefineCurrentMaterial(), G4AdjointBremsstrahlungModel::G4AdjointBremsstrahlungModel(), G4AdjointComptonModel::G4AdjointComptonModel(), G4AdjointeIonisationModel::G4AdjointeIonisationModel(), G4AdjointhIonisationModel::G4AdjointhIonisationModel(), G4AdjointIonIonisationModel::G4AdjointIonIonisationModel(), G4AdjointPhotoElectricModel::G4AdjointPhotoElectricModel(), GetAdjointEquivalentOfDirectSecondaryParticleDefinition(), G4AdjointhIonisationModel::RapidSampleSecondaries(), G4AdjointeIonisationModel::SampleSecondaries(), G4AdjointhIonisationModel::SampleSecondaries(), G4AdjointIonIonisationModel::SampleSecondaries(), and SetAdjointEquivalentOfDirectSecondaryParticleDefinition().
theDirectEMModel
G4VEmModel* G4VEmAdjointModel::theDirectEMModel protected
Definition at line 257 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointBremsstrahlungModel::AdjointCrossSection(), G4AdjointIonIonisationModel::CorrectPostStepWeight(), DefineDirectEMModel(), G4AdjointComptonModel::DiffCrossSectionPerAtomPrimToScatPrim(), G4AdjointIonIonisationModel::DiffCrossSectionPerAtomPrimToSecond(), G4AdjointhIonisationModel::DiffCrossSectionPerAtomPrimToSecond(), DiffCrossSectionPerAtomPrimToSecond(), DiffCrossSectionPerVolumePrimToSecond(), G4AdjointBremsstrahlungModel::DiffCrossSectionPerVolumePrimToSecondApproximated1(), G4AdjointBremsstrahlungModel::DiffCrossSectionPerVolumePrimToSecondApproximated2(), G4AdjointBremsstrahlungModel::G4AdjointBremsstrahlungModel(), G4AdjointComptonModel::G4AdjointComptonModel(), G4AdjointhIonisationModel::G4AdjointhIonisationModel(), G4VEmAdjointModel(), G4AdjointBremsstrahlungModel::GetAdjointCrossSection(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), SetHighEnergyLimit(), and SetLowEnergyLimit().
theDirectPrimaryPartDef
G4ParticleDefinition* G4VEmAdjointModel::theDirectPrimaryPartDef protected
Definition at line 296 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointBremsstrahlungModel::AdjointCrossSection(), G4AdjointIonIonisationModel::CorrectPostStepWeight(), G4AdjointhIonisationModel::DefineProjectileProperty(), G4AdjointIonIonisationModel::DefineProjectileProperty(), G4AdjointIonIonisationModel::DiffCrossSectionPerAtomPrimToSecond(), G4AdjointhIonisationModel::DiffCrossSectionPerAtomPrimToSecond(), DiffCrossSectionPerAtomPrimToSecond(), DiffCrossSectionPerVolumePrimToSecond(), G4AdjointBremsstrahlungModel::DiffCrossSectionPerVolumePrimToSecondApproximated1(), G4AdjointBremsstrahlungModel::DiffCrossSectionPerVolumePrimToSecondApproximated2(), G4AdjointBremsstrahlungModel::G4AdjointBremsstrahlungModel(), G4AdjointComptonModel::G4AdjointComptonModel(), G4AdjointeIonisationModel::G4AdjointeIonisationModel(), G4AdjointhIonisationModel::G4AdjointhIonisationModel(), G4AdjointIonIonisationModel::G4AdjointIonIonisationModel(), G4AdjointPhotoElectricModel::G4AdjointPhotoElectricModel(), G4AdjointBremsstrahlungModel::GetAdjointCrossSection(), SetAdjointEquivalentOfDirectPrimaryParticleDefinition(), and G4AdjointIonIonisationModel::SetIon().
UseMatrix
G4bool G4VEmAdjointModel::UseMatrix protected
Definition at line 330 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointComptonModel::AdjointCrossSection(), G4AdjointBremsstrahlungModel::AdjointCrossSection(), G4AdjointhIonisationModel::AdjointCrossSection(), G4AdjointeIonisationModel::G4AdjointeIonisationModel(), G4AdjointhIonisationModel::G4AdjointhIonisationModel(), G4AdjointIonIonisationModel::G4AdjointIonIonisationModel(), GetUseMatrix(), G4AdjointComptonModel::SampleSecondaries(), G4AdjointBremsstrahlungModel::SampleSecondaries(), G4AdjointhIonisationModel::SampleSecondaries(), and SetUseMatrix().
UseMatrixPerElement
G4bool G4VEmAdjointModel::UseMatrixPerElement protected
Definition at line 331 of file G4VEmAdjointModel.hh.
Referenced by DiffCrossSectionFunction1(), DiffCrossSectionFunction2(), G4AdjointeIonisationModel::G4AdjointeIonisationModel(), G4AdjointhIonisationModel::G4AdjointhIonisationModel(), G4AdjointIonIonisationModel::G4AdjointIonIonisationModel(), GetUseMatrixPerElement(), SelectCSMatrix(), and SetUseMatrixPerElement().
UseOnlyOneMatrixForAllElements
G4bool G4VEmAdjointModel::UseOnlyOneMatrixForAllElements protected
Definition at line 332 of file G4VEmAdjointModel.hh.
Referenced by G4AdjointeIonisationModel::G4AdjointeIonisationModel(), G4AdjointhIonisationModel::G4AdjointhIonisationModel(), G4AdjointIonIonisationModel::G4AdjointIonIonisationModel(), GetUseOnlyOneMatrixForAllElements(), SelectCSMatrix(), and SetUseOnlyOneMatrixForAllElements().
ZSelectedNucleus
G4int G4VEmAdjointModel::ZSelectedNucleus protected
Definition at line 272 of file G4VEmAdjointModel.hh.
Referenced by ComputeAdjointCrossSectionVectorPerAtomForScatProj(), ComputeAdjointCrossSectionVectorPerAtomForSecond(), DiffCrossSectionFunction1(), and DiffCrossSectionFunction2().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/adjoint/include/G4VEmAdjointModel.hh
source/processes/electromagnetic/adjoint/src/G4VEmAdjointModel.cc