Geant4: G4RPGFragmentation Class Reference
G4RPGFragmentation Class Reference
#include <G4RPGFragmentation.hh>
Public Member Functions
G4RPGFragmentation ()
void FragmentationIntegral (G4double, G4double, G4double, G4double)
G4bool ReactionStage (const G4HadProjectile *, G4ReactionProduct &, G4bool &, const G4DynamicParticle *, G4ReactionProduct &, G4bool &, const G4Nucleus &, G4ReactionProduct &, G4FastVector< G4ReactionProduct, 256 > &, G4int &, G4bool, G4ReactionProduct &)
Public Member Functions inherited from G4RPGReaction
G4RPGReaction ()
virtual ~G4RPGReaction ()
G4bool ReactionStage (const G4HadProjectile *, G4ReactionProduct &, G4bool &, const G4DynamicParticle *, G4ReactionProduct &, G4bool &, const G4Nucleus &, G4ReactionProduct &, G4FastVector< G4ReactionProduct, 256 > &, G4int &, G4bool, G4ReactionProduct &)
void AddBlackTrackParticles (const G4double, const G4int, const G4double, const G4int, const G4ReactionProduct &, G4int, G4int, const G4Nucleus &, G4FastVector< G4ReactionProduct, 256 > &, G4int &)
G4double GenerateNBodyEvent (const G4double totalEnergy, const G4bool constantCrossSection, G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen)
G4double GenerateNBodyEventT (const G4double totalEnergy, const G4bool constantCrossSection, std::vector< G4ReactionProduct * > &list)
void NuclearReaction (G4FastVector< G4ReactionProduct, 4 > &vec, G4int &vecLen, const G4HadProjectile *originalIncident, const G4Nucleus &aNucleus, const G4double theAtomicMass, const G4double *massVec)
Private Member Functions
void ReduceEnergiesOfSecondaries (G4int, G4double &, G4double &, G4FastVector< G4ReactionProduct, 256 > &, G4int &, G4ReactionProduct &, G4ReactionProduct &, G4double &)
Private Attributes
G4double dndl [20]
Additional Inherited Members
Protected Member Functions inherited from G4RPGReaction
void Rotate (const G4double numberofFinalStateNucleons, const G4ThreeVector &temp, const G4ReactionProduct &modifiedOriginal, const G4HadProjectile *originalIncident, const G4Nucleus &targetNucleus, G4ReactionProduct &currentParticle, G4ReactionProduct &targetParticle, G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen)
void Defs1 (const G4ReactionProduct &modifiedOriginal, G4ReactionProduct &currentParticle, G4ReactionProduct &targetParticle, G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen)
std::pair< G4int, G4int > GetFinalStateNucleons (const G4DynamicParticle *originalTarget, const G4FastVector< G4ReactionProduct, 256 > &vec, const G4int &vecLen)
void MomentumCheck (const G4ReactionProduct &modifiedOriginal, G4ReactionProduct &currentParticle, G4ReactionProduct &targetParticle, G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen)
G4double normal ()
G4ThreeVector Isotropic (const G4double &)
Detailed Description
Definition at line 48 of file G4RPGFragmentation.hh.
Constructor & Destructor Documentation
G4RPGFragmentation()
G4RPGFragmentation::G4RPGFragmentation ()
Definition at line 42 of file G4RPGFragmentation.cc.
Member Function Documentation
FragmentationIntegral()
void G4RPGFragmentation::FragmentationIntegral (G4double pt, G4double et, G4double parMass, G4double secMass)
Definition at line 50 of file G4RPGFragmentation.cc.
Referenced by ReactionStage().
ReactionStage()
G4bool G4RPGFragmentation::ReactionStage (const G4HadProjectile * originalIncident, G4ReactionProduct & modifiedOriginal, G4bool & incidentHasChanged, const G4DynamicParticle * originalTarget, G4ReactionProduct & targetParticle, G4bool & targetHasChanged, const G4Nucleus & targetNucleus, G4ReactionProduct & currentParticle, G4FastVector< G4ReactionProduct, 256 > & vec, G4int & vecLen, G4bool leadFlag, G4ReactionProduct & leadingStrangeParticle)
Definition at line 69 of file G4RPGFragmentation.cc.
Referenced by G4RPGInelastic::CalculateMomenta().
ReduceEnergiesOfSecondaries()
void G4RPGFragmentation::ReduceEnergiesOfSecondaries (G4int startingIndex, G4double & forwardKinetic, G4double & backwardKinetic, G4FastVector< G4ReactionProduct, 256 > & vec, G4int & vecLen, G4ReactionProduct & forwardPseudoParticle, G4ReactionProduct & backwardPseudoParticle, G4double & pt) private
Definition at line 1126 of file G4RPGFragmentation.cc.
Referenced by ReactionStage().
Field Documentation
dndl
G4double G4RPGFragmentation::dndl[20] private
Definition at line 83 of file G4RPGFragmentation.hh.
Referenced by FragmentationIntegral(), G4RPGFragmentation(), and ReactionStage().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/rpg/include/G4RPGFragmentation.hh
source/processes/hadronic/models/rpg/src/G4RPGFragmentation.cc