Geant4: G4PSNofCollision Class Reference
G4PSNofCollision Class Reference
#include <G4PSNofCollision.hh>
Public Member Functions
G4PSNofCollision (G4String name, G4int depth=0)
virtual ~G4PSNofCollision ()
void Weighted (G4bool flg=true)
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
virtual void SetUnit (const G4String &unit)
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Protected Member Functions
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
Protected Member Functions inherited from G4VPrimitiveScorer
virtual G4int GetIndex (G4Step *)
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Private Attributes
G4int HCID
G4THitsMap< G4double > * EvtMap
G4bool weighted
Additional Inherited Members
Protected Attributes inherited from G4VPrimitiveScorer
G4String primitiveName
G4MultiFunctionalDetector * detector
G4VSDFilter * filter
G4int verboseLevel
G4int indexDepth
G4String unitName
G4double unitValue
G4int fNi
G4int fNj
G4int fNk
Detailed Description
Definition at line 46 of file G4PSNofCollision.hh.
Constructor & Destructor Documentation
G4PSNofCollision()
G4PSNofCollision::G4PSNofCollision (G4String name, G4int depth = 0)
Definition at line 41 of file G4PSNofCollision.cc.
~G4PSNofCollision()
G4PSNofCollision::~G4PSNofCollision () virtual
Definition at line 47 of file G4PSNofCollision.cc.
Member Function Documentation
clear()
void G4PSNofCollision::clear (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 71 of file G4PSNofCollision.cc.
DrawAll()
void G4PSNofCollision::DrawAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 75 of file G4PSNofCollision.cc.
EndOfEvent()
void G4PSNofCollision::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 68 of file G4PSNofCollision.cc.
Initialize()
void G4PSNofCollision::Initialize (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 61 of file G4PSNofCollision.cc.
PrintAll()
void G4PSNofCollision::PrintAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 78 of file G4PSNofCollision.cc.
ProcessHits()
G4bool G4PSNofCollision::ProcessHits (G4Step * aStep, G4TouchableHistory *) protected virtual
Implements G4VPrimitiveScorer.
Definition at line 50 of file G4PSNofCollision.cc.
SetUnit()
void G4PSNofCollision::SetUnit (const G4String & unit) virtual
Definition at line 93 of file G4PSNofCollision.cc.
Referenced by G4PSNofCollision().
Weighted()
void G4PSNofCollision::Weighted (G4bool flg = true) inline
Definition at line 58 of file G4PSNofCollision.hh.
Referenced by B03ImportanceDetectorConstruction::ConstructSD(), B02ImportanceDetectorConstruction::ConstructSD(), and B01DetectorConstruction::ConstructSDandField().
Field Documentation
EvtMap
G4THitsMap<G4double>* G4PSNofCollision::EvtMap private
Definition at line 74 of file G4PSNofCollision.hh.
Referenced by clear(), Initialize(), PrintAll(), and ProcessHits().
HCID
G4int G4PSNofCollision::HCID private
Definition at line 73 of file G4PSNofCollision.hh.
Referenced by Initialize().
weighted
G4bool G4PSNofCollision::weighted private
Definition at line 75 of file G4PSNofCollision.hh.
Referenced by ProcessHits(), and Weighted().
The documentation for this class was generated from the following files:
source/digits_hits/scorer/include/G4PSNofCollision.hh
source/digits_hits/scorer/src/G4PSNofCollision.cc