Geant4: G4TableTemplate< T > Class Template Reference
G4TableTemplate< T > Class Template Reference
G4TableTemplate is essentially a wrapper around a std::vector designed to work specifically with pointers.
#include <G4TableTemplate.hh>
Public Member Functions
G4TableTemplate (void)
Default constructor.
void G4AddContainer (T *NewContainer)
Adds a container to the table.
G4TableTemplate * G4GetTable (void)
Gets a pointer to the table.
T * G4GetContainer (unsigned int WhichContainer)
Retrieve a container from the table.
T * G4GetNewContainer (void)
Create a new blank container.
T * G4GetNewContainer (G4int DefaultValue)
Create a new container that is constructed with a G4int.
G4long G4GetNumberOfElements (void)
Get the number of elements in the table.
~G4TableTemplate (void)
Private Attributes
std::vector< T * > ContainerTable_
Detailed Description
template<class T>
class G4TableTemplate< T >
G4TableTemplate is essentially a wrapper around a std::vector designed to work specifically with pointers.
Definition at line 46 of file G4TableTemplate.hh.
Constructor & Destructor Documentation
G4TableTemplate()
template<class T > G4TableTemplate< T >::G4TableTemplate (void)
Default constructor.
Definition at line 73 of file G4TableTemplate.hh.
~G4TableTemplate()
template<class T > G4TableTemplate< T >::~G4TableTemplate (void)
Definition at line 131 of file G4TableTemplate.hh.
Member Function Documentation
G4AddContainer()
template<class T> void G4TableTemplate< T >::G4AddContainer (T * NewContainer)
Adds a container to the table.
Definition at line 80 of file G4TableTemplate.hh.
G4GetContainer()
template<class T > T * G4TableTemplate< T >::G4GetContainer (unsigned int WhichContainer)
Retrieve a container from the table.
Definition at line 94 of file G4TableTemplate.hh.
Referenced by G4ENDFTapeRead::G4GetYield().
G4GetNewContainer() [1/2]
template<class T > T * G4TableTemplate< T >::G4GetNewContainer (G4int DefaultValue)
Create a new container that is constructed with a G4int.
Definition at line 115 of file G4TableTemplate.hh.
G4GetNewContainer() [2/2]
template<class T > T * G4TableTemplate< T >::G4GetNewContainer (void)
Create a new blank container.
Definition at line 106 of file G4TableTemplate.hh.
Referenced by G4ENDFTapeRead::ReadInData().
G4GetNumberOfElements()
template<class T > G4long G4TableTemplate< T >::G4GetNumberOfElements (void)
Get the number of elements in the table.
Definition at line 124 of file G4TableTemplate.hh.
Referenced by G4ENDFTapeRead::G4GetNumberOfFissionProducts().
G4GetTable()
template<class T > G4TableTemplate< T > * G4TableTemplate< T >::G4GetTable (void)
Gets a pointer to the table.
Definition at line 87 of file G4TableTemplate.hh.
Field Documentation
ContainerTable_
template<class T> std::vector<T*> G4TableTemplate< T >::ContainerTable_ private
Definition at line 65 of file G4TableTemplate.hh.
The documentation for this class was generated from the following file:
source/processes/hadronic/models/particle_hp/include/G4TableTemplate.hh