Geant4: CCalDetector Class Reference
CCalDetector Class Reference abstract
#include <CCalDetector.hh>
Public Member Functions
CCalDetector (const G4String &name)
virtual ~CCalDetector ()
void constructHierarchy ()
void construct ()
void addDetector (CCalDetector *)
G4String Name () const
G4String baseFileName () const
G4String File () const
CCalDetector * getDaughter (int i) const
int getNDaughters () const
G4bool operator== (const CCalDetector &left) const
G4bool operator!= (const CCalDetector &left) const
Protected Member Functions
virtual int readFile ()=0
virtual void constructDaughters ()=0
int buildFromFile ()
Protected Attributes
G4String detectorName
G4String fileName
G4String pathName
CCalDetectorTable theDetectorsInside
int constructFlag
Friends
std::ostream & operator<< (std::ostream &, const CCalDetector &)
Detailed Description
Definition at line 49 of file CCalDetector.hh.
Constructor & Destructor Documentation
CCalDetector()
CCalDetector::CCalDetector (const G4String & name)
Definition at line 44 of file CCalDetector.cc.
~CCalDetector()
CCalDetector::~CCalDetector () virtual
Definition at line 62 of file CCalDetector.cc.
Member Function Documentation
addDetector()
void CCalDetector::addDetector (CCalDetector * det)
Definition at line 95 of file CCalDetector.cc.
Referenced by CCalG4Hall::constructDaughters(), and CCalHall::constructDaughters().
baseFileName()
G4String CCalDetector::baseFileName () const inline
Definition at line 78 of file CCalDetector.hh.
buildFromFile()
int CCalDetector::buildFromFile () protected
Definition at line 103 of file CCalDetector.cc.
Referenced by construct().
construct()
void CCalDetector::construct ()
Definition at line 70 of file CCalDetector.cc.
Referenced by constructHierarchy().
constructDaughters()
virtual void CCalDetector::constructDaughters () protected pure virtual
Implemented in CCalHcal, CCalEcal, CCalG4Hcal, CCalHall, and CCalG4Hall.
Referenced by construct().
constructHierarchy()
void CCalDetector::constructHierarchy () inline
Definition at line 66 of file CCalDetector.hh.
Referenced by CCalDetectorConstruction::Construct().
File()
G4String CCalDetector::File () const inline
Definition at line 79 of file CCalDetector.hh.
Referenced by CCalHall::readFile(), CCalEcal::readFile(), and CCalHcal::readFile().
getDaughter()
CCalDetector* CCalDetector::getDaughter (int i) const inline
Definition at line 80 of file CCalDetector.hh.
getNDaughters()
int CCalDetector::getNDaughters () const inline
Definition at line 81 of file CCalDetector.hh.
Name()
G4String CCalDetector::Name () const inline
Definition at line 77 of file CCalDetector.hh.
Referenced by construct(), CCalG4Hcal::constructAbsorberLayer(), CCalG4Hall::constructIn(), CCalG4Hcal::constructIn(), CCalG4Hcal::constructScintillatorLayer(), and CCalG4Hcal::constructSensitive().
operator!=()
G4bool CCalDetector::operator!= (const CCalDetector & left) const inline
Definition at line 90 of file CCalDetector.hh.
operator==()
G4bool CCalDetector::operator== (const CCalDetector & left) const inline
Definition at line 87 of file CCalDetector.hh.
readFile()
virtual int CCalDetector::readFile () protected pure virtual
Implemented in CCalHcal, CCalEcal, and CCalHall.
Referenced by buildFromFile().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CCalDetector & det) friend
Definition at line 111 of file CCalDetector.cc.
Field Documentation
constructFlag
int CCalDetector::constructFlag protected
Definition at line 122 of file CCalDetector.hh.
Referenced by CCalDetector(), and construct().
detectorName
G4String CCalDetector::detectorName protected
Definition at line 116 of file CCalDetector.hh.
Referenced by Name(), operator!=(), operator<<(), and operator==().
fileName
G4String CCalDetector::fileName protected
Definition at line 117 of file CCalDetector.hh.
Referenced by baseFileName(), CCalDetector(), File(), and operator<<().
pathName
G4String CCalDetector::pathName protected
Definition at line 118 of file CCalDetector.hh.
Referenced by CCalDetector(), CCalHall::readFile(), CCalEcal::readFile(), and CCalHcal::readFile().
theDetectorsInside
CCalDetectorTable CCalDetector::theDetectorsInside protected
Definition at line 120 of file CCalDetector.hh.
Referenced by addDetector(), construct(), getDaughter(), getNDaughters(), operator<<(), and ~CCalDetector().
The documentation for this class was generated from the following files:
examples/advanced/composite_calorimeter/include/CCalDetector.hh
examples/advanced/composite_calorimeter/src/CCalDetector.cc