Geant4: G4ModifiedMidpoint Class Reference
G4ModifiedMidpoint Class Reference
#include <G4ModifiedMidpoint.hh>
Public Member Functions
G4ModifiedMidpoint (G4EquationOfMotion *equation, G4int nvar=6, G4int steps=2)
~G4ModifiedMidpoint ()=default
void DoStep (const G4double yIn[], const G4double dydxIn[], G4double yOut[], G4double hstep) const
void DoStep (const G4double yIn[], const G4double dydxIn[], G4double yOut[], G4double hstep, G4double yMid[], G4double derivs[][G4FieldTrack::ncompSVEC]) const
void SetSteps (G4int steps)
G4int GetSteps () const
void SetEquationOfMotion (G4EquationOfMotion *equation)
G4EquationOfMotion * GetEquationOfMotion ()
G4int GetNumberOfVariables () const
Private Member Functions
void copy (G4double dst[], const G4double src[]) const
Private Attributes
G4EquationOfMotion * fEquation
G4int fnvar
G4int fsteps
Detailed Description
Definition at line 45 of file G4ModifiedMidpoint.hh.
Constructor & Destructor Documentation
G4ModifiedMidpoint()
G4ModifiedMidpoint::G4ModifiedMidpoint (G4EquationOfMotion * equation, G4int nvar = 6, G4int steps = 2)
Definition at line 39 of file G4ModifiedMidpoint.cc.
~G4ModifiedMidpoint()
G4ModifiedMidpoint::~G4ModifiedMidpoint () default
Member Function Documentation
copy()
void G4ModifiedMidpoint::copy (G4double dst[], const G4double src[]) const private
Definition at line 154 of file G4ModifiedMidpoint.cc.
Referenced by DoStep().
DoStep() [1/2]
void G4ModifiedMidpoint::DoStep (const G4double yIn[], const G4double dydxIn[], G4double yOut[], G4double hstep) const
Definition at line 51 of file G4ModifiedMidpoint.cc.
Referenced by G4BulirschStoer::try_step().
DoStep() [2/2]
void G4ModifiedMidpoint::DoStep (const G4double yIn[], const G4double dydxIn[], G4double yOut[], G4double hstep, G4double yMid[], G4double derivs[][G4FieldTrack::ncompSVEC]) const
Definition at line 96 of file G4ModifiedMidpoint.cc.
GetEquationOfMotion()
G4EquationOfMotion* G4ModifiedMidpoint::GetEquationOfMotion () inline
GetNumberOfVariables()
G4int G4ModifiedMidpoint::GetNumberOfVariables () const inline
GetSteps()
G4int G4ModifiedMidpoint::GetSteps () const inline
SetEquationOfMotion()
void G4ModifiedMidpoint::SetEquationOfMotion (G4EquationOfMotion * equation) inline
SetSteps()
void G4ModifiedMidpoint::SetSteps (G4int steps) inline
Referenced by G4BulirschStoer::try_step().
Field Documentation
fEquation
G4EquationOfMotion* G4ModifiedMidpoint::fEquation private
Definition at line 74 of file G4ModifiedMidpoint.hh.
Referenced by DoStep().
fnvar
G4int G4ModifiedMidpoint::fnvar private
Definition at line 75 of file G4ModifiedMidpoint.hh.
Referenced by copy(), and DoStep().
fsteps
G4int G4ModifiedMidpoint::fsteps private
Definition at line 76 of file G4ModifiedMidpoint.hh.
Referenced by DoStep().
The documentation for this class was generated from the following files:
source/geometry/magneticfield/include/G4ModifiedMidpoint.hh
source/geometry/magneticfield/src/G4ModifiedMidpoint.cc