Geant4: G4Triton Class Reference
G4Triton Class Reference
#include <G4Triton.hh>
Static Public Member Functions
static G4Triton * Definition ()
static G4Triton * TritonDefinition ()
static G4Triton * Triton ()
Static Public Member Functions inherited from G4Ions
static G4Ions::G4FloatLevelBase FloatLevelBase (char flbChar)
static G4Ions::G4FloatLevelBase FloatLevelBase (G4int flbIdx)
static char FloatLevelBaseChar (G4Ions::G4FloatLevelBase flb)
Static Public Member Functions inherited from G4ParticleDefinition
static const G4PDefManager & GetSubInstanceManager ()
static void Clean ()
Private Member Functions
G4Triton ()
~G4Triton ()
Static Private Attributes
static G4Triton * theInstance = 0
Additional Inherited Members
Public Types inherited from G4Ions
enum G4FloatLevelBase {
G4FloatLevelBase::no_Float =0, G4FloatLevelBase::plus_X, G4FloatLevelBase::plus_Y, G4FloatLevelBase::plus_Z,
G4FloatLevelBase::plus_U, G4FloatLevelBase::plus_V, G4FloatLevelBase::plus_W, G4FloatLevelBase::plus_R,
G4FloatLevelBase::plus_S, G4FloatLevelBase::plus_T, G4FloatLevelBase::plus_A, G4FloatLevelBase::plus_B,
G4FloatLevelBase::plus_C, G4FloatLevelBase::plus_D, G4FloatLevelBase::plus_E
}
Public Member Functions inherited from G4Ions
G4Ions (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospin3, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable, G4bool shortlived, const G4String &subType="", G4int anti_encoding=0, G4double excitation=0.0, G4int isomer=0)
virtual ~G4Ions ()
G4Ions * IonsDefinition ()
G4Ions * Ions ()
G4double GetExcitationEnergy () const
G4int GetIsomerLevel () const
G4Ions::G4FloatLevelBase GetFloatLevelBase () const
G4int GetFloatLevelBaseIndex () const
void SetFloatLevelBase (G4Ions::G4FloatLevelBase flb)
void SetFloatLevelBase (char flbChar)
void SetFloatLevelBase (G4int flbIdx)
Public Member Functions inherited from G4ParticleDefinition
G4ParticleDefinition (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospinZ, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable, G4bool shortlived=false, const G4String &subType="", G4int anti_encoding=0, G4double magneticMoment=0.0)
virtual ~G4ParticleDefinition ()
const G4String & GetParticleName () const
G4double GetPDGMass () const
G4double GetPDGWidth () const
G4double GetPDGCharge () const
G4double GetPDGSpin () const
G4int GetPDGiSpin () const
G4int GetPDGiParity () const
G4int GetPDGiConjugation () const
G4double GetPDGIsospin () const
G4double GetPDGIsospin3 () const
G4int GetPDGiIsospin () const
G4int GetPDGiIsospin3 () const
G4int GetPDGiGParity () const
G4double GetPDGMagneticMoment () const
void SetPDGMagneticMoment (G4double mageticMoment)
G4double CalculateAnomaly () const
const G4String & GetParticleType () const
const G4String & GetParticleSubType () const
G4int GetLeptonNumber () const
G4int GetBaryonNumber () const
G4int GetPDGEncoding () const
G4int GetAntiPDGEncoding () const
void SetAntiPDGEncoding (G4int aEncoding)
G4int GetQuarkContent (G4int flavor) const
G4int GetAntiQuarkContent (G4int flavor) const
G4bool IsShortLived () const
G4bool GetPDGStable () const
void SetPDGStable (const G4bool aFlag)
G4double GetPDGLifeTime () const
void SetPDGLifeTime (G4double aLifeTime)
G4double GetIonLifeTime () const
G4DecayTable * GetDecayTable () const
void SetDecayTable (G4DecayTable *aDecayTable)
G4ProcessManager * GetProcessManager () const
void SetProcessManager (G4ProcessManager *aProcessManager)
G4ParticleTable * GetParticleTable () const
G4int GetAtomicNumber () const
G4int GetAtomicMass () const
void DumpTable () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetApplyCutsFlag (G4bool)
G4bool GetApplyCutsFlag () const
G4bool IsGeneralIon () const
G4bool IsMuonicAtom () const
G4bool operator== (const G4ParticleDefinition &right) const
G4bool operator!= (const G4ParticleDefinition &right) const
G4ProcessManager * GetMasterProcessManager () const
void SetMasterProcessManager (G4ProcessManager *aNewPM)
G4int GetInstanceID () const
void SetParticleDefinitionID (G4int id=-1)
G4int GetParticleDefinitionID () const
Protected Types inherited from G4ParticleDefinition
enum { NumberOfQuarkFlavor = 6 }
Protected Member Functions inherited from G4Ions
G4Ions ()
Protected Member Functions inherited from G4ParticleDefinition
G4int FillQuarkContents ()
void SetParticleSubType (const G4String &subtype)
void SetAtomicNumber (G4int)
void SetAtomicMass (G4int)
G4ParticleDefinition (const G4ParticleDefinition &right)
G4ParticleDefinition ()
Protected Attributes inherited from G4ParticleDefinition
G4int theQuarkContent [NumberOfQuarkFlavor]
G4int theAntiQuarkContent [NumberOfQuarkFlavor]
G4bool isGeneralIon
G4bool isMuonicAtom
Detailed Description
Definition at line 50 of file G4Triton.hh.
Constructor & Destructor Documentation
G4Triton()
G4Triton::G4Triton () inline private
Definition at line 54 of file G4Triton.hh.
~G4Triton()
G4Triton::~G4Triton () inline private
Definition at line 55 of file G4Triton.hh.
Member Function Documentation
Definition()
G4Triton * G4Triton::Definition () static
Definition at line 49 of file G4Triton.cc.
Referenced by G4InuclElementaryParticle::makeDefinition(), Triton(), TritonDefinition(), and G4InuclElementaryParticle::type().
Triton()
G4Triton * G4Triton::Triton () static
Definition at line 94 of file G4Triton.cc.
Referenced by G4RPGReaction::AddBlackTrackParticles(), G4ParticleHPFinalState::adjust_final_state(), G4ParticleHPT2AInelasticFS::ApplyYourself(), G4ParticleHPNT2AInelasticFS::ApplyYourself(), G4ParticleHPNTInelasticFS::ApplyYourself(), G4ParticleHPPTInelasticFS::ApplyYourself(), G4ParticleHPTInelasticFS::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4TritonBuilder::Build(), G4TritonPHPBuilder::Build(), G4EmLivermorePolarizedPhysics::ConstructParticle(), G4EmLowEPPhysics::ConstructParticle(), G4EmPenelopePhysics::ConstructParticle(), G4EmLivermorePhysics::ConstructParticle(), G4EmStandardPhysicsSS::ConstructParticle(), PhysListEm5DStandard::ConstructParticle(), PhysListEm19DStandard::ConstructParticle(), G4EmStandardPhysicsGS::ConstructParticle(), G4EmStandardPhysics_option4_channeling::ConstructParticle(), G4EmStandardPhysics::ConstructParticle(), G4EmStandardPhysics_option3::ConstructParticle(), G4EmStandardPhysicsWVI::ConstructParticle(), G4EmStandardPhysics_option4::ConstructParticle(), G4EmStandardPhysics_option1::ConstructParticle(), G4EmStandardPhysics_option2::ConstructParticle(), G4IonPhysics::ConstructProcess(), G4IonPhysicsPHP::ConstructProcess(), G4IonINCLXXPhysics::ConstructProcess(), G4IonQMDPhysics::ConstructProcess(), GammaRayTelIonPhysics::ConstructProcess(), G4ChargeExchange::G4ChargeExchange(), G4ChargeExchangeProcess::G4ChargeExchangeProcess(), G4GeneratorPrecompoundInterface::G4GeneratorPrecompoundInterface(), G4HadronNucleonXsc::G4HadronNucleonXsc(), G4LENDManager::G4LENDManager(), G4ParticleHPData::G4ParticleHPData(), G4ParticleHPInelastic::G4ParticleHPInelastic(), G4ParticleHPInelasticData::G4ParticleHPInelasticData(), G4WilsonAblationModel::G4WilsonAblationModel(), G4NuclNuclDiffuseElastic::GetInvCoulombElasticXsc(), G4DiffuseElastic::GetInvCoulombElasticXsc(), G4NuclNuclDiffuseElastic::GetInvElasticSumXsc(), G4DiffuseElastic::GetInvElasticSumXsc(), G4NuclNuclDiffuseElastic::GetInvElasticXsc(), G4DiffuseElastic::GetInvElasticXsc(), G4ParticleHPT2AInelasticFS::Init(), G4ParticleHPD2AInelasticFS::Init(), G4ParticleHPNPInelasticFS::Init(), G4ParticleHP2NInelasticFS::Init(), G4ParticleHPPDInelasticFS::Init(), G4ParticleHPPTInelasticFS::Init(), G4ParticleHPNXInelasticFS::Init(), G4ParticleHPDAInelasticFS::Init(), G4ParticleHPN3AInelasticFS::Init(), G4ParticleHPND2AInelasticFS::Init(), G4ParticleHPNDInelasticFS::Init(), G4ParticleHPNHe3InelasticFS::Init(), G4ParticleHP2N2AInelasticFS::Init(), G4ParticleHPNTInelasticFS::Init(), G4ParticleHPTInelasticFS::Init(), G4ParticleHPNT2AInelasticFS::Init(), G4ParticleHPPAInelasticFS::Init(), G4ParticleHPNInelasticFS::Init(), G4ParticleHPPInelasticFS::Init(), G4ParticleHPNPAInelasticFS::Init(), G4ParticleHPHe3InelasticFS::Init(), G4ParticleHPN2AInelasticFS::Init(), G4ParticleHP2PInelasticFS::Init(), G4ParticleHPN2PInelasticFS::Init(), G4ParticleHP2NDInelasticFS::Init(), G4ParticleHP2NPInelasticFS::Init(), G4ParticleHP3AInelasticFS::Init(), G4ParticleHPNAInelasticFS::Init(), G4ParticleHP2NAInelasticFS::Init(), G4ParticleHPDInelasticFS::Init(), G4ParticleHP3NPInelasticFS::Init(), G4ParticleHP2AInelasticFS::Init(), G4ParticleHPAInelasticFS::Init(), G4ParticleHP3NInelasticFS::Init(), G4ParticleHP4NInelasticFS::Init(), G4ParticleHP3NAInelasticFS::Init(), G4ParticleHPIsoData::Init(), G4RPGReaction::NuclearReaction(), G4ParticleHPIsotropic::Sample(), G4ParticleHPNBodyPhaseSpace::Sample(), G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContAngularPar::Sample(), G4AntiNuclElastic::SampleInvariantT(), G4QuasiElRatios::Scatter(), G4WilsonAblationModel::SelectSecondariesByEvaporation(), G4AblaInterface::toG4ParticleDefinition(), G4INCLXXInterface::toG4ParticleDefinition(), and G4INCLXXInterface::toINCLParticleType().
TritonDefinition()
G4Triton * G4Triton::TritonDefinition () static
Definition at line 89 of file G4Triton.cc.
Referenced by G4ExcitationHandler::BreakItUp(), G4IonConstructor::ConstructLightIons(), GammaKnifeParticles::ConstructParticle(), GammaRayTelParticles::ConstructParticle(), PhysicsList::ConstructParticle(), G4Scintillation::GetScintillationYieldByParticleType(), and G4BinaryCascade::HighEnergyModelFSProducts().
Field Documentation
theInstance
G4Triton * G4Triton::theInstance = 0 static private
Definition at line 53 of file G4Triton.hh.
Referenced by Definition().
The documentation for this class was generated from the following files:
source/particles/hadrons/ions/include/G4Triton.hh
source/particles/hadrons/ions/src/G4Triton.cc