Geant4: G4ErrorTarget Class Reference
G4ErrorTarget Class Reference abstract
#include <G4ErrorTarget.hh>
Public Member Functions
G4ErrorTarget ()
virtual ~G4ErrorTarget ()
virtual G4double GetDistanceFromPoint (const G4ThreeVector &, const G4ThreeVector &) const
virtual G4double GetDistanceFromPoint (const G4ThreeVector &) const
virtual G4bool TargetReached (const G4Step *)
virtual void Dump (const G4String &msg) const =0
G4ErrorTargetType GetType () const
Protected Attributes
G4ErrorTargetType theType
Detailed Description
Definition at line 53 of file G4ErrorTarget.hh.
Constructor & Destructor Documentation
G4ErrorTarget()
G4ErrorTarget::G4ErrorTarget ()
Definition at line 35 of file G4ErrorTarget.cc.
~G4ErrorTarget()
G4ErrorTarget::~G4ErrorTarget () virtual
Definition at line 38 of file G4ErrorTarget.cc.
Member Function Documentation
Dump()
virtual void G4ErrorTarget::Dump (const G4String & msg) const pure virtual
Implemented in G4ErrorSurfaceTarget, G4ErrorTanPlaneTarget, G4ErrorTrackLengthTarget, G4ErrorCylSurfaceTarget, G4ErrorPlaneSurfaceTarget, and G4ErrorGeomVolumeTarget.
Referenced by G4ErrorPropagationNavigator::ComputeStep(), and G4ErrorPropagator::Propagate().
GetDistanceFromPoint() [1/2]
G4double G4ErrorTarget::GetDistanceFromPoint (const G4ThreeVector &) const virtual
Reimplemented in G4ErrorPlaneSurfaceTarget, G4ErrorSurfaceTarget, G4ErrorCylSurfaceTarget, and G4ErrorTrackLengthTarget.
Definition at line 46 of file G4ErrorTarget.cc.
GetDistanceFromPoint() [2/2]
G4double G4ErrorTarget::GetDistanceFromPoint (const G4ThreeVector & , const G4ThreeVector &) const virtual
Reimplemented in G4ErrorSurfaceTarget, G4ErrorPlaneSurfaceTarget, G4ErrorCylSurfaceTarget, and G4ErrorTrackLengthTarget.
Definition at line 40 of file G4ErrorTarget.cc.
Referenced by G4ErrorPropagationNavigator::ComputeStep(), G4ErrorPropagationNavigator::GetGlobalExitNormal(), and G4ErrorPropagationNavigator::TargetSafetyFromPoint().
GetType()
G4ErrorTargetType G4ErrorTarget::GetType () const inline
Definition at line 81 of file G4ErrorTarget.hh.
Referenced by G4ErrorPropagator::GetFinalTrajState(), G4ErrorPropagationNavigator::GetGlobalExitNormal(), and G4ErrorPropagator::MakeOneStep().
TargetReached()
G4bool G4ErrorTarget::TargetReached (const G4Step *) virtual
Reimplemented in G4ErrorGeomVolumeTarget.
Definition at line 51 of file G4ErrorTarget.cc.
Field Documentation
theType
G4ErrorTargetType G4ErrorTarget::theType protected
Definition at line 76 of file G4ErrorTarget.hh.
Referenced by G4ErrorCylSurfaceTarget::G4ErrorCylSurfaceTarget(), G4ErrorGeomVolumeTarget::G4ErrorGeomVolumeTarget(), G4ErrorPlaneSurfaceTarget::G4ErrorPlaneSurfaceTarget(), G4ErrorTrackLengthTarget::G4ErrorTrackLengthTarget(), and GetType().
The documentation for this class was generated from the following files:
source/geometry/management/include/G4ErrorTarget.hh
source/geometry/management/src/G4ErrorTarget.cc