Geant4: G4INCL::Math Namespace Reference
G4INCL::Math Namespace Reference
Functions
G4double toDegrees (G4double radians)
G4int heaviside (G4int n)
G4double pow13 (G4double x)
G4double powMinus13 (G4double x)
G4double pow23 (G4double x)
G4double aSinH (G4double x)
template<typename T >
G4int sign (const T t)
A simple sign function that allows us to port fortran code to c++ more easily.
template<typename T >
T max (const T t1, const T t2)
brief Return the largest of the two arguments
template<typename T >
T min (const T t1, const T t2)
brief Return the smallest of the two arguments
G4double gaussianCDF (const G4double x)
Cumulative distribution function for Gaussian.
G4double gaussianCDF (const G4double x, const G4double x0, const G4double sigma)
Generic cumulative distribution function for Gaussian.
G4double inverseGaussianCDF (const G4double x)
Inverse cumulative distribution function for Gaussian.
G4double arcSin (const G4double x)
Calculates arcsin with some tolerance on illegal arguments.
G4double arcCos (const G4double x)
Calculates arccos with some tolerance on illegal arguments.
Variables
const G4double pi = 3.14159265358979323846264338328
const G4double twoPi = 2.0 * pi
const G4double tenPi = 10.0 * pi
const G4double piOverTwo = 0.5 * pi
const G4double oneOverSqrtTwo = 1./std::sqrt((G4double)2.)
const G4double oneOverSqrtThree = 1./std::sqrt((G4double)3.)
const G4double oneThird = 1./3.
const G4double twoThirds = 2./3.
const G4double sqrtFiveThirds = std::sqrt(5./3.)
const G4double sqrtThreeFifths = std::sqrt(3./5.)
Function Documentation
arcCos()
G4double G4INCL::Math::arcCos (const G4double x)
Calculates arccos with some tolerance on illegal arguments.
Definition at line 103 of file G4INCLGlobals.cc.
Referenced by G4INCL::CoulombNonRelativistic::coulombDeviation(), G4INCL::CoulombNonRelativistic::distortOut(), G4INCL::EventInfo::fillInverseKinematics(), G4INCL::SurfaceAvatar::getTransmissionProbability(), and G4INCL::EventInfo::remnantToParticle().
arcSin()
G4double G4INCL::Math::arcSin (const G4double x)
Calculates arcsin with some tolerance on illegal arguments.
Definition at line 98 of file G4INCLGlobals.cc.
aSinH()
G4double G4INCL::Math::aSinH (G4double x) inline
Definition at line 100 of file G4INCLGlobals.hh.
gaussianCDF() [1/2]
G4double G4INCL::Math::gaussianCDF (const G4double x)
Cumulative distribution function for Gaussian.
A public-domain approximation taken from Abramowitz and Stegun. Applies to a Gaussian with mean=0 and sigma=1.
Parameters
x a Gaussian variable
Definition at line 74 of file G4INCLGlobals.cc.
Referenced by G4INCL::Random::correlatedUniform(), and gaussianCDF().
gaussianCDF() [2/2]
G4double G4INCL::Math::gaussianCDF (const G4double x, const G4double x0, const G4double sigma)
Generic cumulative distribution function for Gaussian.
A public-domain approximation taken from Abramowitz and Stegun. Applies to a generic Gaussian.
Parameters
x a Gaussian variable
x0 mean of the Gaussian
sigma standard deviation of the Gaussian
Definition at line 87 of file G4INCLGlobals.cc.
heaviside()
G4int G4INCL::Math::heaviside (G4int n) inline
Definition at line 83 of file G4INCLGlobals.hh.
Referenced by G4INCL::Nucleus::insertParticle().
inverseGaussianCDF()
G4double G4INCL::Math::inverseGaussianCDF (const G4double x)
Inverse cumulative distribution function for Gaussian.
A public-domain approximation taken from Abramowitz and Stegun. Applies to a Gaussian with mean=0 and sigma=1.
Parameters
x a uniform variate
Returns
a Gaussian variate
Definition at line 91 of file G4INCLGlobals.cc.
max()
template<typename T > T G4INCL::Math::max (const T t1, const T t2) inline
brief Return the largest of the two arguments
Definition at line 112 of file G4INCLGlobals.hh.
Referenced by field_utils::absoluteError(), G4GHEKinematicsVector::Add(), G4RPGReaction::AddBlackTrackParticles(), G4PenelopeCrossSection::AddCrossSectionPoint(), G4UPiNuclearCrossSection::AddDataSet(), G4INCL::ProjectileRemnant::addMostDynamicalSpectators(), G4PenelopeCrossSection::AddShellCrossSectionPoint(), G4SolidExtentList::AddSurface(), G4ParticleHPFinalState::adjust_final_state(), G4NavigationLogger::AlongComputeStepLog(), G4Transportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepDoIt(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4PreCompoundEmission::AngularDistribution(), G4Nucleus::AnnihilationEvaporationEffects(), G4ParticleHPCapture::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4ChordFinder::ApproxCurvePointV(), G4ExtrudedSolid::ApproxSurfaceNormal(), G4RDeIonisationSpectrum::AverageEnergy(), G4eIonisationSpectrum::AverageEnergy(), G4RDeBremsstrahlungSpectrum::AverageEnergy(), G4eBremsstrahlungSpectrum::AverageEnergy(), G4EnergyLossForExtrapolator::AverageScatteringAngle(), G4RDeIonisationSpectrum::AverageValue(), G4eIonisationSpectrum::AverageValue(), G4RDeBremsstrahlungSpectrum::AverageValue(), G4eBremsstrahlungSpectrum::AverageValue(), G4HadronBuilder::Barion(), G4ClippablePolygon::BehindOf(), G4AtimaEnergyLossModel::Bethek_dedx_e(), G4UnionSolid::BoundingLimits(), G4IntersectionSolid::BoundingLimits(), G4Ellipsoid::BoundingLimits(), G4CutTubs::BoundingLimits(), G4Trd::BoundingLimits(), G4Para::BoundingLimits(), G4Cons::BoundingLimits(), G4ExtrudedSolid::BoundingLimits(), G4Sphere::BoundingLimits(), G4WilsonAblationModel::BreakItUp(), G4UnstableFragmentBreakUp::BreakUpChain(), G4Voxelizer::BuildBitmasks(), G4Voxelizer::BuildBoundaries(), G4Voxelizer::BuildBoundingBox(), G4AdjointCSManager::BuildCrossSectionsMatricesForAGivenModelAndElement(), G4AdjointCSManager::BuildCrossSectionsMatricesForAGivenModelAndMaterial(), G4PenelopeIonisationXSHandler::BuildDeltaTable(), G4Voxelizer::BuildEmpty(), G4VEnergyLossProcess::BuildLambdaTable(), G4VEmProcess::BuildLambdaTable(), G4hImpactIonisation::BuildPhysicsTable(), G4Voxelizer::BuildReduceVoxels(), G4Voxelizer::BuildReduceVoxels2(), G4SBBremTable::BuildSamplingTables(), DicomFileCT::BuildStructureIDs(), G4LossTableBuilder::BuildTableForModel(), G4Voxelizer::BuildVoxelLimits(), G4BulirschStoer::calc_h_opt(), G4ConvergenceTester::calc_slope_fit(), G4StatMFMicroCanonical::CalcEntropyOfCompoundNucleus(), G4StatMFMacroMultiNucleon::CalcMeanMultiplicity(), G4StatMFMicroPartition::CalcPartitionProbability(), G4StatMFMicroPartition::CalcPartitionTemperature(), G4StatMFMacroTemperature::CalcTemperature(), G4WeightWindowAlgorithm::Calculate(), G4VCSGfaceted::CalculateExtent(), G4UnionSolid::CalculateExtent(), G4IntersectionSolid::CalculateExtent(), G4RPGInelastic::CalculateMomenta(), G4PreCompoundTransitions::CalculateProbability(), G4SteppingManager::CalculateSafety(), G4ITStepProcessor::CalculateSafety(), G4StatMFMacroCanonical::CalculateTemperature(), G4RPGKMinusInelastic::Cascade(), G4RPGAntiLambdaInelastic::Cascade(), G4RPGAntiProtonInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGSigmaPlusInelastic::Cascade(), G4RPGXiMinusInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4RPGAntiOmegaMinusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGOmegaMinusInelastic::Cascade(), G4RPGKPlusInelastic::Cascade(), G4RPGLambdaInelastic::Cascade(), G4RPGKZeroInelastic::Cascade(), G4RPGSigmaMinusInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), G4RPGAntiKZeroInelastic::Cascade(), G4BoundingEnvelope::CheckBoundingPolygons(), G4MolecularDissociationTable::CheckDataConsistency(), G4GeomTools::CheckSnip(), G4DiffractiveSplitableHadron::ChooseStringEnds(), G4Nucleus::Cinema(), G4BoundingEnvelope::ClipEdgesByVoxel(), G4BoundingEnvelope::ClipVoxelByPlanes(), G4VEmAdjointModel::ComputeAdjointCrossSectionVectorPerAtomForScatProj(), G4VEmAdjointModel::ComputeAdjointCrossSectionVectorPerVolumeForScatProj(), XrayFluoMercuryDetectorConstruction::ComputeApparateParameters(), XrayFluoPlaneDetectorConstruction::ComputeApparateParameters(), XrayFluoDetectorConstruction::ComputeApparateParameters(), G4eBremsstrahlungRelModel::ComputeBremLoss(), G4ChatterjeeCrossSection::ComputeCrossSection(), G4KalbachCrossSection::ComputeCrossSection(), G4BoldyshevTripletModel::ComputeCrossSectionPerAtom(), G4LivermoreGammaConversionModel::ComputeCrossSectionPerAtom(), G4KleinNishinaCompton::ComputeCrossSectionPerAtom(), G4KleinNishinaModel::ComputeCrossSectionPerAtom(), G4LDMBremModel::ComputeCrossSectionPerAtom(), G4BetheHeitlerModel::ComputeCrossSectionPerAtom(), G4eBremsstrahlungRelModel::ComputeCrossSectionPerAtom(), G4PairProductionRelModel::ComputeCrossSectionPerAtom(), G4MuPairProductionModel::ComputeCrossSectionPerAtom(), G4EmCalculator::ComputeCrossSectionPerAtom(), G4eplusTo3GammaOKVIModel::ComputeCrossSectionPerElectron(), G4eplusTo2GammaOKVIModel::ComputeCrossSectionPerElectron(), G4eeToTwoGammaModel::ComputeCrossSectionPerElectron(), G4mplIonisationWithDeltaModel::ComputeCrossSectionPerElectron(), G4MuBetheBlochModel::ComputeCrossSectionPerElectron(), G4PenelopeAnnihilationModel::ComputeCrossSectionPerElectron(), G4EmCalculator::ComputeCrossSectionPerShell(), G4EmCalculator::ComputeCrossSectionPerVolume(), G4ComponentBarNucleonNucleusXsc::ComputeCrossSections(), G4ComponentGGHadronNucleusXsc::ComputeCrossSections(), G4ComponentGGNuclNuclXsc::ComputeCrossSections(), G4mplIonisationWithDeltaModel::ComputeDEDXAhlen(), G4mplIonisationWithDeltaModel::ComputeDEDXPerVolume(), G4eBremsstrahlungRelModel::ComputeDEDXPerVolume(), G4AtimaEnergyLossModel::ComputeDEDXPerVolume(), G4MuPairProductionModel::ComputeDEDXPerVolume(), G4MollerBhabhaModel::ComputeDEDXPerVolume(), G4LindhardSorensenIonModel::ComputeDEDXPerVolume(), G4BetheBlochModel::ComputeDEDXPerVolume(), G4BraggIonModel::ComputeDEDXPerVolume(), G4BraggModel::ComputeDEDXPerVolume(), G4LDMBremModel::ComputeDMicroscopicCrossSection(), G4MuPairProductionModel::ComputeDMicroscopicCrossSection(), G4SeltzerBergerModel::ComputeDXSectionPerAtom(), G4eBremsstrahlungRelModel::ComputeDXSectionPerAtom(), G4PairProductionRelModel::ComputeDXSectionPerAtom(), G4WentzelOKandVIxSection::ComputeElectronCrossSection(), G4eplusTo3GammaOKVIModel::ComputeF(), G4eplusTo3GammaOKVIModel::ComputeFS(), DetectorConstruction::ComputeGeomParameters(), G4UrbanMscModel::ComputeGeomPathLength(), G4UrbanAdjointMscModel::ComputeGeomPathLength(), G4GoudsmitSaundersonMscModel::ComputeGeomPathLength(), GFlashSamplingShowerParameterisation::ComputeLongitudinalParameters(), G4SandiaTable::ComputeMatSandiaMatrix(), G4KokoulinMuonNuclearXS::ComputeMicroscopicCrossSection(), G4MuPairProductionModel::ComputeMicroscopicCrossSection(), PDBlib::ComputeNucleotideBarycenters(), G4eBremParametrizedModel::ComputeParametrizedDXSectionPerAtom(), G4ComponentGGHadronNucleusXsc::ComputeQuasiElasticRatio(), G4eBremsstrahlungRelModel::ComputeRelDXSectionPerAtom(), G4PairProductionRelModel::ComputeRelDXSectionPerAtom(), G4PenelopeIonisationXSHandler::ComputeShellCrossSectionsElectron(), G4PenelopeIonisationXSHandler::ComputeShellCrossSectionsPositron(), G4PathFinder::ComputeStep(), G4PropagatorInField::ComputeStep(), G4WentzelOKandVIxSection::ComputeTransportCrossSectionPerAtom(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTruePathLengthLimit(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), G4eBremsstrahlungRelModel::ComputeXSectionPerAtom(), G4PairProductionRelModel::ComputeXSectionPerAtom(), G4MuPairProductionModel::ComputMuPairLoss(), G4MonopolePhysics::ConstructProcess(), G4EmExtraPhysics::ConstructProcess(), G4ConversionUtils::Convert(), G4BinaryCascade::CorrectFinalPandE(), G4BetheBlochModel::CorrectionsAlongStep(), G4VLongitudinalStringDecay::CreatePartonPair(), G4TwistedTubs::CreatePolyhedron(), G4TessellatedSolid::CreateVertexList(), G4XPDGElastic::CrossSection(), G4PEEffectFluoModel::CrossSectionPerVolume(), G4PAIModelData::CrossSectionPerVolume(), G4VEmProcess::CrossSectionPerVolume(), G4VEnergyLossProcess::CrossSectionPerVolume(), MuCrossSections::CRP_Mephi(), G4FermiPhaseSpaceDecay::Decay(), G4ICRU73QOModel::DEDXPerElement(), G4PAIModelData::DEDXPerVolume(), G4BinaryLightIonReaction::DeExciteSpectatorNucleus(), G4FissionParameters::DefineParameters(), G4hImpactIonisation::DeltaRaysEnergy(), G4INCL::DeuteronDensity::derivWavefunctionR(), G4MagneticFieldModel::DescribeYourselfTo(), G4PenelopeComptonModel::DifferentialCrossSection(), G4QGSMSplitableHadron::DiffractiveSplitUp(), G4PAIySection::DifPAIySection(), G4DiffractiveSplitableHadron::Diquark(), G4QGSMFragmentation::DiQuarkSplitup(), G4LundStringFragmentation::DiQuarkSplitup(), G4GeomTools::DiskExtent(), G4AtimaFluctuations::Dispersion(), G4PolyconeSide::DistanceAway(), G4EllipticalTube::DistanceToIn(), G4Tet::DistanceToIn(), G4Box::DistanceToIn(), G4CutTubs::DistanceToIn(), G4EllipticalCone::DistanceToIn(), G4ExtrudedSolid::DistanceToIn(), G4Trd::DistanceToIn(), G4Para::DistanceToIn(), G4Torus::DistanceToIn(), G4Trap::DistanceToIn(), G4EllipticalTube::DistanceToOut(), G4Tet::DistanceToOut(), G4UnionSolid::DistanceToOut(), G4ExtrudedSolid::DistanceToOut(), G4Trd::DistanceToOut(), G4Para::DistanceToOut(), G4Trap::DistanceToOut(), G4PathFinder::DoNextLinearStep(), G4ITPathFinder::DoNextLinearStep(), G4ITStepProcessor::DoStepping(), G4ScoreLogColorMap::DrawColorChartBar(), G4VScoreColorMap::DrawColorChartBar(), G4ScoreLogColorMap::DrawColorChartText(), G4VScoreColorMap::DrawColorChartText(), G4FermiFragmentsPoolVI::Dump(), G4EmModelManager::DumpModelList(), G4ionEffectiveCharge::EffectiveCharge(), G4PiData::ElasticXSection(), GFlashShowerModel::ElectronDoIt(), G4hImpactIonisation::ElectronicLossFluctuation(), G4BraggModel::ElectronicStoppingPower(), G4BraggIonModel::ElectronicStoppingPower(), G4GeomTools::EllipsePerimeter(), G4GeomTools::EllipticConeLateralArea(), Run::EndOfEvent(), ExGflashEventAction::EndOfEventAction(), G4BinaryLightIonReaction::EnergyAndMomentumCorrector(), G4AtimaFluctuations::EnergyTable_interpolate(), G4AtimaEnergyLossModel::EnergyTable_interpolate(), G4MultiLevelLocator::EstimateIntersectionPoint(), G4Nucleus::EvaporationEffects(), G4RDeIonisationParameters::Excitation(), G4eIonisationParameters::Excitation(), G4MultiUnion::Extent(), G4PolyPhiFace::Extent(), G4VCrossSectionSource::FcrossX(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::ElasticChannel::fillFinalState(), G4INCL::EventInfo::fillInverseKinematics(), G4HadronicProcess::FillResult(), G4NuclearLevelData::FindLevel(), G4JTPolynomialSolver::FindRoots(), G4BoundingEnvelope::FindScaleFactor(), G4StatMF::FindTemperatureOfBreakingChannel(), G4CompetitiveFission::FissionAtomicNumber(), G4CompetitiveFission::FissionKineticEnergy(), G4RPGFragmentation::FragmentationIntegral(), G4ArrowModel::G4ArrowModel(), G4BogackiShampine45::G4BogackiShampine45(), G4CashKarpRKF45::G4CashKarpRKF45(), G4ClassicalRK4::G4ClassicalRK4(), G4DormandPrince745::G4DormandPrince745(), G4DormandPrinceRK56::G4DormandPrinceRK56(), G4DormandPrinceRK78::G4DormandPrinceRK78(), G4FSALBogackiShampine45::G4FSALBogackiShampine45(), G4GDecay3::G4GDecay3(), G4ImplicitEuler::G4ImplicitEuler(), G4IntersectingCone::G4IntersectingCone(), G4MuPairProductionModel::G4MuPairProductionModel(), G4PAIModelData::G4PAIModelData(), G4PAIPhotData::G4PAIPhotData(), G4Para::G4Para(), G4ParticleHPPartial::G4ParticleHPPartial(), G4ParticleHPVector::G4ParticleHPVector(), G4PropagatorInField::G4PropagatorInField(), G4QuadrangularFacet::G4QuadrangularFacet(), G4RandomPointOnEllipse(), G4RandomPointOnEllipsoid(), G4SimpleRunge::G4SimpleRunge(), G4Sphere::G4Sphere(), G4Tet::G4Tet(), G4TriangularFacet::G4TriangularFacet(), G4TsitourasRK45::G4TsitourasRK45(), G4INCL::PhaseSpaceRauboldLynch::generate(), G4eeToHadronsModel::GenerateCMPhoton(), GFlashSamplingShowerParameterisation::GenerateEnergyProfile(), G4Clebsch::GenerateIso3(), G4RPGReaction::GenerateNBodyEvent(), G4RPGReaction::GenerateNBodyEventT(), GFlashSamplingShowerParameterisation::GenerateNSpotProfile(), G4HadronCrossSections::GetCaptureCrossSection(), G4BCLateParticle::GetCollisions(), G4VXTRenergyLoss::GetComptonPerAtom(), G4ContinuousGainOfEnergy::GetContinuousStepLimit(), G4ParticleHPFissionData::GetCrossSection(), G4ParticleHPCaptureData::GetCrossSection(), G4ParticleHPElasticData::GetCrossSection(), G4ParticleHPInelasticData::GetCrossSection(), G4HadronicProcess::GetElementCrossSection(), G4EvaporationChannel::GetEmissionProbability(), G4PhotonEvaporation::GetEmissionProbability(), G4SolidExtentList::GetExtent(), G4ClippablePolygon::GetExtent(), G4HadronCrossSections::GetFissionCrossSection(), G4ComponentGGHadronNucleusXsc::GetHNinelasticXsc(), G4ComponentGGHadronNucleusXsc::GetHNinelasticXscVU(), G4BGGPionElasticXS::GetIsoCrossSection(), G4BGGNucleonElasticXS::GetIsoCrossSection(), G4INCL::ParticleTable::getLargestNuclearRadius(), G4RDVeLowEnergyLoss::GetLossWithFluct(), G4CutTubs::GetMaxMinZ(), G4ClippablePolygon::GetMaxPoint(), G4ScreenedNuclearRecoil::GetMeanFreePath(), G4Accumulables::GetMergeFunction(), G4PenelopeBremsstrahlungFS::GetMomentumIntegral(), G4MuonMinusBoundDecay::GetMuonZeff(), G4RPGInelastic::GetNormalizationConstant(), G4PairingCorrection::GetPairingCorrection(), G4ComponentGGHadronNucleusXsc::GetParticleBarCorIn(), G4ComponentGGHadronNucleusXsc::GetParticleBarCorTot(), G4VMscModel::GetParticleChangeForMSC(), G4ClippablePolygon::GetPlanerExtent(), G4EllipticalCone::GetPointOnSurface(), G4TrajectoryDrawerUtils::GetPointsAndTimes(), G4ITNavigator2::GetRandomInCurrentVolume(), G4ComponentGGHadronNucleusXsc::GetRatioQE(), G4ParticleHPIsoData::GetXsec(), G4ParticleHPChannelList::GetXsec(), G4ParticleHPFissionBaseFS::GetXsec(), G4ParticleHPInelasticBaseFS::GetXsec(), G4ParticleHPInelasticCompFS::GetXsec(), G4ParticleHPChannel::GetXsec(), G4HadronNucleonXsc::HadronNucleonXscNS(), G4ParticleHPElementData::Harmonise(), G4ParticleHPChannel::Harmonise(), G4VhElectronicStoppingPower::HeEffChargeSquare(), G4BraggIonModel::HeEffChargeSquare(), G4ParticleHPContAngularPar::Init(), G4PenelopeBremsstrahlungModel::Initialise(), G4WentzelVIModel::Initialise(), G4FermiFragmentsPoolVI::Initialise(), G4PenelopeIonisationModel::Initialise(), G4SeltzerBergerModel::Initialise(), G4MuPairProductionModel::Initialise(), G4HadronXSDataTable::Initialise(), G4EmModelManager::Initialise(), G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), G4VEmModel::InitialiseElementSelectors(), G4ePairProduction::InitialiseEnergyLossProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), G4MuPairProduction::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), DetectorConstruction::InitialiseGeometryParameters(), G4LivermoreGammaConversionModel::InitialiseProbability(), G4CoulombScattering::InitialiseProcess(), G4PolarizedGammaConversion::InitialiseProcess(), G4GammaGeneralProcess::InitialiseProcess(), G4GammaConversion::InitialiseProcess(), G4FastPathHadronicCrossSection::fastPathEntry::Initialize(), G4INCL::NuclearPotential::NuclearPotentialIsospin::initialize(), G4Orb::Initialize(), G4PenelopeBremsstrahlungFS::InitializeEnergySampling(), G4PenelopeRayleighModel::InitializeSamplingAlgorithm(), G4INCL::INCL::initMaxInteractionDistance(), G4SBBremTable::InitSamplingTables(), G4GoudsmitSaundersonTable::InitSCPCorrection(), G4INCL::INCL::initUniverseRadius(), G4EllipticalTube::Inside(), G4UnionSolid::Inside(), G4Box::Inside(), G4EllipticalCone::Inside(), G4Trd::Inside(), G4ExtrudedSolid::Inside(), G4Para::Inside(), G4Sphere::Inside(), G4Trap::Inside(), G4KineticTrack::IntegrandFunction1(), G4KineticTrack::IntegrandFunction2(), G4INCL::IFunction1D::integrate(), G4GEMChannelVI::IntegratedProbability(), G4HETCFragment::IntegrateEmissionProbability(), G4PreCompoundFragment::IntegrateEmissionProbability(), G4INCL::CrossSections::interactionDistanceKbarN(), G4INCL::CrossSections::interactionDistanceKN(), G4INCL::CrossSections::interactionDistanceNN(), G4INCL::CrossSections::interactionDistancePiN(), G4INCL::CrossSections::interactionDistanceYN(), G4UCNMicroRoughnessHelper::IntIminus(), G4UCNMicroRoughnessHelper::IntIplus(), G4eIonisationSpectrum::IntSpectrum(), G4RDeIonisationSpectrum::IntSpectrum(), G4eBremsstrahlungSpectrum::IntSpectrum(), G4RDeBremsstrahlungSpectrum::IntSpectrum(), G4hIonEffChargeSquare::IonEffChargeSquare(), G4ExtrudedSolid::IsSameLineSegment(), G4HETCProton::K(), G4HETCHe3::K(), G4HETCTriton::K(), G4HETCAlpha::K(), G4HETCDeuteron::K(), G4HETCNeutron::K(), G4INCL::NpiToSKChannel::KaonMomentum(), G4INCL::NKbToSpiChannel::KaonMomentum(), G4HadronNucleonXsc::KaonNucleonXscVG(), G4LevelReader::LevelManager(), G4IntersectingCone::LineHitsCone1(), G4IntersectingCone::LineHitsCone2(), G4AttValueFilterT< T, ConversionErrorPolicy >::LoadIntervalElement(), G4SBBremTable::LoadSamplingTables(), G4SBBremTable::LoadSTGrid(), G4GHEKinematicsVector::Lor(), G4Trap::MakePlane(), G4INCL::Random::Adapter::max(), MCGIDI_particle_getInternalID(), MCGIDI_POPs_findParticleIndex(), G4hCoulombScatteringModel::MinPrimaryEnergy(), G4eBremsstrahlungRelModel::MinPrimaryEnergy(), G4MuPairProductionModel::MinPrimaryEnergy(), G4eCoulombScatteringModel::MinPrimaryEnergy(), G4MuBremsstrahlungModel::MinPrimaryEnergy(), G4RPGReaction::NuclearReaction(), G4ICRU49NuclearStoppingModel::NuclearStoppingPower(), G4MagInt_Driver::OneGoodStep(), G4INCL::NuclearDensityFunctions::ModifiedHarmonicOscillatorRP::operator()(), DicomVFileImage::operator+(), DicomPhantomZSliceHeader::operator+(), operator<<(), G4PenelopeComptonModel::OscillatorTotalCrossSection(), G4PAIySection::PAIdNdxPlasmon(), G4eIonisationParameters::Parameter(), G4RDeIonisationParameters::Parameter(), G4BremsstrahlungParameters::Parameter(), G4RDBremsstrahlungParameters::Parameter(), G4INCL::ParticleEntryChannel::particleEnters(), G4PreCompoundEmission::PerformEmission(), G4PhotoElectricAngularGeneratorPolarized::PhotoElectronGetMajorantSurfaceAandCParameters(), G4Vee2hadrons::PhysicsVector(), G4RPGInelastic::Pmltpc(), G4RDGenerator2BS::PolarAngle(), G4DipBustGenerator::PolarAngle(), G4LowEnergyGammaConversion::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4eplusPolarizedAnnihilation::PostStepGetPhysicalInteractionLength(), G4ePolarizedIonisation::PostStepGetPhysicalInteractionLength(), G4PolarizedCompton::PostStepGetPhysicalInteractionLength(), G4GammaGeneralProcess::PostStepGetPhysicalInteractionLength(), G4VEmProcess::PostStepGetPhysicalInteractionLength(), G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength(), G4RDeBremsstrahlungSpectrum::Probability(), G4eBremsstrahlungSpectrum::Probability(), G4eIonisationSpectrum::Probability(), G4RDeIonisationSpectrum::Probability(), G4PreCompoundIon::ProbabilityDistributionFunction(), G4GEMChannelVI::ProbabilityDistributionFunction(), G4UrbanMscModel::Randomizetlimit(), G4RPGStrangeProduction::ReactionStage(), G4RPGTwoBody::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4PiData::ReactionXSection(), G4RPGFragmentation::ReduceEnergiesOfSecondaries(), field_utils::relativeError2(), G4PathFinder::ReLocate(), G4ITPathFinder::ReLocate(), G4GeomTools::RemoveRedundantVertices(), G4NavigationLogger::ReportOutsideMother(), CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::ResampleTrackLengthInTarget(), G4StatDouble::rms(), G4RPGReaction::Rotate(), G4VoxelSafety::SafetyForVoxelHeader(), G4ParticleHPIsotropic::Sample(), G4ParticleHPKallbachMannSyst::Sample(), G4ParticleHPFissionSpectrum::Sample(), G4ParticleHPNBodyPhaseSpace::Sample(), G4ParticleHPSimpleEvapSpectrum::Sample(), G4ParticleHPWattSpectrum::Sample(), G4ParticleHPLegendreStore::Sample(), G4ParticleHPContAngularPar::Sample(), G4ParticleHPVector::Sample(), G4VEmAdjointModel::SampleAdjSecEnergyFromCSMatrix(), G4UrbanMscModel::SampleCosineTheta(), G4DipBustGenerator::SampleCosTheta(), G4SauterGavrilaAngularDistribution::SampleDirection(), G4Generator2BN::SampleDirection(), G4PenelopeBremsstrahlungAngular::SampleDirection(), G4Generator2BS::SampleDirection(), G4ParticleHPLegendreStore::SampleDiscreteTwoBody(), G4ParticleHPLegendreStore::SampleElastic(), G4VEmissionProbability::SampleEnergy(), G4eIonisationSpectrum::SampleEnergy(), G4RDeIonisationSpectrum::SampleEnergy(), G4eBremsstrahlungSpectrum::SampleEnergy(), G4RDeBremsstrahlungSpectrum::SampleEnergy(), G4SBBremTable::SampleEnergyTransfer(), G4SeltzerBergerModel::SampleEnergyTransfer(), G4PenelopeIonisationModel::SampleFinalStateElectron(), G4PenelopeIonisationModel::SampleFinalStatePositron(), G4PenelopeBremsstrahlungFS::SampleGammaEnergy(), G4HETCChargedFragment::SampleKineticEnergy(), G4HETCNeutron::SampleKineticEnergy(), G4EvaporationProbability::SampleKineticEnergy(), G4SampleResonance::SampleMass(), G4ParticleHPLegendreStore::SampleMax(), G4PAIModelData::SamplePostStepTransfer(), G4VScatteringCollision::SampleResonanceMass(), G4LEPTSIonisationModel::SampleSecondaries(), G4BoldyshevTripletModel::SampleSecondaries(), G4LivermoreGammaConversionModelRC::SampleSecondaries(), G4LivermoreNuclearGammaConversionModel::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4PenelopeAnnihilationModel::SampleSecondaries(), G4PenelopeGammaConversionModel::SampleSecondaries(), G4JAEAElasticScatteringModel::SampleSecondaries(), G4LDMBremModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), G4BetheHeitlerModel::SampleSecondaries(), G4eplusTo2GammaOKVIModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4PairProductionRelModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4MuPairProductionModel::SampleSecondaries(), G4eCoulombScatteringModel::SampleSecondaries(), G4WentzelOKandVIxSection::SampleSingleScattering(), G4GammaTransition::SampleTransition(), G4GoudsmitSaundersonTable::Sampling(), G4ParticleHPInelasticCompFS::SelectExitChannel(), G4Torus::SetAllParameters(), G4TessellatedSolid::SetAllUsingStack(), G4RadioactiveDecayBase::SetDecayHalfAngle(), G4RadioactiveDecay::SetDecayHalfAngle(), G4FieldManager::SetDetectorField(), G4ScreeningMottCrossSection::SetDifferentialXSection(), G4GeomTestVolume::SetErrorsThreshold(), G4EmConfigurator::SetExtraEmModel(), G4GHEKinematicsVector::SetMassAndUpdate(), G4BuffercoutDestination::SetMaxSize(), G4Voxelizer::SetMaxVoxels(), G4TessellatedSolid::SetMaxVoxels(), G4KDTree::HyperRect::SetMinMax(), G4GHEKinematicsVector::SetMomentumAndUpdate(), CexmcProductionModelMessenger::SetNewValue(), CexmcEnergyDepositDigitizerMessenger::SetNewValue(), G4mplIonisationModel::SetParticle(), G4mplIonisationWithDeltaModel::SetParticle(), G3Division::SetRangeAndAxis(), G4TransportationLogger::SetThresholdTrials(), G4WentzelVIRelXSection::SetupKinematic(), G4WentzelOKandVIxSection::SetupKinematic(), G4AtimaEnergyLossModel::sezi_dedx_e(), G4LatticeReader::SkipComments(), G4TrajectoryDrawerUtils::SliceLine(), G4RPGNeutronInelastic::SlowNeutron(), G4GeomTools::SphereExtent(), G4MesonSplitter::SplitMeson(), G4SteppingManager::Stepping(), G4BraggModel::StoppingPower(), G4BraggIonModel::StoppingPower(), G4QGSDiffractiveExcitation::String(), G4GHEKinematicsVector::Sub(), G4Torus::SurfaceNormal(), G4EvaporationProbability::TotalProbability(), G4PiData::TotalXSection(), G4MultiUnion::TransformLimits(), G4Voxelizer::TransformLimits(), G4BulirschStoer::try_step(), G4DiffractiveExcitation::UnpackMeson(), G4EmConfigurator::UpdateModelEnergyRange(), CCalSteppingAction::UserSteppingAction(), G4EmSaturation::VisibleEnergyDeposition(), G4INCL::DeuteronDensity::wavefunctionR(), and G4Clebsch::Weight().
min()
template<typename T > T G4INCL::Math::min (const T t1, const T t2) inline
brief Return the smallest of the two arguments
Definition at line 117 of file G4INCLGlobals.hh.
Referenced by G4ParticleHPKallbachMannSyst::A(), G4RPGReaction::AddBlackTrackParticles(), G4AdjointCSMatrix::AddData(), G4EmDNAPhysicsActivator::AddElectronModels0(), G4EmDNAPhysicsActivator::AddGenericIonModels0(), Run::AddPhantomStep(), G4EmDNAPhysicsActivator::AddProtonModels0(), G4SolidExtentList::AddSurface(), G4AdjointPhotoElectricModel::AdjointCrossSection(), G4VAtomDeexcitation::AlongStepDeexcitation(), G4NuclearStopping::AlongStepDoIt(), G4ContinuousGainOfEnergy::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepDoIt(), G4VMultipleScattering::AlongStepDoIt(), G4Transportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4VEnergyLossProcess::AlongStepGetPhysicalInteractionLength(), G4Nucleus::AnnihilationEvaporationEffects(), G4LightMedia::AntiLambdaExchange(), G4LightMedia::AntiNeutronExchange(), G4LightMedia::AntiOmegaMinusExchange(), G4LightMedia::AntiProtonExchange(), G4LightMedia::AntiSigmaMinusExchange(), G4LightMedia::AntiSigmaPlusExchange(), G4LightMedia::AntiXiMinusExchange(), G4LightMedia::AntiXiZeroExchange(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4EmCaptureCascade::ApplyYourself(), G4CutTubs::ApproxSurfaceNormal(), G4eIonisationSpectrum::AverageEnergy(), G4RDeIonisationSpectrum::AverageEnergy(), G4eBremsstrahlungSpectrum::AverageEnergy(), G4RDeBremsstrahlungSpectrum::AverageEnergy(), G4eBremsstrahlungSpectrum::AverageValue(), G4RDeBremsstrahlungSpectrum::AverageValue(), G4HadronBuilder::Barion(), G4AtimaEnergyLossModel::Bethek_dedx_e(), G4UnionSolid::BoundingLimits(), G4IntersectionSolid::BoundingLimits(), G4Ellipsoid::BoundingLimits(), G4CutTubs::BoundingLimits(), G4Para::BoundingLimits(), G4Cons::BoundingLimits(), G4ExtrudedSolid::BoundingLimits(), G4Sphere::BoundingLimits(), G4WilsonAblationModel::BreakItUp(), DicomFilePET::BuildActivities(), G4Voxelizer::BuildBitmasks(), G4Voxelizer::BuildBoundingBox(), G4AdjointCSManager::BuildCrossSectionsMatricesForAGivenModelAndElement(), G4AdjointCSManager::BuildCrossSectionsMatricesForAGivenModelAndMaterial(), G4VEmProcess::BuildLambdaTable(), G4LowEnergyBremsstrahlung::BuildLossTable(), DicomFileCT::BuildMaterials(), G4PenelopeOscillatorManager::BuildOscillatorTable(), G4SBBremTable::BuildSamplingTables(), G4tgbVolume::BuildSolidForDivision(), DicomFileCT::BuildStructureIDs(), G4Voxelizer::BuildVoxelLimits(), G4BulirschStoer::calc_h_opt(), G4ConvergenceTester::calc_slope_fit(), G4VCSGfaceted::CalculateExtent(), G4UnionSolid::CalculateExtent(), G4IntersectionSolid::CalculateExtent(), G4RPGKMinusInelastic::Cascade(), G4RPGAntiLambdaInelastic::Cascade(), G4RPGAntiProtonInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGXiMinusInelastic::Cascade(), G4RPGSigmaPlusInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4RPGAntiOmegaMinusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGOmegaMinusInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGKZeroInelastic::Cascade(), G4RPGLambdaInelastic::Cascade(), G4RPGKPlusInelastic::Cascade(), G4RPGSigmaMinusInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), G4RPGAntiKZeroInelastic::Cascade(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4EllipticalTube::CheckParameters(), G4GeomTools::CheckSnip(), G4Fancy3DNucleus::ChoosePositions(), G4Nucleus::Cinema(), G4HadronicInteractionRegistry::Clean(), G4BoundingEnvelope::ClipEdgesByVoxel(), G4BoundingEnvelope::ClipVoxelByPlanes(), G4VEmAdjointModel::ComputeAdjointCrossSectionVectorPerAtomForScatProj(), G4VEmAdjointModel::ComputeAdjointCrossSectionVectorPerAtomForSecond(), G4VEmAdjointModel::ComputeAdjointCrossSectionVectorPerVolumeForScatProj(), G4VEmAdjointModel::ComputeAdjointCrossSectionVectorPerVolumeForSecond(), G4ChatterjeeCrossSection::ComputeCrossSection(), G4KalbachCrossSection::ComputeCrossSection(), G4BoldyshevTripletModel::ComputeCrossSectionPerAtom(), G4LivermoreGammaConversionModel::ComputeCrossSectionPerAtom(), G4LDMBremModel::ComputeCrossSectionPerAtom(), G4eBremsstrahlungRelModel::ComputeCrossSectionPerAtom(), G4eBremParametrizedModel::ComputeCrossSectionPerAtom(), G4PairProductionRelModel::ComputeCrossSectionPerAtom(), G4MuPairProductionModel::ComputeCrossSectionPerAtom(), G4MuBremsstrahlungModel::ComputeCrossSectionPerAtom(), G4IonParametrisedLossModel::ComputeCrossSectionPerAtom(), G4PolarizedMollerBhabhaModel::ComputeCrossSectionPerElectron(), G4AtimaEnergyLossModel::ComputeCrossSectionPerElectron(), G4MollerBhabhaModel::ComputeCrossSectionPerElectron(), G4mplIonisationWithDeltaModel::ComputeCrossSectionPerElectron(), G4LindhardSorensenIonModel::ComputeCrossSectionPerElectron(), G4BetheBlochModel::ComputeCrossSectionPerElectron(), G4ICRU73QOModel::ComputeCrossSectionPerElectron(), G4MuBetheBlochModel::ComputeCrossSectionPerElectron(), G4BraggIonModel::ComputeCrossSectionPerElectron(), G4BraggModel::ComputeCrossSectionPerElectron(), G4ComponentBarNucleonNucleusXsc::ComputeCrossSections(), G4ComponentGGHadronNucleusXsc::ComputeCrossSections(), G4ComponentGGNuclNuclXsc::ComputeCrossSections(), MyMollerBhabhaModel::ComputeDEDXPerVolume(), G4mplIonisationWithDeltaModel::ComputeDEDXPerVolume(), G4eBremsstrahlungRelModel::ComputeDEDXPerVolume(), G4eBremParametrizedModel::ComputeDEDXPerVolume(), G4PAIPhotModel::ComputeDEDXPerVolume(), G4PAIModel::ComputeDEDXPerVolume(), G4AtimaEnergyLossModel::ComputeDEDXPerVolume(), G4MollerBhabhaModel::ComputeDEDXPerVolume(), G4LindhardSorensenIonModel::ComputeDEDXPerVolume(), G4MuBremsstrahlungModel::ComputeDEDXPerVolume(), G4BetheBlochModel::ComputeDEDXPerVolume(), G4MuBetheBlochModel::ComputeDEDXPerVolume(), G4BraggIonModel::ComputeDEDXPerVolume(), G4LDMBremModel::ComputeDMicroscopicCrossSection(), G4SeltzerBergerModel::ComputeDXSectionPerAtom(), G4PairProductionRelModel::ComputeDXSectionPerAtom(), G4eplusTo3GammaOKVIModel::ComputeF(), G4UrbanMscModel::ComputeGeomPathLength(), G4UrbanAdjointMscModel::ComputeGeomPathLength(), G4GoudsmitSaundersonMscModel::ComputeGeomPathLength(), GFlashSamplingShowerParameterisation::ComputeLongitudinalParameters(), G4SandiaTable::ComputeMatSandiaMatrix(), G4WentzelOKandVIxSection::ComputeMaxElectronScattering(), G4PairProductionRelModel::ComputeRelDXSectionPerAtom(), G4ErrorPropagationNavigator::ComputeSafety(), G4VoxelSafety::ComputeSafety(), G4ErrorPropagationNavigator::ComputeStep(), G4PathFinder::ComputeStep(), G4PropagatorInField::ComputeStep(), G4Navigator::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4ITNavigator2::ComputeStep(), G4ITPathFinder::ComputeStep(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTruePathLengthLimit(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTrueStepLength(), G4ParameterisedNavigation::ComputeVoxelSafety(), G4VoxelNavigation::ComputeVoxelSafety(), G4PairProductionRelModel::ComputeXSectionPerAtom(), G4MuPairProductionModel::ComputMuPairLoss(), G4MonopolePhysics::ConstructProcess(), G4ConversionUtils::Convert(), G4BetheBlochModel::CorrectionsAlongStep(), G4VLongitudinalStringDecay::CreatePartonPair(), G4LivermoreIonisationCrossSection::CrossSection(), G4PenelopeIonisationCrossSection::CrossSection(), G4PAIPhotModel::CrossSectionPerVolume(), G4PAIModel::CrossSectionPerVolume(), G4DNAMolecularDissociation::DecayIt(), G4ICRU73QOModel::DEDXPerElement(), G4DiffractiveSplitableHadron::Diquark(), G4QGSMFragmentation::DiQuarkSplitup(), G4LundStringFragmentation::DiQuarkSplitup(), G4GeomTools::DiskExtent(), G4AtimaFluctuations::Dispersion(), G4EllipticalTube::DistanceToIn(), G4Ellipsoid::DistanceToIn(), G4UnionSolid::DistanceToIn(), G4Box::DistanceToIn(), G4IntersectionSolid::DistanceToIn(), G4Trap::DistanceToIn(), G4EllipticalTube::DistanceToOut(), G4Tet::DistanceToOut(), G4Box::DistanceToOut(), G4IntersectionSolid::DistanceToOut(), G4SubtractionSolid::DistanceToOut(), G4CutTubs::DistanceToOut(), G4ExtrudedSolid::DistanceToOut(), G4EllipticalCone::DistanceToOut(), G4Sphere::DistanceToOut(), G4PathFinder::DoNextCurvedStep(), G4ITPathFinder::DoNextCurvedStep(), G4PathFinder::DoNextLinearStep(), G4ITPathFinder::DoNextLinearStep(), G4ScreenedCoulombClassicalKinematics::DoScreeningComputation(), G4ScoreLogColorMap::DrawColorChartBar(), G4VScoreColorMap::DrawColorChartBar(), G4ScoreLogColorMap::DrawColorChartText(), G4VScoreColorMap::DrawColorChartText(), G4EmModelManager::DumpModelList(), GFlashShowerModel::ElectronDoIt(), G4BraggModel::ElectronicStoppingPower(), G4BraggIonModel::ElectronicStoppingPower(), G4GeomTools::EllipsePerimeter(), G4GeomTools::EllipticConeLateralArea(), G4AtimaFluctuations::EnergyTable_interpolate(), G4AtimaEnergyLossModel::EnergyTable_interpolate(), G4RDRangeTest::Escape(), G4VSolid::EstimateSurfaceArea(), G4Nucleus::EvaporationEffects(), G4RDeIonisationParameters::Excitation(), G4eIonisationParameters::Excitation(), G4MultiUnion::Extent(), G4RPGInelastic::Factorial(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4MesonAbsorption::FindAndFillCluster(), G4PhysicsVector::FindLinearEnergy(), G4JTPolynomialSolver::FindRoots(), G4PhysicsOrderedFreeVector::FindValueBinLocation(), G3CalcParamsFn(), G4ArrowModel::G4ArrowModel(), G4ElasticData::G4ElasticData(), G4IntersectingCone::G4IntersectingCone(), G4Tet::G4Tet(), G4eeToHadronsModel::GenerateCMPhoton(), G4Clebsch::GenerateIso3(), G4RPGReaction::GenerateNBodyEvent(), G4RPGReaction::GenerateNBodyEventT(), GFlashHomoShowerParameterisation::GenerateRadius(), GFlashSamplingShowerParameterisation::GenerateRadius(), G4AntiNeutronAnnihilationAtRest::GenerateSecondaries(), G4ParticleHPVector::Get15percentBorder(), DNA::Penetration::Terrisol1990::Get3DStdDeviation(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4hImpactIonisation::GetConstraints(), G4ContinuousGainOfEnergy::GetContinuousStepLimit(), G4PenelopeIonisationCrossSection::GetCrossSection(), G4LivermoreIonisationCrossSection::GetCrossSection(), G4VEnergyLossProcess::GetDEDXDispersion(), G4LindhardSorensenData::GetDeltaL(), G4BGGNucleonInelasticXS::GetElementCrossSection(), G4BGGPionElasticXS::GetElementCrossSection(), G4BGGNucleonElasticXS::GetElementCrossSection(), G4BGGPionInelasticXS::GetElementCrossSection(), G4PhotonEvaporation::GetEmissionProbability(), G4SolidExtentList::GetExtent(), G4ClippablePolygon::GetExtent(), G4OpBoundaryProcess::GetFacetNormal(), G4CutTubs::GetMaxMinZ(), G4ScreenedNuclearRecoil::GetMeanFreePath(), G4Accumulables::GetMergeFunction(), G4ClippablePolygon::GetMinPoint(), G4PenelopeBremsstrahlungFS::GetMomentumIntegral(), G4MuonMinusBoundDecay::GetMuonZeff(), G4RPGInelastic::GetNormalizationConstant(), G4ComponentGGHadronNucleusXsc::GetParticleBarCorIn(), G4ComponentGGHadronNucleusXsc::GetParticleBarCorTot(), G4VMscModel::GetParticleChangeForMSC(), G4ClippablePolygon::GetPlanerExtent(), G4ITNavigator2::GetRandomInCurrentVolume(), G4ScreeningMottCrossSection::GetScreeningAngle(), G4AdjointComptonModel::GetSecondAdjEnergyMaxForScatProjToProjCase(), G4VEmAdjointModel::GetSecondAdjEnergyMaxForScatProjToProjCase(), CCaloSD::getStepInfo(), G4ParticleHPVector::GetXsec(), G4ParticleHPPartial::GetY(), G4HadronNucleonXsc::HadronNucleonXscNS(), G4HadronNucleonXsc::HadronNucleonXscVU(), G4ClippablePolygon::InFrontOf(), G4ParticleHPDeExGammas::Init(), G4ParticleHPContAngularPar::Init(), G4BoldyshevTripletModel::Initialise(), G4LivermoreGammaConversionModel::Initialise(), G4LivermorePhotoElectricModel::Initialise(), G4eeToHadronsModel::Initialise(), G4WentzelVIModel::Initialise(), G4FermiFragmentsPoolVI::Initialise(), G4SeltzerBergerModel::Initialise(), G4EmModelManager::Initialise(), G4BetheHeitlerModel::InitialiseElementData(), G4eBremsstrahlungRelModel::InitialiseElementData(), G4PairProductionRelModel::InitialiseElementData(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), G4eBremsstrahlung::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), G4CoulombScattering::InitialiseProcess(), G4GammaConversion::InitialiseProcess(), CCalEventAction::initialize(), G4FastPathHadronicCrossSection::fastPathEntry::Initialize(), G4hImpactIonisation::InitializeParametrisation(), G4PenelopeRayleighModel::InitializeSamplingAlgorithm(), G4GoudsmitSaundersonTable::InitSCPCorrection(), G4INCL::IFunction1D::integrate(), G4eBremsstrahlungSpectrum::IntSpectrum(), G4RDeBremsstrahlungSpectrum::IntSpectrum(), G4INCL::IFunction1D::inverseCDFTable(), G4ExtrudedSolid::IsSameLineSegment(), G4INCL::NpiToSKChannel::KaonMomentum(), G4HadronNucleonXsc::KaonNucleonXscVG(), G4LightMedia::KaonPlusExchange(), G4LightMedia::KaonZeroShortExchange(), G4LightMedia::LambdaExchange(), G4LevelReader::LevelManager(), G4IntersectingCone::LineHitsCone1(), G4IntersectingCone::LineHitsCone2(), G4AttValueFilterT< T, ConversionErrorPolicy >::LoadIntervalElement(), G4SBBremTable::LoadSamplingTables(), G4SBBremTable::LoadSTGrid(), G4EmCorrections::LShellCorrection(), main(), G4AtimaEnergyLossModel::MaxSecondaryEnergy(), G4BetheBlochModel::MaxSecondaryEnergy(), MCGIDI_particle_getInternalID(), MCGIDI_POPs_findParticleIndex(), G4INCL::Random::Adapter::min(), G4hCoulombScatteringModel::MinPrimaryEnergy(), G4eCoulombScatteringModel::MinPrimaryEnergy(), G4LevelManager::NearestLevelIndex(), G4LightMedia::NeutronExchange(), G4RPGReaction::NuclearReaction(), G4ICRU49NuclearStoppingModel::NuclearStoppingPower(), G4LightMedia::OmegaMinusExchange(), DicomVFileImage::operator+(), DicomPhantomZSliceHeader::operator+(), G4PenelopeComptonModel::OscillatorTotalCrossSection(), G4RDeIonisationParameters::Parameter(), G4eIonisationParameters::Parameter(), G4RDBremsstrahlungParameters::Parameter(), G4BremsstrahlungParameters::Parameter(), G4LightMedia::PionPlusExchange(), G4RPGInelastic::Pmltpc(), G4DipBustGenerator::PolarAngle(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4VMultipleScattering::PreparePhysicsTable(), G4INCL::INCL::prepareReaction(), G4eBremsstrahlungSpectrum::Probability(), G4RDeIonisationSpectrum::Probability(), G4RDeBremsstrahlungSpectrum::Probability(), G4eIonisationSpectrum::Probability(), G4LightMedia::ProtonExchange(), G4DNAWaterDissociationDisplacer::radialDistributionOfElectron(), G4RPGTwoBody::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4PathFinder::RecheckDistanceToCurrentBoundary(), G4Navigator::RecheckDistanceToCurrentBoundary(), G4ITNavigator2::RecheckDistanceToCurrentBoundary(), G4VoxelSafety::SafetyForVoxelHeader(), G4VoxelSafety::SafetyForVoxelNode(), G4ParticleHPContAngularPar::Sample(), G4VEmAdjointModel::SampleAdjSecEnergyFromCSMatrix(), G4PAIModelData::SampleAlongStepTransfer(), G4UrbanMscModel::SampleCosineTheta(), G4UrbanAdjointMscModel::SampleCosineTheta(), G4DipBustGenerator::SampleCosTheta(), G4PenelopeBremsstrahlungAngular::SampleDirection(), G4UrbanAdjointMscModel::SampleDisplacement(), G4RDeIonisationSpectrum::SampleEnergy(), G4eIonisationSpectrum::SampleEnergy(), G4RDeBremsstrahlungSpectrum::SampleEnergy(), G4eBremsstrahlungSpectrum::SampleEnergy(), G4SBBremTable::SampleEnergyTransfer(), G4SeltzerBergerModel::SampleEnergyTransfer(), G4UniversalFluctuation::SampleFluctuations(), G4SampleResonance::SampleMass(), G4PAIModelData::SamplePostStepTransfer(), G4VScatteringCollision::SampleResonanceMass(), G4LEPTSDissociationModel::SampleSecondaries(), G4LEPTSExcitationModel::SampleSecondaries(), G4LivermoreGammaConversionModelRC::SampleSecondaries(), G4LivermoreNuclearGammaConversionModel::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4LivermoreIonisationModel::SampleSecondaries(), G4PenelopeRayleighModel::SampleSecondaries(), G4LDMBremModel::SampleSecondaries(), G4BetheHeitlerModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), G4eplusTo3GammaOKVIModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), G4eBremParametrizedModel::SampleSecondaries(), G4mplIonisationWithDeltaModel::SampleSecondaries(), G4PairProductionRelModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4MuPairProductionModel::SampleSecondaries(), G4MuBremsstrahlungModel::SampleSecondaries(), G4ICRU73QOModel::SampleSecondaries(), G4MuBetheBlochModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), G4BetheBlochModel::SampleSecondaries(), G4IonParametrisedLossModel::SampleSecondaries(), G4GammaTransition::SampleTransition(), G4RadioactiveDecayBase::SetDecayHalfAngle(), G4RadioactiveDecay::SetDecayHalfAngle(), G4EmConfigurator::SetExtraEmModel(), G4KDTree::HyperRect::SetMinMax(), CexmcProductionModelMessenger::SetNewValue(), CexmcEnergyDepositDigitizerMessenger::SetNewValue(), G4mplIonisationModel::SetParticle(), G4mplIonisationWithDeltaModel::SetParticle(), G3Division::SetRangeAndAxis(), G4OpenInventorXtExaminerViewer::setStartingPtForAnimation(), G4VEnergyLossProcess::SetStepFunction(), G4ScreeningMottCrossSection::SetupKinematic(), G4WentzelOKandVIxSection::SetupTarget(), G4EmParameters::SetVerbose(), G4AtimaEnergyLossModel::sezi_dedx_e(), G4EmCorrections::ShellCorrection(), G4LightMedia::SigmaMinusExchange(), G4LightMedia::SigmaPlusExchange(), G4RPGNeutronInelastic::SlowNeutron(), G4GeomTools::SphereExtent(), G4VMultipleScattering::StorePhysicsTable(), G4Scheduler::SynchronizeTracks(), G4EvaporationProbability::TotalProbability(), G4MultiUnion::TransformLimits(), G4Voxelizer::TransformLimits(), G4BulirschStoer::try_step(), G4EmConfigurator::UpdateModelEnergyRange(), CCalSteppingAction::UserSteppingAction(), G4Clebsch::Weight(), G4LightMedia::XiMinusExchange(), and G4LightMedia::XiZeroExchange().
pow13()
G4double G4INCL::Math::pow13 (G4double x) inline
Definition at line 88 of file G4INCLGlobals.hh.
Referenced by G4INCL::NuclearDensityFactory::createRPCorrelationTable(), G4INCL::CoulombNonRelativistic::getCoulombRadius(), G4INCL::NuclearPotential::NuclearPotentialIsospin::initialize(), G4INCL::NuclearPotential::INuclearPotential::INuclearPotential(), G4INCL::ParticleSampler::sampleOneParticleWithFuzzyRPCorrelation(), and G4INCL::Random::sphereVector().
pow23()
G4double G4INCL::Math::pow23 (G4double x) inline
Definition at line 96 of file G4INCLGlobals.hh.
Referenced by G4INCL::CoulombNonRelativistic::getCoulombRadius().
powMinus13()
G4double G4INCL::Math::powMinus13 (G4double x) inline
Definition at line 92 of file G4INCLGlobals.hh.
sign()
template<typename T > G4int G4INCL::Math::sign (const T t) inline
A simple sign function that allows us to port fortran code to c++ more easily.
Definition at line 107 of file G4INCLGlobals.hh.
Referenced by G4Clebsch::ClebschGordanCoeff(), G4INCL::CoulombNonRelativistic::coulombDeviation(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::ElasticChannel::fillFinalState(), gaussianCDF(), G4INCL::IFunction1D::integrate(), PrimaryGeneratorAction2::InverseCumul(), nf_floatToShortestString(), nfu_getInfinity(), ptwXY_dullEdges(), ptwXY_integrateWithFunction(), G4INCL::StrangeAbsorbtionChannel::sampleAngles(), G4INCL::SigmaZeroDecayChannel::sampleAngles(), G4INCL::PionResonanceDecayChannel::sampleAngles(), G4INCL::DeltaDecayChannel::sampleAngles(), G4INCL::RootFinder::solve(), G4Clebsch::Wigner6J(), G4Clebsch::Wigner9J(), and G4Clebsch::WignerLittleD().
toDegrees()
G4double G4INCL::Math::toDegrees (G4double radians) inline
Definition at line 79 of file G4INCLGlobals.hh.
Referenced by G4INCL::Nucleus::fillEventInfo(), G4INCL::EventInfo::fillInverseKinematics(), and G4INCL::EventInfo::remnantToParticle().
Variable Documentation
oneOverSqrtThree
const G4double G4INCL::Math::oneOverSqrtThree = 1./std::sqrt((G4double)3.)
Definition at line 73 of file G4INCLGlobals.hh.
Referenced by G4INCL::NuclearDensityFactory::createPCDFTable(), G4INCL::NuclearDensityFactory::createRCDFTable(), G4INCL::NuclearDensityFactory::createRPCorrelationTable(), and G4INCL::Random::gaussVector().
oneOverSqrtTwo
const G4double G4INCL::Math::oneOverSqrtTwo = 1./std::sqrt((G4double)2.)
Definition at line 72 of file G4INCLGlobals.hh.
Referenced by gaussianCDF().
oneThird
const G4double G4INCL::Math::oneThird = 1./3.
Definition at line 74 of file G4INCLGlobals.hh.
Referenced by pow13(), and powMinus13().
pi
const G4double G4INCL::Math::pi = 3.14159265358979323846264338328
Definition at line 68 of file G4INCLGlobals.hh.
Referenced by arcCos(), arcSin(), G4INCL::CoulombNonRelativistic::coulombDeviation(), G4INCL::NpiToNKKbChannel::fillFinalState(), G4INCL::NpiToLKpiChannel::fillFinalState(), G4INCL::NpiToSKpiChannel::fillFinalState(), G4INCL::NpiToSK2piChannel::fillFinalState(), G4INCL::NNToNSKpiChannel::fillFinalState(), G4INCL::NpiToLK2piChannel::fillFinalState(), G4INCL::PauliStandard::getBlockingProbability(), and toDegrees().
piOverTwo
const G4double G4INCL::Math::piOverTwo = 0.5 * pi
Definition at line 71 of file G4INCLGlobals.hh.
Referenced by G4INCL::CoulombNonRelativistic::coulombDeviation(), and G4INCL::CoulombNonRelativistic::distortOut().
sqrtFiveThirds
const G4double G4INCL::Math::sqrtFiveThirds = std::sqrt(5./3.)
Definition at line 76 of file G4INCLGlobals.hh.
Referenced by G4INCL::ParticleTable::getFermiMomentumConstantLight().
sqrtThreeFifths
const G4double G4INCL::Math::sqrtThreeFifths = std::sqrt(3./5.)
Definition at line 77 of file G4INCLGlobals.hh.
Referenced by G4INCL::ParticleTable::getMomentumRMS().
tenPi
const G4double G4INCL::Math::tenPi = 10.0 * pi
Definition at line 70 of file G4INCLGlobals.hh.
Referenced by G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::CrossSections::interactionDistanceKbarN(), G4INCL::CrossSections::interactionDistanceKN(), G4INCL::CrossSections::interactionDistanceNN(), G4INCL::CrossSections::interactionDistancePiN(), G4INCL::CrossSections::interactionDistanceYN(), and G4INCL::INCL::prepareReaction().
twoPi
const G4double G4INCL::Math::twoPi = 2.0 * pi
Definition at line 69 of file G4INCLGlobals.hh.
Referenced by G4INCL::CoulombNonRelativistic::coulombDeviation(), G4INCL::DeuteronDensity::derivDensityR(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::ElasticChannel::fillFinalState(), G4INCL::Random::gaussWithMemory(), G4INCL::PauliStandard::getBlockingProbability(), G4INCL::NKbToLpiChannel::KaonMomentum(), G4INCL::NKbElasticChannel::KaonMomentum(), G4INCL::NKbToNKbChannel::KaonMomentum(), G4INCL::NKbToSpiChannel::KaonMomentum(), G4INCL::NpiToLKChannel::KaonMomentum(), G4INCL::NpiToSKChannel::KaonMomentum(), G4INCL::Random::normVector(), G4INCL::INCL::preCascade(), G4INCL::StrangeAbsorbtionChannel::sampleAngles(), G4INCL::PionResonanceDecayChannel::sampleAngles(), G4INCL::DeltaDecayChannel::sampleAngles(), G4INCL::SigmaZeroDecayChannel::sampleAngles(), and G4BetheHeitler5DModel::SampleSecondaries().
twoThirds
const G4double G4INCL::Math::twoThirds = 2./3.
Definition at line 75 of file G4INCLGlobals.hh.
Referenced by G4INCL::InteractionAvatar::postInteraction(), and pow23().