Geant4: G4VAnalysisManager Class Reference
G4VAnalysisManager Class Reference abstract
#include <G4VAnalysisManager.hh>
Public Member Functions
G4VAnalysisManager (const G4String &type, G4bool isMaster)
virtual ~G4VAnalysisManager ()
G4bool OpenFile (const G4String &fileName="")
G4bool Write ()
G4bool CloseFile (G4bool reset=true)
G4bool Merge (tools::histo::hmpi *hmpi)
G4bool Plot ()
G4bool IsOpenFile () const
G4bool SetFileName (const G4String &fileName)
G4bool SetHistoDirectoryName (const G4String &dirName)
G4bool SetNtupleDirectoryName (const G4String &dirName)
void SetCompressionLevel (G4int level)
G4String GetFileName () const
G4String GetHistoDirectoryName () const
G4String GetNtupleDirectoryName () const
G4int GetCompressionLevel () const
G4int CreateH1 (const G4String &name, const G4String &title, G4int nbins, G4double xmin, G4double xmax, const G4String &unitName="none", const G4String &fcnName="none", const G4String &binSchemeName="linear")
G4int CreateH1 (const G4String &name, const G4String &title, const std::vector< G4double > &edges, const G4String &unitName="none", const G4String &fcnName="none")
G4int CreateH2 (const G4String &name, const G4String &title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear")
G4int CreateH2 (const G4String &name, const G4String &title, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none")
G4int CreateH3 (const G4String &name, const G4String &title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4int nzbins, G4double zmin, G4double zmax, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear", const G4String &zbinSchemeName="linear")
G4int CreateH3 (const G4String &name, const G4String &title, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, const std::vector< G4double > &zedges, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none")
G4bool SetH1 (G4int id, G4int nbins, G4double xmin, G4double xmax, const G4String &unitName="none", const G4String &fcnName="none", const G4String &binSchemeName="linear")
G4bool SetH1 (G4int id, const std::vector< G4double > &edges, const G4String &unitName="none", const G4String &fcnName="none")
G4bool SetH2 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear")
G4bool SetH2 (G4int id, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none")
G4bool SetH3 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nzbins, G4double zmin, G4double zmax, G4int nybins, G4double ymin, G4double ymax, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear", const G4String &zbinSchemeName="linear")
G4bool SetH3 (G4int id, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, const std::vector< G4double > &zedges, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none")
G4bool ScaleH1 (G4int id, G4double factor)
G4bool ScaleH2 (G4int id, G4double factor)
G4bool ScaleH3 (G4int id, G4double factor)
G4int CreateP1 (const G4String &name, const G4String &title, G4int nbins, G4double xmin, G4double xmax, G4double ymin=0, G4double ymax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &xbinSchemeName="linear")
G4int CreateP1 (const G4String &name, const G4String &title, const std::vector< G4double > &edges, G4double ymin=0, G4double ymax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none")
G4int CreateP2 (const G4String &name, const G4String &title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4double zmin=0, G4double zmax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear")
G4int CreateP2 (const G4String &name, const G4String &title, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, G4double zmin=0, G4double zmax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none")
G4bool SetP1 (G4int id, G4int nbins, G4double xmin, G4double xmax, G4double ymin=0, G4double ymax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &xbinSchemeName="linear")
G4bool SetP1 (G4int id, const std::vector< G4double > &edges, G4double ymin=0, G4double ymax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none")
G4bool SetP2 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4double zmin=0, G4double zmax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear")
G4bool SetP2 (G4int id, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, G4double zmin=0, G4double zmax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none")
G4bool ScaleP1 (G4int id, G4double factor)
G4bool ScaleP2 (G4int id, G4double factor)
G4int CreateNtuple (const G4String &name, const G4String &title)
G4int CreateNtupleIColumn (const G4String &name)
G4int CreateNtupleFColumn (const G4String &name)
G4int CreateNtupleDColumn (const G4String &name)
G4int CreateNtupleSColumn (const G4String &name)
G4int CreateNtupleIColumn (const G4String &name, std::vector< int > &vector)
G4int CreateNtupleFColumn (const G4String &name, std::vector< float > &vector)
G4int CreateNtupleDColumn (const G4String &name, std::vector< double > &vector)
void FinishNtuple ()
G4int CreateNtupleIColumn (G4int ntupleId, const G4String &name)
G4int CreateNtupleFColumn (G4int ntupleId, const G4String &name)
G4int CreateNtupleDColumn (G4int ntupleId, const G4String &name)
G4int CreateNtupleSColumn (G4int ntupleId, const G4String &name)
G4int CreateNtupleIColumn (G4int ntupleId, const G4String &name, std::vector< int > &vector)
G4int CreateNtupleFColumn (G4int ntupleId, const G4String &name, std::vector< float > &vector)
G4int CreateNtupleDColumn (G4int ntupleId, const G4String &name, std::vector< double > &vector)
void FinishNtuple (G4int ntupleId)
G4bool SetFirstHistoId (G4int firstId)
G4bool SetFirstH1Id (G4int firstId)
G4bool SetFirstH2Id (G4int firstId)
G4bool SetFirstH3Id (G4int firstId)
G4bool SetFirstProfileId (G4int firstId)
G4bool SetFirstP1Id (G4int firstId)
G4bool SetFirstP2Id (G4int firstId)
G4bool SetFirstNtupleId (G4int firstId)
G4bool SetFirstNtupleColumnId (G4int firstId)
G4bool FillH1 (G4int id, G4double value, G4double weight=1.0)
G4bool FillH2 (G4int id, G4double xvalue, G4double yvalue, G4double weight=1.0)
G4bool FillH3 (G4int id, G4double xvalue, G4double yvalue, G4double zvalue, G4double weight=1.0)
G4bool FillP1 (G4int id, G4double xvalue, G4double yvalue, G4double weight=1.0)
G4bool FillP2 (G4int id, G4double xvalue, G4double yvalue, G4double zvalue, G4double weight=1.0)
G4bool FillNtupleIColumn (G4int id, G4int value)
G4bool FillNtupleFColumn (G4int id, G4float value)
G4bool FillNtupleDColumn (G4int id, G4double value)
G4bool FillNtupleSColumn (G4int id, const G4String &value)
G4bool AddNtupleRow ()
G4bool FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value)
G4bool FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value)
G4bool FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value)
G4bool FillNtupleSColumn (G4int ntupleId, G4int id, const G4String &value)
G4bool AddNtupleRow (G4int ntupleId)
void SetActivation (G4bool activation)
G4bool GetActivation () const
G4bool IsActive () const
G4bool IsAscii () const
G4bool IsPlotting () const
G4int GetFirstH1Id () const
G4int GetFirstH2Id () const
G4int GetFirstH3Id () const
G4int GetFirstP1Id () const
G4int GetFirstP2Id () const
G4int GetFirstNtupleId () const
G4int GetFirstNtupleColumnId () const
G4int GetNofH1s () const
G4int GetNofH2s () const
G4int GetNofH3s () const
G4int GetNofP1s () const
G4int GetNofP2s () const
G4int GetNofNtuples () const
G4int GetH1Id (const G4String &name, G4bool warn=true) const
G4int GetH2Id (const G4String &name, G4bool warn=true) const
G4int GetH3Id (const G4String &name, G4bool warn=true) const
G4int GetP1Id (const G4String &name, G4bool warn=true) const
G4int GetP2Id (const G4String &name, G4bool warn=true) const
void SetH1Activation (G4bool activation)
void SetH1Activation (G4int id, G4bool activation)
void SetH1Ascii (G4int id, G4bool ascii)
void SetH1Plotting (G4int id, G4bool plotting)
void SetH2Activation (G4bool activation)
void SetH2Activation (G4int id, G4bool activation)
void SetH2Ascii (G4int id, G4bool ascii)
void SetH2Plotting (G4int id, G4bool plotting)
void SetH3Activation (G4bool activation)
void SetH3Activation (G4int id, G4bool activation)
void SetH3Ascii (G4int id, G4bool ascii)
void SetH3Plotting (G4int id, G4bool plotting)
void SetP1Activation (G4bool activation)
void SetP1Activation (G4int id, G4bool activation)
void SetP1Ascii (G4int id, G4bool ascii)
void SetP1Plotting (G4int id, G4bool plotting)
void SetP2Activation (G4bool activation)
void SetP2Activation (G4int id, G4bool activation)
void SetP2Ascii (G4int id, G4bool ascii)
void SetP2Plotting (G4int id, G4bool plotting)
void SetNtupleActivation (G4bool activation)
void SetNtupleActivation (G4int id, G4bool activation)
G4int GetH1Nbins (G4int id) const
G4double GetH1Xmin (G4int id) const
G4double GetH1Xmax (G4int id) const
G4double GetH1Width (G4int id) const
G4int GetH2Nxbins (G4int id) const
G4double GetH2Xmin (G4int id) const
G4double GetH2Xmax (G4int id) const
G4double GetH2XWidth (G4int id) const
G4int GetH2Nybins (G4int id) const
G4double GetH2Ymin (G4int id) const
G4double GetH2Ymax (G4int id) const
G4double GetH2YWidth (G4int id) const
G4int GetH3Nxbins (G4int id) const
G4double GetH3Xmin (G4int id) const
G4double GetH3Xmax (G4int id) const
G4double GetH3XWidth (G4int id) const
G4int GetH3Nybins (G4int id) const
G4double GetH3Ymin (G4int id) const
G4double GetH3Ymax (G4int id) const
G4double GetH3YWidth (G4int id) const
G4int GetH3Nzbins (G4int id) const
G4double GetH3Zmin (G4int id) const
G4double GetH3Zmax (G4int id) const
G4double GetH3ZWidth (G4int id) const
G4int GetP1Nbins (G4int id) const
G4double GetP1Xmin (G4int id) const
G4double GetP1Xmax (G4int id) const
G4double GetP1XWidth (G4int id) const
G4double GetP1Ymin (G4int id) const
G4double GetP1Ymax (G4int id) const
G4int GetP2Nxbins (G4int id) const
G4double GetP2Xmin (G4int id) const
G4double GetP2Xmax (G4int id) const
G4double GetP2XWidth (G4int id) const
G4int GetP2Nybins (G4int id) const
G4double GetP2Ymin (G4int id) const
G4double GetP2Ymax (G4int id) const
G4double GetP2YWidth (G4int id) const
G4double GetP2Zmin (G4int id) const
G4double GetP2Zmax (G4int id) const
G4String GetH1Name (G4int id) const
G4double GetH1Unit (G4int id) const
G4bool GetH1Activation (G4int id) const
G4bool GetH1Ascii (G4int id) const
G4bool GetH1Plotting (G4int id) const
G4String GetH2Name (G4int id) const
G4double GetH2XUnit (G4int id) const
G4double GetH2YUnit (G4int id) const
G4bool GetH2Activation (G4int id) const
G4bool GetH2Ascii (G4int id) const
G4bool GetH2Plotting (G4int id) const
G4String GetH3Name (G4int id) const
G4double GetH3XUnit (G4int id) const
G4double GetH3YUnit (G4int id) const
G4double GetH3ZUnit (G4int id) const
G4bool GetH3Activation (G4int id) const
G4bool GetH3Ascii (G4int id) const
G4bool GetH3Plotting (G4int id) const
G4String GetP1Name (G4int id) const
G4double GetP1XUnit (G4int id) const
G4double GetP1YUnit (G4int id) const
G4bool GetP1Activation (G4int id) const
G4bool GetP1Ascii (G4int id) const
G4bool GetP1Plotting (G4int id) const
G4String GetP2Name (G4int id) const
G4double GetP2XUnit (G4int id) const
G4double GetP2YUnit (G4int id) const
G4double GetP2ZUnit (G4int id) const
G4bool GetP2Activation (G4int id) const
G4bool GetP2Ascii (G4int id) const
G4bool GetP2Plotting (G4int id) const
G4bool GetNtupleActivation (G4int id) const
G4bool SetH1Title (G4int id, const G4String &title)
G4bool SetH1XAxisTitle (G4int id, const G4String &title)
G4bool SetH1YAxisTitle (G4int id, const G4String &title)
G4bool SetH2Title (G4int id, const G4String &title)
G4bool SetH2XAxisTitle (G4int id, const G4String &title)
G4bool SetH2YAxisTitle (G4int id, const G4String &title)
G4bool SetH2ZAxisTitle (G4int id, const G4String &title)
G4bool SetH3Title (G4int id, const G4String &title)
G4bool SetH3XAxisTitle (G4int id, const G4String &title)
G4bool SetH3YAxisTitle (G4int id, const G4String &title)
G4bool SetH3ZAxisTitle (G4int id, const G4String &title)
G4bool SetP1Title (G4int id, const G4String &title)
G4bool SetP1XAxisTitle (G4int id, const G4String &title)
G4bool SetP1YAxisTitle (G4int id, const G4String &title)
G4bool SetP2Title (G4int id, const G4String &title)
G4bool SetP2XAxisTitle (G4int id, const G4String &title)
G4bool SetP2YAxisTitle (G4int id, const G4String &title)
G4bool SetP2ZAxisTitle (G4int id, const G4String &title)
G4String GetH1Title (G4int id) const
G4String GetH1XAxisTitle (G4int id) const
G4String GetH1YAxisTitle (G4int id) const
G4String GetH2Title (G4int id) const
G4String GetH2XAxisTitle (G4int id) const
G4String GetH2YAxisTitle (G4int id) const
G4String GetH2ZAxisTitle (G4int id) const
G4String GetH3Title (G4int id) const
G4String GetH3XAxisTitle (G4int id) const
G4String GetH3YAxisTitle (G4int id) const
G4String GetH3ZAxisTitle (G4int id) const
G4String GetP1Title (G4int id) const
G4String GetP1XAxisTitle (G4int id) const
G4String GetP1YAxisTitle (G4int id) const
G4String GetP1ZAxisTitle (G4int id) const
G4String GetP2Title (G4int id) const
G4String GetP2XAxisTitle (G4int id) const
G4String GetP2YAxisTitle (G4int id) const
G4String GetP2ZAxisTitle (G4int id) const
void SetVerboseLevel (G4int verboseLevel)
G4int GetVerboseLevel () const
G4String GetType () const
G4String GetFileType () const
Protected Member Functions
virtual G4bool OpenFileImpl (const G4String &fileName)=0
virtual G4bool WriteImpl ()=0
virtual G4bool CloseFileImpl (G4bool reset)=0
virtual G4bool PlotImpl ()=0
virtual G4bool MergeImpl (tools::histo::hmpi *hmpi)=0
virtual G4bool IsOpenFileImpl () const =0
void SetH1Manager (G4VH1Manager *h1Manager)
void SetH2Manager (G4VH2Manager *h2Manager)
void SetH3Manager (G4VH3Manager *h3Manager)
void SetP1Manager (G4VP1Manager *p1Manager)
void SetP2Manager (G4VP2Manager *p2Manager)
void SetNtupleManager (G4VNtupleManager *ntupleManager)
void SetFileManager (std::shared_ptr< G4VFileManager > fileManager)
void SetPlotManager (std::shared_ptr< G4PlotManager > plotManager)
G4bool WriteAscii (const G4String &fileName)
Protected Attributes
G4AnalysisManagerState fState
std::shared_ptr< G4VFileManager > fVFileManager
std::shared_ptr< G4PlotManager > fPlotManager
Private Attributes
std::unique_ptr< G4AnalysisMessenger > fMessenger
std::shared_ptr< G4HnManager > fH1HnManager
std::shared_ptr< G4HnManager > fH2HnManager
std::shared_ptr< G4HnManager > fH3HnManager
std::shared_ptr< G4HnManager > fP1HnManager
std::shared_ptr< G4HnManager > fP2HnManager
std::unique_ptr< G4VH1Manager > fVH1Manager
std::unique_ptr< G4VH2Manager > fVH2Manager
std::unique_ptr< G4VH3Manager > fVH3Manager
std::unique_ptr< G4VP1Manager > fVP1Manager
std::unique_ptr< G4VP2Manager > fVP2Manager
G4VNtupleManager * fVNtupleManager
Detailed Description
Definition at line 65 of file G4VAnalysisManager.hh.
Constructor & Destructor Documentation
G4VAnalysisManager()
G4VAnalysisManager::G4VAnalysisManager (const G4String & type, G4bool isMaster)
Definition at line 46 of file G4VAnalysisManager.cc.
~G4VAnalysisManager()
G4VAnalysisManager::~G4VAnalysisManager () virtual
Definition at line 67 of file G4VAnalysisManager.cc.
Member Function Documentation
AddNtupleRow() [1/2]
G4bool G4VAnalysisManager::AddNtupleRow ()
Referenced by Histo::AddRow(), XrayFluoAnalysisManager::analyseStepping(), XrayTelAnalysis::analyseStepping(), G4PhysChemIO::G4Analysis::CreateSolvatedElectron(), G4PhysChemIO::G4Analysis::CreateWaterMolecule(), CCalEventAction::EndOfEventAction(), G4ScoreNtupleWriter::Fill(), DMXPrimaryGeneratorAction::GeneratePrimaries(), Par02Output::SaveTrack(), GammaRayTelAnalysis::setNtuple(), HadrontherapyLet::StoreLetAscii(), PurgMagSteppingAction::UserSteppingAction(), DMXEventAction::writePmtHitsToFile(), DMXEventAction::writeScintHitsToFile(), and ScoreSpecies::WriteWithAnalysisManager().
AddNtupleRow() [2/2]
G4bool G4VAnalysisManager::AddNtupleRow (G4int ntupleId)
CloseFile()
G4bool G4VAnalysisManager::CloseFile (G4bool reset = true)
Definition at line 226 of file G4VAnalysisManager.cc.
Referenced by Analysis::Close(), Par02Output::EndAnalysis(), GammaRayTelAnalysis::EndOfRun(), LXeRunAction::EndOfRunAction(), FCALRunAction::EndOfRunAction(), UltraRunAction::EndOfRunAction(), XrayFluoAnalysisManager::finish(), XrayTelAnalysis::finish(), main(), Histo::Save(), RMC01AnalysisManager::Save(), HadrontherapyLet::StoreLetAscii(), G4ScoreNtupleWriter::Write(), and ScoreSpecies::WriteWithAnalysisManager().
CloseFileImpl()
virtual G4bool G4VAnalysisManager::CloseFileImpl (G4bool reset) protected pure virtual
Implemented in G4RootAnalysisManager, G4CsvAnalysisManager, G4Hdf5AnalysisManager, G4XmlAnalysisManager, and G4RootMpiAnalysisManager.
Referenced by CloseFile().
CreateH1() [1/2]
G4int G4VAnalysisManager::CreateH1 (const G4String & name, const G4String & title, const std::vector< G4double > & edges, const G4String & unitName = "none", const G4String & fcnName = "none")
Definition at line 312 of file G4VAnalysisManager.cc.
CreateH1() [2/2]
G4int G4VAnalysisManager::CreateH1 (const G4String & name, const G4String & title, G4int nbins, G4double xmin, G4double xmax, const G4String & unitName = "none", const G4String & fcnName = "none", const G4String & binSchemeName = "linear")
Definition at line 298 of file G4VAnalysisManager.cc.
Referenced by GammaRayTelAnalysis::BeginOfRun(), UltraRunAction::BeginOfRunAction(), CCalRunAction::Book(), Analysis::Book(), XrayFluoAnalysisManager::book(), XrayTelAnalysis::book(), Histo::Book(), DMXRunAction::Book(), RMC01AnalysisManager::Book(), Par02Output::CreateHistograms(), FCALRunAction::FCALRunAction(), and G4H1Messenger::SetNewValue().
CreateH2() [1/2]
G4int G4VAnalysisManager::CreateH2 (const G4String & name, const G4String & title, const std::vector< G4double > & xedges, const std::vector< G4double > & yedges, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none")
Definition at line 347 of file G4VAnalysisManager.cc.
CreateH2() [2/2]
G4int G4VAnalysisManager::CreateH2 (const G4String & name, const G4String & title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & xbinSchemeName = "linear", const G4String & ybinSchemeName = "linear")
Definition at line 323 of file G4VAnalysisManager.cc.
Referenced by GammaRayTelAnalysis::BeginOfRun(), Analysis::Book(), XrayTelAnalysis::book(), DMXRunAction::Book(), and G4H2Messenger::SetNewValue().
CreateH3() [1/2]
G4int G4VAnalysisManager::CreateH3 (const G4String & name, const G4String & title, const std::vector< G4double > & xedges, const std::vector< G4double > & yedges, const std::vector< G4double > & zedges, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none")
Definition at line 398 of file G4VAnalysisManager.cc.
CreateH3() [2/2]
G4int G4VAnalysisManager::CreateH3 (const G4String & name, const G4String & title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4int nzbins, G4double zmin, G4double zmax, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none", const G4String & xbinSchemeName = "linear", const G4String & ybinSchemeName = "linear", const G4String & zbinSchemeName = "linear")
Definition at line 365 of file G4VAnalysisManager.cc.
Referenced by Analysis::Book(), and G4H3Messenger::SetNewValue().
CreateNtuple()
G4int G4VAnalysisManager::CreateNtuple (const G4String & name, const G4String & title)
Definition at line 736 of file G4VAnalysisManager.cc.
Referenced by GammaRayTelAnalysis::BeginOfRun(), CCalRunAction::Book(), XrayFluoAnalysisManager::book(), G4ScoreNtupleWriter::Book(), XrayTelAnalysis::book(), Histo::Book(), PurgMagRunAction::Book(), DMXRunAction::Book(), G4PhysChemIO::G4Analysis::InitializeFile(), HadrontherapyLet::StoreLetAscii(), and ScoreSpecies::WriteWithAnalysisManager().
CreateNtupleDColumn() [1/4]
G4int G4VAnalysisManager::CreateNtupleDColumn (const G4String & name)
Definition at line 761 of file G4VAnalysisManager.cc.
Referenced by GammaRayTelAnalysis::BeginOfRun(), XrayFluoAnalysisManager::book(), G4ScoreNtupleWriter::Book(), XrayTelAnalysis::book(), Histo::Book(), PurgMagRunAction::Book(), DMXRunAction::Book(), G4PhysChemIO::G4Analysis::InitializeFile(), HadrontherapyLet::StoreLetAscii(), and ScoreSpecies::WriteWithAnalysisManager().
CreateNtupleDColumn() [2/4]
G4int G4VAnalysisManager::CreateNtupleDColumn (const G4String & name, std::vector< double > & vector)
Definition at line 795 of file G4VAnalysisManager.cc.
CreateNtupleDColumn() [3/4]
G4int G4VAnalysisManager::CreateNtupleDColumn (G4int ntupleId, const G4String & name)
Definition at line 829 of file G4VAnalysisManager.cc.
CreateNtupleDColumn() [4/4]
G4int G4VAnalysisManager::CreateNtupleDColumn (G4int ntupleId, const G4String & name, std::vector< double > & vector)
Definition at line 867 of file G4VAnalysisManager.cc.
CreateNtupleFColumn() [1/4]
G4int G4VAnalysisManager::CreateNtupleFColumn (const G4String & name)
Definition at line 753 of file G4VAnalysisManager.cc.
Referenced by CCalRunAction::Book(), and Histo::Book().
CreateNtupleFColumn() [2/4]
G4int G4VAnalysisManager::CreateNtupleFColumn (const G4String & name, std::vector< float > & vector)
Definition at line 786 of file G4VAnalysisManager.cc.
CreateNtupleFColumn() [3/4]
G4int G4VAnalysisManager::CreateNtupleFColumn (G4int ntupleId, const G4String & name)
Definition at line 819 of file G4VAnalysisManager.cc.
CreateNtupleFColumn() [4/4]
G4int G4VAnalysisManager::CreateNtupleFColumn (G4int ntupleId, const G4String & name, std::vector< float > & vector)
Definition at line 857 of file G4VAnalysisManager.cc.
CreateNtupleIColumn() [1/4]
G4int G4VAnalysisManager::CreateNtupleIColumn (const G4String & name)
Definition at line 745 of file G4VAnalysisManager.cc.
Referenced by XrayFluoAnalysisManager::book(), G4ScoreNtupleWriter::Book(), Histo::Book(), G4PhysChemIO::G4Analysis::InitializeFile(), HadrontherapyLet::StoreLetAscii(), and ScoreSpecies::WriteWithAnalysisManager().
CreateNtupleIColumn() [2/4]
G4int G4VAnalysisManager::CreateNtupleIColumn (const G4String & name, std::vector< int > & vector)
Definition at line 777 of file G4VAnalysisManager.cc.
CreateNtupleIColumn() [3/4]
G4int G4VAnalysisManager::CreateNtupleIColumn (G4int ntupleId, const G4String & name)
Definition at line 810 of file G4VAnalysisManager.cc.
CreateNtupleIColumn() [4/4]
G4int G4VAnalysisManager::CreateNtupleIColumn (G4int ntupleId, const G4String & name, std::vector< int > & vector)
Definition at line 847 of file G4VAnalysisManager.cc.
CreateNtupleSColumn() [1/2]
G4int G4VAnalysisManager::CreateNtupleSColumn (const G4String & name)
Definition at line 769 of file G4VAnalysisManager.cc.
Referenced by G4PhysChemIO::G4Analysis::InitializeFile(), and ScoreSpecies::WriteWithAnalysisManager().
CreateNtupleSColumn() [2/2]
G4int G4VAnalysisManager::CreateNtupleSColumn (G4int ntupleId, const G4String & name)
Definition at line 838 of file G4VAnalysisManager.cc.
CreateP1() [1/2]
G4int G4VAnalysisManager::CreateP1 (const G4String & name, const G4String & title, const std::vector< G4double > & edges, G4double ymin = 0, G4double ymax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none")
Definition at line 565 of file G4VAnalysisManager.cc.
CreateP1() [2/2]
G4int G4VAnalysisManager::CreateP1 (const G4String & name, const G4String & title, G4int nbins, G4double xmin, G4double xmax, G4double ymin = 0, G4double ymax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & xbinSchemeName = "linear")
Definition at line 544 of file G4VAnalysisManager.cc.
Referenced by Analysis::Book(), and G4P1Messenger::SetNewValue().
CreateP2() [1/2]
G4int G4VAnalysisManager::CreateP2 (const G4String & name, const G4String & title, const std::vector< G4double > & xedges, const std::vector< G4double > & yedges, G4double zmin = 0, G4double zmax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none")
Definition at line 612 of file G4VAnalysisManager.cc.
CreateP2() [2/2]
G4int G4VAnalysisManager::CreateP2 (const G4String & name, const G4String & title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4double zmin = 0, G4double zmax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none", const G4String & xbinSchemeName = "linear", const G4String & ybinSchemeName = "linear")
Definition at line 583 of file G4VAnalysisManager.cc.
Referenced by Analysis::Book(), and G4P2Messenger::SetNewValue().
FillH1()
G4bool G4VAnalysisManager::FillH1 (G4int id, G4double value, G4double weight = 1.0)
Referenced by XrayFluoAnalysisManager::analyseEnergyDep(), XrayFluoAnalysisManager::analysePrimaryGenerator(), XrayFluoAnalysisManager::analyseStepping(), XrayTelAnalysis::analyseStepping(), CCalSteppingAction::endOfEvent(), CCalEventAction::EndOfEventAction(), FCALTBEventAction::EndOfEventAction(), UltraEventAction::EndOfEventAction(), DMXEventAction::EndOfEventAction(), Histo::Fill(), Par02Output::FillHistogram(), GammaRayTelAnalysis::InsertEnergy(), GammaRayTelAnalysis::InsertHits(), DMXSteppingAction::UserSteppingAction(), and DMXEventAction::writeScintHitsToFile().
FillH2()
G4bool G4VAnalysisManager::FillH2 (G4int id, G4double xvalue, G4double yvalue, G4double weight = 1.0)
Referenced by XrayTelAnalysis::analyseStepping(), GammaRayTelAnalysis::InsertPositionXZ(), GammaRayTelAnalysis::InsertPositionYZ(), and DMXEventAction::writePmtHitsToFile().
FillH3()
G4bool G4VAnalysisManager::FillH3 (G4int id, G4double xvalue, G4double yvalue, G4double zvalue, G4double weight = 1.0)
FillNtupleDColumn() [1/2]
G4bool G4VAnalysisManager::FillNtupleDColumn (G4int id, G4double value)
Referenced by XrayFluoAnalysisManager::analyseStepping(), XrayTelAnalysis::analyseStepping(), G4PhysChemIO::G4Analysis::CreateSolvatedElectron(), G4PhysChemIO::G4Analysis::CreateWaterMolecule(), G4ScoreNtupleWriter::Fill(), Histo::FillTupleD(), DMXPrimaryGeneratorAction::GeneratePrimaries(), Par02Output::SaveTrack(), GammaRayTelAnalysis::setNtuple(), HadrontherapyLet::StoreLetAscii(), PurgMagSteppingAction::UserSteppingAction(), DMXEventAction::writePmtHitsToFile(), DMXEventAction::writeScintHitsToFile(), and ScoreSpecies::WriteWithAnalysisManager().
FillNtupleDColumn() [2/2]
G4bool G4VAnalysisManager::FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value)
FillNtupleFColumn() [1/2]
G4bool G4VAnalysisManager::FillNtupleFColumn (G4int id, G4float value)
Referenced by CCalEventAction::EndOfEventAction(), and Histo::FillTupleF().
FillNtupleFColumn() [2/2]
G4bool G4VAnalysisManager::FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value)
FillNtupleIColumn() [1/2]
G4bool G4VAnalysisManager::FillNtupleIColumn (G4int id, G4int value)
Referenced by XrayFluoAnalysisManager::analyseStepping(), G4PhysChemIO::G4Analysis::CreateSolvatedElectron(), G4PhysChemIO::G4Analysis::CreateWaterMolecule(), G4ScoreNtupleWriter::Fill(), Histo::FillTupleI(), Par02Output::SaveTrack(), HadrontherapyLet::StoreLetAscii(), and ScoreSpecies::WriteWithAnalysisManager().
FillNtupleIColumn() [2/2]
G4bool G4VAnalysisManager::FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value)
FillNtupleSColumn() [1/2]
G4bool G4VAnalysisManager::FillNtupleSColumn (G4int id, const G4String & value)
Referenced by G4PhysChemIO::G4Analysis::CreateSolvatedElectron(), G4PhysChemIO::G4Analysis::CreateWaterMolecule(), and ScoreSpecies::WriteWithAnalysisManager().
FillNtupleSColumn() [2/2]
G4bool G4VAnalysisManager::FillNtupleSColumn (G4int ntupleId, G4int id, const G4String & value)
FillP1()
G4bool G4VAnalysisManager::FillP1 (G4int id, G4double xvalue, G4double yvalue, G4double weight = 1.0)
FillP2()
G4bool G4VAnalysisManager::FillP2 (G4int id, G4double xvalue, G4double yvalue, G4double zvalue, G4double weight = 1.0)
FinishNtuple() [1/2]
void G4VAnalysisManager::FinishNtuple ()
Definition at line 804 of file G4VAnalysisManager.cc.
Referenced by GammaRayTelAnalysis::BeginOfRun(), CCalRunAction::Book(), XrayFluoAnalysisManager::book(), G4ScoreNtupleWriter::Book(), XrayTelAnalysis::book(), PurgMagRunAction::Book(), DMXRunAction::Book(), G4PhysChemIO::G4Analysis::InitializeFile(), HadrontherapyLet::StoreLetAscii(), and ScoreSpecies::WriteWithAnalysisManager().
FinishNtuple() [2/2]
void G4VAnalysisManager::FinishNtuple (G4int ntupleId)
Definition at line 877 of file G4VAnalysisManager.cc.
GetActivation()
G4bool G4VAnalysisManager::GetActivation () const
GetCompressionLevel()
G4int G4VAnalysisManager::GetCompressionLevel () const
Definition at line 292 of file G4VAnalysisManager.cc.
GetFileName()
G4String G4VAnalysisManager::GetFileName () const
Definition at line 274 of file G4VAnalysisManager.cc.
Referenced by FCALRunAction::FCALRunAction(), and G4ScoreNtupleWriter::OpenFile().
GetFileType()
G4String G4VAnalysisManager::GetFileType () const
Referenced by RMC01AnalysisManager::Book().
GetFirstH1Id()
G4int G4VAnalysisManager::GetFirstH1Id () const
Definition at line 1004 of file G4VAnalysisManager.cc.
GetFirstH2Id()
G4int G4VAnalysisManager::GetFirstH2Id () const
Definition at line 1012 of file G4VAnalysisManager.cc.
GetFirstH3Id()
G4int G4VAnalysisManager::GetFirstH3Id () const
Definition at line 1020 of file G4VAnalysisManager.cc.
GetFirstNtupleColumnId()
G4int G4VAnalysisManager::GetFirstNtupleColumnId () const
Definition at line 1052 of file G4VAnalysisManager.cc.
GetFirstNtupleId()
G4int G4VAnalysisManager::GetFirstNtupleId () const
Definition at line 1044 of file G4VAnalysisManager.cc.
GetFirstP1Id()
G4int G4VAnalysisManager::GetFirstP1Id () const
Definition at line 1028 of file G4VAnalysisManager.cc.
GetFirstP2Id()
G4int G4VAnalysisManager::GetFirstP2Id () const
Definition at line 1036 of file G4VAnalysisManager.cc.
GetH1Activation()
G4bool G4VAnalysisManager::GetH1Activation (G4int id) const
GetH1Ascii()
G4bool G4VAnalysisManager::GetH1Ascii (G4int id) const
GetH1Id()
G4int G4VAnalysisManager::GetH1Id (const G4String & name, G4bool warn = true) const
Referenced by CCalRunAction::BeginOfRunAction(), CCalSteppingAction::endOfEvent(), and CCalEventAction::EndOfEventAction().
GetH1Name()
G4String G4VAnalysisManager::GetH1Name (G4int id) const
GetH1Nbins()
G4int G4VAnalysisManager::GetH1Nbins (G4int id) const
GetH1Plotting()
G4bool G4VAnalysisManager::GetH1Plotting (G4int id) const
GetH1Title()
G4String G4VAnalysisManager::GetH1Title (G4int id) const
GetH1Unit()
G4double G4VAnalysisManager::GetH1Unit (G4int id) const
GetH1Width()
G4double G4VAnalysisManager::GetH1Width (G4int id) const
GetH1XAxisTitle()
G4String G4VAnalysisManager::GetH1XAxisTitle (G4int id) const
GetH1Xmax()
G4double G4VAnalysisManager::GetH1Xmax (G4int id) const
GetH1Xmin()
G4double G4VAnalysisManager::GetH1Xmin (G4int id) const
GetH1YAxisTitle()
G4String G4VAnalysisManager::GetH1YAxisTitle (G4int id) const
GetH2Activation()
G4bool G4VAnalysisManager::GetH2Activation (G4int id) const
GetH2Ascii()
G4bool G4VAnalysisManager::GetH2Ascii (G4int id) const
GetH2Id()
G4int G4VAnalysisManager::GetH2Id (const G4String & name, G4bool warn = true) const
GetH2Name()
G4String G4VAnalysisManager::GetH2Name (G4int id) const
GetH2Nxbins()
G4int G4VAnalysisManager::GetH2Nxbins (G4int id) const
GetH2Nybins()
G4int G4VAnalysisManager::GetH2Nybins (G4int id) const
GetH2Plotting()
G4bool G4VAnalysisManager::GetH2Plotting (G4int id) const
GetH2Title()
G4String G4VAnalysisManager::GetH2Title (G4int id) const
GetH2XAxisTitle()
G4String G4VAnalysisManager::GetH2XAxisTitle (G4int id) const
GetH2Xmax()
G4double G4VAnalysisManager::GetH2Xmax (G4int id) const
GetH2Xmin()
G4double G4VAnalysisManager::GetH2Xmin (G4int id) const
GetH2XUnit()
G4double G4VAnalysisManager::GetH2XUnit (G4int id) const
GetH2XWidth()
G4double G4VAnalysisManager::GetH2XWidth (G4int id) const
GetH2YAxisTitle()
G4String G4VAnalysisManager::GetH2YAxisTitle (G4int id) const
GetH2Ymax()
G4double G4VAnalysisManager::GetH2Ymax (G4int id) const
GetH2Ymin()
G4double G4VAnalysisManager::GetH2Ymin (G4int id) const
GetH2YUnit()
G4double G4VAnalysisManager::GetH2YUnit (G4int id) const
GetH2YWidth()
G4double G4VAnalysisManager::GetH2YWidth (G4int id) const
GetH2ZAxisTitle()
G4String G4VAnalysisManager::GetH2ZAxisTitle (G4int id) const
GetH3Activation()
G4bool G4VAnalysisManager::GetH3Activation (G4int id) const
GetH3Ascii()
G4bool G4VAnalysisManager::GetH3Ascii (G4int id) const
GetH3Id()
G4int G4VAnalysisManager::GetH3Id (const G4String & name, G4bool warn = true) const
GetH3Name()
G4String G4VAnalysisManager::GetH3Name (G4int id) const
GetH3Nxbins()
G4int G4VAnalysisManager::GetH3Nxbins (G4int id) const
GetH3Nybins()
G4int G4VAnalysisManager::GetH3Nybins (G4int id) const
GetH3Nzbins()
G4int G4VAnalysisManager::GetH3Nzbins (G4int id) const
GetH3Plotting()
G4bool G4VAnalysisManager::GetH3Plotting (G4int id) const
GetH3Title()
G4String G4VAnalysisManager::GetH3Title (G4int id) const
GetH3XAxisTitle()
G4String G4VAnalysisManager::GetH3XAxisTitle (G4int id) const
GetH3Xmax()
G4double G4VAnalysisManager::GetH3Xmax (G4int id) const
GetH3Xmin()
G4double G4VAnalysisManager::GetH3Xmin (G4int id) const
GetH3XUnit()
G4double G4VAnalysisManager::GetH3XUnit (G4int id) const
GetH3XWidth()
G4double G4VAnalysisManager::GetH3XWidth (G4int id) const
GetH3YAxisTitle()
G4String G4VAnalysisManager::GetH3YAxisTitle (G4int id) const
GetH3Ymax()
G4double G4VAnalysisManager::GetH3Ymax (G4int id) const
GetH3Ymin()
G4double G4VAnalysisManager::GetH3Ymin (G4int id) const
GetH3YUnit()
G4double G4VAnalysisManager::GetH3YUnit (G4int id) const
GetH3YWidth()
G4double G4VAnalysisManager::GetH3YWidth (G4int id) const
GetH3ZAxisTitle()
G4String G4VAnalysisManager::GetH3ZAxisTitle (G4int id) const
GetH3Zmax()
G4double G4VAnalysisManager::GetH3Zmax (G4int id) const
GetH3Zmin()
G4double G4VAnalysisManager::GetH3Zmin (G4int id) const
GetH3ZUnit()
G4double G4VAnalysisManager::GetH3ZUnit (G4int id) const
GetH3ZWidth()
G4double G4VAnalysisManager::GetH3ZWidth (G4int id) const
GetHistoDirectoryName()
G4String G4VAnalysisManager::GetHistoDirectoryName () const
Definition at line 280 of file G4VAnalysisManager.cc.
GetNofH1s()
G4int G4VAnalysisManager::GetNofH1s () const
Definition at line 1060 of file G4VAnalysisManager.cc.
Referenced by RMC01AnalysisManager::Save().
GetNofH2s()
G4int G4VAnalysisManager::GetNofH2s () const
Definition at line 1066 of file G4VAnalysisManager.cc.
Referenced by RMC01AnalysisManager::Save().
GetNofH3s()
G4int G4VAnalysisManager::GetNofH3s () const
Definition at line 1072 of file G4VAnalysisManager.cc.
GetNofNtuples()
G4int G4VAnalysisManager::GetNofNtuples () const
Definition at line 1090 of file G4VAnalysisManager.cc.
GetNofP1s()
G4int G4VAnalysisManager::GetNofP1s () const
Definition at line 1078 of file G4VAnalysisManager.cc.
GetNofP2s()
G4int G4VAnalysisManager::GetNofP2s () const
Definition at line 1084 of file G4VAnalysisManager.cc.
GetNtupleActivation()
G4bool G4VAnalysisManager::GetNtupleActivation (G4int id) const
GetNtupleDirectoryName()
G4String G4VAnalysisManager::GetNtupleDirectoryName () const
Definition at line 286 of file G4VAnalysisManager.cc.
GetP1Activation()
G4bool G4VAnalysisManager::GetP1Activation (G4int id) const
GetP1Ascii()
G4bool G4VAnalysisManager::GetP1Ascii (G4int id) const
GetP1Id()
G4int G4VAnalysisManager::GetP1Id (const G4String & name, G4bool warn = true) const
GetP1Name()
G4String G4VAnalysisManager::GetP1Name (G4int id) const
GetP1Nbins()
G4int G4VAnalysisManager::GetP1Nbins (G4int id) const
GetP1Plotting()
G4bool G4VAnalysisManager::GetP1Plotting (G4int id) const
GetP1Title()
G4String G4VAnalysisManager::GetP1Title (G4int id) const
GetP1XAxisTitle()
G4String G4VAnalysisManager::GetP1XAxisTitle (G4int id) const
GetP1Xmax()
G4double G4VAnalysisManager::GetP1Xmax (G4int id) const
GetP1Xmin()
G4double G4VAnalysisManager::GetP1Xmin (G4int id) const
GetP1XUnit()
G4double G4VAnalysisManager::GetP1XUnit (G4int id) const
GetP1XWidth()
G4double G4VAnalysisManager::GetP1XWidth (G4int id) const
GetP1YAxisTitle()
G4String G4VAnalysisManager::GetP1YAxisTitle (G4int id) const
GetP1Ymax()
G4double G4VAnalysisManager::GetP1Ymax (G4int id) const
GetP1Ymin()
G4double G4VAnalysisManager::GetP1Ymin (G4int id) const
GetP1YUnit()
G4double G4VAnalysisManager::GetP1YUnit (G4int id) const
GetP1ZAxisTitle()
G4String G4VAnalysisManager::GetP1ZAxisTitle (G4int id) const
GetP2Activation()
G4bool G4VAnalysisManager::GetP2Activation (G4int id) const
GetP2Ascii()
G4bool G4VAnalysisManager::GetP2Ascii (G4int id) const
GetP2Id()
G4int G4VAnalysisManager::GetP2Id (const G4String & name, G4bool warn = true) const
GetP2Name()
G4String G4VAnalysisManager::GetP2Name (G4int id) const
GetP2Nxbins()
G4int G4VAnalysisManager::GetP2Nxbins (G4int id) const
GetP2Nybins()
G4int G4VAnalysisManager::GetP2Nybins (G4int id) const
GetP2Plotting()
G4bool G4VAnalysisManager::GetP2Plotting (G4int id) const
GetP2Title()
G4String G4VAnalysisManager::GetP2Title (G4int id) const
GetP2XAxisTitle()
G4String G4VAnalysisManager::GetP2XAxisTitle (G4int id) const
GetP2Xmax()
G4double G4VAnalysisManager::GetP2Xmax (G4int id) const
GetP2Xmin()
G4double G4VAnalysisManager::GetP2Xmin (G4int id) const
GetP2XUnit()
G4double G4VAnalysisManager::GetP2XUnit (G4int id) const
GetP2XWidth()
G4double G4VAnalysisManager::GetP2XWidth (G4int id) const
GetP2YAxisTitle()
G4String G4VAnalysisManager::GetP2YAxisTitle (G4int id) const
GetP2Ymax()
G4double G4VAnalysisManager::GetP2Ymax (G4int id) const
GetP2Ymin()
G4double G4VAnalysisManager::GetP2Ymin (G4int id) const
GetP2YUnit()
G4double G4VAnalysisManager::GetP2YUnit (G4int id) const
GetP2YWidth()
G4double G4VAnalysisManager::GetP2YWidth (G4int id) const
GetP2ZAxisTitle()
G4String G4VAnalysisManager::GetP2ZAxisTitle (G4int id) const
GetP2Zmax()
G4double G4VAnalysisManager::GetP2Zmax (G4int id) const
GetP2Zmin()
G4double G4VAnalysisManager::GetP2Zmin (G4int id) const
GetP2ZUnit()
G4double G4VAnalysisManager::GetP2ZUnit (G4int id) const
GetType()
G4String G4VAnalysisManager::GetType () const
GetVerboseLevel()
G4int G4VAnalysisManager::GetVerboseLevel () const
IsActive()
G4bool G4VAnalysisManager::IsActive () const
Definition at line 966 of file G4VAnalysisManager.cc.
Referenced by LXeRunAction::BeginOfRunAction(), and LXeRunAction::EndOfRunAction().
IsAscii()
G4bool G4VAnalysisManager::IsAscii () const
Definition at line 980 of file G4VAnalysisManager.cc.
Referenced by G4Hdf5AnalysisManager::WriteImpl(), G4XmlAnalysisManager::WriteImpl(), and G4RootAnalysisManager::WriteImpl().
IsOpenFile()
G4bool G4VAnalysisManager::IsOpenFile () const
Definition at line 244 of file G4VAnalysisManager.cc.
Referenced by G4ScoreNtupleWriter::OpenFile().
IsOpenFileImpl()
virtual G4bool G4VAnalysisManager::IsOpenFileImpl () const protected pure virtual
Implemented in G4RootAnalysisManager, G4CsvAnalysisManager, G4Hdf5AnalysisManager, and G4XmlAnalysisManager.
Referenced by IsOpenFile().
IsPlotting()
G4bool G4VAnalysisManager::IsPlotting () const
Definition at line 992 of file G4VAnalysisManager.cc.
Referenced by Write().
Merge()
G4bool G4VAnalysisManager::Merge (tools::histo::hmpi * hmpi)
Definition at line 232 of file G4VAnalysisManager.cc.
Referenced by G4MPIhistoMerger::Merge().
MergeImpl()
virtual G4bool G4VAnalysisManager::MergeImpl (tools::histo::hmpi * hmpi) protected pure virtual
Implemented in G4ToolsAnalysisManager.
Referenced by Merge().
OpenFile()
G4bool G4VAnalysisManager::OpenFile (const G4String & fileName = "")
Definition at line 191 of file G4VAnalysisManager.cc.
Referenced by GammaRayTelAnalysis::BeginOfRun(), LXeRunAction::BeginOfRunAction(), FCALRunAction::BeginOfRunAction(), UltraRunAction::BeginOfRunAction(), CCalRunAction::Book(), XrayFluoAnalysisManager::book(), XrayTelAnalysis::book(), PurgMagRunAction::Book(), Histo::Book(), DMXRunAction::Book(), RMC01AnalysisManager::Book(), Analysis::OpenFile(), G4ScoreNtupleWriter::OpenFile(), Par02Output::StartAnalysis(), HadrontherapyLet::StoreLetAscii(), G4PhysChemIO::G4Analysis::WriteInto(), and ScoreSpecies::WriteWithAnalysisManager().
OpenFileImpl()
virtual G4bool G4VAnalysisManager::OpenFileImpl (const G4String & fileName) protected pure virtual
Implemented in G4RootAnalysisManager, G4CsvAnalysisManager, G4Hdf5AnalysisManager, G4XmlAnalysisManager, and G4RootMpiAnalysisManager.
Referenced by OpenFile().
Plot()
G4bool G4VAnalysisManager::Plot ()
Definition at line 238 of file G4VAnalysisManager.cc.
PlotImpl()
virtual G4bool G4VAnalysisManager::PlotImpl () protected pure virtual
Implemented in G4ToolsAnalysisManager.
Referenced by Plot(), and Write().
ScaleH1()
G4bool G4VAnalysisManager::ScaleH1 (G4int id, G4double factor)
Definition at line 526 of file G4VAnalysisManager.cc.
Referenced by RMC01AnalysisManager::Save().
ScaleH2()
G4bool G4VAnalysisManager::ScaleH2 (G4int id, G4double factor)
Definition at line 532 of file G4VAnalysisManager.cc.
Referenced by RMC01AnalysisManager::Save().
ScaleH3()
G4bool G4VAnalysisManager::ScaleH3 (G4int id, G4double factor)
Definition at line 538 of file G4VAnalysisManager.cc.
ScaleP1()
G4bool G4VAnalysisManager::ScaleP1 (G4int id, G4double factor)
Definition at line 724 of file G4VAnalysisManager.cc.
ScaleP2()
G4bool G4VAnalysisManager::ScaleP2 (G4int id, G4double factor)
Definition at line 730 of file G4VAnalysisManager.cc.
SetActivation()
void G4VAnalysisManager::SetActivation (G4bool activation)
Definition at line 958 of file G4VAnalysisManager.cc.
Referenced by LXeHistoManager::Book(), and G4AnalysisMessenger::SetNewValue().
SetCompressionLevel()
void G4VAnalysisManager::SetCompressionLevel (G4int level)
Definition at line 268 of file G4VAnalysisManager.cc.
Referenced by G4AnalysisMessenger::SetNewValue().
SetFileManager()
void G4VAnalysisManager::SetFileManager (std::shared_ptr< G4VFileManager > fileManager) protected
Definition at line 124 of file G4VAnalysisManager.cc.
Referenced by G4CsvAnalysisManager::G4CsvAnalysisManager(), G4Hdf5AnalysisManager::G4Hdf5AnalysisManager(), G4RootAnalysisManager::G4RootAnalysisManager(), and G4XmlAnalysisManager::G4XmlAnalysisManager().
SetFileName()
G4bool G4VAnalysisManager::SetFileName (const G4String & fileName)
Definition at line 250 of file G4VAnalysisManager.cc.
Referenced by LXeHistoManager::Book(), FCALRunAction::FCALRunAction(), G4ScoreNtupleWriter::OpenFile(), G4FileMessenger::SetNewValue(), Par02Output::StartAnalysis(), and G4ScoreNtupleWriter::Write().
SetFirstH1Id()
G4bool G4VAnalysisManager::SetFirstH1Id (G4int firstId)
Definition at line 900 of file G4VAnalysisManager.cc.
Referenced by SetFirstHistoId().
SetFirstH2Id()
G4bool G4VAnalysisManager::SetFirstH2Id (G4int firstId)
Definition at line 906 of file G4VAnalysisManager.cc.
Referenced by SetFirstHistoId().
SetFirstH3Id()
G4bool G4VAnalysisManager::SetFirstH3Id (G4int firstId)
Definition at line 912 of file G4VAnalysisManager.cc.
Referenced by SetFirstHistoId().
SetFirstHistoId()
G4bool G4VAnalysisManager::SetFirstHistoId (G4int firstId)
Definition at line 883 of file G4VAnalysisManager.cc.
Referenced by GammaRayTelAnalysis::BeginOfRun(), UltraRunAction::BeginOfRunAction(), CCalRunAction::Book(), XrayFluoAnalysisManager::book(), XrayTelAnalysis::book(), DMXRunAction::Book(), RMC01AnalysisManager::Book(), FCALRunAction::FCALRunAction(), and HadrontherapyLet::StoreLetAscii().
SetFirstNtupleColumnId()
G4bool G4VAnalysisManager::SetFirstNtupleColumnId (G4int firstId)
Definition at line 950 of file G4VAnalysisManager.cc.
SetFirstNtupleId()
G4bool G4VAnalysisManager::SetFirstNtupleId (G4int firstId)
Definition at line 944 of file G4VAnalysisManager.cc.
Referenced by CCalRunAction::Book(), XrayFluoAnalysisManager::book(), PurgMagRunAction::Book(), DMXRunAction::Book(), and HadrontherapyLet::StoreLetAscii().
SetFirstP1Id()
G4bool G4VAnalysisManager::SetFirstP1Id (G4int firstId)
Definition at line 932 of file G4VAnalysisManager.cc.
Referenced by SetFirstProfileId().
SetFirstP2Id()
G4bool G4VAnalysisManager::SetFirstP2Id (G4int firstId)
Definition at line 938 of file G4VAnalysisManager.cc.
Referenced by SetFirstProfileId().
SetFirstProfileId()
G4bool G4VAnalysisManager::SetFirstProfileId (G4int firstId)
Definition at line 918 of file G4VAnalysisManager.cc.
SetH1() [1/2]
G4bool G4VAnalysisManager::SetH1 (G4int id, const std::vector< G4double > & edges, const G4String & unitName = "none", const G4String & fcnName = "none")
Definition at line 433 of file G4VAnalysisManager.cc.
SetH1() [2/2]
G4bool G4VAnalysisManager::SetH1 (G4int id, G4int nbins, G4double xmin, G4double xmax, const G4String & unitName = "none", const G4String & fcnName = "none", const G4String & binSchemeName = "linear")
Definition at line 421 of file G4VAnalysisManager.cc.
Referenced by G4H1Messenger::SetNewValue().
SetH1Activation() [1/2]
void G4VAnalysisManager::SetH1Activation (G4bool activation)
Definition at line 1106 of file G4VAnalysisManager.cc.
Referenced by LXeHistoManager::Book().
SetH1Activation() [2/2]
void G4VAnalysisManager::SetH1Activation (G4int id, G4bool activation)
Definition at line 1098 of file G4VAnalysisManager.cc.
SetH1Ascii()
void G4VAnalysisManager::SetH1Ascii (G4int id, G4bool ascii)
Definition at line 1114 of file G4VAnalysisManager.cc.
Referenced by RMC01AnalysisManager::Save().
SetH1Manager()
void G4VAnalysisManager::SetH1Manager (G4VH1Manager * h1Manager) protected
Definition at line 77 of file G4VAnalysisManager.cc.
Referenced by G4ToolsAnalysisManager::G4ToolsAnalysisManager().
SetH1Plotting()
void G4VAnalysisManager::SetH1Plotting (G4int id, G4bool plotting)
Definition at line 1120 of file G4VAnalysisManager.cc.
SetH1Title()
G4bool G4VAnalysisManager::SetH1Title (G4int id, const G4String & title)
Referenced by G4H1Messenger::SetNewValue().
SetH1XAxisTitle()
G4bool G4VAnalysisManager::SetH1XAxisTitle (G4int id, const G4String & title)
Referenced by Par02Output::CreateHistograms(), and G4H1Messenger::SetNewValue().
SetH1YAxisTitle()
G4bool G4VAnalysisManager::SetH1YAxisTitle (G4int id, const G4String & title)
Referenced by Par02Output::CreateHistograms(), and G4H1Messenger::SetNewValue().
SetH2() [1/2]
G4bool G4VAnalysisManager::SetH2 (G4int id, const std::vector< G4double > & xedges, const std::vector< G4double > & yedges, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none")
Definition at line 463 of file G4VAnalysisManager.cc.
SetH2() [2/2]
G4bool G4VAnalysisManager::SetH2 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & xbinSchemeName = "linear", const G4String & ybinSchemeName = "linear")
Definition at line 443 of file G4VAnalysisManager.cc.
Referenced by G4H2Messenger::SetNewValue().
SetH2Activation() [1/2]
void G4VAnalysisManager::SetH2Activation (G4bool activation)
Definition at line 1134 of file G4VAnalysisManager.cc.
SetH2Activation() [2/2]
void G4VAnalysisManager::SetH2Activation (G4int id, G4bool activation)
Definition at line 1126 of file G4VAnalysisManager.cc.
SetH2Ascii()
void G4VAnalysisManager::SetH2Ascii (G4int id, G4bool ascii)
Definition at line 1142 of file G4VAnalysisManager.cc.
SetH2Manager()
void G4VAnalysisManager::SetH2Manager (G4VH2Manager * h2Manager) protected
Definition at line 85 of file G4VAnalysisManager.cc.
Referenced by G4ToolsAnalysisManager::G4ToolsAnalysisManager().
SetH2Plotting()
void G4VAnalysisManager::SetH2Plotting (G4int id, G4bool plotting)
Definition at line 1148 of file G4VAnalysisManager.cc.
SetH2Title()
G4bool G4VAnalysisManager::SetH2Title (G4int id, const G4String & title)
Referenced by G4H2Messenger::SetNewValue().
SetH2XAxisTitle()
G4bool G4VAnalysisManager::SetH2XAxisTitle (G4int id, const G4String & title)
Referenced by G4H2Messenger::SetNewValue().
SetH2YAxisTitle()
G4bool G4VAnalysisManager::SetH2YAxisTitle (G4int id, const G4String & title)
Referenced by G4H2Messenger::SetNewValue().
SetH2ZAxisTitle()
G4bool G4VAnalysisManager::SetH2ZAxisTitle (G4int id, const G4String & title)
Referenced by G4H2Messenger::SetNewValue().
SetH3() [1/2]
G4bool G4VAnalysisManager::SetH3 (G4int id, const std::vector< G4double > & xedges, const std::vector< G4double > & yedges, const std::vector< G4double > & zedges, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none")
Definition at line 507 of file G4VAnalysisManager.cc.
SetH3() [2/2]
G4bool G4VAnalysisManager::SetH3 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nzbins, G4double zmin, G4double zmax, G4int nybins, G4double ymin, G4double ymax, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none", const G4String & xbinSchemeName = "linear", const G4String & ybinSchemeName = "linear", const G4String & zbinSchemeName = "linear")
Definition at line 477 of file G4VAnalysisManager.cc.
Referenced by G4H3Messenger::SetNewValue().
SetH3Activation() [1/2]
void G4VAnalysisManager::SetH3Activation (G4bool activation)
Definition at line 1162 of file G4VAnalysisManager.cc.
SetH3Activation() [2/2]
void G4VAnalysisManager::SetH3Activation (G4int id, G4bool activation)
Definition at line 1154 of file G4VAnalysisManager.cc.
SetH3Ascii()
void G4VAnalysisManager::SetH3Ascii (G4int id, G4bool ascii)
Definition at line 1170 of file G4VAnalysisManager.cc.
SetH3Manager()
void G4VAnalysisManager::SetH3Manager (G4VH3Manager * h3Manager) protected
Definition at line 93 of file G4VAnalysisManager.cc.
Referenced by G4ToolsAnalysisManager::G4ToolsAnalysisManager().
SetH3Plotting()
void G4VAnalysisManager::SetH3Plotting (G4int id, G4bool plotting)
Definition at line 1176 of file G4VAnalysisManager.cc.
SetH3Title()
G4bool G4VAnalysisManager::SetH3Title (G4int id, const G4String & title)
Referenced by G4H3Messenger::SetNewValue().
SetH3XAxisTitle()
G4bool G4VAnalysisManager::SetH3XAxisTitle (G4int id, const G4String & title)
Referenced by G4H3Messenger::SetNewValue().
SetH3YAxisTitle()
G4bool G4VAnalysisManager::SetH3YAxisTitle (G4int id, const G4String & title)
Referenced by G4H3Messenger::SetNewValue().
SetH3ZAxisTitle()
G4bool G4VAnalysisManager::SetH3ZAxisTitle (G4int id, const G4String & title)
Referenced by G4H3Messenger::SetNewValue().
SetHistoDirectoryName()
G4bool G4VAnalysisManager::SetHistoDirectoryName (const G4String & dirName)
Definition at line 256 of file G4VAnalysisManager.cc.
Referenced by RMC01AnalysisManager::Book(), and G4FileMessenger::SetNewValue().
SetNtupleActivation() [1/2]
void G4VAnalysisManager::SetNtupleActivation (G4bool activation)
Definition at line 1246 of file G4VAnalysisManager.cc.
Referenced by G4NtupleMessenger::SetNewValue().
SetNtupleActivation() [2/2]
void G4VAnalysisManager::SetNtupleActivation (G4int id, G4bool activation)
Definition at line 1238 of file G4VAnalysisManager.cc.
SetNtupleDirectoryName()
G4bool G4VAnalysisManager::SetNtupleDirectoryName (const G4String & dirName)
Definition at line 262 of file G4VAnalysisManager.cc.
Referenced by G4FileMessenger::SetNewValue().
SetNtupleManager()
void G4VAnalysisManager::SetNtupleManager (G4VNtupleManager * ntupleManager) protected
Definition at line 117 of file G4VAnalysisManager.cc.
Referenced by G4RootMpiAnalysisManager::CreateMpiNtupleManagers(), G4RootAnalysisManager::CreateNtupleManagers(), G4CsvAnalysisManager::G4CsvAnalysisManager(), G4Hdf5AnalysisManager::G4Hdf5AnalysisManager(), and G4XmlAnalysisManager::G4XmlAnalysisManager().
SetP1() [1/2]
G4bool G4VAnalysisManager::SetP1 (G4int id, const std::vector< G4double > & edges, G4double ymin = 0, G4double ymax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none")
Definition at line 655 of file G4VAnalysisManager.cc.
SetP1() [2/2]
G4bool G4VAnalysisManager::SetP1 (G4int id, G4int nbins, G4double xmin, G4double xmax, G4double ymin = 0, G4double ymax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & xbinSchemeName = "linear")
Definition at line 635 of file G4VAnalysisManager.cc.
Referenced by G4P1Messenger::SetNewValue().
SetP1Activation() [1/2]
void G4VAnalysisManager::SetP1Activation (G4bool activation)
Definition at line 1190 of file G4VAnalysisManager.cc.
SetP1Activation() [2/2]
void G4VAnalysisManager::SetP1Activation (G4int id, G4bool activation)
Definition at line 1182 of file G4VAnalysisManager.cc.
SetP1Ascii()
void G4VAnalysisManager::SetP1Ascii (G4int id, G4bool ascii)
Definition at line 1198 of file G4VAnalysisManager.cc.
SetP1Manager()
void G4VAnalysisManager::SetP1Manager (G4VP1Manager * p1Manager) protected
Definition at line 101 of file G4VAnalysisManager.cc.
Referenced by G4ToolsAnalysisManager::G4ToolsAnalysisManager().
SetP1Plotting()
void G4VAnalysisManager::SetP1Plotting (G4int id, G4bool plotting)
Definition at line 1204 of file G4VAnalysisManager.cc.
SetP1Title()
G4bool G4VAnalysisManager::SetP1Title (G4int id, const G4String & title)
Referenced by G4P1Messenger::SetNewValue().
SetP1XAxisTitle()
G4bool G4VAnalysisManager::SetP1XAxisTitle (G4int id, const G4String & title)
Referenced by G4P1Messenger::SetNewValue().
SetP1YAxisTitle()
G4bool G4VAnalysisManager::SetP1YAxisTitle (G4int id, const G4String & title)
Referenced by G4P1Messenger::SetNewValue().
SetP2() [1/2]
G4bool G4VAnalysisManager::SetP2 (G4int id, const std::vector< G4double > & xedges, const std::vector< G4double > & yedges, G4double zmin = 0, G4double zmax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none")
Definition at line 700 of file G4VAnalysisManager.cc.
SetP2() [2/2]
G4bool G4VAnalysisManager::SetP2 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4double zmin = 0, G4double zmax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none", const G4String & xbinSchemeName = "linear", const G4String & ybinSchemeName = "linear")
Definition at line 672 of file G4VAnalysisManager.cc.
Referenced by G4P2Messenger::SetNewValue().
SetP2Activation() [1/2]
void G4VAnalysisManager::SetP2Activation (G4bool activation)
Definition at line 1218 of file G4VAnalysisManager.cc.
SetP2Activation() [2/2]
void G4VAnalysisManager::SetP2Activation (G4int id, G4bool activation)
Definition at line 1210 of file G4VAnalysisManager.cc.
SetP2Ascii()
void G4VAnalysisManager::SetP2Ascii (G4int id, G4bool ascii)
Definition at line 1226 of file G4VAnalysisManager.cc.
SetP2Manager()
void G4VAnalysisManager::SetP2Manager (G4VP2Manager * p2Manager) protected
Definition at line 109 of file G4VAnalysisManager.cc.
Referenced by G4ToolsAnalysisManager::G4ToolsAnalysisManager().
SetP2Plotting()
void G4VAnalysisManager::SetP2Plotting (G4int id, G4bool plotting)
Definition at line 1232 of file G4VAnalysisManager.cc.
SetP2Title()
G4bool G4VAnalysisManager::SetP2Title (G4int id, const G4String & title)
Referenced by G4P2Messenger::SetNewValue().
SetP2XAxisTitle()
G4bool G4VAnalysisManager::SetP2XAxisTitle (G4int id, const G4String & title)
Referenced by G4P2Messenger::SetNewValue().
SetP2YAxisTitle()
G4bool G4VAnalysisManager::SetP2YAxisTitle (G4int id, const G4String & title)
Referenced by G4P2Messenger::SetNewValue().
SetP2ZAxisTitle()
G4bool G4VAnalysisManager::SetP2ZAxisTitle (G4int id, const G4String & title)
Referenced by G4P2Messenger::SetNewValue().
SetPlotManager()
void G4VAnalysisManager::SetPlotManager (std::shared_ptr< G4PlotManager > plotManager) protected
Definition at line 130 of file G4VAnalysisManager.cc.
Referenced by G4ToolsAnalysisManager::G4ToolsAnalysisManager().
SetVerboseLevel()
void G4VAnalysisManager::SetVerboseLevel (G4int verboseLevel)
Definition at line 1256 of file G4VAnalysisManager.cc.
Referenced by CCalRunAction::Book(), LXeHistoManager::Book(), XrayFluoAnalysisManager::book(), G4ScoreNtupleWriter::CreateAnalysisManager(), G4AnalysisMessenger::SetNewValue(), G4ScoreNtupleWriter::SetVerboseLevel(), Par02Output::StartAnalysis(), and HadrontherapyLet::StoreLetAscii().
Write()
G4bool G4VAnalysisManager::Write ()
Definition at line 210 of file G4VAnalysisManager.cc.
Referenced by Par02Output::EndAnalysis(), GammaRayTelAnalysis::EndOfRun(), LXeRunAction::EndOfRunAction(), FCALRunAction::EndOfRunAction(), UltraRunAction::EndOfRunAction(), XrayFluoAnalysisManager::finish(), XrayTelAnalysis::finish(), main(), Analysis::Save(), Histo::Save(), RMC01AnalysisManager::Save(), HadrontherapyLet::StoreLetAscii(), G4ScoreNtupleWriter::Write(), and ScoreSpecies::WriteWithAnalysisManager().
WriteAscii()
G4bool G4VAnalysisManager::WriteAscii (const G4String & fileName) protected
Definition at line 136 of file G4VAnalysisManager.cc.
Referenced by G4Hdf5AnalysisManager::WriteImpl(), G4XmlAnalysisManager::WriteImpl(), and G4RootAnalysisManager::WriteImpl().
WriteImpl()
virtual G4bool G4VAnalysisManager::WriteImpl () protected pure virtual
Implemented in G4RootAnalysisManager, G4CsvAnalysisManager, G4Hdf5AnalysisManager, and G4XmlAnalysisManager.
Referenced by Write().
Field Documentation
fH1HnManager
std::shared_ptr<G4HnManager> G4VAnalysisManager::fH1HnManager private
Definition at line 618 of file G4VAnalysisManager.hh.
Referenced by GetFirstH1Id(), GetNofH1s(), IsActive(), IsAscii(), IsPlotting(), SetFirstH1Id(), SetH1Activation(), SetH1Ascii(), SetH1Manager(), and SetH1Plotting().
fH2HnManager
std::shared_ptr<G4HnManager> G4VAnalysisManager::fH2HnManager private
Definition at line 619 of file G4VAnalysisManager.hh.
Referenced by GetFirstH2Id(), GetNofH2s(), IsActive(), IsAscii(), IsPlotting(), SetFirstH2Id(), SetH2Activation(), SetH2Ascii(), SetH2Manager(), and SetH2Plotting().
fH3HnManager
std::shared_ptr<G4HnManager> G4VAnalysisManager::fH3HnManager private
Definition at line 620 of file G4VAnalysisManager.hh.
Referenced by GetFirstH3Id(), GetNofH3s(), IsActive(), IsAscii(), IsPlotting(), SetFirstH3Id(), SetH3Activation(), SetH3Ascii(), SetH3Manager(), and SetH3Plotting().
fMessenger
std::unique_ptr<G4AnalysisMessenger> G4VAnalysisManager::fMessenger private
Definition at line 617 of file G4VAnalysisManager.hh.
Referenced by SetH1Manager(), SetH2Manager(), SetH3Manager(), SetP1Manager(), and SetP2Manager().
fP1HnManager
std::shared_ptr<G4HnManager> G4VAnalysisManager::fP1HnManager private
Definition at line 621 of file G4VAnalysisManager.hh.
Referenced by GetFirstP1Id(), GetNofP1s(), IsActive(), IsAscii(), IsPlotting(), SetFirstP1Id(), SetP1Activation(), SetP1Ascii(), SetP1Manager(), and SetP1Plotting().
fP2HnManager
std::shared_ptr<G4HnManager> G4VAnalysisManager::fP2HnManager private
Definition at line 622 of file G4VAnalysisManager.hh.
Referenced by GetFirstP2Id(), GetNofP2s(), IsActive(), IsAscii(), IsPlotting(), SetFirstP2Id(), SetP2Activation(), SetP2Ascii(), SetP2Manager(), and SetP2Plotting().
fPlotManager
std::shared_ptr<G4PlotManager> G4VAnalysisManager::fPlotManager protected
Definition at line 613 of file G4VAnalysisManager.hh.
Referenced by G4ToolsAnalysisManager::PlotImpl(), and SetPlotManager().
fState
G4AnalysisManagerState G4VAnalysisManager::fState protected
Definition at line 611 of file G4VAnalysisManager.hh.
Referenced by G4RootAnalysisManager::ClearNtupleManagers(), G4XmlAnalysisManager::CloseFileImpl(), G4RootAnalysisManager::CloseFileImpl(), G4RootMpiAnalysisManager::CreateMpiNtupleManagers(), G4RootAnalysisManager::CreateNtupleManagers(), G4CsvAnalysisManager::G4CsvAnalysisManager(), G4Hdf5AnalysisManager::G4Hdf5AnalysisManager(), G4RootAnalysisManager::G4RootAnalysisManager(), G4ToolsAnalysisManager::G4ToolsAnalysisManager(), G4XmlAnalysisManager::G4XmlAnalysisManager(), GetCompressionLevel(), IsActive(), G4ToolsAnalysisManager::MergeImpl(), G4RootMpiAnalysisManager::OpenFileImpl(), G4Hdf5AnalysisManager::OpenFileImpl(), G4XmlAnalysisManager::OpenFileImpl(), G4RootAnalysisManager::OpenFileImpl(), SetActivation(), SetCompressionLevel(), G4RootMpiAnalysisManager::SetMpiNtupleMergingMode(), G4RootAnalysisManager::SetNtupleMergingMode(), SetVerboseLevel(), WriteAscii(), G4Hdf5AnalysisManager::WriteImpl(), G4XmlAnalysisManager::WriteImpl(), G4CsvAnalysisManager::WriteImpl(), G4RootMpiAnalysisManager::WriteNtuple(), G4RootAnalysisManager::WriteNtuple(), G4CsvAnalysisManager::~G4CsvAnalysisManager(), G4Hdf5AnalysisManager::~G4Hdf5AnalysisManager(), G4RootAnalysisManager::~G4RootAnalysisManager(), and G4XmlAnalysisManager::~G4XmlAnalysisManager().
fVFileManager
std::shared_ptr<G4VFileManager> G4VAnalysisManager::fVFileManager protected
Definition at line 612 of file G4VAnalysisManager.hh.
Referenced by GetFileName(), GetHistoDirectoryName(), GetNtupleDirectoryName(), OpenFile(), G4ToolsAnalysisManager::PlotImpl(), SetFileManager(), SetFileName(), SetHistoDirectoryName(), and SetNtupleDirectoryName().
fVH1Manager
std::unique_ptr<G4VH1Manager> G4VAnalysisManager::fVH1Manager private
Definition at line 623 of file G4VAnalysisManager.hh.
Referenced by CreateH1(), ScaleH1(), SetH1(), SetH1Manager(), and WriteAscii().
fVH2Manager
std::unique_ptr<G4VH2Manager> G4VAnalysisManager::fVH2Manager private
Definition at line 624 of file G4VAnalysisManager.hh.
Referenced by CreateH2(), ScaleH2(), SetH2(), SetH2Manager(), and WriteAscii().
fVH3Manager
std::unique_ptr<G4VH3Manager> G4VAnalysisManager::fVH3Manager private
Definition at line 625 of file G4VAnalysisManager.hh.
Referenced by CreateH3(), ScaleH3(), SetH3(), SetH3Manager(), and WriteAscii().
fVNtupleManager
G4VNtupleManager* G4VAnalysisManager::fVNtupleManager private
Definition at line 629 of file G4VAnalysisManager.hh.
Referenced by CreateNtuple(), CreateNtupleDColumn(), CreateNtupleFColumn(), CreateNtupleIColumn(), CreateNtupleSColumn(), FinishNtuple(), GetFirstNtupleColumnId(), GetFirstNtupleId(), GetNofNtuples(), SetFirstNtupleColumnId(), SetFirstNtupleId(), SetNtupleActivation(), SetNtupleManager(), and ~G4VAnalysisManager().
fVP1Manager
std::unique_ptr<G4VP1Manager> G4VAnalysisManager::fVP1Manager private
Definition at line 626 of file G4VAnalysisManager.hh.
Referenced by CreateP1(), ScaleP1(), SetP1(), and SetP1Manager().
fVP2Manager
std::unique_ptr<G4VP2Manager> G4VAnalysisManager::fVP2Manager private
Definition at line 627 of file G4VAnalysisManager.hh.
Referenced by CreateP2(), ScaleP2(), SetP2(), and SetP2Manager().
The documentation for this class was generated from the following files:
source/analysis/management/include/G4VAnalysisManager.hh
source/analysis/management/src/G4VAnalysisManager.cc