Geant4: source/g3tog4/src/G3toG4MANY.cc File Reference
G3toG4MANY.cc File Reference
#include "globals.hh"
#include "G3toG4MANY.hh"
#include "G3Pos.hh"
#include "G3RotTable.hh"
#include "G4SubtractionSolid.hh"
Functions
void G3toG4MANY (G3VolTableEntry *curVTE)
void MakeBooleanSolids (G3VolTableEntry *curVTE, G3VolTableEntryVector *overlaps, const G4Transform3D &transform)
void SubstractSolids (G3VolTableEntry *vte1, G3VolTableEntry *vte2, G4int copy, const G4Transform3D &transform)
G4Transform3D GetTransform3D (G3Pos *g3pos)
Function Documentation
G3toG4MANY()
void G3toG4MANY (G3VolTableEntry * curVTE)
Definition at line 38 of file G3toG4MANY.cc.
GetTransform3D()
G4Transform3D GetTransform3D (G3Pos * g3pos)
Definition at line 145 of file G3toG4MANY.cc.
Referenced by G3toG4MANY(), and SubstractSolids().
MakeBooleanSolids()
void MakeBooleanSolids (G3VolTableEntry * curVTE, G3VolTableEntryVector * overlaps, const G4Transform3D & transform)
Definition at line 75 of file G3toG4MANY.cc.
Referenced by G3toG4MANY().
SubstractSolids()
void SubstractSolids (G3VolTableEntry * vte1, G3VolTableEntry * vte2, G4int copy, const G4Transform3D & transform)
Definition at line 106 of file G3toG4MANY.cc.
Referenced by MakeBooleanSolids().