Geant4: G4Box Class Reference
G4Box Class Reference
#include <G4Box.hh>
Public Member Functions
G4Box (const G4String &pName, G4double pX, G4double pY, G4double pZ)
virtual ~G4Box ()
void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pMin, G4double &pMax) const
G4double GetXHalfLength () const
G4double GetYHalfLength () const
G4double GetZHalfLength () const
void SetXHalfLength (G4double dx)
void SetYHalfLength (G4double dy)
void SetZHalfLength (G4double dz)
G4double GetCubicVolume ()
G4double GetSurfaceArea ()
EInside Inside (const G4ThreeVector &p) const
G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=false, G4bool *validNorm=0, G4ThreeVector *n=0) const
G4double DistanceToOut (const G4ThreeVector &p) const
G4GeometryType GetEntityType () const
G4ThreeVector GetPointOnSurface () const
G4VSolid * Clone () const
std::ostream & StreamInfo (std::ostream &os) const
void DescribeYourselfTo (G4VGraphicsScene &scene) const
G4VisExtent GetExtent () const
G4Polyhedron * CreatePolyhedron () const
G4Box (__void__ &)
G4Box (const G4Box &rhs)
G4Box & operator= (const G4Box &rhs)
Public Member Functions inherited from G4CSGSolid
G4CSGSolid (const G4String &pName)
virtual ~G4CSGSolid ()
virtual G4Polyhedron * GetPolyhedron () const
G4CSGSolid (__void__ &)
G4CSGSolid (const G4CSGSolid &rhs)
G4CSGSolid & operator= (const G4CSGSolid &rhs)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
void DumpInfo () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Private Member Functions
G4ThreeVector ApproxSurfaceNormal (const G4ThreeVector &p) const
Private Attributes
G4double fDx
G4double fDy
G4double fDz
G4double delta
Additional Inherited Members
Protected Member Functions inherited from G4CSGSolid
G4double GetRadiusInRing (G4double rmin, G4double rmax) const
Protected Member Functions inherited from G4VSolid
void CalculateClippedPolygonExtent (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipCrossSection (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipBetweenSections (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipPolygon (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis) const
Protected Attributes inherited from G4CSGSolid
G4double fCubicVolume
G4double fSurfaceArea
G4bool fRebuildPolyhedron
G4Polyhedron * fpPolyhedron
Protected Attributes inherited from G4VSolid
G4double kCarTolerance
Detailed Description
Definition at line 63 of file G4Box.hh.
Constructor & Destructor Documentation
G4Box() [1/3]
G4Box::G4Box (const G4String & pName, G4double pX, G4double pY, G4double pZ)
Definition at line 62 of file G4Box.cc.
Referenced by Clone().
~G4Box()
G4Box::~G4Box () virtual
Definition at line 94 of file G4Box.cc.
G4Box() [2/3]
G4Box::G4Box (__void__ & a)
Definition at line 85 of file G4Box.cc.
G4Box() [3/3]
G4Box::G4Box (const G4Box & rhs)
Definition at line 102 of file G4Box.cc.
Member Function Documentation
ApproxSurfaceNormal()
G4ThreeVector G4Box::ApproxSurfaceNormal (const G4ThreeVector & p) const private
Definition at line 315 of file G4Box.cc.
Referenced by SurfaceNormal().
BoundingLimits()
void G4Box::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 217 of file G4Box.cc.
Referenced by CalculateExtent().
CalculateExtent()
G4bool G4Box::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pMin, G4double & pMax) const virtual
Implements G4VSolid.
Definition at line 240 of file G4Box.cc.
Clone()
G4VSolid * G4Box::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 537 of file G4Box.cc.
ComputeDimensions()
void G4Box::ComputeDimensions (G4VPVParameterisation * p, const G4int n, const G4VPhysicalVolume * pRep) virtual
Reimplemented from G4VSolid.
Definition at line 206 of file G4Box.cc.
CreatePolyhedron()
G4Polyhedron * G4Box::CreatePolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 556 of file G4Box.cc.
Referenced by G4GMocrenFileSceneHandler::AddSolid(), and StandaloneVisAction::Draw().
DescribeYourselfTo()
void G4Box::DescribeYourselfTo (G4VGraphicsScene & scene) const virtual
Implements G4VSolid.
Definition at line 546 of file G4Box.cc.
DistanceToIn() [1/2]
G4double G4Box::DistanceToIn (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 372 of file G4Box.cc.
DistanceToIn() [2/2]
G4double G4Box::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Implements G4VSolid.
Definition at line 335 of file G4Box.cc.
Referenced by G4Voxelizer::DistanceToFirst().
DistanceToOut() [1/2]
G4double G4Box::DistanceToOut (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 452 of file G4Box.cc.
DistanceToOut() [2/2]
G4double G4Box::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcNorm = false, G4bool * validNorm = 0, G4ThreeVector * n = 0) const virtual
Implements G4VSolid.
Definition at line 387 of file G4Box.cc.
GetCubicVolume()
G4double G4Box::GetCubicVolume () inline virtual
Reimplemented from G4VSolid.
GetEntityType()
G4GeometryType G4Box::GetEntityType () const virtual
Implements G4VSolid.
Definition at line 481 of file G4Box.cc.
GetExtent()
G4VisExtent G4Box::GetExtent () const virtual
Reimplemented from G4VSolid.
Definition at line 551 of file G4Box.cc.
GetPointOnSurface()
G4ThreeVector G4Box::GetPointOnSurface () const virtual
Reimplemented from G4VSolid.
Definition at line 513 of file G4Box.cc.
GetSurfaceArea()
G4double G4Box::GetSurfaceArea () inline virtual
Reimplemented from G4VSolid.
GetXHalfLength()
G4double G4Box::GetXHalfLength () const inline
Referenced by G4XXXFileSceneHandler::AddSolid(), G4XXXStoredSceneHandler::AddSolid(), G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), G4XXXSGSceneHandler::AddSolid(), G4GMocrenFileSceneHandler::AddSolid(), G4GDMLWriteParamvol::Box_dimensionsWrite(), G4GDMLWriteSolids::BoxWrite(), G4tgbVolume::BuildSolidForDivision(), G4ParameterisationBoxY::ComputeDimensions(), G4ParameterisationBoxZ::ComputeDimensions(), G4ParameterisationBoxX::ComputeTransformation(), GB06ParallelWorldForSlices::Construct(), DicomRegularDetectorConstruction::ConstructPhantom(), export_G4Box(), G4ParameterisationBoxX::G4ParameterisationBoxX(), B1PrimaryGeneratorAction::GeneratePrimaries(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), G4ParameterisationBoxX::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4PSFlatSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), G4STRead::Read(), and CexmcSetup::ReadCalorimeterGeometryData().
GetYHalfLength()
G4double G4Box::GetYHalfLength () const inline
Referenced by G4XXXFileSceneHandler::AddSolid(), G4XXXStoredSceneHandler::AddSolid(), G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), G4XXXSGSceneHandler::AddSolid(), G4GMocrenFileSceneHandler::AddSolid(), G4GDMLWriteParamvol::Box_dimensionsWrite(), G4GDMLWriteSolids::BoxWrite(), G4ParameterisationBoxX::ComputeDimensions(), G4ParameterisationBoxZ::ComputeDimensions(), G4ParameterisationBoxY::ComputeTransformation(), GB06ParallelWorldForSlices::Construct(), DicomRegularDetectorConstruction::ConstructPhantom(), export_G4Box(), G4ParameterisationBoxY::G4ParameterisationBoxY(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), G4ParameterisationBoxY::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4PSFlatSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), G4STRead::Read(), and CexmcSetup::ReadCalorimeterGeometryData().
GetZHalfLength()
G4double G4Box::GetZHalfLength () const inline
Referenced by G4XXXFileSceneHandler::AddSolid(), G4XXXStoredSceneHandler::AddSolid(), G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), G4XXXSGSceneHandler::AddSolid(), G4GMocrenFileSceneHandler::AddSolid(), G4GDMLWriteParamvol::Box_dimensionsWrite(), G4GDMLWriteSolids::BoxWrite(), G4tgbVolume::BuildSolidForDivision(), G4ParameterisationBoxX::ComputeDimensions(), G4ParameterisationBoxY::ComputeDimensions(), G4ParameterisationBoxZ::ComputeTransformation(), GB06ParallelWorldForSlices::Construct(), DicomRegularDetectorConstruction::ConstructPhantom(), export_G4Box(), G4ParameterisationBoxZ::G4ParameterisationBoxZ(), B2PrimaryGeneratorAction::GeneratePrimaries(), B4PrimaryGeneratorAction::GeneratePrimaries(), B1PrimaryGeneratorAction::GeneratePrimaries(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), G4ParameterisationBoxZ::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4PSFlatSurfaceCurrent::IsSelectedSurface(), G4PSFlatSurfaceFlux::IsSelectedSurface(), G4STRead::Read(), CexmcSetup::ReadCalorimeterGeometryData(), and CML2Acc2::target().
Inside()
EInside G4Box::Inside (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 259 of file G4Box.cc.
Referenced by DistanceToOut().
operator=()
G4Box & G4Box::operator= (const G4Box & rhs)
Definition at line 111 of file G4Box.cc.
SetXHalfLength()
void G4Box::SetXHalfLength (G4double dx)
Definition at line 135 of file G4Box.cc.
Referenced by G4Voxelizer::BuildBoundingBox(), DetectorConstruction::ChangeGeometry(), VoxelParam::ComputeDimensions(), ExN02ChamberParameterisation::ComputeDimensions(), ExP01ChamberParameterisation::ComputeDimensions(), G02ChamberParameterisation::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), G4ParameterisationBoxX::ComputeDimensions(), DicomNestedPhantomParameterisation::ComputeDimensions(), RE02NestedPhantomParameterisation::ComputeDimensions(), G4ParameterisationBoxY::ComputeDimensions(), G4ParameterisationBoxZ::ComputeDimensions(), export_G4Box(), G4STRead::Read(), and HadrontherapyDetectorROGeometry::UpdateROGeometry().
SetYHalfLength()
void G4Box::SetYHalfLength (G4double dy)
Definition at line 159 of file G4Box.cc.
Referenced by G4Voxelizer::BuildBoundingBox(), DetectorConstruction::ChangeGeometry(), VoxelParam::ComputeDimensions(), ExN02ChamberParameterisation::ComputeDimensions(), ExP01ChamberParameterisation::ComputeDimensions(), G02ChamberParameterisation::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), G4ParameterisationBoxX::ComputeDimensions(), DicomNestedPhantomParameterisation::ComputeDimensions(), RE02NestedPhantomParameterisation::ComputeDimensions(), G4ParameterisationBoxY::ComputeDimensions(), G4ParameterisationBoxZ::ComputeDimensions(), export_G4Box(), G4STRead::Read(), and HadrontherapyDetectorROGeometry::UpdateROGeometry().
SetZHalfLength()
void G4Box::SetZHalfLength (G4double dz)
Definition at line 182 of file G4Box.cc.
Referenced by G4Voxelizer::BuildBoundingBox(), DetectorConstruction::ChangeGeometry(), VoxelParam::ComputeDimensions(), ExN02ChamberParameterisation::ComputeDimensions(), ExP01ChamberParameterisation::ComputeDimensions(), G02ChamberParameterisation::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), G4ParameterisationBoxX::ComputeDimensions(), DicomNestedPhantomParameterisation::ComputeDimensions(), RE02NestedPhantomParameterisation::ComputeDimensions(), G4ParameterisationBoxY::ComputeDimensions(), G4ParameterisationBoxZ::ComputeDimensions(), export_G4Box(), G4STRead::Read(), GB03DetectorConstruction::SetNumberOfLayers(), RE06DetectorConstruction::SetNumberOfLayers(), and HadrontherapyDetectorROGeometry::UpdateROGeometry().
StreamInfo()
std::ostream & G4Box::StreamInfo (std::ostream & os) const virtual
Reimplemented from G4CSGSolid.
Definition at line 490 of file G4Box.cc.
SurfaceNormal()
G4ThreeVector G4Box::SurfaceNormal (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 273 of file G4Box.cc.
Field Documentation
delta
G4double G4Box::delta private
Definition at line 141 of file G4Box.hh.
Referenced by DistanceToIn(), DistanceToOut(), G4Box(), Inside(), operator=(), and SurfaceNormal().
fDx
G4double G4Box::fDx private
Definition at line 140 of file G4Box.hh.
Referenced by ApproxSurfaceNormal(), BoundingLimits(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetExtent(), GetPointOnSurface(), Inside(), operator=(), SetXHalfLength(), StreamInfo(), and SurfaceNormal().
fDy
G4double G4Box::fDy private
Definition at line 140 of file G4Box.hh.
Referenced by ApproxSurfaceNormal(), BoundingLimits(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetExtent(), GetPointOnSurface(), Inside(), operator=(), SetYHalfLength(), StreamInfo(), and SurfaceNormal().
fDz
G4double G4Box::fDz private
Definition at line 140 of file G4Box.hh.
Referenced by ApproxSurfaceNormal(), BoundingLimits(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetExtent(), GetPointOnSurface(), Inside(), operator=(), SetZHalfLength(), StreamInfo(), and SurfaceNormal().
The documentation for this class was generated from the following files:
source/geometry/solids/CSG/include/G4Box.hh
source/geometry/solids/CSG/src/G4Box.cc