Geant4: G4VMscModel Class Reference
G4VMscModel Class Reference
#include <G4VMscModel.hh>
Public Member Functions
G4VMscModel (const G4String &nam)
virtual ~G4VMscModel ()
virtual G4double ComputeTruePathLengthLimit (const G4Track &track, G4double &stepLimit)
virtual G4double ComputeGeomPathLength (G4double truePathLength)
virtual G4double ComputeTrueStepLength (G4double geomPathLength)
virtual G4ThreeVector & SampleScattering (const G4ThreeVector &, G4double safety)
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double tmax) override
void SetStepLimitType (G4MscStepLimitType)
void SetLateralDisplasmentFlag (G4bool val)
void SetRangeFactor (G4double)
void SetGeomFactor (G4double)
void SetSkin (G4double)
void SetSampleZ (G4bool)
G4VEnergyLossProcess * GetIonisation () const
void SetIonisation (G4VEnergyLossProcess *, const G4ParticleDefinition *part)
G4double ComputeSafety (const G4ThreeVector &position, G4double limit=DBL_MAX)
G4double ComputeGeomLimit (const G4Track &, G4double &presafety, G4double limit)
G4double GetDEDX (const G4ParticleDefinition *part, G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double GetRange (const G4ParticleDefinition *part, G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double GetEnergy (const G4ParticleDefinition *part, G4double range, const G4MaterialCutsCouple *couple)
G4double GetTransportMeanFreePath (const G4ParticleDefinition *part, G4double kinEnergy)
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &)=0
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0., G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy)
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Member Functions
G4ParticleChangeForMSC * GetParticleChangeForMSC (const G4ParticleDefinition *p=nullptr)
G4double ConvertTrueToGeom (G4double &tLength, G4double &gLength)
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Protected Attributes
G4double facrange
G4double facgeom
G4double facsafety
G4double skin
G4double dtrl
G4double lambdalimit
G4double geomMin
G4double geomMax
G4ThreeVector fDisplacement
G4MscStepLimitType steppingAlgorithm
G4bool samplez
G4bool latDisplasment
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
Private Member Functions
G4VMscModel & operator= (const G4VMscModel &right)=delete
G4VMscModel (const G4VMscModel &)=delete
Private Attributes
G4SafetyHelper * safetyHelper
G4VEnergyLossProcess * ionisation
const G4ParticleDefinition * currentPart
G4double dedx
G4double localtkin
G4double localrange
Detailed Description
Definition at line 66 of file G4VMscModel.hh.
Constructor & Destructor Documentation
G4VMscModel() [1/2]
G4VMscModel::G4VMscModel (const G4String & nam) explicit
Definition at line 59 of file G4VMscModel.cc.
~G4VMscModel()
G4VMscModel::~G4VMscModel () virtual
Definition at line 84 of file G4VMscModel.cc.
G4VMscModel() [2/2]
G4VMscModel::G4VMscModel (const G4VMscModel &) private delete
Member Function Documentation
ComputeGeomLimit()
G4double G4VMscModel::ComputeGeomLimit (const G4Track & track, G4double & presafety, G4double limit) inline
Definition at line 254 of file G4VMscModel.hh.
Referenced by G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTruePathLengthLimit(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), and G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit().
ComputeGeomPathLength()
G4double G4VMscModel::ComputeGeomPathLength (G4double truePathLength) virtual
Reimplemented in G4UrbanAdjointMscModel, G4UrbanMscModel, G4WentzelVIModel, and G4GoudsmitSaundersonMscModel.
Definition at line 155 of file G4VMscModel.cc.
Referenced by ConvertTrueToGeom().
ComputeSafety()
G4double G4VMscModel::ComputeSafety (const G4ThreeVector & position, G4double limit = DBL_MAX) inline
Definition at line 236 of file G4VMscModel.hh.
Referenced by G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTruePathLengthLimit(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), and G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit().
ComputeTruePathLengthLimit()
G4double G4VMscModel::ComputeTruePathLengthLimit (const G4Track & track, G4double & stepLimit) virtual
Reimplemented in G4UrbanAdjointMscModel, G4UrbanMscModel, G4WentzelVIModel, G4GoudsmitSaundersonMscModel, and G4LowEWentzelVIModel.
Definition at line 148 of file G4VMscModel.cc.
Referenced by G4VMultipleScattering::AlongStepGetPhysicalInteractionLength().
ComputeTrueStepLength()
G4double G4VMscModel::ComputeTrueStepLength (G4double geomPathLength) virtual
Reimplemented in G4UrbanAdjointMscModel, G4UrbanMscModel, G4WentzelVIModel, and G4GoudsmitSaundersonMscModel.
Definition at line 162 of file G4VMscModel.cc.
Referenced by G4VMultipleScattering::AlongStepDoIt().
ConvertTrueToGeom()
G4double G4VMscModel::ConvertTrueToGeom (G4double & tLength, G4double & gLength) inline protected
Definition at line 244 of file G4VMscModel.hh.
Referenced by G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTruePathLengthLimit(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), and G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit().
GetDEDX()
G4double G4VMscModel::GetDEDX (const G4ParticleDefinition * part, G4double kineticEnergy, const G4MaterialCutsCouple * couple) inline
Definition at line 267 of file G4VMscModel.hh.
Referenced by G4UrbanMscModel::SampleScattering(), and G4UrbanAdjointMscModel::SampleScattering().
GetEnergy()
G4double G4VMscModel::GetEnergy (const G4ParticleDefinition * part, G4double range, const G4MaterialCutsCouple * couple) inline
Definition at line 302 of file G4VMscModel.hh.
Referenced by G4WentzelVIModel::ComputeGeomPathLength(), G4UrbanMscModel::ComputeGeomPathLength(), G4UrbanAdjointMscModel::ComputeGeomPathLength(), G4GoudsmitSaundersonMscModel::ComputeGeomPathLength(), G4WentzelVIModel::ComputeTrueStepLength(), G4GoudsmitSaundersonMscModel::SampleMSC(), G4UrbanMscModel::SampleScattering(), and G4UrbanAdjointMscModel::SampleScattering().
GetIonisation()
G4VEnergyLossProcess * G4VMscModel::GetIonisation () const inline
Definition at line 322 of file G4VMscModel.hh.
GetParticleChangeForMSC()
G4ParticleChangeForMSC * G4VMscModel::GetParticleChangeForMSC (const G4ParticleDefinition * p = nullptr) protected
Definition at line 90 of file G4VMscModel.cc.
Referenced by G4WentzelVIModel::Initialise(), G4UrbanMscModel::Initialise(), G4UrbanAdjointMscModel::Initialise(), and G4GoudsmitSaundersonMscModel::Initialise().
GetRange()
G4double G4VMscModel::GetRange (const G4ParticleDefinition * part, G4double kineticEnergy, const G4MaterialCutsCouple * couple) inline
Definition at line 282 of file G4VMscModel.hh.
Referenced by G4VMultipleScattering::AlongStepDoIt(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTruePathLengthLimit(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), and G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit().
GetTransportMeanFreePath()
G4double G4VMscModel::GetTransportMeanFreePath (const G4ParticleDefinition * part, G4double kinEnergy) inline
Definition at line 339 of file G4VMscModel.hh.
Referenced by G4WentzelVIModel::ComputeGeomPathLength(), G4UrbanMscModel::ComputeGeomPathLength(), G4UrbanAdjointMscModel::ComputeGeomPathLength(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTruePathLengthLimit(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTrueStepLength(), G4EmCalculator::GetCrossSectionPerVolume(), G4UrbanMscModel::SampleCosineTheta(), and G4UrbanAdjointMscModel::SampleCosineTheta().
operator=()
G4VMscModel& G4VMscModel::operator= (const G4VMscModel & right) private delete
SampleScattering()
G4ThreeVector & G4VMscModel::SampleScattering (const G4ThreeVector & , G4double safety) virtual
Reimplemented in G4UrbanAdjointMscModel, G4UrbanMscModel, G4WentzelVIModel, and G4GoudsmitSaundersonMscModel.
Definition at line 141 of file G4VMscModel.cc.
Referenced by G4VMultipleScattering::AlongStepDoIt().
SampleSecondaries()
void G4VMscModel::SampleSecondaries (std::vector< G4DynamicParticle * > * , const G4MaterialCutsCouple * , const G4DynamicParticle * , G4double tmin, G4double tmax) override virtual
Implements G4VEmModel.
Reimplemented in G4DummyModel.
Definition at line 169 of file G4VMscModel.cc.
SetGeomFactor()
void G4VMscModel::SetGeomFactor (G4double val) inline
Definition at line 215 of file G4VMscModel.hh.
Referenced by G4VMultipleScattering::PreparePhysicsTable().
SetIonisation()
void G4VMscModel::SetIonisation (G4VEnergyLossProcess * p, const G4ParticleDefinition * part) inline
Definition at line 329 of file G4VMscModel.hh.
Referenced by G4VMultipleScattering::PreparePhysicsTable(), G4VMultipleScattering::SetIonisation(), and G4VMultipleScattering::StartTracking().
SetLateralDisplasmentFlag()
void G4VMscModel::SetLateralDisplasmentFlag (G4bool val) inline
Definition at line 194 of file G4VMscModel.hh.
Referenced by G4VMultipleScattering::PreparePhysicsTable().
SetRangeFactor()
void G4VMscModel::SetRangeFactor (G4double val) inline
Definition at line 208 of file G4VMscModel.hh.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmModelActivator::GetGSModel(), and G4VMultipleScattering::PreparePhysicsTable().
SetSampleZ()
void G4VMscModel::SetSampleZ (G4bool val) inline
Definition at line 229 of file G4VMscModel.hh.
SetSkin()
void G4VMscModel::SetSkin (G4double val) inline
Definition at line 201 of file G4VMscModel.hh.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmModelActivator::GetGSModel(), and G4VMultipleScattering::PreparePhysicsTable().
SetStepLimitType()
void G4VMscModel::SetStepLimitType (G4MscStepLimitType val) inline
Definition at line 222 of file G4VMscModel.hh.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmModelActivator::GetGSModel(), and G4VMultipleScattering::PreparePhysicsTable().
Field Documentation
currentPart
const G4ParticleDefinition* G4VMscModel::currentPart private
Definition at line 166 of file G4VMscModel.hh.
Referenced by G4VMscModel(), and SetIonisation().
dedx
G4double G4VMscModel::dedx private
Definition at line 168 of file G4VMscModel.hh.
Referenced by G4VMscModel(), GetDEDX(), GetEnergy(), and GetRange().
dtrl
G4double G4VMscModel::dtrl protected
Definition at line 178 of file G4VMscModel.hh.
Referenced by G4UrbanMscModel::ComputeGeomPathLength(), G4UrbanAdjointMscModel::ComputeGeomPathLength(), G4GoudsmitSaundersonMscModel::ComputeGeomPathLength(), G4UrbanMscModel::SampleScattering(), and G4UrbanAdjointMscModel::SampleScattering().
facgeom
G4double G4VMscModel::facgeom protected
Definition at line 175 of file G4VMscModel.hh.
Referenced by G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTruePathLengthLimit(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), and SetGeomFactor().
facrange
G4double G4VMscModel::facrange protected
Definition at line 174 of file G4VMscModel.hh.
Referenced by G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTruePathLengthLimit(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), SetRangeFactor(), G4UrbanMscModel::StartTracking(), and G4UrbanAdjointMscModel::StartTracking().
facsafety
G4double G4VMscModel::facsafety protected
Definition at line 176 of file G4VMscModel.hh.
Referenced by G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTruePathLengthLimit(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::G4GoudsmitSaundersonMscModel(), G4UrbanAdjointMscModel::G4UrbanAdjointMscModel(), and G4UrbanMscModel::G4UrbanMscModel().
fDisplacement
G4ThreeVector G4VMscModel::fDisplacement protected
Definition at line 183 of file G4VMscModel.hh.
Referenced by G4UrbanMscModel::SampleDisplacement(), G4UrbanAdjointMscModel::SampleDisplacement(), G4UrbanMscModel::SampleDisplacementNew(), G4UrbanAdjointMscModel::SampleDisplacementNew(), SampleScattering(), G4WentzelVIModel::SampleScattering(), G4UrbanMscModel::SampleScattering(), and G4UrbanAdjointMscModel::SampleScattering().
geomMax
G4double G4VMscModel::geomMax protected
Definition at line 181 of file G4VMscModel.hh.
geomMin
G4double G4VMscModel::geomMin protected
Definition at line 180 of file G4VMscModel.hh.
ionisation
G4VEnergyLossProcess* G4VMscModel::ionisation private
Definition at line 165 of file G4VMscModel.hh.
Referenced by GetDEDX(), GetEnergy(), GetIonisation(), GetRange(), and SetIonisation().
lambdalimit
G4double G4VMscModel::lambdalimit protected
Definition at line 179 of file G4VMscModel.hh.
latDisplasment
G4bool G4VMscModel::latDisplasment protected
Definition at line 187 of file G4VMscModel.hh.
Referenced by G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4UrbanMscModel::Initialise(), G4UrbanAdjointMscModel::Initialise(), G4WentzelVIModel::SampleScattering(), G4UrbanMscModel::SampleScattering(), G4UrbanAdjointMscModel::SampleScattering(), and SetLateralDisplasmentFlag().
localrange
G4double G4VMscModel::localrange private
Definition at line 170 of file G4VMscModel.hh.
Referenced by G4VMscModel(), GetEnergy(), and GetRange().
localtkin
G4double G4VMscModel::localtkin private
Definition at line 169 of file G4VMscModel.hh.
Referenced by G4VMscModel(), GetEnergy(), and GetRange().
safetyHelper
G4SafetyHelper* G4VMscModel::safetyHelper private
Definition at line 164 of file G4VMscModel.hh.
Referenced by ComputeGeomLimit(), ComputeSafety(), and GetParticleChangeForMSC().
samplez
G4bool G4VMscModel::samplez protected
Definition at line 186 of file G4VMscModel.hh.
Referenced by SetSampleZ().
skin
G4double G4VMscModel::skin protected
Definition at line 177 of file G4VMscModel.hh.
Referenced by G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::G4UrbanAdjointMscModel(), G4UrbanMscModel::G4UrbanMscModel(), and SetSkin().
steppingAlgorithm
G4MscStepLimitType G4VMscModel::steppingAlgorithm protected
Definition at line 184 of file G4VMscModel.hh.
Referenced by G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTruePathLengthLimit(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::SampleScattering(), and SetStepLimitType().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/utils/include/G4VMscModel.hh
source/processes/electromagnetic/utils/src/G4VMscModel.cc