Geant4: CCalG4Hit Class Reference
CCalG4Hit Class Reference
#include <CCalG4Hit.hh>
Public Member Functions
CCalG4Hit ()
~CCalG4Hit ()
CCalG4Hit (const CCalG4Hit &right)
const CCalG4Hit & operator= (const CCalG4Hit &right)
G4bool operator== (const CCalG4Hit &)
void Draw ()
void Print ()
double getEM () const
void setEM (double e)
double getHadr () const
void setHadr (double e)
void addEnergyDeposit (const CCalG4Hit &aHit)
void addEnergyDeposit (double em, double hd)
Public Member Functions inherited from G4VHit
G4VHit ()
virtual ~G4VHit ()
G4bool operator== (const G4VHit &right) const
virtual const std::map< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Public Member Functions inherited from CCalHit
CCalHit ()
~CCalHit ()
CCalHit (const CCalHit &right)
const CCalHit & operator= (const CCalHit &right)
G4bool operator== (const CCalHit &)
void print ()
CLHEP::Hep3Vector getEntry () const
void setEntry (CLHEP::Hep3Vector xyz)
double getIncidentEnergy () const
void setIncidentEnergy (double e)
int getTrackID () const
void setTrackID (int i)
unsigned int getUnitID () const
void setUnitID (unsigned int i)
double getTimeSlice () const
void setTimeSlice (double d)
int getTimeSliceID () const
double getEnergyDeposit () const
void setEnergyDeposit (const double e)
void addEnergyDeposit (const CCalHit &aHit)
void addEnergyDeposit (const double e)
Private Attributes
double elem
double hadr
Friends
std::ostream & operator<< (std::ostream &os, const CCalG4Hit &hit)
Detailed Description
Definition at line 38 of file CCalG4Hit.hh.
Constructor & Destructor Documentation
CCalG4Hit() [1/2]
CCalG4Hit::CCalG4Hit ()
Definition at line 35 of file CCalG4Hit.cc.
~CCalG4Hit()
CCalG4Hit::~CCalG4Hit ()
Definition at line 40 of file CCalG4Hit.cc.
CCalG4Hit() [2/2]
CCalG4Hit::CCalG4Hit (const CCalG4Hit & right)
Definition at line 43 of file CCalG4Hit.cc.
Member Function Documentation
addEnergyDeposit() [1/2]
void CCalG4Hit::addEnergyDeposit (const CCalG4Hit & aHit)
Definition at line 63 of file CCalG4Hit.cc.
Referenced by CCaloSD::updateHit().
addEnergyDeposit() [2/2]
void CCalG4Hit::addEnergyDeposit (double em, double hd)
Definition at line 67 of file CCalG4Hit.cc.
Draw()
void CCalG4Hit::Draw () inline virtual
Reimplemented from G4VHit.
Definition at line 52 of file CCalG4Hit.hh.
getEM()
double CCalG4Hit::getEM () const
Definition at line 57 of file CCalG4Hit.cc.
Referenced by addEnergyDeposit(), and operator<<().
getHadr()
double CCalG4Hit::getHadr () const
Definition at line 60 of file CCalG4Hit.cc.
Referenced by addEnergyDeposit(), and operator<<().
operator=()
const CCalG4Hit & CCalG4Hit::operator= (const CCalG4Hit & right)
Definition at line 49 of file CCalG4Hit.cc.
operator==()
G4bool CCalG4Hit::operator== (const CCalG4Hit &) inline
Definition at line 48 of file CCalG4Hit.hh.
Print()
void CCalG4Hit::Print (void) virtual
Reimplemented from G4VHit.
Definition at line 74 of file CCalG4Hit.cc.
setEM()
void CCalG4Hit::setEM (double e)
Definition at line 58 of file CCalG4Hit.cc.
setHadr()
void CCalG4Hit::setHadr (double e)
Definition at line 61 of file CCalG4Hit.cc.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CCalG4Hit & hit) friend
Definition at line 79 of file CCalG4Hit.cc.
Field Documentation
elem
double CCalG4Hit::elem private
Definition at line 66 of file CCalG4Hit.hh.
Referenced by addEnergyDeposit(), getEM(), operator=(), and setEM().
hadr
double CCalG4Hit::hadr private
Definition at line 67 of file CCalG4Hit.hh.
Referenced by addEnergyDeposit(), getHadr(), operator=(), and setHadr().
The documentation for this class was generated from the following files:
examples/advanced/composite_calorimeter/include/CCalG4Hit.hh
examples/advanced/composite_calorimeter/src/CCalG4Hit.cc