Geant4: G4CascadeCoalescence Class Reference
G4CascadeCoalescence Class Reference
#include <G4CascadeCoalescence.hh>
Public Member Functions
G4CascadeCoalescence (G4int verbose=0)
virtual ~G4CascadeCoalescence ()
void FindClusters (G4CollisionOutput &finalState)
void setVerboseLevel (G4int verbose)
Private Types
typedef std::vector< size_t > ClusterCandidate
Private Member Functions
void selectCandidates ()
void createNuclei ()
void removeNucleons ()
void tryClusters (size_t idx1, size_t idx2)
void tryClusters (size_t idx1, size_t idx2, size_t idx3)
void tryClusters (size_t idx1, size_t idx2, size_t idx3, size_t idx4)
void fillCluster (size_t idx1, size_t idx2)
void fillCluster (size_t idx1, size_t idx2, size_t idx3)
void fillCluster (size_t idx1, size_t idx2, size_t idx3, size_t idx4)
bool nucleonUsed (size_t idx) const
bool allNucleons (const ClusterCandidate &clus) const
bool goodCluster (const ClusterCandidate &clus) const
G4int clusterType (const ClusterCandidate &aCluster) const
const G4InuclElementaryParticle & getHadron (size_t idx) const
bool makeLightIon (const ClusterCandidate &aCluster)
G4LorentzVector getClusterMomentum (const ClusterCandidate &aCluster) const
G4double maxDeltaP (const ClusterCandidate &aCluster) const
void reportArgs (const G4String &name, const ClusterCandidate &clus) const
void reportResult (const G4String &name, const G4InuclNuclei &nucl) const
Private Attributes
G4int verboseLevel
std::vector< ClusterCandidate > allClusters
std::set< size_t > usedNucleons
G4CollisionOutput * thisFinalState
const std::vector< G4InuclElementaryParticle > * thisHadrons
ClusterCandidate thisCluster
G4InuclNuclei thisLightIon
const G4double dpMaxDoublet
const G4double dpMaxTriplet
const G4double dpMaxAlpha
G4LorentzVector pCluster
Detailed Description
Definition at line 52 of file G4CascadeCoalescence.hh.
Member Typedef Documentation
ClusterCandidate
typedef std::vector<size_t> G4CascadeCoalescence::ClusterCandidate private
Definition at line 63 of file G4CascadeCoalescence.hh.
Constructor & Destructor Documentation
G4CascadeCoalescence()
G4CascadeCoalescence::G4CascadeCoalescence (G4int verbose = 0)
Definition at line 66 of file G4CascadeCoalescence.cc.
~G4CascadeCoalescence()
G4CascadeCoalescence::~G4CascadeCoalescence () virtual
Definition at line 72 of file G4CascadeCoalescence.cc.
Member Function Documentation
allNucleons()
bool G4CascadeCoalescence::allNucleons (const ClusterCandidate & clus) const private
Definition at line 287 of file G4CascadeCoalescence.cc.
Referenced by goodCluster().
clusterType()
G4int G4CascadeCoalescence::clusterType (const ClusterCandidate & aCluster) const private
Definition at line 248 of file G4CascadeCoalescence.cc.
Referenced by goodCluster(), and makeLightIon().
createNuclei()
void G4CascadeCoalescence::createNuclei () private
Definition at line 179 of file G4CascadeCoalescence.cc.
Referenced by FindClusters().
fillCluster() [1/3]
void G4CascadeCoalescence::fillCluster (size_t idx1, size_t idx2) private
Definition at line 261 of file G4CascadeCoalescence.cc.
Referenced by tryClusters().
fillCluster() [2/3]
void G4CascadeCoalescence::fillCluster (size_t idx1, size_t idx2, size_t idx3) private
Definition at line 267 of file G4CascadeCoalescence.cc.
fillCluster() [3/3]
void G4CascadeCoalescence::fillCluster (size_t idx1, size_t idx2, size_t idx3, size_t idx4) private
Definition at line 274 of file G4CascadeCoalescence.cc.
FindClusters()
void G4CascadeCoalescence::FindClusters (G4CollisionOutput & finalState)
Definition at line 77 of file G4CascadeCoalescence.cc.
Referenced by G4IntraNucleiCascader::finishCascade().
getClusterMomentum()
G4LorentzVector G4CascadeCoalescence::getClusterMomentum (const ClusterCandidate & aCluster) const private
Definition at line 215 of file G4CascadeCoalescence.cc.
Referenced by makeLightIon(), and maxDeltaP().
getHadron()
const G4InuclElementaryParticle& G4CascadeCoalescence::getHadron (size_t idx) const inline private
Definition at line 106 of file G4CascadeCoalescence.hh.
Referenced by allNucleons(), clusterType(), getClusterMomentum(), maxDeltaP(), reportArgs(), and selectCandidates().
goodCluster()
bool G4CascadeCoalescence::goodCluster (const ClusterCandidate & clus) const private
Definition at line 297 of file G4CascadeCoalescence.cc.
Referenced by tryClusters().
makeLightIon()
bool G4CascadeCoalescence::makeLightIon (const ClusterCandidate & aCluster) private
Definition at line 319 of file G4CascadeCoalescence.cc.
Referenced by createNuclei().
maxDeltaP()
G4double G4CascadeCoalescence::maxDeltaP (const ClusterCandidate & aCluster) const private
Definition at line 226 of file G4CascadeCoalescence.cc.
Referenced by goodCluster().
nucleonUsed()
bool G4CascadeCoalescence::nucleonUsed (size_t idx) const inline private
Definition at line 96 of file G4CascadeCoalescence.hh.
Referenced by tryClusters().
removeNucleons()
void G4CascadeCoalescence::removeNucleons () private
Definition at line 199 of file G4CascadeCoalescence.cc.
Referenced by FindClusters().
reportArgs()
void G4CascadeCoalescence::reportArgs (const G4String & name, const ClusterCandidate & clus) const private
Definition at line 348 of file G4CascadeCoalescence.cc.
Referenced by goodCluster(), makeLightIon(), maxDeltaP(), and tryClusters().
reportResult()
void G4CascadeCoalescence::reportResult (const G4String & name, const G4InuclNuclei & nucl) const private
Definition at line 361 of file G4CascadeCoalescence.cc.
Referenced by makeLightIon().
selectCandidates()
void G4CascadeCoalescence::selectCandidates () private
Definition at line 96 of file G4CascadeCoalescence.cc.
Referenced by FindClusters().
setVerboseLevel()
void G4CascadeCoalescence::setVerboseLevel (G4int verbose) inline
Definition at line 60 of file G4CascadeCoalescence.hh.
Referenced by G4IntraNucleiCascader::finishCascade(), and G4IntraNucleiCascader::setVerboseLevel().
tryClusters() [1/3]
void G4CascadeCoalescence::tryClusters (size_t idx1, size_t idx2) private
Definition at line 163 of file G4CascadeCoalescence.cc.
Referenced by selectCandidates().
tryClusters() [2/3]
void G4CascadeCoalescence::tryClusters (size_t idx1, size_t idx2, size_t idx3) private
Definition at line 148 of file G4CascadeCoalescence.cc.
tryClusters() [3/3]
void G4CascadeCoalescence::tryClusters (size_t idx1, size_t idx2, size_t idx3, size_t idx4) private
Definition at line 130 of file G4CascadeCoalescence.cc.
Field Documentation
allClusters
std::vector<ClusterCandidate> G4CascadeCoalescence::allClusters private
Definition at line 67 of file G4CascadeCoalescence.hh.
Referenced by createNuclei(), selectCandidates(), and tryClusters().
dpMaxAlpha
const G4double G4CascadeCoalescence::dpMaxAlpha private
Definition at line 78 of file G4CascadeCoalescence.hh.
Referenced by goodCluster().
dpMaxDoublet
const G4double G4CascadeCoalescence::dpMaxDoublet private
Definition at line 76 of file G4CascadeCoalescence.hh.
Referenced by goodCluster().
dpMaxTriplet
const G4double G4CascadeCoalescence::dpMaxTriplet private
Definition at line 77 of file G4CascadeCoalescence.hh.
Referenced by goodCluster().
pCluster
G4LorentzVector G4CascadeCoalescence::pCluster mutable private
Definition at line 115 of file G4CascadeCoalescence.hh.
Referenced by getClusterMomentum().
thisCluster
ClusterCandidate G4CascadeCoalescence::thisCluster private
Definition at line 73 of file G4CascadeCoalescence.hh.
Referenced by fillCluster(), and tryClusters().
thisFinalState
G4CollisionOutput* G4CascadeCoalescence::thisFinalState private
Definition at line 70 of file G4CascadeCoalescence.hh.
Referenced by createNuclei(), FindClusters(), and removeNucleons().
thisHadrons
const std::vector<G4InuclElementaryParticle>* G4CascadeCoalescence::thisHadrons private
Definition at line 71 of file G4CascadeCoalescence.hh.
Referenced by FindClusters(), getHadron(), and selectCandidates().
thisLightIon
G4InuclNuclei G4CascadeCoalescence::thisLightIon private
Definition at line 74 of file G4CascadeCoalescence.hh.
Referenced by createNuclei(), and makeLightIon().
usedNucleons
std::set<size_t> G4CascadeCoalescence::usedNucleons private
Definition at line 68 of file G4CascadeCoalescence.hh.
Referenced by createNuclei(), nucleonUsed(), removeNucleons(), selectCandidates(), and tryClusters().
verboseLevel
G4int G4CascadeCoalescence::verboseLevel private
Definition at line 65 of file G4CascadeCoalescence.hh.
Referenced by createNuclei(), FindClusters(), goodCluster(), makeLightIon(), maxDeltaP(), removeNucleons(), reportArgs(), selectCandidates(), setVerboseLevel(), and tryClusters().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/cascade/cascade/include/G4CascadeCoalescence.hh
source/processes/hadronic/models/cascade/cascade/src/G4CascadeCoalescence.cc