Geant4: G4GFlashSpot Class Reference
G4GFlashSpot Class Reference
#include <G4GFlashSpot.hh>
Public Member Functions
G4GFlashSpot (const GFlashEnergySpot *aSpot, const G4FastTrack *aTrack, G4TouchableHandle aH)
~G4GFlashSpot ()
const GFlashEnergySpot * GetEnergySpot () const
const G4FastTrack * GetOriginatorTrack () const
G4TouchableHandle GetTouchableHandle () const
G4ThreeVector GetPosition () const
Private Attributes
const GFlashEnergySpot * theSpot
const G4FastTrack * theTrack
G4TouchableHandle theHandle
Detailed Description
Definition at line 47 of file G4GFlashSpot.hh.
Constructor & Destructor Documentation
G4GFlashSpot()
G4GFlashSpot::G4GFlashSpot (const GFlashEnergySpot * aSpot, const G4FastTrack * aTrack, G4TouchableHandle aH) inline
Definition at line 51 of file G4GFlashSpot.hh.
~G4GFlashSpot()
G4GFlashSpot::~G4GFlashSpot () inline
Definition at line 55 of file G4GFlashSpot.hh.
Member Function Documentation
GetEnergySpot()
const GFlashEnergySpot* G4GFlashSpot::GetEnergySpot () const inline
Definition at line 57 of file G4GFlashSpot.hh.
Referenced by ExGflashSensitiveDetector::ProcessHits().
GetOriginatorTrack()
const G4FastTrack* G4GFlashSpot::GetOriginatorTrack () const inline
Definition at line 59 of file G4GFlashSpot.hh.
Referenced by GetPosition(), and G4VGFlashSensitiveDetector::Hit().
GetPosition()
G4ThreeVector G4GFlashSpot::GetPosition () const inline
Definition at line 63 of file G4GFlashSpot.hh.
Referenced by G4VGFlashSensitiveDetector::Hit().
GetTouchableHandle()
G4TouchableHandle G4GFlashSpot::GetTouchableHandle () const inline
Definition at line 61 of file G4GFlashSpot.hh.
Referenced by G4VGFlashSensitiveDetector::Hit(), and ExGflashSensitiveDetector::ProcessHits().
Field Documentation
theHandle
G4TouchableHandle G4GFlashSpot::theHandle private
Definition at line 70 of file G4GFlashSpot.hh.
Referenced by GetTouchableHandle().
theSpot
const GFlashEnergySpot* G4GFlashSpot::theSpot private
Definition at line 68 of file G4GFlashSpot.hh.
Referenced by GetEnergySpot().
theTrack
const G4FastTrack* G4GFlashSpot::theTrack private
Definition at line 69 of file G4GFlashSpot.hh.
Referenced by GetOriginatorTrack().
The documentation for this class was generated from the following file:
source/parameterisations/gflash/include/G4GFlashSpot.hh