Geant4: G4AnyMethod::FuncRef2< S, T, A0, A1 > Struct Template Reference
G4AnyMethod::FuncRef2< S, T, A0, A1 > Struct Template Reference
Public Types
typedef remove_const< typename remove_reference< A0 >::type >::type nakedA0
typedef remove_const< typename remove_reference< A1 >::type >::type nakedA1
Public Member Functions
FuncRef2 (S(T::*f)(A0, A1))
virtual void operator() (void *)
virtual void operator() (void *obj, const std::string &s0)
virtual Placeholder * Clone () const
virtual const std::type_info & ArgType (size_t i) const
Public Member Functions inherited from G4AnyMethod::Placeholder
Placeholder ()
virtual ~Placeholder ()
Data Fields
S(T::* fRef)(A0, A1)
Detailed Description
template<class S, class T, class A0, class A1>
struct G4AnyMethod::FuncRef2< S, T, A0, A1 >
Definition at line 198 of file G4AnyMethod.hh.
Member Typedef Documentation
nakedA0
template<class S , class T , class A0 , class A1 > typedef remove_const<typename remove_reference<A0>::type>::type G4AnyMethod::FuncRef2< S, T, A0, A1 >::nakedA0
Definition at line 199 of file G4AnyMethod.hh.
nakedA1
template<class S , class T , class A0 , class A1 > typedef remove_const<typename remove_reference<A1>::type>::type G4AnyMethod::FuncRef2< S, T, A0, A1 >::nakedA1
Definition at line 200 of file G4AnyMethod.hh.
Constructor & Destructor Documentation
FuncRef2()
template<class S , class T , class A0 , class A1 > G4AnyMethod::FuncRef2< S, T, A0, A1 >::FuncRef2 (S(T::*)(A0, A1) f) inline
Definition at line 202 of file G4AnyMethod.hh.
Referenced by G4AnyMethod::FuncRef2< S, T, A0, A1 >::Clone().
Member Function Documentation
ArgType()
template<class S , class T , class A0 , class A1 > virtual const std::type_info& G4AnyMethod::FuncRef2< S, T, A0, A1 >::ArgType (size_t i) const inline virtual
Implements G4AnyMethod::Placeholder.
Definition at line 217 of file G4AnyMethod.hh.
Clone()
template<class S , class T , class A0 , class A1 > virtual Placeholder* G4AnyMethod::FuncRef2< S, T, A0, A1 >::Clone () const inline virtual
Implements G4AnyMethod::Placeholder.
Definition at line 214 of file G4AnyMethod.hh.
operator()() [1/2]
template<class S , class T , class A0 , class A1 > virtual void G4AnyMethod::FuncRef2< S, T, A0, A1 >::operator() (void *) inline virtual
Implements G4AnyMethod::Placeholder.
Definition at line 204 of file G4AnyMethod.hh.
operator()() [2/2]
template<class S , class T , class A0 , class A1 > virtual void G4AnyMethod::FuncRef2< S, T, A0, A1 >::operator() (void * obj, const std::string & s0) inline virtual
Implements G4AnyMethod::Placeholder.
Definition at line 207 of file G4AnyMethod.hh.
Field Documentation
fRef
template<class S , class T , class A0 , class A1 > S(T::* G4AnyMethod::FuncRef2< S, T, A0, A1 >::fRef) (A0, A1)
Definition at line 220 of file G4AnyMethod.hh.
Referenced by G4AnyMethod::FuncRef2< S, T, A0, A1 >::Clone(), and G4AnyMethod::FuncRef2< S, T, A0, A1 >::operator()().
The documentation for this struct was generated from the following file:
source/intercoms/include/G4AnyMethod.hh