Geant4: G4ScaleTransform Class Reference
G4ScaleTransform Class Reference
#include <G4ScaleTransform.hh>
Public Member Functions
G4ScaleTransform ()
G4ScaleTransform (G4double sx, G4double sy, G4double sz)
G4ScaleTransform (const G4ThreeVector &scale)
G4ScaleTransform (const G4Scale3D &scale)
G4ScaleTransform (const G4ScaleTransform &right)
G4ScaleTransform & operator= (const G4ScaleTransform &right)
void Init ()
const G4ThreeVector & GetScale () const
const G4ThreeVector & GetInvScale () const
void SetScale (const G4ThreeVector &scale)
void SetScale (const G4Scale3D &scale)
void SetScale (G4double sx, G4double sy, G4double sz)
void Transform (const G4ThreeVector &global, G4ThreeVector &local) const
G4ThreeVector Transform (const G4ThreeVector &global) const
void InverseTransform (const G4ThreeVector &local, G4ThreeVector &global) const
G4ThreeVector InverseTransform (const G4ThreeVector &local) const
void TransformNormal (const G4ThreeVector &global, G4ThreeVector &local) const
G4ThreeVector TransformNormal (const G4ThreeVector &global) const
void InverseTransformNormal (const G4ThreeVector &local, G4ThreeVector &global) const
G4ThreeVector InverseTransformNormal (const G4ThreeVector &local) const
G4double TransformDistance (G4double dist, const G4ThreeVector &dir) const
G4double TransformDistance (G4double safety) const
G4double InverseTransformDistance (G4double dist, const G4ThreeVector &dir) const
G4double InverseTransformDistance (G4double safety) const
Private Attributes
G4ThreeVector fScale
G4ThreeVector fIScale
G4double flFactor
G4double fgFactor
Detailed Description
Definition at line 62 of file G4ScaleTransform.hh.
Constructor & Destructor Documentation
G4ScaleTransform() [1/5]
G4ScaleTransform::G4ScaleTransform () inline
G4ScaleTransform() [2/5]
G4ScaleTransform::G4ScaleTransform (G4double sx, G4double sy, G4double sz) inline
G4ScaleTransform() [3/5]
G4ScaleTransform::G4ScaleTransform (const G4ThreeVector & scale) inline
G4ScaleTransform() [4/5]
G4ScaleTransform::G4ScaleTransform (const G4Scale3D & scale) inline
G4ScaleTransform() [5/5]
G4ScaleTransform::G4ScaleTransform (const G4ScaleTransform & right) inline
Member Function Documentation
GetInvScale()
const G4ThreeVector& G4ScaleTransform::GetInvScale () const inline
GetScale()
const G4ThreeVector& G4ScaleTransform::GetScale () const inline
Referenced by G4ScaledSolid::BoundingLimits(), G4ScaledSolid::GetCubicVolume(), G4ScaledSolid::GetScaleTransform(), and G4ScaledSolid::StreamInfo().
Init()
void G4ScaleTransform::Init () inline
InverseTransform() [1/2]
G4ThreeVector G4ScaleTransform::InverseTransform (const G4ThreeVector & local) const inline
InverseTransform() [2/2]
void G4ScaleTransform::InverseTransform (const G4ThreeVector & local, G4ThreeVector & global) const inline
Referenced by G4ScaledSolid::GetPointOnSurface().
InverseTransformDistance() [1/2]
G4double G4ScaleTransform::InverseTransformDistance (G4double dist, const G4ThreeVector & dir) const inline
Referenced by G4ScaledSolid::DistanceToIn(), and G4ScaledSolid::DistanceToOut().
InverseTransformDistance() [2/2]
G4double G4ScaleTransform::InverseTransformDistance (G4double safety) const inline
InverseTransformNormal() [1/2]
G4ThreeVector G4ScaleTransform::InverseTransformNormal (const G4ThreeVector & local) const inline
InverseTransformNormal() [2/2]
void G4ScaleTransform::InverseTransformNormal (const G4ThreeVector & local, G4ThreeVector & global) const inline
Referenced by G4ScaledSolid::SurfaceNormal().
operator=()
G4ScaleTransform& G4ScaleTransform::operator= (const G4ScaleTransform & right) inline
SetScale() [1/3]
void G4ScaleTransform::SetScale (const G4Scale3D & scale) inline
SetScale() [2/3]
void G4ScaleTransform::SetScale (const G4ThreeVector & scale) inline
SetScale() [3/3]
void G4ScaleTransform::SetScale (G4double sx, G4double sy, G4double sz) inline
Transform() [1/2]
G4ThreeVector G4ScaleTransform::Transform (const G4ThreeVector & global) const inline
Transform() [2/2]
void G4ScaleTransform::Transform (const G4ThreeVector & global, G4ThreeVector & local) const inline
Referenced by G4ScaledSolid::DistanceToIn(), G4ScaledSolid::DistanceToOut(), G4ScaledSolid::Inside(), and G4ScaledSolid::SurfaceNormal().
TransformDistance() [1/2]
G4double G4ScaleTransform::TransformDistance (G4double dist, const G4ThreeVector & dir) const inline
TransformDistance() [2/2]
G4double G4ScaleTransform::TransformDistance (G4double safety) const inline
TransformNormal() [1/2]
G4ThreeVector G4ScaleTransform::TransformNormal (const G4ThreeVector & global) const inline
TransformNormal() [2/2]
void G4ScaleTransform::TransformNormal (const G4ThreeVector & global, G4ThreeVector & local) const inline
Referenced by G4ScaledSolid::DistanceToOut().
Field Documentation
fgFactor
G4double G4ScaleTransform::fgFactor private
Definition at line 139 of file G4ScaleTransform.hh.
fIScale
G4ThreeVector G4ScaleTransform::fIScale private
Definition at line 138 of file G4ScaleTransform.hh.
flFactor
G4double G4ScaleTransform::flFactor private
Definition at line 139 of file G4ScaleTransform.hh.
fScale
G4ThreeVector G4ScaleTransform::fScale private
Definition at line 137 of file G4ScaleTransform.hh.
The documentation for this class was generated from the following file:
source/geometry/management/include/G4ScaleTransform.hh