Geant4: G4GenericTrap Class Reference
G4GenericTrap Class Reference
#include <G4GenericTrap.hh>
Public Member Functions
G4GenericTrap (const G4String &name, G4double halfZ, const std::vector< G4TwoVector > &vertices)
~G4GenericTrap ()
G4double GetZHalfLength () const
G4int GetNofVertices () const
G4TwoVector GetVertex (G4int index) const
const std::vector< G4TwoVector > & GetVertices () const
G4double GetTwistAngle (G4int index) const
G4bool IsTwisted () const
G4int GetVisSubdivisions () const
void SetVisSubdivisions (G4int subdiv)
EInside Inside (const G4ThreeVector &p) const
G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=false, G4bool *validNorm=0, G4ThreeVector *n=0) const
G4double DistanceToOut (const G4ThreeVector &p) const
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pmin, G4double &pmax) const
G4GeometryType GetEntityType () const
G4VSolid * Clone () const
std::ostream & StreamInfo (std::ostream &os) const
G4ThreeVector GetPointOnSurface () const
G4double GetCubicVolume ()
G4double GetSurfaceArea ()
G4Polyhedron * GetPolyhedron () const
void DescribeYourselfTo (G4VGraphicsScene &scene) const
G4VisExtent GetExtent () const
G4Polyhedron * CreatePolyhedron () const
G4GenericTrap (__void__ &)
G4GenericTrap (const G4GenericTrap &rhs)
G4GenericTrap & operator= (const G4GenericTrap &rhs)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
virtual void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
void DumpInfo () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Protected Attributes
G4bool fRebuildPolyhedron
G4Polyhedron * fpPolyhedron
Protected Attributes inherited from G4VSolid
G4double kCarTolerance
Private Types
enum ESide {
kUndefined, kXY0, kXY1, kXY2,
kXY3, kMZ, kPZ
}
Private Member Functions
void SetTwistAngle (G4int index, G4double twist)
G4bool ComputeIsTwisted ()
G4bool CheckOrder (const std::vector< G4TwoVector > &vertices) const
G4bool IsSegCrossing (const G4TwoVector &a, const G4TwoVector &b, const G4TwoVector &c, const G4TwoVector &d) const
G4bool IsSegCrossingZ (const G4TwoVector &a, const G4TwoVector &b, const G4TwoVector &c, const G4TwoVector &d) const
void ReorderVertices (std::vector< G4ThreeVector > &vertices) const
void ComputeBBox ()
G4ThreeVector GetMinimumBBox () const
G4ThreeVector GetMaximumBBox () const
G4VFacet * MakeDownFacet (const std::vector< G4ThreeVector > &fromVertices, G4int ind1, G4int ind2, G4int ind3) const
G4VFacet * MakeUpFacet (const std::vector< G4ThreeVector > &fromVertices, G4int ind1, G4int ind2, G4int ind3) const
G4VFacet * MakeSideFacet (const G4ThreeVector &downVertex0, const G4ThreeVector &downVertex1, const G4ThreeVector &upVertex1, const G4ThreeVector &upVertex0) const
G4TessellatedSolid * CreateTessellatedSolid () const
EInside InsidePolygone (const G4ThreeVector &p, const std::vector< G4TwoVector > &poly) const
G4double DistToPlane (const G4ThreeVector &p, const G4ThreeVector &v, const G4int ipl) const
G4double DistToTriangle (const G4ThreeVector &p, const G4ThreeVector &v, const G4int ipl) const
G4ThreeVector NormalToPlane (const G4ThreeVector &p, const G4int ipl) const
G4double SafetyToFace (const G4ThreeVector &p, const G4int iseg) const
G4double GetFaceSurfaceArea (const G4ThreeVector &p0, const G4ThreeVector &p1, const G4ThreeVector &p2, const G4ThreeVector &p3) const
G4double GetFaceCubicVolume (const G4ThreeVector &p0, const G4ThreeVector &p1, const G4ThreeVector &p2, const G4ThreeVector &p3) const
Private Attributes
G4double halfCarTolerance
G4double fDz
std::vector< G4TwoVector > fVertices
G4bool fIsTwisted
G4double fTwist [4]
G4TessellatedSolid * fTessellatedSolid
G4ThreeVector fMinBBoxVector
G4ThreeVector fMaxBBoxVector
G4int fVisSubdivisions
G4double fSurfaceArea
G4double fCubicVolume
Static Private Attributes
static const G4int fgkNofVertices = 8
static const G4double fgkTolerance = 1E-3
Additional Inherited Members
Protected Member Functions inherited from G4VSolid
void CalculateClippedPolygonExtent (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipCrossSection (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipBetweenSections (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipPolygon (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis) const
Detailed Description
Definition at line 87 of file G4GenericTrap.hh.
Member Enumeration Documentation
ESide
enum G4GenericTrap::ESide private
Enumerator
kUndefined
kXY0
kXY1
kXY2
kXY3
kMZ
kPZ
Definition at line 225 of file G4GenericTrap.hh.
Constructor & Destructor Documentation
G4GenericTrap() [1/3]
G4GenericTrap::G4GenericTrap (const G4String & name, G4double halfZ, const std::vector< G4TwoVector > & vertices)
Definition at line 80 of file G4GenericTrap.cc.
Referenced by Clone().
~G4GenericTrap()
G4GenericTrap::~G4GenericTrap ()
Definition at line 195 of file G4GenericTrap.cc.
G4GenericTrap() [2/3]
G4GenericTrap::G4GenericTrap (__void__ & a)
Definition at line 174 of file G4GenericTrap.cc.
G4GenericTrap() [3/3]
G4GenericTrap::G4GenericTrap (const G4GenericTrap & rhs)
Definition at line 203 of file G4GenericTrap.cc.
Member Function Documentation
BoundingLimits()
void G4GenericTrap::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 1214 of file G4GenericTrap.cc.
Referenced by CalculateExtent().
CalculateExtent()
G4bool G4GenericTrap::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pmin, G4double & pmax) const virtual
Implements G4VSolid.
Definition at line 1238 of file G4GenericTrap.cc.
CheckOrder()
G4bool G4GenericTrap::CheckOrder (const std::vector< G4TwoVector > & vertices) const private
Definition at line 1553 of file G4GenericTrap.cc.
Referenced by G4GenericTrap().
Clone()
G4VSolid * G4GenericTrap::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 1304 of file G4GenericTrap.cc.
ComputeBBox()
void G4GenericTrap::ComputeBBox () private
Definition at line 1952 of file G4GenericTrap.cc.
Referenced by G4GenericTrap().
ComputeIsTwisted()
G4bool G4GenericTrap::ComputeIsTwisted () private
Definition at line 1505 of file G4GenericTrap.cc.
Referenced by G4GenericTrap().
CreatePolyhedron()
G4Polyhedron * G4GenericTrap::CreatePolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 2034 of file G4GenericTrap.cc.
Referenced by GetPolyhedron().
CreateTessellatedSolid()
G4TessellatedSolid * G4GenericTrap::CreateTessellatedSolid () const private
Definition at line 1891 of file G4GenericTrap.cc.
Referenced by G4GenericTrap(), and operator=().
DescribeYourselfTo()
void G4GenericTrap::DescribeYourselfTo (G4VGraphicsScene & scene) const virtual
Implements G4VSolid.
Definition at line 1999 of file G4GenericTrap.cc.
DistanceToIn() [1/2]
G4double G4GenericTrap::DistanceToIn (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 838 of file G4GenericTrap.cc.
DistanceToIn() [2/2]
G4double G4GenericTrap::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Implements G4VSolid.
Definition at line 770 of file G4GenericTrap.cc.
DistanceToOut() [1/2]
G4double G4GenericTrap::DistanceToOut (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 1187 of file G4GenericTrap.cc.
DistanceToOut() [2/2]
G4double G4GenericTrap::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcNorm = false, G4bool * validNorm = 0, G4ThreeVector * n = 0) const virtual
Implements G4VSolid.
Definition at line 942 of file G4GenericTrap.cc.
DistToPlane()
G4double G4GenericTrap::DistToPlane (const G4ThreeVector & p, const G4ThreeVector & v, const G4int ipl) const private
Definition at line 612 of file G4GenericTrap.cc.
Referenced by DistanceToIn().
DistToTriangle()
G4double G4GenericTrap::DistToTriangle (const G4ThreeVector & p, const G4ThreeVector & v, const G4int ipl) const private
Definition at line 887 of file G4GenericTrap.cc.
Referenced by DistanceToOut().
GetCubicVolume()
G4double G4GenericTrap::GetCubicVolume () virtual
Reimplemented from G4VSolid.
Definition at line 1452 of file G4GenericTrap.cc.
GetEntityType()
G4GeometryType G4GenericTrap::GetEntityType () const virtual
Implements G4VSolid.
Definition at line 1297 of file G4GenericTrap.cc.
Referenced by StreamInfo().
GetExtent()
G4VisExtent G4GenericTrap::GetExtent () const virtual
Reimplemented from G4VSolid.
Definition at line 2014 of file G4GenericTrap.cc.
GetFaceCubicVolume()
G4double G4GenericTrap::GetFaceCubicVolume (const G4ThreeVector & p0, const G4ThreeVector & p1, const G4ThreeVector & p2, const G4ThreeVector & p3) const private
Definition at line 1493 of file G4GenericTrap.cc.
Referenced by GetCubicVolume().
GetFaceSurfaceArea()
G4double G4GenericTrap::GetFaceSurfaceArea (const G4ThreeVector & p0, const G4ThreeVector & p1, const G4ThreeVector & p2, const G4ThreeVector & p3) const private
Definition at line 1482 of file G4GenericTrap.cc.
Referenced by GetPointOnSurface(), and GetSurfaceArea().
GetMaximumBBox()
G4ThreeVector G4GenericTrap::GetMaximumBBox () const inline private
Referenced by BoundingLimits(), CreatePolyhedron(), and GetExtent().
GetMinimumBBox()
G4ThreeVector G4GenericTrap::GetMinimumBBox () const inline private
Referenced by BoundingLimits(), CreatePolyhedron(), and GetExtent().
GetNofVertices()
G4int G4GenericTrap::GetNofVertices () const inline
GetPointOnSurface()
G4ThreeVector G4GenericTrap::GetPointOnSurface () const virtual
Reimplemented from G4VSolid.
Definition at line 1334 of file G4GenericTrap.cc.
GetPolyhedron()
G4Polyhedron * G4GenericTrap::GetPolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 1973 of file G4GenericTrap.cc.
GetSurfaceArea()
G4double G4GenericTrap::GetSurfaceArea () virtual
Reimplemented from G4VSolid.
Definition at line 1422 of file G4GenericTrap.cc.
GetTwistAngle()
G4double G4GenericTrap::GetTwistAngle (G4int index) const inline
Referenced by CreatePolyhedron(), NormalToPlane(), and SurfaceNormal().
GetVertex()
G4TwoVector G4GenericTrap::GetVertex (G4int index) const inline
Referenced by CalculateExtent().
GetVertices()
const std::vector<G4TwoVector>& G4GenericTrap::GetVertices () const inline
Referenced by G4GDMLWriteSolids::GenTrapWrite().
GetVisSubdivisions()
G4int G4GenericTrap::GetVisSubdivisions () const inline
Referenced by CreatePolyhedron().
GetZHalfLength()
G4double G4GenericTrap::GetZHalfLength () const inline
Referenced by CalculateExtent(), and G4GDMLWriteSolids::GenTrapWrite().
Inside()
EInside G4GenericTrap::Inside (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 356 of file G4GenericTrap.cc.
Referenced by DistanceToIn(), DistToPlane(), and DistToTriangle().
InsidePolygone()
EInside G4GenericTrap::InsidePolygone (const G4ThreeVector & p, const std::vector< G4TwoVector > & poly) const private
Definition at line 255 of file G4GenericTrap.cc.
Referenced by DistanceToOut(), and Inside().
IsSegCrossing()
G4bool G4GenericTrap::IsSegCrossing (const G4TwoVector & a, const G4TwoVector & b, const G4TwoVector & c, const G4TwoVector & d) const private
Definition at line 1649 of file G4GenericTrap.cc.
Referenced by CheckOrder().
IsSegCrossingZ()
G4bool G4GenericTrap::IsSegCrossingZ (const G4TwoVector & a, const G4TwoVector & b, const G4TwoVector & c, const G4TwoVector & d) const private
Definition at line 1739 of file G4GenericTrap.cc.
Referenced by CheckOrder().
IsTwisted()
G4bool G4GenericTrap::IsTwisted () const inline
MakeDownFacet()
G4VFacet * G4GenericTrap::MakeDownFacet (const std::vector< G4ThreeVector > & fromVertices, G4int ind1, G4int ind2, G4int ind3) const private
Definition at line 1789 of file G4GenericTrap.cc.
Referenced by CreateTessellatedSolid().
MakeSideFacet()
G4VFacet * G4GenericTrap::MakeSideFacet (const G4ThreeVector & downVertex0, const G4ThreeVector & downVertex1, const G4ThreeVector & upVertex1, const G4ThreeVector & upVertex0) const private
Definition at line 1862 of file G4GenericTrap.cc.
Referenced by CreateTessellatedSolid().
MakeUpFacet()
G4VFacet * G4GenericTrap::MakeUpFacet (const std::vector< G4ThreeVector > & fromVertices, G4int ind1, G4int ind2, G4int ind3) const private
Definition at line 1825 of file G4GenericTrap.cc.
Referenced by CreateTessellatedSolid().
NormalToPlane()
G4ThreeVector G4GenericTrap::NormalToPlane (const G4ThreeVector & p, const G4int ipl) const private
Definition at line 527 of file G4GenericTrap.cc.
Referenced by DistanceToOut(), DistToPlane(), DistToTriangle(), and SafetyToFace().
operator=()
G4GenericTrap & G4GenericTrap::operator= (const G4GenericTrap & rhs)
Definition at line 222 of file G4GenericTrap.cc.
ReorderVertices()
void G4GenericTrap::ReorderVertices (std::vector< G4ThreeVector > & vertices) const private
Definition at line 1634 of file G4GenericTrap.cc.
Referenced by CreateTessellatedSolid().
SafetyToFace()
G4double G4GenericTrap::SafetyToFace (const G4ThreeVector & p, const G4int iseg) const private
Definition at line 868 of file G4GenericTrap.cc.
Referenced by DistanceToIn(), and DistanceToOut().
SetTwistAngle()
void G4GenericTrap::SetTwistAngle (G4int index, G4double twist) inline private
Referenced by ComputeIsTwisted().
SetVisSubdivisions()
void G4GenericTrap::SetVisSubdivisions (G4int subdiv) inline
StreamInfo()
std::ostream & G4GenericTrap::StreamInfo (std::ostream & os) const virtual
Implements G4VSolid.
Definition at line 1311 of file G4GenericTrap.cc.
SurfaceNormal()
G4ThreeVector G4GenericTrap::SurfaceNormal (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 392 of file G4GenericTrap.cc.
Field Documentation
fCubicVolume
G4double G4GenericTrap::fCubicVolume private
Definition at line 229 of file G4GenericTrap.hh.
Referenced by GetCubicVolume(), and operator=().
fDz
G4double G4GenericTrap::fDz private
Definition at line 216 of file G4GenericTrap.hh.
Referenced by ComputeBBox(), CreatePolyhedron(), CreateTessellatedSolid(), DistanceToIn(), DistanceToOut(), DistToPlane(), DistToTriangle(), GetCubicVolume(), GetPointOnSurface(), GetSurfaceArea(), Inside(), IsSegCrossingZ(), NormalToPlane(), operator=(), SafetyToFace(), StreamInfo(), and SurfaceNormal().
fgkNofVertices
const G4int G4GenericTrap::fgkNofVertices = 8 static private
Definition at line 209 of file G4GenericTrap.hh.
Referenced by ComputeBBox(), ComputeIsTwisted(), CreateTessellatedSolid(), G4GenericTrap(), and StreamInfo().
fgkTolerance
const G4double G4GenericTrap::fgkTolerance = 1E-3 static private
Definition at line 210 of file G4GenericTrap.hh.
Referenced by CheckOrder(), ComputeIsTwisted(), and IsSegCrossing().
fIsTwisted
G4bool G4GenericTrap::fIsTwisted private
Definition at line 218 of file G4GenericTrap.hh.
Referenced by CreatePolyhedron(), G4GenericTrap(), GetCubicVolume(), GetSurfaceArea(), NormalToPlane(), operator=(), and SurfaceNormal().
fMaxBBoxVector
G4ThreeVector G4GenericTrap::fMaxBBoxVector private
Definition at line 222 of file G4GenericTrap.hh.
Referenced by ComputeBBox(), and operator=().
fMinBBoxVector
G4ThreeVector G4GenericTrap::fMinBBoxVector private
Definition at line 221 of file G4GenericTrap.hh.
Referenced by ComputeBBox(), and operator=().
fpPolyhedron
G4Polyhedron* G4GenericTrap::fpPolyhedron mutable protected
Definition at line 203 of file G4GenericTrap.hh.
Referenced by GetPolyhedron(), and operator=().
fRebuildPolyhedron
G4bool G4GenericTrap::fRebuildPolyhedron mutable protected
Definition at line 202 of file G4GenericTrap.hh.
Referenced by GetPolyhedron(), and operator=().
fSurfaceArea
G4double G4GenericTrap::fSurfaceArea private
Definition at line 228 of file G4GenericTrap.hh.
Referenced by GetSurfaceArea(), and operator=().
fTessellatedSolid
G4TessellatedSolid* G4GenericTrap::fTessellatedSolid private
Definition at line 220 of file G4GenericTrap.hh.
Referenced by CreatePolyhedron(), DescribeYourselfTo(), DistanceToIn(), DistanceToOut(), G4GenericTrap(), GetExtent(), GetPointOnSurface(), GetPolyhedron(), Inside(), NormalToPlane(), operator=(), SurfaceNormal(), and ~G4GenericTrap().
fTwist
G4double G4GenericTrap::fTwist[4] private
Definition at line 219 of file G4GenericTrap.hh.
Referenced by G4GenericTrap(), and operator=().
fVertices
std::vector<G4TwoVector> G4GenericTrap::fVertices private
Definition at line 217 of file G4GenericTrap.hh.
Referenced by ComputeBBox(), ComputeIsTwisted(), CreatePolyhedron(), CreateTessellatedSolid(), DistanceToOut(), DistToPlane(), DistToTriangle(), G4GenericTrap(), GetCubicVolume(), GetPointOnSurface(), GetSurfaceArea(), Inside(), NormalToPlane(), operator=(), SafetyToFace(), StreamInfo(), and SurfaceNormal().
fVisSubdivisions
G4int G4GenericTrap::fVisSubdivisions private
Definition at line 223 of file G4GenericTrap.hh.
Referenced by operator=().
halfCarTolerance
G4double G4GenericTrap::halfCarTolerance private
Definition at line 212 of file G4GenericTrap.hh.
Referenced by DistanceToIn(), DistanceToOut(), DistToPlane(), DistToTriangle(), G4GenericTrap(), Inside(), InsidePolygone(), NormalToPlane(), operator=(), and SurfaceNormal().
The documentation for this class was generated from the following files:
source/geometry/solids/specific/include/G4GenericTrap.hh
source/geometry/solids/specific/src/G4GenericTrap.cc