Geant4: source/processes/electromagnetic/dna/molecules/management/include/G4Molecule.hh File Reference
G4Molecule.hh File Reference
#include "G4IT.hh"
#include "G4Allocator.hh"
#include "G4MoleculeDefinition.hh"
Data Structures
class G4Molecule
Class Description The dynamic molecule holds all the data that change for a molecule It has a pointer to G4MoleculeDefinition object, which holds all the "ground level" information.
Functions
G4Molecule * GetMolecule (const G4Track &track)
G4Molecule * GetMolecule (const G4Track *track)
G4DLLIMPORT G4Allocator< G4Molecule > *& aMoleculeAllocator ()
Function Documentation
aMoleculeAllocator()
G4DLLIMPORT G4Allocator<G4Molecule>*& aMoleculeAllocator ()
Referenced by G4Molecule::operator delete(), and G4Molecule::operator new().
GetMolecule() [1/2]
G4Molecule* GetMolecule (const G4Track & track)
Definition at line 79 of file G4Molecule.cc.
Referenced by G4DNABrownianTransportation::AlongStepDoIt(), G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength(), G4DNAMoleculeEncounterStepper::CalculateStep(), G4DNABrownianTransportation::ComputeStep(), G4DNAMolecularDissociation::DecayIt(), G4DNABrownianTransportation::Diffusion(), G4DNAElectronHoleRecombination::FindReactant(), G4DNASmoluchowskiReactionModel::FindReaction(), G4DNAMolecularDissociation::GetMeanLifeTime(), G4DNAMolecularReaction::MakeReaction(), G4DNAElectronHoleRecombination::MakeReaction(), G4DNASecondOrderReaction::PostStepDoIt(), G4DNABrownianTransportation::PostStepDoIt(), G4DNASecondOrderReaction::PostStepGetPhysicalInteractionLength(), G4DNAMolecularReaction::TestReactibility(), and G4DNAMoleculeEncounterStepper::Utils::Utils().
GetMolecule() [2/2]
G4Molecule* GetMolecule (const G4Track * track)
Definition at line 86 of file G4Molecule.cc.