Geant4: G4TRNtupleManager< TNTUPLE > Class Template Reference
G4TRNtupleManager< TNTUPLE > Class Template Reference abstract
#include <G4TRNtupleManager.hh>
Protected Member Functions
G4TRNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4TRNtupleManager ()
G4bool IsEmpty () const
G4bool Reset ()
TNTUPLE * GetNtuple () const
TNTUPLE * GetNtuple (G4int ntupleId) const
G4int SetNtuple (G4TRNtupleDescription< TNTUPLE > *rntupleDescription)
virtual G4bool SetNtupleIColumn (G4int ntupleId, const G4String &columnName, G4int &value) final
virtual G4bool SetNtupleFColumn (G4int ntupleId, const G4String &columnName, G4float &value) final
virtual G4bool SetNtupleDColumn (G4int ntupleId, const G4String &columnName, G4double &value) final
virtual G4bool SetNtupleSColumn (G4int ntupleId, const G4String &columnName, G4String &value) final
virtual G4bool SetNtupleIColumn (G4int ntupleId, const G4String &columnName, std::vector< G4int > &vector) override
virtual G4bool SetNtupleFColumn (G4int ntupleId, const G4String &columnName, std::vector< G4float > &vector) override
virtual G4bool SetNtupleDColumn (G4int ntupleId, const G4String &columnName, std::vector< G4double > &vector) override
virtual G4bool GetNtupleRow (G4int ntupleId) final
virtual G4int GetNofNtuples () const final
G4TRNtupleDescription< TNTUPLE > * GetNtupleDescriptionInFunction (G4int id, G4String function, G4bool warn=true) const
virtual G4bool SetNtupleIColumn (const G4String &columnName, G4int &value) final
virtual G4bool SetNtupleIColumn (G4int ntupleId, const G4String &columnName, G4int &value)=0
virtual G4bool SetNtupleIColumn (const G4String &columnName, std::vector< G4int > &vector) final
virtual G4bool SetNtupleIColumn (G4int ntupleId, const G4String &columnName, std::vector< G4int > &vector)=0
virtual G4bool SetNtupleFColumn (const G4String &columnName, G4float &value) final
virtual G4bool SetNtupleFColumn (G4int ntupleId, const G4String &columnName, G4float &value)=0
virtual G4bool SetNtupleFColumn (const G4String &columnName, std::vector< G4float > &vector) final
virtual G4bool SetNtupleFColumn (G4int ntupleId, const G4String &columnName, std::vector< G4float > &vector)=0
virtual G4bool SetNtupleDColumn (const G4String &columnName, G4double &value) final
virtual G4bool SetNtupleDColumn (G4int ntupleId, const G4String &columnName, G4double &value)=0
virtual G4bool SetNtupleDColumn (const G4String &columnName, std::vector< G4double > &vector) final
virtual G4bool SetNtupleDColumn (G4int ntupleId, const G4String &columnName, std::vector< G4double > &vector)=0
virtual G4bool SetNtupleSColumn (const G4String &columnName, G4String &value) final
virtual G4bool SetNtupleSColumn (G4int ntupleId, const G4String &columnName, G4String &value)=0
virtual G4bool GetNtupleRow () final
virtual G4bool GetNtupleRow (G4int ntupleId)=0
Protected Member Functions inherited from G4BaseRNtupleManager
virtual G4bool SetNtupleIColumn (const G4String &columnName, G4int &value) final
virtual G4bool SetNtupleFColumn (const G4String &columnName, G4float &value) final
virtual G4bool SetNtupleDColumn (const G4String &columnName, G4double &value) final
virtual G4bool SetNtupleSColumn (const G4String &columnName, G4String &value) final
virtual G4bool SetNtupleIColumn (const G4String &columnName, std::vector< G4int > &vector) final
virtual G4bool SetNtupleFColumn (const G4String &columnName, std::vector< G4float > &vector) final
virtual G4bool SetNtupleDColumn (const G4String &columnName, std::vector< G4double > &vector) final
virtual G4bool GetNtupleRow () final
Private Member Functions
virtual G4bool GetTNtupleRow (G4TRNtupleDescription< TNTUPLE > *rntupleDescription)=0
template<typename T >
G4bool SetNtupleTColumn (G4int ntupleId, const G4String &name, T &value)
template<typename T >
G4bool SetNtupleTColumn (G4int ntupleId, const G4String &name, std::vector< T > &vector)
Private Attributes
std::vector< G4TRNtupleDescription< TNTUPLE > * > fNtupleDescriptionVector
Additional Inherited Members
Public Member Functions inherited from G4BaseRNtupleManager
G4BaseRNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4BaseRNtupleManager ()
G4BaseRNtupleManager (const G4BaseRNtupleManager &rhs)=delete
G4BaseRNtupleManager & operator= (const G4BaseRNtupleManager &rhs)=delete
Public Member Functions inherited from G4VRNtupleManager
G4VRNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4VRNtupleManager ()
G4VRNtupleManager (const G4VRNtupleManager &rhs)=delete
G4VRNtupleManager & operator= (const G4VRNtupleManager &rhs)=delete
Public Member Functions inherited from G4BaseAnalysisManager
G4BaseAnalysisManager (const G4AnalysisManagerState &state)
virtual ~G4BaseAnalysisManager ()
G4bool SetFirstId (G4int firstId)
void SetLockFirstId (G4bool lockFirstId)
G4int GetFirstId () const
Protected Attributes inherited from G4BaseAnalysisManager
const G4AnalysisManagerState & fState
G4int fFirstId
G4bool fLockFirstId
Detailed Description
template<typename TNTUPLE>
class G4TRNtupleManager< TNTUPLE >
Definition at line 41 of file G4TRNtupleManager.hh.
Constructor & Destructor Documentation
G4TRNtupleManager()
template<typename TNTUPLE> G4TRNtupleManager< TNTUPLE >::G4TRNtupleManager (const G4AnalysisManagerState & state) explicit protected
~G4TRNtupleManager()
template<typename TNTUPLE> virtual G4TRNtupleManager< TNTUPLE >::~G4TRNtupleManager () protected virtual
Member Function Documentation
GetNofNtuples()
template<typename TNTUPLE> virtual G4int G4TRNtupleManager< TNTUPLE >::GetNofNtuples () const final protected virtual
Implements G4BaseRNtupleManager.
GetNtuple() [1/2]
template<typename TNTUPLE> TNTUPLE* G4TRNtupleManager< TNTUPLE >::GetNtuple () const protected
GetNtuple() [2/2]
template<typename TNTUPLE> TNTUPLE* G4TRNtupleManager< TNTUPLE >::GetNtuple (G4int ntupleId) const protected
GetNtupleDescriptionInFunction()
template<typename TNTUPLE> G4TRNtupleDescription<TNTUPLE>* G4TRNtupleManager< TNTUPLE >::GetNtupleDescriptionInFunction (G4int id, G4String function, G4bool warn = true) const protected
GetNtupleRow() [1/3]
template<typename TNTUPLE> G4bool G4BaseRNtupleManager::GetNtupleRow final protected
Definition at line 100 of file G4BaseRNtupleManager.cc.
GetNtupleRow() [2/3]
template<typename TNTUPLE> virtual G4bool G4TRNtupleManager< TNTUPLE >::GetNtupleRow (G4int ntupleId) final protected virtual
Implements G4BaseRNtupleManager.
GetNtupleRow() [3/3]
template<typename TNTUPLE> virtual G4bool G4BaseRNtupleManager::GetNtupleRow protected
GetTNtupleRow()
template<typename TNTUPLE> virtual G4bool G4TRNtupleManager< TNTUPLE >::GetTNtupleRow (G4TRNtupleDescription< TNTUPLE > * rntupleDescription) private pure virtual
Implemented in G4RootRNtupleManager, G4CsvRNtupleManager, G4Hdf5RNtupleManager, and G4XmlRNtupleManager.
IsEmpty()
template<typename TNTUPLE> G4bool G4TRNtupleManager< TNTUPLE >::IsEmpty () const protected
Reset()
template<typename TNTUPLE> G4bool G4TRNtupleManager< TNTUPLE >::Reset () protected
Referenced by G4CsvAnalysisReader::Reset(), G4XmlAnalysisReader::Reset(), G4RootAnalysisReader::Reset(), and G4Hdf5AnalysisReader::Reset().
SetNtuple()
template<typename TNTUPLE> G4int G4TRNtupleManager< TNTUPLE >::SetNtuple (G4TRNtupleDescription< TNTUPLE > * rntupleDescription) protected
Referenced by G4CsvAnalysisReader::ReadNtupleImpl(), G4XmlAnalysisReader::ReadNtupleImpl(), G4RootAnalysisReader::ReadNtupleImpl(), and G4Hdf5AnalysisReader::ReadNtupleImpl().
SetNtupleDColumn() [1/6]
template<typename TNTUPLE> G4bool G4BaseRNtupleManager::SetNtupleDColumn final protected
Definition at line 65 of file G4BaseRNtupleManager.cc.
SetNtupleDColumn() [2/6]
template<typename TNTUPLE> G4bool G4BaseRNtupleManager::SetNtupleDColumn final protected
Definition at line 93 of file G4BaseRNtupleManager.cc.
SetNtupleDColumn() [3/6]
template<typename TNTUPLE> virtual G4bool G4TRNtupleManager< TNTUPLE >::SetNtupleDColumn (G4int ntupleId, const G4String & columnName, G4double & value) final protected virtual
Implements G4BaseRNtupleManager.
SetNtupleDColumn() [4/6]
template<typename TNTUPLE> virtual G4bool G4BaseRNtupleManager::SetNtupleDColumn protected
SetNtupleDColumn() [5/6]
template<typename TNTUPLE> virtual G4bool G4TRNtupleManager< TNTUPLE >::SetNtupleDColumn (G4int ntupleId, const G4String & columnName, std::vector< G4double > & vector) override protected virtual
Implements G4BaseRNtupleManager.
Reimplemented in G4XmlRNtupleManager.
SetNtupleDColumn() [6/6]
template<typename TNTUPLE> virtual G4bool G4BaseRNtupleManager::SetNtupleDColumn protected
SetNtupleFColumn() [1/6]
template<typename TNTUPLE> G4bool G4BaseRNtupleManager::SetNtupleFColumn final protected
Definition at line 58 of file G4BaseRNtupleManager.cc.
SetNtupleFColumn() [2/6]
template<typename TNTUPLE> G4bool G4BaseRNtupleManager::SetNtupleFColumn final protected
Definition at line 86 of file G4BaseRNtupleManager.cc.
SetNtupleFColumn() [3/6]
template<typename TNTUPLE> virtual G4bool G4TRNtupleManager< TNTUPLE >::SetNtupleFColumn (G4int ntupleId, const G4String & columnName, G4float & value) final protected virtual
Implements G4BaseRNtupleManager.
SetNtupleFColumn() [4/6]
template<typename TNTUPLE> virtual G4bool G4BaseRNtupleManager::SetNtupleFColumn protected
SetNtupleFColumn() [5/6]
template<typename TNTUPLE> virtual G4bool G4TRNtupleManager< TNTUPLE >::SetNtupleFColumn (G4int ntupleId, const G4String & columnName, std::vector< G4float > & vector) override protected virtual
Implements G4BaseRNtupleManager.
Reimplemented in G4XmlRNtupleManager.
SetNtupleFColumn() [6/6]
template<typename TNTUPLE> virtual G4bool G4BaseRNtupleManager::SetNtupleFColumn protected
SetNtupleIColumn() [1/6]
template<typename TNTUPLE> G4bool G4BaseRNtupleManager::SetNtupleIColumn final protected
Definition at line 52 of file G4BaseRNtupleManager.cc.
SetNtupleIColumn() [2/6]
template<typename TNTUPLE> G4bool G4BaseRNtupleManager::SetNtupleIColumn final protected
Definition at line 79 of file G4BaseRNtupleManager.cc.
SetNtupleIColumn() [3/6]
template<typename TNTUPLE> virtual G4bool G4TRNtupleManager< TNTUPLE >::SetNtupleIColumn (G4int ntupleId, const G4String & columnName, G4int & value) final protected virtual
Implements G4BaseRNtupleManager.
SetNtupleIColumn() [4/6]
template<typename TNTUPLE> virtual G4bool G4BaseRNtupleManager::SetNtupleIColumn protected
SetNtupleIColumn() [5/6]
template<typename TNTUPLE> virtual G4bool G4TRNtupleManager< TNTUPLE >::SetNtupleIColumn (G4int ntupleId, const G4String & columnName, std::vector< G4int > & vector) override protected virtual
Implements G4BaseRNtupleManager.
Reimplemented in G4XmlRNtupleManager.
SetNtupleIColumn() [6/6]
template<typename TNTUPLE> virtual G4bool G4BaseRNtupleManager::SetNtupleIColumn protected
SetNtupleSColumn() [1/3]
template<typename TNTUPLE> G4bool G4BaseRNtupleManager::SetNtupleSColumn final protected
Definition at line 72 of file G4BaseRNtupleManager.cc.
SetNtupleSColumn() [2/3]
template<typename TNTUPLE> virtual G4bool G4TRNtupleManager< TNTUPLE >::SetNtupleSColumn (G4int ntupleId, const G4String & columnName, G4String & value) final protected virtual
Implements G4BaseRNtupleManager.
SetNtupleSColumn() [3/3]
template<typename TNTUPLE> virtual G4bool G4BaseRNtupleManager::SetNtupleSColumn protected
SetNtupleTColumn() [1/2]
template<typename TNTUPLE> template<typename T > G4bool G4TRNtupleManager< TNTUPLE >::SetNtupleTColumn (G4int ntupleId, const G4String & name, std::vector< T > & vector) private
SetNtupleTColumn() [2/2]
template<typename TNTUPLE> template<typename T > G4bool G4TRNtupleManager< TNTUPLE >::SetNtupleTColumn (G4int ntupleId, const G4String & name, T & value) private
Field Documentation
fNtupleDescriptionVector
template<typename TNTUPLE> std::vector<G4TRNtupleDescription<TNTUPLE>*> G4TRNtupleManager< TNTUPLE >::fNtupleDescriptionVector private
Definition at line 111 of file G4TRNtupleManager.hh.
The documentation for this class was generated from the following file:
source/analysis/management/include/G4TRNtupleManager.hh