Geant4: G4INCL::IPropagationModel Class Reference
G4INCL::IPropagationModel Class Reference abstract
Propagation model takes care of transporting the particles until something interesting (i.e.
#include <G4INCLIPropagationModel.hh>
Public Member Functions
IPropagationModel ()
virtual ~IPropagationModel ()
virtual void setNucleus (G4INCL::Nucleus *nucleus)=0
Set the nucleus for the propagation model.
virtual G4INCL::Nucleus * getNucleus ()=0
Get a pointer to the nucleus.
virtual G4double shoot (ParticleSpecies const &projectileSpecies, const G4double kineticEnergy, const G4double impactParameter, const G4double phi)=0
virtual G4double getCurrentTime ()=0
Returns the current global time of the system.
virtual void setStoppingTime (G4double)=0
Set new stopping time to the propagation.
virtual G4double getStoppingTime ()=0
Get the current stopping time.
virtual G4INCL::IAvatar * propagate (FinalState const *const fs)=0
Propagate the particles and get the next avatar.
Protected Member Functions
virtual G4double shootParticle (ParticleType const t, const G4double kineticEnergy, const G4double impactParameter, const G4double phi)=0
virtual G4double shootComposite (ParticleSpecies const &s, const G4double kineticEnergy, const G4double impactParameter, const G4double phi)=0
Detailed Description
Propagation model takes care of transporting the particles until something interesting (i.e.
an avatar) happens. This avatar is then returned back to the INCL kernel for further processing.
The propagation model idea abstracts the details of propagation. This allows us to conveniently support multiple propagation models and to compare their results. Some possible future propagation models are: straight line trajectories by using constant time step and curved trajectories.
Definition at line 64 of file G4INCLIPropagationModel.hh.
Constructor & Destructor Documentation
IPropagationModel()
G4INCL::IPropagationModel::IPropagationModel () inline
Definition at line 66 of file G4INCLIPropagationModel.hh.
~IPropagationModel()
virtual G4INCL::IPropagationModel::~IPropagationModel () inline virtual
Definition at line 67 of file G4INCLIPropagationModel.hh.
Member Function Documentation
getCurrentTime()
virtual G4double G4INCL::IPropagationModel::getCurrentTime () pure virtual
Returns the current global time of the system.
Implemented in G4INCL::StandardPropagationModel.
Referenced by G4INCL::INCL::continueCascade(), G4INCL::INCL::makeCompoundNucleus(), G4INCL::INCL::makeProjectileRemnant(), and G4INCL::INCL::postCascade().
getNucleus()
virtual G4INCL::Nucleus* G4INCL::IPropagationModel::getNucleus () pure virtual
Get a pointer to the nucleus.
Returns
G4INCL::Nuleus*
Implemented in G4INCL::StandardPropagationModel.
getStoppingTime()
virtual G4double G4INCL::IPropagationModel::getStoppingTime () pure virtual
Get the current stopping time.
Implemented in G4INCL::StandardPropagationModel.
Referenced by G4INCL::INCL::continueCascade().
propagate()
virtual G4INCL::IAvatar* G4INCL::IPropagationModel::propagate (FinalState const *const fs) pure virtual
Propagate the particles and get the next avatar.
Returns
G4INCL::IAvatar the next avatar
Implemented in G4INCL::StandardPropagationModel.
Referenced by G4INCL::INCL::cascade().
setNucleus()
virtual void G4INCL::IPropagationModel::setNucleus (G4INCL::Nucleus * nucleus) pure virtual
Set the nucleus for the propagation model.
Parameters
nucleus Pointer to the nucleus
Implemented in G4INCL::StandardPropagationModel.
Referenced by G4INCL::INCL::initializeTarget().
setStoppingTime()
virtual void G4INCL::IPropagationModel::setStoppingTime (G4double) pure virtual
Set new stopping time to the propagation.
Implemented in G4INCL::StandardPropagationModel.
shoot()
virtual G4double G4INCL::IPropagationModel::shoot (ParticleSpecies const & projectileSpecies, const G4double kineticEnergy, const G4double impactParameter, const G4double phi) pure virtual
Implemented in G4INCL::StandardPropagationModel.
Referenced by G4INCL::INCL::preCascade().
shootComposite()
virtual G4double G4INCL::IPropagationModel::shootComposite (ParticleSpecies const & s, const G4double kineticEnergy, const G4double impactParameter, const G4double phi) protected pure virtual
Implemented in G4INCL::StandardPropagationModel.
shootParticle()
virtual G4double G4INCL::IPropagationModel::shootParticle (ParticleType const t, const G4double kineticEnergy, const G4double impactParameter, const G4double phi) protected pure virtual
Implemented in G4INCL::StandardPropagationModel.
The documentation for this class was generated from the following file:
source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLIPropagationModel.hh