Geant4: G4HadronElastic Class Reference
G4HadronElastic Class Reference
#include <G4HadronElastic.hh>
Public Member Functions
G4HadronElastic (const G4String &name="hElasticLHEP")
virtual ~G4HadronElastic ()
virtual G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
void SetLowestEnergyLimit (G4double value)
G4double LowestEnergyLimit () const
G4double ComputeMomentumCMS (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual void ModelDescription (std::ostream &) const
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double, G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Attributes
G4ParticleDefinition * theProton
G4ParticleDefinition * theNeutron
G4ParticleDefinition * theDeuteron
G4ParticleDefinition * theAlpha
G4double lowestEnergyLimit
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 49 of file G4HadronElastic.hh.
Constructor & Destructor Documentation
G4HadronElastic()
G4HadronElastic::G4HadronElastic (const G4String & name = "hElasticLHEP")
Definition at line 48 of file G4HadronElastic.cc.
~G4HadronElastic()
G4HadronElastic::~G4HadronElastic () virtual
Definition at line 61 of file G4HadronElastic.cc.
Member Function Documentation
ApplyYourself()
G4HadFinalState * G4HadronElastic::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) virtual
Implements G4HadronicInteraction.
Reimplemented in G4LEnp, G4NeutronElectronElModel, G4LEHadronProtonElastic, G4LEpp, and G4NeutrinoElectronNcModel.
Definition at line 77 of file G4HadronElastic.cc.
ComputeMomentumCMS()
G4double G4HadronElastic::ComputeMomentumCMS (const G4ParticleDefinition * p, G4double plab, G4int Z, G4int A) inline
Definition at line 97 of file G4HadronElastic.hh.
Referenced by SampleInvariantT().
LowestEnergyLimit()
G4double G4HadronElastic::LowestEnergyLimit () const inline
Definition at line 91 of file G4HadronElastic.hh.
Referenced by G4NeutrinoElectronNcModel::ApplyYourself(), and G4NeutronElectronElModel::ApplyYourself().
ModelDescription()
void G4HadronElastic::ModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4HadronicInteraction.
Reimplemented in G4ElasticHadrNucleusHE, G4NeutronElectronElModel, G4NeutrinoElectronNcModel, and G4ChipsElasticModel.
Definition at line 65 of file G4HadronElastic.cc.
SampleInvariantT()
G4double G4HadronElastic::SampleInvariantT (const G4ParticleDefinition * p, G4double plab, G4int Z, G4int A) virtual
Reimplemented from G4HadronicInteraction.
Reimplemented in G4hhElastic, G4ElasticHadrNucleusHE, G4DiffuseElastic, G4DiffuseElasticV2, G4NuclNuclDiffuseElastic, G4LEnp, G4LEHadronProtonElastic, G4LEpp, G4ChipsElasticModel, and G4AntiNuclElastic.
Definition at line 193 of file G4HadronElastic.cc.
Referenced by ApplyYourself(), and G4ChipsElasticModel::SampleInvariantT().
SetLowestEnergyLimit()
void G4HadronElastic::SetLowestEnergyLimit (G4double value) inline
Definition at line 86 of file G4HadronElastic.hh.
Referenced by G4NeutrinoElectronNcModel::G4NeutrinoElectronNcModel(), and G4NeutronElectronElModel::G4NeutronElectronElModel().
Field Documentation
lowestEnergyLimit
G4double G4HadronElastic::lowestEnergyLimit private
Definition at line 82 of file G4HadronElastic.hh.
Referenced by ApplyYourself(), G4HadronElastic(), LowestEnergyLimit(), and SetLowestEnergyLimit().
theAlpha
G4ParticleDefinition* G4HadronElastic::theAlpha private
Definition at line 80 of file G4HadronElastic.hh.
Referenced by ApplyYourself(), and G4HadronElastic().
theDeuteron
G4ParticleDefinition* G4HadronElastic::theDeuteron private
Definition at line 79 of file G4HadronElastic.hh.
Referenced by ApplyYourself(), and G4HadronElastic().
theNeutron
G4ParticleDefinition* G4HadronElastic::theNeutron private
Definition at line 78 of file G4HadronElastic.hh.
Referenced by G4HadronElastic().
theProton
G4ParticleDefinition* G4HadronElastic::theProton private
Definition at line 77 of file G4HadronElastic.hh.
Referenced by ApplyYourself(), and G4HadronElastic().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/coherent_elastic/include/G4HadronElastic.hh
source/processes/hadronic/models/coherent_elastic/src/G4HadronElastic.cc