Geant4: G4SDManager Class Reference
G4SDManager Class Reference
#include <G4SDManager.hh>
Public Member Functions
~G4SDManager ()
void AddNewDetector (G4VSensitiveDetector *aSD)
void Activate (G4String dName, G4bool activeFlag)
G4int GetCollectionID (G4String colName)
G4int GetCollectionID (G4VHitsCollection *aHC)
G4VSensitiveDetector * FindSensitiveDetector (G4String dName, G4bool warning=true)
G4HCofThisEvent * PrepareNewEvent ()
void TerminateCurrentEvent (G4HCofThisEvent *HCE)
void AddNewCollection (G4String SDname, G4String DCname)
void SetVerboseLevel (G4int vl)
G4SDStructure * GetTreeTop () const
void ListTree () const
G4int GetCollectionCapacity () const
G4HCtable * GetHCtable () const
void RegisterSDFilter (G4VSDFilter *filter)
void DeRegisterSDFilter (G4VSDFilter *filter)
Static Public Member Functions
static G4SDManager * GetSDMpointer ()
static G4SDManager * GetSDMpointerIfExist ()
Protected Member Functions
G4SDManager ()
Private Member Functions
G4SDManager (const G4SDManager &)
G4SDManager & operator= (const G4SDManager &)
void DestroyFilters ()
Private Attributes
G4SDStructure * treeTop
G4int verboseLevel
G4HCtable * HCtable
G4SDmessenger * theMessenger
std::vector< G4VSDFilter * > FilterList
Static Private Attributes
static G4ThreadLocal G4SDManager * fSDManager = nullptr
Detailed Description
Definition at line 52 of file G4SDManager.hh.
Constructor & Destructor Documentation
G4SDManager() [1/2]
G4SDManager::G4SDManager () protected
Definition at line 51 of file G4SDManager.cc.
Referenced by GetSDMpointer().
~G4SDManager()
G4SDManager::~G4SDManager ()
Definition at line 59 of file G4SDManager.cc.
G4SDManager() [2/2]
G4SDManager::G4SDManager (const G4SDManager &) private
Member Function Documentation
Activate()
void G4SDManager::Activate (G4String dName, G4bool activeFlag)
Definition at line 121 of file G4SDManager.cc.
Referenced by G4RTRunAction::BeginOfRunAction(), G4RTRunAction::EndOfRunAction(), G4MaterialScanner::RestoreUserActions(), G4TheRayTracer::RestoreUserActions(), G4SDmessenger::SetNewValue(), G4MaterialScanner::StoreUserActions(), and G4TheRayTracer::StoreUserActions().
AddNewCollection()
void G4SDManager::AddNewCollection (G4String SDname, G4String DCname)
Definition at line 92 of file G4SDManager.cc.
Referenced by AddNewDetector(), and G4MultiFunctionalDetector::RegisterPrimitive().
AddNewDetector()
void G4SDManager::AddNewDetector (G4VSensitiveDetector * aSD)
Definition at line 71 of file G4SDManager.cc.
Referenced by CCalSensAssign::assign(), ExN04DetectorConstruction::Construct(), DetectorWatase86::Construct(), DetectorBarr90::Construct(), DetectorHarris73::Construct(), DetectorSimpleALICE::Construct(), DetectorALICE06::Construct(), DetectorBari05::Construct(), FCALHadModule::Construct(), FCALEMModule::Construct(), eRositaDetectorConstruction::Construct(), ExN02DetectorConstruction::Construct(), ExP01DetectorConstruction::Construct(), CML2Ph_FullWater::Construct(), RE01CalorimeterROGeometry::ConstructSD(), RE05CalorimeterParallelWorld::ConstructSD(), HadrontherapyDetectorROGeometry::ConstructSD(), B03ImportanceDetectorConstruction::ConstructSD(), B02ImportanceDetectorConstruction::ConstructSD(), XDetectorConstruction::ConstructSDandField(), G04DetectorConstruction::ConstructSDandField(), Par01DetectorConstruction::ConstructSDandField(), ExTGDetectorConstructionWithSD::ConstructSDandField(), RE01DetectorConstruction::ConstructSDandField(), RE05DetectorConstruction::ConstructSDandField(), GB05DetectorConstruction::ConstructSDandField(), B3DetectorConstruction::ConstructSDandField(), ExGflashDetectorConstruction::ConstructSDandField(), G4HumanPhantomConstruction::ConstructSDandField(), GB06DetectorConstruction::ConstructSDandField(), B2aDetectorConstruction::ConstructSDandField(), B2bDetectorConstruction::ConstructSDandField(), ElectronBenchmarkDetector::ConstructSDandField(), LXeDetectorConstruction::ConstructSDandField(), FCALTestbeamSetup::ConstructSDandField(), B4cDetectorConstruction::ConstructSDandField(), B4dDetectorConstruction::ConstructSDandField(), B01DetectorConstruction::ConstructSDandField(), WLSDetectorConstruction::ConstructSDandField(), DMXDetectorConstruction::ConstructSDandField(), XrayFluoPlaneDetectorConstruction::ConstructSDandField(), UltraDetectorConstruction::ConstructSDandField(), XrayFluoMercuryDetectorConstruction::ConstructSDandField(), F03DetectorConstruction::ConstructSDandField(), F01DetectorConstruction::ConstructSDandField(), F02DetectorConstruction::ConstructSDandField(), XrayFluoDetectorConstruction::ConstructSDandField(), GammaRayTelDetectorConstruction::ConstructSDandField(), TSDetectorConstruction::ConstructSDandField(), DicomDetectorConstruction::ConstructSDandField(), RE02DetectorConstruction::ConstructSDandField(), RMC01DetectorConstruction::ConstructSimpleGeometry(), G4VScoringMesh::G4VScoringMesh(), G4VUserParallelWorld::SetSensitiveDetector(), G4VUserDetectorConstruction::SetSensitiveDetector(), RE06ParallelWorld::SetupDetectors(), GB03DetectorConstruction::SetupDetectors(), RE06DetectorConstruction::SetupDetectors(), and CexmcSetup::SetupSpecialVolumes().
DeRegisterSDFilter()
void G4SDManager::DeRegisterSDFilter (G4VSDFilter * filter)
Definition at line 158 of file G4SDManager.cc.
Referenced by G4VSDFilter::~G4VSDFilter().
DestroyFilters()
void G4SDManager::DestroyFilters () private
Definition at line 170 of file G4SDManager.cc.
Referenced by ~G4SDManager().
FindSensitiveDetector()
G4VSensitiveDetector * G4SDManager::FindSensitiveDetector (G4String dName, G4bool warning = true)
Definition at line 128 of file G4SDManager.cc.
Referenced by B01Run::B01Run(), B02Run::B02Run(), B03Run::B03Run(), DicomRun::ConstructMFD(), Dicom2Run::ConstructMFD(), TSRun::ConstructMFD(), G04DetectorConstruction::ConstructSDandField(), FCALTestbeamSetup::ConstructSDandField(), CCalStackingAction::initialize(), ML2Run::ML2Run(), RE02Run::RE02Run(), G4MultiFunctionalDetector::RegisterPrimitive(), LXeSteppingAction::UserSteppingAction(), and WLSSteppingAction::UserSteppingAction().
GetCollectionCapacity()
G4int G4SDManager::GetCollectionCapacity () const inline
Definition at line 101 of file G4SDManager.hh.
GetCollectionID() [1/2]
G4int G4SDManager::GetCollectionID (G4String colName)
Definition at line 135 of file G4SDManager.cc.
Referenced by B01Run::B01Run(), B02Run::B02Run(), B03Run::B03Run(), RE05EventAction::BeginOfEventAction(), G4HumanPhantomEventAction::BeginOfEventAction(), RE01EventAction::BeginOfEventAction(), LXeEventAction::BeginOfEventAction(), GammaRayTelEventAction::BeginOfEventAction(), XrayFluoEventAction::BeginOfEventAction(), UltraEventAction::BeginOfEventAction(), DMXEventAction::BeginOfEventAction(), DicomRun::ConstructMFD(), Dicom2Run::ConstructMFD(), TSRun::ConstructMFD(), Par01CalorimeterSD::EndOfEvent(), F02CalorimeterSD::EndOfEvent(), F01CalorimeterSD::EndOfEvent(), F03CalorimeterSD::EndOfEvent(), XrayFluoHPGeSD::EndOfEvent(), GammaRayTelCalorimeterSD::EndOfEvent(), GammaRayTelTrackerSD::EndOfEvent(), GammaRayTelAnticoincidenceSD::EndOfEvent(), DMXScintSD::EndOfEvent(), DMXPmtSD::EndOfEvent(), UltraPMTSD::EndOfEvent(), XrayFluoSD::EndOfEvent(), ExGflashEventAction::EndOfEventAction(), CCalEventAction::EndOfEventAction(), B3aEventAction::EndOfEventAction(), B4dEventAction::EndOfEventAction(), B4cEventAction::EndOfEventAction(), WLSEventAction::EndOfEventAction(), RMC01AnalysisManager::EndOfEventForAdjointSimulation(), RMC01AnalysisManager::EndOfEventForForwardSimulation(), RE01StackingAction::GetCalCollection(), RE05StackingAction::GetCollection(), ExN04StackingAction::GetCollection(), G4VPrimitiveScorer::GetCollectionID(), GetCollectionID(), G4VSensitiveDetector::GetCollectionID(), G4DigiManager::GetHitsCollectionID(), G4HumanPhantomSD::Initialize(), eRositaTrackerSD::Initialize(), B5HodoscopeSD::Initialize(), ExTGTrackerSD::Initialize(), XAluminumElectrodeSensitivity::Initialize(), B5DriftChamberSD::Initialize(), B5HadCalorimeterSD::Initialize(), B5EmCalorimeterSD::Initialize(), ExN02TrackerSD::Initialize(), SensitiveDetector::Initialize(), ExP01TrackerSD::Initialize(), B2TrackerSD::Initialize(), TrackerSD::Initialize(), B4cCalorimeterSD::Initialize(), CCaloSD::Initialize(), ML2Run::ML2Run(), RE02Run::RE02Run(), RE06Run::RE06Run(), B3bRun::RecordEvent(), and Run::RecordEvent().
GetCollectionID() [2/2]
G4int G4SDManager::GetCollectionID (G4VHitsCollection * aHC)
Definition at line 145 of file G4SDManager.cc.
GetHCtable()
G4HCtable* G4SDManager::GetHCtable () const inline
Definition at line 103 of file G4SDManager.hh.
Referenced by G4WorkerRunManager::RunInitialization(), and G4RunManager::RunInitialization().
GetSDMpointer()
G4SDManager * G4SDManager::GetSDMpointer () static
Definition at line 39 of file G4SDManager.cc.
Referenced by CCalSensAssign::assign(), B01Run::B01Run(), B02Run::B02Run(), B03Run::B03Run(), ExN04EventAction::BeginOfEventAction(), RE05EventAction::BeginOfEventAction(), HadrontherapyEventAction::BeginOfEventAction(), G4HumanPhantomEventAction::BeginOfEventAction(), RE01EventAction::BeginOfEventAction(), LXeEventAction::BeginOfEventAction(), B5EventAction::BeginOfEventAction(), GammaRayTelEventAction::BeginOfEventAction(), XrayFluoEventAction::BeginOfEventAction(), UltraEventAction::BeginOfEventAction(), DMXEventAction::BeginOfEventAction(), H02DetectorConstruction::Construct(), ExN04DetectorConstruction::Construct(), DetectorBarr90::Construct(), DetectorHarris73::Construct(), DetectorWatase86::Construct(), DetectorSimpleALICE::Construct(), DetectorALICE06::Construct(), DetectorBari05::Construct(), FCALEMModule::Construct(), FCALHadModule::Construct(), eRositaDetectorConstruction::Construct(), ExN02DetectorConstruction::Construct(), ExP01DetectorConstruction::Construct(), CML2Ph_FullWater::Construct(), DicomRun::ConstructMFD(), Dicom2Run::ConstructMFD(), TSRun::ConstructMFD(), RE01CalorimeterROGeometry::ConstructSD(), RE05CalorimeterParallelWorld::ConstructSD(), HadrontherapyDetectorROGeometry::ConstructSD(), B03ImportanceDetectorConstruction::ConstructSD(), B02ImportanceDetectorConstruction::ConstructSD(), XDetectorConstruction::ConstructSDandField(), G04DetectorConstruction::ConstructSDandField(), Par01DetectorConstruction::ConstructSDandField(), ExTGDetectorConstructionWithSD::ConstructSDandField(), RE01DetectorConstruction::ConstructSDandField(), RE05DetectorConstruction::ConstructSDandField(), GB05DetectorConstruction::ConstructSDandField(), G4HumanPhantomConstruction::ConstructSDandField(), B3DetectorConstruction::ConstructSDandField(), ExGflashDetectorConstruction::ConstructSDandField(), GB06DetectorConstruction::ConstructSDandField(), B2aDetectorConstruction::ConstructSDandField(), B2bDetectorConstruction::ConstructSDandField(), B5DetectorConstruction::ConstructSDandField(), ElectronBenchmarkDetector::ConstructSDandField(), LXeDetectorConstruction::ConstructSDandField(), FCALTestbeamSetup::ConstructSDandField(), B4cDetectorConstruction::ConstructSDandField(), B4dDetectorConstruction::ConstructSDandField(), B01DetectorConstruction::ConstructSDandField(), WLSDetectorConstruction::ConstructSDandField(), XrayFluoPlaneDetectorConstruction::ConstructSDandField(), DMXDetectorConstruction::ConstructSDandField(), UltraDetectorConstruction::ConstructSDandField(), XrayFluoMercuryDetectorConstruction::ConstructSDandField(), F03DetectorConstruction::ConstructSDandField(), F01DetectorConstruction::ConstructSDandField(), F02DetectorConstruction::ConstructSDandField(), XrayFluoDetectorConstruction::ConstructSDandField(), GammaRayTelDetectorConstruction::ConstructSDandField(), TSDetectorConstruction::ConstructSDandField(), DicomDetectorConstruction::ConstructSDandField(), RE02DetectorConstruction::ConstructSDandField(), RMC01DetectorConstruction::ConstructSimpleGeometry(), Par01CalorimeterSD::EndOfEvent(), F02CalorimeterSD::EndOfEvent(), F01CalorimeterSD::EndOfEvent(), F03CalorimeterSD::EndOfEvent(), XrayFluoHPGeSD::EndOfEvent(), GammaRayTelAnticoincidenceSD::EndOfEvent(), GammaRayTelCalorimeterSD::EndOfEvent(), GammaRayTelTrackerSD::EndOfEvent(), DMXScintSD::EndOfEvent(), UltraPMTSD::EndOfEvent(), DMXPmtSD::EndOfEvent(), XrayFluoSD::EndOfEvent(), H02EventAction::EndOfEventAction(), ExGflashEventAction::EndOfEventAction(), CCalEventAction::EndOfEventAction(), B4dEventAction::EndOfEventAction(), B3aEventAction::EndOfEventAction(), B4cEventAction::EndOfEventAction(), WLSEventAction::EndOfEventAction(), RMC01AnalysisManager::EndOfEventForAdjointSimulation(), RMC01AnalysisManager::EndOfEventForForwardSimulation(), G4DigiManager::G4DigiManager(), G4VScoringMesh::G4VScoringMesh(), G4VSDFilter::G4VSDFilter(), RE01StackingAction::GetCalCollection(), RE05StackingAction::GetCollection(), ExN04StackingAction::GetCollection(), G4VPrimitiveScorer::GetCollectionID(), G4VSensitiveDetector::GetCollectionID(), G4HumanPhantomSD::Initialize(), ExTGTrackerSD::Initialize(), eRositaTrackerSD::Initialize(), B5HodoscopeSD::Initialize(), XAluminumElectrodeSensitivity::Initialize(), B5DriftChamberSD::Initialize(), B5EmCalorimeterSD::Initialize(), B5HadCalorimeterSD::Initialize(), ExN02TrackerSD::Initialize(), SensitiveDetector::Initialize(), ExP01TrackerSD::Initialize(), B2TrackerSD::Initialize(), B4cCalorimeterSD::Initialize(), TrackerSD::Initialize(), CCaloSD::Initialize(), ML2Run::ML2Run(), RE02Run::RE02Run(), RE06Run::RE06Run(), B3bRun::RecordEvent(), Run::RecordEvent(), G4MultiFunctionalDetector::RegisterPrimitive(), G4VUserParallelWorld::SetSensitiveDetector(), G4VUserDetectorConstruction::SetSensitiveDetector(), RE06ParallelWorld::SetupDetectors(), GB03DetectorConstruction::SetupDetectors(), RE06DetectorConstruction::SetupDetectors(), CexmcSetup::SetupSpecialVolumes(), LXeSteppingAction::UserSteppingAction(), WLSSteppingAction::UserSteppingAction(), VoxelSD::VoxelSD(), and G4VSDFilter::~G4VSDFilter().
GetSDMpointerIfExist()
G4SDManager * G4SDManager::GetSDMpointerIfExist () static
Definition at line 48 of file G4SDManager.cc.
Referenced by G4RTRunAction::BeginOfRunAction(), G4EventManager::DoProcessing(), G4RTRunAction::EndOfRunAction(), G4EventManager::G4EventManager(), CCalStackingAction::initialize(), G4MaterialScanner::RestoreUserActions(), G4TheRayTracer::RestoreUserActions(), G4WorkerRunManager::RunInitialization(), G4RunManager::RunInitialization(), G4MaterialScanner::StoreUserActions(), G4TheRayTracer::StoreUserActions(), and G4RunManagerKernel::~G4RunManagerKernel().
GetTreeTop()
G4SDStructure* G4SDManager::GetTreeTop () const inline
Definition at line 97 of file G4SDManager.hh.
ListTree()
void G4SDManager::ListTree () const inline
Definition at line 99 of file G4SDManager.hh.
Referenced by G4SDmessenger::SetNewValue().
operator=()
G4SDManager& G4SDManager::operator= (const G4SDManager &) private
PrepareNewEvent()
G4HCofThisEvent * G4SDManager::PrepareNewEvent ()
Definition at line 109 of file G4SDManager.cc.
Referenced by G4EventManager::DoProcessing(), G4WorkerRunManager::RunInitialization(), and G4RunManager::RunInitialization().
RegisterSDFilter()
void G4SDManager::RegisterSDFilter (G4VSDFilter * filter)
Definition at line 153 of file G4SDManager.cc.
Referenced by G4VSDFilter::G4VSDFilter().
SetVerboseLevel()
void G4SDManager::SetVerboseLevel (G4int vl) inline
Definition at line 92 of file G4SDManager.hh.
Referenced by B3DetectorConstruction::ConstructSDandField(), ElectronBenchmarkDetector::ConstructSDandField(), B4dDetectorConstruction::ConstructSDandField(), G4SDmessenger::SetNewValue(), RE06ParallelWorld::SetupDetectors(), GB03DetectorConstruction::SetupDetectors(), and RE06DetectorConstruction::SetupDetectors().
TerminateCurrentEvent()
void G4SDManager::TerminateCurrentEvent (G4HCofThisEvent * HCE)
Definition at line 116 of file G4SDManager.cc.
Referenced by G4EventManager::DoProcessing().
Field Documentation
FilterList
std::vector<G4VSDFilter*> G4SDManager::FilterList private
Definition at line 115 of file G4SDManager.hh.
Referenced by DeRegisterSDFilter(), DestroyFilters(), and RegisterSDFilter().
fSDManager
G4ThreadLocal G4SDManager * G4SDManager::fSDManager = nullptr static private
Definition at line 85 of file G4SDManager.hh.
Referenced by GetSDMpointer(), GetSDMpointerIfExist(), and ~G4SDManager().
HCtable
G4HCtable* G4SDManager::HCtable private
Definition at line 88 of file G4SDManager.hh.
Referenced by AddNewCollection(), G4SDManager(), GetCollectionCapacity(), GetCollectionID(), GetHCtable(), PrepareNewEvent(), and ~G4SDManager().
theMessenger
G4SDmessenger* G4SDManager::theMessenger private
Definition at line 89 of file G4SDManager.hh.
Referenced by G4SDManager(), and ~G4SDManager().
treeTop
G4SDStructure* G4SDManager::treeTop private
Definition at line 86 of file G4SDManager.hh.
Referenced by Activate(), AddNewDetector(), FindSensitiveDetector(), G4SDManager(), GetTreeTop(), ListTree(), PrepareNewEvent(), SetVerboseLevel(), TerminateCurrentEvent(), and ~G4SDManager().
verboseLevel
G4int G4SDManager::verboseLevel private
Definition at line 87 of file G4SDManager.hh.
Referenced by AddNewCollection(), AddNewDetector(), DestroyFilters(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
source/digits_hits/detector/include/G4SDManager.hh
source/digits_hits/detector/src/G4SDManager.cc