Geant4: G4Polyhedra Class Reference
G4Polyhedra Class Reference
#include <G4Polyhedra.hh>
Public Member Functions
G4Polyhedra (const G4String &name, G4double phiStart, G4double phiTotal, G4int numSide, G4int numZPlanes, const G4double zPlane[], const G4double rInner[], const G4double rOuter[])
G4Polyhedra (const G4String &name, G4double phiStart, G4double phiTotal, G4int numSide, G4int numRZ, const G4double r[], const G4double z[])
virtual ~G4Polyhedra ()
EInside Inside (const G4ThreeVector &p) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pmin, G4double &pmax) const
void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
G4GeometryType GetEntityType () const
G4VSolid * Clone () const
G4ThreeVector GetPointOnSurface () const
std::ostream & StreamInfo (std::ostream &os) const
G4Polyhedron * CreatePolyhedron () const
G4bool Reset ()
G4int GetNumSide () const
G4double GetStartPhi () const
G4double GetEndPhi () const
G4double GetSinStartPhi () const
G4double GetCosStartPhi () const
G4double GetSinEndPhi () const
G4double GetCosEndPhi () const
G4bool IsOpen () const
G4bool IsGeneric () const
G4int GetNumRZCorner () const
G4PolyhedraSideRZ GetCorner (const G4int index) const
G4PolyhedraHistorical * GetOriginalParameters () const
void SetOriginalParameters (G4PolyhedraHistorical *pars)
G4Polyhedra (__void__ &)
G4Polyhedra (const G4Polyhedra &source)
G4Polyhedra & operator= (const G4Polyhedra &source)
Public Member Functions inherited from G4VCSGfaceted
G4VCSGfaceted (const G4String &name)
virtual ~G4VCSGfaceted ()
G4VCSGfaceted (const G4VCSGfaceted &source)
G4VCSGfaceted & operator= (const G4VCSGfaceted &source)
virtual G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
virtual G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=false, G4bool *validNorm=0, G4ThreeVector *n=0) const
virtual G4double DistanceToOut (const G4ThreeVector &p) const
virtual void DescribeYourselfTo (G4VGraphicsScene &scene) const
virtual G4VisExtent GetExtent () const
virtual G4Polyhedron * GetPolyhedron () const
G4int GetCubVolStatistics () const
G4double GetCubVolEpsilon () const
void SetCubVolStatistics (G4int st)
void SetCubVolEpsilon (G4double ep)
G4int GetAreaStatistics () const
G4double GetAreaAccuracy () const
void SetAreaStatistics (G4int st)
void SetAreaAccuracy (G4double ep)
virtual G4double GetCubicVolume ()
virtual G4double GetSurfaceArea ()
G4VCSGfaceted (__void__ &)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
void DumpInfo () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Protected Member Functions
void SetOriginalParameters (G4ReduciblePolygon *rz)
void Create (G4double phiStart, G4double phiTotal, G4int numSide, G4ReduciblePolygon *rz)
void CopyStuff (const G4Polyhedra &source)
void DeleteStuff ()
G4ThreeVector GetPointOnPlane (G4ThreeVector p0, G4ThreeVector p1, G4ThreeVector p2, G4ThreeVector p3) const
G4ThreeVector GetPointOnTriangle (G4ThreeVector p0, G4ThreeVector p1, G4ThreeVector p2) const
G4ThreeVector GetPointOnSurfaceCorners () const
Protected Member Functions inherited from G4VCSGfaceted
virtual G4double DistanceTo (const G4ThreeVector &p, const G4bool outgoing) const
G4ThreeVector GetPointOnSurfaceGeneric () const
void CopyStuff (const G4VCSGfaceted &source)
void DeleteStuff ()
Protected Member Functions inherited from G4VSolid
void CalculateClippedPolygonExtent (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipCrossSection (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipBetweenSections (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipPolygon (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis) const
Protected Attributes
G4int numSide
G4double startPhi
G4double endPhi
G4bool phiIsOpen
G4bool genericPgon
G4int numCorner
G4PolyhedraSideRZ * corners
G4PolyhedraHistorical * original_parameters
G4EnclosingCylinder * enclosingCylinder
Protected Attributes inherited from G4VCSGfaceted
G4int numFace
G4VCSGface ** faces
G4double fCubicVolume
G4double fSurfaceArea
G4bool fRebuildPolyhedron
G4Polyhedron * fpPolyhedron
Protected Attributes inherited from G4VSolid
G4double kCarTolerance
Detailed Description
Definition at line 80 of file G4Polyhedra.hh.
Constructor & Destructor Documentation
G4Polyhedra() [1/4]
G4Polyhedra::G4Polyhedra (const G4String & name, G4double phiStart, G4double phiTotal, G4int numSide, G4int numZPlanes, const G4double zPlane[], const G4double rInner[], const G4double rOuter[])
Definition at line 83 of file G4Polyhedra.cc.
Referenced by Clone().
G4Polyhedra() [2/4]
G4Polyhedra::G4Polyhedra (const G4String & name, G4double phiStart, G4double phiTotal, G4int numSide, G4int numRZ, const G4double r[], const G4double z[])
Definition at line 169 of file G4Polyhedra.cc.
~G4Polyhedra()
G4Polyhedra::~G4Polyhedra () virtual
Definition at line 394 of file G4Polyhedra.cc.
G4Polyhedra() [3/4]
G4Polyhedra::G4Polyhedra (__void__ & a)
Definition at line 383 of file G4Polyhedra.cc.
G4Polyhedra() [4/4]
G4Polyhedra::G4Polyhedra (const G4Polyhedra & source)
Definition at line 406 of file G4Polyhedra.cc.
Member Function Documentation
BoundingLimits()
void G4Polyhedra::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 575 of file G4Polyhedra.cc.
Referenced by CalculateExtent().
CalculateExtent()
G4bool G4Polyhedra::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pmin, G4double & pmax) const virtual
Reimplemented from G4VCSGfaceted.
Definition at line 645 of file G4Polyhedra.cc.
Clone()
G4VSolid * G4Polyhedra::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 781 of file G4Polyhedra.cc.
ComputeDimensions()
void G4Polyhedra::ComputeDimensions (G4VPVParameterisation * p, const G4int n, const G4VPhysicalVolume * pRep) virtual
Reimplemented from G4VSolid.
Definition at line 761 of file G4Polyhedra.cc.
CopyStuff()
void G4Polyhedra::CopyStuff (const G4Polyhedra & source) protected
Definition at line 436 of file G4Polyhedra.cc.
Referenced by G4Polyhedra(), and operator=().
Create()
void G4Polyhedra::Create (G4double phiStart, G4double phiTotal, G4int numSide, G4ReduciblePolygon * rz) protected
Definition at line 205 of file G4Polyhedra.cc.
Referenced by G4Polyhedra(), and Reset().
CreatePolyhedron()
G4Polyhedron * G4Polyhedra::CreatePolyhedron () const virtual
Creates user defined polyhedron. This function allows to the user to define arbitrary polyhedron. The faces of the polyhedron should be either triangles or planar quadrilateral. Nodes of a face are defined by indexes pointing to the elements in the xyz array. Numeration of the elements in the array starts from 1 (like in fortran). The indexes can be positive or negative. Negative sign means that the corresponding edge is invisible. The normal of the face should be directed to exterior of the polyhedron.
Parameters
Nnodes number of nodes
Nfaces number of faces
xyz nodes
faces_vec faces (quadrilaterals or triangles)
Returns
status of the operation - is non-zero in case of problem
Implements G4VCSGfaceted.
Definition at line 1111 of file G4Polyhedra.cc.
DeleteStuff()
void G4Polyhedra::DeleteStuff () protected
DistanceToIn() [1/2]
G4double G4Polyhedra::DistanceToIn (const G4ThreeVector & p) const virtual
Reimplemented from G4VCSGfaceted.
Definition at line 566 of file G4Polyhedra.cc.
DistanceToIn() [2/2]
G4double G4Polyhedra::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Reimplemented from G4VCSGfaceted.
Definition at line 547 of file G4Polyhedra.cc.
GetCorner()
G4PolyhedraSideRZ G4Polyhedra::GetCorner (const G4int index) const inline
Referenced by BoundingLimits(), CalculateExtent(), G4tgbGeometryDumper::GetSolidParams(), and G4GDMLWriteSolids::PolyhedraWrite().
GetCosEndPhi()
G4double G4Polyhedra::GetCosEndPhi () const inline
GetCosStartPhi()
G4double G4Polyhedra::GetCosStartPhi () const inline
Referenced by BoundingLimits(), and CalculateExtent().
GetEndPhi()
G4double G4Polyhedra::GetEndPhi () const inline
Referenced by BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4VParameterisationPolyhedra::ConvertRadiusFactor(), export_G4Polyhedra(), G4ParameterisationPolyhedraPhi::G4ParameterisationPolyhedraPhi(), G4VParameterisationPolyhedra::G4VParameterisationPolyhedra(), and G4ParameterisationPolyhedraPhi::GetMaxParameter().
GetEntityType()
G4GeometryType G4Polyhedra::GetEntityType () const virtual
Reimplemented from G4VCSGfaceted.
Definition at line 772 of file G4Polyhedra.cc.
GetNumRZCorner()
G4int G4Polyhedra::GetNumRZCorner () const inline
Referenced by BoundingLimits(), CalculateExtent(), export_G4Polyhedra(), G4tgbGeometryDumper::GetSolidParams(), and G4GDMLWriteSolids::PolyhedraWrite().
GetNumSide()
G4int G4Polyhedra::GetNumSide () const inline
Referenced by BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), export_G4Polyhedra(), G4ParameterisationPolyhedraPhi::G4ParameterisationPolyhedraPhi(), and G4tgbGeometryDumper::GetSolidParams().
GetOriginalParameters()
G4PolyhedraHistorical* G4Polyhedra::GetOriginalParameters () const inline
Referenced by G4tgbVolume::BuildSolidForDivision(), G4ParameterisationPolyhedraPhi::CheckParametersValidity(), G4GDMLParameterisation::ComputeDimensions(), G4ParameterisationPolyhedraRho::ComputeDimensions(), G4ParameterisationPolyhedraPhi::ComputeDimensions(), G4VParameterisationPolyhedra::ConvertRadiusFactor(), G4ParameterisationPolyhedraRho::G4ParameterisationPolyhedraRho(), G4VParameterisationPolyhedra::G4VParameterisationPolyhedra(), G4ParameterisationPolyhedraRho::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Polyhedra_dimensionsWrite(), and G4GDMLWriteSolids::PolyhedraWrite().
GetPointOnPlane()
G4ThreeVector G4Polyhedra::GetPointOnPlane (G4ThreeVector p0, G4ThreeVector p1, G4ThreeVector p2, G4ThreeVector p3) const protected
Definition at line 845 of file G4Polyhedra.cc.
Referenced by GetPointOnSurface().
GetPointOnSurface()
G4ThreeVector G4Polyhedra::GetPointOnSurface () const virtual
Reimplemented from G4VSolid.
Definition at line 894 of file G4Polyhedra.cc.
GetPointOnSurfaceCorners()
G4ThreeVector G4Polyhedra::GetPointOnSurfaceCorners () const protected
GetPointOnTriangle()
G4ThreeVector G4Polyhedra::GetPointOnTriangle (G4ThreeVector p0, G4ThreeVector p1, G4ThreeVector p2) const protected
Definition at line 877 of file G4Polyhedra.cc.
GetSinEndPhi()
G4double G4Polyhedra::GetSinEndPhi () const inline
GetSinStartPhi()
G4double G4Polyhedra::GetSinStartPhi () const inline
Referenced by BoundingLimits(), and CalculateExtent().
GetStartPhi()
G4double G4Polyhedra::GetStartPhi () const inline
Referenced by BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4VParameterisationPolyhedra::ConvertRadiusFactor(), export_G4Polyhedra(), G4ParameterisationPolyhedraPhi::G4ParameterisationPolyhedraPhi(), G4VParameterisationPolyhedra::G4VParameterisationPolyhedra(), G4ParameterisationPolyhedraPhi::GetMaxParameter(), and G4tgbGeometryDumper::GetSolidParams().
Inside()
EInside G4Polyhedra::Inside (const G4ThreeVector & p) const virtual
Reimplemented from G4VCSGfaceted.
Definition at line 527 of file G4Polyhedra.cc.
IsGeneric()
G4bool G4Polyhedra::IsGeneric () const inline
Referenced by export_G4Polyhedra(), G4VParameterisationPolyhedra::G4VParameterisationPolyhedra(), and G4GDMLWriteSolids::PolyhedraWrite().
IsOpen()
G4bool G4Polyhedra::IsOpen () const inline
Referenced by BoundingLimits(), CalculateExtent(), and export_G4Polyhedra().
operator=()
G4Polyhedra & G4Polyhedra::operator= (const G4Polyhedra & source)
Definition at line 416 of file G4Polyhedra.cc.
Reset()
G4bool G4Polyhedra::Reset ()
Definition at line 485 of file G4Polyhedra.cc.
Referenced by G4GDMLParameterisation::ComputeDimensions(), G4ParameterisationPolyhedraRho::ComputeDimensions(), G4ParameterisationPolyhedraPhi::ComputeDimensions(), and G4ParameterisationPolyhedraZ::ComputeDimensions().
SetOriginalParameters() [1/2]
void G4Polyhedra::SetOriginalParameters (G4PolyhedraHistorical * pars) inline
Referenced by G4GDMLParameterisation::ComputeDimensions(), G4ParameterisationPolyhedraRho::ComputeDimensions(), G4ParameterisationPolyhedraPhi::ComputeDimensions(), G4ParameterisationPolyhedraZ::ComputeDimensions(), and G4Polyhedra().
SetOriginalParameters() [2/2]
void G4Polyhedra::SetOriginalParameters (G4ReduciblePolygon * rz) protected
Definition at line 1368 of file G4Polyhedra.cc.
StreamInfo()
std::ostream & G4Polyhedra::StreamInfo (std::ostream & os) const virtual
Reimplemented from G4VCSGfaceted.
Definition at line 790 of file G4Polyhedra.cc.
Field Documentation
corners
G4PolyhedraSideRZ* G4Polyhedra::corners protected
Definition at line 195 of file G4Polyhedra.hh.
Referenced by CopyStuff(), Create(), CreatePolyhedron(), operator=(), Reset(), SetOriginalParameters(), StreamInfo(), and ~G4Polyhedra().
enclosingCylinder
G4EnclosingCylinder* G4Polyhedra::enclosingCylinder protected
Definition at line 198 of file G4Polyhedra.hh.
Referenced by CopyStuff(), Create(), DistanceToIn(), Inside(), operator=(), Reset(), and ~G4Polyhedra().
endPhi
G4double G4Polyhedra::endPhi protected
Definition at line 191 of file G4Polyhedra.hh.
Referenced by CopyStuff(), Create(), CreatePolyhedron(), GetPointOnSurface(), SetOriginalParameters(), and StreamInfo().
genericPgon
G4bool G4Polyhedra::genericPgon protected
Definition at line 193 of file G4Polyhedra.hh.
Referenced by CopyStuff(), CreatePolyhedron(), GetPointOnSurface(), Reset(), and StreamInfo().
numCorner
G4int G4Polyhedra::numCorner protected
Definition at line 194 of file G4Polyhedra.hh.
Referenced by CopyStuff(), Create(), CreatePolyhedron(), SetOriginalParameters(), and StreamInfo().
numSide
G4int G4Polyhedra::numSide protected
Definition at line 189 of file G4Polyhedra.hh.
Referenced by CopyStuff(), Create(), CreatePolyhedron(), GetPointOnSurface(), SetOriginalParameters(), and StreamInfo().
original_parameters
G4PolyhedraHistorical* G4Polyhedra::original_parameters protected
Definition at line 196 of file G4Polyhedra.hh.
Referenced by CopyStuff(), CreatePolyhedron(), G4Polyhedra(), GetPointOnSurface(), operator=(), Reset(), SetOriginalParameters(), StreamInfo(), and ~G4Polyhedra().
phiIsOpen
G4bool G4Polyhedra::phiIsOpen protected
Definition at line 192 of file G4Polyhedra.hh.
Referenced by CopyStuff(), Create(), CreatePolyhedron(), and GetPointOnSurface().
startPhi
G4double G4Polyhedra::startPhi protected
Definition at line 190 of file G4Polyhedra.hh.
Referenced by CopyStuff(), Create(), CreatePolyhedron(), GetPointOnSurface(), SetOriginalParameters(), and StreamInfo().
The documentation for this class was generated from the following files:
source/geometry/solids/specific/include/G4Polyhedra.hh
source/geometry/solids/specific/src/G4Polyhedra.cc