Geant4: CCalSensAssign Class Reference
CCalSensAssign Class Reference
#include <CCalSensAssign.hh>
Public Member Functions
~CCalSensAssign ()
bool assign ()
bool stackingAction ()
bool addCaloSD (G4String name, CCalVOrganization *numberingScheme)
Static Public Member Functions
static CCalSensAssign * getInstance ()
Private Member Functions
CCalSensAssign ()
Private Attributes
std::map< G4String, G4VSensitiveDetector * > sens_
Static Private Attributes
static CCalSensAssign * theInstance = 0
Detailed Description
Definition at line 40 of file CCalSensAssign.hh.
Constructor & Destructor Documentation
~CCalSensAssign()
CCalSensAssign::~CCalSensAssign () inline
Definition at line 43 of file CCalSensAssign.hh.
CCalSensAssign()
CCalSensAssign::CCalSensAssign () private
Definition at line 49 of file CCalSensAssign.cc.
Referenced by getInstance().
Member Function Documentation
addCaloSD()
bool CCalSensAssign::addCaloSD (G4String name, CCalVOrganization * numberingScheme)
Definition at line 88 of file CCalSensAssign.cc.
assign()
bool CCalSensAssign::assign ()
Definition at line 52 of file CCalSensAssign.cc.
Referenced by CCalDetectorConstruction::Construct().
getInstance()
CCalSensAssign * CCalSensAssign::getInstance () static
Definition at line 43 of file CCalSensAssign.cc.
Referenced by CCalDetectorConstruction::Construct().
stackingAction()
bool CCalSensAssign::stackingAction ()
Definition at line 72 of file CCalSensAssign.cc.
Referenced by CCalDetectorConstruction::Construct().
Field Documentation
sens_
std::map<G4String,G4VSensitiveDetector*> CCalSensAssign::sens_ private
Definition at line 53 of file CCalSensAssign.hh.
Referenced by addCaloSD(), and assign().
theInstance
CCalSensAssign * CCalSensAssign::theInstance = 0 static private
Definition at line 52 of file CCalSensAssign.hh.
Referenced by getInstance().
The documentation for this class was generated from the following files:
examples/advanced/composite_calorimeter/include/CCalSensAssign.hh
examples/advanced/composite_calorimeter/src/CCalSensAssign.cc