Geant4: G4StackedTrack Class Reference
G4StackedTrack Class Reference
#include <G4StackedTrack.hh>
Public Member Functions
G4StackedTrack ()
G4StackedTrack (G4Track *aTrack, G4VTrajectory *aTraj=0)
~G4StackedTrack ()
G4Track * GetTrack () const
G4VTrajectory * GetTrajectory () const
Private Attributes
G4Track * track
G4VTrajectory * trajectory
Detailed Description
Definition at line 44 of file G4StackedTrack.hh.
Constructor & Destructor Documentation
G4StackedTrack() [1/2]
G4StackedTrack::G4StackedTrack () inline
Definition at line 47 of file G4StackedTrack.hh.
G4StackedTrack() [2/2]
G4StackedTrack::G4StackedTrack (G4Track * aTrack, G4VTrajectory * aTraj = 0) inline
Definition at line 48 of file G4StackedTrack.hh.
~G4StackedTrack()
G4StackedTrack::~G4StackedTrack () inline
Definition at line 49 of file G4StackedTrack.hh.
Member Function Documentation
GetTrack()
G4Track* G4StackedTrack::GetTrack () const inline
Definition at line 56 of file G4StackedTrack.hh.
Referenced by G4SmartTrackStack::PopFromStack(), G4StackManager::PopNextTrack(), G4StackManager::PrepareNewEvent(), G4SmartTrackStack::PushToStack(), G4StackManager::ReClassify(), and G4StackManager::TransferOneStackedTrack().
GetTrajectory()
G4VTrajectory* G4StackedTrack::GetTrajectory () const inline
Definition at line 57 of file G4StackedTrack.hh.
Referenced by G4StackManager::PopNextTrack(), G4StackManager::PrepareNewEvent(), G4StackManager::ReClassify(), and G4StackManager::TransferOneStackedTrack().
Field Documentation
track
G4Track* G4StackedTrack::track private
Definition at line 52 of file G4StackedTrack.hh.
Referenced by GetTrack().
trajectory
G4VTrajectory* G4StackedTrack::trajectory private
Definition at line 53 of file G4StackedTrack.hh.
Referenced by GetTrajectory().
The documentation for this class was generated from the following file:
source/event/include/G4StackedTrack.hh