Geant4: G4GeometryManager Class Reference
G4GeometryManager Class Reference
#include <G4GeometryManager.hh>
Public Member Functions
G4bool CloseGeometry (G4bool pOptimise=true, G4bool verbose=false, G4VPhysicalVolume *vol=0)
void OpenGeometry (G4VPhysicalVolume *vol=0)
void SetWorldMaximumExtent (G4double worldExtent)
~G4GeometryManager ()
Static Public Member Functions
static G4bool IsGeometryClosed ()
static G4GeometryManager * GetInstance ()
static G4GeometryManager * GetInstanceIfExist ()
Protected Member Functions
G4GeometryManager ()
Private Member Functions
void BuildOptimisations (G4bool allOpt, G4bool verbose=false)
void BuildOptimisations (G4bool allOpt, G4VPhysicalVolume *vol)
void DeleteOptimisations ()
void DeleteOptimisations (G4VPhysicalVolume *vol)
Static Private Member Functions
static void ReportVoxelStats (std::vector< G4SmartVoxelStat > &stats, G4double totalCpuTime)
Static Private Attributes
static G4ThreadLocal G4GeometryManager * fgInstance = 0
static G4ThreadLocal G4bool fIsClosed = false
Detailed Description
Definition at line 54 of file G4GeometryManager.hh.
Constructor & Destructor Documentation
~G4GeometryManager()
G4GeometryManager::~G4GeometryManager ()
Definition at line 77 of file G4GeometryManager.cc.
G4GeometryManager()
G4GeometryManager::G4GeometryManager () protected
Definition at line 69 of file G4GeometryManager.cc.
Referenced by GetInstance().
Member Function Documentation
BuildOptimisations() [1/2]
void G4GeometryManager::BuildOptimisations (G4bool allOpt, G4bool verbose = false) private
Definition at line 167 of file G4GeometryManager.cc.
Referenced by BuildOptimisations(), and CloseGeometry().
BuildOptimisations() [2/2]
void G4GeometryManager::BuildOptimisations (G4bool allOpt, G4VPhysicalVolume * vol) private
Definition at line 243 of file G4GeometryManager.cc.
CloseGeometry()
G4bool G4GeometryManager::CloseGeometry (G4bool pOptimise = true, G4bool verbose = false, G4VPhysicalVolume * vol = 0)
Definition at line 90 of file G4GeometryManager.cc.
Referenced by CML2PhantomConstruction::applyNewCentre(), G4GeometryMessenger::CheckGeometry(), G4TheRayTracer::CreateBitMap(), G4MaterialScanner::DoScan(), export_G4GeometryManager(), G4DNAChemistryManager::InitializeThread(), G4RunManagerKernel::ResetNavigator(), CML2AcceleratorConstruction::rotateAccelerator(), G4MaterialScanner::StoreUserActions(), and G4TheRayTracer::StoreUserActions().
DeleteOptimisations() [1/2]
void G4GeometryManager::DeleteOptimisations () private
Definition at line 301 of file G4GeometryManager.cc.
Referenced by DeleteOptimisations(), and OpenGeometry().
DeleteOptimisations() [2/2]
void G4GeometryManager::DeleteOptimisations (G4VPhysicalVolume * vol) private
Definition at line 318 of file G4GeometryManager.cc.
GetInstance()
G4GeometryManager * G4GeometryManager::GetInstance (void) static
Definition at line 144 of file G4GeometryManager.cc.
Referenced by CML2PhantomConstruction::applyNewCentre(), G4GeometryMessenger::CheckGeometry(), G4ErrorPropagatorManager::CloseGeometry(), F04DetectorConstruction::Construct(), ExN02DetectorConstruction::Construct(), WLSDetectorConstruction::Construct(), DetectorConstruction::ConstructCalorimeter(), F02DetectorConstruction::ConstructCalorimeter(), F01DetectorConstruction::ConstructCalorimeter(), ExN03DetectorConstruction::ConstructCalorimeter(), F03DetectorConstruction::ConstructCalorimeter(), RMC01DetectorConstruction::ConstructSimpleGeometry(), DetectorConstruction::ConstructVolumes(), G4TheRayTracer::CreateBitMap(), ElectronBenchmarkDetector::CreateGeometry(), DetectorConstruction::DefineVolumes(), B2aDetectorConstruction::DefineVolumes(), B2bDetectorConstruction::DefineVolumes(), G4MaterialScanner::DoScan(), export_G4GeometryManager(), G4DNAChemistryManager::InitializeThread(), main(), G4RunManager::ReinitializeGeometry(), G4RunManagerKernel::ResetNavigator(), CML2AcceleratorConstruction::rotateAccelerator(), G4GDMLMessenger::SetNewValue(), G4MaterialScanner::StoreUserActions(), G4TheRayTracer::StoreUserActions(), XrayFluoPlaneDetectorConstruction::UpdateGeometry(), XrayFluoMercuryDetectorConstruction::UpdateGeometry(), XrayFluoDetectorConstruction::UpdateGeometry(), IORTDetectorConstruction::UpdateGeometry(), HadrontherapyDetectorConstruction::UpdateGeometry(), and G4RunManagerKernel::~G4RunManagerKernel().
GetInstanceIfExist()
G4GeometryManager * G4GeometryManager::GetInstanceIfExist () static
Definition at line 157 of file G4GeometryManager.cc.
Referenced by G4RunManagerKernel::~G4RunManagerKernel().
IsGeometryClosed()
G4bool G4GeometryManager::IsGeometryClosed () static
Definition at line 134 of file G4GeometryManager.cc.
Referenced by G4GeometryMessenger::CheckGeometry(), G4AssemblyStore::Clean(), G4PhysicalVolumeStore::Clean(), G4SolidStore::Clean(), G4LogicalVolumeStore::Clean(), G4RegionStore::Clean(), and export_G4GeometryManager().
OpenGeometry()
void G4GeometryManager::OpenGeometry (G4VPhysicalVolume * vol = 0)
Definition at line 114 of file G4GeometryManager.cc.
Referenced by CML2PhantomConstruction::applyNewCentre(), G4GeometryMessenger::CheckGeometry(), G4ErrorPropagatorManager::CloseGeometry(), F04DetectorConstruction::Construct(), WLSDetectorConstruction::Construct(), DetectorConstruction::ConstructCalorimeter(), F02DetectorConstruction::ConstructCalorimeter(), F01DetectorConstruction::ConstructCalorimeter(), ExN03DetectorConstruction::ConstructCalorimeter(), F03DetectorConstruction::ConstructCalorimeter(), RMC01DetectorConstruction::ConstructSimpleGeometry(), DetectorConstruction::ConstructVolumes(), G4TheRayTracer::CreateBitMap(), ElectronBenchmarkDetector::CreateGeometry(), DetectorConstruction::DefineVolumes(), G4MaterialScanner::DoScan(), export_G4GeometryManager(), G4DNAChemistryManager::InitializeThread(), main(), G4RunManager::ReinitializeGeometry(), G4RunManagerKernel::ResetNavigator(), CML2AcceleratorConstruction::rotateAccelerator(), G4GDMLMessenger::SetNewValue(), G4MaterialScanner::StoreUserActions(), G4TheRayTracer::StoreUserActions(), XrayFluoPlaneDetectorConstruction::UpdateGeometry(), XrayFluoMercuryDetectorConstruction::UpdateGeometry(), XrayFluoDetectorConstruction::UpdateGeometry(), and G4RunManagerKernel::~G4RunManagerKernel().
ReportVoxelStats()
void G4GeometryManager::ReportVoxelStats (std::vector< G4SmartVoxelStat > & stats, G4double totalCpuTime) static private
Definition at line 363 of file G4GeometryManager.cc.
Referenced by BuildOptimisations().
SetWorldMaximumExtent()
void G4GeometryManager::SetWorldMaximumExtent (G4double worldExtent)
Definition at line 344 of file G4GeometryManager.cc.
Referenced by ExN02DetectorConstruction::Construct(), DetectorConstruction::DefineVolumes(), B2bDetectorConstruction::DefineVolumes(), B2aDetectorConstruction::DefineVolumes(), and export_G4GeometryManager().
Field Documentation
fgInstance
G4ThreadLocal G4GeometryManager * G4GeometryManager::fgInstance = 0 static private
Definition at line 101 of file G4GeometryManager.hh.
Referenced by GetInstance(), GetInstanceIfExist(), and ~G4GeometryManager().
fIsClosed
G4ThreadLocal G4bool G4GeometryManager::fIsClosed = false static private
Definition at line 102 of file G4GeometryManager.hh.
Referenced by CloseGeometry(), IsGeometryClosed(), OpenGeometry(), and ~G4GeometryManager().
The documentation for this class was generated from the following files:
source/geometry/management/include/G4GeometryManager.hh
source/geometry/management/src/G4GeometryManager.cc