Geant4: G4FTFAnnihilation Class Reference
G4FTFAnnihilation Class Reference
#include <G4FTFAnnihilation.hh>
Data Structures
struct CommonVariables
Public Member Functions
G4FTFAnnihilation ()
virtual ~G4FTFAnnihilation ()
virtual G4bool Annihilate (G4VSplitableHadron *aPartner, G4VSplitableHadron *bPartner, G4VSplitableHadron *&AdditionalString, G4FTFParameters *theParameters) const
Private Member Functions
G4FTFAnnihilation (const G4FTFAnnihilation &right)
const G4FTFAnnihilation & operator= (const G4FTFAnnihilation &right)
G4bool operator== (const G4FTFAnnihilation &right) const
G4bool operator!= (const G4FTFAnnihilation &right) const
G4bool Create3QuarkAntiQuarkStrings (G4VSplitableHadron *aPartner, G4VSplitableHadron *bPartner, G4VSplitableHadron *&AdditionalString, G4FTFParameters *theParameters, CommonVariables &common) const
G4int Create1DiquarkAntiDiquarkString (G4VSplitableHadron *aPartner, G4VSplitableHadron *bPartner, CommonVariables &common) const
G4int Create2QuarkAntiQuarkStrings (G4VSplitableHadron *aPartner, G4VSplitableHadron *bPartner, G4FTFParameters *theParameters, CommonVariables &common) const
G4bool Create1QuarkAntiQuarkString (G4VSplitableHadron *aPartner, G4VSplitableHadron *bPartner, G4FTFParameters *theParameters, CommonVariables &common) const
G4ThreeVector GaussianPt (G4double AveragePt2, G4double maxPtSquare) const
G4double ChooseX (G4double Alpha, G4double Beta) const
void UnpackBaryon (G4int IdPDG, G4int &Q1, G4int &Q2, G4int &Q3) const
Detailed Description
Definition at line 49 of file G4FTFAnnihilation.hh.
Constructor & Destructor Documentation
G4FTFAnnihilation() [1/2]
G4FTFAnnihilation::G4FTFAnnihilation ()
Definition at line 76 of file G4FTFAnnihilation.cc.
~G4FTFAnnihilation()
G4FTFAnnihilation::~G4FTFAnnihilation () virtual
Definition at line 81 of file G4FTFAnnihilation.cc.
G4FTFAnnihilation() [2/2]
G4FTFAnnihilation::G4FTFAnnihilation (const G4FTFAnnihilation & right) private
Definition at line 1067 of file G4FTFAnnihilation.cc.
Member Function Documentation
Annihilate()
G4bool G4FTFAnnihilation::Annihilate (G4VSplitableHadron * aPartner, G4VSplitableHadron * bPartner, G4VSplitableHadron *& AdditionalString, G4FTFParameters * theParameters) const virtual
Definition at line 86 of file G4FTFAnnihilation.cc.
Referenced by G4FTFModel::ExciteParticipants().
ChooseX()
G4double G4FTFAnnihilation::ChooseX (G4double Alpha, G4double Beta) const private
Definition at line 1027 of file G4FTFAnnihilation.cc.
Create1DiquarkAntiDiquarkString()
G4int G4FTFAnnihilation::Create1DiquarkAntiDiquarkString (G4VSplitableHadron * aPartner, G4VSplitableHadron * bPartner, G4FTFAnnihilation::CommonVariables & common) const private
Definition at line 553 of file G4FTFAnnihilation.cc.
Referenced by Annihilate().
Create1QuarkAntiQuarkString()
G4bool G4FTFAnnihilation::Create1QuarkAntiQuarkString (G4VSplitableHadron * aPartner, G4VSplitableHadron * bPartner, G4FTFParameters * theParameters, G4FTFAnnihilation::CommonVariables & common) const private
Definition at line 906 of file G4FTFAnnihilation.cc.
Referenced by Annihilate().
Create2QuarkAntiQuarkStrings()
G4int G4FTFAnnihilation::Create2QuarkAntiQuarkStrings (G4VSplitableHadron * aPartner, G4VSplitableHadron * bPartner, G4FTFParameters * theParameters, G4FTFAnnihilation::CommonVariables & common) const private
Definition at line 646 of file G4FTFAnnihilation.cc.
Referenced by Annihilate().
Create3QuarkAntiQuarkStrings()
G4bool G4FTFAnnihilation::Create3QuarkAntiQuarkStrings (G4VSplitableHadron * aPartner, G4VSplitableHadron * bPartner, G4VSplitableHadron *& AdditionalString, G4FTFParameters * theParameters, G4FTFAnnihilation::CommonVariables & common) const private
Definition at line 282 of file G4FTFAnnihilation.cc.
Referenced by Annihilate().
GaussianPt()
G4ThreeVector G4FTFAnnihilation::GaussianPt (G4double AveragePt2, G4double maxPtSquare) const private
Definition at line 1038 of file G4FTFAnnihilation.cc.
Referenced by Create2QuarkAntiQuarkStrings(), and Create3QuarkAntiQuarkStrings().
operator!=()
G4bool G4FTFAnnihilation::operator!= (const G4FTFAnnihilation & right) const private
Definition at line 1091 of file G4FTFAnnihilation.cc.
operator=()
const G4FTFAnnihilation & G4FTFAnnihilation::operator= (const G4FTFAnnihilation & right) private
Definition at line 1075 of file G4FTFAnnihilation.cc.
operator==()
G4bool G4FTFAnnihilation::operator== (const G4FTFAnnihilation & right) const private
Definition at line 1083 of file G4FTFAnnihilation.cc.
UnpackBaryon()
void G4FTFAnnihilation::UnpackBaryon (G4int IdPDG, G4int & Q1, G4int & Q2, G4int & Q3) const private
Definition at line 1055 of file G4FTFAnnihilation.cc.
Referenced by Annihilate().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/parton_string/diffraction/include/G4FTFAnnihilation.hh
source/processes/hadronic/models/parton_string/diffraction/src/G4FTFAnnihilation.cc