Geant4: examples/extended/medical/DICOM/include/DicomRun.hh File Reference
DicomRun.hh File Reference
Definition of the DicomRun class.
#include "G4Run.hh"
#include "G4Event.hh"
#include "G4THitsMap.hh"
#include <vector>
Data Structures
class DicomRun
DicomRun class.
Functions
template<typename T >
void Copy (std::vector< T > &main, const std::vector< T > &data)
template<typename T >
unsigned Copy (std::vector< T * > &main, const std::vector< T * > &data)
template<typename T >
void Print (const std::vector< T > &data)
Detailed Description
Definition of the DicomRun class.
Definition in file DicomRun.hh.
Function Documentation
Copy() [1/2]
template<typename T > unsigned Copy (std::vector< T * > & main, const std::vector< T * > & data) inline
Definition at line 98 of file DicomRun.hh.
Copy() [2/2]
template<typename T > void Copy (std::vector< T > & main, const std::vector< T > & data) inline
Definition at line 90 of file DicomRun.hh.
Referenced by DicomRun::Merge(), and Dicom2Run::Merge().
Print()
template<typename T > void Print (const std::vector< T > & data) inline
Definition at line 108 of file DicomRun.hh.
Referenced by H02EventAction::BeginOfEventAction(), export_G4Element(), export_G4Isotope(), export_G4Material(), G4MCTEvent::Print(), G4MCTSimParticle::Print(), G4SmartFilter< G4VTrajectory >::PrintAll(), PrintVector(), G4VMPIsession::ReceiveG4cerr(), and G4VMPIsession::ReceiveG4cout().