Geant4: G4RayTracerSceneHandler Class Reference
G4RayTracerSceneHandler Class Reference
#include <G4RayTracerSceneHandler.hh>
Data Structures
struct PathLessThan
Public Member Functions
G4RayTracerSceneHandler (G4VGraphicsSystem &system, const G4String &name="")
virtual ~G4RayTracerSceneHandler ()
void BuildVisAttsMap (const G4VSolid &solid)
void RequestPrimitives (const G4VSolid &solid)
void AddPrimitive (const G4Polyline &)
void AddPrimitive (const G4Text &)
void AddPrimitive (const G4Circle &)
void AddPrimitive (const G4Square &)
void AddPrimitive (const G4Polyhedron &)
void AddPrimitive (const G4Polymarker &)
void AddPrimitive (const G4Scale &)
void ClearStore ()
const std::map< G4ModelingParameters::PVPointerCopyNoPath, G4VisAttributes, PathLessThan > & GetSceneVisAttsMap () const
Public Member Functions inherited from G4VSceneHandler
G4VSceneHandler (G4VGraphicsSystem &system, G4int id, const G4String &name="")
virtual ~G4VSceneHandler ()
virtual void PreAddSolid (const G4Transform3D &objectTransformation, const G4VisAttributes &)
virtual void PostAddSolid ()
virtual void AddSolid (const G4Box &)
virtual void AddSolid (const G4Cons &)
virtual void AddSolid (const G4Orb &)
virtual void AddSolid (const G4Para &)
virtual void AddSolid (const G4Sphere &)
virtual void AddSolid (const G4Torus &)
virtual void AddSolid (const G4Trap &)
virtual void AddSolid (const G4Trd &)
virtual void AddSolid (const G4Tubs &)
virtual void AddSolid (const G4Ellipsoid &)
virtual void AddSolid (const G4Polycone &)
virtual void AddSolid (const G4Polyhedra &)
virtual void AddSolid (const G4VSolid &)
virtual void AddCompound (const G4VTrajectory &)
virtual void AddCompound (const G4VHit &)
virtual void AddCompound (const G4VDigi &)
virtual void AddCompound (const G4THitsMap< G4double > &)
virtual void AddCompound (const G4THitsMap< G4StatDouble > &)
virtual void BeginModeling ()
virtual void EndModeling ()
virtual void BeginPrimitives (const G4Transform3D &objectTransformation)
virtual void EndPrimitives ()
virtual void BeginPrimitives2D (const G4Transform3D &objectTransformation)
virtual void EndPrimitives2D ()
virtual const G4VisExtent & GetExtent () const
const G4String & GetName () const
G4int GetSceneHandlerId () const
G4int GetViewCount () const
G4VGraphicsSystem * GetGraphicsSystem () const
G4Scene * GetScene () const
const G4ViewerList & GetViewerList () const
G4VModel * GetModel () const
G4VViewer * GetCurrentViewer () const
G4bool GetMarkForClearingTransientStore () const
G4bool IsReadyForTransients () const
G4bool GetTransientsDrawnThisEvent () const
G4bool GetTransientsDrawnThisRun () const
const G4Transform3D & GetObjectTransformation () const
void SetName (const G4String &)
void SetCurrentViewer (G4VViewer *)
virtual void SetScene (G4Scene *)
G4ViewerList & SetViewerList ()
void SetModel (G4VModel *)
void SetMarkForClearingTransientStore (G4bool)
void SetTransientsDrawnThisEvent (G4bool)
void SetTransientsDrawnThisRun (G4bool)
void SetObjectTransformation (const G4Transform3D &)
const G4Colour & GetColour ()
const G4Colour & GetColor ()
const G4Colour & GetTextColour (const G4Text &)
const G4Colour & GetTextColor (const G4Text &)
G4double GetLineWidth (const G4VisAttributes *)
G4ViewParameters::DrawingStyle GetDrawingStyle (const G4VisAttributes *)
G4bool GetAuxEdgeVisible (const G4VisAttributes *)
G4int GetNoOfSides (const G4VisAttributes *)
G4double GetMarkerSize (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerDiameter (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerRadius (const G4VMarker &, MarkerSizeType &)
G4ModelingParameters * CreateModelingParameters ()
void DrawEvent (const G4Event *)
void DrawEndOfRunModels ()
template<class T >
void AddSolidT (const T &solid)
template<class T >
void AddSolidWithAuxiliaryEdges (const T &solid)
G4int IncrementViewCount ()
virtual void ClearTransientStore ()
void AddViewerToList (G4VViewer *pView)
void RemoveViewerFromList (G4VViewer *pView)
Public Member Functions inherited from G4VGraphicsScene
G4VGraphicsScene ()
virtual ~G4VGraphicsScene ()
Private Attributes
std::map< G4ModelingParameters::PVPointerCopyNoPath, G4VisAttributes, PathLessThan > fSceneVisAttsMap
Static Private Attributes
static G4int fSceneIdCount = 0
Additional Inherited Members
Public Types inherited from G4VSceneHandler
enum MarkerSizeType { world, screen }
Protected Member Functions inherited from G4VSceneHandler
virtual void ProcessScene ()
virtual G4VSolid * CreateSectionSolid ()
virtual G4VSolid * CreateCutawaySolid ()
void LoadAtts (const G4Visible &, G4AttHolder *)
Protected Attributes inherited from G4VSceneHandler
G4VGraphicsSystem & fSystem
const G4int fSceneHandlerId
G4String fName
G4int fViewCount
G4ViewerList fViewerList
G4VViewer * fpViewer
G4Scene * fpScene
G4bool fMarkForClearingTransientStore
G4bool fReadyForTransients
G4bool fTransientsDrawnThisEvent
G4bool fTransientsDrawnThisRun
G4bool fProcessingSolid
G4bool fProcessing2D
G4VModel * fpModel
G4Transform3D fObjectTransformation
G4int fNestingDepth
const G4VisAttributes * fpVisAttribs
const G4Transform3D fIdentityTransformation
Detailed Description
Definition at line 38 of file G4RayTracerSceneHandler.hh.
Constructor & Destructor Documentation
G4RayTracerSceneHandler()
G4RayTracerSceneHandler::G4RayTracerSceneHandler (G4VGraphicsSystem & system, const G4String & name = "")
Definition at line 35 of file G4RayTracerSceneHandler.cc.
~G4RayTracerSceneHandler()
G4RayTracerSceneHandler::~G4RayTracerSceneHandler () virtual
Definition at line 60 of file G4RayTracerSceneHandler.cc.
Member Function Documentation
AddPrimitive() [1/7]
void G4RayTracerSceneHandler::AddPrimitive (const G4Circle &) inline virtual
Implements G4VSceneHandler.
Definition at line 55 of file G4RayTracerSceneHandler.hh.
AddPrimitive() [2/7]
void G4RayTracerSceneHandler::AddPrimitive (const G4Polyhedron &) inline virtual
Implements G4VSceneHandler.
Definition at line 57 of file G4RayTracerSceneHandler.hh.
AddPrimitive() [3/7]
void G4RayTracerSceneHandler::AddPrimitive (const G4Polyline &) inline virtual
Implements G4VSceneHandler.
Definition at line 53 of file G4RayTracerSceneHandler.hh.
AddPrimitive() [4/7]
void G4RayTracerSceneHandler::AddPrimitive (const G4Polymarker &) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 58 of file G4RayTracerSceneHandler.hh.
AddPrimitive() [5/7]
void G4RayTracerSceneHandler::AddPrimitive (const G4Scale &) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 59 of file G4RayTracerSceneHandler.hh.
AddPrimitive() [6/7]
void G4RayTracerSceneHandler::AddPrimitive (const G4Square &) inline virtual
Implements G4VSceneHandler.
Definition at line 56 of file G4RayTracerSceneHandler.hh.
AddPrimitive() [7/7]
void G4RayTracerSceneHandler::AddPrimitive (const G4Text &) inline virtual
Implements G4VSceneHandler.
Definition at line 54 of file G4RayTracerSceneHandler.hh.
BuildVisAttsMap()
void G4RayTracerSceneHandler::BuildVisAttsMap (const G4VSolid & solid)
Definition at line 87 of file G4RayTracerSceneHandler.cc.
Referenced by RequestPrimitives().
ClearStore()
void G4RayTracerSceneHandler::ClearStore () virtual
Reimplemented from G4VSceneHandler.
Definition at line 63 of file G4RayTracerSceneHandler.cc.
GetSceneVisAttsMap()
const std::map<G4ModelingParameters::PVPointerCopyNoPath,G4VisAttributes,PathLessThan>& G4RayTracerSceneHandler::GetSceneVisAttsMap () const inline
Definition at line 71 of file G4RayTracerSceneHandler.hh.
Referenced by G4RayTrajectory::AppendStep(), and G4RTSteppingAction::UserSteppingAction().
RequestPrimitives()
void G4RayTracerSceneHandler::RequestPrimitives (const G4VSolid & solid) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 49 of file G4RayTracerSceneHandler.hh.
Field Documentation
fSceneIdCount
G4int G4RayTracerSceneHandler::fSceneIdCount = 0 static private
Definition at line 76 of file G4RayTracerSceneHandler.hh.
fSceneVisAttsMap
std::map<G4ModelingParameters::PVPointerCopyNoPath,G4VisAttributes,PathLessThan> G4RayTracerSceneHandler::fSceneVisAttsMap private
Definition at line 80 of file G4RayTracerSceneHandler.hh.
Referenced by BuildVisAttsMap(), ClearStore(), and GetSceneVisAttsMap().
The documentation for this class was generated from the following files:
source/visualization/RayTracer/include/G4RayTracerSceneHandler.hh
source/visualization/RayTracer/src/G4RayTracerSceneHandler.cc