Geant4: G4DNAPTBIonisationStructure Class Reference
G4DNAPTBIonisationStructure Class Reference
#include <G4DNAPTBIonisationStructure.hh>
Public Member Functions
G4DNAPTBIonisationStructure ()
virtual ~G4DNAPTBIonisationStructure ()
G4double IonisationEnergy (G4int level, const G4String &materialName)
G4int NumberOfLevels (const G4String &materialName)
Private Member Functions
G4String ReplaceMaterial (const G4String &materialName)
Private Attributes
std::map< G4String, G4int > nLevels
std::map< G4String, std::vector< G4double > > energyConstant
Detailed Description
Definition at line 38 of file G4DNAPTBIonisationStructure.hh.
Constructor & Destructor Documentation
G4DNAPTBIonisationStructure()
G4DNAPTBIonisationStructure::G4DNAPTBIonisationStructure ()
Definition at line 32 of file G4DNAPTBIonisationStructure.cc.
~G4DNAPTBIonisationStructure()
G4DNAPTBIonisationStructure::~G4DNAPTBIonisationStructure () virtual
Definition at line 161 of file G4DNAPTBIonisationStructure.cc.
Member Function Documentation
IonisationEnergy()
G4double G4DNAPTBIonisationStructure::IonisationEnergy (G4int level, const G4String & materialName)
Definition at line 165 of file G4DNAPTBIonisationStructure.cc.
Referenced by G4DNAPTBIonisationModel::DifferentialCrossSection(), G4DNAPTBIonisationModel::RandomizeEjectedElectronEnergy(), G4DNAPTBIonisationModel::RandomizeEjectedElectronEnergyFromCumulated(), and G4DNAPTBIonisationModel::SampleSecondaries().
NumberOfLevels()
G4int G4DNAPTBIonisationStructure::NumberOfLevels (const G4String & materialName)
Definition at line 185 of file G4DNAPTBIonisationStructure.cc.
Referenced by G4DNAPTBIonisationModel::ReadDiffCSFile().
ReplaceMaterial()
G4String G4DNAPTBIonisationStructure::ReplaceMaterial (const G4String & materialName) private
Definition at line 201 of file G4DNAPTBIonisationStructure.cc.
Referenced by IonisationEnergy(), and NumberOfLevels().
Field Documentation
energyConstant
std::map<G4String, std::vector<G4double> > G4DNAPTBIonisationStructure::energyConstant private
Definition at line 57 of file G4DNAPTBIonisationStructure.hh.
Referenced by G4DNAPTBIonisationStructure(), and IonisationEnergy().
nLevels
std::map<G4String, G4int> G4DNAPTBIonisationStructure::nLevels private
Definition at line 55 of file G4DNAPTBIonisationStructure.hh.
Referenced by G4DNAPTBIonisationStructure(), IonisationEnergy(), and NumberOfLevels().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/dna/utils/include/G4DNAPTBIonisationStructure.hh
source/processes/electromagnetic/dna/utils/src/G4DNAPTBIonisationStructure.cc