Geant4: G4PartialPhantomParameterisation Class Reference
G4PartialPhantomParameterisation Class Reference
#include <G4PartialPhantomParameterisation.hh>
Public Member Functions
G4PartialPhantomParameterisation ()
~G4PartialPhantomParameterisation ()
void ComputeTransformation (const G4int, G4VPhysicalVolume *) const
G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=0)
G4int GetReplicaNo (const G4ThreeVector &localPoint, const G4ThreeVector &localDir)
G4ThreeVector GetTranslation (const G4int copyNo) const
size_t GetMaterialIndex (size_t nx, size_t ny, size_t nz) const
size_t GetMaterialIndex (size_t copyNo) const
G4Material * GetMaterial (size_t nx, size_t ny, size_t nz) const
G4Material * GetMaterial (size_t copyNo) const
void SetFilledIDs (std::multimap< G4int, G4int > fid)
void SetFilledMins (std::map< G4int, std::map< G4int, G4int > > fmins)
void BuildContainerWalls ()
Public Member Functions inherited from G4PhantomParameterisation
G4PhantomParameterisation ()
~G4PhantomParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
void BuildContainerSolid (G4VPhysicalVolume *pPhysicalVol)
void BuildContainerSolid (G4VSolid *pMotherSolid)
void SetMaterials (std::vector< G4Material * > &mates)
void SetMaterialIndices (size_t *matInd)
void SetVoxelDimensions (G4double halfx, G4double halfy, G4double halfz)
void SetNoVoxel (size_t nx, size_t ny, size_t nz)
G4double GetVoxelHalfX () const
G4double GetVoxelHalfY () const
G4double GetVoxelHalfZ () const
size_t GetNoVoxelX () const
size_t GetNoVoxelY () const
size_t GetNoVoxelZ () const
size_t GetNoVoxel () const
std::vector< G4Material * > GetMaterials () const
size_t * GetMaterialIndices () const
G4VSolid * GetContainerSolid () const
G4ThreeVector GetTranslation (const G4int copyNo) const
G4bool SkipEqualMaterials () const
void SetSkipEqualMaterials (G4bool skip)
size_t GetMaterialIndex (size_t nx, size_t ny, size_t nz) const
size_t GetMaterialIndex (size_t copyNo) const
G4Material * GetMaterial (size_t nx, size_t ny, size_t nz) const
G4Material * GetMaterial (size_t copyNo) const
void CheckVoxelsFillContainer (G4double contX, G4double contY, G4double contZ) const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Private Member Functions
void ComputeVoxelIndices (const G4int copyNo, size_t &nx, size_t &ny, size_t &nz) const
void CheckCopyNo (const G4int copyNo) const
Private Attributes
std::multimap< G4int, G4int > fFilledIDs
std::map< G4int, std::map< G4int, G4int > > fFilledMins
Additional Inherited Members
Protected Attributes inherited from G4PhantomParameterisation
G4double fVoxelHalfX
G4double fVoxelHalfY
G4double fVoxelHalfZ
size_t fNoVoxelX
size_t fNoVoxelY
size_t fNoVoxelZ
size_t fNoVoxelXY
size_t fNoVoxel
std::vector< G4Material * > fMaterials
size_t * fMaterialIndices
G4VSolid * fContainerSolid
G4double fContainerWallX
G4double fContainerWallY
G4double fContainerWallZ
G4double kCarTolerance
G4bool bSkipEqualMaterials
Detailed Description
Definition at line 56 of file G4PartialPhantomParameterisation.hh.
Constructor & Destructor Documentation
G4PartialPhantomParameterisation()
G4PartialPhantomParameterisation::G4PartialPhantomParameterisation ()
Definition at line 48 of file G4PartialPhantomParameterisation.cc.
~G4PartialPhantomParameterisation()
G4PartialPhantomParameterisation::~G4PartialPhantomParameterisation ()
Definition at line 55 of file G4PartialPhantomParameterisation.cc.
Member Function Documentation
BuildContainerWalls()
void G4PartialPhantomParameterisation::BuildContainerWalls ()
Definition at line 339 of file G4PartialPhantomParameterisation.cc.
Referenced by DicomPartialDetectorConstruction::ConstructPhantom().
CheckCopyNo()
void G4PartialPhantomParameterisation::CheckCopyNo (const G4int copyNo) const private
Definition at line 324 of file G4PartialPhantomParameterisation.cc.
Referenced by ComputeMaterial(), ComputeVoxelIndices(), GetMaterialIndex(), and GetTranslation().
ComputeMaterial()
G4Material * G4PartialPhantomParameterisation::ComputeMaterial (const G4int repNo, G4VPhysicalVolume * currentVol, const G4VTouchable * parentTouch = 0) virtual
Reimplemented from G4PhantomParameterisation.
Definition at line 90 of file G4PartialPhantomParameterisation.cc.
ComputeTransformation()
void G4PartialPhantomParameterisation::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const virtual
Reimplemented from G4PhantomParameterisation.
Definition at line 61 of file G4PartialPhantomParameterisation.cc.
ComputeVoxelIndices()
void G4PartialPhantomParameterisation::ComputeVoxelIndices (const G4int copyNo, size_t & nx, size_t & ny, size_t & nz) const private
Definition at line 138 of file G4PartialPhantomParameterisation.cc.
Referenced by GetTranslation().
GetMaterial() [1/2]
G4Material * G4PartialPhantomParameterisation::GetMaterial (size_t copyNo) const
Definition at line 130 of file G4PartialPhantomParameterisation.cc.
GetMaterial() [2/2]
G4Material * G4PartialPhantomParameterisation::GetMaterial (size_t nx, size_t ny, size_t nz) const
Definition at line 122 of file G4PartialPhantomParameterisation.cc.
GetMaterialIndex() [1/2]
size_t G4PartialPhantomParameterisation::GetMaterialIndex (size_t copyNo) const
Definition at line 101 of file G4PartialPhantomParameterisation.cc.
GetMaterialIndex() [2/2]
size_t G4PartialPhantomParameterisation::GetMaterialIndex (size_t nx, size_t ny, size_t nz) const
Definition at line 113 of file G4PartialPhantomParameterisation.cc.
Referenced by ComputeMaterial(), and GetMaterial().
GetReplicaNo()
G4int G4PartialPhantomParameterisation::GetReplicaNo (const G4ThreeVector & localPoint, const G4ThreeVector & localDir) virtual
Reimplemented from G4PhantomParameterisation.
Definition at line 164 of file G4PartialPhantomParameterisation.cc.
GetTranslation()
G4ThreeVector G4PartialPhantomParameterisation::GetTranslation (const G4int copyNo) const
Definition at line 72 of file G4PartialPhantomParameterisation.cc.
Referenced by ComputeTransformation().
SetFilledIDs()
void G4PartialPhantomParameterisation::SetFilledIDs (std::multimap< G4int, G4int > fid) inline
Definition at line 82 of file G4PartialPhantomParameterisation.hh.
Referenced by DicomPartialDetectorConstruction::ConstructPhantom().
SetFilledMins()
void G4PartialPhantomParameterisation::SetFilledMins (std::map< G4int, std::map< G4int, G4int > > fmins) inline
Definition at line 86 of file G4PartialPhantomParameterisation.hh.
Referenced by DicomPartialDetectorConstruction::ConstructPhantom().
Field Documentation
fFilledIDs
std::multimap<G4int,G4int> G4PartialPhantomParameterisation::fFilledIDs private
Definition at line 103 of file G4PartialPhantomParameterisation.hh.
Referenced by ComputeVoxelIndices(), GetReplicaNo(), and SetFilledIDs().
fFilledMins
std::map< G4int, std::map<G4int,G4int> > G4PartialPhantomParameterisation::fFilledMins private
Definition at line 104 of file G4PartialPhantomParameterisation.hh.
Referenced by SetFilledMins().
The documentation for this class was generated from the following files:
source/geometry/navigation/include/G4PartialPhantomParameterisation.hh
source/geometry/navigation/src/G4PartialPhantomParameterisation.cc