Geant4: source/visualization/OpenInventor/src/wheelmouse.cc File Reference
wheelmouse.cc File Reference
#include <X11/Intrinsic.h>
#include <X11/Xlib.h>
#include <Xm/Xm.h>
#include <Xm/ScrollBar.h>
Functions
static void mouseScroll (Widget, XtPointer client_data, XEvent *event, Boolean *)
void xmAddMouseEventHandler (Widget w)
Function Documentation
mouseScroll()
static void mouseScroll (Widget , XtPointer client_data, XEvent * event, Boolean *) static
Definition at line 57 of file wheelmouse.cc.
Referenced by xmAddMouseEventHandler().
xmAddMouseEventHandler()
void xmAddMouseEventHandler (Widget w)
Definition at line 126 of file wheelmouse.cc.
Referenced by G4OpenInventorXtExaminerViewer::constructListsDialog(), G4OpenInventorXtExaminerViewer::createElementsList(), G4OpenInventorXtExaminerViewer::popUpFileSelDialog(), G4OpenInventorXtExaminerViewer::saveRefCoordsDialogCB(), and G4OpenInventorXtExaminerViewer::saveSceneGraphDialogCB().