Geant4: CexmcEventAction Class Reference
CexmcEventAction Class Reference
#include <CexmcEventAction.hh>
Public Member Functions
CexmcEventAction (CexmcPhysicsManager *physicsManager, G4int verbose=0)
virtual ~CexmcEventAction ()
void BeginOfEventAction (const G4Event *event)
void EndOfEventAction (const G4Event *event)
void BeamParticleChangeHook (void)
void SetVerboseOnCexmcLevel (G4int value)
void SetVerboseDrawLevel (G4int value)
CexmcChargeExchangeReconstructor * GetReconstructor (void)
Public Member Functions inherited from G4UserEventAction
G4UserEventAction ()
virtual ~G4UserEventAction ()
virtual void SetEventManager (G4EventManager *value)
Static Public Member Functions
static CexmcEnergyDepositStore * MakeEnergyDepositStore (const CexmcEnergyDepositDigitizer *digitizer)
static CexmcTrackPointsStore * MakeTrackPointsStore (const CexmcTrackPointsDigitizer *digitizer)
static void PrintEnergyDeposit (const CexmcEnergyDepositStore *edStore)
static void PrintTrackPoints (const CexmcTrackPointsStore *tpStore)
static void PrintProductionModelData (const CexmcAngularRangeList &angularRanges, const CexmcProductionModelData &pmData)
Private Member Functions
void PrintReconstructedData (const CexmcAngularRangeList &angularRanges, const CexmcAngularRange &angularGap) const
void DrawTrajectories (const G4Event *event)
void DrawTrackPoints (const CexmcTrackPointsStore *tpStore) const
void DrawReconstructionData (void)
void UpdateRunHits (const CexmcAngularRangeList &aRangesReal, const CexmcAngularRangeList &aRangesRec, G4bool tpDigitizerHasTriggered, G4bool edDigitizerHasTriggered, G4bool edDigitizerMonitorHasTriggered, G4bool reconstructorHasTriggered, const CexmcAngularRange &aGap)
Private Attributes
CexmcPhysicsManager * physicsManager
CexmcChargeExchangeReconstructor * reconstructor
G4int verbose
G4int verboseDraw
CexmcEventActionMessenger * messenger
Additional Inherited Members
Protected Attributes inherited from G4UserEventAction
G4EventManager * fpEventManager
Detailed Description
Definition at line 61 of file CexmcEventAction.hh.
Constructor & Destructor Documentation
CexmcEventAction()
CexmcEventAction::CexmcEventAction (CexmcPhysicsManager * physicsManager, G4int verbose = 0) explicit
Definition at line 95 of file CexmcEventAction.cc.
~CexmcEventAction()
CexmcEventAction::~CexmcEventAction () virtual
Definition at line 114 of file CexmcEventAction.cc.
Member Function Documentation
BeamParticleChangeHook()
void CexmcEventAction::BeamParticleChangeHook (void)
Definition at line 121 of file CexmcEventAction.cc.
Referenced by CexmcRunManager::BeamParticleChangeHook().
BeginOfEventAction()
void CexmcEventAction::BeginOfEventAction (const G4Event * event) virtual
Reimplemented from G4UserEventAction.
Definition at line 127 of file CexmcEventAction.cc.
DrawReconstructionData()
void CexmcEventAction::DrawReconstructionData (void) private
Definition at line 649 of file CexmcEventAction.cc.
Referenced by EndOfEventAction().
DrawTrackPoints()
void CexmcEventAction::DrawTrackPoints (const CexmcTrackPointsStore * tpStore) const private
Definition at line 591 of file CexmcEventAction.cc.
Referenced by EndOfEventAction().
DrawTrajectories()
void CexmcEventAction::DrawTrajectories (const G4Event * event) private
Definition at line 568 of file CexmcEventAction.cc.
Referenced by EndOfEventAction().
EndOfEventAction()
void CexmcEventAction::EndOfEventAction (const G4Event * event) virtual
Reimplemented from G4UserEventAction.
Definition at line 803 of file CexmcEventAction.cc.
GetReconstructor()
CexmcChargeExchangeReconstructor * CexmcEventAction::GetReconstructor (void) inline
Definition at line 179 of file CexmcEventAction.hh.
MakeEnergyDepositStore()
CexmcEnergyDepositStore * CexmcEventAction::MakeEnergyDepositStore (const CexmcEnergyDepositDigitizer * digitizer) static
Definition at line 140 of file CexmcEventAction.cc.
Referenced by EndOfEventAction().
MakeTrackPointsStore()
CexmcTrackPointsStore * CexmcEventAction::MakeTrackPointsStore (const CexmcTrackPointsDigitizer * digitizer) static
Definition at line 169 of file CexmcEventAction.cc.
Referenced by EndOfEventAction().
PrintEnergyDeposit()
void CexmcEventAction::PrintEnergyDeposit (const CexmcEnergyDepositStore * edStore) static
Definition at line 214 of file CexmcEventAction.cc.
Referenced by EndOfEventAction().
PrintProductionModelData()
void CexmcEventAction::PrintProductionModelData (const CexmcAngularRangeList & angularRanges, const CexmcProductionModelData & pmData) static
Definition at line 263 of file CexmcEventAction.cc.
Referenced by EndOfEventAction().
PrintReconstructedData()
void CexmcEventAction::PrintReconstructedData (const CexmcAngularRangeList & angularRanges, const CexmcAngularRange & angularGap) const private
Definition at line 272 of file CexmcEventAction.cc.
Referenced by EndOfEventAction().
PrintTrackPoints()
void CexmcEventAction::PrintTrackPoints (const CexmcTrackPointsStore * tpStore) static
Definition at line 233 of file CexmcEventAction.cc.
Referenced by EndOfEventAction().
SetVerboseDrawLevel()
void CexmcEventAction::SetVerboseDrawLevel (G4int value) inline
Definition at line 172 of file CexmcEventAction.hh.
Referenced by CexmcEventActionMessenger::SetNewValue().
SetVerboseOnCexmcLevel()
void CexmcEventAction::SetVerboseOnCexmcLevel (G4int value) inline
Definition at line 166 of file CexmcEventAction.hh.
Referenced by CexmcEventActionMessenger::SetNewValue().
UpdateRunHits()
void CexmcEventAction::UpdateRunHits (const CexmcAngularRangeList & aRangesReal, const CexmcAngularRangeList & aRangesRec, G4bool tpDigitizerHasTriggered, G4bool edDigitizerHasTriggered, G4bool edDigitizerMonitorHasTriggered, G4bool reconstructorHasTriggered, const CexmcAngularRange & aGap) private
Definition at line 672 of file CexmcEventAction.cc.
Referenced by EndOfEventAction().
Field Documentation
messenger
CexmcEventActionMessenger* CexmcEventAction::messenger private
Definition at line 162 of file CexmcEventAction.hh.
Referenced by CexmcEventAction(), and ~CexmcEventAction().
physicsManager
CexmcPhysicsManager* CexmcEventAction::physicsManager private
Definition at line 149 of file CexmcEventAction.hh.
Referenced by BeginOfEventAction(), CexmcEventAction(), and EndOfEventAction().
reconstructor
CexmcChargeExchangeReconstructor* CexmcEventAction::reconstructor private
Definition at line 151 of file CexmcEventAction.hh.
Referenced by BeamParticleChangeHook(), CexmcEventAction(), DrawReconstructionData(), EndOfEventAction(), GetReconstructor(), PrintReconstructedData(), and ~CexmcEventAction().
verbose
G4int CexmcEventAction::verbose private
Definition at line 158 of file CexmcEventAction.hh.
Referenced by EndOfEventAction(), and SetVerboseOnCexmcLevel().
verboseDraw
G4int CexmcEventAction::verboseDraw private
Definition at line 160 of file CexmcEventAction.hh.
Referenced by EndOfEventAction(), and SetVerboseDrawLevel().
The documentation for this class was generated from the following files:
examples/advanced/ChargeExchangeMC/include/CexmcEventAction.hh
examples/advanced/ChargeExchangeMC/src/CexmcEventAction.cc