Geant4: G4SingleDiffractiveExcitation Class Reference
G4SingleDiffractiveExcitation Class Reference
#include <G4SingleDiffractiveExcitation.hh>
Public Member Functions
G4SingleDiffractiveExcitation ()
~G4SingleDiffractiveExcitation ()
G4bool ExciteParticipants (G4VSplitableHadron *aPartner, G4VSplitableHadron *bPartner, G4bool ProjectileDiffraction) const
Public Member Functions inherited from G4QGSDiffractiveExcitation
G4QGSDiffractiveExcitation ()
virtual ~G4QGSDiffractiveExcitation ()
virtual G4ExcitedString * String (G4VSplitableHadron *aHadron, G4bool isProjectile) const
Private Member Functions
G4SingleDiffractiveExcitation (const G4SingleDiffractiveExcitation &right)
G4double ChooseX (G4double Xmin, G4double Xmax) const
G4ThreeVector GaussianPt (G4double widthSquare, G4double maxPtSquare) const
const G4SingleDiffractiveExcitation & operator= (const G4SingleDiffractiveExcitation &right)
G4bool operator== (const G4SingleDiffractiveExcitation &right) const
G4bool operator!= (const G4SingleDiffractiveExcitation &right) const
Detailed Description
Definition at line 48 of file G4SingleDiffractiveExcitation.hh.
Constructor & Destructor Documentation
G4SingleDiffractiveExcitation() [1/2]
G4SingleDiffractiveExcitation::G4SingleDiffractiveExcitation ()
Definition at line 53 of file G4SingleDiffractiveExcitation.cc.
~G4SingleDiffractiveExcitation()
G4SingleDiffractiveExcitation::~G4SingleDiffractiveExcitation ()
Definition at line 55 of file G4SingleDiffractiveExcitation.cc.
G4SingleDiffractiveExcitation() [2/2]
G4SingleDiffractiveExcitation::G4SingleDiffractiveExcitation (const G4SingleDiffractiveExcitation & right) private
Member Function Documentation
ChooseX()
G4double G4SingleDiffractiveExcitation::ChooseX (G4double Xmin, G4double Xmax) const private
Definition at line 266 of file G4SingleDiffractiveExcitation.cc.
Referenced by ExciteParticipants().
ExciteParticipants()
G4bool G4SingleDiffractiveExcitation::ExciteParticipants (G4VSplitableHadron * aPartner, G4VSplitableHadron * bPartner, G4bool ProjectileDiffraction) const virtual
Reimplemented from G4QGSDiffractiveExcitation.
Definition at line 58 of file G4SingleDiffractiveExcitation.cc.
Referenced by G4QGSParticipants::PerformDiffractiveCollisions().
GaussianPt()
G4ThreeVector G4SingleDiffractiveExcitation::GaussianPt (G4double widthSquare, G4double maxPtSquare) const private
Definition at line 283 of file G4SingleDiffractiveExcitation.cc.
Referenced by ExciteParticipants().
operator!=()
G4bool G4SingleDiffractiveExcitation::operator!= (const G4SingleDiffractiveExcitation & right) const private
operator=()
const G4SingleDiffractiveExcitation& G4SingleDiffractiveExcitation::operator= (const G4SingleDiffractiveExcitation & right) private
operator==()
G4bool G4SingleDiffractiveExcitation::operator== (const G4SingleDiffractiveExcitation & right) const private
The documentation for this class was generated from the following files:
source/processes/hadronic/models/parton_string/qgsm/include/G4SingleDiffractiveExcitation.hh
source/processes/hadronic/models/parton_string/qgsm/src/G4SingleDiffractiveExcitation.cc