Geant4: GIDI_settings_flux Class Reference
GIDI_settings_flux Class Reference
#include <GIDI_settings.hh>
Public Member Functions
GIDI_settings_flux (std::string const &label, double temperature_MeV)
GIDI_settings_flux (char const *label, double temperature_MeV)
GIDI_settings_flux (GIDI_settings_flux const &flux)
~GIDI_settings_flux ()
const GIDI_settings_flux_order * operator[] (int order) const
int getMaxOrder (void) const
int size (void) const
std::string getLabel () const
bool isLabel (std::string const &label) const
bool isLabel (char const *label) const
double getTemperature () const
void addFluxOrder (GIDI_settings_flux_order const &fluxOrder)
void print (bool outline=true, int valuesPerLine=10) const
Private Attributes
std::string mLabel
Label for the flux.
double mTemperature
std::vector< GIDI_settings_flux_order > mFluxOrders
List of fluxes for each Legendre order, l, sorted by Legendre order starting with l = 0.
Detailed Description
Definition at line 120 of file GIDI_settings.hh.
Constructor & Destructor Documentation
GIDI_settings_flux() [1/3]
GIDI_settings_flux::GIDI_settings_flux (std::string const & label, double temperature_MeV)
Definition at line 89 of file GIDI_settings_flux.cc.
GIDI_settings_flux() [2/3]
GIDI_settings_flux::GIDI_settings_flux (char const * label, double temperature_MeV)
Definition at line 97 of file GIDI_settings_flux.cc.
GIDI_settings_flux() [3/3]
GIDI_settings_flux::GIDI_settings_flux (GIDI_settings_flux const & flux)
Definition at line 105 of file GIDI_settings_flux.cc.
~GIDI_settings_flux()
GIDI_settings_flux::~GIDI_settings_flux ()
Definition at line 114 of file GIDI_settings_flux.cc.
Member Function Documentation
addFluxOrder()
void GIDI_settings_flux::addFluxOrder (GIDI_settings_flux_order const & fluxOrder)
Definition at line 127 of file GIDI_settings_flux.cc.
Referenced by GIDI_settings_flux().
getLabel()
std::string GIDI_settings_flux::getLabel () const inline
Definition at line 137 of file GIDI_settings.hh.
Referenced by GIDI_settings_flux().
getMaxOrder()
int GIDI_settings_flux::getMaxOrder (void) const inline
Definition at line 134 of file GIDI_settings.hh.
getTemperature()
double GIDI_settings_flux::getTemperature () const inline
Definition at line 140 of file GIDI_settings.hh.
Referenced by GIDI_settings_particle::addFlux(), and GIDI_settings_processedFlux::getTemperature().
isLabel() [1/2]
bool GIDI_settings_flux::isLabel (char const * label) const inline
Definition at line 139 of file GIDI_settings.hh.
isLabel() [2/2]
bool GIDI_settings_flux::isLabel (std::string const & label) const inline
Definition at line 138 of file GIDI_settings.hh.
operator[]()
const GIDI_settings_flux_order * GIDI_settings_flux::operator[] (int order) const
Definition at line 120 of file GIDI_settings_flux.cc.
print()
void GIDI_settings_flux::print (bool outline = true, int valuesPerLine = 10) const
Definition at line 139 of file GIDI_settings_flux.cc.
size()
int GIDI_settings_flux::size (void) const inline
Definition at line 135 of file GIDI_settings.hh.
Referenced by GIDI_settings_processedFlux::GIDI_settings_processedFlux(), and print().
Field Documentation
mFluxOrders
std::vector<GIDI_settings_flux_order> GIDI_settings_flux::mFluxOrders private
List of fluxes for each Legendre order, l, sorted by Legendre order starting with l = 0.
Definition at line 125 of file GIDI_settings.hh.
Referenced by addFluxOrder(), getMaxOrder(), GIDI_settings_flux(), operator[](), print(), and size().
mLabel
std::string GIDI_settings_flux::mLabel private
Label for the flux.
Definition at line 123 of file GIDI_settings.hh.
Referenced by getLabel(), GIDI_settings_flux(), isLabel(), and print().
mTemperature
double GIDI_settings_flux::mTemperature private
Definition at line 124 of file GIDI_settings.hh.
Referenced by getTemperature(), and GIDI_settings_flux().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/lend/include/GIDI_settings.hh
source/processes/hadronic/models/lend/src/GIDI_settings_flux.cc