Geant4: G4Hdf5RFileManager Class Reference
G4Hdf5RFileManager Class Reference
#include <G4Hdf5RFileManager.hh>
Public Member Functions
G4Hdf5RFileManager (const G4AnalysisManagerState &state)
virtual ~G4Hdf5RFileManager ()
hid_t GetRFile (const G4String &fileName, G4bool isPerThread) const
hid_t GetHistoRDirectory (const G4String &fileName, const G4String &dirName, G4bool isPerThread)
hid_t GetNtupleRDirectory (const G4String &fileName, const G4String &dirName, G4bool isPerThread)
Public Member Functions inherited from G4BaseFileManager
G4BaseFileManager (const G4AnalysisManagerState &state)
virtual ~G4BaseFileManager ()
virtual G4bool SetFileName (const G4String &fileName)
G4String GetFileName () const
G4String GetFullFileName (const G4String &baseFileName="", G4bool isPerThread=true) const
G4String GetHnFileName (const G4String &hnType, const G4String &hnName) const
G4String GetNtupleFileName (const G4String &ntupleName) const
G4String GetNtupleFileName (G4int ntupleFileNumber) const
G4String GetPlotFileName () const
G4String GetFileType () const
Private Member Functions
hid_t OpenRFile (const G4String &fileName, G4bool isPerThread)
hid_t OpenDirectory (hid_t file, const G4String &directoryName)
hid_t GetRDirectory (const G4String &directoryType, const G4String &fileName, const G4String &dirName, G4bool isPerThread)
Private Attributes
std::map< G4String, hid_t > fRFiles
Static Private Attributes
static const G4String fgkDefaultDirectoryName = "default"
Additional Inherited Members
Protected Member Functions inherited from G4BaseFileManager
G4String TakeOffExtension (G4String &name) const
Protected Attributes inherited from G4BaseFileManager
const G4AnalysisManagerState & fState
G4String fFileName
Detailed Description
Definition at line 41 of file G4Hdf5RFileManager.hh.
Constructor & Destructor Documentation
G4Hdf5RFileManager()
G4Hdf5RFileManager::G4Hdf5RFileManager (const G4AnalysisManagerState & state) explicit
Definition at line 45 of file G4Hdf5RFileManager.cc.
~G4Hdf5RFileManager()
G4Hdf5RFileManager::~G4Hdf5RFileManager () virtual
Definition at line 52 of file G4Hdf5RFileManager.cc.
Member Function Documentation
GetHistoRDirectory()
hid_t G4Hdf5RFileManager::GetHistoRDirectory (const G4String & fileName, const G4String & dirName, G4bool isPerThread)
Definition at line 187 of file G4Hdf5RFileManager.cc.
GetNtupleRDirectory()
hid_t G4Hdf5RFileManager::GetNtupleRDirectory (const G4String & fileName, const G4String & dirName, G4bool isPerThread)
Definition at line 194 of file G4Hdf5RFileManager.cc.
Referenced by G4Hdf5AnalysisReader::ReadNtupleImpl().
GetRDirectory()
hid_t G4Hdf5RFileManager::GetRDirectory (const G4String & directoryType, const G4String & fileName, const G4String & dirName, G4bool isPerThread) private
Definition at line 132 of file G4Hdf5RFileManager.cc.
Referenced by GetHistoRDirectory(), and GetNtupleRDirectory().
GetRFile()
hid_t G4Hdf5RFileManager::GetRFile (const G4String & fileName, G4bool isPerThread) const
Definition at line 171 of file G4Hdf5RFileManager.cc.
Referenced by GetRDirectory().
OpenDirectory()
hid_t G4Hdf5RFileManager::OpenDirectory (hid_t file, const G4String & directoryName) private
Definition at line 104 of file G4Hdf5RFileManager.cc.
Referenced by GetRDirectory().
OpenRFile()
hid_t G4Hdf5RFileManager::OpenRFile (const G4String & fileName, G4bool isPerThread) private
Definition at line 61 of file G4Hdf5RFileManager.cc.
Referenced by GetRDirectory().
Field Documentation
fgkDefaultDirectoryName
const G4String G4Hdf5RFileManager::fgkDefaultDirectoryName = "default" static private
Definition at line 56 of file G4Hdf5RFileManager.hh.
Referenced by GetRDirectory().
fRFiles
std::map<G4String, hid_t> G4Hdf5RFileManager::fRFiles private
Definition at line 66 of file G4Hdf5RFileManager.hh.
Referenced by GetRFile(), and OpenRFile().
The documentation for this class was generated from the following files:
source/analysis/hdf5/include/G4Hdf5RFileManager.hh
source/analysis/hdf5/src/G4Hdf5RFileManager.cc