Geant4: source/processes/hadronic/models/lend/src/nf_incompleteGammaFunctions.cc File Reference
nf_incompleteGammaFunctions.cc File Reference
#include "nf_specialFunctions.h"
Functions
double nf_incompleteGammaFunctionComplementary (double a, double x, nfu_status *status)
double nf_incompleteGammaFunction (double a, double x, nfu_status *status)
Variables
static double big = 4.503599627370496e15
static double biginv = 2.22044604925031308085e-16
Function Documentation
nf_incompleteGammaFunction()
double nf_incompleteGammaFunction (double a, double x, nfu_status * status)
Definition at line 155 of file nf_incompleteGammaFunctions.cc.
Referenced by MCGIDI_energy_parseMadlandNixFromTOM_callback_g(), and nf_incompleteGammaFunctionComplementary().
nf_incompleteGammaFunctionComplementary()
double nf_incompleteGammaFunctionComplementary (double a, double x, nfu_status * status)
Definition at line 88 of file nf_incompleteGammaFunctions.cc.
Referenced by MCGIDI_energy_parseMadlandNixFromTOM_callback_g(), and nf_incompleteGammaFunction().
Variable Documentation
big
double big = 4.503599627370496e15 static
Definition at line 82 of file nf_incompleteGammaFunctions.cc.
Referenced by nf_incompleteGammaFunctionComplementary().
biginv
double biginv = 2.22044604925031308085e-16 static
Definition at line 83 of file nf_incompleteGammaFunctions.cc.
Referenced by nf_incompleteGammaFunctionComplementary().