Geant4: G4VLongitudinalStringDecay Class Reference
G4VLongitudinalStringDecay Class Reference abstract
#include <G4VLongitudinalStringDecay.hh>
Public Member Functions
G4VLongitudinalStringDecay ()
virtual ~G4VLongitudinalStringDecay ()
virtual G4KineticTrackVector * FragmentString (const G4ExcitedString &theString)=0
G4int SampleQuarkFlavor (void)
G4ThreeVector SampleQuarkPt (G4double ptMax=-1.)
G4KineticTrackVector * DecayResonans (G4KineticTrackVector *aHadrons)
void SetSigmaTransverseMomentum (G4double aQT)
void SetStrangenessSuppression (G4double aValue)
void SetDiquarkSuppression (G4double aValue)
void SetDiquarkBreakProbability (G4double aValue)
void SetVectorMesonProbability (G4double aValue)
void SetSpinThreeHalfBarionProbability (G4double aValue)
void SetScalarMesonMixings (std::vector< G4double > aVector)
void SetVectorMesonMixings (std::vector< G4double > aVector)
void SetStringTensionParameter (G4double aValue)
Protected Types
typedef std::pair< G4ParticleDefinition *, G4ParticleDefinition * > pDefPair
typedef G4ParticleDefinition *(G4HadronBuilder::* Pcreate) (G4ParticleDefinition *, G4ParticleDefinition *)
Protected Member Functions
virtual void SetMassCut (G4double aValue)
G4double GetMassCut ()
G4KineticTrackVector * LightFragmentationTest (const G4ExcitedString *const theString)
G4double FragmentationMass (const G4FragmentingString *const string, Pcreate build=0, pDefPair *pdefs=0)
G4ParticleDefinition * FindParticle (G4int Encoding)
virtual void Sample4Momentum (G4LorentzVector *Mom, G4double Mass, G4LorentzVector *AntiMom, G4double AntiMass, G4double InitialMass)=0
virtual G4bool StopFragmenting (const G4FragmentingString *const string)=0
virtual G4bool IsFragmentable (const G4FragmentingString *const string)=0
virtual G4bool SplitLast (G4FragmentingString *string, G4KineticTrackVector *LeftVector, G4KineticTrackVector *RightVector)=0
G4ExcitedString * CopyExcited (const G4ExcitedString &string)
G4ParticleDefinition * QuarkSplitup (G4ParticleDefinition *decay, G4ParticleDefinition *&created)
virtual G4ParticleDefinition * DiQuarkSplitup (G4ParticleDefinition *decay, G4ParticleDefinition *&created)=0
pDefPair CreatePartonPair (G4int NeedParticle, G4bool AllowDiquarks=true)
virtual G4KineticTrack * Splitup (G4FragmentingString *string, G4FragmentingString *&newString)=0
virtual G4LorentzVector * SplitEandP (G4ParticleDefinition *pHadron, G4FragmentingString *string, G4FragmentingString *newString)=0
virtual G4double GetLightConeZ (G4double zmin, G4double zmax, G4int PartonEncoding, G4ParticleDefinition *pHadron, G4double Px, G4double Py)=0
void CalculateHadronTimePosition (G4double theInitialStringMass, G4KineticTrackVector *)
void ConstructParticle ()
G4ParticleDefinition * CreateHadron (G4int id1, G4int id2, G4bool theGivenSpin, G4int theSpin)
G4double GetDiquarkSuppress ()
G4double GetDiquarkBreakProb ()
G4double GetStrangeSuppress ()
G4double GetClusterMass ()
G4int GetClusterLoopInterrupt ()
G4double GetStringTensionParameter ()
Protected Attributes
G4double MassCut
G4double ClusterMass
G4double SigmaQT
G4double DiquarkSuppress
G4double DiquarkBreakProb
G4double SmoothParam
G4double StrangeSuppress
G4int StringLoopInterrupt
G4int ClusterLoopInterrupt
G4HadronBuilder * hadronizer
G4double pspin_meson
G4double pspin_barion
std::vector< G4double > vectorMesonMix
std::vector< G4double > scalarMesonMix
G4bool PastInitPhase
G4double Kappa
Private Member Functions
G4VLongitudinalStringDecay (const G4VLongitudinalStringDecay &right)
const G4VLongitudinalStringDecay & operator= (const G4VLongitudinalStringDecay &right)
int operator== (const G4VLongitudinalStringDecay &right) const
int operator!= (const G4VLongitudinalStringDecay &right) const
Detailed Description
Definition at line 45 of file G4VLongitudinalStringDecay.hh.
Member Typedef Documentation
Pcreate
typedef G4ParticleDefinition*(G4HadronBuilder::* G4VLongitudinalStringDecay::Pcreate) (G4ParticleDefinition *, G4ParticleDefinition *) protected
Definition at line 75 of file G4VLongitudinalStringDecay.hh.
pDefPair
typedef std::pair<G4ParticleDefinition*, G4ParticleDefinition*> G4VLongitudinalStringDecay::pDefPair protected
Definition at line 71 of file G4VLongitudinalStringDecay.hh.
Constructor & Destructor Documentation
G4VLongitudinalStringDecay() [1/2]
G4VLongitudinalStringDecay::G4VLongitudinalStringDecay ()
Definition at line 64 of file G4VLongitudinalStringDecay.cc.
~G4VLongitudinalStringDecay()
G4VLongitudinalStringDecay::~G4VLongitudinalStringDecay () virtual
Definition at line 112 of file G4VLongitudinalStringDecay.cc.
G4VLongitudinalStringDecay() [2/2]
G4VLongitudinalStringDecay::G4VLongitudinalStringDecay (const G4VLongitudinalStringDecay & right) private
Member Function Documentation
CalculateHadronTimePosition()
void G4VLongitudinalStringDecay::CalculateHadronTimePosition (G4double theInitialStringMass, G4KineticTrackVector * Hadrons) protected
Definition at line 343 of file G4VLongitudinalStringDecay.cc.
Referenced by G4QGSMFragmentation::FragmentString().
ConstructParticle()
void G4VLongitudinalStringDecay::ConstructParticle () protected
CopyExcited()
G4ExcitedString * G4VLongitudinalStringDecay::CopyExcited (const G4ExcitedString & string) protected
Definition at line 276 of file G4VLongitudinalStringDecay.cc.
Referenced by G4QGSMFragmentation::FragmentString().
CreateHadron()
G4ParticleDefinition* G4VLongitudinalStringDecay::CreateHadron (G4int id1, G4int id2, G4bool theGivenSpin, G4int theSpin) protected
CreatePartonPair()
G4VLongitudinalStringDecay::pDefPair G4VLongitudinalStringDecay::CreatePartonPair (G4int NeedParticle, G4bool AllowDiquarks = true) protected
Definition at line 304 of file G4VLongitudinalStringDecay.cc.
Referenced by G4QGSMFragmentation::DiQuarkSplitup(), G4LundStringFragmentation::DiQuarkSplitup(), QuarkSplitup(), and G4QGSMFragmentation::SplitLast().
DecayResonans()
G4KineticTrackVector* G4VLongitudinalStringDecay::DecayResonans (G4KineticTrackVector * aHadrons)
DiQuarkSplitup()
virtual G4ParticleDefinition* G4VLongitudinalStringDecay::DiQuarkSplitup (G4ParticleDefinition * decay, G4ParticleDefinition *& created) protected pure virtual
Implemented in G4LundStringFragmentation, and G4QGSMFragmentation.
FindParticle()
G4ParticleDefinition * G4VLongitudinalStringDecay::FindParticle (G4int Encoding) protected
Definition at line 249 of file G4VLongitudinalStringDecay.cc.
Referenced by CreatePartonPair(), G4LundStringFragmentation::Diquark_AntiDiquark_belowThreshold_lastSplitting(), G4QGSMFragmentation::DiQuarkSplitup(), G4LundStringFragmentation::DiQuarkSplitup(), and FragmentationMass().
FragmentationMass()
G4double G4VLongitudinalStringDecay::FragmentationMass (const G4FragmentingString *const string, Pcreate build = 0, pDefPair * pdefs = 0) protected
Definition at line 206 of file G4VLongitudinalStringDecay.cc.
Referenced by G4QGSMFragmentation::IsFragmentable(), and LightFragmentationTest().
FragmentString()
virtual G4KineticTrackVector* G4VLongitudinalStringDecay::FragmentString (const G4ExcitedString & theString) pure virtual
Implemented in G4LundStringFragmentation, and G4QGSMFragmentation.
Referenced by G4VKinkyStringDecay::FragmentString(), and G4ExcitedStringDecay::FragmentString().
GetClusterLoopInterrupt()
G4int G4VLongitudinalStringDecay::GetClusterLoopInterrupt () inline protected
Definition at line 166 of file G4VLongitudinalStringDecay.hh.
GetClusterMass()
G4double G4VLongitudinalStringDecay::GetClusterMass () inline protected
Definition at line 165 of file G4VLongitudinalStringDecay.hh.
GetDiquarkBreakProb()
G4double G4VLongitudinalStringDecay::GetDiquarkBreakProb () inline protected
Definition at line 163 of file G4VLongitudinalStringDecay.hh.
GetDiquarkSuppress()
G4double G4VLongitudinalStringDecay::GetDiquarkSuppress () inline protected
Definition at line 162 of file G4VLongitudinalStringDecay.hh.
Referenced by G4QGSMFragmentation::Splitup(), and G4LundStringFragmentation::Splitup().
GetLightConeZ()
virtual G4double G4VLongitudinalStringDecay::GetLightConeZ (G4double zmin, G4double zmax, G4int PartonEncoding, G4ParticleDefinition * pHadron, G4double Px, G4double Py) protected pure virtual
Implemented in G4LundStringFragmentation, and G4QGSMFragmentation.
GetMassCut()
G4double G4VLongitudinalStringDecay::GetMassCut () protected
Definition at line 141 of file G4VLongitudinalStringDecay.cc.
Referenced by G4LundStringFragmentation::FragmentString().
GetStrangeSuppress()
G4double G4VLongitudinalStringDecay::GetStrangeSuppress () inline protected
Definition at line 164 of file G4VLongitudinalStringDecay.hh.
Referenced by G4QGSMFragmentation::DiQuarkSplitup(), G4LundStringFragmentation::DiQuarkSplitup(), and G4LundStringFragmentation::Splitup().
GetStringTensionParameter()
G4double G4VLongitudinalStringDecay::GetStringTensionParameter () inline protected
Definition at line 168 of file G4VLongitudinalStringDecay.hh.
Referenced by CalculateHadronTimePosition().
IsFragmentable()
virtual G4bool G4VLongitudinalStringDecay::IsFragmentable (const G4FragmentingString *const string) protected pure virtual
Implemented in G4LundStringFragmentation, and G4QGSMFragmentation.
LightFragmentationTest()
G4KineticTrackVector * G4VLongitudinalStringDecay::LightFragmentationTest (const G4ExcitedString *const theString) protected
Definition at line 146 of file G4VLongitudinalStringDecay.cc.
Referenced by G4QGSMFragmentation::FragmentString(), and G4LundStringFragmentation::FragmentString().
operator!=()
int G4VLongitudinalStringDecay::operator!= (const G4VLongitudinalStringDecay & right) const private
Definition at line 131 of file G4VLongitudinalStringDecay.cc.
operator=()
const G4VLongitudinalStringDecay& G4VLongitudinalStringDecay::operator= (const G4VLongitudinalStringDecay & right) private
operator==()
int G4VLongitudinalStringDecay::operator== (const G4VLongitudinalStringDecay & right) const private
Definition at line 123 of file G4VLongitudinalStringDecay.cc.
QuarkSplitup()
G4ParticleDefinition * G4VLongitudinalStringDecay::QuarkSplitup (G4ParticleDefinition * decay, G4ParticleDefinition *& created) protected
Definition at line 284 of file G4VLongitudinalStringDecay.cc.
Referenced by G4QGSMFragmentation::Splitup(), and G4LundStringFragmentation::Splitup().
Sample4Momentum()
virtual void G4VLongitudinalStringDecay::Sample4Momentum (G4LorentzVector * Mom, G4double Mass, G4LorentzVector * AntiMom, G4double AntiMass, G4double InitialMass) protected pure virtual
Implemented in G4LundStringFragmentation, and G4QGSMFragmentation.
Referenced by LightFragmentationTest().
SampleQuarkFlavor()
G4int G4VLongitudinalStringDecay::SampleQuarkFlavor (void)
Definition at line 297 of file G4VLongitudinalStringDecay.cc.
Referenced by CreatePartonPair(), and G4VKinkyStringDecay::FragmentString().
SampleQuarkPt()
G4ThreeVector G4VLongitudinalStringDecay::SampleQuarkPt (G4double ptMax = -1.)
Definition at line 326 of file G4VLongitudinalStringDecay.cc.
Referenced by G4VKinkyStringDecay::FragmentString(), G4LundStringFragmentation::Sample4Momentum(), and G4QGSMFragmentation::SplitEandP().
SetDiquarkBreakProbability()
void G4VLongitudinalStringDecay::SetDiquarkBreakProbability (G4double aValue)
Definition at line 394 of file G4VLongitudinalStringDecay.cc.
Referenced by G4LundStringFragmentation::G4LundStringFragmentation(), and G4QGSMFragmentation::G4QGSMFragmentation().
SetDiquarkSuppression()
void G4VLongitudinalStringDecay::SetDiquarkSuppression (G4double aValue)
Definition at line 387 of file G4VLongitudinalStringDecay.cc.
Referenced by G4LundStringFragmentation::G4LundStringFragmentation(), G4QGSMFragmentation::G4QGSMFragmentation(), G4QGSMFragmentation::Splitup(), and G4LundStringFragmentation::Splitup().
SetMassCut()
void G4VLongitudinalStringDecay::SetMassCut (G4double aValue) protected virtual
Definition at line 140 of file G4VLongitudinalStringDecay.cc.
Referenced by G4LundStringFragmentation::FragmentString(), and G4LundStringFragmentation::G4LundStringFragmentation().
SetScalarMesonMixings()
void G4VLongitudinalStringDecay::SetScalarMesonMixings (std::vector< G4double > aVector)
Definition at line 431 of file G4VLongitudinalStringDecay.cc.
SetSigmaTransverseMomentum()
void G4VLongitudinalStringDecay::SetSigmaTransverseMomentum (G4double aQT)
Definition at line 369 of file G4VLongitudinalStringDecay.cc.
SetSpinThreeHalfBarionProbability()
void G4VLongitudinalStringDecay::SetSpinThreeHalfBarionProbability (G4double aValue)
Definition at line 418 of file G4VLongitudinalStringDecay.cc.
Referenced by G4LundStringFragmentation::G4LundStringFragmentation(), and G4QGSMFragmentation::G4QGSMFragmentation().
SetStrangenessSuppression()
void G4VLongitudinalStringDecay::SetStrangenessSuppression (G4double aValue)
Definition at line 380 of file G4VLongitudinalStringDecay.cc.
Referenced by G4QGSMFragmentation::DiQuarkSplitup(), G4LundStringFragmentation::G4LundStringFragmentation(), G4QGSMFragmentation::G4QGSMFragmentation(), and G4LundStringFragmentation::Splitup().
SetStringTensionParameter()
void G4VLongitudinalStringDecay::SetStringTensionParameter (G4double aValue)
Definition at line 470 of file G4VLongitudinalStringDecay.cc.
Referenced by G4LundStringFragmentation::G4LundStringFragmentation().
SetVectorMesonMixings()
void G4VLongitudinalStringDecay::SetVectorMesonMixings (std::vector< G4double > aVector)
Definition at line 451 of file G4VLongitudinalStringDecay.cc.
Referenced by G4LundStringFragmentation::G4LundStringFragmentation(), and G4QGSMFragmentation::G4QGSMFragmentation().
SetVectorMesonProbability()
void G4VLongitudinalStringDecay::SetVectorMesonProbability (G4double aValue)
Definition at line 405 of file G4VLongitudinalStringDecay.cc.
Referenced by G4LundStringFragmentation::G4LundStringFragmentation(), and G4QGSMFragmentation::G4QGSMFragmentation().
SplitEandP()
virtual G4LorentzVector* G4VLongitudinalStringDecay::SplitEandP (G4ParticleDefinition * pHadron, G4FragmentingString * string, G4FragmentingString * newString) protected pure virtual
Implemented in G4LundStringFragmentation, and G4QGSMFragmentation.
SplitLast()
virtual G4bool G4VLongitudinalStringDecay::SplitLast (G4FragmentingString * string, G4KineticTrackVector * LeftVector, G4KineticTrackVector * RightVector) protected pure virtual
Implemented in G4LundStringFragmentation, and G4QGSMFragmentation.
Splitup()
virtual G4KineticTrack* G4VLongitudinalStringDecay::Splitup (G4FragmentingString * string, G4FragmentingString *& newString) protected pure virtual
Implemented in G4LundStringFragmentation, and G4QGSMFragmentation.
StopFragmenting()
virtual G4bool G4VLongitudinalStringDecay::StopFragmenting (const G4FragmentingString *const string) protected pure virtual
Implemented in G4LundStringFragmentation, and G4QGSMFragmentation.
Field Documentation
ClusterLoopInterrupt
G4int G4VLongitudinalStringDecay::ClusterLoopInterrupt protected
Definition at line 180 of file G4VLongitudinalStringDecay.hh.
Referenced by G4LundStringFragmentation::Diquark_AntiDiquark_belowThreshold_lastSplitting(), G4VLongitudinalStringDecay(), GetClusterLoopInterrupt(), and G4QGSMFragmentation::SplitLast().
ClusterMass
G4double G4VLongitudinalStringDecay::ClusterMass protected
Definition at line 173 of file G4VLongitudinalStringDecay.hh.
Referenced by G4VLongitudinalStringDecay(), and GetClusterMass().
DiquarkBreakProb
G4double G4VLongitudinalStringDecay::DiquarkBreakProb protected
Definition at line 176 of file G4VLongitudinalStringDecay.hh.
Referenced by G4QGSMFragmentation::DiQuarkSplitup(), G4LundStringFragmentation::DiQuarkSplitup(), G4VLongitudinalStringDecay(), GetDiquarkBreakProb(), and SetDiquarkBreakProbability().
DiquarkSuppress
G4double G4VLongitudinalStringDecay::DiquarkSuppress protected
Definition at line 175 of file G4VLongitudinalStringDecay.hh.
Referenced by CreatePartonPair(), G4VLongitudinalStringDecay(), GetDiquarkSuppress(), and SetDiquarkSuppression().
hadronizer
G4HadronBuilder* G4VLongitudinalStringDecay::hadronizer protected
Definition at line 181 of file G4VLongitudinalStringDecay.hh.
Referenced by G4LundStringFragmentation::Diquark_AntiDiquark_belowThreshold_lastSplitting(), G4QGSMFragmentation::DiQuarkSplitup(), G4LundStringFragmentation::DiQuarkSplitup(), FragmentationMass(), G4VLongitudinalStringDecay(), QuarkSplitup(), SetScalarMesonMixings(), SetSpinThreeHalfBarionProbability(), SetVectorMesonMixings(), SetVectorMesonProbability(), G4QGSMFragmentation::SplitLast(), and ~G4VLongitudinalStringDecay().
Kappa
G4double G4VLongitudinalStringDecay::Kappa protected
Definition at line 190 of file G4VLongitudinalStringDecay.hh.
Referenced by G4VLongitudinalStringDecay(), and SetStringTensionParameter().
MassCut
G4double G4VLongitudinalStringDecay::MassCut protected
Definition at line 168 of file G4VLongitudinalStringDecay.hh.
Referenced by G4VLongitudinalStringDecay(), GetMassCut(), G4QGSMFragmentation::IsFragmentable(), LightFragmentationTest(), and SetMassCut().
PastInitPhase
G4bool G4VLongitudinalStringDecay::PastInitPhase protected
Definition at line 188 of file G4VLongitudinalStringDecay.hh.
Referenced by G4QGSMFragmentation::FragmentString(), G4LundStringFragmentation::FragmentString(), G4VLongitudinalStringDecay(), SetDiquarkBreakProbability(), SetScalarMesonMixings(), SetSigmaTransverseMomentum(), SetSpinThreeHalfBarionProbability(), SetVectorMesonMixings(), and SetVectorMesonProbability().
pspin_barion
G4double G4VLongitudinalStringDecay::pspin_barion protected
Definition at line 184 of file G4VLongitudinalStringDecay.hh.
Referenced by G4LundStringFragmentation::G4LundStringFragmentation(), G4QGSMFragmentation::G4QGSMFragmentation(), G4VLongitudinalStringDecay(), G4LundStringFragmentation::SetMinMasses(), SetScalarMesonMixings(), SetSpinThreeHalfBarionProbability(), SetVectorMesonMixings(), and SetVectorMesonProbability().
pspin_meson
G4double G4VLongitudinalStringDecay::pspin_meson protected
Definition at line 183 of file G4VLongitudinalStringDecay.hh.
Referenced by G4LundStringFragmentation::G4LundStringFragmentation(), G4QGSMFragmentation::G4QGSMFragmentation(), G4VLongitudinalStringDecay(), G4LundStringFragmentation::SetMinMasses(), SetScalarMesonMixings(), SetSpinThreeHalfBarionProbability(), SetVectorMesonMixings(), and SetVectorMesonProbability().
scalarMesonMix
std::vector<G4double> G4VLongitudinalStringDecay::scalarMesonMix protected
Definition at line 186 of file G4VLongitudinalStringDecay.hh.
Referenced by G4VLongitudinalStringDecay(), G4LundStringFragmentation::SetMinMasses(), SetScalarMesonMixings(), SetSpinThreeHalfBarionProbability(), SetVectorMesonMixings(), and SetVectorMesonProbability().
SigmaQT
G4double G4VLongitudinalStringDecay::SigmaQT protected
Definition at line 174 of file G4VLongitudinalStringDecay.hh.
Referenced by G4LundStringFragmentation::G4LundStringFragmentation(), G4VLongitudinalStringDecay(), G4LundStringFragmentation::Sample4Momentum(), SampleQuarkPt(), and SetSigmaTransverseMomentum().
SmoothParam
G4double G4VLongitudinalStringDecay::SmoothParam protected
Definition at line 177 of file G4VLongitudinalStringDecay.hh.
Referenced by G4VLongitudinalStringDecay().
StrangeSuppress
G4double G4VLongitudinalStringDecay::StrangeSuppress protected
Definition at line 178 of file G4VLongitudinalStringDecay.hh.
Referenced by G4LundStringFragmentation::DiQuarkSplitup(), G4VLongitudinalStringDecay(), GetStrangeSuppress(), SampleQuarkFlavor(), and SetStrangenessSuppression().
StringLoopInterrupt
G4int G4VLongitudinalStringDecay::StringLoopInterrupt protected
Definition at line 179 of file G4VLongitudinalStringDecay.hh.
Referenced by G4QGSMFragmentation::FragmentString(), G4VLongitudinalStringDecay(), G4LundStringFragmentation::Loop_toFragmentString(), G4QGSMFragmentation::SplitEandP(), and G4LundStringFragmentation::SplitEandP().
vectorMesonMix
std::vector<G4double> G4VLongitudinalStringDecay::vectorMesonMix protected
Definition at line 185 of file G4VLongitudinalStringDecay.hh.
Referenced by G4LundStringFragmentation::G4LundStringFragmentation(), G4QGSMFragmentation::G4QGSMFragmentation(), G4VLongitudinalStringDecay(), G4LundStringFragmentation::SetMinMasses(), SetScalarMesonMixings(), SetSpinThreeHalfBarionProbability(), SetVectorMesonMixings(), and SetVectorMesonProbability().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/parton_string/hadronization/include/G4VLongitudinalStringDecay.hh
source/processes/hadronic/models/parton_string/hadronization/src/G4VLongitudinalStringDecay.cc