Geant4: G4KineticTrack Class Reference
G4KineticTrack Class Reference
#include <G4KineticTrack.hh>
Public Types
enum CascadeState {
undefined, outside, going_in, inside,
going_out, gone_out, captured, miss_nucleus
}
Public Member Functions
G4KineticTrack ()
G4KineticTrack (const G4KineticTrack &right)
G4KineticTrack (const G4ParticleDefinition *aDefinition, G4double aFormationTime, const G4ThreeVector &aPosition, const G4LorentzVector &a4Momentum)
G4KineticTrack (G4Nucleon *nucleon, const G4ThreeVector &aPosition, const G4LorentzVector &a4Momentum)
~G4KineticTrack ()
G4KineticTrack & operator= (const G4KineticTrack &right)
G4int operator== (const G4KineticTrack &right) const
G4int operator!= (const G4KineticTrack &right) const
const G4ParticleDefinition * GetDefinition () const
void SetDefinition (const G4ParticleDefinition *aDefinition)
G4double GetFormationTime () const
void SetFormationTime (G4double aFormationTime)
const G4ThreeVector & GetPosition () const
void SetPosition (const G4ThreeVector aPosition)
const G4LorentzVector & Get4Momentum () const
void Set4Momentum (const G4LorentzVector &a4Momentum)
void Update4Momentum (G4double aEnergy)
void Update4Momentum (const G4ThreeVector &aMomentum)
void SetTrackingMomentum (const G4LorentzVector &a4Momentum)
void UpdateTrackingMomentum (G4double aEnergy)
void UpdateTrackingMomentum (const G4ThreeVector &aMomentum)
const G4LorentzVector & GetTrackingMomentum () const
G4double SampleResidualLifetime ()
void Hit ()
void SetNucleon (G4Nucleon *aN)
G4bool IsParticipant () const
G4KineticTrackVector * Decay ()
G4double * GetActualWidth () const
G4double GetActualMass () const
G4int GetnChannels () const
CascadeState SetState (const CascadeState new_state)
CascadeState GetState () const
void SetProjectilePotential (const G4double aPotential)
G4double GetProjectilePotential () const
G4double BrWig (const G4double Gamma, const G4double rmass, const G4double mass) const
Public Member Functions inherited from G4VKineticNucleon
G4VKineticNucleon ()
G4VKineticNucleon (const G4VKineticNucleon &right)
virtual ~G4VKineticNucleon ()
const G4VKineticNucleon & operator= (const G4VKineticNucleon &right)
int operator== (const G4VKineticNucleon &right) const
int operator!= (const G4VKineticNucleon &right) const
Private Member Functions
void SetnChannels (const G4int aChannel)
void SetActualWidth (G4double *anActualWidth)
G4double EvaluateTotalActualWidth ()
G4double EvaluateCMMomentum (const G4double mass, const G4double *m_ij) const
G4double IntegrateCMMomentum (const G4double lowerLimit) const
G4double IntegrateCMMomentum (const G4double lowerLimit, const G4double polemass) const
G4double IntegrateCMMomentum2 () const
G4double IntegrandFunction1 (G4double xmass) const
G4double IntegrandFunction2 (G4double xmass) const
G4double IntegrandFunction3 (G4double xmass) const
G4double IntegrandFunction4 (G4double xmass) const
Private Attributes
const G4ParticleDefinition * theDefinition
G4double theFormationTime
G4ThreeVector thePosition
G4LorentzVector the4Momentum
G4LorentzVector theFermi3Momentum
G4LorentzVector theTotal4Momentum
G4Nucleon * theNucleon
G4int nChannels
G4double theActualMass
G4double * theActualWidth
G4double * theDaughterMass
G4double * theDaughterWidth
CascadeState theStateToNucleus
G4double theProjectilePotential
Detailed Description
Definition at line 56 of file G4KineticTrack.hh.
Member Enumeration Documentation
CascadeState
enum G4KineticTrack::CascadeState
Enumerator
undefined
outside
going_in
inside
going_out
gone_out
captured
miss_nucleus
Definition at line 118 of file G4KineticTrack.hh.
Constructor & Destructor Documentation
G4KineticTrack() [1/4]
G4KineticTrack::G4KineticTrack ()
Definition at line 67 of file G4KineticTrack.cc.
Referenced by IntegrandFunction4(), IntegrateCMMomentum(), and IntegrateCMMomentum2().
G4KineticTrack() [2/4]
G4KineticTrack::G4KineticTrack (const G4KineticTrack & right)
Definition at line 100 of file G4KineticTrack.cc.
G4KineticTrack() [3/4]
G4KineticTrack::G4KineticTrack (const G4ParticleDefinition * aDefinition, G4double aFormationTime, const G4ThreeVector & aPosition, const G4LorentzVector & a4Momentum)
Definition at line 138 of file G4KineticTrack.cc.
G4KineticTrack() [4/4]
G4KineticTrack::G4KineticTrack (G4Nucleon * nucleon, const G4ThreeVector & aPosition, const G4LorentzVector & a4Momentum)
Definition at line 416 of file G4KineticTrack.cc.
~G4KineticTrack()
G4KineticTrack::~G4KineticTrack ()
Definition at line 438 of file G4KineticTrack.cc.
Member Function Documentation
BrWig()
G4double G4KineticTrack::BrWig (const G4double Gamma, const G4double rmass, const G4double mass) const inline
Definition at line 378 of file G4KineticTrack.hh.
Referenced by IntegrandFunction1(), IntegrandFunction2(), IntegrandFunction3(), and IntegrandFunction4().
Decay()
G4KineticTrackVector * G4KineticTrack::Decay () virtual
Reimplemented from G4VKineticNucleon.
Definition at line 486 of file G4KineticTrack.cc.
Referenced by G4LMsdGenerator::ApplyYourself(), G4QMDCollision::CalKinematicsOfBinaryCollisions(), G4DecayKineticTracks::Decay(), and G4BCDecay::GetFinalState().
EvaluateCMMomentum()
G4double G4KineticTrack::EvaluateCMMomentum (const G4double mass, const G4double * m_ij) const inline private
Definition at line 364 of file G4KineticTrack.hh.
Referenced by G4KineticTrack().
EvaluateTotalActualWidth()
G4double G4KineticTrack::EvaluateTotalActualWidth () inline private
Definition at line 345 of file G4KineticTrack.hh.
Referenced by Decay(), and SampleResidualLifetime().
Get4Momentum()
const G4LorentzVector & G4KineticTrack::Get4Momentum () const inline virtual
Implements G4VKineticNucleon.
Definition at line 239 of file G4KineticTrack.hh.
Referenced by G4MesonAbsorption::AbsorptionCrossSection(), G4CollisionManager::AddCollision(), G4BinaryCascade::ApplyCollision(), G4KineticTrackVector::Boost(), G4KineticTrackVector::BoostBeam(), G4RKFieldIntegrator::CalculateTotalEnergy(), G4BinaryCascade::Capture(), G4BinaryCascade::CorrectShortlivedPrimaryForFermi(), G4XpimNTotal::CrossSection(), G4XpipNTotal::CrossSection(), G4XNNTotalLowE::CrossSection(), G4XNNElasticLowE::CrossSection(), G4CollisionNN::CrossSection(), G4XResonance::CrossSection(), G4XAnnihilationChannel::CrossSection(), G4XMesonBaryonElastic::CrossSection(), G4CrossSectionPatch::CrossSection(), G4XnpTotalLowE::CrossSection(), G4CrossSectionComposite::CrossSection(), G4XnpElasticLowE::CrossSection(), G4CrossSectionBuffer::CrossSection(), G4XPDGElastic::CrossSection(), G4XPDGTotal::CrossSection(), G4BinaryCascade::DebugApplyCollision(), Decay(), G4VXResonance::DetailedBalance(), G4BinaryCascade::FillVoidNucleusProducts(), G4VElasticCollision::FinalState(), G4VScatteringCollision::FinalState(), G4VAnnihilationCollision::FinalState(), G4BinaryCascade::FindLateParticleCollision(), G4Absorber::FindProducts(), G4QGSMFragmentation::FragmentString(), G4ExcitedString::Get4Momentum(), G4MesonAbsorption::GetFinalState(), G4MesonAbsorption::GetTimeToAbsorption(), G4Scatterer::GetTimeToInteraction(), G4RKFieldIntegrator::Integrate(), G4BinaryLightIonReaction::Interact(), G4LundStringFragmentation::Loop_toFragmentString(), G4ExcitedString::LorentzRotate(), G4VCrossSectionSource::PrintAll(), G4BinaryCascade::PrintKTVector(), G4IntraNucleiCascader::processSecondary(), G4BinaryCascade::ProductsAddFinalState(), G4DecayStrongResonances::Propagate(), G4CascadeInterface::Propagate(), G4BinaryCascade::Propagate1H1(), G4IntraNucleiCascader::releaseSecondary(), G4Scatterer::Scatter(), G4CrossSectionPatch::Transition(), G4XAnnihilationChannel::VariablePartialWidth(), G4XAnnihilationChannel::VariableWidth(), and G4Absorber::WillBeAbsorbed().
GetActualMass()
G4double G4KineticTrack::GetActualMass () const inline
Definition at line 318 of file G4KineticTrack.hh.
Referenced by G4BinaryCascade::Capture(), G4CollisionNN::CrossSection(), Decay(), G4RKPropagation::FieldTransport(), G4VElasticCollision::FinalState(), G4VScatteringCollision::FinalState(), G4KineticTrack(), G4MesonAbsorption::GetTimeToAbsorption(), G4Scatterer::GetTimeToInteraction(), G4RKPropagation::Transport(), and G4Absorber::WillBeAbsorbed().
GetActualWidth()
G4double * G4KineticTrack::GetActualWidth () const inline
Definition at line 333 of file G4KineticTrack.hh.
GetDefinition()
const G4ParticleDefinition * G4KineticTrack::GetDefinition () const inline virtual
Implements G4VKineticNucleon.
Definition at line 209 of file G4KineticTrack.hh.
Referenced by G4MesonAbsorption::AbsorptionCrossSection(), G4CollisionManager::AddCollision(), G4BinaryCascade::ApplyCollision(), G4KineticTrackVector::BoostBeam(), G4CollisionComposite::BufferedCrossSection(), G4RKFieldIntegrator::CalculateTotalEnergy(), G4BinaryCascade::Capture(), G4BinaryCascade::CorrectShortlivedPrimaryForFermi(), G4XAqmTotal::CrossSection(), G4CollisionNN::CrossSection(), G4XResonance::CrossSection(), G4XAnnihilationChannel::CrossSection(), G4XnpElasticLowE::CrossSection(), G4XnpTotalLowE::CrossSection(), G4CollisionComposite::CrossSection(), G4XPDGElastic::CrossSection(), G4XPDGTotal::CrossSection(), G4BinaryCascade::DebugApplyCollision(), G4BinaryCascade::DebugApplyCollisionFail(), G4DecayKineticTracks::Decay(), Decay(), G4VXResonance::DegeneracyFactor(), G4VXResonance::DetailedBalance(), G4RKPropagation::FieldTransport(), G4BinaryCascade::FillVoidNucleusProducts(), G4VElasticCollision::FinalState(), G4VScatteringCollision::FinalState(), G4Absorber::FindAbsorbers(), G4MesonAbsorption::FindAndFillCluster(), G4VCrossSectionSource::FindKeyParticle(), G4BinaryCascade::FindLateParticleCollision(), G4VCrossSectionSource::FindLightParticle(), G4Absorber::FindProducts(), G4QGSMFragmentation::FragmentString(), G4ExcitedStringDecay::FragmentStrings(), G4BCDecay::GetCollisions(), G4MesonAbsorption::GetFinalState(), G4ParticleTypeConverter::GetGenericType(), G4ConcreteMesonBaryonToResonance::GetOutgoingParticle(), G4MesonAbsorption::GetTimeToAbsorption(), G4Scatterer::GetTimeToInteraction(), G4GeneralNNCollision::IsInCharge(), G4CollisionnpElastic::IsInCharge(), G4CollisionMesonBaryonElastic::IsInCharge(), G4CollisionNNElastic::IsInCharge(), G4ConcreteNNTwoBodyResonance::IsInCharge(), G4VXResonance::IsospinCorrection(), G4LundStringFragmentation::Loop_toFragmentString(), G4XAnnihilationChannel::NormalizedClebsch(), G4CollisionManager::Print(), G4CollisionInitialState::Print(), G4BinaryCascade::PrintKTVector(), G4IntraNucleiCascader::processSecondary(), G4BinaryCascade::ProductsAddFinalState(), G4DecayStrongResonances::Propagate(), G4CascadeInterface::Propagate(), G4BinaryCascade::Propagate1H1(), G4IntraNucleiCascader::releaseSecondary(), G4Scatterer::Scatter(), G4BinaryCascade::StepParticlesOut(), G4RKPropagation::Transport(), and G4Absorber::WillBeAbsorbed().
GetFormationTime()
G4double G4KineticTrack::GetFormationTime () const inline
Definition at line 219 of file G4KineticTrack.hh.
Referenced by G4XMesonBaryonElastic::CrossSection(), G4QGSMFragmentation::FragmentString(), G4ExcitedString::G4ExcitedString(), G4BCLateParticle::GetCollisions(), G4LundStringFragmentation::Loop_toFragmentString(), and G4CascadeInterface::Propagate().
GetnChannels()
G4int G4KineticTrack::GetnChannels () const inline
Definition at line 323 of file G4KineticTrack.hh.
GetPosition()
const G4ThreeVector & G4KineticTrack::GetPosition (void) const inline virtual
Implements G4VKineticNucleon.
Definition at line 229 of file G4KineticTrack.hh.
Referenced by G4RKFieldIntegrator::CalculateTotalEnergy(), G4BinaryCascade::Capture(), G4BinaryCascade::CorrectShortlivedPrimaryForFermi(), G4XMesonBaryonElastic::CrossSection(), G4BinaryCascade::DebugApplyCollision(), Decay(), G4RKPropagation::FieldTransport(), G4VAnnihilationCollision::FinalState(), G4VScatteringCollision::FinalState(), G4Absorber::FindAbsorbers(), G4MesonAbsorption::FindAndFillCluster(), G4Absorber::FindProducts(), G4QGSMFragmentation::FragmentString(), G4RKPropagation::FreeTransport(), G4ExcitedString::G4ExcitedString(), G4RKPropagation::GetSphereIntersectionTimes(), G4MesonAbsorption::GetTimeToAbsorption(), G4Scatterer::GetTimeToInteraction(), G4RKFieldIntegrator::Integrate(), G4LundStringFragmentation::Loop_toFragmentString(), G4BinaryCascade::PrintKTVector(), G4IntraNucleiCascader::processSecondary(), G4CascadeInterface::Propagate(), G4KineticTrackVector::Shift(), and G4RKPropagation::Transport().
GetProjectilePotential()
G4double G4KineticTrack::GetProjectilePotential () const inline
Definition at line 420 of file G4KineticTrack.hh.
Referenced by G4RKPropagation::Transport().
GetState()
G4KineticTrack::CascadeState G4KineticTrack::GetState () const inline
Definition at line 401 of file G4KineticTrack.hh.
Referenced by G4BinaryCascade::Absorb(), G4BinaryCascade::ApplyCollision(), G4BinaryCascade::Capture(), G4BinaryCascade::CorrectShortlivedPrimaryForFermi(), G4BinaryCascade::FindLateParticleCollision(), G4BinaryCascade::PrintKTVector(), G4BinaryCascade::StepParticlesOut(), and G4RKPropagation::Transport().
GetTrackingMomentum()
const G4LorentzVector & G4KineticTrack::GetTrackingMomentum () const inline
Definition at line 244 of file G4KineticTrack.hh.
Referenced by G4BinaryCascade::ApplyCollision(), G4RKPropagation::FieldTransport(), G4RKPropagation::FreeTransport(), G4RKPropagation::GetSphereIntersectionTimes(), G4MesonAbsorption::GetTimeToAbsorption(), G4Scatterer::GetTimeToInteraction(), G4BinaryCascade::PrintKTVector(), G4BinaryCascade::StepParticlesOut(), and G4RKPropagation::Transport().
Hit()
void G4KineticTrack::Hit () inline
Definition at line 385 of file G4KineticTrack.hh.
Referenced by G4BinaryCascade::ApplyCollision(), and G4BinaryCascade::Capture().
IntegrandFunction1()
G4double G4KineticTrack::IntegrandFunction1 (G4double xmass) const private
Definition at line 744 of file G4KineticTrack.cc.
Referenced by IntegrateCMMomentum().
IntegrandFunction2()
G4double G4KineticTrack::IntegrandFunction2 (G4double xmass) const private
Definition at line 758 of file G4KineticTrack.cc.
Referenced by IntegrateCMMomentum().
IntegrandFunction3()
G4double G4KineticTrack::IntegrandFunction3 (G4double xmass) const private
Definition at line 771 of file G4KineticTrack.cc.
Referenced by IntegrandFunction4().
IntegrandFunction4()
G4double G4KineticTrack::IntegrandFunction4 (G4double xmass) const private
Definition at line 785 of file G4KineticTrack.cc.
Referenced by IntegrateCMMomentum2().
IntegrateCMMomentum() [1/2]
G4double G4KineticTrack::IntegrateCMMomentum (const G4double lowerLimit) const private
Definition at line 805 of file G4KineticTrack.cc.
Referenced by G4KineticTrack().
IntegrateCMMomentum() [2/2]
G4double G4KineticTrack::IntegrateCMMomentum (const G4double lowerLimit, const G4double polemass) const private
Definition at line 818 of file G4KineticTrack.cc.
IntegrateCMMomentum2()
G4double G4KineticTrack::IntegrateCMMomentum2 () const private
Definition at line 832 of file G4KineticTrack.cc.
Referenced by G4KineticTrack().
IsParticipant()
G4bool G4KineticTrack::IsParticipant () const inline
Definition at line 394 of file G4KineticTrack.hh.
Referenced by G4BinaryCascade::PrintKTVector(), and G4BinaryCascade::ProductsAddFinalState().
operator!=()
G4int G4KineticTrack::operator!= (const G4KineticTrack & right) const
Definition at line 479 of file G4KineticTrack.cc.
operator=()
G4KineticTrack & G4KineticTrack::operator= (const G4KineticTrack & right)
Definition at line 447 of file G4KineticTrack.cc.
operator==()
G4int G4KineticTrack::operator== (const G4KineticTrack & right) const
Definition at line 472 of file G4KineticTrack.cc.
SampleResidualLifetime()
G4double G4KineticTrack::SampleResidualLifetime () inline
Definition at line 356 of file G4KineticTrack.hh.
Referenced by G4BCDecay::GetCollisions().
Set4Momentum()
void G4KineticTrack::Set4Momentum (const G4LorentzVector & a4Momentum) inline
Definition at line 249 of file G4KineticTrack.hh.
Referenced by G4BinaryCascade::ApplyCollision(), G4KineticTrackVector::Boost(), G4KineticTrackVector::BoostBeam(), G4CollisionNN::CrossSection(), G4VElasticCollision::FinalState(), G4QGSMFragmentation::FragmentString(), G4KineticTrack(), G4LundStringFragmentation::Loop_toFragmentString(), G4ExcitedString::LorentzRotate(), G4ExcitedString::TransformToCenterOfMass(), and Update4Momentum().
SetActualWidth()
void G4KineticTrack::SetActualWidth (G4double * anActualWidth) inline private
Definition at line 338 of file G4KineticTrack.hh.
SetDefinition()
void G4KineticTrack::SetDefinition (const G4ParticleDefinition * aDefinition) inline
Definition at line 214 of file G4KineticTrack.hh.
SetFormationTime()
void G4KineticTrack::SetFormationTime (G4double aFormationTime) inline
Definition at line 224 of file G4KineticTrack.hh.
Referenced by G4QGSMFragmentation::FragmentString(), and G4LundStringFragmentation::Loop_toFragmentString().
SetnChannels()
void G4KineticTrack::SetnChannels (const G4int aChannel) inline private
Definition at line 328 of file G4KineticTrack.hh.
SetNucleon()
void G4KineticTrack::SetNucleon (G4Nucleon * aN) inline
Definition at line 105 of file G4KineticTrack.hh.
Referenced by G4BinaryCascade::BuildTargetList().
SetPosition()
void G4KineticTrack::SetPosition (const G4ThreeVector aPosition) inline
Definition at line 234 of file G4KineticTrack.hh.
Referenced by G4RKPropagation::FieldTransport(), G4QGSMFragmentation::FragmentString(), G4ExcitedStringDecay::FragmentStrings(), G4RKPropagation::FreeTransport(), G4RKFieldIntegrator::Integrate(), G4LundStringFragmentation::Loop_toFragmentString(), and G4KineticTrackVector::Shift().
SetProjectilePotential()
void G4KineticTrack::SetProjectilePotential (const G4double aPotential) inline
Definition at line 415 of file G4KineticTrack.hh.
Referenced by G4BinaryLightIonReaction::Interact().
SetState()
G4KineticTrack::CascadeState G4KineticTrack::SetState (const CascadeState new_state) inline
Definition at line 407 of file G4KineticTrack.hh.
Referenced by G4BinaryCascade::ApplyYourself(), G4BinaryCascade::BuildTargetList(), G4BinaryCascade::FindLateParticleCollision(), G4BinaryLightIonReaction::Interact(), and G4RKPropagation::Transport().
SetTrackingMomentum()
void G4KineticTrack::SetTrackingMomentum (const G4LorentzVector & a4Momentum) inline
Definition at line 282 of file G4KineticTrack.hh.
Referenced by G4RKPropagation::FieldTransport(), G4RKPropagation::Transport(), and UpdateTrackingMomentum().
Update4Momentum() [1/2]
void G4KineticTrack::Update4Momentum (const G4ThreeVector & aMomentum) inline
Definition at line 274 of file G4KineticTrack.hh.
Update4Momentum() [2/2]
void G4KineticTrack::Update4Momentum (G4double aEnergy) inline
Definition at line 258 of file G4KineticTrack.hh.
Referenced by G4BinaryCascade::CorrectShortlivedPrimaryForFermi().
UpdateTrackingMomentum() [1/2]
void G4KineticTrack::UpdateTrackingMomentum (const G4ThreeVector & aMomentum) inline
Definition at line 310 of file G4KineticTrack.hh.
UpdateTrackingMomentum() [2/2]
void G4KineticTrack::UpdateTrackingMomentum (G4double aEnergy) inline
Definition at line 294 of file G4KineticTrack.hh.
Field Documentation
nChannels
G4int G4KineticTrack::nChannels private
Definition at line 175 of file G4KineticTrack.hh.
Referenced by Decay(), EvaluateTotalActualWidth(), G4KineticTrack(), GetnChannels(), operator=(), and SetnChannels().
the4Momentum
G4LorentzVector G4KineticTrack::the4Momentum private
Definition at line 169 of file G4KineticTrack.hh.
Referenced by G4KineticTrack(), GetActualMass(), GetTrackingMomentum(), operator=(), SampleResidualLifetime(), Set4Momentum(), SetTrackingMomentum(), Update4Momentum(), and UpdateTrackingMomentum().
theActualMass
G4double G4KineticTrack::theActualMass private
Definition at line 177 of file G4KineticTrack.hh.
Referenced by G4KineticTrack(), IntegrandFunction1(), IntegrateCMMomentum(), and IntegrateCMMomentum2().
theActualWidth
G4double* G4KineticTrack::theActualWidth private
Definition at line 179 of file G4KineticTrack.hh.
Referenced by Decay(), EvaluateTotalActualWidth(), G4KineticTrack(), GetActualWidth(), operator=(), SetActualWidth(), and ~G4KineticTrack().
theDaughterMass
G4double* G4KineticTrack::theDaughterMass private
Definition at line 183 of file G4KineticTrack.hh.
Referenced by G4KineticTrack(), IntegrandFunction1(), IntegrandFunction2(), IntegrandFunction3(), IntegrandFunction4(), IntegrateCMMomentum(), and ~G4KineticTrack().
theDaughterWidth
G4double* G4KineticTrack::theDaughterWidth private
Definition at line 184 of file G4KineticTrack.hh.
Referenced by G4KineticTrack(), IntegrandFunction1(), IntegrandFunction2(), IntegrandFunction3(), IntegrandFunction4(), and ~G4KineticTrack().
theDefinition
const G4ParticleDefinition* G4KineticTrack::theDefinition private
Definition at line 163 of file G4KineticTrack.hh.
Referenced by Decay(), G4KineticTrack(), GetDefinition(), IntegrandFunction2(), operator=(), and SetDefinition().
theFermi3Momentum
G4LorentzVector G4KineticTrack::theFermi3Momentum private
Definition at line 170 of file G4KineticTrack.hh.
Referenced by G4KineticTrack(), operator=(), Set4Momentum(), and SetTrackingMomentum().
theFormationTime
G4double G4KineticTrack::theFormationTime private
Definition at line 165 of file G4KineticTrack.hh.
Referenced by G4KineticTrack(), GetFormationTime(), operator=(), and SetFormationTime().
theNucleon
G4Nucleon* G4KineticTrack::theNucleon private
Definition at line 173 of file G4KineticTrack.hh.
Referenced by G4KineticTrack(), Hit(), IsParticipant(), operator=(), and SetNucleon().
thePosition
G4ThreeVector G4KineticTrack::thePosition private
Definition at line 167 of file G4KineticTrack.hh.
Referenced by G4KineticTrack(), GetPosition(), and SetPosition().
theProjectilePotential
G4double G4KineticTrack::theProjectilePotential private
Definition at line 188 of file G4KineticTrack.hh.
Referenced by G4KineticTrack(), GetProjectilePotential(), and SetProjectilePotential().
theStateToNucleus
CascadeState G4KineticTrack::theStateToNucleus private
Definition at line 186 of file G4KineticTrack.hh.
Referenced by G4KineticTrack(), GetState(), operator=(), and SetState().
theTotal4Momentum
G4LorentzVector G4KineticTrack::theTotal4Momentum private
Definition at line 171 of file G4KineticTrack.hh.
Referenced by G4KineticTrack(), Get4Momentum(), operator=(), Set4Momentum(), SetTrackingMomentum(), Update4Momentum(), and UpdateTrackingMomentum().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/util/include/G4KineticTrack.hh
source/processes/hadronic/models/util/src/G4KineticTrack.cc