Geant4: G4Isotope Class Reference
G4Isotope Class Reference
#include <G4Isotope.hh>
Public Member Functions
G4Isotope (const G4String &name, G4int z, G4int n, G4double a=0., G4int m=0)
virtual ~G4Isotope ()
const G4String & GetName () const
G4int GetZ () const
G4int GetN () const
G4double GetA () const
G4int Getm () const
size_t GetIndex () const
G4bool operator== (const G4Isotope &) const
G4bool operator!= (const G4Isotope &) const
G4Isotope (__void__ &)
void SetName (const G4String &name)
Static Public Member Functions
static G4Isotope * GetIsotope (const G4String &name, G4bool warning=false)
static const G4IsotopeTable * GetIsotopeTable ()
static size_t GetNumberOfIsotopes ()
Private Member Functions
G4Isotope (G4Isotope &)
G4Isotope & operator= (const G4Isotope &)
Private Attributes
G4String fName
G4int fZ
G4int fN
G4double fA
G4int fm
size_t fIndexInTable
Static Private Attributes
static G4IsotopeTable theIsotopeTable
Friends
std::ostream & operator<< (std::ostream &, const G4Isotope *)
std::ostream & operator<< (std::ostream &, const G4Isotope &)
std::ostream & operator<< (std::ostream &, G4IsotopeTable)
Detailed Description
Definition at line 71 of file G4Isotope.hh.
Constructor & Destructor Documentation
G4Isotope() [1/3]
G4Isotope::G4Isotope (const G4String & name, G4int z, G4int n, G4double a = 0., G4int m = 0)
Definition at line 58 of file G4Isotope.cc.
~G4Isotope()
G4Isotope::~G4Isotope () virtual
Definition at line 91 of file G4Isotope.cc.
G4Isotope() [2/3]
G4Isotope::G4Isotope (__void__ &)
Definition at line 84 of file G4Isotope.cc.
G4Isotope() [3/3]
G4Isotope::G4Isotope (G4Isotope & right) private
Definition at line 98 of file G4Isotope.cc.
Member Function Documentation
GetA()
G4double G4Isotope::GetA () const inline
Definition at line 96 of file G4Isotope.hh.
Referenced by G4tgbGeometryDumper::DumpIsotope(), export_G4Isotope(), G4GDMLWriteMaterials::IsotopeWrite(), and G4tgbGeometryDumper::Same2G4Isotopes().
GetIndex()
size_t G4Isotope::GetIndex () const inline
Definition at line 110 of file G4Isotope.hh.
Referenced by export_G4Isotope().
GetIsotope()
G4Isotope * G4Isotope::GetIsotope (const G4String & name, G4bool warning = false) static
Definition at line 195 of file G4Isotope.cc.
Referenced by export_G4Isotope(), and G4GDMLReadMaterials::GetIsotope().
GetIsotopeTable()
const G4IsotopeTable * G4Isotope::GetIsotopeTable () static
Definition at line 181 of file G4Isotope.cc.
Referenced by export_G4Isotope(), and G4NistManager::~G4NistManager().
Getm()
G4int G4Isotope::Getm () const inline
Definition at line 99 of file G4Isotope.hh.
Referenced by G4LENDorBERTModel::ApplyYourself(), G4LENDModel::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4LENDFission::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4LENDModel::create_used_target_map(), G4LENDCrossSection::create_used_target_map(), G4LENDCrossSection::GetIsoCrossSection(), G4ParticleHPElementData::Init(), and G4ParticleHPChannel::Register().
GetN()
G4int G4Isotope::GetN () const inline
Definition at line 93 of file G4Isotope.hh.
Referenced by G4ParticleHPElastic::ApplyYourself(), G4ParticleHPCapture::ApplyYourself(), G4ParticleHPFission::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4FissLib::ApplyYourself(), G4ParticleHPJENDLHEData::BuildPhysicsTable(), G4Nucleus::ChooseParameters(), G4VCrossSectionDataSet::ComputeCrossSection(), G4LENDModel::create_used_target_map(), G4LENDCrossSection::create_used_target_map(), G4tgbGeometryDumper::DumpIsotope(), export_G4Isotope(), G4ParticleHPJENDLHEData::GetCrossSection(), G4CrossSectionDataStore::GetCrossSection(), G4ParticleHPElementData::Init(), G4LENDCrossSection::IsIsoApplicable(), G4GDMLWriteMaterials::IsotopeWrite(), G4ParticleHPChannel::Register(), G4tgbGeometryDumper::Same2G4Isotopes(), G4CrossSectionDataStore::SampleZandA(), G4NeutronCaptureXS::SelectIsotope(), G4NeutronInelasticXS::SelectIsotope(), G4ParticleInelasticXS::SelectIsotope(), G4VEmModel::SelectIsotopeNumber(), G4ElementSelector::SelectZandA(), and G4Nucleus::SetIsotope().
GetName()
const G4String& G4Isotope::GetName (void) const inline
Definition at line 87 of file G4Isotope.hh.
Referenced by G4GDMLWriteMaterials::ElementWrite(), export_G4Isotope(), G4tgbMaterialMgr::FindOrBuildG4Isotope(), GetIsotope(), G4tgbGeometryDumper::GetIsotopeName(), and G4GDMLWriteMaterials::IsotopeWrite().
GetNumberOfIsotopes()
size_t G4Isotope::GetNumberOfIsotopes () static
Definition at line 188 of file G4Isotope.cc.
Referenced by export_G4Isotope().
GetZ()
G4int G4Isotope::GetZ () const inline
Definition at line 90 of file G4Isotope.hh.
Referenced by G4Element::AddIsotope(), G4Nucleus::ChooseParameters(), G4LENDModel::create_used_target_map(), G4LENDCrossSection::create_used_target_map(), G4tgbGeometryDumper::DumpIsotope(), export_G4Isotope(), G4GDMLWriteMaterials::IsotopeWrite(), G4tgbGeometryDumper::Same2G4Isotopes(), and G4Nucleus::SetIsotope().
operator!=()
G4bool G4Isotope::operator!= (const G4Isotope & right) const
Definition at line 131 of file G4Isotope.cc.
operator=()
G4Isotope & G4Isotope::operator= (const G4Isotope & right) private
Definition at line 109 of file G4Isotope.cc.
operator==()
G4bool G4Isotope::operator== (const G4Isotope & right) const
Definition at line 124 of file G4Isotope.cc.
SetName()
void G4Isotope::SetName (const G4String & name) inline
Definition at line 131 of file G4Isotope.hh.
Referenced by export_G4Isotope().
Friends And Related Function Documentation
operator<< [1/3]
std::ostream& operator<< (std::ostream & flux, const G4Isotope & isotope) friend
Definition at line 158 of file G4Isotope.cc.
operator<< [2/3]
std::ostream& operator<< (std::ostream & flux, const G4Isotope * isotope) friend
Definition at line 138 of file G4Isotope.cc.
operator<< [3/3]
std::ostream& operator<< (std::ostream & flux, G4IsotopeTable IsotopeTable) friend
Definition at line 166 of file G4Isotope.cc.
Field Documentation
fA
G4double G4Isotope::fA private
Definition at line 143 of file G4Isotope.hh.
Referenced by G4Isotope(), GetA(), operator<<(), and operator=().
fIndexInTable
size_t G4Isotope::fIndexInTable private
Definition at line 149 of file G4Isotope.hh.
Referenced by G4Isotope(), GetIndex(), and ~G4Isotope().
fm
G4int G4Isotope::fm private
Definition at line 144 of file G4Isotope.hh.
Referenced by Getm(), and operator=().
fN
G4int G4Isotope::fN private
Definition at line 142 of file G4Isotope.hh.
Referenced by GetN(), operator<<(), and operator=().
fName
G4String G4Isotope::fName private
Definition at line 140 of file G4Isotope.hh.
Referenced by GetName(), operator<<(), operator=(), and SetName().
fZ
G4int G4Isotope::fZ private
Definition at line 141 of file G4Isotope.hh.
Referenced by GetZ(), operator<<(), and operator=().
theIsotopeTable
G4IsotopeTable G4Isotope::theIsotopeTable static private
Definition at line 147 of file G4Isotope.hh.
Referenced by G4Isotope(), GetIsotope(), GetIsotopeTable(), GetNumberOfIsotopes(), and ~G4Isotope().
The documentation for this class was generated from the following files:
source/materials/include/G4Isotope.hh
source/materials/src/G4Isotope.cc