Geant4: G4AdjointComptonModel Class Reference
G4AdjointComptonModel Class Reference
#include <G4AdjointComptonModel.hh>
Public Member Functions
G4AdjointComptonModel ()
~G4AdjointComptonModel ()
virtual void SampleSecondaries (const G4Track &aTrack, G4bool IsScatProjToProjCase, G4ParticleChange *fParticleChange)
void RapidSampleSecondaries (const G4Track &aTrack, G4bool IsScatProjToProjCase, G4ParticleChange *fParticleChange)
virtual G4double DiffCrossSectionPerAtomPrimToScatPrim (G4double kinEnergyProj, G4double kinEnergyScatProj, G4double Z, G4double A=0.)
virtual G4double DiffCrossSectionPerAtomPrimToSecond (G4double kinEnergyProj, G4double kinEnergyProd, G4double Z, G4double A=0.)
virtual G4double GetSecondAdjEnergyMaxForScatProjToProjCase (G4double PrimAdjEnergy)
virtual G4double GetSecondAdjEnergyMinForProdToProjCase (G4double PrimAdjEnergy)
virtual G4double AdjointCrossSection (const G4MaterialCutsCouple *aCouple, G4double primEnergy, G4bool IsScatProjToProjCase)
virtual G4double GetAdjointCrossSection (const G4MaterialCutsCouple *aCouple, G4double primEnergy, G4bool IsScatProjToProjCase)
void SetDirectProcess (G4VEmProcess *aProcess)
Public Member Functions inherited from G4VEmAdjointModel
G4VEmAdjointModel (const G4String &nam)
virtual ~G4VEmAdjointModel ()
virtual G4double DiffCrossSectionPerVolumePrimToSecond (const G4Material *aMaterial, G4double kinEnergyProj, G4double kinEnergyProd)
virtual G4double DiffCrossSectionPerVolumePrimToScatPrim (const G4Material *aMaterial, G4double kinEnergyProj, G4double kinEnergyScatProj)
virtual G4double GetSecondAdjEnergyMinForScatProjToProjCase (G4double PrimAdjEnergy, G4double Tcut=0)
virtual G4double GetSecondAdjEnergyMaxForProdToProjCase (G4double PrimAdjEnergy)
void DefineCurrentMaterial (const G4MaterialCutsCouple *couple)
std::vector< std::vector< double > * > ComputeAdjointCrossSectionVectorPerAtomForSecond (G4double kinEnergyProd, G4double Z, G4double A=0., G4int nbin_pro_decade=10)
std::vector< std::vector< double > * > ComputeAdjointCrossSectionVectorPerAtomForScatProj (G4double kinEnergyProd, G4double Z, G4double A=0., G4int nbin_pro_decade=10)
std::vector< std::vector< double > * > ComputeAdjointCrossSectionVectorPerVolumeForSecond (G4Material *aMaterial, G4double kinEnergyProd, G4int nbin_pro_decade=10)
std::vector< std::vector< double > * > ComputeAdjointCrossSectionVectorPerVolumeForScatProj (G4Material *aMaterial, G4double kinEnergyProd, G4int nbin_pro_decade=10)
void SetCSMatrices (std::vector< G4AdjointCSMatrix * > *Vec1CSMatrix, std::vector< G4AdjointCSMatrix * > *Vec2CSMatrix)
G4ParticleDefinition * GetAdjointEquivalentOfDirectPrimaryParticleDefinition ()
G4ParticleDefinition * GetAdjointEquivalentOfDirectSecondaryParticleDefinition ()
G4double GetHighEnergyLimit ()
G4double GetLowEnergyLimit ()
void SetHighEnergyLimit (G4double aVal)
void SetLowEnergyLimit (G4double aVal)
void DefineDirectEMModel (G4VEmModel *aModel)
void SetAdjointEquivalentOfDirectPrimaryParticleDefinition (G4ParticleDefinition *aPart)
void SetAdjointEquivalentOfDirectSecondaryParticleDefinition (G4ParticleDefinition *aPart)
void SetSecondPartOfSameType (G4bool aBool)
G4bool GetSecondPartOfSameType ()
void SetUseMatrix (G4bool aBool)
void SetUseMatrixPerElement (G4bool aBool)
void SetUseOnlyOneMatrixForAllElements (G4bool aBool)
void SetApplyCutInRange (G4bool aBool)
G4bool GetUseMatrix ()
G4bool GetUseMatrixPerElement ()
G4bool GetUseOnlyOneMatrixForAllElements ()
G4bool GetApplyCutInRange ()
G4String GetName ()
virtual void SetCSBiasingFactor (G4double aVal)
void SetCorrectWeightForPostStepInModel (G4bool aBool)
void SetAdditionalWeightCorrectionFactorForPostStepOutsideModel (G4double factor)
Private Attributes
G4VEmProcess * theDirectEMProcess
G4double G4direct_CS
Additional Inherited Members
Protected Member Functions inherited from G4VEmAdjointModel
G4double DiffCrossSectionFunction1 (G4double kinEnergyProj)
G4double DiffCrossSectionFunction2 (G4double kinEnergyProj)
G4double DiffCrossSectionPerVolumeFunctionForIntegrationOverEkinProj (G4double EkinProd)
G4double SampleAdjSecEnergyFromCSMatrix (size_t MatrixIndex, G4double prim_energy, G4bool IsScatProjToProjCase)
G4double SampleAdjSecEnergyFromCSMatrix (G4double prim_energy, G4bool IsScatProjToProjCase)
void SelectCSMatrix (G4bool IsScatProjToProjCase)
virtual G4double SampleAdjSecEnergyFromDiffCrossSectionPerAtom (G4double prim_energy, G4bool IsScatProjToProjCase)
virtual void CorrectPostStepWeight (G4ParticleChange *fParticleChange, G4double old_weight, G4double adjointPrimKinEnergy, G4double projectileKinEnergy, G4bool IsScatProjToProjCase)
Protected Attributes inherited from G4VEmAdjointModel
G4VEmModel * theDirectEMModel
G4VParticleChange * pParticleChange
const G4String name
G4int ASelectedNucleus
G4int ZSelectedNucleus
G4Material * SelectedMaterial
G4double kinEnergyProdForIntegration
G4double kinEnergyScatProjForIntegration
G4double kinEnergyProjForIntegration
std::vector< G4AdjointCSMatrix * > * pOnCSMatrixForProdToProjBackwardScattering
std::vector< G4AdjointCSMatrix * > * pOnCSMatrixForScatProjToProjBackwardScattering
std::vector< G4double > CS_Vs_ElementForScatProjToProjCase
std::vector< G4double > CS_Vs_ElementForProdToProjCase
G4double lastCS
G4double lastAdjointCSForScatProjToProjCase
G4double lastAdjointCSForProdToProjCase
G4ParticleDefinition * theAdjEquivOfDirectPrimPartDef
G4ParticleDefinition * theAdjEquivOfDirectSecondPartDef
G4ParticleDefinition * theDirectPrimaryPartDef
G4bool second_part_of_same_type
G4double preStepEnergy
G4Material * currentMaterial
G4MaterialCutsCouple * currentCouple
size_t currentMaterialIndex
size_t currentCoupleIndex
G4double currentTcutForDirectPrim
G4double currentTcutForDirectSecond
G4bool ApplyCutInRange
G4double mass_ratio_product
G4double mass_ratio_projectile
G4double HighEnergyLimit
G4double LowEnergyLimit
G4double CS_biasing_factor
G4bool UseMatrix
G4bool UseMatrixPerElement
G4bool UseOnlyOneMatrixForAllElements
size_t indexOfUsedCrossSectionMatrix
size_t model_index
G4bool correct_weight_for_post_step_in_model
G4double additional_weight_correction_factor_for_post_step_outside_model
Detailed Description
Definition at line 53 of file G4AdjointComptonModel.hh.
Constructor & Destructor Documentation
G4AdjointComptonModel()
G4AdjointComptonModel::G4AdjointComptonModel ()
Definition at line 43 of file G4AdjointComptonModel.cc.
~G4AdjointComptonModel()
G4AdjointComptonModel::~G4AdjointComptonModel ()
Definition at line 59 of file G4AdjointComptonModel.cc.
Member Function Documentation
AdjointCrossSection()
G4double G4AdjointComptonModel::AdjointCrossSection (const G4MaterialCutsCouple * aCouple, G4double primEnergy, G4bool IsScatProjToProjCase) virtual
Reimplemented from G4VEmAdjointModel.
Definition at line 377 of file G4AdjointComptonModel.cc.
Referenced by GetAdjointCrossSection().
DiffCrossSectionPerAtomPrimToScatPrim()
G4double G4AdjointComptonModel::DiffCrossSectionPerAtomPrimToScatPrim (G4double kinEnergyProj, G4double kinEnergyScatProj, G4double Z, G4double A = 0.) virtual
Reimplemented from G4VEmAdjointModel.
Definition at line 294 of file G4AdjointComptonModel.cc.
Referenced by DiffCrossSectionPerAtomPrimToSecond(), and RapidSampleSecondaries().
DiffCrossSectionPerAtomPrimToSecond()
G4double G4AdjointComptonModel::DiffCrossSectionPerAtomPrimToSecond (G4double kinEnergyProj, G4double kinEnergyProd, G4double Z, G4double A = 0.) virtual
Reimplemented from G4VEmAdjointModel.
Definition at line 279 of file G4AdjointComptonModel.cc.
GetAdjointCrossSection()
G4double G4AdjointComptonModel::GetAdjointCrossSection (const G4MaterialCutsCouple * aCouple, G4double primEnergy, G4bool IsScatProjToProjCase) virtual
Reimplemented from G4VEmAdjointModel.
Definition at line 413 of file G4AdjointComptonModel.cc.
GetSecondAdjEnergyMaxForScatProjToProjCase()
G4double G4AdjointComptonModel::GetSecondAdjEnergyMaxForScatProjToProjCase (G4double PrimAdjEnergy) virtual
Reimplemented from G4VEmAdjointModel.
Definition at line 361 of file G4AdjointComptonModel.cc.
Referenced by AdjointCrossSection(), and RapidSampleSecondaries().
GetSecondAdjEnergyMinForProdToProjCase()
G4double G4AdjointComptonModel::GetSecondAdjEnergyMinForProdToProjCase (G4double PrimAdjEnergy) virtual
Reimplemented from G4VEmAdjointModel.
Definition at line 369 of file G4AdjointComptonModel.cc.
Referenced by AdjointCrossSection(), and RapidSampleSecondaries().
RapidSampleSecondaries()
void G4AdjointComptonModel::RapidSampleSecondaries (const G4Track & aTrack, G4bool IsScatProjToProjCase, G4ParticleChange * fParticleChange)
Definition at line 155 of file G4AdjointComptonModel.cc.
Referenced by SampleSecondaries().
SampleSecondaries()
void G4AdjointComptonModel::SampleSecondaries (const G4Track & aTrack, G4bool IsScatProjToProjCase, G4ParticleChange * fParticleChange) virtual
Implements G4VEmAdjointModel.
Definition at line 63 of file G4AdjointComptonModel.cc.
SetDirectProcess()
void G4AdjointComptonModel::SetDirectProcess (G4VEmProcess * aProcess) inline
Definition at line 94 of file G4AdjointComptonModel.hh.
Referenced by G4AdjointPhysicsList::ConstructEM().
Field Documentation
G4direct_CS
G4double G4AdjointComptonModel::G4direct_CS private
Definition at line 98 of file G4AdjointComptonModel.hh.
Referenced by DiffCrossSectionPerAtomPrimToScatPrim(), G4AdjointComptonModel(), and RapidSampleSecondaries().
theDirectEMProcess
G4VEmProcess* G4AdjointComptonModel::theDirectEMProcess private
Definition at line 94 of file G4AdjointComptonModel.hh.
Referenced by RapidSampleSecondaries().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/adjoint/include/G4AdjointComptonModel.hh
source/processes/electromagnetic/adjoint/src/G4AdjointComptonModel.cc