Geant4: G4NucleonNuclearCrossSection Class Reference
G4NucleonNuclearCrossSection Class Reference
#include <G4NucleonNuclearCrossSection.hh>
Public Member Functions
G4NucleonNuclearCrossSection ()
virtual ~G4NucleonNuclearCrossSection ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *aParticle, G4int Z, const G4Material *mat=nullptr)
virtual G4double GetElementCrossSection (const G4DynamicParticle *aParticle, G4int Z, const G4Material *mat=nullptr)
virtual void CrossSectionDescription (std::ostream &) const
G4double GetElasticCrossSection (const G4DynamicParticle *aParticle, G4int Z)
G4double GetTotalXsc ()
G4double GetInelasticXsc ()
G4double GetElasticXsc ()
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsIsoApplicable (const G4DynamicParticle *, G4int Z, G4int A, const G4Element *elm=0, const G4Material *mat=0)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetIsoCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *iso=nullptr, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Static Public Member Functions
static const char * Default_Name ()
Private Member Functions
void ComputeCrossSections (const G4ParticleDefinition *, G4double kinEnergy, G4int Z)
Private Attributes
G4ComponentBarNucleonNucleusXsc * fBarash
const G4ParticleDefinition * theProton
const G4ParticleDefinition * theNeutron
G4double fTotalXsc
G4double fInelasticXsc
G4double fElasticXsc
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 44 of file G4NucleonNuclearCrossSection.hh.
Constructor & Destructor Documentation
G4NucleonNuclearCrossSection()
G4NucleonNuclearCrossSection::G4NucleonNuclearCrossSection ()
Definition at line 52 of file G4NucleonNuclearCrossSection.cc.
~G4NucleonNuclearCrossSection()
G4NucleonNuclearCrossSection::~G4NucleonNuclearCrossSection () virtual
Definition at line 64 of file G4NucleonNuclearCrossSection.cc.
Member Function Documentation
ComputeCrossSections()
void G4NucleonNuclearCrossSection::ComputeCrossSections (const G4ParticleDefinition * pd, G4double kinEnergy, G4int Z) private
Definition at line 89 of file G4NucleonNuclearCrossSection.cc.
Referenced by GetElasticCrossSection(), and GetElementCrossSection().
CrossSectionDescription()
void G4NucleonNuclearCrossSection::CrossSectionDescription (std::ostream & outFile) const virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 104 of file G4NucleonNuclearCrossSection.cc.
Default_Name()
static const char* G4NucleonNuclearCrossSection::Default_Name () inline static
Definition at line 51 of file G4NucleonNuclearCrossSection.hh.
Referenced by G4BGGNucleonInelasticXS::BuildPhysicsTable(), and G4BGGNucleonElasticXS::BuildPhysicsTable().
GetElasticCrossSection()
G4double G4NucleonNuclearCrossSection::GetElasticCrossSection (const G4DynamicParticle * aParticle, G4int Z) inline
Definition at line 87 of file G4NucleonNuclearCrossSection.hh.
Referenced by G4BGGNucleonElasticXS::BuildPhysicsTable(), and G4BGGNucleonElasticXS::GetElementCrossSection().
GetElasticXsc()
G4double G4NucleonNuclearCrossSection::GetElasticXsc () inline
Definition at line 68 of file G4NucleonNuclearCrossSection.hh.
GetElementCrossSection()
G4double G4NucleonNuclearCrossSection::GetElementCrossSection (const G4DynamicParticle * aParticle, G4int Z, const G4Material * mat = nullptr) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 79 of file G4NucleonNuclearCrossSection.cc.
Referenced by G4BGGNucleonInelasticXS::BuildPhysicsTable(), and G4BGGNucleonInelasticXS::GetElementCrossSection().
GetInelasticXsc()
G4double G4NucleonNuclearCrossSection::GetInelasticXsc () inline
Definition at line 67 of file G4NucleonNuclearCrossSection.hh.
GetTotalXsc()
G4double G4NucleonNuclearCrossSection::GetTotalXsc () inline
Definition at line 66 of file G4NucleonNuclearCrossSection.hh.
IsElementApplicable()
G4bool G4NucleonNuclearCrossSection::IsElementApplicable (const G4DynamicParticle * aParticle, G4int Z, const G4Material * mat = nullptr) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 70 of file G4NucleonNuclearCrossSection.cc.
Field Documentation
fBarash
G4ComponentBarNucleonNucleusXsc* G4NucleonNuclearCrossSection::fBarash private
Definition at line 75 of file G4NucleonNuclearCrossSection.hh.
Referenced by ComputeCrossSections(), and G4NucleonNuclearCrossSection().
fElasticXsc
G4double G4NucleonNuclearCrossSection::fElasticXsc private
Definition at line 82 of file G4NucleonNuclearCrossSection.hh.
Referenced by ComputeCrossSections(), GetElasticCrossSection(), and GetElasticXsc().
fInelasticXsc
G4double G4NucleonNuclearCrossSection::fInelasticXsc private
Definition at line 81 of file G4NucleonNuclearCrossSection.hh.
Referenced by ComputeCrossSections(), GetElementCrossSection(), and GetInelasticXsc().
fTotalXsc
G4double G4NucleonNuclearCrossSection::fTotalXsc private
Definition at line 80 of file G4NucleonNuclearCrossSection.hh.
Referenced by ComputeCrossSections(), and GetTotalXsc().
theNeutron
const G4ParticleDefinition* G4NucleonNuclearCrossSection::theNeutron private
Definition at line 78 of file G4NucleonNuclearCrossSection.hh.
Referenced by G4NucleonNuclearCrossSection().
theProton
const G4ParticleDefinition* G4NucleonNuclearCrossSection::theProton private
Definition at line 77 of file G4NucleonNuclearCrossSection.hh.
Referenced by G4NucleonNuclearCrossSection().
The documentation for this class was generated from the following files:
source/processes/hadronic/cross_sections/include/G4NucleonNuclearCrossSection.hh
source/processes/hadronic/cross_sections/src/G4NucleonNuclearCrossSection.cc