Geant4: G4VVisManager Class Reference
G4VVisManager Class Reference abstract
#include <G4VVisManager.hh>
Public Member Functions
G4VVisManager ()
virtual ~G4VVisManager ()
virtual void Draw (const G4Circle &, const G4Transform3D &objectTransformation=G4Transform3D())=0
virtual void Draw (const G4Polyhedron &, const G4Transform3D &objectTransformation=G4Transform3D())=0
virtual void Draw (const G4Polyline &, const G4Transform3D &objectTransformation=G4Transform3D())=0
virtual void Draw (const G4Polymarker &, const G4Transform3D &objectTransformation=G4Transform3D())=0
virtual void Draw (const G4Scale &, const G4Transform3D &objectTransformation=G4Transform3D())=0
virtual void Draw (const G4Square &, const G4Transform3D &objectTransformation=G4Transform3D())=0
virtual void Draw (const G4Text &, const G4Transform3D &objectTransformation=G4Transform3D())=0
virtual void Draw2D (const G4Circle &, const G4Transform3D &objectTransformation=G4Transform3D())=0
virtual void Draw2D (const G4Polyhedron &, const G4Transform3D &objectTransformation=G4Transform3D())=0
virtual void Draw2D (const G4Polyline &, const G4Transform3D &objectTransformation=G4Transform3D())=0
virtual void Draw2D (const G4Polymarker &, const G4Transform3D &objectTransformation=G4Transform3D())=0
virtual void Draw2D (const G4Square &, const G4Transform3D &objectTransformation=G4Transform3D())=0
virtual void Draw2D (const G4Text &, const G4Transform3D &objectTransformation=G4Transform3D())=0
virtual void Draw (const G4VTrajectory &)=0
virtual void Draw (const G4VHit &)=0
virtual void Draw (const G4VDigi &)=0
virtual void Draw (const G4LogicalVolume &, const G4VisAttributes &, const G4Transform3D &objectTransformation=G4Transform3D())=0
virtual void Draw (const G4VPhysicalVolume &, const G4VisAttributes &, const G4Transform3D &objectTransformation=G4Transform3D())=0
virtual void Draw (const G4VSolid &, const G4VisAttributes &, const G4Transform3D &objectTransformation=G4Transform3D())=0
virtual void BeginDraw (const G4Transform3D &objectTransformation=G4Transform3D())=0
virtual void EndDraw ()=0
virtual void BeginDraw2D (const G4Transform3D &objectTransformation=G4Transform3D())=0
virtual void EndDraw2D ()=0
virtual void GeometryHasChanged ()=0
virtual void IgnoreStateChanges (G4bool)
virtual void NotifyHandlers ()
virtual void DispatchToModel (const G4VTrajectory &)=0
virtual G4bool FilterTrajectory (const G4VTrajectory &)=0
virtual G4bool FilterHit (const G4VHit &)=0
virtual G4bool FilterDigi (const G4VDigi &)=0
G4bool GetDrawOverlapsFlag () const
void SetDrawOverlapsFlag (G4bool draw)
Static Public Member Functions
static G4VVisManager * GetConcreteInstance ()
Static Protected Member Functions
static void SetConcreteInstance (G4VVisManager *)
Static Protected Attributes
static G4VVisManager * fpConcreteInstance = 0
Private Attributes
G4bool fDrawOverlapsFlag
Detailed Description
Definition at line 92 of file G4VVisManager.hh.
Constructor & Destructor Documentation
G4VVisManager()
G4VVisManager::G4VVisManager ()
Definition at line 34 of file G4VVisManager.cc.
~G4VVisManager()
G4VVisManager::~G4VVisManager () virtual
Definition at line 38 of file G4VVisManager.cc.
Member Function Documentation
BeginDraw()
virtual void G4VVisManager::BeginDraw (const G4Transform3D & objectTransformation = G4Transform3D()) pure virtual
Implemented in G4VisManager.
Referenced by G4TrajectoriesModel::DescribeYourselfTo(), G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), G4ScoringCylinder::DrawColumn(), and G4ScoringBox::DrawColumn().
BeginDraw2D()
virtual void G4VVisManager::BeginDraw2D (const G4Transform3D & objectTransformation = G4Transform3D()) pure virtual
Implemented in G4VisManager.
Referenced by G4VScoreColorMap::DrawColorChartBar(), and G4VScoreColorMap::DrawColorChartText().
DispatchToModel()
virtual void G4VVisManager::DispatchToModel (const G4VTrajectory &) pure virtual
Implemented in G4VisManager.
Referenced by G4VTrajectory::DrawTrajectory().
Draw() [1/13]
virtual void G4VVisManager::Draw (const G4Circle & , const G4Transform3D & objectTransformation = G4Transform3D()) pure virtual
Implemented in G4VisManager.
Referenced by StandaloneVisAction::Draw(), UVA_VisAction::Draw(), ExN04MuonHit::Draw(), ExN04TrackerHit::Draw(), G4ScoringCylinder::Draw(), ExTGTrackerHit::Draw(), RE01TrackerHit::Draw(), G4ScoringBox::Draw(), RE05MuonHit::Draw(), RE05TrackerHit::Draw(), eRositaTrackerHit::Draw(), RE01CalorimeterHit::Draw(), ExP01TrackerHit::Draw(), RE05CalorimeterHit::Draw(), ExGflashHit::Draw(), B2TrackerHit::Draw(), XAluminumElectrodeHit::Draw(), LXePMTHit::Draw(), ExN02TrackerHit::Draw(), Par01CalorimeterHit::Draw(), TrackerHit::Draw(), DMXPmtHit::Draw(), H02MuonHit::Draw(), G4ScoringCylinder::DrawColumn(), G4ScoringBox::DrawColumn(), G4BlineEventAction::DrawFieldLines(), LXeTrajectory::DrawTrajectory(), RE01Trajectory::DrawTrajectory(), G4DrawVoxels::DrawVoxels(), G4TrajectoryDrawerUtils::DrawWithoutTime(), G4TrajectoryDrawerUtils::DrawWithTime(), ITTrackingInteractivity::Finalize(), and DMXSteppingAction::UserSteppingAction().
Draw() [2/13]
virtual void G4VVisManager::Draw (const G4LogicalVolume & , const G4VisAttributes & , const G4Transform3D & objectTransformation = G4Transform3D()) pure virtual
Implemented in G4VisManager.
Draw() [3/13]
virtual void G4VVisManager::Draw (const G4Polyhedron & , const G4Transform3D & objectTransformation = G4Transform3D()) pure virtual
Implemented in G4VisManager.
Draw() [4/13]
virtual void G4VVisManager::Draw (const G4Polyline & , const G4Transform3D & objectTransformation = G4Transform3D()) pure virtual
Implemented in G4VisManager.
Draw() [5/13]
virtual void G4VVisManager::Draw (const G4Polymarker & , const G4Transform3D & objectTransformation = G4Transform3D()) pure virtual
Implemented in G4VisManager.
Draw() [6/13]
virtual void G4VVisManager::Draw (const G4Scale & , const G4Transform3D & objectTransformation = G4Transform3D()) pure virtual
Implemented in G4VisManager.
Draw() [7/13]
virtual void G4VVisManager::Draw (const G4Square & , const G4Transform3D & objectTransformation = G4Transform3D()) pure virtual
Implemented in G4VisManager.
Draw() [8/13]
virtual void G4VVisManager::Draw (const G4Text & , const G4Transform3D & objectTransformation = G4Transform3D()) pure virtual
Implemented in G4VisManager.
Draw() [9/13]
virtual void G4VVisManager::Draw (const G4VDigi &) pure virtual
Implemented in G4VisManager.
Draw() [10/13]
virtual void G4VVisManager::Draw (const G4VHit &) pure virtual
Implemented in G4VisManager.
Draw() [11/13]
virtual void G4VVisManager::Draw (const G4VPhysicalVolume & , const G4VisAttributes & , const G4Transform3D & objectTransformation = G4Transform3D()) pure virtual
Implemented in G4VisManager.
Draw() [12/13]
virtual void G4VVisManager::Draw (const G4VSolid & , const G4VisAttributes & , const G4Transform3D & objectTransformation = G4Transform3D()) pure virtual
Implemented in G4VisManager.
Draw() [13/13]
virtual void G4VVisManager::Draw (const G4VTrajectory &) pure virtual
Implemented in G4VisManager.
Draw2D() [1/6]
virtual void G4VVisManager::Draw2D (const G4Circle & , const G4Transform3D & objectTransformation = G4Transform3D()) pure virtual
Implemented in G4VisManager.
Referenced by G4ScoreLogColorMap::DrawColorChartBar(), G4VScoreColorMap::DrawColorChartBar(), G4ScoreLogColorMap::DrawColorChartText(), and G4VScoreColorMap::DrawColorChartText().
Draw2D() [2/6]
virtual void G4VVisManager::Draw2D (const G4Polyhedron & , const G4Transform3D & objectTransformation = G4Transform3D()) pure virtual
Implemented in G4VisManager.
Draw2D() [3/6]
virtual void G4VVisManager::Draw2D (const G4Polyline & , const G4Transform3D & objectTransformation = G4Transform3D()) pure virtual
Implemented in G4VisManager.
Draw2D() [4/6]
virtual void G4VVisManager::Draw2D (const G4Polymarker & , const G4Transform3D & objectTransformation = G4Transform3D()) pure virtual
Implemented in G4VisManager.
Draw2D() [5/6]
virtual void G4VVisManager::Draw2D (const G4Square & , const G4Transform3D & objectTransformation = G4Transform3D()) pure virtual
Implemented in G4VisManager.
Draw2D() [6/6]
virtual void G4VVisManager::Draw2D (const G4Text & , const G4Transform3D & objectTransformation = G4Transform3D()) pure virtual
Implemented in G4VisManager.
EndDraw()
virtual void G4VVisManager::EndDraw () pure virtual
Implemented in G4VisManager.
Referenced by G4TrajectoriesModel::DescribeYourselfTo(), G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), G4ScoringCylinder::DrawColumn(), and G4ScoringBox::DrawColumn().
EndDraw2D()
virtual void G4VVisManager::EndDraw2D () pure virtual
Implemented in G4VisManager.
Referenced by G4VScoreColorMap::DrawColorChartBar(), and G4VScoreColorMap::DrawColorChartText().
FilterDigi()
virtual G4bool G4VVisManager::FilterDigi (const G4VDigi &) pure virtual
Implemented in G4VisManager.
FilterHit()
virtual G4bool G4VVisManager::FilterHit (const G4VHit &) pure virtual
Implemented in G4VisManager.
FilterTrajectory()
virtual G4bool G4VVisManager::FilterTrajectory (const G4VTrajectory &) pure virtual
Implemented in G4VisManager.
GeometryHasChanged()
virtual void G4VVisManager::GeometryHasChanged () pure virtual
Implemented in G4VisManager.
Referenced by G4RunManagerKernel::DefineWorldVolume(), G4RunManager::ReinitializeGeometry(), G4RunManagerKernel::RunInitialization(), and G4RunManagerKernel::WorkerDefineWorldVolume().
GetConcreteInstance()
G4VVisManager * G4VVisManager::GetConcreteInstance () static
Definition at line 42 of file G4VVisManager.cc.
Referenced by G4VisManager::BeginOfEvent(), GammaRayTelRunAction::BeginOfRunAction(), XrayFluoRunAction::BeginOfRunAction(), XrayTelRunAction::BeginOfRunAction(), DicomPhantomParameterisationColour::ComputeMaterial(), DicomNestedPhantomParameterisation::ComputeMaterial(), G4TheRayTracer::CreateBitMap(), G4TheMTRayTracer::CreateBitMap(), G4RunManagerKernel::DefineWorldVolume(), G4TrajectoriesModel::DescribeYourselfTo(), StandaloneVisAction::Draw(), UVA_VisAction::Draw(), ExN04MuonHit::Draw(), ExN04TrackerHit::Draw(), G4ScoringCylinder::Draw(), ExTGTrackerHit::Draw(), RE01TrackerHit::Draw(), G4ScoringBox::Draw(), RE05MuonHit::Draw(), RE05TrackerHit::Draw(), Par01EnergySpot::Draw(), ExN04CalorimeterHit::Draw(), PerspectiveVisAction::Draw(), eRositaTrackerHit::Draw(), RE01CalorimeterHit::Draw(), ExP01TrackerHit::Draw(), ExGflashHit::Draw(), RE05CalorimeterHit::Draw(), B2TrackerHit::Draw(), XAluminumElectrodeHit::Draw(), LXePMTHit::Draw(), ExN02TrackerHit::Draw(), Par01CalorimeterHit::Draw(), B5HodoscopeHit::Draw(), TrackerHit::Draw(), B5EmCalorimeterHit::Draw(), B5HadCalorimeterHit::Draw(), DMXPmtHit::Draw(), B5DriftChamberHit::Draw(), G4Event::Draw(), H02MuonHit::Draw(), G4VScoreColorMap::DrawColorChart(), G4ScoringCylinder::DrawColumn(), G4ScoringBox::DrawColumn(), G4BlineEventAction::DrawFieldLines(), CexmcEventAction::DrawReconstructionData(), CexmcEventAction::DrawTrackPoints(), DMXEventAction::drawTracks(), CexmcEventAction::DrawTrajectories(), LXeTrajectory::DrawTrajectory(), RE01Trajectory::DrawTrajectory(), G4VTrajectory::DrawTrajectory(), G4DrawVoxels::DrawVoxels(), G4TrajectoryDrawerUtils::DrawWithoutTime(), G4TrajectoryDrawerUtils::DrawWithTime(), G4VisManager::EndOfEvent(), LXeEventAction::EndOfEventAction(), G4VisManager::EndOfRun(), XrayFluoRunAction::EndOfRunAction(), XrayTelRunAction::EndOfRunAction(), ITTrackingInteractivity::Finalize(), G4WorkerRunManager::G4WorkerRunManager(), G4VSceneHandler::ProcessScene(), CexmcRunManager::RegisterScenePrimitives(), G4RunManager::ReinitializeGeometry(), G4WorkerRunManager::RunInitialization(), G4RunManagerKernel::RunInitialization(), G4ModelCmdApplyStringColour< M >::SetNewValue(), G4VisCommandReviewKeptEvents::SetNewValue(), G4ModelCmdApplyColour< M >::SetNewValue(), G4ModelCmdApplyBool< M >::SetNewValue(), G4ModelCmdApplyNull< M >::SetNewValue(), G4ModelCmdApplyDouble< M >::SetNewValue(), G4ModelCmdApplyDoubleAndUnit< M >::SetNewValue(), G4ModelCmdApplyInteger< M >::SetNewValue(), G4ModelCmdApplyString< M >::SetNewValue(), CexmcScenePrimitives::UpdateScene(), DMXSteppingAction::UserSteppingAction(), and G4RunManagerKernel::WorkerDefineWorldVolume().
GetDrawOverlapsFlag()
G4bool G4VVisManager::GetDrawOverlapsFlag () const inline
Definition at line 231 of file G4VVisManager.hh.
IgnoreStateChanges()
void G4VVisManager::IgnoreStateChanges (G4bool) virtual
Reimplemented in G4VisManager.
Definition at line 52 of file G4VVisManager.cc.
Referenced by G4TheRayTracer::CreateBitMap(), and G4TheMTRayTracer::CreateBitMap().
NotifyHandlers()
virtual void G4VVisManager::NotifyHandlers () inline virtual
Reimplemented in G4VisManager.
Definition at line 207 of file G4VVisManager.hh.
Referenced by G4ModelCmdApplyStringColour< M >::SetNewValue(), G4ModelCmdApplyColour< M >::SetNewValue(), G4ModelCmdApplyNull< M >::SetNewValue(), G4ModelCmdApplyString< M >::SetNewValue(), and CexmcScenePrimitives::UpdateScene().
SetConcreteInstance()
void G4VVisManager::SetConcreteInstance (G4VVisManager * man) static protected
Definition at line 47 of file G4VVisManager.cc.
Referenced by G4VisManager::Disable(), G4VisManager::Enable(), and G4VisManager::G4VisManager().
SetDrawOverlapsFlag()
void G4VVisManager::SetDrawOverlapsFlag (G4bool draw) inline
Definition at line 236 of file G4VVisManager.hh.
Field Documentation
fDrawOverlapsFlag
G4bool G4VVisManager::fDrawOverlapsFlag private
Definition at line 256 of file G4VVisManager.hh.
Referenced by GetDrawOverlapsFlag(), and SetDrawOverlapsFlag().
fpConcreteInstance
G4VVisManager * G4VVisManager::fpConcreteInstance = 0 static protected
Definition at line 252 of file G4VVisManager.hh.
Referenced by GetConcreteInstance(), and SetConcreteInstance().
The documentation for this class was generated from the following files:
source/graphics_reps/include/G4VVisManager.hh
source/graphics_reps/src/G4VVisManager.cc