Geant4: source/g3tog4/src/G4gsdvt.cc File Reference
G4gsdvt.cc File Reference
#include "G3Division.hh"
#include "G3VolTableEntry.hh"
#include "G3VolTable.hh"
#include "globals.hh"
#include "G3toG4.hh"
Functions
void G4CreateCloneVTEWithDivision (G4String vname, G3VolTableEntry *mvte, G3DivType divType, G4int nofDivisions, G4int iaxis, G4int nmed, G4double c0, G4double step)
void PG4gsdvt (G4String *tokens)
void G4gsdvt (G4String vname, G4String vmoth, G4double step, G4int iaxis, G4int numed, G4int ndvmx)
Function Documentation
G4CreateCloneVTEWithDivision()
void G4CreateCloneVTEWithDivision (G4String vname, G3VolTableEntry * mvte, G3DivType divType, G4int nofDivisions, G4int iaxis, G4int nmed, G4double c0, G4double step)
Definition at line 51 of file G4gsdvn.cc.
Referenced by G4gsdvt().
G4gsdvt()
void G4gsdvt (G4String vname, G4String vmoth, G4double step, G4int iaxis, G4int numed, G4int ndvmx)
Definition at line 56 of file G4gsdvt.cc.
Referenced by PG4gsdvt().
PG4gsdvt()
void PG4gsdvt (G4String * tokens)
Definition at line 40 of file G4gsdvt.cc.
Referenced by G3CLEval().