Geant4: G4INCL::Store Class Reference
G4INCL::Store Class Reference
The purpose of the Store object is to act as a "particle manager" that keeps track ofall the particles in our simulation.
#include <G4INCLStore.hh>
Public Member Functions
Store (Config const *const config)
Store constructor.
~Store ()
Store destructor.
void add (Particle *p)
Add one particle to the store.
void add (ParticleList const &pL)
Add a list of particles to the Store.
void addParticleEntryAvatar (IAvatar *a)
Add one ParticleEntry avatar.
void addParticleEntryAvatars (IAvatarList const &al)
Add one ParticleEntry avatar.
void add (IAvatar *a)
Add one avatar to the store.
const IAvatarList & getAvatars () const
Return the list of avatars.
void addIncomingParticle (Particle *const p)
Add a particle to the incoming list.
void removeFromIncoming (Particle *const p)
Add a particle to the incoming list.
void clearIncoming ()
Clear the incoming list.
void deleteIncoming ()
Clear the incoming list and delete the particles.
void particleHasBeenUpdated (Particle *const)
Notify the Store about a particle update.
void removeScheduledAvatars ()
Remove avatars that have been scheduled.
IAvatar * findSmallestTime ()
Find the avatar that has the smallest time.
void timeStep (G4double step)
Make one time step: propagate particles and subtract the length of the step from the avatar times.
void particleHasBeenEjected (Particle *const)
Mark the particle as ejected.
void addToOutgoing (Particle *p)
add the particle to the outgoing particle list.
void addToOutgoing (ParticleList const &pl)
Add a list of particles to the outgoing particle list.
void particleHasBeenDestroyed (Particle *const)
Remove the particle from the system.
void particleHasEntered (Particle *const particle)
Move a particle from incoming to inside.
const ParticleList & getIncomingParticles () const
Return the list of incoming particles (i.e.
const ParticleList & getOutgoingParticles () const
Return the list of outgoing particles (i.e.
ParticleList extractDynamicalSpectators ()
Returns a list of dynamical spectators.
const ParticleList & getParticles () const
Return the list of "active" particles (i.e.
Book & getBook ()
Return the pointer to the Book object which keeps track of various counters.
G4int countCascading ()
const Config * getConfig ()
Get the config object.
void clear ()
Clear all avatars and particles from the store.
void clearInside ()
Clear all inside particles from the store.
void clearOutgoing ()
Clear all outgoing particles from the store.
void clearAvatars ()
Clear avatars only.
void loadParticles (std::string const &filename)
Load particle configuration from ASCII file (see avatarPredictionTest).
G4int getLoadedA ()
Get the value of the nucleus mass number that we read from file with loadParticles.
G4int getLoadedZ ()
Get the value of the nucleus charge number that we read from file with loadParticles.
G4double getLoadedStoppingTime ()
Get the value of the stopping time that we read from file with loadParticles.
std::string printParticleConfiguration ()
Print the nucleon configuration of the nucleus.
void writeParticles (std::string const &filename)
Print the nucleon configuration of the nucleus.
std::string printAvatars ()
Print the list of avatars.
G4bool containsCollisions () const
Static Public Member Functions
static G4bool avatarComparisonPredicate (IAvatar *lhs, IAvatar *rhs)
Comparison predicate for avatars.
Private Types
typedef std::multimap< Particle *, IAvatar * >::value_type PAPair
typedef std::multimap< Particle *, IAvatar * >::iterator PAIter
typedef std::pair< PAIter, PAIter > PAIterPair
typedef std::set< IAvatar * >::const_iterator ASIter
Private Member Functions
Store (const Store &rhs)
Dummy copy constructor to shut up Coverity warnings.
Store & operator= (Store const &rhs)
Dummy assignment operator to shut up Coverity warnings.
void connectAvatarToParticle (IAvatar *const a, Particle *const p)
Connect an avatar to a particle.
void disconnectAvatarFromParticle (IAvatar *const a, Particle *const p)
Disconnect an avatar from a particle.
void removeAvatar (IAvatar *const a)
Remove an avatar from the list of avatars.
Private Attributes
std::multimap< Particle *, IAvatar * > particleAvatarConnections
Map particle -> [avatar].
std::set< IAvatar * > avatarsToBeRemoved
Set of avatars to be removed.
IAvatarList avatarList
List of all avatars.
ParticleList incoming
List of incoming particles.
ParticleList inside
List of particles that are inside the nucleus.
ParticleList outgoing
List of outgoing particles.
ParticleList geomSpectators
List of geometrical spectators.
G4double currentTime
The current time in the simulation.
Book theBook
The Book object keeps track of global counters.
G4int loadedA
The target nucleus mass number that was loaded from a particle file.
G4int loadedZ
The target nucleus charge number that was loaded from a particle file.
G4double loadedStoppingTime
The stopping time that was loaded from a particle file.
const Config * theConfig
Pointer to the Config object.
Detailed Description
The purpose of the Store object is to act as a "particle manager" that keeps track ofall the particles in our simulation.
It also tracks the avatars and their connections to particles.
Definition at line 73 of file G4INCLStore.hh.
Member Typedef Documentation
ASIter
typedef std::set<IAvatar*>::const_iterator G4INCL::Store::ASIter private
Definition at line 406 of file G4INCLStore.hh.
PAIter
typedef std::multimap<Particle*, IAvatar*>::iterator G4INCL::Store::PAIter private
Definition at line 401 of file G4INCLStore.hh.
PAIterPair
typedef std::pair<PAIter, PAIter> G4INCL::Store::PAIterPair private
Definition at line 402 of file G4INCLStore.hh.
PAPair
typedef std::multimap<Particle*, IAvatar*>::value_type G4INCL::Store::PAPair private
Definition at line 400 of file G4INCLStore.hh.
Constructor & Destructor Documentation
Store() [1/2]
G4INCL::Store::Store (Config const *const config)
Store constructor.
Definition at line 45 of file G4INCLStore.cc.
~Store()
G4INCL::Store::~Store ()
Store destructor.
Definition at line 53 of file G4INCLStore.cc.
Store() [2/2]
G4INCL::Store::Store (const Store & rhs) private
Dummy copy constructor to shut up Coverity warnings.
Member Function Documentation
add() [1/3]
void G4INCL::Store::add (IAvatar * a)
Add one avatar to the store.
Avatars know about the particles they are associated with. Adding an avatar consists of the following steps:
Add the new avatar to the avatar list
Add any related new particles to the store by calling add(Particle*) (this should not happen, by the time we are adding avatars all particles should have already been added)
Connect the particles involved to the avatar in the map: particleAvatarConnections :: ParticleID -> [AvatarID]
Add the new avatar to the map: avatarParticleConnections :: AvatarID -> [ParticleID]
Definition at line 83 of file G4INCLStore.cc.
add() [2/3]
void G4INCL::Store::add (Particle * p)
Add one particle to the store.
Particle objects don't know anything about avatars so this method will only do two things:
add the particle to the particle map ParticleID -> Particle*
add an empty entry for this particle into map AvatarID -> [ParticleID]
Definition at line 58 of file G4INCLStore.cc.
Referenced by G4INCL::Nucleus::applyFinalState(), G4INCL::Nucleus::initializeParticles(), loadParticles(), particleHasEntered(), and G4INCL::StandardPropagationModel::registerAvatar().
add() [3/3]
void G4INCL::Store::add (ParticleList const & pL)
Add a list of particles to the Store.
This acts as if add(Particle *) was called on each element of the list.
Definition at line 62 of file G4INCLStore.cc.
addIncomingParticle()
void G4INCL::Store::addIncomingParticle (Particle *const p)
Add a particle to the incoming list.
Parameters
p particle to add
Definition at line 95 of file G4INCLStore.cc.
Referenced by addParticleEntryAvatar().
addParticleEntryAvatar()
void G4INCL::Store::addParticleEntryAvatar (IAvatar * a)
Add one ParticleEntry avatar.
Definition at line 66 of file G4INCLStore.cc.
Referenced by addParticleEntryAvatars(), G4INCL::INCL::makeCompoundNucleus(), and G4INCL::StandardPropagationModel::shootParticle().
addParticleEntryAvatars()
void G4INCL::Store::addParticleEntryAvatars (IAvatarList const & al)
Add one ParticleEntry avatar.
Definition at line 78 of file G4INCLStore.cc.
Referenced by G4INCL::StandardPropagationModel::shootComposite().
addToOutgoing() [1/2]
void G4INCL::Store::addToOutgoing (Particle * p) inline
add the particle to the outgoing particle list.
Parameters
p pointer to the particle to be added
Definition at line 190 of file G4INCLStore.hh.
Referenced by G4INCL::Nucleus::applyFinalState(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::decayMe(), G4INCL::Nucleus::decayOutgoingClusters(), G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), and G4INCL::INCL::makeProjectileRemnant().
addToOutgoing() [2/2]
void G4INCL::Store::addToOutgoing (ParticleList const & pl) inline
Add a list of particles to the outgoing particle list.
Parameters
pl list of particles to be added
Definition at line 196 of file G4INCLStore.hh.
avatarComparisonPredicate()
static G4bool G4INCL::Store::avatarComparisonPredicate (IAvatar * lhs, IAvatar * rhs) inline static
Comparison predicate for avatars.
avatarComparisonPredicate is used by the std::sort or std::min_element functions to compare the avatar objects according to their time.
Parameters
lhs pointer to the first avatar
rhs pointer to the second avatar
Returns
true iff lhs' time is smaller than rhs'.
Definition at line 352 of file G4INCLStore.hh.
Referenced by findSmallestTime().
clear()
void G4INCL::Store::clear (void)
Clear all avatars and particles from the store.
Warning! This actually deletes the objects as well!
Definition at line 203 of file G4INCLStore.cc.
Referenced by loadParticles(), and ~Store().
clearAvatars()
void G4INCL::Store::clearAvatars ()
Clear avatars only.
Definition at line 193 of file G4INCLStore.cc.
Referenced by clear(), and G4INCL::StandardPropagationModel::propagate().
clearIncoming()
void G4INCL::Store::clearIncoming () inline
Clear the incoming list.
Definition at line 145 of file G4INCLStore.hh.
Referenced by G4INCL::INCL::makeCompoundNucleus(), and G4INCL::INCL::postCascade().
clearInside()
void G4INCL::Store::clearInside ()
Clear all inside particles from the store.
Warning! This actually deletes the objects as well!
Definition at line 216 of file G4INCLStore.cc.
Referenced by clear().
clearOutgoing()
void G4INCL::Store::clearOutgoing ()
Clear all outgoing particles from the store.
Warning! This actually deletes the objects as well!
Definition at line 223 of file G4INCLStore.cc.
Referenced by clear(), and G4INCL::INCL::makeCompoundNucleus().
connectAvatarToParticle()
void G4INCL::Store::connectAvatarToParticle (IAvatar *const a, Particle *const p) private
Connect an avatar to a particle.
Adds the avatar to the list of avatars where the particle appears. This is typically called when the avatar is created.
Parameters
p the particle
a the avatar
Definition at line 99 of file G4INCLStore.cc.
Referenced by add(), and addParticleEntryAvatar().
containsCollisions()
G4bool G4INCL::Store::containsCollisions () const
Definition at line 351 of file G4INCLStore.cc.
countCascading()
G4int G4INCL::Store::countCascading () inline
Definition at line 261 of file G4INCLStore.hh.
deleteIncoming()
void G4INCL::Store::deleteIncoming () inline
Clear the incoming list and delete the particles.
Definition at line 150 of file G4INCLStore.hh.
Referenced by G4INCL::INCL::postCascade().
disconnectAvatarFromParticle()
void G4INCL::Store::disconnectAvatarFromParticle (IAvatar *const a, Particle *const p) private
Disconnect an avatar from a particle.
Removes the avatar from the list of avatars where the particle appears. This is typically called when the avatar has been invalidated or realised.
Parameters
p the particle
a the avatar
Definition at line 103 of file G4INCLStore.cc.
Referenced by removeAvatar().
extractDynamicalSpectators()
ParticleList G4INCL::Store::extractDynamicalSpectators () inline
Returns a list of dynamical spectators.
Looks in the outgoing list for particles without collisions and decays, removes them from outgoing and returns them in a list.
Returns
the (possibly empty) list of dynamical spectators
Definition at line 232 of file G4INCLStore.hh.
Referenced by G4INCL::INCL::makeProjectileRemnant().
findSmallestTime()
IAvatar * G4INCL::Store::findSmallestTime ()
Find the avatar that has the smallest time.
Definition at line 142 of file G4INCLStore.cc.
Referenced by G4INCL::StandardPropagationModel::propagate().
getAvatars()
const IAvatarList& G4INCL::Store::getAvatars () const inline
Return the list of avatars.
Definition at line 126 of file G4INCLStore.hh.
getBook()
Book& G4INCL::Store::getBook () inline
Return the pointer to the Book object which keeps track of various counters.
Definition at line 259 of file G4INCLStore.hh.
Referenced by G4INCL::Nucleus::applyFinalState(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::INCL::continueCascade(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::InteractionAvatar::enforceEnergyConservation(), G4INCL::Nucleus::fillEventInfo(), G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::SurfaceAvatar::getChannel(), G4INCL::INCL::initializeTarget(), G4INCL::Nucleus::insertParticle(), G4INCL::PauliStrictStandard::isBlocked(), G4INCL::Nucleus::isEventTransparent(), G4INCL::DecayAvatar::postInteraction(), G4INCL::BinaryCollisionAvatar::postInteraction(), G4INCL::SurfaceAvatar::postInteraction(), G4INCL::InteractionAvatar::postInteraction(), G4INCL::StandardPropagationModel::propagate(), and G4INCL::InteractionAvatar::shouldUseLocalEnergy().
getConfig()
const Config* G4INCL::Store::getConfig () inline
Get the config object.
Definition at line 273 of file G4INCLStore.hh.
Referenced by G4INCL::SurfaceAvatar::getChannel(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::SurfaceAvatar::getTransmissionProbability(), G4INCL::InteractionAvatar::postInteraction(), and G4INCL::InteractionAvatar::shouldUseLocalEnergy().
getIncomingParticles()
const ParticleList& G4INCL::Store::getIncomingParticles () const inline
Return the list of incoming particles (i.e.
particles that have yet to enter the cascade).
Definition at line 217 of file G4INCLStore.hh.
Referenced by G4INCL::INCL::continueCascade().
getLoadedA()
G4int G4INCL::Store::getLoadedA () inline
Get the value of the nucleus mass number that we read from file with loadParticles.
Definition at line 311 of file G4INCLStore.hh.
getLoadedStoppingTime()
G4double G4INCL::Store::getLoadedStoppingTime () inline
Get the value of the stopping time that we read from file with loadParticles.
Definition at line 323 of file G4INCLStore.hh.
getLoadedZ()
G4int G4INCL::Store::getLoadedZ () inline
Get the value of the nucleus charge number that we read from file with loadParticles.
Definition at line 317 of file G4INCLStore.hh.
getOutgoingParticles()
const ParticleList& G4INCL::Store::getOutgoingParticles () const inline
Return the list of outgoing particles (i.e.
particles that have left the cascade).
Definition at line 223 of file G4INCLStore.hh.
Referenced by G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::computeRecoilKinematics(), G4INCL::Nucleus::computeSeparationEnergyBalance(), G4INCL::Nucleus::decayOutgoingClusters(), G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::Nucleus::decayOutgoingNeutralKaon(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), G4INCL::Nucleus::fillEventInfo(), G4INCL::Nucleus::getConservationBalance(), G4INCL::INCL::postCascade(), and G4INCL::Nucleus::print().
getParticles()
const ParticleList& G4INCL::Store::getParticles () const inline
Return the list of "active" particles (i.e.
particles that can participate in collisions).
Definition at line 253 of file G4INCLStore.hh.
Referenced by G4INCL::AvatarDumpAction::afterAvatarUserAction(), G4INCL::Nucleus::computeCenterOfMass(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::computeTotalEnergy(), G4INCL::Nucleus::containsAntiKaon(), G4INCL::Nucleus::containsDeltas(), G4INCL::Nucleus::containsEtas(), G4INCL::Nucleus::containsKaon(), G4INCL::Nucleus::containsLambda(), G4INCL::Nucleus::containsOmegas(), G4INCL::Nucleus::containsSigma(), G4INCL::Nucleus::decayInsideDeltas(), G4INCL::Nucleus::decayInsideStrangeParticles(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::StandardPropagationModel::generateAllAvatars(), G4INCL::PauliStandard::getBlockingProbability(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::CDPP::isBlocked(), G4INCL::Nucleus::print(), and G4INCL::StandardPropagationModel::updateAvatars().
loadParticles()
void G4INCL::Store::loadParticles (std::string const & filename)
Load particle configuration from ASCII file (see avatarPredictionTest).
Definition at line 239 of file G4INCLStore.cc.
operator=()
Store& G4INCL::Store::operator= (Store const & rhs) private
Dummy assignment operator to shut up Coverity warnings.
particleHasBeenDestroyed()
void G4INCL::Store::particleHasBeenDestroyed (Particle * const p)
Remove the particle from the system.
This also removes all avatars related to this particle.
Definition at line 181 of file G4INCLStore.cc.
Referenced by G4INCL::Nucleus::applyFinalState().
particleHasBeenEjected()
void G4INCL::Store::particleHasBeenEjected (Particle * const p)
Mark the particle as ejected.
This removes it from the list of inside particles and removes all avatars related to this particle.
Definition at line 175 of file G4INCLStore.cc.
Referenced by G4INCL::Nucleus::applyFinalState(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), and G4INCL::Nucleus::emitInsideStrangeParticles().
particleHasBeenUpdated()
void G4INCL::Store::particleHasBeenUpdated (Particle * const particle)
Notify the Store about a particle update.
Notify the Store that a particle has been updated. This schedules the removal of obsolete avatars and their disconnection from the particle.
Definition at line 127 of file G4INCLStore.cc.
Referenced by G4INCL::Nucleus::applyFinalState(), particleHasBeenDestroyed(), and particleHasBeenEjected().
particleHasEntered()
void G4INCL::Store::particleHasEntered (Particle *const particle)
Move a particle from incoming to inside.
Parameters
particle pointer to a particle
Definition at line 188 of file G4INCLStore.cc.
Referenced by G4INCL::Nucleus::insertParticle().
printAvatars()
std::string G4INCL::Store::printAvatars ()
Print the list of avatars.
Definition at line 343 of file G4INCLStore.cc.
printParticleConfiguration()
std::string G4INCL::Store::printParticleConfiguration ()
Print the nucleon configuration of the nucleus.
Definition at line 286 of file G4INCLStore.cc.
Referenced by writeParticles().
removeAvatar()
void G4INCL::Store::removeAvatar (IAvatar *const a) private
Remove an avatar from the list of avatars.
Removes an avatar from the list of all avatars. The avatar is not deleted.
Parameters
a the avatar to remove
Definition at line 115 of file G4INCLStore.cc.
Referenced by findSmallestTime(), and removeScheduledAvatars().
removeFromIncoming()
void G4INCL::Store::removeFromIncoming (Particle *const p) inline
Add a particle to the incoming list.
Parameters
p particle to add
Definition at line 142 of file G4INCLStore.hh.
Referenced by particleHasEntered().
removeScheduledAvatars()
void G4INCL::Store::removeScheduledAvatars ()
Remove avatars that have been scheduled.
Definition at line 134 of file G4INCLStore.cc.
Referenced by G4INCL::Nucleus::applyFinalState().
timeStep()
void G4INCL::Store::timeStep (G4double step)
Make one time step: propagate particles and subtract the length of the step from the avatar times.
Definition at line 168 of file G4INCLStore.cc.
Referenced by G4INCL::StandardPropagationModel::propagate().
writeParticles()
void G4INCL::Store::writeParticles (std::string const & filename)
Print the nucleon configuration of the nucleus.
Definition at line 337 of file G4INCLStore.cc.
Field Documentation
avatarList
IAvatarList G4INCL::Store::avatarList private
List of all avatars.
Definition at line 412 of file G4INCLStore.hh.
Referenced by add(), addParticleEntryAvatar(), clearAvatars(), containsCollisions(), findSmallestTime(), printAvatars(), and removeAvatar().
avatarsToBeRemoved
std::set<IAvatar*> G4INCL::Store::avatarsToBeRemoved private
Set of avatars to be removed.
Definition at line 405 of file G4INCLStore.hh.
Referenced by clearAvatars(), particleHasBeenUpdated(), and removeScheduledAvatars().
currentTime
G4double G4INCL::Store::currentTime private
The current time in the simulation.
Definition at line 437 of file G4INCLStore.hh.
geomSpectators
ParticleList G4INCL::Store::geomSpectators private
List of geometrical spectators.
Definition at line 432 of file G4INCLStore.hh.
incoming
ParticleList G4INCL::Store::incoming private
List of incoming particles.
Definition at line 417 of file G4INCLStore.hh.
Referenced by addIncomingParticle(), and clear().
inside
ParticleList G4INCL::Store::inside private
List of particles that are inside the nucleus.
Definition at line 422 of file G4INCLStore.hh.
Referenced by add(), clearInside(), particleHasBeenDestroyed(), particleHasBeenEjected(), printParticleConfiguration(), and timeStep().
loadedA
G4int G4INCL::Store::loadedA private
The target nucleus mass number that was loaded from a particle file.
Definition at line 447 of file G4INCLStore.hh.
Referenced by loadParticles().
loadedStoppingTime
G4double G4INCL::Store::loadedStoppingTime private
The stopping time that was loaded from a particle file.
Definition at line 457 of file G4INCLStore.hh.
Referenced by loadParticles().
loadedZ
G4int G4INCL::Store::loadedZ private
The target nucleus charge number that was loaded from a particle file.
Definition at line 452 of file G4INCLStore.hh.
Referenced by loadParticles().
outgoing
ParticleList G4INCL::Store::outgoing private
List of outgoing particles.
Definition at line 427 of file G4INCLStore.hh.
Referenced by clearOutgoing().
particleAvatarConnections
std::multimap<Particle*, IAvatar*> G4INCL::Store::particleAvatarConnections private
Map particle -> [avatar].
Definition at line 399 of file G4INCLStore.hh.
Referenced by clearAvatars(), connectAvatarToParticle(), disconnectAvatarFromParticle(), and particleHasBeenUpdated().
theBook
Book G4INCL::Store::theBook private
The Book object keeps track of global counters.
Definition at line 442 of file G4INCLStore.hh.
Referenced by loadParticles(), and ~Store().
theConfig
const Config* G4INCL::Store::theConfig private
Pointer to the Config object.
Definition at line 462 of file G4INCLStore.hh.
The documentation for this class was generated from the following files:
source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLStore.hh
source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLStore.cc