Geant4: Par01EnergySpot Class Reference
Par01EnergySpot Class Reference
#include <Par01EnergySpot.hh>
Public Member Functions
Par01EnergySpot ()
Par01EnergySpot (const G4ThreeVector &point, G4double E)
~Par01EnergySpot ()
void SetEnergy (const G4double &E)
G4double GetEnergy () const
void SetPosition (const G4ThreeVector &point)
G4ThreeVector GetPosition () const
G4bool operator== (const Par01EnergySpot &eSpot) const
void Draw (G4Colour *color=0)
void Print ()
Private Attributes
G4double fEnergy
G4ThreeVector fPoint
Detailed Description
Definition at line 37 of file Par01EnergySpot.hh.
Constructor & Destructor Documentation
Par01EnergySpot() [1/2]
Par01EnergySpot::Par01EnergySpot ()
Definition at line 42 of file Par01EnergySpot.cc.
Par01EnergySpot() [2/2]
Par01EnergySpot::Par01EnergySpot (const G4ThreeVector & point, G4double E)
Definition at line 47 of file Par01EnergySpot.cc.
~Par01EnergySpot()
Par01EnergySpot::~Par01EnergySpot ()
Definition at line 55 of file Par01EnergySpot.cc.
Member Function Documentation
Draw()
void Par01EnergySpot::Draw (G4Colour * color = 0)
Definition at line 60 of file Par01EnergySpot.cc.
GetEnergy()
G4double Par01EnergySpot::GetEnergy () const inline
Definition at line 45 of file Par01EnergySpot.hh.
Referenced by Par01PionShowerModel::FillFakeStep(), and Par01EMShowerModel::FillFakeStep().
GetPosition()
G4ThreeVector Par01EnergySpot::GetPosition () const inline
Definition at line 48 of file Par01EnergySpot.hh.
Referenced by Par01PionShowerModel::FillFakeStep(), and Par01EMShowerModel::FillFakeStep().
operator==()
G4bool Par01EnergySpot::operator== (const Par01EnergySpot & eSpot) const inline
Definition at line 50 of file Par01EnergySpot.hh.
Print()
void Par01EnergySpot::Print (void)
Definition at line 94 of file Par01EnergySpot.cc.
SetEnergy()
void Par01EnergySpot::SetEnergy (const G4double & E) inline
Definition at line 44 of file Par01EnergySpot.hh.
Referenced by Par01PionShowerModel::Explode(), and Par01EMShowerModel::Explode().
SetPosition()
void Par01EnergySpot::SetPosition (const G4ThreeVector & point) inline
Definition at line 47 of file Par01EnergySpot.hh.
Referenced by Par01PionShowerModel::Explode(), and Par01EMShowerModel::Explode().
Field Documentation
fEnergy
G4double Par01EnergySpot::fEnergy private
Definition at line 62 of file Par01EnergySpot.hh.
Referenced by GetEnergy(), operator==(), Par01EnergySpot(), Print(), and SetEnergy().
fPoint
G4ThreeVector Par01EnergySpot::fPoint private
Definition at line 63 of file Par01EnergySpot.hh.
Referenced by Draw(), GetPosition(), operator==(), Par01EnergySpot(), Print(), and SetPosition().
The documentation for this class was generated from the following files:
examples/extended/parameterisations/Par01/include/Par01EnergySpot.hh
examples/extended/parameterisations/Par01/src/Par01EnergySpot.cc