Geant4: G4BoundingEnvelope Class Reference
G4BoundingEnvelope Class Reference
#include <G4BoundingEnvelope.hh>
Public Member Functions
G4BoundingEnvelope (const G4ThreeVector &pMin, const G4ThreeVector &pMax)
G4BoundingEnvelope (const std::vector< const G4ThreeVectorList * > &polygons)
G4BoundingEnvelope (const G4ThreeVector &pMin, const G4ThreeVector &pMax, const std::vector< const G4ThreeVectorList * > &polygons)
~G4BoundingEnvelope ()
G4bool BoundingBoxVsVoxelLimits (const EAxis pAxis, const G4VoxelLimits &pVoxelLimits, const G4Transform3D &pTransform3D, G4double &pMin, G4double &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimits, const G4Transform3D &pTransform3D, G4double &pMin, G4double &pMax) const
Private Member Functions
void CheckBoundingBox ()
void CheckBoundingPolygons ()
G4double FindScaleFactor (const G4Transform3D &pTransform3D) const
void TransformVertices (const G4Transform3D &pTransform3D, std::vector< G4Polygon3D * > &pBases) const
void GetPrismAABB (const G4Polygon3D &pBaseA, const G4Polygon3D &pBaseB, G4Segment3D &pAABB) const
void CreateListOfEdges (const G4Polygon3D &baseA, const G4Polygon3D &baseB, std::vector< G4Segment3D > &pEdges) const
void CreateListOfPlanes (const G4Polygon3D &baseA, const G4Polygon3D &baseB, std::vector< G4Plane3D > &pPlanes) const
G4bool ClipEdgesByVoxel (const std::vector< G4Segment3D > &pEdges, const G4VoxelLimits &pLimits, G4Segment3D &pExtent) const
void ClipVoxelByPlanes (G4int pBits, const G4VoxelLimits &pLimits, const std::vector< G4Plane3D > &pPlanes, const G4Segment3D &pAABB, G4Segment3D &pExtent) const
Private Attributes
G4ThreeVector fMin
G4ThreeVector fMax
const std::vector< const G4ThreeVectorList * > * fPolygons
Detailed Description
Definition at line 64 of file G4BoundingEnvelope.hh.
Constructor & Destructor Documentation
G4BoundingEnvelope() [1/3]
G4BoundingEnvelope::G4BoundingEnvelope (const G4ThreeVector & pMin, const G4ThreeVector & pMax)
Definition at line 50 of file G4BoundingEnvelope.cc.
G4BoundingEnvelope() [2/3]
G4BoundingEnvelope::G4BoundingEnvelope (const std::vector< const G4ThreeVectorList * > & polygons)
Definition at line 64 of file G4BoundingEnvelope.cc.
G4BoundingEnvelope() [3/3]
G4BoundingEnvelope::G4BoundingEnvelope (const G4ThreeVector & pMin, const G4ThreeVector & pMax, const std::vector< const G4ThreeVectorList * > & polygons)
Definition at line 105 of file G4BoundingEnvelope.cc.
~G4BoundingEnvelope()
G4BoundingEnvelope::~G4BoundingEnvelope ()
Definition at line 120 of file G4BoundingEnvelope.cc.
Member Function Documentation
BoundingBoxVsVoxelLimits()
G4bool G4BoundingEnvelope::BoundingBoxVsVoxelLimits (const EAxis pAxis, const G4VoxelLimits & pVoxelLimits, const G4Transform3D & pTransform3D, G4double & pMin, G4double & pMax) const
Definition at line 197 of file G4BoundingEnvelope.cc.
Referenced by G4EllipticalTube::CalculateExtent(), G4Tet::CalculateExtent(), G4Orb::CalculateExtent(), G4GenericPolycone::CalculateExtent(), G4CutTubs::CalculateExtent(), G4Polycone::CalculateExtent(), G4Polyhedra::CalculateExtent(), G4EllipticalCone::CalculateExtent(), G4Trd::CalculateExtent(), G4GenericTrap::CalculateExtent(), G4Para::CalculateExtent(), G4Tubs::CalculateExtent(), G4Cons::CalculateExtent(), G4Torus::CalculateExtent(), G4ExtrudedSolid::CalculateExtent(), G4TessellatedSolid::CalculateExtent(), and G4Trap::CalculateExtent().
CalculateExtent()
G4bool G4BoundingEnvelope::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimits, const G4Transform3D & pTransform3D, G4double & pMin, G4double & pMax) const
Definition at line 282 of file G4BoundingEnvelope.cc.
Referenced by G4ScaledSolid::CalculateExtent(), G4EllipticalTube::CalculateExtent(), G4Box::CalculateExtent(), G4VTwistedFaceted::CalculateExtent(), G4Tet::CalculateExtent(), G4Orb::CalculateExtent(), G4Ellipsoid::CalculateExtent(), G4GenericPolycone::CalculateExtent(), G4Hype::CalculateExtent(), G4Paraboloid::CalculateExtent(), G4CutTubs::CalculateExtent(), G4TwistedTubs::CalculateExtent(), G4Polycone::CalculateExtent(), G4Polyhedra::CalculateExtent(), G4EllipticalCone::CalculateExtent(), G4Trd::CalculateExtent(), G4MultiUnion::CalculateExtent(), G4GenericTrap::CalculateExtent(), G4Para::CalculateExtent(), G4Tubs::CalculateExtent(), G4Cons::CalculateExtent(), G4Torus::CalculateExtent(), G4ExtrudedSolid::CalculateExtent(), G4Sphere::CalculateExtent(), G4TessellatedSolid::CalculateExtent(), and G4Trap::CalculateExtent().
CheckBoundingBox()
void G4BoundingEnvelope::CheckBoundingBox () private
Definition at line 128 of file G4BoundingEnvelope.cc.
Referenced by G4BoundingEnvelope().
CheckBoundingPolygons()
void G4BoundingEnvelope::CheckBoundingPolygons () private
Definition at line 146 of file G4BoundingEnvelope.cc.
Referenced by G4BoundingEnvelope().
ClipEdgesByVoxel()
G4bool G4BoundingEnvelope::ClipEdgesByVoxel (const std::vector< G4Segment3D > & pEdges, const G4VoxelLimits & pLimits, G4Segment3D & pExtent) const private
Definition at line 850 of file G4BoundingEnvelope.cc.
Referenced by CalculateExtent().
ClipVoxelByPlanes()
void G4BoundingEnvelope::ClipVoxelByPlanes (G4int pBits, const G4VoxelLimits & pLimits, const std::vector< G4Plane3D > & pPlanes, const G4Segment3D & pAABB, G4Segment3D & pExtent) const private
Definition at line 968 of file G4BoundingEnvelope.cc.
Referenced by CalculateExtent().
CreateListOfEdges()
void G4BoundingEnvelope::CreateListOfEdges (const G4Polygon3D & baseA, const G4Polygon3D & baseB, std::vector< G4Segment3D > & pEdges) const private
Definition at line 704 of file G4BoundingEnvelope.cc.
Referenced by CalculateExtent().
CreateListOfPlanes()
void G4BoundingEnvelope::CreateListOfPlanes (const G4Polygon3D & baseA, const G4Polygon3D & baseB, std::vector< G4Plane3D > & pPlanes) const private
Definition at line 752 of file G4BoundingEnvelope.cc.
Referenced by CalculateExtent().
FindScaleFactor()
G4double G4BoundingEnvelope::FindScaleFactor (const G4Transform3D & pTransform3D) const private
Definition at line 577 of file G4BoundingEnvelope.cc.
Referenced by BoundingBoxVsVoxelLimits(), and CalculateExtent().
GetPrismAABB()
void G4BoundingEnvelope::GetPrismAABB (const G4Polygon3D & pBaseA, const G4Polygon3D & pBaseB, G4Segment3D & pAABB) const private
Definition at line 655 of file G4BoundingEnvelope.cc.
Referenced by CalculateExtent().
TransformVertices()
void G4BoundingEnvelope::TransformVertices (const G4Transform3D & pTransform3D, std::vector< G4Polygon3D * > & pBases) const private
Definition at line 604 of file G4BoundingEnvelope.cc.
Referenced by CalculateExtent().
Field Documentation
fMax
G4ThreeVector G4BoundingEnvelope::fMax private
Definition at line 145 of file G4BoundingEnvelope.hh.
Referenced by BoundingBoxVsVoxelLimits(), CalculateExtent(), CheckBoundingBox(), G4BoundingEnvelope(), and TransformVertices().
fMin
G4ThreeVector G4BoundingEnvelope::fMin private
Definition at line 145 of file G4BoundingEnvelope.hh.
Referenced by BoundingBoxVsVoxelLimits(), CalculateExtent(), CheckBoundingBox(), G4BoundingEnvelope(), and TransformVertices().
fPolygons
const std::vector<const G4ThreeVectorList*>* G4BoundingEnvelope::fPolygons private
Definition at line 148 of file G4BoundingEnvelope.hh.
Referenced by CalculateExtent(), CheckBoundingPolygons(), G4BoundingEnvelope(), and TransformVertices().
The documentation for this class was generated from the following files:
source/geometry/management/include/G4BoundingEnvelope.hh
source/geometry/management/src/G4BoundingEnvelope.cc