Geant4: G4VUserDetectorConstruction Class Reference
G4VUserDetectorConstruction Class Reference abstract
#include <G4VUserDetectorConstruction.hh>
Public Member Functions
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()=0
virtual void ConstructSDandField ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Protected Member Functions
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Private Attributes
std::vector< G4VUserParallelWorld * > parallelWorld
Detailed Description
Definition at line 49 of file G4VUserDetectorConstruction.hh.
Constructor & Destructor Documentation
G4VUserDetectorConstruction()
G4VUserDetectorConstruction::G4VUserDetectorConstruction ()
Definition at line 41 of file G4VUserDetectorConstruction.cc.
~G4VUserDetectorConstruction()
G4VUserDetectorConstruction::~G4VUserDetectorConstruction () virtual
Definition at line 44 of file G4VUserDetectorConstruction.cc.
Member Function Documentation
CloneF()
void G4VUserDetectorConstruction::CloneF () virtual
Definition at line 108 of file G4VUserDetectorConstruction.cc.
CloneSD()
void G4VUserDetectorConstruction::CloneSD () virtual
Definition at line 154 of file G4VUserDetectorConstruction.cc.
Construct()
virtual G4VPhysicalVolume* G4VUserDetectorConstruction::Construct () pure virtual
Implemented in CexmcSetup, XrayFluoGeometry, RE02DetectorConstruction, DetectorConstruction, GammaRayTelDetectorConstruction, TSDetectorConstruction, DetectorConstruction, CML2WorldConstruction, XrayFluoDetectorConstruction, DetectorConstruction, F01DetectorConstruction, F02DetectorConstruction, F03DetectorConstruction, DicomDetectorConstruction, XrayFluoMercuryDetectorConstruction, UltraDetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DMXDetectorConstruction, DetectorConstruction, ExN03DetectorConstruction, PurgMagDetectorConstruction, XrayFluoPlaneDetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, doiPETDetectorConstruction, DetectorConstruction, Collimator100BeamLine, Collimator40BeamLine, Collimator50BeamLine, Collimator60BeamLine, Collimator70BeamLine, Collimator80BeamLine, XrayTelDetectorConstruction, DetectorConstruction, ExErrorDetectorConstruction, DetectorConstruction, WLSDetectorConstruction, LaserDrivenBeamLine, DetectorConstruction, DetectorConstruction, DetectorConstruction, G02DetectorConstruction, RMC01DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, B4cDetectorConstruction, B4dDetectorConstruction, B4dDetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, FCALTestbeamSetup, DetectorConstruction, DetectorConstruction, DetectorConstruction, B4DetectorConstruction, B4DetectorConstruction, F04DetectorConstruction, F06DetectorConstruction, DetectorConstruction, ExN02DetectorConstruction, Par02DetectorConstruction, G03DetectorConstruction, ExP01DetectorConstruction, F05DetectorConstruction, FFDetectorConstruction, DetectorConstruction, LXeDetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, BrachyDetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, B5DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, RE04DetectorConstruction, eRositaDetectorConstruction, B2aDetectorConstruction, B2bDetectorConstruction, DetectorConstruction0, DetectorConstruction0, DetectorConstruction, ExUCNDetectorConstruction, DetectorConstruction0, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, ElectronBenchmarkDetector, B2bDetectorConstruction, DetectorConstruction, DetectorConstruction, TrentoPassiveProtonBeamLine, GB04DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DicomPartialDetectorConstruction, DetectorConstruction, ExN01DetectorConstruction, DetectorConstruction, PassiveCarbonBeamLine, PassiveProtonBeamLine, DetectorConstruction, GB01DetectorConstruction, GB02DetectorConstruction, GB06DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, MyDetectorConstruction, DetectorConstruction, G3toG4DetectorConstruction, DetectorConstruction, B3DetectorConstruction, B3DetectorConstruction, B3DetectorConstruction, DetectorConstruction, ExGflashDetectorConstruction, GammaKnifeDetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, ExP02DetConstrReader, RE06DetectorConstruction, B01DetectorConstruction, B02DetectorConstruction, GB03DetectorConstruction, GB05DetectorConstruction, GeometryConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, OpNoviceDetectorConstruction, G01DetectorConstruction, DetectorConstruction, EzDetectorConstruction, QDetectorConstruction, QDetectorConstruction, ExN04DetectorConstruction, ExP02DetectorConstruction, RE05DetectorConstruction, B1DetectorConstruction, B1DetectorConstruction, B03DetectorConstruction, Par01DetectorConstruction, G04DetectorConstruction, ExTGDetectorConstruction, ExTGDetectorConstructionWithCpp, ExTGDetectorConstructionWithCuts, ExTGDetectorConstructionWithSD, RE01DetectorConstruction, RE03DetectorConstruction, B1DetectorConstruction, G4HumanPhantomConstruction, DetectorConstruction, XDetectorConstruction, pyG4VUserDetectorConstruction::CB_G4VUserDetectorConstruction, ExN04DetectorConstruction, CCalDetectorConstruction, H02DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, and DetectorConstruction.
Referenced by export_G4VUserDetectorConstruction(), G4RunManager::InitializeGeometry(), and G4ErrorRunManagerHelper::SetUserInitialization().
ConstructParallelGeometries()
G4int G4VUserDetectorConstruction::ConstructParallelGeometries ()
Definition at line 64 of file G4VUserDetectorConstruction.cc.
Referenced by G4RunManager::InitializeGeometry().
ConstructParallelSD()
void G4VUserDetectorConstruction::ConstructParallelSD ()
Definition at line 76 of file G4VUserDetectorConstruction.cc.
Referenced by G4WorkerRunManager::InitializeGeometry(), and G4RunManager::InitializeGeometry().
ConstructSDandField()
void G4VUserDetectorConstruction::ConstructSDandField () virtual
Reimplemented in RE02DetectorConstruction, DetectorConstruction, DicomDetectorConstruction, TSDetectorConstruction, GammaRayTelDetectorConstruction, XrayFluoDetectorConstruction, F01DetectorConstruction, F02DetectorConstruction, F03DetectorConstruction, XrayFluoMercuryDetectorConstruction, UltraDetectorConstruction, DetectorConstruction, DetectorConstruction, DMXDetectorConstruction, XrayFluoPlaneDetectorConstruction, DetectorConstruction, PurgMagDetectorConstruction, DetectorConstruction, WLSDetectorConstruction, DetectorConstruction, LaserDrivenBeamLine, DetectorConstruction, DetectorConstruction, B01DetectorConstruction, DetectorConstruction, B4cDetectorConstruction, B4dDetectorConstruction, B4dDetectorConstruction, DetectorConstruction, F04DetectorConstruction, Par02DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, FCALTestbeamSetup, B4DetectorConstruction, B4DetectorConstruction, F06DetectorConstruction, DetectorConstruction, F05DetectorConstruction, DetectorConstruction, LXeDetectorConstruction, DetectorConstruction, ElectronBenchmarkDetector, B5DetectorConstruction, DetectorConstruction, B2aDetectorConstruction, B2bDetectorConstruction, ExUCNDetectorConstruction, B2bDetectorConstruction, DetectorConstruction, GB04DetectorConstruction, DetectorConstruction, DetectorConstruction, GB01DetectorConstruction, GB02DetectorConstruction, GB06DetectorConstruction, DetectorConstruction, DetectorConstruction, G4HumanPhantomConstruction, B3DetectorConstruction, B3DetectorConstruction, B3DetectorConstruction, ExGflashDetectorConstruction, RE06DetectorConstruction, GB03DetectorConstruction, GB05DetectorConstruction, RE05DetectorConstruction, DetectorConstruction, Par01DetectorConstruction, G04DetectorConstruction, ExTGDetectorConstructionWithSD, RE01DetectorConstruction, RE03DetectorConstruction, XDetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, and DetectorConstruction.
Definition at line 94 of file G4VUserDetectorConstruction.cc.
Referenced by G4WorkerRunManager::InitializeGeometry(), and G4RunManager::InitializeGeometry().
GetNumberOfParallelWorld()
G4int G4VUserDetectorConstruction::GetNumberOfParallelWorld () const
Definition at line 83 of file G4VUserDetectorConstruction.cc.
Referenced by GetParallelWorld().
GetParallelWorld()
G4VUserParallelWorld * G4VUserDetectorConstruction::GetParallelWorld (G4int i) const
Definition at line 86 of file G4VUserDetectorConstruction.cc.
Referenced by RE06DetectorConstruction::SetSerialGeometry(), and HadrontherapyDetectorConstruction::UpdateGeometry().
RegisterParallelWorld()
void G4VUserDetectorConstruction::RegisterParallelWorld (G4VUserParallelWorld * aPW)
Definition at line 47 of file G4VUserDetectorConstruction.cc.
Referenced by LaserDrivenBeamLine::LaserDrivenBeamLine(), main(), PassiveCarbonBeamLine::PassiveCarbonBeamLine(), PassiveProtonBeamLine::PassiveProtonBeamLine(), and TrentoPassiveProtonBeamLine::TrentoPassiveProtonBeamLine().
SetSensitiveDetector() [1/2]
void G4VUserDetectorConstruction::SetSensitiveDetector (const G4String & logVolName, G4VSensitiveDetector * aSD, G4bool multi = false) protected
Definition at line 205 of file G4VUserDetectorConstruction.cc.
Referenced by H02DetectorConstruction::Construct(), XDetectorConstruction::ConstructSDandField(), ExTGDetectorConstructionWithSD::ConstructSDandField(), RE01DetectorConstruction::ConstructSDandField(), RE05DetectorConstruction::ConstructSDandField(), G4HumanPhantomConstruction::ConstructSDandField(), B3DetectorConstruction::ConstructSDandField(), B2aDetectorConstruction::ConstructSDandField(), B2bDetectorConstruction::ConstructSDandField(), ElectronBenchmarkDetector::ConstructSDandField(), LXeDetectorConstruction::ConstructSDandField(), FCALTestbeamSetup::ConstructSDandField(), B4cDetectorConstruction::ConstructSDandField(), B4dDetectorConstruction::ConstructSDandField(), B01DetectorConstruction::ConstructSDandField(), WLSDetectorConstruction::ConstructSDandField(), XrayFluoPlaneDetectorConstruction::ConstructSDandField(), DMXDetectorConstruction::ConstructSDandField(), UltraDetectorConstruction::ConstructSDandField(), XrayFluoMercuryDetectorConstruction::ConstructSDandField(), F03DetectorConstruction::ConstructSDandField(), F02DetectorConstruction::ConstructSDandField(), F01DetectorConstruction::ConstructSDandField(), XrayFluoDetectorConstruction::ConstructSDandField(), GammaRayTelDetectorConstruction::ConstructSDandField(), TSDetectorConstruction::ConstructSDandField(), DicomDetectorConstruction::ConstructSDandField(), MyDetectorConstruction::SetSDtoScoreVoxel(), GB03DetectorConstruction::SetupDetectors(), and RE06DetectorConstruction::SetupDetectors().
SetSensitiveDetector() [2/2]
void G4VUserDetectorConstruction::SetSensitiveDetector (G4LogicalVolume * logVol, G4VSensitiveDetector * aSD) protected
Definition at line 240 of file G4VUserDetectorConstruction.cc.
Field Documentation
parallelWorld
std::vector<G4VUserParallelWorld*> G4VUserDetectorConstruction::parallelWorld private
Definition at line 73 of file G4VUserDetectorConstruction.hh.
Referenced by ConstructParallelGeometries(), ConstructParallelSD(), GetNumberOfParallelWorld(), GetParallelWorld(), and RegisterParallelWorld().
The documentation for this class was generated from the following files:
source/run/include/G4VUserDetectorConstruction.hh
source/run/src/G4VUserDetectorConstruction.cc