Geant4: G4eplusTo3GammaOKVIModel Class Reference
G4eplusTo3GammaOKVIModel Class Reference
#include <G4eplusTo3GammaOKVIModel.hh>
Public Member Functions
G4eplusTo3GammaOKVIModel (const G4ParticleDefinition *p=nullptr, const G4String &nam="eplus3ggOKVI")
virtual ~G4eplusTo3GammaOKVIModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &) final
G4double ComputeCrossSectionPerElectron (G4double kinEnergy)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0., G4double cutEnergy=0., G4double maxEnergy=DBL_MAX) final
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX) final
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin=0.0, G4double maxEnergy=DBL_MAX) final
G4double ComputeF (G4double fr1, G4double fr2, G4double fr3, G4double kinEnergy)
G4double ComputeF0 (G4double fr1, G4double fr2, G4double fr3)
G4double ComputeFS (G4double fr1, G4double fr2, G4double fr3, G4double kinEnergy)
void SetDelta (G4double val)
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy)
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Private Member Functions
G4eplusTo3GammaOKVIModel & operator= (const G4eplusTo3GammaOKVIModel &right)=delete
G4eplusTo3GammaOKVIModel (const G4eplusTo3GammaOKVIModel &)=delete
Private Attributes
G4double fDelta
const G4ParticleDefinition * theGamma
G4ParticleChangeForGamma * fParticleChange
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
Detailed Description
Definition at line 53 of file G4eplusTo3GammaOKVIModel.hh.
Constructor & Destructor Documentation
G4eplusTo3GammaOKVIModel() [1/2]
G4eplusTo3GammaOKVIModel::G4eplusTo3GammaOKVIModel (const G4ParticleDefinition * p = nullptr, const G4String & nam = "eplus3ggOKVI") explicit
Definition at line 60 of file G4eplusTo3GammaOKVIModel.cc.
~G4eplusTo3GammaOKVIModel()
G4eplusTo3GammaOKVIModel::~G4eplusTo3GammaOKVIModel () virtual
Definition at line 70 of file G4eplusTo3GammaOKVIModel.cc.
G4eplusTo3GammaOKVIModel() [2/2]
G4eplusTo3GammaOKVIModel::G4eplusTo3GammaOKVIModel (const G4eplusTo3GammaOKVIModel &) private delete
Member Function Documentation
ComputeCrossSectionPerAtom()
G4double G4eplusTo3GammaOKVIModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * , G4double kinEnergy, G4double Z, G4double A = 0., G4double cutEnergy = 0., G4double maxEnergy = DBL_MAX) final virtual
Reimplemented from G4VEmModel.
Definition at line 203 of file G4eplusTo3GammaOKVIModel.cc.
ComputeCrossSectionPerElectron()
G4double G4eplusTo3GammaOKVIModel::ComputeCrossSectionPerElectron (G4double kinEnergy)
Definition at line 182 of file G4eplusTo3GammaOKVIModel.cc.
Referenced by ComputeCrossSectionPerAtom(), CrossSectionPerVolume(), G4eplusTo2GammaOKVIModel::Initialise(), and G4eplusTo2GammaOKVIModel::SampleSecondaries().
ComputeF()
G4double G4eplusTo3GammaOKVIModel::ComputeF (G4double fr1, G4double fr2, G4double fr3, G4double kinEnergy)
Definition at line 86 of file G4eplusTo3GammaOKVIModel.cc.
Referenced by ComputeFS().
ComputeF0()
G4double G4eplusTo3GammaOKVIModel::ComputeF0 (G4double fr1, G4double fr2, G4double fr3)
Definition at line 130 of file G4eplusTo3GammaOKVIModel.cc.
ComputeFS()
G4double G4eplusTo3GammaOKVIModel::ComputeFS (G4double fr1, G4double fr2, G4double fr3, G4double kinEnergy)
Definition at line 163 of file G4eplusTo3GammaOKVIModel.cc.
Referenced by SampleSecondaries().
CrossSectionPerVolume()
G4double G4eplusTo3GammaOKVIModel::CrossSectionPerVolume (const G4Material * material, const G4ParticleDefinition * , G4double kineticEnergy, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) final virtual
Reimplemented from G4VEmModel.
Definition at line 218 of file G4eplusTo3GammaOKVIModel.cc.
Initialise()
void G4eplusTo3GammaOKVIModel::Initialise (const G4ParticleDefinition * , const G4DataVector &) final virtual
Implements G4VEmModel.
Definition at line 75 of file G4eplusTo3GammaOKVIModel.cc.
Referenced by G4eplusTo2GammaOKVIModel::Initialise().
operator=()
G4eplusTo3GammaOKVIModel& G4eplusTo3GammaOKVIModel::operator= (const G4eplusTo3GammaOKVIModel & right) private delete
SampleSecondaries()
void G4eplusTo3GammaOKVIModel::SampleSecondaries (std::vector< G4DynamicParticle * > * vdp, const G4MaterialCutsCouple * , const G4DynamicParticle * dp, G4double tmin = 0.0, G4double maxEnergy = DBL_MAX) final virtual
Implements G4VEmModel.
Definition at line 237 of file G4eplusTo3GammaOKVIModel.cc.
Referenced by G4eplusTo2GammaOKVIModel::SampleSecondaries().
SetDelta()
void G4eplusTo3GammaOKVIModel::SetDelta (G4double val) inline
Definition at line 96 of file G4eplusTo3GammaOKVIModel.hh.
Referenced by G4eplusTo2GammaOKVIModel::Initialise(), and G4eplusTo2GammaOKVIModel::SampleSecondaries().
Field Documentation
fDelta
G4double G4eplusTo3GammaOKVIModel::fDelta private
Definition at line 105 of file G4eplusTo3GammaOKVIModel.hh.
Referenced by ComputeCrossSectionPerElectron(), and SetDelta().
fParticleChange
G4ParticleChangeForGamma* G4eplusTo3GammaOKVIModel::fParticleChange private
Definition at line 107 of file G4eplusTo3GammaOKVIModel.hh.
Referenced by G4eplusTo3GammaOKVIModel(), Initialise(), and SampleSecondaries().
theGamma
const G4ParticleDefinition* G4eplusTo3GammaOKVIModel::theGamma private
Definition at line 106 of file G4eplusTo3GammaOKVIModel.hh.
Referenced by G4eplusTo3GammaOKVIModel(), and SampleSecondaries().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/standard/include/G4eplusTo3GammaOKVIModel.hh
source/processes/electromagnetic/standard/src/G4eplusTo3GammaOKVIModel.cc