Geant4: G4INCL::Particle Class Reference
G4INCL::Particle Class Reference
#include <G4INCLParticle.hh>
Public Member Functions
Particle ()
Particle (ParticleType t, G4double energy, ThreeVector const &momentum, ThreeVector const &position)
Particle (ParticleType t, ThreeVector const &momentum, ThreeVector const &position)
virtual ~Particle ()
Particle (const Particle &rhs)
Copy constructor.
Particle & operator= (const Particle &rhs)
Assignment operator.
G4INCL::ParticleType getType () const
Get the particle type.
virtual G4INCL::ParticleSpecies getSpecies () const
Get the particle species.
void setType (ParticleType t)
G4bool isNucleon () const
Is this a nucleon?
ParticipantType getParticipantType () const
void setParticipantType (ParticipantType const p)
G4bool isParticipant () const
G4bool isTargetSpectator () const
G4bool isProjectileSpectator () const
virtual void makeParticipant ()
virtual void makeTargetSpectator ()
virtual void makeProjectileSpectator ()
G4bool isPion () const
Is this a pion?
G4bool isEta () const
Is this an eta?
G4bool isOmega () const
Is this an omega?
G4bool isEtaPrime () const
Is this an etaprime?
G4bool isPhoton () const
Is this a photon?
G4bool isResonance () const
Is it a resonance?
G4bool isDelta () const
Is it a Delta?
G4bool isSigma () const
Is this a Sigma?
G4bool isKaon () const
Is this a Kaon?
G4bool isAntiKaon () const
Is this an antiKaon?
G4bool isLambda () const
Is this a Lambda?
G4bool isNucleonorLambda () const
Is this a Nucleon or a Lambda?
G4bool isHyperon () const
Is this an Hyperon?
G4bool isMeson () const
Is this a Meson?
G4bool isBaryon () const
Is this a Baryon?
G4bool isStrange () const
Is this an Strange?
G4int getA () const
Returns the baryon number.
G4int getZ () const
Returns the charge number.
G4int getS () const
Returns the strangeness number.
G4double getBeta () const
ThreeVector boostVector () const
Returns a three vector we can give to the boost() -method.
void boost (const ThreeVector &aBoostVector)
Boost the particle using a boost vector.
void lorentzContract (const ThreeVector &aBoostVector, const ThreeVector &refPos)
Lorentz-contract the particle position around some center.
G4double getMass () const
Get the cached particle mass.
G4double getINCLMass () const
Get the INCL particle mass.
virtual G4double getTableMass () const
Get the tabulated particle mass.
G4double getRealMass () const
Get the real particle mass.
void setRealMass ()
Set the mass of the Particle to its real mass.
void setTableMass ()
Set the mass of the Particle to its table mass.
void setINCLMass ()
Set the mass of the Particle to its table mass.
G4double getEmissionQValueCorrection (const G4int AParent, const G4int ZParent) const
Computes correction on the emission Q-value.
G4double getTransferQValueCorrection (const G4int AFrom, const G4int ZFrom, const G4int ATo, const G4int ZTo) const
Computes correction on the transfer Q-value.
G4double getEmissionQValueCorrection (const G4int AParent, const G4int ZParent, const G4int SParent) const
Computes correction on the emission Q-value for hypernuclei.
G4double getTransferQValueCorrection (const G4int AFrom, const G4int ZFrom, const G4int SFrom, const G4int ATo, const G4int ZTo, const G4int STo) const
Computes correction on the transfer Q-value for hypernuclei.
G4double getInvariantMass () const
Get the the particle invariant mass.
G4double getKineticEnergy () const
Get the particle kinetic energy.
G4double getPotentialEnergy () const
Get the particle potential energy.
void setPotentialEnergy (G4double v)
Set the particle potential energy.
G4double getEnergy () const
Get the energy of the particle in MeV.
void setMass (G4double mass)
Set the mass of the particle in MeV/c^2.
void setEnergy (G4double energy)
Set the energy of the particle in MeV.
const G4INCL::ThreeVector & getMomentum () const
Get the momentum vector.
virtual G4INCL::ThreeVector getAngularMomentum () const
Get the angular momentum w.r.t.
virtual void setMomentum (const G4INCL::ThreeVector &momentum)
Set the momentum vector.
const G4INCL::ThreeVector & getPosition () const
Set the position vector.
virtual void setPosition (const G4INCL::ThreeVector &position)
G4double getHelicity ()
void setHelicity (G4double h)
void propagate (G4double step)
G4int getNumberOfCollisions () const
Return the number of collisions undergone by the particle.
void setNumberOfCollisions (G4int n)
Set the number of collisions undergone by the particle.
void incrementNumberOfCollisions ()
Increment the number of collisions undergone by the particle.
G4int getNumberOfDecays () const
Return the number of decays undergone by the particle.
void setNumberOfDecays (G4int n)
Set the number of decays undergone by the particle.
void incrementNumberOfDecays ()
Increment the number of decays undergone by the particle.
void setOutOfWell ()
Mark the particle as out of its potential well.
G4bool isOutOfWell () const
Check if the particle is out of its potential well.
void setEmissionTime (G4double t)
G4double getEmissionTime ()
ThreeVector getTransversePosition () const
Transverse component of the position w.r.t.
ThreeVector getLongitudinalPosition () const
Longitudinal component of the position w.r.t.
const ThreeVector & adjustMomentumFromEnergy ()
Rescale the momentum to match the total energy.
G4double adjustEnergyFromMomentum ()
Recompute the energy to match the momentum.
G4bool isCluster () const
void setFrozenMomentum (const ThreeVector &momentum)
Set the frozen particle momentum.
void setFrozenEnergy (const G4double energy)
Set the frozen particle momentum.
ThreeVector getFrozenMomentum () const
Get the frozen particle momentum.
G4double getFrozenEnergy () const
Get the frozen particle momentum.
ThreeVector getPropagationVelocity () const
Get the propagation velocity of the particle.
void freezePropagation ()
Freeze particle propagation.
void thawPropagation ()
Unfreeze particle propagation.
virtual void rotatePositionAndMomentum (const G4double angle, const ThreeVector &axis)
Rotate the particle position and momentum.
virtual void rotatePosition (const G4double angle, const ThreeVector &axis)
Rotate the particle position.
virtual void rotateMomentum (const G4double angle, const ThreeVector &axis)
Rotate the particle momentum.
std::string print () const
std::string dump () const
long getID () const
const ParticleList * getParticles () const
Return a NULL pointer.
G4double getReflectionMomentum () const
Return the reflection momentum.
void setUncorrelatedMomentum (const G4double p)
Set the uncorrelated momentum.
void rpCorrelate ()
Make the particle follow a strict r-p correlation.
void rpDecorrelate ()
Make the particle not follow a strict r-p correlation.
G4double getCosRPAngle () const
Get the cosine of the angle between position and momentum.
G4double getParticleBias () const
Get the particle bias.
void setParticleBias (G4double ParticleBias)
Set the particle bias.
std::vector< G4int > getBiasCollisionVector () const
Get the vector list of biased vertices on the particle path.
void setBiasCollisionVector (std::vector< G4int > BiasCollisionVector)
Set the vector list of biased vertices on the particle path.
G4int getNumberOfKaon () const
Number of Kaon inside de nucleus.
void setNumberOfKaon (const G4int NK)
Static Public Member Functions
static G4double getTotalBias ()
General bias vector function.
static void setINCLBiasVector (std::vector< G4double > NewVector)
static void FillINCLBiasVector (G4double newBias)
static G4double getBiasFromVector (std::vector< G4int > VectorBias)
static std::vector< G4int > MergeVectorBias (Particle const *const p1, Particle const *const p2)
static std::vector< G4int > MergeVectorBias (std::vector< G4int > p1, Particle const *const p2)
Static Public Attributes
static std::vector< G4double > INCLBiasVector
Time ordered vector of all bias applied.
static G4ThreadLocal G4int nextBiasedCollisionID = 0
Protected Member Functions
void swap (Particle &rhs)
Helper method for the assignment operator.
Protected Attributes
G4int theZ
G4int theA
G4int theS
ParticipantType theParticipantType
G4INCL::ParticleType theType
G4double theEnergy
G4double * thePropagationEnergy
G4double theFrozenEnergy
G4INCL::ThreeVector theMomentum
G4INCL::ThreeVector * thePropagationMomentum
G4INCL::ThreeVector theFrozenMomentum
G4INCL::ThreeVector thePosition
G4int nCollisions
G4int nDecays
G4double thePotentialEnergy
long ID
G4bool rpCorrelated
G4double uncorrelatedMomentum
G4double theParticleBias
G4int theNKaon
The number of Kaons inside the nucleus (update during the cascade)
Private Attributes
G4double theHelicity
G4double emissionTime
G4bool outOfWell
std::vector< G4int > theBiasCollisionVector
Time ordered vector of all biased vertices on the particle path.
G4double theMass
Static Private Attributes
static G4ThreadLocal long nextID = 1
Detailed Description
Definition at line 75 of file G4INCLParticle.hh.
Constructor & Destructor Documentation
Particle() [1/4]
G4INCL::Particle::Particle ()
Definition at line 59 of file G4INCLParticle.cc.
Referenced by G4INCL::Cluster::Cluster(), G4INCL::ProjectileRemnant::reset(), and G4INCL::ProjectileRemnant::storeComponents().
Particle() [2/4]
G4INCL::Particle::Particle (ParticleType t, G4double energy, ThreeVector const & momentum, ThreeVector const & position)
Definition at line 86 of file G4INCLParticle.cc.
Particle() [3/4]
G4INCL::Particle::Particle (ParticleType t, ThreeVector const & momentum, ThreeVector const & position)
Definition at line 114 of file G4INCLParticle.cc.
~Particle()
virtual G4INCL::Particle::~Particle () inline virtual
Definition at line 80 of file G4INCLParticle.hh.
Particle() [4/4]
G4INCL::Particle::Particle (const Particle & rhs) inline
Copy constructor.
Does not copy the particle ID.
Definition at line 86 of file G4INCLParticle.hh.
Member Function Documentation
adjustEnergyFromMomentum()
G4double G4INCL::Particle::adjustEnergyFromMomentum ()
Recompute the energy to match the momentum.
Definition at line 155 of file G4INCLParticle.cc.
Referenced by G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::computeRecoilKinematics(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), G4INCL::NKbToNKbChannel::fillFinalState(), G4INCL::NSToNSChannel::fillFinalState(), G4INCL::NKbToSpiChannel::fillFinalState(), G4INCL::NKbElasticChannel::fillFinalState(), G4INCL::NKbToLpiChannel::fillFinalState(), G4INCL::NKElasticChannel::fillFinalState(), G4INCL::NKToNKChannel::fillFinalState(), G4INCL::StrangeAbsorbtionChannel::fillFinalState(), G4INCL::DeltaDecayChannel::fillFinalState(), G4INCL::PionResonanceDecayChannel::fillFinalState(), G4INCL::SigmaZeroDecayChannel::fillFinalState(), G4INCL::RecombinationChannel::fillFinalState(), G4INCL::PhaseSpaceKopylov::generate(), and G4INCL::PhaseSpaceRauboldLynch::generateEvent().
adjustMomentumFromEnergy()
const ThreeVector & G4INCL::Particle::adjustMomentumFromEnergy ()
Rescale the momentum to match the total energy.
Definition at line 142 of file G4INCLParticle.cc.
Referenced by G4INCL::Cluster::Cluster(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::CrossSections::interactionDistanceKbarN(), G4INCL::CrossSections::interactionDistanceKN(), G4INCL::CrossSections::interactionDistanceNN(), G4INCL::CrossSections::interactionDistancePiN(), G4INCL::CrossSections::interactionDistanceYN(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::TransmissionChannel::particleLeaves(), G4INCL::StandardPropagationModel::shootParticle(), and G4INCL::KinematicsUtils::transformToLocalEnergyFrame().
boost()
void G4INCL::Particle::boost (const ThreeVector & aBoostVector) inline
Boost the particle using a boost vector.
Example (go to the particle rest frame): particle->boost(particle->boostVector());
Definition at line 422 of file G4INCLParticle.hh.
Referenced by G4INCL::Cluster::boost(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), G4INCL::PhaseSpaceKopylov::generate(), and G4INCL::InteractionAvatar::preInteraction().
boostVector()
ThreeVector G4INCL::Particle::boostVector () const inline
Returns a three vector we can give to the boost() -method.
In order to go to the particle rest frame you need to multiply the boost vector by -1.0.
Definition at line 412 of file G4INCLParticle.hh.
Referenced by G4INCL::PhaseSpaceKopylov::generate(), G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
dump()
std::string G4INCL::Particle::dump () const inline
Definition at line 968 of file G4INCLParticle.hh.
Referenced by G4INCL::ParticleEntryAvatar::dump(), G4INCL::BinaryCollisionAvatar::dump(), G4INCL::DecayAvatar::dump(), and G4INCL::SurfaceAvatar::dump().
FillINCLBiasVector()
void G4INCL::Particle::FillINCLBiasVector (G4double newBias) static
Definition at line 202 of file G4INCLParticle.cc.
Referenced by G4INCL::InteractionAvatar::postInteraction().
freezePropagation()
void G4INCL::Particle::freezePropagation () inline
Freeze particle propagation.
Make the particle use theFrozenMomentum and theFrozenEnergy for propagation. The normal state can be restored by calling the thawPropagation() method.
Definition at line 908 of file G4INCLParticle.hh.
getA()
G4int G4INCL::Particle::getA () const inline
Returns the baryon number.
Definition at line 393 of file G4INCLParticle.hh.
Referenced by G4INCL::ProjectileRemnant::addDynamicalSpectator(), G4INCL::Cluster::addParticle(), G4INCL::ClusteringModelIntercomparison::clusterCanEscape(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::INCL::continueCascade(), G4INCL::ClusterDecay::decay(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::Nucleus::fillEventInfo(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::TransmissionChannel::fillFinalState(), G4INCL::Nucleus::finalizeProjectileRemnant(), G4INCL::ClusteringModelIntercomparison::findClusterStartingFrom(), G4INCL::PauliStandard::getBlockingProbability(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::Nucleus::getConservationBalance(), G4INCL::SurfaceAvatar::getTransmissionProbability(), G4INCL::NuclearDensity::getTransmissionRadius(), G4INCL::TransmissionChannel::initializeKineticEnergyOutside(), G4INCL::Nucleus::insertParticle(), G4INCL::ClusterDecay::isStable(), G4INCL::INCL::postCascade(), G4INCL::INCL::preCascade(), G4INCL::INCL::RecoilCMFunctor::RecoilCMFunctor(), G4INCL::INCL::RecoilFunctor::RecoilFunctor(), G4INCL::ProjectileRemnant::removeParticle(), G4INCL::INCL::RecoilCMFunctor::scaleParticleCMMomenta(), G4INCL::INCL::RecoilFunctor::scaleParticleEnergies(), G4INCL::InteractionAvatar::ViolationEMomentumFunctor::scaleParticleMomenta(), G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
getAngularMomentum()
virtual G4INCL::ThreeVector G4INCL::Particle::getAngularMomentum () const inline virtual
Get the angular momentum w.r.t.
the origin
Reimplemented in G4INCL::Cluster.
Definition at line 800 of file G4INCLParticle.hh.
Referenced by G4INCL::Cluster::getAngularMomentum(), and G4INCL::StandardPropagationModel::shootParticle().
getBeta()
G4double G4INCL::Particle::getBeta () const inline
Definition at line 401 of file G4INCLParticle.hh.
getBiasCollisionVector()
std::vector<G4int> G4INCL::Particle::getBiasCollisionVector () const inline
Get the vector list of biased vertices on the particle path.
Definition at line 1038 of file G4INCLParticle.hh.
Referenced by G4INCL::ClusterDecay::decay(), G4INCL::Nucleus::decayMe(), G4INCL::Nucleus::decayOutgoingClusters(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), and MergeVectorBias().
getBiasFromVector()
G4double G4INCL::Particle::getBiasFromVector (std::vector< G4int > VectorBias) static
Definition at line 211 of file G4INCLParticle.cc.
Referenced by G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::ParticleList::getParticleListBias(), and setBiasCollisionVector().
getCosRPAngle()
G4double G4INCL::Particle::getCosRPAngle () const inline
Get the cosine of the angle between position and momentum.
Definition at line 1014 of file G4INCLParticle.hh.
Referenced by G4INCL::SurfaceAvatar::initializeRefractionVariables(), and G4INCL::ParticleEntryChannel::particleEnters().
getEmissionQValueCorrection() [1/2]
G4double G4INCL::Particle::getEmissionQValueCorrection (const G4int AParent, const G4int ZParent) const inline
Computes correction on the emission Q-value.
Computes the correction that must be applied to INCL particles in order to obtain the correct Q-value for particle emission from a given nucleus. For absorption, the correction is obviously equal to minus the value returned by this function.
Parameters
AParent the mass number of the emitting nucleus
ZParent the charge number of the emitting nucleus
Returns
the correction
Definition at line 602 of file G4INCLParticle.hh.
Referenced by G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::TransmissionChannel::fillFinalState(), G4INCL::SurfaceAvatar::getTransmissionProbability(), and G4INCL::TransmissionChannel::initializeKineticEnergyOutside().
getEmissionQValueCorrection() [2/2]
G4double G4INCL::Particle::getEmissionQValueCorrection (const G4int AParent, const G4int ZParent, const G4int SParent) const inline
Computes correction on the emission Q-value for hypernuclei.
Computes the correction that must be applied to INCL particles in order to obtain the correct Q-value for particle emission from a given nucleus. For absorption, the correction is obviously equal to minus the value returned by this function.
Parameters
AParent the mass number of the emitting nucleus
ZParent the charge number of the emitting nucleus
SParent the strangess number of the emitting nucleus
Returns
the correction
Definition at line 678 of file G4INCLParticle.hh.
getEmissionTime()
G4double G4INCL::Particle::getEmissionTime () inline
Definition at line 865 of file G4INCLParticle.hh.
getEnergy()
G4double G4INCL::Particle::getEnergy () const inline
Get the energy of the particle in MeV.
Definition at line 770 of file G4INCLParticle.hh.
Referenced by G4INCL::ProjectileRemnant::addDynamicalSpectator(), G4INCL::Cluster::addParticle(), G4INCL::DeltaDecayChannel::computeDecayTime(), G4INCL::PionResonanceDecayChannel::computeDecayTime(), G4INCL::EtaNElasticChannel::fillFinalState(), G4INCL::EtaNToPiNChannel::fillFinalState(), G4INCL::OmegaNElasticChannel::fillFinalState(), G4INCL::OmegaNToPiNChannel::fillFinalState(), G4INCL::ReflectionChannel::fillFinalState(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::TransmissionChannel::fillFinalState(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::TransmissionChannel::initializeKineticEnergyOutside(), G4INCL::KinematicsUtils::makeBoostVector(), G4INCL::INCL::makeCompoundNucleus(), G4INCL::KinematicsUtils::momentumInCM(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::InteractionAvatar::preInteraction(), G4INCL::InteractionAvatar::preInteractionBlocking(), G4INCL::ProjectileRemnant::removeParticle(), G4INCL::StandardPropagationModel::shootComposite(), G4INCL::StandardPropagationModel::shootParticle(), G4INCL::KinematicsUtils::squareTotalEnergyInCM(), and G4INCL::KinematicsUtils::transformToLocalEnergyFrame().
getFrozenEnergy()
G4double G4INCL::Particle::getFrozenEnergy () const inline
Get the frozen particle momentum.
Definition at line 897 of file G4INCLParticle.hh.
getFrozenMomentum()
ThreeVector G4INCL::Particle::getFrozenMomentum () const inline
Get the frozen particle momentum.
Definition at line 894 of file G4INCLParticle.hh.
getHelicity()
G4double G4INCL::Particle::getHelicity () inline
Definition at line 826 of file G4INCLParticle.hh.
Referenced by G4INCL::DeltaDecayChannel::sampleAngles().
getID()
long G4INCL::Particle::getID () const inline
Definition at line 981 of file G4INCLParticle.hh.
Referenced by G4INCL::ReflectionChannel::fillFinalState(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::PauliStandard::getBlockingProbability(), G4INCL::SurfaceAvatar::getChannel(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::ProjectileRemnant::getStoredMomentum(), G4INCL::ParticleEntryChannel::particleEnters(), and G4INCL::ProjectileRemnant::reset().
getINCLMass()
G4double G4INCL::Particle::getINCLMass () const inline
Get the INCL particle mass.
Definition at line 454 of file G4INCLParticle.hh.
Referenced by G4INCL::ParticleEntryChannel::fillFinalState(), getEmissionQValueCorrection(), and setINCLMass().
getInvariantMass()
G4double G4INCL::Particle::getInvariantMass () const inline
Get the the particle invariant mass.
Uses the relativistic invariant
Definition at line 748 of file G4INCLParticle.hh.
Referenced by G4INCL::Nucleus::finalizeProjectileRemnant(), and Particle().
getKineticEnergy()
G4double G4INCL::Particle::getKineticEnergy () const inline
Get the particle kinetic energy.
Definition at line 759 of file G4INCLParticle.hh.
Referenced by G4INCL::NuclearPotential::NuclearPotentialEnergyIsospin::computePotentialEnergy(), G4INCL::NuclearPotential::NuclearPotentialEnergyIsospinSmooth::computePotentialEnergy(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::Nucleus::fillEventInfo(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::SurfaceAvatar::getChannel(), G4INCL::Nucleus::getConservationBalance(), G4INCL::KinematicsUtils::getLocalEnergy(), G4INCL::SurfaceAvatar::getTransmissionProbability(), G4INCL::CoulombDistortion::maxImpactParameter(), G4INCL::CoulombNonRelativistic::minimumDistance(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::CDPP::processOneParticle(), G4INCL::INCL::RecoilFunctor::RecoilFunctor(), and G4INCL::StandardPropagationModel::shootParticle().
getLongitudinalPosition()
ThreeVector G4INCL::Particle::getLongitudinalPosition () const inline
Longitudinal component of the position w.r.t.
the momentum.
Definition at line 873 of file G4INCLParticle.hh.
Referenced by G4INCL::CoulombNonRelativistic::coulombDeviation(), and getTransversePosition().
getMass()
G4double G4INCL::Particle::getMass () const inline
Get the cached particle mass.
Definition at line 451 of file G4INCLParticle.hh.
Referenced by G4INCL::DeltaDecayChannel::computeDecayTime(), G4INCL::PionResonanceDecayChannel::computeDecayTime(), G4INCL::SigmaZeroDecayChannel::computeDecayTime(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::InteractionAvatar::enforceEnergyConservation(), G4INCL::CrossSectionsMultiPionsAndResonances::etaNToPiN(), G4INCL::OmegaNElasticChannel::fillFinalState(), G4INCL::OmegaNToPiNChannel::fillFinalState(), G4INCL::EtaNElasticChannel::fillFinalState(), G4INCL::EtaNToPiNChannel::fillFinalState(), G4INCL::NSToNLChannel::fillFinalState(), G4INCL::NSToNSChannel::fillFinalState(), G4INCL::PionResonanceDecayChannel::fillFinalState(), G4INCL::DeltaDecayChannel::fillFinalState(), G4INCL::SigmaZeroDecayChannel::fillFinalState(), G4INCL::TransmissionChannel::fillFinalState(), G4INCL::RecombinationChannel::fillFinalState(), G4INCL::Cluster::freezeInternalMotion(), G4INCL::PhaseSpaceKopylov::generate(), G4INCL::NuclearPotential::INuclearPotential::getFermiMomentum(), G4INCL::KinematicsUtils::getLocalEnergy(), G4INCL::SurfaceAvatar::getTransmissionProbability(), G4INCL::PhaseSpaceRauboldLynch::initialize(), G4INCL::TransmissionChannel::initializeKineticEnergyOutside(), G4INCL::CrossSections::interactionDistanceKbarN(), G4INCL::CrossSections::interactionDistanceKN(), G4INCL::CrossSections::interactionDistanceNN(), G4INCL::CrossSections::interactionDistancePiN(), G4INCL::CrossSections::interactionDistanceYN(), G4INCL::Cluster::internalBoostToCM(), G4INCL::KinematicsUtils::momentumInCM(), G4INCL::KinematicsUtils::momentumInLab(), G4INCL::CrossSectionsINCL46::NDeltaToNN(), G4INCL::CrossSectionsMultiPions::NDeltaToNN(), G4INCL::CrossSectionsStrangeness::NNToNLK2pi(), G4INCL::CrossSectionsStrangeness::NNToNLKpi(), G4INCL::CrossSectionsStrangeness::NNToNSK2pi(), G4INCL::CrossSectionsStrangeness::NNToNSKpi(), G4INCL::CrossSectionsMultiPionsAndResonances::omegaNToPiN(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::TransmissionChannel::particleLeaves(), G4INCL::CrossSectionsMultiPionsAndResonances::piMinuspToEtaN(), G4INCL::CrossSectionsMultiPionsAndResonances::piMinuspToOmegaN(), G4INCL::Cluster::print(), G4INCL::ProjectileRemnant::ProjectileRemnant(), and G4INCL::StandardPropagationModel::shootParticle().
getMomentum()
const G4INCL::ThreeVector& G4INCL::Particle::getMomentum () const inline
Get the momentum vector.
Definition at line 794 of file G4INCLParticle.hh.
Referenced by G4INCL::Cluster::addParticle(), G4INCL::ClusteringModelIntercomparison::clusterCanEscape(), G4INCL::SigmaZeroDecayChannel::computeDecayTime(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::computeRecoilKinematics(), G4INCL::CoulombNonRelativistic::coulombDeviation(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), G4INCL::Nucleus::fillEventInfo(), G4INCL::NNToNSKpiChannel::fillFinalState(), G4INCL::NpiToLK2piChannel::fillFinalState(), G4INCL::NpiToNKKbChannel::fillFinalState(), G4INCL::NpiToSK2piChannel::fillFinalState(), G4INCL::NpiToSKpiChannel::fillFinalState(), G4INCL::NpiToLKpiChannel::fillFinalState(), G4INCL::NDeltaEtaProductionChannel::fillFinalState(), G4INCL::NDeltaOmegaProductionChannel::fillFinalState(), G4INCL::ReflectionChannel::fillFinalState(), G4INCL::StrangeAbsorbtionChannel::fillFinalState(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::ElasticChannel::fillFinalState(), G4INCL::PauliStandard::getBlockingProbability(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::Nucleus::getConservationBalance(), G4INCL::KinematicsUtils::getLocalEnergy(), G4INCL::ProjectileRemnant::getStoredMomentum(), G4INCL::SurfaceAvatar::getTransmissionProbability(), G4INCL::NKbElasticChannel::KaonMomentum(), G4INCL::NKbToNKbChannel::KaonMomentum(), G4INCL::NKbToLpiChannel::KaonMomentum(), G4INCL::NKbToSpiChannel::KaonMomentum(), G4INCL::KinematicsUtils::makeBoostVector(), G4INCL::INCL::makeCompoundNucleus(), G4INCL::KinematicsUtils::momentumInCM(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::TransmissionChannel::particleLeaves(), G4INCL::BinaryCollisionAvatar::postInteraction(), G4INCL::InteractionAvatar::preInteraction(), G4INCL::INCL::RecoilCMFunctor::RecoilCMFunctor(), G4INCL::INCL::RecoilFunctor::RecoilFunctor(), G4INCL::ProjectileRemnant::removeParticle(), G4INCL::ParticleSampler::sampleParticlesIntoList(), G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
getNumberOfCollisions()
G4int G4INCL::Particle::getNumberOfCollisions () const inline
Return the number of collisions undergone by the particle.
Definition at line 834 of file G4INCLParticle.hh.
Referenced by G4INCL::Cluster::addParticle().
getNumberOfDecays()
G4int G4INCL::Particle::getNumberOfDecays () const inline
Return the number of decays undergone by the particle.
Definition at line 843 of file G4INCLParticle.hh.
getNumberOfKaon()
G4int G4INCL::Particle::getNumberOfKaon () const inline
Number of Kaon inside de nucleus.
Put in the Particle class in order to calculate the "correct" mass of composit particle.
Definition at line 1053 of file G4INCLParticle.hh.
Referenced by G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::SurfaceAvatar::getChannel(), and G4INCL::BinaryCollisionAvatar::postInteraction().
getParticipantType()
ParticipantType G4INCL::Particle::getParticipantType () const inline
Definition at line 310 of file G4INCLParticle.hh.
Referenced by G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar().
getParticleBias()
G4double G4INCL::Particle::getParticleBias () const inline
Get the particle bias.
Definition at line 1032 of file G4INCLParticle.hh.
getParticles()
const ParticleList* G4INCL::Particle::getParticles () const inline
Return a NULL pointer.
Definition at line 986 of file G4INCLParticle.hh.
getPosition()
const G4INCL::ThreeVector& G4INCL::Particle::getPosition () const inline
Set the position vector.
Definition at line 816 of file G4INCLParticle.hh.
Referenced by G4INCL::Cluster::addParticle(), G4INCL::InteractionAvatar::bringParticleInside(), G4INCL::CoulombNone::bringToSurface(), G4INCL::ClusteringModelIntercomparison::clusterCanEscape(), G4INCL::NDeltaToNSKChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::OmegaNToPiPiNChannel::fillFinalState(), G4INCL::NKbToNKb2piChannel::fillFinalState(), G4INCL::EtaNToPiPiNChannel::fillFinalState(), G4INCL::NKToNK2piChannel::fillFinalState(), G4INCL::NNEtaToMultiPionsChannel::fillFinalState(), G4INCL::NNOmegaToMultiPionsChannel::fillFinalState(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NNToNSKpiChannel::fillFinalState(), G4INCL::NNToNSKChannel::fillFinalState(), G4INCL::NNToNSK2piChannel::fillFinalState(), G4INCL::NNToMultiPionsChannel::fillFinalState(), G4INCL::NNToNNKKbChannel::fillFinalState(), G4INCL::NNToNLK2piChannel::fillFinalState(), G4INCL::NDeltaToDeltaSKChannel::fillFinalState(), G4INCL::NNToNLKChannel::fillFinalState(), G4INCL::NNToNLKpiChannel::fillFinalState(), G4INCL::NNToNNEtaChannel::fillFinalState(), G4INCL::NDeltaToNLKChannel::fillFinalState(), G4INCL::NNToNNOmegaChannel::fillFinalState(), G4INCL::NDeltaToNNKKbChannel::fillFinalState(), G4INCL::NDeltaOmegaProductionChannel::fillFinalState(), G4INCL::ReflectionChannel::fillFinalState(), G4INCL::NDeltaEtaProductionChannel::fillFinalState(), G4INCL::SigmaZeroDecayChannel::fillFinalState(), G4INCL::PionResonanceDecayChannel::fillFinalState(), G4INCL::DeltaDecayChannel::fillFinalState(), G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar(), G4INCL::PauliStandard::getBlockingProbability(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::KinematicsUtils::getLocalEnergy(), G4INCL::StandardPropagationModel::getReflectionTime(), G4INCL::StandardPropagationModel::getTime(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::TransmissionChannel::particleLeaves(), G4INCL::BinaryCollisionAvatar::postInteraction(), and G4INCL::ParticleSampler::sampleParticlesIntoList().
getPotentialEnergy()
G4double G4INCL::Particle::getPotentialEnergy () const inline
Get the particle potential energy.
Definition at line 762 of file G4INCLParticle.hh.
Referenced by G4INCL::Cluster::addParticle(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::ReflectionChannel::fillFinalState(), G4INCL::TransmissionChannel::fillFinalState(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::KinematicsUtils::getLocalEnergy(), G4INCL::SurfaceAvatar::getTransmissionProbability(), G4INCL::TransmissionChannel::initializeKineticEnergyOutside(), G4INCL::InteractionAvatar::preInteractionBlocking(), and G4INCL::CDPP::processOneParticle().
getPropagationVelocity()
ThreeVector G4INCL::Particle::getPropagationVelocity () const inline
Get the propagation velocity of the particle.
Definition at line 900 of file G4INCLParticle.hh.
Referenced by G4INCL::CoulombNone::bringToSurface(), G4INCL::StandardPropagationModel::getReflectionTime(), and G4INCL::StandardPropagationModel::getTime().
getRealMass()
G4double G4INCL::Particle::getRealMass () const inline
Get the real particle mass.
Definition at line 540 of file G4INCLParticle.hh.
Referenced by G4INCL::Cluster::getTableMass(), and setRealMass().
getReflectionMomentum()
G4double G4INCL::Particle::getReflectionMomentum () const inline
Return the reflection momentum.
The reflection momentum is used by calls to getSurfaceRadius to compute the radius of the sphere where the nucleon moves. It is necessary to introduce fuzzy r-p correlations.
Definition at line 997 of file G4INCLParticle.hh.
Referenced by G4INCL::KinematicsUtils::getLocalEnergy(), and G4INCL::Nucleus::getSurfaceRadius().
getS()
G4int G4INCL::Particle::getS () const inline
Returns the strangeness number.
Definition at line 399 of file G4INCLParticle.hh.
Referenced by G4INCL::ProjectileRemnant::addDynamicalSpectator(), G4INCL::Cluster::addParticle(), G4INCL::ClusteringModelIntercomparison::clusterCanEscape(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::ClusterDecay::decay(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::Nucleus::fillEventInfo(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::TransmissionChannel::fillFinalState(), G4INCL::Nucleus::finalizeProjectileRemnant(), G4INCL::Nucleus::getConservationBalance(), G4INCL::SurfaceAvatar::getTransmissionProbability(), G4INCL::TransmissionChannel::initializeKineticEnergyOutside(), G4INCL::Nucleus::insertParticle(), G4INCL::ClusterDecay::isStable(), G4INCL::INCL::preCascade(), G4INCL::INCL::RecoilCMFunctor::scaleParticleCMMomenta(), G4INCL::INCL::RecoilFunctor::scaleParticleEnergies(), G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
getSpecies()
virtual G4INCL::ParticleSpecies G4INCL::Particle::getSpecies () const inline virtual
Get the particle species.
Reimplemented in G4INCL::Cluster.
Definition at line 183 of file G4INCLParticle.hh.
Referenced by G4INCL::CoulombNonRelativistic::coulombDeviation(), G4INCL::CoulombDistortion::maxImpactParameter(), G4INCL::CoulombNonRelativistic::minimumDistance(), and G4INCL::StandardPropagationModel::shootParticle().
getTableMass()
virtual G4double G4INCL::Particle::getTableMass () const inline virtual
Get the tabulated particle mass.
Reimplemented in G4INCL::Cluster.
Definition at line 497 of file G4INCLParticle.hh.
Referenced by G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::TransmissionChannel::fillFinalState(), getEmissionQValueCorrection(), getTransferQValueCorrection(), and setTableMass().
getTotalBias()
G4double G4INCL::Particle::getTotalBias () static
General bias vector function.
Definition at line 300 of file G4INCLParticle.cc.
Referenced by G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::INCL::postCascade(), and G4INCL::EventInfo::remnantToParticle().
getTransferQValueCorrection() [1/2]
G4double G4INCL::Particle::getTransferQValueCorrection (const G4int AFrom, const G4int ZFrom, const G4int ATo, const G4int ZTo) const inline
Computes correction on the transfer Q-value.
Computes the correction that must be applied to INCL particles in order to obtain the correct Q-value for particle transfer from a given nucleus to another.
Assumes that the receving nucleus is INCL's target nucleus, with the INCL separation energy.
Parameters
AFrom the mass number of the donating nucleus
ZFrom the charge number of the donating nucleus
ATo the mass number of the receiving nucleus
ZTo the charge number of the receiving nucleus
Returns
the correction
Definition at line 642 of file G4INCLParticle.hh.
getTransferQValueCorrection() [2/2]
G4double G4INCL::Particle::getTransferQValueCorrection (const G4int AFrom, const G4int ZFrom, const G4int SFrom, const G4int ATo, const G4int ZTo, const G4int STo) const inline
Computes correction on the transfer Q-value for hypernuclei.
Computes the correction that must be applied to INCL particles in order to obtain the correct Q-value for particle transfer from a given nucleus to another.
Assumes that the receving nucleus is INCL's target nucleus, with the INCL separation energy.
Parameters
AFrom the mass number of the donating nucleus
ZFrom the charge number of the donating nucleus
SFrom the strangess number of the donating nucleus
ATo the mass number of the receiving nucleus
ZTo the charge number of the receiving nucleus
STo the strangess number of the receiving nucleus
Returns
the correction
Definition at line 719 of file G4INCLParticle.hh.
getTransversePosition()
ThreeVector G4INCL::Particle::getTransversePosition () const inline
Transverse component of the position w.r.t.
the momentum.
Definition at line 868 of file G4INCLParticle.hh.
Referenced by G4INCL::CoulombNonRelativistic::coulombDeviation(), G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
getType()
G4INCL::ParticleType G4INCL::Particle::getType () const inline
Get the particle type.
See also
G4INCL::ParticleType
Definition at line 178 of file G4INCLParticle.hh.
Referenced by G4INCL::PionResonanceDecayChannel::computeDecayTime(), G4INCL::NuclearPotential::INuclearPotential::computeKaonPotentialEnergy(), G4INCL::NuclearPotential::INuclearPotential::computePionPotentialEnergy(), G4INCL::NuclearPotential::INuclearPotential::computePionResonancePotentialEnergy(), G4INCL::NuclearPotential::NuclearPotentialIsospin::computePotentialEnergy(), G4INCL::NuclearPotential::NuclearPotentialConstant::computePotentialEnergy(), G4INCL::CrossSectionsINCL46::elasticNNLegacy(), G4INCL::NDeltaToDeltaLKChannel::fillFinalState(), G4INCL::NDeltaToDeltaSKChannel::fillFinalState(), G4INCL::NDeltaToNLKChannel::fillFinalState(), G4INCL::NDeltaToNNKKbChannel::fillFinalState(), G4INCL::NNToNSKpiChannel::fillFinalState(), G4INCL::NDeltaToNSKChannel::fillFinalState(), G4INCL::NKbToL2piChannel::fillFinalState(), G4INCL::NKbToLpiChannel::fillFinalState(), G4INCL::NNToNNKKbChannel::fillFinalState(), G4INCL::NKbToNKb2piChannel::fillFinalState(), G4INCL::NKbToNKbChannel::fillFinalState(), G4INCL::NKbToNKbpiChannel::fillFinalState(), G4INCL::NNToNLK2piChannel::fillFinalState(), G4INCL::NKbToS2piChannel::fillFinalState(), G4INCL::NKbToSpiChannel::fillFinalState(), G4INCL::NKToNK2piChannel::fillFinalState(), G4INCL::NKToNKChannel::fillFinalState(), G4INCL::NKToNKpiChannel::fillFinalState(), G4INCL::NNEtaToMultiPionsChannel::fillFinalState(), G4INCL::NNOmegaToMultiPionsChannel::fillFinalState(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NNToMultiPionsChannel::fillFinalState(), G4INCL::NNToNLKChannel::fillFinalState(), G4INCL::NNToNLKpiChannel::fillFinalState(), G4INCL::NNToNNEtaChannel::fillFinalState(), G4INCL::NNToNNOmegaChannel::fillFinalState(), G4INCL::NNToNSK2piChannel::fillFinalState(), G4INCL::NNToNSKChannel::fillFinalState(), G4INCL::NSToNLChannel::fillFinalState(), G4INCL::NSToNSChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::NDeltaOmegaProductionChannel::fillFinalState(), G4INCL::NDeltaEtaProductionChannel::fillFinalState(), G4INCL::DeltaDecayChannel::fillFinalState(), G4INCL::ElasticChannel::fillFinalState(), G4INCL::PionResonanceDecayChannel::fillFinalState(), G4INCL::RecombinationChannel::fillFinalState(), G4INCL::PauliStandard::getBlockingProbability(), G4INCL::DecayAvatar::getChannel(), G4INCL::NuclearPotential::INuclearPotential::getFermiEnergy(), G4INCL::NuclearPotential::INuclearPotential::getFermiMomentum(), G4INCL::KinematicsUtils::getLocalEnergy(), G4INCL::NuclearPotential::INuclearPotential::getSeparationEnergy(), G4INCL::Nucleus::getSurfaceRadius(), G4INCL::NuclearDensity::getTransmissionRadius(), G4INCL::Nucleus::insertParticle(), G4INCL::ParticleConfig::isPair(), G4INCL::CrossSectionsStrangeness::NDeltaToDeltaLK(), G4INCL::CrossSectionsStrangeness::NDeltaToDeltaSK(), G4INCL::CrossSectionsStrangeness::NDeltaToNLK(), G4INCL::CrossSectionsINCL46::NDeltaToNN(), G4INCL::CrossSectionsMultiPions::NDeltaToNN(), G4INCL::CrossSectionsStrangeness::NDeltaToNNKKb(), G4INCL::CrossSectionsStrangeness::NDeltaToNSK(), G4INCL::CrossSectionsStrangeness::NKbToL2pi(), G4INCL::CrossSectionsStrangeness::NKbToLpi(), G4INCL::CrossSectionsStrangeness::NKbToNKb(), G4INCL::CrossSectionsStrangeness::NKbToNKb2pi(), G4INCL::CrossSectionsStrangeness::NKbToNKbpi(), G4INCL::CrossSectionsStrangeness::NKbToS2pi(), G4INCL::CrossSectionsStrangeness::NKbToSpi(), G4INCL::CrossSectionsStrangeness::NKToNK(), G4INCL::CrossSectionsStrangeness::NKToNK2pi(), G4INCL::CrossSectionsStrangeness::NKToNKpi(), G4INCL::CrossSectionsMultiPions::NNElastic(), G4INCL::CrossSectionsMultiPions::NNOnePi(), G4INCL::CrossSectionsMultiPions::NNOnePiOrDelta(), G4INCL::CrossSectionsMultiPions::NNThreePi(), G4INCL::CrossSectionsStrangeness::NNToMissingStrangeness(), G4INCL::CrossSectionsINCL46::NNToNDelta(), G4INCL::CrossSectionsMultiPions::NNToNDelta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNDeltaEta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNDeltaOmega(), G4INCL::CrossSectionsStrangeness::NNToNLK(), G4INCL::CrossSectionsStrangeness::NNToNLK2pi(), G4INCL::CrossSectionsStrangeness::NNToNLKpi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaExclu(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaFourPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaOnePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaOnePiOrDelta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaThreePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaTwoPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaxPi(), G4INCL::CrossSectionsStrangeness::NNToNNKKb(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmega(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaExclu(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaFourPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaOnePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaOnePiOrDelta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaThreePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaTwoPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaxPi(), G4INCL::CrossSectionsStrangeness::NNToNSK(), G4INCL::CrossSectionsStrangeness::NNToNSK2pi(), G4INCL::CrossSectionsStrangeness::NNToNSKpi(), G4INCL::CrossSectionsMultiPions::NNTot(), G4INCL::CrossSectionsMultiPions::NNTwoPi(), G4INCL::CrossSectionsStrangeness::NpiToLK(), G4INCL::CrossSectionsStrangeness::NpiToLK2pi(), G4INCL::CrossSectionsStrangeness::NpiToLKpi(), G4INCL::CrossSectionsStrangeness::NpiToNKKb(), G4INCL::CrossSectionsStrangeness::NpiToSK(), G4INCL::CrossSectionsStrangeness::NpiToSK2pi(), G4INCL::CrossSectionsStrangeness::NpiToSKpi(), G4INCL::CrossSectionsStrangeness::NSToNL(), G4INCL::CrossSectionsStrangeness::NSToNS(), G4INCL::CrossSectionsStrangeness::p_pimToSzKz(), G4INCL::CrossSectionsINCL46::piNToDelta(), G4INCL::CrossSectionsMultiPions::piNToDelta(), G4INCL::CrossSectionsMultiPionsAndResonances::piNToEtaN(), G4INCL::CrossSectionsMultiPionsAndResonances::piNToOmegaN(), and G4INCL::CrossSectionsMultiPions::piNTot().
getZ()
G4int G4INCL::Particle::getZ () const inline
Returns the charge number.
Definition at line 396 of file G4INCLParticle.hh.
Referenced by G4INCL::ProjectileRemnant::addDynamicalSpectator(), G4INCL::Cluster::addParticle(), G4INCL::CoulombNonRelativistic::bringToSurface(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::ClusterDecay::decay(), G4INCL::CoulombNonRelativistic::distortOut(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::Nucleus::fillEventInfo(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::TransmissionChannel::fillFinalState(), G4INCL::Nucleus::finalizeProjectileRemnant(), G4INCL::ClusteringModelIntercomparison::findClusterStartingFrom(), G4INCL::PauliStandard::getBlockingProbability(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::Nucleus::getConservationBalance(), G4INCL::Nucleus::getTransmissionBarrier(), G4INCL::SurfaceAvatar::getTransmissionProbability(), G4INCL::NuclearDensity::getTransmissionRadius(), G4INCL::TransmissionChannel::initializeKineticEnergyOutside(), G4INCL::Nucleus::insertParticle(), G4INCL::ClusterDecay::isStable(), G4INCL::INCL::preCascade(), G4INCL::ProjectileRemnant::removeParticle(), G4INCL::INCL::RecoilCMFunctor::scaleParticleCMMomenta(), G4INCL::INCL::RecoilFunctor::scaleParticleEnergies(), G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
incrementNumberOfCollisions()
void G4INCL::Particle::incrementNumberOfCollisions () inline
Increment the number of collisions undergone by the particle.
Definition at line 840 of file G4INCLParticle.hh.
incrementNumberOfDecays()
void G4INCL::Particle::incrementNumberOfDecays () inline
Increment the number of decays undergone by the particle.
Definition at line 849 of file G4INCLParticle.hh.
isAntiKaon()
G4bool G4INCL::Particle::isAntiKaon () const inline
Is this an antiKaon?
Definition at line 372 of file G4INCLParticle.hh.
Referenced by G4INCL::CrossSectionsStrangeness::elastic(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::DecayAvatar::getChannel(), G4INCL::Nucleus::insertParticle(), isMeson(), isStrange(), G4INCL::CrossSectionsStrangeness::NKbelastic(), G4INCL::CrossSectionsStrangeness::NKbToL2pi(), G4INCL::CrossSectionsStrangeness::NKbToLpi(), G4INCL::CrossSectionsStrangeness::NKbToNKb(), G4INCL::CrossSectionsStrangeness::NKbToNKb2pi(), G4INCL::CrossSectionsStrangeness::NKbToNKbpi(), G4INCL::CrossSectionsStrangeness::NKbToS2pi(), G4INCL::CrossSectionsStrangeness::NKbToSpi(), and G4INCL::CrossSectionsStrangeness::total().
isBaryon()
G4bool G4INCL::Particle::isBaryon () const inline
Is this a Baryon?
Definition at line 387 of file G4INCLParticle.hh.
Referenced by G4INCL::CDPP::processOneParticle().
isCluster()
G4bool G4INCL::Particle::isCluster () const inline
Definition at line 883 of file G4INCLParticle.hh.
Referenced by getEmissionQValueCorrection(), and G4INCL::SurfaceAvatar::postInteraction().
isDelta()
G4bool G4INCL::Particle::isDelta () const inline
Is it a Delta?
Definition at line 361 of file G4INCLParticle.hh.
Referenced by G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::CrossSectionsINCL46::elastic(), G4INCL::CrossSectionsMultiPions::elastic(), G4INCL::CrossSectionsMultiPionsAndResonances::elastic(), G4INCL::CrossSectionsStrangeness::elastic(), G4INCL::CrossSectionsTruncatedMultiPions::elastic(), G4INCL::NDeltaOmegaProductionChannel::fillFinalState(), G4INCL::NDeltaEtaProductionChannel::fillFinalState(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::DecayAvatar::getChannel(), G4INCL::NuclearPotential::INuclearPotential::getFermiMomentum(), isResonance(), G4INCL::CrossSectionsINCL46::NDeltaToNN(), G4INCL::CrossSectionsMultiPions::NDeltaToNN(), G4INCL::CrossSectionsMultiPions::NNTot(), G4INCL::RecombinationChannel::RecombinationChannel(), G4INCL::CrossSectionsINCL46::total(), G4INCL::CrossSectionsStrangeness::total(), G4INCL::CrossSectionsMultiPionsAndResonances::total(), and G4INCL::CrossSectionsMultiPions::total().
isEta()
G4bool G4INCL::Particle::isEta () const inline
Is this an eta?
Definition at line 346 of file G4INCLParticle.hh.
Referenced by G4INCL::CrossSectionsMultiPionsAndResonances::elastic(), G4INCL::CrossSectionsStrangeness::elastic(), G4INCL::CrossSectionsMultiPionsAndResonances::etaNElastic(), G4INCL::CrossSectionsMultiPionsAndResonances::etaNToPiN(), G4INCL::CrossSectionsMultiPionsAndResonances::etaNToPiPiN(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::DecayAvatar::getChannel(), isMeson(), G4INCL::CrossSectionsStrangeness::total(), and G4INCL::CrossSectionsMultiPionsAndResonances::total().
isEtaPrime()
G4bool G4INCL::Particle::isEtaPrime () const inline
Is this an etaprime?
Definition at line 352 of file G4INCLParticle.hh.
Referenced by isMeson(), G4INCL::CrossSectionsStrangeness::total(), and G4INCL::CrossSectionsMultiPionsAndResonances::total().
isHyperon()
G4bool G4INCL::Particle::isHyperon () const inline
Is this an Hyperon?
Definition at line 381 of file G4INCLParticle.hh.
Referenced by G4INCL::CrossSectionsStrangeness::elastic(), isBaryon(), isStrange(), and G4INCL::CrossSectionsStrangeness::NYelastic().
isKaon()
G4bool G4INCL::Particle::isKaon () const inline
Is this a Kaon?
Definition at line 369 of file G4INCLParticle.hh.
Referenced by G4INCL::CrossSectionsStrangeness::elastic(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::SurfaceAvatar::getChannel(), G4INCL::Nucleus::insertParticle(), isMeson(), isStrange(), G4INCL::CrossSectionsStrangeness::NKelastic(), G4INCL::CrossSectionsStrangeness::NKToNK(), G4INCL::CrossSectionsStrangeness::NKToNK2pi(), G4INCL::CrossSectionsStrangeness::NKToNKpi(), and G4INCL::CrossSectionsStrangeness::total().
isLambda()
G4bool G4INCL::Particle::isLambda () const inline
Is this a Lambda?
Definition at line 375 of file G4INCLParticle.hh.
Referenced by G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::Nucleus::getSurfaceRadius(), isHyperon(), isNucleonorLambda(), G4INCL::CrossSectionsStrangeness::NLToNS(), and G4INCL::CrossSectionsStrangeness::total().
isMeson()
G4bool G4INCL::Particle::isMeson () const inline
Is this a Meson?
Definition at line 384 of file G4INCLParticle.hh.
Referenced by G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar(), G4INCL::InteractionAvatar::preInteractionLocalEnergy(), G4INCL::CDPP::processOneParticle(), and G4INCL::StandardPropagationModel::shootParticle().
isNucleon()
G4bool G4INCL::Particle::isNucleon () const inline
Is this a nucleon?
Definition at line 303 of file G4INCLParticle.hh.
Referenced by G4INCL::NuclearPotential::NuclearPotentialEnergyIsospin::computePotentialEnergy(), G4INCL::NuclearPotential::NuclearPotentialEnergyIsospinSmooth::computePotentialEnergy(), G4INCL::CrossSectionsINCL46::elastic(), G4INCL::CrossSectionsMultiPionsAndResonances::elastic(), G4INCL::CrossSectionsMultiPions::elastic(), G4INCL::CrossSectionsStrangeness::elastic(), G4INCL::CrossSectionsTruncatedMultiPions::elastic(), G4INCL::CrossSectionsINCL46::elasticNNLegacy(), G4INCL::PiNToDeltaChannel::fillFinalState(), G4INCL::NKbElasticChannel::fillFinalState(), G4INCL::OmegaNToPiPiNChannel::fillFinalState(), G4INCL::NKbToL2piChannel::fillFinalState(), G4INCL::OmegaNElasticChannel::fillFinalState(), G4INCL::PiNToOmegaChannel::fillFinalState(), G4INCL::NKbToLpiChannel::fillFinalState(), G4INCL::NKbToNKb2piChannel::fillFinalState(), G4INCL::NKbToNKbChannel::fillFinalState(), G4INCL::NKbToNKbpiChannel::fillFinalState(), G4INCL::NpiToSKpiChannel::fillFinalState(), G4INCL::NKbToS2piChannel::fillFinalState(), G4INCL::NKbToSpiChannel::fillFinalState(), G4INCL::NKElasticChannel::fillFinalState(), G4INCL::NpiToLKpiChannel::fillFinalState(), G4INCL::NKToNK2piChannel::fillFinalState(), G4INCL::NKToNKChannel::fillFinalState(), G4INCL::NKToNKpiChannel::fillFinalState(), G4INCL::NLToNSChannel::fillFinalState(), G4INCL::NpiToLK2piChannel::fillFinalState(), G4INCL::NpiToLKChannel::fillFinalState(), G4INCL::PiNToEtaChannel::fillFinalState(), G4INCL::PiNToMultiPionsChannel::fillFinalState(), G4INCL::NpiToNKKbChannel::fillFinalState(), G4INCL::NpiToSK2piChannel::fillFinalState(), G4INCL::NpiToSKChannel::fillFinalState(), G4INCL::NSToNLChannel::fillFinalState(), G4INCL::NSToNSChannel::fillFinalState(), G4INCL::EtaNElasticChannel::fillFinalState(), G4INCL::EtaNToPiNChannel::fillFinalState(), G4INCL::NDeltaToNNKKbChannel::fillFinalState(), G4INCL::PiNElasticChannel::fillFinalState(), G4INCL::NYElasticChannel::fillFinalState(), G4INCL::OmegaNToPiNChannel::fillFinalState(), G4INCL::EtaNToPiPiNChannel::fillFinalState(), G4INCL::StrangeAbsorbtionChannel::fillFinalState(), G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::DecayAvatar::getChannel(), G4INCL::Nucleus::getSurfaceRadius(), G4INCL::Nucleus::insertParticle(), isBaryon(), isNucleonorLambda(), G4INCL::CrossSectionsMultiPions::NNElastic(), G4INCL::CrossSectionsMultiPions::NNTot(), G4INCL::CrossSectionsMultiPions::piMinuspIne(), G4INCL::CrossSectionsMultiPions::piMinuspOnePi(), G4INCL::CrossSectionsMultiPions::piMinuspTwoPi(), G4INCL::CrossSectionsMultiPions::piNIne(), G4INCL::CrossSectionsMultiPions::piNOnePi(), G4INCL::CrossSectionsINCL46::piNToDelta(), G4INCL::CrossSectionsMultiPions::piNToxPiN(), G4INCL::CrossSectionsMultiPions::piNTwoPi(), G4INCL::CrossSectionsMultiPions::piPluspIne(), G4INCL::CrossSectionsMultiPions::piPluspOnePi(), G4INCL::CrossSectionsMultiPions::piPluspTwoPi(), G4INCL::CrossSectionsStrangeness::total(), G4INCL::CrossSectionsINCL46::total(), G4INCL::CrossSectionsMultiPions::total(), and G4INCL::CrossSectionsMultiPionsAndResonances::total().
isNucleonorLambda()
G4bool G4INCL::Particle::isNucleonorLambda () const inline
Is this a Nucleon or a Lambda?
Definition at line 378 of file G4INCLParticle.hh.
Referenced by G4INCL::ParticleEntryChannel::fillFinalState(), and G4INCL::SurfaceAvatar::getChannel().
isOmega()
G4bool G4INCL::Particle::isOmega () const inline
Is this an omega?
Definition at line 349 of file G4INCLParticle.hh.
Referenced by G4INCL::CrossSectionsMultiPionsAndResonances::elastic(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::DecayAvatar::getChannel(), isMeson(), G4INCL::CrossSectionsMultiPionsAndResonances::omegaNElastic(), G4INCL::CrossSectionsMultiPionsAndResonances::omegaNInelastic(), G4INCL::CrossSectionsMultiPionsAndResonances::omegaNToPiN(), G4INCL::CrossSectionsStrangeness::total(), and G4INCL::CrossSectionsMultiPionsAndResonances::total().
isOutOfWell()
G4bool G4INCL::Particle::isOutOfWell () const inline
Check if the particle is out of its potential well.
Definition at line 862 of file G4INCLParticle.hh.
Referenced by G4INCL::NuclearPotential::INuclearPotential::computeKaonPotentialEnergy(), G4INCL::NuclearPotential::INuclearPotential::computePionPotentialEnergy(), and G4INCL::NuclearPotential::INuclearPotential::computePionResonancePotentialEnergy().
isParticipant()
G4bool G4INCL::Particle::isParticipant () const inline
Definition at line 318 of file G4INCLParticle.hh.
Referenced by G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar().
isPhoton()
G4bool G4INCL::Particle::isPhoton () const inline
Is this a photon?
Definition at line 355 of file G4INCLParticle.hh.
isPion()
G4bool G4INCL::Particle::isPion () const inline
Is this a pion?
Definition at line 343 of file G4INCLParticle.hh.
Referenced by G4INCL::CrossSectionsMultiPions::elastic(), G4INCL::CrossSectionsMultiPionsAndResonances::elastic(), G4INCL::CrossSectionsStrangeness::elastic(), G4INCL::CrossSectionsTruncatedMultiPions::elastic(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar(), G4INCL::Nucleus::insertParticle(), isMeson(), G4INCL::CrossSectionsStrangeness::NpiToLK(), G4INCL::CrossSectionsStrangeness::NpiToLK2pi(), G4INCL::CrossSectionsStrangeness::NpiToLKpi(), G4INCL::CrossSectionsStrangeness::NpiToMissingStrangeness(), G4INCL::CrossSectionsStrangeness::NpiToNKKb(), G4INCL::CrossSectionsStrangeness::NpiToSK(), G4INCL::CrossSectionsStrangeness::NpiToSK2pi(), G4INCL::CrossSectionsStrangeness::NpiToSKpi(), G4INCL::CrossSectionsMultiPionsAndResonances::piMinuspToEtaN(), G4INCL::CrossSectionsMultiPionsAndResonances::piMinuspToOmegaN(), G4INCL::CrossSectionsINCL46::piNToDelta(), G4INCL::CrossSectionsMultiPions::piNToDelta(), G4INCL::CrossSectionsMultiPions::piNTot(), G4INCL::CrossSectionsINCL46::total(), G4INCL::CrossSectionsStrangeness::total(), G4INCL::CrossSectionsMultiPions::total(), and G4INCL::CrossSectionsMultiPionsAndResonances::total().
isProjectileSpectator()
G4bool G4INCL::Particle::isProjectileSpectator () const inline
Definition at line 326 of file G4INCLParticle.hh.
Referenced by G4INCL::SurfaceAvatar::getChannel().
isResonance()
G4bool G4INCL::Particle::isResonance () const inline
Is it a resonance?
Definition at line 358 of file G4INCLParticle.hh.
Referenced by G4INCL::NDeltaToDeltaLKChannel::fillFinalState(), G4INCL::NDeltaToDeltaSKChannel::fillFinalState(), G4INCL::NDeltaToNSKChannel::fillFinalState(), G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar(), G4INCL::SurfaceAvatar::getChannel(), G4INCL::Nucleus::getSurfaceRadius(), isBaryon(), Particle(), G4INCL::CDPP::processOneParticle(), and setType().
isSigma()
G4bool G4INCL::Particle::isSigma () const inline
Is this a Sigma?
Definition at line 366 of file G4INCLParticle.hh.
Referenced by G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::DecayAvatar::getChannel(), isHyperon(), G4INCL::CrossSectionsStrangeness::NSToNL(), G4INCL::CrossSectionsStrangeness::NSToNS(), and G4INCL::CrossSectionsStrangeness::total().
isStrange()
G4bool G4INCL::Particle::isStrange () const inline
Is this an Strange?
Definition at line 390 of file G4INCLParticle.hh.
isTargetSpectator()
G4bool G4INCL::Particle::isTargetSpectator () const inline
Definition at line 322 of file G4INCLParticle.hh.
Referenced by G4INCL::SurfaceAvatar::getChannel(), G4INCL::Nucleus::insertParticle(), G4INCL::SurfaceAvatar::postInteraction(), and G4INCL::BinaryCollisionAvatar::preInteraction().
lorentzContract()
void G4INCL::Particle::lorentzContract (const ThreeVector & aBoostVector, const ThreeVector & refPos) inline
Lorentz-contract the particle position around some center.
Apply Lorentz contraction to the position component along the direction of the boost vector.
Parameters
aBoostVector the boost vector (velocity) [c]
refPos the reference position
Definition at line 440 of file G4INCLParticle.hh.
makeParticipant()
virtual void G4INCL::Particle::makeParticipant () inline virtual
Reimplemented in G4INCL::Cluster.
Definition at line 330 of file G4INCLParticle.hh.
Referenced by G4INCL::Store::loadParticles(), and G4INCL::Cluster::makeParticipant().
makeProjectileSpectator()
virtual void G4INCL::Particle::makeProjectileSpectator () inline virtual
Reimplemented in G4INCL::Cluster.
Definition at line 338 of file G4INCLParticle.hh.
Referenced by G4INCL::Cluster::makeProjectileSpectator(), and G4INCL::StandardPropagationModel::shootParticle().
makeTargetSpectator()
virtual void G4INCL::Particle::makeTargetSpectator () inline virtual
Reimplemented in G4INCL::Cluster.
Definition at line 334 of file G4INCLParticle.hh.
Referenced by G4INCL::Cluster::makeTargetSpectator().
MergeVectorBias() [1/2]
std::vector< G4int > G4INCL::Particle::MergeVectorBias (Particle const *const p1, Particle const *const p2) static
Definition at line 223 of file G4INCLParticle.cc.
Referenced by G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::ParticleList::getParticleListBias(), and G4INCL::ParticleList::getParticleListBiasVector().
MergeVectorBias() [2/2]
std::vector< G4int > G4INCL::Particle::MergeVectorBias (std::vector< G4int > p1, Particle const *const p2) static
Definition at line 262 of file G4INCLParticle.cc.
operator=()
Particle& G4INCL::Particle::operator= (const Particle & rhs) inline
Assignment operator.
Does not copy the particle ID.
Definition at line 168 of file G4INCLParticle.hh.
Referenced by G4INCL::Cluster::operator=().
print()
std::string G4INCL::Particle::print () const inline
Definition at line 953 of file G4INCLParticle.hh.
Referenced by adjustMomentumFromEnergy(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::KinematicsUtils::getLocalEnergy(), G4INCL::StandardPropagationModel::getReflectionTime(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::CrossSectionsMultiPions::piNTot(), and G4INCL::ProjectileRemnant::removeParticle().
propagate()
void G4INCL::Particle::propagate (G4double step) inline
Definition at line 829 of file G4INCLParticle.hh.
Referenced by G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar().
rotateMomentum()
virtual void G4INCL::Particle::rotateMomentum (const G4double angle, const ThreeVector & axis) inline virtual
Rotate the particle momentum.
Parameters
angle the rotation angle
axis a unit vector representing the rotation axis
Reimplemented in G4INCL::Cluster.
Definition at line 948 of file G4INCLParticle.hh.
Referenced by G4INCL::Cluster::rotateMomentum(), and rotatePositionAndMomentum().
rotatePosition()
virtual void G4INCL::Particle::rotatePosition (const G4double angle, const ThreeVector & axis) inline virtual
Rotate the particle position.
Parameters
angle the rotation angle
axis a unit vector representing the rotation axis
Reimplemented in G4INCL::Cluster.
Definition at line 939 of file G4INCLParticle.hh.
Referenced by G4INCL::Cluster::rotatePosition(), and rotatePositionAndMomentum().
rotatePositionAndMomentum()
virtual void G4INCL::Particle::rotatePositionAndMomentum (const G4double angle, const ThreeVector & axis) inline virtual
Rotate the particle position and momentum.
Parameters
angle the rotation angle
axis a unit vector representing the rotation axis
Definition at line 929 of file G4INCLParticle.hh.
Referenced by G4INCL::CoulombNonRelativistic::coulombDeviation().
rpCorrelate()
void G4INCL::Particle::rpCorrelate () inline
Make the particle follow a strict r-p correlation.
Definition at line 1008 of file G4INCLParticle.hh.
Referenced by G4INCL::InteractionAvatar::bringParticleInside(), G4INCL::ParticleEntryAvatar::postInteraction(), and G4INCL::SurfaceAvatar::postInteraction().
rpDecorrelate()
void G4INCL::Particle::rpDecorrelate () inline
Make the particle not follow a strict r-p correlation.
Definition at line 1011 of file G4INCLParticle.hh.
setBiasCollisionVector()
void G4INCL::Particle::setBiasCollisionVector (std::vector< G4int > BiasCollisionVector) inline
Set the vector list of biased vertices on the particle path.
Definition at line 1041 of file G4INCLParticle.hh.
Referenced by G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), and G4INCL::SurfaceAvatar::postInteraction().
setEmissionTime()
void G4INCL::Particle::setEmissionTime (G4double t) inline
Definition at line 864 of file G4INCLParticle.hh.
Referenced by G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), and G4INCL::Nucleus::finalizeProjectileRemnant().
setEnergy()
void G4INCL::Particle::setEnergy (G4double energy) inline
Set the energy of the particle in MeV.
Definition at line 786 of file G4INCLParticle.hh.
Referenced by G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::EtaNToPiNChannel::fillFinalState(), G4INCL::OmegaNElasticChannel::fillFinalState(), G4INCL::OmegaNToPiNChannel::fillFinalState(), G4INCL::EtaNElasticChannel::fillFinalState(), G4INCL::NSToNLChannel::fillFinalState(), G4INCL::NSToNSChannel::fillFinalState(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::CrossSections::interactionDistanceKbarN(), G4INCL::CrossSections::interactionDistanceKN(), G4INCL::CrossSections::interactionDistanceNN(), G4INCL::CrossSections::interactionDistancePiN(), G4INCL::CrossSections::interactionDistanceYN(), G4INCL::INCL::makeCompoundNucleus(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::TransmissionChannel::particleLeaves(), G4INCL::INCL::RecoilCMFunctor::scaleParticleCMMomenta(), G4INCL::INCL::RecoilFunctor::scaleParticleEnergies(), G4INCL::StandardPropagationModel::shootParticle(), G4INCL::KinematicsUtils::transformToLocalEnergyFrame(), and G4INCL::Nucleus::useFusionKinematics().
setFrozenEnergy()
void G4INCL::Particle::setFrozenEnergy (const G4double energy) inline
Set the frozen particle momentum.
Definition at line 891 of file G4INCLParticle.hh.
setFrozenMomentum()
void G4INCL::Particle::setFrozenMomentum (const ThreeVector & momentum) inline
Set the frozen particle momentum.
Definition at line 888 of file G4INCLParticle.hh.
setHelicity()
void G4INCL::Particle::setHelicity (G4double h) inline
Definition at line 827 of file G4INCLParticle.hh.
Referenced by G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::NDeltaOmegaProductionChannel::fillFinalState(), G4INCL::NDeltaEtaProductionChannel::fillFinalState(), and G4INCL::DeltaDecayChannel::fillFinalState().
setINCLBiasVector()
void G4INCL::Particle::setINCLBiasVector (std::vector< G4double > NewVector) static
Definition at line 306 of file G4INCLParticle.cc.
setINCLMass()
void G4INCL::Particle::setINCLMass () inline
Set the mass of the Particle to its table mass.
Definition at line 589 of file G4INCLParticle.hh.
Referenced by G4INCL::Cluster::Cluster(), G4INCL::ParticleEntryChannel::particleEnters(), setType(), and G4INCL::StandardPropagationModel::shootParticle().
setMass()
void G4INCL::Particle::setMass (G4double mass) inline
Set the mass of the particle in MeV/c^2.
Definition at line 778 of file G4INCLParticle.hh.
Referenced by G4INCL::Nucleus::computeRecoilKinematics(), G4INCL::NDeltaToDeltaLKChannel::fillFinalState(), G4INCL::NDeltaToDeltaSKChannel::fillFinalState(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::NDeltaOmegaProductionChannel::fillFinalState(), G4INCL::NDeltaEtaProductionChannel::fillFinalState(), G4INCL::Nucleus::finalizeProjectileRemnant(), G4INCL::PhaseSpaceKopylov::generate(), G4INCL::INCL::makeCompoundNucleus(), Particle(), setINCLMass(), setRealMass(), setTableMass(), and G4INCL::Nucleus::useFusionKinematics().
setMomentum()
virtual void G4INCL::Particle::setMomentum (const G4INCL::ThreeVector & momentum) inline virtual
Set the momentum vector.
Definition at line 808 of file G4INCLParticle.hh.
Referenced by G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), G4INCL::NKbElasticChannel::fillFinalState(), G4INCL::NSToNSChannel::fillFinalState(), G4INCL::EtaNElasticChannel::fillFinalState(), G4INCL::EtaNToPiNChannel::fillFinalState(), G4INCL::NKbToLpiChannel::fillFinalState(), G4INCL::OmegaNElasticChannel::fillFinalState(), G4INCL::NKbToNKbChannel::fillFinalState(), G4INCL::OmegaNToPiNChannel::fillFinalState(), G4INCL::NKbToSpiChannel::fillFinalState(), G4INCL::NKElasticChannel::fillFinalState(), G4INCL::NKToNKChannel::fillFinalState(), G4INCL::NSToNLChannel::fillFinalState(), G4INCL::StrangeAbsorbtionChannel::fillFinalState(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::ReflectionChannel::fillFinalState(), G4INCL::ElasticChannel::fillFinalState(), G4INCL::DeltaDecayChannel::fillFinalState(), G4INCL::PionResonanceDecayChannel::fillFinalState(), G4INCL::SigmaZeroDecayChannel::fillFinalState(), G4INCL::RecombinationChannel::fillFinalState(), G4INCL::PhaseSpaceKopylov::generate(), G4INCL::PhaseSpaceRauboldLynch::generateEvent(), G4INCL::INCL::makeCompoundNucleus(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::TransmissionChannel::particleLeaves(), G4INCL::INCL::RecoilCMFunctor::scaleParticleCMMomenta(), G4INCL::INCL::RecoilFunctor::scaleParticleEnergies(), and G4INCL::Nucleus::useFusionKinematics().
setNumberOfCollisions()
void G4INCL::Particle::setNumberOfCollisions (G4int n) inline
Set the number of collisions undergone by the particle.
Definition at line 837 of file G4INCLParticle.hh.
setNumberOfDecays()
void G4INCL::Particle::setNumberOfDecays (G4int n) inline
Set the number of decays undergone by the particle.
Definition at line 846 of file G4INCLParticle.hh.
setNumberOfKaon()
void G4INCL::Particle::setNumberOfKaon (const G4int NK) inline
Definition at line 1054 of file G4INCLParticle.hh.
Referenced by G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::SurfaceAvatar::getChannel(), and G4INCL::BinaryCollisionAvatar::postInteraction().
setOutOfWell()
void G4INCL::Particle::setOutOfWell () inline
Mark the particle as out of its potential well.
This flag is used to control pions created outside their potential well in delta decay. The pion potential checks it and returns zero if it is true (necessary in order to correctly enforce energy conservation). The Nucleus::applyFinalState() method uses it to determine whether new avatars should be generated for the particle.
Definition at line 859 of file G4INCLParticle.hh.
setParticipantType()
void G4INCL::Particle::setParticipantType (ParticipantType const p) inline
Definition at line 314 of file G4INCLParticle.hh.
setParticleBias()
void G4INCL::Particle::setParticleBias (G4double ParticleBias) inline
Set the particle bias.
Definition at line 1035 of file G4INCLParticle.hh.
Referenced by setBiasCollisionVector().
setPosition()
virtual void G4INCL::Particle::setPosition (const G4INCL::ThreeVector & position) inline virtual
Reimplemented in G4INCL::Cluster.
Definition at line 821 of file G4INCLParticle.hh.
Referenced by G4INCL::InteractionAvatar::bringParticleInside(), G4INCL::CoulombNone::bringToSurface(), G4INCL::CoulombNonRelativistic::coulombDeviation(), G4INCL::ReflectionChannel::fillFinalState(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::ParticleSampler::sampleParticlesIntoList(), G4INCL::Cluster::setPosition(), and G4INCL::StandardPropagationModel::shootParticle().
setPotentialEnergy()
void G4INCL::Particle::setPotentialEnergy (G4double v) inline
Set the particle potential energy.
Definition at line 765 of file G4INCLParticle.hh.
Referenced by G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::Store::loadParticles(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::TransmissionChannel::particleLeaves(), and G4INCL::Nucleus::updatePotentialEnergy().
setRealMass()
void G4INCL::Particle::setRealMass () inline
Set the mass of the Particle to its real mass.
Definition at line 583 of file G4INCLParticle.hh.
Referenced by G4INCL::ClusterDecay::decay().
setTableMass()
void G4INCL::Particle::setTableMass () inline
Set the mass of the Particle to its table mass.
Definition at line 586 of file G4INCLParticle.hh.
Referenced by G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::TransmissionChannel::particleLeaves(), G4INCL::ProjectileRemnant::ProjectileRemnant(), and G4INCL::ProjectileRemnant::reset().
setType()
void G4INCL::Particle::setType (ParticleType t) inline
Definition at line 187 of file G4INCLParticle.hh.
Referenced by G4INCL::Cluster::Cluster(), G4INCL::ClusterDecay::decay(), G4INCL::NKbToL2piChannel::fillFinalState(), G4INCL::NKbToLpiChannel::fillFinalState(), G4INCL::NNToNLKpiChannel::fillFinalState(), G4INCL::NNToNNEtaChannel::fillFinalState(), G4INCL::PiNToMultiPionsChannel::fillFinalState(), G4INCL::OmegaNToPiPiNChannel::fillFinalState(), G4INCL::OmegaNToPiNChannel::fillFinalState(), G4INCL::NSToNSChannel::fillFinalState(), G4INCL::NNToNNKKbChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::NNToNSKpiChannel::fillFinalState(), G4INCL::NNToNNOmegaChannel::fillFinalState(), G4INCL::NKbToNKb2piChannel::fillFinalState(), G4INCL::NNToNSK2piChannel::fillFinalState(), G4INCL::NNToNSKChannel::fillFinalState(), G4INCL::NKbToNKbChannel::fillFinalState(), G4INCL::NDeltaToDeltaLKChannel::fillFinalState(), G4INCL::NNToNLKChannel::fillFinalState(), G4INCL::NKbToNKbpiChannel::fillFinalState(), G4INCL::NNToMultiPionsChannel::fillFinalState(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NNOmegaToMultiPionsChannel::fillFinalState(), G4INCL::NNEtaToMultiPionsChannel::fillFinalState(), G4INCL::NKToNKpiChannel::fillFinalState(), G4INCL::NSToNLChannel::fillFinalState(), G4INCL::NKToNK2piChannel::fillFinalState(), G4INCL::NKbToS2piChannel::fillFinalState(), G4INCL::NDeltaToDeltaSKChannel::fillFinalState(), G4INCL::NKbToSpiChannel::fillFinalState(), G4INCL::EtaNToPiNChannel::fillFinalState(), G4INCL::NDeltaToNLKChannel::fillFinalState(), G4INCL::NKToNKChannel::fillFinalState(), G4INCL::NDeltaToNNKKbChannel::fillFinalState(), G4INCL::NNToNLK2piChannel::fillFinalState(), G4INCL::EtaNToPiPiNChannel::fillFinalState(), G4INCL::NDeltaToNSKChannel::fillFinalState(), G4INCL::NDeltaEtaProductionChannel::fillFinalState(), G4INCL::StrangeAbsorbtionChannel::fillFinalState(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::NDeltaOmegaProductionChannel::fillFinalState(), G4INCL::NeutralKaonDecayChannel::fillFinalState(), G4INCL::PionResonanceDecayChannel::fillFinalState(), G4INCL::ElasticChannel::fillFinalState(), G4INCL::DeltaDecayChannel::fillFinalState(), G4INCL::SigmaZeroDecayChannel::fillFinalState(), G4INCL::RecombinationChannel::fillFinalState(), and Particle().
setUncorrelatedMomentum()
void G4INCL::Particle::setUncorrelatedMomentum (const G4double p) inline
Set the uncorrelated momentum.
Definition at line 1005 of file G4INCLParticle.hh.
Referenced by G4INCL::ParticleSampler::sampleOneParticleWithFuzzyRPCorrelation(), and G4INCL::ParticleSampler::sampleOneParticleWithRPCorrelation().
swap()
void G4INCL::Particle::swap (Particle & rhs) inline protected
Helper method for the assignment operator.
Definition at line 125 of file G4INCLParticle.hh.
Referenced by operator=(), and G4INCL::Cluster::swap().
thawPropagation()
void G4INCL::Particle::thawPropagation () inline
Unfreeze particle propagation.
Make the particle use theMomentum and theEnergy for propagation. Call this method to restore the normal propagation if the freezePropagation() method has been called.
Definition at line 919 of file G4INCLParticle.hh.
Referenced by G4INCL::ReflectionChannel::fillFinalState().
Field Documentation
emissionTime
G4double G4INCL::Particle::emissionTime private
Definition at line 1104 of file G4INCLParticle.hh.
Referenced by getEmissionTime(), setEmissionTime(), and swap().
ID
long G4INCL::Particle::ID protected
Definition at line 1093 of file G4INCLParticle.hh.
Referenced by dump(), getID(), Particle(), G4INCL::Cluster::print(), and print().
INCLBiasVector
std::vector< G4double > G4INCL::Particle::INCLBiasVector static
Time ordered vector of all bias applied.
/!\ Caution /!\ methods Assotiated to G4VectorCache<T> are: Push_back(), operator[], Begin(), End(), Clear(), Size() and Pop_back()
Definition at line 1071 of file G4INCLParticle.hh.
Referenced by FillINCLBiasVector(), getBiasFromVector(), getTotalBias(), G4INCL::INCL::processEvent(), and setINCLBiasVector().
nCollisions
G4int G4INCL::Particle::nCollisions protected
Definition at line 1090 of file G4INCLParticle.hh.
Referenced by G4INCL::Cluster::addParticle(), getNumberOfCollisions(), incrementNumberOfCollisions(), G4INCL::ProjectileRemnant::reset(), setNumberOfCollisions(), swap(), and G4INCL::Cluster::updateClusterParameters().
nDecays
G4int G4INCL::Particle::nDecays protected
Definition at line 1091 of file G4INCLParticle.hh.
Referenced by getNumberOfDecays(), incrementNumberOfDecays(), setNumberOfDecays(), and swap().
nextBiasedCollisionID
G4ThreadLocal G4int G4INCL::Particle::nextBiasedCollisionID = 0 static
Definition at line 1077 of file G4INCLParticle.hh.
Referenced by FillINCLBiasVector(), G4INCL::InteractionAvatar::postInteraction(), and G4INCL::INCL::processEvent().
nextID
G4ThreadLocal long G4INCL::Particle::nextID = 1 static private
Definition at line 1111 of file G4INCLParticle.hh.
Referenced by Particle().
outOfWell
G4bool G4INCL::Particle::outOfWell private
Definition at line 1105 of file G4INCLParticle.hh.
Referenced by isOutOfWell(), setOutOfWell(), and swap().
rpCorrelated
G4bool G4INCL::Particle::rpCorrelated protected
Definition at line 1095 of file G4INCLParticle.hh.
Referenced by getReflectionMomentum(), rpCorrelate(), rpDecorrelate(), and swap().
theA
G4int G4INCL::Particle::theA protected
Definition at line 1080 of file G4INCLParticle.hh.
Referenced by G4INCL::ProjectileRemnant::addAllDynamicalSpectators(), G4INCL::ProjectileRemnant::addDynamicalSpectator(), G4INCL::ProjectileRemnant::addMostDynamicalSpectators(), G4INCL::Cluster::addParticle(), G4INCL::Nucleus::applyFinalState(), G4INCL::Cluster::Cluster(), G4INCL::Cluster::computeDynamicalPotential(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::computeRecoilKinematics(), G4INCL::Nucleus::decayInsideDeltas(), G4INCL::Nucleus::decayInsideStrangeParticles(), G4INCL::Nucleus::decayMe(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), getA(), getEmissionQValueCorrection(), getINCLMass(), getRealMass(), G4INCL::Cluster::getSpecies(), getTableMass(), getTransferQValueCorrection(), G4INCL::Cluster::initializeParticles(), G4INCL::Nucleus::insertParticle(), G4INCL::Cluster::internalBoostToCM(), G4INCL::Nucleus::Nucleus(), G4INCL::Cluster::print(), G4INCL::ProjectileRemnant::removeParticle(), G4INCL::ProjectileRemnant::reset(), G4INCL::Cluster::setA(), setType(), swap(), and G4INCL::Cluster::updateClusterParameters().
theBiasCollisionVector
std::vector<G4int> G4INCL::Particle::theBiasCollisionVector private
Time ordered vector of all biased vertices on the particle path.
Definition at line 1108 of file G4INCLParticle.hh.
Referenced by getBiasCollisionVector(), Particle(), setBiasCollisionVector(), and swap().
theEnergy
G4double G4INCL::Particle::theEnergy protected
Definition at line 1083 of file G4INCLParticle.hh.
Referenced by G4INCL::ProjectileRemnant::addAllDynamicalSpectators(), G4INCL::ProjectileRemnant::addDynamicalSpectator(), G4INCL::ProjectileRemnant::addMostDynamicalSpectators(), G4INCL::Cluster::addParticle(), adjustEnergyFromMomentum(), adjustMomentumFromEnergy(), boost(), boostVector(), dump(), getBeta(), getEnergy(), getInvariantMass(), getKineticEnergy(), G4INCL::Cluster::internalBoostToCM(), Particle(), G4INCL::Cluster::print(), print(), G4INCL::ProjectileRemnant::removeParticle(), G4INCL::ProjectileRemnant::reset(), setEnergy(), swap(), thawPropagation(), G4INCL::Cluster::updateClusterParameters(), and G4INCL::Nucleus::useFusionKinematics().
theFrozenEnergy
G4double G4INCL::Particle::theFrozenEnergy protected
Definition at line 1085 of file G4INCLParticle.hh.
Referenced by freezePropagation(), getFrozenEnergy(), Particle(), setFrozenEnergy(), and swap().
theFrozenMomentum
G4INCL::ThreeVector G4INCL::Particle::theFrozenMomentum protected
Definition at line 1088 of file G4INCLParticle.hh.
Referenced by freezePropagation(), getFrozenMomentum(), Particle(), rotateMomentum(), setFrozenMomentum(), and swap().
theHelicity
G4double G4INCL::Particle::theHelicity private
Definition at line 1103 of file G4INCLParticle.hh.
Referenced by getHelicity(), setHelicity(), and swap().
theMass
G4double G4INCL::Particle::theMass private
Definition at line 1110 of file G4INCLParticle.hh.
Referenced by adjustEnergyFromMomentum(), adjustMomentumFromEnergy(), getINCLMass(), getKineticEnergy(), getMass(), getRealMass(), getTableMass(), Particle(), setMass(), and swap().
theMomentum
G4INCL::ThreeVector G4INCL::Particle::theMomentum protected
Definition at line 1086 of file G4INCLParticle.hh.
Referenced by G4INCL::ProjectileRemnant::addAllDynamicalSpectators(), G4INCL::ProjectileRemnant::addDynamicalSpectator(), G4INCL::ProjectileRemnant::addMostDynamicalSpectators(), G4INCL::Cluster::addParticle(), adjustEnergyFromMomentum(), adjustMomentumFromEnergy(), boost(), boostVector(), G4INCL::Nucleus::computeRecoilKinematics(), dump(), G4INCL::Cluster::freezeInternalMotion(), getAngularMomentum(), getBeta(), getInvariantMass(), getMomentum(), getReflectionMomentum(), G4INCL::Cluster::internalBoostToCM(), Particle(), G4INCL::Cluster::print(), print(), G4INCL::ProjectileRemnant::removeParticle(), G4INCL::ProjectileRemnant::reset(), rotateMomentum(), setMomentum(), swap(), thawPropagation(), G4INCL::Cluster::updateClusterParameters(), and G4INCL::Nucleus::useFusionKinematics().
theNKaon
G4int G4INCL::Particle::theNKaon protected
The number of Kaons inside the nucleus (update during the cascade)
Definition at line 1100 of file G4INCLParticle.hh.
Referenced by G4INCL::Nucleus::emitInsideKaon(), getNumberOfKaon(), and setNumberOfKaon().
theParticipantType
ParticipantType G4INCL::Particle::theParticipantType protected
Definition at line 1081 of file G4INCLParticle.hh.
Referenced by getParticipantType(), isParticipant(), isProjectileSpectator(), isTargetSpectator(), makeParticipant(), makeProjectileSpectator(), makeTargetSpectator(), Particle(), setParticipantType(), and swap().
theParticleBias
G4double G4INCL::Particle::theParticleBias protected
Definition at line 1098 of file G4INCLParticle.hh.
Referenced by getParticleBias(), setParticleBias(), and swap().
thePosition
G4INCL::ThreeVector G4INCL::Particle::thePosition protected
Definition at line 1089 of file G4INCLParticle.hh.
Referenced by G4INCL::Cluster::addParticle(), G4INCL::Cluster::boost(), G4INCL::Cluster::Cluster(), G4INCL::Nucleus::computeRecoilKinematics(), dump(), getAngularMomentum(), getCosRPAngle(), getLongitudinalPosition(), getPosition(), getTransversePosition(), G4INCL::Nucleus::initializeParticles(), G4INCL::Cluster::initializeParticles(), G4INCL::Cluster::internalBoostToCM(), lorentzContract(), G4INCL::Cluster::print(), print(), propagate(), G4INCL::ProjectileRemnant::reset(), rotatePosition(), G4INCL::Cluster::setPosition(), setPosition(), swap(), and G4INCL::Cluster::updateClusterParameters().
thePotentialEnergy
G4double G4INCL::Particle::thePotentialEnergy protected
Definition at line 1092 of file G4INCLParticle.hh.
Referenced by G4INCL::Cluster::addParticle(), getPotentialEnergy(), G4INCL::ProjectileRemnant::reset(), setPotentialEnergy(), swap(), and G4INCL::Cluster::updateClusterParameters().
thePropagationEnergy
G4double* G4INCL::Particle::thePropagationEnergy protected
Definition at line 1084 of file G4INCLParticle.hh.
Referenced by freezePropagation(), Particle(), swap(), and thawPropagation().
thePropagationMomentum
G4INCL::ThreeVector* G4INCL::Particle::thePropagationMomentum protected
Definition at line 1087 of file G4INCLParticle.hh.
Referenced by freezePropagation(), getCosRPAngle(), getLongitudinalPosition(), getPropagationVelocity(), Particle(), swap(), and thawPropagation().
theS
G4int G4INCL::Particle::theS protected
Definition at line 1080 of file G4INCLParticle.hh.
Referenced by G4INCL::ProjectileRemnant::addAllDynamicalSpectators(), G4INCL::ProjectileRemnant::addDynamicalSpectator(), G4INCL::ProjectileRemnant::addMostDynamicalSpectators(), G4INCL::Cluster::addParticle(), G4INCL::Nucleus::applyFinalState(), G4INCL::Cluster::Cluster(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::computeRecoilKinematics(), G4INCL::Nucleus::decayMe(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), getEmissionQValueCorrection(), getINCLMass(), getRealMass(), getS(), G4INCL::Cluster::getSpecies(), getTableMass(), getTransferQValueCorrection(), G4INCL::Nucleus::insertParticle(), G4INCL::Nucleus::Nucleus(), G4INCL::Cluster::print(), G4INCL::Cluster::setS(), setType(), swap(), and G4INCL::Cluster::updateClusterParameters().
theType
G4INCL::ParticleType G4INCL::Particle::theType protected
Definition at line 1082 of file G4INCLParticle.hh.
Referenced by dump(), getINCLMass(), getRealMass(), getSpecies(), getTableMass(), getType(), isAntiKaon(), isCluster(), isDelta(), isEta(), isEtaPrime(), isKaon(), isLambda(), isNucleon(), isOmega(), isPhoton(), isPion(), isSigma(), G4INCL::Cluster::print(), print(), setType(), and swap().
theZ
G4int G4INCL::Particle::theZ protected
Definition at line 1080 of file G4INCLParticle.hh.
Referenced by G4INCL::ProjectileRemnant::addAllDynamicalSpectators(), G4INCL::ProjectileRemnant::addDynamicalSpectator(), G4INCL::ProjectileRemnant::addMostDynamicalSpectators(), G4INCL::Cluster::addParticle(), G4INCL::Nucleus::applyFinalState(), G4INCL::Cluster::Cluster(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::computeRecoilKinematics(), G4INCL::Nucleus::decayInsideDeltas(), G4INCL::Nucleus::decayInsideStrangeParticles(), G4INCL::Nucleus::decayMe(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), getEmissionQValueCorrection(), getINCLMass(), getRealMass(), G4INCL::Cluster::getSpecies(), getTableMass(), getTransferQValueCorrection(), G4INCL::Nucleus::getTransmissionBarrier(), getZ(), G4INCL::Cluster::initializeParticles(), G4INCL::Nucleus::insertParticle(), G4INCL::Nucleus::Nucleus(), G4INCL::Cluster::print(), G4INCL::ProjectileRemnant::removeParticle(), G4INCL::ProjectileRemnant::reset(), setType(), G4INCL::Cluster::setZ(), swap(), and G4INCL::Cluster::updateClusterParameters().
uncorrelatedMomentum
G4double G4INCL::Particle::uncorrelatedMomentum protected
Definition at line 1096 of file G4INCLParticle.hh.
Referenced by getReflectionMomentum(), setUncorrelatedMomentum(), and swap().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/inclxx/utils/include/G4INCLParticle.hh
source/processes/hadronic/models/inclxx/utils/src/G4INCLParticle.cc