Geant4: G4ModelCmdApplyBool< M > Class Template Reference
G4ModelCmdApplyBool< M > Class Template Reference abstract
#include <G4ModelApplyCommandsT.hh>
Public Member Functions
G4ModelCmdApplyBool (M *model, const G4String &placement, const G4String &cmdName)
virtual ~G4ModelCmdApplyBool ()
void SetNewValue (G4UIcommand *command, G4String newValue)
Public Member Functions inherited from G4VModelCommand< M >
G4VModelCommand (M *model, const G4String &placement="")
virtual ~G4VModelCommand ()
G4String GetCurrentValue (G4UIcommand *command)
G4String Placement ()
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Protected Member Functions
virtual void Apply (const G4bool &)=0
G4UIcmdWithABool * Command ()
Protected Member Functions inherited from G4VModelCommand< M >
M * Model ()
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Private Attributes
G4UIcmdWithABool * fpCmd
Additional Inherited Members
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
template<typename M>
class G4ModelCmdApplyBool< M >
Definition at line 263 of file G4ModelApplyCommandsT.hh.
Constructor & Destructor Documentation
G4ModelCmdApplyBool()
template<typename M > G4ModelCmdApplyBool< M >::G4ModelCmdApplyBool (M * model, const G4String & placement, const G4String & cmdName)
Definition at line 286 of file G4ModelApplyCommandsT.hh.
~G4ModelCmdApplyBool()
template<typename M > G4ModelCmdApplyBool< M >::~G4ModelCmdApplyBool () virtual
Definition at line 296 of file G4ModelApplyCommandsT.hh.
Member Function Documentation
Apply()
template<typename M > virtual void G4ModelCmdApplyBool< M >::Apply (const G4bool &) protected pure virtual
Implemented in G4ModelCmdDraw< M >, G4ModelCmdVerbose< M >, G4ModelCmdActive< M >, G4ModelCmdInvert< M >, G4ModelCmdSetStepPtsVisible< M >, G4ModelCmdSetDrawStepPts< M >, G4ModelCmdSetAuxPtsVisible< M >, G4ModelCmdSetDrawAuxPts< M >, G4ModelCmdSetLineVisible< M >, and G4ModelCmdSetDrawLine< M >.
Command()
template<typename M > G4UIcmdWithABool* G4ModelCmdApplyBool< M >::Command () inline protected
Definition at line 277 of file G4ModelApplyCommandsT.hh.
Referenced by G4ModelCmdActive< M >::G4ModelCmdActive(), G4ModelCmdDraw< M >::G4ModelCmdDraw(), G4ModelCmdInvert< M >::G4ModelCmdInvert(), G4ModelCmdSetAuxPtsVisible< M >::G4ModelCmdSetAuxPtsVisible(), G4ModelCmdSetDrawAuxPts< M >::G4ModelCmdSetDrawAuxPts(), G4ModelCmdSetDrawLine< M >::G4ModelCmdSetDrawLine(), G4ModelCmdSetDrawStepPts< M >::G4ModelCmdSetDrawStepPts(), G4ModelCmdSetLineVisible< M >::G4ModelCmdSetLineVisible(), G4ModelCmdSetStepPtsVisible< M >::G4ModelCmdSetStepPtsVisible(), and G4ModelCmdVerbose< M >::G4ModelCmdVerbose().
SetNewValue()
template<typename M > void G4ModelCmdApplyBool< M >::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 302 of file G4ModelApplyCommandsT.hh.
Field Documentation
fpCmd
template<typename M > G4UIcmdWithABool* G4ModelCmdApplyBool< M >::fpCmd private
Definition at line 281 of file G4ModelApplyCommandsT.hh.
Referenced by G4ModelCmdApplyBool< M >::Command(), and G4ModelCmdApplyBool< M >::G4ModelCmdApplyBool().
The documentation for this class was generated from the following file:
source/visualization/modeling/include/G4ModelApplyCommandsT.hh