Geant4: G4tgbMaterialMgr Class Reference
G4tgbMaterialMgr Class Reference
#include <G4tgbMaterialMgr.hh>
Public Member Functions
~G4tgbMaterialMgr ()
void CopyIsotopes ()
void CopyElements ()
void CopyMaterials ()
G4Isotope * FindOrBuildG4Isotope (const G4String &name)
G4Isotope * FindBuiltG4Isotope (const G4String &name) const
G4tgbIsotope * FindG4tgbIsotope (const G4String &name, G4bool bMustExist=0) const
G4Element * FindOrBuildG4Element (const G4String &name, G4bool bMustExist=1)
G4Element * FindBuiltG4Element (const G4String &name) const
G4tgbElement * FindG4tgbElement (const G4String &name, G4bool bMustExist=0) const
G4Material * FindOrBuildG4Material (const G4String &name, G4bool bMustExist=1)
G4Material * FindBuiltG4Material (const G4String &name) const
G4tgbMaterial * FindG4tgbMaterial (const G4String &name, G4bool bMustExist=0) const
const G4msg4isot GetG4IsotopeList () const
const G4msg4elem GetG4ElementList () const
const G4msg4mate GetG4MaterialList () const
Static Public Member Functions
static G4tgbMaterialMgr * GetInstance ()
Private Member Functions
G4tgbMaterialMgr ()
Private Attributes
G4mstgbisot theG4tgbIsotopes
G4mstgbelem theG4tgbElements
G4mstgbmate theG4tgbMaterials
G4msg4isot theG4Isotopes
G4msg4elem theG4Elements
G4msg4mate theG4Materials
Static Private Attributes
static G4ThreadLocal G4tgbMaterialMgr * theInstance = 0
Detailed Description
Definition at line 65 of file G4tgbMaterialMgr.hh.
Constructor & Destructor Documentation
~G4tgbMaterialMgr()
G4tgbMaterialMgr::~G4tgbMaterialMgr ()
Definition at line 73 of file G4tgbMaterialMgr.cc.
G4tgbMaterialMgr()
G4tgbMaterialMgr::G4tgbMaterialMgr () private
Definition at line 53 of file G4tgbMaterialMgr.cc.
Referenced by GetInstance().
Member Function Documentation
CopyElements()
void G4tgbMaterialMgr::CopyElements ()
Definition at line 119 of file G4tgbMaterialMgr.cc.
Referenced by GetInstance().
CopyIsotopes()
void G4tgbMaterialMgr::CopyIsotopes ()
Definition at line 104 of file G4tgbMaterialMgr.cc.
Referenced by GetInstance().
CopyMaterials()
void G4tgbMaterialMgr::CopyMaterials ()
Definition at line 134 of file G4tgbMaterialMgr.cc.
Referenced by GetInstance().
FindBuiltG4Element()
G4Element * G4tgbMaterialMgr::FindBuiltG4Element (const G4String & name) const
Definition at line 324 of file G4tgbMaterialMgr.cc.
Referenced by FindOrBuildG4Element().
FindBuiltG4Isotope()
G4Isotope * G4tgbMaterialMgr::FindBuiltG4Isotope (const G4String & name) const
Definition at line 195 of file G4tgbMaterialMgr.cc.
Referenced by FindOrBuildG4Isotope().
FindBuiltG4Material()
G4Material * G4tgbMaterialMgr::FindBuiltG4Material (const G4String & name) const
Definition at line 445 of file G4tgbMaterialMgr.cc.
Referenced by FindOrBuildG4Material().
FindG4tgbElement()
G4tgbElement * G4tgbMaterialMgr::FindG4tgbElement (const G4String & name, G4bool bMustExist = 0) const
Definition at line 346 of file G4tgbMaterialMgr.cc.
Referenced by FindOrBuildG4Element().
FindG4tgbIsotope()
G4tgbIsotope * G4tgbMaterialMgr::FindG4tgbIsotope (const G4String & name, G4bool bMustExist = 0) const
Definition at line 218 of file G4tgbMaterialMgr.cc.
Referenced by FindOrBuildG4Isotope().
FindG4tgbMaterial()
G4tgbMaterial * G4tgbMaterialMgr::FindG4tgbMaterial (const G4String & name, G4bool bMustExist = 0) const
Definition at line 467 of file G4tgbMaterialMgr.cc.
Referenced by FindOrBuildG4Material().
FindOrBuildG4Element()
G4Element * G4tgbMaterialMgr::FindOrBuildG4Element (const G4String & name, G4bool bMustExist = 1)
Definition at line 248 of file G4tgbMaterialMgr.cc.
Referenced by G4tgbMaterialMixtureByWeight::BuildG4Material(), and G4tgbMaterialMixtureByNoAtoms::BuildG4Material().
FindOrBuildG4Isotope()
G4Isotope * G4tgbMaterialMgr::FindOrBuildG4Isotope (const G4String & name)
Definition at line 160 of file G4tgbMaterialMgr.cc.
Referenced by G4tgbElement::BuildG4ElementFromIsotopes().
FindOrBuildG4Material()
G4Material * G4tgbMaterialMgr::FindOrBuildG4Material (const G4String & name, G4bool bMustExist = 1)
Definition at line 376 of file G4tgbMaterialMgr.cc.
Referenced by G4tgbMaterialMixtureByVolume::BuildG4Material(), G4tgbMaterialMixtureByWeight::BuildG4Material(), G4tgbVolume::ConstructG4LogVol(), G4tgbVolume::ConstructG4PhysVol(), and G4tgbMaterialMixtureByVolume::TransformToFractionsByWeight().
GetG4ElementList()
const G4msg4elem G4tgbMaterialMgr::GetG4ElementList () const inline
Definition at line 111 of file G4tgbMaterialMgr.hh.
Referenced by G4tgbVolumeMgr::DumpSummary().
GetG4IsotopeList()
const G4msg4isot G4tgbMaterialMgr::GetG4IsotopeList () const inline
Definition at line 110 of file G4tgbMaterialMgr.hh.
Referenced by G4tgbVolumeMgr::DumpSummary().
GetG4MaterialList()
const G4msg4mate G4tgbMaterialMgr::GetG4MaterialList () const inline
Definition at line 112 of file G4tgbMaterialMgr.hh.
Referenced by G4tgbVolumeMgr::DumpSummary().
GetInstance()
G4tgbMaterialMgr * G4tgbMaterialMgr::GetInstance (void) static
Definition at line 59 of file G4tgbMaterialMgr.cc.
Referenced by G4tgbElement::BuildG4ElementFromIsotopes(), G4tgbMaterialMixtureByWeight::BuildG4Material(), G4tgbMaterialMixtureByVolume::BuildG4Material(), G4tgbMaterialMixtureByNoAtoms::BuildG4Material(), G4tgbVolume::ConstructG4LogVol(), G4tgbVolume::ConstructG4PhysVol(), G4tgbVolumeMgr::DumpSummary(), and G4tgbMaterialMixtureByVolume::TransformToFractionsByWeight().
Field Documentation
theG4Elements
G4msg4elem G4tgbMaterialMgr::theG4Elements private
Definition at line 131 of file G4tgbMaterialMgr.hh.
Referenced by FindBuiltG4Element(), FindOrBuildG4Element(), and GetG4ElementList().
theG4Isotopes
G4msg4isot G4tgbMaterialMgr::theG4Isotopes private
Definition at line 129 of file G4tgbMaterialMgr.hh.
Referenced by FindBuiltG4Isotope(), FindOrBuildG4Isotope(), and GetG4IsotopeList().
theG4Materials
G4msg4mate G4tgbMaterialMgr::theG4Materials private
Definition at line 133 of file G4tgbMaterialMgr.hh.
Referenced by FindBuiltG4Material(), FindOrBuildG4Material(), and GetG4MaterialList().
theG4tgbElements
G4mstgbelem G4tgbMaterialMgr::theG4tgbElements private
Definition at line 125 of file G4tgbMaterialMgr.hh.
Referenced by CopyElements(), FindG4tgbElement(), and ~G4tgbMaterialMgr().
theG4tgbIsotopes
G4mstgbisot G4tgbMaterialMgr::theG4tgbIsotopes private
Definition at line 123 of file G4tgbMaterialMgr.hh.
Referenced by CopyIsotopes(), FindG4tgbIsotope(), and ~G4tgbMaterialMgr().
theG4tgbMaterials
G4mstgbmate G4tgbMaterialMgr::theG4tgbMaterials private
Definition at line 127 of file G4tgbMaterialMgr.hh.
Referenced by CopyMaterials(), FindG4tgbMaterial(), and ~G4tgbMaterialMgr().
theInstance
G4ThreadLocal G4tgbMaterialMgr * G4tgbMaterialMgr::theInstance = 0 static private
Definition at line 121 of file G4tgbMaterialMgr.hh.
Referenced by GetInstance(), and ~G4tgbMaterialMgr().
The documentation for this class was generated from the following files:
source/persistency/ascii/include/G4tgbMaterialMgr.hh
source/persistency/ascii/src/G4tgbMaterialMgr.cc