Geant4: G4CrossSectionDataStore Class Reference
G4CrossSectionDataStore Class Reference
#include <G4CrossSectionDataStore.hh>
Public Member Functions
G4CrossSectionDataStore ()
~G4CrossSectionDataStore ()
G4double GetCrossSection (const G4DynamicParticle *, const G4Material *)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Material *)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *)
G4double GetCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *, const G4Element *, const G4Material *)
const G4Element * SampleZandA (const G4DynamicParticle *, const G4Material *, G4Nucleus &target)
void BuildPhysicsTable (const G4ParticleDefinition &)
void DumpPhysicsTable (const G4ParticleDefinition &)
void DumpHtml (const G4ParticleDefinition &, std::ofstream &) const
void PrintCrossSectionHtml (const G4VCrossSectionDataSet *cs) const
void AddDataSet (G4VCrossSectionDataSet *)
void AddDataSet (G4VCrossSectionDataSet *, size_t)
void SetVerboseLevel (G4int value)
const G4FastPathHadronicCrossSection::fastPathParameters & GetFastPathParameters () const
const G4FastPathHadronicCrossSection::controlFlag & GetFastPathControlFlags () const
void DumpFastPath (const G4ParticleDefinition *, const G4Material *, std::ostream &os)
void ActivateFastPath (const G4ParticleDefinition *, const G4Material *, G4double)
Private Member Functions
G4double GetIsoCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *, const G4Element *, const G4Material *aMaterial, G4int index)
G4CrossSectionDataStore & operator= (const G4CrossSectionDataStore &right)
G4CrossSectionDataStore (const G4CrossSectionDataStore &)
G4String HtmlFileName (const G4String &in) const
G4double GetCrossSection (const G4DynamicParticle *, const G4Material *, G4bool requiresSlowPath)
Private Attributes
G4NistManager * nist
std::vector< G4VCrossSectionDataSet * > dataSetList
std::vector< G4double > xsecelm
std::vector< G4double > xseciso
const G4Material * currentMaterial
const G4ParticleDefinition * matParticle
G4double matKinEnergy
G4double matCrossSection
const G4Material * elmMaterial
const G4Element * currentElement
const G4ParticleDefinition * elmParticle
G4double elmKinEnergy
G4double elmCrossSection
G4int nDataSetList
G4int verboseLevel
G4FastPathHadronicCrossSection::controlFlag fastPathFlags
G4FastPathHadronicCrossSection::fastPathParameters fastPathParams
G4FastPathHadronicCrossSection::getCrossSectionCount counters
G4FastPathHadronicCrossSection::G4CrossSectionDataStore_Cache fastPathCache
G4FastPathHadronicCrossSection::timing timing
G4FastPathHadronicCrossSection::G4CrossSectionDataStore_Requests requests
Friends
struct G4FastPathHadronicCrossSection::fastPathEntry
Detailed Description
Definition at line 62 of file G4CrossSectionDataStore.hh.
Constructor & Destructor Documentation
G4CrossSectionDataStore() [1/2]
G4CrossSectionDataStore::G4CrossSectionDataStore ()
Definition at line 62 of file G4CrossSectionDataStore.cc.
~G4CrossSectionDataStore()
G4CrossSectionDataStore::~G4CrossSectionDataStore ()
Definition at line 75 of file G4CrossSectionDataStore.cc.
G4CrossSectionDataStore() [2/2]
G4CrossSectionDataStore::G4CrossSectionDataStore (const G4CrossSectionDataStore &) private
Member Function Documentation
ActivateFastPath()
void G4CrossSectionDataStore::ActivateFastPath (const G4ParticleDefinition * pdef, const G4Material * mat, G4double min_cutoff)
Definition at line 532 of file G4CrossSectionDataStore.cc.
AddDataSet() [1/2]
void G4CrossSectionDataStore::AddDataSet (G4VCrossSectionDataSet * p)
Definition at line 642 of file G4CrossSectionDataStore.cc.
Referenced by G4HadronicProcess::AddDataSet(), G4HadronPhysicsShieldingLEND::ExtraConfiguration(), G4HadronPhysicsShielding::ExtraConfiguration(), G4ElectronNuclearProcess::G4ElectronNuclearProcess(), G4PhotoNuclearProcess::G4PhotoNuclearProcess(), and G4PositronNuclearProcess::G4PositronNuclearProcess().
AddDataSet() [2/2]
void G4CrossSectionDataStore::AddDataSet (G4VCrossSectionDataSet * p, size_t i)
Definition at line 656 of file G4CrossSectionDataStore.cc.
BuildPhysicsTable()
void G4CrossSectionDataStore::BuildPhysicsTable (const G4ParticleDefinition & aParticleType)
Definition at line 497 of file G4CrossSectionDataStore.cc.
Referenced by G4HadronicProcess::BuildPhysicsTable().
ComputeCrossSection()
G4double G4CrossSectionDataStore::ComputeCrossSection (const G4DynamicParticle * part, const G4Material * mat)
Definition at line 270 of file G4CrossSectionDataStore.cc.
Referenced by G4GammaGeneralProcess::BuildPhysicsTable(), G4NeutrinoElectronProcess::GetMeanFreePath(), G4HadronicProcess::GetMeanFreePath(), G4HadronXSDataTable::Initialise(), G4HadronicProcess::PostStepDoIt(), and G4GammaGeneralProcess::SampleSecondaries().
DumpFastPath()
void G4CrossSectionDataStore::DumpFastPath (const G4ParticleDefinition * pd, const G4Material * mat, std::ostream & os)
Definition at line 251 of file G4CrossSectionDataStore.cc.
DumpHtml()
void G4CrossSectionDataStore::DumpHtml (const G4ParticleDefinition & , std::ofstream & outFile) const
Definition at line 574 of file G4CrossSectionDataStore.cc.
Referenced by G4HadronicProcessStore::PrintHtml().
DumpPhysicsTable()
void G4CrossSectionDataStore::DumpPhysicsTable (const G4ParticleDefinition & aParticleType)
Definition at line 547 of file G4CrossSectionDataStore.cc.
Referenced by G4ChargeExchangeProcess::DumpPhysicsTable(), G4HadronicProcess::DumpPhysicsTable(), and G4HadronicProcessStore::Print().
GetCrossSection() [1/4]
G4double G4CrossSectionDataStore::GetCrossSection (const G4DynamicParticle * part, const G4Element * elm, const G4Material * mat)
Definition at line 298 of file G4CrossSectionDataStore.cc.
GetCrossSection() [2/4]
G4double G4CrossSectionDataStore::GetCrossSection (const G4DynamicParticle * particle, const G4Material * material) inline
Definition at line 156 of file G4CrossSectionDataStore.hh.
Referenced by ComputeCrossSection(), G4HadElementSelector::G4HadElementSelector(), GetCrossSection(), G4ChargeExchangeProcess::GetElementCrossSection(), G4HadronicProcess::GetElementCrossSection(), and G4FastPathHadronicCrossSection::fastPathEntry::Initialize().
GetCrossSection() [3/4]
G4double G4CrossSectionDataStore::GetCrossSection (const G4DynamicParticle * part, const G4Material * mat, G4bool requiresSlowPath) private
Definition at line 81 of file G4CrossSectionDataStore.cc.
GetCrossSection() [4/4]
G4double G4CrossSectionDataStore::GetCrossSection (const G4DynamicParticle * part, G4int Z, G4int A, const G4Isotope * iso, const G4Element * elm, const G4Material * mat)
Definition at line 393 of file G4CrossSectionDataStore.cc.
GetFastPathControlFlags()
const G4FastPathHadronicCrossSection::controlFlag& G4CrossSectionDataStore::GetFastPathControlFlags () const inline
Definition at line 138 of file G4CrossSectionDataStore.hh.
Referenced by G4FastPathHadronicCrossSection::fastPathEntry::Initialize().
GetFastPathParameters()
const G4FastPathHadronicCrossSection::fastPathParameters& G4CrossSectionDataStore::GetFastPathParameters () const inline
Definition at line 136 of file G4CrossSectionDataStore.hh.
Referenced by G4FastPathHadronicCrossSection::fastPathEntry::Initialize().
GetIsoCrossSection()
G4double G4CrossSectionDataStore::GetIsoCrossSection (const G4DynamicParticle * part, G4int Z, G4int A, const G4Isotope * iso, const G4Element * elm, const G4Material * aMaterial, G4int index) private
Definition at line 354 of file G4CrossSectionDataStore.cc.
Referenced by GetCrossSection(), and SampleZandA().
HtmlFileName()
G4String G4CrossSectionDataStore::HtmlFileName (const G4String & in) const private
Definition at line 629 of file G4CrossSectionDataStore.cc.
Referenced by PrintCrossSectionHtml().
operator=()
G4CrossSectionDataStore& G4CrossSectionDataStore::operator= (const G4CrossSectionDataStore & right) private
PrintCrossSectionHtml()
void G4CrossSectionDataStore::PrintCrossSectionHtml (const G4VCrossSectionDataSet * cs) const
Definition at line 606 of file G4CrossSectionDataStore.cc.
Referenced by DumpHtml().
SampleZandA()
const G4Element * G4CrossSectionDataStore::SampleZandA (const G4DynamicParticle * part, const G4Material * mat, G4Nucleus & target)
Definition at line 419 of file G4CrossSectionDataStore.cc.
Referenced by G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), and G4HadronicProcess::PostStepDoIt().
SetVerboseLevel()
void G4CrossSectionDataStore::SetVerboseLevel (G4int value) inline
Definition at line 161 of file G4CrossSectionDataStore.hh.
Friends And Related Function Documentation
G4FastPathHadronicCrossSection::fastPathEntry
friend struct G4FastPathHadronicCrossSection::fastPathEntry friend
Definition at line 142 of file G4CrossSectionDataStore.hh.
Field Documentation
counters
G4FastPathHadronicCrossSection::getCrossSectionCount G4CrossSectionDataStore::counters private
Definition at line 149 of file G4CrossSectionDataStore.hh.
Referenced by GetCrossSection().
currentElement
const G4Element* G4CrossSectionDataStore::currentElement private
Definition at line 126 of file G4CrossSectionDataStore.hh.
Referenced by G4CrossSectionDataStore(), and GetCrossSection().
currentMaterial
const G4Material* G4CrossSectionDataStore::currentMaterial private
Definition at line 120 of file G4CrossSectionDataStore.hh.
Referenced by ComputeCrossSection(), G4CrossSectionDataStore(), and GetCrossSection().
dataSetList
std::vector<G4VCrossSectionDataSet*> G4CrossSectionDataStore::dataSetList private
Definition at line 116 of file G4CrossSectionDataStore.hh.
Referenced by AddDataSet(), BuildPhysicsTable(), DumpHtml(), DumpPhysicsTable(), GetCrossSection(), GetIsoCrossSection(), and SampleZandA().
elmCrossSection
G4double G4CrossSectionDataStore::elmCrossSection private
Definition at line 129 of file G4CrossSectionDataStore.hh.
Referenced by G4CrossSectionDataStore(), and GetCrossSection().
elmKinEnergy
G4double G4CrossSectionDataStore::elmKinEnergy private
Definition at line 128 of file G4CrossSectionDataStore.hh.
Referenced by G4CrossSectionDataStore(), and GetCrossSection().
elmMaterial
const G4Material* G4CrossSectionDataStore::elmMaterial private
Definition at line 125 of file G4CrossSectionDataStore.hh.
Referenced by G4CrossSectionDataStore(), and GetCrossSection().
elmParticle
const G4ParticleDefinition* G4CrossSectionDataStore::elmParticle private
Definition at line 127 of file G4CrossSectionDataStore.hh.
Referenced by G4CrossSectionDataStore(), and GetCrossSection().
fastPathCache
G4FastPathHadronicCrossSection::G4CrossSectionDataStore_Cache G4CrossSectionDataStore::fastPathCache private
Definition at line 151 of file G4CrossSectionDataStore.hh.
Referenced by BuildPhysicsTable(), DumpFastPath(), and GetCrossSection().
fastPathFlags
G4FastPathHadronicCrossSection::controlFlag G4CrossSectionDataStore::fastPathFlags private
Definition at line 146 of file G4CrossSectionDataStore.hh.
Referenced by BuildPhysicsTable(), GetCrossSection(), and GetFastPathControlFlags().
fastPathParams
G4FastPathHadronicCrossSection::fastPathParameters G4CrossSectionDataStore::fastPathParams private
Definition at line 147 of file G4CrossSectionDataStore.hh.
Referenced by GetFastPathParameters().
matCrossSection
G4double G4CrossSectionDataStore::matCrossSection private
Definition at line 123 of file G4CrossSectionDataStore.hh.
Referenced by ComputeCrossSection(), G4CrossSectionDataStore(), GetCrossSection(), and SampleZandA().
matKinEnergy
G4double G4CrossSectionDataStore::matKinEnergy private
Definition at line 122 of file G4CrossSectionDataStore.hh.
Referenced by ComputeCrossSection(), G4CrossSectionDataStore(), and GetCrossSection().
matParticle
const G4ParticleDefinition* G4CrossSectionDataStore::matParticle private
Definition at line 121 of file G4CrossSectionDataStore.hh.
Referenced by ComputeCrossSection(), G4CrossSectionDataStore(), and GetCrossSection().
nDataSetList
G4int G4CrossSectionDataStore::nDataSetList private
Definition at line 131 of file G4CrossSectionDataStore.hh.
Referenced by AddDataSet(), BuildPhysicsTable(), DumpHtml(), DumpPhysicsTable(), GetCrossSection(), GetIsoCrossSection(), and SampleZandA().
nist
G4NistManager* G4CrossSectionDataStore::nist private
Definition at line 114 of file G4CrossSectionDataStore.hh.
Referenced by G4CrossSectionDataStore().
requests
G4FastPathHadronicCrossSection::G4CrossSectionDataStore_Requests G4CrossSectionDataStore::requests private
Definition at line 153 of file G4CrossSectionDataStore.hh.
Referenced by ActivateFastPath(), and BuildPhysicsTable().
timing
G4FastPathHadronicCrossSection::timing G4CrossSectionDataStore::timing private
Definition at line 152 of file G4CrossSectionDataStore.hh.
Referenced by GetCrossSection().
verboseLevel
G4int G4CrossSectionDataStore::verboseLevel private
Definition at line 132 of file G4CrossSectionDataStore.hh.
Referenced by SetVerboseLevel().
xsecelm
std::vector<G4double> G4CrossSectionDataStore::xsecelm private
Definition at line 117 of file G4CrossSectionDataStore.hh.
Referenced by ComputeCrossSection(), GetCrossSection(), and SampleZandA().
xseciso
std::vector<G4double> G4CrossSectionDataStore::xseciso private
Definition at line 118 of file G4CrossSectionDataStore.hh.
Referenced by SampleZandA().
The documentation for this class was generated from the following files:
source/processes/hadronic/cross_sections/include/G4CrossSectionDataStore.hh
source/processes/hadronic/cross_sections/src/G4CrossSectionDataStore.cc