Geant4: G4ReplicaNavigation Class Reference
G4ReplicaNavigation Class Reference
#include <G4ReplicaNavigation.hh>
Public Member Functions
G4ReplicaNavigation ()
~G4ReplicaNavigation ()
G4bool LevelLocate (G4NavigationHistory &history, const G4VPhysicalVolume *blockedVol, const G4int blockedNum, const G4ThreeVector &globalPoint, const G4ThreeVector *globalDirection, const G4bool pLocatedOnEdge, G4ThreeVector &localPoint)
G4double ComputeStep (const G4ThreeVector &globalPoint, const G4ThreeVector &globalDirection, const G4ThreeVector &localPoint, const G4ThreeVector &localDirection, const G4double currentProposedStepLength, G4double &newSafety, G4NavigationHistory &history, G4bool &validExitNormal, G4bool &calculatedExitNormal, G4ThreeVector &exitNormal, G4bool &exiting, G4bool &entering, G4VPhysicalVolume *(*pBlockedPhysical), G4int &blockedReplicaNo)
G4double ComputeSafety (const G4ThreeVector &globalPoint, const G4ThreeVector &localPoint, G4NavigationHistory &history, const G4double pProposedMaxLength=DBL_MAX)
EInside BackLocate (G4NavigationHistory &history, const G4ThreeVector &globalPoint, G4ThreeVector &localPoint, const G4bool &exiting, G4bool &notKnownInside) const
void ComputeTransformation (const G4int replicaNo, G4VPhysicalVolume *pVol, G4ThreeVector &point) const
void ComputeTransformation (const G4int replicaNo, G4VPhysicalVolume *pVol) const
EInside Inside (const G4VPhysicalVolume *pVol, const G4int replicaNo, const G4ThreeVector &localPoint) const
G4double DistanceToOut (const G4VPhysicalVolume *pVol, const G4int replicaNo, const G4ThreeVector &localPoint) const
G4double DistanceToOut (const G4VPhysicalVolume *pVol, const G4int replicaNo, const G4ThreeVector &localPoint, const G4ThreeVector &localDirection, G4ExitNormal &candidateNormal) const
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int level)
void CheckMode (G4bool mode)
Private Member Functions
G4int VoxelLocate (const G4SmartVoxelHeader *pHead, const G4ThreeVector &localPoint, const G4int blocked=-1) const
G4double DistanceToOutPhi (const G4ThreeVector &localPoint, const G4ThreeVector &localDirection, const G4double width, G4ExitNormal &foundNormal) const
G4double DistanceToOutRad (const G4ThreeVector &localPoint, const G4ThreeVector &localDirection, const G4double width, const G4double offset, const G4int replicaNo, G4ExitNormal &foundNormal) const
void SetPhiTransformation (const G4double ang, G4VPhysicalVolume *pVol=0) const
Private Attributes
G4bool fCheck
G4int fVerbose
G4double kCarTolerance
G4double kRadTolerance
G4double kAngTolerance
G4double halfkCarTolerance
G4double halfkRadTolerance
G4double halfkAngTolerance
G4double fMinStep
Detailed Description
Definition at line 81 of file G4ReplicaNavigation.hh.
Constructor & Destructor Documentation
G4ReplicaNavigation()
G4ReplicaNavigation::G4ReplicaNavigation ()
Definition at line 56 of file G4ReplicaNavigation.cc.
~G4ReplicaNavigation()
G4ReplicaNavigation::~G4ReplicaNavigation ()
Definition at line 72 of file G4ReplicaNavigation.cc.
Member Function Documentation
BackLocate()
EInside G4ReplicaNavigation::BackLocate (G4NavigationHistory & history, const G4ThreeVector & globalPoint, G4ThreeVector & localPoint, const G4bool & exiting, G4bool & notKnownInside) const
Definition at line 1246 of file G4ReplicaNavigation.cc.
Referenced by G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), and G4ITNavigator2::LocateGlobalPointAndSetup().
CheckMode()
void G4ReplicaNavigation::CheckMode (G4bool mode) inline
ComputeSafety()
G4double G4ReplicaNavigation::ComputeSafety (const G4ThreeVector & globalPoint, const G4ThreeVector & localPoint, G4NavigationHistory & history, const G4double pProposedMaxLength = DBL_MAX)
Definition at line 1157 of file G4ReplicaNavigation.cc.
Referenced by G4Navigator::ComputeSafety(), G4ITNavigator1::ComputeSafety(), and G4ITNavigator2::ComputeSafety().
ComputeStep()
G4double G4ReplicaNavigation::ComputeStep (const G4ThreeVector & globalPoint, const G4ThreeVector & globalDirection, const G4ThreeVector & localPoint, const G4ThreeVector & localDirection, const G4double currentProposedStepLength, G4double & newSafety, G4NavigationHistory & history, G4bool & validExitNormal, G4bool & calculatedExitNormal, G4ThreeVector & exitNormal, G4bool & exiting, G4bool & entering, G4VPhysicalVolume ** pBlockedPhysical, G4int & blockedReplicaNo)
Definition at line 753 of file G4ReplicaNavigation.cc.
Referenced by G4Navigator::ComputeStep(), G4ITNavigator1::ComputeStep(), and G4ITNavigator2::ComputeStep().
ComputeTransformation() [1/2]
void G4ReplicaNavigation::ComputeTransformation (const G4int replicaNo, G4VPhysicalVolume * pVol) const
Definition at line 709 of file G4ReplicaNavigation.cc.
ComputeTransformation() [2/2]
void G4ReplicaNavigation::ComputeTransformation (const G4int replicaNo, G4VPhysicalVolume * pVol, G4ThreeVector & point) const
Definition at line 653 of file G4ReplicaNavigation.cc.
Referenced by G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITNavigator2::LocateGlobalPointAndSetup(), G4Navigator::SetupHierarchy(), G4ITNavigator1::SetupHierarchy(), and G4ITNavigator2::SetupHierarchy().
DistanceToOut() [1/2]
G4double G4ReplicaNavigation::DistanceToOut (const G4VPhysicalVolume * pVol, const G4int replicaNo, const G4ThreeVector & localPoint) const
Definition at line 187 of file G4ReplicaNavigation.cc.
Referenced by ComputeSafety(), and ComputeStep().
DistanceToOut() [2/2]
G4double G4ReplicaNavigation::DistanceToOut (const G4VPhysicalVolume * pVol, const G4int replicaNo, const G4ThreeVector & localPoint, const G4ThreeVector & localDirection, G4ExitNormal & candidateNormal) const
Definition at line 253 of file G4ReplicaNavigation.cc.
DistanceToOutPhi()
G4double G4ReplicaNavigation::DistanceToOutPhi (const G4ThreeVector & localPoint, const G4ThreeVector & localDirection, const G4double width, G4ExitNormal & foundNormal) const private
Definition at line 327 of file G4ReplicaNavigation.cc.
Referenced by DistanceToOut().
DistanceToOutRad()
G4double G4ReplicaNavigation::DistanceToOutRad (const G4ThreeVector & localPoint, const G4ThreeVector & localDirection, const G4double width, const G4double offset, const G4int replicaNo, G4ExitNormal & foundNormal) const private
Definition at line 501 of file G4ReplicaNavigation.cc.
Referenced by DistanceToOut().
GetVerboseLevel()
G4int G4ReplicaNavigation::GetVerboseLevel () const inline
Inside()
EInside G4ReplicaNavigation::Inside (const G4VPhysicalVolume * pVol, const G4int replicaNo, const G4ThreeVector & localPoint) const
Definition at line 81 of file G4ReplicaNavigation.cc.
Referenced by BackLocate().
LevelLocate()
G4bool G4ReplicaNavigation::LevelLocate (G4NavigationHistory & history, const G4VPhysicalVolume * blockedVol, const G4int blockedNum, const G4ThreeVector & globalPoint, const G4ThreeVector * globalDirection, const G4bool pLocatedOnEdge, G4ThreeVector & localPoint) inline
Referenced by G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), and G4ITNavigator2::LocateGlobalPointAndSetup().
SetPhiTransformation()
void G4ReplicaNavigation::SetPhiTransformation (const G4double ang, G4VPhysicalVolume * pVol = 0) const inline private
Referenced by ComputeTransformation().
SetVerboseLevel()
void G4ReplicaNavigation::SetVerboseLevel (G4int level) inline
VoxelLocate()
G4int G4ReplicaNavigation::VoxelLocate (const G4SmartVoxelHeader * pHead, const G4ThreeVector & localPoint, const G4int blocked = -1) const inline private
Field Documentation
fCheck
G4bool G4ReplicaNavigation::fCheck private
Definition at line 174 of file G4ReplicaNavigation.hh.
Referenced by ComputeStep().
fMinStep
G4double G4ReplicaNavigation::fMinStep private
Definition at line 178 of file G4ReplicaNavigation.hh.
Referenced by ComputeStep(), and G4ReplicaNavigation().
fVerbose
G4int G4ReplicaNavigation::fVerbose private
Definition at line 175 of file G4ReplicaNavigation.hh.
halfkAngTolerance
G4double G4ReplicaNavigation::halfkAngTolerance private
Definition at line 178 of file G4ReplicaNavigation.hh.
Referenced by G4ReplicaNavigation(), and Inside().
halfkCarTolerance
G4double G4ReplicaNavigation::halfkCarTolerance private
Definition at line 178 of file G4ReplicaNavigation.hh.
Referenced by ComputeStep(), DistanceToOut(), DistanceToOutPhi(), G4ReplicaNavigation(), and Inside().
halfkRadTolerance
G4double G4ReplicaNavigation::halfkRadTolerance private
Definition at line 178 of file G4ReplicaNavigation.hh.
Referenced by DistanceToOutRad(), G4ReplicaNavigation(), and Inside().
kAngTolerance
G4double G4ReplicaNavigation::kAngTolerance private
Definition at line 178 of file G4ReplicaNavigation.hh.
Referenced by G4ReplicaNavigation().
kCarTolerance
G4double G4ReplicaNavigation::kCarTolerance private
Definition at line 178 of file G4ReplicaNavigation.hh.
Referenced by ComputeStep(), and G4ReplicaNavigation().
kRadTolerance
G4double G4ReplicaNavigation::kRadTolerance private
Definition at line 178 of file G4ReplicaNavigation.hh.
Referenced by G4ReplicaNavigation().
The documentation for this class was generated from the following files:
source/geometry/navigation/include/G4ReplicaNavigation.hh
source/geometry/navigation/src/G4ReplicaNavigation.cc