Geant4: source/processes/hadronic/models/lend/src/xDataTOM_importXML_axes.cc File Reference
xDataTOM_importXML_axes.cc File Reference
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <ctype.h>
#include "xDataTOM_importXML_private.h"
Functions
int xDataXML_axesElememtToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_axes *axes)
int xDataXML_axesToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_axes *axes)
Function Documentation
xDataXML_axesElememtToTOM()
int xDataXML_axesElememtToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_axes * axes)
Definition at line 20 of file xDataTOM_importXML_axes.cc.
Referenced by xDataXML_initializeData(), and xDataXML_XYsToTOM().
xDataXML_axesToTOM()
int xDataXML_axesToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_axes * axes)
Definition at line 45 of file xDataTOM_importXML_axes.cc.
Referenced by xDataXML_axesElememtToTOM().