Geant4: G4Cache< VALTYPE > Class Template Reference
G4Cache< VALTYPE > Class Template Reference
#include <G4Cache.hh>
Public Types
typedef VALTYPE value_type
Public Member Functions
G4Cache ()
G4Cache (const value_type &v)
virtual ~G4Cache ()
value_type & Get () const
void Put (const value_type &val) const
value_type Pop ()
G4Cache (const G4Cache &rhs)
G4Cache & operator= (const G4Cache &rhs)
Protected Member Functions
const G4int & GetId () const
Private Member Functions
value_type & GetCache () const
Private Attributes
G4int id
G4CacheReference< value_type > theCache
Static Private Attributes
static std::atomic< unsigned int > instancesctr
static std::atomic< unsigned int > dstrctr
Detailed Description
template<class VALTYPE>
class G4Cache< VALTYPE >
Definition at line 91 of file G4Cache.hh.
Member Typedef Documentation
value_type
template<class VALTYPE> typedef VALTYPE G4Cache< VALTYPE >::value_type
Definition at line 95 of file G4Cache.hh.
Constructor & Destructor Documentation
G4Cache() [1/3]
template<class V > G4Cache< V >::G4Cache ()
Definition at line 221 of file G4Cache.hh.
G4Cache() [2/3]
template<class VALTYPE> G4Cache< VALTYPE >::G4Cache (const value_type & v)
~G4Cache()
template<class V > G4Cache< V >::~G4Cache () virtual
Definition at line 279 of file G4Cache.hh.
G4Cache() [3/3]
template<class VALTYPE> G4Cache< VALTYPE >::G4Cache (const G4Cache< VALTYPE > & rhs)
Member Function Documentation
Get()
template<class V > V & G4Cache< V >::Get () const inline
Definition at line 325 of file G4Cache.hh.
Referenced by G4ParticleHPFinalState::adjust_final_state(), G4ParticleHPD2AInelasticFS::ApplyYourself(), G4ParticleHPT2AInelasticFS::ApplyYourself(), G4ParticleHPDAInelasticFS::ApplyYourself(), G4ParticleHPDInelasticFS::ApplyYourself(), G4ParticleHPHe3InelasticFS::ApplyYourself(), G4ParticleHPPDInelasticFS::ApplyYourself(), G4ParticleHPN2AInelasticFS::ApplyYourself(), G4ParticleHPN2PInelasticFS::ApplyYourself(), G4ParticleHPN3AInelasticFS::ApplyYourself(), G4ParticleHPNAInelasticFS::ApplyYourself(), G4ParticleHPND2AInelasticFS::ApplyYourself(), G4ParticleHPNDInelasticFS::ApplyYourself(), G4ParticleHPNHe3InelasticFS::ApplyYourself(), G4ParticleHPNPAInelasticFS::ApplyYourself(), G4ParticleHPNPInelasticFS::ApplyYourself(), G4ParticleHPNT2AInelasticFS::ApplyYourself(), G4ParticleHPNTInelasticFS::ApplyYourself(), G4ParticleHPNXInelasticFS::ApplyYourself(), G4ParticleHPPAInelasticFS::ApplyYourself(), G4ParticleHPNInelasticFS::ApplyYourself(), G4ParticleHPPInelasticFS::ApplyYourself(), G4ParticleHPPTInelasticFS::ApplyYourself(), G4ParticleHPTInelasticFS::ApplyYourself(), G4ParticleHP2N2AInelasticFS::ApplyYourself(), G4ParticleHP2NDInelasticFS::ApplyYourself(), G4ParticleHP2NInelasticFS::ApplyYourself(), G4ParticleHP2NPInelasticFS::ApplyYourself(), G4ParticleHP2PInelasticFS::ApplyYourself(), G4ParticleHP3AInelasticFS::ApplyYourself(), G4ParticleHP2NAInelasticFS::ApplyYourself(), G4ParticleHP2AInelasticFS::ApplyYourself(), G4ParticleHP3NAInelasticFS::ApplyYourself(), G4ParticleHP3NPInelasticFS::ApplyYourself(), G4ParticleHP4NInelasticFS::ApplyYourself(), G4ParticleHPAInelasticFS::ApplyYourself(), G4ParticleHP3NInelasticFS::ApplyYourself(), G4ParticleHPFissionFS::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4VectorCache< G4VCrossSectionDataSet * >::Begin(), G4MapCache< const G4ProcessManager *, G4BiasingProcessSharedData * >::Begin(), G4BiasingProcessInterface::BuildPhysicsTable(), G4BiasingProcessInterface::BuildWorkerPhysicsTable(), G4VectorCache< G4VCrossSectionDataSet * >::Clear(), G4ParticleHPInelasticCompFS::CompositeApply(), DetectorConstruction::ConstructSDandField(), ElectronBenchmarkDetector::ConstructSDandField(), LXeDetectorConstruction::ConstructSDandField(), F04DetectorConstruction::ConstructSDandField(), PurgMagDetectorConstruction::ConstructSDandField(), WLSDetectorConstruction::ConstructSDandField(), XrayFluoPlaneDetectorConstruction::ConstructSDandField(), DMXDetectorConstruction::ConstructSDandField(), XrayFluoMercuryDetectorConstruction::ConstructSDandField(), F03DetectorConstruction::ConstructSDandField(), F01DetectorConstruction::ConstructSDandField(), F02DetectorConstruction::ConstructSDandField(), XrayFluoDetectorConstruction::ConstructSDandField(), GammaRayTelDetectorConstruction::ConstructSDandField(), G4VectorCache< G4VCrossSectionDataSet * >::End(), G4MapCache< const G4ProcessManager *, G4BiasingProcessSharedData * >::End(), G4BiasingProcessInterface::EndTracking(), G4MapCache< const G4ProcessManager *, G4BiasingProcessSharedData * >::Erase(), G4MapCache< const G4ProcessManager *, G4BiasingProcessSharedData * >::Find(), G4VBiasingOperator::G4VBiasingOperator(), G4VectorCache< G4VCrossSectionDataSet * >::G4VectorCache(), G4BiasingOperationManager::GetBiasingOperations(), G4VBiasingOperator::GetBiasingOperators(), DetectorConstruction::GetMonopoleFieldSetup(), G4ParticleHPPhotonDist::GetPhotons(), G4MapCache< const G4ProcessManager *, G4BiasingProcessSharedData * >::Insert(), G4ThreadLocalSingleton< T >::Instance(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), G4ParticleHPContEnergyAngular::MeanEnergyOfThisInteraction(), G4PhaseSpaceDecayChannel::OneBodyDecayIt(), G4VectorCache< G4VCrossSectionDataSet * >::operator[](), G4VectorCache< G4VCrossSectionDataSet * >::Pop_back(), G4VectorCache< G4VCrossSectionDataSet * >::Push_back(), G4ParticleHPContEnergyAngular::Sample(), G4PenelopeBremsstrahlungFS::SampleGammaEnergy(), G4VectorCache< G4VCrossSectionDataSet * >::Size(), G4MapCache< const G4ProcessManager *, G4BiasingProcessSharedData * >::Size(), G4BiasingProcessInterface::StartTracking(), G4PhaseSpaceDecayChannel::ThreeBodyDecayIt(), G4PhaseSpaceDecayChannel::TwoBodyDecayIt(), G4ParticleHPInelasticCompFS::use_nresp71_model(), G4ParticleHPContEnergyAngular::~G4ParticleHPContEnergyAngular(), G4ParticleHPFinalState::~G4ParticleHPFinalState(), and G4ParticleHPPhotonDist::~G4ParticleHPPhotonDist().
GetCache()
template<class VALTYPE> value_type& G4Cache< VALTYPE >::GetCache () const inline private
Definition at line 130 of file G4Cache.hh.
Referenced by G4Cache< F02ElectricFieldSetup * >::operator=().
GetId()
template<class VALTYPE> const G4int& G4Cache< VALTYPE >::GetId () const inline protected
Definition at line 121 of file G4Cache.hh.
Referenced by G4MapCache< const G4ProcessManager *, G4BiasingProcessSharedData * >::~G4MapCache().
operator=()
template<class VALTYPE> G4Cache< V > & G4Cache< V >::operator= (const G4Cache< VALTYPE > & rhs)
Definition at line 251 of file G4Cache.hh.
Pop()
template<class V > V G4Cache< V >::Pop () inline
Definition at line 334 of file G4Cache.hh.
Put()
template<class VALTYPE> void G4Cache< V >::Put (const value_type & val) const inline
Definition at line 329 of file G4Cache.hh.
Referenced by G4ParticleHPFissionFS::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4BiasingProcessInterface::BuildPhysicsTable(), G4BiasingProcessInterface::BuildWorkerPhysicsTable(), G4ParticleHPInelasticCompFS::CompositeApply(), DetectorConstruction::ConstructSDandField(), LXeDetectorConstruction::ConstructSDandField(), F04DetectorConstruction::ConstructSDandField(), PurgMagDetectorConstruction::ConstructSDandField(), WLSDetectorConstruction::ConstructSDandField(), XrayFluoPlaneDetectorConstruction::ConstructSDandField(), DMXDetectorConstruction::ConstructSDandField(), XrayFluoMercuryDetectorConstruction::ConstructSDandField(), F03DetectorConstruction::ConstructSDandField(), F01DetectorConstruction::ConstructSDandField(), F02DetectorConstruction::ConstructSDandField(), XrayFluoDetectorConstruction::ConstructSDandField(), GammaRayTelDetectorConstruction::ConstructSDandField(), G4PhaseSpaceDecayChannel::DecayIt(), DMXDetectorConstruction::DMXDetectorConstruction(), G4BiasingProcessInterface::EndTracking(), G4BiasingProcessInterface::G4BiasingProcessInterface(), G4ParticleHPContEnergyAngular::G4ParticleHPContEnergyAngular(), G4ParticleHPFinalState::G4ParticleHPFinalState(), G4ParticleHPPhotonDist::G4ParticleHPPhotonDist(), G4PenelopeBremsstrahlungFS::G4PenelopeBremsstrahlungFS(), G4ThreadLocalSingleton< T >::G4ThreadLocalSingleton(), G4VBiasingOperator::G4VBiasingOperator(), GammaRayTelDetectorConstruction::GammaRayTelDetectorConstruction(), G4ThreadLocalSingleton< T >::Instance(), G4ParticleHPContEnergyAngular::MeanEnergyOfThisInteraction(), PurgMagDetectorConstruction::PurgMagDetectorConstruction(), G4ParticleHPContEnergyAngular::Sample(), G4PenelopeBremsstrahlungFS::SampleGammaEnergy(), G4BiasingProcessInterface::StartTracking(), and XrayFluoDetectorConstruction::XrayFluoDetectorConstruction().
Field Documentation
dstrctr
template<class VALTYPE> std::atomic< unsigned int > G4Cache< V >::dstrctr static private
Definition at line 128 of file G4Cache.hh.
id
template<class VALTYPE> G4int G4Cache< VALTYPE >::id private
Definition at line 125 of file G4Cache.hh.
Referenced by G4Cache< F02ElectricFieldSetup * >::GetId().
instancesctr
template<class VALTYPE> std::atomic< unsigned int > G4Cache< V >::instancesctr static private
Definition at line 127 of file G4Cache.hh.
theCache
template<class VALTYPE> G4CacheReference<value_type> G4Cache< VALTYPE >::theCache mutable private
Definition at line 126 of file G4Cache.hh.
Referenced by G4Cache< F02ElectricFieldSetup * >::GetCache().
The documentation for this class was generated from the following file:
source/global/management/include/G4Cache.hh