Geant4: MedicalBeam Class Reference
MedicalBeam Class Reference
#include <MedicalBeam.hh>
Public Types
enum FieldShape {
SQUARE =0, CIRCLE, kSQUARE =0, kCIRCLE,
kSQUARE =0, kCIRCLE, kSQUARE =0, kCIRCLE
}
enum FieldShape {
SQUARE =0, CIRCLE, kSQUARE =0, kCIRCLE,
kSQUARE =0, kCIRCLE, kSQUARE =0, kCIRCLE
}
enum FieldShape {
SQUARE =0, CIRCLE, kSQUARE =0, kCIRCLE,
kSQUARE =0, kCIRCLE, kSQUARE =0, kCIRCLE
}
enum FieldShape {
SQUARE =0, CIRCLE, kSQUARE =0, kCIRCLE,
kSQUARE =0, kCIRCLE, kSQUARE =0, kCIRCLE
}
Public Member Functions
MedicalBeam ()
~MedicalBeam ()
void SetParticleDefinition (G4ParticleDefinition *pd)
const G4ParticleDefinition * GetParticleDefinition () const
void SetKineticE (G4double e)
G4double GetKineticE () const
void SetSourcePosition (const G4ThreeVector &pos)
G4ThreeVector GetSourcePosition () const
void SetFieldShape (FieldShape shape)
FieldShape GetFieldShape () const
void SetSSD (G4double ssd)
G4double GetSSD () const
void SetFieldXY (G4double fx, G4double fy)
G4double GetFieldX () const
G4double GetFieldY () const
void SetFieldR (G4double r)
G4double GetFieldR () const
virtual void GeneratePrimaries (G4Event *anEvent)
MedicalBeam ()
~MedicalBeam ()
void SetParticleDefinition (G4ParticleDefinition *pd)
const G4ParticleDefinition * GetParticleDefinition () const
void SetKineticE (G4double e)
G4double GetKineticE () const
void SetSourcePosition (const G4ThreeVector &pos)
G4ThreeVector GetSourcePosition () const
void SetFieldShape (FieldShape shape)
FieldShape GetFieldShape () const
void SetSSD (G4double ssd)
G4double GetSSD () const
void SetFieldXY (G4double fx, G4double fy)
G4double GetFieldX () const
G4double GetFieldY () const
void SetFieldR (G4double r)
G4double GetFieldR () const
virtual void GeneratePrimaries (G4Event *anEvent)
MedicalBeam ()
~MedicalBeam ()
void SetParticleDefinition (G4ParticleDefinition *pd)
const G4ParticleDefinition * GetParticleDefinition () const
void SetKineticE (G4double e)
G4double GetKineticE () const
void SetSourcePosition (const G4ThreeVector &pos)
G4ThreeVector GetSourcePosition () const
void SetFieldShape (FieldShape shape)
FieldShape GetFieldShape () const
void SetSSD (G4double ssd)
G4double GetSSD () const
void SetFieldXY (G4double fx, G4double fy)
G4double GetFieldX () const
G4double GetFieldY () const
void SetFieldR (G4double r)
G4double GetFieldR () const
virtual void GeneratePrimaries (G4Event *anEvent)
MedicalBeam ()
~MedicalBeam ()
void SetParticleDefinition (G4ParticleDefinition *pd)
const G4ParticleDefinition * GetParticleDefinition () const
void SetKineticE (G4double e)
G4double GetKineticE () const
void SetSourcePosition (const G4ThreeVector &pos)
G4ThreeVector GetSourcePosition () const
void SetFieldShape (FieldShape shape)
FieldShape GetFieldShape () const
void SetSSD (G4double ssd)
G4double GetSSD () const
void SetFieldXY (G4double fx, G4double fy)
G4double GetFieldX () const
G4double GetFieldY () const
void SetFieldR (G4double r)
G4double GetFieldR () const
virtual void GeneratePrimaries (G4Event *anEvent)
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Protected Member Functions
G4ThreeVector GenerateBeamDirection () const
Protected Attributes
G4ParticleDefinition * particle
G4double kineticE
G4ThreeVector sourcePosition
G4double SSD
FieldShape fieldShape
G4double fieldXY [2]
G4double fieldR
Private Member Functions
G4ThreeVector GenerateBeamDirection () const
G4ThreeVector GenerateBeamDirection () const
G4ThreeVector GenerateBeamDirection () const
Private Attributes
G4ParticleDefinition * fparticle
G4double fkineticE
G4ThreeVector fsourcePosition
G4double fSSD
FieldShape ffieldShape
G4double ffieldXY [2]
G4double ffieldR
Detailed Description
Definition at line 45 of file MedicalBeam.hh.
Member Enumeration Documentation
FieldShape [1/4]
enum MedicalBeam::FieldShape
Enumerator
SQUARE
CIRCLE
kSQUARE
kCIRCLE
kSQUARE
kCIRCLE
kSQUARE
kCIRCLE
Definition at line 41 of file MedicalBeam.hh.
FieldShape [2/4]
enum MedicalBeam::FieldShape
Enumerator
SQUARE
CIRCLE
kSQUARE
kCIRCLE
kSQUARE
kCIRCLE
kSQUARE
kCIRCLE
Definition at line 41 of file MedicalBeam.hh.
FieldShape [3/4]
enum MedicalBeam::FieldShape
Enumerator
SQUARE
CIRCLE
kSQUARE
kCIRCLE
kSQUARE
kCIRCLE
kSQUARE
kCIRCLE
Definition at line 41 of file MedicalBeam.hh.
FieldShape [4/4]
enum MedicalBeam::FieldShape
Enumerator
SQUARE
CIRCLE
kSQUARE
kCIRCLE
kSQUARE
kCIRCLE
kSQUARE
kCIRCLE
Definition at line 47 of file MedicalBeam.hh.
Constructor & Destructor Documentation
MedicalBeam() [1/4]
MedicalBeam::MedicalBeam ()
Definition at line 48 of file MedicalBeam.cc.
~MedicalBeam() [1/4]
MedicalBeam::~MedicalBeam ()
Definition at line 62 of file MedicalBeam.cc.
MedicalBeam() [2/4]
MedicalBeam::MedicalBeam ()
~MedicalBeam() [2/4]
MedicalBeam::~MedicalBeam ()
MedicalBeam() [3/4]
MedicalBeam::MedicalBeam ()
~MedicalBeam() [3/4]
MedicalBeam::~MedicalBeam ()
MedicalBeam() [4/4]
MedicalBeam::MedicalBeam ()
~MedicalBeam() [4/4]
MedicalBeam::~MedicalBeam ()
Member Function Documentation
GenerateBeamDirection() [1/4]
G4ThreeVector MedicalBeam::GenerateBeamDirection () const protected
Definition at line 69 of file MedicalBeam.cc.
Referenced by GeneratePrimaries().
GenerateBeamDirection() [2/4]
G4ThreeVector MedicalBeam::GenerateBeamDirection () const private
GenerateBeamDirection() [3/4]
G4ThreeVector MedicalBeam::GenerateBeamDirection () const private
GenerateBeamDirection() [4/4]
G4ThreeVector MedicalBeam::GenerateBeamDirection () const private
GeneratePrimaries() [1/4]
virtual void MedicalBeam::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
GeneratePrimaries() [2/4]
virtual void MedicalBeam::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
GeneratePrimaries() [3/4]
virtual void MedicalBeam::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
GeneratePrimaries() [4/4]
void MedicalBeam::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 111 of file MedicalBeam.cc.
GetFieldR() [1/4]
G4double MedicalBeam::GetFieldR () const
GetFieldR() [2/4]
G4double MedicalBeam::GetFieldR () const
GetFieldR() [3/4]
G4double MedicalBeam::GetFieldR () const
GetFieldR() [4/4]
G4double MedicalBeam::GetFieldR () const inline
Definition at line 139 of file MedicalBeam.hh.
Referenced by BOOST_PYTHON_MODULE().
GetFieldShape() [1/4]
FieldShape MedicalBeam::GetFieldShape () const
GetFieldShape() [2/4]
FieldShape MedicalBeam::GetFieldShape () const
GetFieldShape() [3/4]
FieldShape MedicalBeam::GetFieldShape () const
GetFieldShape() [4/4]
MedicalBeam::FieldShape MedicalBeam::GetFieldShape () const inline
Definition at line 118 of file MedicalBeam.hh.
Referenced by BOOST_PYTHON_MODULE().
GetFieldX() [1/4]
G4double MedicalBeam::GetFieldX () const
GetFieldX() [2/4]
G4double MedicalBeam::GetFieldX () const
GetFieldX() [3/4]
G4double MedicalBeam::GetFieldX () const
GetFieldX() [4/4]
G4double MedicalBeam::GetFieldX () const inline
Definition at line 130 of file MedicalBeam.hh.
Referenced by BOOST_PYTHON_MODULE().
GetFieldY() [1/4]
G4double MedicalBeam::GetFieldY () const
GetFieldY() [2/4]
G4double MedicalBeam::GetFieldY () const
GetFieldY() [3/4]
G4double MedicalBeam::GetFieldY () const
GetFieldY() [4/4]
G4double MedicalBeam::GetFieldY () const inline
Definition at line 133 of file MedicalBeam.hh.
Referenced by BOOST_PYTHON_MODULE().
GetKineticE() [1/4]
G4double MedicalBeam::GetKineticE () const
GetKineticE() [2/4]
G4double MedicalBeam::GetKineticE () const
GetKineticE() [3/4]
G4double MedicalBeam::GetKineticE () const
GetKineticE() [4/4]
G4double MedicalBeam::GetKineticE () const inline
Definition at line 106 of file MedicalBeam.hh.
Referenced by BOOST_PYTHON_MODULE().
GetParticleDefinition() [1/4]
const G4ParticleDefinition* MedicalBeam::GetParticleDefinition () const
GetParticleDefinition() [2/4]
const G4ParticleDefinition* MedicalBeam::GetParticleDefinition () const
GetParticleDefinition() [3/4]
const G4ParticleDefinition* MedicalBeam::GetParticleDefinition () const
GetParticleDefinition() [4/4]
const G4ParticleDefinition * MedicalBeam::GetParticleDefinition () const inline
Definition at line 100 of file MedicalBeam.hh.
GetSourcePosition() [1/4]
G4ThreeVector MedicalBeam::GetSourcePosition () const
GetSourcePosition() [2/4]
G4ThreeVector MedicalBeam::GetSourcePosition () const
GetSourcePosition() [3/4]
G4ThreeVector MedicalBeam::GetSourcePosition () const
GetSourcePosition() [4/4]
G4ThreeVector MedicalBeam::GetSourcePosition () const inline
Definition at line 112 of file MedicalBeam.hh.
Referenced by BOOST_PYTHON_MODULE().
GetSSD() [1/4]
G4double MedicalBeam::GetSSD () const
GetSSD() [2/4]
G4double MedicalBeam::GetSSD () const
GetSSD() [3/4]
G4double MedicalBeam::GetSSD () const
GetSSD() [4/4]
G4double MedicalBeam::GetSSD () const inline
Definition at line 124 of file MedicalBeam.hh.
Referenced by BOOST_PYTHON_MODULE().
SetFieldR() [1/4]
void MedicalBeam::SetFieldR (G4double r)
SetFieldR() [2/4]
void MedicalBeam::SetFieldR (G4double r)
SetFieldR() [3/4]
void MedicalBeam::SetFieldR (G4double r)
SetFieldR() [4/4]
void MedicalBeam::SetFieldR (G4double r) inline
Definition at line 136 of file MedicalBeam.hh.
Referenced by BOOST_PYTHON_MODULE().
SetFieldShape() [1/4]
void MedicalBeam::SetFieldShape (FieldShape shape)
SetFieldShape() [2/4]
void MedicalBeam::SetFieldShape (FieldShape shape)
SetFieldShape() [3/4]
void MedicalBeam::SetFieldShape (FieldShape shape)
SetFieldShape() [4/4]
void MedicalBeam::SetFieldShape (MedicalBeam::FieldShape shape) inline
Definition at line 115 of file MedicalBeam.hh.
Referenced by BOOST_PYTHON_MODULE().
SetFieldXY() [1/4]
void MedicalBeam::SetFieldXY (G4double fx, G4double fy)
SetFieldXY() [2/4]
void MedicalBeam::SetFieldXY (G4double fx, G4double fy)
SetFieldXY() [3/4]
void MedicalBeam::SetFieldXY (G4double fx, G4double fy)
SetFieldXY() [4/4]
void MedicalBeam::SetFieldXY (G4double fx, G4double fy) inline
Definition at line 127 of file MedicalBeam.hh.
SetKineticE() [1/4]
void MedicalBeam::SetKineticE (G4double e)
SetKineticE() [2/4]
void MedicalBeam::SetKineticE (G4double e)
SetKineticE() [3/4]
void MedicalBeam::SetKineticE (G4double e)
SetKineticE() [4/4]
void MedicalBeam::SetKineticE (G4double e) inline
Definition at line 103 of file MedicalBeam.hh.
Referenced by BOOST_PYTHON_MODULE().
SetParticleDefinition() [1/4]
void MedicalBeam::SetParticleDefinition (G4ParticleDefinition * pd)
SetParticleDefinition() [2/4]
void MedicalBeam::SetParticleDefinition (G4ParticleDefinition * pd)
SetParticleDefinition() [3/4]
void MedicalBeam::SetParticleDefinition (G4ParticleDefinition * pd)
SetParticleDefinition() [4/4]
void MedicalBeam::SetParticleDefinition (G4ParticleDefinition * pd) inline
Definition at line 97 of file MedicalBeam.hh.
SetSourcePosition() [1/4]
void MedicalBeam::SetSourcePosition (const G4ThreeVector & pos)
SetSourcePosition() [2/4]
void MedicalBeam::SetSourcePosition (const G4ThreeVector & pos)
SetSourcePosition() [3/4]
void MedicalBeam::SetSourcePosition (const G4ThreeVector & pos)
SetSourcePosition() [4/4]
void MedicalBeam::SetSourcePosition (const G4ThreeVector & pos) inline
Definition at line 109 of file MedicalBeam.hh.
Referenced by BOOST_PYTHON_MODULE().
SetSSD() [1/4]
void MedicalBeam::SetSSD (G4double ssd)
SetSSD() [2/4]
void MedicalBeam::SetSSD (G4double ssd)
SetSSD() [3/4]
void MedicalBeam::SetSSD (G4double ssd)
SetSSD() [4/4]
void MedicalBeam::SetSSD (G4double ssd) inline
Definition at line 121 of file MedicalBeam.hh.
Referenced by BOOST_PYTHON_MODULE().
Field Documentation
ffieldR
G4double MedicalBeam::ffieldR private
Definition at line 83 of file MedicalBeam.hh.
ffieldShape
FieldShape MedicalBeam::ffieldShape private
Definition at line 81 of file MedicalBeam.hh.
ffieldXY
G4double MedicalBeam::ffieldXY private
Definition at line 82 of file MedicalBeam.hh.
fieldR
G4double MedicalBeam::fieldR protected
Definition at line 57 of file MedicalBeam.hh.
Referenced by GenerateBeamDirection(), GetFieldR(), and SetFieldR().
fieldShape
FieldShape MedicalBeam::fieldShape protected
Definition at line 55 of file MedicalBeam.hh.
Referenced by GenerateBeamDirection(), GetFieldShape(), and SetFieldShape().
fieldXY
G4double MedicalBeam::fieldXY[2] protected
Definition at line 56 of file MedicalBeam.hh.
Referenced by GenerateBeamDirection(), GetFieldX(), GetFieldY(), MedicalBeam(), and SetFieldXY().
fkineticE
G4double MedicalBeam::fkineticE private
Definition at line 77 of file MedicalBeam.hh.
fparticle
G4ParticleDefinition * MedicalBeam::fparticle private
Definition at line 76 of file MedicalBeam.hh.
fsourcePosition
G4ThreeVector MedicalBeam::fsourcePosition private
Definition at line 78 of file MedicalBeam.hh.
fSSD
G4double MedicalBeam::fSSD private
Definition at line 80 of file MedicalBeam.hh.
kineticE
G4double MedicalBeam::kineticE protected
Definition at line 51 of file MedicalBeam.hh.
Referenced by GeneratePrimaries(), GetKineticE(), and SetKineticE().
particle
G4ParticleDefinition* MedicalBeam::particle protected
Definition at line 50 of file MedicalBeam.hh.
Referenced by GeneratePrimaries(), GetParticleDefinition(), and SetParticleDefinition().
sourcePosition
G4ThreeVector MedicalBeam::sourcePosition protected
Definition at line 52 of file MedicalBeam.hh.
Referenced by GeneratePrimaries(), GetSourcePosition(), and SetSourcePosition().
SSD
G4double MedicalBeam::SSD protected
Definition at line 54 of file MedicalBeam.hh.
Referenced by GenerateBeamDirection(), GetSSD(), and SetSSD().
The documentation for this class was generated from the following files:
environments/g4py/site-modules/primaries/MedicalBeam/MedicalBeam.hh
environments/g4py/site-modules/primaries/MedicalBeam/MedicalBeam.cc