Geant4: ExN02PhysicsList Class Reference
ExN02PhysicsList Class Reference
#include <ExN02PhysicsList.hh>
Public Member Functions
ExN02PhysicsList ()
~ExN02PhysicsList ()
Public Member Functions inherited from G4VUserPhysicsList
G4VUserPhysicsList ()
virtual ~G4VUserPhysicsList ()
G4VUserPhysicsList (const G4VUserPhysicsList &)
G4VUserPhysicsList & operator= (const G4VUserPhysicsList &)
void Construct ()
void UseCoupledTransportation (G4bool vl=true)
void SetDefaultCutValue (G4double newCutValue)
G4double GetDefaultCutValue () const
void BuildPhysicsTable ()
void PreparePhysicsTable (G4ParticleDefinition *)
void BuildPhysicsTable (G4ParticleDefinition *)
G4bool StorePhysicsTable (const G4String &directory=".")
G4bool IsPhysicsTableRetrieved () const
G4bool IsStoredInAscii () const
const G4String & GetPhysicsTableDirectory () const
void SetPhysicsTableRetrieved (const G4String &directory="")
void SetStoredInAscii ()
void ResetPhysicsTableRetrieved ()
void ResetStoredInAscii ()
void DumpList () const
void DumpCutValuesTable (G4int flag=1)
void DumpCutValuesTableIfRequested ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetCutsWithDefault ()
void SetCutValue (G4double aCut, const G4String &pname)
G4double GetCutValue (const G4String &pname) const
void SetCutValue (G4double aCut, const G4String &pname, const G4String &rname)
void SetParticleCuts (G4double cut, G4ParticleDefinition *particle, G4Region *region=0)
void SetParticleCuts (G4double cut, const G4String &particleName, G4Region *region=0)
void SetCutsForRegion (G4double aCut, const G4String &rname)
void ResetCuts ()
obsolete methods
void SetApplyCuts (G4bool value, const G4String &name)
G4bool GetApplyCuts (const G4String &name) const
void RemoveProcessManager ()
void AddProcessManager (G4ParticleDefinition *newParticle, G4ProcessManager *newManager=0)
void CheckParticleList ()
void DisableCheckParticleList ()
G4int GetInstanceID () const
virtual void InitializeWorker ()
virtual void TerminateWorker ()
Protected Member Functions
void ConstructParticle ()
void ConstructProcess ()
void SetCuts ()
void ConstructBosons ()
void ConstructLeptons ()
void ConstructMesons ()
void ConstructBaryons ()
void ConstructGeneral ()
void ConstructEM ()
void AddStepMax ()
Protected Member Functions inherited from G4VUserPhysicsList
void AddTransportation ()
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
void BuildIntegralPhysicsTable (G4VProcess *, G4ParticleDefinition *)
virtual void RetrievePhysicsTable (G4ParticleDefinition *, const G4String &directory, G4bool ascii=false)
void InitializeProcessManager ()
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
Additional Inherited Members
Static Public Member Functions inherited from G4VUserPhysicsList
static const G4VUPLManager & GetSubInstanceManager ()
Protected Attributes inherited from G4VUserPhysicsList
G4ParticleTable * theParticleTable
G4int verboseLevel
G4double defaultCutValue
G4bool isSetDefaultCutValue
G4ProductionCutsTable * fCutsTable
G4bool fRetrievePhysicsTable
G4bool fStoredInAscii
G4bool fIsCheckedForRetrievePhysicsTable
G4bool fIsRestoredCutValues
G4String directoryPhysicsTable
G4bool fDisableCheckParticleList
G4int g4vuplInstanceID
Static Protected Attributes inherited from G4VUserPhysicsList
static G4RUN_DLL G4VUPLManager subInstanceManager
Detailed Description
Definition at line 42 of file ExN02PhysicsList.hh.
Constructor & Destructor Documentation
ExN02PhysicsList()
ExN02PhysicsList::ExN02PhysicsList ()
Definition at line 42 of file ExN02PhysicsList.cc.
~ExN02PhysicsList()
ExN02PhysicsList::~ExN02PhysicsList ()
Definition at line 50 of file ExN02PhysicsList.cc.
Member Function Documentation
AddStepMax()
void ExN02PhysicsList::AddStepMax () protected
Definition at line 258 of file ExN02PhysicsList.cc.
Referenced by ConstructProcess().
ConstructBaryons()
void ExN02PhysicsList::ConstructBaryons () protected
Definition at line 120 of file ExN02PhysicsList.cc.
Referenced by ConstructParticle().
ConstructBosons()
void ExN02PhysicsList::ConstructBosons () protected
Definition at line 70 of file ExN02PhysicsList.cc.
Referenced by ConstructParticle().
ConstructEM()
void ExN02PhysicsList::ConstructEM () protected
Definition at line 165 of file ExN02PhysicsList.cc.
Referenced by ConstructProcess().
ConstructGeneral()
void ExN02PhysicsList::ConstructGeneral () protected
Definition at line 235 of file ExN02PhysicsList.cc.
Referenced by ConstructProcess().
ConstructLeptons()
void ExN02PhysicsList::ConstructLeptons () protected
Definition at line 82 of file ExN02PhysicsList.cc.
Referenced by ConstructParticle().
ConstructMesons()
void ExN02PhysicsList::ConstructMesons () protected
Definition at line 101 of file ExN02PhysicsList.cc.
Referenced by ConstructParticle().
ConstructParticle()
void ExN02PhysicsList::ConstructParticle (void) protected virtual
Implements G4VUserPhysicsList.
Definition at line 55 of file ExN02PhysicsList.cc.
ConstructProcess()
void ExN02PhysicsList::ConstructProcess (void) protected virtual
Implements G4VUserPhysicsList.
Definition at line 132 of file ExN02PhysicsList.cc.
SetCuts()
void ExN02PhysicsList::SetCuts () protected virtual
Reimplemented from G4VUserPhysicsList.
Definition at line 280 of file ExN02PhysicsList.cc.
The documentation for this class was generated from the following files:
examples/extended/parallel/TopC/ParN02/include/ExN02PhysicsList.hh
examples/extended/parallel/TopC/ParN02/src/ExN02PhysicsList.cc