Geant4: G4DNAMolecularReactionTable Class Reference
G4DNAMolecularReactionTable Class Reference
G4DNAMolecularReactionTable sorts out the G4DNAMolecularReactionData for bimolecular reaction.
#include <G4DNAMolecularReactionTable.hh>
Public Member Functions
virtual ~G4DNAMolecularReactionTable ()
void SetReaction (G4double observedReactionRate, G4MolecularConfiguration *reactive1, G4MolecularConfiguration *reactive2)
Define a reaction : First argument : reaction rate Second argument : reactant 1 Third argument : reactant 2 Fourth argument : a std::vector holding the molecular products if this last argument is NULL then it will be interpreted as a reaction giving no products.
void SetReaction (G4DNAMolecularReactionData *)
const G4DNAMolecularReactionData * GetReactionData (G4MolecularConfiguration *, G4MolecularConfiguration *) const
const G4DNAMolecularReactionData * GetReactionData (const G4String &, const G4String &) const
const G4DNAMolecularReactionData * GetReaction (int reactionID) const
size_t GetNReactions () const
const std::vector< G4MolecularConfiguration * > * CanReactWith (G4MolecularConfiguration *) const
Given a molecule's type, it returns with which a reaction is allowed.
const std::map< G4MolecularConfiguration *, const G4DNAMolecularReactionData * > * GetReativesNData (G4MolecularConfiguration *) const
const std::vector< const G4DNAMolecularReactionData * > * GetReactionData (G4MolecularConfiguration *) const
const std::map< G4MolecularConfiguration *, std::map< G4MolecularConfiguration *, const G4DNAMolecularReactionData * > > & GetAllReactionData ()
const std::vector< const G4DNAMolecularReactionData * > & GetVectorOfReactionData ()
void ScaleReactionRateForNewTemperature (double temp_K)
void PrintTable (G4VDNAReactionModel *=0)
Public Member Functions inherited from G4ITReactionTable
G4ITReactionTable ()
Default constructor.
virtual ~G4ITReactionTable ()
Default destructor.
G4ITReactionTable (const G4ITReactionTable &)
Copy constructor.
G4ITReactionTable & operator= (const G4ITReactionTable &)
Assignment operator.
Static Public Member Functions
static G4DNAMolecularReactionTable * GetReactionTable ()
static G4DNAMolecularReactionTable * Instance ()
static void DeleteInstance ()
Protected Types
typedef std::map< G4MolecularConfiguration *, std::map< G4MolecularConfiguration *, const G4DNAMolecularReactionData * > > ReactionDataMap
typedef std::map< G4MolecularConfiguration *, std::vector< G4MolecularConfiguration * > > ReactivesMV
typedef std::map< G4MolecularConfiguration *, std::vector< const G4DNAMolecularReactionData * > > ReactionDataMV
Protected Member Functions
G4DNAMolecularReactionTable ()
Protected Attributes
G4bool fVerbose
ReactionDataMap fReactionData
ReactivesMV fReactantsMV
ReactionDataMV fReactionDataMV
std::vector< const G4DNAMolecularReactionData * > fVectorOfReactionData
G4ReactionTableMessenger * fpMessenger
Static Protected Attributes
static G4DNAMolecularReactionTable * fInstance
Detailed Description
G4DNAMolecularReactionTable sorts out the G4DNAMolecularReactionData for bimolecular reaction.
Definition at line 198 of file G4DNAMolecularReactionTable.hh.
Member Typedef Documentation
ReactionDataMap
typedef std::map<G4MolecularConfiguration*, std::map<G4MolecularConfiguration*, const G4DNAMolecularReactionData*> > G4DNAMolecularReactionTable::ReactionDataMap protected
Definition at line 274 of file G4DNAMolecularReactionTable.hh.
ReactionDataMV
typedef std::map<G4MolecularConfiguration*, std::vector<const G4DNAMolecularReactionData*> > G4DNAMolecularReactionTable::ReactionDataMV protected
Definition at line 278 of file G4DNAMolecularReactionTable.hh.
ReactivesMV
typedef std::map<G4MolecularConfiguration*, std::vector<G4MolecularConfiguration*> > G4DNAMolecularReactionTable::ReactivesMV protected
Definition at line 276 of file G4DNAMolecularReactionTable.hh.
Constructor & Destructor Documentation
G4DNAMolecularReactionTable()
G4DNAMolecularReactionTable::G4DNAMolecularReactionTable () protected
Definition at line 243 of file G4DNAMolecularReactionTable.cc.
Referenced by GetReactionTable(), and Instance().
~G4DNAMolecularReactionTable()
G4DNAMolecularReactionTable::~G4DNAMolecularReactionTable () virtual
Definition at line 255 of file G4DNAMolecularReactionTable.cc.
Member Function Documentation
CanReactWith()
const std::vector< G4MolecularConfiguration * > * G4DNAMolecularReactionTable::CanReactWith (G4MolecularConfiguration * aMolecule) const
Given a molecule's type, it returns with which a reaction is allowed.
Definition at line 544 of file G4DNAMolecularReactionTable.cc.
Referenced by G4DNAMoleculeEncounterStepper::CalculateStep(), and PrintTable().
DeleteInstance()
void G4DNAMolecularReactionTable::DeleteInstance () static
Definition at line 233 of file G4DNAMolecularReactionTable.cc.
Referenced by G4DNAChemistryManager::Clear().
GetAllReactionData()
const std::map<G4MolecularConfiguration*, std::map<G4MolecularConfiguration*, const G4DNAMolecularReactionData*> >& G4DNAMolecularReactionTable::GetAllReactionData () inline
Definition at line 252 of file G4DNAMolecularReactionTable.hh.
GetNReactions()
size_t G4DNAMolecularReactionTable::GetNReactions () const inline
Definition at line 233 of file G4DNAMolecularReactionTable.hh.
GetReaction()
const G4DNAMolecularReactionData * G4DNAMolecularReactionTable::GetReaction (int reactionID) const
Definition at line 744 of file G4DNAMolecularReactionTable.cc.
GetReactionData() [1/3]
const G4DNAMolecularReactionData * G4DNAMolecularReactionTable::GetReactionData (const G4String & mol1, const G4String & mol2) const
Definition at line 666 of file G4DNAMolecularReactionTable.cc.
GetReactionData() [2/3]
const std::vector< const G4DNAMolecularReactionData * > * G4DNAMolecularReactionTable::GetReactionData (G4MolecularConfiguration * molecule) const
Definition at line 640 of file G4DNAMolecularReactionTable.cc.
GetReactionData() [3/3]
const G4DNAMolecularReactionData * G4DNAMolecularReactionTable::GetReactionData (G4MolecularConfiguration * reactant1, G4MolecularConfiguration * reactant2) const
Definition at line 501 of file G4DNAMolecularReactionTable.cc.
Referenced by GetReactionData(), G4DNASmoluchowskiReactionModel::GetReactionRadius(), G4DNASmoluchowskiReactionModel::Initialise(), G4DNASmoluchowskiReactionModel::InitialiseToPrint(), and G4DNAMolecularReaction::MakeReaction().
GetReactionTable()
G4DNAMolecularReactionTable * G4DNAMolecularReactionTable::GetReactionTable () static
Definition at line 211 of file G4DNAMolecularReactionTable.cc.
Referenced by G4DNAMolecularStepByStepModel::Initialize(), G4DNAChemistryManager::InitializeMaster(), and G4DNAChemistryManager::InitializeThread().
GetReativesNData()
const std::map< G4MolecularConfiguration *, const G4DNAMolecularReactionData * > * G4DNAMolecularReactionTable::GetReativesNData (G4MolecularConfiguration * molecule) const
Definition at line 594 of file G4DNAMolecularReactionTable.cc.
GetVectorOfReactionData()
const std::vector<const G4DNAMolecularReactionData*>& G4DNAMolecularReactionTable::GetVectorOfReactionData () inline
Definition at line 258 of file G4DNAMolecularReactionTable.hh.
Instance()
G4DNAMolecularReactionTable * G4DNAMolecularReactionTable::Instance (void) static
Definition at line 222 of file G4DNAMolecularReactionTable.cc.
Referenced by G4DNAChemistryManager::SetGlobalTemperature().
PrintTable()
void G4DNAMolecularReactionTable::PrintTable (G4VDNAReactionModel * pReactionModel = 0)
Definition at line 325 of file G4DNAMolecularReactionTable.cc.
Referenced by G4EmDNAChemistry::ConstructTimeStepModel(), G4EmDNAChemistry_option1::ConstructTimeStepModel(), and G4ReactionTableMessenger::SetNewValue().
ScaleReactionRateForNewTemperature()
void G4DNAMolecularReactionTable::ScaleReactionRateForNewTemperature (double temp_K)
Definition at line 712 of file G4DNAMolecularReactionTable.cc.
SetReaction() [1/2]
void G4DNAMolecularReactionTable::SetReaction (G4DNAMolecularReactionData * reactionData)
Definition at line 293 of file G4DNAMolecularReactionTable.cc.
SetReaction() [2/2]
void G4DNAMolecularReactionTable::SetReaction (G4double observedReactionRate, G4MolecularConfiguration * reactive1, G4MolecularConfiguration * reactive2)
Define a reaction : First argument : reaction rate Second argument : reactant 1 Third argument : reactant 2 Fourth argument : a std::vector holding the molecular products if this last argument is NULL then it will be interpreted as a reaction giving no products.
Definition at line 314 of file G4DNAMolecularReactionTable.cc.
Referenced by G4EmDNAChemistry::ConstructReactionTable(), G4EmDNAChemistry_option1::ConstructReactionTable(), and G4ReactionTableMessenger::SetNewValue().
Field Documentation
fInstance
G4DNAMolecularReactionTable * G4DNAMolecularReactionTable::fInstance static protected
Definition at line 202 of file G4DNAMolecularReactionTable.hh.
Referenced by DeleteInstance(), GetReactionTable(), and Instance().
fpMessenger
G4ReactionTableMessenger* G4DNAMolecularReactionTable::fpMessenger protected
Definition at line 284 of file G4DNAMolecularReactionTable.hh.
Referenced by G4DNAMolecularReactionTable(), and ~G4DNAMolecularReactionTable().
fReactantsMV
ReactivesMV G4DNAMolecularReactionTable::fReactantsMV protected
Definition at line 281 of file G4DNAMolecularReactionTable.hh.
Referenced by CanReactWith(), PrintTable(), SetReaction(), and ~G4DNAMolecularReactionTable().
fReactionData
ReactionDataMap G4DNAMolecularReactionTable::fReactionData protected
Definition at line 280 of file G4DNAMolecularReactionTable.hh.
Referenced by GetAllReactionData(), GetReactionData(), GetReativesNData(), PrintTable(), SetReaction(), and ~G4DNAMolecularReactionTable().
fReactionDataMV
ReactionDataMV G4DNAMolecularReactionTable::fReactionDataMV protected
Definition at line 282 of file G4DNAMolecularReactionTable.hh.
Referenced by GetReactionData(), SetReaction(), and ~G4DNAMolecularReactionTable().
fVectorOfReactionData
std::vector<const G4DNAMolecularReactionData*> G4DNAMolecularReactionTable::fVectorOfReactionData protected
Definition at line 283 of file G4DNAMolecularReactionTable.hh.
Referenced by GetNReactions(), GetReaction(), GetVectorOfReactionData(), ScaleReactionRateForNewTemperature(), and SetReaction().
fVerbose
G4bool G4DNAMolecularReactionTable::fVerbose protected
Definition at line 269 of file G4DNAMolecularReactionTable.hh.
Referenced by CanReactWith(), G4DNAMolecularReactionTable(), and GetReativesNData().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/dna/utils/include/G4DNAMolecularReactionTable.hh
source/processes/electromagnetic/dna/utils/src/G4DNAMolecularReactionTable.cc