Geant4: G4ModelingParameters Class Reference
G4ModelingParameters Class Reference
#include <G4ModelingParameters.hh>
Data Structures
class PVNameCopyNo
class PVPointerCopyNo
class VisAttributesModifier
Public Types
enum DrawingStyle { wf, hlr, hsr, hlhsr }
enum VisAttributesSignifier {
VASVisibility, VASDaughtersInvisible, VASColour, VASLineStyle,
VASLineWidth, VASForceWireframe, VASForceSolid, VASForceAuxEdgeVisible,
VASForceLineSegmentsPerCircle
}
typedef std::vector< PVNameCopyNo > PVNameCopyNoPath
typedef PVNameCopyNoPath::const_iterator PVNameCopyNoPathConstIterator
typedef std::vector< PVPointerCopyNo > PVPointerCopyNoPath
typedef PVPointerCopyNoPath::const_iterator PVPointerCopyNoPathConstIterator
Public Member Functions
G4ModelingParameters ()
G4ModelingParameters (const G4VisAttributes *pDefaultVisAttributes, DrawingStyle drawingStyle, G4bool isCulling, G4bool isCullingInvisible, G4bool isDensityCulling, G4double visibleDensity, G4bool isCullingCovered, G4int noOfSides)
~G4ModelingParameters ()
G4bool operator!= (const G4ModelingParameters &) const
G4bool IsWarning () const
const G4VisAttributes * GetDefaultVisAttributes () const
DrawingStyle GetDrawingStyle () const
G4bool IsCulling () const
G4bool IsCullingInvisible () const
G4bool IsDensityCulling () const
G4double GetVisibleDensity () const
G4bool IsCullingCovered () const
G4int GetCBDAlgorithmNumber () const
const std::vector< G4double > & GetCBDParameters () const
G4bool IsExplode () const
G4double GetExplodeFactor () const
const G4Point3D & GetExplodeCentre () const
G4int GetNoOfSides () const
G4VSolid * GetSectionSolid () const
G4VSolid * GetCutawaySolid () const
const G4Event * GetEvent () const
const std::vector< VisAttributesModifier > & GetVisAttributesModifiers () const
void SetWarning (G4bool)
void SetDefaultVisAttributes (const G4VisAttributes *pDefaultVisAttributes)
void SetDrawingStyle (DrawingStyle)
void SetCulling (G4bool)
void SetCullingInvisible (G4bool)
void SetDensityCulling (G4bool)
void SetVisibleDensity (G4double)
void SetCullingCovered (G4bool)
void SetCBDAlgorithmNumber (G4int)
void SetCBDParameters (const std::vector< G4double > &)
void SetExplodeFactor (G4double explodeFactor)
void SetExplodeCentre (const G4Point3D &explodeCentre)
G4int SetNoOfSides (G4int)
void SetSectionSolid (G4VSolid *pSectionSolid)
void SetCutawaySolid (G4VSolid *pCutawaySolid)
void SetEvent (const G4Event *pEvent)
void SetVisAttributesModifiers (const std::vector< VisAttributesModifier > &)
Private Attributes
G4bool fWarning
const G4VisAttributes * fpDefaultVisAttributes
DrawingStyle fDrawingStyle
G4bool fCulling
G4bool fCullInvisible
G4bool fDensityCulling
G4double fVisibleDensity
G4bool fCullCovered
G4int fCBDAlgorithmNumber
std::vector< G4double > fCBDParameters
G4double fExplodeFactor
G4Point3D fExplodeCentre
G4int fNoOfSides
G4VSolid * fpSectionSolid
G4VSolid * fpCutawaySolid
const G4Event * fpEvent
std::vector< VisAttributesModifier > fVisAttributesModifiers
Friends
std::ostream & operator<< (std::ostream &os, const G4ModelingParameters &)
std::ostream & operator<< (std::ostream &os, const PVNameCopyNoPath &)
std::ostream & operator<< (std::ostream &os, const PVPointerCopyNoPath &)
std::ostream & operator<< (std::ostream &os, const std::vector< VisAttributesModifier > &)
Detailed Description
Definition at line 51 of file G4ModelingParameters.hh.
Member Typedef Documentation
PVNameCopyNoPath
typedef std::vector<PVNameCopyNo> G4ModelingParameters::PVNameCopyNoPath
Definition at line 90 of file G4ModelingParameters.hh.
PVNameCopyNoPathConstIterator
typedef PVNameCopyNoPath::const_iterator G4ModelingParameters::PVNameCopyNoPathConstIterator
Definition at line 91 of file G4ModelingParameters.hh.
PVPointerCopyNoPath
typedef std::vector<PVPointerCopyNo> G4ModelingParameters::PVPointerCopyNoPath
Definition at line 107 of file G4ModelingParameters.hh.
PVPointerCopyNoPathConstIterator
typedef PVPointerCopyNoPath::const_iterator G4ModelingParameters::PVPointerCopyNoPathConstIterator
Definition at line 108 of file G4ModelingParameters.hh.
Member Enumeration Documentation
DrawingStyle
enum G4ModelingParameters::DrawingStyle
Enumerator
wf
hlr
hsr
hlhsr
Definition at line 56 of file G4ModelingParameters.hh.
VisAttributesSignifier
enum G4ModelingParameters::VisAttributesSignifier
Enumerator
VASVisibility
VASDaughtersInvisible
VASColour
VASLineStyle
VASLineWidth
VASForceWireframe
VASForceSolid
VASForceAuxEdgeVisible
VASForceLineSegmentsPerCircle
Definition at line 65 of file G4ModelingParameters.hh.
Constructor & Destructor Documentation
G4ModelingParameters() [1/2]
G4ModelingParameters::G4ModelingParameters ()
Definition at line 43 of file G4ModelingParameters.cc.
G4ModelingParameters() [2/2]
G4ModelingParameters::G4ModelingParameters (const G4VisAttributes * pDefaultVisAttributes, G4ModelingParameters::DrawingStyle drawingStyle, G4bool isCulling, G4bool isCullingInvisible, G4bool isDensityCulling, G4double visibleDensity, G4bool isCullingCovered, G4int noOfSides)
Definition at line 61 of file G4ModelingParameters.cc.
~G4ModelingParameters()
G4ModelingParameters::~G4ModelingParameters ()
Definition at line 86 of file G4ModelingParameters.cc.
Member Function Documentation
GetCBDAlgorithmNumber()
G4int G4ModelingParameters::GetCBDAlgorithmNumber () const
GetCBDParameters()
const std::vector<G4double>& G4ModelingParameters::GetCBDParameters () const
GetCutawaySolid()
G4VSolid* G4ModelingParameters::GetCutawaySolid () const
GetDefaultVisAttributes()
const G4VisAttributes* G4ModelingParameters::GetDefaultVisAttributes () const
Referenced by G4PhysicalVolumeModel::Validate().
GetDrawingStyle()
DrawingStyle G4ModelingParameters::GetDrawingStyle () const
GetEvent()
const G4Event* G4ModelingParameters::GetEvent () const
Referenced by G4DigiModel::DescribeYourselfTo(), G4HitsModel::DescribeYourselfTo(), G4TrajectoriesModel::DescribeYourselfTo(), and G4VisCommandSceneAddEventID::EventID::operator()().
GetExplodeCentre()
const G4Point3D& G4ModelingParameters::GetExplodeCentre () const
GetExplodeFactor()
G4double G4ModelingParameters::GetExplodeFactor () const
GetNoOfSides()
G4int G4ModelingParameters::GetNoOfSides () const
GetSectionSolid()
G4VSolid* G4ModelingParameters::GetSectionSolid () const
GetVisAttributesModifiers()
const std::vector<VisAttributesModifier>& G4ModelingParameters::GetVisAttributesModifiers () const
GetVisibleDensity()
G4double G4ModelingParameters::GetVisibleDensity () const
IsCulling()
G4bool G4ModelingParameters::IsCulling () const
IsCullingCovered()
G4bool G4ModelingParameters::IsCullingCovered () const
IsCullingInvisible()
G4bool G4ModelingParameters::IsCullingInvisible () const
IsDensityCulling()
G4bool G4ModelingParameters::IsDensityCulling () const
IsExplode()
G4bool G4ModelingParameters::IsExplode () const
IsWarning()
G4bool G4ModelingParameters::IsWarning () const
operator!=()
G4bool G4ModelingParameters::operator!= (const G4ModelingParameters & mp) const
Definition at line 237 of file G4ModelingParameters.cc.
SetCBDAlgorithmNumber()
void G4ModelingParameters::SetCBDAlgorithmNumber (G4int)
Referenced by G4VSceneHandler::CreateModelingParameters().
SetCBDParameters()
void G4ModelingParameters::SetCBDParameters (const std::vector< G4double > &)
Referenced by G4VSceneHandler::CreateModelingParameters().
SetCulling()
void G4ModelingParameters::SetCulling (G4bool)
Referenced by G4LogicalVolumeModel::DescribeYourselfTo().
SetCullingCovered()
void G4ModelingParameters::SetCullingCovered (G4bool)
SetCullingInvisible()
void G4ModelingParameters::SetCullingInvisible (G4bool)
SetCutawaySolid()
void G4ModelingParameters::SetCutawaySolid (G4VSolid * pCutawaySolid)
Definition at line 149 of file G4ModelingParameters.cc.
Referenced by G4VSceneHandler::CreateModelingParameters().
SetDefaultVisAttributes()
void G4ModelingParameters::SetDefaultVisAttributes (const G4VisAttributes * pDefaultVisAttributes)
Referenced by G4PhysicalVolumeModel::Validate().
SetDensityCulling()
void G4ModelingParameters::SetDensityCulling (G4bool)
SetDrawingStyle()
void G4ModelingParameters::SetDrawingStyle (DrawingStyle)
SetEvent()
void G4ModelingParameters::SetEvent (const G4Event * pEvent)
Referenced by G4VSceneHandler::DrawEndOfRunModels(), and G4VSceneHandler::DrawEvent().
SetExplodeCentre()
void G4ModelingParameters::SetExplodeCentre (const G4Point3D & explodeCentre)
Referenced by G4VSceneHandler::CreateModelingParameters().
SetExplodeFactor()
void G4ModelingParameters::SetExplodeFactor (G4double explodeFactor)
Referenced by G4VSceneHandler::CreateModelingParameters().
SetNoOfSides()
G4int G4ModelingParameters::SetNoOfSides (G4int nSides)
Definition at line 129 of file G4ModelingParameters.cc.
SetSectionSolid()
void G4ModelingParameters::SetSectionSolid (G4VSolid * pSectionSolid)
Definition at line 143 of file G4ModelingParameters.cc.
Referenced by G4VSceneHandler::CreateModelingParameters().
SetVisAttributesModifiers()
void G4ModelingParameters::SetVisAttributesModifiers (const std::vector< VisAttributesModifier > &)
Referenced by G4VSceneHandler::CreateModelingParameters().
SetVisibleDensity()
void G4ModelingParameters::SetVisibleDensity (G4double visibleDensity)
Definition at line 112 of file G4ModelingParameters.cc.
SetWarning()
void G4ModelingParameters::SetWarning (G4bool)
Referenced by G4VSceneHandler::CreateModelingParameters().
Friends And Related Function Documentation
operator<< [1/4]
std::ostream& operator<< (std::ostream & os, const G4ModelingParameters & mp) friend
Definition at line 154 of file G4ModelingParameters.cc.
operator<< [2/4]
std::ostream& operator<< (std::ostream & os, const PVNameCopyNoPath & path) friend
Definition at line 332 of file G4ModelingParameters.cc.
operator<< [3/4]
std::ostream& operator<< (std::ostream & os, const PVPointerCopyNoPath & path) friend
Definition at line 359 of file G4ModelingParameters.cc.
operator<< [4/4]
std::ostream& operator<< (std::ostream & os, const std::vector< VisAttributesModifier > & vams) friend
Definition at line 373 of file G4ModelingParameters.cc.
Field Documentation
fCBDAlgorithmNumber
G4int G4ModelingParameters::fCBDAlgorithmNumber private
Definition at line 219 of file G4ModelingParameters.hh.
Referenced by operator<<().
fCBDParameters
std::vector<G4double> G4ModelingParameters::fCBDParameters private
Definition at line 220 of file G4ModelingParameters.hh.
Referenced by operator<<().
fCullCovered
G4bool G4ModelingParameters::fCullCovered private
Definition at line 218 of file G4ModelingParameters.hh.
Referenced by operator<<().
fCulling
G4bool G4ModelingParameters::fCulling private
Definition at line 214 of file G4ModelingParameters.hh.
Referenced by operator<<().
fCullInvisible
G4bool G4ModelingParameters::fCullInvisible private
Definition at line 215 of file G4ModelingParameters.hh.
Referenced by operator<<().
fDensityCulling
G4bool G4ModelingParameters::fDensityCulling private
Definition at line 216 of file G4ModelingParameters.hh.
Referenced by operator<<().
fDrawingStyle
DrawingStyle G4ModelingParameters::fDrawingStyle private
Definition at line 213 of file G4ModelingParameters.hh.
Referenced by operator<<().
fExplodeCentre
G4Point3D G4ModelingParameters::fExplodeCentre private
Definition at line 222 of file G4ModelingParameters.hh.
Referenced by operator<<().
fExplodeFactor
G4double G4ModelingParameters::fExplodeFactor private
Definition at line 221 of file G4ModelingParameters.hh.
Referenced by operator<<().
fNoOfSides
G4int G4ModelingParameters::fNoOfSides private
Definition at line 223 of file G4ModelingParameters.hh.
Referenced by operator<<(), and SetNoOfSides().
fpCutawaySolid
G4VSolid* G4ModelingParameters::fpCutawaySolid private
Definition at line 225 of file G4ModelingParameters.hh.
Referenced by operator<<(), and ~G4ModelingParameters().
fpDefaultVisAttributes
const G4VisAttributes* G4ModelingParameters::fpDefaultVisAttributes private
Definition at line 212 of file G4ModelingParameters.hh.
Referenced by operator<<(), and SetNoOfSides().
fpEvent
const G4Event* G4ModelingParameters::fpEvent private
Definition at line 226 of file G4ModelingParameters.hh.
Referenced by operator<<().
fpSectionSolid
G4VSolid* G4ModelingParameters::fpSectionSolid private
Definition at line 224 of file G4ModelingParameters.hh.
Referenced by operator<<(), and ~G4ModelingParameters().
fVisAttributesModifiers
std::vector<VisAttributesModifier> G4ModelingParameters::fVisAttributesModifiers private
Definition at line 227 of file G4ModelingParameters.hh.
Referenced by operator<<().
fVisibleDensity
G4double G4ModelingParameters::fVisibleDensity private
Definition at line 217 of file G4ModelingParameters.hh.
Referenced by operator<<(), and SetVisibleDensity().
fWarning
G4bool G4ModelingParameters::fWarning private
Definition at line 211 of file G4ModelingParameters.hh.
Referenced by operator<<(), SetNoOfSides(), and SetVisibleDensity().
The documentation for this class was generated from the following files:
source/visualization/modeling/include/G4ModelingParameters.hh
source/visualization/modeling/src/G4ModelingParameters.cc