Geant4: G4DNAChemistryManager Class Reference
G4DNAChemistryManager Class Reference
WARNING: THIS CLASS IS A PROTOTYPE G4DNAChemistryManager is called from the physics models.
#include <G4DNAChemistryManager.hh>
Data Structures
struct ThreadLocalData
Public Member Functions
G4bool IsChemistryActivated ()
void SetChemistryActivation (G4bool)
virtual G4bool Notify (G4ApplicationState requestedState)
virtual void SetNewValue (G4UIcommand *, G4String)
virtual G4String GetCurrentValue (G4UIcommand *command)
void Initialize ()
void SetChemistryList (G4VUserChemistryList *)
void Deregister (G4VUserChemistryList *)
void SetGlobalTemperature (G4double temp_K)
void ForceMasterReinitialization ()
void TagThreadForReinitialization ()
void Run ()
void Clear ()
void Gun (G4ITGun *, bool physicsTableToBuild=true)
void ForceThreadReinitialization ()
void ForceRebuildingPhysicsTable ()
void WriteInto (const G4String &, std::ios_base::openmode mode=std::ios_base::out)
Tells the chemMan to write into a file the position and electronic state of the water molecule and the position thermalized or not of the solvated electron.
void AddEmptyLineInOuputFile ()
void CloseFile ()
Close the file specified with WriteInto.
void CreateWaterMolecule (ElectronicModification, G4int, const G4Track *)
Method used by DNA physics model to create a water molecule.
void CreateSolvatedElectron (const G4Track *, G4ThreeVector *finalPosition=0)
On the same idea as the previous method but for solvated electron.
void PushMolecule (G4Molecule *&molecule, G4double time, const G4ThreeVector &position, G4int parentID)
WARNING : In case chemistry is not activated, PushMolecule will take care of deleting the transfered molecule.
void PushMoleculeAtParentTimeAndPlace (G4Molecule *&molecule, const G4Track *)
WARNING : In case chemistry is not activated, PushMoleculeAtParentTimeAndPlace will take care of deleting the transfered molecule.
void SetVerbose (G4int verbose)
void SetBuildPhysicsTable (G4bool flag)
G4bool IsCounterResetWhenRunEnds () const
void ResetCounterWhenRunEnds (G4bool resetCounterWhenRunEnds)
void SetPhysChemIO (G4VPhysChemIO *physChemIO)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Public Member Functions inherited from G4VStateDependent
G4VStateDependent (G4bool bottom=false)
virtual ~G4VStateDependent ()
G4bool operator== (const G4VStateDependent &right) const
G4bool operator!= (const G4VStateDependent &right) const
Static Public Member Functions
static G4DNAChemistryManager * Instance ()
static G4DNAChemistryManager * GetInstanceIfExists ()
static void DeleteInstance ()
You should rather use DeleteInstance than the destructor of this class.
static G4bool IsActivated ()
static void Activated (G4bool flag=true)
Protected Member Functions
virtual ~G4DNAChemistryManager ()
G4DNAWaterExcitationStructure * GetExcitationLevel ()
G4DNAWaterIonisationStructure * GetIonisationLevel ()
void InitializeFile ()
void InitializeMaster ()
void InitializeThread ()
G4DNAChemistryManager ()
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Private Attributes
G4UIdirectory * fpChemDNADirectory
G4UIcmdWithABool * fpActivateChem
G4UIcmdWithoutParameter * fpRunChem
G4UIcmdWithoutParameter * fpSkipReactionsFromChemList
G4UIcmdWithADoubleAndUnit * fpScaleForNewTemperature
G4UIcmdWithoutParameter * fpInitChem
G4bool fActiveChemistry
G4bool fMasterInitialized
G4bool fForceThreadReinitialization
G4DNAWaterExcitationStructure * fpExcitationLevel
G4DNAWaterIonisationStructure * fpIonisationLevel
G4VUserChemistryList * fpUserChemistryList
G4bool fBuildPhysicsTable
G4bool fPhysicsTableBuilt
G4bool fSkipReactions
G4bool fGeometryClosed
G4int fVerbose
G4bool fResetCounterWhenRunEnds
Static Private Attributes
static G4DNAChemistryManager * fgInstance
static G4ThreadLocal ThreadLocalData * fpThreadData = 0
Additional Inherited Members
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
WARNING: THIS CLASS IS A PROTOTYPE G4DNAChemistryManager is called from the physics models.
It creates the water molecules and the solvated electrons and and send them to G4ITStepManager to be treated in the chemistry stage. For this, the fActiveChemistry flag needs to be on. It is also possible to give already molecule's pointers already built. G4DNAChemistryManager will then be in charge of creating the track and loading it to the IT system. The user can also ask to create a file containing a information about the creation of water molecules and solvated electrons.
Definition at line 88 of file G4DNAChemistryManager.hh.
Constructor & Destructor Documentation
~G4DNAChemistryManager()
G4DNAChemistryManager::~G4DNAChemistryManager () protected virtual
Definition at line 164 of file G4DNAChemistryManager.cc.
G4DNAChemistryManager()
G4DNAChemistryManager::G4DNAChemistryManager () protected
Definition at line 98 of file G4DNAChemistryManager.cc.
Referenced by Instance().
Member Function Documentation
Activated()
void G4DNAChemistryManager::Activated (G4bool flag = true) static
Definition at line 546 of file G4DNAChemistryManager.cc.
Referenced by SetChemistryList(), and SetNewValue().
AddEmptyLineInOuputFile()
void G4DNAChemistryManager::AddEmptyLineInOuputFile ()
Definition at line 587 of file G4DNAChemistryManager.cc.
Clear()
void G4DNAChemistryManager::Clear ()
Definition at line 178 of file G4DNAChemistryManager.cc.
Referenced by Notify(), and ~G4DNAChemistryManager().
CloseFile()
void G4DNAChemistryManager::CloseFile ()
Close the file specified with WriteInto.
Definition at line 596 of file G4DNAChemistryManager.cc.
Referenced by Run().
CreateSolvatedElectron()
void G4DNAChemistryManager::CreateSolvatedElectron (const G4Track * theIncomingTrack, G4ThreeVector * finalPosition = 0)
On the same idea as the previous method but for solvated electron.
This method should be used by the physics model of the ElectronSolvatation process.
Definition at line 686 of file G4DNAChemistryManager.cc.
Referenced by G4DNATransformElectronModel::SampleSecondaries().
CreateWaterMolecule()
void G4DNAChemistryManager::CreateWaterMolecule (ElectronicModification modification, G4int electronicLevel, const G4Track * theIncomingTrack)
Method used by DNA physics model to create a water molecule.
The ElectronicModification is a flag telling whether the molecule is ionized or excited, the electronic level is calculated by the model and the IncomingTrack is the track responsible for the creation of this molecule (electron, proton...).
Definition at line 630 of file G4DNAChemistryManager.cc.
Referenced by G4DNADingfelderChargeDecreaseModel::SampleSecondaries(), G4DNARuddIonisationExtendedModel::SampleSecondaries(), G4DNARuddIonisationModel::SampleSecondaries(), G4DNABornExcitationModel1::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4DNABornIonisationModel1::SampleSecondaries(), G4DNABornExcitationModel2::SampleSecondaries(), G4DNAMillerGreenExcitationModel::SampleSecondaries(), G4DNAEmfietzoglouExcitationModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4DNACPA100ExcitationModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), and G4DNAPTBExcitationModel::SampleSecondaries().
DeleteInstance()
void G4DNAChemistryManager::DeleteInstance () static
You should rather use DeleteInstance than the destructor of this class.
Definition at line 240 of file G4DNAChemistryManager.cc.
Deregister()
void G4DNAChemistryManager::Deregister (G4VUserChemistryList * chemistryList) inline
Definition at line 279 of file G4DNAChemistryManager.hh.
Referenced by G4VUserChemistryList::~G4VUserChemistryList().
ForceMasterReinitialization()
void G4DNAChemistryManager::ForceMasterReinitialization () inline
Definition at line 284 of file G4DNAChemistryManager.hh.
ForceRebuildingPhysicsTable()
void G4DNAChemistryManager::ForceRebuildingPhysicsTable () inline
Definition at line 268 of file G4DNAChemistryManager.hh.
ForceThreadReinitialization()
void G4DNAChemistryManager::ForceThreadReinitialization () inline
Definition at line 290 of file G4DNAChemistryManager.hh.
GetCurrentValue()
G4String G4DNAChemistryManager::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 329 of file G4DNAChemistryManager.cc.
GetExcitationLevel()
G4DNAWaterExcitationStructure * G4DNAChemistryManager::GetExcitationLevel () protected
Definition at line 606 of file G4DNAChemistryManager.cc.
Referenced by CreateWaterMolecule().
GetInstanceIfExists()
G4DNAChemistryManager * G4DNAChemistryManager::GetInstanceIfExists () static
Definition at line 157 of file G4DNAChemistryManager.cc.
Referenced by G4VUserChemistryList::~G4VUserChemistryList().
GetIonisationLevel()
G4DNAWaterIonisationStructure * G4DNAChemistryManager::GetIonisationLevel () protected
Definition at line 618 of file G4DNAChemistryManager.cc.
Referenced by CreateWaterMolecule().
Gun()
void G4DNAChemistryManager::Gun (G4ITGun * gun, bool physicsTableToBuild = true)
Definition at line 375 of file G4DNAChemistryManager.cc.
Initialize()
void G4DNAChemistryManager::Initialize ()
Definition at line 383 of file G4DNAChemistryManager.cc.
Referenced by G4EmDNAChemistry::ConstructProcess(), G4EmDNAChemistry_option1::ConstructProcess(), and SetNewValue().
InitializeFile()
void G4DNAChemistryManager::InitializeFile () protected
Definition at line 524 of file G4DNAChemistryManager.cc.
Referenced by InitializeThread().
InitializeMaster()
void G4DNAChemistryManager::InitializeMaster () protected
Definition at line 421 of file G4DNAChemistryManager.cc.
Referenced by ForceMasterReinitialization(), and Initialize().
InitializeThread()
void G4DNAChemistryManager::InitializeThread () protected
Definition at line 462 of file G4DNAChemistryManager.cc.
Referenced by Initialize(), Run(), and SetNewValue().
Instance()
G4DNAChemistryManager * G4DNAChemistryManager::Instance (void) static
Definition at line 136 of file G4DNAChemistryManager.cc.
Referenced by Activated(), G4EmDNAChemistry::ConstructProcess(), G4EmDNAChemistry_option1::ConstructProcess(), G4EmDNAChemistry::G4EmDNAChemistry(), G4EmDNAChemistry_option1::G4EmDNAChemistry_option1(), IsActivated(), StackingAction::NewStage(), G4DNADingfelderChargeDecreaseModel::SampleSecondaries(), G4DNAMeltonAttachmentModel::SampleSecondaries(), G4DNARuddIonisationExtendedModel::SampleSecondaries(), G4DNARuddIonisationModel::SampleSecondaries(), G4DNABornExcitationModel1::SampleSecondaries(), G4DNABornIonisationModel1::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4DNAMillerGreenExcitationModel::SampleSecondaries(), G4DNABornExcitationModel2::SampleSecondaries(), G4DNAEmfietzoglouExcitationModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4DNACPA100ExcitationModel::SampleSecondaries(), G4DNATransformElectronModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), and G4DNAPTBExcitationModel::SampleSecondaries().
IsActivated()
G4bool G4DNAChemistryManager::IsActivated () static
Definition at line 539 of file G4DNAChemistryManager.cc.
Referenced by G4EmDNAPhysicsActivator::ConstructProcess().
IsChemistryActivated()
G4bool G4DNAChemistryManager::IsChemistryActivated ()
Definition at line 553 of file G4DNAChemistryManager.cc.
IsCounterResetWhenRunEnds()
G4bool G4DNAChemistryManager::IsCounterResetWhenRunEnds () const inline
Definition at line 207 of file G4DNAChemistryManager.hh.
Notify()
G4bool G4DNAChemistryManager::Notify (G4ApplicationState requestedState) virtual
Implements G4VStateDependent.
Definition at line 262 of file G4DNAChemistryManager.cc.
PushMolecule()
void G4DNAChemistryManager::PushMolecule (G4Molecule *& molecule, G4double time, const G4ThreeVector & position, G4int parentID)
WARNING : In case chemistry is not activated, PushMolecule will take care of deleting the transfered molecule.
Before calling this method, it is also possible to check if the chemistry is activated through IsChemistryActived(). This method will create the track corresponding to the transfered molecule and will be in charge of loading the new track to the system.
Definition at line 715 of file G4DNAChemistryManager.cc.
PushMoleculeAtParentTimeAndPlace()
void G4DNAChemistryManager::PushMoleculeAtParentTimeAndPlace (G4Molecule *& molecule, const G4Track * theIncomingTrack)
WARNING : In case chemistry is not activated, PushMoleculeAtParentTimeAndPlace will take care of deleting the transfered molecule.
Before calling this method, it is also possible to check if the chemistry is activated through IsChemistryActived(). This method will create the track corresponding to the transfered molecule and will be in charge of loading the new track to the system.
Definition at line 740 of file G4DNAChemistryManager.cc.
ResetCounterWhenRunEnds()
void G4DNAChemistryManager::ResetCounterWhenRunEnds (G4bool resetCounterWhenRunEnds) inline
Definition at line 212 of file G4DNAChemistryManager.hh.
Run()
void G4DNAChemistryManager::Run ()
Definition at line 341 of file G4DNAChemistryManager.cc.
Referenced by StackingAction::NewStage(), and SetNewValue().
SetBuildPhysicsTable()
void G4DNAChemistryManager::SetBuildPhysicsTable (G4bool flag) inline
Definition at line 204 of file G4DNAChemistryManager.hh.
SetChemistryActivation()
void G4DNAChemistryManager::SetChemistryActivation (G4bool flag)
Definition at line 560 of file G4DNAChemistryManager.cc.
SetChemistryList()
void G4DNAChemistryManager::SetChemistryList (G4VUserChemistryList * chemistryList) inline
Definition at line 273 of file G4DNAChemistryManager.hh.
Referenced by G4EmDNAChemistry::G4EmDNAChemistry(), and G4EmDNAChemistry_option1::G4EmDNAChemistry_option1().
SetGlobalTemperature()
void G4DNAChemistryManager::SetGlobalTemperature (G4double temp_K)
Definition at line 762 of file G4DNAChemistryManager.cc.
Referenced by SetNewValue().
SetNewValue()
void G4DNAChemistryManager::SetNewValue (G4UIcommand * command, G4String value) virtual
Reimplemented from G4UImessenger.
Definition at line 296 of file G4DNAChemistryManager.cc.
SetPhysChemIO()
void G4DNAChemistryManager::SetPhysChemIO (G4VPhysChemIO * physChemIO)
Definition at line 89 of file G4DNAChemistryManager.cc.
SetVerbose()
void G4DNAChemistryManager::SetVerbose (G4int verbose) inline
Definition at line 199 of file G4DNAChemistryManager.hh.
TagThreadForReinitialization()
void G4DNAChemistryManager::TagThreadForReinitialization () inline
Definition at line 295 of file G4DNAChemistryManager.hh.
WriteInto()
void G4DNAChemistryManager::WriteInto (const G4String & , std::ios_base::openmode mode = std::ios_base::out)
Tells the chemMan to write into a file the position and electronic state of the water molecule and the position thermalized or not of the solvated electron.
Definition at line 567 of file G4DNAChemistryManager.cc.
Field Documentation
fActiveChemistry
G4bool G4DNAChemistryManager::fActiveChemistry private
Definition at line 238 of file G4DNAChemistryManager.hh.
Referenced by Activated(), CreateSolvatedElectron(), CreateWaterMolecule(), G4DNAChemistryManager(), GetCurrentValue(), InitializeMaster(), IsActivated(), IsChemistryActivated(), PushMolecule(), PushMoleculeAtParentTimeAndPlace(), Run(), and SetChemistryActivation().
fBuildPhysicsTable
G4bool G4DNAChemistryManager::fBuildPhysicsTable private
Definition at line 256 of file G4DNAChemistryManager.hh.
Referenced by G4DNAChemistryManager(), Gun(), InitializeThread(), and SetBuildPhysicsTable().
fForceThreadReinitialization
G4bool G4DNAChemistryManager::fForceThreadReinitialization private
Definition at line 250 of file G4DNAChemistryManager.hh.
Referenced by ForceThreadReinitialization(), G4DNAChemistryManager(), and InitializeThread().
fGeometryClosed
G4bool G4DNAChemistryManager::fGeometryClosed private
Definition at line 260 of file G4DNAChemistryManager.hh.
Referenced by G4DNAChemistryManager(), InitializeThread(), and Notify().
fgInstance
G4DNAChemistryManager * G4DNAChemistryManager::fgInstance static private
Definition at line 237 of file G4DNAChemistryManager.hh.
Referenced by DeleteInstance(), GetInstanceIfExists(), Instance(), and ~G4DNAChemistryManager().
fMasterInitialized
G4bool G4DNAChemistryManager::fMasterInitialized private
Definition at line 249 of file G4DNAChemistryManager.hh.
Referenced by ForceMasterReinitialization(), G4DNAChemistryManager(), InitializeMaster(), and Run().
fpActivateChem
G4UIcmdWithABool* G4DNAChemistryManager::fpActivateChem private
Definition at line 230 of file G4DNAChemistryManager.hh.
Referenced by Clear(), G4DNAChemistryManager(), GetCurrentValue(), and SetNewValue().
fpChemDNADirectory
G4UIdirectory* G4DNAChemistryManager::fpChemDNADirectory private
Definition at line 229 of file G4DNAChemistryManager.hh.
Referenced by Clear(), and G4DNAChemistryManager().
fpExcitationLevel
G4DNAWaterExcitationStructure* G4DNAChemistryManager::fpExcitationLevel private
Definition at line 252 of file G4DNAChemistryManager.hh.
Referenced by Clear(), G4DNAChemistryManager(), and GetExcitationLevel().
fPhysicsTableBuilt
G4bool G4DNAChemistryManager::fPhysicsTableBuilt private
Definition at line 257 of file G4DNAChemistryManager.hh.
Referenced by ForceRebuildingPhysicsTable(), G4DNAChemistryManager(), and InitializeThread().
fpInitChem
G4UIcmdWithoutParameter* G4DNAChemistryManager::fpInitChem private
Definition at line 235 of file G4DNAChemistryManager.hh.
Referenced by Clear(), G4DNAChemistryManager(), and SetNewValue().
fpIonisationLevel
G4DNAWaterIonisationStructure* G4DNAChemistryManager::fpIonisationLevel private
Definition at line 253 of file G4DNAChemistryManager.hh.
Referenced by Clear(), G4DNAChemistryManager(), and GetIonisationLevel().
fpRunChem
G4UIcmdWithoutParameter* G4DNAChemistryManager::fpRunChem private
Definition at line 231 of file G4DNAChemistryManager.hh.
Referenced by Clear(), G4DNAChemistryManager(), and SetNewValue().
fpScaleForNewTemperature
G4UIcmdWithADoubleAndUnit* G4DNAChemistryManager::fpScaleForNewTemperature private
Definition at line 234 of file G4DNAChemistryManager.hh.
Referenced by G4DNAChemistryManager(), and SetNewValue().
fpSkipReactionsFromChemList
G4UIcmdWithoutParameter* G4DNAChemistryManager::fpSkipReactionsFromChemList private
Definition at line 232 of file G4DNAChemistryManager.hh.
Referenced by Clear(), G4DNAChemistryManager(), and SetNewValue().
fpThreadData
G4ThreadLocal G4DNAChemistryManager::ThreadLocalData * G4DNAChemistryManager::fpThreadData = 0 static private
Definition at line 247 of file G4DNAChemistryManager.hh.
Referenced by AddEmptyLineInOuputFile(), CloseFile(), CreateSolvatedElectron(), CreateWaterMolecule(), InitializeFile(), InitializeThread(), Instance(), Run(), TagThreadForReinitialization(), and WriteInto().
fpUserChemistryList
G4VUserChemistryList* G4DNAChemistryManager::fpUserChemistryList private
Definition at line 255 of file G4DNAChemistryManager.hh.
Referenced by Clear(), Deregister(), G4DNAChemistryManager(), InitializeMaster(), InitializeThread(), and SetChemistryList().
fResetCounterWhenRunEnds
G4bool G4DNAChemistryManager::fResetCounterWhenRunEnds private
Definition at line 263 of file G4DNAChemistryManager.hh.
Referenced by G4DNAChemistryManager(), IsCounterResetWhenRunEnds(), ResetCounterWhenRunEnds(), and Run().
fSkipReactions
G4bool G4DNAChemistryManager::fSkipReactions private
Definition at line 258 of file G4DNAChemistryManager.hh.
Referenced by G4DNAChemistryManager(), InitializeMaster(), and SetNewValue().
fVerbose
G4int G4DNAChemistryManager::fVerbose private
Definition at line 262 of file G4DNAChemistryManager.hh.
Referenced by G4DNAChemistryManager(), InitializeFile(), InitializeMaster(), InitializeThread(), Notify(), SetVerbose(), and WriteInto().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/dna/utils/include/G4DNAChemistryManager.hh
source/processes/electromagnetic/dna/utils/src/G4DNAChemistryManager.cc