Geant4: G4MicroElecSiStructure Class Reference
G4MicroElecSiStructure Class Reference
#include <G4MicroElecSiStructure.hh>
Public Member Functions
G4MicroElecSiStructure ()
virtual ~G4MicroElecSiStructure ()
G4double Energy (G4int level)
G4int NumberOfLevels ()
Private Attributes
G4int nLevels
std::vector< G4double > energyConstant
Detailed Description
Definition at line 51 of file G4MicroElecSiStructure.hh.
Constructor & Destructor Documentation
G4MicroElecSiStructure()
G4MicroElecSiStructure::G4MicroElecSiStructure ()
Definition at line 46 of file G4MicroElecSiStructure.cc.
~G4MicroElecSiStructure()
G4MicroElecSiStructure::~G4MicroElecSiStructure () virtual
Definition at line 59 of file G4MicroElecSiStructure.cc.
Member Function Documentation
Energy()
G4double G4MicroElecSiStructure::Energy (G4int level)
Definition at line 63 of file G4MicroElecSiStructure.cc.
Referenced by G4MicroElecInelasticModel::DifferentialCrossSection(), G4MicroElecInelasticModel::RandomizeEjectedElectronEnergy(), G4MicroElecInelasticModel::RandomizeEjectedElectronEnergyFromCumulatedDcs(), G4MicroElecInelasticModel::SampleSecondaries(), and G4MicroElecInelasticModel::TransferedEnergy().
NumberOfLevels()
G4int G4MicroElecSiStructure::NumberOfLevels () inline
Definition at line 61 of file G4MicroElecSiStructure.hh.
Field Documentation
energyConstant
std::vector<G4double> G4MicroElecSiStructure::energyConstant private
Definition at line 69 of file G4MicroElecSiStructure.hh.
Referenced by Energy(), and G4MicroElecSiStructure().
nLevels
G4int G4MicroElecSiStructure::nLevels private
Definition at line 67 of file G4MicroElecSiStructure.hh.
Referenced by Energy(), G4MicroElecSiStructure(), and NumberOfLevels().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/lowenergy/include/G4MicroElecSiStructure.hh
source/processes/electromagnetic/lowenergy/src/G4MicroElecSiStructure.cc