Geant4: source/g3tog4/src/G3toG4BuildTree.cc File Reference
G3toG4BuildTree.cc File Reference
#include "globals.hh"
#include "G3toG4BuildTree.hh"
#include "G3RotTable.hh"
#include "G3MedTable.hh"
#include "G3VolTable.hh"
#include "G3SensVolVector.hh"
#include "G3Pos.hh"
#include "G4LogicalVolume.hh"
#include "G4PVPlacement.hh"
#include "G4ReflectionFactory.hh"
#include "G4Transform3D.hh"
Functions
void G3toG4BuildTree (G3VolTableEntry *curVTE, G3VolTableEntry *motherVTE)
void G3toG4BuildLVTree (G3VolTableEntry *curVTE, G3VolTableEntry *motherVTE)
void G3toG4BuildPVTree (G3VolTableEntry *curVTE)
Function Documentation
G3toG4BuildLVTree()
void G3toG4BuildLVTree (G3VolTableEntry * curVTE, G3VolTableEntry * motherVTE)
Definition at line 48 of file G3toG4BuildTree.cc.
Referenced by G3toG4BuildTree().
G3toG4BuildPVTree()
void G3toG4BuildPVTree (G3VolTableEntry * curVTE)
Definition at line 100 of file G3toG4BuildTree.cc.
Referenced by G3toG4BuildTree().
G3toG4BuildTree()
void G3toG4BuildTree (G3VolTableEntry * curVTE, G3VolTableEntry * motherVTE)
Definition at line 42 of file G3toG4BuildTree.cc.
Referenced by G4BuildGeom().