Geant4: G4IonsShenCrossSection Class Reference
G4IonsShenCrossSection Class Reference
#include <G4IonsShenCrossSection.hh>
Public Member Functions
G4IonsShenCrossSection ()
virtual ~G4IonsShenCrossSection ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *aDP, G4int Z, const G4Material *)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *)
virtual G4double GetIsoCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *iso=0, const G4Element *elm=0, const G4Material *mat=0)
virtual void CrossSectionDescription (std::ostream &) const
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsIsoApplicable (const G4DynamicParticle *, G4int Z, G4int A, const G4Element *elm=0, const G4Material *mat=0)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Private Member Functions
G4double calEcmValue (const G4double, const G4double, const G4double)
G4double calCeValue (const G4double)
Private Attributes
const G4double upperLimit
const G4double r0
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 51 of file G4IonsShenCrossSection.hh.
Constructor & Destructor Documentation
G4IonsShenCrossSection()
G4IonsShenCrossSection::G4IonsShenCrossSection ()
Definition at line 42 of file G4IonsShenCrossSection.cc.
~G4IonsShenCrossSection()
G4IonsShenCrossSection::~G4IonsShenCrossSection () virtual
Definition at line 49 of file G4IonsShenCrossSection.cc.
Member Function Documentation
calCeValue()
G4double G4IonsShenCrossSection::calCeValue (const G4double ke) private
Definition at line 144 of file G4IonsShenCrossSection.cc.
Referenced by GetIsoCrossSection().
calEcmValue()
G4double G4IonsShenCrossSection::calEcmValue (const G4double mp, const G4double mt, const G4double Plab) private
Definition at line 133 of file G4IonsShenCrossSection.cc.
Referenced by GetIsoCrossSection().
CrossSectionDescription()
void G4IonsShenCrossSection::CrossSectionDescription (std::ostream & outFile) const virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 53 of file G4IonsShenCrossSection.cc.
GetElementCrossSection()
G4double G4IonsShenCrossSection::GetElementCrossSection (const G4DynamicParticle * aParticle, G4int Z, const G4Material *) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 70 of file G4IonsShenCrossSection.cc.
GetIsoCrossSection()
G4double G4IonsShenCrossSection::GetIsoCrossSection (const G4DynamicParticle * aParticle, G4int Z, G4int A, const G4Isotope * iso = 0, const G4Element * elm = 0, const G4Material * mat = 0) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 78 of file G4IonsShenCrossSection.cc.
Referenced by GetElementCrossSection().
IsElementApplicable()
G4bool G4IonsShenCrossSection::IsElementApplicable (const G4DynamicParticle * aDP, G4int Z, const G4Material *) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 63 of file G4IonsShenCrossSection.cc.
Field Documentation
r0
const G4double G4IonsShenCrossSection::r0 private
Definition at line 78 of file G4IonsShenCrossSection.hh.
Referenced by GetIsoCrossSection().
upperLimit
const G4double G4IonsShenCrossSection::upperLimit private
Definition at line 76 of file G4IonsShenCrossSection.hh.
Referenced by GetIsoCrossSection().
The documentation for this class was generated from the following files:
source/processes/hadronic/cross_sections/include/G4IonsShenCrossSection.hh
source/processes/hadronic/cross_sections/src/G4IonsShenCrossSection.cc