Geant4: G4Para Class Reference
G4Para Class Reference
#include <G4Para.hh>
Public Member Functions
G4Para (const G4String &pName, G4double pDx, G4double pDy, G4double pDz, G4double pAlpha, G4double pTheta, G4double pPhi)
G4Para (const G4String &pName, const G4ThreeVector pt[8])
virtual ~G4Para ()
G4double GetZHalfLength () const
G4ThreeVector GetSymAxis () const
G4double GetYHalfLength () const
G4double GetXHalfLength () const
G4double GetTanAlpha () const
void SetXHalfLength (G4double val)
void SetYHalfLength (G4double val)
void SetZHalfLength (G4double val)
void SetAlpha (G4double alpha)
void SetTanAlpha (G4double val)
void SetThetaAndPhi (double pTheta, double pPhi)
void SetAllParameters (G4double pDx, G4double pDy, G4double pDz, G4double pAlpha, G4double pTheta, G4double pPhi)
G4double GetCubicVolume ()
G4double GetSurfaceArea ()
void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pMin, G4double &pMax) const
EInside Inside (const G4ThreeVector &p) const
G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=G4bool(false), G4bool *validNorm=0, G4ThreeVector *n=0) const
G4double DistanceToOut (const G4ThreeVector &p) const
G4GeometryType GetEntityType () const
G4ThreeVector GetPointOnSurface () const
G4VSolid * Clone () const
std::ostream & StreamInfo (std::ostream &os) const
void DescribeYourselfTo (G4VGraphicsScene &scene) const
G4Polyhedron * CreatePolyhedron () const
G4Para (__void__ &)
G4Para (const G4Para &rhs)
G4Para & operator= (const G4Para &rhs)
Public Member Functions inherited from G4CSGSolid
G4CSGSolid (const G4String &pName)
virtual ~G4CSGSolid ()
virtual G4Polyhedron * GetPolyhedron () const
G4CSGSolid (__void__ &)
G4CSGSolid (const G4CSGSolid &rhs)
G4CSGSolid & operator= (const G4CSGSolid &rhs)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
void DumpInfo () const
virtual G4VisExtent GetExtent () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Private Member Functions
void CheckParameters ()
void MakePlanes ()
G4ThreeVector ApproxSurfaceNormal (const G4ThreeVector &p) const
Private Attributes
G4double halfCarTolerance
G4double fDx
G4double fDy
G4double fDz
G4double fTalpha
G4double fTthetaCphi
G4double fTthetaSphi
struct {
G4double a
G4double b
G4double c
G4double d
} fPlanes [4]
Additional Inherited Members
Protected Member Functions inherited from G4CSGSolid
G4double GetRadiusInRing (G4double rmin, G4double rmax) const
Protected Member Functions inherited from G4VSolid
void CalculateClippedPolygonExtent (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipCrossSection (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipBetweenSections (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipPolygon (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis) const
Protected Attributes inherited from G4CSGSolid
G4double fCubicVolume
G4double fSurfaceArea
G4bool fRebuildPolyhedron
G4Polyhedron * fpPolyhedron
Protected Attributes inherited from G4VSolid
G4double kCarTolerance
Detailed Description
Definition at line 85 of file G4Para.hh.
Constructor & Destructor Documentation
G4Para() [1/4]
G4Para::G4Para (const G4String & pName, G4double pDx, G4double pDy, G4double pDz, G4double pAlpha, G4double pTheta, G4double pPhi)
Definition at line 67 of file G4Para.cc.
Referenced by Clone().
G4Para() [2/4]
G4Para::G4Para (const G4String & pName, const G4ThreeVector pt[8])
Definition at line 80 of file G4Para.cc.
~G4Para()
G4Para::~G4Para () virtual
Definition at line 151 of file G4Para.cc.
G4Para() [3/4]
G4Para::G4Para (__void__ & a)
Definition at line 140 of file G4Para.cc.
G4Para() [4/4]
G4Para::G4Para (const G4Para & rhs)
Definition at line 159 of file G4Para.cc.
Member Function Documentation
ApproxSurfaceNormal()
G4ThreeVector G4Para::ApproxSurfaceNormal (const G4ThreeVector & p) const private
Definition at line 529 of file G4Para.cc.
Referenced by SurfaceNormal().
BoundingLimits()
void G4Para::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 330 of file G4Para.cc.
Referenced by CalculateExtent().
CalculateExtent()
G4bool G4Para::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pMin, G4double & pMax) const virtual
Implements G4VSolid.
Definition at line 373 of file G4Para.cc.
CheckParameters()
void G4Para::CheckParameters () private
Definition at line 223 of file G4Para.cc.
Referenced by G4Para(), and SetAllParameters().
Clone()
G4VSolid * G4Para::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 817 of file G4Para.cc.
ComputeDimensions()
void G4Para::ComputeDimensions (G4VPVParameterisation * p, const G4int n, const G4VPhysicalVolume * pRep) virtual
Reimplemented from G4VSolid.
Definition at line 319 of file G4Para.cc.
CreatePolyhedron()
G4Polyhedron * G4Para::CreatePolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 914 of file G4Para.cc.
DescribeYourselfTo()
void G4Para::DescribeYourselfTo (G4VGraphicsScene & scene) const virtual
Implements G4VSolid.
Definition at line 909 of file G4Para.cc.
DistanceToIn() [1/2]
G4double G4Para::DistanceToIn (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 643 of file G4Para.cc.
DistanceToIn() [2/2]
G4double G4Para::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Implements G4VSolid.
Definition at line 553 of file G4Para.cc.
DistanceToOut() [1/2]
G4double G4Para::DistanceToOut (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 773 of file G4Para.cc.
DistanceToOut() [2/2]
G4double G4Para::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcNorm = G4bool(false), G4bool * validNorm = 0, G4ThreeVector * n = 0) const virtual
Implements G4VSolid.
Definition at line 664 of file G4Para.cc.
GetCubicVolume()
G4double G4Para::GetCubicVolume () virtual
Reimplemented from G4VSolid.
Definition at line 283 of file G4Para.cc.
GetEntityType()
G4GeometryType G4Para::GetEntityType () const virtual
Implements G4VSolid.
Definition at line 808 of file G4Para.cc.
GetPointOnSurface()
G4ThreeVector G4Para::GetPointOnSurface () const virtual
Reimplemented from G4VSolid.
Definition at line 856 of file G4Para.cc.
GetSurfaceArea()
G4double G4Para::GetSurfaceArea () virtual
Reimplemented from G4VSolid.
Definition at line 297 of file G4Para.cc.
GetSymAxis()
G4ThreeVector G4Para::GetSymAxis () const inline
Referenced by G4tgbVolume::BuildSolidForDivision(), G4ParameterisationParaX::ComputeDimensions(), G4ParameterisationParaY::ComputeDimensions(), G4ParameterisationParaZ::ComputeDimensions(), G4ParameterisationParaZ::ComputeTransformation(), export_G4Para(), G4VParameterisationPara::G4VParameterisationPara(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Para_dimensionsWrite(), and G4GDMLWriteSolids::ParaWrite().
GetTanAlpha()
G4double G4Para::GetTanAlpha () const inline
Referenced by BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationParaX::ComputeDimensions(), G4ParameterisationParaY::ComputeDimensions(), G4ParameterisationParaZ::ComputeDimensions(), G4ParameterisationParaY::ComputeTransformation(), export_G4Para(), G4VParameterisationPara::G4VParameterisationPara(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Para_dimensionsWrite(), and G4GDMLWriteSolids::ParaWrite().
GetXHalfLength()
G4double G4Para::GetXHalfLength () const inline
Referenced by BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationParaY::ComputeDimensions(), G4ParameterisationParaZ::ComputeDimensions(), G4ParameterisationParaX::ComputeTransformation(), export_G4Para(), G4ParameterisationParaX::G4ParameterisationParaX(), G4VParameterisationPara::G4VParameterisationPara(), G4ParameterisationParaX::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Para_dimensionsWrite(), and G4GDMLWriteSolids::ParaWrite().
GetYHalfLength()
G4double G4Para::GetYHalfLength () const inline
Referenced by BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationParaX::ComputeDimensions(), G4ParameterisationParaZ::ComputeDimensions(), G4ParameterisationParaY::ComputeTransformation(), export_G4Para(), G4ParameterisationParaY::G4ParameterisationParaY(), G4VParameterisationPara::G4VParameterisationPara(), G4ParameterisationParaY::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Para_dimensionsWrite(), and G4GDMLWriteSolids::ParaWrite().
GetZHalfLength()
G4double G4Para::GetZHalfLength () const inline
Referenced by BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationParaX::ComputeDimensions(), G4ParameterisationParaY::ComputeDimensions(), G4ParameterisationParaZ::ComputeTransformation(), export_G4Para(), G4ParameterisationParaZ::G4ParameterisationParaZ(), G4VParameterisationPara::G4VParameterisationPara(), G4ParameterisationParaZ::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Para_dimensionsWrite(), and G4GDMLWriteSolids::ParaWrite().
Inside()
EInside G4Para::Inside (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 428 of file G4Para.cc.
Referenced by DistanceToOut().
MakePlanes()
void G4Para::MakePlanes () private
Definition at line 244 of file G4Para.cc.
Referenced by G4Para(), and SetAllParameters().
operator=()
G4Para & G4Para::operator= (const G4Para & rhs)
Definition at line 171 of file G4Para.cc.
SetAllParameters()
void G4Para::SetAllParameters (G4double pDx, G4double pDy, G4double pDz, G4double pAlpha, G4double pTheta, G4double pPhi)
Definition at line 199 of file G4Para.cc.
Referenced by G4ParameterisationParaX::ComputeDimensions(), G4ParameterisationParaY::ComputeDimensions(), G4ParameterisationParaZ::ComputeDimensions(), export_G4Para(), and G4Para().
SetAlpha()
void G4Para::SetAlpha (G4double alpha) inline
Referenced by G4GDMLParameterisation::ComputeDimensions(), and export_G4Para().
SetTanAlpha()
void G4Para::SetTanAlpha (G4double val) inline
Referenced by G4GDMLParameterisation::ComputeDimensions(), and export_G4Para().
SetThetaAndPhi()
void G4Para::SetThetaAndPhi (double pTheta, double pPhi) inline
Referenced by G4GDMLParameterisation::ComputeDimensions(), and export_G4Para().
SetXHalfLength()
void G4Para::SetXHalfLength (G4double val) inline
Referenced by G4GDMLParameterisation::ComputeDimensions(), and export_G4Para().
SetYHalfLength()
void G4Para::SetYHalfLength (G4double val) inline
Referenced by G4GDMLParameterisation::ComputeDimensions(), and export_G4Para().
SetZHalfLength()
void G4Para::SetZHalfLength (G4double val) inline
Referenced by G4GDMLParameterisation::ComputeDimensions(), and export_G4Para().
StreamInfo()
std::ostream & G4Para::StreamInfo (std::ostream & os) const virtual
Reimplemented from G4CSGSolid.
Definition at line 826 of file G4Para.cc.
SurfaceNormal()
G4ThreeVector G4Para::SurfaceNormal (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 448 of file G4Para.cc.
Field Documentation
a
G4double G4Para::a
Definition at line 188 of file G4Para.hh.
Referenced by ApproxSurfaceNormal(), and DistanceToOut().
b
G4double G4Para::b
Definition at line 188 of file G4Para.hh.
Referenced by ApproxSurfaceNormal(), and DistanceToOut().
c
G4double G4Para::c
Definition at line 188 of file G4Para.hh.
Referenced by ApproxSurfaceNormal(), and DistanceToOut().
d
G4double G4Para::d
Definition at line 188 of file G4Para.hh.
Referenced by ApproxSurfaceNormal(), and SurfaceNormal().
fDx
G4double G4Para::fDx private
Definition at line 186 of file G4Para.hh.
Referenced by CheckParameters(), CreatePolyhedron(), G4Para(), GetCubicVolume(), GetPointOnSurface(), GetSurfaceArea(), MakePlanes(), operator=(), SetAllParameters(), and StreamInfo().
fDy
G4double G4Para::fDy private
Definition at line 186 of file G4Para.hh.
Referenced by CheckParameters(), CreatePolyhedron(), G4Para(), GetCubicVolume(), GetPointOnSurface(), GetSurfaceArea(), MakePlanes(), operator=(), SetAllParameters(), and StreamInfo().
fDz
G4double G4Para::fDz private
Definition at line 186 of file G4Para.hh.
Referenced by ApproxSurfaceNormal(), CheckParameters(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), G4Para(), GetCubicVolume(), GetPointOnSurface(), GetSurfaceArea(), Inside(), operator=(), SetAllParameters(), StreamInfo(), and SurfaceNormal().
fPlanes
struct { ... } G4Para::fPlanes[4]
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), G4Para(), Inside(), MakePlanes(), operator=(), and SurfaceNormal().
fTalpha
G4double G4Para::fTalpha private
Definition at line 187 of file G4Para.hh.
Referenced by CreatePolyhedron(), G4Para(), GetPointOnSurface(), GetSurfaceArea(), MakePlanes(), operator=(), SetAllParameters(), and StreamInfo().
fTthetaCphi
G4double G4Para::fTthetaCphi private
Definition at line 187 of file G4Para.hh.
Referenced by BoundingLimits(), CalculateExtent(), CreatePolyhedron(), G4Para(), GetPointOnSurface(), GetSurfaceArea(), MakePlanes(), operator=(), SetAllParameters(), and StreamInfo().
fTthetaSphi
G4double G4Para::fTthetaSphi private
Definition at line 187 of file G4Para.hh.
Referenced by BoundingLimits(), CalculateExtent(), CreatePolyhedron(), G4Para(), GetPointOnSurface(), GetSurfaceArea(), MakePlanes(), operator=(), SetAllParameters(), and StreamInfo().
halfCarTolerance
G4double G4Para::halfCarTolerance private
Definition at line 185 of file G4Para.hh.
Referenced by DistanceToIn(), DistanceToOut(), Inside(), operator=(), and SurfaceNormal().
The documentation for this class was generated from the following files:
source/geometry/solids/CSG/include/G4Para.hh
source/geometry/solids/CSG/src/G4Para.cc