Geant4: G4LinInterpolation Class Reference
G4LinInterpolation Class Reference
#include <G4LinInterpolation.hh>
Public Member Functions
G4LinInterpolation ()
~G4LinInterpolation ()
G4double Calculate (G4double point, G4int bin, const G4DataVector &energies, const G4DataVector &data) const
G4double Calculate (G4double point, G4int bin, const G4DataVector &energies, const G4DataVector &data, const G4DataVector &log_energies, const G4DataVector &log_data) const
G4VDataSetAlgorithm * Clone () const
Public Member Functions inherited from G4VDataSetAlgorithm
G4VDataSetAlgorithm ()
virtual ~G4VDataSetAlgorithm ()
Detailed Description
Definition at line 51 of file G4LinInterpolation.hh.
Constructor & Destructor Documentation
G4LinInterpolation()
G4LinInterpolation::G4LinInterpolation ()
Definition at line 42 of file G4LinInterpolation.cc.
Referenced by Clone().
~G4LinInterpolation()
G4LinInterpolation::~G4LinInterpolation ()
Definition at line 47 of file G4LinInterpolation.cc.
Member Function Documentation
Calculate() [1/2]
G4double G4LinInterpolation::Calculate (G4double point, G4int bin, const G4DataVector & energies, const G4DataVector & data) const virtual
Implements G4VDataSetAlgorithm.
Definition at line 54 of file G4LinInterpolation.cc.
Referenced by G4DataSet::IntegrationFunction(), G4EMDataSet::IntegrationFunction(), G4DataSet::RandomSelect(), and G4EMDataSet::RandomSelect().
Calculate() [2/2]
G4double G4LinInterpolation::Calculate (G4double point, G4int bin, const G4DataVector & energies, const G4DataVector & data, const G4DataVector & log_energies, const G4DataVector & log_data) const virtual
Implements G4VDataSetAlgorithm.
Definition at line 84 of file G4LinInterpolation.cc.
Clone()
G4VDataSetAlgorithm * G4LinInterpolation::Clone () const virtual
Implements G4VDataSetAlgorithm.
Definition at line 51 of file G4LinInterpolation.cc.
The documentation for this class was generated from the following files:
source/processes/electromagnetic/lowenergy/include/G4LinInterpolation.hh
source/processes/electromagnetic/lowenergy/src/G4LinInterpolation.cc