Geant4: G4AnyMethod::FuncRef1< S, T, A0 > Struct Template Reference
G4AnyMethod::FuncRef1< S, T, A0 > Struct Template Reference
Public Types
typedef remove_const< typename remove_reference< A0 >::type >::type nakedA0
Public Member Functions
FuncRef1 (S(T::*f)(A0))
virtual void operator() (void *)
virtual void operator() (void *obj, const std::string &s0)
virtual Placeholder * Clone () const
virtual const std::type_info & ArgType (size_t) const
Public Member Functions inherited from G4AnyMethod::Placeholder
Placeholder ()
virtual ~Placeholder ()
Data Fields
S(T::* fRef)(A0)
Detailed Description
template<class S, class T, class A0>
struct G4AnyMethod::FuncRef1< S, T, A0 >
Definition at line 175 of file G4AnyMethod.hh.
Member Typedef Documentation
nakedA0
template<class S , class T , class A0 > typedef remove_const<typename remove_reference<A0>::type>::type G4AnyMethod::FuncRef1< S, T, A0 >::nakedA0
Definition at line 176 of file G4AnyMethod.hh.
Constructor & Destructor Documentation
FuncRef1()
template<class S , class T , class A0 > G4AnyMethod::FuncRef1< S, T, A0 >::FuncRef1 (S(T::*)(A0) f) inline
Definition at line 178 of file G4AnyMethod.hh.
Referenced by G4AnyMethod::FuncRef1< S, T, A0 >::Clone().
Member Function Documentation
ArgType()
template<class S , class T , class A0 > virtual const std::type_info& G4AnyMethod::FuncRef1< S, T, A0 >::ArgType (size_t) const inline virtual
Implements G4AnyMethod::Placeholder.
Definition at line 192 of file G4AnyMethod.hh.
Clone()
template<class S , class T , class A0 > virtual Placeholder* G4AnyMethod::FuncRef1< S, T, A0 >::Clone () const inline virtual
Implements G4AnyMethod::Placeholder.
Definition at line 189 of file G4AnyMethod.hh.
operator()() [1/2]
template<class S , class T , class A0 > virtual void G4AnyMethod::FuncRef1< S, T, A0 >::operator() (void *) inline virtual
Implements G4AnyMethod::Placeholder.
Definition at line 180 of file G4AnyMethod.hh.
operator()() [2/2]
template<class S , class T , class A0 > virtual void G4AnyMethod::FuncRef1< S, T, A0 >::operator() (void * obj, const std::string & s0) inline virtual
Implements G4AnyMethod::Placeholder.
Definition at line 183 of file G4AnyMethod.hh.
Field Documentation
fRef
template<class S , class T , class A0 > S(T::* G4AnyMethod::FuncRef1< S, T, A0 >::fRef) (A0)
Definition at line 195 of file G4AnyMethod.hh.
Referenced by G4AnyMethod::FuncRef1< S, T, A0 >::Clone(), and G4AnyMethod::FuncRef1< S, T, A0 >::operator()().
The documentation for this struct was generated from the following file:
source/intercoms/include/G4AnyMethod.hh