Geant4: G4BigBanger Class Reference
G4BigBanger Class Reference
#include <G4BigBanger.hh>
Public Member Functions
G4BigBanger ()
virtual ~G4BigBanger ()
virtual void deExcite (const G4Fragment &target, G4CollisionOutput &output)
Public Member Functions inherited from G4CascadeDeexciteBase
G4CascadeDeexciteBase (const char *name)
virtual ~G4CascadeDeexciteBase ()
virtual void setVerboseLevel (G4int verbose=0)
Public Member Functions inherited from G4VCascadeDeexcitation
G4VCascadeDeexcitation (const G4String &name)
virtual ~G4VCascadeDeexcitation ()
virtual void collide (G4InuclParticle *bullet, G4InuclParticle *target, G4CollisionOutput &globalOutput)
Public Member Functions inherited from G4VCascadeCollider
G4VCascadeCollider (const G4String &name, G4int verbose=0)
virtual ~G4VCascadeCollider ()
Private Member Functions
void generateBangInSCM (G4double etot, G4int a, G4int z)
void generateMomentumModules (G4double etot, G4int a, G4int z)
G4double xProbability (G4double x, G4int a) const
G4double maxProbability (G4int a) const
G4double generateX (G4int ia, G4double promax) const
G4BigBanger (const G4BigBanger &)
G4BigBanger & operator= (const G4BigBanger &)
Private Attributes
std::vector< G4InuclElementaryParticle > particles
std::vector< G4double > momModules
std::vector< G4LorentzVector > scm_momentums
Additional Inherited Members
Protected Member Functions inherited from G4CascadeDeexciteBase
virtual G4bool explosion (const G4Fragment &target) const
virtual G4bool explosion (G4int A, G4int Z, G4double excitation) const
virtual G4bool validateOutput (const G4Fragment &target, G4CollisionOutput &output)
virtual G4bool validateOutput (const G4Fragment &target, const std::vector< G4InuclElementaryParticle > &particles)
virtual G4bool validateOutput (const G4Fragment &target, const std::vector< G4InuclNuclei > &fragments)
void getTargetData (const G4Fragment &target)
const G4Fragment & makeFragment (G4LorentzVector mom, G4int A, G4int Z, G4double EX=0.)
const G4Fragment & makeFragment (G4int A, G4int Z, G4double EX=0.)
Protected Member Functions inherited from G4VCascadeCollider
virtual void setName (const G4String &name)
Protected Attributes inherited from G4CascadeDeexciteBase
G4CascadeCheckBalance * balance
G4int A
G4int Z
G4LorentzVector PEX
G4double EEXS
G4Fragment aFragment
Protected Attributes inherited from G4VCascadeCollider
G4String theName
G4int verboseLevel
Detailed Description
Definition at line 47 of file G4BigBanger.hh.
Constructor & Destructor Documentation
G4BigBanger() [1/2]
G4BigBanger::G4BigBanger ()
Definition at line 66 of file G4BigBanger.cc.
~G4BigBanger()
virtual G4BigBanger::~G4BigBanger () inline virtual
Definition at line 50 of file G4BigBanger.hh.
G4BigBanger() [2/2]
G4BigBanger::G4BigBanger (const G4BigBanger &) private
Member Function Documentation
deExcite()
void G4BigBanger::deExcite (const G4Fragment & target, G4CollisionOutput & output) virtual
Implements G4VCascadeDeexcitation.
Definition at line 68 of file G4BigBanger.cc.
Referenced by G4CascadeDeexcitation::deExcite(), and G4EquilibriumEvaporator::deExcite().
generateBangInSCM()
void G4BigBanger::generateBangInSCM (G4double etot, G4int a, G4int z) private
Definition at line 144 of file G4BigBanger.cc.
Referenced by deExcite().
generateMomentumModules()
void G4BigBanger::generateMomentumModules (G4double etot, G4int a, G4int z) private
Definition at line 239 of file G4BigBanger.cc.
Referenced by generateBangInSCM().
generateX()
G4double G4BigBanger::generateX (G4int ia, G4double promax) const private
Definition at line 312 of file G4BigBanger.cc.
Referenced by generateMomentumModules().
maxProbability()
G4double G4BigBanger::maxProbability (G4int a) const private
Definition at line 304 of file G4BigBanger.cc.
Referenced by generateMomentumModules(), and generateX().
operator=()
G4BigBanger& G4BigBanger::operator= (const G4BigBanger &) private
xProbability()
G4double G4BigBanger::xProbability (G4double x, G4int a) const private
Definition at line 284 of file G4BigBanger.cc.
Referenced by generateX(), and maxProbability().
Field Documentation
momModules
std::vector<G4double> G4BigBanger::momModules private
Definition at line 63 of file G4BigBanger.hh.
Referenced by generateBangInSCM(), and generateMomentumModules().
particles
std::vector<G4InuclElementaryParticle> G4BigBanger::particles private
Definition at line 62 of file G4BigBanger.hh.
Referenced by deExcite(), and generateBangInSCM().
scm_momentums
std::vector<G4LorentzVector> G4BigBanger::scm_momentums private
Definition at line 64 of file G4BigBanger.hh.
Referenced by generateBangInSCM().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/cascade/cascade/include/G4BigBanger.hh
source/processes/hadronic/models/cascade/cascade/src/G4BigBanger.cc