Geant4: source/processes/hadronic/models/lend/src/nf_GnG_adaptiveQuadrature.cc File Reference
nf_GnG_adaptiveQuadrature.cc File Reference
#include <float.h>
#include "nf_integration.h"
Data Structures
struct nf_GnG_adaptiveQuadrature_info_s
Typedefs
typedef struct nf_GnG_adaptiveQuadrature_info_s nf_GnG_adaptiveQuadrature_info
Functions
static double nf_GnG_adaptiveQuadrature2 (nf_GnG_adaptiveQuadrature_info *adaptiveQuadrature_info, double currentIntrgral, double x1, double x2, int depth)
nfu_status nf_GnG_adaptiveQuadrature (nf_GnG_adaptiveQuadrature_callback quadratureFunction, nf_Legendre_GaussianQuadrature_callback integrandFunction, void *argList, double x1, double x2, int maxDepth, double tolerance, double *integral, long *evaluations)
Variables
static double initialPoints [] = { 0.2311, 0.4860, 0.6068, 0.8913, 0.9501 }
static int numberOfInitialPoints = sizeof(initialPoints) / sizeof(initialPoints[0])
Typedef Documentation
nf_GnG_adaptiveQuadrature_info
typedef struct nf_GnG_adaptiveQuadrature_info_s nf_GnG_adaptiveQuadrature_info
Function Documentation
nf_GnG_adaptiveQuadrature()
nfu_status nf_GnG_adaptiveQuadrature (nf_GnG_adaptiveQuadrature_callback quadratureFunction, nf_Legendre_GaussianQuadrature_callback integrandFunction, void * argList, double x1, double x2, int maxDepth, double tolerance, double * integral, long * evaluations)
Definition at line 31 of file nf_GnG_adaptiveQuadrature.cc.
Referenced by ptwXY_integrateWithFunction().
nf_GnG_adaptiveQuadrature2()
static double nf_GnG_adaptiveQuadrature2 (nf_GnG_adaptiveQuadrature_info * adaptiveQuadrature_info, double currentIntrgral, double x1, double x2, int depth) static
Definition at line 79 of file nf_GnG_adaptiveQuadrature.cc.
Referenced by nf_GnG_adaptiveQuadrature().
Variable Documentation
initialPoints
double initialPoints[] = { 0.2311, 0.4860, 0.6068, 0.8913, 0.9501 } static
Definition at line 24 of file nf_GnG_adaptiveQuadrature.cc.
Referenced by nf_GnG_adaptiveQuadrature().
numberOfInitialPoints
int numberOfInitialPoints = sizeof(initialPoints) / sizeof(initialPoints[0]) static
Definition at line 25 of file nf_GnG_adaptiveQuadrature.cc.
Referenced by nf_GnG_adaptiveQuadrature().