Geant4: B03ImportanceDetectorConstruction Class Reference
B03ImportanceDetectorConstruction Class Reference
#include <B03ImportanceDetectorConstruction.hh>
Public Member Functions
B03ImportanceDetectorConstruction (G4String worldName)
~B03ImportanceDetectorConstruction ()
const G4VPhysicalVolume & GetPhysicalVolumeByName (const G4String &name) const
G4VPhysicalVolume & GetWorldVolumeAddress () const
G4String ListPhysNamesAsG4String ()
G4String GetCellName (G4int i)
G4GeometryCell GetGeometryCell (G4int i)
G4VPhysicalVolume * GetWorldVolume ()
void SetSensitive ()
virtual void ConstructSD ()
Public Member Functions inherited from G4VUserParallelWorld
G4VUserParallelWorld (G4String worldName)
virtual ~G4VUserParallelWorld ()
G4String GetName ()
Private Member Functions
virtual void Construct ()
Private Attributes
B03PVolumeStore fPVolumeStore
std::vector< G4LogicalVolume * > fLogicalVolumeVector
G4VPhysicalVolume * fGhostWorld
Additional Inherited Members
Protected Member Functions inherited from G4VUserParallelWorld
G4VPhysicalVolume * GetWorld ()
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Protected Attributes inherited from G4VUserParallelWorld
G4String fWorldName
Detailed Description
Definition at line 46 of file B03ImportanceDetectorConstruction.hh.
Constructor & Destructor Documentation
B03ImportanceDetectorConstruction()
B03ImportanceDetectorConstruction::B03ImportanceDetectorConstruction (G4String worldName)
Definition at line 57 of file B03ImportanceDetectorConstruction.cc.
~B03ImportanceDetectorConstruction()
B03ImportanceDetectorConstruction::~B03ImportanceDetectorConstruction ()
Definition at line 65 of file B03ImportanceDetectorConstruction.cc.
Member Function Documentation
Construct()
void B03ImportanceDetectorConstruction::Construct (void) private virtual
Implements G4VUserParallelWorld.
Definition at line 72 of file B03ImportanceDetectorConstruction.cc.
ConstructSD()
void B03ImportanceDetectorConstruction::ConstructSD () virtual
Reimplemented from G4VUserParallelWorld.
Definition at line 261 of file B03ImportanceDetectorConstruction.cc.
GetCellName()
G4String B03ImportanceDetectorConstruction::GetCellName (G4int i)
Definition at line 199 of file B03ImportanceDetectorConstruction.cc.
Referenced by Construct(), B03RunAction::EndOfRunAction(), and GetGeometryCell().
GetGeometryCell()
G4GeometryCell B03ImportanceDetectorConstruction::GetGeometryCell (G4int i)
Definition at line 212 of file B03ImportanceDetectorConstruction.cc.
Referenced by main().
GetPhysicalVolumeByName()
const G4VPhysicalVolume & B03ImportanceDetectorConstruction::GetPhysicalVolumeByName (const G4String & name) const
Definition at line 186 of file B03ImportanceDetectorConstruction.cc.
GetWorldVolume()
G4VPhysicalVolume * B03ImportanceDetectorConstruction::GetWorldVolume ()
Definition at line 235 of file B03ImportanceDetectorConstruction.cc.
GetWorldVolumeAddress()
G4VPhysicalVolume & B03ImportanceDetectorConstruction::GetWorldVolumeAddress () const
Definition at line 229 of file B03ImportanceDetectorConstruction.cc.
Referenced by main().
ListPhysNamesAsG4String()
G4String B03ImportanceDetectorConstruction::ListPhysNamesAsG4String ()
Definition at line 192 of file B03ImportanceDetectorConstruction.cc.
SetSensitive()
void B03ImportanceDetectorConstruction::SetSensitive ()
Definition at line 241 of file B03ImportanceDetectorConstruction.cc.
Referenced by Construct().
Field Documentation
fGhostWorld
G4VPhysicalVolume* B03ImportanceDetectorConstruction::fGhostWorld private
Definition at line 73 of file B03ImportanceDetectorConstruction.hh.
Referenced by Construct(), GetGeometryCell(), GetWorldVolume(), and GetWorldVolumeAddress().
fLogicalVolumeVector
std::vector< G4LogicalVolume * > B03ImportanceDetectorConstruction::fLogicalVolumeVector private
Definition at line 69 of file B03ImportanceDetectorConstruction.hh.
Referenced by Construct(), ConstructSD(), and ~B03ImportanceDetectorConstruction().
fPVolumeStore
B03PVolumeStore B03ImportanceDetectorConstruction::fPVolumeStore private
Definition at line 66 of file B03ImportanceDetectorConstruction.hh.
Referenced by Construct(), GetGeometryCell(), GetPhysicalVolumeByName(), and ListPhysNamesAsG4String().
The documentation for this class was generated from the following files:
examples/extended/biasing/B03/include/B03ImportanceDetectorConstruction.hh
examples/extended/biasing/B03/src/B03ImportanceDetectorConstruction.cc