Geant4: G4IT Class Reference
G4IT Class Reference abstract
G4IT is a interface which allows the inheriting object to be tracked using G4ITStepProcessor The inheriting class must implement the operator < , == and != in order to enable the sorting out.
#include <G4IT.hh>
Public Member Functions
G4IT ()
G4IT (G4Track *)
virtual ~G4IT ()
virtual void Print () const
virtual const G4String & GetName () const =0
virtual G4bool diff (const G4IT &right) const =0
virtual G4bool equal (const G4IT &right) const =0
G4bool operator< (const G4IT &right) const
G4bool operator== (const G4IT &right) const
G4bool operator!= (const G4IT &right) const
void SetTrack (G4Track *)
G4Track * GetTrack ()
const G4Track * GetTrack () const
void RecordCurrentPositionNTime ()
const G4ThreeVector & GetPosition () const
double operator[] (int i) const
const G4ThreeVector & GetPreStepPosition () const
G4double GetPreStepLocalTime () const
G4double GetPreStepGlobalTime () const
void SetPrevious (G4IT *)
void SetNext (G4IT *)
G4IT * GetPrevious ()
G4IT * GetNext ()
const G4IT * GetPrevious () const
const G4IT * GetNext () const
void SetITBox (G4ITBox *)
const G4ITBox * GetITBox () const
void TakeOutBox ()
void SetNode (G4KDNode_Base *)
G4KDNode_Base * GetNode () const
void SetParentID (int, int)
void GetParentID (int &, int &)
G4TrackingInformation * GetTrackingInfo ()
G4TrackListNode * GetListNode ()
void SetListNode (G4TrackListNode *node)
virtual const G4ITType GetITType () const =0
virtual G4ITType GetITSubType () const
Public Member Functions inherited from G4VUserTrackInformation
G4VUserTrackInformation ()
G4VUserTrackInformation (const G4String &infoType)
G4VUserTrackInformation (const G4VUserTrackInformation &)
G4VUserTrackInformation & operator= (const G4VUserTrackInformation &)
virtual ~G4VUserTrackInformation ()
const G4String & GetType () const
Protected Member Functions
G4IT (const G4IT &)
G4IT & operator= (const G4IT &)
Protected Attributes
G4Track * fpTrack
Protected Attributes inherited from G4VUserTrackInformation
G4String * pType
Private Attributes
G4ITBox * fpITBox
G4IT * fpPreviousIT
G4IT * fpNextIT
G4KDNode_Base * fpKDNode
int fParentID_A
int fParentID_B
G4TrackingInformation * fpTrackingInformation
G4TrackListNode * fpTrackNode
Detailed Description
G4IT is a interface which allows the inheriting object to be tracked using G4ITStepProcessor The inheriting class must implement the operator < , == and != in order to enable the sorting out.
also the concrete header of MyIT ("MyIt.hh") should contain : ITDef(MyIT) and the source of MyIT.cc : ITImp(MyIT)
Definition at line 87 of file G4IT.hh.
Constructor & Destructor Documentation
G4IT() [1/3]
G4IT::G4IT ()
Definition at line 67 of file G4IT.cc.
G4IT() [2/3]
G4IT::G4IT (G4Track * aTrack)
Definition at line 124 of file G4IT.cc.
~G4IT()
G4IT::~G4IT () virtual
Definition at line 160 of file G4IT.cc.
G4IT() [3/3]
G4IT::G4IT (const G4IT &) protected
Definition at line 82 of file G4IT.cc.
Member Function Documentation
diff()
virtual G4bool G4IT::diff (const G4IT & right) const pure virtual
Referenced by operator<().
equal()
virtual G4bool G4IT::equal (const G4IT & right) const pure virtual
Referenced by operator==().
GetITBox()
const G4ITBox * G4IT::GetITBox () const inline
Definition at line 183 of file G4IT.hh.
GetITSubType()
virtual G4ITType G4IT::GetITSubType () const inline virtual
Reimplemented in G4Molecule.
Definition at line 159 of file G4IT.hh.
Referenced by G4ITTrackHolder::PushDelayed(), and G4ITTrackHolder::PushTo().
GetITType()
virtual const G4ITType G4IT::GetITType () const pure virtual
Referenced by G4ITModelProcessor::DoCalculateStep(), G4ITModelProcessor::FindReaction(), operator<(), operator==(), and G4AllITFinder::Push().
GetListNode()
G4TrackListNode* G4IT::GetListNode () inline
Definition at line 148 of file G4IT.hh.
GetName()
virtual const G4String& G4IT::GetName () const pure virtual
Implemented in G4Molecule.
Referenced by G4ITTrackHolder::_PushTrack(), G4ITModelProcessor::CalculateMinTimeStep(), G4ITStepProcessor::ComputeInteractionLength(), G4ITModelProcessor::ComputeTrackReaction(), G4DNABrownianTransportation::Diffusion(), G4ITTrackHolder::KillTracks(), G4ITSteppingVerbose::PostStepVerbose(), G4ITSteppingVerbose::PreStepVerbose(), and G4ITSteppingVerbose::TrackingStarted().
GetNext() [1/2]
G4IT * G4IT::GetNext () inline
Definition at line 208 of file G4IT.hh.
Referenced by G4ITBox::Extract(), G4ITBox::TransferTo(), and G4ITBox::~G4ITBox().
GetNext() [2/2]
const G4IT * G4IT::GetNext () const inline
Definition at line 245 of file G4IT.hh.
GetNode()
G4KDNode_Base * G4IT::GetNode () const inline
Definition at line 255 of file G4IT.hh.
GetParentID()
void G4IT::GetParentID (int & p_a, int & p_b) inline
Definition at line 234 of file G4IT.hh.
GetPosition()
const G4ThreeVector & G4IT::GetPosition () const
Definition at line 214 of file G4IT.cc.
GetPreStepGlobalTime()
G4double G4IT::GetPreStepGlobalTime () const
Definition at line 228 of file G4IT.cc.
GetPreStepLocalTime()
G4double G4IT::GetPreStepLocalTime () const
Definition at line 233 of file G4IT.cc.
GetPreStepPosition()
const G4ThreeVector & G4IT::GetPreStepPosition () const
Definition at line 238 of file G4IT.cc.
GetPrevious() [1/2]
G4IT * G4IT::GetPrevious () inline
Definition at line 203 of file G4IT.hh.
Referenced by G4ITBox::Extract(), and G4ITBox::FindIT().
GetPrevious() [2/2]
const G4IT * G4IT::GetPrevious () const inline
Definition at line 240 of file G4IT.hh.
GetTrack() [1/2]
G4Track * G4IT::GetTrack () inline
Definition at line 218 of file G4IT.hh.
Referenced by G4DNAMoleculeEncounterStepper::CheckAndRecordResults(), and GetPosition().
GetTrack() [2/2]
const G4Track * G4IT::GetTrack () const inline
Definition at line 223 of file G4IT.hh.
GetTrackingInfo()
G4TrackingInformation* G4IT::GetTrackingInfo () inline
Definition at line 143 of file G4IT.hh.
Referenced by G4ITTransportation::AlongStepGetPhysicalInteractionLength(), ITTrackingInteractivity::AppendStep(), G4DNABrownianTransportation::ComputeGeomLimit(), G4ITStepProcessor::DoDefinePhysicalStepLength(), ITTrackingInteractivity::EndTracking(), G4ITStepProcessor::InitDefineStep(), G4ITLeadingTracks::PrepareLeadingTracks(), G4ITLeadingTracks::Reset(), G4ITStepProcessor::SetInitialStep(), G4ITStepProcessor::SetTrack(), G4ITStepProcessor::SetupMembers(), ITTrackingInteractivity::StartTracking(), and G4VITProcess::StartTracking().
operator!=()
G4bool G4IT::operator!= (const G4IT & right) const
Definition at line 202 of file G4IT.cc.
operator<()
G4bool G4IT::operator< (const G4IT & right) const
Definition at line 180 of file G4IT.cc.
operator=()
G4IT & G4IT::operator= (const G4IT & right) protected
Definition at line 97 of file G4IT.cc.
operator==()
G4bool G4IT::operator== (const G4IT & right) const
Definition at line 193 of file G4IT.cc.
Referenced by operator!=().
operator[]()
double G4IT::operator[] (int i) const
Definition at line 207 of file G4IT.cc.
Print()
virtual void G4IT::Print (void) const inline virtual
Reimplemented from G4VUserTrackInformation.
Definition at line 97 of file G4IT.hh.
RecordCurrentPositionNTime()
void G4IT::RecordCurrentPositionNTime ()
Definition at line 220 of file G4IT.cc.
Referenced by G4IT().
SetITBox()
void G4IT::SetITBox (G4ITBox * aITBox) inline
Definition at line 188 of file G4IT.hh.
Referenced by G4ITBox::Extract(), and G4ITBox::Push().
SetListNode()
void G4IT::SetListNode (G4TrackListNode * node) inline
Definition at line 152 of file G4IT.hh.
SetNext()
void G4IT::SetNext (G4IT * aIT) inline
Definition at line 198 of file G4IT.hh.
Referenced by G4ITBox::Extract(), and G4ITBox::Push().
SetNode()
void G4IT::SetNode (G4KDNode_Base * aNode) inline
Definition at line 250 of file G4IT.hh.
SetParentID()
void G4IT::SetParentID (int p_a, int p_b) inline
Definition at line 228 of file G4IT.hh.
Referenced by G4ITModelProcessor::ComputeTrackReaction().
SetPrevious()
void G4IT::SetPrevious (G4IT * aIT) inline
Definition at line 193 of file G4IT.hh.
Referenced by G4ITBox::Extract(), and G4ITBox::Push().
SetTrack()
void G4IT::SetTrack (G4Track * track) inline
Definition at line 213 of file G4IT.hh.
TakeOutBox()
void G4IT::TakeOutBox ()
Definition at line 139 of file G4IT.cc.
Referenced by ~G4IT().
Field Documentation
fParentID_A
int G4IT::fParentID_A private
Definition at line 175 of file G4IT.hh.
Referenced by G4IT(), GetParentID(), operator=(), and SetParentID().
fParentID_B
int G4IT::fParentID_B private
Definition at line 176 of file G4IT.hh.
Referenced by G4IT(), GetParentID(), operator=(), and SetParentID().
fpITBox
G4ITBox* G4IT::fpITBox private
Definition at line 170 of file G4IT.hh.
Referenced by G4IT(), GetITBox(), operator=(), SetITBox(), and TakeOutBox().
fpKDNode
G4KDNode_Base* G4IT::fpKDNode private
Definition at line 173 of file G4IT.hh.
Referenced by G4IT(), GetNode(), operator=(), SetNode(), and TakeOutBox().
fpNextIT
G4IT* G4IT::fpNextIT private
Definition at line 172 of file G4IT.hh.
Referenced by GetNext(), operator=(), and SetNext().
fpPreviousIT
G4IT* G4IT::fpPreviousIT private
Definition at line 171 of file G4IT.hh.
Referenced by GetPrevious(), operator=(), and SetPrevious().
fpTrack
G4Track* G4IT::fpTrack protected
Definition at line 167 of file G4IT.hh.
Referenced by G4Molecule::BuildTrack(), G4IT(), GetPosition(), GetTrack(), operator=(), operator[](), RecordCurrentPositionNTime(), SetTrack(), and G4Molecule::~G4Molecule().
fpTrackingInformation
G4TrackingInformation* G4IT::fpTrackingInformation private
Definition at line 178 of file G4IT.hh.
Referenced by GetPreStepGlobalTime(), GetPreStepLocalTime(), GetPreStepPosition(), GetTrackingInfo(), operator=(), RecordCurrentPositionNTime(), and ~G4IT().
fpTrackNode
G4TrackListNode* G4IT::fpTrackNode private
Definition at line 179 of file G4IT.hh.
Referenced by G4IT(), GetListNode(), operator=(), SetListNode(), and TakeOutBox().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/dna/management/include/G4IT.hh
source/processes/electromagnetic/dna/management/src/G4IT.cc