Geant4: G4INCL::DeJongSpin Namespace Reference
G4INCL::DeJongSpin Namespace Reference
Functions
ThreeVector shoot (const G4int Ap, const G4int Af)
Function Documentation
shoot()
ThreeVector G4INCL::DeJongSpin::shoot (const G4int Ap, const G4int Af)
Definition at line 68 of file G4INCLDeJongSpin.cc.
Referenced by G4MoleculeGun::AddMolecule(), G4MoleculeGun::AddMoleculeInCMRepresentation(), G4MoleculeGun::AddMoleculeShoot(), G4MoleculeGun::AddMoleculesRandomPositionInBox(), G4MoleculeGun::AddNMolecules(), G4DNABrownianTransportation::AlongStepDoIt(), GFlashSamplingShowerParameterisation::ApplySampling(), G4LENDModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4LFission::ApplyYourself(), G4HETCFragment::BetaRand(), G4Fancy3DNucleus::ChoosePositions(), G4StatMFMicroPartition::ChooseZ(), G4StatMFMacroCanonical::ChooseZ(), G4DNABrownianTransportation::ComputeStep(), G4MoleculeGunMessenger::CreateNewType(), CexmcEnergyDepositDigitizer::Digitize(), G4hImpactIonisation::ElectronicLossFluctuation(), Run::EndOfEvent(), Par01PionShowerModel::Explode(), Par01EMShowerModel::Explode(), pyRandomize::f1_RandGaussQ_shoot(), pyRandomize::f2_RandGaussQ_shoot(), G4CompetitiveFission::FissionCharge(), G4CompetitiveFission::FissionKineticEnergy(), G4INCL::Random::gauss(), MedicalBeam::GenerateBeamDirection(), G4SPSAngDistribution::GenerateBeamFlux(), GFlashHomoShowerParameterisation::GenerateEnergyProfile(), GFlashSamplingShowerParameterisation::GenerateEnergyProfile(), GFlashHomoShowerParameterisation::GenerateExponential(), GFlashSamplingShowerParameterisation::GenerateExponential(), CML2PrimaryGenerationAction::GenerateFromRandom(), G4SPSEneDistribution::GenerateGaussEnergies(), G4SPSPosDistribution::GeneratePointsInBeam(), IORTPrimaryGeneratorAction::GeneratePrimaries(), CexmcPrimaryGeneratorAction::GeneratePrimaries(), CCalPrimaryGeneratorAction::GeneratePrimaries(), G4OpBoundaryProcess::GetFacetNormal(), G4Nucleus::GetFermiMomentum(), DNA::Penetration::GetGaussianPenetrationFromRmean3D(), G4RDVeLowEnergyLoss::GetLossWithFluct(), G4ParticleHPProduct::GetMultiplicity(), DNA::Penetration::Terrisol1990::GetPenetration(), G4Polycone::GetPointOnCone(), G4Tet::GetPointOnFace(), G4Polyhedra::GetPointOnPlane(), G4Polycone::GetPointOnRing(), G4VTwistedFaceted::GetPointOnSurface(), G4Ellipsoid::GetPointOnSurface(), G4Tet::GetPointOnSurface(), G4Polycone::GetPointOnSurface(), G4Polyhedra::GetPointOnSurface(), G4CutTubs::GetPointOnSurface(), G4Paraboloid::GetPointOnSurface(), G4Hype::GetPointOnSurface(), G4Tubs::GetPointOnSurface(), G4Torus::GetPointOnSurface(), G4Cons::GetPointOnSurface(), G4Sphere::GetPointOnSurface(), G4TwistedTubs::GetPointOnSurface(), G4TessellatedSolid::GetPointOnSurface(), G4Polyhedra::GetPointOnTriangle(), G4Polycone::GetPointOnTubs(), G4Nucleus::GetThermalPz(), G4hICRU49Nuclear::NuclearStoppingPower(), G4hZiegler1985Nuclear::NuclearStoppingPower(), G4ICRU49NuclearStoppingModel::NuclearStoppingPower(), G4VXTRenergyLoss::PostStepDoIt(), G4Scintillation::PostStepDoIt(), doiPETAnalysis::QuantumEffifciency(), G4DNAWaterDissociationDisplacer::radialDistributionOfProducts(), XrayFluoEventAction::RandomCut(), G4UrbanMscModel::Randomizetlimit(), G4UrbanAdjointMscModel::Randomizetlimit(), G4GoudsmitSaundersonMscModel::Randomizetlimit(), G4UrbanAdjointMscModel::SampleDisplacementNew(), G4UniversalFluctuation::SampleFluctuations(), G4BohrFluctuations::SampleFluctuations(), G4AtimaFluctuations::SampleFluctuations(), G4IonFluctuations::SampleFluctuations(), G4mplIonisationModel::SampleFluctuations(), G4mplIonisationWithDeltaModel::SampleFluctuations(), G4UniversalFluctuation::SampleGauss(), G4ElectronIonPair::SampleNumberOfIonsAlongStep(), G4VLongitudinalStringDecay::SampleQuarkPt(), G4WentzelVIModel::SampleScattering(), G4HeatedKleinNishinaCompton::SampleSecondaries(), G4NuclNuclDiffuseElastic::SampleThetaCMS(), G4DiffuseElastic::SampleThetaCMS(), and G4QGSMSplitableHadron::SampleX().