Geant4: G4PSTrackLength Class Reference
G4PSTrackLength Class Reference
#include <G4PSTrackLength.hh>
Public Member Functions
G4PSTrackLength (G4String name, G4int depth=0)
G4PSTrackLength (G4String name, const G4String &unit, G4int depth=0)
virtual ~G4PSTrackLength ()
void Weighted (G4bool flg=true)
void MultiplyKineticEnergy (G4bool flg=true)
void DivideByVelocity (G4bool flg=true)
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
virtual void SetUnit (const G4String &unit)
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Protected Member Functions
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
virtual void DefineUnitAndCategory ()
Protected Member Functions inherited from G4VPrimitiveScorer
virtual G4int GetIndex (G4Step *)
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Private Attributes
G4int HCID
G4THitsMap< G4double > * EvtMap
G4bool weighted
G4bool multiplyKinE
G4bool divideByVelocity
Additional Inherited Members
Protected Attributes inherited from G4VPrimitiveScorer
G4String primitiveName
G4MultiFunctionalDetector * detector
G4VSDFilter * filter
G4int verboseLevel
G4int indexDepth
G4String unitName
G4double unitValue
G4int fNi
G4int fNj
G4int fNk
Detailed Description
Definition at line 48 of file G4PSTrackLength.hh.
Constructor & Destructor Documentation
G4PSTrackLength() [1/2]
G4PSTrackLength::G4PSTrackLength (G4String name, G4int depth = 0)
Definition at line 43 of file G4PSTrackLength.cc.
G4PSTrackLength() [2/2]
G4PSTrackLength::G4PSTrackLength (G4String name, const G4String & unit, G4int depth = 0)
Definition at line 51 of file G4PSTrackLength.cc.
~G4PSTrackLength()
G4PSTrackLength::~G4PSTrackLength () virtual
Definition at line 60 of file G4PSTrackLength.cc.
Member Function Documentation
clear()
void G4PSTrackLength::clear (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 99 of file G4PSTrackLength.cc.
DefineUnitAndCategory()
void G4PSTrackLength::DefineUnitAndCategory () protected virtual
Definition at line 160 of file G4PSTrackLength.cc.
Referenced by G4PSTrackLength().
DivideByVelocity()
void G4PSTrackLength::DivideByVelocity (G4bool flg = true)
Definition at line 70 of file G4PSTrackLength.cc.
Referenced by B03ImportanceDetectorConstruction::ConstructSD(), B02ImportanceDetectorConstruction::ConstructSD(), and B01DetectorConstruction::ConstructSDandField().
DrawAll()
void G4PSTrackLength::DrawAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 103 of file G4PSTrackLength.cc.
EndOfEvent()
void G4PSTrackLength::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 96 of file G4PSTrackLength.cc.
Initialize()
void G4PSTrackLength::Initialize (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 89 of file G4PSTrackLength.cc.
MultiplyKineticEnergy()
void G4PSTrackLength::MultiplyKineticEnergy (G4bool flg = true)
Definition at line 63 of file G4PSTrackLength.cc.
Referenced by B03ImportanceDetectorConstruction::ConstructSD(), B02ImportanceDetectorConstruction::ConstructSD(), and B01DetectorConstruction::ConstructSDandField().
PrintAll()
void G4PSTrackLength::PrintAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 106 of file G4PSTrackLength.cc.
ProcessHits()
G4bool G4PSTrackLength::ProcessHits (G4Step * aStep, G4TouchableHistory *) protected virtual
Implements G4VPrimitiveScorer.
Definition at line 77 of file G4PSTrackLength.cc.
SetUnit()
void G4PSTrackLength::SetUnit (const G4String & unit) virtual
Definition at line 127 of file G4PSTrackLength.cc.
Referenced by DivideByVelocity(), G4PSTrackLength(), G4PSTrackLength3D::G4PSTrackLength3D(), and MultiplyKineticEnergy().
Weighted()
void G4PSTrackLength::Weighted (G4bool flg = true) inline
Definition at line 56 of file G4PSTrackLength.hh.
Referenced by B03ImportanceDetectorConstruction::ConstructSD(), B02ImportanceDetectorConstruction::ConstructSD(), and B01DetectorConstruction::ConstructSDandField().
Field Documentation
divideByVelocity
G4bool G4PSTrackLength::divideByVelocity private
Definition at line 86 of file G4PSTrackLength.hh.
Referenced by DivideByVelocity(), PrintAll(), ProcessHits(), and SetUnit().
EvtMap
G4THitsMap<G4double>* G4PSTrackLength::EvtMap private
Definition at line 83 of file G4PSTrackLength.hh.
Referenced by clear(), Initialize(), PrintAll(), and ProcessHits().
HCID
G4int G4PSTrackLength::HCID private
Definition at line 82 of file G4PSTrackLength.hh.
Referenced by Initialize().
multiplyKinE
G4bool G4PSTrackLength::multiplyKinE private
Definition at line 85 of file G4PSTrackLength.hh.
Referenced by MultiplyKineticEnergy(), PrintAll(), ProcessHits(), and SetUnit().
weighted
G4bool G4PSTrackLength::weighted private
Definition at line 84 of file G4PSTrackLength.hh.
Referenced by ProcessHits(), and Weighted().
The documentation for this class was generated from the following files:
source/digits_hits/scorer/include/G4PSTrackLength.hh
source/digits_hits/scorer/src/G4PSTrackLength.cc