Geant4: G4UserRunAction Class Reference
G4UserRunAction Class Reference
#include <G4UserRunAction.hh>
Public Member Functions
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *aRun)
virtual void EndOfRunAction (const G4Run *aRun)
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Protected Attributes
G4bool isMaster
Detailed Description
Definition at line 51 of file G4UserRunAction.hh.
Constructor & Destructor Documentation
G4UserRunAction()
G4UserRunAction::G4UserRunAction ()
Definition at line 34 of file G4UserRunAction.cc.
~G4UserRunAction()
G4UserRunAction::~G4UserRunAction () virtual
Definition at line 51 of file G4UserRunAction.cc.
Member Function Documentation
BeginOfRunAction()
void G4UserRunAction::BeginOfRunAction (const G4Run * aRun) virtual
Reimplemented in RunAction, RunAction, B2RunAction, B2RunAction, B2RunAction, G4MultiRunAction, G4AdjointSimManager, G4BlineTracer, CML2RunAction, UltraRunAction, OpNoviceRunAction, F01RunAction, ExGflashRunAction, CCalRunAction, RunActionMaster, CB_G4UserRunAction, RunAction, RunActionMaster, RunAction, RunAction, RE02RunAction, RunAction, XrayTelRunAction, XrayFluoRunAction, RMC01RunAction, RunAction, B4bRunAction, RunAction, RunAction, RunAction, TSRunAction, doiPETRunAction, B4RunAction, B4RunAction, B4RunAction, B4RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, DMXRunAction, RunAction, RunAction, IORTRunAction, B01RunAction, B02RunAction, B03RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, Par02RunAction, G02RunAction, RunAction, GammaRayTelRunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, G03RunAction, RunAction, RunAction, PurgMagRunAction, RunAction, RunAction, RunAction, RunAction, RunAction, BrachyRunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, FFRunAction, RunAction, WLSRunAction, GammaKnifeRunAction, RunAction, RunAction, RunAction, B1ConRunAction, RunAction, RunAction, RunAction, RunAction, ExP01RunAction, B1RunAction, DicomRunAction, RunAction, B1RunAction, RunAction, HadrontherapyRunAction, RunAction, RunAction, ExUCNRunAction, RunAction, ExN02RunAction, ExN04RunAction, FCALRunAction, RunAction, F04RunAction, RunAction, RunAction, RE05RunAction, G4RTRunAction, RunAction, RunAction, RunAction, RunAction, RunAction, B5RunAction, RunAction, RunAction, LXeRunAction, eRositaRunAction, B3bRunAction, ExTGRunAction, RE01RunAction, RE06RunAction, G4HumanPhantomRunAction, ExN04RunAction, B3aRunAction, B3aRunAction, and RunAction.
Definition at line 57 of file G4UserRunAction.cc.
Referenced by G4MPIextraWorker::BeamOn(), CB_G4UserRunAction::BeginOfRunAction(), G4AdjointSimManager::BeginOfRunAction(), export_G4UserRunAction(), G4WorkerRunManager::RunInitialization(), and G4RunManager::RunInitialization().
EndOfRunAction()
void G4UserRunAction::EndOfRunAction (const G4Run * aRun) virtual
Reimplemented in CexmcRunAction, RunAction, RunAction, B2RunAction, B2RunAction, B2RunAction, G4MultiRunAction, Dicom2RunAction, G4AdjointSimManager, G4BlineTracer, CML2RunAction, UltraRunAction, OpNoviceRunAction, CB_G4UserRunAction, F01RunAction, ExGflashRunAction, CCalRunAction, RunActionMaster, RunAction, RunActionMaster, RunAction, RunAction, RE02RunAction, RunAction, XrayTelRunAction, XrayFluoRunAction, RMC01RunAction, RunAction, RunAction, RunAction, RunAction, B4bRunAction, RunAction, TSRunAction, doiPETRunAction, B4RunAction, B4RunAction, B4RunAction, B4RunAction, Par02RunAction, RunAction, RunAction, RunAction, RunAction, DMXRunAction, RunAction, RunAction, RunAction, IORTRunAction, B01RunAction, B02RunAction, B03RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, G02RunAction, RunAction, GammaRayTelRunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, G03RunAction, RunAction, RunAction, PurgMagRunAction, RunAction, RunAction, RunAction, RunAction, RunAction, BrachyRunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, FFRunAction, RunAction, WLSRunAction, GammaKnifeRunAction, RunAction, RunAction, RunAction, B1ConRunAction, RunAction, RunAction, RunAction, RunAction, ExP01RunAction, B1RunAction, DicomRunAction, RunAction, B1RunAction, RunAction, HadrontherapyRunAction, FCALRunAction, RunAction, RunAction, ExUCNRunAction, RunAction, RunAction, RunAction, ExN02RunAction, RunAction, F04RunAction, RunAction, RunAction, G4RTRunAction, RunAction, RunAction, RunAction, B5RunAction, RunAction, RunAction, LXeRunAction, eRositaRunAction, B3bRunAction, ElectronRunAction, ExTGRunAction, RE01RunAction, RE06RunAction, G4HumanPhantomRunAction, B3aRunAction, B3aRunAction, and RunAction.
Definition at line 60 of file G4UserRunAction.cc.
Referenced by G4MPIextraWorker::BeamOn(), CB_G4UserRunAction::EndOfRunAction(), G4AdjointSimManager::EndOfRunAction(), export_G4UserRunAction(), and G4RunManager::RunTermination().
GenerateRun()
G4Run * G4UserRunAction::GenerateRun (void) virtual
Reimplemented in CexmcRunAction, G4MultiRunAction, Dicom2RunAction, RE02RunAction, RunAction, TSRunAction, B4bRunAction, RunAction, RunAction, doiPETRunAction, CML2RunAction, RunAction, RunAction, RunAction, B01RunAction, B02RunAction, B03RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, B1ConRunAction, DicomRunAction, RunAction, B1RunAction, RunAction, RunAction, G4RTRunAction, LXeRunAction, B3bRunAction, ElectronRunAction, RE06RunAction, RunActionMaster, RunAction, RunActionMaster, and RunAction.
Definition at line 54 of file G4UserRunAction.cc.
Referenced by G4WorkerRunManager::RunInitialization(), and G4RunManager::RunInitialization().
IsMaster()
G4bool G4UserRunAction::IsMaster () const inline
Definition at line 68 of file G4UserRunAction.hh.
Referenced by ExTGRunAction::BeginOfRunAction(), HadrontherapyRunAction::BeginOfRunAction(), B1ConRunAction::BeginOfRunAction(), PurgMagRunAction::BeginOfRunAction(), GammaRayTelRunAction::BeginOfRunAction(), UltraRunAction::BeginOfRunAction(), DMXRunAction::BeginOfRunAction(), TSRunAction::BeginOfRunAction(), XrayFluoRunAction::BeginOfRunAction(), XrayTelRunAction::BeginOfRunAction(), B3aRunAction::EndOfRunAction(), B3bRunAction::EndOfRunAction(), RE06RunAction::EndOfRunAction(), HadrontherapyRunAction::EndOfRunAction(), DicomRunAction::EndOfRunAction(), B1RunAction::EndOfRunAction(), B1ConRunAction::EndOfRunAction(), Dicom2RunAction::EndOfRunAction(), PurgMagRunAction::EndOfRunAction(), B03RunAction::EndOfRunAction(), UltraRunAction::EndOfRunAction(), B02RunAction::EndOfRunAction(), B01RunAction::EndOfRunAction(), CML2RunAction::EndOfRunAction(), TSRunAction::EndOfRunAction(), XrayTelRunAction::EndOfRunAction(), RE02RunAction::EndOfRunAction(), and XrayFluoRunAction::Initialise().
SetMaster()
virtual void G4UserRunAction::SetMaster (G4bool val = true) inline virtual
Reimplemented in G4MultiRunAction.
Definition at line 66 of file G4UserRunAction.hh.
Referenced by G4MultiRunAction::SetMaster(), G4WorkerRunManager::SetUserAction(), and G4MTRunManager::SetUserAction().
Field Documentation
isMaster
G4bool G4UserRunAction::isMaster protected
Definition at line 63 of file G4UserRunAction.hh.
Referenced by doiPETRunAction::BeginOfRunAction(), LXeRunAction::EndOfRunAction(), B4RunAction::EndOfRunAction(), B4bRunAction::EndOfRunAction(), RunAction::InitializeWorker(), IsMaster(), SetMaster(), and Par02RunAction::~Par02RunAction().
The documentation for this class was generated from the following files:
source/run/include/G4UserRunAction.hh
source/run/src/G4UserRunAction.cc