Geant4: G4TrajectoryContainer Class Reference
G4TrajectoryContainer Class Reference
#include <G4TrajectoryContainer.hh>
Public Member Functions
G4TrajectoryContainer ()
~G4TrajectoryContainer ()
void * operator new (size_t)
void operator delete (void *anEvent)
G4bool operator== (const G4TrajectoryContainer &right) const
G4bool operator!= (const G4TrajectoryContainer &right) const
size_t size () const
void push_back (G4VTrajectory *p)
G4int entries () const
G4bool insert (G4VTrajectory *p)
void clearAndDestroy ()
G4VTrajectory * operator[] (size_t n)
TrajectoryVector * GetVector () const
Private Member Functions
G4TrajectoryContainer (const G4TrajectoryContainer &)
G4TrajectoryContainer & operator= (const G4TrajectoryContainer &)
Private Attributes
TrajectoryVector * vect
Detailed Description
Definition at line 50 of file G4TrajectoryContainer.hh.
Constructor & Destructor Documentation
G4TrajectoryContainer() [1/2]
G4TrajectoryContainer::G4TrajectoryContainer ()
Definition at line 37 of file G4TrajectoryContainer.cc.
~G4TrajectoryContainer()
G4TrajectoryContainer::~G4TrajectoryContainer ()
Definition at line 42 of file G4TrajectoryContainer.cc.
G4TrajectoryContainer() [2/2]
G4TrajectoryContainer::G4TrajectoryContainer (const G4TrajectoryContainer &) private
Member Function Documentation
clearAndDestroy()
void G4TrajectoryContainer::clearAndDestroy () inline
Definition at line 72 of file G4TrajectoryContainer.hh.
Referenced by G4Event::~G4Event(), and ~G4TrajectoryContainer().
entries()
G4int G4TrajectoryContainer::entries () const inline
Definition at line 70 of file G4TrajectoryContainer.hh.
Referenced by G4TrajectoriesModel::DescribeYourselfTo(), G4Event::Draw(), DMXEventAction::drawTracks(), CexmcEventAction::DrawTrajectories(), ExGflashEventAction::EndOfEventAction(), B2EventAction::EndOfEventAction(), RE01EventAction::EndOfEventAction(), ExN02EventAction::EndOfEventAction(), LXeEventAction::EndOfEventAction(), ExP01EventAction::EndOfEventAction(), RE04EventAction::EndOfEventAction(), and RE02EventAction::EndOfEventAction().
GetVector()
TrajectoryVector* G4TrajectoryContainer::GetVector () const inline
Definition at line 78 of file G4TrajectoryContainer.hh.
insert()
G4bool G4TrajectoryContainer::insert (G4VTrajectory * p) inline
Definition at line 71 of file G4TrajectoryContainer.hh.
Referenced by G4EventManager::DoProcessing(), and ITTrackingInteractivity::EndTracking().
operator delete()
void G4TrajectoryContainer::operator delete (void * anEvent) inline
Definition at line 93 of file G4TrajectoryContainer.hh.
operator new()
void * G4TrajectoryContainer::operator new (size_t) inline
Definition at line 86 of file G4TrajectoryContainer.hh.
operator!=()
G4bool G4TrajectoryContainer::operator!= (const G4TrajectoryContainer & right) const
Definition at line 53 of file G4TrajectoryContainer.cc.
operator=()
G4TrajectoryContainer& G4TrajectoryContainer::operator= (const G4TrajectoryContainer &) private
operator==()
G4bool G4TrajectoryContainer::operator== (const G4TrajectoryContainer & right) const
Definition at line 48 of file G4TrajectoryContainer.cc.
operator[]()
G4VTrajectory* G4TrajectoryContainer::operator[] (size_t n) inline
Definition at line 77 of file G4TrajectoryContainer.hh.
push_back()
void G4TrajectoryContainer::push_back (G4VTrajectory * p) inline
Definition at line 69 of file G4TrajectoryContainer.hh.
Referenced by insert().
size()
size_t G4TrajectoryContainer::size () const inline
Definition at line 68 of file G4TrajectoryContainer.hh.
Referenced by clearAndDestroy(), and entries().
Field Documentation
vect
TrajectoryVector* G4TrajectoryContainer::vect private
Definition at line 81 of file G4TrajectoryContainer.hh.
Referenced by clearAndDestroy(), G4TrajectoryContainer(), GetVector(), operator[](), push_back(), size(), and ~G4TrajectoryContainer().
The documentation for this class was generated from the following files:
source/event/include/G4TrajectoryContainer.hh
source/event/src/G4TrajectoryContainer.cc