Geant4: G4VGraphicsScene Class Reference
G4VGraphicsScene Class Reference abstract
#include <G4VGraphicsScene.hh>
Public Member Functions
G4VGraphicsScene ()
virtual ~G4VGraphicsScene ()
virtual void PreAddSolid (const G4Transform3D &objectTransformation, const G4VisAttributes &visAttribs)=0
virtual void PostAddSolid ()=0
virtual void AddSolid (const G4Box &)=0
virtual void AddSolid (const G4Cons &)=0
virtual void AddSolid (const G4Orb &)=0
virtual void AddSolid (const G4Para &)=0
virtual void AddSolid (const G4Sphere &)=0
virtual void AddSolid (const G4Torus &)=0
virtual void AddSolid (const G4Trap &)=0
virtual void AddSolid (const G4Trd &)=0
virtual void AddSolid (const G4Tubs &)=0
virtual void AddSolid (const G4Ellipsoid &)=0
virtual void AddSolid (const G4Polycone &)=0
virtual void AddSolid (const G4Polyhedra &)=0
virtual void AddSolid (const G4VSolid &)=0
virtual void AddCompound (const G4VTrajectory &)=0
virtual void AddCompound (const G4VHit &)=0
virtual void AddCompound (const G4VDigi &)=0
virtual void AddCompound (const G4THitsMap< G4double > &)=0
virtual void AddCompound (const G4THitsMap< G4StatDouble > &)=0
virtual void BeginPrimitives (const G4Transform3D &objectTransformation=G4Transform3D())=0
virtual void EndPrimitives ()=0
virtual void BeginPrimitives2D (const G4Transform3D &objectTransformation=G4Transform3D())=0
virtual void EndPrimitives2D ()=0
virtual void AddPrimitive (const G4Polyline &)=0
virtual void AddPrimitive (const G4Scale &)=0
virtual void AddPrimitive (const G4Text &)=0
virtual void AddPrimitive (const G4Circle &)=0
virtual void AddPrimitive (const G4Square &)=0
virtual void AddPrimitive (const G4Polymarker &)=0
virtual void AddPrimitive (const G4Polyhedron &)=0
virtual const G4VisExtent & GetExtent () const
Detailed Description
Definition at line 72 of file G4VGraphicsScene.hh.
Constructor & Destructor Documentation
G4VGraphicsScene()
G4VGraphicsScene::G4VGraphicsScene ()
Definition at line 33 of file G4VGraphicsScene.cc.
~G4VGraphicsScene()
G4VGraphicsScene::~G4VGraphicsScene () virtual
Definition at line 35 of file G4VGraphicsScene.cc.
Member Function Documentation
AddCompound() [1/5]
virtual void G4VGraphicsScene::AddCompound (const G4THitsMap< G4double > &) pure virtual
Implemented in G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4HepRepFileSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4VSceneHandler, and G4PseudoScene.
AddCompound() [2/5]
virtual void G4VGraphicsScene::AddCompound (const G4THitsMap< G4StatDouble > &) pure virtual
Implemented in G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4HepRepFileSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4VSceneHandler, and G4PseudoScene.
AddCompound() [3/5]
virtual void G4VGraphicsScene::AddCompound (const G4VDigi &) pure virtual
Implemented in G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4HepRepFileSceneHandler, G4HepRepSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4VSceneHandler, and G4PseudoScene.
AddCompound() [4/5]
virtual void G4VGraphicsScene::AddCompound (const G4VHit &) pure virtual
Implemented in G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4VSceneHandler, G4HepRepFileSceneHandler, and G4PseudoScene.
AddCompound() [5/5]
virtual void G4VGraphicsScene::AddCompound (const G4VTrajectory &) pure virtual
Implemented in G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4VSceneHandler, G4HepRepSceneHandler, G4HepRepFileSceneHandler, and G4PseudoScene.
Referenced by G4PSHitsModel::DescribeYourselfTo(), G4HitsModel::DescribeYourselfTo(), G4DigiModel::DescribeYourselfTo(), and G4TrajectoriesModel::DescribeYourselfTo().
AddPrimitive() [1/7]
virtual void G4VGraphicsScene::AddPrimitive (const G4Circle &) pure virtual
Implemented in G4VSceneHandler, G4XXXSGSceneHandler, G4HepRepFileSceneHandler, G4HepRepSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4PseudoScene, G4GMocrenFileSceneHandler, G4VTreeSceneHandler, G4DAWNFILESceneHandler, G4RayTracerSceneHandler, and G4XXXSceneHandler.
AddPrimitive() [2/7]
virtual void G4VGraphicsScene::AddPrimitive (const G4Polyhedron &) pure virtual
Implemented in G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4VSceneHandler, G4XXXSGSceneHandler, G4HepRepFileSceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4XXXFileSceneHandler, G4PseudoScene, G4VTreeSceneHandler, G4RayTracerSceneHandler, and G4XXXSceneHandler.
AddPrimitive() [3/7]
virtual void G4VGraphicsScene::AddPrimitive (const G4Polyline &) pure virtual
Implemented in G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4VSceneHandler, G4XXXSGSceneHandler, G4HepRepFileSceneHandler, G4HepRepSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4PseudoScene, G4VTreeSceneHandler, G4RayTracerSceneHandler, and G4XXXSceneHandler.
Referenced by G4PhysicalVolumeModel::DescribeSolid(), G4ScaleModel::DescribeYourselfTo(), G4TextModel::DescribeYourselfTo(), G4GPSModel::DescribeYourselfTo(), G4MagneticFieldModel::DescribeYourselfTo(), G4ArrowModel::DescribeYourselfTo(), G4LogicalVolumeModel::DescribeYourselfTo(), CexmcScenePrimitives::DrawRadialLine(), CexmcScenePrimitives::HighlightInnerCrystals(), CexmcScenePrimitives::MarkTargetCenter(), G4VisCommandSceneAddArrow2D::Arrow2D::operator()(), G4VisCommandSceneAddDate::Date::operator()(), G4VisCommandSceneAddEventID::EventID::operator()(), G4VisCommandSceneAddFrame::Frame::operator()(), G4VisCommandSceneAddLine::Line::operator()(), G4VisCommandSceneAddLine2D::Line2D::operator()(), G4VisCommandSceneAddLogo::G4Logo::operator()(), G4VisCommandSceneAddLogo2D::Logo2D::operator()(), and G4VisCommandSceneAddText2D::G4Text2D::operator()().
AddPrimitive() [4/7]
virtual void G4VGraphicsScene::AddPrimitive (const G4Polymarker &) pure virtual
Implemented in G4XXXSGSceneHandler, G4XXXStoredSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4XXXFileSceneHandler, G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4XXXSceneHandler, G4VSceneHandler, G4HepRepFileSceneHandler, G4HepRepSceneHandler, G4PseudoScene, G4VTreeSceneHandler, and G4RayTracerSceneHandler.
AddPrimitive() [5/7]
virtual void G4VGraphicsScene::AddPrimitive (const G4Scale &) pure virtual
Implemented in G4XXXSGSceneHandler, G4HepRepFileSceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4XXXFileSceneHandler, G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4XXXSceneHandler, G4VSceneHandler, G4PseudoScene, G4VTreeSceneHandler, and G4RayTracerSceneHandler.
AddPrimitive() [6/7]
virtual void G4VGraphicsScene::AddPrimitive (const G4Square &) pure virtual
Implemented in G4VSceneHandler, G4XXXSGSceneHandler, G4HepRepFileSceneHandler, G4HepRepSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4PseudoScene, G4GMocrenFileSceneHandler, G4VTreeSceneHandler, G4DAWNFILESceneHandler, G4RayTracerSceneHandler, and G4XXXSceneHandler.
AddPrimitive() [7/7]
virtual void G4VGraphicsScene::AddPrimitive (const G4Text &) pure virtual
Implemented in G4VSceneHandler, G4XXXSGSceneHandler, G4HepRepFileSceneHandler, G4HepRepSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4PseudoScene, G4GMocrenFileSceneHandler, G4VTreeSceneHandler, G4DAWNFILESceneHandler, G4RayTracerSceneHandler, and G4XXXSceneHandler.
AddSolid() [1/13]
virtual void G4VGraphicsScene::AddSolid (const G4Box &) pure virtual
Implemented in G4PseudoScene, G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4VSceneHandler, G4XXXSGSceneHandler, G4HepRepFileSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4XXXStoredSceneHandler, and G4XXXFileSceneHandler.
Referenced by G4GPSModel::DescribeYourselfTo(), G4VCSGfaceted::DescribeYourselfTo(), G4EllipticalTube::DescribeYourselfTo(), G4VTwistedFaceted::DescribeYourselfTo(), G4UnionSolid::DescribeYourselfTo(), G4Ellipsoid::DescribeYourselfTo(), G4ScaledSolid::DescribeYourselfTo(), G4Box::DescribeYourselfTo(), G4IntersectionSolid::DescribeYourselfTo(), G4SubtractionSolid::DescribeYourselfTo(), G4Tet::DescribeYourselfTo(), G4Orb::DescribeYourselfTo(), G4ReflectedSolid::DescribeYourselfTo(), G4TwistedTubs::DescribeYourselfTo(), G4Paraboloid::DescribeYourselfTo(), G4Hype::DescribeYourselfTo(), G4CutTubs::DescribeYourselfTo(), G4MultiUnion::DescribeYourselfTo(), G4GenericTrap::DescribeYourselfTo(), G4EllipticalCone::DescribeYourselfTo(), G4Trd::DescribeYourselfTo(), G4DisplacedSolid::DescribeYourselfTo(), G4Para::DescribeYourselfTo(), G4Tubs::DescribeYourselfTo(), G4Torus::DescribeYourselfTo(), G4Cons::DescribeYourselfTo(), G4Sphere::DescribeYourselfTo(), G4TessellatedSolid::DescribeYourselfTo(), and G4Trap::DescribeYourselfTo().
AddSolid() [2/13]
virtual void G4VGraphicsScene::AddSolid (const G4Cons &) pure virtual
Implemented in G4PseudoScene, G4GMocrenFileSceneHandler, G4XXXSGSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4VSceneHandler, G4HepRepFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
AddSolid() [3/13]
virtual void G4VGraphicsScene::AddSolid (const G4Ellipsoid &) pure virtual
Implemented in G4PseudoScene, G4GMocrenFileSceneHandler, G4XXXSGSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4VSceneHandler, and G4HepRepFileSceneHandler.
AddSolid() [4/13]
virtual void G4VGraphicsScene::AddSolid (const G4Orb &) pure virtual
Implemented in G4PseudoScene, G4GMocrenFileSceneHandler, G4XXXSGSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4VSceneHandler, and G4HepRepFileSceneHandler.
AddSolid() [5/13]
virtual void G4VGraphicsScene::AddSolid (const G4Para &) pure virtual
Implemented in G4PseudoScene, G4GMocrenFileSceneHandler, G4XXXSGSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4VSceneHandler, G4HepRepFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
AddSolid() [6/13]
virtual void G4VGraphicsScene::AddSolid (const G4Polycone &) pure virtual
Implemented in G4PseudoScene, G4XXXSGSceneHandler, G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4VSceneHandler, and G4HepRepFileSceneHandler.
AddSolid() [7/13]
virtual void G4VGraphicsScene::AddSolid (const G4Polyhedra &) pure virtual
Implemented in G4PseudoScene, G4GMocrenFileSceneHandler, G4XXXSGSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4VSceneHandler, and G4HepRepFileSceneHandler.
AddSolid() [8/13]
virtual void G4VGraphicsScene::AddSolid (const G4Sphere &) pure virtual
Implemented in G4GMocrenFileSceneHandler, G4XXXSGSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4PseudoScene, G4VSceneHandler, G4HepRepFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
AddSolid() [9/13]
virtual void G4VGraphicsScene::AddSolid (const G4Torus &) pure virtual
Implemented in G4GMocrenFileSceneHandler, G4XXXSGSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4PseudoScene, G4VSceneHandler, G4HepRepFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
AddSolid() [10/13]
virtual void G4VGraphicsScene::AddSolid (const G4Trap &) pure virtual
Implemented in G4GMocrenFileSceneHandler, G4XXXSGSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4PseudoScene, G4VSceneHandler, G4HepRepFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
AddSolid() [11/13]
virtual void G4VGraphicsScene::AddSolid (const G4Trd &) pure virtual
Implemented in G4GMocrenFileSceneHandler, G4XXXSGSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4PseudoScene, G4VSceneHandler, G4HepRepFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
AddSolid() [12/13]
virtual void G4VGraphicsScene::AddSolid (const G4Tubs &) pure virtual
Implemented in G4GMocrenFileSceneHandler, G4XXXSGSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4PseudoScene, G4VSceneHandler, G4HepRepFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
AddSolid() [13/13]
virtual void G4VGraphicsScene::AddSolid (const G4VSolid &) pure virtual
Implemented in G4GMocrenFileSceneHandler, G4XXXSGSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4PseudoScene, G4VSceneHandler, G4HepRepFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
BeginPrimitives()
virtual void G4VGraphicsScene::BeginPrimitives (const G4Transform3D & objectTransformation = G4Transform3D()) pure virtual
Implemented in G4VSceneHandler, G4XXXSGSceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, and G4PseudoScene.
Referenced by G4PhysicalVolumeModel::DescribeSolid(), G4ScaleModel::DescribeYourselfTo(), G4TextModel::DescribeYourselfTo(), G4GPSModel::DescribeYourselfTo(), G4MagneticFieldModel::DescribeYourselfTo(), G4ArrowModel::DescribeYourselfTo(), G4LogicalVolumeModel::DescribeYourselfTo(), CexmcScenePrimitives::DrawRadialLine(), CexmcScenePrimitives::HighlightInnerCrystals(), CexmcScenePrimitives::MarkTargetCenter(), G4VisCommandSceneAddLine::Line::operator()(), and G4VisCommandSceneAddLogo::G4Logo::operator()().
BeginPrimitives2D()
virtual void G4VGraphicsScene::BeginPrimitives2D (const G4Transform3D & objectTransformation = G4Transform3D()) pure virtual
Implemented in G4VSceneHandler, G4HepRepFileSceneHandler, and G4PseudoScene.
Referenced by G4VisCommandSceneAddArrow2D::Arrow2D::operator()(), G4VisCommandSceneAddDate::Date::operator()(), G4VisCommandSceneAddEventID::EventID::operator()(), G4VisCommandSceneAddFrame::Frame::operator()(), G4VisCommandSceneAddLine2D::Line2D::operator()(), G4VisCommandSceneAddLogo2D::Logo2D::operator()(), and G4VisCommandSceneAddText2D::G4Text2D::operator()().
EndPrimitives()
virtual void G4VGraphicsScene::EndPrimitives () pure virtual
Implemented in G4VSceneHandler, G4XXXSGSceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4GMocrenFileSceneHandler, G4PseudoScene, and G4DAWNFILESceneHandler.
Referenced by G4PhysicalVolumeModel::DescribeSolid(), G4ScaleModel::DescribeYourselfTo(), G4TextModel::DescribeYourselfTo(), G4GPSModel::DescribeYourselfTo(), G4MagneticFieldModel::DescribeYourselfTo(), G4ArrowModel::DescribeYourselfTo(), G4LogicalVolumeModel::DescribeYourselfTo(), CexmcScenePrimitives::DrawRadialLine(), CexmcScenePrimitives::HighlightInnerCrystals(), CexmcScenePrimitives::MarkTargetCenter(), G4VisCommandSceneAddLine::Line::operator()(), and G4VisCommandSceneAddLogo::G4Logo::operator()().
EndPrimitives2D()
virtual void G4VGraphicsScene::EndPrimitives2D () pure virtual
Implemented in G4VSceneHandler, G4HepRepFileSceneHandler, and G4PseudoScene.
Referenced by G4VisCommandSceneAddArrow2D::Arrow2D::operator()(), G4VisCommandSceneAddDate::Date::operator()(), G4VisCommandSceneAddEventID::EventID::operator()(), G4VisCommandSceneAddFrame::Frame::operator()(), G4VisCommandSceneAddLine2D::Line2D::operator()(), G4VisCommandSceneAddLogo2D::Logo2D::operator()(), and G4VisCommandSceneAddText2D::G4Text2D::operator()().
GetExtent()
const G4VisExtent & G4VGraphicsScene::GetExtent () const virtual
Reimplemented in G4VSceneHandler.
Definition at line 37 of file G4VGraphicsScene.cc.
Referenced by G4MagneticFieldModel::DescribeYourselfTo().
PostAddSolid()
virtual void G4VGraphicsScene::PostAddSolid () pure virtual
Implemented in G4XXXSGSceneHandler, G4VSceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4PseudoScene, and G4VTreeSceneHandler.
Referenced by G4LogicalVolumeModel::DescribeSolid(), G4PhysicalVolumeModel::DescribeSolid(), and G4GPSModel::DescribeYourselfTo().
PreAddSolid()
virtual void G4VGraphicsScene::PreAddSolid (const G4Transform3D & objectTransformation, const G4VisAttributes & visAttribs) pure virtual
Implemented in G4HepRepSceneHandler, G4XXXSGSceneHandler, G4VSceneHandler, G4XXXStoredSceneHandler, G4PseudoScene, and G4VTreeSceneHandler.
Referenced by G4LogicalVolumeModel::DescribeSolid(), G4PhysicalVolumeModel::DescribeSolid(), and G4GPSModel::DescribeYourselfTo().
The documentation for this class was generated from the following files:
source/graphics_reps/include/G4VGraphicsScene.hh
source/graphics_reps/src/G4VGraphicsScene.cc