Geant4: G4LatticePhysical Class Reference
G4LatticePhysical Class Reference
#include <G4LatticePhysical.hh>
Public Member Functions
G4LatticePhysical (const G4LatticeLogical *Lat=0, const G4RotationMatrix *Rot=0)
virtual ~G4LatticePhysical ()
void SetVerboseLevel (G4int vb)
G4double MapKtoV (G4int, G4ThreeVector) const
G4ThreeVector MapKtoVDir (G4int, G4ThreeVector) const
void SetLatticeLogical (const G4LatticeLogical *Lat)
void SetPhysicalOrientation (const G4RotationMatrix *Rot)
void SetLatticeOrientation (G4double, G4double)
void SetMillerOrientation (G4int, G4int, G4int)
const G4LatticeLogical * GetLattice () const
G4double GetScatteringConstant () const
G4double GetAnhDecConstant () const
G4double GetLDOS () const
G4double GetSTDOS () const
G4double GetFTDOS () const
G4double GetBeta () const
G4double GetGamma () const
G4double GetLambda () const
G4double GetMu () const
G4ThreeVector RotateToGlobal (const G4ThreeVector &dir) const
G4ThreeVector RotateToLocal (const G4ThreeVector &dir) const
Private Attributes
G4int verboseLevel
G4double fTheta
G4double fPhi
const G4LatticeLogical * fLattice
G4RotationMatrix fLocalToGlobal
G4RotationMatrix fGlobalToLocal
Detailed Description
Definition at line 41 of file G4LatticePhysical.hh.
Constructor & Destructor Documentation
G4LatticePhysical()
G4LatticePhysical::G4LatticePhysical (const G4LatticeLogical * Lat = 0, const G4RotationMatrix * Rot = 0)
Definition at line 49 of file G4LatticePhysical.cc.
~G4LatticePhysical()
G4LatticePhysical::~G4LatticePhysical () virtual
Definition at line 55 of file G4LatticePhysical.cc.
Member Function Documentation
GetAnhDecConstant()
G4double G4LatticePhysical::GetAnhDecConstant () const inline
Definition at line 62 of file G4LatticePhysical.hh.
Referenced by G4PhononDownconversion::GetMeanFreePath().
GetBeta()
G4double G4LatticePhysical::GetBeta () const inline
Definition at line 66 of file G4LatticePhysical.hh.
Referenced by G4PhononDownconversion::PostStepDoIt().
GetFTDOS()
G4double G4LatticePhysical::GetFTDOS () const inline
Definition at line 65 of file G4LatticePhysical.hh.
Referenced by G4PhononDownconversion::MakeLTSecondaries(), G4PhononDownconversion::MakeTTSecondaries(), and G4PhononScattering::PostStepDoIt().
GetGamma()
G4double G4LatticePhysical::GetGamma () const inline
Definition at line 67 of file G4LatticePhysical.hh.
Referenced by G4PhononDownconversion::PostStepDoIt().
GetLambda()
G4double G4LatticePhysical::GetLambda () const inline
Definition at line 68 of file G4LatticePhysical.hh.
Referenced by G4PhononDownconversion::PostStepDoIt().
GetLattice()
const G4LatticeLogical* G4LatticePhysical::GetLattice () const inline
Definition at line 59 of file G4LatticePhysical.hh.
GetLDOS()
G4double G4LatticePhysical::GetLDOS () const inline
Definition at line 63 of file G4LatticePhysical.hh.
Referenced by G4PhononScattering::PostStepDoIt().
GetMu()
G4double G4LatticePhysical::GetMu () const inline
Definition at line 69 of file G4LatticePhysical.hh.
Referenced by G4PhononDownconversion::PostStepDoIt().
GetScatteringConstant()
G4double G4LatticePhysical::GetScatteringConstant () const inline
Definition at line 61 of file G4LatticePhysical.hh.
Referenced by G4PhononScattering::GetMeanFreePath().
GetSTDOS()
G4double G4LatticePhysical::GetSTDOS () const inline
Definition at line 64 of file G4LatticePhysical.hh.
Referenced by G4PhononDownconversion::MakeLTSecondaries(), G4PhononDownconversion::MakeTTSecondaries(), and G4PhononScattering::PostStepDoIt().
MapKtoV()
G4double G4LatticePhysical::MapKtoV (G4int polarizationState, G4ThreeVector k) const
Definition at line 104 of file G4LatticePhysical.cc.
Referenced by G4VPhononProcess::CreateSecondary(), G4LatticeManager::MapKtoV(), and G4PhononReflection::PostStepDoIt().
MapKtoVDir()
G4ThreeVector G4LatticePhysical::MapKtoVDir (G4int polarizationState, G4ThreeVector k) const
Definition at line 115 of file G4LatticePhysical.cc.
Referenced by G4VPhononProcess::CreateSecondary(), and G4LatticeManager::MapKtoVDir().
RotateToGlobal()
G4ThreeVector G4LatticePhysical::RotateToGlobal (const G4ThreeVector & dir) const
Definition at line 131 of file G4LatticePhysical.cc.
Referenced by G4VPhononProcess::CreateSecondary().
RotateToLocal()
G4ThreeVector G4LatticePhysical::RotateToLocal (const G4ThreeVector & dir) const
Definition at line 145 of file G4LatticePhysical.cc.
SetLatticeLogical()
void G4LatticePhysical::SetLatticeLogical (const G4LatticeLogical * Lat) inline
Definition at line 53 of file G4LatticePhysical.hh.
SetLatticeOrientation()
void G4LatticePhysical::SetLatticeOrientation (G4double t_rot, G4double p_rot)
Definition at line 78 of file G4LatticePhysical.cc.
SetMillerOrientation()
void G4LatticePhysical::SetMillerOrientation (G4int l, G4int k, G4int n)
Definition at line 89 of file G4LatticePhysical.cc.
SetPhysicalOrientation()
void G4LatticePhysical::SetPhysicalOrientation (const G4RotationMatrix * Rot)
Definition at line 60 of file G4LatticePhysical.cc.
Referenced by G4LatticePhysical().
SetVerboseLevel()
void G4LatticePhysical::SetVerboseLevel (G4int vb) inline
Definition at line 47 of file G4LatticePhysical.hh.
Field Documentation
fGlobalToLocal
G4RotationMatrix G4LatticePhysical::fGlobalToLocal private
Definition at line 82 of file G4LatticePhysical.hh.
Referenced by RotateToLocal(), and SetPhysicalOrientation().
fLattice
const G4LatticeLogical* G4LatticePhysical::fLattice private
Definition at line 79 of file G4LatticePhysical.hh.
Referenced by GetAnhDecConstant(), GetBeta(), GetFTDOS(), GetGamma(), GetLambda(), GetLattice(), GetLDOS(), GetMu(), GetScatteringConstant(), GetSTDOS(), MapKtoV(), MapKtoVDir(), and SetLatticeLogical().
fLocalToGlobal
G4RotationMatrix G4LatticePhysical::fLocalToGlobal private
Definition at line 81 of file G4LatticePhysical.hh.
Referenced by RotateToGlobal(), and SetPhysicalOrientation().
fPhi
G4double G4LatticePhysical::fPhi private
Definition at line 78 of file G4LatticePhysical.hh.
Referenced by MapKtoV(), MapKtoVDir(), SetLatticeOrientation(), and SetMillerOrientation().
fTheta
G4double G4LatticePhysical::fTheta private
Definition at line 78 of file G4LatticePhysical.hh.
Referenced by MapKtoV(), MapKtoVDir(), SetLatticeOrientation(), and SetMillerOrientation().
verboseLevel
G4int G4LatticePhysical::verboseLevel private
Definition at line 76 of file G4LatticePhysical.hh.
Referenced by MapKtoV(), MapKtoVDir(), RotateToGlobal(), RotateToLocal(), SetLatticeOrientation(), SetMillerOrientation(), SetPhysicalOrientation(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
source/materials/include/G4LatticePhysical.hh
source/materials/src/G4LatticePhysical.cc