Geant4: Par02EventInformation Class Reference
Par02EventInformation Class Reference
Event information.
#include <Par02EventInformation.hh>
Public Member Functions
Par02EventInformation ()
A default constructor. Sets flag fDoSmearing to true.
Par02EventInformation (G4bool aSmear)
A constructor.
virtual ~Par02EventInformation ()
virtual void Print () const
Prints event information.
void SetDoSmearing (G4bool aSmear)
Sets the flag indicating if smearing should be done.
G4bool GetDoSmearing ()
Gets the flag indicating if smearing should be done.
Public Member Functions inherited from G4VUserEventInformation
G4VUserEventInformation ()
virtual ~G4VUserEventInformation ()
Private Attributes
G4bool fDoSmearing
A flag indicating if smearing should be performed.
Detailed Description
Event information.
Describes the information that can be associated with a G4Event class object.
Author
Anna Zaborowska
Definition at line 41 of file Par02EventInformation.hh.
Constructor & Destructor Documentation
Par02EventInformation() [1/2]
Par02EventInformation::Par02EventInformation ()
A default constructor. Sets flag fDoSmearing to true.
Definition at line 34 of file Par02EventInformation.cc.
Par02EventInformation() [2/2]
Par02EventInformation::Par02EventInformation (G4bool aSmear)
A constructor.
Parameters
aSmear The flag indicating if smearing should be done.
Definition at line 38 of file Par02EventInformation.cc.
~Par02EventInformation()
Par02EventInformation::~Par02EventInformation () virtual
Definition at line 42 of file Par02EventInformation.cc.
Member Function Documentation
GetDoSmearing()
G4bool Par02EventInformation::GetDoSmearing ()
Gets the flag indicating if smearing should be done.
Definition at line 52 of file Par02EventInformation.cc.
Referenced by Par02FastSimModelEMCal::DoIt(), Par02FastSimModelHCal::DoIt(), and Par02FastSimModelTracker::DoIt().
Print()
void Par02EventInformation::Print (void) const virtual
Prints event information.
Implements G4VUserEventInformation.
Definition at line 58 of file Par02EventInformation.cc.
SetDoSmearing()
void Par02EventInformation::SetDoSmearing (G4bool aSmear)
Sets the flag indicating if smearing should be done.
Parameters
aSmear A boolean flag.
Definition at line 46 of file Par02EventInformation.cc.
Field Documentation
fDoSmearing
G4bool Par02EventInformation::fDoSmearing private
A flag indicating if smearing should be performed.
It is read by implementations of G4VFastSimulationModel.
Definition at line 67 of file Par02EventInformation.hh.
Referenced by GetDoSmearing(), Print(), and SetDoSmearing().
The documentation for this class was generated from the following files:
examples/extended/parameterisations/Par02/include/Par02EventInformation.hh
examples/extended/parameterisations/Par02/src/Par02EventInformation.cc