Geant4: CCaloOrganization Class Reference
CCaloOrganization Class Reference
#include <CCaloOrganization.hh>
Public Member Functions
CCaloOrganization ()
virtual ~CCaloOrganization ()
unsigned int packindex (int det, int z, int eta, int phi) const
unsigned int packindex (int det, int depth, int z, int eta, int phi) const
void unpackindex (const unsigned int &idx, int &det, int &z, int &eta, int &phi) const
void unpackindex (const unsigned int &idx, int &det, int &depth, int &z, int &eta, int &phi) const
int getUnitWithMaxEnergy (std::map< int, float, std::less< int > > &themap)
float energyInMatrix (int nCellInEta, int nCellInPhi, int crystalWithMaxEnergy, std::map< int, float, std::less< int > > &themap)
Detailed Description
Definition at line 38 of file CCaloOrganization.hh.
Constructor & Destructor Documentation
CCaloOrganization()
CCaloOrganization::CCaloOrganization () inline
Definition at line 41 of file CCaloOrganization.hh.
~CCaloOrganization()
virtual CCaloOrganization::~CCaloOrganization () inline virtual
Definition at line 42 of file CCaloOrganization.hh.
Member Function Documentation
energyInMatrix()
float CCaloOrganization::energyInMatrix (int nCellInEta, int nCellInPhi, int crystalWithMaxEnergy, std::map< int, float, std::less< int > > & themap)
Definition at line 121 of file CCaloOrganization.cc.
getUnitWithMaxEnergy()
int CCaloOrganization::getUnitWithMaxEnergy (std::map< int, float, std::less< int > > & themap)
Definition at line 94 of file CCaloOrganization.cc.
packindex() [1/2]
unsigned int CCaloOrganization::packindex (int det, int depth, int z, int eta, int phi) const
Definition at line 53 of file CCaloOrganization.cc.
packindex() [2/2]
unsigned int CCaloOrganization::packindex (int det, int z, int eta, int phi) const
Definition at line 35 of file CCaloOrganization.cc.
Referenced by energyInMatrix().
unpackindex() [1/2]
void CCaloOrganization::unpackindex (const unsigned int & idx, int & det, int & depth, int & z, int & eta, int & phi) const
Definition at line 83 of file CCaloOrganization.cc.
unpackindex() [2/2]
void CCaloOrganization::unpackindex (const unsigned int & idx, int & det, int & z, int & eta, int & phi) const
Definition at line 73 of file CCaloOrganization.cc.
Referenced by energyInMatrix(), and getUnitWithMaxEnergy().
The documentation for this class was generated from the following files:
examples/advanced/composite_calorimeter/include/CCaloOrganization.hh
examples/advanced/composite_calorimeter/src/CCaloOrganization.cc