Geant4: G4ParticleHPThermalBoost Class Reference
G4ParticleHPThermalBoost Class Reference
#include <G4ParticleHPThermalBoost.hh>
Public Member Functions
G4double GetThermalEnergy (const G4HadProjectile &aP, const G4Element *anE, G4double aT)
G4double GetThermalEnergy (const G4HadProjectile &aP, G4double theA, G4double theZ, G4double aT)
Detailed Description
Definition at line 42 of file G4ParticleHPThermalBoost.hh.
Member Function Documentation
GetThermalEnergy() [1/2]
G4double G4ParticleHPThermalBoost::GetThermalEnergy (const G4HadProjectile & aP, const G4Element * anE, G4double aT) inline
Definition at line 45 of file G4ParticleHPThermalBoost.hh.
Referenced by G4ParticleHPElastic::ApplyYourself(), G4ParticleHPCapture::ApplyYourself(), G4ParticleHPChannelList::ApplyYourself(), G4ParticleHPFission::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4FissLib::ApplyYourself(), and G4ParticleHPChannel::ApplyYourself().
GetThermalEnergy() [2/2]
G4double G4ParticleHPThermalBoost::GetThermalEnergy (const G4HadProjectile & aP, G4double theA, G4double theZ, G4double aT) inline
Definition at line 54 of file G4ParticleHPThermalBoost.hh.
The documentation for this class was generated from the following file:
source/processes/hadronic/models/particle_hp/include/G4ParticleHPThermalBoost.hh