Geant4: G4GenericMuonicAtom Class Reference
G4GenericMuonicAtom Class Reference
#include <G4GenericMuonicAtom.hh>
Static Public Member Functions
static G4GenericMuonicAtom * Definition ()
static G4GenericMuonicAtom * GenericMuonicAtomDefinition ()
static G4GenericMuonicAtom * GenericMuonicAtom ()
Static Public Member Functions inherited from G4Ions
static G4Ions::G4FloatLevelBase FloatLevelBase (char flbChar)
static G4Ions::G4FloatLevelBase FloatLevelBase (G4int flbIdx)
static char FloatLevelBaseChar (G4Ions::G4FloatLevelBase flb)
Static Public Member Functions inherited from G4ParticleDefinition
static const G4PDefManager & GetSubInstanceManager ()
static void Clean ()
Private Member Functions
G4GenericMuonicAtom ()
~G4GenericMuonicAtom ()
Static Private Attributes
static G4GenericMuonicAtom * theInstance = nullptr
Additional Inherited Members
Public Types inherited from G4Ions
enum G4FloatLevelBase {
G4FloatLevelBase::no_Float =0, G4FloatLevelBase::plus_X, G4FloatLevelBase::plus_Y, G4FloatLevelBase::plus_Z,
G4FloatLevelBase::plus_U, G4FloatLevelBase::plus_V, G4FloatLevelBase::plus_W, G4FloatLevelBase::plus_R,
G4FloatLevelBase::plus_S, G4FloatLevelBase::plus_T, G4FloatLevelBase::plus_A, G4FloatLevelBase::plus_B,
G4FloatLevelBase::plus_C, G4FloatLevelBase::plus_D, G4FloatLevelBase::plus_E
}
Public Member Functions inherited from G4MuonicAtom
G4MuonicAtom (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospin3, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifeTime, G4DecayTable *decaytable, G4bool shortlived, const G4String &subType, G4Ions const *baseion, G4int anti_encoding=0, G4double excitation=0.0, G4int isomer=0, G4double DIOLifeTime=-1.0, G4double NCLifeTime=-1.0)
virtual ~G4MuonicAtom ()
G4MuonicAtom * MuonicAtomDefinition ()
G4MuonicAtom * MuonicAtom ()
G4Ions const * GetBaseIon () const
G4double GetDIOLifeTime () const
void SetDIOLifeTime (G4double lt)
G4double GetNCLifeTime () const
void SetNCLifeTime (G4double lt)
Public Member Functions inherited from G4Ions
G4Ions (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospin3, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable, G4bool shortlived, const G4String &subType="", G4int anti_encoding=0, G4double excitation=0.0, G4int isomer=0)
virtual ~G4Ions ()
G4Ions * IonsDefinition ()
G4Ions * Ions ()
G4double GetExcitationEnergy () const
G4int GetIsomerLevel () const
G4Ions::G4FloatLevelBase GetFloatLevelBase () const
G4int GetFloatLevelBaseIndex () const
void SetFloatLevelBase (G4Ions::G4FloatLevelBase flb)
void SetFloatLevelBase (char flbChar)
void SetFloatLevelBase (G4int flbIdx)
Public Member Functions inherited from G4ParticleDefinition
G4ParticleDefinition (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospinZ, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable, G4bool shortlived=false, const G4String &subType="", G4int anti_encoding=0, G4double magneticMoment=0.0)
virtual ~G4ParticleDefinition ()
const G4String & GetParticleName () const
G4double GetPDGMass () const
G4double GetPDGWidth () const
G4double GetPDGCharge () const
G4double GetPDGSpin () const
G4int GetPDGiSpin () const
G4int GetPDGiParity () const
G4int GetPDGiConjugation () const
G4double GetPDGIsospin () const
G4double GetPDGIsospin3 () const
G4int GetPDGiIsospin () const
G4int GetPDGiIsospin3 () const
G4int GetPDGiGParity () const
G4double GetPDGMagneticMoment () const
void SetPDGMagneticMoment (G4double mageticMoment)
G4double CalculateAnomaly () const
const G4String & GetParticleType () const
const G4String & GetParticleSubType () const
G4int GetLeptonNumber () const
G4int GetBaryonNumber () const
G4int GetPDGEncoding () const
G4int GetAntiPDGEncoding () const
void SetAntiPDGEncoding (G4int aEncoding)
G4int GetQuarkContent (G4int flavor) const
G4int GetAntiQuarkContent (G4int flavor) const
G4bool IsShortLived () const
G4bool GetPDGStable () const
void SetPDGStable (const G4bool aFlag)
G4double GetPDGLifeTime () const
void SetPDGLifeTime (G4double aLifeTime)
G4double GetIonLifeTime () const
G4DecayTable * GetDecayTable () const
void SetDecayTable (G4DecayTable *aDecayTable)
G4ProcessManager * GetProcessManager () const
void SetProcessManager (G4ProcessManager *aProcessManager)
G4ParticleTable * GetParticleTable () const
G4int GetAtomicNumber () const
G4int GetAtomicMass () const
void DumpTable () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetApplyCutsFlag (G4bool)
G4bool GetApplyCutsFlag () const
G4bool IsGeneralIon () const
G4bool IsMuonicAtom () const
G4bool operator== (const G4ParticleDefinition &right) const
G4bool operator!= (const G4ParticleDefinition &right) const
G4ProcessManager * GetMasterProcessManager () const
void SetMasterProcessManager (G4ProcessManager *aNewPM)
G4int GetInstanceID () const
void SetParticleDefinitionID (G4int id=-1)
G4int GetParticleDefinitionID () const
Protected Types inherited from G4ParticleDefinition
enum { NumberOfQuarkFlavor = 6 }
Protected Member Functions inherited from G4MuonicAtom
G4MuonicAtom ()
Protected Member Functions inherited from G4Ions
G4Ions ()
Protected Member Functions inherited from G4ParticleDefinition
G4int FillQuarkContents ()
void SetParticleSubType (const G4String &subtype)
void SetAtomicNumber (G4int)
void SetAtomicMass (G4int)
G4ParticleDefinition (const G4ParticleDefinition &right)
G4ParticleDefinition ()
Protected Attributes inherited from G4ParticleDefinition
G4int theQuarkContent [NumberOfQuarkFlavor]
G4int theAntiQuarkContent [NumberOfQuarkFlavor]
G4bool isGeneralIon
G4bool isMuonicAtom
Detailed Description
Definition at line 53 of file G4GenericMuonicAtom.hh.
Constructor & Destructor Documentation
G4GenericMuonicAtom()
G4GenericMuonicAtom::G4GenericMuonicAtom () inline private
Definition at line 57 of file G4GenericMuonicAtom.hh.
~G4GenericMuonicAtom()
G4GenericMuonicAtom::~G4GenericMuonicAtom () inline private
Definition at line 58 of file G4GenericMuonicAtom.hh.
Member Function Documentation
Definition()
G4GenericMuonicAtom * G4GenericMuonicAtom::Definition () static
!!! !!! this particle should not be used for tracking !!! all properties except the name and type are meaningless !!!
Definition at line 47 of file G4GenericMuonicAtom.cc.
Referenced by GenericMuonicAtom(), and GenericMuonicAtomDefinition().
GenericMuonicAtom()
G4GenericMuonicAtom * G4GenericMuonicAtom::GenericMuonicAtom () static
Definition at line 103 of file G4GenericMuonicAtom.cc.
Referenced by G4MuonicAtomDecayPhysics::ConstructParticle(), and G4MuonicAtomDecayPhysics::ConstructProcess().
GenericMuonicAtomDefinition()
G4GenericMuonicAtom * G4GenericMuonicAtom::GenericMuonicAtomDefinition () static
Definition at line 98 of file G4GenericMuonicAtom.cc.
Field Documentation
theInstance
G4GenericMuonicAtom * G4GenericMuonicAtom::theInstance = nullptr static private
Definition at line 56 of file G4GenericMuonicAtom.hh.
Referenced by Definition().
The documentation for this class was generated from the following files:
source/particles/hadrons/ions/include/G4GenericMuonicAtom.hh
source/particles/hadrons/ions/src/G4GenericMuonicAtom.cc