Geant4: G4Nucleon Class Reference
G4Nucleon Class Reference
#include <G4Nucleon.hh>
Public Member Functions
G4Nucleon ()
~G4Nucleon ()
int operator== (const G4Nucleon &right) const
int operator!= (const G4Nucleon &right) const
G4Nucleon & operator= (const G4Nucleon &right)
void SetPosition (const G4ThreeVector aPosition)
const G4ThreeVector & GetPosition () const
void SetMomentum (G4LorentzVector &aMomentum)
const G4LorentzVector & GetMomentum () const
virtual const G4LorentzVector & Get4Momentum () const
void SetBindingEnergy (G4double anEnergy)
G4double GetBindingEnergy () const
void SetParticleType (G4Proton *aProton)
void SetParticleType (G4Neutron *aNeutron)
void SetParticleType (G4AntiProton *aAntiProton)
void SetParticleType (G4AntiNeutron *aAntiNeutron)
const G4ParticleDefinition * GetParticleType () const
virtual const G4ParticleDefinition * GetDefinition () const
void Boost (const G4ThreeVector &beta)
void Boost (const G4LorentzVector &aMomentum)
void Hit (G4VSplitableHadron *aHit)
void Hit (G4int)
G4VSplitableHadron * GetSplitableHadron () const
G4bool AreYouHit () const
Public Member Functions inherited from G4VKineticNucleon
G4VKineticNucleon ()
G4VKineticNucleon (const G4VKineticNucleon &right)
virtual ~G4VKineticNucleon ()
const G4VKineticNucleon & operator= (const G4VKineticNucleon &right)
int operator== (const G4VKineticNucleon &right) const
int operator!= (const G4VKineticNucleon &right) const
virtual G4KineticTrackVector * Decay ()
Private Attributes
G4ThreeVector thePosition
G4LorentzVector theMomentum
G4double theBindingE
const G4ParticleDefinition * theParticleType
G4VSplitableHadron * theSplitableHadron
Detailed Description
Definition at line 54 of file G4Nucleon.hh.
Constructor & Destructor Documentation
G4Nucleon()
G4Nucleon::G4Nucleon ()
Definition at line 38 of file G4Nucleon.cc.
~G4Nucleon()
G4Nucleon::~G4Nucleon ()
Definition at line 42 of file G4Nucleon.cc.
Member Function Documentation
AreYouHit()
G4bool G4Nucleon::AreYouHit () const inline
Definition at line 96 of file G4Nucleon.hh.
Referenced by G4QGSParticipants::ComputeNucleusProperties(), G4FTFModel::ComputeNucleusProperties(), G4InuclNuclei::copy(), G4IntraNucleiCascader::copyWoundedNucleus(), G4FTFParticipants::GetList(), G4BinaryLightIonReaction::GetProjectileExcitation(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), G4KineticTrack::IsParticipant(), G4QGSParticipants::PrepareInitialState(), G4GeneratorPrecompoundInterface::Propagate(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4QGSParticipants::ReggeonCascade(), G4FTFModel::ReggeonCascade(), G4VPartonStringModel::Scatter(), G4QGSParticipants::StoreInvolvedNucleon(), and G4FTFModel::StoreInvolvedNucleon().
Boost() [1/2]
void G4Nucleon::Boost (const G4LorentzVector & aMomentum)
Definition at line 46 of file G4Nucleon.cc.
Boost() [2/2]
void G4Nucleon::Boost (const G4ThreeVector & beta) inline
Definition at line 86 of file G4Nucleon.hh.
Get4Momentum()
virtual const G4LorentzVector& G4Nucleon::Get4Momentum () const inline virtual
Implements G4VKineticNucleon.
Definition at line 72 of file G4Nucleon.hh.
Referenced by G4QGSParticipants::BuildInteractions(), G4QGSParticipants::CheckKinematics(), G4FTFModel::CheckKinematics(), G4QGSParticipants::ComputeNucleusProperties(), G4FTFModel::ComputeNucleusProperties(), G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), G4FTFParticipants::GetList(), G4QGSParticipants::GetList(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), G4QGSParticipants::PrepareInitialState(), G4GeneratorPrecompoundInterface::Propagate(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4QGSParticipants::SamplingNucleonKinematics(), G4FTFModel::SamplingNucleonKinematics(), and G4VPartonStringModel::Scatter().
GetBindingEnergy()
G4double G4Nucleon::GetBindingEnergy () const inline
Definition at line 75 of file G4Nucleon.hh.
Referenced by G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), and G4VPartonStringModel::Scatter().
GetDefinition()
virtual const G4ParticleDefinition* G4Nucleon::GetDefinition () const inline virtual
Implements G4VKineticNucleon.
Definition at line 84 of file G4Nucleon.hh.
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4QGSParticipants::ComputeNucleusProperties(), G4FTFModel::ComputeNucleusProperties(), G4QGSParticipants::FinalizeKinematics(), G4QGSParticipants::GetList(), G4BinaryLightIonReaction::GetProjectileExcitation(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), G4FTFModel::Init(), G4BinaryLightIonReaction::Interact(), G4GeneratorPrecompoundInterface::Propagate(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4QGSParticipants::ReggeonCascade(), and G4VPartonStringModel::Scatter().
GetMomentum()
const G4LorentzVector& G4Nucleon::GetMomentum (void) const inline
Definition at line 71 of file G4Nucleon.hh.
Referenced by G4VSplitableHadron::G4VSplitableHadron(), G4BinaryLightIonReaction::GetProjectileExcitation(), and G4BinaryLightIonReaction::Interact().
GetParticleType()
const G4ParticleDefinition* G4Nucleon::GetParticleType () const inline
Definition at line 83 of file G4Nucleon.hh.
Referenced by G4LowEIonFragmentation::ApplyYourself(), G4InuclNuclei::copy(), G4IntraNucleiCascader::copyWoundedNucleus(), and G4VSplitableHadron::G4VSplitableHadron().
GetPosition()
const G4ThreeVector & G4Nucleon::GetPosition (void) const inline virtual
Implements G4VKineticNucleon.
Definition at line 138 of file G4Nucleon.hh.
Referenced by G4LowEIonFragmentation::ApplyYourself(), G4IntraNucleiCascader::copyWoundedNucleus(), G4Fancy3DNucleusHelperForSortInZ(), G4VSplitableHadron::G4VSplitableHadron(), G4FTFParticipants::GetList(), G4QGSParticipants::GetList(), G4BinaryLightIonReaction::GetProjectileExcitation(), G4BinaryLightIonReaction::Interact(), G4QGSParticipants::ReggeonCascade(), and G4FTFModel::ReggeonCascade().
GetSplitableHadron()
G4VSplitableHadron* G4Nucleon::GetSplitableHadron () const inline
Definition at line 95 of file G4Nucleon.hh.
Referenced by G4QGSParticipants::BuildInteractions(), G4FTFModel::BuildStrings(), G4QGSParticipants::CheckKinematics(), G4FTFModel::CheckKinematics(), G4QGSParticipants::CreateStrings(), G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), G4QGSParticipants::GenerateDeltaIsobar(), G4FTFModel::GenerateDeltaIsobar(), G4FTFParticipants::GetList(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), G4FTFModel::GetStrings(), G4QGSParticipants::PrepareInitialState(), G4QGSParticipants::ReggeonCascade(), G4FTFModel::ReggeonCascade(), G4QGSParticipants::SamplingNucleonKinematics(), G4FTFModel::SamplingNucleonKinematics(), and G4FTFModel::~G4FTFModel().
Hit() [1/2]
void G4Nucleon::Hit (G4int) inline
Definition at line 91 of file G4Nucleon.hh.
Hit() [2/2]
void G4Nucleon::Hit (G4VSplitableHadron * aHit) inline
Definition at line 89 of file G4Nucleon.hh.
Referenced by G4FTFParticipants::GetList(), G4QGSParticipants::GetList(), G4FTFModel::GetResiduals(), G4KineticTrack::Hit(), G4QGSParticipants::PrepareInitialState(), G4QGSParticipants::ReggeonCascade(), G4FTFModel::ReggeonCascade(), G4VPartonStringModel::Scatter(), G4GammaParticipants::SelectInteractions(), and G4QGSParticipants::SelectInteractions().
operator!=()
int G4Nucleon::operator!= (const G4Nucleon & right) const inline
Definition at line 115 of file G4Nucleon.hh.
operator=()
G4Nucleon & G4Nucleon::operator= (const G4Nucleon & right) inline
Definition at line 120 of file G4Nucleon.hh.
operator==()
int G4Nucleon::operator== (const G4Nucleon & right) const inline
Definition at line 111 of file G4Nucleon.hh.
SetBindingEnergy()
void G4Nucleon::SetBindingEnergy (G4double anEnergy) inline
Definition at line 74 of file G4Nucleon.hh.
Referenced by G4QGSParticipants::GetResiduals(), and G4FTFModel::GetResiduals().
SetMomentum()
void G4Nucleon::SetMomentum (G4LorentzVector & aMomentum) inline
Definition at line 70 of file G4Nucleon.hh.
Referenced by G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), G4QGSParticipants::SamplingNucleonKinematics(), G4FTFModel::SamplingNucleonKinematics(), and G4VPartonStringModel::Scatter().
SetParticleType() [1/4]
void G4Nucleon::SetParticleType (G4AntiNeutron * aAntiNeutron) inline
Definition at line 81 of file G4Nucleon.hh.
SetParticleType() [2/4]
void G4Nucleon::SetParticleType (G4AntiProton * aAntiProton) inline
Definition at line 80 of file G4Nucleon.hh.
SetParticleType() [3/4]
void G4Nucleon::SetParticleType (G4Neutron * aNeutron) inline
Definition at line 78 of file G4Nucleon.hh.
SetParticleType() [4/4]
void G4Nucleon::SetParticleType (G4Proton * aProton) inline
Definition at line 77 of file G4Nucleon.hh.
Referenced by G4FTFModel::Init().
SetPosition()
void G4Nucleon::SetPosition (const G4ThreeVector aPosition) inline
Definition at line 133 of file G4Nucleon.hh.
Referenced by G4QGSParticipants::GetList(), and G4QGSParticipants::PrepareInitialState().
Field Documentation
theBindingE
G4double G4Nucleon::theBindingE private
Definition at line 102 of file G4Nucleon.hh.
Referenced by GetBindingEnergy(), operator=(), and SetBindingEnergy().
theMomentum
G4LorentzVector G4Nucleon::theMomentum private
Definition at line 101 of file G4Nucleon.hh.
Referenced by Boost(), Get4Momentum(), GetMomentum(), operator=(), and SetMomentum().
theParticleType
const G4ParticleDefinition* G4Nucleon::theParticleType private
Definition at line 103 of file G4Nucleon.hh.
Referenced by GetDefinition(), GetParticleType(), operator=(), and SetParticleType().
thePosition
G4ThreeVector G4Nucleon::thePosition private
Definition at line 100 of file G4Nucleon.hh.
Referenced by GetPosition(), operator=(), and SetPosition().
theSplitableHadron
G4VSplitableHadron* G4Nucleon::theSplitableHadron private
Definition at line 104 of file G4Nucleon.hh.
Referenced by AreYouHit(), GetSplitableHadron(), Hit(), and operator=().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/util/include/G4Nucleon.hh
source/processes/hadronic/models/util/src/G4Nucleon.cc