Geant4: G4VFieldPropagation Class Reference
G4VFieldPropagation Class Reference abstract
#include <G4VFieldPropagation.hh>
Public Member Functions
G4VFieldPropagation ()
virtual ~G4VFieldPropagation ()
virtual void Init (G4V3DNucleus *theNucleus)=0
virtual void Transport (G4KineticTrackVector &theActive, const G4KineticTrackVector &theSpectators, G4double theTimeStep)=0
virtual G4ThreeVector GetMomentumTransfer () const =0
Private Member Functions
G4VFieldPropagation (const G4VFieldPropagation &right)
const G4VFieldPropagation & operator= (const G4VFieldPropagation &right)
G4int operator== (const G4VFieldPropagation &right) const
G4int operator!= (const G4VFieldPropagation &right) const
Detailed Description
Definition at line 34 of file G4VFieldPropagation.hh.
Constructor & Destructor Documentation
G4VFieldPropagation() [1/2]
G4VFieldPropagation::G4VFieldPropagation ()
Definition at line 42 of file G4VFieldPropagation.cc.
~G4VFieldPropagation()
G4VFieldPropagation::~G4VFieldPropagation () virtual
Definition at line 48 of file G4VFieldPropagation.cc.
G4VFieldPropagation() [2/2]
G4VFieldPropagation::G4VFieldPropagation (const G4VFieldPropagation & right) private
Definition at line 45 of file G4VFieldPropagation.cc.
Member Function Documentation
GetMomentumTransfer()
virtual G4ThreeVector G4VFieldPropagation::GetMomentumTransfer () const pure virtual
Implemented in G4RKPropagation.
Referenced by G4BinaryCascade::DoTimeStep().
Init()
virtual void G4VFieldPropagation::Init (G4V3DNucleus * theNucleus) pure virtual
Implemented in G4RKPropagation.
Referenced by G4BinaryCascade::ApplyYourself(), and G4BinaryCascade::Propagate().
operator!=()
G4int G4VFieldPropagation::operator!= (const G4VFieldPropagation & right) const private
operator=()
const G4VFieldPropagation& G4VFieldPropagation::operator= (const G4VFieldPropagation & right) private
operator==()
G4int G4VFieldPropagation::operator== (const G4VFieldPropagation & right) const private
Transport()
virtual void G4VFieldPropagation::Transport (G4KineticTrackVector & theActive, const G4KineticTrackVector & theSpectators, G4double theTimeStep) pure virtual
Implemented in G4RKPropagation.
Referenced by G4BinaryCascade::DoTimeStep().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/binary_cascade/include/G4VFieldPropagation.hh
source/processes/hadronic/models/binary_cascade/src/G4VFieldPropagation.cc