Geant4: G4ShellEMDataSet Class Reference
G4ShellEMDataSet Class Reference
#include <G4ShellEMDataSet.hh>
Public Member Functions
G4ShellEMDataSet (G4int Z, G4VDataSetAlgorithm *algo, G4double eUnit=CLHEP::MeV, G4double dataUnit=CLHEP::barn)
virtual ~G4ShellEMDataSet ()
virtual G4double FindValue (G4double energy, G4int componentId=0) const
virtual void PrintData (void) const
virtual const G4VEMDataSet * GetComponent (G4int componentId) const
virtual void AddComponent (G4VEMDataSet *dataSet)
virtual size_t NumberOfComponents (void) const
virtual const G4DataVector & GetEnergies (G4int componentId) const
virtual const G4DataVector & GetData (G4int componentId) const
virtual const G4DataVector & GetLogEnergies (G4int componentId) const
virtual const G4DataVector & GetLogData (G4int componentId) const
virtual void SetEnergiesData (G4DataVector *energies, G4DataVector *data, G4int componentId)
virtual void SetLogEnergiesData (G4DataVector *energies, G4DataVector *data, G4DataVector *log_energies, G4DataVector *log_data, G4int componentId)
virtual G4bool LoadData (const G4String &fileName)
virtual G4bool LoadNonLogData (const G4String &fileName)
virtual G4bool SaveData (const G4String &fileName) const
virtual G4double RandomSelect (G4int) const
Public Member Functions inherited from G4VEMDataSet
G4VEMDataSet ()
virtual ~G4VEMDataSet ()
Protected Member Functions
G4double GetUnitEnergies () const
G4double GetUnitData () const
const G4VDataSetAlgorithm * GetAlgorithm () const
void CleanUpComponents (void)
Private Member Functions
G4String FullFileName (const G4String &fileName) const
G4ShellEMDataSet ()
G4ShellEMDataSet (const G4ShellEMDataSet &copy)
G4ShellEMDataSet & operator= (const G4ShellEMDataSet &right)
Private Attributes
std::vector< G4VEMDataSet * > components
G4int z
G4VDataSetAlgorithm * algorithm
G4double unitEnergies
G4double unitData
Detailed Description
Definition at line 59 of file G4ShellEMDataSet.hh.
Constructor & Destructor Documentation
G4ShellEMDataSet() [1/3]
G4ShellEMDataSet::G4ShellEMDataSet (G4int Z, G4VDataSetAlgorithm * algo, G4double eUnit = CLHEP::MeV, G4double dataUnit = CLHEP::barn)
Definition at line 63 of file G4ShellEMDataSet.cc.
~G4ShellEMDataSet()
G4ShellEMDataSet::~G4ShellEMDataSet () virtual
Definition at line 76 of file G4ShellEMDataSet.cc.
G4ShellEMDataSet() [2/3]
G4ShellEMDataSet::G4ShellEMDataSet () private
G4ShellEMDataSet() [3/3]
G4ShellEMDataSet::G4ShellEMDataSet (const G4ShellEMDataSet & copy) private
Member Function Documentation
AddComponent()
virtual void G4ShellEMDataSet::AddComponent (G4VEMDataSet * dataSet) inline virtual
Implements G4VEMDataSet.
Definition at line 74 of file G4ShellEMDataSet.hh.
Referenced by LoadData(), and LoadNonLogData().
CleanUpComponents()
void G4ShellEMDataSet::CleanUpComponents (void) protected
Definition at line 388 of file G4ShellEMDataSet.cc.
Referenced by LoadData(), LoadNonLogData(), and ~G4ShellEMDataSet().
FindValue()
G4double G4ShellEMDataSet::FindValue (G4double energy, G4int componentId = 0) const virtual
Implements G4VEMDataSet.
Definition at line 83 of file G4ShellEMDataSet.cc.
FullFileName()
G4String G4ShellEMDataSet::FullFileName (const G4String & fileName) const private
Definition at line 398 of file G4ShellEMDataSet.cc.
Referenced by LoadData(), LoadNonLogData(), and SaveData().
GetAlgorithm()
const G4VDataSetAlgorithm* G4ShellEMDataSet::GetAlgorithm () const inline protected
Definition at line 100 of file G4ShellEMDataSet.hh.
GetComponent()
virtual const G4VEMDataSet* G4ShellEMDataSet::GetComponent (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 73 of file G4ShellEMDataSet.hh.
Referenced by GetData(), GetEnergies(), GetLogData(), GetLogEnergies(), PrintData(), and SaveData().
GetData()
virtual const G4DataVector& G4ShellEMDataSet::GetData (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 78 of file G4ShellEMDataSet.hh.
GetEnergies()
virtual const G4DataVector& G4ShellEMDataSet::GetEnergies (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 77 of file G4ShellEMDataSet.hh.
GetLogData()
virtual const G4DataVector& G4ShellEMDataSet::GetLogData (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 80 of file G4ShellEMDataSet.hh.
GetLogEnergies()
virtual const G4DataVector& G4ShellEMDataSet::GetLogEnergies (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 79 of file G4ShellEMDataSet.hh.
GetUnitData()
G4double G4ShellEMDataSet::GetUnitData () const inline protected
Definition at line 99 of file G4ShellEMDataSet.hh.
GetUnitEnergies()
G4double G4ShellEMDataSet::GetUnitEnergies () const inline protected
Definition at line 98 of file G4ShellEMDataSet.hh.
LoadData()
G4bool G4ShellEMDataSet::LoadData (const G4String & fileName) virtual
Implements G4VEMDataSet.
Definition at line 159 of file G4ShellEMDataSet.cc.
LoadNonLogData()
G4bool G4ShellEMDataSet::LoadNonLogData (const G4String & fileName) virtual
Implements G4VEMDataSet.
Definition at line 243 of file G4ShellEMDataSet.cc.
NumberOfComponents()
virtual size_t G4ShellEMDataSet::NumberOfComponents (void) const inline virtual
Implements G4VEMDataSet.
Definition at line 75 of file G4ShellEMDataSet.hh.
Referenced by PrintData(), and SaveData().
operator=()
G4ShellEMDataSet& G4ShellEMDataSet::operator= (const G4ShellEMDataSet & right) private
PrintData()
void G4ShellEMDataSet::PrintData (void) const virtual
Implements G4VEMDataSet.
Definition at line 101 of file G4ShellEMDataSet.cc.
RandomSelect()
virtual G4double G4ShellEMDataSet::RandomSelect (G4int) const inline virtual
Implements G4VEMDataSet.
Definition at line 94 of file G4ShellEMDataSet.hh.
SaveData()
G4bool G4ShellEMDataSet::SaveData (const G4String & fileName) const virtual
Implements G4VEMDataSet.
Definition at line 316 of file G4ShellEMDataSet.cc.
SetEnergiesData()
void G4ShellEMDataSet::SetEnergiesData (G4DataVector * energies, G4DataVector * data, G4int componentId) virtual
Implements G4VEMDataSet.
Definition at line 119 of file G4ShellEMDataSet.cc.
SetLogEnergiesData()
void G4ShellEMDataSet::SetLogEnergiesData (G4DataVector * energies, G4DataVector * data, G4DataVector * log_energies, G4DataVector * log_data, G4int componentId) virtual
Implements G4VEMDataSet.
Definition at line 137 of file G4ShellEMDataSet.cc.
Field Documentation
algorithm
G4VDataSetAlgorithm* G4ShellEMDataSet::algorithm private
Definition at line 117 of file G4ShellEMDataSet.hh.
Referenced by G4ShellEMDataSet(), GetAlgorithm(), LoadData(), LoadNonLogData(), and ~G4ShellEMDataSet().
components
std::vector<G4VEMDataSet*> G4ShellEMDataSet::components private
Definition at line 113 of file G4ShellEMDataSet.hh.
Referenced by AddComponent(), CleanUpComponents(), FindValue(), GetComponent(), NumberOfComponents(), SetEnergiesData(), and SetLogEnergiesData().
unitData
G4double G4ShellEMDataSet::unitData private
Definition at line 120 of file G4ShellEMDataSet.hh.
Referenced by GetUnitData(), LoadData(), LoadNonLogData(), and SaveData().
unitEnergies
G4double G4ShellEMDataSet::unitEnergies private
Definition at line 119 of file G4ShellEMDataSet.hh.
Referenced by GetUnitEnergies(), LoadData(), LoadNonLogData(), and SaveData().
z
G4int G4ShellEMDataSet::z private
Definition at line 115 of file G4ShellEMDataSet.hh.
Referenced by FullFileName().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/lowenergy/include/G4ShellEMDataSet.hh
source/processes/electromagnetic/lowenergy/src/G4ShellEMDataSet.cc