Geant4: source/g3tog4/src/G3toG4MakeSolid.cc File Reference
G3toG4MakeSolid.cc File Reference
#include "globals.hh"
#include "G4Box.hh"
#include "G4Tubs.hh"
#include "G4Trd.hh"
#include "G4Trap.hh"
#include "G4Cons.hh"
#include "G4Sphere.hh"
#include "G3toG4.hh"
#include "G4Polycone.hh"
#include "G4Polyhedra.hh"
#include "G4Para.hh"
#include "G4Hype.hh"
#include "G4EllipticalTube.hh"
#include "G3toG4MakeSolid.hh"
#include "G4SystemOfUnits.hh"
Functions
G4VSolid * G3toG4MakeSolid (const G4String &vname, const G4String &shape, const G4double *rpar, const G4int npar, G4bool &NegVolPars, G4bool &Deferred, G4bool *OKAxis)
Function Documentation
G3toG4MakeSolid()
G4VSolid* G3toG4MakeSolid (const G4String & vname, const G4String & shape, const G4double * rpar, const G4int npar, G4bool & NegVolPars, G4bool & Deferred, G4bool * OKAxis)
Definition at line 46 of file G3toG4MakeSolid.cc.
Referenced by G3Division::CreateSolid(), G4CreateCloneVTE(), G4CreateVTE(), and G4ProcessDaughters().