Geant4: G4VScoreWriter Class Reference
G4VScoreWriter Class Reference
#include <G4VScoreWriter.hh>
Public Member Functions
G4VScoreWriter ()
virtual ~G4VScoreWriter ()
virtual void DumpQuantityToFile (const G4String &psName, const G4String &fileName, const G4String &option)
virtual void DumpAllQuantitiesToFile (const G4String &fileName, const G4String &option)
void SetScoringMesh (G4VScoringMesh *sm)
void SetVerboseLevel (G4int vl)
Protected Member Functions
G4int GetIndex (G4int x, G4int y, G4int z) const
Protected Attributes
G4int fNMeshSegments [3]
G4VScoringMesh * fScoringMesh
G4int verboseLevel
Detailed Description
Definition at line 40 of file G4VScoreWriter.hh.
Constructor & Destructor Documentation
G4VScoreWriter()
G4VScoreWriter::G4VScoreWriter ()
Definition at line 39 of file G4VScoreWriter.cc.
~G4VScoreWriter()
G4VScoreWriter::~G4VScoreWriter () virtual
Definition at line 44 of file G4VScoreWriter.cc.
Member Function Documentation
DumpAllQuantitiesToFile()
void G4VScoreWriter::DumpAllQuantitiesToFile (const G4String & fileName, const G4String & option) virtual
Definition at line 151 of file G4VScoreWriter.cc.
Referenced by G4ScoringManager::DumpAllQuantitiesToFile().
DumpQuantityToFile()
void G4VScoreWriter::DumpQuantityToFile (const G4String & psName, const G4String & fileName, const G4String & option) virtual
Reimplemented in BrachyUserScoreWriter, and RE03UserScoreWriter.
Definition at line 52 of file G4VScoreWriter.cc.
Referenced by G4ScoringManager::DumpQuantityToFile().
GetIndex()
G4int G4VScoreWriter::GetIndex (G4int x, G4int y, G4int z) const protected
Definition at line 246 of file G4VScoreWriter.cc.
Referenced by DumpAllQuantitiesToFile(), DumpQuantityToFile(), BrachyUserScoreWriter::DumpQuantityToFile(), and RE03UserScoreWriter::DumpQuantityToFile().
SetScoringMesh()
void G4VScoreWriter::SetScoringMesh (G4VScoringMesh * sm)
Definition at line 47 of file G4VScoreWriter.cc.
Referenced by G4ScoringManager::DumpAllQuantitiesToFile(), and G4ScoringManager::DumpQuantityToFile().
SetVerboseLevel()
void G4VScoreWriter::SetVerboseLevel (G4int vl) inline
Definition at line 58 of file G4VScoreWriter.hh.
Referenced by G4ScoringManager::SetScoreWriter(), and G4ScoringManager::SetVerboseLevel().
Field Documentation
fNMeshSegments
G4int G4VScoreWriter::fNMeshSegments[3] protected
Definition at line 67 of file G4VScoreWriter.hh.
Referenced by DumpAllQuantitiesToFile(), DumpQuantityToFile(), BrachyUserScoreWriter::DumpQuantityToFile(), RE03UserScoreWriter::DumpQuantityToFile(), G4VScoreWriter(), GetIndex(), and SetScoringMesh().
fScoringMesh
G4VScoringMesh* G4VScoreWriter::fScoringMesh protected
Definition at line 68 of file G4VScoreWriter.hh.
Referenced by DumpAllQuantitiesToFile(), DumpQuantityToFile(), RE03UserScoreWriter::DumpQuantityToFile(), BrachyUserScoreWriter::DumpQuantityToFile(), and SetScoringMesh().
verboseLevel
G4int G4VScoreWriter::verboseLevel protected
Definition at line 69 of file G4VScoreWriter.hh.
Referenced by BrachyUserScoreWriter::DumpQuantityToFile(), RE03UserScoreWriter::DumpQuantityToFile(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
source/digits_hits/utils/include/G4VScoreWriter.hh
source/digits_hits/utils/src/G4VScoreWriter.cc