Geant4: G4INCL::ParticleList Class Reference
G4INCL::ParticleList Class Reference
#include <G4INCLParticle.hh>
Public Member Functions
void rotatePositionAndMomentum (const G4double angle, const ThreeVector &axis) const
void rotatePosition (const G4double angle, const ThreeVector &axis) const
void rotateMomentum (const G4double angle, const ThreeVector &axis) const
void boost (const ThreeVector &b) const
G4double getParticleListBias () const
std::vector< G4int > getParticleListBiasVector () const
Public Member Functions inherited from G4INCL::UnorderedVector< Particle * >
UnorderedVector ()
void remove (const Particle * &t)
G4bool contains (const Particle * &t) const
Detailed Description
Definition at line 62 of file G4INCLParticle.hh.
Member Function Documentation
boost()
void G4INCL::ParticleList::boost (const ThreeVector & b) const
Definition at line 178 of file G4INCLParticle.cc.
Referenced by G4INCL::InteractionAvatar::postInteraction().
getParticleListBias()
G4double G4INCL::ParticleList::getParticleListBias () const
Definition at line 184 of file G4INCLParticle.cc.
getParticleListBiasVector()
std::vector< G4int > G4INCL::ParticleList::getParticleListBiasVector () const
Definition at line 193 of file G4INCLParticle.cc.
Referenced by G4INCL::DecayAvatar::postInteraction(), G4INCL::SurfaceAvatar::postInteraction(), and G4INCL::InteractionAvatar::postInteraction().
rotateMomentum()
void G4INCL::ParticleList::rotateMomentum (const G4double angle, const ThreeVector & axis) const
Definition at line 172 of file G4INCLParticle.cc.
rotatePosition()
void G4INCL::ParticleList::rotatePosition (const G4double angle, const ThreeVector & axis) const
Definition at line 166 of file G4INCLParticle.cc.
rotatePositionAndMomentum()
void G4INCL::ParticleList::rotatePositionAndMomentum (const G4double angle, const ThreeVector & axis) const
Definition at line 160 of file G4INCLParticle.cc.
The documentation for this class was generated from the following files:
source/processes/hadronic/models/inclxx/utils/include/G4INCLParticle.hh
source/processes/hadronic/models/inclxx/utils/src/G4INCLParticle.cc