Geant4: source/global/management/src/G4Timer.cc File Reference
G4Timer.cc File Reference
#include "G4Timer.hh"
#include "G4ios.hh"
#include <iomanip>
#include "G4ExceptionSeverity.hh"
Functions
void G4Exception (const char *originOfException, const char *exceptionCode, G4ExceptionSeverity severity, const char *comments)
std::ostream & operator<< (std::ostream &os, const G4Timer &t)
Function Documentation
G4Exception()
void G4Exception (const char * originOfException, const char * exceptionCode, G4ExceptionSeverity severity, const char * comments)
Definition at line 36 of file G4Exception.cc.
Referenced by G4Exception(), G4Timer::GetRealElapsed(), G4Timer::GetSystemElapsed(), and G4Timer::GetUserElapsed().
operator<<()
std::ostream& operator<< (std::ostream & os, const G4Timer & t)
Definition at line 91 of file G4Timer.cc.