Geant4: DMXRunAction Class Reference
DMXRunAction Class Reference
#include <DMXRunAction.hh>
Public Member Functions
DMXRunAction ()
~DMXRunAction ()
void BeginOfRunAction (const G4Run *)
void EndOfRunAction (const G4Run *)
void SetsavehitsFile (G4String val)
void SetsavepmtFile (G4String val)
void SetsavehistFile (G4String val)
G4String GetsavehitsFile () const
G4String GetsavepmtFile () const
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual G4Run * GenerateRun ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Member Functions
void Book ()
Private Attributes
G4String savehitsFile
G4String savepmtFile
G4String savehistFile
DMXRunActionMessenger * runMessenger
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 54 of file DMXRunAction.hh.
Constructor & Destructor Documentation
DMXRunAction()
DMXRunAction::DMXRunAction ()
Definition at line 58 of file DMXRunAction.cc.
~DMXRunAction()
DMXRunAction::~DMXRunAction ()
Definition at line 68 of file DMXRunAction.cc.
Member Function Documentation
BeginOfRunAction()
void DMXRunAction::BeginOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 77 of file DMXRunAction.cc.
Book()
void DMXRunAction::Book () private
Definition at line 97 of file DMXRunAction.cc.
Referenced by BeginOfRunAction().
EndOfRunAction()
void DMXRunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
Definition at line 92 of file DMXRunAction.cc.
GetsavehitsFile()
G4String DMXRunAction::GetsavehitsFile () const inline
Definition at line 69 of file DMXRunAction.hh.
Referenced by DMXEventAction::writeScintHitsToFile().
GetsavepmtFile()
G4String DMXRunAction::GetsavepmtFile () const inline
Definition at line 70 of file DMXRunAction.hh.
Referenced by DMXEventAction::writePmtHitsToFile().
SetsavehistFile()
void DMXRunAction::SetsavehistFile (G4String val) inline
Definition at line 67 of file DMXRunAction.hh.
Referenced by DMXRunActionMessenger::SetNewValue().
SetsavehitsFile()
void DMXRunAction::SetsavehitsFile (G4String val) inline
Definition at line 65 of file DMXRunAction.hh.
Referenced by DMXRunActionMessenger::SetNewValue().
SetsavepmtFile()
void DMXRunAction::SetsavepmtFile (G4String val) inline
Definition at line 66 of file DMXRunAction.hh.
Referenced by DMXRunActionMessenger::SetNewValue().
Field Documentation
runMessenger
DMXRunActionMessenger* DMXRunAction::runMessenger private
Definition at line 80 of file DMXRunAction.hh.
Referenced by DMXRunAction(), and ~DMXRunAction().
savehistFile
G4String DMXRunAction::savehistFile private
Definition at line 78 of file DMXRunAction.hh.
Referenced by Book(), DMXRunAction(), and SetsavehistFile().
savehitsFile
G4String DMXRunAction::savehitsFile private
Definition at line 76 of file DMXRunAction.hh.
Referenced by DMXRunAction(), GetsavehitsFile(), and SetsavehitsFile().
savepmtFile
G4String DMXRunAction::savepmtFile private
Definition at line 77 of file DMXRunAction.hh.
Referenced by DMXRunAction(), GetsavepmtFile(), and SetsavepmtFile().
The documentation for this class was generated from the following files:
examples/advanced/underground_physics/include/DMXRunAction.hh
examples/advanced/underground_physics/src/DMXRunAction.cc