Geant4: G4Absorber Class Reference
G4Absorber Class Reference
#include <G4Absorber.hh>
Public Member Functions
G4Absorber (G4double cutOnP)
~G4Absorber ()
G4bool WillBeAbsorbed (const G4KineticTrack &kt)
G4bool Absorb (G4KineticTrack &kt, G4KineticTrackVector &tgt)
G4KineticTrackVector * GetAbsorbers ()
G4KineticTrackVector * GetProducts ()
G4bool FindAbsorbers (G4KineticTrack &kt, G4KineticTrackVector &tgt)
G4bool FindProducts (G4KineticTrack &kt)
Private Member Functions
G4Absorber (const G4Absorber &right)
const G4Absorber & operator= (const G4Absorber &right)
int operator== (const G4Absorber &right) const
int operator!= (const G4Absorber &right) const
G4ThreeVector GetRandomDirection ()
Private Attributes
G4double theCutOnP
G4KineticTrackVector * theAbsorbers
G4KineticTrackVector * theProducts
Detailed Description
Definition at line 34 of file G4Absorber.hh.
Constructor & Destructor Documentation
G4Absorber() [1/2]
G4Absorber::G4Absorber (G4double cutOnP)
Definition at line 38 of file G4Absorber.cc.
~G4Absorber()
G4Absorber::~G4Absorber ()
Definition at line 46 of file G4Absorber.cc.
G4Absorber() [2/2]
G4Absorber::G4Absorber (const G4Absorber & right) private
Member Function Documentation
Absorb()
G4bool G4Absorber::Absorb (G4KineticTrack & kt, G4KineticTrackVector & tgt)
Definition at line 72 of file G4Absorber.cc.
FindAbsorbers()
G4bool G4Absorber::FindAbsorbers (G4KineticTrack & kt, G4KineticTrackVector & tgt)
Definition at line 80 of file G4Absorber.cc.
Referenced by Absorb(), and G4BinaryCascade::Absorb().
FindProducts()
G4bool G4Absorber::FindProducts (G4KineticTrack & kt)
Definition at line 174 of file G4Absorber.cc.
Referenced by Absorb(), and G4BinaryCascade::Absorb().
GetAbsorbers()
G4KineticTrackVector * G4Absorber::GetAbsorbers () inline
Definition at line 66 of file G4Absorber.hh.
Referenced by G4BinaryCascade::Absorb().
GetProducts()
G4KineticTrackVector * G4Absorber::GetProducts () inline
Definition at line 71 of file G4Absorber.hh.
Referenced by G4BinaryCascade::Absorb().
GetRandomDirection()
G4ThreeVector G4Absorber::GetRandomDirection () private
Definition at line 286 of file G4Absorber.cc.
Referenced by FindProducts().
operator!=()
int G4Absorber::operator!= (const G4Absorber & right) const private
operator=()
const G4Absorber& G4Absorber::operator= (const G4Absorber & right) private
operator==()
int G4Absorber::operator== (const G4Absorber & right) const private
WillBeAbsorbed()
bool G4Absorber::WillBeAbsorbed (const G4KineticTrack & kt)
Definition at line 53 of file G4Absorber.cc.
Referenced by G4BinaryCascade::Absorb().
Field Documentation
theAbsorbers
G4KineticTrackVector* G4Absorber::theAbsorbers private
Definition at line 57 of file G4Absorber.hh.
Referenced by FindAbsorbers(), G4Absorber(), GetAbsorbers(), and ~G4Absorber().
theCutOnP
G4double G4Absorber::theCutOnP private
Definition at line 56 of file G4Absorber.hh.
Referenced by G4Absorber(), and WillBeAbsorbed().
theProducts
G4KineticTrackVector* G4Absorber::theProducts private
Definition at line 58 of file G4Absorber.hh.
Referenced by FindProducts(), G4Absorber(), GetProducts(), and ~G4Absorber().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/binary_cascade/include/G4Absorber.hh
source/processes/hadronic/models/binary_cascade/src/G4Absorber.cc