Geant4: G4AttFilterUtils Namespace Reference
G4AttFilterUtils Namespace Reference
Typedefs
typedef G4CreatorFactoryT< G4VAttValueFilter, G4TypeKey, G4VAttValueFilter *(*)()> G4AttValueFilterFactory
Functions
G4AttValueFilterFactory * GetAttValueFilterFactory ()
G4VAttValueFilter * GetNewFilter (const G4AttDef &def)
Typedef Documentation
G4AttValueFilterFactory
typedef G4CreatorFactoryT<G4VAttValueFilter, G4TypeKey, G4VAttValueFilter*(*)()> G4AttFilterUtils::G4AttValueFilterFactory
Definition at line 41 of file G4AttFilterUtils.hh.
Function Documentation
GetAttValueFilterFactory()
G4AttValueFilterFactory * G4AttFilterUtils::GetAttValueFilterFactory ()
Definition at line 54 of file G4AttFilterUtils.cc.
Referenced by GetNewFilter().
GetNewFilter()
G4VAttValueFilter * G4AttFilterUtils::GetNewFilter (const G4AttDef & def)
Definition at line 73 of file G4AttFilterUtils.cc.
Referenced by G4TrajectoryDrawByAttribute::Draw(), and G4AttributeFilterT< T >::Evaluate().