Geant4: G4UniformMagField Class Reference
G4UniformMagField Class Reference
#include <G4UniformMagField.hh>
Public Member Functions
G4UniformMagField (const G4ThreeVector &FieldVector)
G4UniformMagField (G4double vField, G4double vTheta, G4double vPhi)
virtual ~G4UniformMagField () override
G4UniformMagField (const G4UniformMagField &p)
G4UniformMagField & operator= (const G4UniformMagField &p)
virtual void GetFieldValue (const G4double yTrack[4], G4double *MagField) const override final
void SetFieldValue (const G4ThreeVector &newFieldValue)
G4ThreeVector GetConstantFieldValue () const
virtual G4Field * Clone () const override
Public Member Functions inherited from G4MagneticField
G4MagneticField ()
virtual ~G4MagneticField ()
G4MagneticField (const G4MagneticField &r)
G4MagneticField & operator= (const G4MagneticField &p)
G4bool DoesFieldChangeEnergy () const
Public Member Functions inherited from G4Field
G4Field (G4bool gravityOn=false)
G4Field (const G4Field &)
virtual ~G4Field ()
G4Field & operator= (const G4Field &p)
G4bool IsGravityActive () const
void SetGravityActive (G4bool OnOffFlag)
Private Attributes
G4double fFieldComponents [3]
Additional Inherited Members
Static Public Attributes inherited from G4Field
static constexpr G4int MAX_NUMBER_OF_COMPONENTS = 24
Detailed Description
Definition at line 48 of file G4UniformMagField.hh.
Constructor & Destructor Documentation
G4UniformMagField() [1/3]
G4UniformMagField::G4UniformMagField (const G4ThreeVector & FieldVector)
Definition at line 38 of file G4UniformMagField.cc.
Referenced by Clone().
G4UniformMagField() [2/3]
G4UniformMagField::G4UniformMagField (G4double vField, G4double vTheta, G4double vPhi)
Definition at line 60 of file G4UniformMagField.cc.
~G4UniformMagField()
G4UniformMagField::~G4UniformMagField () override virtual
Definition at line 93 of file G4UniformMagField.cc.
G4UniformMagField() [3/3]
G4UniformMagField::G4UniformMagField (const G4UniformMagField & p)
Definition at line 97 of file G4UniformMagField.cc.
Member Function Documentation
Clone()
G4Field * G4UniformMagField::Clone () const override virtual
Reimplemented from G4Field.
Definition at line 45 of file G4UniformMagField.cc.
GetConstantFieldValue()
G4ThreeVector G4UniformMagField::GetConstantFieldValue () const
Definition at line 127 of file G4UniformMagField.cc.
Referenced by export_G4UniformMagField(), and G4GlobalMagFieldMessenger::GetFieldValue().
GetFieldValue()
void G4UniformMagField::GetFieldValue (const G4double yTrack[4], G4double * MagField) const final override virtual
Implements G4MagneticField.
Definition at line 119 of file G4UniformMagField.cc.
operator=()
G4UniformMagField & G4UniformMagField::operator= (const G4UniformMagField & p)
Definition at line 106 of file G4UniformMagField.cc.
SetFieldValue()
void G4UniformMagField::SetFieldValue (const G4ThreeVector & newFieldValue)
Definition at line 53 of file G4UniformMagField.cc.
Referenced by export_G4UniformMagField(), G4GlobalMagFieldMessenger::SetField(), ExErrorMagneticField::SetFieldValue(), ExP01MagneticField::SetFieldValue(), and ExN02MagneticField::SetMagFieldValue().
Field Documentation
fFieldComponents
G4double G4UniformMagField::fFieldComponents[3] private
Definition at line 77 of file G4UniformMagField.hh.
Referenced by Clone(), G4UniformMagField(), GetConstantFieldValue(), GetFieldValue(), operator=(), and SetFieldValue().
The documentation for this class was generated from the following files:
source/geometry/magneticfield/include/G4UniformMagField.hh
source/geometry/magneticfield/src/G4UniformMagField.cc