Geant4: G4INCL::UnorderedVector< T > Class Template Reference
G4INCL::UnorderedVector< T > Class Template Reference
#include <G4INCLUnorderedVector.hh>
Public Member Functions
UnorderedVector ()
void remove (const T &t)
G4bool contains (const T &t) const
Detailed Description
template<class T>
class G4INCL::UnorderedVector< T >
Definition at line 63 of file G4INCLUnorderedVector.hh.
Constructor & Destructor Documentation
UnorderedVector()
template<class T> G4INCL::UnorderedVector< T >::UnorderedVector () inline
Definition at line 65 of file G4INCLUnorderedVector.hh.
Member Function Documentation
contains()
template<class T> G4bool G4INCL::UnorderedVector< T >::contains (const T & t) const inline
Definition at line 95 of file G4INCLUnorderedVector.hh.
Referenced by G4INCL::AvatarDumpAction::afterAvatarUserAction(), G4INCL::StandardPropagationModel::generateCollisions(), and G4INCL::StandardPropagationModel::generateUpdatedCollisions().
remove()
template<class T> void G4INCL::UnorderedVector< T >::remove (const T & t) inline
Definition at line 88 of file G4INCLUnorderedVector.hh.
Referenced by G4INCL::ProjectileRemnant::addDynamicalSpectators(), G4INCL::Store::extractDynamicalSpectators(), G4INCL::Store::particleHasBeenDestroyed(), G4INCL::Store::particleHasBeenEjected(), G4INCL::Store::removeAvatar(), and G4INCL::Cluster::removeParticle().
The documentation for this class was generated from the following file:
source/processes/hadronic/models/inclxx/utils/include/G4INCLUnorderedVector.hh