Geant4: source/g3tog4/src/G4gspos.cc File Reference
G4gspos.cc File Reference
#include "G3G4Interface.hh"
#include "G3VolTable.hh"
#include "G3toG4.hh"
#include "G3Pos.hh"
#include "globals.hh"
#include "G4SystemOfUnits.hh"
Functions
void G4CreateCloneVTE (G3VolTableEntry *vte, G3VolTableEntry *mvte, G4double pars[], G4int npar, G4int num, G4double x, G4double y, G4double z, G4int irot, G4String vonly)
void PG4gspos (G4String *tokens)
void G4gspos (G4String vname, G4int num, G4String vmoth, G4double x, G4double y, G4double z, G4int irot, G4String vonly)
Function Documentation
G4CreateCloneVTE()
void G4CreateCloneVTE (G3VolTableEntry * vte, G3VolTableEntry * mvte, G4double pars[], G4int npar, G4int num, G4double x, G4double y, G4double z, G4int irot, G4String vonly)
Definition at line 192 of file G4gsposp.cc.
Referenced by G4gspos(), and G4gsposp().
G4gspos()
void G4gspos (G4String vname, G4int num, G4String vmoth, G4double x, G4double y, G4double z, G4int irot, G4String vonly)
Definition at line 64 of file G4gspos.cc.
Referenced by PG4gspos().
PG4gspos()
void PG4gspos (G4String * tokens)
Definition at line 41 of file G4gspos.cc.
Referenced by G3CLEval().