Geant4: CexmcEventInfo Class Reference
CexmcEventInfo Class Reference
#include <CexmcEventInfo.hh>
Public Member Functions
CexmcEventInfo (G4bool edTriggerIsOk, G4bool tpTriggerIsOk, G4bool reconstructionIsOk)
void Print (void) const
G4bool EdTriggerIsOk (void) const
G4bool TpTriggerIsOk (void) const
G4bool ReconstructionIsOk (void) const
Public Member Functions inherited from G4VUserEventInformation
G4VUserEventInformation ()
virtual ~G4VUserEventInformation ()
Private Attributes
G4bool edTriggerIsOk
G4bool tpTriggerIsOk
G4bool reconstructionIsOk
Detailed Description
Definition at line 51 of file CexmcEventInfo.hh.
Constructor & Destructor Documentation
CexmcEventInfo()
CexmcEventInfo::CexmcEventInfo (G4bool edTriggerIsOk, G4bool tpTriggerIsOk, G4bool reconstructionIsOk)
Definition at line 47 of file CexmcEventInfo.cc.
Member Function Documentation
EdTriggerIsOk()
G4bool CexmcEventInfo::EdTriggerIsOk (void) const inline
Definition at line 76 of file CexmcEventInfo.hh.
Referenced by CexmcRunManager::DoCommonEventLoop(), and CexmcEventAction::EndOfEventAction().
Print()
void CexmcEventInfo::Print (void) const virtual
Implements G4VUserEventInformation.
Definition at line 55 of file CexmcEventInfo.cc.
ReconstructionIsOk()
G4bool CexmcEventInfo::ReconstructionIsOk (void) const inline
Definition at line 88 of file CexmcEventInfo.hh.
TpTriggerIsOk()
G4bool CexmcEventInfo::TpTriggerIsOk (void) const inline
Definition at line 82 of file CexmcEventInfo.hh.
Referenced by CexmcRunManager::DoCommonEventLoop().
Field Documentation
edTriggerIsOk
G4bool CexmcEventInfo::edTriggerIsOk private
Definition at line 68 of file CexmcEventInfo.hh.
Referenced by EdTriggerIsOk().
reconstructionIsOk
G4bool CexmcEventInfo::reconstructionIsOk private
Definition at line 72 of file CexmcEventInfo.hh.
Referenced by ReconstructionIsOk().
tpTriggerIsOk
G4bool CexmcEventInfo::tpTriggerIsOk private
Definition at line 70 of file CexmcEventInfo.hh.
Referenced by TpTriggerIsOk().
The documentation for this class was generated from the following files:
examples/advanced/ChargeExchangeMC/include/CexmcEventInfo.hh
examples/advanced/ChargeExchangeMC/src/CexmcEventInfo.cc