Geant4: G4INCL::NuclearPotential::INuclearPotential Class Reference
G4INCL::NuclearPotential::INuclearPotential Class Reference abstract
#include <G4INCLINuclearPotential.hh>
Public Member Functions
INuclearPotential (const G4int A, const G4int Z, const G4bool pionPot)
virtual ~INuclearPotential ()
G4bool hasPionPotential () const
Do we have a pion potential?
virtual G4double computePotentialEnergy (const Particle *const p) const =0
G4double getFermiEnergy (const Particle *const p) const
Return the Fermi energy for a particle.
G4double getFermiEnergy (const ParticleType t) const
Return the Fermi energy for a particle type.
G4double getSeparationEnergy (const Particle *const p) const
Return the separation energy for a particle.
G4double getSeparationEnergy (const ParticleType t) const
Return the separation energy for a particle type.
G4double getFermiMomentum (const Particle *const p) const
Return the Fermi momentum for a particle.
G4double getFermiMomentum (const ParticleType t) const
Return the Fermi momentum for a particle type.
Protected Member Functions
G4double computePionPotentialEnergy (const Particle *const p) const
Compute the potential energy for the given pion.
G4double computeKaonPotentialEnergy (const Particle *const p) const
Compute the potential energy for the given kaon.
G4double computePionResonancePotentialEnergy (const Particle *const p) const
Compute the potential energy for the given pion resonances (Eta, Omega and EtaPrime and Gamma also).
Protected Attributes
const G4int theA
The mass number of the nucleus.
const G4int theZ
The charge number of the nucleus.
std::map< ParticleType, G4double > fermiEnergy
std::map< ParticleType, G4double > fermiMomentum
std::map< ParticleType, G4double > separationEnergy
Private Attributes
const G4bool pionPotential
G4double vPiPlus
G4double vPiZero
G4double vPiMinus
G4double vKPlus
G4double vKZero
G4double vKZeroBar
G4double vKMinus
Static Private Attributes
static const G4double vPionDefault = 30.6
static const G4double vKPlusDefault = -25.
static const G4double vKMinusDefault = 60.
Detailed Description
Definition at line 61 of file G4INCLINuclearPotential.hh.
Constructor & Destructor Documentation
INuclearPotential()
G4INCL::NuclearPotential::INuclearPotential::INuclearPotential (const G4int A, const G4int Z, const G4bool pionPot) inline
Definition at line 63 of file G4INCLINuclearPotential.hh.
~INuclearPotential()
virtual G4INCL::NuclearPotential::INuclearPotential::~INuclearPotential () inline virtual
Definition at line 93 of file G4INCLINuclearPotential.hh.
Member Function Documentation
computeKaonPotentialEnergy()
G4double G4INCL::NuclearPotential::INuclearPotential::computeKaonPotentialEnergy (const Particle *const p) const inline protected
Compute the potential energy for the given kaon.
Definition at line 197 of file G4INCLINuclearPotential.hh.
Referenced by G4INCL::NuclearPotential::NuclearPotentialIsospin::computePotentialEnergy(), and G4INCL::NuclearPotential::NuclearPotentialConstant::computePotentialEnergy().
computePionPotentialEnergy()
G4double G4INCL::NuclearPotential::INuclearPotential::computePionPotentialEnergy (const Particle *const p) const inline protected
Compute the potential energy for the given pion.
Definition at line 173 of file G4INCLINuclearPotential.hh.
Referenced by G4INCL::NuclearPotential::NuclearPotentialIsospin::computePotentialEnergy(), and G4INCL::NuclearPotential::NuclearPotentialConstant::computePotentialEnergy().
computePionResonancePotentialEnergy()
G4double G4INCL::NuclearPotential::INuclearPotential::computePionResonancePotentialEnergy (const Particle *const p) const inline protected
Compute the potential energy for the given pion resonances (Eta, Omega and EtaPrime and Gamma also).
Definition at line 228 of file G4INCLINuclearPotential.hh.
Referenced by G4INCL::NuclearPotential::NuclearPotentialIsospin::computePotentialEnergy(), and G4INCL::NuclearPotential::NuclearPotentialConstant::computePotentialEnergy().
computePotentialEnergy()
virtual G4double G4INCL::NuclearPotential::INuclearPotential::computePotentialEnergy (const Particle *const p) const pure virtual
Implemented in G4INCL::NuclearPotential::NuclearPotentialConstant, G4INCL::NuclearPotential::NuclearPotentialEnergyIsospinSmooth, G4INCL::NuclearPotential::NuclearPotentialEnergyIsospin, and G4INCL::NuclearPotential::NuclearPotentialIsospin.
Referenced by G4INCL::ParticleEntryChannel::particleEnters(), and G4INCL::Nucleus::updatePotentialEnergy().
getFermiEnergy() [1/2]
G4double G4INCL::NuclearPotential::INuclearPotential::getFermiEnergy (const Particle *const p) const inline
Return the Fermi energy for a particle.
Parameters
p pointer to a Particle
Returns
Fermi energy for that particle type
Definition at line 105 of file G4INCLINuclearPotential.hh.
Referenced by G4INCL::NuclearPotential::NuclearPotentialEnergyIsospin::computePotentialEnergy(), G4INCL::NuclearPotential::NuclearPotentialEnergyIsospinSmooth::computePotentialEnergy(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::SurfaceAvatar::getChannel(), getFermiMomentum(), and G4INCL::CDPP::processOneParticle().
getFermiEnergy() [2/2]
G4double G4INCL::NuclearPotential::INuclearPotential::getFermiEnergy (const ParticleType t) const inline
Return the Fermi energy for a particle type.
Parameters
t particle type
Returns
Fermi energy for that particle type
Definition at line 116 of file G4INCLINuclearPotential.hh.
getFermiMomentum() [1/2]
G4double G4INCL::NuclearPotential::INuclearPotential::getFermiMomentum (const Particle *const p) const inline
Return the Fermi momentum for a particle.
Parameters
p pointer to a Particle
Returns
Fermi momentum for that particle type
Definition at line 149 of file G4INCLINuclearPotential.hh.
Referenced by G4INCL::PauliStandard::getBlockingProbability(), G4INCL::Nucleus::getSurfaceRadius(), G4INCL::ParticleSampler::sampleOneParticleWithFuzzyRPCorrelation(), and G4INCL::ParticleSampler::sampleOneParticleWithRPCorrelation().
getFermiMomentum() [2/2]
G4double G4INCL::NuclearPotential::INuclearPotential::getFermiMomentum (const ParticleType t) const inline
Return the Fermi momentum for a particle type.
Parameters
t particle type
Returns
Fermi momentum for that particle type
Definition at line 165 of file G4INCLINuclearPotential.hh.
getSeparationEnergy() [1/2]
G4double G4INCL::NuclearPotential::INuclearPotential::getSeparationEnergy (const Particle *const p) const inline
Return the separation energy for a particle.
Parameters
p pointer to a Particle
Returns
separation energy for that particle type
Definition at line 127 of file G4INCLINuclearPotential.hh.
Referenced by G4INCL::Nucleus::computeSeparationEnergyBalance(), G4INCL::Nucleus::Nucleus(), and G4INCL::CDPP::processOneParticle().
getSeparationEnergy() [2/2]
G4double G4INCL::NuclearPotential::INuclearPotential::getSeparationEnergy (const ParticleType t) const inline
Return the separation energy for a particle type.
Parameters
t particle type
Returns
separation energy for that particle type
Definition at line 138 of file G4INCLINuclearPotential.hh.
hasPionPotential()
G4bool G4INCL::NuclearPotential::INuclearPotential::hasPionPotential () const inline
Do we have a pion potential?
Definition at line 96 of file G4INCLINuclearPotential.hh.
Referenced by G4INCL::Nucleus::decayInsideDeltas().
Field Documentation
fermiEnergy
std::map<ParticleType,G4double> G4INCL::NuclearPotential::INuclearPotential::fermiEnergy protected
Definition at line 269 of file G4INCLINuclearPotential.hh.
Referenced by getFermiEnergy(), G4INCL::NuclearPotential::NuclearPotentialIsospin::initialize(), and G4INCL::NuclearPotential::NuclearPotentialConstant::initialize().
fermiMomentum
std::map<ParticleType,G4double> G4INCL::NuclearPotential::INuclearPotential::fermiMomentum protected
Definition at line 271 of file G4INCLINuclearPotential.hh.
Referenced by getFermiMomentum(), G4INCL::NuclearPotential::NuclearPotentialIsospin::initialize(), and G4INCL::NuclearPotential::NuclearPotentialConstant::initialize().
pionPotential
const G4bool G4INCL::NuclearPotential::INuclearPotential::pionPotential private
Definition at line 261 of file G4INCLINuclearPotential.hh.
Referenced by computeKaonPotentialEnergy(), computePionPotentialEnergy(), computePionResonancePotentialEnergy(), hasPionPotential(), and INuclearPotential().
separationEnergy
std::map<ParticleType,G4double> G4INCL::NuclearPotential::INuclearPotential::separationEnergy protected
Definition at line 273 of file G4INCLINuclearPotential.hh.
Referenced by getSeparationEnergy(), G4INCL::NuclearPotential::NuclearPotentialIsospin::initialize(), and G4INCL::NuclearPotential::NuclearPotentialConstant::initialize().
theA
const G4int G4INCL::NuclearPotential::INuclearPotential::theA protected
The mass number of the nucleus.
Definition at line 257 of file G4INCLINuclearPotential.hh.
Referenced by G4INCL::NuclearPotential::NuclearPotentialIsospin::initialize(), G4INCL::NuclearPotential::NuclearPotentialConstant::initialize(), and INuclearPotential().
theZ
const G4int G4INCL::NuclearPotential::INuclearPotential::theZ protected
The charge number of the nucleus.
Definition at line 259 of file G4INCLINuclearPotential.hh.
Referenced by G4INCL::NuclearPotential::NuclearPotentialIsospin::initialize(), G4INCL::NuclearPotential::NuclearPotentialConstant::initialize(), and INuclearPotential().
vKMinus
G4double G4INCL::NuclearPotential::INuclearPotential::vKMinus private
Definition at line 264 of file G4INCLINuclearPotential.hh.
Referenced by computeKaonPotentialEnergy(), and INuclearPotential().
vKMinusDefault
const G4double G4INCL::NuclearPotential::INuclearPotential::vKMinusDefault = 60. static private
Definition at line 266 of file G4INCLINuclearPotential.hh.
Referenced by INuclearPotential().
vKPlus
G4double G4INCL::NuclearPotential::INuclearPotential::vKPlus private
Definition at line 264 of file G4INCLINuclearPotential.hh.
Referenced by computeKaonPotentialEnergy(), and INuclearPotential().
vKPlusDefault
const G4double G4INCL::NuclearPotential::INuclearPotential::vKPlusDefault = -25. static private
Definition at line 265 of file G4INCLINuclearPotential.hh.
Referenced by INuclearPotential().
vKZero
G4double G4INCL::NuclearPotential::INuclearPotential::vKZero private
Definition at line 264 of file G4INCLINuclearPotential.hh.
Referenced by computeKaonPotentialEnergy(), and INuclearPotential().
vKZeroBar
G4double G4INCL::NuclearPotential::INuclearPotential::vKZeroBar private
Definition at line 264 of file G4INCLINuclearPotential.hh.
Referenced by computeKaonPotentialEnergy(), and INuclearPotential().
vPiMinus
G4double G4INCL::NuclearPotential::INuclearPotential::vPiMinus private
Definition at line 262 of file G4INCLINuclearPotential.hh.
Referenced by computePionPotentialEnergy(), and INuclearPotential().
vPionDefault
const G4double G4INCL::NuclearPotential::INuclearPotential::vPionDefault = 30.6 static private
Definition at line 263 of file G4INCLINuclearPotential.hh.
Referenced by INuclearPotential().
vPiPlus
G4double G4INCL::NuclearPotential::INuclearPotential::vPiPlus private
Definition at line 262 of file G4INCLINuclearPotential.hh.
Referenced by computePionPotentialEnergy(), and INuclearPotential().
vPiZero
G4double G4INCL::NuclearPotential::INuclearPotential::vPiZero private
Definition at line 262 of file G4INCLINuclearPotential.hh.
Referenced by computePionPotentialEnergy(), and INuclearPotential().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLINuclearPotential.hh
source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLINuclearPotential.cc