Geant4: G4NavigationHistory Class Reference
G4NavigationHistory Class Reference
#include <G4NavigationHistory.hh>
Public Member Functions
G4NavigationHistory ()
~G4NavigationHistory ()
G4NavigationHistory (const G4NavigationHistory &h)
G4NavigationHistory & operator= (const G4NavigationHistory &h)
void Reset ()
void Clear ()
void SetFirstEntry (G4VPhysicalVolume *pVol)
const G4AffineTransform & GetTopTransform () const
const G4AffineTransform * GetPtrTopTransform () const
G4int GetTopReplicaNo () const
EVolume GetTopVolumeType () const
G4VPhysicalVolume * GetTopVolume () const
G4int GetDepth () const
G4int GetMaxDepth () const
const G4AffineTransform & GetTransform (G4int n) const
G4int GetReplicaNo (G4int n) const
EVolume GetVolumeType (G4int n) const
G4VPhysicalVolume * GetVolume (G4int n) const
void NewLevel (G4VPhysicalVolume *pNewMother, EVolume vType=kNormal, G4int nReplica=-1)
void BackLevel ()
void BackLevel (G4int n)
void * operator new (size_t)
void operator delete (void *aHistory)
Private Member Functions
void EnlargeHistory ()
Private Attributes
std::vector< G4NavigationLevel > * fNavHistory
G4int fStackDepth
Friends
std::ostream & operator<< (std::ostream &os, const G4NavigationHistory &h)
Detailed Description
Definition at line 56 of file G4NavigationHistory.hh.
Constructor & Destructor Documentation
G4NavigationHistory() [1/2]
G4NavigationHistory::G4NavigationHistory ()
Definition at line 44 of file G4NavigationHistory.cc.
~G4NavigationHistory()
G4NavigationHistory::~G4NavigationHistory ()
Definition at line 66 of file G4NavigationHistory.cc.
G4NavigationHistory() [2/2]
G4NavigationHistory::G4NavigationHistory (const G4NavigationHistory & h)
Definition at line 51 of file G4NavigationHistory.cc.
Member Function Documentation
BackLevel() [1/2]
void G4NavigationHistory::BackLevel () inline
Referenced by G4ReplicaNavigation::BackLocate(), G4ScoreSplittingProcess::CreateTouchableForSubStep(), G4ParameterisedNavigation::LevelLocate(), G4Navigator::LocateGlobalPointAndSetup(), and G4ITNavigator1::LocateGlobalPointAndSetup().
BackLevel() [2/2]
void G4NavigationHistory::BackLevel (G4int n) inline
Clear()
void G4NavigationHistory::Clear () inline
Referenced by G4NavigationHistory().
EnlargeHistory()
void G4NavigationHistory::EnlargeHistory () inline private
GetDepth()
G4int G4NavigationHistory::GetDepth () const inline
Referenced by G4ReplicaNavigation::BackLocate(), G4ReplicaNavigation::ComputeSafety(), G4Navigator::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4ITNavigator1::ComputeStep(), G4RegularNavigation::ComputeStepSkippingEqualMaterials(), G4FastTrack::FRecordsAffineTransformation(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), operator<<(), G4Navigator::SetupHierarchy(), and G4ITNavigator1::SetupHierarchy().
GetMaxDepth()
G4int G4NavigationHistory::GetMaxDepth () const inline
Referenced by G4NavigationHistory().
GetPtrTopTransform()
const G4AffineTransform* G4NavigationHistory::GetPtrTopTransform () const inline
GetReplicaNo()
G4int G4NavigationHistory::GetReplicaNo (G4int n) const inline
Referenced by G4ReplicaNavigation::BackLocate(), G4ReplicaNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeStep(), operator<<(), G4Navigator::SetupHierarchy(), and G4ITNavigator1::SetupHierarchy().
GetTopReplicaNo()
G4int G4NavigationHistory::GetTopReplicaNo () const inline
Referenced by G4ReplicaNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeStep(), G4Navigator::LocateGlobalPointAndSetup(), and G4ITNavigator1::LocateGlobalPointAndSetup().
GetTopTransform()
const G4AffineTransform& G4NavigationHistory::GetTopTransform () const inline
Referenced by G4RegularNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4Navigator::ComputeStepLog(), G4ITNavigator1::ComputeStepLog(), F04ElementField::Construct(), G4DrawVoxels::DrawVoxels(), G4TouchableHistory::G4TouchableHistory(), F04PrimaryGeneratorAction::GeneratePrimaries(), G4Navigator::GetGlobalExitNormal(), G4VIntersectionLocator::GetLocalSurfaceNormal(), G4PSSphereSurfaceCurrent::IsSelectedSurface(), G4PSCylinderSurfaceFlux::IsSelectedSurface(), G4PSSphereSurfaceFlux::IsSelectedSurface(), G4PSCylinderSurfaceCurrent::IsSelectedSurface(), G4PSFlatSurfaceCurrent::IsSelectedSurface(), G4PSFlatSurfaceFlux::IsSelectedSurface(), G4RegularNavigation::LevelLocate(), G4ParameterisedNavigation::LevelLocate(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), ExN04CalorimeterSD::ProcessHits(), RE05CalorimeterSD::ProcessHits(), ScreenSD::ProcessHits(), Par01CalorimeterSD::ProcessHits(), XAluminumElectrodeSensitivity::ProcessHits(), RE01CalorimeterSD::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), and CCaloSD::SetToLocal().
GetTopVolume()
G4VPhysicalVolume* G4NavigationHistory::GetTopVolume () const inline
Referenced by G4ParameterisedNavigation::ComputeSafety(), G4NormalNavigation::ComputeSafety(), G4VoxelNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeSafety(), G4Navigator::ComputeSafety(), G4ITNavigator1::ComputeSafety(), G4RegularNavigation::ComputeStep(), G4ParameterisedNavigation::ComputeStep(), G4NormalNavigation::ComputeStep(), G4VoxelNavigation::ComputeStep(), G4Navigator::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4ITNavigator1::ComputeStep(), G4ScoreSplittingProcess::CreateTouchableForSubStep(), G4Navigator::GetGlobalExitNormal(), G4Navigator::GetLocalExitNormal(), G4ITNavigator1::GetLocalExitNormal(), G4RegularNavigation::LevelLocate(), G4ParameterisedNavigation::LevelLocate(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4Navigator::LocateGlobalPointWithinVolume(), G4ITNavigator1::LocateGlobalPointWithinVolume(), and G4Navigator::RecheckDistanceToCurrentBoundary().
GetTopVolumeType()
EVolume G4NavigationHistory::GetTopVolumeType () const inline
Referenced by G4Navigator::ComputeSafety(), G4ITNavigator1::ComputeSafety(), G4Navigator::ComputeStep(), G4ITNavigator1::ComputeStep(), G4ScoreSplittingProcess::CreateTouchableForSubStep(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4Navigator::LocateGlobalPointWithinVolume(), G4ITNavigator1::LocateGlobalPointWithinVolume(), and G4Navigator::RecheckDistanceToCurrentBoundary().
GetTransform()
const G4AffineTransform& G4NavigationHistory::GetTransform (G4int n) const inline
Referenced by G4ReplicaNavigation::BackLocate(), G4ReplicaNavigation::ComputeSafety(), G4Navigator::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4ITNavigator1::ComputeStep(), G4RegularNavigation::ComputeStepSkippingEqualMaterials(), G4FastTrack::FRecordsAffineTransformation(), G4TouchableHistory::GetRotation(), and G4TouchableHistory::GetTranslation().
GetVolume()
G4VPhysicalVolume* G4NavigationHistory::GetVolume (G4int n) const inline
Referenced by G4ReplicaNavigation::BackLocate(), G4ReplicaNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeStep(), G4FastTrack::FRecordsAffineTransformation(), operator<<(), G4Navigator::SetupHierarchy(), and G4ITNavigator1::SetupHierarchy().
GetVolumeType()
EVolume G4NavigationHistory::GetVolumeType (G4int n) const inline
Referenced by G4ReplicaNavigation::BackLocate(), G4ReplicaNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeStep(), operator<<(), G4Navigator::SetupHierarchy(), and G4ITNavigator1::SetupHierarchy().
NewLevel()
void G4NavigationHistory::NewLevel (G4VPhysicalVolume * pNewMother, EVolume vType = kNormal, G4int nReplica = -1) inline
Referenced by G4ScoreSplittingProcess::CreateTouchableForSubStep(), G4RegularNavigation::LevelLocate(), G4ParameterisedNavigation::LevelLocate(), G4Navigator::LocateGlobalPointAndSetup(), and G4ITNavigator1::LocateGlobalPointAndSetup().
operator delete()
void G4NavigationHistory::operator delete (void * aHistory) inline
operator new()
void* G4NavigationHistory::operator new (size_t) inline
operator=()
G4NavigationHistory& G4NavigationHistory::operator= (const G4NavigationHistory & h) inline
Reset()
void G4NavigationHistory::Reset () inline
SetFirstEntry()
void G4NavigationHistory::SetFirstEntry (G4VPhysicalVolume * pVol) inline
Referenced by G4TouchableHistory::G4TouchableHistory().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const G4NavigationHistory & h) friend
Definition at line 72 of file G4NavigationHistory.cc.
Field Documentation
fNavHistory
std::vector<G4NavigationLevel>* G4NavigationHistory::fNavHistory private
Definition at line 148 of file G4NavigationHistory.hh.
Referenced by G4NavigationHistory(), and ~G4NavigationHistory().
fStackDepth
G4int G4NavigationHistory::fStackDepth private
Definition at line 151 of file G4NavigationHistory.hh.
Referenced by G4NavigationHistory().
The documentation for this class was generated from the following files:
source/geometry/volumes/include/G4NavigationHistory.hh
source/geometry/volumes/src/G4NavigationHistory.cc