Geant4: source/global/management/src/G4ios.cc File Reference
G4ios.cc File Reference
#include "G4ios.hh"
#include "G4strstreambuf.hh"
#include <iostream>
Functions
void G4iosInitialization ()
void G4iosFinalization ()
Variables
G4strstreambuf G4coutbuf
G4strstreambuf G4cerrbuf
Function Documentation
G4iosFinalization()
void G4iosFinalization ()
Definition at line 107 of file G4ios.cc.
Referenced by G4StateManager::~G4StateManager(), and G4UImanager::~G4UImanager().
G4iosInitialization()
void G4iosInitialization ()
Definition at line 106 of file G4ios.cc.
Referenced by G4StateManager::G4StateManager(), G4UImanager::SetUpForAThread(), and G4UImanager::SetUpForSpecialThread().
Variable Documentation
G4cerrbuf
std::ostream G4cerr& G4cerrbuf
Definition at line 102 of file G4ios.cc.
Referenced by G4MTcoutDestination::G4MTcoutDestination(), G4UImanager::SetCoutDestination(), pyglobals::SetG4PyCoutDestination(), and G4coutFormatters::SetupStyleGlobally().
G4coutbuf
std::ostream G4cout& G4coutbuf
Definition at line 101 of file G4ios.cc.
Referenced by G4MTcoutDestination::G4MTcoutDestination(), G4UImanager::SetCoutDestination(), pyglobals::SetG4PyCoutDestination(), and G4coutFormatters::SetupStyleGlobally().