Geant4: G4GDMLParser Class Reference
G4GDMLParser Class Reference
#include <G4GDMLParser.hh>
Public Member Functions
G4GDMLParser ()
G4GDMLParser (G4GDMLReadStructure *)
G4GDMLParser (G4GDMLReadStructure *, G4GDMLWriteStructure *)
~G4GDMLParser ()
void Read (const G4String &filename, G4bool Validate=true)
void ReadModule (const G4String &filename, G4bool Validate=true)
void Write (const G4String &filename, const G4VPhysicalVolume *pvol=0, G4bool storeReferences=true, const G4String &SchemaLocation=G4GDML_DEFAULT_SCHEMALOCATION)
void Write (const G4String &filename, const G4LogicalVolume *lvol, G4bool storeReferences=true, const G4String &SchemaLocation=G4GDML_DEFAULT_SCHEMALOCATION)
G4LogicalVolume * ParseST (const G4String &name, G4Material *medium, G4Material *solid)
G4bool IsValid (const G4String &name) const
G4double GetConstant (const G4String &name) const
G4double GetVariable (const G4String &name) const
G4double GetQuantity (const G4String &name) const
G4ThreeVector GetPosition (const G4String &name) const
G4ThreeVector GetRotation (const G4String &name) const
G4ThreeVector GetScale (const G4String &name) const
G4GDMLMatrix GetMatrix (const G4String &name) const
G4LogicalVolume * GetVolume (const G4String &name) const
G4VPhysicalVolume * GetWorldVolume (const G4String &setupName="Default") const
G4GDMLAuxListType GetVolumeAuxiliaryInformation (G4LogicalVolume *lvol) const
const G4GDMLAuxMapType * GetAuxMap () const
const G4GDMLAuxListType * GetAuxList () const
void AddAuxiliary (G4GDMLAuxStructType myaux)
void StripNamePointers () const
void SetStripFlag (G4bool)
void SetOverlapCheck (G4bool)
void SetRegionExport (G4bool)
void SetEnergyCutsExport (G4bool)
void SetSDExport (G4bool)
G4int GetMaxExportLevel () const
void SetMaxExportLevel (G4int)
void Clear ()
void AddModule (const G4VPhysicalVolume *const physvol)
void AddModule (const G4int depth)
void SetAddPointerToName (G4bool set)
void AddVolumeAuxiliary (G4GDMLAuxStructType myaux, const G4LogicalVolume *const lvol)
Private Member Functions
void ImportRegions ()
void ExportRegions (G4bool storeReferences=true)
Private Attributes
G4GDMLEvaluator eval
G4GDMLReadStructure * reader
G4GDMLWriteStructure * writer
G4GDMLAuxListType * rlist
G4GDMLAuxListType * ullist
G4GDMLMessenger * messenger
G4bool urcode
G4bool uwcode
G4bool strip
G4bool rexp
Detailed Description
Definition at line 54 of file G4GDMLParser.hh.
Constructor & Destructor Documentation
G4GDMLParser() [1/3]
G4GDMLParser::G4GDMLParser ()
Definition at line 43 of file G4GDMLParser.cc.
G4GDMLParser() [2/3]
G4GDMLParser::G4GDMLParser (G4GDMLReadStructure * extr)
Definition at line 53 of file G4GDMLParser.cc.
G4GDMLParser() [3/3]
G4GDMLParser::G4GDMLParser (G4GDMLReadStructure * extr, G4GDMLWriteStructure * extw)
Definition at line 63 of file G4GDMLParser.cc.
~G4GDMLParser()
G4GDMLParser::~G4GDMLParser ()
Definition at line 74 of file G4GDMLParser.cc.
Member Function Documentation
AddAuxiliary()
void G4GDMLParser::AddAuxiliary (G4GDMLAuxStructType myaux) inline
Referenced by ExportRegions().
AddModule() [1/2]
void G4GDMLParser::AddModule (const G4int depth) inline
AddModule() [2/2]
void G4GDMLParser::AddModule (const G4VPhysicalVolume *const physvol) inline
AddVolumeAuxiliary()
void G4GDMLParser::AddVolumeAuxiliary (G4GDMLAuxStructType myaux, const G4LogicalVolume *const lvol) inline
Clear()
void G4GDMLParser::Clear () inline
Referenced by G4GDMLMessenger::SetNewValue().
ExportRegions()
void G4GDMLParser::ExportRegions (G4bool storeReferences = true) private
Definition at line 193 of file G4GDMLParser.cc.
GetAuxList()
const G4GDMLAuxListType* G4GDMLParser::GetAuxList () const inline
Referenced by ImportRegions().
GetAuxMap()
const G4GDMLAuxMapType* G4GDMLParser::GetAuxMap () const inline
Referenced by G04DetectorConstruction::ConstructSDandField().
GetConstant()
G4double G4GDMLParser::GetConstant (const G4String & name) const inline
GetMatrix()
G4GDMLMatrix G4GDMLParser::GetMatrix (const G4String & name) const inline
GetMaxExportLevel()
G4int G4GDMLParser::GetMaxExportLevel () const inline
GetPosition()
G4ThreeVector G4GDMLParser::GetPosition (const G4String & name) const inline
Referenced by CexmcSetup::ReadTransforms().
GetQuantity()
G4double G4GDMLParser::GetQuantity (const G4String & name) const inline
GetRotation()
G4ThreeVector G4GDMLParser::GetRotation (const G4String & name) const inline
Referenced by CexmcSetup::ReadTransforms().
GetScale()
G4ThreeVector G4GDMLParser::GetScale (const G4String & name) const inline
GetVariable()
G4double G4GDMLParser::GetVariable (const G4String & name) const inline
GetVolume()
G4LogicalVolume* G4GDMLParser::GetVolume (const G4String & name) const inline
GetVolumeAuxiliaryInformation()
G4GDMLAuxListType G4GDMLParser::GetVolumeAuxiliaryInformation (G4LogicalVolume * lvol) const inline
Referenced by CexmcSetup::SetupSpecialVolumes().
GetWorldVolume()
G4VPhysicalVolume* G4GDMLParser::GetWorldVolume (const G4String & setupName = "Default") const inline
Referenced by G04DetectorConstruction::Construct(), G03DetectorConstruction::Construct(), G02DetectorConstruction::Construct(), CexmcSetup::Construct(), and G4GDMLMessenger::SetNewValue().
ImportRegions()
void G4GDMLParser::ImportRegions () private
Definition at line 83 of file G4GDMLParser.cc.
IsValid()
G4bool G4GDMLParser::IsValid (const G4String & name) const inline
ParseST()
G4LogicalVolume* G4GDMLParser::ParseST (const G4String & name, G4Material * medium, G4Material * solid) inline
Referenced by G02DetectorConstruction::Construct().
Read()
void G4GDMLParser::Read (const G4String & filename, G4bool Validate = true) inline
Referenced by G03DetectorConstruction::Construct(), G02DetectorConstruction::Construct(), CexmcSetup::Construct(), and G4GDMLMessenger::SetNewValue().
ReadModule()
void G4GDMLParser::ReadModule (const G4String & filename, G4bool Validate = true) inline
SetAddPointerToName()
void G4GDMLParser::SetAddPointerToName (G4bool set) inline
Referenced by G4GDMLMessenger::SetNewValue().
SetEnergyCutsExport()
void G4GDMLParser::SetEnergyCutsExport (G4bool) inline
Referenced by G4GDMLMessenger::SetNewValue().
SetMaxExportLevel()
void G4GDMLParser::SetMaxExportLevel (G4int) inline
SetOverlapCheck()
void G4GDMLParser::SetOverlapCheck (G4bool) inline
SetRegionExport()
void G4GDMLParser::SetRegionExport (G4bool) inline
Referenced by G4GDMLMessenger::SetNewValue().
SetSDExport()
void G4GDMLParser::SetSDExport (G4bool) inline
Referenced by G4GDMLMessenger::SetNewValue().
SetStripFlag()
void G4GDMLParser::SetStripFlag (G4bool) inline
Referenced by G4GDMLMessenger::SetNewValue().
StripNamePointers()
void G4GDMLParser::StripNamePointers () const inline
Write() [1/2]
void G4GDMLParser::Write (const G4String & filename, const G4LogicalVolume * lvol, G4bool storeReferences = true, const G4String & SchemaLocation = G4GDML_DEFAULT_SCHEMALOCATION) inline
Write() [2/2]
void G4GDMLParser::Write (const G4String & filename, const G4VPhysicalVolume * pvol = 0, G4bool storeReferences = true, const G4String & SchemaLocation = G4GDML_DEFAULT_SCHEMALOCATION) inline
Referenced by G03DetectorConstruction::Construct(), G02DetectorConstruction::Construct(), and G4GDMLMessenger::SetNewValue().
Field Documentation
eval
G4GDMLEvaluator G4GDMLParser::eval private
Definition at line 149 of file G4GDMLParser.hh.
Referenced by ExportRegions(), and ImportRegions().
messenger
G4GDMLMessenger* G4GDMLParser::messenger private
Definition at line 153 of file G4GDMLParser.hh.
Referenced by G4GDMLParser(), and ~G4GDMLParser().
reader
G4GDMLReadStructure* G4GDMLParser::reader private
Definition at line 150 of file G4GDMLParser.hh.
Referenced by ExportRegions(), G4GDMLParser(), ImportRegions(), and ~G4GDMLParser().
rexp
G4bool G4GDMLParser::rexp private
Definition at line 154 of file G4GDMLParser.hh.
rlist
G4GDMLAuxListType* G4GDMLParser::rlist private
Definition at line 152 of file G4GDMLParser.hh.
Referenced by ExportRegions(), and ~G4GDMLParser().
strip
G4bool G4GDMLParser::strip private
Definition at line 154 of file G4GDMLParser.hh.
Referenced by ImportRegions().
ullist
G4GDMLAuxListType * G4GDMLParser::ullist private
Definition at line 152 of file G4GDMLParser.hh.
Referenced by ExportRegions(), and ~G4GDMLParser().
urcode
G4bool G4GDMLParser::urcode private
Definition at line 154 of file G4GDMLParser.hh.
Referenced by ~G4GDMLParser().
uwcode
G4bool G4GDMLParser::uwcode private
Definition at line 154 of file G4GDMLParser.hh.
Referenced by ~G4GDMLParser().
writer
G4GDMLWriteStructure* G4GDMLParser::writer private
Definition at line 151 of file G4GDMLParser.hh.
Referenced by ExportRegions(), G4GDMLParser(), and ~G4GDMLParser().
The documentation for this class was generated from the following files:
source/persistency/gdml/include/G4GDMLParser.hh
source/persistency/gdml/src/G4GDMLParser.cc