Geant4: BrachyAnalysisManager Class Reference
BrachyAnalysisManager Class Reference
#include <BrachyAnalysisManager.hh>
Public Member Functions
~BrachyAnalysisManager ()
void book ()
void save ()
Static Public Member Functions
static BrachyAnalysisManager * GetInstance ()
Private Member Functions
BrachyAnalysisManager ()
Static Private Attributes
static BrachyAnalysisManager * instance = 0
Detailed Description
Definition at line 45 of file BrachyAnalysisManager.hh.
Constructor & Destructor Documentation
BrachyAnalysisManager()
BrachyAnalysisManager::BrachyAnalysisManager () private
Definition at line 37 of file BrachyAnalysisManager.cc.
Referenced by GetInstance().
~BrachyAnalysisManager()
BrachyAnalysisManager::~BrachyAnalysisManager ()
Definition at line 46 of file BrachyAnalysisManager.cc.
Member Function Documentation
book()
void BrachyAnalysisManager::book ()
Definition at line 61 of file BrachyAnalysisManager.cc.
GetInstance()
BrachyAnalysisManager * BrachyAnalysisManager::GetInstance () static
Definition at line 55 of file BrachyAnalysisManager.cc.
Referenced by BrachyUserScoreWriter::DumpQuantityToFile(), BrachyPrimaryGeneratorAction::GeneratePrimaries(), main(), and BrachySteppingAction::UserSteppingAction().
save()
void BrachyAnalysisManager::save ()
Definition at line 88 of file BrachyAnalysisManager.cc.
Field Documentation
instance
BrachyAnalysisManager * BrachyAnalysisManager::instance = 0 static private
Definition at line 73 of file BrachyAnalysisManager.hh.
Referenced by GetInstance().
The documentation for this class was generated from the following files:
examples/advanced/brachytherapy/include/BrachyAnalysisManager.hh
examples/advanced/brachytherapy/src/BrachyAnalysisManager.cc