Geant4: source/g3tog4/src/G4gsdvx.cc File Reference
G4gsdvx.cc File Reference
#include "globals.hh"
#include "G3toG4.hh"
Functions
void G4gsdvn2 (G4String name, G4String moth, G4int ndiv, G4int iaxis, G4double c0, G4int numed)
void G4gsdvt2 (G4String name, G4String moth, G4double Step, G4int iaxis, G4double c0, G4int numed, G4int ndvmx)
void PG4gsdvx (G4String *tokens)
void G4gsdvx (G4String name, G4String moth, G4int ndiv, G4int iaxis, G4double Step, G4double c0, G4int numed, G4int ndvmx)
Function Documentation
G4gsdvn2()
void G4gsdvn2 (G4String name, G4String moth, G4int ndiv, G4int iaxis, G4double c0, G4int numed)
Definition at line 55 of file G4gsdvn2.cc.
Referenced by G4gsdvx(), and PG4gsdvn2().
G4gsdvt2()
void G4gsdvt2 (G4String name, G4String moth, G4double Step, G4int iaxis, G4double c0, G4int numed, G4int ndvmx)
Definition at line 57 of file G4gsdvt2.cc.
Referenced by G4gsdvx(), and PG4gsdvt2().
G4gsdvx()
void G4gsdvx (G4String name, G4String moth, G4int ndiv, G4int iaxis, G4double Step, G4double c0, G4int numed, G4int ndvmx)
Definition at line 57 of file G4gsdvx.cc.
Referenced by PG4gsdvx().
PG4gsdvx()
void PG4gsdvx (G4String * tokens)
Definition at line 39 of file G4gsdvx.cc.
Referenced by G3CLEval().