Geant4: G4SmartVoxelProxy Class Reference
G4SmartVoxelProxy Class Reference
#include <G4SmartVoxelProxy.hh>
Public Member Functions
G4SmartVoxelProxy (G4SmartVoxelHeader *pHeader)
G4SmartVoxelProxy (G4SmartVoxelNode *pNode)
~G4SmartVoxelProxy ()
G4bool IsHeader () const
G4bool IsNode () const
G4SmartVoxelNode * GetNode () const
G4SmartVoxelHeader * GetHeader () const
G4bool operator== (const G4SmartVoxelProxy &v) const
Private Attributes
G4SmartVoxelHeader * fHeader
G4SmartVoxelNode * fNode
Detailed Description
Definition at line 53 of file G4SmartVoxelProxy.hh.
Constructor & Destructor Documentation
G4SmartVoxelProxy() [1/2]
G4SmartVoxelProxy::G4SmartVoxelProxy (G4SmartVoxelHeader * pHeader) inline
Definition at line 58 of file G4SmartVoxelProxy.hh.
G4SmartVoxelProxy() [2/2]
G4SmartVoxelProxy::G4SmartVoxelProxy (G4SmartVoxelNode * pNode) inline
Definition at line 62 of file G4SmartVoxelProxy.hh.
~G4SmartVoxelProxy()
G4SmartVoxelProxy::~G4SmartVoxelProxy ()
Definition at line 38 of file G4SmartVoxelProxy.cc.
Member Function Documentation
GetHeader()
G4SmartVoxelHeader* G4SmartVoxelProxy::GetHeader () const
Referenced by G4SmartVoxelHeader::CollectEquivalentHeaders(), G4DrawVoxels::ComputeVoxelPolyhedra(), G4SmartVoxelStat::CountHeadsAndNodes(), G4VoxelNavigation::LocateNextVoxel(), G4SmartVoxelHeader::operator==(), and G4VoxelSafety::SafetyForVoxelHeader().
GetNode()
G4SmartVoxelNode* G4SmartVoxelProxy::GetNode () const
Referenced by G4SmartVoxelHeader::CollectEquivalentNodes(), G4ParameterisedNavigation::ComputeSafety(), G4DrawVoxels::ComputeVoxelPolyhedra(), G4ParameterisedNavigation::LocateNextVoxel(), G4VoxelNavigation::LocateNextVoxel(), G4SmartVoxelHeader::operator==(), G4SmartVoxelHeader::RefineNodes(), and G4VoxelSafety::SafetyForVoxelHeader().
IsHeader()
G4bool G4SmartVoxelProxy::IsHeader () const
Referenced by G4SmartVoxelHeader::CollectEquivalentHeaders(), G4DrawVoxels::ComputeVoxelPolyhedra(), and G4SmartVoxelHeader::operator==().
IsNode()
G4bool G4SmartVoxelProxy::IsNode () const
Referenced by G4SmartVoxelStat::CountHeadsAndNodes(), G4VoxelNavigation::LocateNextVoxel(), G4SmartVoxelHeader::operator==(), and G4VoxelSafety::SafetyForVoxelHeader().
operator==()
G4bool G4SmartVoxelProxy::operator== (const G4SmartVoxelProxy & v) const
Field Documentation
fHeader
G4SmartVoxelHeader* G4SmartVoxelProxy::fHeader private
Definition at line 87 of file G4SmartVoxelProxy.hh.
fNode
G4SmartVoxelNode* G4SmartVoxelProxy::fNode private
Definition at line 88 of file G4SmartVoxelProxy.hh.
The documentation for this class was generated from the following files:
source/geometry/management/include/G4SmartVoxelProxy.hh
source/geometry/management/src/G4SmartVoxelProxy.cc