Geant4: G4IStore Class Reference
G4IStore Class Reference
#include <G4IStore.hh>
Public Member Functions
virtual G4double GetImportance (const G4GeometryCell &gCell) const
virtual G4bool IsKnown (const G4GeometryCell &gCell) const
void Clear ()
void SetWorldVolume ()
void SetParallelWorldVolume (G4String paraName)
virtual const G4VPhysicalVolume & GetWorldVolume () const
virtual const G4VPhysicalVolume * GetParallelWorldVolumePointer () const
void AddImportanceGeometryCell (G4double importance, const G4GeometryCell &gCell)
void AddImportanceGeometryCell (G4double importance, const G4VPhysicalVolume &, G4int aRepNum=0)
void ChangeImportance (G4double importance, const G4GeometryCell &gCell)
void ChangeImportance (G4double importance, const G4VPhysicalVolume &, G4int aRepNum=0)
G4double GetImportance (const G4VPhysicalVolume &, G4int aRepNum=0) const
Public Member Functions inherited from G4VIStore
G4VIStore ()
virtual ~G4VIStore ()
Static Public Member Functions
static G4IStore * GetInstance ()
static G4IStore * GetInstance (const G4String &ParallelWorldName)
Protected Member Functions
G4IStore ()
G4IStore (const G4String &ParallelWorldName)
~G4IStore ()
Private Member Functions
G4bool IsInWorld (const G4VPhysicalVolume &) const
void SetInternalIterator (const G4GeometryCell &gCell) const
void Error (const G4String &m) const
Private Attributes
const G4VPhysicalVolume * fWorldVolume
G4GeometryCellImportance fGeometryCelli
G4GeometryCellImportance::const_iterator fCurrentIterator
Static Private Attributes
static G4ThreadLocal G4IStore * fInstance = 0
Detailed Description
Definition at line 61 of file G4IStore.hh.
Constructor & Destructor Documentation
G4IStore() [1/2]
G4IStore::G4IStore () explicit protected
Definition at line 51 of file G4IStore.cc.
Referenced by GetInstance().
G4IStore() [2/2]
G4IStore::G4IStore (const G4String & ParallelWorldName) explicit protected
Definition at line 55 of file G4IStore.cc.
~G4IStore()
G4IStore::~G4IStore () protected
Definition at line 62 of file G4IStore.cc.
Member Function Documentation
AddImportanceGeometryCell() [1/2]
void G4IStore::AddImportanceGeometryCell (G4double importance, const G4GeometryCell & gCell)
Definition at line 106 of file G4IStore.cc.
Referenced by AddImportanceGeometryCell(), B01DetectorConstruction::CreateImportanceStore(), B02ImportanceDetectorConstruction::CreateImportanceStore(), and main().
AddImportanceGeometryCell() [2/2]
void G4IStore::AddImportanceGeometryCell (G4double importance, const G4VPhysicalVolume & aVolume, G4int aRepNum = 0)
Definition at line 122 of file G4IStore.cc.
ChangeImportance() [1/2]
void G4IStore::ChangeImportance (G4double importance, const G4GeometryCell & gCell)
Definition at line 130 of file G4IStore.cc.
Referenced by ChangeImportance().
ChangeImportance() [2/2]
void G4IStore::ChangeImportance (G4double importance, const G4VPhysicalVolume & aVolume, G4int aRepNum = 0)
Definition at line 145 of file G4IStore.cc.
Clear()
void G4IStore::Clear ()
Definition at line 65 of file G4IStore.cc.
Error()
void G4IStore::Error (const G4String & m) const private
Definition at line 225 of file G4IStore.cc.
Referenced by AddImportanceGeometryCell(), ChangeImportance(), and GetImportance().
GetImportance() [1/2]
G4double G4IStore::GetImportance (const G4GeometryCell & gCell) const virtual
Implements G4VIStore.
Definition at line 173 of file G4IStore.cc.
GetImportance() [2/2]
G4double G4IStore::GetImportance (const G4VPhysicalVolume & aVolume, G4int aRepNum = 0) const
Definition at line 152 of file G4IStore.cc.
GetInstance() [1/2]
G4IStore * G4IStore::GetInstance (void) static
Definition at line 235 of file G4IStore.cc.
Referenced by B03PhysicsList::AddBiasingProcess(), G4ImportanceBiasing::ConstructProcess(), B01DetectorConstruction::CreateImportanceStore(), B02ImportanceDetectorConstruction::CreateImportanceStore(), and main().
GetInstance() [2/2]
G4IStore * G4IStore::GetInstance (const G4String & ParallelWorldName) static
Definition at line 250 of file G4IStore.cc.
GetParallelWorldVolumePointer()
const G4VPhysicalVolume * G4IStore::GetParallelWorldVolumePointer () const virtual
Definition at line 96 of file G4IStore.cc.
GetWorldVolume()
const G4VPhysicalVolume & G4IStore::GetWorldVolume () const virtual
Implements G4VIStore.
Definition at line 86 of file G4IStore.cc.
IsInWorld()
G4bool G4IStore::IsInWorld (const G4VPhysicalVolume & aVolume) const private
Definition at line 212 of file G4IStore.cc.
Referenced by AddImportanceGeometryCell(), ChangeImportance(), and IsKnown().
IsKnown()
G4bool G4IStore::IsKnown (const G4GeometryCell & gCell) const virtual
Implements G4VIStore.
Definition at line 196 of file G4IStore.cc.
SetInternalIterator()
void G4IStore::SetInternalIterator (const G4GeometryCell & gCell) const private
Definition at line 101 of file G4IStore.cc.
Referenced by AddImportanceGeometryCell(), ChangeImportance(), GetImportance(), and IsKnown().
SetParallelWorldVolume()
void G4IStore::SetParallelWorldVolume (G4String paraName)
Definition at line 78 of file G4IStore.cc.
SetWorldVolume()
void G4IStore::SetWorldVolume ()
Definition at line 70 of file G4IStore.cc.
Field Documentation
fCurrentIterator
G4GeometryCellImportance::const_iterator G4IStore::fCurrentIterator mutable private
Definition at line 143 of file G4IStore.hh.
Referenced by AddImportanceGeometryCell(), ChangeImportance(), GetImportance(), IsKnown(), and SetInternalIterator().
fGeometryCelli
G4GeometryCellImportance G4IStore::fGeometryCelli private
Definition at line 141 of file G4IStore.hh.
Referenced by AddImportanceGeometryCell(), ChangeImportance(), Clear(), GetImportance(), IsKnown(), and SetInternalIterator().
fInstance
G4ThreadLocal G4IStore * G4IStore::fInstance = 0 static private
Definition at line 145 of file G4IStore.hh.
Referenced by GetInstance().
fWorldVolume
const G4VPhysicalVolume* G4IStore::fWorldVolume private
Definition at line 138 of file G4IStore.hh.
Referenced by G4IStore(), GetParallelWorldVolumePointer(), GetWorldVolume(), IsInWorld(), SetParallelWorldVolume(), and SetWorldVolume().
The documentation for this class was generated from the following files:
source/geometry/biasing/include/G4IStore.hh
source/geometry/biasing/src/G4IStore.cc