Geant4: G4AtomicTransitionManager Class Reference
G4AtomicTransitionManager Class Reference
#include <G4AtomicTransitionManager.hh>
Public Member Functions
void Initialise ()
G4AtomicShell * Shell (G4int Z, size_t shellIndex) const
const G4FluoTransition * ReachableShell (G4int Z, size_t shellIndex) const
const G4AugerTransition * ReachableAugerShell (G4int Z, G4int shellIndex) const
G4int NumberOfShells (G4int Z) const
G4int NumberOfReachableShells (G4int Z) const
G4int NumberOfReachableAugerShells (G4int Z) const
G4double TotalRadiativeTransitionProbability (G4int Z, size_t shellIndex) const
G4double TotalNonRadiativeTransitionProbability (G4int Z, size_t shellIndex) const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel ()
Static Public Member Functions
static G4AtomicTransitionManager * Instance ()
Private Member Functions
G4AtomicTransitionManager ()
~G4AtomicTransitionManager ()
G4AtomicTransitionManager & operator= (const G4AtomicTransitionManager &right)
G4AtomicTransitionManager (const G4AtomicTransitionManager &)
Private Attributes
std::map< G4int, std::vector< G4AtomicShell * >, std::less< G4int > > shellTable
std::map< G4int, std::vector< G4FluoTransition * >, std::less< G4int > > transitionTable
G4AugerData * augerData
G4int zMin
G4int zMax
G4int infTableLimit
G4int supTableLimit
G4bool isInitialized
G4int verboseLevel
Static Private Attributes
static G4AtomicTransitionManager * instance = 0
Detailed Description
Definition at line 59 of file G4AtomicTransitionManager.hh.
Constructor & Destructor Documentation
G4AtomicTransitionManager() [1/2]
G4AtomicTransitionManager::G4AtomicTransitionManager () private
Definition at line 52 of file G4AtomicTransitionManager.cc.
Referenced by Instance().
~G4AtomicTransitionManager()
G4AtomicTransitionManager::~G4AtomicTransitionManager () private
Definition at line 62 of file G4AtomicTransitionManager.cc.
G4AtomicTransitionManager() [2/2]
G4AtomicTransitionManager::G4AtomicTransitionManager (const G4AtomicTransitionManager &) private
Member Function Documentation
GetVerboseLevel()
G4int G4AtomicTransitionManager::GetVerboseLevel () inline
Definition at line 115 of file G4AtomicTransitionManager.hh.
Initialise()
void G4AtomicTransitionManager::Initialise ()
Definition at line 285 of file G4AtomicTransitionManager.cc.
Referenced by G4LivermoreIonisationModel::Initialise(), G4UAtomicDeexcitation::InitialiseForNewRun(), and G4PenelopeOscillatorManager::ReadElementData().
Instance()
G4AtomicTransitionManager * G4AtomicTransitionManager::Instance (void) static
Definition at line 44 of file G4AtomicTransitionManager.cc.
Referenced by G4eIonisationSpectrum::AverageEnergy(), G4ecpssrBaseKxsModel::CalculateCrossSection(), G4ecpssrBaseLixsModel::CalculateL1CrossSection(), G4ecpssrBaseLixsModel::CalculateL2CrossSection(), G4ecpssrBaseLixsModel::CalculateL3CrossSection(), G4ecpssrBaseLixsModel::CalculateVelocity(), G4LivermoreIonisationCrossSection::G4LivermoreIonisationCrossSection(), G4LivermoreIonisationModel::G4LivermoreIonisationModel(), G4OrlicLiXsModel::G4OrlicLiXsModel(), G4PenelopeComptonModel::G4PenelopeComptonModel(), G4PenelopeIonisationCrossSection::G4PenelopeIonisationCrossSection(), G4PenelopePhotoElectricModel::G4PenelopePhotoElectricModel(), G4UAtomicDeexcitation::G4UAtomicDeexcitation(), G4AtomicDeexcitation::GenerateAuger(), G4AtomicDeexcitation::GenerateFluorescence(), G4hImpactIonisation::PostStepDoIt(), G4eIonisationSpectrum::Probability(), G4PenelopeOscillatorManager::ReadElementData(), G4eIonisationSpectrum::SampleEnergy(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4PenelopeIonisationModel::SampleSecondaries(), and G4AtomicDeexcitation::SelectTypeOfTransition().
NumberOfReachableAugerShells()
G4int G4AtomicTransitionManager::NumberOfReachableAugerShells (G4int Z) const
Definition at line 216 of file G4AtomicTransitionManager.cc.
Referenced by G4AtomicDeexcitation::GenerateAuger(), and G4UAtomicDeexcitation::GenerateAuger().
NumberOfReachableShells()
G4int G4AtomicTransitionManager::NumberOfReachableShells (G4int Z) const
Definition at line 192 of file G4AtomicTransitionManager.cc.
Referenced by G4AtomicDeexcitation::GenerateFluorescence(), G4UAtomicDeexcitation::GenerateFluorescence(), G4AtomicDeexcitation::SelectTypeOfTransition(), and G4UAtomicDeexcitation::SelectTypeOfTransition().
NumberOfShells()
G4int G4AtomicTransitionManager::NumberOfShells (G4int Z) const
Definition at line 170 of file G4AtomicTransitionManager.cc.
Referenced by G4LivermoreIonisationModel::ComputeDEDXPerVolume(), G4LivermoreIonisationCrossSection::CrossSection(), G4PenelopeIonisationCrossSection::CrossSection(), G4PenelopeIonisationCrossSection::GetCrossSection(), G4LivermoreIonisationCrossSection::GetCrossSection(), G4PenelopeOscillatorManager::ReadElementData(), and G4PenelopePhotoElectricModel::SampleSecondaries().
operator=()
G4AtomicTransitionManager& G4AtomicTransitionManager::operator= (const G4AtomicTransitionManager & right) private
ReachableAugerShell()
const G4AugerTransition * G4AtomicTransitionManager::ReachableAugerShell (G4int Z, G4int shellIndex) const
Definition at line 164 of file G4AtomicTransitionManager.cc.
Referenced by G4AtomicDeexcitation::GenerateAuger(), and G4UAtomicDeexcitation::GenerateAuger().
ReachableShell()
const G4FluoTransition * G4AtomicTransitionManager::ReachableShell (G4int Z, size_t shellIndex) const
Definition at line 135 of file G4AtomicTransitionManager.cc.
Referenced by G4AtomicDeexcitation::SelectTypeOfTransition(), and G4UAtomicDeexcitation::SelectTypeOfTransition().
SetVerboseLevel()
void G4AtomicTransitionManager::SetVerboseLevel (G4int vl) inline
Definition at line 114 of file G4AtomicTransitionManager.hh.
Shell()
G4AtomicShell * G4AtomicTransitionManager::Shell (G4int Z, size_t shellIndex) const
Definition at line 94 of file G4AtomicTransitionManager.cc.
Referenced by G4ecpssrBaseKxsModel::CalculateCrossSection(), G4ecpssrBaseLixsModel::CalculateL1CrossSection(), G4OrlicLiXsModel::CalculateL1CrossSection(), G4ecpssrBaseLixsModel::CalculateL2CrossSection(), G4OrlicLiXsModel::CalculateL2CrossSection(), G4ecpssrBaseLixsModel::CalculateL3CrossSection(), G4OrlicLiXsModel::CalculateL3CrossSection(), G4ecpssrBaseLixsModel::CalculateVelocity(), G4UAtomicDeexcitation::GetAtomicShell(), G4hImpactIonisation::PostStepDoIt(), G4PenelopeOscillatorManager::ReadElementData(), G4LivermoreIonisationModel::SampleSecondaries(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), and G4PenelopeIonisationModel::SampleSecondaries().
TotalNonRadiativeTransitionProbability()
G4double G4AtomicTransitionManager::TotalNonRadiativeTransitionProbability (G4int Z, size_t shellIndex) const
Definition at line 265 of file G4AtomicTransitionManager.cc.
TotalRadiativeTransitionProbability()
G4double G4AtomicTransitionManager::TotalRadiativeTransitionProbability (G4int Z, size_t shellIndex) const
Definition at line 221 of file G4AtomicTransitionManager.cc.
Referenced by TotalNonRadiativeTransitionProbability().
Field Documentation
augerData
G4AugerData* G4AtomicTransitionManager::augerData private
Definition at line 139 of file G4AtomicTransitionManager.hh.
Referenced by Initialise(), NumberOfReachableAugerShells(), ReachableAugerShell(), and ~G4AtomicTransitionManager().
infTableLimit
G4int G4AtomicTransitionManager::infTableLimit private
Definition at line 148 of file G4AtomicTransitionManager.hh.
Referenced by Initialise().
instance
G4AtomicTransitionManager * G4AtomicTransitionManager::instance = 0 static private
Definition at line 127 of file G4AtomicTransitionManager.hh.
Referenced by Instance().
isInitialized
G4bool G4AtomicTransitionManager::isInitialized private
Definition at line 151 of file G4AtomicTransitionManager.hh.
Referenced by Initialise().
shellTable
std::map<G4int,std::vector<G4AtomicShell*>,std::less<G4int> > G4AtomicTransitionManager::shellTable private
Definition at line 131 of file G4AtomicTransitionManager.hh.
Referenced by Initialise(), NumberOfShells(), Shell(), and ~G4AtomicTransitionManager().
supTableLimit
G4int G4AtomicTransitionManager::supTableLimit private
Definition at line 149 of file G4AtomicTransitionManager.hh.
Referenced by Initialise().
transitionTable
std::map<G4int,std::vector<G4FluoTransition*>,std::less<G4int> > G4AtomicTransitionManager::transitionTable private
Definition at line 135 of file G4AtomicTransitionManager.hh.
Referenced by Initialise(), NumberOfReachableShells(), ReachableShell(), TotalRadiativeTransitionProbability(), and ~G4AtomicTransitionManager().
verboseLevel
G4int G4AtomicTransitionManager::verboseLevel private
Definition at line 153 of file G4AtomicTransitionManager.hh.
Referenced by GetVerboseLevel(), SetVerboseLevel(), and Shell().
zMax
G4int G4AtomicTransitionManager::zMax private
Definition at line 144 of file G4AtomicTransitionManager.hh.
Referenced by Initialise().
zMin
G4int G4AtomicTransitionManager::zMin private
Definition at line 143 of file G4AtomicTransitionManager.hh.
Referenced by Initialise().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/lowenergy/include/G4AtomicTransitionManager.hh
source/processes/electromagnetic/lowenergy/src/G4AtomicTransitionManager.cc