Geant4: G4PhantomParameterisation Class Reference
G4PhantomParameterisation Class Reference
#include <G4PhantomParameterisation.hh>
Public Member Functions
G4PhantomParameterisation ()
~G4PhantomParameterisation ()
virtual void ComputeTransformation (const G4int, G4VPhysicalVolume *) const
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=0)
void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
void BuildContainerSolid (G4VPhysicalVolume *pPhysicalVol)
void BuildContainerSolid (G4VSolid *pMotherSolid)
virtual G4int GetReplicaNo (const G4ThreeVector &localPoint, const G4ThreeVector &localDir)
void SetMaterials (std::vector< G4Material * > &mates)
void SetMaterialIndices (size_t *matInd)
void SetVoxelDimensions (G4double halfx, G4double halfy, G4double halfz)
void SetNoVoxel (size_t nx, size_t ny, size_t nz)
G4double GetVoxelHalfX () const
G4double GetVoxelHalfY () const
G4double GetVoxelHalfZ () const
size_t GetNoVoxelX () const
size_t GetNoVoxelY () const
size_t GetNoVoxelZ () const
size_t GetNoVoxel () const
std::vector< G4Material * > GetMaterials () const
size_t * GetMaterialIndices () const
G4VSolid * GetContainerSolid () const
G4ThreeVector GetTranslation (const G4int copyNo) const
G4bool SkipEqualMaterials () const
void SetSkipEqualMaterials (G4bool skip)
size_t GetMaterialIndex (size_t nx, size_t ny, size_t nz) const
size_t GetMaterialIndex (size_t copyNo) const
G4Material * GetMaterial (size_t nx, size_t ny, size_t nz) const
G4Material * GetMaterial (size_t copyNo) const
void CheckVoxelsFillContainer (G4double contX, G4double contY, G4double contZ) const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Protected Attributes
G4double fVoxelHalfX
G4double fVoxelHalfY
G4double fVoxelHalfZ
size_t fNoVoxelX
size_t fNoVoxelY
size_t fNoVoxelZ
size_t fNoVoxelXY
size_t fNoVoxel
std::vector< G4Material * > fMaterials
size_t * fMaterialIndices
G4VSolid * fContainerSolid
G4double fContainerWallX
G4double fContainerWallY
G4double fContainerWallZ
G4double kCarTolerance
G4bool bSkipEqualMaterials
Private Member Functions
void ComputeVoxelIndices (const G4int copyNo, size_t &nx, size_t &ny, size_t &nz) const
void CheckCopyNo (const G4int copyNo) const
Detailed Description
Definition at line 72 of file G4PhantomParameterisation.hh.
Constructor & Destructor Documentation
G4PhantomParameterisation()
G4PhantomParameterisation::G4PhantomParameterisation ()
Definition at line 45 of file G4PhantomParameterisation.cc.
~G4PhantomParameterisation()
G4PhantomParameterisation::~G4PhantomParameterisation ()
Definition at line 57 of file G4PhantomParameterisation.cc.
Member Function Documentation
BuildContainerSolid() [1/2]
void G4PhantomParameterisation::BuildContainerSolid (G4VPhysicalVolume * pPhysicalVol)
Definition at line 64 of file G4PhantomParameterisation.cc.
Referenced by DicomRegularDetectorConstruction::ConstructPhantom().
BuildContainerSolid() [2/2]
void G4PhantomParameterisation::BuildContainerSolid (G4VSolid * pMotherSolid)
Definition at line 76 of file G4PhantomParameterisation.cc.
CheckCopyNo()
void G4PhantomParameterisation::CheckCopyNo (const G4int copyNo) const private
Definition at line 392 of file G4PhantomParameterisation.cc.
Referenced by ComputeMaterial(), ComputeVoxelIndices(), GetMaterialIndex(), and GetTranslation().
CheckVoxelsFillContainer()
void G4PhantomParameterisation::CheckVoxelsFillContainer (G4double contX, G4double contY, G4double contZ) const
Definition at line 184 of file G4PhantomParameterisation.cc.
Referenced by DicomRegularDetectorConstruction::ConstructPhantom().
ComputeDimensions() [1/13]
void G4PhantomParameterisation::ComputeDimensions (G4Box & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 88 of file G4PhantomParameterisation.hh.
ComputeDimensions() [2/13]
void G4PhantomParameterisation::ComputeDimensions (G4Cons & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 96 of file G4PhantomParameterisation.hh.
ComputeDimensions() [3/13]
void G4PhantomParameterisation::ComputeDimensions (G4Ellipsoid & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 102 of file G4PhantomParameterisation.hh.
ComputeDimensions() [4/13]
void G4PhantomParameterisation::ComputeDimensions (G4Hype & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 108 of file G4PhantomParameterisation.hh.
ComputeDimensions() [5/13]
void G4PhantomParameterisation::ComputeDimensions (G4Orb & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 98 of file G4PhantomParameterisation.hh.
ComputeDimensions() [6/13]
void G4PhantomParameterisation::ComputeDimensions (G4Para & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 106 of file G4PhantomParameterisation.hh.
ComputeDimensions() [7/13]
void G4PhantomParameterisation::ComputeDimensions (G4Polycone & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 110 of file G4PhantomParameterisation.hh.
ComputeDimensions() [8/13]
void G4PhantomParameterisation::ComputeDimensions (G4Polyhedra & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 112 of file G4PhantomParameterisation.hh.
ComputeDimensions() [9/13]
void G4PhantomParameterisation::ComputeDimensions (G4Sphere & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 100 of file G4PhantomParameterisation.hh.
ComputeDimensions() [10/13]
void G4PhantomParameterisation::ComputeDimensions (G4Torus & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 104 of file G4PhantomParameterisation.hh.
ComputeDimensions() [11/13]
void G4PhantomParameterisation::ComputeDimensions (G4Trap & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 94 of file G4PhantomParameterisation.hh.
ComputeDimensions() [12/13]
void G4PhantomParameterisation::ComputeDimensions (G4Trd & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 92 of file G4PhantomParameterisation.hh.
ComputeDimensions() [13/13]
void G4PhantomParameterisation::ComputeDimensions (G4Tubs & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 90 of file G4PhantomParameterisation.hh.
ComputeMaterial()
G4Material * G4PhantomParameterisation::ComputeMaterial (const G4int repNo, G4VPhysicalVolume * currentVol, const G4VTouchable * parentTouch = 0) virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in G4PartialPhantomParameterisation, and DicomPhantomParameterisationColour.
Definition at line 128 of file G4PhantomParameterisation.cc.
Referenced by G4GMocrenFileSceneHandler::AddSolid(), DicomPhantomParameterisationColour::ComputeMaterial(), G4RegularNavigation::ComputeStepSkippingEqualMaterials(), and G4RegularNavigation::LevelLocate().
ComputeSolid()
G4VSolid * G4PhantomParameterisation::ComputeSolid (const G4int, G4VPhysicalVolume * pPhysicalVol) virtual
Reimplemented from G4VPVParameterisation.
Definition at line 120 of file G4PhantomParameterisation.cc.
ComputeTransformation()
void G4PhantomParameterisation::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const virtual
Implements G4VPVParameterisation.
Reimplemented in G4PartialPhantomParameterisation.
Definition at line 89 of file G4PhantomParameterisation.cc.
Referenced by G4RegularNavigation::LevelLocate().
ComputeVoxelIndices()
void G4PhantomParameterisation::ComputeVoxelIndices (const G4int copyNo, size_t & nx, size_t & ny, size_t & nz) const private
Definition at line 172 of file G4PhantomParameterisation.cc.
Referenced by GetTranslation().
GetContainerSolid()
G4VSolid* G4PhantomParameterisation::GetContainerSolid () const inline
Referenced by G4RegularNavigation::ComputeStepSkippingEqualMaterials().
GetMaterial() [1/2]
G4Material * G4PhantomParameterisation::GetMaterial (size_t copyNo) const
Definition at line 165 of file G4PhantomParameterisation.cc.
GetMaterial() [2/2]
G4Material * G4PhantomParameterisation::GetMaterial (size_t nx, size_t ny, size_t nz) const
Definition at line 159 of file G4PhantomParameterisation.cc.
Referenced by DicomIntersectVolume::SetNewValue(), and G4EnergySplitter::SplitEnergyInVolumes().
GetMaterialIndex() [1/2]
size_t G4PhantomParameterisation::GetMaterialIndex (size_t copyNo) const
Definition at line 139 of file G4PhantomParameterisation.cc.
GetMaterialIndex() [2/2]
size_t G4PhantomParameterisation::GetMaterialIndex (size_t nx, size_t ny, size_t nz) const
Definition at line 150 of file G4PhantomParameterisation.cc.
Referenced by DicomPhantomParameterisationColour::ComputeMaterial(), ComputeMaterial(), GetMaterial(), and DicomIntersectVolume::SetNewValue().
GetMaterialIndices()
size_t* G4PhantomParameterisation::GetMaterialIndices () const inline
GetMaterials()
std::vector<G4Material*> G4PhantomParameterisation::GetMaterials () const inline
Referenced by DicomIntersectVolume::SetNewValue().
GetNoVoxel()
size_t G4PhantomParameterisation::GetNoVoxel () const inline
Referenced by G4RegularNavigation::LevelLocate().
GetNoVoxelX()
size_t G4PhantomParameterisation::GetNoVoxelX () const inline
Referenced by G4GMocrenFileSceneHandler::AddSolid(), and DicomIntersectVolume::SetNewValue().
GetNoVoxelY()
size_t G4PhantomParameterisation::GetNoVoxelY () const inline
Referenced by G4GMocrenFileSceneHandler::AddSolid(), and DicomIntersectVolume::SetNewValue().
GetNoVoxelZ()
size_t G4PhantomParameterisation::GetNoVoxelZ () const inline
Referenced by G4GMocrenFileSceneHandler::AddSolid(), and DicomIntersectVolume::SetNewValue().
GetReplicaNo()
G4int G4PhantomParameterisation::GetReplicaNo (const G4ThreeVector & localPoint, const G4ThreeVector & localDir) virtual
Reimplemented in G4PartialPhantomParameterisation.
Definition at line 231 of file G4PhantomParameterisation.cc.
Referenced by G4RegularNavigation::ComputeStep(), G4RegularNavigation::ComputeStepSkippingEqualMaterials(), and G4RegularNavigation::LevelLocate().
GetTranslation()
G4ThreeVector G4PhantomParameterisation::GetTranslation (const G4int copyNo) const
Definition at line 101 of file G4PhantomParameterisation.cc.
Referenced by G4RegularNavigation::ComputeStep(), G4RegularNavigation::ComputeStepSkippingEqualMaterials(), and ComputeTransformation().
GetVoxelHalfX()
G4double G4PhantomParameterisation::GetVoxelHalfX () const inline
Referenced by G4GMocrenFileSceneHandler::AddSolid(), and DicomIntersectVolume::SetNewValue().
GetVoxelHalfY()
G4double G4PhantomParameterisation::GetVoxelHalfY () const inline
Referenced by G4GMocrenFileSceneHandler::AddSolid(), and DicomIntersectVolume::SetNewValue().
GetVoxelHalfZ()
G4double G4PhantomParameterisation::GetVoxelHalfZ () const inline
Referenced by G4GMocrenFileSceneHandler::AddSolid(), and DicomIntersectVolume::SetNewValue().
SetMaterialIndices()
void G4PhantomParameterisation::SetMaterialIndices (size_t * matInd) inline
Referenced by DicomRegularDetectorConstruction::ConstructPhantom(), and DicomPartialDetectorConstruction::ConstructPhantom().
SetMaterials()
void G4PhantomParameterisation::SetMaterials (std::vector< G4Material * > & mates) inline
Referenced by DicomRegularDetectorConstruction::ConstructPhantom(), and DicomPartialDetectorConstruction::ConstructPhantom().
SetNoVoxel()
void G4PhantomParameterisation::SetNoVoxel (size_t nx, size_t ny, size_t nz)
Referenced by DicomRegularDetectorConstruction::ConstructPhantom(), and DicomPartialDetectorConstruction::ConstructPhantom().
SetSkipEqualMaterials()
void G4PhantomParameterisation::SetSkipEqualMaterials (G4bool skip)
Referenced by DicomPartialDetectorConstruction::ConstructPhantom(), and DicomPhantomParameterisationColour::DicomPhantomParameterisationColour().
SetVoxelDimensions()
void G4PhantomParameterisation::SetVoxelDimensions (G4double halfx, G4double halfy, G4double halfz)
Referenced by DicomRegularDetectorConstruction::ConstructPhantom(), and DicomPartialDetectorConstruction::ConstructPhantom().
SkipEqualMaterials()
G4bool G4PhantomParameterisation::SkipEqualMaterials () const
Referenced by G4RegularNavigation::ComputeStepSkippingEqualMaterials().
Field Documentation
bSkipEqualMaterials
G4bool G4PhantomParameterisation::bSkipEqualMaterials protected
Definition at line 196 of file G4PhantomParameterisation.hh.
fContainerSolid
G4VSolid* G4PhantomParameterisation::fContainerSolid protected
Definition at line 186 of file G4PhantomParameterisation.hh.
Referenced by BuildContainerSolid(), CheckVoxelsFillContainer(), and GetReplicaNo().
fContainerWallX
G4double G4PhantomParameterisation::fContainerWallX protected
Definition at line 190 of file G4PhantomParameterisation.hh.
Referenced by BuildContainerSolid(), G4PartialPhantomParameterisation::BuildContainerWalls(), G4PartialPhantomParameterisation::GetReplicaNo(), GetReplicaNo(), G4PartialPhantomParameterisation::GetTranslation(), and GetTranslation().
fContainerWallY
G4double G4PhantomParameterisation::fContainerWallY protected
Definition at line 190 of file G4PhantomParameterisation.hh.
Referenced by BuildContainerSolid(), G4PartialPhantomParameterisation::BuildContainerWalls(), G4PartialPhantomParameterisation::GetReplicaNo(), GetReplicaNo(), G4PartialPhantomParameterisation::GetTranslation(), and GetTranslation().
fContainerWallZ
G4double G4PhantomParameterisation::fContainerWallZ protected
Definition at line 190 of file G4PhantomParameterisation.hh.
Referenced by BuildContainerSolid(), G4PartialPhantomParameterisation::BuildContainerWalls(), G4PartialPhantomParameterisation::GetReplicaNo(), GetReplicaNo(), G4PartialPhantomParameterisation::GetTranslation(), and GetTranslation().
fMaterialIndices
size_t* G4PhantomParameterisation::fMaterialIndices protected
Definition at line 183 of file G4PhantomParameterisation.hh.
Referenced by G4PartialPhantomParameterisation::GetMaterialIndex(), and GetMaterialIndex().
fMaterials
std::vector<G4Material*> G4PhantomParameterisation::fMaterials protected
Definition at line 181 of file G4PhantomParameterisation.hh.
Referenced by G4PartialPhantomParameterisation::ComputeMaterial(), ComputeMaterial(), G4PartialPhantomParameterisation::GetMaterial(), and GetMaterial().
fNoVoxel
size_t G4PhantomParameterisation::fNoVoxel protected
Definition at line 178 of file G4PhantomParameterisation.hh.
Referenced by G4PartialPhantomParameterisation::CheckCopyNo(), and CheckCopyNo().
fNoVoxelX
size_t G4PhantomParameterisation::fNoVoxelX protected
Definition at line 174 of file G4PhantomParameterisation.hh.
Referenced by BuildContainerSolid(), G4PartialPhantomParameterisation::BuildContainerWalls(), CheckVoxelsFillContainer(), ComputeVoxelIndices(), G4PartialPhantomParameterisation::GetMaterialIndex(), GetMaterialIndex(), G4PartialPhantomParameterisation::GetReplicaNo(), and GetReplicaNo().
fNoVoxelXY
size_t G4PhantomParameterisation::fNoVoxelXY protected
Definition at line 176 of file G4PhantomParameterisation.hh.
Referenced by ComputeVoxelIndices(), G4PartialPhantomParameterisation::GetMaterialIndex(), GetMaterialIndex(), and GetReplicaNo().
fNoVoxelY
size_t G4PhantomParameterisation::fNoVoxelY protected
Definition at line 174 of file G4PhantomParameterisation.hh.
Referenced by BuildContainerSolid(), G4PartialPhantomParameterisation::BuildContainerWalls(), CheckVoxelsFillContainer(), G4PartialPhantomParameterisation::ComputeVoxelIndices(), ComputeVoxelIndices(), G4PartialPhantomParameterisation::GetReplicaNo(), and GetReplicaNo().
fNoVoxelZ
size_t G4PhantomParameterisation::fNoVoxelZ protected
Definition at line 174 of file G4PhantomParameterisation.hh.
Referenced by BuildContainerSolid(), G4PartialPhantomParameterisation::BuildContainerWalls(), CheckVoxelsFillContainer(), G4PartialPhantomParameterisation::GetReplicaNo(), and GetReplicaNo().
fVoxelHalfX
G4double G4PhantomParameterisation::fVoxelHalfX protected
Definition at line 172 of file G4PhantomParameterisation.hh.
Referenced by BuildContainerSolid(), G4PartialPhantomParameterisation::BuildContainerWalls(), CheckVoxelsFillContainer(), G4PartialPhantomParameterisation::GetReplicaNo(), GetReplicaNo(), G4PartialPhantomParameterisation::GetTranslation(), and GetTranslation().
fVoxelHalfY
G4double G4PhantomParameterisation::fVoxelHalfY protected
Definition at line 172 of file G4PhantomParameterisation.hh.
Referenced by BuildContainerSolid(), G4PartialPhantomParameterisation::BuildContainerWalls(), CheckVoxelsFillContainer(), G4PartialPhantomParameterisation::GetReplicaNo(), GetReplicaNo(), G4PartialPhantomParameterisation::GetTranslation(), and GetTranslation().
fVoxelHalfZ
G4double G4PhantomParameterisation::fVoxelHalfZ protected
Definition at line 172 of file G4PhantomParameterisation.hh.
Referenced by BuildContainerSolid(), G4PartialPhantomParameterisation::BuildContainerWalls(), CheckVoxelsFillContainer(), G4PartialPhantomParameterisation::GetReplicaNo(), GetReplicaNo(), G4PartialPhantomParameterisation::GetTranslation(), and GetTranslation().
kCarTolerance
G4double G4PhantomParameterisation::kCarTolerance protected
Definition at line 193 of file G4PhantomParameterisation.hh.
Referenced by CheckVoxelsFillContainer(), G4PhantomParameterisation(), G4PartialPhantomParameterisation::GetReplicaNo(), and GetReplicaNo().
The documentation for this class was generated from the following files:
source/geometry/navigation/include/G4PhantomParameterisation.hh
source/geometry/navigation/src/G4PhantomParameterisation.cc