Geant4: CCalSDList Class Reference
CCalSDList Class Reference
#include <CCalSDList.hh>
Public Member Functions
void addCalo (nameType name)
void addTracker (nameType name)
nameType getCaloSDName (int i)
nameType getTrackerSDName (int i)
int getNumberOfCaloSD ()
int getNumberOfTrackerSD ()
Static Public Member Functions
static CCalSDList * getInstance ()
Private Member Functions
CCalSDList ()
~CCalSDList ()
CCalSDList & operator= (CCalSDList &)
Private Attributes
std::vector< nameType > caloSD
std::vector< nameType > trackerSD
Static Private Attributes
static CCalSDList * theList = 0
Detailed Description
Definition at line 40 of file CCalSDList.hh.
Constructor & Destructor Documentation
CCalSDList()
CCalSDList::CCalSDList () private
Definition at line 34 of file CCalSDList.cc.
Referenced by getInstance().
~CCalSDList()
CCalSDList::~CCalSDList () private
Definition at line 35 of file CCalSDList.cc.
Member Function Documentation
addCalo()
void CCalSDList::addCalo (nameType name)
Definition at line 44 of file CCalSDList.cc.
Referenced by CCaloSD::CCaloSD().
addTracker()
void CCalSDList::addTracker (nameType name)
Definition at line 49 of file CCalSDList.cc.
getCaloSDName()
nameType CCalSDList::getCaloSDName (int i)
Definition at line 54 of file CCalSDList.cc.
getInstance()
CCalSDList * CCalSDList::getInstance () static
Definition at line 37 of file CCalSDList.cc.
Referenced by CCaloSD::CCaloSD(), CCalEventAction::initialize(), and CCalStackingAction::initialize().
getNumberOfCaloSD()
int CCalSDList::getNumberOfCaloSD ()
Definition at line 76 of file CCalSDList.cc.
Referenced by getCaloSDName(), CCalEventAction::initialize(), and CCalStackingAction::initialize().
getNumberOfTrackerSD()
int CCalSDList::getNumberOfTrackerSD ()
Definition at line 81 of file CCalSDList.cc.
Referenced by getTrackerSDName().
getTrackerSDName()
nameType CCalSDList::getTrackerSDName (int i)
Definition at line 64 of file CCalSDList.cc.
operator=()
CCalSDList & CCalSDList::operator= (CCalSDList &) private
Definition at line 87 of file CCalSDList.cc.
Field Documentation
caloSD
std::vector<nameType> CCalSDList::caloSD private
Definition at line 61 of file CCalSDList.hh.
Referenced by addCalo(), getCaloSDName(), and getNumberOfCaloSD().
theList
CCalSDList * CCalSDList::theList = 0 static private
Definition at line 60 of file CCalSDList.hh.
Referenced by addCalo(), addTracker(), getCaloSDName(), getInstance(), getNumberOfCaloSD(), getNumberOfTrackerSD(), getTrackerSDName(), and ~CCalSDList().
trackerSD
std::vector<nameType> CCalSDList::trackerSD private
Definition at line 62 of file CCalSDList.hh.
Referenced by addTracker(), getNumberOfTrackerSD(), and getTrackerSDName().
The documentation for this class was generated from the following files:
examples/advanced/composite_calorimeter/include/CCalSDList.hh
examples/advanced/composite_calorimeter/src/CCalSDList.cc