Geant4: G4VFermiBreakUp Class Reference
G4VFermiBreakUp Class Reference abstract
#include <G4VFermiBreakUp.hh>
Public Member Functions
G4VFermiBreakUp ()
virtual ~G4VFermiBreakUp ()
virtual void Initialise ()=0
virtual G4bool IsApplicable (G4int Z, G4int A, G4double mass) const =0
virtual void BreakFragment (G4FragmentVector *results, G4Fragment *theNucleus)=0
Private Member Functions
G4VFermiBreakUp (const G4VFermiBreakUp &right)=delete
const G4VFermiBreakUp & operator= (const G4VFermiBreakUp &right)=delete
G4bool operator== (const G4VFermiBreakUp &right) const =delete
G4bool operator!= (const G4VFermiBreakUp &right) const =delete
Detailed Description
Definition at line 39 of file G4VFermiBreakUp.hh.
Constructor & Destructor Documentation
G4VFermiBreakUp() [1/2]
G4VFermiBreakUp::G4VFermiBreakUp () inline explicit
Definition at line 43 of file G4VFermiBreakUp.hh.
~G4VFermiBreakUp()
virtual G4VFermiBreakUp::~G4VFermiBreakUp () inline virtual
Definition at line 44 of file G4VFermiBreakUp.hh.
G4VFermiBreakUp() [2/2]
G4VFermiBreakUp::G4VFermiBreakUp (const G4VFermiBreakUp & right) private delete
Member Function Documentation
BreakFragment()
virtual void G4VFermiBreakUp::BreakFragment (G4FragmentVector * results, G4Fragment * theNucleus) pure virtual
Implemented in G4FermiBreakUpVI.
Referenced by G4ExcitationHandler::BreakItUp().
Initialise()
virtual void G4VFermiBreakUp::Initialise () pure virtual
Implemented in G4FermiBreakUpVI.
Referenced by G4ExcitationHandler::Initialise().
IsApplicable()
virtual G4bool G4VFermiBreakUp::IsApplicable (G4int Z, G4int A, G4double mass) const pure virtual
Implemented in G4FermiBreakUpVI.
Referenced by G4Evaporation::BreakFragment(), and G4ExcitationHandler::BreakItUp().
operator!=()
G4bool G4VFermiBreakUp::operator!= (const G4VFermiBreakUp & right) const private delete
operator=()
const G4VFermiBreakUp& G4VFermiBreakUp::operator= (const G4VFermiBreakUp & right) private delete
operator==()
G4bool G4VFermiBreakUp::operator== (const G4VFermiBreakUp & right) const private delete
The documentation for this class was generated from the following file:
source/processes/hadronic/models/de_excitation/fermi_breakup/include/G4VFermiBreakUp.hh