Geant4: G4PrimaryVertex Class Reference
G4PrimaryVertex Class Reference
#include <G4PrimaryVertex.hh>
Public Member Functions
void * operator new (size_t)
void operator delete (void *aStackedTrack)
G4PrimaryVertex ()
G4PrimaryVertex (G4double x0, G4double y0, G4double z0, G4double t0)
G4PrimaryVertex (G4ThreeVector xyz0, G4double t0)
virtual ~G4PrimaryVertex ()
G4PrimaryVertex (const G4PrimaryVertex &right)
G4PrimaryVertex & operator= (const G4PrimaryVertex &right)
G4bool operator== (const G4PrimaryVertex &right) const
G4bool operator!= (const G4PrimaryVertex &right) const
G4ThreeVector GetPosition () const
void SetPosition (G4double x0, G4double y0, G4double z0)
G4double GetX0 () const
G4double GetY0 () const
G4double GetZ0 () const
G4double GetT0 () const
void SetT0 (G4double t0)
G4int GetNumberOfParticle () const
void SetPrimary (G4PrimaryParticle *pp)
G4PrimaryParticle * GetPrimary (G4int i=0) const
void SetNext (G4PrimaryVertex *nv)
void ClearNext ()
G4PrimaryVertex * GetNext () const
G4double GetWeight () const
void SetWeight (G4double w)
void SetUserInformation (G4VUserPrimaryVertexInformation *anInfo)
G4VUserPrimaryVertexInformation * GetUserInformation () const
void Print () const
Private Attributes
G4double X0
G4double Y0
G4double Z0
G4double T0
G4PrimaryParticle * theParticle
G4PrimaryParticle * theTail
G4PrimaryVertex * nextVertex
G4PrimaryVertex * tailVertex
G4int numberOfParticle
G4double Weight0
G4VUserPrimaryVertexInformation * userInfo
Detailed Description
Definition at line 47 of file G4PrimaryVertex.hh.
Constructor & Destructor Documentation
G4PrimaryVertex() [1/4]
G4PrimaryVertex::G4PrimaryVertex ()
Definition at line 40 of file G4PrimaryVertex.cc.
Referenced by operator=().
G4PrimaryVertex() [2/4]
G4PrimaryVertex::G4PrimaryVertex (G4double x0, G4double y0, G4double z0, G4double t0)
Definition at line 47 of file G4PrimaryVertex.cc.
G4PrimaryVertex() [3/4]
G4PrimaryVertex::G4PrimaryVertex (G4ThreeVector xyz0, G4double t0)
Definition at line 55 of file G4PrimaryVertex.cc.
~G4PrimaryVertex()
G4PrimaryVertex::~G4PrimaryVertex () virtual
Definition at line 69 of file G4PrimaryVertex.cc.
G4PrimaryVertex() [4/4]
G4PrimaryVertex::G4PrimaryVertex (const G4PrimaryVertex & right)
Definition at line 62 of file G4PrimaryVertex.cc.
Member Function Documentation
ClearNext()
void G4PrimaryVertex::ClearNext () inline
Definition at line 157 of file G4PrimaryVertex.hh.
Referenced by G4Event::~G4Event().
GetNext()
G4PrimaryVertex * G4PrimaryVertex::GetNext () const inline
Definition at line 163 of file G4PrimaryVertex.hh.
Referenced by PrimaryGeneratorAction1::GeneratePrimaries(), G4Event::GetPrimaryVertex(), G4PrimaryTransformer::GimmePrimaries(), operator=(), and G4Event::~G4Event().
GetNumberOfParticle()
G4int G4PrimaryVertex::GetNumberOfParticle () const inline
Definition at line 139 of file G4PrimaryVertex.hh.
Referenced by export_G4PrimaryVertex(), and Par02PrimaryGeneratorAction::GeneratePrimaries().
GetPosition()
G4ThreeVector G4PrimaryVertex::GetPosition () const inline
Definition at line 118 of file G4PrimaryVertex.hh.
Referenced by ExGflashEventAction::EndOfEventAction(), export_G4PrimaryVertex(), G4BlinePrimaryGeneratorAction::GeneratePrimaries(), and G4AdjointPrimaryGeneratorAction::GeneratePrimaries().
GetPrimary()
G4PrimaryParticle * G4PrimaryVertex::GetPrimary (G4int i = 0) const
Definition at line 144 of file G4PrimaryVertex.cc.
Referenced by ExGflashEventAction::EndOfEventAction(), RE01EventAction::EndOfEventAction(), RMC01AnalysisManager::EndOfEventForForwardSimulation(), export_G4PrimaryVertex(), Par02PrimaryGeneratorAction::GeneratePrimaries(), G4AdjointPrimaryGeneratorAction::GeneratePrimaries(), and G4PrimaryTransformer::GenerateTracks().
GetT0()
G4double G4PrimaryVertex::GetT0 () const inline
Definition at line 133 of file G4PrimaryVertex.hh.
Referenced by RE01EventAction::EndOfEventAction(), export_G4PrimaryVertex(), G4BlinePrimaryGeneratorAction::GeneratePrimaries(), and G4PrimaryTransformer::GenerateTracks().
GetUserInformation()
G4VUserPrimaryVertexInformation * G4PrimaryVertex::GetUserInformation () const inline
Definition at line 175 of file G4PrimaryVertex.hh.
GetWeight()
G4double G4PrimaryVertex::GetWeight () const inline
Definition at line 166 of file G4PrimaryVertex.hh.
Referenced by export_G4PrimaryVertex(), and G4PrimaryTransformer::GenerateTracks().
GetX0()
G4double G4PrimaryVertex::GetX0 () const inline
Definition at line 124 of file G4PrimaryVertex.hh.
Referenced by RE01EventAction::EndOfEventAction(), export_G4PrimaryVertex(), and G4PrimaryTransformer::GenerateTracks().
GetY0()
G4double G4PrimaryVertex::GetY0 () const inline
Definition at line 127 of file G4PrimaryVertex.hh.
Referenced by RE01EventAction::EndOfEventAction(), export_G4PrimaryVertex(), and G4PrimaryTransformer::GenerateTracks().
GetZ0()
G4double G4PrimaryVertex::GetZ0 () const inline
Definition at line 130 of file G4PrimaryVertex.hh.
Referenced by RE01EventAction::EndOfEventAction(), export_G4PrimaryVertex(), and G4PrimaryTransformer::GenerateTracks().
operator delete()
void G4PrimaryVertex::operator delete (void * aStackedTrack) inline
Definition at line 113 of file G4PrimaryVertex.hh.
operator new()
void * G4PrimaryVertex::operator new (size_t) inline
Definition at line 104 of file G4PrimaryVertex.hh.
operator!=()
G4bool G4PrimaryVertex::operator!= (const G4PrimaryVertex & right) const
Definition at line 141 of file G4PrimaryVertex.cc.
operator=()
G4PrimaryVertex & G4PrimaryVertex::operator= (const G4PrimaryVertex & right)
Definition at line 94 of file G4PrimaryVertex.cc.
operator==()
G4bool G4PrimaryVertex::operator== (const G4PrimaryVertex & right) const
Definition at line 138 of file G4PrimaryVertex.cc.
Print()
void G4PrimaryVertex::Print (void) const
Definition at line 158 of file G4PrimaryVertex.cc.
Referenced by export_G4PrimaryVertex(), G4PrimaryTransformer::GenerateTracks(), and Print().
SetNext()
void G4PrimaryVertex::SetNext (G4PrimaryVertex * nv) inline
Definition at line 150 of file G4PrimaryVertex.hh.
Referenced by G4Event::AddPrimaryVertex(), and SetNext().
SetPosition()
void G4PrimaryVertex::SetPosition (G4double x0, G4double y0, G4double z0) inline
Definition at line 121 of file G4PrimaryVertex.hh.
Referenced by G4AdjointPrimaryGeneratorAction::GeneratePrimaries().
SetPrimary()
void G4PrimaryVertex::SetPrimary (G4PrimaryParticle * pp) inline
Definition at line 142 of file G4PrimaryVertex.hh.
Referenced by export_G4PrimaryVertex(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), G4BlinePrimaryGeneratorAction::GeneratePrimaries(), G4AdjointPrimaryGeneratorAction::GeneratePrimaries(), PrimaryGenerator::GeneratePrimaryVertex(), DMXParticleSource::GeneratePrimaryVertex(), G4ParticleGun::GeneratePrimaryVertex(), G4HEPEvtInterface::GeneratePrimaryVertex(), G4SingleParticleSource::GeneratePrimaryVertex(), and G4RayShooter::Shoot().
SetT0()
void G4PrimaryVertex::SetT0 (G4double t0) inline
Definition at line 136 of file G4PrimaryVertex.hh.
Referenced by PrimaryGeneratorAction1::GeneratePrimaries(), and G4AdjointPrimaryGeneratorAction::GeneratePrimaries().
SetUserInformation()
void G4PrimaryVertex::SetUserInformation (G4VUserPrimaryVertexInformation * anInfo) inline
Definition at line 172 of file G4PrimaryVertex.hh.
SetWeight()
void G4PrimaryVertex::SetWeight (G4double w) inline
Definition at line 169 of file G4PrimaryVertex.hh.
Referenced by export_G4PrimaryVertex(), and G4AdjointPrimaryGeneratorAction::GeneratePrimaries().
Field Documentation
nextVertex
G4PrimaryVertex* G4PrimaryVertex::nextVertex private
Definition at line 94 of file G4PrimaryVertex.hh.
Referenced by ClearNext(), GetNext(), operator=(), Print(), SetNext(), and ~G4PrimaryVertex().
numberOfParticle
G4int G4PrimaryVertex::numberOfParticle private
Definition at line 96 of file G4PrimaryVertex.hh.
Referenced by GetNumberOfParticle(), GetPrimary(), operator=(), Print(), and SetPrimary().
T0
G4double G4PrimaryVertex::T0 private
Definition at line 91 of file G4PrimaryVertex.hh.
Referenced by GetT0(), operator=(), Print(), and SetT0().
tailVertex
G4PrimaryVertex* G4PrimaryVertex::tailVertex private
Definition at line 95 of file G4PrimaryVertex.hh.
Referenced by ClearNext(), operator=(), SetNext(), and ~G4PrimaryVertex().
theParticle
G4PrimaryParticle* G4PrimaryVertex::theParticle private
Definition at line 92 of file G4PrimaryVertex.hh.
Referenced by GetPrimary(), operator=(), Print(), SetPrimary(), and ~G4PrimaryVertex().
theTail
G4PrimaryParticle* G4PrimaryVertex::theTail private
Definition at line 93 of file G4PrimaryVertex.hh.
Referenced by operator=(), SetPrimary(), and ~G4PrimaryVertex().
userInfo
G4VUserPrimaryVertexInformation* G4PrimaryVertex::userInfo private
Definition at line 98 of file G4PrimaryVertex.hh.
Referenced by GetUserInformation(), operator=(), Print(), SetUserInformation(), and ~G4PrimaryVertex().
Weight0
G4double G4PrimaryVertex::Weight0 private
Definition at line 97 of file G4PrimaryVertex.hh.
Referenced by GetWeight(), operator=(), Print(), and SetWeight().
X0
G4double G4PrimaryVertex::X0 private
Definition at line 88 of file G4PrimaryVertex.hh.
Referenced by GetPosition(), GetX0(), operator=(), Print(), and SetPosition().
Y0
G4double G4PrimaryVertex::Y0 private
Definition at line 89 of file G4PrimaryVertex.hh.
Referenced by GetPosition(), GetY0(), operator=(), Print(), and SetPosition().
Z0
G4double G4PrimaryVertex::Z0 private
Definition at line 90 of file G4PrimaryVertex.hh.
Referenced by GetPosition(), GetZ0(), operator=(), Print(), and SetPosition().
The documentation for this class was generated from the following files:
source/particles/management/include/G4PrimaryVertex.hh
source/particles/management/src/G4PrimaryVertex.cc