Geant4: G4NistElementBuilder Class Reference
G4NistElementBuilder Class Reference
#include <G4NistElementBuilder.hh>
Public Member Functions
G4NistElementBuilder (G4int vb)
~G4NistElementBuilder ()
G4Element * FindElement (G4int Z) const
G4Element * FindOrBuildElement (G4int Z, G4bool buildIsotopes=true)
G4Element * FindOrBuildElement (const G4String &symb, G4bool buildIsotopes=true)
void PrintElement (G4int Z) const
const std::vector< G4String > & GetElementNames () const
G4int GetZ (const G4String &symb) const
G4double GetAtomicMassAmu (const G4String &symb) const
G4double GetAtomicMassAmu (G4int Z) const
G4double GetIsotopeMass (G4int Z, G4int N) const
G4double GetAtomicMass (G4int Z, G4int N) const
G4double GetTotalElectronBindingEnergy (G4int Z) const
G4double GetIsotopeAbundance (G4int Z, G4int N) const
G4int GetNistFirstIsotopeN (G4int Z) const
G4int GetNumberOfNistIsotopes (G4int Z) const
G4int GetMaxNumElements () const
void SetVerbose (G4int)
Private Member Functions
void Initialise ()
void AddElement (const G4String &symbol, G4int Z, G4int NumberOfIsotopes, const G4int &N, const G4double &A, const G4double &sigmaA, const G4double &W)
G4Element * BuildElement (G4int Z)
Private Attributes
G4String elmSymbol [maxNumElements]
G4double atomicMass [maxNumElements]
G4double bindingEnergy [maxNumElements]
G4int nIsotopes [maxNumElements]
G4int nFirstIsotope [maxNumElements]
G4int idxIsotopes [maxNumElements]
G4int elmIndex [maxNumElements]
G4double massIsotopes [maxAbundance]
G4double sigMass [maxAbundance]
G4double relAbundance [maxAbundance]
G4int index
G4int verbose
std::vector< G4String > elmNames
Detailed Description
Definition at line 68 of file G4NistElementBuilder.hh.
Constructor & Destructor Documentation
G4NistElementBuilder()
G4NistElementBuilder::G4NistElementBuilder (G4int vb) explicit
Definition at line 68 of file G4NistElementBuilder.cc.
~G4NistElementBuilder()
G4NistElementBuilder::~G4NistElementBuilder ()
Definition at line 80 of file G4NistElementBuilder.cc.
Member Function Documentation
AddElement()
void G4NistElementBuilder::AddElement (const G4String & symbol, G4int Z, G4int NumberOfIsotopes, const G4int & N, const G4double & A, const G4double & sigmaA, const G4double & W) private
Definition at line 237 of file G4NistElementBuilder.cc.
Referenced by Initialise().
BuildElement()
G4Element * G4NistElementBuilder::BuildElement (G4int Z) private
Definition at line 156 of file G4NistElementBuilder.cc.
Referenced by FindOrBuildElement().
FindElement()
G4Element * G4NistElementBuilder::FindElement (G4int Z) const inline
Definition at line 255 of file G4NistElementBuilder.hh.
Referenced by G4NistManager::FindElement(), and FindOrBuildElement().
FindOrBuildElement() [1/2]
G4Element * G4NistElementBuilder::FindOrBuildElement (const G4String & symb, G4bool buildIsotopes = true)
Definition at line 125 of file G4NistElementBuilder.cc.
FindOrBuildElement() [2/2]
G4Element * G4NistElementBuilder::FindOrBuildElement (G4int Z, G4bool buildIsotopes = true)
Definition at line 105 of file G4NistElementBuilder.cc.
Referenced by G4NistMaterialBuilder::BuildMaterial(), and G4NistManager::FindOrBuildElement().
GetAtomicMass()
G4double G4NistElementBuilder::GetAtomicMass (G4int Z, G4int N) const inline
Definition at line 182 of file G4NistElementBuilder.hh.
Referenced by BuildElement(), G4NistManager::GetAtomicMass(), and PrintElement().
GetAtomicMassAmu() [1/2]
G4double G4NistElementBuilder::GetAtomicMassAmu (const G4String & symb) const
Definition at line 95 of file G4NistElementBuilder.cc.
Referenced by G4NistMaterialBuilder::ConstructNewIdealGasMaterial(), G4NistManager::G4NistManager(), and G4NistManager::GetAtomicMassAmu().
GetAtomicMassAmu() [2/2]
G4double G4NistElementBuilder::GetAtomicMassAmu (G4int Z) const inline
Definition at line 163 of file G4NistElementBuilder.hh.
GetElementNames()
const std::vector< G4String > & G4NistElementBuilder::GetElementNames () const inline
Definition at line 234 of file G4NistElementBuilder.hh.
Referenced by G4NistManager::GetNistElementNames().
GetIsotopeAbundance()
G4double G4NistElementBuilder::GetIsotopeAbundance (G4int Z, G4int N) const inline
Definition at line 207 of file G4NistElementBuilder.hh.
Referenced by G4LENDModel::create_used_target_map(), G4LENDCrossSection::create_used_target_map(), and G4NistManager::GetIsotopeAbundance().
GetIsotopeMass()
G4double G4NistElementBuilder::GetIsotopeMass (G4int Z, G4int N) const inline
Definition at line 170 of file G4NistElementBuilder.hh.
Referenced by G4NistManager::GetIsotopeMass().
GetMaxNumElements()
G4int G4NistElementBuilder::GetMaxNumElements () const inline
Definition at line 241 of file G4NistElementBuilder.hh.
GetNistFirstIsotopeN()
G4int G4NistElementBuilder::GetNistFirstIsotopeN (G4int Z) const inline
Definition at line 219 of file G4NistElementBuilder.hh.
Referenced by G4LENDModel::create_used_target_map(), G4LENDCrossSection::create_used_target_map(), and G4NistManager::GetNistFirstIsotopeN().
GetNumberOfNistIsotopes()
G4int G4NistElementBuilder::GetNumberOfNistIsotopes (G4int Z) const inline
Definition at line 226 of file G4NistElementBuilder.hh.
Referenced by G4LENDModel::create_used_target_map(), G4LENDCrossSection::create_used_target_map(), and G4NistManager::GetNumberOfNistIsotopes().
GetTotalElectronBindingEnergy()
G4double G4NistElementBuilder::GetTotalElectronBindingEnergy (G4int Z) const inline
Definition at line 198 of file G4NistElementBuilder.hh.
Referenced by G4NistManager::GetTotalElectronBindingEnergy().
GetZ()
G4int G4NistElementBuilder::GetZ (const G4String & symb) const
Definition at line 85 of file G4NistElementBuilder.cc.
Referenced by G4NistMaterialBuilder::AddElementByAtomCount(), G4NistMaterialBuilder::AddElementByWeightFraction(), G4NistMaterialBuilder::ConstructNewIdealGasMaterial(), G4NistMaterialBuilder::ConstructNewMaterial(), G4NistManager::GetZ(), and G4NistManager::PrintElement().
Initialise()
void G4NistElementBuilder::Initialise () private
Definition at line 297 of file G4NistElementBuilder.cc.
Referenced by G4NistElementBuilder().
PrintElement()
void G4NistElementBuilder::PrintElement (G4int Z) const
Definition at line 203 of file G4NistElementBuilder.cc.
Referenced by AddElement(), and G4NistManager::PrintElement().
SetVerbose()
void G4NistElementBuilder::SetVerbose (G4int val) inline
Definition at line 248 of file G4NistElementBuilder.hh.
Referenced by G4NistMaterialBuilder::SetVerbose(), and G4NistManager::SetVerbose().
Field Documentation
atomicMass
G4double G4NistElementBuilder::atomicMass[maxNumElements] private
Definition at line 139 of file G4NistElementBuilder.hh.
Referenced by AddElement(), BuildElement(), GetAtomicMassAmu(), and PrintElement().
bindingEnergy
G4double G4NistElementBuilder::bindingEnergy[maxNumElements] private
Definition at line 140 of file G4NistElementBuilder.hh.
Referenced by AddElement(), GetAtomicMass(), GetTotalElectronBindingEnergy(), and Initialise().
elmIndex
G4int G4NistElementBuilder::elmIndex[maxNumElements] private
Definition at line 145 of file G4NistElementBuilder.hh.
Referenced by FindElement(), FindOrBuildElement(), and G4NistElementBuilder().
elmNames
std::vector<G4String> G4NistElementBuilder::elmNames private
Definition at line 154 of file G4NistElementBuilder.hh.
Referenced by GetElementNames(), and Initialise().
elmSymbol
G4String G4NistElementBuilder::elmSymbol[maxNumElements] private
Definition at line 138 of file G4NistElementBuilder.hh.
Referenced by AddElement(), BuildElement(), FindOrBuildElement(), GetAtomicMassAmu(), GetZ(), Initialise(), and PrintElement().
idxIsotopes
G4int G4NistElementBuilder::idxIsotopes[maxNumElements] private
Definition at line 143 of file G4NistElementBuilder.hh.
Referenced by AddElement(), BuildElement(), GetAtomicMass(), GetIsotopeAbundance(), GetIsotopeMass(), and PrintElement().
index
G4int G4NistElementBuilder::index private
Definition at line 151 of file G4NistElementBuilder.hh.
Referenced by AddElement(), and Initialise().
massIsotopes
G4double G4NistElementBuilder::massIsotopes[maxAbundance] private
Definition at line 147 of file G4NistElementBuilder.hh.
Referenced by AddElement(), GetAtomicMass(), and GetIsotopeMass().
nFirstIsotope
G4int G4NistElementBuilder::nFirstIsotope[maxNumElements] private
Definition at line 142 of file G4NistElementBuilder.hh.
Referenced by AddElement(), BuildElement(), G4NistElementBuilder(), GetAtomicMass(), GetIsotopeAbundance(), GetIsotopeMass(), GetNistFirstIsotopeN(), and PrintElement().
nIsotopes
G4int G4NistElementBuilder::nIsotopes[maxNumElements] private
Definition at line 141 of file G4NistElementBuilder.hh.
Referenced by AddElement(), BuildElement(), G4NistElementBuilder(), GetAtomicMass(), GetIsotopeAbundance(), GetIsotopeMass(), GetNumberOfNistIsotopes(), and PrintElement().
relAbundance
G4double G4NistElementBuilder::relAbundance[maxAbundance] private
Definition at line 149 of file G4NistElementBuilder.hh.
Referenced by AddElement(), BuildElement(), G4NistElementBuilder(), GetIsotopeAbundance(), and PrintElement().
sigMass
G4double G4NistElementBuilder::sigMass[maxAbundance] private
Definition at line 148 of file G4NistElementBuilder.hh.
Referenced by AddElement().
verbose
G4int G4NistElementBuilder::verbose private
Definition at line 152 of file G4NistElementBuilder.hh.
Referenced by AddElement(), BuildElement(), Initialise(), and SetVerbose().
The documentation for this class was generated from the following files:
source/materials/include/G4NistElementBuilder.hh
source/materials/src/G4NistElementBuilder.cc