Geant4: G4WeightWindowStore Class Reference
G4WeightWindowStore Class Reference
#include <G4WeightWindowStore.hh>
Public Member Functions
virtual G4double GetLowerWeight (const G4GeometryCell &gCell, G4double partEnergy) const
virtual G4bool IsKnown (const G4GeometryCell &gCell) const
void Clear ()
void SetWorldVolume ()
void SetParallelWorldVolume (G4String paraName)
virtual const G4VPhysicalVolume & GetWorldVolume () const
virtual const G4VPhysicalVolume * GetParallelWorldVolumePointer () const
void AddLowerWeights (const G4GeometryCell &gCell, const std::vector< G4double > &lowerWeights)
void AddUpperEboundLowerWeightPairs (const G4GeometryCell &gCell, const G4UpperEnergyToLowerWeightMap &enWeMap)
void SetGeneralUpperEnergyBounds (const std::set< G4double, std::less< G4double > > &enBounds)
Public Member Functions inherited from G4VWeightWindowStore
G4VWeightWindowStore ()
virtual ~G4VWeightWindowStore ()
Static Public Member Functions
static G4WeightWindowStore * GetInstance ()
static G4WeightWindowStore * GetInstance (const G4String &ParallelWorldName)
Protected Member Functions
G4WeightWindowStore ()
G4WeightWindowStore (const G4String &ParallelWorldName)
~G4WeightWindowStore ()
Private Member Functions
G4bool IsInWorld (const G4VPhysicalVolume &) const
void Error (const G4String &m) const
void SetInternalIterator (const G4GeometryCell &gCell) const
Private Attributes
const G4VPhysicalVolume * fWorldVolume
std::set< G4double, std::less< G4double > > fGeneralUpperEnergyBounds
G4GeometryCellWeight fCellToUpEnBoundLoWePairsMap
G4GeometryCellWeight::const_iterator fCurrentIterator
Static Private Attributes
static G4ThreadLocal G4WeightWindowStore * fInstance = 0
Detailed Description
Definition at line 57 of file G4WeightWindowStore.hh.
Constructor & Destructor Documentation
G4WeightWindowStore() [1/2]
G4WeightWindowStore::G4WeightWindowStore () explicit protected
Definition at line 48 of file G4WeightWindowStore.cc.
Referenced by GetInstance().
G4WeightWindowStore() [2/2]
G4WeightWindowStore::G4WeightWindowStore (const G4String & ParallelWorldName) explicit protected
Definition at line 56 of file G4WeightWindowStore.cc.
~G4WeightWindowStore()
G4WeightWindowStore::~G4WeightWindowStore () protected
Definition at line 63 of file G4WeightWindowStore.cc.
Member Function Documentation
AddLowerWeights()
void G4WeightWindowStore::AddLowerWeights (const G4GeometryCell & gCell, const std::vector< G4double > & lowerWeights)
Definition at line 160 of file G4WeightWindowStore.cc.
Referenced by B01DetectorConstruction::CreateWeightWindowStore(), and B02ImportanceDetectorConstruction::CreateWeightWindowStore().
AddUpperEboundLowerWeightPairs()
void G4WeightWindowStore::AddUpperEboundLowerWeightPairs (const G4GeometryCell & gCell, const G4UpperEnergyToLowerWeightMap & enWeMap)
Definition at line 191 of file G4WeightWindowStore.cc.
Clear()
void G4WeightWindowStore::Clear ()
Definition at line 127 of file G4WeightWindowStore.cc.
Error()
void G4WeightWindowStore::Error (const G4String & m) const private
Definition at line 216 of file G4WeightWindowStore.cc.
Referenced by AddLowerWeights(), AddUpperEboundLowerWeightPairs(), GetLowerWeight(), and SetGeneralUpperEnergyBounds().
GetInstance() [1/2]
G4WeightWindowStore * G4WeightWindowStore::GetInstance (void) static
Definition at line 228 of file G4WeightWindowStore.cc.
Referenced by G4WeightWindowBiasing::ConstructProcess(), B01DetectorConstruction::CreateWeightWindowStore(), and B02ImportanceDetectorConstruction::CreateWeightWindowStore().
GetInstance() [2/2]
G4WeightWindowStore * G4WeightWindowStore::GetInstance (const G4String & ParallelWorldName) static
Definition at line 242 of file G4WeightWindowStore.cc.
GetLowerWeight()
G4double G4WeightWindowStore::GetLowerWeight (const G4GeometryCell & gCell, G4double partEnergy) const virtual
Implements G4VWeightWindowStore.
Definition at line 67 of file G4WeightWindowStore.cc.
GetParallelWorldVolumePointer()
const G4VPhysicalVolume * G4WeightWindowStore::GetParallelWorldVolumePointer () const virtual
Definition at line 152 of file G4WeightWindowStore.cc.
GetWorldVolume()
const G4VPhysicalVolume & G4WeightWindowStore::GetWorldVolume () const virtual
Implements G4VWeightWindowStore.
Definition at line 147 of file G4WeightWindowStore.cc.
IsInWorld()
G4bool G4WeightWindowStore::IsInWorld (const G4VPhysicalVolume & aVolume) const private
Definition at line 106 of file G4WeightWindowStore.cc.
Referenced by IsKnown().
IsKnown()
G4bool G4WeightWindowStore::IsKnown (const G4GeometryCell & gCell) const virtual
Implements G4VWeightWindowStore.
Definition at line 116 of file G4WeightWindowStore.cc.
Referenced by AddLowerWeights(), and AddUpperEboundLowerWeightPairs().
SetGeneralUpperEnergyBounds()
void G4WeightWindowStore::SetGeneralUpperEnergyBounds (const std::set< G4double, std::less< G4double > > & enBounds)
Definition at line 206 of file G4WeightWindowStore.cc.
Referenced by B01DetectorConstruction::CreateWeightWindowStore(), and B02ImportanceDetectorConstruction::CreateWeightWindowStore().
SetInternalIterator()
void G4WeightWindowStore::SetInternalIterator (const G4GeometryCell & gCell) const private
Definition at line 100 of file G4WeightWindowStore.cc.
Referenced by GetLowerWeight(), and IsKnown().
SetParallelWorldVolume()
void G4WeightWindowStore::SetParallelWorldVolume (G4String paraName)
Definition at line 140 of file G4WeightWindowStore.cc.
SetWorldVolume()
void G4WeightWindowStore::SetWorldVolume ()
Definition at line 132 of file G4WeightWindowStore.cc.
Field Documentation
fCellToUpEnBoundLoWePairsMap
G4GeometryCellWeight G4WeightWindowStore::fCellToUpEnBoundLoWePairsMap private
Definition at line 129 of file G4WeightWindowStore.hh.
Referenced by AddLowerWeights(), AddUpperEboundLowerWeightPairs(), Clear(), GetLowerWeight(), IsKnown(), and SetInternalIterator().
fCurrentIterator
G4GeometryCellWeight::const_iterator G4WeightWindowStore::fCurrentIterator mutable private
Definition at line 130 of file G4WeightWindowStore.hh.
Referenced by GetLowerWeight(), IsKnown(), and SetInternalIterator().
fGeneralUpperEnergyBounds
std::set<G4double, std::less<G4double> > G4WeightWindowStore::fGeneralUpperEnergyBounds private
Definition at line 128 of file G4WeightWindowStore.hh.
Referenced by AddLowerWeights(), and SetGeneralUpperEnergyBounds().
fInstance
G4ThreadLocal G4WeightWindowStore * G4WeightWindowStore::fInstance = 0 static private
Definition at line 132 of file G4WeightWindowStore.hh.
Referenced by GetInstance().
fWorldVolume
const G4VPhysicalVolume* G4WeightWindowStore::fWorldVolume private
Definition at line 125 of file G4WeightWindowStore.hh.
Referenced by GetParallelWorldVolumePointer(), GetWorldVolume(), IsInWorld(), SetParallelWorldVolume(), and SetWorldVolume().
The documentation for this class was generated from the following files:
source/geometry/biasing/include/G4WeightWindowStore.hh
source/geometry/biasing/src/G4WeightWindowStore.cc