Geant4: G4NucleusLimits Class Reference
G4NucleusLimits Class Reference
#include <G4NucleusLimits.hh>
Public Member Functions
G4NucleusLimits ()
G4NucleusLimits (G4int aMin1, G4int aMax1, G4int zMin1, G4int zMax1)
~G4NucleusLimits ()
G4int GetAMin () const
G4int GetAMax () const
G4int GetZMin () const
G4int GetZMax () const
Private Attributes
G4int aMin
G4int aMax
G4int zMin
G4int zMax
Friends
std::ostream & operator<< (std::ostream &s, const G4NucleusLimits &q)
Detailed Description
Definition at line 58 of file G4NucleusLimits.hh.
Constructor & Destructor Documentation
G4NucleusLimits() [1/2]
G4NucleusLimits::G4NucleusLimits ()
Definition at line 56 of file G4NucleusLimits.cc.
G4NucleusLimits() [2/2]
G4NucleusLimits::G4NucleusLimits (G4int aMin1, G4int aMax1, G4int zMin1, G4int zMax1)
Definition at line 65 of file G4NucleusLimits.cc.
~G4NucleusLimits()
G4NucleusLimits::~G4NucleusLimits ()
Definition at line 114 of file G4NucleusLimits.cc.
Member Function Documentation
GetAMax()
G4int G4NucleusLimits::GetAMax () const inline
Definition at line 94 of file G4NucleusLimits.hh.
Referenced by G4UIcmdWithNucleusLimits::ConvertToString(), G4RadioactiveDecayBase::IsApplicable(), G4RadioactiveDecay::IsApplicable(), operator<<(), and G4UIcmdWithNucleusLimits::SetDefaultValue().
GetAMin()
G4int G4NucleusLimits::GetAMin () const inline
Definition at line 91 of file G4NucleusLimits.hh.
Referenced by G4UIcmdWithNucleusLimits::ConvertToString(), G4RadioactiveDecayBase::IsApplicable(), G4RadioactiveDecay::IsApplicable(), operator<<(), and G4UIcmdWithNucleusLimits::SetDefaultValue().
GetZMax()
G4int G4NucleusLimits::GetZMax () const inline
Definition at line 100 of file G4NucleusLimits.hh.
Referenced by G4UIcmdWithNucleusLimits::ConvertToString(), G4RadioactiveDecayBase::IsApplicable(), G4RadioactiveDecay::IsApplicable(), operator<<(), and G4UIcmdWithNucleusLimits::SetDefaultValue().
GetZMin()
G4int G4NucleusLimits::GetZMin () const inline
Definition at line 97 of file G4NucleusLimits.hh.
Referenced by G4UIcmdWithNucleusLimits::ConvertToString(), G4RadioactiveDecayBase::IsApplicable(), G4RadioactiveDecay::IsApplicable(), operator<<(), and G4UIcmdWithNucleusLimits::SetDefaultValue().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & s, const G4NucleusLimits & q) friend
Definition at line 118 of file G4NucleusLimits.cc.
Field Documentation
aMax
G4int G4NucleusLimits::aMax private
Definition at line 81 of file G4NucleusLimits.hh.
Referenced by GetAMax().
aMin
G4int G4NucleusLimits::aMin private
Definition at line 80 of file G4NucleusLimits.hh.
Referenced by GetAMin().
zMax
G4int G4NucleusLimits::zMax private
Definition at line 83 of file G4NucleusLimits.hh.
Referenced by GetZMax().
zMin
G4int G4NucleusLimits::zMin private
Definition at line 82 of file G4NucleusLimits.hh.
Referenced by GetZMin().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/radioactive_decay/include/G4NucleusLimits.hh
source/processes/hadronic/models/radioactive_decay/src/G4NucleusLimits.cc