Geant4: G4Orb Class Reference
G4Orb Class Reference
#include <G4Orb.hh>
Public Member Functions
G4Orb (const G4String &pName, G4double pRmax)
~G4Orb ()
G4double GetRadius () const
G4double GetRadialTolerance () const
void SetRadius (G4double newRmax)
G4double GetCubicVolume ()
G4double GetSurfaceArea ()
void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pmin, G4double &pmax) const
EInside Inside (const G4ThreeVector &p) const
G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=G4bool(false), G4bool *validNorm=0, G4ThreeVector *n=0) const
G4double DistanceToOut (const G4ThreeVector &p) const
G4GeometryType GetEntityType () const
G4ThreeVector GetPointOnSurface () const
G4VSolid * Clone () const
std::ostream & StreamInfo (std::ostream &os) const
void DescribeYourselfTo (G4VGraphicsScene &scene) const
G4VisExtent GetExtent () const
G4Polyhedron * CreatePolyhedron () const
G4Orb (__void__ &)
G4Orb (const G4Orb &rhs)
G4Orb & operator= (const G4Orb &rhs)
Public Member Functions inherited from G4CSGSolid
G4CSGSolid (const G4String &pName)
virtual ~G4CSGSolid ()
virtual G4Polyhedron * GetPolyhedron () const
G4CSGSolid (__void__ &)
G4CSGSolid (const G4CSGSolid &rhs)
G4CSGSolid & operator= (const G4CSGSolid &rhs)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
void DumpInfo () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Protected Member Functions
void Initialize ()
Protected Member Functions inherited from G4CSGSolid
G4double GetRadiusInRing (G4double rmin, G4double rmax) const
Protected Member Functions inherited from G4VSolid
void CalculateClippedPolygonExtent (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipCrossSection (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipBetweenSections (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipPolygon (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis) const
Private Attributes
G4double fRmax
G4double halfRmaxTol
G4double sqrRmaxPlusTol
G4double sqrRmaxMinusTol
Additional Inherited Members
Protected Attributes inherited from G4CSGSolid
G4double fCubicVolume
G4double fSurfaceArea
G4bool fRebuildPolyhedron
G4Polyhedron * fpPolyhedron
Protected Attributes inherited from G4VSolid
G4double kCarTolerance
Detailed Description
Definition at line 61 of file G4Orb.hh.
Constructor & Destructor Documentation
G4Orb() [1/3]
G4Orb::G4Orb (const G4String & pName, G4double pRmax)
Definition at line 63 of file G4Orb.cc.
Referenced by Clone().
~G4Orb()
G4Orb::~G4Orb ()
Definition at line 84 of file G4Orb.cc.
G4Orb() [2/3]
G4Orb::G4Orb (__void__ & a)
Definition at line 74 of file G4Orb.cc.
G4Orb() [3/3]
G4Orb::G4Orb (const G4Orb & rhs)
Definition at line 92 of file G4Orb.cc.
Member Function Documentation
BoundingLimits()
void G4Orb::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 160 of file G4Orb.cc.
Referenced by CalculateExtent().
CalculateExtent()
G4bool G4Orb::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pmin, G4double & pmax) const virtual
Implements G4VSolid.
Definition at line 185 of file G4Orb.cc.
Clone()
G4VSolid * G4Orb::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 424 of file G4Orb.cc.
ComputeDimensions()
void G4Orb::ComputeDimensions (G4VPVParameterisation * p, const G4int n, const G4VPhysicalVolume * pRep) virtual
Reimplemented from G4VSolid.
Definition at line 149 of file G4Orb.cc.
CreatePolyhedron()
G4Polyhedron * G4Orb::CreatePolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 470 of file G4Orb.cc.
DescribeYourselfTo()
void G4Orb::DescribeYourselfTo (G4VGraphicsScene & scene) const virtual
Implements G4VSolid.
Definition at line 460 of file G4Orb.cc.
DistanceToIn() [1/2]
G4double G4Orb::DistanceToIn (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 333 of file G4Orb.cc.
DistanceToIn() [2/2]
G4double G4Orb::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Implements G4VSolid.
Definition at line 290 of file G4Orb.cc.
DistanceToOut() [1/2]
G4double G4Orb::DistanceToOut (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 389 of file G4Orb.cc.
DistanceToOut() [2/2]
G4double G4Orb::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcNorm = G4bool(false), G4bool * validNorm = 0, G4ThreeVector * n = 0) const virtual
Implements G4VSolid.
Definition at line 345 of file G4Orb.cc.
GetCubicVolume()
G4double G4Orb::GetCubicVolume () inline virtual
Reimplemented from G4VSolid.
GetEntityType()
G4GeometryType G4Orb::GetEntityType () const virtual
Implements G4VSolid.
Definition at line 415 of file G4Orb.cc.
GetExtent()
G4VisExtent G4Orb::GetExtent () const virtual
Reimplemented from G4VSolid.
Definition at line 465 of file G4Orb.cc.
GetPointOnSurface()
G4ThreeVector G4Orb::GetPointOnSurface () const virtual
Reimplemented from G4VSolid.
Definition at line 451 of file G4Orb.cc.
GetRadialTolerance()
G4double G4Orb::GetRadialTolerance () const inline
Referenced by G4Voxelizer::BuildVoxelLimits().
GetRadius()
G4double G4Orb::GetRadius () const inline
Referenced by BoundingLimits(), CalculateExtent(), export_G4Orb(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Orb_dimensionsWrite(), and G4GDMLWriteSolids::OrbWrite().
GetSurfaceArea()
G4double G4Orb::GetSurfaceArea () inline virtual
Reimplemented from G4VSolid.
Initialize()
void G4Orb::Initialize () protected
Definition at line 126 of file G4Orb.cc.
Referenced by G4Orb().
Inside()
EInside G4Orb::Inside (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 268 of file G4Orb.cc.
Referenced by DistanceToOut().
operator=()
G4Orb & G4Orb::operator= (const G4Orb & rhs)
Definition at line 102 of file G4Orb.cc.
SetRadius()
void G4Orb::SetRadius (G4double newRmax) inline
Referenced by G4GDMLParameterisation::ComputeDimensions(), and export_G4Orb().
StreamInfo()
std::ostream & G4Orb::StreamInfo (std::ostream & os) const virtual
Reimplemented from G4CSGSolid.
Definition at line 433 of file G4Orb.cc.
SurfaceNormal()
G4ThreeVector G4Orb::SurfaceNormal (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 279 of file G4Orb.cc.
Field Documentation
fRmax
G4double G4Orb::fRmax private
Definition at line 140 of file G4Orb.hh.
Referenced by CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetExtent(), GetPointOnSurface(), Initialize(), operator=(), and StreamInfo().
halfRmaxTol
G4double G4Orb::halfRmaxTol private
Definition at line 141 of file G4Orb.hh.
Referenced by DistanceToIn(), DistanceToOut(), Initialize(), and operator=().
sqrRmaxMinusTol
G4double G4Orb::sqrRmaxMinusTol private
Definition at line 142 of file G4Orb.hh.
Referenced by DistanceToIn(), DistanceToOut(), Initialize(), Inside(), and operator=().
sqrRmaxPlusTol
G4double G4Orb::sqrRmaxPlusTol private
Definition at line 142 of file G4Orb.hh.
Referenced by Initialize(), Inside(), and operator=().
The documentation for this class was generated from the following files:
source/geometry/solids/CSG/include/G4Orb.hh
source/geometry/solids/CSG/src/G4Orb.cc