Geant4: G4ParticleChangeForNothing Class Reference
G4ParticleChangeForNothing Class Reference
#include <G4ParticleChangeForNothing.hh>
Public Member Functions
G4ParticleChangeForNothing ()
~G4ParticleChangeForNothing ()
virtual void Initialize (const G4Track &track)
virtual G4Step * UpdateStepForAtRest (G4Step *step)
virtual G4Step * UpdateStepForAlongStep (G4Step *step)
virtual G4Step * UpdateStepForPostStep (G4Step *step)
Public Member Functions inherited from G4VParticleChange
G4VParticleChange ()
virtual ~G4VParticleChange ()
G4bool operator== (const G4VParticleChange &right) const
G4bool operator!= (const G4VParticleChange &right) const
G4double GetTrueStepLength () const
void ProposeTrueStepLength (G4double truePathLength)
G4double GetLocalEnergyDeposit () const
void ProposeLocalEnergyDeposit (G4double anEnergyPart)
G4double GetNonIonizingEnergyDeposit () const
void ProposeNonIonizingEnergyDeposit (G4double anEnergyPart)
G4TrackStatus GetTrackStatus () const
void ProposeTrackStatus (G4TrackStatus status)
G4SteppingControl GetSteppingControl () const
void ProposeSteppingControl (G4SteppingControl StepControlFlag)
G4bool GetFirstStepInVolume () const
G4bool GetLastStepInVolume () const
void ProposeFirstStepInVolume (G4bool flag)
void ProposeLastStepInVolume (G4bool flag)
void Clear ()
void SetNumberOfSecondaries (G4int totSecondaries)
G4int GetNumberOfSecondaries () const
G4Track * GetSecondary (G4int anIndex) const
void AddSecondary (G4Track *aSecondary)
G4double GetWeight () const
G4double GetParentWeight () const
void ProposeWeight (G4double finalWeight)
void ProposeParentWeight (G4double finalWeight)
void SetSecondaryWeightByProcess (G4bool)
G4bool IsSecondaryWeightSetByProcess () const
void SetParentWeightByProcess (G4bool)
G4bool IsParentWeightSetByProcess () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int vLevel)
G4int GetVerboseLevel () const
virtual G4bool CheckIt (const G4Track &)
void ClearDebugFlag ()
void SetDebugFlag ()
G4bool GetDebugFlag () const
Additional Inherited Members
Protected Member Functions inherited from G4VParticleChange
G4VParticleChange (const G4VParticleChange &right)
G4VParticleChange & operator= (const G4VParticleChange &right)
G4Step * UpdateStepInfo (G4Step *Step)
void InitializeTrueStepLength (const G4Track &)
void InitializeLocalEnergyDeposit (const G4Track &)
void InitializeSteppingControl (const G4Track &)
void InitializeParentWeight (const G4Track &)
void InitializeParentGlobalTime (const G4Track &)
void InitializeStatusChange (const G4Track &)
void InitializeSecondaries (const G4Track &)
void InitializeStepInVolumeFlags (const G4Track &)
G4bool CheckSecondary (G4Track &)
G4double GetAccuracyForWarning () const
G4double GetAccuracyForException () const
Protected Attributes inherited from G4VParticleChange
G4TrackFastVector * theListOfSecondaries
G4int theNumberOfSecondaries
G4int theSizeOftheListOfSecondaries
G4TrackStatus theStatusChange
G4SteppingControl theSteppingControlFlag
G4double theLocalEnergyDeposit
G4double theNonIonizingEnergyDeposit
G4double theTrueStepLength
G4bool theFirstStepInVolume
G4bool theLastStepInVolume
G4double theParentWeight
G4bool isParentWeightProposed
G4bool fSetSecondaryWeightByProcess
G4double theParentGlobalTime
G4int verboseLevel
G4bool debugFlag
Static Protected Attributes inherited from G4VParticleChange
static const G4double accuracyForWarning = 1.0e-9
static const G4double accuracyForException = 0.001
Detailed Description
Definition at line 43 of file G4ParticleChangeForNothing.hh.
Constructor & Destructor Documentation
G4ParticleChangeForNothing()
G4ParticleChangeForNothing::G4ParticleChangeForNothing () inline
Definition at line 45 of file G4ParticleChangeForNothing.hh.
~G4ParticleChangeForNothing()
G4ParticleChangeForNothing::~G4ParticleChangeForNothing () inline
Definition at line 46 of file G4ParticleChangeForNothing.hh.
Member Function Documentation
Initialize()
virtual void G4ParticleChangeForNothing::Initialize (const G4Track & track) inline virtual
Reimplemented from G4VParticleChange.
Definition at line 50 of file G4ParticleChangeForNothing.hh.
Referenced by G4ParallelGeometriesLimiterProcess::AlongStepDoIt(), G4BiasingProcessInterface::AlongStepDoIt(), G4BOptnForceCommonTruncatedExp::ApplyFinalStateBiasing(), GB03BOptnSplitOrKillOnBoundary::GenerateBiasingFinalState(), and GB06BOptnSplitAndKillByImportance::GenerateBiasingFinalState().
UpdateStepForAlongStep()
virtual G4Step* G4ParticleChangeForNothing::UpdateStepForAlongStep (G4Step * step) inline virtual
Reimplemented from G4VParticleChange.
Definition at line 56 of file G4ParticleChangeForNothing.hh.
UpdateStepForAtRest()
virtual G4Step* G4ParticleChangeForNothing::UpdateStepForAtRest (G4Step * step) inline virtual
Reimplemented from G4VParticleChange.
Definition at line 55 of file G4ParticleChangeForNothing.hh.
UpdateStepForPostStep()
virtual G4Step* G4ParticleChangeForNothing::UpdateStepForPostStep (G4Step * step) inline virtual
Reimplemented from G4VParticleChange.
Definition at line 57 of file G4ParticleChangeForNothing.hh.
The documentation for this class was generated from the following file:
source/processes/biasing/generic/include/G4ParticleChangeForNothing.hh