Geant4: source/processes/hadronic/models/lend/src/xDataTOM_polynomial.cc File Reference
xDataTOM_polynomial.cc File Reference
#include <string.h>
#include "xDataTOM_private.h"
Functions
int xDataTOM_polynomial_initialize (statusMessageReporting *smr, xDataTOM_polynomial *polynomial, int length, xDataTOM_axes *axes)
int xDataTOM_polynomial_free (xDataTOM_xDataInfo *xDI)
int xDataTOM_polynomial_release (xDataTOM_polynomial *polynomial)
int xDataTOM_polynomial_getData (xDataTOM_polynomial *polynomial, double **data)
int xDataTOM_polynomial_getDataFromXDataInfo (xDataTOM_xDataInfo *xDI, double **data)
Variables
const char * xDataTOM_polynomial_ID = "polynomial"
Function Documentation
xDataTOM_polynomial_free()
int xDataTOM_polynomial_free (xDataTOM_xDataInfo * xDI)
Definition at line 33 of file xDataTOM_polynomial.cc.
Referenced by xDataTOM_releaseElement().
xDataTOM_polynomial_getData()
int xDataTOM_polynomial_getData (xDataTOM_polynomial * polynomial, double ** data)
Definition at line 55 of file xDataTOM_polynomial.cc.
Referenced by xDataTOM_polynomial_getDataFromXDataInfo().
xDataTOM_polynomial_getDataFromXDataInfo()
int xDataTOM_polynomial_getDataFromXDataInfo (xDataTOM_xDataInfo * xDI, double ** data)
Definition at line 63 of file xDataTOM_polynomial.cc.
Referenced by MCGIDI_product_parsePolynomialMultiplicity().
xDataTOM_polynomial_initialize()
int xDataTOM_polynomial_initialize (statusMessageReporting * smr, xDataTOM_polynomial * polynomial, int length, xDataTOM_axes * axes)
Definition at line 19 of file xDataTOM_polynomial.cc.
Referenced by xDataXML_polynomialToTOM().
xDataTOM_polynomial_release()
int xDataTOM_polynomial_release (xDataTOM_polynomial * polynomial)
Definition at line 44 of file xDataTOM_polynomial.cc.
Referenced by xDataTOM_polynomial_free(), and xDataXML_polynomialToTOM().
Variable Documentation
xDataTOM_polynomial_ID
const char* xDataTOM_polynomial_ID = "polynomial"
Definition at line 14 of file xDataTOM_polynomial.cc.
Referenced by xDataTOM_polynomial_free(), xDataTOM_releaseElement(), xDataXML_constructTOM(), and xDataXML_polynomialToTOM().