Geant4: CCalHall Class Reference
CCalHall Class Reference
#include <CCalHall.hh>
Public Member Functions
CCalHall (const G4String &name)
virtual ~CCalHall ()
G4String getMaterial () const
double getDy_2Hall () const
double getDx_2Hall () const
Public Member Functions inherited from CCalDetector
CCalDetector (const G4String &name)
virtual ~CCalDetector ()
void constructHierarchy ()
void construct ()
void addDetector (CCalDetector *)
G4String Name () const
G4String baseFileName () const
G4String File () const
CCalDetector * getDaughter (int i) const
int getNDaughters () const
G4bool operator== (const CCalDetector &left) const
G4bool operator!= (const CCalDetector &left) const
Protected Member Functions
virtual int readFile ()
virtual void constructDaughters ()
Protected Member Functions inherited from CCalDetector
int buildFromFile ()
Private Attributes
G4String genMaterial
double dy_2Hall
double dx_2Hall
Additional Inherited Members
Protected Attributes inherited from CCalDetector
G4String detectorName
G4String fileName
G4String pathName
CCalDetectorTable theDetectorsInside
int constructFlag
Detailed Description
Definition at line 35 of file CCalHall.hh.
Constructor & Destructor Documentation
CCalHall()
CCalHall::CCalHall (const G4String & name)
Definition at line 40 of file CCalHall.cc.
~CCalHall()
CCalHall::~CCalHall () virtual
Definition at line 42 of file CCalHall.cc.
Member Function Documentation
constructDaughters()
void CCalHall::constructDaughters () protected virtual
Implements CCalDetector.
Reimplemented in CCalG4Hall.
Definition at line 75 of file CCalHall.cc.
getDx_2Hall()
double CCalHall::getDx_2Hall () const inline
Definition at line 44 of file CCalHall.hh.
Referenced by CCalG4Hall::constructIn().
getDy_2Hall()
double CCalHall::getDy_2Hall () const inline
Definition at line 43 of file CCalHall.hh.
Referenced by CCalG4Hall::constructIn().
getMaterial()
G4String CCalHall::getMaterial () const inline
Definition at line 42 of file CCalHall.hh.
Referenced by CCalG4Hall::constructIn().
readFile()
int CCalHall::readFile () protected virtual
Implements CCalDetector.
Definition at line 44 of file CCalHall.cc.
Field Documentation
dx_2Hall
double CCalHall::dx_2Hall private
Definition at line 53 of file CCalHall.hh.
Referenced by getDx_2Hall(), and readFile().
dy_2Hall
double CCalHall::dy_2Hall private
Definition at line 52 of file CCalHall.hh.
Referenced by getDy_2Hall(), and readFile().
genMaterial
G4String CCalHall::genMaterial private
Definition at line 51 of file CCalHall.hh.
Referenced by getMaterial(), and readFile().
The documentation for this class was generated from the following files:
examples/advanced/composite_calorimeter/include/CCalHall.hh
examples/advanced/composite_calorimeter/src/CCalHall.cc