Geant4: G4AttDef Class Reference
G4AttDef Class Reference
#include <G4AttDef.hh>
Public Member Functions
G4AttDef (const G4String &name, const G4String &desc, const G4String &category, const G4String &extra, const G4String &valueType)
G4AttDef (const G4String &name, const G4String &desc, const G4String &category, const G4String &extra, const G4TypeKey &typeKey)
G4AttDef ()
virtual ~G4AttDef ()
const G4String & GetName () const
const G4String & GetDesc () const
const G4String & GetCategory () const
const G4String & GetExtra () const
const G4String & GetValueType () const
const G4TypeKey & GetTypeKey () const
void SetName (const G4String &name)
void SetDesc (const G4String &desc)
void SetCategory (const G4String &cat)
void SetExtra (const G4String &extra)
void SetValueType (const G4String &type)
Private Attributes
G4String m_name
The name of the attribute.
G4String m_desc
A short description of the attribute.
G4String m_category
The category (Draw, Physics, PickAction, Association, etc.)
G4String m_extra
Some extra property of the attribute (units, etc.)
G4String m_valueType
The type of the value of the attribute (int, double, vector, etc.)
G4TypeKey m_typeKey
Detailed Description
Definition at line 56 of file G4AttDef.hh.
Constructor & Destructor Documentation
G4AttDef() [1/3]
G4AttDef::G4AttDef (const G4String & name, const G4String & desc, const G4String & category, const G4String & extra, const G4String & valueType) inline
Definition at line 59 of file G4AttDef.hh.
G4AttDef() [2/3]
G4AttDef::G4AttDef (const G4String & name, const G4String & desc, const G4String & category, const G4String & extra, const G4TypeKey & typeKey) inline
Definition at line 69 of file G4AttDef.hh.
G4AttDef() [3/3]
G4AttDef::G4AttDef () inline
Definition at line 80 of file G4AttDef.hh.
~G4AttDef()
virtual G4AttDef::~G4AttDef () inline virtual
Definition at line 81 of file G4AttDef.hh.
Member Function Documentation
GetCategory()
const G4String& G4AttDef::GetCategory () const inline
Definition at line 85 of file G4AttDef.hh.
Referenced by operator<<().
GetDesc()
const G4String& G4AttDef::GetDesc () const inline
Definition at line 84 of file G4AttDef.hh.
Referenced by operator<<().
GetExtra()
const G4String& G4AttDef::GetExtra () const inline
Definition at line 86 of file G4AttDef.hh.
Referenced by G4AttUtils::GetKey(), and operator<<().
GetName()
const G4String& G4AttDef::GetName (void) const inline
Definition at line 83 of file G4AttDef.hh.
GetTypeKey()
const G4TypeKey& G4AttDef::GetTypeKey () const inline
Definition at line 88 of file G4AttDef.hh.
Referenced by G4AttFilterUtils::GetNewFilter().
GetValueType()
const G4String& G4AttDef::GetValueType () const inline
Definition at line 87 of file G4AttDef.hh.
Referenced by G4AttUtils::GetKey(), and operator<<().
SetCategory()
void G4AttDef::SetCategory (const G4String & cat) inline
Definition at line 92 of file G4AttDef.hh.
SetDesc()
void G4AttDef::SetDesc (const G4String & desc) inline
Definition at line 91 of file G4AttDef.hh.
SetExtra()
void G4AttDef::SetExtra (const G4String & extra) inline
Definition at line 93 of file G4AttDef.hh.
SetName()
void G4AttDef::SetName (const G4String & name) inline
Definition at line 90 of file G4AttDef.hh.
SetValueType()
void G4AttDef::SetValueType (const G4String & type) inline
Definition at line 94 of file G4AttDef.hh.
Field Documentation
m_category
G4String G4AttDef::m_category private
The category (Draw, Physics, PickAction, Association, etc.)
Definition at line 102 of file G4AttDef.hh.
Referenced by GetCategory(), and SetCategory().
m_desc
G4String G4AttDef::m_desc private
A short description of the attribute.
Definition at line 100 of file G4AttDef.hh.
Referenced by GetDesc(), and SetDesc().
m_extra
G4String G4AttDef::m_extra private
Some extra property of the attribute (units, etc.)
Definition at line 104 of file G4AttDef.hh.
Referenced by GetExtra(), and SetExtra().
m_name
G4String G4AttDef::m_name private
The name of the attribute.
Definition at line 94 of file G4AttDef.hh.
Referenced by GetName(), and SetName().
m_typeKey
G4TypeKey G4AttDef::m_typeKey private
Definition at line 108 of file G4AttDef.hh.
Referenced by GetTypeKey().
m_valueType
G4String G4AttDef::m_valueType private
The type of the value of the attribute (int, double, vector, etc.)
Definition at line 106 of file G4AttDef.hh.
Referenced by GetValueType(), and SetValueType().
The documentation for this class was generated from the following file:
source/graphics_reps/include/G4AttDef.hh