Geant4: G4RPGInelastic Class Reference
G4RPGInelastic Class Reference
#include <G4RPGInelastic.hh>
Public Member Functions
G4RPGInelastic (const G4String &modelName="RPGInelastic")
virtual ~G4RPGInelastic ()
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)=0
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double, G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void ModelDescription (std::ostream &outFile) const
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Protected Types
enum {
pi0, pip, pim, kp,
km, k0, k0b, pro,
neu, lam, sp, s0,
sm, xi0, xim, om,
ap, an
}
Protected Member Functions
G4double Pmltpc (G4int np, G4int nm, G4int nz, G4int n, G4double b, G4double c)
G4int Factorial (G4int n)
G4bool MarkLeadingStrangeParticle (const G4ReactionProduct &currentParticle, const G4ReactionProduct &targetParticle, G4ReactionProduct &leadParticle)
void SetUpPions (const G4int np, const G4int nm, const G4int nz, G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen)
void GetNormalizationConstant (const G4double availableEnergy, G4double &n, G4double &anpn)
void CalculateMomenta (G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen, const G4HadProjectile *originalIncident, const G4DynamicParticle *originalTarget, G4ReactionProduct &modifiedOriginal, G4Nucleus &targetNucleus, G4ReactionProduct &currentParticle, G4ReactionProduct &targetParticle, G4bool &incidentHasChanged, G4bool &targetHasChanged, G4bool quasiElastic)
void SetUpChange (G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen, G4ReactionProduct &currentParticle, G4ReactionProduct &targetParticle, G4bool &incidentHasChanged)
std::pair< G4int, G4double > interpolateEnergy (G4double ke) const
G4int sampleFlat (std::vector< G4double > sigma) const
void CheckQnums (G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen, G4ReactionProduct &currentParticle, G4ReactionProduct &targetParticle, G4double Q, G4double B, G4double S)
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes
G4RPGFragmentation fragmentation
G4RPGTwoCluster twoCluster
G4RPGPionSuppression pionSuppression
G4RPGStrangeProduction strangeProduction
G4RPGTwoBody twoBody
G4ParticleDefinition * particleDef [18]
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Private Attributes
G4double cache
G4ThreeVector what
Static Private Attributes
static const G4double energyScale [30]
Detailed Description
Definition at line 54 of file G4RPGInelastic.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
pi0
pip
pim
kp
km
k0
k0b
pro
neu
lam
sp
s0
sm
xi0
xim
om
ap
an
Definition at line 122 of file G4RPGInelastic.hh.
Constructor & Destructor Documentation
G4RPGInelastic()
G4RPGInelastic::G4RPGInelastic (const G4String & modelName = "RPGInelastic")
Definition at line 38 of file G4RPGInelastic.cc.
~G4RPGInelastic()
virtual G4RPGInelastic::~G4RPGInelastic () inline virtual
Definition at line 60 of file G4RPGInelastic.hh.
Member Function Documentation
CalculateMomenta()
void G4RPGInelastic::CalculateMomenta (G4FastVector< G4ReactionProduct, 256 > & vec, G4int & vecLen, const G4HadProjectile * originalIncident, const G4DynamicParticle * originalTarget, G4ReactionProduct & modifiedOriginal, G4Nucleus & targetNucleus, G4ReactionProduct & currentParticle, G4ReactionProduct & targetParticle, G4bool & incidentHasChanged, G4bool & targetHasChanged, G4bool quasiElastic) protected
Definition at line 202 of file G4RPGInelastic.cc.
Referenced by G4RPGPiMinusInelastic::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4RPGNeutronInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), and G4RPGAntiKZeroInelastic::ApplyYourself().
CheckQnums()
void G4RPGInelastic::CheckQnums (G4FastVector< G4ReactionProduct, 256 > & vec, G4int & vecLen, G4ReactionProduct & currentParticle, G4ReactionProduct & targetParticle, G4double Q, G4double B, G4double S) protected
Definition at line 545 of file G4RPGInelastic.cc.
Referenced by G4RPGPiMinusInelastic::InitialCollision(), G4RPGPiPlusInelastic::InitialCollision(), G4RPGProtonInelastic::InitialCollision(), and G4RPGNeutronInelastic::InitialCollision().
Factorial()
G4int G4RPGInelastic::Factorial (G4int n) protected
Definition at line 86 of file G4RPGInelastic.cc.
GetNormalizationConstant()
void G4RPGInelastic::GetNormalizationConstant (const G4double availableEnergy, G4double & n, G4double & anpn) protected
Definition at line 158 of file G4RPGInelastic.cc.
Referenced by G4RPGKMinusInelastic::Cascade(), G4RPGAntiLambdaInelastic::Cascade(), G4RPGSigmaPlusInelastic::Cascade(), G4RPGXiMinusInelastic::Cascade(), G4RPGAntiProtonInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGAntiOmegaMinusInelastic::Cascade(), G4RPGOmegaMinusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4RPGKZeroInelastic::Cascade(), G4RPGSigmaMinusInelastic::Cascade(), G4RPGKPlusInelastic::Cascade(), G4RPGLambdaInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), and G4RPGAntiKZeroInelastic::Cascade().
interpolateEnergy()
std::pair< G4int, G4double > G4RPGInelastic::interpolateEnergy (G4double ke) const protected
Definition at line 506 of file G4RPGInelastic.cc.
Referenced by G4RPGNucleonInelastic::GetFSPartTypesForT0(), G4RPGNucleonInelastic::GetFSPartTypesForT1(), G4RPGPionInelastic::GetFSPartTypesForT12(), G4RPGPionInelastic::GetFSPartTypesForT32(), G4RPGNucleonInelastic::GetMultiplicityT0(), G4RPGNucleonInelastic::GetMultiplicityT1(), G4RPGPionInelastic::GetMultiplicityT12(), and G4RPGPionInelastic::GetMultiplicityT32().
MarkLeadingStrangeParticle()
G4bool G4RPGInelastic::MarkLeadingStrangeParticle (const G4ReactionProduct & currentParticle, const G4ReactionProduct & targetParticle, G4ReactionProduct & leadParticle) protected
Definition at line 96 of file G4RPGInelastic.cc.
Referenced by CalculateMomenta().
Pmltpc()
G4double G4RPGInelastic::Pmltpc (G4int np, G4int nm, G4int nz, G4int n, G4double b, G4double c) protected
Definition at line 68 of file G4RPGInelastic.cc.
Referenced by G4RPGKMinusInelastic::Cascade(), G4RPGAntiLambdaInelastic::Cascade(), G4RPGSigmaPlusInelastic::Cascade(), G4RPGXiMinusInelastic::Cascade(), G4RPGAntiProtonInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGAntiOmegaMinusInelastic::Cascade(), G4RPGOmegaMinusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4RPGKZeroInelastic::Cascade(), G4RPGSigmaMinusInelastic::Cascade(), G4RPGKPlusInelastic::Cascade(), G4RPGLambdaInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), and G4RPGAntiKZeroInelastic::Cascade().
sampleFlat()
G4int G4RPGInelastic::sampleFlat (std::vector< G4double > sigma) const protected
Definition at line 523 of file G4RPGInelastic.cc.
Referenced by G4RPGNucleonInelastic::GetFSPartTypesForT0(), G4RPGNucleonInelastic::GetFSPartTypesForT1(), G4RPGPionInelastic::GetFSPartTypesForT12(), G4RPGPionInelastic::GetFSPartTypesForT32(), G4RPGNucleonInelastic::GetMultiplicityT0(), G4RPGNucleonInelastic::GetMultiplicityT1(), G4RPGPionInelastic::GetMultiplicityT12(), and G4RPGPionInelastic::GetMultiplicityT32().
SetUpChange()
void G4RPGInelastic::SetUpChange (G4FastVector< G4ReactionProduct, 256 > & vec, G4int & vecLen, G4ReactionProduct & currentParticle, G4ReactionProduct & targetParticle, G4bool & incidentHasChanged) protected
Definition at line 403 of file G4RPGInelastic.cc.
Referenced by G4RPGPiMinusInelastic::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4RPGNeutronInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), and G4RPGAntiKZeroInelastic::ApplyYourself().
SetUpPions()
void G4RPGInelastic::SetUpPions (const G4int np, const G4int nm, const G4int nz, G4FastVector< G4ReactionProduct, 256 > & vec, G4int & vecLen) protected
Definition at line 126 of file G4RPGInelastic.cc.
Referenced by G4RPGKMinusInelastic::Cascade(), G4RPGAntiLambdaInelastic::Cascade(), G4RPGSigmaPlusInelastic::Cascade(), G4RPGXiMinusInelastic::Cascade(), G4RPGAntiProtonInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGAntiOmegaMinusInelastic::Cascade(), G4RPGOmegaMinusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4RPGKZeroInelastic::Cascade(), G4RPGSigmaMinusInelastic::Cascade(), G4RPGKPlusInelastic::Cascade(), G4RPGLambdaInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), and G4RPGAntiKZeroInelastic::Cascade().
Field Documentation
cache
G4double G4RPGInelastic::cache private
Definition at line 131 of file G4RPGInelastic.hh.
Referenced by CalculateMomenta(), G4RPGInelastic(), and SetUpChange().
energyScale
const G4double G4RPGInelastic::energyScale static private
Initial value:
= {
  0.0,  0.01, 0.013, 0.018, 0.024, 0.032, 0.042, 0.056, 0.075, 0.1,
  0.13, 0.18, 0.24,  0.32,  0.42,  0.56,  0.75,  1.0,   1.3,   1.8,
  2.4,  3.2,  4.2,   5.6,   7.5,   10.0,  13.0,  18.0,  24.0, 32.0 }
Definition at line 134 of file G4RPGInelastic.hh.
Referenced by interpolateEnergy().
fragmentation
G4RPGFragmentation G4RPGInelastic::fragmentation protected
Definition at line 102 of file G4RPGInelastic.hh.
Referenced by CalculateMomenta().
particleDef
G4ParticleDefinition* G4RPGInelastic::particleDef[18] protected
Definition at line 127 of file G4RPGInelastic.hh.
Referenced by G4RPGInelastic(), G4RPGPiMinusInelastic::InitialCollision(), G4RPGPiPlusInelastic::InitialCollision(), G4RPGProtonInelastic::InitialCollision(), G4RPGNeutronInelastic::InitialCollision(), and SetUpChange().
pionSuppression
G4RPGPionSuppression G4RPGInelastic::pionSuppression protected
Definition at line 106 of file G4RPGInelastic.hh.
strangeProduction
G4RPGStrangeProduction G4RPGInelastic::strangeProduction protected
Definition at line 108 of file G4RPGInelastic.hh.
twoBody
G4RPGTwoBody G4RPGInelastic::twoBody protected
Definition at line 110 of file G4RPGInelastic.hh.
Referenced by CalculateMomenta(), G4RPGNeutronInelastic::SlowNeutron(), and G4RPGProtonInelastic::SlowProton().
twoCluster
G4RPGTwoCluster G4RPGInelastic::twoCluster protected
Definition at line 104 of file G4RPGInelastic.hh.
Referenced by CalculateMomenta().
what
G4ThreeVector G4RPGInelastic::what private
Definition at line 132 of file G4RPGInelastic.hh.
Referenced by CalculateMomenta(), and SetUpChange().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/rpg/include/G4RPGInelastic.hh
source/processes/hadronic/models/rpg/src/G4RPGInelastic.cc