Geant4: G4VHadronModelBuilder Class Reference
G4VHadronModelBuilder Class Reference abstract
#include <G4VHadronModelBuilder.hh>
Public Member Functions
G4VHadronModelBuilder (const G4String &name="")
virtual ~G4VHadronModelBuilder ()
G4HadronicInteraction * GetModel ()
const G4String & GetName () const
Protected Member Functions
virtual G4HadronicInteraction * BuildModel ()=0
Private Member Functions
G4VHadronModelBuilder (G4VHadronModelBuilder &)
G4VHadronModelBuilder & operator= (const G4VHadronModelBuilder &right)
Private Attributes
G4HadronicInteraction * model
G4String name
Detailed Description
Definition at line 43 of file G4VHadronModelBuilder.hh.
Constructor & Destructor Documentation
G4VHadronModelBuilder() [1/2]
G4VHadronModelBuilder::G4VHadronModelBuilder (const G4String & name = "")
Definition at line 40 of file G4VHadronModelBuilder.cc.
~G4VHadronModelBuilder()
G4VHadronModelBuilder::~G4VHadronModelBuilder () virtual
Definition at line 44 of file G4VHadronModelBuilder.cc.
G4VHadronModelBuilder() [2/2]
G4VHadronModelBuilder::G4VHadronModelBuilder (G4VHadronModelBuilder &) private
Member Function Documentation
BuildModel()
virtual G4HadronicInteraction* G4VHadronModelBuilder::BuildModel () protected pure virtual
Implemented in G4QGSBuilder, and G4FTFBuilder.
Referenced by GetModel().
GetModel()
G4HadronicInteraction * G4VHadronModelBuilder::GetModel ()
Definition at line 47 of file G4VHadronModelBuilder.cc.
Referenced by G4VHadronPhysics::BuildModel(), G4IonPhysics::ConstructProcess(), G4IonPhysicsPHP::ConstructProcess(), G4IonINCLXXPhysics::ConstructProcess(), and G4IonQMDPhysics::ConstructProcess().
GetName()
const G4String & G4VHadronModelBuilder::GetName (void) const inline
Definition at line 69 of file G4VHadronModelBuilder.hh.
Referenced by G4FTFBuilder::BuildModel(), and G4QGSBuilder::BuildModel().
operator=()
G4VHadronModelBuilder& G4VHadronModelBuilder::operator= (const G4VHadronModelBuilder & right) private
Field Documentation
model
G4HadronicInteraction* G4VHadronModelBuilder::model private
Definition at line 65 of file G4VHadronModelBuilder.hh.
Referenced by GetModel().
name
G4String G4VHadronModelBuilder::name private
Definition at line 66 of file G4VHadronModelBuilder.hh.
Referenced by GetName().
The documentation for this class was generated from the following files:
source/physics_lists/builders/include/G4VHadronModelBuilder.hh
source/physics_lists/builders/src/G4VHadronModelBuilder.cc