Geant4: source/processes/hadronic/models/lend/src/xDataTOM_LegendreSeries.cc File Reference
xDataTOM_LegendreSeries.cc File Reference
#include <string.h>
#include "xDataTOM_private.h"
Functions
int xDataTOM_LegendreSeries_initialize (statusMessageReporting *smr, xDataTOM_LegendreSeries *LegendreSeries, int index, int length, double value)
int xDataTOM_LegendreSeries_release (xDataTOM_LegendreSeries *LegendreSeries)
Function Documentation
xDataTOM_LegendreSeries_initialize()
int xDataTOM_LegendreSeries_initialize (statusMessageReporting * smr, xDataTOM_LegendreSeries * LegendreSeries, int index, int length, double value)
Definition at line 17 of file xDataTOM_LegendreSeries.cc.
Referenced by xDataXML_LegendreSeriesDataToTOM().
xDataTOM_LegendreSeries_release()
int xDataTOM_LegendreSeries_release (xDataTOM_LegendreSeries * LegendreSeries)
Definition at line 30 of file xDataTOM_LegendreSeries.cc.
Referenced by xDataTOM_W_XYs_LegendreSeries_release(), and xDataXML_LegendreSeriesDataToTOM().