Geant4: G4IonisParamMat Class Reference
G4IonisParamMat Class Reference
#include <G4IonisParamMat.hh>
Public Member Functions
G4IonisParamMat (const G4Material *)
~G4IonisParamMat ()
G4double GetMeanExcitationEnergy () const
void SetMeanExcitationEnergy (G4double value)
G4double FindMeanExcitationEnergy (const G4Material *) const
G4double GetLogMeanExcEnergy () const
G4double * GetShellCorrectionVector () const
G4double GetTaul () const
G4double GetPlasmaEnergy () const
G4double GetAdjustmentFactor () const
G4double GetCdensity () const
G4double GetMdensity () const
G4double GetAdensity () const
G4double GetX0density () const
G4double GetX1density () const
G4double GetD0density () const
void SetDensityEffectParameters (G4double cd, G4double md, G4double ad, G4double x0, G4double x1, G4double d0)
void SetDensityEffectParameters (const G4Material *bmat)
G4double DensityCorrection (G4double x)
G4double GetF1fluct () const
G4double GetF2fluct () const
G4double GetEnergy1fluct () const
G4double GetLogEnergy1fluct () const
G4double GetEnergy2fluct () const
G4double GetLogEnergy2fluct () const
G4double GetEnergy0fluct () const
G4double GetRateionexcfluct () const
G4double GetZeffective () const
G4double GetFermiEnergy () const
G4double GetLFactor () const
G4double GetInvA23 () const
void SetBirksConstant (G4double value)
G4double GetBirksConstant () const
void SetMeanEnergyPerIonPair (G4double value)
G4double GetMeanEnergyPerIonPair () const
G4IonisParamMat (__void__ &)
Static Public Member Functions
static G4DensityEffectData * GetDensityEffectData ()
Private Member Functions
void ComputeMeanParameters ()
void ComputeDensityEffect ()
void ComputeFluctModel ()
void ComputeIonParameters ()
G4IonisParamMat & operator= (const G4IonisParamMat &)=delete
G4bool operator== (const G4IonisParamMat &) const =delete
G4bool operator!= (const G4IonisParamMat &) const =delete
G4IonisParamMat (const G4IonisParamMat &)=delete
Private Attributes
const G4Material * fMaterial
G4double fMeanExcitationEnergy
G4double fLogMeanExcEnergy
G4double * fShellCorrectionVector
G4double fTaul
G4double fCdensity
G4double fMdensity
G4double fAdensity
G4double fX0density
G4double fX1density
G4double fD0density
G4double fPlasmaEnergy
G4double fAdjustmentFactor
G4double fF1fluct
G4double fF2fluct
G4double fEnergy1fluct
G4double fLogEnergy1fluct
G4double fEnergy2fluct
G4double fLogEnergy2fluct
G4double fEnergy0fluct
G4double fRateionexcfluct
G4double fZeff
G4double fFermiEnergy
G4double fLfactor
G4double fInvA23
G4double fBirks
G4double fMeanEnergyPerIon
G4double twoln10
Static Private Attributes
static G4DensityEffectData * fDensityData = nullptr
Detailed Description
Definition at line 58 of file G4IonisParamMat.hh.
Constructor & Destructor Documentation
G4IonisParamMat() [1/3]
G4IonisParamMat::G4IonisParamMat (const G4Material * material)
Definition at line 59 of file G4IonisParamMat.cc.
~G4IonisParamMat()
G4IonisParamMat::~G4IonisParamMat ()
Definition at line 119 of file G4IonisParamMat.cc.
G4IonisParamMat() [2/3]
G4IonisParamMat::G4IonisParamMat (__void__ &)
Definition at line 84 of file G4IonisParamMat.cc.
G4IonisParamMat() [3/3]
G4IonisParamMat::G4IonisParamMat (const G4IonisParamMat &) private delete
Member Function Documentation
ComputeDensityEffect()
void G4IonisParamMat::ComputeDensityEffect () private
Definition at line 181 of file G4IonisParamMat.cc.
Referenced by G4IonisParamMat().
ComputeFluctModel()
void G4IonisParamMat::ComputeFluctModel () private
Definition at line 352 of file G4IonisParamMat.cc.
Referenced by G4IonisParamMat(), and SetMeanExcitationEnergy().
ComputeIonParameters()
void G4IonisParamMat::ComputeIonParameters () private
Definition at line 376 of file G4IonisParamMat.cc.
Referenced by G4IonisParamMat().
ComputeMeanParameters()
void G4IonisParamMat::ComputeMeanParameters () private
Definition at line 129 of file G4IonisParamMat.cc.
Referenced by G4IonisParamMat().
DensityCorrection()
G4double G4IonisParamMat::DensityCorrection (G4double x) inline
Definition at line 228 of file G4IonisParamMat.hh.
Referenced by G4mplIonisationWithDeltaModel::ComputeDEDXAhlen(), G4MollerBhabhaModel::ComputeDEDXPerVolume(), G4LindhardSorensenIonModel::ComputeDEDXPerVolume(), G4BetheBlochModel::ComputeDEDXPerVolume(), and G4MuBetheBlochModel::ComputeDEDXPerVolume().
FindMeanExcitationEnergy()
G4double G4IonisParamMat::FindMeanExcitationEnergy (const G4Material * mat) const
Definition at line 492 of file G4IonisParamMat.cc.
Referenced by ComputeMeanParameters().
GetAdensity()
G4double G4IonisParamMat::GetAdensity () const inline
Definition at line 89 of file G4IonisParamMat.hh.
Referenced by G4hBetheBlochModel::BetheBlochFormula(), G4mplIonisationModel::ComputeDEDXAhlen(), G4EmCorrections::DensityCorrection(), and SetDensityEffectParameters().
GetAdjustmentFactor()
G4double G4IonisParamMat::GetAdjustmentFactor () const inline
Definition at line 83 of file G4IonisParamMat.hh.
GetBirksConstant()
G4double G4IonisParamMat::GetBirksConstant () const inline
Definition at line 142 of file G4IonisParamMat.hh.
Referenced by SteppingAction::BirksAttenuation(), G4EmSaturation::DumpBirksCoefficients(), G4EmSaturation::InitialiseBirksCoefficient(), and G4EmSaturation::VisibleEnergyDeposition().
GetCdensity()
G4double G4IonisParamMat::GetCdensity () const inline
Definition at line 85 of file G4IonisParamMat.hh.
Referenced by G4hBetheBlochModel::BetheBlochFormula(), G4mplIonisationModel::ComputeDEDXAhlen(), G4EmCorrections::DensityCorrection(), and SetDensityEffectParameters().
GetD0density()
G4double G4IonisParamMat::GetD0density () const inline
Definition at line 95 of file G4IonisParamMat.hh.
Referenced by SetDensityEffectParameters().
GetDensityEffectData()
G4DensityEffectData * G4IonisParamMat::GetDensityEffectData () static
Definition at line 174 of file G4IonisParamMat.cc.
Referenced by G4NistMessenger::SetNewValue().
GetEnergy0fluct()
G4double G4IonisParamMat::GetEnergy0fluct () const inline
Definition at line 124 of file G4IonisParamMat.hh.
Referenced by G4hImpactIonisation::ElectronicLossFluctuation(), G4RDVeLowEnergyLoss::GetLossWithFluct(), and G4UniversalFluctuation::SampleFluctuations().
GetEnergy1fluct()
G4double G4IonisParamMat::GetEnergy1fluct () const inline
Definition at line 116 of file G4IonisParamMat.hh.
Referenced by G4hImpactIonisation::ElectronicLossFluctuation(), G4RDVeLowEnergyLoss::GetLossWithFluct(), and G4UniversalFluctuation::SampleFluctuations().
GetEnergy2fluct()
G4double G4IonisParamMat::GetEnergy2fluct () const inline
Definition at line 120 of file G4IonisParamMat.hh.
Referenced by G4hImpactIonisation::ElectronicLossFluctuation(), G4RDVeLowEnergyLoss::GetLossWithFluct(), and G4UniversalFluctuation::SampleFluctuations().
GetF1fluct()
G4double G4IonisParamMat::GetF1fluct () const inline
Definition at line 112 of file G4IonisParamMat.hh.
Referenced by G4hImpactIonisation::ElectronicLossFluctuation(), G4RDVeLowEnergyLoss::GetLossWithFluct(), and G4UniversalFluctuation::SampleFluctuations().
GetF2fluct()
G4double G4IonisParamMat::GetF2fluct () const inline
Definition at line 114 of file G4IonisParamMat.hh.
Referenced by G4hImpactIonisation::ElectronicLossFluctuation(), G4RDVeLowEnergyLoss::GetLossWithFluct(), and G4UniversalFluctuation::SampleFluctuations().
GetFermiEnergy()
G4double G4IonisParamMat::GetFermiEnergy () const inline
Definition at line 132 of file G4IonisParamMat.hh.
Referenced by G4ionEffectiveCharge::EffectiveCharge(), and G4IonFluctuations::RelativisticFactor().
GetInvA23()
G4double G4IonisParamMat::GetInvA23 () const inline
Definition at line 136 of file G4IonisParamMat.hh.
Referenced by G4CoulombScattering::MinPrimaryEnergy(), G4WentzelVIRelXSection::SetupKinematic(), and G4WentzelOKandVIxSection::SetupKinematic().
GetLFactor()
G4double G4IonisParamMat::GetLFactor () const inline
Definition at line 134 of file G4IonisParamMat.hh.
GetLogEnergy1fluct()
G4double G4IonisParamMat::GetLogEnergy1fluct () const inline
Definition at line 118 of file G4IonisParamMat.hh.
Referenced by G4hImpactIonisation::ElectronicLossFluctuation(), G4RDVeLowEnergyLoss::GetLossWithFluct(), and G4UniversalFluctuation::SampleFluctuations().
GetLogEnergy2fluct()
G4double G4IonisParamMat::GetLogEnergy2fluct () const inline
Definition at line 122 of file G4IonisParamMat.hh.
Referenced by G4hImpactIonisation::ElectronicLossFluctuation(), G4RDVeLowEnergyLoss::GetLossWithFluct(), and G4UniversalFluctuation::SampleFluctuations().
GetLogMeanExcEnergy()
G4double G4IonisParamMat::GetLogMeanExcEnergy () const inline
Definition at line 73 of file G4IonisParamMat.hh.
Referenced by G4hImpactIonisation::ElectronicLossFluctuation(), G4RDVeLowEnergyLoss::GetLossWithFluct(), and G4UniversalFluctuation::SampleFluctuations().
GetMdensity()
G4double G4IonisParamMat::GetMdensity () const inline
Definition at line 87 of file G4IonisParamMat.hh.
Referenced by G4hBetheBlochModel::BetheBlochFormula(), G4mplIonisationModel::ComputeDEDXAhlen(), G4EmCorrections::DensityCorrection(), and SetDensityEffectParameters().
GetMeanEnergyPerIonPair()
G4double G4IonisParamMat::GetMeanEnergyPerIonPair () const inline
Definition at line 148 of file G4IonisParamMat.hh.
Referenced by G4ElectronIonPair::DumpMeanEnergyPerIonPair(), and G4ElectronIonPair::MeanNumberOfIonsAlongStep().
GetMeanExcitationEnergy()
G4double G4IonisParamMat::GetMeanExcitationEnergy () const inline
Definition at line 67 of file G4IonisParamMat.hh.
Referenced by G4EmCorrections::Bethe(), G4hBetheBlochModel::BetheBlochFormula(), G4hImpactIonisation::BuildPhysicsTable(), G4mplIonisationModel::ComputeDEDXAhlen(), G4mplIonisationWithDeltaModel::ComputeDEDXAhlen(), MyMollerBhabhaModel::ComputeDEDXPerVolume(), G4MollerBhabhaModel::ComputeDEDXPerVolume(), G4LindhardSorensenIonModel::ComputeDEDXPerVolume(), G4BetheBlochModel::ComputeDEDXPerVolume(), G4MuBetheBlochModel::ComputeDEDXPerVolume(), G4Material::CopyPointersOfBaseMaterial(), G4tgbGeometryDumper::DumpMaterial(), G4hImpactIonisation::ElectronicLossFluctuation(), G4RDVeLowEnergyLoss::GetLossWithFluct(), G4GDMLWriteMaterials::MaterialWrite(), G4AtimaEnergyLossModel::MinEnergyCut(), G4LindhardSorensenIonModel::MinEnergyCut(), G4BetheBlochModel::MinEnergyCut(), G4BraggIonModel::MinEnergyCut(), G4MuBetheBlochModel::MinEnergyCut(), G4mplIonisationWithDeltaModel::MinEnergyCut(), operator<<(), G4hImpactIonisation::PrintInfoDefinition(), G4IonFluctuations::RelativisticFactor(), and G4UniversalFluctuation::SampleFluctuations().
GetPlasmaEnergy()
G4double G4IonisParamMat::GetPlasmaEnergy () const inline
Definition at line 81 of file G4IonisParamMat.hh.
GetRateionexcfluct()
G4double G4IonisParamMat::GetRateionexcfluct () const inline
Definition at line 126 of file G4IonisParamMat.hh.
Referenced by G4hImpactIonisation::ElectronicLossFluctuation(), and G4RDVeLowEnergyLoss::GetLossWithFluct().
GetShellCorrectionVector()
G4double* G4IonisParamMat::GetShellCorrectionVector () const inline
Definition at line 75 of file G4IonisParamMat.hh.
Referenced by G4hBetheBlochModel::BetheBlochFormula(), and G4EmCorrections::ShellCorrectionSTD().
GetTaul()
G4double G4IonisParamMat::GetTaul () const inline
Definition at line 77 of file G4IonisParamMat.hh.
Referenced by G4hBetheBlochModel::BetheBlochFormula(), G4hBetheBlochModel::LowEnergyLimit(), and G4EmCorrections::ShellCorrectionSTD().
GetX0density()
G4double G4IonisParamMat::GetX0density () const inline
Definition at line 91 of file G4IonisParamMat.hh.
Referenced by G4hBetheBlochModel::BetheBlochFormula(), G4mplIonisationModel::ComputeDEDXAhlen(), G4EmCorrections::DensityCorrection(), and SetDensityEffectParameters().
GetX1density()
G4double G4IonisParamMat::GetX1density () const inline
Definition at line 93 of file G4IonisParamMat.hh.
Referenced by G4hBetheBlochModel::BetheBlochFormula(), G4mplIonisationModel::ComputeDEDXAhlen(), G4EmCorrections::DensityCorrection(), and SetDensityEffectParameters().
GetZeffective()
G4double G4IonisParamMat::GetZeffective () const inline
Definition at line 130 of file G4IonisParamMat.hh.
Referenced by G4AtimaEnergyLossModel::ComputeDEDXPerVolume(), G4MollerBhabhaModel::ComputeDEDXPerVolume(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), G4AtimaFluctuations::Dispersion(), G4IonFluctuations::Dispersion(), G4ionEffectiveCharge::EffectiveCharge(), and G4GoudsmitSaundersonTable::InitSCPCorrection().
operator!=()
G4bool G4IonisParamMat::operator!= (const G4IonisParamMat &) const private delete
operator=()
G4IonisParamMat& G4IonisParamMat::operator= (const G4IonisParamMat &) private delete
operator==()
G4bool G4IonisParamMat::operator== (const G4IonisParamMat &) const private delete
SetBirksConstant()
void G4IonisParamMat::SetBirksConstant (G4double value) inline
Definition at line 140 of file G4IonisParamMat.hh.
Referenced by OpNoviceDetectorConstruction::Construct(), WLSMaterials::CreateMaterials(), LXeDetectorConstruction::DefineMaterials(), G4EmSaturation::InitialiseBirksCoefficient(), and DetectorConstruction::SetTankMaterial().
SetDensityEffectParameters() [1/2]
void G4IonisParamMat::SetDensityEffectParameters (const G4Material * bmat)
Definition at line 468 of file G4IonisParamMat.cc.
SetDensityEffectParameters() [2/2]
void G4IonisParamMat::SetDensityEffectParameters (G4double cd, G4double md, G4double ad, G4double x0, G4double x1, G4double d0)
Definition at line 447 of file G4IonisParamMat.cc.
SetMeanEnergyPerIonPair()
void G4IonisParamMat::SetMeanEnergyPerIonPair (G4double value) inline
Definition at line 146 of file G4IonisParamMat.hh.
Referenced by G4ElectronIonPair::FindG4MeanEnergyPerIonPair(), and DetectorConstruction::SetPairEnergy().
SetMeanExcitationEnergy()
void G4IonisParamMat::SetMeanExcitationEnergy (G4double value)
Definition at line 420 of file G4IonisParamMat.cc.
Referenced by G4Material::CopyPointersOfBaseMaterial(), G4HumanPhantomMaterial::DefineMaterials(), BrachyMaterial::DefineMaterials(), doiPETDetectorConstruction::DefineMaterials(), DetectorConstruction::DefineMaterials(), ExN03DetectorConstruction::DefineMaterials(), G4tgbMaterialMgr::FindOrBuildG4Material(), and G4GDMLReadMaterials::MaterialRead().
Field Documentation
fAdensity
G4double G4IonisParamMat::fAdensity private
Definition at line 189 of file G4IonisParamMat.hh.
Referenced by ComputeDensityEffect(), DensityCorrection(), G4IonisParamMat(), GetAdensity(), and SetDensityEffectParameters().
fAdjustmentFactor
G4double G4IonisParamMat::fAdjustmentFactor private
Definition at line 195 of file G4IonisParamMat.hh.
Referenced by ComputeDensityEffect(), G4IonisParamMat(), and GetAdjustmentFactor().
fBirks
G4double G4IonisParamMat::fBirks private
Definition at line 214 of file G4IonisParamMat.hh.
Referenced by G4IonisParamMat(), GetBirksConstant(), and SetBirksConstant().
fCdensity
G4double G4IonisParamMat::fCdensity private
Definition at line 187 of file G4IonisParamMat.hh.
Referenced by ComputeDensityEffect(), DensityCorrection(), G4IonisParamMat(), GetCdensity(), SetDensityEffectParameters(), and SetMeanExcitationEnergy().
fD0density
G4double G4IonisParamMat::fD0density private
Definition at line 192 of file G4IonisParamMat.hh.
Referenced by ComputeDensityEffect(), DensityCorrection(), G4IonisParamMat(), GetD0density(), and SetDensityEffectParameters().
fDensityData
G4DensityEffectData * G4IonisParamMat::fDensityData = nullptr static private
Definition at line 219 of file G4IonisParamMat.hh.
Referenced by ComputeDensityEffect(), FindMeanExcitationEnergy(), G4IonisParamMat(), GetDensityEffectData(), and ~G4IonisParamMat().
fEnergy0fluct
G4double G4IonisParamMat::fEnergy0fluct private
Definition at line 204 of file G4IonisParamMat.hh.
Referenced by ComputeFluctModel(), G4IonisParamMat(), and GetEnergy0fluct().
fEnergy1fluct
G4double G4IonisParamMat::fEnergy1fluct private
Definition at line 200 of file G4IonisParamMat.hh.
Referenced by ComputeFluctModel(), G4IonisParamMat(), and GetEnergy1fluct().
fEnergy2fluct
G4double G4IonisParamMat::fEnergy2fluct private
Definition at line 202 of file G4IonisParamMat.hh.
Referenced by ComputeFluctModel(), G4IonisParamMat(), and GetEnergy2fluct().
fF1fluct
G4double G4IonisParamMat::fF1fluct private
Definition at line 198 of file G4IonisParamMat.hh.
Referenced by ComputeFluctModel(), G4IonisParamMat(), and GetF1fluct().
fF2fluct
G4double G4IonisParamMat::fF2fluct private
Definition at line 199 of file G4IonisParamMat.hh.
Referenced by ComputeFluctModel(), G4IonisParamMat(), and GetF2fluct().
fFermiEnergy
G4double G4IonisParamMat::fFermiEnergy private
Definition at line 209 of file G4IonisParamMat.hh.
Referenced by ComputeIonParameters(), G4IonisParamMat(), and GetFermiEnergy().
fInvA23
G4double G4IonisParamMat::fInvA23 private
Definition at line 211 of file G4IonisParamMat.hh.
Referenced by ComputeIonParameters(), G4IonisParamMat(), and GetInvA23().
fLfactor
G4double G4IonisParamMat::fLfactor private
Definition at line 210 of file G4IonisParamMat.hh.
Referenced by ComputeIonParameters(), G4IonisParamMat(), and GetLFactor().
fLogEnergy1fluct
G4double G4IonisParamMat::fLogEnergy1fluct private
Definition at line 201 of file G4IonisParamMat.hh.
Referenced by ComputeFluctModel(), G4IonisParamMat(), and GetLogEnergy1fluct().
fLogEnergy2fluct
G4double G4IonisParamMat::fLogEnergy2fluct private
Definition at line 203 of file G4IonisParamMat.hh.
Referenced by ComputeFluctModel(), G4IonisParamMat(), and GetLogEnergy2fluct().
fLogMeanExcEnergy
G4double G4IonisParamMat::fLogMeanExcEnergy private
Definition at line 182 of file G4IonisParamMat.hh.
Referenced by ComputeFluctModel(), ComputeMeanParameters(), G4IonisParamMat(), GetLogMeanExcEnergy(), and SetMeanExcitationEnergy().
fMaterial
const G4Material* G4IonisParamMat::fMaterial private
Definition at line 178 of file G4IonisParamMat.hh.
Referenced by ComputeDensityEffect(), ComputeFluctModel(), ComputeIonParameters(), ComputeMeanParameters(), SetDensityEffectParameters(), and SetMeanExcitationEnergy().
fMdensity
G4double G4IonisParamMat::fMdensity private
Definition at line 188 of file G4IonisParamMat.hh.
Referenced by ComputeDensityEffect(), DensityCorrection(), G4IonisParamMat(), GetMdensity(), and SetDensityEffectParameters().
fMeanEnergyPerIon
G4double G4IonisParamMat::fMeanEnergyPerIon private
Definition at line 216 of file G4IonisParamMat.hh.
Referenced by G4IonisParamMat(), GetMeanEnergyPerIonPair(), and SetMeanEnergyPerIonPair().
fMeanExcitationEnergy
G4double G4IonisParamMat::fMeanExcitationEnergy private
Definition at line 181 of file G4IonisParamMat.hh.
Referenced by ComputeDensityEffect(), ComputeMeanParameters(), G4IonisParamMat(), GetMeanExcitationEnergy(), and SetMeanExcitationEnergy().
fPlasmaEnergy
G4double G4IonisParamMat::fPlasmaEnergy private
Definition at line 194 of file G4IonisParamMat.hh.
Referenced by ComputeDensityEffect(), G4IonisParamMat(), and GetPlasmaEnergy().
fRateionexcfluct
G4double G4IonisParamMat::fRateionexcfluct private
Definition at line 205 of file G4IonisParamMat.hh.
Referenced by ComputeFluctModel(), G4IonisParamMat(), and GetRateionexcfluct().
fShellCorrectionVector
G4double* G4IonisParamMat::fShellCorrectionVector private
Definition at line 183 of file G4IonisParamMat.hh.
Referenced by ComputeMeanParameters(), GetShellCorrectionVector(), and ~G4IonisParamMat().
fTaul
G4double G4IonisParamMat::fTaul private
Definition at line 184 of file G4IonisParamMat.hh.
Referenced by ComputeMeanParameters(), G4IonisParamMat(), and GetTaul().
fX0density
G4double G4IonisParamMat::fX0density private
Definition at line 190 of file G4IonisParamMat.hh.
Referenced by ComputeDensityEffect(), DensityCorrection(), G4IonisParamMat(), GetX0density(), SetDensityEffectParameters(), and SetMeanExcitationEnergy().
fX1density
G4double G4IonisParamMat::fX1density private
Definition at line 191 of file G4IonisParamMat.hh.
Referenced by ComputeDensityEffect(), DensityCorrection(), G4IonisParamMat(), GetX1density(), SetDensityEffectParameters(), and SetMeanExcitationEnergy().
fZeff
G4double G4IonisParamMat::fZeff private
Definition at line 208 of file G4IonisParamMat.hh.
Referenced by ComputeIonParameters(), G4IonisParamMat(), and GetZeffective().
twoln10
G4double G4IonisParamMat::twoln10 private
Definition at line 220 of file G4IonisParamMat.hh.
Referenced by ComputeDensityEffect(), DensityCorrection(), G4IonisParamMat(), SetDensityEffectParameters(), and SetMeanExcitationEnergy().
The documentation for this class was generated from the following files:
source/materials/include/G4IonisParamMat.hh
source/materials/src/G4IonisParamMat.cc