Geant4: G4Allocator< Type > Class Template Reference
G4Allocator< Type > Class Template Reference
#include <G4Allocator.hh>
Data Structures
struct rebind
Public Types
typedef Type value_type
typedef size_t size_type
typedef ptrdiff_t difference_type
typedef Type * pointer
typedef Type & reference
Public Member Functions
G4Allocator () throw ()
~G4Allocator () throw ()
Type * MallocSingle ()
void FreeSingle (Type *anElement)
void ResetStorage ()
size_t GetAllocatedSize () const
int GetNoPages () const
size_t GetPageSize () const
void IncreasePageSize (unsigned int sz)
const char * GetPoolType () const
template<class U >
G4Allocator (const G4Allocator< U > &right) throw ()
pointer address (reference r) const
const_pointer address (const_reference r) const
pointer allocate (size_type n, void *=0)
void deallocate (pointer p, size_type n)
void construct (pointer p, const Type &val)
void destroy (pointer p)
size_type max_size () const throw ()
Public Member Functions inherited from G4AllocatorBase
G4AllocatorBase ()
virtual ~G4AllocatorBase ()
Data Fields
const typedef Type * const_pointer
const typedef Type & const_reference
G4AllocatorPool mem
Private Attributes
const char * tname
Detailed Description
template<class Type>
class G4Allocator< Type >
Definition at line 66 of file G4Allocator.hh.
Member Typedef Documentation
difference_type
template<class Type> typedef ptrdiff_t G4Allocator< Type >::difference_type
Definition at line 107 of file G4Allocator.hh.
pointer
template<class Type> typedef Type* G4Allocator< Type >::pointer
Definition at line 108 of file G4Allocator.hh.
reference
template<class Type> typedef Type& G4Allocator< Type >::reference
Definition at line 110 of file G4Allocator.hh.
size_type
template<class Type> typedef size_t G4Allocator< Type >::size_type
Definition at line 106 of file G4Allocator.hh.
value_type
template<class Type> typedef Type G4Allocator< Type >::value_type
Definition at line 105 of file G4Allocator.hh.
Constructor & Destructor Documentation
G4Allocator() [1/2]
template<class Type > G4Allocator< Type >::G4Allocator () throw ()
Definition at line 181 of file G4Allocator.hh.
~G4Allocator()
template<class Type > G4Allocator< Type >::~G4Allocator () throw ()
Definition at line 192 of file G4Allocator.hh.
G4Allocator() [2/2]
template<class Type> template<class U > G4Allocator< Type >::G4Allocator (const G4Allocator< U > & right) throw () inline
Definition at line 113 of file G4Allocator.hh.
Member Function Documentation
address() [1/2]
template<class Type> const_pointer G4Allocator< Type >::address (const_reference r) const inline
Definition at line 118 of file G4Allocator.hh.
address() [2/2]
template<class Type> pointer G4Allocator< Type >::address (reference r) const inline
Definition at line 117 of file G4Allocator.hh.
allocate()
template<class Type> pointer G4Allocator< Type >::allocate (size_type n, void * = 0) inline
Definition at line 121 of file G4Allocator.hh.
construct()
template<class Type> void G4Allocator< Type >::construct (pointer p, const Type & val) inline
Definition at line 143 of file G4Allocator.hh.
deallocate()
template<class Type> void G4Allocator< Type >::deallocate (pointer p, size_type n) inline
Definition at line 132 of file G4Allocator.hh.
destroy()
template<class Type> void G4Allocator< Type >::destroy (pointer p) inline
Definition at line 145 of file G4Allocator.hh.
FreeSingle()
template<class Type> void G4Allocator< Type >::FreeSingle (Type * anElement) inline
Definition at line 211 of file G4Allocator.hh.
Referenced by G4Allocator< G4KDNode< PointT > >::deallocate(), G4DCofThisEvent::operator delete(), G4GeomSplitter< T >::operator delete(), G4TDigiCollection< T >::operator delete(), and G4KDNodeCopy< PointCopyT >::operator delete().
GetAllocatedSize()
template<class Type > size_t G4Allocator< Type >::GetAllocatedSize () const inline virtual
Implements G4AllocatorBase.
Definition at line 235 of file G4Allocator.hh.
GetNoPages()
template<class Type > int G4Allocator< Type >::GetNoPages () const inline virtual
Implements G4AllocatorBase.
Definition at line 245 of file G4Allocator.hh.
GetPageSize()
template<class Type > size_t G4Allocator< Type >::GetPageSize () const inline virtual
Implements G4AllocatorBase.
Definition at line 255 of file G4Allocator.hh.
GetPoolType()
template<class Type > const char * G4Allocator< Type >::GetPoolType () const inline virtual
Implements G4AllocatorBase.
Definition at line 276 of file G4Allocator.hh.
IncreasePageSize()
template<class Type > void G4Allocator< Type >::IncreasePageSize (unsigned int sz) inline virtual
Implements G4AllocatorBase.
Definition at line 265 of file G4Allocator.hh.
MallocSingle()
template<class Type > Type * G4Allocator< Type >::MallocSingle () inline
Definition at line 201 of file G4Allocator.hh.
Referenced by G4Allocator< G4KDNode< PointT > >::allocate(), G4DCofThisEvent::operator new(), G4GeomSplitter< T >::operator new(), G4TDigiCollection< T >::operator new(), G4KDTree::operator new(), G4KDNode< PointT >::operator new(), and G4KDNodeCopy< PointCopyT >::operator new().
max_size()
template<class Type> size_type G4Allocator< Type >::max_size () const throw () inline
Definition at line 148 of file G4Allocator.hh.
ResetStorage()
template<class Type > void G4Allocator< Type >::ResetStorage () inline virtual
Implements G4AllocatorBase.
Definition at line 222 of file G4Allocator.hh.
Field Documentation
const_pointer
template<class Type> const typedef Type* G4Allocator< Type >::const_pointer
Definition at line 109 of file G4Allocator.hh.
const_reference
template<class Type> const typedef Type& G4Allocator< Type >::const_reference
Definition at line 111 of file G4Allocator.hh.
mem
template<class Type> G4AllocatorPool G4Allocator< Type >::mem
Definition at line 159 of file G4Allocator.hh.
tname
template<class Type> const char* G4Allocator< Type >::tname private
Definition at line 164 of file G4Allocator.hh.
The documentation for this class was generated from the following file:
source/global/management/include/G4Allocator.hh