Geant4: G4PSCellFlux Class Reference
G4PSCellFlux Class Reference
#include <G4PSCellFlux.hh>
Public Member Functions
G4PSCellFlux (G4String name, G4int depth=0)
G4PSCellFlux (G4String name, const G4String &unit, G4int depth=0)
virtual ~G4PSCellFlux ()
void Weighted (G4bool flg=true)
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
virtual void SetUnit (const G4String &unit)
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Protected Member Functions
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
virtual G4double ComputeVolume (G4Step *, G4int idx)
virtual void DefineUnitAndCategory ()
Protected Member Functions inherited from G4VPrimitiveScorer
virtual G4int GetIndex (G4Step *)
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Private Attributes
G4int HCID
G4THitsMap< G4double > * EvtMap
G4bool weighted
Additional Inherited Members
Protected Attributes inherited from G4VPrimitiveScorer
G4String primitiveName
G4MultiFunctionalDetector * detector
G4VSDFilter * filter
G4int verboseLevel
G4int indexDepth
G4String unitName
G4double unitValue
G4int fNi
G4int fNj
G4int fNk
Detailed Description
Definition at line 56 of file G4PSCellFlux.hh.
Constructor & Destructor Documentation
G4PSCellFlux() [1/2]
G4PSCellFlux::G4PSCellFlux (G4String name, G4int depth = 0)
Definition at line 54 of file G4PSCellFlux.cc.
G4PSCellFlux() [2/2]
G4PSCellFlux::G4PSCellFlux (G4String name, const G4String & unit, G4int depth = 0)
Definition at line 62 of file G4PSCellFlux.cc.
~G4PSCellFlux()
G4PSCellFlux::~G4PSCellFlux () virtual
Definition at line 69 of file G4PSCellFlux.cc.
Member Function Documentation
clear()
void G4PSCellFlux::clear (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 101 of file G4PSCellFlux.cc.
ComputeVolume()
G4double G4PSCellFlux::ComputeVolume (G4Step * aStep, G4int idx) protected virtual
Reimplemented in G4PSCellFluxForCylinder3D.
Definition at line 134 of file G4PSCellFlux.cc.
Referenced by ProcessHits().
DefineUnitAndCategory()
void G4PSCellFlux::DefineUnitAndCategory () protected virtual
Definition at line 127 of file G4PSCellFlux.cc.
Referenced by G4PSCellFlux().
DrawAll()
void G4PSCellFlux::DrawAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 105 of file G4PSCellFlux.cc.
EndOfEvent()
void G4PSCellFlux::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 98 of file G4PSCellFlux.cc.
Initialize()
void G4PSCellFlux::Initialize (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 90 of file G4PSCellFlux.cc.
PrintAll()
void G4PSCellFlux::PrintAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 108 of file G4PSCellFlux.cc.
ProcessHits()
G4bool G4PSCellFlux::ProcessHits (G4Step * aStep, G4TouchableHistory *) protected virtual
Implements G4VPrimitiveScorer.
Definition at line 72 of file G4PSCellFlux.cc.
SetUnit()
void G4PSCellFlux::SetUnit (const G4String & unit) virtual
Definition at line 122 of file G4PSCellFlux.cc.
Referenced by G4PSCellFlux(), and G4PSCellFlux3D::G4PSCellFlux3D().
Weighted()
void G4PSCellFlux::Weighted (G4bool flg = true) inline
Definition at line 63 of file G4PSCellFlux.hh.
Field Documentation
EvtMap
G4THitsMap<G4double>* G4PSCellFlux::EvtMap private
Definition at line 85 of file G4PSCellFlux.hh.
Referenced by clear(), Initialize(), PrintAll(), and ProcessHits().
HCID
G4int G4PSCellFlux::HCID private
Definition at line 84 of file G4PSCellFlux.hh.
Referenced by Initialize().
weighted
G4bool G4PSCellFlux::weighted private
Definition at line 86 of file G4PSCellFlux.hh.
Referenced by ProcessHits(), and Weighted().
The documentation for this class was generated from the following files:
source/digits_hits/scorer/include/G4PSCellFlux.hh
source/digits_hits/scorer/src/G4PSCellFlux.cc