Geant4: G4HadronElasticPhysics Class Reference
G4HadronElasticPhysics Class Reference
#include <G4HadronElasticPhysics.hh>
Public Member Functions
G4HadronElasticPhysics (G4int ver=0, const G4String &nam="hElasticWEL_CHIPS_XS")
virtual ~G4HadronElasticPhysics ()
void ConstructParticle () override
void ConstructProcess () override
G4HadronicProcess * GetElasticProcess (const G4ParticleDefinition *part) const
G4HadronElastic * GetElasticModel (const G4ParticleDefinition *part) const
G4HadronicProcess * GetNeutronProcess () const
G4HadronElastic * GetNeutronModel () const
void AddXSection (const G4ParticleDefinition *, G4VCrossSectionDataSet *) const
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Protected Attributes
G4int verbose
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Private Member Functions
G4HadronElasticPhysics (G4HadronElasticPhysics &)=delete
G4HadronElasticPhysics & operator= (const G4HadronElasticPhysics &right)=delete
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 54 of file G4HadronElasticPhysics.hh.
Constructor & Destructor Documentation
G4HadronElasticPhysics() [1/2]
G4HadronElasticPhysics::G4HadronElasticPhysics (G4int ver = 0, const G4String & nam = "hElasticWEL_CHIPS_XS") explicit
Definition at line 79 of file G4HadronElasticPhysics.cc.
~G4HadronElasticPhysics()
G4HadronElasticPhysics::~G4HadronElasticPhysics () virtual
Definition at line 88 of file G4HadronElasticPhysics.cc.
G4HadronElasticPhysics() [2/2]
G4HadronElasticPhysics::G4HadronElasticPhysics (G4HadronElasticPhysics &) private delete
Member Function Documentation
AddXSection()
void G4HadronElasticPhysics::AddXSection (const G4ParticleDefinition * part, G4VCrossSectionDataSet * cross) const
Definition at line 291 of file G4HadronElasticPhysics.cc.
ConstructParticle()
void G4HadronElasticPhysics::ConstructParticle (void) override virtual
Implements G4VPhysicsConstructor.
Definition at line 91 of file G4HadronElasticPhysics.cc.
ConstructProcess()
void G4HadronElasticPhysics::ConstructProcess (void) override virtual
Implements G4VPhysicsConstructor.
Reimplemented in G4HadronElasticPhysicsLEND, G4HadronElasticPhysicsHP, G4HadronElasticPhysicsXS, and G4HadronElasticPhysicsPHP.
Definition at line 104 of file G4HadronElasticPhysics.cc.
Referenced by HadronElasticPhysicsHP::ConstructProcess(), G4HadronElasticPhysicsPHP::ConstructProcess(), G4HadronElasticPhysicsHP::ConstructProcess(), G4HadronElasticPhysicsXS::ConstructProcess(), and G4HadronElasticPhysicsLEND::ConstructProcess().
GetElasticModel()
G4HadronElastic * G4HadronElasticPhysics::GetElasticModel (const G4ParticleDefinition * part) const
Definition at line 270 of file G4HadronElasticPhysics.cc.
Referenced by G4HadronElasticPhysicsPHP::ConstructProcess(), G4HadronElasticPhysicsHP::ConstructProcess(), G4HadronElasticPhysicsLEND::ConstructProcess(), and GetNeutronModel().
GetElasticProcess()
G4HadronicProcess * G4HadronElasticPhysics::GetElasticProcess (const G4ParticleDefinition * part) const
Definition at line 255 of file G4HadronElasticPhysics.cc.
Referenced by AddXSection(), G4HadronElasticPhysicsPHP::ConstructProcess(), G4HadronElasticPhysicsHP::ConstructProcess(), G4HadronElasticPhysicsLEND::ConstructProcess(), GetElasticModel(), and GetNeutronProcess().
GetNeutronModel()
G4HadronElastic * G4HadronElasticPhysics::GetNeutronModel () const
Definition at line 286 of file G4HadronElasticPhysics.cc.
Referenced by HadronElasticPhysicsHP::ConstructProcess().
GetNeutronProcess()
G4HadronicProcess * G4HadronElasticPhysics::GetNeutronProcess () const
Definition at line 281 of file G4HadronElasticPhysics.cc.
Referenced by HadronElasticPhysicsHP::ConstructProcess().
operator=()
G4HadronElasticPhysics& G4HadronElasticPhysics::operator= (const G4HadronElasticPhysics & right) private delete
Field Documentation
verbose
G4int G4HadronElasticPhysics::verbose protected
Definition at line 89 of file G4HadronElasticPhysics.hh.
Referenced by G4HadronElasticPhysicsPHP::ConstructProcess(), G4HadronElasticPhysicsHP::ConstructProcess(), G4HadronElasticPhysicsLEND::ConstructProcess(), ConstructProcess(), G4HadronElasticPhysics(), G4HadronElasticPhysicsHP::G4HadronElasticPhysicsHP(), G4HadronElasticPhysicsLEND::G4HadronElasticPhysicsLEND(), G4HadronElasticPhysicsPHP::G4HadronElasticPhysicsPHP(), and G4HadronElasticPhysicsXS::G4HadronElasticPhysicsXS().
The documentation for this class was generated from the following files:
source/physics_lists/constructors/hadron_elastic/include/G4HadronElasticPhysics.hh
source/physics_lists/constructors/hadron_elastic/src/G4HadronElasticPhysics.cc