Geant4: CCalSensitiveDetectors Class Reference
CCalSensitiveDetectors Class Reference
#include <CCalSensitiveDetectors.hh>
Public Member Functions
~CCalSensitiveDetectors ()
std::vector< G4LogicalVolume * > getVolumes (const G4String &name, bool exists=0)
void registerVolume (const G4String &name, G4LogicalVolume *)
bool setSensitive (const G4String &string, G4VSensitiveDetector *sens)
Static Public Member Functions
static CCalSensitiveDetectors * getInstance ()
Private Member Functions
CCalSensitiveDetectors ()
Private Attributes
mmslv theLVs
Static Private Attributes
static CCalSensitiveDetectors * theInstance = 0
Detailed Description
Definition at line 41 of file CCalSensitiveDetectors.hh.
Constructor & Destructor Documentation
~CCalSensitiveDetectors()
CCalSensitiveDetectors::~CCalSensitiveDetectors () inline
Definition at line 44 of file CCalSensitiveDetectors.hh.
CCalSensitiveDetectors()
CCalSensitiveDetectors::CCalSensitiveDetectors () inline private
Definition at line 50 of file CCalSensitiveDetectors.hh.
Referenced by getInstance().
Member Function Documentation
getInstance()
CCalSensitiveDetectors * CCalSensitiveDetectors::getInstance () static
Definition at line 38 of file CCalSensitiveDetectors.cc.
Referenced by CCalSensAssign::assign(), CCalG4Hcal::constructSensitive(), and CCalG4Ecal::constructSensitive().
getVolumes()
std::vector< G4LogicalVolume * > CCalSensitiveDetectors::getVolumes (const G4String & name, bool exists = 0)
Definition at line 54 of file CCalSensitiveDetectors.cc.
registerVolume()
void CCalSensitiveDetectors::registerVolume (const G4String & name, G4LogicalVolume * logv)
Definition at line 44 of file CCalSensitiveDetectors.cc.
Referenced by CCalG4Hcal::constructSensitive(), and CCalG4Ecal::constructSensitive().
setSensitive()
bool CCalSensitiveDetectors::setSensitive (const G4String & string, G4VSensitiveDetector * sens)
Definition at line 72 of file CCalSensitiveDetectors.cc.
Referenced by CCalSensAssign::assign().
Field Documentation
theInstance
CCalSensitiveDetectors * CCalSensitiveDetectors::theInstance = 0 static private
Definition at line 50 of file CCalSensitiveDetectors.hh.
Referenced by getInstance().
theLVs
mmslv CCalSensitiveDetectors::theLVs private
Definition at line 53 of file CCalSensitiveDetectors.hh.
Referenced by getVolumes(), registerVolume(), and setSensitive().
The documentation for this class was generated from the following files:
examples/advanced/composite_calorimeter/include/CCalSensitiveDetectors.hh
examples/advanced/composite_calorimeter/src/CCalSensitiveDetectors.cc