Geant4: g4alt::G4PhysListFactory Class Reference
g4alt::G4PhysListFactory Class Reference
#include <G4PhysListFactoryAlt.hh>
Public Member Functions
G4PhysListFactory ()
~G4PhysListFactory ()
G4VModularPhysicsList * GetReferencePhysList (const G4String &)
G4VModularPhysicsList * ReferencePhysList ()
void SetDefaultReferencePhysList (const G4String &name="")
G4bool IsReferencePhysList (const G4String &)
const std::vector< G4String > & AvailablePhysLists () const
const std::vector< G4String > & AvailablePhysListsEM () const
void PrintAvailablePhysLists () const
void SetVerbose (G4int val)
G4int GetVerbose () const
void SetUnknownFatal (G4int val)
G4int GetUnknownFatal () const
Detailed Description
Definition at line 45 of file G4PhysListFactoryAlt.hh.
Constructor & Destructor Documentation
G4PhysListFactory()
G4PhysListFactory::G4PhysListFactory ()
Definition at line 43 of file G4PhysListFactoryAlt.cc.
~G4PhysListFactory()
G4PhysListFactory::~G4PhysListFactory ()
Definition at line 47 of file G4PhysListFactoryAlt.cc.
Member Function Documentation
AvailablePhysLists()
const std::vector< G4String > & G4PhysListFactory::AvailablePhysLists () const
Definition at line 73 of file G4PhysListFactoryAlt.cc.
AvailablePhysListsEM()
const std::vector< G4String > & G4PhysListFactory::AvailablePhysListsEM () const
Definition at line 79 of file G4PhysListFactoryAlt.cc.
GetReferencePhysList()
G4VModularPhysicsList * G4PhysListFactory::GetReferencePhysList (const G4String & name)
Definition at line 62 of file G4PhysListFactoryAlt.cc.
Referenced by main().
GetUnknownFatal()
G4int G4PhysListFactory::GetUnknownFatal () const
Definition at line 104 of file G4PhysListFactoryAlt.cc.
GetVerbose()
G4int G4PhysListFactory::GetVerbose () const
Definition at line 94 of file G4PhysListFactoryAlt.cc.
IsReferencePhysList()
G4bool G4PhysListFactory::IsReferencePhysList (const G4String & name)
Definition at line 67 of file G4PhysListFactoryAlt.cc.
PrintAvailablePhysLists()
void G4PhysListFactory::PrintAvailablePhysLists () const
Definition at line 84 of file G4PhysListFactoryAlt.cc.
ReferencePhysList()
G4VModularPhysicsList * G4PhysListFactory::ReferencePhysList ()
Definition at line 56 of file G4PhysListFactoryAlt.cc.
Referenced by main().
SetDefaultReferencePhysList()
void G4PhysListFactory::SetDefaultReferencePhysList (const G4String & name = "")
Definition at line 50 of file G4PhysListFactoryAlt.cc.
Referenced by main().
SetUnknownFatal()
void G4PhysListFactory::SetUnknownFatal (G4int val)
Definition at line 99 of file G4PhysListFactoryAlt.cc.
SetVerbose()
void G4PhysListFactory::SetVerbose (G4int val)
Definition at line 89 of file G4PhysListFactoryAlt.cc.
The documentation for this class was generated from the following files:
source/physics_lists/lists/include/G4PhysListFactoryAlt.hh
source/physics_lists/lists/src/G4PhysListFactoryAlt.cc