Geant4: G4Hdf5NtupleManager Class Reference
G4Hdf5NtupleManager Class Reference
#include <G4Hdf5NtupleManager.hh>
Public Member Functions
G4Hdf5NtupleManager (const G4AnalysisManagerState &state)
~G4Hdf5NtupleManager ()
Public Member Functions inherited from G4TNtupleManager< tools::hdf5::ntuple >
G4TNtupleManager (const G4AnalysisManagerState &state)
~G4TNtupleManager ()
Public Member Functions inherited from G4BaseNtupleManager
G4BaseNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4BaseNtupleManager ()
G4BaseNtupleManager (const G4BaseNtupleManager &rhs)=delete
G4BaseNtupleManager & operator= (const G4BaseNtupleManager &rhs)=delete
Public Member Functions inherited from G4VNtupleManager
G4VNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4VNtupleManager ()
G4VNtupleManager (const G4VNtupleManager &rhs)=delete
G4VNtupleManager & operator= (const G4VNtupleManager &rhs)=delete
Public Member Functions inherited from G4BaseAnalysisManager
G4BaseAnalysisManager (const G4AnalysisManagerState &state)
virtual ~G4BaseAnalysisManager ()
G4bool SetFirstId (G4int firstId)
void SetLockFirstId (G4bool lockFirstId)
G4int GetFirstId () const
Private Types
using NtupleType = tools::hdf5::ntuple
using NtupleDescriptionType = G4TNtupleDescription< NtupleType >
Private Member Functions
void SetFileManager (std::shared_ptr< G4Hdf5FileManager > fileManager)
const std::vector< NtupleDescriptionType * > & GetNtupleDescriptionVector () const
void CreateTNtuple (NtupleDescriptionType *ntupleDescription, G4bool warn)
virtual void CreateTNtuple (NtupleDescriptionType *ntupleDescription, const G4String &name, const G4String &title) final
virtual void CreateTNtupleFromBooking (NtupleDescriptionType *ntupleDescription) final
virtual void FinishTNtuple (NtupleDescriptionType *ntupleDescription, G4bool fromBooking) final
Private Attributes
std::shared_ptr< G4Hdf5FileManager > fFileManager
Friends
class G4Hdf5AnalysisManager
Additional Inherited Members
Protected Member Functions inherited from G4TNtupleManager< tools::hdf5::ntuple >
virtual void CreateNtuplesFromBooking ()
G4bool IsEmpty () const
virtual G4bool Reset (G4bool deleteNtuple)
virtual G4int CreateNtuple (const G4String &name, const G4String &title) override
virtual G4int CreateNtupleIColumn (G4int ntupleId, const G4String &name, std::vector< int > *vector) final
virtual G4int CreateNtupleIColumn (const G4String &name, std::vector< int > *vector) final
virtual G4int CreateNtupleIColumn (G4int ntupleId, const G4String &name, std::vector< int > *vector)=0
virtual G4int CreateNtupleFColumn (G4int ntupleId, const G4String &name, std::vector< float > *vector) final
virtual G4int CreateNtupleFColumn (const G4String &name, std::vector< float > *vector) final
virtual G4int CreateNtupleFColumn (G4int ntupleId, const G4String &name, std::vector< float > *vector)=0
virtual G4int CreateNtupleDColumn (G4int ntupleId, const G4String &name, std::vector< double > *vector) final
virtual G4int CreateNtupleDColumn (const G4String &name, std::vector< double > *vector) final
virtual G4int CreateNtupleDColumn (G4int ntupleId, const G4String &name, std::vector< double > *vector)=0
virtual G4int CreateNtupleSColumn (G4int ntupleId, const G4String &name) final
virtual G4int CreateNtupleSColumn (const G4String &name)
virtual G4int CreateNtupleSColumn (G4int ntupleId, const G4String &name)=0
virtual void FinishNtuple (G4int ntupleId) final
virtual void FinishNtuple () final
virtual void FinishNtuple (G4int ntupleId)=0
virtual G4bool FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value) final
virtual G4bool FillNtupleIColumn (G4int id, G4int value) final
virtual G4bool FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value)=0
virtual G4bool FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value) final
virtual G4bool FillNtupleFColumn (G4int id, G4float value) final
virtual G4bool FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value)=0
virtual G4bool FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value) final
virtual G4bool FillNtupleDColumn (G4int id, G4double value) final
virtual G4bool FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value)=0
virtual G4bool FillNtupleSColumn (G4int ntupleId, G4int columnId, const G4String &value) final
virtual G4bool FillNtupleSColumn (G4int id, const G4String &value) final
virtual G4bool FillNtupleSColumn (G4int ntupleId, G4int columnId, const G4String &value)=0
virtual G4bool AddNtupleRow (G4int ntupleId) override
virtual G4bool AddNtupleRow () final
virtual G4bool AddNtupleRow (G4int ntupleId)=0
virtual void SetActivation (G4bool activation) final
virtual void SetActivation (G4int ntupleId, G4bool activation) final
virtual G4bool GetActivation (G4int ntupleId) const final
tools::hdf5::ntuple * GetNtuple () const
tools::hdf5::ntuple * GetNtuple (G4int ntupleId) const
virtual G4int GetNofNtuples () const final
virtual G4int GetNofNtupleBookings () const override
std::vector< tools::hdf5::ntuple * >::iterator BeginNtuple ()
std::vector< tools::hdf5::ntuple * >::iterator EndNtuple ()
std::vector< tools::hdf5::ntuple * >::const_iterator BeginConstNtuple () const
std::vector< tools::hdf5::ntuple * >::const_iterator EndConstNtuple () const
Protected Member Functions inherited from G4BaseNtupleManager
virtual G4int CreateNtupleIColumn (const G4String &name, std::vector< int > *vector) final
virtual G4int CreateNtupleFColumn (const G4String &name, std::vector< float > *vector) final
virtual G4int CreateNtupleDColumn (const G4String &name, std::vector< double > *vector) final
virtual G4int CreateNtupleSColumn (const G4String &name)
virtual void FinishNtuple () final
virtual G4bool SetFirstNtupleColumnId (G4int firstId) final
G4int GetFirstNtupleColumnId () const final
virtual G4bool FillNtupleIColumn (G4int id, G4int value) final
virtual G4bool FillNtupleFColumn (G4int id, G4float value) final
virtual G4bool FillNtupleDColumn (G4int id, G4double value) final
virtual G4bool FillNtupleSColumn (G4int id, const G4String &value) final
virtual G4bool AddNtupleRow () final
Protected Attributes inherited from G4TNtupleManager< tools::hdf5::ntuple >
std::vector< G4TNtupleDescription< tools::hdf5::ntuple > * > fNtupleDescriptionVector
std::vector< tools::hdf5::ntuple * > fNtupleVector
Protected Attributes inherited from G4BaseNtupleManager
G4int fFirstNtupleColumnId
G4bool fLockFirstNtupleColumnId
Protected Attributes inherited from G4BaseAnalysisManager
const G4AnalysisManagerState & fState
G4int fFirstId
G4bool fLockFirstId
Detailed Description
Definition at line 52 of file G4Hdf5NtupleManager.hh.
Member Typedef Documentation
NtupleDescriptionType
using G4Hdf5NtupleManager::NtupleDescriptionType = G4TNtupleDescription<NtupleType> private
Definition at line 63 of file G4Hdf5NtupleManager.hh.
NtupleType
using G4Hdf5NtupleManager::NtupleType = tools::hdf5::ntuple private
Definition at line 62 of file G4Hdf5NtupleManager.hh.
Constructor & Destructor Documentation
G4Hdf5NtupleManager()
G4Hdf5NtupleManager::G4Hdf5NtupleManager (const G4AnalysisManagerState & state) explicit
Definition at line 43 of file G4Hdf5NtupleManager.cc.
~G4Hdf5NtupleManager()
G4Hdf5NtupleManager::~G4Hdf5NtupleManager ()
Definition at line 49 of file G4Hdf5NtupleManager.cc.
Member Function Documentation
CreateTNtuple() [1/2]
virtual void G4Hdf5NtupleManager::CreateTNtuple (NtupleDescriptionType * ntupleDescription, const G4String & name, const G4String & title) final private virtual
CreateTNtuple() [2/2]
void G4Hdf5NtupleManager::CreateTNtuple (NtupleDescriptionType * ntupleDescription, G4bool warn) private
Definition at line 56 of file G4Hdf5NtupleManager.cc.
Referenced by CreateTNtupleFromBooking(), and FinishTNtuple().
CreateTNtupleFromBooking()
void G4Hdf5NtupleManager::CreateTNtupleFromBooking (NtupleDescriptionType * ntupleDescription) final private virtual
Definition at line 99 of file G4Hdf5NtupleManager.cc.
FinishTNtuple()
void G4Hdf5NtupleManager::FinishTNtuple (NtupleDescriptionType * ntupleDescription, G4bool fromBooking) final private virtual
Definition at line 107 of file G4Hdf5NtupleManager.cc.
GetNtupleDescriptionVector()
const std::vector< G4TNtupleDescription< tools::hdf5::ntuple > * > & G4Hdf5NtupleManager::GetNtupleDescriptionVector () const inline private
Definition at line 98 of file G4Hdf5NtupleManager.hh.
SetFileManager()
void G4Hdf5NtupleManager::SetFileManager (std::shared_ptr< G4Hdf5FileManager > fileManager) inline private
Definition at line 94 of file G4Hdf5NtupleManager.hh.
Referenced by G4Hdf5AnalysisManager::G4Hdf5AnalysisManager().
Friends And Related Function Documentation
G4Hdf5AnalysisManager
friend class G4Hdf5AnalysisManager friend
Definition at line 54 of file G4Hdf5NtupleManager.hh.
Field Documentation
fFileManager
std::shared_ptr<G4Hdf5FileManager> G4Hdf5NtupleManager::fFileManager private
Definition at line 88 of file G4Hdf5NtupleManager.hh.
Referenced by CreateTNtuple(), FinishTNtuple(), and SetFileManager().
The documentation for this class was generated from the following files:
source/analysis/hdf5/include/G4Hdf5NtupleManager.hh
source/analysis/hdf5/src/G4Hdf5NtupleManager.cc