Geant4: G4Field Class Reference
G4Field Class Reference abstract
#include <G4Field.hh>
Public Member Functions
virtual void GetFieldValue (const double Point[4], double *fieldArr) const =0
G4Field (G4bool gravityOn=false)
G4Field (const G4Field &)
virtual ~G4Field ()
G4Field & operator= (const G4Field &p)
virtual G4bool DoesFieldChangeEnergy () const =0
G4bool IsGravityActive () const
void SetGravityActive (G4bool OnOffFlag)
virtual G4Field * Clone () const
Static Public Attributes
static constexpr G4int MAX_NUMBER_OF_COMPONENTS = 24
Private Attributes
G4bool fGravityActive
Detailed Description
Definition at line 64 of file G4Field.hh.
Constructor & Destructor Documentation
G4Field() [1/2]
G4Field::G4Field (G4bool gravityOn = false)
Definition at line 33 of file G4Field.cc.
G4Field() [2/2]
G4Field::G4Field (const G4Field & p)
Definition at line 49 of file G4Field.cc.
~G4Field()
G4Field::~G4Field () virtual
Definition at line 38 of file G4Field.cc.
Member Function Documentation
Clone()
G4Field * G4Field::Clone () const virtual
Reimplemented in G4UniformMagField, G4UniformGravityField, G4CachedMagneticField, G4QuadrupoleMagField, G4UniformElectricField, G4DELPHIMagField, G4HarmonicPolMagField, G4LineCurrentMagField, and G4KM_DummyField.
Definition at line 54 of file G4Field.cc.
Referenced by G4CachedMagneticField::Clone(), and G4FieldManager::Clone().
DoesFieldChangeEnergy()
virtual G4bool G4Field::DoesFieldChangeEnergy () const pure virtual
Implemented in G4ElectroMagneticField, F04GlobalField, G4UniformGravityField, G4MagneticField, G4ElectricField, EMField, and F05Field.
Referenced by G4FieldManager::G4FieldManager(), and G4FieldManager::InitialiseFieldChangesEnergy().
GetFieldValue()
virtual void G4Field::GetFieldValue (const double Point[4], double * fieldArr) const pure virtual
Implemented in G4UniformMagField, G4UniformElectricField, G4UniformGravityField, G4ElectroMagneticField, G4MagneticField, G4ElectricField, G4CachedMagneticField, F05Field, PyG4MagneticField, B5MagneticField, HadrontherapyElectricTabulatedField3D, PurgMagTabulatedField3D, HadrontherapyMagneticField3D, EMField, and TabulatedField3D.
Referenced by G4ErrorSurfaceTrajState::BuildErrorMatrix(), G4MagneticFieldModel::DescribeYourselfTo(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), G4SynchrotronRadiation::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetPhotonEnergy(), G4SynchrotronRadiation::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4ErrorMagFieldLimitProcess::PostStepGetPhysicalInteractionLength(), and G4ErrorFreeTrajState::PropagateError().
IsGravityActive()
G4bool G4Field::IsGravityActive () const inline
Definition at line 99 of file G4Field.hh.
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), and G4RepleteEofM::G4RepleteEofM().
operator=()
G4Field & G4Field::operator= (const G4Field & p)
Definition at line 42 of file G4Field.cc.
Referenced by G4MagneticField::operator=(), G4UniformGravityField::operator=(), and G4ElectroMagneticField::operator=().
SetGravityActive()
void G4Field::SetGravityActive (G4bool OnOffFlag) inline
Definition at line 111 of file G4Field.hh.
Field Documentation
fGravityActive
G4bool G4Field::fGravityActive private
Definition at line 108 of file G4Field.hh.
Referenced by IsGravityActive(), operator=(), and SetGravityActive().
MAX_NUMBER_OF_COMPONENTS
constexpr G4int G4Field::MAX_NUMBER_OF_COMPONENTS = 24 static constexpr
Definition at line 68 of file G4Field.hh.
The documentation for this class was generated from the following files:
source/geometry/magneticfield/include/G4Field.hh
source/geometry/magneticfield/src/G4Field.cc