Geant4: source/processes/hadronic/models/lend/src/xDataTOM_XYs.cc File Reference
xDataTOM_XYs.cc File Reference
#include <string.h>
#include "xDataTOM_private.h"
Functions
int xDataTOM_XYs_free (xDataTOM_xDataInfo *xDI)
int xDataTOM_XYs_release (xDataTOM_XYs *XYs)
int xDataTOM_XYs_getData (xDataTOM_XYs *XYs, double **data)
int xDataTOM_XYs_getDataFromXDataInfo (xDataTOM_xDataInfo *xDI, double **data)
Variables
const char * xDataTOM_XYs_ID = "XYs"
Function Documentation
xDataTOM_XYs_free()
int xDataTOM_XYs_free (xDataTOM_xDataInfo * xDI)
Definition at line 19 of file xDataTOM_XYs.cc.
Referenced by xDataTOM_releaseElement().
xDataTOM_XYs_getData()
int xDataTOM_XYs_getData (xDataTOM_XYs * XYs, double ** data)
Definition at line 42 of file xDataTOM_XYs.cc.
Referenced by MCGIDI_misc_dataFromXYs2ptwXYPointsInUnitsOf(), and xDataTOM_XYs_getDataFromXDataInfo().
xDataTOM_XYs_getDataFromXDataInfo()
int xDataTOM_XYs_getDataFromXDataInfo (xDataTOM_xDataInfo * xDI, double ** data)
Definition at line 50 of file xDataTOM_XYs.cc.
Referenced by MCGIDI_misc_dataFromElement2ptwXYPointsInUnitsOf().
xDataTOM_XYs_release()
int xDataTOM_XYs_release (xDataTOM_XYs * XYs)
Definition at line 31 of file xDataTOM_XYs.cc.
Referenced by xDataTOM_regionsXYs_free(), xDataTOM_W_XYs_release(), and xDataTOM_XYs_free().
Variable Documentation
xDataTOM_XYs_ID
const char* xDataTOM_XYs_ID = "XYs"
Definition at line 14 of file xDataTOM_XYs.cc.
Referenced by xDataTOM_releaseElement(), xDataTOM_XYs_free(), xDataXML_constructTOM(), and xDataXML_XYsDataToTOM2().