Geant4: G4SliceTimer Class Reference
G4SliceTimer Class Reference
#include <G4SliceTimer.hh>
Public Member Functions
G4SliceTimer ()
void Start ()
void Stop ()
void Clear ()
G4bool IsValid () const
G4double GetRealElapsed () const
G4double GetSystemElapsed () const
G4double GetUserElapsed () const
Private Attributes
G4bool fValidTimes
clock_t fStartRealTime
clock_t fEndRealTime
tms fStartTimes
tms fEndTimes
G4double fRealElapsed
G4double fSystemElapsed
G4double fUserElapsed
Detailed Description
Definition at line 110 of file G4SliceTimer.hh.
Constructor & Destructor Documentation
G4SliceTimer()
G4SliceTimer::G4SliceTimer ()
Definition at line 60 of file G4SliceTimer.cc.
Member Function Documentation
Clear()
void G4SliceTimer::Clear () inline
Referenced by G4SliceTimer().
GetRealElapsed()
G4double G4SliceTimer::GetRealElapsed () const
Definition at line 66 of file G4SliceTimer.cc.
Referenced by operator<<().
GetSystemElapsed()
G4double G4SliceTimer::GetSystemElapsed () const
Definition at line 71 of file G4SliceTimer.cc.
Referenced by operator<<().
GetUserElapsed()
G4double G4SliceTimer::GetUserElapsed () const
Definition at line 76 of file G4SliceTimer.cc.
Referenced by operator<<().
IsValid()
G4bool G4SliceTimer::IsValid () const inline
Referenced by operator<<().
Start()
void G4SliceTimer::Start () inline
Stop()
void G4SliceTimer::Stop () inline
Field Documentation
fEndRealTime
clock_t G4SliceTimer::fEndRealTime private
Definition at line 127 of file G4SliceTimer.hh.
fEndTimes
tms G4SliceTimer::fEndTimes private
Definition at line 128 of file G4SliceTimer.hh.
fRealElapsed
G4double G4SliceTimer::fRealElapsed private
Definition at line 129 of file G4SliceTimer.hh.
Referenced by GetRealElapsed().
fStartRealTime
clock_t G4SliceTimer::fStartRealTime private
Definition at line 127 of file G4SliceTimer.hh.
fStartTimes
tms G4SliceTimer::fStartTimes private
Definition at line 128 of file G4SliceTimer.hh.
fSystemElapsed
G4double G4SliceTimer::fSystemElapsed private
Definition at line 129 of file G4SliceTimer.hh.
Referenced by GetSystemElapsed().
fUserElapsed
G4double G4SliceTimer::fUserElapsed private
Definition at line 129 of file G4SliceTimer.hh.
Referenced by GetUserElapsed().
fValidTimes
G4bool G4SliceTimer::fValidTimes private
Definition at line 126 of file G4SliceTimer.hh.
The documentation for this class was generated from the following files:
source/global/management/include/G4SliceTimer.hh
source/global/management/src/G4SliceTimer.cc