Geant4: source/digits_hits/digits/src/G4TDigiCollection.cc File Reference
G4TDigiCollection.cc File Reference
#include "G4TDigiCollection.hh"
Functions
G4Allocator< G4DigiCollection > *& aDCAllocator_G4MT_TLS_ ()
Function Documentation
aDCAllocator_G4MT_TLS_()
G4Allocator<G4DigiCollection>*& aDCAllocator_G4MT_TLS_ ()
Definition at line 31 of file G4TDigiCollection.cc.
Referenced by G4TDigiCollection< T >::DrawAllDigi(), G4TDigiCollection< T >::entries(), G4DigiCollection::G4DigiCollection(), G4TDigiCollection< T >::G4TDigiCollection(), G4TDigiCollection< T >::GetDigi(), G4TDigiCollection< T >::GetSize(), G4TDigiCollection< T >::GetVector(), G4TDigiCollection< T >::insert(), G4TDigiCollection< T >::operator delete(), G4TDigiCollection< T >::operator new(), G4DigiCollection::operator==(), G4TDigiCollection< T >::operator==(), G4TDigiCollection< T >::operator[](), G4TDigiCollection< T >::PrintAllDigi(), G4DigiCollection::~G4DigiCollection(), and G4TDigiCollection< T >::~G4TDigiCollection().