Geant4: G4MagneticField Class Reference
G4MagneticField Class Reference abstract
#include <G4MagneticField.hh>
Public Member Functions
G4MagneticField ()
virtual ~G4MagneticField ()
G4MagneticField (const G4MagneticField &r)
G4MagneticField & operator= (const G4MagneticField &p)
G4bool DoesFieldChangeEnergy () const
virtual void GetFieldValue (const G4double Point[4], G4double *Bfield) const =0
Public Member Functions inherited from G4Field
G4Field (G4bool gravityOn=false)
G4Field (const G4Field &)
virtual ~G4Field ()
G4Field & operator= (const G4Field &p)
G4bool IsGravityActive () const
void SetGravityActive (G4bool OnOffFlag)
virtual G4Field * Clone () const
Additional Inherited Members
Static Public Attributes inherited from G4Field
static constexpr G4int MAX_NUMBER_OF_COMPONENTS = 24
Detailed Description
Definition at line 45 of file G4MagneticField.hh.
Constructor & Destructor Documentation
G4MagneticField() [1/2]
G4MagneticField::G4MagneticField ()
Definition at line 32 of file G4MagneticField.cc.
~G4MagneticField()
G4MagneticField::~G4MagneticField () virtual
Definition at line 37 of file G4MagneticField.cc.
G4MagneticField() [2/2]
G4MagneticField::G4MagneticField (const G4MagneticField & r)
Definition at line 41 of file G4MagneticField.cc.
Member Function Documentation
DoesFieldChangeEnergy()
G4bool G4MagneticField::DoesFieldChangeEnergy () const inline virtual
Implements G4Field.
Definition at line 57 of file G4MagneticField.hh.
Referenced by export_G4MagneticField().
GetFieldValue()
virtual void G4MagneticField::GetFieldValue (const G4double Point[4], G4double * Bfield) const pure virtual
Implements G4Field.
Implemented in G4UniformMagField, G4CachedMagneticField, PyG4MagneticField, B5MagneticField, PurgMagTabulatedField3D, HadrontherapyMagneticField3D, and TabulatedField3D.
Referenced by F03FieldSetup::GetConstantFieldValue(), and G4CachedMagneticField::GetFieldValue().
operator=()
G4MagneticField & G4MagneticField::operator= (const G4MagneticField & p)
Definition at line 46 of file G4MagneticField.cc.
Referenced by G4CachedMagneticField::operator=(), and G4UniformMagField::operator=().
The documentation for this class was generated from the following files:
source/geometry/magneticfield/include/G4MagneticField.hh
source/geometry/magneticfield/src/G4MagneticField.cc