Geant4: G4P2ToolsManager Class Reference
G4P2ToolsManager Class Reference
#include <G4P2ToolsManager.hh>
Public Member Functions
G4P2ToolsManager (const G4AnalysisManagerState &state)
virtual ~G4P2ToolsManager ()
G4int AddP2 (const G4String &name, tools::histo::p2d *p2d)
void AddP2Vector (const std::vector< tools::histo::p2d * > &p2Vector)
tools::histo::p2d * GetP2 (G4int id, G4bool warn=true, G4bool onlyIfActive=true) const
std::vector< tools::histo::p2d * >::iterator BeginP2 ()
std::vector< tools::histo::p2d * >::iterator EndP2 ()
std::vector< tools::histo::p2d * >::const_iterator BeginConstP2 () const
std::vector< tools::histo::p2d * >::const_iterator EndConstP2 () const
const std::vector< tools::histo::p2d * > & GetP2Vector () const
const std::vector< G4HnInformation * > & GetHnVector () const
Public Member Functions inherited from G4VP2Manager
G4VP2Manager ()
virtual ~G4VP2Manager ()
G4VP2Manager (const G4VP2Manager &rhs)=delete
G4VP2Manager & operator= (const G4VP2Manager &rhs)=delete
Public Member Functions inherited from G4THnManager< tools::histo::p2d >
G4THnManager (const G4AnalysisManagerState &state, const G4String &hnType)
virtual ~G4THnManager ()
G4bool Reset ()
G4bool IsEmpty () const
Protected Member Functions
virtual G4int CreateP2 (const G4String &name, const G4String &title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4double zmin=0, G4double zmax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none", const G4String &xbinScheme="linear", const G4String &ybinScheme="linear") final
virtual G4int CreateP2 (const G4String &name, const G4String &title, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, G4double zmin=0, G4double zmax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none") final
virtual G4bool SetP2 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4double zmin=0, G4double zmax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none", const G4String &xbinScheme="linear", const G4String &ybinScheme="linear") final
virtual G4bool SetP2 (G4int id, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, G4double zmin=0, G4double zmax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none") final
virtual G4bool ScaleP2 (G4int id, G4double factor) final
virtual G4bool FillP2 (G4int id, G4double xvalue, G4double yvalue, G4double zvalue, G4double weight=1.0) final
virtual G4int GetP2Id (const G4String &name, G4bool warn=true) const final
virtual G4int GetP2Nxbins (G4int id) const final
virtual G4double GetP2Xmin (G4int id) const final
virtual G4double GetP2Xmax (G4int id) const final
virtual G4double GetP2XWidth (G4int id) const final
virtual G4int GetP2Nybins (G4int id) const final
virtual G4double GetP2Ymin (G4int id) const final
virtual G4double GetP2Ymax (G4int id) const final
virtual G4double GetP2YWidth (G4int id) const final
virtual G4double GetP2Zmin (G4int id) const final
virtual G4double GetP2Zmax (G4int id) const final
virtual G4bool SetP2Title (G4int id, const G4String &title) final
virtual G4bool SetP2XAxisTitle (G4int id, const G4String &title) final
virtual G4bool SetP2YAxisTitle (G4int id, const G4String &title) final
virtual G4bool SetP2ZAxisTitle (G4int id, const G4String &title) final
virtual G4String GetP2Title (G4int id) const final
virtual G4String GetP2XAxisTitle (G4int id) const final
virtual G4String GetP2YAxisTitle (G4int id) const final
virtual G4String GetP2ZAxisTitle (G4int id) const final
virtual G4bool WriteOnAscii (std::ofstream &output) final
virtual std::shared_ptr< G4HnManager > GetHnManager () final
Protected Member Functions inherited from G4THnManager< tools::histo::p2d >
void AddTVector (const std::vector< tools::histo::p2d * > &tVector)
std::vector< tools::histo::p2d * >::iterator BeginT ()
std::vector< tools::histo::p2d * >::iterator EndT ()
std::vector< tools::histo::p2d * >::const_iterator BeginConstT () const
std::vector< tools::histo::p2d * >::const_iterator EndConstT () const
tools::histo::p2d * GetTInFunction (G4int id, G4String functionName, G4bool warn=true, G4bool onlyIfActive=true) const
G4int RegisterT (tools::histo::p2d *t, const G4String &name)
G4int GetTId (const G4String &name, G4bool warn=true) const
Private Member Functions
void AddP2Information (const G4String &name, const G4String &xunitName, const G4String &yunitName, const G4String &zunitName, const G4String &xfcnName, const G4String &yfcnName, const G4String &zfcnName, G4BinScheme xbinScheme, G4BinScheme ybinScheme) const
Static Private Attributes
static const G4int kDimension = 2
Additional Inherited Members
Protected Attributes inherited from G4THnManager< tools::histo::p2d >
const G4AnalysisManagerState & fState
std::vector< tools::histo::p2d * > fTVector
std::map< G4String, G4int > fNameIdMap
std::shared_ptr< G4HnManager > fHnManager
Detailed Description
Definition at line 51 of file G4P2ToolsManager.hh.
Constructor & Destructor Documentation
G4P2ToolsManager()
G4P2ToolsManager::G4P2ToolsManager (const G4AnalysisManagerState & state) explicit
Definition at line 44 of file G4P2ToolsManager.cc.
~G4P2ToolsManager()
G4P2ToolsManager::~G4P2ToolsManager () virtual
Definition at line 50 of file G4P2ToolsManager.cc.
Member Function Documentation
AddP2()
G4int G4P2ToolsManager::AddP2 (const G4String & name, tools::histo::p2d * p2d)
Definition at line 722 of file G4P2ToolsManager.cc.
Referenced by G4CsvAnalysisReader::ReadP2Impl(), G4XmlAnalysisReader::ReadP2Impl(), G4RootAnalysisReader::ReadP2Impl(), and G4Hdf5AnalysisReader::ReadP2Impl().
AddP2Information()
void G4P2ToolsManager::AddP2Information (const G4String & name, const G4String & xunitName, const G4String & yunitName, const G4String & zunitName, const G4String & xfcnName, const G4String & yfcnName, const G4String & zfcnName, G4BinScheme xbinScheme, G4BinScheme ybinScheme) const private
Definition at line 295 of file G4P2ToolsManager.cc.
Referenced by AddP2(), and CreateP2().
AddP2Vector()
void G4P2ToolsManager::AddP2Vector (const std::vector< tools::histo::p2d * > & p2Vector)
Definition at line 746 of file G4P2ToolsManager.cc.
Referenced by G4XmlAnalysisManager::WriteP2(), G4CsvAnalysisManager::WriteP2(), G4Hdf5AnalysisManager::WriteP2(), and G4RootAnalysisManager::WriteP2().
BeginConstP2()
std::vector< tools::histo::p2d * >::const_iterator G4P2ToolsManager::BeginConstP2 () const inline
Definition at line 201 of file G4P2ToolsManager.hh.
BeginP2()
std::vector< tools::histo::p2d * >::iterator G4P2ToolsManager::BeginP2 () inline
Definition at line 194 of file G4P2ToolsManager.hh.
CreateP2() [1/2]
G4int G4P2ToolsManager::CreateP2 (const G4String & name, const G4String & title, const std::vector< G4double > & xedges, const std::vector< G4double > & yedges, G4double zmin = 0, G4double zmax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none") final protected virtual
Implements G4VP2Manager.
Definition at line 362 of file G4P2ToolsManager.cc.
CreateP2() [2/2]
G4int G4P2ToolsManager::CreateP2 (const G4String & name, const G4String & title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4double zmin = 0, G4double zmax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none", const G4String & xbinScheme = "linear", const G4String & ybinScheme = "linear") final protected virtual
Implements G4VP2Manager.
Definition at line 316 of file G4P2ToolsManager.cc.
EndConstP2()
std::vector< tools::histo::p2d * >::const_iterator G4P2ToolsManager::EndConstP2 () const inline
Definition at line 205 of file G4P2ToolsManager.hh.
EndP2()
std::vector< tools::histo::p2d * >::iterator G4P2ToolsManager::EndP2 () inline
Definition at line 197 of file G4P2ToolsManager.hh.
FillP2()
G4bool G4P2ToolsManager::FillP2 (G4int id, G4double xvalue, G4double yvalue, G4double zvalue, G4double weight = 1.0) final protected virtual
Implements G4VP2Manager.
Definition at line 492 of file G4P2ToolsManager.cc.
GetHnManager()
std::shared_ptr< G4HnManager > G4P2ToolsManager::GetHnManager () inline final protected virtual
Implements G4VP2Manager.
Definition at line 214 of file G4P2ToolsManager.hh.
GetHnVector()
const std::vector< G4HnInformation * > & G4P2ToolsManager::GetHnVector () const inline
Definition at line 211 of file G4P2ToolsManager.hh.
Referenced by G4ToolsAnalysisManager::MergeImpl(), G4XmlAnalysisManager::WriteP2(), G4CsvAnalysisManager::WriteP2(), G4Hdf5AnalysisManager::WriteP2(), and G4RootAnalysisManager::WriteP2().
GetP2()
tools::histo::p2d * G4P2ToolsManager::GetP2 (G4int id, G4bool warn = true, G4bool onlyIfActive = true) const
Definition at line 753 of file G4P2ToolsManager.cc.
GetP2Id()
G4int G4P2ToolsManager::GetP2Id (const G4String & name, G4bool warn = true) const final protected virtual
Implements G4VP2Manager.
Definition at line 533 of file G4P2ToolsManager.cc.
GetP2Nxbins()
G4int G4P2ToolsManager::GetP2Nxbins (G4int id) const final protected virtual
Implements G4VP2Manager.
Definition at line 539 of file G4P2ToolsManager.cc.
GetP2Nybins()
G4int G4P2ToolsManager::GetP2Nybins (G4int id) const final protected virtual
Implements G4VP2Manager.
Definition at line 577 of file G4P2ToolsManager.cc.
GetP2Title()
G4String G4P2ToolsManager::GetP2Title (G4int id) const final protected virtual
Implements G4VP2Manager.
Definition at line 671 of file G4P2ToolsManager.cc.
GetP2Vector()
const std::vector< tools::histo::p2d * > & G4P2ToolsManager::GetP2Vector () const inline
Definition at line 208 of file G4P2ToolsManager.hh.
Referenced by G4ToolsAnalysisManager::MergeImpl(), G4XmlAnalysisManager::WriteP2(), G4CsvAnalysisManager::WriteP2(), G4Hdf5AnalysisManager::WriteP2(), and G4RootAnalysisManager::WriteP2().
GetP2XAxisTitle()
G4String G4P2ToolsManager::GetP2XAxisTitle (G4int id) const final protected virtual
Implements G4VP2Manager.
Definition at line 680 of file G4P2ToolsManager.cc.
GetP2Xmax()
G4double G4P2ToolsManager::GetP2Xmax (G4int id) const final protected virtual
Implements G4VP2Manager.
Definition at line 559 of file G4P2ToolsManager.cc.
GetP2Xmin()
G4double G4P2ToolsManager::GetP2Xmin (G4int id) const final protected virtual
Implements G4VP2Manager.
Definition at line 548 of file G4P2ToolsManager.cc.
GetP2XWidth()
G4double G4P2ToolsManager::GetP2XWidth (G4int id) const final protected virtual
Implements G4VP2Manager.
Definition at line 568 of file G4P2ToolsManager.cc.
GetP2YAxisTitle()
G4String G4P2ToolsManager::GetP2YAxisTitle (G4int id) const final protected virtual
Implements G4VP2Manager.
Definition at line 689 of file G4P2ToolsManager.cc.
GetP2Ymax()
G4double G4P2ToolsManager::GetP2Ymax (G4int id) const final protected virtual
Implements G4VP2Manager.
Definition at line 597 of file G4P2ToolsManager.cc.
GetP2Ymin()
G4double G4P2ToolsManager::GetP2Ymin (G4int id) const final protected virtual
Implements G4VP2Manager.
Definition at line 586 of file G4P2ToolsManager.cc.
GetP2YWidth()
G4double G4P2ToolsManager::GetP2YWidth (G4int id) const final protected virtual
Implements G4VP2Manager.
Definition at line 606 of file G4P2ToolsManager.cc.
GetP2ZAxisTitle()
G4String G4P2ToolsManager::GetP2ZAxisTitle (G4int id) const final protected virtual
Implements G4VP2Manager.
Definition at line 698 of file G4P2ToolsManager.cc.
GetP2Zmax()
G4double G4P2ToolsManager::GetP2Zmax (G4int id) const final protected virtual
Implements G4VP2Manager.
Definition at line 626 of file G4P2ToolsManager.cc.
GetP2Zmin()
G4double G4P2ToolsManager::GetP2Zmin (G4int id) const final protected virtual
Implements G4VP2Manager.
Definition at line 615 of file G4P2ToolsManager.cc.
ScaleP2()
G4bool G4P2ToolsManager::ScaleP2 (G4int id, G4double factor) final protected virtual
Implements G4VP2Manager.
Definition at line 483 of file G4P2ToolsManager.cc.
SetP2() [1/2]
G4bool G4P2ToolsManager::SetP2 (G4int id, const std::vector< G4double > & xedges, const std::vector< G4double > & yedges, G4double zmin = 0, G4double zmax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none") final protected virtual
Implements G4VP2Manager.
Definition at line 445 of file G4P2ToolsManager.cc.
SetP2() [2/2]
G4bool G4P2ToolsManager::SetP2 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4double zmin = 0, G4double zmax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none", const G4String & xbinScheme = "linear", const G4String & ybinScheme = "linear") final protected virtual
Implements G4VP2Manager.
Definition at line 401 of file G4P2ToolsManager.cc.
SetP2Title()
G4bool G4P2ToolsManager::SetP2Title (G4int id, const G4String & title) final protected virtual
Implements G4VP2Manager.
Definition at line 635 of file G4P2ToolsManager.cc.
SetP2XAxisTitle()
G4bool G4P2ToolsManager::SetP2XAxisTitle (G4int id, const G4String & title) final protected virtual
Implements G4VP2Manager.
Definition at line 644 of file G4P2ToolsManager.cc.
SetP2YAxisTitle()
G4bool G4P2ToolsManager::SetP2YAxisTitle (G4int id, const G4String & title) final protected virtual
Implements G4VP2Manager.
Definition at line 653 of file G4P2ToolsManager.cc.
SetP2ZAxisTitle()
G4bool G4P2ToolsManager::SetP2ZAxisTitle (G4int id, const G4String & title) final protected virtual
Implements G4VP2Manager.
Definition at line 662 of file G4P2ToolsManager.cc.
WriteOnAscii()
G4bool G4P2ToolsManager::WriteOnAscii (std::ofstream & output) final protected virtual
Implements G4VP2Manager.
Definition at line 707 of file G4P2ToolsManager.cc.
Field Documentation
kDimension
const G4int G4P2ToolsManager::kDimension = 2 static private
Definition at line 189 of file G4P2ToolsManager.hh.
The documentation for this class was generated from the following files:
source/analysis/hntools/include/G4P2ToolsManager.hh
source/analysis/hntools/src/G4P2ToolsManager.cc