Geant4: source/processes/electromagnetic/dna/molecules/management/src/G4Molecule.cc File Reference
G4Molecule.cc File Reference
#include "G4Molecule.hh"
#include "G4MolecularConfiguration.hh"
#include "Randomize.hh"
#include "G4PhysicalConstants.hh"
#include "G4SystemOfUnits.hh"
#include "G4Track.hh"
#include "G4VMoleculeCounter.hh"
Functions
ITImp (G4Molecule) G4Allocator< G4Molecule > *&aMoleculeAllocator()
G4ThreadLocal‍/G4double G4Molecule::fgTemperature = 310; // 310*kelvin;
G4Molecule * GetMolecule (const G4Track &track)
G4Molecule * GetMolecule (const G4Track *track)
Function Documentation
GetMolecule() [1/2]
G4Molecule* GetMolecule (const G4Track & track)
Definition at line 79 of file G4Molecule.cc.
Referenced by G4DNABrownianTransportation::AlongStepDoIt(), G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength(), G4DNAMoleculeEncounterStepper::CalculateStep(), G4DNABrownianTransportation::ComputeStep(), G4DNAMolecularDissociation::DecayIt(), G4DNABrownianTransportation::Diffusion(), G4DNAElectronHoleRecombination::FindReactant(), G4DNASmoluchowskiReactionModel::FindReaction(), G4DNAMolecularDissociation::GetMeanLifeTime(), G4DNAMolecularReaction::MakeReaction(), G4DNAElectronHoleRecombination::MakeReaction(), G4DNASecondOrderReaction::PostStepDoIt(), G4DNABrownianTransportation::PostStepDoIt(), G4DNASecondOrderReaction::PostStepGetPhysicalInteractionLength(), G4DNAMolecularReaction::TestReactibility(), and G4DNAMoleculeEncounterStepper::Utils::Utils().
GetMolecule() [2/2]
G4Molecule* GetMolecule (const G4Track * track)
Definition at line 86 of file G4Molecule.cc.
ITImp()
ITImp (G4Molecule) &
G4ThreadLocal‍/G4double G4Molecule::fgTemperature = 310; // 310*kelvin;
Definition at line 62 of file G4Molecule.cc.