Geant4: G4KalbachCrossSection Class Reference
G4KalbachCrossSection Class Reference
#include <G4KalbachCrossSection.hh>
Static Public Member Functions
static G4double ComputePowerParameter (G4int resA, G4int idx)
static G4double ComputeCrossSection (G4double K, G4double cb, G4double resA13, G4double amu1, G4int idx, G4int Z, G4int A, G4int resA)
Detailed Description
Definition at line 40 of file G4KalbachCrossSection.hh.
Member Function Documentation
ComputeCrossSection()
G4double G4KalbachCrossSection::ComputeCrossSection (G4double K, G4double cb, G4double resA13, G4double amu1, G4int idx, G4int Z, G4int A, G4int resA) static
Definition at line 75 of file G4KalbachCrossSection.cc.
Referenced by G4PreCompoundFragment::CrossSection(), and G4EvaporationProbability::CrossSection().
ComputePowerParameter()
G4double G4KalbachCrossSection::ComputePowerParameter (G4int resA, G4int idx) static
Definition at line 69 of file G4KalbachCrossSection.cc.
Referenced by G4PreCompoundFragment::CalcEmissionProbability(), and G4EvaporationProbability::TotalProbability().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/de_excitation/util/include/G4KalbachCrossSection.hh
source/processes/hadronic/models/de_excitation/util/src/G4KalbachCrossSection.cc