Geant4: source/processes/hadronic/models/parton_string/diffraction/src/G4FTFParameters.cc File Reference
G4FTFParameters.cc File Reference
#include <utility>
#include "G4FTFParameters.hh"
#include "G4ios.hh"
#include "G4PhysicalConstants.hh"
#include "G4SystemOfUnits.hh"
#include "G4ParticleDefinition.hh"
#include "G4Proton.hh"
#include "G4Neutron.hh"
#include "G4PionPlus.hh"
#include "G4PionMinus.hh"
#include "G4KaonPlus.hh"
#include "G4KaonMinus.hh"
#include "G4Exp.hh"
#include "G4Log.hh"
#include "G4Pow.hh"
#include "G4HadronicDeveloperParameters.hh"
Data Structures
class G4FTFSettingDefaultHDP
Variables
G4HadronicDeveloperParameters & HDP = G4HadronicDeveloperParameters::GetInstance()
G4FTFSettingDefaultHDP FTFDefaultsHDP
Variable Documentation
FTFDefaultsHDP
G4FTFSettingDefaultHDP FTFDefaultsHDP
Definition at line 159 of file G4FTFParameters.cc.
HDP
G4HadronicDeveloperParameters& HDP = G4HadronicDeveloperParameters::GetInstance()
Definition at line 53 of file G4FTFParameters.cc.
Referenced by G4FTFParamCollBaryonProj::G4FTFParamCollBaryonProj(), G4FTFParamCollection::G4FTFParamCollection(), G4FTFSettingDefaultHDP::G4FTFSettingDefaultHDP(), and G4CascadeParameters::Initialize().