Geant4: G4tgrMessenger Class Reference
G4tgrMessenger Class Reference
#include <G4tgrMessenger.hh>
Public Member Functions
G4tgrMessenger ()
~G4tgrMessenger ()
void SetNewValue (G4UIcommand *command, G4String newValues)
G4String GetCurrentValue (G4UIcommand *command)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Static Public Member Functions
static G4int GetVerboseLevel ()
static void SetVerboseLevel (G4int verb)
Private Attributes
G4UIdirectory * tgDirectory
G4UIcmdWithAnInteger * verboseCmd
Static Private Attributes
static G4ThreadLocal G4int theVerboseLevel = 0
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 48 of file G4tgrMessenger.hh.
Constructor & Destructor Documentation
G4tgrMessenger()
G4tgrMessenger::G4tgrMessenger ()
Definition at line 44 of file G4tgrMessenger.cc.
~G4tgrMessenger()
G4tgrMessenger::~G4tgrMessenger ()
Definition at line 59 of file G4tgrMessenger.cc.
Member Function Documentation
GetCurrentValue()
G4String G4tgrMessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 91 of file G4tgrMessenger.cc.
GetVerboseLevel()
G4int G4tgrMessenger::GetVerboseLevel () static
Definition at line 67 of file G4tgrMessenger.cc.
Referenced by G4tgrMaterialFactory::AddMaterialMixture(), G4tgrMaterialFactory::AddMaterialSimple(), G4tgrParameterMgr::AddParameterNumber(), G4tgrParameterMgr::AddParameterString(), G4tgrVolumeAssembly::AddPlace(), G4tgrVolume::AddPlace(), G4tgrVolume::AddPlaceParam(), G4tgrVolume::AddPlaceReplica(), G4tgrRotationMatrixFactory::AddRotMatrix(), G4tgbElement::BuildG4ElementFromIsotopes(), G4tgbElement::BuildG4ElementSimple(), G4tgbIsotope::BuildG4Isotope(), G4tgbMaterialMixtureByVolume::BuildG4Material(), G4tgbMaterialMixtureByWeight::BuildG4Material(), G4tgbMaterialMixtureByNoAtoms::BuildG4Material(), G4tgbMaterialSimple::BuildG4Material(), G4tgbRotationMatrix::BuildG4RotMatrixFrom3(), G4tgbRotationMatrix::BuildG4RotMatrixFrom6(), G4tgbRotationMatrix::BuildG4RotMatrixFrom9(), G4tgbVolume::BuildSolidForDivision(), G4tgbGeometryDumper::CheckIfPhysVolExists(), G4tgrFileIn::Close(), G4tgbPlaceParamSquare::ComputeTransformation(), G4tgbPlaceParamLinear::ComputeTransformation(), G4tgbPlaceParamCircle::ComputeTransformation(), G4tgbDetectorConstruction::Construct(), G4tgbDetectorBuilder::ConstructDetector(), G4tgbVolume::ConstructG4LogVol(), G4tgbVolume::ConstructG4PhysVol(), G4tgbVolume::ConstructG4Volumes(), G4tgbGeometryDumper::DumpPVPlacement(), G4tgrFileIn::EndOfFile(), G4tgrMaterialFactory::ErrorAlreadyExists(), G4tgrSolid::FillSolidParams(), G4tgbMaterialMgr::FindBuiltG4Element(), G4tgbMaterialMgr::FindBuiltG4Isotope(), G4tgbMaterialMgr::FindBuiltG4Material(), G4tgrMaterialFactory::FindElement(), G4tgbRotationMatrixMgr::FindG4RotMatrix(), G4tgbVolumeMgr::FindG4Solid(), G4tgbMaterialMgr::FindG4tgbElement(), G4tgbMaterialMgr::FindG4tgbIsotope(), G4tgbMaterialMgr::FindG4tgbMaterial(), G4tgrMaterialFactory::FindIsotope(), G4tgrMaterialFactory::FindMaterial(), G4tgbMaterialMgr::FindOrBuildG4Element(), G4tgbMaterialMgr::FindOrBuildG4Isotope(), G4tgbMaterialMgr::FindOrBuildG4Material(), G4tgbRotationMatrixMgr::FindOrBuildG4RotMatrix(), G4tgbVolume::FindOrConstructG4Solid(), G4tgrParameterMgr::FindParameter(), G4tgbPlaceParamCircle::G4tgbPlaceParamCircle(), G4tgbPlaceParamLinear::G4tgbPlaceParamLinear(), G4tgbPlaceParamSquare::G4tgbPlaceParamSquare(), G4tgrElementFromIsotopes::G4tgrElementFromIsotopes(), G4tgrElementSimple::G4tgrElementSimple(), G4tgrIsotope::G4tgrIsotope(), G4tgrMaterialMixture::G4tgrMaterialMixture(), G4tgrMaterialSimple::G4tgrMaterialSimple(), G4tgrPlaceDivRep::G4tgrPlaceDivRep(), G4tgrPlaceParameterisation::G4tgrPlaceParameterisation(), G4tgrPlaceSimple::G4tgrPlaceSimple(), G4tgrRotationMatrix::G4tgrRotationMatrix(), G4tgrSolid::G4tgrSolid(), G4tgrSolidBoolean::G4tgrSolidBoolean(), G4tgrVolume::G4tgrVolume(), G4tgrVolumeAssembly::G4tgrVolumeAssembly(), G4tgrVolumeDivision::G4tgrVolumeDivision(), GetCurrentValue(), G4tgrUtils::GetDouble(), G4tgbGeometryDumper::GetPVChildren(), G4tgrUtils::GetString(), G4tgbVolumeMgr::GetTopLogVol(), G4tgbVolumeMgr::GetTopPhysVol(), G4tgrVolumeMgr::GetTopVolume(), G4tgrFileIn::GetWordsInLine(), G4tgrLineProcessor::ProcessLine(), G4tgrFileReader::ReadFiles(), G4tgbVolumeMgr::RegisterMe(), and G4tgbMaterialMixtureByVolume::TransformToFractionsByWeight().
SetNewValue()
void G4tgrMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 81 of file G4tgrMessenger.cc.
SetVerboseLevel()
void G4tgrMessenger::SetVerboseLevel (G4int verb) static
Definition at line 74 of file G4tgrMessenger.cc.
Referenced by SetNewValue().
Field Documentation
tgDirectory
G4UIdirectory* G4tgrMessenger::tgDirectory private
Definition at line 62 of file G4tgrMessenger.hh.
Referenced by G4tgrMessenger(), and ~G4tgrMessenger().
theVerboseLevel
G4ThreadLocal G4int G4tgrMessenger::theVerboseLevel = 0 static private
Definition at line 64 of file G4tgrMessenger.hh.
Referenced by GetVerboseLevel(), and SetVerboseLevel().
verboseCmd
G4UIcmdWithAnInteger* G4tgrMessenger::verboseCmd private
Definition at line 63 of file G4tgrMessenger.hh.
Referenced by G4tgrMessenger(), GetCurrentValue(), SetNewValue(), and ~G4tgrMessenger().
The documentation for this class was generated from the following files:
source/persistency/ascii/include/G4tgrMessenger.hh
source/persistency/ascii/src/G4tgrMessenger.cc