Geant4: G4PolynomialPDF Class Reference
G4PolynomialPDF Class Reference
#include <G4PolynomialPDF.hh>
Public Member Functions
G4PolynomialPDF (size_t n=0, const double *coeffs=nullptr, G4double x1=0, G4double x2=1)
~G4PolynomialPDF ()
void SetNCoefficients (size_t n)
size_t GetNCoefficients () const
void SetCoefficients (const std::vector< G4double > &v)
G4double GetCoefficient (size_t i) const
void SetCoefficient (size_t i, G4double value, bool doSimplify)
void SetCoefficients (size_t n, const G4double *coeffs)
void Simplify ()
void SetDomain (G4double x1, G4double x2)
void Normalize ()
G4double Evaluate (G4double x, G4int ddxPower=0)
G4double GetRandomX ()
void SetTolerance (G4double tolerance)
G4double GetX (G4double p, G4double x1, G4double x2, G4int ddxPower=0, G4double guess=1.e99, G4bool bisect=true)
G4double EvalInverseCDF (G4double p)
G4double Bisect (G4double p, G4double x1, G4double x2)
void Dump ()
Protected Member Functions
G4bool HasNegativeMinimum (G4double x1, G4double x2)
Protected Attributes
G4double fX1
G4double fX2
std::vector< G4double > fCoefficients
G4bool fChanged
G4double fTolerance
G4int fVerbose
Detailed Description
Definition at line 49 of file G4PolynomialPDF.hh.
Constructor & Destructor Documentation
G4PolynomialPDF()
G4PolynomialPDF::G4PolynomialPDF (size_t n = 0, const double * coeffs = nullptr, G4double x1 = 0, G4double x2 = 1)
Definition at line 43 of file G4PolynomialPDF.cc.
~G4PolynomialPDF()
G4PolynomialPDF::~G4PolynomialPDF ()
Definition at line 51 of file G4PolynomialPDF.cc.
Member Function Documentation
Bisect()
G4double G4PolynomialPDF::Bisect (G4double p, G4double x1, G4double x2)
Definition at line 392 of file G4PolynomialPDF.cc.
Referenced by GetX().
Dump()
void G4PolynomialPDF::Dump ()
Definition at line 401 of file G4PolynomialPDF.cc.
Referenced by Normalize().
EvalInverseCDF()
G4double G4PolynomialPDF::EvalInverseCDF (G4double p) inline
Definition at line 102 of file G4PolynomialPDF.hh.
Referenced by GetRandomX().
Evaluate()
G4double G4PolynomialPDF::Evaluate (G4double x, G4int ddxPower = 0)
Evaluate f(x) ddxPower = -1: f = CDF ddxPower = 0: f = PDF ddxPower = 1: f = (d/dx) PDF ddxPower = 2: f = (d2/dx2) PDF
Definition at line 131 of file G4PolynomialPDF.cc.
Referenced by Bisect(), and HasNegativeMinimum().
GetCoefficient()
G4double G4PolynomialPDF::GetCoefficient (size_t i) const inline
Definition at line 62 of file G4PolynomialPDF.hh.
Referenced by Dump(), Evaluate(), GetX(), HasNegativeMinimum(), and Normalize().
GetNCoefficients()
size_t G4PolynomialPDF::GetNCoefficients () const inline
Definition at line 58 of file G4PolynomialPDF.hh.
Referenced by Dump(), Evaluate(), GetX(), HasNegativeMinimum(), Normalize(), and SetCoefficients().
GetRandomX()
G4double G4PolynomialPDF::GetRandomX ()
Definition at line 207 of file G4PolynomialPDF.cc.
Referenced by G4PolarizationTransition::GenerateGammaCosTheta().
GetX()
G4double G4PolynomialPDF::GetX (G4double p, G4double x1, G4double x2, G4int ddxPower = 0, G4double guess = 1.e99, G4bool bisect = true)
Find a value of X between x1 and x2 at which f(x) = p. ddxPower = -1: f = CDF ddxPower = 0: f = PDF ddxPower = 1: f = (d/dx) PDF Uses the Newton-Raphson method to find the zero of f(x) - p. If not found in range, returns the nearest boundary
Definition at line 223 of file G4PolynomialPDF.cc.
Referenced by Bisect(), EvalInverseCDF(), and HasNegativeMinimum().
HasNegativeMinimum()
G4bool G4PolynomialPDF::HasNegativeMinimum (G4double x1, G4double x2) protected
Definition at line 166 of file G4PolynomialPDF.cc.
Referenced by GetRandomX().
Normalize()
void G4PolynomialPDF::Normalize ()
Normalize PDF to 1 over domain fX1 to fX2. Double-check that the highest-order coefficient is non-zero.
Definition at line 100 of file G4PolynomialPDF.cc.
Referenced by GetRandomX().
SetCoefficient()
void G4PolynomialPDF::SetCoefficient (size_t i, G4double value, bool doSimplify)
Definition at line 54 of file G4PolynomialPDF.cc.
Referenced by Normalize(), and SetCoefficients().
SetCoefficients() [1/2]
void G4PolynomialPDF::SetCoefficients (const std::vector< G4double > & v) inline
Definition at line 59 of file G4PolynomialPDF.hh.
Referenced by G4PolynomialPDF(), and G4PolarizationTransition::GenerateGammaCosTheta().
SetCoefficients() [2/2]
void G4PolynomialPDF::SetCoefficients (size_t n, const G4double * coeffs)
Definition at line 63 of file G4PolynomialPDF.cc.
SetDomain()
void G4PolynomialPDF::SetDomain (G4double x1, G4double x2)
Definition at line 86 of file G4PolynomialPDF.cc.
SetNCoefficients()
void G4PolynomialPDF::SetNCoefficients (size_t n) inline
Definition at line 57 of file G4PolynomialPDF.hh.
Referenced by G4PolynomialPDF(), and SetCoefficients().
SetTolerance()
void G4PolynomialPDF::SetTolerance (G4double tolerance) inline
Definition at line 87 of file G4PolynomialPDF.hh.
Simplify()
void G4PolynomialPDF::Simplify ()
Definition at line 74 of file G4PolynomialPDF.cc.
Referenced by Normalize(), SetCoefficient(), and SetCoefficients().
Field Documentation
fChanged
G4bool G4PolynomialPDF::fChanged protected
Definition at line 114 of file G4PolynomialPDF.hh.
Referenced by GetRandomX(), SetCoefficient(), SetCoefficients(), SetDomain(), SetNCoefficients(), and Simplify().
fCoefficients
std::vector<G4double> G4PolynomialPDF::fCoefficients protected
Definition at line 113 of file G4PolynomialPDF.hh.
Referenced by GetCoefficient(), GetNCoefficients(), Normalize(), SetCoefficient(), SetCoefficients(), SetNCoefficients(), and Simplify().
fTolerance
G4double G4PolynomialPDF::fTolerance protected
Definition at line 115 of file G4PolynomialPDF.hh.
Referenced by GetX(), HasNegativeMinimum(), and SetTolerance().
fVerbose
G4int G4PolynomialPDF::fVerbose protected
Definition at line 116 of file G4PolynomialPDF.hh.
Referenced by Evaluate(), GetRandomX(), GetX(), HasNegativeMinimum(), Normalize(), SetDomain(), and Simplify().
fX1
G4double G4PolynomialPDF::fX1 protected
Definition at line 111 of file G4PolynomialPDF.hh.
Referenced by Bisect(), Dump(), EvalInverseCDF(), Evaluate(), GetRandomX(), GetX(), Normalize(), and SetDomain().
fX2
G4double G4PolynomialPDF::fX2 protected
Definition at line 112 of file G4PolynomialPDF.hh.
Referenced by Bisect(), Dump(), EvalInverseCDF(), GetRandomX(), GetX(), HasNegativeMinimum(), Normalize(), and SetDomain().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/util/include/G4PolynomialPDF.hh
source/processes/hadronic/models/util/src/G4PolynomialPDF.cc