Geant4: B4DetectorConstruction Class Reference
B4DetectorConstruction Class Reference
Detector construction class to define materials and geometry.
#include <B4DetectorConstruction.hh>
Public Member Functions
B4DetectorConstruction ()
virtual ~B4DetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
const G4VPhysicalVolume * GetAbsorberPV () const
const G4VPhysicalVolume * GetGapPV () const
B4DetectorConstruction ()
virtual ~B4DetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
const G4VPhysicalVolume * GetAbsorberPV () const
const G4VPhysicalVolume * GetGapPV () const
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
void DefineMaterials ()
G4VPhysicalVolume * DefineVolumes ()
void DefineMaterials ()
G4VPhysicalVolume * DefineVolumes ()
Private Attributes
G4VPhysicalVolume * fAbsorberPV
G4VPhysicalVolume * fGapPV
G4bool fCheckOverlaps
Static Private Attributes
static G4ThreadLocal G4GlobalMagFieldMessenger * fMagFieldMessenger = nullptr
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Detector construction class to define materials and geometry.
The calorimeter is a box made of a given number of layers. A layer consists of an absorber plate and of a detection gap. The layer is replicated.
Four parameters define the geometry of the calorimeter :
the thickness of an absorber plate,
the thickness of a gap,
the number of layers,
the transverse size of the calorimeter (the input face is a square).
In addition a transverse uniform magnetic field is defined via G4GlobalMagFieldMessenger class.
Definition at line 53 of file B4DetectorConstruction.hh.
Constructor & Destructor Documentation
B4DetectorConstruction() [1/2]
B4DetectorConstruction::B4DetectorConstruction ()
Definition at line 60 of file B4DetectorConstruction.cc.
~B4DetectorConstruction() [1/2]
B4DetectorConstruction::~B4DetectorConstruction () virtual
Definition at line 70 of file B4DetectorConstruction.cc.
B4DetectorConstruction() [2/2]
B4DetectorConstruction::B4DetectorConstruction ()
~B4DetectorConstruction() [2/2]
virtual B4DetectorConstruction::~B4DetectorConstruction () virtual
Member Function Documentation
Construct() [1/2]
G4VPhysicalVolume * B4DetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 76 of file B4DetectorConstruction.cc.
Construct() [2/2]
virtual G4VPhysicalVolume* B4DetectorConstruction::Construct () virtual
Implements G4VUserDetectorConstruction.
ConstructSDandField() [1/2]
void B4DetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 280 of file B4DetectorConstruction.cc.
ConstructSDandField() [2/2]
virtual void B4DetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
DefineMaterials() [1/2]
void B4DetectorConstruction::DefineMaterials () private
DefineMaterials() [2/2]
void B4DetectorConstruction::DefineMaterials () private
Definition at line 87 of file B4DetectorConstruction.cc.
Referenced by Construct().
DefineVolumes() [1/2]
G4VPhysicalVolume * B4DetectorConstruction::DefineVolumes () private
Definition at line 110 of file B4DetectorConstruction.cc.
Referenced by Construct().
DefineVolumes() [2/2]
G4VPhysicalVolume* B4DetectorConstruction::DefineVolumes () private
GetAbsorberPV() [1/2]
const G4VPhysicalVolume* B4DetectorConstruction::GetAbsorberPV () const
GetAbsorberPV() [2/2]
const G4VPhysicalVolume * B4DetectorConstruction::GetAbsorberPV () const inline
Definition at line 87 of file B4DetectorConstruction.hh.
Referenced by B4bSteppingAction::UserSteppingAction(), and B4aSteppingAction::UserSteppingAction().
GetGapPV() [1/2]
const G4VPhysicalVolume * B4DetectorConstruction::GetGapPV () const inline
Definition at line 91 of file B4DetectorConstruction.hh.
Referenced by B4bSteppingAction::UserSteppingAction(), and B4aSteppingAction::UserSteppingAction().
GetGapPV() [2/2]
const G4VPhysicalVolume* B4DetectorConstruction::GetGapPV () const
Field Documentation
fAbsorberPV
G4VPhysicalVolume * B4DetectorConstruction::fAbsorberPV private
Definition at line 79 of file B4DetectorConstruction.hh.
Referenced by DefineVolumes(), and GetAbsorberPV().
fCheckOverlaps
G4bool B4DetectorConstruction::fCheckOverlaps private
Definition at line 82 of file B4DetectorConstruction.hh.
Referenced by DefineVolumes().
fGapPV
G4VPhysicalVolume * B4DetectorConstruction::fGapPV private
Definition at line 80 of file B4DetectorConstruction.hh.
Referenced by DefineVolumes(), and GetGapPV().
fMagFieldMessenger
G4ThreadLocal G4GlobalMagFieldMessenger * B4DetectorConstruction::fMagFieldMessenger = nullptr static private
Definition at line 76 of file B4DetectorConstruction.hh.
Referenced by ConstructSDandField().
The documentation for this class was generated from the following files:
examples/basic/B4/B4a/include/B4DetectorConstruction.hh
examples/basic/B4/B4a/src/B4DetectorConstruction.cc