Geant4: source/global/management/include/G4Version.hh File Reference
G4Version.hh File Reference
#include "G4String.hh"
Macros
#define G4VERSION_NUMBER 1051
#define G4VERSION_TAG "$Name: geant4-10-05-patch-01 $"
Variables
static const G4String G4Version = "$Name: geant4-10-05-patch-01 $"
static const G4String G4Date = "(17-April-2019)"
Macro Definition Documentation
G4VERSION_NUMBER
#define G4VERSION_NUMBER 1051
Definition at line 47 of file G4Version.hh.
G4VERSION_TAG
#define G4VERSION_TAG "$Name: geant4-10-05-patch-01 $"
Definition at line 51 of file G4Version.hh.
Variable Documentation
G4Date
const G4String G4Date = "(17-April-2019)" static
Definition at line 63 of file G4Version.hh.
Referenced by G4HepRepSceneHandler::addTopLevelAttributes(), G4HepRepFileSceneHandler::CheckFileOpen(), export_G4Version(), and G4RunManagerKernel::G4RunManagerKernel().
G4Version
const G4String G4Version = "$Name: geant4-10-05-patch-01 $" static
Definition at line 61 of file G4Version.hh.
Referenced by G4HepRepSceneHandler::addTopLevelAttributes(), G4HepRepFileSceneHandler::CheckFileOpen(), export_G4Version(), and G4RunManagerKernel::G4RunManagerKernel().