Geant4: G4ParticleHPDataPoint Class Reference
G4ParticleHPDataPoint Class Reference
#include <G4ParticleHPDataPoint.hh>
Public Member Functions
G4ParticleHPDataPoint ()
G4ParticleHPDataPoint (G4double e, G4double x)
void operator= (const G4ParticleHPDataPoint &aSet)
G4double GetEnergy () const
G4double GetXsection () const
void SetEnergy (G4double e)
void SetXsection (G4double x)
G4double GetX () const
G4double GetY () const
void SetX (G4double e)
void SetY (G4double x)
void SetData (G4double e, G4double x)
Private Attributes
G4double energy
G4double xSec
Detailed Description
Definition at line 35 of file G4ParticleHPDataPoint.hh.
Constructor & Destructor Documentation
G4ParticleHPDataPoint() [1/2]
G4ParticleHPDataPoint::G4ParticleHPDataPoint () inline
Definition at line 39 of file G4ParticleHPDataPoint.hh.
G4ParticleHPDataPoint() [2/2]
G4ParticleHPDataPoint::G4ParticleHPDataPoint (G4double e, G4double x) inline
Definition at line 40 of file G4ParticleHPDataPoint.hh.
Member Function Documentation
GetEnergy()
G4double G4ParticleHPDataPoint::GetEnergy () const inline
Definition at line 53 of file G4ParticleHPDataPoint.hh.
Referenced by operator=().
GetX()
G4double G4ParticleHPDataPoint::GetX () const inline
Definition at line 59 of file G4ParticleHPDataPoint.hh.
Referenced by G4ParticleHPVector::Dump(), G4ParticleHPVector::Get15percentBorder(), G4ParticleHPVector::Get50percentBorder(), G4ParticleHPVector::GetEnergy(), G4ParticleHPVector::GetMeanX(), G4ParticleHPVector::GetX(), G4ParticleHPVector::GetXsec(), G4ParticleHPVector::Integrate(), G4ParticleHPVector::IntegrateAndNormalise(), G4ParticleHPVector::Sample(), G4ParticleHPVector::SampleLin(), G4ParticleHPVector::SetPoint(), and G4ParticleHPVector::ThinOut().
GetXsection()
G4double G4ParticleHPDataPoint::GetXsection () const inline
Definition at line 54 of file G4ParticleHPDataPoint.hh.
Referenced by operator=().
GetY()
G4double G4ParticleHPDataPoint::GetY () const inline
Definition at line 60 of file G4ParticleHPDataPoint.hh.
Referenced by G4ParticleHPVector::Dump(), G4ParticleHPVector::GetMeanX(), G4ParticleHPVector::GetXsec(), G4ParticleHPVector::GetY(), G4ParticleHPVector::Integrate(), G4ParticleHPVector::IntegrateAndNormalise(), G4ParticleHPVector::Sample(), G4ParticleHPVector::SetPoint(), and G4ParticleHPVector::ThinOut().
operator=()
void G4ParticleHPDataPoint::operator= (const G4ParticleHPDataPoint & aSet) inline
Definition at line 42 of file G4ParticleHPDataPoint.hh.
SetData()
void G4ParticleHPDataPoint::SetData (G4double e, G4double x) inline
Definition at line 65 of file G4ParticleHPDataPoint.hh.
Referenced by G4ParticleHPVector::SetData(), and G4ParticleHPHash::SetData().
SetEnergy()
void G4ParticleHPDataPoint::SetEnergy (G4double e) inline
Definition at line 56 of file G4ParticleHPDataPoint.hh.
SetX()
void G4ParticleHPDataPoint::SetX (G4double e) inline
Definition at line 62 of file G4ParticleHPDataPoint.hh.
Referenced by G4ParticleHPVector::SetEnergy(), and G4ParticleHPVector::SetX().
SetXsection()
void G4ParticleHPDataPoint::SetXsection (G4double x) inline
Definition at line 57 of file G4ParticleHPDataPoint.hh.
SetY()
void G4ParticleHPDataPoint::SetY (G4double x) inline
Definition at line 63 of file G4ParticleHPDataPoint.hh.
Referenced by G4ParticleHPVector::SetXsec(), G4ParticleHPVector::SetY(), and G4ParticleHPVector::Times().
Field Documentation
energy
G4double G4ParticleHPDataPoint::energy private
Definition at line 69 of file G4ParticleHPDataPoint.hh.
Referenced by G4ParticleHPDataPoint(), GetEnergy(), GetX(), operator=(), SetData(), SetEnergy(), and SetX().
xSec
G4double G4ParticleHPDataPoint::xSec private
Definition at line 70 of file G4ParticleHPDataPoint.hh.
Referenced by G4ParticleHPDataPoint(), GetXsection(), GetY(), operator=(), SetData(), SetXsection(), and SetY().
The documentation for this class was generated from the following file:
source/processes/hadronic/models/particle_hp/include/G4ParticleHPDataPoint.hh