Geant4: HepMCG4Interface Class Reference
HepMCG4Interface Class Reference
A base class for primary generation via HepMC object.
#include <HepMCG4Interface.hh>
Public Member Functions
HepMCG4Interface ()
virtual ~HepMCG4Interface ()
HepMC::GenEvent * GetHepMCGenEvent () const
virtual void GeneratePrimaryVertex (G4Event *anEvent)
HepMCG4Interface ()
virtual ~HepMCG4Interface ()
HepMC::GenEvent * GetHepMCGenEvent () const
virtual void GeneratePrimaryVertex (G4Event *anEvent)
Public Member Functions inherited from G4VPrimaryGenerator
G4VPrimaryGenerator ()
virtual ~G4VPrimaryGenerator ()
G4ThreeVector GetParticlePosition ()
G4double GetParticleTime ()
void SetParticlePosition (G4ThreeVector aPosition)
void SetParticleTime (G4double aTime)
Protected Member Functions
virtual G4bool CheckVertexInsideWorld (const G4ThreeVector &pos) const
void HepMC2G4 (const HepMC::GenEvent *hepmcevt, G4Event *g4event)
virtual HepMC::GenEvent * GenerateHepMCEvent ()
virtual G4bool CheckVertexInsideWorld (const G4ThreeVector &pos) const
void HepMC2G4 (const HepMC::GenEvent *hepmcevt, G4Event *g4event)
virtual HepMC::GenEvent * GenerateHepMCEvent ()
Protected Attributes
HepMC::GenEvent * hepmcEvent
Protected Attributes inherited from G4VPrimaryGenerator
G4ThreeVector particle_position
G4double particle_time
Additional Inherited Members
Static Public Member Functions inherited from G4VPrimaryGenerator
static G4bool CheckVertexInsideWorld (const G4ThreeVector &pos)
Detailed Description
A base class for primary generation via HepMC object.
This class is derived from G4VPrimaryGenerator.
Definition at line 40 of file HepMCG4Interface.hh.
Constructor & Destructor Documentation
HepMCG4Interface() [1/2]
HepMCG4Interface::HepMCG4Interface ()
Definition at line 43 of file HepMCG4Interface.cc.
~HepMCG4Interface() [1/2]
HepMCG4Interface::~HepMCG4Interface () virtual
Definition at line 49 of file HepMCG4Interface.cc.
HepMCG4Interface() [2/2]
HepMCG4Interface::HepMCG4Interface ()
~HepMCG4Interface() [2/2]
virtual HepMCG4Interface::~HepMCG4Interface () virtual
Member Function Documentation
CheckVertexInsideWorld() [1/2]
G4bool HepMCG4Interface::CheckVertexInsideWorld (const G4ThreeVector & pos) const protected virtual
Definition at line 56 of file HepMCG4Interface.cc.
Referenced by HepMC2G4().
CheckVertexInsideWorld() [2/2]
virtual G4bool HepMCG4Interface::CheckVertexInsideWorld (const G4ThreeVector & pos) const protected virtual
GenerateHepMCEvent() [1/2]
virtual HepMC::GenEvent* HepMCG4Interface::GenerateHepMCEvent () protected virtual
Reimplemented in HepMCG4PythiaInterface, HepMCG4PythiaInterface, HepMCG4AsciiReader, and HepMCG4AsciiReader.
GenerateHepMCEvent() [2/2]
HepMC::GenEvent * HepMCG4Interface::GenerateHepMCEvent () protected virtual
Reimplemented in HepMCG4PythiaInterface, HepMCG4PythiaInterface, HepMCG4AsciiReader, and HepMCG4AsciiReader.
Definition at line 118 of file HepMCG4Interface.cc.
Referenced by GeneratePrimaryVertex().
GeneratePrimaryVertex() [1/2]
void HepMCG4Interface::GeneratePrimaryVertex (G4Event * anEvent) virtual
Implements G4VPrimaryGenerator.
Definition at line 125 of file HepMCG4Interface.cc.
GeneratePrimaryVertex() [2/2]
virtual void HepMCG4Interface::GeneratePrimaryVertex (G4Event * anEvent) virtual
Implements G4VPrimaryGenerator.
GetHepMCGenEvent() [1/2]
HepMC::GenEvent* HepMCG4Interface::GetHepMCGenEvent () const
GetHepMCGenEvent() [2/2]
HepMC::GenEvent * HepMCG4Interface::GetHepMCGenEvent () const inline
Definition at line 73 of file HepMCG4Interface.hh.
HepMC2G4() [1/2]
void HepMCG4Interface::HepMC2G4 (const HepMC::GenEvent * hepmcevt, G4Event * g4event) protected
Definition at line 70 of file HepMCG4Interface.cc.
Referenced by GeneratePrimaryVertex().
HepMC2G4() [2/2]
void HepMCG4Interface::HepMC2G4 (const HepMC::GenEvent * hepmcevt, G4Event * g4event) protected
Field Documentation
hepmcEvent
HepMC::GenEvent * HepMCG4Interface::hepmcEvent protected
Definition at line 45 of file HepMCG4Interface.hh.
Referenced by GeneratePrimaryVertex(), GetHepMCGenEvent(), and ~HepMCG4Interface().
The documentation for this class was generated from the following files:
examples/extended/eventgenerator/HepMC/HepMCEx01/include/HepMCG4Interface.hh
examples/extended/eventgenerator/HepMC/HepMCEx01/src/HepMCG4Interface.cc