Geant4: G4VDigiCollection Class Reference
G4VDigiCollection Class Reference
#include <G4VDigiCollection.hh>
Public Member Functions
G4VDigiCollection ()
G4VDigiCollection (G4String DMnam, G4String colNam)
virtual ~G4VDigiCollection ()
G4bool operator== (const G4VDigiCollection &right) const
virtual void DrawAllDigi ()
virtual void PrintAllDigi ()
G4String GetName ()
G4String GetDMname ()
virtual G4VDigi * GetDigi (size_t) const
virtual size_t GetSize () const
Protected Attributes
G4String collectionName
G4String DMname
Detailed Description
Definition at line 44 of file G4VDigiCollection.hh.
Constructor & Destructor Documentation
G4VDigiCollection() [1/2]
G4VDigiCollection::G4VDigiCollection ()
Definition at line 33 of file G4VDigiCollection.cc.
G4VDigiCollection() [2/2]
G4VDigiCollection::G4VDigiCollection (G4String DMnam, G4String colNam)
Definition at line 39 of file G4VDigiCollection.cc.
~G4VDigiCollection()
G4VDigiCollection::~G4VDigiCollection () virtual
Definition at line 45 of file G4VDigiCollection.cc.
Member Function Documentation
DrawAllDigi()
void G4VDigiCollection::DrawAllDigi () virtual
Reimplemented in G4TDigiCollection< T >.
Definition at line 54 of file G4VDigiCollection.cc.
Referenced by G4Event::Draw().
GetDigi()
virtual G4VDigi* G4VDigiCollection::GetDigi (size_t) const inline virtual
Reimplemented in G4TDigiCollection< T >.
Definition at line 71 of file G4VDigiCollection.hh.
GetDMname()
G4String G4VDigiCollection::GetDMname () inline
Definition at line 64 of file G4VDigiCollection.hh.
GetName()
G4String G4VDigiCollection::GetName (void) inline
Definition at line 62 of file G4VDigiCollection.hh.
Referenced by G4DigiManager::SetDigiCollection(), and G4VDigitizerModule::StoreDigiCollection().
GetSize()
virtual size_t G4VDigiCollection::GetSize () const inline virtual
Reimplemented in G4TDigiCollection< T >.
Definition at line 72 of file G4VDigiCollection.hh.
Referenced by G4DigiModel::DescribeYourselfTo().
operator==()
G4bool G4VDigiCollection::operator== (const G4VDigiCollection & right) const
Definition at line 48 of file G4VDigiCollection.cc.
PrintAllDigi()
void G4VDigiCollection::PrintAllDigi () virtual
Reimplemented in G4TDigiCollection< T >.
Definition at line 57 of file G4VDigiCollection.cc.
Field Documentation
collectionName
G4String G4VDigiCollection::collectionName protected
Definition at line 58 of file G4VDigiCollection.hh.
Referenced by G4VDigiCollection(), GetName(), operator==(), and G4DigiCollection::operator==().
DMname
G4String G4VDigiCollection::DMname protected
Definition at line 59 of file G4VDigiCollection.hh.
Referenced by G4VDigiCollection(), GetDMname(), and operator==().
The documentation for this class was generated from the following files:
source/digits_hits/digits/include/G4VDigiCollection.hh
source/digits_hits/digits/src/G4VDigiCollection.cc