Geant4: G4LevelManager Class Reference
G4LevelManager Class Reference
#include <G4LevelManager.hh>
Public Member Functions
G4LevelManager (G4int Z, G4int A, size_t nlev, const std::vector< G4double > &energies, const std::vector< G4int > &spin, const std::vector< const G4NucLevel * > &levels)
~G4LevelManager ()
size_t NumberOfTransitions () const
const G4NucLevel * GetLevel (size_t i) const
G4double LevelEnergy (size_t i) const
G4double MaxLevelEnergy () const
size_t NearestLevelIndex (G4double energy, size_t index=0) const
size_t NearestLowEdgeLevelIndex (G4double energy) const
const G4NucLevel * NearestLevel (G4double energy, size_t index=0) const
G4double NearestLevelEnergy (G4double energy, size_t index=0) const
G4double NearestLowEdgeLevelEnergy (G4double energy) const
G4double LifeTime (size_t i) const
G4int SpinTwo (size_t i) const
G4int Parity (size_t i) const
G4int FloatingLevel (size_t i) const
G4double PairingCorrection () const
G4double ShellCorrection () const
G4double LevelDensity (G4double U) const
const G4String & FloatingType (size_t i) const
void StreamInfo (std::ostream &os) const
Private Member Functions
G4LevelManager (const G4LevelManager &right)=delete
const G4LevelManager & operator= (const G4LevelManager &right)=delete
G4bool operator== (const G4LevelManager &right) const =delete
G4bool operator!= (const G4LevelManager &right) const =delete
Private Attributes
std::vector< G4double > fLevelEnergy
std::vector< G4int > fSpin
std::vector< const G4NucLevel * > fLevels
G4double fPairingCorrection
G4double fShellCorrection
G4double fLevelDensity
size_t nTransitions
Static Private Attributes
static const G4int nfloting = 13
static G4String fFloatingLevels [nfloting]
Detailed Description
Definition at line 53 of file G4LevelManager.hh.
Constructor & Destructor Documentation
G4LevelManager() [1/2]
G4LevelManager::G4LevelManager (G4int Z, G4int A, size_t nlev, const std::vector< G4double > & energies, const std::vector< G4int > & spin, const std::vector< const G4NucLevel * > & levels) explicit
Definition at line 52 of file G4LevelManager.cc.
~G4LevelManager()
G4LevelManager::~G4LevelManager ()
Definition at line 94 of file G4LevelManager.cc.
G4LevelManager() [2/2]
G4LevelManager::G4LevelManager (const G4LevelManager & right) private delete
Member Function Documentation
FloatingLevel()
G4int G4LevelManager::FloatingLevel (size_t i) const inline
Definition at line 213 of file G4LevelManager.hh.
Referenced by G4PhotonEvaporation::GenerateGamma(), and StreamInfo().
FloatingType()
const G4String & G4LevelManager::FloatingType (size_t i) const
Definition at line 127 of file G4LevelManager.cc.
GetLevel()
const G4NucLevel * G4LevelManager::GetLevel (size_t i) const inline
Definition at line 141 of file G4LevelManager.hh.
Referenced by G4PhotonEvaporation::GenerateGamma(), and NearestLevel().
LevelDensity()
G4double G4LevelManager::LevelDensity (G4double U) const inline
Definition at line 231 of file G4LevelManager.hh.
Referenced by G4NuclearLevelData::GetLevelDensity().
LevelEnergy()
G4double G4LevelManager::LevelEnergy (size_t i) const inline
Definition at line 149 of file G4LevelManager.hh.
Referenced by G4GEMChannelVI::FindLevel(), G4NuclearLevelData::FindLevel(), G4PhotonEvaporation::GenerateGamma(), G4FermiFragmentsPoolVI::Initialise(), NearestLevelEnergy(), and NearestLowEdgeLevelEnergy().
LifeTime()
G4double G4LevelManager::LifeTime (size_t i) const inline
Definition at line 189 of file G4LevelManager.hh.
Referenced by G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), G4PhotonEvaporation::GenerateGamma(), and G4FermiFragmentsPoolVI::Initialise().
MaxLevelEnergy()
G4double G4LevelManager::MaxLevelEnergy () const inline
Definition at line 157 of file G4LevelManager.hh.
Referenced by G4GEMChannelVI::G4GEMChannelVI(), and G4PhotonEvaporation::InitialiseLevelManager().
NearestLevel()
const G4NucLevel * G4LevelManager::NearestLevel (G4double energy, size_t index = 0) const inline
Definition at line 173 of file G4LevelManager.hh.
NearestLevelEnergy()
G4double G4LevelManager::NearestLevelEnergy (G4double energy, size_t index = 0) const inline
Definition at line 179 of file G4LevelManager.hh.
Referenced by G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), G4PhotonEvaporation::GetFinalLevelEnergy(), and G4NuclearLevelData::GetLevelEnergy().
NearestLevelIndex()
size_t G4LevelManager::NearestLevelIndex (G4double energy, size_t index = 0) const
Definition at line 100 of file G4LevelManager.cc.
Referenced by G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), G4NuclearLevelData::FindLevel(), G4PhotonEvaporation::GenerateGamma(), NearestLevel(), and NearestLevelEnergy().
NearestLowEdgeLevelEnergy()
G4double G4LevelManager::NearestLowEdgeLevelEnergy (G4double energy) const inline
Definition at line 184 of file G4LevelManager.hh.
Referenced by G4UnstableFragmentBreakUp::BreakUpChain(), and G4NuclearLevelData::GetLowEdgeLevelEnergy().
NearestLowEdgeLevelIndex()
size_t G4LevelManager::NearestLowEdgeLevelIndex (G4double energy) const inline
Definition at line 162 of file G4LevelManager.hh.
Referenced by G4GEMChannelVI::FindLevel(), and NearestLowEdgeLevelEnergy().
NumberOfTransitions()
size_t G4LevelManager::NumberOfTransitions () const inline
Definition at line 136 of file G4LevelManager.hh.
Referenced by G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), G4GEMChannelVI::FindLevel(), G4NuclearLevelData::FindLevel(), G4NuclearLevelData::GetLevelEnergy(), G4FermiFragmentsPoolVI::Initialise(), and G4NuclearLevelData::StreamLevels().
operator!=()
G4bool G4LevelManager::operator!= (const G4LevelManager & right) const private delete
operator=()
const G4LevelManager& G4LevelManager::operator= (const G4LevelManager & right) private delete
operator==()
G4bool G4LevelManager::operator== (const G4LevelManager & right) const private delete
PairingCorrection()
G4double G4LevelManager::PairingCorrection () const inline
Definition at line 221 of file G4LevelManager.hh.
Referenced by G4NuclearLevelData::GetPairingCorrection().
Parity()
G4int G4LevelManager::Parity (size_t i) const inline
Definition at line 205 of file G4LevelManager.hh.
Referenced by StreamInfo().
ShellCorrection()
G4double G4LevelManager::ShellCorrection () const inline
Definition at line 226 of file G4LevelManager.hh.
SpinTwo()
G4int G4LevelManager::SpinTwo (size_t i) const inline
Definition at line 197 of file G4LevelManager.hh.
Referenced by G4GEMChannelVI::FindLevel(), G4PhotonEvaporation::GenerateGamma(), G4FermiFragmentsPoolVI::Initialise(), and StreamInfo().
StreamInfo()
void G4LevelManager::StreamInfo (std::ostream & os) const
Definition at line 146 of file G4LevelManager.cc.
Referenced by G4NuclearLevelData::StreamLevels().
Field Documentation
fFloatingLevels
G4String G4LevelManager::fFloatingLevels static private
Initial value:
= {
  "-", "+X", "+Y", "+Z", "+U", "+V", "+W", "+R", "+S", "+T", "+A", "+B", "+C"}
Definition at line 132 of file G4LevelManager.hh.
Referenced by FloatingType().
fLevelDensity
G4double G4LevelManager::fLevelDensity private
Definition at line 127 of file G4LevelManager.hh.
Referenced by G4LevelManager(), and LevelDensity().
fLevelEnergy
std::vector<G4double> G4LevelManager::fLevelEnergy private
Definition at line 121 of file G4LevelManager.hh.
Referenced by G4LevelManager(), LevelEnergy(), MaxLevelEnergy(), NearestLevelIndex(), NearestLowEdgeLevelIndex(), and StreamInfo().
fLevels
std::vector<const G4NucLevel*> G4LevelManager::fLevels private
Definition at line 123 of file G4LevelManager.hh.
Referenced by G4LevelManager(), GetLevel(), LifeTime(), StreamInfo(), and ~G4LevelManager().
fPairingCorrection
G4double G4LevelManager::fPairingCorrection private
Definition at line 125 of file G4LevelManager.hh.
Referenced by G4LevelManager(), and PairingCorrection().
fShellCorrection
G4double G4LevelManager::fShellCorrection private
Definition at line 126 of file G4LevelManager.hh.
Referenced by G4LevelManager(), and ShellCorrection().
fSpin
std::vector<G4int> G4LevelManager::fSpin private
Definition at line 122 of file G4LevelManager.hh.
Referenced by FloatingLevel(), FloatingType(), G4LevelManager(), Parity(), and SpinTwo().
nfloting
const G4int G4LevelManager::nfloting = 13 static private
Definition at line 131 of file G4LevelManager.hh.
nTransitions
size_t G4LevelManager::nTransitions private
Definition at line 129 of file G4LevelManager.hh.
Referenced by FloatingLevel(), FloatingType(), G4LevelManager(), GetLevel(), LevelEnergy(), LifeTime(), MaxLevelEnergy(), NearestLevelIndex(), NearestLowEdgeLevelIndex(), NumberOfTransitions(), Parity(), SpinTwo(), StreamInfo(), and ~G4LevelManager().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/de_excitation/management/include/G4LevelManager.hh
source/processes/hadronic/models/de_excitation/management/src/G4LevelManager.cc