Geant4: G4DrawVoxels Class Reference
G4DrawVoxels Class Reference
#include <G4DrawVoxels.hh>
Public Member Functions
G4DrawVoxels ()
~G4DrawVoxels ()
void DrawVoxels (const G4LogicalVolume *lv) const
G4PlacedPolyhedronList * CreatePlacedPolyhedra (const G4LogicalVolume *) const
void SetVoxelsVisAttributes (G4VisAttributes &, G4VisAttributes &, G4VisAttributes &)
void SetBoundingBoxVisAttributes (G4VisAttributes &)
Private Member Functions
void ComputeVoxelPolyhedra (const G4LogicalVolume *, const G4SmartVoxelHeader *, G4VoxelLimits &, G4PlacedPolyhedronList *) const
G4DrawVoxels (const G4DrawVoxels &)
G4DrawVoxels operator= (const G4DrawVoxels &)
Private Attributes
G4VisAttributes fVoxelsVisAttributes [3]
G4VisAttributes fBoundingBoxVisAttributes
Detailed Description
Definition at line 55 of file G4DrawVoxels.hh.
Constructor & Destructor Documentation
G4DrawVoxels() [1/2]
G4DrawVoxels::G4DrawVoxels ()
Definition at line 55 of file G4DrawVoxels.cc.
~G4DrawVoxels()
G4DrawVoxels::~G4DrawVoxels ()
Definition at line 65 of file G4DrawVoxels.cc.
G4DrawVoxels() [2/2]
G4DrawVoxels::G4DrawVoxels (const G4DrawVoxels &) private
Member Function Documentation
ComputeVoxelPolyhedra()
void G4DrawVoxels::ComputeVoxelPolyhedra (const G4LogicalVolume * lv, const G4SmartVoxelHeader * header, G4VoxelLimits & limit, G4PlacedPolyhedronList * ppl) const private
Definition at line 88 of file G4DrawVoxels.cc.
Referenced by CreatePlacedPolyhedra().
CreatePlacedPolyhedra()
G4PlacedPolyhedronList * G4DrawVoxels::CreatePlacedPolyhedra (const G4LogicalVolume * lv) const
Definition at line 193 of file G4DrawVoxels.cc.
Referenced by G4LogicalVolumeModel::DescribeYourselfTo(), and DrawVoxels().
DrawVoxels()
void G4DrawVoxels::DrawVoxels (const G4LogicalVolume * lv) const
Definition at line 201 of file G4DrawVoxels.cc.
operator=()
G4DrawVoxels G4DrawVoxels::operator= (const G4DrawVoxels &) private
SetBoundingBoxVisAttributes()
void G4DrawVoxels::SetBoundingBoxVisAttributes (G4VisAttributes & VA_boundingbox)
Definition at line 80 of file G4DrawVoxels.cc.
SetVoxelsVisAttributes()
void G4DrawVoxels::SetVoxelsVisAttributes (G4VisAttributes & VA_voxelX, G4VisAttributes & VA_voxelY, G4VisAttributes & VA_voxelZ)
Definition at line 71 of file G4DrawVoxels.cc.
Field Documentation
fBoundingBoxVisAttributes
G4VisAttributes G4DrawVoxels::fBoundingBoxVisAttributes private
Definition at line 79 of file G4DrawVoxels.hh.
Referenced by ComputeVoxelPolyhedra(), G4DrawVoxels(), and SetBoundingBoxVisAttributes().
fVoxelsVisAttributes
G4VisAttributes G4DrawVoxels::fVoxelsVisAttributes[3] private
Definition at line 78 of file G4DrawVoxels.hh.
Referenced by ComputeVoxelPolyhedra(), G4DrawVoxels(), and SetVoxelsVisAttributes().
The documentation for this class was generated from the following files:
source/geometry/navigation/include/G4DrawVoxels.hh
source/geometry/navigation/src/G4DrawVoxels.cc