Geant4: ClusterSBPoints Class Reference
ClusterSBPoints Class Reference
define a cluster of SB Points
#include <ClusterSBPoints.hh>
Public Member Functions
ClusterSBPoints (std::set< SBPoint * > pPoints)
~ClusterSBPoints ()
bool IsDSB () const
bool IsSSB () const
unsigned int GetSize () const
void AddSBPoint (SBPoint *pSBPoint)
G4ThreeVector GetBarycenter () const
G4double GetEdep () const
void FindAllPointsPossible (std::vector< SBPoint * > *ptToCheck, G4int minPts, G4double minDist)
void NoticeInternalPts ()
will set to all store SBPoint they are part of this cluster
bool HasIn (const SBPoint *, G4double)
bool HasInBarycenter (const SBPoint *, G4double)
void MergeWith (ClusterSBPoints *)
this will insert all registredSBPoint from the given cluster to this cluster.
std::set< SBPoint * > GetRegistredSBPoints () const
void Clear ()
Private Member Functions
void UpdateDoubleStrand ()
Private Attributes
unsigned int fSize
bool fIsDoubleSB
std::set< SBPoint * > fpRegisteredSBPoints
Detailed Description
define a cluster of SB Points
Definition at line 47 of file ClusterSBPoints.hh.
Constructor & Destructor Documentation
ClusterSBPoints()
ClusterSBPoints::ClusterSBPoints (std::set< SBPoint * > pPoints)
Definition at line 46 of file ClusterSBPoints.cc.
~ClusterSBPoints()
ClusterSBPoints::~ClusterSBPoints ()
Definition at line 59 of file ClusterSBPoints.cc.
Member Function Documentation
AddSBPoint()
void ClusterSBPoints::AddSBPoint (SBPoint * pSBPoint)
Definition at line 78 of file ClusterSBPoints.cc.
Referenced by ClusterSBPoints(), FindAllPointsPossible(), and MergeWith().
Clear()
void ClusterSBPoints::Clear ()
Definition at line 64 of file ClusterSBPoints.cc.
Referenced by MergeWith(), and ~ClusterSBPoints().
FindAllPointsPossible()
void ClusterSBPoints::FindAllPointsPossible (std::vector< SBPoint * > * ptToCheck, G4int minPts, G4double minDist)
Definition at line 191 of file ClusterSBPoints.cc.
GetBarycenter()
G4ThreeVector ClusterSBPoints::GetBarycenter () const
Definition at line 89 of file ClusterSBPoints.cc.
Referenced by HasInBarycenter().
GetEdep()
G4double ClusterSBPoints::GetEdep () const
Definition at line 113 of file ClusterSBPoints.cc.
GetRegistredSBPoints()
std::set<SBPoint* > ClusterSBPoints::GetRegistredSBPoints () const inline
Definition at line 84 of file ClusterSBPoints.hh.
Referenced by MergeWith().
GetSize()
unsigned int ClusterSBPoints::GetSize () const inline
Definition at line 63 of file ClusterSBPoints.hh.
Referenced by FindAllPointsPossible().
HasIn()
bool ClusterSBPoints::HasIn (const SBPoint * pPtToCheck, G4double pMinDist)
Definition at line 223 of file ClusterSBPoints.cc.
HasInBarycenter()
bool ClusterSBPoints::HasInBarycenter (const SBPoint * pPtToCheck, G4double pMinDist)
Definition at line 246 of file ClusterSBPoints.cc.
Referenced by FindAllPointsPossible().
IsDSB()
bool ClusterSBPoints::IsDSB () const inline
Definition at line 53 of file ClusterSBPoints.hh.
Referenced by IsSSB().
IsSSB()
bool ClusterSBPoints::IsSSB () const inline
Definition at line 58 of file ClusterSBPoints.hh.
MergeWith()
void ClusterSBPoints::MergeWith (ClusterSBPoints * pCluster)
this will insert all registredSBPoint from the given cluster to this cluster.
Definition at line 273 of file ClusterSBPoints.cc.
NoticeInternalPts()
void ClusterSBPoints::NoticeInternalPts ()
will set to all store SBPoint they are part of this cluster
UpdateDoubleStrand()
void ClusterSBPoints::UpdateDoubleStrand () private
Definition at line 128 of file ClusterSBPoints.cc.
Referenced by AddSBPoint(), and ClusterSBPoints().
Field Documentation
fIsDoubleSB
bool ClusterSBPoints::fIsDoubleSB private
Definition at line 95 of file ClusterSBPoints.hh.
Referenced by IsDSB(), and UpdateDoubleStrand().
fpRegisteredSBPoints
std::set<SBPoint* > ClusterSBPoints::fpRegisteredSBPoints private
Definition at line 97 of file ClusterSBPoints.hh.
Referenced by AddSBPoint(), Clear(), FindAllPointsPossible(), GetBarycenter(), GetEdep(), GetRegistredSBPoints(), GetSize(), HasIn(), and UpdateDoubleStrand().
fSize
unsigned int ClusterSBPoints::fSize private
Definition at line 94 of file ClusterSBPoints.hh.
The documentation for this class was generated from the following files:
examples/extended/medical/dna/clustering/include/ClusterSBPoints.hh
examples/extended/medical/dna/clustering/src/ClusterSBPoints.cc