Geant4: G4MolecularDissociationChannel Class Reference
G4MolecularDissociationChannel Class Reference
#include <G4MolecularDissociationChannel.hh>
Public Member Functions
G4MolecularDissociationChannel ()
G4MolecularDissociationChannel (G4String)
~G4MolecularDissociationChannel ()
G4MolecularDissociationChannel (const G4MolecularDissociationChannel &)
G4MolecularDissociationChannel & operator= (const G4MolecularDissociationChannel &right)
void AddProduct (const G4Molecule *, G4double=0)
void AddProduct (G4MolecularConfiguration *, G4double=0)
void AddProduct (const G4String &molecule, G4double displacement=0)
void SetName (const G4String &)
void SetEnergy (G4double)
void SetProbability (G4double)
void SetDecayTime (G4double)
void SetRMSMotherMoleculeDisplacement (G4double)
void SetDisplacementType (DisplacementType)
const G4String & GetName () const
G4int GetNbProducts () const
G4MolecularConfiguration * GetProduct (int) const
const std::vector< G4double > & GetRMSProductsDisplacement () const
G4double GetEnergy () const
G4double GetProbability () const
G4double GetDecayTime () const
G4double GetRMSMotherMoleculeDisplacement () const
DisplacementType GetDisplacementType () const
G4double GetRMSRadialDisplacementOfProduct (const G4Molecule *)
Private Attributes
DisplacementType fDisplacementType
G4String fName
std::vector< G4MolecularConfiguration * > * fProductsVector
G4double fReleasedEnergy
G4double fProbability
G4double fDecayTime
G4double fRMSMotherMoleculeDisplacement
std::vector< G4double > fRMSProductsDisplacementVector
Detailed Description
Definition at line 73 of file G4MolecularDissociationChannel.hh.
Constructor & Destructor Documentation
G4MolecularDissociationChannel() [1/3]
G4MolecularDissociationChannel::G4MolecularDissociationChannel ()
Definition at line 70 of file G4MolecularDissociationChannel.cc.
G4MolecularDissociationChannel() [2/3]
G4MolecularDissociationChannel::G4MolecularDissociationChannel (G4String aName)
Definition at line 55 of file G4MolecularDissociationChannel.cc.
~G4MolecularDissociationChannel()
G4MolecularDissociationChannel::~G4MolecularDissociationChannel ()
Definition at line 84 of file G4MolecularDissociationChannel.cc.
G4MolecularDissociationChannel() [3/3]
G4MolecularDissociationChannel::G4MolecularDissociationChannel (const G4MolecularDissociationChannel & right)
Definition at line 96 of file G4MolecularDissociationChannel.cc.
Member Function Documentation
AddProduct() [1/3]
void G4MolecularDissociationChannel::AddProduct (const G4Molecule * molecule, G4double displacement = 0)
Definition at line 132 of file G4MolecularDissociationChannel.cc.
Referenced by G4EmDNAChemistry::ConstructDissociationChannels(), G4EmDNAChemistry_option1::ConstructDissociationChannels(), and G4DNAElectronHoleRecombination::IsApplicable().
AddProduct() [2/3]
void G4MolecularDissociationChannel::AddProduct (const G4String & molecule, G4double displacement = 0)
Definition at line 155 of file G4MolecularDissociationChannel.cc.
AddProduct() [3/3]
void G4MolecularDissociationChannel::AddProduct (G4MolecularConfiguration * molecule, G4double displacement = 0)
Definition at line 144 of file G4MolecularDissociationChannel.cc.
GetDecayTime()
G4double G4MolecularDissociationChannel::GetDecayTime () const inline
Definition at line 199 of file G4MolecularDissociationChannel.hh.
GetDisplacementType()
DisplacementType G4MolecularDissociationChannel::GetDisplacementType () const inline
Definition at line 223 of file G4MolecularDissociationChannel.hh.
Referenced by G4DNAWaterDissociationDisplacer::GetMotherMoleculeDisplacement(), and G4DNAWaterDissociationDisplacer::GetProductsDisplacement().
GetEnergy()
G4double G4MolecularDissociationChannel::GetEnergy () const inline
Definition at line 185 of file G4MolecularDissociationChannel.hh.
Referenced by G4DNAMolecularDissociation::DecayIt().
GetName()
const G4String & G4MolecularDissociationChannel::GetName (void) const inline
Definition at line 170 of file G4MolecularDissociationChannel.hh.
Referenced by G4DNAMolecularDissociation::DecayIt(), and G4DNAWaterDissociationDisplacer::GetProductsDisplacement().
GetNbProducts()
G4int G4MolecularDissociationChannel::GetNbProducts () const
Definition at line 168 of file G4MolecularDissociationChannel.cc.
Referenced by G4DNAMolecularDissociation::DecayIt(), and G4DNAWaterDissociationDisplacer::GetProductsDisplacement().
GetProbability()
G4double G4MolecularDissociationChannel::GetProbability () const inline
Definition at line 192 of file G4MolecularDissociationChannel.hh.
Referenced by G4DNAMolecularDissociation::DecayIt().
GetProduct()
G4MolecularConfiguration * G4MolecularDissociationChannel::GetProduct (int index) const
Definition at line 176 of file G4MolecularDissociationChannel.cc.
Referenced by G4DNAMolecularDissociation::DecayIt(), and G4DNAWaterDissociationDisplacer::GetProductsDisplacement().
GetRMSMotherMoleculeDisplacement()
G4double G4MolecularDissociationChannel::GetRMSMotherMoleculeDisplacement () const inline
Definition at line 207 of file G4MolecularDissociationChannel.hh.
GetRMSProductsDisplacement()
const std::vector< G4double > & G4MolecularDissociationChannel::GetRMSProductsDisplacement () const inline
Definition at line 178 of file G4MolecularDissociationChannel.hh.
GetRMSRadialDisplacementOfProduct()
G4double G4MolecularDissociationChannel::GetRMSRadialDisplacementOfProduct (const G4Molecule * product)
Definition at line 188 of file G4MolecularDissociationChannel.cc.
operator=()
G4MolecularDissociationChannel & G4MolecularDissociationChannel::operator= (const G4MolecularDissociationChannel & right)
Definition at line 104 of file G4MolecularDissociationChannel.cc.
SetDecayTime()
void G4MolecularDissociationChannel::SetDecayTime (G4double value) inline
Definition at line 154 of file G4MolecularDissociationChannel.hh.
SetDisplacementType()
void G4MolecularDissociationChannel::SetDisplacementType (DisplacementType aDisplacementType) inline
Definition at line 215 of file G4MolecularDissociationChannel.hh.
Referenced by G4EmDNAChemistry::ConstructDissociationChannels(), G4EmDNAChemistry_option1::ConstructDissociationChannels(), and G4DNAElectronHoleRecombination::IsApplicable().
SetEnergy()
void G4MolecularDissociationChannel::SetEnergy (G4double value) inline
Definition at line 140 of file G4MolecularDissociationChannel.hh.
Referenced by G4EmDNAChemistry::ConstructDissociationChannels(), and G4EmDNAChemistry_option1::ConstructDissociationChannels().
SetName()
void G4MolecularDissociationChannel::SetName (const G4String & value) inline
Definition at line 133 of file G4MolecularDissociationChannel.hh.
SetProbability()
void G4MolecularDissociationChannel::SetProbability (G4double value) inline
Definition at line 147 of file G4MolecularDissociationChannel.hh.
Referenced by G4EmDNAChemistry::ConstructDissociationChannels(), G4EmDNAChemistry_option1::ConstructDissociationChannels(), and G4DNAElectronHoleRecombination::IsApplicable().
SetRMSMotherMoleculeDisplacement()
void G4MolecularDissociationChannel::SetRMSMotherMoleculeDisplacement (G4double value) inline
Definition at line 163 of file G4MolecularDissociationChannel.hh.
Field Documentation
fDecayTime
G4double G4MolecularDissociationChannel::fDecayTime private
Definition at line 124 of file G4MolecularDissociationChannel.hh.
Referenced by G4MolecularDissociationChannel(), GetDecayTime(), operator=(), and SetDecayTime().
fDisplacementType
DisplacementType G4MolecularDissociationChannel::fDisplacementType private
Definition at line 118 of file G4MolecularDissociationChannel.hh.
Referenced by G4MolecularDissociationChannel(), GetDisplacementType(), operator=(), and SetDisplacementType().
fName
G4String G4MolecularDissociationChannel::fName private
Definition at line 119 of file G4MolecularDissociationChannel.hh.
Referenced by GetName(), operator=(), and SetName().
fProbability
G4double G4MolecularDissociationChannel::fProbability private
Definition at line 123 of file G4MolecularDissociationChannel.hh.
Referenced by G4MolecularDissociationChannel(), GetProbability(), operator=(), and SetProbability().
fProductsVector
std::vector<G4MolecularConfiguration*>* G4MolecularDissociationChannel::fProductsVector private
Definition at line 121 of file G4MolecularDissociationChannel.hh.
Referenced by AddProduct(), G4MolecularDissociationChannel(), GetNbProducts(), GetProduct(), GetRMSRadialDisplacementOfProduct(), operator=(), and ~G4MolecularDissociationChannel().
fReleasedEnergy
G4double G4MolecularDissociationChannel::fReleasedEnergy private
Definition at line 122 of file G4MolecularDissociationChannel.hh.
Referenced by G4MolecularDissociationChannel(), GetEnergy(), operator=(), and SetEnergy().
fRMSMotherMoleculeDisplacement
G4double G4MolecularDissociationChannel::fRMSMotherMoleculeDisplacement private
Definition at line 127 of file G4MolecularDissociationChannel.hh.
Referenced by G4MolecularDissociationChannel(), GetRMSMotherMoleculeDisplacement(), operator=(), and SetRMSMotherMoleculeDisplacement().
fRMSProductsDisplacementVector
std::vector<G4double> G4MolecularDissociationChannel::fRMSProductsDisplacementVector private
Definition at line 128 of file G4MolecularDissociationChannel.hh.
Referenced by AddProduct(), GetRMSProductsDisplacement(), GetRMSRadialDisplacementOfProduct(), and operator=().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/dna/molecules/management/include/G4MolecularDissociationChannel.hh
source/processes/electromagnetic/dna/molecules/management/src/G4MolecularDissociationChannel.cc