Geant4: examples/extended/medical/dna/chem1/chem1.cc File Reference
chem1.cc File Reference
Chem1 example.
#include "DetectorConstruction.hh"
#include "PhysicsList.hh"
#include "ActionInitialization.hh"
#include "G4RunManager.hh"
#include "G4DNAChemistryManager.hh"
#include "G4UImanager.hh"
#include "G4UIExecutive.hh"
#include "G4VisExecutive.hh"
#include "CommandLineParser.hh"
Functions
CommandLineParser * parser (0)
void Parse (int &argc, char **argv)
int main (int argc, char **argv)
Detailed Description
Chem1 example.
Definition in file chem1.cc.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 70 of file chem1.cc.
Parse()
void Parse (int & argc, char ** argv)
Definition at line 192 of file chem1.cc.
Referenced by main().
parser()
CommandLineParser* parser (0)
Referenced by appendAttributeValue(), build_model(), build_node(), cdataSectionProcessor(), Par02DetectorConstruction::Construct(), contentProcessor(), RunAction::CreateNtuple(), doCdataSection(), doContent(), doProlog(), epilogProcessor(), externalEntityContentProcessor(), externalEntityInitProcessor(), externalEntityInitProcessor2(), externalEntityInitProcessor3(), getAttributeId(), getElementType(), initializeEncoding(), internalEntityProcessor(), lookup(), main(), Parse(), parserCreate(), parserInit(), processInternalEntity(), processXmlDecl(), prologInitProcessor(), prologProcessor(), G4GDMLRead::Read(), reportComment(), reportProcessingInstruction(), setContext(), setElementTypePrefix(), startParsing(), storeAttributeValue(), storeAtts(), storeEntityValue(), RunAction::WriteNtuple(), XML_DefaultCurrent(), XML_ExternalEntityParserCreate(), XML_GetParsingStatus(), XML_Parse(), XML_ParseBuffer(), XML_ParserFree(), XML_ParserReset(), XML_ResumeParser(), XML_SetExternalEntityRefHandlerArg(), and XML_UseParserAsHandlerArg().