Geant4: G4VSamplerConfigurator Class Reference
G4VSamplerConfigurator Class Reference abstract
#include <G4VSamplerConfigurator.hh>
Public Member Functions
G4VSamplerConfigurator ()
virtual ~G4VSamplerConfigurator ()
virtual void Configure (G4VSamplerConfigurator *preConf)=0
virtual const G4VTrackTerminator * GetTrackTerminator () const =0
Detailed Description
Definition at line 50 of file G4VSamplerConfigurator.hh.
Constructor & Destructor Documentation
G4VSamplerConfigurator()
G4VSamplerConfigurator::G4VSamplerConfigurator ()
Definition at line 39 of file G4VSamplerConfigurator.cc.
~G4VSamplerConfigurator()
G4VSamplerConfigurator::~G4VSamplerConfigurator () virtual
Definition at line 42 of file G4VSamplerConfigurator.cc.
Member Function Documentation
Configure()
virtual void G4VSamplerConfigurator::Configure (G4VSamplerConfigurator * preConf) pure virtual
Implemented in G4ImportanceConfigurator, G4WeightCutOffConfigurator, and G4WeightWindowConfigurator.
Referenced by G4GeometrySampler::AddProcess().
GetTrackTerminator()
virtual const G4VTrackTerminator* G4VSamplerConfigurator::GetTrackTerminator () const pure virtual
Implemented in G4ImportanceConfigurator, G4WeightCutOffConfigurator, and G4WeightWindowConfigurator.
Referenced by G4WeightWindowConfigurator::Configure(), and G4ImportanceConfigurator::Configure().
The documentation for this class was generated from the following files:
source/processes/biasing/importance/include/G4VSamplerConfigurator.hh
source/processes/biasing/importance/src/G4VSamplerConfigurator.cc