Geant4: G4RDShellVacancy Class Reference
G4RDShellVacancy Class Reference
#include <G4RDShellVacancy.hh>
Public Member Functions
G4RDShellVacancy ()
~G4RDShellVacancy ()
std::vector< G4int > GenerateNumberOfIonisations (const G4MaterialCutsCouple *couple, G4double incidentEnergy, G4double eLoss) const
void AddXsiTable (G4RDVEMDataSet *set)
Private Member Functions
G4double AverageNOfIonisations (const G4MaterialCutsCouple *couple, G4int index, G4double energy, G4double eLoss) const
Private Attributes
std::vector< G4RDVEMDataSet * > xsis
Detailed Description
Definition at line 53 of file G4RDShellVacancy.hh.
Constructor & Destructor Documentation
G4RDShellVacancy()
G4RDShellVacancy::G4RDShellVacancy ()
Definition at line 43 of file G4RDShellVacancy.cc.
~G4RDShellVacancy()
G4RDShellVacancy::~G4RDShellVacancy ()
Definition at line 47 of file G4RDShellVacancy.cc.
Member Function Documentation
AddXsiTable()
void G4RDShellVacancy::AddXsiTable (G4RDVEMDataSet * set)
Definition at line 58 of file G4RDShellVacancy.cc.
Referenced by G4LowEnergyIonisation::BuildLossTable().
AverageNOfIonisations()
G4double G4RDShellVacancy::AverageNOfIonisations (const G4MaterialCutsCouple * couple, G4int index, G4double energy, G4double eLoss) const private
Definition at line 93 of file G4RDShellVacancy.cc.
Referenced by GenerateNumberOfIonisations().
GenerateNumberOfIonisations()
std::vector< G4int > G4RDShellVacancy::GenerateNumberOfIonisations (const G4MaterialCutsCouple * couple, G4double incidentEnergy, G4double eLoss) const
Definition at line 64 of file G4RDShellVacancy.cc.
Referenced by G4LowEnergyIonisation::DeexciteAtom().
Field Documentation
xsis
std::vector<G4RDVEMDataSet*> G4RDShellVacancy::xsis private
Definition at line 74 of file G4RDShellVacancy.hh.
Referenced by AddXsiTable(), AverageNOfIonisations(), and ~G4RDShellVacancy().
The documentation for this class was generated from the following files:
examples/advanced/eRosita/physics/include/G4RDShellVacancy.hh
examples/advanced/eRosita/physics/src/G4RDShellVacancy.cc