Geant4: G4VEmModel Class Reference
G4VEmModel Class Reference abstract
#include <G4VEmModel.hh>
Public Member Functions
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &)=0
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin=0.0, G4double tmax=DBL_MAX)=0
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0., G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy)
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Member Functions
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Protected Attributes
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
Private Member Functions
G4VEmModel & operator= (const G4VEmModel &right)=delete
G4VEmModel (const G4VEmModel &)=delete
Private Attributes
G4VEmFluctuationModel * flucModel
G4VEmAngularDistribution * anglModel
const G4String name
G4double lowLimit
G4double highLimit
G4double eMinActive
G4double eMaxActive
G4double polarAngleLimit
G4double secondaryThreshold
G4bool theLPMflag
G4bool flagDeexcitation
G4bool flagForceBuildTable
G4bool isMaster
G4bool localTable
G4bool localElmSelectors
G4bool useAngularGenerator
G4bool isLocked
G4int nSelectors
std::vector< G4EmElementSelector * > * elmSelectors
G4LossTableManager * fEmManager
const G4MaterialCutsCouple * fCurrentCouple
const G4Element * fCurrentElement
const G4Isotope * fCurrentIsotope
G4VEmModel * fTripletModel
G4int nsec
std::vector< G4double > xsec
Detailed Description
Definition at line 103 of file G4VEmModel.hh.
Constructor & Destructor Documentation
G4VEmModel() [1/2]
G4VEmModel::G4VEmModel (const G4String & nam) explicit
Definition at line 65 of file G4VEmModel.cc.
~G4VEmModel()
G4VEmModel::~G4VEmModel () virtual
Definition at line 91 of file G4VEmModel.cc.
G4VEmModel() [2/2]
G4VEmModel::G4VEmModel (const G4VEmModel &) private delete
Member Function Documentation
ChargeSquareRatio()
G4double G4VEmModel::ChargeSquareRatio (const G4Track & track) virtual
Reimplemented in G4BetheBlochIonGasModel, and G4BraggIonGasModel.
Definition at line 380 of file G4VEmModel.cc.
Referenced by G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength().
ComputeCrossSectionPerAtom() [1/2]
G4double G4VEmModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * part, const G4Element * elm, G4double kinEnergy, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) inline
Definition at line 534 of file G4VEmModel.hh.
ComputeCrossSectionPerAtom() [2/2]
G4double G4VEmModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * , G4double kinEnergy, G4double Z, G4double A = 0., G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) virtual
Reimplemented in G4PenelopeBremsstrahlungModel, G4UrbanAdjointMscModel, G4UrbanMscModel, G4IonParametrisedLossModel, G4PenelopeComptonModel, G4PenelopeIonisationModel, G4eBremParametrizedModel, G4eeToHadronsMultiModel, G4eeToHadronsModel, G4MuBetheBlochModel, G4MuBremsstrahlungModel, G4BraggIonModel, G4BraggModel, G4ICRU73QOModel, G4MuPairProductionModel, G4BetheBlochModel, G4LindhardSorensenIonModel, G4mplIonisationWithDeltaModel, G4MollerBhabhaModel, G4AtimaEnergyLossModel, G4LDMBremModel, G4WentzelVIModel, G4WentzelVIRelModel, G4LivermoreGammaConversionModel, G4EmMultiModel, G4eeToTwoGammaModel, G4eplusTo2GammaOKVIModel, G4eplusTo3GammaOKVIModel, G4PairProductionRelModel, G4BetheHeitlerModel, G4BoldyshevTripletModel, G4LowEPPolarizedComptonModel, G4LowEPComptonModel, G4PenelopePhotoElectricModel, G4LivermoreIonisationModel, G4PenelopeRayleighModel, G4JAEAElasticScatteringModel, G4LivermorePolarizedComptonModel, G4PenelopeAnnihilationModel, G4PenelopeGammaConversionModel, G4LivermorePolarizedRayleighModel, G4LivermoreComptonModel, G4LivermoreComptonModifiedModel, G4LivermorePolarizedGammaConversionModel, G4LivermoreNuclearGammaConversionModel, G4LivermoreGammaConversionModelRC, G4LivermoreRayleighModel, G4LivermorePolarizedPhotoElectricGDModel, G4XrayRayleighModel, G4PEEffectFluoModel, G4eCoulombScatteringModel, G4hCoulombScatteringModel, G4KleinNishinaCompton, G4KleinNishinaModel, G4PolarizedComptonModel, G4IonCoulombScatteringModel, G4eSingleCoulombScatteringModel, G4LivermorePhotoElectricModel, G4LivermorePolarizedPhotoElectricModel, and G4eBremsstrahlungRelModel.
Definition at line 356 of file G4VEmModel.cc.
Referenced by G4VEmProcess::ComputeCrossSectionPerAtom(), G4EmCalculator::ComputeCrossSectionPerAtom(), ComputeCrossSectionPerAtom(), G4EmCalculator::ComputeCrossSectionPerShell(), G4AdjointIonIonisationModel::CorrectPostStepWeight(), CrossSectionPerVolume(), G4AdjointComptonModel::DiffCrossSectionPerAtomPrimToScatPrim(), G4AdjointIonIonisationModel::DiffCrossSectionPerAtomPrimToSecond(), G4AdjointhIonisationModel::DiffCrossSectionPerAtomPrimToSecond(), G4VEmAdjointModel::DiffCrossSectionPerAtomPrimToSecond(), G4AdjointBremsstrahlungModel::DiffCrossSectionPerVolumePrimToSecondApproximated2(), G4EmElementSelector::Initialise(), G4LivermoreGammaConversionModel::InitialiseProbability(), and main().
ComputeCrossSectionPerShell()
G4double G4VEmModel::ComputeCrossSectionPerShell (const G4ParticleDefinition * , G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) virtual
Definition at line 366 of file G4VEmModel.cc.
Referenced by G4EmCalculator::ComputeCrossSectionPerShell().
ComputeDEDX()
G4double G4VEmModel::ComputeDEDX (const G4MaterialCutsCouple * couple, const G4ParticleDefinition * part, G4double kineticEnergy, G4double cutEnergy = DBL_MAX) inline virtual
Reimplemented in G4EmMultiModel.
Definition at line 496 of file G4VEmModel.hh.
Referenced by G4EmModelManager::ComputeDEDX(), G4TablesForExtrapolator::ComputeElectronDEDX(), G4TablesForExtrapolator::ComputeMuonDEDX(), and G4TablesForExtrapolator::ComputeProtonDEDX().
ComputeDEDXPerVolume()
G4double G4VEmModel::ComputeDEDXPerVolume (const G4Material * , const G4ParticleDefinition * , G4double kineticEnergy, G4double cutEnergy = DBL_MAX) virtual
Reimplemented in G4IonParametrisedLossModel, G4ICRU73QOModel, G4AtimaEnergyLossModel, G4ICRU49NuclearStoppingModel, G4MuBetheBlochModel, G4BraggIonModel, G4BraggModel, G4MuBremsstrahlungModel, G4BetheBlochModel, G4LindhardSorensenIonModel, G4MuPairProductionModel, G4MollerBhabhaModel, G4eBremParametrizedModel, G4mplIonisationModel, G4mplIonisationWithDeltaModel, G4BetheBlochNoDeltaModel, G4BraggNoDeltaModel, G4ICRU73NoDeltaModel, G4LDMBremModel, G4PAIModel, G4PAIPhotModel, G4PenelopeIonisationModel, G4PenelopeBremsstrahlungModel, G4LivermoreIonisationModel, MyMollerBhabhaModel, MyMollerBhabhaModel, and G4eBremsstrahlungRelModel.
Definition at line 242 of file G4VEmModel.cc.
Referenced by G4NuclearStopping::AlongStepDoIt(), G4EmCorrections::BuildCorrectionVector(), G4EmCalculator::ComputeDEDX(), ComputeDEDX(), G4EmCalculator::ComputeNuclearDEDX(), and main().
ComputeMeanFreePath()
G4double G4VEmModel::ComputeMeanFreePath (const G4ParticleDefinition * part, G4double kineticEnergy, const G4Material * material, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) inline
Definition at line 521 of file G4VEmModel.hh.
Referenced by main().
CorrectionsAlongStep()
void G4VEmModel::CorrectionsAlongStep (const G4MaterialCutsCouple * , const G4DynamicParticle * , G4double & eloss, G4double & niel, G4double length) virtual
Reimplemented in G4BetheBlochModel, G4LindhardSorensenIonModel, G4BraggIonModel, G4ICRU73QOModel, G4AtimaEnergyLossModel, and G4IonParametrisedLossModel.
Definition at line 405 of file G4VEmModel.cc.
Referenced by G4ContinuousGainOfEnergy::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepDoIt(), G4EmCalculator::ComputeDEDX(), and G4EmCalculator::GetDEDX().
CrossSection()
G4double G4VEmModel::CrossSection (const G4MaterialCutsCouple * couple, const G4ParticleDefinition * part, G4double kineticEnergy, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) inline
Definition at line 507 of file G4VEmModel.hh.
Referenced by G4eplusPolarizedAnnihilation::ComputeAsymmetry(), G4ePolarizedIonisation::ComputeAsymmetry(), G4PolarizedCompton::ComputeAsymmetry(), G4EmModelManager::FillLambdaVector(), and G4EmMultiModel::SampleSecondaries().
CrossSectionPerVolume()
G4double G4VEmModel::CrossSectionPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double kineticEnergy, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) virtual
Reimplemented in G4PenelopeIonisationModel, G4PenelopeBremsstrahlungModel, G4TDNAOneStepThermalizationModel< MODEL >, G4DNAModelInterface, G4MicroElecInelasticModel, G4MuElecInelasticModel, G4DNACPA100IonisationModel, G4DNACPA100ExcitationModel, G4DNATransformElectronModel, G4DNACPA100ElasticModel, G4DNAEmfietzoglouIonisationModel, G4DNAEmfietzoglouExcitationModel, G4MicroElecElasticModel, G4MuElecElasticModel, G4DNAIonElasticModel, G4DNABornIonisationModel1, G4DNABornIonisationModel2, G4DNARuddIonisationExtendedModel, G4DNARuddIonisationModel, G4DNABornExcitationModel2, G4DNAMillerGreenExcitationModel, G4DNASancheExcitationModel, G4DNABornExcitationModel1, G4DNAChampionElasticModel, G4DNAMeltonAttachmentModel, G4DNADingfelderChargeIncreaseModel, G4DNADingfelderChargeDecreaseModel, G4DNAScreenedRutherfordElasticModel, G4DNAUeharaScreenedRutherfordElasticModel, G4IonParametrisedLossModel, G4eeToTwoGammaModel, G4eplusTo2GammaOKVIModel, G4eplusTo3GammaOKVIModel, G4GoudsmitSaundersonMscModel, G4PenelopeComptonModel, G4LEPTSAttachmentModel, G4LEPTSExcitationModel, G4LEPTSDissociationModel, G4LEPTSElasticModel, G4LEPTSIonisationModel, G4LEPTSPositroniumModel, G4LEPTSRotExcitationModel, G4LEPTSVibExcitationModel, G4MuBetheBlochModel, G4BraggIonModel, G4BraggModel, G4ICRU73QOModel, G4BetheBlochModel, G4LindhardSorensenIonModel, G4MollerBhabhaModel, G4AtimaEnergyLossModel, G4eeToHadronsMultiModel, G4PEEffectFluoModel, G4eeToHadronsModel, G4BetheBlochNoDeltaModel, G4BraggNoDeltaModel, G4ICRU73NoDeltaModel, G4PAIModel, G4PAIPhotModel, MyKleinNishinaCompton, G4LivermorePhotoElectricModel, and G4LivermorePolarizedPhotoElectricModel.
Definition at line 251 of file G4VEmModel.cc.
Referenced by G4AdjointBremsstrahlungModel::AdjointCrossSection(), G4EmCalculator::ComputeCrossSectionPerVolume(), G4VEmProcess::ComputeCurrentLambda(), ComputeMeanFreePath(), G4TablesForExtrapolator::ComputeTrasportXS(), CrossSection(), G4DNADummyModel::CrossSectionPerVolume(), MyKleinNishinaCompton::CrossSectionPerVolume(), G4LivermorePolarizedPhotoElectricModel::CrossSectionPerVolume(), G4LivermorePhotoElectricModel::CrossSectionPerVolume(), G4VEmProcess::CrossSectionPerVolume(), G4VEnergyLossProcess::CrossSectionPerVolume(), G4VEmAdjointModel::DiffCrossSectionPerVolumePrimToSecond(), G4AdjointBremsstrahlungModel::DiffCrossSectionPerVolumePrimToSecondApproximated1(), G4AdjointBremsstrahlungModel::GetAdjointCrossSection(), G4VMscModel::GetTransportMeanFreePath(), SelectRandomAtom(), and Value().
CurrentCouple()
const G4MaterialCutsCouple * G4VEmModel::CurrentCouple () const inline protected
Definition at line 458 of file G4VEmModel.hh.
Referenced by G4PEEffectFluoModel::ComputeCrossSectionPerAtom(), G4WentzelVIRelModel::ComputeCrossSectionPerAtom(), G4EmMultiModel::ComputeCrossSectionPerAtom(), G4hCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4eSingleCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4WentzelVIModel::ComputeCrossSectionPerAtom(), G4IonCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4eCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4mplIonisationModel::ComputeDEDXPerVolume(), G4mplIonisationWithDeltaModel::ComputeDEDXPerVolume(), G4PAIPhotModel::ComputeDEDXPerVolume(), G4PAIModel::ComputeDEDXPerVolume(), G4PAIPhotModel::CrossSectionPerVolume(), G4PAIModel::CrossSectionPerVolume(), G4VMscModel::GetTransportMeanFreePath(), G4LivermoreGammaConversionModel::InitialiseProbability(), G4hCoulombScatteringModel::MinPrimaryEnergy(), and G4eCoulombScatteringModel::MinPrimaryEnergy().
DeexcitationFlag()
G4bool G4VEmModel::DeexcitationFlag () const inline
Definition at line 654 of file G4VEmModel.hh.
Referenced by G4EmModelManager::DumpModelList().
DefineForRegion()
void G4VEmModel::DefineForRegion (const G4Region *) virtual
Reimplemented in G4PAIModel, and G4PAIPhotModel.
Definition at line 375 of file G4VEmModel.cc.
Referenced by G4EmModelManager::AddEmModel().
ForceBuildTableFlag()
G4bool G4VEmModel::ForceBuildTableFlag () const inline
Definition at line 661 of file G4VEmModel.hh.
Referenced by G4VMscModel::GetParticleChangeForMSC().
GetAngularDistribution()
G4VEmAngularDistribution * G4VEmModel::GetAngularDistribution () inline
Definition at line 571 of file G4VEmModel.hh.
Referenced by G4EmModelManager::DumpModelList(), G4AtimaEnergyLossModel::Initialise(), G4LindhardSorensenIonModel::Initialise(), G4BetheBlochModel::Initialise(), G4MollerBhabhaModel::Initialise(), G4BraggIonModel::Initialise(), G4ICRU73QOModel::Initialise(), G4BraggModel::Initialise(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4DNARuddIonisationExtendedModel::SampleSecondaries(), G4LivermoreRayleighModel::SampleSecondaries(), G4DNARuddIonisationModel::SampleSecondaries(), G4DNABornIonisationModel1::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4LivermorePhotoElectricModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), G4LivermoreIonisationModel::SampleSecondaries(), G4PEEffectFluoModel::SampleSecondaries(), G4MicroElecInelasticModel::SampleSecondaries(), G4BetheHeitlerModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), G4eBremParametrizedModel::SampleSecondaries(), G4PairProductionRelModel::SampleSecondaries(), G4PAIPhotModel::SampleSecondaries(), G4PAIModel::SampleSecondaries(), G4MollerBhabhaModel::SampleSecondaries(), G4ICRU73QOModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), G4BetheBlochModel::SampleSecondaries(), and G4IonParametrisedLossModel::SampleSecondaries().
GetChargeSquareRatio()
G4double G4VEmModel::GetChargeSquareRatio (const G4ParticleDefinition * p, const G4Material * , G4double kineticEnergy) virtual
Reimplemented in G4BetheBlochModel, G4LindhardSorensenIonModel, G4AtimaEnergyLossModel, G4IonParametrisedLossModel, G4BraggIonModel, and G4BraggModel.
Definition at line 388 of file G4VEmModel.cc.
Referenced by G4ContinuousGainOfEnergy::AlongStepDoIt(), G4AdjointCSManager::BuildTotalSigmaTables(), ChargeSquareRatio(), G4EmCalculator::ComputeDEDX(), G4AdjointIonIonisationModel::CorrectPostStepWeight(), G4ContinuousGainOfEnergy::GetContinuousStepLimit(), and G4EmCalculator::GetDEDX().
GetCrossSectionTable()
G4PhysicsTable * G4VEmModel::GetCrossSectionTable () inline
Definition at line 804 of file G4VEmModel.hh.
Referenced by G4VMultipleScattering::BuildPhysicsTable(), G4EmModelManager::DumpModelList(), G4EmCalculator::FindLambdaTable(), G4WentzelVIModel::Initialise(), and G4VMultipleScattering::StorePhysicsTable().
GetCurrentElement()
const G4Element * G4VEmModel::GetCurrentElement () const inline
Definition at line 473 of file G4VEmModel.hh.
Referenced by G4VEmProcess::GetCurrentElement(), G4VEnergyLossProcess::GetCurrentElement(), G4VEmProcess::GetTargetElement(), G4PolarizedGammaConversionModel::SampleSecondaries(), G4ePolarizedBremsstrahlungModel::SampleSecondaries(), G4PolarizedPEEffectModel::SampleSecondaries(), G4PolarizedGammaConversionModel::SelectedAtom(), G4ePolarizedBremsstrahlungModel::SelectedAtom(), and G4eBremParametrizedModel::SetCurrentElement().
GetCurrentIsotope()
const G4Isotope * G4VEmModel::GetCurrentIsotope () const inline
Definition at line 480 of file G4VEmModel.hh.
Referenced by G4VEmProcess::GetTargetIsotope().
GetElementData()
G4ElementData * G4VEmModel::GetElementData () inline
Definition at line 797 of file G4VEmModel.hh.
Referenced by G4MuPairProductionModel::InitialiseLocal(), G4ePairProduction::StreamProcessInfo(), and G4MuPairProduction::StreamProcessInfo().
GetElementSelectors()
std::vector< G4EmElementSelector * > * G4VEmModel::GetElementSelectors () inline
Definition at line 780 of file G4VEmModel.hh.
Referenced by G4LivermoreRayleighModel::InitialiseLocal(), G4LivermoreGammaConversionModelRC::InitialiseLocal(), G4LivermoreNuclearGammaConversionModel::InitialiseLocal(), G4LivermorePolarizedGammaConversionModel::InitialiseLocal(), G4LivermoreGammaConversionModel::InitialiseLocal(), G4LivermoreComptonModel::InitialiseLocal(), G4LivermorePolarizedRayleighModel::InitialiseLocal(), G4JAEAElasticScatteringModel::InitialiseLocal(), G4LivermorePolarizedComptonModel::InitialiseLocal(), G4PenelopePhotoElectricModel::InitialiseLocal(), G4KleinNishinaCompton::InitialiseLocal(), G4KleinNishinaModel::InitialiseLocal(), G4eBremParametrizedModel::InitialiseLocal(), G4eBremsstrahlungRelModel::InitialiseLocal(), G4BetheHeitlerModel::InitialiseLocal(), G4PAIPhotModel::InitialiseLocal(), G4eSingleCoulombScatteringModel::InitialiseLocal(), G4hCoulombScatteringModel::InitialiseLocal(), G4PairProductionRelModel::InitialiseLocal(), G4PAIModel::InitialiseLocal(), G4MuBremsstrahlungModel::InitialiseLocal(), G4MuPairProductionModel::InitialiseLocal(), G4eCoulombScatteringModel::InitialiseLocal(), G4LowEPComptonModel::InitialiseLocal(), and G4LowEPPolarizedComptonModel::InitialiseLocal().
GetModelOfFluctuations()
G4VEmFluctuationModel * G4VEmModel::GetModelOfFluctuations () inline
Definition at line 564 of file G4VEmModel.hh.
Referenced by G4ContinuousGainOfEnergy::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepDoIt(), G4AtimaEnergyLossModel::CorrectionsAlongStep(), G4LindhardSorensenIonModel::CorrectionsAlongStep(), G4BetheBlochModel::CorrectionsAlongStep(), G4BraggIonModel::CorrectionsAlongStep(), G4IonParametrisedLossModel::CorrectionsAlongStep(), G4BraggModel::GetChargeSquareRatio(), G4VEnergyLossProcess::GetDEDXDispersion(), and G4EmMultiModel::Initialise().
GetName()
const G4String & G4VEmModel::GetName (void) const inline
Definition at line 773 of file G4VEmModel.hh.
Referenced by G4IonParametrisedLossModel::AddDEDXTable(), G4VLEPTSModel::BuildMeanFreePathTable(), G4VLEPTSModel::BuildPhysicsTable(), G4EmCalculator::ComputeDEDX(), G4MuPairProductionModel::DataCorrupted(), G4EmElementSelector::Dump(), G4EmModelManager::DumpModelList(), G4EmCalculator::FindEmModel(), G4EmMultiModel::Initialise(), G4IonParametrisedLossModel::Initialise(), G4EmModelManager::Initialise(), G4IonParametrisedLossModel::PrintDEDXTable(), G4DNADissociation::PrintInfo(), G4DNARotExcitation::PrintInfo(), G4DNAPositronium::PrintInfo(), G4DNAChargeIncrease::PrintInfo(), G4DNAVibExcitation::PrintInfo(), G4DNAAttachment::PrintInfo(), G4DNAElastic::PrintInfo(), G4DNAChargeDecrease::PrintInfo(), G4DNAExcitation::PrintInfo(), G4DNAIonisation::PrintInfo(), G4PolarizedCompton::PrintInfo(), G4VLEPTSModel::ReadIXS(), G4LossTableManager::Register(), G4DNAModelInterface::RegisterModel(), G4IonParametrisedLossModel::RemoveDEDXTable(), G4VLEPTSModel::SampleEnergyLoss(), G4EmConfigurator::SetExtraEmModel(), G4EmConfigurator::SetModelForRegion(), and G4EmConfigurator::UpdateModelEnergyRange().
GetPartialCrossSection()
G4double G4VEmModel::GetPartialCrossSection (const G4Material * , G4int level, const G4ParticleDefinition * , G4double kineticEnergy) virtual
Reimplemented in G4DNABornIonisationModel1, G4DNABornIonisationModel2, G4DNAMillerGreenExcitationModel, G4DNABornExcitationModel2, and G4DNABornExcitationModel1.
Definition at line 276 of file G4VEmModel.cc.
GetParticleChangeForGamma()
G4ParticleChangeForGamma * G4VEmModel::GetParticleChangeForGamma () protected
Definition at line 130 of file G4VEmModel.cc.
Referenced by G4LEPTSDissociationModel::Initialise(), G4LEPTSElasticModel::Initialise(), G4LEPTSExcitationModel::Initialise(), G4LEPTSIonisationModel::Initialise(), G4LEPTSPositroniumModel::Initialise(), G4LEPTSRotExcitationModel::Initialise(), G4LEPTSVibExcitationModel::Initialise(), G4LEPTSAttachmentModel::Initialise(), G4DNAUeharaScreenedRutherfordElasticModel::Initialise(), G4DNAScreenedRutherfordElasticModel::Initialise(), G4LivermoreRayleighModel::Initialise(), G4BoldyshevTripletModel::Initialise(), G4DNADingfelderChargeDecreaseModel::Initialise(), G4DNAChampionElasticModel::Initialise(), G4DNADingfelderChargeIncreaseModel::Initialise(), G4DNABornExcitationModel1::Initialise(), G4DNASancheExcitationModel::Initialise(), G4DNAMeltonAttachmentModel::Initialise(), G4XrayRayleighModel::Initialise(), G4LivermoreGammaConversionModel::Initialise(), G4LivermorePolarizedGammaConversionModel::Initialise(), G4DNABornExcitationModel2::Initialise(), G4LivermorePolarizedPhotoElectricGDModel::Initialise(), G4DNAMillerGreenExcitationModel::Initialise(), G4DNARuddIonisationExtendedModel::Initialise(), G4LivermoreComptonModel::Initialise(), G4DNARuddIonisationModel::Initialise(), G4LivermoreComptonModifiedModel::Initialise(), G4DNABornIonisationModel2::Initialise(), G4DNABornIonisationModel1::Initialise(), G4LivermorePhotoElectricModel::Initialise(), G4LivermorePolarizedPhotoElectricModel::Initialise(), G4DNAIonElasticModel::Initialise(), G4LivermorePolarizedRayleighModel::Initialise(), G4DNAEmfietzoglouExcitationModel::Initialise(), G4MicroElecElasticModel::Initialise(), G4MuElecElasticModel::Initialise(), G4JAEAElasticScatteringModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4DNAEmfietzoglouIonisationModel::Initialise(), G4eplusTo3GammaOKVIModel::Initialise(), G4DNACPA100ElasticModel::Initialise(), G4PenelopeAnnihilationModel::Initialise(), G4DNATransformElectronModel::Initialise(), G4PenelopeGammaConversionModel::Initialise(), G4PenelopeRayleighModel::Initialise(), G4DNACPA100ExcitationModel::Initialise(), G4eplusTo2GammaOKVIModel::Initialise(), G4KleinNishinaCompton::Initialise(), G4PEEffectFluoModel::Initialise(), G4KleinNishinaModel::Initialise(), G4PenelopePhotoElectricModel::Initialise(), G4DNAModelInterface::Initialise(), G4eeToTwoGammaModel::Initialise(), G4BetheHeitlerModel::Initialise(), G4DNACPA100IonisationModel::Initialise(), G4PolarizedAnnihilationModel::Initialise(), G4PenelopeComptonModel::Initialise(), G4eeToHadronsMultiModel::Initialise(), G4MicroElecInelasticModel::Initialise(), G4MuElecInelasticModel::Initialise(), G4hCoulombScatteringModel::Initialise(), G4eSingleCoulombScatteringModel::Initialise(), G4PairProductionRelModel::Initialise(), G4IonCoulombScatteringModel::Initialise(), G4eCoulombScatteringModel::Initialise(), G4LowEPComptonModel::Initialise(), and G4LowEPPolarizedComptonModel::Initialise().
GetParticleChangeForLoss()
G4ParticleChangeForLoss * G4VEmModel::GetParticleChangeForLoss () protected
Definition at line 115 of file G4VEmModel.cc.
Referenced by G4mplIonisationModel::Initialise(), G4mplIonisationWithDeltaModel::Initialise(), G4LivermoreIonisationModel::Initialise(), G4AtimaEnergyLossModel::Initialise(), G4eBremsstrahlungRelModel::Initialise(), G4eBremParametrizedModel::Initialise(), G4LindhardSorensenIonModel::Initialise(), G4MollerBhabhaModel::Initialise(), G4PenelopeBremsstrahlungModel::Initialise(), G4BetheBlochModel::Initialise(), G4PAIPhotModel::Initialise(), G4PenelopeIonisationModel::Initialise(), G4SeltzerBergerModel::Initialise(), G4PAIModel::Initialise(), G4BraggIonModel::Initialise(), G4MuBetheBlochModel::Initialise(), G4ICRU73QOModel::Initialise(), G4MuPairProductionModel::Initialise(), G4BraggModel::Initialise(), G4MuBremsstrahlungModel::Initialise(), and G4IonParametrisedLossModel::Initialise().
GetParticleCharge()
G4double G4VEmModel::GetParticleCharge (const G4ParticleDefinition * p, const G4Material * , G4double kineticEnergy) virtual
Reimplemented in G4BraggIonModel, G4BraggModel, G4BetheBlochModel, G4LindhardSorensenIonModel, G4AtimaEnergyLossModel, G4BetheBlochIonGasModel, G4BraggIonGasModel, and G4IonParametrisedLossModel.
Definition at line 397 of file G4VEmModel.cc.
Referenced by G4VEnergyLossProcess::AlongStepDoIt().
GetTripletModel()
G4VEmModel * G4VEmModel::GetTripletModel () inline
Definition at line 588 of file G4VEmModel.hh.
Referenced by G4LivermoreGammaConversionModel::Initialise(), G4eBremsstrahlungRelModel::Initialise(), G4SeltzerBergerModel::Initialise(), G4LivermoreGammaConversionModel::InitialiseForElement(), G4LivermoreGammaConversionModel::InitialiseProbability(), G4LivermoreGammaConversionModel::SampleSecondaries(), and G4eBremsstrahlungRelModel::SampleSecondaries().
HighEnergyActivationLimit()
G4double G4VEmModel::HighEnergyActivationLimit () const inline
Definition at line 619 of file G4VEmModel.hh.
Referenced by G4EmModelManager::DumpModelList(), G4VMscModel::GetParticleChangeForMSC(), G4WentzelVIModel::Initialise(), and G4EmModelManager::Initialise().
HighEnergyLimit()
G4double G4VEmModel::HighEnergyLimit () const inline
Definition at line 605 of file G4VEmModel.hh.
Referenced by G4DNAScreenedRutherfordElasticModel::CrossSectionPerVolume(), G4DNAChampionElasticModel::CrossSectionPerVolume(), G4DNAMeltonAttachmentModel::CrossSectionPerVolume(), G4DNASancheExcitationModel::CrossSectionPerVolume(), G4DNAEmfietzoglouExcitationModel::CrossSectionPerVolume(), G4DNAEmfietzoglouIonisationModel::CrossSectionPerVolume(), G4DNATransformElectronModel::CrossSectionPerVolume(), G4DNACPA100ExcitationModel::CrossSectionPerVolume(), G4DNACPA100IonisationModel::CrossSectionPerVolume(), G4DNAChampionElasticModel::G4DNAChampionElasticModel(), G4DNACPA100ElasticModel::G4DNACPA100ElasticModel(), G4DNAMeltonAttachmentModel::G4DNAMeltonAttachmentModel(), G4DNASancheExcitationModel::G4DNASancheExcitationModel(), G4DNAUeharaScreenedRutherfordElasticModel::G4DNAUeharaScreenedRutherfordElasticModel(), G4eeToHadronsModel::G4eeToHadronsModel(), G4IonParametrisedLossModel::G4IonParametrisedLossModel(), G4LivermorePolarizedRayleighModel::G4LivermorePolarizedRayleighModel(), G4ContinuousGainOfEnergy::GetContinuousStepLimit(), G4PenelopeBremsstrahlungModel::GetCrossSectionTableForCouple(), G4VMscModel::GetParticleChangeForMSC(), G4DNAUeharaScreenedRutherfordElasticModel::Initialise(), G4DNAScreenedRutherfordElasticModel::Initialise(), G4LivermoreRayleighModel::Initialise(), G4DNADingfelderChargeDecreaseModel::Initialise(), G4DNADummyModel::Initialise(), G4BoldyshevTripletModel::Initialise(), G4DNADingfelderChargeIncreaseModel::Initialise(), G4DNABornExcitationModel1::Initialise(), G4DNAChampionElasticModel::Initialise(), G4DNASancheExcitationModel::Initialise(), G4DNAMeltonAttachmentModel::Initialise(), G4LivermoreGammaConversionModel::Initialise(), G4DNABornExcitationModel2::Initialise(), G4LivermorePolarizedGammaConversionModel::Initialise(), G4DNAMillerGreenExcitationModel::Initialise(), G4LivermoreComptonModel::Initialise(), G4DNARuddIonisationExtendedModel::Initialise(), G4DNARuddIonisationModel::Initialise(), G4DNABornIonisationModel1::Initialise(), G4DNABornIonisationModel2::Initialise(), G4LivermoreComptonModifiedModel::Initialise(), G4DNAIonElasticModel::Initialise(), G4DNAEmfietzoglouExcitationModel::Initialise(), G4MicroElecElasticModel::Initialise(), G4MuElecElasticModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4JAEAElasticScatteringModel::Initialise(), G4DNAEmfietzoglouIonisationModel::Initialise(), G4DNACPA100ElasticModel::Initialise(), G4PenelopeAnnihilationModel::Initialise(), G4PenelopeGammaConversionModel::Initialise(), G4PenelopeRayleighModel::Initialise(), G4DNACPA100ExcitationModel::Initialise(), G4LivermoreIonisationModel::Initialise(), G4PenelopePhotoElectricModel::Initialise(), G4eBremsstrahlungRelModel::Initialise(), G4DNACPA100IonisationModel::Initialise(), G4PenelopeComptonModel::Initialise(), G4PenelopeBremsstrahlungModel::Initialise(), G4PAIPhotModel::Initialise(), G4MicroElecInelasticModel::Initialise(), G4WentzelVIModel::Initialise(), G4MuElecInelasticModel::Initialise(), G4PenelopeIonisationModel::Initialise(), G4PairProductionRelModel::Initialise(), G4SeltzerBergerModel::Initialise(), G4PAIModel::Initialise(), G4MuBremsstrahlungModel::Initialise(), G4MuPairProductionModel::Initialise(), G4LowEPComptonModel::Initialise(), G4LowEPPolarizedComptonModel::Initialise(), G4GoudsmitSaundersonMscModel::Initialise(), G4EmModelManager::Initialise(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4eBremsstrahlungRelModel::InitialiseLocal(), G4PairProductionRelModel::InitialiseLocal(), G4MuBremsstrahlungModel::InitialiseLocal(), G4MuPairProductionModel::InitialiseLocal(), G4LivermoreGammaConversionModel::InitialiseProbability(), G4CoulombScattering::InitialiseProcess(), G4VEmProcess::PreparePhysicsTable(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4DNASancheExcitationModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4EmConfigurator::SetExtraEmModel(), G4mplIonisationModel::SetParticle(), G4mplIonisationWithDeltaModel::SetParticle(), G4eBremsstrahlung::StreamProcessInfo(), and G4EmConfigurator::UpdateModelEnergyRange().
Initialise()
virtual void G4VEmModel::Initialise (const G4ParticleDefinition * , const G4DataVector &) pure virtual
Implemented in G4PolarizedPEEffectModel, G4DNAIonElasticModel, G4DNAModelInterface, G4DNACPA100IonisationModel, G4DNACPA100ExcitationModel, G4DNAEmfietzoglouIonisationModel, G4DNAEmfietzoglouExcitationModel, G4DNABornIonisationModel1, G4DNABornIonisationModel2, G4DNABornExcitationModel2, G4DNABornExcitationModel1, G4eCoulombScatteringModel, G4UrbanAdjointMscModel, G4MuBremsstrahlungModel, G4MuPairProductionModel, G4BraggModel, G4ICRU73QOModel, G4UrbanMscModel, G4MuBetheBlochModel, G4BraggIonModel, G4PairProductionRelModel, G4SeltzerBergerModel, G4hCoulombScatteringModel, G4WentzelVIRelModel, G4WentzelVIModel, G4eeToHadronsMultiModel, G4BetheBlochModel, G4MollerBhabhaModel, G4BetheHeitlerModel, G4LindhardSorensenIonModel, G4eBremParametrizedModel, G4eeToTwoGammaModel, G4eeToHadronsModel, G4eBremsstrahlungRelModel, G4mplIonisationModel, G4mplIonisationWithDeltaModel, G4ePolarizedBremsstrahlungModel, G4PolarizedGammaConversionModel, G4AtimaEnergyLossModel, G4KleinNishinaCompton, G4KleinNishinaModel, G4PEEffectFluoModel, G4eplusTo2GammaOKVIModel, G4IonCoulombScatteringModel, G4PAIModel, G4eSingleCoulombScatteringModel, G4PAIPhotModel, G4PolarizedAnnihilationModel, G4ICRU49NuclearStoppingModel, G4BetheHeitler5DModel, G4EmMultiModel, G4eplusTo3GammaOKVIModel, G4DummyModel, G4GoudsmitSaundersonMscModel, G4TDNAOneStepThermalizationModel< MODEL >, G4LowEPPolarizedComptonModel, G4IonParametrisedLossModel, G4LowEPComptonModel, G4PenelopeIonisationModel, G4MicroElecInelasticModel, G4MuElecInelasticModel, G4PenelopeBremsstrahlungModel, G4PenelopeComptonModel, G4LivermoreBremsstrahlungModel, G4PenelopePhotoElectricModel, G4LivermoreIonisationModel, G4DNATransformElectronModel, G4PenelopeGammaConversionModel, G4PenelopeRayleighModel, G4DNACPA100ElasticModel, G4PenelopeAnnihilationModel, G4JAEAElasticScatteringModel, G4LivermorePolarizedComptonModel, G4MicroElecElasticModel, G4MuElecElasticModel, G4LivermorePolarizedRayleighModel, G4LivermorePhotoElectricModel, G4LivermorePolarizedPhotoElectricModel, G4LivermoreComptonModifiedModel, G4DNARuddIonisationExtendedModel, G4DNARuddIonisationModel, G4LivermoreComptonModel, G4DNAMillerGreenExcitationModel, G4LivermoreGammaConversionModel, G4LivermorePolarizedGammaConversionModel, G4LivermorePolarizedPhotoElectricGDModel, G4XrayRayleighModel, G4DNAMeltonAttachmentModel, G4DNASancheExcitationModel, G4DNAChampionElasticModel, G4DNADingfelderChargeIncreaseModel, G4DNADingfelderChargeDecreaseModel, G4BoldyshevTripletModel, G4LivermoreGammaConversionModelRC, G4LivermoreNuclearGammaConversionModel, G4LivermoreRayleighModel, G4DNAScreenedRutherfordElasticModel, G4DNAUeharaScreenedRutherfordElasticModel, G4LEPTSAttachmentModel, G4LEPTSDissociationModel, G4LEPTSElasticModel, G4LEPTSExcitationModel, G4LEPTSIonisationModel, G4LEPTSPositroniumModel, G4LEPTSRotExcitationModel, and G4LEPTSVibExcitationModel.
Referenced by G4DNADummyModel::Initialise(), G4LivermoreGammaConversionModel::Initialise(), G4eBremsstrahlungRelModel::Initialise(), G4SeltzerBergerModel::Initialise(), G4EmModelManager::Initialise(), InitialiseElementSelectors(), and main().
InitialiseElementSelectors()
void G4VEmModel::InitialiseElementSelectors (const G4ParticleDefinition * part, const G4DataVector & cuts)
Definition at line 145 of file G4VEmModel.cc.
Referenced by G4LivermoreRayleighModel::Initialise(), G4LivermoreGammaConversionModel::Initialise(), G4LivermorePolarizedGammaConversionModel::Initialise(), G4XrayRayleighModel::Initialise(), G4LivermoreComptonModel::Initialise(), G4LivermoreComptonModifiedModel::Initialise(), G4LivermorePolarizedRayleighModel::Initialise(), G4JAEAElasticScatteringModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4KleinNishinaCompton::Initialise(), G4KleinNishinaModel::Initialise(), G4eBremsstrahlungRelModel::Initialise(), G4PenelopePhotoElectricModel::Initialise(), G4eBremParametrizedModel::Initialise(), G4BetheHeitlerModel::Initialise(), G4PAIPhotModel::Initialise(), G4eSingleCoulombScatteringModel::Initialise(), G4hCoulombScatteringModel::Initialise(), G4SeltzerBergerModel::Initialise(), G4PairProductionRelModel::Initialise(), G4PAIModel::Initialise(), G4MuPairProductionModel::Initialise(), G4MuBremsstrahlungModel::Initialise(), G4eCoulombScatteringModel::Initialise(), G4LowEPComptonModel::Initialise(), and G4LowEPPolarizedComptonModel::Initialise().
InitialiseForElement()
void G4VEmModel::InitialiseForElement (const G4ParticleDefinition * , G4int Z) virtual
Reimplemented in G4SeltzerBergerModel, G4LowEPPolarizedComptonModel, G4LowEPComptonModel, G4LivermorePhotoElectricModel, G4LivermorePolarizedPhotoElectricModel, G4LivermoreBremsstrahlungModel, G4LivermorePolarizedPhotoElectricGDModel, G4JAEAElasticScatteringModel, G4LivermorePolarizedComptonModel, G4LivermorePolarizedRayleighModel, G4LivermoreComptonModel, G4LivermoreGammaConversionModel, G4LivermorePolarizedGammaConversionModel, G4LivermoreNuclearGammaConversionModel, G4LivermoreGammaConversionModelRC, G4LivermoreRayleighModel, and G4BoldyshevTripletModel.
Definition at line 237 of file G4VEmModel.cc.
Referenced by G4EmCalculator::ComputeCrossSectionPerAtom(), G4EmCalculator::ComputeCrossSectionPerShell(), G4LivermoreGammaConversionModel::InitialiseForElement(), and InitialiseForMaterial().
InitialiseForMaterial()
void G4VEmModel::InitialiseForMaterial (const G4ParticleDefinition * part, const G4Material * material) virtual
Definition at line 223 of file G4VEmModel.cc.
Referenced by G4EmCalculator::FindEmModel().
InitialiseLocal()
void G4VEmModel::InitialiseLocal (const G4ParticleDefinition * , G4VEmModel * masterModel) virtual
Reimplemented in G4GoudsmitSaundersonMscModel, G4eCoulombScatteringModel, G4MuBremsstrahlungModel, G4MuPairProductionModel, G4PairProductionRelModel, G4hCoulombScatteringModel, G4WentzelVIModel, G4BetheHeitlerModel, G4eBremParametrizedModel, G4eBremsstrahlungRelModel, G4KleinNishinaCompton, G4KleinNishinaModel, G4PAIModel, G4eSingleCoulombScatteringModel, G4PAIPhotModel, G4LowEPPolarizedComptonModel, G4LowEPComptonModel, G4PenelopeComptonModel, G4PenelopePhotoElectricModel, G4PenelopeRayleighModel, G4JAEAElasticScatteringModel, G4LivermorePolarizedComptonModel, G4LivermorePolarizedRayleighModel, G4LivermoreComptonModel, G4LivermoreGammaConversionModel, G4LivermorePolarizedGammaConversionModel, G4LivermoreNuclearGammaConversionModel, G4LivermoreGammaConversionModelRC, G4LivermoreRayleighModel, G4PenelopeIonisationModel, G4PenelopeBremsstrahlungModel, G4PenelopeGammaConversionModel, and G4PenelopeAnnihilationModel.
Definition at line 217 of file G4VEmModel.cc.
Referenced by G4VEmProcess::BuildPhysicsTable(), G4VMultipleScattering::BuildPhysicsTable(), and G4VEnergyLossProcess::BuildPhysicsTable().
IsActive()
G4bool G4VEmModel::IsActive (G4double kinEnergy) inline
Definition at line 731 of file G4VEmModel.hh.
Referenced by G4NuclearStopping::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepGetPhysicalInteractionLength(), G4VMultipleScattering::AlongStepGetPhysicalInteractionLength(), G4VEmProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), G4VEmProcess::PostStepGetPhysicalInteractionLength(), and G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength().
IsLocked()
G4bool G4VEmModel::IsLocked () const inline
Definition at line 811 of file G4VEmModel.hh.
Referenced by G4VMscModel::SetGeomFactor(), G4VMscModel::SetLateralDisplasmentFlag(), G4VMscModel::SetRangeFactor(), G4VMscModel::SetSampleZ(), G4VMscModel::SetSkin(), and G4VMscModel::SetStepLimitType().
IsMaster()
G4bool G4VEmModel::IsMaster () const inline
Definition at line 696 of file G4VEmModel.hh.
Referenced by G4PenelopeBremsstrahlungModel::BuildXSTable(), G4PenelopeBremsstrahlungModel::ClearTables(), G4MuPairProductionModel::DataCorrupted(), G4PenelopePhotoElectricModel::GetNumberOfShellXS(), G4VMscModel::GetParticleChangeForMSC(), G4LivermoreRayleighModel::Initialise(), G4BoldyshevTripletModel::Initialise(), G4LivermorePolarizedGammaConversionModel::Initialise(), G4LivermorePolarizedPhotoElectricGDModel::Initialise(), G4LivermoreGammaConversionModel::Initialise(), G4LivermoreComptonModel::Initialise(), G4LivermorePhotoElectricModel::Initialise(), G4LivermorePolarizedPhotoElectricModel::Initialise(), G4LivermorePolarizedRayleighModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4JAEAElasticScatteringModel::Initialise(), G4PenelopeAnnihilationModel::Initialise(), G4eplusTo2GammaOKVIModel::Initialise(), G4PenelopeGammaConversionModel::Initialise(), G4PenelopeRayleighModel::Initialise(), G4mplIonisationWithDeltaModel::Initialise(), G4KleinNishinaCompton::Initialise(), G4KleinNishinaModel::Initialise(), G4mplIonisationModel::Initialise(), G4PenelopePhotoElectricModel::Initialise(), G4eBremsstrahlungRelModel::Initialise(), G4eBremParametrizedModel::Initialise(), G4LindhardSorensenIonModel::Initialise(), G4LivermoreBremsstrahlungModel::Initialise(), G4BetheHeitlerModel::Initialise(), G4PenelopeComptonModel::Initialise(), G4PenelopeBremsstrahlungModel::Initialise(), G4BetheBlochModel::Initialise(), G4PAIPhotModel::Initialise(), G4WentzelVIModel::Initialise(), G4eSingleCoulombScatteringModel::Initialise(), G4hCoulombScatteringModel::Initialise(), G4PenelopeIonisationModel::Initialise(), G4PairProductionRelModel::Initialise(), G4SeltzerBergerModel::Initialise(), G4PAIModel::Initialise(), G4BraggIonModel::Initialise(), G4MuBremsstrahlungModel::Initialise(), G4MuPairProductionModel::Initialise(), G4BraggModel::Initialise(), G4eCoulombScatteringModel::Initialise(), G4LowEPComptonModel::Initialise(), G4LowEPPolarizedComptonModel::Initialise(), G4GoudsmitSaundersonMscModel::Initialise(), G4PenelopeBremsstrahlungModel::InitialiseLocal(), G4PenelopeGammaConversionModel::ReadDataFile(), G4PenelopePhotoElectricModel::ReadDataFile(), G4BetheHeitlerModel::~G4BetheHeitlerModel(), G4BoldyshevTripletModel::~G4BoldyshevTripletModel(), G4BraggIonModel::~G4BraggIonModel(), G4BraggModel::~G4BraggModel(), G4eBremsstrahlungRelModel::~G4eBremsstrahlungRelModel(), G4GoudsmitSaundersonMscModel::~G4GoudsmitSaundersonMscModel(), G4JAEAElasticScatteringModel::~G4JAEAElasticScatteringModel(), G4LivermoreBremsstrahlungModel::~G4LivermoreBremsstrahlungModel(), G4LivermoreComptonModel::~G4LivermoreComptonModel(), G4LivermoreGammaConversionModel::~G4LivermoreGammaConversionModel(), G4LivermorePhotoElectricModel::~G4LivermorePhotoElectricModel(), G4LivermorePolarizedComptonModel::~G4LivermorePolarizedComptonModel(), G4LivermorePolarizedGammaConversionModel::~G4LivermorePolarizedGammaConversionModel(), G4LivermorePolarizedPhotoElectricGDModel::~G4LivermorePolarizedPhotoElectricGDModel(), G4LivermorePolarizedPhotoElectricModel::~G4LivermorePolarizedPhotoElectricModel(), G4LivermorePolarizedRayleighModel::~G4LivermorePolarizedRayleighModel(), G4LivermoreRayleighModel::~G4LivermoreRayleighModel(), G4LowEPComptonModel::~G4LowEPComptonModel(), G4LowEPPolarizedComptonModel::~G4LowEPPolarizedComptonModel(), G4mplIonisationModel::~G4mplIonisationModel(), G4mplIonisationWithDeltaModel::~G4mplIonisationWithDeltaModel(), G4PAIModel::~G4PAIModel(), G4PAIPhotModel::~G4PAIPhotModel(), G4PairProductionRelModel::~G4PairProductionRelModel(), G4PenelopeBremsstrahlungModel::~G4PenelopeBremsstrahlungModel(), G4PenelopeGammaConversionModel::~G4PenelopeGammaConversionModel(), G4PenelopeIonisationModel::~G4PenelopeIonisationModel(), G4PenelopePhotoElectricModel::~G4PenelopePhotoElectricModel(), G4PenelopeRayleighModel::~G4PenelopeRayleighModel(), G4SeltzerBergerModel::~G4SeltzerBergerModel(), and G4WentzelVIModel::~G4WentzelVIModel().
LowEnergyActivationLimit()
G4double G4VEmModel::LowEnergyActivationLimit () const inline
Definition at line 626 of file G4VEmModel.hh.
Referenced by G4EmModelManager::DumpModelList(), G4VMscModel::GetParticleChangeForMSC(), G4WentzelVIModel::Initialise(), and G4EmModelManager::Initialise().
LowEnergyLimit()
G4double G4VEmModel::LowEnergyLimit () const inline
Definition at line 612 of file G4VEmModel.hh.
Referenced by G4LivermoreComptonModifiedModel::ComputeCrossSectionPerAtom(), G4LivermoreComptonModel::ComputeCrossSectionPerAtom(), G4LivermorePolarizedComptonModel::ComputeCrossSectionPerAtom(), G4KleinNishinaCompton::ComputeCrossSectionPerAtom(), G4KleinNishinaModel::ComputeCrossSectionPerAtom(), G4eBremsstrahlungRelModel::ComputeCrossSectionPerAtom(), G4LowEPComptonModel::ComputeCrossSectionPerAtom(), G4LowEPPolarizedComptonModel::ComputeCrossSectionPerAtom(), G4mplIonisationWithDeltaModel::ComputeCrossSectionPerElectron(), G4EmCalculator::ComputeDEDX(), G4mplIonisationWithDeltaModel::ComputeDEDXPerVolume(), G4eBremsstrahlungRelModel::ComputeDEDXPerVolume(), G4IonParametrisedLossModel::ComputeDEDXPerVolume(), G4IonParametrisedLossModel::CorrectionsAlongStep(), G4DNAScreenedRutherfordElasticModel::CrossSectionPerVolume(), G4DNAChampionElasticModel::CrossSectionPerVolume(), G4DNAMeltonAttachmentModel::CrossSectionPerVolume(), G4DNASancheExcitationModel::CrossSectionPerVolume(), G4DNAEmfietzoglouExcitationModel::CrossSectionPerVolume(), G4DNAEmfietzoglouIonisationModel::CrossSectionPerVolume(), G4DNACPA100ExcitationModel::CrossSectionPerVolume(), G4DNACPA100IonisationModel::CrossSectionPerVolume(), G4PenelopeComptonModel::CrossSectionPerVolume(), G4EmCalculator::FindEmModel(), G4DNAChampionElasticModel::G4DNAChampionElasticModel(), G4DNACPA100ElasticModel::G4DNACPA100ElasticModel(), G4DNAMeltonAttachmentModel::G4DNAMeltonAttachmentModel(), G4DNASancheExcitationModel::G4DNASancheExcitationModel(), G4DNAUeharaScreenedRutherfordElasticModel::G4DNAUeharaScreenedRutherfordElasticModel(), G4eeToHadronsModel::G4eeToHadronsModel(), G4LivermorePolarizedRayleighModel::G4LivermorePolarizedRayleighModel(), G4PenelopeBremsstrahlungModel::GetCrossSectionTableForCouple(), G4VMscModel::GetParticleChangeForMSC(), G4DNAUeharaScreenedRutherfordElasticModel::Initialise(), G4DNAScreenedRutherfordElasticModel::Initialise(), G4LivermoreRayleighModel::Initialise(), G4DNADummyModel::Initialise(), G4BoldyshevTripletModel::Initialise(), G4DNADingfelderChargeDecreaseModel::Initialise(), G4DNABornExcitationModel1::Initialise(), G4DNADingfelderChargeIncreaseModel::Initialise(), G4DNAChampionElasticModel::Initialise(), G4DNAMeltonAttachmentModel::Initialise(), G4DNASancheExcitationModel::Initialise(), G4DNABornExcitationModel2::Initialise(), G4LivermoreGammaConversionModel::Initialise(), G4LivermorePolarizedGammaConversionModel::Initialise(), G4DNAMillerGreenExcitationModel::Initialise(), G4LivermoreComptonModel::Initialise(), G4DNARuddIonisationExtendedModel::Initialise(), G4DNARuddIonisationModel::Initialise(), G4DNABornIonisationModel2::Initialise(), G4LivermoreComptonModifiedModel::Initialise(), G4DNABornIonisationModel1::Initialise(), G4DNAIonElasticModel::Initialise(), G4MicroElecElasticModel::Initialise(), G4MuElecElasticModel::Initialise(), G4DNAEmfietzoglouExcitationModel::Initialise(), G4JAEAElasticScatteringModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4DNAEmfietzoglouIonisationModel::Initialise(), G4PenelopeAnnihilationModel::Initialise(), G4DNACPA100ElasticModel::Initialise(), G4PenelopeGammaConversionModel::Initialise(), G4PenelopeRayleighModel::Initialise(), G4DNACPA100ExcitationModel::Initialise(), G4LivermoreIonisationModel::Initialise(), G4PenelopePhotoElectricModel::Initialise(), G4eBremsstrahlungRelModel::Initialise(), G4eBremParametrizedModel::Initialise(), G4DNACPA100IonisationModel::Initialise(), G4PenelopeComptonModel::Initialise(), G4PenelopeBremsstrahlungModel::Initialise(), G4PAIPhotModel::Initialise(), G4WentzelVIModel::Initialise(), G4MicroElecInelasticModel::Initialise(), G4MuElecInelasticModel::Initialise(), G4PenelopeIonisationModel::Initialise(), G4SeltzerBergerModel::Initialise(), G4PairProductionRelModel::Initialise(), G4PAIModel::Initialise(), G4MuPairProductionModel::Initialise(), G4LowEPComptonModel::Initialise(), G4LowEPPolarizedComptonModel::Initialise(), G4GoudsmitSaundersonMscModel::Initialise(), G4EmModelManager::Initialise(), G4eBremsstrahlungRelModel::InitialiseLocal(), G4PairProductionRelModel::InitialiseLocal(), G4CoulombScattering::InitialiseProcess(), G4HeatedKleinNishinaCompton::SampleSecondaries(), G4LivermoreComptonModifiedModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4KleinNishinaCompton::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), G4LowEPPolarizedComptonModel::SampleSecondaries(), G4EmConfigurator::SetExtraEmModel(), G4mplIonisationModel::SetParticle(), G4mplIonisationWithDeltaModel::SetParticle(), and G4EmConfigurator::UpdateModelEnergyRange().
LPMFlag()
G4bool G4VEmModel::LPMFlag () const inline
Definition at line 647 of file G4VEmModel.hh.
Referenced by G4eBremsstrahlungRelModel::Initialise(), G4SeltzerBergerModel::SetupForMaterial(), G4eBremsstrahlungRelModel::SetupForMaterial(), and G4eBremsstrahlungRelModel::~G4eBremsstrahlungRelModel().
MaxSecondaryEnergy()
G4double G4VEmModel::MaxSecondaryEnergy (const G4ParticleDefinition * , G4double kineticEnergy) protected virtual
Reimplemented in G4IonParametrisedLossModel, G4BetheBlochModel, G4LindhardSorensenIonModel, G4AtimaEnergyLossModel, G4MuBetheBlochModel, G4mplIonisationWithDeltaModel, G4BraggIonModel, G4BraggModel, G4ICRU73QOModel, G4PAIModel, G4PAIPhotModel, and G4MollerBhabhaModel.
Definition at line 438 of file G4VEmModel.cc.
Referenced by MaxSecondaryKinEnergy().
MaxSecondaryKinEnergy()
G4double G4VEmModel::MaxSecondaryKinEnergy (const G4DynamicParticle * dynParticle) inline
Definition at line 488 of file G4VEmModel.hh.
Referenced by G4ContinuousGainOfEnergy::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepDoIt(), G4VEnergyLossProcess::GetDEDXDispersion(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4ICRU73QOModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4MuBetheBlochModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), and G4IonParametrisedLossModel::SampleSecondaries().
MinEnergyCut()
G4double G4VEmModel::MinEnergyCut (const G4ParticleDefinition * , const G4MaterialCutsCouple *) virtual
Reimplemented in G4mplIonisationWithDeltaModel, G4BraggIonModel, G4BetheBlochModel, G4LindhardSorensenIonModel, G4AtimaEnergyLossModel, G4PAIModel, G4PAIPhotModel, G4MuBremsstrahlungModel, G4MuBetheBlochModel, G4eBremParametrizedModel, G4PenelopeIonisationModel, G4IonParametrisedLossModel, and G4PenelopeBremsstrahlungModel.
Definition at line 430 of file G4VEmModel.cc.
Referenced by G4EmModelManager::Initialise().
MinPrimaryEnergy()
G4double G4VEmModel::MinPrimaryEnergy (const G4Material * , const G4ParticleDefinition * , G4double cut = 0.0) virtual
Reimplemented in G4MuBremsstrahlungModel, G4MuPairProductionModel, G4eCoulombScatteringModel, G4hCoulombScatteringModel, G4LivermoreGammaConversionModel, G4LivermorePolarizedGammaConversionModel, G4LivermoreNuclearGammaConversionModel, G4LivermoreGammaConversionModelRC, G4BoldyshevTripletModel, and G4eBremsstrahlungRelModel.
Definition at line 421 of file G4VEmModel.cc.
Referenced by G4LossTableBuilder::BuildTableForModel(), InitialiseElementSelectors(), and G4LivermoreGammaConversionModel::InitialiseProbability().
ModelDescription()
void G4VEmModel::ModelDescription (std::ostream & outFile) const virtual
Reimplemented in G4eeToHadronsMultiModel.
Definition at line 475 of file G4VEmModel.cc.
operator=()
G4VEmModel& G4VEmModel::operator= (const G4VEmModel & right) private delete
PolarAngleLimit()
G4double G4VEmModel::PolarAngleLimit () const inline
Definition at line 633 of file G4VEmModel.hh.
Referenced by G4WentzelVIModel::Initialise(), G4hCoulombScatteringModel::Initialise(), and G4eCoulombScatteringModel::Initialise().
SampleSecondaries()
virtual void G4VEmModel::SampleSecondaries (std::vector< G4DynamicParticle * > * , const G4MaterialCutsCouple * , const G4DynamicParticle * , G4double tmin = 0.0, G4double tmax = DBL_MAX) pure virtual
Implemented in G4BetheHeitler5DModel, G4DNAModelInterface, G4ICRU49NuclearStoppingModel, G4IonParametrisedLossModel, G4LEPTSAttachmentModel, G4LEPTSExcitationModel, G4LEPTSDissociationModel, G4LEPTSElasticModel, G4LEPTSIonisationModel, G4LEPTSPositroniumModel, G4LEPTSRotExcitationModel, G4LEPTSVibExcitationModel, G4eeToHadronsModel, G4eeToHadronsMultiModel, G4eplusTo2GammaOKVIModel, G4eplusTo3GammaOKVIModel, G4VMscModel, G4EmMultiModel, G4DummyModel, G4BetheBlochModel, G4LindhardSorensenIonModel, G4AtimaEnergyLossModel, G4MuBetheBlochModel, G4BraggIonModel, G4BraggModel, G4ICRU73QOModel, G4MuBremsstrahlungModel, G4eCoulombScatteringModel, G4MuPairProductionModel, G4MollerBhabhaModel, G4PairProductionRelModel, G4hCoulombScatteringModel, G4mplIonisationWithDeltaModel, G4eeToTwoGammaModel, G4BetheHeitlerModel, G4PEEffectFluoModel, G4KleinNishinaCompton, G4KleinNishinaModel, G4LDMBremModel, G4PolarizedComptonModel, G4mplIonisationModel, G4PolarizedPEEffectModel, G4PolarizedMollerBhabhaModel, G4ePolarizedBremsstrahlungModel, G4PolarizedGammaConversionModel, G4PAIModel, G4PAIPhotModel, G4IonCoulombScatteringModel, G4eSingleCoulombScatteringModel, G4PolarizedAnnihilationModel, G4HeatedKleinNishinaCompton, G4TDNAOneStepThermalizationModel< MODEL >, G4LowEPPolarizedComptonModel, G4LowEPComptonModel, G4PenelopeIonisationModel, G4PenelopeBremsstrahlungModel, G4PenelopeComptonModel, G4MicroElecInelasticModel, G4MuElecInelasticModel, G4PenelopePhotoElectricModel, G4DNACPA100IonisationModel, G4JAEAElasticScatteringModel, G4LivermoreIonisationModel, G4PenelopeRayleighModel, G4LivermorePolarizedComptonModel, G4PenelopeGammaConversionModel, G4PenelopeAnnihilationModel, G4DNACPA100ExcitationModel, G4DNATransformElectronModel, G4LivermorePhotoElectricModel, G4LivermorePolarizedPhotoElectricModel, G4LivermorePolarizedRayleighModel, G4DNACPA100ElasticModel, G4DNAEmfietzoglouIonisationModel, G4DNAEmfietzoglouExcitationModel, G4LivermoreComptonModel, G4MicroElecElasticModel, G4MuElecElasticModel, G4LivermoreGammaConversionModel, G4DNAIonElasticModel, G4LivermorePolarizedGammaConversionModel, G4DNABornExcitationModel2, G4DNAMillerGreenExcitationModel, G4LivermoreComptonModifiedModel, G4LivermoreNuclearGammaConversionModel, G4DNABornIonisationModel1, G4DNABornIonisationModel2, G4DNABornExcitationModel1, G4LivermoreGammaConversionModelRC, G4DNARuddIonisationExtendedModel, G4DNARuddIonisationModel, G4LivermoreRayleighModel, G4BoldyshevTripletModel, G4LivermorePolarizedPhotoElectricGDModel, G4XrayRayleighModel, MyKleinNishinaCompton, G4DNASancheExcitationModel, G4DNAChampionElasticModel, G4DNAMeltonAttachmentModel, G4DNADingfelderChargeIncreaseModel, G4DNADingfelderChargeDecreaseModel, G4DNAScreenedRutherfordElasticModel, G4DNAUeharaScreenedRutherfordElasticModel, G4eBremParametrizedModel, G4eBremsstrahlungRelModel, G4SeltzerBergerModel, and G4LivermoreBremsstrahlungModel.
Referenced by G4EmBiasingManager::ApplyDirectionalSplitting(), G4EmBiasingManager::ApplySplitting(), G4eplusAnnihilation::AtRestDoIt(), G4VEmProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), G4DNADummyModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), and G4VEnergyLossProcess::SampleSubCutSecondaries().
SecondaryThreshold()
G4double G4VEmModel::SecondaryThreshold () const inline
Definition at line 640 of file G4VEmModel.hh.
Referenced by G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), and G4eBremParametrizedModel::SampleSecondaries().
SelectIsotopeNumber()
G4int G4VEmModel::SelectIsotopeNumber (const G4Element * elm)
Definition at line 334 of file G4VEmModel.cc.
Referenced by G4BetheHeitler5DModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), and G4eCoulombScatteringModel::SampleSecondaries().
SelectRandomAtom() [1/2]
const G4Element * G4VEmModel::SelectRandomAtom (const G4Material * material, const G4ParticleDefinition * pd, G4double kineticEnergy, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX)
Definition at line 290 of file G4VEmModel.cc.
SelectRandomAtom() [2/2]
const G4Element * G4VEmModel::SelectRandomAtom (const G4MaterialCutsCouple * couple, const G4ParticleDefinition * part, G4double kineticEnergy, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) inline
Definition at line 548 of file G4VEmModel.hh.
Referenced by G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4XrayRayleighModel::SampleSecondaries(), G4LivermoreRayleighModel::SampleSecondaries(), G4LivermoreComptonModifiedModel::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4LivermorePhotoElectricModel::SampleSecondaries(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), G4LivermorePolarizedRayleighModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4JAEAElasticScatteringModel::SampleSecondaries(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4LDMBremModel::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4PEEffectFluoModel::SampleSecondaries(), G4BetheHeitlerModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), G4eBremParametrizedModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4PairProductionRelModel::SampleSecondaries(), G4PAIPhotModel::SampleSecondaries(), G4PAIModel::SampleSecondaries(), G4MuPairProductionModel::SampleSecondaries(), G4eCoulombScatteringModel::SampleSecondaries(), G4MuBremsstrahlungModel::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), and G4LowEPPolarizedComptonModel::SampleSecondaries().
SelectRandomAtomNumber()
G4int G4VEmModel::SelectRandomAtomNumber (const G4Material * mat)
Definition at line 312 of file G4VEmModel.cc.
Referenced by G4MollerBhabhaModel::SampleSecondaries(), G4ICRU73QOModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), G4BetheBlochModel::SampleSecondaries(), and G4IonParametrisedLossModel::SampleSecondaries().
SetActivationHighEnergyLimit()
void G4VEmModel::SetActivationHighEnergyLimit (G4double val) inline
Definition at line 717 of file G4VEmModel.hh.
Referenced by G4EmModelActivator::ActivateMicroElec(), PhysicsList::ConstructEM(), G4EmDNAPhysics_option7::ConstructProcess(), G4EmDNAPhysics_option8::ConstructProcess(), G4NuclearStopping::InitialiseProcess(), and G4EmConfigurator::SetExtraEmModel().
SetActivationLowEnergyLimit()
void G4VEmModel::SetActivationLowEnergyLimit (G4double val) inline
Definition at line 724 of file G4VEmModel.hh.
Referenced by G4EmModelActivator::ActivateMicroElec(), G4EmDNAPhysicsActivator::AddElectronModels0(), G4EmDNAPhysicsActivator::AddGenericIonModels0(), G4EmDNAPhysicsActivator::AddHeliumModels0(), G4EmDNAPhysicsActivator::AddProtonModels0(), G4EmModelActivator::AddStandardScattering(), PhysicsList::ConstructEM(), G4EmPenelopePhysics::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmDNAPhysics_option7::ConstructProcess(), G4EmDNAPhysics_option8::ConstructProcess(), PhysListEmStandardNR::ConstructProcess(), PhysListEm5DStandard::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), G4EmStandardPhysics_option2::ConstructProcess(), and G4EmDNAPhysicsActivator::DeactivateNuclearStopping().
SetAngularDistribution()
void G4VEmModel::SetAngularDistribution (G4VEmAngularDistribution * p) inline
Definition at line 578 of file G4VEmModel.hh.
Referenced by G4EmLivermorePhysics::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4BetheHeitlerModel::G4BetheHeitlerModel(), G4DNABornIonisationModel1::G4DNABornIonisationModel1(), G4DNABornIonisationModel2::G4DNABornIonisationModel2(), G4DNAEmfietzoglouIonisationModel::G4DNAEmfietzoglouIonisationModel(), G4DNARuddIonisationExtendedModel::G4DNARuddIonisationExtendedModel(), G4DNARuddIonisationModel::G4DNARuddIonisationModel(), G4eBremParametrizedModel::G4eBremParametrizedModel(), G4eBremsstrahlungRelModel::G4eBremsstrahlungRelModel(), G4IonParametrisedLossModel::G4IonParametrisedLossModel(), G4LivermoreBremsstrahlungModel::G4LivermoreBremsstrahlungModel(), G4LivermoreIonisationModel::G4LivermoreIonisationModel(), G4LivermorePhotoElectricModel::G4LivermorePhotoElectricModel(), G4LivermorePolarizedPhotoElectricModel::G4LivermorePolarizedPhotoElectricModel(), G4LivermoreRayleighModel::G4LivermoreRayleighModel(), G4MicroElecInelasticModel::G4MicroElecInelasticModel(), G4PAIModel::G4PAIModel(), G4PAIPhotModel::G4PAIPhotModel(), G4PairProductionRelModel::G4PairProductionRelModel(), G4PEEffectFluoModel::G4PEEffectFluoModel(), G4SeltzerBergerModel::G4SeltzerBergerModel(), G4AtimaEnergyLossModel::Initialise(), G4LindhardSorensenIonModel::Initialise(), G4MollerBhabhaModel::Initialise(), G4BetheBlochModel::Initialise(), G4BraggIonModel::Initialise(), G4ICRU73QOModel::Initialise(), and G4BraggModel::Initialise().
SetAngularGeneratorFlag()
void G4VEmModel::SetAngularGeneratorFlag (G4bool val) inline
Definition at line 675 of file G4VEmModel.hh.
Referenced by G4VEnergyLossProcess::PreparePhysicsTable().
SetCrossSectionTable()
void G4VEmModel::SetCrossSectionTable (G4PhysicsTable * p, G4bool isLocal)
Definition at line 461 of file G4VEmModel.cc.
Referenced by G4VMultipleScattering::BuildPhysicsTable().
SetCurrentCouple()
void G4VEmModel::SetCurrentCouple (const G4MaterialCutsCouple * p) inline
Definition at line 451 of file G4VEmModel.hh.
Referenced by G4EmMultiModel::ComputeCrossSectionPerAtom(), G4EmMultiModel::ComputeDEDX(), ComputeDEDX(), G4TablesForExtrapolator::ComputeTrasportXS(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), CrossSection(), G4AdjointPhotoElectricModel::DefineCurrentMaterialAndElectronEnergy(), G4WentzelVIRelModel::DefineMaterial(), G4WentzelVIModel::DefineMaterial(), G4EmCalculator::GetCrossSectionPerVolume(), G4LivermoreGammaConversionModel::Initialise(), main(), G4PEEffectFluoModel::SampleSecondaries(), G4EmMultiModel::SampleSecondaries(), G4VEmProcess::SelectModel(), G4VEnergyLossProcess::SelectModel(), and Value().
SetCurrentElement()
void G4VEmModel::SetCurrentElement (const G4Element * elm) inline protected
Definition at line 465 of file G4VEmModel.hh.
Referenced by ComputeCrossSectionPerAtom(), G4eBremsstrahlungRelModel::ComputeDEDXPerVolume(), G4eBremParametrizedModel::ComputeDEDXPerVolume(), and SelectIsotopeNumber().
SetDeexcitationFlag()
void G4VEmModel::SetDeexcitationFlag (G4bool val) inline
Definition at line 759 of file G4VEmModel.hh.
Referenced by G4DNABornIonisationModel1::G4DNABornIonisationModel1(), G4DNABornIonisationModel2::G4DNABornIonisationModel2(), G4DNACPA100IonisationModel::G4DNACPA100IonisationModel(), G4DNAEmfietzoglouIonisationModel::G4DNAEmfietzoglouIonisationModel(), G4DNARuddIonisationExtendedModel::G4DNARuddIonisationExtendedModel(), G4DNARuddIonisationModel::G4DNARuddIonisationModel(), G4KleinNishinaModel::G4KleinNishinaModel(), G4LEPTSIonisationModel::G4LEPTSIonisationModel(), G4LivermoreComptonModel::G4LivermoreComptonModel(), G4LivermoreComptonModifiedModel::G4LivermoreComptonModifiedModel(), G4LivermorePhotoElectricModel::G4LivermorePhotoElectricModel(), G4LivermorePolarizedComptonModel::G4LivermorePolarizedComptonModel(), G4LivermorePolarizedPhotoElectricGDModel::G4LivermorePolarizedPhotoElectricGDModel(), G4LivermorePolarizedPhotoElectricModel::G4LivermorePolarizedPhotoElectricModel(), G4LowEPComptonModel::G4LowEPComptonModel(), G4LowEPPolarizedComptonModel::G4LowEPPolarizedComptonModel(), G4MicroElecInelasticModel::G4MicroElecInelasticModel(), G4MuElecInelasticModel::G4MuElecInelasticModel(), G4PEEffectFluoModel::G4PEEffectFluoModel(), G4PenelopeBremsstrahlungModel::G4PenelopeBremsstrahlungModel(), G4PenelopeComptonModel::G4PenelopeComptonModel(), G4PenelopeIonisationModel::G4PenelopeIonisationModel(), G4PenelopePhotoElectricModel::G4PenelopePhotoElectricModel(), G4AtimaEnergyLossModel::Initialise(), G4LindhardSorensenIonModel::Initialise(), G4BetheBlochModel::Initialise(), G4BraggIonModel::Initialise(), G4ICRU73QOModel::Initialise(), and G4BraggModel::Initialise().
SetElementSelectors()
void G4VEmModel::SetElementSelectors (std::vector< G4EmElementSelector * > * p) inline
Definition at line 788 of file G4VEmModel.hh.
Referenced by G4LivermoreRayleighModel::InitialiseLocal(), G4LivermorePolarizedGammaConversionModel::InitialiseLocal(), G4LivermoreGammaConversionModel::InitialiseLocal(), G4LivermoreComptonModel::InitialiseLocal(), G4LivermorePolarizedRayleighModel::InitialiseLocal(), G4LivermorePolarizedComptonModel::InitialiseLocal(), G4JAEAElasticScatteringModel::InitialiseLocal(), G4PenelopePhotoElectricModel::InitialiseLocal(), G4KleinNishinaCompton::InitialiseLocal(), G4KleinNishinaModel::InitialiseLocal(), G4eBremsstrahlungRelModel::InitialiseLocal(), G4eBremParametrizedModel::InitialiseLocal(), G4BetheHeitlerModel::InitialiseLocal(), G4PAIPhotModel::InitialiseLocal(), G4eSingleCoulombScatteringModel::InitialiseLocal(), G4hCoulombScatteringModel::InitialiseLocal(), G4PAIModel::InitialiseLocal(), G4PairProductionRelModel::InitialiseLocal(), G4MuBremsstrahlungModel::InitialiseLocal(), G4MuPairProductionModel::InitialiseLocal(), G4eCoulombScatteringModel::InitialiseLocal(), G4LowEPComptonModel::InitialiseLocal(), and G4LowEPPolarizedComptonModel::InitialiseLocal().
SetFluctuationFlag()
void G4VEmModel::SetFluctuationFlag (G4bool val) inline
Definition at line 682 of file G4VEmModel.hh.
Referenced by G4EmCalculator::ComputeNuclearDEDX().
SetForceBuildTable()
void G4VEmModel::SetForceBuildTable (G4bool val) inline
Definition at line 766 of file G4VEmModel.hh.
SetHighEnergyLimit()
void G4VEmModel::SetHighEnergyLimit (G4double val) inline
Definition at line 703 of file G4VEmModel.hh.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmDNAPhysics_option3::ConstructProcess(), G4EmDNAPhysics_option2::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4EmDNAPhysics_option4::ConstructProcess(), G4EmDNAPhysics_option5::ConstructProcess(), G4EmDNAPhysics_option7::ConstructProcess(), G4EmDNAPhysics_option8::ConstructProcess(), PhysListEmLivermore::ConstructProcess(), PhysListEmPenelope::ConstructProcess(), PhysListEmStandardNR::ConstructProcess(), G4EmLEPTSPhysics::ConstructProcess(), G4EmDNAPhysics_option6::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), PhysListEm5DStandard::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), G4EmStandardPhysics_option2::ConstructProcess(), G4BraggIonModel::G4BraggIonModel(), G4BraggModel::G4BraggModel(), G4DNAChampionElasticModel::G4DNAChampionElasticModel(), G4DNACPA100ElasticModel::G4DNACPA100ElasticModel(), G4DNACPA100ExcitationModel::G4DNACPA100ExcitationModel(), G4DNACPA100IonisationModel::G4DNACPA100IonisationModel(), G4DNAEmfietzoglouExcitationModel::G4DNAEmfietzoglouExcitationModel(), G4DNAEmfietzoglouIonisationModel::G4DNAEmfietzoglouIonisationModel(), G4DNAIonElasticModel::G4DNAIonElasticModel(), G4DNAMeltonAttachmentModel::G4DNAMeltonAttachmentModel(), G4DNASancheExcitationModel::G4DNASancheExcitationModel(), G4DNAScreenedRutherfordElasticModel::G4DNAScreenedRutherfordElasticModel(), G4DNATransformElectronModel::G4DNATransformElectronModel(), G4DNAUeharaScreenedRutherfordElasticModel::G4DNAUeharaScreenedRutherfordElasticModel(), G4ICRU73QOModel::G4ICRU73QOModel(), G4IonParametrisedLossModel::G4IonParametrisedLossModel(), G4MicroElecElasticModel::G4MicroElecElasticModel(), G4MuElecElasticModel::G4MuElecElasticModel(), G4PenelopeAnnihilationModel::G4PenelopeAnnihilationModel(), G4PenelopeBremsstrahlungModel::G4PenelopeBremsstrahlungModel(), G4PenelopeComptonModel::G4PenelopeComptonModel(), G4PenelopeGammaConversionModel::G4PenelopeGammaConversionModel(), G4PenelopeIonisationModel::G4PenelopeIonisationModel(), G4PenelopePhotoElectricModel::G4PenelopePhotoElectricModel(), G4PenelopeRayleighModel::G4PenelopeRayleighModel(), G4XrayRayleighModel::G4XrayRayleighModel(), G4VLEPTSModel::Init(), G4DNADingfelderChargeDecreaseModel::Initialise(), G4DNAChampionElasticModel::Initialise(), G4DNADingfelderChargeIncreaseModel::Initialise(), G4DNABornExcitationModel1::Initialise(), G4DNAMeltonAttachmentModel::Initialise(), G4DNASancheExcitationModel::Initialise(), G4DNABornExcitationModel2::Initialise(), G4DNAMillerGreenExcitationModel::Initialise(), G4DNARuddIonisationModel::Initialise(), G4DNARuddIonisationExtendedModel::Initialise(), G4DNABornIonisationModel1::Initialise(), G4DNABornIonisationModel2::Initialise(), G4DNAIonElasticModel::Initialise(), G4MicroElecElasticModel::Initialise(), G4MuElecElasticModel::Initialise(), G4DNACPA100ElasticModel::Initialise(), G4DNAModelInterface::Initialise(), G4MicroElecInelasticModel::Initialise(), G4MuElecInelasticModel::Initialise(), G4ePolarizedBremsstrahlung::InitialiseEnergyLossProcess(), G4LDMBremsstrahlung::InitialiseEnergyLossProcess(), G4hPairProduction::InitialiseEnergyLossProcess(), G4hBremsstrahlung::InitialiseEnergyLossProcess(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4ePairProduction::InitialiseEnergyLossProcess(), G4ePolarizedIonisation::InitialiseEnergyLossProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4MuPairProduction::InitialiseEnergyLossProcess(), G4eIonisation::InitialiseEnergyLossProcess(), G4eBremsstrahlung::InitialiseEnergyLossProcess(), G4MuBremsstrahlung::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), G4DNARotExcitation::InitialiseProcess(), G4DNAPositronium::InitialiseProcess(), G4DNADissociation::InitialiseProcess(), G4DNAChargeIncrease::InitialiseProcess(), G4DNAAttachment::InitialiseProcess(), G4DNAChargeDecrease::InitialiseProcess(), G4DNAElastic::InitialiseProcess(), G4DNAExcitation::InitialiseProcess(), G4DNAIonisation::InitialiseProcess(), G4DNAVibExcitation::InitialiseProcess(), G4MuElecElastic::InitialiseProcess(), G4MuElecInelastic::InitialiseProcess(), G4CoulombScattering::InitialiseProcess(), G4PolarizedGammaConversion::InitialiseProcess(), G4ComptonScattering::InitialiseProcess(), G4eplusAnnihilation::InitialiseProcess(), G4PolarizedCompton::InitialiseProcess(), G4PolarizedPhotoElectricEffect::InitialiseProcess(), G4GammaConversion::InitialiseProcess(), G4PhotoElectricEffect::InitialiseProcess(), G4VEmProcess::PreparePhysicsTable(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4DNAUeharaScreenedRutherfordElasticModel::SelectHighEnergyLimit(), G4VEmAdjointModel::SetHighEnergyLimit(), G4mplIonisationModel::SetParticle(), G4mplIonisationWithDeltaModel::SetParticle(), and G4EmConfigurator::UpdateModelEnergyRange().
SetLocked()
void G4VEmModel::SetLocked (G4bool val) inline
Definition at line 818 of file G4VEmModel.hh.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmModelActivator::AddStandardScattering(), and G4EmModelActivator::GetGSModel().
SetLowEnergyLimit()
void G4VEmModel::SetLowEnergyLimit (G4double val) inline
Definition at line 710 of file G4VEmModel.hh.
Referenced by G4EmDNAPhysics_option2::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmDNAPhysics_option5::ConstructProcess(), PhysListEm5DStandard::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), G4EmStandardPhysics_option2::ConstructProcess(), G4DNASancheExcitationModel::ExtendLowEnergyLimit(), G4AtimaEnergyLossModel::G4AtimaEnergyLossModel(), G4BetheBlochModel::G4BetheBlochModel(), G4BetheHeitler5DModel::G4BetheHeitler5DModel(), G4DNAChampionElasticModel::G4DNAChampionElasticModel(), G4DNACPA100ElasticModel::G4DNACPA100ElasticModel(), G4DNACPA100ExcitationModel::G4DNACPA100ExcitationModel(), G4DNACPA100IonisationModel::G4DNACPA100IonisationModel(), G4DNAEmfietzoglouExcitationModel::G4DNAEmfietzoglouExcitationModel(), G4DNAEmfietzoglouIonisationModel::G4DNAEmfietzoglouIonisationModel(), G4DNAIonElasticModel::G4DNAIonElasticModel(), G4DNAMeltonAttachmentModel::G4DNAMeltonAttachmentModel(), G4DNASancheExcitationModel::G4DNASancheExcitationModel(), G4DNAScreenedRutherfordElasticModel::G4DNAScreenedRutherfordElasticModel(), G4DNATransformElectronModel::G4DNATransformElectronModel(), G4DNAUeharaScreenedRutherfordElasticModel::G4DNAUeharaScreenedRutherfordElasticModel(), G4DummyModel::G4DummyModel(), G4eBremParametrizedModel::G4eBremParametrizedModel(), G4eBremsstrahlungRelModel::G4eBremsstrahlungRelModel(), G4LindhardSorensenIonModel::G4LindhardSorensenIonModel(), G4LivermoreBremsstrahlungModel::G4LivermoreBremsstrahlungModel(), G4MicroElecElasticModel::G4MicroElecElasticModel(), G4MuElecElasticModel::G4MuElecElasticModel(), G4SeltzerBergerModel::G4SeltzerBergerModel(), G4VLEPTSModel::Init(), G4DNADingfelderChargeDecreaseModel::Initialise(), G4DNABornExcitationModel1::Initialise(), G4DNAChampionElasticModel::Initialise(), G4DNADingfelderChargeIncreaseModel::Initialise(), G4DNAMeltonAttachmentModel::Initialise(), G4DNABornExcitationModel2::Initialise(), G4DNAMillerGreenExcitationModel::Initialise(), G4DNARuddIonisationExtendedModel::Initialise(), G4DNARuddIonisationModel::Initialise(), G4DNABornIonisationModel1::Initialise(), G4DNABornIonisationModel2::Initialise(), G4DNAIonElasticModel::Initialise(), G4MuElecElasticModel::Initialise(), G4MicroElecElasticModel::Initialise(), G4DNACPA100ElasticModel::Initialise(), G4DNAModelInterface::Initialise(), G4MuElecInelasticModel::Initialise(), G4MicroElecInelasticModel::Initialise(), G4ePolarizedBremsstrahlung::InitialiseEnergyLossProcess(), G4LDMBremsstrahlung::InitialiseEnergyLossProcess(), G4hPairProduction::InitialiseEnergyLossProcess(), G4hBremsstrahlung::InitialiseEnergyLossProcess(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4ePairProduction::InitialiseEnergyLossProcess(), G4ePolarizedIonisation::InitialiseEnergyLossProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4MuPairProduction::InitialiseEnergyLossProcess(), G4eIonisation::InitialiseEnergyLossProcess(), G4eBremsstrahlung::InitialiseEnergyLossProcess(), G4MuBremsstrahlung::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), G4DNARotExcitation::InitialiseProcess(), G4DNADissociation::InitialiseProcess(), G4DNAPositronium::InitialiseProcess(), G4DNAChargeIncrease::InitialiseProcess(), G4DNAAttachment::InitialiseProcess(), G4DNAElastic::InitialiseProcess(), G4DNAChargeDecrease::InitialiseProcess(), G4DNAExcitation::InitialiseProcess(), G4DNAIonisation::InitialiseProcess(), G4DNAVibExcitation::InitialiseProcess(), G4MuElecElastic::InitialiseProcess(), G4MuElecInelastic::InitialiseProcess(), G4CoulombScattering::InitialiseProcess(), G4PolarizedGammaConversion::InitialiseProcess(), G4ComptonScattering::InitialiseProcess(), G4PolarizedCompton::InitialiseProcess(), G4eplusAnnihilation::InitialiseProcess(), G4PolarizedPhotoElectricEffect::InitialiseProcess(), G4GammaConversion::InitialiseProcess(), G4PhotoElectricEffect::InitialiseProcess(), G4VEmAdjointModel::SetLowEnergyLimit(), G4mplIonisationModel::SetParticle(), G4mplIonisationWithDeltaModel::SetParticle(), and G4EmConfigurator::UpdateModelEnergyRange().
SetLPMFlag()
void G4VEmModel::SetLPMFlag (G4bool val) inline
Definition at line 752 of file G4VEmModel.hh.
Referenced by G4eBremsstrahlungRelModel::G4eBremsstrahlungRelModel(), G4LivermoreBremsstrahlungModel::G4LivermoreBremsstrahlungModel(), G4SeltzerBergerModel::G4SeltzerBergerModel(), and G4eBremsstrahlung::InitialiseEnergyLossProcess().
SetMasterThread()
void G4VEmModel::SetMasterThread (G4bool val) inline
Definition at line 689 of file G4VEmModel.hh.
Referenced by G4VEmProcess::PreparePhysicsTable(), G4VMultipleScattering::PreparePhysicsTable(), and G4VEnergyLossProcess::PreparePhysicsTable().
SetParticleChange()
void G4VEmModel::SetParticleChange (G4VParticleChange * p, G4VEmFluctuationModel * f = nullptr)
Definition at line 453 of file G4VEmModel.cc.
Referenced by G4VMultipleScattering::AddEmModel(), G4VEmProcess::AddEmModel(), G4VEnergyLossProcess::AddEmModel(), GetParticleChangeForGamma(), GetParticleChangeForLoss(), G4DNADummyModel::Initialise(), G4LivermoreGammaConversionModel::Initialise(), G4EmMultiModel::Initialise(), G4IonParametrisedLossModel::Initialise(), and G4NuclearStopping::InitialiseProcess().
SetPolarAngleLimit()
void G4VEmModel::SetPolarAngleLimit (G4double val) inline
Definition at line 738 of file G4VEmModel.hh.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4TablesForExtrapolator::ComputeTrasportXS(), PhysListEmStandardSSM::ConstructProcess(), G4CoulombScattering::InitialiseProcess(), G4VEmProcess::PreparePhysicsTable(), and G4VMultipleScattering::PreparePhysicsTable().
SetSecondaryThreshold()
void G4VEmModel::SetSecondaryThreshold (G4double val) inline
Definition at line 745 of file G4VEmModel.hh.
Referenced by G4eBremsstrahlung::InitialiseEnergyLossProcess().
SetTripletModel()
void G4VEmModel::SetTripletModel (G4VEmModel * p) inline
Definition at line 595 of file G4VEmModel.hh.
Referenced by G4eplusTo2GammaOKVIModel::G4eplusTo2GammaOKVIModel().
SetupForMaterial()
void G4VEmModel::SetupForMaterial (const G4ParticleDefinition * , const G4Material * , G4double kineticEnergy) virtual
Reimplemented in G4PairProductionRelModel, G4eBremParametrizedModel, G4eBremsstrahlungRelModel, and G4SeltzerBergerModel.
Definition at line 446 of file G4VEmModel.cc.
Referenced by G4PenelopeComptonModel::CrossSectionPerVolume(), G4PenelopeBremsstrahlungModel::CrossSectionPerVolume(), G4PenelopeIonisationModel::CrossSectionPerVolume(), CrossSectionPerVolume(), G4EmCalculator::FindEmModel(), G4EmElementSelector::Initialise(), and G4LivermoreGammaConversionModel::InitialiseProbability().
StartTracking()
void G4VEmModel::StartTracking (G4Track *) virtual
Reimplemented in G4UrbanAdjointMscModel, G4UrbanMscModel, G4WentzelVIModel, and G4GoudsmitSaundersonMscModel.
Definition at line 285 of file G4VEmModel.cc.
Referenced by G4VMultipleScattering::StartTracking().
UseAngularGeneratorFlag()
G4bool G4VEmModel::UseAngularGeneratorFlag () const inline
Definition at line 668 of file G4VEmModel.hh.
Referenced by G4AtimaEnergyLossModel::Initialise(), G4LindhardSorensenIonModel::Initialise(), G4BetheBlochModel::Initialise(), G4MollerBhabhaModel::Initialise(), G4BraggIonModel::Initialise(), G4ICRU73QOModel::Initialise(), G4BraggModel::Initialise(), G4MollerBhabhaModel::SampleSecondaries(), G4ICRU73QOModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), and G4BetheBlochModel::SampleSecondaries().
Value()
G4double G4VEmModel::Value (const G4MaterialCutsCouple * couple, const G4ParticleDefinition * p, G4double kineticEnergy) virtual
Definition at line 412 of file G4VEmModel.cc.
Referenced by G4IonParametrisedLossModel::BuildRangeVector(), G4LossTableBuilder::BuildTableForModel(), G4LivermorePolarizedPhotoElectricGDModel::ComputeCrossSectionPerAtom(), G4LivermorePolarizedPhotoElectricModel::ComputeCrossSectionPerAtom(), G4LivermorePhotoElectricModel::ComputeCrossSectionPerAtom(), G4IonParametrisedLossModel::ComputeLossForStep(), G4DNABornExcitationModel2::GetPartialCrossSection(), G4DNABornExcitationModel2::Initialise(), G4DNABornExcitationModel2::RandomSelect(), G4SeltzerBergerModel::SampleEnergyTransfer(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), and G4LivermorePhotoElectricModel::SampleSecondaries().
Field Documentation
anglModel
G4VEmAngularDistribution* G4VEmModel::anglModel private
Definition at line 400 of file G4VEmModel.hh.
Referenced by GetAngularDistribution(), SetAngularDistribution(), and ~G4VEmModel().
elmSelectors
std::vector<G4EmElementSelector*>* G4VEmModel::elmSelectors private
Definition at line 421 of file G4VEmModel.hh.
Referenced by G4VEmModel(), GetElementSelectors(), InitialiseElementSelectors(), SelectRandomAtom(), SetElementSelectors(), and ~G4VEmModel().
eMaxActive
G4double G4VEmModel::eMaxActive private
Definition at line 408 of file G4VEmModel.hh.
Referenced by HighEnergyActivationLimit(), IsActive(), and SetActivationHighEnergyLimit().
eMinActive
G4double G4VEmModel::eMinActive private
Definition at line 407 of file G4VEmModel.hh.
Referenced by IsActive(), LowEnergyActivationLimit(), and SetActivationLowEnergyLimit().
fCurrentCouple
const G4MaterialCutsCouple* G4VEmModel::fCurrentCouple private
Definition at line 439 of file G4VEmModel.hh.
Referenced by CurrentCouple(), InitialiseElementSelectors(), SelectRandomAtom(), and SetCurrentCouple().
fCurrentElement
const G4Element* G4VEmModel::fCurrentElement private
Definition at line 440 of file G4VEmModel.hh.
Referenced by GetCurrentElement(), SelectRandomAtom(), SelectRandomAtomNumber(), and SetCurrentElement().
fCurrentIsotope
const G4Isotope* G4VEmModel::fCurrentIsotope private
Definition at line 441 of file G4VEmModel.hh.
Referenced by GetCurrentIsotope(), SelectIsotopeNumber(), SelectRandomAtom(), and SetCurrentElement().
fElementData
G4ElementData* G4VEmModel::fElementData protected
Definition at line 426 of file G4VEmModel.hh.
Referenced by G4MuPairProductionModel::FindScaledEnergy(), GetElementData(), G4MuPairProductionModel::Initialise(), G4MuPairProductionModel::InitialiseLocal(), G4MuPairProductionModel::MakeSamplingTables(), and ~G4VEmModel().
fEmManager
G4LossTableManager* G4VEmModel::fEmManager private
Definition at line 422 of file G4VEmModel.hh.
Referenced by G4VEmModel(), and ~G4VEmModel().
flagDeexcitation
G4bool G4VEmModel::flagDeexcitation private
Definition at line 412 of file G4VEmModel.hh.
Referenced by DeexcitationFlag(), and SetDeexcitationFlag().
flagForceBuildTable
G4bool G4VEmModel::flagForceBuildTable private
Definition at line 413 of file G4VEmModel.hh.
Referenced by ForceBuildTableFlag(), and SetForceBuildTable().
flucModel
G4VEmFluctuationModel* G4VEmModel::flucModel private
Definition at line 399 of file G4VEmModel.hh.
Referenced by GetModelOfFluctuations(), and SetParticleChange().
fTripletModel
G4VEmModel* G4VEmModel::fTripletModel private
Definition at line 442 of file G4VEmModel.hh.
Referenced by GetParticleChangeForGamma(), GetParticleChangeForLoss(), GetTripletModel(), and SetTripletModel().
highLimit
G4double G4VEmModel::highLimit private
Definition at line 406 of file G4VEmModel.hh.
Referenced by HighEnergyLimit(), InitialiseElementSelectors(), and SetHighEnergyLimit().
idxTable
size_t G4VEmModel::idxTable protected
Definition at line 431 of file G4VEmModel.hh.
Referenced by G4VEmModel(), G4VMscModel::GetParticleChangeForMSC(), and G4VMscModel::GetTransportMeanFreePath().
inveplus
G4double G4VEmModel::inveplus protected
Definition at line 433 of file G4VEmModel.hh.
Referenced by GetChargeSquareRatio(), G4VMscModel::GetDEDX(), G4VMscModel::GetEnergy(), G4VMscModel::GetRange(), G4LindhardSorensenIonModel::SetupParameters(), and G4BetheBlochModel::SetupParameters().
isLocked
G4bool G4VEmModel::isLocked private
Definition at line 419 of file G4VEmModel.hh.
Referenced by G4VEmModel(), IsLocked(), SetLocked(), and SetPolarAngleLimit().
isMaster
G4bool G4VEmModel::isMaster private
Definition at line 414 of file G4VEmModel.hh.
Referenced by IsMaster(), SetMasterThread(), and ~G4VEmModel().
localElmSelectors
G4bool G4VEmModel::localElmSelectors private
Definition at line 417 of file G4VEmModel.hh.
Referenced by G4VEmModel(), SetElementSelectors(), and ~G4VEmModel().
localTable
G4bool G4VEmModel::localTable private
Definition at line 416 of file G4VEmModel.hh.
Referenced by G4VEmModel(), SetCrossSectionTable(), and ~G4VEmModel().
lossFlucFlag
G4bool G4VEmModel::lossFlucFlag protected
Definition at line 432 of file G4VEmModel.hh.
Referenced by G4ICRU49NuclearStoppingModel::NuclearStoppingPower(), and SetFluctuationFlag().
lowLimit
G4double G4VEmModel::lowLimit private
Definition at line 405 of file G4VEmModel.hh.
Referenced by InitialiseElementSelectors(), LowEnergyLimit(), and SetLowEnergyLimit().
name
const G4String G4VEmModel::name private
Definition at line 401 of file G4VEmModel.hh.
Referenced by GetName().
nsec
G4int G4VEmModel::nsec private
Definition at line 444 of file G4VEmModel.hh.
Referenced by CrossSectionPerVolume(), and G4VEmModel().
nSelectors
G4int G4VEmModel::nSelectors private
Definition at line 420 of file G4VEmModel.hh.
Referenced by G4VEmModel(), InitialiseElementSelectors(), SelectRandomAtom(), SetElementSelectors(), and ~G4VEmModel().
polarAngleLimit
G4double G4VEmModel::polarAngleLimit private
Definition at line 409 of file G4VEmModel.hh.
Referenced by PolarAngleLimit(), and SetPolarAngleLimit().
pParticleChange
G4VParticleChange* G4VEmModel::pParticleChange protected
Definition at line 427 of file G4VEmModel.hh.
Referenced by GetParticleChangeForGamma(), GetParticleChangeForLoss(), G4VMscModel::GetParticleChangeForMSC(), G4EmMultiModel::Initialise(), and SetParticleChange().
secondaryThreshold
G4double G4VEmModel::secondaryThreshold private
Definition at line 410 of file G4VEmModel.hh.
Referenced by SecondaryThreshold(), and SetSecondaryThreshold().
theDensityFactor
const std::vector<G4double>* G4VEmModel::theDensityFactor protected
Definition at line 429 of file G4VEmModel.hh.
Referenced by G4VMscModel::GetParticleChangeForMSC().
theDensityIdx
const std::vector<G4int>* G4VEmModel::theDensityIdx protected
Definition at line 430 of file G4VEmModel.hh.
Referenced by G4VMscModel::GetParticleChangeForMSC().
theLPMflag
G4bool G4VEmModel::theLPMflag private
Definition at line 411 of file G4VEmModel.hh.
Referenced by LPMFlag(), and SetLPMFlag().
useAngularGenerator
G4bool G4VEmModel::useAngularGenerator private
Definition at line 418 of file G4VEmModel.hh.
Referenced by G4VEmModel(), SetAngularGeneratorFlag(), and UseAngularGeneratorFlag().
xsec
std::vector<G4double> G4VEmModel::xsec private
Definition at line 445 of file G4VEmModel.hh.
Referenced by CrossSectionPerVolume(), G4VEmModel(), and SelectRandomAtom().
xSectionTable
G4PhysicsTable* G4VEmModel::xSectionTable protected
Definition at line 428 of file G4VEmModel.hh.
Referenced by GetCrossSectionTable(), G4VMscModel::GetParticleChangeForMSC(), G4VMscModel::GetTransportMeanFreePath(), SetCrossSectionTable(), and ~G4VEmModel().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/utils/include/G4VEmModel.hh
source/processes/electromagnetic/utils/src/G4VEmModel.cc