Geant4: G4VPVDivisionFactory Class Reference
G4VPVDivisionFactory Class Reference abstract
#include <G4VPVDivisionFactory.hh>
Public Member Functions
virtual ~G4VPVDivisionFactory ()
virtual G4VPhysicalVolume * CreatePVDivision (const G4String &pName, G4LogicalVolume *pLogical, G4LogicalVolume *pMother, const EAxis pAxis, const G4int nReplicas, const G4double width, const G4double offset)=0
virtual G4VPhysicalVolume * CreatePVDivision (const G4String &pName, G4LogicalVolume *pLogical, G4LogicalVolume *pMotherLogical, const EAxis pAxis, const G4int nReplicas, const G4double offset)=0
virtual G4VPhysicalVolume * CreatePVDivision (const G4String &pName, G4LogicalVolume *pLogical, G4LogicalVolume *pMotherLogical, const EAxis pAxis, const G4double width, const G4double offset)=0
virtual G4VPhysicalVolume * CreatePVDivision (const G4String &pName, G4LogicalVolume *pLogical, G4LogicalVolume *pMotherLogical, const G4VPVParameterisation *param)=0
virtual G4bool IsPVDivision (const G4VPhysicalVolume *pv) const =0
Static Public Member Functions
static G4VPVDivisionFactory * Instance ()
Protected Member Functions
G4VPVDivisionFactory ()
Static Protected Attributes
static G4ThreadLocal G4VPVDivisionFactory * fgInstance = 0
Detailed Description
Definition at line 47 of file G4VPVDivisionFactory.hh.
Constructor & Destructor Documentation
~G4VPVDivisionFactory()
G4VPVDivisionFactory::~G4VPVDivisionFactory () virtual
Definition at line 58 of file G4VPVDivisionFactory.cc.
G4VPVDivisionFactory()
G4VPVDivisionFactory::G4VPVDivisionFactory () protected
Definition at line 49 of file G4VPVDivisionFactory.cc.
Member Function Documentation
CreatePVDivision() [1/4]
virtual G4VPhysicalVolume* G4VPVDivisionFactory::CreatePVDivision (const G4String & pName, G4LogicalVolume * pLogical, G4LogicalVolume * pMother, const EAxis pAxis, const G4int nReplicas, const G4double width, const G4double offset) pure virtual
Implemented in G4PVDivisionFactory.
Referenced by G4ReflectionFactory::Divide(), and G4ReflectionFactory::ReflectPVDivision().
CreatePVDivision() [2/4]
virtual G4VPhysicalVolume* G4VPVDivisionFactory::CreatePVDivision (const G4String & pName, G4LogicalVolume * pLogical, G4LogicalVolume * pMotherLogical, const EAxis pAxis, const G4double width, const G4double offset) pure virtual
Implemented in G4PVDivisionFactory.
CreatePVDivision() [3/4]
virtual G4VPhysicalVolume* G4VPVDivisionFactory::CreatePVDivision (const G4String & pName, G4LogicalVolume * pLogical, G4LogicalVolume * pMotherLogical, const EAxis pAxis, const G4int nReplicas, const G4double offset) pure virtual
Implemented in G4PVDivisionFactory.
CreatePVDivision() [4/4]
virtual G4VPhysicalVolume* G4VPVDivisionFactory::CreatePVDivision (const G4String & pName, G4LogicalVolume * pLogical, G4LogicalVolume * pMotherLogical, const G4VPVParameterisation * param) pure virtual
Implemented in G4PVDivisionFactory.
Instance()
G4VPVDivisionFactory * G4VPVDivisionFactory::Instance (void) static
Definition at line 39 of file G4VPVDivisionFactory.cc.
Referenced by G4ReflectionFactory::GetPVDivisionFactory(), and G4ReflectionFactory::ReflectDaughters().
IsPVDivision()
virtual G4bool G4VPVDivisionFactory::IsPVDivision (const G4VPhysicalVolume * pv) const pure virtual
Implemented in G4PVDivisionFactory.
Field Documentation
fgInstance
G4ThreadLocal G4VPVDivisionFactory * G4VPVDivisionFactory::fgInstance = 0 static protected
Definition at line 99 of file G4VPVDivisionFactory.hh.
Referenced by G4PVDivisionFactory::GetInstance(), and Instance().
The documentation for this class was generated from the following files:
source/geometry/management/include/G4VPVDivisionFactory.hh
source/geometry/management/src/G4VPVDivisionFactory.cc