Geant4: G4RootAnalysisManager Class Reference
G4RootAnalysisManager Class Reference
#include <G4RootAnalysisManager.hh>
Public Member Functions
G4RootAnalysisManager (G4bool isMaster=true)
virtual ~G4RootAnalysisManager ()
tools::wroot::ntuple * GetNtuple () const
tools::wroot::ntuple * GetNtuple (G4int ntupleId) const
std::vector< tools::wroot::ntuple * >::iterator BeginNtuple ()
std::vector< tools::wroot::ntuple * >::iterator EndNtuple ()
std::vector< tools::wroot::ntuple * >::const_iterator BeginConstNtuple () const
std::vector< tools::wroot::ntuple * >::const_iterator EndConstNtuple () const
void SetNtupleMerging (G4bool mergeNtuples, G4int nofReducedNtupleFiles=0, G4bool rowWise=true, unsigned int basketSize=fgkDefaultBasketSize)
void SetNtupleRowWise (G4bool rowWise)
Public Member Functions inherited from G4ToolsAnalysisManager
G4ToolsAnalysisManager (const G4String &type, G4bool isMaster=true)
virtual ~G4ToolsAnalysisManager ()
tools::histo::h1d * GetH1 (G4int id, G4bool warn=true, G4bool onlyIfActive=true) const
tools::histo::h2d * GetH2 (G4int id, G4bool warn=true, G4bool onlyIfActive=true) const
tools::histo::h3d * GetH3 (G4int id, G4bool warn=true, G4bool onlyIfActive=true) const
tools::histo::p1d * GetP1 (G4int id, G4bool warn=true, G4bool onlyIfActive=true) const
tools::histo::p2d * GetP2 (G4int id, G4bool warn=true, G4bool onlyIfActive=true) const
std::vector< tools::histo::h1d * >::iterator BeginH1 ()
std::vector< tools::histo::h1d * >::iterator EndH1 ()
std::vector< tools::histo::h1d * >::const_iterator BeginConstH1 () const
std::vector< tools::histo::h1d * >::const_iterator EndConstH1 () const
std::vector< tools::histo::h2d * >::iterator BeginH2 ()
std::vector< tools::histo::h2d * >::iterator EndH2 ()
std::vector< tools::histo::h2d * >::const_iterator BeginConstH2 () const
std::vector< tools::histo::h2d * >::const_iterator EndConstH2 () const
std::vector< tools::histo::h3d * >::iterator BeginH3 ()
std::vector< tools::histo::h3d * >::iterator EndH3 ()
std::vector< tools::histo::h3d * >::const_iterator BeginConstH3 () const
std::vector< tools::histo::h3d * >::const_iterator EndConstH3 () const
std::vector< tools::histo::p1d * >::iterator BeginP1 ()
std::vector< tools::histo::p1d * >::iterator EndP1 ()
std::vector< tools::histo::p1d * >::const_iterator BeginConstP1 () const
std::vector< tools::histo::p1d * >::const_iterator EndConstP1 () const
std::vector< tools::histo::p2d * >::iterator BeginP2 ()
std::vector< tools::histo::p2d * >::iterator EndP2 ()
std::vector< tools::histo::p2d * >::const_iterator BeginConstP2 () const
std::vector< tools::histo::p2d * >::const_iterator EndConstP2 () const
std::vector< tools::wroot::ntuple * >::iterator BeginNtuple ()
std::vector< tools::wroot::ntuple * >::iterator EndNtuple ()
std::vector< tools::wroot::ntuple * >::const_iterator BeginConstNtuple () const
std::vector< tools::wroot::ntuple * >::const_iterator EndConstNtuple () const
Public Member Functions inherited from G4VAnalysisManager
G4VAnalysisManager (const G4String &type, G4bool isMaster)
virtual ~G4VAnalysisManager ()
G4bool OpenFile (const G4String &fileName="")
G4bool Write ()
G4bool CloseFile (G4bool reset=true)
G4bool Merge (tools::histo::hmpi *hmpi)
G4bool Plot ()
G4bool IsOpenFile () const
G4bool SetFileName (const G4String &fileName)
G4bool SetHistoDirectoryName (const G4String &dirName)
G4bool SetNtupleDirectoryName (const G4String &dirName)
void SetCompressionLevel (G4int level)
G4String GetFileName () const
G4String GetHistoDirectoryName () const
G4String GetNtupleDirectoryName () const
G4int GetCompressionLevel () const
G4int CreateH1 (const G4String &name, const G4String &title, G4int nbins, G4double xmin, G4double xmax, const G4String &unitName="none", const G4String &fcnName="none", const G4String &binSchemeName="linear")
G4int CreateH1 (const G4String &name, const G4String &title, const std::vector< G4double > &edges, const G4String &unitName="none", const G4String &fcnName="none")
G4int CreateH2 (const G4String &name, const G4String &title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear")
G4int CreateH2 (const G4String &name, const G4String &title, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none")
G4int CreateH3 (const G4String &name, const G4String &title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4int nzbins, G4double zmin, G4double zmax, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear", const G4String &zbinSchemeName="linear")
G4int CreateH3 (const G4String &name, const G4String &title, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, const std::vector< G4double > &zedges, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none")
G4bool SetH1 (G4int id, G4int nbins, G4double xmin, G4double xmax, const G4String &unitName="none", const G4String &fcnName="none", const G4String &binSchemeName="linear")
G4bool SetH1 (G4int id, const std::vector< G4double > &edges, const G4String &unitName="none", const G4String &fcnName="none")
G4bool SetH2 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear")
G4bool SetH2 (G4int id, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none")
G4bool SetH3 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nzbins, G4double zmin, G4double zmax, G4int nybins, G4double ymin, G4double ymax, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear", const G4String &zbinSchemeName="linear")
G4bool SetH3 (G4int id, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, const std::vector< G4double > &zedges, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none")
G4bool ScaleH1 (G4int id, G4double factor)
G4bool ScaleH2 (G4int id, G4double factor)
G4bool ScaleH3 (G4int id, G4double factor)
G4int CreateP1 (const G4String &name, const G4String &title, G4int nbins, G4double xmin, G4double xmax, G4double ymin=0, G4double ymax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &xbinSchemeName="linear")
G4int CreateP1 (const G4String &name, const G4String &title, const std::vector< G4double > &edges, G4double ymin=0, G4double ymax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none")
G4int CreateP2 (const G4String &name, const G4String &title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4double zmin=0, G4double zmax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear")
G4int CreateP2 (const G4String &name, const G4String &title, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, G4double zmin=0, G4double zmax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none")
G4bool SetP1 (G4int id, G4int nbins, G4double xmin, G4double xmax, G4double ymin=0, G4double ymax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &xbinSchemeName="linear")
G4bool SetP1 (G4int id, const std::vector< G4double > &edges, G4double ymin=0, G4double ymax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none")
G4bool SetP2 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4double zmin=0, G4double zmax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear")
G4bool SetP2 (G4int id, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, G4double zmin=0, G4double zmax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none")
G4bool ScaleP1 (G4int id, G4double factor)
G4bool ScaleP2 (G4int id, G4double factor)
G4int CreateNtuple (const G4String &name, const G4String &title)
G4int CreateNtupleIColumn (const G4String &name)
G4int CreateNtupleFColumn (const G4String &name)
G4int CreateNtupleDColumn (const G4String &name)
G4int CreateNtupleSColumn (const G4String &name)
G4int CreateNtupleIColumn (const G4String &name, std::vector< int > &vector)
G4int CreateNtupleFColumn (const G4String &name, std::vector< float > &vector)
G4int CreateNtupleDColumn (const G4String &name, std::vector< double > &vector)
void FinishNtuple ()
G4int CreateNtupleIColumn (G4int ntupleId, const G4String &name)
G4int CreateNtupleFColumn (G4int ntupleId, const G4String &name)
G4int CreateNtupleDColumn (G4int ntupleId, const G4String &name)
G4int CreateNtupleSColumn (G4int ntupleId, const G4String &name)
G4int CreateNtupleIColumn (G4int ntupleId, const G4String &name, std::vector< int > &vector)
G4int CreateNtupleFColumn (G4int ntupleId, const G4String &name, std::vector< float > &vector)
G4int CreateNtupleDColumn (G4int ntupleId, const G4String &name, std::vector< double > &vector)
void FinishNtuple (G4int ntupleId)
G4bool SetFirstHistoId (G4int firstId)
G4bool SetFirstH1Id (G4int firstId)
G4bool SetFirstH2Id (G4int firstId)
G4bool SetFirstH3Id (G4int firstId)
G4bool SetFirstProfileId (G4int firstId)
G4bool SetFirstP1Id (G4int firstId)
G4bool SetFirstP2Id (G4int firstId)
G4bool SetFirstNtupleId (G4int firstId)
G4bool SetFirstNtupleColumnId (G4int firstId)
G4bool FillH1 (G4int id, G4double value, G4double weight=1.0)
G4bool FillH2 (G4int id, G4double xvalue, G4double yvalue, G4double weight=1.0)
G4bool FillH3 (G4int id, G4double xvalue, G4double yvalue, G4double zvalue, G4double weight=1.0)
G4bool FillP1 (G4int id, G4double xvalue, G4double yvalue, G4double weight=1.0)
G4bool FillP2 (G4int id, G4double xvalue, G4double yvalue, G4double zvalue, G4double weight=1.0)
G4bool FillNtupleIColumn (G4int id, G4int value)
G4bool FillNtupleFColumn (G4int id, G4float value)
G4bool FillNtupleDColumn (G4int id, G4double value)
G4bool FillNtupleSColumn (G4int id, const G4String &value)
G4bool AddNtupleRow ()
G4bool FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value)
G4bool FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value)
G4bool FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value)
G4bool FillNtupleSColumn (G4int ntupleId, G4int id, const G4String &value)
G4bool AddNtupleRow (G4int ntupleId)
void SetActivation (G4bool activation)
G4bool GetActivation () const
G4bool IsActive () const
G4bool IsAscii () const
G4bool IsPlotting () const
G4int GetFirstH1Id () const
G4int GetFirstH2Id () const
G4int GetFirstH3Id () const
G4int GetFirstP1Id () const
G4int GetFirstP2Id () const
G4int GetFirstNtupleId () const
G4int GetFirstNtupleColumnId () const
G4int GetNofH1s () const
G4int GetNofH2s () const
G4int GetNofH3s () const
G4int GetNofP1s () const
G4int GetNofP2s () const
G4int GetNofNtuples () const
G4int GetH1Id (const G4String &name, G4bool warn=true) const
G4int GetH2Id (const G4String &name, G4bool warn=true) const
G4int GetH3Id (const G4String &name, G4bool warn=true) const
G4int GetP1Id (const G4String &name, G4bool warn=true) const
G4int GetP2Id (const G4String &name, G4bool warn=true) const
void SetH1Activation (G4bool activation)
void SetH1Activation (G4int id, G4bool activation)
void SetH1Ascii (G4int id, G4bool ascii)
void SetH1Plotting (G4int id, G4bool plotting)
void SetH2Activation (G4bool activation)
void SetH2Activation (G4int id, G4bool activation)
void SetH2Ascii (G4int id, G4bool ascii)
void SetH2Plotting (G4int id, G4bool plotting)
void SetH3Activation (G4bool activation)
void SetH3Activation (G4int id, G4bool activation)
void SetH3Ascii (G4int id, G4bool ascii)
void SetH3Plotting (G4int id, G4bool plotting)
void SetP1Activation (G4bool activation)
void SetP1Activation (G4int id, G4bool activation)
void SetP1Ascii (G4int id, G4bool ascii)
void SetP1Plotting (G4int id, G4bool plotting)
void SetP2Activation (G4bool activation)
void SetP2Activation (G4int id, G4bool activation)
void SetP2Ascii (G4int id, G4bool ascii)
void SetP2Plotting (G4int id, G4bool plotting)
void SetNtupleActivation (G4bool activation)
void SetNtupleActivation (G4int id, G4bool activation)
G4int GetH1Nbins (G4int id) const
G4double GetH1Xmin (G4int id) const
G4double GetH1Xmax (G4int id) const
G4double GetH1Width (G4int id) const
G4int GetH2Nxbins (G4int id) const
G4double GetH2Xmin (G4int id) const
G4double GetH2Xmax (G4int id) const
G4double GetH2XWidth (G4int id) const
G4int GetH2Nybins (G4int id) const
G4double GetH2Ymin (G4int id) const
G4double GetH2Ymax (G4int id) const
G4double GetH2YWidth (G4int id) const
G4int GetH3Nxbins (G4int id) const
G4double GetH3Xmin (G4int id) const
G4double GetH3Xmax (G4int id) const
G4double GetH3XWidth (G4int id) const
G4int GetH3Nybins (G4int id) const
G4double GetH3Ymin (G4int id) const
G4double GetH3Ymax (G4int id) const
G4double GetH3YWidth (G4int id) const
G4int GetH3Nzbins (G4int id) const
G4double GetH3Zmin (G4int id) const
G4double GetH3Zmax (G4int id) const
G4double GetH3ZWidth (G4int id) const
G4int GetP1Nbins (G4int id) const
G4double GetP1Xmin (G4int id) const
G4double GetP1Xmax (G4int id) const
G4double GetP1XWidth (G4int id) const
G4double GetP1Ymin (G4int id) const
G4double GetP1Ymax (G4int id) const
G4int GetP2Nxbins (G4int id) const
G4double GetP2Xmin (G4int id) const
G4double GetP2Xmax (G4int id) const
G4double GetP2XWidth (G4int id) const
G4int GetP2Nybins (G4int id) const
G4double GetP2Ymin (G4int id) const
G4double GetP2Ymax (G4int id) const
G4double GetP2YWidth (G4int id) const
G4double GetP2Zmin (G4int id) const
G4double GetP2Zmax (G4int id) const
G4String GetH1Name (G4int id) const
G4double GetH1Unit (G4int id) const
G4bool GetH1Activation (G4int id) const
G4bool GetH1Ascii (G4int id) const
G4bool GetH1Plotting (G4int id) const
G4String GetH2Name (G4int id) const
G4double GetH2XUnit (G4int id) const
G4double GetH2YUnit (G4int id) const
G4bool GetH2Activation (G4int id) const
G4bool GetH2Ascii (G4int id) const
G4bool GetH2Plotting (G4int id) const
G4String GetH3Name (G4int id) const
G4double GetH3XUnit (G4int id) const
G4double GetH3YUnit (G4int id) const
G4double GetH3ZUnit (G4int id) const
G4bool GetH3Activation (G4int id) const
G4bool GetH3Ascii (G4int id) const
G4bool GetH3Plotting (G4int id) const
G4String GetP1Name (G4int id) const
G4double GetP1XUnit (G4int id) const
G4double GetP1YUnit (G4int id) const
G4bool GetP1Activation (G4int id) const
G4bool GetP1Ascii (G4int id) const
G4bool GetP1Plotting (G4int id) const
G4String GetP2Name (G4int id) const
G4double GetP2XUnit (G4int id) const
G4double GetP2YUnit (G4int id) const
G4double GetP2ZUnit (G4int id) const
G4bool GetP2Activation (G4int id) const
G4bool GetP2Ascii (G4int id) const
G4bool GetP2Plotting (G4int id) const
G4bool GetNtupleActivation (G4int id) const
G4bool SetH1Title (G4int id, const G4String &title)
G4bool SetH1XAxisTitle (G4int id, const G4String &title)
G4bool SetH1YAxisTitle (G4int id, const G4String &title)
G4bool SetH2Title (G4int id, const G4String &title)
G4bool SetH2XAxisTitle (G4int id, const G4String &title)
G4bool SetH2YAxisTitle (G4int id, const G4String &title)
G4bool SetH2ZAxisTitle (G4int id, const G4String &title)
G4bool SetH3Title (G4int id, const G4String &title)
G4bool SetH3XAxisTitle (G4int id, const G4String &title)
G4bool SetH3YAxisTitle (G4int id, const G4String &title)
G4bool SetH3ZAxisTitle (G4int id, const G4String &title)
G4bool SetP1Title (G4int id, const G4String &title)
G4bool SetP1XAxisTitle (G4int id, const G4String &title)
G4bool SetP1YAxisTitle (G4int id, const G4String &title)
G4bool SetP2Title (G4int id, const G4String &title)
G4bool SetP2XAxisTitle (G4int id, const G4String &title)
G4bool SetP2YAxisTitle (G4int id, const G4String &title)
G4bool SetP2ZAxisTitle (G4int id, const G4String &title)
G4String GetH1Title (G4int id) const
G4String GetH1XAxisTitle (G4int id) const
G4String GetH1YAxisTitle (G4int id) const
G4String GetH2Title (G4int id) const
G4String GetH2XAxisTitle (G4int id) const
G4String GetH2YAxisTitle (G4int id) const
G4String GetH2ZAxisTitle (G4int id) const
G4String GetH3Title (G4int id) const
G4String GetH3XAxisTitle (G4int id) const
G4String GetH3YAxisTitle (G4int id) const
G4String GetH3ZAxisTitle (G4int id) const
G4String GetP1Title (G4int id) const
G4String GetP1XAxisTitle (G4int id) const
G4String GetP1YAxisTitle (G4int id) const
G4String GetP1ZAxisTitle (G4int id) const
G4String GetP2Title (G4int id) const
G4String GetP2XAxisTitle (G4int id) const
G4String GetP2YAxisTitle (G4int id) const
G4String GetP2ZAxisTitle (G4int id) const
void SetVerboseLevel (G4int verboseLevel)
G4int GetVerboseLevel () const
G4String GetType () const
G4String GetFileType () const
Static Public Member Functions
static G4RootAnalysisManager * Instance ()
static G4bool IsInstance ()
Protected Member Functions
virtual G4bool OpenFileImpl (const G4String &fileName) override
virtual G4bool WriteImpl () final
virtual G4bool CloseFileImpl (G4bool reset) override
virtual G4bool IsOpenFileImpl () const final
virtual G4bool WriteNtuple ()
virtual G4bool Reset ()
Protected Member Functions inherited from G4ToolsAnalysisManager
virtual G4bool PlotImpl () final
virtual G4bool MergeImpl (tools::histo::hmpi *hmpi) final
G4bool Reset ()
Protected Member Functions inherited from G4VAnalysisManager
void SetH1Manager (G4VH1Manager *h1Manager)
void SetH2Manager (G4VH2Manager *h2Manager)
void SetH3Manager (G4VH3Manager *h3Manager)
void SetP1Manager (G4VP1Manager *p1Manager)
void SetP2Manager (G4VP2Manager *p2Manager)
void SetNtupleManager (G4VNtupleManager *ntupleManager)
void SetFileManager (std::shared_ptr< G4VFileManager > fileManager)
void SetPlotManager (std::shared_ptr< G4PlotManager > plotManager)
G4bool WriteAscii (const G4String &fileName)
Private Member Functions
void SetNtupleMergingMode (G4bool mergeNtuples, G4int nofNtupleFiles, G4bool rowWise)
void ClearNtupleManagers ()
void CreateNtupleManagers ()
G4int GetNtupleFileNumber ()
G4bool ResetNtuple ()
template<typename T >
G4bool WriteT (const std::vector< T * > &htVector, const std::vector< G4HnInformation * > &hnVector, tools::wroot::directory *directory, const G4String &hnType)
G4bool WriteH1 ()
G4bool WriteH2 ()
G4bool WriteH3 ()
G4bool WriteP1 ()
G4bool WriteP2 ()
Private Attributes
G4int fNofNtupleFiles
G4bool fNtupleRowWise
G4NtupleMergeMode fNtupleMergeMode
G4RootNtupleManager * fNtupleManager
G4RootPNtupleManager * fSlaveNtupleManager
std::shared_ptr< G4RootFileManager > fFileManager
Static Private Attributes
static constexpr unsigned int fgkDefaultBasketSize = 32000
static G4RootAnalysisManager * fgMasterInstance = nullptr
static G4ThreadLocal G4RootAnalysisManager * fgInstance = nullptr
Friends
class G4RootMpiAnalysisManager
Additional Inherited Members
Protected Attributes inherited from G4ToolsAnalysisManager
G4H1ToolsManager * fH1Manager
G4H2ToolsManager * fH2Manager
G4H3ToolsManager * fH3Manager
G4P1ToolsManager * fP1Manager
G4P2ToolsManager * fP2Manager
Protected Attributes inherited from G4VAnalysisManager
G4AnalysisManagerState fState
std::shared_ptr< G4VFileManager > fVFileManager
std::shared_ptr< G4PlotManager > fPlotManager
Detailed Description
Definition at line 60 of file G4RootAnalysisManager.hh.
Constructor & Destructor Documentation
G4RootAnalysisManager()
G4RootAnalysisManager::G4RootAnalysisManager (G4bool isMaster = true) explicit
Definition at line 79 of file G4RootAnalysisManager.cc.
Referenced by Instance().
~G4RootAnalysisManager()
G4RootAnalysisManager::~G4RootAnalysisManager () virtual
Definition at line 116 of file G4RootAnalysisManager.cc.
Member Function Documentation
BeginConstNtuple()
std::vector<tools::wroot::ntuple*>::const_iterator G4RootAnalysisManager::BeginConstNtuple () const
BeginNtuple()
std::vector<tools::wroot::ntuple*>::iterator G4RootAnalysisManager::BeginNtuple ()
ClearNtupleManagers()
void G4RootAnalysisManager::ClearNtupleManagers () private
Definition at line 229 of file G4RootAnalysisManager.cc.
Referenced by G4RootMpiAnalysisManager::SetMpiNtupleMerging(), SetNtupleMerging(), and SetNtupleRowWise().
CloseFileImpl()
G4bool G4RootAnalysisManager::CloseFileImpl (G4bool reset) override protected virtual
Implements G4VAnalysisManager.
Reimplemented in G4RootMpiAnalysisManager.
Definition at line 622 of file G4RootAnalysisManager.cc.
Referenced by G4RootMpiAnalysisManager::CloseFileImpl().
CreateNtupleManagers()
void G4RootAnalysisManager::CreateNtupleManagers () private
Definition at line 253 of file G4RootAnalysisManager.cc.
Referenced by G4RootAnalysisManager(), SetNtupleMerging(), and SetNtupleRowWise().
EndConstNtuple()
std::vector<tools::wroot::ntuple*>::const_iterator G4RootAnalysisManager::EndConstNtuple () const
EndNtuple()
std::vector<tools::wroot::ntuple*>::iterator G4RootAnalysisManager::EndNtuple ()
GetNtuple() [1/2]
tools::wroot::ntuple* G4RootAnalysisManager::GetNtuple () const
GetNtuple() [2/2]
tools::wroot::ntuple* G4RootAnalysisManager::GetNtuple (G4int ntupleId) const
GetNtupleFileNumber()
G4int G4RootAnalysisManager::GetNtupleFileNumber () private
Definition at line 295 of file G4RootAnalysisManager.cc.
Referenced by CreateNtupleManagers().
Instance()
G4RootAnalysisManager * G4RootAnalysisManager::Instance (void) static
Definition at line 62 of file G4RootAnalysisManager.cc.
Referenced by Histo::Book(), G4ScoreNtupleWriter::CreateAnalysisManager(), ScoreSpecies::OutputAndClear(), and Histo::Save().
IsInstance()
G4bool G4RootAnalysisManager::IsInstance () static
Definition at line 73 of file G4RootAnalysisManager.cc.
Referenced by G4ScoreNtupleWriter::CreateAnalysisManager().
IsOpenFileImpl()
virtual G4bool G4RootAnalysisManager::IsOpenFileImpl () const final protected virtual
Implements G4VAnalysisManager.
OpenFileImpl()
G4bool G4RootAnalysisManager::OpenFileImpl (const G4String & fileName) override protected virtual
Implements G4VAnalysisManager.
Reimplemented in G4RootMpiAnalysisManager.
Definition at line 506 of file G4RootAnalysisManager.cc.
Referenced by G4RootMpiAnalysisManager::OpenFileImpl().
Reset()
G4bool G4RootAnalysisManager::Reset () protected virtual
Reimplemented in G4RootMpiAnalysisManager.
Definition at line 486 of file G4RootAnalysisManager.cc.
Referenced by CloseFileImpl(), and G4RootMpiAnalysisManager::Reset().
ResetNtuple()
G4bool G4RootAnalysisManager::ResetNtuple () private
Definition at line 470 of file G4RootAnalysisManager.cc.
Referenced by CloseFileImpl(), and Reset().
SetNtupleMerging()
void G4RootAnalysisManager::SetNtupleMerging (G4bool mergeNtuples, G4int nofReducedNtupleFiles = 0, G4bool rowWise = true, unsigned int basketSize = fgkDefaultBasketSize)
Definition at line 684 of file G4RootAnalysisManager.cc.
SetNtupleMergingMode()
void G4RootAnalysisManager::SetNtupleMergingMode (G4bool mergeNtuples, G4int nofNtupleFiles, G4bool rowWise) private
Definition at line 127 of file G4RootAnalysisManager.cc.
Referenced by G4RootAnalysisManager(), and SetNtupleMerging().
SetNtupleRowWise()
void G4RootAnalysisManager::SetNtupleRowWise (G4bool rowWise)
Definition at line 704 of file G4RootAnalysisManager.cc.
WriteH1()
G4bool G4RootAnalysisManager::WriteH1 () private
Definition at line 311 of file G4RootAnalysisManager.cc.
Referenced by WriteImpl().
WriteH2()
G4bool G4RootAnalysisManager::WriteH2 () private
Definition at line 336 of file G4RootAnalysisManager.cc.
Referenced by WriteImpl().
WriteH3()
G4bool G4RootAnalysisManager::WriteH3 () private
Definition at line 361 of file G4RootAnalysisManager.cc.
Referenced by WriteImpl().
WriteImpl()
G4bool G4RootAnalysisManager::WriteImpl () final protected virtual
Implements G4VAnalysisManager.
Definition at line 564 of file G4RootAnalysisManager.cc.
WriteNtuple()
G4bool G4RootAnalysisManager::WriteNtuple () protected virtual
Reimplemented in G4RootMpiAnalysisManager.
Definition at line 436 of file G4RootAnalysisManager.cc.
Referenced by WriteImpl(), and G4RootMpiAnalysisManager::WriteNtuple().
WriteP1()
G4bool G4RootAnalysisManager::WriteP1 () private
Definition at line 386 of file G4RootAnalysisManager.cc.
Referenced by WriteImpl().
WriteP2()
G4bool G4RootAnalysisManager::WriteP2 () private
Definition at line 411 of file G4RootAnalysisManager.cc.
Referenced by WriteImpl().
WriteT()
template<typename T > G4bool G4RootAnalysisManager::WriteT (const std::vector< T * > & htVector, const std::vector< G4HnInformation * > & hnVector, tools::wroot::directory * directory, const G4String & hnType) private
Referenced by WriteH1(), WriteH2(), WriteH3(), WriteP1(), and WriteP2().
Friends And Related Function Documentation
G4RootMpiAnalysisManager
friend class G4RootMpiAnalysisManager friend
Definition at line 62 of file G4RootAnalysisManager.hh.
Field Documentation
fFileManager
std::shared_ptr<G4RootFileManager> G4RootAnalysisManager::fFileManager private
Definition at line 133 of file G4RootAnalysisManager.hh.
Referenced by G4RootMpiAnalysisManager::CloseFileImpl(), CloseFileImpl(), G4RootMpiAnalysisManager::CreateMpiNtupleManagers(), CreateNtupleManagers(), G4RootAnalysisManager(), G4RootMpiAnalysisManager::OpenFileImpl(), OpenFileImpl(), G4RootMpiAnalysisManager::SetMpiNtupleMerging(), SetNtupleMerging(), WriteH1(), WriteH2(), WriteH3(), WriteImpl(), WriteP1(), and WriteP2().
fgInstance
G4ThreadLocal G4RootAnalysisManager * G4RootAnalysisManager::fgInstance = nullptr static private
Definition at line 105 of file G4RootAnalysisManager.hh.
Referenced by G4RootAnalysisManager(), Instance(), IsInstance(), and ~G4RootAnalysisManager().
fgkDefaultBasketSize
constexpr unsigned int G4RootAnalysisManager::fgkDefaultBasketSize = 32000 static constexpr private
Definition at line 101 of file G4RootAnalysisManager.hh.
Referenced by G4RootAnalysisManager().
fgMasterInstance
G4RootAnalysisManager * G4RootAnalysisManager::fgMasterInstance = nullptr static private
Definition at line 104 of file G4RootAnalysisManager.hh.
Referenced by CreateNtupleManagers(), G4RootAnalysisManager(), SetNtupleMergingMode(), WriteH1(), WriteH2(), WriteH3(), WriteImpl(), WriteP1(), WriteP2(), and ~G4RootAnalysisManager().
fNofNtupleFiles
G4int G4RootAnalysisManager::fNofNtupleFiles private
Definition at line 128 of file G4RootAnalysisManager.hh.
Referenced by CreateNtupleManagers(), G4RootAnalysisManager(), GetNtupleFileNumber(), G4RootMpiAnalysisManager::OpenFileImpl(), OpenFileImpl(), G4RootMpiAnalysisManager::SetMpiNtupleMergingMode(), and SetNtupleMergingMode().
fNtupleManager
G4RootNtupleManager* G4RootAnalysisManager::fNtupleManager private
Definition at line 131 of file G4RootAnalysisManager.hh.
Referenced by ClearNtupleManagers(), CloseFileImpl(), G4RootMpiAnalysisManager::CreateMpiNtupleManagers(), CreateNtupleManagers(), G4RootMpiAnalysisManager::OpenFileImpl(), OpenFileImpl(), G4RootMpiAnalysisManager::Reset(), ResetNtuple(), G4RootMpiAnalysisManager::WriteNtuple(), and WriteNtuple().
fNtupleMergeMode
G4NtupleMergeMode G4RootAnalysisManager::fNtupleMergeMode private
Definition at line 130 of file G4RootAnalysisManager.hh.
Referenced by ClearNtupleManagers(), CloseFileImpl(), CreateNtupleManagers(), OpenFileImpl(), ResetNtuple(), SetNtupleMergingMode(), WriteImpl(), and WriteNtuple().
fNtupleRowWise
G4bool G4RootAnalysisManager::fNtupleRowWise private
Definition at line 129 of file G4RootAnalysisManager.hh.
Referenced by G4RootMpiAnalysisManager::CreateMpiNtupleManagers(), CreateNtupleManagers(), G4RootAnalysisManager(), G4RootMpiAnalysisManager::SetMpiNtupleMerging(), SetNtupleMergingMode(), and SetNtupleRowWise().
fSlaveNtupleManager
G4RootPNtupleManager* G4RootAnalysisManager::fSlaveNtupleManager private
Definition at line 132 of file G4RootAnalysisManager.hh.
Referenced by ClearNtupleManagers(), CreateNtupleManagers(), OpenFileImpl(), and WriteNtuple().
The documentation for this class was generated from the following files:
source/analysis/root/include/G4RootAnalysisManager.hh
source/analysis/root/src/G4RootAnalysisManager.cc