Geant4: source/processes/hadronic/models/lend/src/xDataTOM_importXML_W_XYs_LegendreSeries.cc File Reference
xDataTOM_importXML_W_XYs_LegendreSeries.cc File Reference
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <ctype.h>
#include "xDataTOM_importXML_private.h"
Functions
static int xDataXML_LegendreSeriesDataToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_LegendreSeries *LegendreSeries, int index, int length, double value)
int xDataXML_W_XYs_LegendreSeriesToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_element *TE)
int xDataXML_W_XYs_LegendreSeries_LegendreSeriesToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_LegendreSeries *LegendreSeries)
Function Documentation
xDataXML_LegendreSeriesDataToTOM()
static int xDataXML_LegendreSeriesDataToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_LegendreSeries * LegendreSeries, int index, int length, double value) static
Definition at line 71 of file xDataTOM_importXML_W_XYs_LegendreSeries.cc.
Referenced by xDataXML_W_XYs_LegendreSeries_LegendreSeriesToTOM().
xDataXML_W_XYs_LegendreSeries_LegendreSeriesToTOM()
int xDataXML_W_XYs_LegendreSeries_LegendreSeriesToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_LegendreSeries * LegendreSeries)
Definition at line 58 of file xDataTOM_importXML_W_XYs_LegendreSeries.cc.
Referenced by xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), and xDataXML_W_XYs_LegendreSeriesToTOM().
xDataXML_W_XYs_LegendreSeriesToTOM()
int xDataXML_W_XYs_LegendreSeriesToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_element * TE)
Definition at line 22 of file xDataTOM_importXML_W_XYs_LegendreSeries.cc.
Referenced by xDataXML_constructTOM().