Geant4: G4ConcreteNNTwoBodyResonance Class Reference
G4ConcreteNNTwoBodyResonance Class Reference
#include <G4ConcreteNNTwoBodyResonance.hh>
Public Member Functions
G4ConcreteNNTwoBodyResonance (const G4ParticleDefinition *aPrimary, const G4ParticleDefinition *bPriamry, const G4ParticleDefinition *aSecondary, const G4ParticleDefinition *bSecondary, const G4VXResonanceTable &sigmaTable)
void establish_G4MT_TLS_G4ConcreteNNTwoBodyResonance (const G4ParticleDefinition *aPrimary, const G4ParticleDefinition *bPriamry, const G4ParticleDefinition *aSecondary, const G4ParticleDefinition *bSecondary, const G4VXResonanceTable &sigmaTable)
G4ConcreteNNTwoBodyResonance (void *s1, void *s2, void *s3, void *s4, void *s5, void *s6, void *s7)
virtual ~G4ConcreteNNTwoBodyResonance ()
virtual G4bool IsInCharge (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const std::vector< G4String > & GetListOfColliders (G4int) const
virtual G4String GetName () const
G4bool operator== (const G4ConcreteNNTwoBodyResonance &right) const
G4bool operator!= (const G4ConcreteNNTwoBodyResonance &right) const
Public Member Functions inherited from G4VScatteringCollision
G4VScatteringCollision ()
void establish_G4MT_TLS_G4VScatteringCollision ()
virtual ~G4VScatteringCollision ()
G4bool operator== (const G4VScatteringCollision &right) const
G4bool operator!= (const G4VScatteringCollision &right) const
virtual G4KineticTrackVector * FinalState (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const G4VAngularDistribution * GetAngularDistribution () const
Public Member Functions inherited from G4VCollision
G4VCollision ()
void establish_G4MT_TLS_G4VCollision ()
G4VCollision (void *s1, void *s2, void *s3, void *s4, void *s5, void *s6, void *s7)
virtual ~G4VCollision ()
G4bool operator== (const G4VCollision &right) const
G4bool operator!= (const G4VCollision &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual void Print () const
virtual void Print (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Protected Member Functions
virtual const G4VCrossSectionSource * GetCrossSectionSource () const
virtual const std::vector< const G4ParticleDefinition * > & GetOutgoingParticles () const
Protected Member Functions inherited from G4VCollision
G4int GetNumberOfPartons (const G4ParticleDefinition *aP) const
virtual const G4CollisionVector * GetComponents () const
Private Member Functions
G4ConcreteNNTwoBodyResonance (const G4ConcreteNNTwoBodyResonance &)
G4ConcreteNNTwoBodyResonance & operator= (const G4ConcreteNNTwoBodyResonance &)
Private Attributes
G4VCrossSectionSource * crossSectionSource
const G4ParticleDefinition * thePrimary1
const G4ParticleDefinition * thePrimary2
std::vector< const G4ParticleDefinition * > theOutGoing
Detailed Description
Definition at line 39 of file G4ConcreteNNTwoBodyResonance.hh.
Constructor & Destructor Documentation
G4ConcreteNNTwoBodyResonance() [1/3]
G4ConcreteNNTwoBodyResonance::G4ConcreteNNTwoBodyResonance (const G4ParticleDefinition * aPrimary, const G4ParticleDefinition * bPriamry, const G4ParticleDefinition * aSecondary, const G4ParticleDefinition * bSecondary, const G4VXResonanceTable & sigmaTable)
Definition at line 42 of file G4ConcreteNNTwoBodyResonance.cc.
G4ConcreteNNTwoBodyResonance() [2/3]
G4ConcreteNNTwoBodyResonance::G4ConcreteNNTwoBodyResonance (void * s1, void * s2, void * s3, void * s4, void * s5, void * s6, void * s7)
Definition at line 78 of file G4ConcreteNNTwoBodyResonance.cc.
~G4ConcreteNNTwoBodyResonance()
G4ConcreteNNTwoBodyResonance::~G4ConcreteNNTwoBodyResonance () virtual
Definition at line 64 of file G4ConcreteNNTwoBodyResonance.cc.
G4ConcreteNNTwoBodyResonance() [3/3]
G4ConcreteNNTwoBodyResonance::G4ConcreteNNTwoBodyResonance (const G4ConcreteNNTwoBodyResonance &) private
Member Function Documentation
establish_G4MT_TLS_G4ConcreteNNTwoBodyResonance()
void G4ConcreteNNTwoBodyResonance::establish_G4MT_TLS_G4ConcreteNNTwoBodyResonance (const G4ParticleDefinition * aPrimary, const G4ParticleDefinition * bPriamry, const G4ParticleDefinition * aSecondary, const G4ParticleDefinition * bSecondary, const G4VXResonanceTable & sigmaTable)
Definition at line 82 of file G4ConcreteNNTwoBodyResonance.cc.
Referenced by G4ConcreteNNToDeltaDelta::G4ConcreteNNToDeltaDelta(), G4ConcreteNNToDeltaDeltastar::G4ConcreteNNToDeltaDeltastar(), G4ConcreteNNToDeltaNstar::G4ConcreteNNToDeltaNstar(), G4ConcreteNNToNDelta::G4ConcreteNNToNDelta(), G4ConcreteNNToNDeltaStar::G4ConcreteNNToNDeltaStar(), G4ConcreteNNToNNStar::G4ConcreteNNToNNStar(), and G4ConcreteNStarNToNN::G4ConcreteNStarNToNN().
GetCrossSectionSource()
virtual const G4VCrossSectionSource* G4ConcreteNNTwoBodyResonance::GetCrossSectionSource () const inline protected virtual
Implements G4VCollision.
Definition at line 80 of file G4ConcreteNNTwoBodyResonance.hh.
GetListOfColliders()
virtual const std::vector<G4String>& G4ConcreteNNTwoBodyResonance::GetListOfColliders (G4int) const inline virtual
Implements G4VCollision.
Definition at line 62 of file G4ConcreteNNTwoBodyResonance.hh.
GetName()
virtual G4String G4ConcreteNNTwoBodyResonance::GetName (void) const inline virtual
Implements G4VCollision.
Reimplemented in G4ConcreteNNToDeltaDelta, G4ConcreteNNToDeltaDeltastar, G4ConcreteNNToDeltaNstar, G4ConcreteNNToNDelta, G4ConcreteNNToNDeltaStar, G4ConcreteNNToNNStar, and G4ConcreteNStarNToNN.
Definition at line 69 of file G4ConcreteNNTwoBodyResonance.hh.
GetOutgoingParticles()
virtual const std::vector<const G4ParticleDefinition*>& G4ConcreteNNTwoBodyResonance::GetOutgoingParticles () const inline protected virtual
Implements G4VScatteringCollision.
Definition at line 82 of file G4ConcreteNNTwoBodyResonance.hh.
IsInCharge()
G4bool G4ConcreteNNTwoBodyResonance::IsInCharge (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VCollision.
Definition at line 70 of file G4ConcreteNNTwoBodyResonance.cc.
operator!=()
G4bool G4ConcreteNNTwoBodyResonance::operator!= (const G4ConcreteNNTwoBodyResonance & right) const
operator=()
G4ConcreteNNTwoBodyResonance& G4ConcreteNNTwoBodyResonance::operator= (const G4ConcreteNNTwoBodyResonance &) private
operator==()
G4bool G4ConcreteNNTwoBodyResonance::operator== (const G4ConcreteNNTwoBodyResonance & right) const
Field Documentation
crossSectionSource
G4VCrossSectionSource* G4ConcreteNNTwoBodyResonance::crossSectionSource private
Definition at line 93 of file G4ConcreteNNTwoBodyResonance.hh.
Referenced by establish_G4MT_TLS_G4ConcreteNNTwoBodyResonance(), G4ConcreteNNTwoBodyResonance(), GetCrossSectionSource(), and ~G4ConcreteNNTwoBodyResonance().
theOutGoing
std::vector<const G4ParticleDefinition*> G4ConcreteNNTwoBodyResonance::theOutGoing private
Definition at line 96 of file G4ConcreteNNTwoBodyResonance.hh.
Referenced by establish_G4MT_TLS_G4ConcreteNNTwoBodyResonance(), G4ConcreteNNTwoBodyResonance(), and GetOutgoingParticles().
thePrimary1
const G4ParticleDefinition* G4ConcreteNNTwoBodyResonance::thePrimary1 private
Definition at line 94 of file G4ConcreteNNTwoBodyResonance.hh.
Referenced by establish_G4MT_TLS_G4ConcreteNNTwoBodyResonance(), and IsInCharge().
thePrimary2
const G4ParticleDefinition* G4ConcreteNNTwoBodyResonance::thePrimary2 private
Definition at line 95 of file G4ConcreteNNTwoBodyResonance.hh.
Referenced by establish_G4MT_TLS_G4ConcreteNNTwoBodyResonance(), and IsInCharge().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/im_r_matrix/include/G4ConcreteNNTwoBodyResonance.hh
source/processes/hadronic/models/im_r_matrix/src/G4ConcreteNNTwoBodyResonance.cc