Geant4: G4GDMLReadSolids Class Reference
G4GDMLReadSolids Class Reference
#include <G4GDMLReadSolids.hh>
Data Structures
struct rzPointType
struct zplaneType
Public Member Functions
G4VSolid * GetSolid (const G4String &) const
G4SurfaceProperty * GetSurfaceProperty (const G4String &) const
virtual void SolidsRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLReadMaterials
G4Element * GetElement (const G4String &, G4bool verbose=true) const
G4Isotope * GetIsotope (const G4String &, G4bool verbose=true) const
G4Material * GetMaterial (const G4String &, G4bool verbose=true) const
virtual void MaterialsRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLReadDefine
G4bool IsValidID (const G4String &) const
G4double GetConstant (const G4String &)
G4double GetVariable (const G4String &)
G4double GetQuantity (const G4String &)
G4ThreeVector GetPosition (const G4String &)
G4ThreeVector GetRotation (const G4String &)
G4ThreeVector GetScale (const G4String &)
G4GDMLMatrix GetMatrix (const G4String &)
virtual void DefineRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLRead
virtual void SetupRead (const xercesc::DOMElement *const)=0
virtual void Paramvol_contentRead (const xercesc::DOMElement *const)=0
virtual void Volume_contentRead (const xercesc::DOMElement *const)=0
virtual void StructureRead (const xercesc::DOMElement *const)=0
virtual void ExtensionRead (const xercesc::DOMElement *const)
virtual void UserinfoRead (const xercesc::DOMElement *const)
virtual G4LogicalVolume * GetVolume (const G4String &) const =0
virtual G4String GetSetup (const G4String &)=0
void Read (const G4String &, G4bool validation, G4bool isModule, G4bool strip=true)
void StripNames () const
void StripName (G4String &) const
void OverlapCheck (G4bool)
const G4GDMLAuxListType * GetAuxList () const
Protected Member Functions
G4GDMLReadSolids ()
virtual ~G4GDMLReadSolids ()
void BooleanRead (const xercesc::DOMElement *const, const BooleanOp)
void BoxRead (const xercesc::DOMElement *const)
void ConeRead (const xercesc::DOMElement *const)
void ElconeRead (const xercesc::DOMElement *const)
void EllipsoidRead (const xercesc::DOMElement *const)
void EltubeRead (const xercesc::DOMElement *const)
void XtruRead (const xercesc::DOMElement *const)
void HypeRead (const xercesc::DOMElement *const)
void MultiUnionNodeRead (const xercesc::DOMElement *const, G4MultiUnion *const)
void MultiUnionRead (const xercesc::DOMElement *const)
void OrbRead (const xercesc::DOMElement *const)
void ParaRead (const xercesc::DOMElement *const)
void ParaboloidRead (const xercesc::DOMElement *const)
void PolyconeRead (const xercesc::DOMElement *const)
void GenericPolyconeRead (const xercesc::DOMElement *const)
void PolyhedraRead (const xercesc::DOMElement *const)
void GenericPolyhedraRead (const xercesc::DOMElement *const)
G4QuadrangularFacet * QuadrangularRead (const xercesc::DOMElement *const)
void ReflectedSolidRead (const xercesc::DOMElement *const)
void ScaledSolidRead (const xercesc::DOMElement *const)
G4ExtrudedSolid::ZSection SectionRead (const xercesc::DOMElement *const, G4double)
void SphereRead (const xercesc::DOMElement *const)
void TessellatedRead (const xercesc::DOMElement *const)
void TetRead (const xercesc::DOMElement *const)
void TorusRead (const xercesc::DOMElement *const)
void GenTrapRead (const xercesc::DOMElement *const)
void TrapRead (const xercesc::DOMElement *const)
void TrdRead (const xercesc::DOMElement *const)
void TubeRead (const xercesc::DOMElement *const)
void CutTubeRead (const xercesc::DOMElement *const)
void TwistedboxRead (const xercesc::DOMElement *const)
void TwistedtrapRead (const xercesc::DOMElement *const)
void TwistedtrdRead (const xercesc::DOMElement *const)
void TwistedtubsRead (const xercesc::DOMElement *const)
G4TriangularFacet * TriangularRead (const xercesc::DOMElement *const)
G4TwoVector TwoDimVertexRead (const xercesc::DOMElement *const, G4double)
zplaneType ZplaneRead (const xercesc::DOMElement *const)
rzPointType RZPointRead (const xercesc::DOMElement *const)
void OpticalSurfaceRead (const xercesc::DOMElement *const)
void PropertyRead (const xercesc::DOMElement *const, G4OpticalSurface *)
Protected Member Functions inherited from G4GDMLReadMaterials
G4GDMLReadMaterials ()
virtual ~G4GDMLReadMaterials ()
G4double AtomRead (const xercesc::DOMElement *const)
G4int CompositeRead (const xercesc::DOMElement *const, G4String &)
G4double DRead (const xercesc::DOMElement *const)
G4double PRead (const xercesc::DOMElement *const)
G4double TRead (const xercesc::DOMElement *const)
G4double MEERead (const xercesc::DOMElement *const)
void ElementRead (const xercesc::DOMElement *const)
G4double FractionRead (const xercesc::DOMElement *const, G4String &)
void IsotopeRead (const xercesc::DOMElement *const)
void MaterialRead (const xercesc::DOMElement *const)
void MixtureRead (const xercesc::DOMElement *const, G4Element *)
void MixtureRead (const xercesc::DOMElement *const, G4Material *)
void PropertyRead (const xercesc::DOMElement *const, G4Material *)
Protected Member Functions inherited from G4GDMLReadDefine
G4GDMLReadDefine ()
virtual ~G4GDMLReadDefine ()
G4RotationMatrix GetRotationMatrix (const G4ThreeVector &)
void VectorRead (const xercesc::DOMElement *const, G4ThreeVector &)
G4String RefRead (const xercesc::DOMElement *const)
void ConstantRead (const xercesc::DOMElement *const)
void MatrixRead (const xercesc::DOMElement *const)
void PositionRead (const xercesc::DOMElement *const)
void RotationRead (const xercesc::DOMElement *const)
void ScaleRead (const xercesc::DOMElement *const)
void VariableRead (const xercesc::DOMElement *const)
void QuantityRead (const xercesc::DOMElement *const)
void ExpressionRead (const xercesc::DOMElement *const)
Protected Member Functions inherited from G4GDMLRead
G4GDMLRead ()
virtual ~G4GDMLRead ()
G4String Transcode (const XMLCh *const)
G4String GenerateName (const G4String &name, G4bool strip=false)
G4String Strip (const G4String &) const
void GeneratePhysvolName (const G4String &, G4VPhysicalVolume *)
void LoopRead (const xercesc::DOMElement *const, void(G4GDMLRead::*)(const xercesc::DOMElement *const))
G4GDMLAuxStructType AuxiliaryRead (const xercesc::DOMElement *const auxElem)
Private Types
enum BooleanOp { UNION, SUBTRACTION, INTERSECTION }
Additional Inherited Members
Protected Attributes inherited from G4GDMLReadDefine
std::map< G4String, G4double > quantityMap
std::map< G4String, G4ThreeVector > positionMap
std::map< G4String, G4ThreeVector > rotationMap
std::map< G4String, G4ThreeVector > scaleMap
std::map< G4String, G4GDMLMatrix > matrixMap
Protected Attributes inherited from G4GDMLRead
G4GDMLEvaluator eval
G4bool validate
G4bool check
G4bool dostrip
Detailed Description
Definition at line 53 of file G4GDMLReadSolids.hh.
Member Enumeration Documentation
BooleanOp
enum G4GDMLReadSolids::BooleanOp private
Enumerator
UNION
SUBTRACTION
INTERSECTION
Definition at line 55 of file G4GDMLReadSolids.hh.
Constructor & Destructor Documentation
G4GDMLReadSolids()
G4GDMLReadSolids::G4GDMLReadSolids () protected
Definition at line 73 of file G4GDMLReadSolids.cc.
~G4GDMLReadSolids()
G4GDMLReadSolids::~G4GDMLReadSolids () protected virtual
Definition at line 77 of file G4GDMLReadSolids.cc.
Member Function Documentation
BooleanRead()
void G4GDMLReadSolids::BooleanRead (const xercesc::DOMElement * const booleanElement, const BooleanOp op) protected
Definition at line 82 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
BoxRead()
void G4GDMLReadSolids::BoxRead (const xercesc::DOMElement * const boxElement) protected
Definition at line 179 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
ConeRead()
void G4GDMLReadSolids::ConeRead (const xercesc::DOMElement * const coneElement) protected
Definition at line 229 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
CutTubeRead()
void G4GDMLReadSolids::CutTubeRead (const xercesc::DOMElement * const cuttubeElement) protected
Definition at line 2006 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
ElconeRead()
void G4GDMLReadSolids::ElconeRead (const xercesc::DOMElement * const elconeElement) protected
Definition at line 297 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
EllipsoidRead()
void G4GDMLReadSolids::EllipsoidRead (const xercesc::DOMElement * const ellipsoidElement) protected
Definition at line 348 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
EltubeRead()
void G4GDMLReadSolids::EltubeRead (const xercesc::DOMElement * const eltubeElement) protected
Definition at line 404 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
GenericPolyconeRead()
void G4GDMLReadSolids::GenericPolyconeRead (const xercesc::DOMElement * const polyconeElement) protected
Definition at line 954 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
GenericPolyhedraRead()
void G4GDMLReadSolids::GenericPolyhedraRead (const xercesc::DOMElement * const polyhedraElement) protected
Definition at line 1133 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
GenTrapRead()
void G4GDMLReadSolids::GenTrapRead (const xercesc::DOMElement * const gtrapElement) protected
Definition at line 1691 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
GetSolid()
G4VSolid * G4GDMLReadSolids::GetSolid (const G4String & ref) const
Definition at line 2753 of file G4GDMLReadSolids.cc.
Referenced by BooleanRead(), MultiUnionNodeRead(), ReflectedSolidRead(), ScaledSolidRead(), G03ColorReader::VolumeRead(), and G4GDMLReadStructure::VolumeRead().
GetSurfaceProperty()
G4SurfaceProperty * G4GDMLReadSolids::GetSurfaceProperty (const G4String & ref) const
Definition at line 2768 of file G4GDMLReadSolids.cc.
Referenced by G4GDMLReadStructure::BorderSurfaceRead(), and G4GDMLReadStructure::SkinSurfaceRead().
HypeRead()
void G4GDMLReadSolids::HypeRead (const xercesc::DOMElement * const hypeElement) protected
Definition at line 516 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
MultiUnionNodeRead()
void G4GDMLReadSolids::MultiUnionNodeRead (const xercesc::DOMElement * const unionNodeElement, G4MultiUnion * const multiUnionSolid) protected
Definition at line 578 of file G4GDMLReadSolids.cc.
Referenced by MultiUnionRead().
MultiUnionRead()
void G4GDMLReadSolids::MultiUnionRead (const xercesc::DOMElement * const unionElement) protected
Definition at line 647 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
OpticalSurfaceRead()
void G4GDMLReadSolids::OpticalSurfaceRead (const xercesc::DOMElement * const opticalsurfaceElement) protected
Definition at line 2548 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
OrbRead()
void G4GDMLReadSolids::OrbRead (const xercesc::DOMElement * const orbElement) protected
Definition at line 705 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
ParaboloidRead()
void G4GDMLReadSolids::ParaboloidRead (const xercesc::DOMElement * const paraElement) protected
Definition at line 813 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
ParaRead()
void G4GDMLReadSolids::ParaRead (const xercesc::DOMElement * const paraElement) protected
Definition at line 748 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
PolyconeRead()
void G4GDMLReadSolids::PolyconeRead (const xercesc::DOMElement * const polyconeElement) protected
Definition at line 863 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
PolyhedraRead()
void G4GDMLReadSolids::PolyhedraRead (const xercesc::DOMElement * const polyhedraElement) protected
Definition at line 1040 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
PropertyRead()
void G4GDMLReadSolids::PropertyRead (const xercesc::DOMElement * const propertyElement, G4OpticalSurface * opticalsurface) protected
Definition at line 2479 of file G4GDMLReadSolids.cc.
Referenced by OpticalSurfaceRead().
QuadrangularRead()
G4QuadrangularFacet * G4GDMLReadSolids::QuadrangularRead (const xercesc::DOMElement * const quadrangularElement) protected
Definition at line 1223 of file G4GDMLReadSolids.cc.
Referenced by TessellatedRead().
ReflectedSolidRead()
void G4GDMLReadSolids::ReflectedSolidRead (const xercesc::DOMElement * const reflectedSolidElement) protected
Definition at line 1278 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
RZPointRead()
G4GDMLReadSolids::rzPointType G4GDMLReadSolids::RZPointRead (const xercesc::DOMElement * const zplaneElement) protected
Definition at line 2444 of file G4GDMLReadSolids.cc.
Referenced by GenericPolyconeRead(), and GenericPolyhedraRead().
ScaledSolidRead()
void G4GDMLReadSolids::ScaledSolidRead (const xercesc::DOMElement * const scaledSolidElement) protected
Definition at line 1344 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
SectionRead()
G4ExtrudedSolid::ZSection G4GDMLReadSolids::SectionRead (const xercesc::DOMElement * const sectionElement, G4double lunit) protected
Definition at line 1412 of file G4GDMLReadSolids.cc.
Referenced by XtruRead().
SolidsRead()
void G4GDMLReadSolids::SolidsRead (const xercesc::DOMElement * const solidsElement) virtual
Implements G4GDMLRead.
Definition at line 2689 of file G4GDMLReadSolids.cc.
SphereRead()
void G4GDMLReadSolids::SphereRead (const xercesc::DOMElement * const sphereElement) protected
Definition at line 1455 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
TessellatedRead()
void G4GDMLReadSolids::TessellatedRead (const xercesc::DOMElement * const tessellatedElement) protected
Definition at line 1520 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
TetRead()
void G4GDMLReadSolids::TetRead (const xercesc::DOMElement * const tetElement) protected
Definition at line 1576 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
TorusRead()
void G4GDMLReadSolids::TorusRead (const xercesc::DOMElement * const torusElement) protected
Definition at line 1629 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
TrapRead()
void G4GDMLReadSolids::TrapRead (const xercesc::DOMElement * const trapElement) protected
Definition at line 1761 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
TrdRead()
void G4GDMLReadSolids::TrdRead (const xercesc::DOMElement * const trdElement) protected
Definition at line 1840 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
TriangularRead()
G4TriangularFacet * G4GDMLReadSolids::TriangularRead (const xercesc::DOMElement * const triangularElement) protected
Definition at line 1895 of file G4GDMLReadSolids.cc.
Referenced by TessellatedRead().
TubeRead()
void G4GDMLReadSolids::TubeRead (const xercesc::DOMElement * const tubeElement) protected
Definition at line 1945 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
TwistedboxRead()
void G4GDMLReadSolids::TwistedboxRead (const xercesc::DOMElement * const twistedboxElement) protected
Definition at line 2077 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
TwistedtrapRead()
void G4GDMLReadSolids::TwistedtrapRead (const xercesc::DOMElement * const twistedtrapElement) protected
Definition at line 2136 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
TwistedtrdRead()
void G4GDMLReadSolids::TwistedtrdRead (const xercesc::DOMElement * const twistedtrdElement) protected
Definition at line 2217 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
TwistedtubsRead()
void G4GDMLReadSolids::TwistedtubsRead (const xercesc::DOMElement * const twistedtubsElement) protected
Definition at line 2282 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
TwoDimVertexRead()
G4TwoVector G4GDMLReadSolids::TwoDimVertexRead (const xercesc::DOMElement * const element, G4double lunit) protected
Definition at line 2376 of file G4GDMLReadSolids.cc.
Referenced by XtruRead().
XtruRead()
void G4GDMLReadSolids::XtruRead (const xercesc::DOMElement * const xtruElement) protected
Definition at line 453 of file G4GDMLReadSolids.cc.
Referenced by SolidsRead().
ZplaneRead()
G4GDMLReadSolids::zplaneType G4GDMLReadSolids::ZplaneRead (const xercesc::DOMElement * const zplaneElement) protected
Definition at line 2410 of file G4GDMLReadSolids.cc.
Referenced by G4GDMLReadParamvol::Polycone_dimensionsRead(), PolyconeRead(), G4GDMLReadParamvol::Polyhedra_dimensionsRead(), and PolyhedraRead().
The documentation for this class was generated from the following files:
source/persistency/gdml/include/G4GDMLReadSolids.hh
source/persistency/gdml/src/G4GDMLReadSolids.cc