Geant4: source/processes/hadronic/models/lend/src/nf_stringToDoubles.cc File Reference
nf_stringToDoubles.cc File Reference
#include <stdlib.h>
#include <cmath>
#include "nf_utilities.h"
Macros
#define isfinite std::isfinite
#define numberOfStaticDoubles (100 * 1000)
Functions
static nfu_status nfu_stringToListOfDoubles2 (char const *str, int64_t *numberConverted, double **doublePtr, char **endCharacter)
nfu_status nfu_stringToListOfDoubles (char const *str, int64_t *numberConverted, double **doublePtr, char **endCharacter)
char * nf_floatToShortestString (double value, int significantDigits, int favorEFormBy, int flags)
Macro Definition Documentation
isfinite
#define isfinite std::isfinite
Definition at line 15 of file nf_stringToDoubles.cc.
numberOfStaticDoubles
#define numberOfStaticDoubles (100 * 1000)
Definition at line 23 of file nf_stringToDoubles.cc.
Function Documentation
nf_floatToShortestString()
char* nf_floatToShortestString (double value, int significantDigits, int favorEFormBy, int flags)
Definition at line 66 of file nf_stringToDoubles.cc.
nfu_stringToListOfDoubles()
nfu_status nfu_stringToListOfDoubles (char const * str, int64_t * numberConverted, double ** doublePtr, char ** endCharacter)
Definition at line 29 of file nf_stringToDoubles.cc.
Referenced by ptwX_fromString(), and ptwXY_fromString().
nfu_stringToListOfDoubles2()
static nfu_status nfu_stringToListOfDoubles2 (char const * str, int64_t * numberConverted, double ** doublePtr, char ** endCharacter) static
Definition at line 38 of file nf_stringToDoubles.cc.
Referenced by nfu_stringToListOfDoubles().