Geant4: G4ClippablePolygon Class Reference
G4ClippablePolygon Class Reference
#include <G4ClippablePolygon.hh>
Public Member Functions
G4ClippablePolygon ()
virtual ~G4ClippablePolygon ()
virtual void AddVertexInOrder (const G4ThreeVector vertex)
virtual void ClearAllVertices ()
void SetNormal (const G4ThreeVector &newNormal)
const G4ThreeVector GetNormal () const
virtual G4bool Clip (const G4VoxelLimits &voxelLimit)
virtual G4bool PartialClip (const G4VoxelLimits &voxelLimit, const EAxis IgnoreMe)
virtual void ClipAlongOneAxis (const G4VoxelLimits &voxelLimit, const EAxis axis)
virtual G4bool GetExtent (const EAxis axis, G4double &min, G4double &max) const
virtual const G4ThreeVector * GetMinPoint (const EAxis axis) const
virtual const G4ThreeVector * GetMaxPoint (const EAxis axis) const
G4int GetNumVertices () const
G4bool Empty () const
virtual G4bool InFrontOf (const G4ClippablePolygon &other, EAxis axis) const
virtual G4bool BehindOf (const G4ClippablePolygon &other, EAxis axis) const
virtual G4bool GetPlanerExtent (const G4ThreeVector &pointOnPlane, const G4ThreeVector &planeNormal, G4double &min, G4double &max) const
Protected Member Functions
void ClipToSimpleLimits (G4ThreeVectorList &pPolygon, G4ThreeVectorList &outputPolygon, const G4VoxelLimits &pVoxelLimit)
Protected Attributes
G4ThreeVectorList vertices
G4ThreeVector normal
G4double kCarTolerance
Private Types
typedef std::vector< G4ThreeVector > G4ThreeVectorList
Detailed Description
Definition at line 54 of file G4ClippablePolygon.hh.
Member Typedef Documentation
G4ThreeVectorList
typedef std::vector<G4ThreeVector> G4ClippablePolygon::G4ThreeVectorList private
Definition at line 56 of file G4ClippablePolygon.hh.
Constructor & Destructor Documentation
G4ClippablePolygon()
G4ClippablePolygon::G4ClippablePolygon ()
Definition at line 47 of file G4ClippablePolygon.cc.
~G4ClippablePolygon()
G4ClippablePolygon::~G4ClippablePolygon () virtual
Definition at line 57 of file G4ClippablePolygon.cc.
Member Function Documentation
AddVertexInOrder()
void G4ClippablePolygon::AddVertexInOrder (const G4ThreeVector vertex) virtual
Definition at line 65 of file G4ClippablePolygon.cc.
Referenced by G4PolyPhiFace::CalculateExtent(), G4PolyconeSide::CalculateExtent(), and G4PolyhedraSide::CalculateExtent().
BehindOf()
G4bool G4ClippablePolygon::BehindOf (const G4ClippablePolygon & other, EAxis axis) const virtual
Definition at line 295 of file G4ClippablePolygon.cc.
Referenced by G4SolidExtentList::AddSurface().
ClearAllVertices()
void G4ClippablePolygon::ClearAllVertices () virtual
Definition at line 74 of file G4ClippablePolygon.cc.
Referenced by G4PolyconeSide::CalculateExtent().
Clip()
G4bool G4ClippablePolygon::Clip (const G4VoxelLimits & voxelLimit) virtual
Definition at line 83 of file G4ClippablePolygon.cc.
ClipAlongOneAxis()
void G4ClippablePolygon::ClipAlongOneAxis (const G4VoxelLimits & voxelLimit, const EAxis axis) virtual
Definition at line 400 of file G4ClippablePolygon.cc.
Referenced by Clip(), and PartialClip().
ClipToSimpleLimits()
void G4ClippablePolygon::ClipToSimpleLimits (G4ThreeVectorList & pPolygon, G4ThreeVectorList & outputPolygon, const G4VoxelLimits & pVoxelLimit) protected
Definition at line 444 of file G4ClippablePolygon.cc.
Referenced by ClipAlongOneAxis().
Empty()
G4bool G4ClippablePolygon::Empty () const inline
Referenced by BehindOf(), G4SolidExtentList::GetExtent(), and InFrontOf().
GetExtent()
G4bool G4ClippablePolygon::GetExtent (const EAxis axis, G4double & min, G4double & max) const virtual
Definition at line 116 of file G4ClippablePolygon.cc.
Referenced by G4SolidExtentList::AddSurface(), and G4SolidExtentList::GetExtent().
GetMaxPoint()
const G4ThreeVector * G4ClippablePolygon::GetMaxPoint (const EAxis axis) const virtual
Definition at line 189 of file G4ClippablePolygon.cc.
Referenced by BehindOf().
GetMinPoint()
const G4ThreeVector * G4ClippablePolygon::GetMinPoint (const EAxis axis) const virtual
Definition at line 158 of file G4ClippablePolygon.cc.
Referenced by InFrontOf().
GetNormal()
const G4ThreeVector G4ClippablePolygon::GetNormal () const inline
Referenced by BehindOf(), G4SolidExtentList::GetExtent(), and InFrontOf().
GetNumVertices()
G4int G4ClippablePolygon::GetNumVertices () const inline
GetPlanerExtent()
G4bool G4ClippablePolygon::GetPlanerExtent (const G4ThreeVector & pointOnPlane, const G4ThreeVector & planeNormal, G4double & min, G4double & max) const virtual
Definition at line 360 of file G4ClippablePolygon.cc.
Referenced by BehindOf(), and InFrontOf().
InFrontOf()
G4bool G4ClippablePolygon::InFrontOf (const G4ClippablePolygon & other, EAxis axis) const virtual
Definition at line 230 of file G4ClippablePolygon.cc.
Referenced by G4SolidExtentList::AddSurface().
PartialClip()
G4bool G4ClippablePolygon::PartialClip (const G4VoxelLimits & voxelLimit, const EAxis IgnoreMe) virtual
Definition at line 100 of file G4ClippablePolygon.cc.
Referenced by G4PolyPhiFace::CalculateExtent(), G4PolyconeSide::CalculateExtent(), and G4PolyhedraSide::CalculateExtent().
SetNormal()
void G4ClippablePolygon::SetNormal (const G4ThreeVector & newNormal) inline
Referenced by G4PolyPhiFace::CalculateExtent(), G4PolyconeSide::CalculateExtent(), and G4PolyhedraSide::CalculateExtent().
Field Documentation
kCarTolerance
G4double G4ClippablePolygon::kCarTolerance protected
Definition at line 122 of file G4ClippablePolygon.hh.
Referenced by BehindOf(), G4ClippablePolygon(), and InFrontOf().
normal
G4ThreeVector G4ClippablePolygon::normal protected
Definition at line 121 of file G4ClippablePolygon.hh.
Referenced by BehindOf(), and InFrontOf().
vertices
G4ThreeVectorList G4ClippablePolygon::vertices protected
Definition at line 120 of file G4ClippablePolygon.hh.
Referenced by AddVertexInOrder(), BehindOf(), ClearAllVertices(), Clip(), ClipAlongOneAxis(), GetExtent(), GetMaxPoint(), GetMinPoint(), GetPlanerExtent(), InFrontOf(), and PartialClip().
The documentation for this class was generated from the following files:
source/geometry/solids/specific/include/G4ClippablePolygon.hh
source/geometry/solids/specific/src/G4ClippablePolygon.cc