Geant4: environments/g4py/tests/test05/module/XFunc.hh File Reference
XFunc.hh File Reference
Functions
int func1 (int i)
double func1 (int i, double d)
int func2 (int i)
int func2 (int i0, int i1)
int func3 (int i)
int func3 (double d)
Function Documentation
func1() [1/2]
int func1 (int i)
Definition at line 39 of file XFunc.cc.
Referenced by G4LDMBremModel::SampleSecondaries(), and G4MuBremsstrahlungModel::SampleSecondaries().
func1() [2/2]
double func1 (int i, double d)
Definition at line 44 of file XFunc.cc.
func2() [1/2]
int func2 (int i)
Definition at line 50 of file XFunc.cc.
Referenced by G4LDMBremModel::SampleSecondaries(), and G4MuBremsstrahlungModel::SampleSecondaries().
func2() [2/2]
int func2 (int i0, int i1)
Definition at line 55 of file XFunc.cc.
func3() [1/2]
int func3 (double d)
Definition at line 65 of file XFunc.cc.
func3() [2/2]
int func3 (int i)
Definition at line 60 of file XFunc.cc.