Geant4: G4MagIntegratorStepper Class Reference
G4MagIntegratorStepper Class Reference abstract
#include <G4MagIntegratorStepper.hh>
Public Member Functions
G4MagIntegratorStepper (G4EquationOfMotion *Equation, G4int numIntegrationVariables, G4int numStateVariables=12, bool isFSAL=false)
virtual ~G4MagIntegratorStepper ()=default
virtual void Stepper (const G4double y[], const G4double dydx[], G4double h, G4double yout[], G4double yerr[])=0
virtual G4double DistChord () const =0
void NormaliseTangentVector (G4double vec[6])
void NormalisePolarizationVector (G4double vec[12])
void RightHandSide (const G4double y[], G4double dydx[]) const
void RightHandSide (const G4double y[], G4double dydx[], G4double field[]) const
G4int GetNumberOfVariables () const
G4int GetNumberOfStateVariables () const
virtual G4int IntegratorOrder () const =0
G4int IntegrationOrder ()
G4EquationOfMotion * GetEquationOfMotion ()
const G4EquationOfMotion * GetEquationOfMotion () const
void SetEquationOfMotion (G4EquationOfMotion *newEquation)
unsigned long GetfNoRHSCalls ()
void ResetfNORHSCalls ()
bool IsFSAL () const
Protected Member Functions
void SetIntegrationOrder (int order)
void SetFSAL (bool flag=true)
Private Member Functions
G4MagIntegratorStepper (const G4MagIntegratorStepper &)
G4MagIntegratorStepper & operator= (const G4MagIntegratorStepper &)
Private Attributes
G4EquationOfMotion * fEquation_Rhs
const G4int fNoIntegrationVariables
const G4int fNoStateVariables
unsigned long fNoRHSCalls
int fIntegrationOrder
bool fIsFSAL
Detailed Description
Definition at line 51 of file G4MagIntegratorStepper.hh.
Constructor & Destructor Documentation
G4MagIntegratorStepper() [1/2]
G4MagIntegratorStepper::G4MagIntegratorStepper (G4EquationOfMotion * Equation, G4int numIntegrationVariables, G4int numStateVariables = 12, bool isFSAL = false)
Definition at line 35 of file G4MagIntegratorStepper.cc.
~G4MagIntegratorStepper()
virtual G4MagIntegratorStepper::~G4MagIntegratorStepper () virtual default
G4MagIntegratorStepper() [2/2]
G4MagIntegratorStepper::G4MagIntegratorStepper (const G4MagIntegratorStepper &) private
Member Function Documentation
DistChord()
virtual G4double G4MagIntegratorStepper::DistChord () const pure virtual
Implemented in G4BogackiShampine23, G4NystromRK4, G4RK547FEq1, G4RK547FEq2, G4RK547FEq3, G4DormandPrince745, G4BogackiShampine45, G4DoLoMcPriRK34, G4HelixMixedStepper, G4MagHelicalStepper, G4MagErrorStepper, G4TsitourasRK45, G4ExactHelixStepper, G4CashKarpRKF45, G4RKG3_Stepper, G4ConstRK4, G4DormandPrinceRK78, G4HelixExplicitEuler, and G4DormandPrinceRK56.
GetEquationOfMotion() [1/2]
G4EquationOfMotion* G4MagIntegratorStepper::GetEquationOfMotion () inline
Referenced by G4MagInt_Driver::GetEquationOfMotion(), G4NystromRK4::GetField(), G4NystromRK4::SetDistanceForConstantField(), G4RKG3_Stepper::StepNoErr(), and G4RKG3_Stepper::Stepper().
GetEquationOfMotion() [2/2]
const G4EquationOfMotion* G4MagIntegratorStepper::GetEquationOfMotion () const inline
GetfNoRHSCalls()
unsigned long G4MagIntegratorStepper::GetfNoRHSCalls () inline
Definition at line 113 of file G4MagIntegratorStepper.hh.
GetNumberOfStateVariables()
G4int G4MagIntegratorStepper::GetNumberOfStateVariables () const inline
Referenced by G4BogackiShampine45::G4BogackiShampine45(), G4CashKarpRKF45::G4CashKarpRKF45(), G4DormandPrince745::G4DormandPrince745(), G4SimpleRunge::G4SimpleRunge(), G4TsitourasRK45::G4TsitourasRK45(), G4RK547FEq3::makeStep(), G4RK547FEq2::makeStep(), G4RK547FEq1::makeStep(), G4BogackiShampine23::makeStep(), G4MagErrorStepper::Stepper(), and G4ConstRK4::Stepper().
GetNumberOfVariables()
G4int G4MagIntegratorStepper::GetNumberOfVariables () const inline
Referenced by G4ExplicitEuler::DumbStepper(), G4ImplicitEuler::DumbStepper(), G4ClassicalRK4::DumbStepper(), G4ChordFinder::G4ChordFinder(), G4BogackiShampine45::GetLastDydx(), G4TsitourasRK45::Interpolate(), G4DoLoMcPriRK34::Interpolate(), G4DormandPrinceRK56::Interpolate_high(), G4DormandPrince745::Interpolate_high(), G4DormandPrinceRK56::Interpolate_low(), G4DormandPrince745::Interpolate_low(), G4RK547FEq3::makeStep(), G4RK547FEq1::makeStep(), G4RK547FEq2::makeStep(), G4BogackiShampine23::makeStep(), G4BlineTracer::ResetChordFinders(), G4DormandPrinceRK56::SetupInterpolate_high(), G4DormandPrinceRK56::SetupInterpolate_low(), G4DormandPrince745::SetupInterpolation_high(), G4BogackiShampine45::SetupInterpolationHigh(), G4TsitourasRK45::Stepper(), G4DormandPrinceRK56::Stepper(), G4MagErrorStepper::Stepper(), G4BogackiShampine45::Stepper(), G4CashKarpRKF45::Stepper(), G4DormandPrince745::Stepper(), G4DormandPrinceRK78::Stepper(), G4DoLoMcPriRK34::Stepper(), and F02ElectricFieldSetup::UpdateIntegrator().
IntegrationOrder()
G4int G4MagIntegratorStepper::IntegrationOrder () inline
Definition at line 103 of file G4MagIntegratorStepper.hh.
IntegratorOrder()
virtual G4int G4MagIntegratorStepper::IntegratorOrder () const pure virtual
Implemented in G4BogackiShampine23, G4NystromRK4, G4RK547FEq1, G4RK547FEq2, G4RK547FEq3, G4DormandPrince745, G4HelixMixedStepper, G4BogackiShampine45, G4RKG3_Stepper, G4DoLoMcPriRK34, G4ConstRK4, G4ExactHelixStepper, G4HelixExplicitEuler, G4ClassicalRK4, G4TsitourasRK45, G4CashKarpRKF45, G4DormandPrinceRK78, G4HelixImplicitEuler, G4SimpleRunge, G4HelixHeum, G4SimpleHeum, G4ImplicitEuler, G4HelixSimpleRunge, G4ExplicitEuler, and G4DormandPrinceRK56.
Referenced by G4MagInt_Driver::G4MagInt_Driver(), and G4MagErrorStepper::Stepper().
IsFSAL()
bool G4MagIntegratorStepper::IsFSAL () const inline
Definition at line 118 of file G4MagIntegratorStepper.hh.
NormalisePolarizationVector()
void G4MagIntegratorStepper::NormalisePolarizationVector (G4double vec[12]) inline
Referenced by G4ClassicalRK4::DumbStepper(), and G4SimpleHeum::DumbStepper().
NormaliseTangentVector()
void G4MagIntegratorStepper::NormaliseTangentVector (G4double vec[6]) inline
operator=()
G4MagIntegratorStepper& G4MagIntegratorStepper::operator= (const G4MagIntegratorStepper &) private
ResetfNORHSCalls()
void G4MagIntegratorStepper::ResetfNORHSCalls () inline
Definition at line 115 of file G4MagIntegratorStepper.hh.
RightHandSide() [1/2]
void G4MagIntegratorStepper::RightHandSide (const G4double y[], G4double dydx[]) const inline
Referenced by G4MagInt_Driver::AccurateAdvance(), G4ImplicitEuler::DumbStepper(), G4SimpleHeum::DumbStepper(), G4ClassicalRK4::DumbStepper(), G4SimpleRunge::DumbStepper(), G4MagInt_Driver::GetDerivatives(), G4RK547FEq1::makeStep(), G4RK547FEq2::makeStep(), G4RK547FEq3::makeStep(), G4BogackiShampine23::makeStep(), G4DormandPrinceRK56::SetupInterpolate_high(), G4DormandPrinceRK56::SetupInterpolate_low(), G4DormandPrince745::SetupInterpolation_high(), G4BogackiShampine45::SetupInterpolationHigh(), G4TsitourasRK45::Stepper(), G4DormandPrinceRK56::Stepper(), G4MagErrorStepper::Stepper(), G4DormandPrince745::Stepper(), G4CashKarpRKF45::Stepper(), G4BogackiShampine45::Stepper(), G4DormandPrinceRK78::Stepper(), and G4DoLoMcPriRK34::Stepper().
RightHandSide() [2/2]
void G4MagIntegratorStepper::RightHandSide (const G4double y[], G4double dydx[], G4double field[]) const inline
SetEquationOfMotion()
void G4MagIntegratorStepper::SetEquationOfMotion (G4EquationOfMotion * newEquation) inline
Referenced by G4MagInt_Driver::SetEquationOfMotion().
SetFSAL()
void G4MagIntegratorStepper::SetFSAL (bool flag = true) inline protected
Definition at line 122 of file G4MagIntegratorStepper.hh.
Referenced by G4BogackiShampine23::G4BogackiShampine23().
SetIntegrationOrder()
void G4MagIntegratorStepper::SetIntegrationOrder (int order) inline protected
Definition at line 121 of file G4MagIntegratorStepper.hh.
Referenced by G4BogackiShampine23::G4BogackiShampine23().
Stepper()
virtual void G4MagIntegratorStepper::Stepper (const G4double y[], const G4double dydx[], G4double h, G4double yout[], G4double yerr[]) pure virtual
Implemented in G4BogackiShampine23, G4RK547FEq1, G4RK547FEq2, G4RK547FEq3, G4RKG3_Stepper, G4NystromRK4, G4HelixMixedStepper, G4DoLoMcPriRK34, G4MagHelicalStepper, G4DormandPrinceRK78, G4BogackiShampine45, G4CashKarpRKF45, G4DormandPrince745, G4ConstRK4, G4ExactHelixStepper, G4MagErrorStepper, G4DormandPrinceRK56, and G4TsitourasRK45.
Referenced by G4HelixMixedStepper::Stepper().
Field Documentation
fEquation_Rhs
G4EquationOfMotion* G4MagIntegratorStepper::fEquation_Rhs private
Definition at line 132 of file G4MagIntegratorStepper.hh.
fIntegrationOrder
int G4MagIntegratorStepper::fIntegrationOrder private
Definition at line 142 of file G4MagIntegratorStepper.hh.
Referenced by IntegrationOrder(), and SetIntegrationOrder().
fIsFSAL
bool G4MagIntegratorStepper::fIsFSAL private
Definition at line 143 of file G4MagIntegratorStepper.hh.
Referenced by IsFSAL(), and SetFSAL().
fNoIntegrationVariables
const G4int G4MagIntegratorStepper::fNoIntegrationVariables private
Definition at line 133 of file G4MagIntegratorStepper.hh.
fNoRHSCalls
unsigned long G4MagIntegratorStepper::fNoRHSCalls mutable private
Definition at line 138 of file G4MagIntegratorStepper.hh.
Referenced by GetfNoRHSCalls(), and ResetfNORHSCalls().
fNoStateVariables
const G4int G4MagIntegratorStepper::fNoStateVariables private
Definition at line 134 of file G4MagIntegratorStepper.hh.
The documentation for this class was generated from the following files:
source/geometry/magneticfield/include/G4MagIntegratorStepper.hh
source/geometry/magneticfield/src/G4MagIntegratorStepper.cc