Geant4: G4MaterialCutsCouple Class Reference
G4MaterialCutsCouple Class Reference
#include <G4MaterialCutsCouple.hh>
Public Member Functions
G4MaterialCutsCouple ()
G4MaterialCutsCouple (const G4Material *, G4ProductionCuts *cut=0)
G4MaterialCutsCouple (const G4MaterialCutsCouple &right)
G4MaterialCutsCouple & operator= (const G4MaterialCutsCouple &right)
virtual ~G4MaterialCutsCouple ()
G4bool operator== (const G4MaterialCutsCouple &right) const
G4bool operator!= (const G4MaterialCutsCouple &right) const
void SetMaterial (const G4Material *)
const G4Material * GetMaterial () const
void SetProductionCuts (G4ProductionCuts *)
G4ProductionCuts * GetProductionCuts () const
G4bool IsRecalcNeeded () const
void PhysicsTableUpdated ()
void SetIndex (G4int idx)
G4int GetIndex () const
void SetUseFlag (G4bool flg=true)
G4bool IsUsed () const
Private Attributes
G4bool isMaterialModified
const G4Material * fMaterial
G4ProductionCuts * fCuts
G4int indexNumber
G4bool isUsedInGeometry
Detailed Description
Definition at line 49 of file G4MaterialCutsCouple.hh.
Constructor & Destructor Documentation
G4MaterialCutsCouple() [1/3]
G4MaterialCutsCouple::G4MaterialCutsCouple ()
Definition at line 40 of file G4MaterialCutsCouple.cc.
G4MaterialCutsCouple() [2/3]
G4MaterialCutsCouple::G4MaterialCutsCouple (const G4Material * material, G4ProductionCuts * cut = 0)
Definition at line 49 of file G4MaterialCutsCouple.cc.
G4MaterialCutsCouple() [3/3]
G4MaterialCutsCouple::G4MaterialCutsCouple (const G4MaterialCutsCouple & right)
Definition at line 60 of file G4MaterialCutsCouple.cc.
~G4MaterialCutsCouple()
G4MaterialCutsCouple::~G4MaterialCutsCouple () virtual
Definition at line 66 of file G4MaterialCutsCouple.cc.
Member Function Documentation
GetIndex()
G4int G4MaterialCutsCouple::GetIndex () const inline
Definition at line 110 of file G4MaterialCutsCouple.hh.
Referenced by G4NuclearStopping::AlongStepDoIt(), G4VMultipleScattering::AlongStepGetPhysicalInteractionLength(), G4RDShellVacancy::AverageNOfIonisations(), G4ShellVacancy::AverageNOfIonisations(), G4SBBremTable::BuildSamplingTables(), G4AdjointCSManager::BuildTotalSigmaTables(), G4ProductionCutsTable::CheckMaterialCutsCoupleInfo(), G4mplIonisationWithDeltaModel::ComputeDEDXPerVolume(), G4mplIonisationModel::ComputeDEDXPerVolume(), G4GoudsmitSaundersonTable::ComputeScatteringPowerCorrection(), G4AdjointCSManager::ComputeTotalAdjointCS(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4VEmAdjointModel::DefineCurrentMaterial(), G4AdjointCSManager::DefineCurrentMaterial(), G4AdjointPhotoElectricModel::DefineCurrentMaterialAndElectronEnergy(), G4WentzelVIRelModel::DefineMaterial(), G4AdjointAlongStepWeightCorrection::DefineMaterial(), G4eSingleCoulombScatteringModel::DefineMaterial(), G4IonCoulombScatteringModel::DefineMaterial(), G4hCoulombScatteringModel::DefineMaterial(), G4ContinuousGainOfEnergy::DefineMaterial(), G4WentzelVIModel::DefineMaterial(), G4eCoulombScatteringModel::DefineMaterial(), G4VEmProcess::DefineMaterial(), G4VEnergyLossProcess::DefineMaterial(), G4hImpactIonisation::DeltaRaysEnergy(), G4ProductionCutsTable::DumpCouples(), G4EmModelManager::FillDEDXVector(), G4EmModelManager::FillLambdaVector(), G4ForwardXrayTR::G4ForwardXrayTR(), G4EmCalculator::GetCrossSectionPerVolume(), G4EnergyLossTables::GetDEDX(), G4RDVeLowEnergyLoss::GetLossWithFluct(), G4LowEnergyRayleigh::GetMeanFreePath(), G4LowEnergyCompton::GetMeanFreePath(), G4LowEnergyGammaConversion::GetMeanFreePath(), G4hImpactIonisation::GetMeanFreePath(), G4LowEnergyPolarizedCompton::GetMeanFreePath(), G4EnergyLossTables::GetPreciseDEDX(), G4EnergyLossTables::GetPreciseEnergyFromRange(), G4EnergyLossTables::GetPreciseRangeFromEnergy(), G4EnergyLossTables::GetRange(), G4VMscModel::GetTransportMeanFreePath(), G4PAIPhotModel::Initialise(), G4PAIModel::Initialise(), G4GoudsmitSaundersonTable::InitSCPCorrection(), G4EmCorrections::IonHighOrderCorrections(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4LowEnergyBremsstrahlung::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4hImpactIonisation::PrintInfoDefinition(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4LivermoreComptonModifiedModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), G4LivermorePhotoElectricModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4PEEffectFluoModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), G4eplusTo2GammaOKVIModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4PenelopeIonisationModel::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), G4LowEPPolarizedComptonModel::SampleSecondaries(), G4RDVCrossSectionHandler::SelectRandomAtom(), G4VCrossSectionHandler::SelectRandomAtom(), G4VEmModel::SelectRandomAtom(), G4RDVCrossSectionHandler::SelectRandomElement(), G4VCrossSectionHandler::SelectRandomElement(), G4ProductionCutsTable::StoreMaterialCutsCoupleInfo(), G4GammaGeneralProcess::TotalCrossSectionPerVolume(), and G4EmCalculator::UpdateCouple().
GetMaterial()
const G4Material * G4MaterialCutsCouple::GetMaterial () const inline
Definition at line 149 of file G4MaterialCutsCouple.hh.
Referenced by G4AdjointBremsstrahlungModel::AdjointCrossSection(), G4NuclearStopping::AlongStepDoIt(), G4hImpactIonisation::AlongStepDoIt(), G4hImpactIonisation::AntiProtonParametrisedDEDX(), G4CrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDBremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDeIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4BremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4eIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4VEnergyLossProcess::BuildLambdaTable(), G4hImpactIonisation::BuildLambdaTable(), G4VEmProcess::BuildLambdaTable(), G4LowEnergyBremsstrahlung::BuildLossTable(), G4LowEnergyIonisation::BuildLossTable(), G4hImpactIonisation::BuildLossTable(), G4hImpactIonisation::BuildPhysicsTable(), G4GammaGeneralProcess::BuildPhysicsTable(), G4SBBremTable::BuildSamplingTables(), G4LossTableBuilder::BuildTableForModel(), G4AdjointCSManager::BuildTotalSigmaTables(), G4ForwardXrayTR::BuildXrayTRtables(), G4ProductionCutsTable::CheckMaterialCutsCoupleInfo(), G4PEEffectFluoModel::ComputeCrossSectionPerAtom(), G4hImpactIonisation::ComputeDEDX(), G4VEmModel::ComputeDEDX(), G4WentzelVIRelModel::ComputeEffectiveMass(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), G4AtimaEnergyLossModel::CorrectionsAlongStep(), G4LindhardSorensenIonModel::CorrectionsAlongStep(), G4BetheBlochModel::CorrectionsAlongStep(), G4BraggIonModel::CorrectionsAlongStep(), G4VEmModel::CrossSection(), G4LowEnergyIonisation::DeexciteAtom(), G4VEmAdjointModel::DefineCurrentMaterial(), G4AdjointCSManager::DefineCurrentMaterial(), G4AdjointPhotoElectricModel::DefineCurrentMaterialAndElectronEnergy(), G4WentzelVIRelModel::DefineMaterial(), G4AdjointAlongStepWeightCorrection::DefineMaterial(), G4eSingleCoulombScatteringModel::DefineMaterial(), G4IonCoulombScatteringModel::DefineMaterial(), G4hCoulombScatteringModel::DefineMaterial(), G4ContinuousGainOfEnergy::DefineMaterial(), G4WentzelVIModel::DefineMaterial(), G4eCoulombScatteringModel::DefineMaterial(), G4VEmProcess::DefineMaterial(), G4VEnergyLossProcess::DefineMaterial(), G4hImpactIonisation::DeltaRaysEnergy(), G4ProductionCutsTable::DumpCouples(), G4EmModelManager::FillDEDXVector(), G4EmModelManager::FillLambdaVector(), G4ForwardXrayTR::G4ForwardXrayTR(), G4InitXscPAI::G4InitXscPAI(), G4PAIxSection::G4PAIxSection(), G4RDShellVacancy::GenerateNumberOfIonisations(), G4ShellVacancy::GenerateNumberOfIonisations(), G4AdjointBremsstrahlungModel::GetAdjointCrossSection(), G4hImpactIonisation::GetConstraints(), RunAction::GetCuts(), G4VMscModel::GetEnergy(), RunAction::GetEnergyCut(), G4ForwardXrayTR::GetEnergyTR(), G4RDVeLowEnergyLoss::GetLossWithFluct(), G4hImpactIonisation::GetMeanFreePath(), G4ScreenedNuclearRecoil::GetMeanFreePath(), G4VMscModel::GetRange(), G4GoudsmitSaundersonMscModel::GetTransportMeanFreePath(), G4GoudsmitSaundersonMscModel::GetTransportMeanFreePathOnly(), G4GSPWACorrections::InitDataPerElement(), G4GSPWACorrections::InitDataPerMaterials(), G4LivermoreNuclearGammaConversionModel::Initialise(), G4LivermoreRayleighModel::Initialise(), G4LivermoreGammaConversionModelRC::Initialise(), G4BoldyshevTripletModel::Initialise(), G4LivermorePolarizedGammaConversionModel::Initialise(), G4LivermorePolarizedPhotoElectricGDModel::Initialise(), G4LivermoreGammaConversionModel::Initialise(), G4LivermoreComptonModel::Initialise(), G4LivermorePhotoElectricModel::Initialise(), G4LivermorePolarizedPhotoElectricModel::Initialise(), G4LivermorePolarizedRayleighModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4JAEAElasticScatteringModel::Initialise(), G4PenelopeGammaConversionModel::Initialise(), G4PenelopeRayleighModel::Initialise(), G4mplIonisationModel::Initialise(), G4mplIonisationWithDeltaModel::Initialise(), G4PenelopePhotoElectricModel::Initialise(), G4PenelopeBremsstrahlungModel::Initialise(), G4PAIPhotData::Initialise(), G4PenelopeIonisationModel::Initialise(), G4PAIModelData::Initialise(), G4LowEPComptonModel::Initialise(), G4LowEPPolarizedComptonModel::Initialise(), G4EmModelManager::Initialise(), G4LossTableBuilder::InitialiseBaseMaterials(), G4LossTableBuilder::InitialiseCouples(), G4VEmModel::InitialiseElementSelectors(), G4EmCorrections::InitialiseForNewRun(), G4PenelopeBremsstrahlungModel::InitialiseLocal(), G4LivermoreGammaConversionModel::InitialiseProbability(), G4GSMottCorrection::InitMCDataPerElement(), G4GSMottCorrection::InitMCDataPerMaterials(), G4GoudsmitSaundersonTable::InitSCPCorrection(), G4EmCorrections::IonHighOrderCorrections(), G4ProductionCutsTable::IsCoupleUsedInTheRegion(), G4AtimaEnergyLossModel::MinEnergyCut(), G4LindhardSorensenIonModel::MinEnergyCut(), G4BetheBlochModel::MinEnergyCut(), G4MuBetheBlochModel::MinEnergyCut(), G4BraggIonModel::MinEnergyCut(), G4mplIonisationWithDeltaModel::MinEnergyCut(), G4Transportation::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4ITTransportation::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4ScreenedNuclearRecoil::PostStepDoIt(), G4GammaGeneralProcess::PostStepGetPhysicalInteractionLength(), G4hImpactIonisation::PrintInfoDefinition(), G4hImpactIonisation::ProtonParametrisedDEDX(), G4UrbanMscModel::SampleCosineTheta(), G4UrbanAdjointMscModel::SampleCosineTheta(), G4UniversalFluctuation::SampleFluctuations(), G4BohrFluctuations::SampleFluctuations(), G4AtimaFluctuations::SampleFluctuations(), G4IonFluctuations::SampleFluctuations(), G4mplIonisationModel::SampleFluctuations(), G4mplIonisationWithDeltaModel::SampleFluctuations(), G4LEPTSRotExcitationModel::SampleSecondaries(), G4LEPTSElasticModel::SampleSecondaries(), G4LEPTSVibExcitationModel::SampleSecondaries(), G4LEPTSDissociationModel::SampleSecondaries(), G4LEPTSPositroniumModel::SampleSecondaries(), G4LEPTSIonisationModel::SampleSecondaries(), G4LEPTSExcitationModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4DNARuddIonisationModel::SampleSecondaries(), G4LivermoreRayleighModel::SampleSecondaries(), G4DNARuddIonisationExtendedModel::SampleSecondaries(), G4DNABornIonisationModel1::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4LivermoreComptonModifiedModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4LivermorePhotoElectricModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), G4PenelopeGammaConversionModel::SampleSecondaries(), G4PenelopeRayleighModel::SampleSecondaries(), G4LivermoreIonisationModel::SampleSecondaries(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4PEEffectFluoModel::SampleSecondaries(), G4MicroElecInelasticModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), G4eBremParametrizedModel::SampleSecondaries(), G4PairProductionRelModel::SampleSecondaries(), G4PAIPhotModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4PenelopeBremsstrahlungModel::SampleSecondaries(), G4PenelopeIonisationModel::SampleSecondaries(), G4PAIModel::SampleSecondaries(), G4MollerBhabhaModel::SampleSecondaries(), G4DNAModelInterface::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), G4ICRU73QOModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), G4BetheBlochModel::SampleSecondaries(), G4LowEPPolarizedComptonModel::SampleSecondaries(), G4IonParametrisedLossModel::SampleSecondaries(), G4ProductionCutsTable::ScanAndSetCouple(), G4RDVCrossSectionHandler::SelectRandomAtom(), G4VCrossSectionHandler::SelectRandomAtom(), G4VEmModel::SelectRandomAtom(), G4RDVCrossSectionHandler::SelectRandomElement(), G4VCrossSectionHandler::SelectRandomElement(), G4ScreenedCoulombCrossSection::SelectRandomUnweightedTarget(), G4ProductionCutsTable::StoreMaterialCutsCoupleInfo(), G4VEmModel::Value(), and G4EmSaturation::VisibleEnergyDeposition().
GetProductionCuts()
G4ProductionCuts * G4MaterialCutsCouple::GetProductionCuts () const inline
Definition at line 126 of file G4MaterialCutsCouple.hh.
Referenced by G4VEnergyLossProcess::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepGetPhysicalInteractionLength(), G4ProductionCutsTable::CheckMaterialCutsCoupleInfo(), G4WentzelVIModel::ComputeTruePathLengthLimit(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4ContinuousGainOfEnergy::DefineMaterial(), G4ProductionCutsTable::DumpCouples(), G4RDRangeTest::Escape(), G4hImpactIonisation::GetConstraints(), G4EmBiasingManager::Initialise(), G4EmModelManager::Initialise(), G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), G4LossTableBuilder::InitialiseBaseMaterials(), G4LossTableBuilder::InitialiseCouples(), G4ProductionCutsTable::IsCoupleUsedInTheRegion(), G4Transportation::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), G4ITTransportation::PostStepDoIt(), G4VEnergyLossProcess::PreparePhysicsTable(), G4ProductionCutsTable::StoreMaterialCutsCoupleInfo(), and G4ParallelWorldProcess::SwitchMaterial().
IsRecalcNeeded()
G4bool G4MaterialCutsCouple::IsRecalcNeeded () const inline
Definition at line 155 of file G4MaterialCutsCouple.hh.
Referenced by G4hRDEnergyLoss::CutsWhereModified(), and G4PhysicsTableHelper::PreparePhysicsTable().
IsUsed()
G4bool G4MaterialCutsCouple::IsUsed () const inline
Definition at line 118 of file G4MaterialCutsCouple.hh.
Referenced by G4SBBremTable::BuildSamplingTables(), G4ProductionCutsTable::CheckMaterialCutsCoupleInfo(), G4ProductionCutsTable::DumpCouples(), G4GSPWACorrections::InitDataPerElement(), G4GSPWACorrections::InitDataPerMaterials(), G4GSMottCorrection::InitMCDataPerElement(), G4GSMottCorrection::InitMCDataPerMaterials(), G4PhysicsTableHelper::PreparePhysicsTable(), and G4ProductionCutsTable::StoreMaterialCutsCoupleInfo().
operator!=()
G4bool G4MaterialCutsCouple::operator!= (const G4MaterialCutsCouple & right) const inline
Definition at line 136 of file G4MaterialCutsCouple.hh.
operator=()
G4MaterialCutsCouple & G4MaterialCutsCouple::operator= (const G4MaterialCutsCouple & right)
Definition at line 70 of file G4MaterialCutsCouple.cc.
operator==()
G4bool G4MaterialCutsCouple::operator== (const G4MaterialCutsCouple & right) const inline
Definition at line 130 of file G4MaterialCutsCouple.hh.
PhysicsTableUpdated()
void G4MaterialCutsCouple::PhysicsTableUpdated () inline
Definition at line 163 of file G4MaterialCutsCouple.hh.
SetIndex()
void G4MaterialCutsCouple::SetIndex (G4int idx) inline
Definition at line 106 of file G4MaterialCutsCouple.hh.
Referenced by G4ProductionCutsTable::UpdateCoupleTable().
SetMaterial()
void G4MaterialCutsCouple::SetMaterial (const G4Material * material) inline
Definition at line 142 of file G4MaterialCutsCouple.hh.
SetProductionCuts()
void G4MaterialCutsCouple::SetProductionCuts (G4ProductionCuts * aCut) inline
Definition at line 122 of file G4MaterialCutsCouple.hh.
SetUseFlag()
void G4MaterialCutsCouple::SetUseFlag (G4bool flg = true) inline
Definition at line 114 of file G4MaterialCutsCouple.hh.
Referenced by G4ProductionCutsTable::UpdateCoupleTable().
Field Documentation
fCuts
G4ProductionCuts* G4MaterialCutsCouple::fCuts private
Definition at line 99 of file G4MaterialCutsCouple.hh.
Referenced by GetProductionCuts(), IsRecalcNeeded(), operator=(), PhysicsTableUpdated(), and SetProductionCuts().
fMaterial
const G4Material* G4MaterialCutsCouple::fMaterial private
Definition at line 98 of file G4MaterialCutsCouple.hh.
Referenced by GetMaterial(), operator=(), and SetMaterial().
indexNumber
G4int G4MaterialCutsCouple::indexNumber private
Definition at line 100 of file G4MaterialCutsCouple.hh.
Referenced by GetIndex(), operator=(), and SetIndex().
isMaterialModified
G4bool G4MaterialCutsCouple::isMaterialModified private
Definition at line 97 of file G4MaterialCutsCouple.hh.
Referenced by IsRecalcNeeded(), operator=(), PhysicsTableUpdated(), and SetMaterial().
isUsedInGeometry
G4bool G4MaterialCutsCouple::isUsedInGeometry private
Definition at line 101 of file G4MaterialCutsCouple.hh.
Referenced by IsUsed(), operator=(), and SetUseFlag().
The documentation for this class was generated from the following files:
source/processes/cuts/include/G4MaterialCutsCouple.hh
source/processes/cuts/src/G4MaterialCutsCouple.cc