Geant4: G4VNestedParameterisation Class Reference
G4VNestedParameterisation Class Reference abstract
#include <G4VNestedParameterisation.hh>
Public Member Functions
G4VNestedParameterisation ()
virtual ~G4VNestedParameterisation ()
virtual G4Material * ComputeMaterial (G4VPhysicalVolume *currentVol, const G4int repNo, const G4VTouchable *parentTouch=0)=0
virtual G4int GetNumberOfMaterials () const =0
virtual G4Material * GetMaterial (G4int idx) const =0
virtual void ComputeTransformation (const G4int no, G4VPhysicalVolume *currentPV) const =0
virtual G4VSolid * ComputeSolid (const G4int no, G4VPhysicalVolume *thisVol)
virtual void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=0)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
Public Member Functions inherited from G4VVolumeMaterialScanner
G4VVolumeMaterialScanner ()
virtual ~G4VVolumeMaterialScanner ()
Detailed Description
Definition at line 78 of file G4VNestedParameterisation.hh.
Constructor & Destructor Documentation
G4VNestedParameterisation()
G4VNestedParameterisation::G4VNestedParameterisation ()
Definition at line 38 of file G4VNestedParameterisation.cc.
~G4VNestedParameterisation()
G4VNestedParameterisation::~G4VNestedParameterisation () virtual
Definition at line 44 of file G4VNestedParameterisation.cc.
Member Function Documentation
ComputeDimensions() [1/13]
virtual void G4VNestedParameterisation::ComputeDimensions (G4Box & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 111 of file G4VNestedParameterisation.hh.
Referenced by G4GMocrenFileSceneHandler::AddSolid().
ComputeDimensions() [2/13]
virtual void G4VNestedParameterisation::ComputeDimensions (G4Cons & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 127 of file G4VNestedParameterisation.hh.
ComputeDimensions() [3/13]
virtual void G4VNestedParameterisation::ComputeDimensions (G4Ellipsoid & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 139 of file G4VNestedParameterisation.hh.
ComputeDimensions() [4/13]
virtual void G4VNestedParameterisation::ComputeDimensions (G4Hype & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 159 of file G4VNestedParameterisation.hh.
ComputeDimensions() [5/13]
virtual void G4VNestedParameterisation::ComputeDimensions (G4Orb & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 135 of file G4VNestedParameterisation.hh.
ComputeDimensions() [6/13]
virtual void G4VNestedParameterisation::ComputeDimensions (G4Para & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 147 of file G4VNestedParameterisation.hh.
ComputeDimensions() [7/13]
virtual void G4VNestedParameterisation::ComputeDimensions (G4Polycone & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 151 of file G4VNestedParameterisation.hh.
ComputeDimensions() [8/13]
virtual void G4VNestedParameterisation::ComputeDimensions (G4Polyhedra & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 155 of file G4VNestedParameterisation.hh.
ComputeDimensions() [9/13]
virtual void G4VNestedParameterisation::ComputeDimensions (G4Sphere & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 131 of file G4VNestedParameterisation.hh.
ComputeDimensions() [10/13]
virtual void G4VNestedParameterisation::ComputeDimensions (G4Torus & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 143 of file G4VNestedParameterisation.hh.
ComputeDimensions() [11/13]
virtual void G4VNestedParameterisation::ComputeDimensions (G4Trap & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 123 of file G4VNestedParameterisation.hh.
ComputeDimensions() [12/13]
virtual void G4VNestedParameterisation::ComputeDimensions (G4Trd & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 119 of file G4VNestedParameterisation.hh.
ComputeDimensions() [13/13]
virtual void G4VNestedParameterisation::ComputeDimensions (G4Tubs & , const G4int, const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 115 of file G4VNestedParameterisation.hh.
ComputeMaterial() [1/2]
G4Material * G4VNestedParameterisation::ComputeMaterial (const G4int repNo, G4VPhysicalVolume * currentVol, const G4VTouchable * parentTouch = 0) virtual
Reimplemented from G4VPVParameterisation.
Definition at line 65 of file G4VNestedParameterisation.cc.
ComputeMaterial() [2/2]
virtual G4Material* G4VNestedParameterisation::ComputeMaterial (G4VPhysicalVolume * currentVol, const G4int repNo, const G4VTouchable * parentTouch = 0) pure virtual
Implemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Referenced by G4GMocrenFileSceneHandler::AddSolid(), and ComputeMaterial().
ComputeSolid()
G4VSolid * G4VNestedParameterisation::ComputeSolid (const G4int no, G4VPhysicalVolume * thisVol) virtual
Reimplemented from G4VPVParameterisation.
Definition at line 48 of file G4VNestedParameterisation.cc.
ComputeTransformation()
virtual void G4VNestedParameterisation::ComputeTransformation (const G4int no, G4VPhysicalVolume * currentPV) const pure virtual
Implements G4VPVParameterisation.
Implemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Referenced by G4GMocrenFileSceneHandler::AddSolid().
GetMaterial()
virtual G4Material* G4VNestedParameterisation::GetMaterial (G4int idx) const pure virtual
Implements G4VVolumeMaterialScanner.
Implemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
GetMaterialScanner()
G4VVolumeMaterialScanner * G4VNestedParameterisation::GetMaterialScanner () virtual
Reimplemented from G4VPVParameterisation.
Definition at line 59 of file G4VNestedParameterisation.cc.
GetNumberOfMaterials()
virtual G4int G4VNestedParameterisation::GetNumberOfMaterials () const pure virtual
Implements G4VVolumeMaterialScanner.
Implemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
IsNested()
G4bool G4VNestedParameterisation::IsNested () const virtual
Reimplemented from G4VPVParameterisation.
Definition at line 54 of file G4VNestedParameterisation.cc.
The documentation for this class was generated from the following files:
source/geometry/management/include/G4VNestedParameterisation.hh
source/geometry/management/src/G4VNestedParameterisation.cc