Geant4: G4DensityEffectData Class Reference
G4DensityEffectData Class Reference
#include <G4DensityEffectData.hh>
Public Member Functions
G4DensityEffectData ()
~G4DensityEffectData ()
G4int GetElementIndex (G4int Z, G4State mState) const
G4int GetIndex (const G4String &matName) const
void PrintData (const G4String &matName) const
void DumpData () const
G4double GetPlasmaEnergy (G4int idx) const
G4double GetAdjustmentFactor (G4int idx) const
G4double GetCdensity (G4int idx) const
G4double GetX0density (G4int idx) const
G4double GetX1density (G4int idx) const
G4double GetAdensity (G4int idx) const
G4double GetMdensity (G4int idx) const
G4double GetDelta0density (G4int idx) const
G4double GetErrorDensity (G4int idx) const
G4double GetMeanIonisationPotential (G4int idx) const
Private Member Functions
void Initialize ()
void AddMaterial (G4double *val, const G4String &matName)
G4DensityEffectData & operator= (const G4DensityEffectData &right)=delete
G4DensityEffectData (const G4DensityEffectData &)=delete
Private Attributes
G4double data [NDENSDATA][NDENSARRAY]
std::vector< G4String > names
G4int indexZ [NDENSELEM]
G4State state [NDENSELEM]
G4int index
Detailed Description
Definition at line 60 of file G4DensityEffectData.hh.
Constructor & Destructor Documentation
G4DensityEffectData() [1/2]
G4DensityEffectData::G4DensityEffectData () explicit
Definition at line 52 of file G4DensityEffectData.cc.
~G4DensityEffectData()
G4DensityEffectData::~G4DensityEffectData ()
Definition at line 59 of file G4DensityEffectData.cc.
G4DensityEffectData() [2/2]
G4DensityEffectData::G4DensityEffectData (const G4DensityEffectData &) private delete
Member Function Documentation
AddMaterial()
void G4DensityEffectData::AddMaterial (G4double * val, const G4String & matName) private
Definition at line 1324 of file G4DensityEffectData.cc.
Referenced by Initialize().
DumpData()
void G4DensityEffectData::DumpData () const
Definition at line 1361 of file G4DensityEffectData.cc.
Referenced by PrintData().
GetAdensity()
G4double G4DensityEffectData::GetAdensity (G4int idx) const inline
Definition at line 138 of file G4DensityEffectData.hh.
Referenced by G4IonisParamMat::ComputeDensityEffect().
GetAdjustmentFactor()
G4double G4DensityEffectData::GetAdjustmentFactor (G4int idx) const inline
Definition at line 118 of file G4DensityEffectData.hh.
Referenced by G4IonisParamMat::ComputeDensityEffect().
GetCdensity()
G4double G4DensityEffectData::GetCdensity (G4int idx) const inline
Definition at line 123 of file G4DensityEffectData.hh.
Referenced by G4IonisParamMat::ComputeDensityEffect().
GetDelta0density()
G4double G4DensityEffectData::GetDelta0density (G4int idx) const inline
Definition at line 148 of file G4DensityEffectData.hh.
Referenced by G4IonisParamMat::ComputeDensityEffect().
GetElementIndex()
G4int G4DensityEffectData::GetElementIndex (G4int Z, G4State mState) const
Definition at line 1301 of file G4DensityEffectData.cc.
Referenced by G4IonisParamMat::ComputeDensityEffect(), and G4ICRU73QOModel::GetOscillatorEnergy().
GetErrorDensity()
G4double G4DensityEffectData::GetErrorDensity (G4int idx) const inline
Definition at line 153 of file G4DensityEffectData.hh.
GetIndex()
G4int G4DensityEffectData::GetIndex (const G4String & matName) const
Definition at line 1311 of file G4DensityEffectData.cc.
Referenced by G4IonisParamMat::ComputeDensityEffect(), G4IonisParamMat::FindMeanExcitationEnergy(), and PrintData().
GetMdensity()
G4double G4DensityEffectData::GetMdensity (G4int idx) const inline
Definition at line 143 of file G4DensityEffectData.hh.
Referenced by G4IonisParamMat::ComputeDensityEffect().
GetMeanIonisationPotential()
G4double G4DensityEffectData::GetMeanIonisationPotential (G4int idx) const inline
Definition at line 158 of file G4DensityEffectData.hh.
Referenced by G4IonisParamMat::FindMeanExcitationEnergy().
GetPlasmaEnergy()
G4double G4DensityEffectData::GetPlasmaEnergy (G4int idx) const inline
Definition at line 113 of file G4DensityEffectData.hh.
Referenced by G4IonisParamMat::ComputeDensityEffect(), and G4ICRU73QOModel::GetOscillatorEnergy().
GetX0density()
G4double G4DensityEffectData::GetX0density (G4int idx) const inline
Definition at line 128 of file G4DensityEffectData.hh.
Referenced by G4IonisParamMat::ComputeDensityEffect().
GetX1density()
G4double G4DensityEffectData::GetX1density (G4int idx) const inline
Definition at line 133 of file G4DensityEffectData.hh.
Referenced by G4IonisParamMat::ComputeDensityEffect().
Initialize()
void G4DensityEffectData::Initialize () private
Definition at line 63 of file G4DensityEffectData.cc.
Referenced by G4DensityEffectData().
operator=()
G4DensityEffectData& G4DensityEffectData::operator= (const G4DensityEffectData & right) private delete
PrintData()
void G4DensityEffectData::PrintData (const G4String & matName) const
Definition at line 1335 of file G4DensityEffectData.cc.
Referenced by G4NistMessenger::SetNewValue().
Field Documentation
data
G4double G4DensityEffectData::data[NDENSDATA][NDENSARRAY] private
Definition at line 102 of file G4DensityEffectData.hh.
Referenced by AddMaterial(), DumpData(), GetAdensity(), GetAdjustmentFactor(), GetCdensity(), GetDelta0density(), GetErrorDensity(), GetMdensity(), GetMeanIonisationPotential(), GetPlasmaEnergy(), GetX0density(), GetX1density(), and PrintData().
index
G4int G4DensityEffectData::index private
Definition at line 109 of file G4DensityEffectData.hh.
Referenced by AddMaterial().
indexZ
G4int G4DensityEffectData::indexZ[NDENSELEM] private
Definition at line 106 of file G4DensityEffectData.hh.
Referenced by GetElementIndex(), and Initialize().
names
std::vector<G4String> G4DensityEffectData::names private
Definition at line 103 of file G4DensityEffectData.hh.
Referenced by AddMaterial(), DumpData(), and GetIndex().
state
G4State G4DensityEffectData::state[NDENSELEM] private
Definition at line 107 of file G4DensityEffectData.hh.
Referenced by GetElementIndex(), and Initialize().
The documentation for this class was generated from the following files:
source/materials/include/G4DensityEffectData.hh
source/materials/src/G4DensityEffectData.cc