Geant4: G4INCL::RootFinder Namespace Reference
G4INCL::RootFinder Namespace Reference
Data Structures
class Solution
Functions
Solution solve (RootFunctor const *const f, const G4double x0)
Numerically solve a one-dimensional equation.
Function Documentation
solve()
Solution G4INCL::RootFinder::solve (RootFunctor const *const f, const G4double x0)
Numerically solve a one-dimensional equation.
Numerically solves the equation f(x)==0. This implementation uses the false-position method.
If a root is found, it can be retrieved using the getSolution() method,
Parameters
f pointer to a RootFunctor
x0 initial value of the function argument
Returns
a Solution object describing the root, if it was found
Definition at line 118 of file G4INCLRootFinder.cc.
Referenced by G4INCL::InteractionAvatar::enforceEnergyConservation(), G4INCL::ParticleEntryChannel::particleEnters(), and G4INCL::INCL::rescaleOutgoingForRecoil().