Geant4: G4ForEach< group > Class Template Reference
G4ForEach< group > Class Template Reference
#include <G4Pair.hh>
Static Public Member Functions
template<class T1 , class functor >
static void Apply (functor *aFP, T1 *aT1=0)
template<class functor >
static void Apply ()
Static Private Member Functions
template<class T1 >
static void ActOn (T1 *aT1, VCall< T1 > *aV)
Detailed Description
template<class group>
class G4ForEach< group >
Definition at line 163 of file G4Pair.hh.
Member Function Documentation
ActOn()
template<class group > template<class T1 > static void G4ForEach< group >::ActOn (T1 * aT1, VCall< T1 > * aV) inline static private
Definition at line 166 of file G4Pair.hh.
Apply() [1/2]
template<class group > template<class functor > static void G4ForEach< group >::Apply () inline static
Definition at line 179 of file G4Pair.hh.
Referenced by G4ForEach< group >::Apply(), G4CollisionNN::G4CollisionNN(), G4CollisionNNToDeltaDelta::G4CollisionNNToDeltaDelta(), G4CollisionNNToDeltaDeltastar::G4CollisionNNToDeltaDeltastar(), G4CollisionNNToNDeltastar::G4CollisionNNToNDeltastar(), G4CollisionPN::G4CollisionPN(), G4Scatterer::G4Scatterer(), G4GeneralNNCollision::MakeNNToNDelta< dm, d0, dp, dpp, channelType >::Make(), G4GeneralNNCollision::MakeNNToNNStar< Np, Nn, channelType >::Make(), G4GeneralNNCollision::MakeNNStarToNN< channelType, Np, Nn >::Make(), G4GeneralNNCollision::MakeNNToDeltaNstar< Np, channelType, Nn >::Make(), and G4GeneralNNCollision::MakeNNToDeltaDelta< dm, d0, dp, dpp, channelType >::Make().
Apply() [2/2]
template<class group > template<class T1 , class functor > static void G4ForEach< group >::Apply (functor * aFP, T1 * aT1 = 0) inline static
Definition at line 171 of file G4Pair.hh.
The documentation for this class was generated from the following file:
source/processes/hadronic/util/include/G4Pair.hh