Geant4: G4LogicalSurface Class Reference
G4LogicalSurface Class Reference
#include <G4LogicalSurface.hh>
Public Member Functions
G4SurfaceProperty * GetSurfaceProperty () const
void SetSurfaceProperty (G4SurfaceProperty *ptrSurfaceProperty)
const G4String & GetName () const
void SetName (const G4String &name)
G4TransitionRadiationSurface * GetTransitionRadiationSurface () const
void SetTransitionRadiationSurface (G4TransitionRadiationSurface *tRadSurf)
virtual ~G4LogicalSurface ()
G4bool operator== (const G4LogicalSurface &right) const
G4bool operator!= (const G4LogicalSurface &right) const
Protected Member Functions
G4LogicalSurface (const G4String &name, G4SurfaceProperty *prop)
Private Member Functions
G4LogicalSurface (const G4LogicalSurface &right)
G4LogicalSurface & operator= (const G4LogicalSurface &right)
Private Attributes
G4String theName
G4SurfaceProperty * theSurfaceProperty
G4TransitionRadiationSurface * theTransRadSurface
Detailed Description
Definition at line 78 of file G4LogicalSurface.hh.
Constructor & Destructor Documentation
~G4LogicalSurface()
G4LogicalSurface::~G4LogicalSurface () virtual
Definition at line 50 of file G4LogicalSurface.cc.
G4LogicalSurface() [1/2]
G4LogicalSurface::G4LogicalSurface (const G4String & name, G4SurfaceProperty * prop) protected
Definition at line 38 of file G4LogicalSurface.cc.
G4LogicalSurface() [2/2]
G4LogicalSurface::G4LogicalSurface (const G4LogicalSurface & right) private
Definition at line 44 of file G4LogicalSurface.cc.
Member Function Documentation
GetName()
const G4String& G4LogicalSurface::GetName () const inline
Referenced by G4GDMLWriteStructure::BorderSurfaceCache(), G4LogicalSkinSurface::DumpInfo(), G4LogicalBorderSurface::DumpInfo(), and G4GDMLWriteStructure::SkinSurfaceCache().
GetSurfaceProperty()
G4SurfaceProperty* G4LogicalSurface::GetSurfaceProperty () const inline
Referenced by G4GDMLWriteStructure::BorderSurfaceCache(), OpNoviceDetectorConstruction::Construct(), G4OpBoundaryProcess::PostStepDoIt(), and G4GDMLWriteStructure::SkinSurfaceCache().
GetTransitionRadiationSurface()
G4TransitionRadiationSurface* G4LogicalSurface::GetTransitionRadiationSurface () const inline
operator!=()
G4bool G4LogicalSurface::operator!= (const G4LogicalSurface & right) const inline
operator=()
G4LogicalSurface& G4LogicalSurface::operator= (const G4LogicalSurface & right) inline private
operator==()
G4bool G4LogicalSurface::operator== (const G4LogicalSurface & right) const inline
SetName()
void G4LogicalSurface::SetName (const G4String & name) inline
Referenced by G4LogicalSkinSurface::operator=(), and G4LogicalBorderSurface::operator=().
SetSurfaceProperty()
void G4LogicalSurface::SetSurfaceProperty (G4SurfaceProperty * ptrSurfaceProperty) inline
Referenced by G4LogicalSkinSurface::operator=(), and G4LogicalBorderSurface::operator=().
SetTransitionRadiationSurface()
void G4LogicalSurface::SetTransitionRadiationSurface (G4TransitionRadiationSurface * tRadSurf) inline
Referenced by G4LogicalBorderSurface::G4LogicalBorderSurface(), G4LogicalSkinSurface::G4LogicalSkinSurface(), G4LogicalSkinSurface::operator=(), and G4LogicalBorderSurface::operator=().
Field Documentation
theName
G4String G4LogicalSurface::theName private
Definition at line 113 of file G4LogicalSurface.hh.
theSurfaceProperty
G4SurfaceProperty* G4LogicalSurface::theSurfaceProperty private
Definition at line 115 of file G4LogicalSurface.hh.
theTransRadSurface
G4TransitionRadiationSurface* G4LogicalSurface::theTransRadSurface private
Definition at line 116 of file G4LogicalSurface.hh.
The documentation for this class was generated from the following files:
source/geometry/management/include/G4LogicalSurface.hh
source/geometry/management/src/G4LogicalSurface.cc