Geant4: G4ProtonBuilder Class Reference
G4ProtonBuilder Class Reference
#include <G4ProtonBuilder.hh>
Public Member Functions
G4ProtonBuilder ()
virtual ~G4ProtonBuilder ()
virtual void Build () final override
virtual void RegisterMe (G4PhysicsBuilderInterface *aB) final override
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void SetMinEnergy (G4double)
virtual void SetMaxEnergy (G4double)
Private Attributes
G4ProtonInelasticProcess * theProtonInelastic
std::vector< G4VProtonBuilder * > theModelCollections
G4bool wasActivated
Detailed Description
Definition at line 51 of file G4ProtonBuilder.hh.
Constructor & Destructor Documentation
G4ProtonBuilder()
G4ProtonBuilder::G4ProtonBuilder ()
Definition at line 59 of file G4ProtonBuilder.cc.
~G4ProtonBuilder()
virtual G4ProtonBuilder::~G4ProtonBuilder () inline virtual
Definition at line 55 of file G4ProtonBuilder.hh.
Member Function Documentation
Build()
void G4ProtonBuilder::Build (void) final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 46 of file G4ProtonBuilder.cc.
Referenced by G4HadronPhysicsQGSP_BIC_AllHP::ConstructProcess(), and G4HadronPhysicsQGSP_BIC_HP::ConstructProcess().
RegisterMe()
void G4ProtonBuilder::RegisterMe (G4PhysicsBuilderInterface * aB) final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 64 of file G4ProtonBuilder.cc.
Referenced by G4HadronPhysicsQGSP_BIC_AllHP::CreateModels(), and G4HadronPhysicsQGSP_BIC_HP::CreateModels().
Field Documentation
theModelCollections
std::vector<G4VProtonBuilder *> G4ProtonBuilder::theModelCollections private
Definition at line 63 of file G4ProtonBuilder.hh.
Referenced by Build(), and RegisterMe().
theProtonInelastic
G4ProtonInelasticProcess* G4ProtonBuilder::theProtonInelastic private
Definition at line 61 of file G4ProtonBuilder.hh.
Referenced by Build(), and G4ProtonBuilder().
wasActivated
G4bool G4ProtonBuilder::wasActivated private
Definition at line 65 of file G4ProtonBuilder.hh.
Referenced by Build().
The documentation for this class was generated from the following files:
source/physics_lists/builders/include/G4ProtonBuilder.hh
source/physics_lists/builders/src/G4ProtonBuilder.cc