Geant4: G4DCofThisEvent Class Reference
G4DCofThisEvent Class Reference
#include <G4DCofThisEvent.hh>
Public Member Functions
G4DCofThisEvent ()
G4DCofThisEvent (G4int cap)
~G4DCofThisEvent ()
void * operator new (size_t)
void operator delete (void *anDCoTE)
void AddDigiCollection (G4int DCID, G4VDigiCollection *aDC)
G4DCofThisEvent (const G4DCofThisEvent &)
G4DCofThisEvent & operator= (const G4DCofThisEvent &)
G4VDigiCollection * GetDC (G4int i) const
G4int GetNumberOfCollections () const
G4int GetCapacity () const
Private Attributes
std::vector< G4VDigiCollection * > * DC
Detailed Description
Definition at line 49 of file G4DCofThisEvent.hh.
Constructor & Destructor Documentation
G4DCofThisEvent() [1/3]
G4DCofThisEvent::G4DCofThisEvent ()
Definition at line 38 of file G4DCofThisEvent.cc.
G4DCofThisEvent() [2/3]
G4DCofThisEvent::G4DCofThisEvent (G4int cap)
Definition at line 43 of file G4DCofThisEvent.cc.
~G4DCofThisEvent()
G4DCofThisEvent::~G4DCofThisEvent ()
Definition at line 52 of file G4DCofThisEvent.cc.
G4DCofThisEvent() [3/3]
G4DCofThisEvent::G4DCofThisEvent (const G4DCofThisEvent & rhs)
Definition at line 67 of file G4DCofThisEvent.cc.
Member Function Documentation
AddDigiCollection()
void G4DCofThisEvent::AddDigiCollection (G4int DCID, G4VDigiCollection * aDC)
Definition at line 61 of file G4DCofThisEvent.cc.
Referenced by G4DigiManager::SetDigiCollection().
GetCapacity()
G4int G4DCofThisEvent::GetCapacity () const inline
Definition at line 82 of file G4DCofThisEvent.hh.
Referenced by G4Event::Draw().
GetDC()
G4VDigiCollection* G4DCofThisEvent::GetDC (G4int i) const inline
Definition at line 66 of file G4DCofThisEvent.hh.
Referenced by G4Event::Draw(), and G4DigiManager::GetDigiCollection().
GetNumberOfCollections()
G4int G4DCofThisEvent::GetNumberOfCollections () const inline
Definition at line 73 of file G4DCofThisEvent.hh.
operator delete()
void G4DCofThisEvent::operator delete (void * anDCoTE) inline
Definition at line 105 of file G4DCofThisEvent.hh.
operator new()
void * G4DCofThisEvent::operator new (size_t) inline
Definition at line 94 of file G4DCofThisEvent.hh.
operator=()
G4DCofThisEvent & G4DCofThisEvent::operator= (const G4DCofThisEvent & rhs)
Definition at line 75 of file G4DCofThisEvent.cc.
Field Documentation
DC
std::vector<G4VDigiCollection*>* G4DCofThisEvent::DC private
Definition at line 63 of file G4DCofThisEvent.hh.
Referenced by AddDigiCollection(), G4DCofThisEvent(), GetCapacity(), GetDC(), GetNumberOfCollections(), operator=(), and ~G4DCofThisEvent().
The documentation for this class was generated from the following files:
source/digits_hits/digits/include/G4DCofThisEvent.hh
source/digits_hits/digits/src/G4DCofThisEvent.cc