Geant4: G4ReduciblePolygonIterator Class Reference
G4ReduciblePolygonIterator Class Reference
#include <G4ReduciblePolygon.hh>
Public Member Functions
G4ReduciblePolygonIterator (const G4ReduciblePolygon *theSubject)
void Begin ()
G4bool Next ()
G4bool Valid () const
G4double GetA () const
G4double GetB () const
Protected Attributes
const G4ReduciblePolygon * subject
G4ReduciblePolygon::ABVertex * current
Detailed Description
Definition at line 162 of file G4ReduciblePolygon.hh.
Constructor & Destructor Documentation
G4ReduciblePolygonIterator()
G4ReduciblePolygonIterator::G4ReduciblePolygonIterator (const G4ReduciblePolygon * theSubject) inline
Definition at line 166 of file G4ReduciblePolygon.hh.
Member Function Documentation
Begin()
void G4ReduciblePolygonIterator::Begin () inline
Definition at line 169 of file G4ReduciblePolygon.hh.
Referenced by G4GenericPolycone::Create(), G4Polycone::Create(), G4Polyhedra::Create(), and G4PolyPhiFace::G4PolyPhiFace().
GetA()
G4double G4ReduciblePolygonIterator::GetA () const inline
Definition at line 174 of file G4ReduciblePolygon.hh.
Referenced by G4GenericPolycone::Create(), G4Polycone::Create(), G4Polyhedra::Create(), and G4PolyPhiFace::G4PolyPhiFace().
GetB()
G4double G4ReduciblePolygonIterator::GetB () const inline
Definition at line 175 of file G4ReduciblePolygon.hh.
Referenced by G4GenericPolycone::Create(), G4Polycone::Create(), G4Polyhedra::Create(), and G4PolyPhiFace::G4PolyPhiFace().
Next()
G4bool G4ReduciblePolygonIterator::Next () inline
Definition at line 170 of file G4ReduciblePolygon.hh.
Referenced by G4GenericPolycone::Create(), G4Polycone::Create(), G4Polyhedra::Create(), and G4PolyPhiFace::G4PolyPhiFace().
Valid()
G4bool G4ReduciblePolygonIterator::Valid () const inline
Definition at line 172 of file G4ReduciblePolygon.hh.
Referenced by Next().
Field Documentation
current
G4ReduciblePolygon::ABVertex* G4ReduciblePolygonIterator::current protected
Definition at line 180 of file G4ReduciblePolygon.hh.
Referenced by Begin(), G4ReduciblePolygonIterator(), GetA(), GetB(), Next(), and Valid().
subject
const G4ReduciblePolygon* G4ReduciblePolygonIterator::subject protected
Definition at line 179 of file G4ReduciblePolygon.hh.
Referenced by Begin(), and G4ReduciblePolygonIterator().
The documentation for this class was generated from the following file:
source/geometry/solids/specific/include/G4ReduciblePolygon.hh