Geant4: G4VoxelLimits Class Reference
G4VoxelLimits Class Reference
#include <G4VoxelLimits.hh>
Public Member Functions
G4VoxelLimits ()
~G4VoxelLimits ()
void AddLimit (const EAxis pAxis, const G4double pMin, const G4double pMax)
G4double GetMaxXExtent () const
G4double GetMaxYExtent () const
G4double GetMaxZExtent () const
G4double GetMinXExtent () const
G4double GetMinYExtent () const
G4double GetMinZExtent () const
G4double GetMaxExtent (const EAxis pAxis) const
G4double GetMinExtent (const EAxis pAxis) const
G4bool IsXLimited () const
G4bool IsYLimited () const
G4bool IsZLimited () const
G4bool IsLimited () const
G4bool IsLimited (const EAxis pAxis) const
G4bool ClipToLimits (G4ThreeVector &pStart, G4ThreeVector &pEnd) const
G4bool Inside (const G4ThreeVector &pVec) const
G4int OutCode (const G4ThreeVector &pVec) const
Private Attributes
G4double fxAxisMin
G4double fxAxisMax
G4double fyAxisMin
G4double fyAxisMax
G4double fzAxisMin
G4double fzAxisMax
Detailed Description
Definition at line 61 of file G4VoxelLimits.hh.
Constructor & Destructor Documentation
G4VoxelLimits()
G4VoxelLimits::G4VoxelLimits ()
Definition at line 47 of file G4VoxelLimits.cc.
~G4VoxelLimits()
G4VoxelLimits::~G4VoxelLimits ()
Definition at line 54 of file G4VoxelLimits.cc.
Member Function Documentation
AddLimit()
void G4VoxelLimits::AddLimit (const EAxis pAxis, const G4double pMin, const G4double pMax)
Definition at line 64 of file G4VoxelLimits.cc.
Referenced by G4ReflectedSolid::CalculateExtent(), G4BoundingEnvelope::CalculateExtent(), G4ClippablePolygon::ClipAlongOneAxis(), G4VSolid::ClipPolygon(), G4DrawVoxels::ComputeVoxelPolyhedra(), and G4SmartVoxelHeader::RefineNodes().
ClipToLimits()
G4bool G4VoxelLimits::ClipToLimits (G4ThreeVector & pStart, G4ThreeVector & pEnd) const
Definition at line 101 of file G4VoxelLimits.cc.
Referenced by G4VSolid::ClipPolygonToSimpleLimits(), and G4ClippablePolygon::ClipToSimpleLimits().
GetMaxExtent()
G4double G4VoxelLimits::GetMaxExtent (const EAxis pAxis) const
Referenced by G4SmartVoxelHeader::BuildNodes(), G4GenericPolycone::CalculateExtent(), G4BoundingEnvelope::CalculateExtent(), G4Polycone::CalculateExtent(), G4Polyhedra::CalculateExtent(), G4Torus::CalculateExtent(), G4ExtrudedSolid::CalculateExtent(), G4TessellatedSolid::CalculateExtent(), G4ClippablePolygon::ClipAlongOneAxis(), and G4SolidExtentList::G4SolidExtentList().
GetMaxXExtent()
G4double G4VoxelLimits::GetMaxXExtent () const
Referenced by G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), G4ReflectedSolid::CalculateExtent(), G4BoundingEnvelope::CalculateExtent(), G4BoundingEnvelope::ClipEdgesByVoxel(), G4VSolid::ClipPolygon(), G4BoundingEnvelope::ClipVoxelByPlanes(), and operator<<().
GetMaxYExtent()
G4double G4VoxelLimits::GetMaxYExtent () const
Referenced by G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), G4ReflectedSolid::CalculateExtent(), G4BoundingEnvelope::CalculateExtent(), G4BoundingEnvelope::ClipEdgesByVoxel(), G4VSolid::ClipPolygon(), G4BoundingEnvelope::ClipVoxelByPlanes(), and operator<<().
GetMaxZExtent()
G4double G4VoxelLimits::GetMaxZExtent () const
Referenced by G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), G4ReflectedSolid::CalculateExtent(), G4BoundingEnvelope::CalculateExtent(), G4BoundingEnvelope::ClipEdgesByVoxel(), G4VSolid::ClipPolygon(), G4BoundingEnvelope::ClipVoxelByPlanes(), and operator<<().
GetMinExtent()
G4double G4VoxelLimits::GetMinExtent (const EAxis pAxis) const
Referenced by G4SmartVoxelHeader::BuildNodes(), G4GenericPolycone::CalculateExtent(), G4BoundingEnvelope::CalculateExtent(), G4Polycone::CalculateExtent(), G4Polyhedra::CalculateExtent(), G4Torus::CalculateExtent(), G4ExtrudedSolid::CalculateExtent(), G4TessellatedSolid::CalculateExtent(), G4ClippablePolygon::ClipAlongOneAxis(), and G4SolidExtentList::G4SolidExtentList().
GetMinXExtent()
G4double G4VoxelLimits::GetMinXExtent () const
Referenced by G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), G4ReflectedSolid::CalculateExtent(), G4BoundingEnvelope::CalculateExtent(), G4BoundingEnvelope::ClipEdgesByVoxel(), G4VSolid::ClipPolygon(), G4BoundingEnvelope::ClipVoxelByPlanes(), and operator<<().
GetMinYExtent()
G4double G4VoxelLimits::GetMinYExtent () const
Referenced by G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), G4ReflectedSolid::CalculateExtent(), G4BoundingEnvelope::CalculateExtent(), G4BoundingEnvelope::ClipEdgesByVoxel(), G4VSolid::ClipPolygon(), G4BoundingEnvelope::ClipVoxelByPlanes(), and operator<<().
GetMinZExtent()
G4double G4VoxelLimits::GetMinZExtent () const
Referenced by G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), G4ReflectedSolid::CalculateExtent(), G4BoundingEnvelope::CalculateExtent(), G4BoundingEnvelope::ClipEdgesByVoxel(), G4VSolid::ClipPolygon(), G4BoundingEnvelope::ClipVoxelByPlanes(), and operator<<().
Inside()
G4bool G4VoxelLimits::Inside (const G4ThreeVector & pVec) const
Referenced by G4VSolid::ClipPolygonToSimpleLimits(), and G4ClippablePolygon::ClipToSimpleLimits().
IsLimited() [1/2]
G4bool G4VoxelLimits::IsLimited () const
Referenced by G4SmartVoxelHeader::BuildNodes(), G4SmartVoxelHeader::BuildVoxelsWithinLimits(), G4BoundingEnvelope::CalculateExtent(), G4ClippablePolygon::Clip(), G4ClippablePolygon::ClipAlongOneAxis(), G4VSolid::ClipPolygon(), G4SolidExtentList::G4SolidExtentList(), and G4ClippablePolygon::PartialClip().
IsLimited() [2/2]
G4bool G4VoxelLimits::IsLimited (const EAxis pAxis) const
IsXLimited()
G4bool G4VoxelLimits::IsXLimited () const
Referenced by G4VSolid::ClipPolygon(), operator<<(), OutCode(), and G4SmartVoxelHeader::RefineNodes().
IsYLimited()
G4bool G4VoxelLimits::IsYLimited () const
Referenced by G4VSolid::ClipPolygon(), operator<<(), OutCode(), and G4SmartVoxelHeader::RefineNodes().
IsZLimited()
G4bool G4VoxelLimits::IsZLimited () const
Referenced by G4VSolid::ClipPolygon(), operator<<(), OutCode(), and G4SmartVoxelHeader::RefineNodes().
OutCode()
G4int G4VoxelLimits::OutCode (const G4ThreeVector & pVec) const
Definition at line 261 of file G4VoxelLimits.cc.
Referenced by ClipToLimits().
Field Documentation
fxAxisMax
G4double G4VoxelLimits::fxAxisMax private
Definition at line 127 of file G4VoxelLimits.hh.
Referenced by AddLimit(), ClipToLimits(), and OutCode().
fxAxisMin
G4double G4VoxelLimits::fxAxisMin private
Definition at line 127 of file G4VoxelLimits.hh.
Referenced by AddLimit(), ClipToLimits(), and OutCode().
fyAxisMax
G4double G4VoxelLimits::fyAxisMax private
Definition at line 128 of file G4VoxelLimits.hh.
Referenced by AddLimit(), ClipToLimits(), and OutCode().
fyAxisMin
G4double G4VoxelLimits::fyAxisMin private
Definition at line 128 of file G4VoxelLimits.hh.
Referenced by AddLimit(), ClipToLimits(), and OutCode().
fzAxisMax
G4double G4VoxelLimits::fzAxisMax private
Definition at line 129 of file G4VoxelLimits.hh.
Referenced by AddLimit(), ClipToLimits(), and OutCode().
fzAxisMin
G4double G4VoxelLimits::fzAxisMin private
Definition at line 129 of file G4VoxelLimits.hh.
Referenced by AddLimit(), ClipToLimits(), and OutCode().
The documentation for this class was generated from the following files:
source/geometry/management/include/G4VoxelLimits.hh
source/geometry/management/src/G4VoxelLimits.cc