Geant4: G4INCL::CrossSectionsINCL46 Class Reference
G4INCL::CrossSectionsINCL46 Class Reference
Cross sections used in INCL4.6.
#include <G4INCLCrossSectionsINCL46.hh>
Public Member Functions
virtual G4double elastic (Particle const *const p1, Particle const *const p2)
Elastic particle-particle cross section.
virtual G4double total (Particle const *const p1, Particle const *const p2)
Total (elastic+inelastic) particle-particle cross section.
virtual G4double NDeltaToNN (Particle const *const p1, Particle const *const p2)
Cross section for NDelta->NN.
virtual G4double NNToNDelta (Particle const *const p1, Particle const *const p2)
Cross section for NN->NDelta.
virtual G4double piNToDelta (Particle const *const p1, Particle const *const p2)
Cross section for piN->NDelta.
virtual G4double NNToxPiNN (const G4int xpi, Particle const *const p1, Particle const *const p2)
Cross section for X pion production - NN Channel.
virtual G4double piNToxPiN (const G4int xpi, Particle const *const p1, Particle const *const p2)
Cross section for X pion production - piN Channel.
virtual G4double piNToEtaN (Particle const *const p1, Particle const *const p2)
Cross sections for mesonic resonance production - piN Channel.
virtual G4double piNToOmegaN (Particle const *const p1, Particle const *const p2)
Cross section for PiN->OmegaN.
virtual G4double piNToEtaPrimeN (Particle const *const p1, Particle const *const p2)
Cross section for PiN->EtaPrimeN.
virtual G4double etaNToPiN (Particle const *const p1, Particle const *const p2)
Cross sections for mesonic resonance absorption on nucleons - piN Channel.
virtual G4double omegaNToPiN (Particle const *const p1, Particle const *const p2)
Cross section for OmegaN->PiN.
virtual G4double etaPrimeNToPiN (Particle const *const p1, Particle const *const p2)
Cross section for EtaPrimeN->PiN.
virtual G4double etaNToPiPiN (Particle const *const p1, Particle const *const p2)
Cross sections for mesonic resonance absorption on nucleon - pipiN Channel.
virtual G4double omegaNToPiPiN (Particle const *const p1, Particle const *const p2)
Cross section for OmegaN->PiPiN.
virtual G4double NNToNNEta (Particle const *const p1, Particle const *const p2)
Cross section for Eta production - NN entrance channel.
virtual G4double NNToNNEtaExclu (Particle const *const p1, Particle const *const p2)
Cross section for Eta production (exclusive) - NN entrance channel.
virtual G4double NNToNNEtaxPi (const G4int xpi, Particle const *const p1, Particle const *const p2)
Cross section for X pion production - NNEta Channel.
virtual G4double NNToNDeltaEta (Particle const *const p1, Particle const *const p2)
Cross section for N-Delta-Eta production - NNEta Channel.
virtual G4double NYelastic (Particle const *const p1, Particle const *const p2)
elastic scattering for Nucleon-Strange Particles cross sections
virtual G4double NKbelastic (Particle const *const p1, Particle const *const p2)
virtual G4double NKelastic (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNLK (Particle const *const p1, Particle const *const p2)
Nucleon-Nucleon to Stange particles cross sections.
virtual G4double NNToNSK (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNLKpi (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNSKpi (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNLK2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNSK2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNNKKb (Particle const *const p1, Particle const *const p2)
virtual G4double NNToMissingStrangeness (Particle const *const p1, Particle const *const p2)
virtual G4double NDeltaToNLK (Particle const *const p1, Particle const *const p2)
Nucleon-Delta to Stange particles cross sections.
virtual G4double NDeltaToNSK (Particle const *const p1, Particle const *const p2)
virtual G4double NDeltaToDeltaLK (Particle const *const p1, Particle const *const p2)
virtual G4double NDeltaToDeltaSK (Particle const *const p1, Particle const *const p2)
virtual G4double NDeltaToNNKKb (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToLK (Particle const *const p1, Particle const *const p2)
Nucleon-Pion to Stange particles cross sections.
virtual G4double NpiToSK (Particle const *const p1, Particle const *const p2)
virtual G4double p_pimToSzKz (Particle const *const p1, Particle const *const p2)
virtual G4double p_pimToSmKp (Particle const *const p1, Particle const *const p2)
virtual G4double p_pizToSzKp (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToLKpi (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToSKpi (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToLK2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToSK2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToNKKb (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToMissingStrangeness (Particle const *const p1, Particle const *const p2)
virtual G4double NLToNS (Particle const *const p1, Particle const *const p2)
Nucleon-Hyperon cross sections.
virtual G4double NSToNL (Particle const *const p1, Particle const *const p2)
virtual G4double NSToNS (Particle const *const p1, Particle const *const p2)
virtual G4double NKToNK (Particle const *const p1, Particle const *const p2)
Nucleon-Kaon inelastic cross sections.
virtual G4double NKToNKpi (Particle const *const p1, Particle const *const p2)
virtual G4double NKToNK2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToNKb (Particle const *const p1, Particle const *const p2)
Nucleon-antiKaon inelastic cross sections.
virtual G4double NKbToSpi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToLpi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToS2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToL2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToNKbpi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToNKb2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNNOmega (Particle const *const particle1, Particle const *const particle2)
Cross section for Eta production - NN entrance channel.
virtual G4double NNToNNOmegaExclu (Particle const *const particle1, Particle const *const particle2)
Cross section for Eta production (exclusive) - NN entrance channel.
virtual G4double NNToNNOmegaxPi (const G4int xpi, Particle const *const p1, Particle const *const p2)
Cross section for X pion production - NNEta Channel.
virtual G4double NNToNDeltaOmega (Particle const *const p1, Particle const *const p2)
Cross section for N-Delta-Eta production - NNEta Channel.
virtual G4double calculateNNAngularSlope (G4double energyCM, G4int iso)
Calculate the slope of the NN DDXS.
Public Member Functions inherited from G4INCL::ICrossSections
ICrossSections ()
virtual ~ICrossSections ()
Protected Member Functions
G4double elasticNNLegacy (Particle const *const part1, Particle const *const part2)
Internal implementation of the elastic cross section.
G4double deltaProduction (const G4int isospin, const G4double pLab)
Internal function for the delta-production cross section.
G4double spnPiPlusPHE (const G4double x)
G4double spnPiMinusPHE (const G4double x)
Detailed Description
Cross sections used in INCL4.6.
Definition at line 53 of file G4INCLCrossSectionsINCL46.hh.
Member Function Documentation
calculateNNAngularSlope()
G4double G4INCL::CrossSectionsINCL46::calculateNNAngularSlope (G4double energyCM, G4int iso) virtual
Calculate the slope of the NN DDXS.
Parameters
energyCM energy in the CM frame, in MeV
iso total isospin of the system
Returns
the slope of the angular distribution
Implements G4INCL::ICrossSections.
Definition at line 345 of file G4INCLCrossSectionsINCL46.cc.
deltaProduction()
G4double G4INCL::CrossSectionsINCL46::deltaProduction (const G4int isospin, const G4double pLab) protected
Internal function for the delta-production cross section.
Definition at line 149 of file G4INCLCrossSectionsINCL46.cc.
Referenced by NDeltaToNN(), and NNToNDelta().
elastic()
G4double G4INCL::CrossSectionsINCL46::elastic (Particle const *const p1, Particle const *const p2) virtual
Elastic particle-particle cross section.
Implements G4INCL::ICrossSections.
Definition at line 336 of file G4INCLCrossSectionsINCL46.cc.
Referenced by total().
elasticNNLegacy()
G4double G4INCL::CrossSectionsINCL46::elasticNNLegacy (Particle const *const part1, Particle const *const part2) protected
Internal implementation of the elastic cross section.
Definition at line 92 of file G4INCLCrossSectionsINCL46.cc.
Referenced by elastic().
etaNToPiN()
G4double G4INCL::CrossSectionsINCL46::etaNToPiN (Particle const *const p1, Particle const *const p2) virtual
Cross sections for mesonic resonance absorption on nucleons - piN Channel.
Implements G4INCL::ICrossSections.
Definition at line 397 of file G4INCLCrossSectionsINCL46.cc.
etaNToPiPiN()
G4double G4INCL::CrossSectionsINCL46::etaNToPiPiN (Particle const *const p1, Particle const *const p2) virtual
Cross sections for mesonic resonance absorption on nucleon - pipiN Channel.
Implements G4INCL::ICrossSections.
Definition at line 405 of file G4INCLCrossSectionsINCL46.cc.
etaPrimeNToPiN()
G4double G4INCL::CrossSectionsINCL46::etaPrimeNToPiN (Particle const *const p1, Particle const *const p2) virtual
Cross section for EtaPrimeN->PiN.
Implements G4INCL::ICrossSections.
Definition at line 426 of file G4INCLCrossSectionsINCL46.cc.
NDeltaToDeltaLK()
G4double G4INCL::CrossSectionsINCL46::NDeltaToDeltaLK (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 570 of file G4INCLCrossSectionsINCL46.cc.
NDeltaToDeltaSK()
G4double G4INCL::CrossSectionsINCL46::NDeltaToDeltaSK (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 574 of file G4INCLCrossSectionsINCL46.cc.
NDeltaToNLK()
G4double G4INCL::CrossSectionsINCL46::NDeltaToNLK (Particle const *const p1, Particle const *const p2) virtual
Nucleon-Delta to Stange particles cross sections.
Implements G4INCL::ICrossSections.
Definition at line 562 of file G4INCLCrossSectionsINCL46.cc.
NDeltaToNN()
G4double G4INCL::CrossSectionsINCL46::NDeltaToNN (Particle const *const p1, Particle const *const p2) virtual
Cross section for NDelta->NN.
Implements G4INCL::ICrossSections.
Definition at line 286 of file G4INCLCrossSectionsINCL46.cc.
Referenced by total().
NDeltaToNNKKb()
G4double G4INCL::CrossSectionsINCL46::NDeltaToNNKKb (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 579 of file G4INCLCrossSectionsINCL46.cc.
NDeltaToNSK()
G4double G4INCL::CrossSectionsINCL46::NDeltaToNSK (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 566 of file G4INCLCrossSectionsINCL46.cc.
NKbelastic()
G4double G4INCL::CrossSectionsINCL46::NKbelastic (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 499 of file G4INCLCrossSectionsINCL46.cc.
NKbToL2pi()
G4double G4INCL::CrossSectionsINCL46::NKbToL2pi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 719 of file G4INCLCrossSectionsINCL46.cc.
NKbToLpi()
G4double G4INCL::CrossSectionsINCL46::NKbToLpi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 705 of file G4INCLCrossSectionsINCL46.cc.
NKbToNKb()
G4double G4INCL::CrossSectionsINCL46::NKbToNKb (Particle const *const p1, Particle const *const p2) virtual
Nucleon-antiKaon inelastic cross sections.
Implements G4INCL::ICrossSections.
Definition at line 691 of file G4INCLCrossSectionsINCL46.cc.
NKbToNKb2pi()
G4double G4INCL::CrossSectionsINCL46::NKbToNKb2pi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 733 of file G4INCLCrossSectionsINCL46.cc.
NKbToNKbpi()
G4double G4INCL::CrossSectionsINCL46::NKbToNKbpi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 726 of file G4INCLCrossSectionsINCL46.cc.
NKbToS2pi()
G4double G4INCL::CrossSectionsINCL46::NKbToS2pi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 712 of file G4INCLCrossSectionsINCL46.cc.
NKbToSpi()
G4double G4INCL::CrossSectionsINCL46::NKbToSpi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 698 of file G4INCLCrossSectionsINCL46.cc.
NKelastic()
G4double G4INCL::CrossSectionsINCL46::NKelastic (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 492 of file G4INCLCrossSectionsINCL46.cc.
NKToNK()
G4double G4INCL::CrossSectionsINCL46::NKToNK (Particle const *const p1, Particle const *const p2) virtual
Nucleon-Kaon inelastic cross sections.
Implements G4INCL::ICrossSections.
Definition at line 670 of file G4INCLCrossSectionsINCL46.cc.
NKToNK2pi()
G4double G4INCL::CrossSectionsINCL46::NKToNK2pi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 684 of file G4INCLCrossSectionsINCL46.cc.
NKToNKpi()
G4double G4INCL::CrossSectionsINCL46::NKToNKpi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 677 of file G4INCLCrossSectionsINCL46.cc.
NLToNS()
G4double G4INCL::CrossSectionsINCL46::NLToNS (Particle const *const p1, Particle const *const p2) virtual
Nucleon-Hyperon cross sections.
Implements G4INCL::ICrossSections.
Definition at line 649 of file G4INCLCrossSectionsINCL46.cc.
NNToMissingStrangeness()
G4double G4INCL::CrossSectionsINCL46::NNToMissingStrangeness (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 555 of file G4INCLCrossSectionsINCL46.cc.
NNToNDelta()
G4double G4INCL::CrossSectionsINCL46::NNToNDelta (Particle const *const p1, Particle const *const p2) virtual
Cross section for NN->NDelta.
Implements G4INCL::ICrossSections.
Definition at line 324 of file G4INCLCrossSectionsINCL46.cc.
Referenced by total().
NNToNDeltaEta()
G4double G4INCL::CrossSectionsINCL46::NNToNDeltaEta (Particle const *const p1, Particle const *const p2) virtual
Cross section for N-Delta-Eta production - NNEta Channel.
Implements G4INCL::ICrossSections.
Definition at line 451 of file G4INCLCrossSectionsINCL46.cc.
NNToNDeltaOmega()
G4double G4INCL::CrossSectionsINCL46::NNToNDeltaOmega (Particle const *const p1, Particle const *const p2) virtual
Cross section for N-Delta-Eta production - NNEta Channel.
Implements G4INCL::ICrossSections.
Definition at line 476 of file G4INCLCrossSectionsINCL46.cc.
NNToNLK()
G4double G4INCL::CrossSectionsINCL46::NNToNLK (Particle const *const p1, Particle const *const p2) virtual
Nucleon-Nucleon to Stange particles cross sections.
Implements G4INCL::ICrossSections.
Definition at line 506 of file G4INCLCrossSectionsINCL46.cc.
NNToNLK2pi()
G4double G4INCL::CrossSectionsINCL46::NNToNLK2pi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 534 of file G4INCLCrossSectionsINCL46.cc.
NNToNLKpi()
G4double G4INCL::CrossSectionsINCL46::NNToNLKpi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 520 of file G4INCLCrossSectionsINCL46.cc.
NNToNNEta()
G4double G4INCL::CrossSectionsINCL46::NNToNNEta (Particle const *const p1, Particle const *const p2) virtual
Cross section for Eta production - NN entrance channel.
Implements G4INCL::ICrossSections.
Definition at line 433 of file G4INCLCrossSectionsINCL46.cc.
NNToNNEtaExclu()
G4double G4INCL::CrossSectionsINCL46::NNToNNEtaExclu (Particle const *const p1, Particle const *const p2) virtual
Cross section for Eta production (exclusive) - NN entrance channel.
Implements G4INCL::ICrossSections.
Definition at line 440 of file G4INCLCrossSectionsINCL46.cc.
NNToNNEtaxPi()
G4double G4INCL::CrossSectionsINCL46::NNToNNEtaxPi (const G4int xpi, Particle const *const p1, Particle const *const p2) virtual
Cross section for X pion production - NNEta Channel.
Implements G4INCL::ICrossSections.
Definition at line 447 of file G4INCLCrossSectionsINCL46.cc.
NNToNNKKb()
G4double G4INCL::CrossSectionsINCL46::NNToNNKKb (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 548 of file G4INCLCrossSectionsINCL46.cc.
NNToNNOmega()
G4double G4INCL::CrossSectionsINCL46::NNToNNOmega (Particle const *const particle1, Particle const *const particle2) virtual
Cross section for Eta production - NN entrance channel.
Implements G4INCL::ICrossSections.
Definition at line 458 of file G4INCLCrossSectionsINCL46.cc.
NNToNNOmegaExclu()
G4double G4INCL::CrossSectionsINCL46::NNToNNOmegaExclu (Particle const *const particle1, Particle const *const particle2) virtual
Cross section for Eta production (exclusive) - NN entrance channel.
Implements G4INCL::ICrossSections.
Definition at line 465 of file G4INCLCrossSectionsINCL46.cc.
NNToNNOmegaxPi()
G4double G4INCL::CrossSectionsINCL46::NNToNNOmegaxPi (const G4int xpi, Particle const *const p1, Particle const *const p2) virtual
Cross section for X pion production - NNEta Channel.
Implements G4INCL::ICrossSections.
Definition at line 472 of file G4INCLCrossSectionsINCL46.cc.
NNToNSK()
G4double G4INCL::CrossSectionsINCL46::NNToNSK (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 513 of file G4INCLCrossSectionsINCL46.cc.
NNToNSK2pi()
G4double G4INCL::CrossSectionsINCL46::NNToNSK2pi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 541 of file G4INCLCrossSectionsINCL46.cc.
NNToNSKpi()
G4double G4INCL::CrossSectionsINCL46::NNToNSKpi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 527 of file G4INCLCrossSectionsINCL46.cc.
NNToxPiNN()
G4double G4INCL::CrossSectionsINCL46::NNToxPiNN (const G4int xpi, Particle const *const p1, Particle const *const p2) virtual
Cross section for X pion production - NN Channel.
Implements G4INCL::ICrossSections.
Definition at line 368 of file G4INCLCrossSectionsINCL46.cc.
NpiToLK()
G4double G4INCL::CrossSectionsINCL46::NpiToLK (Particle const *const p1, Particle const *const p2) virtual
Nucleon-Pion to Stange particles cross sections.
Implements G4INCL::ICrossSections.
Definition at line 584 of file G4INCLCrossSectionsINCL46.cc.
NpiToLK2pi()
G4double G4INCL::CrossSectionsINCL46::NpiToLK2pi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 621 of file G4INCLCrossSectionsINCL46.cc.
NpiToLKpi()
G4double G4INCL::CrossSectionsINCL46::NpiToLKpi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 607 of file G4INCLCrossSectionsINCL46.cc.
NpiToMissingStrangeness()
G4double G4INCL::CrossSectionsINCL46::NpiToMissingStrangeness (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 642 of file G4INCLCrossSectionsINCL46.cc.
NpiToNKKb()
G4double G4INCL::CrossSectionsINCL46::NpiToNKKb (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 635 of file G4INCLCrossSectionsINCL46.cc.
NpiToSK()
G4double G4INCL::CrossSectionsINCL46::NpiToSK (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 591 of file G4INCLCrossSectionsINCL46.cc.
NpiToSK2pi()
G4double G4INCL::CrossSectionsINCL46::NpiToSK2pi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 628 of file G4INCLCrossSectionsINCL46.cc.
NpiToSKpi()
G4double G4INCL::CrossSectionsINCL46::NpiToSKpi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 614 of file G4INCLCrossSectionsINCL46.cc.
NSToNL()
G4double G4INCL::CrossSectionsINCL46::NSToNL (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 656 of file G4INCLCrossSectionsINCL46.cc.
NSToNS()
G4double G4INCL::CrossSectionsINCL46::NSToNS (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 663 of file G4INCLCrossSectionsINCL46.cc.
NYelastic()
G4double G4INCL::CrossSectionsINCL46::NYelastic (Particle const *const p1, Particle const *const p2) virtual
elastic scattering for Nucleon-Strange Particles cross sections
Implements G4INCL::ICrossSections.
Definition at line 485 of file G4INCLCrossSectionsINCL46.cc.
omegaNToPiN()
G4double G4INCL::CrossSectionsINCL46::omegaNToPiN (Particle const *const p1, Particle const *const p2) virtual
Cross section for OmegaN->PiN.
Implements G4INCL::ICrossSections.
Definition at line 412 of file G4INCLCrossSectionsINCL46.cc.
omegaNToPiPiN()
G4double G4INCL::CrossSectionsINCL46::omegaNToPiPiN (Particle const *const p1, Particle const *const p2) virtual
Cross section for OmegaN->PiPiN.
Implements G4INCL::ICrossSections.
Definition at line 419 of file G4INCLCrossSectionsINCL46.cc.
p_pimToSmKp()
G4double G4INCL::CrossSectionsINCL46::p_pimToSmKp (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 597 of file G4INCLCrossSectionsINCL46.cc.
p_pimToSzKz()
G4double G4INCL::CrossSectionsINCL46::p_pimToSzKz (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 600 of file G4INCLCrossSectionsINCL46.cc.
p_pizToSzKp()
G4double G4INCL::CrossSectionsINCL46::p_pizToSzKp (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Definition at line 603 of file G4INCLCrossSectionsINCL46.cc.
piNToDelta()
G4double G4INCL::CrossSectionsINCL46::piNToDelta (Particle const *const p1, Particle const *const p2) virtual
Cross section for piN->NDelta.
Implements G4INCL::ICrossSections.
Definition at line 227 of file G4INCLCrossSectionsINCL46.cc.
Referenced by total().
piNToEtaN()
G4double G4INCL::CrossSectionsINCL46::piNToEtaN (Particle const *const p1, Particle const *const p2) virtual
Cross sections for mesonic resonance production - piN Channel.
Implements G4INCL::ICrossSections.
Definition at line 376 of file G4INCLCrossSectionsINCL46.cc.
piNToEtaPrimeN()
G4double G4INCL::CrossSectionsINCL46::piNToEtaPrimeN (Particle const *const p1, Particle const *const p2) virtual
Cross section for PiN->EtaPrimeN.
Implements G4INCL::ICrossSections.
Definition at line 390 of file G4INCLCrossSectionsINCL46.cc.
piNToOmegaN()
G4double G4INCL::CrossSectionsINCL46::piNToOmegaN (Particle const *const p1, Particle const *const p2) virtual
Cross section for PiN->OmegaN.
Implements G4INCL::ICrossSections.
Definition at line 383 of file G4INCLCrossSectionsINCL46.cc.
piNToxPiN()
G4double G4INCL::CrossSectionsINCL46::piNToxPiN (const G4int xpi, Particle const *const p1, Particle const *const p2) virtual
Cross section for X pion production - piN Channel.
Implements G4INCL::ICrossSections.
Definition at line 372 of file G4INCLCrossSectionsINCL46.cc.
spnPiMinusPHE()
G4double G4INCL::CrossSectionsINCL46::spnPiMinusPHE (const G4double x) protected
Definition at line 195 of file G4INCLCrossSectionsINCL46.cc.
Referenced by piNToDelta().
spnPiPlusPHE()
G4double G4INCL::CrossSectionsINCL46::spnPiPlusPHE (const G4double x) protected
Definition at line 182 of file G4INCLCrossSectionsINCL46.cc.
Referenced by piNToDelta().
total()
G4double G4INCL::CrossSectionsINCL46::total (Particle const *const p1, Particle const *const p2) virtual
Total (elastic+inelastic) particle-particle cross section.
Implements G4INCL::ICrossSections.
Definition at line 210 of file G4INCLCrossSectionsINCL46.cc.
The documentation for this class was generated from the following files:
source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLCrossSectionsINCL46.hh
source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLCrossSectionsINCL46.cc