Geant4: G4AttHolder Class Reference
G4AttHolder Class Reference
#include <G4AttHolder.hh>
Public Member Functions
G4AttHolder ()
~G4AttHolder ()
const std::vector< const std::vector< G4AttValue > * > & GetAttValues () const
const std::vector< const std::map< G4String, G4AttDef > * > & GetAttDefs () const
void AddAtts (const std::vector< G4AttValue > *values, const std::map< G4String, G4AttDef > *defs)
Private Member Functions
G4AttHolder (const G4AttHolder &)
G4AttHolder & operator= (const G4AttHolder &)
Private Attributes
std::vector< const std::vector< G4AttValue > * > fValues
std::vector< const std::map< G4String, G4AttDef > * > fDefs
Detailed Description
Definition at line 52 of file G4AttHolder.hh.
Constructor & Destructor Documentation
G4AttHolder() [1/2]
G4AttHolder::G4AttHolder () inline
Definition at line 56 of file G4AttHolder.hh.
~G4AttHolder()
G4AttHolder::~G4AttHolder ()
Definition at line 33 of file G4AttHolder.cc.
G4AttHolder() [2/2]
G4AttHolder::G4AttHolder (const G4AttHolder &) private
Member Function Documentation
AddAtts()
void G4AttHolder::AddAtts (const std::vector< G4AttValue > * values, const std::map< G4String, G4AttDef > * defs) inline
Definition at line 64 of file G4AttHolder.hh.
Referenced by G4VSceneHandler::LoadAtts().
GetAttDefs()
const std::vector<const std::map<G4String,G4AttDef>*>& G4AttHolder::GetAttDefs () const inline
Definition at line 61 of file G4AttHolder.hh.
Referenced by G4OpenInventorXtExaminerViewer::findAndSetRefPath(), G4OpenInventorXtExaminerViewer::mouseoverCB(), and G4OpenInventorXtExaminerViewer::pickingCB().
GetAttValues()
const std::vector<const std::vector<G4AttValue>*>& G4AttHolder::GetAttValues () const inline
Definition at line 59 of file G4AttHolder.hh.
Referenced by G4OpenInventorXtExaminerViewer::findAndSetRefPath(), G4OpenInventorXtExaminerViewer::mouseoverCB(), and G4OpenInventorXtExaminerViewer::pickingCB().
operator=()
G4AttHolder& G4AttHolder::operator= (const G4AttHolder &) private
Field Documentation
fDefs
std::vector<const std::map<G4String,G4AttDef>*> G4AttHolder::fDefs private
Definition at line 75 of file G4AttHolder.hh.
Referenced by AddAtts(), and GetAttDefs().
fValues
std::vector<const std::vector<G4AttValue>*> G4AttHolder::fValues private
Definition at line 74 of file G4AttHolder.hh.
Referenced by AddAtts(), GetAttValues(), and ~G4AttHolder().
The documentation for this class was generated from the following files:
source/graphics_reps/include/G4AttHolder.hh
source/graphics_reps/src/G4AttHolder.cc