Geant4: G4VTrajectory Class Reference
G4VTrajectory Class Reference abstract
#include <G4VTrajectory.hh>
Public Member Functions
G4VTrajectory ()
virtual ~G4VTrajectory ()
G4bool operator== (const G4VTrajectory &right) const
virtual G4int GetTrackID () const =0
virtual G4int GetParentID () const =0
virtual G4String GetParticleName () const =0
virtual G4double GetCharge () const =0
virtual G4int GetPDGEncoding () const =0
virtual G4ThreeVector GetInitialMomentum () const =0
virtual int GetPointEntries () const =0
virtual G4VTrajectoryPoint * GetPoint (G4int i) const =0
virtual void ShowTrajectory (std::ostream &os=G4cout) const
virtual void DrawTrajectory () const
virtual const std::map< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
virtual void AppendStep (const G4Step *aStep)=0
virtual void MergeTrajectory (G4VTrajectory *secondTrajectory)=0
Detailed Description
Definition at line 56 of file G4VTrajectory.hh.
Constructor & Destructor Documentation
G4VTrajectory()
G4VTrajectory::G4VTrajectory ()
Definition at line 52 of file G4VTrajectory.cc.
~G4VTrajectory()
G4VTrajectory::~G4VTrajectory () virtual
Definition at line 53 of file G4VTrajectory.cc.
Member Function Documentation
AppendStep()
virtual void G4VTrajectory::AppendStep (const G4Step * aStep) pure virtual
Implemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, G4RichTrajectory, WLSTrajectory, F04Trajectory, RE01Trajectory, and G4RayTrajectory.
Referenced by ITTrackingInteractivity::AppendStep().
CreateAttValues()
virtual std::vector<G4AttValue>* G4VTrajectory::CreateAttValues () const inline virtual
Reimplemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, WLSTrajectory, G4RichTrajectory, F04Trajectory, and RE01Trajectory.
Definition at line 99 of file G4VTrajectory.hh.
Referenced by G4HepRepSceneHandler::addAttributes(), G4HepRepFileSceneHandler::AddCompound(), G4TrajectoriesModelDebugG4AttValues(), G4VSceneHandler::LoadAtts(), and ShowTrajectory().
DrawTrajectory()
void G4VTrajectory::DrawTrajectory () const virtual
Reimplemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, G4RichTrajectory, G4RayTrajectory, RE01Trajectory, and LXeTrajectory.
Definition at line 114 of file G4VTrajectory.cc.
Referenced by G4GMocrenFileSceneHandler::AddCompound(), G4VSceneHandler::AddCompound(), CexmcEventAction::DrawTrajectories(), G4RichTrajectory::DrawTrajectory(), G4SmoothTrajectory::DrawTrajectory(), G4Trajectory::DrawTrajectory(), and RE04Trajectory::DrawTrajectory().
GetAttDefs()
virtual const std::map<G4String,G4AttDef>* G4VTrajectory::GetAttDefs () const inline virtual
Reimplemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, WLSTrajectory, G4RichTrajectory, F04Trajectory, and RE01Trajectory.
Definition at line 93 of file G4VTrajectory.hh.
Referenced by G4HepRepSceneHandler::addAttributes(), G4HepRepFileSceneHandler::AddCompound(), G4TrajectoriesModelDebugG4AttValues(), G4VSceneHandler::LoadAtts(), and ShowTrajectory().
GetCharge()
virtual G4double G4VTrajectory::GetCharge () const pure virtual
Implemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, G4RayTrajectory, WLSTrajectory, F04Trajectory, and RE01Trajectory.
Referenced by G4GMocrenFileSceneHandler::AddCompound(), G4TrajectoryDrawByCharge::Draw(), and G4TrajectoryChargeFilter::Evaluate().
GetInitialMomentum()
virtual G4ThreeVector G4VTrajectory::GetInitialMomentum () const pure virtual
Implemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, G4RayTrajectory, WLSTrajectory, F04Trajectory, and RE01Trajectory.
Referenced by G4GMocrenFileSceneHandler::AddCompound().
GetParentID()
virtual G4int G4VTrajectory::GetParentID () const pure virtual
Implemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, G4RayTrajectory, WLSTrajectory, F04Trajectory, and RE01Trajectory.
GetParticleName()
virtual G4String G4VTrajectory::GetParticleName () const pure virtual
Implemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, G4RayTrajectory, WLSTrajectory, F04Trajectory, and RE01Trajectory.
Referenced by G4GMocrenFileSceneHandler::AddCompound(), G4TrajectoryDrawByParticleID::Draw(), and G4TrajectoryParticleFilter::Evaluate().
GetPDGEncoding()
virtual G4int G4VTrajectory::GetPDGEncoding () const pure virtual
Implemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, G4RayTrajectory, WLSTrajectory, F04Trajectory, and RE01Trajectory.
GetPoint()
virtual G4VTrajectoryPoint* G4VTrajectory::GetPoint (G4int i) const pure virtual
Implemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, WLSTrajectory, G4RichTrajectory, F04Trajectory, RE01Trajectory, and G4RayTrajectory.
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4GMocrenFileSceneHandler::AddCompound(), G4TrajectoryDrawByOriginVolume::Draw(), G4TrajectoryOriginVolumeFilter::Evaluate(), G4TrajectoriesModelDebugG4AttValues(), G4TrajectoryDrawerUtils::GetPointsAndTimes(), G4VSceneHandler::LoadAtts(), and ShowTrajectory().
GetPointEntries()
virtual int G4VTrajectory::GetPointEntries () const pure virtual
Implemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, WLSTrajectory, G4RichTrajectory, F04Trajectory, RE01Trajectory, and G4RayTrajectory.
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4GMocrenFileSceneHandler::AddCompound(), G4TrajectoriesModelDebugG4AttValues(), G4TrajectoryDrawerUtils::GetPointsAndTimes(), G4VSceneHandler::LoadAtts(), and ShowTrajectory().
GetTrackID()
virtual G4int G4VTrajectory::GetTrackID () const pure virtual
Implemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, G4RayTrajectory, WLSTrajectory, F04Trajectory, and RE01Trajectory.
Referenced by G4GMocrenFileSceneHandler::AddCompound().
MergeTrajectory()
virtual void G4VTrajectory::MergeTrajectory (G4VTrajectory * secondTrajectory) pure virtual
Implemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, G4RichTrajectory, WLSTrajectory, F04Trajectory, G4RayTrajectory, and RE01Trajectory.
Referenced by G4EventManager::DoProcessing().
operator==()
G4bool G4VTrajectory::operator== (const G4VTrajectory & right) const
Definition at line 55 of file G4VTrajectory.cc.
ShowTrajectory()
void G4VTrajectory::ShowTrajectory (std::ostream & os = G4cout) const virtual
Reimplemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, WLSTrajectory, G4RichTrajectory, F04Trajectory, RE01Trajectory, and G4RayTrajectory.
Definition at line 60 of file G4VTrajectory.cc.
Referenced by ITTrackingInteractivity::EndTracking(), G4TrackingManager::ProcessOneTrack(), F04Trajectory::ShowTrajectory(), G4RichTrajectory::ShowTrajectory(), WLSTrajectory::ShowTrajectory(), G4SmoothTrajectory::ShowTrajectory(), G4Trajectory::ShowTrajectory(), and RE04Trajectory::ShowTrajectory().
The documentation for this class was generated from the following files:
source/tracking/include/G4VTrajectory.hh
source/tracking/src/G4VTrajectory.cc