Geant4: G4VUserPhysicsList Class Reference
G4VUserPhysicsList Class Reference abstract
#include <G4VUserPhysicsList.hh>
Public Member Functions
G4VUserPhysicsList ()
virtual ~G4VUserPhysicsList ()
G4VUserPhysicsList (const G4VUserPhysicsList &)
G4VUserPhysicsList & operator= (const G4VUserPhysicsList &)
virtual void ConstructParticle ()=0
void Construct ()
virtual void ConstructProcess ()=0
void UseCoupledTransportation (G4bool vl=true)
virtual void SetCuts ()
void SetDefaultCutValue (G4double newCutValue)
G4double GetDefaultCutValue () const
void BuildPhysicsTable ()
void PreparePhysicsTable (G4ParticleDefinition *)
void BuildPhysicsTable (G4ParticleDefinition *)
G4bool StorePhysicsTable (const G4String &directory=".")
G4bool IsPhysicsTableRetrieved () const
G4bool IsStoredInAscii () const
const G4String & GetPhysicsTableDirectory () const
void SetPhysicsTableRetrieved (const G4String &directory="")
void SetStoredInAscii ()
void ResetPhysicsTableRetrieved ()
void ResetStoredInAscii ()
void DumpList () const
void DumpCutValuesTable (G4int flag=1)
void DumpCutValuesTableIfRequested ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetCutsWithDefault ()
void SetCutValue (G4double aCut, const G4String &pname)
G4double GetCutValue (const G4String &pname) const
void SetCutValue (G4double aCut, const G4String &pname, const G4String &rname)
void SetParticleCuts (G4double cut, G4ParticleDefinition *particle, G4Region *region=0)
void SetParticleCuts (G4double cut, const G4String &particleName, G4Region *region=0)
void SetCutsForRegion (G4double aCut, const G4String &rname)
void ResetCuts ()
obsolete methods
void SetApplyCuts (G4bool value, const G4String &name)
G4bool GetApplyCuts (const G4String &name) const
void RemoveProcessManager ()
void AddProcessManager (G4ParticleDefinition *newParticle, G4ProcessManager *newManager=0)
void CheckParticleList ()
void DisableCheckParticleList ()
G4int GetInstanceID () const
virtual void InitializeWorker ()
virtual void TerminateWorker ()
Static Public Member Functions
static const G4VUPLManager & GetSubInstanceManager ()
Protected Member Functions
void AddTransportation ()
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
void BuildIntegralPhysicsTable (G4VProcess *, G4ParticleDefinition *)
virtual void RetrievePhysicsTable (G4ParticleDefinition *, const G4String &directory, G4bool ascii=false)
void InitializeProcessManager ()
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
Protected Attributes
G4ParticleTable * theParticleTable
G4int verboseLevel
G4double defaultCutValue
G4bool isSetDefaultCutValue
G4ProductionCutsTable * fCutsTable
G4bool fRetrievePhysicsTable
G4bool fStoredInAscii
G4bool fIsCheckedForRetrievePhysicsTable
G4bool fIsRestoredCutValues
G4String directoryPhysicsTable
G4bool fDisableCheckParticleList
G4int g4vuplInstanceID
Static Protected Attributes
static G4RUN_DLL G4VUPLManager subInstanceManager
Private Types
enum { FixedStringLengthForStore = 32 }
Detailed Description
Definition at line 155 of file G4VUserPhysicsList.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
FixedStringLengthForStore
Definition at line 388 of file G4VUserPhysicsList.hh.
Constructor & Destructor Documentation
G4VUserPhysicsList() [1/2]
G4VUserPhysicsList::G4VUserPhysicsList ()
Definition at line 103 of file G4VUserPhysicsList.cc.
~G4VUserPhysicsList()
G4VUserPhysicsList::~G4VUserPhysicsList () virtual
Definition at line 159 of file G4VUserPhysicsList.cc.
G4VUserPhysicsList() [2/2]
G4VUserPhysicsList::G4VUserPhysicsList (const G4VUserPhysicsList & right)
Definition at line 173 of file G4VUserPhysicsList.cc.
Member Function Documentation
AddProcessManager()
void G4VUserPhysicsList::AddProcessManager (G4ParticleDefinition * newParticle, G4ProcessManager * newManager = 0)
Definition at line 230 of file G4VUserPhysicsList.cc.
Referenced by G4UserPhysicsListMessenger::SetNewValue().
AddTransportation()
void G4VUserPhysicsList::AddTransportation () protected
Definition at line 958 of file G4VUserPhysicsList.cc.
Referenced by DMXPhysicsList::AddTransportation(), Par02PhysicsList::AddTransportation(), eRositaPhysicsList::ConstructProcess(), XPhysicsList::ConstructProcess(), GeantinoPhysicsList::ConstructProcess(), G4HumanPhantomPhysicsList::ConstructProcess(), GammaKnifePhysicsList::ConstructProcess(), BrachyPhysicsList::ConstructProcess(), ExN02PhysicsList::ConstructProcess(), PhysicsListEMstd::ConstructProcess(), ExN01PhysicsList::ConstructProcess(), XrayFluoPhysicsList::ConstructProcess(), HadrontherapyPhysicsList::ConstructProcess(), PhysicsList::ConstructProcess(), UltraPhysicsList::ConstructProcess(), GammaRayTelPhysicsList::ConstructProcess(), doiPETPhysicsList::ConstructProcess(), B03PhysicsList::ConstructProcess(), OpNovicePhysicsList::ConstructProcess(), ML2PhysicsList::ConstructProcess(), PurgMagPhysicsList::ConstructProcess(), TSPhysicsList::ConstructProcess(), IORTPhysicsList::ConstructProcess(), XrayTelPhysicsList::ConstructProcess(), G4AdjointPhysicsList::ConstructProcess(), and G4VModularPhysicsList::ConstructProcess().
BuildIntegralPhysicsTable()
void G4VUserPhysicsList::BuildIntegralPhysicsTable (G4VProcess * process, G4ParticleDefinition * particle) protected
Definition at line 769 of file G4VUserPhysicsList.cc.
Referenced by RetrievePhysicsTable().
BuildPhysicsTable() [1/2]
void G4VUserPhysicsList::BuildPhysicsTable ()
Definition at line 526 of file G4VUserPhysicsList.cc.
Referenced by G4RunManagerKernel::BuildPhysicsTables(), and G4UserPhysicsListMessenger::SetNewValue().
BuildPhysicsTable() [2/2]
void G4VUserPhysicsList::BuildPhysicsTable (G4ParticleDefinition * particle)
Definition at line 595 of file G4VUserPhysicsList.cc.
CheckParticleList()
void G4VUserPhysicsList::CheckParticleList ()
Definition at line 950 of file G4VUserPhysicsList.cc.
Referenced by G4RunManagerKernel::InitializePhysics().
Construct()
void G4VUserPhysicsList::Construct (void) inline
Definition at line 407 of file G4VUserPhysicsList.hh.
Referenced by G4RunManagerKernel::InitializePhysics().
ConstructParticle()
virtual void G4VUserPhysicsList::ConstructParticle () pure virtual
Implemented in G4VModularPhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, G4AdjointPhysicsList, PhysicsList, DMXPhysicsList, WLSPhysicsList, XrayTelPhysicsList, PhysicsList, PhysicsList, PhysicsList, PurgMagPhysicsList, TSPhysicsList, PhysicsList, PhysicsList, ML2PhysicsList, PhysicsList, PhysicsList, OpNovicePhysicsList, F04PhysicsList, IORTPhysicsList, PhysicsList, G4ErrorPhysicsList, B03PhysicsList, PhysicsList, PhysicsList, UltraPhysicsList, doiPETPhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, Par02PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsListEMstd, ExN01PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, ExN02PhysicsList, BrachyPhysicsList, PhysicsList, XrayFluoPhysicsList, F05PhysicsList, F06PhysicsList, PhysicsList, PhysicsList, PhysicsListEMstd, GammaRayTelPhysicsList, PhysicsList, HadrontherapyPhysicsList, PhysicsList, G4HumanPhantomPhysicsList, ExUCNPhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, GeantinoPhysicsList, GeantinoPhysicsList, GeantinoPhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, pyG4VUserPhysicsList::CB_G4VUserPhysicsList, XPhysicsList, eRositaPhysicsList, and GammaKnifePhysicsList.
Referenced by export_G4VUserPhysicsList(), and G4RunManagerKernel::SetupPhysics().
ConstructProcess()
virtual void G4VUserPhysicsList::ConstructProcess () pure virtual
Implemented in G4VModularPhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, G4AdjointPhysicsList, PhysicsList, DMXPhysicsList, WLSPhysicsList, PhysicsList, IORTPhysicsList, XrayTelPhysicsList, PhysicsList, PhysicsList, PhysicsList, PurgMagPhysicsList, PhysicsList, PhysicsList, TSPhysicsList, ML2PhysicsList, PhysicsList, OpNovicePhysicsList, F04PhysicsList, G4ErrorPhysicsList, PhysicsList, Par02PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, B03PhysicsList, PhysicsList, PhysicsList, UltraPhysicsList, doiPETPhysicsList, GammaRayTelPhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, HadrontherapyPhysicsList, XrayFluoPhysicsList, PhysicsList, PhysicsListEMstd, ExN01PhysicsList, BrachyPhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, ExN02PhysicsList, GammaKnifePhysicsList, F05PhysicsList, F06PhysicsList, PhysicsList, PhysicsList, PhysicsListEMstd, PhysicsList, PhysicsList, PhysicsList, pyG4VUserPhysicsList::CB_G4VUserPhysicsList, PhysicsList, PhysicsList, G4HumanPhantomPhysicsList, ExUCNPhysicsList, PhysicsList, GeantinoPhysicsList, GeantinoPhysicsList, GeantinoPhysicsList, PhysicsList, XPhysicsList, and eRositaPhysicsList.
Referenced by Construct(), and export_G4VUserPhysicsList().
DisableCheckParticleList()
void G4VUserPhysicsList::DisableCheckParticleList () inline
Definition at line 474 of file G4VUserPhysicsList.hh.
DumpCutValuesTable()
void G4VUserPhysicsList::DumpCutValuesTable (G4int flag = 1)
Definition at line 816 of file G4VUserPhysicsList.cc.
Referenced by G4RunManagerKernel::BuildPhysicsTables(), export_G4VUserPhysicsList(), GammaKnifePhysicsList::SetCuts(), eRositaPhysicsList::SetCuts(), G4HumanPhantomPhysicsList::SetCuts(), GammaRayTelPhysicsList::SetCuts(), WLSPhysicsList::SetCuts(), ExN02PhysicsList::SetCuts(), BrachyPhysicsList::SetCuts(), PhysicsList::SetCuts(), XrayFluoPhysicsList::SetCuts(), doiPETPhysicsList::SetCuts(), IORTPhysicsList::SetCuts(), DMXPhysicsList::SetCuts(), OpNovicePhysicsList::SetCuts(), PurgMagPhysicsList::SetCuts(), XrayTelPhysicsList::SetCuts(), G4AdjointPhysicsList::SetCuts(), SetCuts(), and G4UserPhysicsListMessenger::SetNewValue().
DumpCutValuesTableIfRequested()
void G4VUserPhysicsList::DumpCutValuesTableIfRequested ()
Definition at line 822 of file G4VUserPhysicsList.cc.
Referenced by G4RunManagerKernel::BuildPhysicsTables(), and export_G4VUserPhysicsList().
DumpList()
void G4VUserPhysicsList::DumpList () const
Definition at line 798 of file G4VUserPhysicsList.cc.
Referenced by export_G4VUserPhysicsList(), and G4UserPhysicsListMessenger::SetNewValue().
GetApplyCuts()
G4bool G4VUserPhysicsList::GetApplyCuts (const G4String & name) const
Definition at line 943 of file G4VUserPhysicsList.cc.
Referenced by export_G4VUserPhysicsList().
GetCutValue()
G4double G4VUserPhysicsList::GetCutValue (const G4String & pname) const
Definition at line 401 of file G4VUserPhysicsList.cc.
Referenced by SetCuts(), and G4UserPhysicsListMessenger::SetNewValue().
GetDefaultCutValue()
G4double G4VUserPhysicsList::GetDefaultCutValue () const inline
Definition at line 422 of file G4VUserPhysicsList.hh.
Referenced by export_G4VUserPhysicsList(), G4UserPhysicsListMessenger::GetCurrentValue(), and CexmcSetup::SetupSpecialVolumes().
GetInstanceID()
G4int G4VUserPhysicsList::GetInstanceID () const inline
Definition at line 480 of file G4VUserPhysicsList.hh.
GetParticleIterator()
G4ParticleTable::G4PTblDicIterator * G4VUserPhysicsList::GetParticleIterator () const protected
Definition at line 977 of file G4VUserPhysicsList.cc.
Referenced by XrayFluoPhysicsList::AddDecay(), PhysicsList::AddDecay(), PhysicsList::AddIonGasModels(), Par02PhysicsList::AddParameterisation(), B03PhysicsList::AddScoringProcess(), F04PhysicsList::AddStepMax(), HadrontherapyPhysicsList::AddStepMax(), XrayFluoPhysicsList::AddStepMax(), PhysicsList::AddStepMax(), WLSPhysicsList::AddStepMax(), ML2PhysicsList::AddStepMax(), ExN02PhysicsList::AddStepMax(), IORTPhysicsList::AddStepMax(), PhysicsList::AddTrackingCut(), DMXPhysicsList::AddTransportation(), OpNovicePhysicsList::ConstructDecay(), eRositaPhysicsList::ConstructEM(), PhysicsList::ConstructEM(), B03PhysicsList::ConstructEM(), ExN02PhysicsList::ConstructEM(), G4ErrorPhysicsList::ConstructEM(), OpNovicePhysicsList::ConstructEM(), DMXPhysicsList::ConstructEM(), XrayTelPhysicsList::ConstructEM(), G4AdjointPhysicsList::ConstructEM(), PurgMagPhysicsList::ConstructEM(), eRositaPhysicsList::ConstructGeneral(), B03PhysicsList::ConstructGeneral(), ExN02PhysicsList::ConstructGeneral(), DMXPhysicsList::ConstructGeneral(), Par02PhysicsList::ConstructGeneral(), XrayTelPhysicsList::ConstructGeneral(), G4AdjointPhysicsList::ConstructGeneral(), B03PhysicsList::ConstructHad(), DMXPhysicsList::ConstructHad(), OpNovicePhysicsList::ConstructOp(), DMXPhysicsList::ConstructOp(), XPhysicsList::ConstructProcess(), G4ErrorPhysicsList::ConstructProcess(), and TSPhysicsList::ConstructProcess().
GetPhysicsTableDirectory()
const G4String & G4VUserPhysicsList::GetPhysicsTableDirectory () const inline
Definition at line 446 of file G4VUserPhysicsList.hh.
Referenced by export_G4VUserPhysicsList(), and G4UserPhysicsListMessenger::GetCurrentValue().
GetSubInstanceManager()
const G4VUPLManager & G4VUserPhysicsList::GetSubInstanceManager () inline static
Definition at line 486 of file G4VUserPhysicsList.hh.
Referenced by G4PhysicsListWorkspace::G4PhysicsListWorkspace().
GetVerboseLevel()
G4int G4VUserPhysicsList::GetVerboseLevel () const inline
Definition at line 428 of file G4VUserPhysicsList.hh.
Referenced by export_G4VUserPhysicsList(), G4UserPhysicsListMessenger::GetCurrentValue(), and ExN01PhysicsList::SetCuts().
InitializeProcessManager()
void G4VUserPhysicsList::InitializeProcessManager () protected
Definition at line 241 of file G4VUserPhysicsList.cc.
Referenced by Construct().
InitializeWorker()
void G4VUserPhysicsList::InitializeWorker () virtual
Definition at line 145 of file G4VUserPhysicsList.cc.
Referenced by G4WorkerRunManager::SetUserInitialization().
IsPhysicsTableRetrieved()
G4bool G4VUserPhysicsList::IsPhysicsTableRetrieved () const inline
Definition at line 434 of file G4VUserPhysicsList.hh.
Referenced by export_G4VUserPhysicsList(), and G4UserPhysicsListMessenger::GetCurrentValue().
IsStoredInAscii()
G4bool G4VUserPhysicsList::IsStoredInAscii () const inline
Definition at line 440 of file G4VUserPhysicsList.hh.
Referenced by export_G4VUserPhysicsList(), and G4UserPhysicsListMessenger::GetCurrentValue().
operator=()
G4VUserPhysicsList & G4VUserPhysicsList::operator= (const G4VUserPhysicsList & right)
Definition at line 209 of file G4VUserPhysicsList.cc.
PreparePhysicsTable()
void G4VUserPhysicsList::PreparePhysicsTable (G4ParticleDefinition * particle)
Definition at line 703 of file G4VUserPhysicsList.cc.
Referenced by BuildPhysicsTable(), and G4UserPhysicsListMessenger::SetNewValue().
RegisterProcess()
G4bool G4VUserPhysicsList::RegisterProcess (G4VProcess * process, G4ParticleDefinition * particle) protected
Definition at line 970 of file G4VUserPhysicsList.cc.
RemoveProcessManager()
void G4VUserPhysicsList::RemoveProcessManager ()
Definition at line 300 of file G4VUserPhysicsList.cc.
Referenced by TerminateWorker(), and ~G4VUserPhysicsList().
ResetCuts()
void G4VUserPhysicsList::ResetCuts ()
obsolete methods
Definition at line 1004 of file G4VUserPhysicsList.cc.
Referenced by XrayTelPhysicsList::SetCutForElectron(), XrayTelPhysicsList::SetCutForGamma(), and PurgMagPhysicsList::SetGammaCut().
ResetPhysicsTableRetrieved()
void G4VUserPhysicsList::ResetPhysicsTableRetrieved () inline
Definition at line 459 of file G4VUserPhysicsList.hh.
Referenced by G4UserPhysicsListMessenger::SetNewValue().
ResetStoredInAscii()
void G4VUserPhysicsList::ResetStoredInAscii () inline
Definition at line 468 of file G4VUserPhysicsList.hh.
Referenced by export_G4VUserPhysicsList(), and G4UserPhysicsListMessenger::SetNewValue().
RetrievePhysicsTable()
void G4VUserPhysicsList::RetrievePhysicsTable (G4ParticleDefinition * particle, const G4String & directory, G4bool ascii = false) protected virtual
Definition at line 892 of file G4VUserPhysicsList.cc.
Referenced by BuildPhysicsTable().
SetApplyCuts()
void G4VUserPhysicsList::SetApplyCuts (G4bool value, const G4String & name)
Definition at line 925 of file G4VUserPhysicsList.cc.
Referenced by G4UserPhysicsListMessenger::SetNewValue().
SetCuts()
void G4VUserPhysicsList::SetCuts () virtual
Reimplemented in PhysicsList, G4AdjointPhysicsList, PhysicsList, PhysicsList, PhysicsList, XrayTelPhysicsList, PurgMagPhysicsList, TSPhysicsList, DMXPhysicsList, OpNovicePhysicsList, G4ErrorPhysicsList, PhysicsList, PhysicsList, Par02PhysicsList, PhysicsList, doiPETPhysicsList, IORTPhysicsList, B03PhysicsList, PhysicsList, PhysicsList, UltraPhysicsList, XrayFluoPhysicsList, PhysicsList, PhysicsList, BrachyPhysicsList, WLSPhysicsList, ExN02PhysicsList, PhysicsListEMstd, ExN01PhysicsList, pyG4VUserPhysicsList::CB_G4VUserPhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, F05PhysicsList, F06PhysicsList, PhysicsList, PhysicsList, PhysicsList, GammaRayTelPhysicsList, ExUCNPhysicsList, QPhysicsList, G4HumanPhantomPhysicsList, B3PhysicsList, B3PhysicsList, B3PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, eRositaPhysicsList, XPhysicsList, PhysicsList, PhysicsList, PhysicsList, pyG4VModularPhysicsList::CB_G4VModularPhysicsList, and GammaKnifePhysicsList.
Definition at line 341 of file G4VUserPhysicsList.cc.
Referenced by export_G4VModularPhysicsList(), export_G4VUserPhysicsList(), G4RunManagerKernel::InitializePhysics(), main(), B3PhysicsList::SetCuts(), SetCutsWithDefault(), and G4UserPhysicsListMessenger::SetNewValue().
SetCutsForRegion()
void G4VUserPhysicsList::SetCutsForRegion (G4double aCut, const G4String & rname)
Definition at line 453 of file G4VUserPhysicsList.cc.
Referenced by export_G4VUserPhysicsList(), and G4UserPhysicsListMessenger::SetNewValue().
SetCutsWithDefault()
void G4VUserPhysicsList::SetCutsWithDefault ()
Definition at line 446 of file G4VUserPhysicsList.cc.
Referenced by export_G4VUserPhysicsList(), XPhysicsList::SetCuts(), eRositaPhysicsList::SetCuts(), QPhysicsList::SetCuts(), ExUCNPhysicsList::SetCuts(), F06PhysicsList::SetCuts(), ExN01PhysicsList::SetCuts(), F05PhysicsList::SetCuts(), PhysicsListEMstd::SetCuts(), ExN02PhysicsList::SetCuts(), UltraPhysicsList::SetCuts(), B03PhysicsList::SetCuts(), Par02PhysicsList::SetCuts(), G4ErrorPhysicsList::SetCuts(), and OpNovicePhysicsList::SetCuts().
SetCutValue() [1/2]
void G4VUserPhysicsList::SetCutValue (G4double aCut, const G4String & pname)
Definition at line 421 of file G4VUserPhysicsList.cc.
Referenced by QGSP_BIC_AllHP::QGSP_BIC_AllHP(), QGSP_BIC_HP::QGSP_BIC_HP(), GammaKnifePhysicsList::SetCuts(), G4HumanPhantomPhysicsList::SetCuts(), GammaRayTelPhysicsList::SetCuts(), WLSPhysicsList::SetCuts(), BrachyPhysicsList::SetCuts(), PhysicsList::SetCuts(), XrayFluoPhysicsList::SetCuts(), doiPETPhysicsList::SetCuts(), IORTPhysicsList::SetCuts(), DMXPhysicsList::SetCuts(), TSPhysicsList::SetCuts(), PurgMagPhysicsList::SetCuts(), XrayTelPhysicsList::SetCuts(), G4AdjointPhysicsList::SetCuts(), SetCutsForRegion(), SetDefaultCutValue(), G4UserPhysicsListMessenger::SetNewValue(), and Shielding::Shielding().
SetCutValue() [2/2]
void G4VUserPhysicsList::SetCutValue (G4double aCut, const G4String & pname, const G4String & rname)
Definition at line 428 of file G4VUserPhysicsList.cc.
SetDefaultCutValue()
void G4VUserPhysicsList::SetDefaultCutValue (G4double newCutValue)
Definition at line 369 of file G4VUserPhysicsList.cc.
Referenced by export_G4VUserPhysicsList(), main(), PhysicsList::PhysicsList(), SetCuts(), SetCutsWithDefault(), G4UserPhysicsListMessenger::SetNewValue(), SetParticleCuts(), UltraPhysicsList::UltraPhysicsList(), and XPhysicsList::XPhysicsList().
SetParticleCuts() [1/2]
void G4VUserPhysicsList::SetParticleCuts (G4double cut, const G4String & particleName, G4Region * region = 0)
Definition at line 471 of file G4VUserPhysicsList.cc.
SetParticleCuts() [2/2]
void G4VUserPhysicsList::SetParticleCuts (G4double cut, G4ParticleDefinition * particle, G4Region * region = 0)
Definition at line 465 of file G4VUserPhysicsList.cc.
Referenced by GammaKnifePhysicsList::SetCutForElectron(), GammaRayTelPhysicsList::SetCutForElectron(), WLSPhysicsList::SetCutForElectron(), PhysicsList::SetCutForElectron(), XrayFluoPhysicsList::SetCutForElectron(), IORTPhysicsList::SetCutForElectron(), GammaKnifePhysicsList::SetCutForGamma(), GammaRayTelPhysicsList::SetCutForGamma(), WLSPhysicsList::SetCutForGamma(), PhysicsList::SetCutForGamma(), XrayFluoPhysicsList::SetCutForGamma(), IORTPhysicsList::SetCutForGamma(), GammaKnifePhysicsList::SetCutForPositron(), GammaRayTelPhysicsList::SetCutForPositron(), WLSPhysicsList::SetCutForPositron(), PhysicsList::SetCutForPositron(), XrayFluoPhysicsList::SetCutForPositron(), IORTPhysicsList::SetCutForPositron(), XrayFluoPhysicsList::SetCutForProton(), and SetCutValue().
SetPhysicsTableRetrieved()
void G4VUserPhysicsList::SetPhysicsTableRetrieved (const G4String & directory = "")
Definition at line 881 of file G4VUserPhysicsList.cc.
Referenced by G4UserPhysicsListMessenger::SetNewValue().
SetStoredInAscii()
void G4VUserPhysicsList::SetStoredInAscii () inline
Definition at line 452 of file G4VUserPhysicsList.hh.
Referenced by export_G4VUserPhysicsList(), and G4UserPhysicsListMessenger::SetNewValue().
SetVerboseLevel()
void G4VUserPhysicsList::SetVerboseLevel (G4int value)
Definition at line 983 of file G4VUserPhysicsList.cc.
Referenced by B03PhysicsList::B03PhysicsList(), DMXPhysicsList::DMXPhysicsList(), eRositaPhysicsList::eRositaPhysicsList(), ExN02PhysicsList::ExN02PhysicsList(), export_G4VUserPhysicsList(), G4AdjointPhysicsList::G4AdjointPhysicsList(), Par02PhysicsList::Par02PhysicsList(), PurgMagPhysicsList::PurgMagPhysicsList(), ExN01PhysicsList::SetCuts(), G4UserPhysicsListMessenger::SetNewValue(), XPhysicsList::XPhysicsList(), and XrayTelPhysicsList::XrayTelPhysicsList().
StorePhysicsTable()
G4bool G4VUserPhysicsList::StorePhysicsTable (const G4String & directory = ".")
Definition at line 831 of file G4VUserPhysicsList.cc.
Referenced by export_G4VUserPhysicsList(), and G4UserPhysicsListMessenger::SetNewValue().
TerminateWorker()
void G4VUserPhysicsList::TerminateWorker () virtual
Reimplemented in G4VModularPhysicsList.
Definition at line 152 of file G4VUserPhysicsList.cc.
Referenced by G4VModularPhysicsList::TerminateWorker(), and G4WorkerRunManager::~G4WorkerRunManager().
UseCoupledTransportation()
void G4VUserPhysicsList::UseCoupledTransportation (G4bool vl = true)
Definition at line 964 of file G4VUserPhysicsList.cc.
Referenced by G4RunManagerKernel::InitializePhysics().
Field Documentation
defaultCutValue
G4double G4VUserPhysicsList::defaultCutValue protected
Definition at line 358 of file G4VUserPhysicsList.hh.
Referenced by DMXPhysicsList::DMXPhysicsList(), eRositaPhysicsList::eRositaPhysicsList(), ExN02PhysicsList::ExN02PhysicsList(), F04PhysicsList::F04PhysicsList(), G4AdjointPhysicsList::G4AdjointPhysicsList(), G4ErrorPhysicsList::G4ErrorPhysicsList(), G4VUserPhysicsList(), GammaKnifePhysicsList::GammaKnifePhysicsList(), GammaRayTelPhysicsList::GammaRayTelPhysicsList(), GetDefaultCutValue(), HadrontherapyPhysicsList::HadrontherapyPhysicsList(), IORTPhysicsList::IORTPhysicsList(), ML2PhysicsList::ML2PhysicsList(), G4VModularPhysicsList::operator=(), operator=(), Par02PhysicsList::Par02PhysicsList(), PhysicsListEMstd::PhysicsListEMstd(), PurgMagPhysicsList::PurgMagPhysicsList(), QBBC::QBBC(), QGSP_BIC::QGSP_BIC(), QGSP_BIC_AllHP::QGSP_BIC_AllHP(), QGSP_BIC_HP::QGSP_BIC_HP(), QPhysicsList::QPhysicsList(), GammaKnifePhysicsList::SetCuts(), G4HumanPhantomPhysicsList::SetCuts(), GammaRayTelPhysicsList::SetCuts(), WLSPhysicsList::SetCuts(), BrachyPhysicsList::SetCuts(), XrayFluoPhysicsList::SetCuts(), doiPETPhysicsList::SetCuts(), B03PhysicsList::SetCuts(), IORTPhysicsList::SetCuts(), DMXPhysicsList::SetCuts(), PurgMagPhysicsList::SetCuts(), G4AdjointPhysicsList::SetCuts(), SetCuts(), SetCutsWithDefault(), SetDefaultCutValue(), SetParticleCuts(), Shielding::Shielding(), WLSPhysicsList::WLSPhysicsList(), XrayFluoPhysicsList::XrayFluoPhysicsList(), and XrayTelPhysicsList::XrayTelPhysicsList().
directoryPhysicsTable
G4String G4VUserPhysicsList::directoryPhysicsTable protected
Definition at line 373 of file G4VUserPhysicsList.hh.
Referenced by BuildPhysicsTable(), GetPhysicsTableDirectory(), G4VModularPhysicsList::operator=(), operator=(), SetPhysicsTableRetrieved(), and StorePhysicsTable().
fCutsTable
G4ProductionCutsTable* G4VUserPhysicsList::fCutsTable protected
Definition at line 363 of file G4VUserPhysicsList.hh.
Referenced by BuildPhysicsTable(), G4VUserPhysicsList(), SetVerboseLevel(), and StorePhysicsTable().
fDisableCheckParticleList
G4bool G4VUserPhysicsList::fDisableCheckParticleList protected
Definition at line 382 of file G4VUserPhysicsList.hh.
Referenced by CheckParticleList(), DisableCheckParticleList(), G4VModularPhysicsList::operator=(), and operator=().
fIsCheckedForRetrievePhysicsTable
G4bool G4VUserPhysicsList::fIsCheckedForRetrievePhysicsTable protected
Definition at line 369 of file G4VUserPhysicsList.hh.
Referenced by G4VModularPhysicsList::operator=(), operator=(), ResetPhysicsTableRetrieved(), and SetPhysicsTableRetrieved().
fIsRestoredCutValues
G4bool G4VUserPhysicsList::fIsRestoredCutValues protected
Definition at line 370 of file G4VUserPhysicsList.hh.
Referenced by BuildPhysicsTable(), G4VModularPhysicsList::operator=(), operator=(), ResetPhysicsTableRetrieved(), and SetPhysicsTableRetrieved().
fRetrievePhysicsTable
G4bool G4VUserPhysicsList::fRetrievePhysicsTable protected
Definition at line 366 of file G4VUserPhysicsList.hh.
Referenced by BuildPhysicsTable(), IsPhysicsTableRetrieved(), G4VModularPhysicsList::operator=(), operator=(), ResetPhysicsTableRetrieved(), and SetPhysicsTableRetrieved().
fStoredInAscii
G4bool G4VUserPhysicsList::fStoredInAscii protected
Definition at line 367 of file G4VUserPhysicsList.hh.
Referenced by BuildPhysicsTable(), IsStoredInAscii(), G4VModularPhysicsList::operator=(), operator=(), ResetStoredInAscii(), SetStoredInAscii(), and StorePhysicsTable().
g4vuplInstanceID
G4int G4VUserPhysicsList::g4vuplInstanceID protected
Definition at line 392 of file G4VUserPhysicsList.hh.
Referenced by G4VUserPhysicsList(), GetInstanceID(), GetParticleIterator(), and G4VModularPhysicsList::operator=().
isSetDefaultCutValue
G4bool G4VUserPhysicsList::isSetDefaultCutValue protected
Definition at line 359 of file G4VUserPhysicsList.hh.
Referenced by G4VModularPhysicsList::operator=(), operator=(), SetCuts(), SetDefaultCutValue(), and SetParticleCuts().
subInstanceManager
G4VUPLManager G4VUserPhysicsList::subInstanceManager static protected
Definition at line 393 of file G4VUserPhysicsList.hh.
Referenced by G4VUserPhysicsList(), GetParticleIterator(), GetSubInstanceManager(), and G4VModularPhysicsList::operator=().
theParticleTable
G4ParticleTable* G4VUserPhysicsList::theParticleTable protected
Definition at line 346 of file G4VUserPhysicsList.hh.
Referenced by BuildPhysicsTable(), G4VUserPhysicsList(), GetApplyCuts(), SetApplyCuts(), and ~G4VUserPhysicsList().
verboseLevel
G4int G4VUserPhysicsList::verboseLevel protected
Definition at line 354 of file G4VUserPhysicsList.hh.
Referenced by BuildIntegralPhysicsTable(), BuildPhysicsTable(), Construct(), XPhysicsList::ConstructProcess(), G4ErrorPhysicsList::ConstructProcess(), G4VUserPhysicsList(), GetCutValue(), GetVerboseLevel(), InitializeProcessManager(), operator=(), PreparePhysicsTable(), RemoveProcessManager(), ResetCuts(), RetrievePhysicsTable(), SetApplyCuts(), eRositaPhysicsList::SetCuts(), ExN02PhysicsList::SetCuts(), B03PhysicsList::SetCuts(), Par02PhysicsList::SetCuts(), DMXPhysicsList::SetCuts(), OpNovicePhysicsList::SetCuts(), PurgMagPhysicsList::SetCuts(), XrayTelPhysicsList::SetCuts(), G4AdjointPhysicsList::SetCuts(), SetCuts(), SetDefaultCutValue(), PurgMagPhysicsList::SetElectronLowLimit(), PurgMagPhysicsList::SetGammaLowLimit(), PurgMagPhysicsList::SetGELowLimit(), PurgMagPhysicsList::SetGEPLowLimit(), SetParticleCuts(), PurgMagPhysicsList::SetPositronLowLimit(), PurgMagPhysicsList::SetProtonLowLimit(), SetVerboseLevel(), and StorePhysicsTable().
The documentation for this class was generated from the following files:
source/run/include/G4VUserPhysicsList.hh
source/run/src/G4VUserPhysicsList.cc