Geant4: XBase Class Reference
XBase Class Reference abstract
#include <XBase.hh>
Public Member Functions
XBase ()
virtual ~XBase ()
void SetIVal (int aval)
int GetIVal () const
void SetDVal (double aval)
double GetDVal () const
void AMethod ()
virtual int VMethod (const XBase *abase) const =0
XBase ()
virtual ~XBase ()
void SetIVal (int i)
int GetIVal () const
virtual std::string PVMethod ()=0
XBase ()
~XBase ()
virtual void VMethodA (const AClass *a)
virtual void VMethodB (const BClass *b)
Protected Attributes
int ival
double dval
Detailed Description
Definition at line 40 of file XBase.hh.
Constructor & Destructor Documentation
XBase() [1/3]
XBase::XBase ()
Definition at line 42 of file XBase.cc.
~XBase() [1/3]
XBase::~XBase () virtual
Definition at line 51 of file XBase.cc.
XBase() [2/3]
XBase::XBase ()
~XBase() [2/3]
virtual XBase::~XBase () virtual
XBase() [3/3]
XBase::XBase () inline
Definition at line 62 of file test10.cc.
~XBase() [3/3]
XBase::~XBase () inline
Definition at line 63 of file test10.cc.
Member Function Documentation
AMethod()
void XBase::AMethod ()
Definition at line 58 of file XBase.cc.
Referenced by BOOST_PYTHON_MODULE().
GetDVal()
double XBase::GetDVal () const inline
Definition at line 67 of file XBase.hh.
Referenced by BOOST_PYTHON_MODULE().
GetIVal() [1/2]
int XBase::GetIVal () const inline
Definition at line 64 of file XBase.hh.
Referenced by BOOST_PYTHON_MODULE().
GetIVal() [2/2]
int XBase::GetIVal () const inline
PVMethod()
virtual std::string XBase::PVMethod () pure virtual
Implemented in w_XBase.
Referenced by BOOST_PYTHON_MODULE().
SetDVal()
void XBase::SetDVal (double aval) inline
Definition at line 66 of file XBase.hh.
Referenced by BOOST_PYTHON_MODULE().
SetIVal() [1/2]
void XBase::SetIVal (int aval) inline
Definition at line 63 of file XBase.hh.
Referenced by BOOST_PYTHON_MODULE().
SetIVal() [2/2]
void XBase::SetIVal (int i) inline
VMethod()
virtual int XBase::VMethod (const XBase * abase) const pure virtual
Implemented in AClass, and BClass.
Referenced by BOOST_PYTHON_MODULE().
VMethodA()
virtual void XBase::VMethodA (const AClass * a) inline virtual
Reimplemented in CB_XBase.
Definition at line 65 of file test10.cc.
Referenced by BOOST_PYTHON_MODULE(), CB_XBase::d_VMethodA(), and CB_XBase::VMethodA().
VMethodB()
virtual void XBase::VMethodB (const BClass * b) inline virtual
Reimplemented in CB_XBase.
Definition at line 69 of file test10.cc.
Referenced by BOOST_PYTHON_MODULE(), CB_XBase::d_VMethodB(), and CB_XBase::VMethodB().
Field Documentation
dval
double XBase::dval protected
Definition at line 43 of file XBase.hh.
Referenced by BClass::AMethod(), AMethod(), BClass::BClass(), GetDVal(), and SetDVal().
ival
int XBase::ival protected
Definition at line 42 of file XBase.hh.
Referenced by BClass::AMethod(), AMethod(), BClass::BClass(), GetIVal(), and SetIVal().
The documentation for this class was generated from the following files:
environments/g4py/tests/test02/module/XBase.hh
environments/g4py/tests/test10/module/test10.cc
environments/g4py/tests/test02/module/XBase.cc