Geant4: G4Proton Class Reference
G4Proton Class Reference
#include <G4Proton.hh>
Static Public Member Functions
static G4Proton * Definition ()
static G4Proton * ProtonDefinition ()
static G4Proton * Proton ()
Static Public Member Functions inherited from G4Ions
static G4Ions::G4FloatLevelBase FloatLevelBase (char flbChar)
static G4Ions::G4FloatLevelBase FloatLevelBase (G4int flbIdx)
static char FloatLevelBaseChar (G4Ions::G4FloatLevelBase flb)
Static Public Member Functions inherited from G4ParticleDefinition
static const G4PDefManager & GetSubInstanceManager ()
static void Clean ()
Private Member Functions
G4Proton ()
~G4Proton ()
Static Private Attributes
static G4Proton * theInstance = 0
Additional Inherited Members
Public Types inherited from G4Ions
enum G4FloatLevelBase {
G4FloatLevelBase::no_Float =0, G4FloatLevelBase::plus_X, G4FloatLevelBase::plus_Y, G4FloatLevelBase::plus_Z,
G4FloatLevelBase::plus_U, G4FloatLevelBase::plus_V, G4FloatLevelBase::plus_W, G4FloatLevelBase::plus_R,
G4FloatLevelBase::plus_S, G4FloatLevelBase::plus_T, G4FloatLevelBase::plus_A, G4FloatLevelBase::plus_B,
G4FloatLevelBase::plus_C, G4FloatLevelBase::plus_D, G4FloatLevelBase::plus_E
}
Public Member Functions inherited from G4Ions
G4Ions (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospin3, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable, G4bool shortlived, const G4String &subType="", G4int anti_encoding=0, G4double excitation=0.0, G4int isomer=0)
virtual ~G4Ions ()
G4Ions * IonsDefinition ()
G4Ions * Ions ()
G4double GetExcitationEnergy () const
G4int GetIsomerLevel () const
G4Ions::G4FloatLevelBase GetFloatLevelBase () const
G4int GetFloatLevelBaseIndex () const
void SetFloatLevelBase (G4Ions::G4FloatLevelBase flb)
void SetFloatLevelBase (char flbChar)
void SetFloatLevelBase (G4int flbIdx)
Public Member Functions inherited from G4ParticleDefinition
G4ParticleDefinition (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospinZ, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable, G4bool shortlived=false, const G4String &subType="", G4int anti_encoding=0, G4double magneticMoment=0.0)
virtual ~G4ParticleDefinition ()
const G4String & GetParticleName () const
G4double GetPDGMass () const
G4double GetPDGWidth () const
G4double GetPDGCharge () const
G4double GetPDGSpin () const
G4int GetPDGiSpin () const
G4int GetPDGiParity () const
G4int GetPDGiConjugation () const
G4double GetPDGIsospin () const
G4double GetPDGIsospin3 () const
G4int GetPDGiIsospin () const
G4int GetPDGiIsospin3 () const
G4int GetPDGiGParity () const
G4double GetPDGMagneticMoment () const
void SetPDGMagneticMoment (G4double mageticMoment)
G4double CalculateAnomaly () const
const G4String & GetParticleType () const
const G4String & GetParticleSubType () const
G4int GetLeptonNumber () const
G4int GetBaryonNumber () const
G4int GetPDGEncoding () const
G4int GetAntiPDGEncoding () const
void SetAntiPDGEncoding (G4int aEncoding)
G4int GetQuarkContent (G4int flavor) const
G4int GetAntiQuarkContent (G4int flavor) const
G4bool IsShortLived () const
G4bool GetPDGStable () const
void SetPDGStable (const G4bool aFlag)
G4double GetPDGLifeTime () const
void SetPDGLifeTime (G4double aLifeTime)
G4double GetIonLifeTime () const
G4DecayTable * GetDecayTable () const
void SetDecayTable (G4DecayTable *aDecayTable)
G4ProcessManager * GetProcessManager () const
void SetProcessManager (G4ProcessManager *aProcessManager)
G4ParticleTable * GetParticleTable () const
G4int GetAtomicNumber () const
G4int GetAtomicMass () const
void DumpTable () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetApplyCutsFlag (G4bool)
G4bool GetApplyCutsFlag () const
G4bool IsGeneralIon () const
G4bool IsMuonicAtom () const
G4bool operator== (const G4ParticleDefinition &right) const
G4bool operator!= (const G4ParticleDefinition &right) const
G4ProcessManager * GetMasterProcessManager () const
void SetMasterProcessManager (G4ProcessManager *aNewPM)
G4int GetInstanceID () const
void SetParticleDefinitionID (G4int id=-1)
G4int GetParticleDefinitionID () const
Protected Types inherited from G4ParticleDefinition
enum { NumberOfQuarkFlavor = 6 }
Protected Member Functions inherited from G4Ions
G4Ions ()
Protected Member Functions inherited from G4ParticleDefinition
G4int FillQuarkContents ()
void SetParticleSubType (const G4String &subtype)
void SetAtomicNumber (G4int)
void SetAtomicMass (G4int)
G4ParticleDefinition (const G4ParticleDefinition &right)
G4ParticleDefinition ()
Protected Attributes inherited from G4ParticleDefinition
G4int theQuarkContent [NumberOfQuarkFlavor]
G4int theAntiQuarkContent [NumberOfQuarkFlavor]
G4bool isGeneralIon
G4bool isMuonicAtom
Detailed Description
Definition at line 50 of file G4Proton.hh.
Constructor & Destructor Documentation
G4Proton()
G4Proton::G4Proton () inline private
Definition at line 54 of file G4Proton.hh.
~G4Proton()
G4Proton::~G4Proton () inline private
Definition at line 55 of file G4Proton.hh.
Member Function Documentation
Definition()
G4Proton * G4Proton::Definition () static
Definition at line 48 of file G4Proton.cc.
Referenced by XrayFluoAnalysisManager::analyseStepping(), CexmcChargeExchangeProductionModel< OutputParticle >::CexmcChargeExchangeProductionModel(), G4RadioactiveDecayBase::CollimateDecay(), G4RadioactiveDecay::CollimateDecay(), G4InuclNuclei::copy(), G4InuclElementaryParticle::makeDefinition(), Proton(), ProtonDefinition(), G4ChipsProtonInelasticXS::ThresholdMomentum(), and G4InuclElementaryParticle::type().
Proton()
G4Proton * G4Proton::Proton () static
Definition at line 92 of file G4Proton.cc.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmModelActivator::ActivateMicroElec(), G4RPGReaction::AddBlackTrackParticles(), PhysicsList::AddDarkMatter(), HistoManager::AddLeakingParticle(), HistoManager::AddTargetStep(), G4ParticleHPFinalState::adjust_final_state(), G4hImpactIonisation::AlongStepDoIt(), G4LightMedia::AntiLambdaExchange(), G4LightMedia::AntiOmegaMinusExchange(), G4LightMedia::AntiProtonExchange(), G4hImpactIonisation::AntiProtonParametrisedDEDX(), G4LightMedia::AntiSigmaMinusExchange(), G4LightMedia::AntiSigmaPlusExchange(), G4LightMedia::AntiXiMinusExchange(), G4LightMedia::AntiXiZeroExchange(), G4ParticleHP2NPInelasticFS::ApplyYourself(), G4ParticleHP2PInelasticFS::ApplyYourself(), G4ParticleHPN2PInelasticFS::ApplyYourself(), G4ParticleHPNPAInelasticFS::ApplyYourself(), G4ParticleHPNPInelasticFS::ApplyYourself(), G4ParticleHPPAInelasticFS::ApplyYourself(), G4ParticleHPPDInelasticFS::ApplyYourself(), G4ParticleHPPInelasticFS::ApplyYourself(), G4ParticleHPPTInelasticFS::ApplyYourself(), G4ParticleHP3NPInelasticFS::ApplyYourself(), G4ElectroVDNuclearModel::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LEpp::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4LEnp::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4WilsonAblationModel::BreakItUp(), G4ProtonPHPBuilder::Build(), G4ProtonBuilder::Build(), G4FTFBinaryProtonBuilder::Build(), G4FTFPProtonBuilder::Build(), G4QGSBinaryProtonBuilder::Build(), G4QGSPLundStrFragmProtonBuilder::Build(), G4QGSPProtonBuilder::Build(), G4INCLXXProtonBuilder::Build(), G4hRDEnergyLoss::BuildInverseRangeTable(), G4hImpactIonisation::BuildLossTable(), G4hImpactIonisation::BuildPhysicsTable(), G4hRDEnergyLoss::BuildTimeTables(), G4ecpssrBaseKxsModel::CalculateCrossSection(), G4ecpssrFormFactorKxsModel::CalculateCrossSection(), G4ElectroVDNuclearModel::CalculateEMVertex(), G4PaulKxsModel::CalculateKCrossSection(), G4ecpssrFormFactorLixsModel::CalculateL1CrossSection(), G4ecpssrBaseLixsModel::CalculateL1CrossSection(), G4ecpssrFormFactorLixsModel::CalculateL2CrossSection(), G4ecpssrBaseLixsModel::CalculateL2CrossSection(), G4OrlicLiXsModel::CalculateL2CrossSection(), G4ecpssrFormFactorLixsModel::CalculateL3CrossSection(), G4ecpssrBaseLixsModel::CalculateL3CrossSection(), G4OrlicLiXsModel::CalculateL3CrossSection(), G4ecpssrFormFactorMixsModel::CalculateMiCrossSection(), G4ecpssrBaseLixsModel::CalculateVelocity(), G4BinaryCascade::Capture(), G4RPGKMinusInelastic::Cascade(), G4RPGSigmaPlusInelastic::Cascade(), G4RPGXiMinusInelastic::Cascade(), G4RPGAntiLambdaInelastic::Cascade(), G4RPGAntiProtonInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4RPGAntiOmegaMinusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGOmegaMinusInelastic::Cascade(), G4RPGLambdaInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGKPlusInelastic::Cascade(), G4RPGKZeroInelastic::Cascade(), G4RPGSigmaMinusInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), G4RPGAntiKZeroInelastic::Cascade(), G4BinaryCascade::CheckPauliPrinciple(), G4QuasiElRatios::ChExer(), G4Fancy3DNucleus::ChooseFermiMomenta(), G4Fancy3DNucleus::ChooseNucleons(), G4Fancy3DNucleus::ChoosePositions(), G4hImpactIonisation::ComputeDEDX(), G4AdjointPhysicsList::ConstructEM(), DMXPhysicsList::ConstructHad(), G4EmDNAPhysics_option3::ConstructParticle(), G4EmDNAPhysics_stationary::ConstructParticle(), G4EmDNAPhysics_stationary_option2::ConstructParticle(), G4EmDNAPhysics_stationary_option4::ConstructParticle(), G4EmDNAPhysics_stationary_option6::ConstructParticle(), G4EmLivermorePhysics::ConstructParticle(), G4EmLivermorePolarizedPhysics::ConstructParticle(), G4EmLowEPPhysics::ConstructParticle(), G4EmPenelopePhysics::ConstructParticle(), G4EmDNAPhysics::ConstructParticle(), G4EmDNAPhysics_option2::ConstructParticle(), G4EmDNAPhysics_option1::ConstructParticle(), G4EmDNAPhysics_option7::ConstructParticle(), G4EmDNAPhysics_option8::ConstructParticle(), G4EmDNAPhysics_option5::ConstructParticle(), G4EmDNAPhysics_option4::ConstructParticle(), G4EmDNAPhysicsActivator::ConstructParticle(), G4EmLEPTSPhysics::ConstructParticle(), G4EmDNAPhysics_option6::ConstructParticle(), G4EmStandardPhysicsSS::ConstructParticle(), PhysListEm5DStandard::ConstructParticle(), PhysListEm19DStandard::ConstructParticle(), G4EmStandardPhysics_option4_channeling::ConstructParticle(), G4EmStandardPhysics::ConstructParticle(), G4EmStandardPhysics_option3::ConstructParticle(), G4EmStandardPhysicsGS::ConstructParticle(), G4EmStandardPhysics_option4::ConstructParticle(), G4EmStandardPhysicsWVI::ConstructParticle(), G4EmStandardPhysics_option1::ConstructParticle(), G4EmStandardPhysics_option2::ConstructParticle(), G4EmDNAPhysicsActivator::ConstructProcess(), G4HadronPhysicsFTFQGSP_BERT::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), G4BinaryCascade::CorrectBarionsOnBoundary(), G4DNARuddIonisationModel::CorrectionFactor(), G4empCrossSection::CrossSection(), G4HadronicProcessStore::DumpHtml(), RMC01AnalysisManager::EndOfEventForAdjointSimulation(), Run::EndOfRun(), G4GDMLWriteStructure::ExportEnergyCuts(), G4VElasticCollision::FinalState(), G4VCrossSectionSource::FindKeyParticle(), G4Absorber::FindProducts(), G4AdjointhIonisationModel::G4AdjointhIonisationModel(), G4AntiNuclElastic::G4AntiNuclElastic(), G4BaryonSplitter::G4BaryonSplitter(), G4BGGNucleonElasticXS::G4BGGNucleonElasticXS(), G4BGGNucleonInelasticXS::G4BGGNucleonInelasticXS(), G4BGGPionElasticXS::G4BGGPionElasticXS(), G4BGGPionInelasticXS::G4BGGPionInelasticXS(), G4ChargeExchange::G4ChargeExchange(), G4ChargeExchangeProcess::G4ChargeExchangeProcess(), G4ChipsKaonPlusInelasticXS::G4ChipsKaonPlusInelasticXS(), G4ChipsNeutronElasticXS::G4ChipsNeutronElasticXS(), G4ChipsProtonElasticXS::G4ChipsProtonElasticXS(), G4ComponentBarNucleonNucleusXsc::G4ComponentBarNucleonNucleusXsc(), G4ComponentGGHadronNucleusXsc::G4ComponentGGHadronNucleusXsc(), G4ComponentGGNuclNuclXsc::G4ComponentGGNuclNuclXsc(), G4CoulombScattering::G4CoulombScattering(), G4DiffuseElastic::G4DiffuseElastic(), G4DiffuseElasticV2::G4DiffuseElasticV2(), G4eCoulombScatteringModel::G4eCoulombScatteringModel(), G4ElasticData::G4ElasticData(), G4GeneralSpaceNNCrossSection::G4GeneralSpaceNNCrossSection(), G4GeneratorPrecompoundInterface::G4GeneratorPrecompoundInterface(), G4HadronElastic::G4HadronElastic(), G4HadronNucleonXsc::G4HadronNucleonXsc(), G4hCoulombScatteringModel::G4hCoulombScatteringModel(), G4hhElastic::G4hhElastic(), G4IonCoulombCrossSection::G4IonCoulombCrossSection(), G4IonCoulombScatteringModel::G4IonCoulombScatteringModel(), G4IonProtonCrossSection::G4IonProtonCrossSection(), G4LENDManager::G4LENDManager(), G4LowEIonFragmentation::G4LowEIonFragmentation(), G4MuMinusCapturePrecompound::G4MuMinusCapturePrecompound(), G4NucleonNuclearCrossSection::G4NucleonNuclearCrossSection(), G4NuclNuclDiffuseElastic::G4NuclNuclDiffuseElastic(), G4ParticleHPData::G4ParticleHPData(), G4ParticleHPInelastic::G4ParticleHPInelastic(), G4ParticleHPInelasticData::G4ParticleHPInelasticData(), G4PreCompoundModel::G4PreCompoundModel(), G4PreCompoundTransitions::G4PreCompoundTransitions(), G4ProtonInelasticCrossSection::G4ProtonInelasticCrossSection(), G4QMDGroundStateNucleus::G4QMDGroundStateNucleus(), G4RPGInelastic::G4RPGInelastic(), G4WentzelOKandVIxSection::G4WentzelOKandVIxSection(), G4WilsonAblationModel::G4WilsonAblationModel(), G4QMDNucleus::GetAtomicNumber(), G4hImpactIonisation::GetConstraints(), G4empCrossSection::GetCrossSection(), G4AdjointCSManager::GetForwardParticleEquivalent(), G4Fancy3DNucleus::GetMass(), G4QMDNucleus::GetMassNumber(), G4QMDNucleus::GetNuclearMass(), G4ChipsAntiBaryonElasticXS::GetQ2max(), G4ParticleHPD2AInelasticFS::Init(), G4ParticleHPT2AInelasticFS::Init(), G4ParticleHPNTInelasticFS::Init(), G4ParticleHPNInelasticFS::Init(), G4ParticleHPNT2AInelasticFS::Init(), G4ParticleHPTInelasticFS::Init(), G4ParticleHPN2PInelasticFS::Init(), G4ParticleHPPTInelasticFS::Init(), G4ParticleHPNAInelasticFS::Init(), G4ParticleHPN3AInelasticFS::Init(), G4ParticleHP2N2AInelasticFS::Init(), G4ParticleHP2NDInelasticFS::Init(), G4ParticleHP2NInelasticFS::Init(), G4ParticleHP2NPInelasticFS::Init(), G4ParticleHP2PInelasticFS::Init(), G4ParticleHP3AInelasticFS::Init(), G4ParticleHPDAInelasticFS::Init(), G4ParticleHPDInelasticFS::Init(), G4ParticleHPHe3InelasticFS::Init(), G4ParticleHPNPAInelasticFS::Init(), G4ParticleHPN2AInelasticFS::Init(), G4ParticleHPNHe3InelasticFS::Init(), G4ParticleHPND2AInelasticFS::Init(), G4ParticleHP2NAInelasticFS::Init(), G4ParticleHPNPInelasticFS::Init(), G4ParticleHPPDInelasticFS::Init(), G4ParticleHPPInelasticFS::Init(), G4ParticleHPNXInelasticFS::Init(), G4ParticleHPPAInelasticFS::Init(), G4ParticleHPNDInelasticFS::Init(), G4ParticleHP4NInelasticFS::Init(), G4ParticleHP2AInelasticFS::Init(), G4ParticleHP3NInelasticFS::Init(), G4ParticleHP3NPInelasticFS::Init(), G4ParticleHPAInelasticFS::Init(), G4ParticleHP3NAInelasticFS::Init(), G4RKPropagation::Init(), G4FTFModel::Init(), G4ParticleHPIsoData::Init(), G4FTFParameters::InitForInteraction(), G4TablesForExtrapolator::Initialisation(), G4EnergyLossForExtrapolator::Initialisation(), G4hhElastic::Initialise(), G4hIonisation::InitialiseEnergyLossProcess(), G4DNAElastic::IsApplicable(), G4DNAIonisation::IsApplicable(), G4MicroElecInelastic::IsApplicable(), G4MuElecInelastic::IsApplicable(), G4DiffuseElasticV2::IsApplicable(), G4DiffuseElastic::IsApplicable(), G4hhElastic::IsApplicable(), G4LMsdGenerator::IsApplicable(), G4ScreenedNuclearRecoil::IsApplicable(), G4GeneralNNCollision::IsInCharge(), G4LightMedia::KaonZeroShortExchange(), G4LightMedia::LambdaExchange(), main(), G4RPGInelastic::MarkLeadingStrangeParticle(), G4LightMedia::NeutronExchange(), G4RPGReaction::NuclearReaction(), G4DNADingfelderChargeDecreaseModel::NumberOfFinalStates(), G4LightMedia::OmegaMinusExchange(), G4DNADingfelderChargeDecreaseModel::OutgoingParticleBindingEnergyConstant(), G4DNADingfelderChargeIncreaseModel::OutgoingParticleDefinition(), G4DNADingfelderChargeDecreaseModel::OutgoingParticleDefinition(), RMC01SD::ProcessHits(), G4BinaryCascade::Propagate(), G4hImpactIonisation::ProtonParametrisedDEDX(), G4RPGPionSuppression::ReactionStage(), G4RPGStrangeProduction::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4Nucleus::ReturnTargetParticle(), G4ParticleHPIsotropic::Sample(), G4ParticleHPNBodyPhaseSpace::Sample(), G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContAngularPar::Sample(), G4hhElastic::SampleBisectionalT(), G4hhElastic::SampleInvariantT(), G4LMsdGenerator::SampleMx(), G4DNADingfelderChargeDecreaseModel::SampleSecondaries(), G4VPartonStringModel::Scatter(), G4QuasiElRatios::Scatter(), G4WilsonAblationModel::SelectSecondariesByEvaporation(), XrayFluoPhysicsList::SetCutForProton(), RMC01AnalysisManager::SetPrimaryExpSpectrumForAdjointSim(), RMC01AnalysisManager::SetPrimaryPowerLawSpectrumForAdjointSim(), G4LightMedia::SigmaMinusExchange(), G4LightMedia::SigmaPlusExchange(), G4ChipsProtonInelasticXS::ThresholdMomentum(), G4AblaInterface::toG4ParticleDefinition(), G4INCLXXInterface::toG4ParticleDefinition(), G4INCLXXInterface::toINCLParticleType(), G4RKPropagation::Transport(), G4DNADingfelderChargeDecreaseModel::WaterBindingEnergyConstant(), G4LightMedia::XiMinusExchange(), and G4LightMedia::XiZeroExchange().
ProtonDefinition()
G4Proton * G4Proton::ProtonDefinition () static
Definition at line 87 of file G4Proton.cc.
Referenced by G4BinaryCascade::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4LFission::Atomas(), G4ExcitationHandler::BreakItUp(), F04StackingAction::ClassifyNewTrack(), PhysicsList::ConstructBarions(), PurgMagPhysicsList::ConstructBarions(), eRositaPhysicsList::ConstructBaryons(), ExN02PhysicsList::ConstructBaryons(), G4AdjointPhysicsList::ConstructBaryons(), G4BaryonConstructor::ConstructNucleons(), GammaKnifeParticles::ConstructParticle(), ExUCNPhysicsList::ConstructParticle(), F06PhysicsList::ConstructParticle(), PhysicsList::ConstructParticle(), G4ErrorPhysicsList::ConstructParticle(), G4XMesonBaryonElastic::CrossSection(), G4XnpElasticLowE::CrossSection(), G4XnpTotalLowE::CrossSection(), G4DNADingfelderChargeDecreaseModel::CrossSectionPerVolume(), G4DNAMillerGreenExcitationModel::CrossSectionPerVolume(), G4DNARuddIonisationExtendedModel::CrossSectionPerVolume(), G4DNARuddIonisationModel::CrossSectionPerVolume(), G4DNABornIonisationModel2::CrossSectionPerVolume(), G4DNABornIonisationModel1::CrossSectionPerVolume(), G4DNABornIonisationModel1::DifferentialCrossSection(), G4MicroElecInelasticModel::DifferentialCrossSection(), G4MuElecInelasticModel::DifferentialCrossSection(), G4DNARuddIonisationModel::DifferentialCrossSection(), G4DNAPTBIonisationModel::DifferentialCrossSection(), G4LossTableManager::DumpHtml(), G4CollisionMesonBaryonToResonance::G4CollisionMesonBaryonToResonance(), G4CollisionNNElastic::G4CollisionNNElastic(), G4CollisionnpElastic::G4CollisionnpElastic(), G4ParticleTypeConverter::G4ParticleTypeConverter(), G4XNNElasticLowE::G4XNNElasticLowE(), G4XNNTotalLowE::G4XNNTotalLowE(), G4XPDGElastic::G4XPDGElastic(), G4XPDGTotal::G4XPDGTotal(), G4WilsonAbrasionModel::GetAbradedNucleons(), G4MesonAbsorption::GetFinalState(), G4Scintillation::GetScintillationYieldByParticleType(), G4BinaryCascade::HighEnergyModelFSProducts(), G4DNADingfelderChargeDecreaseModel::Initialise(), G4DNAMillerGreenExcitationModel::Initialise(), G4DNARuddIonisationExtendedModel::Initialise(), G4DNARuddIonisationModel::Initialise(), G4DNABornIonisationModel1::Initialise(), G4MicroElecInelasticModel::Initialise(), G4MuElecInelasticModel::Initialise(), G4DNAPTBIonisationModel::Initialise(), G4DNAChargeDecrease::IsApplicable(), G4DNAExcitation::IsApplicable(), G4CollisionNNElastic::IsInCharge(), G4CollisionnpElastic::IsInCharge(), G4VXResonance::IsospinCorrection(), G4DNADingfelderChargeDecreaseModel::PartialCrossSection(), G4DNAMillerGreenExcitationModel::PartialCrossSection(), G4hImpactIonisation::PostStepDoIt(), G4XNNElasticLowE::Print(), G4BinaryCascade::Propagate1H1(), G4MuElecInelasticModel::RandomizeEjectedElectronDirection(), G4DNAPTBIonisationModel::RandomizeEjectedElectronDirection(), G4DNARuddIonisationModel::RandomizeEjectedElectronEnergy(), G4DNABornIonisationModel2::RandomizeEjectedElectronEnergy(), G4MuElecInelasticModel::RandomizeEjectedElectronEnergy(), G4DNABornIonisationModel1::RandomizeEjectedElectronEnergy(), G4MicroElecInelasticModel::RandomizeEjectedElectronEnergy(), G4DNAPTBIonisationModel::RandomizeEjectedElectronEnergy(), G4DNADingfelderChargeDecreaseModel::RandomSelect(), G4DNAMillerGreenExcitationModel::RandomSelect(), G4DNARuddIonisationExtendedModel::RejectionFunction(), G4DNARuddIonisationModel::SampleSecondaries(), G4MicroElecInelasticModel::SampleSecondaries(), G4MuElecInelasticModel::SampleSecondaries(), G4DNADingfelderChargeDecreaseModel::Sum(), G4DNABornIonisationModel1::TransferedEnergy(), G4MicroElecInelasticModel::TransferedEnergy(), G4XNNElasticLowE::~G4XNNElasticLowE(), and G4XNNTotalLowE::~G4XNNTotalLowE().
Field Documentation
theInstance
G4Proton * G4Proton::theInstance = 0 static private
Definition at line 53 of file G4Proton.hh.
Referenced by Definition().
The documentation for this class was generated from the following files:
source/particles/hadrons/barions/include/G4Proton.hh
source/particles/hadrons/barions/src/G4Proton.cc