Geant4: source/tracking/src/G4RichTrajectoryPoint.cc File Reference
G4RichTrajectoryPoint.cc File Reference
#include "G4RichTrajectoryPoint.hh"
#include "G4Track.hh"
#include "G4Step.hh"
#include "G4VProcess.hh"
#include "G4AttDefStore.hh"
#include "G4AttDef.hh"
#include "G4AttValue.hh"
#include "G4UnitsTable.hh"
#include <sstream>
Functions
G4Allocator< G4RichTrajectoryPoint > *& aRichTrajectoryPointAllocator ()
static G4String Status (G4StepStatus stps)
static G4String Path (const G4TouchableHandle &th)
Function Documentation
aRichTrajectoryPointAllocator()
G4Allocator<G4RichTrajectoryPoint>*& aRichTrajectoryPointAllocator ()
Definition at line 63 of file G4RichTrajectoryPoint.cc.
Referenced by G4RichTrajectoryPoint::operator delete(), and G4RichTrajectoryPoint::operator new().
Path()
static G4String Path (const G4TouchableHandle & th) static
Definition at line 223 of file G4RichTrajectoryPoint.cc.
Referenced by G4RichTrajectoryPoint::CreateAttValues().
Status()
static G4String Status (G4StepStatus stps) static
Definition at line 206 of file G4RichTrajectoryPoint.cc.
Referenced by G4RichTrajectoryPoint::CreateAttValues(), G4VUserMPIrunMerger::Receive(), and G4MPIscorerMerger::Receive().