Geant4: G4SPBaryonTable Class Reference
G4SPBaryonTable Class Reference
#include <G4SPBaryonTable.hh>
Data Structures
struct DeleteSPBaryon
Public Member Functions
~G4SPBaryonTable ()
void insert (G4SPBaryon *aBaryon)
G4double length ()
const G4SPBaryon * GetBaryon (G4ParticleDefinition *aDefinition)
Private Attributes
std::vector< G4SPBaryon * > theBaryons
Detailed Description
Definition at line 32 of file G4SPBaryonTable.hh.
Constructor & Destructor Documentation
~G4SPBaryonTable()
G4SPBaryonTable::~G4SPBaryonTable () inline
Definition at line 37 of file G4SPBaryonTable.hh.
Member Function Documentation
GetBaryon()
const G4SPBaryon * G4SPBaryonTable::GetBaryon (G4ParticleDefinition * aDefinition) inline
Definition at line 48 of file G4SPBaryonTable.hh.
Referenced by G4BaryonSplitter::FindDiquark(), G4BaryonSplitter::GetSPBaryon(), and G4BaryonSplitter::SplitBarion().
insert()
void G4SPBaryonTable::insert (G4SPBaryon * aBaryon) inline
Definition at line 38 of file G4SPBaryonTable.hh.
Referenced by G4BaryonSplitter::G4BaryonSplitter().
length()
G4double G4SPBaryonTable::length () inline
Definition at line 39 of file G4SPBaryonTable.hh.
Field Documentation
theBaryons
std::vector<G4SPBaryon *> G4SPBaryonTable::theBaryons private
Definition at line 44 of file G4SPBaryonTable.hh.
Referenced by GetBaryon(), insert(), length(), and ~G4SPBaryonTable().
The documentation for this class was generated from the following file:
source/processes/hadronic/models/parton_string/qgsm/include/G4SPBaryonTable.hh