Geant4: B4dEventAction Class Reference
B4dEventAction Class Reference
Event action class.
#include <B4dEventAction.hh>
Public Member Functions
B4dEventAction ()
virtual ~B4dEventAction ()
virtual void BeginOfEventAction (const G4Event *event)
virtual void EndOfEventAction (const G4Event *event)
B4dEventAction ()
virtual ~B4dEventAction ()
virtual void BeginOfEventAction (const G4Event *event)
virtual void EndOfEventAction (const G4Event *event)
Public Member Functions inherited from G4UserEventAction
G4UserEventAction ()
virtual ~G4UserEventAction ()
virtual void SetEventManager (G4EventManager *value)
Private Member Functions
G4THitsMap< G4double > * GetHitsCollection (G4int hcID, const G4Event *event) const
G4double GetSum (G4THitsMap< G4double > *hitsMap) const
void PrintEventStatistics (G4double absoEdep, G4double absoTrackLength, G4double gapEdep, G4double gapTrackLength) const
G4THitsMap< G4double > * GetHitsCollection (G4int hcID, const G4Event *event) const
G4double GetSum (G4THitsMap< G4double > *hitsMap) const
void PrintEventStatistics (G4double absoEdep, G4double absoTrackLength, G4double gapEdep, G4double gapTrackLength) const
Private Attributes
G4int fAbsoEdepHCID
G4int fGapEdepHCID
G4int fAbsoTrackLengthHCID
G4int fGapTrackLengthHCID
Additional Inherited Members
Protected Attributes inherited from G4UserEventAction
G4EventManager * fpEventManager
Detailed Description
Event action class.
In EndOfEventAction(), it prints the accumulated quantities of the energy deposit and track lengths of charged particles in Absober and Gap layers stored in the hits collections.
Definition at line 44 of file B4dEventAction.hh.
Constructor & Destructor Documentation
B4dEventAction() [1/2]
B4dEventAction::B4dEventAction ()
Definition at line 44 of file B4dEventAction.cc.
~B4dEventAction() [1/2]
B4dEventAction::~B4dEventAction () virtual
Definition at line 54 of file B4dEventAction.cc.
B4dEventAction() [2/2]
B4dEventAction::B4dEventAction ()
~B4dEventAction() [2/2]
virtual B4dEventAction::~B4dEventAction () virtual
Member Function Documentation
BeginOfEventAction() [1/2]
void B4dEventAction::BeginOfEventAction (const G4Event * event) virtual
Reimplemented from G4UserEventAction.
Definition at line 112 of file B4dEventAction.cc.
BeginOfEventAction() [2/2]
virtual void B4dEventAction::BeginOfEventAction (const G4Event * event) virtual
Reimplemented from G4UserEventAction.
EndOfEventAction() [1/2]
void B4dEventAction::EndOfEventAction (const G4Event * event) virtual
Reimplemented from G4UserEventAction.
Definition at line 117 of file B4dEventAction.cc.
EndOfEventAction() [2/2]
virtual void B4dEventAction::EndOfEventAction (const G4Event * event) virtual
Reimplemented from G4UserEventAction.
GetHitsCollection() [1/2]
G4THitsMap<G4double>* B4dEventAction::GetHitsCollection (G4int hcID, const G4Event * event) const private
GetHitsCollection() [2/2]
G4THitsMap< G4double > * B4dEventAction::GetHitsCollection (G4int hcID, const G4Event * event) const private
Definition at line 60 of file B4dEventAction.cc.
Referenced by EndOfEventAction().
GetSum() [1/2]
G4double B4dEventAction::GetSum (G4THitsMap< G4double > * hitsMap) const private
GetSum() [2/2]
G4double B4dEventAction::GetSum (G4THitsMap< G4double > * hitsMap) const private
Definition at line 79 of file B4dEventAction.cc.
Referenced by EndOfEventAction().
PrintEventStatistics() [1/2]
void B4dEventAction::PrintEventStatistics (G4double absoEdep, G4double absoTrackLength, G4double gapEdep, G4double gapTrackLength) const private
PrintEventStatistics() [2/2]
void B4dEventAction::PrintEventStatistics (G4double absoEdep, G4double absoTrackLength, G4double gapEdep, G4double gapTrackLength) const private
Definition at line 91 of file B4dEventAction.cc.
Referenced by EndOfEventAction().
Field Documentation
fAbsoEdepHCID
G4int B4dEventAction::fAbsoEdepHCID private
Definition at line 62 of file B4dEventAction.hh.
Referenced by EndOfEventAction().
fAbsoTrackLengthHCID
G4int B4dEventAction::fAbsoTrackLengthHCID private
Definition at line 64 of file B4dEventAction.hh.
Referenced by EndOfEventAction().
fGapEdepHCID
G4int B4dEventAction::fGapEdepHCID private
Definition at line 63 of file B4dEventAction.hh.
Referenced by EndOfEventAction().
fGapTrackLengthHCID
G4int B4dEventAction::fGapTrackLengthHCID private
Definition at line 65 of file B4dEventAction.hh.
Referenced by EndOfEventAction().
The documentation for this class was generated from the following files:
examples/basic/B4/B4d/include/B4dEventAction.hh
examples/basic/B4/B4d/src/B4dEventAction.cc