Geant4: G4VITReactionProcess Class Reference
G4VITReactionProcess Class Reference abstract
G4VITReactionProcess defines the reaction between two G4IT.
#include <G4VITReactionProcess.hh>
Public Member Functions
G4VITReactionProcess ()
Default constructor.
virtual ~G4VITReactionProcess ()
Default destructor.
G4VITReactionProcess (const G4VITReactionProcess &other)
Copy constructor.
G4VITReactionProcess & operator= (const G4VITReactionProcess &other)
Will Clone the reaction process i.e.
virtual void Initialize ()
First initialization (done once for all at the begin of the run) eg.
virtual G4bool IsApplicable (G4ITType, G4ITType) const
virtual G4bool TestReactibility (const G4Track &, const G4Track &, const double, const double, bool)=0
virtual G4ITReactionChange * MakeReaction (const G4Track &, const G4Track &)=0
void SetReactionTable (const G4ITReactionTable *)
void ResetChanges ()
Protected Attributes
const G4ITReactionTable * fpReactionTable
G4ITReactionChange * fpChanges
G4String fName
Detailed Description
G4VITReactionProcess defines the reaction between two G4IT.
It should be stored in a G4VITModel.
Definition at line 61 of file G4VITReactionProcess.hh.
Constructor & Destructor Documentation
G4VITReactionProcess() [1/2]
G4VITReactionProcess::G4VITReactionProcess ()
Default constructor.
Definition at line 37 of file G4VITReactionProcess.cc.
~G4VITReactionProcess()
G4VITReactionProcess::~G4VITReactionProcess () virtual
Default destructor.
Definition at line 42 of file G4VITReactionProcess.cc.
G4VITReactionProcess() [2/2]
G4VITReactionProcess::G4VITReactionProcess (const G4VITReactionProcess & other)
Copy constructor.
Parameters
other Object to copy from
Definition at line 47 of file G4VITReactionProcess.cc.
Member Function Documentation
Initialize()
virtual void G4VITReactionProcess::Initialize () inline virtual
First initialization (done once for all at the begin of the run) eg.
check if the reaction table is given ...
Definition at line 91 of file G4VITReactionProcess.hh.
Referenced by G4VITStepModel::Initialize().
IsApplicable()
virtual G4bool G4VITReactionProcess::IsApplicable (G4ITType , G4ITType) const inline virtual
Definition at line 93 of file G4VITReactionProcess.hh.
MakeReaction()
virtual G4ITReactionChange* G4VITReactionProcess::MakeReaction (const G4Track & , const G4Track &) pure virtual
Implemented in G4DNAMolecularReaction.
Referenced by G4ITModelProcessor::FindReaction().
operator=()
G4VITReactionProcess & G4VITReactionProcess::operator= (const G4VITReactionProcess & other)
Will Clone the reaction process i.e.
new reaction process will be created with same features as the parent one. Use preprocessor macro : AddCloneReactionProcess the copy constructor of the derived class must be implemented. This macro is defined in AddClone_def Assignment operator
Parameters
other Object to assign from
Returns
A reference to this
Definition at line 54 of file G4VITReactionProcess.cc.
ResetChanges()
void G4VITReactionProcess::ResetChanges () inline
Definition at line 122 of file G4VITReactionProcess.hh.
Referenced by G4ITModelProcessor::FindReaction().
SetReactionTable()
void G4VITReactionProcess::SetReactionTable (const G4ITReactionTable * table) inline
Definition at line 117 of file G4VITReactionProcess.hh.
Referenced by G4VITStepModel::Initialize().
TestReactibility()
virtual G4bool G4VITReactionProcess::TestReactibility (const G4Track & , const G4Track & , const double , const double , bool) pure virtual
Implemented in G4DNAMolecularReaction.
Referenced by G4ITModelProcessor::FindReaction().
Field Documentation
fName
G4String G4VITReactionProcess::fName protected
Definition at line 114 of file G4VITReactionProcess.hh.
Referenced by operator=().
fpChanges
G4ITReactionChange* G4VITReactionProcess::fpChanges protected
Definition at line 113 of file G4VITReactionProcess.hh.
Referenced by G4VITReactionProcess(), G4DNAMolecularReaction::MakeReaction(), ResetChanges(), and G4DNAMolecularReaction::~G4DNAMolecularReaction().
fpReactionTable
const G4ITReactionTable* G4VITReactionProcess::fpReactionTable protected
Definition at line 112 of file G4VITReactionProcess.hh.
Referenced by G4VITReactionProcess(), and SetReactionTable().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/dna/management/include/G4VITReactionProcess.hh
source/processes/electromagnetic/dna/management/src/G4VITReactionProcess.cc