Geant4: G4VSDFilter Class Reference
G4VSDFilter Class Reference abstract
#include <G4VSDFilter.hh>
Public Member Functions
G4VSDFilter (G4String name)
virtual ~G4VSDFilter ()
virtual G4bool Accept (const G4Step *) const =0
G4String GetName () const
Protected Attributes
G4String filterName
Detailed Description
Definition at line 40 of file G4VSDFilter.hh.
Constructor & Destructor Documentation
G4VSDFilter()
G4VSDFilter::G4VSDFilter (G4String name)
Definition at line 32 of file G4VSDFilter.cc.
~G4VSDFilter()
G4VSDFilter::~G4VSDFilter () virtual
Definition at line 38 of file G4VSDFilter.cc.
Member Function Documentation
Accept()
virtual G4bool G4VSDFilter::Accept (const G4Step *) const pure virtual
Implemented in CexmcTrackPointsFilter, G4SDParticleFilter, G4SDKineticEnergyFilter, G4SDParticleWithEnergyFilter, G4SDNeutralFilter, and G4SDChargedFilter.
Referenced by G4VSensitiveDetector::Hit(), and G4VPrimitiveScorer::HitPrimitive().
GetName()
G4String G4VSDFilter::GetName (void) const inline
Definition at line 56 of file G4VSDFilter.hh.
Referenced by G4VScoringMesh::List(), G4VScoringMesh::SetFilter(), and G4SDKineticEnergyFilter::show().
Field Documentation
filterName
G4String G4VSDFilter::filterName protected
Definition at line 53 of file G4VSDFilter.hh.
Referenced by GetName().
The documentation for this class was generated from the following files:
source/digits_hits/detector/include/G4VSDFilter.hh
source/digits_hits/detector/src/G4VSDFilter.cc