Geant4: G4AutoDelete Namespace Reference
G4AutoDelete Namespace Reference
Functions
template<class T >
void Register (T *inst)
Function Documentation
Register()
template<class T > void G4AutoDelete::Register (T * inst)
Definition at line 64 of file G4AutoDelete.hh.
Referenced by HadrontherapyPhysicsList::AddStepMax(), G4ParticleHPCapture::BuildPhysicsTable(), G4ParticleHPFission::BuildPhysicsTable(), G4ParticleHPElastic::BuildPhysicsTable(), G4ParticleHPInelastic::BuildPhysicsTable(), G4VDivisionParameterisation::ChangeRotMatrix(), F04PhysicsList::ConstructProcess(), G4HadronHElasticPhysics::ConstructProcess(), DetectorConstruction::ConstructSDandField(), B2aDetectorConstruction::ConstructSDandField(), B2bDetectorConstruction::ConstructSDandField(), B4DetectorConstruction::ConstructSDandField(), B4dDetectorConstruction::ConstructSDandField(), F04DetectorConstruction::ConstructSDandField(), Par02DetectorConstruction::ConstructSDandField(), B4cDetectorConstruction::ConstructSDandField(), F03DetectorConstruction::ConstructSDandField(), F01DetectorConstruction::ConstructSDandField(), F02DetectorConstruction::ConstructSDandField(), GammaRayTelDetectorConstruction::ConstructSDandField(), G4UniformRandPool::flat(), G4UniformRandPool::flatArray(), G4NucleiModel::generateParticleFate(), G4InuclSpecialFunctions::generateWithFixedTheta(), G4InuclSpecialFunctions::generateWithRandomAngles(), G4MultiBodyMomentumDist::GetInstance(), G4GeometryTolerance::GetInstance(), G4TwoBodyAngularDist::GetInstance(), G4IonTable::GetIonName(), G4CascadeParameters::Instance(), G4CascadeChannelTables::instance(), G4ThreadLocalSingleton< T >::Instance(), G4VIntersectionLocator::ReportImmediateHit(), and G4PenelopeBremsstrahlungFS::SampleGammaEnergy().