Geant4: G4StokesVector Class Reference
G4StokesVector Class Reference
#include <G4StokesVector.hh>
Public Member Functions
G4StokesVector ()
G4StokesVector (const G4ThreeVector &v)
~G4StokesVector ()=default
G4bool IsZero () const
G4double p1 () const
G4double p2 () const
G4double p3 () const
G4double Transverse () const
G4ThreeVector PolSqr () const
G4ThreeVector PolSqrt () const
G4ThreeVector PolError (const G4StokesVector &sum2, long n)
G4ThreeVector PolDiv (const G4StokesVector &)
void SetPhoton ()
void RotateAz (G4ThreeVector nInteractionFrame, G4ThreeVector particleDirection)
void InvRotateAz (G4ThreeVector nInteractionFrame, G4ThreeVector particleDirection)
void RotateAz (G4double cosphi, G4double sinphi)
G4double GetBeta ()
void DiceUniform ()
void DiceP1 ()
void DiceP2 ()
void DiceP3 ()
void FlipP3 ()
Static Public Attributes
static const G4StokesVector ZERO =G4ThreeVector(0.,0.,0.)
static const G4StokesVector P1 =G4ThreeVector(1.,0.,0.)
static const G4StokesVector P2 =G4ThreeVector(0.,1.,0.)
static const G4StokesVector P3 =G4ThreeVector(0.,0.,1.)
static const G4StokesVector M1 =G4ThreeVector(-1.,0.,0.)
static const G4StokesVector M2 =G4ThreeVector(0.,-1.,0.)
static const G4StokesVector M3 =G4ThreeVector(0.,0.,-1.)
Private Attributes
G4bool isPhoton
Detailed Description
Definition at line 57 of file G4StokesVector.hh.
Constructor & Destructor Documentation
G4StokesVector() [1/2]
G4StokesVector::G4StokesVector ()
Definition at line 56 of file G4StokesVector.cc.
Referenced by PolError().
G4StokesVector() [2/2]
G4StokesVector::G4StokesVector (const G4ThreeVector & v)
Definition at line 61 of file G4StokesVector.cc.
~G4StokesVector()
G4StokesVector::~G4StokesVector () default
Member Function Documentation
DiceP1()
void G4StokesVector::DiceP1 ()
Definition at line 168 of file G4StokesVector.cc.
DiceP2()
void G4StokesVector::DiceP2 ()
Definition at line 176 of file G4StokesVector.cc.
DiceP3()
void G4StokesVector::DiceP3 ()
Definition at line 184 of file G4StokesVector.cc.
DiceUniform()
void G4StokesVector::DiceUniform ()
Definition at line 158 of file G4StokesVector.cc.
FlipP3()
void G4StokesVector::FlipP3 ()
Definition at line 192 of file G4StokesVector.cc.
GetBeta()
G4double G4StokesVector::GetBeta ()
Definition at line 151 of file G4StokesVector.cc.
InvRotateAz()
void G4StokesVector::InvRotateAz (G4ThreeVector nInteractionFrame, G4ThreeVector particleDirection)
Definition at line 108 of file G4StokesVector.cc.
Referenced by G4ePolarizedBremsstrahlungModel::SampleSecondaries(), G4PolarizedGammaConversionModel::SampleSecondaries(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4PolarizedPEEffectModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), and G4PolarizedAnnihilationModel::SampleSecondaries().
IsZero()
G4bool G4StokesVector::IsZero () const
Definition at line 66 of file G4StokesVector.cc.
Referenced by G4ePolarizedIonisation::ComputeSaturationFactor(), G4PolarizedBhabhaCrossSection::Initialize(), G4PolarizedMollerCrossSection::Initialize(), G4PolarizedBhabhaCrossSection::XSection(), and G4PolarizedMollerCrossSection::XSection().
p1()
G4double G4StokesVector::p1 () const inline
Definition at line 75 of file G4StokesVector.hh.
Referenced by RotateAz(), G4PolarizedGammaConversionModel::SampleSecondaries(), G4ePolarizedBremsstrahlungModel::SampleSecondaries(), G4PolarizedPEEffectModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), and G4PolarizedAnnihilationModel::SampleSecondaries().
p2()
G4double G4StokesVector::p2 () const inline
Definition at line 76 of file G4StokesVector.hh.
Referenced by RotateAz(), G4PolarizedGammaConversionModel::SampleSecondaries(), G4ePolarizedBremsstrahlungModel::SampleSecondaries(), G4PolarizedPEEffectModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), and G4PolarizedAnnihilationModel::SampleSecondaries().
p3()
G4double G4StokesVector::p3 () const inline
Definition at line 77 of file G4StokesVector.hh.
Referenced by G4PolarizedComptonModel::ComputeCrossSectionPerAtom(), G4PolarizedCompton::ComputeSaturationFactor(), G4PolarizedGammaConversionModel::SampleSecondaries(), G4ePolarizedBremsstrahlungModel::SampleSecondaries(), G4PolarizedPEEffectModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4PolarizedAnnihilationModel::SampleSecondaries(), and G4PolarizedComptonCrossSection::TotalXSection().
PolDiv()
G4ThreeVector G4StokesVector::PolDiv (const G4StokesVector & b)
Definition at line 204 of file G4StokesVector.cc.
PolError()
G4ThreeVector G4StokesVector::PolError (const G4StokesVector & sum2, long n)
Definition at line 197 of file G4StokesVector.cc.
PolSqr()
G4ThreeVector G4StokesVector::PolSqr () const inline
Definition at line 81 of file G4StokesVector.hh.
Referenced by PolError().
PolSqrt()
G4ThreeVector G4StokesVector::PolSqrt () const inline
Definition at line 84 of file G4StokesVector.hh.
Referenced by PolError().
RotateAz() [1/2]
void G4StokesVector::RotateAz (G4double cosphi, G4double sinphi)
Definition at line 132 of file G4StokesVector.cc.
RotateAz() [2/2]
void G4StokesVector::RotateAz (G4ThreeVector nInteractionFrame, G4ThreeVector particleDirection)
Definition at line 71 of file G4StokesVector.cc.
Referenced by InvRotateAz(), G4PolarizedGammaConversionModel::SampleSecondaries(), G4ePolarizedBremsstrahlungModel::SampleSecondaries(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4PolarizedPEEffectModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), and G4PolarizedAnnihilationModel::SampleSecondaries().
SetPhoton()
void G4StokesVector::SetPhoton () inline
Definition at line 92 of file G4StokesVector.hh.
Referenced by G4PolarizedPairProductionCrossSection::Initialize(), G4PolarizedBremsstrahlungCrossSection::Initialize(), G4PolarizedGammaConversionModel::SampleSecondaries(), G4ePolarizedBremsstrahlungModel::SampleSecondaries(), G4PolarizedPEEffectModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), and G4PolarizedAnnihilationModel::SampleSecondaries().
Transverse()
G4double G4StokesVector::Transverse () const inline
Definition at line 79 of file G4StokesVector.hh.
Field Documentation
isPhoton
G4bool G4StokesVector::isPhoton private
Definition at line 108 of file G4StokesVector.hh.
Referenced by GetBeta(), RotateAz(), and SetPhoton().
M1
const G4StokesVector G4StokesVector::M1 =G4ThreeVector(-1.,0.,0.) static
Definition at line 65 of file G4StokesVector.hh.
M2
const G4StokesVector G4StokesVector::M2 =G4ThreeVector(0.,-1.,0.) static
Definition at line 66 of file G4StokesVector.hh.
M3
const G4StokesVector G4StokesVector::M3 =G4ThreeVector(0.,0.,-1.) static
Definition at line 67 of file G4StokesVector.hh.
P1
const G4StokesVector G4StokesVector::P1 =G4ThreeVector(1.,0.,0.) static
Definition at line 62 of file G4StokesVector.hh.
Referenced by G4PolarizedAnnihilationModel::ComputeAsymmetriesPerElectron(), G4VPolarizedCrossSection::GetPol2(), and G4VPolarizedCrossSection::GetPol3().
P2
const G4StokesVector G4StokesVector::P2 =G4ThreeVector(0.,1.,0.) static
Definition at line 63 of file G4StokesVector.hh.
Referenced by G4PolarizedAnnihilationModel::ComputeAsymmetriesPerElectron(), G4VPolarizedCrossSection::GetPol2(), and G4VPolarizedCrossSection::GetPol3().
P3
const G4StokesVector G4StokesVector::P3 =G4ThreeVector(0.,0.,1.) static
Definition at line 64 of file G4StokesVector.hh.
Referenced by G4PolarizedAnnihilationModel::ComputeAsymmetriesPerElectron(), G4VPolarizedCrossSection::GetPol2(), and G4VPolarizedCrossSection::GetPol3().
ZERO
const G4StokesVector G4StokesVector::ZERO =G4ThreeVector(0.,0.,0.) static
Definition at line 61 of file G4StokesVector.hh.
Referenced by G4PolarizedAnnihilationModel::ComputeAsymmetriesPerElectron(), G4PolarizedMollerBhabhaModel::ComputeCrossSectionPerElectron(), G4VPolarizedCrossSection::GetPol2(), G4VPolarizedCrossSection::GetPol3(), IsZero(), G4PolarizedGammaConversionModel::SampleSecondaries(), G4ePolarizedBremsstrahlungModel::SampleSecondaries(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4PolarizedPEEffectModel::SampleSecondaries(), and G4PolarizedComptonCrossSection::XSection().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/polarisation/include/G4StokesVector.hh
source/processes/electromagnetic/polarisation/src/G4StokesVector.cc