Geant4: source/processes/electromagnetic/dna/molecules/management/include/G4Serialize.hh File Reference
G4Serialize.hh File Reference
#include "globals.hh"
Functions
template<typename T >
void WRITE (std::ostream &out, const T &toBeSaved)
template<typename T >
void READ (std::istream &in, T &toBeSaved)
template<>
void WRITE< G4String > (std::ostream &out, const G4String &name)
template<>
void READ< G4String > (std::istream &in, G4String &name)
Function Documentation
READ()
template<typename T > void READ (std::istream & in, T & toBeSaved)
Definition at line 49 of file G4Serialize.hh.
Referenced by G4MoleculeDefinition::Load(), and G4MolecularConfiguration::Unserialize().
READ< G4String >()
template<> void READ< G4String > (std::istream & in, G4String & name)
Definition at line 67 of file G4Serialize.cc.
WRITE()
template<typename T > void WRITE (std::ostream & out, const T & toBeSaved)
Definition at line 41 of file G4Serialize.hh.
Referenced by G4MoleculeDefinition::Serialize(), and G4MolecularConfiguration::Serialize().
WRITE< G4String >()
template<> void WRITE< G4String > (std::ostream & out, const G4String & name)
Definition at line 37 of file G4Serialize.cc.