Geant4: source/processes/hadronic/models/lend/include/G4GIDI_Misc.hh File Reference
G4GIDI_Misc.hh File Reference
#include <MCGIDI_map.h>
Functions
char * G4GIDI_Misc_Z_A_m_ToName (int iZ, int iA, int im=0)
char * G4GIDI_Misc_channelCompound (char *particle1, char *particle2)
int getNamesOfAvailableTargets_walker (GIDI::MCGIDI_mapEntry *entry, int level, void *userData)
Function Documentation
G4GIDI_Misc_channelCompound()
char* G4GIDI_Misc_channelCompound (char * particle1, char * particle2)
Definition at line 70 of file G4GIDI_Misc.cc.
G4GIDI_Misc_Z_A_m_ToName()
char* G4GIDI_Misc_Z_A_m_ToName (int iZ, int iA, int im = 0)
Definition at line 44 of file G4GIDI_Misc.cc.
Referenced by G4GIDI::dataFilename(), G4GIDI::freeTarget(), G4GIDI_Misc_channelCompound(), G4GIDI_Z_AMass(), G4GIDI::getAlreadyReadTarget(), G4GIDI::getNamesOfAvailableLibraries(), G4GIDI::isThisDataAvailable(), and G4GIDI::readTarget().
getNamesOfAvailableTargets_walker()
int getNamesOfAvailableTargets_walker (GIDI::MCGIDI_mapEntry * entry, int level, void * userData)
Referenced by G4GIDI::getNamesOfAvailableTargets().