Geant4: G4VNotifier Class Reference
G4VNotifier Class Reference abstract
#include <G4VNotifier.hh>
Public Member Functions
G4VNotifier ()
virtual ~G4VNotifier ()
virtual void NotifyRegistration ()=0
virtual void NotifyDeRegistration ()=0
Detailed Description
Definition at line 42 of file G4VNotifier.hh.
Constructor & Destructor Documentation
G4VNotifier()
G4VNotifier::G4VNotifier ()
Definition at line 42 of file G4VNotifier.cc.
~G4VNotifier()
G4VNotifier::~G4VNotifier () virtual
Definition at line 50 of file G4VNotifier.cc.
Member Function Documentation
NotifyDeRegistration()
virtual void G4VNotifier::NotifyDeRegistration () pure virtual
Referenced by G4AssemblyStore::Clean(), G4LogicalVolumeStore::Clean(), G4PhysicalVolumeStore::Clean(), G4SolidStore::Clean(), G4RegionStore::Clean(), G4AssemblyStore::DeRegister(), G4PhysicalVolumeStore::DeRegister(), G4LogicalVolumeStore::DeRegister(), G4SolidStore::DeRegister(), and G4RegionStore::DeRegister().
NotifyRegistration()
virtual void G4VNotifier::NotifyRegistration () pure virtual
Referenced by G4AssemblyStore::Register(), G4PhysicalVolumeStore::Register(), G4SolidStore::Register(), G4LogicalVolumeStore::Register(), and G4RegionStore::Register().
The documentation for this class was generated from the following files:
source/global/management/include/G4VNotifier.hh
source/global/management/src/G4VNotifier.cc