Geant4: G4LogicalVolume Class Reference
G4LogicalVolume Class Reference
#include <G4LogicalVolume.hh>
Public Member Functions
G4LogicalVolume (G4VSolid *pSolid, G4Material *pMaterial, const G4String &name, G4FieldManager *pFieldMgr=0, G4VSensitiveDetector *pSDetector=0, G4UserLimits *pULimits=0, G4bool optimise=true)
virtual ~G4LogicalVolume ()
const G4String & GetName () const
void SetName (const G4String &pName)
G4int GetNoDaughters () const
G4VPhysicalVolume * GetDaughter (const G4int i) const
void AddDaughter (G4VPhysicalVolume *p)
G4bool IsDaughter (const G4VPhysicalVolume *p) const
G4bool IsAncestor (const G4VPhysicalVolume *p) const
void RemoveDaughter (const G4VPhysicalVolume *p)
void ClearDaughters ()
G4int TotalVolumeEntities () const
EVolume CharacteriseDaughters () const
G4VSolid * GetSolid () const
void SetSolid (G4VSolid *pSolid)
G4Material * GetMaterial () const
void SetMaterial (G4Material *pMaterial)
void UpdateMaterial (G4Material *pMaterial)
G4double GetMass (G4bool forced=false, G4bool propagate=true, G4Material *parMaterial=0)
void ResetMass ()
G4FieldManager * GetFieldManager () const
void SetFieldManager (G4FieldManager *pFieldMgr, G4bool forceToAllDaughters)
G4VSensitiveDetector * GetSensitiveDetector () const
void SetSensitiveDetector (G4VSensitiveDetector *pSDetector)
G4UserLimits * GetUserLimits () const
void SetUserLimits (G4UserLimits *pULimits)
G4SmartVoxelHeader * GetVoxelHeader () const
void SetVoxelHeader (G4SmartVoxelHeader *pVoxel)
G4double GetSmartless () const
void SetSmartless (G4double s)
G4bool IsToOptimise () const
void SetOptimisation (G4bool optim)
G4bool IsRootRegion () const
void SetRegionRootFlag (G4bool rreg)
G4bool IsRegion () const
void SetRegion (G4Region *reg)
G4Region * GetRegion () const
void PropagateRegion ()
const G4MaterialCutsCouple * GetMaterialCutsCouple () const
void SetMaterialCutsCouple (G4MaterialCutsCouple *cuts)
G4bool operator== (const G4LogicalVolume &lv) const
const G4VisAttributes * GetVisAttributes () const
void SetVisAttributes (const G4VisAttributes *pVA)
void SetVisAttributes (const G4VisAttributes &VA)
G4FastSimulationManager * GetFastSimulationManager () const
void SetBiasWeight (G4double w)
G4double GetBiasWeight () const
G4LogicalVolume (__void__ &)
virtual G4bool IsExtended () const
G4FieldManager * GetMasterFieldManager () const
G4VSensitiveDetector * GetMasterSensitiveDetector () const
G4VSolid * GetMasterSolid () const
G4int GetInstanceID () const
void Lock ()
void InitialiseWorker (G4LogicalVolume *ptrMasterObject, G4VSolid *pSolid, G4VSensitiveDetector *pSDetector)
void TerminateWorker (G4LogicalVolume *ptrMasterObject)
void AssignFieldManager (G4FieldManager *fldMgr)
Static Public Member Functions
static const G4LVManager & GetSubInstanceManager ()
static void Clean ()
static G4VSolid * GetSolid (G4LVData &instLVdata)
static void SetSolid (G4LVData &instLVdata, G4VSolid *pSolid)
Private Types
typedef std::vector< G4VPhysicalVolume * > G4PhysicalVolumeList
Private Member Functions
G4LogicalVolume (const G4LogicalVolume &)
G4LogicalVolume & operator= (const G4LogicalVolume &)
Private Attributes
G4PhysicalVolumeList fDaughters
G4String fName
G4UserLimits * fUserLimits
G4SmartVoxelHeader * fVoxel
G4bool fOptimise
G4bool fRootRegion
G4bool fLock
G4double fSmartless
const G4VisAttributes * fVisAttributes
G4Region * fRegion
G4double fBiasWeight
G4int instanceID
G4VSolid * fSolid
G4VSensitiveDetector * fSensitiveDetector
G4FieldManager * fFieldManager
G4LVData * lvdata
Static Private Attributes
static G4GEOM_DLL G4LVManager subInstanceManager
Detailed Description
Definition at line 189 of file G4LogicalVolume.hh.
Member Typedef Documentation
G4PhysicalVolumeList
typedef std::vector<G4VPhysicalVolume*> G4LogicalVolume::G4PhysicalVolumeList private
Definition at line 191 of file G4LogicalVolume.hh.
Constructor & Destructor Documentation
G4LogicalVolume() [1/3]
G4LogicalVolume::G4LogicalVolume (G4VSolid * pSolid, G4Material * pMaterial, const G4String & name, G4FieldManager * pFieldMgr = 0, G4VSensitiveDetector * pSDetector = 0, G4UserLimits * pULimits = 0, G4bool optimise = true)
Definition at line 76 of file G4LogicalVolume.cc.
~G4LogicalVolume()
G4LogicalVolume::~G4LogicalVolume () virtual
Definition at line 147 of file G4LogicalVolume.cc.
G4LogicalVolume() [2/3]
G4LogicalVolume::G4LogicalVolume (__void__ &)
Definition at line 122 of file G4LogicalVolume.cc.
G4LogicalVolume() [3/3]
G4LogicalVolume::G4LogicalVolume (const G4LogicalVolume &) private
Member Function Documentation
AddDaughter()
void G4LogicalVolume::AddDaughter (G4VPhysicalVolume * p)
Definition at line 284 of file G4LogicalVolume.cc.
Referenced by G4ReplicatedSlice::CheckAndSetParameters(), export_G4LogicalVolume(), G4PVDivision::G4PVDivision(), G4PVPlacement::G4PVPlacement(), and G4PVReplica::G4PVReplica().
AssignFieldManager()
void G4LogicalVolume::AssignFieldManager (G4FieldManager * fldMgr)
Definition at line 243 of file G4LogicalVolume.cc.
Referenced by G4LogicalVolume(), InitialiseWorker(), and SetFieldManager().
CharacteriseDaughters()
EVolume G4LogicalVolume::CharacteriseDaughters () const inline
Referenced by G4Navigator::RecheckDistanceToCurrentBoundary(), and G4ITNavigator2::RecheckDistanceToCurrentBoundary().
Clean()
void G4LogicalVolume::Clean () static
Definition at line 201 of file G4LogicalVolume.cc.
Referenced by G4LogicalVolumeStore::~G4LogicalVolumeStore().
ClearDaughters()
void G4LogicalVolume::ClearDaughters ()
Definition at line 351 of file G4LogicalVolume.cc.
Referenced by export_G4LogicalVolume().
GetBiasWeight()
G4double G4LogicalVolume::GetBiasWeight () const inline
Referenced by G4ReflectionFactory::CreateReflectedLV(), and export_G4LogicalVolume().
GetDaughter()
G4VPhysicalVolume* G4LogicalVolume::GetDaughter (const G4int i) const inline
Referenced by G4GMocrenFileSceneHandler::AddSolid(), G4Region::BelongsTo(), G4SmartVoxelHeader::BuildNodes(), G4GeometryManager::BuildOptimisations(), G4SmartVoxelHeader::BuildReplicaVoxels(), G4PVPlacement::CheckOverlaps(), CML2WorldConstruction::checkVolumeOverlap(), G4ParameterisedNavigation::ComputeSafety(), G4NormalNavigation::ComputeSafety(), G4VoxelNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeSafety(), G4RegularNavigation::ComputeStep(), G4ParameterisedNavigation::ComputeStep(), G4NormalNavigation::ComputeStep(), G4VoxelNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), CML2PhantomConstruction::createPhysicalVolumeNamesList(), G4GeometryManager::DeleteOptimisations(), G4LogicalVolumeModel::DescribeYourselfTo(), export_G4LogicalVolume(), G4SmartVoxelHeader::G4SmartVoxelHeader(), G4RegularNavigation::LevelLocate(), G4ParameterisedNavigation::LevelLocate(), CexmcSetup::ReadCalorimeterGeometryData(), G4ReflectionFactory::ReflectDaughters(), G4VoxelSafety::SafetyForVoxelNode(), G4ProductionCutsTable::ScanAndSetCouple(), G4Region::ScanVolumeTree(), SetFieldManager(), G4VVisCommandGeometrySet::SetLVVisAtts(), G4GeomTestVolume::TestRecursiveOverlap(), and G4GDMLWriteStructure::TraverseVolumeTree().
GetFastSimulationManager()
G4FastSimulationManager* G4LogicalVolume::GetFastSimulationManager () const inline
Referenced by G4FastSimulationManagerProcess::AtRestGetPhysicalInteractionLength(), export_G4LogicalVolume(), GFlashHitMaker::make(), and G4FastSimulationManagerProcess::PostStepGetPhysicalInteractionLength().
GetFieldManager()
G4FieldManager * G4LogicalVolume::GetFieldManager () const
Definition at line 234 of file G4LogicalVolume.cc.
Referenced by AddDaughter(), G4ReflectionFactory::CreateReflectedLV(), G4MagneticFieldModel::DescribeYourselfTo(), export_G4LogicalVolume(), G4PropagatorInField::FindAndSetFieldManager(), InitialiseWorker(), SetFieldManager(), and G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster().
GetInstanceID()
G4int G4LogicalVolume::GetInstanceID () const inline
GetMass()
G4double G4LogicalVolume::GetMass (G4bool forced = false, G4bool propagate = true, G4Material * parMaterial = 0)
Definition at line 531 of file G4LogicalVolume.cc.
Referenced by B1RunAction::EndOfRunAction(), B1ConRunAction::EndOfRunAction(), export_G4LogicalVolume(), DetectorConstruction::GetAbsorMass(), DetectorConstruction::GetCytoMass(), GetMass(), DetectorConstruction::GetNuclMass(), and G4ASCIITreeSceneHandler::RequestPrimitives().
GetMasterFieldManager()
G4FieldManager* G4LogicalVolume::GetMasterFieldManager () const inline
Referenced by G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster().
GetMasterSensitiveDetector()
G4VSensitiveDetector* G4LogicalVolume::GetMasterSensitiveDetector () const inline
Referenced by G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster().
GetMasterSolid()
G4VSolid* G4LogicalVolume::GetMasterSolid () const inline
Referenced by G4GeometryWorkspace::InitialisePhysicalVolumes().
GetMaterial()
G4Material * G4LogicalVolume::GetMaterial () const
Definition at line 406 of file G4LogicalVolume.cc.
Referenced by CML2ExpVoxels::add(), UltraFresnelLens::BuildLens(), G4Track::CalculateVelocityForOpticalPhoton(), G4AdjointPrimaryGenerator::ComputeAccumulatedDepthVectorAlongBackRay(), G4VPVParameterisation::ComputeMaterial(), CellParameterisation::ComputeMaterial(), G4MIRDLiver::Construct(), G4MIRDRightScapula::Construct(), G4MIRDLeftLegBone::Construct(), G4MIRDRightKidney::Construct(), G4MIRDBrain::Construct(), G4MIRDRightLegBone::Construct(), G4MIRDLeftOvary::Construct(), G4MIRDLeftScapula::Construct(), G4MIRDSkull::Construct(), G4MIRDLeftAdrenal::Construct(), G4MIRDLeftTeste::Construct(), G4MIRDLeftLung::Construct(), G4MIRDLeftClavicle::Construct(), G4MIRDLowerLargeIntestine::Construct(), G4MIRDMaleGenitalia::Construct(), G4MIRDThyroid::Construct(), G4MIRDUpperLargeIntestine::Construct(), G4MIRDPelvis::Construct(), G4MIRDLeftKidney::Construct(), G4MIRDLeftLeg::Construct(), G4MIRDRightAdrenal::Construct(), G4MIRDRightClavicle::Construct(), G4MIRDSmallIntestine::Construct(), G4MIRDHeart::Construct(), G4MIRDRightLeg::Construct(), G4MIRDUterus::Construct(), G4MIRDRightLung::Construct(), G4MIRDUpperSpine::Construct(), G4MIRDRightOvary::Construct(), G4MIRDRightTeste::Construct(), G4MIRDLeftArmBone::Construct(), G4MIRDSpleen::Construct(), G4MIRDStomach::Construct(), G4MIRDThymus::Construct(), G4MIRDTrunk::Construct(), G4MIRDLeftBreast::Construct(), G4MIRDMiddleLowerSpine::Construct(), G4MIRDPancreas::Construct(), G4MIRDRibCage::Construct(), G4MIRDRightBreast::Construct(), G4MIRDHead::Construct(), G4MIRDUrinaryBladder::Construct(), G4MIRDRightArmBone::Construct(), CML2PhantomConstruction::createPhysicalVolumeNamesList(), G4ReflectionFactory::CreateReflectedLV(), G4tgbGeometryDumper::DumpLogVol(), export_G4LogicalVolume(), G4GDMLWriteStructure::ExportEnergyCuts(), DetectorConstruction::GetAbsorberMaterial(), G4LogicalCrystalVolume::GetCrystal(), GetMass(), G4Channeling::GetMatData(), PhysicsList::GetRange(), G4LatticeManager::LoadLattice(), G4Transportation::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4ITTransportation::PostStepDoIt(), XrayFluoMercuryDetectorConstruction::PrintApparateParameters(), XrayFluoPlaneDetectorConstruction::PrintApparateParameters(), XrayFluoDetectorConstruction::PrintApparateParameters(), G4ErrorFreeTrajState::PropagateErrorIoni(), G4ErrorFreeTrajState::PropagateErrorMSC(), G4LatticeManager::RegisterLattice(), G4PropagatorInField::ReportLoopingParticle(), G4TransportationLogger::ReportLoopingTrack(), G4ProductionCutsTable::ScanAndSetCouple(), G4Region::ScanVolumeTree(), G4ParallelWorldProcess::SwitchMaterial(), and G4GDMLWriteStructure::TraverseVolumeTree().
GetMaterialCutsCouple()
const G4MaterialCutsCouple * G4LogicalVolume::GetMaterialCutsCouple () const
Definition at line 455 of file G4LogicalVolume.cc.
Referenced by export_G4LogicalVolume(), PhysicsList::GetRange(), G4Transportation::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), G4ITTransportation::PostStepDoIt(), and G4AdjointForcedInteractionForGamma::PostStepGetPhysicalInteractionLength().
GetName()
const G4String& G4LogicalVolume::GetName () const inline
Referenced by G4AdjointCrossSurfChecker::AddanExtSurfaceOfAvolume(), AddDaughter(), G4HepRepFileSceneHandler::AddHepRepInstance(), G4HepRepSceneHandler::AddSolid(), G4VBiasingOperator::AttachTo(), G4SmartVoxelHeader::BuildNodes(), G4GeometryManager::BuildOptimisations(), G4SmartVoxelHeader::BuildReplicaVoxels(), G4SmartVoxelHeader::BuildVoxelsWithinLimits(), G4PVParameterised::CheckOverlaps(), G4PVPlacement::CheckOverlaps(), checkVol(), G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), G4ePolarizedIonisation::ComputeSaturationFactor(), G4PolarizedCompton::ComputeSaturationFactor(), G3toG4DetectorConstruction::Construct(), FFDetectorConstruction::Construct(), Par02DetectorConstruction::Construct(), G4tgbVolume::ConstructG4LogVol(), G4tgbVolume::ConstructG4PhysVol(), G4tgbVolume::ConstructG4Volumes(), CCalG4Ecal::constructGlobal(), CCalG4Hall::constructIn(), CCalG4Hcal::constructIn(), CCalG4Ecal::constructIn(), CCalG4Hcal::constructScintillatorLayer(), GB01DetectorConstruction::ConstructSDandField(), GB02DetectorConstruction::ConstructSDandField(), GB04DetectorConstruction::ConstructSDandField(), RE01CalorimeterHit::CreateAttValues(), B5HodoscopeHit::CreateAttValues(), B5EmCalorimeterHit::CreateAttValues(), G4PhysicalVolumeModel::CreateCurrentAttValues(), G3Division::CreatePVReplica(), G4ReflectionFactory::CreateReflectedLV(), G4AdjointCrossSurfChecker::CrossingAnInterfaceBetweenTwoVolumes(), G4Radioactivation::DecayIt(), G4RadioactiveDecayBase::DecayIt(), G4RadioactiveDecay::DecayIt(), G4RunManagerKernel::DefineWorldVolume(), G4RadioactiveDecayBase::DeselectAVolume(), G4RadioactiveDecay::DeselectAVolume(), G4ReflectionFactory::Divide(), G4GDMLReadStructure::DivisionvolRead(), G4GDMLWriteStructure::DivisionvolWrite(), G4TrajectoryDrawByOriginVolume::Draw(), G4tgbVolumeMgr::DumpG4LogVolLeaf(), G4LogicalSkinSurface::DumpInfo(), G4tgbGeometryDumper::DumpLogVol(), G4tgbGeometryDumper::DumpPhysVol(), G4tgbGeometryDumper::DumpPVParameterised(), G4tgbGeometryDumper::DumpPVPlacement(), G4tgbGeometryDumper::DumpPVReplica(), G4TrajectoryOriginVolumeFilter::Evaluate(), export_G4LogicalVolume(), G4GDMLParser::ExportRegions(), G4BuildGeom(), G4PVReplica::G4PVReplica(), G4GDMLRead::GeneratePhysvolName(), G4HepRepSceneHandler::getGeometryInstance(), G4Navigator::GetLocalExitNormal(), G4ITNavigator1::GetLocalExitNormal(), G4ITNavigator2::GetLocalExitNormal(), G4tgbGeometryDumper::GetPVChildren(), G4tgbVolumeMgr::GetTopLogVol(), G4tgbVolumeMgr::GetTopPhysVol(), G4GDMLReadStructure::GetWorldVolume(), G4AdjointCrossSurfChecker::GoingInOrOutOfaVolumeByExtSurface(), G4GDMLWriteParamvol::ParamvolAlgorithmWrite(), G4GDMLReadParamvol::ParamvolRead(), G4GDMLWriteParamvol::ParamvolWrite(), G4GDMLReadStructure::PhysvolRead(), G4GDMLWriteStructure::PhysvolWrite(), G4ReflectionFactory::Place(), G4HumanPhantomSD::ProcessHits(), G4ReflectionFactory::ReflectDaughters(), G4ReflectionFactory::ReflectPVDivision(), G4ReflectionFactory::ReflectPVPlacement(), G4ReflectionFactory::ReflectPVReplica(), G4tgbVolumeMgr::RegisterMe(), G4RunManager::ReOptimize(), G4GDMLReadStructure::ReplicaRead(), G4ReflectionFactory::Replicate(), G4GDMLWriteStructure::ReplicavolWrite(), G4ASCIITreeSceneHandler::RequestPrimitives(), G4VoxelSafety::SafetyForVoxelHeader(), G4PolarizedComptonModel::SampleSecondaries(), G4PolarizedAnnihilationModel::SampleSecondaries(), G4Region::ScanVolumeTree(), G4RadioactiveDecayBase::SelectAllVolumes(), G4RadioactiveDecay::SelectAllVolumes(), G4RadioactiveDecayBase::SelectAVolume(), G4RadioactiveDecay::SelectAVolume(), G4VVisCommandGeometrySet::Set(), G4VVisCommandGeometrySet::SetLVVisAtts(), G4VisCommandGeometryList::SetNewValue(), G4VisCommandGeometryRestore::SetNewValue(), DicomDetectorConstruction::SetScorer(), CCalSensitiveDetectors::setSensitive(), G4VUserDetectorConstruction::SetSensitiveDetector(), G4GDMLWriteSetup::SetupWrite(), CCalG4Able::setVisType(), G4PolarizationManager::SetVolumePolarization(), G4GDMLWriteStructure::SkinSurfaceCache(), G4GDMLRead::StripNames(), and G4GDMLWriteStructure::TraverseVolumeTree().
GetNoDaughters()
G4int G4LogicalVolume::GetNoDaughters () const inline
Referenced by G4GMocrenFileSceneHandler::AddSolid(), G4Region::BelongsTo(), G4SmartVoxelHeader::BuildNodes(), G4GeometryManager::BuildOptimisations(), G4SmartVoxelHeader::BuildReplicaVoxels(), G4SmartVoxelHeader::BuildVoxels(), G4PVPlacement::CheckOverlaps(), CML2WorldConstruction::checkVolumeOverlap(), G4VoxelSafety::ComputeSafety(), G4NormalNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeSafety(), G4NormalNavigation::ComputeStep(), G4VoxelNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4DrawVoxels::ComputeVoxelPolyhedra(), CML2PhantomConstruction::createPhysicalVolumeNamesList(), G4GeometryManager::DeleteOptimisations(), G4PhysicalVolumeModel::DescribeAndDescend(), G4LogicalVolumeModel::DescribeYourselfTo(), G4DrawVoxels::DrawVoxels(), export_G4LogicalVolume(), G4PVReplica::G4PVReplica(), G4SmartVoxelHeader::G4SmartVoxelHeader(), G4AssemblyVolume::MakeImprint(), CexmcSetup::ReadCalorimeterGeometryData(), G4ReflectionFactory::ReflectDaughters(), G4ASCIITreeSceneHandler::RequestPrimitives(), G4ProductionCutsTable::ScanAndSetCouple(), G4Region::ScanVolumeTree(), SetFieldManager(), G4VVisCommandGeometrySet::SetLVVisAtts(), G4GeomTestVolume::TestRecursiveOverlap(), and G4GDMLWriteStructure::TraverseVolumeTree().
GetRegion()
G4Region* G4LogicalVolume::GetRegion () const inline
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4Region::BelongsTo(), G4RunManagerKernel::CheckRegions(), G4PhysicalVolumeModel::CreateCurrentAttValues(), G4ReflectionFactory::CreateReflectedLV(), G4RunManagerKernel::DefineWorldVolume(), G4MagneticFieldModel::DescribeYourselfTo(), G4GlobalFastSimulationManager::DisplayRegion(), export_G4LogicalVolume(), G4GDMLWriteStructure::ExportEnergyCuts(), G4PropagatorInField::FindAndSetFieldManager(), G4FastTrack::FRecordsAffineTransformation(), G4HepRepSceneHandler::getGeometryInstance(), G4VTransitionRadiation::GetMeanFreePath(), G4NeutrinoElectronProcess::GetMeanFreePath(), RE06SteppingVerbose::NewStep(), SplitProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VTransitionRadiation::PostStepDoIt(), G4ElectronCapture::PostStepGetPhysicalInteractionLength(), G4LowECapture::PostStepGetPhysicalInteractionLength(), G4ReflectionFactory::ReflectLV(), G4ProductionCutsTable::ScanAndSetCouple(), G4GlobalFastSimulationManager::ShowSetup(), G4SteppingManager::Stepping(), G4ParallelWorldProcess::SwitchMaterial(), RE01SteppingAction::UserSteppingAction(), and G4MSSteppingAction::UserSteppingAction().
GetSensitiveDetector()
G4VSensitiveDetector * G4LogicalVolume::GetSensitiveDetector () const
Definition at line 436 of file G4LogicalVolume.cc.
Referenced by G4ParallelWorldProcess::AtRestDoIt(), G4ParallelWorldScoringProcess::AtRestDoIt(), G4ReflectionFactory::CreateReflectedLV(), export_G4LogicalVolume(), G4GDMLWriteStructure::ExportSD(), GFlashHitMaker::make(), G4Transportation::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), G4ParallelWorldProcess::PostStepDoIt(), G4ScoreSplittingProcess::PostStepDoIt(), G4ParallelWorldScoringProcess::PostStepDoIt(), G4ITTransportation::PostStepDoIt(), G4ASCIITreeSceneHandler::RequestPrimitives(), G4VUserDetectorConstruction::SetSensitiveDetector(), and G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster().
GetSmartless()
G4double G4LogicalVolume::GetSmartless () const inline
Referenced by G4SmartVoxelHeader::BuildNodes(), and export_G4LogicalVolume().
GetSolid() [1/2]
G4VSolid * G4LogicalVolume::GetSolid () const
Definition at line 379 of file G4LogicalVolume.cc.
Referenced by G4AdjointCrossSurfChecker::AddanExtSurfaceOfAvolume(), G4HepRepFileSceneHandler::AddHepRepInstance(), G4GMocrenFileSceneHandler::AddPrimitive(), G4GMocrenFileSceneHandler::AddSolid(), XrayFluoAnalysisManager::analyseStepping(), G4ReplicaNavigation::BackLocate(), G4PhantomParameterisation::BuildContainerSolid(), G4SmartVoxelHeader::BuildNodes(), G4SmartVoxelHeader::BuildReplicaVoxels(), G4SmartVoxelHeader::BuildVoxelsWithinLimits(), G4PVDivision::CheckAndSetParameters(), G4ReplicatedSlice::CheckAndSetParameters(), G4PVParameterised::CheckOverlaps(), G4PVPlacement::CheckOverlaps(), G4GeometryWorkspace::CloneParameterisedSolids(), G4GeometryWorkspace::CloneReplicaSolid(), G4VoxelSafety::ComputeSafety(), G4ParameterisedNavigation::ComputeSafety(), G4NormalNavigation::ComputeSafety(), G4VoxelNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeSafety(), G4PhantomParameterisation::ComputeSolid(), G4VPVParameterisation::ComputeSolid(), G4VNestedParameterisation::ComputeSolid(), G4ParameterisedNavigation::ComputeStep(), G4NormalNavigation::ComputeStep(), G4Navigator::ComputeStep(), G4VoxelNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4ITNavigator1::ComputeStep(), G4ITNavigator2::ComputeStep(), G4RegularNavigation::ComputeStepSkippingEqualMaterials(), G4PSDoseDeposit::ComputeVolume(), G4PSPassageCellFlux::ComputeVolume(), G4PSCellFlux::ComputeVolume(), G4DrawVoxels::ComputeVoxelPolyhedra(), GB06ParallelWorldForSlices::Construct(), G4MIRDRightScapula::Construct(), G4MIRDLeftLegBone::Construct(), G4MIRDLiver::Construct(), G4MIRDRightKidney::Construct(), G4MIRDLeftClavicle::Construct(), G4MIRDHeart::Construct(), G4MIRDLeftTeste::Construct(), G4MIRDSkull::Construct(), G4MIRDLowerLargeIntestine::Construct(), G4MIRDSmallIntestine::Construct(), G4MIRDMaleGenitalia::Construct(), G4MIRDThyroid::Construct(), G4MIRDUpperLargeIntestine::Construct(), G4MIRDLeftKidney::Construct(), G4MIRDPelvis::Construct(), G4MIRDLeftLeg::Construct(), G4MIRDLeftAdrenal::Construct(), G4MIRDRightAdrenal::Construct(), G4MIRDLeftLung::Construct(), G4MIRDRightClavicle::Construct(), G4MIRDLeftOvary::Construct(), G4MIRDBrain::Construct(), G4MIRDRightLeg::Construct(), G4MIRDLeftScapula::Construct(), G4MIRDRightLegBone::Construct(), G4MIRDRightOvary::Construct(), G4MIRDRightTeste::Construct(), G4MIRDLeftBreast::Construct(), G4MIRDSpleen::Construct(), G4MIRDStomach::Construct(), G4MIRDThymus::Construct(), G4MIRDMiddleLowerSpine::Construct(), G4MIRDHead::Construct(), G4MIRDTrunk::Construct(), G4MIRDPancreas::Construct(), G4MIRDUpperSpine::Construct(), G4MIRDUterus::Construct(), G4MIRDRibCage::Construct(), G4MIRDLeftArmBone::Construct(), G4MIRDRightBreast::Construct(), G4MIRDRightLung::Construct(), G4MIRDUrinaryBladder::Construct(), G4MIRDRightArmBone::Construct(), G4tgbVolume::ConstructG4PhysVol(), G4TheRayTracer::CreateBitMap(), G4PhysicalVolumeModel::CreateCurrentAttValues(), G3Division::CreatePVReplica(), G4ReflectionFactory::CreateReflectedLV(), G4AdjointPosOnPhysVolGenerator::DefinePhysicalVolume(), G4LogicalVolumeModel::DescribeYourselfTo(), G4VisManager::Draw(), G4tgbGeometryDumper::DumpLogVol(), F04SimpleSolenoid::F04SimpleSolenoid(), G4FastTrack::FRecordsAffineTransformation(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), B2PrimaryGeneratorAction::GeneratePrimaries(), B1PrimaryGeneratorAction::GeneratePrimaries(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), G4HepRepSceneHandler::getGeometryInstance(), G4Navigator::GetGlobalExitNormal(), G4Navigator::GetLocalExitNormal(), G4ITNavigator1::GetLocalExitNormal(), G4ITNavigator2::GetLocalExitNormal(), G4VIntersectionLocator::GetLocalSurfaceNormal(), GetMass(), FFPrimaryGeneratorAction::GetNeutronSourceCenter(), G4ITTransportationManager::GetParallelWorld(), G4TransportationManager::GetParallelWorld(), G4BOptnForceCommonTruncatedExp::Initialize(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4GDMLWriteParamvol::ParametersWrite(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4NavigationLogger::PreComputeStepLog(), G4PSSphereSurfaceCurrent::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), CexmcSetup::ReadCalorimeterGeometryData(), G4Navigator::RecheckDistanceToCurrentBoundary(), G4ITNavigator2::RecheckDistanceToCurrentBoundary(), G4NavigationLogger::ReportOutsideMother(), G4NavigationLogger::ReportVolumeAndIntersection(), G4VoxelSafety::SafetyForVoxelHeader(), G4VoxelSafety::SafetyForVoxelNode(), G4VisCommandsTouchable::SetNewValue(), G4PVDivision::SetParameterisation(), G4ReplicatedSlice::SetParameterisation(), G4RTPrimaryGeneratorAction::SetUp(), CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::SetupConstructionHook(), and G4GDMLWriteStructure::TraverseVolumeTree().
GetSolid() [2/2]
G4VSolid * G4LogicalVolume::GetSolid (G4LVData & instLVdata) static
Definition at line 374 of file G4LogicalVolume.cc.
GetSubInstanceManager()
const G4LVManager & G4LogicalVolume::GetSubInstanceManager () static
Definition at line 225 of file G4LogicalVolume.cc.
Referenced by G4GeometryWorkspace::G4GeometryWorkspace().
GetUserLimits()
G4UserLimits* G4LogicalVolume::GetUserLimits () const inline
Referenced by G4ReflectionFactory::CreateReflectedLV(), export_G4LogicalVolume(), G4StepLimiter::PostStepGetPhysicalInteractionLength(), G4MinEkineCuts::PostStepGetPhysicalInteractionLength(), DMXMinEkineCuts::PostStepGetPhysicalInteractionLength(), G4UserSpecialCuts::PostStepGetPhysicalInteractionLength(), G4MaxTimeCuts::PostStepGetPhysicalInteractionLength(), and DMXMaxTimeCuts::PostStepGetPhysicalInteractionLength().
GetVisAttributes()
const G4VisAttributes* G4LogicalVolume::GetVisAttributes () const inline
Referenced by G4GMocrenFileSceneHandler::AddDetector(), G03ColorWriter::AddExtension(), G4ReflectionFactory::CreateReflectedLV(), G4PhysicalVolumeModel::DescribeAndDescend(), RE01CalorimeterHit::Draw(), ExGflashHit::Draw(), RE05CalorimeterHit::Draw(), Par01CalorimeterHit::Draw(), B5HodoscopeHit::Draw(), B5EmCalorimeterHit::Draw(), export_G4LogicalVolume(), G4BuildGeom(), G4VVisCommandGeometrySet::SetLVVisAtts(), G4VisCommandGeometryList::SetNewValue(), and G4VisCommandGeometryRestore::SetNewValue().
GetVoxelHeader()
G4SmartVoxelHeader* G4LogicalVolume::GetVoxelHeader () const inline
Referenced by G4GeometryManager::BuildOptimisations(), G4VoxelSafety::ComputeSafety(), G4Navigator::ComputeSafety(), G4ITNavigator1::ComputeSafety(), G4ITNavigator2::ComputeSafety(), G4Navigator::ComputeStep(), G4ITNavigator1::ComputeStep(), G4ITNavigator2::ComputeStep(), G4DrawVoxels::CreatePlacedPolyhedra(), G4GeometryManager::DeleteOptimisations(), export_G4LogicalVolume(), G4ParameterisedNavigation::LevelLocate(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITNavigator2::LocateGlobalPointAndSetup(), G4Navigator::LocateGlobalPointWithinVolume(), G4ITNavigator1::LocateGlobalPointWithinVolume(), G4ITNavigator2::LocateGlobalPointWithinVolume(), and G4RunManager::ReOptimize().
InitialiseWorker()
void G4LogicalVolume::InitialiseWorker (G4LogicalVolume * ptrMasterObject, G4VSolid * pSolid, G4VSensitiveDetector * pSDetector)
Definition at line 168 of file G4LogicalVolume.cc.
Referenced by G4GeometryWorkspace::CloneParameterisedSolids(), G4GeometryWorkspace::CloneReplicaSolid(), and G4GeometryWorkspace::InitialisePhysicalVolumes().
IsAncestor()
G4bool G4LogicalVolume::IsAncestor (const G4VPhysicalVolume * p) const
Definition at line 477 of file G4LogicalVolume.cc.
Referenced by export_G4LogicalVolume(), G4WeightWindowStore::IsInWorld(), and G4IStore::IsInWorld().
IsDaughter()
G4bool G4LogicalVolume::IsDaughter (const G4VPhysicalVolume * p) const inline
Referenced by export_G4LogicalVolume(), and IsAncestor().
IsExtended()
G4bool G4LogicalVolume::IsExtended () const virtual
Reimplemented in G4LogicalCrystalVolume.
Definition at line 253 of file G4LogicalVolume.cc.
Referenced by G4Channeling::GetMatData().
IsRegion()
G4bool G4LogicalVolume::IsRegion () const inline
Referenced by G4ReflectionFactory::CreateReflectedLV(), and export_G4LogicalVolume().
IsRootRegion()
G4bool G4LogicalVolume::IsRootRegion () const inline
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4PhysicalVolumeModel::CreateCurrentAttValues(), G4GlobalFastSimulationManager::DisplayRegion(), export_G4LogicalVolume(), G4FastTrack::FRecordsAffineTransformation(), G4HepRepSceneHandler::getGeometryInstance(), G4ReflectionFactory::ReflectLV(), and G4Region::ScanVolumeTree().
IsToOptimise()
G4bool G4LogicalVolume::IsToOptimise () const inline
Referenced by G4GeometryManager::BuildOptimisations(), and export_G4LogicalVolume().
Lock()
void G4LogicalVolume::Lock () inline
operator=()
G4LogicalVolume& G4LogicalVolume::operator= (const G4LogicalVolume &) private
operator==()
G4bool G4LogicalVolume::operator== (const G4LogicalVolume & lv) const
PropagateRegion()
void G4LogicalVolume::PropagateRegion () inline
Referenced by AddDaughter(), and export_G4LogicalVolume().
RemoveDaughter()
void G4LogicalVolume::RemoveDaughter (const G4VPhysicalVolume * p)
Definition at line 329 of file G4LogicalVolume.cc.
Referenced by G4PhysicalVolumeStore::DeRegister(), export_G4LogicalVolume(), GB03DetectorConstruction::SetNumberOfLayers(), and RE06DetectorConstruction::SetNumberOfLayers().
ResetMass()
void G4LogicalVolume::ResetMass ()
Definition at line 365 of file G4LogicalVolume.cc.
Referenced by SetSolid().
SetBiasWeight()
void G4LogicalVolume::SetBiasWeight (G4double w) inline
Referenced by export_G4LogicalVolume().
SetFieldManager()
void G4LogicalVolume::SetFieldManager (G4FieldManager * pFieldMgr, G4bool forceToAllDaughters)
Definition at line 263 of file G4LogicalVolume.cc.
Referenced by AddDaughter(), G4VUserDetectorConstruction::CloneF(), B5DetectorConstruction::ConstructSDandField(), F03DetectorConstruction::ConstructSDandField(), export_G4LogicalVolume(), G4LogicalVolume(), InitialiseWorker(), SetFieldManager(), and G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster().
SetMaterial()
void G4LogicalVolume::SetMaterial (G4Material * pMaterial)
Definition at line 415 of file G4LogicalVolume.cc.
Referenced by Par01ParallelWorldForPion::Construct(), export_G4LogicalVolume(), G4LogicalVolume(), G4ScoreSplittingProcess::PostStepDoIt(), DetectorConstruction::SetAbsMaterial(), GB03DetectorConstruction::SetAbsorberMaterial(), RE06DetectorConstruction::SetAbsorberMaterial(), DetectorConstruction::SetAbsorberMaterial(), F03DetectorConstruction::SetAbsorberMaterial(), F01DetectorConstruction::SetAbsorberMaterial(), F02DetectorConstruction::SetAbsorberMaterial(), DetectorConstruction::SetAbsorMaterial(), DetectorConstruction::SetBoxMaterial(), B2bDetectorConstruction::SetChamberMaterial(), ExN02DetectorConstruction::setChamberMaterial(), ExP01DetectorConstruction::SetChamberMaterial(), DetectorConstruction::SetContainerMaterial(), DetectorConstruction::SetContainMaterial(), GammaRayTelDetectorConstruction::SetConverterMaterial(), DetectorConstruction::SetDetectorMaterial(), DetectorConstruction::SetEcalMaterial(), GB03DetectorConstruction::SetGapMaterial(), RE06DetectorConstruction::SetGapMaterial(), DetectorConstruction::SetGapMaterial(), DetectorConstruction::SetGasMaterial(), DetectorConstruction0::SetMaterial(), DetectorConstruction::SetMaterial(), XrayFluoMercuryDetectorConstruction::SetMercuryMaterial(), XrayFluoPlaneDetectorConstruction::SetPlaneMaterial(), ElectronBenchmarkDetector::SetPrimFoilMaterial(), XrayFluoDetectorConstruction::SetSampleMaterial(), DetectorConstruction::SetTankMaterial(), DetectorConstruction::SetTarget1Material(), DetectorConstruction::SetTarget2Material(), B2aDetectorConstruction::SetTargetMaterial(), B2bDetectorConstruction::SetTargetMaterial(), DetectorConstruction::SetTargetMaterial(), ExP01DetectorConstruction::SetTargetMaterial(), ExN02DetectorConstruction::setTargetMaterial(), DetectorConstruction::SetWorldMaterial(), F03DetectorConstruction::SetWorldMaterial(), F01DetectorConstruction::SetWorldMaterial(), and F02DetectorConstruction::SetWorldMaterial().
SetMaterialCutsCouple()
void G4LogicalVolume::SetMaterialCutsCouple (G4MaterialCutsCouple * cuts)
Definition at line 464 of file G4LogicalVolume.cc.
Referenced by export_G4LogicalVolume(), and G4ProductionCutsTable::ScanAndSetCouple().
SetName()
void G4LogicalVolume::SetName (const G4String & pName) inline
Referenced by export_G4LogicalVolume(), G4LogicalVolume(), and G4GDMLRead::StripNames().
SetOptimisation()
void G4LogicalVolume::SetOptimisation (G4bool optim) inline
Referenced by export_G4LogicalVolume().
SetRegion()
void G4LogicalVolume::SetRegion (G4Region * reg) inline
Referenced by G4RunManagerKernel::CheckRegions(), RE01DetectorConstruction::Construct(), ExGflashDetectorConstruction::Construct(), CML2Ph_BoxInBox::Construct(), G4RunManagerKernel::DefineWorldVolume(), export_G4LogicalVolume(), CML2Acc1::flatteningFilter(), CML2Acc2::flatteningFilter(), CML2AccSaturn::flatteningFilter(), CML2Acc1::ionizationChamber(), CML2Acc2::ionizationChamber(), CML2AccSaturn::Jaw1X(), CML2AccSaturn::Jaw1Y(), CML2Acc2::MLC(), CML2Acc1::primaryCollimator(), CML2Acc2::primaryCollimator(), G4Region::ScanVolumeTree(), RE06DetectorConstruction::SetupGeometry(), CML2Acc2::target(), and CML2Acc2::vacuumWindow().
SetRegionRootFlag()
void G4LogicalVolume::SetRegionRootFlag (G4bool rreg) inline
Referenced by G4Region::AddRootLogicalVolume(), export_G4LogicalVolume(), and G4Region::RemoveRootLogicalVolume().
SetSensitiveDetector()
void G4LogicalVolume::SetSensitiveDetector (G4VSensitiveDetector * pSDetector)
Definition at line 445 of file G4LogicalVolume.cc.
Referenced by ExN04CalorimeterROGeometry::Build(), G4VUserDetectorConstruction::CloneSD(), ExN04DetectorConstruction::Construct(), DetectorBarr90::Construct(), DetectorWatase86::Construct(), DetectorHarris73::Construct(), DetectorSimpleALICE::Construct(), DetectorALICE06::Construct(), DetectorBari05::Construct(), FCALEMModule::Construct(), FCALHadModule::Construct(), eRositaDetectorConstruction::Construct(), ExN02DetectorConstruction::Construct(), ExP01DetectorConstruction::Construct(), CML2Ph_FullWater::Construct(), HadrontherapyDetectorROGeometry::ConstructSD(), G04DetectorConstruction::ConstructSDandField(), Par01DetectorConstruction::ConstructSDandField(), GB05DetectorConstruction::ConstructSDandField(), ExGflashDetectorConstruction::ConstructSDandField(), GB06DetectorConstruction::ConstructSDandField(), B5DetectorConstruction::ConstructSDandField(), RE02DetectorConstruction::ConstructSDandField(), RMC01DetectorConstruction::ConstructSimpleGeometry(), export_G4LogicalVolume(), G4LogicalVolume(), InitialiseWorker(), CCalSensitiveDetectors::setSensitive(), G4VUserParallelWorld::SetSensitiveDetector(), G4VUserDetectorConstruction::SetSensitiveDetector(), G4ScoringCylinder::SetupGeometry(), G4ScoringBox::SetupGeometry(), G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster(), and G4VScoringMesh::WorkerConstruct().
SetSmartless()
void G4LogicalVolume::SetSmartless (G4double s) inline
Referenced by FCALEMModule::Construct(), FCALHadModule::Construct(), DicomPartialDetectorConstruction::ConstructPhantom(), and export_G4LogicalVolume().
SetSolid() [1/2]
void G4LogicalVolume::SetSolid (G4LVData & instLVdata, G4VSolid * pSolid) static
Definition at line 395 of file G4LogicalVolume.cc.
SetSolid() [2/2]
void G4LogicalVolume::SetSolid (G4VSolid * pSolid)
Definition at line 388 of file G4LogicalVolume.cc.
Referenced by G4LogicalVolume(), G4Navigator::GetMotherToDaughterTransform(), G4ITNavigator1::GetMotherToDaughterTransform(), G4ITNavigator2::GetMotherToDaughterTransform(), InitialiseWorker(), G4ParameterisedNavigation::LevelLocate(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITNavigator2::LocateGlobalPointAndSetup(), G4Navigator::SetupHierarchy(), G4ITNavigator1::SetupHierarchy(), and G4ITNavigator2::SetupHierarchy().
SetUserLimits()
void G4LogicalVolume::SetUserLimits (G4UserLimits * pULimits) inline
Referenced by ExUCNDetectorConstruction::Construct(), B5DetectorConstruction::Construct(), F05DetectorConstruction::Construct(), ExN02DetectorConstruction::Construct(), ExP01DetectorConstruction::Construct(), F06DetectorConstruction::Construct(), CML2Ph_BoxInBox::Construct(), DMXDetectorConstruction::Construct(), WLSDetectorConstruction::ConstructFiber(), TSDetectorConstruction::ConstructWorld(), DetectorConstruction::DefineVolumes(), B2bDetectorConstruction::DefineVolumes(), B2aDetectorConstruction::DefineVolumes(), export_G4LogicalVolume(), F04ElementField::F04ElementField(), G4LogicalVolume(), F04ElementField::SetMaxStep(), and XDetectorConstruction::SetupGeometry().
SetVisAttributes() [1/2]
void G4LogicalVolume::SetVisAttributes (const G4VisAttributes & VA)
Definition at line 614 of file G4LogicalVolume.cc.
SetVisAttributes() [2/2]
void G4LogicalVolume::SetVisAttributes (const G4VisAttributes * pVA) inline
Referenced by DetectorConstruction::AtomisticView(), DetectorConstruction::BarycenterView(), UltraFresnelLens::BuildLens(), HadrontherapyModulator::BuildSteps(), DicomPhantomParameterisationColour::ComputeMaterial(), DicomNestedPhantomParameterisation::ComputeMaterial(), CellParameterisation::ComputeMaterial(), G4MIRDLeftLegBone::Construct(), G4MIRDLiver::Construct(), G4MIRDRightKidney::Construct(), G4MIRDRightScapula::Construct(), G4MIRDLeftLung::Construct(), G4MIRDLeftOvary::Construct(), G4MIRDLeftScapula::Construct(), G4MIRDLeftTeste::Construct(), G4MIRDLowerLargeIntestine::Construct(), G4MIRDMaleGenitalia::Construct(), G4MIRDBrain::Construct(), G4MIRDPelvis::Construct(), G4MIRDRightAdrenal::Construct(), G4MIRDRightClavicle::Construct(), G4MIRDHeart::Construct(), G4MIRDRightLeg::Construct(), ExN04DetectorConstruction::Construct(), G4MIRDRightLegBone::Construct(), G4MIRDLeftAdrenal::Construct(), G4MIRDSkull::Construct(), G4MIRDLeftClavicle::Construct(), G4MIRDSmallIntestine::Construct(), G4MIRDLeftKidney::Construct(), G4MIRDThyroid::Construct(), G4MIRDLeftLeg::Construct(), G4MIRDUpperLargeIntestine::Construct(), G4MIRDUterus::Construct(), G4MIRDPancreas::Construct(), G4MIRDMiddleLowerSpine::Construct(), G4MIRDRibCage::Construct(), G4MIRDRightBreast::Construct(), G4MIRDHead::Construct(), G4MIRDRightLung::Construct(), G4MIRDRightOvary::Construct(), G4MIRDRightTeste::Construct(), G4MIRDLeftArmBone::Construct(), G4MIRDLeftBreast::Construct(), G4MIRDSpleen::Construct(), G4MIRDStomach::Construct(), G4MIRDThymus::Construct(), G4MIRDTrunk::Construct(), G4MIRDUpperSpine::Construct(), G4MIRDUrinaryBladder::Construct(), RE01DetectorConstruction::Construct(), G4MIRDRightArmBone::Construct(), B03DetectorConstruction::Construct(), Par01DetectorConstruction::Construct(), RE05DetectorConstruction::Construct(), B01DetectorConstruction::Construct(), B02DetectorConstruction::Construct(), GeometryConstruction::Construct(), B3DetectorConstruction::Construct(), ExGflashDetectorConstruction::Construct(), FCALCryostatVolumes::Construct(), FCALEMModule::Construct(), FCALHadModule::Construct(), eRositaDetectorConstruction::Construct(), ExUCNDetectorConstruction::Construct(), B5DetectorConstruction::Construct(), LXeDetectorConstruction::Construct(), ExP01DetectorConstruction::Construct(), ExN02DetectorConstruction::Construct(), FCALTestbeamSetup::Construct(), CML2Ph_BoxInBox::Construct(), G02DetectorConstruction::Construct(), ExErrorDetectorConstruction::Construct(), doiPETDetectorConstruction::Construct(), DMXDetectorConstruction::Construct(), UltraDetectorConstruction::Construct(), RE02DetectorConstruction::Construct(), XrayFluoMercuryDetectorConstruction::ConstructApparate(), XrayFluoPlaneDetectorConstruction::ConstructApparate(), XrayFluoDetectorConstruction::ConstructApparate(), DetectorConstruction::ConstructCalorimeter(), ExN03DetectorConstruction::ConstructCalorimeter(), PurgMagDetectorConstruction::ConstructCalorimeter(), DetectorConstruction::ConstructDetector(), G4tgbVolume::ConstructG4LogVol(), DetectorConstruction::ConstructLine(), GammaRayTelDetectorConstruction::ConstructPayload(), DicomNestedParamDetectorConstruction::ConstructPhantom(), DicomRegularDetectorConstruction::ConstructPhantom(), DicomPartialDetectorConstruction::ConstructPhantom(), doiPETDetectorConstruction::ConstructPhantom(), UltraDetectorConstruction::ConstructReflector(), XrayTelDetectorConstruction::ConstructTelescope(), UltraDetectorConstruction::ConstructUVscope(), G4HumanPhantomConstruction::ConstructWorld(), DetectorConstruction::ConstructWorld(), TSDetectorConstruction::ConstructWorld(), ElectronBenchmarkDetector::CreateExitWindow(), ElectronBenchmarkDetector::CreateHeliumBag(), ElectronBenchmarkDetector::CreateMonitor(), ElectronBenchmarkDetector::CreatePrimaryFoil(), G4ReflectionFactory::CreateReflectedLV(), ElectronBenchmarkDetector::CreateScorer(), ElectronBenchmarkDetector::CreateWorld(), B2bDetectorConstruction::DefineVolumes(), B2aDetectorConstruction::DefineVolumes(), DetectorConstruction::DrawBoundingVolume(), F04ElementField::F04ElementField(), LaserDrivenBeamLine::FaradayCup(), CML2Acc1::flatteningFilter(), CML2Acc2::flatteningFilter(), CML2AccSaturn::flatteningFilter(), G4BuildGeom(), G4GDMLReadStructure::GetWorldVolume(), TrentoPassiveProtonBeamLine::HadrontherapyRidgeFilter(), CML2Acc1::ionizationChamber(), CML2Acc2::ionizationChamber(), CML2AccSaturn::Jaw1Y(), CML2Acc2::MLC(), CML2Acc1::primaryCollimator(), CML2Acc2::primaryCollimator(), DetectorConstruction::ResiduesView(), F04ElementField::SetColor(), G4VVisCommandGeometrySet::SetLVVisAtts(), G4VisCommandGeometryRestore::SetNewValue(), G4ScoringCylinder::SetupGeometry(), G4ScoringBox::SetupGeometry(), XDetectorConstruction::SetupGeometry(), RE03DetectorConstruction::SetupGeometry(), RE04DetectorConstruction::SetupGeometry(), GB03DetectorConstruction::SetupGeometry(), RE06DetectorConstruction::SetupGeometry(), CCalG4Able::setVisType(), G3toG4DetectorConstruction::SimpleConstruct(), CML2Acc2::target(), CML2Acc2::vacuumWindow(), LXeMainVolume::VisAttributes(), and G03ColorReader::VolumeRead().
SetVoxelHeader()
void G4LogicalVolume::SetVoxelHeader (G4SmartVoxelHeader * pVoxel) inline
Referenced by G4GeometryManager::BuildOptimisations(), G4GeometryManager::DeleteOptimisations(), export_G4LogicalVolume(), and G4RunManager::ReOptimize().
TerminateWorker()
void G4LogicalVolume::TerminateWorker (G4LogicalVolume * ptrMasterObject)
Definition at line 215 of file G4LogicalVolume.cc.
Referenced by G4GeometryWorkspace::DestroyWorkspace().
TotalVolumeEntities()
G4int G4LogicalVolume::TotalVolumeEntities () const
Definition at line 499 of file G4LogicalVolume.cc.
Referenced by export_G4LogicalVolume(), and TotalVolumeEntities().
UpdateMaterial()
void G4LogicalVolume::UpdateMaterial (G4Material * pMaterial)
Definition at line 425 of file G4LogicalVolume.cc.
Referenced by export_G4LogicalVolume(), G4RegularNavigation::LevelLocate(), G4ParameterisedNavigation::LevelLocate(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITNavigator2::LocateGlobalPointAndSetup(), G4Navigator::SetupHierarchy(), G4ITNavigator1::SetupHierarchy(), and G4ITNavigator2::SetupHierarchy().
Field Documentation
fBiasWeight
G4double G4LogicalVolume::fBiasWeight private
Definition at line 421 of file G4LogicalVolume.hh.
fDaughters
G4PhysicalVolumeList G4LogicalVolume::fDaughters private
Definition at line 398 of file G4LogicalVolume.hh.
Referenced by AddDaughter(), ClearDaughters(), GetMass(), IsAncestor(), RemoveDaughter(), and TotalVolumeEntities().
fFieldManager
G4FieldManager* G4LogicalVolume::fFieldManager private
Definition at line 435 of file G4LogicalVolume.hh.
Referenced by AssignFieldManager(), G4LogicalVolume(), and InitialiseWorker().
fLock
G4bool G4LogicalVolume::fLock private
Definition at line 412 of file G4LogicalVolume.hh.
Referenced by ~G4LogicalVolume().
fName
G4String G4LogicalVolume::fName private
Definition at line 400 of file G4LogicalVolume.hh.
Referenced by GetMass().
fOptimise
G4bool G4LogicalVolume::fOptimise private
Definition at line 408 of file G4LogicalVolume.hh.
fRegion
G4Region* G4LogicalVolume::fRegion private
Definition at line 419 of file G4LogicalVolume.hh.
Referenced by AddDaughter(), ClearDaughters(), RemoveDaughter(), UpdateMaterial(), and ~G4LogicalVolume().
fRootRegion
G4bool G4LogicalVolume::fRootRegion private
Definition at line 410 of file G4LogicalVolume.hh.
Referenced by ~G4LogicalVolume().
fSensitiveDetector
G4VSensitiveDetector* G4LogicalVolume::fSensitiveDetector private
Definition at line 434 of file G4LogicalVolume.hh.
Referenced by G4LogicalVolume(), and SetSensitiveDetector().
fSmartless
G4double G4LogicalVolume::fSmartless private
Definition at line 414 of file G4LogicalVolume.hh.
fSolid
G4VSolid* G4LogicalVolume::fSolid private
Definition at line 433 of file G4LogicalVolume.hh.
Referenced by G4LogicalVolume().
fUserLimits
G4UserLimits* G4LogicalVolume::fUserLimits private
Definition at line 404 of file G4LogicalVolume.hh.
fVisAttributes
const G4VisAttributes* G4LogicalVolume::fVisAttributes private
Definition at line 417 of file G4LogicalVolume.hh.
Referenced by SetVisAttributes().
fVoxel
G4SmartVoxelHeader* G4LogicalVolume::fVoxel private
Definition at line 406 of file G4LogicalVolume.hh.
instanceID
G4int G4LogicalVolume::instanceID private
Definition at line 424 of file G4LogicalVolume.hh.
Referenced by G4LogicalVolume(), and GetSolid().
lvdata
G4LVData* G4LogicalVolume::lvdata private
Definition at line 436 of file G4LogicalVolume.hh.
Referenced by G4LogicalVolume(), and ~G4LogicalVolume().
subInstanceManager
G4LVManager G4LogicalVolume::subInstanceManager static private
Definition at line 426 of file G4LogicalVolume.hh.
Referenced by Clean(), G4LogicalVolume(), GetSolid(), GetSubInstanceManager(), and InitialiseWorker().
The documentation for this class was generated from the following files:
source/geometry/management/include/G4LogicalVolume.hh
source/geometry/management/src/G4LogicalVolume.cc