Geant4: source/processes/hadronic/models/lend/src/ptwXY_misc.cc File Reference
ptwXY_misc.cc File Reference
#include <stdio.h>
#include <stdlib.h>
#include <cmath>
#include <float.h>
#include "ptwXY.h"
Functions
static nfu_status ptwXY_createFromFunctionBisect (ptwXYPoints *ptwXY, double x1, double y1, double x2, double y2, ptwXY_createFromFunction_callback func, void *argList, int level, int checkForRoots, double eps)
static nfu_status ptwXY_createFromFunctionZeroCrossing (ptwXYPoints *ptwXY, double x1, double y1, double x2, double y2, ptwXY_createFromFunction_callback func, void *argList, double eps)
static nfu_status ptwXY_applyFunction2 (ptwXYPoints *ptwXY1, double y1, double y2, ptwXYPoint *p1, ptwXYPoint *p2, ptwXY_applyFunction_callback func, void *argList, int level, int checkForRoots)
static nfu_status ptwXY_applyFunctionZeroCrossing (ptwXYPoints *ptwXY1, double y1, double y2, ptwXYPoint *p1, ptwXYPoint *p2, ptwXY_applyFunction_callback func, void *argList)
void ptwXY_update_biSectionMax (ptwXYPoints *ptwXY1, double oldLength)
ptwXYPoints * ptwXY_createFromFunction (int n, double *xs, ptwXY_createFromFunction_callback func, void *argList, double accuracy, int checkForRoots, int biSectionMax, nfu_status *status)
ptwXYPoints * ptwXY_createFromFunction2 (ptwXPoints *xs, ptwXY_createFromFunction_callback func, void *argList, double accuracy, int checkForRoots, int biSectionMax, nfu_status *status)
nfu_status ptwXY_applyFunction (ptwXYPoints *ptwXY1, ptwXY_applyFunction_callback func, void *argList, int checkForRoots)
ptwXYPoints * ptwXY_fromString (char const *str, ptwXY_interpolation interpolation, ptwXY_interpolationOtherInfo const *interpolationOtherInfo, double biSectionMax, double accuracy, char **endCharacter, nfu_status *status)
void ptwXY_showInteralStructure (ptwXYPoints *ptwXY, FILE *f, int printPointersAsNull)
void ptwXY_simpleWrite (ptwXYPoints *ptwXY, FILE *f, char *format)
void ptwXY_simplePrint (ptwXYPoints *ptwXY, char *format)
Function Documentation
ptwXY_applyFunction()
nfu_status ptwXY_applyFunction (ptwXYPoints * ptwXY1, ptwXY_applyFunction_callback func, void * argList, int checkForRoots)
Definition at line 146 of file ptwXY_misc.cc.
Referenced by ptwXY_pow().
ptwXY_applyFunction2()
static nfu_status ptwXY_applyFunction2 (ptwXYPoints * ptwXY1, double y1, double y2, ptwXYPoint * p1, ptwXYPoint * p2, ptwXY_applyFunction_callback func, void * argList, int level, int checkForRoots) static
Definition at line 175 of file ptwXY_misc.cc.
Referenced by ptwXY_applyFunction().
ptwXY_applyFunctionZeroCrossing()
static nfu_status ptwXY_applyFunctionZeroCrossing (ptwXYPoints * ptwXY1, double y1, double y2, ptwXYPoint * p1, ptwXYPoint * p2, ptwXY_applyFunction_callback func, void * argList) static
Definition at line 201 of file ptwXY_misc.cc.
Referenced by ptwXY_applyFunction2().
ptwXY_createFromFunction()
ptwXYPoints* ptwXY_createFromFunction (int n, double * xs, ptwXY_createFromFunction_callback func, void * argList, double accuracy, int checkForRoots, int biSectionMax, nfu_status * status)
Definition at line 40 of file ptwXY_misc.cc.
Referenced by MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_energy_parseNBodyPhaseSpaceFromTOM(), nf_Legendre_to_ptwXY(), and ptwXY_createFromFunction2().
ptwXY_createFromFunction2()
ptwXYPoints* ptwXY_createFromFunction2 (ptwXPoints * xs, ptwXY_createFromFunction_callback func, void * argList, double accuracy, int checkForRoots, int biSectionMax, nfu_status * status)
Definition at line 89 of file ptwXY_misc.cc.
ptwXY_createFromFunctionBisect()
static nfu_status ptwXY_createFromFunctionBisect (ptwXYPoints * ptwXY, double x1, double y1, double x2, double y2, ptwXY_createFromFunction_callback func, void * argList, int level, int checkForRoots, double eps) static
Definition at line 97 of file ptwXY_misc.cc.
Referenced by ptwXY_createFromFunction().
ptwXY_createFromFunctionZeroCrossing()
static nfu_status ptwXY_createFromFunctionZeroCrossing (ptwXYPoints * ptwXY, double x1, double y1, double x2, double y2, ptwXY_createFromFunction_callback func, void * argList, double eps) static
Definition at line 116 of file ptwXY_misc.cc.
Referenced by ptwXY_createFromFunction().
ptwXY_fromString()
ptwXYPoints* ptwXY_fromString (char const * str, ptwXY_interpolation interpolation, ptwXY_interpolationOtherInfo const * interpolationOtherInfo, double biSectionMax, double accuracy, char ** endCharacter, nfu_status * status)
Definition at line 236 of file ptwXY_misc.cc.
ptwXY_showInteralStructure()
void ptwXY_showInteralStructure (ptwXYPoints * ptwXY, FILE * f, int printPointersAsNull)
Definition at line 253 of file ptwXY_misc.cc.
ptwXY_simplePrint()
void ptwXY_simplePrint (ptwXYPoints * ptwXY, char * format)
Definition at line 298 of file ptwXY_misc.cc.
ptwXY_simpleWrite()
void ptwXY_simpleWrite (ptwXYPoints * ptwXY, FILE * f, char * format)
Definition at line 285 of file ptwXY_misc.cc.
Referenced by ptwXY_simplePrint().
ptwXY_update_biSectionMax()
void ptwXY_update_biSectionMax (ptwXYPoints * ptwXY1, double oldLength)
Definition at line 31 of file ptwXY_misc.cc.
Referenced by ptwXY_applyFunction(), ptwXY_div_ptwXY(), and ptwXY_mul2_ptwXY().