Geant4: AClass Class Reference
AClass Class Reference
#include <AClass.hh>
Public Member Functions
AClass ()
AClass (int i, double d=0.)
~AClass ()
void SetIVal (int i)
int GetIVal () const
void SetDVal (double d)
double GetDVal () const
void AMethod ()
AClass ()
~AClass ()
void AMethod ()
virtual int VMethod (const XBase *abase) const
~AClass ()
AClass ()
AClass (int i, double d=0.)
~AClass ()
void SetIVal (int i)
int GetIVal () const
int AMethod ()
int AMethod (int i)
int AMethod (int i, double d)
int BMethod ()
double BMethod (double d)
double CMethod (int i, double d1=1., double d2=2.)
AClass ()
~AClass ()
AClass ()
AClass (int i)
~AClass ()
void SetIVal (int i)
int GetIVal () const
AClass operator+ (const AClass &aclass)
AClass & operator+= (const AClass &aclass)
bool operator== (const AClass &aclass) const
AClass ()
~AClass ()
AClass (int i)
AClass (const AClass &a)
~AClass ()
AClass ()
AClass (const AClass &right)
~AClass ()
void SetIVal (int i)
int GetIVal ()
void Print () const
Public Member Functions inherited from XBase
XBase ()
virtual ~XBase ()
void SetIVal (int aval)
int GetIVal () const
void SetDVal (double aval)
double GetDVal () const
void AMethod ()
XBase ()
virtual ~XBase ()
void SetIVal (int i)
int GetIVal () const
virtual std::string PVMethod ()=0
XBase ()
~XBase ()
virtual void VMethodA (const AClass *a)
virtual void VMethodB (const BClass *b)
Static Public Member Functions
static AClass * GetPointer ()
static int AMethod ()
Protected Member Functions
AClass ()
Static Protected Attributes
static AClass * thePointer = 0
Private Member Functions
AClass ()
Private Attributes
int ival
double dval
Additional Inherited Members
Protected Attributes inherited from XBase
int ival
double dval
Detailed Description
Definition at line 40 of file AClass.hh.
Constructor & Destructor Documentation
AClass() [1/15]
AClass::AClass ()
Definition at line 41 of file AClass.cc.
Referenced by GetPointer().
AClass() [2/15]
AClass::AClass (int i, double d = 0.)
Definition at line 50 of file AClass.cc.
~AClass() [1/9]
AClass::~AClass ()
Definition at line 58 of file AClass.cc.
AClass() [3/15]
AClass::AClass ()
~AClass() [2/9]
AClass::~AClass ()
AClass() [4/15]
AClass::AClass () protected
~AClass() [3/9]
AClass::~AClass ()
AClass() [5/15]
AClass::AClass ()
AClass() [6/15]
AClass::AClass (int i, double d = 0.)
~AClass() [4/9]
AClass::~AClass ()
AClass() [7/15]
AClass::AClass () inline
Definition at line 36 of file test08.cc.
~AClass() [5/9]
AClass::~AClass () inline
Definition at line 37 of file test08.cc.
AClass() [8/15]
AClass::AClass () inline
Definition at line 40 of file test09.cc.
AClass() [9/15]
AClass::AClass (int i) inline
Definition at line 41 of file test09.cc.
~AClass() [6/9]
AClass::~AClass () inline
Definition at line 42 of file test09.cc.
AClass() [10/15]
AClass::AClass () inline
Definition at line 37 of file test10.cc.
~AClass() [7/9]
AClass::~AClass () inline
Definition at line 42 of file test10.cc.
AClass() [11/15]
AClass::AClass () inline private
Definition at line 35 of file test11.cc.
AClass() [12/15]
AClass::AClass (int i) inline
Definition at line 38 of file test11.cc.
AClass() [13/15]
AClass::AClass (const AClass & a) inline
Definition at line 39 of file test11.cc.
~AClass() [8/9]
AClass::~AClass () inline
Definition at line 40 of file test11.cc.
AClass() [14/15]
AClass::AClass () inline
Definition at line 48 of file test12.cc.
AClass() [15/15]
AClass::AClass (const AClass & right) inline
Definition at line 51 of file test12.cc.
~AClass() [9/9]
AClass::~AClass () inline
Definition at line 56 of file test12.cc.
Member Function Documentation
AMethod() [1/6]
static int AClass::AMethod () inline static
Definition at line 38 of file test08.cc.
AMethod() [2/6]
void AClass::AMethod ()
AMethod() [3/6]
int AClass::AMethod ()
AMethod() [4/6]
int AClass::AMethod ()
Definition at line 65 of file AClass.cc.
Referenced by BOOST_PYTHON_MODULE().
AMethod() [5/6]
int AClass::AMethod (int i)
Definition at line 70 of file AClass.cc.
AMethod() [6/6]
int AClass::AMethod (int i, double d)
Definition at line 78 of file AClass.cc.
BMethod() [1/2]
int AClass::BMethod ()
Definition at line 87 of file AClass.cc.
BMethod() [2/2]
double AClass::BMethod (double d)
Definition at line 94 of file AClass.cc.
CMethod()
double AClass::CMethod (int i, double d1 = 1., double d2 = 2.)
Definition at line 102 of file AClass.cc.
Referenced by BOOST_PYTHON_MODULE().
GetDVal()
double AClass::GetDVal () const inline
Definition at line 69 of file AClass.hh.
Referenced by BOOST_PYTHON_MODULE().
GetIVal() [1/4]
int AClass::GetIVal () inline
Definition at line 59 of file test12.cc.
GetIVal() [2/4]
int AClass::GetIVal () const inline
Definition at line 45 of file test09.cc.
GetIVal() [3/4]
int AClass::GetIVal () const
GetIVal() [4/4]
int AClass::GetIVal () const inline
Definition at line 66 of file AClass.hh.
Referenced by BOOST_PYTHON_MODULE(), and operator<<().
GetPointer()
AClass * AClass::GetPointer () static
Definition at line 57 of file AClass.cc.
Referenced by BOOST_PYTHON_MODULE().
operator+()
AClass AClass::operator+ (const AClass & aclass) inline
Definition at line 47 of file test09.cc.
operator+=()
AClass& AClass::operator+= (const AClass & aclass) inline
Definition at line 53 of file test09.cc.
operator==()
bool AClass::operator== (const AClass & aclass) const inline
Definition at line 58 of file test09.cc.
Print()
void AClass::Print () const inline
Definition at line 61 of file test12.cc.
Referenced by BOOST_PYTHON_MODULE().
SetDVal()
void AClass::SetDVal (double d) inline
Definition at line 68 of file AClass.hh.
Referenced by BOOST_PYTHON_MODULE().
SetIVal() [1/4]
void AClass::SetIVal (int i) inline
Definition at line 44 of file test09.cc.
SetIVal() [2/4]
void AClass::SetIVal (int i)
SetIVal() [3/4]
void AClass::SetIVal (int i) inline
Definition at line 65 of file AClass.hh.
Referenced by BOOST_PYTHON_MODULE().
SetIVal() [4/4]
void AClass::SetIVal (int i) inline
Definition at line 58 of file test12.cc.
VMethod()
int AClass::VMethod (const XBase * abase) const virtual
Implements XBase.
Definition at line 65 of file AClass.cc.
Field Documentation
dval
double AClass::dval private
Definition at line 43 of file AClass.hh.
Referenced by AMethod(), GetDVal(), and SetDVal().
ival
int AClass::ival private
Definition at line 42 of file AClass.hh.
Referenced by AClass(), AMethod(), GetIVal(), operator+(), operator+=(), operator==(), Print(), and SetIVal().
thePointer
AClass * AClass::thePointer = 0 static protected
Definition at line 42 of file AClass.hh.
Referenced by GetPointer().
The documentation for this class was generated from the following files:
environments/g4py/tests/test01/module/AClass.hh
environments/g4py/tests/test09/module/test09.cc
environments/g4py/tests/test12/module/test12.cc
environments/g4py/tests/test08/module/test08.cc
environments/g4py/tests/test10/module/test10.cc
environments/g4py/tests/test11/module/test11.cc
environments/g4py/tests/test01/module/AClass.cc