Geant4: G4PartonPair Class Reference
G4PartonPair Class Reference
#include <G4PartonPair.hh>
Public Types
enum { DIFFRACTIVE = 1, SOFT = 2, HARD = 3 }
enum { PROJECTILE = 1, TARGET = -1 }
Public Member Functions
G4PartonPair (G4Parton *P1, G4Parton *P2, G4int Type, G4int Direction)
~G4PartonPair ()
void SetPartons (G4Parton *P1, G4Parton *P2)
void SetCollisionType (G4int Type)
G4int GetCollisionType ()
G4Parton * GetParton1 (void)
G4Parton * GetParton2 (void)
G4int GetDirection ()
Private Member Functions
G4PartonPair (const G4PartonPair &right)
G4bool operator== (const G4PartonPair &right) const
G4bool operator!= (const G4PartonPair &right) const
Private Attributes
G4Parton * Parton1
G4Parton * Parton2
G4int CollisionType
G4int Direction
Detailed Description
Definition at line 35 of file G4PartonPair.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
DIFFRACTIVE
SOFT
HARD
Definition at line 38 of file G4PartonPair.hh.
anonymous enum
anonymous enum
Enumerator
PROJECTILE
TARGET
Definition at line 43 of file G4PartonPair.hh.
Constructor & Destructor Documentation
G4PartonPair() [1/2]
G4PartonPair::G4PartonPair (G4Parton * P1, G4Parton * P2, G4int Type, G4int Direction)
Definition at line 31 of file G4PartonPair.cc.
~G4PartonPair()
G4PartonPair::~G4PartonPair ()
Definition at line 60 of file G4PartonPair.cc.
G4PartonPair() [2/2]
G4PartonPair::G4PartonPair (const G4PartonPair & right) private
Member Function Documentation
GetCollisionType()
G4int G4PartonPair::GetCollisionType () inline
Definition at line 86 of file G4PartonPair.hh.
GetDirection()
G4int G4PartonPair::GetDirection () inline
Definition at line 91 of file G4PartonPair.hh.
Referenced by G4DiffractiveStringBuilder::BuildString(), and G4SoftStringBuilder::BuildString().
GetParton1()
G4Parton * G4PartonPair::GetParton1 (void) inline
Definition at line 71 of file G4PartonPair.hh.
Referenced by G4DiffractiveStringBuilder::BuildString(), G4SoftStringBuilder::BuildString(), G4QGSParticipants::CreateStrings(), and G4QGSParticipants::PerformSoftCollisions().
GetParton2()
G4Parton * G4PartonPair::GetParton2 (void) inline
Definition at line 76 of file G4PartonPair.hh.
Referenced by G4DiffractiveStringBuilder::BuildString(), G4SoftStringBuilder::BuildString(), G4QGSParticipants::CreateStrings(), and G4QGSParticipants::PerformSoftCollisions().
operator!=()
G4bool G4PartonPair::operator!= (const G4PartonPair & right) const private
operator==()
G4bool G4PartonPair::operator== (const G4PartonPair & right) const private
SetCollisionType()
void G4PartonPair::SetCollisionType (G4int Type) inline
Definition at line 81 of file G4PartonPair.hh.
SetPartons()
void G4PartonPair::SetPartons (G4Parton * P1, G4Parton * P2)
Field Documentation
CollisionType
G4int G4PartonPair::CollisionType private
Definition at line 67 of file G4PartonPair.hh.
Referenced by G4PartonPair(), GetCollisionType(), and SetCollisionType().
Direction
G4int G4PartonPair::Direction private
Definition at line 68 of file G4PartonPair.hh.
Referenced by G4PartonPair(), and GetDirection().
Parton1
G4Parton* G4PartonPair::Parton1 private
Definition at line 65 of file G4PartonPair.hh.
Referenced by G4PartonPair(), and GetParton1().
Parton2
G4Parton* G4PartonPair::Parton2 private
Definition at line 66 of file G4PartonPair.hh.
Referenced by G4PartonPair(), and GetParton2().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/parton_string/qgsm/include/G4PartonPair.hh
source/processes/hadronic/models/parton_string/qgsm/src/G4PartonPair.cc