Geant4: G4EmParameters Class Reference
G4EmParameters Class Reference
#include <G4EmParameters.hh>
Public Member Functions
~G4EmParameters ()
void SetDefaults ()
std::ostream & StreamInfo (std::ostream &os) const
void Dump () const
void SetLossFluctuations (G4bool val)
G4bool LossFluctuation () const
void SetBuildCSDARange (G4bool val)
G4bool BuildCSDARange () const
void SetLPM (G4bool val)
G4bool LPM () const
void SetSpline (G4bool val)
G4bool Spline () const
void SetUseCutAsFinalRange (G4bool val)
G4bool UseCutAsFinalRange () const
void SetApplyCuts (G4bool val)
G4bool ApplyCuts () const
void SetFluo (G4bool val)
G4bool Fluo () const
void SetBeardenFluoDir (G4bool val)
G4bool BeardenFluoDir () const
void SetAuger (G4bool val)
G4bool Auger () const
void SetAugerCascade (G4bool val)
G4bool AugerCascade () const
void SetPixe (G4bool val)
G4bool Pixe () const
void SetDeexcitationIgnoreCut (G4bool val)
G4bool DeexcitationIgnoreCut () const
void SetLateralDisplacement (G4bool val)
G4bool LateralDisplacement () const
void SetLateralDisplacementAlg96 (G4bool val)
G4bool LateralDisplacementAlg96 () const
void SetMuHadLateralDisplacement (G4bool val)
G4bool MuHadLateralDisplacement () const
void SetLatDisplacementBeyondSafety (G4bool val)
G4bool LatDisplacementBeyondSafety () const
void ActivateAngularGeneratorForIonisation (G4bool val)
G4bool UseAngularGeneratorForIonisation () const
void SetUseMottCorrection (G4bool val)
G4bool UseMottCorrection () const
void SetIntegral (G4bool val)
G4bool Integral () const
void SetBirksActive (G4bool val)
G4bool BirksActive () const
void SetUseICRU90Data (G4bool val)
G4bool UseICRU90Data () const
void SetDNAFast (G4bool val)
G4bool DNAFast () const
void SetDNAStationary (G4bool val)
G4bool DNAStationary () const
void SetDNAElectronMsc (G4bool val)
G4bool DNAElectronMsc () const
void SetGeneralProcessActive (G4bool val)
G4bool GeneralProcessActive () const
void SetEnableSamplingTable (G4bool val)
G4bool EnableSamplingTable () const
void SetEmSaturation (G4EmSaturation *)
G4EmSaturation * GetEmSaturation ()
void SetOnIsolated (G4bool val)
bool OnIsolated () const
void SetMinSubRange (G4double val)
G4double MinSubRange () const
void SetMinEnergy (G4double val)
G4double MinKinEnergy () const
void SetMaxEnergy (G4double val)
G4double MaxKinEnergy () const
void SetMaxEnergyForCSDARange (G4double val)
G4double MaxEnergyForCSDARange () const
void SetLowestElectronEnergy (G4double val)
G4double LowestElectronEnergy () const
void SetLowestMuHadEnergy (G4double val)
G4double LowestMuHadEnergy () const
void SetLowestTripletEnergy (G4double val)
G4double LowestTripletEnergy () const
void SetLinearLossLimit (G4double val)
G4double LinearLossLimit () const
void SetBremsstrahlungTh (G4double val)
G4double BremsstrahlungTh () const
void SetLambdaFactor (G4double val)
G4double LambdaFactor () const
void SetFactorForAngleLimit (G4double val)
G4double FactorForAngleLimit () const
void SetMscThetaLimit (G4double val)
G4double MscThetaLimit () const
void SetMscEnergyLimit (G4double val)
G4double MscEnergyLimit () const
void SetMscRangeFactor (G4double val)
G4double MscRangeFactor () const
void SetMscMuHadRangeFactor (G4double val)
G4double MscMuHadRangeFactor () const
void SetMscGeomFactor (G4double val)
G4double MscGeomFactor () const
void SetMscSkin (G4double val)
G4double MscSkin () const
void SetScreeningFactor (G4double val)
G4double ScreeningFactor () const
void SetStepFunction (G4double v1, G4double v2)
void SetStepFunctionMuHad (G4double v1, G4double v2)
void SetNumberOfBins (G4int val)
G4int NumberOfBins () const
void SetNumberOfBinsPerDecade (G4int val)
G4int NumberOfBinsPerDecade () const
void SetVerbose (G4int val)
G4int Verbose () const
void SetWorkerVerbose (G4int val)
G4int WorkerVerbose () const
void SetMscStepLimitType (G4MscStepLimitType val)
G4MscStepLimitType MscStepLimitType () const
void SetMscMuHadStepLimitType (G4MscStepLimitType val)
G4MscStepLimitType MscMuHadStepLimitType () const
void SetNuclearFormfactorType (G4NuclearFormfactorType val)
G4NuclearFormfactorType NuclearFormfactorType () const
void SetDNAeSolvationSubType (G4DNAModelSubType val)
G4DNAModelSubType DNAeSolvationSubType () const
void SetConversionType (G4int val)
G4int GetConversionType () const
void SetPIXECrossSectionModel (const G4String &)
const G4String & PIXECrossSectionModel ()
void SetPIXEElectronCrossSectionModel (const G4String &)
const G4String & PIXEElectronCrossSectionModel ()
void AddPAIModel (const G4String &particle, const G4String &region, const G4String &type)
const std::vector< G4String > & ParticlesPAI () const
const std::vector< G4String > & RegionsPAI () const
const std::vector< G4String > & TypesPAI () const
void AddMicroElec (const G4String &region)
const std::vector< G4String > & RegionsMicroElec () const
void AddDNA (const G4String &region, const G4String &type)
const std::vector< G4String > & RegionsDNA () const
const std::vector< G4String > & TypesDNA () const
void AddMsc (const G4String &region, const G4String &type)
const std::vector< G4String > & RegionsMsc () const
const std::vector< G4String > & TypesMsc () const
void AddPhysics (const G4String &region, const G4String &type)
const std::vector< G4String > & RegionsPhysics () const
const std::vector< G4String > & TypesPhysics () const
void SetSubCutoff (G4bool val, const G4String &region="")
void SetDeexActiveRegion (const G4String &region, G4bool fdeex, G4bool fauger, G4bool fpixe)
void SetProcessBiasingFactor (const G4String &procname, G4double val, G4bool wflag)
void ActivateForcedInteraction (const G4String &procname, const G4String &region, G4double length, G4bool wflag)
void ActivateSecondaryBiasing (const G4String &name, const G4String &region, G4double factor, G4double energyLimit)
G4bool GetDirectionalSplitting ()
void SetDirectionalSplitting (G4int v)
void SetDirectionalSplittingTarget (G4ThreeVector v)
G4ThreeVector GetDirectionalSplittingTarget ()
void SetDirectionalSplittingRadius (G4double r)
G4double GetDirectionalSplittingRadius ()
void DefineRegParamForLoss (G4VEnergyLossProcess *, G4bool isElectron) const
void DefineRegParamForEM (G4VEmProcess *) const
void DefineRegParamForDeex (G4VAtomDeexcitation *) const
G4EmParameters (G4EmParameters &)=delete
G4EmParameters & operator= (const G4EmParameters &right)=delete
Static Public Member Functions
static G4EmParameters * Instance ()
Private Member Functions
G4EmParameters ()
void Initialise ()
G4bool IsLocked () const
G4String CheckRegion (const G4String &) const
void PrintWarning (G4ExceptionDescription &ed) const
Private Attributes
G4EmParametersMessenger * theMessenger
G4StateManager * fStateManager
G4EmSaturation * emSaturation
G4bool lossFluctuation
G4bool buildCSDARange
G4bool flagLPM
G4bool spline
G4bool cutAsFinalRange
G4bool applyCuts
G4bool fluo
G4bool beardenFluoDir
G4bool auger
G4bool augerCascade
G4bool pixe
G4bool deexIgnoreCut
G4bool lateralDisplacement
G4bool lateralDisplacementAlg96
G4bool muhadLateralDisplacement
G4bool latDisplacementBeyondSafety
G4bool useAngGeneratorForIonisation
G4bool useMottCorrection
G4bool integral
G4bool birks
G4bool fICRU90
G4bool dnaFast
G4bool dnaStationary
G4bool dnaMsc
G4bool gener
G4bool enableSamplingTable
G4bool onIsolated
G4bool directionalSplitting
G4double minSubRange
G4double minKinEnergy
G4double maxKinEnergy
G4double maxKinEnergyCSDA
G4double lowestElectronEnergy
G4double lowestMuHadEnergy
G4double lowestTripletEnergy
G4double linLossLimit
G4double bremsTh
G4double lambdaFactor
G4double factorForAngleLimit
G4double thetaLimit
G4double energyLimit
G4double rangeFactor
G4double rangeFactorMuHad
G4double geomFactor
G4double skin
G4double dRoverRange
G4double finalRange
G4double dRoverRangeMuHad
G4double finalRangeMuHad
G4double factorScreen
G4double directionalSplittingRadius
G4int nbins
G4int nbinsPerDecade
G4int verbose
G4int workerVerbose
G4int tripletConv
G4ThreeVector directionalSplittingTarget
G4MscStepLimitType mscStepLimit
G4MscStepLimitType mscStepLimitMuHad
G4NuclearFormfactorType nucFormfactor
G4DNAModelSubType dnaElectronSolvation
G4String namePIXE
G4String nameElectronPIXE
std::vector< G4String > m_particlesPAI
std::vector< G4String > m_regnamesPAI
std::vector< G4String > m_typesPAI
std::vector< G4String > m_regnamesME
std::vector< G4String > m_regnamesDNA
std::vector< G4String > m_typesDNA
std::vector< G4String > m_regnamesPhys
std::vector< G4String > m_typesPhys
std::vector< G4String > m_regnamesSubCut
std::vector< G4bool > m_subCuts
std::vector< G4String > m_regnamesDeex
std::vector< G4bool > m_fluo
std::vector< G4bool > m_auger
std::vector< G4bool > m_pixe
std::vector< G4String > m_procBiasedXS
std::vector< G4double > m_factBiasedXS
std::vector< G4bool > m_weightBiasedXS
std::vector< G4String > m_procForced
std::vector< G4String > m_regnamesForced
std::vector< G4double > m_lengthForced
std::vector< G4bool > m_weightForced
std::vector< G4String > m_procBiasedSec
std::vector< G4String > m_regnamesBiasedSec
std::vector< G4double > m_factBiasedSec
std::vector< G4double > m_elimBiasedSec
Static Private Attributes
static G4EmParameters * theInstance = nullptr
Friends
std::ostream & operator<< (std::ostream &os, const G4EmParameters &)
Detailed Description
Definition at line 72 of file G4EmParameters.hh.
Constructor & Destructor Documentation
~G4EmParameters()
G4EmParameters::~G4EmParameters ()
Definition at line 88 of file G4EmParameters.cc.
G4EmParameters() [1/2]
G4EmParameters::G4EmParameters (G4EmParameters &) delete
G4EmParameters() [2/2]
G4EmParameters::G4EmParameters () private
Definition at line 96 of file G4EmParameters.cc.
Member Function Documentation
ActivateAngularGeneratorForIonisation()
void G4EmParameters::ActivateAngularGeneratorForIonisation (G4bool val)
Definition at line 361 of file G4EmParameters.cc.
Referenced by G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), PhysListEmStandard_option4::PhysListEmStandard_option4(), and G4EmParametersMessenger::SetNewValue().
ActivateForcedInteraction()
void G4EmParameters::ActivateForcedInteraction (const G4String & procname, const G4String & region, G4double length, G4bool wflag)
Definition at line 1202 of file G4EmParameters.cc.
Referenced by G4EmProcessOptions::ActivateForcedInteraction(), and G4EmParametersMessenger::SetNewValue().
ActivateSecondaryBiasing()
void G4EmParameters::ActivateSecondaryBiasing (const G4String & name, const G4String & region, G4double factor, G4double energyLimit)
Definition at line 1232 of file G4EmParameters.cc.
Referenced by G4EmProcessOptions::ActivateSecondaryBiasing(), G4EmProcessOptions::ActivateSecondaryBiasingForGamma(), and G4EmParametersMessenger::SetNewValue().
AddDNA()
void G4EmParameters::AddDNA (const G4String & region, const G4String & type)
Definition at line 1073 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue().
AddMicroElec()
void G4EmParameters::AddMicroElec (const G4String & region)
Definition at line 1057 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue().
AddMsc()
void G4EmParameters::AddMsc (const G4String & region, const G4String & type)
Definition at line 1095 of file G4EmParameters.cc.
AddPAIModel()
void G4EmParameters::AddPAIModel (const G4String & particle, const G4String & region, const G4String & type)
Definition at line 1016 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue().
AddPhysics()
void G4EmParameters::AddPhysics (const G4String & region, const G4String & type)
Definition at line 1110 of file G4EmParameters.cc.
Referenced by AddMsc(), G4RadioactiveDecayPhysics::G4RadioactiveDecayPhysics(), and G4EmParametersMessenger::SetNewValue().
ApplyCuts()
G4bool G4EmParameters::ApplyCuts () const
Definition at line 244 of file G4EmParameters.cc.
Referenced by G4VEmProcess::PreparePhysicsTable().
Auger()
G4bool G4EmParameters::Auger () const
Definition at line 276 of file G4EmParameters.cc.
Referenced by G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), and G4RadioactiveDecay::StreamInfo().
AugerCascade()
G4bool G4EmParameters::AugerCascade () const
Definition at line 289 of file G4EmParameters.cc.
Referenced by G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), and G4RadioactiveDecay::StreamInfo().
BeardenFluoDir()
G4bool G4EmParameters::BeardenFluoDir () const
Definition at line 266 of file G4EmParameters.cc.
Referenced by G4AtomicTransitionManager::Initialise(), and G4RadioactiveDecay::StreamInfo().
BirksActive()
G4bool G4EmParameters::BirksActive () const
Definition at line 409 of file G4EmParameters.cc.
BremsstrahlungTh()
G4double G4EmParameters::BremsstrahlungTh () const
Definition at line 667 of file G4EmParameters.cc.
Referenced by G4eBremsstrahlung::InitialiseEnergyLossProcess(), and G4eBremsstrahlung::StreamProcessInfo().
BuildCSDARange()
G4bool G4EmParameters::BuildCSDARange () const
Definition at line 200 of file G4EmParameters.cc.
Referenced by G4LossTableManager::BuildTables(), G4EmCalculator::GetCSDARange(), G4EmCalculator::GetRange(), and G4VEnergyLossProcess::PreparePhysicsTable().
CheckRegion()
G4String G4EmParameters::CheckRegion (const G4String & reg) const private
Definition at line 1007 of file G4EmParameters.cc.
Referenced by ActivateForcedInteraction(), ActivateSecondaryBiasing(), AddDNA(), AddMicroElec(), AddPAIModel(), AddPhysics(), SetDeexActiveRegion(), and SetSubCutoff().
DeexcitationIgnoreCut()
G4bool G4EmParameters::DeexcitationIgnoreCut () const
Definition at line 312 of file G4EmParameters.cc.
Referenced by G4ECDecay::DecayIt(), G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), and G4RadioactiveDecay::StreamInfo().
DefineRegParamForDeex()
void G4EmParameters::DefineRegParamForDeex (G4VAtomDeexcitation * ptr) const
Definition at line 1331 of file G4EmParameters.cc.
Referenced by G4EmModelActivator::ActivateEmOptions(), and G4VAtomDeexcitation::InitialiseAtomicDeexcitation().
DefineRegParamForEM()
void G4EmParameters::DefineRegParamForEM (G4VEmProcess * ptr) const
Definition at line 1301 of file G4EmParameters.cc.
Referenced by G4VEmProcess::PreparePhysicsTable().
DefineRegParamForLoss()
void G4EmParameters::DefineRegParamForLoss (G4VEnergyLossProcess * ptr, G4bool isElectron) const
Definition at line 1261 of file G4EmParameters.cc.
Referenced by G4VEnergyLossProcess::PreparePhysicsTable().
DNAElectronMsc()
G4bool G4EmParameters::DNAElectronMsc () const
Definition at line 452 of file G4EmParameters.cc.
DNAeSolvationSubType()
G4DNAModelSubType G4EmParameters::DNAeSolvationSubType () const
Definition at line 963 of file G4EmParameters.cc.
Referenced by G4DNASolvationModelFactory::GetMacroDefinedModel().
DNAFast()
G4bool G4EmParameters::DNAFast () const
Definition at line 430 of file G4EmParameters.cc.
DNAStationary()
G4bool G4EmParameters::DNAStationary () const
Definition at line 441 of file G4EmParameters.cc.
Dump()
void G4EmParameters::Dump () const
Definition at line 1441 of file G4EmParameters.cc.
Referenced by PhysListEmLivermore::PhysListEmLivermore(), PhysListEmPenelope::PhysListEmPenelope(), and G4EmParametersMessenger::SetNewValue().
EnableSamplingTable()
G4bool G4EmParameters::EnableSamplingTable () const
Definition at line 504 of file G4EmParameters.cc.
Referenced by G4SeltzerBergerModel::Initialise().
FactorForAngleLimit()
G4double G4EmParameters::FactorForAngleLimit () const
Definition at line 703 of file G4EmParameters.cc.
Referenced by G4WentzelOKandVIxSection::Initialise(), and G4CoulombScattering::InitialiseProcess().
Fluo()
G4bool G4EmParameters::Fluo () const
Definition at line 255 of file G4EmParameters.cc.
Referenced by G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), and G4RadioactiveDecay::StreamInfo().
GeneralProcessActive()
G4bool G4EmParameters::GeneralProcessActive () const
Definition at line 473 of file G4EmParameters.cc.
GetConversionType()
G4int G4EmParameters::GetConversionType () const
Definition at line 974 of file G4EmParameters.cc.
Referenced by G4BetheHeitler5DModel::Initialise().
GetDirectionalSplitting()
G4bool G4EmParameters::GetDirectionalSplitting () inline
Definition at line 311 of file G4EmParameters.hh.
Referenced by G4EmBiasingManager::Initialise().
GetDirectionalSplittingRadius()
G4double G4EmParameters::GetDirectionalSplittingRadius () inline
Definition at line 320 of file G4EmParameters.hh.
Referenced by G4EmBiasingManager::Initialise().
GetDirectionalSplittingTarget()
G4ThreeVector G4EmParameters::GetDirectionalSplittingTarget () inline
Definition at line 316 of file G4EmParameters.hh.
Referenced by G4EmBiasingManager::Initialise().
GetEmSaturation()
G4EmSaturation * G4EmParameters::GetEmSaturation ()
Definition at line 509 of file G4EmParameters.cc.
Referenced by G4LossTableManager::EmSaturation().
Initialise()
void G4EmParameters::Initialise () private
Definition at line 111 of file G4EmParameters.cc.
Referenced by G4EmParameters(), and SetDefaults().
Instance()
G4EmParameters * G4EmParameters::Instance (void) static
Definition at line 69 of file G4EmParameters.cc.
Referenced by G4EmModelActivator::ActivateEmOptions(), DMXPhysicsList::ConstructEM(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4RadioactiveDecayPhysics::ConstructProcess(), G4EmStandardPhysicsSS::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), G4EmStandardPhysics_option2::ConstructProcess(), G4ECDecay::DecayIt(), G4ITDecay::DecayIt(), ElectromagneticPhysics::ElectromagneticPhysics(), G4EmCalculator::G4EmCalculator(), G4EmDNAPhysics::G4EmDNAPhysics(), G4EmDNAPhysics_option1::G4EmDNAPhysics_option1(), G4EmDNAPhysics_option2::G4EmDNAPhysics_option2(), G4EmDNAPhysics_option3::G4EmDNAPhysics_option3(), G4EmDNAPhysics_option4::G4EmDNAPhysics_option4(), G4EmDNAPhysics_option5::G4EmDNAPhysics_option5(), G4EmDNAPhysics_option6::G4EmDNAPhysics_option6(), G4EmDNAPhysics_option7::G4EmDNAPhysics_option7(), G4EmDNAPhysics_option8::G4EmDNAPhysics_option8(), G4EmDNAPhysics_stationary::G4EmDNAPhysics_stationary(), G4EmDNAPhysics_stationary_option2::G4EmDNAPhysics_stationary_option2(), G4EmDNAPhysics_stationary_option4::G4EmDNAPhysics_stationary_option4(), G4EmDNAPhysics_stationary_option6::G4EmDNAPhysics_stationary_option6(), G4EmDNAPhysicsActivator::G4EmDNAPhysicsActivator(), G4EmLEPTSPhysics::G4EmLEPTSPhysics(), G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmModelActivator::G4EmModelActivator(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmProcessOptions::G4EmProcessOptions(), G4EmStandardPhysics::G4EmStandardPhysics(), G4EmStandardPhysics_option1::G4EmStandardPhysics_option1(), G4EmStandardPhysics_option2::G4EmStandardPhysics_option2(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmStandardPhysicsGS::G4EmStandardPhysicsGS(), G4EmStandardPhysicsSS::G4EmStandardPhysicsSS(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), G4LossTableBuilder::G4LossTableBuilder(), G4LossTableManager::G4LossTableManager(), G4RadioactiveDecayPhysics::G4RadioactiveDecayPhysics(), G4VAtomDeexcitation::G4VAtomDeexcitation(), G4VEmProcess::G4VEmProcess(), G4VEnergyLossProcess::G4VEnergyLossProcess(), G4VMultipleScattering::G4VMultipleScattering(), G4DNASolvationModelFactory::GetMacroDefinedModel(), G4VMscModel::GetParticleChangeForMSC(), G4TablesForExtrapolator::Initialisation(), G4eplusTo2GammaOKVIModel::Initialise(), G4AtomicTransitionManager::Initialise(), G4BetheHeitler5DModel::Initialise(), G4BetheBlochModel::Initialise(), G4EmBiasingManager::Initialise(), G4WentzelVIModel::Initialise(), G4PenelopeIonisationModel::Initialise(), G4eSingleCoulombScatteringModel::Initialise(), G4SeltzerBergerModel::Initialise(), G4BraggIonModel::Initialise(), G4UrbanMscModel::Initialise(), G4BraggModel::Initialise(), G4WentzelOKandVIxSection::Initialise(), G4GoudsmitSaundersonMscModel::Initialise(), G4WentzelOKandVIxSection::InitialiseA(), G4VEmModel::InitialiseElementSelectors(), G4ePolarizedBremsstrahlung::InitialiseEnergyLossProcess(), G4LDMBremsstrahlung::InitialiseEnergyLossProcess(), G4hPairProduction::InitialiseEnergyLossProcess(), G4hBremsstrahlung::InitialiseEnergyLossProcess(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4ePairProduction::InitialiseEnergyLossProcess(), G4ePolarizedIonisation::InitialiseEnergyLossProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), G4MuPairProduction::InitialiseEnergyLossProcess(), G4eIonisation::InitialiseEnergyLossProcess(), G4eBremsstrahlung::InitialiseEnergyLossProcess(), G4MuBremsstrahlung::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), G4UAtomicDeexcitation::InitialiseForNewRun(), G4LivermoreGammaConversionModel::InitialiseProbability(), G4CoulombScattering::InitialiseProcess(), G4PolarizedGammaConversion::InitialiseProcess(), G4ComptonScattering::InitialiseProcess(), G4PolarizedCompton::InitialiseProcess(), G4PolarizedPhotoElectricEffect::InitialiseProcess(), G4GammaConversion::InitialiseProcess(), G4PhotoElectricEffect::InitialiseProcess(), main(), G4CoulombScattering::MinPrimaryEnergy(), PhysListEm19DStandard::PhysListEm19DStandard(), PhysListEm5DStandard::PhysListEm5DStandard(), PhysListEmLivermore::PhysListEmLivermore(), PhysListEmPenelope::PhysListEmPenelope(), PhysListEmStandard_GS::PhysListEmStandard_GS(), PhysListEmStandard_option0::PhysListEmStandard_option0(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), PhysListEmStandard_SS::PhysListEmStandard_SS(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), PhysListEmStandardSS::PhysListEmStandardSS(), PhysListEmStandardWVI::PhysListEmStandardWVI(), G4EmDataHandler::RetrievePhysicsTable(), G4RadioactiveDecay::StreamInfo(), G4CoulombScattering::StreamProcessInfo(), and G4eBremsstrahlung::StreamProcessInfo().
Integral()
G4bool G4EmParameters::Integral () const
Definition at line 389 of file G4EmParameters.cc.
Referenced by G4VEnergyLossProcess::PreparePhysicsTable().
IsLocked()
G4bool G4EmParameters::IsLocked () const private
Definition at line 1451 of file G4EmParameters.cc.
Referenced by ActivateAngularGeneratorForIonisation(), ActivateForcedInteraction(), ActivateSecondaryBiasing(), AddDNA(), AddMicroElec(), AddPAIModel(), AddPhysics(), SetApplyCuts(), SetAugerCascade(), SetBeardenFluoDir(), SetBremsstrahlungTh(), SetBuildCSDARange(), SetConversionType(), SetDeexActiveRegion(), SetDeexcitationIgnoreCut(), SetDefaults(), SetDNAElectronMsc(), SetDNAeSolvationSubType(), SetDNAFast(), SetDNAStationary(), SetEnableSamplingTable(), SetFactorForAngleLimit(), SetFluo(), SetGeneralProcessActive(), SetIntegral(), SetLambdaFactor(), SetLatDisplacementBeyondSafety(), SetLateralDisplacement(), SetLateralDisplacementAlg96(), SetLinearLossLimit(), SetLossFluctuations(), SetLowestElectronEnergy(), SetLowestMuHadEnergy(), SetLowestTripletEnergy(), SetLPM(), SetMaxEnergy(), SetMaxEnergyForCSDARange(), SetMinEnergy(), SetMinSubRange(), SetMscEnergyLimit(), SetMscGeomFactor(), SetMscMuHadRangeFactor(), SetMscMuHadStepLimitType(), SetMscRangeFactor(), SetMscSkin(), SetMscStepLimitType(), SetMscThetaLimit(), SetMuHadLateralDisplacement(), SetNuclearFormfactorType(), SetNumberOfBins(), SetNumberOfBinsPerDecade(), SetOnIsolated(), SetPixe(), SetPIXECrossSectionModel(), SetPIXEElectronCrossSectionModel(), SetProcessBiasingFactor(), SetScreeningFactor(), SetSpline(), SetStepFunction(), SetStepFunctionMuHad(), SetSubCutoff(), SetUseCutAsFinalRange(), SetUseMottCorrection(), SetVerbose(), and SetWorkerVerbose().
LambdaFactor()
G4double G4EmParameters::LambdaFactor () const
Definition at line 685 of file G4EmParameters.cc.
Referenced by G4VEmProcess::PreparePhysicsTable(), and G4VEnergyLossProcess::PreparePhysicsTable().
LatDisplacementBeyondSafety()
G4bool G4EmParameters::LatDisplacementBeyondSafety () const
Definition at line 356 of file G4EmParameters.cc.
Referenced by G4VMultipleScattering::PreparePhysicsTable().
LateralDisplacement()
G4bool G4EmParameters::LateralDisplacement () const
Definition at line 323 of file G4EmParameters.cc.
Referenced by G4VMultipleScattering::PreparePhysicsTable().
LateralDisplacementAlg96()
G4bool G4EmParameters::LateralDisplacementAlg96 () const
Definition at line 334 of file G4EmParameters.cc.
Referenced by G4UrbanMscModel::Initialise().
LinearLossLimit()
G4double G4EmParameters::LinearLossLimit () const
Definition at line 649 of file G4EmParameters.cc.
Referenced by G4VEnergyLossProcess::PreparePhysicsTable().
LossFluctuation()
G4bool G4EmParameters::LossFluctuation () const
Definition at line 189 of file G4EmParameters.cc.
Referenced by G4VEnergyLossProcess::PreparePhysicsTable().
LowestElectronEnergy()
G4double G4EmParameters::LowestElectronEnergy () const
Definition at line 602 of file G4EmParameters.cc.
Referenced by G4EmCalculator::ComputeCrossSectionPerAtom(), G4EmCalculator::ComputeCrossSectionPerShell(), G4EmCalculator::ComputeCrossSectionPerVolume(), G4VEnergyLossProcess::G4VEnergyLossProcess(), and G4VEnergyLossProcess::PreparePhysicsTable().
LowestMuHadEnergy()
G4double G4EmParameters::LowestMuHadEnergy () const
Definition at line 620 of file G4EmParameters.cc.
Referenced by G4VEnergyLossProcess::PreparePhysicsTable().
LowestTripletEnergy()
G4double G4EmParameters::LowestTripletEnergy () const
Definition at line 631 of file G4EmParameters.cc.
Referenced by G4eplusTo2GammaOKVIModel::Initialise().
LPM()
G4bool G4EmParameters::LPM () const
Definition at line 211 of file G4EmParameters.cc.
Referenced by G4eBremsstrahlung::InitialiseEnergyLossProcess(), and G4eBremsstrahlung::StreamProcessInfo().
MaxEnergyForCSDARange()
G4double G4EmParameters::MaxEnergyForCSDARange () const
Definition at line 584 of file G4EmParameters.cc.
Referenced by G4VEnergyLossProcess::PreparePhysicsTable().
MaxKinEnergy()
G4double G4EmParameters::MaxKinEnergy () const
Definition at line 566 of file G4EmParameters.cc.
Referenced by G4EmDNAPhysicsActivator::AddElectronModels0(), G4EmDNAPhysicsActivator::AddGenericIonModels0(), G4EmDNAPhysicsActivator::AddHeliumModels0(), G4EmDNAPhysicsActivator::AddProtonModels0(), G4VEmProcess::BuildLambdaTable(), G4VMscModel::GetParticleChangeForMSC(), G4ePolarizedBremsstrahlung::InitialiseEnergyLossProcess(), G4LDMBremsstrahlung::InitialiseEnergyLossProcess(), G4hPairProduction::InitialiseEnergyLossProcess(), G4hBremsstrahlung::InitialiseEnergyLossProcess(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4ePairProduction::InitialiseEnergyLossProcess(), G4ePolarizedIonisation::InitialiseEnergyLossProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), G4MuPairProduction::InitialiseEnergyLossProcess(), G4eIonisation::InitialiseEnergyLossProcess(), G4eBremsstrahlung::InitialiseEnergyLossProcess(), G4MuBremsstrahlung::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), G4CoulombScattering::InitialiseProcess(), G4PolarizedGammaConversion::InitialiseProcess(), G4GammaGeneralProcess::InitialiseProcess(), G4ComptonScattering::InitialiseProcess(), G4PolarizedCompton::InitialiseProcess(), G4PolarizedPhotoElectricEffect::InitialiseProcess(), G4GammaConversion::InitialiseProcess(), G4PhotoElectricEffect::InitialiseProcess(), G4VEmProcess::PreparePhysicsTable(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4VEmProcess::PrintWarning(), and G4VEmProcess::SetMinKinEnergyPrim().
MinKinEnergy()
G4double G4EmParameters::MinKinEnergy () const
Definition at line 547 of file G4EmParameters.cc.
Referenced by G4VEmProcess::BuildLambdaTable(), G4VMscModel::GetParticleChangeForMSC(), G4ePolarizedBremsstrahlung::InitialiseEnergyLossProcess(), G4LDMBremsstrahlung::InitialiseEnergyLossProcess(), G4hPairProduction::InitialiseEnergyLossProcess(), G4hBremsstrahlung::InitialiseEnergyLossProcess(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4ePairProduction::InitialiseEnergyLossProcess(), G4ePolarizedIonisation::InitialiseEnergyLossProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), G4MuPairProduction::InitialiseEnergyLossProcess(), G4eIonisation::InitialiseEnergyLossProcess(), G4eBremsstrahlung::InitialiseEnergyLossProcess(), G4MuBremsstrahlung::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), G4CoulombScattering::InitialiseProcess(), G4PolarizedGammaConversion::InitialiseProcess(), G4GammaGeneralProcess::InitialiseProcess(), G4ComptonScattering::InitialiseProcess(), G4PolarizedCompton::InitialiseProcess(), G4PolarizedPhotoElectricEffect::InitialiseProcess(), G4GammaConversion::InitialiseProcess(), G4PhotoElectricEffect::InitialiseProcess(), G4VEmProcess::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4VEmProcess::PrintWarning(), and G4VEmProcess::SetMinKinEnergyPrim().
MinSubRange()
G4double G4EmParameters::MinSubRange () const
Definition at line 528 of file G4EmParameters.cc.
Referenced by G4VEnergyLossProcess::PreparePhysicsTable().
MscEnergyLimit()
G4double G4EmParameters::MscEnergyLimit () const
Definition at line 739 of file G4EmParameters.cc.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), and G4EmStandardPhysics_option2::ConstructProcess().
MscGeomFactor()
G4double G4EmParameters::MscGeomFactor () const
Definition at line 793 of file G4EmParameters.cc.
Referenced by G4VMultipleScattering::GeomFactor(), and G4VMultipleScattering::PreparePhysicsTable().
MscMuHadRangeFactor()
G4double G4EmParameters::MscMuHadRangeFactor () const
Definition at line 775 of file G4EmParameters.cc.
Referenced by G4VMultipleScattering::PreparePhysicsTable().
MscMuHadStepLimitType()
G4MscStepLimitType G4EmParameters::MscMuHadStepLimitType () const
Definition at line 940 of file G4EmParameters.cc.
Referenced by G4VMultipleScattering::PreparePhysicsTable().
MscRangeFactor()
G4double G4EmParameters::MscRangeFactor () const
Definition at line 757 of file G4EmParameters.cc.
Referenced by G4VMultipleScattering::PreparePhysicsTable().
MscSkin()
G4double G4EmParameters::MscSkin () const
Definition at line 811 of file G4EmParameters.cc.
Referenced by G4VMultipleScattering::PreparePhysicsTable(), and G4VMultipleScattering::Skin().
MscStepLimitType()
G4MscStepLimitType G4EmParameters::MscStepLimitType () const
Definition at line 929 of file G4EmParameters.cc.
Referenced by G4VMultipleScattering::PreparePhysicsTable().
MscThetaLimit()
G4double G4EmParameters::MscThetaLimit () const
Definition at line 721 of file G4EmParameters.cc.
Referenced by G4CoulombScattering::InitialiseProcess(), G4CoulombScattering::MinPrimaryEnergy(), G4VMultipleScattering::PolarAngleLimit(), G4VEmProcess::PolarAngleLimit(), G4VEmProcess::PreparePhysicsTable(), G4VMultipleScattering::PreparePhysicsTable(), and G4CoulombScattering::StreamProcessInfo().
MuHadLateralDisplacement()
G4bool G4EmParameters::MuHadLateralDisplacement () const
Definition at line 345 of file G4EmParameters.cc.
Referenced by G4VMultipleScattering::PreparePhysicsTable().
NuclearFormfactorType()
G4NuclearFormfactorType G4EmParameters::NuclearFormfactorType () const
Definition at line 952 of file G4EmParameters.cc.
Referenced by G4eSingleCoulombScatteringModel::Initialise(), and G4WentzelOKandVIxSection::Initialise().
NumberOfBins()
G4int G4EmParameters::NumberOfBins () const
Definition at line 876 of file G4EmParameters.cc.
Referenced by G4VEmProcess::PrintWarning().
NumberOfBinsPerDecade()
G4int G4EmParameters::NumberOfBinsPerDecade () const
Definition at line 895 of file G4EmParameters.cc.
Referenced by G4VEmProcess::BuildLambdaTable(), G4LossTableBuilder::BuildTableForModel(), G4WentzelVIModel::Initialise(), G4VEmModel::InitialiseElementSelectors(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), G4LivermoreGammaConversionModel::InitialiseProbability(), G4GammaGeneralProcess::InitialiseProcess(), G4VEnergyLossProcess::PreparePhysicsTable(), and G4VEnergyLossProcess::StreamInfo().
OnIsolated()
G4bool G4EmParameters::OnIsolated () const
Definition at line 493 of file G4EmParameters.cc.
Referenced by G4BetheHeitler5DModel::Initialise().
operator=()
G4EmParameters& G4EmParameters::operator= (const G4EmParameters & right) delete
ParticlesPAI()
const std::vector< G4String > & G4EmParameters::ParticlesPAI () const
Definition at line 1042 of file G4EmParameters.cc.
Referenced by G4EmModelActivator::ActivatePAI().
Pixe()
G4bool G4EmParameters::Pixe () const
Definition at line 301 of file G4EmParameters.cc.
Referenced by G4VAtomDeexcitation::InitialiseAtomicDeexcitation().
PIXECrossSectionModel()
const G4String & G4EmParameters::PIXECrossSectionModel ()
Definition at line 986 of file G4EmParameters.cc.
Referenced by G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), and G4UAtomicDeexcitation::InitialiseForNewRun().
PIXEElectronCrossSectionModel()
const G4String & G4EmParameters::PIXEElectronCrossSectionModel ()
Definition at line 997 of file G4EmParameters.cc.
Referenced by G4PenelopeIonisationModel::Initialise(), G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), and G4UAtomicDeexcitation::InitialiseForNewRun().
PrintWarning()
void G4EmParameters::PrintWarning (G4ExceptionDescription & ed) const private
Definition at line 1002 of file G4EmParameters.cc.
Referenced by ActivateForcedInteraction(), ActivateSecondaryBiasing(), SetBremsstrahlungTh(), SetFactorForAngleLimit(), SetLambdaFactor(), SetLinearLossLimit(), SetLowestElectronEnergy(), SetLowestMuHadEnergy(), SetMaxEnergy(), SetMaxEnergyForCSDARange(), SetMinEnergy(), SetMinSubRange(), SetMscEnergyLimit(), SetMscGeomFactor(), SetMscMuHadRangeFactor(), SetMscRangeFactor(), SetMscSkin(), SetMscThetaLimit(), SetNumberOfBins(), SetNumberOfBinsPerDecade(), SetProcessBiasingFactor(), SetScreeningFactor(), SetStepFunction(), and SetStepFunctionMuHad().
RegionsDNA()
const std::vector< G4String > & G4EmParameters::RegionsDNA () const
Definition at line 1085 of file G4EmParameters.cc.
Referenced by G4EmDNAPhysicsActivator::ConstructProcess().
RegionsMicroElec()
const std::vector< G4String > & G4EmParameters::RegionsMicroElec () const
Definition at line 1068 of file G4EmParameters.cc.
Referenced by G4EmModelActivator::ActivateMicroElec(), and G4EmModelActivator::G4EmModelActivator().
RegionsMsc()
const std::vector< G4String > & G4EmParameters::RegionsMsc () const
Definition at line 1100 of file G4EmParameters.cc.
RegionsPAI()
const std::vector< G4String > & G4EmParameters::RegionsPAI () const
Definition at line 1047 of file G4EmParameters.cc.
Referenced by G4EmModelActivator::ActivatePAI(), and G4EmModelActivator::G4EmModelActivator().
RegionsPhysics()
const std::vector< G4String > & G4EmParameters::RegionsPhysics () const
Definition at line 1122 of file G4EmParameters.cc.
Referenced by G4EmModelActivator::ActivateEmOptions(), and G4EmModelActivator::G4EmModelActivator().
ScreeningFactor()
G4double G4EmParameters::ScreeningFactor () const
Definition at line 829 of file G4EmParameters.cc.
Referenced by G4WentzelOKandVIxSection::InitialiseA().
SetApplyCuts()
void G4EmParameters::SetApplyCuts (G4bool val)
Definition at line 238 of file G4EmParameters.cc.
Referenced by G4EmStandardPhysics_option1::G4EmStandardPhysics_option1(), G4EmStandardPhysics_option2::G4EmStandardPhysics_option2(), G4EmProcessOptions::SetApplyCuts(), and G4EmParametersMessenger::SetNewValue().
SetAuger()
void G4EmParameters::SetAuger (G4bool val)
Definition at line 271 of file G4EmParameters.cc.
Referenced by DMXPhysicsList::ConstructEM(), G4EmDNAPhysics::G4EmDNAPhysics(), G4EmDNAPhysics_option1::G4EmDNAPhysics_option1(), G4EmDNAPhysics_option2::G4EmDNAPhysics_option2(), G4EmDNAPhysics_option3::G4EmDNAPhysics_option3(), G4EmDNAPhysics_option4::G4EmDNAPhysics_option4(), G4EmDNAPhysics_option5::G4EmDNAPhysics_option5(), G4EmDNAPhysics_option6::G4EmDNAPhysics_option6(), G4EmDNAPhysics_option7::G4EmDNAPhysics_option7(), G4EmDNAPhysics_option8::G4EmDNAPhysics_option8(), G4EmDNAPhysics_stationary::G4EmDNAPhysics_stationary(), G4EmDNAPhysics_stationary_option2::G4EmDNAPhysics_stationary_option2(), G4EmDNAPhysics_stationary_option4::G4EmDNAPhysics_stationary_option4(), G4EmDNAPhysics_stationary_option6::G4EmDNAPhysics_stationary_option6(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmProcessOptions::SetAuger(), and G4EmParametersMessenger::SetNewValue().
SetAugerCascade()
void G4EmParameters::SetAugerCascade (G4bool val)
Definition at line 281 of file G4EmParameters.cc.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4RadioactiveDecayPhysics::ConstructProcess(), G4EmDNAPhysics::G4EmDNAPhysics(), G4EmDNAPhysics_option1::G4EmDNAPhysics_option1(), G4EmDNAPhysics_option2::G4EmDNAPhysics_option2(), G4EmDNAPhysics_option3::G4EmDNAPhysics_option3(), G4EmDNAPhysics_option4::G4EmDNAPhysics_option4(), G4EmDNAPhysics_option5::G4EmDNAPhysics_option5(), G4EmDNAPhysics_option6::G4EmDNAPhysics_option6(), G4EmDNAPhysics_option7::G4EmDNAPhysics_option7(), G4EmDNAPhysics_option8::G4EmDNAPhysics_option8(), G4EmDNAPhysics_stationary::G4EmDNAPhysics_stationary(), G4EmDNAPhysics_stationary_option2::G4EmDNAPhysics_stationary_option2(), G4EmDNAPhysics_stationary_option4::G4EmDNAPhysics_stationary_option4(), G4EmDNAPhysics_stationary_option6::G4EmDNAPhysics_stationary_option6(), G4EmStandardPhysicsSS::G4EmStandardPhysicsSS(), SetAuger(), and G4EmParametersMessenger::SetNewValue().
SetBeardenFluoDir()
void G4EmParameters::SetBeardenFluoDir (G4bool val)
Definition at line 260 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue().
SetBirksActive()
void G4EmParameters::SetBirksActive (G4bool val)
Definition at line 394 of file G4EmParameters.cc.
Referenced by GetEmSaturation(), SetEmSaturation(), and G4EmParametersMessenger::SetNewValue().
SetBremsstrahlungTh()
void G4EmParameters::SetBremsstrahlungTh (G4double val)
Definition at line 654 of file G4EmParameters.cc.
Referenced by G4EmProcessOptions::SetBremsstrahlungTh(), and G4EmParametersMessenger::SetNewValue().
SetBuildCSDARange()
void G4EmParameters::SetBuildCSDARange (G4bool val)
Definition at line 194 of file G4EmParameters.cc.
Referenced by PhysListEmLivermore::PhysListEmLivermore(), PhysListEmPenelope::PhysListEmPenelope(), PhysListEmStandard_GS::PhysListEmStandard_GS(), PhysListEmStandard_option0::PhysListEmStandard_option0(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), PhysListEmStandard_SS::PhysListEmStandard_SS(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), G4EmProcessOptions::SetBuildCSDARange(), and G4EmParametersMessenger::SetNewValue().
SetConversionType()
void G4EmParameters::SetConversionType (G4int val)
Definition at line 968 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue().
SetDeexActiveRegion()
void G4EmParameters::SetDeexActiveRegion (const G4String & region, G4bool fdeex, G4bool fauger, G4bool fpixe)
Definition at line 1148 of file G4EmParameters.cc.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmProcessOptions::SetDeexcitationActiveRegion(), and G4EmParametersMessenger::SetNewValue().
SetDeexcitationIgnoreCut()
void G4EmParameters::SetDeexcitationIgnoreCut (G4bool val)
Definition at line 306 of file G4EmParameters.cc.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmDNAPhysics::G4EmDNAPhysics(), G4EmDNAPhysics_option1::G4EmDNAPhysics_option1(), G4EmDNAPhysics_option2::G4EmDNAPhysics_option2(), G4EmDNAPhysics_option3::G4EmDNAPhysics_option3(), G4EmDNAPhysics_option4::G4EmDNAPhysics_option4(), G4EmDNAPhysics_option5::G4EmDNAPhysics_option5(), G4EmDNAPhysics_option6::G4EmDNAPhysics_option6(), G4EmDNAPhysics_option7::G4EmDNAPhysics_option7(), G4EmDNAPhysics_option8::G4EmDNAPhysics_option8(), G4EmDNAPhysics_stationary::G4EmDNAPhysics_stationary(), G4EmDNAPhysics_stationary_option2::G4EmDNAPhysics_stationary_option2(), G4EmDNAPhysics_stationary_option4::G4EmDNAPhysics_stationary_option4(), G4EmDNAPhysics_stationary_option6::G4EmDNAPhysics_stationary_option6(), G4EmProcessOptions::SetDeexcitationIgnoreCuts(), and G4EmParametersMessenger::SetNewValue().
SetDefaults()
void G4EmParameters::SetDefaults ()
Definition at line 106 of file G4EmParameters.cc.
Referenced by ElectromagneticPhysics::ElectromagneticPhysics(), G4EmDNAPhysics::G4EmDNAPhysics(), G4EmDNAPhysics_option1::G4EmDNAPhysics_option1(), G4EmDNAPhysics_option2::G4EmDNAPhysics_option2(), G4EmDNAPhysics_option3::G4EmDNAPhysics_option3(), G4EmDNAPhysics_option4::G4EmDNAPhysics_option4(), G4EmDNAPhysics_option5::G4EmDNAPhysics_option5(), G4EmDNAPhysics_option6::G4EmDNAPhysics_option6(), G4EmDNAPhysics_option7::G4EmDNAPhysics_option7(), G4EmDNAPhysics_option8::G4EmDNAPhysics_option8(), G4EmDNAPhysics_stationary::G4EmDNAPhysics_stationary(), G4EmDNAPhysics_stationary_option2::G4EmDNAPhysics_stationary_option2(), G4EmDNAPhysics_stationary_option4::G4EmDNAPhysics_stationary_option4(), G4EmDNAPhysics_stationary_option6::G4EmDNAPhysics_stationary_option6(), G4EmLEPTSPhysics::G4EmLEPTSPhysics(), G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics::G4EmStandardPhysics(), G4EmStandardPhysics_option1::G4EmStandardPhysics_option1(), G4EmStandardPhysics_option2::G4EmStandardPhysics_option2(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmStandardPhysicsGS::G4EmStandardPhysicsGS(), G4EmStandardPhysicsSS::G4EmStandardPhysicsSS(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), PhysListEm19DStandard::PhysListEm19DStandard(), PhysListEm5DStandard::PhysListEm5DStandard(), PhysListEmLivermore::PhysListEmLivermore(), PhysListEmPenelope::PhysListEmPenelope(), PhysListEmStandard_GS::PhysListEmStandard_GS(), PhysListEmStandard_option0::PhysListEmStandard_option0(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), PhysListEmStandard_SS::PhysListEmStandard_SS(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), PhysListEmStandardSS::PhysListEmStandardSS(), and PhysListEmStandardWVI::PhysListEmStandardWVI().
SetDirectionalSplitting()
void G4EmParameters::SetDirectionalSplitting (G4int v) inline
Definition at line 312 of file G4EmParameters.hh.
Referenced by G4EmParametersMessenger::SetNewValue().
SetDirectionalSplittingRadius()
void G4EmParameters::SetDirectionalSplittingRadius (G4double r) inline
Definition at line 318 of file G4EmParameters.hh.
Referenced by G4EmParametersMessenger::SetNewValue().
SetDirectionalSplittingTarget()
void G4EmParameters::SetDirectionalSplittingTarget (G4ThreeVector v) inline
Definition at line 314 of file G4EmParameters.hh.
Referenced by G4EmParametersMessenger::SetNewValue().
SetDNAElectronMsc()
void G4EmParameters::SetDNAElectronMsc (G4bool val)
Definition at line 446 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue().
SetDNAeSolvationSubType()
void G4EmParameters::SetDNAeSolvationSubType (G4DNAModelSubType val)
Definition at line 957 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue().
SetDNAFast()
void G4EmParameters::SetDNAFast (G4bool val)
Definition at line 424 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue().
SetDNAStationary()
void G4EmParameters::SetDNAStationary (G4bool val)
Definition at line 435 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue().
SetEmSaturation()
void G4EmParameters::SetEmSaturation (G4EmSaturation * ptr)
Definition at line 478 of file G4EmParameters.cc.
SetEnableSamplingTable()
void G4EmParameters::SetEnableSamplingTable (G4bool val)
Definition at line 498 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue().
SetFactorForAngleLimit()
void G4EmParameters::SetFactorForAngleLimit (G4double val)
Definition at line 690 of file G4EmParameters.cc.
Referenced by G4EmProcessOptions::SetFactorForAngleLimit(), and G4EmParametersMessenger::SetNewValue().
SetFluo()
void G4EmParameters::SetFluo (G4bool val)
Definition at line 249 of file G4EmParameters.cc.
Referenced by DMXPhysicsList::ConstructEM(), G4EmDNAPhysics::G4EmDNAPhysics(), G4EmDNAPhysics_option1::G4EmDNAPhysics_option1(), G4EmDNAPhysics_option2::G4EmDNAPhysics_option2(), G4EmDNAPhysics_option3::G4EmDNAPhysics_option3(), G4EmDNAPhysics_option4::G4EmDNAPhysics_option4(), G4EmDNAPhysics_option5::G4EmDNAPhysics_option5(), G4EmDNAPhysics_option6::G4EmDNAPhysics_option6(), G4EmDNAPhysics_option7::G4EmDNAPhysics_option7(), G4EmDNAPhysics_option8::G4EmDNAPhysics_option8(), G4EmDNAPhysics_stationary::G4EmDNAPhysics_stationary(), G4EmDNAPhysics_stationary_option2::G4EmDNAPhysics_stationary_option2(), G4EmDNAPhysics_stationary_option4::G4EmDNAPhysics_stationary_option4(), G4EmDNAPhysics_stationary_option6::G4EmDNAPhysics_stationary_option6(), G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), PhysListEm19DStandard::PhysListEm19DStandard(), PhysListEm5DStandard::PhysListEm5DStandard(), G4EmProcessOptions::SetFluo(), and G4EmParametersMessenger::SetNewValue().
SetGeneralProcessActive()
void G4EmParameters::SetGeneralProcessActive (G4bool val)
Definition at line 457 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue().
SetIntegral()
void G4EmParameters::SetIntegral (G4bool val)
Definition at line 383 of file G4EmParameters.cc.
Referenced by G4EmProcessOptions::SetIntegral(), and G4EmParametersMessenger::SetNewValue().
SetLambdaFactor()
void G4EmParameters::SetLambdaFactor (G4double val)
Definition at line 672 of file G4EmParameters.cc.
Referenced by G4EmProcessOptions::SetLambdaFactor(), and G4EmParametersMessenger::SetNewValue().
SetLatDisplacementBeyondSafety()
void G4EmParameters::SetLatDisplacementBeyondSafety (G4bool val)
Definition at line 350 of file G4EmParameters.cc.
Referenced by G4EmProcessOptions::SetDisplacementBeyondSafety(), and G4EmParametersMessenger::SetNewValue().
SetLateralDisplacement()
void G4EmParameters::SetLateralDisplacement (G4bool val)
Definition at line 317 of file G4EmParameters.cc.
Referenced by G4EmStandardPhysics_option2::G4EmStandardPhysics_option2(), G4EmProcessOptions::SetMscLateralDisplacement(), and G4EmParametersMessenger::SetNewValue().
SetLateralDisplacementAlg96()
void G4EmParameters::SetLateralDisplacementAlg96 (G4bool val)
Definition at line 328 of file G4EmParameters.cc.
Referenced by G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), PhysListEm19DStandard::PhysListEm19DStandard(), PhysListEm5DStandard::PhysListEm5DStandard(), PhysListEmStandard_option3::PhysListEmStandard_option3(), and G4EmParametersMessenger::SetNewValue().
SetLinearLossLimit()
void G4EmParameters::SetLinearLossLimit (G4double val)
Definition at line 636 of file G4EmParameters.cc.
Referenced by G4EmProcessOptions::SetLinearLossLimit(), and G4EmParametersMessenger::SetNewValue().
SetLossFluctuations()
void G4EmParameters::SetLossFluctuations (G4bool val)
Definition at line 183 of file G4EmParameters.cc.
Referenced by G4EmProcessOptions::SetLossFluctuations(), and G4EmParametersMessenger::SetNewValue().
SetLowestElectronEnergy()
void G4EmParameters::SetLowestElectronEnergy (G4double val)
Definition at line 589 of file G4EmParameters.cc.
Referenced by G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmStandardPhysicsSS::G4EmStandardPhysicsSS(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), PhysListEmStandard_option0::PhysListEmStandard_option0(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), PhysListEmStandard_SS::PhysListEmStandard_SS(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), and G4EmParametersMessenger::SetNewValue().
SetLowestMuHadEnergy()
void G4EmParameters::SetLowestMuHadEnergy (G4double val)
Definition at line 607 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue().
SetLowestTripletEnergy()
void G4EmParameters::SetLowestTripletEnergy (G4double val)
Definition at line 625 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue().
SetLPM()
void G4EmParameters::SetLPM (G4bool val)
Definition at line 205 of file G4EmParameters.cc.
Referenced by G4EmProcessOptions::SetLPMFlag(), and G4EmParametersMessenger::SetNewValue().
SetMaxEnergy()
void G4EmParameters::SetMaxEnergy (G4double val)
Definition at line 552 of file G4EmParameters.cc.
Referenced by DMXPhysicsList::ConstructEM(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), PhysListEmLivermore::PhysListEmLivermore(), PhysListEmPenelope::PhysListEmPenelope(), PhysListEmStandard_GS::PhysListEmStandard_GS(), PhysListEmStandard_option0::PhysListEmStandard_option0(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), PhysListEmStandard_SS::PhysListEmStandard_SS(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), G4EmProcessOptions::SetMaxEnergy(), G4EmProcessOptions::SetMaxEnergyForMuons(), and G4EmParametersMessenger::SetNewValue().
SetMaxEnergyForCSDARange()
void G4EmParameters::SetMaxEnergyForCSDARange (G4double val)
Definition at line 571 of file G4EmParameters.cc.
Referenced by PhysListEmLivermore::PhysListEmLivermore(), PhysListEmPenelope::PhysListEmPenelope(), PhysListEmStandard_GS::PhysListEmStandard_GS(), PhysListEmStandard_option0::PhysListEmStandard_option0(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), PhysListEmStandard_SS::PhysListEmStandard_SS(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), G4EmProcessOptions::SetMaxEnergyForCSDARange(), and G4EmParametersMessenger::SetNewValue().
SetMinEnergy()
void G4EmParameters::SetMinEnergy (G4double val)
Definition at line 533 of file G4EmParameters.cc.
Referenced by G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), PhysListEmLivermore::PhysListEmLivermore(), PhysListEmPenelope::PhysListEmPenelope(), PhysListEmStandard_GS::PhysListEmStandard_GS(), PhysListEmStandard_option0::PhysListEmStandard_option0(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), PhysListEmStandard_SS::PhysListEmStandard_SS(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), G4EmProcessOptions::SetMinEnergy(), and G4EmParametersMessenger::SetNewValue().
SetMinSubRange()
void G4EmParameters::SetMinSubRange (G4double val)
Definition at line 515 of file G4EmParameters.cc.
Referenced by G4EmProcessOptions::SetMinSubRange(), and G4EmParametersMessenger::SetNewValue().
SetMscEnergyLimit()
void G4EmParameters::SetMscEnergyLimit (G4double val)
Definition at line 726 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue().
SetMscGeomFactor()
void G4EmParameters::SetMscGeomFactor (G4double val)
Definition at line 780 of file G4EmParameters.cc.
Referenced by G4EmProcessOptions::SetMscGeomFactor(), and G4EmParametersMessenger::SetNewValue().
SetMscMuHadRangeFactor()
void G4EmParameters::SetMscMuHadRangeFactor (G4double val)
Definition at line 762 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue().
SetMscMuHadStepLimitType()
void G4EmParameters::SetMscMuHadStepLimitType (G4MscStepLimitType val)
Definition at line 934 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue().
SetMscRangeFactor()
void G4EmParameters::SetMscRangeFactor (G4double val)
Definition at line 744 of file G4EmParameters.cc.
Referenced by G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option1::G4EmStandardPhysics_option1(), G4EmStandardPhysics_option2::G4EmStandardPhysics_option2(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysicsGS::G4EmStandardPhysicsGS(), PhysListEmStandard_GS::PhysListEmStandard_GS(), PhysListEmStandard_option4::PhysListEmStandard_option4(), G4EmProcessOptions::SetMscRangeFactor(), G4EmParametersMessenger::SetNewValue(), and G4VMultipleScattering::SetRangeFactor().
SetMscSkin()
void G4EmParameters::SetMscSkin (G4double val)
Definition at line 798 of file G4EmParameters.cc.
Referenced by G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), PhysListEmStandard_option4::PhysListEmStandard_option4(), G4EmParametersMessenger::SetNewValue(), G4EmProcessOptions::SetSkin(), and G4VMultipleScattering::SetSkin().
SetMscStepLimitType()
void G4EmParameters::SetMscStepLimitType (G4MscStepLimitType val)
Definition at line 923 of file G4EmParameters.cc.
Referenced by DMXPhysicsList::ConstructEM(), G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option1::G4EmStandardPhysics_option1(), G4EmStandardPhysics_option2::G4EmStandardPhysics_option2(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), PhysListEm19DStandard::PhysListEm19DStandard(), PhysListEm5DStandard::PhysListEm5DStandard(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), G4EmProcessOptions::SetMscStepLimitation(), G4EmParametersMessenger::SetNewValue(), and G4VMultipleScattering::SetStepLimitType().
SetMscThetaLimit()
void G4EmParameters::SetMscThetaLimit (G4double val)
Definition at line 708 of file G4EmParameters.cc.
Referenced by G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmStandardPhysicsSS::G4EmStandardPhysicsSS(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), PhysListEmStandard_SS::PhysListEmStandard_SS(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), PhysListEmStandardSS::PhysListEmStandardSS(), PhysListEmStandardWVI::PhysListEmStandardWVI(), G4EmParametersMessenger::SetNewValue(), and G4EmProcessOptions::SetPolarAngleLimit().
SetMuHadLateralDisplacement()
void G4EmParameters::SetMuHadLateralDisplacement (G4bool val)
Definition at line 339 of file G4EmParameters.cc.
Referenced by G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), G4EmProcessOptions::SetMscMuHadLateralDisplacement(), and G4EmParametersMessenger::SetNewValue().
SetNuclearFormfactorType()
void G4EmParameters::SetNuclearFormfactorType (G4NuclearFormfactorType val)
Definition at line 946 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue().
SetNumberOfBins()
void G4EmParameters::SetNumberOfBins (G4int val)
Definition at line 862 of file G4EmParameters.cc.
Referenced by G4EmProcessOptions::SetDEDXBinning(), G4EmProcessOptions::SetLambdaBinning(), and G4EmParametersMessenger::SetNewValue().
SetNumberOfBinsPerDecade()
void G4EmParameters::SetNumberOfBinsPerDecade (G4int val)
Definition at line 881 of file G4EmParameters.cc.
Referenced by G4EmModelActivator::ActivateEmOptions(), DMXPhysicsList::ConstructEM(), G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), PhysListEm19DStandard::PhysListEm19DStandard(), PhysListEm5DStandard::PhysListEm5DStandard(), PhysListEmLivermore::PhysListEmLivermore(), PhysListEmPenelope::PhysListEmPenelope(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), and G4EmParametersMessenger::SetNewValue().
SetOnIsolated()
void G4EmParameters::SetOnIsolated (G4bool val)
Definition at line 487 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue().
SetPixe()
void G4EmParameters::SetPixe (G4bool val)
Definition at line 294 of file G4EmParameters.cc.
Referenced by DMXPhysicsList::ConstructEM(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmStandardPhysicsSS::G4EmStandardPhysicsSS(), G4EmParametersMessenger::SetNewValue(), and G4EmProcessOptions::SetPIXE().
SetPIXECrossSectionModel()
void G4EmParameters::SetPIXECrossSectionModel (const G4String & sss)
Definition at line 979 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue(), and G4EmProcessOptions::SetPIXECrossSectionModel().
SetPIXEElectronCrossSectionModel()
void G4EmParameters::SetPIXEElectronCrossSectionModel (const G4String & sss)
Definition at line 991 of file G4EmParameters.cc.
Referenced by G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmParametersMessenger::SetNewValue(), and G4EmProcessOptions::SetPIXEElectronCrossSectionModel().
SetProcessBiasingFactor()
void G4EmParameters::SetProcessBiasingFactor (const G4String & procname, G4double val, G4bool wflag)
Definition at line 1177 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue(), and G4EmProcessOptions::SetProcessBiasingFactor().
SetScreeningFactor()
void G4EmParameters::SetScreeningFactor (G4double val)
Definition at line 816 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue().
SetSpline()
void G4EmParameters::SetSpline (G4bool val)
Definition at line 216 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue(), and G4EmProcessOptions::SetSplineFlag().
SetStepFunction()
void G4EmParameters::SetStepFunction (G4double v1, G4double v2)
Definition at line 834 of file G4EmParameters.cc.
Referenced by ElectromagneticPhysics::ElectromagneticPhysics(), G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), G4EmParametersMessenger::SetNewValue(), and G4EmProcessOptions::SetStepFunction().
SetStepFunctionMuHad()
void G4EmParameters::SetStepFunctionMuHad (G4double v1, G4double v2)
Definition at line 848 of file G4EmParameters.cc.
Referenced by ElectromagneticPhysics::ElectromagneticPhysics(), G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), and G4EmParametersMessenger::SetNewValue().
SetSubCutoff()
void G4EmParameters::SetSubCutoff (G4bool val, const G4String & region = "")
Definition at line 1132 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue(), and G4EmProcessOptions::SetSubCutoff().
SetUseCutAsFinalRange()
void G4EmParameters::SetUseCutAsFinalRange (G4bool val)
Definition at line 227 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue(), and G4EmProcessOptions::SetUseCutAsFinalRange().
SetUseICRU90Data()
void G4EmParameters::SetUseICRU90Data (G4bool val)
Definition at line 414 of file G4EmParameters.cc.
Referenced by G4EmLowEPPhysics::G4EmLowEPPhysics(), and G4EmParametersMessenger::SetNewValue().
SetUseMottCorrection()
void G4EmParameters::SetUseMottCorrection (G4bool val)
Definition at line 372 of file G4EmParameters.cc.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), PhysListEmStandard_option4::PhysListEmStandard_option4(), and G4EmParametersMessenger::SetNewValue().
SetVerbose()
void G4EmParameters::SetVerbose (G4int val)
Definition at line 900 of file G4EmParameters.cc.
Referenced by ElectromagneticPhysics::ElectromagneticPhysics(), G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics::G4EmStandardPhysics(), G4EmStandardPhysics_option1::G4EmStandardPhysics_option1(), G4EmStandardPhysics_option2::G4EmStandardPhysics_option2(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmStandardPhysicsGS::G4EmStandardPhysicsGS(), G4EmStandardPhysicsSS::G4EmStandardPhysicsSS(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), main(), PhysListEm19DStandard::PhysListEm19DStandard(), PhysListEm5DStandard::PhysListEm5DStandard(), PhysListEmLivermore::PhysListEmLivermore(), PhysListEmPenelope::PhysListEmPenelope(), PhysListEmStandard_GS::PhysListEmStandard_GS(), PhysListEmStandard_option0::PhysListEmStandard_option0(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), PhysListEmStandard_SS::PhysListEmStandard_SS(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), G4EmParametersMessenger::SetNewValue(), and G4EmProcessOptions::SetVerbose().
SetWorkerVerbose()
void G4EmParameters::SetWorkerVerbose (G4int val)
Definition at line 912 of file G4EmParameters.cc.
Referenced by G4EmParametersMessenger::SetNewValue(), and G4EmProcessOptions::SetWorkerVerbose().
Spline()
G4bool G4EmParameters::Spline () const
Definition at line 222 of file G4EmParameters.cc.
Referenced by G4VEnergyLossProcess::BuildDEDXTable(), G4VEnergyLossProcess::BuildLambdaTable(), G4TablesForExtrapolator::Initialisation(), G4VEnergyLossProcess::LambdaPhysicsVector(), G4VEmProcess::LambdaPhysicsVector(), G4VEmProcess::PreparePhysicsTable(), G4LossTableManager::ResetParameters(), G4EmDataHandler::RetrievePhysicsTable(), G4VEmProcess::RetrievePhysicsTable(), G4VEnergyLossProcess::RetrieveTable(), and G4VEnergyLossProcess::StreamInfo().
StreamInfo()
std::ostream & G4EmParameters::StreamInfo (std::ostream & os) const
Definition at line 1340 of file G4EmParameters.cc.
Referenced by Dump(), and operator<<().
TypesDNA()
const std::vector< G4String > & G4EmParameters::TypesDNA () const
Definition at line 1090 of file G4EmParameters.cc.
Referenced by G4EmDNAPhysicsActivator::ConstructProcess().
TypesMsc()
const std::vector< G4String > & G4EmParameters::TypesMsc () const
Definition at line 1105 of file G4EmParameters.cc.
TypesPAI()
const std::vector< G4String > & G4EmParameters::TypesPAI () const
Definition at line 1052 of file G4EmParameters.cc.
Referenced by G4EmModelActivator::ActivatePAI().
TypesPhysics()
const std::vector< G4String > & G4EmParameters::TypesPhysics () const
Definition at line 1127 of file G4EmParameters.cc.
Referenced by G4EmModelActivator::ActivateEmOptions().
UseAngularGeneratorForIonisation()
G4bool G4EmParameters::UseAngularGeneratorForIonisation () const
Definition at line 367 of file G4EmParameters.cc.
Referenced by G4VEnergyLossProcess::PreparePhysicsTable().
UseCutAsFinalRange()
G4bool G4EmParameters::UseCutAsFinalRange () const
Definition at line 233 of file G4EmParameters.cc.
Referenced by G4VEnergyLossProcess::PreparePhysicsTable().
UseICRU90Data()
G4bool G4EmParameters::UseICRU90Data () const
Definition at line 419 of file G4EmParameters.cc.
UseMottCorrection()
G4bool G4EmParameters::UseMottCorrection () const
Definition at line 378 of file G4EmParameters.cc.
Verbose()
G4int G4EmParameters::Verbose () const
Definition at line 907 of file G4EmParameters.cc.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmModelActivator::ActivateMicroElec(), G4EmModelActivator::ActivatePAI(), G4LossTableManager::G4LossTableManager(), G4BetheHeitler5DModel::Initialise(), G4GammaGeneralProcess::PreparePhysicsTable(), G4VEmProcess::PreparePhysicsTable(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4LossTableManager::ResetParameters(), and G4EmDataHandler::RetrievePhysicsTable().
WorkerVerbose()
G4int G4EmParameters::WorkerVerbose () const
Definition at line 918 of file G4EmParameters.cc.
Referenced by G4LossTableManager::G4LossTableManager(), G4GammaGeneralProcess::PreparePhysicsTable(), G4VEmProcess::PreparePhysicsTable(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), and G4LossTableManager::ResetParameters().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const G4EmParameters & par) friend
Definition at line 1446 of file G4EmParameters.cc.
Field Documentation
applyCuts
G4bool G4EmParameters::applyCuts private
Definition at line 357 of file G4EmParameters.hh.
Referenced by ApplyCuts(), Initialise(), SetApplyCuts(), and StreamInfo().
auger
G4bool G4EmParameters::auger private
Definition at line 360 of file G4EmParameters.hh.
Referenced by Auger(), Initialise(), SetAugerCascade(), and StreamInfo().
augerCascade
G4bool G4EmParameters::augerCascade private
Definition at line 361 of file G4EmParameters.hh.
Referenced by AugerCascade(), Initialise(), SetAugerCascade(), and StreamInfo().
beardenFluoDir
G4bool G4EmParameters::beardenFluoDir private
Definition at line 359 of file G4EmParameters.hh.
Referenced by BeardenFluoDir(), Initialise(), SetBeardenFluoDir(), and StreamInfo().
birks
G4bool G4EmParameters::birks private
Definition at line 371 of file G4EmParameters.hh.
Referenced by BirksActive(), Initialise(), SetBirksActive(), and StreamInfo().
bremsTh
G4double G4EmParameters::bremsTh private
Definition at line 389 of file G4EmParameters.hh.
Referenced by BremsstrahlungTh(), Initialise(), SetBremsstrahlungTh(), and StreamInfo().
buildCSDARange
G4bool G4EmParameters::buildCSDARange private
Definition at line 353 of file G4EmParameters.hh.
Referenced by BuildCSDARange(), Initialise(), SetBuildCSDARange(), and StreamInfo().
cutAsFinalRange
G4bool G4EmParameters::cutAsFinalRange private
Definition at line 356 of file G4EmParameters.hh.
Referenced by Initialise(), SetUseCutAsFinalRange(), StreamInfo(), and UseCutAsFinalRange().
deexIgnoreCut
G4bool G4EmParameters::deexIgnoreCut private
Definition at line 363 of file G4EmParameters.hh.
Referenced by DeexcitationIgnoreCut(), Initialise(), SetDeexcitationIgnoreCut(), and StreamInfo().
directionalSplitting
G4bool G4EmParameters::directionalSplitting private
Definition at line 379 of file G4EmParameters.hh.
Referenced by GetDirectionalSplitting(), Initialise(), and SetDirectionalSplitting().
directionalSplittingRadius
G4double G4EmParameters::directionalSplittingRadius private
Definition at line 403 of file G4EmParameters.hh.
Referenced by GetDirectionalSplittingRadius(), Initialise(), and SetDirectionalSplittingRadius().
directionalSplittingTarget
G4ThreeVector G4EmParameters::directionalSplittingTarget private
Definition at line 411 of file G4EmParameters.hh.
Referenced by GetDirectionalSplittingTarget(), Initialise(), and SetDirectionalSplittingTarget().
dnaElectronSolvation
G4DNAModelSubType G4EmParameters::dnaElectronSolvation private
Definition at line 416 of file G4EmParameters.hh.
Referenced by DNAeSolvationSubType(), Initialise(), SetDNAeSolvationSubType(), and StreamInfo().
dnaFast
G4bool G4EmParameters::dnaFast private
Definition at line 373 of file G4EmParameters.hh.
Referenced by DNAFast(), Initialise(), SetDNAFast(), and StreamInfo().
dnaMsc
G4bool G4EmParameters::dnaMsc private
Definition at line 375 of file G4EmParameters.hh.
Referenced by DNAElectronMsc(), Initialise(), SetDNAElectronMsc(), and StreamInfo().
dnaStationary
G4bool G4EmParameters::dnaStationary private
Definition at line 374 of file G4EmParameters.hh.
Referenced by DNAStationary(), Initialise(), SetDNAStationary(), and StreamInfo().
dRoverRange
G4double G4EmParameters::dRoverRange private
Definition at line 398 of file G4EmParameters.hh.
Referenced by DefineRegParamForLoss(), Initialise(), SetStepFunction(), and StreamInfo().
dRoverRangeMuHad
G4double G4EmParameters::dRoverRangeMuHad private
Definition at line 400 of file G4EmParameters.hh.
Referenced by DefineRegParamForLoss(), Initialise(), SetStepFunctionMuHad(), and StreamInfo().
emSaturation
G4EmSaturation* G4EmParameters::emSaturation private
Definition at line 350 of file G4EmParameters.hh.
Referenced by G4EmParameters(), GetEmSaturation(), SetBirksActive(), SetEmSaturation(), and ~G4EmParameters().
enableSamplingTable
G4bool G4EmParameters::enableSamplingTable private
Definition at line 377 of file G4EmParameters.hh.
Referenced by EnableSamplingTable(), Initialise(), SetEnableSamplingTable(), and StreamInfo().
energyLimit
G4double G4EmParameters::energyLimit private
Definition at line 393 of file G4EmParameters.hh.
Referenced by Initialise(), MscEnergyLimit(), SetMscEnergyLimit(), and StreamInfo().
factorForAngleLimit
G4double G4EmParameters::factorForAngleLimit private
Definition at line 391 of file G4EmParameters.hh.
Referenced by FactorForAngleLimit(), Initialise(), SetFactorForAngleLimit(), and StreamInfo().
factorScreen
G4double G4EmParameters::factorScreen private
Definition at line 402 of file G4EmParameters.hh.
Referenced by Initialise(), ScreeningFactor(), SetScreeningFactor(), and StreamInfo().
fICRU90
G4bool G4EmParameters::fICRU90 private
Definition at line 372 of file G4EmParameters.hh.
Referenced by Initialise(), SetUseICRU90Data(), StreamInfo(), and UseICRU90Data().
finalRange
G4double G4EmParameters::finalRange private
Definition at line 399 of file G4EmParameters.hh.
Referenced by DefineRegParamForLoss(), Initialise(), SetStepFunction(), and StreamInfo().
finalRangeMuHad
G4double G4EmParameters::finalRangeMuHad private
Definition at line 401 of file G4EmParameters.hh.
Referenced by DefineRegParamForLoss(), Initialise(), SetStepFunctionMuHad(), and StreamInfo().
flagLPM
G4bool G4EmParameters::flagLPM private
Definition at line 354 of file G4EmParameters.hh.
Referenced by Initialise(), LPM(), SetLPM(), and StreamInfo().
fluo
G4bool G4EmParameters::fluo private
Definition at line 358 of file G4EmParameters.hh.
Referenced by Fluo(), Initialise(), SetAugerCascade(), SetDeexActiveRegion(), SetFluo(), SetPixe(), and StreamInfo().
fStateManager
G4StateManager* G4EmParameters::fStateManager private
Definition at line 348 of file G4EmParameters.hh.
Referenced by G4EmParameters(), and IsLocked().
gener
G4bool G4EmParameters::gener private
Definition at line 376 of file G4EmParameters.hh.
Referenced by ActivateForcedInteraction(), GeneralProcessActive(), Initialise(), SetGeneralProcessActive(), SetSubCutoff(), and StreamInfo().
geomFactor
G4double G4EmParameters::geomFactor private
Definition at line 396 of file G4EmParameters.hh.
Referenced by Initialise(), MscGeomFactor(), SetMscGeomFactor(), and StreamInfo().
integral
G4bool G4EmParameters::integral private
Definition at line 370 of file G4EmParameters.hh.
Referenced by Initialise(), Integral(), SetIntegral(), and StreamInfo().
lambdaFactor
G4double G4EmParameters::lambdaFactor private
Definition at line 390 of file G4EmParameters.hh.
Referenced by Initialise(), LambdaFactor(), SetLambdaFactor(), and StreamInfo().
latDisplacementBeyondSafety
G4bool G4EmParameters::latDisplacementBeyondSafety private
Definition at line 367 of file G4EmParameters.hh.
Referenced by Initialise(), LatDisplacementBeyondSafety(), SetLatDisplacementBeyondSafety(), and StreamInfo().
lateralDisplacement
G4bool G4EmParameters::lateralDisplacement private
Definition at line 364 of file G4EmParameters.hh.
Referenced by Initialise(), LateralDisplacement(), SetLateralDisplacement(), and StreamInfo().
lateralDisplacementAlg96
G4bool G4EmParameters::lateralDisplacementAlg96 private
Definition at line 365 of file G4EmParameters.hh.
Referenced by Initialise(), LateralDisplacementAlg96(), SetLateralDisplacementAlg96(), and StreamInfo().
linLossLimit
G4double G4EmParameters::linLossLimit private
Definition at line 388 of file G4EmParameters.hh.
Referenced by Initialise(), LinearLossLimit(), SetLinearLossLimit(), and StreamInfo().
lossFluctuation
G4bool G4EmParameters::lossFluctuation private
Definition at line 352 of file G4EmParameters.hh.
Referenced by Initialise(), LossFluctuation(), SetLossFluctuations(), and StreamInfo().
lowestElectronEnergy
G4double G4EmParameters::lowestElectronEnergy private
Definition at line 385 of file G4EmParameters.hh.
Referenced by Initialise(), LowestElectronEnergy(), SetLowestElectronEnergy(), and StreamInfo().
lowestMuHadEnergy
G4double G4EmParameters::lowestMuHadEnergy private
Definition at line 386 of file G4EmParameters.hh.
Referenced by Initialise(), LowestMuHadEnergy(), SetLowestMuHadEnergy(), and StreamInfo().
lowestTripletEnergy
G4double G4EmParameters::lowestTripletEnergy private
Definition at line 387 of file G4EmParameters.hh.
Referenced by Initialise(), LowestTripletEnergy(), SetLowestTripletEnergy(), and StreamInfo().
m_auger
std::vector<G4bool> G4EmParameters::m_auger private
Definition at line 438 of file G4EmParameters.hh.
Referenced by DefineRegParamForDeex(), and SetDeexActiveRegion().
m_elimBiasedSec
std::vector<G4double> G4EmParameters::m_elimBiasedSec private
Definition at line 453 of file G4EmParameters.hh.
Referenced by ActivateSecondaryBiasing(), DefineRegParamForEM(), and DefineRegParamForLoss().
m_factBiasedSec
std::vector<G4double> G4EmParameters::m_factBiasedSec private
Definition at line 452 of file G4EmParameters.hh.
Referenced by ActivateSecondaryBiasing(), DefineRegParamForEM(), and DefineRegParamForLoss().
m_factBiasedXS
std::vector<G4double> G4EmParameters::m_factBiasedXS private
Definition at line 442 of file G4EmParameters.hh.
Referenced by DefineRegParamForEM(), DefineRegParamForLoss(), and SetProcessBiasingFactor().
m_fluo
std::vector<G4bool> G4EmParameters::m_fluo private
Definition at line 437 of file G4EmParameters.hh.
Referenced by DefineRegParamForDeex(), and SetDeexActiveRegion().
m_lengthForced
std::vector<G4double> G4EmParameters::m_lengthForced private
Definition at line 447 of file G4EmParameters.hh.
Referenced by ActivateForcedInteraction(), DefineRegParamForEM(), DefineRegParamForLoss(), and SetGeneralProcessActive().
m_particlesPAI
std::vector<G4String> G4EmParameters::m_particlesPAI private
Definition at line 421 of file G4EmParameters.hh.
Referenced by AddPAIModel(), and ParticlesPAI().
m_pixe
std::vector<G4bool> G4EmParameters::m_pixe private
Definition at line 439 of file G4EmParameters.hh.
Referenced by DefineRegParamForDeex(), and SetDeexActiveRegion().
m_procBiasedSec
std::vector<G4String> G4EmParameters::m_procBiasedSec private
Definition at line 450 of file G4EmParameters.hh.
Referenced by ActivateSecondaryBiasing(), DefineRegParamForEM(), and DefineRegParamForLoss().
m_procBiasedXS
std::vector<G4String> G4EmParameters::m_procBiasedXS private
Definition at line 441 of file G4EmParameters.hh.
Referenced by DefineRegParamForEM(), DefineRegParamForLoss(), and SetProcessBiasingFactor().
m_procForced
std::vector<G4String> G4EmParameters::m_procForced private
Definition at line 445 of file G4EmParameters.hh.
Referenced by ActivateForcedInteraction(), DefineRegParamForEM(), DefineRegParamForLoss(), and SetGeneralProcessActive().
m_regnamesBiasedSec
std::vector<G4String> G4EmParameters::m_regnamesBiasedSec private
Definition at line 451 of file G4EmParameters.hh.
Referenced by ActivateSecondaryBiasing(), DefineRegParamForEM(), and DefineRegParamForLoss().
m_regnamesDeex
std::vector<G4String> G4EmParameters::m_regnamesDeex private
Definition at line 436 of file G4EmParameters.hh.
Referenced by DefineRegParamForDeex(), and SetDeexActiveRegion().
m_regnamesDNA
std::vector<G4String> G4EmParameters::m_regnamesDNA private
Definition at line 427 of file G4EmParameters.hh.
Referenced by AddDNA(), and RegionsDNA().
m_regnamesForced
std::vector<G4String> G4EmParameters::m_regnamesForced private
Definition at line 446 of file G4EmParameters.hh.
Referenced by ActivateForcedInteraction(), DefineRegParamForEM(), DefineRegParamForLoss(), and SetGeneralProcessActive().
m_regnamesME
std::vector<G4String> G4EmParameters::m_regnamesME private
Definition at line 425 of file G4EmParameters.hh.
Referenced by AddMicroElec(), and RegionsMicroElec().
m_regnamesPAI
std::vector<G4String> G4EmParameters::m_regnamesPAI private
Definition at line 422 of file G4EmParameters.hh.
Referenced by AddPAIModel(), and RegionsPAI().
m_regnamesPhys
std::vector<G4String> G4EmParameters::m_regnamesPhys private
Definition at line 430 of file G4EmParameters.hh.
Referenced by AddPhysics(), RegionsMsc(), and RegionsPhysics().
m_regnamesSubCut
std::vector<G4String> G4EmParameters::m_regnamesSubCut private
Definition at line 433 of file G4EmParameters.hh.
Referenced by DefineRegParamForLoss(), SetGeneralProcessActive(), and SetSubCutoff().
m_subCuts
std::vector<G4bool> G4EmParameters::m_subCuts private
Definition at line 434 of file G4EmParameters.hh.
Referenced by DefineRegParamForLoss(), SetGeneralProcessActive(), and SetSubCutoff().
m_typesDNA
std::vector<G4String> G4EmParameters::m_typesDNA private
Definition at line 428 of file G4EmParameters.hh.
Referenced by AddDNA(), and TypesDNA().
m_typesPAI
std::vector<G4String> G4EmParameters::m_typesPAI private
Definition at line 423 of file G4EmParameters.hh.
Referenced by AddPAIModel(), and TypesPAI().
m_typesPhys
std::vector<G4String> G4EmParameters::m_typesPhys private
Definition at line 431 of file G4EmParameters.hh.
Referenced by AddPhysics(), TypesMsc(), and TypesPhysics().
m_weightBiasedXS
std::vector<G4bool> G4EmParameters::m_weightBiasedXS private
Definition at line 443 of file G4EmParameters.hh.
Referenced by DefineRegParamForEM(), DefineRegParamForLoss(), and SetProcessBiasingFactor().
m_weightForced
std::vector<G4bool> G4EmParameters::m_weightForced private
Definition at line 448 of file G4EmParameters.hh.
Referenced by ActivateForcedInteraction(), DefineRegParamForEM(), DefineRegParamForLoss(), and SetGeneralProcessActive().
maxKinEnergy
G4double G4EmParameters::maxKinEnergy private
Definition at line 383 of file G4EmParameters.hh.
Referenced by Initialise(), MaxKinEnergy(), SetMaxEnergy(), SetMinEnergy(), SetNumberOfBins(), SetNumberOfBinsPerDecade(), and StreamInfo().
maxKinEnergyCSDA
G4double G4EmParameters::maxKinEnergyCSDA private
Definition at line 384 of file G4EmParameters.hh.
Referenced by Initialise(), MaxEnergyForCSDARange(), SetMaxEnergyForCSDARange(), and StreamInfo().
minKinEnergy
G4double G4EmParameters::minKinEnergy private
Definition at line 382 of file G4EmParameters.hh.
Referenced by Initialise(), MinKinEnergy(), SetMaxEnergy(), SetMaxEnergyForCSDARange(), SetMinEnergy(), SetNumberOfBins(), SetNumberOfBinsPerDecade(), and StreamInfo().
minSubRange
G4double G4EmParameters::minSubRange private
Definition at line 381 of file G4EmParameters.hh.
Referenced by Initialise(), MinSubRange(), SetMinSubRange(), and StreamInfo().
mscStepLimit
G4MscStepLimitType G4EmParameters::mscStepLimit private
Definition at line 413 of file G4EmParameters.hh.
Referenced by Initialise(), MscStepLimitType(), SetMscStepLimitType(), and StreamInfo().
mscStepLimitMuHad
G4MscStepLimitType G4EmParameters::mscStepLimitMuHad private
Definition at line 414 of file G4EmParameters.hh.
Referenced by Initialise(), MscMuHadStepLimitType(), SetMscMuHadStepLimitType(), and StreamInfo().
muhadLateralDisplacement
G4bool G4EmParameters::muhadLateralDisplacement private
Definition at line 366 of file G4EmParameters.hh.
Referenced by Initialise(), MuHadLateralDisplacement(), SetMuHadLateralDisplacement(), and StreamInfo().
nameElectronPIXE
G4String G4EmParameters::nameElectronPIXE private
Definition at line 419 of file G4EmParameters.hh.
Referenced by Initialise(), PIXEElectronCrossSectionModel(), SetPIXEElectronCrossSectionModel(), and StreamInfo().
namePIXE
G4String G4EmParameters::namePIXE private
Definition at line 418 of file G4EmParameters.hh.
Referenced by Initialise(), PIXECrossSectionModel(), SetPIXECrossSectionModel(), and StreamInfo().
nbins
G4int G4EmParameters::nbins private
Definition at line 405 of file G4EmParameters.hh.
Referenced by Initialise(), NumberOfBins(), SetMaxEnergy(), SetMinEnergy(), SetNumberOfBins(), SetNumberOfBinsPerDecade(), and StreamInfo().
nbinsPerDecade
G4int G4EmParameters::nbinsPerDecade private
Definition at line 406 of file G4EmParameters.hh.
Referenced by Initialise(), NumberOfBinsPerDecade(), SetMaxEnergy(), SetMinEnergy(), SetNumberOfBins(), SetNumberOfBinsPerDecade(), and StreamInfo().
nucFormfactor
G4NuclearFormfactorType G4EmParameters::nucFormfactor private
Definition at line 415 of file G4EmParameters.hh.
Referenced by Initialise(), NuclearFormfactorType(), SetNuclearFormfactorType(), and StreamInfo().
onIsolated
G4bool G4EmParameters::onIsolated private
Definition at line 378 of file G4EmParameters.hh.
Referenced by Initialise(), OnIsolated(), SetOnIsolated(), and StreamInfo().
pixe
G4bool G4EmParameters::pixe private
Definition at line 362 of file G4EmParameters.hh.
Referenced by Initialise(), Pixe(), SetPixe(), and StreamInfo().
rangeFactor
G4double G4EmParameters::rangeFactor private
Definition at line 394 of file G4EmParameters.hh.
Referenced by Initialise(), MscRangeFactor(), SetMscRangeFactor(), and StreamInfo().
rangeFactorMuHad
G4double G4EmParameters::rangeFactorMuHad private
Definition at line 395 of file G4EmParameters.hh.
Referenced by Initialise(), MscMuHadRangeFactor(), SetMscMuHadRangeFactor(), and StreamInfo().
skin
G4double G4EmParameters::skin private
Definition at line 397 of file G4EmParameters.hh.
Referenced by Initialise(), MscSkin(), SetMscSkin(), and StreamInfo().
spline
G4bool G4EmParameters::spline private
Definition at line 355 of file G4EmParameters.hh.
Referenced by Initialise(), SetSpline(), Spline(), and StreamInfo().
theInstance
G4EmParameters * G4EmParameters::theInstance = nullptr static private
Definition at line 344 of file G4EmParameters.hh.
Referenced by Instance().
theMessenger
G4EmParametersMessenger* G4EmParameters::theMessenger private
Definition at line 346 of file G4EmParameters.hh.
Referenced by G4EmParameters(), and ~G4EmParameters().
thetaLimit
G4double G4EmParameters::thetaLimit private
Definition at line 392 of file G4EmParameters.hh.
Referenced by Initialise(), MscThetaLimit(), SetMscThetaLimit(), and StreamInfo().
tripletConv
G4int G4EmParameters::tripletConv private
Definition at line 409 of file G4EmParameters.hh.
Referenced by GetConversionType(), Initialise(), SetConversionType(), and StreamInfo().
useAngGeneratorForIonisation
G4bool G4EmParameters::useAngGeneratorForIonisation private
Definition at line 368 of file G4EmParameters.hh.
Referenced by ActivateAngularGeneratorForIonisation(), Initialise(), StreamInfo(), and UseAngularGeneratorForIonisation().
useMottCorrection
G4bool G4EmParameters::useMottCorrection private
Definition at line 369 of file G4EmParameters.hh.
Referenced by Initialise(), SetUseMottCorrection(), StreamInfo(), and UseMottCorrection().
verbose
G4int G4EmParameters::verbose private
Definition at line 407 of file G4EmParameters.hh.
Referenced by Initialise(), SetVerbose(), StreamInfo(), and Verbose().
workerVerbose
G4int G4EmParameters::workerVerbose private
Definition at line 408 of file G4EmParameters.hh.
Referenced by Initialise(), SetVerbose(), SetWorkerVerbose(), StreamInfo(), and WorkerVerbose().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/utils/include/G4EmParameters.hh
source/processes/electromagnetic/utils/src/G4EmParameters.cc