Geant4: G4GeomTestVolume Class Reference
G4GeomTestVolume Class Reference
#include <G4GeomTestVolume.hh>
Public Member Functions
G4GeomTestVolume (G4VPhysicalVolume *theTarget, G4double theTolerance=0.0, G4int numberOfPoints=10000, G4bool theVerbosity=true)
~G4GeomTestVolume ()
G4double GetTolerance () const
void SetTolerance (G4double tolerance)
G4int GetResolution () const
void SetResolution (G4int points)
G4bool GetVerbosity () const
void SetVerbosity (G4bool verbosity)
G4int GetErrorsThreshold () const
void SetErrorsThreshold (G4int max)
void TestRecursiveOverlap (G4int sLevel=0, G4int depth=-1)
Private Attributes
G4VPhysicalVolume * target
G4double tolerance
G4int resolution
G4int maxErr
G4bool verbosity
Detailed Description
Definition at line 48 of file G4GeomTestVolume.hh.
Constructor & Destructor Documentation
G4GeomTestVolume()
G4GeomTestVolume::G4GeomTestVolume (G4VPhysicalVolume * theTarget, G4double theTolerance = 0.0, G4int numberOfPoints = 10000, G4bool theVerbosity = true)
Definition at line 48 of file G4GeomTestVolume.cc.
~G4GeomTestVolume()
G4GeomTestVolume::~G4GeomTestVolume ()
Definition at line 59 of file G4GeomTestVolume.cc.
Member Function Documentation
GetErrorsThreshold()
G4int G4GeomTestVolume::GetErrorsThreshold () const
Definition at line 112 of file G4GeomTestVolume.cc.
GetResolution()
G4int G4GeomTestVolume::GetResolution () const
Definition at line 80 of file G4GeomTestVolume.cc.
GetTolerance()
G4double G4GeomTestVolume::GetTolerance () const
Definition at line 64 of file G4GeomTestVolume.cc.
GetVerbosity()
G4bool G4GeomTestVolume::GetVerbosity () const
Definition at line 96 of file G4GeomTestVolume.cc.
SetErrorsThreshold()
void G4GeomTestVolume::SetErrorsThreshold (G4int max)
Definition at line 120 of file G4GeomTestVolume.cc.
Referenced by G4GeometryMessenger::SetNewValue(), and TestRecursiveOverlap().
SetResolution()
void G4GeomTestVolume::SetResolution (G4int points)
Definition at line 88 of file G4GeomTestVolume.cc.
Referenced by G4GeometryMessenger::SetNewValue().
SetTolerance()
void G4GeomTestVolume::SetTolerance (G4double tolerance)
Definition at line 72 of file G4GeomTestVolume.cc.
Referenced by G4GeometryMessenger::SetNewValue().
SetVerbosity()
void G4GeomTestVolume::SetVerbosity (G4bool verbosity)
Definition at line 104 of file G4GeomTestVolume.cc.
Referenced by G4GeometryMessenger::SetNewValue().
TestRecursiveOverlap()
void G4GeomTestVolume::TestRecursiveOverlap (G4int sLevel = 0, G4int depth = -1)
Definition at line 128 of file G4GeomTestVolume.cc.
Referenced by G4GeometryMessenger::RecursiveOverlapTest(), and TestRecursiveOverlap().
Field Documentation
maxErr
G4int G4GeomTestVolume::maxErr private
Definition at line 84 of file G4GeomTestVolume.hh.
Referenced by GetErrorsThreshold(), SetErrorsThreshold(), and TestRecursiveOverlap().
resolution
G4int G4GeomTestVolume::resolution private
Definition at line 83 of file G4GeomTestVolume.hh.
Referenced by GetResolution(), SetResolution(), and TestRecursiveOverlap().
target
G4VPhysicalVolume* G4GeomTestVolume::target private
Definition at line 81 of file G4GeomTestVolume.hh.
Referenced by TestRecursiveOverlap().
tolerance
G4double G4GeomTestVolume::tolerance private
Definition at line 82 of file G4GeomTestVolume.hh.
Referenced by GetTolerance(), SetTolerance(), and TestRecursiveOverlap().
verbosity
G4bool G4GeomTestVolume::verbosity private
Definition at line 85 of file G4GeomTestVolume.hh.
Referenced by GetVerbosity(), SetVerbosity(), and TestRecursiveOverlap().
The documentation for this class was generated from the following files:
source/geometry/navigation/include/G4GeomTestVolume.hh
source/geometry/navigation/src/G4GeomTestVolume.cc