Geant4: CCalHit Class Reference
CCalHit Class Reference
#include <CCalHit.hh>
Public Member Functions
CCalHit ()
~CCalHit ()
CCalHit (const CCalHit &right)
const CCalHit & operator= (const CCalHit &right)
G4bool operator== (const CCalHit &)
void print ()
CLHEP::Hep3Vector getEntry () const
void setEntry (CLHEP::Hep3Vector xyz)
double getIncidentEnergy () const
void setIncidentEnergy (double e)
int getTrackID () const
void setTrackID (int i)
unsigned int getUnitID () const
void setUnitID (unsigned int i)
double getTimeSlice () const
void setTimeSlice (double d)
int getTimeSliceID () const
double getEnergyDeposit () const
void setEnergyDeposit (const double e)
void addEnergyDeposit (const CCalHit &aHit)
void addEnergyDeposit (const double e)
Private Attributes
CLHEP::Hep3Vector entry
double theIncidentEnergy
int theTrackID
unsigned int theUnitID
double theTimeSlice
double theEnergyDeposit
Friends
std::ostream & operator<< (std::ostream &, const CCalHit &)
Detailed Description
Definition at line 52 of file CCalHit.hh.
Constructor & Destructor Documentation
CCalHit() [1/2]
CCalHit::CCalHit ()
Definition at line 35 of file CCalHit.cc.
~CCalHit()
CCalHit::~CCalHit ()
Definition at line 41 of file CCalHit.cc.
CCalHit() [2/2]
CCalHit::CCalHit (const CCalHit & right)
Definition at line 44 of file CCalHit.cc.
Member Function Documentation
addEnergyDeposit() [1/2]
void CCalHit::addEnergyDeposit (const CCalHit & aHit)
Definition at line 90 of file CCalHit.cc.
Referenced by CCalG4Hit::addEnergyDeposit().
addEnergyDeposit() [2/2]
void CCalHit::addEnergyDeposit (const double e)
Definition at line 94 of file CCalHit.cc.
getEnergyDeposit()
double CCalHit::getEnergyDeposit () const
Definition at line 86 of file CCalHit.cc.
Referenced by addEnergyDeposit(), CCalEventAction::EndOfEventAction(), and operator<<().
getEntry()
CLHEP::Hep3Vector CCalHit::getEntry () const
Definition at line 65 of file CCalHit.cc.
Referenced by operator<<().
getIncidentEnergy()
double CCalHit::getIncidentEnergy () const
Definition at line 68 of file CCalHit.cc.
Referenced by operator<<().
getTimeSlice()
double CCalHit::getTimeSlice () const
Definition at line 77 of file CCalHit.cc.
Referenced by CCalEventAction::EndOfEventAction().
getTimeSliceID()
int CCalHit::getTimeSliceID () const
Definition at line 79 of file CCalHit.cc.
Referenced by CCaloSD::hitExists(), and operator<<().
getTrackID()
int CCalHit::getTrackID () const
Definition at line 71 of file CCalHit.cc.
Referenced by CCaloSD::hitExists(), and operator<<().
getUnitID()
unsigned int CCalHit::getUnitID () const
Definition at line 74 of file CCalHit.cc.
Referenced by CCalEventAction::EndOfEventAction(), CCaloSD::hitExists(), and operator<<().
operator=()
const CCalHit & CCalHit::operator= (const CCalHit & right)
Definition at line 54 of file CCalHit.cc.
Referenced by CCalG4Hit::operator=().
operator==()
G4bool CCalHit::operator== (const CCalHit &) inline
Definition at line 62 of file CCalHit.hh.
print()
void CCalHit::print ()
Definition at line 99 of file CCalHit.cc.
setEnergyDeposit()
void CCalHit::setEnergyDeposit (const double e)
Definition at line 82 of file CCalHit.cc.
setEntry()
void CCalHit::setEntry (CLHEP::Hep3Vector xyz)
Definition at line 66 of file CCalHit.cc.
Referenced by CCaloSD::createNewHit().
setIncidentEnergy()
void CCalHit::setIncidentEnergy (double e)
Definition at line 69 of file CCalHit.cc.
Referenced by CCaloSD::createNewHit().
setTimeSlice()
void CCalHit::setTimeSlice (double d)
Definition at line 78 of file CCalHit.cc.
Referenced by CCaloSD::createNewHit().
setTrackID()
void CCalHit::setTrackID (int i)
Definition at line 72 of file CCalHit.cc.
Referenced by CCaloSD::createNewHit().
setUnitID()
void CCalHit::setUnitID (unsigned int i)
Definition at line 75 of file CCalHit.cc.
Referenced by CCaloSD::createNewHit().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CCalHit & hit) friend
Definition at line 104 of file CCalHit.cc.
Field Documentation
entry
CLHEP::Hep3Vector CCalHit::entry private
Definition at line 91 of file CCalHit.hh.
Referenced by getEntry(), operator=(), and setEntry().
theEnergyDeposit
double CCalHit::theEnergyDeposit private
Definition at line 96 of file CCalHit.hh.
Referenced by addEnergyDeposit(), getEnergyDeposit(), operator=(), and setEnergyDeposit().
theIncidentEnergy
double CCalHit::theIncidentEnergy private
Definition at line 92 of file CCalHit.hh.
Referenced by getIncidentEnergy(), operator=(), and setIncidentEnergy().
theTimeSlice
double CCalHit::theTimeSlice private
Definition at line 95 of file CCalHit.hh.
Referenced by getTimeSlice(), getTimeSliceID(), operator=(), and setTimeSlice().
theTrackID
int CCalHit::theTrackID private
Definition at line 93 of file CCalHit.hh.
Referenced by getTrackID(), operator=(), and setTrackID().
theUnitID
unsigned int CCalHit::theUnitID private
Definition at line 94 of file CCalHit.hh.
Referenced by getUnitID(), operator=(), and setUnitID().
The documentation for this class was generated from the following files:
examples/advanced/composite_calorimeter/include/CCalHit.hh
examples/advanced/composite_calorimeter/src/CCalHit.cc