Geant4: G4Scintillation Class Reference
G4Scintillation Class Reference
#include <G4Scintillation.hh>
Public Member Functions
G4Scintillation (const G4String &processName="Scintillation", G4ProcessType type=fElectromagnetic)
~G4Scintillation ()
G4bool IsApplicable (const G4ParticleDefinition &aParticleType) override
void BuildPhysicsTable (const G4ParticleDefinition &aParticleType) override
G4double GetMeanFreePath (const G4Track &aTrack, G4double, G4ForceCondition *) override
G4double GetMeanLifeTime (const G4Track &aTrack, G4ForceCondition *) override
G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep) override
G4VParticleChange * AtRestDoIt (const G4Track &aTrack, const G4Step &aStep) override
G4double GetScintillationYieldByParticleType (const G4Track &aTrack, const G4Step &aStep)
void SetTrackSecondariesFirst (const G4bool state)
G4bool GetTrackSecondariesFirst () const
void SetFiniteRiseTime (const G4bool state)
G4bool GetFiniteRiseTime () const
void SetScintillationYieldFactor (const G4double yieldfactor)
G4double GetScintillationYieldFactor () const
void SetScintillationExcitationRatio (const G4double ratio)
G4double GetScintillationExcitationRatio () const
G4PhysicsTable * GetFastIntegralTable () const
G4PhysicsTable * GetSlowIntegralTable () const
void AddSaturation (G4EmSaturation *sat)
void RemoveSaturation ()
G4EmSaturation * GetSaturation () const
void SetScintillationByParticleType (const G4bool)
G4bool GetScintillationByParticleType () const
void SetScintillationTrackInfo (const G4bool trackType)
G4bool GetScintillationTrackInfo () const
void SetStackPhotons (const G4bool)
G4bool GetStackPhotons () const
G4int GetNumPhotons () const
void DumpPhysicsTable () const
Public Member Functions inherited from G4VRestDiscreteProcess
G4VRestDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VRestDiscreteProcess (G4VRestDiscreteProcess &)
virtual ~G4VRestDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
void BuildThePhysicsTable ()
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes
G4PhysicsTable * fFastIntegralTable
G4PhysicsTable * fSlowIntegralTable
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Private Member Functions
G4Scintillation (const G4Scintillation &right)=delete
G4Scintillation & operator= (const G4Scintillation &right)=delete
G4double single_exp (G4double t, G4double tau2)
G4double bi_exp (G4double t, G4double tau1, G4double tau2)
G4double sample_time (G4double tau1, G4double tau2)
Private Attributes
G4bool fTrackSecondariesFirst
G4bool fFiniteRiseTime
G4double fYieldFactor
G4double fExcitationRatio
G4bool fScintillationByParticleType
G4bool fScintillationTrackInfo
G4bool fStackingFlag
G4int fNumPhotons
G4EmSaturation * fEmSaturation
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Detailed Description
Definition at line 87 of file G4Scintillation.hh.
Constructor & Destructor Documentation
G4Scintillation() [1/2]
G4Scintillation::G4Scintillation (const G4String & processName = "Scintillation", G4ProcessType type = fElectromagnetic) explicit
Definition at line 109 of file G4Scintillation.cc.
~G4Scintillation()
G4Scintillation::~G4Scintillation ()
Definition at line 141 of file G4Scintillation.cc.
G4Scintillation() [2/2]
G4Scintillation::G4Scintillation (const G4Scintillation & right) private delete
Member Function Documentation
AddSaturation()
void G4Scintillation::AddSaturation (G4EmSaturation * sat) inline
Definition at line 339 of file G4Scintillation.hh.
Referenced by OpNovicePhysicsList::ConstructOp(), WLSOpticalPhysics::ConstructProcess(), and G4OpticalPhysics::ConstructProcess().
AtRestDoIt()
G4VParticleChange * G4Scintillation::AtRestDoIt (const G4Track & aTrack, const G4Step & aStep) override virtual
Reimplemented from G4VRestDiscreteProcess.
Definition at line 185 of file G4Scintillation.cc.
bi_exp()
G4double G4Scintillation::bi_exp (G4double t, G4double tau1, G4double tau2) inline private
Definition at line 400 of file G4Scintillation.hh.
Referenced by sample_time().
BuildPhysicsTable()
void G4Scintillation::BuildPhysicsTable (const G4ParticleDefinition & aParticleType) override virtual
Reimplemented from G4VProcess.
Definition at line 165 of file G4Scintillation.cc.
BuildThePhysicsTable()
void G4Scintillation::BuildThePhysicsTable () protected
Definition at line 508 of file G4Scintillation.cc.
Referenced by BuildPhysicsTable().
DumpPhysicsTable()
void G4Scintillation::DumpPhysicsTable () const
Definition at line 866 of file G4Scintillation.cc.
GetFastIntegralTable()
G4PhysicsTable * G4Scintillation::GetFastIntegralTable () const inline
Definition at line 333 of file G4Scintillation.hh.
GetFiniteRiseTime()
G4bool G4Scintillation::GetFiniteRiseTime () const inline
Definition at line 297 of file G4Scintillation.hh.
GetMeanFreePath()
G4double G4Scintillation::GetMeanFreePath (const G4Track & aTrack, G4double , G4ForceCondition * condition) override virtual
Implements G4VRestDiscreteProcess.
Definition at line 675 of file G4Scintillation.cc.
GetMeanLifeTime()
G4double G4Scintillation::GetMeanLifeTime (const G4Track & aTrack, G4ForceCondition * condition) override virtual
Implements G4VRestDiscreteProcess.
Definition at line 689 of file G4Scintillation.cc.
GetNumPhotons()
G4int G4Scintillation::GetNumPhotons () const inline
Definition at line 387 of file G4Scintillation.hh.
GetSaturation()
G4EmSaturation * G4Scintillation::GetSaturation () const inline
Definition at line 351 of file G4Scintillation.hh.
GetScintillationByParticleType()
G4bool G4Scintillation::GetScintillationByParticleType () const inline
Definition at line 357 of file G4Scintillation.hh.
GetScintillationExcitationRatio()
G4double G4Scintillation::GetScintillationExcitationRatio () const inline
Definition at line 321 of file G4Scintillation.hh.
GetScintillationTrackInfo()
G4bool G4Scintillation::GetScintillationTrackInfo () const inline
Definition at line 369 of file G4Scintillation.hh.
GetScintillationYieldByParticleType()
G4double G4Scintillation::GetScintillationYieldByParticleType (const G4Track & aTrack, const G4Step & aStep)
Definition at line 721 of file G4Scintillation.cc.
Referenced by PostStepDoIt().
GetScintillationYieldFactor()
G4double G4Scintillation::GetScintillationYieldFactor () const inline
Definition at line 309 of file G4Scintillation.hh.
GetSlowIntegralTable()
G4PhysicsTable * G4Scintillation::GetSlowIntegralTable () const inline
Definition at line 327 of file G4Scintillation.hh.
GetStackPhotons()
G4bool G4Scintillation::GetStackPhotons () const inline
Definition at line 381 of file G4Scintillation.hh.
GetTrackSecondariesFirst()
G4bool G4Scintillation::GetTrackSecondariesFirst () const inline
Definition at line 285 of file G4Scintillation.hh.
IsApplicable()
G4bool G4Scintillation::IsApplicable (const G4ParticleDefinition & aParticleType) override virtual
Reimplemented from G4VProcess.
Definition at line 157 of file G4Scintillation.cc.
Referenced by OpNovicePhysicsList::ConstructOp(), DMXPhysicsList::ConstructOp(), WLSOpticalPhysics::ConstructProcess(), and G4OpticalPhysics::ConstructProcess().
operator=()
G4Scintillation& G4Scintillation::operator= (const G4Scintillation & right) private delete
PostStepDoIt()
G4VParticleChange * G4Scintillation::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) override virtual
Reimplemented from G4VRestDiscreteProcess.
Definition at line 198 of file G4Scintillation.cc.
Referenced by AtRestDoIt().
RemoveSaturation()
void G4Scintillation::RemoveSaturation () inline
Definition at line 345 of file G4Scintillation.hh.
Referenced by SetScintillationByParticleType().
sample_time()
G4double G4Scintillation::sample_time (G4double tau1, G4double tau2) private
Definition at line 698 of file G4Scintillation.cc.
Referenced by PostStepDoIt().
SetFiniteRiseTime()
void G4Scintillation::SetFiniteRiseTime (const G4bool state) inline
Definition at line 291 of file G4Scintillation.hh.
Referenced by G4OpticalPhysics::ConstructProcess(), and G4OpticalPhysics::SetFiniteRiseTime().
SetScintillationByParticleType()
void G4Scintillation::SetScintillationByParticleType (const G4bool scintType)
Definition at line 661 of file G4Scintillation.cc.
Referenced by G4OpticalPhysics::ConstructProcess().
SetScintillationExcitationRatio()
void G4Scintillation::SetScintillationExcitationRatio (const G4double ratio) inline
Definition at line 315 of file G4Scintillation.hh.
Referenced by DMXPhysicsList::ConstructOp(), WLSOpticalPhysics::ConstructProcess(), G4OpticalPhysics::ConstructProcess(), and G4OpticalPhysics::SetScintillationExcitationRatio().
SetScintillationTrackInfo()
void G4Scintillation::SetScintillationTrackInfo (const G4bool trackType) inline
Definition at line 363 of file G4Scintillation.hh.
Referenced by G4OpticalPhysics::ConstructProcess(), and G4OpticalPhysics::SetScintillationTrackInfo().
SetScintillationYieldFactor()
void G4Scintillation::SetScintillationYieldFactor (const G4double yieldfactor) inline
Definition at line 303 of file G4Scintillation.hh.
Referenced by OpNovicePhysicsList::ConstructOp(), DMXPhysicsList::ConstructOp(), WLSOpticalPhysics::ConstructProcess(), G4OpticalPhysics::ConstructProcess(), and G4OpticalPhysics::SetScintillationYieldFactor().
SetStackPhotons()
void G4Scintillation::SetStackPhotons (const G4bool stackingFlag) inline
Definition at line 375 of file G4Scintillation.hh.
Referenced by G4OpticalPhysics::ConstructProcess(), and G4OpticalPhysics::SetScintillationStackPhotons().
SetTrackSecondariesFirst()
void G4Scintillation::SetTrackSecondariesFirst (const G4bool state) inline
Definition at line 279 of file G4Scintillation.hh.
Referenced by OpNovicePhysicsList::ConstructOp(), DMXPhysicsList::ConstructOp(), WLSOpticalPhysics::ConstructProcess(), and G4OpticalPhysics::ConstructProcess().
single_exp()
G4double G4Scintillation::single_exp (G4double t, G4double tau2) inline private
Definition at line 394 of file G4Scintillation.hh.
Referenced by sample_time().
Field Documentation
fEmSaturation
G4EmSaturation* G4Scintillation::fEmSaturation private
Definition at line 270 of file G4Scintillation.hh.
Referenced by AddSaturation(), GetSaturation(), PostStepDoIt(), RemoveSaturation(), and SetScintillationByParticleType().
fExcitationRatio
G4double G4Scintillation::fExcitationRatio private
Definition at line 250 of file G4Scintillation.hh.
Referenced by GetScintillationExcitationRatio(), PostStepDoIt(), and SetScintillationExcitationRatio().
fFastIntegralTable
G4PhysicsTable* G4Scintillation::fFastIntegralTable protected
Definition at line 240 of file G4Scintillation.hh.
Referenced by BuildPhysicsTable(), BuildThePhysicsTable(), DumpPhysicsTable(), G4Scintillation(), GetFastIntegralTable(), PostStepDoIt(), and ~G4Scintillation().
fFiniteRiseTime
G4bool G4Scintillation::fFiniteRiseTime private
Definition at line 246 of file G4Scintillation.hh.
Referenced by GetFiniteRiseTime(), PostStepDoIt(), and SetFiniteRiseTime().
fNumPhotons
G4int G4Scintillation::fNumPhotons private
Definition at line 258 of file G4Scintillation.hh.
Referenced by GetNumPhotons(), and PostStepDoIt().
fScintillationByParticleType
G4bool G4Scintillation::fScintillationByParticleType private
Definition at line 252 of file G4Scintillation.hh.
Referenced by GetScintillationByParticleType(), PostStepDoIt(), and SetScintillationByParticleType().
fScintillationTrackInfo
G4bool G4Scintillation::fScintillationTrackInfo private
Definition at line 254 of file G4Scintillation.hh.
Referenced by GetScintillationTrackInfo(), PostStepDoIt(), and SetScintillationTrackInfo().
fSlowIntegralTable
G4PhysicsTable* G4Scintillation::fSlowIntegralTable protected
Definition at line 241 of file G4Scintillation.hh.
Referenced by BuildPhysicsTable(), BuildThePhysicsTable(), DumpPhysicsTable(), G4Scintillation(), GetSlowIntegralTable(), PostStepDoIt(), and ~G4Scintillation().
fStackingFlag
G4bool G4Scintillation::fStackingFlag private
Definition at line 256 of file G4Scintillation.hh.
Referenced by GetStackPhotons(), PostStepDoIt(), and SetStackPhotons().
fTrackSecondariesFirst
G4bool G4Scintillation::fTrackSecondariesFirst private
Definition at line 245 of file G4Scintillation.hh.
Referenced by GetTrackSecondariesFirst(), PostStepDoIt(), and SetTrackSecondariesFirst().
fYieldFactor
G4double G4Scintillation::fYieldFactor private
Definition at line 248 of file G4Scintillation.hh.
Referenced by GetScintillationYieldFactor(), PostStepDoIt(), and SetScintillationYieldFactor().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/xrays/include/G4Scintillation.hh
source/processes/electromagnetic/xrays/src/G4Scintillation.cc