Geant4: source/processes/electromagnetic/dna/management/src/G4IT.cc File Reference
G4IT.cc File Reference
#include "G4IT.hh"
#include "G4KDTree.hh"
#include "G4ITBox.hh"
#include "G4Track.hh"
#include "G4TrackList.hh"
#include "G4TrackingInformation.hh"
Functions
G4IT * GetIT (const G4Track *track)
G4IT * GetIT (const G4Track &track)
Function Documentation
GetIT() [1/2]
G4IT* GetIT (const G4Track & track)
Definition at line 53 of file G4IT.cc.
GetIT() [2/2]
G4IT* GetIT (const G4Track * track)
Definition at line 48 of file G4IT.cc.
Referenced by G4ITTrackHolder::_PushTrack(), G4DNABrownianTransportation::AlongStepDoIt(), G4ITTransportation::AlongStepGetPhysicalInteractionLength(), ITTrackingInteractivity::AppendStep(), G4ITModelProcessor::CalculateMinTimeStep(), G4DNABrownianTransportation::ComputeGeomLimit(), G4ITStepProcessor::ComputeInteractionLength(), G4DNABrownianTransportation::ComputeStep(), G4ITModelProcessor::ComputeTrackReaction(), G4DNABrownianTransportation::Diffusion(), G4ITModelProcessor::DoCalculateStep(), G4ITStepProcessor::DoStepping(), ITTrackingInteractivity::EndTracking(), G4ITModelProcessor::FindReaction(), GetMolecule(), G4Molecule::GetMolecule(), G4ITTrackHolder::KillTracks(), G4ITSteppingVerbose::PostStepVerbose(), G4ITLeadingTracks::PrepareLeadingTracks(), G4ITSteppingVerbose::PreStepVerbose(), G4AllITFinder::Push(), G4ITTrackHolder::PushDelayed(), G4ITTrackHolder::PushTo(), G4ITLeadingTracks::Reset(), G4ITStepProcessor::SetTrack(), ITTrackingInteractivity::StartTracking(), G4ITTransportation::StartTracking(), G4VITProcess::StartTracking(), and G4ITSteppingVerbose::TrackingStarted().