Geant4: G4RDVCrossSectionHandler Class Reference
G4RDVCrossSectionHandler Class Reference abstract
#include <G4RDVCrossSectionHandler.hh>
Public Member Functions
G4RDVCrossSectionHandler ()
G4RDVCrossSectionHandler (G4RDVDataSetAlgorithm *interpolation, G4double minE=250 *CLHEP::eV, G4double maxE=100 *CLHEP::GeV, G4int nBins=200, G4double unitE=CLHEP::MeV, G4double unitData=CLHEP::barn, G4int minZ=1, G4int maxZ=99)
virtual ~G4RDVCrossSectionHandler ()
void Initialise (G4RDVDataSetAlgorithm *interpolation=0, G4double minE=250 *CLHEP::eV, G4double maxE=100 *CLHEP::GeV, G4int numberOfBins=200, G4double unitE=CLHEP::MeV, G4double unitData=CLHEP::barn, G4int minZ=1, G4int maxZ=99)
G4int SelectRandomAtom (const G4MaterialCutsCouple *couple, G4double e) const
const G4Element * SelectRandomElement (const G4MaterialCutsCouple *material, G4double e) const
G4int SelectRandomShell (G4int Z, G4double e) const
G4RDVEMDataSet * BuildMeanFreePathForMaterials (const G4DataVector *energyCuts=0)
G4double FindValue (G4int Z, G4double e) const
G4double FindValue (G4int Z, G4double e, G4int shellIndex) const
G4double ValueForMaterial (const G4Material *material, G4double e) const
void LoadData (const G4String &dataFile)
void LoadShellData (const G4String &dataFile)
void PrintData () const
void Clear ()
Protected Member Functions
G4int NumberOfComponents (G4int Z) const
void ActiveElements ()
virtual std::vector< G4RDVEMDataSet * > * BuildCrossSectionsForMaterials (const G4DataVector &energyVector, const G4DataVector *energyCuts=0)=0
virtual G4RDVDataSetAlgorithm * CreateInterpolation ()
const G4RDVDataSetAlgorithm * GetInterpolation () const
Private Member Functions
G4RDVCrossSectionHandler (const G4RDVCrossSectionHandler &)
G4RDVCrossSectionHandler & operator= (const G4RDVCrossSectionHandler &right)
Private Attributes
G4RDVDataSetAlgorithm * interpolation
G4double eMin
G4double eMax
G4int nBins
G4double unit1
G4double unit2
G4int zMin
G4int zMax
G4DataVector activeZ
std::map< G4int, G4RDVEMDataSet *, std::less< G4int > > dataMap
std::vector< G4RDVEMDataSet * > * crossSections
Detailed Description
Definition at line 62 of file G4RDVCrossSectionHandler.hh.
Constructor & Destructor Documentation
G4RDVCrossSectionHandler() [1/3]
G4RDVCrossSectionHandler::G4RDVCrossSectionHandler ()
Definition at line 57 of file G4RDVCrossSectionHandler.cc.
G4RDVCrossSectionHandler() [2/3]
G4RDVCrossSectionHandler::G4RDVCrossSectionHandler (G4RDVDataSetAlgorithm * interpolation, G4double minE = 250*CLHEP::eV, G4double maxE = 100*CLHEP::GeV, G4int nBins = 200, G4double unitE = CLHEP::MeV, G4double unitData = CLHEP::barn, G4int minZ = 1, G4int maxZ = 99)
Definition at line 66 of file G4RDVCrossSectionHandler.cc.
~G4RDVCrossSectionHandler()
G4RDVCrossSectionHandler::~G4RDVCrossSectionHandler () virtual
Definition at line 81 of file G4RDVCrossSectionHandler.cc.
G4RDVCrossSectionHandler() [3/3]
G4RDVCrossSectionHandler::G4RDVCrossSectionHandler (const G4RDVCrossSectionHandler &) private
Member Function Documentation
ActiveElements()
void G4RDVCrossSectionHandler::ActiveElements () protected
Definition at line 622 of file G4RDVCrossSectionHandler.cc.
Referenced by Clear(), and G4RDVCrossSectionHandler().
BuildCrossSectionsForMaterials()
virtual std::vector<G4RDVEMDataSet*>* G4RDVCrossSectionHandler::BuildCrossSectionsForMaterials (const G4DataVector & energyVector, const G4DataVector * energyCuts = 0) protected pure virtual
Implemented in G4RDCrossSectionHandler, G4RDeIonisationCrossSectionHandler, and G4RDBremsstrahlungCrossSectionHandler.
Referenced by BuildMeanFreePathForMaterials().
BuildMeanFreePathForMaterials()
G4RDVEMDataSet * G4RDVCrossSectionHandler::BuildMeanFreePathForMaterials (const G4DataVector * energyCuts = 0)
Definition at line 414 of file G4RDVCrossSectionHandler.cc.
Referenced by G4LowEnergyRayleigh::BuildPhysicsTable(), G4LowEnergyCompton::BuildPhysicsTable(), G4LowEnergyGammaConversion::BuildPhysicsTable(), G4LowEnergyPhotoElectric::BuildPhysicsTable(), and G4LowEnergyPolarizedCompton::BuildPhysicsTable().
Clear()
void G4RDVCrossSectionHandler::Clear ()
Definition at line 304 of file G4RDVCrossSectionHandler.cc.
Referenced by G4LowEnergyRayleigh::BuildPhysicsTable(), G4LowEnergyCompton::BuildPhysicsTable(), G4LowEnergyGammaConversion::BuildPhysicsTable(), G4LowEnergyPhotoElectric::BuildPhysicsTable(), and G4LowEnergyPolarizedCompton::BuildPhysicsTable().
CreateInterpolation()
G4RDVDataSetAlgorithm * G4RDVCrossSectionHandler::CreateInterpolation () protected virtual
Definition at line 649 of file G4RDVCrossSectionHandler.cc.
Referenced by G4RDCrossSectionHandler::BuildCrossSectionsForMaterials(), BuildMeanFreePathForMaterials(), and Initialise().
FindValue() [1/2]
G4double G4RDVCrossSectionHandler::FindValue (G4int Z, G4double e) const
Definition at line 330 of file G4RDVCrossSectionHandler.cc.
Referenced by G4RDCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDBremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDeIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4LowEnergyBremsstrahlung::BuildLossTable(), G4LowEnergyIonisation::BuildLossTable(), SelectRandomShell(), and ValueForMaterial().
FindValue() [2/2]
G4double G4RDVCrossSectionHandler::FindValue (G4int Z, G4double e, G4int shellIndex) const
Definition at line 353 of file G4RDVCrossSectionHandler.cc.
GetInterpolation()
const G4RDVDataSetAlgorithm* G4RDVCrossSectionHandler::GetInterpolation () const inline protected
Definition at line 118 of file G4RDVCrossSectionHandler.hh.
Initialise()
void G4RDVCrossSectionHandler::Initialise (G4RDVDataSetAlgorithm * interpolation = 0, G4double minE = 250*CLHEP::eV, G4double maxE = 100*CLHEP::GeV, G4int numberOfBins = 200, G4double unitE = CLHEP::MeV, G4double unitData = CLHEP::barn, G4int minZ = 1, G4int maxZ = 99)
Definition at line 109 of file G4RDVCrossSectionHandler.cc.
Referenced by G4LowEnergyBremsstrahlung::BuildPhysicsTable(), G4LowEnergyGammaConversion::G4LowEnergyGammaConversion(), G4RDeIonisationCrossSectionHandler::G4RDeIonisationCrossSectionHandler(), and G4RDVCrossSectionHandler().
LoadData()
void G4RDVCrossSectionHandler::LoadData (const G4String & dataFile)
Definition at line 155 of file G4RDVCrossSectionHandler.cc.
Referenced by G4LowEnergyRayleigh::BuildPhysicsTable(), G4LowEnergyCompton::BuildPhysicsTable(), G4LowEnergyGammaConversion::BuildPhysicsTable(), G4LowEnergyPhotoElectric::BuildPhysicsTable(), and G4LowEnergyPolarizedCompton::BuildPhysicsTable().
LoadShellData()
void G4RDVCrossSectionHandler::LoadShellData (const G4String & dataFile)
Definition at line 223 of file G4RDVCrossSectionHandler.cc.
Referenced by G4LowEnergyPhotoElectric::BuildPhysicsTable(), G4LowEnergyIonisation::BuildPhysicsTable(), and G4LowEnergyBremsstrahlung::BuildPhysicsTable().
NumberOfComponents()
G4int G4RDVCrossSectionHandler::NumberOfComponents (G4int Z) const protected
Definition at line 655 of file G4RDVCrossSectionHandler.cc.
Referenced by G4RDeIonisationCrossSectionHandler::BuildCrossSectionsForMaterials().
operator=()
G4RDVCrossSectionHandler& G4RDVCrossSectionHandler::operator= (const G4RDVCrossSectionHandler & right) private
PrintData()
void G4RDVCrossSectionHandler::PrintData (void) const
Definition at line 134 of file G4RDVCrossSectionHandler.cc.
Referenced by G4LowEnergyIonisation::BuildPhysicsTable(), and G4LowEnergyBremsstrahlung::BuildPhysicsTable().
SelectRandomAtom()
G4int G4RDVCrossSectionHandler::SelectRandomAtom (const G4MaterialCutsCouple * couple, G4double e) const
Definition at line 496 of file G4RDVCrossSectionHandler.cc.
Referenced by G4LowEnergyRayleigh::PostStepDoIt(), G4LowEnergyCompton::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), and G4LowEnergyBremsstrahlung::PostStepDoIt().
SelectRandomElement()
const G4Element * G4RDVCrossSectionHandler::SelectRandomElement (const G4MaterialCutsCouple * material, G4double e) const
Definition at line 538 of file G4RDVCrossSectionHandler.cc.
Referenced by G4LowEnergyGammaConversion::PostStepDoIt().
SelectRandomShell()
G4int G4RDVCrossSectionHandler::SelectRandomShell (G4int Z, G4double e) const
Definition at line 584 of file G4RDVCrossSectionHandler.cc.
Referenced by G4LowEnergyIonisation::DeexciteAtom(), G4LowEnergyPhotoElectric::PostStepDoIt(), and G4LowEnergyIonisation::PostStepDoIt().
ValueForMaterial()
G4double G4RDVCrossSectionHandler::ValueForMaterial (const G4Material * material, G4double e) const
Definition at line 393 of file G4RDVCrossSectionHandler.cc.
Referenced by G4LowEnergyPhotoElectric::GetMeanFreePath().
Field Documentation
activeZ
G4DataVector G4RDVCrossSectionHandler::activeZ private
Definition at line 139 of file G4RDVCrossSectionHandler.hh.
Referenced by ActiveElements(), Clear(), LoadData(), and LoadShellData().
crossSections
std::vector<G4RDVEMDataSet*>* G4RDVCrossSectionHandler::crossSections private
Definition at line 143 of file G4RDVCrossSectionHandler.hh.
Referenced by BuildMeanFreePathForMaterials(), G4RDVCrossSectionHandler(), and ~G4RDVCrossSectionHandler().
dataMap
std::map<G4int,G4RDVEMDataSet*,std::less<G4int> > G4RDVCrossSectionHandler::dataMap private
Definition at line 141 of file G4RDVCrossSectionHandler.hh.
Referenced by Clear(), FindValue(), LoadData(), LoadShellData(), NumberOfComponents(), PrintData(), SelectRandomShell(), and ~G4RDVCrossSectionHandler().
eMax
G4double G4RDVCrossSectionHandler::eMax private
Definition at line 130 of file G4RDVCrossSectionHandler.hh.
Referenced by BuildMeanFreePathForMaterials(), and Initialise().
eMin
G4double G4RDVCrossSectionHandler::eMin private
Definition at line 129 of file G4RDVCrossSectionHandler.hh.
Referenced by BuildMeanFreePathForMaterials(), and Initialise().
interpolation
G4RDVDataSetAlgorithm* G4RDVCrossSectionHandler::interpolation private
Definition at line 127 of file G4RDVCrossSectionHandler.hh.
Referenced by G4RDVCrossSectionHandler(), GetInterpolation(), Initialise(), LoadData(), LoadShellData(), and ~G4RDVCrossSectionHandler().
nBins
G4int G4RDVCrossSectionHandler::nBins private
Definition at line 131 of file G4RDVCrossSectionHandler.hh.
Referenced by BuildMeanFreePathForMaterials(), and Initialise().
unit1
G4double G4RDVCrossSectionHandler::unit1 private
Definition at line 133 of file G4RDVCrossSectionHandler.hh.
Referenced by Initialise(), LoadData(), and LoadShellData().
unit2
G4double G4RDVCrossSectionHandler::unit2 private
Definition at line 134 of file G4RDVCrossSectionHandler.hh.
Referenced by Initialise(), LoadData(), and LoadShellData().
zMax
G4int G4RDVCrossSectionHandler::zMax private
Definition at line 137 of file G4RDVCrossSectionHandler.hh.
Referenced by ActiveElements(), and Initialise().
zMin
G4int G4RDVCrossSectionHandler::zMin private
Definition at line 136 of file G4RDVCrossSectionHandler.hh.
Referenced by ActiveElements(), and Initialise().
The documentation for this class was generated from the following files:
examples/advanced/eRosita/physics/include/G4RDVCrossSectionHandler.hh
examples/advanced/eRosita/physics/src/G4RDVCrossSectionHandler.cc