Geant4: G4StepPoint Class Reference
G4StepPoint Class Reference
#include <G4StepPoint.hh>
Public Member Functions
G4StepPoint ()
~G4StepPoint ()
G4StepPoint (const G4StepPoint &)
G4StepPoint & operator= (const G4StepPoint &)
const G4ThreeVector & GetPosition () const
void SetPosition (const G4ThreeVector &aValue)
void AddPosition (const G4ThreeVector &aValue)
G4double GetLocalTime () const
void SetLocalTime (const G4double aValue)
void AddLocalTime (const G4double aValue)
G4double GetGlobalTime () const
void SetGlobalTime (const G4double aValue)
void AddGlobalTime (const G4double aValue)
G4double GetProperTime () const
void SetProperTime (const G4double aValue)
void AddProperTime (const G4double aValue)
const G4ThreeVector & GetMomentumDirection () const
void SetMomentumDirection (const G4ThreeVector &aValue)
void AddMomentumDirection (const G4ThreeVector &aValue)
G4ThreeVector GetMomentum () const
G4double GetTotalEnergy () const
G4double GetKineticEnergy () const
void SetKineticEnergy (const G4double aValue)
void AddKineticEnergy (const G4double aValue)
G4double GetVelocity () const
void SetVelocity (G4double v)
G4double GetBeta () const
G4double GetGamma () const
G4VPhysicalVolume * GetPhysicalVolume () const
const G4VTouchable * GetTouchable () const
const G4TouchableHandle & GetTouchableHandle () const
void SetTouchableHandle (const G4TouchableHandle &apValue)
G4Material * GetMaterial () const
void SetMaterial (G4Material *)
const G4MaterialCutsCouple * GetMaterialCutsCouple () const
void SetMaterialCutsCouple (const G4MaterialCutsCouple *)
G4VSensitiveDetector * GetSensitiveDetector () const
void SetSensitiveDetector (G4VSensitiveDetector *)
G4double GetSafety () const
void SetSafety (const G4double aValue)
const G4ThreeVector & GetPolarization () const
void SetPolarization (const G4ThreeVector &aValue)
void AddPolarization (const G4ThreeVector &aValue)
G4StepStatus GetStepStatus () const
void SetStepStatus (const G4StepStatus aValue)
const G4VProcess * GetProcessDefinedStep () const
void SetProcessDefinedStep (const G4VProcess *aValue)
G4double GetMass () const
void SetMass (G4double value)
G4double GetCharge () const
void SetCharge (G4double value)
G4double GetMagneticMoment () const
void SetMagneticMoment (G4double value)
void SetWeight (G4double aValue)
G4double GetWeight () const
Private Attributes
G4ThreeVector fPosition
G4double fGlobalTime
G4double fLocalTime
G4double fProperTime
G4ThreeVector fMomentumDirection
G4double fKineticEnergy
G4double fVelocity
G4TouchableHandle fpTouchable
G4Material * fpMaterial
const G4MaterialCutsCouple * fpMaterialCutsCouple
G4VSensitiveDetector * fpSensitiveDetector
G4double fSafety
G4ThreeVector fPolarization
G4StepStatus fStepStatus
const G4VProcess * fpProcessDefinedStep
G4double fMass
G4double fCharge
G4double fMagneticMoment
G4double fWeight
Detailed Description
Definition at line 67 of file G4StepPoint.hh.
Constructor & Destructor Documentation
G4StepPoint() [1/2]
G4StepPoint::G4StepPoint ()
Definition at line 47 of file G4StepPoint.cc.
~G4StepPoint()
G4StepPoint::~G4StepPoint () inline
Definition at line 78 of file G4StepPoint.hh.
G4StepPoint() [2/2]
G4StepPoint::G4StepPoint (const G4StepPoint & right)
Definition at line 61 of file G4StepPoint.cc.
Member Function Documentation
AddGlobalTime()
void G4StepPoint::AddGlobalTime (const G4double aValue)
Referenced by G4ParticleChangeForTransport::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAtRest(), and G4ParticleChange::UpdateStepForPostStep().
AddKineticEnergy()
void G4StepPoint::AddKineticEnergy (const G4double aValue)
AddLocalTime()
void G4StepPoint::AddLocalTime (const G4double aValue)
Referenced by G4ParticleChangeForTransport::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), G4FastStep::UpdateStepForAtRest(), and G4FastStep::UpdateStepForPostStep().
AddMomentumDirection()
void G4StepPoint::AddMomentumDirection (const G4ThreeVector & aValue)
AddPolarization()
void G4StepPoint::AddPolarization (const G4ThreeVector & aValue)
Referenced by G4ParticleChangeForTransport::UpdateStepForAlongStep(), and G4ParticleChange::UpdateStepForAlongStep().
AddPosition()
void G4StepPoint::AddPosition (const G4ThreeVector & aValue)
Referenced by G4ParticleChangeForTransport::UpdateStepForAlongStep(), and G4ParticleChange::UpdateStepForAlongStep().
AddProperTime()
void G4StepPoint::AddProperTime (const G4double aValue)
Referenced by G4ParticleChangeForTransport::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), and G4ParticleChangeForDecay::UpdateStepForAtRest().
GetBeta()
G4double G4StepPoint::GetBeta () const
Referenced by export_G4StepPoint(), and G4Cerenkov::PostStepDoIt().
GetCharge()
G4double G4StepPoint::GetCharge () const
Referenced by G4SDChargedFilter::Accept(), G4SDNeutralFilter::Accept(), G4NuclearStopping::AlongStepDoIt(), export_G4StepPoint(), and G4PSCellCharge::ProcessHits().
GetGamma()
G4double G4StepPoint::GetGamma () const
Referenced by export_G4StepPoint().
GetGlobalTime()
G4double G4StepPoint::GetGlobalTime () const
Referenced by G4VAtomDeexcitation::AlongStepDeexcitation(), G4eLowEnergyLoss::AlongStepDoIt(), G4DNABrownianTransportation::ComputeStep(), export_G4StepPoint(), F04TrajectoryPoint::F04TrajectoryPoint(), G4RichTrajectoryPoint::G4RichTrajectoryPoint(), CCaloSD::getStepInfo(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4Scintillation::PostStepDoIt(), ScreenSD::ProcessHits(), XAluminumElectrodeSensitivity::ProcessHits(), DMXScintSD::ProcessHits(), DMXPmtSD::ProcessHits(), G4VEnergyLossProcess::SampleSubCutSecondaries(), G4SteppingVerbose::ShowStep(), CCalSteppingAction::UserSteppingAction(), and WLSTrajectoryPoint::WLSTrajectoryPoint().
GetKineticEnergy()
G4double G4StepPoint::GetKineticEnergy () const
Referenced by G4SDKineticEnergyFilter::Accept(), G4VAtomDeexcitation::AlongStepDeexcitation(), G4NuclearStopping::AlongStepDoIt(), G4AdjointAlongStepWeightCorrection::AlongStepDoIt(), XrayFluoAnalysisManager::analyseStepping(), G4RichTrajectory::AppendStep(), G4CellScoreComposer::EstimatorCalculation(), export_G4StepPoint(), G4RichTrajectoryPoint::G4RichTrajectoryPoint(), G4Step::GetDeltaEnergy(), G4Scintillation::GetScintillationYieldByParticleType(), ScreenSD::ProcessHits(), eRositaTrackerSD::ProcessHits(), G4PSMinKinEAtGeneration::ProcessHits(), DMXScintSD::ProcessHits(), G4PSTrackLength::ProcessHits(), RMC01SD::ProcessHits(), PrimaryKiller::ProcessHits(), G4TransportationLogger::ReportLoopingTrack(), CCaloSD::ResetForNewPrimary(), G4SteppingVerbose::ShowStep(), G4EnergySplitter::SplitEnergyInVolumes(), G4ParticleChangeForLoss::UpdateStepForAlongStep(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), G4ParticleChangeForTransport::UpdateStepForPostStep(), and DMXSteppingAction::UserSteppingAction().
GetLocalTime()
G4double G4StepPoint::GetLocalTime () const
Referenced by export_G4StepPoint(), G4SteppingVerbose::ShowStep(), and G4ParticleChangeForTransport::UpdateStepForAlongStep().
GetMagneticMoment()
G4double G4StepPoint::GetMagneticMoment () const
GetMass()
G4double G4StepPoint::GetMass () const
Referenced by export_G4StepPoint().
GetMaterial()
G4Material* G4StepPoint::GetMaterial () const
Referenced by G4VAtomDeexcitation::AlongStepDeexcitation(), RE04Trajectory::AppendStep(), G4ExceptionHandler::DumpTrackInfo(), export_G4StepPoint(), G4ElectronIonPair::MeanNumberOfIonsAlongStep(), G4UCNBoundaryProcess::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4PSDoseDeposit::ProcessHits(), G4EnergySplitter::SplitEnergyInVolumes(), G4ParallelWorldProcess::SwitchMaterial(), and G4MSSteppingAction::UserSteppingAction().
GetMaterialCutsCouple()
const G4MaterialCutsCouple* G4StepPoint::GetMaterialCutsCouple () const
Referenced by G4SteppingManager::ApplyProductionCut(), and G4ParallelWorldProcess::SwitchMaterial().
GetMomentum()
G4ThreeVector G4StepPoint::GetMomentum () const
Referenced by export_G4StepPoint(), F04TrajectoryPoint::F04TrajectoryPoint(), G4Step::GetDeltaMomentum(), G4ErrorFreeTrajState::PropagateError(), G4ErrorFreeTrajState::PropagateErrorIoni(), G4SteppingVerbose::ShowStep(), G4Channeling::UpdateParameters(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), and WLSTrajectoryPoint::WLSTrajectoryPoint().
GetMomentumDirection()
const G4ThreeVector& G4StepPoint::GetMomentumDirection () const
Referenced by G4VMultipleScattering::AlongStepDoIt(), export_G4StepPoint(), G4VReadOutGeometry::FindROTouchable(), G4VTransitionRadiation::PostStepDoIt(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::ResampleTrackLengthInTarget(), and G4SteppingVerbose::ShowStep().
GetPhysicalVolume()
G4VPhysicalVolume* G4StepPoint::GetPhysicalVolume () const
Referenced by CML2ExpVoxels::add(), XrayFluoAnalysisManager::analyseStepping(), Par01PionShowerModel::AssignSpotAndCallHit(), Par01EMShowerModel::AssignSpotAndCallHit(), G4VReadOutGeometry::CheckROVolume(), G4PSDoseDeposit::ComputeVolume(), G4PSPassageCellFlux::ComputeVolume(), G4PSCellFlux::ComputeVolume(), G4ExceptionHandler::DumpTrackInfo(), F04TrajectoryPoint::F04TrajectoryPoint(), G4NeutrinoElectronProcess::GetMeanFreePath(), CCaloSD::getStepInfo(), G4ITStepProcessor::InitDefineStep(), RE06SteppingVerbose::NewStep(), G4NeutrinoElectronProcess::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4WeightCutOffProcess::PostStepDoIt(), G4ImportanceProcess::PostStepDoIt(), G4WeightWindowProcess::PostStepDoIt(), G4UCNAbsorption::PostStepDoIt(), G4UCNMultiScattering::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4AdjointForcedInteractionForGamma::PostStepGetPhysicalInteractionLength(), G4PSSphereSurfaceCurrent::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSFlatSurfaceCurrent::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), G4SteppingVerbose::ShowStep(), G4SteppingManager::Stepping(), ExN04SteppingAction::UserSteppingAction(), RE05SteppingAction::UserSteppingAction(), RE01SteppingAction::UserSteppingAction(), LXeSteppingAction::UserSteppingAction(), F04SteppingAction::UserSteppingAction(), doiPETSteppingAction::UserSteppingAction(), G4MSSteppingAction::UserSteppingAction(), WLSSteppingAction::UserSteppingAction(), PurgMagSteppingAction::UserSteppingAction(), G4RTSteppingAction::UserSteppingAction(), G4ScoreSplittingProcess::Verbose(), G4ParallelWorldScoringProcess::Verbose(), and WLSTrajectoryPoint::WLSTrajectoryPoint().
GetPolarization()
const G4ThreeVector& G4StepPoint::GetPolarization () const
Referenced by export_G4StepPoint(), G4SteppingVerbose::ShowStep(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), and G4ParticleChange::UpdateStepForAlongStep().
GetPosition()
const G4ThreeVector& G4StepPoint::GetPosition () const
Referenced by CML2ExpVoxels::add(), HistoManager::AddTargetStep(), G4VAtomDeexcitation::AlongStepDeexcitation(), G4eLowEnergyLoss::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepDoIt(), G4VMultipleScattering::AlongStepDoIt(), RE01Trajectory::AppendStep(), G4SmoothTrajectory::AppendStep(), RE04Trajectory::AppendStep(), G4DecayWithSpin::AtRestDoIt(), G4SteppingManager::CalculateSafety(), G4ITStepProcessor::CalculateSafety(), G4VMscModel::ComputeGeomLimit(), G4DNABrownianTransportation::ComputeGeomLimit(), G4AdjointCrossSurfChecker::CrossingAGivenRegisteredSurface(), G4AdjointCrossSurfChecker::CrossingASphere(), CCaloSD::curve_LY(), G4ExceptionHandler::DumpTrackInfo(), export_G4StepPoint(), G4DNASmoluchowskiReactionModel::FindReaction(), G4VReadOutGeometry::FindROTouchable(), CCaloSD::getStepInfo(), G4PSSphereSurfaceCurrent::IsSelectedSurface(), G4PSCylinderSurfaceFlux::IsSelectedSurface(), G4PSCylinderSurfaceCurrent::IsSelectedSurface(), G4PSFlatSurfaceCurrent::IsSelectedSurface(), G4PSSphereSurfaceFlux::IsSelectedSurface(), G4PSFlatSurfaceFlux::IsSelectedSurface(), G4Channeling::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VTransitionRadiation::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4ScoreSplittingProcess::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), RE05TrackerSD::ProcessHits(), ExN04MuonSD::ProcessHits(), ExN04TrackerSD::ProcessHits(), ScreenSD::ProcessHits(), RE05MuonSD::ProcessHits(), eRositaTrackerSD::ProcessHits(), LXeScintSD::ProcessHits(), ExTGTrackerSD::ProcessHits(), RE01TrackerSD::ProcessHits(), XAluminumElectrodeSensitivity::ProcessHits(), ExN02TrackerSD::ProcessHits(), ExGflashSensitiveDetector::ProcessHits(), ExP01TrackerSD::ProcessHits(), GammaRayTelAnticoincidenceSD::ProcessHits(), GammaRayTelCalorimeterSD::ProcessHits(), GammaRayTelTrackerSD::ProcessHits(), B2TrackerSD::ProcessHits(), TrackerSD::ProcessHits(), DMXScintSD::ProcessHits(), PhantomSD::ProcessHits(), UltraPMTSD::ProcessHits(), DMXPmtSD::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4ErrorFreeTrajState::PropagateError(), CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::ResampleTrackLengthInTarget(), G4ElectronIonPair::SampleIonsAlongStep(), G4VEnergyLossProcess::SampleSubCutSecondaries(), G4SteppingVerbose::ShowStep(), G4SteppingManager::Stepping(), G4Channeling::UpdateParameters(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), CCalSteppingAction::UserSteppingAction(), RE04SteppingAction::UserSteppingAction(), XrayFluoSteppingAction::UserSteppingAction(), doiPETSteppingAction::UserSteppingAction(), DMXSteppingAction::UserSteppingAction(), G4ScoreSplittingProcess::Verbose(), and G4ParallelWorldScoringProcess::Verbose().
GetProcessDefinedStep()
const G4VProcess* G4StepPoint::GetProcessDefinedStep () const
Referenced by G4RichTrajectory::AppendStep(), G4DNABrownianTransportation::ComputeStep(), G4ExceptionHandler::DumpTrackInfo(), export_G4StepPoint(), G4RichTrajectoryPoint::G4RichTrajectoryPoint(), G4ErrorPropagator::MakeOneStep(), G4ITSteppingVerbose::PostStepVerbose(), G4ElectronIonPair::ResidualeChargePostStep(), G4SteppingVerbose::ShowStep(), F04SteppingVerbose::StepInfo(), WLSSteppingVerbose::StepInfo(), ExN04SteppingVerbose::StepInfo(), SteppingVerbose::StepInfo(), OpNoviceSteppingVerbose::StepInfo(), eRositaSteppingVerbose::StepInfo(), FCALSteppingVerbose::StepInfo(), XrayFluoSteppingVerbose::StepInfo(), PurgMagSteppingVerbose::StepInfo(), ExN02SteppingVerbose::StepInfo(), RE05SteppingVerbose::StepInfo(), ExP01SteppingVerbose::StepInfo(), F05SteppingVerbose::StepInfo(), G4SteppingVerbose::StepInfo(), F01SteppingVerbose::StepInfo(), F02SteppingVerbose::StepInfo(), F03SteppingVerbose::StepInfo(), LXeSteppingAction::UserSteppingAction(), F04SteppingAction::UserSteppingAction(), doiPETSteppingAction::UserSteppingAction(), PurgMagSteppingAction::UserSteppingAction(), G4ScoreSplittingProcess::Verbose(), and G4ParallelWorldScoringProcess::Verbose().
GetProperTime()
G4double G4StepPoint::GetProperTime () const
Referenced by export_G4StepPoint(), G4SteppingVerbose::ShowStep(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), and G4ParticleChange::UpdateStepForAlongStep().
GetSafety()
G4double G4StepPoint::GetSafety () const
Referenced by G4VEnergyLossProcess::AlongStepDoIt(), G4eplusAnnihilation::AtRestDoIt(), G4LowEnergyCompton::PostStepDoIt(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), and G4SteppingVerbose::ShowStep().
GetSensitiveDetector()
G4VSensitiveDetector* G4StepPoint::GetSensitiveDetector () const
Referenced by G4ParallelWorldScoringProcess::AtRestDoIt(), G4UCNBoundaryProcess::InvokeSD(), G4OpBoundaryProcess::InvokeSD(), G4ParallelWorldProcess::PostStepDoIt(), and G4ParallelWorldScoringProcess::PostStepDoIt().
GetStepStatus()
G4StepStatus G4StepPoint::GetStepStatus () const
Referenced by G4VEnergyLossProcess::AlongStepDoIt(), XrayFluoAnalysisManager::analyseStepping(), G4BOptnForceFreeFlight::ApplyFinalStateBiasing(), G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4AdjointCrossSurfChecker::CrossingAnInterfaceBetweenTwoVolumes(), G4ExceptionHandler::DumpTrackInfo(), export_G4StepPoint(), F04TrajectoryPoint::F04TrajectoryPoint(), G4RichTrajectoryPoint::G4RichTrajectoryPoint(), GB03BOptnSplitOrKillOnBoundary::GenerateBiasingFinalState(), G4Scintillation::GetScintillationYieldByParticleType(), G4AdjointCrossSurfChecker::GoingInOrOutOfaVolume(), G4AdjointCrossSurfChecker::GoingInOrOutOfaVolumeByExtSurface(), G4PSPassageTrackLength::IsPassed(), G4PSPassageCellCurrent::IsPassed(), G4PSPassageCellFlux::IsPassed(), G4PSSphereSurfaceCurrent::IsSelectedSurface(), G4PSCylinderSurfaceFlux::IsSelectedSurface(), G4PSCylinderSurfaceCurrent::IsSelectedSurface(), G4PSSphereSurfaceFlux::IsSelectedSurface(), G4PSFlatSurfaceCurrent::IsSelectedSurface(), G4PSFlatSurfaceFlux::IsSelectedSurface(), G4PhononScattering::PostStepDoIt(), G4PhononReflection::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4ImportanceProcess::PostStepDoIt(), G4WeightWindowProcess::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4ScoreSplittingProcess::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4BiasingProcessInterface::PostStepGetPhysicalInteractionLength(), G4PSNofCollision::ProcessHits(), G4PSTrackCounter::ProcessHits(), G4PSCellCharge::ProcessHits(), RMC01SD::ProcessHits(), G4BOptrForceCollision::ProposeNonPhysicsBiasingOperation(), G4SteppingVerbose::ShowStep(), G4ParallelWorldProcess::SwitchMaterial(), LXeSteppingAction::UserSteppingAction(), G4AdjointSteppingAction::UserSteppingAction(), and WLSTrajectoryPoint::WLSTrajectoryPoint().
GetTotalEnergy()
G4double G4StepPoint::GetTotalEnergy () const
Referenced by export_G4StepPoint(), and G4SteppingVerbose::ShowStep().
GetTouchable()
const G4VTouchable* G4StepPoint::GetTouchable () const
Referenced by G4RayTrajectory::AppendStep(), G4AdjointCrossSurfChecker::CrossingAnInterfaceBetweenTwoVolumes(), CCalVOrganization::DetectorLevel(), export_G4StepPoint(), RE02PSEnergyDeposit::GetIndex(), G4PSNofSecondary3D::GetIndex(), RE02PSNofStep::GetIndex(), G4PSNofStep3D::GetIndex(), G4PSTermination3D::GetIndex(), G4PSPopulation3D::GetIndex(), G4PSStepChecker3D::GetIndex(), G4PSEnergyDeposit3D::GetIndex(), G4PSNofCollision3D::GetIndex(), G4PSPassageCellCurrent3D::GetIndex(), G4PSTrackCounter3D::GetIndex(), RE02PSPassageCellFlux::GetIndex(), G4PSDoseDeposit3D::GetIndex(), G4PSCellCharge3D::GetIndex(), G4PSMinKinEAtGeneration3D::GetIndex(), G4PSTrackLength3D::GetIndex(), G4PSPassageTrackLength3D::GetIndex(), G4PSPassageCellFlux3D::GetIndex(), RE02PSCellFlux::GetIndex(), G4VPrimitiveScorer::GetIndex(), RE02PSFlatSurfaceCurrent::GetIndex(), G4PSCellFlux3D::GetIndex(), RE02PSFlatSurfaceFlux::GetIndex(), G4PSCylinderSurfaceCurrent3D::GetIndex(), G4PSCylinderSurfaceFlux3D::GetIndex(), G4PSFlatSurfaceCurrent3D::GetIndex(), G4PSSphereSurfaceCurrent3D::GetIndex(), G4PSSphereSurfaceFlux3D::GetIndex(), G4PSFlatSurfaceFlux3D::GetIndex(), CCaloSD::getStepInfo(), CCalHcalOrganization::GetUnitID(), CCalEcalOrganization::GetUnitID(), G4AdjointCrossSurfChecker::GoingInOrOutOfaVolume(), G4AdjointCrossSurfChecker::GoingInOrOutOfaVolumeByExtSurface(), CCalVOrganization::Levels(), G4Channeling::PosToLattice(), G4Channeling::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4WeightCutOffProcess::PostStepDoIt(), G4ImportanceProcess::PostStepDoIt(), G4WeightWindowProcess::PostStepDoIt(), G4HumanPhantomSD::ProcessHits(), ScreenSD::ProcessHits(), RE05CalorimeterSD::ProcessHits(), Par01CalorimeterSD::ProcessHits(), HadrontherapyDetectorSD::ProcessHits(), B5HodoscopeSD::ProcessHits(), LXeScintSD::ProcessHits(), B5DriftChamberSD::ProcessHits(), B5EmCalorimeterSD::ProcessHits(), B5HadCalorimeterSD::ProcessHits(), XAluminumElectrodeSensitivity::ProcessHits(), RE01CalorimeterSD::ProcessHits(), ExGflashSensitiveDetector::ProcessHits(), G4PSDoseDeposit::ProcessHits(), F02CalorimeterSD::ProcessHits(), ExP01TrackerSD::ProcessHits(), FCALHadModuleSD::ProcessHits(), F01CalorimeterSD::ProcessHits(), F03CalorimeterSD::ProcessHits(), FCALEMModuleSD::ProcessHits(), FCALTestbeamSetupSD::ProcessHits(), GammaRayTelCalorimeterSD::ProcessHits(), GammaRayTelTrackerSD::ProcessHits(), GammaRayTelAnticoincidenceSD::ProcessHits(), B4cCalorimeterSD::ProcessHits(), G4PSPassageCellFlux::ProcessHits(), XrayFluoHPGeSD::ProcessHits(), G4PSCellFlux::ProcessHits(), XrayFluoSD::ProcessHits(), G4PSSphereSurfaceCurrent::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSFlatSurfaceCurrent::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), LXePMTSD::ProcessHits_constStep(), WLSPhotonDetSD::ProcessHits_constStep(), CCaloSD::SetToLocal(), G4Channeling::UpdateParameters(), doiPETSteppingAction::UserSteppingAction(), G4RTSteppingAction::UserSteppingAction(), CexmcSteppingAction::UserSteppingAction(), G4ScoreSplittingProcess::Verbose(), and G4ParallelWorldScoringProcess::Verbose().
GetTouchableHandle()
const G4TouchableHandle& G4StepPoint::GetTouchableHandle () const
Referenced by G4ParallelWorldProcess::AtRestDoIt(), G4ParallelWorldScoringProcess::AtRestDoIt(), G4RichTrajectoryPoint::G4RichTrajectoryPoint(), G4PSSphereSurfaceCurrent::IsSelectedSurface(), G4PSCylinderSurfaceFlux::IsSelectedSurface(), G4PSFlatSurfaceCurrent::IsSelectedSurface(), G4PSSphereSurfaceFlux::IsSelectedSurface(), G4PSCylinderSurfaceCurrent::IsSelectedSurface(), G4PSFlatSurfaceFlux::IsSelectedSurface(), SplitProcess::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4WeightCutOffProcess::PostStepDoIt(), G4ImportanceProcess::PostStepDoIt(), G4WeightWindowProcess::PostStepDoIt(), G4ParallelWorldProcess::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4ParallelWorldScoringProcess::PostStepDoIt(), G4Scintillation::PostStepDoIt(), HadrontherapyDetectorSD::ProcessHits(), ExTGTrackerSD::ProcessHits(), ExN02TrackerSD::ProcessHits(), B2TrackerSD::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSFlatSurfaceCurrent::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), B4bSteppingAction::UserSteppingAction(), SteppingAction::UserSteppingAction(), B1SteppingAction::UserSteppingAction(), B4aSteppingAction::UserSteppingAction(), HadrontherapySteppingAction::UserSteppingAction(), and doiPETSteppingAction::UserSteppingAction().
GetVelocity()
G4double G4StepPoint::GetVelocity () const
Referenced by HistoManager::AddTargetStep(), G4Transportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), G4ITTransportation::AlongStepDoIt(), G4CellScoreComposer::EstimatorCalculation(), export_G4StepPoint(), G4Cerenkov::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4PSTrackLength::ProcessHits(), and G4SteppingVerbose::ShowStep().
GetWeight()
G4double G4StepPoint::GetWeight () const
Referenced by G4AdjointForcedInteractionForGamma::AlongStepDoIt(), G4AdjointAlongStepWeightCorrection::AlongStepDoIt(), G4ContinuousGainOfEnergy::AlongStepDoIt(), G4CellScoreComposer::EstimatorCalculation(), export_G4StepPoint(), G4RichTrajectoryPoint::G4RichTrajectoryPoint(), G4PSPassageTrackLength::IsPassed(), G4PSPassageCellFlux::IsPassed(), G4PSDoseDeposit::ProcessHits(), G4PSCellCharge::ProcessHits(), G4PSEnergyDeposit::ProcessHits(), G4PSTermination::ProcessHits(), G4PSTrackCounter::ProcessHits(), G4PSNofCollision::ProcessHits(), G4PSPopulation::ProcessHits(), G4PSPassageCellCurrent::ProcessHits(), G4PSNofSecondary::ProcessHits(), G4PSTrackLength::ProcessHits(), G4PSCellFlux::ProcessHits(), RMC01SD::ProcessHits(), G4PSSphereSurfaceCurrent::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSFlatSurfaceCurrent::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), ScoreSpecies::ProcessHits(), G4SteppingVerbose::ShowStep(), G4ParticleChangeForOccurenceBiasing::UpdateStepForAlongStep(), and G4ParticleChangeForOccurenceBiasing::UpdateStepForPostStep().
operator=()
G4StepPoint & G4StepPoint::operator= (const G4StepPoint & right)
Definition at line 86 of file G4StepPoint.cc.
SetCharge()
void G4StepPoint::SetCharge (G4double value)
Referenced by G4ParticleChangeForLoss::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAtRest(), G4ParticleChangeForLoss::UpdateStepForPostStep(), and G4ParticleChange::UpdateStepForPostStep().
SetGlobalTime()
void G4StepPoint::SetGlobalTime (const G4double aValue)
Referenced by G4ParticleChangeForDecay::UpdateStepForAtRest(), G4FastStep::UpdateStepForAtRest(), and G4FastStep::UpdateStepForPostStep().
SetKineticEnergy()
void G4StepPoint::SetKineticEnergy (const G4double aValue)
Referenced by G4ParticleChangeForLoss::UpdateStepForAlongStep(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAtRest(), G4FastStep::UpdateStepForAtRest(), G4ParticleChangeForGamma::UpdateStepForPostStep(), G4ParticleChangeForLoss::UpdateStepForPostStep(), G4ParticleChange::UpdateStepForPostStep(), and G4FastStep::UpdateStepForPostStep().
SetLocalTime()
void G4StepPoint::SetLocalTime (const G4double aValue)
Referenced by G4ParticleChangeForDecay::UpdateStepForAtRest(), G4ParticleChange::UpdateStepForAtRest(), and G4ParticleChange::UpdateStepForPostStep().
SetMagneticMoment()
void G4StepPoint::SetMagneticMoment (G4double value)
Referenced by G4ParticleChange::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAtRest(), and G4ParticleChange::UpdateStepForPostStep().
SetMass()
void G4StepPoint::SetMass (G4double value)
Referenced by G4ParticleChange::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAtRest(), and G4ParticleChange::UpdateStepForPostStep().
SetMaterial()
void G4StepPoint::SetMaterial (G4Material *)
Referenced by G4ParallelWorldProcess::SwitchMaterial(), and G4ParticleChangeForTransport::UpdateStepForPostStep().
SetMaterialCutsCouple()
void G4StepPoint::SetMaterialCutsCouple (const G4MaterialCutsCouple *)
Referenced by G4ParallelWorldProcess::SwitchMaterial(), and G4ParticleChangeForTransport::UpdateStepForPostStep().
SetMomentumDirection()
void G4StepPoint::SetMomentumDirection (const G4ThreeVector & aValue)
Referenced by G4VGFlashSensitiveDetector::Hit(), G4ParticleChangeForMSC::UpdateStepForAlongStep(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAtRest(), G4FastStep::UpdateStepForAtRest(), G4ParticleChangeForGamma::UpdateStepForPostStep(), G4ParticleChangeForLoss::UpdateStepForPostStep(), G4ParticleChangeForMSC::UpdateStepForPostStep(), G4ParticleChange::UpdateStepForPostStep(), G4FastStep::UpdateStepForPostStep(), and XrayFluoSteppingAction::UserSteppingAction().
SetPolarization()
void G4StepPoint::SetPolarization (const G4ThreeVector & aValue)
Referenced by G4ParticleChangeForDecay::UpdateStepForAtRest(), G4ParticleChange::UpdateStepForAtRest(), G4FastStep::UpdateStepForAtRest(), G4ParticleChangeForGamma::UpdateStepForPostStep(), G4ParticleChangeForLoss::UpdateStepForPostStep(), G4ParticleChangeForDecay::UpdateStepForPostStep(), G4ParticleChange::UpdateStepForPostStep(), and G4FastStep::UpdateStepForPostStep().
SetPosition()
void G4StepPoint::SetPosition (const G4ThreeVector & aValue)
Referenced by G4VGFlashSensitiveDetector::Hit(), G4ScoreSplittingProcess::PostStepDoIt(), G4ParticleChangeForMSC::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAtRest(), G4FastStep::UpdateStepForAtRest(), G4ParticleChangeForMSC::UpdateStepForPostStep(), G4ParticleChange::UpdateStepForPostStep(), and G4FastStep::UpdateStepForPostStep().
SetProcessDefinedStep()
void G4StepPoint::SetProcessDefinedStep (const G4VProcess * aValue)
Referenced by G4SteppingManager::DefinePhysicalStepLength(), G4ITStepProcessor::DoDefinePhysicalStepLength(), and G4SteppingManager::InvokeAtRestDoItProcs().
SetProperTime()
void G4StepPoint::SetProperTime (const G4double aValue)
Referenced by G4ParticleChange::UpdateStepForAtRest(), G4FastStep::UpdateStepForAtRest(), G4ParticleChange::UpdateStepForPostStep(), and G4FastStep::UpdateStepForPostStep().
SetSafety()
void G4StepPoint::SetSafety (const G4double aValue)
Referenced by G4SteppingManager::InvokePSDIP(), and G4SteppingManager::Stepping().
SetSensitiveDetector()
void G4StepPoint::SetSensitiveDetector (G4VSensitiveDetector *)
Referenced by G4ParallelWorldProcess::AtRestDoIt(), G4ParallelWorldScoringProcess::AtRestDoIt(), G4ParallelWorldProcess::PostStepDoIt(), G4ScoreSplittingProcess::PostStepDoIt(), G4ParallelWorldScoringProcess::PostStepDoIt(), and G4ParticleChangeForTransport::UpdateStepForPostStep().
SetStepStatus()
void G4StepPoint::SetStepStatus (const G4StepStatus aValue)
Referenced by G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4SteppingManager::InvokePostStepDoItProcs(), G4ScoreSplittingProcess::PostStepDoIt(), G4ScoreSplittingProcess::StartTracking(), G4ParallelWorldScoringProcess::StartTracking(), G4ParallelWorldProcess::StartTracking(), and G4SteppingManager::Stepping().
SetTouchableHandle()
void G4StepPoint::SetTouchableHandle (const G4TouchableHandle & apValue)
Referenced by G4ParallelWorldProcess::AtRestDoIt(), G4ParallelWorldScoringProcess::AtRestDoIt(), Par01PionShowerModel::FillFakeStep(), Par01EMShowerModel::FillFakeStep(), G4VGFlashSensitiveDetector::Hit(), G4WeightCutOffProcess::PostStepDoIt(), G4ImportanceProcess::PostStepDoIt(), G4WeightWindowProcess::PostStepDoIt(), G4ParallelWorldProcess::PostStepDoIt(), G4ScoreSplittingProcess::PostStepDoIt(), G4ParallelWorldScoringProcess::PostStepDoIt(), G4WeightCutOffProcess::StartTracking(), G4ImportanceProcess::StartTracking(), G4ScoreSplittingProcess::StartTracking(), G4WeightWindowProcess::StartTracking(), G4ParallelWorldScoringProcess::StartTracking(), G4ParallelWorldProcess::StartTracking(), and G4ParticleChangeForTransport::UpdateStepForPostStep().
SetVelocity()
void G4StepPoint::SetVelocity (G4double v)
Referenced by G4ParallelWorldProcess::StartTracking(), G4ParticleChangeForLoss::UpdateStepForAlongStep(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAtRest(), G4ParticleChangeForGamma::UpdateStepForPostStep(), G4ParticleChangeForLoss::UpdateStepForPostStep(), and G4ParticleChange::UpdateStepForPostStep().
SetWeight()
void G4StepPoint::SetWeight (G4double aValue)
Referenced by G4ParticleChangeForOccurenceBiasing::UpdateStepForAlongStep(), G4ParticleChangeForLoss::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), G4ParticleChangeForGamma::UpdateStepForAtRest(), G4ParticleChangeForDecay::UpdateStepForAtRest(), G4ParticleChange::UpdateStepForAtRest(), G4FastStep::UpdateStepForAtRest(), G4ParticleChangeForOccurenceBiasing::UpdateStepForPostStep(), G4ParticleChangeForGamma::UpdateStepForPostStep(), G4ParticleChangeForLoss::UpdateStepForPostStep(), G4ParticleChangeForDecay::UpdateStepForPostStep(), G4ParticleChange::UpdateStepForPostStep(), and G4FastStep::UpdateStepForPostStep().
Field Documentation
fCharge
G4double G4StepPoint::fCharge private
Definition at line 209 of file G4StepPoint.hh.
Referenced by operator=().
fGlobalTime
G4double G4StepPoint::fGlobalTime private
Definition at line 184 of file G4StepPoint.hh.
Referenced by operator=().
fKineticEnergy
G4double G4StepPoint::fKineticEnergy private
Definition at line 191 of file G4StepPoint.hh.
Referenced by operator=().
fLocalTime
G4double G4StepPoint::fLocalTime private
Definition at line 186 of file G4StepPoint.hh.
Referenced by operator=().
fMagneticMoment
G4double G4StepPoint::fMagneticMoment private
Definition at line 211 of file G4StepPoint.hh.
Referenced by operator=().
fMass
G4double G4StepPoint::fMass private
Definition at line 207 of file G4StepPoint.hh.
Referenced by operator=().
fMomentumDirection
G4ThreeVector G4StepPoint::fMomentumDirection private
Definition at line 190 of file G4StepPoint.hh.
Referenced by operator=().
fpMaterial
G4Material* G4StepPoint::fpMaterial private
Definition at line 196 of file G4StepPoint.hh.
Referenced by operator=().
fpMaterialCutsCouple
const G4MaterialCutsCouple* G4StepPoint::fpMaterialCutsCouple private
Definition at line 198 of file G4StepPoint.hh.
Referenced by operator=().
fPolarization
G4ThreeVector G4StepPoint::fPolarization private
Definition at line 202 of file G4StepPoint.hh.
Referenced by operator=().
fPosition
G4ThreeVector G4StepPoint::fPosition private
Definition at line 183 of file G4StepPoint.hh.
Referenced by operator=().
fpProcessDefinedStep
const G4VProcess* G4StepPoint::fpProcessDefinedStep private
Definition at line 205 of file G4StepPoint.hh.
Referenced by operator=().
fProperTime
G4double G4StepPoint::fProperTime private
Definition at line 188 of file G4StepPoint.hh.
Referenced by operator=().
fpSensitiveDetector
G4VSensitiveDetector* G4StepPoint::fpSensitiveDetector private
Definition at line 200 of file G4StepPoint.hh.
Referenced by operator=().
fpTouchable
G4TouchableHandle G4StepPoint::fpTouchable private
Definition at line 194 of file G4StepPoint.hh.
Referenced by operator=().
fSafety
G4double G4StepPoint::fSafety private
Definition at line 201 of file G4StepPoint.hh.
Referenced by operator=().
fStepStatus
G4StepStatus G4StepPoint::fStepStatus private
Definition at line 203 of file G4StepPoint.hh.
Referenced by operator=().
fVelocity
G4double G4StepPoint::fVelocity private
Definition at line 192 of file G4StepPoint.hh.
Referenced by operator=().
fWeight
G4double G4StepPoint::fWeight private
Definition at line 213 of file G4StepPoint.hh.
Referenced by operator=().
The documentation for this class was generated from the following files:
source/track/include/G4StepPoint.hh
source/track/src/G4StepPoint.cc