Geant4: G4UserWorkerInitialization Class Reference
G4UserWorkerInitialization Class Reference
#include <G4UserWorkerInitialization.hh>
Public Member Functions
G4UserWorkerInitialization ()
virtual ~G4UserWorkerInitialization ()
virtual void WorkerInitialize () const
virtual void WorkerStart () const
virtual void WorkerRunStart () const
virtual void WorkerRunEnd () const
virtual void WorkerStop () const
Detailed Description
Definition at line 62 of file G4UserWorkerInitialization.hh.
Constructor & Destructor Documentation
G4UserWorkerInitialization()
G4UserWorkerInitialization::G4UserWorkerInitialization ()
Definition at line 28 of file G4UserWorkerInitialization.cc.
~G4UserWorkerInitialization()
G4UserWorkerInitialization::~G4UserWorkerInitialization () virtual
Definition at line 31 of file G4UserWorkerInitialization.cc.
Member Function Documentation
WorkerInitialize()
void G4UserWorkerInitialization::WorkerInitialize () const virtual
Reimplemented in RE05WorkerInitialization, and RE06WorkerInitialization.
Definition at line 34 of file G4UserWorkerInitialization.cc.
Referenced by tbbTask::execute(), and G4MTRunManagerKernel::StartThread().
WorkerRunEnd()
void G4UserWorkerInitialization::WorkerRunEnd () const virtual
Reimplemented in G4RTWorkerInitialization.
Definition at line 43 of file G4UserWorkerInitialization.cc.
Referenced by G4WorkerRunManager::RunTermination().
WorkerRunStart()
void G4UserWorkerInitialization::WorkerRunStart () const virtual
Reimplemented in G4RTWorkerInitialization.
Definition at line 40 of file G4UserWorkerInitialization.cc.
Referenced by G4WorkerRunManager::RunInitialization().
WorkerStart()
void G4UserWorkerInitialization::WorkerStart () const virtual
Definition at line 37 of file G4UserWorkerInitialization.cc.
Referenced by tbbTask::execute(), and G4MTRunManagerKernel::StartThread().
WorkerStop()
void G4UserWorkerInitialization::WorkerStop () const virtual
Definition at line 46 of file G4UserWorkerInitialization.cc.
Referenced by G4MTRunManagerKernel::StartThread().
The documentation for this class was generated from the following files:
source/run/include/G4UserWorkerInitialization.hh
source/run/src/G4UserWorkerInitialization.cc