Geant4: G4InteractionCase Class Reference
G4InteractionCase Class Reference
#include <G4InteractionCase.hh>
Public Member Functions
G4InteractionCase ()
G4InteractionCase (G4InuclParticle *part1, G4InuclParticle *part2)
void set (G4InuclParticle *part1, G4InuclParticle *part2)
void clear ()
G4InuclParticle * getBullet () const
G4InuclParticle * getTarget () const
G4bool valid () const
G4bool twoNuclei () const
G4bool hadNucleus () const
G4int hadrons () const
G4int code () const
Private Attributes
G4InuclParticle * bullet
G4InuclParticle * target
G4int inter_case
Detailed Description
Definition at line 39 of file G4InteractionCase.hh.
Constructor & Destructor Documentation
G4InteractionCase() [1/2]
G4InteractionCase::G4InteractionCase () inline
Definition at line 41 of file G4InteractionCase.hh.
G4InteractionCase() [2/2]
G4InteractionCase::G4InteractionCase (G4InuclParticle * part1, G4InuclParticle * part2) inline
Definition at line 43 of file G4InteractionCase.hh.
Member Function Documentation
clear()
void G4InteractionCase::clear (void) inline
Definition at line 49 of file G4InteractionCase.hh.
Referenced by set().
code()
G4int G4InteractionCase::code () const inline
Definition at line 64 of file G4InteractionCase.hh.
Referenced by G4InuclCollider::collide(), and G4IntraNucleiCascader::newCascade().
getBullet()
G4InuclParticle* G4InteractionCase::getBullet () const inline
Definition at line 54 of file G4InteractionCase.hh.
Referenced by G4InuclCollider::collide(), G4IntraNucleiCascader::finishCascade(), G4IntraNucleiCascader::generateCascade(), G4IntraNucleiCascader::initialize(), and G4InuclCollider::photonuclearOkay().
getTarget()
G4InuclParticle* G4InteractionCase::getTarget () const inline
Definition at line 55 of file G4InteractionCase.hh.
Referenced by G4InuclCollider::collide(), G4IntraNucleiCascader::finishCascade(), G4IntraNucleiCascader::generateCascade(), G4IntraNucleiCascader::initialize(), and G4InuclCollider::photonuclearOkay().
hadNucleus()
G4bool G4InteractionCase::hadNucleus () const inline
Definition at line 60 of file G4InteractionCase.hh.
Referenced by G4InuclCollider::collide(), and G4IntraNucleiCascader::setupCascade().
hadrons()
G4int G4InteractionCase::hadrons () const inline
Definition at line 61 of file G4InteractionCase.hh.
Referenced by G4ElementaryParticleCollider::collide(), and G4ElementaryParticleCollider::pionNucleonAbsorption().
set()
void G4InteractionCase::set (G4InuclParticle * part1, G4InuclParticle * part2)
Definition at line 38 of file G4InteractionCase.cc.
Referenced by G4InuclCollider::collide(), G4ElementaryParticleCollider::collide(), G4InteractionCase(), and G4IntraNucleiCascader::initialize().
twoNuclei()
G4bool G4InteractionCase::twoNuclei () const inline
Definition at line 59 of file G4InteractionCase.hh.
Referenced by G4InuclCollider::photonuclearOkay().
valid()
G4bool G4InteractionCase::valid () const inline
Definition at line 57 of file G4InteractionCase.hh.
Referenced by G4InuclCollider::collide().
Field Documentation
bullet
G4InuclParticle* G4InteractionCase::bullet private
Definition at line 67 of file G4InteractionCase.hh.
Referenced by clear(), getBullet(), and set().
inter_case
G4int G4InteractionCase::inter_case private
Definition at line 70 of file G4InteractionCase.hh.
Referenced by clear(), code(), hadNucleus(), hadrons(), set(), twoNuclei(), and valid().
target
G4InuclParticle* G4InteractionCase::target private
Definition at line 68 of file G4InteractionCase.hh.
Referenced by clear(), getTarget(), and set().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/cascade/cascade/include/G4InteractionCase.hh
source/processes/hadronic/models/cascade/cascade/src/G4InteractionCase.cc