Geant4: pyG4VUserPhysicsList Namespace Reference
pyG4VUserPhysicsList Namespace Reference
Data Structures
struct CB_G4VUserPhysicsList
Functions
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS (f_StorePhysicsTable, StorePhysicsTable, 0, 1) BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS(f_SetParticleCuts
Variables
void(G4VUserPhysicsList::* f1_SetCutValue)(G4double, const G4String &) = &G4VUserPhysicsList::SetCutValue
void(G4VUserPhysicsList::* f2_SetCutValue)(G4double, const G4String &, const G4String &) = &G4VUserPhysicsList::SetCutValue
void(G4VUserPhysicsList::* f1_SetParticleCuts)(G4double, G4ParticleDefinition *, G4Region *) = &G4VUserPhysicsList::SetParticleCuts
void(G4VUserPhysicsList::* f2_SetParticleCuts)(G4double, G4ParticleDefinition *, G4Region *) = &G4VUserPhysicsList::SetParticleCuts
SetParticleCuts
Function Documentation
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS()
pyG4VUserPhysicsList::BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS (f_StorePhysicsTable , StorePhysicsTable , 0 , 1)
Variable Documentation
f1_SetCutValue
void(G4VUserPhysicsList::* pyG4VUserPhysicsList::f1_SetCutValue) (G4double, const G4String &) = &G4VUserPhysicsList::SetCutValue
Definition at line 58 of file pyG4VUserPhysicsList.cc.
Referenced by export_G4VUserPhysicsList().
f1_SetParticleCuts
void(G4VUserPhysicsList::* pyG4VUserPhysicsList::f1_SetParticleCuts) (G4double, G4ParticleDefinition *, G4Region *) = &G4VUserPhysicsList::SetParticleCuts
Definition at line 65 of file pyG4VUserPhysicsList.cc.
Referenced by export_G4VUserPhysicsList().
f2_SetCutValue
void(G4VUserPhysicsList::* pyG4VUserPhysicsList::f2_SetCutValue) (G4double, const G4String &, const G4String &) = &G4VUserPhysicsList::SetCutValue
Definition at line 60 of file pyG4VUserPhysicsList.cc.
Referenced by export_G4VUserPhysicsList().
f2_SetParticleCuts
void(G4VUserPhysicsList::* pyG4VUserPhysicsList::f2_SetParticleCuts) (G4double, G4ParticleDefinition *, G4Region *) = &G4VUserPhysicsList::SetParticleCuts
Definition at line 69 of file pyG4VUserPhysicsList.cc.
Referenced by export_G4VUserPhysicsList().
SetParticleCuts
pyG4VUserPhysicsList::SetParticleCuts
Definition at line 79 of file pyG4VUserPhysicsList.cc.
Referenced by G4VUserPhysicsList::SetCutValue().