Geant4: G4RDVEnergySpectrum Class Reference
G4RDVEnergySpectrum Class Reference abstract
#include <G4RDVEnergySpectrum.hh>
Public Member Functions
G4RDVEnergySpectrum ()
virtual ~G4RDVEnergySpectrum ()
virtual G4double Probability (G4int Z, G4double minKineticEnergy, G4double maxKineticEnergy, G4double kineticEnergy, G4int shell=0, const G4ParticleDefinition *pd=0) const =0
virtual G4double AverageEnergy (G4int Z, G4double minKineticEnergy, G4double maxKineticEnergy, G4double kineticEnergy, G4int shell=0, const G4ParticleDefinition *pd=0) const =0
virtual G4double SampleEnergy (G4int Z, G4double minKineticEnergy, G4double maxKineticEnergy, G4double kineticEnergy, G4int shell=0, const G4ParticleDefinition *pd=0) const =0
virtual G4double MaxEnergyOfSecondaries (G4double kineticEnergy, G4int Z=0, const G4ParticleDefinition *pd=0) const =0
virtual G4double Excitation (G4int Z, G4double kineticEnergy) const =0
virtual void PrintData () const =0
Private Member Functions
G4RDVEnergySpectrum (const G4RDVEnergySpectrum &)
G4RDVEnergySpectrum & operator= (const G4RDVEnergySpectrum &right)
Detailed Description
Definition at line 59 of file G4RDVEnergySpectrum.hh.
Constructor & Destructor Documentation
G4RDVEnergySpectrum() [1/2]
G4RDVEnergySpectrum::G4RDVEnergySpectrum () inline
Definition at line 64 of file G4RDVEnergySpectrum.hh.
~G4RDVEnergySpectrum()
virtual G4RDVEnergySpectrum::~G4RDVEnergySpectrum () inline virtual
Definition at line 66 of file G4RDVEnergySpectrum.hh.
G4RDVEnergySpectrum() [2/2]
G4RDVEnergySpectrum::G4RDVEnergySpectrum (const G4RDVEnergySpectrum &) private
Member Function Documentation
AverageEnergy()
virtual G4double G4RDVEnergySpectrum::AverageEnergy (G4int Z, G4double minKineticEnergy, G4double maxKineticEnergy, G4double kineticEnergy, G4int shell = 0, const G4ParticleDefinition * pd = 0) const pure virtual
Implemented in G4RDeBremsstrahlungSpectrum, and G4RDeIonisationSpectrum.
Referenced by G4LowEnergyBremsstrahlung::BuildLossTable(), and G4LowEnergyIonisation::BuildLossTable().
Excitation()
virtual G4double G4RDVEnergySpectrum::Excitation (G4int Z, G4double kineticEnergy) const pure virtual
Implemented in G4RDeBremsstrahlungSpectrum, and G4RDeIonisationSpectrum.
Referenced by G4LowEnergyIonisation::BuildLossTable().
MaxEnergyOfSecondaries()
virtual G4double G4RDVEnergySpectrum::MaxEnergyOfSecondaries (G4double kineticEnergy, G4int Z = 0, const G4ParticleDefinition * pd = 0) const pure virtual
Implemented in G4RDeBremsstrahlungSpectrum, and G4RDeIonisationSpectrum.
Referenced by G4LowEnergyIonisation::PostStepDoIt().
operator=()
G4RDVEnergySpectrum& G4RDVEnergySpectrum::operator= (const G4RDVEnergySpectrum & right) private
PrintData()
virtual void G4RDVEnergySpectrum::PrintData () const pure virtual
Implemented in G4RDeBremsstrahlungSpectrum, and G4RDeIonisationSpectrum.
Referenced by G4LowEnergyIonisation::BuildPhysicsTable(), and G4LowEnergyBremsstrahlung::BuildPhysicsTable().
Probability()
virtual G4double G4RDVEnergySpectrum::Probability (G4int Z, G4double minKineticEnergy, G4double maxKineticEnergy, G4double kineticEnergy, G4int shell = 0, const G4ParticleDefinition * pd = 0) const pure virtual
Implemented in G4RDeBremsstrahlungSpectrum, and G4RDeIonisationSpectrum.
Referenced by G4RDBremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDeIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), and G4LowEnergyIonisation::BuildLossTable().
SampleEnergy()
virtual G4double G4RDVEnergySpectrum::SampleEnergy (G4int Z, G4double minKineticEnergy, G4double maxKineticEnergy, G4double kineticEnergy, G4int shell = 0, const G4ParticleDefinition * pd = 0) const pure virtual
Implemented in G4RDeBremsstrahlungSpectrum, and G4RDeIonisationSpectrum.
Referenced by G4LowEnergyIonisation::PostStepDoIt(), and G4LowEnergyBremsstrahlung::PostStepDoIt().
The documentation for this class was generated from the following file:
examples/advanced/eRosita/physics/include/G4RDVEnergySpectrum.hh