Geant4: G4FastSimulationVector< T > Class Template Reference
G4FastSimulationVector< T > Class Template Reference
#include <G4FastSimulationVector.hh>
Public Member Functions
G4FastSimulationVector ()
virtual ~G4FastSimulationVector ()
T * remove (const T *)
T * removeAt (G4int)
void clearAndDestroy ()
Private Types
typedef std::vector< T * > std_pvector
typedef std_pvector::iterator iterator
typedef std_pvector::const_iterator const_iterator
Detailed Description
template<class T>
class G4FastSimulationVector< T >
Definition at line 48 of file G4FastSimulationVector.hh.
Member Typedef Documentation
const_iterator
template<class T> typedef std_pvector::const_iterator G4FastSimulationVector< T >::const_iterator private
Definition at line 52 of file G4FastSimulationVector.hh.
iterator
template<class T> typedef std_pvector::iterator G4FastSimulationVector< T >::iterator private
Definition at line 51 of file G4FastSimulationVector.hh.
std_pvector
template<class T> typedef std::vector<T*> G4FastSimulationVector< T >::std_pvector private
Definition at line 50 of file G4FastSimulationVector.hh.
Constructor & Destructor Documentation
G4FastSimulationVector()
template<class T> G4FastSimulationVector< T >::G4FastSimulationVector () inline
Definition at line 56 of file G4FastSimulationVector.hh.
~G4FastSimulationVector()
template<class T> virtual G4FastSimulationVector< T >::~G4FastSimulationVector () inline virtual
Definition at line 59 of file G4FastSimulationVector.hh.
Member Function Documentation
clearAndDestroy()
template<class T> void G4FastSimulationVector< T >::clearAndDestroy ()
remove()
template<class T> T* G4FastSimulationVector< T >::remove (const T *)
Referenced by G4GlobalFastSimulationManager::RemoveFastSimulationManager(), G4FastSimulationManager::RemoveFastSimulationModel(), and G4GlobalFastSimulationManager::RemoveFSMP().
removeAt()
template<class T> T* G4FastSimulationVector< T >::removeAt (G4int)
Referenced by G4FastSimulationManager::ActivateFastSimulationModel(), and G4FastSimulationManager::InActivateFastSimulationModel().
The documentation for this class was generated from the following file:
source/processes/parameterisation/include/G4FastSimulationVector.hh