Geant4: G4PSDoseDeposit Class Reference
G4PSDoseDeposit Class Reference
#include <G4PSDoseDeposit.hh>
Public Member Functions
G4PSDoseDeposit (G4String name, G4int depth=0)
G4PSDoseDeposit (G4String name, const G4String &unit, G4int depth=0)
virtual ~G4PSDoseDeposit ()
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
virtual void SetUnit (const G4String &unit)
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Protected Member Functions
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
virtual G4double ComputeVolume (G4Step *, G4int idx)
Protected Member Functions inherited from G4VPrimitiveScorer
virtual G4int GetIndex (G4Step *)
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Private Attributes
G4int HCID
G4THitsMap< G4double > * EvtMap
Additional Inherited Members
Protected Attributes inherited from G4VPrimitiveScorer
G4String primitiveName
G4MultiFunctionalDetector * detector
G4VSDFilter * filter
G4int verboseLevel
G4int indexDepth
G4String unitName
G4double unitValue
G4int fNi
G4int fNj
G4int fNk
Detailed Description
Definition at line 44 of file G4PSDoseDeposit.hh.
Constructor & Destructor Documentation
G4PSDoseDeposit() [1/2]
G4PSDoseDeposit::G4PSDoseDeposit (G4String name, G4int depth = 0)
Definition at line 45 of file G4PSDoseDeposit.cc.
G4PSDoseDeposit() [2/2]
G4PSDoseDeposit::G4PSDoseDeposit (G4String name, const G4String & unit, G4int depth = 0)
Definition at line 51 of file G4PSDoseDeposit.cc.
~G4PSDoseDeposit()
G4PSDoseDeposit::~G4PSDoseDeposit () virtual
Definition at line 58 of file G4PSDoseDeposit.cc.
Member Function Documentation
clear()
void G4PSDoseDeposit::clear (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 91 of file G4PSDoseDeposit.cc.
ComputeVolume()
G4double G4PSDoseDeposit::ComputeVolume (G4Step * aStep, G4int idx) protected virtual
Reimplemented in G4PSDoseDepositForCylinder3D.
Definition at line 119 of file G4PSDoseDeposit.cc.
Referenced by ProcessHits().
DrawAll()
void G4PSDoseDeposit::DrawAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 96 of file G4PSDoseDeposit.cc.
EndOfEvent()
void G4PSDoseDeposit::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 88 of file G4PSDoseDeposit.cc.
Initialize()
void G4PSDoseDeposit::Initialize (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 80 of file G4PSDoseDeposit.cc.
PrintAll()
void G4PSDoseDeposit::PrintAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 99 of file G4PSDoseDeposit.cc.
ProcessHits()
G4bool G4PSDoseDeposit::ProcessHits (G4Step * aStep, G4TouchableHistory *) protected virtual
Implements G4VPrimitiveScorer.
Definition at line 61 of file G4PSDoseDeposit.cc.
SetUnit()
void G4PSDoseDeposit::SetUnit (const G4String & unit) virtual
Definition at line 114 of file G4PSDoseDeposit.cc.
Referenced by G4PSDoseDeposit(), and G4PSDoseDeposit3D::G4PSDoseDeposit3D().
Field Documentation
EvtMap
G4THitsMap<G4double>* G4PSDoseDeposit::EvtMap private
Definition at line 67 of file G4PSDoseDeposit.hh.
Referenced by clear(), Initialize(), PrintAll(), and ProcessHits().
HCID
G4int G4PSDoseDeposit::HCID private
Definition at line 66 of file G4PSDoseDeposit.hh.
Referenced by Initialize().
The documentation for this class was generated from the following files:
source/digits_hits/scorer/include/G4PSDoseDeposit.hh
source/digits_hits/scorer/src/G4PSDoseDeposit.cc