Geant4: G4CollisionManager Class Reference
G4CollisionManager Class Reference
#include <G4CollisionManager.hh>
Public Member Functions
G4CollisionManager ()
~G4CollisionManager ()
G4int Entries ()
void AddCollision (G4double time, G4KineticTrack *proj, G4KineticTrack *target=NULL)
void AddCollision (G4CollisionInitialState *collision)
void RemoveCollision (G4CollisionInitialState *collision)
void RemoveTracksCollisions (G4KineticTrackVector *ktv)
void ClearAndDestroy ()
G4CollisionInitialState * GetNextCollision ()
void Print ()
Private Member Functions
G4CollisionManager (const G4CollisionManager &)
G4CollisionManager & operator= (const G4CollisionManager &)
Private Attributes
G4ListOfCollisions * theCollisionList
Detailed Description
Definition at line 36 of file G4CollisionManager.hh.
Constructor & Destructor Documentation
G4CollisionManager() [1/2]
G4CollisionManager::G4CollisionManager ()
Definition at line 35 of file G4CollisionManager.cc.
~G4CollisionManager()
G4CollisionManager::~G4CollisionManager ()
Definition at line 41 of file G4CollisionManager.cc.
G4CollisionManager() [2/2]
G4CollisionManager::G4CollisionManager (const G4CollisionManager &) private
Member Function Documentation
AddCollision() [1/2]
void G4CollisionManager::AddCollision (G4CollisionInitialState * collision) inline
Definition at line 45 of file G4CollisionManager.hh.
AddCollision() [2/2]
void G4CollisionManager::AddCollision (G4double time, G4KineticTrack * proj, G4KineticTrack * target = NULL)
Definition at line 48 of file G4CollisionManager.cc.
Referenced by G4BinaryCascade::FindCollisions(), G4BinaryCascade::FindDecayCollision(), and G4BinaryCascade::FindLateParticleCollision().
ClearAndDestroy()
void G4CollisionManager::ClearAndDestroy ()
Definition at line 131 of file G4CollisionManager.cc.
Referenced by G4BinaryCascade::ApplyYourself(), G4BinaryCascade::Propagate(), and ~G4CollisionManager().
Entries()
G4int G4CollisionManager::Entries () inline
Definition at line 65 of file G4CollisionManager.hh.
Referenced by G4BinaryCascade::DoTimeStep(), G4BinaryCascade::FillVoidNucleusProducts(), G4BinaryCascade::Propagate(), and G4BinaryCascade::StepParticlesOut().
GetNextCollision()
G4CollisionInitialState * G4CollisionManager::GetNextCollision ()
Definition at line 140 of file G4CollisionManager.cc.
Referenced by G4BinaryCascade::DoTimeStep(), G4BinaryCascade::FillVoidNucleusProducts(), G4BinaryCascade::Propagate(), and G4BinaryCascade::StepParticlesOut().
operator=()
G4CollisionManager& G4CollisionManager::operator= (const G4CollisionManager &) private
Print()
void G4CollisionManager::Print (void)
Definition at line 175 of file G4CollisionManager.cc.
Referenced by G4BinaryCascade::ApplyCollision().
RemoveCollision()
void G4CollisionManager::RemoveCollision (G4CollisionInitialState * collision)
Definition at line 70 of file G4CollisionManager.cc.
Referenced by G4BinaryCascade::FillVoidNucleusProducts(), G4BinaryCascade::Propagate(), and G4BinaryCascade::StepParticlesOut().
RemoveTracksCollisions()
void G4CollisionManager::RemoveTracksCollisions (G4KineticTrackVector * ktv)
Definition at line 80 of file G4CollisionManager.cc.
Referenced by G4BinaryCascade::ApplyCollision(), and G4BinaryCascade::UpdateTracksAndCollisions().
Field Documentation
theCollisionList
G4ListOfCollisions* G4CollisionManager::theCollisionList private
Definition at line 60 of file G4CollisionManager.hh.
Referenced by AddCollision(), ClearAndDestroy(), Entries(), G4CollisionManager(), GetNextCollision(), Print(), RemoveCollision(), RemoveTracksCollisions(), and ~G4CollisionManager().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/im_r_matrix/include/G4CollisionManager.hh
source/processes/hadronic/models/im_r_matrix/src/G4CollisionManager.cc