Geant4: examples/advanced/composite_calorimeter/src/CCalutils.cc File Reference
CCalutils.cc File Reference
#include "CCalutils.hh"
#include "G4ios.hh"
#include "G4UnitsTable.hh"
#include <sstream>
Functions
G4String operator+ (const G4String &str, const int i)
G4String operator+ (const G4String &str, const double i)
std::ifstream & readName (std::ifstream &is, G4String &name)
std::ifstream & findDO (std::ifstream &is, const G4String &str)
std::ostream & tab (std::ostream &os)
std::istream & jump (std::istream &is)
bool openGeomFile (std::ifstream &is, const G4String &pathname, const G4String &filename)
Function Documentation
findDO()
std::ifstream& findDO (std::ifstream & is, const G4String & str)
Definition at line 72 of file CCalutils.cc.
Referenced by CCalMagneticField::CCalMagneticField(), CCalRotationMatrixFactory::CCalRotationMatrixFactory(), CCalMaterialFactory::readElements(), CCalHall::readFile(), CCalEcal::readFile(), CCalHcal::readFile(), and CCalMaterialFactory::readMaterials().
jump()
std::istream& jump (std::istream & is)
Definition at line 95 of file CCalutils.cc.
Referenced by CCalGeometryConfiguration::CCalGeometryConfiguration(), CCalSensitiveConfiguration::CCalSensitiveConfiguration(), CCalMaterialFactory::readElements(), CCalHall::readFile(), CCalEcal::readFile(), CCalHcal::readFile(), CCalVisualisable::readFile(), and CCalMaterialFactory::readMaterials().
openGeomFile()
bool openGeomFile (std::ifstream & is, const G4String & pathname, const G4String & filename)
Definition at line 116 of file CCalutils.cc.
Referenced by CCalGeometryConfiguration::CCalGeometryConfiguration(), CCalMagneticField::CCalMagneticField(), CCalRotationMatrixFactory::CCalRotationMatrixFactory(), CCalSensitiveConfiguration::CCalSensitiveConfiguration(), CCalMaterialFactory::readElements(), CCalHall::readFile(), CCalEcal::readFile(), CCalHcal::readFile(), CCalVisualisable::readFile(), and CCalMaterialFactory::readMaterials().
operator+() [1/2]
G4String operator+ (const G4String & str, const double i)
Definition at line 45 of file CCalutils.cc.
operator+() [2/2]
G4String operator+ (const G4String & str, const int i)
Definition at line 37 of file CCalutils.cc.
readName()
std::ifstream& readName (std::ifstream & is, G4String & name)
Definition at line 53 of file CCalutils.cc.
Referenced by CCalGeometryConfiguration::CCalGeometryConfiguration(), CCalSensitiveConfiguration::CCalSensitiveConfiguration(), CCalMaterialFactory::readElements(), CCalHall::readFile(), CCalEcal::readFile(), CCalHcal::readFile(), CCalVisualisable::readFile(), and CCalMaterialFactory::readMaterials().
tab()
std::ostream& tab (std::ostream & os)
Definition at line 89 of file CCalutils.cc.
Referenced by CCalGeometryConfiguration::CCalGeometryConfiguration(), CCalMagneticField::CCalMagneticField(), CCalSensitiveConfiguration::CCalSensitiveConfiguration(), G4PenelopeBremsstrahlungAngular::ClearTables(), CCalDetectorConstruction::Construct(), CCalG4Hcal::constructAbsorberLayer(), CCalG4Ecal::constructGlobal(), CCalG4Hall::constructIn(), CCalG4Hcal::constructIn(), CCalG4Ecal::constructIn(), CCalG4Hcal::constructScintillatorLayer(), CCalG4Able::PhysicalVolume(), CCalHall::readFile(), CCalEcal::readFile(), CCalHcal::readFile(), CCalVisualisable::readFile(), and CCalG4Able::setVisType().