Geant4: G4ITModelProcessor Class Reference
G4ITModelProcessor Class Reference
The G4ITModelProcessor will call the two processes defined in G4VITModel.
#include <G4ITModelProcessor.hh>
Public Member Functions
G4ITModelProcessor ()
virtual ~G4ITModelProcessor ()
void SetModelHandler (G4ITModelHandler *)
void Initialize ()
void RegisterModel (double time, G4VITStepModel *)
void CleanProcessor ()
Restore original state of the modelProcessor.
G4double CalculateMinTimeStep (G4double currentGlobalTime, G4double definedMinTimeStep)
void ComputeTrackReaction (G4ITStepStatus fITStepStatus, G4double fGlobalTime, G4double currentTimeStep, G4double previousTimeStep, G4bool reachedUserTimeLimit, G4double fTimeTolerance, G4UserTimeStepAction *fpUserTimeStepAction, G4int fVerbose)
void InitializeStepper (G4double currentGlobalTime, G4double userMinTime)
bool GetComputeTimeStep ()
void CalculateTimeStep (const G4Track *, const G4double)
void DoCalculateStep ()
void FindReaction (G4ITReactionSet *reactionSet, const double currentStepTime, const double previousStepTime, const bool reachedUserStepTimeLimit)
const std::vector< std::vector< G4VITStepModel * > > * GetCurrentModel ()
std::vector< G4ITReactionChange * > * GetReactionInfo ()
const G4Track * GetTrack () const
void SetTrackingManager (G4ITTrackingManager *trackingManager)
Protected Member Functions
void SetTrack (const G4Track *)
void ExtractTimeStepperData ()
G4ITModelProcessor (const G4ITModelProcessor &other)
Copy constructor.
G4ITModelProcessor & operator= (const G4ITModelProcessor &other)
Assignment operator.
Protected Attributes
G4double fTSTimeStep
G4ITReactionSet * fReactionSet
G4ITTrackingManager * fpTrackingManager
G4ITTrackHolder * fpTrackContainer
G4bool fInitialized
G4ITModelHandler * fpModelHandler
const G4Track * fpTrack
G4double fUserMinTimeStep
std::vector< std::vector< G4VITStepModel * > > fCurrentModel
G4VITStepModel * fpModel
G4ITModelManager * fpModelManager
G4ITType fCurrentType1
G4ITType fCurrentType2
std::vector< G4ITReactionChange * > fReactionInfo
bool fComputeTimeStep
bool fComputeReaction
Detailed Description
The G4ITModelProcessor will call the two processes defined in G4VITModel.
This processes act at the beginning and end of each step. The first one, the TimeStepper will calculate a time step to propagate all the track and eventually it can return some tracks that can likely react at the end of the step. The second one, the ReactionProcess will make the tracks reacting.
Definition at line 82 of file G4ITModelProcessor.hh.
Constructor & Destructor Documentation
G4ITModelProcessor() [1/2]
G4ITModelProcessor::G4ITModelProcessor ()
Definition at line 55 of file G4ITModelProcessor.cc.
~G4ITModelProcessor()
G4ITModelProcessor::~G4ITModelProcessor () virtual
Definition at line 77 of file G4ITModelProcessor.cc.
G4ITModelProcessor() [2/2]
G4ITModelProcessor::G4ITModelProcessor (const G4ITModelProcessor & other) protected
Copy constructor.
Parameters
other Object to copy from
Definition at line 86 of file G4ITModelProcessor.cc.
Member Function Documentation
CalculateMinTimeStep()
G4double G4ITModelProcessor::CalculateMinTimeStep (G4double currentGlobalTime, G4double definedMinTimeStep)
Definition at line 130 of file G4ITModelProcessor.cc.
Referenced by G4Scheduler::Stepping().
CalculateTimeStep()
void G4ITModelProcessor::CalculateTimeStep (const G4Track * track, const G4double userMinTimeStep)
Definition at line 396 of file G4ITModelProcessor.cc.
CleanProcessor()
void G4ITModelProcessor::CleanProcessor () inline
Restore original state of the modelProcessor.
This method should be call only by the G4Scheduler
Definition at line 228 of file G4ITModelProcessor.hh.
ComputeTrackReaction()
void G4ITModelProcessor::ComputeTrackReaction (G4ITStepStatus fITStepStatus, G4double fGlobalTime, G4double currentTimeStep, G4double previousTimeStep, G4bool reachedUserTimeLimit, G4double fTimeTolerance, G4UserTimeStepAction * fpUserTimeStepAction, G4int fVerbose)
Definition at line 438 of file G4ITModelProcessor.cc.
Referenced by G4Scheduler::Stepping().
DoCalculateStep()
void G4ITModelProcessor::DoCalculateStep ()
Definition at line 417 of file G4ITModelProcessor.cc.
ExtractTimeStepperData()
void G4ITModelProcessor::ExtractTimeStepperData () protected
Definition at line 209 of file G4ITModelProcessor.cc.
FindReaction()
void G4ITModelProcessor::FindReaction (G4ITReactionSet * reactionSet, const double currentStepTime, const double previousStepTime, const bool reachedUserStepTimeLimit)
Definition at line 621 of file G4ITModelProcessor.cc.
GetComputeTimeStep()
bool G4ITModelProcessor::GetComputeTimeStep () inline
Definition at line 117 of file G4ITModelProcessor.hh.
Referenced by G4Scheduler::Stepping().
GetCurrentModel()
const std::vector< std::vector< G4VITStepModel * > > * G4ITModelProcessor::GetCurrentModel () inline
Definition at line 210 of file G4ITModelProcessor.hh.
GetReactionInfo()
std::vector<G4ITReactionChange*>* G4ITModelProcessor::GetReactionInfo () inline
Definition at line 141 of file G4ITModelProcessor.hh.
GetTrack()
const G4Track* G4ITModelProcessor::GetTrack () const inline
Definition at line 146 of file G4ITModelProcessor.hh.
Initialize()
void G4ITModelProcessor::Initialize ()
Definition at line 116 of file G4ITModelProcessor.cc.
Referenced by G4Scheduler::Process().
InitializeStepper()
void G4ITModelProcessor::InitializeStepper (G4double currentGlobalTime, G4double userMinTime)
Definition at line 314 of file G4ITModelProcessor.cc.
operator=()
G4ITModelProcessor & G4ITModelProcessor::operator= (const G4ITModelProcessor & other) protected
Assignment operator.
Parameters
other Object to assign from
Returns
A reference to this
Definition at line 109 of file G4ITModelProcessor.cc.
RegisterModel()
void G4ITModelProcessor::RegisterModel (double time, G4VITStepModel * model)
Definition at line 103 of file G4ITModelProcessor.cc.
SetModelHandler()
void G4ITModelProcessor::SetModelHandler (G4ITModelHandler * modelHandler) inline
Definition at line 215 of file G4ITModelProcessor.hh.
Referenced by G4Scheduler::Initialize().
SetTrack()
void G4ITModelProcessor::SetTrack (const G4Track * track) inline protected
Definition at line 205 of file G4ITModelProcessor.hh.
SetTrackingManager()
void G4ITModelProcessor::SetTrackingManager (G4ITTrackingManager * trackingManager) inline
Definition at line 151 of file G4ITModelProcessor.hh.
Referenced by G4Scheduler::Initialize().
Field Documentation
fComputeReaction
bool G4ITModelProcessor::fComputeReaction protected
Definition at line 198 of file G4ITModelProcessor.hh.
fComputeTimeStep
bool G4ITModelProcessor::fComputeTimeStep protected
Definition at line 197 of file G4ITModelProcessor.hh.
Referenced by GetComputeTimeStep().
fCurrentModel
std::vector<std::vector<G4VITStepModel*> > G4ITModelProcessor::fCurrentModel protected
Definition at line 185 of file G4ITModelProcessor.hh.
Referenced by GetCurrentModel().
fCurrentType1
G4ITType G4ITModelProcessor::fCurrentType1 protected
Definition at line 192 of file G4ITModelProcessor.hh.
fCurrentType2
G4ITType G4ITModelProcessor::fCurrentType2 protected
Definition at line 193 of file G4ITModelProcessor.hh.
fInitialized
G4bool G4ITModelProcessor::fInitialized protected
Definition at line 177 of file G4ITModelProcessor.hh.
Referenced by SetModelHandler().
fpModel
G4VITStepModel* G4ITModelProcessor::fpModel protected
Definition at line 189 of file G4ITModelProcessor.hh.
fpModelHandler
G4ITModelHandler* G4ITModelProcessor::fpModelHandler protected
Definition at line 178 of file G4ITModelProcessor.hh.
Referenced by SetModelHandler().
fpModelManager
G4ITModelManager* G4ITModelProcessor::fpModelManager protected
Definition at line 190 of file G4ITModelProcessor.hh.
fpTrack
const G4Track* G4ITModelProcessor::fpTrack protected
Definition at line 180 of file G4ITModelProcessor.hh.
Referenced by CleanProcessor(), GetTrack(), and SetTrack().
fpTrackContainer
G4ITTrackHolder* G4ITModelProcessor::fpTrackContainer protected
Definition at line 175 of file G4ITModelProcessor.hh.
fpTrackingManager
G4ITTrackingManager* G4ITModelProcessor::fpTrackingManager protected
Definition at line 174 of file G4ITModelProcessor.hh.
Referenced by SetTrackingManager().
fReactionInfo
std::vector<G4ITReactionChange*> G4ITModelProcessor::fReactionInfo protected
Definition at line 195 of file G4ITModelProcessor.hh.
Referenced by GetReactionInfo().
fReactionSet
G4ITReactionSet* G4ITModelProcessor::fReactionSet protected
Definition at line 173 of file G4ITModelProcessor.hh.
fTSTimeStep
G4double G4ITModelProcessor::fTSTimeStep protected
Definition at line 172 of file G4ITModelProcessor.hh.
fUserMinTimeStep
G4double G4ITModelProcessor::fUserMinTimeStep protected
Definition at line 181 of file G4ITModelProcessor.hh.
The documentation for this class was generated from the following files:
source/processes/electromagnetic/dna/management/include/G4ITModelProcessor.hh
source/processes/electromagnetic/dna/management/src/G4ITModelProcessor.cc