Geant4: G4Cerenkov Class Reference
G4Cerenkov Class Reference
#include <G4Cerenkov.hh>
Public Member Functions
G4Cerenkov (const G4String &processName="Cerenkov", G4ProcessType type=fElectromagnetic)
~G4Cerenkov ()
G4Cerenkov (const G4Cerenkov &right)
G4bool IsApplicable (const G4ParticleDefinition &aParticleType) override
void BuildPhysicsTable (const G4ParticleDefinition &aParticleType) override
G4double GetMeanFreePath (const G4Track &aTrack, G4double, G4ForceCondition *)
G4double PostStepGetPhysicalInteractionLength (const G4Track &aTrack, G4double, G4ForceCondition *) override
G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep) override
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *) override
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *) override
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &) override
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &) override
void SetTrackSecondariesFirst (const G4bool state)
G4bool GetTrackSecondariesFirst () const
void SetMaxBetaChangePerStep (const G4double d)
G4double GetMaxBetaChangePerStep () const
void SetMaxNumPhotonsPerStep (const G4int NumPhotons)
G4int GetMaxNumPhotonsPerStep () const
void SetStackPhotons (const G4bool)
G4bool GetStackPhotons () const
G4int GetNumPhotons () const
G4PhysicsTable * GetPhysicsTable () const
void DumpPhysicsTable () const
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Attributes
G4PhysicsTable * thePhysicsTable
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Private Member Functions
G4Cerenkov & operator= (const G4Cerenkov &right)=delete
void BuildThePhysicsTable ()
G4double GetAverageNumberOfPhotons (const G4double charge, const G4double beta, const G4Material *aMaterial, G4MaterialPropertyVector *Rindex) const
Private Attributes
G4bool fTrackSecondariesFirst
G4double fMaxBetaChange
G4int fMaxPhotons
G4bool fStackingFlag
G4int fNumPhotons
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Detailed Description
Definition at line 80 of file G4Cerenkov.hh.
Constructor & Destructor Documentation
G4Cerenkov() [1/2]
G4Cerenkov::G4Cerenkov (const G4String & processName = "Cerenkov", G4ProcessType type = fElectromagnetic) explicit
Definition at line 95 of file G4Cerenkov.cc.
~G4Cerenkov()
G4Cerenkov::~G4Cerenkov ()
Definition at line 120 of file G4Cerenkov.cc.
G4Cerenkov() [2/2]
G4Cerenkov::G4Cerenkov (const G4Cerenkov & right) explicit
Member Function Documentation
AlongStepDoIt()
virtual G4VParticleChange* G4Cerenkov::AlongStepDoIt (const G4Track & , const G4Step &) inline override virtual
Implements G4VProcess.
Definition at line 147 of file G4Cerenkov.hh.
AlongStepGetPhysicalInteractionLength()
virtual G4double G4Cerenkov::AlongStepGetPhysicalInteractionLength (const G4Track & , G4double , G4double , G4double & , G4GPILSelection *) inline override virtual
Implements G4VProcess.
Definition at line 132 of file G4Cerenkov.hh.
AtRestDoIt()
virtual G4VParticleChange* G4Cerenkov::AtRestDoIt (const G4Track & , const G4Step &) inline override virtual
Implements G4VProcess.
Definition at line 144 of file G4Cerenkov.hh.
AtRestGetPhysicalInteractionLength()
virtual G4double G4Cerenkov::AtRestGetPhysicalInteractionLength (const G4Track & , G4ForceCondition *) inline override virtual
Implements G4VProcess.
Definition at line 139 of file G4Cerenkov.hh.
BuildPhysicsTable()
void G4Cerenkov::BuildPhysicsTable (const G4ParticleDefinition & aParticleType) override virtual
Reimplemented from G4VProcess.
Definition at line 159 of file G4Cerenkov.cc.
BuildThePhysicsTable()
void G4Cerenkov::BuildThePhysicsTable () private
Definition at line 390 of file G4Cerenkov.cc.
Referenced by BuildPhysicsTable().
DumpPhysicsTable()
void G4Cerenkov::DumpPhysicsTable () const
Definition at line 686 of file G4Cerenkov.cc.
GetAverageNumberOfPhotons()
G4double G4Cerenkov::GetAverageNumberOfPhotons (const G4double charge, const G4double beta, const G4Material * aMaterial, G4MaterialPropertyVector * Rindex) const private
Definition at line 606 of file G4Cerenkov.cc.
Referenced by PostStepDoIt(), and PostStepGetPhysicalInteractionLength().
GetMaxBetaChangePerStep()
G4double G4Cerenkov::GetMaxBetaChangePerStep () const inline
Definition at line 238 of file G4Cerenkov.hh.
GetMaxNumPhotonsPerStep()
G4int G4Cerenkov::GetMaxNumPhotonsPerStep () const inline
Definition at line 244 of file G4Cerenkov.hh.
GetMeanFreePath()
G4double G4Cerenkov::GetMeanFreePath (const G4Track & aTrack, G4double , G4ForceCondition *)
Definition at line 484 of file G4Cerenkov.cc.
GetNumPhotons()
G4int G4Cerenkov::GetNumPhotons () const inline
Definition at line 262 of file G4Cerenkov.hh.
GetPhysicsTable()
G4PhysicsTable * G4Cerenkov::GetPhysicsTable () const inline
Definition at line 268 of file G4Cerenkov.hh.
GetStackPhotons()
G4bool G4Cerenkov::GetStackPhotons () const inline
Definition at line 256 of file G4Cerenkov.hh.
GetTrackSecondariesFirst()
G4bool G4Cerenkov::GetTrackSecondariesFirst () const inline
Definition at line 232 of file G4Cerenkov.hh.
IsApplicable()
G4bool G4Cerenkov::IsApplicable (const G4ParticleDefinition & aParticleType) override virtual
Reimplemented from G4VProcess.
Definition at line 132 of file G4Cerenkov.cc.
Referenced by OpNovicePhysicsList::ConstructOp(), WLSOpticalPhysics::ConstructProcess(), and G4OpticalPhysics::ConstructProcess().
operator=()
G4Cerenkov& G4Cerenkov::operator= (const G4Cerenkov & right) private delete
PostStepDoIt()
G4VParticleChange * G4Cerenkov::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) override virtual
Implements G4VProcess.
Definition at line 168 of file G4Cerenkov.cc.
PostStepGetPhysicalInteractionLength()
G4double G4Cerenkov::PostStepGetPhysicalInteractionLength (const G4Track & aTrack, G4double , G4ForceCondition * condition) override virtual
Implements G4VProcess.
Definition at line 491 of file G4Cerenkov.cc.
SetMaxBetaChangePerStep()
void G4Cerenkov::SetMaxBetaChangePerStep (const G4double d)
Definition at line 149 of file G4Cerenkov.cc.
Referenced by OpNovicePhysicsList::ConstructOp(), G4OpticalPhysics::ConstructProcess(), and G4OpticalPhysics::SetMaxBetaChangePerStep().
SetMaxNumPhotonsPerStep()
void G4Cerenkov::SetMaxNumPhotonsPerStep (const G4int NumPhotons)
Definition at line 154 of file G4Cerenkov.cc.
Referenced by OpNovicePhysicsList::ConstructOp(), WLSOpticalPhysics::ConstructProcess(), G4OpticalPhysics::ConstructProcess(), G4OpticalPhysics::SetMaxNumPhotonsPerStep(), WLSOpticalPhysics::SetNbOfPhotonsCerenkov(), and OpNovicePhysicsList::SetNbOfPhotonsCerenkov().
SetStackPhotons()
void G4Cerenkov::SetStackPhotons (const G4bool stackingFlag) inline
Definition at line 250 of file G4Cerenkov.hh.
Referenced by G4OpticalPhysics::ConstructProcess(), and G4OpticalPhysics::SetCerenkovStackPhotons().
SetTrackSecondariesFirst()
void G4Cerenkov::SetTrackSecondariesFirst (const G4bool state)
Definition at line 144 of file G4Cerenkov.cc.
Referenced by OpNovicePhysicsList::ConstructOp(), WLSOpticalPhysics::ConstructProcess(), and G4OpticalPhysics::ConstructProcess().
Field Documentation
fMaxBetaChange
G4double G4Cerenkov::fMaxBetaChange private
Definition at line 219 of file G4Cerenkov.hh.
Referenced by GetMaxBetaChangePerStep(), PostStepGetPhysicalInteractionLength(), and SetMaxBetaChangePerStep().
fMaxPhotons
G4int G4Cerenkov::fMaxPhotons private
Definition at line 220 of file G4Cerenkov.hh.
Referenced by GetMaxNumPhotonsPerStep(), PostStepGetPhysicalInteractionLength(), and SetMaxNumPhotonsPerStep().
fNumPhotons
G4int G4Cerenkov::fNumPhotons private
Definition at line 224 of file G4Cerenkov.hh.
Referenced by GetNumPhotons(), PostStepDoIt(), and PostStepGetPhysicalInteractionLength().
fStackingFlag
G4bool G4Cerenkov::fStackingFlag private
Definition at line 222 of file G4Cerenkov.hh.
Referenced by GetStackPhotons(), PostStepDoIt(), and SetStackPhotons().
fTrackSecondariesFirst
G4bool G4Cerenkov::fTrackSecondariesFirst private
Definition at line 218 of file G4Cerenkov.hh.
Referenced by GetTrackSecondariesFirst(), PostStepDoIt(), and SetTrackSecondariesFirst().
thePhysicsTable
G4PhysicsTable* G4Cerenkov::thePhysicsTable protected
Definition at line 211 of file G4Cerenkov.hh.
Referenced by BuildPhysicsTable(), BuildThePhysicsTable(), DumpPhysicsTable(), G4Cerenkov(), GetAverageNumberOfPhotons(), GetPhysicsTable(), PostStepGetPhysicalInteractionLength(), and ~G4Cerenkov().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/xrays/include/G4Cerenkov.hh
source/processes/electromagnetic/xrays/src/G4Cerenkov.cc