Geant4: source/processes/hadronic/models/lend/src/xDataTOM.cc File Reference
xDataTOM.cc File Reference
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <errno.h>
#include <unistd.h>
#include "xDataTOM_importXML_private.h"
#include "xDataTOM_private.h"
Macros
#define PATH_MAX 4096
Functions
static int xDataTOME_initializeElement (statusMessageReporting *smr, xDataTOM_element *element, xDataTOM_element *parent, int ordinal, int index, char const *name)
static void xDataTOME_displayTree (statusMessageReporting *smr, xDataTOM_element *element, int printAttributes, int level)
static int xDataTOM_initialize_xData (statusMessageReporting *smr, xDataTOM_xDataInfo *xDataInfo)
xDataTOM_TOM * xDataTOM_importFile (statusMessageReporting *smr, const char *fileName)
xDataTOM_TOM * xDataTOM_mallocTOM (statusMessageReporting *smr)
int xDataTOM_initializeTOM (statusMessageReporting *smr, xDataTOM_TOM *TOM)
void * xDataTOM_freeTOM (statusMessageReporting *, xDataTOM_TOM **TOM)
int xDataTOM_setFileNameTOM (statusMessageReporting *smr, xDataTOM_TOM *TOM, const char *fileName)
void xDataTOM_displayTree (statusMessageReporting *smr, xDataTOM_TOM *TOM, int printAttributes)
xDataTOM_element * xDataTOM_mallocElement (statusMessageReporting *smr, xDataTOM_element *parent, int ordinal, int index, char const *name)
void xDataTOM_freeElement (xDataTOM_element **element)
void xDataTOM_releaseElement (xDataTOM_element *element)
xDataTOM_element * xDataTOM_addElementInElement (statusMessageReporting *smr, xDataTOM_element *parent, int index, char const *name)
xDataTOM_element * xDataTOM_getDocumentsElement (xDataTOM_TOM *TOM)
xDataTOM_element * xDataTOME_getFirstElement (xDataTOM_element *element)
xDataTOM_element * xDataTOME_getNextElement (xDataTOM_element *element)
xDataTOM_element * xDataTOME_getOneElementByName (statusMessageReporting *smr, xDataTOM_element *element, char const *name, int required)
int xDataTOM_numberOfElementsByName (statusMessageReporting *, xDataTOM_element *element, char const *name)
int xDataTOME_addAttribute (statusMessageReporting *smr, xDataTOM_element *element, char const *name, char const *value)
const char * xDataTOM_getAttributesValueInElement (xDataTOM_element *element, char const *name)
int xDataTOME_copyAttributionList (statusMessageReporting *smr, xDataTOM_attributionList *desc, xDataTOM_element *element)
int xDataTOME_convertAttributeToInteger (statusMessageReporting *smr, xDataTOM_element *element, char const *name, int *n)
int xDataTOME_convertAttributeToDouble (statusMessageReporting *smr, xDataTOM_element *element, char const *name, double *d)
int xDataTOME_getInterpolation (statusMessageReporting *smr, xDataTOM_element *element, int index, enum xDataTOM_interpolationFlag *independent, enum xDataTOM_interpolationFlag *dependent, enum xDataTOM_interpolationQualifier *qualifier)
void xDataTOMAL_initial (statusMessageReporting *, xDataTOM_attributionList *attributes)
void xDataTOMAL_release (xDataTOM_attributionList *attributes)
int xDataTOMAL_addAttribute (statusMessageReporting *smr, xDataTOM_attributionList *attributes, char const *name, char const *value)
const char * xDataTOMAL_getAttributesValue (xDataTOM_attributionList *attributes, char const *name)
int xDataTOMAL_copyAttributionList (statusMessageReporting *smr, xDataTOM_attributionList *desc, xDataTOM_attributionList *src)
int xDataTOMAL_convertAttributeToInteger (statusMessageReporting *smr, xDataTOM_attributionList *attributes, char const *name, int *n)
int xDataTOMAL_convertAttributeToDouble (statusMessageReporting *smr, xDataTOM_attributionList *attributes, char const *name, double *d)
void * xData_initializeData (statusMessageReporting *smr, xDataTOM_element *TE, char const *ID, size_t size)
int xDataTOM_isXDataID (xDataTOM_element *TE, char const *ID)
xDataTOM_xDataInfo * xDataTOME_getXData (xDataTOM_element *TE)
void * xDataTOME_getXDataIfID (statusMessageReporting *smr, xDataTOM_element *TE, char const *ID)
Variables
int xDataTOM_smrLibraryID = smr_unknownID
Macro Definition Documentation
PATH_MAX
#define PATH_MAX 4096
Definition at line 31 of file xDataTOM.cc.
Function Documentation
xData_initializeData()
void* xData_initializeData (statusMessageReporting * smr, xDataTOM_element * TE, char const * ID, size_t size)
Definition at line 476 of file xDataTOM.cc.
Referenced by xDataXML_initializeData().
xDataTOM_addElementInElement()
xDataTOM_element* xDataTOM_addElementInElement (statusMessageReporting * smr, xDataTOM_element * parent, int index, char const * name)
Definition at line 187 of file xDataTOM.cc.
Referenced by xDataXML_constructTOM().
xDataTOM_displayTree()
void xDataTOM_displayTree (statusMessageReporting * smr, xDataTOM_TOM * TOM, int printAttributes)
Definition at line 114 of file xDataTOM.cc.
xDataTOM_freeElement()
void xDataTOM_freeElement (xDataTOM_element ** element)
Definition at line 138 of file xDataTOM.cc.
Referenced by xDataTOM_releaseElement().
xDataTOM_freeTOM()
void* xDataTOM_freeTOM (statusMessageReporting * , xDataTOM_TOM ** TOM)
Definition at line 78 of file xDataTOM.cc.
Referenced by MCGIDI_target_heated_read(), and xDataXML_importFile().
xDataTOM_getAttributesValueInElement()
const char* xDataTOM_getAttributesValueInElement (xDataTOM_element * element, char const * name)
Definition at line 285 of file xDataTOM.cc.
Referenced by MCGIDI_angular_parseFromTOM(), MCGIDI_angularEnergy_parseFromTOM(), MCGIDI_distribution_parseFromTOM(), MCGIDI_energy_parseEvaporationFromTOM(), MCGIDI_energy_parseFromTOM(), MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_energy_parseNBodyPhaseSpaceFromTOM(), MCGIDI_energy_parseSimpleMaxwellianFissionFromTOM(), MCGIDI_energy_parseWattFromTOM(), MCGIDI_energyAngular_parseFromTOM(), MCGIDI_LLNL_angularEnergy_parseFromTOM(), MCGIDI_misc_getProductFrame(), MCGIDI_outputChannel_parseFromTOM(), MCGIDI_product_parseFromTOM(), MCGIDI_product_parseWeightedReferenceMultiplicityFromTOM(), MCGIDI_reaction_parseFromTOM(), MCGIDI_target_heated_parseParticle(), MCGIDI_target_heated_parseParticleGammas(), MCGIDI_target_heated_parseParticleLevel(), MCGIDI_target_heated_parseReaction(), MCGIDI_target_heated_read(), and xDataTOM_getLinksElement2().
xDataTOM_getDocumentsElement()
xDataTOM_element* xDataTOM_getDocumentsElement (xDataTOM_TOM * TOM)
Definition at line 222 of file xDataTOM.cc.
Referenced by MCGIDI_target_heated_read().
xDataTOM_importFile()
xDataTOM_TOM* xDataTOM_importFile (statusMessageReporting * smr, const char * fileName)
Definition at line 44 of file xDataTOM.cc.
Referenced by MCGIDI_target_heated_read().
xDataTOM_initialize_xData()
static int xDataTOM_initialize_xData (statusMessageReporting * smr, xDataTOM_xDataInfo * xDataInfo) static
Definition at line 469 of file xDataTOM.cc.
Referenced by xDataTOME_initializeElement().
xDataTOM_initializeTOM()
int xDataTOM_initializeTOM (statusMessageReporting * smr, xDataTOM_TOM * TOM)
Definition at line 68 of file xDataTOM.cc.
Referenced by xDataTOM_mallocTOM().
xDataTOM_isXDataID()
int xDataTOM_isXDataID (xDataTOM_element * TE, char const * ID)
Definition at line 488 of file xDataTOM.cc.
xDataTOM_mallocElement()
xDataTOM_element* xDataTOM_mallocElement (statusMessageReporting * smr, xDataTOM_element * parent, int ordinal, int index, char const * name)
Definition at line 124 of file xDataTOM.cc.
Referenced by xDataTOM_addElementInElement().
xDataTOM_mallocTOM()
xDataTOM_TOM* xDataTOM_mallocTOM (statusMessageReporting * smr)
Definition at line 54 of file xDataTOM.cc.
Referenced by xDataXML_importFile().
xDataTOM_numberOfElementsByName()
int xDataTOM_numberOfElementsByName (statusMessageReporting * , xDataTOM_element * element, char const * name)
Definition at line 267 of file xDataTOM.cc.
Referenced by MCGIDI_outputChannel_parseFromTOM(), and MCGIDI_target_heated_read().
xDataTOM_releaseElement()
void xDataTOM_releaseElement (xDataTOM_element * element)
Definition at line 147 of file xDataTOM.cc.
Referenced by xDataTOM_freeElement(), and xDataTOM_freeTOM().
xDataTOM_setFileNameTOM()
int xDataTOM_setFileNameTOM (statusMessageReporting * smr, xDataTOM_TOM * TOM, const char * fileName)
Definition at line 94 of file xDataTOM.cc.
Referenced by xDataXML_importFile().
xDataTOMAL_addAttribute()
int xDataTOMAL_addAttribute (statusMessageReporting * smr, xDataTOM_attributionList * attributes, char const * name, char const * value)
Definition at line 374 of file xDataTOM.cc.
Referenced by MCGIDI_misc_copyXMLAttributesToTOM(), xDataTOMAL_copyAttributionList(), and xDataTOME_addAttribute().
xDataTOMAL_convertAttributeToDouble()
int xDataTOMAL_convertAttributeToDouble (statusMessageReporting * smr, xDataTOM_attributionList * attributes, char const * name, double * d)
Definition at line 448 of file xDataTOM.cc.
Referenced by xDataTOME_convertAttributeToDouble().
xDataTOMAL_convertAttributeToInteger()
int xDataTOMAL_convertAttributeToInteger (statusMessageReporting * smr, xDataTOM_attributionList * attributes, char const * name, int * n)
Definition at line 431 of file xDataTOM.cc.
Referenced by xDataTOME_convertAttributeToInteger().
xDataTOMAL_copyAttributionList()
int xDataTOMAL_copyAttributionList (statusMessageReporting * smr, xDataTOM_attributionList * desc, xDataTOM_attributionList * src)
Definition at line 413 of file xDataTOM.cc.
Referenced by MCGIDI_target_heated_read(), and xDataTOME_copyAttributionList().
xDataTOMAL_getAttributesValue()
const char* xDataTOMAL_getAttributesValue (xDataTOM_attributionList * attributes, char const * name)
Definition at line 401 of file xDataTOM.cc.
Referenced by MCGIDI_misc_pointerToAttributeIfAllOk(), MCGIDI_misc_pointerToTOMAttributeIfAllOk(), MCGIDI_target_getAttributesValue(), xDataTOM_getAttributesValueInElement(), xDataTOMAL_convertAttributeToDouble(), and xDataTOMAL_convertAttributeToInteger().
xDataTOMAL_initial()
void xDataTOMAL_initial (statusMessageReporting * , xDataTOM_attributionList * attributes)
Definition at line 351 of file xDataTOM.cc.
Referenced by MCGIDI_misc_copyXMLAttributesToTOM(), MCGIDI_reaction_initialize2(), xDataTOMAL_copyAttributionList(), xDataTOMAL_release(), and xDataTOME_initializeElement().
xDataTOMAL_release()
void xDataTOMAL_release (xDataTOM_attributionList * attributes)
Definition at line 359 of file xDataTOM.cc.
Referenced by MCGIDI_misc_copyXMLAttributesToTOM(), MCGIDI_reaction_release(), MCGIDI_target_heated_release(), MCGIDI_target_release(), xDataTOM_releaseElement(), and xDataTOMAL_copyAttributionList().
xDataTOME_addAttribute()
int xDataTOME_addAttribute (statusMessageReporting * smr, xDataTOM_element * element, char const * name, char const * value)
Definition at line 278 of file xDataTOM.cc.
Referenced by xDataXML_constructTOM().
xDataTOME_convertAttributeToDouble()
int xDataTOME_convertAttributeToDouble (statusMessageReporting * smr, xDataTOM_element * element, char const * name, double * d)
Definition at line 306 of file xDataTOM.cc.
Referenced by MCGIDI_target_heated_parseParticleGammas().
xDataTOME_convertAttributeToInteger()
int xDataTOME_convertAttributeToInteger (statusMessageReporting * smr, xDataTOM_element * element, char const * name, int * n)
Definition at line 299 of file xDataTOM.cc.
Referenced by MCGIDI_energy_parseNBodyPhaseSpaceFromTOM(), MCGIDI_product_parseFromTOM(), and MCGIDI_reaction_parseFromTOM().
xDataTOME_copyAttributionList()
int xDataTOME_copyAttributionList (statusMessageReporting * smr, xDataTOM_attributionList * desc, xDataTOM_element * element)
Definition at line 292 of file xDataTOM.cc.
Referenced by MCGIDI_reaction_parseFromTOM().
xDataTOME_displayTree()
static void xDataTOME_displayTree (statusMessageReporting * smr, xDataTOM_element * element, int printAttributes, int level) static
Definition at line 325 of file xDataTOM.cc.
Referenced by xDataTOM_displayTree().
xDataTOME_getFirstElement()
xDataTOM_element* xDataTOME_getFirstElement (xDataTOM_element * element)
Definition at line 229 of file xDataTOM.cc.
Referenced by MCGIDI_energy_parseWeightedFunctionalsFromTOM(), MCGIDI_energy_parseWeightFromTOM(), MCGIDI_outputChannel_parseFromTOM(), MCGIDI_target_heated_parseParticle(), MCGIDI_target_heated_parseParticleGammas(), MCGIDI_target_heated_parseParticleLevel(), MCGIDI_target_heated_parsePOPs(), MCGIDI_target_heated_read(), xDataTOM_numberOfElementsByName(), xDataTOME_displayTree(), and xDataTOME_getOneElementByName().
xDataTOME_getInterpolation()
int xDataTOME_getInterpolation (statusMessageReporting * smr, xDataTOM_element * element, int index, enum xDataTOM_interpolationFlag * independent, enum xDataTOM_interpolationFlag * dependent, enum xDataTOM_interpolationQualifier * qualifier)
Definition at line 313 of file xDataTOM.cc.
Referenced by MCGIDI_fromTOM_interpolation(), and MCGIDI_reaction_parseFromTOM().
xDataTOME_getNextElement()
xDataTOM_element* xDataTOME_getNextElement (xDataTOM_element * element)
Definition at line 237 of file xDataTOM.cc.
Referenced by MCGIDI_energy_parseWeightedFunctionalsFromTOM(), MCGIDI_energy_parseWeightFromTOM(), MCGIDI_outputChannel_parseFromTOM(), MCGIDI_target_heated_parseParticle(), MCGIDI_target_heated_parseParticleGammas(), MCGIDI_target_heated_parseParticleLevel(), MCGIDI_target_heated_parsePOPs(), MCGIDI_target_heated_read(), xDataTOM_numberOfElementsByName(), xDataTOME_displayTree(), and xDataTOME_getOneElementByName().
xDataTOME_getOneElementByName()
xDataTOM_element* xDataTOME_getOneElementByName (statusMessageReporting * smr, xDataTOM_element * element, char const * name, int required)
Definition at line 245 of file xDataTOM.cc.
Referenced by MCGIDI_angular_parseFromTOM(), MCGIDI_angularEnergy_parseFromTOM(), MCGIDI_distribution_parseFromTOM(), MCGIDI_energy_parseEvaporationFromTOM(), MCGIDI_energy_parseFromTOM(), MCGIDI_energy_parseGeneralEvaporationFromTOM(), MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_energy_parseSimpleMaxwellianFissionFromTOM(), MCGIDI_energy_parseWattFromTOM(), MCGIDI_energyAngular_linear_parseFromTOM(), MCGIDI_energyAngular_parseFromTOM(), MCGIDI_KalbachMann_parseFromTOM(), MCGIDI_LLNL_angularEnergy_parseFromTOM(), MCGIDI_LLNLAngular_angularEnergy_parseFromTOM(), MCGIDI_product_parseFromTOM(), MCGIDI_product_parseWeightedReferenceMultiplicityFromTOM(), MCGIDI_reaction_parseFromTOM(), MCGIDI_target_heated_read(), and MCGIDI_uncorrelated_parseFromTOM().
xDataTOME_getXData()
xDataTOM_xDataInfo* xDataTOME_getXData (xDataTOM_element * TE)
Definition at line 501 of file xDataTOM.cc.
Referenced by xDataTOME_getXDataIfID().
xDataTOME_getXDataIfID()
void* xDataTOME_getXDataIfID (statusMessageReporting * smr, xDataTOM_element * TE, char const * ID)
Definition at line 509 of file xDataTOM.cc.
Referenced by MCGIDI_angular_parseFromTOM(), MCGIDI_angularEnergy_parsePointwiseFromTOM(), MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_energyAngular_linear_parseFromTOM(), MCGIDI_fromTOM_pdfsOfXGivenW(), and MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM().
xDataTOME_initializeElement()
static int xDataTOME_initializeElement (statusMessageReporting * smr, xDataTOM_element * element, xDataTOM_element * parent, int ordinal, int index, char const * name) static
Definition at line 206 of file xDataTOM.cc.
Referenced by xDataTOM_initializeTOM(), and xDataTOM_mallocElement().
Variable Documentation
xDataTOM_smrLibraryID
int xDataTOM_smrLibraryID = smr_unknownID
Definition at line 34 of file xDataTOM.cc.
Referenced by xDataTOM_axes_getInterpolation(), xDataTOM_axes_getLabel(), xDataTOM_axes_getUnit(), xDataTOM_interpolation_getFromString(), xDataTOM_interpolation_set(), xDataTOM_interpolation_setFromString(), xDataTOM_setMessageError_ReturnInt(), xDataTOM_subAxes_initialize(), xDataTOMAL_convertAttributeToDouble(), xDataTOMAL_convertAttributeToInteger(), xDataTOME_getXDataIfID(), xDataTOMMisc_getAbsPath(), xDataXML_addElementToRoot(), xDataXML_axesElememtToTOM(), xDataXML_axesToTOM(), xDataXML_constructTOM(), xDataXML_convertAttributeTo_xDataTOM_Int(), xDataXML_convertAttributeToDouble(), xDataXML_endXMLParsing(), xDataXML_getCommonData(), xDataXML_getOneElementByTagName(), xDataXML_importFile2(), xDataXML_initializeDoc(), xDataXML_is_xDataType(), xDataXML_KalbachMannToTOM(), xDataXML_polynomialToTOM(), xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), xDataXML_regionsW_XYs_LegendreSeriesToTOM(), xDataXML_regionsXYs_regionToTOM(), xDataXML_regionsXYsToTOM(), xDataXML_stringTo_double(), xDataXML_stringTo_xDataTOM_Int(), xDataXML_stringToDoubles(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYsToTOM(), xDataXML_W_XYs_LegendreSeriesToTOM(), xDataXML_W_XYsDataToTOM(), xDataXML_xDataTypeConvertAttributes(), and xDataXML_XYsToTOM().