Geant4: G4TNtupleManager< TNTUPLE > Class Template Reference
G4TNtupleManager< TNTUPLE > Class Template Reference abstract
#include <G4TNtupleManager.hh>
Public Member Functions
G4TNtupleManager (const G4AnalysisManagerState &state)
~G4TNtupleManager ()
Public Member Functions inherited from G4BaseNtupleManager
G4BaseNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4BaseNtupleManager ()
G4BaseNtupleManager (const G4BaseNtupleManager &rhs)=delete
G4BaseNtupleManager & operator= (const G4BaseNtupleManager &rhs)=delete
Public Member Functions inherited from G4VNtupleManager
G4VNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4VNtupleManager ()
G4VNtupleManager (const G4VNtupleManager &rhs)=delete
G4VNtupleManager & operator= (const G4VNtupleManager &rhs)=delete
Public Member Functions inherited from G4BaseAnalysisManager
G4BaseAnalysisManager (const G4AnalysisManagerState &state)
virtual ~G4BaseAnalysisManager ()
G4bool SetFirstId (G4int firstId)
void SetLockFirstId (G4bool lockFirstId)
G4int GetFirstId () const
Protected Member Functions
virtual void CreateNtuplesFromBooking ()
G4bool IsEmpty () const
virtual G4bool Reset (G4bool deleteNtuple)
virtual G4int CreateNtuple (const G4String &name, const G4String &title) override
virtual G4int CreateNtupleIColumn (G4int ntupleId, const G4String &name, std::vector< int > *vector) final
virtual G4int CreateNtupleFColumn (G4int ntupleId, const G4String &name, std::vector< float > *vector) final
virtual G4int CreateNtupleDColumn (G4int ntupleId, const G4String &name, std::vector< double > *vector) final
virtual G4int CreateNtupleSColumn (G4int ntupleId, const G4String &name) final
virtual void FinishNtuple (G4int ntupleId) final
virtual G4bool FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value) final
virtual G4bool FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value) final
virtual G4bool FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value) final
virtual G4bool FillNtupleSColumn (G4int ntupleId, G4int columnId, const G4String &value) final
virtual G4bool AddNtupleRow (G4int ntupleId) override
virtual void SetActivation (G4bool activation) final
virtual void SetActivation (G4int ntupleId, G4bool activation) final
virtual G4bool GetActivation (G4int ntupleId) const final
TNTUPLE * GetNtuple () const
TNTUPLE * GetNtuple (G4int ntupleId) const
virtual G4int GetNofNtuples () const final
virtual G4int GetNofNtupleBookings () const override
std::vector< TNTUPLE * >::iterator BeginNtuple ()
std::vector< TNTUPLE * >::iterator EndNtuple ()
std::vector< TNTUPLE * >::const_iterator BeginConstNtuple () const
std::vector< TNTUPLE * >::const_iterator EndConstNtuple () const
virtual G4int CreateNtupleIColumn (const G4String &name, std::vector< int > *vector) final
virtual G4int CreateNtupleIColumn (G4int ntupleId, const G4String &name, std::vector< int > *vector)=0
virtual G4int CreateNtupleFColumn (const G4String &name, std::vector< float > *vector) final
virtual G4int CreateNtupleFColumn (G4int ntupleId, const G4String &name, std::vector< float > *vector)=0
virtual G4int CreateNtupleDColumn (const G4String &name, std::vector< double > *vector) final
virtual G4int CreateNtupleDColumn (G4int ntupleId, const G4String &name, std::vector< double > *vector)=0
virtual G4int CreateNtupleSColumn (const G4String &name)
virtual G4int CreateNtupleSColumn (G4int ntupleId, const G4String &name)=0
virtual void FinishNtuple () final
virtual void FinishNtuple (G4int ntupleId)=0
virtual G4bool FillNtupleIColumn (G4int id, G4int value) final
virtual G4bool FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value)=0
virtual G4bool FillNtupleFColumn (G4int id, G4float value) final
virtual G4bool FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value)=0
virtual G4bool FillNtupleDColumn (G4int id, G4double value) final
virtual G4bool FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value)=0
virtual G4bool FillNtupleSColumn (G4int id, const G4String &value) final
virtual G4bool FillNtupleSColumn (G4int ntupleId, G4int columnId, const G4String &value)=0
virtual G4bool AddNtupleRow () final
virtual G4bool AddNtupleRow (G4int ntupleId)=0
Protected Member Functions inherited from G4BaseNtupleManager
virtual G4int CreateNtupleIColumn (const G4String &name, std::vector< int > *vector) final
virtual G4int CreateNtupleFColumn (const G4String &name, std::vector< float > *vector) final
virtual G4int CreateNtupleDColumn (const G4String &name, std::vector< double > *vector) final
virtual G4int CreateNtupleSColumn (const G4String &name)
virtual void FinishNtuple () final
virtual G4bool SetFirstNtupleColumnId (G4int firstId) final
G4int GetFirstNtupleColumnId () const final
virtual G4bool FillNtupleIColumn (G4int id, G4int value) final
virtual G4bool FillNtupleFColumn (G4int id, G4float value) final
virtual G4bool FillNtupleDColumn (G4int id, G4double value) final
virtual G4bool FillNtupleSColumn (G4int id, const G4String &value) final
virtual G4bool AddNtupleRow () final
Protected Attributes
std::vector< G4TNtupleDescription< TNTUPLE > * > fNtupleDescriptionVector
std::vector< TNTUPLE * > fNtupleVector
Protected Attributes inherited from G4BaseNtupleManager
G4int fFirstNtupleColumnId
G4bool fLockFirstNtupleColumnId
Protected Attributes inherited from G4BaseAnalysisManager
const G4AnalysisManagerState & fState
G4int fFirstId
G4bool fLockFirstId
Private Member Functions
virtual void CreateTNtupleFromBooking (G4TNtupleDescription< TNTUPLE > *ntupleDescription)=0
virtual void FinishTNtuple (G4TNtupleDescription< TNTUPLE > *ntupleDescription, G4bool fromBooking)=0
G4TNtupleDescription< TNTUPLE > * GetNtupleDescriptionInFunction (G4int id, G4String function, G4bool warn=true) const
TNTUPLE * GetNtupleInFunction (G4int id, G4String function, G4bool warn=true) const
template<typename T >
G4int CreateNtupleTColumn (G4int ntupleId, const G4String &name, std::vector< T > *vector)
template<typename T >
G4bool FillNtupleTColumn (G4int ntupleId, G4int columnId, const T &value)
Detailed Description
template<typename TNTUPLE>
class G4TNtupleManager< TNTUPLE >
Definition at line 41 of file G4TNtupleManager.hh.
Constructor & Destructor Documentation
G4TNtupleManager()
template<typename TNTUPLE> G4TNtupleManager< TNTUPLE >::G4TNtupleManager (const G4AnalysisManagerState & state) explicit
~G4TNtupleManager()
template<typename TNTUPLE> G4TNtupleManager< TNTUPLE >::~G4TNtupleManager ()
Member Function Documentation
AddNtupleRow() [1/3]
template<typename TNTUPLE> G4bool G4BaseNtupleManager::AddNtupleRow final protected
Definition at line 115 of file G4BaseNtupleManager.cc.
AddNtupleRow() [2/3]
template<typename TNTUPLE> virtual G4bool G4TNtupleManager< TNTUPLE >::AddNtupleRow (G4int ntupleId) override protected virtual
Implements G4BaseNtupleManager.
AddNtupleRow() [3/3]
template<typename TNTUPLE> virtual G4bool G4BaseNtupleManager::AddNtupleRow protected
BeginConstNtuple()
template<typename TNTUPLE> std::vector<TNTUPLE*>::const_iterator G4TNtupleManager< TNTUPLE >::BeginConstNtuple () const protected
BeginNtuple()
template<typename TNTUPLE> std::vector<TNTUPLE*>::iterator G4TNtupleManager< TNTUPLE >::BeginNtuple () protected
CreateNtuple()
template<typename TNTUPLE> virtual G4int G4TNtupleManager< TNTUPLE >::CreateNtuple (const G4String & name, const G4String & title) override protected virtual
Implements G4BaseNtupleManager.
CreateNtupleDColumn() [1/3]
template<typename TNTUPLE> G4int G4BaseNtupleManager::CreateNtupleDColumn final protected
Definition at line 72 of file G4BaseNtupleManager.cc.
CreateNtupleDColumn() [2/3]
template<typename TNTUPLE> virtual G4int G4TNtupleManager< TNTUPLE >::CreateNtupleDColumn (G4int ntupleId, const G4String & name, std::vector< double > * vector) final protected virtual
Implements G4BaseNtupleManager.
CreateNtupleDColumn() [3/3]
template<typename TNTUPLE> virtual G4int G4BaseNtupleManager::CreateNtupleDColumn protected
CreateNtupleFColumn() [1/3]
template<typename TNTUPLE> G4int G4BaseNtupleManager::CreateNtupleFColumn final protected
Definition at line 65 of file G4BaseNtupleManager.cc.
CreateNtupleFColumn() [2/3]
template<typename TNTUPLE> virtual G4int G4TNtupleManager< TNTUPLE >::CreateNtupleFColumn (G4int ntupleId, const G4String & name, std::vector< float > * vector) final protected virtual
Implements G4BaseNtupleManager.
CreateNtupleFColumn() [3/3]
template<typename TNTUPLE> virtual G4int G4BaseNtupleManager::CreateNtupleFColumn protected
CreateNtupleIColumn() [1/3]
template<typename TNTUPLE> G4int G4BaseNtupleManager::CreateNtupleIColumn final protected
Definition at line 58 of file G4BaseNtupleManager.cc.
CreateNtupleIColumn() [2/3]
template<typename TNTUPLE> virtual G4int G4TNtupleManager< TNTUPLE >::CreateNtupleIColumn (G4int ntupleId, const G4String & name, std::vector< int > * vector) final protected virtual
Implements G4BaseNtupleManager.
CreateNtupleIColumn() [3/3]
template<typename TNTUPLE> virtual G4int G4BaseNtupleManager::CreateNtupleIColumn protected
CreateNtupleSColumn() [1/3]
template<typename TNTUPLE> G4int G4BaseNtupleManager::CreateNtupleSColumn protected
Definition at line 79 of file G4BaseNtupleManager.cc.
CreateNtupleSColumn() [2/3]
template<typename TNTUPLE> virtual G4int G4TNtupleManager< TNTUPLE >::CreateNtupleSColumn (G4int ntupleId, const G4String & name) final protected virtual
Implements G4BaseNtupleManager.
CreateNtupleSColumn() [3/3]
template<typename TNTUPLE> virtual G4int G4BaseNtupleManager::CreateNtupleSColumn protected
CreateNtuplesFromBooking()
template<typename TNTUPLE> virtual void G4TNtupleManager< TNTUPLE >::CreateNtuplesFromBooking () protected virtual
Reimplemented in G4RootMpiNtupleManager.
Referenced by G4RootMpiNtupleManager::CreateNtuplesFromBooking(), G4RootMpiAnalysisManager::OpenFileImpl(), G4Hdf5AnalysisManager::OpenFileImpl(), G4XmlAnalysisManager::OpenFileImpl(), G4CsvAnalysisManager::OpenFileImpl(), and G4RootAnalysisManager::OpenFileImpl().
CreateNtupleTColumn()
template<typename TNTUPLE> template<typename T > G4int G4TNtupleManager< TNTUPLE >::CreateNtupleTColumn (G4int ntupleId, const G4String & name, std::vector< T > * vector) private
CreateTNtupleFromBooking()
template<typename TNTUPLE> virtual void G4TNtupleManager< TNTUPLE >::CreateTNtupleFromBooking (G4TNtupleDescription< TNTUPLE > * ntupleDescription) private pure virtual
EndConstNtuple()
template<typename TNTUPLE> std::vector<TNTUPLE*>::const_iterator G4TNtupleManager< TNTUPLE >::EndConstNtuple () const protected
EndNtuple()
template<typename TNTUPLE> std::vector<TNTUPLE*>::iterator G4TNtupleManager< TNTUPLE >::EndNtuple () protected
FillNtupleDColumn() [1/3]
template<typename TNTUPLE> G4bool G4BaseNtupleManager::FillNtupleDColumn final protected
Definition at line 103 of file G4BaseNtupleManager.cc.
FillNtupleDColumn() [2/3]
template<typename TNTUPLE> virtual G4bool G4TNtupleManager< TNTUPLE >::FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value) final protected virtual
Implements G4BaseNtupleManager.
FillNtupleDColumn() [3/3]
template<typename TNTUPLE> virtual G4bool G4BaseNtupleManager::FillNtupleDColumn protected
FillNtupleFColumn() [1/3]
template<typename TNTUPLE> G4bool G4BaseNtupleManager::FillNtupleFColumn final protected
Definition at line 97 of file G4BaseNtupleManager.cc.
FillNtupleFColumn() [2/3]
template<typename TNTUPLE> virtual G4bool G4TNtupleManager< TNTUPLE >::FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value) final protected virtual
Implements G4BaseNtupleManager.
FillNtupleFColumn() [3/3]
template<typename TNTUPLE> virtual G4bool G4BaseNtupleManager::FillNtupleFColumn protected
FillNtupleIColumn() [1/3]
template<typename TNTUPLE> G4bool G4BaseNtupleManager::FillNtupleIColumn final protected
Definition at line 91 of file G4BaseNtupleManager.cc.
FillNtupleIColumn() [2/3]
template<typename TNTUPLE> virtual G4bool G4TNtupleManager< TNTUPLE >::FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value) final protected virtual
Implements G4BaseNtupleManager.
FillNtupleIColumn() [3/3]
template<typename TNTUPLE> virtual G4bool G4BaseNtupleManager::FillNtupleIColumn protected
FillNtupleSColumn() [1/3]
template<typename TNTUPLE> G4bool G4BaseNtupleManager::FillNtupleSColumn final protected
Definition at line 109 of file G4BaseNtupleManager.cc.
FillNtupleSColumn() [2/3]
template<typename TNTUPLE> virtual G4bool G4TNtupleManager< TNTUPLE >::FillNtupleSColumn (G4int ntupleId, G4int columnId, const G4String & value) final protected virtual
Implements G4BaseNtupleManager.
FillNtupleSColumn() [3/3]
template<typename TNTUPLE> virtual G4bool G4BaseNtupleManager::FillNtupleSColumn protected
FillNtupleTColumn()
template<typename TNTUPLE> template<typename T > G4bool G4TNtupleManager< TNTUPLE >::FillNtupleTColumn (G4int ntupleId, G4int columnId, const T & value) private
FinishNtuple() [1/3]
template<typename TNTUPLE> void G4BaseNtupleManager::FinishNtuple final protected
Definition at line 85 of file G4BaseNtupleManager.cc.
FinishNtuple() [2/3]
template<typename TNTUPLE> virtual void G4TNtupleManager< TNTUPLE >::FinishNtuple (G4int ntupleId) final protected virtual
Implements G4BaseNtupleManager.
FinishNtuple() [3/3]
template<typename TNTUPLE> virtual void G4BaseNtupleManager::FinishNtuple protected
FinishTNtuple()
template<typename TNTUPLE> virtual void G4TNtupleManager< TNTUPLE >::FinishTNtuple (G4TNtupleDescription< TNTUPLE > * ntupleDescription, G4bool fromBooking) private pure virtual
GetActivation()
template<typename TNTUPLE> virtual G4bool G4TNtupleManager< TNTUPLE >::GetActivation (G4int ntupleId) const final protected virtual
Implements G4VNtupleManager.
GetNofNtupleBookings()
template<typename TNTUPLE> virtual G4int G4TNtupleManager< TNTUPLE >::GetNofNtupleBookings () const override protected virtual
Implements G4VNtupleManager.
GetNofNtuples()
template<typename TNTUPLE> virtual G4int G4TNtupleManager< TNTUPLE >::GetNofNtuples () const final protected virtual
Implements G4VNtupleManager.
GetNtuple() [1/2]
template<typename TNTUPLE> TNTUPLE* G4TNtupleManager< TNTUPLE >::GetNtuple () const protected
GetNtuple() [2/2]
template<typename TNTUPLE> TNTUPLE* G4TNtupleManager< TNTUPLE >::GetNtuple (G4int ntupleId) const protected
GetNtupleDescriptionInFunction()
template<typename TNTUPLE> G4TNtupleDescription<TNTUPLE>* G4TNtupleManager< TNTUPLE >::GetNtupleDescriptionInFunction (G4int id, G4String function, G4bool warn = true) const private
GetNtupleInFunction()
template<typename TNTUPLE> TNTUPLE* G4TNtupleManager< TNTUPLE >::GetNtupleInFunction (G4int id, G4String function, G4bool warn = true) const private
IsEmpty()
template<typename TNTUPLE> G4bool G4TNtupleManager< TNTUPLE >::IsEmpty () const protected
Referenced by G4RootAnalysisManager::CloseFileImpl().
Reset()
template<typename TNTUPLE> virtual G4bool G4TNtupleManager< TNTUPLE >::Reset (G4bool deleteNtuple) protected virtual
Reimplemented in G4RootNtupleManager.
Referenced by G4Hdf5AnalysisManager::CloseFileImpl(), G4XmlAnalysisManager::CloseFileImpl(), G4CsvAnalysisManager::CloseFileImpl(), G4XmlAnalysisManager::Reset(), G4CsvAnalysisManager::Reset(), G4Hdf5AnalysisManager::Reset(), and G4RootNtupleManager::Reset().
SetActivation() [1/2]
template<typename TNTUPLE> virtual void G4TNtupleManager< TNTUPLE >::SetActivation (G4bool activation) final protected virtual
Implements G4VNtupleManager.
SetActivation() [2/2]
template<typename TNTUPLE> virtual void G4TNtupleManager< TNTUPLE >::SetActivation (G4int ntupleId, G4bool activation) final protected virtual
Implements G4VNtupleManager.
Field Documentation
fNtupleDescriptionVector
template<typename TNTUPLE> std::vector<G4TNtupleDescription<TNTUPLE>*> G4TNtupleManager< TNTUPLE >::fNtupleDescriptionVector protected
Definition at line 107 of file G4TNtupleManager.hh.
fNtupleVector
template<typename TNTUPLE> std::vector<TNTUPLE*> G4TNtupleManager< TNTUPLE >::fNtupleVector protected
Definition at line 108 of file G4TNtupleManager.hh.
The documentation for this class was generated from the following file:
source/analysis/management/include/G4TNtupleManager.hh