Geant4: CCalVisualisable Class Reference
CCalVisualisable Class Reference
#include <CCalVisualisable.hh>
Data Structures
class visParameters
Public Types
enum visType {
Sensitive =0, Electronics =1, Support =2, Cable =3,
Absorber =4, OtherServices =5, PseudoVolumes =6, TotalVisTypes =7,
Undefined =-1
}
Public Member Functions
CCalVisualisable (G4String file)
virtual ~CCalVisualisable ()
bool readFile (G4String file)
void setDefault ()
bool isVisible (visType v) const
void setVisible (visType v, bool flag=true)
double colorRed (visType v) const
double colorGreen (visType v) const
double colorBlue (visType v) const
void setColorRed (visType v, double r)
void setColorGreen (visType v, double g)
void setColorBlue (visType v, double b)
void setColor (visType v, double r, double g, double b)
bool isWireFrame (visType v) const
void setWireFrame (visType v, bool wf=true)
Protected Member Functions
bool readFile ()
Static Protected Member Functions
static void setPath ()
Private Member Functions
double checkColorRange (double color, char type) const
Private Attributes
G4String visFile
visParameters theParameters [TotalVisTypes]
Static Private Attributes
static const char * pathName =0
Detailed Description
Definition at line 39 of file CCalVisualisable.hh.
Member Enumeration Documentation
visType
enum CCalVisualisable::visType
Enumerator
Sensitive
Electronics
Support
Cable
Absorber
OtherServices
PseudoVolumes
TotalVisTypes
Undefined
Definition at line 43 of file CCalVisualisable.hh.
Constructor & Destructor Documentation
CCalVisualisable()
CCalVisualisable::CCalVisualisable (G4String file)
Definition at line 41 of file CCalVisualisable.cc.
~CCalVisualisable()
virtual CCalVisualisable::~CCalVisualisable () inline virtual
Definition at line 71 of file CCalVisualisable.hh.
Member Function Documentation
checkColorRange()
double CCalVisualisable::checkColorRange (double color, char type) const private
Definition at line 159 of file CCalVisualisable.cc.
Referenced by readFile().
colorBlue()
double CCalVisualisable::colorBlue (visType v) const inline
Definition at line 85 of file CCalVisualisable.hh.
Referenced by CCalG4Able::setVisType().
colorGreen()
double CCalVisualisable::colorGreen (visType v) const inline
Definition at line 84 of file CCalVisualisable.hh.
Referenced by CCalG4Able::setVisType().
colorRed()
double CCalVisualisable::colorRed (visType v) const inline
Definition at line 83 of file CCalVisualisable.hh.
Referenced by CCalG4Able::setVisType().
isVisible()
bool CCalVisualisable::isVisible (visType v) const inline
Definition at line 80 of file CCalVisualisable.hh.
Referenced by CCalG4Able::setVisType().
isWireFrame()
bool CCalVisualisable::isWireFrame (visType v) const inline
Definition at line 91 of file CCalVisualisable.hh.
Referenced by CCalG4Able::setVisType().
readFile() [1/2]
bool CCalVisualisable::readFile () protected
Definition at line 80 of file CCalVisualisable.cc.
Referenced by CCalVisualisable(), and readFile().
readFile() [2/2]
bool CCalVisualisable::readFile (G4String file)
Definition at line 48 of file CCalVisualisable.cc.
setColor()
void CCalVisualisable::setColor (visType v, double r, double g, double b)
Definition at line 62 of file CCalVisualisable.cc.
setColorBlue()
void CCalVisualisable::setColorBlue (visType v, double b) inline
Definition at line 88 of file CCalVisualisable.hh.
setColorGreen()
void CCalVisualisable::setColorGreen (visType v, double g) inline
Definition at line 87 of file CCalVisualisable.hh.
setColorRed()
void CCalVisualisable::setColorRed (visType v, double r) inline
Definition at line 86 of file CCalVisualisable.hh.
setDefault()
void CCalVisualisable::setDefault ()
Definition at line 53 of file CCalVisualisable.cc.
Referenced by CCalVisualisable().
setPath()
void CCalVisualisable::setPath () static protected
Definition at line 68 of file CCalVisualisable.cc.
Referenced by CCalVisualisable().
setVisible()
void CCalVisualisable::setVisible (visType v, bool flag = true) inline
Definition at line 81 of file CCalVisualisable.hh.
setWireFrame()
void CCalVisualisable::setWireFrame (visType v, bool wf = true) inline
Definition at line 92 of file CCalVisualisable.hh.
Field Documentation
pathName
const char * CCalVisualisable::pathName =0 static private
Definition at line 102 of file CCalVisualisable.hh.
Referenced by CCalVisualisable(), readFile(), and setPath().
theParameters
visParameters CCalVisualisable::theParameters[TotalVisTypes] private
Definition at line 104 of file CCalVisualisable.hh.
Referenced by colorBlue(), colorGreen(), colorRed(), isVisible(), isWireFrame(), readFile(), setColor(), setColorBlue(), setColorGreen(), setColorRed(), setDefault(), setVisible(), and setWireFrame().
visFile
G4String CCalVisualisable::visFile private
Definition at line 103 of file CCalVisualisable.hh.
Referenced by checkColorRange(), and readFile().
The documentation for this class was generated from the following files:
examples/advanced/composite_calorimeter/include/CCalVisualisable.hh
examples/advanced/composite_calorimeter/src/CCalVisualisable.cc