Geant4: DicomBeamDevice Class Reference
DicomBeamDevice Class Reference
#include <DicomBeamDevice.hh>
Public Member Functions
DicomBeamDevice (DRTBeamLimitingDeviceSequenceInRTBeamsModule::Item bldsItem)
DicomBeamDevice (DRTBeamLimitingDevicePositionSequence::Item bldpsItem)
~DicomBeamDevice ()
void SetSourceToBeamLimitingDeviceDistance (Float64 dat)
Float64 GetSourceToBeamLimitingDeviceDistance () const
void SetNumberOfLeafJawPairs (Sint32 dat)
Sint32 GetNumberOfLeafJawPairs () const
void SetType (OFString dat)
OFString GetType () const
void AddPositionBoundary (Float64 dat)
Float64 GetPositionBoundary (size_t ii)
void Print (std::ostream &out)
Private Attributes
OFString theType
Float64 theSourceToBeamLimitingDeviceDistance
Sint32 theNumberOfLeafJawPairs
std::vector< Float64 > thePositionBoundaries
Detailed Description
Definition at line 39 of file DicomBeamDevice.hh.
Constructor & Destructor Documentation
DicomBeamDevice() [1/2]
DicomBeamDevice::DicomBeamDevice (DRTBeamLimitingDeviceSequenceInRTBeamsModule::Item bldsItem)
Definition at line 31 of file DicomBeamDevice.cc.
DicomBeamDevice() [2/2]
DicomBeamDevice::DicomBeamDevice (DRTBeamLimitingDevicePositionSequence::Item bldpsItem)
Definition at line 56 of file DicomBeamDevice.cc.
~DicomBeamDevice()
DicomBeamDevice::~DicomBeamDevice () inline
Definition at line 44 of file DicomBeamDevice.hh.
Member Function Documentation
AddPositionBoundary()
void DicomBeamDevice::AddPositionBoundary (Float64 dat) inline
Definition at line 65 of file DicomBeamDevice.hh.
Referenced by DicomBeamDevice().
GetNumberOfLeafJawPairs()
Sint32 DicomBeamDevice::GetNumberOfLeafJawPairs () const inline
Definition at line 56 of file DicomBeamDevice.hh.
GetPositionBoundary()
Float64 DicomBeamDevice::GetPositionBoundary (size_t ii) inline
Definition at line 68 of file DicomBeamDevice.hh.
GetSourceToBeamLimitingDeviceDistance()
Float64 DicomBeamDevice::GetSourceToBeamLimitingDeviceDistance () const inline
Definition at line 50 of file DicomBeamDevice.hh.
GetType()
OFString DicomBeamDevice::GetType () const inline
Definition at line 62 of file DicomBeamDevice.hh.
Print()
void DicomBeamDevice::Print (std::ostream & out)
Definition at line 75 of file DicomBeamDevice.cc.
SetNumberOfLeafJawPairs()
void DicomBeamDevice::SetNumberOfLeafJawPairs (Sint32 dat) inline
Definition at line 53 of file DicomBeamDevice.hh.
Referenced by DicomBeamDevice().
SetSourceToBeamLimitingDeviceDistance()
void DicomBeamDevice::SetSourceToBeamLimitingDeviceDistance (Float64 dat) inline
Definition at line 47 of file DicomBeamDevice.hh.
Referenced by DicomBeamDevice().
SetType()
void DicomBeamDevice::SetType (OFString dat) inline
Definition at line 59 of file DicomBeamDevice.hh.
Referenced by DicomBeamDevice().
Field Documentation
theNumberOfLeafJawPairs
Sint32 DicomBeamDevice::theNumberOfLeafJawPairs private
Definition at line 76 of file DicomBeamDevice.hh.
Referenced by GetNumberOfLeafJawPairs(), and SetNumberOfLeafJawPairs().
thePositionBoundaries
std::vector<Float64> DicomBeamDevice::thePositionBoundaries private
Definition at line 77 of file DicomBeamDevice.hh.
Referenced by AddPositionBoundary(), and GetPositionBoundary().
theSourceToBeamLimitingDeviceDistance
Float64 DicomBeamDevice::theSourceToBeamLimitingDeviceDistance private
Definition at line 75 of file DicomBeamDevice.hh.
Referenced by GetSourceToBeamLimitingDeviceDistance(), and SetSourceToBeamLimitingDeviceDistance().
theType
OFString DicomBeamDevice::theType private
Definition at line 74 of file DicomBeamDevice.hh.
Referenced by GetType(), and SetType().
The documentation for this class was generated from the following files:
examples/extended/medical/DICOM/dicomReader/include/DicomBeamDevice.hh
examples/extended/medical/DICOM/dicomReader/src/DicomBeamDevice.cc