Geant4: B03PVolumeStore Class Reference
B03PVolumeStore Class Reference
#include <B03PVolumeStore.hh>
Public Member Functions
B03PVolumeStore ()
~B03PVolumeStore ()
void AddPVolume (const G4GeometryCell &cell)
const G4VPhysicalVolume * GetPVolume (const G4String &name) const
G4String GetPNames () const
Private Attributes
B03SetGeometryCell fSetGeometryCell
Detailed Description
Definition at line 52 of file B03PVolumeStore.hh.
Constructor & Destructor Documentation
B03PVolumeStore()
B03PVolumeStore::B03PVolumeStore ()
Definition at line 46 of file B03PVolumeStore.cc.
~B03PVolumeStore()
B03PVolumeStore::~B03PVolumeStore ()
Definition at line 50 of file B03PVolumeStore.cc.
Member Function Documentation
AddPVolume()
void B03PVolumeStore::AddPVolume (const G4GeometryCell & cell)
Definition at line 54 of file B03PVolumeStore.cc.
Referenced by B03ImportanceDetectorConstruction::Construct().
GetPNames()
G4String B03PVolumeStore::GetPNames () const
Definition at line 90 of file B03PVolumeStore.cc.
Referenced by B03ImportanceDetectorConstruction::ListPhysNamesAsG4String().
GetPVolume()
const G4VPhysicalVolume * B03PVolumeStore::GetPVolume (const G4String & name) const
Definition at line 72 of file B03PVolumeStore.cc.
Referenced by B03ImportanceDetectorConstruction::GetGeometryCell(), and B03ImportanceDetectorConstruction::GetPhysicalVolumeByName().
Field Documentation
fSetGeometryCell
B03SetGeometryCell B03PVolumeStore::fSetGeometryCell private
Definition at line 62 of file B03PVolumeStore.hh.
Referenced by AddPVolume(), GetPNames(), and GetPVolume().
The documentation for this class was generated from the following files:
examples/extended/biasing/B03/include/B03PVolumeStore.hh
examples/extended/biasing/B03/src/B03PVolumeStore.cc