Geant4: G4InuclParticleNames Namespace Reference
G4InuclParticleNames Namespace Reference
Enumerations
enum Long {
nuclei =0, proton =1, neutron =2, pionPlus =3,
pionMinus =5, pionZero =7, photon =9, kaonPlus =11,
kaonMinus =13, kaonZero =15, kaonZeroBar =17, lambda =21,
sigmaPlus =23, sigmaZero =25, sigmaMinus =27, xiZero =29,
xiMinus =31, omegaMinus =33, deuteron =41, triton =43,
He3 =45, alpha =47, antiProton =51, antiNeutron =53,
antiDeuteron =61, antiTriton =63, antiHe3 =65, antiAlpha =67,
diproton =111, unboundPN =112, dineutron =122, electronNu =-1,
muonNu =-3, tauNu =-5, antiElectronNu =-7, antiMuonNu =-9,
antiTauNu =-11, WMinus =-13, WPlus =-15, Zzero =-17,
electron =-21, muonMinus =-23, tauMinus =-25, positron =-27,
muonPlus =-29, tauPlus =-31
}
enum Short {
nuc =nuclei, pro =proton, neu =neutron, pip =pionPlus,
pim =pionMinus, pi0 =pionZero, gam =photon, kpl =kaonPlus,
kmi =kaonMinus, k0 =kaonZero, k0b =kaonZeroBar, lam =lambda,
sp =sigmaPlus, s0 =sigmaZero, sm =sigmaMinus, xi0 =xiZero,
xim =xiMinus, om =omegaMinus, deu =deuteron, ap =antiProton,
an =antiNeutron, ade =antiDeuteron, atr =antiTriton, ahe =antiHe3,
aal =antiAlpha, pp =diproton, pn =unboundPN, nn =dineutron,
enu =electronNu, mnu =muonNu, tnu =tauNu, aenu =antiElectronNu,
amnu =antiMuonNu, atnu =antiTauNu, wm =WMinus, wp =WPlus,
z0 =Zzero, ele =electron, mum =muonMinus, tm =tauMinus,
pos =positron, mup =muonPlus, tp =tauPlus
}
Functions
const char * nameLong (G4int ptype)
const char * nameShort (G4int ptype)
const char * name (G4int ptype)
G4bool isPhoton (G4int ityp)
G4bool isMuon (G4int ityp)
G4bool isElectron (G4int ityp)
G4bool isNeutrino (G4int ityp)
G4bool pion (G4int ityp)
G4bool nucleon (G4int ityp)
G4bool antinucleon (G4int ityp)
G4bool quasi_deutron (G4int ityp)
G4int baryon (G4int ityp)
G4bool antibaryon (G4int ityp)
G4bool hyperon (G4int ityp)
Enumeration Type Documentation
Long
enum G4InuclParticleNames::Long
Enumerator
nuclei
proton
neutron
pionPlus
pionMinus
pionZero
photon
kaonPlus
kaonMinus
kaonZero
kaonZeroBar
lambda
sigmaPlus
sigmaZero
sigmaMinus
xiZero
xiMinus
omegaMinus
deuteron
triton
He3
alpha
antiProton
antiNeutron
antiDeuteron
antiTriton
antiHe3
antiAlpha
diproton
unboundPN
dineutron
electronNu
muonNu
tauNu
antiElectronNu
antiMuonNu
antiTauNu
WMinus
WPlus
Zzero
electron
muonMinus
tauMinus
positron
muonPlus
tauPlus
Definition at line 43 of file G4InuclParticleNames.hh.
Short
enum G4InuclParticleNames::Short
Enumerator
nuc
pro
neu
pip
pim
pi0
gam
kpl
kmi
k0
k0b
lam
sp
s0
sm
xi0
xim
om
deu
ap
an
ade
atr
ahe
aal
pp
pn
nn
enu
mnu
tnu
aenu
amnu
atnu
wm
wp
z0
ele
mum
tm
pos
mup
tp
Definition at line 59 of file G4InuclParticleNames.hh.
Function Documentation
antibaryon()
G4bool G4InuclParticleNames::antibaryon (G4int ityp) inline
Definition at line 113 of file G4InuclParticleNames.hh.
antinucleon()
G4bool G4InuclParticleNames::antinucleon (G4int ityp) inline
Definition at line 96 of file G4InuclParticleNames.hh.
Referenced by G4InuclElementaryParticle::antinucleon().
baryon()
G4int G4InuclParticleNames::baryon (G4int ityp) inline
Definition at line 103 of file G4InuclParticleNames.hh.
Referenced by antibaryon(), GammaKnifeParticles::ConstructParticle(), HadrontherapyParticles::ConstructParticle(), GammaRayTelParticles::ConstructParticle(), and G4CollisionOutput::getTotalBaryonNumber().
hyperon()
G4bool G4InuclParticleNames::hyperon (G4int ityp) inline
Definition at line 115 of file G4InuclParticleNames.hh.
Referenced by G4INCL::NYElasticChannel::fillFinalState(), and G4INCL::CrossSectionsStrangeness::NYelastic().
isElectron()
G4bool G4InuclParticleNames::isElectron (G4int ityp) inline
Definition at line 83 of file G4InuclParticleNames.hh.
Referenced by G4PhysicsListHelper::CheckParticleList(), G4EmParameters::DefineRegParamForLoss(), G4GoudsmitSaundersonMscModel::Initialise(), G4InuclElementaryParticle::isElectron(), and G4SBBremTable::SampleEnergyTransfer().
isMuon()
G4bool G4InuclParticleNames::isMuon (G4int ityp) inline
Definition at line 81 of file G4InuclParticleNames.hh.
Referenced by G4InuclElementaryParticle::isMuon().
isNeutrino()
G4bool G4InuclParticleNames::isNeutrino (G4int ityp) inline
Definition at line 85 of file G4InuclParticleNames.hh.
Referenced by G4InuclElementaryParticle::isNeutrino().
isPhoton()
G4bool G4InuclParticleNames::isPhoton (G4int ityp) inline
Definition at line 79 of file G4InuclParticleNames.hh.
Referenced by G4InuclElementaryParticle::isPhoton().
name()
const char* G4InuclParticleNames::name (G4int ptype) inline
Definition at line 76 of file G4InuclParticleNames.hh.
Referenced by G4EmBiasingManager::ActivateForcedInteraction(), G4EmProcessOptions::ActivateForcedInteraction(), G4EmModelActivator::ActivatePAI(), G4EmBiasingManager::ActivateSecondaryBiasing(), G4EmProcessOptions::ActivateSecondaryBiasing(), G4EmProcessOptions::ActivateSecondaryBiasingForGamma(), Histo::Add1D(), G4HepRepFileXMLWriter::addAttDef(), G4HepRepSceneHandler::addAttVals(), G4HepRepFileXMLWriter::addAttValue(), G4OpenInventorXtExaminerViewer::addButton(), CCalSDList::addCalo(), CCalSensAssign::addCaloSD(), CanvasInTab::AddCanvas(), CCalMaterialFactory::addCCalMaterial(), CCalMaterialFactory::addElement(), G4NistElementBuilder::AddElement(), G4NistMaterialBuilder::AddElementByAtomCount(), G4NistMaterialBuilder::AddElementByWeightFraction(), G4PhysListRegistry::AddFactory(), G4PhysicsConstructorRegistry::AddFactory(), G4H1ToolsManager::AddH1(), G4H1ToolsManager::AddH1Information(), G4H2ToolsManager::AddH2(), G4H2ToolsManager::AddH2Information(), G4H3ToolsManager::AddH3(), G4H3ToolsManager::AddH3Information(), G4HnManager::AddHnInformation(), G4TrajectoryDrawByAttribute::AddIntervalContext(), CCalMaterialFactory::addMaterial(), RE06DetectorConstruction::AddMaterial(), CCalRotationMatrixFactory::AddMatrix(), G4OpenInventorXtExaminerViewer::addMenu(), G4MoleculeGun::AddMolecule(), G4P1ToolsManager::AddP1(), G4P1ToolsManager::AddP1Information(), G4P2ToolsManager::AddP2(), G4P2ToolsManager::AddP2Information(), GammaRayTelPhysicsList::AddPackage(), PhysicsList::AddPackage(), G4PhysListRegistry::AddPhysicsExtension(), GammaKnifePhysicsList::AddPhysicsList(), BrachyPhysicsList::AddPhysicsList(), XrayFluoPhysicsList::AddPhysicsList(), HadrontherapyPhysicsList::AddPhysicsList(), PhysicsList::AddPhysicsList(), GammaRayTelPhysicsList::AddPhysicsList(), ML2PhysicsList::AddPhysicsList(), IORTPhysicsList::AddPhysicsList(), G4GDMLWriteDefine::AddPosition(), G4IonPhysicsXS::AddProcess(), G4IonPhysics::AddProcess(), G4IonPhysicsPHP::AddProcess(), G4IonINCLXXPhysics::AddProcess(), G4IonQMDPhysics::AddProcess(), G4NativeScreenedCoulombCrossSection::AddScreeningFunction(), G4GMocrenFileSceneHandler::AddSolid(), CCalSDList::addTracker(), G4HepRepFileXMLWriter::addType(), G4TrajectoryDrawByAttribute::AddValueContext(), G4AttCheck::AddValuesAndDefs(), G4VisCommandSceneAddUserAction::AddVisAction(), appendAttributeValue(), G4ModelCmdAddIntervalContext< M >::Apply(), G4ModelCmdAddValueContext< M >::Apply(), G4BinaryCascade::ApplyCollision(), G4GDMLReadStructure::AssemblyRead(), CCalSensAssign::assign(), G4EnergyLossForExtrapolator::AverageScatteringAngle(), G4GDMLReadSolids::BooleanRead(), G4GDMLWriteSolids::BooleanWrite(), G4GDMLReadStructure::BorderSurfaceRead(), G4GDMLReadSolids::BoxRead(), G4GDMLWriteSolids::BoxWrite(), G4MoleculeGun::BuildAndPushTrack(), G4NistManager::BuildMaterialWithNewDensity(), G4NistMaterialBuilder::BuildNistMaterial(), G4MPIscorerMerger::CalculatePackSize(), CCalDetector::CCalDetector(), CCalG4Able::CCalG4Able(), CCalGeometryConfiguration::CCalGeometryConfiguration(), CCaloSD::CCaloSD(), CCalRotationMatrixFactory::CCalRotationMatrixFactory(), CCalSensitiveConfiguration::CCalSensitiveConfiguration(), G4LENDModel::ChangeDefaultEvaluation(), CML2RunAction::ChangeOutputFileName(), DicomHandler::CheckFileFormat(), G4tgbGeometryDumper::CheckIfLogVolExists(), G4tgbGeometryDumper::CheckIfPhysVolExists(), G4ProductionCutsTable::CheckMaterialInfo(), G4AccumulableManager::CheckName(), G4Analysis::CheckName(), G4PhysicsListHelper::CheckParticleList(), F04StackingAction::ClassifyNewTrack(), G4GMocrenFileSceneHandler::Detector::clear(), G4HepRepSceneHandler::closeHepRep(), G03ColorReader::ColorRead(), G03ColorWriter::ColorWrite(), G4GDMLReadSolids::ConeRead(), G4GDMLWriteSolids::ConeWrite(), G4GDMLReadDefine::ConstantRead(), B03DetectorConstruction::Construct(), RE01DetectorConstruction::Construct(), B01DetectorConstruction::Construct(), B02DetectorConstruction::Construct(), GeometryConstruction::Construct(), B02ImportanceDetectorConstruction::Construct(), B03ImportanceDetectorConstruction::Construct(), UltraDetectorConstruction::Construct(), CCalG4Hcal::constructAbsorberLayer(), G4ExcitedBaryonConstructor::ConstructAntiParticle(), CCalG4Ecal::constructGlobal(), CCalG4Hall::constructIn(), CCalG4Hcal::constructIn(), CCalG4Ecal::constructIn(), G4MuonicAtomHelper::ConstructMuonicAtom(), G4NistMaterialBuilder::ConstructNewGasMaterial(), G4NistManager::ConstructNewGasMaterial(), G4NistMaterialBuilder::ConstructNewIdealGasMaterial(), G4NistManager::ConstructNewIdealGasMaterial(), G4NistMaterialBuilder::ConstructNewMaterial(), G4NistManager::ConstructNewMaterial(), G4ExcitedBaryonConstructor::ConstructParticle(), UltraDetectorConstruction::ConstructReflector(), CCalG4Hcal::constructScintillatorLayer(), DMXDetectorConstruction::ConstructSDandField(), RE02DetectorConstruction::ConstructSDandField(), UltraDetectorConstruction::ConstructTableMaterials(), UltraDetectorConstruction::ConstructUVscope(), copyEntityTable(), Run::CountInTimeWindow(), Run::CountNuclearChannel(), G4DigiAttributeFilterFactory::Create(), G4HitAttributeFilterFactory::Create(), G4TrajectoryAttributeFilterFactory::Create(), G4TrajectoryDrawByAttributeFactory::Create(), G4TrajectoryDrawByChargeFactory::Create(), G4TrajectoryChargeFilterFactory::Create(), G4TrajectoryGenericDrawerFactory::Create(), G4TrajectoryParticleFilterFactory::Create(), G4TrajectoryDrawByParticleIDFactory::Create(), G4TrajectoryOriginVolumeFilterFactory::Create(), G4TrajectoryDrawByOriginVolumeFactory::Create(), G4TrajectoryDrawByEncounteredVolumeFactory::Create(), G4TrajectoryEncounteredVolumeFilterFactory::Create(), pyG4Box::CreateBox(), pyG4Cons::CreateCons(), pyG4Ellipsoid::CreateEllipsoid(), pyG4EllipticalCone::CreateEllipticalCone(), pyG4EllipticalTube::CreateEllipticalTube(), G4H1ToolsManager::CreateH1(), G4VAnalysisManager::CreateH1(), G4H2ToolsManager::CreateH2(), G4VAnalysisManager::CreateH2(), G4H3ToolsManager::CreateH3(), G4VAnalysisManager::CreateH3(), pyG4Hype::CreateHype(), G4IonTable::CreateIon(), G4MoleculeTable::CreateMoleculeDefinition(), G4MoleculeGunMessenger::CreateNewType(), G4RootMpiPNtupleManager::CreateNtuple(), G4RootPNtupleManager::CreateNtuple(), G4VAnalysisManager::CreateNtuple(), G4TNtupleManager< tools::hdf5::ntuple >::CreateNtupleDColumn(), G4RootMpiPNtupleManager::CreateNtupleDColumn(), G4RootPNtupleManager::CreateNtupleDColumn(), G4VAnalysisManager::CreateNtupleDColumn(), G4TNtupleManager< tools::hdf5::ntuple >::CreateNtupleFColumn(), G4RootMpiPNtupleManager::CreateNtupleFColumn(), G4RootPNtupleManager::CreateNtupleFColumn(), G4VAnalysisManager::CreateNtupleFColumn(), G4TNtupleManager< tools::hdf5::ntuple >::CreateNtupleIColumn(), G4RootMpiPNtupleManager::CreateNtupleIColumn(), G4RootPNtupleManager::CreateNtupleIColumn(), G4VAnalysisManager::CreateNtupleIColumn(), G4TNtupleManager< tools::hdf5::ntuple >::CreateNtupleSColumn(), G4RootMpiPNtupleManager::CreateNtupleSColumn(), G4RootPNtupleManager::CreateNtupleSColumn(), G4VAnalysisManager::CreateNtupleSColumn(), G4RootMpiPNtupleManager::CreateNtupleTColumn(), G4RootPNtupleManager::CreateNtupleTColumn(), pyG4Orb::CreateOrb(), G4P1ToolsManager::CreateP1(), G4VAnalysisManager::CreateP1(), G4P2ToolsManager::CreateP2(), G4VAnalysisManager::CreateP2(), pyG4Para::CreatePara(), G3Division::CreatePVReplica(), G4HepRep::CreateSceneHandler(), G4VRML1File::CreateSceneHandler(), G4VRML2File::CreateSceneHandler(), G4XXX::CreateSceneHandler(), G4XXXFile::CreateSceneHandler(), G4XXXSG::CreateSceneHandler(), G4XXXStored::CreateSceneHandler(), G4HepRepFile::CreateSceneHandler(), G4ASCIITree::CreateSceneHandler(), G4DAWNFILE::CreateSceneHandler(), G4GMocrenFile::CreateSceneHandler(), G4RayTracer::CreateSceneHandler(), G4VisManager::CreateSceneHandler(), pyG4Sphere::CreateSphere(), pyG4Tet::CreateTet(), pyG4Torus::CreateTorus(), pyG4Trd::CreateTrd(), pyG4Tubs::CreateTubs(), pyG4TwistedBox::CreateTwistedBox(), pyG4TwistedTrd::CreateTwistedTrd(), G4HepRep::CreateViewer(), G4VRML1File::CreateViewer(), G4XXXFile::CreateViewer(), G4XXXSG::CreateViewer(), G4XXXStored::CreateViewer(), G4VRML2File::CreateViewer(), G4XXX::CreateViewer(), G4ASCIITree::CreateViewer(), G4HepRepFile::CreateViewer(), G4DAWNFILE::CreateViewer(), G4GMocrenFile::CreateViewer(), G4RayTracer::CreateViewer(), G4VisManager::CreateViewer(), G4GDMLReadSolids::CutTubeRead(), G4GDMLWriteSolids::CutTubeWrite(), G4BinaryCascade::DebugApplyCollisionFail(), G4GenericMessenger::DeclareMethod(), G4GenericMessenger::DeclareMethodWithUnit(), G4GenericMessenger::DeclareProperty(), G4GenericMessenger::DeclarePropertyWithUnit(), G4PhysListRegistry::DeconstructPhysListName(), G4GDMLEvaluator::DefineConstant(), GB03DetectorConstruction::DefineMaterials(), RE06DetectorConstruction::DefineMaterials(), F02DetectorConstruction::DefineMaterials(), F01DetectorConstruction::DefineMaterials(), F03DetectorConstruction::DefineMaterials(), PurgMagDetectorConstruction::DefineMaterials(), GammaRayTelDetectorConstruction::DefineMaterials(), G4GDMLEvaluator::DefineMatrix(), G4GDMLEvaluator::DefineVariable(), G4PhononLong::Definition(), G4PhononTransSlow::Definition(), G4PhononTransFast::Definition(), G4BcMesonMinus::Definition(), G4EtaPrime::Definition(), G4Upsilon::Definition(), G4BcMesonPlus::Definition(), G4BMesonPlus::Definition(), G4AntiNeutrinoMu::Definition(), G4NeutrinoMu::Definition(), G4AntiLambda::Definition(), G4AntiLambdacPlus::Definition(), G4AntiNeutron::Definition(), G4AntiOmegabMinus::Definition(), G4AntiOmegacZero::Definition(), G4DMesonMinus::Definition(), G4AntiOmegaMinus::Definition(), G4AntiProton::Definition(), G4AntiSigmacPlus::Definition(), G4AntiSigmacPlusPlus::Definition(), G4AntiSigmacZero::Definition(), G4AntiSigmaMinus::Definition(), G4AntiSigmaPlus::Definition(), G4AntiSigmaZero::Definition(), G4AntiXicPlus::Definition(), G4AntiXicZero::Definition(), G4AntiXiMinus::Definition(), G4AntiXiZero::Definition(), G4Lambda::Definition(), G4LambdacPlus::Definition(), G4OmegabMinus::Definition(), G4OmegacZero::Definition(), G4OmegaMinus::Definition(), G4SigmacPlus::Definition(), G4SigmacPlusPlus::Definition(), G4SigmacZero::Definition(), G4SigmaMinus::Definition(), G4SigmaPlus::Definition(), G4SigmaZero::Definition(), G4XicPlus::Definition(), G4XicZero::Definition(), G4NeutrinoE::Definition(), G4XiMinus::Definition(), G4XiZero::Definition(), G4AntiBMesonZero::Definition(), G4AntiBsMesonZero::Definition(), G4AntiDMesonZero::Definition(), G4AntiKaonZero::Definition(), G4BMesonMinus::Definition(), G4TauMinus::Definition(), G4BMesonZero::Definition(), G4DMesonPlus::Definition(), G4DMesonZero::Definition(), G4DsMesonMinus::Definition(), G4DsMesonPlus::Definition(), G4Eta::Definition(), G4JPsi::Definition(), G4KaonMinus::Definition(), G4KaonPlus::Definition(), G4KaonZero::Definition(), G4KaonZeroLong::Definition(), G4KaonZeroShort::Definition(), G4PionPlus::Definition(), G4PionMinus::Definition(), G4PionZero::Definition(), G4AntiNeutrinoE::Definition(), G4AntiNeutrinoTau::Definition(), G4Electron::Definition(), G4MuonMinus::Definition(), G4MuonPlus::Definition(), G4NeutrinoTau::Definition(), G4TauPlus::Definition(), G4BsMesonZero::Definition(), G4AntiSigmabMinus::Definition(), G4AntiSigmabPlus::Definition(), G4AntiSigmabZero::Definition(), G4AntiXibMinus::Definition(), G4AntiXibZero::Definition(), G4Neutron::Definition(), G4Proton::Definition(), G4SigmabMinus::Definition(), G4SigmabZero::Definition(), G4SigmabPlus::Definition(), G4XibZero::Definition(), G4XibMinus::Definition(), G4Alpha::Definition(), G4AntiAlpha::Definition(), G4AntiDeuteron::Definition(), G4AntiHe3::Definition(), G4AntiTriton::Definition(), G4Deuteron::Definition(), G4He3::Definition(), G4Triton::Definition(), G4Etac::Definition(), G4Positron::Definition(), G4AntiLambdab::Definition(), G4Lambdab::Definition(), G4Geantino::Definition(), G4AdjointAlpha::Definition(), G4AdjointDeuteron::Definition(), G4AdjointHe3::Definition(), G4AdjointTriton::Definition(), G4Gamma::Definition(), G4ChargedGeantino::Definition(), G4OpticalPhoton::Definition(), G4UnknownParticle::Definition(), G4AdjointElectron::Definition(), G4AdjointElectronFI::Definition(), G4AdjointGenericIon::Definition(), G4AdjointPositron::Definition(), G4AdjointProton::Definition(), G4GenericMuonicAtom::Definition(), G4GenericIon::Definition(), G4AdjointGamma::Definition(), G4Electron_aq::Definition(), G4H2::Definition(), G4H2O::Definition(), G4H2O2::Definition(), G4H3O::Definition(), G4Hydrogen::Definition(), G4OH::Definition(), G4PSHitsModel::DescribeYourselfTo(), CCalVOrganization::DetectorLevel(), G4HadronicDeveloperParameters::DeveloperGet(), G4ReflectionFactory::Divide(), G4GDMLReadStructure::DivisionvolRead(), G4GDMLWriteStructure::DivisionvolWrite(), doContent(), doParseXmlDecl(), doProlog(), dtdCopy(), G4HadronicDeveloperParameters::Dump(), G4LatticeLogical::Dump_NMap(), G4LatticeLogical::DumpMap(), DicomBeamBlock::DumpToFile(), DicomBeamCompensator::DumpToFile(), DicomBeamWedge::DumpToFile(), G4GDMLReadSolids::ElconeRead(), G4GDMLWriteSolids::ElconeWrite(), G4GDMLReadMaterials::ElementRead(), G4GDMLWriteMaterials::ElementWrite(), G4GDMLReadSolids::EllipsoidRead(), G4GDMLWriteSolids::EllipsoidWrite(), G4GDMLReadSolids::EltubeRead(), G4GDMLWriteSolids::EltubeWrite(), Run::EndOfRun(), G4EnergyLossForExtrapolator::EnergyAfterStep(), G4EnergyLossForExtrapolator::EnergyBeforeStep(), G4EnergyLossForExtrapolator::EnergyDispersion(), ExP01TrackerSD::ExP01TrackerSD(), G4GDMLReadDefine::ExpressionRead(), G4AttUtils::ExtractAttDef(), G4AttUtils::ExtractAttValue(), pyG4Polycone::f1_CreatePolycone(), pyG4Polyhedra::f1_CreatePolyhedra(), pyG4Trap::f1_CreateTrap(), pyG4TwistedTrap::f1_CreateTwistedTrap(), pyG4TwistedTubs::f1_CreateTwistedTubs(), pyG4Polycone::f2_CreatePolycone(), pyG4Polyhedra::f2_CreatePolyhedra(), pyG4Trap::f2_CreateTrap(), pyG4TwistedTrap::f2_CreateTwistedTrap(), pyG4TwistedTubs::f2_CreateTwistedTubs(), pyG4Trap::f3_CreateTrap(), pyG4TwistedTubs::f3_CreateTwistedTubs(), pyG4Trap::f4_CreateTrap(), pyG4TwistedTubs::f4_CreateTwistedTubs(), pyG4Trap::f5_CreateTrap(), pyG4Trap::f6_CreateTrap(), FCALMaterialConsultant::FCALMaterialConsultant(), G4GDMLReadStructure::FileRead(), HadrontherapyMatrix::Fill(), HadrontherapyLet::FillEnergySpectrum(), G4VParticlePropertyReporter::FillList(), DicomRunAction::FillString(), B01RunAction::FillString(), B02RunAction::FillString(), B03RunAction::FillString(), G4HadronicInteractionRegistry::FindAllModels(), G4tgbMaterialMgr::FindBuiltG4Element(), G4tgbMaterialMgr::FindBuiltG4Isotope(), G4tgbMaterialMgr::FindBuiltG4Material(), G4tgrMaterialFactory::FindElement(), G4EmSaturation::FindG4BirksCoefficient(), G4tgbVolumeMgr::FindG4LogVol(), G4ElectronIonPair::FindG4MeanEnergyPerIonPair(), G4tgbVolumeMgr::FindG4PhysVol(), G4tgbRotationMatrixMgr::FindG4RotMatrix(), G4tgbVolumeMgr::FindG4Solid(), G4tgbMaterialMgr::FindG4tgbElement(), G4tgbMaterialMgr::FindG4tgbIsotope(), G4tgbMaterialMgr::FindG4tgbMaterial(), G4tgrMaterialFactory::FindIsotope(), G4NistMaterialBuilder::FindMaterial(), G4tgrMaterialFactory::FindMaterial(), WLSDetectorConstruction::FindMaterial(), G4NistManager::FindMaterial(), G4EmCalculator::FindMaterial(), G4IonisParamMat::FindMeanExcitationEnergy(), G4HadronicInteractionRegistry::FindModel(), G4EmModelActivator::FindOrAddProcess(), G4tgbMaterialMgr::FindOrBuildG4Element(), G4tgbMaterialMgr::FindOrBuildG4Isotope(), G4tgbMaterialMgr::FindOrBuildG4Material(), G4tgbRotationMatrixMgr::FindOrBuildG4RotMatrix(), G4NistMaterialBuilder::FindOrBuildMaterial(), G4NistManager::FindOrBuildMaterial(), G4tgbRotationMatrixMgr::FindOrBuildTgbRotMatrix(), G4RegionStore::FindOrCreateRegion(), G4tgrParameterMgr::FindParameter(), G4EnergyLossForExtrapolator::FindParticle(), G4EmCalculator::FindParticle(), ExTGRCRegionCutsMgr::FindRegionData(), G4AdjointCrossSurfChecker::FindRegisteredSurface(), G4tgrRotationMatrixFactory::FindRotMatrix(), G4tgbRotationMatrixMgr::FindTgbRotMatrix(), G4GDMLWriteDefine::FirstpositionWrite(), G4GDMLWriteDefine::FirstrotationWrite(), CML2Acc2::flatteningFilter(), G4ScoreQuantityMessenger::FParticleCommand(), G4ScoreQuantityMessenger::FParticleWithEnergyCommand(), G4DataSet::FullFileName(), G4RDEMDataSet::FullFileName(), G4EMDataSet::FullFileName(), function(), G4Allocator< G4KDNode< PointT > >::G4Allocator(), G4BOptnChangeCrossSection::G4BOptnChangeCrossSection(), G4BOptnForceCommonTruncatedExp::G4BOptnForceCommonTruncatedExp(), G4BOptnForceFreeFlight::G4BOptnForceFreeFlight(), G4BremsstrahlungParameters::G4BremsstrahlungParameters(), G4CascadeColliderBase::G4CascadeColliderBase(), G4CascadeDeexciteBase::G4CascadeDeexciteBase(), G4CrossSectionFactory< T, mode >::G4CrossSectionFactory(), G4CrossSectionFactory< T, 0 >::G4CrossSectionFactory(), G4CrossSectionFactory< T, 1 >::G4CrossSectionFactory(), G4CrossSectionFactory< T, 2 >::G4CrossSectionFactory(), G4eBremsstrahlungSpectrum::G4eBremsstrahlungSpectrum(), G4Element::G4Element(), G4ErrorGeomVolumeTarget::G4ErrorGeomVolumeTarget(), G4GenericTrap::G4GenericTrap(), G4GIDI_Misc_Z_A_m_ToName(), G4GIDI_Z_AMass(), G4gsdvx(), G4gsmate(), G4gsmixt(), G4HepRepViewer::G4HepRepViewer(), G4ImportanceBiasing::G4ImportanceBiasing(), G4LogicalVolume::G4LogicalVolume(), G4Material::G4Material(), G4MoleculeShootMessenger::G4MoleculeShootMessenger(), G4MultiSensitiveDetector::G4MultiSensitiveDetector(), G4MultiUnion::G4MultiUnion(), G4MuonicAtomDecayPhysics::G4MuonicAtomDecayPhysics(), G4PersistencyCenterMessenger::G4PersistencyCenterMessenger(), G4PhysicsConstructorFactory< T >::G4PhysicsConstructorFactory(), G4PhysListStamper< T >::G4PhysListStamper(), G4RDBremsstrahlungParameters::G4RDBremsstrahlungParameters(), G4RDeBremsstrahlungSpectrum::G4RDeBremsstrahlungSpectrum(), G4SDParticleWithEnergyFilter::G4SDParticleWithEnergyFilter(), G4UnitDefinition::G4UnitDefinition(), G4VisCommandSceneHandlerCreate::G4VisCommandSceneHandlerCreate(), G4VMultipleScattering::G4VMultipleScattering(), G4VSceneHandler::G4VSceneHandler(), G4VSensitiveDetector::G4VSensitiveDetector(), G4VViewer::G4VViewer(), G4WeightWindowBiasing::G4WeightWindowBiasing(), G4HtmlPPReporter::GenerateIndex(), G4AccumulableManager::GenerateName(), G4GDMLWrite::GenerateName(), G4TextPPReporter::GeneratePropertyTable(), G4HtmlPPReporter::GeneratePropertyTable(), G4GDMLReadSolids::GenericPolyconeRead(), G4GDMLWriteSolids::GenericPolyconeWrite(), G4GDMLReadSolids::GenericPolyhedraRead(), G4GDMLReadSolids::GenTrapRead(), G4GDMLWriteSolids::GenTrapWrite(), G4HadronicDeveloperParameters::Get(), G4HadronicDeveloperParameters::get(), G4AccumulableManager::GetAccumulable(), G4VUserPhysicsList::GetApplyCuts(), G4NistElementBuilder::GetAtomicMassAmu(), getAttributeId(), G4UnitDefinition::GetCategory(), B03ImportanceDetectorConstruction::GetCellName(), B02ImportanceDetectorConstruction::GetCellName(), B01DetectorConstruction::GetCellName(), G4tgrVolumeMgr::GetChildren(), G4CrossSectionDataSetRegistry::GetComponentCrossSection(), G4MoleculeTable::GetConfiguration(), G4GDMLEvaluator::GetConstant(), G4CrossSectionDataSetRegistry::GetCrossSectionDataSet(), G4VUserPhysicsList::GetCutValue(), G4DCIOcatalog::GetDCIOmanager(), G4HadronicDeveloperParameters::GetDefault(), G4GMocrenIO::getDoseDistName(), G4ChannelingMaterialData::GetEFXEl(), G4ChannelingMaterialData::GetEFYEl(), G4ChannelingMaterialData::GetElDEl(), G3EleTable::GetEle(), getElementType(), XrayFluoAnalysisManager::GetEmittedParticleEnergyAndType(), getEncodingIndex(), G4DCIOcatalog::GetEntry(), G4HCIOcatalog::GetEntry(), G4CrossSectionFactoryRegistry::GetFactory(), G4BaseFileManager::GetFullFileName(), G4HepRepSceneHandler::getFullTypeName(), B03ImportanceDetectorConstruction::GetGeometryCell(), B02ImportanceDetectorConstruction::GetGeometryCell(), G4HepRepSceneHandler::getGeometryType(), G4H1ToolsManager::GetH1Id(), G4H2ToolsManager::GetH2Id(), G4H3ToolsManager::GetH3Id(), G4HCIOcatalog::GetHCIOmanager(), G4BaseFileManager::GetHnFileName(), G4PhysicsModelCatalog::GetIndex(), G4ProductionCuts::GetIndex(), G4DNAGenericIonsManager::GetIon(), G4IonTable::GetIonName(), DicomIntersectVolume::GetLogicalVolumes(), G3VolTableEntry::GetMasterClone(), Materials::GetMaterial(), G4PhysListRegistry::GetModularPhysicsList(), G4PhysListRegistry::GetModularPhysicsListFromEnv(), G4MoleculeTable::GetMoleculeDefinition(), G4IonTable::GetMuonicAtom(), G4GIDI_target::getName(), G4BaseFileManager::GetNtupleFileName(), G4ChannelingMaterialData::GetNuDEl(), G4P1ToolsManager::GetP1Id(), G4P2ToolsManager::GetP2Id(), B03ImportanceDetectorConstruction::GetPhysicalVolumeByName(), B02ImportanceDetectorConstruction::GetPhysicalVolumeByName(), DicomIntersectVolume::GetPhysicalVolumes(), G4VModularPhysicsList::GetPhysics(), G4PhysicsConstructorRegistry::GetPhysicsConstructor(), G4BaseFileManager::GetPlotFileName(), G4ChannelingMaterialData::GetPotEl(), G4VScoringMesh::GetPrimitiveScorer(), G4ProductionCuts::GetProductionCut(), B02PVolumeStore::GetPVolume(), B03PVolumeStore::GetPVolume(), G4PhysListFactory::GetReferencePhysList(), g4alt::G4PhysListFactory::GetReferencePhysList(), G4RegionStore::GetRegion(), G4Hdf5RFileManager::GetRFile(), G4XmlRFileManager::GetRFile(), G4RootRFileManager::GetRFile(), G4SolidStore::GetSolid(), G4OpenInventorXtExaminerViewer::getSuperimpositionNode(), G4VITProcess::G4ProcessStateBase< T >::GetType(), G4UnitDefinition::GetValueOf(), G4GDMLEvaluator::GetVariable(), G4OpenInventorXtExaminerViewer::getViewPtNameCB(), G4LogicalVolumeStore::GetVolume(), G4PhysicalVolumeStore::GetVolume(), G4FastList< OBJECT >::TWatcher< WATCHER_TYPE >::GetWatcherName(), G4NistElementBuilder::GetZ(), HadrontherapyDetectorSD::HadrontherapyDetectorSD(), G4hICRU49He::HasMaterial(), G4hICRU49p::HasMaterial(), G4GDMLReadSolids::HypeRead(), G4GDMLWriteSolids::HypeWrite(), G4GDMLParser::ImportRegions(), G4GIDI_target::init(), DicomDetectorConstruction::InitialisationOfMaterials(), Materials::Initialise(), G4EmSaturation::InitialiseBirksCoefficient(), G4DNAChargeIncrease::InitialiseProcess(), G4DNAAttachment::InitialiseProcess(), G4DNAChargeDecrease::InitialiseProcess(), G4DNAElastic::InitialiseProcess(), G4DNAExcitation::InitialiseProcess(), G4DNAIonisation::InitialiseProcess(), G4DNAVibExcitation::InitialiseProcess(), G4MicroElecInelastic::InitialiseProcess(), G4MuElecInelastic::InitialiseProcess(), G4CoulombScattering::InitialiseProcess(), G4MoleculeTable::Insert(), G4PhysicsConstructorRegistry::IsKnownPhysicsConstructor(), G4GDMLReadMaterials::IsotopeRead(), G4GDMLWriteMaterials::IsotopeWrite(), G4PhysListFactory::IsReferencePhysList(), g4alt::G4PhysListFactory::IsReferencePhysList(), G4PhysListRegistry::IsReferencePhysList(), G4HadronicDeveloperParameters::issue_has_changed(), G4HadronicDeveloperParameters::issue_is_already_defined(), G4HadronicDeveloperParameters::issue_is_modified(), G4HadronicDeveloperParameters::issue_no_param(), G4HadronicDeveloperParameters::issue_non_eligible_value(), G4UnitDefinition::IsUnitDefined(), G4GDMLEvaluator::IsVariable(), G4ITTransportationManager::IsWorldExisting(), G4TransportationManager::IsWorldExisting(), CML2Acc1::Jaw1X(), CML2Acc2::Jaw1X(), CML2Acc1::Jaw1Y(), CML2Acc2::Jaw1Y(), CML2Acc1::Jaw2X(), CML2Acc2::Jaw2X(), CML2Acc1::Jaw2Y(), CML2Acc2::Jaw2Y(), G03DetectorConstruction::ListOfMaterials(), G02DetectorConstruction::ListOfMaterials(), G4MoleculeDefinition::Load(), G4DopplerProfile::LoadBiggsP(), G4RDDopplerProfile::LoadBiggsP(), G4RDShellData::LoadData(), G4ShellData::LoadData(), G4eIonisationParameters::LoadData(), G4RDeIonisationParameters::LoadData(), G4BremsstrahlungParameters::LoadData(), G4RDBremsstrahlungParameters::LoadData(), G4FluoData::LoadData(), G4RDFluoData::LoadData(), G4AugerData::LoadData(), G4RDAugerData::LoadData(), G4DopplerProfile::LoadProfile(), G4RDDopplerProfile::LoadProfile(), XrayFluoHPGeDetectorType::LoadResponseData(), XrayFluoSiLiDetectorType::LoadResponseData(), lookup(), lPoPs_addParticleIfNeeded(), G4InuclNuclei::makeNuclearFragment(), G4BaryonWidth::MassDependentWidth(), G4BaryonPartialWidth::MassDependentWidth(), G4GDMLReadMaterials::MaterialRead(), DetectorConstruction::MaterialWithSingleIsotope(), G4GDMLWriteMaterials::MaterialWrite(), G4GDMLReadDefine::MatrixRead(), MCGIDI_misc_pointerToAttributeIfAllOk(), MCGIDI_misc_pointerToTOMAttributeIfAllOk(), MCGIDI_miscNameToZAm(), MCGIDI_miscNameToZAm_getLevel(), MCGIDI_particle_getInternalID(), MCGIDI_particle_printInternalSortedList(), MCGIDI_particleMass_AMU(), MCGIDI_POP_new(), MCGIDI_POPs_addParticleIfNeeded(), MCGIDI_POPs_findParticle(), MCGIDI_POPs_findParticleIndex(), MCGIDI_product_parseFromTOM(), MCGIDI_target_getAttributesValue(), MCGIDI_target_heated_parseParticle(), MCGIDI_target_heated_parseParticleGammas(), MCGIDI_target_heated_parseParticleLevel(), MCGIDI_target_heated_read(), Run::Merge(), G4ResonanceNames::MinMass(), G4TextPPRetriever::ModifyPropertyTable(), G4hParametrisedLossModel::MolecIsInZiegler1988(), G4GDMLReadSolids::MultiUnionNodeRead(), G4GDMLReadSolids::MultiUnionRead(), G4GDMLWriteSolids::MultiUnionWrite(), G4XNNTotal::Name(), G4XNNTotalLowE::Name(), G4XAqmTotal::Name(), G4XNNElasticLowE::Name(), G4XnpTotal::Name(), G4XnpElastic::Name(), G4XNNElastic::Name(), G4XAnnihilationChannel::Name(), G4XAqmElastic::Name(), G4XMesonBaryonElastic::Name(), G4XPDGElastic::Name(), G4XPDGTotal::Name(), G4XnpElasticLowE::Name(), G4XnpTotalLowE::Name(), G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), OneProcessCount::OneProcessCount(), G4HepRepSceneHandler::open(), G4RootFileManager::OpenFile(), G4Hdf5FileManager::OpenFile(), GammaRayTelRunAction::OpenFile(), G4HepRepSceneHandler::openFile(), G4RootMpiAnalysisManager::OpenFileImpl(), G4XmlAnalysisManager::OpenFileImpl(), G4Hdf5AnalysisManager::OpenFileImpl(), G4RootAnalysisManager::OpenFileImpl(), G4RootFileManager::OpenNtupleFiles(), G4XmlRFileManager::OpenRFile(), G4RootRFileManager::OpenRFile(), G4Hdf5RFileManager::OpenRFile(), operator<<(), G4GDMLReadSolids::OpticalSurfaceRead(), G4GDMLWriteSolids::OpticalSurfaceWrite(), G4GDMLReadSolids::OrbRead(), G4GDMLWriteSolids::OrbWrite(), G4MPIscorerMerger::Pack(), G4PersistencyCenter::PadString(), G4GDMLReadSolids::ParaboloidRead(), G4GDMLWriteSolids::ParaboloidWrite(), G4GDMLWriteParamvol::ParametersWrite(), G4GDMLReadSolids::ParaRead(), G4GDMLWriteSolids::ParaWrite(), G3EleTable::parse(), Run::ParticleCount(), Run::ParticleCountNeuron(), Run::ParticleFlux(), PG4gsatt(), PG4gsdvx(), PG4gsmate(), PG4gsmixt(), PG4gspos(), PG4gsposp(), PG4gstmed(), G4STRead::PhysvolRead(), G4GDMLReadStructure::PhysvolRead(), G4GDMLWriteStructure::PhysvolWrite(), G4OpenInventorXtExaminerViewer::pickingCB(), G4ReflectionFactory::Place(), G4PlotManager::PlotAndWrite(), G4GDMLReadSolids::PolyconeRead(), G4GDMLWriteSolids::PolyconeWrite(), G4GDMLReadSolids::PolyhedraRead(), G4GDMLWriteSolids::PolyhedraWrite(), PoP_makeAlias(), PoP_makeParticle(), PoPs_addAliasIfNeeded(), PoPs_getAtomsIndex(), PoPs_getAtomsName(), PoPs_getGenre(), PoPs_getMassInUnitOf(), PoPs_getZ_A_l(), PoPs_hasNucleus(), PoPs_particleCreateLoadInfo(), PoPs_particleIndex(), PoPs_particleIndex_smr(), PoPs_particleLoadInfo(), PoPs_particleMass_AMU(), PoPs_particleReadDatabase(), PoPs_setBDFLS_File(), PoPs_sortedParticleIndex(), G4GDMLWriteDefine::Position_vectorWrite(), G4GDMLReadDefine::PositionRead(), G4GDMLWriteDefine::PositionWrite(), G4CollisionManager::Print(), G4VisListManager< T >::Print(), G4VCollision::Print(), G4VisModelManager< G4VTrajectoryModel >::Print(), G4VisFilterManager< G4VTrajectory >::Print(), G4PersistencyCenter::PrintAll(), G4VisManager::PrintAvailableGraphicsSystems(), G4VisManager::PrintAvailableUserVisActions(), Run::PrintFluence(), G4NistManager::PrintG4Element(), G4NistManager::PrintG4Material(), G4MCTSimParticle::PrintSingle(), HistoManager::PrintStatistic(), ProcessCount::ProcessCount(), FCALTestbeamSetupSD::ProcessHits(), G4LatticeReader::ProcessValue(), G4PhysicalVolumeSearchScene::ProcessVolume(), G4PhysicalVolumesSearchScene::ProcessVolume(), G4GDMLReadMaterials::PropertyRead(), G4GDMLReadSolids::PropertyRead(), G4GDMLReadDefine::QuantityRead(), G4STRead::Read(), READ< G4String >(), G4ParticleHPThermalScattering::readACoherentFSDATA(), G4ParticleHPThermalScattering::readAnIncoherentFSDATA(), G4ParticleHPThermalScattering::readAnInelasticFSDATA(), XrayFluoRunAction::ReadData(), CCalMaterialFactory::readElements(), G4STRead::ReadGeom(), CCalMaterialFactory::readMaterials(), readName(), G4STRead::ReadTree(), G4PhysListFactory::ReferencePhysList(), G4GDMLReadSolids::ReflectedSolidRead(), G4PhysicsModelCatalog::Register(), G4CrossSectionFactoryRegistry::Register(), G4ParticleHPChannelList::Register(), G4AccumulableManager::RegisterAccumulable(), PhysicsList::RegisterConstructor(), G4VisManager::RegisterEndOfEventUserVisAction(), G4VisManager::RegisterEndOfRunUserVisAction(), G4IonTable::RegisterIsotopeTable(), G4coutFormatters::RegisterNewStyle(), G4VisManager::RegisterRunDurationUserVisAction(), G4Track::RemoveAuxiliaryTrackInformation(), WLSPhysicsList::RemoveFromPhysicsList(), G4VModularPhysicsList::RemovePhysics(), G4GDMLReadStructure::ReplicaRead(), G4ReflectionFactory::Replicate(), G4CascadeCoalescence::reportArgs(), G4CascadeCoalescence::reportResult(), G4ExtendedMaterial::RetrieveExtension(), G4GDMLWriteDefine::Rotation_vectorWrite(), G4GDMLReadDefine::RotationRead(), G4GDMLWriteDefine::RotationWrite(), HistoManager::SaveAscii(), CanvasInTab::SaveCanvas(), G4DataSet::SaveData(), G4RDEMDataSet::SaveData(), G4EMDataSet::SaveData(), G4OpenInventorXtExaminerViewer::saveViewPt(), G4GDMLWriteDefine::Scale_vectorWrite(), G4GDMLReadSolids::ScaledSolidRead(), G4GDMLWriteSolids::ScaledWrite(), G4GDMLReadDefine::ScaleRead(), G4GDMLWriteDefine::ScaleWrite(), G4HadronicDeveloperParameters::Set(), G4TrajectoryDrawByAttribute::Set(), G4AttributeFilterT< T >::Set(), G4LowEnergyPhotoElectric::SetAngularGenerator(), G4LowEnergyBremsstrahlung::SetAngularGenerator(), G4VUserPhysicsList::SetApplyCuts(), G4HepRepSceneHandler::setAttribute(), HadrontherapyRBE::SetCellLine(), DetectorConstruction::SetContainerMaterial(), G4VisListManager< T >::SetCurrent(), G4VScoringMesh::SetCurrentPrimitiveScorer(), G4VUserPhysicsList::SetCutValue(), G4HadronicDeveloperParameters::SetDefault(), g4alt::G4PhysListFactory::SetDefaultReferencePhysList(), HistoManager::SetElementName(), setElementTypePrefix(), HepMCG4AsciiReader::SetFileName(), HistoManager::SetFileName(), G4MoleculeDefinition::SetFormatedName(), DetectorConstruction::SetGasMaterial(), HadrontherapyGeometryController::SetGeometry(), IORTGeometryController::SetGeometry(), G4RadioactiveDecayChainsFromParent::SetIonName(), StackingAction::SetKill(), G4ExcitedMesons::SetMultipletName(), G4ExcitedBaryons::SetMultipletName(), G4VCascadeCollider::setName(), G4AttValue::SetName(), CCalG4Able::setName(), G4tgrVolume::SetName(), G4AttDef::SetName(), G3VolTableEntry::SetName(), G4SurfaceProperty::SetName(), G4Isotope::SetName(), G4VViewer::SetName(), G4Element::SetName(), G4Material::SetName(), G4H2Messenger::SetNewValue(), G4P2Messenger::SetNewValue(), G4H3Messenger::SetNewValue(), G4P1Messenger::SetNewValue(), G4VisCommandListManagerList< Manager >::SetNewValue(), G4H1Messenger::SetNewValue(), WLSPhysicsListMessenger::SetNewValue(), CexmcScenePrimitivesMessenger::SetNewValue(), G4ScoreQuantityMessenger::SetNewValue(), G4VisCommandSceneHandlerList::SetNewValue(), G4UserPhysicsListMessenger::SetNewValue(), G4VisCommandSceneList::SetNewValue(), G4VisCommandSetTouchable::SetNewValue(), G4VisCommandListManagerSelect< Manager >::SetNewValue(), G4VisCommandManagerMode< Manager >::SetNewValue(), G4VisCommandGeometrySetColour::SetNewValue(), G4VisCommandGeometrySetDaughtersInvisible::SetNewValue(), G4VisCommandGeometrySetForceAuxEdgeVisible::SetNewValue(), G4VisCommandViewerList::SetNewValue(), G4VisCommandGeometrySetForceSolid::SetNewValue(), G4VisCommandGeometrySetForceLineSegmentsPerCircle::SetNewValue(), G4VisCommandGeometrySetForceWireframe::SetNewValue(), G4VisCommandGeometrySetLineStyle::SetNewValue(), G4VisCommandSceneAddLogicalVolume::SetNewValue(), G4VisCommandGeometrySetLineWidth::SetNewValue(), G4VisCommandGeometrySetVisibility::SetNewValue(), G4VisCommandSceneAddUserAction::SetNewValue(), G4VisCommandSceneAddVolume::SetNewValue(), G4ASCIITree::SetOutFileName(), G4GenericMessenger::Command::SetParameterName(), DMXScintHit::SetParticle(), HistoManager::SetParticleName(), G4PersistencyCenter::SetPersistencyManager(), G4VPhysicsConstructor::SetPhysicsName(), G4hImpactIonisation::SetPixeCrossSectionK(), G4hImpactIonisation::SetPixeCrossSectionL(), G4hImpactIonisation::SetPixeCrossSectionM(), G4EmProcessOptions::SetProcessBiasingFactor(), G4GDMLReadSetup::SetupRead(), G4PhysListRegistry::SetUserDefaultPhysList(), G4GDMLEvaluator::SetVariable(), G4OpticalPhysics::SetWLSTimeProfile(), G4ImportanceConfigurator::SetWorldName(), TransitionRadiationPhysics::SetXTRModel(), PhysicsList::SetXTRModel(), G4ResonanceNames::ShortName(), G3toG4DetectorConstruction::SimpleConstruct(), G4GDMLReadStructure::SkinSurfaceRead(), G4GDMLReadSolids::SphereRead(), G4GDMLWriteSolids::SphereWrite(), storeAtts(), G4GMocrenIO::storeData4(), HadrontherapyMatrix::StoreDoseData(), storeEntityValue(), HadrontherapyMatrix::StoreFluenceData(), G4ProductionCutsTable::StoreMaterialInfo(), G4VMultipleScattering::StorePhysicsTable(), G4VEmProcess::StorePhysicsTable(), G4VEnergyLossProcess::StoreTable(), G4GDMLRead::Strip(), G4GDMLRead::StripName(), G4tgbGeometryDumper::SubstituteRefl(), G4tgbGeometryDumper::SupressRefl(), G4BaseFileManager::TakeOffExtension(), G4STRead::TessellatedRead(), G4GDMLReadSolids::TessellatedRead(), G4GDMLWriteSolids::TessellatedWrite(), G4GDMLReadSolids::TetRead(), G4GDMLWriteSolids::TetWrite(), G4GDMLReadSolids::TorusRead(), G4GDMLWriteSolids::TorusWrite(), G4GDMLReadSolids::TrapRead(), G4GDMLWriteSolids::TrapWrite(), G4GDMLWriteStructure::TraverseVolumeTree(), G4GDMLReadSolids::TrdRead(), G4GDMLWriteSolids::TrdWrite(), G4GDMLReadSolids::TubeRead(), G4GDMLWriteSolids::TubeWrite(), G4GDMLReadSolids::TwistedboxRead(), G4GDMLWriteSolids::TwistedboxWrite(), G4GDMLReadSolids::TwistedtrapRead(), G4GDMLWriteSolids::TwistedtrapWrite(), G4GDMLReadSolids::TwistedtrdRead(), G4GDMLWriteSolids::TwistedtrdWrite(), G4GDMLReadSolids::TwistedtubsRead(), G4GDMLWriteSolids::TwistedtubsWrite(), G4MPIscorerMerger::UnPackAndMerge(), DMXSteppingAction::UserSteppingAction(), G4OpWLS::UseTimeProfile(), variable(), G4GDMLReadDefine::VariableRead(), G03ColorReader::VolumeRead(), G4GDMLReadStructure::VolumeRead(), WRITE< G4String >(), G4VAnalysisManager::WriteAscii(), EventAction::WriteFibers(), G4Hdf5AnalysisManager::WriteImpl(), G4XmlAnalysisManager::WriteImpl(), ScoreSpecies::WriteWithAnalysisManager(), xDataTOM_addElementInElement(), xDataTOM_getAttributesValueInElement(), xDataTOM_getLinksElement2(), xDataTOM_getLinksElement3(), xDataTOM_mallocElement(), xDataTOM_numberOfElementsByName(), xDataTOMAL_addAttribute(), xDataTOMAL_convertAttributeToDouble(), xDataTOMAL_convertAttributeToInteger(), xDataTOMAL_getAttributesValue(), xDataTOME_addAttribute(), xDataTOME_convertAttributeToDouble(), xDataTOME_convertAttributeToInteger(), xDataTOME_getOneElementByName(), xDataTOME_initializeElement(), xDataXML_addElementToRoot(), xDataXML_convertAttributeTo_xDataTOM_Int(), xDataXML_convertAttributeToDouble(), xDataXML_getAttributesValue(), xDataXML_getAttributesValueInElement(), xDataXML_getOneElementByTagName(), xDataXML_getTraceback(), xDataXML_getTraceback2(), xDataXML_isAttributeInElement(), xDataXML_isAttributeInList(), xDataXML_parseStartElement(), G4GDMLReadSolids::XtruRead(), G4GDMLWriteSolids::XtruWrite(), and G4Cache< F02ElectricFieldSetup * >::~G4Cache().
nameLong()
const char * G4InuclParticleNames::nameLong (G4int ptype)
Definition at line 38 of file G4InuclParticleNames.cc.
Referenced by name().
nameShort()
const char * G4InuclParticleNames::nameShort (G4int ptype)
Definition at line 91 of file G4InuclParticleNames.cc.
nucleon()
G4bool G4InuclParticleNames::nucleon (G4int ityp) inline
Definition at line 94 of file G4InuclParticleNames.hh.
Referenced by G4Analyser::analyse(), G4BinaryCascade::BuildTargetList(), G4HadronNucleonXsc::ComputeKaonNucleonXsc(), G4HadronNucleonXsc::CoulombBarrier(), G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::CrossSectionsMultiPionsAndResonances::etaNElastic(), G4INCL::CrossSectionsMultiPionsAndResonances::etaNToPiN(), G4INCL::CrossSectionsMultiPionsAndResonances::etaNToPiPiN(), G4INCL::NKToNKChannel::fillFinalState(), G4INCL::NKToNKpiChannel::fillFinalState(), G4INCL::NLToNSChannel::fillFinalState(), G4INCL::NpiToLK2piChannel::fillFinalState(), G4INCL::NpiToLKChannel::fillFinalState(), G4INCL::NSToNSChannel::fillFinalState(), G4INCL::NpiToLKpiChannel::fillFinalState(), G4INCL::NKToNK2piChannel::fillFinalState(), G4INCL::NpiToSK2piChannel::fillFinalState(), G4INCL::NpiToSKChannel::fillFinalState(), G4INCL::NpiToNKKbChannel::fillFinalState(), G4INCL::NSToNLChannel::fillFinalState(), G4INCL::NpiToSKpiChannel::fillFinalState(), G4INCL::NYElasticChannel::fillFinalState(), G4INCL::OmegaNElasticChannel::fillFinalState(), G4INCL::OmegaNToPiNChannel::fillFinalState(), G4INCL::OmegaNToPiPiNChannel::fillFinalState(), G4INCL::PiNElasticChannel::fillFinalState(), G4INCL::PiNToDeltaChannel::fillFinalState(), G4INCL::PiNToEtaChannel::fillFinalState(), G4INCL::EtaNElasticChannel::fillFinalState(), G4INCL::PiNToOmegaChannel::fillFinalState(), G4INCL::EtaNToPiNChannel::fillFinalState(), G4INCL::EtaNToPiPiNChannel::fillFinalState(), G4INCL::NDeltaToDeltaLKChannel::fillFinalState(), G4INCL::NKbElasticChannel::fillFinalState(), G4INCL::PiNToMultiPionsChannel::fillFinalState(), G4INCL::NKbToL2piChannel::fillFinalState(), G4INCL::NKbToLpiChannel::fillFinalState(), G4INCL::NKbToNKb2piChannel::fillFinalState(), G4INCL::NKbToNKbChannel::fillFinalState(), G4INCL::NKbToNKbpiChannel::fillFinalState(), G4INCL::NKbToS2piChannel::fillFinalState(), G4INCL::NKbToSpiChannel::fillFinalState(), G4INCL::NKElasticChannel::fillFinalState(), G4INCL::StrangeAbsorbtionChannel::fillFinalState(), G4FTFParticipants::GetList(), G4HadronNucleonXsc::HadronNucleonXscNS(), G4HadronNucleonXsc::HadronNucleonXscPDG(), G4HadronNucleonXsc::HadronNucleonXscPDG2005(), G4HadronNucleonXsc::HadronNucleonXscVU(), G4INCL::NpiToLKChannel::KaonMomentum(), G4INCL::NpiToSKChannel::KaonMomentum(), G4INCL::NKbToSpiChannel::KaonMomentum(), G4INCL::NKbElasticChannel::KaonMomentum(), G4INCL::NKbToNKbChannel::KaonMomentum(), G4INCL::NKbToLpiChannel::KaonMomentum(), G4HadronNucleonXsc::KaonNucleonXscGG(), G4HadronNucleonXsc::KaonNucleonXscNS(), G4HadronNucleonXsc::KaonNucleonXscVG(), G4INCL::CrossSectionsStrangeness::NKbelastic(), G4INCL::CrossSectionsStrangeness::NKbToL2pi(), G4INCL::CrossSectionsStrangeness::NKbToLpi(), G4INCL::CrossSectionsStrangeness::NKbToNKb(), G4INCL::CrossSectionsStrangeness::NKbToNKb2pi(), G4INCL::CrossSectionsStrangeness::NKbToNKbpi(), G4INCL::CrossSectionsStrangeness::NKbToS2pi(), G4INCL::CrossSectionsStrangeness::NKbToSpi(), G4INCL::CrossSectionsStrangeness::NKelastic(), G4INCL::CrossSectionsStrangeness::NpiToLK(), G4INCL::CrossSectionsStrangeness::NpiToLK2pi(), G4INCL::CrossSectionsStrangeness::NpiToLKpi(), G4INCL::CrossSectionsStrangeness::NpiToMissingStrangeness(), G4INCL::CrossSectionsStrangeness::NpiToSK(), G4INCL::CrossSectionsStrangeness::NpiToSK2pi(), G4INCL::CrossSectionsStrangeness::NpiToSKpi(), G4InuclElementaryParticle::nucleon(), G4INCL::CrossSectionsStrangeness::NYelastic(), G4INCL::CrossSectionsMultiPionsAndResonances::omegaNElastic(), G4INCL::CrossSectionsMultiPionsAndResonances::omegaNInelastic(), operator<<(), G4NucleiModel::passFermi(), G4INCL::CrossSectionsMultiPions::piMinuspIne(), G4INCL::CrossSectionsMultiPions::piMinuspOnePi(), G4INCL::CrossSectionsMultiPions::piMinuspTwoPi(), G4INCL::CrossSectionsMultiPions::piNIne(), G4INCL::CrossSectionsMultiPions::piNOnePi(), G4INCL::CrossSectionsMultiPions::piNToxPiN(), G4INCL::CrossSectionsMultiPions::piNTwoPi(), G4INCL::CrossSectionsMultiPions::piPluspIne(), G4INCL::CrossSectionsMultiPions::piPluspOnePi(), G4INCL::CrossSectionsMultiPions::piPluspTwoPi(), and G4CascadeCoalescence::selectCandidates().
pion()
G4bool G4InuclParticleNames::pion (G4int ityp) inline
Definition at line 90 of file G4InuclParticleNames.hh.
Referenced by G4Analyser::analyse(), GammaRayTelHadronPhysics::ConstructProcess(), G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::PiNToMultiPionsChannel::fillFinalState(), G4INCL::NNToNSKpiChannel::fillFinalState(), G4INCL::NpiToLK2piChannel::fillFinalState(), G4INCL::NpiToLKChannel::fillFinalState(), G4INCL::NpiToLKpiChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::NpiToNKKbChannel::fillFinalState(), G4INCL::NpiToSK2piChannel::fillFinalState(), G4INCL::NKbToL2piChannel::fillFinalState(), G4INCL::NpiToSKChannel::fillFinalState(), G4INCL::NpiToSKpiChannel::fillFinalState(), G4INCL::PiNElasticChannel::fillFinalState(), G4INCL::PiNToDeltaChannel::fillFinalState(), G4INCL::PiNToEtaChannel::fillFinalState(), G4INCL::NKbToNKbpiChannel::fillFinalState(), G4INCL::NNToNLKpiChannel::fillFinalState(), G4INCL::NKbToS2piChannel::fillFinalState(), G4INCL::PiNToOmegaChannel::fillFinalState(), G4INCL::NKToNKpiChannel::fillFinalState(), G4INCL::NNEtaToMultiPionsChannel::fillFinalState(), G4INCL::NNOmegaToMultiPionsChannel::fillFinalState(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NNToMultiPionsChannel::fillFinalState(), G4INCL::DeltaDecayChannel::fillFinalState(), G4INCL::NpiToLKChannel::KaonMomentum(), G4INCL::NpiToSKChannel::KaonMomentum(), G4ResonanceNames::MinMass(), G4INCL::CrossSectionsStrangeness::NpiToLK(), G4INCL::CrossSectionsStrangeness::NpiToLK2pi(), G4INCL::CrossSectionsStrangeness::NpiToLKpi(), G4INCL::CrossSectionsStrangeness::NpiToMissingStrangeness(), G4INCL::CrossSectionsStrangeness::NpiToSK(), G4INCL::CrossSectionsStrangeness::NpiToSK2pi(), G4INCL::CrossSectionsStrangeness::NpiToSKpi(), G4INCL::CrossSectionsMultiPions::piMinuspIne(), G4INCL::CrossSectionsMultiPions::piMinuspOnePi(), G4INCL::CrossSectionsMultiPions::piMinuspTwoPi(), G4INCL::CrossSectionsMultiPions::piNIne(), G4INCL::CrossSectionsMultiPions::piNOnePi(), G4INCL::CrossSectionsMultiPions::piNToxPiN(), G4INCL::CrossSectionsMultiPions::piNTwoPi(), G4InuclElementaryParticle::pion(), G4INCL::CrossSectionsMultiPions::piPluspIne(), G4INCL::CrossSectionsMultiPions::piPluspOnePi(), and G4INCL::CrossSectionsMultiPions::piPluspTwoPi().
quasi_deutron()
G4bool G4InuclParticleNames::quasi_deutron (G4int ityp) inline
Definition at line 100 of file G4InuclParticleNames.hh.
Referenced by G4InuclElementaryParticle::quasi_deutron().