Geant4: CLHEP Namespace Reference
CLHEP Namespace Reference
Namespaces
detail
Functions
static void ZMpvAxisAngleRep (const HepAxisAngle &aa, double array[])
std::ostream & operator<< (std::ostream &os, const HepAxisAngle &aa)
void ZMinputAxisAngle (std::istream &is, double &x, double &y, double &z, double &delta)
std::istream & operator>> (std::istream &is, HepAxisAngle &aa)
template<class E >
static HepRandomEngine * makeAnEngine (const std::string &tag, std::istream &is)
template<class E >
static HepRandomEngine * makeAnEngine (const std::vector< unsigned long > &v)
static std::vector< unsigned long > gen_crc_table ()
unsigned long crc32ul (const std::string &s)
static void ZMpvEulerAnglesRep (const HepEulerAngles &ex, double array[])
std::ostream & operator<< (std::ostream &os, const HepEulerAngles &ea)
void ZMinput3doubles (std::istream &is, const char *type, double &x, double &y, double &z)
std::istream & operator>> (std::istream &is, HepEulerAngles &ea)
double transformSmall (double r)
HepLorentzRotation operator* (const HepRotation &r, const HepLorentzRotation &lt)
std::ostream & operator<< (std::ostream &os, const HepLorentzVector &v1)
std::istream & operator>> (std::istream &is, HepLorentzVector &v1)
HepLorentzVector operator/ (const HepLorentzVector &w, double c)
HepLorentzVector rotationXOf (const HepLorentzVector &vec, double phi)
HepLorentzVector rotationYOf (const HepLorentzVector &vec, double phi)
HepLorentzVector rotationZOf (const HepLorentzVector &vec, double phi)
HepLorentzVector rotationOf (const HepLorentzVector &vec, const Hep3Vector &aaxis, double ddelta)
HepLorentzVector rotationOf (const HepLorentzVector &vec, const HepAxisAngle &ax)
HepLorentzVector rotationOf (const HepLorentzVector &vec, const HepEulerAngles &e1)
HepLorentzVector rotationOf (const HepLorentzVector &vec, double phi1, double theta1, double psi1)
static double StirlingCorrection (long int k)
std::ostream & operator<< (std::ostream &os, const HepRandom &dist)
std::istream & operator>> (std::istream &is, HepRandom &dist)
std::ostream & operator<< (std::ostream &os, const HepRandomEngine &e)
std::istream & operator>> (std::istream &is, HepRandomEngine &e)
double gammln (double xx)
static double normal (HepRandomEngine *eptr)
static double safe_acos (double x)
static double safe_acos (double x)
static void correctByPi (double &psi1, double &phi1)
static void correctPsiPhi (double rxz, double rzx, double ryz, double rzy, double &psi1, double &phi1)
static double safe_acos (double x)
static double safe_acos (double x)
static double safe_acos (double x)
Hep3Vector rotationOf (const Hep3Vector &vec, const HepAxisAngle &ax)
Hep3Vector rotationOf (const Hep3Vector &vec, const Hep3Vector &axis, double ddelta)
Hep3Vector rotationOf (const Hep3Vector &vec, const HepEulerAngles &ex)
Hep3Vector rotationOf (const Hep3Vector &vec, double phi, double theta, double psi)
Hep3Vector rotationXOf (const Hep3Vector &vec, double ddelta)
Hep3Vector rotationYOf (const Hep3Vector &vec, double ddelta)
Hep3Vector rotationZOf (const Hep3Vector &vec, double ddelta)
std::ostream & operator<< (std::ostream &os, const Hep3Vector &v)
std::istream & operator>> (std::istream &is, Hep3Vector &v)
const Hep3Vector HepXHat (1.0, 0.0, 0.0)
const Hep3Vector HepYHat (0.0, 1.0, 0.0)
const Hep3Vector HepZHat (0.0, 0.0, 1.0)
Hep3Vector operator/ (const Hep3Vector &v1, double c)
Hep2Vector operator/ (const Hep2Vector &p, double a)
std::ostream & operator<< (std::ostream &os, const Hep2Vector &q)
void ZMinput2doubles (std::istream &is, const char *type, double &x, double &y)
std::istream & operator>> (std::istream &is, Hep2Vector &p)
Variables
static const int MarkerLen = 64
static const int Tsizes [5]
static const double Tsteps [5]
static const int Toffsets [5]
static const double gaussTables [2 *TableSize]
static const int MarkerLen = 64
static const int MarkerLen = 64
static const int MarkerLen = 64
static const float gaussTables [TableSize]
static const float TABLE_INTERVAL = .001f
static const int TABLE_END = 982
static const float TABLE_MULTIPLIER = 1.0f/TABLE_INTERVAL
static const float inverseLandau [TABLE_END+1]
static const double poissonTables [51 *((95-10)/5+1)]
static const int MarkerLen = 64
static const double prec = 4.6566128E-10
static const int MarkerLen = 64
static const int MarkerLen = 64
static const int MarkerLen = 64
Function Documentation
correctByPi()
static void CLHEP::correctByPi (double & psi1, double & phi1) static
Definition at line 148 of file RotationE.cc.
Referenced by correctPsiPhi().
correctPsiPhi()
static void CLHEP::correctPsiPhi (double rxz, double rzx, double ryz, double rzy, double & psi1, double & phi1) static
Definition at line 162 of file RotationE.cc.
crc32ul()
unsigned long CLHEP::crc32ul (const std::string & s)
Definition at line 36 of file engineIDulong.cc.
gammln()
double CLHEP::gammln (double xx)
Definition at line 53 of file RandPoisson.cc.
gen_crc_table()
static std::vector<unsigned long> CLHEP::gen_crc_table () static
Definition at line 18 of file engineIDulong.cc.
Referenced by crc32ul().
HepXHat()
const Hep3Vector CLHEP::HepXHat (1. 0, 0. 0, 0. 0)
Referenced by G4GPSModel::DescribeYourselfTo(), G4CrystalUnitCell::G4CrystalUnitCell(), G4SPSAngDistribution::G4SPSAngDistribution(), G4SPSPosDistribution::G4SPSPosDistribution(), and G4SPSPosDistribution::thread_data_t::thread_data_t().
HepYHat()
const Hep3Vector CLHEP::HepYHat (0. 0, 1. 0, 0. 0)
Referenced by G4GPSModel::DescribeYourselfTo(), G4CrystalUnitCell::G4CrystalUnitCell(), G4SPSAngDistribution::G4SPSAngDistribution(), G4SPSPosDistribution::G4SPSPosDistribution(), and G4SPSPosDistribution::thread_data_t::thread_data_t().
HepZHat()
const Hep3Vector CLHEP::HepZHat (0. 0, 0. 0, 1. 0)
Referenced by G4GPSModel::DescribeYourselfTo(), G4CrystalUnitCell::G4CrystalUnitCell(), G4SPSAngDistribution::G4SPSAngDistribution(), G4SPSPosDistribution::G4SPSPosDistribution(), and G4SPSPosDistribution::thread_data_t::thread_data_t().
makeAnEngine() [1/2]
template<class E > static HepRandomEngine* CLHEP::makeAnEngine (const std::string & tag, std::istream & is) static
Definition at line 31 of file EngineFactory.cc.
makeAnEngine() [2/2]
template<class E > static HepRandomEngine* CLHEP::makeAnEngine (const std::vector< unsigned long > & v) static
Definition at line 42 of file EngineFactory.cc.
normal()
static double CLHEP::normal (HepRandomEngine * eptr) static
Definition at line 76 of file RandPoisson.cc.
Referenced by G4PolyconeSide::CalculateExtent(), G4VSceneHandler::CreateSectionSolid(), G4ErrorMatrix::dfact_matrix(), G4PolyhedraSide::Distance(), G4VTwistedFaceted::DistanceToIn(), G4VTwistSurface::DistanceToIn(), G4Paraboloid::DistanceToIn(), G4TwistedTubs::DistanceToIn(), G4TessellatedSolid::DistanceToInCandidates(), G4TessellatedSolid::DistanceToInNoVoxels(), G4VCSGfaceted::DistanceToOut(), G4ScaledSolid::DistanceToOut(), G4VTwistSurface::DistanceToOut(), G4VTwistedFaceted::DistanceToOut(), G4Tet::DistanceToOut(), G4Paraboloid::DistanceToOut(), G4TwistedTubs::DistanceToOut(), G4TessellatedSolid::DistanceToOutCandidates(), G4TessellatedSolid::DistanceToOutNoVoxels(), G4TwistTubsSide::DistanceToSurface(), G4ErrorPlaneSurfaceTarget::Dump(), G4LambertianRand(), G4PlaneVectorRand(), G4QuadrangularFacet::G4QuadrangularFacet(), G4TwistTubsFlatSide::G4TwistTubsFlatSide(), G4SPSEneDistribution::GenerateBiasPowEnergies(), G4PrimaryTransformer::GenerateSingleTrack(), G4ErrorPlaneSurfaceTarget::GetDistanceFromPoint(), G4PolarizationHelper::GetFrame(), G4ErrorPropagationNavigator::GetGlobalExitNormal(), G4TwistBoxSide::GetNormal(), G4TwistTrapAlphaSide::GetNormal(), G4TwistTrapParallelSide::GetNormal(), G4TwistTubsSide::GetNormal(), G4TwistTubsHypeSide::GetNormal(), G4Polyhedra::GetPointOnPlane(), G4PolarizationHelper::GetRandomFrame(), G4RTRun::GetSurfaceColour(), G4TheRayTracer::GetSurfaceColour(), G4ErrorCylSurfaceTarget::GetTangentPlane(), G4TriangularFacet::Intersect(), G4QuadrangularFacet::Intersect(), G4PolyconeSide::Intersect(), G4PolyhedraSide::Intersect(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITNavigator2::LocateGlobalPointAndSetup(), G4Trap::MakePlane(), G4Trap::MakePlanes(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::TransmissionChannel::particleLeaves(), G4PolyconeSide::PointOnCone(), G4GeomTools::PolygonAreaNormal(), OpNovicePrimaryGeneratorAction::SetOptPhotonPolar(), PrimaryGeneratorAction::SetOptPhotonPolar(), WLSPrimaryGeneratorAction::SetOptPhotonPolar(), G4TriangularFacet::SetSurfaceNormal(), G4VCSGfaceted::SurfaceNormal(), G4ScaledSolid::SurfaceNormal(), G4ReflectedSolid::SurfaceNormal(), G4DisplacedSolid::SurfaceNormal(), G4IntersectionSolid::SurfaceNormal(), G4SubtractionSolid::SurfaceNormal(), and G4MultiUnion::SurfaceNormal().
operator*()
HepLorentzRotation CLHEP::operator* (const HepRotation & r, const HepLorentzRotation & lt)
Definition at line 263 of file LorentzRotation.cc.
operator/() [1/3]
Hep2Vector CLHEP::operator/ (const Hep2Vector & p, double a)
Definition at line 61 of file TwoVector.cc.
operator/() [2/3]
Hep3Vector CLHEP::operator/ (const Hep3Vector & v1, double c)
Definition at line 300 of file ThreeVector.cc.
operator/() [3/3]
HepLorentzVector CLHEP::operator/ (const HepLorentzVector & w, double c)
Definition at line 164 of file LorentzVector.cc.
operator<<() [1/7]
std::ostream& CLHEP::operator<< (std::ostream & os, const Hep2Vector & q)
Definition at line 69 of file TwoVector.cc.
operator<<() [2/7]
std::ostream& CLHEP::operator<< (std::ostream & os, const Hep3Vector & v)
Definition at line 65 of file ThreeVector.cc.
operator<<() [3/7]
std::ostream& CLHEP::operator<< (std::ostream & os, const HepAxisAngle & aa)
Definition at line 85 of file AxisAngle.cc.
operator<<() [4/7]
std::ostream& CLHEP::operator<< (std::ostream & os, const HepEulerAngles & ea)
Definition at line 100 of file EulerAngles.cc.
operator<<() [5/7]
std::ostream& CLHEP::operator<< (std::ostream & os, const HepLorentzVector & v1)
Definition at line 89 of file LorentzVector.cc.
operator<<() [6/7]
std::ostream& CLHEP::operator<< (std::ostream & os, const HepRandom & dist)
Definition at line 215 of file Random.cc.
operator<<() [7/7]
std::ostream& CLHEP::operator<< (std::ostream & os, const HepRandomEngine & e)
Definition at line 97 of file RandomEngine.cc.
operator>>() [1/7]
std::istream& CLHEP::operator>> (std::istream & is, Hep2Vector & p)
Definition at line 77 of file TwoVector.cc.
operator>>() [2/7]
std::istream& CLHEP::operator>> (std::istream & is, Hep3Vector & v)
Definition at line 72 of file ThreeVector.cc.
operator>>() [3/7]
std::istream& CLHEP::operator>> (std::istream & is, HepAxisAngle & aa)
Definition at line 95 of file AxisAngle.cc.
operator>>() [4/7]
std::istream& CLHEP::operator>> (std::istream & is, HepEulerAngles & ea)
Definition at line 109 of file EulerAngles.cc.
operator>>() [5/7]
std::istream& CLHEP::operator>> (std::istream & is, HepLorentzVector & v1)
Definition at line 95 of file LorentzVector.cc.
operator>>() [6/7]
std::istream& CLHEP::operator>> (std::istream & is, HepRandom & dist)
Definition at line 219 of file Random.cc.
operator>>() [7/7]
std::istream& CLHEP::operator>> (std::istream & is, HepRandomEngine & e)
Definition at line 101 of file RandomEngine.cc.
rotationOf() [1/8]
Hep3Vector CLHEP::rotationOf (const Hep3Vector & vec, const Hep3Vector & axis, double ddelta)
Definition at line 132 of file SpaceVectorR.cc.
rotationOf() [2/8]
Hep3Vector CLHEP::rotationOf (const Hep3Vector & vec, const HepAxisAngle & ax)
Definition at line 127 of file SpaceVectorR.cc.
rotationOf() [3/8]
Hep3Vector CLHEP::rotationOf (const Hep3Vector & vec, const HepEulerAngles & ex)
Definition at line 138 of file SpaceVectorR.cc.
rotationOf() [4/8]
Hep3Vector CLHEP::rotationOf (const Hep3Vector & vec, double phi, double theta, double psi)
Definition at line 143 of file SpaceVectorR.cc.
rotationOf() [5/8]
HepLorentzVector CLHEP::rotationOf (const HepLorentzVector & vec, const Hep3Vector & aaxis, double ddelta)
Definition at line 47 of file LorentzVectorR.cc.
rotationOf() [6/8]
HepLorentzVector CLHEP::rotationOf (const HepLorentzVector & vec, const HepAxisAngle & ax)
Definition at line 55 of file LorentzVectorR.cc.
rotationOf() [7/8]
HepLorentzVector CLHEP::rotationOf (const HepLorentzVector & vec, const HepEulerAngles & e1)
Definition at line 61 of file LorentzVectorR.cc.
rotationOf() [8/8]
HepLorentzVector CLHEP::rotationOf (const HepLorentzVector & vec, double phi1, double theta1, double psi1)
Definition at line 66 of file LorentzVectorR.cc.
rotationXOf() [1/2]
Hep3Vector CLHEP::rotationXOf (const Hep3Vector & vec, double ddelta)
Definition at line 149 of file SpaceVectorR.cc.
rotationXOf() [2/2]
HepLorentzVector CLHEP::rotationXOf (const HepLorentzVector & vec, double phi)
Definition at line 27 of file LorentzVectorB.cc.
rotationYOf() [1/2]
Hep3Vector CLHEP::rotationYOf (const Hep3Vector & vec, double ddelta)
Definition at line 154 of file SpaceVectorR.cc.
rotationYOf() [2/2]
HepLorentzVector CLHEP::rotationYOf (const HepLorentzVector & vec, double phi)
Definition at line 33 of file LorentzVectorB.cc.
rotationZOf() [1/2]
Hep3Vector CLHEP::rotationZOf (const Hep3Vector & vec, double ddelta)
Definition at line 159 of file SpaceVectorR.cc.
rotationZOf() [2/2]
HepLorentzVector CLHEP::rotationZOf (const HepLorentzVector & vec, double phi)
Definition at line 39 of file LorentzVectorB.cc.
safe_acos() [1/5]
static double CLHEP::safe_acos (double x) inline static
Definition at line 22 of file Rotation.cc.
safe_acos() [2/5]
static double CLHEP::safe_acos (double x) inline static
Definition at line 26 of file RotationX.cc.
safe_acos() [3/5]
static double CLHEP::safe_acos (double x) inline static
Definition at line 26 of file RotationZ.cc.
safe_acos() [4/5]
static double CLHEP::safe_acos (double x) inline static
Definition at line 26 of file RotationY.cc.
safe_acos() [5/5]
static double CLHEP::safe_acos (double x) inline static
Definition at line 26 of file RotationE.cc.
StirlingCorrection()
static double CLHEP::StirlingCorrection (long int k) static
Definition at line 91 of file RandBinomial.cc.
transformSmall()
double CLHEP::RandGaussQ::transformSmall (double r)
Definition at line 218 of file flatToGaussian.cc.
ZMinput2doubles()
void CLHEP::ZMinput2doubles (std::istream & is, const char * type, double & x, double & y)
Definition at line 243 of file ZMinput.cc.
Referenced by operator>>().
ZMinput3doubles()
void CLHEP::ZMinput3doubles (std::istream & is, const char * type, double & x, double & y, double & z)
Definition at line 42 of file ZMinput.cc.
Referenced by operator>>(), and ZMinputAxisAngle().
ZMinputAxisAngle()
void CLHEP::ZMinputAxisAngle (std::istream & is, double & x, double & y, double & z, double & delta)
Definition at line 156 of file ZMinput.cc.
Referenced by operator>>().
ZMpvAxisAngleRep()
static void CLHEP::ZMpvAxisAngleRep (const HepAxisAngle & aa, double array[]) static
Definition at line 20 of file AxisAngle.cc.
ZMpvEulerAnglesRep()
static void CLHEP::ZMpvEulerAnglesRep (const HepEulerAngles & ex, double array[]) static
Definition at line 43 of file EulerAngles.cc.
Variable Documentation
gaussTables [1/2]
const double CLHEP::gaussTables[2 *TableSize] static
Initial value:
= {
}
Definition at line 84 of file flatToGaussian.cc.
gaussTables [2/2]
const float CLHEP::gaussTables[TableSize] static
Initial value:
= {
}
Definition at line 87 of file RandGaussQ.cc.
inverseLandau
const float CLHEP::inverseLandau[TABLE_END+1] static
Definition at line 73 of file RandLandau.cc.
MarkerLen [1/8]
const int CLHEP::MarkerLen = 64 static
Definition at line 50 of file MixMaxRng.cc.
MarkerLen [2/8]
const int CLHEP::MarkerLen = 64 static
Definition at line 55 of file RanecuEngine.cc.
MarkerLen [3/8]
const int CLHEP::MarkerLen = 64 static
Definition at line 57 of file RanluxEngine.cc.
MarkerLen [4/8]
const int CLHEP::MarkerLen = 64 static
Definition at line 58 of file RanshiEngine.cc.
MarkerLen [5/8]
const int CLHEP::MarkerLen = 64 static
Definition at line 58 of file JamesRandom.cc.
MarkerLen [6/8]
const int CLHEP::MarkerLen = 64 static
Definition at line 59 of file MTwistEngine.cc.
MarkerLen [7/8]
const int CLHEP::MarkerLen = 64 static
Definition at line 66 of file DualRand.cc.
MarkerLen [8/8]
const int CLHEP::MarkerLen = 64 static
Definition at line 75 of file Ranlux64Engine.cc.
poissonTables
const double CLHEP::poissonTables[51 *((95-10)/5+1)] static
Initial value:
= {
}
Definition at line 71 of file RandPoissonQ.cc.
prec
const double CLHEP::prec = 4.6566128E-10 static
Definition at line 57 of file RanecuEngine.cc.
Referenced by G4MagInt_Driver::AccurateAdvance(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), RunAction::BeginOfRunAction(), G4SandiaTable::ComputeMatSandiaMatrix(), G4FermiFragmentsPoolVI::Dump(), G4FermiFragmentsPoolVI::DumpFragment(), Run::EndOfRun(), HistoManager::EndOfRun(), LXeRun::EndOfRun(), G4PhotonEvaporation::GenerateGamma(), G4ElasticHadrNucleusHE::GetLightFq2(), G4SynchrotronRadiation::GetRandomEnergySR(), G4LevelReader::LevelManager(), G4LevelReader::NormalizedICCProbability(), operator<<(), Run::PrintFluence(), DetectorConstruction::PrintGeometry(), CexmcRunAction::PrintResults(), G4PropagatorInField::ReportLoopingParticle(), Run::Run(), F04SteppingVerbose::StepInfo(), WLSSteppingVerbose::StepInfo(), ExN04SteppingVerbose::StepInfo(), SteppingVerbose::StepInfo(), OpNoviceSteppingVerbose::StepInfo(), eRositaSteppingVerbose::StepInfo(), FCALSteppingVerbose::StepInfo(), XrayFluoSteppingVerbose::StepInfo(), PurgMagSteppingVerbose::StepInfo(), ExN02SteppingVerbose::StepInfo(), RE05SteppingVerbose::StepInfo(), ExP01SteppingVerbose::StepInfo(), F05SteppingVerbose::StepInfo(), G4SteppingVerbose::StepInfo(), G4ITSteppingVerbose::StepInfo(), F01SteppingVerbose::StepInfo(), F02SteppingVerbose::StepInfo(), F03SteppingVerbose::StepInfo(), G4ITSteppingVerbose::StepInfoForLeadingTrack(), G4Physics2DVector::Store(), G4DeexPrecoParameters::StreamInfo(), G4EmParameters::StreamInfo(), G4NucLevel::StreamInfo(), G4LevelManager::StreamInfo(), G4RadioactiveDecay::StreamInfo(), Run::SurveyConvergence(), F04SteppingVerbose::TrackingStarted(), WLSSteppingVerbose::TrackingStarted(), ExN04SteppingVerbose::TrackingStarted(), SteppingVerbose::TrackingStarted(), FCALSteppingVerbose::TrackingStarted(), eRositaSteppingVerbose::TrackingStarted(), OpNoviceSteppingVerbose::TrackingStarted(), XrayFluoSteppingVerbose::TrackingStarted(), PurgMagSteppingVerbose::TrackingStarted(), RE05SteppingVerbose::TrackingStarted(), ExN02SteppingVerbose::TrackingStarted(), ExP01SteppingVerbose::TrackingStarted(), F05SteppingVerbose::TrackingStarted(), G4SteppingVerbose::TrackingStarted(), G4ITSteppingVerbose::TrackingStarted(), F02SteppingVerbose::TrackingStarted(), F01SteppingVerbose::TrackingStarted(), F03SteppingVerbose::TrackingStarted(), G4SteppingVerbose::VerboseTrack(), G4ITSteppingVerbose::VerboseTrack(), and EventAction::WriteFibers().
TABLE_END
const int CLHEP::TABLE_END = 982 static
Definition at line 60 of file RandLandau.cc.
TABLE_INTERVAL
const float CLHEP::TABLE_INTERVAL = .001f static
Definition at line 59 of file RandLandau.cc.
TABLE_MULTIPLIER
const float CLHEP::TABLE_MULTIPLIER = 1.0f/TABLE_INTERVAL static
Definition at line 61 of file RandLandau.cc.
Toffsets
const int CLHEP::Toffsets[5] static
Initial value:
= { Table0offset,
                                 Table1offset,
                                 Table2offset,
                                 Table3offset,
                                 Table4offset }
Definition at line 76 of file flatToGaussian.cc.
Tsizes
const int CLHEP::Tsizes[5] static
Initial value:
=   { Table0size,
                                 Table1size,
                                 Table2size,
                                 Table3size,
                                 Table4size }
Definition at line 52 of file flatToGaussian.cc.
Tsteps
const double CLHEP::Tsteps[5] static
Initial value:
= { Table0step,
                                 Table1step,
                                 Table2step,
                                 Table3step,
                                 Table4step }
Definition at line 64 of file flatToGaussian.cc.