Geant4: source/digits_hits/digits/include/G4DCofThisEvent.hh File Reference
G4DCofThisEvent.hh File Reference
#include "globals.hh"
#include "G4Allocator.hh"
#include "G4VDigiCollection.hh"
#include <vector>
Data Structures
class G4DCofThisEvent
Functions
G4DLLIMPORT G4Allocator< G4DCofThisEvent > *& anDCoTHAllocator_G4MT_TLS_ ()
Function Documentation
anDCoTHAllocator_G4MT_TLS_()
G4DLLIMPORT G4Allocator<G4DCofThisEvent>*& anDCoTHAllocator_G4MT_TLS_ ()
Definition at line 32 of file G4DCofThisEvent.cc.
Referenced by G4DCofThisEvent::AddDigiCollection(), G4DCofThisEvent::G4DCofThisEvent(), G4DCofThisEvent::operator delete(), G4DCofThisEvent::operator new(), G4DCofThisEvent::operator=(), and G4DCofThisEvent::~G4DCofThisEvent().