Geant4: G4tgbDetectorBuilder Class Reference
G4tgbDetectorBuilder Class Reference
#include <G4tgbDetectorBuilder.hh>
Public Member Functions
G4tgbDetectorBuilder ()
virtual ~G4tgbDetectorBuilder ()
virtual const G4tgrVolume * ReadDetector ()
virtual G4VPhysicalVolume * ConstructDetector (const G4tgrVolume *tgrVoltop)
Detailed Description
Definition at line 56 of file G4tgbDetectorBuilder.hh.
Constructor & Destructor Documentation
G4tgbDetectorBuilder()
G4tgbDetectorBuilder::G4tgbDetectorBuilder ()
Definition at line 52 of file G4tgbDetectorBuilder.cc.
~G4tgbDetectorBuilder()
G4tgbDetectorBuilder::~G4tgbDetectorBuilder () virtual
Definition at line 57 of file G4tgbDetectorBuilder.cc.
Member Function Documentation
ConstructDetector()
G4VPhysicalVolume * G4tgbDetectorBuilder::ConstructDetector (const G4tgrVolume * tgrVoltop) virtual
Reimplemented in ExTGRCDetectorBuilder.
Definition at line 75 of file G4tgbDetectorBuilder.cc.
Referenced by ExTGRCDetectorBuilder::ConstructDetector(), and G4tgbVolumeMgr::ReadAndConstructDetector().
ReadDetector()
const G4tgrVolume * G4tgbDetectorBuilder::ReadDetector () virtual
Reimplemented in ExTGRCDetectorBuilder.
Definition at line 62 of file G4tgbDetectorBuilder.cc.
Referenced by G4tgbVolumeMgr::ReadAndConstructDetector().
The documentation for this class was generated from the following files:
source/persistency/ascii/include/G4tgbDetectorBuilder.hh
source/persistency/ascii/src/G4tgbDetectorBuilder.cc