Geant4: source/error_propagation/include/G4ErrorSymMatrix.hh File Reference
G4ErrorSymMatrix.hh File Reference
#include <vector>
#include "globals.hh"
#include "G4ErrorSymMatrix.icc"
Data Structures
class G4ErrorSymMatrix
class G4ErrorSymMatrix::G4ErrorSymMatrix_row
class G4ErrorSymMatrix::G4ErrorSymMatrix_row_const
Functions
std::ostream & operator<< (std::ostream &s, const G4ErrorSymMatrix &q)
G4ErrorMatrix operator* (const G4ErrorMatrix &m1, const G4ErrorSymMatrix &m2)
G4ErrorMatrix operator* (const G4ErrorSymMatrix &m1, const G4ErrorMatrix &m2)
G4ErrorMatrix operator* (const G4ErrorSymMatrix &m1, const G4ErrorSymMatrix &m2)
G4ErrorSymMatrix operator* (G4double t, const G4ErrorSymMatrix &s1)
G4ErrorSymMatrix operator* (const G4ErrorSymMatrix &s1, G4double t)
G4ErrorSymMatrix operator/ (const G4ErrorSymMatrix &m1, G4double t)
G4ErrorMatrix operator+ (const G4ErrorMatrix &m1, const G4ErrorSymMatrix &s2)
G4ErrorMatrix operator+ (const G4ErrorSymMatrix &s1, const G4ErrorMatrix &m2)
G4ErrorSymMatrix operator+ (const G4ErrorSymMatrix &s1, const G4ErrorSymMatrix &s2)
G4ErrorMatrix operator- (const G4ErrorMatrix &m1, const G4ErrorSymMatrix &s2)
G4ErrorMatrix operator- (const G4ErrorSymMatrix &m1, const G4ErrorMatrix &m2)
G4ErrorSymMatrix operator- (const G4ErrorSymMatrix &s1, const G4ErrorSymMatrix &s2)
G4ErrorSymMatrix dsum (const G4ErrorSymMatrix &s1, const G4ErrorSymMatrix &s2)
G4double condition (const G4ErrorSymMatrix &m)
void diag_step (G4ErrorSymMatrix *t, G4int begin, G4int end)
void diag_step (G4ErrorSymMatrix *t, G4ErrorMatrix *u, G4int begin, G4int end)
G4ErrorMatrix diagonalize (G4ErrorSymMatrix *s)
void house_with_update2 (G4ErrorSymMatrix *a, G4ErrorMatrix *v, G4int row=1, G4int col=1)
void tridiagonal (G4ErrorSymMatrix *a, G4ErrorMatrix *hsm)
G4ErrorMatrix tridiagonal (G4ErrorSymMatrix *a)
Function Documentation
condition()
G4double condition (const G4ErrorSymMatrix & m)
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_Sampling(), G4AntiNeutronAnnihilationAtRest::AtRestGetPhysicalInteractionLength(), G4VRestContinuousProcess::AtRestGetPhysicalInteractionLength(), G4VRestProcess::AtRestGetPhysicalInteractionLength(), G4VITRestProcess::AtRestGetPhysicalInteractionLength(), G4HadronStoppingProcess::AtRestGetPhysicalInteractionLength(), G4MuonMinusAtomicCapture::AtRestGetPhysicalInteractionLength(), G4VRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4eplusAnnihilation::AtRestGetPhysicalInteractionLength(), G4VITRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4MuonicAtomDecay::AtRestGetPhysicalInteractionLength(), G4DNAMolecularDissociation::AtRestGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4ScoreSplittingProcess::AtRestGetPhysicalInteractionLength(), G4AdjointProcessEquivalentToDirectProcess::AtRestGetPhysicalInteractionLength(), G4ParallelWorldScoringProcess::AtRestGetPhysicalInteractionLength(), G4ParallelWorldProcess::AtRestGetPhysicalInteractionLength(), G4WrapperProcess::AtRestGetPhysicalInteractionLength(), G4Decay::AtRestGetPhysicalInteractionLength(), G4FastSimulationManagerProcess::AtRestGetPhysicalInteractionLength(), G4BiasingProcessInterface::AtRestGetPhysicalInteractionLength(), G4RadioactiveDecayBase::AtRestGetPhysicalInteractionLength(), G4RadioactiveDecay::AtRestGetPhysicalInteractionLength(), G4VProcess::AtRestGPIL(), G4eBremsstrahlungRelModel::ComputeLPMfunctions(), G4PairProductionRelModel::ComputeLPMfunctions(), G4MuonicAtomDecay::DecayIt(), G4BOptnCloning::DistanceToApplyOperation(), GB03BOptnSplitOrKillOnBoundary::DistanceToApplyOperation(), GB05BOptnSplitAndKillByCrossSection::DistanceToApplyOperation(), GB06BOptnSplitAndKillByImportance::DistanceToApplyOperation(), G4LowEnergyRayleigh::DumpMeanFreePath(), G4LowEnergyCompton::DumpMeanFreePath(), G4LowEnergyGammaConversion::DumpMeanFreePath(), G4LowEnergyPolarizedCompton::DumpMeanFreePath(), G4LowEnergyPhotoElectric::DumpMeanFreePath(), G4PhononScattering::GetMeanFreePath(), G4PhononReflection::GetMeanFreePath(), G4PhononDownconversion::GetMeanFreePath(), G4Channeling::GetMeanFreePath(), G4VTransitionRadiation::GetMeanFreePath(), G4TransitionRadiation::GetMeanFreePath(), G4SynchrotronRadiation::GetMeanFreePath(), G4eplusPolarizedAnnihilation::GetMeanFreePath(), G4ForwardXrayTR::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetMeanFreePath(), G4hImpactIonisation::GetMeanFreePath(), G4VAdjointReverseReaction::GetMeanFreePath(), G4VXTRenergyLoss::GetMeanFreePath(), G4PolarizedCompton::GetMeanFreePath(), G4UCNBoundaryProcess::GetMeanFreePath(), G4Scintillation::GetMeanFreePath(), G4GammaGeneralProcess::GetMeanFreePath(), G4OpBoundaryProcess::GetMeanFreePath(), G4VEnergyLossProcess::GetMeanFreePath(), G4VMultipleScattering::GetMeanFreePath(), G4VEmProcess::GetMeanFreePath(), G4Scintillation::GetMeanLifeTime(), G4BiasingProcessInterface::InvokeWrappedProcessPostStepGPIL(), HadrontherapyStepMax::PostStepGetPhysicalInteractionLength(), G4StepLimiter::PostStepGetPhysicalInteractionLength(), DMXMinEkineCuts::PostStepGetPhysicalInteractionLength(), G4VITDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4MinEkineCuts::PostStepGetPhysicalInteractionLength(), G4UserSpecialCuts::PostStepGetPhysicalInteractionLength(), XrayFluoStepMax::PostStepGetPhysicalInteractionLength(), F04StepMax::PostStepGetPhysicalInteractionLength(), StepMax::PostStepGetPhysicalInteractionLength(), StepLimiter::PostStepGetPhysicalInteractionLength(), StepMaxProcess::PostStepGetPhysicalInteractionLength(), WLSStepMax::PostStepGetPhysicalInteractionLength(), DMXMaxTimeCuts::PostStepGetPhysicalInteractionLength(), G4MaxTimeCuts::PostStepGetPhysicalInteractionLength(), CexmcStudiedProcess::PostStepGetPhysicalInteractionLength(), IORTStepMax::PostStepGetPhysicalInteractionLength(), G4ErrorMagFieldLimitProcess::PostStepGetPhysicalInteractionLength(), G4ErrorStepLengthLimitProcess::PostStepGetPhysicalInteractionLength(), ML2StepMax::PostStepGetPhysicalInteractionLength(), G4VRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), XrayTelStepCut::PostStepGetPhysicalInteractionLength(), G4VDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4ErrorTrackLengthTarget::PostStepGetPhysicalInteractionLength(), G4VITRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4ElectronCapture::PostStepGetPhysicalInteractionLength(), G4eplusPolarizedAnnihilation::PostStepGetPhysicalInteractionLength(), G4LowECapture::PostStepGetPhysicalInteractionLength(), G4MuonicAtomDecay::PostStepGetPhysicalInteractionLength(), G4HadronStoppingProcess::PostStepGetPhysicalInteractionLength(), G4NeutronKiller::PostStepGetPhysicalInteractionLength(), G4AdjointForcedInteractionForGamma::PostStepGetPhysicalInteractionLength(), G4WeightCutOffProcess::PostStepGetPhysicalInteractionLength(), G4ImportanceProcess::PostStepGetPhysicalInteractionLength(), G4UnknownDecay::PostStepGetPhysicalInteractionLength(), G4WeightWindowProcess::PostStepGetPhysicalInteractionLength(), G4PolarizedCompton::PostStepGetPhysicalInteractionLength(), G4AdjointProcessEquivalentToDirectProcess::PostStepGetPhysicalInteractionLength(), G4GammaGeneralProcess::PostStepGetPhysicalInteractionLength(), G4WrapperProcess::PostStepGetPhysicalInteractionLength(), G4ParallelWorldProcess::PostStepGetPhysicalInteractionLength(), G4FastSimulationManagerProcess::PostStepGetPhysicalInteractionLength(), G4Cerenkov::PostStepGetPhysicalInteractionLength(), G4VEmProcess::PostStepGetPhysicalInteractionLength(), G4ScoreSplittingProcess::PostStepGetPhysicalInteractionLength(), G4Decay::PostStepGetPhysicalInteractionLength(), G4ParallelWorldScoringProcess::PostStepGetPhysicalInteractionLength(), G4ParallelGeometriesLimiterProcess::PostStepGetPhysicalInteractionLength(), G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength(), G4VMultipleScattering::PostStepGetPhysicalInteractionLength(), G4BiasingProcessInterface::PostStepGetPhysicalInteractionLength(), and G4VProcess::PostStepGPIL().
diag_step() [1/2]
void diag_step (G4ErrorSymMatrix * t, G4ErrorMatrix * u, G4int begin, G4int end)
diag_step() [2/2]
void diag_step (G4ErrorSymMatrix * t, G4int begin, G4int end)
diagonalize()
G4ErrorMatrix diagonalize (G4ErrorSymMatrix * s)
dsum()
G4ErrorSymMatrix dsum (const G4ErrorSymMatrix & s1, const G4ErrorSymMatrix & s2)
Definition at line 182 of file G4ErrorSymMatrix.cc.
house_with_update2()
void house_with_update2 (G4ErrorSymMatrix * a, G4ErrorMatrix * v, G4int row = 1, G4int col = 1)
operator*() [1/5]
G4ErrorMatrix operator* (const G4ErrorMatrix & m1, const G4ErrorSymMatrix & m2)
Definition at line 286 of file G4ErrorSymMatrix.cc.
operator*() [2/5]
G4ErrorMatrix operator* (const G4ErrorSymMatrix & m1, const G4ErrorMatrix & m2)
Definition at line 320 of file G4ErrorSymMatrix.cc.
operator*() [3/5]
G4ErrorMatrix operator* (const G4ErrorSymMatrix & m1, const G4ErrorSymMatrix & m2)
Definition at line 353 of file G4ErrorSymMatrix.cc.
operator*() [4/5]
G4ErrorSymMatrix operator* (const G4ErrorSymMatrix & s1, G4double t)
Definition at line 272 of file G4ErrorSymMatrix.cc.
operator*() [5/5]
G4ErrorSymMatrix operator* (G4double t, const G4ErrorSymMatrix & s1)
Definition at line 279 of file G4ErrorSymMatrix.cc.
operator+() [1/3]
G4ErrorMatrix operator+ (const G4ErrorMatrix & m1, const G4ErrorSymMatrix & s2)
Definition at line 206 of file G4ErrorSymMatrix.cc.
operator+() [2/3]
G4ErrorMatrix operator+ (const G4ErrorSymMatrix & s1, const G4ErrorMatrix & m2)
Definition at line 214 of file G4ErrorSymMatrix.cc.
operator+() [3/3]
G4ErrorSymMatrix operator+ (const G4ErrorSymMatrix & s1, const G4ErrorSymMatrix & s2)
Definition at line 222 of file G4ErrorSymMatrix.cc.
operator-() [1/3]
G4ErrorMatrix operator- (const G4ErrorMatrix & m1, const G4ErrorSymMatrix & s2)
Definition at line 235 of file G4ErrorSymMatrix.cc.
operator-() [2/3]
G4ErrorMatrix operator- (const G4ErrorSymMatrix & m1, const G4ErrorMatrix & m2)
Definition at line 243 of file G4ErrorSymMatrix.cc.
operator-() [3/3]
G4ErrorSymMatrix operator- (const G4ErrorSymMatrix & s1, const G4ErrorSymMatrix & s2)
Definition at line 251 of file G4ErrorSymMatrix.cc.
operator/()
G4ErrorSymMatrix operator/ (const G4ErrorSymMatrix & m1, G4double t)
Definition at line 265 of file G4ErrorSymMatrix.cc.
operator<<()
std::ostream& operator<< (std::ostream & s, const G4ErrorSymMatrix & q)
Definition at line 523 of file G4ErrorSymMatrix.cc.
tridiagonal() [1/2]
G4ErrorMatrix tridiagonal (G4ErrorSymMatrix * a)
tridiagonal() [2/2]
void tridiagonal (G4ErrorSymMatrix * a, G4ErrorMatrix * hsm)