Geant4: G4MemStat Namespace Reference
G4MemStat Namespace Reference
Data Structures
struct MemStat
Functions
std::ostream & operator<< (std::ostream &os, const MemStat &p)
MemStat MemoryUsage ()
Function Documentation
MemoryUsage()
MemStat G4MemStat::MemoryUsage ()
Definition at line 55 of file G4MemStat.cc.
Referenced by G4ITTransportation::AlongStepDoIt(), G4DNABrownianTransportation::AlongStepDoIt(), G4ITModelProcessor::CalculateMinTimeStep(), G4DNABrownianTransportation::Diffusion(), G4ITStepProcessor::DoIt(), G4Scheduler::DoProcess(), G4ITStepProcessor::DoStepping(), G4ITModelProcessor::InitializeStepper(), G4ITStepProcessor::InvokeAlongStepDoItProcs(), G4DNAMoleculeEncounterStepper::Prepare(), G4Scheduler::Stepping(), and G4ITStepProcessor::Stepping().
operator<<()
std::ostream & G4MemStat::operator<< (std::ostream & os, const MemStat & p)
Definition at line 94 of file G4MemStat.cc.