Geant4: source/global/management/include/G4Log.hh File Reference
G4Log.hh File Reference
#include <limits>
#include <stdint.h>
#include "G4Types.hh"
Data Structures
union G4LogConsts::ieee754
Namespaces
G4LogConsts
Functions
G4double G4LogConsts::get_log_px (const G4double x)
G4double G4LogConsts::get_log_qx (const G4double x)
uint64_t G4LogConsts::dp2uint64 (G4double x)
G4double G4LogConsts::uint642dp (uint64_t ll)
G4float G4LogConsts::uint322sp (G4int x)
uint32_t G4LogConsts::sp2uint32 (G4float x)
G4double G4LogConsts::getMantExponent (const G4double x, G4double &fe)
Like frexp but vectorising and the exponent is a double.
G4float G4LogConsts::getMantExponentf (const G4float x, G4float &fe)
Like frexp but vectorising and the exponent is a float.
G4double G4Log (G4double x)
G4float G4LogConsts::get_log_poly (const G4float x)
G4float G4Logf (G4float x)
void logv (const uint32_t size, G4double const *__restrict__ iarray, G4double *__restrict__ oarray)
void G4Logv (const uint32_t size, G4double const *__restrict__ iarray, G4double *__restrict__ oarray)
void logfv (const uint32_t size, G4float const *__restrict__ iarray, G4float *__restrict__ oarray)
void G4Logfv (const uint32_t size, G4float const *__restrict__ iarray, G4float *__restrict__ oarray)
Variables
const G4double G4LogConsts::LOG_UPPER_LIMIT = 1e307
const G4double G4LogConsts::LOG_LOWER_LIMIT = 0
const G4double G4LogConsts::SQRTH = 0.70710678118654752440
const G4float G4LogConsts::MAXNUMF = 3.4028234663852885981170418348451692544e38f
const G4float G4LogConsts::LOGF_UPPER_LIMIT = MAXNUMF
const G4float G4LogConsts::LOGF_LOWER_LIMIT = 0
const G4float G4LogConsts::PX1logf = 7.0376836292E-2f
const G4float G4LogConsts::PX2logf = -1.1514610310E-1f
const G4float G4LogConsts::PX3logf = 1.1676998740E-1f
const G4float G4LogConsts::PX4logf = -1.2420140846E-1f
const G4float G4LogConsts::PX5logf = 1.4249322787E-1f
const G4float G4LogConsts::PX6logf = -1.6668057665E-1f
const G4float G4LogConsts::PX7logf = 2.0000714765E-1f
const G4float G4LogConsts::PX8logf = -2.4999993993E-1f
const G4float G4LogConsts::PX9logf = 3.3333331174E-1f
const G4float G4LogConsts::SQRTHF = 0.707106781186547524f
Function Documentation
G4Log()
G4double G4Log (G4double x) inline
Definition at line 229 of file G4Log.hh.
Referenced by G4Pow::A13High(), G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4FTFModel::AdjustNucleonsAlgorithm_Sampling(), G4PreCompoundEmission::AngularDistribution(), G4Nucleus::AnnihilationEvaporationEffects(), G4AntiNeutronAnnihilationAtRest::AntiNeutronAnnihilation(), G4ParticleHPFissionFS::ApplyYourself(), G4LFission::ApplyYourself(), G4MuonMinusBoundDecay::ApplyYourself(), G4EnergyLossForExtrapolator::AverageScatteringAngle(), G4EmCorrections::BarkasCorrection(), G4EmCorrections::Bethe(), G4AtimaEnergyLossModel::Bethek_dedx_e(), G4SampleResonance::BrWigInt1(), G4VAnnihilationCollision::BrWigInt1(), G4VScatteringCollision::BrWigInt1(), G4VEnergyLossProcess::BuildLambdaTable(), G4VEmProcess::BuildLambdaTable(), G4SBBremTable::BuildSamplingTables(), G4QuasiElRatios::CalcElTot(), G4StatMFMacroTetraNucleon::CalcEntropy(), G4StatMFMacroTriNucleon::CalcEntropy(), G4StatMFMacroNucleon::CalcEntropy(), G4StatMFMacroBiNucleon::CalcEntropy(), G4StatMFMacroMultiNucleon::CalcEntropy(), G4StatMFMicroPartition::CalcPartitionProbability(), G4GEMProbability::CalcProbability(), G4HadronCrossSections::CalcScatteringCrossSections(), G4ChipsAntiBaryonInelasticXS::CalculateCrossSection(), G4ChipsProtonInelasticXS::CalculateCrossSection(), G4ChipsHyperonInelasticXS::CalculateCrossSection(), G4ChipsPionMinusInelasticXS::CalculateCrossSection(), G4ChipsHyperonElasticXS::CalculateCrossSection(), G4ChipsPionPlusElasticXS::CalculateCrossSection(), G4ChipsNeutronInelasticXS::CalculateCrossSection(), G4ChipsPionMinusElasticXS::CalculateCrossSection(), G4ChipsPionPlusInelasticXS::CalculateCrossSection(), G4ChipsAntiBaryonElasticXS::CalculateCrossSection(), G4MuonVDNuclearModel::CalculateEMVertex(), G4MaterialPropertiesTable::CalculateGROUPVEL(), G4PreCompoundTransitions::CalculateProbability(), G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD(), G4QGSParticipants::CheckKinematics(), G4FTFModel::CheckKinematics(), G4QuasiElRatios::ChExElCoef(), G4Reggeons::Chi_pomeron(), G4Reggeons::Chi_reggeon(), G4Nucleus::Cinema(), G4PolarizedComptonModel::ComputeAsymmetryPerAtom(), G4eeToHadronsModel::ComputeCMCrossSectionPerElectron(), G4KleinNishinaCompton::ComputeCrossSectionPerAtom(), G4KleinNishinaModel::ComputeCrossSectionPerAtom(), G4BetheHeitlerModel::ComputeCrossSectionPerAtom(), G4UrbanMscModel::ComputeCrossSectionPerAtom(), G4UrbanAdjointMscModel::ComputeCrossSectionPerAtom(), G4GammaConversionToMuons::ComputeCrossSectionPerAtom(), G4eplusTo3GammaOKVIModel::ComputeCrossSectionPerElectron(), G4eplusTo2GammaOKVIModel::ComputeCrossSectionPerElectron(), G4eeToTwoGammaModel::ComputeCrossSectionPerElectron(), G4AtimaEnergyLossModel::ComputeCrossSectionPerElectron(), G4MollerBhabhaModel::ComputeCrossSectionPerElectron(), G4LindhardSorensenIonModel::ComputeCrossSectionPerElectron(), G4BetheBlochModel::ComputeCrossSectionPerElectron(), G4ICRU73QOModel::ComputeCrossSectionPerElectron(), G4MuBetheBlochModel::ComputeCrossSectionPerElectron(), G4BraggIonModel::ComputeCrossSectionPerElectron(), G4BraggModel::ComputeCrossSectionPerElectron(), G4ComponentGGHadronNucleusXsc::ComputeCrossSections(), G4ComponentGGNuclNuclXsc::ComputeCrossSections(), G4KokoulinMuonNuclearXS::ComputeDDMicroscopicCrossSection(), G4mplIonisationWithDeltaModel::ComputeDEDXAhlen(), G4MollerBhabhaModel::ComputeDEDXPerVolume(), G4LindhardSorensenIonModel::ComputeDEDXPerVolume(), G4BetheBlochModel::ComputeDEDXPerVolume(), G4ICRU73QOModel::ComputeDEDXPerVolume(), G4MuBetheBlochModel::ComputeDEDXPerVolume(), G4BraggIonModel::ComputeDEDXPerVolume(), G4BraggModel::ComputeDEDXPerVolume(), G4IonisParamMat::ComputeDensityEffect(), G4hBremsstrahlungModel::ComputeDMicroscopicCrossSection(), G4hPairProductionModel::ComputeDMicroscopicCrossSection(), G4LDMBremModel::ComputeDMicroscopicCrossSection(), G4MuBremsstrahlungModel::ComputeDMicroscopicCrossSection(), G4MuPairProductionModel::ComputeDMicroscopicCrossSection(), G4LivermoreBremsstrahlungModel::ComputeDXSectionPerAtom(), G4SeltzerBergerModel::ComputeDXSectionPerAtom(), G4eplusTo3GammaOKVIModel::ComputeF(), G4eplusTo3GammaOKVIModel::ComputeF0(), G4IonisParamMat::ComputeFluctModel(), G4UrbanMscModel::ComputeGeomPathLength(), G4UrbanAdjointMscModel::ComputeGeomPathLength(), G4eBremsstrahlungRelModel::ComputeLPMfunctions(), G4PairProductionRelModel::ComputeLPMfunctions(), G4Element::ComputeLradTsaiFactor(), G4IonisParamMat::ComputeMeanParameters(), G4KokoulinMuonNuclearXS::ComputeMicroscopicCrossSection(), G4MuBremsstrahlungModel::ComputeMicroscopicCrossSection(), G4MuPairProductionModel::ComputeMicroscopicCrossSection(), G4Material::ComputeNuclearInterLength(), G4QGSParticipants::ComputeNucleusProperties(), G4FTFModel::ComputeNucleusProperties(), G4eBremParametrizedModel::ComputeParametrizedDXSectionPerAtom(), G4PairProductionRelModel::ComputePhi12(), G4LivermoreComptonModel::ComputeScatteringFunction(), G4LowEPComptonModel::ComputeScatteringFunction(), G4LowEPPolarizedComptonModel::ComputeScatteringFunction(), G4GoudsmitSaundersonTable::ComputeScatteringPowerCorrection(), G4eBremsstrahlungRelModel::ComputeScreeningFunctions(), G4UrbanMscModel::ComputeTheta0(), G4UrbanAdjointMscModel::ComputeTheta0(), G4WentzelOKandVIxSection::ComputeTransportCrossSectionPerAtom(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTrueStepLength(), G4UrbanMscModel::ComputeTrueStepLength(), G4UrbanAdjointMscModel::ComputeTrueStepLength(), G4GoudsmitSaundersonMscModel::ComputeTrueStepLength(), G4eBremParametrizedModel::ComputeXSectionPerAtom(), G4eBremsstrahlungRelModel::ComputeXSectionPerAtom(), G4MuPairProductionModel::ComputMuPairLoss(), UltraDetectorConstruction::ConstructTableMaterials(), G4NuclNuclDiffuseElastic::CoulombAmplitude(), G4BGGNucleonInelasticXS::CoulombFactor(), G4BGGNucleonElasticXS::CoulombFactor(), G4DiffractiveExcitation::CreateStrings(), G4AngularDistribution::Cross(), G4LowEXsection::CrossSection(), G4XpimNTotal::CrossSection(), G4XpipNTotal::CrossSection(), G4XPDGElastic::CrossSection(), G4ChipsProtonInelasticXS::CrossSectionFormula(), G4ChipsHyperonInelasticXS::CrossSectionFormula(), G4ChipsPionMinusInelasticXS::CrossSectionFormula(), G4ChipsNeutronInelasticXS::CrossSectionFormula(), G4ChipsPionPlusInelasticXS::CrossSectionFormula(), G4ChipsAntiBaryonInelasticXS::CrossSectionLin(), G4ChipsProtonInelasticXS::CrossSectionLin(), G4ChipsHyperonInelasticXS::CrossSectionLin(), G4ChipsPionMinusInelasticXS::CrossSectionLin(), G4ChipsNeutronInelasticXS::CrossSectionLin(), G4ChipsPionPlusInelasticXS::CrossSectionLin(), G4GoudsmitSaundersonMscModel::CrossSectionPerVolume(), G4AtimaEnergyLossModel::dedx_n(), G4ElasticHadrNucleusHE::DefineHadronValues(), G4ElasticData::DefineNucleusParameters(), G4IonisParamMat::DensityCorrection(), G4EmCorrections::DensityCorrection(), G4AtimaFluctuations::Dispersion(), G4ProjectileFragmentCrossSection::doit(), G4ParticleHPMadlandNixSpectrum::E1(), G4ionEffectiveCharge::EffectiveCharge(), G4BraggModel::ElectronicStoppingPower(), G4BraggIonModel::ElectronicStoppingPower(), G4BinaryLightIonReaction::EnergyAndMomentumCorrector(), G4AtimaFluctuations::EnergyTable_interpolate(), G4AtimaEnergyLossModel::EnergyTable_interpolate(), G4LegendrePolynomial::EvalAssocLegendrePoly(), G4Nucleus::EvaporationEffects(), G4AntiNeutronAnnihilationAtRest::ExNu(), G4QuasiElRatios::FetchElTot(), G4NucleiModel::fillZoneRadii(), G4VelocityTable::FindBinLocation(), G4JTPolynomialSolver::FindRoots(), G4ScreeningMottCrossSection::FormFactor2UniformHelm(), G4InuclSpecialFunctions::G4cbrt(), G4ElasticHadrNucleusHE::G4ElasticHadrNucleusHE(), G4F20GEMProbability::G4F20GEMProbability(), G4GSMottCorrection::G4GSMottCorrection(), G4GSPWACorrections::G4GSPWACorrections(), G4O17GEMProbability::G4O17GEMProbability(), G4PhysicsLogVector::G4PhysicsLogVector(), G4Pow::G4Pow(), G4FPYSamplingOps::G4SampleWatt(), G4fissionEvent::G4SmpGEng(), G4fissionEvent::G4SmpNEngCf252(), G4fissionEvent::G4SmpNugDist(), G4fissionEvent::G4SmpTerrell(), G4fissionEvent::G4SmpWatt(), G4XNNElasticLowE::G4XNNElasticLowE(), G4XnpElasticLowE::G4XnpElasticLowE(), G4XnpTotalLowE::G4XnpTotalLowE(), G4NuclNuclDiffuseElastic::GammaLogB2n(), G4ElasticHNScattering::GaussianPt(), G4QuarkExchange::GaussianPt(), G4SingleDiffractiveExcitation::GaussianPt(), G4QGSDiffractiveExcitation::GaussianPt(), G4QGSMSplitableHadron::GaussianPt(), G4DiffractiveExcitation::GaussianPt(), G4QGSParticipants::GaussianPt(), G4FTFAnnihilation::GaussianPt(), G4FTFModel::GaussianPt(), G4eeToHadronsModel::GenerateCMPhoton(), G4PhotonEvaporation::GenerateGamma(), G4NucleiModel::generateInteractionLength(), G4RPGReaction::GenerateNBodyEvent(), G4RPGReaction::GenerateNBodyEventT(), G4ComponentAntiNuclNuclearXS::GetAntiHadronNucleonElCrSc(), G4ComponentAntiNuclNuclearXS::GetAntiHadronNucleonTotCrSc(), G4hhElastic::GetAqq(), G4hhElastic::GetAQQ(), G4ParticleHPInterpolator::GetBinIntegral(), G4QuasiElRatios::GetChExFactor(), G4LindhardSorensenData::GetDeltaL(), G4PhotoNuclearCrossSection::GetElementCrossSection(), G4ElectroNuclearCrossSection::GetElementCrossSection(), G4ElectroNuclearCrossSection::GetEquivalentPhotonEnergy(), G4ElectroNuclearCrossSection::GetEquivalentPhotonQ2(), G4ChipsHyperonElasticXS::GetExchangeT(), G4ChipsPionPlusElasticXS::GetExchangeT(), G4ChipsAntiBaryonElasticXS::GetExchangeT(), G4ChipsPionMinusElasticXS::GetExchangeT(), G4RKFieldIntegrator::GetExcitationEnergy(), G4GoudsmitSaundersonTable::GetGSAngularDtr(), G4NuclNuclDiffuseElastic::GetHadronNucleonXscNS(), G4ComponentAntiNuclNuclearXS::GetInelasticElementCrossSection(), G4PhotoNuclearCrossSection::GetIsoCrossSection(), G4ParticleHPKallbachMannSyst::GetKallbachZero(), G4RPGInelastic::GetNormalizationConstant(), G4ProtonInelasticCrossSection::GetProtonCrossSection(), G4QuasiElRatios::GetQF2IN_Ratio(), G4NuclearShellModelDensity::GetRadius(), G4NuclearFermiDensity::GetRadius(), G4ComponentAntiNuclNuclearXS::GetTotalElementCrossSection(), G4ScreeningMottCrossSection::GetTransitionRandom(), G4GoudsmitSaundersonMscModel::GetTransportMeanFreePath(), G4GoudsmitSaundersonMscModel::GetTransportMeanFreePathOnly(), G4ElectroNuclearCrossSection::GetVirtualFactor(), G4ParticleHPInterpolator::GetWeightedBinIntegral(), G4ElasticHadrNucleusHE::HadrNucDifferCrSec(), G4HadronNucleonXsc::HadronNucleonXscEL(), G4HadronNucleonXsc::HadronNucleonXscNS(), G4HadronNucleonXsc::HadronNucleonXscPDG(), G4HadronNucleonXsc::HadronNucleonXscPDG2005(), G4HadronNucleonXsc::HadronNucleonXscVU(), G4BraggIonModel::HeEffChargeSquare(), G4GSPWACorrections::InitDataMaterial(), G4FTFParameters::InitForInteraction(), G4BoldyshevTripletModel::Initialise(), G4mplIonisationModel::Initialise(), G4mplIonisationWithDeltaModel::Initialise(), G4MuPairProductionModel::Initialise(), G4GoudsmitSaundersonTable::Initialise(), G4EmCorrections::Initialise(), G4eBremParametrizedModel::InitialiseConstants(), G4LindhardSorensenData::InitialiseData(), G4eBremsstrahlungRelModel::InitialiseElementData(), G4PairProductionRelModel::InitialiseElementData(), G4VEmModel::InitialiseElementSelectors(), G4LivermoreGammaConversionModel::InitialiseProbability(), G4NucleiModel::initializeCascad(), G4GSMottCorrection::InitMCDataMaterial(), G4GoudsmitSaundersonTable::InitMoliereMSCParams(), G4SBBremTable::InitSamplingTables(), G4GoudsmitSaundersonTable::InitSCPCorrection(), G4ParticleHPVector::Integrate(), G4SynchrotronRadiation::InvSynFracInt(), G4Bessel::K0(), G4Bessel::K1(), G4HadronNucleonXsc::KaonNucleonXscVG(), lgam(), G4ParticleHPInterpolator::LinearLogarithmic(), G4SBBremTable::LoadSTGrid(), G4ParticleHPInterpolator::LogarithmicLinear(), G4ParticleHPInterpolator::LogarithmicLogarithmic(), G4Pow::logBase(), G4Pow::logX(), G4MuonVDNuclearModel::MakeSamplingTable(), G4MuPairProductionModel::MakeSamplingTables(), G4BetheHeitler5DModel::MaxDiffCrossSection(), MCGIDI_energy_sampleWatt(), MCGIDI_KalbachMann_sampleEp(), MCGIDI_outputChannel_sampleProductsAtE(), MCGIDI_sampling_interpolationValues(), MCGIDI_sampling_sampleX_from_pdfsOfXGivenW(), nf_exponentialIntegral(), nf_incompleteGammaFunction(), nf_incompleteGammaFunctionComplementary(), G4NuclNuclDiffuseElastic::PhaseFar(), G4NuclNuclDiffuseElastic::PhaseNear(), G4Bessel::pK0(), G4RPGInelastic::Pmltpc(), G4AntiNeutronAnnihilationAtRest::Poisso(), G4hhElastic::Pomeron(), G4GammaConversionToMuons::PostStepDoIt(), G4GammaGeneralProcess::PostStepGetPhysicalInteractionLength(), G4VEmProcess::PostStepGetPhysicalInteractionLength(), G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength(), G4VelocityTable::PrepareVelocityTable(), G4GEMChannelVI::ProbabilityDistributionFunction(), G4GeneratorPrecompoundInterface::Propagate(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), ptwXY_createGaussianCenteredSigma1(), ptwXY_f_integrate(), ptwXY_interpolatePoint(), ptwXY_LinLogToLinLin(), ptwXY_LogLinToLinLin(), ptwXY_LogLogToLinLin(), ptwXY_thicken(), ptwXY_update_biSectionMax(), G4InuclSpecialFunctions::randomGauss(), G4RPGStrangeProduction::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGTwoBody::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4SeltzerBergerModel::ReadData(), G4Generator2BS::RejectionFunction(), G4IonFluctuations::RelativisticFactor(), G4VProcess::ResetNumberOfInteractionLengthLeft(), G4PhysicsLogVector::Retrieve(), G4PreCompoundEmission::rho(), G4RPGReaction::Rotate(), G4ParticleHPWattSpectrum::Sample(), G4ParticleHPSimpleEvapSpectrum::Sample(), G4UrbanMscModel::SampleCosineTheta(), G4UrbanAdjointMscModel::SampleCosineTheta(), G4ModifiedTsai::SampleCosTheta(), G4DeltaAngle::SampleDirection(), G4RayleighAngularGenerator::SampleDirection(), G4UrbanMscModel::SampleDisplacement(), G4UrbanAdjointMscModel::SampleDisplacement(), G4UrbanMscModel::SampleDisplacementNew(), G4UrbanAdjointMscModel::SampleDisplacementNew(), G4VEmissionProbability::SampleEnergy(), G4SeltzerBergerModel::SampleEnergyTransfer(), G4UniversalFluctuation::SampleFluctuations(), G4FPYSamplingOps::SampleGaussian(), G4AntiNuclElastic::SampleInvariantT(), G4HadronElastic::SampleInvariantT(), G4EvaporationProbability::SampleKineticEnergy(), G4GEMChannel::SampleKineticEnergy(), G4GoudsmitSaundersonMscModel::SampleMSC(), G4VLongitudinalStringDecay::SampleQuarkPt(), G4KineticTrack::SampleResidualLifetime(), G4WentzelVIModel::SampleScattering(), G4BoldyshevTripletModel::SampleSecondaries(), G4LivermoreGammaConversionModelRC::SampleSecondaries(), G4LivermoreNuclearGammaConversionModel::SampleSecondaries(), G4HeatedKleinNishinaCompton::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4LDMBremModel::SampleSecondaries(), G4KleinNishinaCompton::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), G4eplusTo2GammaOKVIModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), G4eBremParametrizedModel::SampleSecondaries(), G4eeToTwoGammaModel::SampleSecondaries(), G4MuPairProductionModel::SampleSecondaries(), G4MuBremsstrahlungModel::SampleSecondaries(), G4MuBetheBlochModel::SampleSecondaries(), G4VEnergyLossProcess::SampleSubCutSecondaries(), G4ChargeExchange::SampleT(), G4LMsdGenerator::SampleT(), G4PhysicsLogVector::ScaleVector(), G4LivermoreNuclearGammaConversionModel::ScreenFunction1(), G4LivermoreGammaConversionModel::ScreenFunction1(), G4LivermoreGammaConversionModelRC::ScreenFunction1(), G4BetheHeitlerModel::ScreenFunction1(), G4PairProductionRelModel::ScreenFunction1(), G4eBremParametrizedModel::ScreenFunction1(), G4BetheHeitlerModel::ScreenFunction12(), G4PairProductionRelModel::ScreenFunction12(), G4LivermoreNuclearGammaConversionModel::ScreenFunction2(), G4LivermoreGammaConversionModel::ScreenFunction2(), G4LivermoreGammaConversionModelRC::ScreenFunction2(), G4BetheHeitlerModel::ScreenFunction2(), G4PairProductionRelModel::ScreenFunction2(), G4eBremParametrizedModel::ScreenFunction2(), G4DNAScreenedRutherfordElasticModel::ScreeningFactor(), G4IonisParamMat::SetDensityEffectParameters(), G4VEmProcess::SetMaxKinEnergy(), G4IonisParamMat::SetMeanExcitationEnergy(), G4VEmProcess::SetMinKinEnergy(), G4IonCoulombCrossSection::SetupTarget(), G4AtimaEnergyLossModel::sezi_dedx_e(), G4AtimaEnergyLossModel::sezi_p_se(), G4EmCorrections::ShellCorrectionSTD(), G4UrbanMscModel::SimpleScattering(), G4UrbanAdjointMscModel::SimpleScattering(), G4LundStringFragmentation::SplitEandP(), G4BraggModel::StoppingPower(), G4BraggIonModel::StoppingPower(), G4EnergyLossForExtrapolator::TrueStepLength(), G4UrbanMscModel::UpdateCache(), G4UrbanAdjointMscModel::UpdateCache(), G4VelocityTable::Value(), G4Clebsch::WignerLittleD(), and G4NucleiModel::zoneIntegralWoodsSaxon().
G4Logf()
G4float G4Logf (G4float x) inline
Definition at line 310 of file G4Log.hh.
G4Logfv()
void G4Logfv (const uint32_t size, G4float const *__restrict__ iarray, G4float *__restrict__ oarray)
G4Logv()
void G4Logv (const uint32_t size, G4double const *__restrict__ iarray, G4double *__restrict__ oarray)
logfv()
void logfv (const uint32_t size, G4float const *__restrict__ iarray, G4float *__restrict__ oarray)
logv()
void logv (const uint32_t size, G4double const *__restrict__ iarray, G4double *__restrict__ oarray)
Referenced by CCalSensitiveDetectors::registerVolume().