Geant4: G4ParticleHPFieldPoint Class Reference
G4ParticleHPFieldPoint Class Reference
#include <G4ParticleHPFieldPoint.hh>
Public Member Functions
G4ParticleHPFieldPoint ()
G4ParticleHPFieldPoint (G4int n)
void operator= (const G4ParticleHPFieldPoint &aSet)
~G4ParticleHPFieldPoint ()
void InitY (G4int n)
G4int GetDepth () const
G4double GetX () const
G4double GetY (G4int i) const
void SetX (G4double e)
void SetY (G4int i, G4double x)
void SetData (G4double e, G4int i, G4double x)
Private Attributes
G4double X
G4double * Y
G4int nP
Detailed Description
Definition at line 34 of file G4ParticleHPFieldPoint.hh.
Constructor & Destructor Documentation
G4ParticleHPFieldPoint() [1/2]
G4ParticleHPFieldPoint::G4ParticleHPFieldPoint () inline
Definition at line 38 of file G4ParticleHPFieldPoint.hh.
G4ParticleHPFieldPoint() [2/2]
G4ParticleHPFieldPoint::G4ParticleHPFieldPoint (G4int n)
Definition at line 35 of file G4ParticleHPFieldPoint.cc.
~G4ParticleHPFieldPoint()
G4ParticleHPFieldPoint::~G4ParticleHPFieldPoint ()
Definition at line 54 of file G4ParticleHPFieldPoint.cc.
Member Function Documentation
GetDepth()
G4int G4ParticleHPFieldPoint::GetDepth () const inline
Definition at line 53 of file G4ParticleHPFieldPoint.hh.
Referenced by G4ParticleHPField::Dump(), and operator=().
GetX()
G4double G4ParticleHPFieldPoint::GetX () const inline
Definition at line 54 of file G4ParticleHPFieldPoint.hh.
Referenced by G4ParticleHPField::Dump(), G4ParticleHPField::GetEnergy(), G4ParticleHPField::GetX(), G4ParticleHPField::GetY(), and operator=().
GetY()
G4double G4ParticleHPFieldPoint::GetY (G4int i) const inline
Definition at line 55 of file G4ParticleHPFieldPoint.hh.
Referenced by G4ParticleHPField::Dump(), G4ParticleHPField::GetY(), and operator=().
InitY()
void G4ParticleHPFieldPoint::InitY (G4int n)
Definition at line 59 of file G4ParticleHPFieldPoint.cc.
Referenced by G4ParticleHPField::InitY().
operator=()
void G4ParticleHPFieldPoint::operator= (const G4ParticleHPFieldPoint & aSet)
Definition at line 43 of file G4ParticleHPFieldPoint.cc.
SetData()
void G4ParticleHPFieldPoint::SetData (G4double e, G4int i, G4double x) inline
Definition at line 60 of file G4ParticleHPFieldPoint.hh.
Referenced by G4ParticleHPField::G4ParticleHPField(), and G4ParticleHPField::SetData().
SetX()
void G4ParticleHPFieldPoint::SetX (G4double e) inline
Definition at line 57 of file G4ParticleHPFieldPoint.hh.
Referenced by G4ParticleHPField::SetEnergy(), and G4ParticleHPField::SetX().
SetY()
void G4ParticleHPFieldPoint::SetY (G4int i, G4double x) inline
Definition at line 58 of file G4ParticleHPFieldPoint.hh.
Referenced by G4ParticleHPField::SetY().
Field Documentation
nP
G4int G4ParticleHPFieldPoint::nP private
Definition at line 66 of file G4ParticleHPFieldPoint.hh.
Referenced by G4ParticleHPFieldPoint(), GetDepth(), and InitY().
X
G4double G4ParticleHPFieldPoint::X private
Definition at line 64 of file G4ParticleHPFieldPoint.hh.
Referenced by G4ParticleHPFieldPoint(), GetX(), InitY(), operator=(), SetData(), and SetX().
Y
G4double* G4ParticleHPFieldPoint::Y private
Definition at line 65 of file G4ParticleHPFieldPoint.hh.
Referenced by G4ParticleHPFieldPoint(), GetY(), InitY(), operator=(), SetData(), SetY(), and ~G4ParticleHPFieldPoint().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/particle_hp/include/G4ParticleHPFieldPoint.hh
source/processes/hadronic/models/particle_hp/src/G4ParticleHPFieldPoint.cc