Geant4: lightions Namespace Reference
lightions Namespace Reference
Functions
void Init ()
Variables
static const G4ParticleDefinition * p_proton = nullptr
static const G4ParticleDefinition * p_deuteron = nullptr
static const G4ParticleDefinition * p_triton = nullptr
static const G4ParticleDefinition * p_alpha = nullptr
static const G4ParticleDefinition * p_He3 = nullptr
Function Documentation
Init()
void lightions::Init ()
Definition at line 90 of file G4IonTable.cc.
Referenced by G4ParticleHPData::addPhysicsVector(), G4ParticleHPCapture::BuildPhysicsTable(), G4ParticleHPFission::BuildPhysicsTable(), G4ParticleHPElastic::BuildPhysicsTable(), G4ParticleHPInelastic::BuildPhysicsTable(), G4AttCheck::G4AttCheck(), G4ParticleHPData::G4ParticleHPData(), G4IonTable::GetLightIon(), and G4IonTable::InitializeLightIons().
Variable Documentation
p_alpha
const G4ParticleDefinition* lightions::p_alpha = nullptr static
Definition at line 88 of file G4IonTable.cc.
Referenced by G4IonTable::GetLightIon(), and Init().
p_deuteron
const G4ParticleDefinition* lightions::p_deuteron = nullptr static
Definition at line 86 of file G4IonTable.cc.
Referenced by G4IonTable::GetLightIon(), and Init().
p_He3
const G4ParticleDefinition* lightions::p_He3 = nullptr static
Definition at line 89 of file G4IonTable.cc.
Referenced by G4IonTable::GetLightIon(), and Init().
p_proton
const G4ParticleDefinition* lightions::p_proton = nullptr static
Definition at line 85 of file G4IonTable.cc.
Referenced by G4IonTable::GetLightIon(), and Init().
p_triton
const G4ParticleDefinition* lightions::p_triton = nullptr static
Definition at line 87 of file G4IonTable.cc.
Referenced by G4IonTable::GetLightIon(), and Init().