Geant4: G4VBasicShell Class Reference
G4VBasicShell Class Reference abstract
#include <G4VBasicShell.hh>
Public Member Functions
G4VBasicShell ()
virtual ~G4VBasicShell ()
virtual G4UIsession * SessionStart ()=0
virtual void PauseSessionStart (const G4String &Prompt)=0
Public Member Functions inherited from G4UIsession
G4UIsession ()
G4UIsession (G4int iBatch)
virtual ~G4UIsession ()
virtual G4int ReceiveG4cout (const G4String &coutString)
virtual G4int ReceiveG4cerr (const G4String &cerrString)
Public Member Functions inherited from G4coutDestination
G4coutDestination ()=default
virtual ~G4coutDestination ()
void AddCoutTransformer (const Transformer &t)
void AddCoutTransformer (Transformer &&t)
void AddCerrTransformer (const Transformer &t)
void AddCerrTransformer (Transformer &&t)
virtual void ResetTransformers ()
G4int ReceiveG4cout_ (const G4String &msg)
G4int ReceiveG4cerr_ (const G4String &msg)
Protected Member Functions
G4String ModifyToFullPathCommand (const char *aCommandLine) const
G4String GetCurrentWorkingDirectory () const
G4bool ChangeDirectory (const char *newDir)
G4UIcommandTree * FindDirectory (const char *dirName) const
G4UIcommand * FindCommand (const char *commandName) const
G4String Complete (const G4String &)
G4String FindMatchingPath (G4UIcommandTree *, const G4String &)
virtual void ExecuteCommand (const G4String &)
virtual G4bool GetHelpChoice (G4int &)=0
virtual void ExitHelp () const =0
void ApplyShellCommand (const G4String &, G4bool &, G4bool &)
void ShowCurrent (const G4String &) const
void ChangeDirectoryCommand (const G4String &)
void ListDirectory (const G4String &) const
void TerminalHelp (const G4String &)
Private Member Functions
G4String ModifyPath (const G4String &tempPath) const
Private Attributes
G4String currentDirectory
Additional Inherited Members
Public Types inherited from G4coutDestination
using Transformer = std::function< G4bool(G4String &)>
Static Public Member Functions inherited from G4UIsession
static G4int InSession ()
Protected Attributes inherited from G4UIsession
G4int ifBatch
Protected Attributes inherited from G4coutDestination
std::vector< Transformer > transformersCout
std::vector< Transformer > transformersCerr
Static Protected Attributes inherited from G4UIsession
static G4ICOMS_DLL G4int inSession = 0
Static Protected Attributes inherited from G4coutDestination
static G4coutDestination * masterG4coutDestination = 0
Detailed Description
Definition at line 51 of file G4VBasicShell.hh.
Constructor & Destructor Documentation
G4VBasicShell()
G4VBasicShell::G4VBasicShell ()
Definition at line 38 of file G4VBasicShell.cc.
~G4VBasicShell()
G4VBasicShell::~G4VBasicShell () virtual
Definition at line 43 of file G4VBasicShell.cc.
Member Function Documentation
ApplyShellCommand()
void G4VBasicShell::ApplyShellCommand (const G4String & a_string, G4bool & exitSession, G4bool & exitPause) protected
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Definition at line 231 of file G4VBasicShell.cc.
ChangeDirectory()
G4bool G4VBasicShell::ChangeDirectory (const char * newDir) protected
Definition at line 74 of file G4VBasicShell.cc.
Referenced by ChangeDirectoryCommand().
ChangeDirectoryCommand()
void G4VBasicShell::ChangeDirectoryCommand (const G4String & newCommand) protected
Definition at line 325 of file G4VBasicShell.cc.
Referenced by ApplyShellCommand(), G4MPIsession::GetCommand(), G4ZMQServer::GetCommand(), and G4UIterminal::GetCommand().
Complete()
G4String G4VBasicShell::Complete (const G4String & commandName) protected
Definition at line 180 of file G4VBasicShell.cc.
ExecuteCommand()
void G4VBasicShell::ExecuteCommand (const G4String & aCommand) protected virtual
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Reimplemented in G4ZMQServer, G4UIGainServer, and G4UIterminal.
Definition at line 205 of file G4VBasicShell.cc.
Referenced by ApplyShellCommand().
ExitHelp()
virtual void G4VBasicShell::ExitHelp () const protected pure virtual
Implemented in G4UIGainServer, G4UIterminal, G4VMPIsession, and G4ZMQServer.
Referenced by TerminalHelp().
FindCommand()
G4UIcommand * G4VBasicShell::FindCommand (const char * commandName) const protected
Definition at line 109 of file G4VBasicShell.cc.
Referenced by G4VMPIsession::ExecCommand(), G4ZMQServer::ExecuteCommand(), and G4UIterminal::ExecuteCommand().
FindDirectory()
G4UIcommandTree * G4VBasicShell::FindDirectory (const char * dirName) const protected
Definition at line 87 of file G4VBasicShell.cc.
Referenced by ChangeDirectory(), ListDirectory(), and G4ZMQServer::SessionStart().
FindMatchingPath()
G4String G4VBasicShell::FindMatchingPath (G4UIcommandTree * aTree, const G4String & aCommandPath) protected
Definition at line 195 of file G4VBasicShell.cc.
Referenced by Complete().
GetCurrentWorkingDirectory()
G4String G4VBasicShell::GetCurrentWorkingDirectory () const protected
Definition at line 69 of file G4VBasicShell.cc.
Referenced by ApplyShellCommand(), G4MPIsession::GetCommand(), G4ZMQServer::GetCommand(), G4UIterminal::GetCommand(), ListDirectory(), G4ZMQServer::SessionStart(), and TerminalHelp().
GetHelpChoice()
virtual G4bool G4VBasicShell::GetHelpChoice (G4int &) protected pure virtual
Implemented in G4VMPIsession, G4UIGainServer, G4UIterminal, and G4ZMQServer.
Referenced by TerminalHelp().
ListDirectory()
void G4VBasicShell::ListDirectory (const G4String & newCommand) const protected
Definition at line 339 of file G4VBasicShell.cc.
Referenced by ApplyShellCommand(), G4MPIsession::GetCommand(), G4ZMQServer::GetCommand(), and G4UIterminal::GetCommand().
ModifyPath()
G4String G4VBasicShell::ModifyPath (const G4String & tempPath) const private
Definition at line 124 of file G4VBasicShell.cc.
Referenced by ChangeDirectory(), Complete(), FindCommand(), FindDirectory(), and ModifyToFullPathCommand().
ModifyToFullPathCommand()
G4String G4VBasicShell::ModifyToFullPathCommand (const char * aCommandLine) const protected
Definition at line 47 of file G4VBasicShell.cc.
Referenced by ApplyShellCommand(), G4MPIsession::GetCommand(), G4ZMQServer::GetCommand(), G4UIterminal::GetCommand(), ShowCurrent(), and TerminalHelp().
PauseSessionStart()
virtual void G4VBasicShell::PauseSessionStart (const G4String & Prompt) pure virtual
Reimplemented from G4UIsession.
Implemented in G4UIGainServer, G4UIterminal, G4VMPIsession, and G4ZMQServer.
SessionStart()
virtual G4UIsession* G4VBasicShell::SessionStart () pure virtual
Reimplemented from G4UIsession.
Implemented in G4UIGainServer, G4UIterminal, G4ZMQServer, G4MPIsession, and G4MPIbatch.
ShowCurrent()
void G4VBasicShell::ShowCurrent (const G4String & newCommand) const protected
Definition at line 313 of file G4VBasicShell.cc.
Referenced by ApplyShellCommand(), G4MPIsession::GetCommand(), G4ZMQServer::GetCommand(), and G4UIterminal::GetCommand().
TerminalHelp()
void G4VBasicShell::TerminalHelp (const G4String & newCommand) protected
Definition at line 355 of file G4VBasicShell.cc.
Referenced by ApplyShellCommand(), G4MPIsession::GetCommand(), G4ZMQServer::GetCommand(), and G4UIterminal::GetCommand().
Field Documentation
currentDirectory
G4String G4VBasicShell::currentDirectory private
Definition at line 101 of file G4VBasicShell.hh.
Referenced by ChangeDirectory(), GetCurrentWorkingDirectory(), and ModifyPath().
The documentation for this class was generated from the following files:
source/interfaces/common/include/G4VBasicShell.hh
source/interfaces/common/src/G4VBasicShell.cc