Geant4: G4AblaRandom Namespace Reference
G4AblaRandom Namespace Reference
Functions
double flat ()
Function Documentation
flat()
double G4AblaRandom::flat ()
Definition at line 48 of file G4AblaRandom.cc.
Referenced by G4Abla::DeexcitationAblaxx(), G4Abla::evap_postsaddle(), G4Abla::evapora(), G4Abla::fission(), G4Abla::fissionDistri(), G4Abla::fmaxhaz(), G4Abla::fmaxhaz_old(), G4Abla::fvmaxhaz(), G4Abla::fvmaxhaz_neut(), G4Abla::haz(), G4Abla::IPOWERLIMHAZ(), G4Abla::part_fiss(), G4EvaporationProbability::SampleKineticEnergy(), G4BoldyshevTripletModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4eplusTo2GammaOKVIModel::SampleSecondaries(), G4eBremParametrizedModel::SampleSecondaries(), G4eeToTwoGammaModel::SampleSecondaries(), and G4Abla::unstable_tke().