Geant4: G4ITType Struct Reference
G4ITType Struct Reference
Tag the G4IT Should be automatically setup by G4IT using : ITDef(MyIT) and ITImp(MyIT)
#include <G4ITType.hh>
Public Member Functions
G4ITType (const int d_=0)
G4ITType (const G4ITType &d_)
G4ITType & operator= (const G4ITType &rhs)
G4ITType & operator= (const int &rhs)
operator int & ()
operator const int & () const
bool operator== (const G4ITType &rhs) const
bool operator== (const int &rhs) const
bool operator< (const G4ITType &rhs) const
void operator++ ()
Static Public Member Functions
static size_t size ()
Private Attributes
int fValue
Friends
G4ITType operator+ (const G4ITType &left, const int &right)
G4ITType operator- (const G4ITType &left, const int &right)
Detailed Description
Tag the G4IT Should be automatically setup by G4IT using : ITDef(MyIT) and ITImp(MyIT)
Definition at line 59 of file G4ITType.hh.
Constructor & Destructor Documentation
G4ITType() [1/2]
G4ITType::G4ITType (const int d_ = 0) inline
Definition at line 70 of file G4ITType.hh.
G4ITType() [2/2]
G4ITType::G4ITType (const G4ITType & d_) inline
Definition at line 71 of file G4ITType.hh.
Member Function Documentation
operator const int &()
G4ITType::operator const int & () const inline
Definition at line 75 of file G4ITType.hh.
operator int &()
G4ITType::operator int & () inline
Definition at line 74 of file G4ITType.hh.
operator++()
void G4ITType::operator++ () inline
Definition at line 79 of file G4ITType.hh.
operator<()
bool G4ITType::operator< (const G4ITType & rhs) const inline
Definition at line 78 of file G4ITType.hh.
operator=() [1/2]
G4ITType & G4ITType::operator= (const G4ITType & rhs)
Definition at line 50 of file G4ITType.cc.
operator=() [2/2]
G4ITType& G4ITType::operator= (const int & rhs) inline
Definition at line 73 of file G4ITType.hh.
operator==() [1/2]
bool G4ITType::operator== (const G4ITType & rhs) const inline
Definition at line 76 of file G4ITType.hh.
operator==() [2/2]
bool G4ITType::operator== (const int & rhs) const inline
Definition at line 77 of file G4ITType.hh.
size()
size_t G4ITType::size () static
Definition at line 45 of file G4ITType.cc.
Referenced by G4ITModelHandler::G4ITModelHandler(), G4ITModelProcessor::G4ITModelProcessor(), and G4ITModelHandler::RegisterModel().
Friends And Related Function Documentation
operator+
G4ITType operator+ (const G4ITType & left, const int & right) friend
Definition at line 82 of file G4ITType.hh.
operator-
G4ITType operator- (const G4ITType & left, const int & right) friend
Definition at line 87 of file G4ITType.hh.
Field Documentation
fValue
int G4ITType::fValue private
Definition at line 64 of file G4ITType.hh.
Referenced by operator const int &(), operator int &(), operator++(), operator<(), operator=(), and operator==().
The documentation for this struct was generated from the following files:
source/processes/electromagnetic/dna/management/include/G4ITType.hh
source/processes/electromagnetic/dna/management/src/G4ITType.cc