Geant4: G4IonisParamElm Class Reference
G4IonisParamElm Class Reference
#include <G4IonisParamElm.hh>
Public Member Functions
G4IonisParamElm (G4double Z)
~G4IonisParamElm ()
G4double GetZ () const
G4double GetZ3 () const
G4double GetZZ3 () const
G4double GetlogZ3 () const
G4double GetTau0 () const
G4double GetTaul () const
G4double GetAlow () const
G4double GetBlow () const
G4double GetClow () const
G4double GetMeanExcitationEnergy () const
G4double GetFermiVelocity () const
G4double GetLFactor () const
G4double * GetShellCorrectionVector () const
G4IonisParamElm (__void__ &)
Private Member Functions
G4IonisParamElm & operator= (const G4IonisParamElm &)=delete
G4bool operator== (const G4IonisParamElm &) const =delete
G4bool operator!= (const G4IonisParamElm &) const =delete
G4IonisParamElm (G4IonisParamElm &)=delete
Private Attributes
G4double fZ
G4double fZ3
G4double fZZ3
G4double flogZ3
G4double fTau0
G4double fTaul
G4double fBetheBlochLow
G4double fAlow
G4double fBlow
G4double fClow
G4double fMeanExcitationEnergy
G4double * fShellCorrectionVector
G4double fVFermi
G4double fLFactor
Detailed Description
Definition at line 50 of file G4IonisParamElm.hh.
Constructor & Destructor Documentation
G4IonisParamElm() [1/3]
G4IonisParamElm::G4IonisParamElm (G4double Z)
Definition at line 51 of file G4IonisParamElm.cc.
~G4IonisParamElm()
G4IonisParamElm::~G4IonisParamElm ()
Definition at line 149 of file G4IonisParamElm.cc.
G4IonisParamElm() [2/3]
G4IonisParamElm::G4IonisParamElm (__void__ &)
Definition at line 140 of file G4IonisParamElm.cc.
G4IonisParamElm() [3/3]
G4IonisParamElm::G4IonisParamElm (G4IonisParamElm &) private delete
Member Function Documentation
GetAlow()
G4double G4IonisParamElm::GetAlow () const inline
Definition at line 69 of file G4IonisParamElm.hh.
GetBlow()
G4double G4IonisParamElm::GetBlow () const inline
Definition at line 70 of file G4IonisParamElm.hh.
GetClow()
G4double G4IonisParamElm::GetClow () const inline
Definition at line 71 of file G4IonisParamElm.hh.
GetFermiVelocity()
G4double G4IonisParamElm::GetFermiVelocity () const inline
Definition at line 77 of file G4IonisParamElm.hh.
Referenced by G4IonisParamMat::ComputeIonParameters().
GetLFactor()
G4double G4IonisParamElm::GetLFactor () const inline
Definition at line 78 of file G4IonisParamElm.hh.
Referenced by G4IonisParamMat::ComputeIonParameters().
GetlogZ3()
G4double G4IonisParamElm::GetlogZ3 () const inline
Definition at line 62 of file G4IonisParamElm.hh.
Referenced by G4BetheHeitlerModel::InitialiseElementData(), G4PairProductionRelModel::InitialiseElementData(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LivermoreGammaConversionModelRC::SampleSecondaries(), G4LivermoreNuclearGammaConversionModel::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), and G4BetheHeitlerModel::SampleSecondaries().
GetMeanExcitationEnergy()
G4double G4IonisParamElm::GetMeanExcitationEnergy () const inline
Definition at line 74 of file G4IonisParamElm.hh.
Referenced by G4IonisParamMat::ComputeMeanParameters().
GetShellCorrectionVector()
G4double* G4IonisParamElm::GetShellCorrectionVector () const inline
Definition at line 80 of file G4IonisParamElm.hh.
GetTau0()
G4double G4IonisParamElm::GetTau0 () const inline
Definition at line 64 of file G4IonisParamElm.hh.
GetTaul()
G4double G4IonisParamElm::GetTaul () const inline
Definition at line 67 of file G4IonisParamElm.hh.
GetZ()
G4double G4IonisParamElm::GetZ () const inline
Definition at line 59 of file G4IonisParamElm.hh.
GetZ3()
G4double G4IonisParamElm::GetZ3 () const inline
Definition at line 60 of file G4IonisParamElm.hh.
Referenced by G4PairProductionRelModel::InitialiseElementData(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LivermoreGammaConversionModelRC::SampleSecondaries(), G4LivermoreNuclearGammaConversionModel::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), and G4BetheHeitlerModel::SampleSecondaries().
GetZZ3()
G4double G4IonisParamElm::GetZZ3 () const inline
Definition at line 61 of file G4IonisParamElm.hh.
operator!=()
G4bool G4IonisParamElm::operator!= (const G4IonisParamElm &) const private delete
operator=()
G4IonisParamElm& G4IonisParamElm::operator= (const G4IonisParamElm &) private delete
operator==()
G4bool G4IonisParamElm::operator== (const G4IonisParamElm &) const private delete
Field Documentation
fAlow
G4double G4IonisParamElm::fAlow private
Definition at line 108 of file G4IonisParamElm.hh.
Referenced by G4IonisParamElm(), and GetAlow().
fBetheBlochLow
G4double G4IonisParamElm::fBetheBlochLow private
Definition at line 107 of file G4IonisParamElm.hh.
Referenced by G4IonisParamElm().
fBlow
G4double G4IonisParamElm::fBlow private
Definition at line 108 of file G4IonisParamElm.hh.
Referenced by G4IonisParamElm(), and GetBlow().
fClow
G4double G4IonisParamElm::fClow private
Definition at line 108 of file G4IonisParamElm.hh.
Referenced by G4IonisParamElm(), and GetClow().
fLFactor
G4double G4IonisParamElm::fLFactor private
Definition at line 114 of file G4IonisParamElm.hh.
Referenced by G4IonisParamElm(), and GetLFactor().
flogZ3
G4double G4IonisParamElm::flogZ3 private
Definition at line 101 of file G4IonisParamElm.hh.
Referenced by G4IonisParamElm(), and GetlogZ3().
fMeanExcitationEnergy
G4double G4IonisParamElm::fMeanExcitationEnergy private
Definition at line 109 of file G4IonisParamElm.hh.
Referenced by G4IonisParamElm(), and GetMeanExcitationEnergy().
fShellCorrectionVector
G4double* G4IonisParamElm::fShellCorrectionVector private
Definition at line 110 of file G4IonisParamElm.hh.
Referenced by G4IonisParamElm(), GetShellCorrectionVector(), and ~G4IonisParamElm().
fTau0
G4double G4IonisParamElm::fTau0 private
Definition at line 105 of file G4IonisParamElm.hh.
Referenced by G4IonisParamElm(), and GetTau0().
fTaul
G4double G4IonisParamElm::fTaul private
Definition at line 106 of file G4IonisParamElm.hh.
Referenced by G4IonisParamElm(), and GetTaul().
fVFermi
G4double G4IonisParamElm::fVFermi private
Definition at line 113 of file G4IonisParamElm.hh.
Referenced by G4IonisParamElm(), and GetFermiVelocity().
fZ
G4double G4IonisParamElm::fZ private
Definition at line 98 of file G4IonisParamElm.hh.
Referenced by G4IonisParamElm(), and GetZ().
fZ3
G4double G4IonisParamElm::fZ3 private
Definition at line 99 of file G4IonisParamElm.hh.
Referenced by G4IonisParamElm(), and GetZ3().
fZZ3
G4double G4IonisParamElm::fZZ3 private
Definition at line 100 of file G4IonisParamElm.hh.
Referenced by G4IonisParamElm(), and GetZZ3().
The documentation for this class was generated from the following files:
source/materials/include/G4IonisParamElm.hh
source/materials/src/G4IonisParamElm.cc