Geant4: G4INCL::Nucleus Class Reference
G4INCL::Nucleus Class Reference
#include <G4INCLNucleus.hh>
Data Structures
struct ConservationBalance
Struct for conservation laws.
Public Member Functions
Nucleus (G4int mass, G4int charge, G4int strangess, Config const *const conf, const G4double universeRadius=-1.)
virtual ~Nucleus ()
Nucleus (const Nucleus &rhs)
Dummy copy constructor to silence Coverity warning.
Nucleus & operator= (const Nucleus &rhs)
Dummy assignment operator to silence Coverity warning.
void initializeParticles ()
Call the Cluster method to generate the initial distribution of particles.
void insertParticle (Particle *p)
Insert a new particle (e.g. a projectile) in the nucleus.
void applyFinalState (FinalState *)
Apply reaction final state information to the nucleus.
G4int getInitialA () const
G4int getInitialZ () const
G4int getInitialS () const
void propagateParticles (G4double step)
Propagate the particles one time step.
G4int getNumberOfEnteringProtons () const
G4int getNumberOfEnteringNeutrons () const
G4int getNumberOfEnteringPions () const
G4int getNumberOfEnteringKaons () const
G4double computeSeparationEnergyBalance () const
Outgoing - incoming separation energies.
G4bool decayOutgoingDeltas ()
Force the decay of outgoing deltas.
G4bool decayInsideDeltas ()
Force the decay of deltas inside the nucleus.
G4bool decayInsideStrangeParticles ()
Force the transformation of strange particles into a Lambda;.
G4bool decayOutgoingPionResonances (G4double timeThreshold)
Force the decay of outgoing PionResonances (eta/omega).
G4bool decayOutgoingSigmaZero (G4double timeThreshold)
Force the decay of outgoing Neutral Sigma.
G4bool decayOutgoingNeutralKaon ()
Force the transformation of outgoing Neutral Kaon into propation eigenstate.
G4bool decayOutgoingClusters ()
Force the decay of unstable outgoing clusters.
G4bool decayMe ()
Force the phase-space decay of the Nucleus.
void emitInsidePions ()
Force emission of all pions inside the nucleus.
void emitInsideStrangeParticles ()
Force emission of all strange particles inside the nucleus.
G4int emitInsideLambda ()
Force emission of all Lambda (desexitation code with strangeness not implanted yet)
G4bool emitInsideKaon ()
Force emission of all Kaon inside the nucleus.
void computeRecoilKinematics ()
Compute the recoil momentum and spin of the nucleus.
ThreeVector computeCenterOfMass () const
Compute the current center-of-mass position.
G4double computeTotalEnergy () const
Compute the current total energy.
G4double computeExcitationEnergy () const
Compute the current excitation energy.
void setIncomingAngularMomentum (const ThreeVector &j)
Set the incoming angular-momentum vector.
const ThreeVector & getIncomingAngularMomentum () const
Get the incoming angular-momentum vector.
void setIncomingMomentum (const ThreeVector &p)
Set the incoming momentum vector.
const ThreeVector & getIncomingMomentum () const
Get the incoming momentum vector.
void setInitialEnergy (const G4double e)
Set the initial energy.
G4double getInitialEnergy () const
Get the initial energy.
G4double getExcitationEnergy () const
Get the excitation energy of the nucleus.
G4bool containsDeltas ()
Returns true if the nucleus contains any deltas.
G4bool containsAntiKaon ()
Returns true if the nucleus contains any anti Kaons.
G4bool containsLambda ()
Returns true if the nucleus contains any Lambda.
G4bool containsSigma ()
Returns true if the nucleus contains any Sigma.
G4bool containsKaon ()
Returns true if the nucleus contains any Kaons.
G4bool containsEtas ()
Returns true if the nucleus contains any etas.
G4bool containsOmegas ()
Returns true if the nucleus contains any omegas.
std::string print ()
Print the nucleus info.
Store * getStore () const
void setStore (Store *s)
G4double getInitialInternalEnergy () const
G4bool isEventTransparent () const
Is the event transparent?
G4bool hasRemnant () const
Does the nucleus give a cascade remnant?
void fillEventInfo (EventInfo *eventInfo)
Fill the event info which contains INCL output data.
G4bool getTryCompoundNucleus ()
G4double getTransmissionBarrier (Particle const *const p)
Get the transmission barrier.
ConservationBalance getConservationBalance (EventInfo const &theEventInfo, const G4bool afterRecoil) const
Compute charge, mass, energy and momentum balance.
void useFusionKinematics ()
Adjust the kinematics for complete-fusion events.
G4double getSurfaceRadius (Particle const *const particle) const
Get the maximum allowed radius for a given particle.
G4double getUniverseRadius () const
Getter for theUniverseRadius.
void setUniverseRadius (const G4double universeRadius)
Setter for theUniverseRadius.
G4bool isNucleusNucleusCollision () const
Is it a nucleus-nucleus collision?
void setNucleusNucleusCollision ()
Set a nucleus-nucleus collision.
void setParticleNucleusCollision ()
Set a particle-nucleus collision.
void setProjectileRemnant (ProjectileRemnant *const c)
Set the projectile remnant.
ProjectileRemnant * getProjectileRemnant () const
Get the projectile remnant.
void deleteProjectileRemnant ()
Delete the projectile remnant.
void finalizeProjectileRemnant (const G4double emissionTime)
Finalise the projectile remnant.
void updatePotentialEnergy (Particle *p) const
Update the particle potential energy.
void setDensity (NuclearDensity const *const d)
Setter for theDensity.
const NuclearDensity * getDensity () const
Getter for theDensity.
const NuclearPotential::INuclearPotential * getPotential () const
Getter for thePotential.
Public Member Functions inherited from G4INCL::Cluster
Cluster (const G4int Z, const G4int A, const G4int S, const G4bool createParticleSampler=true)
Standard Cluster constructor.
template<class Iterator >
Cluster (Iterator begin, Iterator end)
A cluster can be directly built from a list of particles.
virtual ~Cluster ()
Cluster (const Cluster &rhs)
Copy constructor.
Cluster & operator= (const Cluster &rhs)
Assignment operator.
void swap (Cluster &rhs)
Helper method for the assignment operator.
ParticleSpecies getSpecies () const
Get the particle species.
void deleteParticles ()
void clearParticles ()
void setZ (const G4int Z)
Set the charge number of the cluster.
void setA (const G4int A)
Set the mass number of the cluster.
void setS (const G4int S)
Set the strangess number of the cluster.
G4double getExcitationEnergy () const
Get the excitation energy of the cluster.
void setExcitationEnergy (const G4double e)
Set the excitation energy of the cluster.
virtual G4double getTableMass () const
Get the real particle mass.
const ParticleList & getParticles () const
Get the list of particles in the cluster.
void removeParticle (Particle *const p)
Remove a particle from the cluster components.
void addParticle (Particle *const p)
Add one particle to the cluster.
void updateClusterParameters ()
Set total cluster mass, energy, size, etc. from the particles.
void addParticles (ParticleList const &pL)
Add a list of particles to the cluster.
ParticleList getParticleList () const
Returns the list of particles that make up the cluster.
std::string print () const
void internalBoostToCM ()
Boost to the CM of the component particles.
void putParticlesOffShell ()
Put the cluster components off shell.
void setPosition (const ThreeVector &position)
Set the position of the cluster.
void boost (const ThreeVector &aBoostVector)
Boost the cluster with the indicated velocity.
void freezeInternalMotion ()
Freeze the internal motion of the particles.
virtual void rotatePosition (const G4double angle, const ThreeVector &axis)
Rotate position of all the particles.
virtual void rotateMomentum (const G4double angle, const ThreeVector &axis)
Rotate momentum of all the particles.
virtual void makeProjectileSpectator ()
Make all the components projectile spectators, too.
virtual void makeTargetSpectator ()
Make all the components target spectators, too.
virtual void makeParticipant ()
Make all the components participants, too.
const ThreeVector & getSpin () const
Get the spin of the nucleus.
void setSpin (const ThreeVector &j)
Set the spin of the nucleus.
G4INCL::ThreeVector getAngularMomentum () const
Get the total angular momentum (orbital + spin)
Public Member Functions inherited from G4INCL::Particle
Particle ()
Particle (ParticleType t, G4double energy, ThreeVector const &momentum, ThreeVector const &position)
Particle (ParticleType t, ThreeVector const &momentum, ThreeVector const &position)
virtual ~Particle ()
Particle (const Particle &rhs)
Copy constructor.
Particle & operator= (const Particle &rhs)
Assignment operator.
G4INCL::ParticleType getType () const
Get the particle type.
void setType (ParticleType t)
G4bool isNucleon () const
Is this a nucleon?
ParticipantType getParticipantType () const
void setParticipantType (ParticipantType const p)
G4bool isParticipant () const
G4bool isTargetSpectator () const
G4bool isProjectileSpectator () const
G4bool isPion () const
Is this a pion?
G4bool isEta () const
Is this an eta?
G4bool isOmega () const
Is this an omega?
G4bool isEtaPrime () const
Is this an etaprime?
G4bool isPhoton () const
Is this a photon?
G4bool isResonance () const
Is it a resonance?
G4bool isDelta () const
Is it a Delta?
G4bool isSigma () const
Is this a Sigma?
G4bool isKaon () const
Is this a Kaon?
G4bool isAntiKaon () const
Is this an antiKaon?
G4bool isLambda () const
Is this a Lambda?
G4bool isNucleonorLambda () const
Is this a Nucleon or a Lambda?
G4bool isHyperon () const
Is this an Hyperon?
G4bool isMeson () const
Is this a Meson?
G4bool isBaryon () const
Is this a Baryon?
G4bool isStrange () const
Is this an Strange?
G4int getA () const
Returns the baryon number.
G4int getZ () const
Returns the charge number.
G4int getS () const
Returns the strangeness number.
G4double getBeta () const
ThreeVector boostVector () const
Returns a three vector we can give to the boost() -method.
void boost (const ThreeVector &aBoostVector)
Boost the particle using a boost vector.
void lorentzContract (const ThreeVector &aBoostVector, const ThreeVector &refPos)
Lorentz-contract the particle position around some center.
G4double getMass () const
Get the cached particle mass.
G4double getINCLMass () const
Get the INCL particle mass.
G4double getRealMass () const
Get the real particle mass.
void setRealMass ()
Set the mass of the Particle to its real mass.
void setTableMass ()
Set the mass of the Particle to its table mass.
void setINCLMass ()
Set the mass of the Particle to its table mass.
G4double getEmissionQValueCorrection (const G4int AParent, const G4int ZParent) const
Computes correction on the emission Q-value.
G4double getTransferQValueCorrection (const G4int AFrom, const G4int ZFrom, const G4int ATo, const G4int ZTo) const
Computes correction on the transfer Q-value.
G4double getEmissionQValueCorrection (const G4int AParent, const G4int ZParent, const G4int SParent) const
Computes correction on the emission Q-value for hypernuclei.
G4double getTransferQValueCorrection (const G4int AFrom, const G4int ZFrom, const G4int SFrom, const G4int ATo, const G4int ZTo, const G4int STo) const
Computes correction on the transfer Q-value for hypernuclei.
G4double getInvariantMass () const
Get the the particle invariant mass.
G4double getKineticEnergy () const
Get the particle kinetic energy.
G4double getPotentialEnergy () const
Get the particle potential energy.
void setPotentialEnergy (G4double v)
Set the particle potential energy.
G4double getEnergy () const
Get the energy of the particle in MeV.
void setMass (G4double mass)
Set the mass of the particle in MeV/c^2.
void setEnergy (G4double energy)
Set the energy of the particle in MeV.
const G4INCL::ThreeVector & getMomentum () const
Get the momentum vector.
virtual void setMomentum (const G4INCL::ThreeVector &momentum)
Set the momentum vector.
const G4INCL::ThreeVector & getPosition () const
Set the position vector.
G4double getHelicity ()
void setHelicity (G4double h)
void propagate (G4double step)
G4int getNumberOfCollisions () const
Return the number of collisions undergone by the particle.
void setNumberOfCollisions (G4int n)
Set the number of collisions undergone by the particle.
void incrementNumberOfCollisions ()
Increment the number of collisions undergone by the particle.
G4int getNumberOfDecays () const
Return the number of decays undergone by the particle.
void setNumberOfDecays (G4int n)
Set the number of decays undergone by the particle.
void incrementNumberOfDecays ()
Increment the number of decays undergone by the particle.
void setOutOfWell ()
Mark the particle as out of its potential well.
G4bool isOutOfWell () const
Check if the particle is out of its potential well.
void setEmissionTime (G4double t)
G4double getEmissionTime ()
ThreeVector getTransversePosition () const
Transverse component of the position w.r.t.
ThreeVector getLongitudinalPosition () const
Longitudinal component of the position w.r.t.
const ThreeVector & adjustMomentumFromEnergy ()
Rescale the momentum to match the total energy.
G4double adjustEnergyFromMomentum ()
Recompute the energy to match the momentum.
G4bool isCluster () const
void setFrozenMomentum (const ThreeVector &momentum)
Set the frozen particle momentum.
void setFrozenEnergy (const G4double energy)
Set the frozen particle momentum.
ThreeVector getFrozenMomentum () const
Get the frozen particle momentum.
G4double getFrozenEnergy () const
Get the frozen particle momentum.
ThreeVector getPropagationVelocity () const
Get the propagation velocity of the particle.
void freezePropagation ()
Freeze particle propagation.
void thawPropagation ()
Unfreeze particle propagation.
virtual void rotatePositionAndMomentum (const G4double angle, const ThreeVector &axis)
Rotate the particle position and momentum.
std::string print () const
std::string dump () const
long getID () const
const ParticleList * getParticles () const
Return a NULL pointer.
G4double getReflectionMomentum () const
Return the reflection momentum.
void setUncorrelatedMomentum (const G4double p)
Set the uncorrelated momentum.
void rpCorrelate ()
Make the particle follow a strict r-p correlation.
void rpDecorrelate ()
Make the particle not follow a strict r-p correlation.
G4double getCosRPAngle () const
Get the cosine of the angle between position and momentum.
G4double getParticleBias () const
Get the particle bias.
void setParticleBias (G4double ParticleBias)
Set the particle bias.
std::vector< G4int > getBiasCollisionVector () const
Get the vector list of biased vertices on the particle path.
void setBiasCollisionVector (std::vector< G4int > BiasCollisionVector)
Set the vector list of biased vertices on the particle path.
G4int getNumberOfKaon () const
Number of Kaon inside de nucleus.
void setNumberOfKaon (const G4int NK)
Private Member Functions
void computeOneNucleonRecoilKinematics ()
Compute the recoil kinematics for a 1-nucleon remnant.
Private Attributes
G4int theInitialZ
G4int theInitialA
G4int theInitialS
G4int theNpInitial
The number of entering protons.
G4int theNnInitial
The number of entering neutrons.
G4int theNpionplusInitial
The number of entering pions.
G4int theNpionminusInitial
G4int theNkaonplusInitial
The number of entering kaons.
G4int theNkaonminusInitial
G4double initialInternalEnergy
ThreeVector incomingAngularMomentum
ThreeVector incomingMomentum
ThreeVector initialCenterOfMass
G4bool remnant
G4double initialEnergy
Store * theStore
G4bool tryCN
G4int projectileZ
The charge number of the projectile.
G4int projectileA
The mass number of the projectile.
G4int projectileS
The strangeness number of the projectile.
G4double theUniverseRadius
The radius of the universe.
G4bool isNucleusNucleus
true if running a nucleus-nucleus collision
ProjectileRemnant * theProjectileRemnant
Pointer to the quasi-projectile.
const NuclearDensity * theDensity
Pointer to the NuclearDensity object.
const NuclearPotential::INuclearPotential * thePotential
Pointer to the NuclearPotential object.
Additional Inherited Members
Static Public Member Functions inherited from G4INCL::Particle
static G4double getTotalBias ()
General bias vector function.
static void setINCLBiasVector (std::vector< G4double > NewVector)
static void FillINCLBiasVector (G4double newBias)
static G4double getBiasFromVector (std::vector< G4int > VectorBias)
static std::vector< G4int > MergeVectorBias (Particle const *const p1, Particle const *const p2)
static std::vector< G4int > MergeVectorBias (std::vector< G4int > p1, Particle const *const p2)
Static Public Attributes inherited from G4INCL::Particle
static std::vector< G4double > INCLBiasVector
Time ordered vector of all bias applied.
static G4ThreadLocal G4int nextBiasedCollisionID = 0
Protected Member Functions inherited from G4INCL::Particle
void swap (Particle &rhs)
Helper method for the assignment operator.
Protected Attributes inherited from G4INCL::Cluster
ParticleList particles
G4double theExcitationEnergy
ThreeVector theSpin
ParticleSampler * theParticleSampler
Protected Attributes inherited from G4INCL::Particle
G4int theZ
G4int theA
G4int theS
ParticipantType theParticipantType
G4INCL::ParticleType theType
G4double theEnergy
G4double * thePropagationEnergy
G4double theFrozenEnergy
G4INCL::ThreeVector theMomentum
G4INCL::ThreeVector * thePropagationMomentum
G4INCL::ThreeVector theFrozenMomentum
G4INCL::ThreeVector thePosition
G4int nCollisions
G4int nDecays
G4double thePotentialEnergy
long ID
G4bool rpCorrelated
G4double uncorrelatedMomentum
G4double theParticleBias
G4int theNKaon
The number of Kaons inside the nucleus (update during the cascade)
Detailed Description
Definition at line 65 of file G4INCLNucleus.hh.
Constructor & Destructor Documentation
Nucleus() [1/2]
G4INCL::Nucleus::Nucleus (G4int mass, G4int charge, G4int strangess, Config const *const conf, const G4double universeRadius = -1.)
Definition at line 68 of file G4INCLNucleus.cc.
~Nucleus()
G4INCL::Nucleus::~Nucleus () virtual
Definition at line 112 of file G4INCLNucleus.cc.
Nucleus() [2/2]
G4INCL::Nucleus::Nucleus (const Nucleus & rhs)
Dummy copy constructor to silence Coverity warning.
Member Function Documentation
applyFinalState()
void G4INCL::Nucleus::applyFinalState (FinalState * finalstate)
Apply reaction final state information to the nucleus.
Definition at line 136 of file G4INCLNucleus.cc.
Referenced by G4INCL::INCL::cascade(), decayInsideDeltas(), decayInsideStrangeParticles(), and G4INCL::INCL::makeCompoundNucleus().
computeCenterOfMass()
ThreeVector G4INCL::Nucleus::computeCenterOfMass () const
Compute the current center-of-mass position.
Returns
the center-of-mass position vector [fm].
Definition at line 268 of file G4INCLNucleus.cc.
Referenced by computeRecoilKinematics().
computeExcitationEnergy()
G4double G4INCL::Nucleus::computeExcitationEnergy () const
Compute the current excitation energy.
Returns
the excitation energy [MeV]
Definition at line 281 of file G4INCLNucleus.cc.
Referenced by G4INCL::INCL::postCascade().
computeOneNucleonRecoilKinematics()
void G4INCL::Nucleus::computeOneNucleonRecoilKinematics () private
Compute the recoil kinematics for a 1-nucleon remnant.
Puts the remnant nucleon on mass shell and tries to enforce approximate energy conservation by modifying the masses of the outgoing particles.
Definition at line 853 of file G4INCLNucleus.cc.
Referenced by computeRecoilKinematics().
computeRecoilKinematics()
void G4INCL::Nucleus::computeRecoilKinematics ()
Compute the recoil momentum and spin of the nucleus.
Definition at line 235 of file G4INCLNucleus.cc.
Referenced by G4INCL::INCL::postCascade().
computeSeparationEnergyBalance()
G4double G4INCL::Nucleus::computeSeparationEnergyBalance () const inline
Outgoing - incoming separation energies.
Used by CDPP.
Definition at line 128 of file G4INCLNucleus.hh.
Referenced by computeExcitationEnergy(), and G4INCL::CDPP::isBlocked().
computeTotalEnergy()
G4double G4INCL::Nucleus::computeTotalEnergy () const
Compute the current total energy.
Returns
the total energy [MeV]
Definition at line 218 of file G4INCLNucleus.cc.
Referenced by computeExcitationEnergy(), and initializeParticles().
containsAntiKaon()
G4bool G4INCL::Nucleus::containsAntiKaon () inline
Returns true if the nucleus contains any anti Kaons.
Definition at line 295 of file G4INCLNucleus.hh.
Referenced by G4INCL::INCL::postCascade().
containsDeltas()
G4bool G4INCL::Nucleus::containsDeltas () inline
Returns true if the nucleus contains any deltas.
Definition at line 287 of file G4INCLNucleus.hh.
Referenced by G4INCL::INCL::postCascade().
containsEtas()
G4bool G4INCL::Nucleus::containsEtas () inline
Returns true if the nucleus contains any etas.
Definition at line 327 of file G4INCLNucleus.hh.
containsKaon()
G4bool G4INCL::Nucleus::containsKaon () inline
Returns true if the nucleus contains any Kaons.
Definition at line 319 of file G4INCLNucleus.hh.
Referenced by G4INCL::INCL::postCascade().
containsLambda()
G4bool G4INCL::Nucleus::containsLambda () inline
Returns true if the nucleus contains any Lambda.
Definition at line 303 of file G4INCLNucleus.hh.
Referenced by G4INCL::INCL::postCascade().
containsOmegas()
G4bool G4INCL::Nucleus::containsOmegas () inline
Returns true if the nucleus contains any omegas.
Definition at line 335 of file G4INCLNucleus.hh.
containsSigma()
G4bool G4INCL::Nucleus::containsSigma () inline
Returns true if the nucleus contains any Sigma.
Definition at line 311 of file G4INCLNucleus.hh.
Referenced by G4INCL::INCL::postCascade().
decayInsideDeltas()
G4bool G4INCL::Nucleus::decayInsideDeltas ()
Force the decay of deltas inside the nucleus.
Returns
true if any delta was forced to decay.
Definition at line 361 of file G4INCLNucleus.cc.
Referenced by G4INCL::INCL::postCascade().
decayInsideStrangeParticles()
G4bool G4INCL::Nucleus::decayInsideStrangeParticles ()
Force the transformation of strange particles into a Lambda;.
Returns
true if any strange particles was forced to absorb.
Definition at line 417 of file G4INCLNucleus.cc.
Referenced by G4INCL::INCL::postCascade().
decayMe()
G4bool G4INCL::Nucleus::decayMe ()
Force the phase-space decay of the Nucleus.
Only applied if Z==0 or N==0.
Returns
true if the nucleus was forced to decay.
Definition at line 656 of file G4INCLNucleus.cc.
Referenced by G4INCL::INCL::makeCompoundNucleus(), and G4INCL::INCL::postCascade().
decayOutgoingClusters()
G4bool G4INCL::Nucleus::decayOutgoingClusters ()
Force the decay of unstable outgoing clusters.
Returns
true if any cluster was forced to decay.
Definition at line 631 of file G4INCLNucleus.cc.
Referenced by G4INCL::INCL::makeCompoundNucleus(), and G4INCL::INCL::postCascade().
decayOutgoingDeltas()
G4bool G4INCL::Nucleus::decayOutgoingDeltas ()
Force the decay of outgoing deltas.
Returns
true if any delta was forced to decay.
Definition at line 308 of file G4INCLNucleus.cc.
Referenced by G4INCL::INCL::makeCompoundNucleus(), and G4INCL::INCL::postCascade().
decayOutgoingNeutralKaon()
G4bool G4INCL::Nucleus::decayOutgoingNeutralKaon ()
Force the transformation of outgoing Neutral Kaon into propation eigenstate.
Returns
true if any kaon was forced to decay.
Definition at line 608 of file G4INCLNucleus.cc.
Referenced by G4INCL::INCL::postCascade().
decayOutgoingPionResonances()
G4bool G4INCL::Nucleus::decayOutgoingPionResonances (G4double timeThreshold)
Force the decay of outgoing PionResonances (eta/omega).
Returns
true if any eta was forced to decay.
Definition at line 480 of file G4INCLNucleus.cc.
Referenced by G4INCL::INCL::makeCompoundNucleus(), and G4INCL::INCL::postCascade().
decayOutgoingSigmaZero()
G4bool G4INCL::Nucleus::decayOutgoingSigmaZero (G4double timeThreshold)
Force the decay of outgoing Neutral Sigma.
Returns
true if any Sigma was forced to decay.
Definition at line 551 of file G4INCLNucleus.cc.
Referenced by G4INCL::INCL::postCascade().
deleteProjectileRemnant()
void G4INCL::Nucleus::deleteProjectileRemnant () inline
Delete the projectile remnant.
Definition at line 442 of file G4INCLNucleus.hh.
Referenced by ~Nucleus().
emitInsideKaon()
G4bool G4INCL::Nucleus::emitInsideKaon ()
Force emission of all Kaon inside the nucleus.
Definition at line 796 of file G4INCLNucleus.cc.
Referenced by G4INCL::INCL::makeCompoundNucleus(), and G4INCL::INCL::postCascade().
emitInsideLambda()
G4int G4INCL::Nucleus::emitInsideLambda ()
Force emission of all Lambda (desexitation code with strangeness not implanted yet)
Definition at line 753 of file G4INCLNucleus.cc.
Referenced by G4INCL::INCL::postCascade().
emitInsidePions()
void G4INCL::Nucleus::emitInsidePions ()
Force emission of all pions inside the nucleus.
Definition at line 670 of file G4INCLNucleus.cc.
Referenced by computeRecoilKinematics(), and decayInsideDeltas().
emitInsideStrangeParticles()
void G4INCL::Nucleus::emitInsideStrangeParticles ()
Force emission of all strange particles inside the nucleus.
Definition at line 710 of file G4INCLNucleus.cc.
Referenced by decayInsideStrangeParticles(), and G4INCL::INCL::postCascade().
fillEventInfo()
void G4INCL::Nucleus::fillEventInfo (EventInfo * eventInfo)
Fill the event info which contains INCL output data.
Definition at line 1010 of file G4INCLNucleus.cc.
Referenced by G4INCL::INCL::makeCompoundNucleus(), and G4INCL::INCL::postCascade().
finalizeProjectileRemnant()
void G4INCL::Nucleus::finalizeProjectileRemnant (const G4double emissionTime)
Finalise the projectile remnant.
Complete the treatment of the projectile remnant. If it contains nucleons, assign its excitation energy and spin. Move stuff to the outgoing list, if appropriate.
Parameters
emissionTime the emission time of the projectile remnant
Definition at line 1211 of file G4INCLNucleus.cc.
Referenced by G4INCL::INCL::makeCompoundNucleus(), and G4INCL::INCL::makeProjectileRemnant().
getConservationBalance()
Nucleus::ConservationBalance G4INCL::Nucleus::getConservationBalance (EventInfo const & theEventInfo, const G4bool afterRecoil) const
Compute charge, mass, energy and momentum balance.
Definition at line 1155 of file G4INCLNucleus.cc.
Referenced by G4INCL::INCL::RecoilFunctor::operator()(), and G4INCL::INCL::RecoilCMFunctor::operator()().
getDensity()
const NuclearDensity* G4INCL::Nucleus::getDensity () const inline
Getter for theDensity.
Definition at line 470 of file G4INCLNucleus.hh.
Referenced by G4INCL::CoulombNonRelativistic::distortOut(), G4INCL::ClusteringModelIntercomparison::findClusterStartingFrom(), and G4INCL::ClusteringModelIntercomparison::getCluster().
getExcitationEnergy()
G4double G4INCL::Nucleus::getExcitationEnergy () const inline
Get the excitation energy of the nucleus.
Method computeRecoilKinematics() should be called first.
Definition at line 284 of file G4INCLNucleus.hh.
Referenced by fillEventInfo(), getConservationBalance(), G4INCL::INCL::postCascade(), G4INCL::INCL::RecoilCMFunctor::scaleParticleCMMomenta(), and G4INCL::INCL::RecoilFunctor::scaleParticleEnergies().
getIncomingAngularMomentum()
const ThreeVector& G4INCL::Nucleus::getIncomingAngularMomentum () const inline
Get the incoming angular-momentum vector.
Definition at line 262 of file G4INCLNucleus.hh.
Referenced by G4INCL::INCL::makeCompoundNucleus().
getIncomingMomentum()
const ThreeVector& G4INCL::Nucleus::getIncomingMomentum () const inline
Get the incoming momentum vector.
Definition at line 270 of file G4INCLNucleus.hh.
Referenced by getConservationBalance(), G4INCL::INCL::makeCompoundNucleus(), G4INCL::INCL::RecoilCMFunctor::RecoilCMFunctor(), and G4INCL::INCL::RecoilFunctor::scaleParticleEnergies().
getInitialA()
G4int G4INCL::Nucleus::getInitialA () const inline
Definition at line 108 of file G4INCLNucleus.hh.
getInitialEnergy()
G4double G4INCL::Nucleus::getInitialEnergy () const inline
Get the initial energy.
Definition at line 278 of file G4INCLNucleus.hh.
Referenced by getConservationBalance(), and G4INCL::INCL::RecoilCMFunctor::RecoilCMFunctor().
getInitialInternalEnergy()
G4double G4INCL::Nucleus::getInitialInternalEnergy () const inline
Definition at line 353 of file G4INCLNucleus.hh.
Referenced by G4INCL::CDPP::isBlocked().
getInitialS()
G4int G4INCL::Nucleus::getInitialS () const inline
Definition at line 110 of file G4INCLNucleus.hh.
getInitialZ()
G4int G4INCL::Nucleus::getInitialZ () const inline
Definition at line 109 of file G4INCLNucleus.hh.
getNumberOfEnteringKaons()
G4int G4INCL::Nucleus::getNumberOfEnteringKaons () const inline
Definition at line 122 of file G4INCLNucleus.hh.
getNumberOfEnteringNeutrons()
G4int G4INCL::Nucleus::getNumberOfEnteringNeutrons () const inline
Definition at line 120 of file G4INCLNucleus.hh.
getNumberOfEnteringPions()
G4int G4INCL::Nucleus::getNumberOfEnteringPions () const inline
Definition at line 121 of file G4INCLNucleus.hh.
getNumberOfEnteringProtons()
G4int G4INCL::Nucleus::getNumberOfEnteringProtons () const inline
Definition at line 119 of file G4INCLNucleus.hh.
getPotential()
const NuclearPotential::INuclearPotential* G4INCL::Nucleus::getPotential () const inline
Getter for thePotential.
Definition at line 473 of file G4INCLNucleus.hh.
Referenced by G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::PauliStandard::getBlockingProbability(), G4INCL::SurfaceAvatar::getChannel(), G4INCL::CDPP::isBlocked(), and G4INCL::ParticleEntryChannel::particleEnters().
getProjectileRemnant()
ProjectileRemnant* G4INCL::Nucleus::getProjectileRemnant () const inline
Get the projectile remnant.
Definition at line 439 of file G4INCLNucleus.hh.
Referenced by G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::INCL::makeCompoundNucleus(), G4INCL::INCL::makeProjectileRemnant(), and G4INCL::INCL::postCascade().
getStore()
Store* G4INCL::Nucleus::getStore () const inline
Definition at line 347 of file G4INCLNucleus.hh.
Referenced by G4INCL::AvatarDumpAction::afterAvatarUserAction(), G4INCL::INCL::continueCascade(), G4INCL::InteractionAvatar::enforceEnergyConservation(), fillEventInfo(), G4INCL::StandardPropagationModel::generateAllAvatars(), G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar(), G4INCL::PauliStandard::getBlockingProbability(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::SurfaceAvatar::getChannel(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::SurfaceAvatar::getTransmissionProbability(), G4INCL::INCL::initializeTarget(), G4INCL::CDPP::isBlocked(), G4INCL::PauliStrictStandard::isBlocked(), G4INCL::INCL::makeCompoundNucleus(), G4INCL::INCL::makeProjectileRemnant(), G4INCL::INCL::postCascade(), G4INCL::DecayAvatar::postInteraction(), G4INCL::BinaryCollisionAvatar::postInteraction(), G4INCL::SurfaceAvatar::postInteraction(), G4INCL::InteractionAvatar::postInteraction(), G4INCL::StandardPropagationModel::propagate(), G4INCL::StandardPropagationModel::registerAvatar(), G4INCL::StandardPropagationModel::shootComposite(), G4INCL::StandardPropagationModel::shootParticle(), G4INCL::InteractionAvatar::shouldUseLocalEnergy(), and G4INCL::StandardPropagationModel::updateAvatars().
getSurfaceRadius()
G4double G4INCL::Nucleus::getSurfaceRadius (Particle const *const particle) const inline
Get the maximum allowed radius for a given particle.
Calls the NuclearDensity::getMaxRFromP() method for nucleons and deltas, and the NuclearDensity::getTrasmissionRadius() method for pions.
Parameters
particle pointer to a particle
Returns
surface radius
Definition at line 402 of file G4INCLNucleus.hh.
Referenced by G4INCL::InteractionAvatar::bringParticleInside(), G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar(), G4INCL::StandardPropagationModel::getReflectionTime(), and G4INCL::InteractionAvatar::postInteraction().
getTransmissionBarrier()
G4double G4INCL::Nucleus::getTransmissionBarrier (Particle const *const p) inline
Get the transmission barrier.
Definition at line 375 of file G4INCLNucleus.hh.
Referenced by G4INCL::SurfaceAvatar::getTransmissionProbability(), and G4INCL::InteractionAvatar::postInteraction().
getTryCompoundNucleus()
G4bool G4INCL::Nucleus::getTryCompoundNucleus () inline
Definition at line 372 of file G4INCLNucleus.hh.
Referenced by G4INCL::INCL::continueCascade(), G4INCL::INCL::postCascade(), and G4INCL::INCL::updateGlobalInfo().
getUniverseRadius()
G4double G4INCL::Nucleus::getUniverseRadius () const inline
Getter for theUniverseRadius.
Definition at line 418 of file G4INCLNucleus.hh.
Referenced by G4INCL::PauliStandard::getBlockingProbability(), G4INCL::ClusteringModelIntercomparison::getCluster(), getSurfaceRadius(), G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
hasRemnant()
G4bool G4INCL::Nucleus::hasRemnant () const inline
Does the nucleus give a cascade remnant?
To be called after computeRecoilKinematics().
Definition at line 365 of file G4INCLNucleus.hh.
Referenced by fillEventInfo(), getConservationBalance(), and G4INCL::INCL::postCascade().
initializeParticles()
void G4INCL::Nucleus::initializeParticles () virtual
Call the Cluster method to generate the initial distribution of particles.
At the beginning all particles are assigned as spectators.
Reimplemented from G4INCL::Cluster.
Definition at line 121 of file G4INCLNucleus.cc.
Referenced by G4INCL::INCL::initializeTarget().
insertParticle()
void G4INCL::Nucleus::insertParticle (Particle * p) inline
Insert a new particle (e.g. a projectile) in the nucleus.
Definition at line 83 of file G4INCLNucleus.hh.
Referenced by applyFinalState().
isEventTransparent()
G4bool G4INCL::Nucleus::isEventTransparent () const
Is the event transparent?
To be called at the end of the cascade.
Definition at line 840 of file G4INCLNucleus.cc.
Referenced by G4INCL::INCL::postCascade().
isNucleusNucleusCollision()
G4bool G4INCL::Nucleus::isNucleusNucleusCollision () const inline
Is it a nucleus-nucleus collision?
Definition at line 424 of file G4INCLNucleus.hh.
Referenced by G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::SurfaceAvatar::getChannel(), and G4INCL::INCL::makeCompoundNucleus().
operator=()
Nucleus& G4INCL::Nucleus::operator= (const Nucleus & rhs)
Dummy assignment operator to silence Coverity warning.
print()
std::string G4INCL::Nucleus::print ()
Print the nucleus info.
Definition at line 288 of file G4INCLNucleus.cc.
propagateParticles()
void G4INCL::Nucleus::propagateParticles (G4double step)
Propagate the particles one time step.
Parameters
step length of the time step
Definition at line 214 of file G4INCLNucleus.cc.
setDensity()
void G4INCL::Nucleus::setDensity (NuclearDensity const *const d) inline
Setter for theDensity.
Definition at line 463 of file G4INCLNucleus.hh.
setIncomingAngularMomentum()
void G4INCL::Nucleus::setIncomingAngularMomentum (const ThreeVector & j) inline
Set the incoming angular-momentum vector.
Definition at line 257 of file G4INCLNucleus.hh.
Referenced by G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
setIncomingMomentum()
void G4INCL::Nucleus::setIncomingMomentum (const ThreeVector & p) inline
Set the incoming momentum vector.
Definition at line 265 of file G4INCLNucleus.hh.
Referenced by G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
setInitialEnergy()
void G4INCL::Nucleus::setInitialEnergy (const G4double e) inline
Set the initial energy.
Definition at line 275 of file G4INCLNucleus.hh.
Referenced by G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
setNucleusNucleusCollision()
void G4INCL::Nucleus::setNucleusNucleusCollision () inline
Set a nucleus-nucleus collision.
Definition at line 427 of file G4INCLNucleus.hh.
Referenced by G4INCL::StandardPropagationModel::shootComposite().
setParticleNucleusCollision()
void G4INCL::Nucleus::setParticleNucleusCollision () inline
Set a particle-nucleus collision.
Definition at line 430 of file G4INCLNucleus.hh.
Referenced by G4INCL::StandardPropagationModel::shootParticle().
setProjectileRemnant()
void G4INCL::Nucleus::setProjectileRemnant (ProjectileRemnant *const c) inline
Set the projectile remnant.
Definition at line 433 of file G4INCLNucleus.hh.
Referenced by G4INCL::StandardPropagationModel::shootComposite().
setStore()
void G4INCL::Nucleus::setStore (Store * s) inline
Definition at line 348 of file G4INCLNucleus.hh.
setUniverseRadius()
void G4INCL::Nucleus::setUniverseRadius (const G4double universeRadius) inline
Setter for theUniverseRadius.
Definition at line 421 of file G4INCLNucleus.hh.
updatePotentialEnergy()
void G4INCL::Nucleus::updatePotentialEnergy (Particle * p) const inline
Update the particle potential energy.
Definition at line 458 of file G4INCLNucleus.hh.
Referenced by G4INCL::ReflectionChannel::fillFinalState(), initializeParticles(), G4INCL::InteractionAvatar::ViolationEMomentumFunctor::scaleParticleMomenta(), and G4INCL::InteractionAvatar::ViolationEEnergyFunctor::setParticleEnergy().
useFusionKinematics()
void G4INCL::Nucleus::useFusionKinematics ()
Adjust the kinematics for complete-fusion events.
Definition at line 1203 of file G4INCLNucleus.cc.
Referenced by G4INCL::INCL::postCascade().
Field Documentation
incomingAngularMomentum
ThreeVector G4INCL::Nucleus::incomingAngularMomentum private
Definition at line 497 of file G4INCLNucleus.hh.
Referenced by computeRecoilKinematics(), getIncomingAngularMomentum(), setIncomingAngularMomentum(), and useFusionKinematics().
incomingMomentum
ThreeVector G4INCL::Nucleus::incomingMomentum private
Definition at line 497 of file G4INCLNucleus.hh.
Referenced by computeOneNucleonRecoilKinematics(), computeRecoilKinematics(), getIncomingMomentum(), setIncomingMomentum(), and useFusionKinematics().
initialCenterOfMass
ThreeVector G4INCL::Nucleus::initialCenterOfMass private
Definition at line 498 of file G4INCLNucleus.hh.
Referenced by computeRecoilKinematics(), and initializeParticles().
initialEnergy
G4double G4INCL::Nucleus::initialEnergy private
Definition at line 501 of file G4INCLNucleus.hh.
Referenced by computeOneNucleonRecoilKinematics(), getInitialEnergy(), setInitialEnergy(), and useFusionKinematics().
initialInternalEnergy
G4double G4INCL::Nucleus::initialInternalEnergy private
Definition at line 496 of file G4INCLNucleus.hh.
Referenced by computeExcitationEnergy(), getInitialInternalEnergy(), and initializeParticles().
isNucleusNucleus
G4bool G4INCL::Nucleus::isNucleusNucleus private
true if running a nucleus-nucleus collision
Tells INCL whether to make a projectile-like pre-fragment or not.
Definition at line 519 of file G4INCLNucleus.hh.
Referenced by isNucleusNucleusCollision(), setNucleusNucleusCollision(), and setParticleNucleusCollision().
projectileA
G4int G4INCL::Nucleus::projectileA private
The mass number of the projectile.
Definition at line 508 of file G4INCLNucleus.hh.
projectileS
G4int G4INCL::Nucleus::projectileS private
The strangeness number of the projectile.
Definition at line 510 of file G4INCLNucleus.hh.
projectileZ
G4int G4INCL::Nucleus::projectileZ private
The charge number of the projectile.
Definition at line 506 of file G4INCLNucleus.hh.
remnant
G4bool G4INCL::Nucleus::remnant private
Definition at line 499 of file G4INCLNucleus.hh.
Referenced by computeRecoilKinematics(), and hasRemnant().
theDensity
const NuclearDensity* G4INCL::Nucleus::theDensity private
Pointer to the NuclearDensity object.
Definition at line 528 of file G4INCLNucleus.hh.
Referenced by getDensity(), getSurfaceRadius(), getTransmissionBarrier(), Nucleus(), and setDensity().
theInitialA
G4int G4INCL::Nucleus::theInitialA private
Definition at line 484 of file G4INCLNucleus.hh.
Referenced by getInitialA().
theInitialS
G4int G4INCL::Nucleus::theInitialS private
Definition at line 484 of file G4INCLNucleus.hh.
Referenced by getInitialS().
theInitialZ
G4int G4INCL::Nucleus::theInitialZ private
Definition at line 484 of file G4INCLNucleus.hh.
Referenced by getInitialZ().
theNkaonminusInitial
G4int G4INCL::Nucleus::theNkaonminusInitial private
Definition at line 494 of file G4INCLNucleus.hh.
Referenced by computeSeparationEnergyBalance(), getNumberOfEnteringKaons(), and insertParticle().
theNkaonplusInitial
G4int G4INCL::Nucleus::theNkaonplusInitial private
The number of entering kaons.
Definition at line 493 of file G4INCLNucleus.hh.
Referenced by computeSeparationEnergyBalance(), getNumberOfEnteringKaons(), and insertParticle().
theNnInitial
G4int G4INCL::Nucleus::theNnInitial private
The number of entering neutrons.
Definition at line 488 of file G4INCLNucleus.hh.
Referenced by computeSeparationEnergyBalance(), getNumberOfEnteringNeutrons(), and insertParticle().
theNpInitial
G4int G4INCL::Nucleus::theNpInitial private
The number of entering protons.
Definition at line 486 of file G4INCLNucleus.hh.
Referenced by computeSeparationEnergyBalance(), getNumberOfEnteringProtons(), and insertParticle().
theNpionminusInitial
G4int G4INCL::Nucleus::theNpionminusInitial private
Definition at line 491 of file G4INCLNucleus.hh.
Referenced by computeSeparationEnergyBalance(), getNumberOfEnteringPions(), and insertParticle().
theNpionplusInitial
G4int G4INCL::Nucleus::theNpionplusInitial private
The number of entering pions.
Definition at line 490 of file G4INCLNucleus.hh.
Referenced by computeSeparationEnergyBalance(), getNumberOfEnteringPions(), and insertParticle().
thePotential
const NuclearPotential::INuclearPotential* G4INCL::Nucleus::thePotential private
Pointer to the NuclearPotential object.
Definition at line 531 of file G4INCLNucleus.hh.
Referenced by computeSeparationEnergyBalance(), decayInsideDeltas(), getPotential(), getSurfaceRadius(), Nucleus(), and updatePotentialEnergy().
theProjectileRemnant
ProjectileRemnant* G4INCL::Nucleus::theProjectileRemnant private
Pointer to the quasi-projectile.
Owned by the Nucleus object.
Definition at line 525 of file G4INCLNucleus.hh.
Referenced by computeRecoilKinematics(), deleteProjectileRemnant(), fillEventInfo(), finalizeProjectileRemnant(), getConservationBalance(), getProjectileRemnant(), initializeParticles(), and setProjectileRemnant().
theStore
Store* G4INCL::Nucleus::theStore private
Definition at line 502 of file G4INCLNucleus.hh.
Referenced by applyFinalState(), computeCenterOfMass(), computeOneNucleonRecoilKinematics(), computeRecoilKinematics(), computeSeparationEnergyBalance(), computeTotalEnergy(), containsAntiKaon(), containsDeltas(), containsEtas(), containsKaon(), containsLambda(), containsOmegas(), containsSigma(), decayInsideDeltas(), decayInsideStrangeParticles(), decayMe(), decayOutgoingClusters(), decayOutgoingDeltas(), decayOutgoingNeutralKaon(), decayOutgoingPionResonances(), decayOutgoingSigmaZero(), emitInsideKaon(), emitInsideLambda(), emitInsidePions(), emitInsideStrangeParticles(), fillEventInfo(), getConservationBalance(), getStore(), initializeParticles(), insertParticle(), isEventTransparent(), Nucleus(), print(), setStore(), and ~Nucleus().
theUniverseRadius
G4double G4INCL::Nucleus::theUniverseRadius private
The radius of the universe.
Definition at line 513 of file G4INCLNucleus.hh.
Referenced by getUniverseRadius(), Nucleus(), and setUniverseRadius().
tryCN
G4bool G4INCL::Nucleus::tryCN private
Definition at line 503 of file G4INCLNucleus.hh.
Referenced by applyFinalState(), fillEventInfo(), and getTryCompoundNucleus().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNucleus.hh
source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLNucleus.cc