Geant4: DicomFileMgr Class Reference
DicomFileMgr Class Reference
#include <DicomFileMgr.hh>
Public Member Functions
~DicomFileMgr ()
std::vector< DicomFileStructure * > GetStructFiles () const
void SetCompression (G4String fComp)
void AddFile (G4String fComp)
void AddMaterial (std::vector< G4String > data)
void AddMaterialDensity (std::vector< G4String > data)
void AddCT2Density (std::vector< G4String > data)
void Convert (G4String fFileName)
void CheckNColumns (std::vector< G4String > wl, size_t vsizeTh)
void ProcessFiles ()
void CheckCTSlices ()
G4double Hounsfield2density (Uint32 Hval)
size_t GetMaterialIndex (G4double Hval)
size_t GetMaterialIndexByDensity (G4double density)
void BuildCTMaterials ()
void MergeCTFiles ()
void CheckPETSlices ()
void BuildPETActivities ()
void MergePETFiles ()
void DumpToTextFile ()
void SetStructureNCheck (G4int nsc)
G4int GetStructureNCheck () const
void SetStructureNMaxROI (G4int nsc)
G4int GetStructureNMaxROI () const
G4int GetCompression () const
G4String GetFileOutName () const
void SetControlPointMetersets ()
G4bool IsMaterialsDensity () const
Static Public Member Functions
static DicomFileMgr * GetInstance ()
Data Fields
G4bool bMaterialsDensity
Static Public Attributes
static int verbose = 1
Protected Attributes
G4int fCompression
Private Member Functions
DicomFileMgr ()
Private Attributes
G4String theFileOutName
mdct theCTFiles
std::vector< DicomFileStructure * > theStructFiles
std::vector< DicomFilePlan * > thePlanFiles
mdpet thePETFiles
std::map< G4double, G4String > theMaterials
std::map< G4double, G4String > theMaterialsDensity
std::map< G4int, G4double > theCT2Density
DicomFileCT * theCTFileAll
DicomFilePET * thePETFileAll
G4int theStructureNCheck
G4int theStructureNMaxROI
Static Private Attributes
static DicomFileMgr * theInstance = 0
Detailed Description
Definition at line 46 of file DicomFileMgr.hh.
Constructor & Destructor Documentation
~DicomFileMgr()
DicomFileMgr::~DicomFileMgr () inline
Definition at line 50 of file DicomFileMgr.hh.
DicomFileMgr()
DicomFileMgr::DicomFileMgr () private
Definition at line 50 of file DicomFileMgr.cc.
Referenced by GetInstance().
Member Function Documentation
AddCT2Density()
void DicomFileMgr::AddCT2Density (std::vector< G4String > data)
Definition at line 209 of file DicomFileMgr.cc.
Referenced by Convert().
AddFile()
void DicomFileMgr::AddFile (G4String fComp)
Definition at line 128 of file DicomFileMgr.cc.
Referenced by Convert().
AddMaterial()
void DicomFileMgr::AddMaterial (std::vector< G4String > data)
Definition at line 183 of file DicomFileMgr.cc.
Referenced by Convert().
AddMaterialDensity()
void DicomFileMgr::AddMaterialDensity (std::vector< G4String > data)
Definition at line 196 of file DicomFileMgr.cc.
Referenced by Convert().
BuildCTMaterials()
void DicomFileMgr::BuildCTMaterials ()
Definition at line 507 of file DicomFileMgr.cc.
Referenced by ProcessFiles().
BuildPETActivities()
void DicomFileMgr::BuildPETActivities ()
Definition at line 517 of file DicomFileMgr.cc.
Referenced by ProcessFiles().
CheckCTSlices()
void DicomFileMgr::CheckCTSlices ()
Definition at line 344 of file DicomFileMgr.cc.
Referenced by ProcessFiles().
CheckNColumns()
void DicomFileMgr::CheckNColumns (std::vector< G4String > wl, size_t vsizeTh)
Definition at line 103 of file DicomFileMgr.cc.
Referenced by Convert().
CheckPETSlices()
void DicomFileMgr::CheckPETSlices ()
Definition at line 425 of file DicomFileMgr.cc.
Referenced by ProcessFiles().
Convert()
void DicomFileMgr::Convert (G4String fFileName)
Definition at line 59 of file DicomFileMgr.cc.
Referenced by main().
DumpToTextFile()
void DicomFileMgr::DumpToTextFile ()
Definition at line 553 of file DicomFileMgr.cc.
Referenced by ProcessFiles().
GetCompression()
G4int DicomFileMgr::GetCompression () const inline
Definition at line 91 of file DicomFileMgr.hh.
Referenced by DicomFilePET::BuildActivities(), DicomFileCT::BuildMaterials(), DicomFileCT::BuildStructureIDs(), DicomFilePET::DumpActivitiesToTextFile(), DicomFileCT::DumpDensitiesToTextFile(), DicomVFileImage::DumpHeaderToTextFile(), DicomFileCT::DumpMateIDsToTextFile(), DicomFileCT::DumpStructureIDsToTextFile(), and DicomVFileImage::Print().
GetFileOutName()
G4String DicomFileMgr::GetFileOutName () const inline
Definition at line 94 of file DicomFileMgr.hh.
Referenced by DicomDetectorConstruction::ReadPhantomDataNew().
GetInstance()
DicomFileMgr * DicomFileMgr::GetInstance (void) static
Definition at line 41 of file DicomFileMgr.cc.
Referenced by DicomFileCT::BuildStructureIDs(), DicomVFileImage::DicomVFileImage(), main(), and DicomDetectorConstruction::ReadPhantomDataNew().
GetMaterialIndex()
size_t DicomFileMgr::GetMaterialIndex (G4double Hval)
Definition at line 272 of file DicomFileMgr.cc.
Referenced by DicomFileCT::BuildMaterials().
GetMaterialIndexByDensity()
size_t DicomFileMgr::GetMaterialIndexByDensity (G4double density)
Definition at line 292 of file DicomFileMgr.cc.
Referenced by DicomFileCT::BuildMaterials().
GetStructFiles()
std::vector<DicomFileStructure*> DicomFileMgr::GetStructFiles () const inline
Definition at line 56 of file DicomFileMgr.hh.
Referenced by DicomFileCT::BuildStructureIDs(), DicomFileCT::DumpStructureIDsToTextFile(), and DumpToTextFile().
GetStructureNCheck()
G4int DicomFileMgr::GetStructureNCheck () const inline
Definition at line 82 of file DicomFileMgr.hh.
Referenced by DicomFileCT::BuildStructureIDs().
GetStructureNMaxROI()
G4int DicomFileMgr::GetStructureNMaxROI () const inline
Definition at line 88 of file DicomFileMgr.hh.
Referenced by DicomFileCT::BuildStructureIDs().
Hounsfield2density()
G4double DicomFileMgr::Hounsfield2density (Uint32 Hval)
Definition at line 217 of file DicomFileMgr.cc.
Referenced by DicomFileCT::BuildMaterials().
IsMaterialsDensity()
G4bool DicomFileMgr::IsMaterialsDensity () const inline
Definition at line 99 of file DicomFileMgr.hh.
Referenced by DicomFileCT::BuildMaterials().
MergeCTFiles()
void DicomFileMgr::MergeCTFiles ()
Definition at line 527 of file DicomFileMgr.cc.
Referenced by ProcessFiles().
MergePETFiles()
void DicomFileMgr::MergePETFiles ()
Definition at line 540 of file DicomFileMgr.cc.
Referenced by ProcessFiles().
ProcessFiles()
void DicomFileMgr::ProcessFiles ()
Definition at line 311 of file DicomFileMgr.cc.
Referenced by Convert().
SetCompression()
void DicomFileMgr::SetCompression (G4String fComp)
Definition at line 122 of file DicomFileMgr.cc.
Referenced by Convert().
SetControlPointMetersets()
void DicomFileMgr::SetControlPointMetersets ()
SetStructureNCheck()
void DicomFileMgr::SetStructureNCheck (G4int nsc) inline
Definition at line 79 of file DicomFileMgr.hh.
SetStructureNMaxROI()
void DicomFileMgr::SetStructureNMaxROI (G4int nsc) inline
Definition at line 85 of file DicomFileMgr.hh.
Field Documentation
bMaterialsDensity
G4bool DicomFileMgr::bMaterialsDensity
Definition at line 126 of file DicomFileMgr.hh.
Referenced by AddMaterial(), AddMaterialDensity(), DumpToTextFile(), and IsMaterialsDensity().
fCompression
G4int DicomFileMgr::fCompression protected
Definition at line 104 of file DicomFileMgr.hh.
Referenced by DicomFileMgr(), GetCompression(), and SetCompression().
theCT2Density
std::map<G4int,G4double> DicomFileMgr::theCT2Density private
Definition at line 117 of file DicomFileMgr.hh.
Referenced by AddCT2Density(), and Hounsfield2density().
theCTFileAll
DicomFileCT* DicomFileMgr::theCTFileAll private
Definition at line 119 of file DicomFileMgr.hh.
Referenced by DicomFileMgr(), DumpToTextFile(), and MergeCTFiles().
theCTFiles
mdct DicomFileMgr::theCTFiles private
Definition at line 111 of file DicomFileMgr.hh.
Referenced by AddFile(), BuildCTMaterials(), CheckCTSlices(), DumpToTextFile(), MergeCTFiles(), and ProcessFiles().
theFileOutName
G4String DicomFileMgr::theFileOutName private
Definition at line 109 of file DicomFileMgr.hh.
Referenced by Convert(), DumpToTextFile(), and GetFileOutName().
theInstance
DicomFileMgr * DicomFileMgr::theInstance = 0 static private
Definition at line 107 of file DicomFileMgr.hh.
Referenced by GetInstance().
theMaterials
std::map<G4double,G4String> DicomFileMgr::theMaterials private
Definition at line 115 of file DicomFileMgr.hh.
Referenced by AddMaterial(), DumpToTextFile(), and GetMaterialIndex().
theMaterialsDensity
std::map<G4double,G4String> DicomFileMgr::theMaterialsDensity private
Definition at line 116 of file DicomFileMgr.hh.
Referenced by AddMaterialDensity(), DumpToTextFile(), and GetMaterialIndexByDensity().
thePETFileAll
DicomFilePET* DicomFileMgr::thePETFileAll private
Definition at line 120 of file DicomFileMgr.hh.
Referenced by DumpToTextFile(), and MergePETFiles().
thePETFiles
mdpet DicomFileMgr::thePETFiles private
Definition at line 114 of file DicomFileMgr.hh.
Referenced by AddFile(), BuildPETActivities(), CheckPETSlices(), DumpToTextFile(), MergePETFiles(), and ProcessFiles().
thePlanFiles
std::vector<DicomFilePlan*> DicomFileMgr::thePlanFiles private
Definition at line 113 of file DicomFileMgr.hh.
Referenced by AddFile(), and DumpToTextFile().
theStructFiles
std::vector<DicomFileStructure*> DicomFileMgr::theStructFiles private
Definition at line 112 of file DicomFileMgr.hh.
Referenced by AddFile(), and GetStructFiles().
theStructureNCheck
G4int DicomFileMgr::theStructureNCheck private
Definition at line 121 of file DicomFileMgr.hh.
Referenced by DicomFileMgr(), GetStructureNCheck(), and SetStructureNCheck().
theStructureNMaxROI
G4int DicomFileMgr::theStructureNMaxROI private
Definition at line 122 of file DicomFileMgr.hh.
Referenced by DicomFileMgr(), GetStructureNMaxROI(), and SetStructureNMaxROI().
verbose
int DicomFileMgr::verbose = 1 static
Definition at line 125 of file DicomFileMgr.hh.
Referenced by DicomFileCT::BuildStructureIDs(), DicomFilePET::DumpActivitiesToTextFile(), DicomFileCT::DumpDensitiesToTextFile(), DicomVFileImage::DumpHeaderToTextFile(), DicomFileCT::DumpMateIDsToTextFile(), DicomFileCT::DumpStructureIDsToTextFile(), DicomVFileImage::ReadData(), and DicomVFileImage::ReadPixelData().
The documentation for this class was generated from the following files:
examples/extended/medical/DICOM/dicomReader/include/DicomFileMgr.hh
examples/extended/medical/DICOM/dicomReader/src/DicomFileMgr.cc