Geant4: source/processes/electromagnetic/highenergy/src/G4GammaConversionToMuons.cc File Reference
G4GammaConversionToMuons.cc File Reference
#include "G4GammaConversionToMuons.hh"
#include "G4PhysicalConstants.hh"
#include "G4SystemOfUnits.hh"
#include "G4UnitsTable.hh"
#include "G4MuonPlus.hh"
#include "G4MuonMinus.hh"
#include "G4EmProcessSubType.hh"
#include "G4NistManager.hh"
#include "G4Log.hh"
#include "G4Exp.hh"
Variables
static const G4double sqrte =sqrt(exp(1.))
static const G4double PowSat =-0.88
Variable Documentation
PowSat
const G4double PowSat =-0.88 static
Definition at line 52 of file G4GammaConversionToMuons.cc.
Referenced by G4GammaConversionToMuons::ComputeCrossSectionPerAtom().
sqrte
const G4double sqrte =sqrt(exp(1.)) static
Definition at line 51 of file G4GammaConversionToMuons.cc.
Referenced by G4GammaConversionToMuons::ComputeCrossSectionPerAtom(), MuCrossSections::CRB_Mephi(), MuCrossSections::CRP_Mephi(), and G4GammaConversionToMuons::PostStepDoIt().