Geant4: G4FissionParameters Class Reference
G4FissionParameters Class Reference
#include <G4FissionParameters.hh>
Public Member Functions
G4FissionParameters ()
~G4FissionParameters ()
void DefineParameters (G4int A, G4int Z, G4double ExEnergy, G4double FissionBarrier)
G4int GetA1 (void) const
G4int GetA2 (void) const
G4double GetAs (void) const
G4double GetSigma1 (void) const
G4double GetSigma2 (void) const
G4double GetSigmaS (void) const
G4double GetW (void) const
Private Member Functions
G4FissionParameters (const G4FissionParameters &right)
const G4FissionParameters & operator= (const G4FissionParameters &right)
G4bool operator== (const G4FissionParameters &right) const
G4bool operator!= (const G4FissionParameters &right) const
Private Attributes
G4int A1
G4int A2
G4double A3
G4double As
G4double Sigma1
G4double Sigma2
G4double SigmaS
G4double w
Detailed Description
Definition at line 37 of file G4FissionParameters.hh.
Constructor & Destructor Documentation
G4FissionParameters() [1/2]
G4FissionParameters::G4FissionParameters ()
Definition at line 38 of file G4FissionParameters.cc.
~G4FissionParameters()
G4FissionParameters::~G4FissionParameters ()
Definition at line 43 of file G4FissionParameters.cc.
G4FissionParameters() [2/2]
G4FissionParameters::G4FissionParameters (const G4FissionParameters & right) private
Member Function Documentation
DefineParameters()
void G4FissionParameters::DefineParameters (G4int A, G4int Z, G4double ExEnergy, G4double FissionBarrier)
Definition at line 46 of file G4FissionParameters.cc.
Referenced by G4CompetitiveFission::EmittedFragment().
GetA1()
G4int G4FissionParameters::GetA1 (void) const inline
Definition at line 50 of file G4FissionParameters.hh.
Referenced by G4CompetitiveFission::FissionAtomicNumber(), G4CompetitiveFission::FissionKineticEnergy(), and G4CompetitiveFission::MassDistribution().
GetA2()
G4int G4FissionParameters::GetA2 (void) const inline
Definition at line 51 of file G4FissionParameters.hh.
Referenced by G4CompetitiveFission::FissionAtomicNumber(), G4CompetitiveFission::FissionKineticEnergy(), and G4CompetitiveFission::MassDistribution().
GetAs()
G4double G4FissionParameters::GetAs (void) const inline
Definition at line 53 of file G4FissionParameters.hh.
Referenced by G4CompetitiveFission::FissionAtomicNumber(), G4CompetitiveFission::FissionKineticEnergy(), and G4CompetitiveFission::MassDistribution().
GetSigma1()
G4double G4FissionParameters::GetSigma1 (void) const inline
Definition at line 54 of file G4FissionParameters.hh.
Referenced by G4CompetitiveFission::FissionKineticEnergy(), and G4CompetitiveFission::MassDistribution().
GetSigma2()
G4double G4FissionParameters::GetSigma2 (void) const inline
Definition at line 55 of file G4FissionParameters.hh.
Referenced by G4CompetitiveFission::FissionAtomicNumber(), G4CompetitiveFission::FissionKineticEnergy(), and G4CompetitiveFission::MassDistribution().
GetSigmaS()
G4double G4FissionParameters::GetSigmaS (void) const inline
Definition at line 56 of file G4FissionParameters.hh.
Referenced by G4CompetitiveFission::FissionAtomicNumber(), G4CompetitiveFission::FissionKineticEnergy(), and G4CompetitiveFission::MassDistribution().
GetW()
G4double G4FissionParameters::GetW (void) const inline
Definition at line 57 of file G4FissionParameters.hh.
Referenced by G4CompetitiveFission::FissionAtomicNumber(), G4CompetitiveFission::FissionKineticEnergy(), and G4CompetitiveFission::MassDistribution().
operator!=()
G4bool G4FissionParameters::operator!= (const G4FissionParameters & right) const private
operator=()
const G4FissionParameters& G4FissionParameters::operator= (const G4FissionParameters & right) private
operator==()
G4bool G4FissionParameters::operator== (const G4FissionParameters & right) const private
Field Documentation
A1
G4int G4FissionParameters::A1 private
Definition at line 68 of file G4FissionParameters.hh.
Referenced by DefineParameters(), and GetA1().
A2
G4int G4FissionParameters::A2 private
Definition at line 69 of file G4FissionParameters.hh.
Referenced by DefineParameters(), and GetA2().
A3
G4double G4FissionParameters::A3 private
Definition at line 70 of file G4FissionParameters.hh.
Referenced by DefineParameters().
As
G4double G4FissionParameters::As private
Definition at line 73 of file G4FissionParameters.hh.
Referenced by DefineParameters(), and GetAs().
Sigma1
G4double G4FissionParameters::Sigma1 private
Definition at line 77 of file G4FissionParameters.hh.
Referenced by DefineParameters(), and GetSigma1().
Sigma2
G4double G4FissionParameters::Sigma2 private
Definition at line 78 of file G4FissionParameters.hh.
Referenced by DefineParameters(), and GetSigma2().
SigmaS
G4double G4FissionParameters::SigmaS private
Definition at line 81 of file G4FissionParameters.hh.
Referenced by DefineParameters(), and GetSigmaS().
w
G4double G4FissionParameters::w private
Definition at line 85 of file G4FissionParameters.hh.
Referenced by DefineParameters(), and GetW().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/de_excitation/fission/include/G4FissionParameters.hh
source/processes/hadronic/models/de_excitation/fission/src/G4FissionParameters.cc