Geant4: G4DNAWaterDissociationDisplacer Class Reference
G4DNAWaterDissociationDisplacer Class Reference
#include <G4DNAWaterDissociationDisplacer.hh>
Public Member Functions
G4DNAWaterDissociationDisplacer ()
virtual ~G4DNAWaterDissociationDisplacer ()
std::vector< G4ThreeVector > GetProductsDisplacement (const G4MolecularDissociationChannel *) const override
G4ThreeVector GetMotherMoleculeDisplacement (const G4MolecularDissociationChannel *) const override
G4ThreeVector radialDistributionOfElectron () const
G4ThreeVector radialDistributionOfProducts (G4double r_rms) const
Public Member Functions inherited from G4VMolecularDecayDisplacer
virtual ~G4VMolecularDecayDisplacer ()
void SetVerbose (G4int verbose)
Static Public Member Functions
static G4double ElectronProbaDistribution (G4double r)
Private Attributes
std::function< G4double(G4double)> fProba1DFunction
std::vector< G4double > fElectronThermalization
G4DNARevertProbability fFastElectronDistrib
Additional Inherited Members
Protected Member Functions inherited from G4VMolecularDecayDisplacer
G4VMolecularDecayDisplacer ()
Protected Attributes inherited from G4VMolecularDecayDisplacer
G4int fVerbose
Detailed Description
Definition at line 56 of file G4DNAWaterDissociationDisplacer.hh.
Constructor & Destructor Documentation
G4DNAWaterDissociationDisplacer()
G4DNAWaterDissociationDisplacer::G4DNAWaterDissociationDisplacer ()
~G4DNAWaterDissociationDisplacer()
G4DNAWaterDissociationDisplacer::~G4DNAWaterDissociationDisplacer () virtual
Definition at line 145 of file G4DNAWaterDissociationDisplacer.cc.
Member Function Documentation
ElectronProbaDistribution()
static G4double G4DNAWaterDissociationDisplacer::ElectronProbaDistribution (G4double r) static
GetMotherMoleculeDisplacement()
G4ThreeVector G4DNAWaterDissociationDisplacer::GetMotherMoleculeDisplacement (const G4MolecularDissociationChannel * theDecayChannel) const override virtual
Implements G4VMolecularDecayDisplacer.
Definition at line 152 of file G4DNAWaterDissociationDisplacer.cc.
GetProductsDisplacement()
vector< G4ThreeVector > G4DNAWaterDissociationDisplacer::GetProductsDisplacement (const G4MolecularDissociationChannel * theDecayChannel) const override virtual
Implements G4VMolecularDecayDisplacer.
Definition at line 189 of file G4DNAWaterDissociationDisplacer.cc.
radialDistributionOfElectron()
G4ThreeVector G4DNAWaterDissociationDisplacer::radialDistributionOfElectron () const
Definition at line 399 of file G4DNAWaterDissociationDisplacer.cc.
Referenced by GetProductsDisplacement().
radialDistributionOfProducts()
G4ThreeVector G4DNAWaterDissociationDisplacer::radialDistributionOfProducts (G4double r_rms) const
Definition at line 386 of file G4DNAWaterDissociationDisplacer.cc.
Referenced by GetMotherMoleculeDisplacement(), and GetProductsDisplacement().
Field Documentation
fElectronThermalization
std::vector<G4double> G4DNAWaterDissociationDisplacer::fElectronThermalization private
Definition at line 82 of file G4DNAWaterDissociationDisplacer.hh.
Referenced by radialDistributionOfElectron().
fFastElectronDistrib
G4DNARevertProbability G4DNAWaterDissociationDisplacer::fFastElectronDistrib private
Definition at line 83 of file G4DNAWaterDissociationDisplacer.hh.
fProba1DFunction
std::function<G4double(G4double)> G4DNAWaterDissociationDisplacer::fProba1DFunction private
Definition at line 81 of file G4DNAWaterDissociationDisplacer.hh.
The documentation for this class was generated from the following files:
source/processes/electromagnetic/dna/processes/include/G4DNAWaterDissociationDisplacer.hh
source/processes/electromagnetic/dna/processes/src/G4DNAWaterDissociationDisplacer.cc