Geant4: G4MolecularConfiguration Class Reference
G4MolecularConfiguration Class Reference
The pointer G4MolecularConfiguration will be shared by all the molecules having the same molecule definition and the same electron occupancy BE CAREFUlL !!! : If you change the mass for instance of a OH^-, this will affect all the OH^- molecule diffusing around.
#include <G4MolecularConfiguration.hh>
Data Structures
class G4MolecularConfigurationManager
Public Types
typedef std::function< double(const G4Material *, double, const G4MolecularConfiguration *)> G4DiffCoeffParam
Public Member Functions
void AddDiffCoeffParameterization (const G4DiffCoeffParam &)
const G4MoleculeDefinition * GetDefinition () const
const G4String & GetName () const
Returns the name of the molecule.
const G4String & GetFormatedName () const
Returns the formated name of the molecule.
G4int GetAtomsNumber () const
Returns the nomber of atoms compouning the molecule.
G4MolecularConfiguration * ExciteMolecule (G4int)
Method used in Geant4-DNA to excite water molecules.
G4MolecularConfiguration * IonizeMolecule (G4int)
Method used in Geant4-DNA to ionize water molecules.
G4MolecularConfiguration * AddElectron (G4int orbit, G4int n=1)
Add n electrons to a given orbit.
G4MolecularConfiguration * RemoveElectron (G4int, G4int number=1)
Remove n electrons to a given orbit.
G4MolecularConfiguration * MoveOneElectron (G4int, G4int)
Move one electron from an orbit to another.
G4double GetNbElectrons () const
Returns the number of electron.
void PrintState () const
Display the electronic state of the molecule.
const std::vector< const G4MolecularDissociationChannel * > * GetDecayChannel () const
G4int GetFakeParticleID () const
G4int GetMoleculeID () const
void SetDiffusionCoefficient (G4double)
Sets the diffusion coefficient D of the molecule used in diffusion processes to calculate the mean square jump distance between two changes of direction.
G4double GetDiffusionCoefficient () const
Returns the diffusion coefficient D.
G4double GetDiffusionCoefficient (const G4Material *, double temperature) const
void SetDecayTime (G4double)
Set the decay time of the molecule.
G4double GetDecayTime () const
Returns the decay time of the molecule.
void SetVanDerVaalsRadius (G4double)
The Van Der Valls Radius of the molecule.
G4double GetVanDerVaalsRadius () const
const G4ElectronOccupancy * GetElectronOccupancy () const
Returns the object ElectronOccupancy describing the electronic configuration of the molecule.
G4int GetCharge () const
Returns the charge of molecule.
void SetMass (G4double)
Set the total mass of the molecule.
G4double GetMass () const
Returns the total mass of the molecule.
void SetLabel (const G4String &)
const G4String & GetLabel () const
void Finalize ()
const G4String & GetUserID () const
void Serialize (std::ostream &)
void Unserialize (std::istream &)
Static Public Member Functions
static G4MolecularConfiguration * GetOrCreateMolecularConfiguration (const G4MoleculeDefinition *)
static G4MolecularConfiguration * GetOrCreateMolecularConfiguration (const G4MoleculeDefinition *, const G4ElectronOccupancy &eOcc)
static G4MolecularConfiguration * GetOrCreateMolecularConfiguration (const G4MoleculeDefinition *, int charge)
static G4MolecularConfiguration * CreateMolecularConfiguration (const G4String &userIdentifier, const G4MoleculeDefinition *, bool &wasAlreadyCreated)
static G4MolecularConfiguration * CreateMolecularConfiguration (const G4String &userIdentifier, const G4MoleculeDefinition *, const G4String &label, const G4ElectronOccupancy &eOcc, bool &wasAlreadyCreated)
static G4MolecularConfiguration * CreateMolecularConfiguration (const G4String &userIdentifier, const G4MoleculeDefinition *, int charge, const G4String &label, bool &wasAlreadyCreated)
static G4MolecularConfiguration * CreateMolecularConfiguration (const G4String &userIdentifier, const G4MoleculeDefinition *, const G4String &label, bool &wasAlreadyCreated)
static G4MolecularConfiguration * GetMolecularConfiguration (const G4MoleculeDefinition *, const G4String &label)
static G4MolecularConfiguration * GetMolecularConfiguration (int moleculeID)
static G4MolecularConfiguration * GetMolecularConfiguration (const G4String &userID)
static int GetNumberOfSpecies ()
static std::map< G4String, G4MolecularConfiguration * > & GetUserIDTable ()
static void DeleteManager ()
static double DiffCoeffWater (double temperature_K)
static void FinalizeAll ()
static void SetGlobalTemperature (G4double)
static G4double GetGlobalTemperature ()
static G4MolecularConfiguration * Load (std::istream &)
Protected Member Functions
G4MolecularConfiguration (const G4MoleculeDefinition *, const G4ElectronOccupancy &, const G4String &label="")
G4MolecularConfiguration (const G4MoleculeDefinition *, int charge)
G4MolecularConfiguration (const G4MoleculeDefinition *, const G4String &label, int charge)
G4MolecularConfiguration (std::istream &)
G4MolecularConfiguration (const G4MolecularConfiguration &)
G4MolecularConfiguration & operator= (G4MolecularConfiguration &right)
~G4MolecularConfiguration ()
G4MolecularConfiguration * ChangeConfiguration (const G4ElectronOccupancy &newElectronOccupancy)
G4MolecularConfiguration * ChangeConfiguration (int charge)
void CheckElectronOccupancy (const char *line) const
void MakeExceptionIfFinalized ()
void SetUserID (const G4String &userID)
void CreateDefaultDiffCoeffParam ()
Static Protected Member Functions
static void ScaleAllDiffusionCoefficientsOnWater (double temperature_K)
static G4MolecularConfigurationManager * GetManager ()
static double ReturnDefaultDiffCoeff (const G4Material *, double, const G4MolecularConfiguration *molConf)
Protected Attributes
const G4MoleculeDefinition * fMoleculeDefinition
const G4ElectronOccupancy * fElectronOccupancy
G4String * fLabel
G4double fDynDiffusionCoefficient
G4double fDynVanDerVaalsRadius
G4double fDynDecayTime
G4double fDynMass
G4int fDynCharge
G4int fMoleculeID
G4String fFormatedName
G4String fName
G4String fUserIdentifier
G4bool fIsFinalized
G4DiffCoeffParam fDiffParam
Static Protected Attributes
static G4MolecularConfigurationManager * fgManager = 0
static double fgTemperature = 298
Detailed Description
The pointer G4MolecularConfiguration will be shared by all the molecules having the same molecule definition and the same electron occupancy BE CAREFUlL !!! : If you change the mass for instance of a OH^-, this will affect all the OH^- molecule diffusing around.
Definition at line 98 of file G4MolecularConfiguration.hh.
Member Typedef Documentation
G4DiffCoeffParam
typedef std::function<double(const G4Material*, double, const G4MolecularConfiguration*)> G4MolecularConfiguration::G4DiffCoeffParam
Definition at line 104 of file G4MolecularConfiguration.hh.
Constructor & Destructor Documentation
G4MolecularConfiguration() [1/5]
G4MolecularConfiguration::G4MolecularConfiguration (const G4MoleculeDefinition * moleculeDef, const G4ElectronOccupancy & elecOcc, const G4String & label = "") protected
Definition at line 437 of file G4MolecularConfiguration.cc.
G4MolecularConfiguration() [2/5]
G4MolecularConfiguration::G4MolecularConfiguration (const G4MoleculeDefinition * moleculeDef, int charge) protected
Definition at line 490 of file G4MolecularConfiguration.cc.
G4MolecularConfiguration() [3/5]
G4MolecularConfiguration::G4MolecularConfiguration (const G4MoleculeDefinition * moleculeDef, const G4String & label, int charge) protected
Definition at line 79 of file G4MolecularConfiguration.cc.
G4MolecularConfiguration() [4/5]
G4MolecularConfiguration::G4MolecularConfiguration (std::istream & in) protected
Definition at line 1443 of file G4MolecularConfiguration.cc.
G4MolecularConfiguration() [5/5]
G4MolecularConfiguration::G4MolecularConfiguration (const G4MolecularConfiguration &) protected
~G4MolecularConfiguration()
G4MolecularConfiguration::~G4MolecularConfiguration () protected
Definition at line 526 of file G4MolecularConfiguration.cc.
Member Function Documentation
AddDiffCoeffParameterization()
void G4MolecularConfiguration::AddDiffCoeffParameterization (const G4DiffCoeffParam & para) inline
Definition at line 586 of file G4MolecularConfiguration.hh.
AddElectron()
G4MolecularConfiguration * G4MolecularConfiguration::AddElectron (G4int orbit, G4int n = 1)
Add n electrons to a given orbit.
Note : You can add as many electrons to a given orbit, the result may be unrealist.
Definition at line 635 of file G4MolecularConfiguration.cc.
Referenced by G4Molecule::AddElectron().
ChangeConfiguration() [1/2]
G4MolecularConfiguration * G4MolecularConfiguration::ChangeConfiguration (const G4ElectronOccupancy & newElectronOccupancy) protected
Definition at line 544 of file G4MolecularConfiguration.cc.
ChangeConfiguration() [2/2]
G4MolecularConfiguration * G4MolecularConfiguration::ChangeConfiguration (int charge) protected
Definition at line 561 of file G4MolecularConfiguration.cc.
CheckElectronOccupancy()
void G4MolecularConfiguration::CheckElectronOccupancy (const char * line) const protected
Definition at line 823 of file G4MolecularConfiguration.cc.
CreateDefaultDiffCoeffParam()
void G4MolecularConfiguration::CreateDefaultDiffCoeffParam () protected
Definition at line 1515 of file G4MolecularConfiguration.cc.
Referenced by Finalize().
CreateMolecularConfiguration() [1/4]
G4MolecularConfiguration * G4MolecularConfiguration::CreateMolecularConfiguration (const G4String & userIdentifier, const G4MoleculeDefinition * molDef, bool & wasAlreadyCreated) static
Definition at line 1098 of file G4MolecularConfiguration.cc.
Referenced by G4MoleculeTable::CreateConfiguration(), G4MoleculeDefinition::NewConfiguration(), and G4MoleculeDefinition::NewConfigurationWithElectronOccupancy().
CreateMolecularConfiguration() [2/4]
G4MolecularConfiguration * G4MolecularConfiguration::CreateMolecularConfiguration (const G4String & userIdentifier, const G4MoleculeDefinition * molDef, const G4String & label, bool & wasAlreadyCreated) static
Definition at line 1179 of file G4MolecularConfiguration.cc.
CreateMolecularConfiguration() [3/4]
G4MolecularConfiguration * G4MolecularConfiguration::CreateMolecularConfiguration (const G4String & userIdentifier, const G4MoleculeDefinition * molDef, const G4String & label, const G4ElectronOccupancy & eOcc, bool & wasAlreadyCreated) static
Definition at line 1245 of file G4MolecularConfiguration.cc.
CreateMolecularConfiguration() [4/4]
G4MolecularConfiguration * G4MolecularConfiguration::CreateMolecularConfiguration (const G4String & userIdentifier, const G4MoleculeDefinition * molDef, int charge, const G4String & label, bool & wasAlreadyCreated) static
Definition at line 1005 of file G4MolecularConfiguration.cc.
DeleteManager()
void G4MolecularConfiguration::DeleteManager () static
Definition at line 426 of file G4MolecularConfiguration.cc.
Referenced by G4DNAChemistryManager::Clear().
DiffCoeffWater()
double G4MolecularConfiguration::DiffCoeffWater (double temperature_K) static
Definition at line 1482 of file G4MolecularConfiguration.cc.
Referenced by G4DNAMolecularReactionData::ScaledParameterization().
ExciteMolecule()
G4MolecularConfiguration * G4MolecularConfiguration::ExciteMolecule (G4int ExcitedLevel)
Method used in Geant4-DNA to excite water molecules.
Definition at line 587 of file G4MolecularConfiguration.cc.
Referenced by G4Molecule::ExciteMolecule().
Finalize()
void G4MolecularConfiguration::Finalize () inline
Definition at line 574 of file G4MolecularConfiguration.hh.
FinalizeAll()
void G4MolecularConfiguration::FinalizeAll () static
Definition at line 1561 of file G4MolecularConfiguration.cc.
Referenced by G4MoleculeTable::Finalize().
GetAtomsNumber()
G4int G4MolecularConfiguration::GetAtomsNumber () const
Returns the nomber of atoms compouning the molecule.
Definition at line 736 of file G4MolecularConfiguration.cc.
Referenced by G4Molecule::GetAtomsNumber().
GetCharge()
G4int G4MolecularConfiguration::GetCharge () const inline
Returns the charge of molecule.
Definition at line 531 of file G4MolecularConfiguration.hh.
Referenced by G4Molecule::GetCharge().
GetDecayChannel()
const vector< const G4MolecularDissociationChannel * > * G4MolecularConfiguration::GetDecayChannel () const
Definition at line 789 of file G4MolecularConfiguration.cc.
Referenced by G4Molecule::GetDecayChannel().
GetDecayTime()
G4double G4MolecularConfiguration::GetDecayTime () const inline
Returns the decay time of the molecule.
Definition at line 515 of file G4MolecularConfiguration.hh.
Referenced by G4Molecule::GetDecayTime().
GetDefinition()
const G4MoleculeDefinition * G4MolecularConfiguration::GetDefinition () const inline
Definition at line 488 of file G4MolecularConfiguration.hh.
Referenced by G4MoleculeCounter::AddAMoleculeAtTime(), G4Molecule::BuildTrack(), G4Molecule::ChangeConfigurationToLabel(), CreateMolecularConfiguration(), G4Molecule::GetDefinition(), G4DNAWaterDissociationDisplacer::GetProductsDisplacement(), G4MoleculeCounter::RemoveAMoleculeAtTime(), G4MolecularConfiguration::G4MolecularConfigurationManager::RemoveMolecularConfigurationFromTable(), and G4Molecule::SetElectronOccupancy().
GetDiffusionCoefficient() [1/2]
G4double G4MolecularConfiguration::GetDiffusionCoefficient () const inline
Returns the diffusion coefficient D.
Definition at line 504 of file G4MolecularConfiguration.hh.
Referenced by G4DNAMolecularReactionData::G4DNAMolecularReactionData(), G4Molecule::GetDiffusionCoefficient(), G4DNAMolecularReaction::MakeReaction(), ScaleAllDiffusionCoefficientsOnWater(), and G4DNAMoleculeEncounterStepper::Utils::Utils().
GetDiffusionCoefficient() [2/2]
G4double G4MolecularConfiguration::GetDiffusionCoefficient (const G4Material * material, double temperature) const inline
Definition at line 592 of file G4MolecularConfiguration.hh.
GetElectronOccupancy()
const G4ElectronOccupancy * G4MolecularConfiguration::GetElectronOccupancy () const inline
Returns the object ElectronOccupancy describing the electronic configuration of the molecule.
Definition at line 493 of file G4MolecularConfiguration.hh.
Referenced by CreateMolecularConfiguration(), G4Molecule::GetElectronOccupancy(), and G4MolecularConfiguration::G4MolecularConfigurationManager::RemoveMolecularConfigurationFromTable().
GetFakeParticleID()
G4int G4MolecularConfiguration::GetFakeParticleID () const
Definition at line 797 of file G4MolecularConfiguration.cc.
Referenced by G4Molecule::GetFakeParticleID().
GetFormatedName()
const G4String & G4MolecularConfiguration::GetFormatedName () const
Returns the formated name of the molecule.
Definition at line 721 of file G4MolecularConfiguration.cc.
Referenced by G4Molecule::GetFormatedName().
GetGlobalTemperature()
G4double G4MolecularConfiguration::GetGlobalTemperature () static
Definition at line 1533 of file G4MolecularConfiguration.cc.
Referenced by G4Molecule::GetDiffusionVelocity().
GetLabel()
const G4String & G4MolecularConfiguration::GetLabel () const inline
Definition at line 566 of file G4MolecularConfiguration.hh.
Referenced by CreateMolecularConfiguration(), and G4Molecule::GetLabel().
GetManager()
G4MolecularConfiguration::G4MolecularConfigurationManager * G4MolecularConfiguration::GetManager () static protected
Definition at line 130 of file G4MolecularConfiguration.cc.
Referenced by GetUserIDTable().
GetMass()
G4double G4MolecularConfiguration::GetMass () const inline
Returns the total mass of the molecule.
Definition at line 542 of file G4MolecularConfiguration.hh.
Referenced by G4Molecule::GetDiffusionVelocity(), G4Molecule::GetKineticEnergy(), and G4Molecule::GetMass().
GetMolecularConfiguration() [1/3]
G4MolecularConfiguration * G4MolecularConfiguration::GetMolecularConfiguration (const G4MoleculeDefinition * molDef, const G4String & label) static
Definition at line 988 of file G4MolecularConfiguration.cc.
Referenced by G4MoleculeDefinition::AddDecayChannel(), ChangeConfiguration(), G4Molecule::ChangeConfigurationToLabel(), CreateMolecularConfiguration(), G4MoleculeTable::GetConfiguration(), G4MoleculeDefinition::GetConfigurationWithLabel(), GetMolecularConfiguration(), and GetOrCreateMolecularConfiguration().
GetMolecularConfiguration() [2/3]
G4MolecularConfiguration * G4MolecularConfiguration::GetMolecularConfiguration (const G4String & userID) static
Definition at line 1554 of file G4MolecularConfiguration.cc.
GetMolecularConfiguration() [3/3]
G4MolecularConfiguration * G4MolecularConfiguration::GetMolecularConfiguration (int moleculeID) static
Definition at line 997 of file G4MolecularConfiguration.cc.
GetMoleculeID()
G4int G4MolecularConfiguration::GetMoleculeID () const inline
Definition at line 547 of file G4MolecularConfiguration.hh.
Referenced by G4DNAMoleculeEncounterStepper::CalculateStep(), and G4Molecule::GetMoleculeID().
GetName()
const G4String & G4MolecularConfiguration::GetName (void) const
Returns the name of the molecule.
Definition at line 706 of file G4MolecularConfiguration.cc.
Referenced by G4MoleculeCounter::AddAMoleculeAtTime(), G4DNAMolecularReactionTable::CanReactWith(), G4DNAMoleculeEncounterStepper::CheckAndRecordResults(), G4MoleculeCounter::Dump(), G4Molecule::GetName(), G4DNAMolecularReactionTable::GetReactionData(), G4DNAMolecularReactionTable::GetReativesNData(), G4DNAMolecularReactionTable::PrintTable(), G4MoleculeCounter::RemoveAMoleculeAtTime(), G4DNAMolecularReaction::TestReactibility(), and ScoreSpecies::WriteWithAnalysisManager().
GetNbElectrons()
G4double G4MolecularConfiguration::GetNbElectrons () const
Returns the number of electron.
Definition at line 743 of file G4MolecularConfiguration.cc.
Referenced by G4Molecule::GetNbElectrons().
GetNumberOfSpecies()
int G4MolecularConfiguration::GetNumberOfSpecies () static
Definition at line 66 of file G4MolecularConfiguration.cc.
Referenced by G4MoleculeTable::GetNumberOfDefinedSpecies().
GetOrCreateMolecularConfiguration() [1/3]
G4MolecularConfiguration * G4MolecularConfiguration::GetOrCreateMolecularConfiguration (const G4MoleculeDefinition * molDef) static
Definition at line 338 of file G4MolecularConfiguration.cc.
Referenced by G4Molecule::G4Molecule(), GetOrCreateMolecularConfiguration(), G4MoleculeTable::PrepareMolecularConfiguration(), and G4Molecule::SetElectronOccupancy().
GetOrCreateMolecularConfiguration() [2/3]
G4MolecularConfiguration * G4MolecularConfiguration::GetOrCreateMolecularConfiguration (const G4MoleculeDefinition * molDef, const G4ElectronOccupancy & eOcc) static
Definition at line 382 of file G4MolecularConfiguration.cc.
GetOrCreateMolecularConfiguration() [3/3]
G4MolecularConfiguration * G4MolecularConfiguration::GetOrCreateMolecularConfiguration (const G4MoleculeDefinition * molDef, int charge) static
Definition at line 406 of file G4MolecularConfiguration.cc.
GetUserID()
const G4String & G4MolecularConfiguration::GetUserID () const inline
Definition at line 580 of file G4MolecularConfiguration.hh.
GetUserIDTable()
static std::map<G4String, G4MolecularConfiguration*>& G4MolecularConfiguration::GetUserIDTable () inline static
Definition at line 169 of file G4MolecularConfiguration.hh.
Referenced by G4MoleculeTable::GetConfigurationIterator().
GetVanDerVaalsRadius()
G4double G4MolecularConfiguration::GetVanDerVaalsRadius () const inline
Definition at line 526 of file G4MolecularConfiguration.hh.
Referenced by G4Molecule::GetVanDerVaalsRadius().
IonizeMolecule()
G4MolecularConfiguration * G4MolecularConfiguration::IonizeMolecule (G4int IonizedLevel)
Method used in Geant4-DNA to ionize water molecules.
Definition at line 604 of file G4MolecularConfiguration.cc.
Referenced by G4Molecule::IonizeMolecule().
Load()
G4MolecularConfiguration * G4MolecularConfiguration::Load (std::istream & in) static
Definition at line 1436 of file G4MolecularConfiguration.cc.
MakeExceptionIfFinalized()
void G4MolecularConfiguration::MakeExceptionIfFinalized () protected
Definition at line 114 of file G4MolecularConfiguration.cc.
Referenced by SetDecayTime(), SetDiffusionCoefficient(), SetMass(), and SetVanDerVaalsRadius().
MoveOneElectron()
G4MolecularConfiguration * G4MolecularConfiguration::MoveOneElectron (G4int orbitToFree, G4int orbitToFill)
Move one electron from an orbit to another.
Definition at line 677 of file G4MolecularConfiguration.cc.
Referenced by G4Molecule::MoveOneElectron().
operator=()
G4MolecularConfiguration & G4MolecularConfiguration::operator= (G4MolecularConfiguration & right) protected
Definition at line 576 of file G4MolecularConfiguration.cc.
PrintState()
void G4MolecularConfiguration::PrintState () const
Display the electronic state of the molecule.
Definition at line 751 of file G4MolecularConfiguration.cc.
Referenced by CreateMolecularConfiguration(), G4Molecule::PrintState(), and G4MoleculeCounter::RemoveAMoleculeAtTime().
RemoveElectron()
G4MolecularConfiguration * G4MolecularConfiguration::RemoveElectron (G4int orbit, G4int number = 1)
Remove n electrons to a given orbit.
Definition at line 648 of file G4MolecularConfiguration.cc.
Referenced by G4Molecule::RemoveElectron().
ReturnDefaultDiffCoeff()
double G4MolecularConfiguration::ReturnDefaultDiffCoeff (const G4Material * , double , const G4MolecularConfiguration * molConf) static protected
Definition at line 71 of file G4MolecularConfiguration.cc.
Referenced by CreateDefaultDiffCoeffParam(), and G4MolecularConfiguration().
ScaleAllDiffusionCoefficientsOnWater()
void G4MolecularConfiguration::ScaleAllDiffusionCoefficientsOnWater (double temperature_K) static protected
Definition at line 1494 of file G4MolecularConfiguration.cc.
Serialize()
void G4MolecularConfiguration::Serialize (std::ostream & out)
Definition at line 1386 of file G4MolecularConfiguration.cc.
SetDecayTime()
void G4MolecularConfiguration::SetDecayTime (G4double dynDecayTime) inline
Set the decay time of the molecule.
Definition at line 509 of file G4MolecularConfiguration.hh.
Referenced by G4MoleculeDefinition::NewConfigurationWithElectronOccupancy(), and G4Molecule::SetDecayTime().
SetDiffusionCoefficient()
void G4MolecularConfiguration::SetDiffusionCoefficient (G4double dynDiffusionCoefficient) inline
Sets the diffusion coefficient D of the molecule used in diffusion processes to calculate the mean square jump distance between two changes of direction.
In three dimension : <x^2> = 6 D t where t is the mean jump time between two changes of direction.
Note : Diffusion Coefficient in one medium only For the time being, we will consider only one diffusion coefficient for the all simulation => diffusion in one medium only If the user needs to use the diffusion in different materials, she/he should contact the developpers/mainteners of this package
Definition at line 498 of file G4MolecularConfiguration.hh.
Referenced by G4EmDNAChemistry_option1::ConstructMolecule(), G4MoleculeTable::CreateConfiguration(), ScaleAllDiffusionCoefficientsOnWater(), and G4Molecule::SetDiffusionCoefficient().
SetGlobalTemperature()
void G4MolecularConfiguration::SetGlobalTemperature (G4double temperature) static
Definition at line 1525 of file G4MolecularConfiguration.cc.
Referenced by G4DNAChemistryManager::SetGlobalTemperature().
SetLabel()
void G4MolecularConfiguration::SetLabel (const G4String & label) inline
Definition at line 552 of file G4MolecularConfiguration.hh.
Referenced by CreateMolecularConfiguration(), and G4Molecule::SetLabel().
SetMass()
void G4MolecularConfiguration::SetMass (G4double aMass) inline
Set the total mass of the molecule.
Definition at line 536 of file G4MolecularConfiguration.hh.
Referenced by G4EmDNAChemistry::ConstructMolecule(), G4EmDNAChemistry_option1::ConstructMolecule(), and G4Molecule::SetMass().
SetUserID()
void G4MolecularConfiguration::SetUserID (const G4String & userID) protected
Definition at line 1473 of file G4MolecularConfiguration.cc.
Referenced by GetOrCreateMolecularConfiguration().
SetVanDerVaalsRadius()
void G4MolecularConfiguration::SetVanDerVaalsRadius (G4double dynVanDerVaalsRadius) inline
The Van Der Valls Radius of the molecule.
Definition at line 520 of file G4MolecularConfiguration.hh.
Referenced by G4Molecule::SetVanDerVaalsRadius().
Unserialize()
void G4MolecularConfiguration::Unserialize (std::istream & in)
Definition at line 1408 of file G4MolecularConfiguration.cc.
Field Documentation
fDiffParam
G4DiffCoeffParam G4MolecularConfiguration::fDiffParam protected
Definition at line 479 of file G4MolecularConfiguration.hh.
Referenced by GetDiffusionCoefficient().
fDynCharge
G4int G4MolecularConfiguration::fDynCharge protected
Definition at line 472 of file G4MolecularConfiguration.hh.
Referenced by GetCharge().
fDynDecayTime
G4double G4MolecularConfiguration::fDynDecayTime protected
Definition at line 470 of file G4MolecularConfiguration.hh.
Referenced by GetDecayTime(), and SetDecayTime().
fDynDiffusionCoefficient
G4double G4MolecularConfiguration::fDynDiffusionCoefficient protected
Definition at line 468 of file G4MolecularConfiguration.hh.
Referenced by GetDiffusionCoefficient(), ReturnDefaultDiffCoeff(), and SetDiffusionCoefficient().
fDynMass
G4double G4MolecularConfiguration::fDynMass protected
Definition at line 471 of file G4MolecularConfiguration.hh.
Referenced by GetMass(), and SetMass().
fDynVanDerVaalsRadius
G4double G4MolecularConfiguration::fDynVanDerVaalsRadius protected
Definition at line 469 of file G4MolecularConfiguration.hh.
Referenced by GetVanDerVaalsRadius(), and SetVanDerVaalsRadius().
fElectronOccupancy
const G4ElectronOccupancy* G4MolecularConfiguration::fElectronOccupancy protected
Definition at line 464 of file G4MolecularConfiguration.hh.
Referenced by GetElectronOccupancy(), and G4MolecularConfiguration::G4MolecularConfigurationManager::RemoveMolecularConfigurationFromTable().
fFormatedName
G4String G4MolecularConfiguration::fFormatedName protected
Definition at line 474 of file G4MolecularConfiguration.hh.
fgManager
MolecularConfigurationManager * G4MolecularConfiguration::fgManager = 0 static protected
Definition at line 460 of file G4MolecularConfiguration.hh.
Referenced by SetLabel().
fgTemperature
G4double G4MolecularConfiguration::fgTemperature = 298 static protected
Definition at line 480 of file G4MolecularConfiguration.hh.
fIsFinalized
G4bool G4MolecularConfiguration::fIsFinalized protected
Definition at line 477 of file G4MolecularConfiguration.hh.
Referenced by Finalize().
fLabel
G4String* G4MolecularConfiguration::fLabel mutable protected
Definition at line 466 of file G4MolecularConfiguration.hh.
Referenced by CreateMolecularConfiguration(), GetLabel(), G4MolecularConfiguration::G4MolecularConfigurationManager::RecordNewlyLabeledConfiguration(), and SetLabel().
fMoleculeDefinition
const G4MoleculeDefinition* G4MolecularConfiguration::fMoleculeDefinition protected
Definition at line 463 of file G4MolecularConfiguration.hh.
Referenced by GetDefinition(), and G4MolecularConfiguration::G4MolecularConfigurationManager::RecordNewlyLabeledConfiguration().
fMoleculeID
G4int G4MolecularConfiguration::fMoleculeID protected
Definition at line 473 of file G4MolecularConfiguration.hh.
Referenced by GetMoleculeID().
fName
G4String G4MolecularConfiguration::fName protected
Definition at line 475 of file G4MolecularConfiguration.hh.
fUserIdentifier
G4String G4MolecularConfiguration::fUserIdentifier protected
Definition at line 476 of file G4MolecularConfiguration.hh.
Referenced by CreateMolecularConfiguration(), and GetUserID().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/dna/molecules/management/include/G4MolecularConfiguration.hh
source/processes/electromagnetic/dna/molecules/management/src/G4MolecularConfiguration.cc