Geant4: G4CascadeInterface Class Reference
G4CascadeInterface Class Reference
#include <G4CascadeInterface.hh>
Public Member Functions
G4CascadeInterface (const G4String &name="BertiniCascade")
virtual ~G4CascadeInterface ()
G4ReactionProductVector * Propagate (G4KineticTrackVector *theSecondaries, G4V3DNucleus *theNucleus)
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &theNucleus)
void SetVerboseLevel (G4int verbose)
G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &theNucleus)
G4bool IsApplicable (const G4ParticleDefinition *aPD) const
void useCascadeDeexcitation ()
void usePreCompoundDeexcitation ()
virtual void ModelDescription (std::ostream &outFile) const
virtual void DumpConfiguration (std::ostream &outFile) const
Public Member Functions inherited from G4VIntraNuclearTransportModel
G4VIntraNuclearTransportModel (const G4String &mName="CascadeModel", G4VPreCompoundModel *ptr=nullptr)
virtual ~G4VIntraNuclearTransportModel ()
virtual G4ReactionProductVector * PropagateNuclNucl (G4KineticTrackVector *theSecondaries, G4V3DNucleus *theNucleus, G4V3DNucleus *theProjectileNucleus)
void SetDeExcitation (G4VPreCompoundModel *ptr)
void Set3DNucleus (G4V3DNucleus *const value)
void SetPrimaryProjectile (const G4HadProjectile &aPrimary)
const G4String & GetModelName () const
virtual void PropagateModelDescription (std::ostream &outFile) const
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double, G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Static Public Member Functions
static void Initialize ()
Protected Member Functions
void clear ()
G4bool createBullet (const G4HadProjectile &aTrack)
G4bool createTarget (G4Nucleus &theNucleus)
G4bool createTarget (G4V3DNucleus *theNucleus)
G4bool createTarget (G4int A, G4int Z)
G4bool coulombBarrierViolation () const
G4bool retryInelasticProton () const
G4bool retryInelasticNucleus () const
void copyOutputToHadronicResult ()
G4ReactionProductVector * copyOutputToReactionProducts ()
G4HadFinalState * NoInteraction (const G4HadProjectile &aTrack, G4Nucleus &theNucleus)
void checkFinalResult ()
void throwNonConservationFailure ()
G4DynamicParticle * makeDynamicParticle (const G4InuclElementaryParticle &iep) const
G4DynamicParticle * makeDynamicParticle (const G4InuclNuclei &inuc) const
Protected Member Functions inherited from G4VIntraNuclearTransportModel
G4V3DNucleus * Get3DNucleus () const
G4VPreCompoundModel * GetDeExcitation () const
const G4HadProjectile * GetPrimaryProjectile () const
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Private Member Functions
G4int operator== (const G4CascadeInterface &right) const
G4int operator!= (const G4CascadeInterface &right) const
G4CascadeInterface (const G4CascadeInterface &)
G4CascadeInterface & operator= (const G4CascadeInterface &)
Private Attributes
const G4String randomFile
const G4int maximumTries
G4int numberOfTries
G4InuclCollider * collider
G4CascadeCheckBalance * balance
G4InuclParticle * bullet
G4InuclParticle * target
G4CollisionOutput * output
G4InuclElementaryParticle hadronBullet
G4InuclNuclei nucleusBullet
G4InuclElementaryParticle hadronTarget
G4InuclNuclei nucleusTarget
Additional Inherited Members
Protected Attributes inherited from G4VIntraNuclearTransportModel
G4String theTransportModelName
G4V3DNucleus * the3DNucleus
G4VPreCompoundModel * theDeExcitation
const G4HadProjectile * thePrimaryProjectile
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 87 of file G4CascadeInterface.hh.
Constructor & Destructor Documentation
G4CascadeInterface() [1/2]
G4CascadeInterface::G4CascadeInterface (const G4String & name = "BertiniCascade")
Definition at line 145 of file G4CascadeInterface.cc.
~G4CascadeInterface()
G4CascadeInterface::~G4CascadeInterface () virtual
Definition at line 164 of file G4CascadeInterface.cc.
G4CascadeInterface() [2/2]
G4CascadeInterface::G4CascadeInterface (const G4CascadeInterface &) private
Member Function Documentation
ApplyYourself()
G4HadFinalState * G4CascadeInterface::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & theNucleus) virtual
Implements G4HadronicInteraction.
Definition at line 247 of file G4CascadeInterface.cc.
Referenced by G4ElectroVDNuclearModel::CalculateHadronicVertex(), and G4MuonVDNuclearModel::CalculateHadronicVertex().
checkFinalResult()
void G4CascadeInterface::checkFinalResult () protected
Definition at line 628 of file G4CascadeInterface.cc.
Referenced by ApplyYourself().
clear()
void G4CascadeInterface::clear (void) protected
Definition at line 189 of file G4CascadeInterface.cc.
Referenced by ApplyYourself(), Propagate(), and ~G4CascadeInterface().
copyOutputToHadronicResult()
void G4CascadeInterface::copyOutputToHadronicResult () protected
Definition at line 559 of file G4CascadeInterface.cc.
Referenced by ApplyYourself().
copyOutputToReactionProducts()
G4ReactionProductVector * G4CascadeInterface::copyOutputToReactionProducts () protected
Definition at line 586 of file G4CascadeInterface.cc.
Referenced by Propagate().
coulombBarrierViolation()
G4bool G4CascadeInterface::coulombBarrierViolation () const protected
Definition at line 664 of file G4CascadeInterface.cc.
Referenced by retryInelasticNucleus().
createBullet()
G4bool G4CascadeInterface::createBullet (const G4HadProjectile & aTrack) protected
Definition at line 444 of file G4CascadeInterface.cc.
Referenced by ApplyYourself(), and Propagate().
createTarget() [1/3]
G4bool G4CascadeInterface::createTarget (G4int A, G4int Z) protected
Definition at line 503 of file G4CascadeInterface.cc.
createTarget() [2/3]
G4bool G4CascadeInterface::createTarget (G4Nucleus & theNucleus) protected
Definition at line 495 of file G4CascadeInterface.cc.
Referenced by ApplyYourself(), createTarget(), and Propagate().
createTarget() [3/3]
G4bool G4CascadeInterface::createTarget (G4V3DNucleus * theNucleus) protected
Definition at line 499 of file G4CascadeInterface.cc.
DumpConfiguration()
void G4CascadeInterface::DumpConfiguration (std::ostream & outFile) const virtual
Definition at line 185 of file G4CascadeInterface.cc.
Initialize()
void G4CascadeInterface::Initialize () static
Definition at line 197 of file G4CascadeInterface.cc.
Referenced by G4CascadeInterface().
IsApplicable() [1/2]
G4bool G4CascadeInterface::IsApplicable (const G4HadProjectile & aTrack, G4Nucleus & theNucleus) virtual
Reimplemented from G4HadronicInteraction.
Definition at line 230 of file G4CascadeInterface.cc.
Referenced by ApplyYourself(), and G4HadronicAbsorptionBertini::IsApplicable().
IsApplicable() [2/2]
G4bool G4CascadeInterface::IsApplicable (const G4ParticleDefinition * aPD) const
Definition at line 235 of file G4CascadeInterface.cc.
makeDynamicParticle() [1/2]
G4DynamicParticle * G4CascadeInterface::makeDynamicParticle (const G4InuclElementaryParticle & iep) const protected
Definition at line 521 of file G4CascadeInterface.cc.
Referenced by copyOutputToHadronicResult(), and copyOutputToReactionProducts().
makeDynamicParticle() [2/2]
G4DynamicParticle * G4CascadeInterface::makeDynamicParticle (const G4InuclNuclei & inuc) const protected
Definition at line 547 of file G4CascadeInterface.cc.
ModelDescription()
void G4CascadeInterface::ModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4VIntraNuclearTransportModel.
Definition at line 171 of file G4CascadeInterface.cc.
NoInteraction()
G4HadFinalState * G4CascadeInterface::NoInteraction (const G4HadProjectile & aTrack, G4Nucleus & theNucleus) protected
Definition at line 427 of file G4CascadeInterface.cc.
Referenced by ApplyYourself().
operator!=()
G4int G4CascadeInterface::operator!= (const G4CascadeInterface & right) const inline private
Definition at line 157 of file G4CascadeInterface.hh.
operator=()
G4CascadeInterface& G4CascadeInterface::operator= (const G4CascadeInterface &) private
operator==()
G4int G4CascadeInterface::operator== (const G4CascadeInterface & right) const inline private
Definition at line 153 of file G4CascadeInterface.hh.
Propagate()
G4ReactionProductVector * G4CascadeInterface::Propagate (G4KineticTrackVector * theSecondaries, G4V3DNucleus * theNucleus) virtual
Implements G4VIntraNuclearTransportModel.
Definition at line 352 of file G4CascadeInterface.cc.
retryInelasticNucleus()
G4bool G4CascadeInterface::retryInelasticNucleus () const protected
Definition at line 715 of file G4CascadeInterface.cc.
Referenced by ApplyYourself(), and Propagate().
retryInelasticProton()
G4bool G4CascadeInterface::retryInelasticProton () const protected
Definition at line 683 of file G4CascadeInterface.cc.
Referenced by ApplyYourself().
SetVerboseLevel()
void G4CascadeInterface::SetVerboseLevel (G4int verbose)
Definition at line 220 of file G4CascadeInterface.cc.
Referenced by G4CascadeInterface().
throwNonConservationFailure()
void G4CascadeInterface::throwNonConservationFailure () protected
Definition at line 764 of file G4CascadeInterface.cc.
Referenced by ApplyYourself(), and Propagate().
useCascadeDeexcitation()
void G4CascadeInterface::useCascadeDeexcitation ()
Definition at line 209 of file G4CascadeInterface.cc.
Referenced by G4CascadeInterface().
usePreCompoundDeexcitation()
void G4CascadeInterface::usePreCompoundDeexcitation ()
Definition at line 213 of file G4CascadeInterface.cc.
Referenced by G4HadronInelasticQBBC::ConstructProcess(), G4CascadeInterface(), and G4HadronicAbsorptionBertini::G4HadronicAbsorptionBertini().
Field Documentation
balance
G4CascadeCheckBalance* G4CascadeInterface::balance private
Definition at line 167 of file G4CascadeInterface.hh.
Referenced by ApplyYourself(), checkFinalResult(), G4CascadeInterface(), Propagate(), retryInelasticNucleus(), SetVerboseLevel(), throwNonConservationFailure(), and ~G4CascadeInterface().
bullet
G4InuclParticle* G4CascadeInterface::bullet private
Definition at line 169 of file G4CascadeInterface.hh.
Referenced by ApplyYourself(), checkFinalResult(), clear(), createBullet(), Propagate(), retryInelasticNucleus(), retryInelasticProton(), and throwNonConservationFailure().
collider
G4InuclCollider* G4CascadeInterface::collider private
Definition at line 166 of file G4CascadeInterface.hh.
Referenced by ApplyYourself(), Propagate(), SetVerboseLevel(), useCascadeDeexcitation(), usePreCompoundDeexcitation(), and ~G4CascadeInterface().
hadronBullet
G4InuclElementaryParticle G4CascadeInterface::hadronBullet private
Definition at line 174 of file G4CascadeInterface.hh.
Referenced by createBullet().
hadronTarget
G4InuclElementaryParticle G4CascadeInterface::hadronTarget private
Definition at line 177 of file G4CascadeInterface.hh.
Referenced by createTarget().
maximumTries
const G4int G4CascadeInterface::maximumTries private
Definition at line 162 of file G4CascadeInterface.hh.
Referenced by ApplyYourself(), Propagate(), retryInelasticNucleus(), and retryInelasticProton().
nucleusBullet
G4InuclNuclei G4CascadeInterface::nucleusBullet private
Definition at line 175 of file G4CascadeInterface.hh.
Referenced by createBullet().
nucleusTarget
G4InuclNuclei G4CascadeInterface::nucleusTarget private
Definition at line 178 of file G4CascadeInterface.hh.
Referenced by createTarget().
numberOfTries
G4int G4CascadeInterface::numberOfTries private
Definition at line 164 of file G4CascadeInterface.hh.
Referenced by ApplyYourself(), Propagate(), retryInelasticNucleus(), retryInelasticProton(), and throwNonConservationFailure().
output
G4CollisionOutput* G4CascadeInterface::output private
Definition at line 172 of file G4CascadeInterface.hh.
Referenced by ApplyYourself(), checkFinalResult(), copyOutputToHadronicResult(), copyOutputToReactionProducts(), coulombBarrierViolation(), Propagate(), retryInelasticNucleus(), retryInelasticProton(), SetVerboseLevel(), throwNonConservationFailure(), and ~G4CascadeInterface().
randomFile
const G4String G4CascadeInterface::randomFile private
Definition at line 161 of file G4CascadeInterface.hh.
Referenced by ApplyYourself(), and Propagate().
target
G4InuclParticle* G4CascadeInterface::target private
Definition at line 170 of file G4CascadeInterface.hh.
Referenced by ApplyYourself(), checkFinalResult(), clear(), createTarget(), Propagate(), and throwNonConservationFailure().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/cascade/cascade/include/G4CascadeInterface.hh
source/processes/hadronic/models/cascade/cascade/src/G4CascadeInterface.cc