Geant4: G4GDMLWriteStructure Class Reference
G4GDMLWriteStructure Class Reference
#include <G4GDMLWriteStructure.hh>
Public Member Functions
G4GDMLWriteStructure ()
virtual ~G4GDMLWriteStructure ()
virtual void StructureWrite (xercesc::DOMElement *)
void AddVolumeAuxiliary (G4GDMLAuxStructType myaux, const G4LogicalVolume *const)
void SetEnergyCutsExport (G4bool)
void SetSDExport (G4bool)
G4int GetMaxExportLevel () const
void SetMaxExportLevel (G4int)
Public Member Functions inherited from G4GDMLWriteParamvol
virtual void ParamvolWrite (xercesc::DOMElement *, const G4VPhysicalVolume *const)
virtual void ParamvolAlgorithmWrite (xercesc::DOMElement *paramvolElement, const G4VPhysicalVolume *const paramvol)
Public Member Functions inherited from G4GDMLWriteSetup
virtual void SetupWrite (xercesc::DOMElement *, const G4LogicalVolume *const)
Public Member Functions inherited from G4GDMLWriteSolids
virtual void AddSolid (const G4VSolid *const)
virtual void SolidsWrite (xercesc::DOMElement *)
Public Member Functions inherited from G4GDMLWriteMaterials
void AddIsotope (const G4Isotope *const)
void AddElement (const G4Element *const)
void AddMaterial (const G4Material *const)
virtual void MaterialsWrite (xercesc::DOMElement *)
Public Member Functions inherited from G4GDMLWriteDefine
G4ThreeVector GetAngles (const G4RotationMatrix &)
void ScaleWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &scl)
void RotationWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &rot)
void PositionWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &pos)
void FirstrotationWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &rot)
void FirstpositionWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &pos)
void AddPosition (const G4String &name, const G4ThreeVector &pos)
virtual void DefineWrite (xercesc::DOMElement *)
Public Member Functions inherited from G4GDMLWrite
G4Transform3D Write (const G4String &filename, const G4LogicalVolume *const topLog, const G4String &schemaPath, const G4int depth, G4bool storeReferences=true)
void AddModule (const G4VPhysicalVolume *const topVol)
void AddModule (const G4int depth)
void AddAuxiliary (G4GDMLAuxStructType myaux)
virtual void ExtensionWrite (xercesc::DOMElement *)
virtual void UserinfoWrite (xercesc::DOMElement *)
virtual void AddExtension (xercesc::DOMElement *, const G4LogicalVolume *const)
G4String GenerateName (const G4String &, const void *const)
Protected Member Functions
void DivisionvolWrite (xercesc::DOMElement *, const G4PVDivision *const)
void PhysvolWrite (xercesc::DOMElement *, const G4VPhysicalVolume *const topVol, const G4Transform3D &transform, const G4String &moduleName)
void ReplicavolWrite (xercesc::DOMElement *, const G4VPhysicalVolume *const)
G4Transform3D TraverseVolumeTree (const G4LogicalVolume *const topVol, const G4int depth)
void SurfacesWrite ()
void BorderSurfaceCache (const G4LogicalBorderSurface *const)
void SkinSurfaceCache (const G4LogicalSkinSurface *const)
const G4LogicalBorderSurface * GetBorderSurface (const G4VPhysicalVolume *const)
const G4LogicalSkinSurface * GetSkinSurface (const G4LogicalVolume *const)
G4bool FindOpticalSurface (const G4SurfaceProperty *)
void ExportEnergyCuts (const G4LogicalVolume *const)
void ExportSD (const G4LogicalVolume *const)
Protected Member Functions inherited from G4GDMLWriteParamvol
G4GDMLWriteParamvol ()
virtual ~G4GDMLWriteParamvol ()
void Box_dimensionsWrite (xercesc::DOMElement *, const G4Box *const)
void Trd_dimensionsWrite (xercesc::DOMElement *, const G4Trd *const)
void Trap_dimensionsWrite (xercesc::DOMElement *, const G4Trap *const)
void Tube_dimensionsWrite (xercesc::DOMElement *, const G4Tubs *const)
void Cone_dimensionsWrite (xercesc::DOMElement *, const G4Cons *const)
void Sphere_dimensionsWrite (xercesc::DOMElement *, const G4Sphere *const)
void Orb_dimensionsWrite (xercesc::DOMElement *, const G4Orb *const)
void Torus_dimensionsWrite (xercesc::DOMElement *, const G4Torus *const)
void Ellipsoid_dimensionsWrite (xercesc::DOMElement *, const G4Ellipsoid *const)
void Para_dimensionsWrite (xercesc::DOMElement *, const G4Para *const)
void Hype_dimensionsWrite (xercesc::DOMElement *, const G4Hype *const)
void Polycone_dimensionsWrite (xercesc::DOMElement *, const G4Polycone *const)
void Polyhedra_dimensionsWrite (xercesc::DOMElement *, const G4Polyhedra *const)
void ParametersWrite (xercesc::DOMElement *, const G4VPhysicalVolume *const, const G4int &)
Protected Member Functions inherited from G4GDMLWriteSetup
G4GDMLWriteSetup ()
virtual ~G4GDMLWriteSetup ()
Protected Member Functions inherited from G4GDMLWriteSolids
G4GDMLWriteSolids ()
virtual ~G4GDMLWriteSolids ()
void MultiUnionWrite (xercesc::DOMElement *solElement, const G4MultiUnion *const)
void BooleanWrite (xercesc::DOMElement *, const G4BooleanSolid *const)
void ScaledWrite (xercesc::DOMElement *, const G4ScaledSolid *const)
void BoxWrite (xercesc::DOMElement *, const G4Box *const)
void ConeWrite (xercesc::DOMElement *, const G4Cons *const)
void ElconeWrite (xercesc::DOMElement *, const G4EllipticalCone *const)
void EllipsoidWrite (xercesc::DOMElement *, const G4Ellipsoid *const)
void EltubeWrite (xercesc::DOMElement *, const G4EllipticalTube *const)
void XtruWrite (xercesc::DOMElement *, const G4ExtrudedSolid *const)
void HypeWrite (xercesc::DOMElement *, const G4Hype *const)
void OrbWrite (xercesc::DOMElement *, const G4Orb *const)
void ParaWrite (xercesc::DOMElement *, const G4Para *const)
void ParaboloidWrite (xercesc::DOMElement *, const G4Paraboloid *const)
void PolyconeWrite (xercesc::DOMElement *, const G4Polycone *const)
void GenericPolyconeWrite (xercesc::DOMElement *, const G4GenericPolycone *const)
void PolyhedraWrite (xercesc::DOMElement *, const G4Polyhedra *const)
void SphereWrite (xercesc::DOMElement *, const G4Sphere *const)
void TessellatedWrite (xercesc::DOMElement *, const G4TessellatedSolid *const)
void TetWrite (xercesc::DOMElement *, const G4Tet *const)
void TorusWrite (xercesc::DOMElement *, const G4Torus *const)
void GenTrapWrite (xercesc::DOMElement *, const G4GenericTrap *const)
void TrapWrite (xercesc::DOMElement *, const G4Trap *const)
void TrdWrite (xercesc::DOMElement *, const G4Trd *const)
void TubeWrite (xercesc::DOMElement *, const G4Tubs *const)
void CutTubeWrite (xercesc::DOMElement *, const G4CutTubs *const)
void TwistedboxWrite (xercesc::DOMElement *, const G4TwistedBox *const)
void TwistedtrapWrite (xercesc::DOMElement *, const G4TwistedTrap *const)
void TwistedtrdWrite (xercesc::DOMElement *, const G4TwistedTrd *const)
void TwistedtubsWrite (xercesc::DOMElement *, const G4TwistedTubs *const)
void ZplaneWrite (xercesc::DOMElement *, const G4double &, const G4double &, const G4double &)
void RZPointWrite (xercesc::DOMElement *, const G4double &, const G4double &)
void OpticalSurfaceWrite (xercesc::DOMElement *, const G4OpticalSurface *const)
void PropertyWrite (xercesc::DOMElement *, const G4OpticalSurface *const)
Protected Member Functions inherited from G4GDMLWriteMaterials
G4GDMLWriteMaterials ()
virtual ~G4GDMLWriteMaterials ()
void AtomWrite (xercesc::DOMElement *, const G4double &)
void DWrite (xercesc::DOMElement *, const G4double &)
void PWrite (xercesc::DOMElement *, const G4double &)
void TWrite (xercesc::DOMElement *, const G4double &)
void MEEWrite (xercesc::DOMElement *, const G4double &)
void IsotopeWrite (const G4Isotope *const)
void ElementWrite (const G4Element *const)
void MaterialWrite (const G4Material *const)
void PropertyWrite (xercesc::DOMElement *, const G4Material *const)
void PropertyVectorWrite (const G4String &, const G4PhysicsOrderedFreeVector *const)
Protected Member Functions inherited from G4GDMLWriteDefine
G4GDMLWriteDefine ()
virtual ~G4GDMLWriteDefine ()
void Scale_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
void Rotation_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
void Position_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
Protected Member Functions inherited from G4GDMLWrite
G4GDMLWrite ()
virtual ~G4GDMLWrite ()
VolumeMapType & VolumeMap ()
xercesc::DOMAttr * NewAttribute (const G4String &, const G4String &)
xercesc::DOMAttr * NewAttribute (const G4String &, const G4double &)
xercesc::DOMElement * NewElement (const G4String &)
G4String Modularize (const G4VPhysicalVolume *const topvol, const G4int depth)
void AddAuxInfo (G4GDMLAuxListType *auxInfoList, xercesc::DOMElement *element)
G4bool FileExists (const G4String &) const
PhysVolumeMapType & PvolumeMap ()
DepthMapType & DepthMap ()
Protected Attributes
xercesc::DOMElement * structureElement
std::vector< xercesc::DOMElement * > borderElementVec
std::vector< xercesc::DOMElement * > skinElementVec
std::map< const G4LogicalVolume *, G4GDMLAuxListType > auxmap
Protected Attributes inherited from G4GDMLWriteSolids
std::vector< const G4VSolid * > solidList
xercesc::DOMElement * solidsElement
Protected Attributes inherited from G4GDMLWriteMaterials
std::vector< const G4Isotope * > isotopeList
std::vector< const G4Element * > elementList
std::vector< const G4Material * > materialList
std::vector< const G4PhysicsOrderedFreeVector * > propertyList
xercesc::DOMElement * materialsElement
Protected Attributes inherited from G4GDMLWriteDefine
xercesc::DOMElement * defineElement
Protected Attributes inherited from G4GDMLWrite
G4String SchemaLocation
xercesc::DOMDocument * doc
xercesc::DOMElement * extElement
xercesc::DOMElement * userinfoElement
XMLCh tempStr [10000]
G4GDMLAuxListType auxList
Private Attributes
std::vector< const G4OpticalSurface * > opt_vec
G4ReflectionFactory * reflFactory
G4bool cexport
G4bool sdexport
G4int maxLevel
Static Private Attributes
static G4int levelNo = 0
Additional Inherited Members
Static Public Member Functions inherited from G4GDMLWrite
static void SetAddPointerToName (G4bool)
Static Protected Attributes inherited from G4GDMLWriteSolids
static const G4int maxTransforms = 8
Static Protected Attributes inherited from G4GDMLWriteDefine
static const G4double kRelativePrecision = DBL_EPSILON
static const G4double kAngularPrecision = DBL_EPSILON
static const G4double kLinearPrecision = DBL_EPSILON
Static Protected Attributes inherited from G4GDMLWrite
static G4bool addPointerToName = true
Detailed Description
Definition at line 55 of file G4GDMLWriteStructure.hh.
Constructor & Destructor Documentation
G4GDMLWriteStructure()
G4GDMLWriteStructure::G4GDMLWriteStructure ()
Definition at line 61 of file G4GDMLWriteStructure.cc.
~G4GDMLWriteStructure()
G4GDMLWriteStructure::~G4GDMLWriteStructure () virtual
Definition at line 67 of file G4GDMLWriteStructure.cc.
Member Function Documentation
AddVolumeAuxiliary()
void G4GDMLWriteStructure::AddVolumeAuxiliary (G4GDMLAuxStructType myaux, const G4LogicalVolume * const lvol)
Definition at line 584 of file G4GDMLWriteStructure.cc.
Referenced by ExportEnergyCuts(), and ExportSD().
BorderSurfaceCache()
void G4GDMLWriteStructure::BorderSurfaceCache (const G4LogicalBorderSurface * const bsurf) protected
Definition at line 233 of file G4GDMLWriteStructure.cc.
Referenced by GetBorderSurface().
DivisionvolWrite()
void G4GDMLWriteStructure::DivisionvolWrite (xercesc::DOMElement * volumeElement, const G4PVDivision * const divisionvol) protected
Definition at line 72 of file G4GDMLWriteStructure.cc.
Referenced by TraverseVolumeTree().
ExportEnergyCuts()
void G4GDMLWriteStructure::ExportEnergyCuts (const G4LogicalVolume * const lvol) protected
Definition at line 602 of file G4GDMLWriteStructure.cc.
Referenced by TraverseVolumeTree().
ExportSD()
void G4GDMLWriteStructure::ExportSD (const G4LogicalVolume * const lvol) protected
Definition at line 644 of file G4GDMLWriteStructure.cc.
Referenced by TraverseVolumeTree().
FindOpticalSurface()
G4bool G4GDMLWriteStructure::FindOpticalSurface (const G4SurfaceProperty * psurf) protected
Definition at line 311 of file G4GDMLWriteStructure.cc.
Referenced by BorderSurfaceCache(), and SkinSurfaceCache().
GetBorderSurface()
const G4LogicalBorderSurface * G4GDMLWriteStructure::GetBorderSurface (const G4VPhysicalVolume * const pvol) protected
Definition at line 344 of file G4GDMLWriteStructure.cc.
Referenced by TraverseVolumeTree().
GetMaxExportLevel()
G4int G4GDMLWriteStructure::GetMaxExportLevel () const
Definition at line 658 of file G4GDMLWriteStructure.cc.
GetSkinSurface()
const G4LogicalSkinSurface * G4GDMLWriteStructure::GetSkinSurface (const G4LogicalVolume * const lvol) protected
Definition at line 323 of file G4GDMLWriteStructure.cc.
Referenced by TraverseVolumeTree().
PhysvolWrite()
void G4GDMLWriteStructure::PhysvolWrite (xercesc::DOMElement * volumeElement, const G4VPhysicalVolume *const topVol, const G4Transform3D & transform, const G4String & moduleName) protected
Definition at line 110 of file G4GDMLWriteStructure.cc.
Referenced by TraverseVolumeTree().
ReplicavolWrite()
void G4GDMLWriteStructure::ReplicavolWrite (xercesc::DOMElement * volumeElement, const G4VPhysicalVolume * const replicavol) protected
Definition at line 181 of file G4GDMLWriteStructure.cc.
Referenced by TraverseVolumeTree().
SetEnergyCutsExport()
void G4GDMLWriteStructure::SetEnergyCutsExport (G4bool fcuts)
Definition at line 596 of file G4GDMLWriteStructure.cc.
SetMaxExportLevel()
void G4GDMLWriteStructure::SetMaxExportLevel (G4int level)
Definition at line 664 of file G4GDMLWriteStructure.cc.
SetSDExport()
void G4GDMLWriteStructure::SetSDExport (G4bool fsd)
Definition at line 637 of file G4GDMLWriteStructure.cc.
SkinSurfaceCache()
void G4GDMLWriteStructure::SkinSurfaceCache (const G4LogicalSkinSurface * const ssurf) protected
Definition at line 275 of file G4GDMLWriteStructure.cc.
Referenced by TraverseVolumeTree().
StructureWrite()
void G4GDMLWriteStructure::StructureWrite (xercesc::DOMElement * gdmlElement) virtual
Implements G4GDMLWrite.
Definition at line 381 of file G4GDMLWriteStructure.cc.
SurfacesWrite()
void G4GDMLWriteStructure::SurfacesWrite () protected virtual
Implements G4GDMLWrite.
Definition at line 365 of file G4GDMLWriteStructure.cc.
TraverseVolumeTree()
G4Transform3D G4GDMLWriteStructure::TraverseVolumeTree (const G4LogicalVolume *const topVol, const G4int depth) protected virtual
Implements G4GDMLWrite.
Definition at line 391 of file G4GDMLWriteStructure.cc.
Field Documentation
auxmap
std::map<const G4LogicalVolume*, G4GDMLAuxListType> G4GDMLWriteStructure::auxmap protected
Definition at line 94 of file G4GDMLWriteStructure.hh.
Referenced by AddVolumeAuxiliary(), and TraverseVolumeTree().
borderElementVec
std::vector<xercesc::DOMElement*> G4GDMLWriteStructure::borderElementVec protected
Definition at line 92 of file G4GDMLWriteStructure.hh.
Referenced by BorderSurfaceCache(), and SurfacesWrite().
cexport
G4bool G4GDMLWriteStructure::cexport private
Definition at line 100 of file G4GDMLWriteStructure.hh.
Referenced by SetEnergyCutsExport(), and TraverseVolumeTree().
levelNo
G4int G4GDMLWriteStructure::levelNo = 0 static private
Definition at line 103 of file G4GDMLWriteStructure.hh.
Referenced by SetMaxExportLevel(), and TraverseVolumeTree().
maxLevel
G4int G4GDMLWriteStructure::maxLevel private
Definition at line 102 of file G4GDMLWriteStructure.hh.
Referenced by GetMaxExportLevel(), SetMaxExportLevel(), and TraverseVolumeTree().
opt_vec
std::vector<const G4OpticalSurface*> G4GDMLWriteStructure::opt_vec private
Definition at line 98 of file G4GDMLWriteStructure.hh.
Referenced by FindOpticalSurface().
reflFactory
G4ReflectionFactory* G4GDMLWriteStructure::reflFactory private
Definition at line 99 of file G4GDMLWriteStructure.hh.
Referenced by G4GDMLWriteStructure(), PhysvolWrite(), and TraverseVolumeTree().
sdexport
G4bool G4GDMLWriteStructure::sdexport private
Definition at line 101 of file G4GDMLWriteStructure.hh.
Referenced by SetSDExport(), and TraverseVolumeTree().
skinElementVec
std::vector<xercesc::DOMElement*> G4GDMLWriteStructure::skinElementVec protected
Definition at line 93 of file G4GDMLWriteStructure.hh.
Referenced by SkinSurfaceCache(), and SurfacesWrite().
structureElement
xercesc::DOMElement* G4GDMLWriteStructure::structureElement protected
Definition at line 91 of file G4GDMLWriteStructure.hh.
Referenced by StructureWrite(), SurfacesWrite(), and TraverseVolumeTree().
The documentation for this class was generated from the following files:
source/persistency/gdml/include/G4GDMLWriteStructure.hh
source/persistency/gdml/src/G4GDMLWriteStructure.cc