Geant4: G4LossTableBuilder Class Reference
G4LossTableBuilder Class Reference
#include <G4LossTableBuilder.hh>
Public Member Functions
G4LossTableBuilder ()
virtual ~G4LossTableBuilder ()
void BuildDEDXTable (G4PhysicsTable *dedxTable, const std::vector< G4PhysicsTable * > &)
void BuildRangeTable (const G4PhysicsTable *dedxTable, G4PhysicsTable *rangeTable, G4bool isIonisation=false)
void BuildInverseRangeTable (const G4PhysicsTable *rangeTable, G4PhysicsTable *invRangeTable, G4bool isIonisation=false)
G4PhysicsTable * BuildTableForModel (G4PhysicsTable *table, G4VEmModel *model, const G4ParticleDefinition *, G4double emin, G4double emax, G4bool spline)
void InitialiseBaseMaterials (G4PhysicsTable *table)
const std::vector< G4int > * GetCoupleIndexes ()
const std::vector< G4double > * GetDensityFactors ()
G4bool GetFlag (size_t idx) const
void SetSplineFlag (G4bool flag)
void SetInitialisationFlag (G4bool flag)
Private Member Functions
void InitialiseCouples ()
G4LossTableBuilder & operator= (const G4LossTableBuilder &right)=delete
G4LossTableBuilder (const G4LossTableBuilder &)=delete
Private Attributes
G4EmParameters * theParameters
G4bool splineFlag
G4bool isInitialized
std::vector< G4double > * theDensityFactor
std::vector< G4int > * theDensityIdx
std::vector< G4bool > * theFlag
Detailed Description
Definition at line 61 of file G4LossTableBuilder.hh.
Constructor & Destructor Documentation
G4LossTableBuilder() [1/2]
G4LossTableBuilder::G4LossTableBuilder ()
Definition at line 72 of file G4LossTableBuilder.cc.
~G4LossTableBuilder()
G4LossTableBuilder::~G4LossTableBuilder () virtual
Definition at line 85 of file G4LossTableBuilder.cc.
G4LossTableBuilder() [2/2]
G4LossTableBuilder::G4LossTableBuilder (const G4LossTableBuilder &) private delete
Member Function Documentation
BuildDEDXTable()
void G4LossTableBuilder::BuildDEDXTable (G4PhysicsTable * dedxTable, const std::vector< G4PhysicsTable * > & list)
Definition at line 95 of file G4LossTableBuilder.cc.
Referenced by G4LossTableManager::BuildTables().
BuildInverseRangeTable()
void G4LossTableBuilder::BuildInverseRangeTable (const G4PhysicsTable * rangeTable, G4PhysicsTable * invRangeTable, G4bool isIonisation = false)
Definition at line 217 of file G4LossTableBuilder.cc.
Referenced by G4LossTableManager::BuildTables(), and G4TablesForExtrapolator::Initialisation().
BuildRangeTable()
void G4LossTableBuilder::BuildRangeTable (const G4PhysicsTable * dedxTable, G4PhysicsTable * rangeTable, G4bool isIonisation = false)
Definition at line 130 of file G4LossTableBuilder.cc.
Referenced by G4LossTableManager::BuildTables(), and G4TablesForExtrapolator::Initialisation().
BuildTableForModel()
G4PhysicsTable * G4LossTableBuilder::BuildTableForModel (G4PhysicsTable * table, G4VEmModel * model, const G4ParticleDefinition * part, G4double emin, G4double emax, G4bool spline)
Definition at line 406 of file G4LossTableBuilder.cc.
Referenced by G4VMscModel::GetParticleChangeForMSC().
GetCoupleIndexes()
const std::vector< G4int > * G4LossTableBuilder::GetCoupleIndexes () inline
Definition at line 125 of file G4LossTableBuilder.hh.
Referenced by G4VEnergyLossProcess::BuildLambdaTable(), G4VEmProcess::BuildPhysicsTable(), G4VEnergyLossProcess::BuildPhysicsTable(), G4VMscModel::GetParticleChangeForMSC(), G4VEnergyLossProcess::SetDEDXTable(), and G4VEnergyLossProcess::SetLambdaTable().
GetDensityFactors()
const std::vector< G4double > * G4LossTableBuilder::GetDensityFactors () inline
Definition at line 132 of file G4LossTableBuilder.hh.
Referenced by G4VEnergyLossProcess::BuildLambdaTable(), G4VEmProcess::BuildPhysicsTable(), G4VEnergyLossProcess::BuildPhysicsTable(), G4VMscModel::GetParticleChangeForMSC(), G4VEnergyLossProcess::SetDEDXTable(), and G4VEnergyLossProcess::SetLambdaTable().
GetFlag()
G4bool G4LossTableBuilder::GetFlag (size_t idx) const inline
Definition at line 138 of file G4LossTableBuilder.hh.
Referenced by G4VEnergyLossProcess::BuildDEDXTable(), G4VEnergyLossProcess::BuildLambdaTable(), G4VEmProcess::BuildLambdaTable(), G4GammaGeneralProcess::BuildPhysicsTable(), and BuildTableForModel().
InitialiseBaseMaterials()
void G4LossTableBuilder::InitialiseBaseMaterials (G4PhysicsTable * table)
Definition at line 253 of file G4LossTableBuilder.cc.
Referenced by G4VEmProcess::BuildPhysicsTable(), G4VEnergyLossProcess::BuildPhysicsTable(), BuildTableForModel(), G4VEmProcess::PreparePhysicsTable(), and G4VEnergyLossProcess::PreparePhysicsTable().
InitialiseCouples()
void G4LossTableBuilder::InitialiseCouples () private
Definition at line 339 of file G4LossTableBuilder.cc.
Referenced by GetCoupleIndexes(), and GetDensityFactors().
operator=()
G4LossTableBuilder& G4LossTableBuilder::operator= (const G4LossTableBuilder & right) private delete
SetInitialisationFlag()
void G4LossTableBuilder::SetInitialisationFlag (G4bool flag) inline
Definition at line 148 of file G4LossTableBuilder.hh.
Referenced by G4LossTableManager::ResetParameters().
SetSplineFlag()
void G4LossTableBuilder::SetSplineFlag (G4bool flag) inline
Definition at line 143 of file G4LossTableBuilder.hh.
Referenced by G4LossTableManager::ResetParameters().
Field Documentation
isInitialized
G4bool G4LossTableBuilder::isInitialized private
Definition at line 116 of file G4LossTableBuilder.hh.
Referenced by G4LossTableBuilder(), InitialiseBaseMaterials(), InitialiseCouples(), and SetInitialisationFlag().
splineFlag
G4bool G4LossTableBuilder::splineFlag private
Definition at line 115 of file G4LossTableBuilder.hh.
Referenced by BuildDEDXTable(), BuildInverseRangeTable(), BuildRangeTable(), G4LossTableBuilder(), and SetSplineFlag().
theDensityFactor
std::vector<G4double>* G4LossTableBuilder::theDensityFactor private
Definition at line 118 of file G4LossTableBuilder.hh.
Referenced by G4LossTableBuilder(), GetDensityFactors(), InitialiseBaseMaterials(), InitialiseCouples(), and ~G4LossTableBuilder().
theDensityIdx
std::vector<G4int>* G4LossTableBuilder::theDensityIdx private
Definition at line 119 of file G4LossTableBuilder.hh.
Referenced by G4LossTableBuilder(), GetCoupleIndexes(), GetDensityFactors(), InitialiseBaseMaterials(), InitialiseCouples(), and ~G4LossTableBuilder().
theFlag
std::vector<G4bool>* G4LossTableBuilder::theFlag private
Definition at line 120 of file G4LossTableBuilder.hh.
Referenced by BuildInverseRangeTable(), BuildRangeTable(), G4LossTableBuilder(), GetFlag(), InitialiseBaseMaterials(), InitialiseCouples(), and ~G4LossTableBuilder().
theParameters
G4EmParameters* G4LossTableBuilder::theParameters private
Definition at line 113 of file G4LossTableBuilder.hh.
Referenced by BuildTableForModel(), and G4LossTableBuilder().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/utils/include/G4LossTableBuilder.hh
source/processes/electromagnetic/utils/src/G4LossTableBuilder.cc