Geant4: source/externals/expat/src/xmlparse.cc File Reference
xmlparse.cc File Reference
#include <stddef.h>
#include <string.h>
#include <assert.h>
#include <limits.h>
#include <time.h>
#include "ascii.h"
#include "expat.h"
#include "internal.h"
#include "xmltok.h"
#include "xmlrole.h"
Data Structures
struct NAMED
struct HASH_TABLE
struct HASH_TABLE_ITER
struct binding
struct prefix
struct TAG_NAME
struct tag
struct ENTITY
struct CONTENT_SCAFFOLD
struct block
struct STRING_POOL
struct attribute_id
struct DEFAULT_ATTRIBUTE
struct NS_ATT
struct ELEMENT_TYPE
struct DTD
struct open_internal_entity
struct XML_ParserStruct
Macros
#define XML_BUILDING_EXPAT 1
#define XML_ENCODE_MAX XML_UTF8_ENCODE_MAX
#define XmlConvert XmlUtf8Convert
#define XmlGetInternalEncoding XmlGetUtf8InternalEncoding
#define XmlGetInternalEncodingNS XmlGetUtf8InternalEncodingNS
#define XmlEncode XmlUtf8Encode
#define MUST_CONVERT(enc, s) (!(enc)->isUtf8)
#define XmlInitEncodingNS XmlInitEncoding
#define XmlInitUnknownEncodingNS XmlInitUnknownEncoding
#define XmlGetInternalEncodingNS XmlGetInternalEncoding
#define XmlParseXmlDeclNS XmlParseXmlDecl
#define XML_T(x) x
#define XML_L(x) x
#define ROUND_UP(n, sz) (((n) + ((sz) - 1)) & ~((sz) - 1))
#define CHAR_HASH(h, c) (((h) * 0xF4243) ^ (unsigned char)(c))
#define SECOND_HASH(hash, mask, power) ((((hash) & ~(mask)) >> ((power) - 1)) & ((mask) >> 2))
#define PROBE_STEP(hash, mask, power) ((unsigned char)((SECOND_HASH(hash, mask, power)) | 1))
#define INIT_TAG_BUF_SIZE 32 /* must be a multiple of sizeof(XML_Char) */
#define INIT_DATA_BUF_SIZE 1024
#define INIT_ATTS_SIZE 16
#define INIT_ATTS_VERSION 0xFFFFFFFF
#define INIT_BLOCK_SIZE 1024
#define INIT_BUFFER_SIZE 1024
#define EXPAND_SPARE 24
#define INIT_SCAFFOLD_ELEMENTS 32
#define poolStart(pool) ((pool)->start)
#define poolEnd(pool) ((pool)->ptr)
#define poolLength(pool) ((pool)->ptr - (pool)->start)
#define poolChop(pool) ((void)--(pool->ptr))
#define poolLastChar(pool) (((pool)->ptr)[-1])
#define poolDiscard(pool) ((pool)->ptr = (pool)->start)
#define poolFinish(pool) ((pool)->start = (pool)->ptr)
#define poolAppendChar(pool, c)
#define MALLOC(s) (parser->m_mem.malloc_fcn((s)))
#define REALLOC(p, s) (parser->m_mem.realloc_fcn((p),(s)))
#define FREE(p) (parser->m_mem.free_fcn((p)))
#define userData (parser->m_userData)
#define handlerArg (parser->m_handlerArg)
#define startElementHandler (parser->m_startElementHandler)
#define endElementHandler (parser->m_endElementHandler)
#define characterDataHandler (parser->m_characterDataHandler)
#define processingInstructionHandler (parser->m_processingInstructionHandler)
#define commentHandler (parser->m_commentHandler)
#define startCdataSectionHandler (parser->m_startCdataSectionHandler)
#define endCdataSectionHandler (parser->m_endCdataSectionHandler)
#define defaultHandler (parser->m_defaultHandler)
#define startDoctypeDeclHandler (parser->m_startDoctypeDeclHandler)
#define endDoctypeDeclHandler (parser->m_endDoctypeDeclHandler)
#define unparsedEntityDeclHandler (parser->m_unparsedEntityDeclHandler)
#define notationDeclHandler (parser->m_notationDeclHandler)
#define startNamespaceDeclHandler (parser->m_startNamespaceDeclHandler)
#define endNamespaceDeclHandler (parser->m_endNamespaceDeclHandler)
#define notStandaloneHandler (parser->m_notStandaloneHandler)
#define externalEntityRefHandler (parser->m_externalEntityRefHandler)
#define externalEntityRefHandlerArg (parser->m_externalEntityRefHandlerArg)
#define internalEntityRefHandler (parser->m_internalEntityRefHandler)
#define skippedEntityHandler (parser->m_skippedEntityHandler)
#define unknownEncodingHandler (parser->m_unknownEncodingHandler)
#define elementDeclHandler (parser->m_elementDeclHandler)
#define attlistDeclHandler (parser->m_attlistDeclHandler)
#define entityDeclHandler (parser->m_entityDeclHandler)
#define xmlDeclHandler (parser->m_xmlDeclHandler)
#define encoding (parser->m_encoding)
#define initEncoding (parser->m_initEncoding)
#define internalEncoding (parser->m_internalEncoding)
#define unknownEncodingMem (parser->m_unknownEncodingMem)
#define unknownEncodingData (parser->m_unknownEncodingData)
#define unknownEncodingHandlerData (parser->m_unknownEncodingHandlerData)
#define unknownEncodingRelease (parser->m_unknownEncodingRelease)
#define protocolEncodingName (parser->m_protocolEncodingName)
#define ns (parser->m_ns)
#define ns_triplets (parser->m_ns_triplets)
#define prologState (parser->m_prologState)
#define processor (parser->m_processor)
#define errorCode (parser->m_errorCode)
#define eventPtr (parser->m_eventPtr)
#define eventEndPtr (parser->m_eventEndPtr)
#define positionPtr (parser->m_positionPtr)
#define position (parser->m_position)
#define openInternalEntities (parser->m_openInternalEntities)
#define freeInternalEntities (parser->m_freeInternalEntities)
#define defaultExpandInternalEntities (parser->m_defaultExpandInternalEntities)
#define tagLevel (parser->m_tagLevel)
#define buffer (parser->m_buffer)
#define bufferPtr (parser->m_bufferPtr)
#define bufferEnd (parser->m_bufferEnd)
#define parseEndByteIndex (parser->m_parseEndByteIndex)
#define parseEndPtr (parser->m_parseEndPtr)
#define bufferLim (parser->m_bufferLim)
#define dataBuf (parser->m_dataBuf)
#define dataBufEnd (parser->m_dataBufEnd)
#define _dtd (parser->m_dtd)
#define curBase (parser->m_curBase)
#define declEntity (parser->m_declEntity)
#define doctypeName (parser->m_doctypeName)
#define doctypeSysid (parser->m_doctypeSysid)
#define doctypePubid (parser->m_doctypePubid)
#define declAttributeType (parser->m_declAttributeType)
#define declNotationName (parser->m_declNotationName)
#define declNotationPublicId (parser->m_declNotationPublicId)
#define declElementType (parser->m_declElementType)
#define declAttributeId (parser->m_declAttributeId)
#define declAttributeIsCdata (parser->m_declAttributeIsCdata)
#define declAttributeIsId (parser->m_declAttributeIsId)
#define freeTagList (parser->m_freeTagList)
#define freeBindingList (parser->m_freeBindingList)
#define inheritedBindings (parser->m_inheritedBindings)
#define tagStack (parser->m_tagStack)
#define atts (parser->m_atts)
#define attsSize (parser->m_attsSize)
#define nSpecifiedAtts (parser->m_nSpecifiedAtts)
#define idAttIndex (parser->m_idAttIndex)
#define nsAtts (parser->m_nsAtts)
#define nsAttsVersion (parser->m_nsAttsVersion)
#define nsAttsPower (parser->m_nsAttsPower)
#define attInfo (parser->m_attInfo)
#define tempPool (parser->m_tempPool)
#define temp2Pool (parser->m_temp2Pool)
#define groupConnector (parser->m_groupConnector)
#define groupSize (parser->m_groupSize)
#define namespaceSeparator (parser->m_namespaceSeparator)
#define parentParser (parser->m_parentParser)
#define ps_parsing (parser->m_parsingStatus.parsing)
#define ps_finalBuffer (parser->m_parsingStatus.finalBuffer)
#define hash_secret_salt (parser->m_hash_secret_salt)
#define V1(a, b, c) XML_L(#a)XML_L(".")XML_L(#b)XML_L(".")XML_L(#c)
#define V2(a, b, c) XML_L("expat_")V1(a,b,c)
#define CONTEXT_SEP XML_T(ASCII_FF)
#define INIT_POWER 6
Typedefs
typedef char ICHAR
typedef struct binding BINDING
typedef struct prefix PREFIX
typedef struct tag TAG
typedef struct block BLOCK
typedef struct attribute_id ATTRIBUTE_ID
typedef struct open_internal_entity OPEN_INTERNAL_ENTITY
Functions
enum XML_Error PTRCALL Processor (XML_Parser parser, const char *start, const char *end, const char **endPtr)
static enum XML_Error handleUnknownEncoding (XML_Parser parser, const XML_Char *encodingName)
static enum XML_Error processXmlDecl (XML_Parser parser, int isGeneralTextEntity, const char *s, const char *next)
static enum XML_Error initializeEncoding (XML_Parser parser)
static enum XML_Error doProlog (XML_Parser parser, const ENCODING *enc, const char *s, const char *end, int tok, const char *next, const char **nextPtr, XML_Bool haveMore)
static enum XML_Error processInternalEntity (XML_Parser parser, ENTITY *entity, XML_Bool betweenDecl)
static enum XML_Error doContent (XML_Parser parser, int startTagLevel, const ENCODING *enc, const char *start, const char *end, const char **endPtr, XML_Bool haveMore)
static enum XML_Error doCdataSection (XML_Parser parser, const ENCODING *, const char **startPtr, const char *end, const char **nextPtr, XML_Bool haveMore)
static enum XML_Error storeAtts (XML_Parser parser, const ENCODING *, const char *s, TAG_NAME *tagNamePtr, BINDING **bindingsPtr)
static enum XML_Error addBinding (XML_Parser parser, PREFIX *prefix, const ATTRIBUTE_ID *attId, const XML_Char *uri, BINDING **bindingsPtr)
static int defineAttribute (ELEMENT_TYPE *type, ATTRIBUTE_ID *, XML_Bool isCdata, XML_Bool isId, const XML_Char *dfltValue, XML_Parser parser)
static enum XML_Error storeAttributeValue (XML_Parser parser, const ENCODING *, XML_Bool isCdata, const char *, const char *, STRING_POOL *)
static enum XML_Error appendAttributeValue (XML_Parser parser, const ENCODING *, XML_Bool isCdata, const char *, const char *, STRING_POOL *)
static ATTRIBUTE_ID * getAttributeId (XML_Parser parser, const ENCODING *enc, const char *start, const char *end)
static int setElementTypePrefix (XML_Parser parser, ELEMENT_TYPE *)
static enum XML_Error storeEntityValue (XML_Parser parser, const ENCODING *enc, const char *start, const char *end)
static int reportProcessingInstruction (XML_Parser parser, const ENCODING *enc, const char *start, const char *end)
static int reportComment (XML_Parser parser, const ENCODING *enc, const char *start, const char *end)
static void reportDefault (XML_Parser parser, const ENCODING *enc, const char *start, const char *end)
static const XML_Char * getContext (XML_Parser parser)
static XML_Bool setContext (XML_Parser parser, const XML_Char *context)
static void FASTCALL normalizePublicId (XML_Char *s)
static DTD * dtdCreate (const XML_Memory_Handling_Suite *ms)
static void dtdReset (DTD *p, const XML_Memory_Handling_Suite *ms)
static void dtdDestroy (DTD *p, XML_Bool isDocEntity, const XML_Memory_Handling_Suite *ms)
static int dtdCopy (XML_Parser oldParser, DTD *newDtd, const DTD *oldDtd, const XML_Memory_Handling_Suite *ms)
static int copyEntityTable (XML_Parser oldParser, HASH_TABLE *, STRING_POOL *, const HASH_TABLE *)
static NAMED * lookup (XML_Parser parser, HASH_TABLE *table, KEY name, size_t createSize)
static void FASTCALL hashTableInit (HASH_TABLE *, const XML_Memory_Handling_Suite *ms)
static void FASTCALL hashTableClear (HASH_TABLE *)
static void FASTCALL hashTableDestroy (HASH_TABLE *)
static void FASTCALL hashTableIterInit (HASH_TABLE_ITER *, const HASH_TABLE *)
static NAMED *FASTCALL hashTableIterNext (HASH_TABLE_ITER *)
static void FASTCALL poolInit (STRING_POOL *, const XML_Memory_Handling_Suite *ms)
static void FASTCALL poolClear (STRING_POOL *)
static void FASTCALL poolDestroy (STRING_POOL *)
static XML_Char * poolAppend (STRING_POOL *pool, const ENCODING *enc, const char *ptr, const char *end)
static XML_Char * poolStoreString (STRING_POOL *pool, const ENCODING *enc, const char *ptr, const char *end)
static XML_Bool FASTCALL poolGrow (STRING_POOL *pool)
static const XML_Char *FASTCALL poolCopyString (STRING_POOL *pool, const XML_Char *s)
static const XML_Char * poolCopyStringN (STRING_POOL *pool, const XML_Char *s, int n)
static const XML_Char *FASTCALL poolAppendString (STRING_POOL *pool, const XML_Char *s)
static int FASTCALL nextScaffoldPart (XML_Parser parser)
static XML_Content * build_model (XML_Parser parser)
static ELEMENT_TYPE * getElementType (XML_Parser parser, const ENCODING *enc, const char *ptr, const char *end)
static unsigned long generate_hash_secret_salt (void)
static XML_Bool startParsing (XML_Parser parser)
static XML_Parser parserCreate (const XML_Char *encodingName, const XML_Memory_Handling_Suite *memsuite, const XML_Char *nameSep, DTD *dtd)
static void parserInit (XML_Parser parser, const XML_Char *encodingName)
XML_Parser XMLCALL XML_ParserCreate (const XML_Char *encodingName)
XML_Parser XMLCALL XML_ParserCreateNS (const XML_Char *encodingName, XML_Char nsSep)
XML_Parser XMLCALL XML_ParserCreate_MM (const XML_Char *encodingName, const XML_Memory_Handling_Suite *memsuite, const XML_Char *nameSep)
static void FASTCALL moveToFreeBindingList (XML_Parser parser, BINDING *bindings)
XML_Bool XMLCALL XML_ParserReset (XML_Parser parser, const XML_Char *encodingName)
enum XML_Status XMLCALL XML_SetEncoding (XML_Parser parser, const XML_Char *encodingName)
XML_Parser XMLCALL XML_ExternalEntityParserCreate (XML_Parser oldParser, const XML_Char *context, const XML_Char *encodingName)
static void FASTCALL destroyBindings (BINDING *bindings, XML_Parser parser)
void XMLCALL XML_ParserFree (XML_Parser parser)
void XMLCALL XML_UseParserAsHandlerArg (XML_Parser parser)
enum XML_Error XMLCALL XML_UseForeignDTD (XML_Parser parser, XML_Bool useDTD)
void XMLCALL XML_SetReturnNSTriplet (XML_Parser parser, int do_nst)
void XMLCALL XML_SetUserData (XML_Parser parser, void *p)
enum XML_Status XMLCALL XML_SetBase (XML_Parser parser, const XML_Char *p)
const XML_Char *XMLCALL XML_GetBase (XML_Parser parser)
int XMLCALL XML_GetSpecifiedAttributeCount (XML_Parser parser)
int XMLCALL XML_GetIdAttributeIndex (XML_Parser parser)
void XMLCALL XML_SetElementHandler (XML_Parser parser, XML_StartElementHandler start, XML_EndElementHandler end)
void XMLCALL XML_SetStartElementHandler (XML_Parser parser, XML_StartElementHandler start)
void XMLCALL XML_SetEndElementHandler (XML_Parser parser, XML_EndElementHandler end)
void XMLCALL XML_SetCharacterDataHandler (XML_Parser parser, XML_CharacterDataHandler handler)
void XMLCALL XML_SetProcessingInstructionHandler (XML_Parser parser, XML_ProcessingInstructionHandler handler)
void XMLCALL XML_SetCommentHandler (XML_Parser parser, XML_CommentHandler handler)
void XMLCALL XML_SetCdataSectionHandler (XML_Parser parser, XML_StartCdataSectionHandler start, XML_EndCdataSectionHandler end)
void XMLCALL XML_SetStartCdataSectionHandler (XML_Parser parser, XML_StartCdataSectionHandler start)
void XMLCALL XML_SetEndCdataSectionHandler (XML_Parser parser, XML_EndCdataSectionHandler end)
void XMLCALL XML_SetDefaultHandler (XML_Parser parser, XML_DefaultHandler handler)
void XMLCALL XML_SetDefaultHandlerExpand (XML_Parser parser, XML_DefaultHandler handler)
void XMLCALL XML_SetDoctypeDeclHandler (XML_Parser parser, XML_StartDoctypeDeclHandler start, XML_EndDoctypeDeclHandler end)
void XMLCALL XML_SetStartDoctypeDeclHandler (XML_Parser parser, XML_StartDoctypeDeclHandler start)
void XMLCALL XML_SetEndDoctypeDeclHandler (XML_Parser parser, XML_EndDoctypeDeclHandler end)
void XMLCALL XML_SetUnparsedEntityDeclHandler (XML_Parser parser, XML_UnparsedEntityDeclHandler handler)
void XMLCALL XML_SetNotationDeclHandler (XML_Parser parser, XML_NotationDeclHandler handler)
void XMLCALL XML_SetNamespaceDeclHandler (XML_Parser parser, XML_StartNamespaceDeclHandler start, XML_EndNamespaceDeclHandler end)
void XMLCALL XML_SetStartNamespaceDeclHandler (XML_Parser parser, XML_StartNamespaceDeclHandler start)
void XMLCALL XML_SetEndNamespaceDeclHandler (XML_Parser parser, XML_EndNamespaceDeclHandler end)
void XMLCALL XML_SetNotStandaloneHandler (XML_Parser parser, XML_NotStandaloneHandler handler)
void XMLCALL XML_SetExternalEntityRefHandler (XML_Parser parser, XML_ExternalEntityRefHandler handler)
void XMLCALL XML_SetExternalEntityRefHandlerArg (XML_Parser parser, void *arg)
void XMLCALL XML_SetSkippedEntityHandler (XML_Parser parser, XML_SkippedEntityHandler handler)
void XMLCALL XML_SetUnknownEncodingHandler (XML_Parser parser, XML_UnknownEncodingHandler handler, void *data)
void XMLCALL XML_SetElementDeclHandler (XML_Parser parser, XML_ElementDeclHandler eldecl)
void XMLCALL XML_SetAttlistDeclHandler (XML_Parser parser, XML_AttlistDeclHandler attdecl)
void XMLCALL XML_SetEntityDeclHandler (XML_Parser parser, XML_EntityDeclHandler handler)
void XMLCALL XML_SetXmlDeclHandler (XML_Parser parser, XML_XmlDeclHandler handler)
int XMLCALL XML_SetParamEntityParsing (XML_Parser parser, enum XML_ParamEntityParsing peParsing)
int XMLCALL XML_SetHashSalt (XML_Parser parser, unsigned long hash_salt)
enum XML_Status XMLCALL XML_Parse (XML_Parser parser, const char *s, int len, int isFinal)
enum XML_Status XMLCALL XML_ParseBuffer (XML_Parser parser, int len, int isFinal)
void *XMLCALL XML_GetBuffer (XML_Parser parser, int len)
enum XML_Status XMLCALL XML_StopParser (XML_Parser parser, XML_Bool resumable)
enum XML_Status XMLCALL XML_ResumeParser (XML_Parser parser)
void XMLCALL XML_GetParsingStatus (XML_Parser parser, XML_ParsingStatus *status)
enum XML_Error XMLCALL XML_GetErrorCode (XML_Parser parser)
XML_Index XMLCALL XML_GetCurrentByteIndex (XML_Parser parser)
int XMLCALL XML_GetCurrentByteCount (XML_Parser parser)
const char *XMLCALL XML_GetInputContext (XML_Parser parser, int *offset, int *size)
XML_Size XMLCALL XML_GetCurrentLineNumber (XML_Parser parser)
XML_Size XMLCALL XML_GetCurrentColumnNumber (XML_Parser parser)
void XMLCALL XML_FreeContentModel (XML_Parser parser, XML_Content *model)
void *XMLCALL XML_MemMalloc (XML_Parser parser, size_t size)
void *XMLCALL XML_MemRealloc (XML_Parser parser, void *ptr, size_t size)
void XMLCALL XML_MemFree (XML_Parser parser, void *ptr)
void XMLCALL XML_DefaultCurrent (XML_Parser parser)
const XML_LChar *XMLCALL XML_ErrorString (enum XML_Error code)
const XML_LChar *XMLCALL XML_ExpatVersion (void)
XML_Expat_Version XMLCALL XML_ExpatVersionInfo (void)
const XML_Feature *XMLCALL XML_GetFeatureList (void)
static XML_Bool storeRawNames (XML_Parser parser)
static enum XML_Error PTRCALL contentProcessor (XML_Parser parser, const char *start, const char *end, const char **endPtr)
static enum XML_Error PTRCALL externalEntityInitProcessor (XML_Parser parser, const char *start, const char *end, const char **endPtr)
static enum XML_Error PTRCALL externalEntityInitProcessor2 (XML_Parser parser, const char *start, const char *end, const char **endPtr)
static enum XML_Error PTRCALL externalEntityInitProcessor3 (XML_Parser parser, const char *start, const char *end, const char **endPtr)
static enum XML_Error PTRCALL externalEntityContentProcessor (XML_Parser parser, const char *start, const char *end, const char **endPtr)
static enum XML_Error PTRCALL cdataSectionProcessor (XML_Parser parser, const char *start, const char *end, const char **endPtr)
static enum XML_Error PTRCALL prologInitProcessor (XML_Parser parser, const char *s, const char *end, const char **nextPtr)
static enum XML_Error PTRCALL prologProcessor (XML_Parser parser, const char *s, const char *end, const char **nextPtr)
static enum XML_Error PTRCALL epilogProcessor (XML_Parser parser, const char *s, const char *end, const char **nextPtr)
static enum XML_Error PTRCALL internalEntityProcessor (XML_Parser parser, const char *s, const char *end, const char **nextPtr)
static enum XML_Error PTRCALL errorProcessor (XML_Parser parser, const char *s, const char *end, const char **nextPtr)
static void FASTCALL normalizeLines (XML_Char *s)
static XML_Bool FASTCALL keyeq (KEY s1, KEY s2)
static unsigned long FASTCALL hash (XML_Parser parser, KEY s)
static void build_node (XML_Parser parser, int src_node, XML_Content *dest, XML_Content **contpos, XML_Char **strpos)
Variables
const typedef XML_Char * KEY
static Processor prologProcessor
static Processor prologInitProcessor
static Processor contentProcessor
static Processor cdataSectionProcessor
static Processor epilogProcessor
static Processor errorProcessor
static Processor externalEntityInitProcessor
static Processor externalEntityInitProcessor2
static Processor externalEntityInitProcessor3
static Processor externalEntityContentProcessor
static Processor internalEntityProcessor
static const XML_Char implicitContext []
Macro Definition Documentation
_dtd
#define _dtd (parser->m_dtd)
Definition at line 636 of file xmlparse.cc.
attInfo
#define attInfo (parser->m_attInfo)
Definition at line 660 of file xmlparse.cc.
attlistDeclHandler
#define attlistDeclHandler (parser->m_attlistDeclHandler)
Definition at line 602 of file xmlparse.cc.
atts
#define atts (parser->m_atts)
Definition at line 653 of file xmlparse.cc.
attsSize
#define attsSize (parser->m_attsSize)
Definition at line 654 of file xmlparse.cc.
buffer
#define buffer (parser->m_buffer)
Definition at line 628 of file xmlparse.cc.
bufferEnd
#define bufferEnd (parser->m_bufferEnd)
Definition at line 630 of file xmlparse.cc.
bufferLim
#define bufferLim (parser->m_bufferLim)
Definition at line 633 of file xmlparse.cc.
bufferPtr
#define bufferPtr (parser->m_bufferPtr)
Definition at line 629 of file xmlparse.cc.
CHAR_HASH
#define CHAR_HASH (h, c) (((h) * 0xF4243) ^ (unsigned char)(c))
Definition at line 119 of file xmlparse.cc.
characterDataHandler
#define characterDataHandler (parser->m_characterDataHandler)
Definition at line 576 of file xmlparse.cc.
commentHandler
#define commentHandler (parser->m_commentHandler)
Definition at line 579 of file xmlparse.cc.
CONTEXT_SEP
#define CONTEXT_SEP XML_T(ASCII_FF)
Definition at line 5496 of file xmlparse.cc.
curBase
#define curBase (parser->m_curBase)
Definition at line 637 of file xmlparse.cc.
dataBuf
#define dataBuf (parser->m_dataBuf)
Definition at line 634 of file xmlparse.cc.
dataBufEnd
#define dataBufEnd (parser->m_dataBufEnd)
Definition at line 635 of file xmlparse.cc.
declAttributeId
#define declAttributeId (parser->m_declAttributeId)
Definition at line 646 of file xmlparse.cc.
declAttributeIsCdata
#define declAttributeIsCdata (parser->m_declAttributeIsCdata)
Definition at line 647 of file xmlparse.cc.
declAttributeIsId
#define declAttributeIsId (parser->m_declAttributeIsId)
Definition at line 648 of file xmlparse.cc.
declAttributeType
#define declAttributeType (parser->m_declAttributeType)
Definition at line 642 of file xmlparse.cc.
declElementType
#define declElementType (parser->m_declElementType)
Definition at line 645 of file xmlparse.cc.
declEntity
#define declEntity (parser->m_declEntity)
Definition at line 638 of file xmlparse.cc.
declNotationName
#define declNotationName (parser->m_declNotationName)
Definition at line 643 of file xmlparse.cc.
declNotationPublicId
#define declNotationPublicId (parser->m_declNotationPublicId)
Definition at line 644 of file xmlparse.cc.
defaultExpandInternalEntities
#define defaultExpandInternalEntities (parser->m_defaultExpandInternalEntities)
Definition at line 625 of file xmlparse.cc.
defaultHandler
#define defaultHandler (parser->m_defaultHandler)
Definition at line 583 of file xmlparse.cc.
doctypeName
#define doctypeName (parser->m_doctypeName)
Definition at line 639 of file xmlparse.cc.
doctypePubid
#define doctypePubid (parser->m_doctypePubid)
Definition at line 641 of file xmlparse.cc.
doctypeSysid
#define doctypeSysid (parser->m_doctypeSysid)
Definition at line 640 of file xmlparse.cc.
elementDeclHandler
#define elementDeclHandler (parser->m_elementDeclHandler)
Definition at line 601 of file xmlparse.cc.
encoding
#define encoding (parser->m_encoding)
Definition at line 605 of file xmlparse.cc.
endCdataSectionHandler
#define endCdataSectionHandler (parser->m_endCdataSectionHandler)
Definition at line 582 of file xmlparse.cc.
endDoctypeDeclHandler
#define endDoctypeDeclHandler (parser->m_endDoctypeDeclHandler)
Definition at line 585 of file xmlparse.cc.
endElementHandler
#define endElementHandler (parser->m_endElementHandler)
Definition at line 575 of file xmlparse.cc.
endNamespaceDeclHandler
#define endNamespaceDeclHandler (parser->m_endNamespaceDeclHandler)
Definition at line 591 of file xmlparse.cc.
entityDeclHandler
#define entityDeclHandler (parser->m_entityDeclHandler)
Definition at line 603 of file xmlparse.cc.
errorCode
#define errorCode (parser->m_errorCode)
Definition at line 618 of file xmlparse.cc.
eventEndPtr
#define eventEndPtr (parser->m_eventEndPtr)
Definition at line 620 of file xmlparse.cc.
eventPtr
#define eventPtr (parser->m_eventPtr)
Definition at line 619 of file xmlparse.cc.
EXPAND_SPARE
#define EXPAND_SPARE 24
Definition at line 148 of file xmlparse.cc.
externalEntityRefHandler
#define externalEntityRefHandler (parser->m_externalEntityRefHandler)
Definition at line 593 of file xmlparse.cc.
externalEntityRefHandlerArg
#define externalEntityRefHandlerArg (parser->m_externalEntityRefHandlerArg)
Definition at line 595 of file xmlparse.cc.
FREE
#define FREE (p) (parser->m_mem.free_fcn((p)))
Definition at line 570 of file xmlparse.cc.
freeBindingList
#define freeBindingList (parser->m_freeBindingList)
Definition at line 650 of file xmlparse.cc.
freeInternalEntities
#define freeInternalEntities (parser->m_freeInternalEntities)
Definition at line 624 of file xmlparse.cc.
freeTagList
#define freeTagList (parser->m_freeTagList)
Definition at line 649 of file xmlparse.cc.
groupConnector
#define groupConnector (parser->m_groupConnector)
Definition at line 663 of file xmlparse.cc.
groupSize
#define groupSize (parser->m_groupSize)
Definition at line 664 of file xmlparse.cc.
handlerArg
#define handlerArg (parser->m_handlerArg)
Definition at line 573 of file xmlparse.cc.
hash_secret_salt
#define hash_secret_salt (parser->m_hash_secret_salt)
Definition at line 674 of file xmlparse.cc.
idAttIndex
#define idAttIndex (parser->m_idAttIndex)
Definition at line 656 of file xmlparse.cc.
inheritedBindings
#define inheritedBindings (parser->m_inheritedBindings)
Definition at line 651 of file xmlparse.cc.
INIT_ATTS_SIZE
#define INIT_ATTS_SIZE 16
Definition at line 143 of file xmlparse.cc.
INIT_ATTS_VERSION
#define INIT_ATTS_VERSION 0xFFFFFFFF
Definition at line 144 of file xmlparse.cc.
INIT_BLOCK_SIZE
#define INIT_BLOCK_SIZE 1024
Definition at line 145 of file xmlparse.cc.
INIT_BUFFER_SIZE
#define INIT_BUFFER_SIZE 1024
Definition at line 146 of file xmlparse.cc.
INIT_DATA_BUF_SIZE
#define INIT_DATA_BUF_SIZE 1024
Definition at line 142 of file xmlparse.cc.
INIT_POWER
#define INIT_POWER 6
Definition at line 5955 of file xmlparse.cc.
INIT_SCAFFOLD_ELEMENTS
#define INIT_SCAFFOLD_ELEMENTS 32
Definition at line 221 of file xmlparse.cc.
INIT_TAG_BUF_SIZE
#define INIT_TAG_BUF_SIZE 32 /* must be a multiple of sizeof(XML_Char) */
Definition at line 141 of file xmlparse.cc.
initEncoding
#define initEncoding (parser->m_initEncoding)
Definition at line 606 of file xmlparse.cc.
internalEncoding
#define internalEncoding (parser->m_internalEncoding)
Definition at line 607 of file xmlparse.cc.
internalEntityRefHandler
#define internalEntityRefHandler (parser->m_internalEntityRefHandler)
Definition at line 597 of file xmlparse.cc.
MALLOC
#define MALLOC (s) (parser->m_mem.malloc_fcn((s)))
Definition at line 568 of file xmlparse.cc.
MUST_CONVERT
#define MUST_CONVERT (enc, s) (!(enc)->isUtf8)
Definition at line 49 of file xmlparse.cc.
namespaceSeparator
#define namespaceSeparator (parser->m_namespaceSeparator)
Definition at line 665 of file xmlparse.cc.
notationDeclHandler
#define notationDeclHandler (parser->m_notationDeclHandler)
Definition at line 588 of file xmlparse.cc.
notStandaloneHandler
#define notStandaloneHandler (parser->m_notStandaloneHandler)
Definition at line 592 of file xmlparse.cc.
ns
#define ns (parser->m_ns)
Definition at line 614 of file xmlparse.cc.
ns_triplets
#define ns_triplets (parser->m_ns_triplets)
Definition at line 615 of file xmlparse.cc.
nsAtts
#define nsAtts (parser->m_nsAtts)
Definition at line 657 of file xmlparse.cc.
nsAttsPower
#define nsAttsPower (parser->m_nsAttsPower)
Definition at line 659 of file xmlparse.cc.
nsAttsVersion
#define nsAttsVersion (parser->m_nsAttsVersion)
Definition at line 658 of file xmlparse.cc.
nSpecifiedAtts
#define nSpecifiedAtts (parser->m_nSpecifiedAtts)
Definition at line 655 of file xmlparse.cc.
openInternalEntities
#define openInternalEntities (parser->m_openInternalEntities)
Definition at line 623 of file xmlparse.cc.
parentParser
#define parentParser (parser->m_parentParser)
Definition at line 666 of file xmlparse.cc.
parseEndByteIndex
#define parseEndByteIndex (parser->m_parseEndByteIndex)
Definition at line 631 of file xmlparse.cc.
parseEndPtr
#define parseEndPtr (parser->m_parseEndPtr)
Definition at line 632 of file xmlparse.cc.
poolAppendChar
#define poolAppendChar (pool, c)
Value:
(((pool)->ptr == (pool)->end && !poolGrow(pool)) \
   ? 0 \
   : ((*((pool)->ptr)++ = c), 1))
Definition at line 460 of file xmlparse.cc.
poolChop
#define poolChop (pool) ((void)--(pool->ptr))
Definition at line 456 of file xmlparse.cc.
poolDiscard
#define poolDiscard (pool) ((pool)->ptr = (pool)->start)
Definition at line 458 of file xmlparse.cc.
poolEnd
#define poolEnd (pool) ((pool)->ptr)
Definition at line 454 of file xmlparse.cc.
poolFinish
#define poolFinish (pool) ((pool)->start = (pool)->ptr)
Definition at line 459 of file xmlparse.cc.
poolLastChar
#define poolLastChar (pool) (((pool)->ptr)[-1])
Definition at line 457 of file xmlparse.cc.
poolLength
#define poolLength (pool) ((pool)->ptr - (pool)->start)
Definition at line 455 of file xmlparse.cc.
poolStart
#define poolStart (pool) ((pool)->start)
Definition at line 453 of file xmlparse.cc.
position
#define position (parser->m_position)
Definition at line 622 of file xmlparse.cc.
positionPtr
#define positionPtr (parser->m_positionPtr)
Definition at line 621 of file xmlparse.cc.
PROBE_STEP
#define PROBE_STEP (hash, mask, power) ((unsigned char)((SECOND_HASH(hash, mask, power)) | 1))
Definition at line 133 of file xmlparse.cc.
processingInstructionHandler
#define processingInstructionHandler (parser->m_processingInstructionHandler)
Definition at line 577 of file xmlparse.cc.
processor
#define processor (parser->m_processor)
Definition at line 617 of file xmlparse.cc.
prologState
#define prologState (parser->m_prologState)
Definition at line 616 of file xmlparse.cc.
protocolEncodingName
#define protocolEncodingName (parser->m_protocolEncodingName)
Definition at line 613 of file xmlparse.cc.
ps_finalBuffer
#define ps_finalBuffer (parser->m_parsingStatus.finalBuffer)
Definition at line 668 of file xmlparse.cc.
ps_parsing
#define ps_parsing (parser->m_parsingStatus.parsing)
Definition at line 667 of file xmlparse.cc.
REALLOC
#define REALLOC (p, s) (parser->m_mem.realloc_fcn((p),(s)))
Definition at line 569 of file xmlparse.cc.
ROUND_UP
#define ROUND_UP (n, sz) (((n) + ((sz) - 1)) & ~((sz) - 1))
Definition at line 82 of file xmlparse.cc.
SECOND_HASH
#define SECOND_HASH (hash, mask, power) ((((hash) & ~(mask)) >> ((power) - 1)) & ((mask) >> 2))
Definition at line 131 of file xmlparse.cc.
skippedEntityHandler
#define skippedEntityHandler (parser->m_skippedEntityHandler)
Definition at line 599 of file xmlparse.cc.
startCdataSectionHandler
#define startCdataSectionHandler (parser->m_startCdataSectionHandler)
Definition at line 580 of file xmlparse.cc.
startDoctypeDeclHandler
#define startDoctypeDeclHandler (parser->m_startDoctypeDeclHandler)
Definition at line 584 of file xmlparse.cc.
startElementHandler
#define startElementHandler (parser->m_startElementHandler)
Definition at line 574 of file xmlparse.cc.
startNamespaceDeclHandler
#define startNamespaceDeclHandler (parser->m_startNamespaceDeclHandler)
Definition at line 589 of file xmlparse.cc.
tagLevel
#define tagLevel (parser->m_tagLevel)
Definition at line 627 of file xmlparse.cc.
tagStack
#define tagStack (parser->m_tagStack)
Definition at line 652 of file xmlparse.cc.
temp2Pool
#define temp2Pool (parser->m_temp2Pool)
Definition at line 662 of file xmlparse.cc.
tempPool
#define tempPool (parser->m_tempPool)
Definition at line 661 of file xmlparse.cc.
unknownEncodingData
#define unknownEncodingData (parser->m_unknownEncodingData)
Definition at line 609 of file xmlparse.cc.
unknownEncodingHandler
#define unknownEncodingHandler (parser->m_unknownEncodingHandler)
Definition at line 600 of file xmlparse.cc.
unknownEncodingHandlerData
#define unknownEncodingHandlerData (parser->m_unknownEncodingHandlerData)
Definition at line 610 of file xmlparse.cc.
unknownEncodingMem
#define unknownEncodingMem (parser->m_unknownEncodingMem)
Definition at line 608 of file xmlparse.cc.
unknownEncodingRelease
#define unknownEncodingRelease (parser->m_unknownEncodingRelease)
Definition at line 612 of file xmlparse.cc.
unparsedEntityDeclHandler
#define unparsedEntityDeclHandler (parser->m_unparsedEntityDeclHandler)
Definition at line 586 of file xmlparse.cc.
userData
#define userData (parser->m_userData)
Definition at line 572 of file xmlparse.cc.
V1
#define V1 (a, b, c) XML_L(#a)XML_L(".")XML_L(#b)XML_L(".")XML_L(#c)
V2
#define V2 (a, b, c) XML_L("expat_")V1(a,b,c)
XML_BUILDING_EXPAT
#define XML_BUILDING_EXPAT 1
Definition at line 17 of file xmlparse.cc.
XML_ENCODE_MAX
#define XML_ENCODE_MAX XML_UTF8_ENCODE_MAX
Definition at line 44 of file xmlparse.cc.
XML_L
#define XML_L (x) x
Definition at line 77 of file xmlparse.cc.
XML_T
#define XML_T (x) x
Definition at line 76 of file xmlparse.cc.
XmlConvert
#define XmlConvert XmlUtf8Convert
Definition at line 45 of file xmlparse.cc.
xmlDeclHandler
#define xmlDeclHandler (parser->m_xmlDeclHandler)
Definition at line 604 of file xmlparse.cc.
XmlEncode
#define XmlEncode XmlUtf8Encode
Definition at line 48 of file xmlparse.cc.
XmlGetInternalEncoding
#define XmlGetInternalEncoding XmlGetUtf8InternalEncoding
Definition at line 46 of file xmlparse.cc.
XmlGetInternalEncodingNS [1/2]
#define XmlGetInternalEncodingNS XmlGetUtf8InternalEncodingNS
Definition at line 59 of file xmlparse.cc.
XmlGetInternalEncodingNS [2/2]
#define XmlGetInternalEncodingNS XmlGetInternalEncoding
Definition at line 59 of file xmlparse.cc.
XmlInitEncodingNS
#define XmlInitEncodingNS XmlInitEncoding
Definition at line 56 of file xmlparse.cc.
XmlInitUnknownEncodingNS
#define XmlInitUnknownEncodingNS XmlInitUnknownEncoding
Definition at line 57 of file xmlparse.cc.
XmlParseXmlDeclNS
#define XmlParseXmlDeclNS XmlParseXmlDecl
Definition at line 60 of file xmlparse.cc.
Typedef Documentation
ATTRIBUTE_ID
typedef struct attribute_id ATTRIBUTE_ID
BINDING
typedef struct binding BINDING
BLOCK
typedef struct block BLOCK
ICHAR
typedef char ICHAR
Definition at line 50 of file xmlparse.cc.
OPEN_INTERNAL_ENTITY
typedef struct open_internal_entity OPEN_INTERNAL_ENTITY
PREFIX
typedef struct prefix PREFIX
TAG
typedef struct tag TAG
Function Documentation
addBinding()
static enum XML_Error addBinding (XML_Parser parser, PREFIX * prefix, const ATTRIBUTE_ID * attId, const XML_Char * uri, BINDING ** bindingsPtr) static
Definition at line 3056 of file xmlparse.cc.
Referenced by setContext(), and storeAtts().
appendAttributeValue()
static enum XML_Error appendAttributeValue (XML_Parser parser, const ENCODING * enc, XML_Bool isCdata, const char * ptr, const char * end, STRING_POOL * pool) static
Definition at line 4944 of file xmlparse.cc.
Referenced by storeAttributeValue().
build_model()
static XML_Content * build_model (XML_Parser parser) static
Definition at line 6366 of file xmlparse.cc.
Referenced by doProlog().
build_node()
static void build_node (XML_Parser parser, int src_node, XML_Content * dest, XML_Content ** contpos, XML_Char ** strpos) static
Definition at line 6328 of file xmlparse.cc.
Referenced by build_model().
cdataSectionProcessor()
static enum XML_Error PTRCALL cdataSectionProcessor (XML_Parser parser, const char * start, const char * end, const char ** endPtr) static
Definition at line 3173 of file xmlparse.cc.
contentProcessor()
static enum XML_Error PTRCALL contentProcessor (XML_Parser parser, const char * start, const char * end, const char ** endPtr) static
Definition at line 2106 of file xmlparse.cc.
copyEntityTable()
static int copyEntityTable (XML_Parser oldParser, HASH_TABLE * newTable, STRING_POOL * newPool, const HASH_TABLE * oldTable) static
Definition at line 5889 of file xmlparse.cc.
Referenced by dtdCopy().
defineAttribute()
static int defineAttribute (ELEMENT_TYPE * type, ATTRIBUTE_ID * attId, XML_Bool isCdata, XML_Bool isId, const XML_Char * dfltValue, XML_Parser parser) static
Definition at line 5362 of file xmlparse.cc.
Referenced by doProlog().
destroyBindings()
static void FASTCALL destroyBindings (BINDING * bindings, XML_Parser parser) static
Definition at line 1123 of file xmlparse.cc.
Referenced by XML_ParserFree().
doCdataSection()
static enum XML_Error doCdataSection (XML_Parser parser, const ENCODING * enc, const char ** startPtr, const char * end, const char ** nextPtr, XML_Bool haveMore) static
Definition at line 3199 of file xmlparse.cc.
Referenced by cdataSectionProcessor(), and doContent().
doContent()
static enum XML_Error doContent (XML_Parser parser, int startTagLevel, const ENCODING * enc, const char * start, const char * end, const char ** endPtr, XML_Bool haveMore) static
Definition at line 2237 of file xmlparse.cc.
Referenced by contentProcessor(), externalEntityContentProcessor(), internalEntityProcessor(), and processInternalEntity().
doProlog()
static enum XML_Error doProlog (XML_Parser parser, const ENCODING * enc, const char * s, const char * end, int tok, const char * next, const char ** nextPtr, XML_Bool haveMore) static
Definition at line 3750 of file xmlparse.cc.
Referenced by internalEntityProcessor(), processInternalEntity(), and prologProcessor().
dtdCopy()
static int dtdCopy (XML_Parser oldParser, DTD * newDtd, const DTD * oldDtd, const XML_Memory_Handling_Suite * ms) static
Definition at line 5757 of file xmlparse.cc.
Referenced by XML_ExternalEntityParserCreate().
dtdCreate()
static DTD * dtdCreate (const XML_Memory_Handling_Suite * ms) static
Definition at line 5651 of file xmlparse.cc.
Referenced by parserCreate().
dtdDestroy()
static void dtdDestroy (DTD * p, XML_Bool isDocEntity, const XML_Memory_Handling_Suite * ms) static
Definition at line 5726 of file xmlparse.cc.
Referenced by XML_ParserFree().
dtdReset()
static void dtdReset (DTD * p, const XML_Memory_Handling_Suite * ms) static
Definition at line 5684 of file xmlparse.cc.
Referenced by XML_ParserReset().
epilogProcessor()
static enum XML_Error PTRCALL epilogProcessor (XML_Parser parser, const char * s, const char * end, const char ** nextPtr) static
Definition at line 4734 of file xmlparse.cc.
errorProcessor()
static enum XML_Error PTRCALL errorProcessor (XML_Parser parser, const char * s, const char * end, const char ** nextPtr) static
Definition at line 4919 of file xmlparse.cc.
externalEntityContentProcessor()
static enum XML_Error PTRCALL externalEntityContentProcessor (XML_Parser parser, const char * start, const char * end, const char ** endPtr) static
Definition at line 2222 of file xmlparse.cc.
externalEntityInitProcessor()
static enum XML_Error PTRCALL externalEntityInitProcessor (XML_Parser parser, const char * start, const char * end, const char ** endPtr) static
Definition at line 2121 of file xmlparse.cc.
externalEntityInitProcessor2()
static enum XML_Error PTRCALL externalEntityInitProcessor2 (XML_Parser parser, const char * start, const char * end, const char ** endPtr) static
Definition at line 2134 of file xmlparse.cc.
externalEntityInitProcessor3()
static enum XML_Error PTRCALL externalEntityInitProcessor3 (XML_Parser parser, const char * start, const char * end, const char ** endPtr) static
Definition at line 2174 of file xmlparse.cc.
generate_hash_secret_salt()
static unsigned long generate_hash_secret_salt (void) static
Definition at line 700 of file xmlparse.cc.
Referenced by startParsing().
getAttributeId()
static ATTRIBUTE_ID * getAttributeId (XML_Parser parser, const ENCODING * enc, const char * start, const char * end) static
Definition at line 5436 of file xmlparse.cc.
Referenced by doProlog(), and storeAtts().
getContext()
static const XML_Char * getContext (XML_Parser parser) static
Definition at line 5499 of file xmlparse.cc.
Referenced by doContent().
getElementType()
static ELEMENT_TYPE * getElementType (XML_Parser parser, const ENCODING * enc, const char * ptr, const char * end) static
Definition at line 6387 of file xmlparse.cc.
Referenced by doProlog().
handleUnknownEncoding()
static enum XML_Error handleUnknownEncoding (XML_Parser parser, const XML_Char * encodingName) static
Definition at line 3514 of file xmlparse.cc.
Referenced by initializeEncoding(), and processXmlDecl().
hash()
static unsigned long FASTCALL hash (XML_Parser parser, KEY s) static
Definition at line 5967 of file xmlparse.cc.
Referenced by G4ITReaction::GetHash(), lookup(), and storeAtts().
hashTableClear()
static void FASTCALL hashTableClear (HASH_TABLE * table) static
Definition at line 6055 of file xmlparse.cc.
Referenced by dtdReset().
hashTableDestroy()
static void FASTCALL hashTableDestroy (HASH_TABLE * table) static
Definition at line 6066 of file xmlparse.cc.
Referenced by dtdDestroy().
hashTableInit()
static void FASTCALL hashTableInit (HASH_TABLE * p, const XML_Memory_Handling_Suite * ms) static
Definition at line 6075 of file xmlparse.cc.
Referenced by dtdCreate().
hashTableIterInit()
static void FASTCALL hashTableIterInit (HASH_TABLE_ITER * iter, const HASH_TABLE * table) static
Definition at line 6085 of file xmlparse.cc.
Referenced by copyEntityTable(), dtdCopy(), dtdDestroy(), dtdReset(), and getContext().
hashTableIterNext()
static NAMED *FASTCALL hashTableIterNext (HASH_TABLE_ITER * iter) static
Definition at line 6092 of file xmlparse.cc.
Referenced by copyEntityTable(), dtdCopy(), dtdDestroy(), dtdReset(), and getContext().
initializeEncoding()
static enum XML_Error initializeEncoding (XML_Parser parser) static
Definition at line 3396 of file xmlparse.cc.
Referenced by externalEntityInitProcessor(), and prologInitProcessor().
internalEntityProcessor()
static enum XML_Error PTRCALL internalEntityProcessor (XML_Parser parser, const char * s, const char * end, const char ** nextPtr) static
Definition at line 4858 of file xmlparse.cc.
keyeq()
static XML_Bool FASTCALL keyeq (KEY s1, KEY s2) static
Definition at line 5958 of file xmlparse.cc.
Referenced by lookup().
lookup()
static NAMED * lookup (XML_Parser parser, HASH_TABLE * table, KEY name, size_t createSize) static
Definition at line 5976 of file xmlparse.cc.
Referenced by appendAttributeValue(), copyEntityTable(), doContent(), doProlog(), dtdCopy(), getAttributeId(), getElementType(), setContext(), setElementTypePrefix(), storeAtts(), and storeEntityValue().
moveToFreeBindingList()
static void FASTCALL moveToFreeBindingList (XML_Parser parser, BINDING * bindings) static
Definition at line 920 of file xmlparse.cc.
Referenced by XML_ParserReset().
nextScaffoldPart()
static int FASTCALL nextScaffoldPart (XML_Parser parser) static
Definition at line 6280 of file xmlparse.cc.
Referenced by doProlog().
normalizeLines()
static void FASTCALL normalizeLines (XML_Char * s) static
Definition at line 5260 of file xmlparse.cc.
Referenced by reportComment(), and reportProcessingInstruction().
normalizePublicId()
static void FASTCALL normalizePublicId (XML_Char * s) static
Definition at line 5629 of file xmlparse.cc.
Referenced by doProlog().
parserCreate()
static XML_Parser parserCreate (const XML_Char * encodingName, const XML_Memory_Handling_Suite * memsuite, const XML_Char * nameSep, DTD * dtd) static
Definition at line 731 of file xmlparse.cc.
Referenced by XML_ExternalEntityParserCreate(), and XML_ParserCreate_MM().
parserInit()
static void parserInit (XML_Parser parser, const XML_Char * encodingName) static
Definition at line 846 of file xmlparse.cc.
Referenced by parserCreate(), and XML_ParserReset().
poolAppend()
static XML_Char * poolAppend (STRING_POOL * pool, const ENCODING * enc, const char * ptr, const char * end) static
Definition at line 6151 of file xmlparse.cc.
Referenced by appendAttributeValue(), doProlog(), poolStoreString(), and storeEntityValue().
poolAppendString()
static const XML_Char *FASTCALL poolAppendString (STRING_POOL * pool, const XML_Char * s) static
Definition at line 6193 of file xmlparse.cc.
Referenced by doProlog().
poolClear()
static void FASTCALL poolClear (STRING_POOL * pool) static
Definition at line 6114 of file xmlparse.cc.
Referenced by doContent(), doProlog(), dtdReset(), processXmlDecl(), reportComment(), reportProcessingInstruction(), and XML_ParserReset().
poolCopyString()
static const XML_Char *FASTCALL poolCopyString (STRING_POOL * pool, const XML_Char * s) static
Definition at line 6167 of file xmlparse.cc.
Referenced by copyEntityTable(), dtdCopy(), parserInit(), setContext(), storeAtts(), XML_SetBase(), and XML_SetEncoding().
poolCopyStringN()
static const XML_Char * poolCopyStringN (STRING_POOL * pool, const XML_Char * s, int n) static
Definition at line 6179 of file xmlparse.cc.
Referenced by copyEntityTable().
poolDestroy()
static void FASTCALL poolDestroy (STRING_POOL * pool) static
Definition at line 6134 of file xmlparse.cc.
Referenced by dtdDestroy(), and XML_ParserFree().
poolGrow()
static XML_Bool FASTCALL poolGrow (STRING_POOL * pool) static
Definition at line 6216 of file xmlparse.cc.
Referenced by poolAppend(), poolCopyStringN(), poolStoreString(), and storeEntityValue().
poolInit()
static void FASTCALL poolInit (STRING_POOL * pool, const XML_Memory_Handling_Suite * ms) static
Definition at line 6103 of file xmlparse.cc.
Referenced by dtdCreate(), and parserCreate().
poolStoreString()
static XML_Char * poolStoreString (STRING_POOL * pool, const ENCODING * enc, const char * ptr, const char * end) static
Definition at line 6204 of file xmlparse.cc.
Referenced by appendAttributeValue(), doContent(), doProlog(), getAttributeId(), getElementType(), processXmlDecl(), reportComment(), reportProcessingInstruction(), storeAtts(), and storeEntityValue().
processInternalEntity()
static enum XML_Error processInternalEntity (XML_Parser parser, ENTITY * entity, XML_Bool betweenDecl) static
Definition at line 4801 of file xmlparse.cc.
Referenced by doContent(), and doProlog().
Processor()
enum XML_Error PTRCALL Processor (XML_Parser parser, const char * start, const char * end, const char ** endPtr)
processXmlDecl()
static enum XML_Error processXmlDecl (XML_Parser parser, int isGeneralTextEntity, const char * s, const char * next) static
Definition at line 3425 of file xmlparse.cc.
Referenced by doProlog(), and externalEntityInitProcessor3().
prologInitProcessor()
static enum XML_Error PTRCALL prologInitProcessor (XML_Parser parser, const char * s, const char * end, const char ** nextPtr) static
Definition at line 3553 of file xmlparse.cc.
prologProcessor()
static enum XML_Error PTRCALL prologProcessor (XML_Parser parser, const char * s, const char * end, const char ** nextPtr) static
Definition at line 3738 of file xmlparse.cc.
reportComment()
static int reportComment (XML_Parser parser, const ENCODING * enc, const char * start, const char * end) static
Definition at line 5312 of file xmlparse.cc.
Referenced by doContent(), doProlog(), and epilogProcessor().
reportDefault()
static void reportDefault (XML_Parser parser, const ENCODING * enc, const char * start, const char * end) static
Definition at line 5334 of file xmlparse.cc.
Referenced by doCdataSection(), doContent(), doProlog(), epilogProcessor(), processXmlDecl(), reportComment(), reportProcessingInstruction(), and XML_DefaultCurrent().
reportProcessingInstruction()
static int reportProcessingInstruction (XML_Parser parser, const ENCODING * enc, const char * start, const char * end) static
Definition at line 5283 of file xmlparse.cc.
Referenced by doContent(), doProlog(), and epilogProcessor().
setContext()
static XML_Bool setContext (XML_Parser parser, const XML_Char * context) static
Definition at line 5568 of file xmlparse.cc.
Referenced by startParsing(), and XML_ExternalEntityParserCreate().
setElementTypePrefix()
static int setElementTypePrefix (XML_Parser parser, ELEMENT_TYPE * elementType) static
Definition at line 5406 of file xmlparse.cc.
Referenced by getElementType(), and storeAtts().
startParsing()
static XML_Bool startParsing (XML_Parser parser) static
Definition at line 708 of file xmlparse.cc.
Referenced by XML_Parse(), and XML_ParseBuffer().
storeAttributeValue()
static enum XML_Error storeAttributeValue (XML_Parser parser, const ENCODING * enc, XML_Bool isCdata, const char * ptr, const char * end, STRING_POOL * pool) static
Definition at line 4928 of file xmlparse.cc.
Referenced by doProlog(), and storeAtts().
storeAtts()
static enum XML_Error storeAtts (XML_Parser parser, const ENCODING * enc, const char * s, TAG_NAME * tagNamePtr, BINDING ** bindingsPtr) static
Definition at line 2704 of file xmlparse.cc.
Referenced by doContent().
storeEntityValue()
static enum XML_Error storeEntityValue (XML_Parser parser, const ENCODING * enc, const char * start, const char * end) static
Definition at line 5094 of file xmlparse.cc.
Referenced by doProlog().
storeRawNames()
static XML_Bool storeRawNames (XML_Parser parser) static
Definition at line 2061 of file xmlparse.cc.
Referenced by contentProcessor(), and externalEntityContentProcessor().
XML_DefaultCurrent()
void XMLCALL XML_DefaultCurrent (XML_Parser parser)
Definition at line 1920 of file xmlparse.cc.
XML_ErrorString()
const XML_LChar* XMLCALL XML_ErrorString (enum XML_Error code)
Definition at line 1934 of file xmlparse.cc.
Referenced by xDataXML_endXMLParsing().
XML_ExpatVersion()
const XML_LChar* XMLCALL XML_ExpatVersion (void)
Definition at line 1985 of file xmlparse.cc.
XML_ExpatVersionInfo()
XML_Expat_Version XMLCALL XML_ExpatVersionInfo (void)
Definition at line 2005 of file xmlparse.cc.
XML_ExternalEntityParserCreate()
XML_Parser XMLCALL XML_ExternalEntityParserCreate (XML_Parser oldParser, const XML_Char * context, const XML_Char * encodingName)
Definition at line 986 of file xmlparse.cc.
XML_FreeContentModel()
void XMLCALL XML_FreeContentModel (XML_Parser parser, XML_Content * model)
Definition at line 1896 of file xmlparse.cc.
XML_GetBase()
const XML_Char* XMLCALL XML_GetBase (XML_Parser parser)
Definition at line 1253 of file xmlparse.cc.
XML_GetBuffer()
void* XMLCALL XML_GetBuffer (XML_Parser parser, int len)
Definition at line 1685 of file xmlparse.cc.
Referenced by XML_Parse().
XML_GetCurrentByteCount()
int XMLCALL XML_GetCurrentByteCount (XML_Parser parser)
Definition at line 1855 of file xmlparse.cc.
XML_GetCurrentByteIndex()
XML_Index XMLCALL XML_GetCurrentByteIndex (XML_Parser parser)
Definition at line 1847 of file xmlparse.cc.
XML_GetCurrentColumnNumber()
XML_Size XMLCALL XML_GetCurrentColumnNumber (XML_Parser parser)
Definition at line 1886 of file xmlparse.cc.
Referenced by xDataXML_endXMLParsing(), and xDataXML_parseGetCurrentPosition().
XML_GetCurrentLineNumber()
XML_Size XMLCALL XML_GetCurrentLineNumber (XML_Parser parser)
Definition at line 1876 of file xmlparse.cc.
Referenced by xDataXML_endXMLParsing(), and xDataXML_parseGetCurrentPosition().
XML_GetErrorCode()
enum XML_Error XMLCALL XML_GetErrorCode (XML_Parser parser)
Definition at line 1841 of file xmlparse.cc.
Referenced by xDataXML_endXMLParsing().
XML_GetFeatureList()
const XML_Feature* XMLCALL XML_GetFeatureList (void)
Definition at line 2017 of file xmlparse.cc.
XML_GetIdAttributeIndex()
int XMLCALL XML_GetIdAttributeIndex (XML_Parser parser)
Definition at line 1265 of file xmlparse.cc.
XML_GetInputContext()
const char* XMLCALL XML_GetInputContext (XML_Parser parser, int * offset, int * size)
Definition at line 1863 of file xmlparse.cc.
XML_GetParsingStatus()
void XMLCALL XML_GetParsingStatus (XML_Parser parser, XML_ParsingStatus * status)
Definition at line 1834 of file xmlparse.cc.
XML_GetSpecifiedAttributeCount()
int XMLCALL XML_GetSpecifiedAttributeCount (XML_Parser parser)
Definition at line 1259 of file xmlparse.cc.
XML_MemFree()
void XMLCALL XML_MemFree (XML_Parser parser, void * ptr)
Definition at line 1914 of file xmlparse.cc.
XML_MemMalloc()
void* XMLCALL XML_MemMalloc (XML_Parser parser, size_t size)
Definition at line 1902 of file xmlparse.cc.
XML_MemRealloc()
void* XMLCALL XML_MemRealloc (XML_Parser parser, void * ptr, size_t size)
Definition at line 1908 of file xmlparse.cc.
XML_Parse()
enum XML_Status XMLCALL XML_Parse (XML_Parser parser, const char * s, int len, int isFinal)
Definition at line 1506 of file xmlparse.cc.
Referenced by xDataXML_endXMLParsing(), and xDataXML_parse().
XML_ParseBuffer()
enum XML_Status XMLCALL XML_ParseBuffer (XML_Parser parser, int len, int isFinal)
Definition at line 1629 of file xmlparse.cc.
Referenced by XML_Parse().
XML_ParserCreate()
XML_Parser XMLCALL XML_ParserCreate (const XML_Char * encodingName)
Definition at line 677 of file xmlparse.cc.
Referenced by xDataXML_initializeDoc().
XML_ParserCreate_MM()
XML_Parser XMLCALL XML_ParserCreate_MM (const XML_Char * encodingName, const XML_Memory_Handling_Suite * memsuite, const XML_Char * nameSep)
Definition at line 723 of file xmlparse.cc.
Referenced by XML_ParserCreate(), and XML_ParserCreateNS().
XML_ParserCreateNS()
XML_Parser XMLCALL XML_ParserCreateNS (const XML_Char * encodingName, XML_Char nsSep)
Definition at line 683 of file xmlparse.cc.
XML_ParserFree()
void XMLCALL XML_ParserFree (XML_Parser parser)
Definition at line 1136 of file xmlparse.cc.
Referenced by parserCreate(), xDataXML_endXMLParsing(), and XML_ExternalEntityParserCreate().
XML_ParserReset()
XML_Bool XMLCALL XML_ParserReset (XML_Parser parser, const XML_Char * encodingName)
Definition at line 931 of file xmlparse.cc.
XML_ResumeParser()
enum XML_Status XMLCALL XML_ResumeParser (XML_Parser parser)
Definition at line 1796 of file xmlparse.cc.
XML_SetAttlistDeclHandler()
void XMLCALL XML_SetAttlistDeclHandler (XML_Parser parser, XML_AttlistDeclHandler attdecl)
Definition at line 1460 of file xmlparse.cc.
XML_SetBase()
enum XML_Status XMLCALL XML_SetBase (XML_Parser parser, const XML_Char * p)
Definition at line 1239 of file xmlparse.cc.
XML_SetCdataSectionHandler()
void XMLCALL XML_SetCdataSectionHandler (XML_Parser parser, XML_StartCdataSectionHandler start, XML_EndCdataSectionHandler end)
Definition at line 1321 of file xmlparse.cc.
XML_SetCharacterDataHandler()
void XMLCALL XML_SetCharacterDataHandler (XML_Parser parser, XML_CharacterDataHandler handler)
Definition at line 1300 of file xmlparse.cc.
Referenced by xDataXML_initializeDoc().
XML_SetCommentHandler()
void XMLCALL XML_SetCommentHandler (XML_Parser parser, XML_CommentHandler handler)
Definition at line 1314 of file xmlparse.cc.
XML_SetDefaultHandler()
void XMLCALL XML_SetDefaultHandler (XML_Parser parser, XML_DefaultHandler handler)
Definition at line 1342 of file xmlparse.cc.
XML_SetDefaultHandlerExpand()
void XMLCALL XML_SetDefaultHandlerExpand (XML_Parser parser, XML_DefaultHandler handler)
Definition at line 1350 of file xmlparse.cc.
XML_SetDoctypeDeclHandler()
void XMLCALL XML_SetDoctypeDeclHandler (XML_Parser parser, XML_StartDoctypeDeclHandler start, XML_EndDoctypeDeclHandler end)
Definition at line 1358 of file xmlparse.cc.
XML_SetElementDeclHandler()
void XMLCALL XML_SetElementDeclHandler (XML_Parser parser, XML_ElementDeclHandler eldecl)
Definition at line 1453 of file xmlparse.cc.
XML_SetElementHandler()
void XMLCALL XML_SetElementHandler (XML_Parser parser, XML_StartElementHandler start, XML_EndElementHandler end)
Definition at line 1279 of file xmlparse.cc.
Referenced by xDataXML_initializeDoc().
XML_SetEncoding()
enum XML_Status XMLCALL XML_SetEncoding (XML_Parser parser, const XML_Char * encodingName)
Definition at line 967 of file xmlparse.cc.
XML_SetEndCdataSectionHandler()
void XMLCALL XML_SetEndCdataSectionHandler (XML_Parser parser, XML_EndCdataSectionHandler end)
Definition at line 1336 of file xmlparse.cc.
XML_SetEndDoctypeDeclHandler()
void XMLCALL XML_SetEndDoctypeDeclHandler (XML_Parser parser, XML_EndDoctypeDeclHandler end)
Definition at line 1373 of file xmlparse.cc.
XML_SetEndElementHandler()
void XMLCALL XML_SetEndElementHandler (XML_Parser parser, XML_EndElementHandler end)
Definition at line 1294 of file xmlparse.cc.
XML_SetEndNamespaceDeclHandler()
void XMLCALL XML_SetEndNamespaceDeclHandler (XML_Parser parser, XML_EndNamespaceDeclHandler end)
Definition at line 1408 of file xmlparse.cc.
XML_SetEntityDeclHandler()
void XMLCALL XML_SetEntityDeclHandler (XML_Parser parser, XML_EntityDeclHandler handler)
Definition at line 1467 of file xmlparse.cc.
XML_SetExternalEntityRefHandler()
void XMLCALL XML_SetExternalEntityRefHandler (XML_Parser parser, XML_ExternalEntityRefHandler handler)
Definition at line 1421 of file xmlparse.cc.
XML_SetExternalEntityRefHandlerArg()
void XMLCALL XML_SetExternalEntityRefHandlerArg (XML_Parser parser, void * arg)
Definition at line 1428 of file xmlparse.cc.
XML_SetHashSalt()
int XMLCALL XML_SetHashSalt (XML_Parser parser, unsigned long hash_salt)
Definition at line 1495 of file xmlparse.cc.
XML_SetNamespaceDeclHandler()
void XMLCALL XML_SetNamespaceDeclHandler (XML_Parser parser, XML_StartNamespaceDeclHandler start, XML_EndNamespaceDeclHandler end)
Definition at line 1393 of file xmlparse.cc.
XML_SetNotationDeclHandler()
void XMLCALL XML_SetNotationDeclHandler (XML_Parser parser, XML_NotationDeclHandler handler)
Definition at line 1386 of file xmlparse.cc.
XML_SetNotStandaloneHandler()
void XMLCALL XML_SetNotStandaloneHandler (XML_Parser parser, XML_NotStandaloneHandler handler)
Definition at line 1414 of file xmlparse.cc.
XML_SetParamEntityParsing()
int XMLCALL XML_SetParamEntityParsing (XML_Parser parser, enum XML_ParamEntityParsing peParsing)
Definition at line 1480 of file xmlparse.cc.
XML_SetProcessingInstructionHandler()
void XMLCALL XML_SetProcessingInstructionHandler (XML_Parser parser, XML_ProcessingInstructionHandler handler)
Definition at line 1307 of file xmlparse.cc.
XML_SetReturnNSTriplet()
void XMLCALL XML_SetReturnNSTriplet (XML_Parser parser, int do_nst)
Definition at line 1221 of file xmlparse.cc.
XML_SetSkippedEntityHandler()
void XMLCALL XML_SetSkippedEntityHandler (XML_Parser parser, XML_SkippedEntityHandler handler)
Definition at line 1437 of file xmlparse.cc.
XML_SetStartCdataSectionHandler()
void XMLCALL XML_SetStartCdataSectionHandler (XML_Parser parser, XML_StartCdataSectionHandler start)
Definition at line 1330 of file xmlparse.cc.
XML_SetStartDoctypeDeclHandler()
void XMLCALL XML_SetStartDoctypeDeclHandler (XML_Parser parser, XML_StartDoctypeDeclHandler start)
Definition at line 1367 of file xmlparse.cc.
XML_SetStartElementHandler()
void XMLCALL XML_SetStartElementHandler (XML_Parser parser, XML_StartElementHandler start)
Definition at line 1288 of file xmlparse.cc.
XML_SetStartNamespaceDeclHandler()
void XMLCALL XML_SetStartNamespaceDeclHandler (XML_Parser parser, XML_StartNamespaceDeclHandler start)
Definition at line 1402 of file xmlparse.cc.
XML_SetUnknownEncodingHandler()
void XMLCALL XML_SetUnknownEncodingHandler (XML_Parser parser, XML_UnknownEncodingHandler handler, void * data)
Definition at line 1444 of file xmlparse.cc.
XML_SetUnparsedEntityDeclHandler()
void XMLCALL XML_SetUnparsedEntityDeclHandler (XML_Parser parser, XML_UnparsedEntityDeclHandler handler)
Definition at line 1379 of file xmlparse.cc.
XML_SetUserData()
void XMLCALL XML_SetUserData (XML_Parser parser, void * p)
Definition at line 1230 of file xmlparse.cc.
Referenced by xDataXML_initializeDoc().
XML_SetXmlDeclHandler()
void XMLCALL XML_SetXmlDeclHandler (XML_Parser parser, XML_XmlDeclHandler handler)
Definition at line 1474 of file xmlparse.cc.
XML_StopParser()
enum XML_Status XMLCALL XML_StopParser (XML_Parser parser, XML_Bool resumable)
Definition at line 1766 of file xmlparse.cc.
XML_UseForeignDTD()
enum XML_Error XMLCALL XML_UseForeignDTD (XML_Parser parser, XML_Bool useDTD)
Definition at line 1207 of file xmlparse.cc.
XML_UseParserAsHandlerArg()
void XMLCALL XML_UseParserAsHandlerArg (XML_Parser parser)
Definition at line 1201 of file xmlparse.cc.
Variable Documentation
cdataSectionProcessor
Processor cdataSectionProcessor static
Definition at line 314 of file xmlparse.cc.
Referenced by doContent().
contentProcessor
Processor contentProcessor static
Definition at line 313 of file xmlparse.cc.
Referenced by cdataSectionProcessor(), doProlog(), and internalEntityProcessor().
epilogProcessor
Processor epilogProcessor static
Definition at line 322 of file xmlparse.cc.
Referenced by doContent(), and epilogProcessor().
errorProcessor
Processor errorProcessor static
Definition at line 323 of file xmlparse.cc.
Referenced by XML_Parse(), XML_ParseBuffer(), and XML_ResumeParser().
externalEntityContentProcessor
Processor externalEntityContentProcessor static
Definition at line 327 of file xmlparse.cc.
Referenced by cdataSectionProcessor(), and externalEntityInitProcessor3().
externalEntityInitProcessor
Processor externalEntityInitProcessor static
Definition at line 324 of file xmlparse.cc.
Referenced by XML_ExternalEntityParserCreate().
externalEntityInitProcessor2
Processor externalEntityInitProcessor2 static
Definition at line 325 of file xmlparse.cc.
Referenced by externalEntityInitProcessor().
externalEntityInitProcessor3
Processor externalEntityInitProcessor3 static
Definition at line 326 of file xmlparse.cc.
Referenced by externalEntityInitProcessor2().
implicitContext
const XML_Char implicitContext[] static
Initial value:
= {
  ASCII_x, ASCII_m, ASCII_l, ASCII_EQUALS, ASCII_h, ASCII_t, ASCII_t, ASCII_p,
  ASCII_COLON, ASCII_SLASH, ASCII_SLASH, ASCII_w, ASCII_w, ASCII_w,
  ASCII_PERIOD, ASCII_w, ASCII_3, ASCII_PERIOD, ASCII_o, ASCII_r, ASCII_g,
  ASCII_SLASH, ASCII_X, ASCII_M, ASCII_L, ASCII_SLASH, ASCII_1, ASCII_9,
  ASCII_9, ASCII_8, ASCII_SLASH, ASCII_n, ASCII_a, ASCII_m, ASCII_e,
  ASCII_s, ASCII_p, ASCII_a, ASCII_c, ASCII_e, '\0'
}
Definition at line 690 of file xmlparse.cc.
Referenced by startParsing().
internalEntityProcessor
Processor internalEntityProcessor static
Definition at line 328 of file xmlparse.cc.
Referenced by processInternalEntity().
KEY
const typedef XML_Char* KEY
Definition at line 97 of file xmlparse.cc.
prologInitProcessor
Processor prologInitProcessor static
Definition at line 312 of file xmlparse.cc.
Referenced by parserInit().
prologProcessor
Processor prologProcessor static
Definition at line 311 of file xmlparse.cc.
Referenced by internalEntityProcessor(), and prologInitProcessor().