Geant4: G4IonTable Class Reference
G4IonTable Class Reference
#include <G4IonTable.hh>
Public Types
enum { numberOfElements = 118 }
typedef std::multimap< G4int, const G4ParticleDefinition * > G4IonList
typedef std::multimap< G4int, const G4ParticleDefinition * >::iterator G4IonListIterator
Public Member Functions
G4IonTable ()
void SlaveG4IonTable ()
void WorkerG4IonTable ()
virtual ~G4IonTable ()
void DestroyWorkerG4IonTable ()
G4int GetNumberOfElements () const
void RegisterIsotopeTable (G4VIsotopeTable *table)
G4VIsotopeTable * GetIsotopeTable (size_t idx=0) const
void CreateAllIon ()
void CreateAllIsomer ()
void PrepareNuclideTable ()
void PreloadNuclide ()
G4ParticleDefinition * GetIon (G4int Z, G4int A, G4int lvl=0)
G4ParticleDefinition * GetIon (G4int Z, G4int A, G4int L, G4int lvl)
G4ParticleDefinition * GetIon (G4int Z, G4int A, G4double E, G4int J=0)
G4ParticleDefinition * GetIon (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb, G4int J=0)
G4ParticleDefinition * GetIon (G4int Z, G4int A, G4double E, char flbChar, G4int J=0)
G4ParticleDefinition * GetIon (G4int Z, G4int A, G4int L, G4double E, G4int J=0)
G4ParticleDefinition * GetIon (G4int Z, G4int A, G4int L, G4double E, G4Ions::G4FloatLevelBase flb, G4int J=0)
G4ParticleDefinition * GetIon (G4int Z, G4int A, G4int L, G4double E, char flbChar, G4int J=0)
G4ParticleDefinition * GetIon (G4int encoding)
G4ParticleDefinition * FindIon (G4int Z, G4int A, G4int lvl=0)
G4ParticleDefinition * FindIon (G4int Z, G4int A, G4int L, G4int lvl)
G4ParticleDefinition * FindIon (G4int Z, G4int A, G4double E, G4int J=0)
G4ParticleDefinition * FindIon (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb, G4int J=0)
G4ParticleDefinition * FindIon (G4int Z, G4int A, G4double E, char flbChar, G4int J=0)
G4ParticleDefinition * FindIon (G4int Z, G4int A, G4int L, G4double E, G4int J=0)
G4ParticleDefinition * FindIon (G4int Z, G4int A, G4int L, G4double E, G4Ions::G4FloatLevelBase flb, G4int J=0)
G4ParticleDefinition * FindIon (G4int Z, G4int A, G4int L, G4double E, char flbChar, G4int J=0)
const G4String & GetIonName (G4int Z, G4int A, G4int lvl=0) const
const G4String & GetIonName (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb=G4Ions::G4FloatLevelBase::no_Float) const
const G4String & GetIonName (G4int Z, G4int A, G4int L, G4double E, G4Ions::G4FloatLevelBase flb=G4Ions::G4FloatLevelBase::no_Float) const
const G4String & GetIonName (G4int Z, G4int A, G4int L, G4int lvl) const
G4double GetIonMass (G4int Z, G4int A, G4int L=0, G4int lvl=0) const
G4double GetNucleusMass (G4int Z, G4int A, G4int L=0, G4int lvl=0) const
G4double GetIsomerMass (G4int Z, G4int A, G4int lvl=0) const
G4double GetLifeTime (const G4ParticleDefinition *) const
G4double GetLifeTime (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb=G4Ions::G4FloatLevelBase::no_Float) const
G4double GetLifeTime (G4int Z, G4int A, G4double E, char flbChar) const
G4int Entries () const
G4ParticleDefinition * GetParticle (G4int index) const
G4bool Contains (const G4ParticleDefinition *particle) const
void Insert (const G4ParticleDefinition *particle)
void Remove (const G4ParticleDefinition *particle)
void clear ()
G4int size () const
void DumpTable (const G4String &particle_name="ALL") const
void InitializeLightIons ()
G4ParticleDefinition * GetMuonicAtom (G4Ions const *)
G4ParticleDefinition * GetMuonicAtom (G4int Z, G4int A)
Static Public Member Functions
static G4IonTable * GetIonTable ()
static G4bool IsIon (const G4ParticleDefinition *)
static G4bool IsAntiIon (const G4ParticleDefinition *)
static G4int GetNucleusEncoding (G4int Z, G4int A, G4double E=0.0, G4int lvl=0)
static G4int GetNucleusEncoding (G4int Z, G4int A, G4int L, G4double E=0.0, G4int lvl=0)
static G4bool GetNucleusByEncoding (G4int encoding, G4int &Z, G4int &A, G4double &E, G4int &lvl)
static G4bool GetNucleusByEncoding (G4int encoding, G4int &Z, G4int &A, G4int &L, G4double &E, G4int &lvl)
Static Public Attributes
static G4ThreadLocal G4IonList * fIonList = nullptr
static G4ThreadLocal std::vector< G4VIsotopeTable * > * fIsotopeTableList = nullptr
static G4IonList * fIonListShadow = nullptr
static std::vector< G4VIsotopeTable * > * fIsotopeTableListShadow = nullptr
static const G4String elementName [numberOfElements]
Protected Member Functions
G4IonTable (const G4IonTable &right)
G4IonTable & operator= (const G4IonTable &)
G4ParticleDefinition * FindIonInMaster (G4int Z, G4int A, G4int lvl=0)
G4ParticleDefinition * FindIonInMaster (G4int Z, G4int A, G4int L, G4int lvl)
G4ParticleDefinition * FindIonInMaster (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb, G4int J=0)
G4ParticleDefinition * FindIonInMaster (G4int Z, G4int A, G4int L, G4double E, G4Ions::G4FloatLevelBase flb, G4int J=0)
G4ParticleDefinition * CreateIon (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb)
G4ParticleDefinition * CreateIon (G4int Z, G4int A, G4int L, G4double E, G4Ions::G4FloatLevelBase flb)
G4ParticleDefinition * CreateIon (G4int Z, G4int A, G4int lvl=0)
G4ParticleDefinition * CreateIon (G4int Z, G4int A, G4int L, G4int lvl)
void InsertWorker (const G4ParticleDefinition *particle)
G4IsotopeProperty * FindIsotope (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb) const
G4IsotopeProperty * FindIsotope (G4int Z, G4int A, G4int lvl) const
G4ParticleDefinition * GetLightIon (G4int Z, G4int A) const
G4ParticleDefinition * GetLightAntiIon (G4int Z, G4int A) const
G4bool IsLightIon (const G4ParticleDefinition *) const
G4bool IsLightAntiIon (const G4ParticleDefinition *) const
void AddProcessManager (G4ParticleDefinition *)
G4int GetVerboseLevel () const
Private Attributes
G4NuclideTable * pNuclideTable
G4bool isIsomerCreated
G4int n_error
Detailed Description
Definition at line 64 of file G4IonTable.hh.
Member Typedef Documentation
G4IonList
typedef std::multimap<G4int, const G4ParticleDefinition*> G4IonTable::G4IonList
Definition at line 73 of file G4IonTable.hh.
G4IonListIterator
typedef std::multimap<G4int, const G4ParticleDefinition*>::iterator G4IonTable::G4IonListIterator
Definition at line 74 of file G4IonTable.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
numberOfElements
Definition at line 326 of file G4IonTable.hh.
Constructor & Destructor Documentation
G4IonTable() [1/2]
G4IonTable::G4IonTable ()
Definition at line 121 of file G4IonTable.cc.
G4IonTable() [2/2]
G4IonTable::G4IonTable (const G4IonTable & right) protected
~G4IonTable()
G4IonTable::~G4IonTable () virtual
Definition at line 181 of file G4IonTable.cc.
Member Function Documentation
AddProcessManager()
void G4IonTable::AddProcessManager (G4ParticleDefinition * ion) protected
Definition at line 1477 of file G4IonTable.cc.
Referenced by CreateIon(), and GetMuonicAtom().
clear()
void G4IonTable::clear (void)
Definition at line 1319 of file G4IonTable.cc.
Referenced by G4ParticleTable::RemoveAllParticles().
Contains()
G4bool G4IonTable::Contains (const G4ParticleDefinition * particle) const
Definition at line 1663 of file G4IonTable.cc.
Referenced by Insert().
CreateAllIon()
void G4IonTable::CreateAllIon ()
Definition at line 1602 of file G4IonTable.cc.
Referenced by G4ParticleMessenger::SetNewValue().
CreateAllIsomer()
void G4IonTable::CreateAllIsomer ()
Definition at line 1608 of file G4IonTable.cc.
Referenced by G4ParticleMessenger::SetNewValue().
CreateIon() [1/4]
G4ParticleDefinition * G4IonTable::CreateIon (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb) protected
Definition at line 229 of file G4IonTable.cc.
Referenced by CreateIon(), and GetIon().
CreateIon() [2/4]
G4ParticleDefinition * G4IonTable::CreateIon (G4int Z, G4int A, G4int L, G4double E, G4Ions::G4FloatLevelBase flb) protected
Definition at line 366 of file G4IonTable.cc.
CreateIon() [3/4]
G4ParticleDefinition * G4IonTable::CreateIon (G4int Z, G4int A, G4int L, G4int lvl) protected
Definition at line 464 of file G4IonTable.cc.
CreateIon() [4/4]
G4ParticleDefinition * G4IonTable::CreateIon (G4int Z, G4int A, G4int lvl = 0) protected
Definition at line 454 of file G4IonTable.cc.
DestroyWorkerG4IonTable()
void G4IonTable::DestroyWorkerG4IonTable ()
Definition at line 203 of file G4IonTable.cc.
Referenced by G4ParticleTable::DestroyWorkerG4ParticleTable().
DumpTable()
void G4IonTable::DumpTable (const G4String & particle_name = "ALL") const
Definition at line 1440 of file G4IonTable.cc.
Entries()
G4int G4IonTable::Entries () const
Definition at line 1685 of file G4IonTable.cc.
Referenced by DMXPhysicsList::ConstructGeneral(), and GetParticle().
FindIon() [1/8]
G4ParticleDefinition * G4IonTable::FindIon (G4int Z, G4int A, G4double E, char flbChar, G4int J = 0)
Definition at line 709 of file G4IonTable.cc.
FindIon() [2/8]
G4ParticleDefinition * G4IonTable::FindIon (G4int Z, G4int A, G4double E, G4int J = 0)
Definition at line 703 of file G4IonTable.cc.
FindIon() [3/8]
G4ParticleDefinition * G4IonTable::FindIon (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb, G4int J = 0)
Definition at line 716 of file G4IonTable.cc.
FindIon() [4/8]
G4ParticleDefinition * G4IonTable::FindIon (G4int Z, G4int A, G4int L, G4double E, char flbChar, G4int J = 0)
Definition at line 773 of file G4IonTable.cc.
FindIon() [5/8]
G4ParticleDefinition * G4IonTable::FindIon (G4int Z, G4int A, G4int L, G4double E, G4int J = 0)
Definition at line 767 of file G4IonTable.cc.
FindIon() [6/8]
G4ParticleDefinition * G4IonTable::FindIon (G4int Z, G4int A, G4int L, G4double E, G4Ions::G4FloatLevelBase flb, G4int J = 0)
Definition at line 780 of file G4IonTable.cc.
FindIon() [7/8]
G4ParticleDefinition * G4IonTable::FindIon (G4int Z, G4int A, G4int L, G4int lvl)
Definition at line 879 of file G4IonTable.cc.
FindIon() [8/8]
G4ParticleDefinition * G4IonTable::FindIon (G4int Z, G4int A, G4int lvl = 0)
Definition at line 828 of file G4IonTable.cc.
Referenced by FindIon(), FindIonInMaster(), and GetIon().
FindIonInMaster() [1/4]
G4ParticleDefinition * G4IonTable::FindIonInMaster (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb, G4int J = 0) protected
Definition at line 1698 of file G4IonTable.cc.
FindIonInMaster() [2/4]
G4ParticleDefinition * G4IonTable::FindIonInMaster (G4int Z, G4int A, G4int L, G4double E, G4Ions::G4FloatLevelBase flb, G4int J = 0) protected
Definition at line 1731 of file G4IonTable.cc.
FindIonInMaster() [3/4]
G4ParticleDefinition * G4IonTable::FindIonInMaster (G4int Z, G4int A, G4int L, G4int lvl) protected
Definition at line 1796 of file G4IonTable.cc.
FindIonInMaster() [4/4]
G4ParticleDefinition * G4IonTable::FindIonInMaster (G4int Z, G4int A, G4int lvl = 0) protected
Definition at line 1767 of file G4IonTable.cc.
Referenced by GetIon().
FindIsotope() [1/2]
G4IsotopeProperty * G4IonTable::FindIsotope (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb) const protected
Definition at line 1564 of file G4IonTable.cc.
Referenced by CreateIon(), GetLifeTime(), and GetNucleusMass().
FindIsotope() [2/2]
G4IsotopeProperty * G4IonTable::FindIsotope (G4int Z, G4int A, G4int lvl) const protected
Definition at line 1583 of file G4IonTable.cc.
GetIon() [1/9]
G4ParticleDefinition * G4IonTable::GetIon (G4int encoding)
Definition at line 681 of file G4IonTable.cc.
GetIon() [2/9]
G4ParticleDefinition * G4IonTable::GetIon (G4int Z, G4int A, G4double E, char flbChar, G4int J = 0)
Definition at line 575 of file G4IonTable.cc.
GetIon() [3/9]
G4ParticleDefinition * G4IonTable::GetIon (G4int Z, G4int A, G4double E, G4int J = 0)
Definition at line 569 of file G4IonTable.cc.
GetIon() [4/9]
G4ParticleDefinition * G4IonTable::GetIon (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb, G4int J = 0)
Definition at line 582 of file G4IonTable.cc.
GetIon() [5/9]
G4ParticleDefinition * G4IonTable::GetIon (G4int Z, G4int A, G4int L, G4double E, char flbChar, G4int J = 0)
Definition at line 625 of file G4IonTable.cc.
GetIon() [6/9]
G4ParticleDefinition * G4IonTable::GetIon (G4int Z, G4int A, G4int L, G4double E, G4int J = 0)
Definition at line 619 of file G4IonTable.cc.
GetIon() [7/9]
G4ParticleDefinition * G4IonTable::GetIon (G4int Z, G4int A, G4int L, G4double E, G4Ions::G4FloatLevelBase flb, G4int J = 0)
Definition at line 632 of file G4IonTable.cc.
GetIon() [8/9]
G4ParticleDefinition * G4IonTable::GetIon (G4int Z, G4int A, G4int L, G4int lvl)
Definition at line 519 of file G4IonTable.cc.
GetIon() [9/9]
G4ParticleDefinition * G4IonTable::GetIon (G4int Z, G4int A, G4int lvl = 0)
Definition at line 483 of file G4IonTable.cc.
Referenced by G4ParticleHPFinalState::adjust_final_state(), G4ParticleHPFissionFS::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4LENDModel::ApplyYourself(), G4ParticleHPChannelList::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4ExcitationHandler::BreakItUp(), G4EmCorrections::BuildCorrectionVector(), G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), G4ParticleHPInelasticCompFS::CompositeApply(), G4DNARuddIonisationExtendedModel::CrossSectionPerVolume(), G4ITDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecay::DecayIt(), G4EmCalculator::FindIon(), G4AlphaDecay::G4AlphaDecay(), G4BetaMinusDecay::G4BetaMinusDecay(), G4BetaPlusDecay::G4BetaPlusDecay(), G4ECDecay::G4ECDecay(), G4ITDecay::G4ITDecay(), G4NeutronDecay::G4NeutronDecay(), G4ProtonDecay::G4ProtonDecay(), HadrontherapyPrimaryGeneratorAction::GeneratePrimaries(), B3PrimaryGeneratorAction::GeneratePrimaries(), G4NuclNuclDiffuseElastic::GetInvCoulombElasticXsc(), G4DiffuseElastic::GetInvCoulombElasticXsc(), G4NuclNuclDiffuseElastic::GetInvElasticSumXsc(), G4DiffuseElastic::GetInvElasticSumXsc(), G4NuclNuclDiffuseElastic::GetInvElasticXsc(), G4DiffuseElastic::GetInvElasticXsc(), GetIon(), GetMuonicAtom(), G4FissionProductYieldDist::GetParticleDefinition(), G4ChipsHyperonElasticXS::GetQ2max(), G4ChipsProtonElasticXS::GetQ2max(), G4ChipsKaonPlusElasticXS::GetQ2max(), G4ChipsPionPlusElasticXS::GetQ2max(), G4ChipsPionMinusElasticXS::GetQ2max(), G4ChipsAntiBaryonElasticXS::GetQ2max(), G4ChipsKaonMinusElasticXS::GetQ2max(), G4ChipsNeutronElasticXS::GetQ2max(), G4BinaryCascade::HighEnergyModelFSProducts(), G4DNARuddIonisationExtendedModel::Initialise(), G4ParticleGunMessenger::IonCommand(), G4GeneralParticleSourceMessenger::IonCommand(), G4ParticleGunMessenger::IonLevelCommand(), G4GeneralParticleSourceMessenger::IonLvlCommand(), G4InuclNuclei::makeDefinition(), PreloadNuclide(), G4BetheHeitler5DModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4eCoulombScatteringModel::SampleSecondaries(), G4QuasiElasticChannel::Scatter(), G4ScreenedCoulombCrossSection::SelectRandomUnweightedTarget(), DMXParticleSourceMessenger::SetNewValue(), G4AblaInterface::toG4ParticleDefinition(), and G4INCLXXInterface::toG4ParticleDefinition().
GetIonMass()
G4double G4IonTable::GetIonMass (G4int Z, G4int A, G4int L = 0, G4int lvl = 0) const
Definition at line 1309 of file G4IonTable.cc.
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4BinaryLightIonReaction::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4IonDEDXScalingICRU73::CreateReferenceParticles(), G4BinaryLightIonReaction::DeExciteSpectatorNucleus(), G4BinaryLightIonReaction::FuseNucleiAndPrompound(), G4TripathiCrossSection::GetElementCrossSection(), G4BinaryCascade::GetIonMass(), G4StatMFFragment::GetNuclearMass(), G4FTFModel::Init(), G4BinaryLightIonReaction::Interact(), and G4BinaryLightIonReaction::SetLighterAsProjectile().
GetIonName() [1/4]
const G4String & G4IonTable::GetIonName (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb = G4Ions::G4FloatLevelBase::no_Float) const
Definition at line 1022 of file G4IonTable.cc.
GetIonName() [2/4]
const G4String & G4IonTable::GetIonName (G4int Z, G4int A, G4int L, G4double E, G4Ions::G4FloatLevelBase flb = G4Ions::G4FloatLevelBase::no_Float) const
Definition at line 1055 of file G4IonTable.cc.
GetIonName() [3/4]
const G4String & G4IonTable::GetIonName (G4int Z, G4int A, G4int L, G4int lvl) const
Definition at line 1109 of file G4IonTable.cc.
GetIonName() [4/4]
const G4String & G4IonTable::GetIonName (G4int Z, G4int A, G4int lvl = 0) const
Definition at line 1071 of file G4IonTable.cc.
Referenced by G4INCLXXInterface::ApplyYourself(), CreateIon(), GetIonName(), G4LENDManager::GetLENDTarget(), and GetMuonicAtom().
GetIonTable()
static G4IonTable* G4IonTable::GetIonTable () inline static
Definition at line 77 of file G4IonTable.hh.
Referenced by G4ParticleHPFinalState::adjust_final_state(), G4NRESP71M03::ApplyMechanismABE(), G4ParticleHPFissionFS::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4LENDModel::ApplyYourself(), G4ParticleHPChannelList::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDFission::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4ParticleHPInelasticBaseFS::BaseApply(), G4ParticleHPInelasticCompFS::CompositeApply(), G4IonDEDXScalingICRU73::CreateReferenceParticles(), G4DNARuddIonisationExtendedModel::CrossSectionPerVolume(), G4BetheHeitler5DModel::G4BetheHeitler5DModel(), HadrontherapyPrimaryGeneratorAction::GeneratePrimaries(), B3PrimaryGeneratorAction::GeneratePrimaries(), G4DNARuddIonisationExtendedModel::Initialise(), G4FissionProductYieldDist::Initialize(), G4ParticleGunMessenger::IonCommand(), G4GeneralParticleSourceMessenger::IonCommand(), G4ParticleGunMessenger::IonLevelCommand(), G4GeneralParticleSourceMessenger::IonLvlCommand(), G4ParticleHPIsotropic::Sample(), G4ParticleHPContAngularPar::Sample(), G4ScreenedCoulombCrossSection::SelectRandomUnweightedTarget(), DMXParticleSourceMessenger::SetNewValue(), G4AblaInterface::toG4ParticleDefinition(), and G4ParticleHPInelasticCompFS::two_body_reaction().
GetIsomerMass()
G4double G4IonTable::GetIsomerMass (G4int Z, G4int A, G4int lvl = 0) const
Definition at line 1303 of file G4IonTable.cc.
GetIsotopeTable()
G4VIsotopeTable * G4IonTable::GetIsotopeTable (size_t idx = 0) const
Definition at line 1553 of file G4IonTable.cc.
GetLifeTime() [1/3]
G4double G4IonTable::GetLifeTime (const G4ParticleDefinition * particle) const
Definition at line 1827 of file G4IonTable.cc.
Referenced by GetLifeTime().
GetLifeTime() [2/3]
G4double G4IonTable::GetLifeTime (G4int Z, G4int A, G4double E, char flbChar) const
Definition at line 1838 of file G4IonTable.cc.
GetLifeTime() [3/3]
G4double G4IonTable::GetLifeTime (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb = G4Ions::G4FloatLevelBase::no_Float) const
Definition at line 1844 of file G4IonTable.cc.
GetLightAntiIon()
G4ParticleDefinition * G4IonTable::GetLightAntiIon (G4int Z, G4int A) const protected
Definition at line 1216 of file G4IonTable.cc.
GetLightIon()
G4ParticleDefinition * G4IonTable::GetLightIon (G4int Z, G4int A) const protected
Definition at line 1191 of file G4IonTable.cc.
Referenced by FindIon(), and GetNucleusMass().
GetMuonicAtom() [1/2]
G4ParticleDefinition * G4IonTable::GetMuonicAtom (G4int Z, G4int A)
Definition at line 1935 of file G4IonTable.cc.
GetMuonicAtom() [2/2]
G4ParticleDefinition * G4IonTable::GetMuonicAtom (G4Ions const * base)
Definition at line 1855 of file G4IonTable.cc.
Referenced by G4MuonMinusAtomicCapture::AtRestDoIt(), and GetMuonicAtom().
GetNucleusByEncoding() [1/2]
G4bool G4IonTable::GetNucleusByEncoding (G4int encoding, G4int & Z, G4int & A, G4double & E, G4int & lvl) static
Definition at line 967 of file G4IonTable.cc.
Referenced by GetIon().
GetNucleusByEncoding() [2/2]
G4bool G4IonTable::GetNucleusByEncoding (G4int encoding, G4int & Z, G4int & A, G4int & L, G4double & E, G4int & lvl) static
!!not supported for excitation states !!!
Definition at line 988 of file G4IonTable.cc.
GetNucleusEncoding() [1/2]
G4int G4IonTable::GetNucleusEncoding (G4int Z, G4int A, G4double E = 0.0, G4int lvl = 0) static
Definition at line 926 of file G4IonTable.cc.
Referenced by Contains(), CreateIon(), FindIon(), FindIonInMaster(), GetMuonicAtom(), G4LENDManager::GetNucleusEncoding(), GetNucleusEncoding(), GetNucleusMass(), Insert(), InsertWorker(), G4InuclNuclei::makeNuclearFragment(), and Remove().
GetNucleusEncoding() [2/2]
G4int G4IonTable::GetNucleusEncoding (G4int Z, G4int A, G4int L, G4double E = 0.0, G4int lvl = 0) static
Definition at line 947 of file G4IonTable.cc.
GetNucleusMass()
G4double G4IonTable::GetNucleusMass (G4int Z, G4int A, G4int L = 0, G4int lvl = 0) const
Definition at line 1244 of file G4IonTable.cc.
Referenced by CreateIon(), GetIonMass(), and GetIsomerMass().
GetNumberOfElements()
G4int G4IonTable::GetNumberOfElements () const inline
Definition at line 345 of file G4IonTable.hh.
GetParticle()
G4ParticleDefinition * G4IonTable::GetParticle (G4int index) const
Definition at line 1639 of file G4IonTable.cc.
Referenced by DMXPhysicsList::ConstructGeneral().
GetVerboseLevel()
G4int G4IonTable::GetVerboseLevel () const protected
Definition at line 1471 of file G4IonTable.cc.
Referenced by AddProcessManager(), clear(), CreateIon(), FindIon(), GetIon(), GetNucleusMass(), GetParticle(), and Remove().
InitializeLightIons()
void G4IonTable::InitializeLightIons ()
Definition at line 173 of file G4IonTable.cc.
Referenced by G4RunManagerKernel::SetupPhysics().
Insert()
void G4IonTable::Insert (const G4ParticleDefinition * particle)
Definition at line 1337 of file G4IonTable.cc.
Referenced by G4ParticleTable::Insert().
InsertWorker()
void G4IonTable::InsertWorker (const G4ParticleDefinition * particle) protected
Definition at line 1352 of file G4IonTable.cc.
Referenced by GetIon().
IsAntiIon()
G4bool G4IonTable::IsAntiIon (const G4ParticleDefinition * particle) static
Definition at line 1147 of file G4IonTable.cc.
Referenced by G4ParticleDefinition::DumpTable(), and G4ParticleDefinition::G4ParticleDefinition().
IsIon()
G4bool G4IonTable::IsIon (const G4ParticleDefinition * particle) static
Definition at line 1124 of file G4IonTable.cc.
Referenced by G4DynamicParticle::AllocateElectronOccupancy(), Contains(), G4ParticleDefinition::DumpTable(), G4ParticleDefinition::G4ParticleDefinition(), GetMuonicAtom(), G4ParticleTable::Insert(), Insert(), G4ParticleTable::Remove(), and Remove().
IsLightAntiIon()
G4bool G4IonTable::IsLightAntiIon (const G4ParticleDefinition * particle) const protected
Definition at line 1181 of file G4IonTable.cc.
IsLightIon()
G4bool G4IonTable::IsLightIon (const G4ParticleDefinition * particle) const protected
Definition at line 1172 of file G4IonTable.cc.
operator=()
G4IonTable& G4IonTable::operator= (const G4IonTable &) inline protected
Definition at line 92 of file G4IonTable.hh.
PreloadNuclide()
void G4IonTable::PreloadNuclide ()
Definition at line 1620 of file G4IonTable.cc.
Referenced by CreateAllIon(), and CreateAllIsomer().
PrepareNuclideTable()
void G4IonTable::PrepareNuclideTable ()
Definition at line 1614 of file G4IonTable.cc.
Referenced by G4IonTable().
RegisterIsotopeTable()
void G4IonTable::RegisterIsotopeTable (G4VIsotopeTable * table)
Definition at line 1540 of file G4IonTable.cc.
Referenced by G4IonTable().
Remove()
void G4IonTable::Remove (const G4ParticleDefinition * particle)
Definition at line 1378 of file G4IonTable.cc.
Referenced by G4ParticleTable::Remove().
size()
G4int G4IonTable::size () const
Definition at line 1691 of file G4IonTable.cc.
Referenced by GetIsotopeTable().
SlaveG4IonTable()
void G4IonTable::SlaveG4IonTable ()
Definition at line 149 of file G4IonTable.cc.
WorkerG4IonTable()
void G4IonTable::WorkerG4IonTable ()
Definition at line 154 of file G4IonTable.cc.
Referenced by G4ParticleTable::WorkerG4ParticleTable().
Field Documentation
elementName
const G4String G4IonTable::elementName static
Initial value:
= {
  "H",                                                                                                "He",
  "Li", "Be",                                                             "B",  "C",  "N",  "O", "F", "Ne",
  "Na", "Mg",                                                             "Al", "Si", "P", "S", "Cl", "Ar",
  "K", "Ca", "Sc", "Ti", "V", "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "Ga", "Ge", "As", "Se", "Br", "Kr",
  "Rb", "Sr", "Y", "Zr", "Nb", "Mo","Tc", "Ru", "Rh", "Pd", "Ag", "Cd", "In", "Sn", "Sb", "Te", "I",  "Xe",
  "Cs", "Ba",
              "La", "Ce", "Pr", "Nd", "Pm", "Sm", "Eu", "Gd", "Tb", "Dy", "Ho", "Er", "Tm", "Yb", "Lu",
                   "Hf", "Ta", "W", "Re", "Os", "Ir", "Pt", "Au", "Hg", "Tl", "Pb", "Bi", "Po", "At", "Rn",
  "Fr", "Ra",
              "Ac", "Th", "Pa",  "U", "Np", "Pu", "Am", "Cm", "Bk", "Cf", "Es", "Fm", "Md", "No", "Lr",
              "Rf", "Db", "Sg", "Bh", "Hs", "Mt", "Ds", "Rg", "Cn", "Nh", "Fl", "Mc", "Lv", "Ts", "Og"
}
Definition at line 327 of file G4IonTable.hh.
Referenced by GetIonName().
fIonList
G4ThreadLocal G4IonTable::G4IonList * G4IonTable::fIonList = nullptr static
Definition at line 315 of file G4IonTable.hh.
Referenced by clear(), DestroyWorkerG4IonTable(), DumpTable(), Entries(), FindIon(), G4IonTable(), GetMuonicAtom(), GetNucleusMass(), GetParticle(), InsertWorker(), size(), WorkerG4IonTable(), and ~G4IonTable().
fIonListShadow
G4IonTable::G4IonList * G4IonTable::fIonListShadow = nullptr static
Definition at line 317 of file G4IonTable.hh.
Referenced by Contains(), FindIonInMaster(), G4IonTable(), GetMuonicAtom(), Insert(), Remove(), and WorkerG4IonTable().
fIsotopeTableList
G4ThreadLocal std::vector< G4VIsotopeTable * > * G4IonTable::fIsotopeTableList = nullptr static
Definition at line 316 of file G4IonTable.hh.
Referenced by DestroyWorkerG4IonTable(), FindIsotope(), G4IonTable(), RegisterIsotopeTable(), WorkerG4IonTable(), and ~G4IonTable().
fIsotopeTableListShadow
std::vector< G4VIsotopeTable * > * G4IonTable::fIsotopeTableListShadow = nullptr static
Definition at line 318 of file G4IonTable.hh.
Referenced by G4IonTable(), and WorkerG4IonTable().
isIsomerCreated
G4bool G4IonTable::isIsomerCreated private
Definition at line 311 of file G4IonTable.hh.
Referenced by PreloadNuclide().
n_error
G4int G4IonTable::n_error private
Definition at line 333 of file G4IonTable.hh.
pNuclideTable
G4NuclideTable* G4IonTable::pNuclideTable private
Definition at line 310 of file G4IonTable.hh.
Referenced by FindIon(), FindIonInMaster(), G4IonTable(), GetLifeTime(), PreloadNuclide(), and PrepareNuclideTable().
The documentation for this class was generated from the following files:
source/particles/management/include/G4IonTable.hh
source/particles/management/src/G4IonTable.cc