Geant4: source/processes/electromagnetic/dna/management/src/G4KDTreeResult.cc File Reference
G4KDTreeResult.cc File Reference
#include "G4KDTreeResult.hh"
Data Structures
struct ResNode
Functions
G4Allocator< G4KDTreeResult > *& aKDTreeAllocator ()
bool CompareResNode (const ResNode &left, const ResNode &right)
Function Documentation
aKDTreeAllocator()
G4Allocator<G4KDTreeResult>*& aKDTreeAllocator ()
Definition at line 39 of file G4KDTreeResult.cc.
Referenced by G4KDTreeResult::operator delete(), and G4KDTreeResult::operator new().
CompareResNode()
bool CompareResNode (const ResNode & left, const ResNode & right)
Definition at line 81 of file G4KDTreeResult.cc.
Referenced by G4KDTreeResult::Sort().