Geant4: G4UIcmdWithADouble Class Reference
G4UIcmdWithADouble Class Reference
#include <G4UIcmdWithADouble.hh>
Public Member Functions
G4UIcmdWithADouble (const char *theCommandPath, G4UImessenger *theMessenger)
void SetParameterName (const char *theName, G4bool omittable, G4bool currentAsDefault=false)
void SetDefaultValue (G4double defVal)
Public Member Functions inherited from G4UIcommand
G4UIcommand ()
G4UIcommand (const char *theCommandPath, G4UImessenger *theMessenger, G4bool tBB=true)
virtual ~G4UIcommand ()
G4bool operator== (const G4UIcommand &right) const
G4bool operator!= (const G4UIcommand &right) const
virtual G4int DoIt (G4String parameterList)
G4String GetCurrentValue ()
void AvailableForStates (G4ApplicationState s1)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3, G4ApplicationState s4)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3, G4ApplicationState s4, G4ApplicationState s5)
G4bool IsAvailable ()
virtual void List ()
void SetRange (const char *rs)
const G4String & GetRange () const
G4int GetGuidanceEntries () const
const G4String & GetGuidanceLine (G4int i) const
const G4String & GetCommandPath () const
const G4String & GetCommandName () const
G4int GetParameterEntries () const
G4UIparameter * GetParameter (G4int i) const
std::vector< G4ApplicationState > * GetStateList ()
G4UImessenger * GetMessenger () const
void SetParameter (G4UIparameter *const newParameter)
void SetGuidance (const char *aGuidance)
const G4String GetTitle () const
void SetToBeBroadcasted (G4bool val)
G4bool ToBeBroadcasted () const
void SetToBeFlushed (G4bool val)
G4bool ToBeFlushed () const
void SetWorkerThreadOnly (G4bool val=true)
G4bool IsWorkerThreadOnly () const
void CommandFailed (G4int errCode, G4ExceptionDescription &ed)
void CommandFailed (G4ExceptionDescription &ed)
G4int IfCommandFailed ()
G4String & GetFailureDescription ()
void ResetFailure ()
Static Public Member Functions
static G4double GetNewDoubleValue (const char *paramString)
Static Public Member Functions inherited from G4UIcommand
static G4String ConvertToString (G4bool boolVal)
static G4String ConvertToString (G4int intValue)
static G4String ConvertToString (G4double doubleValue)
static G4String ConvertToString (G4double doubleValue, const char *unitName)
static G4String ConvertToString (G4ThreeVector vec)
static G4String ConvertToString (G4ThreeVector vec, const char *unitName)
static G4bool ConvertToBool (const char *st)
static G4int ConvertToInt (const char *st)
static G4double ConvertToDouble (const char *st)
static G4double ConvertToDimensionedDouble (const char *st)
static G4ThreeVector ConvertTo3Vector (const char *st)
static G4ThreeVector ConvertToDimensioned3Vector (const char *st)
static G4double ValueOf (const char *unitName)
static G4String CategoryOf (const char *unitName)
static G4String UnitsList (const char *unitCategory)
Additional Inherited Members
Protected Member Functions inherited from G4UIcommand
G4int CheckNewValue (const char *newValue)
Protected Attributes inherited from G4UIcommand
G4bool toBeBroadcasted
G4bool toBeFlushed
G4bool workerThreadOnly
G4int commandFailureCode
G4String failureDescription
Detailed Description
Definition at line 40 of file G4UIcmdWithADouble.hh.
Constructor & Destructor Documentation
G4UIcmdWithADouble()
G4UIcmdWithADouble::G4UIcmdWithADouble (const char * theCommandPath, G4UImessenger * theMessenger)
Definition at line 33 of file G4UIcmdWithADouble.cc.
Member Function Documentation
GetNewDoubleValue()
G4double G4UIcmdWithADouble::GetNewDoubleValue (const char * paramString) static
Definition at line 40 of file G4UIcmdWithADouble.cc.
Referenced by G4HepRepMessenger::SetNewValue(), CCalPrimaryGeneratorMessenger::SetNewValue(), MyKleinNishinaMessenger::SetNewValue(), LXeDetectorMessenger::SetNewValue(), ClusteringAlgoMessenger::SetNewValue(), G4HadronicEPTestMessenger::SetNewValue(), WLSDetectorMessenger::SetNewValue(), G4EmMessenger::SetNewValue(), G4ErrorMessenger::SetNewValue(), GFlashShowerModelMessenger::SetNewValue(), CexmcPrimaryGeneratorActionMessenger::SetNewValue(), RMC01AnalysisManagerMessenger::SetNewValue(), CexmcEnergyDepositDigitizerMessenger::SetNewValue(), G4OpticalPhysicsMessenger::SetNewValue(), G4VisCommandSetLineWidth::SetNewValue(), G4DecayTableMessenger::SetNewValue(), G4EmParametersMessenger::SetNewValue(), G4VisCommandSetTextSize::SetNewValue(), G4GeneralParticleSourceMessenger::SetNewValue(), and G4VisCommandViewerZoom::SetNewValue().
SetDefaultValue()
void G4UIcmdWithADouble::SetDefaultValue (G4double defVal)
Definition at line 54 of file G4UIcmdWithADouble.cc.
Referenced by CCalPrimaryGeneratorMessenger::CCalPrimaryGeneratorMessenger(), CexmcEnergyDepositDigitizerMessenger::CexmcEnergyDepositDigitizerMessenger(), CexmcPrimaryGeneratorActionMessenger::CexmcPrimaryGeneratorActionMessenger(), G4EmParametersMessenger::G4EmParametersMessenger(), G4HadronicEPTestMessenger::G4HadronicEPTestMessenger(), G4HepRepMessenger::G4HepRepMessenger(), G4VisCommandSetLineWidth::G4VisCommandSetLineWidth(), G4VisCommandSetTextSize::G4VisCommandSetTextSize(), G4VisCommandsTouchableSet::G4VisCommandsTouchableSet(), and G4VisCommandsViewerSet::G4VisCommandsViewerSet().
SetParameterName()
void G4UIcmdWithADouble::SetParameterName (const char * theName, G4bool omittable, G4bool currentAsDefault = false)
Definition at line 46 of file G4UIcmdWithADouble.cc.
Referenced by CCalPrimaryGeneratorMessenger::CCalPrimaryGeneratorMessenger(), CexmcEnergyDepositDigitizerMessenger::CexmcEnergyDepositDigitizerMessenger(), CexmcPrimaryGeneratorActionMessenger::CexmcPrimaryGeneratorActionMessenger(), ClusteringAlgoMessenger::ClusteringAlgoMessenger(), G4BlineTracerMessenger::G4BlineTracerMessenger(), G4DecayTableMessenger::G4DecayTableMessenger(), G4EmParametersMessenger::G4EmParametersMessenger(), G4HadronicEPTestMessenger::G4HadronicEPTestMessenger(), G4HepRepMessenger::G4HepRepMessenger(), G4ModelCmdApplyDouble< M >::G4ModelCmdApplyDouble(), G4OpticalPhysicsMessenger::G4OpticalPhysicsMessenger(), G4VisCommandSetLineWidth::G4VisCommandSetLineWidth(), G4VisCommandSetTextSize::G4VisCommandSetTextSize(), G4VisCommandsTouchableSet::G4VisCommandsTouchableSet(), G4VisCommandsViewerSet::G4VisCommandsViewerSet(), GFlashShowerModelMessenger::GFlashShowerModelMessenger(), MyKleinNishinaMessenger::MyKleinNishinaMessenger(), RMC01AnalysisManagerMessenger::RMC01AnalysisManagerMessenger(), and WLSDetectorMessenger::WLSDetectorMessenger().
The documentation for this class was generated from the following files:
source/intercoms/include/G4UIcmdWithADouble.hh
source/intercoms/src/G4UIcmdWithADouble.cc