Geant4: G4MagInt_Driver Class Reference
G4MagInt_Driver Class Reference
#include <G4MagIntegratorDriver.hh>
Public Member Functions
G4MagInt_Driver (G4double hminimum, G4MagIntegratorStepper *pItsStepper, G4int numberOfComponents=6, G4int statisticsVerbosity=1)
virtual ~G4MagInt_Driver () override
G4MagInt_Driver (const G4MagInt_Driver &)=delete
G4MagInt_Driver & operator= (const G4MagInt_Driver &)=delete
virtual G4double AdvanceChordLimited (G4FieldTrack &track, G4double stepMax, G4double epsStep, G4double chordDistance) override
virtual void OnComputeStep () override
virtual void OnStartTracking () override
virtual G4bool AccurateAdvance (G4FieldTrack &y_current, G4double hstep, G4double eps, G4double hinitial=0.0) override
virtual G4bool QuickAdvance (G4FieldTrack &y_val, const G4double dydx[], G4double hstep, G4double inverseCurvatureRadius, G4double &dchord_step, G4double &dyerr) override
G4bool QuickAdvance (G4FieldTrack &y_posvel, const G4double dydx[], G4double hstep, G4double &dchord_step, G4double &dyerr_pos_sq, G4double &dyerr_mom_rel_sq)
G4double GetHmin () const
G4double Hmin () const
G4double GetSafety () const
G4double GetPshrnk () const
G4double GetPgrow () const
G4double GetErrcon () const
virtual void GetDerivatives (const G4FieldTrack &y_curr, G4double dydx[]) const override
virtual void GetDerivatives (const G4FieldTrack &track, G4double dydx[], G4double field[]) const override
virtual G4EquationOfMotion * GetEquationOfMotion () override
virtual void SetEquationOfMotion (G4EquationOfMotion *equation) override
virtual void RenewStepperAndAdjust (G4MagIntegratorStepper *pItsStepper) override
void ReSetParameters (G4double new_safety=0.9)
void SetSafety (G4double valS)
void SetPshrnk (G4double valPs)
void SetPgrow (G4double valPg)
void SetErrcon (G4double valEc)
G4double ComputeAndSetErrcon ()
virtual const G4MagIntegratorStepper * GetStepper () const override
virtual G4MagIntegratorStepper * GetStepper () override
void OneGoodStep (G4double ystart[], const G4double dydx[], G4double &x, G4double htry, G4double eps, G4double &hdid, G4double &hnext)
virtual G4double ComputeNewStepSize (G4double errMaxNorm, G4double hstepCurrent) override
G4double ComputeNewStepSize_WithinLimits (G4double errMaxNorm, G4double hstepCurrent)
G4int GetMaxNoSteps () const
void SetMaxNoSteps (G4int val)
void SetHmin (G4double newval)
virtual void SetVerboseLevel (G4int newLevel) override
virtual G4int GetVerboseLevel () const override
G4double GetSmallestFraction () const
void SetSmallestFraction (G4double val)
Public Member Functions inherited from G4VIntegrationDriver
virtual ~G4VIntegrationDriver ()=default
virtual G4double GetInverseCurvatureRadius (const G4FieldTrack &track, G4double field[]) const
Public Member Functions inherited from G4ChordFinderDelegate< G4MagInt_Driver >
virtual ~G4ChordFinderDelegate ()
G4double AdvanceChordLimitedImpl (G4FieldTrack &track, G4double hstep, G4double eps, G4double chordDistance)
void ResetStepEstimate ()
void TestChordPrint (G4int noTrials, G4int lastStepTrial, G4double dChordStep, G4double fDeltaChord, G4double nextStepTrial)
G4int GetNoCalls ()
G4int GetNoTrials ()
G4int GetNoMaxTrials ()
void SetFractions_Last_Next (G4double fractLast=0.90, G4double fractNext=0.95)
void SetFirstFraction (G4double fractFirst)
G4double GetFirstFraction ()
G4double GetFractionLast ()
G4double GetFractionNextEstimate ()
G4double GetLastStepEstimateUnc ()
void SetLastStepEstimateUnc (G4double stepEst)
Protected Member Functions
void WarnSmallStepSize (G4double hnext, G4double hstep, G4double h, G4double xDone, G4int noSteps)
void WarnTooManyStep (G4double x1start, G4double x2end, G4double xCurrent)
void WarnEndPointTooFar (G4double endPointDist, G4double hStepSize, G4double epsilonRelative, G4int debugFlag)
void PrintStatus (const G4double *StartArr, G4double xstart, const G4double *CurrentArr, G4double xcurrent, G4double requestStep, G4int subStepNo)
void PrintStatus (const G4FieldTrack &StartFT, const G4FieldTrack &CurrentFT, G4double requestStep, G4int subStepNo)
void PrintStat_Aux (const G4FieldTrack &aFieldTrack, G4double requestStep, G4double actualStep, G4int subStepNo, G4double subStepSize, G4double dotVelocities)
void PrintStatisticsReport ()
Private Types
using ChordFinderDelegate = G4ChordFinderDelegate< G4MagInt_Driver >
Private Attributes
G4double fMinimumStep
G4double fSmallestFraction
const G4int fNoIntegrationVariables
const G4int fMinNoVars
const G4int fNoVars
G4int fMaxNoSteps
G4int fMaxStepBase
G4double safety
G4double pshrnk
G4double pgrow
G4double errcon
G4int fStatisticsVerboseLevel
G4MagIntegratorStepper * pIntStepper
unsigned long fNoTotalSteps
unsigned long fNoBadSteps
unsigned long fNoSmallSteps
unsigned long fNoInitialSmallSteps
unsigned long fNoCalls
G4double fDyerr_max
G4double fDyerr_mx2
G4double fDyerrPos_smTot
G4double fDyerrPos_lgTot
G4double fDyerrVel_lgTot
G4double fSumH_sm
G4double fSumH_lg
G4int fVerboseLevel
Additional Inherited Members
Protected Types inherited from G4VIntegrationDriver
using State = G4double[G4FieldTrack::ncompSVEC]
Static Protected Attributes inherited from G4VIntegrationDriver
static constexpr G4double UNKNOWN_CURVATURE_RADIUS = -1
static constexpr G4double max_stepping_increase = 5
static constexpr G4double max_stepping_decrease = 0.1
Detailed Description
Definition at line 47 of file G4MagIntegratorDriver.hh.
Member Typedef Documentation
ChordFinderDelegate
using G4MagInt_Driver::ChordFinderDelegate = G4ChordFinderDelegate<G4MagInt_Driver> private
Definition at line 270 of file G4MagIntegratorDriver.hh.
Constructor & Destructor Documentation
G4MagInt_Driver() [1/2]
G4MagInt_Driver::G4MagInt_Driver (G4double hminimum, G4MagIntegratorStepper * pItsStepper, G4int numberOfComponents = 6, G4int statisticsVerbosity = 1)
Definition at line 53 of file G4MagIntegratorDriver.cc.
~G4MagInt_Driver()
G4MagInt_Driver::~G4MagInt_Driver () override virtual
Definition at line 102 of file G4MagIntegratorDriver.cc.
G4MagInt_Driver() [2/2]
G4MagInt_Driver::G4MagInt_Driver (const G4MagInt_Driver &) delete
Member Function Documentation
AccurateAdvance()
G4bool G4MagInt_Driver::AccurateAdvance (G4FieldTrack & y_current, G4double hstep, G4double eps, G4double hinitial = 0.0) override virtual
Implements G4VIntegrationDriver.
Definition at line 113 of file G4MagIntegratorDriver.cc.
Referenced by G4RKPropagation::FieldTransport().
AdvanceChordLimited()
virtual G4double G4MagInt_Driver::AdvanceChordLimited (G4FieldTrack & track, G4double stepMax, G4double epsStep, G4double chordDistance) inline override virtual
Implements G4VIntegrationDriver.
Definition at line 63 of file G4MagIntegratorDriver.hh.
ComputeAndSetErrcon()
G4double G4MagInt_Driver::ComputeAndSetErrcon () inline
ComputeNewStepSize()
G4double G4MagInt_Driver::ComputeNewStepSize (G4double errMaxNorm, G4double hstepCurrent) override virtual
Implements G4VIntegrationDriver.
Definition at line 748 of file G4MagIntegratorDriver.cc.
Referenced by AccurateAdvance(), and QuickAdvance().
ComputeNewStepSize_WithinLimits()
G4double G4MagInt_Driver::ComputeNewStepSize_WithinLimits (G4double errMaxNorm, G4double hstepCurrent)
Definition at line 781 of file G4MagIntegratorDriver.cc.
GetDerivatives() [1/2]
void G4MagInt_Driver::GetDerivatives (const G4FieldTrack & track, G4double dydx[], G4double field[]) const override virtual
Implements G4VIntegrationDriver.
Definition at line 1011 of file G4MagIntegratorDriver.cc.
GetDerivatives() [2/2]
virtual void G4MagInt_Driver::GetDerivatives (const G4FieldTrack & y_curr, G4double dydx[]) const override virtual
Implements G4VIntegrationDriver.
GetEquationOfMotion()
G4EquationOfMotion * G4MagInt_Driver::GetEquationOfMotion () override virtual
Implements G4VIntegrationDriver.
Definition at line 1020 of file G4MagIntegratorDriver.cc.
GetErrcon()
G4double G4MagInt_Driver::GetErrcon () const inline
GetHmin()
G4double G4MagInt_Driver::GetHmin () const inline
GetMaxNoSteps()
G4int G4MagInt_Driver::GetMaxNoSteps () const inline
GetPgrow()
G4double G4MagInt_Driver::GetPgrow () const inline
Referenced by ComputeNewStepSize(), ComputeNewStepSize_WithinLimits(), and OneGoodStep().
GetPshrnk()
G4double G4MagInt_Driver::GetPshrnk () const inline
Referenced by ComputeNewStepSize(), ComputeNewStepSize_WithinLimits(), and OneGoodStep().
GetSafety()
G4double G4MagInt_Driver::GetSafety () const inline
Referenced by ComputeNewStepSize(), ComputeNewStepSize_WithinLimits(), and OneGoodStep().
GetSmallestFraction()
G4double G4MagInt_Driver::GetSmallestFraction () const inline
GetStepper() [1/2]
const G4MagIntegratorStepper * G4MagInt_Driver::GetStepper () const override virtual
Implements G4VIntegrationDriver.
Definition at line 1030 of file G4MagIntegratorDriver.cc.
GetStepper() [2/2]
G4MagIntegratorStepper * G4MagInt_Driver::GetStepper () override virtual
Implements G4VIntegrationDriver.
Definition at line 1035 of file G4MagIntegratorDriver.cc.
GetVerboseLevel()
virtual G4int G4MagInt_Driver::GetVerboseLevel () const override virtual
Implements G4VIntegrationDriver.
Hmin()
G4double G4MagInt_Driver::Hmin () const inline
Referenced by AccurateAdvance(), and WarnSmallStepSize().
OnComputeStep()
virtual void G4MagInt_Driver::OnComputeStep () inline override virtual
Implements G4VIntegrationDriver.
Definition at line 71 of file G4MagIntegratorDriver.hh.
OneGoodStep()
void G4MagInt_Driver::OneGoodStep (G4double ystart[], const G4double dydx[], G4double & x, G4double htry, G4double eps, G4double & hdid, G4double & hnext)
Definition at line 501 of file G4MagIntegratorDriver.cc.
Referenced by AccurateAdvance().
OnStartTracking()
virtual void G4MagInt_Driver::OnStartTracking () inline override virtual
Implements G4VIntegrationDriver.
Definition at line 76 of file G4MagIntegratorDriver.hh.
operator=()
G4MagInt_Driver& G4MagInt_Driver::operator= (const G4MagInt_Driver &) delete
PrintStat_Aux()
void G4MagInt_Driver::PrintStat_Aux (const G4FieldTrack & aFieldTrack, G4double requestStep, G4double actualStep, G4int subStepNo, G4double subStepSize, G4double dotVelocities) protected
Definition at line 902 of file G4MagIntegratorDriver.cc.
Referenced by PrintStatus().
PrintStatisticsReport()
void G4MagInt_Driver::PrintStatisticsReport () protected
Definition at line 968 of file G4MagIntegratorDriver.cc.
Referenced by ~G4MagInt_Driver().
PrintStatus() [1/2]
void G4MagInt_Driver::PrintStatus (const G4double * StartArr, G4double xstart, const G4double * CurrentArr, G4double xcurrent, G4double requestStep, G4int subStepNo) protected
Definition at line 813 of file G4MagIntegratorDriver.cc.
Referenced by AccurateAdvance(), and QuickAdvance().
PrintStatus() [2/2]
void G4MagInt_Driver::PrintStatus (const G4FieldTrack & StartFT, const G4FieldTrack & CurrentFT, G4double requestStep, G4int subStepNo) protected
Definition at line 838 of file G4MagIntegratorDriver.cc.
QuickAdvance() [1/2]
G4bool G4MagInt_Driver::QuickAdvance (G4FieldTrack & y_posvel, const G4double dydx[], G4double hstep, G4double & dchord_step, G4double & dyerr_pos_sq, G4double & dyerr_mom_rel_sq)
Definition at line 629 of file G4MagIntegratorDriver.cc.
QuickAdvance() [2/2]
G4bool G4MagInt_Driver::QuickAdvance (G4FieldTrack & y_val, const G4double dydx[], G4double hstep, G4double inverseCurvatureRadius, G4double & dchord_step, G4double & dyerr) override virtual
Reimplemented from G4VIntegrationDriver.
Definition at line 648 of file G4MagIntegratorDriver.cc.
Referenced by AccurateAdvance().
RenewStepperAndAdjust()
void G4MagInt_Driver::RenewStepperAndAdjust (G4MagIntegratorStepper * pItsStepper) override virtual
Reimplemented from G4VIntegrationDriver.
Definition at line 1041 of file G4MagIntegratorDriver.cc.
Referenced by F02ElectricFieldSetup::CreateStepper(), and G4MagInt_Driver().
ReSetParameters()
void G4MagInt_Driver::ReSetParameters (G4double new_safety = 0.9) inline
Referenced by RenewStepperAndAdjust().
SetEquationOfMotion()
void G4MagInt_Driver::SetEquationOfMotion (G4EquationOfMotion * equation) override virtual
Implements G4VIntegrationDriver.
Definition at line 1025 of file G4MagIntegratorDriver.cc.
SetErrcon()
void G4MagInt_Driver::SetErrcon (G4double valEc) inline
SetHmin()
void G4MagInt_Driver::SetHmin (G4double newval) inline
SetMaxNoSteps()
void G4MagInt_Driver::SetMaxNoSteps (G4int val) inline
SetPgrow()
void G4MagInt_Driver::SetPgrow (G4double valPg) inline
SetPshrnk()
void G4MagInt_Driver::SetPshrnk (G4double valPs) inline
SetSafety()
void G4MagInt_Driver::SetSafety (G4double valS) inline
SetSmallestFraction()
void G4MagInt_Driver::SetSmallestFraction (G4double val)
Definition at line 985 of file G4MagIntegratorDriver.cc.
SetVerboseLevel()
virtual void G4MagInt_Driver::SetVerboseLevel (G4int newLevel) override virtual
Implements G4VIntegrationDriver.
WarnEndPointTooFar()
void G4MagInt_Driver::WarnEndPointTooFar (G4double endPointDist, G4double hStepSize, G4double epsilonRelative, G4int debugFlag) protected
Definition at line 465 of file G4MagIntegratorDriver.cc.
Referenced by AccurateAdvance().
WarnSmallStepSize()
void G4MagInt_Driver::WarnSmallStepSize (G4double hnext, G4double hstep, G4double h, G4double xDone, G4int noSteps) protected
Definition at line 416 of file G4MagIntegratorDriver.cc.
Referenced by AccurateAdvance().
WarnTooManyStep()
void G4MagInt_Driver::WarnTooManyStep (G4double x1start, G4double x2end, G4double xCurrent) protected
Definition at line 448 of file G4MagIntegratorDriver.cc.
Referenced by AccurateAdvance().
Field Documentation
errcon
G4double G4MagInt_Driver::errcon private
Definition at line 248 of file G4MagIntegratorDriver.hh.
Referenced by ComputeNewStepSize_WithinLimits(), and OneGoodStep().
fDyerr_max
G4double G4MagInt_Driver::fDyerr_max private
Definition at line 262 of file G4MagIntegratorDriver.hh.
Referenced by AccurateAdvance().
fDyerr_mx2
G4double G4MagInt_Driver::fDyerr_mx2 private
Definition at line 262 of file G4MagIntegratorDriver.hh.
fDyerrPos_lgTot
G4double G4MagInt_Driver::fDyerrPos_lgTot private
Definition at line 263 of file G4MagIntegratorDriver.hh.
fDyerrPos_smTot
G4double G4MagInt_Driver::fDyerrPos_smTot private
Definition at line 263 of file G4MagIntegratorDriver.hh.
Referenced by AccurateAdvance().
fDyerrVel_lgTot
G4double G4MagInt_Driver::fDyerrVel_lgTot private
Definition at line 263 of file G4MagIntegratorDriver.hh.
fMaxNoSteps
G4int G4MagInt_Driver::fMaxNoSteps private
Definition at line 242 of file G4MagIntegratorDriver.hh.
Referenced by AccurateAdvance(), and G4MagInt_Driver().
fMaxStepBase
G4int G4MagInt_Driver::fMaxStepBase private
Definition at line 243 of file G4MagIntegratorDriver.hh.
Referenced by G4MagInt_Driver().
fMinimumStep
G4double G4MagInt_Driver::fMinimumStep private
Definition at line 232 of file G4MagIntegratorDriver.hh.
Referenced by AccurateAdvance(), G4MagInt_Driver(), and OneGoodStep().
fMinNoVars
const G4int G4MagInt_Driver::fMinNoVars private
Definition at line 239 of file G4MagIntegratorDriver.hh.
fNoBadSteps
unsigned long G4MagInt_Driver::fNoBadSteps private
Definition at line 260 of file G4MagIntegratorDriver.hh.
Referenced by AccurateAdvance(), and PrintStatisticsReport().
fNoCalls
unsigned long G4MagInt_Driver::fNoCalls private
Definition at line 261 of file G4MagIntegratorDriver.hh.
fNoInitialSmallSteps
unsigned long G4MagInt_Driver::fNoInitialSmallSteps private
Definition at line 260 of file G4MagIntegratorDriver.hh.
Referenced by AccurateAdvance(), and PrintStatisticsReport().
fNoIntegrationVariables
const G4int G4MagInt_Driver::fNoIntegrationVariables private
Definition at line 238 of file G4MagIntegratorDriver.hh.
Referenced by AccurateAdvance(), OneGoodStep(), PrintStatus(), and QuickAdvance().
fNoSmallSteps
unsigned long G4MagInt_Driver::fNoSmallSteps private
Definition at line 260 of file G4MagIntegratorDriver.hh.
Referenced by AccurateAdvance(), and PrintStatisticsReport().
fNoTotalSteps
unsigned long G4MagInt_Driver::fNoTotalSteps private
Definition at line 260 of file G4MagIntegratorDriver.hh.
Referenced by AccurateAdvance(), and PrintStatisticsReport().
fNoVars
const G4int G4MagInt_Driver::fNoVars private
Definition at line 240 of file G4MagIntegratorDriver.hh.
Referenced by AccurateAdvance().
fSmallestFraction
G4double G4MagInt_Driver::fSmallestFraction private
Definition at line 234 of file G4MagIntegratorDriver.hh.
Referenced by AccurateAdvance(), and SetSmallestFraction().
fStatisticsVerboseLevel
G4int G4MagInt_Driver::fStatisticsVerboseLevel private
Definition at line 251 of file G4MagIntegratorDriver.hh.
Referenced by G4MagInt_Driver(), and ~G4MagInt_Driver().
fSumH_lg
G4double G4MagInt_Driver::fSumH_lg private
Definition at line 264 of file G4MagIntegratorDriver.hh.
fSumH_sm
G4double G4MagInt_Driver::fSumH_sm private
Definition at line 264 of file G4MagIntegratorDriver.hh.
Referenced by AccurateAdvance().
fVerboseLevel
G4int G4MagInt_Driver::fVerboseLevel private
Definition at line 267 of file G4MagIntegratorDriver.hh.
Referenced by G4MagInt_Driver(), PrintStatus(), QuickAdvance(), and WarnSmallStepSize().
pgrow
G4double G4MagInt_Driver::pgrow private
Definition at line 247 of file G4MagIntegratorDriver.hh.
pIntStepper
G4MagIntegratorStepper* G4MagInt_Driver::pIntStepper private
Definition at line 255 of file G4MagIntegratorDriver.hh.
Referenced by AccurateAdvance(), G4MagInt_Driver(), GetDerivatives(), GetEquationOfMotion(), GetStepper(), OneGoodStep(), QuickAdvance(), RenewStepperAndAdjust(), and SetEquationOfMotion().
pshrnk
G4double G4MagInt_Driver::pshrnk private
Definition at line 246 of file G4MagIntegratorDriver.hh.
safety
G4double G4MagInt_Driver::safety private
Definition at line 245 of file G4MagIntegratorDriver.hh.
The documentation for this class was generated from the following files:
source/geometry/magneticfield/include/G4MagIntegratorDriver.hh
source/geometry/magneticfield/src/G4MagIntegratorDriver.cc