Geant4: G4NavigationLevelRep Class Reference
G4NavigationLevelRep Class Reference
#include <G4NavigationLevelRep.hh>
Public Member Functions
G4NavigationLevelRep (G4VPhysicalVolume *newPtrPhysVol, const G4AffineTransform &newT, EVolume newVolTp, G4int newRepNo=-1)
G4NavigationLevelRep (G4VPhysicalVolume *newPtrPhysVol, const G4AffineTransform &levelAbove, const G4AffineTransform &relativeCurrent, EVolume newVolTp, G4int newRepNo=-1)
G4NavigationLevelRep ()
G4NavigationLevelRep (G4NavigationLevelRep &)
~G4NavigationLevelRep ()
G4NavigationLevelRep & operator= (const G4NavigationLevelRep &right)
G4VPhysicalVolume * GetPhysicalVolume ()
const G4AffineTransform * GetTransformPtr () const
const G4AffineTransform & GetTransform () const
EVolume GetVolumeType () const
G4int GetReplicaNo () const
void AddAReference ()
G4bool RemoveAReference ()
void * operator new (size_t)
void operator delete (void *aTrack)
Private Attributes
G4AffineTransform sTransform
G4VPhysicalVolume * sPhysicalVolumePtr
G4int sReplicaNo
EVolume sVolumeType
G4int fCountRef
Detailed Description
Definition at line 54 of file G4NavigationLevelRep.hh.
Constructor & Destructor Documentation
G4NavigationLevelRep() [1/4]
G4NavigationLevelRep::G4NavigationLevelRep (G4VPhysicalVolume * newPtrPhysVol, const G4AffineTransform & newT, EVolume newVolTp, G4int newRepNo = -1) inline
G4NavigationLevelRep() [2/4]
G4NavigationLevelRep::G4NavigationLevelRep (G4VPhysicalVolume * newPtrPhysVol, const G4AffineTransform & levelAbove, const G4AffineTransform & relativeCurrent, EVolume newVolTp, G4int newRepNo = -1) inline
G4NavigationLevelRep() [3/4]
G4NavigationLevelRep::G4NavigationLevelRep () inline
G4NavigationLevelRep() [4/4]
G4NavigationLevelRep::G4NavigationLevelRep (G4NavigationLevelRep &) inline
~G4NavigationLevelRep()
G4NavigationLevelRep::~G4NavigationLevelRep () inline
Member Function Documentation
AddAReference()
void G4NavigationLevelRep::AddAReference () inline
Referenced by G4NavigationLevel::G4NavigationLevel().
GetPhysicalVolume()
G4VPhysicalVolume* G4NavigationLevelRep::GetPhysicalVolume () inline
GetReplicaNo()
G4int G4NavigationLevelRep::GetReplicaNo () const inline
GetTransform()
const G4AffineTransform& G4NavigationLevelRep::GetTransform () const inline
GetTransformPtr()
const G4AffineTransform* G4NavigationLevelRep::GetTransformPtr () const inline
GetVolumeType()
EVolume G4NavigationLevelRep::GetVolumeType () const inline
operator delete()
void G4NavigationLevelRep::operator delete (void * aTrack) inline
operator new()
void* G4NavigationLevelRep::operator new (size_t) inline
operator=()
G4NavigationLevelRep& G4NavigationLevelRep::operator= (const G4NavigationLevelRep & right) inline
RemoveAReference()
G4bool G4NavigationLevelRep::RemoveAReference () inline
Referenced by G4NavigationLevel::operator=(), and G4NavigationLevel::~G4NavigationLevel().
Field Documentation
fCountRef
G4int G4NavigationLevelRep::fCountRef private
Definition at line 110 of file G4NavigationLevelRep.hh.
sPhysicalVolumePtr
G4VPhysicalVolume* G4NavigationLevelRep::sPhysicalVolumePtr private
Definition at line 103 of file G4NavigationLevelRep.hh.
sReplicaNo
G4int G4NavigationLevelRep::sReplicaNo private
Definition at line 106 of file G4NavigationLevelRep.hh.
sTransform
G4AffineTransform G4NavigationLevelRep::sTransform private
Definition at line 99 of file G4NavigationLevelRep.hh.
sVolumeType
EVolume G4NavigationLevelRep::sVolumeType private
Definition at line 107 of file G4NavigationLevelRep.hh.
The documentation for this class was generated from the following file:
source/geometry/volumes/include/G4NavigationLevelRep.hh