Geant4: G4AttUtils Namespace Reference
G4AttUtils Namespace Reference
Functions
template<typename T >
G4bool ExtractAttDef (const T &object, const G4String &name, G4AttDef &def)
template<typename T >
G4bool ExtractAttValue (const T &object, const G4String &name, G4AttValue &attVal)
G4TypeKey GetKey (const G4AttDef &def)
Function Documentation
ExtractAttDef()
template<typename T > G4bool G4AttUtils::ExtractAttDef (const T & object, const G4String & name, G4AttDef & def)
Definition at line 61 of file G4AttUtils.hh.
Referenced by G4TrajectoryDrawByAttribute::Draw(), and G4AttributeFilterT< T >::Evaluate().
ExtractAttValue()
template<typename T > G4bool G4AttUtils::ExtractAttValue (const T & object, const G4String & name, G4AttValue & attVal)
Definition at line 75 of file G4AttUtils.hh.
Referenced by G4TrajectoryDrawByAttribute::Draw(), and G4AttributeFilterT< T >::Evaluate().
GetKey()
G4TypeKey G4AttUtils::GetKey (const G4AttDef & def)
Definition at line 40 of file G4AttUtils.cc.
Referenced by G4AttFilterUtils::GetNewFilter().