Geant4: G4UnitsCategory Class Reference
G4UnitsCategory Class Reference
#include <G4UnitsTable.hh>
Public Member Functions
G4UnitsCategory (const G4String &name)
~G4UnitsCategory ()
G4bool operator== (const G4UnitsCategory &) const
G4bool operator!= (const G4UnitsCategory &) const
const G4String & GetName () const
G4UnitsContainer & GetUnitsList ()
G4int GetNameMxLen () const
G4int GetSymbMxLen () const
void UpdateNameMxLen (G4int len)
void UpdateSymbMxLen (G4int len)
void PrintCategory ()
Private Member Functions
G4UnitsCategory (const G4UnitsCategory &)
G4UnitsCategory & operator= (const G4UnitsCategory &)
Private Attributes
G4String Name
G4UnitsContainer UnitsList
G4int NameMxLen
G4int SymbMxLen
Detailed Description
Definition at line 138 of file G4UnitsTable.hh.
Constructor & Destructor Documentation
G4UnitsCategory() [1/2]
G4UnitsCategory::G4UnitsCategory (const G4String & name) explicit
Definition at line 421 of file G4UnitsTable.cc.
~G4UnitsCategory()
G4UnitsCategory::~G4UnitsCategory ()
Definition at line 428 of file G4UnitsTable.cc.
G4UnitsCategory() [2/2]
G4UnitsCategory::G4UnitsCategory (const G4UnitsCategory & right) private
Definition at line 439 of file G4UnitsTable.cc.
Member Function Documentation
GetName()
const G4String& G4UnitsCategory::GetName () const inline
Referenced by export_G4UnitsTable().
GetNameMxLen()
G4int G4UnitsCategory::GetNameMxLen () const inline
Referenced by export_G4UnitsTable().
GetSymbMxLen()
G4int G4UnitsCategory::GetSymbMxLen () const inline
Referenced by export_G4UnitsTable().
GetUnitsList()
G4UnitsContainer& G4UnitsCategory::GetUnitsList () inline
Referenced by export_G4UnitsTable().
operator!=()
G4bool G4UnitsCategory::operator!= (const G4UnitsCategory & right) const
Definition at line 467 of file G4UnitsTable.cc.
operator=()
G4UnitsCategory & G4UnitsCategory::operator= (const G4UnitsCategory & right) private
Definition at line 446 of file G4UnitsTable.cc.
operator==()
G4bool G4UnitsCategory::operator== (const G4UnitsCategory & right) const
Definition at line 460 of file G4UnitsTable.cc.
PrintCategory()
void G4UnitsCategory::PrintCategory ()
Definition at line 474 of file G4UnitsTable.cc.
Referenced by export_G4UnitsTable().
UpdateNameMxLen()
void G4UnitsCategory::UpdateNameMxLen (G4int len) inline
Referenced by export_G4UnitsTable().
UpdateSymbMxLen()
void G4UnitsCategory::UpdateSymbMxLen (G4int len) inline
Referenced by export_G4UnitsTable().
Field Documentation
Name
G4String G4UnitsCategory::Name private
Definition at line 164 of file G4UnitsTable.hh.
Referenced by operator=(), and PrintCategory().
NameMxLen
G4int G4UnitsCategory::NameMxLen private
Definition at line 166 of file G4UnitsTable.hh.
Referenced by operator=().
SymbMxLen
G4int G4UnitsCategory::SymbMxLen private
Definition at line 167 of file G4UnitsTable.hh.
Referenced by operator=().
UnitsList
G4UnitsContainer G4UnitsCategory::UnitsList private
Definition at line 165 of file G4UnitsTable.hh.
Referenced by operator=(), PrintCategory(), and ~G4UnitsCategory().
The documentation for this class was generated from the following files:
source/global/management/include/G4UnitsTable.hh
source/global/management/src/G4UnitsTable.cc