Geant4: G4ModelCmdApplyString< M > Class Template Reference
G4ModelCmdApplyString< M > Class Template Reference abstract
#include <G4ModelApplyCommandsT.hh>
Public Member Functions
G4ModelCmdApplyString (M *model, const G4String &placement, const G4String &cmdName)
virtual ~G4ModelCmdApplyString ()
void SetNewValue (G4UIcommand *command, G4String newValue)
Public Member Functions inherited from G4VModelCommand< M >
G4VModelCommand (M *model, const G4String &placement="")
virtual ~G4VModelCommand ()
G4String GetCurrentValue (G4UIcommand *command)
G4String Placement ()
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Protected Member Functions
virtual void Apply (const G4String &)=0
G4UIcmdWithAString * Command ()
Protected Member Functions inherited from G4VModelCommand< M >
M * Model ()
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Private Attributes
G4UIcmdWithAString * fpCmd
Additional Inherited Members
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
template<typename M>
class G4ModelCmdApplyString< M >
Definition at line 509 of file G4ModelApplyCommandsT.hh.
Constructor & Destructor Documentation
G4ModelCmdApplyString()
template<typename M > G4ModelCmdApplyString< M >::G4ModelCmdApplyString (M * model, const G4String & placement, const G4String & cmdName)
Definition at line 533 of file G4ModelApplyCommandsT.hh.
~G4ModelCmdApplyString()
template<typename M > G4ModelCmdApplyString< M >::~G4ModelCmdApplyString () virtual
Definition at line 542 of file G4ModelApplyCommandsT.hh.
Member Function Documentation
Apply()
template<typename M > virtual void G4ModelCmdApplyString< M >::Apply (const G4String &) protected pure virtual
Implemented in G4ModelCmdSetAuxPtsFillStyle< M >, G4ModelCmdSetStepPtsFillStyle< M >, G4ModelCmdSetAuxPtsSizeType< M >, G4ModelCmdSetStepPtsSizeType< M >, G4ModelCmdSetAuxPtsType< M >, G4ModelCmdSetStepPtsType< M >, G4ModelCmdSetStepPtsSize< M >, G4ModelCmdSetAuxPtsSize< M >, G4ModelCmdAddValue< M >, G4ModelCmdAddInterval< M >, G4ModelCmdAddValueContext< M >, G4ModelCmdAddIntervalContext< M >, G4ModelCmdSetString< M >, and G4ModelCmdAddString< M >.
Command()
template<typename M > G4UIcmdWithAString* G4ModelCmdApplyString< M >::Command () inline protected
Definition at line 524 of file G4ModelApplyCommandsT.hh.
Referenced by G4ModelCmdAddInterval< M >::G4ModelCmdAddInterval(), G4ModelCmdAddIntervalContext< M >::G4ModelCmdAddIntervalContext(), G4ModelCmdAddString< M >::G4ModelCmdAddString(), G4ModelCmdAddValue< M >::G4ModelCmdAddValue(), G4ModelCmdAddValueContext< M >::G4ModelCmdAddValueContext(), G4ModelCmdSetAuxPtsFillStyle< M >::G4ModelCmdSetAuxPtsFillStyle(), G4ModelCmdSetAuxPtsSize< M >::G4ModelCmdSetAuxPtsSize(), G4ModelCmdSetAuxPtsSizeType< M >::G4ModelCmdSetAuxPtsSizeType(), G4ModelCmdSetAuxPtsType< M >::G4ModelCmdSetAuxPtsType(), G4ModelCmdSetStepPtsFillStyle< M >::G4ModelCmdSetStepPtsFillStyle(), G4ModelCmdSetStepPtsSize< M >::G4ModelCmdSetStepPtsSize(), G4ModelCmdSetStepPtsSizeType< M >::G4ModelCmdSetStepPtsSizeType(), G4ModelCmdSetStepPtsType< M >::G4ModelCmdSetStepPtsType(), and G4ModelCmdSetString< M >::G4ModelCmdSetString().
SetNewValue()
template<typename M > void G4ModelCmdApplyString< M >::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 548 of file G4ModelApplyCommandsT.hh.
Field Documentation
fpCmd
template<typename M > G4UIcmdWithAString* G4ModelCmdApplyString< M >::fpCmd private
Definition at line 528 of file G4ModelApplyCommandsT.hh.
Referenced by G4ModelCmdApplyString< M >::Command(), and G4ModelCmdApplyString< M >::G4ModelCmdApplyString().
The documentation for this class was generated from the following file:
source/visualization/modeling/include/G4ModelApplyCommandsT.hh