Geant4: source/externals/clhep/src/Evaluator.cc File Reference
Evaluator.cc File Reference
#include "CLHEP/Evaluator/Evaluator.h"
#include <iostream>
#include <sstream>
#include <cmath>
#include "CLHEP/Evaluator/stack.icc"
#include "CLHEP/Evaluator/string.icc"
#include "CLHEP/Evaluator/hash_map.icc"
#include <string.h>
#include <ctype.h>
#include <errno.h>
#include <stdlib.h>
Data Structures
struct Item
struct Struct
Namespaces
HepTool
Macros
#define EVAL HepTool::Evaluator
#define REMOVE_BLANKS
#define SKIP_BLANKS
#define EVAL_EXIT(STATUS, POSITION) endp = POSITION; return STATUS
#define MAX_N_PAR 5
Typedefs
typedef void(* voidfuncptr) ()
typedef char * pchar
typedef hash_map< string, Item > dic_type
Enumerations
enum {
ENDL, LBRA, OR, AND,
EQ, NE, GE, GT,
LE, LT, PLUS, MINUS,
UNARY_PLUS, UNARY_MINUS, MULT, DIV,
POW, RBRA, VALUE
}
Functions
static int engine (pchar, pchar, double &, pchar &, const dic_type &)
static int variable (const string &name, double &result, const dic_type &dictionary)
static int function (const string &name, stack< double > &par, double &result, const dic_type &dictionary)
static int operand (pchar begin, pchar end, double &result, pchar &endp, const dic_type &dictionary)
static int maker (int op, stack< double > &val)
static void setItem (const char *prefix, const char *name, const Item &item, Struct *s)
Variables
static const char sss [MAX_N_PAR+2] = "012345"
Macro Definition Documentation
EVAL
#define EVAL HepTool::Evaluator
Definition at line 48 of file Evaluator.cc.
EVAL_EXIT
#define EVAL_EXIT (STATUS, POSITION) endp = POSITION; return STATUS
Definition at line 60 of file Evaluator.cc.
MAX_N_PAR
#define MAX_N_PAR 5
Definition at line 61 of file Evaluator.cc.
REMOVE_BLANKS
#define REMOVE_BLANKS
Value:
for(pointer=name;;pointer++) if (!isspace(*pointer)) break; \
for(n=strlen(pointer);n>0;n--) if (!isspace(*(pointer+n-1))) break
Definition at line 50 of file Evaluator.cc.
SKIP_BLANKS
#define SKIP_BLANKS
Value:
for(;;pointer++) {                       \
  c = (pointer > end) ? '\0' : *pointer; \
  if (!isspace(c)) break;                \
}
Definition at line 54 of file Evaluator.cc.
Typedef Documentation
dic_type
typedef hash_map<string,Item> dic_type
Definition at line 37 of file Evaluator.cc.
pchar
typedef char* pchar
Definition at line 36 of file Evaluator.cc.
voidfuncptr
typedef void(* voidfuncptr) ()
Definition at line 20 of file Evaluator.cc.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ENDL
LBRA
OR
AND
EQ
NE
GE
GT
LE
LT
PLUS
MINUS
UNARY_PLUS
UNARY_MINUS
MULT
DIV
POW
RBRA
VALUE
Definition at line 65 of file Evaluator.cc.
Function Documentation
engine()
static int engine (pchar begin, pchar end, double & result, pchar & endp, const dic_type & dictionary) static
Definition at line 355 of file Evaluator.cc.
Referenced by variable().
function()
static int function (const string & name, stack< double > & par, double & result, const dic_type & dictionary) static
Definition at line 107 of file Evaluator.cc.
maker()
static int maker (int op, stack< double > & val) static
Definition at line 281 of file Evaluator.cc.
Referenced by engine().
operand()
static int operand (pchar begin, pchar end, double & result, pchar & endp, const dic_type & dictionary) static
Definition at line 161 of file Evaluator.cc.
Referenced by any_cast(), G4MultiUnion::CreatePolyhedron(), engine(), and G4BooleanSolid::StackPolyhedron().
setItem()
static void setItem (const char * prefix, const char * name, const Item & item, Struct * s) static
Definition at line 546 of file Evaluator.cc.
variable()
static int variable (const string & name, double & result, const dic_type & dictionary) static
Definition at line 70 of file Evaluator.cc.
Variable Documentation
sss
const char sss[MAX_N_PAR+2] = "012345" static
Definition at line 63 of file Evaluator.cc.
Referenced by function(), G4PolarizedComptonModel::PrintWarning(), G4JTPolynomialSolver::RealPolynomialIteration(), GammaRayTelDetectorConstruction::SetMagField(), G4EmParameters::SetPIXECrossSectionModel(), G4EmParameters::SetPIXEElectronCrossSectionModel(), DMXEventAction::writePmtHitsToFile(), and DMXEventAction::writeScintHitsToFile().