Geant4: G4FieldTrack Class Reference
G4FieldTrack Class Reference
#include <G4FieldTrack.hh>
Public Types
enum { ncompSVEC = 12 }
Public Member Functions
G4FieldTrack (const G4ThreeVector &pPosition, G4double LaboratoryTimeOfFlight, const G4ThreeVector &pMomentumDirection, G4double kineticEnergy, G4double restMass_c2, G4double charge, const G4ThreeVector &polarization, G4double magnetic_dipole_moment=0.0, G4double curve_length=0.0, G4double PDGspin=-1.0)
G4FieldTrack (const G4FieldTrack &pFieldTrack)
G4FieldTrack (char)
~G4FieldTrack ()
void UpdateState (const G4ThreeVector &pPosition, G4double LaboratoryTimeOfFlight, const G4ThreeVector &pMomentumDirection, G4double kineticEnergy)
void UpdateFourMomentum (G4double kineticEnergy, const G4ThreeVector &momentumDirection)
void SetChargeAndMoments (G4double charge, G4double magnetic_dipole_moment=DBL_MAX, G4double electric_dipole_moment=DBL_MAX, G4double magnetic_charge=DBL_MAX)
void SetPDGSpin (G4double pdgSpin)
G4double GetPDGSpin ()
G4FieldTrack (const G4ThreeVector &pPosition, const G4ThreeVector &pMomentumDirection, G4double curve_length, G4double kineticEnergy, const G4double restMass_c2, G4double velocity, G4double LaboratoryTimeOfFlight=0.0, G4double ProperTimeOfFlight=0.0, const G4ThreeVector *pPolarization=0, G4double PDGspin=-1.0)
G4FieldTrack & operator= (const G4FieldTrack &rStVec)
G4ThreeVector GetMomentum () const
G4ThreeVector GetPosition () const
const G4ThreeVector & GetMomentumDir () const
G4ThreeVector GetMomentumDirection () const
G4double GetCurveLength () const
G4ThreeVector GetPolarization () const
void SetPolarization (const G4ThreeVector &vecPol)
G4double GetLabTimeOfFlight () const
G4double GetProperTimeOfFlight () const
G4double GetKineticEnergy () const
G4double GetCharge () const
G4double GetRestMass () const
void SetPosition (G4ThreeVector nPos)
void SetMomentum (G4ThreeVector nMomDir)
void SetMomentumDir (G4ThreeVector nMomDir)
void SetRestMass (G4double Mass_c2)
void SetCurveLength (G4double nCurve_s)
void SetKineticEnergy (G4double nEnergy)
void SetLabTimeOfFlight (G4double tofLab)
void SetProperTimeOfFlight (G4double tofProper)
void DumpToArray (G4double valArr[ncompSVEC]) const
void LoadFromArray (const G4double valArr[ncompSVEC], G4int noVarsIntegrated)
void InitialiseSpin (const G4ThreeVector &vecPolarization)
G4ThreeVector GetSpin () const
void SetSpin (G4ThreeVector vSpin)
const G4ChargeState * GetChargeState () const
Private Member Functions
G4FieldTrack & SetCurvePnt (const G4ThreeVector &pPosition, const G4ThreeVector &pMomentum, G4double s_curve)
Private Attributes
G4double SixVector [6]
G4double fDistanceAlongCurve
G4double fKineticEnergy
G4double fRestMass_c2
G4double fLabTimeOfFlight
G4double fProperTimeOfFlight
G4ThreeVector fPolarization
G4ThreeVector fMomentumDir
G4ChargeState fChargeState
Friends
std::ostream & operator<< (std::ostream &os, const G4FieldTrack &SixVec)
Detailed Description
Definition at line 53 of file G4FieldTrack.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
ncompSVEC
Definition at line 148 of file G4FieldTrack.hh.
Constructor & Destructor Documentation
G4FieldTrack() [1/4]
G4FieldTrack::G4FieldTrack (const G4ThreeVector & pPosition, G4double LaboratoryTimeOfFlight, const G4ThreeVector & pMomentumDirection, G4double kineticEnergy, G4double restMass_c2, G4double charge, const G4ThreeVector & polarization, G4double magnetic_dipole_moment = 0.0, G4double curve_length = 0.0, G4double PDGspin = -1.0)
Definition at line 71 of file G4FieldTrack.cc.
G4FieldTrack() [2/4]
G4FieldTrack::G4FieldTrack (const G4FieldTrack & pFieldTrack)
G4FieldTrack() [3/4]
G4FieldTrack::G4FieldTrack (char)
Definition at line 127 of file G4FieldTrack.cc.
~G4FieldTrack()
G4FieldTrack::~G4FieldTrack ()
G4FieldTrack() [4/4]
G4FieldTrack::G4FieldTrack (const G4ThreeVector & pPosition, const G4ThreeVector & pMomentumDirection, G4double curve_length, G4double kineticEnergy, const G4double restMass_c2, G4double velocity, G4double LaboratoryTimeOfFlight = 0.0, G4double ProperTimeOfFlight = 0.0, const G4ThreeVector * pPolarization = 0, G4double PDGspin = -1.0)
Definition at line 99 of file G4FieldTrack.cc.
Member Function Documentation
DumpToArray()
void G4FieldTrack::DumpToArray (G4double valArr[ncompSVEC]) const inline
Referenced by G4MagInt_Driver::AccurateAdvance(), G4MagInt_Driver::GetDerivatives(), and G4MagInt_Driver::QuickAdvance().
GetCharge()
G4double G4FieldTrack::GetCharge () const inline
Referenced by G4PathFinder::ComputeStep().
GetChargeState()
const G4ChargeState* G4FieldTrack::GetChargeState () const inline
Definition at line 184 of file G4FieldTrack.hh.
Referenced by G4PathFinder::DoNextCurvedStep().
GetCurveLength()
G4double G4FieldTrack::GetCurveLength () const inline
Referenced by G4MagInt_Driver::AccurateAdvance(), G4ChordFinder::ApproxCurvePointS(), G4ChordFinder::ApproxCurvePointV(), G4VIntersectionLocator::CheckAndReEstimateEndpoint(), G4PropagatorInField::ComputeStep(), G4BrentLocator::EstimateIntersectionPoint(), G4MultiLevelLocator::EstimateIntersectionPoint(), G4SimpleLocator::EstimateIntersectionPoint(), operator<<(), G4MagInt_Driver::PrintStat_Aux(), G4PropagatorInField::printStatus(), G4VIntersectionLocator::printStatus(), G4MagInt_Driver::PrintStatus(), G4MagInt_Driver::QuickAdvance(), G4VIntersectionLocator::ReEstimateEndpoint(), and G4VIntersectionLocator::ReportReversedPoints().
GetKineticEnergy()
G4double G4FieldTrack::GetKineticEnergy () const inline
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), and G4MagInt_Driver::PrintStat_Aux().
GetLabTimeOfFlight()
G4double G4FieldTrack::GetLabTimeOfFlight () const inline
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), and G4MultiLevelLocator::ReportFieldValue().
GetMomentum()
G4ThreeVector G4FieldTrack::GetMomentum () const inline
Referenced by G4PropagatorInField::ComputeStep(), G4PathFinder::DoNextCurvedStep(), G4PropagatorInField::printStatus(), G4VIntersectionLocator::printStatus(), and G4FieldTrackUpdator::Update().
GetMomentumDir()
const G4ThreeVector& G4FieldTrack::GetMomentumDir () const inline
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4PropagatorInField::ComputeStep(), G4BrentLocator::EstimateIntersectionPoint(), G4MultiLevelLocator::EstimateIntersectionPoint(), G4SimpleLocator::EstimateIntersectionPoint(), G4MagInt_Driver::PrintStat_Aux(), G4PropagatorInField::printStatus(), G4VIntersectionLocator::printStatus(), and G4MagInt_Driver::PrintStatus().
GetMomentumDirection()
G4ThreeVector G4FieldTrack::GetMomentumDirection () const inline
Referenced by G4PathFinder::ComputeStep(), G4ITPathFinder::ComputeStep(), G4PathFinder::DoNextLinearStep(), G4ITPathFinder::DoNextLinearStep(), G4BrentLocator::EstimateIntersectionPoint(), G4MultiLevelLocator::EstimateIntersectionPoint(), and G4SimpleLocator::EstimateIntersectionPoint().
GetPDGSpin()
G4double G4FieldTrack::GetPDGSpin () inline
Definition at line 93 of file G4FieldTrack.hh.
GetPolarization()
G4ThreeVector G4FieldTrack::GetPolarization () const inline
Referenced by GetSpin(), and operator<<().
GetPosition()
G4ThreeVector G4FieldTrack::GetPosition () const inline
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4WeightCutOffProcess::AlongStepGetPhysicalInteractionLength(), G4ImportanceProcess::AlongStepGetPhysicalInteractionLength(), G4WeightWindowProcess::AlongStepGetPhysicalInteractionLength(), G4ChordFinder::ApproxCurvePointS(), G4ChordFinder::ApproxCurvePointV(), G4VIntersectionLocator::CheckAndReEstimateEndpoint(), G4PathFinder::ComputeStep(), G4PropagatorInField::ComputeStep(), G4ITPathFinder::ComputeStep(), G4PathFinder::DoNextCurvedStep(), G4ITPathFinder::DoNextCurvedStep(), G4PathFinder::DoNextLinearStep(), G4ITPathFinder::DoNextLinearStep(), G4BrentLocator::EstimateIntersectionPoint(), G4MultiLevelLocator::EstimateIntersectionPoint(), G4SimpleLocator::EstimateIntersectionPoint(), G4PathFinder::Locate(), G4MagInt_Driver::PrintStat_Aux(), G4PropagatorInField::printStatus(), G4VIntersectionLocator::printStatus(), G4MagInt_Driver::PrintStatus(), G4MagInt_Driver::QuickAdvance(), G4VIntersectionLocator::ReEstimateEndpoint(), G4PathFinder::ReLocate(), and G4MultiLevelLocator::ReportFieldValue().
GetProperTimeOfFlight()
G4double G4FieldTrack::GetProperTimeOfFlight () const inline
GetRestMass()
G4double G4FieldTrack::GetRestMass () const inline
Definition at line 125 of file G4FieldTrack.hh.
Referenced by G4PathFinder::DoNextCurvedStep(), and G4MultiLevelLocator::EstimateIntersectionPoint().
GetSpin()
G4ThreeVector G4FieldTrack::GetSpin () const inline
Definition at line 160 of file G4FieldTrack.hh.
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), and G4CoupledTransportation::AlongStepGetPhysicalInteractionLength().
InitialiseSpin()
void G4FieldTrack::InitialiseSpin (const G4ThreeVector & vecPolarization) inline
Definition at line 158 of file G4FieldTrack.hh.
LoadFromArray()
void G4FieldTrack::LoadFromArray (const G4double valArr[ncompSVEC], G4int noVarsIntegrated)
Definition at line 165 of file G4FieldTrack.cc.
Referenced by G4MagInt_Driver::AccurateAdvance(), G4MagInt_Driver::PrintStatus(), and G4MagInt_Driver::QuickAdvance().
operator=()
G4FieldTrack& G4FieldTrack::operator= (const G4FieldTrack & rStVec) inline
SetChargeAndMoments()
void G4FieldTrack::SetChargeAndMoments (G4double charge, G4double magnetic_dipole_moment = DBL_MAX, G4double electric_dipole_moment = DBL_MAX, G4double magnetic_charge = DBL_MAX)
Definition at line 139 of file G4FieldTrack.cc.
Referenced by G4FieldTrackUpdator::Update().
SetCurveLength()
void G4FieldTrack::SetCurveLength (G4double nCurve_s) inline
Referenced by G4MagInt_Driver::AccurateAdvance(), G4MagInt_Driver::PrintStatus(), and G4MagInt_Driver::QuickAdvance().
SetCurvePnt()
G4FieldTrack& G4FieldTrack::SetCurvePnt (const G4ThreeVector & pPosition, const G4ThreeVector & pMomentum, G4double s_curve) inline private
Referenced by G4FieldTrack().
SetKineticEnergy()
void G4FieldTrack::SetKineticEnergy (G4double nEnergy) inline
SetLabTimeOfFlight()
void G4FieldTrack::SetLabTimeOfFlight (G4double tofLab) inline
SetMomentum()
void G4FieldTrack::SetMomentum (G4ThreeVector nMomDir) inline
SetMomentumDir()
void G4FieldTrack::SetMomentumDir (G4ThreeVector nMomDir) inline
SetPDGSpin()
void G4FieldTrack::SetPDGSpin (G4double pdgSpin) inline
Definition at line 92 of file G4FieldTrack.hh.
Referenced by G4FieldTrackUpdator::Update().
SetPolarization()
void G4FieldTrack::SetPolarization (const G4ThreeVector & vecPol) inline
Referenced by G4FieldTrack(), InitialiseSpin(), LoadFromArray(), and SetSpin().
SetPosition()
void G4FieldTrack::SetPosition (G4ThreeVector nPos) inline
Referenced by G4PathFinder::DoNextLinearStep(), G4BrentLocator::EstimateIntersectionPoint(), G4MultiLevelLocator::EstimateIntersectionPoint(), G4SimpleLocator::EstimateIntersectionPoint(), and G4FieldTrack().
SetProperTimeOfFlight()
void G4FieldTrack::SetProperTimeOfFlight (G4double tofProper) inline
Referenced by G4PathFinder::DoNextLinearStep(), and G4FieldTrackUpdator::Update().
SetRestMass()
void G4FieldTrack::SetRestMass (G4double Mass_c2) inline
Definition at line 135 of file G4FieldTrack.hh.
Referenced by G4FieldTrackUpdator::Update().
SetSpin()
void G4FieldTrack::SetSpin (G4ThreeVector vSpin) inline
Definition at line 161 of file G4FieldTrack.hh.
Referenced by G4FieldTrackUpdator::Update().
UpdateFourMomentum()
void G4FieldTrack::UpdateFourMomentum (G4double kineticEnergy, const G4ThreeVector & momentumDirection) inline
Referenced by G4FieldTrack().
UpdateState()
void G4FieldTrack::UpdateState (const G4ThreeVector & pPosition, G4double LaboratoryTimeOfFlight, const G4ThreeVector & pMomentumDirection, G4double kineticEnergy) inline
Referenced by G4FieldTrackUpdator::Update().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const G4FieldTrack & SixVec) friend
Definition at line 32 of file G4FieldTrack.cc.
Field Documentation
fChargeState
G4ChargeState G4FieldTrack::fChargeState private
Definition at line 180 of file G4FieldTrack.hh.
Referenced by G4FieldTrack(), GetChargeState(), GetPDGSpin(), SetChargeAndMoments(), and SetPDGSpin().
fDistanceAlongCurve
G4double G4FieldTrack::fDistanceAlongCurve private
Definition at line 170 of file G4FieldTrack.hh.
fKineticEnergy
G4double G4FieldTrack::fKineticEnergy private
Definition at line 171 of file G4FieldTrack.hh.
Referenced by LoadFromArray(), and operator<<().
fLabTimeOfFlight
G4double G4FieldTrack::fLabTimeOfFlight private
Definition at line 173 of file G4FieldTrack.hh.
Referenced by LoadFromArray(), and operator<<().
fMomentumDir
G4ThreeVector G4FieldTrack::fMomentumDir private
Definition at line 176 of file G4FieldTrack.hh.
Referenced by LoadFromArray(), and operator<<().
fPolarization
G4ThreeVector G4FieldTrack::fPolarization private
Definition at line 175 of file G4FieldTrack.hh.
fProperTimeOfFlight
G4double G4FieldTrack::fProperTimeOfFlight private
Definition at line 174 of file G4FieldTrack.hh.
Referenced by LoadFromArray(), and operator<<().
fRestMass_c2
G4double G4FieldTrack::fRestMass_c2 private
Definition at line 172 of file G4FieldTrack.hh.
Referenced by GetRestMass(), LoadFromArray(), operator<<(), and SetRestMass().
SixVector
G4double G4FieldTrack::SixVector[6] private
Definition at line 169 of file G4FieldTrack.hh.
Referenced by LoadFromArray(), and operator<<().
The documentation for this class was generated from the following files:
source/geometry/magneticfield/include/G4FieldTrack.hh
source/geometry/magneticfield/src/G4FieldTrack.cc