Geant4: G4AnalysisMessengerHelper Class Reference
G4AnalysisMessengerHelper Class Reference
#include <G4AnalysisMessengerHelper.hh>
Data Structures
struct BinData
struct ValueData
Public Member Functions
G4AnalysisMessengerHelper (const G4String &hnType)
~G4AnalysisMessengerHelper ()
std::unique_ptr< G4UIdirectory > CreateHnDirectory () const
std::unique_ptr< G4UIcommand > CreateSetTitleCommand (G4UImessenger *messenger) const
std::unique_ptr< G4UIcommand > CreateSetBinsCommand (const G4String &axis, G4UImessenger *messenger) const
std::unique_ptr< G4UIcommand > CreateSetValuesCommand (const G4String &axis, G4UImessenger *messenger) const
std::unique_ptr< G4UIcommand > CreateSetAxisCommand (const G4String &axis, G4UImessenger *messenger) const
void GetBinData (BinData &data, std::vector< G4String > &parameters, G4int &counter) const
void GetValueData (ValueData &data, std::vector< G4String > &parameters, G4int &counter) const
void WarnAboutParameters (G4UIcommand *command, G4int nofParameters) const
void WarnAboutSetCommands () const
Private Member Functions
G4String Update (const G4String &str, const G4String &axis="") const
Private Attributes
G4String fHnType
Friends
class G4HnMessenger
Detailed Description
Definition at line 44 of file G4AnalysisMessengerHelper.hh.
Constructor & Destructor Documentation
G4AnalysisMessengerHelper()
G4AnalysisMessengerHelper::G4AnalysisMessengerHelper (const G4String & hnType) explicit
Definition at line 78 of file G4AnalysisMessengerHelper.cc.
~G4AnalysisMessengerHelper()
G4AnalysisMessengerHelper::~G4AnalysisMessengerHelper ()
Definition at line 83 of file G4AnalysisMessengerHelper.cc.
Member Function Documentation
CreateHnDirectory()
std::unique_ptr< G4UIdirectory > G4AnalysisMessengerHelper::CreateHnDirectory () const
Definition at line 133 of file G4AnalysisMessengerHelper.cc.
CreateSetAxisCommand()
std::unique_ptr< G4UIcommand > G4AnalysisMessengerHelper::CreateSetAxisCommand (const G4String & axis, G4UImessenger * messenger) const
Definition at line 264 of file G4AnalysisMessengerHelper.cc.
CreateSetBinsCommand()
std::unique_ptr< G4UIcommand > G4AnalysisMessengerHelper::CreateSetBinsCommand (const G4String & axis, G4UImessenger * messenger) const
Definition at line 165 of file G4AnalysisMessengerHelper.cc.
CreateSetTitleCommand()
std::unique_ptr< G4UIcommand > G4AnalysisMessengerHelper::CreateSetTitleCommand (G4UImessenger * messenger) const
Definition at line 142 of file G4AnalysisMessengerHelper.cc.
CreateSetValuesCommand()
std::unique_ptr< G4UIcommand > G4AnalysisMessengerHelper::CreateSetValuesCommand (const G4String & axis, G4UImessenger * messenger) const
Definition at line 222 of file G4AnalysisMessengerHelper.cc.
GetBinData()
void G4AnalysisMessengerHelper::GetBinData (BinData & data, std::vector< G4String > & parameters, G4int & counter) const
Definition at line 286 of file G4AnalysisMessengerHelper.cc.
GetValueData()
void G4AnalysisMessengerHelper::GetValueData (ValueData & data, std::vector< G4String > & parameters, G4int & counter) const
Definition at line 299 of file G4AnalysisMessengerHelper.cc.
Update()
G4String G4AnalysisMessengerHelper::Update (const G4String & str, const G4String & axis = "") const private
Definition at line 91 of file G4AnalysisMessengerHelper.cc.
Referenced by CreateHnDirectory(), CreateSetAxisCommand(), CreateSetBinsCommand(), CreateSetTitleCommand(), CreateSetValuesCommand(), WarnAboutParameters(), and WarnAboutSetCommands().
WarnAboutParameters()
void G4AnalysisMessengerHelper::WarnAboutParameters (G4UIcommand * command, G4int nofParameters) const
Definition at line 310 of file G4AnalysisMessengerHelper.cc.
WarnAboutSetCommands()
void G4AnalysisMessengerHelper::WarnAboutSetCommands () const
Definition at line 325 of file G4AnalysisMessengerHelper.cc.
Friends And Related Function Documentation
G4HnMessenger
friend class G4HnMessenger friend
Definition at line 78 of file G4AnalysisMessengerHelper.hh.
Field Documentation
fHnType
G4String G4AnalysisMessengerHelper::fHnType private
Definition at line 111 of file G4AnalysisMessengerHelper.hh.
Referenced by Update().
The documentation for this class was generated from the following files:
source/analysis/management/include/G4AnalysisMessengerHelper.hh
source/analysis/management/src/G4AnalysisMessengerHelper.cc