Geant4: G4RunManagerKernel Class Reference
G4RunManagerKernel Class Reference
#include <G4RunManagerKernel.hh>
Public Types
enum RMKType { sequentialRMK, masterRMK, workerRMK }
Public Member Functions
G4RunManagerKernel ()
virtual ~G4RunManagerKernel ()
void DefineWorldVolume (G4VPhysicalVolume *worldVol, G4bool topologyIsChanged=true)
void WorkerDefineWorldVolume (G4VPhysicalVolume *worldVol, G4bool topologyIsChanged=true)
void SetPhysics (G4VUserPhysicsList *uPhys)
void InitializePhysics ()
G4bool RunInitialization (G4bool fakeRun=false)
void RunTermination ()
void WorkerUpdateWorldVolume ()
void UpdateRegion ()
void DumpRegion (const G4String &rname) const
void DumpRegion (G4Region *region=0) const
void GeometryHasBeenModified ()
void PhysicsHasBeenModified ()
G4EventManager * GetEventManager () const
G4StackManager * GetStackManager () const
G4TrackingManager * GetTrackingManager () const
void SetPrimaryTransformer (G4PrimaryTransformer *pt)
G4PrimaryTransformer * GetPrimaryTransformer () const
const G4String & GetVersionString () const
void SetVerboseLevel (G4int vl)
void SetGeometryToBeOptimized (G4bool vl)
G4int GetNumberOfParallelWorld () const
void SetNumberOfParallelWorld (G4int i)
G4VUserPhysicsList * GetPhysicsList () const
G4VPhysicalVolume * GetCurrentWorld () const
G4int GetNumberOfStaticAllocators () const
Static Public Member Functions
static G4RunManagerKernel * GetRunManagerKernel ()
Protected Member Functions
G4RunManagerKernel (RMKType rmkType)
void SetupDefaultRegion ()
void SetupPhysics ()
void ResetNavigator ()
void BuildPhysicsTables (G4bool fakeRun)
void CheckRegions ()
virtual void SetupShadowProcess () const
void PropagateGenericIonID ()
Protected Attributes
RMKType runManagerKernelType
G4Region * defaultRegion
G4Region * defaultRegionForParallelWorld
G4bool geometryNeedsToBeClosed
Private Member Functions
void CheckRegularGeometry ()
G4bool ConfirmCoupledTransportation ()
void SetScoreSplitter ()
Private Attributes
G4VUserPhysicsList * physicsList
G4VPhysicalVolume * currentWorld
G4bool geometryInitialized
G4bool physicsInitialized
G4bool geometryToBeOptimized
G4bool physicsNeedsToBeReBuilt
G4int verboseLevel
G4int numberOfParallelWorld
G4EventManager * eventManager
G4ExceptionHandler * defaultExceptionHandler
G4String versionString
G4int numberOfStaticAllocators
Static Private Attributes
static G4ThreadLocal G4RunManagerKernel * fRunManagerKernel = 0
Detailed Description
Definition at line 67 of file G4RunManagerKernel.hh.
Member Enumeration Documentation
RMKType
enum G4RunManagerKernel::RMKType
Enumerator
sequentialRMK
masterRMK
workerRMK
Definition at line 85 of file G4RunManagerKernel.hh.
Constructor & Destructor Documentation
G4RunManagerKernel() [1/2]
G4RunManagerKernel::G4RunManagerKernel ()
Definition at line 81 of file G4RunManagerKernel.cc.
~G4RunManagerKernel()
G4RunManagerKernel::~G4RunManagerKernel () virtual
Definition at line 274 of file G4RunManagerKernel.cc.
G4RunManagerKernel() [2/2]
G4RunManagerKernel::G4RunManagerKernel (RMKType rmkType) protected
Definition at line 151 of file G4RunManagerKernel.cc.
Member Function Documentation
BuildPhysicsTables()
void G4RunManagerKernel::BuildPhysicsTables (G4bool fakeRun) protected
Definition at line 784 of file G4RunManagerKernel.cc.
Referenced by RunInitialization().
CheckRegions()
void G4RunManagerKernel::CheckRegions () protected
Definition at line 808 of file G4RunManagerKernel.cc.
Referenced by InitializePhysics(), and UpdateRegion().
CheckRegularGeometry()
void G4RunManagerKernel::CheckRegularGeometry () private
Definition at line 959 of file G4RunManagerKernel.cc.
Referenced by RunInitialization().
ConfirmCoupledTransportation()
G4bool G4RunManagerKernel::ConfirmCoupledTransportation () private
Definition at line 980 of file G4RunManagerKernel.cc.
DefineWorldVolume()
void G4RunManagerKernel::DefineWorldVolume (G4VPhysicalVolume * worldVol, G4bool topologyIsChanged = true)
Definition at line 439 of file G4RunManagerKernel.cc.
Referenced by G4RunManager::DefineWorldVolume(), G4ErrorRunManagerHelper::InitializeGeometry(), and G4RunManager::InitializeGeometry().
DumpRegion() [1/2]
void G4RunManagerKernel::DumpRegion (const G4String & rname) const
Definition at line 881 of file G4RunManagerKernel.cc.
Referenced by BuildPhysicsTables(), DumpRegion(), and G4RunManager::DumpRegion().
DumpRegion() [2/2]
void G4RunManagerKernel::DumpRegion (G4Region * region = 0) const
Definition at line 887 of file G4RunManagerKernel.cc.
GeometryHasBeenModified()
void G4RunManagerKernel::GeometryHasBeenModified () inline
Definition at line 163 of file G4RunManagerKernel.hh.
Referenced by G4RunManager::GeometryHasBeenModified(), G4RunManager::ReinitializeGeometry(), and G4RunManager::SetGeometryToBeOptimized().
GetCurrentWorld()
G4VPhysicalVolume* G4RunManagerKernel::GetCurrentWorld () const inline
Definition at line 211 of file G4RunManagerKernel.hh.
Referenced by G4WorkerRunManager::InitializeGeometry().
GetEventManager()
G4EventManager* G4RunManagerKernel::GetEventManager () const inline
Definition at line 177 of file G4RunManagerKernel.hh.
Referenced by G4RunManager::G4RunManager().
GetNumberOfParallelWorld()
G4int G4RunManagerKernel::GetNumberOfParallelWorld () const inline
Definition at line 203 of file G4RunManagerKernel.hh.
Referenced by G4PhysicsListHelper::AddTransportation(), and G4WorkerRunManager::InitializeGeometry().
GetNumberOfStaticAllocators()
G4int G4RunManagerKernel::GetNumberOfStaticAllocators () const inline
Definition at line 221 of file G4RunManagerKernel.hh.
Referenced by G4MTRunManager::G4MTRunManager().
GetPhysicsList()
G4VUserPhysicsList* G4RunManagerKernel::GetPhysicsList () const inline
Definition at line 208 of file G4RunManagerKernel.hh.
GetPrimaryTransformer()
G4PrimaryTransformer* G4RunManagerKernel::GetPrimaryTransformer () const inline
Definition at line 185 of file G4RunManagerKernel.hh.
Referenced by RunInitialization().
GetRunManagerKernel()
G4RunManagerKernel * G4RunManagerKernel::GetRunManagerKernel () static
Definition at line 78 of file G4RunManagerKernel.cc.
Referenced by G4PhysicsListHelper::AddTransportation(), G4VisManager::Disable(), G4MaterialScanner::DoScan(), G4ExceptionHandler::DumpTrackInfo(), export_G4RunManagerKernel(), G4ErrorRunManagerHelper::G4ErrorRunManagerHelper(), and RE06SteppingVerbose::InitializeTimers().
GetStackManager()
G4StackManager* G4RunManagerKernel::GetStackManager () const inline
Definition at line 179 of file G4RunManagerKernel.hh.
GetTrackingManager()
G4TrackingManager* G4RunManagerKernel::GetTrackingManager () const inline
Definition at line 181 of file G4RunManagerKernel.hh.
Referenced by G4VisManager::Disable(), G4ExceptionHandler::DumpTrackInfo(), and RE06SteppingVerbose::InitializeTimers().
GetVersionString()
const G4String& G4RunManagerKernel::GetVersionString () const inline
Definition at line 188 of file G4RunManagerKernel.hh.
Referenced by G4RunManager::GetVersionString().
InitializePhysics()
void G4RunManagerKernel::InitializePhysics ()
Definition at line 580 of file G4RunManagerKernel.cc.
Referenced by G4ErrorRunManagerHelper::InitializePhysics(), and G4RunManager::InitializePhysics().
PhysicsHasBeenModified()
void G4RunManagerKernel::PhysicsHasBeenModified () inline
Definition at line 169 of file G4RunManagerKernel.hh.
Referenced by G4RunManager::PhysicsHasBeenModified().
PropagateGenericIonID()
void G4RunManagerKernel::PropagateGenericIonID () protected
Definition at line 719 of file G4RunManagerKernel.cc.
Referenced by RunInitialization().
ResetNavigator()
void G4RunManagerKernel::ResetNavigator () protected
Definition at line 743 of file G4RunManagerKernel.cc.
Referenced by RunInitialization().
RunInitialization()
G4bool G4RunManagerKernel::RunInitialization (G4bool fakeRun = false)
Definition at line 656 of file G4RunManagerKernel.cc.
Referenced by export_G4RunManagerKernel(), G4WorkerRunManager::RunInitialization(), G4ErrorRunManagerHelper::RunInitialization(), and G4RunManager::RunInitialization().
RunTermination()
void G4RunManagerKernel::RunTermination ()
Definition at line 736 of file G4RunManagerKernel.cc.
Referenced by G4ErrorRunManagerHelper::RunTermination(), and G4RunManager::RunTermination().
SetGeometryToBeOptimized()
void G4RunManagerKernel::SetGeometryToBeOptimized (G4bool vl) inline
Definition at line 194 of file G4RunManagerKernel.hh.
Referenced by G4RunManager::SetGeometryToBeOptimized().
SetNumberOfParallelWorld()
void G4RunManagerKernel::SetNumberOfParallelWorld (G4int i) inline
Definition at line 205 of file G4RunManagerKernel.hh.
Referenced by G4WorkerRunManager::InitializeGeometry(), and G4RunManager::InitializeGeometry().
SetPhysics()
void G4RunManagerKernel::SetPhysics (G4VUserPhysicsList * uPhys)
Definition at line 513 of file G4RunManagerKernel.cc.
Referenced by G4ErrorRunManagerHelper::InitializePhysics(), and G4RunManager::SetUserInitialization().
SetPrimaryTransformer()
void G4RunManagerKernel::SetPrimaryTransformer (G4PrimaryTransformer * pt) inline
Definition at line 183 of file G4RunManagerKernel.hh.
Referenced by G4RunManager::SetPrimaryTransformer().
SetScoreSplitter()
void G4RunManagerKernel::SetScoreSplitter () private
Definition at line 1000 of file G4RunManagerKernel.cc.
Referenced by CheckRegularGeometry().
SetupDefaultRegion()
void G4RunManagerKernel::SetupDefaultRegion () protected
Definition at line 251 of file G4RunManagerKernel.cc.
Referenced by DefineWorldVolume().
SetupPhysics()
void G4RunManagerKernel::SetupPhysics () protected
Definition at line 540 of file G4RunManagerKernel.cc.
Referenced by SetPhysics().
SetupShadowProcess()
void G4RunManagerKernel::SetupShadowProcess () const protected virtual
Reimplemented in G4MTRunManagerKernel, and G4WorkerRunManagerKernel.
Definition at line 1027 of file G4RunManagerKernel.cc.
Referenced by RunInitialization(), and G4MTRunManagerKernel::SetupShadowProcess().
SetVerboseLevel()
void G4RunManagerKernel::SetVerboseLevel (G4int vl) inline
Definition at line 191 of file G4RunManagerKernel.hh.
Referenced by G4ErrorRunManagerHelper::G4ErrorRunManagerHelper(), and G4RunManager::SetVerboseLevel().
UpdateRegion()
void G4RunManagerKernel::UpdateRegion ()
Definition at line 762 of file G4RunManagerKernel.cc.
Referenced by G4MaterialScanner::DoScan(), and RunInitialization().
WorkerDefineWorldVolume()
void G4RunManagerKernel::WorkerDefineWorldVolume (G4VPhysicalVolume * worldVol, G4bool topologyIsChanged = true)
Definition at line 375 of file G4RunManagerKernel.cc.
Referenced by G4WorkerRunManager::InitializeGeometry().
WorkerUpdateWorldVolume()
void G4RunManagerKernel::WorkerUpdateWorldVolume ()
Definition at line 358 of file G4RunManagerKernel.cc.
Field Documentation
currentWorld
G4VPhysicalVolume* G4RunManagerKernel::currentWorld private
Definition at line 147 of file G4RunManagerKernel.hh.
Referenced by CheckRegions(), DefineWorldVolume(), GetCurrentWorld(), UpdateRegion(), and WorkerDefineWorldVolume().
defaultExceptionHandler
G4ExceptionHandler* G4RunManagerKernel::defaultExceptionHandler private
Definition at line 156 of file G4RunManagerKernel.hh.
Referenced by G4RunManagerKernel(), and ~G4RunManagerKernel().
defaultRegion
G4Region* G4RunManagerKernel::defaultRegion protected
Definition at line 159 of file G4RunManagerKernel.hh.
Referenced by DefineWorldVolume(), G4RunManagerKernel(), and SetupDefaultRegion().
defaultRegionForParallelWorld
G4Region* G4RunManagerKernel::defaultRegionForParallelWorld protected
Definition at line 160 of file G4RunManagerKernel.hh.
Referenced by CheckRegions(), and G4RunManagerKernel().
eventManager
G4EventManager* G4RunManagerKernel::eventManager private
Definition at line 155 of file G4RunManagerKernel.hh.
Referenced by G4RunManagerKernel(), GetEventManager(), GetPrimaryTransformer(), GetStackManager(), GetTrackingManager(), SetPrimaryTransformer(), and ~G4RunManagerKernel().
fRunManagerKernel
G4ThreadLocal G4RunManagerKernel * G4RunManagerKernel::fRunManagerKernel = 0 static private
Definition at line 75 of file G4RunManagerKernel.hh.
Referenced by G4RunManagerKernel(), GetRunManagerKernel(), and ~G4RunManagerKernel().
geometryInitialized
G4bool G4RunManagerKernel::geometryInitialized private
Definition at line 148 of file G4RunManagerKernel.hh.
Referenced by DefineWorldVolume(), InitializePhysics(), RunInitialization(), and WorkerDefineWorldVolume().
geometryNeedsToBeClosed
G4bool G4RunManagerKernel::geometryNeedsToBeClosed protected
Definition at line 161 of file G4RunManagerKernel.hh.
Referenced by DefineWorldVolume(), GeometryHasBeenModified(), ResetNavigator(), RunInitialization(), SetGeometryToBeOptimized(), and WorkerDefineWorldVolume().
geometryToBeOptimized
G4bool G4RunManagerKernel::geometryToBeOptimized private
Definition at line 150 of file G4RunManagerKernel.hh.
Referenced by ResetNavigator(), and SetGeometryToBeOptimized().
numberOfParallelWorld
G4int G4RunManagerKernel::numberOfParallelWorld private
Definition at line 153 of file G4RunManagerKernel.hh.
Referenced by GetNumberOfParallelWorld(), InitializePhysics(), and SetNumberOfParallelWorld().
numberOfStaticAllocators
G4int G4RunManagerKernel::numberOfStaticAllocators private
Definition at line 218 of file G4RunManagerKernel.hh.
Referenced by G4RunManagerKernel(), GetNumberOfStaticAllocators(), and ~G4RunManagerKernel().
physicsInitialized
G4bool G4RunManagerKernel::physicsInitialized private
Definition at line 149 of file G4RunManagerKernel.hh.
Referenced by DefineWorldVolume(), InitializePhysics(), RunInitialization(), and WorkerDefineWorldVolume().
physicsList
G4VUserPhysicsList* G4RunManagerKernel::physicsList private
Definition at line 146 of file G4RunManagerKernel.hh.
Referenced by BuildPhysicsTables(), GetPhysicsList(), InitializePhysics(), SetPhysics(), and SetupPhysics().
physicsNeedsToBeReBuilt
G4bool G4RunManagerKernel::physicsNeedsToBeReBuilt private
Definition at line 151 of file G4RunManagerKernel.hh.
Referenced by BuildPhysicsTables(), and PhysicsHasBeenModified().
runManagerKernelType
RMKType G4RunManagerKernel::runManagerKernelType protected
Definition at line 89 of file G4RunManagerKernel.hh.
Referenced by BuildPhysicsTables(), G4RunManagerKernel(), ResetNavigator(), RunTermination(), SetPhysics(), SetupDefaultRegion(), UpdateRegion(), and ~G4RunManagerKernel().
verboseLevel
G4int G4RunManagerKernel::verboseLevel private
Definition at line 152 of file G4RunManagerKernel.hh.
Referenced by BuildPhysicsTables(), DefineWorldVolume(), G4RunManagerKernel(), InitializePhysics(), ResetNavigator(), SetPhysics(), SetScoreSplitter(), SetupDefaultRegion(), SetVerboseLevel(), and ~G4RunManagerKernel().
versionString
G4String G4RunManagerKernel::versionString private
Definition at line 157 of file G4RunManagerKernel.hh.
Referenced by G4RunManagerKernel(), and GetVersionString().
The documentation for this class was generated from the following files:
source/run/include/G4RunManagerKernel.hh
source/run/src/G4RunManagerKernel.cc