Geant4: G4SampleResonance Class Reference
G4SampleResonance Class Reference
#include <G4SampleResonance.hh>
Public Types
typedef std::map< const G4ParticleDefinition *, G4double, std::less< const G4ParticleDefinition * > >::const_iterator minMassMapIterator
typedef std::map< const G4ParticleDefinition *, G4double, std::less< const G4ParticleDefinition * > > minMassMapType
Public Member Functions
G4double GetMinimumMass (const G4ParticleDefinition *p) const
G4double SampleMass (const G4double poleMass, const G4double gamma, const G4double minMass, const G4double maxMass) const
G4double SampleMass (const G4ParticleDefinition *p, const G4double maxMass) const
Private Member Functions
G4double BrWigInt0 (const G4double x, const G4double gamma, const G4double m0) const
G4double BrWigInt1 (const G4double x, const G4double gamma, const G4double m0) const
G4double BrWigInv (const G4double x, const G4double gamma, const G4double m0) const
Static Private Attributes
static G4ThreadLocal minMassMapType * minMassCache_G4MT_TLS_ = 0
Detailed Description
Definition at line 43 of file G4SampleResonance.hh.
Member Typedef Documentation
minMassMapIterator
typedef std::map<const G4ParticleDefinition*, G4double, std::less<const G4ParticleDefinition*> >::const_iterator G4SampleResonance::minMassMapIterator
Definition at line 67 of file G4SampleResonance.hh.
minMassMapType
typedef std::map<const G4ParticleDefinition*, G4double, std::less<const G4ParticleDefinition*> > G4SampleResonance::minMassMapType
Definition at line 68 of file G4SampleResonance.hh.
Member Function Documentation
BrWigInt0()
G4double G4SampleResonance::BrWigInt0 (const G4double x, const G4double gamma, const G4double m0) const inline private
Definition at line 56 of file G4SampleResonance.hh.
Referenced by BrWigInt1(), and SampleMass().
BrWigInt1()
G4double G4SampleResonance::BrWigInt1 (const G4double x, const G4double gamma, const G4double m0) const inline private
Definition at line 59 of file G4SampleResonance.hh.
BrWigInv()
G4double G4SampleResonance::BrWigInv (const G4double x, const G4double gamma, const G4double m0) const inline private
Definition at line 62 of file G4SampleResonance.hh.
Referenced by SampleMass().
GetMinimumMass()
G4double G4SampleResonance::GetMinimumMass (const G4ParticleDefinition * p) const
Definition at line 46 of file G4SampleResonance.cc.
Referenced by G4KineticTrack::Decay(), G4ElasticHNScattering::ElasticScattering(), G4KineticTrack::G4KineticTrack(), and SampleMass().
SampleMass() [1/2]
G4double G4SampleResonance::SampleMass (const G4double poleMass, const G4double gamma, const G4double minMass, const G4double maxMass) const
Definition at line 110 of file G4SampleResonance.cc.
Referenced by G4KineticTrack::Decay(), G4ExcitedStringDecay::FragmentStrings(), and SampleMass().
SampleMass() [2/2]
G4double G4SampleResonance::SampleMass (const G4ParticleDefinition * p, const G4double maxMass) const
Definition at line 104 of file G4SampleResonance.cc.
Field Documentation
minMassCache_G4MT_TLS_
G4ThreadLocal G4SampleResonance::minMassMapType * G4SampleResonance::minMassCache_G4MT_TLS_ = 0 static private
Definition at line 72 of file G4SampleResonance.hh.
Referenced by GetMinimumMass(), and SampleMass().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/util/include/G4SampleResonance.hh
source/processes/hadronic/models/util/src/G4SampleResonance.cc