Geant4: G4BinaryNeutronBuilder Class Reference
G4BinaryNeutronBuilder Class Reference
#include <G4BinaryNeutronBuilder.hh>
Public Member Functions
G4BinaryNeutronBuilder ()
virtual ~G4BinaryNeutronBuilder ()
virtual void Build (G4HadronElasticProcess *) final override
virtual void Build (G4HadronFissionProcess *) final override
virtual void Build (G4HadronCaptureProcess *) final override
virtual void Build (G4NeutronInelasticProcess *aP) final override
virtual void SetMinEnergy (G4double aM) final override
virtual void SetMaxEnergy (G4double aM) final override
virtual void Build (G4HadronElasticProcess *aP)=0
virtual void Build (G4HadronFissionProcess *aP)=0
virtual void Build (G4HadronCaptureProcess *aP)=0
virtual void Build (G4NeutronInelasticProcess *aP)=0
Public Member Functions inherited from G4VNeutronBuilder
G4VNeutronBuilder ()=default
virtual ~G4VNeutronBuilder ()
virtual void Build ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4BinaryCascade * theModel
G4double theMin
G4double theMax
Detailed Description
Definition at line 52 of file G4BinaryNeutronBuilder.hh.
Constructor & Destructor Documentation
G4BinaryNeutronBuilder()
G4BinaryNeutronBuilder::G4BinaryNeutronBuilder ()
Definition at line 46 of file G4BinaryNeutronBuilder.cc.
~G4BinaryNeutronBuilder()
virtual G4BinaryNeutronBuilder::~G4BinaryNeutronBuilder () inline virtual
Definition at line 56 of file G4BinaryNeutronBuilder.hh.
Member Function Documentation
Build() [1/8]
virtual void G4BinaryNeutronBuilder::Build (G4HadronCaptureProcess *) inline final override virtual
Implements G4VNeutronBuilder.
Definition at line 60 of file G4BinaryNeutronBuilder.hh.
Build() [2/8]
virtual void G4VNeutronBuilder::Build
Build() [3/8]
virtual void G4BinaryNeutronBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VNeutronBuilder.
Definition at line 58 of file G4BinaryNeutronBuilder.hh.
Build() [4/8]
virtual void G4VNeutronBuilder::Build
Build() [5/8]
virtual void G4BinaryNeutronBuilder::Build (G4HadronFissionProcess *) inline final override virtual
Implements G4VNeutronBuilder.
Definition at line 59 of file G4BinaryNeutronBuilder.hh.
Build() [6/8]
virtual void G4VNeutronBuilder::Build
Build() [7/8]
void G4BinaryNeutronBuilder::Build (G4NeutronInelasticProcess * aP) final override virtual
Implements G4VNeutronBuilder.
Definition at line 54 of file G4BinaryNeutronBuilder.cc.
Build() [8/8]
virtual void G4VNeutronBuilder::Build
SetMaxEnergy()
virtual void G4BinaryNeutronBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 64 of file G4BinaryNeutronBuilder.hh.
Referenced by G4HadronPhysicsQGSP_BIC_AllHP::CreateModels(), and G4HadronPhysicsQGSP_BIC_HP::CreateModels().
SetMinEnergy()
virtual void G4BinaryNeutronBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 63 of file G4BinaryNeutronBuilder.hh.
Referenced by G4HadronPhysicsQGSP_BIC_AllHP::CreateModels(), and G4HadronPhysicsQGSP_BIC_HP::CreateModels().
Field Documentation
theMax
G4double G4BinaryNeutronBuilder::theMax private
Definition at line 70 of file G4BinaryNeutronBuilder.hh.
Referenced by Build(), G4BinaryNeutronBuilder(), and SetMaxEnergy().
theMin
G4double G4BinaryNeutronBuilder::theMin private
Definition at line 69 of file G4BinaryNeutronBuilder.hh.
Referenced by Build(), G4BinaryNeutronBuilder(), and SetMinEnergy().
theModel
G4BinaryCascade* G4BinaryNeutronBuilder::theModel private
Definition at line 68 of file G4BinaryNeutronBuilder.hh.
Referenced by Build(), and G4BinaryNeutronBuilder().
The documentation for this class was generated from the following files:
source/physics_lists/builders/include/G4BinaryNeutronBuilder.hh
source/physics_lists/builders/src/G4BinaryNeutronBuilder.cc