Geant4: G4SDKineticEnergyFilter Class Reference
G4SDKineticEnergyFilter Class Reference
#include <G4SDKineticEnergyFilter.hh>
Public Member Functions
G4SDKineticEnergyFilter (G4String name, G4double elow=0.0, G4double ehigh=DBL_MAX)
virtual ~G4SDKineticEnergyFilter ()
virtual G4bool Accept (const G4Step *) const
void SetKineticEnergy (G4double elow, G4double ehigh)
void SetLowEnergy (G4double elow)
void SetHighEnergy (G4double ehigh)
void show ()
Public Member Functions inherited from G4VSDFilter
G4VSDFilter (G4String name)
virtual ~G4VSDFilter ()
G4String GetName () const
Private Attributes
G4double fLowEnergy
G4double fHighEnergy
Additional Inherited Members
Protected Attributes inherited from G4VSDFilter
G4String filterName
Detailed Description
Definition at line 50 of file G4SDKineticEnergyFilter.hh.
Constructor & Destructor Documentation
G4SDKineticEnergyFilter()
G4SDKineticEnergyFilter::G4SDKineticEnergyFilter (G4String name, G4double elow = 0.0, G4double ehigh = DBL_MAX)
Definition at line 43 of file G4SDKineticEnergyFilter.cc.
~G4SDKineticEnergyFilter()
G4SDKineticEnergyFilter::~G4SDKineticEnergyFilter () virtual
Definition at line 49 of file G4SDKineticEnergyFilter.cc.
Member Function Documentation
Accept()
G4bool G4SDKineticEnergyFilter::Accept (const G4Step * aStep) const virtual
Implements G4VSDFilter.
Definition at line 52 of file G4SDKineticEnergyFilter.cc.
Referenced by G4SDParticleWithEnergyFilter::Accept().
SetHighEnergy()
void G4SDKineticEnergyFilter::SetHighEnergy (G4double ehigh)
SetKineticEnergy()
void G4SDKineticEnergyFilter::SetKineticEnergy (G4double elow, G4double ehigh)
Definition at line 60 of file G4SDKineticEnergyFilter.cc.
Referenced by G4SDParticleWithEnergyFilter::SetKineticEnergy().
SetLowEnergy()
void G4SDKineticEnergyFilter::SetLowEnergy (G4double elow)
show()
void G4SDKineticEnergyFilter::show ()
Definition at line 65 of file G4SDKineticEnergyFilter.cc.
Referenced by G4SDParticleWithEnergyFilter::show().
Field Documentation
fHighEnergy
G4double G4SDKineticEnergyFilter::fHighEnergy private
Definition at line 74 of file G4SDKineticEnergyFilter.hh.
Referenced by Accept(), SetKineticEnergy(), and show().
fLowEnergy
G4double G4SDKineticEnergyFilter::fLowEnergy private
Definition at line 73 of file G4SDKineticEnergyFilter.hh.
Referenced by Accept(), SetKineticEnergy(), and show().
The documentation for this class was generated from the following files:
source/digits_hits/scorer/include/G4SDKineticEnergyFilter.hh
source/digits_hits/scorer/src/G4SDKineticEnergyFilter.cc