Geant4: G4UserWorkerThreadInitialization Class Reference
G4UserWorkerThreadInitialization Class Reference
#include <G4UserWorkerThreadInitialization.hh>
Public Member Functions
G4UserWorkerThreadInitialization ()
virtual ~G4UserWorkerThreadInitialization ()
virtual G4Thread * CreateAndStartWorker (G4WorkerThread *workerThreadContext)
virtual void SetupRNGEngine (const CLHEP::HepRandomEngine *aRNGEngine) const
virtual void JoinWorker (G4Thread *aThread)
virtual G4WorkerRunManager * CreateWorkerRunManager () const
Detailed Description
Definition at line 47 of file G4UserWorkerThreadInitialization.hh.
Constructor & Destructor Documentation
G4UserWorkerThreadInitialization()
G4UserWorkerThreadInitialization::G4UserWorkerThreadInitialization ()
Definition at line 70 of file G4UserWorkerThreadInitialization.cc.
~G4UserWorkerThreadInitialization()
G4UserWorkerThreadInitialization::~G4UserWorkerThreadInitialization () virtual
Definition at line 73 of file G4UserWorkerThreadInitialization.cc.
Member Function Documentation
CreateAndStartWorker()
G4Thread * G4UserWorkerThreadInitialization::CreateAndStartWorker (G4WorkerThread * workerThreadContext) virtual
Reimplemented in tbbUserWorkerInitialization.
Definition at line 52 of file G4UserWorkerThreadInitialization.cc.
Referenced by G4MTRunManager::CreateAndStartWorkers().
CreateWorkerRunManager()
G4WorkerRunManager * G4UserWorkerThreadInitialization::CreateWorkerRunManager () const virtual
Reimplemented in tbbUserWorkerInitialization.
Definition at line 131 of file G4UserWorkerThreadInitialization.cc.
Referenced by tbbTask::execute(), and G4MTRunManagerKernel::StartThread().
JoinWorker()
void G4UserWorkerThreadInitialization::JoinWorker (G4Thread * aThread) virtual
Reimplemented in tbbUserWorkerInitialization.
Definition at line 65 of file G4UserWorkerThreadInitialization.cc.
Referenced by G4MTRunManager::TerminateWorkers().
SetupRNGEngine()
void G4UserWorkerThreadInitialization::SetupRNGEngine (const CLHEP::HepRandomEngine * aRNGEngine) const virtual
Definition at line 81 of file G4UserWorkerThreadInitialization.cc.
Referenced by tbbTask::execute(), G4WorkerRunManager::SetupDefaultRNGEngine(), and G4MTRunManagerKernel::StartThread().
The documentation for this class was generated from the following files:
source/run/include/G4UserWorkerThreadInitialization.hh
source/run/src/G4UserWorkerThreadInitialization.cc