Geant4: G4VPhysChemIO Class Reference
G4VPhysChemIO Class Reference abstract
#include <G4VPhysChemIO.hh>
Public Member Functions
G4VPhysChemIO ()
virtual ~G4VPhysChemIO ()
virtual void InitializeMaster ()
virtual void InitializeThread ()
virtual void InitializeFile ()=0
virtual void NewRun ()=0
virtual void NewEvent ()=0
virtual void CreateWaterMolecule (G4int electronicModif, G4int, G4double energy, const G4Track *)=0
When DNA physics model create a water molecule, you'll get a notification through this method.
virtual void CreateSolvatedElectron (const G4Track *, G4ThreeVector *finalPosition=0)=0
Same idea as the previous method but for solvated electron.
virtual void WriteInto (const G4String &, std::ios_base::openmode mode=std::ios_base::out)=0
Tells the chemistry manager to write into a file the position and electronic state of the water molecule and the position thermalized or not of the solvated electron.
virtual void AddEmptyLineInOuputFile ()
virtual void CloseFile ()=0
Close the file specified with WriteInto.
Detailed Description
Definition at line 43 of file G4VPhysChemIO.hh.
Constructor & Destructor Documentation
G4VPhysChemIO()
G4VPhysChemIO::G4VPhysChemIO ()
Definition at line 37 of file G4VPhysChemIO.cc.
~G4VPhysChemIO()
G4VPhysChemIO::~G4VPhysChemIO () virtual
Definition at line 43 of file G4VPhysChemIO.cc.
Member Function Documentation
AddEmptyLineInOuputFile()
virtual void G4VPhysChemIO::AddEmptyLineInOuputFile () inline virtual
Reimplemented in G4PhysChemIO::G4Analysis, and G4PhysChemIO::FormattedText.
Definition at line 88 of file G4VPhysChemIO.hh.
Referenced by G4DNAChemistryManager::AddEmptyLineInOuputFile().
CloseFile()
virtual void G4VPhysChemIO::CloseFile () pure virtual
Close the file specified with WriteInto.
Implemented in G4PhysChemIO::G4Analysis, and G4PhysChemIO::FormattedText.
Referenced by G4DNAChemistryManager::CloseFile().
CreateSolvatedElectron()
virtual void G4VPhysChemIO::CreateSolvatedElectron (const G4Track * , G4ThreeVector * finalPosition = 0) pure virtual
Same idea as the previous method but for solvated electron.
This method should be used by the physics model of the ElectronSolvatation process.
Implemented in G4PhysChemIO::G4Analysis, and G4PhysChemIO::FormattedText.
Referenced by G4DNAChemistryManager::CreateSolvatedElectron().
CreateWaterMolecule()
virtual void G4VPhysChemIO::CreateWaterMolecule (G4int electronicModif, G4int , G4double energy, const G4Track *) pure virtual
When DNA physics model create a water molecule, you'll get a notification through this method.
The ElectronicModification is a flag telling whether the molecule is ionized or excited, the electronic level is calculated by the model and the IncomingTrack is the track responsible for the creation of this molecule (electron, proton...)
Implemented in G4PhysChemIO::G4Analysis, and G4PhysChemIO::FormattedText.
Referenced by G4DNAChemistryManager::CreateWaterMolecule().
InitializeFile()
virtual void G4VPhysChemIO::InitializeFile () pure virtual
Implemented in G4PhysChemIO::G4Analysis, and G4PhysChemIO::FormattedText.
Referenced by G4DNAChemistryManager::InitializeFile().
InitializeMaster()
virtual void G4VPhysChemIO::InitializeMaster () inline virtual
Reimplemented in G4PhysChemIO::G4Analysis, and G4PhysChemIO::FormattedText.
Definition at line 49 of file G4VPhysChemIO.hh.
InitializeThread()
virtual void G4VPhysChemIO::InitializeThread () inline virtual
Reimplemented in G4PhysChemIO::G4Analysis, and G4PhysChemIO::FormattedText.
Definition at line 50 of file G4VPhysChemIO.hh.
NewEvent()
virtual void G4VPhysChemIO::NewEvent () pure virtual
Implemented in G4PhysChemIO::G4Analysis, and G4PhysChemIO::FormattedText.
NewRun()
virtual void G4VPhysChemIO::NewRun () pure virtual
Implemented in G4PhysChemIO::G4Analysis, and G4PhysChemIO::FormattedText.
WriteInto()
virtual void G4VPhysChemIO::WriteInto (const G4String & , std::ios_base::openmode mode = std::ios_base::out) pure virtual
Tells the chemistry manager to write into a file the position and electronic state of the water molecule and the position thermalized or not of the solvated electron.
Implemented in G4PhysChemIO::G4Analysis, and G4PhysChemIO::FormattedText.
Referenced by G4DNAChemistryManager::WriteInto().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/dna/utils/include/G4VPhysChemIO.hh
source/processes/electromagnetic/dna/utils/src/G4VPhysChemIO.cc