Geant4: G4DCtable Class Reference
G4DCtable Class Reference
#include <G4DCtable.hh>
Public Member Functions
G4DCtable ()
~G4DCtable ()
G4int Registor (G4String SDname, G4String DCname)
G4int GetCollectionID (G4String DCname) const
G4int GetCollectionID (G4VDigitizerModule *aDM) const
G4int entries () const
G4String GetDMname (G4int i) const
G4String GetDCname (G4int i) const
Private Attributes
std::vector< G4String > DMlist
std::vector< G4String > DClist
Detailed Description
Definition at line 49 of file G4DCtable.hh.
Constructor & Destructor Documentation
G4DCtable()
G4DCtable::G4DCtable ()
Definition at line 32 of file G4DCtable.cc.
~G4DCtable()
G4DCtable::~G4DCtable ()
Definition at line 34 of file G4DCtable.cc.
Member Function Documentation
entries()
G4int G4DCtable::entries () const inline
Definition at line 65 of file G4DCtable.hh.
Referenced by G4DigiManager::GetCollectionCapacity(), GetDCname(), GetDMname(), and G4DigiManager::SetDigiCollection().
GetCollectionID() [1/2]
G4int G4DCtable::GetCollectionID (G4String DCname) const
Definition at line 45 of file G4DCtable.cc.
Referenced by G4DigiManager::GetDigiCollectionID().
GetCollectionID() [2/2]
G4int G4DCtable::GetCollectionID (G4VDigitizerModule * aDM) const
Definition at line 76 of file G4DCtable.cc.
GetDCname()
G4String G4DCtable::GetDCname (G4int i) const inline
Definition at line 72 of file G4DCtable.hh.
GetDMname()
G4String G4DCtable::GetDMname (G4int i) const inline
Definition at line 67 of file G4DCtable.hh.
Registor()
G4int G4DCtable::Registor (G4String SDname, G4String DCname)
Definition at line 36 of file G4DCtable.cc.
Referenced by G4DigiManager::AddNewModule().
Field Documentation
DClist
std::vector<G4String> G4DCtable::DClist private
Definition at line 62 of file G4DCtable.hh.
Referenced by entries(), GetCollectionID(), GetDCname(), and Registor().
DMlist
std::vector<G4String> G4DCtable::DMlist private
Definition at line 61 of file G4DCtable.hh.
Referenced by GetCollectionID(), GetDMname(), and Registor().
The documentation for this class was generated from the following files:
source/readout/include/G4DCtable.hh
source/readout/src/G4DCtable.cc