Geant4: DicomVBeamDevice Class Reference
DicomVBeamDevice Class Reference abstract
#include <DicomVBeamDevice.hh>
Public Member Functions
void SetNumberOfLeafJawPairs (Sint32 dat)
Sint32 GetNumberOfLeafJawPairs () const
void SetType (OFString dat)
OFString GetType () const
void AddPositionBoundary (Float64 dat)
Float64 GetPositionBoundary (size_t ii)
virtual void DumpToFile (std::ofstream &out)=0
virtual void Print (std::ostream &out)=0
Protected Member Functions
DicomVBeamDevice ()
~DicomVBeamDevice ()
Protected Attributes
OFString theType
Sint32 theNumberOfLeafJawPairs
std::vector< Float64 > thePositionBoundaries
Detailed Description
Definition at line 39 of file DicomVBeamDevice.hh.
Constructor & Destructor Documentation
DicomVBeamDevice()
DicomVBeamDevice::DicomVBeamDevice () protected
Definition at line 31 of file DicomVBeamDevice.cc.
~DicomVBeamDevice()
DicomVBeamDevice::~DicomVBeamDevice () inline protected
Definition at line 43 of file DicomVBeamDevice.hh.
Member Function Documentation
AddPositionBoundary()
void DicomVBeamDevice::AddPositionBoundary (Float64 dat) inline
Definition at line 58 of file DicomVBeamDevice.hh.
Referenced by DicomBeamDevicePos::DicomBeamDevicePos(), and DicomBeamDeviceRef::DicomBeamDeviceRef().
DumpToFile()
virtual void DicomVBeamDevice::DumpToFile (std::ofstream & out) pure virtual
Implemented in DicomBeamDeviceRef, and DicomBeamDevicePos.
GetNumberOfLeafJawPairs()
Sint32 DicomVBeamDevice::GetNumberOfLeafJawPairs () const inline
Definition at line 49 of file DicomVBeamDevice.hh.
GetPositionBoundary()
Float64 DicomVBeamDevice::GetPositionBoundary (size_t ii) inline
Definition at line 61 of file DicomVBeamDevice.hh.
GetType()
OFString DicomVBeamDevice::GetType () const inline
Definition at line 55 of file DicomVBeamDevice.hh.
Print()
virtual void DicomVBeamDevice::Print (std::ostream & out) pure virtual
Implemented in DicomBeamDeviceRef, and DicomBeamDevicePos.
SetNumberOfLeafJawPairs()
void DicomVBeamDevice::SetNumberOfLeafJawPairs (Sint32 dat) inline
Definition at line 46 of file DicomVBeamDevice.hh.
Referenced by DicomBeamDevicePos::DicomBeamDevicePos(), and DicomBeamDeviceRef::DicomBeamDeviceRef().
SetType()
void DicomVBeamDevice::SetType (OFString dat) inline
Definition at line 52 of file DicomVBeamDevice.hh.
Referenced by DicomBeamDevicePos::DicomBeamDevicePos(), and DicomBeamDeviceRef::DicomBeamDeviceRef().
Field Documentation
theNumberOfLeafJawPairs
Sint32 DicomVBeamDevice::theNumberOfLeafJawPairs protected
Definition at line 71 of file DicomVBeamDevice.hh.
Referenced by DicomBeamDevicePos::DumpToFile(), GetNumberOfLeafJawPairs(), and SetNumberOfLeafJawPairs().
thePositionBoundaries
std::vector<Float64> DicomVBeamDevice::thePositionBoundaries protected
Definition at line 72 of file DicomVBeamDevice.hh.
Referenced by AddPositionBoundary(), DicomBeamDevicePos::DumpToFile(), and GetPositionBoundary().
theType
OFString DicomVBeamDevice::theType protected
Definition at line 70 of file DicomVBeamDevice.hh.
Referenced by DicomBeamDevicePos::DumpToFile(), DicomBeamDeviceRef::DumpToFile(), GetType(), and SetType().
The documentation for this class was generated from the following files:
examples/extended/medical/DICOM/dicomReader/include/DicomVBeamDevice.hh
examples/extended/medical/DICOM/dicomReader/src/DicomVBeamDevice.cc