Geant4: G4TriangularFacet Class Reference
G4TriangularFacet Class Reference
#include <G4TriangularFacet.hh>
Public Member Functions
G4TriangularFacet ()
~G4TriangularFacet ()
G4TriangularFacet (const G4ThreeVector &vt0, const G4ThreeVector &vt1, const G4ThreeVector &vt2, G4FacetVertexType)
G4TriangularFacet (const G4TriangularFacet &right)
G4TriangularFacet & operator= (const G4TriangularFacet &right)
G4VFacet * GetClone ()
G4TriangularFacet * GetFlippedFacet ()
G4ThreeVector Distance (const G4ThreeVector &p)
G4double Distance (const G4ThreeVector &p, G4double minDist)
G4double Distance (const G4ThreeVector &p, G4double minDist, const G4bool outgoing)
G4double Extent (const G4ThreeVector axis)
G4bool Intersect (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool outgoing, G4double &distance, G4double &distFromSurface, G4ThreeVector &normal)
G4double GetArea () const
G4ThreeVector GetPointOnFace () const
G4ThreeVector GetSurfaceNormal () const
void SetSurfaceNormal (G4ThreeVector normal)
G4GeometryType GetEntityType () const
G4bool IsDefined () const
G4int GetNumberOfVertices () const
G4ThreeVector GetVertex (G4int i) const
void SetVertex (G4int i, const G4ThreeVector &val)
G4ThreeVector GetCircumcentre () const
G4double GetRadius () const
G4int AllocatedMemory ()
G4int GetVertexIndex (G4int i) const
void SetVertexIndex (G4int i, G4int j)
void SetVertices (std::vector< G4ThreeVector > *v)
Public Member Functions inherited from G4VFacet
virtual ~G4VFacet ()
G4bool operator== (const G4VFacet &right) const
void ApplyTranslation (const G4ThreeVector v)
std::ostream & StreamInfo (std::ostream &os) const
G4bool IsInside (const G4ThreeVector &p) const
Private Member Functions
void CopyFrom (const G4TriangularFacet &rhs)
Private Attributes
G4ThreeVector fSurfaceNormal
G4double fArea
G4ThreeVector fCircumcentre
G4double fRadius
G4int fIndices [3]
std::vector< G4ThreeVector > * fVertices
G4double fA
G4double fB
G4double fC
G4double fDet
G4double fSqrDist
G4ThreeVector fE1
G4ThreeVector fE2
G4bool fIsDefined
Additional Inherited Members
Static Protected Attributes inherited from G4VFacet
static const G4double dirTolerance = 1.0E-14
static const G4double kCarTolerance
Detailed Description
Definition at line 64 of file G4TriangularFacet.hh.
Constructor & Destructor Documentation
G4TriangularFacet() [1/3]
G4TriangularFacet::G4TriangularFacet ()
Definition at line 166 of file G4TriangularFacet.cc.
Referenced by GetClone(), and GetFlippedFacet().
~G4TriangularFacet()
G4TriangularFacet::~G4TriangularFacet ()
Definition at line 186 of file G4TriangularFacet.cc.
G4TriangularFacet() [2/3]
G4TriangularFacet::G4TriangularFacet (const G4ThreeVector & vt0, const G4ThreeVector & vt1, const G4ThreeVector & vt2, G4FacetVertexType vertexType)
Definition at line 78 of file G4TriangularFacet.cc.
G4TriangularFacet() [3/3]
G4TriangularFacet::G4TriangularFacet (const G4TriangularFacet & right)
Definition at line 207 of file G4TriangularFacet.cc.
Member Function Documentation
AllocatedMemory()
G4int G4TriangularFacet::AllocatedMemory () inline virtual
Implements G4VFacet.
Definition at line 164 of file G4TriangularFacet.hh.
Referenced by G4QuadrangularFacet::AllocatedMemory().
CopyFrom()
void G4TriangularFacet::CopyFrom (const G4TriangularFacet & rhs) private
Definition at line 193 of file G4TriangularFacet.cc.
Referenced by G4TriangularFacet(), and operator=().
Distance() [1/3]
G4ThreeVector G4TriangularFacet::Distance (const G4ThreeVector & p)
Definition at line 267 of file G4TriangularFacet.cc.
Referenced by Distance(), G4QuadrangularFacet::Distance(), and Intersect().
Distance() [2/3]
G4double G4TriangularFacet::Distance (const G4ThreeVector & p, G4double minDist) virtual
Implements G4VFacet.
Definition at line 451 of file G4TriangularFacet.cc.
Distance() [3/3]
G4double G4TriangularFacet::Distance (const G4ThreeVector & p, G4double minDist, const G4bool outgoing) virtual
Implements G4VFacet.
Definition at line 486 of file G4TriangularFacet.cc.
Extent()
G4double G4TriangularFacet::Extent (const G4ThreeVector axis) virtual
Implements G4VFacet.
Definition at line 527 of file G4TriangularFacet.cc.
GetArea()
G4double G4TriangularFacet::GetArea () const virtual
Implements G4VFacet.
Definition at line 770 of file G4TriangularFacet.cc.
Referenced by G4QuadrangularFacet::GetArea(), and G4QuadrangularFacet::GetPointOnFace().
GetCircumcentre()
G4ThreeVector G4TriangularFacet::GetCircumcentre () const inline virtual
Implements G4VFacet.
Definition at line 154 of file G4TriangularFacet.hh.
GetClone()
G4VFacet * G4TriangularFacet::GetClone () virtual
Implements G4VFacet.
Definition at line 232 of file G4TriangularFacet.cc.
GetEntityType()
G4GeometryType G4TriangularFacet::GetEntityType () const virtual
Implements G4VFacet.
Definition at line 777 of file G4TriangularFacet.cc.
GetFlippedFacet()
G4TriangularFacet * G4TriangularFacet::GetFlippedFacet ()
Definition at line 246 of file G4TriangularFacet.cc.
GetNumberOfVertices()
G4int G4TriangularFacet::GetNumberOfVertices () const inline virtual
Implements G4VFacet.
Definition at line 138 of file G4TriangularFacet.hh.
Referenced by AllocatedMemory().
GetPointOnFace()
G4ThreeVector G4TriangularFacet::GetPointOnFace () const virtual
Implements G4VFacet.
Definition at line 756 of file G4TriangularFacet.cc.
Referenced by G4QuadrangularFacet::GetPointOnFace().
GetRadius()
G4double G4TriangularFacet::GetRadius () const inline virtual
Implements G4VFacet.
Definition at line 159 of file G4TriangularFacet.hh.
GetSurfaceNormal()
G4ThreeVector G4TriangularFacet::GetSurfaceNormal () const virtual
Implements G4VFacet.
Definition at line 784 of file G4TriangularFacet.cc.
Referenced by G4QuadrangularFacet::GetSurfaceNormal().
GetVertex()
G4ThreeVector G4TriangularFacet::GetVertex (G4int i) const inline virtual
Implements G4VFacet.
Definition at line 143 of file G4TriangularFacet.hh.
Referenced by Distance(), Extent(), G4TriangularFacet(), GetClone(), GetFlippedFacet(), GetPointOnFace(), G4QuadrangularFacet::GetVertex(), and Intersect().
GetVertexIndex()
G4int G4TriangularFacet::GetVertexIndex (G4int i) const inline virtual
Implements G4VFacet.
Definition at line 171 of file G4TriangularFacet.hh.
Referenced by G4QuadrangularFacet::GetVertexIndex().
Intersect()
G4bool G4TriangularFacet::Intersect (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool outgoing, G4double & distance, G4double & distFromSurface, G4ThreeVector & normal) virtual
Implements G4VFacet.
Definition at line 564 of file G4TriangularFacet.cc.
Referenced by G4QuadrangularFacet::Intersect().
IsDefined()
G4bool G4TriangularFacet::IsDefined () const inline virtual
Implements G4VFacet.
Definition at line 133 of file G4TriangularFacet.hh.
Referenced by G4QuadrangularFacet::IsDefined().
operator=()
G4TriangularFacet & G4TriangularFacet::operator= (const G4TriangularFacet & right)
Definition at line 216 of file G4TriangularFacet.cc.
SetSurfaceNormal()
void G4TriangularFacet::SetSurfaceNormal (G4ThreeVector normal)
Definition at line 791 of file G4TriangularFacet.cc.
SetVertex()
void G4TriangularFacet::SetVertex (G4int i, const G4ThreeVector & val) inline virtual
Implements G4VFacet.
Definition at line 149 of file G4TriangularFacet.hh.
Referenced by G4TriangularFacet(), and G4QuadrangularFacet::SetVertex().
SetVertexIndex()
void G4TriangularFacet::SetVertexIndex (G4int i, G4int j) inline virtual
Implements G4VFacet.
Definition at line 177 of file G4TriangularFacet.hh.
Referenced by G4QuadrangularFacet::SetVertexIndex().
SetVertices()
void G4TriangularFacet::SetVertices (std::vector< G4ThreeVector > * v) inline virtual
Implements G4VFacet.
Definition at line 182 of file G4TriangularFacet.hh.
Referenced by operator=(), G4QuadrangularFacet::SetVertices(), and ~G4TriangularFacet().
Field Documentation
fA
G4double G4TriangularFacet::fA private
Definition at line 122 of file G4TriangularFacet.hh.
Referenced by Distance(), G4TriangularFacet(), and Intersect().
fArea
G4double G4TriangularFacet::fArea private
Definition at line 115 of file G4TriangularFacet.hh.
Referenced by G4TriangularFacet(), and GetArea().
fB
G4double G4TriangularFacet::fB private
Definition at line 122 of file G4TriangularFacet.hh.
Referenced by Distance(), G4TriangularFacet(), and Intersect().
fC
G4double G4TriangularFacet::fC private
Definition at line 122 of file G4TriangularFacet.hh.
Referenced by Distance(), G4TriangularFacet(), and Intersect().
fCircumcentre
G4ThreeVector G4TriangularFacet::fCircumcentre private
Definition at line 116 of file G4TriangularFacet.hh.
Referenced by Distance(), G4TriangularFacet(), and GetCircumcentre().
fDet
G4double G4TriangularFacet::fDet private
Definition at line 123 of file G4TriangularFacet.hh.
Referenced by Distance(), G4TriangularFacet(), and Intersect().
fE1
G4ThreeVector G4TriangularFacet::fE1 private
Definition at line 125 of file G4TriangularFacet.hh.
Referenced by Distance(), G4TriangularFacet(), GetPointOnFace(), and Intersect().
fE2
G4ThreeVector G4TriangularFacet::fE2 private
Definition at line 125 of file G4TriangularFacet.hh.
Referenced by Distance(), G4TriangularFacet(), GetPointOnFace(), and Intersect().
fIndices
G4int G4TriangularFacet::fIndices[3] private
Definition at line 118 of file G4TriangularFacet.hh.
Referenced by CopyFrom(), G4TriangularFacet(), GetVertex(), GetVertexIndex(), SetVertexIndex(), and SetVertices().
fIsDefined
G4bool G4TriangularFacet::fIsDefined private
Definition at line 126 of file G4TriangularFacet.hh.
Referenced by G4TriangularFacet(), and IsDefined().
fRadius
G4double G4TriangularFacet::fRadius private
Definition at line 117 of file G4TriangularFacet.hh.
Referenced by Distance(), G4TriangularFacet(), and GetRadius().
fSqrDist
G4double G4TriangularFacet::fSqrDist private
Definition at line 124 of file G4TriangularFacet.hh.
Referenced by Distance(), and Intersect().
fSurfaceNormal
G4ThreeVector G4TriangularFacet::fSurfaceNormal private
Definition at line 114 of file G4TriangularFacet.hh.
Referenced by Distance(), G4TriangularFacet(), GetSurfaceNormal(), Intersect(), and SetSurfaceNormal().
fVertices
std::vector<G4ThreeVector>* G4TriangularFacet::fVertices private
Definition at line 120 of file G4TriangularFacet.hh.
Referenced by CopyFrom(), G4TriangularFacet(), and SetVertices().
The documentation for this class was generated from the following files:
source/geometry/solids/specific/include/G4TriangularFacet.hh
source/geometry/solids/specific/src/G4TriangularFacet.cc