Geant4: G4DiffractiveExcitation Class Reference
G4DiffractiveExcitation Class Reference
#include <G4DiffractiveExcitation.hh>
Data Structures
struct CommonVariables
Public Member Functions
G4DiffractiveExcitation ()
virtual ~G4DiffractiveExcitation ()
virtual G4bool ExciteParticipants (G4VSplitableHadron *aPartner, G4VSplitableHadron *bPartner, G4FTFParameters *theParameters, G4ElasticHNScattering *theElastic) const
virtual void CreateStrings (G4VSplitableHadron *aHadron, G4bool isProjectile, G4ExcitedString *&FirstString, G4ExcitedString *&SecondString, G4FTFParameters *theParameters) const
Private Member Functions
G4DiffractiveExcitation (const G4DiffractiveExcitation &right)
const G4DiffractiveExcitation & operator= (const G4DiffractiveExcitation &right)
G4bool operator== (const G4DiffractiveExcitation &right) const
G4bool operator!= (const G4DiffractiveExcitation &right) const
G4double LambdaF (G4double sqrM, G4double sqrM1, G4double sqrM2) const
G4ThreeVector GaussianPt (G4double AveragePt2, G4double maxPtSquare) const
G4double ChooseP (G4double Pmin, G4double Pmax) const
G4double GetQuarkFractionOfKink (G4double zmin, G4double zmax) const
void UnpackMeson (G4int IdPDG, G4int &Q1, G4int &Q2) const
void UnpackBaryon (G4int IdPDG, G4int &Q1, G4int &Q2, G4int &Q3) const
G4int NewNucleonId (G4int Q1, G4int Q2, G4int Q3) const
G4int ExciteParticipants_doChargeExchange (G4VSplitableHadron *projectile, G4VSplitableHadron *target, G4FTFParameters *theParameters, G4ElasticHNScattering *theElastic, CommonVariables &common) const
G4bool ExciteParticipants_doDiffraction (G4VSplitableHadron *projectile, G4VSplitableHadron *target, G4FTFParameters *theParameters, CommonVariables &common) const
G4bool ExciteParticipants_doNonDiffraction (G4VSplitableHadron *projectile, G4VSplitableHadron *target, G4FTFParameters *theParameters, CommonVariables &common) const
Detailed Description
Definition at line 50 of file G4DiffractiveExcitation.hh.
Constructor & Destructor Documentation
G4DiffractiveExcitation() [1/2]
G4DiffractiveExcitation::G4DiffractiveExcitation ()
Definition at line 81 of file G4DiffractiveExcitation.cc.
~G4DiffractiveExcitation()
G4DiffractiveExcitation::~G4DiffractiveExcitation () virtual
Definition at line 86 of file G4DiffractiveExcitation.cc.
G4DiffractiveExcitation() [2/2]
G4DiffractiveExcitation::G4DiffractiveExcitation (const G4DiffractiveExcitation & right) private
Definition at line 1426 of file G4DiffractiveExcitation.cc.
Member Function Documentation
ChooseP()
G4double G4DiffractiveExcitation::ChooseP (G4double Pmin, G4double Pmax) const private
Definition at line 1319 of file G4DiffractiveExcitation.cc.
Referenced by ExciteParticipants_doDiffraction(), and ExciteParticipants_doNonDiffraction().
CreateStrings()
void G4DiffractiveExcitation::CreateStrings (G4VSplitableHadron * aHadron, G4bool isProjectile, G4ExcitedString *& FirstString, G4ExcitedString *& SecondString, G4FTFParameters * theParameters) const virtual
Definition at line 984 of file G4DiffractiveExcitation.cc.
Referenced by G4FTFModel::BuildStrings().
ExciteParticipants()
G4bool G4DiffractiveExcitation::ExciteParticipants (G4VSplitableHadron * aPartner, G4VSplitableHadron * bPartner, G4FTFParameters * theParameters, G4ElasticHNScattering * theElastic) const virtual
Definition at line 91 of file G4DiffractiveExcitation.cc.
Referenced by G4FTFModel::ExciteParticipants().
ExciteParticipants_doChargeExchange()
G4int G4DiffractiveExcitation::ExciteParticipants_doChargeExchange (G4VSplitableHadron * projectile, G4VSplitableHadron * target, G4FTFParameters * theParameters, G4ElasticHNScattering * theElastic, G4DiffractiveExcitation::CommonVariables & common) const private
Definition at line 321 of file G4DiffractiveExcitation.cc.
Referenced by ExciteParticipants().
ExciteParticipants_doDiffraction()
G4bool G4DiffractiveExcitation::ExciteParticipants_doDiffraction (G4VSplitableHadron * projectile, G4VSplitableHadron * target, G4FTFParameters * theParameters, G4DiffractiveExcitation::CommonVariables & common) const private
Definition at line 790 of file G4DiffractiveExcitation.cc.
Referenced by ExciteParticipants().
ExciteParticipants_doNonDiffraction()
G4bool G4DiffractiveExcitation::ExciteParticipants_doNonDiffraction (G4VSplitableHadron * projectile, G4VSplitableHadron * target, G4FTFParameters * theParameters, G4DiffractiveExcitation::CommonVariables & common) const private
Definition at line 898 of file G4DiffractiveExcitation.cc.
Referenced by ExciteParticipants().
GaussianPt()
G4ThreeVector G4DiffractiveExcitation::GaussianPt (G4double AveragePt2, G4double maxPtSquare) const private
Definition at line 1336 of file G4DiffractiveExcitation.cc.
Referenced by ExciteParticipants_doDiffraction(), and ExciteParticipants_doNonDiffraction().
GetQuarkFractionOfKink()
G4double G4DiffractiveExcitation::GetQuarkFractionOfKink (G4double zmin, G4double zmax) const private
Definition at line 1353 of file G4DiffractiveExcitation.cc.
Referenced by CreateStrings().
LambdaF()
G4double G4DiffractiveExcitation::LambdaF (G4double sqrM, G4double sqrM1, G4double sqrM2) const private
NewNucleonId()
G4int G4DiffractiveExcitation::NewNucleonId (G4int Q1, G4int Q2, G4int Q3) const private
Definition at line 1403 of file G4DiffractiveExcitation.cc.
Referenced by ExciteParticipants_doChargeExchange().
operator!=()
G4bool G4DiffractiveExcitation::operator!= (const G4DiffractiveExcitation & right) const private
Definition at line 1451 of file G4DiffractiveExcitation.cc.
operator=()
const G4DiffractiveExcitation & G4DiffractiveExcitation::operator= (const G4DiffractiveExcitation & right) private
Definition at line 1434 of file G4DiffractiveExcitation.cc.
operator==()
G4bool G4DiffractiveExcitation::operator== (const G4DiffractiveExcitation & right) const private
Definition at line 1443 of file G4DiffractiveExcitation.cc.
UnpackBaryon()
void G4DiffractiveExcitation::UnpackBaryon (G4int IdPDG, G4int & Q1, G4int & Q2, G4int & Q3) const private
Definition at line 1392 of file G4DiffractiveExcitation.cc.
Referenced by ExciteParticipants_doChargeExchange().
UnpackMeson()
void G4DiffractiveExcitation::UnpackMeson (G4int IdPDG, G4int & Q1, G4int & Q2) const private
Definition at line 1371 of file G4DiffractiveExcitation.cc.
Referenced by ExciteParticipants_doChargeExchange().
The documentation for this class was generated from the following files:
source/processes/hadronic/models/parton_string/diffraction/include/G4DiffractiveExcitation.hh
source/processes/hadronic/models/parton_string/diffraction/src/G4DiffractiveExcitation.cc