Geant4: G4CrossSectionFactoryRegistry Class Reference
G4CrossSectionFactoryRegistry Class Reference
#include <G4CrossSectionFactoryRegistry.hh>
Public Member Functions
G4VBaseXSFactory * GetFactory (const G4String &name, G4bool abortIfNotFound=true) const
void Register (const G4String &name, G4VBaseXSFactory *factory)
Static Public Member Functions
static G4CrossSectionFactoryRegistry * Instance ()
Private Member Functions
G4CrossSectionFactoryRegistry ()
G4CrossSectionFactoryRegistry (const G4CrossSectionFactoryRegistry &)
G4CrossSectionFactoryRegistry & operator= (const G4CrossSectionFactoryRegistry &)
Private Attributes
std::map< G4String, G4VBaseXSFactory * > factories
Static Private Attributes
static G4CrossSectionFactoryRegistry * instance = 0
Friends
std::ostream & operator<< (std::ostream &, const G4CrossSectionFactoryRegistry &)
Detailed Description
Definition at line 48 of file G4CrossSectionFactoryRegistry.hh.
Constructor & Destructor Documentation
G4CrossSectionFactoryRegistry() [1/2]
G4CrossSectionFactoryRegistry::G4CrossSectionFactoryRegistry () private
Definition at line 47 of file G4CrossSectionFactoryRegistry.cc.
Referenced by Instance().
G4CrossSectionFactoryRegistry() [2/2]
G4CrossSectionFactoryRegistry::G4CrossSectionFactoryRegistry (const G4CrossSectionFactoryRegistry &) private
Definition at line 52 of file G4CrossSectionFactoryRegistry.cc.
Member Function Documentation
GetFactory()
G4VBaseXSFactory * G4CrossSectionFactoryRegistry::GetFactory (const G4String & name, G4bool abortIfNotFound = true) const
Definition at line 78 of file G4CrossSectionFactoryRegistry.cc.
Referenced by G4CrossSectionDataSetRegistry::GetCrossSectionDataSet().
Instance()
G4CrossSectionFactoryRegistry * G4CrossSectionFactoryRegistry::Instance (void) static
Definition at line 39 of file G4CrossSectionFactoryRegistry.cc.
Referenced by G4CrossSectionFactory< T, mode >::G4CrossSectionFactory(), G4CrossSectionFactory< T, 0 >::G4CrossSectionFactory(), G4CrossSectionFactory< T, 1 >::G4CrossSectionFactory(), G4CrossSectionFactory< T, 2 >::G4CrossSectionFactory(), and G4CrossSectionDataSetRegistry::GetCrossSectionDataSet().
operator=()
G4CrossSectionFactoryRegistry & G4CrossSectionFactoryRegistry::operator= (const G4CrossSectionFactoryRegistry &) private
Definition at line 57 of file G4CrossSectionFactoryRegistry.cc.
Register()
void G4CrossSectionFactoryRegistry::Register (const G4String & name, G4VBaseXSFactory * factory)
Definition at line 64 of file G4CrossSectionFactoryRegistry.cc.
Referenced by G4CrossSectionFactory< T, mode >::G4CrossSectionFactory(), G4CrossSectionFactory< T, 0 >::G4CrossSectionFactory(), G4CrossSectionFactory< T, 1 >::G4CrossSectionFactory(), and G4CrossSectionFactory< T, 2 >::G4CrossSectionFactory().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & msg, const G4CrossSectionFactoryRegistry & rhs) friend
Definition at line 98 of file G4CrossSectionFactoryRegistry.cc.
Field Documentation
factories
std::map<G4String, G4VBaseXSFactory*> G4CrossSectionFactoryRegistry::factories private
Definition at line 52 of file G4CrossSectionFactoryRegistry.hh.
Referenced by GetFactory(), and Register().
instance
G4CrossSectionFactoryRegistry * G4CrossSectionFactoryRegistry::instance = 0 static private
Definition at line 53 of file G4CrossSectionFactoryRegistry.hh.
Referenced by G4CrossSectionFactoryRegistry(), and Instance().
The documentation for this class was generated from the following files:
source/processes/hadronic/cross_sections/include/G4CrossSectionFactoryRegistry.hh
source/processes/hadronic/cross_sections/src/G4CrossSectionFactoryRegistry.cc