Geant4: SimpleTbbMasterRunManager Class Reference
SimpleTbbMasterRunManager Class Reference
#include <SimpleTbbMasterRunManager.hh>
Public Member Functions
SimpleTbbMasterRunManager ()
virtual ~SimpleTbbMasterRunManager ()
virtual void RunTermination ()
void SetTaskList (tbb::task_list *tl)
void SetNumberEventsPerTask (G4int nt)
Public Member Functions inherited from G4MTRunManager
G4MTRunManager ()
virtual ~G4MTRunManager ()
void SetNumberOfThreads (G4int n)
G4int GetNumberOfThreads () const
void SetPinAffinity (G4int n=1)
G4int GetPinAffinity () const
virtual void Initialize ()
virtual void InitializeEventLoop (G4int n_event, const char *macroFile=0, G4int n_select=-1)
virtual void TerminateOneEvent ()
virtual void ProcessOneEvent (G4int i_event)
virtual void ConstructScoringWorlds ()
virtual G4bool SetUpAnEvent (G4Event *, long &s1, long &s2, long &s3, G4bool reseedRequired=true)
virtual G4int SetUpNEvents (G4Event *, G4SeedsQueue *seedsQueue, G4bool reseedRequired=true)
std::vector< G4String > GetCommandStack ()
size_t GetNumberActiveThreads () const
const CLHEP::HepRandomEngine * getMasterRandomEngine () const
virtual void SetUserInitialization (G4VUserPhysicsList *userPL)
virtual void SetUserInitialization (G4VUserDetectorConstruction *userDC)
virtual void SetUserInitialization (G4UserWorkerInitialization *userInit)
virtual void SetUserInitialization (G4UserWorkerThreadInitialization *userInit)
virtual void SetUserInitialization (G4VUserActionInitialization *userInit)
virtual void SetUserAction (G4UserRunAction *userAction)
virtual void SetUserAction (G4VUserPrimaryGeneratorAction *userAction)
virtual void SetUserAction (G4UserEventAction *userAction)
virtual void SetUserAction (G4UserStackingAction *userAction)
virtual void SetUserAction (G4UserTrackingAction *userAction)
virtual void SetUserAction (G4UserSteppingAction *userAction)
void MergeScores (const G4ScoringManager *localScoringManager)
void MergeRun (const G4Run *localRun)
virtual void RequestWorkersProcessCommandsStack ()
virtual void ThisWorkerProcessCommandsStackDone ()
void SetEventModulo (G4int i=1)
G4int GetEventModulo () const
virtual void AbortRun (G4bool softAbort=false)
virtual void AbortEvent ()
Public Member Functions inherited from G4RunManager
G4RunManager ()
virtual ~G4RunManager ()
virtual void BeamOn (G4int n_event, const char *macroFile=0, G4int n_select=-1)
virtual void DefineWorldVolume (G4VPhysicalVolume *worldVol, G4bool topologyIsChanged=true)
virtual void InitializeGeometry ()
virtual void InitializePhysics ()
virtual G4bool ConfirmBeamOnCondition ()
virtual void RunInitialization ()
virtual void DoEventLoop (G4int n_event, const char *macroFile=0, G4int n_select=-1)
virtual void TerminateEventLoop ()
virtual G4Event * GenerateEvent (G4int i_event)
virtual void AnalyzeEvent (G4Event *anEvent)
void DumpRegion (const G4String &rname) const
void DumpRegion (G4Region *region=0) const
virtual void rndmSaveThisRun ()
virtual void rndmSaveThisEvent ()
virtual void RestoreRandomNumberStatus (const G4String &fileN)
const G4VUserDetectorConstruction * GetUserDetectorConstruction () const
const G4VUserPhysicsList * GetUserPhysicsList () const
const G4VUserActionInitialization * GetUserActionInitialization () const
G4VUserActionInitialization * GetNonConstUserActionInitialization () const
const G4UserWorkerInitialization * GetUserWorkerInitialization () const
const G4UserWorkerThreadInitialization * GetUserWorkerThreadInitialization () const
const G4UserRunAction * GetUserRunAction () const
const G4VUserPrimaryGeneratorAction * GetUserPrimaryGeneratorAction () const
const G4UserEventAction * GetUserEventAction () const
const G4UserStackingAction * GetUserStackingAction () const
const G4UserTrackingAction * GetUserTrackingAction () const
const G4UserSteppingAction * GetUserSteppingAction () const
void SetNumberOfAdditionalWaitingStacks (G4int iAdd)
const G4String & GetVersionString () const
void SetPrimaryTransformer (G4PrimaryTransformer *pt)
void StoreRandomNumberStatusToG4Event (G4int vl)
G4int GetFlagRandomNumberStatusToG4Event () const
void SetRandomNumberStore (G4bool flag)
G4bool GetRandomNumberStore () const
void SetRandomNumberStoreDir (const G4String &dir)
const G4String & GetRandomNumberStoreDir () const
const G4String & GetRandomNumberStatusForThisRun () const
const G4String & GetRandomNumberStatusForThisEvent () const
void SetRandomNumberStorePerEvent (G4bool flag)
G4bool GetRandomNumberStorePerEvent () const
void GeometryHasBeenModified (G4bool prop=true)
void ReinitializeGeometry (G4bool destroyFirst=false, G4bool prop=true)
void PhysicsHasBeenModified ()
void CutOffHasBeenModified ()
void ReOptimizeMotherOf (G4VPhysicalVolume *)
void ReOptimize (G4LogicalVolume *)
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
G4int GetPrintProgress ()
void SetPrintProgress (G4int i)
void SetGeometryToBeOptimized (G4bool vl)
G4bool GetGeometryToBeOptimized ()
void SetNumberOfEventsToBeStored (G4int val)
const G4Run * GetCurrentRun () const
G4Run * GetNonConstCurrentRun () const
const G4Event * GetCurrentEvent () const
const G4Event * GetPreviousEvent (G4int i) const
void SetRunIDCounter (G4int i)
G4int GetNumberOfParallelWorld () const
void SetNumberOfEventsToBeProcessed (G4int val)
G4int GetNumberOfEventsToBeProcessed () const
G4int GetNumberOfSelectEvents () const
G4String GetSelectMacro () const
void SetDCtable (G4DCtable *DCtbl)
RMType GetRunManagerType () const
virtual void RestoreRndmEachEvent (G4bool)
Protected Member Functions
virtual void CreateAndStartWorkers ()
virtual void TerminateWorkers ()
virtual void CreateTask (G4int id, G4int evts)
virtual void WaitForReadyWorkers ()
virtual void WaitForEndEventLoopWorkers ()
virtual void ThisWorkerReady ()
virtual void ThisWorkerEndEventLoop ()
virtual WorkerActionRequest ThisWorkerWaitForNextAction ()
virtual void NewActionRequest (WorkerActionRequest)
Protected Member Functions inherited from G4MTRunManager
virtual G4bool InitializeSeeds (G4int)
virtual void PrepareCommandsStack ()
virtual void StoreRNGStatus (const G4String &filenamePrefix)
void RefillSeeds ()
Protected Member Functions inherited from G4RunManager
void CleanUpPreviousEvents ()
void CleanUpUnnecessaryEvents (G4int keepNEvents)
void StackPreviousEvent (G4Event *anEvent)
G4RunManager (RMType rmType)
void UpdateScoring ()
virtual void DeleteUserInitializations ()
Private Attributes
tbb::task_list * theTasks
G4int nEvtsPerTask
Additional Inherited Members
Public Types inherited from G4MTRunManager
enum WorkerActionRequest { WorkerActionRequest::UNDEFINED, WorkerActionRequest::NEXTITERATION, WorkerActionRequest::PROCESSUI, WorkerActionRequest::ENDWORKER }
typedef std::map< G4int, G4VPhysicalVolume * > masterWorlds_t
Public Types inherited from G4RunManager
enum RMType { sequentialRM, masterRM, workerRM }
Static Public Member Functions inherited from G4MTRunManager
static G4ScoringManager * GetMasterScoringManager ()
static masterWorlds_t & GetMasterWorlds ()
static void addWorld (G4int counter, G4VPhysicalVolume *w)
static G4MTRunManager * GetMasterRunManager ()
static G4RunManagerKernel * GetMasterRunManagerKernel ()
static G4MTRunManagerKernel * GetMTMasterRunManagerKernel ()
static G4int SeedOncePerCommunication ()
static void SetSeedOncePerCommunication (G4int val)
Static Public Member Functions inherited from G4RunManager
static G4RunManager * GetRunManager ()
static G4bool IfGeometryHasBeenDestroyed ()
Protected Attributes inherited from G4MTRunManager
G4int numberOfEventToBeProcessed
WorkerActionRequest nextActionRequest
G4int eventModuloDef
G4int eventModulo
G4int nSeedsUsed
G4int nSeedsFilled
G4int nSeedsMax
G4int nSeedsPerEvent
double * randDbl
G4MTBarrier beginOfEventLoopBarrier
G4MTBarrier endOfEventLoopBarrier
G4MTBarrier nextActionRequestBarrier
G4MTBarrier processUIBarrier
Protected Attributes inherited from G4RunManager
G4RunManagerKernel * kernel
G4EventManager * eventManager
G4VUserDetectorConstruction * userDetector
G4VUserPhysicsList * physicsList
G4VUserActionInitialization * userActionInitialization
G4UserWorkerInitialization * userWorkerInitialization
G4UserWorkerThreadInitialization * userWorkerThreadInitialization
G4UserRunAction * userRunAction
G4VUserPrimaryGeneratorAction * userPrimaryGeneratorAction
G4UserEventAction * userEventAction
G4UserStackingAction * userStackingAction
G4UserTrackingAction * userTrackingAction
G4UserSteppingAction * userSteppingAction
G4bool geometryInitialized
G4bool physicsInitialized
G4bool runAborted
G4bool initializedAtLeastOnce
G4bool geometryToBeOptimized
G4int runIDCounter
G4int verboseLevel
G4int printModulo
G4Timer * timer
G4DCtable * DCtable
G4Run * currentRun
G4Event * currentEvent
std::list< G4Event * > * previousEvents
G4int n_perviousEventsToBeStored
G4int numberOfEventToBeProcessed
G4bool storeRandomNumberStatus
G4int storeRandomNumberStatusToG4Event
G4String randomNumberStatusDir
G4String randomNumberStatusForThisRun
G4String randomNumberStatusForThisEvent
G4bool rngStatusEventsFlag
G4VPhysicalVolume * currentWorld
G4int nParallelWorlds
G4String msgText
G4int n_select_msg
G4int numberOfEventProcessed
G4String selectMacro
G4bool fakeRun
G4bool isScoreNtupleWriter
RMType runManagerType
Static Protected Attributes inherited from G4MTRunManager
static G4int seedOncePerCommunication = 0
Static Protected Attributes inherited from G4RunManager
static G4bool fGeometryHasBeenDestroyed = false
Detailed Description
Definition at line 48 of file SimpleTbbMasterRunManager.hh.
Constructor & Destructor Documentation
SimpleTbbMasterRunManager()
SimpleTbbMasterRunManager::SimpleTbbMasterRunManager ()
Definition at line 45 of file SimpleTbbMasterRunManager.cc.
~SimpleTbbMasterRunManager()
SimpleTbbMasterRunManager::~SimpleTbbMasterRunManager () virtual
Definition at line 52 of file SimpleTbbMasterRunManager.cc.
Member Function Documentation
CreateAndStartWorkers()
void SimpleTbbMasterRunManager::CreateAndStartWorkers () protected virtual
Reimplemented from G4MTRunManager.
Definition at line 61 of file SimpleTbbMasterRunManager.cc.
CreateTask()
void SimpleTbbMasterRunManager::CreateTask (G4int id, G4int evts) protected virtual
Definition at line 74 of file SimpleTbbMasterRunManager.cc.
Referenced by CreateAndStartWorkers().
NewActionRequest()
virtual void SimpleTbbMasterRunManager::NewActionRequest (WorkerActionRequest) inline protected virtual
Reimplemented from G4MTRunManager.
Definition at line 77 of file SimpleTbbMasterRunManager.hh.
RunTermination()
void SimpleTbbMasterRunManager::RunTermination () virtual
Reimplemented from G4MTRunManager.
Definition at line 81 of file SimpleTbbMasterRunManager.cc.
SetNumberEventsPerTask()
void SimpleTbbMasterRunManager::SetNumberEventsPerTask (G4int nt) inline
Definition at line 60 of file SimpleTbbMasterRunManager.hh.
Referenced by main().
SetTaskList()
void SimpleTbbMasterRunManager::SetTaskList (tbb::task_list * tl) inline
Definition at line 57 of file SimpleTbbMasterRunManager.hh.
Referenced by main().
TerminateWorkers()
void SimpleTbbMasterRunManager::TerminateWorkers () protected virtual
Reimplemented from G4MTRunManager.
Definition at line 56 of file SimpleTbbMasterRunManager.cc.
ThisWorkerEndEventLoop()
virtual void SimpleTbbMasterRunManager::ThisWorkerEndEventLoop () inline protected virtual
Reimplemented from G4MTRunManager.
Definition at line 74 of file SimpleTbbMasterRunManager.hh.
ThisWorkerReady()
virtual void SimpleTbbMasterRunManager::ThisWorkerReady () inline protected virtual
Reimplemented from G4MTRunManager.
Definition at line 73 of file SimpleTbbMasterRunManager.hh.
ThisWorkerWaitForNextAction()
virtual WorkerActionRequest SimpleTbbMasterRunManager::ThisWorkerWaitForNextAction () inline protected virtual
Reimplemented from G4MTRunManager.
Definition at line 75 of file SimpleTbbMasterRunManager.hh.
WaitForEndEventLoopWorkers()
virtual void SimpleTbbMasterRunManager::WaitForEndEventLoopWorkers () inline protected virtual
Reimplemented from G4MTRunManager.
Definition at line 72 of file SimpleTbbMasterRunManager.hh.
WaitForReadyWorkers()
virtual void SimpleTbbMasterRunManager::WaitForReadyWorkers () inline protected virtual
Reimplemented from G4MTRunManager.
Definition at line 71 of file SimpleTbbMasterRunManager.hh.
Field Documentation
nEvtsPerTask
G4int SimpleTbbMasterRunManager::nEvtsPerTask private
Definition at line 80 of file SimpleTbbMasterRunManager.hh.
Referenced by CreateAndStartWorkers(), and SetNumberEventsPerTask().
theTasks
tbb::task_list* SimpleTbbMasterRunManager::theTasks private
Definition at line 79 of file SimpleTbbMasterRunManager.hh.
Referenced by CreateTask(), and SetTaskList().
The documentation for this class was generated from the following files:
examples/extended/parallel/TBB/B2b/include/SimpleTbbMasterRunManager.hh
examples/extended/parallel/TBB/B2b/src/SimpleTbbMasterRunManager.cc