Geant4: CCalAMaterial Class Reference
CCalAMaterial Class Reference
#include <CCalAMaterial.hh>
Public Member Functions
CCalAMaterial (G4String mat, double dens, int nelem, CCalAMaterial **constituents, double *weights)
CCalAMaterial (G4String elemat, double Aeff, double dens)
CCalAMaterial (const CCalAMaterial &)
virtual ~CCalAMaterial ()
G4double Aeff () const
CCalAMaterial & operator= (const CCalAMaterial &)
Public Member Functions inherited from CCalMaterial
CCalMaterial (G4String mat, double dens, int nelem, CCalMaterial **constituents, double *weights, FractionType=FTWeight)
CCalMaterial (const CCalMaterial &)
virtual ~CCalMaterial ()
G4String Name () const
double Density () const
int NElements () const
G4String Element (int i) const
double Weight (int i) const
G4bool operator== (const CCalMaterial &) const
G4bool operator!= (const CCalMaterial &) const
CCalMaterial & operator= (const CCalMaterial &)
Protected Member Functions
void computeAeff (G4int nconst, CCalAMaterial **constituents, double *weights)
Protected Member Functions inherited from CCalMaterial
CCalMaterial ()
void computeDensity (int nconst, CCalMaterial **constituents, double *weights, FractionType ft)
void closeMaterial ()
Protected Attributes
double aEff
Protected Attributes inherited from CCalMaterial
G4String name
double density
int nElem
G4String * theElements
double * theWeights
Friends
std::ostream & operator<< (std::ostream &, const CCalAMaterial &)
Additional Inherited Members
Public Types inherited from CCalMaterial
enum FractionType { FTWeight, FTVolume }
Detailed Description
Definition at line 38 of file CCalAMaterial.hh.
Constructor & Destructor Documentation
CCalAMaterial() [1/3]
CCalAMaterial::CCalAMaterial (G4String mat, double dens, int nelem, CCalAMaterial ** constituents, double * weights)
Definition at line 33 of file CCalAMaterial.cc.
CCalAMaterial() [2/3]
CCalAMaterial::CCalAMaterial (G4String elemat, double Aeff, double dens)
Definition at line 64 of file CCalAMaterial.cc.
CCalAMaterial() [3/3]
CCalAMaterial::CCalAMaterial (const CCalAMaterial & mat)
Definition at line 81 of file CCalAMaterial.cc.
~CCalAMaterial()
CCalAMaterial::~CCalAMaterial () virtual
Definition at line 77 of file CCalAMaterial.cc.
Member Function Documentation
Aeff()
G4double CCalAMaterial::Aeff () const inline
Definition at line 51 of file CCalAMaterial.hh.
Referenced by CCalAMaterial(), and computeAeff().
computeAeff()
void CCalAMaterial::computeAeff (G4int nconst, CCalAMaterial ** constituents, double * weights) protected
Definition at line 114 of file CCalAMaterial.cc.
Referenced by CCalAMaterial().
operator=()
CCalAMaterial & CCalAMaterial::operator= (const CCalAMaterial & mat)
Definition at line 94 of file CCalAMaterial.cc.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CCalAMaterial & mat) friend
Definition at line 122 of file CCalAMaterial.cc.
Field Documentation
aEff
double CCalAMaterial::aEff protected
Definition at line 59 of file CCalAMaterial.hh.
Referenced by Aeff(), CCalAMaterial(), computeAeff(), operator<<(), and operator=().
The documentation for this class was generated from the following files:
examples/advanced/composite_calorimeter/include/CCalAMaterial.hh
examples/advanced/composite_calorimeter/src/CCalAMaterial.cc