Geant4: CexmcPrimitiveScorer Class Reference
CexmcPrimitiveScorer Class Reference
#include <CexmcPrimitiveScorer.hh>
Public Member Functions
CexmcPrimitiveScorer (const G4String &name)
virtual ~CexmcPrimitiveScorer ()
void InitializeMessenger (void)
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Protected Member Functions
void PrintHeader (G4int nmbOfEntries) const
Protected Member Functions inherited from G4VPrimitiveScorer
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)=0
virtual G4int GetIndex (G4Step *)
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Private Attributes
CexmcSensitiveDetectorMessenger * messenger
Additional Inherited Members
Protected Attributes inherited from G4VPrimitiveScorer
G4String primitiveName
G4MultiFunctionalDetector * detector
G4VSDFilter * filter
G4int verboseLevel
G4int indexDepth
G4String unitName
G4double unitValue
G4int fNi
G4int fNj
G4int fNk
Detailed Description
Definition at line 52 of file CexmcPrimitiveScorer.hh.
Constructor & Destructor Documentation
CexmcPrimitiveScorer()
CexmcPrimitiveScorer::CexmcPrimitiveScorer (const G4String & name) explicit
Definition at line 49 of file CexmcPrimitiveScorer.cc.
~CexmcPrimitiveScorer()
CexmcPrimitiveScorer::~CexmcPrimitiveScorer () virtual
Definition at line 55 of file CexmcPrimitiveScorer.cc.
Member Function Documentation
InitializeMessenger()
void CexmcPrimitiveScorer::InitializeMessenger (void)
Definition at line 61 of file CexmcPrimitiveScorer.cc.
Referenced by CexmcSetup::SetupSpecialVolumes().
PrintHeader()
void CexmcPrimitiveScorer::PrintHeader (G4int nmbOfEntries) const protected
Definition at line 67 of file CexmcPrimitiveScorer.cc.
Referenced by CexmcEnergyDepositInCalorimeter::PrintAll(), CexmcTrackPointsInCalorimeter::PrintAll(), CexmcEnergyDepositInLeftRightSet::PrintAll(), CexmcTrackPointsInLeftRightSet::PrintAll(), CexmcSimpleEnergyDeposit::PrintAll(), and CexmcTrackPoints::PrintAll().
Field Documentation
messenger
CexmcSensitiveDetectorMessenger* CexmcPrimitiveScorer::messenger private
Definition at line 66 of file CexmcPrimitiveScorer.hh.
Referenced by InitializeMessenger(), and ~CexmcPrimitiveScorer().
The documentation for this class was generated from the following files:
examples/advanced/ChargeExchangeMC/include/CexmcPrimitiveScorer.hh
examples/advanced/ChargeExchangeMC/src/CexmcPrimitiveScorer.cc