Geant4: ExN02MagneticField Class Reference
ExN02MagneticField Class Reference
#include <ExN02MagneticField.hh>
Public Member Functions
ExN02MagneticField (G4ThreeVector)
ExN02MagneticField ()
~ExN02MagneticField ()
void SetMagFieldValue (G4double fieldValue)
void SetMagFieldValue (G4ThreeVector fieldVector)
G4ThreeVector GetConstantFieldValue ()
Public Member Functions inherited from G4UniformMagField
G4UniformMagField (const G4ThreeVector &FieldVector)
G4UniformMagField (G4double vField, G4double vTheta, G4double vPhi)
virtual ~G4UniformMagField () override
G4UniformMagField (const G4UniformMagField &p)
G4UniformMagField & operator= (const G4UniformMagField &p)
virtual void GetFieldValue (const G4double yTrack[4], G4double *MagField) const override final
void SetFieldValue (const G4ThreeVector &newFieldValue)
G4ThreeVector GetConstantFieldValue () const
virtual G4Field * Clone () const override
Public Member Functions inherited from G4MagneticField
G4MagneticField ()
virtual ~G4MagneticField ()
G4MagneticField (const G4MagneticField &r)
G4MagneticField & operator= (const G4MagneticField &p)
G4bool DoesFieldChangeEnergy () const
Public Member Functions inherited from G4Field
G4Field (G4bool gravityOn=false)
G4Field (const G4Field &)
virtual ~G4Field ()
G4Field & operator= (const G4Field &p)
G4bool IsGravityActive () const
void SetGravityActive (G4bool OnOffFlag)
Protected Member Functions
G4FieldManager * GetGlobalFieldManager ()
Additional Inherited Members
Static Public Attributes inherited from G4Field
static constexpr G4int MAX_NUMBER_OF_COMPONENTS = 24
Detailed Description
Definition at line 48 of file ExN02MagneticField.hh.
Constructor & Destructor Documentation
ExN02MagneticField() [1/2]
ExN02MagneticField::ExN02MagneticField (G4ThreeVector fieldVector)
Definition at line 51 of file ExN02MagneticField.cc.
ExN02MagneticField() [2/2]
ExN02MagneticField::ExN02MagneticField ()
Definition at line 42 of file ExN02MagneticField.cc.
~ExN02MagneticField()
ExN02MagneticField::~ExN02MagneticField ()
Definition at line 60 of file ExN02MagneticField.cc.
Member Function Documentation
GetConstantFieldValue()
G4ThreeVector ExN02MagneticField::GetConstantFieldValue ()
GetGlobalFieldManager()
G4FieldManager * ExN02MagneticField::GetGlobalFieldManager () protected
Definition at line 96 of file ExN02MagneticField.cc.
Referenced by ExN02MagneticField(), and SetMagFieldValue().
SetMagFieldValue() [1/2]
void ExN02MagneticField::SetMagFieldValue (G4double fieldValue)
Definition at line 68 of file ExN02MagneticField.cc.
Referenced by ExN02DetectorConstruction::SetMagField().
SetMagFieldValue() [2/2]
void ExN02MagneticField::SetMagFieldValue (G4ThreeVector fieldVector)
Definition at line 77 of file ExN02MagneticField.cc.
The documentation for this class was generated from the following files:
examples/extended/parallel/TopC/ParN02/include/ExN02MagneticField.hh
examples/extended/parallel/TopC/ParN02/src/ExN02MagneticField.cc