Geant4: G4ProcessManager Class Reference
G4ProcessManager Class Reference
#include <G4ProcessManager.hh>
Public Types
enum { SizeOfProcVectorArray = 6 }
Public Member Functions
G4ProcessManager (G4ProcessManager &right)
G4ProcessManager (const G4ParticleDefinition *aParticleType)
~G4ProcessManager ()
G4bool operator== (const G4ProcessManager &right) const
G4bool operator!= (const G4ProcessManager &right) const
G4ProcessVector * GetProcessList () const
G4int GetProcessListLength () const
G4int GetProcessIndex (G4VProcess *) const
G4ProcessVector * GetProcessVector (G4ProcessVectorDoItIndex idx, G4ProcessVectorTypeIndex typ=typeGPIL) const
G4ProcessVector * GetAtRestProcessVector (G4ProcessVectorTypeIndex typ=typeGPIL) const
G4ProcessVector * GetAlongStepProcessVector (G4ProcessVectorTypeIndex typ=typeGPIL) const
G4ProcessVector * GetPostStepProcessVector (G4ProcessVectorTypeIndex typ=typeGPIL) const
G4int GetProcessVectorIndex (G4VProcess *aProcess, G4ProcessVectorDoItIndex idx, G4ProcessVectorTypeIndex typ=typeGPIL) const
G4int GetAtRestIndex (G4VProcess *aProcess, G4ProcessVectorTypeIndex typ=typeGPIL) const
G4int GetAlongStepIndex (G4VProcess *aProcess, G4ProcessVectorTypeIndex typ=typeGPIL) const
G4int GetPostStepIndex (G4VProcess *aProcess, G4ProcessVectorTypeIndex typ=typeGPIL) const
G4int AddProcess (G4VProcess *aProcess, G4int ordAtRestDoIt=ordInActive, G4int ordAlongSteptDoIt=ordInActive, G4int ordPostStepDoIt=ordInActive)
G4int AddRestProcess (G4VProcess *aProcess, G4int ord=ordDefault)
G4int AddDiscreteProcess (G4VProcess *aProcess, G4int ord=ordDefault)
G4int AddContinuousProcess (G4VProcess *aProcess, G4int ord=ordDefault)
G4int GetProcessOrdering (G4VProcess *aProcess, G4ProcessVectorDoItIndex idDoIt)
void SetProcessOrdering (G4VProcess *aProcess, G4ProcessVectorDoItIndex idDoIt, G4int ordDoIt=ordDefault)
void SetProcessOrderingToFirst (G4VProcess *aProcess, G4ProcessVectorDoItIndex idDoIt)
void SetProcessOrderingToSecond (G4VProcess *aProcess, G4ProcessVectorDoItIndex idDoIt)
void SetProcessOrderingToLast (G4VProcess *aProcess, G4ProcessVectorDoItIndex idDoIt)
G4VProcess * RemoveProcess (G4VProcess *aProcess)
G4VProcess * RemoveProcess (G4int index)
G4VProcess * SetProcessActivation (G4VProcess *aProcess, G4bool fActive)
G4VProcess * SetProcessActivation (G4int index, G4bool fActive)
G4bool GetProcessActivation (G4VProcess *aProcess) const
G4bool GetProcessActivation (G4int index) const
G4ParticleDefinition * GetParticleType () const
void SetParticleType (const G4ParticleDefinition *)
G4VProcess * GetProcess (const G4String &) const
void StartTracking (G4Track *aTrack=0)
void EndTracking ()
void DumpInfo ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
Protected Member Functions
G4int InsertAt (G4int position, G4VProcess *process, G4int ivec)
G4int RemoveAt (G4int position, G4VProcess *process, G4int ivec)
G4int FindInsertPosition (G4int ord, G4int ivec)
G4int GetProcessVectorId (G4ProcessVectorDoItIndex idx, G4ProcessVectorTypeIndex typ=typeGPIL) const
void CheckOrderingParameters (G4VProcess *) const
Protected Attributes
G4int verboseLevel
Private Types
typedef std::vector< G4ProcessAttribute * > G4ProcessAttrVector
Private Member Functions
G4ProcessManager & operator= (const G4ProcessManager &right)
G4ProcessManager ()
G4ProcessAttribute * GetAttribute (G4int index) const
G4ProcessAttribute * GetAttribute (G4VProcess *aProcess) const
G4VProcess * ActivateProcess (G4int index)
G4VProcess * InActivateProcess (G4int index)
void CreateGPILvectors ()
void SetIndexToProcessVector (G4int ivec)
Private Attributes
G4ProcessVector * theProcVector [SizeOfProcVectorArray]
G4ProcessAttrVector * theAttrVector
const G4ParticleDefinition * theParticleType
G4int numberOfProcesses
G4ProcessVector * theProcessList
G4bool duringTracking
G4bool isSetOrderingFirstInvoked [NDoit]
G4bool isSetOrderingLastInvoked [NDoit]
Static Private Attributes
static G4ThreadLocal G4ProcessManagerMessenger * fProcessManagerMessenger = 0
static G4ThreadLocal G4int counterOfObjects = 0
Detailed Description
Definition at line 105 of file G4ProcessManager.hh.
Member Typedef Documentation
G4ProcessAttrVector
typedef std::vector<G4ProcessAttribute*> G4ProcessManager::G4ProcessAttrVector private
Definition at line 304 of file G4ProcessManager.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
SizeOfProcVectorArray
Definition at line 299 of file G4ProcessManager.hh.
Constructor & Destructor Documentation
G4ProcessManager() [1/3]
G4ProcessManager::G4ProcessManager (G4ProcessManager & right)
Definition at line 101 of file G4ProcessManager.cc.
G4ProcessManager() [2/3]
G4ProcessManager::G4ProcessManager () private
Definition at line 166 of file G4ProcessManager.cc.
G4ProcessManager() [3/3]
G4ProcessManager::G4ProcessManager (const G4ParticleDefinition * aParticleType)
Definition at line 59 of file G4ProcessManager.cc.
~G4ProcessManager()
G4ProcessManager::~G4ProcessManager ()
Definition at line 199 of file G4ProcessManager.cc.
Member Function Documentation
ActivateProcess()
G4VProcess * G4ProcessManager::ActivateProcess (G4int index) private
Definition at line 931 of file G4ProcessManager.cc.
Referenced by RemoveProcess(), and SetProcessActivation().
AddContinuousProcess()
G4int G4ProcessManager::AddContinuousProcess (G4VProcess * aProcess, G4int ord = ordDefault)
Referenced by G4ErrorPhysicsList::ConstructEM(), and export_G4ProcessManager().
AddDiscreteProcess()
G4int G4ProcessManager::AddDiscreteProcess (G4VProcess * aProcess, G4int ord = ordDefault)
Referenced by G4EmModelActivator::ActivateMicroElec(), G4IonPhysicsXS::AddProcess(), G4IonPhysics::AddProcess(), G4IonPhysicsPHP::AddProcess(), G4IonINCLXXPhysics::AddProcess(), G4IonQMDPhysics::AddProcess(), F04PhysicsList::AddStepMax(), HadrontherapyPhysicsList::AddStepMax(), XrayFluoPhysicsList::AddStepMax(), PhysicsList::AddStepMax(), WLSPhysicsList::AddStepMax(), ML2PhysicsList::AddStepMax(), ExN02PhysicsList::AddStepMax(), IORTPhysicsList::AddStepMax(), DMXPhysicsList::AddTransportation(), G4AlphaBuilder::Build(), G4He3Builder::Build(), G4TritonBuilder::Build(), G4PionBuilder::Build(), G4AntiBarionBuilder::Build(), G4DeuteronBuilder::Build(), G4BertiniElectroNuclearBuilder::Build(), G4PiKBuilder::Build(), G4ProtonBuilder::Build(), G4KaonBuilder::Build(), G4NeutronBuilder::Build(), G4HyperonFTFPBuilder::Build(), PhysicsList::ConstructEM(), B03PhysicsList::ConstructEM(), ExN02PhysicsList::ConstructEM(), G4ErrorPhysicsList::ConstructEM(), OpNovicePhysicsList::ConstructEM(), DMXPhysicsList::ConstructEM(), XrayTelPhysicsList::ConstructEM(), G4AdjointPhysicsList::ConstructEM(), PurgMagPhysicsList::ConstructEM(), B03PhysicsList::ConstructHad(), DMXPhysicsList::ConstructHad(), PhysicsList::ConstructHighEnergy(), OpNovicePhysicsList::ConstructOp(), DMXPhysicsList::ConstructOp(), XPhysicsList::ConstructProcess(), G4ChannelingPhysics::ConstructProcess(), ExUCNExtraPhysics::ConstructProcess(), GammaNuclearPhysics::ConstructProcess(), G4EmDNAPhysicsActivator::ConstructProcess(), StepMaxBuilder::ConstructProcess(), WLSExtraPhysics::ConstructProcess(), NeutronHPphysics::ConstructProcess(), PhysListEmStandard::ConstructProcess(), PhysListEmStandardGS::ConstructProcess(), PhysListEmStandardSS::ConstructProcess(), StepLimiterBuilder::ConstructProcess(), PhysListEmStandardSSM::ConstructProcess(), MuNuclearBuilder::ConstructProcess(), G4EmLEPTSPhysics::ConstructProcess(), PhysListEmStandardWVI::ConstructProcess(), PhysListEmPolarized::ConstructProcess(), PhysListEmStandard_GS::ConstructProcess(), PhysListEmStandard_WVI::ConstructProcess(), TransitionRadiationPhysics::ConstructProcess(), PhysListEmStandard_option0::ConstructProcess(), PhysListEmStandard_option3::ConstructProcess(), PhysListEmStandard_option4::ConstructProcess(), G4StepLimiterPhysics::ConstructProcess(), PhysListEmStandard_SS::ConstructProcess(), G4ChargeExchangePhysics::ConstructProcess(), WLSOpticalPhysics::ConstructProcess(), G4IonElasticPhysics::ConstructProcess(), G4HadronDElasticPhysics::ConstructProcess(), GammaRayTelEMstdPhysics::ConstructProcess(), GammaRayTelEMlowePhysics::ConstructProcess(), G4HadronHElasticPhysics::ConstructProcess(), GammaRayTelMuonPhysics::ConstructProcess(), CexmcStudiedPhysics< CexmcHadronicProcess >::ConstructProcess(), G4HadronElasticPhysics::ConstructProcess(), G4OpticalPhysics::ConstructProcess(), GammaRayTelIonPhysics::ConstructProcess(), G4HadronPhysicsFTFQGSP_BERT::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), ExUCNExtraPhysics::ConstructUCN(), export_G4ProcessManager(), G4VHadronPhysics::FindCaptureProcess(), G4VHadronPhysics::FindElasticProcess(), G4VHadronPhysics::FindFissionProcess(), G4VHadronPhysics::FindInelasticProcess(), G4EmModelActivator::FindOrAddProcess(), G4ErrorTrackLengthTarget::G4ErrorTrackLengthTarget(), and G4RunManagerKernel::SetScoreSplitter().
AddProcess()
G4int G4ProcessManager::AddProcess (G4VProcess * aProcess, G4int ordAtRestDoIt = ordInActive, G4int ordAlongSteptDoIt = ordInActive, G4int ordPostStepDoIt = ordInActive)
Definition at line 408 of file G4ProcessManager.cc.
Referenced by G4FastSimulationHelper::ActivateFastSimulation(), G4BiasingHelper::ActivateNonPhysicsBiasing(), G4BiasingHelper::ActivatePhysicsBiasing(), PhysicsList::AddDarkMatter(), XrayFluoPhysicsList::AddDecay(), G4BiasingHelper::AddLimiterProcess(), Par02PhysicsList::AddParameterisation(), G4ProcessPlacer::AddProcessAs(), B03PhysicsList::AddScoringProcess(), G4PhysicsListHelper::AddTransportation(), DMXPhysicsList::AddTransportation(), OpNovicePhysicsList::ConstructDecay(), eRositaPhysicsList::ConstructEM(), PhysicsList::ConstructEM(), B03PhysicsList::ConstructEM(), ExN02PhysicsList::ConstructEM(), OpNovicePhysicsList::ConstructEM(), DMXPhysicsList::ConstructEM(), XrayTelPhysicsList::ConstructEM(), G4AdjointPhysicsList::ConstructEM(), PurgMagPhysicsList::ConstructEM(), eRositaPhysicsList::ConstructGeneral(), B03PhysicsList::ConstructGeneral(), ExN02PhysicsList::ConstructGeneral(), DMXPhysicsList::ConstructGeneral(), Par02PhysicsList::ConstructGeneral(), XrayTelPhysicsList::ConstructGeneral(), G4AdjointPhysicsList::ConstructGeneral(), OpNovicePhysicsList::ConstructOp(), DMXPhysicsList::ConstructOp(), PhysListEmStandard::ConstructProcess(), PhysListEmStandardSSM::ConstructProcess(), G4ParallelWorldPhysics::ConstructProcess(), PhysListEmStandardGS::ConstructProcess(), PhysListEmStandardSS::ConstructProcess(), PhysListEmStandardWVI::ConstructProcess(), PhysListEmPolarized::ConstructProcess(), PhysListEmStandard_GS::ConstructProcess(), PhysListEmStandard_WVI::ConstructProcess(), PhysListEmStandard_SS::ConstructProcess(), PhysListEmStandard_option3::ConstructProcess(), PhysListEmStandard_option4::ConstructProcess(), PhysListEmStandard_option0::ConstructProcess(), G4MonopolePhysics::ConstructProcess(), WLSOpticalPhysics::ConstructProcess(), F04PhysicsList::ConstructProcess(), G4ErrorPhysicsList::ConstructProcess(), GammaRayTelEMlowePhysics::ConstructProcess(), GammaRayTelEMstdPhysics::ConstructProcess(), GammaRayTelGeneralPhysics::ConstructProcess(), G4SpinDecayPhysics::ConstructProcess(), GammaRayTelMuonPhysics::ConstructProcess(), WLSPhysicsList::ConstructProcess(), G4OpticalPhysics::ConstructProcess(), GammaRayTelIonPhysics::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), G4RunManager::ConstructScoringWorlds(), export_G4ProcessManager(), and G4PhysicsListHelper::RegisterProcess().
AddRestProcess()
G4int G4ProcessManager::AddRestProcess (G4VProcess * aProcess, G4int ord = ordDefault)
Referenced by DMXPhysicsList::ConstructHad(), G4EmDNAChemistry::ConstructProcess(), G4EmDNAChemistry_option1::ConstructProcess(), F04PhysicsList::ConstructProcess(), GammaRayTelMuonPhysics::ConstructProcess(), G4StoppingPhysics::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), and export_G4ProcessManager().
CheckOrderingParameters()
void G4ProcessManager::CheckOrderingParameters (G4VProcess * aProcess) const protected
Definition at line 1154 of file G4ProcessManager.cc.
Referenced by AddProcess(), SetProcessOrdering(), SetProcessOrderingToFirst(), and SetProcessOrderingToSecond().
CreateGPILvectors()
void G4ProcessManager::CreateGPILvectors () private
Definition at line 1056 of file G4ProcessManager.cc.
Referenced by AddProcess(), RemoveProcess(), SetProcessOrdering(), SetProcessOrderingToFirst(), and SetProcessOrderingToSecond().
DumpInfo()
void G4ProcessManager::DumpInfo ()
Definition at line 1005 of file G4ProcessManager.cc.
Referenced by G4ProcessTable::DumpInfo(), export_G4ProcessManager(), and G4ProcessManagerMessenger::SetNewValue().
EndTracking()
void G4ProcessManager::EndTracking ()
Definition at line 1092 of file G4ProcessManager.cc.
Referenced by G4TrackingManager::ProcessOneTrack(), and G4ErrorPropagator::Propagate().
FindInsertPosition()
G4int G4ProcessManager::FindInsertPosition (G4int ord, G4int ivec) protected
Definition at line 389 of file G4ProcessManager.cc.
Referenced by AddProcess(), and SetProcessOrdering().
GetAlongStepIndex()
G4int G4ProcessManager::GetAlongStepIndex (G4VProcess * aProcess, G4ProcessVectorTypeIndex typ = typeGPIL) const
Referenced by export_G4ProcessManager().
GetAlongStepProcessVector()
G4ProcessVector* G4ProcessManager::GetAlongStepProcessVector (G4ProcessVectorTypeIndex typ = typeGPIL) const
Referenced by G4RunManagerKernel::ConfirmCoupledTransportation(), G4SteppingManager::GetProcessNumber(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4ProcessPlacer::PrintAlongStepDoItVec(), G4ProcessPlacer::PrintAlongStepGPILVec(), and G4ITStepProcessor::SetupGeneralProcessInfo().
GetAtRestIndex()
G4int G4ProcessManager::GetAtRestIndex (G4VProcess * aProcess, G4ProcessVectorTypeIndex typ = typeGPIL) const
Referenced by export_G4ProcessManager().
GetAtRestProcessVector()
G4ProcessVector* G4ProcessManager::GetAtRestProcessVector (G4ProcessVectorTypeIndex typ = typeGPIL) const
Referenced by G4hImpactIonisation::AlongStepDoIt(), G4ITStepProcessor::DealWithSecondaries(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), G4SteppingManager::GetProcessNumber(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePSDIP(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), and G4ITStepProcessor::SetupGeneralProcessInfo().
GetAttribute() [1/2]
G4ProcessAttribute * G4ProcessManager::GetAttribute (G4int index) const private
Definition at line 268 of file G4ProcessManager.cc.
Referenced by ActivateProcess(), CheckOrderingParameters(), CreateGPILvectors(), EndTracking(), GetAttribute(), GetProcessOrdering(), GetProcessVectorIndex(), InActivateProcess(), RemoveProcess(), SetProcessOrdering(), SetProcessOrderingToFirst(), SetProcessOrderingToSecond(), and StartTracking().
GetAttribute() [2/2]
G4ProcessAttribute * G4ProcessManager::GetAttribute (G4VProcess * aProcess) const private
Definition at line 324 of file G4ProcessManager.cc.
GetParticleType()
G4ParticleDefinition* G4ProcessManager::GetParticleType () const
Referenced by G4BiasingHelper::AddLimiterProcess(), G4ProcessTable::DumpInfo(), export_G4ProcessManager(), G4ProcessTable::FindProcess(), G4ProcessTable::Insert(), G4ProcessTable::Remove(), G4ProcessTable::SetProcessActivation(), and G4ParallelGeometriesLimiterProcess::SetProcessManager().
GetPostStepIndex()
G4int G4ProcessManager::GetPostStepIndex (G4VProcess * aProcess, G4ProcessVectorTypeIndex typ = typeGPIL) const
Referenced by export_G4ProcessManager().
GetPostStepProcessVector()
G4ProcessVector* G4ProcessManager::GetPostStepProcessVector (G4ProcessVectorTypeIndex typ = typeGPIL) const
Referenced by G4HadronElasticPhysics::GetElasticProcess(), G4SteppingManager::GetProcessNumber(), G4BiasingProcessInterface::IsFirstPostStepDoItInterface(), G4BiasingProcessInterface::IsFirstPostStepGPILInterface(), G4BiasingProcessInterface::IsLastPostStepDoItInterface(), G4BiasingProcessInterface::IsLastPostStepGPILInterface(), G4ProcessPlacer::PrintPostStepDoItVec(), G4ProcessPlacer::PrintPostStepGPILVec(), G4BiasingProcessInterface::ReorderBiasingVectorAsGPIL(), G4ITStepProcessor::SetupGeneralProcessInfo(), and WLSSteppingAction::UserSteppingAction().
GetProcess()
G4VProcess * G4ProcessManager::GetProcess (const G4String & processName) const
Definition at line 1103 of file G4ProcessManager.cc.
Referenced by NeutronHPphysics::ConstructProcess().
GetProcessActivation() [1/2]
G4bool G4ProcessManager::GetProcessActivation (G4int index) const
Definition at line 1136 of file G4ProcessManager.cc.
GetProcessActivation() [2/2]
G4bool G4ProcessManager::GetProcessActivation (G4VProcess * aProcess) const
Definition at line 1129 of file G4ProcessManager.cc.
Referenced by G4EmCalculator::ActiveForParticle().
GetProcessIndex()
G4int G4ProcessManager::GetProcessIndex (G4VProcess *) const
Referenced by export_G4ProcessManager(), GetAttribute(), GetProcessActivation(), GetProcessVectorIndex(), RemoveProcess(), G4ProcessTable::SetProcessActivation(), and SetProcessActivation().
GetProcessList()
G4ProcessVector* G4ProcessManager::GetProcessList () const
Referenced by G4BiasingHelper::ActivatePhysicsBiasing(), G4EmCalculator::ActiveForParticle(), G4ITStepProcessor::ActiveOnlyITProcess(), G4BiasingHelper::AddLimiterProcess(), G4ProcessPlacer::AddProcessAs(), RunAction::BeginOfRunAction(), G4hImpactIonisation::BuildPhysicsTable(), G4VUserChemistryList::BuildPhysicsTable(), G4VUserPhysicsList::BuildPhysicsTable(), G4LossTableManager::BuildTables(), G4PhysicsListHelper::CheckParticleList(), P6DExtDecayerPhysics::ConstructProcess(), G4FastSimulationPhysics::ConstructProcess(), G4GenericBiasingPhysics::ConstructProcess(), G4TheRayTracer::CreateBitMap(), G4EmDNAPhysicsActivator::DeactivateNuclearStopping(), G4LossTableManager::DumpHtml(), G4PhysListUtil::FindCaptureProcess(), G4VHadronPhysics::FindCaptureProcess(), G4VHadronPhysics::FindElasticProcess(), G4PhysListUtil::FindFissionProcess(), G4VHadronPhysics::FindFissionProcess(), G4PhysListUtil::FindInelasticProcess(), G4VHadronPhysics::FindInelasticProcess(), G4EmModelActivator::FindOrAddProcess(), G4EmCalculator::FindProcess(), G4ProcessTable::FindProcesses(), G4ErrorTrackLengthTarget::G4ErrorTrackLengthTarget(), PhysicsList::GetProcess(), G4EmDNAPhysicsActivator::HasMsc(), G4EmModelActivator::HasMsc(), G4VUserPhysicsList::PreparePhysicsTable(), G4PhysicsListHelper::RegisterProcess(), G4ProcessManagerMessenger::SetCurrentParticle(), G4EmConfigurator::SetModelForRegion(), G4ProcessTable::SetProcessActivation(), G4WorkerRunManagerKernel::SetupShadowProcess(), G4RunManagerKernel::SetupShadowProcess(), G4GlobalFastSimulationManager::ShowSetup(), and LXeSteppingAction::UserSteppingAction().
GetProcessListLength()
G4int G4ProcessManager::GetProcessListLength () const
Referenced by G4EmDNAPhysicsActivator::DeactivateNuclearStopping(), G4LossTableManager::DumpHtml(), export_G4ProcessManager(), G4EmModelActivator::FindOrAddProcess(), PhysicsList::GetProcess(), G4EmDNAPhysicsActivator::HasMsc(), G4EmModelActivator::HasMsc(), G4EmConfigurator::SetModelForRegion(), and LXeSteppingAction::UserSteppingAction().
GetProcessOrdering()
G4int G4ProcessManager::GetProcessOrdering (G4VProcess * aProcess, G4ProcessVectorDoItIndex idDoIt)
Definition at line 586 of file G4ProcessManager.cc.
Referenced by G4BiasingHelper::ActivatePhysicsBiasing(), and export_G4ProcessManager().
GetProcessVector()
G4ProcessVector* G4ProcessManager::GetProcessVector (G4ProcessVectorDoItIndex idx, G4ProcessVectorTypeIndex typ = typeGPIL) const
GetProcessVectorId()
G4int G4ProcessManager::GetProcessVectorId (G4ProcessVectorDoItIndex idx, G4ProcessVectorTypeIndex typ = typeGPIL) const protected
Referenced by GetProcessOrdering(), GetProcessVectorIndex(), SetProcessOrdering(), SetProcessOrderingToFirst(), and SetProcessOrderingToSecond().
GetProcessVectorIndex()
G4int G4ProcessManager::GetProcessVectorIndex (G4VProcess * aProcess, G4ProcessVectorDoItIndex idx, G4ProcessVectorTypeIndex typ = typeGPIL) const
Definition at line 234 of file G4ProcessManager.cc.
Referenced by export_G4ProcessManager().
GetVerboseLevel()
G4int G4ProcessManager::GetVerboseLevel () const
Referenced by ActivateProcess(), AddProcess(), CheckOrderingParameters(), G4ProcessTable::DumpInfo(), export_G4ProcessManager(), G4ProcessManager(), GetAttribute(), G4ProcessManagerMessenger::GetCurrentValue(), GetProcessActivation(), InActivateProcess(), InsertAt(), RemoveAt(), SetProcessOrdering(), SetProcessOrderingToSecond(), and ~G4ProcessManager().
InActivateProcess()
G4VProcess * G4ProcessManager::InActivateProcess (G4int index) private
Definition at line 866 of file G4ProcessManager.cc.
Referenced by SetProcessActivation().
InsertAt()
G4int G4ProcessManager::InsertAt (G4int position, G4VProcess * process, G4int ivec) protected
Definition at line 330 of file G4ProcessManager.cc.
Referenced by AddProcess(), SetProcessOrdering(), SetProcessOrderingToFirst(), and SetProcessOrderingToSecond().
operator!=()
G4bool G4ProcessManager::operator!= (const G4ProcessManager & right) const
Definition at line 999 of file G4ProcessManager.cc.
operator=()
G4ProcessManager & G4ProcessManager::operator= (const G4ProcessManager & right) private
Definition at line 190 of file G4ProcessManager.cc.
operator==()
G4bool G4ProcessManager::operator== (const G4ProcessManager & right) const
Definition at line 993 of file G4ProcessManager.cc.
RemoveAt()
G4int G4ProcessManager::RemoveAt (G4int position, G4VProcess * process, G4int ivec) protected
Definition at line 358 of file G4ProcessManager.cc.
Referenced by RemoveProcess(), SetProcessOrdering(), SetProcessOrderingToFirst(), and SetProcessOrderingToSecond().
RemoveProcess() [1/2]
G4VProcess * G4ProcessManager::RemoveProcess (G4int index)
Definition at line 515 of file G4ProcessManager.cc.
RemoveProcess() [2/2]
G4VProcess * G4ProcessManager::RemoveProcess (G4VProcess * aProcess)
Definition at line 580 of file G4ProcessManager.cc.
Referenced by G4BiasingHelper::ActivatePhysicsBiasing(), NeutronHPphysics::ConstructProcess(), G4MonopolePhysics::ConstructProcess(), F04PhysicsList::ConstructProcess(), G4SpinDecayPhysics::ConstructProcess(), WLSPhysicsList::ConstructProcess(), G4ErrorTrackLengthTarget::G4ErrorTrackLengthTarget(), and G4ProcessPlacer::RemoveProcess().
SetIndexToProcessVector()
void G4ProcessManager::SetIndexToProcessVector (G4int ivec) private
SetParticleType()
void G4ProcessManager::SetParticleType (const G4ParticleDefinition *)
Referenced by export_G4ProcessManager().
SetProcessActivation() [1/2]
G4VProcess * G4ProcessManager::SetProcessActivation (G4int index, G4bool fActive)
Definition at line 1122 of file G4ProcessManager.cc.
SetProcessActivation() [2/2]
G4VProcess * G4ProcessManager::SetProcessActivation (G4VProcess * aProcess, G4bool fActive)
Definition at line 1114 of file G4ProcessManager.cc.
Referenced by G4ITStepProcessor::ActiveOnlyITProcess(), G4ProcessManagerMessenger::SetNewValue(), and G4ProcessTable::SetProcessActivation().
SetProcessOrdering()
void G4ProcessManager::SetProcessOrdering (G4VProcess * aProcess, G4ProcessVectorDoItIndex idDoIt, G4int ordDoIt = ordDefault)
Definition at line 605 of file G4ProcessManager.cc.
Referenced by G4FastSimulationHelper::ActivateFastSimulation(), XrayFluoPhysicsList::AddDecay(), B03PhysicsList::AddScoringProcess(), OpNovicePhysicsList::ConstructDecay(), G4AdjointPhysicsList::ConstructEM(), eRositaPhysicsList::ConstructGeneral(), B03PhysicsList::ConstructGeneral(), ExN02PhysicsList::ConstructGeneral(), DMXPhysicsList::ConstructGeneral(), Par02PhysicsList::ConstructGeneral(), XrayTelPhysicsList::ConstructGeneral(), G4AdjointPhysicsList::ConstructGeneral(), OpNovicePhysicsList::ConstructOp(), G4ParallelWorldPhysics::ConstructProcess(), WLSOpticalPhysics::ConstructProcess(), F04PhysicsList::ConstructProcess(), GammaRayTelGeneralPhysics::ConstructProcess(), G4SpinDecayPhysics::ConstructProcess(), GammaRayTelMuonPhysics::ConstructProcess(), WLSPhysicsList::ConstructProcess(), G4OpticalPhysics::ConstructProcess(), GammaRayTelIonPhysics::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), G4RunManager::ConstructScoringWorlds(), export_G4ProcessManager(), G4PhysicsListHelper::RegisterProcess(), and SetProcessOrderingToLast().
SetProcessOrderingToFirst()
void G4ProcessManager::SetProcessOrderingToFirst (G4VProcess * aProcess, G4ProcessVectorDoItIndex idDoIt)
Definition at line 686 of file G4ProcessManager.cc.
Referenced by G4PhysicsListHelper::AddTransportation(), G4AdjointPhysicsList::ConstructEM(), G4ErrorPhysicsList::ConstructProcess(), export_G4ProcessManager(), and G4PhysicsListHelper::RegisterProcess().
SetProcessOrderingToLast()
void G4ProcessManager::SetProcessOrderingToLast (G4VProcess * aProcess, G4ProcessVectorDoItIndex idDoIt)
Definition at line 847 of file G4ProcessManager.cc.
Referenced by G4BiasingHelper::AddLimiterProcess(), OpNovicePhysicsList::ConstructOp(), DMXPhysicsList::ConstructOp(), WLSOpticalPhysics::ConstructProcess(), G4OpticalPhysics::ConstructProcess(), export_G4ProcessManager(), and G4PhysicsListHelper::RegisterProcess().
SetProcessOrderingToSecond()
void G4ProcessManager::SetProcessOrderingToSecond (G4VProcess * aProcess, G4ProcessVectorDoItIndex idDoIt)
Definition at line 756 of file G4ProcessManager.cc.
Referenced by G4BiasingHelper::AddLimiterProcess(), G4ProcessPlacer::AddProcessAs(), B03PhysicsList::AddScoringProcess(), G4ParallelWorldPhysics::ConstructProcess(), and G4RunManager::ConstructScoringWorlds().
SetVerboseLevel()
void G4ProcessManager::SetVerboseLevel (G4int value)
Referenced by DMXPhysicsList::ConstructGeneral(), G4ProcessTable::DumpInfo(), export_G4ProcessManager(), and G4ProcessManagerMessenger::SetNewValue().
StartTracking()
void G4ProcessManager::StartTracking (G4Track * aTrack = 0)
Definition at line 1082 of file G4ProcessManager.cc.
Referenced by G4ErrorPropagator::InitG4Track(), G4TrackingManager::ProcessOneTrack(), and G4ITTrackingManager::StartTracking().
Field Documentation
counterOfObjects
G4ThreadLocal G4int G4ProcessManager::counterOfObjects = 0 static private
Definition at line 366 of file G4ProcessManager.hh.
Referenced by G4ProcessManager(), and ~G4ProcessManager().
duringTracking
G4bool G4ProcessManager::duringTracking private
Definition at line 344 of file G4ProcessManager.hh.
Referenced by EndTracking(), and StartTracking().
fProcessManagerMessenger
G4ThreadLocal G4ProcessManagerMessenger * G4ProcessManager::fProcessManagerMessenger = 0 static private
Definition at line 365 of file G4ProcessManager.hh.
Referenced by G4ProcessManager(), and ~G4ProcessManager().
isSetOrderingFirstInvoked
G4bool G4ProcessManager::isSetOrderingFirstInvoked[NDoit] private
Definition at line 348 of file G4ProcessManager.hh.
Referenced by G4ProcessManager(), and SetProcessOrderingToFirst().
isSetOrderingLastInvoked
G4bool G4ProcessManager::isSetOrderingLastInvoked[NDoit] private
Definition at line 349 of file G4ProcessManager.hh.
Referenced by G4ProcessManager(), and SetProcessOrderingToLast().
numberOfProcesses
G4int G4ProcessManager::numberOfProcesses private
Definition at line 339 of file G4ProcessManager.hh.
Referenced by AddProcess(), FindInsertPosition(), G4ProcessManager(), GetAttribute(), GetProcess(), InsertAt(), RemoveAt(), RemoveProcess(), and SetProcessOrderingToSecond().
theAttrVector
G4ProcessAttrVector* G4ProcessManager::theAttrVector private
Definition at line 305 of file G4ProcessManager.hh.
Referenced by AddProcess(), G4ProcessManager(), GetAttribute(), RemoveProcess(), and ~G4ProcessManager().
theParticleType
const G4ParticleDefinition* G4ProcessManager::theParticleType private
Definition at line 336 of file G4ProcessManager.hh.
Referenced by ActivateProcess(), AddProcess(), DumpInfo(), GetAttribute(), GetProcessVectorIndex(), InActivateProcess(), RemoveProcess(), SetProcessOrdering(), SetProcessOrderingToFirst(), SetProcessOrderingToLast(), and SetProcessOrderingToSecond().
theProcessList
G4ProcessVector* G4ProcessManager::theProcessList private
Definition at line 340 of file G4ProcessManager.hh.
Referenced by AddProcess(), CreateGPILvectors(), DumpInfo(), EndTracking(), G4ProcessManager(), RemoveProcess(), StartTracking(), and ~G4ProcessManager().
theProcVector
G4ProcessVector* G4ProcessManager::theProcVector[SizeOfProcVectorArray] private
Definition at line 301 of file G4ProcessManager.hh.
Referenced by ActivateProcess(), CreateGPILvectors(), FindInsertPosition(), G4ProcessManager(), InActivateProcess(), InsertAt(), RemoveAt(), RemoveProcess(), SetProcessOrderingToSecond(), and ~G4ProcessManager().
verboseLevel
G4int G4ProcessManager::verboseLevel protected
Definition at line 362 of file G4ProcessManager.hh.
Referenced by AddProcess(), DumpInfo(), GetProcessVectorIndex(), SetProcessOrdering(), SetProcessOrderingToFirst(), and SetProcessOrderingToSecond().
The documentation for this class was generated from the following files:
source/processes/management/include/G4ProcessManager.hh
source/processes/management/src/G4ProcessManager.cc