Geant4: source/processes/hadronic/models/lend/src/xDataTOM_regionsW_XYs_LegendreSeries.cc File Reference
xDataTOM_regionsW_XYs_LegendreSeries.cc File Reference
#include <string.h>
#include "xDataTOM_private.h"
Functions
int xDataTOM_regionsW_XYs_LegendreSeries_initialize (statusMessageReporting *smr, xDataTOM_regionsW_XYs_LegendreSeries *regionsW_XYs_LegendreSeries, int length, xDataTOM_axes *axes)
int xDataTOM_regionsW_XYs_LegendreSeries_free (xDataTOM_xDataInfo *xDI)
int xDataTOM_regionsW_XYs_LegendreSeries_release (xDataTOM_regionsW_XYs_LegendreSeries *regionsW_XYs_LegendreSeries)
Variables
const char * xDataTOM_regionsW_XYs_LegendreSeries_ID = "regionsW_XYs_LegendreSeries"
Function Documentation
xDataTOM_regionsW_XYs_LegendreSeries_free()
int xDataTOM_regionsW_XYs_LegendreSeries_free (xDataTOM_xDataInfo * xDI)
Definition at line 33 of file xDataTOM_regionsW_XYs_LegendreSeries.cc.
Referenced by xDataTOM_releaseElement().
xDataTOM_regionsW_XYs_LegendreSeries_initialize()
int xDataTOM_regionsW_XYs_LegendreSeries_initialize (statusMessageReporting * smr, xDataTOM_regionsW_XYs_LegendreSeries * regionsW_XYs_LegendreSeries, int length, xDataTOM_axes * axes)
Definition at line 19 of file xDataTOM_regionsW_XYs_LegendreSeries.cc.
Referenced by xDataXML_regionsW_XYs_LegendreSeriesToTOM().
xDataTOM_regionsW_XYs_LegendreSeries_release()
int xDataTOM_regionsW_XYs_LegendreSeries_release (xDataTOM_regionsW_XYs_LegendreSeries * regionsW_XYs_LegendreSeries)
Definition at line 44 of file xDataTOM_regionsW_XYs_LegendreSeries.cc.
Referenced by xDataTOM_regionsW_XYs_LegendreSeries_free().
Variable Documentation
xDataTOM_regionsW_XYs_LegendreSeries_ID
const char* xDataTOM_regionsW_XYs_LegendreSeries_ID = "regionsW_XYs_LegendreSeries"
Definition at line 14 of file xDataTOM_regionsW_XYs_LegendreSeries.cc.
Referenced by xDataTOM_regionsW_XYs_LegendreSeries_free(), xDataTOM_releaseElement(), xDataXML_constructTOM(), and xDataXML_regionsW_XYs_LegendreSeriesToTOM().