Geant4: G4PenelopeOscillator Class Reference
G4PenelopeOscillator Class Reference
#include <G4PenelopeOscillator.hh>
Public Member Functions
G4PenelopeOscillator ()
G4PenelopeOscillator (const G4PenelopeOscillator &)
~G4PenelopeOscillator ()
G4PenelopeOscillator & operator= (const G4PenelopeOscillator &)
G4bool operator== (const G4PenelopeOscillator &) const
G4bool operator> (const G4PenelopeOscillator &) const
G4bool operator< (const G4PenelopeOscillator &) const
G4double GetHartreeFactor ()
void SetHartreeFactor (G4double hf)
G4double GetIonisationEnergy ()
void SetIonisationEnergy (G4double ie)
G4double GetResonanceEnergy () const
void SetResonanceEnergy (G4double re)
G4double GetOscillatorStrength ()
void SetOscillatorStrength (G4double ostr)
G4int GetShellFlag ()
void SetShellFlag (G4int theflag)
G4double GetParentZ ()
void SetParentZ (G4double parZ)
G4int GetParentShellID ()
void SetParentShellID (G4int psID)
G4double GetCutoffRecoilResonantEnergy ()
void SetCutoffRecoilResonantEnergy (G4double ene)
Private Attributes
G4double hartreeFactor
G4double ionisationEnergy
G4double resonanceEnergy
G4double oscillatorStrength
G4int shellFlag
G4double parentZ
G4int parentShellID
G4double cutoffRecoilResonantEnergy
Detailed Description
Definition at line 47 of file G4PenelopeOscillator.hh.
Constructor & Destructor Documentation
G4PenelopeOscillator() [1/2]
G4PenelopeOscillator::G4PenelopeOscillator ()
Definition at line 38 of file G4PenelopeOscillator.cc.
G4PenelopeOscillator() [2/2]
G4PenelopeOscillator::G4PenelopeOscillator (const G4PenelopeOscillator & right)
Definition at line 46 of file G4PenelopeOscillator.cc.
~G4PenelopeOscillator()
G4PenelopeOscillator::~G4PenelopeOscillator () inline
Definition at line 54 of file G4PenelopeOscillator.hh.
Member Function Documentation
GetCutoffRecoilResonantEnergy()
G4double G4PenelopeOscillator::GetCutoffRecoilResonantEnergy () inline
Definition at line 84 of file G4PenelopeOscillator.hh.
Referenced by G4PenelopeIonisationXSHandler::ComputeShellCrossSectionsElectron(), and G4PenelopeIonisationXSHandler::ComputeShellCrossSectionsPositron().
GetHartreeFactor()
G4double G4PenelopeOscillator::GetHartreeFactor () inline
Definition at line 63 of file G4PenelopeOscillator.hh.
Referenced by G4PenelopeComptonModel::DifferentialCrossSection().
GetIonisationEnergy()
G4double G4PenelopeOscillator::GetIonisationEnergy () inline
Definition at line 66 of file G4PenelopeOscillator.hh.
Referenced by G4PenelopeIonisationXSHandler::ComputeShellCrossSectionsElectron(), G4PenelopeIonisationXSHandler::ComputeShellCrossSectionsPositron(), G4PenelopeIonisationCrossSection::CrossSection(), G4PenelopeComptonModel::DifferentialCrossSection(), and G4PenelopeComptonModel::KleinNishinaCrossSection().
GetOscillatorStrength()
G4double G4PenelopeOscillator::GetOscillatorStrength () inline
Definition at line 72 of file G4PenelopeOscillator.hh.
Referenced by G4PenelopeIonisationXSHandler::BuildDeltaTable(), G4PenelopeIonisationXSHandler::BuildXSTable(), G4PenelopeComptonModel::KleinNishinaCrossSection(), and G4PenelopeComptonModel::OscillatorTotalCrossSection().
GetParentShellID()
G4int G4PenelopeOscillator::GetParentShellID () inline
Definition at line 81 of file G4PenelopeOscillator.hh.
GetParentZ()
G4double G4PenelopeOscillator::GetParentZ () inline
Definition at line 78 of file G4PenelopeOscillator.hh.
Referenced by G4PenelopeIonisationCrossSection::CrossSection(), and G4PenelopeIonisationCrossSection::FindShellIDIndex().
GetResonanceEnergy()
G4double G4PenelopeOscillator::GetResonanceEnergy () const inline
Definition at line 69 of file G4PenelopeOscillator.hh.
Referenced by G4PenelopeIonisationXSHandler::BuildDeltaTable(), G4PenelopeIonisationXSHandler::ComputeShellCrossSectionsElectron(), G4PenelopeIonisationXSHandler::ComputeShellCrossSectionsPositron(), and G4PenelopeIonisationCrossSection::CrossSection().
GetShellFlag()
G4int G4PenelopeOscillator::GetShellFlag () inline
Definition at line 75 of file G4PenelopeOscillator.hh.
Referenced by G4PenelopeIonisationCrossSection::CrossSection(), and G4PenelopeIonisationCrossSection::FindShellIDIndex().
operator<()
G4bool G4PenelopeOscillator::operator< (const G4PenelopeOscillator & right) const
Definition at line 96 of file G4PenelopeOscillator.cc.
operator=()
G4PenelopeOscillator & G4PenelopeOscillator::operator= (const G4PenelopeOscillator & right)
Definition at line 60 of file G4PenelopeOscillator.cc.
operator==()
G4bool G4PenelopeOscillator::operator== (const G4PenelopeOscillator & right) const
Definition at line 78 of file G4PenelopeOscillator.cc.
operator>()
G4bool G4PenelopeOscillator::operator> (const G4PenelopeOscillator & right) const
Definition at line 87 of file G4PenelopeOscillator.cc.
SetCutoffRecoilResonantEnergy()
void G4PenelopeOscillator::SetCutoffRecoilResonantEnergy (G4double ene) inline
Definition at line 85 of file G4PenelopeOscillator.hh.
SetHartreeFactor()
void G4PenelopeOscillator::SetHartreeFactor (G4double hf) inline
Definition at line 64 of file G4PenelopeOscillator.hh.
Referenced by G4PenelopeOscillatorManager::BuildOscillatorTable().
SetIonisationEnergy()
void G4PenelopeOscillator::SetIonisationEnergy (G4double ie) inline
Definition at line 67 of file G4PenelopeOscillator.hh.
Referenced by G4PenelopeOscillatorManager::BuildOscillatorTable().
SetOscillatorStrength()
void G4PenelopeOscillator::SetOscillatorStrength (G4double ostr) inline
Definition at line 73 of file G4PenelopeOscillator.hh.
Referenced by G4PenelopeOscillatorManager::BuildOscillatorTable().
SetParentShellID()
void G4PenelopeOscillator::SetParentShellID (G4int psID) inline
Definition at line 82 of file G4PenelopeOscillator.hh.
Referenced by G4PenelopeOscillatorManager::BuildOscillatorTable().
SetParentZ()
void G4PenelopeOscillator::SetParentZ (G4double parZ) inline
Definition at line 79 of file G4PenelopeOscillator.hh.
Referenced by G4PenelopeOscillatorManager::BuildOscillatorTable().
SetResonanceEnergy()
void G4PenelopeOscillator::SetResonanceEnergy (G4double re) inline
Definition at line 70 of file G4PenelopeOscillator.hh.
SetShellFlag()
void G4PenelopeOscillator::SetShellFlag (G4int theflag) inline
Definition at line 76 of file G4PenelopeOscillator.hh.
Referenced by G4PenelopeOscillatorManager::BuildOscillatorTable().
Field Documentation
cutoffRecoilResonantEnergy
G4double G4PenelopeOscillator::cutoffRecoilResonantEnergy private
Definition at line 95 of file G4PenelopeOscillator.hh.
Referenced by G4PenelopeOscillator(), GetCutoffRecoilResonantEnergy(), operator=(), and SetCutoffRecoilResonantEnergy().
hartreeFactor
G4double G4PenelopeOscillator::hartreeFactor private
Definition at line 85 of file G4PenelopeOscillator.hh.
Referenced by G4PenelopeOscillator(), GetHartreeFactor(), operator=(), and SetHartreeFactor().
ionisationEnergy
G4double G4PenelopeOscillator::ionisationEnergy private
Definition at line 89 of file G4PenelopeOscillator.hh.
Referenced by G4PenelopeOscillator(), GetIonisationEnergy(), operator<(), operator=(), operator==(), operator>(), and SetIonisationEnergy().
oscillatorStrength
G4double G4PenelopeOscillator::oscillatorStrength private
Definition at line 91 of file G4PenelopeOscillator.hh.
Referenced by G4PenelopeOscillator(), GetOscillatorStrength(), operator=(), and SetOscillatorStrength().
parentShellID
G4int G4PenelopeOscillator::parentShellID private
Definition at line 94 of file G4PenelopeOscillator.hh.
Referenced by G4PenelopeOscillator(), GetParentShellID(), operator=(), and SetParentShellID().
parentZ
G4double G4PenelopeOscillator::parentZ private
Definition at line 93 of file G4PenelopeOscillator.hh.
Referenced by G4PenelopeOscillator(), GetParentZ(), operator=(), and SetParentZ().
resonanceEnergy
G4double G4PenelopeOscillator::resonanceEnergy private
Definition at line 90 of file G4PenelopeOscillator.hh.
Referenced by G4PenelopeOscillator(), GetResonanceEnergy(), operator=(), and SetResonanceEnergy().
shellFlag
G4int G4PenelopeOscillator::shellFlag private
Definition at line 92 of file G4PenelopeOscillator.hh.
Referenced by G4PenelopeOscillator(), GetShellFlag(), operator=(), and SetShellFlag().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/lowenergy/include/G4PenelopeOscillator.hh
source/processes/electromagnetic/lowenergy/src/G4PenelopeOscillator.cc