Geant4: source/processes/hadronic/models/lend/src/xDataTOM_axes.cc File Reference
xDataTOM_axes.cc File Reference
#include <string.h>
#include "xDataTOM_private.h"
Functions
int xDataTOM_axes_initialize (statusMessageReporting *smr, xDataTOM_axes *axes, int numberOfAxes)
int xDataTOM_axes_release (xDataTOM_axes *axes)
const char * xDataTOM_axes_getLabel (statusMessageReporting *smr, xDataTOM_axes *axes, int index)
const char * xDataTOM_axes_getUnit (statusMessageReporting *smr, xDataTOM_axes *axes, int index)
int xDataTOM_axes_getInterpolation (statusMessageReporting *smr, xDataTOM_axes *axes, int index, enum xDataTOM_interpolationFlag *independent, enum xDataTOM_interpolationFlag *dependent, enum xDataTOM_interpolationQualifier *qualifier)
int xDataTOM_subAxes_initialize (statusMessageReporting *smr, xDataTOM_subAxes *subAxes, enum xDataTOM_subAxesType type, int offset, xDataTOM_axes *axes, xDataTOM_interpolation *interpolation)
int xDataTOM_subAxes_release (xDataTOM_subAxes *subAxes)
const char * xDataTOM_subAxes_getLabel (statusMessageReporting *smr, xDataTOM_subAxes *subAxes, int index)
const char * xDataTOM_subAxes_getUnit (statusMessageReporting *smr, xDataTOM_subAxes *subAxes, int index)
xDataTOM_axis * xDataTOM_axis_new (statusMessageReporting *smr, int index, char const *label, char const *unit, xDataTOM_interpolation *interpolation)
int xDataTOM_axis_initialize (statusMessageReporting *smr, xDataTOM_axis *axis, int index, char const *label, char const *unit, xDataTOM_interpolation *interpolation)
xDataTOM_axis * xDataTOM_axis_release (statusMessageReporting *, xDataTOM_axis *axis)
enum xDataTOM_frame xDataTOM_axis_stringToFrame (statusMessageReporting *, char const *frame)
const char * xDataTOM_axis_frameToString (statusMessageReporting *, enum xDataTOM_frame frame)
Variables
static const char * xDataTOM_frame_labString = "lab"
static const char * xDataTOM_frame_centerOfMassString = "centerOfMass"
static const char * xDataTOM_frame_invalidString = "invalid"
Function Documentation
xDataTOM_axes_getInterpolation()
int xDataTOM_axes_getInterpolation (statusMessageReporting * smr, xDataTOM_axes * axes, int index, enum xDataTOM_interpolationFlag * independent, enum xDataTOM_interpolationFlag * dependent, enum xDataTOM_interpolationQualifier * qualifier)
Definition at line 66 of file xDataTOM_axes.cc.
Referenced by xDataTOME_getInterpolation().
xDataTOM_axes_getLabel()
const char* xDataTOM_axes_getLabel (statusMessageReporting * smr, xDataTOM_axes * axes, int index)
Definition at line 44 of file xDataTOM_axes.cc.
Referenced by xDataTOM_subAxes_getLabel(), xDataXML_KalbachMannToTOM(), xDataXML_regionsW_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYsToTOM(), xDataXML_W_XYs_LegendreSeriesToTOM(), and xDataXML_W_XYsDataToTOM().
xDataTOM_axes_getUnit()
const char* xDataTOM_axes_getUnit (statusMessageReporting * smr, xDataTOM_axes * axes, int index)
Definition at line 55 of file xDataTOM_axes.cc.
Referenced by MCGIDI_fromTOM_pdfsOfXGivenW(), MCGIDI_KalbachMann_parseFromTOM(), MCGIDI_product_parsePolynomialMultiplicity(), and xDataTOM_subAxes_getUnit().
xDataTOM_axes_initialize()
int xDataTOM_axes_initialize (statusMessageReporting * smr, xDataTOM_axes * axes, int numberOfAxes)
Definition at line 21 of file xDataTOM_axes.cc.
Referenced by xDataXML_axesToTOM().
xDataTOM_axes_release()
int xDataTOM_axes_release (xDataTOM_axes * axes)
Definition at line 31 of file xDataTOM_axes.cc.
Referenced by xDataTOM_releaseElement().
xDataTOM_axis_frameToString()
const char* xDataTOM_axis_frameToString (statusMessageReporting * , enum xDataTOM_frame frame)
Definition at line 191 of file xDataTOM_axes.cc.
xDataTOM_axis_initialize()
int xDataTOM_axis_initialize (statusMessageReporting * smr, xDataTOM_axis * axis, int index, char const * label, char const * unit, xDataTOM_interpolation * interpolation)
Definition at line 155 of file xDataTOM_axes.cc.
Referenced by xDataTOM_axis_new(), and xDataXML_axesToTOM().
xDataTOM_axis_new()
xDataTOM_axis* xDataTOM_axis_new (statusMessageReporting * smr, int index, char const * label, char const * unit, xDataTOM_interpolation * interpolation)
Definition at line 144 of file xDataTOM_axes.cc.
xDataTOM_axis_release()
xDataTOM_axis* xDataTOM_axis_release (statusMessageReporting * , xDataTOM_axis * axis)
Definition at line 172 of file xDataTOM_axes.cc.
Referenced by xDataTOM_axes_release(), and xDataXML_axesToTOM().
xDataTOM_axis_stringToFrame()
enum xDataTOM_frame xDataTOM_axis_stringToFrame (statusMessageReporting * , char const * frame)
Definition at line 182 of file xDataTOM_axes.cc.
Referenced by MCGIDI_misc_getProductFrame().
xDataTOM_subAxes_getLabel()
const char* xDataTOM_subAxes_getLabel (statusMessageReporting * smr, xDataTOM_subAxes * subAxes, int index)
Definition at line 126 of file xDataTOM_axes.cc.
xDataTOM_subAxes_getUnit()
const char* xDataTOM_subAxes_getUnit (statusMessageReporting * smr, xDataTOM_subAxes * subAxes, int index)
Definition at line 133 of file xDataTOM_axes.cc.
Referenced by MCGIDI_angular_parseFromTOM(), MCGIDI_angularEnergy_parsePointwiseFromTOM(), MCGIDI_energyAngular_linear_parseFromTOM(), and MCGIDI_misc_dataFromXYs2ptwXYPointsInUnitsOf().
xDataTOM_subAxes_initialize()
int xDataTOM_subAxes_initialize (statusMessageReporting * smr, xDataTOM_subAxes * subAxes, enum xDataTOM_subAxesType type, int offset, xDataTOM_axes * axes, xDataTOM_interpolation * interpolation)
Definition at line 89 of file xDataTOM_axes.cc.
Referenced by xDataTOM_KalbachMann_initialize(), xDataTOM_polynomial_initialize(), xDataTOM_V_W_XYs_initialize(), xDataTOM_V_W_XYs_LegendreSeries_initialize(), xDataTOM_W_XYs_initialize(), xDataTOM_W_XYs_LegendreSeries_initialize(), and xDataXML_XYsDataToTOM().
xDataTOM_subAxes_release()
int xDataTOM_subAxes_release (xDataTOM_subAxes * subAxes)
Definition at line 118 of file xDataTOM_axes.cc.
Referenced by xDataTOM_KalbachMann_release(), xDataTOM_polynomial_release(), xDataTOM_W_XYs_release(), and xDataTOM_XYs_release().
Variable Documentation
xDataTOM_frame_centerOfMassString
const char* xDataTOM_frame_centerOfMassString = "centerOfMass" static
Definition at line 16 of file xDataTOM_axes.cc.
Referenced by xDataTOM_axis_frameToString().
xDataTOM_frame_invalidString
const char* xDataTOM_frame_invalidString = "invalid" static
Definition at line 17 of file xDataTOM_axes.cc.
Referenced by xDataTOM_axis_frameToString().
xDataTOM_frame_labString
const char* xDataTOM_frame_labString = "lab" static
Definition at line 15 of file xDataTOM_axes.cc.
Referenced by xDataTOM_axis_frameToString().