Geant4: G4PenelopeIonisationXSHandler Class Reference
G4PenelopeIonisationXSHandler Class Reference
#include <G4PenelopeIonisationXSHandler.hh>
Public Member Functions
G4PenelopeIonisationXSHandler (size_t nBins=200)
Constructor.
virtual ~G4PenelopeIonisationXSHandler ()
Destructor. Clean all tables.
G4double GetDensityCorrection (const G4Material *, const G4double energy) const
Returns the density coeection for the material at the given energy.
const G4PenelopeCrossSection * GetCrossSectionTableForCouple (const G4ParticleDefinition *, const G4Material *, const G4double cut) const
Returns the table of cross sections for the given particle, given material and given cut as a G4PenelopeCrossSection* pointer.
void SetVerboseLevel (G4int vl)
Setter for the verbosity level.
void BuildXSTable (const G4Material *, G4double cut, const G4ParticleDefinition *, G4bool isMaster=true)
This can be inkoved only by the master.
Private Member Functions
G4PenelopeIonisationXSHandler & operator= (const G4PenelopeIonisationXSHandler &right)
G4PenelopeIonisationXSHandler (const G4PenelopeIonisationXSHandler &)
void BuildDeltaTable (const G4Material *)
G4DataVector * ComputeShellCrossSectionsElectron (G4PenelopeOscillator *, G4double energy, G4double cut, G4double delta)
G4DataVector * ComputeShellCrossSectionsPositron (G4PenelopeOscillator *, G4double energy, G4double cut, G4double delta)
Private Attributes
G4PenelopeOscillatorManager * oscManager
std::map< std::pair< const G4Material *, G4double >, G4PenelopeCrossSection * > * XSTableElectron
std::map< std::pair< const G4Material *, G4double >, G4PenelopeCrossSection * > * XSTablePositron
std::map< const G4Material *, G4PhysicsFreeVector * > * theDeltaTable
G4PhysicsLogVector * energyGrid
size_t nBins
G4int verboseLevel
Detailed Description
Definition at line 59 of file G4PenelopeIonisationXSHandler.hh.
Constructor & Destructor Documentation
G4PenelopeIonisationXSHandler() [1/2]
G4PenelopeIonisationXSHandler::G4PenelopeIonisationXSHandler (size_t nBins = 200)
Constructor.
nBins is the number of intervals in the energy grid. By default the energy grid goes from 100 eV to 100 GeV.
Definition at line 46 of file G4PenelopeIonisationXSHandler.cc.
~G4PenelopeIonisationXSHandler()
G4PenelopeIonisationXSHandler::~G4PenelopeIonisationXSHandler () virtual
Destructor. Clean all tables.
Definition at line 69 of file G4PenelopeIonisationXSHandler.cc.
G4PenelopeIonisationXSHandler() [2/2]
G4PenelopeIonisationXSHandler::G4PenelopeIonisationXSHandler (const G4PenelopeIonisationXSHandler &) private
Member Function Documentation
BuildDeltaTable()
void G4PenelopeIonisationXSHandler::BuildDeltaTable (const G4Material * mat) private
Definition at line 322 of file G4PenelopeIonisationXSHandler.cc.
Referenced by BuildXSTable().
BuildXSTable()
void G4PenelopeIonisationXSHandler::BuildXSTable (const G4Material * mat, G4double cut, const G4ParticleDefinition * part, G4bool isMaster = true)
This can be inkoved only by the master.
Definition at line 159 of file G4PenelopeIonisationXSHandler.cc.
Referenced by G4PenelopeIonisationModel::ComputeDEDXPerVolume(), G4PenelopeIonisationCrossSection::CrossSection(), G4PenelopeIonisationModel::CrossSectionPerVolume(), and G4PenelopeIonisationModel::Initialise().
ComputeShellCrossSectionsElectron()
G4DataVector * G4PenelopeIonisationXSHandler::ComputeShellCrossSectionsElectron (G4PenelopeOscillator * theOsc, G4double energy, G4double cut, G4double delta) private
Definition at line 425 of file G4PenelopeIonisationXSHandler.cc.
Referenced by BuildXSTable().
ComputeShellCrossSectionsPositron()
G4DataVector * G4PenelopeIonisationXSHandler::ComputeShellCrossSectionsPositron (G4PenelopeOscillator * theOsc, G4double energy, G4double cut, G4double delta) private
Definition at line 557 of file G4PenelopeIonisationXSHandler.cc.
Referenced by BuildXSTable().
GetCrossSectionTableForCouple()
const G4PenelopeCrossSection * G4PenelopeIonisationXSHandler::GetCrossSectionTableForCouple (const G4ParticleDefinition * part, const G4Material * mat, const G4double cut) const
Returns the table of cross sections for the given particle, given material and given cut as a G4PenelopeCrossSection* pointer.
Definition at line 110 of file G4PenelopeIonisationXSHandler.cc.
Referenced by G4PenelopeIonisationModel::ComputeDEDXPerVolume(), G4PenelopeIonisationCrossSection::CrossSection(), G4PenelopeIonisationModel::CrossSectionPerVolume(), G4PenelopeIonisationModel::SampleFinalStateElectron(), and G4PenelopeIonisationModel::SampleFinalStatePositron().
GetDensityCorrection()
G4double G4PenelopeIonisationXSHandler::GetDensityCorrection (const G4Material * mat, const G4double energy) const
Returns the density coeection for the material at the given energy.
Definition at line 285 of file G4PenelopeIonisationXSHandler.cc.
Referenced by BuildXSTable(), G4PenelopeIonisationModel::SampleFinalStateElectron(), and G4PenelopeIonisationModel::SampleFinalStatePositron().
operator=()
G4PenelopeIonisationXSHandler& G4PenelopeIonisationXSHandler::operator= (const G4PenelopeIonisationXSHandler & right) private
SetVerboseLevel()
void G4PenelopeIonisationXSHandler::SetVerboseLevel (G4int vl) inline
Setter for the verbosity level.
Definition at line 78 of file G4PenelopeIonisationXSHandler.hh.
Referenced by G4PenelopeIonisationModel::Initialise().
Field Documentation
energyGrid
G4PhysicsLogVector* G4PenelopeIonisationXSHandler::energyGrid private
Definition at line 109 of file G4PenelopeIonisationXSHandler.hh.
Referenced by BuildDeltaTable(), BuildXSTable(), G4PenelopeIonisationXSHandler(), and ~G4PenelopeIonisationXSHandler().
nBins
size_t G4PenelopeIonisationXSHandler::nBins private
Definition at line 110 of file G4PenelopeIonisationXSHandler.hh.
Referenced by BuildDeltaTable(), BuildXSTable(), and G4PenelopeIonisationXSHandler().
oscManager
G4PenelopeOscillatorManager* G4PenelopeIonisationXSHandler::oscManager private
Definition at line 99 of file G4PenelopeIonisationXSHandler.hh.
Referenced by BuildDeltaTable(), BuildXSTable(), and G4PenelopeIonisationXSHandler().
theDeltaTable
std::map<const G4Material*,G4PhysicsFreeVector*>* G4PenelopeIonisationXSHandler::theDeltaTable private
Definition at line 106 of file G4PenelopeIonisationXSHandler.hh.
Referenced by BuildDeltaTable(), BuildXSTable(), G4PenelopeIonisationXSHandler(), GetDensityCorrection(), and ~G4PenelopeIonisationXSHandler().
verboseLevel
G4int G4PenelopeIonisationXSHandler::verboseLevel private
Definition at line 112 of file G4PenelopeIonisationXSHandler.hh.
Referenced by BuildXSTable(), G4PenelopeIonisationXSHandler(), SetVerboseLevel(), and ~G4PenelopeIonisationXSHandler().
XSTableElectron
std::map< std::pair<const G4Material*,G4double>, G4PenelopeCrossSection*>* G4PenelopeIonisationXSHandler::XSTableElectron private
Definition at line 102 of file G4PenelopeIonisationXSHandler.hh.
Referenced by BuildXSTable(), G4PenelopeIonisationXSHandler(), GetCrossSectionTableForCouple(), and ~G4PenelopeIonisationXSHandler().
XSTablePositron
std::map< std::pair<const G4Material*,G4double>, G4PenelopeCrossSection*>* G4PenelopeIonisationXSHandler::XSTablePositron private
Definition at line 103 of file G4PenelopeIonisationXSHandler.hh.
Referenced by BuildXSTable(), G4PenelopeIonisationXSHandler(), GetCrossSectionTableForCouple(), and ~G4PenelopeIonisationXSHandler().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/lowenergy/include/G4PenelopeIonisationXSHandler.hh
source/processes/electromagnetic/lowenergy/src/G4PenelopeIonisationXSHandler.cc