Geant4: G4VEnergyLossProcess Class Reference
G4VEnergyLossProcess Class Reference abstract
#include <G4VEnergyLossProcess.hh>
Public Member Functions
G4VEnergyLossProcess (const G4String &name="EnergyLoss", G4ProcessType type=fElectromagnetic)
virtual ~G4VEnergyLossProcess ()
virtual G4bool IsApplicable (const G4ParticleDefinition &p) override=0
virtual void PrintInfo ()
virtual void ProcessDescription (std::ostream &outFile) const override
virtual void PreparePhysicsTable (const G4ParticleDefinition &) override
virtual void BuildPhysicsTable (const G4ParticleDefinition &) override
G4PhysicsTable * BuildDEDXTable (G4EmTableType tType=fRestricted)
G4PhysicsTable * BuildLambdaTable (G4EmTableType tType=fRestricted)
virtual void StartTracking (G4Track *) override
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety, G4GPILSelection *selection) override
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &) override
G4double SampleSubCutSecondaries (std::vector< G4Track * > &, const G4Step &, G4VEmModel *model, G4int matIdx)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &) override
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii=false) override
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii) override
G4double GetDEDXDispersion (const G4MaterialCutsCouple *couple, const G4DynamicParticle *dp, G4double length)
G4double CrossSectionPerVolume (G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double MeanFreePath (const G4Track &track)
G4double ContinuousStepLimit (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety)
G4VEmModel * SelectModelForMaterial (G4double kinEnergy, size_t &idx) const
void AddEmModel (G4int, G4VEmModel *, G4VEmFluctuationModel *fluc=0, const G4Region *region=nullptr)
void UpdateEmModel (const G4String &, G4double, G4double)
void SetEmModel (G4VEmModel *, G4int index=0)
G4VEmModel * EmModel (size_t index=0) const
G4VEmModel * GetModelByIndex (G4int idx=0, G4bool ver=false) const
G4int NumberOfModels () const
void SetFluctModel (G4VEmFluctuationModel *)
G4VEmFluctuationModel * FluctModel ()
void SetBaseParticle (const G4ParticleDefinition *p)
const G4ParticleDefinition * Particle () const
const G4ParticleDefinition * BaseParticle () const
const G4ParticleDefinition * SecondaryParticle () const
void ActivateSubCutoff (G4bool val, const G4Region *region=nullptr)
void SetCrossSectionBiasingFactor (G4double f, G4bool flag=true)
void ActivateForcedInteraction (G4double length, const G4String &region, G4bool flag=true)
void ActivateSecondaryBiasing (const G4String &region, G4double factor, G4double energyLimit)
void AddCollaborativeProcess (G4VEnergyLossProcess *)
void SetLossFluctuations (G4bool val)
void SetIntegral (G4bool val)
G4bool IsIntegral () const
void SetIonisation (G4bool val)
G4bool IsIonisationProcess () const
void SetLinearLossLimit (G4double val)
void SetStepFunction (G4double v1, G4double v2, G4bool lock=true)
void SetLowestEnergyLimit (G4double)
G4int NumberOfSubCutoffRegions () const
void SetDEDXTable (G4PhysicsTable *p, G4EmTableType tType)
void SetCSDARangeTable (G4PhysicsTable *pRange)
void SetRangeTableForLoss (G4PhysicsTable *p)
void SetSecondaryRangeTable (G4PhysicsTable *p)
void SetInverseRangeTable (G4PhysicsTable *p)
void SetLambdaTable (G4PhysicsTable *p)
void SetSubLambdaTable (G4PhysicsTable *p)
void SetDEDXBinning (G4int nbins)
void SetMinKinEnergy (G4double e)
G4double MinKinEnergy () const
void SetMaxKinEnergy (G4double e)
G4double MaxKinEnergy () const
G4double CrossSectionBiasingFactor () const
G4double GetDEDX (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetDEDXForSubsec (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetRange (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetCSDARange (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetRangeForLoss (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetKineticEnergy (G4double range, const G4MaterialCutsCouple *)
G4double GetLambda (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4bool TablesAreBuilt () const
G4PhysicsTable * DEDXTable () const
G4PhysicsTable * DEDXTableForSubsec () const
G4PhysicsTable * DEDXunRestrictedTable () const
G4PhysicsTable * IonisationTable () const
G4PhysicsTable * IonisationTableForSubsec () const
G4PhysicsTable * CSDARangeTable () const
G4PhysicsTable * SecondaryRangeTable () const
G4PhysicsTable * RangeTableForLoss () const
G4PhysicsTable * InverseRangeTable () const
G4PhysicsTable * LambdaTable () const
G4PhysicsTable * SubLambdaTable () const
const G4Element * GetCurrentElement () const
void SetDynamicMassCharge (G4double massratio, G4double charge2ratio)
Public Member Functions inherited from G4VContinuousDiscreteProcess
G4VContinuousDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VContinuousDiscreteProcess (G4VContinuousDiscreteProcess &)
virtual ~G4VContinuousDiscreteProcess ()
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
virtual void StreamProcessInfo (std::ostream &) const
virtual void InitialiseEnergyLossProcess (const G4ParticleDefinition *, const G4ParticleDefinition *)=0
virtual G4double MinPrimaryEnergy (const G4ParticleDefinition *, const G4Material *, G4double cut)
virtual G4double GetMeanFreePath (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
virtual G4double GetContinuousStepLimit (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety) override
G4PhysicsVector * LambdaPhysicsVector (const G4MaterialCutsCouple *, G4double cut)
size_t CurrentMaterialCutsCoupleIndex () const
void SelectModel (G4double kinEnergy)
void SetParticle (const G4ParticleDefinition *p)
void SetSecondaryParticle (const G4ParticleDefinition *p)
Protected Member Functions inherited from G4VContinuousDiscreteProcess
void SetGPILSelection (G4GPILSelection selection)
G4GPILSelection GetGPILSelection () const
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes
G4ParticleChangeForLoss fParticleChange
const G4Material * currentMaterial
const G4MaterialCutsCouple * currentCouple
size_t currentCoupleIndex
G4double preStepLambda
G4double fRange
G4double computedRange
G4double preStepKinEnergy
G4double preStepScaledEnergy
G4double preStepRangeEnergy
G4double mfpKinEnergy
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Private Member Functions
void Clean ()
void StreamInfo (std::ostream &out, const G4ParticleDefinition &part, G4bool rst=false) const
G4bool StoreTable (const G4ParticleDefinition *p, G4PhysicsTable *, G4bool ascii, const G4String &directory, const G4String &tname)
G4bool RetrieveTable (const G4ParticleDefinition *p, G4PhysicsTable *, G4bool ascii, const G4String &directory, const G4String &tname, G4bool mandatory)
void FillSecondariesAlongStep (G4double &eloss, G4double &weight)
void PrintWarning (G4String, G4double val)
void DefineMaterial (const G4MaterialCutsCouple *couple)
G4double GetDEDXForScaledEnergy (G4double scaledKinEnergy)
G4double GetSubDEDXForScaledEnergy (G4double scaledKinEnergy)
G4double GetIonisationForScaledEnergy (G4double scaledKinEnergy)
G4double GetSubIonisationForScaledEnergy (G4double scaledKinEnergy)
G4double GetScaledRangeForScaledEnergy (G4double scaledKinEnergy)
G4double GetLimitScaledRangeForScaledEnergy (G4double scaledKinEnergy)
G4double ScaledKinEnergyForLoss (G4double range)
G4double GetLambdaForScaledEnergy (G4double scaledKinEnergy)
void ComputeLambdaForScaledEnergy (G4double scaledKinEnergy)
G4VEnergyLossProcess (G4VEnergyLossProcess &)=delete
G4VEnergyLossProcess & operator= (const G4VEnergyLossProcess &right)=delete
Private Attributes
G4LossTableManager * lManager
G4EmModelManager * modelManager
G4EmBiasingManager * biasManager
G4SafetyHelper * safetyHelper
G4EmParameters * theParameters
const G4ParticleDefinition * secondaryParticle
const G4ParticleDefinition * theElectron
const G4ParticleDefinition * thePositron
const G4ParticleDefinition * theGamma
const G4ParticleDefinition * theGenericIon
std::vector< G4VEmModel * > emModels
G4VEmFluctuationModel * fluctModel
G4VAtomDeexcitation * atomDeexcitation
G4VSubCutProducer * subcutProducer
std::vector< const G4Region * > scoffRegions
G4int nSCoffRegions
G4bool * idxSCoffRegions
std::vector< G4VEnergyLossProcess * > scProcesses
G4int nProcesses
G4PhysicsTable * theDEDXTable
G4PhysicsTable * theDEDXSubTable
G4PhysicsTable * theDEDXunRestrictedTable
G4PhysicsTable * theIonisationTable
G4PhysicsTable * theIonisationSubTable
G4PhysicsTable * theRangeTableForLoss
G4PhysicsTable * theCSDARangeTable
G4PhysicsTable * theSecondaryRangeTable
G4PhysicsTable * theInverseRangeTable
G4PhysicsTable * theLambdaTable
G4PhysicsTable * theSubLambdaTable
size_t idxDEDX
size_t idxDEDXSub
size_t idxDEDXunRestricted
size_t idxIonisation
size_t idxIonisationSub
size_t idxRange
size_t idxCSDA
size_t idxSecRange
size_t idxInverseRange
size_t idxLambda
size_t idxSubLambda
std::vector< G4double > theDEDXAtMaxEnergy
std::vector< G4double > theRangeAtMaxEnergy
std::vector< G4double > theEnergyOfCrossSectionMax
std::vector< G4double > theCrossSectionMax
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
const G4DataVector * theCuts
const G4DataVector * theSubCuts
const G4ParticleDefinition * baseParticle
G4int nBins
G4int nBinsCSDA
G4double lowestKinEnergy
G4double minKinEnergy
G4double maxKinEnergy
G4double maxKinEnergyCSDA
G4double linLossLimit
G4double dRoverRange
G4double finalRange
G4double lambdaFactor
G4double biasFactor
G4bool lossFluctuationFlag
G4bool rndmStepFlag
G4bool tablesAreBuilt
G4bool integral
G4bool isIon
G4bool isIonisation
G4bool useSubCutoff
G4bool useDeexcitation
G4bool biasFlag
G4bool weightFlag
G4bool isMaster
G4bool actIntegral
G4bool actStepFunc
G4bool actLinLossLimit
G4bool actLossFluc
G4bool actBinning
G4bool actMinKinEnergy
G4bool actMaxKinEnergy
std::vector< G4DynamicParticle * > secParticles
std::vector< G4Track * > scTracks
const G4ParticleDefinition * particle
G4VEmModel * currentModel
size_t basedCoupleIndex
size_t lastIdx
G4double massRatio
G4double fFactor
G4double reduceFactor
G4double chargeSqRatio
G4GPILSelection aGPILSelection
G4int secID
G4int subsecID
G4int biasID
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Detailed Description
Definition at line 81 of file G4VEnergyLossProcess.hh.
Constructor & Destructor Documentation
G4VEnergyLossProcess() [1/2]
G4VEnergyLossProcess::G4VEnergyLossProcess (const G4String & name = "EnergyLoss", G4ProcessType type = fElectromagnetic)
Definition at line 87 of file G4VEnergyLossProcess.cc.
~G4VEnergyLossProcess()
G4VEnergyLossProcess::~G4VEnergyLossProcess () virtual
Definition at line 195 of file G4VEnergyLossProcess.cc.
G4VEnergyLossProcess() [2/2]
G4VEnergyLossProcess::G4VEnergyLossProcess (G4VEnergyLossProcess &) private delete
Member Function Documentation
ActivateForcedInteraction()
void G4VEnergyLossProcess::ActivateForcedInteraction (G4double length, const G4String & region, G4bool flag = true)
Definition at line 2218 of file G4VEnergyLossProcess.cc.
Referenced by G4EmParameters::DefineRegParamForLoss().
ActivateSecondaryBiasing()
void G4VEnergyLossProcess::ActivateSecondaryBiasing (const G4String & region, G4double factor, G4double energyLimit)
Definition at line 2238 of file G4VEnergyLossProcess.cc.
Referenced by G4EmParameters::DefineRegParamForLoss().
ActivateSubCutoff()
void G4VEnergyLossProcess::ActivateSubCutoff (G4bool val, const G4Region * region = nullptr)
Definition at line 959 of file G4VEnergyLossProcess.cc.
Referenced by G4EmParameters::DefineRegParamForLoss().
AddCollaborativeProcess()
void G4VEnergyLossProcess::AddCollaborativeProcess (G4VEnergyLossProcess * p)
Definition at line 1967 of file G4VEnergyLossProcess.cc.
Referenced by G4LossTableManager::BuildTables().
AddEmModel()
void G4VEnergyLossProcess::AddEmModel (G4int order, G4VEmModel * p, G4VEmFluctuationModel * fluc = 0, const G4Region * region = nullptr)
Definition at line 311 of file G4VEnergyLossProcess.cc.
Referenced by G4EmLivermorePhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), PhysListEmLivermore::ConstructProcess(), PhysListEmPenelope::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4ePolarizedBremsstrahlung::InitialiseEnergyLossProcess(), G4LDMBremsstrahlung::InitialiseEnergyLossProcess(), G4hPairProduction::InitialiseEnergyLossProcess(), G4hBremsstrahlung::InitialiseEnergyLossProcess(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4ePairProduction::InitialiseEnergyLossProcess(), G4ePolarizedIonisation::InitialiseEnergyLossProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), G4MuPairProduction::InitialiseEnergyLossProcess(), G4eIonisation::InitialiseEnergyLossProcess(), G4eBremsstrahlung::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4MuBremsstrahlung::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), G4EmConfigurator::PrepareModels(), and G4EmConfigurator::SetModelForRegion().
AlongStepDoIt()
G4VParticleChange * G4VEnergyLossProcess::AlongStepDoIt (const G4Track & track, const G4Step & step) override virtual
Reimplemented from G4VContinuousDiscreteProcess.
Definition at line 1178 of file G4VEnergyLossProcess.cc.
AlongStepGetPhysicalInteractionLength()
G4double G4VEnergyLossProcess::AlongStepGetPhysicalInteractionLength (const G4Track & , G4double previousStepSize, G4double currentMinimumStep, G4double & currentSafety, G4GPILSelection * selection) override virtual
Reimplemented from G4VContinuousDiscreteProcess.
Definition at line 1023 of file G4VEnergyLossProcess.cc.
Referenced by ContinuousStepLimit().
BaseParticle()
const G4ParticleDefinition * G4VEnergyLossProcess::BaseParticle () const inline
Definition at line 857 of file G4VEnergyLossProcess.hh.
Referenced by G4LossTableManager::BuildPhysicsTable(), G4LossTableManager::LocalPhysicsTables(), G4LossTableManager::RegisterExtraParticle(), and G4EmCalculator::UpdateParticle().
BuildDEDXTable()
G4PhysicsTable * G4VEnergyLossProcess::BuildDEDXTable (G4EmTableType tType = fRestricted)
Definition at line 716 of file G4VEnergyLossProcess.cc.
Referenced by G4LossTableManager::BuildTables().
BuildLambdaTable()
G4PhysicsTable * G4VEnergyLossProcess::BuildLambdaTable (G4EmTableType tType = fRestricted)
Definition at line 804 of file G4VEnergyLossProcess.cc.
Referenced by G4LossTableManager::BuildTables().
BuildPhysicsTable()
void G4VEnergyLossProcess::BuildPhysicsTable (const G4ParticleDefinition & part) override virtual
Reimplemented from G4VProcess.
Reimplemented in G4ePolarizedIonisation.
Definition at line 608 of file G4VEnergyLossProcess.cc.
Referenced by G4ePolarizedIonisation::BuildPhysicsTable().
Clean()
void G4VEnergyLossProcess::Clean () private
Definition at line 280 of file G4VEnergyLossProcess.cc.
Referenced by PreparePhysicsTable(), and ~G4VEnergyLossProcess().
ComputeLambdaForScaledEnergy()
void G4VEnergyLossProcess::ComputeLambdaForScaledEnergy (G4double scaledKinEnergy) private
Definition at line 1148 of file G4VEnergyLossProcess.cc.
Referenced by PostStepGetPhysicalInteractionLength().
ContinuousStepLimit()
G4double G4VEnergyLossProcess::ContinuousStepLimit (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & currentSafety)
Definition at line 1924 of file G4VEnergyLossProcess.cc.
CrossSectionBiasingFactor()
G4double G4VEnergyLossProcess::CrossSectionBiasingFactor () const inline
Definition at line 923 of file G4VEnergyLossProcess.hh.
CrossSectionPerVolume()
G4double G4VEnergyLossProcess::CrossSectionPerVolume (G4double kineticEnergy, const G4MaterialCutsCouple * couple)
Definition at line 1895 of file G4VEnergyLossProcess.cc.
CSDARangeTable()
G4PhysicsTable * G4VEnergyLossProcess::CSDARangeTable () const inline
Definition at line 972 of file G4VEnergyLossProcess.hh.
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), and G4LossTableManager::CopyTables().
CurrentMaterialCutsCoupleIndex()
size_t G4VEnergyLossProcess::CurrentMaterialCutsCoupleIndex () const inline protected
Definition at line 575 of file G4VEnergyLossProcess.hh.
Referenced by G4ePolarizedIonisation::ComputeSaturationFactor().
DEDXTable()
G4PhysicsTable * G4VEnergyLossProcess::DEDXTable () const inline
Definition at line 937 of file G4VEnergyLossProcess.hh.
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), G4LossTableManager::LocalPhysicsTables(), and G4EmCalculator::PrintDEDXTable().
DEDXTableForSubsec()
G4PhysicsTable * G4VEnergyLossProcess::DEDXTableForSubsec () const inline
Definition at line 944 of file G4VEnergyLossProcess.hh.
Referenced by BuildPhysicsTable(), and G4LossTableManager::CopyTables().
DEDXunRestrictedTable()
G4PhysicsTable * G4VEnergyLossProcess::DEDXunRestrictedTable () const inline
Definition at line 951 of file G4VEnergyLossProcess.hh.
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), and G4LossTableManager::CopyTables().
DefineMaterial()
void G4VEnergyLossProcess::DefineMaterial (const G4MaterialCutsCouple * couple) inline private
Definition at line 599 of file G4VEnergyLossProcess.hh.
Referenced by CrossSectionPerVolume(), GetCSDARange(), GetDEDX(), GetDEDXDispersion(), GetDEDXForSubsec(), GetKineticEnergy(), GetLambda(), GetRange(), GetRangeForLoss(), MeanFreePath(), and PostStepGetPhysicalInteractionLength().
EmModel()
G4VEmModel * G4VEnergyLossProcess::EmModel (size_t index = 0) const
Definition at line 337 of file G4VEnergyLossProcess.cc.
Referenced by G4LDMBremsstrahlung::InitialiseEnergyLossProcess(), G4hPairProduction::InitialiseEnergyLossProcess(), G4hBremsstrahlung::InitialiseEnergyLossProcess(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4eIonisation::InitialiseEnergyLossProcess(), G4eBremsstrahlung::InitialiseEnergyLossProcess(), G4MuBremsstrahlung::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), G4ePairProduction::StreamProcessInfo(), G4MuPairProduction::StreamProcessInfo(), and G4eBremsstrahlung::StreamProcessInfo().
FillSecondariesAlongStep()
void G4VEnergyLossProcess::FillSecondariesAlongStep (G4double & eloss, G4double & weight) private
Definition at line 1438 of file G4VEnergyLossProcess.cc.
Referenced by AlongStepDoIt().
FluctModel()
G4VEmFluctuationModel * G4VEnergyLossProcess::FluctModel () inline
Definition at line 820 of file G4VEnergyLossProcess.hh.
Referenced by G4alphaIonisation::InitialiseEnergyLossProcess(), G4ePolarizedIonisation::InitialiseEnergyLossProcess(), G4eIonisation::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), and G4hIonisation::InitialiseEnergyLossProcess().
GetContinuousStepLimit()
G4double G4VEnergyLossProcess::GetContinuousStepLimit (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & currentSafety) override protected virtual
Implements G4VContinuousDiscreteProcess.
Definition at line 1946 of file G4VEnergyLossProcess.cc.
GetCSDARange()
G4double G4VEnergyLossProcess::GetCSDARange (G4double kineticEnergy, const G4MaterialCutsCouple * couple) inline
Definition at line 771 of file G4VEnergyLossProcess.hh.
Referenced by G4LossTableManager::GetCSDARange().
GetCurrentElement()
const G4Element * G4VEnergyLossProcess::GetCurrentElement () const
Definition at line 2191 of file G4VEnergyLossProcess.cc.
GetDEDX()
G4double G4VEnergyLossProcess::GetDEDX (G4double kineticEnergy, const G4MaterialCutsCouple * couple) inline
Definition at line 734 of file G4VEnergyLossProcess.hh.
Referenced by G4ContinuousGainOfEnergy::AlongStepDoIt(), G4VMscModel::GetDEDX(), and G4LossTableManager::GetDEDX().
GetDEDXDispersion()
G4double G4VEnergyLossProcess::GetDEDXDispersion (const G4MaterialCutsCouple * couple, const G4DynamicParticle * dp, G4double length)
Definition at line 1877 of file G4VEnergyLossProcess.cc.
Referenced by G4LossTableManager::GetDEDXDispersion().
GetDEDXForScaledEnergy()
G4double G4VEnergyLossProcess::GetDEDXForScaledEnergy (G4double scaledKinEnergy) inline private
Definition at line 626 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), and GetDEDX().
GetDEDXForSubsec()
G4double G4VEnergyLossProcess::GetDEDXForSubsec (G4double kineticEnergy, const G4MaterialCutsCouple * couple) inline
Definition at line 744 of file G4VEnergyLossProcess.hh.
Referenced by G4LossTableManager::GetSubDEDX().
GetIonisationForScaledEnergy()
G4double G4VEnergyLossProcess::GetIonisationForScaledEnergy (G4double scaledKinEnergy) inline private
Definition at line 650 of file G4VEnergyLossProcess.hh.
GetKineticEnergy()
G4double G4VEnergyLossProcess::GetKineticEnergy (G4double range, const G4MaterialCutsCouple * couple) inline
Definition at line 794 of file G4VEnergyLossProcess.hh.
Referenced by G4ContinuousGainOfEnergy::AlongStepDoIt(), G4VMscModel::GetEnergy(), and G4LossTableManager::GetEnergy().
GetLambda()
G4double G4VEnergyLossProcess::GetLambda (G4double kineticEnergy, const G4MaterialCutsCouple * couple) inline
Definition at line 804 of file G4VEnergyLossProcess.hh.
GetLambdaForScaledEnergy()
G4double G4VEnergyLossProcess::GetLambdaForScaledEnergy (G4double scaledKinEnergy) inline private
Definition at line 726 of file G4VEnergyLossProcess.hh.
Referenced by ComputeLambdaForScaledEnergy(), CrossSectionPerVolume(), GetLambda(), MeanFreePath(), PostStepDoIt(), and PostStepGetPhysicalInteractionLength().
GetLimitScaledRangeForScaledEnergy()
G4double G4VEnergyLossProcess::GetLimitScaledRangeForScaledEnergy (G4double scaledKinEnergy) inline private
Definition at line 693 of file G4VEnergyLossProcess.hh.
Referenced by GetCSDARange(), and GetRange().
GetMeanFreePath()
G4double G4VEnergyLossProcess::GetMeanFreePath (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) override protected virtual
Implements G4VContinuousDiscreteProcess.
Reimplemented in G4ePolarizedIonisation.
Definition at line 1934 of file G4VEnergyLossProcess.cc.
Referenced by G4ePolarizedIonisation::GetMeanFreePath().
GetModelByIndex()
G4VEmModel * G4VEnergyLossProcess::GetModelByIndex (G4int idx = 0, G4bool ver = false) const
Definition at line 344 of file G4VEnergyLossProcess.cc.
Referenced by BuildPhysicsTable().
GetRange()
G4double G4VEnergyLossProcess::GetRange (G4double kineticEnergy, const G4MaterialCutsCouple * couple) inline
Definition at line 754 of file G4VEnergyLossProcess.hh.
Referenced by G4ContinuousGainOfEnergy::AlongStepDoIt(), G4ContinuousGainOfEnergy::GetContinuousStepLimit(), and G4LossTableManager::GetRange().
GetRangeForLoss()
G4double G4VEnergyLossProcess::GetRangeForLoss (G4double kineticEnergy, const G4MaterialCutsCouple * couple) inline
Definition at line 783 of file G4VEnergyLossProcess.hh.
Referenced by G4EmBiasingManager::ApplyRangeCut(), G4VMscModel::GetRange(), and G4LossTableManager::GetRangeFromRestricteDEDX().
GetScaledRangeForScaledEnergy()
G4double G4VEnergyLossProcess::GetScaledRangeForScaledEnergy (G4double scaledKinEnergy) inline private
Definition at line 671 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepGetPhysicalInteractionLength(), GetRange(), and GetRangeForLoss().
GetSubDEDXForScaledEnergy()
G4double G4VEnergyLossProcess::GetSubDEDXForScaledEnergy (G4double scaledKinEnergy) inline private
Definition at line 640 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), and GetDEDXForSubsec().
GetSubIonisationForScaledEnergy()
G4double G4VEnergyLossProcess::GetSubIonisationForScaledEnergy (G4double scaledKinEnergy) inline private
Definition at line 661 of file G4VEnergyLossProcess.hh.
InitialiseEnergyLossProcess()
virtual void G4VEnergyLossProcess::InitialiseEnergyLossProcess (const G4ParticleDefinition * , const G4ParticleDefinition *) protected pure virtual
Implemented in G4hIonisation, G4MuIonisation, G4MuBremsstrahlung, G4ionIonisation, G4eBremsstrahlung, G4eIonisation, G4MuPairProduction, G4mplIonisation, G4hhIonisation, G4ePolarizedIonisation, G4ePairProduction, G4alphaIonisation, G4hBremsstrahlung, G4hPairProduction, G4LDMBremsstrahlung, and G4ePolarizedBremsstrahlung.
Referenced by PreparePhysicsTable().
InverseRangeTable()
G4PhysicsTable * G4VEnergyLossProcess::InverseRangeTable () const inline
Definition at line 993 of file G4VEnergyLossProcess.hh.
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), G4LossTableManager::CopyTables(), G4LossTableManager::LocalPhysicsTables(), and G4EmCalculator::PrintInverseRangeTable().
IonisationTable()
G4PhysicsTable * G4VEnergyLossProcess::IonisationTable () const inline
Definition at line 958 of file G4VEnergyLossProcess.hh.
Referenced by BuildPhysicsTable(), and G4LossTableManager::CopyTables().
IonisationTableForSubsec()
G4PhysicsTable * G4VEnergyLossProcess::IonisationTableForSubsec () const inline
Definition at line 965 of file G4VEnergyLossProcess.hh.
Referenced by BuildPhysicsTable(), and G4LossTableManager::BuildTables().
IsApplicable()
virtual G4bool G4VEnergyLossProcess::IsApplicable (const G4ParticleDefinition & p) override pure virtual
Reimplemented from G4VProcess.
Implemented in G4MuIonisation, G4hIonisation, G4MuBremsstrahlung, G4MuPairProduction, G4ePolarizedIonisation, G4mplIonisation, G4hBremsstrahlung, G4hhIonisation, G4hPairProduction, G4ePairProduction, G4LDMBremsstrahlung, G4eBremsstrahlung, G4eIonisation, G4ionIonisation, and G4alphaIonisation.
IsIntegral()
G4bool G4VEnergyLossProcess::IsIntegral () const inline
Definition at line 888 of file G4VEnergyLossProcess.hh.
IsIonisationProcess()
G4bool G4VEnergyLossProcess::IsIonisationProcess () const inline
Definition at line 895 of file G4VEnergyLossProcess.hh.
Referenced by G4LossTableManager::BuildPhysicsTable(), BuildPhysicsTable(), G4LossTableManager::BuildTables(), G4LossTableManager::CopyTables(), and G4LossTableManager::LocalPhysicsTables().
LambdaPhysicsVector()
G4PhysicsVector * G4VEnergyLossProcess::LambdaPhysicsVector (const G4MaterialCutsCouple * , G4double cut) protected
Definition at line 1956 of file G4VEnergyLossProcess.cc.
Referenced by G4ePolarizedIonisation::BuildAsymmetryTables().
LambdaTable()
G4PhysicsTable * G4VEnergyLossProcess::LambdaTable () const inline
Definition at line 1000 of file G4VEnergyLossProcess.hh.
Referenced by BuildPhysicsTable(), G4LossTableManager::CopyTables(), and G4EmCalculator::FindLambdaTable().
MaxKinEnergy()
G4double G4VEnergyLossProcess::MaxKinEnergy () const inline
Definition at line 916 of file G4VEnergyLossProcess.hh.
MeanFreePath()
G4double G4VEnergyLossProcess::MeanFreePath (const G4Track & track)
Definition at line 1915 of file G4VEnergyLossProcess.cc.
Referenced by GetMeanFreePath().
MinKinEnergy()
G4double G4VEnergyLossProcess::MinKinEnergy () const inline
Definition at line 909 of file G4VEnergyLossProcess.hh.
Referenced by G4LDMBremsstrahlung::MinPrimaryEnergy().
MinPrimaryEnergy()
G4double G4VEnergyLossProcess::MinPrimaryEnergy (const G4ParticleDefinition * , const G4Material * , G4double cut) protected virtual
Reimplemented in G4MuIonisation, G4MuBremsstrahlung, G4MuPairProduction, G4hhIonisation, G4ePairProduction, G4ionIonisation, G4hIonisation, G4alphaIonisation, G4mplIonisation, G4LDMBremsstrahlung, G4ePolarizedIonisation, and G4eIonisation.
Definition at line 302 of file G4VEnergyLossProcess.cc.
Referenced by BuildLambdaTable().
NumberOfModels()
G4int G4VEnergyLossProcess::NumberOfModels () const
Definition at line 351 of file G4VEnergyLossProcess.cc.
NumberOfSubCutoffRegions()
G4int G4VEnergyLossProcess::NumberOfSubCutoffRegions () const inline
Definition at line 902 of file G4VEnergyLossProcess.hh.
Referenced by G4LossTableManager::BuildTables().
operator=()
G4VEnergyLossProcess& G4VEnergyLossProcess::operator= (const G4VEnergyLossProcess & right) private delete
Particle()
const G4ParticleDefinition * G4VEnergyLossProcess::Particle () const inline
Definition at line 850 of file G4VEnergyLossProcess.hh.
Referenced by G4LossTableManager::BuildPhysicsTable(), and G4LossTableManager::LocalPhysicsTables().
PostStepDoIt()
G4VParticleChange * G4VEnergyLossProcess::PostStepDoIt (const G4Track & track, const G4Step & step) override virtual
Reimplemented from G4VContinuousDiscreteProcess.
Definition at line 1548 of file G4VEnergyLossProcess.cc.
PostStepGetPhysicalInteractionLength()
G4double G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) override virtual
Reimplemented from G4VContinuousDiscreteProcess.
Reimplemented in G4ePolarizedIonisation.
Definition at line 1053 of file G4VEnergyLossProcess.cc.
Referenced by G4ePolarizedIonisation::PostStepGetPhysicalInteractionLength().
PreparePhysicsTable()
void G4VEnergyLossProcess::PreparePhysicsTable (const G4ParticleDefinition & part) override virtual
Reimplemented from G4VProcess.
Definition at line 359 of file G4VEnergyLossProcess.cc.
PrintInfo()
virtual void G4VEnergyLossProcess::PrintInfo () inline virtual
Reimplemented in G4MuIonisation, G4MuBremsstrahlung, G4eIonisation, G4mplIonisation, G4ePolarizedIonisation, G4hhIonisation, G4alphaIonisation, and G4hIonisation.
Definition at line 102 of file G4VEnergyLossProcess.hh.
PrintWarning()
void G4VEnergyLossProcess::PrintWarning (G4String tit, G4double val) private
Definition at line 2340 of file G4VEnergyLossProcess.cc.
Referenced by SetDEDXBinning(), SetLinearLossLimit(), SetLowestEnergyLimit(), SetMaxKinEnergy(), SetMinKinEnergy(), and SetStepFunction().
ProcessDescription()
void G4VEnergyLossProcess::ProcessDescription (std::ostream & outFile) const override virtual
Reimplemented from G4VProcess.
Reimplemented in G4MuIonisation, G4hIonisation, G4MuBremsstrahlung, G4eIonisation, G4ionIonisation, G4eBremsstrahlung, G4MuPairProduction, G4mplIonisation, G4hhIonisation, G4ePairProduction, G4hBremsstrahlung, G4alphaIonisation, and G4hPairProduction.
Definition at line 2354 of file G4VEnergyLossProcess.cc.
Referenced by G4hPairProduction::ProcessDescription(), G4alphaIonisation::ProcessDescription(), G4hBremsstrahlung::ProcessDescription(), G4ePairProduction::ProcessDescription(), G4hhIonisation::ProcessDescription(), G4mplIonisation::ProcessDescription(), G4MuPairProduction::ProcessDescription(), G4eBremsstrahlung::ProcessDescription(), G4ionIonisation::ProcessDescription(), G4eIonisation::ProcessDescription(), G4MuBremsstrahlung::ProcessDescription(), G4hIonisation::ProcessDescription(), and G4MuIonisation::ProcessDescription().
RangeTableForLoss()
G4PhysicsTable * G4VEnergyLossProcess::RangeTableForLoss () const inline
Definition at line 986 of file G4VEnergyLossProcess.hh.
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), G4LossTableManager::CopyTables(), G4LossTableManager::LocalPhysicsTables(), and G4EmCalculator::PrintRangeTable().
RetrievePhysicsTable()
G4bool G4VEnergyLossProcess::RetrievePhysicsTable (const G4ParticleDefinition * part, const G4String & directory, G4bool ascii) override virtual
Reimplemented from G4VProcess.
Definition at line 1750 of file G4VEnergyLossProcess.cc.
RetrieveTable()
G4bool G4VEnergyLossProcess::RetrieveTable (const G4ParticleDefinition * p, G4PhysicsTable * aTable, G4bool ascii, const G4String & directory, const G4String & tname, G4bool mandatory) private
Definition at line 1836 of file G4VEnergyLossProcess.cc.
Referenced by RetrievePhysicsTable().
SampleSubCutSecondaries()
G4double G4VEnergyLossProcess::SampleSubCutSecondaries (std::vector< G4Track * > & tracks, const G4Step & step, G4VEmModel * model, G4int matIdx)
Definition at line 1470 of file G4VEnergyLossProcess.cc.
Referenced by AlongStepDoIt().
ScaledKinEnergyForLoss()
G4double G4VEnergyLossProcess::ScaledKinEnergyForLoss (G4double range) inline private
Definition at line 708 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), and GetKineticEnergy().
SecondaryParticle()
const G4ParticleDefinition * G4VEnergyLossProcess::SecondaryParticle () const inline
Definition at line 865 of file G4VEnergyLossProcess.hh.
Referenced by G4LossTableManager::CopyTables().
SecondaryRangeTable()
G4PhysicsTable * G4VEnergyLossProcess::SecondaryRangeTable () const inline
Definition at line 979 of file G4VEnergyLossProcess.hh.
Referenced by BuildPhysicsTable().
SelectModel()
void G4VEnergyLossProcess::SelectModel (G4double kinEnergy) inline protected
Definition at line 582 of file G4VEnergyLossProcess.hh.
Referenced by CrossSectionPerVolume(), GetDEDXDispersion(), PostStepDoIt(), and PostStepGetPhysicalInteractionLength().
SelectModelForMaterial()
G4VEmModel * G4VEnergyLossProcess::SelectModelForMaterial (G4double kinEnergy, size_t & idx) const inline
Definition at line 590 of file G4VEnergyLossProcess.hh.
Referenced by G4EmCalculator::FindEmModel(), and G4ContinuousGainOfEnergy::GetContinuousStepLimit().
SetBaseParticle()
void G4VEnergyLossProcess::SetBaseParticle (const G4ParticleDefinition * p) inline
Definition at line 843 of file G4VEnergyLossProcess.hh.
Referenced by G4alphaIonisation::InitialiseEnergyLossProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), and G4hIonisation::InitialiseEnergyLossProcess().
SetCrossSectionBiasingFactor()
void G4VEnergyLossProcess::SetCrossSectionBiasingFactor (G4double f, G4bool flag = true)
Definition at line 2200 of file G4VEnergyLossProcess.cc.
Referenced by G4EmParameters::DefineRegParamForLoss().
SetCSDARangeTable()
void G4VEnergyLossProcess::SetCSDARangeTable (G4PhysicsTable * pRange)
Definition at line 2055 of file G4VEnergyLossProcess.cc.
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), and G4LossTableManager::CopyTables().
SetDEDXBinning()
void G4VEnergyLossProcess::SetDEDXBinning (G4int nbins)
Definition at line 2306 of file G4VEnergyLossProcess.cc.
Referenced by G4MonopolePhysics::ConstructProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), and G4hIonisation::InitialiseEnergyLossProcess().
SetDEDXTable()
void G4VEnergyLossProcess::SetDEDXTable (G4PhysicsTable * p, G4EmTableType tType)
Definition at line 1994 of file G4VEnergyLossProcess.cc.
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), and G4LossTableManager::CopyTables().
SetDynamicMassCharge()
void G4VEnergyLossProcess::SetDynamicMassCharge (G4double massratio, G4double charge2ratio) inline
Definition at line 615 of file G4VEnergyLossProcess.hh.
Referenced by G4ContinuousGainOfEnergy::AlongStepDoIt(), G4ContinuousGainOfEnergy::GetContinuousStepLimit(), G4ContinuousGainOfEnergy::SetDynamicMassCharge(), and G4EmCalculator::UpdateParticle().
SetEmModel()
void G4VEnergyLossProcess::SetEmModel (G4VEmModel * ptr, G4int index = 0)
Definition at line 329 of file G4VEnergyLossProcess.cc.
Referenced by DMXPhysicsList::ConstructEM(), G4EmLivermorePhysics::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), PhysListEmStandardNR::ConstructProcess(), PhysListEmStandardGS::ConstructProcess(), ElectromagneticPhysics::ConstructProcess(), PhysListEmStandardWVI::ConstructProcess(), PhysListEmStandard_GS::ConstructProcess(), PhysListEmStandard_WVI::ConstructProcess(), PhysListEmStandard_option0::ConstructProcess(), PhysListEmStandard_option3::ConstructProcess(), PhysListEmStandard_option4::ConstructProcess(), PhysListEmStandard_SS::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), GammaRayTelEMlowePhysics::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysicsWVI::ConstructProcess(), G4LDMBremsstrahlung::InitialiseEnergyLossProcess(), G4hPairProduction::InitialiseEnergyLossProcess(), G4hBremsstrahlung::InitialiseEnergyLossProcess(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4ePairProduction::InitialiseEnergyLossProcess(), G4ePolarizedIonisation::InitialiseEnergyLossProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), G4MuPairProduction::InitialiseEnergyLossProcess(), G4eIonisation::InitialiseEnergyLossProcess(), G4eBremsstrahlung::InitialiseEnergyLossProcess(), G4MuBremsstrahlung::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), and G4hIonisation::InitialiseEnergyLossProcess().
SetFluctModel()
void G4VEnergyLossProcess::SetFluctModel (G4VEmFluctuationModel * p) inline
Definition at line 813 of file G4VEnergyLossProcess.hh.
Referenced by PhysListEm19DStandard::ConstructProcess(), G4EmStandardPhysicsWVI::ConstructProcess(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4ePolarizedIonisation::InitialiseEnergyLossProcess(), G4eIonisation::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), and G4EmConfigurator::PrepareModels().
SetIntegral()
void G4VEnergyLossProcess::SetIntegral (G4bool val) inline
Definition at line 880 of file G4VEnergyLossProcess.hh.
SetInverseRangeTable()
void G4VEnergyLossProcess::SetInverseRangeTable (G4PhysicsTable * p)
Definition at line 2105 of file G4VEnergyLossProcess.cc.
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), and G4LossTableManager::CopyTables().
SetIonisation()
void G4VEnergyLossProcess::SetIonisation (G4bool val)
Definition at line 2263 of file G4VEnergyLossProcess.cc.
Referenced by G4LossTableManager::BuildPhysicsTable(), G4LossTableManager::BuildTables(), G4LossTableManager::CopyTables(), G4eBremsstrahlung::G4eBremsstrahlung(), G4ePairProduction::G4ePairProduction(), G4MuBremsstrahlung::G4MuBremsstrahlung(), G4MuPairProduction::G4MuPairProduction(), and G4ePolarizedBremsstrahlung::InitialiseEnergyLossProcess().
SetLambdaTable()
void G4VEnergyLossProcess::SetLambdaTable (G4PhysicsTable * p)
Definition at line 2117 of file G4VEnergyLossProcess.cc.
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), and G4LossTableManager::CopyTables().
SetLinearLossLimit()
void G4VEnergyLossProcess::SetLinearLossLimit (G4double val)
Definition at line 2271 of file G4VEnergyLossProcess.cc.
Referenced by G4alphaIonisation::G4alphaIonisation(), and G4ionIonisation::G4ionIonisation().
SetLossFluctuations()
void G4VEnergyLossProcess::SetLossFluctuations (G4bool val) inline
Definition at line 872 of file G4VEnergyLossProcess.hh.
Referenced by G4AdjointPhysicsList::ConstructEM(), and G4AdjointPhysicsList::SetLossFluctuationFlag().
SetLowestEnergyLimit()
void G4VEnergyLossProcess::SetLowestEnergyLimit (G4double val)
Definition at line 2298 of file G4VEnergyLossProcess.cc.
SetMaxKinEnergy()
void G4VEnergyLossProcess::SetMaxKinEnergy (G4double e)
Definition at line 2329 of file G4VEnergyLossProcess.cc.
Referenced by G4MonopolePhysics::ConstructProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), and G4hIonisation::InitialiseEnergyLossProcess().
SetMinKinEnergy()
void G4VEnergyLossProcess::SetMinKinEnergy (G4double e)
Definition at line 2319 of file G4VEnergyLossProcess.cc.
Referenced by G4MonopolePhysics::ConstructProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), and G4hIonisation::InitialiseEnergyLossProcess().
SetParticle()
void G4VEnergyLossProcess::SetParticle (const G4ParticleDefinition * p) inline protected
Definition at line 827 of file G4VEnergyLossProcess.hh.
SetRangeTableForLoss()
void G4VEnergyLossProcess::SetRangeTableForLoss (G4PhysicsTable * p)
Definition at line 2081 of file G4VEnergyLossProcess.cc.
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), and G4LossTableManager::CopyTables().
SetSecondaryParticle()
void G4VEnergyLossProcess::SetSecondaryParticle (const G4ParticleDefinition * p) inline protected
Definition at line 835 of file G4VEnergyLossProcess.hh.
Referenced by G4eBremsstrahlung::G4eBremsstrahlung(), G4eIonisation::G4eIonisation(), G4ePairProduction::G4ePairProduction(), G4ePolarizedIonisation::G4ePolarizedIonisation(), G4hhIonisation::G4hhIonisation(), G4hIonisation::G4hIonisation(), G4ionIonisation::G4ionIonisation(), G4mplIonisation::G4mplIonisation(), G4MuBremsstrahlung::G4MuBremsstrahlung(), G4MuIonisation::G4MuIonisation(), G4MuPairProduction::G4MuPairProduction(), G4ePolarizedBremsstrahlung::InitialiseEnergyLossProcess(), and G4alphaIonisation::InitialiseEnergyLossProcess().
SetSecondaryRangeTable()
void G4VEnergyLossProcess::SetSecondaryRangeTable (G4PhysicsTable * p)
Definition at line 2093 of file G4VEnergyLossProcess.cc.
Referenced by BuildPhysicsTable(), and G4LossTableManager::CopyTables().
SetStepFunction()
void G4VEnergyLossProcess::SetStepFunction (G4double v1, G4double v2, G4bool lock = true)
Definition at line 2282 of file G4VEnergyLossProcess.cc.
Referenced by DMXPhysicsList::ConstructEM(), G4EmDNAPhysics_option3::ConstructProcess(), G4EmDNAPhysics_stationary_option2::ConstructProcess(), G4EmDNAPhysics_stationary_option4::ConstructProcess(), G4EmDNAPhysics_stationary_option6::ConstructProcess(), G4EmDNAPhysics_stationary::ConstructProcess(), G4EmDNAPhysics_option2::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4EmDNAPhysics::ConstructProcess(), G4EmDNAPhysics_option1::ConstructProcess(), G4EmDNAPhysics_option4::ConstructProcess(), G4EmDNAPhysics_option5::ConstructProcess(), G4EmDNAPhysics_option7::ConstructProcess(), G4EmDNAPhysics_option8::ConstructProcess(), PhysListEmStandardNR::ConstructProcess(), G4EmDNAPhysics_option6::ConstructProcess(), PhysListEm5DStandard::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4EmStandardPhysicsWVI::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), G4EmStandardPhysics_option2::ConstructProcess(), G4EmParameters::DefineRegParamForLoss(), G4hhIonisation::G4hhIonisation(), and G4mplIonisation::G4mplIonisation().
SetSubLambdaTable()
void G4VEnergyLossProcess::SetSubLambdaTable (G4PhysicsTable * p)
Definition at line 2179 of file G4VEnergyLossProcess.cc.
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), and G4LossTableManager::CopyTables().
StartTracking()
void G4VEnergyLossProcess::StartTracking (G4Track * track) override virtual
Reimplemented from G4VProcess.
Definition at line 984 of file G4VEnergyLossProcess.cc.
StorePhysicsTable()
G4bool G4VEnergyLossProcess::StorePhysicsTable (const G4ParticleDefinition * part, const G4String & directory, G4bool ascii = false) override virtual
Reimplemented from G4VProcess.
Definition at line 1687 of file G4VEnergyLossProcess.cc.
StoreTable()
G4bool G4VEnergyLossProcess::StoreTable (const G4ParticleDefinition * p, G4PhysicsTable * aTable, G4bool ascii, const G4String & directory, const G4String & tname) private
Definition at line 1816 of file G4VEnergyLossProcess.cc.
Referenced by StorePhysicsTable().
StreamInfo()
void G4VEnergyLossProcess::StreamInfo (std::ostream & out, const G4ParticleDefinition & part, G4bool rst = false) const private
Definition at line 884 of file G4VEnergyLossProcess.cc.
Referenced by BuildPhysicsTable(), and ProcessDescription().
StreamProcessInfo()
virtual void G4VEnergyLossProcess::StreamProcessInfo (std::ostream &) const inline protected virtual
Reimplemented in G4ionIonisation, G4eBremsstrahlung, G4MuPairProduction, and G4ePairProduction.
Definition at line 108 of file G4VEnergyLossProcess.hh.
Referenced by StreamInfo().
SubLambdaTable()
G4PhysicsTable * G4VEnergyLossProcess::SubLambdaTable () const inline
Definition at line 1007 of file G4VEnergyLossProcess.hh.
Referenced by BuildPhysicsTable(), and G4LossTableManager::CopyTables().
TablesAreBuilt()
G4bool G4VEnergyLossProcess::TablesAreBuilt () const inline
Definition at line 930 of file G4VEnergyLossProcess.hh.
UpdateEmModel()
void G4VEnergyLossProcess::UpdateEmModel (const G4String & nam, G4double emin, G4double emax)
Definition at line 321 of file G4VEnergyLossProcess.cc.
Field Documentation
actBinning
G4bool G4VEnergyLossProcess::actBinning private
Definition at line 529 of file G4VEnergyLossProcess.hh.
Referenced by G4VEnergyLossProcess(), PreparePhysicsTable(), and SetDEDXBinning().
actIntegral
G4bool G4VEnergyLossProcess::actIntegral private
Definition at line 525 of file G4VEnergyLossProcess.hh.
Referenced by G4VEnergyLossProcess(), PreparePhysicsTable(), and SetIntegral().
actLinLossLimit
G4bool G4VEnergyLossProcess::actLinLossLimit private
Definition at line 527 of file G4VEnergyLossProcess.hh.
Referenced by G4VEnergyLossProcess(), PreparePhysicsTable(), and SetLinearLossLimit().
actLossFluc
G4bool G4VEnergyLossProcess::actLossFluc private
Definition at line 528 of file G4VEnergyLossProcess.hh.
Referenced by G4VEnergyLossProcess(), PreparePhysicsTable(), and SetLossFluctuations().
actMaxKinEnergy
G4bool G4VEnergyLossProcess::actMaxKinEnergy private
Definition at line 531 of file G4VEnergyLossProcess.hh.
Referenced by G4VEnergyLossProcess(), PreparePhysicsTable(), and SetMaxKinEnergy().
actMinKinEnergy
G4bool G4VEnergyLossProcess::actMinKinEnergy private
Definition at line 530 of file G4VEnergyLossProcess.hh.
Referenced by G4VEnergyLossProcess(), PreparePhysicsTable(), and SetMinKinEnergy().
actStepFunc
G4bool G4VEnergyLossProcess::actStepFunc private
Definition at line 526 of file G4VEnergyLossProcess.hh.
Referenced by G4VEnergyLossProcess(), and SetStepFunction().
aGPILSelection
G4GPILSelection G4VEnergyLossProcess::aGPILSelection private
Definition at line 566 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepGetPhysicalInteractionLength(), G4VEnergyLossProcess(), and SetIonisation().
atomDeexcitation
G4VAtomDeexcitation* G4VEnergyLossProcess::atomDeexcitation private
Definition at line 453 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), BuildPhysicsTable(), and G4VEnergyLossProcess().
basedCoupleIndex
size_t G4VEnergyLossProcess::basedCoupleIndex private
Definition at line 558 of file G4VEnergyLossProcess.hh.
Referenced by DefineMaterial(), G4VEnergyLossProcess(), GetDEDXForScaledEnergy(), GetIonisationForScaledEnergy(), GetLambdaForScaledEnergy(), GetLimitScaledRangeForScaledEnergy(), GetScaledRangeForScaledEnergy(), GetSubDEDXForScaledEnergy(), GetSubIonisationForScaledEnergy(), and ScaledKinEnergyForLoss().
baseParticle
const G4ParticleDefinition* G4VEnergyLossProcess::baseParticle private
Definition at line 498 of file G4VEnergyLossProcess.hh.
Referenced by BaseParticle(), BuildPhysicsTable(), PreparePhysicsTable(), RetrievePhysicsTable(), SetBaseParticle(), StartTracking(), StorePhysicsTable(), and ~G4VEnergyLossProcess().
biasFactor
G4double G4VEnergyLossProcess::biasFactor private
Definition at line 512 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), CrossSectionBiasingFactor(), CrossSectionPerVolume(), DefineMaterial(), G4VEnergyLossProcess(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), SetCrossSectionBiasingFactor(), and SetDynamicMassCharge().
biasFlag
G4bool G4VEnergyLossProcess::biasFlag private
Definition at line 522 of file G4VEnergyLossProcess.hh.
Referenced by G4VEnergyLossProcess(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), and StartTracking().
biasID
G4int G4VEnergyLossProcess::biasID private
Definition at line 570 of file G4VEnergyLossProcess.hh.
Referenced by FillSecondariesAlongStep(), G4VEnergyLossProcess(), PostStepDoIt(), and PreparePhysicsTable().
biasManager
G4EmBiasingManager* G4VEnergyLossProcess::biasManager private
Definition at line 439 of file G4VEnergyLossProcess.hh.
Referenced by ActivateForcedInteraction(), ActivateSecondaryBiasing(), FillSecondariesAlongStep(), G4VEnergyLossProcess(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), StartTracking(), and ~G4VEnergyLossProcess().
chargeSqRatio
G4double G4VEnergyLossProcess::chargeSqRatio private
Definition at line 564 of file G4VEnergyLossProcess.hh.
Referenced by DefineMaterial(), G4VEnergyLossProcess(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), SampleSubCutSecondaries(), SetDynamicMassCharge(), and StartTracking().
computedRange
G4double G4VEnergyLossProcess::computedRange protected
Definition at line 542 of file G4VEnergyLossProcess.hh.
Referenced by G4VEnergyLossProcess(), and GetScaledRangeForScaledEnergy().
currentCouple
const G4MaterialCutsCouple* G4VEnergyLossProcess::currentCouple protected
Definition at line 537 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), DefineMaterial(), PostStepDoIt(), PreparePhysicsTable(), and SelectModel().
currentCoupleIndex
size_t G4VEnergyLossProcess::currentCoupleIndex protected
Definition at line 538 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), ComputeLambdaForScaledEnergy(), CrossSectionPerVolume(), CurrentMaterialCutsCoupleIndex(), DefineMaterial(), FillSecondariesAlongStep(), G4VEnergyLossProcess(), GetDEDXDispersion(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), SelectModel(), and SetDynamicMassCharge().
currentMaterial
const G4Material* G4VEnergyLossProcess::currentMaterial protected
Definition at line 536 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), CrossSectionPerVolume(), DefineMaterial(), G4VEnergyLossProcess(), GetDEDXDispersion(), and PostStepGetPhysicalInteractionLength().
currentModel
G4VEmModel* G4VEnergyLossProcess::currentModel private
Definition at line 557 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), CrossSectionPerVolume(), G4VEnergyLossProcess(), GetCurrentElement(), GetDEDXDispersion(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), and SelectModel().
dRoverRange
G4double G4VEnergyLossProcess::dRoverRange private
Definition at line 509 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepGetPhysicalInteractionLength(), G4VEnergyLossProcess(), SetStepFunction(), and StreamInfo().
emModels
std::vector<G4VEmModel*> G4VEnergyLossProcess::emModels private
Definition at line 451 of file G4VEnergyLossProcess.hh.
Referenced by EmModel(), and SetEmModel().
fFactor
G4double G4VEnergyLossProcess::fFactor private
Definition at line 562 of file G4VEnergyLossProcess.hh.
Referenced by ComputeLambdaForScaledEnergy(), DefineMaterial(), G4VEnergyLossProcess(), GetDEDXForScaledEnergy(), GetIonisationForScaledEnergy(), GetLambdaForScaledEnergy(), GetSubDEDXForScaledEnergy(), GetSubIonisationForScaledEnergy(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), and SetDynamicMassCharge().
finalRange
G4double G4VEnergyLossProcess::finalRange private
Definition at line 510 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepGetPhysicalInteractionLength(), G4VEnergyLossProcess(), SetStepFunction(), and StreamInfo().
fluctModel
G4VEmFluctuationModel* G4VEnergyLossProcess::fluctModel private
Definition at line 452 of file G4VEnergyLossProcess.hh.
Referenced by FluctModel(), G4VEnergyLossProcess(), and SetFluctModel().
fParticleChange
G4ParticleChangeForLoss G4VEnergyLossProcess::fParticleChange protected
Definition at line 535 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), FillSecondariesAlongStep(), G4VEnergyLossProcess(), and PostStepDoIt().
fRange
G4double G4VEnergyLossProcess::fRange protected
Definition at line 541 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), G4VEnergyLossProcess(), GetRange(), and PreparePhysicsTable().
idxCSDA
size_t G4VEnergyLossProcess::idxCSDA private
Definition at line 481 of file G4VEnergyLossProcess.hh.
Referenced by Clean(), G4VEnergyLossProcess(), GetLimitScaledRangeForScaledEnergy(), and SetCSDARangeTable().
idxDEDX
size_t G4VEnergyLossProcess::idxDEDX private
Definition at line 475 of file G4VEnergyLossProcess.hh.
Referenced by Clean(), G4VEnergyLossProcess(), and GetDEDXForScaledEnergy().
idxDEDXSub
size_t G4VEnergyLossProcess::idxDEDXSub private
Definition at line 476 of file G4VEnergyLossProcess.hh.
Referenced by Clean(), G4VEnergyLossProcess(), and GetSubDEDXForScaledEnergy().
idxDEDXunRestricted
size_t G4VEnergyLossProcess::idxDEDXunRestricted private
Definition at line 477 of file G4VEnergyLossProcess.hh.
Referenced by Clean(), G4VEnergyLossProcess(), and SetDEDXTable().
idxInverseRange
size_t G4VEnergyLossProcess::idxInverseRange private
Definition at line 483 of file G4VEnergyLossProcess.hh.
Referenced by Clean(), G4VEnergyLossProcess(), and ScaledKinEnergyForLoss().
idxIonisation
size_t G4VEnergyLossProcess::idxIonisation private
Definition at line 478 of file G4VEnergyLossProcess.hh.
Referenced by Clean(), G4VEnergyLossProcess(), and GetIonisationForScaledEnergy().
idxIonisationSub
size_t G4VEnergyLossProcess::idxIonisationSub private
Definition at line 479 of file G4VEnergyLossProcess.hh.
Referenced by Clean(), G4VEnergyLossProcess(), and GetSubIonisationForScaledEnergy().
idxLambda
size_t G4VEnergyLossProcess::idxLambda private
Definition at line 484 of file G4VEnergyLossProcess.hh.
Referenced by Clean(), DefineMaterial(), G4VEnergyLossProcess(), and GetLambdaForScaledEnergy().
idxRange
size_t G4VEnergyLossProcess::idxRange private
Definition at line 480 of file G4VEnergyLossProcess.hh.
Referenced by Clean(), G4VEnergyLossProcess(), and GetScaledRangeForScaledEnergy().
idxSCoffRegions
G4bool* G4VEnergyLossProcess::idxSCoffRegions private
Definition at line 457 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), Clean(), and PreparePhysicsTable().
idxSecRange
size_t G4VEnergyLossProcess::idxSecRange private
Definition at line 482 of file G4VEnergyLossProcess.hh.
Referenced by Clean(), and G4VEnergyLossProcess().
idxSubLambda
size_t G4VEnergyLossProcess::idxSubLambda private
Definition at line 485 of file G4VEnergyLossProcess.hh.
Referenced by Clean(), DefineMaterial(), G4VEnergyLossProcess(), and SampleSubCutSecondaries().
integral
G4bool G4VEnergyLossProcess::integral private
Definition at line 517 of file G4VEnergyLossProcess.hh.
Referenced by IsIntegral(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), SetIntegral(), and StreamInfo().
isIon
G4bool G4VEnergyLossProcess::isIon private
Definition at line 518 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), BuildPhysicsTable(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), and StartTracking().
isIonisation
G4bool G4VEnergyLossProcess::isIonisation private
Definition at line 519 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), BuildPhysicsTable(), IsIonisationProcess(), PreparePhysicsTable(), SetIonisation(), StorePhysicsTable(), StreamInfo(), and ~G4VEnergyLossProcess().
isMaster
G4bool G4VEnergyLossProcess::isMaster private
Definition at line 524 of file G4VEnergyLossProcess.hh.
Referenced by BuildPhysicsTable(), G4VEnergyLossProcess(), PreparePhysicsTable(), RetrievePhysicsTable(), StorePhysicsTable(), and ~G4VEnergyLossProcess().
lambdaFactor
G4double G4VEnergyLossProcess::lambdaFactor private
Definition at line 511 of file G4VEnergyLossProcess.hh.
Referenced by ComputeLambdaForScaledEnergy(), G4VEnergyLossProcess(), and PreparePhysicsTable().
lastIdx
size_t G4VEnergyLossProcess::lastIdx private
Definition at line 559 of file G4VEnergyLossProcess.hh.
Referenced by G4VEnergyLossProcess(), GetScaledRangeForScaledEnergy(), and PreparePhysicsTable().
linLossLimit
G4double G4VEnergyLossProcess::linLossLimit private
Definition at line 508 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), G4VEnergyLossProcess(), PreparePhysicsTable(), SetLinearLossLimit(), and StreamInfo().
lManager
G4LossTableManager* G4VEnergyLossProcess::lManager private
Definition at line 437 of file G4VEnergyLossProcess.hh.
Referenced by BuildDEDXTable(), BuildLambdaTable(), BuildPhysicsTable(), G4VEnergyLossProcess(), PreparePhysicsTable(), SetDEDXTable(), SetLambdaTable(), and ~G4VEnergyLossProcess().
lossFluctuationFlag
G4bool G4VEnergyLossProcess::lossFluctuationFlag private
Definition at line 514 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), PreparePhysicsTable(), SetLossFluctuations(), and StreamInfo().
lowestKinEnergy
G4double G4VEnergyLossProcess::lowestKinEnergy private
Definition at line 503 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), G4VEnergyLossProcess(), PostStepDoIt(), PreparePhysicsTable(), and SetLowestEnergyLimit().
massRatio
G4double G4VEnergyLossProcess::massRatio private
Definition at line 561 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), CrossSectionPerVolume(), DefineMaterial(), G4VEnergyLossProcess(), GetCSDARange(), GetDEDX(), GetDEDXDispersion(), GetDEDXForSubsec(), GetKineticEnergy(), GetLambda(), GetRange(), GetRangeForLoss(), MeanFreePath(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), SampleSubCutSecondaries(), SetDynamicMassCharge(), and StartTracking().
maxKinEnergy
G4double G4VEnergyLossProcess::maxKinEnergy private
Definition at line 505 of file G4VEnergyLossProcess.hh.
Referenced by BuildDEDXTable(), BuildLambdaTable(), G4VEnergyLossProcess(), LambdaPhysicsVector(), MaxKinEnergy(), PreparePhysicsTable(), PrintWarning(), SetMaxKinEnergy(), SetMinKinEnergy(), and StreamInfo().
maxKinEnergyCSDA
G4double G4VEnergyLossProcess::maxKinEnergyCSDA private
Definition at line 506 of file G4VEnergyLossProcess.hh.
Referenced by BuildDEDXTable(), G4VEnergyLossProcess(), GetLimitScaledRangeForScaledEnergy(), PreparePhysicsTable(), SetCSDARangeTable(), SetDEDXTable(), SetMaxKinEnergy(), and StreamInfo().
mfpKinEnergy
G4double G4VEnergyLossProcess::mfpKinEnergy protected
Definition at line 546 of file G4VEnergyLossProcess.hh.
Referenced by ComputeLambdaForScaledEnergy(), DefineMaterial(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), and StartTracking().
minKinEnergy
G4double G4VEnergyLossProcess::minKinEnergy private
Definition at line 504 of file G4VEnergyLossProcess.hh.
Referenced by BuildDEDXTable(), BuildLambdaTable(), G4VEnergyLossProcess(), GetDEDXForScaledEnergy(), GetIonisationForScaledEnergy(), GetLimitScaledRangeForScaledEnergy(), GetScaledRangeForScaledEnergy(), GetSubDEDXForScaledEnergy(), GetSubIonisationForScaledEnergy(), LambdaPhysicsVector(), MinKinEnergy(), PreparePhysicsTable(), PrintWarning(), ScaledKinEnergyForLoss(), SetMaxKinEnergy(), SetMinKinEnergy(), and StreamInfo().
modelManager
G4EmModelManager* G4VEnergyLossProcess::modelManager private
Definition at line 438 of file G4VEnergyLossProcess.hh.
Referenced by AddEmModel(), BuildDEDXTable(), BuildLambdaTable(), BuildPhysicsTable(), G4VEnergyLossProcess(), GetModelByIndex(), NumberOfModels(), PreparePhysicsTable(), SelectModel(), SelectModelForMaterial(), StreamInfo(), UpdateEmModel(), and ~G4VEnergyLossProcess().
nBins
G4int G4VEnergyLossProcess::nBins private
Definition at line 500 of file G4VEnergyLossProcess.hh.
Referenced by BuildDEDXTable(), BuildLambdaTable(), G4VEnergyLossProcess(), LambdaPhysicsVector(), PreparePhysicsTable(), PrintWarning(), SetDEDXBinning(), and StreamInfo().
nBinsCSDA
G4int G4VEnergyLossProcess::nBinsCSDA private
Definition at line 501 of file G4VEnergyLossProcess.hh.
Referenced by BuildDEDXTable(), G4VEnergyLossProcess(), PreparePhysicsTable(), and StreamInfo().
nProcesses
G4int G4VEnergyLossProcess::nProcesses private
Definition at line 460 of file G4VEnergyLossProcess.hh.
Referenced by AddCollaborativeProcess(), and Clean().
nSCoffRegions
G4int G4VEnergyLossProcess::nSCoffRegions private
Definition at line 456 of file G4VEnergyLossProcess.hh.
Referenced by ActivateSubCutoff(), BuildPhysicsTable(), NumberOfSubCutoffRegions(), PreparePhysicsTable(), RetrievePhysicsTable(), and StreamInfo().
particle
const G4ParticleDefinition* G4VEnergyLossProcess::particle private
Definition at line 555 of file G4VEnergyLossProcess.hh.
Referenced by BuildDEDXTable(), BuildLambdaTable(), BuildPhysicsTable(), CrossSectionPerVolume(), Particle(), PostStepDoIt(), PreparePhysicsTable(), ProcessDescription(), RetrievePhysicsTable(), SetInverseRangeTable(), SetLambdaTable(), SetParticle(), SetRangeTableForLoss(), SetSecondaryRangeTable(), SetSubLambdaTable(), and StorePhysicsTable().
preStepKinEnergy
G4double G4VEnergyLossProcess::preStepKinEnergy protected
Definition at line 543 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), G4VEnergyLossProcess(), PostStepGetPhysicalInteractionLength(), and PreparePhysicsTable().
preStepLambda
G4double G4VEnergyLossProcess::preStepLambda protected
Definition at line 540 of file G4VEnergyLossProcess.hh.
Referenced by ComputeLambdaForScaledEnergy(), G4VEnergyLossProcess(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), and PreparePhysicsTable().
preStepRangeEnergy
G4double G4VEnergyLossProcess::preStepRangeEnergy protected
Definition at line 545 of file G4VEnergyLossProcess.hh.
Referenced by G4VEnergyLossProcess(), GetScaledRangeForScaledEnergy(), PreparePhysicsTable(), and StartTracking().
preStepScaledEnergy
G4double G4VEnergyLossProcess::preStepScaledEnergy protected
Definition at line 544 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), G4VEnergyLossProcess(), and PostStepGetPhysicalInteractionLength().
reduceFactor
G4double G4VEnergyLossProcess::reduceFactor private
Definition at line 563 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), DefineMaterial(), G4VEnergyLossProcess(), GetCSDARange(), GetKineticEnergy(), GetRange(), GetRangeForLoss(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), and SetDynamicMassCharge().
rndmStepFlag
G4bool G4VEnergyLossProcess::rndmStepFlag private
Definition at line 515 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepGetPhysicalInteractionLength(), and PreparePhysicsTable().
safetyHelper
G4SafetyHelper* G4VEnergyLossProcess::safetyHelper private
Definition at line 440 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), BuildPhysicsTable(), and G4VEnergyLossProcess().
scoffRegions
std::vector<const G4Region*> G4VEnergyLossProcess::scoffRegions private
Definition at line 455 of file G4VEnergyLossProcess.hh.
Referenced by ActivateSubCutoff(), and PreparePhysicsTable().
scProcesses
std::vector<G4VEnergyLossProcess*> G4VEnergyLossProcess::scProcesses private
Definition at line 459 of file G4VEnergyLossProcess.hh.
Referenced by AddCollaborativeProcess(), and Clean().
scTracks
std::vector<G4Track*> G4VEnergyLossProcess::scTracks private
Definition at line 553 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), FillSecondariesAlongStep(), and G4VEnergyLossProcess().
secID
G4int G4VEnergyLossProcess::secID private
Definition at line 568 of file G4VEnergyLossProcess.hh.
Referenced by G4VEnergyLossProcess(), PostStepDoIt(), and PreparePhysicsTable().
secondaryParticle
const G4ParticleDefinition* G4VEnergyLossProcess::secondaryParticle private
Definition at line 443 of file G4VEnergyLossProcess.hh.
Referenced by ActivateSecondaryBiasing(), PreparePhysicsTable(), SecondaryParticle(), and SetSecondaryParticle().
secParticles
std::vector<G4DynamicParticle*> G4VEnergyLossProcess::secParticles private
Definition at line 552 of file G4VEnergyLossProcess.hh.
Referenced by G4VEnergyLossProcess(), PostStepDoIt(), and SampleSubCutSecondaries().
subcutProducer
G4VSubCutProducer* G4VEnergyLossProcess::subcutProducer private
Definition at line 454 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), BuildPhysicsTable(), and G4VEnergyLossProcess().
subsecID
G4int G4VEnergyLossProcess::subsecID private
Definition at line 569 of file G4VEnergyLossProcess.hh.
Referenced by G4VEnergyLossProcess(), PreparePhysicsTable(), and SampleSubCutSecondaries().
tablesAreBuilt
G4bool G4VEnergyLossProcess::tablesAreBuilt private
Definition at line 516 of file G4VEnergyLossProcess.hh.
Referenced by BuildPhysicsTable(), Clean(), RetrievePhysicsTable(), SetLambdaTable(), and TablesAreBuilt().
theCrossSectionMax
std::vector<G4double> G4VEnergyLossProcess::theCrossSectionMax private
Definition at line 490 of file G4VEnergyLossProcess.hh.
Referenced by ComputeLambdaForScaledEnergy(), PreparePhysicsTable(), and SetLambdaTable().
theCSDARangeTable
G4PhysicsTable* G4VEnergyLossProcess::theCSDARangeTable private
Definition at line 469 of file G4VEnergyLossProcess.hh.
Referenced by CSDARangeTable(), GetCSDARange(), GetRange(), PreparePhysicsTable(), RetrievePhysicsTable(), SetCSDARangeTable(), StorePhysicsTable(), StreamInfo(), and ~G4VEnergyLossProcess().
theCuts
const G4DataVector* G4VEnergyLossProcess::theCuts private
Definition at line 495 of file G4VEnergyLossProcess.hh.
Referenced by CrossSectionPerVolume(), G4VEnergyLossProcess(), GetDEDXDispersion(), and PreparePhysicsTable().
theDEDXAtMaxEnergy
std::vector<G4double> G4VEnergyLossProcess::theDEDXAtMaxEnergy private
Definition at line 487 of file G4VEnergyLossProcess.hh.
Referenced by GetLimitScaledRangeForScaledEnergy(), PreparePhysicsTable(), and SetDEDXTable().
theDEDXSubTable
G4PhysicsTable* G4VEnergyLossProcess::theDEDXSubTable private
Definition at line 464 of file G4VEnergyLossProcess.hh.
Referenced by BuildDEDXTable(), DEDXTableForSubsec(), PreparePhysicsTable(), RetrievePhysicsTable(), SetDEDXTable(), StorePhysicsTable(), StreamInfo(), and ~G4VEnergyLossProcess().
theDEDXTable
G4PhysicsTable* G4VEnergyLossProcess::theDEDXTable private
Definition at line 463 of file G4VEnergyLossProcess.hh.
Referenced by BuildDEDXTable(), DEDXTable(), PreparePhysicsTable(), RetrievePhysicsTable(), SetDEDXTable(), StorePhysicsTable(), StreamInfo(), and ~G4VEnergyLossProcess().
theDEDXunRestrictedTable
G4PhysicsTable* G4VEnergyLossProcess::theDEDXunRestrictedTable private
Definition at line 465 of file G4VEnergyLossProcess.hh.
Referenced by BuildDEDXTable(), DEDXunRestrictedTable(), PreparePhysicsTable(), RetrievePhysicsTable(), SetDEDXTable(), StorePhysicsTable(), StreamInfo(), and ~G4VEnergyLossProcess().
theDensityFactor
const std::vector<G4double>* G4VEnergyLossProcess::theDensityFactor private
Definition at line 492 of file G4VEnergyLossProcess.hh.
Referenced by BuildLambdaTable(), BuildPhysicsTable(), SetDEDXTable(), and SetLambdaTable().
theDensityIdx
const std::vector<G4int>* G4VEnergyLossProcess::theDensityIdx private
Definition at line 493 of file G4VEnergyLossProcess.hh.
Referenced by BuildLambdaTable(), BuildPhysicsTable(), SetDEDXTable(), and SetLambdaTable().
theElectron
const G4ParticleDefinition* G4VEnergyLossProcess::theElectron private
Definition at line 444 of file G4VEnergyLossProcess.hh.
Referenced by G4VEnergyLossProcess().
theEnergyOfCrossSectionMax
std::vector<G4double> G4VEnergyLossProcess::theEnergyOfCrossSectionMax private
Definition at line 489 of file G4VEnergyLossProcess.hh.
Referenced by ComputeLambdaForScaledEnergy(), PreparePhysicsTable(), and SetLambdaTable().
theGamma
const G4ParticleDefinition* G4VEnergyLossProcess::theGamma private
Definition at line 446 of file G4VEnergyLossProcess.hh.
Referenced by G4VEnergyLossProcess().
theGenericIon
const G4ParticleDefinition* G4VEnergyLossProcess::theGenericIon private
Definition at line 447 of file G4VEnergyLossProcess.hh.
Referenced by G4VEnergyLossProcess(), PreparePhysicsTable(), and StartTracking().
theInverseRangeTable
G4PhysicsTable* G4VEnergyLossProcess::theInverseRangeTable private
Definition at line 471 of file G4VEnergyLossProcess.hh.
Referenced by InverseRangeTable(), PreparePhysicsTable(), RetrievePhysicsTable(), SetInverseRangeTable(), StorePhysicsTable(), StreamInfo(), and ~G4VEnergyLossProcess().
theIonisationSubTable
G4PhysicsTable* G4VEnergyLossProcess::theIonisationSubTable private
Definition at line 467 of file G4VEnergyLossProcess.hh.
Referenced by IonisationTableForSubsec(), PreparePhysicsTable(), RetrievePhysicsTable(), SetDEDXTable(), StorePhysicsTable(), and ~G4VEnergyLossProcess().
theIonisationTable
G4PhysicsTable* G4VEnergyLossProcess::theIonisationTable private
Definition at line 466 of file G4VEnergyLossProcess.hh.
Referenced by IonisationTable(), PreparePhysicsTable(), SetDEDXTable(), StorePhysicsTable(), and ~G4VEnergyLossProcess().
theLambdaTable
G4PhysicsTable* G4VEnergyLossProcess::theLambdaTable private
Definition at line 472 of file G4VEnergyLossProcess.hh.
Referenced by BuildLambdaTable(), CrossSectionPerVolume(), GetLambda(), LambdaTable(), PreparePhysicsTable(), RetrievePhysicsTable(), SetLambdaTable(), StorePhysicsTable(), StreamInfo(), and ~G4VEnergyLossProcess().
theParameters
G4EmParameters* G4VEnergyLossProcess::theParameters private
Definition at line 441 of file G4VEnergyLossProcess.hh.
Referenced by BuildDEDXTable(), BuildLambdaTable(), G4VEnergyLossProcess(), LambdaPhysicsVector(), PreparePhysicsTable(), RetrieveTable(), and StreamInfo().
thePositron
const G4ParticleDefinition* G4VEnergyLossProcess::thePositron private
Definition at line 445 of file G4VEnergyLossProcess.hh.
Referenced by G4VEnergyLossProcess(), and SampleSubCutSecondaries().
theRangeAtMaxEnergy
std::vector<G4double> G4VEnergyLossProcess::theRangeAtMaxEnergy private
Definition at line 488 of file G4VEnergyLossProcess.hh.
Referenced by GetLimitScaledRangeForScaledEnergy(), PreparePhysicsTable(), and SetCSDARangeTable().
theRangeTableForLoss
G4PhysicsTable* G4VEnergyLossProcess::theRangeTableForLoss private
Definition at line 468 of file G4VEnergyLossProcess.hh.
Referenced by GetRange(), PreparePhysicsTable(), RangeTableForLoss(), RetrievePhysicsTable(), SetRangeTableForLoss(), StorePhysicsTable(), StreamInfo(), and ~G4VEnergyLossProcess().
theSecondaryRangeTable
G4PhysicsTable* G4VEnergyLossProcess::theSecondaryRangeTable private
Definition at line 470 of file G4VEnergyLossProcess.hh.
Referenced by SecondaryRangeTable(), and SetSecondaryRangeTable().
theSubCuts
const G4DataVector* G4VEnergyLossProcess::theSubCuts private
Definition at line 496 of file G4VEnergyLossProcess.hh.
Referenced by G4VEnergyLossProcess(), and PreparePhysicsTable().
theSubLambdaTable
G4PhysicsTable* G4VEnergyLossProcess::theSubLambdaTable private
Definition at line 473 of file G4VEnergyLossProcess.hh.
Referenced by BuildLambdaTable(), PreparePhysicsTable(), RetrievePhysicsTable(), SetSubLambdaTable(), StorePhysicsTable(), StreamInfo(), SubLambdaTable(), and ~G4VEnergyLossProcess().
useDeexcitation
G4bool G4VEnergyLossProcess::useDeexcitation private
Definition at line 521 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), and BuildPhysicsTable().
useSubCutoff
G4bool G4VEnergyLossProcess::useSubCutoff private
Definition at line 520 of file G4VEnergyLossProcess.hh.
Referenced by AlongStepDoIt(), and PreparePhysicsTable().
weightFlag
G4bool G4VEnergyLossProcess::weightFlag private
Definition at line 523 of file G4VEnergyLossProcess.hh.
Referenced by ActivateForcedInteraction(), AlongStepDoIt(), G4VEnergyLossProcess(), PostStepDoIt(), and SetCrossSectionBiasingFactor().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/utils/include/G4VEnergyLossProcess.hh
source/processes/electromagnetic/utils/src/G4VEnergyLossProcess.cc