Geant4: G4RDVDataSetAlgorithm Class Reference
G4RDVDataSetAlgorithm Class Reference abstract
#include <G4RDVDataSetAlgorithm.hh>
Public Member Functions
G4RDVDataSetAlgorithm ()
virtual ~G4RDVDataSetAlgorithm ()
virtual G4double Calculate (G4double point, G4int bin, const G4DataVector &energies, const G4DataVector &data) const =0
virtual G4RDVDataSetAlgorithm * Clone () const =0
Private Member Functions
G4RDVDataSetAlgorithm (const G4RDVDataSetAlgorithm &)
G4RDVDataSetAlgorithm & operator= (const G4RDVDataSetAlgorithm &right)
Detailed Description
Definition at line 47 of file G4RDVDataSetAlgorithm.hh.
Constructor & Destructor Documentation
G4RDVDataSetAlgorithm() [1/2]
G4RDVDataSetAlgorithm::G4RDVDataSetAlgorithm () inline
Definition at line 51 of file G4RDVDataSetAlgorithm.hh.
~G4RDVDataSetAlgorithm()
virtual G4RDVDataSetAlgorithm::~G4RDVDataSetAlgorithm () inline virtual
Definition at line 53 of file G4RDVDataSetAlgorithm.hh.
G4RDVDataSetAlgorithm() [2/2]
G4RDVDataSetAlgorithm::G4RDVDataSetAlgorithm (const G4RDVDataSetAlgorithm &) private
Member Function Documentation
Calculate()
virtual G4double G4RDVDataSetAlgorithm::Calculate (G4double point, G4int bin, const G4DataVector & energies, const G4DataVector & data) const pure virtual
Implemented in G4RDLinInterpolation, G4RDLogLogInterpolation, G4RDSemiLogInterpolation, G4RDLinLogInterpolation, and G4RDLinLogLogInterpolation.
Referenced by G4RDEMDataSet::FindValue(), G4RDEMDataSet::IntegrationFunction(), and G4RDEMDataSet::RandomSelect().
Clone()
virtual G4RDVDataSetAlgorithm* G4RDVDataSetAlgorithm::Clone () const pure virtual
Implemented in G4RDLinInterpolation, G4RDLogLogInterpolation, G4RDSemiLogInterpolation, G4RDLinLogInterpolation, and G4RDLinLogLogInterpolation.
Referenced by G4RDCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDBremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDeIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDCompositeEMDataSet::LoadData(), G4RDShellEMDataSet::LoadData(), G4RDVCrossSectionHandler::LoadData(), G4RDDopplerProfile::LoadProfile(), and G4RDVCrossSectionHandler::LoadShellData().
operator=()
G4RDVDataSetAlgorithm& G4RDVDataSetAlgorithm::operator= (const G4RDVDataSetAlgorithm & right) private
The documentation for this class was generated from the following file:
examples/advanced/eRosita/physics/include/G4RDVDataSetAlgorithm.hh