Geant4: G4tgbElement Class Reference
G4tgbElement Class Reference
#include <G4tgbElement.hh>
Public Member Functions
G4tgbElement ()
~G4tgbElement ()
G4tgbElement (G4tgrElement *hg)
G4Element * BuildG4ElementSimple ()
G4Element * BuildG4ElementFromIsotopes ()
const G4String & GetName () const
const G4String & GetType () const
Private Attributes
G4tgrElement * theTgrElem
G4Element * theG4Elem
Detailed Description
Definition at line 52 of file G4tgbElement.hh.
Constructor & Destructor Documentation
G4tgbElement() [1/2]
G4tgbElement::G4tgbElement () inline
Definition at line 57 of file G4tgbElement.hh.
~G4tgbElement()
G4tgbElement::~G4tgbElement () inline
Definition at line 58 of file G4tgbElement.hh.
G4tgbElement() [2/2]
G4tgbElement::G4tgbElement (G4tgrElement * hg)
Definition at line 43 of file G4tgbElement.cc.
Member Function Documentation
BuildG4ElementFromIsotopes()
G4Element * G4tgbElement::BuildG4ElementFromIsotopes ()
Definition at line 82 of file G4tgbElement.cc.
Referenced by G4tgbMaterialMgr::FindOrBuildG4Element().
BuildG4ElementSimple()
G4Element * G4tgbElement::BuildG4ElementSimple ()
Definition at line 51 of file G4tgbElement.cc.
Referenced by G4tgbMaterialMgr::FindOrBuildG4Element().
GetName()
const G4String& G4tgbElement::GetName (void) const inline
Definition at line 67 of file G4tgbElement.hh.
Referenced by G4tgbMaterialMgr::CopyElements().
GetType()
const G4String& G4tgbElement::GetType () const inline
Definition at line 71 of file G4tgbElement.hh.
Referenced by G4tgbMaterialMgr::FindOrBuildG4Element().
Field Documentation
theG4Elem
G4Element* G4tgbElement::theG4Elem private
Definition at line 79 of file G4tgbElement.hh.
Referenced by BuildG4ElementFromIsotopes(), BuildG4ElementSimple(), and G4tgbElement().
theTgrElem
G4tgrElement* G4tgbElement::theTgrElem private
Definition at line 78 of file G4tgbElement.hh.
Referenced by BuildG4ElementFromIsotopes(), BuildG4ElementSimple(), G4tgbElement(), GetName(), and GetType().
The documentation for this class was generated from the following files:
source/persistency/ascii/include/G4tgbElement.hh
source/persistency/ascii/src/G4tgbElement.cc