Geant4: source/processes/hadronic/models/lend/src/xDataTOM_KalbachMann.cc File Reference
xDataTOM_KalbachMann.cc File Reference
#include <string.h>
#include "xDataTOM_private.h"
Functions
int xDataTOM_KalbachMann_initialize (statusMessageReporting *smr, xDataTOM_KalbachMann *KalbachMann, int length, xDataTOM_axes *axes)
int xDataTOM_KalbachMann_free (xDataTOM_xDataInfo *xDI)
int xDataTOM_KalbachMann_release (xDataTOM_KalbachMann *KalbachMann)
Variables
const char * xDataTOM_KalbachMann_ID = "KalbachMann"
Function Documentation
xDataTOM_KalbachMann_free()
int xDataTOM_KalbachMann_free (xDataTOM_xDataInfo * xDI)
Definition at line 35 of file xDataTOM_KalbachMann.cc.
Referenced by xDataTOM_releaseElement().
xDataTOM_KalbachMann_initialize()
int xDataTOM_KalbachMann_initialize (statusMessageReporting * smr, xDataTOM_KalbachMann * KalbachMann, int length, xDataTOM_axes * axes)
Definition at line 19 of file xDataTOM_KalbachMann.cc.
Referenced by xDataXML_KalbachMannToTOM().
xDataTOM_KalbachMann_release()
int xDataTOM_KalbachMann_release (xDataTOM_KalbachMann * KalbachMann)
Definition at line 46 of file xDataTOM_KalbachMann.cc.
Referenced by xDataTOM_KalbachMann_free().
Variable Documentation
xDataTOM_KalbachMann_ID
const char* xDataTOM_KalbachMann_ID = "KalbachMann"
Definition at line 14 of file xDataTOM_KalbachMann.cc.
Referenced by xDataTOM_KalbachMann_free(), xDataTOM_releaseElement(), xDataXML_constructTOM(), and xDataXML_KalbachMannToTOM().