Geant4: G4Navigator Class Reference
G4Navigator Class Reference
#include <G4Navigator.hh>
Data Structures
struct G4SaveNavigatorState
Public Member Functions
G4Navigator ()
virtual ~G4Navigator ()
virtual G4double ComputeStep (const G4ThreeVector &pGlobalPoint, const G4ThreeVector &pDirection, const G4double pCurrentProposedStepLength, G4double &pNewSafety)
G4double CheckNextStep (const G4ThreeVector &pGlobalPoint, const G4ThreeVector &pDirection, const G4double pCurrentProposedStepLength, G4double &pNewSafety)
virtual G4VPhysicalVolume * ResetHierarchyAndLocate (const G4ThreeVector &point, const G4ThreeVector &direction, const G4TouchableHistory &h)
virtual G4VPhysicalVolume * LocateGlobalPointAndSetup (const G4ThreeVector &point, const G4ThreeVector *direction=0, const G4bool pRelativeSearch=true, const G4bool ignoreDirection=true)
virtual void LocateGlobalPointWithinVolume (const G4ThreeVector &position)
void LocateGlobalPointAndUpdateTouchableHandle (const G4ThreeVector &position, const G4ThreeVector &direction, G4TouchableHandle &oldTouchableToUpdate, const G4bool RelativeSearch=true)
void LocateGlobalPointAndUpdateTouchable (const G4ThreeVector &position, const G4ThreeVector &direction, G4VTouchable *touchableToUpdate, const G4bool RelativeSearch=true)
void LocateGlobalPointAndUpdateTouchable (const G4ThreeVector &position, G4VTouchable *touchableToUpdate, const G4bool RelativeSearch=true)
void SetGeometricallyLimitedStep ()
virtual G4double ComputeSafety (const G4ThreeVector &globalpoint, const G4double pProposedMaxLength=DBL_MAX, const G4bool keepState=true)
virtual G4bool RecheckDistanceToCurrentBoundary (const G4ThreeVector &pGlobalPoint, const G4ThreeVector &pDirection, const G4double CurrentProposedStepLength, G4double *prDistance, G4double *prNewSafety=0) const
G4VPhysicalVolume * GetWorldVolume () const
void SetWorldVolume (G4VPhysicalVolume *pWorld)
G4GRSVolume * CreateGRSVolume () const
G4GRSSolid * CreateGRSSolid () const
G4TouchableHistory * CreateTouchableHistory () const
G4TouchableHistory * CreateTouchableHistory (const G4NavigationHistory *) const
virtual G4TouchableHistoryHandle CreateTouchableHistoryHandle () const
virtual G4ThreeVector GetLocalExitNormal (G4bool *valid)
virtual G4ThreeVector GetLocalExitNormalAndCheck (const G4ThreeVector &point, G4bool *valid)
virtual G4ThreeVector GetGlobalExitNormal (const G4ThreeVector &point, G4bool *valid)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int level)
G4bool IsActive () const
void Activate (G4bool flag)
G4bool EnteredDaughterVolume () const
G4bool ExitedMotherVolume () const
void CheckMode (G4bool mode)
G4bool IsCheckModeActive () const
void SetPushVerbosity (G4bool mode)
void PrintState () const
const G4AffineTransform & GetGlobalToLocalTransform () const
const G4AffineTransform GetLocalToGlobalTransform () const
G4AffineTransform GetMotherToDaughterTransform (G4VPhysicalVolume *dVolume, G4int dReplicaNo, EVolume dVolumeType)
void ResetStackAndState ()
G4int SeverityOfZeroStepping (G4int *noZeroSteps) const
G4ThreeVector GetCurrentLocalCoordinate () const
G4ThreeVector NetTranslation () const
G4RotationMatrix NetRotation () const
void EnableBestSafety (G4bool value=false)
Protected Member Functions
void SetSavedState ()
void RestoreSavedState ()
virtual void ResetState ()
G4ThreeVector ComputeLocalPoint (const G4ThreeVector &rGlobPoint) const
G4ThreeVector ComputeLocalAxis (const G4ThreeVector &pVec) const
EVolume VolumeType (const G4VPhysicalVolume *pVol) const
EVolume CharacteriseDaughters (const G4LogicalVolume *pLog) const
G4int GetDaughtersRegularStructureId (const G4LogicalVolume *pLog) const
virtual void SetupHierarchy ()
Protected Attributes
G4double kCarTolerance
G4double fMinStep
G4double fSqTol
G4NavigationHistory fHistory
G4bool fEnteredDaughter
G4bool fExitedMother
G4bool fWasLimitedByGeometry
G4ThreeVector fStepEndPoint
G4ThreeVector fLastStepEndPointLocal
G4int fVerbose
Private Member Functions
G4Navigator (const G4Navigator &)
G4Navigator & operator= (const G4Navigator &)
void ComputeStepLog (const G4ThreeVector &pGlobalpoint, G4double moveLenSq) const
Private Attributes
G4bool fActive
G4bool fLastTriedStepComputation
G4bool fEntering
G4bool fExiting
G4VPhysicalVolume * fBlockedPhysicalVolume
G4int fBlockedReplicaNo
G4ThreeVector fLastLocatedPointLocal
G4bool fLocatedOutsideWorld
G4bool fValidExitNormal
G4ThreeVector fExitNormal
G4ThreeVector fGrandMotherExitNormal
G4bool fChangedGrandMotherRefFrame
G4ThreeVector fExitNormalGlobalFrame
G4bool fCalculatedExitNormal
G4bool fLastStepWasZero
G4bool fLocatedOnEdge
G4int fNumberZeroSteps
G4int fActionThreshold_NoZeroSteps
G4int fAbandonThreshold_NoZeroSteps
G4ThreeVector fPreviousSftOrigin
G4double fPreviousSafety
struct G4Navigator::G4SaveNavigatorState fSaveState
G4VPhysicalVolume * fTopPhysical
G4bool fCheck
G4bool fPushed
G4bool fWarnPush
G4NormalNavigation fnormalNav
G4VoxelNavigation fvoxelNav
G4ParameterisedNavigation fparamNav
G4ReplicaNavigation freplicaNav
G4RegularNavigation fregularNav
G4VoxelSafety * fpVoxelSafety
Friends
std::ostream & operator<< (std::ostream &os, const G4Navigator &n)
Detailed Description
Definition at line 72 of file G4Navigator.hh.
Constructor & Destructor Documentation
G4Navigator() [1/2]
G4Navigator::G4Navigator ()
Definition at line 57 of file G4Navigator.cc.
~G4Navigator()
G4Navigator::~G4Navigator () virtual
Definition at line 90 of file G4Navigator.cc.
G4Navigator() [2/2]
G4Navigator::G4Navigator (const G4Navigator &) private
Member Function Documentation
Activate()
void G4Navigator::Activate (G4bool flag) inline
Referenced by G4TransportationManager::ActivateNavigator(), and G4TransportationManager::G4TransportationManager().
CharacteriseDaughters()
EVolume G4Navigator::CharacteriseDaughters (const G4LogicalVolume * pLog) const inline protected
Referenced by ComputeSafety(), ComputeStep(), LocateGlobalPointAndSetup(), and LocateGlobalPointWithinVolume().
CheckMode()
void G4Navigator::CheckMode (G4bool mode) inline
Referenced by G4VIntersectionLocator::LocateGlobalPointWithinVolumeAndCheck(), and G4GeometryMessenger::SetCheckMode().
CheckNextStep()
G4double G4Navigator::CheckNextStep (const G4ThreeVector & pGlobalPoint, const G4ThreeVector & pDirection, const G4double pCurrentProposedStepLength, G4double & pNewSafety)
Definition at line 1201 of file G4Navigator.cc.
Referenced by G4SafetyHelper::CheckNextStep().
ComputeLocalAxis()
G4ThreeVector G4Navigator::ComputeLocalAxis (const G4ThreeVector & pVec) const inline protected
Referenced by ComputeStep(), and RecheckDistanceToCurrentBoundary().
ComputeLocalPoint()
G4ThreeVector G4Navigator::ComputeLocalPoint (const G4ThreeVector & rGlobPoint) const inline protected
Referenced by ComputeSafety(), ComputeStep(), LocateGlobalPointWithinVolume(), and RecheckDistanceToCurrentBoundary().
ComputeSafety()
G4double G4Navigator::ComputeSafety (const G4ThreeVector & globalpoint, const G4double pProposedMaxLength = DBL_MAX, const G4bool keepState = true) virtual
Reimplemented in G4ErrorPropagationNavigator, and G4MultiNavigator.
Definition at line 1752 of file G4Navigator.cc.
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4WeightCutOffProcess::AlongStepGetPhysicalInteractionLength(), G4ParallelWorldProcess::AlongStepGetPhysicalInteractionLength(), G4ImportanceProcess::AlongStepGetPhysicalInteractionLength(), G4ParallelWorldScoringProcess::AlongStepGetPhysicalInteractionLength(), G4WeightWindowProcess::AlongStepGetPhysicalInteractionLength(), G4FastSimulationManagerProcess::AlongStepGetPhysicalInteractionLength(), G4ErrorPropagationNavigator::ComputeSafety(), G4SafetyHelper::ComputeSafety(), and G4PathFinder::DoNextCurvedStep().
ComputeStep()
G4double G4Navigator::ComputeStep (const G4ThreeVector & pGlobalPoint, const G4ThreeVector & pDirection, const G4double pCurrentProposedStepLength, G4double & pNewSafety) virtual
Reimplemented in G4MultiNavigator, and G4ErrorPropagationNavigator.
Definition at line 752 of file G4Navigator.cc.
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), CheckNextStep(), G4AdjointPrimaryGenerator::ComputeAccumulatedDepthVectorAlongBackRay(), and G4ErrorPropagationNavigator::ComputeStep().
ComputeStepLog()
void G4Navigator::ComputeStepLog (const G4ThreeVector & pGlobalpoint, G4double moveLenSq) const private
Definition at line 2150 of file G4Navigator.cc.
Referenced by ComputeStep().
CreateGRSSolid()
G4GRSSolid* G4Navigator::CreateGRSSolid () const inline
CreateGRSVolume()
G4GRSVolume* G4Navigator::CreateGRSVolume () const inline
CreateTouchableHistory() [1/2]
G4TouchableHistory* G4Navigator::CreateTouchableHistory () const inline
Referenced by G4MultiNavigator::CreateTouchableHistoryHandle(), CreateTouchableHistoryHandle(), G4VIntersectionLocator::GetLocalSurfaceNormal(), and G4SteppingManager::SetInitialStep().
CreateTouchableHistory() [2/2]
G4TouchableHistory* G4Navigator::CreateTouchableHistory (const G4NavigationHistory *) const inline
CreateTouchableHistoryHandle()
G4TouchableHistoryHandle G4Navigator::CreateTouchableHistoryHandle () const virtual
Reimplemented in G4MultiNavigator.
Definition at line 2078 of file G4Navigator.cc.
Referenced by G4FastTrack::FRecordsAffineTransformation(), and G4VIntersectionLocator::LocateGlobalPointWithinVolumeAndCheck().
EnableBestSafety()
void G4Navigator::EnableBestSafety (G4bool value = false) inline
EnteredDaughterVolume()
G4bool G4Navigator::EnteredDaughterVolume () const inline
Referenced by GetLocalExitNormal(), and G4Transportation::PostStepDoIt().
ExitedMotherVolume()
G4bool G4Navigator::ExitedMotherVolume () const inline
Referenced by G4Transportation::PostStepDoIt().
GetCurrentLocalCoordinate()
G4ThreeVector G4Navigator::GetCurrentLocalCoordinate () const inline
GetDaughtersRegularStructureId()
G4int G4Navigator::GetDaughtersRegularStructureId (const G4LogicalVolume * pLog) const inline protected
Referenced by ComputeSafety(), ComputeStep(), LocateGlobalPointAndSetup(), and LocateGlobalPointWithinVolume().
GetGlobalExitNormal()
G4ThreeVector G4Navigator::GetGlobalExitNormal (const G4ThreeVector & point, G4bool * valid) virtual
Reimplemented in G4ErrorPropagationNavigator, and G4MultiNavigator.
Definition at line 1581 of file G4Navigator.cc.
Referenced by G4ErrorPropagationNavigator::GetGlobalExitNormal(), G4MultiNavigator::GetGlobalExitNormal(), and G4VIntersectionLocator::GetLastSurfaceNormal().
GetGlobalToLocalTransform()
const G4AffineTransform& G4Navigator::GetGlobalToLocalTransform () const inline
Referenced by GetLocalExitNormalAndCheck(), and G4VIntersectionLocator::LocateGlobalPointWithinVolumeAndCheck().
GetLocalExitNormal()
G4ThreeVector G4Navigator::GetLocalExitNormal (G4bool * valid) virtual
Reimplemented in G4MultiNavigator.
Definition at line 1333 of file G4Navigator.cc.
Referenced by G4RayTrajectory::AppendStep(), G4MultiNavigator::GetLocalExitNormal(), GetLocalExitNormalAndCheck(), and G4VTransitionRadiation::PostStepDoIt().
GetLocalExitNormalAndCheck()
G4ThreeVector G4Navigator::GetLocalExitNormalAndCheck (const G4ThreeVector & point, G4bool * valid) virtual
Reimplemented in G4MultiNavigator.
Definition at line 1545 of file G4Navigator.cc.
Referenced by GetGlobalExitNormal().
GetLocalToGlobalTransform()
const G4AffineTransform G4Navigator::GetLocalToGlobalTransform () const inline
Referenced by G4RayTrajectory::AppendStep(), and G4VIntersectionLocator::GetGlobalSurfaceNormal().
GetMotherToDaughterTransform()
G4AffineTransform G4Navigator::GetMotherToDaughterTransform (G4VPhysicalVolume * dVolume, G4int dReplicaNo, EVolume dVolumeType)
Definition at line 1498 of file G4Navigator.cc.
Referenced by GetLocalExitNormal().
GetVerboseLevel()
G4int G4Navigator::GetVerboseLevel () const inline
Referenced by export_G4Navigator(), GetGlobalExitNormal(), and G4ErrorPropagatorManager::StartNavigator().
GetWorldVolume()
G4VPhysicalVolume* G4Navigator::GetWorldVolume () const inline
Referenced by G4TransportationManager::ActivateNavigator(), G4ParallelGeometriesLimiterProcess::AddParallelWorld(), G4MultiNavigator::CheckMassWorld(), G4PropagatorInField::ComputeStep(), F04ElementField::Construct(), G4TransportationManager::DeActivateNavigator(), G4TransportationManager::DeRegisterNavigator(), export_G4Navigator(), G4FastSimulationManagerProcess::G4FastSimulationManagerProcess(), G4GeometrySampler::G4GeometrySampler(), G4ImportanceConfigurator::G4ImportanceConfigurator(), G4MultiNavigator::G4MultiNavigator(), G4TransportationManager::G4TransportationManager(), F04PrimaryGeneratorAction::GeneratePrimaries(), G4TransportationManager::GetParallelWorld(), G4SafetyHelper::GetWorldVolume(), G4GeometryMessenger::Init(), G4SafetyHelper::InitialiseNavigator(), G4ITTransportationManager::Initialize(), G4FastSimulationManager::ListTitle(), G4MultiNavigator::PrepareNavigators(), G4MultiNavigator::PrintLimited(), G4PathFinder::PrintLimited(), G4WeightWindowStore::SetWorldVolume(), G4IStore::SetWorldVolume(), and G4ErrorPropagatorManager::StartNavigator().
IsActive()
G4bool G4Navigator::IsActive () const inline
Referenced by export_G4Navigator().
IsCheckModeActive()
G4bool G4Navigator::IsCheckModeActive () const inline
Referenced by G4VIntersectionLocator::LocateGlobalPointWithinVolumeAndCheck().
LocateGlobalPointAndSetup()
G4VPhysicalVolume * G4Navigator::LocateGlobalPointAndSetup (const G4ThreeVector & point, const G4ThreeVector * direction = 0, const G4bool pRelativeSearch = true, const G4bool ignoreDirection = true) virtual
Reimplemented in G4MultiNavigator.
Definition at line 130 of file G4Navigator.cc.
Referenced by XrayFluoAnalysisManager::analyseStepping(), G4AdjointPrimaryGenerator::ComputeAccumulatedDepthVectorAlongBackRay(), ComputeStep(), F04ElementField::Construct(), G4TheRayTracer::CreateBitMap(), G4MagneticFieldModel::DescribeYourselfTo(), G4EventManager::DoProcessing(), G4MaterialScanner::DoScan(), G4TrajectoryDrawByOriginVolume::Draw(), G4TrajectoryOriginVolumeFilter::Evaluate(), F04PrimaryGeneratorAction::GeneratePrimaries(), G4VIntersectionLocator::GetLocalSurfaceNormal(), DMXParticleSource::IsSourceConfined(), G4SPSPosDistribution::IsSourceConfined(), G4SafetyHelper::Locate(), G4VIntersectionLocator::LocateGlobalPointWithinVolumeAndCheck(), ResetHierarchyAndLocate(), G4GeometryMessenger::ResetNavigator(), and G4SteppingManager::SetInitialStep().
LocateGlobalPointAndUpdateTouchable() [1/2]
void G4Navigator::LocateGlobalPointAndUpdateTouchable (const G4ThreeVector & position, const G4ThreeVector & direction, G4VTouchable * touchableToUpdate, const G4bool RelativeSearch = true) inline
Referenced by G4VReadOutGeometry::FindROTouchable().
LocateGlobalPointAndUpdateTouchable() [2/2]
void G4Navigator::LocateGlobalPointAndUpdateTouchable (const G4ThreeVector & position, G4VTouchable * touchableToUpdate, const G4bool RelativeSearch = true) inline
LocateGlobalPointAndUpdateTouchableHandle()
void G4Navigator::LocateGlobalPointAndUpdateTouchableHandle (const G4ThreeVector & position, const G4ThreeVector & direction, G4TouchableHandle & oldTouchableToUpdate, const G4bool RelativeSearch = true) inline
LocateGlobalPointWithinVolume()
void G4Navigator::LocateGlobalPointWithinVolume (const G4ThreeVector & position) virtual
Reimplemented in G4MultiNavigator.
Definition at line 587 of file G4Navigator.cc.
Referenced by G4VIntersectionLocator::AdjustmentOfFoundIntersection(), ComputeSafety(), G4PropagatorInField::ComputeStep(), ComputeStep(), G4BrentLocator::EstimateIntersectionPoint(), G4MultiLevelLocator::EstimateIntersectionPoint(), G4SimpleLocator::EstimateIntersectionPoint(), G4VIntersectionLocator::LocateGlobalPointWithinVolumeAndCheck(), G4Transportation::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), and G4SafetyHelper::ReLocateWithinVolume().
NetRotation()
G4RotationMatrix G4Navigator::NetRotation () const inline
NetTranslation()
G4ThreeVector G4Navigator::NetTranslation () const inline
operator=()
G4Navigator& G4Navigator::operator= (const G4Navigator &) private
PrintState()
void G4Navigator::PrintState () const
Definition at line 2087 of file G4Navigator.cc.
Referenced by ComputeSafety(), ComputeStep(), export_G4Navigator(), and LocateGlobalPointAndSetup().
RecheckDistanceToCurrentBoundary()
G4bool G4Navigator::RecheckDistanceToCurrentBoundary (const G4ThreeVector & pGlobalPoint, const G4ThreeVector & pDirection, const G4double CurrentProposedStepLength, G4double * prDistance, G4double * prNewSafety = 0) const virtual
Definition at line 1912 of file G4Navigator.cc.
Referenced by G4SafetyHelper::RecheckDistanceToCurrentBoundary(), and G4PathFinder::RecheckDistanceToCurrentBoundary().
ResetHierarchyAndLocate()
G4VPhysicalVolume * G4Navigator::ResetHierarchyAndLocate (const G4ThreeVector & point, const G4ThreeVector & direction, const G4TouchableHistory & h) virtual
Reimplemented in G4MultiNavigator.
Definition at line 100 of file G4Navigator.cc.
Referenced by G4MultiNavigator::ResetHierarchyAndLocate(), and G4SteppingManager::SetInitialStep().
ResetStackAndState()
void G4Navigator::ResetStackAndState () inline
Referenced by G4Navigator(), and LocateGlobalPointAndSetup().
ResetState()
void G4Navigator::ResetState () protected virtual
Reimplemented in G4MultiNavigator.
Definition at line 1234 of file G4Navigator.cc.
Referenced by ResetHierarchyAndLocate().
RestoreSavedState()
void G4Navigator::RestoreSavedState () protected
Definition at line 698 of file G4Navigator.cc.
Referenced by CheckNextStep(), and ComputeSafety().
SetGeometricallyLimitedStep()
void G4Navigator::SetGeometricallyLimitedStep () inline
Referenced by G4Transportation::PostStepDoIt(), and G4MonopoleTransportation::PostStepDoIt().
SetPushVerbosity()
void G4Navigator::SetPushVerbosity (G4bool mode) inline
Referenced by G4ParallelWorldProcess::G4ParallelWorldProcess(), G4ParallelWorldProcess::SetParallelWorld(), and G4GeometryMessenger::SetPushFlag().
SetSavedState()
void G4Navigator::SetSavedState () protected
Definition at line 664 of file G4Navigator.cc.
Referenced by CheckNextStep(), and ComputeSafety().
SetupHierarchy()
void G4Navigator::SetupHierarchy () protected virtual
Reimplemented in G4MultiNavigator.
Definition at line 1273 of file G4Navigator.cc.
Referenced by ResetHierarchyAndLocate().
SetVerboseLevel()
void G4Navigator::SetVerboseLevel (G4int level) inline
Referenced by export_G4Navigator(), GetGlobalExitNormal(), G4GeometryMessenger::SetVerbosity(), and G4ErrorPropagatorManager::StartNavigator().
SetWorldVolume()
void G4Navigator::SetWorldVolume (G4VPhysicalVolume * pWorld) inline
Referenced by G4VReadOutGeometry::BuildROGeometry(), F04ElementField::Construct(), XrayFluoDetectorConstruction::ConstructApparate(), G4MultiNavigator::G4MultiNavigator(), F04PrimaryGeneratorAction::GeneratePrimaries(), G4VIntersectionLocator::GetLocalSurfaceNormal(), G4TransportationManager::GetNavigator(), G4MultiNavigator::PrepareNavigators(), and G4ErrorPropagatorManager::StartNavigator().
SeverityOfZeroStepping()
G4int G4Navigator::SeverityOfZeroStepping (G4int * noZeroSteps) const inline
VolumeType()
EVolume G4Navigator::VolumeType (const G4VPhysicalVolume * pVol) const inline protected
Referenced by GetLocalExitNormal(), and LocateGlobalPointAndSetup().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const G4Navigator & n) friend
Definition at line 2253 of file G4Navigator.cc.
Field Documentation
fAbandonThreshold_NoZeroSteps
G4int G4Navigator::fAbandonThreshold_NoZeroSteps private
Definition at line 450 of file G4Navigator.hh.
Referenced by ComputeStep(), and G4Navigator().
fActionThreshold_NoZeroSteps
G4int G4Navigator::fActionThreshold_NoZeroSteps private
Definition at line 448 of file G4Navigator.hh.
Referenced by ComputeStep(), and G4Navigator().
fActive
G4bool G4Navigator::fActive private
Definition at line 396 of file G4Navigator.hh.
Referenced by G4Navigator().
fBlockedPhysicalVolume
G4VPhysicalVolume* G4Navigator::fBlockedPhysicalVolume private
Definition at line 414 of file G4Navigator.hh.
Referenced by ComputeStep(), GetLocalExitNormal(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), PrintState(), RecheckDistanceToCurrentBoundary(), ResetState(), RestoreSavedState(), and SetSavedState().
fBlockedReplicaNo
G4int G4Navigator::fBlockedReplicaNo private
Definition at line 415 of file G4Navigator.hh.
Referenced by ComputeStep(), GetLocalExitNormal(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), PrintState(), ResetState(), RestoreSavedState(), and SetSavedState().
fCalculatedExitNormal
G4bool G4Navigator::fCalculatedExitNormal private
Definition at line 432 of file G4Navigator.hh.
Referenced by ComputeStep(), GetGlobalExitNormal(), GetLocalExitNormal(), and ResetState().
fChangedGrandMotherRefFrame
G4bool G4Navigator::fChangedGrandMotherRefFrame private
Definition at line 428 of file G4Navigator.hh.
Referenced by ComputeStep(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), and ResetState().
fCheck
G4bool G4Navigator::fCheck private
Definition at line 492 of file G4Navigator.hh.
Referenced by GetLocalExitNormal(), and LocateGlobalPointAndSetup().
fEnteredDaughter
G4bool G4Navigator::fEnteredDaughter protected
Definition at line 371 of file G4Navigator.hh.
Referenced by ComputeSafety(), ComputeStep(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), RecheckDistanceToCurrentBoundary(), ResetState(), RestoreSavedState(), and SetSavedState().
fEntering
G4bool G4Navigator::fEntering private
Definition at line 405 of file G4Navigator.hh.
Referenced by ComputeStep(), GetGlobalExitNormal(), GetLocalExitNormal(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), PrintState(), ResetState(), RestoreSavedState(), and SetSavedState().
fExitedMother
G4bool G4Navigator::fExitedMother protected
Definition at line 377 of file G4Navigator.hh.
Referenced by ComputeSafety(), ComputeStep(), GetLocalExitNormal(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), ResetState(), RestoreSavedState(), and SetSavedState().
fExiting
G4bool G4Navigator::fExiting private
Definition at line 405 of file G4Navigator.hh.
Referenced by ComputeStep(), GetGlobalExitNormal(), GetLocalExitNormal(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), PrintState(), ResetState(), RestoreSavedState(), and SetSavedState().
fExitNormal
G4ThreeVector G4Navigator::fExitNormal private
Definition at line 423 of file G4Navigator.hh.
Referenced by ComputeStep(), PrintState(), ResetState(), RestoreSavedState(), and SetSavedState().
fExitNormalGlobalFrame
G4ThreeVector G4Navigator::fExitNormalGlobalFrame private
Definition at line 430 of file G4Navigator.hh.
Referenced by ComputeStep(), GetGlobalExitNormal(), and ResetState().
fGrandMotherExitNormal
G4ThreeVector G4Navigator::fGrandMotherExitNormal private
Definition at line 426 of file G4Navigator.hh.
Referenced by ComputeStep(), GetLocalExitNormal(), LocateGlobalPointAndSetup(), and ResetState().
fHistory
G4NavigationHistory G4Navigator::fHistory protected
Definition at line 367 of file G4Navigator.hh.
Referenced by ComputeSafety(), ComputeStep(), ComputeStepLog(), GetGlobalExitNormal(), GetLocalExitNormal(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), RecheckDistanceToCurrentBoundary(), ResetHierarchyAndLocate(), and SetupHierarchy().
fLastLocatedPointLocal
G4ThreeVector G4Navigator::fLastLocatedPointLocal private
Definition at line 417 of file G4Navigator.hh.
Referenced by ComputeStep(), ComputeStepLog(), GetLocalExitNormal(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), PrintState(), ResetState(), RestoreSavedState(), and SetSavedState().
fLastStepEndPointLocal
G4ThreeVector G4Navigator::fLastStepEndPointLocal protected
Definition at line 387 of file G4Navigator.hh.
Referenced by ComputeStep(), G4Navigator(), and GetLocalExitNormal().
fLastStepWasZero
G4bool G4Navigator::fLastStepWasZero private
Definition at line 441 of file G4Navigator.hh.
Referenced by ComputeStep(), PrintState(), ResetState(), RestoreSavedState(), and SetSavedState().
fLastTriedStepComputation
G4bool G4Navigator::fLastTriedStepComputation private
Definition at line 399 of file G4Navigator.hh.
Referenced by ComputeStep(), G4Navigator(), GetGlobalExitNormal(), GetLocalExitNormal(), GetLocalExitNormalAndCheck(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), RecheckDistanceToCurrentBoundary(), and ResetHierarchyAndLocate().
fLocatedOnEdge
G4bool G4Navigator::fLocatedOnEdge private
Definition at line 444 of file G4Navigator.hh.
Referenced by ComputeStep(), LocateGlobalPointAndSetup(), and ResetState().
fLocatedOutsideWorld
G4bool G4Navigator::fLocatedOutsideWorld private
Definition at line 419 of file G4Navigator.hh.
Referenced by LocateGlobalPointAndSetup(), ResetState(), RestoreSavedState(), and SetSavedState().
fMinStep
G4double G4Navigator::fMinStep protected
Definition at line 360 of file G4Navigator.hh.
Referenced by ComputeStep(), and G4Navigator().
fnormalNav
G4NormalNavigation G4Navigator::fnormalNav private
Definition at line 499 of file G4Navigator.hh.
Referenced by ComputeSafety(), ComputeStep(), G4Navigator(), and LocateGlobalPointAndSetup().
fNumberZeroSteps
G4int G4Navigator::fNumberZeroSteps private
Definition at line 446 of file G4Navigator.hh.
Referenced by ComputeStep(), and ResetState().
fparamNav
G4ParameterisedNavigation G4Navigator::fparamNav private
Definition at line 501 of file G4Navigator.hh.
Referenced by ComputeSafety(), ComputeStep(), LocateGlobalPointAndSetup(), and LocateGlobalPointWithinVolume().
fPreviousSafety
G4double G4Navigator::fPreviousSafety private
Definition at line 454 of file G4Navigator.hh.
Referenced by ComputeSafety(), ComputeStep(), ComputeStepLog(), PrintState(), ResetState(), RestoreSavedState(), and SetSavedState().
fPreviousSftOrigin
G4ThreeVector G4Navigator::fPreviousSftOrigin private
Definition at line 453 of file G4Navigator.hh.
Referenced by ComputeSafety(), ComputeStep(), ComputeStepLog(), PrintState(), ResetState(), RestoreSavedState(), and SetSavedState().
fPushed
G4bool G4Navigator::fPushed private
Definition at line 494 of file G4Navigator.hh.
Referenced by ComputeStep(), and ResetState().
fpVoxelSafety
G4VoxelSafety* G4Navigator::fpVoxelSafety private
Definition at line 504 of file G4Navigator.hh.
Referenced by ComputeSafety(), G4Navigator(), and ~G4Navigator().
fregularNav
G4RegularNavigation G4Navigator::fregularNav private
Definition at line 503 of file G4Navigator.hh.
Referenced by ComputeSafety(), ComputeStep(), G4Navigator(), and LocateGlobalPointAndSetup().
freplicaNav
G4ReplicaNavigation G4Navigator::freplicaNav private
Definition at line 502 of file G4Navigator.hh.
Referenced by ComputeSafety(), ComputeStep(), LocateGlobalPointAndSetup(), and SetupHierarchy().
fSaveState
struct G4Navigator::G4SaveNavigatorState G4Navigator::fSaveState private
Referenced by RestoreSavedState(), and SetSavedState().
fSqTol
G4double G4Navigator::fSqTol protected
Definition at line 360 of file G4Navigator.hh.
Referenced by ComputeStep(), G4Navigator(), and GetGlobalExitNormal().
fStepEndPoint
G4ThreeVector G4Navigator::fStepEndPoint protected
Definition at line 384 of file G4Navigator.hh.
Referenced by ComputeSafety(), ComputeStep(), G4Navigator(), and GetGlobalExitNormal().
fTopPhysical
G4VPhysicalVolume* G4Navigator::fTopPhysical private
Definition at line 486 of file G4Navigator.hh.
fValidExitNormal
G4bool G4Navigator::fValidExitNormal private
Definition at line 422 of file G4Navigator.hh.
Referenced by ComputeStep(), LocateGlobalPointAndSetup(), PrintState(), ResetState(), RestoreSavedState(), and SetSavedState().
fVerbose
G4int G4Navigator::fVerbose protected
Definition at line 391 of file G4Navigator.hh.
Referenced by G4MultiNavigator::ComputeSafety(), ComputeSafety(), G4MultiNavigator::ComputeStep(), ComputeStep(), G4MultiNavigator::GetGlobalExitNormal(), GetGlobalExitNormal(), GetLocalExitNormal(), G4MultiNavigator::LocateGlobalPointAndSetup(), LocateGlobalPointAndSetup(), G4MultiNavigator::LocateGlobalPointWithinVolume(), LocateGlobalPointWithinVolume(), G4MultiNavigator::ObtainFinalStep(), G4MultiNavigator::PrepareNavigators(), G4MultiNavigator::PrepareNewTrack(), G4MultiNavigator::PrintLimited(), PrintState(), and G4MultiNavigator::WhichLimited().
fvoxelNav
G4VoxelNavigation G4Navigator::fvoxelNav private
Definition at line 500 of file G4Navigator.hh.
Referenced by ComputeSafety(), ComputeStep(), LocateGlobalPointAndSetup(), and LocateGlobalPointWithinVolume().
fWarnPush
G4bool G4Navigator::fWarnPush private
Definition at line 494 of file G4Navigator.hh.
Referenced by ComputeStep().
fWasLimitedByGeometry
G4bool G4Navigator::fWasLimitedByGeometry protected
Definition at line 381 of file G4Navigator.hh.
Referenced by G4MultiNavigator::LocateGlobalPointAndSetup(), LocateGlobalPointAndSetup(), G4MultiNavigator::LocateGlobalPointWithinVolume(), LocateGlobalPointWithinVolume(), G4MultiNavigator::PrepareNavigators(), G4MultiNavigator::ResetState(), ResetState(), RestoreSavedState(), and SetSavedState().
kCarTolerance
G4double G4Navigator::kCarTolerance protected
Definition at line 360 of file G4Navigator.hh.
Referenced by ComputeSafety(), ComputeStep(), ComputeStepLog(), G4Navigator(), G4ErrorPropagationNavigator::GetGlobalExitNormal(), and GetLocalExitNormal().
The documentation for this class was generated from the following files:
source/geometry/navigation/include/G4Navigator.hh
source/geometry/navigation/src/G4Navigator.cc