Geant4: G4PolyhedronArbitrary Class Reference
G4PolyhedronArbitrary Class Reference
#include <G4PolyhedronArbitrary.hh>
Public Member Functions
G4PolyhedronArbitrary (const G4int nVertices, const G4int nFacets)
virtual ~G4PolyhedronArbitrary ()
void AddVertex (const G4ThreeVector &v)
void AddFacet (const G4int iv1, const G4int iv2, const G4int iv3, const G4int iv4=0)
void SetReferences ()
void InvertFacets ()
Public Member Functions inherited from G4Polyhedron
G4Polyhedron ()
G4Polyhedron (const HepPolyhedron &from)
virtual ~G4Polyhedron ()
G4int GetNumberOfRotationStepsAtTimeOfCreation () const
Public Member Functions inherited from G4Visible
G4Visible ()
G4Visible (const G4Visible &)
G4Visible (const G4VisAttributes *)
virtual ~G4Visible ()
G4Visible & operator= (const G4Visible &)
G4bool operator!= (const G4Visible &right) const
const G4VisAttributes * GetVisAttributes () const
void SetVisAttributes (const G4VisAttributes *)
void SetVisAttributes (const G4VisAttributes &)
Protected Attributes
G4int nVertexCount
G4int nFacetCount
Protected Attributes inherited from G4Visible
const G4VisAttributes * fpVisAttributes
G4bool fAllocatedVisAttributes
Private Member Functions
G4PolyhedronArbitrary (const G4PolyhedronArbitrary &)
G4PolyhedronArbitrary & operator= (const G4PolyhedronArbitrary &)
Detailed Description
Definition at line 75 of file G4PolyhedronArbitrary.hh.
Constructor & Destructor Documentation
G4PolyhedronArbitrary() [1/2]
G4PolyhedronArbitrary::G4PolyhedronArbitrary (const G4int nVertices, const G4int nFacets)
Definition at line 62 of file G4PolyhedronArbitrary.cc.
~G4PolyhedronArbitrary()
G4PolyhedronArbitrary::~G4PolyhedronArbitrary () virtual
Definition at line 71 of file G4PolyhedronArbitrary.cc.
G4PolyhedronArbitrary() [2/2]
G4PolyhedronArbitrary::G4PolyhedronArbitrary (const G4PolyhedronArbitrary &) private
Member Function Documentation
AddFacet()
void G4PolyhedronArbitrary::AddFacet (const G4int iv1, const G4int iv2, const G4int iv3, const G4int iv4 = 0)
Definition at line 93 of file G4PolyhedronArbitrary.cc.
Referenced by G4GenericTrap::CreatePolyhedron(), and G4TessellatedSolid::CreatePolyhedron().
AddVertex()
void G4PolyhedronArbitrary::AddVertex (const G4ThreeVector & v)
Definition at line 75 of file G4PolyhedronArbitrary.cc.
Referenced by G4GenericTrap::CreatePolyhedron(), and G4TessellatedSolid::CreatePolyhedron().
InvertFacets()
void G4PolyhedronArbitrary::InvertFacets () inline
Definition at line 89 of file G4PolyhedronArbitrary.hh.
Referenced by G4GenericTrap::CreatePolyhedron().
operator=()
G4PolyhedronArbitrary& G4PolyhedronArbitrary::operator= (const G4PolyhedronArbitrary &) private
SetReferences()
void G4PolyhedronArbitrary::SetReferences () inline
Definition at line 86 of file G4PolyhedronArbitrary.hh.
Referenced by G4GenericTrap::CreatePolyhedron(), and G4TessellatedSolid::CreatePolyhedron().
Field Documentation
nFacetCount
G4int G4PolyhedronArbitrary::nFacetCount protected
Definition at line 93 of file G4PolyhedronArbitrary.hh.
Referenced by AddFacet(), and G4PolyhedronArbitrary().
nVertexCount
G4int G4PolyhedronArbitrary::nVertexCount protected
Definition at line 92 of file G4PolyhedronArbitrary.hh.
Referenced by AddFacet(), AddVertex(), and G4PolyhedronArbitrary().
The documentation for this class was generated from the following files:
source/graphics_reps/include/G4PolyhedronArbitrary.hh
source/graphics_reps/src/G4PolyhedronArbitrary.cc