Geant4: G4MuElecSiStructure Class Reference
G4MuElecSiStructure Class Reference
#include <G4MuElecSiStructure.hh>
Public Member Functions
G4MuElecSiStructure ()
virtual ~G4MuElecSiStructure ()
G4double Energy (G4int level)
G4int NumberOfLevels ()
Private Attributes
G4int nLevels
std::vector< G4double > energyConstant
Detailed Description
Definition at line 51 of file G4MuElecSiStructure.hh.
Constructor & Destructor Documentation
G4MuElecSiStructure()
G4MuElecSiStructure::G4MuElecSiStructure ()
Definition at line 46 of file G4MuElecSiStructure.cc.
~G4MuElecSiStructure()
G4MuElecSiStructure::~G4MuElecSiStructure () virtual
Definition at line 59 of file G4MuElecSiStructure.cc.
Member Function Documentation
Energy()
G4double G4MuElecSiStructure::Energy (G4int level)
Definition at line 63 of file G4MuElecSiStructure.cc.
Referenced by G4MuElecInelasticModel::DifferentialCrossSection(), G4MuElecInelasticModel::RandomizeEjectedElectronEnergy(), and G4MuElecInelasticModel::SampleSecondaries().
NumberOfLevels()
G4int G4MuElecSiStructure::NumberOfLevels () inline
Definition at line 61 of file G4MuElecSiStructure.hh.
Field Documentation
energyConstant
std::vector<G4double> G4MuElecSiStructure::energyConstant private
Definition at line 69 of file G4MuElecSiStructure.hh.
Referenced by Energy(), and G4MuElecSiStructure().
nLevels
G4int G4MuElecSiStructure::nLevels private
Definition at line 67 of file G4MuElecSiStructure.hh.
Referenced by Energy(), G4MuElecSiStructure(), and NumberOfLevels().
The documentation for this class was generated from the following files:
source/processes/electromagnetic/lowenergy/include/G4MuElecSiStructure.hh
source/processes/electromagnetic/lowenergy/src/G4MuElecSiStructure.cc