Geant4: G4ParticleTable Class Reference
G4ParticleTable Class Reference
#include <G4ParticleTable.hh>
Public Types
typedef G4ParticleTableIterator< G4String, G4ParticleDefinition * >::Map G4PTblDictionary
typedef G4ParticleTableIterator< G4String, G4ParticleDefinition * > G4PTblDicIterator
typedef G4ParticleTableIterator< G4int, G4ParticleDefinition * >::Map G4PTblEncodingDictionary
typedef G4ParticleTableIterator< G4int, G4ParticleDefinition * > G4PTblEncodingDicIterator
Public Member Functions
void SlaveG4ParticleTable ()
void WorkerG4ParticleTable ()
virtual ~G4ParticleTable ()
void DestroyWorkerG4ParticleTable ()
G4bool contains (const G4ParticleDefinition *particle) const
G4bool contains (const G4String &particle_name) const
G4int entries () const
G4int size () const
G4ParticleDefinition * GetParticle (G4int index) const
const G4String & GetParticleName (G4int index) const
G4ParticleDefinition * FindParticle (G4int PDGEncoding)
G4ParticleDefinition * FindParticle (const G4String &particle_name)
G4ParticleDefinition * FindParticle (const G4ParticleDefinition *particle)
G4ParticleDefinition * FindAntiParticle (G4int PDGEncoding)
G4ParticleDefinition * FindAntiParticle (const G4String &particle_name)
G4ParticleDefinition * FindAntiParticle (const G4ParticleDefinition *particle)
G4PTblDicIterator * GetIterator () const
void DumpTable (const G4String &particle_name="ALL")
G4IonTable * GetIonTable () const
G4ParticleDefinition * Insert (G4ParticleDefinition *particle)
G4ParticleDefinition * Remove (G4ParticleDefinition *particle)
void RemoveAllParticles ()
void DeleteAllParticles ()
G4UImessenger * CreateMessenger ()
void DeleteMessenger ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetReadiness (G4bool val=true)
G4bool GetReadiness () const
G4ParticleDefinition * GetGenericIon () const
void SetGenericIon (G4ParticleDefinition *)
G4ParticleDefinition * GetGenericMuonicAtom () const
void SetGenericMuonicAtom (G4ParticleDefinition *)
Static Public Member Functions
static G4ParticleTable * GetParticleTable ()
Static Public Attributes
static G4ThreadLocal G4ParticleMessenger * fParticleMessenger = nullptr
static G4ThreadLocal G4PTblDictionary * fDictionary = nullptr
static G4ThreadLocal G4PTblDicIterator * fIterator = nullptr
static G4ThreadLocal G4PTblEncodingDictionary * fEncodingDictionary = nullptr
static G4ParticleTable * fgParticleTable =nullptr
static G4IonTable * fIonTable = nullptr
static G4ParticleMessenger * fParticleMessengerShadow = nullptr
static G4PTblDictionary * fDictionaryShadow = nullptr
static G4PTblDicIterator * fIteratorShadow = nullptr
static G4PTblEncodingDictionary * fEncodingDictionaryShadow = nullptr
Protected Member Functions
G4ParticleTable ()
G4ParticleTable (const G4ParticleTable &right)
G4ParticleTable & operator= (const G4ParticleTable &)
const G4PTblDictionary * GetDictionary () const
const G4String & GetKey (const G4ParticleDefinition *particle) const
const G4PTblEncodingDictionary * GetEncodingDictionary () const
Private Member Functions
void CheckReadiness () const
Private Attributes
G4int verboseLevel
const G4String noName
G4bool readyToUse
G4ParticleDefinition * genericIon
G4ParticleDefinition * genericMuonicAtom
Detailed Description
Definition at line 65 of file G4ParticleTable.hh.
Member Typedef Documentation
G4PTblDicIterator
typedef G4ParticleTableIterator<G4String, G4ParticleDefinition*> G4ParticleTable::G4PTblDicIterator
Definition at line 78 of file G4ParticleTable.hh.
G4PTblDictionary
typedef G4ParticleTableIterator<G4String, G4ParticleDefinition*>::Map G4ParticleTable::G4PTblDictionary
Definition at line 77 of file G4ParticleTable.hh.
G4PTblEncodingDicIterator
typedef G4ParticleTableIterator<G4int, G4ParticleDefinition*> G4ParticleTable::G4PTblEncodingDicIterator
Definition at line 80 of file G4ParticleTable.hh.
G4PTblEncodingDictionary
typedef G4ParticleTableIterator<G4int, G4ParticleDefinition*>::Map G4ParticleTable::G4PTblEncodingDictionary
Definition at line 79 of file G4ParticleTable.hh.
Constructor & Destructor Documentation
G4ParticleTable() [1/2]
G4ParticleTable::G4ParticleTable () protected
Definition at line 119 of file G4ParticleTable.cc.
G4ParticleTable() [2/2]
G4ParticleTable::G4ParticleTable (const G4ParticleTable & right) protected
Definition at line 265 of file G4ParticleTable.cc.
~G4ParticleTable()
G4ParticleTable::~G4ParticleTable () virtual
Definition at line 203 of file G4ParticleTable.cc.
Member Function Documentation
CheckReadiness()
void G4ParticleTable::CheckReadiness () const private
Definition at line 640 of file G4ParticleTable.cc.
Referenced by DumpTable(), FindParticle(), and GetParticle().
contains() [1/2]
G4bool G4ParticleTable::contains (const G4ParticleDefinition * particle) const
Referenced by Insert(), and G4ProcessTableMessenger::SetNewValue().
contains() [2/2]
G4bool G4ParticleTable::contains (const G4String & particle_name) const
Definition at line 679 of file G4ParticleTable.cc.
CreateMessenger()
G4UImessenger * G4ParticleTable::CreateMessenger ()
Definition at line 290 of file G4ParticleTable.cc.
Referenced by G4RunManager::G4RunManager().
DeleteAllParticles()
void G4ParticleTable::DeleteAllParticles ()
Definition at line 311 of file G4ParticleTable.cc.
Referenced by G4VUserPhysicsList::~G4VUserPhysicsList().
DeleteMessenger()
void G4ParticleTable::DeleteMessenger ()
Definition at line 300 of file G4ParticleTable.cc.
Referenced by G4RunManager::~G4RunManager().
DestroyWorkerG4ParticleTable()
void G4ParticleTable::DestroyWorkerG4ParticleTable ()
Definition at line 239 of file G4ParticleTable.cc.
Referenced by G4WorkerRunManagerKernel::~G4WorkerRunManagerKernel().
DumpTable()
void G4ParticleTable::DumpTable (const G4String & particle_name = "ALL")
Definition at line 614 of file G4ParticleTable.cc.
Referenced by export_G4ParticleTable(), Insert(), G4ParticleGunMessenger::SetNewValue(), G4GeneralParticleSourceMessenger::SetNewValue(), and G4RunManagerKernel::SetPhysics().
entries()
G4int G4ParticleTable::entries () const
Definition at line 685 of file G4ParticleTable.cc.
Referenced by G4GlobalFastSimulationManager::DisplayRegion(), export_G4ParticleTable(), G4RunManagerKernel::G4RunManagerKernel(), GetParticle(), G4FastSimulationManager::ListModels(), G4RunManagerKernel::SetPhysics(), and G4GlobalFastSimulationManager::ShowSetup().
FindAntiParticle() [1/3]
G4ParticleDefinition* G4ParticleTable::FindAntiParticle (const G4ParticleDefinition * particle)
FindAntiParticle() [2/3]
G4ParticleDefinition* G4ParticleTable::FindAntiParticle (const G4String & particle_name)
FindAntiParticle() [3/3]
G4ParticleDefinition* G4ParticleTable::FindAntiParticle (G4int PDGEncoding)
FindParticle() [1/3]
G4ParticleDefinition * G4ParticleTable::FindParticle (const G4ParticleDefinition * particle)
Definition at line 561 of file G4ParticleTable.cc.
FindParticle() [2/3]
G4ParticleDefinition * G4ParticleTable::FindParticle (const G4String & particle_name)
Definition at line 532 of file G4ParticleTable.cc.
FindParticle() [3/3]
G4ParticleDefinition * G4ParticleTable::FindParticle (G4int PDGEncoding)
Definition at line 569 of file G4ParticleTable.cc.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmModelActivator::ActivatePAI(), G4SDParticleFilter::add(), G4VHadronPhysics::AddElasticCrossSection(), G4VHadronPhysics::AddInelasticCrossSection(), GB02BOptrMultiParticleForceCollision::AddParticle(), G4ChannelingOptrMultiParticleChangeCrossSection::AddParticle(), GB01BOptrMultiParticleChangeCrossSection::AddParticle(), G4MonopoleTransportation::AlongStepDoIt(), G4ITTransportation::AlongStepDoIt(), B1PrimaryGeneratorAction::B1PrimaryGeneratorAction(), B2PrimaryGeneratorAction::B2PrimaryGeneratorAction(), B3PrimaryGeneratorAction::B3PrimaryGeneratorAction(), B4PrimaryGeneratorAction::B4PrimaryGeneratorAction(), G4HadronBuilder::Barion(), G4ErrorTrajState::BuildCharge(), G4VUserPhysicsList::BuildPhysicsTable(), CCalPrimaryGeneratorAction::CCalPrimaryGeneratorAction(), G4PrimaryTransformer::CheckUnknown(), G4MuonicAtomHelper::ConstructMuonicAtom(), G4EmLivermorePhysics::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4EmStandardPhysicsSS::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysicsWVI::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), G4EmStandardPhysics_option2::ConstructProcess(), G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), G4PionDecayMakeSpin::DaughterPolarization(), G4PhononLong::Definition(), G4PhononTransSlow::Definition(), G4PhononTransFast::Definition(), G4BcMesonMinus::Definition(), G4BcMesonPlus::Definition(), G4EtaPrime::Definition(), G4Upsilon::Definition(), G4SigmacPlusPlus::Definition(), G4SigmacPlus::Definition(), G4SigmacZero::Definition(), G4SigmaPlus::Definition(), G4SigmaMinus::Definition(), G4SigmaZero::Definition(), G4XicPlus::Definition(), G4XicZero::Definition(), G4XiMinus::Definition(), G4XiZero::Definition(), G4AntiBMesonZero::Definition(), G4AntiBsMesonZero::Definition(), G4AntiDMesonZero::Definition(), G4AntiKaonZero::Definition(), G4BMesonMinus::Definition(), G4BMesonPlus::Definition(), G4BMesonZero::Definition(), G4DMesonMinus::Definition(), G4DMesonPlus::Definition(), G4DMesonZero::Definition(), G4DsMesonMinus::Definition(), G4DsMesonPlus::Definition(), G4Eta::Definition(), G4BsMesonZero::Definition(), G4JPsi::Definition(), G4KaonMinus::Definition(), G4KaonPlus::Definition(), G4KaonZero::Definition(), G4KaonZeroLong::Definition(), G4KaonZeroShort::Definition(), G4PionMinus::Definition(), G4PionZero::Definition(), G4PionPlus::Definition(), G4AntiNeutrinoE::Definition(), G4AntiNeutrinoMu::Definition(), G4AntiNeutrinoTau::Definition(), G4Electron::Definition(), G4MuonMinus::Definition(), G4MuonPlus::Definition(), G4NeutrinoE::Definition(), G4NeutrinoMu::Definition(), G4NeutrinoTau::Definition(), G4AntiLambda::Definition(), G4TauMinus::Definition(), G4TauPlus::Definition(), G4AntiLambdacPlus::Definition(), G4AntiNeutron::Definition(), G4AntiOmegabMinus::Definition(), G4AntiOmegacZero::Definition(), G4AntiOmegaMinus::Definition(), G4AntiProton::Definition(), G4AntiSigmacPlus::Definition(), G4AntiSigmacPlusPlus::Definition(), G4AntiSigmacZero::Definition(), G4AntiSigmaMinus::Definition(), G4AntiSigmaPlus::Definition(), G4AntiSigmaZero::Definition(), G4AntiXicPlus::Definition(), G4AntiXicZero::Definition(), G4AntiXiZero::Definition(), G4AntiXiMinus::Definition(), G4Lambda::Definition(), G4LambdacPlus::Definition(), G4OmegabMinus::Definition(), G4OmegacZero::Definition(), G4OmegaMinus::Definition(), G4SigmabZero::Definition(), G4XibZero::Definition(), G4Alpha::Definition(), G4AntiAlpha::Definition(), G4AntiDeuteron::Definition(), G4AntiHe3::Definition(), G4AntiTriton::Definition(), G4Deuteron::Definition(), G4He3::Definition(), G4Triton::Definition(), G4Etac::Definition(), G4XibMinus::Definition(), G4Positron::Definition(), G4AntiSigmabMinus::Definition(), G4AntiSigmabPlus::Definition(), G4AntiSigmabZero::Definition(), G4AntiXibMinus::Definition(), G4AntiXibZero::Definition(), G4Neutron::Definition(), G4Proton::Definition(), G4SigmabMinus::Definition(), G4SigmabPlus::Definition(), G4AntiLambdab::Definition(), G4Lambdab::Definition(), G4AdjointAlpha::Definition(), G4AdjointDeuteron::Definition(), G4AdjointHe3::Definition(), G4AdjointTriton::Definition(), G4ChargedGeantino::Definition(), G4Geantino::Definition(), G4Gamma::Definition(), G4OpticalPhoton::Definition(), G4UnknownParticle::Definition(), G4GenericMuonicAtom::Definition(), G4AdjointElectron::Definition(), G4AdjointElectronFI::Definition(), G4AdjointGenericIon::Definition(), G4AdjointProton::Definition(), G4AdjointPositron::Definition(), G4GenericIon::Definition(), G4AdjointGamma::Definition(), G4H2::Definition(), G4H2O::Definition(), G4H2O2::Definition(), G4Electron_aq::Definition(), G4H3O::Definition(), G4Hydrogen::Definition(), G4OH::Definition(), Dicom2PrimaryGeneratorAction::Dicom2PrimaryGeneratorAction(), G4LundStringFragmentation::Diquark_AntiDiquark_aboveThreshold_lastSplitting(), DumpTable(), HistoManager::EndOfRun(), eRositaPrimaryGeneratorAction::eRositaPrimaryGeneratorAction(), G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), ExN02PrimaryGeneratorAction::ExN02PrimaryGeneratorAction(), ExP01PrimaryGeneratorAction::ExP01PrimaryGeneratorAction(), ExP02PrimaryGeneratorAction::ExP02PrimaryGeneratorAction(), ExTGPrimaryGeneratorAction::ExTGPrimaryGeneratorAction(), ExUCNPrimaryGeneratorAction::ExUCNPrimaryGeneratorAction(), F01PrimaryGeneratorAction::F01PrimaryGeneratorAction(), F02PrimaryGeneratorAction::F02PrimaryGeneratorAction(), F03PrimaryGeneratorAction::F03PrimaryGeneratorAction(), F05PrimaryGeneratorAction::F05PrimaryGeneratorAction(), F06PrimaryGeneratorAction::F06PrimaryGeneratorAction(), FCALPrimaryGeneratorAction::FCALPrimaryGeneratorAction(), G4VDecayChannel::FillDaughters(), G4VDecayChannel::FillParent(), G4VHadronPhysics::FindElasticProcess(), G4VHadronPhysics::FindInelasticProcess(), G4VLongitudinalStringDecay::FindParticle(), FindParticle(), G4EnergyLossForExtrapolator::FindParticle(), G4EmCalculator::FindParticle(), G01PrimaryGeneratorAction::G01PrimaryGeneratorAction(), G02PrimaryGeneratorAction::G02PrimaryGeneratorAction(), G03PrimaryGeneratorAction::G03PrimaryGeneratorAction(), G04PrimaryGeneratorAction::G04PrimaryGeneratorAction(), G4BOptrForceCollision::G4BOptrForceCollision(), G4ChannelingOptrChangeCrossSection::G4ChannelingOptrChangeCrossSection(), G4CollisionMesonBaryonToResonance::G4CollisionMesonBaryonToResonance(), G4HadronicProcessStore::G4HadronicProcessStore(), G4Parton::G4Parton(), G4PrimaryParticle::G4PrimaryParticle(), G4ResonanceNames::G4ResonanceNames(), G4RToEConvForElectron::G4RToEConvForElectron(), G4RToEConvForGamma::G4RToEConvForGamma(), G4RToEConvForPositron::G4RToEConvForPositron(), G4RToEConvForProton::G4RToEConvForProton(), G4SDParticleFilter::G4SDParticleFilter(), G4Track::G4Track(), GammaKnifeActionInitialization::GammaKnifeActionInitialization(), GammaRayTelPrimaryGeneratorAction::GammaRayTelPrimaryGeneratorAction(), GB01BOptrChangeCrossSection::GB01BOptrChangeCrossSection(), GB01PrimaryGeneratorAction::GB01PrimaryGeneratorAction(), GB02PrimaryGeneratorAction::GB02PrimaryGeneratorAction(), GB03PrimaryGeneratorAction::GB03PrimaryGeneratorAction(), GB04PrimaryGeneratorAction::GB04PrimaryGeneratorAction(), GB05BOptrSplitAndKillByCrossSection::GB05BOptrSplitAndKillByCrossSection(), GB05PrimaryGeneratorAction::GB05PrimaryGeneratorAction(), GB06BOptrSplitAndKillByImportance::GB06BOptrSplitAndKillByImportance(), GB06PrimaryGeneratorAction::GB06PrimaryGeneratorAction(), G4QGSParticipants::GenerateDeltaIsobar(), G4FTFModel::GenerateDeltaIsobar(), G4HtmlPPReporter::GenerateIndex(), HadrontherapyPrimaryGeneratorAction::GeneratePrimaries(), DicomPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPrimaryGeneratorAction::GeneratePrimaries(), PrimaryGenerator::GeneratePrimaryVertex(), G4VUserPhysicsList::GetApplyCuts(), G4PrimaryTransformer::GetDefinition(), G4DynamicParticle::GetElectronMass(), G4NucleiProperties::GetNuclearMass(), G4HyperNucleiProperties::GetNuclearMass(), G4Pythia6Decayer::GetParticleDefinition(), G4ParticlePropertyTable::GetParticleProperty(), PhysicsList::GetRange(), GunPrimaryGeneratorAction::GunPrimaryGeneratorAction(), G4ErrorPropagator::InitG4Track(), G4DNAIonElasticModel::Initialise(), G4EmSaturation::InitialiseBirksCoefficient(), G4INCL::ParticleTable::initialize(), CML2PrimaryGenerationAction::inizialize(), Insert(), G4HadronBuilder::Meson(), G4ResonanceNames::MinMass(), MyPrimaryGeneratorActionFromFile::MyPrimaryGeneratorActionFromFile(), PrimaryGeneratorAction::Notify(), MyPrimaryGeneratorActionFromFile::Notify(), G4CollisionComposite::Resolve::operator()(), OpNovicePrimaryGeneratorAction::OpNovicePrimaryGeneratorAction(), Par01PrimaryGeneratorAction::Par01PrimaryGeneratorAction(), Par02PrimaryGeneratorAction::Par02PrimaryGeneratorAction(), G4AdjointTrackingAction::PostUserTrackingAction(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), PrimaryGeneratorGun1::PrimaryGeneratorGun1(), PrimaryGeneratorGun2::PrimaryGeneratorGun2(), G4TextPPReporter::Print(), G4HtmlPPReporter::Print(), G4LundStringFragmentation::Quark_AntiQuark_lastSplitting(), G4LundStringFragmentation::Quark_Diquark_lastSplitting(), RE01PrimaryGeneratorAction::RE01PrimaryGeneratorAction(), RE02PrimaryGeneratorAction::RE02PrimaryGeneratorAction(), RE03PrimaryGeneratorAction::RE03PrimaryGeneratorAction(), RE04PrimaryGeneratorAction::RE04PrimaryGeneratorAction(), RE05PrimaryGeneratorAction::RE05PrimaryGeneratorAction(), RE06PrimaryGeneratorAction::RE06PrimaryGeneratorAction(), G4AdjointSimManager::RegisterAtEndOfAdjointTrack(), G4LMsdGenerator::SampleMx(), G4VUserPhysicsList::SetApplyCuts(), G4DecayTableMessenger::SetCurrentParticle(), G4ParticlePropertyMessenger::SetCurrentParticle(), G4ProcessManagerMessenger::SetCurrentParticle(), PrimaryGeneratorAction::SetDefaultKinematic(), StackingAction::SetKill(), F04PhysicsListMessenger::SetNewValue(), G4ParticleGunMessenger::SetNewValue(), WLSPhysicsListMessenger::SetNewValue(), G4ProcessTableMessenger::SetNewValue(), G4ParticleMessenger::SetNewValue(), G4GeneralParticleSourceMessenger::SetNewValue(), G4PSNofSecondary::SetParticle(), G4ParticlePropertyTable::SetParticleProperty(), G4PrimaryParticle::SetPDGcode(), G4RTPrimaryGeneratorAction::SetUp(), G4RayShooter::Shoot(), TSPrimaryGeneratorAction::TSPrimaryGeneratorAction(), G4AdjointPrimaryGeneratorAction::UpdateListOfPrimaryParticles(), XrayFluoMercuryPrimaryGeneratorAction::XrayFluoMercuryPrimaryGeneratorAction(), and XrayFluoPlanePrimaryGeneratorAction::XrayFluoPlanePrimaryGeneratorAction().
GetDictionary()
const G4ParticleTable::G4PTblDictionary * G4ParticleTable::GetDictionary () const protected
Definition at line 664 of file G4ParticleTable.cc.
GetEncodingDictionary()
const G4ParticleTable::G4PTblEncodingDictionary * G4ParticleTable::GetEncodingDictionary () const protected
Definition at line 674 of file G4ParticleTable.cc.
GetGenericIon()
G4ParticleDefinition* G4ParticleTable::GetGenericIon () const
Referenced by G4IonTable::AddProcessManager(), G4IonTable::CreateIon(), G4VUserPhysicsList::InitializeProcessManager(), G4RunManagerKernel::PropagateGenericIonID(), and G4RunManagerKernel::SetupPhysics().
GetGenericMuonicAtom()
G4ParticleDefinition* G4ParticleTable::GetGenericMuonicAtom () const
Referenced by G4IonTable::AddProcessManager().
GetIonTable()
G4IonTable * G4ParticleTable::GetIonTable () const
Definition at line 659 of file G4ParticleTable.cc.
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4BinaryLightIonReaction::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4WilsonAblationModel::BreakItUp(), G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), G4QGSParticipants::ComputeNucleusProperties(), G4FTFModel::ComputeNucleusProperties(), DMXPhysicsList::ConstructGeneral(), G4ITDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecay::DecayIt(), G4BinaryLightIonReaction::DeExciteSpectatorNucleus(), G4ParticleDefinition::DumpTable(), G4BinaryLightIonReaction::FuseNucleiAndPrompound(), G4AlphaDecay::G4AlphaDecay(), G4BetaMinusDecay::G4BetaMinusDecay(), G4BetaPlusDecay::G4BetaPlusDecay(), G4ECDecay::G4ECDecay(), G4eCoulombScatteringModel::G4eCoulombScatteringModel(), G4EmCalculator::G4EmCalculator(), G4EmCorrections::G4EmCorrections(), G4eSingleCoulombScatteringModel::G4eSingleCoulombScatteringModel(), G4Evaporation::G4Evaporation(), G4ExcitationHandler::G4ExcitationHandler(), G4hCoulombScatteringModel::G4hCoulombScatteringModel(), G4IonCoulombScatteringModel::G4IonCoulombScatteringModel(), G4ITDecay::G4ITDecay(), G4LENDManager::G4LENDManager(), G4NeutronDecay::G4NeutronDecay(), G4NeutronRadCapture::G4NeutronRadCapture(), G4ParticleDefinition::G4ParticleDefinition(), G4ProtonDecay::G4ProtonDecay(), G4WilsonAbrasionModel::GetAbradedNucleons(), G4TripathiCrossSection::GetElementCrossSection(), G4NuclNuclDiffuseElastic::GetInvCoulombElasticXsc(), G4DiffuseElastic::GetInvCoulombElasticXsc(), G4NuclNuclDiffuseElastic::GetInvElasticSumXsc(), G4DiffuseElastic::GetInvElasticSumXsc(), G4NuclNuclDiffuseElastic::GetInvElasticXsc(), G4DiffuseElastic::GetInvElasticXsc(), G4BinaryCascade::GetIonMass(), G4IonTable::GetIonTable(), G4StatMFFragment::GetNuclearMass(), G4ChipsProtonElasticXS::GetQ2max(), G4ChipsHyperonElasticXS::GetQ2max(), G4ChipsPionPlusElasticXS::GetQ2max(), G4ChipsKaonPlusElasticXS::GetQ2max(), G4ChipsPionMinusElasticXS::GetQ2max(), G4ChipsAntiBaryonElasticXS::GetQ2max(), G4ChipsKaonMinusElasticXS::GetQ2max(), G4ChipsNeutronElasticXS::GetQ2max(), G4BinaryCascade::HighEnergyModelFSProducts(), G4FTFModel::Init(), G4INCL::ParticleTable::initialize(), G4BinaryLightIonReaction::Interact(), G4InuclNuclei::makeDefinition(), G4QuasiElasticChannel::Scatter(), G4BinaryLightIonReaction::SetLighterAsProjectile(), G4ParticleMessenger::SetNewValue(), and G4RunManagerKernel::SetupPhysics().
GetIterator()
G4ParticleTable::G4PTblDicIterator * G4ParticleTable::GetIterator () const
Definition at line 669 of file G4ParticleTable.cc.
Referenced by G4ITStepProcessor::ActiveOnlyITProcess(), G4RunManagerKernel::ConfirmCoupledTransportation(), G4ChannelingPhysics::ConstructProcess(), G4RunManager::ConstructScoringWorlds(), G4VParticlePropertyReporter::FillList(), G4ErrorTrackLengthTarget::G4ErrorTrackLengthTarget(), G4ParticleGunMessenger::G4ParticleGunMessenger(), G4PhysicsListHelper::G4PhysicsListHelper(), G4VUserPhysicsList::G4VUserPhysicsList(), G4ParticleMessenger::GetCurrentValue(), G4ProcessPlacer::GetProcessManager(), G4VPCData::initialize(), G4VUPLData::initialize(), G4RunManagerKernel::PropagateGenericIonID(), G4TextPPRetriever::Retrieve(), G4EmConfigurator::SetModelForRegion(), G4ParticleMessenger::SetNewValue(), G4RunManagerKernel::SetScoreSplitter(), G4MTRunManagerKernel::SetUpDecayChannels(), G4RunManagerKernel::SetupPhysics(), G4WorkerRunManagerKernel::SetupShadowProcess(), and G4RunManagerKernel::SetupShadowProcess().
GetKey()
const G4String& G4ParticleTable::GetKey (const G4ParticleDefinition * particle) const protected
Referenced by FindParticle(), Insert(), Remove(), and WorkerG4ParticleTable().
GetParticle()
G4ParticleDefinition * G4ParticleTable::GetParticle (G4int index) const
Definition at line 499 of file G4ParticleTable.cc.
Referenced by G4GlobalFastSimulationManager::DisplayRegion(), export_G4ParticleTable(), G4RunManagerKernel::G4RunManagerKernel(), GetParticleName(), G4FastSimulationManager::ListModels(), G4RunManagerKernel::SetPhysics(), and G4GlobalFastSimulationManager::ShowSetup().
GetParticleName()
const G4String & G4ParticleTable::GetParticleName (G4int index) const
Definition at line 521 of file G4ParticleTable.cc.
Referenced by DeleteAllParticles(), export_G4ParticleTable(), getParticleTable(), and G4FastSimulationManager::ListModels().
GetParticleTable()
G4ParticleTable * G4ParticleTable::GetParticleTable () static
Definition at line 104 of file G4ParticleTable.cc.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmModelActivator::ActivatePAI(), G4ITStepProcessor::ActiveOnlyITProcess(), G4SDParticleFilter::add(), G4ChannelingOptrMultiParticleChangeCrossSection::AddChargedParticles(), G4VHadronPhysics::AddElasticCrossSection(), G4VHadronPhysics::AddInelasticCrossSection(), GB02BOptrMultiParticleForceCollision::AddParticle(), G4ChannelingOptrMultiParticleChangeCrossSection::AddParticle(), GB01BOptrMultiParticleChangeCrossSection::AddParticle(), G4IonTable::AddProcessManager(), G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4MonopoleTransportation::AlongStepDoIt(), G4ITTransportation::AlongStepDoIt(), G4BinaryLightIonReaction::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), B1PrimaryGeneratorAction::B1PrimaryGeneratorAction(), B2PrimaryGeneratorAction::B2PrimaryGeneratorAction(), B3PrimaryGeneratorAction::B3PrimaryGeneratorAction(), B4PrimaryGeneratorAction::B4PrimaryGeneratorAction(), B5PrimaryGeneratorAction::B5PrimaryGeneratorAction(), G4HadronBuilder::Barion(), G4WilsonAblationModel::BreakItUp(), G4ErrorTrajState::BuildCharge(), G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), CCalPrimaryGeneratorAction::CCalPrimaryGeneratorAction(), G4IonTable::clear(), G4QGSParticipants::ComputeNucleusProperties(), G4FTFModel::ComputeNucleusProperties(), G4RunManagerKernel::ConfirmCoupledTransportation(), G4ExcitedBaryonConstructor::Construct(), G4ExcitedMesonConstructor::Construct(), DMXPhysicsList::ConstructGeneral(), G4MuonicAtomHelper::ConstructMuonicAtom(), G4EmLivermorePhysics::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4ChannelingPhysics::ConstructProcess(), G4EmStandardPhysicsSS::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysicsWVI::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), G4EmStandardPhysics_option2::ConstructProcess(), G4RunManager::ConstructScoringWorlds(), G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), G4IonTable::CreateIon(), G4PionDecayMakeSpin::DaughterPolarization(), G4ITDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecay::DecayIt(), G4BinaryLightIonReaction::DeExciteSpectatorNucleus(), G4PhononLong::Definition(), G4PhononTransSlow::Definition(), G4PhononTransFast::Definition(), G4Diproton::Definition(), G4Dineutron::Definition(), G4UnboundPN::Definition(), G4BcMesonMinus::Definition(), G4BcMesonPlus::Definition(), G4EtaPrime::Definition(), G4Upsilon::Definition(), G4AntiSigmaPlus::Definition(), G4AntiSigmacZero::Definition(), G4AntiSigmaMinus::Definition(), G4AntiSigmaZero::Definition(), G4AntiXicPlus::Definition(), G4AntiXicZero::Definition(), G4AntiXiZero::Definition(), G4AntiXiMinus::Definition(), G4Lambda::Definition(), G4LambdacPlus::Definition(), G4OmegabMinus::Definition(), G4OmegacZero::Definition(), G4SigmacPlus::Definition(), G4SigmacPlusPlus::Definition(), G4SigmacZero::Definition(), G4SigmaMinus::Definition(), G4SigmaPlus::Definition(), G4SigmaZero::Definition(), G4OmegaMinus::Definition(), G4XicPlus::Definition(), G4XicZero::Definition(), G4XiMinus::Definition(), G4DMesonZero::Definition(), G4XiZero::Definition(), G4AntiDMesonZero::Definition(), G4AntiBMesonZero::Definition(), G4AntiBsMesonZero::Definition(), G4AntiKaonZero::Definition(), G4BMesonMinus::Definition(), G4BMesonPlus::Definition(), G4BMesonZero::Definition(), G4DMesonMinus::Definition(), G4BsMesonZero::Definition(), G4DMesonPlus::Definition(), G4DsMesonPlus::Definition(), G4Eta::Definition(), G4JPsi::Definition(), G4DsMesonMinus::Definition(), G4KaonMinus::Definition(), G4KaonZero::Definition(), G4KaonZeroLong::Definition(), G4KaonZeroShort::Definition(), G4PionMinus::Definition(), G4KaonPlus::Definition(), G4PionZero::Definition(), G4PionPlus::Definition(), G4AntiNeutrinoE::Definition(), G4AntiNeutrinoMu::Definition(), G4AntiNeutrinoTau::Definition(), G4Electron::Definition(), G4MuonMinus::Definition(), G4MuonPlus::Definition(), G4NeutrinoE::Definition(), G4NeutrinoMu::Definition(), G4NeutrinoTau::Definition(), G4TauMinus::Definition(), G4TauPlus::Definition(), G4AntiLambda::Definition(), G4AntiLambdacPlus::Definition(), G4AntiNeutron::Definition(), G4AntiOmegabMinus::Definition(), G4AntiOmegacZero::Definition(), G4AntiOmegaMinus::Definition(), G4AntiProton::Definition(), G4AntiSigmacPlus::Definition(), G4AntiSigmacPlusPlus::Definition(), G4AntiXibZero::Definition(), G4AntiXibMinus::Definition(), G4Neutron::Definition(), G4SigmabMinus::Definition(), G4SigmabPlus::Definition(), G4SigmabZero::Definition(), G4Proton::Definition(), G4XibMinus::Definition(), G4XibZero::Definition(), G4Alpha::Definition(), G4AntiAlpha::Definition(), G4AntiDeuteron::Definition(), G4AntiHe3::Definition(), G4AntiTriton::Definition(), G4Deuteron::Definition(), G4Triton::Definition(), G4He3::Definition(), G4Etac::Definition(), G4Positron::Definition(), G4AntiSigmabMinus::Definition(), G4AntiSigmabZero::Definition(), G4AntiSigmabPlus::Definition(), G4Lambdab::Definition(), G4AntiLambdab::Definition(), G4AdjointAlpha::Definition(), G4AdjointDeuteron::Definition(), G4AdjointHe3::Definition(), G4AdjointTriton::Definition(), G4ChargedGeantino::Definition(), G4Geantino::Definition(), G4OpticalPhoton::Definition(), G4Gamma::Definition(), G4UnknownParticle::Definition(), G4GenericMuonicAtom::Definition(), G4AdjointElectron::Definition(), G4AdjointElectronFI::Definition(), G4AdjointGenericIon::Definition(), G4AdjointProton::Definition(), G4AdjointPositron::Definition(), G4GenericIon::Definition(), G4AdjointGamma::Definition(), G4Electron_aq::Definition(), G4H2::Definition(), G4H2O::Definition(), G4H2O2::Definition(), G4H3O::Definition(), G4Hydrogen::Definition(), G4OH::Definition(), Dicom2PrimaryGeneratorAction::Dicom2PrimaryGeneratorAction(), G4LundStringFragmentation::Diquark_AntiDiquark_aboveThreshold_lastSplitting(), G4GlobalFastSimulationManager::DisplayRegion(), DMXParticleSourceMessenger::DMXParticleSourceMessenger(), HistoManager::EndOfRun(), eRositaPrimaryGeneratorAction::eRositaPrimaryGeneratorAction(), G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), ExN02PrimaryGeneratorAction::ExN02PrimaryGeneratorAction(), ExP01PrimaryGeneratorAction::ExP01PrimaryGeneratorAction(), ExP02PrimaryGeneratorAction::ExP02PrimaryGeneratorAction(), export_G4ParticleTable(), ExTGPrimaryGeneratorAction::ExTGPrimaryGeneratorAction(), ExUCNPrimaryGeneratorAction::ExUCNPrimaryGeneratorAction(), F01PrimaryGeneratorAction::F01PrimaryGeneratorAction(), F02PrimaryGeneratorAction::F02PrimaryGeneratorAction(), F03PrimaryGeneratorAction::F03PrimaryGeneratorAction(), F04PrimaryGeneratorAction::F04PrimaryGeneratorAction(), F05PrimaryGeneratorAction::F05PrimaryGeneratorAction(), F06PrimaryGeneratorAction::F06PrimaryGeneratorAction(), FCALPrimaryGeneratorAction::FCALPrimaryGeneratorAction(), G4VParticlePropertyReporter::FillList(), G4BaryonSplitter::FindDiquark(), G4VHadronPhysics::FindElasticProcess(), G4VHadronPhysics::FindInelasticProcess(), G4VLongitudinalStringDecay::FindParticle(), G4EnergyLossForExtrapolator::FindParticle(), G4EmCalculator::FindParticle(), G4BinaryLightIonReaction::FuseNucleiAndPrompound(), G01PrimaryGeneratorAction::G01PrimaryGeneratorAction(), G02PrimaryGeneratorAction::G02PrimaryGeneratorAction(), G03PrimaryGeneratorAction::G03PrimaryGeneratorAction(), G04PrimaryGeneratorAction::G04PrimaryGeneratorAction(), G4AlphaDecay::G4AlphaDecay(), G4BaryonSplitter::G4BaryonSplitter(), G4BetaMinusDecay::G4BetaMinusDecay(), G4BetaPlusDecay::G4BetaPlusDecay(), G4BOptrForceCollision::G4BOptrForceCollision(), G4ChannelingOptrChangeCrossSection::G4ChannelingOptrChangeCrossSection(), G4CollisionMesonBaryonToResonance::G4CollisionMesonBaryonToResonance(), G4DecayTableMessenger::G4DecayTableMessenger(), G4ECDecay::G4ECDecay(), G4eCoulombScatteringModel::G4eCoulombScatteringModel(), G4EmCalculator::G4EmCalculator(), G4EmCorrections::G4EmCorrections(), G4ErrorTrackLengthTarget::G4ErrorTrackLengthTarget(), G4eSingleCoulombScatteringModel::G4eSingleCoulombScatteringModel(), G4Evaporation::G4Evaporation(), G4ExcitationHandler::G4ExcitationHandler(), G4GeneralParticleSourceMessenger::G4GeneralParticleSourceMessenger(), G4HadronicProcessStore::G4HadronicProcessStore(), G4hCoulombScatteringModel::G4hCoulombScatteringModel(), G4IonCoulombScatteringModel::G4IonCoulombScatteringModel(), G4ITDecay::G4ITDecay(), G4LENDManager::G4LENDManager(), G4NeutronDecay::G4NeutronDecay(), G4NeutronRadCapture::G4NeutronRadCapture(), G4ParticleDefinition::G4ParticleDefinition(), G4ParticleGunMessenger::G4ParticleGunMessenger(), G4ParticleMessenger::G4ParticleMessenger(), G4ParticlePropertyMessenger::G4ParticlePropertyMessenger(), G4ParticlePropertyTable::G4ParticlePropertyTable(), G4ParticleTypeConverter::G4ParticleTypeConverter(), G4Parton::G4Parton(), G4PhysicsListHelper::G4PhysicsListHelper(), G4PrimaryParticle::G4PrimaryParticle(), G4PrimaryTransformer::G4PrimaryTransformer(), G4ProcessManagerMessenger::G4ProcessManagerMessenger(), G4ProtonDecay::G4ProtonDecay(), G4ResonanceNames::G4ResonanceNames(), G4RToEConvForElectron::G4RToEConvForElectron(), G4RToEConvForGamma::G4RToEConvForGamma(), G4RToEConvForPositron::G4RToEConvForPositron(), G4RToEConvForProton::G4RToEConvForProton(), G4RunManager::G4RunManager(), G4RunManagerKernel::G4RunManagerKernel(), G4SDParticleFilter::G4SDParticleFilter(), G4SPBaryon::G4SPBaryon(), G4Track::G4Track(), G4UserEventAction::G4UserEventAction(), G4UserRunAction::G4UserRunAction(), G4UserStackingAction::G4UserStackingAction(), G4UserSteppingAction::G4UserSteppingAction(), G4UserTrackingAction::G4UserTrackingAction(), G4VDecayChannel::G4VDecayChannel(), G4VPhysicsConstructor::G4VPhysicsConstructor(), G4VUserPhysicsList::G4VUserPhysicsList(), G4VUserPrimaryGeneratorAction::G4VUserPrimaryGeneratorAction(), G4WorkerRunManager::G4WorkerRunManager(), GammaKnifeActionInitialization::GammaKnifeActionInitialization(), GammaRayTelPrimaryGeneratorAction::GammaRayTelPrimaryGeneratorAction(), GB01BOptrChangeCrossSection::GB01BOptrChangeCrossSection(), GB01PrimaryGeneratorAction::GB01PrimaryGeneratorAction(), GB02PrimaryGeneratorAction::GB02PrimaryGeneratorAction(), GB03PrimaryGeneratorAction::GB03PrimaryGeneratorAction(), GB04PrimaryGeneratorAction::GB04PrimaryGeneratorAction(), GB05BOptrSplitAndKillByCrossSection::GB05BOptrSplitAndKillByCrossSection(), GB05PrimaryGeneratorAction::GB05PrimaryGeneratorAction(), GB06BOptrSplitAndKillByImportance::GB06BOptrSplitAndKillByImportance(), GB06PrimaryGeneratorAction::GB06PrimaryGeneratorAction(), G4QGSParticipants::GenerateDeltaIsobar(), G4FTFModel::GenerateDeltaIsobar(), G4HtmlPPReporter::GenerateIndex(), HadrontherapyPrimaryGeneratorAction::GeneratePrimaries(), DicomPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPrimaryGeneratorAction::GeneratePrimaries(), PrimaryGenerator::GeneratePrimaryVertex(), G4WilsonAbrasionModel::GetAbradedNucleons(), G4HyperNucleiProperties::GetAtomicMass(), G4NucleiProperties::GetAtomicMass(), G4NucleiProperties::GetBindingEnergy(), G4UserPhysicsListMessenger::GetCurrentValue(), G4DynamicParticle::GetElectronMass(), G4TripathiCrossSection::GetElementCrossSection(), G4NuclNuclDiffuseElastic::GetInvCoulombElasticXsc(), G4DiffuseElastic::GetInvCoulombElasticXsc(), G4NuclNuclDiffuseElastic::GetInvElasticSumXsc(), G4DiffuseElastic::GetInvElasticSumXsc(), G4NuclNuclDiffuseElastic::GetInvElasticXsc(), G4DiffuseElastic::GetInvElasticXsc(), G4BinaryCascade::GetIonMass(), G4IonTable::GetIonTable(), G4NucleiProperties::GetMassExcess(), G4NucleiProperties::GetNuclearMass(), G4HyperNucleiProperties::GetNuclearMass(), G4StatMFFragment::GetNuclearMass(), G4Pythia6Decayer::GetParticleDefinition(), F04Trajectory::GetParticleDefinition(), WLSTrajectory::GetParticleDefinition(), G4SmoothTrajectory::GetParticleDefinition(), G4Trajectory::GetParticleDefinition(), RE04Trajectory::GetParticleDefinition(), getParticleTable(), G4ProcessPlacer::GetProcessManager(), G4ChipsProtonElasticXS::GetQ2max(), G4ChipsHyperonElasticXS::GetQ2max(), G4ChipsKaonPlusElasticXS::GetQ2max(), G4ChipsPionPlusElasticXS::GetQ2max(), G4ChipsAntiBaryonElasticXS::GetQ2max(), G4ChipsKaonMinusElasticXS::GetQ2max(), G4ChipsPionMinusElasticXS::GetQ2max(), G4ChipsNeutronElasticXS::GetQ2max(), PhysicsList::GetRange(), G4BaryonSplitter::GetSPBaryon(), G4IsotopeMagneticMomentTable::GetVerboseLevel(), G4IonTable::GetVerboseLevel(), GunPrimaryGeneratorAction::GunPrimaryGeneratorAction(), G4BinaryCascade::HighEnergyModelFSProducts(), G4FTFModel::Init(), lightions::Init(), antilightions::Init(), G4ErrorPropagator::InitG4Track(), G4DNAIonElasticModel::Initialise(), G4EmSaturation::InitialiseBirksCoefficient(), G4VPCData::initialize(), G4VUPLData::initialize(), G4INCL::ParticleTable::initialize(), G4VUserPhysicsList::InitializeProcessManager(), CML2PrimaryGenerationAction::inizialize(), G4BinaryLightIonReaction::Interact(), G4EMDissociationCrossSection::IsElementApplicable(), G4NucleiProperties::IsInStableTable(), G4FastSimulationManager::ListModels(), LXePrimaryGeneratorAction::LXePrimaryGeneratorAction(), main(), G4InuclNuclei::makeDefinition(), G4HadronBuilder::Meson(), G4ResonanceNames::MinMass(), MyPrimaryGeneratorActionFromFile::MyPrimaryGeneratorActionFromFile(), PrimaryGeneratorAction::Notify(), MyPrimaryGeneratorActionFromFile::Notify(), G4NucleiProperties::NuclearMass(), G4CollisionComposite::Resolve::operator()(), G4VDecayChannel::operator=(), OpNovicePrimaryGeneratorAction::OpNovicePrimaryGeneratorAction(), PyG4ParticleList::p_begin(), PyG4ParticleList::p_end(), Par01PrimaryGeneratorAction::Par01PrimaryGeneratorAction(), Par02PrimaryGeneratorAction::Par02PrimaryGeneratorAction(), G4AdjointTrackingAction::PostUserTrackingAction(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), PrimaryGeneratorGun1::PrimaryGeneratorGun1(), PrimaryGeneratorGun2::PrimaryGeneratorGun2(), G4TextPPReporter::Print(), G4HtmlPPReporter::Print(), G4RunManagerKernel::PropagateGenericIonID(), G4LundStringFragmentation::Quark_AntiQuark_lastSplitting(), G4LundStringFragmentation::Quark_Diquark_lastSplitting(), RE01PrimaryGeneratorAction::RE01PrimaryGeneratorAction(), RE02PrimaryGeneratorAction::RE02PrimaryGeneratorAction(), RE03PrimaryGeneratorAction::RE03PrimaryGeneratorAction(), RE04PrimaryGeneratorAction::RE04PrimaryGeneratorAction(), RE05PrimaryGeneratorAction::RE05PrimaryGeneratorAction(), RE06PrimaryGeneratorAction::RE06PrimaryGeneratorAction(), G4AdjointSimManager::RegisterAtEndOfAdjointTrack(), G4IonTable::Remove(), G4TextPPRetriever::Retrieve(), G4LMsdGenerator::SampleMx(), G4QuasiElasticChannel::Scatter(), PrimaryGeneratorAction::SetDefaultKinematic(), IORTPrimaryGeneratorAction::SetDefaultPrimaryParticle(), StackingAction::SetKill(), G4BinaryLightIonReaction::SetLighterAsProjectile(), G4EmConfigurator::SetModelForRegion(), F04PhysicsListMessenger::SetNewValue(), G4FastSimulationMessenger::SetNewValue(), WLSPhysicsListMessenger::SetNewValue(), CexmcParticleGunMessenger::SetNewValue(), G4ProcessTableMessenger::SetNewValue(), G4UserPhysicsListMessenger::SetNewValue(), G4PSNofSecondary::SetParticle(), pyMedicalBeam::SetParticleByName(), pyG4ParticleGun::SetParticleByName(), G4PrimaryParticle::SetPDGcode(), G4RunManagerKernel::SetPhysics(), G4RunManagerKernel::SetScoreSplitter(), G4RTPrimaryGeneratorAction::SetUp(), G4MTRunManagerKernel::SetUpDecayChannels(), G4RunManagerKernel::SetupPhysics(), G4WorkerRunManagerKernel::SetupShadowProcess(), G4RunManagerKernel::SetupShadowProcess(), G4RayShooter::Shoot(), G4GlobalFastSimulationManager::ShowSetup(), G4BaryonSplitter::SplitBarion(), TSPrimaryGeneratorAction::TSPrimaryGeneratorAction(), G4ProductionCutsTable::UpdateCoupleTable(), G4AdjointPrimaryGeneratorAction::UpdateListOfPrimaryParticles(), XrayFluoMercuryPrimaryGeneratorAction::XrayFluoMercuryPrimaryGeneratorAction(), XrayFluoPlanePrimaryGeneratorAction::XrayFluoPlanePrimaryGeneratorAction(), G4ParticleDefinition::~G4ParticleDefinition(), G4RunManager::~G4RunManager(), and G4WorkerRunManagerKernel::~G4WorkerRunManagerKernel().
GetReadiness()
G4bool G4ParticleTable::GetReadiness () const
Referenced by G4Dineutron::Definition(), G4UnboundPN::Definition(), G4Diproton::Definition(), and export_G4ParticleTable().
GetVerboseLevel()
G4int G4ParticleTable::GetVerboseLevel () const
Referenced by export_G4ParticleTable(), G4ParticleDefinition::G4ParticleDefinition(), G4ParticleMessenger::GetCurrentValue(), G4HyperNucleiProperties::GetNuclearMass(), G4IsotopeMagneticMomentTable::GetVerboseLevel(), and G4IonTable::GetVerboseLevel().
Insert()
G4ParticleDefinition * G4ParticleTable::Insert (G4ParticleDefinition * particle)
Definition at line 365 of file G4ParticleTable.cc.
Referenced by G4ParticleDefinition::G4ParticleDefinition().
operator=()
G4ParticleTable & G4ParticleTable::operator= (const G4ParticleTable & right) protected
Definition at line 279 of file G4ParticleTable.cc.
Remove()
G4ParticleDefinition * G4ParticleTable::Remove (G4ParticleDefinition * particle)
Definition at line 438 of file G4ParticleTable.cc.
Referenced by G4Dineutron::Definition(), G4UnboundPN::Definition(), and G4Diproton::Definition().
RemoveAllParticles()
void G4ParticleTable::RemoveAllParticles ()
Definition at line 338 of file G4ParticleTable.cc.
Referenced by DeleteAllParticles(), and ~G4ParticleTable().
SetGenericIon()
void G4ParticleTable::SetGenericIon (G4ParticleDefinition *)
Referenced by G4GenericIon::Definition().
SetGenericMuonicAtom()
void G4ParticleTable::SetGenericMuonicAtom (G4ParticleDefinition *)
Referenced by G4GenericMuonicAtom::Definition().
SetReadiness()
void G4ParticleTable::SetReadiness (G4bool val = true)
Referenced by G4Dineutron::Definition(), G4Diproton::Definition(), G4UnboundPN::Definition(), export_G4ParticleTable(), main(), and G4RunManagerKernel::SetupPhysics().
SetVerboseLevel()
void G4ParticleTable::SetVerboseLevel (G4int value)
Referenced by export_G4ParticleTable(), and G4ParticleMessenger::SetNewValue().
size()
G4int G4ParticleTable::size () const
Definition at line 690 of file G4ParticleTable.cc.
Referenced by export_G4ParticleTable(), and getParticleTable().
SlaveG4ParticleTable()
void G4ParticleTable::SlaveG4ParticleTable ()
Definition at line 158 of file G4ParticleTable.cc.
WorkerG4ParticleTable()
void G4ParticleTable::WorkerG4ParticleTable ()
Definition at line 163 of file G4ParticleTable.cc.
Referenced by G4WorkerRunManager::G4WorkerRunManager(), and GetParticleTable().
Field Documentation
fDictionary
G4ThreadLocal G4ParticleTable::G4PTblDictionary * G4ParticleTable::fDictionary = nullptr static
Definition at line 190 of file G4ParticleTable.hh.
Referenced by DestroyWorkerG4ParticleTable(), entries(), FindParticle(), G4ParticleTable(), GetDictionary(), GetParticleTable(), Insert(), RemoveAllParticles(), size(), WorkerG4ParticleTable(), and ~G4ParticleTable().
fDictionaryShadow
G4ParticleTable::G4PTblDictionary * G4ParticleTable::fDictionaryShadow = nullptr static
Definition at line 213 of file G4ParticleTable.hh.
Referenced by contains(), FindParticle(), G4ParticleTable(), Insert(), and Remove().
fEncodingDictionary
G4ThreadLocal G4ParticleTable::G4PTblEncodingDictionary * G4ParticleTable::fEncodingDictionary = nullptr static
Definition at line 192 of file G4ParticleTable.hh.
Referenced by DestroyWorkerG4ParticleTable(), FindParticle(), G4ParticleTable(), GetEncodingDictionary(), Insert(), WorkerG4ParticleTable(), and ~G4ParticleTable().
fEncodingDictionaryShadow
G4ParticleTable::G4PTblEncodingDictionary * G4ParticleTable::fEncodingDictionaryShadow = nullptr static
Definition at line 215 of file G4ParticleTable.hh.
Referenced by FindParticle(), G4ParticleTable(), Insert(), and Remove().
fgParticleTable
G4ParticleTable * G4ParticleTable::fgParticleTable =nullptr static
Definition at line 202 of file G4ParticleTable.hh.
Referenced by GetParticleTable(), and ~G4ParticleTable().
fIonTable
G4IonTable * G4ParticleTable::fIonTable = nullptr static
Definition at line 204 of file G4ParticleTable.hh.
Referenced by DestroyWorkerG4ParticleTable(), G4ParticleTable(), GetIonTable(), Insert(), Remove(), RemoveAllParticles(), WorkerG4ParticleTable(), and ~G4ParticleTable().
fIterator
G4ThreadLocal G4ParticleTable::G4PTblDicIterator * G4ParticleTable::fIterator = nullptr static
Definition at line 191 of file G4ParticleTable.hh.
Referenced by DeleteAllParticles(), DestroyWorkerG4ParticleTable(), DumpTable(), G4ParticleTable(), GetIterator(), GetParticle(), WorkerG4ParticleTable(), and ~G4ParticleTable().
fIteratorShadow
G4ParticleTable::G4PTblDicIterator * G4ParticleTable::fIteratorShadow = nullptr static
Definition at line 214 of file G4ParticleTable.hh.
Referenced by G4ParticleTable(), and WorkerG4ParticleTable().
fParticleMessenger
G4ThreadLocal G4ParticleMessenger * G4ParticleTable::fParticleMessenger = nullptr static
Definition at line 189 of file G4ParticleTable.hh.
Referenced by CreateMessenger(), DeleteMessenger(), DestroyWorkerG4ParticleTable(), G4ParticleTable(), and ~G4ParticleTable().
fParticleMessengerShadow
G4ParticleMessenger * G4ParticleTable::fParticleMessengerShadow = nullptr static
Definition at line 212 of file G4ParticleTable.hh.
genericIon
G4ParticleDefinition* G4ParticleTable::genericIon private
Definition at line 221 of file G4ParticleTable.hh.
genericMuonicAtom
G4ParticleDefinition* G4ParticleTable::genericMuonicAtom private
Definition at line 222 of file G4ParticleTable.hh.
noName
const G4String G4ParticleTable::noName private
Definition at line 218 of file G4ParticleTable.hh.
Referenced by GetParticleName().
readyToUse
G4bool G4ParticleTable::readyToUse private
Definition at line 220 of file G4ParticleTable.hh.
Referenced by CheckReadiness(), DeleteAllParticles(), Remove(), RemoveAllParticles(), and ~G4ParticleTable().
verboseLevel
G4int G4ParticleTable::verboseLevel private
Definition at line 179 of file G4ParticleTable.hh.
Referenced by DeleteAllParticles(), DumpTable(), FindParticle(), GetParticle(), Insert(), Remove(), and RemoveAllParticles().
The documentation for this class was generated from the following files:
source/particles/management/include/G4ParticleTable.hh
source/particles/management/src/G4ParticleTable.cc